### ISSUE TITLE
Unable to install new version of npm

### ISSUE THREAD

**Issue by chennakeshavaSoC** [nodejs/help#100]
Hi,

I am unable to upgrade to newer version of npm.

The logs are:
/package$ sudo make install
node cli.js install -g -f 
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "node" "/Softwares/package/cli.js" "install" "-g" "-f"
npm ERR! node v0.6.12
npm ERR! npm  v3.7.5

npm ERR! Object #<Object> has no method 'exists'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Softwares/package/npm-debug.log
npm ERR! code 1
make: *** [install] Error 1

Thanks,
Chenna

**Comment by bnoordhuis** [comment]
Please report npm issues [here](https://github.com/npm/npm/issues) but before you do, make sure you're using a still supported version of node.js, i.e., v0.10 or newer.  v0.6.12 is almost four years old to the day.
