### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Sc-studio** [nodejs/help#1000]
the problem? How can I solve it?
![image](https://user-images.githubusercontent.com/34097384/33377448-9328cca0-d522-11e7-9cb4-ec6b531304a7.png)

**Comment by gibfahn** [comment]
cc/ @nodejs/platform-windows

**Comment by shellberg** [comment]
Perhaps exactly the same as in #998 ?

**Comment by lordKnighton** [comment]
@Sc-studio Are you still having this issue?

**Comment by tniessen** [comment]
If you are, please post the installation logs here.
