### ISSUE TITLE
How does fstat work cross-platform

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1001]
* **Node.js Version 6,7,8,9**:
* ***Unix and MacOS**:

I was looking at this StackExchange answer
https://unix.stackexchange.com/a/383132/113238

On a *nix machine you can use a file descriptor and find:

`/proc/<pid>/fd/x`

(Something like that). But this is not possible on MacOS...my question is how `fstat` works so that it can take a `fd` and find out stats info about that fd, like in the StackExchange answer.

**Comment by bnoordhuis** [comment]
`fstat()` is a system call on UNIX platforms, there's no need to go through the procfs.

**Comment by the1mills** [comment]
Good point, I guess my question is how fstat works on MacOS, but I will look at the docs

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if this did not help you.
