### ISSUE TITLE
ERROR UPDATE NODE

### ISSUE THREAD

**Issue by joaovelozo** [nodejs/help#1004]
C:>npm install -g update-node
npm ERR! not a package C:\update-node
npm ERR! addLocal Could not install C:\update-node
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\node.exe" "C:\node_modules\npm\bin\npm-cli.js" "install" "-g" "update-node"
npm ERR! node v4.5.0
npm ERR! npm v2.15.9
npm ERR! path C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR! C:\npm-debug.log

**Comment by lordKnighton** [comment]
@joaovelozo Have you ran `npm install -g update-node` and see what's going on from there. 
Plus+ post your `npm-debug.log` file

**Comment by joaovelozo** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\node.exe',
1 verbose cli   'C:\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'update-node' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose install initial load of C:\package.json
5 verbose readDependencies loading dependencies from C:\package.json
6 silly cache add args [ 'update-node', null ]
7 verbose cache add spec update-node
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'update-node',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: 'update-node',
8 silly cache add   spec: 'C:\\update-node',
8 silly cache add   type: 'local' }
9 silly addLocalTarball shasum (computed) bb17ebfeed34d3c1c60b0e148d98963865d518d7
10 verbose addTmpTarball C:\update-node not in flight; adding
11 verbose correctMkdir C:\Users\JoaoVelozo\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
12 verbose makeDirectory C:\Users\JoaoVelozo\AppData\Roaming\npm-cache creation not in flight; initializing
13 verbose makeCacheDir UID & GID are irrelevant on win32
14 verbose addTmpTarball validating metadata from C:\update-node
15 verbose tar unpack C:\update-node
16 verbose tar unpacking to C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672
17 silly gentlyRm C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672 is being purged
18 verbose gentlyRm don't care about contents; nuking C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672
19 silly gunzTarPerm modes [ '777', '666' ]
20 error not a package C:\update-node
21 error addLocal Could not install C:\update-node
22 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672\package.json'
22 verbose stack     at Error (native)
23 verbose cwd C:\
24 error Windows_NT 10.0.15063
25 error argv "C:\\node.exe" "C:\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "update-node"
26 error node v4.5.0
27 error npm  v2.15.9
28 error path C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672\package.json
29 error code ENOENT
30 error errno -4058
31 error syscall open
32 error enoent ENOENT: no such file or directory, open 'C:\Users\JOAOVE~1\AppData\Local\Temp\npm-5072-e9eb08b6\unpack-a7f300429672\package.json'
32 error enoent This is most likely not a problem with npm itself
32 error enoent and is related to npm not being able to find a file.
33 verbose exit [ -4058, true ]

**Comment by lordKnighton** [comment]
First of all, it would be helpful, if you communicated how you got to this point: 
(e.g) You have a node application up & running with no errors but when you try to install 
a needed package, then it throws errors.  Or just having problems installing node

@joaovelozo I'm gonna recommend you open a new issue over at - https://github.com/thenativeweb/update-node

**Comment by joaovelozo** [comment]
Tanks

**Comment by gireeshpunathil** [comment]
closing as referred to the right repo
