### ISSUE TITLE
9.2.0 throwing error "The "digest" argument must be one of type string or null"

### ISSUE THREAD

**Issue by aakarshan29** [nodejs/help#1006]
* **Node.js Version**: 9.2.0
* **OS**: CentOS 6
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

After upgrading the nodejs to version 9.2.0, on CentOS 6(Sentora), I am not able to access the application which requires login.

TypeError [ERR_INVALID_ARG_TYPE]: The "digest" argument must be one of type string or null
at _pbkdf2 (internal/crypto/pbkdf2.js:35:11)
at Object.pbkdf2 (internal/crypto/pbkdf2.js:25:10)

**Comment by leftstick** [comment]
You might missed the `digest` argument while calling `crypto.pbkdf2Sync`.

![screen shot 2017-12-18 at 10 52 38 am](https://user-images.githubusercontent.com/1059956/34087995-97282bf2-e3e1-11e7-95ef-ddb096dd1d0b.png)

**Comment by gireeshpunathil** [comment]
@aakarshan29 - are you able to resolve your issue by following @leftstick 's suggestion?

**Comment by gireeshpunathil** [comment]
closing as answered.
