### ISSUE TITLE
Best way to parse env variables from string

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1008]
This regards Node.js versions 6+

Say I have this:

```bash
node foo.js --child-env="foo=bar zim='zam' rim=raf"
```

What is the best way to parse "--child-env" and turn it into an object like so:

```js
let childEnv = {
  foo : 'bar',
  zim : 'zam',
  rim : 'raf'
}
```

I was looking at `querystring`, but not sure if it's the best way to do it

https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options

**Comment by ORESoftware** [comment]
If I use this 

```js
const qs = require('querystring');
const str = `foo=bar zim='zam' rim=raf`;
const x = qs.parse(String(str), ' ', '=');
```

I get this

x => `{ foo: 'bar', zim: '\'zam\'', rim: 'raf' }`

**Comment by ORESoftware** [comment]
more specifically this is the problem, parsing this:

``foo=bar zim="zam bia" rim=raf``

becomes

`{ foo: 'bar', zim: '"zam', 'bia"': '', rim: 'raf' }`

**Comment by ORESoftware** [comment]
what I am doing now is starting a Node.js child process, and then "echo"ing the env variables back as JSON:

```
const JSONStdio = require('json-stdio');
console.log(JSONStdio.logToStdout({env: process.env}));
```

but I am looking for a way to do this without starting a child process if possible

**Comment by the-pirate-bay** [comment]
@ORESoftware Is [this](https://github.com/the-pirate-bay/test/tree/master/env) what you're looking for?

**Comment by ORESoftware** [comment]
@the-pirate-bay thanks, did you write that up to answer this question? nice work, I have a clever solution too

**Comment by gireeshpunathil** [comment]
close-able then?

**Comment by gireeshpunathil** [comment]
Closing as resolved based on the [comment](https://github.com/nodejs/help/issues/1008#issuecomment-349632712) . @ORESoftware please let me know if that is not the case.

**Comment by avivkeller** [comment]
Please don't comment on issues that have been closed for seven years, it's unnecessary noise.
