### ISSUE TITLE
How to get array_buffer_allocator of node isolate?

### ISSUE THREAD

**Issue by helloshuangzi** [nodejs/help#1009]
Hi, 
As described in the subject, does node provide a way to get its array_buffer_allocator after [the isolate is created as below](https://github.com/nodejs/node/blob/a803bcaab8420d3c4d29dbc3d0c3b641ceafdfc7/src/node.cc).
```c++
inline int Start(uv_loop_t* event_loop,
                 int argc, const char* const* argv,
                 int exec_argc, const char* const* exec_argv) {
  Isolate::CreateParams params;
  ArrayBufferAllocator allocator;
  params.array_buffer_allocator = &allocator;
#ifdef NODE_ENABLE_VTUNE_PROFILING
  params.code_event_handler = vTune::GetVtuneCodeEventHandler();
#endif

  Isolate* const isolate = Isolate::New(params);
...
```
Or do you know whether v8 provide some API to get it?

I am working on [napajs](https://github.com/Microsoft/napajs), trying to make SharedArrayBuffer transportable between multiple napa isolates. This allocator is required to handle disposition of SharedArrayBuffer externalized contents.

Thank you very much,
Allen.

**Comment by bnoordhuis** [comment]
At the moment you cannot do that.

**Comment by gireeshpunathil** [comment]
closing as answered.
