### ISSUE TITLE
Application Problems

### ISSUE THREAD

**Issue by zlokomatic** [nodejs/help#101]
Hi,

one of our applications is making problems for a long time now and i hope someone can help.

We are running a chat server using socket.io.
Userdata is stored in redis and sent when necessary. 

This works after startup and for some time running. 
But as far as i can see in top the memory is filling up over time and after some more time the cpu stays more or less at 100%.
Then the application starts getting slow and after a while totaly stops responding. It is still running however but just does not respond anymore and even socket.io connections are not handled anymore.

Using heapdump i already found we had one memory leak because we used socket.leave(roomname) in the ondisconnect function and using strace we could see there are many epoll_wait calls.

The biggest problem is i can not reproduce behaviour in a test environment but it only happens live.

So does anyone have any more pointers at how and what i could test to see what the real issue is?

We are currently using node v5.5.0 but also had this problems with node v0.12 and v4.x.

**Comment by kelthenoble** [comment]
did you already fix the memory leak?

**Comment by kkc** [comment]
did you try to profile your program?
https://nodejs.org/en/docs/guides/simple-profiling/

**Comment by kelthenoble** [comment]
+1 
> https://nodejs.org/en/docs/guides/simple-profiling/

**Comment by zlokomatic** [comment]
With profiling i could not find any problems. 
And the cpu usage doesnt seem to be the problem until the memory fills up after some time

**Comment by lordKnighton** [comment]
closing for now, If you're still having issues with this, reopen an pursue a solution

happy coding
