### ISSUE TITLE
Ignore specific node_modules Folder

### ISSUE THREAD

**Issue by ulfgebhardt** [nodejs/help#1011]
* **Node.js Version**:
v8.9.1
* **OS**:
Windows & Mac
* **Scope (install, code, runtime, meta, other?)**:
runtime/other
* **Module (and version) (if relevant)**:
React-Native & Electron

I use **React-Native in combination with Electron** to build iOS, Android, Desktop and Webversions of my  Application. Electron generates a folder node_modules under ressource in its output. This folder is required to run the Desktop Application. Once the Desktop Version is compiled, node fails to build the iOS and Android, aswell as the Web Application since it will find **two node_modules folders**, containing **duplicate modules**.

This results in following errors:

```
Scanning folders for symlinks in D:\sources\demokratie-live\democracy-client\node_modules (66ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running Metro Bundler on port 8081.                                       │
 │                                                                            │
 │  Keep Metro Bundler running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own Metro Bundler  instance if you    │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   D:\sources\demokratie-live\democracy-client


Metro Bundler ready.

Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `D:\sources\demokratie-live\democracy-client\index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:

  * `D:\sources\demokratie-live\democracy-client\dist\win-unpacked\resources\app.asar.unpacked\node_modules\react-native\package.json`
  * `D:\sources\demokratie-live\democracy-client\node_modules\react-native\package.json`
```

The question is: **How do I tell node to ignore a certain node_modules folder or specify which one it should use?**

Rel: https://github.com/demokratie-live/democracy-client/tree/desktop

Grüße Ulf

<3

**Comment by bnoordhuis** [comment]
That looks like an issue with that bundler tool, not with node itself.  You should probably file an issue with that project if it's not in their documentation (and close this issue.)

**Comment by ulfgebhardt** [comment]
You are correct - i found an issue @ metro bundler repo describing the same problem - thanks
rel: https://github.com/facebook/metro/issues/97

Grüße Ulf

<3

**Comment by ProfNandaa** [comment]
@ulfgebhardt - you can close this now?

**Comment by ulfgebhardt** [comment]
It is not solved, but i will close, ty for your hint

Grüße Ulf

<3
