### ISSUE TITLE
Red Hat installation issues

### ISSUE THREAD

**Issue by nbarr007** [nodejs/help#1013]
* **Node.js Version**:v0.10.36
* **OS**:redhat-release-server-7.2-9.el7.x86_64
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Hi Support,

Could you please review the log below and advise? From your page can see that RHEL 7 64bit is supported

Many thanks in advance

Rgd's

Norman

Installing the NodeSource Node.js 8.x repo...

Inspecting system...
•rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
•uname -m

Confirming "el7-x86_64" is supported...
•curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

Your distribution, identified as "redhat-release-server-7.2-9.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by bnoordhuis** [comment]
Any reason you're opening an issue here and not over at https://github.com/nodesource/distributions/issues, like it says in the message?

**Comment by nbarr007** [comment]
Cheers Ben,

I have not had a response from the other forum, so thought I might get one from this one

Rgd’s

**Comment by gireeshpunathil** [comment]
as already suggested, this be report at https://github.com/nodesource/distributions/issues
