### ISSUE TITLE
Initialisation Vector / Nonce format unclear

### ISSUE THREAD

**Issue by smartyw** [nodejs/help#1014]
* **Node.js Version**: 8.9.2
* **OS**: All
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: Crypto

When using a crypto algorithm like aes-128-ccm with the createCipheriv function:

crypto.createCipheriv(algorithm, key, iv[, options])

What are the rules regarding the iv value? Does the caller need to supply a fully formed IV which includes the FLAGS field with the size of length field and integrity value check field size included in it? i.e. is the iv parameter always 16 octets in length?

Thanks

**Comment by bnoordhuis** [comment]
Is your question how to use CCM?  It's not supported at the moment, see https://github.com/nodejs/node/issues/2383.

**Comment by smartyw** [comment]
I know how to use it with other APIs, but was getting errors relating to the iv parameter in node.js Crypto API so I was thinking I had to format the IV, per my question.

Thanks.... I saw aes-128-ccm in the list of ciphers so thought that meant it was supported.

Do you know of a suitable module that supports aes-ccm?

**Comment by bnoordhuis** [comment]
Can't vouch for it but https://www.npmjs.com/package/node-aes-ccm is the package mentioned in the issue.

**Comment by smartyw** [comment]
Thanks! I'll give it a try :-)

**Comment by gireeshpunathil** [comment]
@smartyw - hope your issue is resolved?

**Comment by smartyw** [comment]
Thank you, yes.
