### ISSUE TITLE
How does Node.js execute functions

### ISSUE THREAD

**Issue by cexewupuv** [nodejs/help#1016]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I don't know much about JavaScript engine v8, but I'm wondering how does Node.js (and generaly v8 engine) execute functions? Node.js reads source javascript file and then parses it, but how then execute it, since it is an interpreter?

I mean, there are two possibilities, but I dont know which one Node.js uses: 1) Does it store parsed function as array of instructions and then at runtime event loop reads one instruction at a time and call some internal c++ routine which performs that instruction or 2) convert parsed function to assemblies depending on the actual architecture and then simply jump to these machine instructions once the function is called?

I think the second one is true, but I'm not sure, so that is why I'm asking. I tried to ask on StackOverflow, but after few feeks I didn't get any answers and no votes at all. Simply, the question was completely ignored, so I'm asking here.

Thank you anyone who answers in advanced. sorry my bed english.

**Comment by addaleax** [comment]
Maybe this helps you? https://v8project.blogspot.de/2016/08/firing-up-ignition-interpreter.html

The general idea is that there are two compilers inside of V8, one that runs bytecode (that is generated from the abstract syntax tree itself) for code that has not yet been run very often and for which the variable types etc. cannot be inferred yet (Ignition) and one for code that has run at least a few times and for which the variable types are known, and thus optimized machine-language code can be generated (TurboFan).

The article also mentions Crankshaft as an additional compiler, but that one is gone in Node 8 + 9 and has fully been replaced by TurboFan. If you want to know more about how these compiler pipelines work, their names (TurboFan + Ignition) should be a good pair of keywords to look for.

**Comment by cexewupuv** [comment]
That article explains very good. Thanks for fast response.

**Comment by NickNaso** [comment]
@cexewupuv Sorry for my late in answer but I think that the following resources could be help you to understand how JavaScript code is executed:

- [KEYNOTE- The V8 Engine and Node.js](https://youtu.be/PsDqH_RKvyc)

- [Keynote slides](https://fhinkel.github.io/V8AndNode/NodeInteractive2017/assets/player/KeynoteDHTMLPlayer.html#0)

In general on v8 project blog you can find all you need.
