### ISSUE TITLE
How to implement std::cout and std::cin in Node.js

### ISSUE THREAD

**Issue by 6-8-axnw1bom81v5xa3nh48c** [nodejs/help#1020]
I was programming in C++ for very long time and now I moved to JavaScript, but I really miss `std::cout` and `std::cin`. Is there any way I can implement it in Node.js?

Here is my attempt:

```JavaScript
setTimeout(main);
var a;

function main(){
  a = "C++";
  cout << "Hello " << a << " World!";
}

var cout = {
  [Symbol.toPrimitive]: () => {
    var stack = new Error().stack;
    var line = stack.match(/(?:.*(?:\r\n|\r|\n)){2}.*(\d+)\:\d+\)/)[1] | 0;
    var code = arguments.callee.toString().split(/\r\n|\r|\n/)[line - 1];
    var str = code.replace(/cout\s*<</, '').replace(/<</g, '+');
    var result = eval(str);

    console.log(result);
    return null;
  }
};
```

But, it has several problems:

1. It cannot be exported to other modules
2. It cannot print local variables (which are not visible from outer scope)
3. It doesn't work for multiline print.

**Comment by ORESoftware** [comment]
```js
process.stdin
process.stdout
process.stderr
```

are all streams in Node.js - it's asynchronous only

to collect data from process.stdin

use:

```js
let stdin = '';

process.stdin.on('data', function(chunk){
   stdin += String(chunk);
});
```

to write to stdout without using `console.log()`, you would use

```js
process.stdout.write();
```

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
Thank you. However, I think you misunderstood my question. I know about `stdin` and `stdout` streams and how they work, but I am looking for a way to use literal C++ notation using overloaded bitwise shl operator (I mean `<<`). See my example code snippet in the question, hope it will explain better what I'm trying to do.

**Comment by ORESoftware** [comment]
Yeah I don't see why you'd want to overload operators - why not just use methods?

`getReadableStream().pipe(process.stdout);`

**Comment by ORESoftware** [comment]
it looks like you've read that SO article and you're trying to manipulate toString() / Symbol.toPrimitive etc on an object, yeah so idk

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
> Yeah I don't see why you'd want to overload operators - why not just use methods?

It is more readable to me when using C++ syntax instead of `console.log`.

> I don't think JS supports operator overloading.

I know ES standard doesn't specify operator overloading, but I still think it is possible to achieve something very similar to it.

> But I think it's kinda verbose?

You want to say that `cin >> str` is more verbose than

```JavaScript
var stdin = '';

process.stdin.on('data', function(chunk){
   stdin += String(chunk);
});
```

I really don't see how is C++ way more verbose.

> It looks like you've read that SO article.

No, I actually didn't read that article. Also, notice that the article you linked to talks about something different. I'm not trying here just to return something, What my script does (but it is still not the best solution) is to evaluate the line where `cout` appears and print it to the console. Your article doesn't talk about anything even similar to it.

But, anyways, thank you ore software for trying to help, I really appreciate it. :)

**Comment by ORESoftware** [comment]
well maybe you can show the C++ code that continues to read from stdin, you'd need a while loop?

the stdin in code above, will read all data sent to `process.stdin`, the equivalent code with C++ would require a `while` loop.

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
@ORESoftware Thanks, I'll try your suggestions.
