### ISSUE TITLE
Question on async hooks when used together with DB operations

### ISSUE THREAD

**Issue by sebastian-curland** [nodejs/help#1021]
* **Node.js Version**: 8.9.1
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: behavior
* **Module (and version) (if relevant)**: async hooks

Hi, 
I have a web application with node + express.
What I want to achieve is to be able to access a request id, that is generated when a new request comes in, and access that request id in any function in the code (similar to what continuation local storage does https://github.com/othiym23/node-continuation-local-storage).

The way I implement that is the following. Every time a request comes in a request id is created and, using async hooks, I store that request id for the current _executionAsyncId_. 
Also, the request id is stored for all the child async resources that are created from the code that handles the request.
So, in other words, I have a "tree" of async resources associated with a request id.

The code works well except for cases where I need to access a DB (I'm using rethinkdb but I don't think it matters which DB).
What is happening is that the request id is _undefined_ in the functions that access the DB.
I noticed that the "tree" of async resources when calling those functions is different from the tree of the async resources of the request.

This is an example of those trees that illustrates the issue:
When a request comes in and the _executionAsyncId_ is 281, all the following async resources will be associated to the same request id: 
```js
PROMISE(asyncId 284): trigger: 281 currentId: 281
PROMISE(asyncId 285): trigger: 284 currentId: 281
PROMISE(asyncId 286): trigger: 285 currentId: 281
Immediate(asyncId 287): trigger: 285 currentId: 285
Immediate(asyncId 288): trigger: 287 currentId: 287
Immediate(asyncId 289): trigger: 288 currentId: 288
TickObject(asyncId 290): trigger: 289 currentId: 289
```
Let's say the request calls a function that accesses the DB to get data and the callback function has 
_executionAsyncId_ 298. Below are the async resources related to async id 298
```js
Immediate(asyncId 44): trigger: 25 currentId: 25
Timeout(asyncId 45): trigger: 44 currentId: 44
TCPWRAP(asyncId 104): trigger: 45 currentId: 45
Immediate(asyncId 231): trigger: 104 currentId: 104
TCPWRAP(asyncId 239): trigger: 231 currentId: 231
Immediate(asyncId 292): trigger: 239 currentId: 239
Immediate(asyncId 296): trigger: 292 currentId: 292
Immediate(asyncId 297): trigger: 296 currentId: 296
Immediate(asyncId 298): trigger: 297 currentId: 297
```
As can be seen, the trees don't have a common node, so in the callback function, when executionAsyncId is 298, there is no request id associated to that async id.

**So my question is why this is happening? I would like to understand this behavior.**

When the node server starts, a DB connection pool is created, so my theory is that the async resources created when accessing the DB are childs of the async resources created when the connection pool was created (and that tree is not related to the async resources created when handling the express request).

Another thing I noticed is that if I wrap the  functions that access the DB with Promise.resolve() then everything works well. So I assume that creating a Promise will connect the async resources of the DB with the ones created as part of the request.
**Am I correct with this conclusion?** 

Thanks in advance for your help!

This is my async hooks code:
```js
'use strict'

const asyncHooks = require('async_hooks')
const uuid = require('uuid')
const contextMap = new Map()

const asyncHook = asyncHooks.createHook({ init, before, after, destroy })
asyncHook.enable()

function init (asyncId, type, triggerAsyncId, resource) {
  // Store same request object for child async resources
  if (contextMap.has(triggerAsyncId)) {
    contextMap.set(asyncId, contextMap.get(triggerAsyncId))
  }
}

function before (asyncId) {
}

function after (asyncId) {
}

function destroy (asyncId) {
  if (contextMap.has(asyncId)) {
    contextMap.delete(asyncId)
  }
}

module.exports.createRequestContext = function (requestId) {
  contextMap.set(asyncHooks.executionAsyncId(), requestId)
  return requestId
}

module.exports.getRequestContext = function () {
  return contextMap.get(asyncHooks.executionAsyncId())
}

// express middleware
module.exports.setAsyncHooksOnRequest = function (data) {
  return (req, res, next) => {
    module.exports.createRequestContext(req, uuid())
    next()
  }
}
```

**Comment by domarmstrong** [comment]
#1036

**Comment by ORESoftware** [comment]
@trevnorris maybe can provide some insight? thx

**Comment by sebastian-curland** [comment]
@AndreasMadsen @refack @trevnorris 
Can you help with this issue?

**Comment by AndreasMadsen** [comment]
@sebastian-curland There is definitely something odd with `module.exports.createRequestContext` you call it with two parameters but the function only accepts one. Anyway, I think this is just an issue with your issue code and not your actual implementation.

> When the node server starts, a DB connection pool is created, so my theory is that the async resources created when accessing the DB are childs of the async resources created when the connection pool was created (and that tree is not related to the async resources created when handling the express request).

Yes, this is very correct. The solution is to send a pull request to the DB module that "fixes" the context such that it doesn't come from the pool but from where something was inserted into the pool.

```js
const { AsyncResource } = require('async_hooks') 

function query(object, callback) {
  const resource = new AsyncResource('rethinkdb-query', { requireManualDestroy: true })
  pool.insert(object, function (err, result) {
    try {
      resource.emitBefore()
      callback(err, result)
    } finally {
      resource.emitAfter()
      resource.emitDestroy()
    }
  })
}
```

**Comment by sebastian-curland** [comment]
Thanks @AndreasMadsen.
Regarding `module.exports.createRequestContext`, my mistake, I changed the original code when I copy/pasted it here, originally that function accepts two parameters.

So, why when wrapping the DB functions with `Promise.all` or `Promise.resolve` it works well? 
Also, is there other way to workaround this using async_hooks module?

**Comment by domarmstrong** [comment]
Wrapping with Promise.all you are creating a new promise in the current context and then chaining onto that, rather than chaining onto the promise created out of context. Promise.resolve still seems to be run in the context of the original promise, I couldn't get resolve to work as you described, but I didn't try with you're code example.

@AndreasMadsen so is the solution really going to have to be to make PRs to every library we encounter that caches promises, because it seems to be a fairly common pattern?

Another way to solve it would be if we had a way to bind to an execution id. For example:

```
const async_hooks = require('async_hooks');

function doAThing() {
  const dataFetcher = async_hooks.bindExecutionAsyncId(() => getSomeData());
  brokenAsyncLib(dataFetcher).then(async_hooks.bindExecutionAsyncId((data) => {}));
}
```

If we had some way to bind the scope of the code that we control that would help. But I don't think its possible without some intervention from node.

**Comment by sebastian-curland** [comment]
@gireeshpunathil - yes, this is still outstanding although the workaround with Promise.all (or using async/await) will do the trick.

**Comment by gireeshpunathil** [comment]
the solution provided was to fix (or propose to fix) it at the third party DB layer `graduating` the context from the pool where connections are re-used, to a more lower level call stack where the queries are distinguishable from each other.

This is a great and probably the straightforward solution, but becomes problematic if different modules have similar patterns. 

So the outstanding question is (In my understanding): Is it possible to associate unique IDs to transactions with the help from core.

**Comment by AndreasMadsen** [comment]
> So the outstanding question is (In my understanding): Is it possible to associate unique IDs to transactions with the help from core.

No.

Some examples: 

* A TCP connection can either be part of a pool or an individual query.
* A Promise can either be a lazy initializer or an individual async operation.

There is no way to distinguish between these different cases, the third party module has to provide some metadata to help us understand the meaning and we provide an API for that. `async_hooks` understand the "individual query" and even gives you enough information about Promises that is useful for both scenarios. However, it is not technically feasible for us to do any better than that.

There has been some talk about "fixing" this on a language level but even that would require changes to the third-party modules, so I see little difference in terms of required effort from third-party authors.

**Comment by gireeshpunathil** [comment]
closing as answered, thanks!

**Comment by jpollard-cs** [comment]
@AndreasMadsen re async hooks

> the third party module has to provide some metadata to help us understand the meaning and we provide an API for that

Could you please provide a link for this? I'm assuming it's not part of the async hook API as documented here? https://nodejs.org/api/async_hooks.html

**Comment by ofrobots** [comment]
@jpollard-cs The `AsyncResource` concept mentioned in the [JavaScript Embedder API](https://nodejs.org/api/async_hooks.html#async_hooks_javascript_embedder_api) section in the linked doc is the API that third party JS libraries can use. There is also a lower level API AsyncResource available for [N-API](https://nodejs.org/api/n-api.html#n_api_custom_asynchronous_operations) and [Nan](https://github.com/nodejs/nan/blob/master/doc/node_misc.md#api_nan_asyncresource) native modules can use.

**Comment by jpollard-cs** [comment]
@ofrobots thank you!
