### ISSUE TITLE
How to catch CALL_AND_RETRY_LAST error

### ISSUE THREAD

**Issue by ghost** [nodejs/help#1026]
* **Node.js Version:** v9.2.0
* **OS:** Win7; Win8.1; Win10; Ubuntu17.0
* **Scope:** Runtime
* **Module:** /

I tried to execute this code

```JavaScript
'use strict';

try{
  var a = () => [...new Array(1e9)].map(a);
  a();
}catch(err){
  console.log(err);
}
```

And instead of printing the error to the console, the application crashed. This is what I got:

```
<--- Last few GCs --->

[2068:0000008A050D1DC0]    10487 ms: Mark-sweep 577.7 (585.1) -> 577.7 (585.1) MB, 202.4 / 0.0 ms  allocation failure GC in old space requested
[2068:0000008A050D1DC0]    10692 ms: Mark-sweep 577.7 (585.1) -> 577.7 (581.6) MB, 204.4 / 0.0 ms  last resort GC in old space requested
[2068:0000008A050D1DC0]    10895 ms: Mark-sweep 577.7 (581.6) -> 577.7 (581.6) MB, 203.3 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

The process terminated with exit code `134`. I want to somehow catch these error like all other errors. Is there a way to capture such errors inside some sort of `try..catch` block?

Thanks.

**Comment by bnoordhuis** [comment]
> Is there a way to capture such errors inside some sort of try..catch block?

No.

**Comment by cexewupuv** [comment]
I don't mean exactly try catch block, I mean any way to prevent crashing application. So, basically, if such error happens, my goal is to somehow continue running the application without exiting. I dont know how to deal with such errors in node.js

**Comment by bnoordhuis** [comment]
You can't, out-of-memory errors are fatal.  You're probably looking for a tool like pm2 or forever (or systemd, on ubuntu) to restart your application after a crash.

**Comment by cexewupuv** [comment]
> You're probably looking for a tool [...] to restart your application after a crash.

I'm afraid that restarting the application is not an option.

I tried to use child process to spawn new node process, but I want to access variables and call functions in both processes from each other, so it is very hard, and when one process crashes, it loses all it's variables and data. I also tried to use virtual machine module `require('vm');`, but I'm not sure how to properly use it. Is vm safe of fatal errors? If yes, how can I properly call functions in main process from vm module and vice versa?

Thanks.

**Comment by bnoordhuis** [comment]
> Is vm safe of fatal errors?

It's not.

**Comment by wallet77** [comment]
Hi @bnoordhuis 

I'm working on PM2 and we have an issue about this kind of error.
Here is the situation =>
If we launch app with cluster mode, when this kind of error occurred it's saved into main process log file, basically in /home/user/.pm2/pm2.log.

We can't log it into app's log file because it has crashed, right ?

We agree there is no way to get this kind of error into child process ?
Like we do with uncaughtException : 
`process.on('uncaughtException', ....);`

**Comment by bnoordhuis** [comment]
That's right.  An out-of-memory condition is immediately fatal.

**Comment by wallet77** [comment]
Thanks a lot !
We will document it from our side to explain how it works.

**Comment by gireeshpunathil** [comment]
Closing as answered.
