### ISSUE TITLE
Custom TLS extension handling

### ISSUE THREAD

**Issue by MarcoCaballero** [nodejs/help#1027]
* **Node.js Version**: 9.X.X
* **OS**:  Linux
* **Scope**: code/runtime
* **Module**: tls

Hi all,

I'm now working to get the custom extensions of a TLS handshake, and i'm having problems to manage it.
I dont know if is posible to manage custom TLS handshake extensions with Node `tls module` or else if is posible to preload TLS library with a patch based on the official OpenSSl API using the[`[SSL_extension_supported]`](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_add_server_custom_ext.html#EXTENSION-CALLBACKS) (e.g.)

```
 int SSL_CTX_add_server_custom_ext(SSL_CTX *ctx, unsigned int ext_type,
                                   custom_ext_add_cb add_cb,
                                   custom_ext_free_cb free_cb, void *add_arg,
                                   custom_ext_parse_cb parse_cb,
                                   void *parse_arg);
```

**Comment by bnoordhuis** [comment]
There's no support for that in node.js but you can probably accomplish it through an add-on, a native module.

You may have a difficult time if you want to hook into `tls.connect()` or `tls.createServer()` because there are a lot of layers and moving parts but writing something specific to your use case shouldn't be too hard.

**Comment by MarcoCaballero** [comment]
Okei, thx you.

I hesitate between implementing my own module or simply using Nginx or Apache as a proxy. It might be useful to issue a new functionality request to add a method to manage custom extensions.

**Comment by gireeshpunathil** [comment]
Closing as answered, please re-open if there is anything outstanding here.
