### ISSUE TITLE
Peer certificates

### ISSUE THREAD

**Issue by npepper-techteriors** [nodejs/help#103]
My question is involving TLS/SSL and the clients certificate.  I know of the function 

`tlsSocket.getPeerCertificate() `

which should get the clients certificate if it was sent with the request.  The problem with this function is that:

> If the peer does not provide a certificate, it returns null or an empty object.

..according to the API documentation.  If you have a successful SSL connection, there is ALWAYS a client (peer) certificate used, for instance Chrome has my self signed non-validated certificate that it uses.  When a TLS connection is established, after the server sends its certificate and the client validates it, the client sends back their public certificate as part of the handshake.  Why can I not access that certificate?

My reasoning for this is that I am running a node server which will have many client devices connected to it.  The server will have a good signed SSL certificate, however the clients will not and will be using their self signed default certificates.  I am manually provisioning these devices (clients) with an approval process and would like to store the clients public certificate as a validated certificate if approved.  I am not able to get this certificate and the client does not send a certificate with the exception of the TLS handshake.  Why is the certificate not available?  I'm not really concerned about trusting it.

**Comment by npepper-techteriors** [comment]
@bnoordhuis perhaps what I meant to say is that there is always a key exchange.  What I am really looking for is the public key from the client and use that for validation.  Clients are verified in person by technicians in the field, so the validity of their key or certificate is irrelevant.

**Comment by npepper-techteriors** [comment]
It looks like all paths point towards actually setting up a CA and doing this properly.

**Comment by kelthenoble** [comment]
Hey @npepper-techteriors how is it going for you, did you get it fix?

**Comment by bnoordhuis** [comment]
I think I understand your question better now.

> I am not able to get this certificate and the client does not send a certificate with the exception of the TLS handshake. Why is the certificate not available?

Self-signed client certificates are rejected / ignored unless you start the server with `tls.createServer({ requestCert: true, rejectUnauthorized: false })`.

**Comment by npepper-techteriors** [comment]
Here is what I am using to create the server:

`var credentials = {key: keyfile, cert: keyfile, ca: keyfile,`
`requestCert: true, rejectUnauthorized: false};`
`var server = require('https').createServer(credentials, app);`

I'm using express and passport as middleware.  Perhaps some of the issue here is that I am testing on a development box with a self signed certificate on the server and client.

Being a little more ignorant on the inner details of SSL, I am under the assumption that just like a server has a public and private key used every time the server starts, that a client device (or browser) has a unique public and private key pair used in every connection as well.  For instance if I install a fresh installation of Chromium and connect to any random SSL secured site, I assume that my public / private key combo would be used and is generated for the browser.  I probably have assumed wrong.

Either way, I think that my issue will be solved by properly setting up a CA and actually installing signed certificates on these individual devices.

**Comment by bnoordhuis** [comment]
>  For instance if I install a fresh installation of Chromium and connect to any random SSL secured site, I assume that my public / private key combo would be used and is generated for the browser. I probably have assumed wrong.

That's indeed not what happens.  It's hard to generalize about TLS because it's complex and has many extensions, but in general, insofar that the client has a private and public key, they're ephemeral - they are negotiated during the TLS handshake and only exist for the duration of the session (which can span more than just the current connection but is still limited in lifetime.)  That's not counting explicit client certificates, of course.

If you feel your question has been answered, can you close the issue?  Thanks!

**Comment by npepper-techteriors** [comment]
It has indeed.  Thank you for your assistance in better understanding TLS.
