### ISSUE TITLE
Sudo not working with npm following nodejs install

### ISSUE THREAD

**Issue by Nova-1** [nodejs/help#1030]
* **Node.js Version**: 8.9.3
* **OS**: Ubuntu 16.04.3
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

I have followed your instructions on installing, but when I try to run npm with sudo I get the following error:
sudo: npm: command not found

I am trying to install angular-cli; my npm version is 5.5.1.

**Comment by bnoordhuis** [comment]
Make sure npm is on the path of the root user.  You can force it with `sudo env PATH="$PATH" npm install`.

That said, running npm as root is usually a bad idea and seldom necessary.  You might want to rethink what you're doing.

**Comment by Nova-1** [comment]
when I try running it without sudo (npm install -g @angular/cli) I get the error: EACCESS: permission denied...try running this command again as root.

**Comment by bnoordhuis** [comment]
Most of the time you don't need the `-g` switch, you can just install locally.  Any executable scripts end up in `node_modules/.bin`.

**Comment by Nova-1** [comment]
I found a work-around by first installing _nvm_ then using nvm to install nodejs 
nvm install  &lt;version number&gt;
