### ISSUE TITLE
Help decrypting AES-256-GCM string using createDecipheriv & decipher.final()

### ISSUE THREAD

**Issue by joepagan** [nodejs/help#1034]
* **Node.js Version**: 9.2.0
* **OS**: MacOS
* **Subsystem**: Crypto

I appear to be having a similar problem to https://github.com/nodejs/help/issues/983 where I am having trouble decrypting an encoded string. I don't know if this is because I have not set `.setAAD()`.

My decryption function looks like this:
```
exports.decrypt = (algorithm, privateKey, data, keyAuthTag) => {
  const div = new Buffer(crypto.randomBytes(16), 'utf8')
  const decipher = crypto.createDecipheriv(algorithm, new Buffer(privateKey,'utf8'), div)
  decipher.setAuthTag(keyAuthTag)
  let dec = decipher.update(data,'hex', 'utf8')
  console.log('before decipher.final')
  dec += decipher.final('utf8')
  console.log('after decipher.final')
  return dec;
}
```

My terminal window will return `before decipher.final`, but, never gets as far as the log `after decipher.final`. On The page I am working on in my node app I get the following error:

```
Error: Unsupported state or unable to authenticate data
    at Decipheriv.final (internal/crypto/cipher.js:104:26)
    at Object.exports.decrypt (/Users/joe/var/www/project/handlers/encryption.js:22:19)
    at exports.getData (/Users/joe/var/www/project/controllers/xController.js:42:58)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
 I have tried adding `decipher.setAAD(new Buffer(crypto.randomBytes(16), 'utf8'))`, after setting the authTag, though unfortunately I get the same results.
I'm not sure of exactly what the contents of the buffer required for `.setAAD()` should be.

Any suggestions on how to deal with this would be appreciated.

**Comment by bnoordhuis** [comment]
https://crypto.stackexchange.com/a/15701 - that's what AAD is.  It's an optional authentication mechanism on top of encryption.

If AAD was used in computing the ciphertext, you need that AAD to decrypt the data again, otherwise authentication will fail (which is what happens in your example.)

**Comment by joepagan** [comment]
Thanks for kindly providing an explanation for AAD, though I did not use it during encryption. I thought it was a potential requirement, in the event that the docs may not have been updated.

I have tried setting AAD on the encrypt & decrypt functions, though unfortunately, that didn't change the result, do you have any further suggestions on what I am doing wrong here?

For clarity, here are both encrypt & decrypt functions I am using:
```
const crypto = require('crypto');

exports.encrypt = (algorithm, privateKey, data) => {
  const civ = new Buffer(crypto.randomBytes(16), 'utf8')
  const cipher = crypto.createCipheriv(algorithm, privateKey, civ)
  let crypted = cipher.update(data, 'utf8', 'hex')
  crypted += cipher.final('hex')
  return {
    content: crypted,
    tag: cipher.getAuthTag()
  }
}

exports.decrypt = (algorithm, privateKey, data, keyAuthTag) => {
  const div = new Buffer(crypto.randomBytes(16), 'utf8')
  const decipher = crypto.createDecipheriv(algorithm, new Buffer(privateKey,'utf8'), div)
  decipher.setAuthTag(keyAuthTag)
  let dec = decipher.update(data,'hex', 'utf8')
  dec += decipher.final('utf8')
  return dec;
}
```

**Comment by bnoordhuis** [comment]
You need to use the same IV for encryption and decryption.

I hope I don't come across as condescending but can I suggest you read up on the underlying principles of cryptography first?

Unlike many other disciplines in computer science, cryptography is not an area where you can tweak things until it looks like you're getting the right answers.  Without a good understanding of the fundamentals, chances are better than even that you introduce some fatal weakness.

**Comment by joepagan** [comment]
Thanks for pointing that out. I didn't notice the IVs in the examples I was looking at were actually the same var. That works perfectly now (with setAAD too).

That's ok, admittedly, I am new to crypto world, me using this isn't something that will be "production" ready any time soon. I will take the time to review crypto principles before then.

I very much appreciate you reviewing this for me, I'm sure you get dumb questions all day every day, so thank you for doing another..

**Comment by bnoordhuis** [comment]
Happy to help and glad to hear you solved it.

**Comment by ksuhiyp** [comment]
I am getting this too on cypher.final() even with same IV and no AEAD, but Ive noticed that the text is clearly decrypted before final(), I am using same algo

**Comment by ksuhiyp** [comment]
well I was using < 12 iv  length, also not using `authTag`, eventough i was able to decrypt the text at `update`  but final must be called, for more info according to the documentation 

> Even though calling update() is sufficient to encrypt/decrypt the message, applications must call final() to compute or verify the authentication tag.

**Comment by tcomben** [comment]
> well I was using < 12 iv length, also not using `authTag`, eventough i was able to decrypt the text at `update` but final must be called, for more info according to the documentation
> 
> > Even though calling update() is sufficient to encrypt/decrypt the message, applications must call final() to compute or verify the authentication tag.
> 
> runkit AES GCM 128 playground
> https://runkit.com/ksuhiyp/5be1d3f3d4ed2f0012d4ec85

The "cipherTag" was the missing piece for me.
