### ISSUE TITLE
Issue while tracking context with async_hooks

### ISSUE THREAD

**Issue by domarmstrong** [nodejs/help#1036]
* **9.3.0**:
* **Linux Mint**:
* **code**:
* **async_hooks**:

I'm trying to track context through the async stack using node async_hooks. It works for most cases, however I have found this use case that I can't think how to resolve:

service.js:

```js
const asyncHooks = require('async_hooks');

class Service {
  constructor() {
    this.store = {};
    this.hooks = asyncHooks.createHook({
      init: (asyncId, type, triggerAsyncId) => {
        if (this.store[triggerAsyncId]) {
          this.store[asyncId] = this.store[triggerAsyncId];
        }
      },
      destroy: (asyncId) => {
        delete this.store[asyncId];
      },
    });
    this.enable();
  }

  async run(fn) {
    this.store[asyncHooks.executionAsyncId()] = {};
    await fn();
  }

  set(key, value) {
    this.store[asyncHooks.executionAsyncId()][key] = value;
  }

  get(key) {
    const state = this.store[asyncHooks.executionAsyncId()];
    if (state) {
      return state[key];
    } else {
      return null;
    }
  }

  enable() {
    this.hooks.enable();
  }

  disable() {
    this.hooks.disable();
  }
}

module.exports = Service;
```

service.spec.js

```js
const assert = require('assert');
const Service = require('./service');

describe('Service', () => {
  let service;

  afterEach(() => {
    service.disable();
  });

  it('can handle promises created out of the execution stack', async () => {
    service = new Service();

    const p = Promise.resolve();

    await service.run(async () => {
      service.set('foo', 'foo');

      await p.then(() => {
        assert.strictEqual('foo', service.get('foo'));
      });
    });
  });
});
```

This test case will fail because the triggerAsyncId of the promise created when calling next is the executionAsyncId of the Promise.resolve() call. Which was created outside the current async stack and is a separate context. I can't see any way to marry the next functions async context with the context it was created in.

https://github.com/domarmstrong/async_hook_then_example

**Comment by ORESoftware** [comment]
+1

**Comment by domarmstrong** [comment]
Small update. I noticed in #1021 @sebastian-curland mentioned wrapping code in `Promise.resolve`, this hasn't worked for me. But wrapping a promise created out of scope in `Promise.all([oldPromise])` does work in node 9.3.0. Although this still requires the calling code to do this intentionally.

**Comment by ORESoftware** [comment]
use domains?

**Comment by gireeshpunathil** [comment]
@domarmstrong - is this still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing
