### ISSUE TITLE
Read last N bytes of a big binary file

### ISSUE THREAD

**Issue by vasyl-shumskyi** [nodejs/help#1037]
Hello,

How can I read last 10 bytes of a big binary file using Node.js? 

Thanks!

**Comment by addaleax** [comment]
You can use `fs.stat()` to find out the file size, then use `fs.open()` + `fs.read()` + `fs.close()` manually; `fs.read()` supports a `position` argument that can specify an offset in the file: https://nodejs.org/api/fs.html#fs_fs_read_fd_buffer_offset_length_position_callback

Let us know if that doesn’t help :)

**Comment by vasyl-shumskyi** [comment]
Great. Thanks for quick answer @addaleax I will give it a try.

**Comment by gireeshpunathil** [comment]
> FATAL ERROR: CALL_AND_RETRY_0 Allocation failed - process out of memory

that is not a memory leak, instead out of memory in the vm. You could increase the allocation of memory according to your anticipated demand, using `--max_old_space_size` option (value in mega bytes)

**Comment by gireeshpunathil** [comment]
closing as answered.
