### ISSUE TITLE
Using `process.emit('info')` as opposed to `process.emit('warning')`

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1038]
It appears to be common practice for libraries to use 

    const err = new Error('some warning');
    process.emit('warning', err);

*so that the user-land library can log the error or handle the error, their way.*

However, I am wondering, is there a convention for handling info level messages instead of warning level messages.

Might it be 

    process.emit('message',msg) // no that's reserved for IPC messages

what about

    process.emit('info', msg);

anybody know?

**Comment by ORESoftware** [comment]
```process.emitWarning()``` might be something to look at

**Comment by gireeshpunathil** [comment]
@ORESoftware - just making sure that we are in sync:

```trace
> process.on('x', () => console.log('hello, x!!'))
> process.emit('x')
hello, x!!
>
```

process object being an event emitter, one could define, propage and consume custom events on it.

So: were you hinting at making an `info` event part of the core library, or stating it as a best practice or something like that?

**Comment by ryzokuken** [comment]
@gireeshpunathil looks like this is stale. Let's wait for one more day for them to answer, and if they don't, close it.

**Comment by ORESoftware** [comment]
Yeah I meant part of the core library, but I think probably best to leave it to userland

**Comment by ORESoftware** [comment]
The problem to be solve is how libraries can log certain thigns - it's awkward for the user to pass in a logging function and for the library to try to use that. it's better for the user to log things their way, but they have to get the logging data somehow, that's where process.on/.emit come in handy I guess.

**Comment by gireeshpunathil** [comment]
supplying a logger function (with some standard header etc.) and associating it with a well defined event (such as info) would be very trivial in core. However, as different workloads will want different destinations for the log data (console|disk|wire) a generic logger may be tough to consume.

**Comment by ORESoftware** [comment]
this is related:
https://stackoverflow.com/questions/50302220/cannot-use-process-on-process-emit-with-application-code
