### ISSUE TITLE
Documentation doesn't have an object generating an object... 

### ISSUE THREAD

**Issue by d3x0r** [nodejs/help#104]
this is an object that returns a SqlObject from a volume....

var vol = Volume( );//returns a mmapio region 
var db = vol.SqlObject( "sqlite.db" ); // returns a sqlite object that you can run() things on..

```c++
void SqlObject::New( const FunctionCallbackInfo<Value>& args ) {
	Isolate* isolate = args.GetIsolate();
	if( args.IsConstructCall() ) {
		char *dsn;
		String::Utf8Value arg( args[0] );
		dsn = *arg;
		VolumeObject* vol;
		SqlObject* obj;
		if( args.Length() < 2 ) {
			vol = ObjectWrap::Unwrap<VolumeObject>( args.Holder() );
			obj = new SqlObject( dsn, isolate, args.Holder() );
		}
		else {
			vol = ObjectWrap::Unwrap<VolumeObject>( args[1]->ToObject() );
			obj = new SqlObject( dsn, isolate, args[1]->ToObject() );
		}
		obj->Wrap( args.This() );
		args.GetReturnValue().Set( args.This() );
	} else {
		const int argc = 2;
// have to pass args.Holder() as an argument because doing new constructor after this gives
// the next level that is 'IsConstructCall' a new holder() and new this().... 
		Local<Value> argv[argc] = { args[0], args.Holder() };
		Local<Function> cons = Local<Function>::New( isolate, constructor );
		args.GetReturnValue().Set( cons->NewInstance( argc, argv ) );
	}
}

```

What is args.Holder() and when is it more useful than args.This() ?  Is there some way I could preserve it so I don't have to add it as an arguemnt, which may or may not be there?  Or how can I improve the test for is args[0] a Holder() type ?

-------
posted first as https://github.com/nodejs/node/issues/5482 which got this response and then was closed.

bnoordhuis commented...
> What is args.Holder() and when is it more useful than args.This() ?
> It's... complicated, but in practice, args.Holder() == args.This().

It's good form to use a v8::Signature to restrict the receiver of your object methods to instances of your constructor, that way you don't have to worry about the difference between the two.

> Is there some way I could preserve it so I don't have to add it as an argument, which may or may not > be there?

Don't do that, just have cons->NewInstance() create a new instance and return that. In non-construct calls, the holder and this are the global object.

---------------
while developing a wrapped object that returns a wrapped object args.Holder() is never equal args.This() 

I can't just 'not do that' I need the value in holder as the containing object to reference. and holder is the existing object not global. (othewise unwrap wouldn't give me the volume)

**Comment by lordKnighton** [comment]
cc @nodejs/documentation

**Comment by techjeffharris** [comment]
@d3x0r Please provide a link to the documentation that you suspect is incorrect when you have a moment.  Thanks!

**Comment by d3x0r** [comment]
https://nodejs.org/api/addons.html
