### ISSUE TITLE
Can't install latest NodeJS on Debian Stretch (Debian v9.3)

### ISSUE THREAD

**Issue by chrismp** [nodejs/help#1040]
* **Node.js Version: 9.x (attempting)**:
* **OS: Debian 9.3 Stretch**:
* **Scope: install**:
* **Module: N/A**:

I cannot figure out how to install Node.js v9.x. I ran the following commands in terminal...

```
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
```

But the terminal spit out this message:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (4.8.2~dfsg-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I already have v4.8.2 of the `nodejs` package installed on my computer. 

I also tried running the following...

```
apt purge nodejs
apt install lsb-release
apt install -y nodejs
```

No dice. Still installed `nodejs` v4.8.2.

If I run `update-alternatives --config nodejs`, I get "update-alternatives: error: no alternatives for nodejs" from the terminal.

**Comment by bnoordhuis** [comment]
Run `node`, not `nodejs` - `nodejs` is the name debian gave to the binary for reasons they've probably come to regret over the years.

If you have the `nodejs-legacy` package installed, uninstall it; it conflicts.  No harm in removing it, it's only a symlink of `/usr/bin/nodejs` to `/usr/bin/node`.

**Comment by janfiedler** [comment]
I have same problem, any solution? tip for use "node" doset work. Thanks

**Comment by freed00m** [comment]
I am using stretch and to get latest node I use this npm package called "n"

I first added node 6 to my `/etc/apt/sources.list.d/nodesource.list`
```
deb https://deb.nodesource.com/node_6.x stretch main
deb-src https://deb.nodesource.com/node_6.x stretch main
```
Then I installed nodejs, after having nodejs and npm I did, "#" for root shell.

```
# npm install -g n
# n latests
# npm install -g n
```
This will give me latest node and npm, reinstalling the n package just to feel safer it has been installed by newer npm.

**Comment by jeancarlos** [comment]
I had the same problem. The debian package source priority was higher than the nodesource. I just defined a pin-priority higher and it worked.

### Confirm the problem:

Run: `apt-cache policy nodejs` 

For me it was:
```
9.5.0-1nodesource1 500
   500 https://deb.nodesource.com/node_9.x stretch/main amd64 Packages
4.8.2~dfsg-1 1000
  1000 http://ftp.br.debian.org/debian stretch/main amd64 Packages
```
There is the problem. The nodesource number needs to be higher so the package manager can choose it as a source.

### The solution:

As root: `# nano /etc/apt/preferences.d/nodejs`

Set the priority:
```
Package: * 
Pin: origin deb.nodesource.com
Pin-Priority: 1002
```

Check if it worked:
Run: `apt-cache policy nodejs` 
```
9.5.0-1nodesource1 1002
   1002 https://deb.nodesource.com/node_9.x stretch/main amd64 Packages
4.8.2~dfsg-1 1000
  1000 http://ftp.br.debian.org/debian stretch/main amd64 Packages
```

Finaly!

Now just try the apt install again.

**Comment by Djaymare** [comment]
`apt-cache policy nodejs`

returns

```
4.8.2~dfsg-1 500
  500 http://ftp.br.debian.org/debian stretch/main amd64 Packages
  100 /var/lib/dpkg/status
```

Why does Debian feels we're some puppets ? Isn't Linux enough idiot-proof to let us dev in an unstable environment ? ...

**Comment by AJ-Acevedo** [comment]
@jeancarlos's solution worked perfectly!

**Comment by phicarre** [comment]
Also for me. Thank you @jeancarlos

**Comment by gireeshpunathil** [comment]
closing out as answered, thanks!

**Comment by begoat** [comment]
i still cannot get it work even i tried jeancarlos's answer. But instead i use [nvm (node version manager)](https://github.com/creationix/nvm) and then i can install node 8+

**Comment by HarleyKwyn** [comment]
Late to the party:

A combination of @jeancarlos and @freed00m responses helped me.
Originally I was running into the frustration that no matter what I did `apt-cache policy nodejs` would always output this:
```
nodejs:
  Installed: (none)
  Candidate: 4.8.2~dfsg-1
  Version table:
     4.8.2~dfsg-1 500
        500 http://debian.csail.mit.edu/debian stretch/main amd64 Packages
        500 http://ftp.de.debian.org/debian stable/main amd64 Packages
```

After much frustration this is what worked for me:
1. Update your sourcelist to include the node version you want. In my case I wanted the latest which is currently `https://deb.nodesource.com/node_9.x`
```
sudo vim /etc/apt/source.list
## Add the two following lines to the source list and save the file, for vim press esc and `:wq`
deb https://deb.nodesource.com/node_9.x stretch main
deb-src https://deb.nodesource.com/node_9.x stretch main
```
2. Run `sudo apt-get update` so the source lists refresh. **critical step missing from the above comments**
3. Check for the new apt-cache versions of node
```
apt-cache policy nodejs
> nodejs:
  Installed: (none)
  Candidate: 9.11.1-1nodesource1
  Version table:
     9.11.1-1nodesource1 1002
       1002 https://deb.nodesource.com/node_9.x stretch/main amd64 Packages
     6.14.1-1nodesource1 1002
       1002 https://deb.nodesource.com/node_6.x stretch/main amd64 Packages
     4.8.2~dfsg-1 500
        500 http://debian.csail.mit.edu/debian stretch/main amd64 Packages
        500 http://ftp.de.debian.org/debian stable/main amd64 Packages
```
4. Install node! :tada: 
```
sudo apt install -y nodejs
```
5. verify install
```
nodejs -v
> v9.11.1
npm -v 
> 5.6.0
```

Thank you all for your help!

**Comment by olivier1208** [comment]
Was getting the same issue and anything helps.

As this post is the most relevant, here's what i did

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-debian-8#how-to-install-using-nvm

I used the nvm to install npm and node

Works like a charm now ;)

**Comment by vaioco** [comment]
I got same issue installing node10 with the command

`curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -`

my system configuration is the following

```
@debian:~/$ uname -a
Linux debian 4.9.0-6-686 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) i686 GNU/Linux
@debian:~/$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
@debian:~/
```

instead installing node8 it worked like a charm.

thanks,

**Comment by bil80** [comment]
This is how i was finally able to install nodejs 10 in Debian 9 with these steps:
 1- Create nodesource.list file in /etc/apt/sources.list.d/  with these lines:
   deb https://deb.nodesource.com/node_10.x stretch main
   deb-src https://deb.nodesource.com/node_10.x stretch main
2- apt install curl
3- apt-get update
4- curl -sL https://deb.nodesource.com/setup_10.x | bash - 
5- apt install nodejs
6- apt-get install -y build-essential
7- npm init
8- npm install socket.io --save

And check the installtion with:
node -v
npm -v

**Comment by macagua** [comment]
Also for me. Thank you @jeancarlos

**Comment by germanllop** [comment]
Hello, by now, I'm trying jeancarlos's way that should be the one but, when I use the 10.x and 11.x repos:

> root@server:~# apt-cache policy nodejs
nodejs:
  Installed: (none)
  Candidate: (none)
  Version table:

Empty (I disabled the regular debian repo for testing, when I got those, only debian repo apeared after apt-cache policy nodejs)

Only with 8.x I got a candidate from the repo, anyone knows what's going on with the repos?

**Comment by sevaa** [comment]
One point of interest: looks like node.js 10.x is not available for **32 bit** Debian Stretch.

Changed the the repository lines to  `node_9.x`, and it worked.

**Comment by yDkay** [comment]
> Run `node`, not `nodejs` - `nodejs` is the name debian gave to the binary for reasons they've probably come to regret over the years.
> 
> If you have the `nodejs-legacy` package installed, uninstall it; it conflicts. No harm in removing it, it's only a symlink of `/usr/bin/nodejs` to `/usr/bin/node`.

THANK YOU SO FUCKING MUCH

**Comment by hsiboy** [comment]
> One point of interest: looks like node.js 10.x is not available for **32 bit** Debian Stretch.
> 
> Changed the the repository lines to `node_9.x`, and it worked.

OMG, three shaved yaks later!

Thank you so much!

**Comment by capsule5** [comment]
this is the solution : https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04

**Comment by threehappypenguins** [comment]
When I type in `sudo apt-cache policy nodejs`, I get this:

```
nodejs:
  Installed: (none)
  Candidate: 4.8.2~dfsg-1
  Version table:
     8.11.1~dfsg-2~bpo9+1 100
        100 http://httpredir.debian.org/debian stretch-backports/main armhf Packages
     4.8.2~dfsg-1 500
        500 http://httpredir.debian.org/debian stretch/main armhf Packages
```

But when I type in `sudo nano /etc/apt/preferences.d/nodejs`, it's blank. So I copy and paste into the file:

```
Package: * 
Pin: origin deb.nodesource.com
Pin-Priority: 502
```
Then I save it, and then I `sudo apt-cache policy nodejs` again and it shows the exact same thing as before. I tried changing the 502 in the file to 1002 like jeancarlos had, but it didn't work either. I don't really understand what I'm doing. Can someone please help? I want to install Sharepoint framework, but I apparently need npm, and I can't install npm with old 4.x nodejs.

**Comment by ideaztech** [comment]
I was getting this error:
dpkg: error processing archive /var/cache/apt/archives/nodejs_18.7.0-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3

I tried everything, but finally found this solved the problem:

` sudo dpkg -i --force-overwrite /var/cache/apt/archives/nodejs_18.7.0-deb-1nodesource1_amd64.deb `

After this, then 

 `sudo apt-get install -y nodejs`

**Comment by kanasimi** [comment]
@ideaztech You may need do this:
```
sudo apt remove libnode-dev
```

**Comment by hsiboy** [comment]
@kanasimi this issue is 5 years old and closed.

**Comment by franco-matt3r** [comment]
> franco
This was my problem on ubuntu 22.04 and doing this with reinstalling solved it, from start to end:

sudo apt remove libnode-dev

cd /etc/apt/sources.list.d 
sudo rm nodesource.list

sudo apt --fix-broken install
sudo apt update
sudo apt remove nodejs
sudo apt remove nodejs-doc

curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
