### ISSUE TITLE
Running tasks in the background...

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1041]
Hi all,

I am currently using NodeJS with Express for a project I'm working on. I want it to perform search queries over the web, according to user input. My (pseudo)code looks like this:
```javascript

function (userURL){
// crawl.queue('test.com');
if (find something) {
log it by email
}
}

```
**What I want it to do** : 
- re-crawl a page every minute ( I have that working with setInterval) : this happens through as soon as my html form gets posted and it works. 
- keep the above task running, even after a next form gets submitted

**What its doing** : 
the first assignment/crawl task stops as soon as a second form gets submitted

Any ideas?

**Comment by bnoordhuis** [comment]
Not enough information to say what the issue is.  You should post code - but try to reduce it to just the essentials.

**Comment by WAINGOR** [comment]
thanks Ben I sorted it out :)
