### ISSUE TITLE
Performance implications if next is not called in the middleware?

### ISSUE THREAD

**Issue by ShrawanLakhe** [nodejs/help#1042]
In the middleware function, to move on to the succeeding middleware function, we need to invoke the next function. As we all know, if we omit the call the next() function, the request will be hanging. In these scenarios, are there  any performance implications due to this? If yes, then what are those issues? What might be the issues if we do not explicitly call next function and requests are left hanging?

Thank you.

**Comment by ORESoftware** [comment]
If you don't call `next()`

1. The response probably won't get sent to the client
2. There may be some memory leaks because 

Because of 2, the memory of your serve might keep growing until the process crashes, or the server is restarted. High memory requirements will tend degrade performance because the CPU spend more time in garbage collection.

**Comment by ORESoftware** [comment]
one thing you can experiment with, is domains, which can trap errors thrown asynchronously

```js
const Domain = require('domain');

app.use(function (req, res, next) {

  let d = Domain.create(); // create a new domain for this request

  res.once('finish', function () {
    d.exit();
    d.removeAllListeners();
  });

  d.once('error', function (e) {
    if (!res.headersSent) {
      res.status(500).json({
        error: util.inspect(e ? e.stack || e : e)
      });
    }
  });

  // we invoke the next middleware
  d.run(next);

});

```

**Comment by ShrawanLakhe** [comment]
Thank you very much. Is there any way that we could prevent track the issue and prevent it?

**Comment by ORESoftware** [comment]
to know when next is not called?

you could create a setTimeout, and if the response is not sent within 30 seconds you can send an error, like this:

```js
app.use(function(req,res,next){
   
   setTimeout(function(){
      if(!res.headersSent){
         res.json({
            error: 'request timed out'
           });
      }
   }, 30000)

   next();
});
```

obviously, adjust the timeout as needed, 30 seconds should be more than enough though for most kinds of servers

**Comment by ShrawanLakhe** [comment]
ok Thank you very much.

**Comment by ORESoftware** [comment]
np, I believe the 'finish' event is correct, but it could be 'end' instead, double check for me

**Comment by ShrawanLakhe** [comment]
yeah sure i will.

**Comment by ShrawanLakhe** [comment]
**finish** and **end** both works. Thank you very much.

**Comment by ORESoftware** [comment]
np yw

**Comment by gireeshpunathil** [comment]
closing as answered.
