### ISSUE TITLE
How to freeze node.js title on windows?

### ISSUE THREAD

**Issue by 6-8-axnw1bom81v5xa3nh48c** [nodejs/help#1048]
* **Node.js Version**: the latest
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**: meta
* **Module (and version) (if relevant)**: child_process

Here is my code

```JavaScript
require('child_process')
  .spawn('cmd')
  .stdin.write('md 1 && xcopy 1 2\n');
```

It causes my command prompt window to change title to `xcopy 1 2`. I want to keep the previous title of the window. How to achieve it?

Many thanks in advance.

**Comment by gibfahn** [comment]
cc/ @nodejs/platform-windows

**Comment by seishun** [comment]
I'm quite sure this has nothing to do with Node.js. If you manually type `md 1 && xcopy 1 2` in a command prompt, it will change the window title to "xcopy 1 2".

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
Correct, but I didn't say it's a bug. I was just wondering is there a feature, which Node.js provides, that allows users to freeze command prompt title.

**Comment by tniessen** [comment]
Not that I know of. Is there a way to do that on other platforms?

**Comment by gibfahn** [comment]
>Not that I know of. Is there a way to do that on other platforms?

In Unix terminal programs you can usually set the title manually.

**Comment by RReverser** [comment]
You can set title manually here too, but I think actual command will override it in cmd. If it's an option for you, you might spawn powershell instead which will give better control over console.

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
Thank you for this idea. Unfortunately, PowerShell changes the title to `"Windows PowerShell"` itself. However, you're right: powershell somehow manages to keep the original title (even if another operable program or built-in command is called). Therefore, I suppose it should be possible for other programs to keep the original title, right? I mean, Node.js should probably be able to do the same thing that powershell did. Powershell sets the title once at the beginning and then freezes it, so wouldn't it mean Node.js's child_process should be able to achieve the same thing?

**Comment by gibfahn** [comment]
I think what @RReverser is saying is that you can do something like [this](https://blogs.technet.microsoft.com/heyscriptingguy/2012/12/30/powertip-change-the-powershell-console-title/) to change the title.

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
Thanks, but... I can't say I understood what you mean. `$host.ui.RawUI.WindowTitle` is a PowerShell variable, what it has to do with Node.js? I'm not talking only about cmd or powershell, I'm talking about arbitrary programs.

Basically, I would like to spawn a process (which may or may not try to change the title), but the title should not be changed. Suppose I have a program `1.exe` which changes the title to `"abc"` and then spins in a loop forever (I don't know anything else about such program). When I execute it using child_process, my title is changed to `"abc"`, but I would like the title to be unchanged. I'm wondering is it possible to achieve it. According to the fact that any program which has been started from PowerShell is unable to change the title, I suppose it is possible to freeze the title such that no child processes can change it. I don't want to use PowerShell for that, I would like to do the same internall stuff PowerShell does, but in Node.js (I suppose it is somehow possible).

To make it clear, PowerShell somehow succeeds to freeze the command prompt window title and, no matter which programs are executed from it, they will not be able to change the title. Therefore, I suppose it is possible to somehow freeze the title without using PowerShell, using only native Node.js methods (and maybe `process.env` entries, idk).

Thank you anyways.

**Comment by gireeshpunathil** [comment]
Assuming that [the win32 API SetWindowText](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633546(v=vs.85).aspx) is responsible for changing the title, your requirement does not seem possible:

 - If a process uses this API to over-ride an existing title, the same rule applies to a child process, so it can over-ride the title too.

 - For argument's sake, if there exist a hypothetical API that `sets and freezes` the title, and if node's parent process invoeks such a hypothetical API, then node will not be able to change it, as the title is frozen.

I don't think powershell `freezes` it, it might be such that no child process that powershell spawns bother to change the title, whereas MS-DOS attempts to `reflect` what child is running on it by modifying the title as and when it spawns children.

All these speculations are easily verified if we have an `strace` like feature in Windows (I don't know) which will tell who calls the title changing function and with what.

**Comment by tniessen** [comment]
@gireeshpunathil Windows applications usually use [`SetConsoleTitle`](https://docs.microsoft.com/en-us/windows/console/setconsoletitle) to set their own title (I assume that's what node does as well).

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
@gireeshpunathil Thank you for explanations. It seems that you are right. I'm closing this question.
