### ISSUE TITLE
Windows Error: Implement me. Unknown stdin file type!

### ISSUE THREAD

**Issue by rafaelcastrocouto** [nodejs/help#105]
Hey guys, we are having an error at devtool related to stdin that only happens in windows Jam3/devtool#42 and I have no clue how to solve it. Seems like electron "renderer" process.stdin is throwing the Exception: Error: Implement me. Unknown stdin file type! error. Can anyone help? Thx a lot!

**Comment by lordKnighton** [comment]
@rafaelcastrocouto Are you still having issues with this?

**Comment by rafaelcastrocouto** [comment]
Yes ... and it`s easy to reproduce ... just install devtool `npm i devtool -g`

then run `devtool` and inside the console type `process.stdin` ...

you will get an error message `Uncaught Error: Implement me. Unknown stdin file type!`

**Comment by j-mueller** [comment]
So, has this been resolved?

**Comment by addaleax** [comment]
@j-mueller I don’t think so… Can you tell which file type stdin has?

**Comment by j-mueller** [comment]
`stdin` is undefined, and the result of `tty_wrap.guessHandleType(fd)` is `"UNKNOWN"`

**Comment by j-mueller** [comment]
PS. I got this error following the Electron Quick Start tutorial (http://electron.atom.io/docs/tutorial/quick-start/)

Do you think I should file an issue with electron, or is this the right place?

**Comment by addaleax** [comment]
> `stdin` is undefined

If you’re talking about the `stdin` variable, yes, that’s normal before the first call to `tty_wrap.guessHandleType`. What I meant was more, like, in what way is the process spawned so that it does not have a valid stdin?

> Do you think I should file an issue with electron, or is this the right place?

Maybe, yes.

**Comment by j-mueller** [comment]
> in what way is the process spawned so that it does not have a valid stdin?

It was spawned by electron, so I will see if I can find anything over there. Thanks.
