### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by slim-hmidi** [nodejs/help#1051]
* **Node.js Version**: v8.4.0
* **OS**: ubuntu 17.04

I run this test in jest: 
```
test('run tests in parallel', () => {
  return Promise.all(_.range(3000).map((i) => {
    return Model.query().insert({ name: `user${i}` });
  }));
}, 60000);
```
I got this error:
```
(node:14910) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by bnoordhuis** [comment]
`node --trace-warning app.js` makes it print a stack trace, that should tell you where the issue comes from.  It might be benign, it might not be.

If it's benign, you can suppress it with `ee.setMaxListeners(n)`.

**Comment by NickNaso** [comment]
@slim-hmidi Node.js as default allow you to set 10 listeners for any single event as reported here:
https://nodejs.org/dist/latest-v8.x/docs/api/events.html#events_eventemitter_defaultmaxlisteners
If you want change this behavior you as @bnoordhuis wrote in the previous thread you need to use the method ```setMaxListeners``` as reported here:
https://nodejs.org/dist/latest-v8.x/docs/api/events.html#events_emitter_setmaxlisteners_n 
Remember if you increase indiscriminately the number of maximum listener for any single event you could experiment some performance issue.

**Comment by jennyvallon** [comment]
@bnoordhuis it's `--trace-warnings app.js`

**Comment by nimatullah** [comment]
@jennyvallon, awesome thank you.

**Comment by rogeriojlle** [comment]
Is it possible to identify in "Model" when the query ends and remove the listener?
Maybe this helps, causing setMaxListeners (#) to have a smaller number or even need to set it?

Like that?

```
const {createServer} = require ('http');
const ffmpeg = ... \\ a EventEmitter
const server = createServer ((req, res) => {

    let bufEvt = (d) => {
      res.write (d);
    }
    ...
    ...

    case '/filme.mp4':

       res.writeHead (200, {
         'Content-Type': 'video / mp4',
         'Transfer-Encoding': 'chunked'
       });

       ffmpeg.on ('buf', bufEvt);

       req.on ('close', (c) => {
         ffmpeg.removeListener ('buf', bufEvt);
       });

       req.on ('abort', (c) => {
         ffmpeg.removeListener ('buf', bufEvt);
       });

     break;
    ...
    ...
  )};
```

**Comment by alfasin** [comment]
I tried a few different solutions that **didn't** work for me:

* increasing --max-old-space-size
* using the node flag: node --no-compilation-cache
* use  --runInBand
* use --expose-gc
* limiting the number of workers

What **did** work for me:

[Limiting the idle memory per worker](https://jestjs.io/docs/configuration#workeridlememorylimit-numberstring) (setting: workerIdleMemoryLimit).

I'm also limiting the number of workers so maybe it was a combination of the solutions.
