### ISSUE TITLE
nodejs endless execSync Problem

### ISSUE THREAD

**Issue by DerKatzeLP** [nodejs/help#1052]
* **Node.js Version**: 8.9.3
* **OS**: Rasbian Lite
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: 

If i start a child_process with execSync, it never ends like there is no Exit-Event.

Can't find any help in sth like google XD

```js
var tmpStr = "ls -la";
var code = require('child_process').execSync( tmpStr, {stdio:[0,1,2]} ).toString();
  console.log( code );
```

I also used this

```js
var tmpStr = "ls -la";
try
{
	var code = require('child_process').execSync( tmpStr, {stdio:[0,1,2]} ).toString();
	console.log( code );
} catch (e) {
	console.log( "catchy thing" );
	console.log( e );
	return e;
} finally {
	return "Finish";
}
```

Hope there is someone here to help me =)

Thanks

**Comment by vsemozhetbyt** [comment]
It seems with `stdio: 'inherit'` (= `stdio:[0,1,2]`) `execSync` returns `null` instead of stdout Buffer.
```console
> require('child_process').execSync('echo 0', { stdio: 'inherit' })
0
null
```
Is this a bug or is this documented somewhere?

cc @bnoordhuis, @cjihrig

**Comment by addaleax** [comment]
@vsemozhetbyt That doesn’t seem like a bug… By specifying `stdio: 'inherit'`, you basically say that you do not care about the output and want it to fall through to the parent processes own stdio – right?

**Comment by vsemozhetbyt** [comment]
Maybe we need to document this? [Currently](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options) the returned value is only Buffer. Or is it considered self-evident?

**Comment by DerKatzeLP** [comment]
Hello,

thanks for reading my Problem.

I don't know what to do, because even if i do it like this

```js
var tmpStr = "ls -la";
try
{
	var code = require('child_process').execSync( tmpStr ).toString();
	console.log( code );
} catch (e) {
	console.log( "catchy thing" );
	console.log( e );
	return e;
} finally {
	return "Finish";
}
```

the Process never ends.

I want to do this in a function with a return but the whole programm always gets stuck when i try to start the function.

Is there another way to run shell-commands and wait for its response to work with it later on??


Thank you for your help =)

**Comment by bradisbell** [comment]
@DerKatzeLP What was your solution?

**Comment by DerKatzeLP** [comment]
Hello @bradisbell,
I am sorry but i never found a proper solution. Now i am working with callbacks and just .exec instead of .execSync.
I works for me i my specific case but its not an ideal way.
If you find a solution, please let me know as well.

Thanks and good luck

**Comment by bradisbell** [comment]
Well, it turns out I had a bug in my code after all.  :-)  I used Process Explorer on Windows to track down all the child processes and found that I was passing an extra option to one of my scripts that was waiting on files to change before proceeding.

For anyone else that needs to debug, I also recommend ensuring that you output all of your streams so you can see them.  By default, you'll only see STDERR.  Try something like this:

```
  childProcess.execSync('some-binary', {
    stdio: ['inherit', 'inherit', 'inherit']
  });
```
