### ISSUE TITLE
Cannot find module 'crypto'

### ISSUE THREAD

**Issue by sulthonzh** [nodejs/help#1053]
hello, i got error when require 'crypto'

==========================================================

code:
`const crypto = require('crypto');`

error result:
`Cannot find module 'crypto'`

==========================================================
is not crypto module supposed to by default already included?
but why this error got it?

thanks,

sorry, for this issue i write here.

this is my env:

```
{ 
test: '1.0.0',
npm: '5.6.0',
ares: '1.10.1-DEV',
cldr: '31.0.1',
http_parser: '2.7.0',
icu: '59.1',
modules: '57',
nghttp2: '1.25.0',
node: '8.9.4',
openssl: '1.0.2n',
tz: '2017b',
unicode: '9.0',
uv: '1.15.0',
v8: '6.1.534.50',
zlib: '1.2.11' 
}
```

**Comment by vsemozhetbyt** [comment]
How do you get the node binary and what OS do you use?

**Comment by sulthonzh** [comment]
Hi @vsemozhetbyt,  used Linux Ubuntu 16.04, and donwload binary with `nvm install --lts`

**Comment by sulthonzh** [comment]
Hi @vsemozhetbyt,  used Linux Ubuntu 16.04, and download binary with `nvm install --lts`

**Comment by vsemozhetbyt** [comment]
As far as I know, if you have openssl (`process.versions.openssl` is defined), you also have `crypto` module, so it is strange to me. But I may be wrong, so let us wait till other answers.

cc @nodejs/crypto

**Comment by sulthonzh** [comment]
@vsemozhetbyt who @nodejs/crypto, the page not found, I've asked the nodejs/node, but it was rejected.

**Comment by vsemozhetbyt** [comment]
@sulthonzh I've just mentioned the @nodejs/crypto group so that its members can chime in)

**Comment by mmarchini** [comment]
Couldn't reproduce it on Ubuntu 16.04 or 17.10 with Node 8.9.4 from nvm. @sulthonzh can you try to reinstall Node 8.9.4 to see if something went wrong during installation or if it's an environment problem? (remember to clear nvm cache before reinstalling it with `nvm clear cache`)

**Comment by tniessen** [comment]
Yes, the crypto module should be available. What happens if you start the REPL by running `node` and then type `crypto`? It should print something like this:

```
F:\node>node
> crypto
{ DEFAULT_ENCODING: 'buffer',
  constants:
   { SSL_OP_ALL: 2147486719,
     SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION: 262144,
     SSL_OP_CIPHER_SERVER_PREFERENCE: 4194304,
     SSL_OP_CISCO_ANYCONNECT: 32768,
     SSL_OP_COOKIE_EXCHANGE: 8192,
     SSL_OP_CRYPTOPRO_TLSEXT_BUG: 2147483648,
     SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS: 2048,
     SSL_OP_EPHEMERAL_RSA: 0,
     SSL_OP_LEGACY_SERVER_CONNECT: 4,
     SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER: 32,
     SSL_OP_MICROSOFT_SESS_ID_BUG: 1,
     SSL_OP_MSIE_SSLV2_RSA_PADDING: 0,
     SSL_OP_NETSCAPE_CA_DN_BUG: 536870912,
     SSL_OP_NETSCAPE_CHALLENGE_BUG: 2,
     SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG: 1073741824,
     SSL_OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG: 8,
     SSL_OP_NO_COMPRESSION: 131072,
     SSL_OP_NO_QUERY_MTU: 4096,
     SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION: 65536,
```

**Comment by sulthonzh** [comment]
![image](https://user-images.githubusercontent.com/4921059/34529991-541ebda6-f0e0-11e7-9d9f-bcc0d7b9f545.png)
this is my result `node > crypto` is working on node console, 
but when `require` got error,

i have reinstall this but same,

**Comment by mmarchini** [comment]
As far as I understood, you're having problems when running a Casper test, right? Casper [**does not** run on node](http://docs.casperjs.org/en/latest/faq.html#is-casperjs-a-node-js-library), so this is not a Node issue. There's a related issue on Casper repository: https://github.com/casperjs/casperjs/issues/738, maybe it can help you :)

**Comment by sulthonzh** [comment]
@mmarchini  oh not careful, I have not read it, ok thanks for u reference,

**Comment by adonahoe** [comment]
@thatham This gist resolved my issue, It's a hacky solution but might be worth a look:
https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d
