### ISSUE TITLE
How to implement a back pressure absorbing stream for "live" data?

### ISSUE THREAD

**Issue by Torsten85** [nodejs/help#1054]
Hi there,
currently I'm trying to wrap my head around streams and now im stuck with back pressure. 
Assume the following situation:

I've a stream that pumps out images at a rate of 1 image / 100ms. (`imageStream`)
I've a resize stream that is capable of resizing an image at a rate of 1 image per 1 seconds. (`resizeStream`).

So this would generate back pressure and ultimately will stop the `imageStream` right?
```js
imageStream.pipe(resizeStream)
```

Now I always need the most recent image resized. Because the `resizeStream` is ten times slower as the `imageStream`, I need a stream in between that will "absorb" the back pressure and throws away every image that cannot currently be processed. It doesn't matter that I'll loose data, I only want the newest image and I don't want any buffer filling up with old data. Basically I need something like this:

```js
imageStream.pipe(backPressureAbsorber).pipe(resizeStream)
```

I've started with a test implementation that is not working at all:
`ImageStream`:
```js
class ImageStream extends PassThrough {
  constructor() {
    super();
    setInterval(() => this.write(Buffer.from(Date.now().toString())), 100);
  }
}
```

`ResizeStream`:
```js
class ResizeStream extends Transform {
  _transform(chunk, encoding, callback) {
    setTimeout(() => {
      this.push(chunk);
      callback();
    }, 1000);
  }
}
```

The following shows that the image gets older over time:
```js
imageStream.pipe(resizeStream);
resizeStream.on('data', data => {
  console.log('got data of age', Date.now() - Number(data));
});
```

`BackPressureAbsorber`:
```js
class BackPressureAbsorber extends Duplex {
  constructor() {
    super();
    this.acceptChunk = false;
  }

  _write(chunk, encoding, callback) {
    // here I will ignore every chunk that is not "accepted"
    if (this.acceptChunk) {
      this.acceptChunk = false;
      this.push(chunk);
    }
    callback();
  }

  _read() {
   // here I thought the resizeStream would only call this every second, but it happens continously
    this.acceptChunk = true;
  }
}
```

I guess that I not understood some aspects of streams. Maybe someone could solve this for me or point me in the right direction.

Thanks in advance

**Comment by gireeshpunathil** [comment]
not necessarily the optimal solution, but please see if this one works for you. 
```js
const stream = require('stream')
class D extends stream.Duplex {
  constructor() {
    super()
  }
  _write(chunk, encoding, callback) {
    console.log('source: ' + chunk.toString())
    if(!this.isPaused())
      this.push(chunk)
    callback()
  }
  _read() {}
}

var d = new D()
d.on('data', (chunk) => {
  d.pause()
  setTimeout(() => {
    console.log('dest: ' + chunk.toString())
    d.resume()
  }, 1000)
})
var i = 0
setInterval(() => {
  d.write((i++).toString())
}, 100)
```

**Comment by gireeshpunathil** [comment]
@Torsten85 - does this help you? can I close this?

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding.
