### ISSUE TITLE
Invoking a calling of the same async function one by one crashes the nodejs

### ISSUE THREAD

**Issue by Globik** [nodejs/help#1055]
* **Node.js Version**:9.0
* **OS**:Linux, Lubuntu 32bit
* **Scope (install, code, runtime, meta, other?)**: code and runtime
* **Module (and version) (if relevant)**:napi addon

Without intervals when you calling the same function one by one in a loop the system craches right after the first call. Why so? What if I delete this methods:
NAPI_CALL_RETURN_VOID(env, napi_call_function(env,global,callback,2,argv,&result));
NAPI_CALL_RETURN_VOID(env, napi_delete_reference(env,c->_callback));
Brings to the memory leaks?
You can reproduce this issue like this 
https://github.com/Globik/libqrencode-js/blob/master/simple_test/test_async.c
And the javascript part of issue
https://github.com/Globik/libqrencode-js/blob/master/simple_test/b.js
Is this my problem of coding or is this just a bug?

```js
// I am an example of JS code
// please remove me too
const addon=require('./build/Release/test_async');

//STEP 1 is OK

addon.Test(5,{type:'start'},function(err,val){
	console.log('err: ',err);
	console.log('val: ',val);
});

// STEP 2  and further CRASHES
// RACE CONDITION OR WHAT? 
//Console error report:
//undefined:0
//Error: Invalid argument


addon.Test(5,{type:'start'},function(err, val){
console.log(err);
console.log(val);
})


addon.Test(5,{type:'start'},function(err, val){
console.log(err);
console.log(val);
})

addon.Test(5,{type:'start'},function(err, val){
console.log(err);
console.log(val);
})
And here the napi addon part:

#include <node_api.h>
#include "common.h"
#if defined _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif
#define nullptr ((void*)0)
typedef struct{
int32_t _input;
int32_t _output;
napi_ref _callback;
napi_async_work _request;
}carrier;
carrier the_carrier;

void Execute(napi_env env,void*data){
carrier* c=(carrier*)data;
	if(c !=&the_carrier){napi_throw_type_error(env,nullptr,"wrong data to execute.\n");return;}
	#if defined _WIN32
	Sleep(1000);
	#else
	sleep(1);
	#endif
	c->_output=c->_input*2;
}
void Complete(napi_env env,napi_status status, void* data){
    carrier* c=(carrier*)data;
	
	if(c !=&the_carrier){
	napi_throw_type_error(env,nullptr,"wrong data parameter to Complete");
		return;
	}
	
	if(status !=napi_ok){
	napi_throw_type_error(env,nullptr,"execute callback failed.");
		return;
	}
    //napi_handle_scope scope;
	napi_value argv[2];
	//napi_open_handle_scope(env,&scope);
	NAPI_CALL_RETURN_VOID(env,napi_get_null(env,&argv[0]));
	

	NAPI_CALL_RETURN_VOID(env, napi_create_int32(env,c->_output,&argv[1]));
	
	napi_value callback;
	NAPI_CALL_RETURN_VOID(env, napi_get_reference_value(env,c->_callback,&callback));
	napi_value global;
	NAPI_CALL_RETURN_VOID(env, napi_get_global(env,&global));
	napi_value result;
	NAPI_CALL_RETURN_VOID(env, napi_call_function(env,global,callback,2,argv,&result));
// AND HERE IS THE PROBLEM, WORKFLOW IN NO TIME CANNOT WAIT WHEN A NEW REFERENCE
// AND NEW ASYNC WORK WILL BE CREATED. BOOM AND CRASH!
	NAPI_CALL_RETURN_VOID(env, napi_delete_reference(env,c->_callback));
	NAPI_CALL_RETURN_VOID(env, napi_delete_async_work(env,c->_request));
	//napi_close_handle_scope(env,scope);
}

napi_value Test(napi_env env,napi_callback_info info){
	//napi_handle_scope scope;
size_t argc=3;
	
	napi_value argv[3];
	napi_value _this;
	napi_value resource_name;
	void* data;
	//napi_open_handle_scope(env,&scope);
	
	NAPI_CALL(env,napi_get_cb_info(env,info,&argc,argv,&_this,&data));
	
	NAPI_ASSERT(env,argc >=3,"not enough arguments, expected 3?.");
	
	
	the_carrier._output=0;
	NAPI_CALL(env,napi_get_value_int32(env,argv[0],&the_carrier._input));
	
	
	NAPI_CALL(env, napi_create_reference(env,argv[2],1,&the_carrier._callback));
	
	NAPI_CALL(env, napi_create_string_utf8(env,"TestResource",NAPI_AUTO_LENGTH,&resource_name));
	
	NAPI_CALL(env, napi_create_async_work(env,argv[1],resource_name,Execute,Complete,&the_carrier,&the_carrier._request));
	
	NAPI_CALL(env, napi_queue_async_work(env,the_carrier._request));
	
	//napi_close_handle_scope(env,scope);
	return nullptr;
	}


napi_value Init(napi_env env,napi_value exports){

napi_property_descriptor properties[]={
	DECLARE_NAPI_PROPERTY("Test",Test),
};
NAPI_CALL(env, napi_define_properties(env,exports,sizeof(properties)/sizeof(*properties),properties));
return exports;
}
NAPI_MODULE(addon,Init);



```

And if I call the same function addon.Test throughout setInterval=1000 - one second, then no crashes, system works like a swiss timers. What the bogus with it? Or I 'm missing something?

**Comment by Trott** [comment]
@nodejs/n-api

**Comment by Globik** [comment]
Tried to handelscoping the stuff, but the same, crashes. This is not my code. This is what they have on their official repo in test directory. And? 
OK, please God, provide an test code also where people can see how to call async function from nodejs part one by one in a big loop without afraid of system crashing.
Or should I every nodejs addon napi async function to wrap to setInterval?)

**Comment by Globik** [comment]
From uv.h:
Warning libuv will coalesce calls to uv_async_send(), that is, not every call to it will yield an execution of the callback. For example: if uv_async_send() is called 5 times in a row before the callback is called, the callback will only be called once. If uv_async_send() is called again after the callback was called, it will be called again.
This is it.

**Comment by mhdawson** [comment]
Looking at the doc for napi_call_function https://nodejs.org/api/n-api.html#n_api_napi_call_function, it indicates that:

```
For the special case of calling into JavaScript after an async operation, see napi_make_callback.
```

I'd have to look more carefully at your code but at first glance I'm thinking you should be using napi_make_callback instead of napi_call_function.  Can you give that a try ?

**Comment by mhdawson** [comment]
Doc for napi_make_callback: https://nodejs.org/api/n-api.html#n_api_napi_make_callback

**Comment by mhdawson** [comment]
I guess never mind, I'm just reading that doc and it says it is not necessary to use napi_make_callback in napi_async_complete_callback

**Comment by mhdawson** [comment]
Since this is static and is used for every call 
```
carrier the_carrier;
```

I'm current guess is that because I don't see anything to ensure that the first call to addon.Test() and the associated Complete callback is complete before the second call to addon.Test(), is that the based on timing you could have the_carrier being overwritten/deleted (ie second call overwrites the contents of the_carrier, then first Complete deletes it etc.) It would also explain why adding delays seems to help.

**Comment by Globik** [comment]
@mhdawson  I have today tried again. First of all I have renamed a file extension from c to cc. Removed the define for a nullptr : ) 
What I have noticed that if I write like this:
setInterval(function(){
setImmediate(function(){
addon.Test(5,{type:'start'}, function(err, val){
console.log(err, val)
})
})

},15)
so workflow runs like a charm. Interval < =15 crashes the process on my machiene.
They say that asynchronous workflow is some tricky in nodejs addons, so I must to use high level abstruction libraries as node-addon-api or nan on c++. Yes, they right. Just tested both with AsyncWorker classes runs all just fine. It's a little pitty for me, becouse I was so excited about nodejs new abi compatible api for addons developing.

**Comment by Globik** [comment]
Yes the_carrier is hardcoded and static but the same runs well when using the nan, node-addn-api and pure combination of v8, node and uv.

**Comment by kfarnung** [comment]
@Globik Taking a look at the code I'm inclined to agree with @mhdawson that you appear to be reusing the same `carrier` object for each of your async work items.  This is problematic as the `_request` field is overwritten each time your start your async work and then deleted when a previous work item completes.

Your `Test` function should be creating a new instance of `carrier` for each call and then using only the object passed in as `data`.  Without seeing specific examples of the other implementations I can't really comment on why those appear to be working.

**Comment by Globik** [comment]
Thank you @mhdawson , @kfarnung for your reply. I fugured out with your help. I removed the static struct. In function Test declared instance for the struct, malloced it. And in the function Complete() free that struct. It works now like a charm. And the code is now like this:
```
#include <node_api.h>
#include "common.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#if defined _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

typedef struct carrier{
int32_t _input;
int32_t _output;
napi_ref _callback;
napi_async_work _request;
}carrier;


void Execute(napi_env env,void*data){
carrier* c=(carrier*)data;
	//if(c !=&the_carrier){napi_throw_type_error(env,nullptr,"wrong data to execute.\n");return;}
	#if defined _WIN32
	//Sleep(1000);
	#else
	//sleep(1);
	#endif
	c->_output=c->_input*2;
}

void Complete(napi_env env,napi_status status, void* data){
    carrier* c=(carrier*)data;
	/*
	if(c !=&the_carrier){
	napi_throw_type_error(env,nullptr,"wrong data parameter to Complete");
		return;
	}*/
	
	if(status !=napi_ok){
	napi_throw_type_error(env,nullptr,"execute callback failed.");
		return;
	}
    //napi_handle_scope scope;
	napi_value argv[2];
	//napi_open_handle_scope(env,&scope);
	printf("satus: %s\n",(char*)status);
	NAPI_CALL_RETURN_VOID(env,napi_get_null(env,&argv[0]));
	

	NAPI_CALL_RETURN_VOID(env, napi_create_int32(env,c->_output,&argv[1]));
	
	napi_value callback;
	NAPI_CALL_RETURN_VOID(env, napi_get_reference_value(env,c->_callback,&callback));
	napi_value global;
	NAPI_CALL_RETURN_VOID(env, napi_get_global(env,&global));
	//NAPI_CALL_RETURN_VOID(env, napi_delete_reference(env,c->_callback));
	napi_value result;
	NAPI_CALL_RETURN_VOID(env, napi_call_function(env,global,callback,2,argv,&result));
	//napi_close_handle_scope(env,scope);
	NAPI_CALL_RETURN_VOID(env, napi_delete_reference(env,c->_callback));
	NAPI_CALL_RETURN_VOID(env, napi_delete_async_work(env,c->_request));
	//napi_close_handle_scope(env,scope);
	//return;
	free(c);// ???
}

napi_value Test(napi_env env,napi_callback_info info){
	//napi_handle_scope scope;
	carrier* c=(carrier*)malloc(sizeof(carrier));
size_t argc=3;
	
	napi_value argv[3];
	napi_value _this; // <=FOR WHAT THIS _THIS???
	napi_value resource_name;
	void* data;// <= FOR WHAT THIS DATA??? c->data=data???
	//napi_open_handle_scope(env,&scope);
	
	NAPI_CALL(env,napi_get_cb_info(env,info,&argc,argv,&_this,&data));
	//NAPI_ASSERT(env,argc >=3,"not enough arguments, expected 3?.");
	c->_output=0;
	NAPI_CALL(env,napi_get_value_int32(env,argv[0],&c->_input));
	
	NAPI_CALL(env, napi_create_reference(env,argv[2],1,&c->_callback));
	
	NAPI_CALL(env, napi_create_string_utf8(env,"TestResource",NAPI_AUTO_LENGTH, &resource_name));
	
	NAPI_CALL(env, napi_create_async_work(env,argv[1],resource_name,Execute,Complete,c, &c->_request));
	
	NAPI_CALL(env, napi_queue_async_work(env,c->_request));
	return nullptr;
	}


napi_value Init(napi_env env,napi_value exports){

napi_property_descriptor properties[]={
	DECLARE_NAPI_PROPERTY("Test",Test),
};
NAPI_CALL(env, napi_define_properties(env,exports,sizeof(properties)/sizeof(*properties),properties));
return exports;
}

NAPI_MODULE(addon,Init);
```

**Comment by kfarnung** [comment]
Great to hear @Globik! I'll close this issue for now, but feel free to reactivate or create a new issue.
