### ISSUE TITLE
AWS server testing issue with node inspector

### ISSUE THREAD

**Issue by jdal** [nodejs/help#1056]
* **Node.js Version v8.9.3 **:
* **OS AWS Ubuntu 16.04**:
* **Scope Debugger**:
* **Module (and version) (if relevant)**:

I am having an issue using node inspector on an AWS server as follows:

geofit@virginia:/usr/local/antaeus/PluginManager$ node --inspect-brk=$HOSTNAME PluginManager.js 
Starting inspector on virginia.antaeus.cloud:9229 failed: address not available

I have opened port 9229 on the server, and tested it for remote access using netcat/ping as follows:

From the remote machine (Not on AWS):
dlambert@development:~$ nc virginia.antaeus.cloud 9229
Test from outside <<<Sent to the AWS sever
^C
dlambert@development:~$ ping virginia.antaeus.cloud
PING virginia.antaeus.cloud (54.224.230.140) 56(84) bytes of data.
64 bytes from ec2-54-224-230-140.compute-1.amazonaws.com (54.224.230.140): icmp_seq=1 ttl=42 time=58.3 ms
64 bytes from ec2-54-224-230-140.compute-1.amazonaws.com (54.224.230.140): icmp_seq=2 ttl=42 time=57.3 ms

From the AWS server:

geofit@virginia:/usr/local/antaeus/PluginManager$ nc -l 9229
Test from outside <<<Text from the remote machine received OK

geofit@virginia:/usr/local/antaeus/PluginManager$ node --inspect-brk=$HOSTNAME PluginManager.js 
Starting inspector on virginia.antaeus.cloud:9229 failed: address not available

**Comment by eugeneo** [comment]
Can you try specifying the IP address?

**Comment by jdal** [comment]
Thanks. I had tried this, but with the IP routable from outside, but now you made me realize that the AWS local IP address is rerouted
Now it seems to work with the internal IP address.
