### ISSUE TITLE
Basic Form handling question

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1057]
Hi all,

I have a very basic question on NodeJS. In Express I have a form set up and a post method that handles it, and writes the formdata to a .JSON file . It looks like this: 
```javascript
app.post('/adminpanel', urlencodedParser, function (req, res) {
	if (!req.body) return res.sendStatus(400)
	fs.readFile('u1-searchqueries.json', 'utf8', function(err,data){
		if(err) {
			console.log(err.message);
		}
		var searchQueries = JSON.parse(data);
		var username = req.body.user;
		var userpass = req.body.pwdg;
		var adminpass = req.body.pwd;
		var usermail = req.body.useremail;

		if (adminpass===searchQueries.pwda) {
		searchQueries.searchQueries.users[username]={"userqueries":[],"email":usermail,"pwu":userpass};
		fs.writeFile('u1-dataAds.json', JSON.stringify(searchQueries));
		}
	});
	res.send'Form isworking' );

})
```
So I'm wondering:
- If a hundred people fill in this form at once, what will happen? Wont the JSON file break because all of those people are putting data into it at once? Will Node be able to handle all this new input even if lots of concurrent users are POSTing it? Or can I assume that, because of the async function/nature of Node it will be handled one at a time and will work just fine?
- Also, if the function would be readFileSync, would the situation be that every time a user filled in a form (and thus writing to the JSOn file) it would also block other users from using the form?

Greets and many thanks

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by ORESoftware** [comment]
Why are people filling out a form on a server? shouldn't they be filling out a form on the client?

also your code needs some work:

```js
app.post('/adminpanel', urlencodedParser, function (req, res) {
  
  fs.readFile('u1-searchqueries.json', 'utf8', function (err, data) {
    if (err) {
      console.log(err.message);
      return res.json({error:err.stack});
    }
    var searchQueries = JSON.parse(data);
    var username = req.body.user;
    var userpass = req.body.pwdg;
    var adminpass = req.body.pwd;
    var usermail = req.body.useremail;

    if (adminpass === searchQueries.pwda) {
      searchQueries.searchQueries.users[username] = {"userqueries": [], "email": usermail, "pwu": userpass};
      fs.writeFile('u1-dataAds.json', JSON.stringify(searchQueries));
    }

    res.send('Form isworking');
  });
});
```

**Comment by samundrak** [comment]
You can lock file system after opening so other have to wait for it, you can use this module [https://www.npmjs.com/package/lockfile](https://www.npmjs.com/package/lockfile)

**Comment by WAINGOR** [comment]
Thanks all for the feedback! @ORESoftware what exactly would you call an improvement in the code you wrote above (Apart from removing the consoles)? Also I see that you make use of async without callbacks, which is deprecated... Thanks a lot for your efforts :)
