### ISSUE TITLE
v8.serialize  is so strange!

### ISSUE THREAD

**Issue by askforone** [nodejs/help#1059]
* **Node.js Version 8.94:
* **OS**:  Win7 64

I think v8.serialize will be faster than JSON... but not?
and
v8.serialize(value)   is slower  than  v8.serialize(value).toString()

Plz test the codes below; 

```js
// I am an example of JS code
var deco_getSyncRunTime = function(func, times){
    var t = Date.now();
    for(var i=0; i<times; i++){
        func();
    }
    console.log('run time:', Date.now() - t);
    console.log(process.memoryUsage());
}

var v8 = require('v8');
var test_func_1 = function(){
    return v8.serialize(obj).toString(); //1e6   11sec
}
var test_func_2 = function(){
    return v8.serialize(obj);  //1e6   21sec    why
}
var obj = {"dirty_map":{"pid":1},"pid":1,"uid":"","wid":"","phone":"","wechat":"","currency_1":3000,"char_1":{"dirty_map":{"money":1},"money":5}};

setTimeout(function(){
    deco_getSyncRunTime(test_func_1, 1e6);
    //deco_getSyncRunTime(test_func_2, 1e6);
}, 1e4);

-->

**Comment by bnoordhuis** [comment]
> I think v8.serialize will be faster than JSON... but not?

Its raison d'être is that it supports more types than plain JSON.  No one said anything about it being faster. :-)

**Comment by askforone** [comment]
but why 
v8.serialize(obj).toString()   is  faster than  v8.serialize(obj)

**Comment by bnoordhuis** [comment]
I ran it a few times and there's so much variance between runs that I can't really draw meaningful conclusions but it's probably because the `.toString()` forces more GC scavenges, keeping the memory footprint down.

If you start node with `--expose_gc` and call `gc()` every 1,000 iterations, they perform about the same.

**Comment by askforone** [comment]
I think it's not a reasonable explanation, gc may cost more time。
so I feel there's something wrong of the buffer gc。does buffer still alloc external memory outside of v8?

**Comment by bnoordhuis** [comment]
Yes.

**Comment by gireeshpunathil** [comment]
close-able?

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding.
