### ISSUE TITLE
[v8 engine] Weird error thrown

### ISSUE THREAD

**Issue by 6-8-axnw1bom81v5xa3nh48c** [nodejs/help#1060]
* **Node.js Version**: master
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: /

Consider this code

```JavaScript
'use strict';

new Function(`(a={a:a=>a})+${'a.a``+'.repeat`1e3`}\n(a=>{throw new Error()})()`)``
```

It should throw something like

```
Error
    (eval at <anonymous> (main.js:3:1), <anonymous>:3:12) at eval (eval at <anonymous> (main.js:3:1), <anonymous>:3:25)
    at Object.<anonymous> (main.js:3:81)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
```

But instead, it prints `a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a......` at the beginning of the stack trace, like the error is trhown inside a call of the function `a` (which is wrong). The error is thrown **after** all functions `a` finished execution.

In firefox it throws error

```
uncaught exception: anonymous/<@main.js line 13 > Function line 45 > Function line 5 > Function:4:12
anonymous@main.js line 13 > Function line 45 > Function line 5 > Function:4:1
anonymous@main.js line 13 > Function line 45 > Function:5:1
main/<@main.js line 13 > Function:45:9
main/xhr.onreadystatechange@main.js line 13 > Function:145:9
```

Which is correct. Notice that there is no function `a` in the stack trace. For some reason, Node.js prints `a` in the stack trace thousand times, but `a` is not part of the call stack at the time the error is thrown.

Is this a bug, or is intended behavior? I'm filing issue here and not in main repo, because I'm not sure if you are aware of this behavior.

**Comment by bnoordhuis** [comment]
That's the result of V8's function name inference algorithm.  It computes a human-readable name for anonymous functions on a best-effort basis by looking at the surrounding context.  It works okay most of the time but in code like you posted, it doesn't have much to go on.

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
So, it means this is working as intended, I suppose. Ok, I'm closing this issue.
