### ISSUE TITLE
The endless child_process? Is this how it is expected??

### ISSUE THREAD

**Issue by DerKatzeLP** [nodejs/help#1065]
* **Node.js Version**: 8.9.3
* **OS**: Raspbian Lite
* **Scope (install, code, runtime, meta, other?)**: code, runtime
* **Module (and version) (if relevant)**: child_process

Hello,

i have some issues with the execSync function.
The child_process never exits for some reason i don't understand.
It would be nice to know why it gets stuck.

**It works fine like this:**
```js
code = require('child_process').execSync( "" ).toString();
return "Finish";
```

**It never ends with this code / no return will be send:**
```js
code = require('child_process').execSync( "echo hallo" ).toString();
retrun "Finish";
```

Please tell me what went wrong and how i can fix this problem.

**Of course I have read the following:**
[nodejs.org/api](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options)

> The child_process.execSync() method is generally identical to child_process.exec() with the exception that the method will not return until the child process has fully closed. When a timeout has been encountered and killSignal is sent, the method won't return until the process has completely exited. Note that if the child process intercepts and handles the SIGTERM signal and doesn't exit, the parent process will wait until the child process has exited.
Maybe I just do not understand that right. :(

If this works as expected, which function can i use then to just get the output of a shell-command into a variable in nodeJs and use it afterwards?
Exec doesn't works for me :(

Thank you =)

**Comment by theShivaa** [comment]
I second case you have made a Typo most probably thats why your code never ends . you have typed  **retrun** instead of **return**

**Comment by ORESoftware** [comment]
dynamic languages FTW :)

**Comment by DudeVoid** [comment]
JavaScript isn't Python so you'd have to use `var`, `let` or `const` when defining a variable(s).

**Comment by DerKatzeLP** [comment]
Hey,

okay thank you.
My typo is just here in this Text but not in my original code. Sorry for that one.

And may be i dont have to write var or something like that but thats not the Problem here.

I hope for more problem-related solutions.

**Comment by ORESoftware** [comment]
dunno, try:

```js
code = require('child_process').execSync( 'echo hallo; exit;' ).toString();
return "Finish";
```

**Comment by DerKatzeLP** [comment]
I have found a workaround that works for me.
Issue closed.
