### ISSUE TITLE
Connect hortonworks hive in node express js

### ISSUE THREAD

**Issue by gattewar** [nodejs/help#1066]
I want to connect hortonworks hive with user name , password, SASL type, hive server 2. I did not found any code which ia running fine. It may be i have done something wrong. It would be great if you provide example code. But my hive server does not have cluster.

**Comment by ORESoftware** [comment]
I had a task to connect to hive Node.js...eventually we learned that the only good connection to hive is JDBC and some other things like that, so ended up using Java

**Comment by gattewar** [comment]
I tried to install java and jdbc driver through npm but it's not going to
install. Can you help me with connection of hortonworks hive connection. It
would be appreciated if you can provide me source code with some
documentation if available. Hoping for solution. Thanks in advance.

**Comment by gireeshpunathil** [comment]
@gattewar  - is this still outstanding?

**Comment by gireeshpunathil** [comment]
thanks for clarification, closing then

**Comment by ArunKarthick-pss** [comment]
@gattewar,

I need to connect hive database using hive driver package npm in node-js. But In this package, Session is not connected properly. Please any alternate solution for this
