### ISSUE TITLE
Get Windows console codepage

### ISSUE THREAD

**Issue by kAlvaro** [nodejs/help#1067]
* **Node.js Version**: does not matter
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

Is there a way (either builtin, either with a plug-in) to read the value of the Windows console codepage? Running `chcp` and parsing its output does not seem the most robust approach.

_The context is that I run a third-party program from within Node the encodes its output in the default console codepage and I need to convert it back to UTF-8 but I cannot do it reliably if I just hard-code `CP850`._

**Comment by gireeshpunathil** [comment]
`chcp` is not abstracted in node, but is easily availed with the help of a native add-on:

```c++
#include <node.h>
#include <windows.h>

using namespace v8;

void GET(const FunctionCallbackInfo<Value>& args) {
  Isolate* isolate = args.GetIsolate();
  Local<Number> chcp = Number::New(isolate, GetConsoleOutputCP());
  args.GetReturnValue().Set(chcp);
}
void init(Local<Object> exports) {
  NODE_SET_METHOD(exports, "get", GET);
}
NODE_MODULE(NODE_GYP_MODULE_NAME, init)
```

```js
var chcp = require('./chcp')
console.log(chcp.get());
```
```
D:\addon>node foo.js
437
```

Please let me know if you are able to build (with the help of [native add-on documentation](https://nodejs.org/api/addons.html)) and use this for your purpose.

**Comment by kAlvaro** [comment]
So... The feature exists but its not exposed to userland code, did I understand correctly?

(I couldn't compile successfully at first attempt, I'll try later with more time.)

**Comment by bnoordhuis** [comment]
If you mean "exists internally in node.js": no.  The add-on calls a Win32 API and returns the result to JS land.

**Comment by gireeshpunathil** [comment]
@kAlvaro - let me know if you were able to use the add-on for your purpose.

**Comment by kAlvaro** [comment]
@gireeshpunathil I'm stuck in the compilation phase (I'm unable to install build tools for Visual Studio) but my question has been definitively answered anyway.

**Comment by kAlvaro** [comment]
I eventually ran `npm install -g node-gyp@latest` from an elevated prompt and build tools for Visual Studio started working magically :-?

Full recipe:

1. Install dependencies from elevated prompt:

        npm install -g node-gyp@latest
        npm install --global --production windows-build-tools

1. Create `binding.gyp`
1. Create build files

	    node-gyp configure

1. Create `chcp.cc`

1. Compile

	    node-gyp build

1. require() *.node file (without extension, base name can be changed)

The `.get()` methods returns a number (e.g. `850`).

**Comment by gireeshpunathil** [comment]
great to know! I think you got all the steps right. Feel free to use the code for your purpose as well as extend it if you wish - for example, implementing a setter to complement the getter.

**Comment by bnoordhuis** [comment]
@gireeshpunathil You should publish that as a module!

**Comment by gireeshpunathil** [comment]
@kAlvaro - I have built this an `npm` module: https://www.npmjs.com/package/chcp
