### ISSUE TITLE
Problem with Apple Sample code which uses Node.js

### ISSUE THREAD

**Issue by jeroenleenarts** [nodejs/help#107]
It seems related to special characters.

If I take the Apple node server-2-server sample code from here: https://developer.apple.com/library/prerelease/ios/samplecode/CloudAtlas/History/History.html#//apple_ref/doc/uid/TP40014599-RevisionHistory-DontLinkElementID_1

And then change the line on line 48 to include a special character in the recordName, like change "hello-u" to "hello-ü" the Apple provided Node.JS sample code crashed. If I perform the same change in their browser based sample code. It works. Filed an Apple Rader on it, no response as of yet: http://openradar.appspot.com/radar?id=4983964439674880

Clues or suggestions are much appreciated. :)

**Comment by williamkapke** [comment]
I think you meant to use this url:
https://developer.apple.com/library/prerelease/ios/samplecode/CloudAtlas/Listings/Node_node_client_s2s_index_js.html

**Comment by williamkapke** [comment]
This is likely something within the CloudKit lib. Can you explain more about the crash? Is there an error message? Stack trace?

**Comment by jeroenleenarts** [comment]
In the fail case I get an output ending with:

{ [Error: Authentication failed]
  _ckErrorCode: 'AUTHENTICATION_FAILED',
  _uuid: '163243ab-8145-4f3e-9e79-efce248defd3',
  _reason: 'Authentication failed',
  _serverErrorCode: 'AUTHENTICATION_FAILED',
  _extensionErrorCode: undefined,
  _retryAfter: undefined,
  _recordName: undefined,
  _subscriptionID: undefined,
  _zoneID: undefined,
  _redirectURL: undefined,
  message: 'Authentication failed' }


My guess is it's related to string encoding related.
