### ISSUE TITLE
Running behind corporate proxy and unable to install npm packages 

### ISSUE THREAD

**Issue by helenanita** [nodejs/help#1072]
* **Node.js Version: v8.4.0
* ** OS : Windows OS
* **Scope (install, code, runtime, meta, other?)**: install npm live-server
*** npm version : 5. 3.0

I tried to install npm live server in nodejs. But I'm unable to install as i am running behind corporate proxy. I have not set any username and password for my http and https proxy. It is running like this.
Somebody please explain how to get my packages installed.

I even tried so many fom stackoverflow ....

C:\Users\626484>npm config set strict-ssl false
 C:\Users\626484>npm config set registry "registry.npms.org/"; 
C:\Users\626484>npm --proxy http://@cacheaddress.com.br:80\ install live-server 
npm ERR! code ECONNREFUSED npm ERR! errno ECONNREFUSED npm ERR! FetchError: request to registry.npms.org/live-server failed, reason: connect ECONNREFUSED 74.122.238.10:8080 

C:\Users\626484>npm install -g live-server
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://registry.npms.org/live-server failed, rea
son: connect ECONNREFUSED 74.122.238.10:8080
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\n
pm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-np
m\src\index.js:68:14)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at ClientRequest.emit (events.js:210:7)
npm ERR!     at Socket.socketErrorListener (_http_client.js:401:9)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at Socket.emit (events.js:210:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!  { FetchError: request to http://registry.npms.org/live-server failed,
reason: connect ECONNREFUSED 74.122.238.10:8080
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\n
pm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-np
m\src\index.js:68:14)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at ClientRequest.emit (events.js:210:7)
npm ERR!     at Socket.socketErrorListener (_http_client.js:401:9)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at Socket.emit (events.js:210:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!   message: 'request to http://registry.npms.org/live-server failed, rea
son: connect ECONNREFUSED 74.122.238.10:8080',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to http://registry.npms.org/live-server f
ailed, reason: connect ECONNREFUSED 74.122.238.10:8080\n    at ClientRequest.req
.on.err (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\pacote\\nod
e_modules\\make-fetch-happen\\node_modules\\node-fetch-npm\\src\\index.js:68:14)
\n    at emitOne (events.js:115:13)\n    at ClientRequest.emit (events.js:210:7)
\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (eve
nts.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (intern
al/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next
_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:18
0:9)' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\626484\AppData\Roaming\npm-cache\_logs\2018-01-19T06_31_04
_154Z-debug.log

**Comment by gireeshpunathil** [comment]
can you please see if following these documents help?
https://github.com/nodejs/node/blob/master/deps/npm/TROUBLESHOOTING.md#proxy-and-networking-issues
https://docs.npmjs.com/misc/config#https-proxy

**Comment by gireeshpunathil** [comment]
@helenanita - were you able to solve this?

**Comment by helenanita** [comment]
Hello...I solved this by giving my username with password.. Thank you for the guidance.

**Comment by vijjuh** [comment]
@helenanita : could you please share the detail , how you have resolved this issue , as i'm also facing issue.
and not able to install the modules due to firewall.

@gireeshpunathil : i have tried with your given steps , but did not get what exactly i need to do it or what exactly changes i have to done ?

**Comment by hrishiawari** [comment]
delete package-lock.json and run npm install

**Comment by tom14mac** [comment]
what the package i delete

**Comment by mdmasudrana** [comment]
npm config set proxy null
npm config set https-proxy null
npm config set registry http://registry.npmjs.org/
