### ISSUE TITLE
Easy/beginner question

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1074]
Hi all,

I have a working app running on NodeJS + Express... I want to create a URL/page that, if requested, serves  a .JSON object.., I am currently using a request module but its not working .

- The code below logs test "TESTundefined
undefined
listening on 3000" to my console
Here are the relevant parts of my files:
Index.js:
```javascript
router.get('/senddata', function(req, res, next) {
	fs.readFile('u1-searchqueries.json', 'utf8', function(err,data){
		if(err) {
			console.log(err.message);
			return res.json({error:err.stack});
		}
		var completeData = JSON.parse(data);
		res.send(completeData);
	});
});

```
App.js
```javascript
var url = "/senddata";
request(url,function(err,resp,body){
 if(err){
	 console.log("test TEST" + body);
 }
 console.log(body);
});

```
- Eventually I want to have my local Node server request this object from a live environment, but that would be no different than requestion this object from the server that it's on , right? Except for changing the URL's offcourse. 
PS: I am positive that the path to "u1-searchqueries.json" is correct and that it contains valid JSON. I have tested this in other files.

**Comment by gireeshpunathil** [comment]
#cat r.js
```js
var express = require('express')
var router = express()
var fs = require('fs')

router.get('/senddata', function(req, res, next) {
  fs.readFile('u1-searchqueries.json', 'utf8', function(err,data){
    if(err) {
      console.log(err.message);
      return res.json({error:err.stack});
    }
    var completeData = JSON.parse(data);
    res.send(completeData);
  });
});
router.listen(30000)
```

#cat app.js

```js
var request = require('request')
var url = "http://localhost:30000/senddata";
request(url,function(err,resp,body){
 if(err){
	 console.log("test TEST" + body);
 }
 console.log(body);
});
```

#node r.js &
[2] 10522

```
#node app.js 
{"glossary":{"title":"example glossary","GlossDiv":{"title":"S","GlossList":{"GlossEntry":{"ID":"SGML","SortAs":"SGML","GlossTerm":"Standard Generalized Markup Language","Acronym":"SGML","Abbrev":"ISO 8879:1986","GlossDef":{"para":"A meta-markup language, used to create markup languages such as DocBook.","GlossSeeAlso":["GML","XML"]},"GlossSee":"markup"}}}}}
#
```

The only major change I introduced is fully qualifiying the `url` in the app.

Hope this helps.

**Comment by gireeshpunathil** [comment]
@WAINGOR - were you able to solve your problem by following the step mentioned?

**Comment by WAINGOR** [comment]
Hi gireesh, sorry for the late response. No, but I did solve it in another way :) thanks

**Comment by gireeshpunathil** [comment]
thanks!
