### ISSUE TITLE
about macOS pkg edition uninstall

### ISSUE THREAD

**Issue by mitixx** [nodejs/help#1075]
* **Node.js Version**:8.x~9.x
* **OS**:MacOS high sierra

Nice to meet you.
I installed the node.js for mac from official site pkg.
But want the exchange in homebrew edition is.
However, the uninstall method is pkg edition couldn't find.
Do I how to uninstall pkg edition in this case?

I'm Japanese so I can't good English.
Sorry, artificial English.
Any help would be appreciated.

**Comment by nigelhanlon** [comment]
There is a way to uninstall pkg files using the `pkgutil` command line tool. 

This Gist describes how: https://gist.github.com/githubutilities/b5318d08a4b970d104f1.

I would be careful though as this involves running the `rm` command as root via `sudo`.
It should work but if done wrong, could cause big problems.

**Comment by mitixx** [comment]
Dear Mr.nigelhanlon
Thank you for the information!
I will try it once.

**Comment by mitixx** [comment]
The problem did solve successfully!!

**Comment by gireeshpunathil** [comment]
Closing, please re-open if anything is outstanding in this.
