### ISSUE TITLE
How to implement a Transform stream?

### ISSUE THREAD

**Issue by jyzykunyv** [nodejs/help#1076]
* **Node.js Version**: v9.4.0
* **OS**: win10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: stream

I'm trying to implement a stream which will read data from one stream, then xor each byte with 255 and then write data to another stream. For example:

```JavaScript
var fstream = fs.createWriteStream('1.txt');
var mystream = createMyStream();

mystream.pipe(fstream);
mystream.write(Buffer.from('ABC'));
mystream.end();
```

The content of the file `1.txt` after executing my script should be `BE BD BC` in hexadecimal (string `ABC` with each bit flipped). How to implement `MyStream`?

### My attempt

```JavaScript
function createMyStream(){
  return new stream.Transform({
    writableObjectMode: true,
    transform: transformFunc
  });

  function transformFunc(chunk, encoding, callback){
    var data = chunk.map(a => a ^ 0xFF);

    callback(data);
  }
}
```

But, unfortunatelly, I got error

```
events.js:143
      throw err;
      ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (?t????????)
    at Transform.emit (events.js:141:19)
    at Transform.onerror (_stream_readable.js:670:12)
    at Transform.emit (events.js:160:13)
    at onwriteError (_stream_writable.js:422:12)
    at onwrite (_stream_writable.js:450:5)
    at Transform.afterTransform (_stream_transform.js:89:3)
```

I don't even know if `stream.Transform` is a good tool for this use. Should I use Duplex instead? The parts from the docs which talk about implementing streams are not clear to me.

Thanks.

**Comment by addaleax** [comment]
What you got here seems almost right! There are two minor issues:

* The transform callback has the form `callback(error, data)` (like all other callbacks provided by Node), so you need to use `callback(null, data);` instead – right now, the callback thinks you’re trying to pass it an error
* Setting `writableObjectMode: true` is probably not what you want if you want to work with actual byte sequences (buffers). Using object mode means that chunk can by *any* kind of object, not just a Buffer. I think you can just leave that out.

**Comment by jyzykunyv** [comment]
@addaleax That exactly solved my problem! Thanks a lot!

**Comment by jimmont** [comment]
based on the dialog, this appeared to be the correct working solution, ie the "transformStream" thingy:
```function streamer(){
  return new require('stream').Transform({
    transform: function transformer(chunk, encoding, callback){
        // callback(<error>, <result>)
        callback(false, <transformed-chunk>);
    }
  });
}```

**Comment by d-beltran** [comment]
Is this implementation smart enough to handle backpressure?
