### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Shellyhan** [nodejs/help#1077]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by gibfahn** [comment]
@Shellyhan if you have a question let us know! Otherwise if this was opened by mistake please close it.

**Comment by Shellyhan** [comment]
hi there, sorry about the confusion. It's a mistake, must be my cat posting
it. Thanks for closing the ticket. Have a nice day!
