### ISSUE TITLE
Cannot uninstall old version

### ISSUE THREAD

**Issue by judag** [nodejs/help#108]
Hi !!! I want to unnistall and old version and install the latest, but cannot do it because when I want to do that it ask me for the msi and it's missing...Can you help me please I'am new with this and I have to learn and work. Thanks a lot!!! Regards... Judith Neumann
![screenshot_2](https://cloud.githubusercontent.com/assets/6303123/13628384/74e6bbca-e5b0-11e5-96f2-1cf311d6a950.png)

**Comment by williamkapke** [comment]
So you're getting this when trying to uninstall? I always just run the latest installer and it overwrites the old version.

**Comment by judag** [comment]
Yes I tryed to overwrite it but I have the same travel... I have not experience yet with this...:)

**Comment by judag** [comment]
Ok I suposse that I have to install node in another device so I can get the package is that so?

**Comment by kelthenoble** [comment]
`Try these` links https://discussions.apple.com/thread/4382893?tstart=0   but you may want to **start** with this one ->   http://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/the-path-to-the-silverlighmsi-file-could-not-be/0eb0ea02-809b-4784-aac0-03bcc737c348?auth=1

**Comment by judag** [comment]
I will take a look!!! Thanks a lot!!! :)

**Comment by kelthenoble** [comment]
I'm sure they will help, just like @williamkapke been helping you so far. When you find a solution. Please close this issue. Many thanks. And let us know if you need further assistance.

**Comment by judag** [comment]
Thanks a lot for everybody...you are very kind..:) . I could not fixed the problem yet I will continue looking for a solution... Best regards!!! :)

**Comment by lordKnighton** [comment]
Hey @judag did you get this fixed?

**Comment by judag** [comment]
Hi @lordKnighton  yes I fixed this!!! :) Thanks a lot for asking and helping!!! Best regards!!! :)

**Comment by lordKnighton** [comment]
That's very good to hear.Well come back anytime :+1:  

======
closing for now, feel free to reopen.
