### ISSUE TITLE
http2: does response.write() flush data to a socket?

### ISSUE THREAD

**Issue by LPardue** [nodejs/help#1081]
* **Version**: 9.4.0
* **Platform**: Windows 10
* **Subsystem**: http2

I've got some test code where i would like to write a long response on a stream and see a client read it out chunk-by-chunk using ReadableStream.

The server writes the response header and then loops N amount of times writing a line of text. After N the response is ended with the line "End".

When N is large, I was expecting to see the server writing lines of the response and the client print out chunks that it had received. However, what I see instead is that the server spends a long time writing lines to the response, and that the client only starts to receive chunks once the final line is done.

This implies that response.write() does not flush data to the socket. Instead, the flush occurs when response.end() is called. If that is true, is there any way to get the behaviour I am after?

**Server node.js code**
```const http2 = require('http2');
const fs = require('fs');

const server = http2.createSecureServer({
  key: fs.readFileSync('localhost-privkey.pem'),
  cert: fs.readFileSync('localhost-cert.pem')
});

server.listen(8443);
server.on('error', (err) => console.error(err));
server.on('socketError', (err) => console.error(err));

const reqHandler = (req, res) => {
  res.writeHead(200, {
    'Content-type': 'text/plain',
    'access-control-allow-origin': '*'
  });

  for (let i=0; i < 500000; i++)  {
    res.write(`Line ${i}\n`);
    console.log(`Line ${i}`);
  }

  res.end('End\n');
};

server.addListener("request", reqHandler);
```

**client.html**
```
<h1>Long response readablestream test</h1>

<script>
  async function fetchLongResponse() {
    const response = await fetch('https://localhost:8443/foo');
    const reader = response.body.getReader();

    while (true) {
      const {done, value} = await reader.read();
      if (done) {
        console.log('done!');
        return;
      }
      console.log(new TextDecoder('utf-8').decode(value));
    }
  }
</script>

<body>
    <button onclick="fetchLongResponse()">Fetch Long Response</button>
</body>
```

**Comment by addaleax** [comment]
> This implies that response.write() does not flush data to the socket. Instead, the flush occurs when response.end() is called.

Writing data to the socket occurs after the current call stack has cleared (think of it as a `setImmediate()` or `process.nextTick`), `response.end()` is not related to that.

> The server writes the response header and then loops N amount of times writing a line of text.

A problem with what you’re doing right now is that you ignore the return value of `.write()` and/or don’t attach a callback to it.

The stream will tell you once its buffers are full that you should wait with writing more data to it; if `.write()` returns false, you should wait until the `drain` event on the stream (or until the callback to `.write()` has been called), which tells you to write more data.

(Here’s the docs for `.write()`: https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback)

**Comment by LPardue** [comment]
Hey @addaleax, thanks for the answer!

I modified my code in line with the example on that page. This seems work, the client sees the time to first byte reduce from 7 seconds to 1.

Now the important bit looks like:

```
function myResponseWrite(response, data, cb) {
  if (!response.write(data)) {
    response.once('drain', cb);
  } else {
    process.nextTick(cb);
  }
}

const reqHandler = (req, res) => {
  res.writeHead(200, {
    'Content-type': 'text/plain',
    'access-control-allow-origin': '*'
  });

  for (let i=0; i < 1000000; i++) {
    myResponseWrite(res, `Line ${i}\n`, () => {
      // write completed, do more writes now
    });
  }

  res.end('End\n');
  console.log('Done!');
};
```

heres the output I see with this change

```
Line 1
// snip
Line 1748
(node:17024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
// no more lines logges
```

**Comment by addaleax** [comment]
@LPardue That makes sense to me – you are still writing all the data synchronously, so it all gets stored in one large buffer, that is only drained after writing a bunch of lines has finished.

If you want proper backpressure handling, you will actually need to stop writing once `write()` returns false, and then wait for the `'drain'` callback to be called.

**Comment by LPardue** [comment]
@addaleax thanks again for the help, I'm gonna close this now as I think I know what I'm doing.
