### ISSUE TITLE
How to force the occurance of a problem.

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/help#1083]
I am hunting down a tricky error in Node.js's core for Win. Its about the following lines:

https://github.com/nodejs/node/blob/02fef8ad5a6c0e5c1ce0d4b46aa3a762935c981c/lib/internal/child_process.js#L571-L579

```javascript
target._send({ cmd: 'NODE_HANDLE_ACK' }, null, true);
var obj = handleConversion[message.type];

// Update simultaneous accepts on Windows
if (process.platform === 'win32') {
  handle._simultaneousAccepts = false;
  net._setSimultaneousAccepts(handle);
}

```

it seems that under the right circumstances `._send(` might trigger the closing of the handle which then later lets `net._setSimultaneousAccepts` throw a memory access error (in c-code: triggering a hard-close of node)

That behavior has been hard for me to reproduce so I wonder: How could I force trigger the error in a simple example, worthy of an issue to the node repository.

**Comment by addaleax** [comment]
How frequently does that problem occur? Enough to get it to fail in a C/C++ debugger after a couple attempts?

**Comment by martinheidegger** [comment]
Hmm, yes : in a complex system. I have a test case failing constantly but only if the whole of the suite is run - not some single test. Which made it hard to triangulate. Not sure how to attach a C/C++ debugger to the node process (not a windows person; not a c person)

**Comment by addaleax** [comment]
> I have a test case failing constantly but only if the whole of the suite is run - not some single test.

That’s interesting. How are you running the single test? Using `python tools/test.py <path-to-test>` or `node <path-to-test>`? What happens if you use something like `python tools/test.py --repeat=1000 -j 16` to push up load on your machine? 

> Not sure how to attach a C/C++ debugger to the node process (not a windows person; not a c person)

If you’re using VSCode, there are some things you can look up to make that happen.

**Comment by martinheidegger** [comment]
It's the spectron testcase of an dat-desktop. Tbh. It had been kinda rough to track the issue - also because I use a Mac - which is why I thought the opposite road: trying to dump a socket during ACK might be easier to reproduce, pinpoint and test... I will need to look at it more in the office

**Comment by gireeshpunathil** [comment]
@martinheidegger - is this still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing
