### ISSUE TITLE
uninstall npm

### ISSUE THREAD

**Issue by q4solutions** [nodejs/help#1086]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by ProfNandaa** [comment]
@q4solutions - Did you complete this ticket or is this spam?

**Comment by arswaw** [comment]
It seems to me they didn't even bother to notice that there's a template to be filled out.

**Comment by bnoordhuis** [comment]
Yep, let's close this out.
