### ISSUE TITLE
Getting Nodejs to work on standalone C++ application on Windows

### ISSUE THREAD

**Issue by ehsanen** [nodejs/help#1087]
* **Node.js 8.9.1**:
* **Windows 10**:
* **Scope (code, runtime)**:

We have embedded nodejs into our C++ crossplatform app. We faced a crash bug, which was cause by the lack of stdin when you do not run the node from command line. We noticed that there is already a pull request [#11863](https://github.com/nodejs/node/pull/11863) for this issue and we have these changes in our nodejs code. But this does not solve our problem as the `PlatformInit()` function in node.cc never gets called. Here is how we initialise node and v8 in our program:

```
platform_ = new node::NodePlatform(8, loop_, nullptr);
node::i18n::InitializeICUDirectory("");
v8::V8::InitializePlatform(platform_);
v8::V8::Initialize();
```

copied directly from `SetUp()` function in  `node_test_fixture.h`. 

interestingly we just face this problem on Windows not on macOs. We solved it now by adding this line

```
NODE_EXTERN void PlatformInit();
```

to `node.h` file in the node namespace, and then calling `PlatformInit()` before creating the NodePlatform. So now our initialisation looks like this:

```
node::PlatformInit(); // new line added
platform_ = new node::NodePlatform(8, loop_, nullptr);
node::i18n::InitializeICUDirectory("");
v8::V8::InitializePlatform(platform_);
v8::V8::Initialize();
```

Now we are wondering is our initialisation wrong at first place or is this really a bug and we need to create a pull request for it. Please advice.

**Comment by bnoordhuis** [comment]
> which was cause by the lack of stdin when you do not run the node from command line

Yes, `PlatformInit()` guards against that by ensuring that the stdio file descriptors are valid.  As an embedder, the best way forward is probably to duplicate that logic; it's only a few lines of code.

Calling `PlatformInit()` is not a good idea.  It's a grab bag of things for the standalone binary.  The initialization it does may not be suitable for the embedding application.

**Comment by ehsanen** [comment]
thanks for the reply. I assume by duplicating the logic you mean to do what the PlatformInit does right now, somewhere in my own source code. But do I have access to all the variables and defined objects that PlatformInit uses? I don't have my windows laptop nearby right now, but will give it a shot soon

**Comment by bnoordhuis** [comment]
You don't need anything specific.  The logic is this: https://github.com/nodejs/node/blob/v9.5.0/src/node.cc#L4422-L4434

**Comment by ehsanen** [comment]
I've tested that today and it worked. I did what bnoordhuis has suggested, duplicating the logic that PlatformInit does in my code and avoid touching the nodejs source code.

**Comment by DiegoBM** [comment]
ehsanen, could you please explain in more detail (hopefully with code example) how did you embed node.js without modifying node's source code? And how are you using it exactly (use the node loop?)

**Comment by viferga** [comment]
@DiegoBM I have detailed in this issue (https://github.com/nodejs/node/issues/23265#issuecomment-452690239) how I have solved the problem of NodeJS embedding with examples and a functional implementation.

**Comment by DiegoBM** [comment]
Thank you @viferga I finally solved my problem with a different solution, but if I consider integrating node.js again I'll consider your implementation
