### ISSUE TITLE
Node.js giving UnhandledPromiseRejectionWarning, even for code that doesn't have an unhandled promise rejection

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/help#1091]
I tried to run the `parcel index.html` command to build `country-currency-map` (a Node.js module), but I had an "UnhandledPromiseRejectionWarning" even though the library reportedly doesn't have an unhandled promise rejection.  Trying to do the "Getting Started" example on the Parcel.js page has the same result.  I already uninstalling and reinstalling Node.js and I even installed the latest version.  Still doesn't work.

I'm using Windows 10.  I also have WSL.  When I try to run the commands in the bash shell, though, I get an error saying "parcel: node: not found" even though I did install Node.js in WSL mode as well.  And it's also on my PATH.

**Comment by evanlucas** [comment]
Setting the `NODE_OPTIONS` environment variable to `--trace-warnings` should print out a stack trace for unhandled rejections (depending on what version of node you are using)

**Comment by DragonOsman** [comment]
Sorry for noob-question, but: Where do I set that?

**Comment by evanlucas** [comment]
@DragonOsman apologies, but I'm not a Windows user. A quick [google search](https://www.google.com/search?rlz=1C5CHFA_enUS687US691&ei=Beh0WrHRLsnatQWO46ngDA&q=windows+10+set+environment+variable&oq=windows+10+set+environment+variable) shows this. Hopefully, that helps! Thanks! :]

**Comment by gireeshpunathil** [comment]
you could also set it on the command prompt:
`set NODE_OPTIONS="--trace-warnings"` as a one time business (the setting expires along with the shell session). 

More simpler, you could add the option in-line to the node command (the setting lives only for the node command)

```trace
D:\home\gireesh>cat foo.js
require('util').debug('hello')

D:\home\gireesh>node --trace-warnings foo.js
DEBUG: hello
(node:11724) [DEP0028] DeprecationWarning: util.debug is deprecated. Use console.error instead.
    at Object.<anonymous> (D:\home\gireesh\foo.js:1:79)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
```
closing as answered, please let me know if you have additional questions.
