### ISSUE TITLE
An option to install Node prebundled with Yarn instead of NPM?

### ISSUE THREAD

**Issue by ozzie1998** [nodejs/help#1094]
* **Node.js Version**: Latest
* **OS**: Mac OS High Sierra
* **Scope (install, code, runtime, meta, other?)**:  other
* **Module (and version) (if relevant)**:

Would it be possible to have an option to install NodeJS with Yarn instead of NPM?

**Comment by gibfahn** [comment]
This has come up a lot before, e.g. in https://github.com/nodejs/node/issues/15244 and https://github.com/nodejs/node/issues/9161.

**Comment by mcollina** [comment]
What do you use to install Node? I typically use nvm.

**Comment by joyeecheung** [comment]
BTW, yarn already provide ways to install Node.js and Yarn together. https://yarnpkg.com/en/docs/install

**Comment by ORESoftware** [comment]
I think it would be more likely that Node.js comes with Yarn, than for Yarn to come with Node, at this point. NVM is the way to go, though, in general for installing Node on a developer's machine.

**Comment by gireeshpunathil** [comment]
I think this issue had run a good course of discussion with a lot of background information. Closing this, please let me know if there is anything outstanding.
