### ISSUE TITLE
Ports and IP's

### ISSUE THREAD

**Issue by esi5uxlab** [nodejs/help#1096]
Hi,

We're busy setting up our own network with Firewall and DMZ (Whitelist basis) because we work with sensitive Data. Because we already use your Software and would like to carry on using it, we need to know What ports, IP's and so on, your Software needs for it to work properly. Does your Software online services for "Call home", "License check", "Updates" and so on. Please share a list of everything your Software needs Internet for and which Ports, IT's, etc. it needs.

Thanks and greetings from Germany

**Comment by gireeshpunathil** [comment]
Answer is no, but:

> Because we already use your Software

can you elaborate on your usage of `the` software?

**Comment by esi5uxlab** [comment]
Good morning,

Thanks for the reply.

As to your question, we use it for car development, but, because everything here is TOP SECRET, I’m not able to elaborate, please understand.

mit freundlichen Grüßen / Best regards

Braam Lee

IT/Netzwerk
FERCHAU Engineering GmbH

im Auftrag der:
Dr. Ing. h.c. F. Porsche AG
Technologie Design Modelle Style Porsche - ESM4
Porschestraße D-71287 Weissach

Telefon: +49 711 / 911 - 83431
Fax:     +49 711 / 911 - 88599
E-Mail:  extern.abraham_johannes.lee@porsche.de


Dr. Ing. h.c. F.  Porsche Aktiengesellschaft
Sitz der Gesellschaft: Stuttgart
Registergericht: Amtsgericht Stuttgart HRB-Nr. 730623
Vorsitzender des Aufsichtsrats: Dr. Wolfgang Porsche
Vorstand: Oliver Blume, Vorsitzender
Lutz Meschke, stv. Vorsitzender
Andreas Haffner, Detlev von Platen, Albrecht Reimold, Uwe-Karsten Städter, Michael Steiner

Die vorgenannten Angaben werden jeder E-Mail automatisch hinzugefügt. Dies ist kein Anerkenntnis,
dass es sich beim Inhalt dieser E-Mail um eine rechtsverbindliche Erklärung der Porsche AG handelt.
Erklärungen, die die Porsche AG verpflichten, bedürfen jeweils der Unterschrift durch zwei zeichnungs-
berechtigte Personen der AG.





Von: Gireesh Punathil [mailto:notifications@github.com]
Gesendet: Freitag, 9. Februar 2018 04:49
An: nodejs/help <help@noreply.github.com>
Cc: Lee, Abraham Johannes (ESM4_EXTERN) <extern.abraham_johannes.lee@porsche.de>; Author <author@noreply.github.com>
Betreff: Re: [nodejs/help] Ports and IP's (#1096)


Answer is no, but:

Because we already use your Software

can you elaborate on your usage of the software?

**Comment by gireeshpunathil** [comment]
thanks then, closing as answered.
