### ISSUE TITLE
 I can't abel to install browser-sync in git bash

### ISSUE THREAD

**Issue by rohithreddybc** [nodejs/help#1101]
* **Node.js Version**:
* **OS**: Windows 10 pro
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

 I can't abel to install browser-sync . How can I install browser-sync in git bash by using this command ["npm install -g browser-sync" ].

**Comment by rohithreddybc** [comment]
Node.js Version:  8.4.0

**Comment by Martii** [comment]
You don't get something like this in git bash?:

``` sh-session
User@somewhere MINGW64 ~
$ npm install -g browser-sync
C:\Users\User\AppData\Roaming\npm\browser-sync -> C:\Users\User\AppData\Roaming\npm\node_modules\browser-sync\dist\bin.js

> uws@0.14.5 install C:\Users\User\AppData\Roaming\npm\node_modules\browser-sync\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\browser-sync\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ browser-sync@2.23.6
added 275 packages in 21.434s

User@somewhere MINGW64 ~
$
```

**Comment by rohithreddybc** [comment]
hi martii,
thank-you I got solution I suppose to add my proxy and port of my college.

**Comment by Martii** [comment]
@rohithreddybc 
Having the right network configuration is important. :smile: 

Would you mind closing the issue then please?

**Comment by gireeshpunathil** [comment]
closing as answered.
