### ISSUE TITLE
Is there a fix for Http connections aborted after 5s / keepAliveTimeout

### ISSUE THREAD

**Issue by samcov** [nodejs/help#1103]
* **8.6**:
* **Red Hat Linux**:

Is there a version of Node 8 that has the "Http connections aborted after 5s / keepAliveTimeout" problem fixed? See reference here: https://github.com/nodejs/node/issues/13391

We don't want to fall back to Node 6.4 as we're heavily using async/await.

**Comment by bnoordhuis** [comment]
Can you test with v8.9.4?

**Comment by samcov** [comment]
Is that version supposed to be the one that's fixed?

**Comment by bnoordhuis** [comment]
It was fixed sometime in 2017.  My point is that you should be testing against the latest release.

**Comment by samcov** [comment]
I'll check to see if that versions is in Red Hat Collections, it's not as easy as you might think to use the latest version. If you install unsupported version it affects support contracts wit Red Hat.

Who would know if the issue has been fixed, or where could I go to find this out?

**Comment by samcov** [comment]
Sorry, I see you said it was fixed, it's just likely you don't know exactly which version of node the fix made it into.

I'kk see if we can use the latest version, I guarantee that I'll get some push back :)

**Comment by bnoordhuis** [comment]
If you have a support contract with RedHat, you should get in touch with them.  The fix you're looking for is in v8.8.0.

I'll close this out, cheers.

**Comment by samcov** [comment]
Thanks, I really appreciate the quick response!!!

**Comment by apapirovski** [comment]
Just a note to say that if you're going to setup the 8.8 version then go for 8.8.1 and not 8.8.0 which, I believe, had a net-related bug in it. (Of course, even better would be to go straight to 8.9.4.)

**Comment by samcov** [comment]
@apapirovski, I agree, my goal is v8.9.4 as it also has some security fixes.
