### ISSUE TITLE
Cannot run node.js on Windows 7

### ISSUE THREAD

**Issue by ZhuWeiyang** [nodejs/help#111]
Hello, I installed `node.js-4.4.0(64bit version)` on `Windows 7 x64 SP1`. But it just stop here... How can I solve this problem?
![screenshot](https://cloud.githubusercontent.com/assets/16204743/13697848/43c09190-e7ab-11e5-87b4-3a13f6442fd2.png)

**Comment by ZhuWeiyang** [comment]
Sorry to disturb. I fix the problem myself. Another program injure a module 'xlacc64sp.dll' into node.exe which causes nodejs stop working.

**Comment by lordKnighton** [comment]
:+1: we been pretty busy. Sorry we didn't respond sooner, but i'm glad that you solved it.
