### ISSUE TITLE
Node does not terminate when pipe is terminated

### ISSUE THREAD

**Issue by whitfin** [nodejs/help#1110]
* **Node.js Version**: v8.9.x and v4.8.x (so I assume everything in between, didn't test earlier)
* **OS**: macOS High Sierra
* **Scope (install, code, runtime, meta, other?)**: I guess code/runtime?

I am hitting an issue where a Node program does not terminate when using streams and Unix pipes. To demonstrate what I'm talking about, consider this simple Unix pipeline:

```shell
whitfin:~$ yes | head
y
y
y
y
y
y
y
y
y
y
```

Although `yes` is an infinite stream, it still exits after the first 5 lines are printed because of `SIGPIPE`. However Node.js does not exhibit this behaviour (which is seen as Unix standard, afaik). Here is a reproduction case using a super simple program, with `process.nextTick/1` used to simulate async behaviour.

```javascript
(function log() {
  console.log('tick');
  process.nextTick(log);
})();
```

And the shell session is as follows (I left the `^C` to signal that the session has to be manually killed).

```shell
whitfin:~$ node test.js | head
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
^C
```

The pipe is kept open forever and never exits, even though the passthrough to `head` should actually terminate it. I brought this here first; I think this is a bug but would be nice if anyone more familiar with the Node.js core could inform me otherwise/confirm :)

**Comment by bnoordhuis** [comment]
Node.js blocks SIGPIPE because socket I/O on most platforms is inefficient when it's unblocked.

It's a quirk but I wouldn't call it a bug, more a trade-off.  You can install a listener for it like this: `process.on('SIGPIPE', () => process.exit(141));`

**Comment by gireeshpunathil** [comment]
closing as answered.
