### ISSUE TITLE
node-gyp breaks the program immediately after building

### ISSUE THREAD

**Issue by 6-8-axnw1bom81v5xa3nh48c** [nodejs/help#1112]
* **Node.js Version**: v9.5.0
* **OS**: Windows 8.1
* **Scope**: other
* **<s>Module</s> Tool**: node-gyp

It seems that node-gyp closes batch file from where it is called immediately after building project. For example, consider this batch file:

```bat
node-gyp rebuild
echo Finished
cd ./project
```

String `Finished` is not echoed and cmd doesn't navigate to `project` subdirectory. Basically, everything after calling `node-gyp` is not executed, which means that `node-gyp` closes the batch file. Why? Am I doing something wrong, or is this a bug (or a feature) with node-gyp? How to properly run node-gyp without breaking batch script? Adding `start` command before `node-gyp` works fine, but it is asynchronous. I need to wait for the node-gyp to complete running before batch script can continue, so it must be synchronous, therefore `start` command is not an option.

Thanks.

**Comment by gireeshpunathil** [comment]
I think this is what is happening:


```script
C:\rec>cat first.bat
second
echo " world!"
C:\rec>cat second.bat
echo "hello"

C:\rec>first.bat

C:\rec>second

C:\rec>echo "hello"
"hello"

C:\rec>
```

`first.bat` acts as your script, and `node-gyp` is acting as second. The exit from the second script causes exit from the whole batch.

I don't have enough knowledge on the windows batch specification to assert whether it is working as expected or not, however, this is no quirck with node, as demonstrated.

/cc @nodejs/platform-windows 

invoking node-gyp directly through the script (`node <path to node-gyp.js> rebuild.."`) works fine as there is no second batch script involved here.


Hope this helps.

**Comment by gireeshpunathil** [comment]
I think I got the [info](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490873%28v%3dtechnet.10%29)
```script
C:\>cat first.bat
call second
echo " world!"
C:\>cat second.bat
echo "hello"
C:\>first.bat

C:\>call second

C:\>echo "hello"
"hello"

C:\>echo " world!"
" world!"

C:\>
```

So you would simply need to:
```script
call node-gyp rebuild
echo Finished
cd ./project
```

Hope this helps.

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
Seems that `call` works properly. I didn't know that `node-gyp` is actually a batch file itself. This problem doesn't happen with `exe` files.

Thanks.
