### ISSUE TITLE
Iterating over mongo objects

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1113]
Hi all,

I have a fairly simple question:
All I want is to iterate over an Object that I have stored inside a mongo db. The database is called nodeads. The collection I want, that contains my object, is called userqueries.

```javascript
mongo.connect(url, (err, client) => {
  // Client returned
  var resultArr = [];
  var db = client.db('nodeads');
  const col = db.collection('find');
});
console.log(col);
```

This logs the following:
```javascript
[]Collection {
  s: 
   { pkFactory: 
      { [Function: ObjectID]
        index: 6021363,
        createPk: [Function: createPk],
        createFromTime: [Function: createFromTime],
        createFromHexString: [Function: createFromHexString],
        isValid: [Function: isValid],
        ObjectID: [Circular],
        ObjectId: [Circular] },
     db: 
      Db {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        s: [Object],
        serverConfig: [Getter],
        bufferMaxEntries: [Getter],
        databaseName: [Getter] },
     topology: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 22,
        _maxListeners: Infinity,
        clientInfo: [Object],
        s: [Object] },
     dbName: 'nodeads',

```

But all I want is to iterate over my object, or store it into a variable so I can work with it inside nodeJS. When I try the following:
```
db.collection.find().forEach(function(item){ console.log(item)  });
```
It says TypeError: db.collection.find is not a function... I got this line of code from the Mongo documentation...

I hope somebody can help me.

BTW this is what my collection looks like:

```javascript
{
	"users": {
		"Falco": {
			"userqueries": [
				{
					"Merk": "Audi",
					"Type": "R8",
					"Start URL": "https://www.marktplaats.nl/z/auto-s/audi/r8.html?categoryId=93&attributes=S%2C573&sortBy=price&sortOrder=increasing"

				},
				{
					"Merk": "Audi",
					"Type": "S5",
					"Start URL": "https://www.marktplaats.nl/z/auto-s/audi/particulier-s5.html?categoryId=93&searchOnTitleAndDescription=true&attributes=S%2C10898+S%2C578&startDateFrom=ALWAYS&sortBy=price&sortOrder=increasing"
				}
				]
			}
		}
	},
}

```

**Comment by gireeshpunathil** [comment]
according to the [documentaton](https://docs.mongodb.com/manual/tutorial/query-documents/#select-all-documents-in-a-collection) the code needs to be like:

```js
mongo.connect(url, (err, client) => {
  // Client returned
  var resultArr = [];
  var db = client.db('nodeads');
  const col = db.collection('userqueries');
  console.log(col);
});
```

note that I did not test this.

**Comment by WAINGOR** [comment]
Hi all, I changed the code to 
```
  var resultArr = [];
  var db = client.db('userqueries');
  const col = db.collection('find');
  console.log(col);
```
This logs me the exact same result of my first post in the terminal (I probably made a typo in my app.js, which is the first block of code in my original post) while typing my post.

What I want is simple: In my collection called userqueries you can see a key (also called userqueries) with an array filled with objects, as a value. 

**I want to get this array out of the database and assign it to a variable** that I can further manipulate inside my code.

**Comment by MidnightP** [comment]
```db.collection``` is a function that can return you a reference to a MongoDB collection. It takes one argument, like so:

```const userqueriesCollection = db.collection("userqueries")```.

Once you have the collection you can use the ```.find``` function on it, like so:

```const resultArr = userqueriesCollection.find()```

That should get you going.

In any case, this question does in my opinion not at all concern Node.js. It is actually just MongoDB troubleshooting. Stackoverflow is a great place for that, e.g. with questions like "How to find all documents in a collection?"

**Comment by gireeshpunathil** [comment]
@WAINGOR - I think you are making the same mistake again, and hence the same wrong result.

try:

```js
var db = client.db('nodeads');
const col = db.collection('userqueries');
```

instead of:

```js
var db = client.db('userqueries');
const col = db.collection('find');
```

**Comment by gireeshpunathil** [comment]
ping @WAINGOR

**Comment by WAINGOR** [comment]
Oops :) Its working now, thank you for your help @gireeshpunathil
