### ISSUE TITLE
Cannot download image using `http.get`

### ISSUE THREAD

**Issue by jsdeveloper97** [nodejs/help#1114]
* **Node.js Version**: v9.5.0
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http

I want to download image from this url:

```
http://bsnscb.com/data/out/18/38675461-beautiful-road-wallpapers.jpg
```

but node.js doesn't downloading it properly. It dont throw errors but it says content-length 0 bytes. I properly can open the image in browsers but in Node.js it doesnt working.

Here is my code, can someone tell me what I am doing wrong:

```js
var http = require('http');

var url = 'http://bsnscb.com/data/out/18/38675461-beautiful-road-wallpapers.jpg';

http.get(url, res => {
  console.log(res.headers['content-length']); // ---> 0 ???
  // create fs stream, pipe `res` to it, blah blah, similar stuff here
});
```

Probably browser sends some headers by default and website properly displays image in browser, but in node.js it doesn't work. I am pretty sure i need to send some headers, but which ones? How to force the website to send image properly?

Here is screenshot how it looks in my browser: [screenshot](https://github.com/jsdeveloper97/javascript/blob/master/1.zip?raw=true).

Thanks a lot hope someone can help

**Comment by devsnek** [comment]
the server is responding with a redirect:
![](https://gc.gy/B♢ɭ.png)

**Comment by jsdeveloper97** [comment]
@devsnek Thanks for fast reply!

I already know it is a redirect code, I checked it in `res.statusCode === 301` and it was true. But, since this is help repo I am wondering why does the image displays properly in a browser (in browser status code is 200 and image is sent properly), but when I try using node.js it send status code 301 and redirects me to their gallery?

Maybe it is worth mentioning, in browser if I try to open link directly (paste it in omnibox), then website redirects me to the same page like in node.js. Only if I navigate to the image url from the website's gallery, then it works. But if I copy link and paste in another tab, it redirects me/ Why?

So, I am assuming the website probably checks what was the url address where I was before, and if it is not some of gallery websites, then it redirects me to gallery. Am I right? If yes, what headers are responsible for it and how can I manage to set those headers properly in order to download image from node? If I am not right, then what is actually going on here?

sorry for bad english

**Comment by devsnek** [comment]
> So, I am assuming the website probably checks what was the url address where I was before, and if it is not some of gallery websites, then it redirects me to gallery.

that seems correct. i'm not going to personally investigate but its most likely the referrer header or a cookie.

**Comment by jsdeveloper97** [comment]
I figured it out finally. I had thought it was a cookie, but I tried clearing and blocking cookies in Chrome but it still displays image, so it means it must be header. And yes, you are right, it is exactly `referer` header, I had no idea it even exists

This code works fine

```js
http.get({
  host: 'bsnscb.com',
  path: '/data/out/18/38675461-beautiful-road-wallpapers.jpg',
  headers: {
    ['Referer']: 'http://bsnscb.com/beautiful-road-wallpapers/38675461.html',
  },
}, res => {
  res.pipe(require('fs').createWriteStream('./1.jpg'));
});
```

thanks for helping and pointing to right direction.
