### ISSUE TITLE
Should I (or am I required to) use uv_mutex_t?

### ISSUE THREAD

**Issue by JoshuaWise** [nodejs/help#112]
While creating asynchronous c++ addons for Node.js, I understand that Node (or, libuv, I suppose) provides the `uv_mutex_t` object for preventing data corruption while multiple threads access the same memory.

I'm building an addon that uses the [sqlite3 C API](http://www.sqlite.org/capi3ref.html), which comes with their own mutex implementation called [`sqlite3_mutex `](http://www.sqlite.org/capi3ref.html#sqlite3_mutex_alloc).

I was wondering if I'm required to use the libuv mutex, or if it doesn't matter? I haven't worked in multithreaded environments very much, so I'm not aware of what kinds of responsibilities mutexes have, or if they're all pretty much the same. Is there a preference or "best practice" in this case?

Should I use one over the other?

**Comment by bnoordhuis** [comment]
It's optional.  If sqlite3 provides its own cross-platform mutex implementation, it's fine to use that.  That's what libuv's `uv_mutex_t` is, a (very thin) abstraction over native mutexes.

**Comment by JoshuaWise** [comment]
Great, thanks!
