### ISSUE TITLE
HTTPS.request() - Usage of clientCertEngine 

### ISSUE THREAD

**Issue by pavanravuri** [nodejs/help#1120]
* **Node.js Version**:9.5.0
* **OS**:Linux
* **Scope (install, code, runtime, meta, other?)**: HTTPS
* **Module (and version) (if relevant)**: HTTPS

I am using HTTPS.request.
I have customised SSL engine which will take care of loading certificates from specified path.
I am wondering if I can use "clientCertEngine" to specify my engine to be used.

**Present Code:**

const options = {
  hostname: 'encrypted.google.com',
  port: 443,
  path: '/',
  method: 'GET',
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};
options.agent = new https.Agent(options);

const req = https.request(options, (res) => {
  // ...
});

**New code I want to be:**

const options = {
  hostname: 'encrypted.google.com',
  port: 443,
  path: '/',
  method: 'GET',
  **clientCertEngine: myCustomizedEngine**
};
options.agent = new https.Agent(options);

const req = https.request(options, (res) => {
  // ...
});

Will it give me intended result ?

**Comment by pavanravuri** [comment]
Facing below error when tried setting:

:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:

**Comment by pavanravuri** [comment]
When absolute path to engine is provided, node crashed

**Comment by nigelhanlon** [comment]
The `clientCertEngine` parameter does not take a path, but rather a string representing the name of the engine you wish to use in OpenSSL. 

From https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options:
```
clientCertEngine <string> 
Optional name of an OpenSSL engine which can provide the client certificate.
```

My suggestion would be to test your engine and its configuration using the command line `openssl` tool to verify it works as expected. For reference, the OpenSSL Engine readme can be found [here](https://github.com/openssl/openssl/blob/master/README.ENGINE). 

It is hard to know right now if it is indeed a Node.js issue or a problem loading shared libraries for your engine of choice. 

Hope this helps.

**Comment by gireeshpunathil** [comment]
@pavanravuri - is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding.
