### ISSUE TITLE
Specify custom engine to be loaded using openssl.cnf

### ISSUE THREAD

**Issue by pavanravuri** [nodejs/help#1121]
* **Node.js Version**: 9.5.0
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: SSL
* **Module (and version) (if relevant)**: SSL

Is there a way where I can:
set path of "--openssl-config" to load openssl.cnf and
specify engine to be loaded in openssl.cnf

**Comment by nigelhanlon** [comment]
As far as I can tell, using the command line switch `--openssl-config` is the only way to achieve this. It allows you to specify an OpenSSL configuration file and is documented [here](https://nodejs.org/api/cli.html#cli_openssl_config_file). In the OpenSSL config file you should be able to set whatever parameters you need. More information on the configuration file can be found [here](https://www.openssl.org/docs/manmaster/man5/config.html) including details about the `engines` you mentioned.

**Comment by gireeshpunathil** [comment]
@pavanravuri - is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding, thanks!
