### ISSUE TITLE
Problem running Ionic offline with NodeJs 8.9.4

### ISSUE THREAD

**Issue by bhekor** [nodejs/help#1129]
* **Node.js 8.9.4 (x64)**:
* **Windows 10**:
* **Ionic CLI 3.19.1**:

Hi guys, am having problem running my ionic app offline using the:  `ionic serve` or the `ionic serve --lab`. The app runs the first time but when a file changes instead of reloading/rebuilding the app I got this.

### Here is the error am getting: 
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn "C:\Program Files\nodejs\node.exe" ENOENT
    at notFoundError (C:\Users\Learn\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\Learn\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\Learn\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
Please help me with this I really need to be able to  run and test my app offline

**Comment by gireeshpunathil** [comment]
the call stack is an evidence of node binary in execution, but the spawn failure would indicate a possible issue with the options passed to the custom launcher - cross-spawn. So I don't see any evidence of an issue with node, instead with the module(s). Looks like there are similar issues reported against ionic, please  you may track the progress there: https://github.com/ionic-team/ionic-cli/issues/2866

**Comment by bhekor** [comment]
Thanks, I will check that out.

**Comment by gireeshpunathil** [comment]
Closing it, please re-open if this turns out to be a node issue

**Comment by bhekor** [comment]
Please, I'm still having the issue
