### ISSUE TITLE
No SHASUM256.txt file

### ISSUE THREAD

**Issue by ndclinite** [nodejs/help#113]
I've downloaded v4.4.0 LTS for my Ubuntu x64 box, and extracted the directory node-v4.4.0-linux-x64.  The README.md says "Stable, LTS and Nightly download directories all contain a *SHASUM256.txt* file that lists the SHA checksums for each file available for download."  However, `find -iname "*shasum*"` returns nothing.  How am I supposed to verify my download?

**Comment by bnoordhuis** [comment]
You can download the file from [here](https://nodejs.org/dist/v4.4.0/SHASUMS256.txt) or [here](https://nodejs.org/dist/v4.4.0/SHASUMS256.txt.asc).  The second file is signed with a GPG key from the release team.
