### ISSUE TITLE
Using NPM hook after `npm install x`

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1130]
This applies to all Node.js versions > 6.0.0 and all OS.

https://stackoverflow.com/questions/48983841/run-postinstall-hook-for-any-local-dependency

I am looking for an answer to that question. I have some library code, and I am looking for a built-in hook that I can use after an `npm install` command runs. 

A "postinstall" hook runs after `npm install`
but I am looking for a hook that runs after `npm install x` too.

**Comment by gireeshpunathil** [comment]
a question to https://github.com/npm/npm ?

**Comment by ORESoftware** [comment]
https://github.com/npm/npm/issues/19921

**Comment by gireeshpunathil** [comment]
so closing here!

**Comment by ORESoftware** [comment]
ok np thx
