### ISSUE TITLE
feature request: register custom encodings

### ISSUE THREAD

**Issue by FranckFreiburger** [nodejs/help#1133]
* **Node.js Version**: latest
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: any

Currently, node.js support multiple encodings: ascii, base64, binary, hex, ucs2/ucs-2/utf16le/utf-16le, utf8/utf-8, latin1 (ISO8859-1, only in node 6.4.0+)

I wondering if it is possible give a mean to register new custom encoding (eg. base85, base64-url, ...)

(I hope this is the right place for feature requests)

**Comment by addaleax** [comment]
What would “registering” a new encoding mean? Node is still not going to be able to encode/decode for those, right…?

**Comment by FranckFreiburger** [comment]
The idea is to provide new encodings with encode/decode functions.

```js
encoding.register('base85', {
  encode(buffer) {
    return encode_buffer_to_base85(buffer);
  }, 
  decode(data) {
    return decode_base85_data_to_buffer(buffer);
  }
);
```

**Comment by gireeshpunathil** [comment]
the current design of Buffer implementation has no tight binding with an `encoding` attribute - instead   user passes the required encoding for creation of a buffer object and subsequent operations on it, independent of each other.

While the proposal looks cool from design perspective, its implementation in the existing codebase may have challenges, and may invite performance implications in the sensitive area of code.

/cc @nodejs/buffer for opinion.

**Comment by seishun** [comment]
This was discussed and rejected before: https://github.com/nodejs/node/issues/2835

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding and you have specific suggestions that addresses concerns from https://github.com/nodejs/node/issues/2835
