### ISSUE TITLE
sublime warning when open a js file

### ISSUE THREAD

**Issue by Yuriuh** [nodejs/help#1136]
* **Node.js Version**:v8.9.3
* **OS**:windows 10
* **Scope (install, code, runtime, meta, other?)**:runtime
* **Module (and version) (if relevant)**:

<img width="960" alt="stwarning" src="https://user-images.githubusercontent.com/33216220/36933682-3bf4bf9e-1f18-11e8-9f50-93f158958c8f.png">

Just like the image above,  sublime text report 3 warnings when I open a js file. I don't know how to solve this problem. I‘ve installed the SublimeText-Nodejs plug-in module.

**Comment by gireeshpunathil** [comment]
@Yuriuh - you can trace the source of the usage of deprecated APIs using `--trace-deprecation` in the environment which goes into the submlime build script.

```json
{
  "cmd": ["/usr/local/bin/node", "$file"],
  "selector": "source.js",
  "encoding": "cp1252",
  "env": {
  	"NODE_OPTIONS":"--trace-deprecation"
  }
}
```

Additionally export `NODE_PENDING_DEPRECATION` to `1` too to catch pending deprecations.

If your code is making use of the deprecated APIs, you may refer to the API documentation and identify the alternatives. [here](https://nodejs.org/dist/v8.9.3/docs/api/) is `.8.9.3` doc.

Hope this helps.

**Comment by Yuriuh** [comment]
Thanks a lot~

**Comment by gireeshpunathil** [comment]
sure! Assuming that you got it resolved, so closing. Please let me know if that is not the case.

**Comment by Yuriuh** [comment]
Yes, I've solved it, I use the vscode instead, and vscode's more suitable to write js file.
