### ISSUE TITLE
How may I help?

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/help#1137]
Hey everyone!
I am a junior developer and wanted to get involved and contribute. That said, I'd definitely need some assistance finding my way for the first few days. If you're working on the project and could use some help, please let me know how I may join in.

**Comment by gireeshpunathil** [comment]
@ryzokuken - wish you a great experience with node.js.

You can start by looking through [good-first-issues](
https://github.com/nodejs/node/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and [mentor-available](
https://github.com/nodejs/node/issues?q=is%3Aissue+is%3Aopen+label%3Amentor-available).

and pick choose one or two of your choice, and start hacking. Let others know you are working on it.

A low hanging PR for you for a starter: fix the typo in this [line](https://github.com/nodejs/node/blob/452eed956ef451965344cf29f61e2ab434cea9df/lib/buffer.js#L740)

**Comment by ryzokuken** [comment]
Thanks, @gireeshpunathil! I'll jump in right away.

I see the line says:
```js
// - encoding - an optional encoding, relevant is val is a string
```
I had been wondering what the appropriate sentence would be. I know that encoding is an "optional encoding value which expects type String". It should probably default to UTF-8. What exactly should I mention, though?

**Comment by gireeshpunathil** [comment]
~relevant is val is a string~
relevant if val is a string
:)

**Comment by ryzokuken** [comment]
Great! I'll make that change and submit a PR.

**Comment by ryzokuken** [comment]
@gireeshpunathil I should make the change against the `10.0.0-proposal` branch, right?

**Comment by devsnek** [comment]
@ryzokuken target the master branch. when we're creating releases backports will target versioned branches but thats about the only reason

**Comment by ryzokuken** [comment]
@devsnek so for the record, I make a branch off the `10.0.0-proposal` branch, make my changes and make the PR against *not* the `10.0.0-proposal` branch, but the `master` branch instead.

**Comment by gireeshpunathil** [comment]
please follow the `Pull Requests` section in [contributor's guide](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md) - that is comprehensive.

**Comment by ryzokuken** [comment]
@gireeshpunathil that's what I had been looking into, and got confused.

The guide says: As a best practice to keep your development environment as organized as possible, create local branches to work within. These should also be created directly off of the `master` branch.

However, I don't think the commit has landed in `master` yet.

**Comment by ryzokuken** [comment]
Wait, it has. That helps.

**Comment by ryzokuken** [comment]
@gireeshpunathil @devsnek I submitted the PR! Here it is: https://github.com/nodejs/node/pull/19126

**Comment by gireeshpunathil** [comment]
The purpose is met, closing.
