### ISSUE TITLE
How I can run node.js and angular 2 on different ports ? I want to do saml authentication and protect api

### ISSUE THREAD

**Issue by tusharbudhe0302** [nodejs/help#1139]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by gireeshpunathil** [comment]
please be descriptive - what you are trying to solve, and what problem you encountered?

**Comment by tusharbudhe0302** [comment]
Thanks @gireeshpunathil . I am able to resolve this. I have keep passport saml angularjs ruuiing on node instance. In call back I am doing post to my api which returns a token. It's working fine for me. I willl share my code Once I will done with it.

**Comment by gireeshpunathil** [comment]
thanks @tusharbudhe0302 . I will close this out then, please don't hesitate to highlight any insights you may want to share with others.
