### ISSUE TITLE
node app as service

### ISSUE THREAD

**Issue by mh-cbon** [nodejs/help#114]
Hi,

I m digging to find the right way to setup and initialize a node server as a service on various platform.
A friendly, simple and automated way which does not involve a sysadmin operator to realize it.

As always, there s a bunch of module available in the wild, with more or less good tests, integration, support, maintenance. 
Some clearly tries to achieve the goal, some does far more, some are limited to fix a part of the problem only.

I m mainly talking about all those great modules,
- https://github.com/foreverjs/forever
- https://github.com/coreybutler/node-linux
- https://github.com/Unitech/pm2

If i d go through each and tries to summarize their abilities, correct me if i m wrong,

- https://github.com/foreverjs/forever
Manages the problem of keeping an app up, but does not provide automated way to install forever itself as a service, nor registering, unregistering app. We are left with half of the solution.

- pm2
Does a lot of thing, way too much for a service system installer. It embed its own [service setup scripts](https://github.com/Unitech/pm2/tree/master/lib/scripts), with limited support, see [windows](https://www.npmjs.com/package/pm2-windows-service)

- https://github.com/coreybutler/node-linux
Is the one which tries to address the problem with the most accuracy by providing programmatic api to install, uninstall ect services on the major OSes available (windows, mac os, linux). But the project clearly has governance issues, and maintenance difficulties by the lack of support of the creator. Also its a pity, it does not have any automated tests suite built on top of vagrant boxes to ensure its integrity.

I m wondering 
- if this support will be normalized someday by __a__ community (this place may be the wrong one),
- if there are interests about that
- if i miss some newer initiatives / modules to solve this
- if there are chances to make this right in near future

I d be happy to hear your thoughts, if any, and i hope this won t be misunderstood as free criticism which is not my intent. I m rather trying to evaluate my current options to move on my next steps to solve my own needs.

**Comment by lordKnighton** [comment]
If I'm honest: https://gitter.im/nodejs/node that is the better place to ask that question.

**Comment by lordKnighton** [comment]
@mh-cbon how is it going with this?

**Comment by mh-cbon** [comment]
I started to dig more specifically solutions per system, i found that strongloop provides something really nice and cool
https://github.com/strongloop/strong-service-upstart
https://github.com/strongloop/strong-service-systemd
https://github.com/strongloop/strong-service-install

I feel it is not satisfactory, for few preliminary reasons,
- it s not smart, it needs to provide the init system and version on the command line
- it s root only, systemd has its cool feature to let us install a service into userland home
- it does not support other oses
- it s a bit monolithic

I need to dig it more, and decide how the functionality to be provided. I think i ll go for an automated system when possible, and fallback on user input (inquirer) when details are missing.

The immediate job is to gather information about how other oses works, then the coding job can be started, i dont think it s going to be very difficult, but i m sure there s going to be numerous module to init, code, release.

**Comment by lordKnighton** [comment]
https://blog.risingstack.com/continuous-deployment-of-node-js-applications/ I'm reading this.

**Comment by mh-cbon** [comment]
yup that s the ideal workflow i d like to implement. I only need to make it real with a matrix of multiple operating systems types * multiple oses versions * multiple node versions.
There should be something out there to help me on that matter (way more than nvm).
The thing is as i don t have a battery of servers available, the time to run will be very, very, long. Unless, i try to use travis to spawn vagrant boxes, it that works, i m not sure they ll be happy with that.
This is probably the most tricky point as it is not only a matter of quality of coding, but a matter of material ($$$).

I ll try to summarize things tbd.

**Comment by lordKnighton** [comment]
Hey how's it going with this?

**Comment by subfuzion** [comment]
@mh-cbon If you're thinking through all of this as an academic issue and because you enjoy it, that's great. Generally all the choices you just mentioned will be influenced by your existing init philosophy, distro and version, and maybe other factors. I suggest you just use forever with the init system you're already using (such as upstart), make sure you have a monitoring solution in place for production, be done with it, and focus on getting other tasks done! No need for paralysis by analysis.  If you find a limitation to this approach, then investigate the next alternative with a bit more data under your belt. Good luck!

**Comment by mh-cbon** [comment]
@subfuzion  Hi, thanks for advice. yeah agreed when you say to not stay stuck while doing analysis. This said, a bit of pre engineering to do the right choice worth at the end. For example, it would have been great that node-linux is a plug able system, instead of this monolithic project.

This said, at that very moment i have been struggling while virtualizing windows to implement testing via its scripting capabilities (i m having epic debate about powershell since this news window's bash came out yesterday).
I m still having lots of difficulties here to test windows 7/8/10, and more if possible. Mainly a problem about building/finding workable boxes.

I m slowly moving on to macos now (images are 10 to 13gb each..). I ll keep moving on for linux-friendly oses.

An important remark, i won t use forever or pm2 ect, the goal is to provide pieces to integrate with per system services management in an automated fashion for non enterprise level use cases.
/If you want to use pm2, you still need to set it up itself as a service of the system, afaik/
If you are a company i m afraid this project won t be the definitive answer to your need, the options, use cases and possibilities are so numerous that it will complexify the project too much, and kill it.
Which i want not. Finding the middle way would be a great thing.

Last word, let s be pragmatic and provide small, re usable, focused and functional module to solve every needed functionality one after the other. So that at worst, it will still remains workable modules for future attempts or whatever else needs to be solved.

If one is passing here to find quick answers, quick modules, ready to go, you can take look to my screening of existing modules https://github.com/mh-cbon/problems-and-solutions/tree/master/system-services 

hth

**Comment by mh-cbon** [comment]
It starts to show up, 
- https://github.com/mh-cbon/launchd-simple-api
- https://github.com/mh-cbon/sc-simple-api
- https://github.com/mh-cbon/upstart-simple-api
- https://github.com/mh-cbon/systemd-simple-api

It was not always [straight forward](https://github.com/mh-cbon/has-sc/blob/master/index.js)

- It needs more boxes (windows / mac) to enhance the testing via vagrant. For example, I have not been able to work with https://atlas.hashicorp.com/opentable/boxes/win-7-professional-amd64-nocm or https://atlas.hashicorp.com/boxes/search?utf8=%E2%9C%93&sort=&provider=&q=capitan. Support from an experienced sysadmin would be warmly welcome.
- It needs a super module to automagically install the service whatever is the underlying OS
- this super module should probably provide a way to override default service definition in order to re install with customs settings, something that needs to be thought
- It s missing a sysvinit, openrc, runinit support

I m also looking for a cool module to perform sudo command with password prompt support, the [one](https://github.com/calmh/node-sudo) i found seems not so good, to me.

**Comment by mh-cbon** [comment]
Two problems solved,
- Fix opentable windows vagrant box http://digitaldrummerj.me/vagrant-fixing-opentable-basebox/
- a better sudo command https://github.com/mh-cbon/yasudo

BTW, a better module to support windows elevated command https://github.com/mh-cbon/aghfabsowecwn

**Comment by lordKnighton** [comment]
closing for now, reopen to pursue 

happy coding 😃
