### ISSUE TITLE
node.js memory consumption, in megabytes?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1140]
I am graphing Node.js memory overtime, using `process.memoryUsage()`.
I push the values from that call, onto an array and that graph rss, heapTotal, heapUsed, like so:

<img width="597" alt="screenshot 2018-03-05 17 36 04" src="https://user-images.githubusercontent.com/11139560/37009447-d74aa470-209b-11e8-8a2c-6c70e1694c04.png">

However, my question is, are those values measured in megabytes? It seems like it, but I can't be sure..with RSS at almost 38,000 MB, that would be almost 4GBs, I didn't know Node.js processes would be automatically allocated that much memory from the start..

@bnoordhuis hopefully you can help thanks

**Comment by ORESoftware** [comment]
Looks like to get the correct memory amount is like so:

```js
const used = process.memoryUsage().heapUsed / 1024 / 1024;
// used is now in MB, correct?
```

**Comment by gireeshpunathil** [comment]
The `process.memoryUsage()` method returns an object describing the memory usage of the Node.js process measured in [bytes.](https://nodejs.org/dist/latest-v9.x/docs/api/process.html#process_process_memoryusage)

**Comment by ORESoftware** [comment]
yeah, I guess I don't remember the difference between:

`const used = process.memoryUsage().heapUsed / (1000 * 1000);
`
and

`const used = process.memoryUsage().heapUsed / (1000 * 1000);
`

**Comment by gireeshpunathil** [comment]
sorry - I did not get you - both lines are same!

**Comment by ORESoftware** [comment]
ughh sorry I just fixed that!

**Comment by SomeoneWeird** [comment]
`1024` bytes is `1024` kilobytes
`1024` kilobytes is `1` megabyte
`1024` metabytes is `1` gigabyte

If you want to get the value in Megabytes, you need to use `1024` and not `1000`

**Comment by gireeshpunathil** [comment]
closing then, thanks.

**Comment by samuelkilada** [comment]
Using the rss property seems to give a number which actually reflects what I see in the Windows Resource Monitor:

`process.memoryUsage().rss / (1024 * 1024)`

**Comment by lucascriado** [comment]
@ORESoftware what software/website did you use to make this graph?
