### ISSUE TITLE
App freezes on mobile devices

### ISSUE THREAD

**Issue by sebastianks** [nodejs/help#1143]
* **Node.js Version**: 6.x
* **OS**: Ubuntu
* **Scope (install, code, runtime, meta, other?)**: runtime

I've created an eCommerce solution with Nuxt (Vue framework) and by that, a nodejs app. The app runs on desktop, but as soon as I try to enter the site from a mobile device the app loads, but then when clicking a link, the whole app freezes, and if you wait long enough, the whole browser freezes, and you have to close the browser app and open it again.

I know it's kind of hard to help debugging without any code or examples, but I have no idea of what I should post as code, as it's only happening on mobile devices.

Have anyone tried this, or maybe have an idea why it's only freezing on mobile devices?

**Comment by nigelhanlon** [comment]
It is very difficult to know what exactly is causing the issue without knowing more about the application and the architecture. It might be worth creating a new issue on the Nuxt Github [here](https://github.com/nuxt/nuxt.js/issues) as it may be Nuxt specific. 

You should be able to remotely debug the mobile device's browser using [Web inspector on Safari ](https://appletoolbox.com/2014/05/use-web-inspector-debug-mobile-safari/)(assuming you have a Mac) or using the Google equivalent [here](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/). With remote debugging you will be able to access the web console to find any additional errors you might not have seen previously.

If you find a specific Node.js error be sure to follow up here 👍

**Comment by sebastianks** [comment]
Hello @nigelhanlon 

Thank you for your reply. I've thought of the remote debugging, but the thing is, I have a Surface Book and an iPhone X. How do I debug this? The Google debugger seems like it's for Android devices.

I can't find any straightforward way of debugging an iOS device on a Window machine.

**Comment by nigelhanlon** [comment]
Debugging iOS on Windows is far from straightforward, but there are tools available. If you use Visual Studio Code, you might find the following useful: 

https://code.visualstudio.com/blogs/2016/08/22/introducing-ios-web-debugging-for-vs-code-on-windows-and-mac

You can also try the RemoteDebug iOS WebKit Adapter which you can find here:  https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter

These might help, but I haven't used them myself. Other people might have more suggestions.

**Comment by sebastianks** [comment]
Thank you.

I might try Det RemoteDebug. The first one is deprecated, and they recommend RemoteDebug. I might get an Android phone instead tho ;-)

**Comment by gireeshpunathil** [comment]
ping @sebastianks

**Comment by sebastianks** [comment]
Hello

Actually I found out, that I had a middleware on every pageload that, for some reason, made my App freeze. I'm pretty sure it wasn't a Nodejs issue, so I'm closing this now.
