### ISSUE TITLE
Download a JPEG file from a remote source?

### ISSUE THREAD

**Issue by cquillen2003** [nodejs/help#1144]
Node.js Version: 9.3.0
OS: macOS
Scope: Runtime
Module: node-bandwidth v2.6.2

I am trying to download a JPEG from a remote source and save it to my server.  It seems to work, but when I try to access the JPEG on my server, the image renders as a black screen or I get an error.

Am I missing a processing or encoding step to get the raw JPEG data?

Here is the API for the method I am using:
http://dev.bandwidth.com/node-bandwidth/Media.html#download

```js
//Bandwidth is a Twilio-like service for sending/receiving SMS/MMS messages
import Bandwidth from 'node-bandwidth';
import axios from 'axios';

var client = new Bandwidth(myAPICredentials);

async function() {
    //Fetch image from MMS message in Bandwidth
    var res1 = await client.Media.download('my-mms-image.jpg');

    //Bandwidth docs say res1.content is type String | Buffer | Readable
    //Do I need to process or encode the data somehow here???
    
    //Save image to my server
    var res2 = await axios.post(serverUrl, res1.content);
}
```

**Comment by gireeshpunathil** [comment]
ideally you should be posting this question to https://github.com/Bandwidth/node-bandwidth/issues 

but looking at their [download logic](https://github.com/Bandwidth/node-bandwidth/blob/21a7b32c240f5e9f5229ce868630ee66c556f7ad/lib/media.js#L84-L94) I guess you got your data in a binary buffer. So:
 - before sending it to server you could try opening it and see if stage 1 is good
 - try axios.post(serverUrl, res1.content, {responseType:arraybuffer}) or whatever type axios.post is accepting for binary data.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still not working.
