### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by markfilipak** [nodejs/help#1145]
Where can I find nodejs documentation? Especially, methods of the global object.

I wrote this:
`var FileSysObj = require('fs');
console.log('=== THIS PROGRAM ===');
console.log(FileSysObj.readFileSync(filespec=__filename, encoding='utf8'));
console.log('=== END ===');
console.log('=== PROPERTIES OF fs OBJECT ===');
console.log(FileSysObj);
console.log('=== END ===');
console.log('=== PROPERTIES OF this OBJECT ===');
console.log(this);
console.log('=== END ===');`
and it works, but I'm not going to get further without documentation.

Warm Regards,
Mark.

**Comment by markfilipak** [comment]
Also...

Is there some way to turn off the rich text here so I can post plain text?

**Comment by devsnek** [comment]
> Where can I find nodejs documentation? Especially, methods of the global object.

https://nodejs.org/api/ has all our documentation

> Is there some way to turn off the rich text here so I can post plain text?

if you surround your code in three backticks instead of one you'll get a proper codeblock:
<pre>
```
some code
```
</pre>

becomes
```
some code
```

**Comment by gireeshpunathil** [comment]
closing as answered.
