### ISSUE TITLE
Sending a another wrapped object from native addon function

### ISSUE THREAD

**Issue by jay11ca39** [nodejs/help#1146]
Hello All,
I am writing native addon for my CPP library.
I have 2 classes:

```c++
  class A : public Nan::ObjectWrap
    {
        public:
            static void Init(v8::Local<v8::Object> exports);
            virtual ~A();

        private:
            static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);

             ...................other methods.................

            static Nan::Persistent<v8::Function> constructor;
    };
  class B : public Nan::ObjectWrap
    {
        public:
            static void Init(v8::Local<v8::Object> exports);
            virtual ~B();

        private:
            static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);
            static void GetAObj(const Nan::FunctionCallbackInfo<v8::Value>& info);
           
             ...................other methods.................

            static Nan::Persistent<v8::Function> constructor;
    };
```
In class B there is a method: GetAObj , in this method i want to return a Class A object to javascript and from javascript I want to use that A class object to make function call of class A.

Can anybody help me out in defining GetAObj method of class B ?

* **Node.js Version**: v8.9.4
* **OS**: Linux 64-bit [Ubuntu 14.04]

Thanks in advance.

_mod EDIT:ofrobots:fixed formatting_

**Comment by gireeshpunathil** [comment]
@jay11ca39 - I guess your #1171 is covering this issue as well? Please confirm. If so, I will close this out. Please let me know.

**Comment by jay11ca39** [comment]
@gireeshpunathil ,
Sorry for multiple issues. Quite new to NAN and nodejs addons. :)
Thanks for your support. You can close this issue.

**Comment by gireeshpunathil** [comment]
closing this in favor of #1171 , cheers!
