### ISSUE TITLE
serialport node gone?

### ISSUE THREAD

**Issue by Alfemann** [nodejs/help#1147]
* **Node.js Version**: 9.8.0 and any after 4.8.7 basically
* **OS**: Ubuntu 16.04
* **Scope (install, code, runtime, meta, other?)**: Missing node after upgrade
* **Module (and version) (if relevant)**: node-red-node-serialport 

After upgrading nodejs the Serial node is gone from my palette.
By downgrading and upgrading, I found that the last version that will show the serial node is 4.8.7 - anything after that - and the serial node goes away. No amount if re-installing just the node will make it reappear....

**Comment by Alfemann** [comment]
I have a working and running node-red installation  on 2 Ubuntu PCs running 16.04 and the latest 17.X Ubuntu.
On the machine with ubuntu 17.X - That OS was installed from scratch, and I just looked at the palette and the serial node was not there.

The 16.04 machine is a little more frankenstein - I had to install an earlier version of the os, and upgrade.
After having the fresh install with working Node-red, I saw that the serial port was there.
Due to a need for a specific function, I had to upgrade node-red to fix a bug in that function.
After the upgrade - the serial node was gone.

So I played around with it, and I have come to the conclusion that the serial port will be there as long as you stick to version 4.X. If I upgrade to 5 or higher - the serial port node disappears from the palette. Weird...


Mvh
Alf Møllerud (+47 93267132)

**Comment by gireeshpunathil** [comment]
Unable to recreate when I tried in mac:

```
Welcome to Node-RED
===================

15 Mar 16:28:36 - [info] Node-RED version: v0.18.4
15 Mar 16:28:36 - [info] Node.js  version: v6.11.2
15 Mar 16:28:36 - [info] Darwin 16.7.0 x64 LE
15 Mar 16:28:36 - [info] Loading palette nodes
...
Server now running at http://127.0.0.1:1880/
```
<img width="579" alt="screen shot 2018-03-15 at 4 31 50 pm" src="https://user-images.githubusercontent.com/6447530/37459629-b248e530-286e-11e8-80ba-42a2985a030a.png">


I guess you should take it up with node-red to see if they don't support `node-red-node-serialport` with higher versions of node.

**Comment by Alfemann** [comment]
Thanks.

Mvh
Alf Møllerud (+47 93267132)

**Comment by gireeshpunathil** [comment]
closing then, thanks!
