### ISSUE TITLE
Inspector not available in 9.x.x?

### ISSUE THREAD

**Issue by zGrav** [nodejs/help#1149]
* **Node.js Version**: 9.8.0
* **OS**: macOS 10.13.2 17C88 x86_64 (High Sierra)
* **Scope (install, code, runtime, meta, other?)**: runtime/other?
* **Module (and version) (if relevant)**: inspector

```js
const inspector = require('inspector');
```

Can't seem to require the v8-inspector anymore, is there a new way of importing it in v9?

Yes, I know I can do --inspect, but I'm trying to build a module that enables inspector programatically.

**Comment by gireeshpunathil** [comment]
```
#node -v
v9.8.0
#node
> const inspector = require('inspector');
undefined
> inspector
{ open: [Function: open],
  close: [Function: _debugEnd],
  url: [Function: url],
  Session: [Function: Session] }
> 
```

**Comment by zGrav** [comment]
interesting, so it changed it seems, no longer able to import on the fly 🤔

**Comment by bnoordhuis** [comment]
Closing, looks like this has been answered.

**Comment by bnoordhuis** [comment]
Oh, I thought this was nodejs/node (email ended up in the wrong folder.)  I'll reopen.

**Comment by gireeshpunathil** [comment]
@zGrav: sorry, but I am unable to follow your last statement.

 - do you mean to say this is not working on the master / latest release?
 - importing on the fly - do you allude to any other semantic than what I used (REPL)? Like deep inside the code under some conditionals?

**Comment by zGrav** [comment]
@gireeshpunathil what I mean is with v9 trying to require inspector returns undefined as stated above and works just fine in v8. I wanted to replicate this exact behavior.

**Comment by gireeshpunathil** [comment]
ah! ok. `undefined` is the return value of the whole expression, not the return value of the require statement. That is a known and ratified REPL behavior.

You can go ahead with importing `inspector`, there are API changes and differences between v8.x and v9.x, but your stated requirement is possible, if you face specific issues while programatic invocation of the inspector, let me know

**Comment by zGrav** [comment]
Understandable, seems to be working now actually. thanks for the help!
