### ISSUE TITLE
Npm is not install - npm ERR! code ECONNRESET npm ERR! errno ECONNRESET.

### ISSUE THREAD

**Issue by magdalena-dering** [nodejs/help#1152]
* **Node.js Version**: v9.8.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

Hi, 
I can't install npm. I have updated my node.js and then I wanted to write a command 'npm install', but terminal got me info:
```λ npm install
npm WARN css-grid@1.0.0 No repository field.

npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/browser-sync/-/browser-sync-2.18.13.tgz failed, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Magdalena\AppData\Roaming\npm-cache\_logs\2018-03-10T19_38_27_555Z-debug.log


I run to the following path but I don't know what should I change there. 
Thank in advance for your help.

**Comment by gireeshpunathil** [comment]
are you accessing within your organization's firewall? If so, please see how to setup `npm proxy` configuration by following this [link](https://docs.npmjs.com/misc/config)

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still not working.

**Comment by nashents** [comment]
Also came across such errors but i noticed i was getting these errors when i try to execute commands from an embedded terminal using Vs Code but if try and execute the commands using windows default cmd shell it works perfectly fine

**Comment by kaygeeklaas** [comment]
I am also facing this issue when i am using WiFi from the library which does not require any proxy settings to connect to the internet but when i use my mobile phone as a WiFi hotspot everything works perfectly and i do not get this error

Any help on how to fix this issue with WiFi will be much appreciated

**Comment by ArtixZ** [comment]
I'm having this issue when running Jenkins build. Even after setting up the proxy.

**Comment by myjurisdiction** [comment]
npm i user -g npm       use this comand line

**Comment by VivaRunor** [comment]
Hello please I need urgent help.
I am using visual studio code and have installed node js but having issues installing with npm via the terminal.

The following is usually what I get when I try to install using npm install -g lite-server

-------------------------------------------------------------------------------------------------------------

npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/lite-server failed, reason: connect ECONNREFUSED 10.32.47.71:80
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:189:13)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:100:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:122:5)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR!  { FetchError: request to https://registry.npmjs.org/lite-server failed, reason: connect ECONNREFUSED 10.32.47.71:80
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:189:13)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:100:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:122:5)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR!   message:
npm ERR!    'request to https://registry.npmjs.org/lite-server failed, reason: connect ECONNREFUSED 10.32.47.71:80',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack:
npm ERR!    'FetchError: request to https://registry.npmjs.org/lite-server failed, reason: connect ECONNREFUSED 10.32.47.71:80\n    at ClientRequest.req.on.err (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n    at ClientRequest.emit (events.js:189:13)\n    at onerror (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\agent-base\\index.js:100:9)\n

**Comment by CompuTaker** [comment]
If you are using Windows OS, I guess when you run the CMD with the administrator mode(Administraion permit), the problem might be solved. Well, it worked in my case...

**Comment by wide4head** [comment]
@VivaRunor Are you using a proxy server at 10.32.47.71?  Looks like the proxy is not running  or the listening port is not 80. Please check

**Comment by VivaRunor** [comment]
@wide4head and @CompuTaker thanks for your response to me. 

Please I just run my cmd as an administrator and tried to npm install but still getting same errors


![npm](https://user-images.githubusercontent.com/47452951/57217673-2c230100-6feb-11e9-9d03-571169396952.JPG)





You

**Comment by binnerlee** [comment]
> I am also facing this issue when i am using WiFi from the library which does not require any proxy settings to connect to the internet but when i use my mobile phone as a WiFi hotspot everything works perfectly and i do not get this error
> 
> Any help on how to fix this issue with WiFi will be much appreciated

I have encountered the same problem. However, I used the WIFI problem at home.

**Comment by VivaRunor** [comment]
I see
It therefore means my company server which I use is the reason. okay, I'll
try using my mobile network

**Comment by VivaRunor** [comment]
Yes, I'm using Windows OS, I'll try this in the morning.

Thanks.

**Comment by maheshantaliya** [comment]
I have error while installing npm install http-server
i tried in administrator too but it did't work for me.
[New Text Document.txt](https://github.com/nodejs/help/files/5098913/New.Text.Document.txt)

**Comment by maheshantaliya** [comment]
C:\WINDOWS\system32>npm install http-server
npm ERR! code EACCES
npm ERR! errno EACCES
npm ERR! FetchError: request to https://registry.npmjs.org/http-server failed, reason: connect EACCES 104.16.22.35:443
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:180:13)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:395:9)
npm ERR!     at TLSSocket.emit (events.js:180:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:178:19)
npm ERR!  { FetchError: request to https://registry.npmjs.org/http-server failed, reason: connect EACCES 104.16.22.35:443
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:180:13)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:395:9)
npm ERR!     at TLSSocket.emit (events.js:180:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:178:19)
npm ERR!   message: 'request to https://registry.npmjs.org/http-server failed, reason: connect EACCES 104.16.22.35:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'EACCES',
npm ERR!   code: 'EACCES',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/http-server failed, reason: connect EACCES 104.16.22.35:443\n    at ClientRequest.req.on.err (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n    at ClientRequest.emit (events.js:180:13)\n    at TLSSocket.socketErrorListener (_http_client.js:395:9)\n    at TLSSocket.emit (events.js:180:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:178:19)' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shivay\AppData\Roaming\npm-cache\_logs\2020-08-19T19_49_14_702Z-debug.log

**Comment by PenguSL** [comment]
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080

(eg:)
npm config set proxy http://10.50.225.222:3128
npm config set https-proxy http://10.50.225.222:3128

**Comment by JiveshRajput** [comment]
I am also facing same issue. Can somebody help me please

**Comment by alirezakasirzare** [comment]
i have same problem...

**Comment by Diokuz** [comment]
+

**Comment by Zaki-Dz** [comment]
try using sudo npm, it worked for me

**Comment by joeadu** [comment]
i am also having same issues adding angular fire. Package found, files loaded but installation keeps failing with the same error
 Unable to load package information from registry: request to http://registry.npmjs.org/@angular%2ffire failed, reason: read ECONNRESET

**Comment by Coderddd** [comment]
hello guys i just came across this problem and solved by: npm config edit then clear out ur .npmrc file, save it then clean out chache using npm cache clean -f then try createing your react app, happy-hacking!

**Comment by NYN1100** [comment]
> hello guys i just came across this problem and solved by: npm config edit then clear out ur .npmrc file, save it then clean out cache using npm cache clean -f then try createing your react app, happy-hacking!

Really helped me.Thanks.

**Comment by Nuwanthi-R** [comment]
try updating npm
` npm install -g npm`

**Comment by amin-shahin** [comment]
> hello guys i just came across this problem and solved by: npm config edit then clear out ur .npmrc file, save it then clean out cache using npm cache clean -f then try createing your react app, happy-hacking!

thanks a lot 💯 🥇 
your solution worked for me :)

**Comment by moweiwei** [comment]
> hello guys i just came across this problem and solved by: npm config edit then clear out ur .npmrc file, save it then clean out cache using npm cache clean -f then try createing your react app, happy-hacking!

not works for me

**Comment by Ashutosh11-yadav** [comment]
Hello Developers, I faced this problem too.
But after going through the second point of this article [](https://weekendprojects.dev/posts/fixed-npm-err-code-econnreset/) my error get solved.

**Comment by FernandoGOT** [comment]
> hello guys i just came across this problem and solved by: npm config edit then clear out ur .npmrc file, save it then clean out cache using npm cache clean -f then try createing your react app, happy-hacking!

I was having this problem on my Windows (WSL 2) and this fixed for me

**Comment by codingwithsaleem** [comment]
to resolve this issue 

delete the package-lock and node module folder 

then add the nodejs engine in the package.json file 

"engines": {
    "node": "20.x",
    "npm": "10.x"
  }
  
  then run npm install and push the changes
