### ISSUE TITLE
How to use N-API for sending array from JavaScript to C++ and back

### ISSUE THREAD

**Issue by jimcarst** [nodejs/help#1154]
* **Node.js Version**: v9.8.0
* **OS**:  Windows 10 64bit
* **Scope**: code
* **Module**: N-API
Hi,

Currently, I am trying to pass a (2xN) array from a JavaScript application to a C++ module using N-API. Then I calculate something with the array and want to return a (1xM) array to the JS application and log it to the console. For example, it could take a (2xN) array, calculate the sum of each pair of numbers in the array, and return this in a (1xN) array.

However, since I am a beginner in the field I have trouble figuring out how to do this type of conversion. Therefore I was wondering if someone could help me out and put me on the right track.

Sample Node application code:

```js
const addon = require('../build/Release/module');
const inputarray = [  [1.111, 2.222],   [3.333, 4.444],
                      [5.555, 6.666],   [7.777, 8.888]   ];
const outputarray= addon.my_function(inputarray);
console.log(outputarray);
```

Sample C++ module code:
```cc
#include <node_api.h>

napi_value MyFunction(napi_env env, napi_callback_info info) {
  napi_status status;
  size_t argc = 1;
  double array[]=  { };
  napi_value argv[1];
  status = napi_get_cb_info(env, info, &argc, argv, NULL, NULL);  
  status = napi_get_value_double(env, argv[0], &number);
  
  napi_value myNumber;
  array[i]= number[i][0] + number[i][1];
  status = napi_create_array(env, number, &myArray);

  return myArray;
}

napi_value Init(napi_env env, napi_value exports)
{
  napi_status status;
  napi_value fn;

  status = napi_create_function(env, NULL, 0, MyFunction, NULL, &fn);
  status = napi_set_named_property(env, exports, "my_function", fn);

  return exports;
}
NAPI_MODULE(NODE_GYP_MODULE_NAME, Init) //initialise node module pointing -> Init
```

Desired output:
```js
[3.333,   7.777,
12.221,   16.665];
```
Many thanks in advance.

**Comment by gireeshpunathil** [comment]
I tried to fix the code and realized that it needs deeper knowledge than I thought initially. Copying the experts.
/cc @aruneshchandra @jasongin @mhdawson

**Comment by bnoordhuis** [comment]
If you'll be passing large amounts of data around, then for efficiency reasons it makes more sense to use typed arrays instead of normal arrays.  Typed arrays are one-dimensional, though.

**Comment by jimcarst** [comment]
Thanks for taking a look. A typical inputarray I want to use would be (50x2), max (300x2). This doesn't qualify as a large amount of data right? If it does though, taking into account the one-dimensionality of the typed array is something I could comfortably do in C++ so not a problem.

**Comment by bnoordhuis** [comment]
How often do you call your C++ code?  Because of JS semantics, retrieving an element from a JS array is several magnitudes slower than retrieving the same element from a typed array.

**Comment by jimcarst** [comment]
For each program run once, to calculate the outputarray. 

All the entries of the array are doubles, so that would also help with typing.

Using node/test/addons-napi/test_array/ I managed to get the following code to work:
```cc
#include <node_api.h>

napi_value MyFunction(napi_env env, napi_callback_info info)
{  ...  }
 
napi_value New(napi_env env, napi_callback_info info)
{
  size_t argc = 1;
  napi_value args[1];
  napi_status status;

  status = napi_get_cb_info(env, info, &argc, args, NULL, NULL);  
  napi_valuetype valuetype0;
  status = napi_typeof(env, args[0], &valuetype0);  
  napi_value ret;
  status = napi_create_array(env, &ret);
  uint32_t i, length;
  status = napi_get_array_length(env, args[0], &length);
  for (i = 0; i < length; i++)
  {
    napi_value e;
    status = napi_get_element(env, args[0], i, &e);
   status = napi_set_element(env, ret, i, e);
  }
  return ret;
}

napi_value Init(napi_env env, napi_value exports)
{
  napi_status status;
  napi_value fn;

  status = napi_create_function(env, NULL, 0, MyFunction, NULL, &fn);
  status = napi_set_named_property(env, exports, "my_function", fn);

  status = napi_create_function(env, NULL, 0, New, NULL, &fn);
  status = napi_set_named_property(env, exports, "New", fn);

  return exports;
}
NAPI_MODULE(NODE_GYP_MODULE_NAME, Init) //initialise node module pointing -> Init
```
Calling in JS New(inputarray) gives the same array as output for 1-dimensional input. So this is not 2D, and I can not perform any calculations on the array in between (maybe because the values are references?). I think I should somehow separate the reading of the inputarray from the writing to an outputarray so I can do this.

**Comment by bnoordhuis** [comment]
> I think I should somehow separate the reading of the inputarray from the writing to an outputarray so I can do this.

That's easiest and cleanest but you can update in-place: `napi_get_element(i)` -> compute new value -> `napi_set_element(i, newval)`.

**Comment by jimcarst** [comment]
Sure thing, but since the dimensionality of the inputmatrix is different from the outputmatrix, a simple in-place calculation swapping the values wouldn't suffice. Which is why I think it maybe should be separated.

**Comment by jimcarst** [comment]
I fixed it. Separating the get_element from the set_element and putting get_value_double and create_double in between did the trick. Thanks for your help!
