### ISSUE TITLE
Implement synchronous behavious

### ISSUE THREAD

**Issue by tecziq** [nodejs/help#1155]
* **Node version: 8.9.4**
* **OS: Windows**
* **Scope: Synchronous Nature**

Issue:
I am using MongoDB with node.

The thing is i have many-to-many relationship inside mongodb collections. I want a query is like: get list of values from one table based on some parameter then based on values fetched previously run another query in for loop and fetch other data and so on...

The issue i am facing is of asynchronous behaviour of node.

 I would appreciate the help ....!!!

**Comment by gireeshpunathil** [comment]
please see if this [link](https://www.guru99.com/node-js-promise-generator-event.html) helps you - it precisely talks about usage of promises to address mongodb multi-fetch use case.

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it does not help you
