### ISSUE TITLE
EACCES error when trying to run "node index.js" from CMD

### ISSUE THREAD

**Issue by philipjani** [nodejs/help#1159]
* **Node.js Version**: 8.10.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: When trying to run server on CMD with "node index.js"
* **Module (and version) (if relevant)**:

C:\Users\Phil\Documents\node\new_project>node index.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES localhost
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1503:5)
    at Object.<anonymous> (C:\Users\Phil\Documents\node\new_project\index.js:9:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

index.js source code if it helps.
'''
const http = require('http');
const hostname = 'localhost';
const port = 3000;

const server = http.createServer((req, res) => {
	res.end('Welcome to Node!');
});

server.listen(hostname, port, () => {
	console.log('server listening on host: ${hostname} port: ${port}');
});
'''

**Comment by gireeshpunathil** [comment]
try a higher port please, say a 5 digit number.

**Comment by gireeshpunathil** [comment]
sorry, I did not look at your code. the listen takes port number as its first param:
https://nodejs.org/dist/latest-v9.x/docs/api/http.html#http_server_listen

So please try this code:
```js
const http = require('http');
const hostname = 'localhost';
const port = 3000;

const server = http.createServer((req, res) => {
res.end('Welcome to Node!');
});

server.listen(port, () => {
console.log(`server listening on host: ${hostname} port: ${port}`);
});
```

**Comment by philipjani** [comment]
Thanks. That looks like it did the trick!

**Comment by aman071** [comment]
Hello, firstly thanks to @gireeshpunathil . this solved by issue too.
I'm new to Node.js. I don't understand what the problem was here? Could you please explain? Just removing the hostname did the trick, why is that? 

Thank You.

**Comment by trustidkid** [comment]
I tried this but it still returns  
![image](https://user-images.githubusercontent.com/39337003/55795966-d37e4800-5ac0-11e9-84c9-5d2b98151ed8.png). This is my first time of doing Node.js. Thanks.
