### ISSUE TITLE
node reactive data sharing

### ISSUE THREAD

**Issue by edwardsmarkf** [nodejs/help#116]
hello -

What is the easiest way to share a simple data-object using something like meteor's reactive programming between server and client? 

currently i am using socket.io and express for the application.

In other words, i want the data-object to stay synced-up between the server and the client.

I saw redis in my research but it seemed like overkill for one simple data-object. 

thank you very much.

**Comment by lordKnighton** [comment]
are you searching for something in this ballpark? -http://stackoverflow.com/questions/10326347/how-do-you-store-data-server-side-that-is-specific-to-a-client-in-meteor

**Comment by edwardsmarkf** [comment]
actually i was hoping for a very simple package that would let me share a data-object between client and server, and hopefully it has nothing to do with meteor at all, except maybe to emulate it a little bit.

my favorite examples are the ones with just a few lines of code on the client and a few more on the server-side.

**Comment by lordKnighton** [comment]
This seems a bit abstract, http://programmers.stackexchange.com/questions/188427/how-to-synchronize-client-and-server-model-objects check this out.

**Comment by lordKnighton** [comment]
> i want the data-object to stay synced-up 

if you're using express & socket.io. you have your express code running, so what's your client code that wont stay sync?

**Comment by edwardsmarkf** [comment]
can express & socketIo sync up variables?  i know you can pass values back & forth easily enough, but i was hoping to take a variable on node.js and virtually "bind" it to the same variable on the client side.

if you know a way, please let me know.

i am tempted to post this on stackOverflow, but those people just love to vote down questions if they sense a lack of research for an answer.

**Comment by lordKnighton** [comment]
I don't think so, an if so, will this really prove of better way, if anything it just seems like a high tech way of doing something. To my knowledge, i think you're thinking of the react & angular stuff, I haven't heard of this, but if you're determined on this path, interact with people [here](https://gitter.im/nodejs/node) & [here](https://gitter.im/expressjs/express) I've posted something there already, but i'd like you to post.

**Comment by edwardsmarkf** [comment]
ok well thanks anyways.  its probably time to try a different approach.

it seems like with node packages, just about anything i can imagine is already being done.

**Comment by lordKnighton** [comment]
I agree, I just have come across something in this nature. Be sure to go to the gitter links i put there or the nodejs google group, many people have different knowledge, so i'm sure that something may be more keen to this type of data manipulation.

**Comment by edwardsmarkf** [comment]
question now on gitter - and by the way Knighton, THANK YOU very much !

**Comment by lordKnighton** [comment]
no worries man, my pleasure. Yeah it should get answered soon.

**Comment by edwardsmarkf** [comment]
lets hope i dont get too many down-votes -- sometimes the stack-overflow people can be vicious:

http://stackoverflow.com/questions/36167001/node-sharing-data-between-server-client

**Comment by lordKnighton** [comment]
you're at `120 10`, that's dwarfs my points by a long shot. You will be fine though.

**Comment by edwardsmarkf** [comment]
most of those points were the result of a bribe.

**Comment by edwardsmarkf** [comment]
this looks rather promising:

https://deepstream.io/tutorials/getting-started.html

**Comment by lordKnighton** [comment]
How's it going with this @edwardsmarkf

**Comment by lordKnighton** [comment]
Hi @edwardsmarkf I hope all is well, I'm gonna close this issue for the time being. If you want to continue, feel free to reopen.  

Happy coding 😺
