### ISSUE TITLE
Error in installing node-report

### ISSUE THREAD

**Issue by raviverma89** [nodejs/help#1160]
Operating System : Ubuntu 16.04
NodeJs : v8.10.0
NPM : 5.6.0
Module :  node-report 2.2.1 
Scope : install

npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'node-report',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.10.0
npm verb npm-session 0b1e59e2df797231
npm http fetch GET 304 https://registry.npmjs.org/node-report 557ms (from cache)
npm verb correctMkdir /home/ravi/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/ravi/.npm/_locks/staging-283c77d2d56b65e0.lock for /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/.staging
npm info lifecycle node-report@2.2.1~preinstall: node-report@2.2.1
npm info linkStuff node-report@2.2.1
npm verb linkBins node-report@2.2.1
npm verb linkMans node-report@2.2.1
npm info lifecycle node-report@2.2.1~install: node-report@2.2.1

> node-report@2.2.1 install /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.10.0
gyp verb command install [ '8.10.0' ]
gyp verb install input version string "8.10.0"
gyp verb install installing version: 8.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.10.0
gyp verb build dir attempting to create "build" dir: /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/build
gyp verb build dir "build" dir needed to be created? /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/config.gypi
gyp verb common.gypi checking for gypi file: /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ravi/.node-gyp/8.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ravi/.node-gyp/8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ravi/.node-gyp/8.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/ravi/.node-gyp/8.10.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/build'
  g++ '-DNODE_GYP_MODULE_NAME=api' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNODEREPORT_VERSION="2.2.1"' '-D_GNU_SOURCE' '-DBUILDING_NODE_EXTENSION' -I/home/ravi/.node-gyp/8.10.0/include/node -I/home/ravi/.node-gyp/8.10.0/src -I/home/ravi/.node-gyp/8.10.0/deps/uv/include -I/home/ravi/.node-gyp/8.10.0/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g -O2 -std=c++11 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/api/src/node_report.o.d.raw   -c -o Release/obj.target/api/src/node_report.o ../src/node_report.cc
  g++ '-DNODE_GYP_MODULE_NAME=api' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNODEREPORT_VERSION="2.2.1"' '-D_GNU_SOURCE' '-DBUILDING_NODE_EXTENSION' -I/home/ravi/.node-gyp/8.10.0/include/node -I/home/ravi/.node-gyp/8.10.0/src -I/home/ravi/.node-gyp/8.10.0/deps/uv/include -I/home/ravi/.node-gyp/8.10.0/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g -O2 -std=c++11 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/api/src/module.o.d.raw   -c -o Release/obj.target/api/src/module.o ../src/module.cc
  g++ '-DNODE_GYP_MODULE_NAME=api' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNODEREPORT_VERSION="2.2.1"' '-D_GNU_SOURCE' '-DBUILDING_NODE_EXTENSION' -I/home/ravi/.node-gyp/8.10.0/include/node -I/home/ravi/.node-gyp/8.10.0/src -I/home/ravi/.node-gyp/8.10.0/deps/uv/include -I/home/ravi/.node-gyp/8.10.0/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g -O2 -std=c++11 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/api/src/utilities.o.d.raw   -c -o Release/obj.target/api/src/utilities.o ../src/utilities.cc
  g++ -shared -pthread -rdynamic -m64  -Wl,-soname=api.node -o Release/obj.target/api.node -Wl,--start-group Release/obj.target/api/src/node_report.o Release/obj.target/api/src/module.o Release/obj.target/api/src/utilities.o -Wl,--end-group 
  rm -rf "Release/api.node" && cp -af "Release/obj.target/api.node" "Release/api.node"
  rm -rf "/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/api.node" && cp -af "Release/api.node" "/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/api.node"
/bin/sh: 1: Syntax error: "(" unexpected
install.target.mk:8: recipe for target '/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/api.node' failed
make: *** [/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/api.node] Error 2
make: Leaving directory '/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm verb lifecycle node-report@2.2.1~install: unsafe-perm in lifecycle true
npm verb lifecycle node-report@2.2.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report/node_modules/.bin:/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/ravi/Documents/software/Sdk/tools:/home/ravi/Documents/software/Sdk/platform-tools
npm verb lifecycle node-report@2.2.1~install: CWD: /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/node-report
npm info lifecycle node-report@2.2.1~install: Failed to exec install script
npm verb unlock done using /home/ravi/.npm/_locks/staging-283c77d2d56b65e0.lock for /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)/node_modules/.staging
npm WARN mongoose-delete@0.4.0 requires a peer of mongoose@4.x but none is installed. You must install peer dependencies yourself.
npm WARN winston-daily-rotate-file@1.7.2 requires a peer of winston@2.x but none is installed. You must install peer dependencies yourself.

npm verb stack Error: node-report@2.2.1 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid node-report@2.2.1
npm verb cwd /home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)
npm verb Linux 4.4.0-112-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-report" "--verbose"
npm verb node v8.10.0
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-report@2.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-report@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ravi/.npm/_logs/2018-03-12T10_51_31_746Z-debug.log

**Comment by gireeshpunathil** [comment]
can you **manually** remove `/home/ravi/Documents/projects/node-backend-seed/MEAN Seed (Activity_Based_Auth)` folder or rename it without the special characters such as SPACE and brackets, and try again?

**Comment by raviverma89** [comment]
@gireeshpunathil  worked fine, Thanks

**Comment by gireeshpunathil** [comment]
wonderful, closing then, thanks!
