### ISSUE TITLE
Aggregration + Merging results in MongoDB v3.6

### ISSUE THREAD

**Issue by tecziq** [nodejs/help#1163]
* **Node.js Version**: v8.9.4
* **OS**: Windows

I have three collections as below:

Products - row:

    {
        _id : 5aaa0eec9a77b10a789e5f38,
        name : "Product 1",
        parts : [
            {
              parts_id : 5a8fbe48c4c15b31f4885446,
              quantity : "1"
            },
            {
              parts_id : 5a8fbe48c4c15b31f4885126,
              quantity : "2"
            }
        ]
    },
    {
        _id : 5aaa0eec9a77b10a789e5f39,
        name : "Product 2",
        parts : [
            {
              parts_id : 5a8fbe48c4c15b31f4885446,
              quantity : "1"
            },
            {
              parts_id : 5a8fbe48c4c15b31f4885126,
              quantity : "2"
            }
        ]
    }
    
Parts - row:

    {
        _id : 5a8fbe48c4c15b31f4885446,
        name : "Part 1"
    },
    {
        _id : 5a8fbe48c4c15b31f4885126,
        name : "Part 2"
    }
    
Order collection:

    {
        _id : 5aaa0eec9a77b10a789e5f38,
        order_no : "Testing Order",
        products : [
            {
              products_id : 5aaa0eec9a77b10a789e5f38,
              quantity : "1"
            },
            {
              products_id : 5aaa0eec9a77b10a789e5f39,
              quantity : "1"
            }
        ]
    }

Flow is like we have products which contains some parts. Products doesn't exists in physical, parts exists. Consider this scenario like grouped products.

Now if i want to check an order products and related parts i want a result like below:- 

    {
        _id: 5aaa0eec9a77b10a789e5f38 //order_id
        order_no: "Testing Order"
        products: [
            {
                 products_id: 5aaa0eec9a77b10a789e5f38,
                 name : "Product 1",
                 quantity : "1",
                 parts : [
                    {
                      parts_id : 5a8fbe48c4c15b31f4885446,
                      name: "Part 1",
                      quantity : "1"
                    },
                    {
                      parts_id : 5a8fbe48c4c15b31f4885126,
                      name : "Part 2",
                      quantity : "2"
                    }
                ]
            },
            {
                 products_id: 5aaa0eec9a77b10a789e5f39,
                 name : "Product 2",
                 quantity : "1",
                 parts : [
                    {
                      parts_id : 5a8fbe48c4c15b31f4885446,
                      name: "Part 1",
                      quantity : "1"
                    },
                    {
                      parts_id : 5a8fbe48c4c15b31f4885126,
                      name : "Part 2",
                      quantity : "2"
                    }
                ]
            }
        ]
    }

I am using nodejs v8.9.4 with mongoDB v3.6
I have tried to fetch results from one collection and then run for loops then fetch results from another collection. Due to the asynchronous nature of nodejs loops approach not working. Finally, i managed to write a single query with nested $lookup but the thing is; not able to fetch data as required.

Please check below query i managed to write:-

    db.Order.aggregate([
        { $lookup: {
          from: "Products",
          localField: "Products.Products_id",
          foreignField: "_id",
          as: "Products"
        } }, 
        { $unwind: {
          path: "$Products",
          preserveNullAndEmptyArrays: true
        } },
        { $lookup: {
          from: "Parts",
          localField: "Products.parts.parts_id",
          foreignField: "_id",
          as: "Products.parts",
        } }
    ]).toArray(function (err, orderedProducts){        
        console.log(orderedProducts);
    });

Result with above query (below result is for order with two products in cart):-

    [ 
      { 
        _id: 5aaa0eec9a77b10a789e5f38,
        order_no: 'Testing Order',
        Products: { 
           _id: 5aaa0eec9a77b10a789e5f38,
           name : "Product 1",
           parts : [
                 {
                     parts_id : 5a8fbe48c4c15b31f4885446,
                     name : "Part 2"
                 },
                 {
                     parts_id : 5a8fbe48c4c15b31f4885126,
                     name : "Part 2"
                 }
           ]
        } 
      },
      { _id: 5aaa0eec9a77b10a789e5f30,
        order_no: 'Testing Order',
        Products: { 
           _id: 5aaa0eec9a77b10a789e5f39,
           name : "Product 2",
           parts : [
                 {
                     parts_id : 5a8fbe48c4c15b31f4885446,
                     name : "Part 2"
                 },
                 {
                     parts_id : 5a8fbe48c4c15b31f4885126,
                     name : "Part 2"
                 }
           ],
       } 
    ]

As you can see in above result no quantity is showing also result is an array of two instead of one.

Any help will be greatly appreciated !!!

**Comment by gireeshpunathil** [comment]
loop approach does not help, you will need either plain callback based approach or promises. Please see if [this](https://www.guru99.com/node-js-promise-generator-event.html) tutorial helps you

**Comment by tecziq** [comment]
@gireeshpunathil 

Thanks for suggestion.

Can't we get the desired result in single query ? As, if you see in above explanation, the result; query returning is in array of multiple object and the aggregation also overwriting the results from prior tables. What i want is single object with nested results. Can't this be achievable in single query ?

**Comment by gireeshpunathil** [comment]
sorry, that is beyond the scope of this project repo. You could review the mongo documentation [here](http://mongodb.github.io/node-mongodb-native/3.0/api/) or if that does not yield anything, ask them [here](https://github.com/mongodb/node-mongodb-native) . Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered within this repo's scope. please re-open if you think that is not the case, thanks.
