### ISSUE TITLE
Call a javascript function from C using api

### ISSUE THREAD

**Issue by prabhaguna** [nodejs/help#1164]
I am working with napi with C, I can able to call a C function from nodejs. I need to call a javascript function from C. I followed the napi documentation and I tried the example mentioned under 
"napi_call_function". but it not works 

https://nodejs.org/api/n-api.html#n_api_napi_call_function

Can you please give an working example to call a javascript function from C

**Comment by jasnell** [comment]
Hello @prabhaguna ... take a look at the test/addons-napi/test_function... specifically https://github.com/nodejs/node/blob/master/test/addons-napi/test_function/test_function.c#L4-L27

The test illustrates how calling a js function from C works.

**Comment by NickNaso** [comment]
Hi @prabhaguna ,
you can take a look here https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/3_callbacks/napi 
In the example a function passed from javascript is called from C.

**Comment by gireeshpunathil** [comment]
Closing as answered.

**Comment by theslyprofessor** [comment]
Hi, I am having the same difficulty. Some of the links are not working anymore. Is there a simple C file I can look at where a call to nodejs is made? 
Thanks,
Nakul
