### ISSUE TITLE
Can't install on Windows 7

### ISSUE THREAD

**Issue by carej** [nodejs/help#117]
I've tried both LTS and Stable, neither will install on Windows 7 Enterprise. Both kick out with an error dialog that says:

> The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203.

**Comment by lordKnighton** [comment]
https://github.com/nodejs/node/issues/5816 

 Are you using the Msi or exe?

**Comment by carej** [comment]
msi; should I try the exe? Is that an installer or just a naked binary?

On Tuesday, March 22, 2016, kelvin knighton <notifications@github.com>
wrote:

> nodejs/node#5816 <https://github.com/nodejs/node/issues/5816>
>
> Are you using the Msi or exe?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/117#issuecomment-200040224>
>


-- 
JEC

**Comment by lordKnighton** [comment]
binary

**Comment by lordKnighton** [comment]
Hey bud, how are you doing with this?

**Comment by carej** [comment]
I tried the suggestion regarding adding Everyone to my AppData\Local\Temp directory. Now when I run the installer after a while it pops up a dialog with the title of **Node.js setup** and text that reads:

> The system cannot open the device or file specified.

My options are _Retry_ and _Cancel_. Retry just seems to spit the same dialog back at me. Selecting Canel I get a new diaglog with this text:

> The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2755.

**Comment by lordKnighton** [comment]
Here are a few resources, i'll keep updating it through out the day. :8ball: 

- https://bitnami.com/stack/nodejs/installer

**Comment by carej** [comment]
I deleted the old installer and grabbed a new LTS installer (which I noticed is now 4.4.1). Trying to install this I get a message:

> The installer has insufficient privileges to access the directory c:\Users\xxxxx\AppData\Roaming\npm. The installation cannot continue. Log on as administrator or contact your system administrator.

**Comment by lordKnighton** [comment]
https://www.youtube.com/watch?v=PiSH7hNZ9GY

**Comment by lordKnighton** [comment]
https://github.com/nodejs/node-v0.x-archive/issues/4516
& 
https://github.com/nodejs/node-v0.x-archive/issues/3620

There are fixes, but it looks like the best bet is to go manually and get it done. 
When the errors occur, it's mostly isolated & not widespread, so for the time being `manual install` is key.

**Comment by carej** [comment]
After manually creating **AppData\Roaming\npm** retry was successful.

What an ordeal.

**Comment by lordKnighton** [comment]
Glad to hear it :smile:
