### ISSUE TITLE
data visualization with firestore

### ISSUE THREAD

**Issue by AwalDeep** [nodejs/help#1173]
I want to do data visualization and analytics using node.js and my data is in fire-store database.Can anyone help me in how should i proceed .

**Comment by gireeshpunathil** [comment]
@AwalDeep -
 - node.js core does not have features for data visualization. It is all done in the user land
 - searching in the popular module repositories may be the best option.
 - google search got me [this](https://anmolkoul.wordpress.com/2015/06/05/interactive-data-visualization-using-d3-js-dc-js-nodejs-and-mongodb/) . Note that this is informational only, not an endorsement to use it.
 - framework selection may be based on the use case: interactive visualization vs. streaming data visualization vs. customizable views etc.

Hope this helps!

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding, thanks!
