### ISSUE TITLE
SIGINT -  ctrl+c vs. `kill -INT <pid>`

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1177]
* **Node.js: Version 9+**
* **OS: MacOS**
* **Scope: runtime**

I have these handlers:

```js
export const handleSignals = function () {
  process.once('SIGTERM', cleanShutdown);
  process.once('SIGINT', cleanShutdown);
};
```

when I send the process

```bash
kill -TERM x
kill -INT x
```

it can gracefully shutdown (asynchronously).

however, if I just use ctrl+c in the terminal (which should send a SIGINT to the process), it cannot shutdown gracefully - it shuts down immediate (in one tick).

I made a video on this:

https://www.useloom.com/share/d1b433d5e2514c3a904367303650d29e

**Comment by gireeshpunathil** [comment]
thanks @ORESoftware - that (video) was wonderful way of demonstrating issues!

I tried in my MAC, and did not exhibit the issue. So let us start from basics!

```js
process.once('SIGINT', (e) => {
  console.log(e)
  process.exit(0)
})
console.log(process.pid)
setTimeout(() => {},10000000)
```
can you apply the `kill -INT <PID>` and the `CTRL+C` actions and see what happens in the output? In my case it prints SIGINT in both the cases.

**Comment by santigimeno** [comment]
I don't know exactly why you're observing this behavior but there's indeed a difference between using kill and using `ctrl +c` as the latter sends the `SIGINT` signal to all the processes in the same process group whereas using `kill -INT <PID>` just sends the signal to the specific process with pid <PID>. By chance, does your application consists of several processes?

**Comment by gireeshpunathil** [comment]
my guess is that the ctrl+c is intercepted by the `editor`, not `node`

**Comment by the1mills** [comment]
Yeah I realized that when I use ctrl-c it's likely doing this:

1. Sending kill -INT to the bash script
2. Sending kill -INT to nodemon
3. Nodemon must send kill -INT to my node server

However, when I ran kill -INT directly to my process, my process handled it gracefully, whereas looks like nodemon or bash wiil exit and not let the child shutdown gracefully.

**Comment by gireeshpunathil** [comment]
```sh
#bash -version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)
...
#bash -c ./1177.js
17681
^CSIGINT
#
```

With the same program as above, looks like bash is behaving as expected - passing the user input as it is to the child process. In your video, I don't believe bash is involved, instead a shell emulation by the editor, which probably does have default behavior to process ctrl+c rather than passing it on.

In either way, there is nothing actionable in node, please let me know if that is not the case.

**Comment by ORESoftware** [comment]
I think the terminal emulator launches bash and pipes the result to the emulator, but yeah, not something wrong with Node.js.
