### ISSUE TITLE
Query strings with http module

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1178]
Regarding:
https://nodejs.org/api/http.html

How can we set the query string params with the options object?

```js
  const opts = {
     hostname: 'localhost',
     path: '/',
     port: 6969
   };

  const req = http.get(opts, function(resp){
     
   });
```

I am guessing that we have to write them to the request stream? but how?

```js
req.write(???);
```

this does not seem to be well documented. :(

With the user-land request package, it would be:

```js
const request = require('request');
request.get({qs:{}});
```

but I am looking to do this with the core module if possible.

**Comment by devsnek** [comment]
the path should include the querystring:
```js
const opts = {
  hostname: 'localhost',
  path: '/?a=1&b=2',
  port: 6969
};
```

If you want to generate it from an object you can do
```js
const opts = {
  hostname: 'localhost',
  path: `/?${querystring.stringify({ a: 1, b: 2 })}`,
  port: 6969
};
```

**Comment by ORESoftware** [comment]
yeah this needs to go in the docs...when I search for "query" or "qs" or "querystring" on the http module page, there really needs to be a section that describes this.

also, as an aside, this pattern is very convenient:

```js
const opts = {
  hostname: 'localhost',
  path: `/?foo=`${JSON.stringify({ a: 1, b: 2 })}`,
  port: 6969
};
```

then on Express server, or wherever, you can do:


```js
app.use(function(req,res,next){
  req.fooParsed = JSON.parse(req.query.foo);
});
```

**Comment by devsnek** [comment]
already seems to be documented ![](https://gc.gy/ʑ⚍⚶.png)

**Comment by ORESoftware** [comment]
you're right, not sure how I missed that.

IMO, one of the options should be `qs`, it should be a string, and it should be appended to path on behalf of the user.

**Comment by gireeshpunathil** [comment]
Closing as answered, please let me know if that is not the case
