### ISSUE TITLE
process event 'exit' not triggered when receiving SIGTERM

### ISSUE THREAD

**Issue by yw662** [nodejs/help#1180]
* **Node.js Version**: 9.9.0
* **OS**: archlinux, linux 4.15.11-1
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: process

```js
...
fs.writeFileSync(pidFile, process.pid + "\n");
process.on('exit', () => {
    console.log("sth.");
    fs.unlinkSync(pidFile);
});
...
const pid = fs.readFileSync(pidFile);
process.kill(pid);
```

The file is not deleted, and no output.

**Comment by gireeshpunathil** [comment]
@yw662 - thanks for reporting this, looks like this was introduced in v9.2.0 . I have reported this as a bug under https://github.com/nodejs/node/issues/19586

**Comment by addaleax** [comment]
@gireeshpunathil I don’t think it’s related to that, unless there are explicit signal handlers that @yw662 didn’t include in the report.

Generally, Node.js leaves signal handling up to the OS, so for `SIGTERM`, the process will terminate immediately and not emit any JS events, so it’s expected that `.on('exit')` handlers don’t run.

@yw662 Have you tried something like https://www.npmjs.com/package/signal-exit? It’s pretty much made for these situations. :)

**Comment by yw662** [comment]
@addaleax 

II agree this "may not" relate to the signal handler issues,
but event exit should be triggered on signals that cause exit, except SIGKILL and SIGSTOP,
anyway that is what "exit" means, right ?

**Comment by addaleax** [comment]
@yw662 It’s unfortunately not that simple … Node’s signal handlers have to be called asynchronously, so calling them will have to wait until after currently running JS is finished.

So, if we were to introduce a `process.emit('exit')` call into the default signal handlers, that means that you couldn’t interrupt infinite loops like `while(true) {}` anymore. :/

Or, maybe to put it another way: *When* do you think the `process.on('exit')` callback should run?

**Comment by gireeshpunathil** [comment]
@yw662 - is there anything outstanding on this, are you satisfied with the explanation given?

**Comment by yw662** [comment]
@gireeshpunathill  
There are some workarounds for that, but I do think there should be a solution for the problem addaleax mentioned.

That why I dont want to close. If you think this should be closed, you can do it.

**Comment by yw662** [comment]
I know all the work arounds that can solve my problem. I just feel the behavior "wired".

Technically we "can" interrupt the js engine, and run the event callback immediately.  If the process will exit anyway after the function, doing so should be safe, because the engine will have no chance to run sth else. So the problem is not really a problem. It is just not so "javascript".

The event beforeExit will be emitted when there is nothing to do and nothing to wait for. So event exit may not be emitted in that situation, actually.

I understand that keeping compatibility is important for nodejs. If that really affect compatibility, just keep it wired.

**Comment by yw662** [comment]
And, anyway, using an inf loop in nodejs is always a bad idea.

**Comment by gireeshpunathil** [comment]
> we "can" interrupt the js engine, and run the event callback immediately.

How about users who implement custom handlers for signals? this approach will cause functional issues for them.

the `weirdness` you are talking about is probably from a specific class of applications that expect low level signals be attached to exit events. However, Node.js as a runtime that needs to cater to a variety of application needs can only provide APIs and capabilities, while leaving it for the programmer to decide what to do with them, based on the custom need.

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if the provided solution does not work, or there is an outstanding issue identified.
