### ISSUE TITLE
Spawning a bash process and communicating with it

### ISSUE THREAD

**Issue by Aetheryx** [nodejs/help#1183]
* **Node.js Version**: v9.8.0
* **OS**: Arch Linux
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: child_process

I'm trying to spawn a bash process and then keep communicating with it, e.g. persistent cd's and whatnot.
Example:

We have the following folder structure:
```
root
  |-- file1
  |-- file2
  |-- folder1
      |-- file3
      |-- file4
```

We'll describe the function I want as `run`:
```js
run('ls')
// Output: "file1 file2 folder1"

run('cd folder1')
// Output: ''

run('ls')
// Output: "file3 file4"
```

Obviously the function doesn't need to be in this exact form, it could work in a different shape too, like having the output be in an event listener. Just an example to give an idea of what I'm trying to do.  

I played around with `spawn('bash')`, hooking listeners with `.stdout.on('data', (c) => console.log(c.toString())` but that's where I got stuck, I couldn't find anything on how I would pipe data into the process, fiddled around a bit but couldn't get anything meaningful.

**Comment by Aetheryx** [comment]
devsnek figured out the following script, which comes close, but has one critical issue.
```js
const childProcess = require('child_process');

function spawnInstance () {
  const child = childProcess.spawn('bash');
  return (command) => {
    return new Promise((resolve, reject) => {
      child.stdout.once('data', (d) => resolve(d.toString()));
      child.stderr.once('data', (d) => reject(d.toString()));
      child.stdin.write(`${command}\n`);
    });
  };
}

(async () => {
  const bash = spawnInstance();

  console.log(await bash('ls'));
  console.log(await bash('cd modules'));
  console.log(await bash('ls'));
})().catch(console.log);
```
The issue being that `cd` doesn't have any output - stdout or stderr. This means the promise is never resolved or rejected and the process hangs.  
I hadn't been able to find any libraries to do this for me, but [`pty.js`](https://github.com/chjj/pty.js/) seems to be able to do it, but it's a C binding. I'd still like to know a solution to the problem, though.

**Comment by ORESoftware** [comment]
you have to use `stream.end()`

so do:

```js
child.stdin.write(`${command}`);
child.stdin.end(`\n`);
```

or for short, just do this:

```js
child.stdin.end(`${command}\n`);
```

`end` will call `write` before it ends.

just one of those gotchas in the node world :)

**Comment by ORESoftware** [comment]
so do this (I tried to improve your code in general too):

```js
const cp = require('child_process');

function spawnInstance () {
  const c = cp.spawn('bash');
  return command => {
    return new Promise((resolve, reject) => {
      c.stdout.once('data', (d) => resolve(String(d || 'empty stdout')));
      c.stderr.once('data', (d) => reject(String(d || 'empty stderr'));
      c.stdin.end(`${command}\n`);
    });
  };
}

(async () => {
  const bash = spawnInstance();
  console.log(await bash('ls'));
  console.log(await bash('cd modules'));
  console.log(await bash('ls'));
})()
.catch(
console.error
);
```

**Comment by ORESoftware** [comment]
Yeah, I know what you want to do, but I am not sure how to do it. If you want to reuse the same bash process, you need to get rid of stream.end(), that was my mistake.

```js
const cp = require('child_process');

function spawnInstance () {
  const c = cp.spawn('bash');
  return command => {
    return new Promise((resolve, reject) => {
      c.stdout.on('data', d => resolve(String(d || 'empty stdout.\n')));
      c.stderr.once('data', d => reject(String(d || 'empty stderr.\n')));
      c.stdin.write(`echo "${command}" | bash;`);
      c.stdin.write('\n');
    });
  };
}

(async () => {
  const bash = spawnInstance();

  console.log(await bash('ls'));

  console.log('now running cd node_modules...');
  console.log(await bash('cd node_modules'));

  console.log('now running ls again...');
  console.log(await bash('ls'));
})()
.catch(e =>
  console.error(e)
);
```

the above, but it won't actually finish the `cd` command.
In the meantime, you may just want to create a new bash process for each command, although I agree it would be nice to figure out how to reuse the same bash process, let me look into it, it must be possible.

**Comment by Aetheryx** [comment]
But I'm guessing creating a new bash process for each command would lose the pwd. What I'm trying to achieve here is a pwd-persistant bash. If I didn't need that, I'd just use child_process.exec. Maybe using a C-binding is really the only way to do this, like pty.js does?

**Comment by ORESoftware** [comment]
@Aetheryx I bet there is a way to do this with Node.js, just have to figure it out, I am looking into it.

**Comment by ORESoftware** [comment]
@Aetheryx  I asked this question for you on SO:

In the meantime, this works fine:

```js

const cp = require('child_process');

function spawnInstance () {
  return command => {
    return new Promise((resolve, reject) => {
      const c = cp.spawn('bash');
      let stdout = '';
      c.once('exit', function () {
        resolve(stdout);
      });
      c.stdout.on('data', d => {
        stdout += String(d);
      });
      c.stderr.once('data', d => reject(String(d || 'empty stderr.\n')));
      c.stdin.end(`${command}\n`);
    });
  };
}

(async () => {
  const bash = spawnInstance();

  console.log(await bash('ls'));
  console.log('now running ls again...');
  console.log(await bash('cd node_modules && ls'));
})()
.catch(e =>
  console.error(e)
);
```

the above spawns a new bash process for each command, but this is a lot safer.
One thing you could do, if you want, is create a bash process pool. Each time a command runs, you create a new process in the background. So you don't reuse processes, but at least they are already started up for you, ready to receive stdin. I have done this before.

**Comment by Aetheryx** [comment]
I can definitely appreciate you helping me, but the solutions you're offering way overcomplicate things to me. For one, they don't do what I'm looking for whatsoever, and outside of that I don't see why one would use your solution over `child_process.exec`.

**Comment by ORESoftware** [comment]
the purpose of using spawn is primarily to pipe the results elsewhere. exec will buffer things.
but I think there is a way to do this, just have to find someone more knowledgeable than I.

**Comment by gireeshpunathil** [comment]
@Aetheryx - 2 issues:

1. `child.stdout.once` assumes that the child's data is always available in one shot - When child data is large (also depending on the platforms that decide to send data in chunks) you will not get all the data.

2. your original issue: commands that do not print anything but completes successfully cannot be caught.

Please review this and see if you find it useful.

#cat 1183.js 

```js
const cp = require('child_process')
const readline = require('readline');

function spawnInstance () {
  const c = cp.spawn('bash')
  return command => {
    return new Promise((resolve, reject) => {
      var buf = Buffer.alloc(0)
      c.stdout.on('data', (d) => {
        buf = Buffer.concat([buf, d])
        if(buf.includes('ERRORCODE'))
          resolve(String(buf))
      })
      c.stderr.on('data', d => {
        buf = Buffer.concat([buf, d])
        reject(String(buf))
      })
      c.stdin.write(`${command} && echo ERRORCODE=$?\n`)
    })
  }
}

process.stdout.write('nodebash$$$ ');
const rl = readline.createInterface({
  input: process.stdin
})

function err(e) {
  console.error(e);
  process.stdout.write('nodebash$$$ ');
}
rl.on('line', (command) => {
(async () => {
  const bash = spawnInstance()
  const output = await bash(command)
  process.stdout.write(output)
  process.stdout.write('nodebash$$$ ');
})().catch(e => err(e));
})
```
#node 1183.js

```trace 
nodebash$$$ pwd
/home/gireesh/support
ERRORCODE=0
nodebash$$$ whoami
gireesh
ERRORCODE=0
nodebash$$$ hello
bash: line 1: hello: command not found

nodebash$$$ cd
ERRORCODE=0
nodebash$$$ echo np  
np
ERRORCODE=0
nodebash$$$ 
```


side effects:

1. Additional error code printing - as we are dealing with IPC, there should be a mechanism for the parent to know the child has completed. You could strip off the error code string from being printed.

2. You could select a deliitor string that is unique and guarenteed not to appear in the child's data.

Hope this helps!

**Comment by Aetheryx** [comment]
@gireeshpunathil Thank you so much for the response, this definitely feels like a step in the right direction. There's still one issue though, for some reason, `cd` doesn't seem to actually change the pwd:
```
nodebash$$$ ls
blah.js
node_modules
ERRORCODE=0

nodebash$$$ cd node_modules
ERRORCODE=0

nodebash$$$ ls
blah.js
node_modules
ERRORCODE=0

nodebash$$$ pwd
/home/aetheryx/Development/persistent-bash
ERRORCODE=0

nodebash$$$ cd node_modules
ERRORCODE=0

nodebash$$$ pwd
/home/aetheryx/Development/persistent-bash
ERRORCODE=0
```
The script doesn't seem to spawn a new process for each command, though. Could this be a limitation out of our reach?

**Comment by gireeshpunathil** [comment]
Right now the `const bash = spawnInstance()` is called every time a line of data is read from the user. Take that out of the block, and it should do the trick.

**Comment by Aetheryx** [comment]
Oh my, I didn't see that line. This works, thank you!
