### ISSUE TITLE
Protractor's webdriver-manager -update  Issue

### ISSUE THREAD

**Issue by Parthibanjj** [nodejs/help#1184]
I am trying to run Protractor's webdriver-manager tool using node:
node ./node_modules/protractor/bin/webdriver-manager update
and get the following output:

webdriver-manager update
events.js:137
      throw er; // Unhandled 'error' event
Error: getaddrinfo ENOTFOUND selenium-release.storage.googleapis.com selenium-release.storage.googleapis.com:443
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)

I am behind company's proxy and I have updated the proxy settings as well
What should i do now?

**Comment by gireeshpunathil** [comment]
@Parthibanjj - when you said you have updated the proxy settings, can you elaborate what exactly you did? thanks!

**Comment by Parthibanjj** [comment]
Lke this below code.. i have update the proxy setting and tries to update the Proxy
$ npm config set proxy http://localhost:3128
$ npm config set https-proxy http://localhost:3128

After this i have tried run Protractor's webdriver-manager tool using node.js

**Comment by gireeshpunathil** [comment]
are you able to `ping` `selenium-release.storage.googleapis.com` ?

**Comment by gireeshpunathil** [comment]
ping @Parthibanjj

**Comment by gireeshpunathil** [comment]
closing, please re-open if you still have the issue.

**Comment by MikePot** [comment]
> closing, please re-open if you still have the issue.

@gireeshpunathil I have the same issue, and I tried that I am not able to ping selenium-release.storage.googleapis.com, is that a test that I am not able to use the proxy if I am not able to ping it? I really appreciate your answers.
