### ISSUE TITLE
express deprecated !!

### ISSUE THREAD

**Issue by amiraahmed-93** [nodejs/help#119]
i try to ceate chat app using node js 
when i run >>  node index.js 
this error appears:
express deprecated res.sendfile: Use res.sendFile instead index.js:6:7

**Comment by TheAlphaNerd** [comment]
change instances of `res.sendfile` to `res.sendFile`
The important thing to notice is the camel case, the capitalization of the **F** in `File`

**Comment by amiraahmed-93** [comment]
yeah i edited it thanks alot :)
