### ISSUE TITLE
Documentation problem re installing via binary archive on Linux

### ISSUE THREAD

**Issue by Marxsal** [nodejs/help#1192]
* **Node.js Version**: n/a
* **OS**: Linux
* **Scope**: Install
* **Module**: n/a

I'm pretty sure that these lines in the Wiki under section "How to install Node.js via binary archive on Linux?" are incorrect:

export NODEJS_HOME=/usr/local/lib/nodejs/node-v8.9.4/bin
export PATH=$NODEJS_HOME/bin:$PATH

If you try this, you'll end up with a path ending in **../bin/bin** which doesn't work. I'm pretty sure the lines should read:

export NODEJS_HOME=/usr/local/lib/nodejs/node-v8.9.4
export PATH=$NODEJS_HOME/bin:$PATH

I could change it in the Wiki (it appears), but want to be sure I've got it right. Can someone confirm that the latter is the correct form?

Thanks!

**Comment by gireeshpunathil** [comment]
@Marxsal - good catch, but which wiki you are referring to? please link it here? thanks!

**Comment by Marxsal** [comment]
The wiki on github:

https://github.com/nodejs/help/wiki/Installation

Thanks!

**Comment by gireeshpunathil** [comment]
your proposal sounds good to me!

**Comment by gireeshpunathil** [comment]
thanks for pointing this out, looks like this is fixed, so closing.
