### ISSUE TITLE
Installing problem with npm install -g @angular/cli

### ISSUE THREAD

**Issue by ykdevep** [nodejs/help#1193]
Hi, I have a problem with node install, I use node version 8.11.1 and I install correctly but when I use: 
npm install -g @angular/cli 
To install the client dependency I have this problems (view image attached) and I cant use the client or the server. I use ubuntu 16.04 LTS on a VirtualBox enviorement. On a real pc with the same OS work fine. I need help please 

![1](https://user-images.githubusercontent.com/23484181/38215661-2916ffbc-368e-11e8-96a6-5797644f9622.jpeg)

**Comment by yw662** [comment]
According to the information you provided, 
The optional dep `fsevents@1.1.3` wanted `darwin` os on any architectures, but want you have is linux.
And this **may** be related to some parts of `angular/cli`, and prevent it from running properly.

Anyway, you should go to [angular-cli](https://github.com/angular/angular-cli) first, before posting sth. here.

**Comment by gireeshpunathil** [comment]
closing as answered
