### ISSUE TITLE
tracker bug in nodejs when use web3.js

### ISSUE THREAD

**Issue by ajax-2** [nodejs/help#1195]
* **Node.js Version**:4.2.6
* **OS**:ubuntu server 1604
* **Scope (install, code, runtime, meta, other?)**:apt-get install nodejs
* **Module (and version) (if relevant)**:

I use nodejs and web3.js to develop solidity cotract, But my script is stoped because of tracker bug. This bug is like this:
```
var c = [{"a":{"g":"h"}}]
Print c:[{a:{g:'h'}}]
var c = [{"a":['v',{"g":"h"}]}]
Print c:[{a:['v',[Object]]}]
```
But i must get [{"a":['v',{"g":"h"}]}] in here!
otherwise, when i use contract's method, i will get 'object cannot convert to string:]'.

**Comment by jsdeveloper97** [comment]
You probably need to use `JSON.stringify` function. Example:

```js
var c = [{"a":['v',{"g":"h"}]}]
console.log(JSON.stringify(c));
// Prints: [{"a":["v",{"g":"h"}]}]
```

**Comment by ajax-2** [comment]
@jsdeveloper97 En! The type of JSON.stringify(c) is 'str'. In web3js, here is must JSON, Because i get the error:
> Error: You must provide the json interface of the contract when instantiating a contract object.

Can we set depth level on system? Thank you for your attention!

**Comment by jsdeveloper97** [comment]
It's not clear to me what you're trying to do. To which function do you pass variable `c`? Where do you see `c:[{a:['v',[Object]]}]` as the output? If the function you're calling stringifies the inner JSON object, then it probably expects a string to be there (but without knowing anything about the function you're calling, I really cannot tell if that is the case).

**Comment by ajax-2** [comment]
@jsdeveloper97 c:[{a:['v',[Object]]}] is a example.  
Following is my web3js' code, And run it with **nodejs web3_c.js **
>web3_c.js
var Web3 = require('web3');
var web3;
var address = ["0x288b178f7538633275002f7795e2bdb177dd6358"];
var p_file = 'Deno.sol'; // this is my file of solidity contract 
var p_name = ':Deno' // this is my contract's name
if (typeof web3 !== 'undefined') {
  web3 = new Web3(web3.currentProvider);
} else {
  // set the provider you want from Web3.providers
  web3 = new Web3(new Web3.providers.HttpProvider("http://18.18.117.118:5587"));
}
var eth = web3.eth;
eth.defaultAccount = address[0]
const fs_c = require('fs')
const solc_c = require('solc')
var source_c = fs_c.readFileSync(p_file,'utf8');
var compileContract_c = solc_c.compile(source_c, 1); //compile solidity file
var abi_c = compileContract_c.contracts[p_name].interface; **  this is contract's abi, equivalent to "c" of my problem, it's type is string **
var bytecode_c = compileContract_c.contracts[p_name].bytecode;
var mycontract = new eth.Contract(JSON.parse(abi_c)); //** here, I must parse abi_c to Json, But i will get object **

In my code, the "**" is important, 
> var abi_c = compileContract_c.contracts[p_name].interface; **  this is contract's abi, equivalent to  "c" of my problem, it's type is string **
var mycontract = new eth.Contract(JSON.parse(abi_c)); //** here, I must parse abi_c to Json, But i will get object **
Those code is about my problem.

**Comment by jsdeveloper97** [comment]
Can you provide the content of `Deno.sol` sile?

**Comment by ajax-2** [comment]
Year, this is my code of  Deno.sol
> pragma solidity ^0.4.0;
contract Deno {
    //Donate People struct
    struct User {
        string donate_user_name;
        string donate_user_phone;
        address donate_user_addr;
        int user_balance;
    }
    address[] users_address ;
    //create mapping to get address-user
    mapping(address => User)  users;
    /**
    * get Author
    */
    function getAuthor() public pure returns(string result){
        return "Allence";
    }
    /**
     * get User
     */
    function getUsers(address userAddres) public view returns (string user_name, string user_phone, int user_coin){
        User storage user_t = users[userAddres];
        require(user_t.donate_user_addr == userAddres);
        user_name = user_t.donate_user_name;
        user_phone = user_t.donate_user_phone;
        user_coin = user_t.user_balance;
    }
    /**
     * create user, need some paramer
     */ 
    function create_user(string donate_user_name, string donate_user_phone,
        address donate_user_addr, int user_balance) 
        public
	{
        require(user_balance > 0);
        require(users[donate_user_addr].donate_user_addr != donate_user_addr);
        users[donate_user_addr].donate_user_addr = donate_user_addr;
        users[donate_user_addr].donate_user_phone = donate_user_phone;
        users[donate_user_addr].donate_user_name = donate_user_name;
        users[donate_user_addr].user_balance = user_balance;
    }
    /**
     * add User balance
     */ 
    function add_user_balance(address user_address, int amount)
    public
    {
        require(amount > 0);
        require(msg.sender != user_address);
        require(users[user_address].donate_user_addr == user_address);
        users[user_address].user_balance += amount;
    }
    }

**Comment by jsdeveloper97** [comment]
If I understand correctly, this works properly and the only problem you're experiencing is that when you log `abi_c` to the console, it displays `[Object]` in it, right? If that is the case, then it has nothing to do with `web3` or `solc` modules. It is the way how `util.inspect` (which is called by the `console.log`) stringifies the object. I hope this code will help you:

```js
'use strict';

var fs_c = require('fs');
var solc_c = require('solc');
var Web3 = require('web3');

var web3 = new Web3(new Web3.providers.HttpProvider('http://18.18.117.118:5587'));
var p_file = 'Deno.sol';
var p_name = ':Deno';
var eth = web3.eth;

eth.defaultAccount = '0x288b178f7538633275002f7795e2bdb177dd6358';

var source_c = fs_c.readFileSync(p_file, 'utf8');
var compileContract_c = solc_c.compile(source_c, 1);
var abi_c = compileContract_c.contracts[p_name].interface;
var bytecode_c = compileContract_c.contracts[p_name].bytecode;
var mycontract = new eth.Contract(JSON.parse(abi_c)); // Works fine

var parsed = JSON.parse(abi_c);
console.log(JSON.stringify(parsed, null, 2)); // Displays the object properly
```

If your problem is something else, please let me know

**Comment by ajax-2** [comment]
@jsdeveloper97 Sorry, I didn't describe the details of the problem. The type of parsing is "string", and not only do I need to see "parse", I can use mycontract as normal. Next I will send you some execution code, maybe this will help you understand my problem.

 check contract's abi';
> mycontract.options.jsonInterface

You will get some similar code
>   { constant: false,
    inputs: [ [Object], [Object], [Object], [Object] ], // here is Object, i think it will affect next result
    name: 'create_user',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x5bce2471' }


and we will use "getAuthor" of mycontract:
> mycontract.options.address=address[0]; // set contarct's address
mycontract.methods.getAuthor().call(console.log); // call(console.log) is print Author to console

i have got the error:
> [Error: ERROR: The returned value is not a convertible string:]

So i think it will get string if we contract's abi is string.

**Comment by ajax-2** [comment]
@jsdeveloper97  "http://18.18.117.118:5587" is my local go-ethereum. Maybe the problem is caused by my web3.js. Could you give my your environment? ex: How to install those softwares or the version of software?

**Comment by ajax-2** [comment]
Thank you, you are great, I hope you have a nice day!
