### ISSUE TITLE
execSync hangs and script does not proceed anymore

### ISSUE THREAD

**Issue by Legends** [nodejs/help#1200]
* **Node.js Version**: v8.10
* **OS**: Win 10 x64
* **Scope (install, code, runtime, meta, other?)**: ?
* **Module (and version) (if relevant)**:

I want to run the following [script](https://github.com/webpack/webpack/blob/master/examples/buildAll.js) from the `webpack` repo.
If you want to please try it out on Win10 x64, perhaps it works on other systems..?!
```
git clone https://github.com/webpack/webpack.git
yarn setup
yarn build:examples
```
I don't know where to start to eliminate this issue, any help is appreciated.

![image](https://user-images.githubusercontent.com/966368/38435264-752383c6-39d1-11e8-8b1d-c31f67b51abc.png)

```js
const cp = require("child_process");
const examples = require("./examples");

const cmds = examples.map(function(dirname) {
	return "cd " + dirname + " && node build.js";
});

let failed = 0;
let i = 0;
for(const cmd of cmds) {
	console.log(`[${++i}/${cmds.length}] ${cmd}`);
	try {
		cp.execSync(cmd, { encoding: "utf-8" });
	} catch(e) {
		failed++;
		console.log(e);
	}
}
console.log("done");
if(failed > 0)
	console.log(`${failed} failed`);
```

**Comment by gireeshpunathil** [comment]
link https://github.com/nodejs/node/issues/19801

**Comment by gireeshpunathil** [comment]
D:\gireesh\1200>cat 1200.js
```js
const cp = require("child_process");
const cmd = 'cd foo && node build.js'
try {
  const o = cp.execSync(cmd, { encoding: "utf-8" });
  console.log(o);
} catch(e) {
  console.log(e);
}
console.log("done");
```
D:\gireesh\1200>cat foo\build.js
```js
jsconsole.log("HELLO!!!!")
```
D:\gireesh\1200>node 1200.js
```
trace
HELLO!!!!

done
```
D:\gireesh\1200>

so as such there is no issue with execSync on Win 10 with node 8.10.
For the sake of simplicity, can you start with this program and see how it goes?
If this one itself hands, enable tracing on the child node to see how far it is able to progress:

```patch
- const cmd = 'cd foo && node build.js'
+ const cmd = 'cd foo && node --trace build.js > out.txt'
```

If this one does not hang, slowly introduce your content into build.js while retaining the `--trace` option.

Hope this helps.

**Comment by Legends** [comment]
Yes, I started to use `console.log` to trace it down and it was not `execSync` that was blocking but another `cp.exec(` in `build-common.js`.

Can you `git clone the webpack repo` and execute the following commands:

```
git clone https://github.com/webpack/webpack.git
npm run setup
npm run build:examples  // <-- I am interested, if this builds on your machine Win10 x64 rigth?
```

**Comment by gireeshpunathil** [comment]
@Legends - thanks for the steps, I am able to reproduce the hang (in win and darwin)

stay tuned!

**Comment by Legends** [comment]
Thanks for your support @gireeshpunathil  !

**Comment by Legends** [comment]
Sorry I forgot an important step to make it work:

you actually need additionaly to:

```
git clone https://github.com/webpack/webpack-cli.git
npm install
npm link
cd/to/the/Webpack/project/folder
npm link webpack-cli
```

**Comment by Legends** [comment]
And in the webpack-cli repo, you probably must install additionaly:

npm install uri-js --save-dev

**Comment by Legends** [comment]
Did you test this on Win10 x64?

**Comment by gireeshpunathil** [comment]
yes, same versions for OS , node and npm.

sure, let me know how it goes.

**Comment by Legends** [comment]
Sorry for bothering you with this, but now it does not hang anymore.. very strange...
I will close this issue for now.
Thanks a lot again to you @gireeshpunathil  !
