### ISSUE TITLE
Problem for 

### ISSUE THREAD

**Issue by Alireza51** [nodejs/help#1202]
* **Node.js Version**:
* **OS**: all OS
* **Scope (install, code, runtime, meta, other?)**: non clear
* **Module (and version) (if relevant)**: base on attached

Dear All
When the homepage runs, there isn't any poster or screen play of videos and they don't work. the errors refer to the two files that I attach it. I can tell more information about the webpage. 
Thanks a lot
[video.list.txt](https://github.com/nodejs/help/files/1886143/video.list.txt)
[download.txt](https://github.com/nodejs/help/files/1886144/download.txt)

**Comment by vsemozhetbyt** [comment]
According to the error messages, Server is on Perl, so maybe Node.js is not related to the issue.

Could you try to report in https://rt.perl.org/ ?

**Comment by ryzokuken** [comment]
@Alireza51 it's definitely a Perl problem. Please close this issue and report this to the Perl issue tracker as suggested by @vsemozhetbyt.
