### ISSUE TITLE
Where are release developer fingerprints?

### ISSUE THREAD

**Issue by Marxsal** [nodejs/help#1203]
I've looked all over github and the nodejs.org site. Where do we find the GPG release fingrprints so we can verify packages properly?

Thanks --
Mark

**Comment by ryzokuken** [comment]
@Marxsal have you tried verifying the packages using the SHA256 checksums? Doesn't that work for you? I don't think the binaries are signed by someone in particular in the release team anyway.

**Comment by ryzokuken** [comment]
@Marxsal BTW, this section in the `README` contains all you'd need: https://github.com/nodejs/node#verifying-binaries

**Comment by Marxsal** [comment]
Thanks, that's it!

**Comment by Marxsal** [comment]
There should be a link to this right next to the SHASUM text file listings.

**Comment by ryzokuken** [comment]
Follow-up:

Created pull https://github.com/nodejs/nodejs.org/pull/1626 regarding this.

@Marxsal looks good to you?
