### ISSUE TITLE
child_process execSync dont't return stdout

### ISSUE THREAD

**Issue by ildelian** [nodejs/help#1205]
* **Node.js Version**: v8.10.0
* **OS**: Windows 10 64 bits
* **Scope (install, code, runtime, meta, other?)**: code/runtime
* **Module (and version) (if relevant)**: child_process

I, i'm trying to invoke yeoman as a child process with this command:

```js
var child = require('child_process').execSync('yo jhipster --skip-install', { cwd: tempDir, maxBuffer: 1024 * 500,stdio: ['pipe', 'pipe', 'pipe']});
```
On the documentation says that, the "execSync" return a Buffer with the stdout, but it is returning an empty buffer.

If I use this:

```js
var child = require('child_process').execSync('yo jhipster --skip-install', { cwd: tempDir, maxBuffer: 1024 * 500,stdio: ['inherit', 'inherit', 'inherit']});
```
I see the stdout on the main console, and the buffer returned is null.

Why the buffer is empty on the first option? What I am doing wrong?

PD: I need to write the stdout of the child process on a file.

Thans.

**Comment by bnoordhuis** [comment]
Suggestion: use `spawnSync()` and check `child.stderr`.  I expect yo is printing to stderr, not stdout.

**Comment by ildelian** [comment]
I already have tried to use spawnSync, but It give me this error:

"error": {
		"code": "ENOENT",
		"errno": "ENOENT",
		"syscall": "spawnSync yo jhipster --skip-install",
		"path": "yo jhipster --skip-install",
		"spawnargs": []
	}

**Comment by ildelian** [comment]
Solver, for spawnSync on windows I have to add ".cmd" to the command.

**Comment by ildelian** [comment]
With spawnSync I obtain this:

stdout -> Empty Buffer
stderr -> The log is here, I do not know why, the app ends fine.

**Comment by ryzokuken** [comment]
@ildelian is this solved, then?

**Comment by ildelian** [comment]
Yes, thanks.

**Comment by ryzokuken** [comment]
@ildelian please close the issue, in that case.
