### ISSUE TITLE
node.js sslv3 with tls.TLSSocket

### ISSUE THREAD

**Issue by Light24** [nodejs/help#1206]
node8.10 + windows7x64

How can I enable sslv3 (аor compatibility with the old client version)? Maybee use existing npm module, writing gyp plugin or anything also?

```js
const opt = {
  isServer: true,
  pfx: Buffer.from(certificate.cert),
  passphrase: certificate.key,
  secureProtocol: 'SSLv3_method',
};

const tlsSocket = new tls.TLSSocket(duplex, req);
```

**Comment by ryzokuken** [comment]
What do you mean? `SSLv3_method` *should* force SSL v3 according to https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

**Comment by bnoordhuis** [comment]
SSLv3 is completely disabled.  The description in the docs was updated recently in #19794 but that isn't live yet.

Can you post questions to nodejs/help next time?
