### ISSUE TITLE
NodeJS sockets, how to receive multiple multicast address on the same port

### ISSUE THREAD

**Issue by GummyDonut** [nodejs/help#1207]
* **Node.js Version**: 6.11.2
* **OS**: Linux (Ubuntu Server)
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: DGram (https://nodejs.org/dist/latest-v6.x/docs/api/dgram.html)

Hello I am currently trying to receive information sent over multiple network interface, with multiple multicast address, but they all share the same port.
Put it more simply, I am binding a socket to listen to a specific port and wish to filter out data that only contain a specific multicast address and was provided in a specific multicastInterface.

Original sample code here:
```js
/**
     * Create instance of the multicast receiver
     * @param multicast, The multicast address we want to receive on, of form { 'ips' : ['addy'], 'port' : # }
     * @param localIPs, an array of ip addresses, [ "","",... ] that represent the network interfaces we are trying to filter on
     * @param transmit, Does something with the message that we received, should be a function
     *                  function(message, info, details) {}
     *                     message, the message received on the multicast
     *                     info,    an object of the source information (contains properties: 'address', 'family', 'port', 'size'),
     *                     details, an object that gets passed to the consuming function containing extra information pertinent to the multicast receiver.
     * @return receiver, an object that can receive content
     */
    'getMulticastUDPReceiver' : function(multicast, localIPs, transmit) {

        // create the connection
    	
        var socket = dgram.createSocket({'type' : 'udp4', 'reuseAddr' : true});
        var receiver = {
            'connection' : socket
        };
  
        
        // grab address information
        var port = multicast['port'];
        var addresses = multicast['ips'];
        
        // Extra arguments that get passed to the transmit consumer function.
        var details = {};
        details['multicast'] = multicast;
        
        // on socket error event handler
        socket.on('error', function(exception) {
                var address = receiver['address'];
                console.log('Multicast Error : ' + (address ? (address['address'] + ':' + address['port']) : 'unknown issue'));
        });

        // on socket close event handler
        socket.on('close', function() {
                var address = receiver['address'];
               console.log('Multicast Close : ' + (address ? (address['address'] + ':' + address['port']) : 'unknown address'));
        });

        // on message receive event handler
        socket.on('message', function(message, info) {
        	
            // call the message event handler function
            if (transmit)
                transmit(message, info, details);
        });

        // bind to the multicast port
        var multicastPort = multicast['port'];
        var multicastIPs  = multicast['ips'];
        
        // 239.71.238.19 :1234
        
        // establish connection
        socket.bind({ 'port' : multicastPort, 'exclusive' : false }, function() {
        	socket.setMulticastLoopback(true);
        	socket.setMulticastTTL(128);
        	
            // cache the address for use
            receiver['address'] = socket.address();
            
            var address = receiver['address'];
            console.log('Multicast Connect : ' + (address ? (address['address'] + ':' + address['port']) : 'unknown address'));

            // loop through the multicast groups and join with the interfaces
            for (var index1 = 0; index1 < multicastIPs.length; index1++) {
                var multicastIP = multicastIPs[index1];
                
                // for each local ip add membership
                for (var index2 = 0; index2 < localIPs.length; index2++) {
                    var localIP = localIPs[index2];
                    
                    try {
                    	console.log("Add Membership : " + multicastIP + ':' + multicastPort + ' on ' + localIP);
                    	
                        // attempt to subscribe
                        socket.addMembership(multicastIP, localIP);
                        console.log('Multicast Joined : ' + multicastIP + ':' + multicastPort + ' on local : ' + localIP);
                    } catch(exception) {
                            console.log('Multicast Join Failed : ' + multicastIP + ':' + multicastPort + ' on local : ' + localIP);
                    }
                }
            }
        });

        // return the multicast receiver instance
        return receiver;
```

Initially this code works, however for some strange reason, every once in awhile( beyond my understanding at this moment)
any information set on the same port is still receives and **socket.on('message', function(){})** is triggered(Note this does not happen consistently and the code will work sometimes?). Thus if we set the multicast object to be 
``` js
{
   "ips"  : ['239.0.0.1'],
   "port": "1234"
}
```
and the data coming over the wire has the multicast address and port of 239.71.238.19 :1234 it still triggers the socket on message call.

To make sure, I wasn't missing anything I've been scouring on the internet looking for a solution
https://github.com/nodejs/node/issues/1690
and mocked my code to look like **receive-specific-address.js** with the LOCALIP replaced with MULTICAST_IP as indicated by **santigimeno**.

However that code does not work for me as I would like to listen to multiple multicast addresses that have the same port (Edit: Tried it anyways and unfortunately it fails when there is a lot of data, still no idea as to why). Sorry to bother you guys with some noobie question. But I have been pulling my hair for the past few days around this issue.

### Edit: 
So I have been doing a bit more testing and found that if this bug only occurs when there is a LOT of information sent over the wire. Note that this code gets called on start up, would it be possible that the bind callback function is not being called on time as the data is coming in and thus the multicast is not being joined?
Otherwise, when data is coming in at a slow rate it seems to be working. 

I have tried updating my code so that the socket.on message occurs after the bind (so now its in the callback function), however to no avail, it still fails to behave as intended when massive amount.
**Note** this data is coming in even before the code runs

### Edit 
Found something else to add to this, I found out that there is another node process that is also binding to the same port, its also runs the same code but with different addresses.

**Comment by gireeshpunathil** [comment]
@lantern77 - is this still outstanding?

**Comment by lantern77** [comment]
Yes sadly I  am not sure as to why this issue is occuring, more details can be found here
https://github.com/nodejs/node/issues/19954

**Comment by lantern77** [comment]
I'll post my more cleaner reproduction here as well, I have 3 files
**socketClient.js, socketClient2.js, and socketServer.js.**
socketServer.js broadcasts UDP messsages on single multicast address(239.0.0.2) and a single port (1234)
while socketClient.js is attempting to receive on multicast address(239.0.0.1) and a port (1234)
while socketClient2.js is attempting to receive on multicast address(239.0.0.2) and a port (1234)

IN the end running the server and both clients will cause the clients to receive message from the server when only socketClient2.js should be receiving it. This doesn't seem to be intended behaviour, but I could be wrong. Is there something wrong with my system, and what is the best way to look into this. Been working on this on and off for weeks and its driving me nuts xD

Code samples below to reproduce:
**socketServer.js**
```javascript
var dgram = require('dgram');

var socket = dgram.createSocket('udp4');
var PORT = '1234';
var MULTICAST_ADDR = '239.0.0.2';
 
 // bind the udp socket to the specified interface ip and enable broadcasting
socket.bind(
		{
		'address' : '172.16.110.24'
		}
		,function() {

		// set multicast
		socket.setBroadcast(true);
		socket.setMulticastTTL(128);
		setInterval(function () {
				let message = new Buffer(new Date().toLocaleTimeString());
				socket.send(message, 0, message.length, PORT, 
						MULTICAST_ADDR, function () {
						console.log("Sent '" + message + "'");
						});
				}, 1000);
		}
);

```


**socketClient.js**
```javascript
var PORT = '1234';
var MULTICAST = '239.0.0.1';
var adapter = '172.16.110.24';
//var adapter = '10.10.160.103';
var dgram = require('dgram');
var client = dgram.createSocket({'type' : 'udp4', 'reuseAddr': true});

client.on('listening', function () {
    var address = client.address();
    //client.setMulticastLoopback(false);
    console.log('UDP Client listening on ' + address.address + ":" + address.port);
    client.setMulticastTTL(128); 
    client.addMembership(MULTICAST, adapter);
});

client.on('message', function (message, remote) {   
    console.log('A: Epic Command Received. Preparing Relay.');
    console.log('B: From: ' + remote.address + ':' + remote.port +' - ' + 'message');
});

client.bind({'port' : PORT});
```


**socketClient2.js**
```javascript
var PORT = '1234';
var MULTICAST = '239.0.0.2';
//var adapter = '10.10.160.103';
var adapter = '172.16.110.24';
var dgram = require('dgram');
var client = dgram.createSocket({'type' : 'udp4', 'reuseAddr' : true});

client.on('listening', function () {
    var address = client.address();
    //client.setMulticastLoopback(false);
    console.log('UDP Client listening on ' + address.address + ":" + address.port);
    client.setMulticastTTL(128); 
    client.addMembership(MULTICAST, adapter);
});

client.on('message', function (message, remote) {   
    console.log('A: Epic Command Received. Preparing Relay.');
    console.log('B: From: ' + remote.address + ':' + remote.port +' - ' + 'message');
});

client.bind({'port' : PORT});
```

**Comment by gireeshpunathil** [comment]
pinging @nodejs/dgram again to see if this can be looked into / explained.

**Comment by GummyDonut** [comment]
@gireeshpunathil It ended being brought up in this https://github.com/nodejs/node/issues/22994 issue and this is no longer a issue I found a solution after a bit of pinging https://github.com/nodejs/node/issues/19954
