### ISSUE TITLE
A strange behavior of Node.js: program exit 0 inside `try{}` block without run `finally {}` block

### ISSUE THREAD

**Issue by zixia** [nodejs/help#1209]
* **Version**: v9.7.1
* **Platform**: Linux zixia-desktop 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**:

Recently I find we can skip the `finally {}` block when we are inside a `try{}` block and without any error reported.

The shortest code is as the following:

```js
async function main() {
  try {
    await new Promise(r => console.log('IN TRY BLOCK'))
  } finally {
    console.log('IN FINALLY BLOCK')
  }
}

main()
```

After running the above program, it will exit immediately with the following one line output:

```shell
IN TRY BLOCK
```

If we `echo $?` we can get `0`. The `finally{}` block has been skipped(which is unexpected).

After thinking/asking/thinking, I begin to understand the reason behind this, more details are in this StackOverflow question/answer: https://stackoverflow.com/questions/49728838/node-js-program-does-not-run-the-finally-block-after-try-and-exit-with/

However, I still feel there's something not right. 

So I post this issue is want to know: do we think this behavior is right? I feel it is not expected because if we write a `try {} finally {}`, we will expect the `finally {}` block always be executed, if it is not at least should raise an error, and I believe the Java/C++ will all follow this flow.

### Summary

I can understand that the finally{} block will not be executed because of unresolved promises do not keep a process alive in Node.js.

However, my question is: should we keep the try {} finally {} behavior consistent with Java & C++ ?

Because this behavior of the try {} finally {} statement in Node.js will make the people who are familiar with Java & C++ very confusing.

Original: https://github.com/nodejs/node/issues/19929

**Comment by ryzokuken** [comment]
I see this was resolved in the original issue (https://github.com/nodejs/node/issues/19929), could you please close this? Feel free to reopen this or open another issue if you have any other issues you'd need help with.
