### ISSUE TITLE
Install Node on Windows Server with domain

### ISSUE THREAD

**Issue by doubletaketech** [nodejs/help#121]
Can you point me to instructions on how to run Node on Windows Server without using IISNode?  I know how to install node, just need to understand how to get a website/domain name to point to it when not going through IIS?

Thanks,
Donnie

**Comment by tudvari** [comment]
Hi Donnie,

if your node application is running, you need to check the following list:

-  Change your domain A or AAA record to the IP address of your server
-  Check your firewall and port forward settings.

I hope it is helpful for you, If you have any question just ask :-)

Best Regards,
Tibor

**Comment by lordKnighton** [comment]
closing for now, reopen to pursue 

happy coding 👍
