### ISSUE TITLE
ANSI escape codes not working properly in Windows Command Line. They used to.

### ISSUE THREAD

**Issue by johndimi** [nodejs/help#1211]
* **Node.js Version**: 6.x and up
* **OS**: Windows 10 64bit

Hello, I was working on some old projects and came across something that no longer appears to work.
With **node 4.x** for Windows (32 and 64 bit versions of node) I could use some **ANSI** codes on the default windows terminal to **save** and **restore** the position of the cursor.

I was using this to draw progress bars and status updates, etc. It was a really useful escape code. But when I updated to versions (6.x, 8.x and 9.x) *(32 and 64bit builds tried them all)* this feature **stopped working**, it mostly breaks everything as it renders my programs unusable on the default CMD.exe, which is something that is already there on all windows systems. 

**Example Code**. It will count to 10 printing every number at the same place, by storing and restoring the cursor position.

```javascript
// - Program start
function print(s) { process.stdout.write(s); }
function savePos()  { print('\033[s'); } // Also tried with the '\x1B[' escape code
function restorePos() { print('\033[u'); }
// --
var c=0; var ctarget=10;
print("\n NodeJs Version : " + process.version + ", Arch : " + process.arch + "\n");
print(" Counting to " + ctarget + " : ");
savePos(); // This is supposed to save the current cursor position
var i = setInterval(function(){
	restorePos(); // And now it is supposed to go where it was
	if(++c==10) { 
		print(" Complete\n");
		process.exit();
	}
	print(' ' + c);
	
},200);
// - End
```

**How it should look like:** *Runs as expected with version 4.9.1*
![working](https://user-images.githubusercontent.com/6090296/38754923-7c3ec9ea-3f6c-11e8-8b52-4980df018566.gif)

**Here is the output with nodejs versions 6 and up**
![notworking](https://user-images.githubusercontent.com/6090296/38754993-c72911e0-3f6c-11e8-8d88-a4599af998fd.gif)

I know the windows terminal doesn't have FULL ANSI support, but some useful codes work just fine, like colors still work, and some other cursor manipulation codes work as well. Why just this particular code seems broken?

Can anyone please help me with this issue?

Many thanks! 😄

**Comment by ryzokuken** [comment]
cc @nodejs/platform-windows @vsemozhetbyt

**Comment by johndimi** [comment]
@Hakerh400 Indeed, I just tested this on another Win10 computer and it seems to work just fine. 
I was too quick to judge since I haven't updated my Windows for a while. Perhaps it's a problem with an older version of CMD.exe, but what threw me off is that with the nodejs 4 it worked fine.

I'm closing this, because it seems it's a fault on my end. Thanks for your time!

**Comment by tniessen** [comment]
@johndimi Feel free to reopen this issue if the problem persists and you believe it is caused by node.

**Comment by johndimi** [comment]
@tniessen  Will do. Going to make more tests tomorrow. Thanks
