### ISSUE TITLE
[Idea] Improve overall issue quality

### ISSUE THREAD

**Issue by advanceddeveloper** [nodejs/help#1214]
Hello. I noticed that a lot of people are having troubles posting a valid issue to nodejs/node repo. Too many issues are labeled as `wrong repo`, `question`, or even `invalid`.

People usually post `npm` issues, or even issues with some external modules, directly to `nodejs/node` issue tracker, which lead to wasting developers' time on closing such issues. I also mistakenly posted an issue which turned out to be my misunderstanding of javascript. Therefore, I think node.js should consider improving issue tracker to filter issues and detect bad ones before posting.

Node.js can use some sort of github-bot which will automatically close (or at least label them) issues by some criterion. For example, issues containing text `why this code doesn't work` or `npm is reporting error` or similar should be closed by the bot with appropriate comment redirecting OP to npm issue tracker, node/help repo, or the issue tracker of the reported module. If it turns out to be a node.js bug, then a someone may easily reopen the issue.

Also, the bot can automatically request missing field from the issue template (for example if someone didn't provide node.js version or platform), except if the issue is posted by a node.js member.

It wouldn't be too hard to create and host a bot for this purpose, and it would make filtering issues much easier. Any opinions about this idea?

![](https://user-images.githubusercontent.com/38354752/38781512-cba3477e-40e6-11e8-8e6d-cee191fe4f84.png)

**Comment by ryzokuken** [comment]
We *could* add such functionality to @nodejs/github-bot. It would be fairly simple, but I'd rather not close issues automatically.

The whole point of this repo is that these issues don't end up in nodejs/node instead, innit?

**Comment by gireeshpunathil** [comment]
link https://github.com/nodejs/node/pull/18867 . @advanceddeveloper - if you have specific proposals / solutions, PRs welcome! Any automation activities that reduce manual efforts of managing issues while sustaining quality and user satisfaction will be much appreciated!

**Comment by kasicka** [comment]
Maybe add something like `If you've found a bug/issue in npm or npm module, consider opening the issue in their own respective repos` in the issue template?

**Comment by bnoordhuis** [comment]
We've tweaked the template quite a bit and it never really stopped the bogus issues.

My gut feeling is that a lot of people simply don't read what you put in front of them unless it has `<font size="72" color="red">` and `<blink>` tags in it.

**Comment by advanceddeveloper** [comment]
Closing. Seems like there isn't a good solution to this problem.
