### ISSUE TITLE
gulp module.js:471     throw err;

### ISSUE THREAD

**Issue by Esraa-Awad** [nodejs/help#1215]
hi, 
Node.js Version: v6.9.1
OS: Windows 10

# I have done all instructions required in below link 
[gulp](https://gulpjs.com/)
# But when I try to execute gulp I got following error
module.js:471
    throw err;
    ^
Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\shop\gulpfile.js:1:75)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
# and this is gulpfile.js
`var elixire=require('laravel-elixir');
elixire(function(mix){
    mix.sass('app.scss')
        .webpack('app.js')
      .style([
            'blog-post.css',
            'bootsrap.css',
            'bootsrap.min.css',
            'font-awesome.css',
            'metisMenu.css',
            'sb-admin-2.css',
            'styles.css',
            'timeline.css'
        ],'./public/css/mycss.css')
        .scripts([
            'app.js',
            'bootstrap.js',
            'bootstrap.min.js',
            'jquery.js',
            'metisMenu.js',
            'sb-admin-2.js'
        ],'./public/js/myjs.js')
});`

**Comment by ryzokuken** [comment]
@Esraa-Awad What are the contents of your `package.json`? Is `larvel-elixir` a dependency? Did you run `npm install`?

**Comment by Esraa-Awad** [comment]
@ryzokuken Thanks for your reply,
yes i run npm install npm install gulp-cli -g
 ### Contents of package.json 
`{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^5.0.1",
    "gulp": "^3.9.1",
    "jquery": "^3.1.1",
    "laravel-mix": "^1.0",
    "lodash": "^4.17.4",
    "vue": "^2.1.10",
    
  }
}
`

**Comment by ryzokuken** [comment]
I'd recommend you to better format the code for readability, but from what I can see, you didn't add `larvel-elixir` as a dependency. That's what's wrong.

**Comment by gireeshpunathil** [comment]
closing as answered.
