### ISSUE TITLE
When does a Stream's close event fire?

### ISSUE THREAD

**Issue by pushkin-** [nodejs/help#1216]
* **Node.js Version**: 7.9.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime/code?
* **Module (and version) (if relevant)**: `child_process`/`Writeable` streams

After calling `cp.spawn`, I save off `proc.stdin`, so I can write to the process. I added a listener for the `close` event. When I kill the process via task manager, the `close` handler fires, because the stream gets destroyed (I believe this is the [source](https://github.com/nodejs/node/blob/master/lib/_stream_writable.js#L148)).

However, if I manually close the stream in my C# process (via `stream.Close()`/`stream.Dispose()`/`stream = null;`), the `close` event does not execute, and my handler doesn't fire.

Is that intended? Does Node get notified if a streams resources are released? When exactly would `close` fire? Only if the process dies, or I close the stream from Node?

**Comment by ryzokuken** [comment]
cc @nodejs/streams

**Comment by gireeshpunathil** [comment]
@pushkin- when you say you manually close the stream via. C#, which stream you are referring to? a steam that is created by Node.js parent and passed it to C# child? or a stream that is created by C# child itself? or one of the stdio streams that is used for the IPC between the two processes?

[This explanation is based on assuming last one is the case] `close` is part of stream's lifecycle events, and its emission is realized through well defined conditionals at program control flow points. If the underlying resource is closed through brute force, or through wrappers in other abstractions  (such as C#) these control flow points will not be ignited and thereby no events will be triggered.

**Comment by pushkin-** [comment]
@gireeshpunathil Alright, I think that answers my question. My C# child process uses the `stdin` stream: `Stream stdin = Console.OpenStandardInput()`
