### ISSUE TITLE
Async/await question

### ISSUE THREAD

**Issue by TempUserNode** [nodejs/help#1220]
* **Node.js Version**: 8.11.1
* **OS**: Win32
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**:

So suppose I have a function that serially, or parallel, calls 2-3 promises. And one of them throws an error, how can I stop the execution?

Example 1:

Created nested promises. Since the if an error gets thrown it will skip all the `then` and go straight to the catch, I can stop the execution.

```js
function nested_promises()
{
  return promise1
    .then(promise2)
    .then(promise3)
    .catch(console.error);
}
```

Example 2:

Using async/await. Using that method I can achieve the same result as above, but this time using the try catch method, kinda uglier if you ask me, but gets the job done.
```js
async function async_await()
{
  try { await promise1() } catch (err) { console.error(err); return; }
  try { await promise2() } catch (err) { console.error(err); return; }
  try { await promise3() } catch (err) { console.error(err); return; }
}
```

Example 3:

This is what I wanted to do, and ask if its actually doable.
```js
async function async_await()
{
  // even if an error gets thrown, it does not return and moves to promise 2.
  await promise1().catch(err =>{ console.error(err); return; }); 
  await promise2().catch(err =>{ console.error(err); return; });
  await promise3().catch(err =>{ console.error(err); return; });
}
```

So to re-cup, Can I somehow using the .catch(e => {}) return from the function if an error gets thrown, and is it actually a thing? 

Why I do not use any of the first two.
Because in the same function I use the values returned from the promises, so If I ignore the catches, with async/await it looks something like this (which would get messy with the first two examples and since this is used on queries, I want to rollback as well in case of error):

```js
async function async_await()
{
  let value1 = await promise1();
  
  if(value1 === X) await promise4();
  else ..

  let value2 = await promise2();
  await promise3(value2);

  return value2;
}
```

**Comment by vsemozhetbyt** [comment]
Would [`Promise.all()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) be helpful?

**Comment by FerX** [comment]
Try 
- https://www.npmjs.com/package/bluebird 
- https://www.npmjs.com/package/p-all

**Comment by Shagon94** [comment]
If you want them to be executed serially the following code might help, but if you want them to be executed in parallel then [Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) would be your next bet.

```js
const a = 42;
const b = Promise.resolve(3);
const c = new Promise((resolve, reject) => {
  return setTimeout(() => resolve('test'), 3000);
});

const promises = [c, a, b];

const result = promises.reduce((prev, current) => {
  return prev.then(() => current);
}, Promise.resolve());

result
  .then(() => console.log(require('util').inspect(promises, { colors: true, depth: null })))
  .catch(e => console.log('error', e));

```

But do note the nature of promises, as described in the mozilla [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise):

> If an error is thrown in the executor function, the promise is rejected. The return value of the executor is ignored.

To test this all you have to do is change line 4 in my example from `resolve` to `reject`

**Comment by gireeshpunathil** [comment]
closing as answered.

**Comment by ORESoftware** [comment]
@TempUserNode 

this:

```js
async function async_await() {
  try { 
    await promise1() 
    await promise2()
    await promise3()
 } 
  catch (err) { 
   console.error(err);
   return; 
 }
}
```

is pretty much equivalent to this:

```js
async function async_await()
{
  try { await promise1() } catch (err) { console.error(err); return; }
  try { await promise2() } catch (err) { console.error(err); return; }
  try { await promise3() } catch (err) { console.error(err); return; }
}
```
