### ISSUE TITLE
Streams and event loop - do data handlers always fire on next tick?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1222]
I have this question:
https://stackoverflow.com/questions/49883626/streams-and-event-loop-do-data-handlers-always-fire-on-next-tick

Say I have a readable stream, like so:

```js
const strm = fs.createReadStream(file);
strm.on('data', function onData(d){});
```

my question is, does the onData callback fire in the next tick of the event loop? Or is it possible for the onData handler to be called twice in the same tick of the event loop?

**Comment by addaleax** [comment]
> Or is it possible for the onData handler to be called twice in the same tick of the event loop?

Yes:

```js
const stream = require('stream');
const readable = new stream.Readable({read(){}});
readable.on('data', () => console.log('data'));
process.nextTick(() => console.log('next tick'));

readable.push('foo');
readable.push('foo');
```

Output:

```
data
data
next tick
```

**Comment by gireeshpunathil** [comment]
closing as answered
