### ISSUE TITLE
Running JS in Android Java app using nodejs-mobile

### ISSUE THREAD

**Issue by adonnini** [nodejs/help#1223]
Hi,

Apologies, if this is not the place to ask this question. If it is not, please let me know where I should ask it.

I need to run a JavaScript in my Android Java app (a blockchain driver). There is no UI. No need/desire to run WebView.

I tried using J2V8. It does not have Android wrappers for running Node.js 

Any help/ideas on how to do this would be greatly appreciated.

Thanks,

Alex Donnini

**Comment by devsnek** [comment]
> I tried using J2V8. It does not have Android wrappers for running Node.js

https://eclipsesource.com/blogs/2016/07/20/running-node-js-on-the-jvm/

hope i helped

**Comment by adonnini** [comment]
Thanks. I am familair with the blog. Unfortunately, it does not solve the problem I have.

When trying to run node.js via J2V8, my app crashes with the following error:

java.lang.UnsupportedOperationException: StartNodeJS Not Supported.

When I brought this to the attention of the folks at EclipseSource, the response was:

"The node wrappers (for running node.js in an android app) are not available on Android, they are only available on the Desktop platforms (windows, mac, linux). This is the expected behaviour until we have node binaries for Android."

My current concern is that J2V8 is basically dormant. It would be a real shame.

I am looking for alternatives. That's what brought me here.

Can you help in any way?

Thanks,

Alex Donnini

**Comment by orangemocha** [comment]
You might want to try https://github.com/janeasystems/nodejs-mobile

**Comment by adonnini** [comment]
Thanks for suggestion.

As they say, been there, done that.

I could be wrong (would love to be wrong). It does not work for Android Java 
applications that need to access complex JS scripts.

Thanks anyway,

Alex Donnini

Alexis Campailla wrote:

**Comment by orangemocha** [comment]
@adonnini running complex JS scripts is no problem. The part that might not be easy out of the box is marshalling data between Java and JavaScript. But it's doable, and there is code that does it in the react-native and cordova plug-ins, that you could copy.
Anyway, nodejs-mobile might be a better place of this discussion 😃

**Comment by adonnini** [comment]
Thank you very much. I will look at the code you suggest. I hope you won't mind if I come back with questions.

Thanks
