### ISSUE TITLE
How to multiplex named pipe / fifo

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1227]
https://stackoverflow.com/questions/49937798/how-to-multiplex-named-pipe-fifo

this doesn't exactly have to do with Node.js, but hoping I can get some answers here..

Say we have a named pipe:

`mkfifo my_named_pipe`

say there are multiple writers writing to this named pipe:

```bash
node x.js > ${my_named_pipe} &
node y.js > ${my_named_pipe} &
node z.js > ${my_named_pipe} &
```

something like that - is there a reliable way to multiplex it, so that one whole message gets through each time, or can a named pipe reliable read from only one writer?

It leads me to wonder how we multiplex ports/sockets etc, I don't know how it's done.

**Comment by bnoordhuis** [comment]
Writes <= `PIPE_BUF` bytes (at least 512 but bigger on some platforms) are atomic and won't be intermixed.

**Comment by ORESoftware** [comment]
@bnoordhuis  interesting, I was guessing that writes _smaller than a certain size_ would be atomic, but you are saying that writes _bigger than a certain size_ will be atomic.

**Comment by ORESoftware** [comment]
@bnoordhuis I am wondering - is that the same way that sockets are multiplexed? By having big enough writes?

**Comment by bnoordhuis** [comment]
Yes, that's right.  And yes, the "at least 512" means you can assume writes <= 512 will be atomic everywhere.  Larger writes may be atomic too but that depends on the platform.

**Comment by ORESoftware** [comment]
@bnoordhuis  how do I discover what the value is for PIPE_BUF on Ubuntu or MacOS?

if I use echo $PIPE_BUF, that yields nothing

is there a way to set the value to something bigger for a specific named pipe?

**Comment by bnoordhuis** [comment]
> how do I discover what the value is for PIPE_BUF on Ubuntu or MacOS?

`grep -wr PIPE_BUF /usr/include` should find it.

> is there a way to set the value to something bigger for a specific named pipe?

I don't think so.  Nothing that's portable anyway.

**Comment by gireeshpunathil** [comment]
closing as answered.
