### ISSUE TITLE
http.get

### ISSUE THREAD

**Issue by josh4trunks** [nodejs/help#1229]
* **Node.js 8.10**:
* **AWS Lambda**:

I am very new to javascript so I am probably making some glaring mistakes; I just started by writing this Amazon Alexa skill yesterday.
I am trying to write an Amazon Alexa Skill for my Echo. I need the skill to browse to a specific URL, then pass some canned data as a response to the Amazon Smart Home API. I do not want or need to get any data from the URL.

Looking at the documentation it looks like `http.get(options[, callback])` could be run with just a URL. I tried this but it does not seem to run. It does run when I `return http.get('http://www.example.com/echo/run-script');` but then my script script exits and does not pass the canned data to the Amazon Smart Home API.

How do I get the below http.get to run? Thank you
```js
var http = require('http');
http.get('http://www.example.com/echo/run-script');
```

**Comment by Shagon94** [comment]
In the documentation [here](https://nodejs.org/api/http.html#http_http_get_options_callback), it says that `http.get` also accepts a callback, since it is an asynchronous operation it takes some amount of time to complete.

First off, we don't know how your script looks like and how your server behaves, but I think what you want to do. In your code:
```js
return http.get('http://www.example.com/echo/run-script');
```
All you did is fire a HTTP GET request to the URL, your server must do all other work, since you said that you don't want or need any data from the URL I suspect that the script in question does all the work for the Alexa skill. Just getting the script via that url doesn't mean it will run, if it is a `.sh` or similar it won't run automatically without any server work on your part, it is practically the same as getting an image.

I suggest setting up an express server on your server that will listen on that route for request, and then when a request triggers it just fire the script you have. If the script in question is written in a different language or you just don't want to do any more work, you can just fork a child process and let it execute the script for you.

[here](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) is the documentation for the function in question, and here is some example code:

```js
const { exec } = require('child_process');
const scriptToExecute = '/bin/ls';
exec(scriptToExecute, {});
```

If you do care about the output of the script all you have to do is pass the callback function like so:

```js
const { exec } = require('child_process');
const script = '/Users/Name/script.sh';
exec(script, (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
});
```

**Comment by josh4trunks** [comment]
Thanks @Shagon94 
As you said, all the work is done on my webserver at my home. All I need is to browse to either URL.
* browsing to `/echo/tv-on` has nginx use lua to execute the 'wake' command to wakeup my HTPC
* browsing to `/echo/tv-on` has nginx proxy_pass's the request and adds an argument to suspend my HTPC using the Kodi API over HTTP

It seems like the Lambda service doesn't run the http.get command, maybe because it is async it finishes the rest of the script before executing. Here is the full script...
```js
exports.handler = function (request, context) {
    if (request.directive.header.namespace === 'Alexa.Discovery' && request.directive.header.name === 'Discover') {
        log("DEBUG:", "Discover request",  JSON.stringify(request));
        handleDiscovery(request, context, "");
    }
    else if (request.directive.header.namespace === 'Alexa.PowerController') {
        if (request.directive.header.name === 'TurnOn' || request.directive.header.name === 'TurnOff') {
            log("DEBUG:", "TurnOn or TurnOff Request", JSON.stringify(request));
            handlePowerControl(request, context);
        }
    }

    function handleDiscovery(request, context) {
        var payload = {
            "endpoints":
            [
                {
                    "endpointId": "TV",
                    "friendlyName": "TV",
                    "description": "Television",
                    "capabilities":
                    [
                        {
                          "interface": "Alexa",
                          "type": "AlexaInterface",
                          "version": "3"
                        },
                        {
                            "interface": "Alexa.PowerController",
                            "type": "AlexaInterface",
                            "version": "3",
                            "properties": {
                                "supported": [{
                                    "name": "powerState"
                                }],
                                "retrievable": true
                            }
                        }
                    ]
                }
            ]
        };
        var header = request.directive.header;
        header.name = "Discover.Response";
        log("DEBUG", "Discovery Response: ", JSON.stringify({ header: header, payload: payload }));
        context.succeed({ event: { header: header, payload: payload } });
    }

    function log(message, message1, message2) {
        console.log(message + message1 + message2);
    }

    function handlePowerControl(request, context) {
        var http = require('http');
        var requestMethod = request.directive.header.name;
        var powerResult;

        if (requestMethod === "TurnOn") {
            req.get('http://www.example.com/echo/tv-on');
            powerResult = "ON";
        }
        else if (requestMethod === "TurnOff") {
            req.get('http://www.example.com/echo/tv-off');
            powerResult = "OFF";
        }
        var contextResult = {
            "properties": [{
                "namespace": "Alexa.PowerController",
                "name": "powerState",
                "value": powerResult
            }]
        };
        var responseHeader = request.directive.header;
        responseHeader.namespace = "Alexa";
        responseHeader.name = "Response";
        responseHeader.messageId = responseHeader.messageId + "-R";
        var response = {
            context: contextResult,
            event: {
                header: responseHeader
            },
            payload: {}

        };
        log("DEBUG", "Alexa.PowerController ", JSON.stringify(response));
        context.succeed(response);
    }
};
```

**Comment by Shagon94** [comment]
I think because it doesn't wait for the machine to fully power on, I mean, you do a request that turns it on, but that too is asynchronous, it takes time to boot up, you can try adding `setTimeout` like this:

```js
...code


        if (requestMethod === "TurnOn") {
            http.get('http://www.example.com/echo/tv-on');
            powerResult = "ON";
        }
        else if (requestMethod === "TurnOff") {
            http.get('http://www.example.com/echo/tv-off');
            powerResult = "OFF";
      }
      const numberOfMilisecondsToWait = 10000;
      setTimeout(() => {
        var contextResult = {
          "properties": [{
            "namespace": "Alexa.PowerController",
            "name": "powerState",
            "value": powerResult
          }]
        };
        var responseHeader = request.directive.header;
        responseHeader.namespace = "Alexa";
        responseHeader.name = "Response";
        responseHeader.messageId = responseHeader.messageId + "-R";
        var response = {
          context: contextResult,
          event: {
            header: responseHeader
          },
          payload: {}

        };
        log("DEBUG", "Alexa.PowerController ", JSON.stringify(response));
        context.succeed(response);
      }, numberOfMilisecondsToWait);
    }
};
```

**Comment by josh4trunks** [comment]
got it working. just split the http.get part from the response part into 2 different functions.

Thanks, for the help. reading through what you wrote helped lead me to my solution.

**Comment by josh4trunks** [comment]
I don't actually check if the command worked. so waiting to boot up is irrelevant.

**Comment by josh4trunks** [comment]
So I am still having a lot of trouble with this. I had it working, but it no longer seems to work. I believe what is happening is the **http.get** is not completing in time (takes 300-500ms) before `context.succeed` is being run ~200ms.

How could I simply run `handleResponse` after `handlePowerControl`? I was trying to make handleResponse an on('end') callback to the http.get but could not get it to working.
Thank you

```js
exports.handler = function (request, context) {
    if (request.directive.header.namespace === 'Alexa.Discovery' && request.directive.header.name === 'Discover') {
        log("DEBUG:", "Discover request",  JSON.stringify(request));
        handleDiscovery(request, context, "");
    }
    else if (request.directive.header.namespace === 'Alexa.PowerController') {
        log("DEBUG:", "TurnOn or TurnOff Request", JSON.stringify(request));
        handlePowerControl(request, context);
    }

    function handleDiscovery(request, context) {
        var payload = {
            "endpoints":
            [
                {
                    "endpointId": "roseparade_tv",
                    "manufacturerName": "JRuehlig Technologies",
                    "friendlyName": "TV",
                    "description": "Television",
                    "displayCategories": ["SWITCH"],
                    "capabilities":
                    [
                        {
                          "interface": "Alexa",
                          "type": "AlexaInterface",
                          "version": "3"
                        },
                        {
                            "interface": "Alexa.PowerController",
                            "type": "AlexaInterface",
                            "version": "3",
                            "properties": {
                                "supported": [{
                                    "name": "powerState"
                                }],
                            }
                        }
                    ]
                }
            ]
        };
        var header = request.directive.header;
        header.name = "Discover.Response";
        log("DEBUG", "Discovery Response: ", JSON.stringify({ header: header, payload: payload }));
        context.succeed({ event: { header: header, payload: payload } });
    }
    
    function log(message, message1, message2) {
        console.log(message + message1 + message2);
    }

    function handlePowerControl(request, context) {
        var requestMethod = request.directive.header.name;
        var controlURL;
        var powerResult;
        if (requestMethod === "TurnOn") {
            controlURL = 'http://example.com/echo/tv-on';
            powerResult = "ON";
        }
        else if (requestMethod === "TurnOff") {
            controlURL = 'http://example.com/echo/tv-off';
            powerResult = "OFF";
        }
        require('http').get(controlURL);
    }
        
    function handleResponse(request, context, powerResult) {
        var responseHeader = request.directive.header;
        var contextResult = {
            "properties": [{
                "namespace": "Alexa.PowerController",
                "name": "powerState",
                "value": powerResult
            }]
        };
        responseHeader.namespace = "Alexa";
        responseHeader.name = "Response";
        responseHeader.messageId = responseHeader.messageId + "-R";
        var response = {
            context: contextResult,
            event: {
                header: responseHeader
            },
            payload: {}
        };
        log("DEBUG", "Alexa.PowerController ", JSON.stringify(response));
        context.succeed(response);
    }
};
```

**Comment by Shagon94** [comment]
Since `http.get` has a callback function when finished you can refactor your code like this:

```js
    function handlePowerControl(request, context) {
        var http = require('http');
        var requestMethod = request.directive.header.name;
        var controlURL;
        var powerResult;
        if (requestMethod === "TurnOn") {
            controlURL = 'http://example.com/echo/tv-on';
            powerResult = "ON";
        }
        else if (requestMethod === "TurnOff") {
            controlURL = 'http://example.com/echo/tv-off';
            powerResult = "OFF";
        }
       http.get(controlURL, function (result) {
           console.log('the code in this block will only execute when http get request has a response from the server');
           console.log('so when a response has been returned by the server we can simply just run another asynchronous operation in here and know it will only run after the first one has been done');
           handleResponse();
       });
    }

```

**Comment by josh4trunks** [comment]
so i have definitely tried that, and other similar iterations to get `handleResponse()` called as a callback to http.get
I think the environment causes some things to act differently than expected as I have read others having similar issues using http.get and returning a response.
https://stackoverflow.com/questions/42424614/how-do-i-create-an-alexa-skill-that-gets-data-from-an-http-https-api-using-ale

I'll post my own attempt and maybe you or someone else can see if I'm making any obvious mistakes.

**Comment by Shagon94** [comment]
You can use the [r2](https://www.npmjs.com/package/r2) and try with that, since its a A+ Promise you can just create an async function and try your luck with it, but I doubt its the http get issue, but as I said, you can try with `r2`, they have good documentation, but in your case I can give you some sample code:

```js
    async function handlePowerControl(request, context) {
        var r2 = require('r2');
        var requestMethod = request.directive.header.name;
        var controlURL;
        var powerResult;
        if (requestMethod === "TurnOn") {
            controlURL = 'http://example.com/echo/tv-on';
            powerResult = "ON";
        }
        else if (requestMethod === "TurnOff") {
            controlURL = 'http://example.com/echo/tv-off';
            powerResult = "OFF";
        }
        await r2(controlURL); // the await keyword makes the program wait for the request to finish before continuing
        console.log('this console log will execute when the request finishes');
    }
```

**Comment by josh4trunks** [comment]
It seems like everything it working now with a callback like you mentioned https://github.com/nodejs/help/issues/1229#issuecomment-383799998.
I think it wasn';t working before because I was calling the function and not passing everything I needed to. Instead I just pasted the contents of `handleResponse` as the http.get callback and it works well.
Thanks!

**Comment by gireeshpunathil** [comment]
closing then.

**Comment by 27andrea** [comment]
Hi,i had the same issue and solved with the handle response but when I say Alexa start device x ,Alexa say that the device don't answer...
my code is:


`exports.handler = function (request, context) {
    if (request.directive.header.namespace === 'Alexa.Discovery' && request.directive.header.name === 'Discover') {
        log("DEBUG:", "Discover request",  JSON.stringify(request));
        handleDiscovery(request, context, "");
    }
    else if (request.directive.header.namespace === 'Alexa.PowerController') {
        if (request.directive.header.name === 'TurnOn' || request.directive.header.name === 'TurnOff') {
            log("DEBUG:", "TurnOn or TurnOff Request", JSON.stringify(request));
            handlePowerControl(request, context);
        }
    }

    function handleDiscovery(request, context) {
        var payload = {
            "endpoints":
            [
                {
                    "endpointId": “room",
                    "manufacturerName": "Smart Device Company",
                    "friendlyName": “room",
                    "description": "Smart Device Switch",
                    "displayCategories": ["SWITCH"],
                    "cookie": {
                        "key1": "arbitrary key/value pairs for skill to reference this endpoint.",
                        "key2": "There can be multiple entries",
                        "key3": "but they should only be used for reference purposes.",
                        "key4": "This is not a suitable place to maintain current endpoint state."
                    },
                    "capabilities":
                    [
                        {
                          "type": "AlexaInterface",
                          "interface": "Alexa",
                          "version": "3"
                        },
                        {
                            "interface": "Alexa.PowerController",
                            "version": "3",
                            "type": "AlexaInterface",
                            "properties": {
                                "supported": [{
                                    "name": "powerState"
                                }],
                                 "retrievable": true
                            }
                        }
                    ]
                },{
                    "endpointId": “room2",
                    "manufacturerName": "Smart Device Company",
                    "friendlyName": “room2",
                    "description": "Smart Device Switch",
                    "displayCategories": ["SWITCH"],
                    "cookie": {
                        "key1": "arbitrary key/value pairs for skill to reference this endpoint.",
                        "key2": "There can be multiple entries",
                        "key3": "but they should only be used for reference purposes.",
                        "key4": "This is not a suitable place to maintain current endpoint state."
                    },
                    "capabilities":
                    [
                        {
                          "type": "AlexaInterface",
                          "interface": "Alexa",
                          "version": "3"
                        },
                        {
                            "interface": "Alexa.PowerController",
                            "version": "3",
                            "type": "AlexaInterface",
                            "properties": {
                                "supported": [{
                                    "name": "powerState"
                                }],
                                 "retrievable": true
                            }
                        }
                    ]
                }
            ]
        };
        var header = request.directive.header;
        header.name = "Discover.Response";
        log("DEBUG", "Discovery Response: ", JSON.stringify({ header: header, payload: payload }));
        context.succeed({ event: { header: header, payload: payload } });
    }
    function log(message, message1, message2) {
        console.log(message + message1 + message2);
}
   
    function handlePowerControl(request, context) {
        // get device ID passed in during discovery
                var http = require('http');

        var requestMethod = request.directive.header.name;
        var responseHeader = request.directive.header;
        responseHeader.namespace = "Alexa";
        responseHeader.name = "Response";
        responseHeader.messageId = responseHeader.messageId + "-R";
        // get user token pass in request
        var requestToken = request.directive.endpoint.scope.token;
        var powerResult;  
        var url='';
        var url;
        if (requestMethod === "TurnOn") {
                              url = 'http://api.api.com/user/light.cgi?type=lights&number=1';

             powerResult = "ON";
        }
       else if (requestMethod === "TurnOff") {
                              url = 'http://api.api.com/user/light.cgi?type=lights&number=0';

            powerResult = "OFF";
        }
         http.get(url, function (result) {
           handleResponse();
       });
}
function handleResponse(request, context, powerResult) {
             var contextResult = {
            "properties": [{
                "namespace": "Alexa.PowerController",
                "name": "powerState",
                "value": powerResult
            }]
        };
        var responseHeader = request.directive.header;
        responseHeader.namespace = "Alexa";
        responseHeader.name = "Response";
        responseHeader.messageId = responseHeader.messageId + "-R";
        var response = {
            context: contextResult,
            event: {
                header: responseHeader
            },
            payload: {}
        };
        log("DEBUG", "Alexa.PowerController ", JSON.stringify(response));
        context.succeed(response);
    }
    
    
};
    `


here the error on cloud watch
`2019-09-05T20:09:37.936Z	0bf1f96f-378d-48a8-9a9d-6f3cfb815446	ERROR	Uncaught Exception
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'directive' of undefined",
    "stack": [
        "TypeError: Cannot read property 'directive' of undefined",
        "    at handleResponse (/var/task/index.js:129:38)",
        "    at ClientRequest.<anonymous> (/var/task/index.js:118:12)",
        "    at Object.onceWrapper (events.js:286:20)",
        "    at ClientRequest.emit (events.js:198:13)",
        "    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)",
        "    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)",
        "    at Socket.socketOnData (_http_client.js:442:20)",
        "    at Socket.emit (events.js:198:13)",
        "    at addChunk (_stream_readable.js:288:12)",
        "    at readableAddChunk (_stream_readable.js:269:11)"
    ]
}
`
can you help me?
thanks

**Comment by 27andrea** [comment]
Solved

**Comment by harishajankar** [comment]
PLEASE SOLVE MY PROBLEM RELATED REPORTSTATE
var https = require('https');
var firebaseHost = "saprahas-d6d9e.firebaseio.com"; 



exports.handler = function (request, context) {
    if (request.directive.header.namespace === 'Alexa.Discovery' && request.directive.header.name === 'Discover') {
        log("DEBUG:", "Discover request",  JSON.stringify(request));
        handleDiscovery(request, context, "");
    }
    else if (request.directive.header.namespace === 'Alexa.PowerController') {
        if (request.directive.header.name === 'TurnOn' || request.directive.header.name === 'TurnOff') {
            log("DEBUG:", "TurnOn or TurnOff Request", JSON.stringify(request));
            handlePowerControl(request, context);
        }
    }

    function handleDiscovery(request, context) {
        var payload = {
            "endpoints":
            [
                {
                    "endpointId": "demo_id",
                    "manufacturerName": "saprahas",
                    "friendlyName": "Bedroom Outlet",
                    "description": "Smart Device Switch",
                    "displayCategories": ["SWITCH"],
                   
                    "capabilities":
                    [
                        {
                          "type": "AlexaInterface",
                          "interface": "Alexa",
                          "version": "3"
                        },
                        {
                            "interface": "Alexa.PowerController",
                            "version": "3",
                            "type": "AlexaInterface",
                            "properties": {
                                "supported": [{
                                    "name": "powerState"
                                }],
                                 "retrievable": true
                            }
                        }
                    ]
                }
            ]
        };
        var header = request.directive.header;
        header.name = "Discover.Response";
        log("DEBUG", "Discovery Response: ", JSON.stringify({ header: header, payload: payload }));
        context.succeed({ event: { header: header, payload: payload } });
    }

    function log(message, message1, message2) {
        console.log(message + message1 + message2);
    }

    function handlePowerControl(request, context) {
        // get device ID passed in during discovery
        
        var requestMethod = request.directive.header.name;
        var responseHeader = request.directive.header;
        responseHeader.namespace = "Alexa";
        responseHeader.name = "Response";
        responseHeader.messageId = responseHeader.messageId + "-R";
        // get user token pass in request
        var requestToken = request.directive.endpoint.scope.token;
        var powerResult;

        if (requestMethod === "TurnOn") {

            // Make the call to your device cloud for control
            // powerResult = stubControlFunctionToYourCloud(endpointId, token, request);
            powerResult = "ON";
             fbPut("/foo/bar",powerResult ).then(data => {
  console.log(data); // prints "lol"
}).catch(e => {
  console.log("error saving to firebase: ");
  console.log(e);
})
        }
      else if (requestMethod === "TurnOff") {
            // Make the call to your device cloud for control and check for success
            // powerResult = stubControlFunctionToYourCloud(endpointId, token, request);
            powerResult = "OFF";
             fbPut("/foo/bar",powerResult ).then(data => {
  console.log(data); // prints "lol"
}).catch(e => {
  console.log("error saving to firebase: ");
  console.log(e);
})
        }
        var contextResult = {
            "properties": [{
                "namespace": "Alexa.PowerController",
                "name": "powerState",
                "value": powerResult,
                "timeOfSample": "2017-09-03T16:20:50.52Z", //retrieve from result.
                "uncertaintyInMilliseconds": 50
            }]
        };
        var response = {
            context: contextResult,
            event: {
                header: responseHeader,
                endpoint: { 
                    scope: {
                        type: "BearerToken",
                        token: requestToken
                    },
                    endpointId: "demo_id"
                },
                payload: {}
            }
        };
        log("DEBUG", "Alexa.PowerController ", JSON.stringify(response));
        context.succeed(response);
    }
};




function fbGet(key){
  return new Promise((resolve, reject) => {
    var options = {
      hostname: firebaseHost,
      port: 443,
      path: key + ".json",
      method: 'GET'
    };
    var req = https.request(options, function (res) {
      res.setEncoding('utf8');
      var body = '';
      res.on('data', function(chunk) {
        body += chunk;
      });
      res.on('end', function() {
        resolve(JSON.parse(body))
      });
    });
    req.end();
    req.on('error', reject);
  });
}

function fbPut(key, value){
  return new Promise((resolve, reject) => {
    var options = {
      hostname: firebaseHost,
      port: 443,
      path: key + ".json",
      method: 'PUT'
    };

    var req = https.request(options, function (res) {
      console.log("request made")
      res.setEncoding('utf8');
      var body = '';
      res.on('data', function(chunk) {
        body += chunk;
      });
      res.on('end', function() {
        resolve(body)
      });
    });
    req.end(JSON.stringify(value));
    req.on('error', reject);
  });
}





//-------Helper Methods---------//
function onLaunch(callback) {
    var output = "Welcome to trial firebase skill . what action did you want to perform . ";
    var endSession = false;
    callback(buildSpeechletResponse(output, endSession));
}

function buildSpeechletResponse(output, shouldEndSession) {
    return {
        outputSpeech: {
            type: "PlainText",
            text: output
        },
        shouldEndSession: shouldEndSession
    };
}

function buildResponse(speechletResponse) {
    return {
        version: "1.0",
        response: speechletResponse
    };
}
