### ISSUE TITLE
Log down Expressjs response 

### ISSUE THREAD

**Issue by kkc** [nodejs/help#123]
I am searching the way to log down expressjs response, and I know I should use middleware to capture response while `res.finish` has been called.
Message with string format is okay. But when it becomes Buffer format, I can't convert it back to string.

Following is my code:
```js
function logdown = {
return function(req, res, next) {
      var chunks = [];
      var oldWrite = res.write;
      res.write = function (chunk, encoding) {
        if (Buffer.isBuffer(chunk)) {
          console.log(chunk.toString('utf8'));
        }
        if (chunk) chunks.push(chunk);

        oldWrite.apply(res, arguments);
      };

      var oldEnd = res.end;
      res.end = function(chunk, encoding) {
        if (Buffer.isBuffer(chunk)) {
          console.log(chunk.toString(encoding));
        }
        if (chunk) { chunks.push(chunk); }

        oldEnd.apply(res, arguments);
      };

      res.once('finish', function logIt() {
        console.log(chunks);
      }
}
}
```

want to know the right way to docode Buffer
Thx a lot

**Comment by Fishrock123** [comment]
```js
if (Buffer.isBuffer(chunk)) {
    console.log(chunk.toString(encoding));
}
```

Looks about right. Usually you'll do `buffer.toString('utf8')`.

**Comment by kkc** [comment]
@Fishrock123 thx, but I still can't get proper response, it's always garbled code...

**Comment by subfuzion** [comment]
@kkc, are you talking about not getting a proper response when you handle `'finish`'? You are printing an array of chunks (Buffers).

Try this instead:

```
res.once('finish', function logIt() {
  console.log(Buffer.concat(chunks).toString('utf8'));
});
```

**Comment by subfuzion** [comment]
@kkc Let me know if that helped so I can close this issue. Thanks!

**Comment by lordKnighton** [comment]
gonna close for now, reopen to pursue. 

happy coding 😃
