### ISSUE TITLE
How to read a timestamp from a Buffer using the native API?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [nodejs/help#1231]
Background
--------
I am reading buffers using the Node.js buffer native API. This API has two functions called `readUIntBE` and `readUIntLE` for Big Endian and Little Endian respectively. 

https://nodejs.org/api/buffer.html#buffer_buf_readuintbe_offset_bytelength_noassert

Problem
---------

By reading the docs, I stumbled upon the following lines:

 - byteLength <integer> Number of bytes to read. Must satisfy: 0 < byteLength <= 6.

If I understand correctly, this means that I can only read 6 bytes at a time using this function, which makes it useless for my use case, as I need to read a timestamp comprised of 8 bytes.

Originally I thought this was a typo in the docs, but after getting a response from @BridgeAR  it was clear this is intended behavior: 

 - https://github.com/nodejs/node/issues/20249#issuecomment-383899009

He mentions that I can  read multiple entries by adding the offset, but it is not clear to me how this could be done. 

Questions
----
1. How can you read a timestamp that is more that 6 bytes long by continuously adding the offset?

**Comment by Fl4m3Ph03n1x** [comment]
Waiting for `BigInt` is not an option, nor is any loss of precision. I guess that instead of reading it as a Number I could just get a String that represents that timestamp? Would this be possible?

**Comment by addaleax** [comment]
I mean, if you just need some way to represent it, you can store an array with two 32-bit integer entries; that works and is reasonably fast, and not an uncommon pattern work around this limitation. The downside that it’s not going to be enough if you actually want to display data in a human-readable format.

I don’t know of any code that converts between a decimal string and a 64-bit representation, but I’m sure it’s possible if one wants to write it. :)

**Comment by apapirovski** [comment]
Seems like this could be solved by https://github.com/kawanet/int64-buffer?

**Comment by Fl4m3Ph03n1x** [comment]
Well, for the time being I just convert the 8 bytes to an HEX string. 
Then I use a function that converts that HEX string, char by char, into a DEC number. 

I believe that for 8 byte numbers it works without loss of precision:
```

//https://www.rapidtables.com/convert/number/hex-to-decimal.html
const hexToDec = hex => {

    const hexMap = new Map([
        [ "0", 0 ],
        [ "1", 1 ],
        [ "2", 2 ],
        [ "3", 3 ],
        [ "4", 4 ],
        [ "5", 5 ],
        [ "6", 6 ],
        [ "7", 7 ],
        [ "8", 8 ],
        [ "9", 9 ],
        [ "A", 10 ],
        [ "B", 11 ],
        [ "C", 12 ],
        [ "D", 13 ],
        [ "E", 14 ],
        [ "F", 15 ],
    ]);

    let dec = 0;
    let power = hex.length - 1;
    for( const char of hex ){
        dec += hexMap.get( char.toUpperCase() ) * Math.pow( 16, power );
        power--;
    }

    return dec;
};

```

I am definitely open to feedback, although if you guys want we can close this as I believe it may be getting of scope for what this github is for.

**Comment by apapirovski** [comment]
I don't believe that's safe in JavaScript, e.g. `Math.pow(2, 53) === Math.pow(2, 53) + 1`

**Comment by Fl4m3Ph03n1x** [comment]
@apapirovski Oh Dear God, the calamity. You gotta be kidding me. This is most definitely **not** safe. 
Question is... could it be safe for 8 byte Numbers? 

I argue that *yes*, because 8 byte numbers generate HEX string with a total of 10 positions. Therefore, because `Math.pow(2, 10) === Math.pow(2, 10) + 1` returns `false`, no loss of precision happens. 

Am I correct i my assumption?

**Comment by Fl4m3Ph03n1x** [comment]
@apapirovski You are correct ... back to stage 1. 
You guys have helped me enough, I now have a clearer understanding of the problem I have. Just need to find a solution, but this is my fight, not yours :P

I will mark it as closed. Thanks for the help!

**Comment by apapirovski** [comment]
@Fl4m3Ph03n1x I think the two projects I linked above should work. They do bring an extra dependency with them but that's probably unavoidable if you don't want to re-do all that work. Good luck either way.

Also just a friendly note for the future: lots of the people involved here aren't "guys" and we try to avoid using exclusionary terminology as much as possible. Thanks!

**Comment by Fl4m3Ph03n1x** [comment]
> Also just a friendly note for the future: lots of the people involved here aren't "guys" and we try to avoid using exclusionary terminology as much as possible. Thanks!

AHhh, I meant no offense at all. I guess it's just a culture thing, where I come from no one feels excluded by the usage of such terminology, although I totally understand where you are coming from and I will be more careful in the future. 

The point I wanted to make obvious is that I am grateful for all the help you wonderful people gave me, and I wanted to leave a comment stating that!

Dully noted!
