### ISSUE TITLE
Inspector question

### ISSUE THREAD

**Issue by mathiask88** [nodejs/help#1233]
* **Node.js Version**: 9.11.1
* **OS**: Win10 x64
* **Scope (install, code, runtime, meta, other?)**: Inspector

I recently tried the node inspector and I had some behavior that I don't understand. Following code:

```js
const snap7 = require('node-snap7'); // native module
const s7server = new snap7.S7Server(); // NAN Object-Wrap

s7server.SetResourceless(true);

s7server.on("readWrite", function(sender, operation, tagObj, buffer, callback) {
  console.log((operation === s7server.operationRead ? 'Read' : 'Write') + ' event from ' + sender);
  console.log('Area     : ' + tagObj.Area);
  console.log('DBNumber : ' + tagObj.DBNumber);
  console.log('Start    : ' + tagObj.Start);
  console.log('Size     : ' + tagObj.Size);
  console.log('WordLen  : ' + tagObj.WordLen);

  if (operation === s7server.operationRead) {
    buffer.fill(255);
    return callback(buffer);
  } else {
    console.log('Buffer   : ' + buffer);
    return callback();
  }
});

s7server.SetParam(s7server.LocalPort, 3333);
s7server.StartTo('127.0.0.1');
```

starts a Siemens S7 server. The `StartTo()` method calls a `uv_ref()` so the event loop keeps running. If I start this code with `--inspect` everything works as expected. But when I connect the chrome inspector a garbage collection is triggered and V8 destructs the `s7server` object. What is the reason behind this? Isn't there an active reference with the `s7server` constant? A solution would be to `Ref()` the `Nan::ObjectWrap`. I thought this is not necessary, but now I think I am wrong :)

**Comment by bnoordhuis** [comment]
An `ObjectWrap` (either nan's or node's) starts out weakly persistent and is therefore eligible for garbage collection.  Calling `Ref()` makes it strong.

It looks like there are no references in your example that keep the object alive.  If you want a simple sanity check, try if it works when you add a `global.s7server = s7server;` statement.

**Comment by mathiask88** [comment]
> An ObjectWrap (either nan's or node's) starts out weakly persistent and is therefore eligible for garbage collection. Calling Ref() makes it strong.

Yes, I read this in the NAN docs, but I thought the `const s7server = new snap7.S7Server();` counts as active reference so that the object won't be garbage collected. You were right with the `global.s7server = s7server;` reference. Thank you for the quick response!
