### ISSUE TITLE
How can one detect when file being transferring from one directory to another is completed 

### ISSUE THREAD

**Issue by Akumzy** [nodejs/help#1234]
* **Node.js Version 8.2.1**:
* **OS window, mac, linux**:
* **Electron   1.8.4**:

I have an electron app that's watching a specific directory in the user machine for any change.
The file watch is working fine but the problem am facing right now is 
when you're copying, moving or transferring a very large single file it normally takes time to complete.
Event will be triggered but the actual file will be empty 
Is there a way I can to detect file transfer is done.

**Comment by ORESoftware** [comment]
@Akumzy can you include/show the watch process? I have an idea.

I have hooked into watch processes before. Usually you have to read from their stdout. Everytime the watcher does an action, it usually writes to stdout, you parse that to determine when it starts/ends a cycle.

**Comment by Akumzy** [comment]
Mmmh ok @ORESoftware

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if anything outstanding.
