### ISSUE TITLE
Is there any switch way to change nodejs to work synchronously by default?

### ISSUE THREAD

**Issue by ezequias** [nodejs/help#1235]
Hi

I would like to know if there is a way to work synchronously without need to use the async library?

I am facing various problems regarding this issue.

Sincerely
Ezequias.

**Comment by vsemozhetbyt** [comment]
Can you elaborate or add some examples of the code or use cases?

**Comment by ezequias** [comment]
Dear @vsemozhetbyt 

I am running a batch process from a list in node with many requests to a remote webservice and at some point the async lib starts to work asynchronously.

I would like to know why nodejs is set to work asynchronously by default. In backends we do encounter many cases we need a synchronous behaviour much more than at frontend.

Ezequias.

**Comment by vsemozhetbyt** [comment]
Well, we have synchronous methods for `fs`, but it seems we have not them for `http` module.

Can async-await functions with `for-await-of` help in your cases?

**Comment by FerX** [comment]
use async function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

or if you use fs look: https://www.npmjs.com/package/fs-extra#sync

**Comment by ORESoftware** [comment]
@ezequias async.autoInject is by far the most superior async utility, far better than async.waterfall

https://caolan.github.io/async/autoInject.js.html

trust me, I have been using the async lib for almost 3 years now

**Comment by ORESoftware** [comment]
@ezequias if you want a good example of that, see:
https://github.com/ORESoftware/ts-project/blob/master/lib/index.ts

**Comment by ezequias** [comment]
We find the solution using version 8 but I believe that 7.6.6 and using "asinc function" with await will works fine also.

Thank you all.
