### ISSUE TITLE
Docs missing for net.Socket .pipe() ?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [nodejs/help#1236]
I am reading the Net documentation for Node in order to create a socket server:
 - https://nodejs.org/api/net.html

One of the first things I do is to try and understand the docs and code snippets. There is a special code snippet that caught my attention:
 - https://nodejs.org/api/net.html#net_net_createserver_options_connectionlistener

```
const server = net.createServer((c) => {
  // 'connection' listener
  console.log('client connected');
  c.on('end', () => {
    console.log('client disconnected');
  });
  c.write('hello\r\n');
  c.pipe(c);
});
```

`c.on` is for events, `c.write` [is documented](https://nodejs.org/api/net.html#net_socket_write_data_encoding_callback), but after searching the entire documentation page I can't find any entry for `c.pipe`.

If I get it right, `c` is a [net.Socket object](https://nodejs.org/api/net.html#net_event_connection).

So, from that example I expect this method to be documented under:

https://nodejs.org/api/net.html#net_class_net_socket

But that is not the case.
Am I missing something or is the documentation incomplete?

**Comment by addaleax** [comment]
From the docs you linked (emphasis by me):

> A `net.Socket` is also a [**duplex stream**](https://nodejs.org/api/stream.html#stream_class_stream_duplex), so it can be both readable and writable, and it is also a [`EventEmitter`](https://nodejs.org/api/events.html#events_class_eventemitter).

I admit that it’s not displayed very prominently, but generally, the idea is that `net.Socket` inherits from `stream.Duplex` inherits from `stream.Readable`. The docs for `readable.pipe()` are [here](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options).

If you have ideas for how to make this more obvious, feel free to raise them (or maybe even open a PR with them, if you want).

**Comment by Fl4m3Ph03n1x** [comment]
AHhh, that makes sense.
As far as suggestions go, the only thing I can think of would be to have it like the following:

> Class: net.Socket, Implements A, B, C

A more detailed option can be seen in the javadocs. As an example we can check this `window` object:

https://docs.oracle.com/javase/7/docs/api/java/awt/Window.html

I am not suggesting to copy the entire format, but it is my subjective opinion that putting such information in the Headers would make it more clear.

Anyway, it now clear that the documentation is complete and ( again ) this was an user issue :P

Thanks for the super sonic response!
