### ISSUE TITLE
socket: (10050) A socket operation encountered a dead network (originally posted at nodejs/node repo, but redirected here)

### ISSUE THREAD

**Issue by user928782** [nodejs/help#1240]
* **Node.js Version**: 10.0.0
* **OS**: windows 7 32bit
* **Scope (install, code, runtime, meta, other?)**: have no idea
* **Module (and version) (if relevant)**: what?

original issue: https://github.com/nodejs/node/issues/20354
@bnoordhuis said that I should open issue here if I cannot solve the problem.

First, I need to correct myself, when bnoordhuis asked what does "node -v" print, I didn't understand their question. I understood it like "what does it print in general (i.e. what is your version)", and I just responded without even typing node-v into command prompt.

Actually, i now typed literally "node -v" into cmd and it didn't print v10.0.0, but instead it displays the same error. But I installed version 10.0.0 and installer said "successfully installed", but node still dont working.

If this is not printed by node.js, and instead by msvcrt or winsock, how can i remove these two programs/ I am sure i dind't install any extra software, I just installed windows 7 from iso file and then installed node, so no single other file is installed, I didn't change firewall or proxy, or any other windows feature. Just clean windows system, no single other programs and node.js installed and thats it.

i searched in meanwhile on internet, but couldnt find solution, they are suggesting to change firewall setting, i have no idea how to do it. I didn't touch firewall, so i am surprised it is by default wrongly configured. But maybe firewall is not problem at all, maybe node.js depends on some other programs which require some conditions to be fullfiled, but i have no idea which ones. Is there a way to solve this somehow?

Just to mention, node works good on my windows 10 computer, i installed windows from iso file, and then installed node.js and works awesomely, but on windows 7 computer it dont working.

thanks much for any help!

**Comment by gireeshpunathil** [comment]
are you able to access the network through other means? for example:
 - does `ping www.google.com` work?
 - does your browser load web pages properly?

As already mentioned, Node.js just relays the low level error messages when it gets one.

all searches for this error message relate to corrupt antivirus stack. Can you see if your antibirus suite is healthy?

**Comment by user928782** [comment]
> does ping www.google.com work?

No, I don't have internet connection at all. My computer is not connected on internet.

> does your browser load web pages properly?

I don't have any browsers installed.

> Can you see if your antivirus suite is healthy?

I don't have any antiviruses installed. Let me clarify things: I have only windows 7 clean installation and no single other program except node.js. No internet, no browsres, no antivirus, no firewall...

I fond https://github.com/nodejs/help/issues/948 and seems that it is somehow (maybe?) related to my issue, because I also don't have internet connection on windows 7 computer. But the difference is that I cannot even start node.js, but in the linked issue node.js starts properly and then throws javascript error, so I think my issue is somehow still different.

Thanks in advance

**Comment by user928782** [comment]
Sorry, I said that I don't have any browsers. That is wrong, now I found one browser in my computer, it is located in C:\program files\Internet explorer, and as I understand it is native windows browser, so as answer to question, yes I indeed have one browserr. If needed, I am posting here full output of my ping command and launching internet explorer:

```
C:\Windows\System32> ping www.google.com
Ping request could not find host www.google.com. Please check the name and try a
gain.

C:\Windows\System32> ping 172.217.11.68
Unable to contact IP driver. General failure.

C:\Windows\System32> cd ..\..\"program files"\"internet explorer"

C:\Program Files\Internet Explorer> start iexplore.exe

C:\Program Files\Internet Explorer>
```

afetr typing start iexplorer.exe internet explorer properly launches. Of course it doesn't display any webpage, but it doesn't crash. It simply tells me that I don't have internet connection and thats it. That is also what I expect from node.js: to work properly and do everying offline (so I expect all node.js features except online stuff to work properly), I mean, when I launched internet explorer it didn't crash or display msvcrt error or anything, it siply properly launched gui and works fine, but node doesn't even launch, it displays error and terminates immediatelly, so am I doing something wrong? Does node.js requires internet in order to even launch?

Thanks...

**Comment by bnoordhuis** [comment]
> Does node.js requires internet in order to even launch?

Not a working network connection, but I won't vouch it runs without a network stack.  That "general failure" error suggests your system doesn't have TCP/IP installed.

**Comment by bnoordhuis** [comment]
I'm not sure that would do any good because I suspect the problem is not Node.js itself but the libraries it's linked against.

Maybe you can check with a debugger just how far into program startup it happens?  Set a breakpoint on `wmain` and step through until it terminates.

(If it doesn't even make it to `wmain`, there's probably no hope.)

**Comment by user928782** [comment]
@bnoordhuis 

I can't say that I'm happy to hear that. But thank you anyway for your help. Closing, as it seems that nothing can be done here :/

![](https://user-images.githubusercontent.com/38784761/39579464-2792157a-4ee7-11e8-8cda-71d5d1ed1fa9.png)
