### ISSUE TITLE
Add delay to for / while loop

### ISSUE THREAD

**Issue by josh4trunks** [nodejs/help#1243]
* **Node.js Version 8.10**:
* **AWS Lambda**:

Hello again. I have an Amazon Alexa Skill mostly built but had trouble with a little more advanced part.
I need to run several **http.get**'s to my Kodi home theater to increase/decrease the volume, but with a small delay between each one.
While the Kodi API responds to all my requests if they are within a few miliseconds, Kodi then forwards those command to my receiver over CEC, which seems to disregard multiple volume up/down commands that are too close together.

I have tried the below code, also tried it with a `while` loop, and also tried using awaits / async functions, but no matter what I do my http.gets always seem to run right away. I need them spread out. Thanks!

```js
if (!request.directive.payload.volumeStepsDefault) {
  var volumeAdjust = function() {
    http.get(controlURL);
  };
  for (let volumeCounter = Math.abs(request.directive.payload.volumeSteps); volumeCounter > 0; volumeCounter--) {
    setTimeout(function() {
      volumeAdjust();
    }, 1000);
  }
}
```

**Comment by gireeshpunathil** [comment]
let us say request.directive.payload.volumeSteps = 10. So your code will actually fire 10 http.gets back-to-back, after 1 second.

Assuming you want the audio to change volume after every 1 second and repeat this for `request.directive.payload.volumeSteps` steps, you could do this:

```js
let volumeCounter = Math.abs(request.directive.payload.volumeSteps);
function foo() {
  setTimeout(function() {
    volumeAdjust()
    if (--volumeCounter > 0)
      foo()
  }, 1000)
}
foo()
```

So with this setup, each request is fired only on the elapse of the previous timeout.

Hope this helps!

**Comment by josh4trunks** [comment]
great, yes I was able to get it to work. gotta refactor my code a bit but at least I do have a working 1 second delay now.
Thanks!

**Comment by vsemozhetbyt** [comment]
@josh4trunks If you need async/await variant:
```js
const sleep = require('util').promisify(setTimeout);

(async function main() {
  let i = 10;
  while (i--) {
    console.log(i);
    await sleep(1000);
  }
}());
```
