### ISSUE TITLE
cli-js not found error version 8.11.1-x64

### ISSUE THREAD

**Issue by jbmahadevan** [nodejs/help#1244]
* **Node.js Version**: 8.11.1-x64
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**:npm install
* **Module (and version) (if relevant)**:cli-js

I installed node version 8.11.1-x64 in my Windows 10 laptop.
Then installed
npm install express --save. - express installed successfully.
npm install body-parser --save - installed successfully

After that all npm commands are throwing the below error

Receiving error: 
 module.js:569
    throw err;
          ^
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'

I uninstalled and installed same version again.
Followed all the steps in stackoverflow link
https://stackoverflow.com/questions/24721903/npm-cli-js-not-found-when-running-npm
issue still exists

 I am able to reproduce same issue.

I installed  older version
node-v7.9.0-win-x64. This issue resolved.

**Comment by AyushG3112** [comment]
Whats the output of `npm -v`?

**Comment by gireeshpunathil** [comment]
ping @jbmahadevan

**Comment by gireeshpunathil** [comment]
no response, closing
