### ISSUE TITLE
how can i add mongodb module in netbeans

### ISSUE THREAD

**Issue by mishavthomas** [nodejs/help#1245]
internal/modules/cjs/loader.js:573
throw err;
^

Error: Cannot find module 'mongodb'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
at Function.Module._load (internal/modules/cjs/loader.js:497:25)
at Module.require (internal/modules/cjs/loader.js:626:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object. (C:\Users\user\Documents\NetBeansProjects\NodeJsApplication2\main.js:11:19)
at Module._compile (internal/modules/cjs/loader.js:678:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)

my code is :     
var http = require("http");
var express = require('express');
var app = express();
var bodyParser = require('body-parser');
var urlencodedParser = bodyParser.urlencoded({ extended: true });
var MongoClient = require('mongodb').MongoClient;
var url = "mongodb://localhost:27017/";
// Running Server Details.
var server = app.listen(8082, function () {
  var host = server.address().address
  var port = server.address().port
  console.log("Example app listening at %s:%s Port", host, port)
});
 
 
app.get('/form', function (req, res) {
  var html='';
  html +="<body>";
  html += "<form action='/thank'  method='post' name='form1'>";
  html += "Name:</p><input type= 'text' name='name'>";
  html += "Email:</p><input type='text' name='email'>";
  html += "address:</p><input type='text' name='address'>";
  html += "Mobile number:</p><input type='text' name='mobilno'>";
  html += "<input type='submit' value='submit'>";
  html += "<INPUT type='reset'  value='reset'>";
  html += "</form>";
  html += "</body>";
  res.send(html);
});
 var data={};
app.post('/thank', urlencodedParser, function (req, res){
  var reply='';
  reply += "Your name is" + req.body.name;
  reply += "Your E-mail id is" + req.body.email; 
  reply += "Your address is" + req.body.address;
  reply += "Your mobile number is" + req.body.mobilno;
  data = { name: req.body.name, address: req.body.address,mobile:req.body.mobilno,email:req.body.email};
  res.send(reply);
  MongoClient.connect(url, function(err, db) {
  if (err) throw err;
  var dbo = db.db("mydb");
  var myobj = { name: "Company Inc", address: "Highway 37" };
  dbo.collection("customers").insertOne(data, function(err, res) {
    if (err) throw err;
    console.log("1 document inserted");
    db.close();
  });
});
 });

created a  nodejs web  application in that i added a main.js and added code above
when running thrwing above exception

**Comment by gireeshpunathil** [comment]
does https://timboudreau.com/blog/NetBeans_Tools_for_Node_js/read help you?

**Comment by AyushG3112** [comment]
From the command prompt/terminal, run `npm i --save mongodb` in the root of your project directory.

**Comment by mishavthomas** [comment]
@AyushG3112 :I need to get mongodb module in netbeans.in console its installing and working fine .

**Comment by helderburato** [comment]
@mishavthomas install in your project dependencies running `npm i --save mongodb`. 
I think this [link](https://www.npmjs.com/package/mongodb) can help you.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if you still have questions.
