### ISSUE TITLE
Question: How skip node api during debugging

### ISSUE THREAD

**Issue by Legends** [nodejs/help#1248]
node v8.10

I am debugging a framework and under scripts I have:

node --inspect --inspect-brk ...

How to skip the node api during debugging ?

**Comment by advanceddeveloper** [comment]
> How to skip the node api during debugging?

What do you mean by node api? Do you mean the message

```
Debugger listening on ws://127.0.0.1:9229/651b7a5e-9ad3-28e4-c36b-fe6ec3239f81
For help, see: https://nodejs.org/en/docs/inspector
```

that is printed to the console?

**Comment by Legends** [comment]
I don't want to debug internal node modules just external code..

**Comment by advanceddeveloper** [comment]
You can blackbox internal Node.js scripts in the developers tools inspector.

**Comment by Legends** [comment]
Give me a gun please....
