### ISSUE TITLE
npm ERR! enoent ENOENT: no such file or directory

### ISSUE THREAD

**Issue by zorek9502** [nodejs/help#1249]
Hi, I'm a totally noob with angular, and when I try to create a project with CLI I got some errors.

Command- > npm run ng -- build --base-href /newApp or  -> ng new newApp

-----Errors----

npm ERR! path C:\Users\username\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\username\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Also I cannot run ng -v 
"'ng' is not recognized as an internal or external command,
operable program or batch file."

Hope someone can help me, thank you.

**Comment by rajkbhawsar** [comment]
HI Zorek,
Run this command where package.json file exist. even i experience similar problem then i change the folder and got resolve it.
for more explanation i run c:\selfPractice>  npm start
whereas my package.json resides in c:\selfPractice\frontend> then i change the folder and run c:\selfPractice\frontend> npm start and it got run

**Comment by mahmmoudkinawy** [comment]
If you ever get this error, the hotfix is to follow these steps:

delete node-modules folder
run command npm cache clean --force
run command npm install
install the package again with npm install your-package-name

**Comment by ijomah** [comment]
@rajkbhawsar thanks for that. It solved my problem

**Comment by alexanderhipe** [comment]
just cd to your directory.

**Comment by shishuyanguang** [comment]
> 

Thank you , it is  very uesful

**Comment by shishuyanguang** [comment]
Thanks，its very useful

> HI Zorek, Run this command where package.json file exist. even i experience similar problem then i change the folder and got resolve it. for more explanation i run c:\selfPractice> npm start whereas my package.json resides in c:\selfPractice\frontend> then i change the folder and run c:\selfPractice\frontend> npm start and it got run
> 
> 在 package.json 文件存在的地方运行这个命令。即使我经历类似的问题，然后我改变文件夹，并得到解决它。为了得到更多的解释，我运行 c: selfPractice > npm start然而我的 package.json 驻留在 c: selfPractice 前端 > 中，然后我改变文件夹并运行 c: selfPractice 前端 > npm start 并运行它
