### ISSUE TITLE
How can I know when VM is done?

### ISSUE THREAD

**Issue by felipefdl** [nodejs/help#125]
I tried looking any event like on(exit) on(end) but vm doesn't support that, I'm trying a solution using cluster+vm, but I'm not doing very well. my context have callbacks function, so my thread doesn't wait when VM is done.

**Comment by bnoordhuis** [comment]
Are you looking for `process.on('exit', ...)`?

**Comment by felipefdl** [comment]
@bnoordhuis The vm context doesn't have process object.

**Comment by bnoordhuis** [comment]
Oh, you mean the actual 'vm' module?  Execution is synchronous, when `vm.runInContext()` (or whatever method you called) returns, it's finished.  If you allow the context to register callbacks, you'll have to track those yourself; there's no built-in mechanism for that.
