### ISSUE TITLE
On `use_idle_notification` usage

### ISSUE THREAD

**Issue by Shahor** [nodejs/help#1250]
* **Node.js Version**: 8.11.0
* **OS**: Linux (Debian)
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I hope this is the right place to ask for help on this matter.

I'm working on scaling a websocket nodejs program and I have stumbled on this option, `use_idle_notification` a number of times now.

One of those times is in [this issue](https://github.com/nodejs/node/issues/3370#issuecomment-148934249) which seems to indicate that this is a noop now. 

The problem is I can't find proper documentation on this matter and don't know exatly how to deal with this.
I have tested a little bit and haven't seen much differences when running it with the default value (`true`)  or with `--no-use_idle_notification`

Is there any up-to-date documentation on how exactly this works and what the `idle notifications` are?

Cheers 🍺

**Comment by gireeshpunathil** [comment]
```
#find . -name "*.h" | xargs grep "use_idle_notification"
./deps/v8/src/flag-definitions.h:DEFINE_BOOL(use_idle_notification, true,
```
Only one search result in the latest code base makes me believe it is dysfunctional.

/cc @nodejs/v8

**Comment by hashseed** [comment]
It is used [here](https://cs.chromium.org/chromium/src/v8/src/api.cc?l=8688&rcl=0cb7b82ecaab1aeb72ec695c0aaaeda26d3513b4).

It defaults to true, but only affects whether `v8::Isolate::IdleNotificationDeadline`, which is not used by Node.js.
