### ISSUE TITLE
if no 'data' handler, Transform stream doesn't work

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1252]
This regards Node.js versions 9.x+

I have this:

```js
import {XMLParser} from "./index";
process.stdin.resume().pipe(new XMLParser()).once('result', function (v) {
  console.log(JSON.stringify(v));
});
```

but I can also use it this way:

```js
import {XMLParser} from "./index";
const file = path.resolve(__dirname + '/some.file.xml');

new XMLParser({file}).once('result', function (v) {
  console.log(JSON.stringify(v));
});
```

So the readable stream is either the transform stream instance itself or created by `fs.createReadStream()` inside the constructor.

But even when using the Transform stream instance, if I don't call this:

 ```js
reader.on('data', function (d: string) {});
```

inside the constructor, then the pipe call won't work.

```js
'use strict';

import {Readable, Transform, TransformOptions} from "stream";
import fs = require('fs');
import * as path from "path";
import * as util from "util";
import EventEmitter = require('events');

export class XMLParser extends Transform {
  
  filepath = '';
  rawInput = '';
  jsResult = {
    root: new Node(null, 'root')
  };
  
  file = '';
  withinField = false;
  currentNode: Node;
  reader: Readable;
  emitter = new EventEmitter();
  key = '';
  
  constructor(opts?: XMLParserOpts, to?: TransformOptions) {
    
    super(to || {});
    
    opts = opts || {} as XMLParserOpts;
    const file = this.file = opts.file || '';
    this.key = opts.key || '';
    
    if (file && !path.isAbsolute(file)) {
      throw new Error('xml file path must be absolute.')
    }
        
    let reader = this as Readable;
    
    if (file) {
      reader = fs.createReadStream(file, 'utf8');
    }
    
    this.currentNode = this.jsResult.root;
    const self = this;
    
    reader.once('end', function () {
      setImmediate(function () {
        self.emit('result', self.jsResult.root);
      });
    });
    
    let dataCount = 0;
    
    reader.on('data', function (d: string) {   /// if I don't include this handler, piping won't work
      dataCount++;
      console.log('data count:', dataCount);
      self.handleData(d);
    });
    
  }
  
  _transform(chunk: string, enc: string, cb: Function) {
    this.handleData(chunk);
    cb();
  }
  
  handleData(d: string) {
    
    let index = 0;
    let prevChar = '';
    let nextNodeName = '';
    let nodeValue = '';
    const self = this;
    
    for (let v of String(d)) {
      
      const isWhiteSpace = String(v).trim() === '';
      
      if (isWhiteSpace && recordingNextNodeName) {
        recordingNextNodeName = false;
        recordingFields = true;
      }
      
      if (recordingValue) {
        nodeValue += v;
      }
      
      index++;
      prevChar = v;
    }
  }
  
  
  inspectValue() {
    return util.inspect(this.jsResult, {depth: 15, maxArrayLength: 50});
  }
  
  toXML(): string {
    return '';
  }
  
  getNewNode(parent: Node, name: string): Node {
    return new Node(parent, name);
  }
  
}
```

**Comment by user928782** [comment]
Whan I run your script with node v10.0.0 I get the following error:

```console
import {Readable, Transform, TransformOptions} from "stream";
       ^

SyntaxError: Unexpected token {
```

**Comment by addaleax** [comment]
If there is nothing that consumes the output of a `Transform` stream, then it doesn’t continue reading data either – that’s essentially the difference behind Transform streams and generic Duplex streams.

In this case, it doesn’t look like the `Transform` stream actually produces output in any way – there are no calls to `.push()` and the callback for `_transform` doesn’t receive any arguments. From the use case (parsing XML + returning a *single* result), it seems like a `Writable` stream might be a better fit?

**Comment by ORESoftware** [comment]
@addaleax yeah this transform stream doesn't do anything line by line, it's basically converting XML to JSON, so it mostly buffers everything, when it's done it emits 'result' which you can see in the constructor. (I omitted code that wasn't necessary, the code above is just a selection of the important stuff).

There is a possibility of creating an XML to JSON parser that doesn't buffer everything, but I am not quite there yet.

**Comment by ORESoftware** [comment]
But you're probably right that I should call `this.push()` and emit 'result', those can coexist.

**Comment by user928782** [comment]
@ORESoftware 

can you please explain how you compile this code?? i am trying to run it and keep getting syntax errors... is this some different kind of javascript? do i need to install some additional softwares to compile your code?

**Comment by ORESoftware** [comment]
@user928782 sorry I should have mentioned that it's TypeScript (highly recommended)

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if you still have questions.
