### ISSUE TITLE
How to make these scripts work as fast as possible

### ISSUE THREAD

**Issue by advanceddeveloper** [nodejs/help#1254]
* **Node.js Version**: v10.0.0
* **OS**: windows 10
* **Scope**: code
* **Module**: child_process (socket)

Hello.

There are two scripts in my project (very simplified example):

**1.js**

```js
'use strict';

var cp = require('child_process');
var proc = cp.spawn('node', ['2.js']);
var i = 0;

while(1){
  var buff = Buffer.alloc(10e6);
  buff.writeUInt32LE(i, 0);
  proc.stdin.write(buff);
  i = ++i % 2 ** 32;
}
```

**2.js**

```js
'use strict';

var fs = require('fs');
var fd = fs.openSync('1.bin', 'w');

process.stdin.on('data', buff => {
  var time = Date.now();
  while(Date.now() - time < 1e3);
  buff[buff.length - 1] ^= 1;
  fs.writeSync(fd, buff);
});
```

Let me explain: the first script in a while loop allocates a buffer of size 10 millions bytes, then at the first 4 bytes write values 0, 1, 2, ... etc depending of the number of the current iteration, then sends buffer to 2.js. When 2.js receives the buffer it synchronously waits 1 second, then writes the number 1 at the last byte of the recived buffer and saves (appends) it to the file `1.bin` which is a binary file (as the extension suggests).

My question here is how to do it, firstly properly, then optimal. Currently, it doesn't even work, All the allocated buffers are still stored in the heap of 1.js and don't seem to be freed until 2.js receives each of them and processes them. Allocations happen much faster and my 1.js runs out of memory pretty quickly. My goal is to make this to work arbitrary amount of time (forever) and to make it work as fast as possible.

I solved the "Array buffer allocation failed" problem by making my while loop asynchronous and attaching event listener when calling `write` method, but the problem is because my 1.js doesn't do anything useful while it is waiting for 2.js to process data. Script 2.js cannot be modified, I need to addapt my 1.js to the 2.js script, not vice versa. So, how can I make it optimal? I mean how can I make 1.js work as fast as possible and produce as much data as possible? Of course, 2.js works much slower so probably the speed of the whole process needs to adapt to the speed of 2.js, but I am sure it can be more optimal and faster than adding listener (callback) to `write` method or attaching a listener to `drain` event.

Many thanks for your time.

**Comment by gireeshpunathil** [comment]
> Of course, 2.js works much slower so probably the speed of the whole process needs to adapt to the speed of 2.js

I guess that is the point. Because of the synchronous writes 2.js may be much slower compared to 1.js so whatever you do to `improve` things at 1.js will not be visible - any apparent improvement to the readability, semantics, allocation logic, filling logic, writing logic etc. will be masked by the delay at the receiver side.

If you can profile 2.js and see if there are any instance where it is found to be waiting (uv loop in blocking poll state) for data from 1.js, then there is a scope for improvement, but my gut feeling looking at your code is none exists.

**Comment by advanceddeveloper** [comment]
Thanks a lot for the response.

I know it cannot be improved a lot, but I am sure it can at least be improved a bit. What I currently have is this: while 1.js prepares data, 2.js waits. As soon as 1.js has data ready, it passes to 2.js and waits for 2.js to process the data, in the meanwhile 1.js waits and doesn't do anything. When 2.js processes data, it sends signal to 1.js and waits for 1.js and so on. The problem is because at every point in time exactly one script is doing useful work, while the other one is spinning in the event loop and waiting for the signal.

My idea is to force 1.js to work while 2.js works, when 1.js prepares next data, then wait for 2.js to finishes previous processing, and then send new data to 2.js and again prepare new data. Maybe it is confusing (even when I read what I said is a bit confusing to me), so here is the picture of what I mean:

![](https://user-images.githubusercontent.com/38354752/39672601-a472f0a8-512d-11e8-94ef-16eb30523118.png)

Suppose that 1.js and 2.js need approximatelly same time to process the data. Then the second chart is x2 times faster than the first chart. Moreover, if I have more than 2 scripts, the speed can be increased a lot.

I tried to somehow achieve it, but couldn't. Whatever I try, I got allocation failed after some time.

**Comment by gireeshpunathil** [comment]
untested, but can you try this logic?

```js
var b1 = Buffer.alloc(10e6)
b1.writeUInt32LE(i, 0)
var b2

function foo() {
  proc.stdin.write(b1, () => {
    var temp = b1
    b1 = b2
    b2 = temp
    foo()
  })
  b2 = Buffer.alloc(1024)
  b2.writeUInt32LE(i, 0)
  i = ++i % 2 ** 32
}

foo()
```

**Comment by advanceddeveloper** [comment]
That is what I've already tried and the performances are the same. In the meanwhile I did some research and I actually think that it is working as fast as possible and that there is not much to be improved. The majority of time is spent on asynchronous callbacks (assuming that both scripts are very fast), so it would be optimal to write and read data synchronously from sockets, but as I know, there is no way to achieve it. So, I'm closing this issue, but thank you for your help.

**Comment by gireeshpunathil** [comment]
> That is what I've already tried and the performances are the same

Just to make sure we are on the same page - the logic I proposed is different from what is posted in your first comment. My code has a backup buffer `b2` which is being allocated and filled while the write is being carried out, and as soon as the write is over on b1, you have b2 ready for write.

Do you mean to say your code is same as mine, or do you mean to say you have had tried this one too already, though not posted here? I just want to make sure we have applied the best effort on this with nothing left hanging, thanks.

**Comment by gireeshpunathil** [comment]
thanks @advanceddeveloper - great explanation! though nothing changes at the end, it gives pleasure to know that it is already optimal.
