### ISSUE TITLE
Pass handle representing request/response to child process 

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1260]
I have a Node.js server (running on Node version 9) and I want to launch a child process for a certain type of request.

I'd like to read from the request and write to the response from the child process.

Is there some way to pass a handle on the request/response from the Node.js server process to the child process?

I asked a similar question here:
https://stackoverflow.com/questions/47270986/pass-handle-down-pipeline

seems like I might have to dive into the world of C/C++, but not sure. Please advise thanks!

**Comment by ORESoftware** [comment]
This answer looks good:
https://stackoverflow.com/a/35719054/1223975

but I am not sure how it works? How do you pass a handle on the socket using IPC and JSON? How does that actually work?

**Comment by gireeshpunathil** [comment]
@ORESoftware - probably this below example will help illustrate this better. 
This has a parent and a child, parent creates a server, and upon client connections, the socket handle is passed onto the child.

The child has only a message loop in which it receives the handle, and is able to reach to the client through that.

#cat 1260.js
```js
const cp = require('child_process')
const n = require('net')

if (process.argv[2] === 'child') {
  process.on('message', (m, h) =>  {
    h.end('ok')
  })
}
else {
  const c = cp.fork(process.argv[1], ['child'])
  const s = n.createServer();
  s.on('connection', (h) => {
    c.send({}, h)
  }).listen(12000, () => {
  const m = n.connect(12000)
  m.on('data', (d) => {
    console.log(d.toString())
  })
 })
}
```

strace with relevant sections around the handshake.

```c
[pid 12055] sendmsg(11, {msg_name(0)=NULL, msg_iov(1)=[{"{\"cmd\":\"NODE_HANDLE\",\"type\":\"net.Socket\",\"msg\":{},\"key\":\"6::::12000\"}\n", 70}], msg_controllen=24, {cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, {14}}, msg_flags=0}, 0) = 70
...
[pid 12061] recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"{\"cmd\":\"NODE_HANDLE\",\"type\":\"net.Socket\",\"msg\":{},\"key\":\"6::::12000\"}\n", 65536}], msg_controllen=24, {cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, {12}}, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 70

[pid 12061] getsockname(12, {sa_family=AF_INET6, sin6_port=htons(12000), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 0

[pid 12061] getsockopt(12, SOL_SOCKET, SO_TYPE, [1], [4]) = 0

[pid 12061] write(3, "{\"cmd\":\"NODE_HANDLE_ACK\"}\n", 26) = 26

[pid 12055] <... epoll_wait resumed> {{EPOLLIN, {u32=11, u64=11}}}, 1024, -1) = 1

[pid 12055] recvmsg(11, {msg_name(0)=NULL, msg_iov(1)=[{"{\"cmd\":\"NODE_HANDLE_ACK\"}\n", 65536}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 26
```

As you can see, the parent and child engage in a protocol through which the socket handle is transported, and the child recreates a net.Socket object from the handle information thus received. Subsequently, the child is able to handle the client underneath this connection.

This protocol, and the way of transporting handles and thereby workload across processes, is the heart and soul of `cluster` module.

Hope this helps!

**Comment by ORESoftware** [comment]
yes this is very cool, will read this again tomorrow

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if anything is outstanding here.
