### ISSUE TITLE
using IPC to pass socket to child process, how to associate it with data in server?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1263]
I am on Node.js versions 6+

I have this question on SO:
https://stackoverflow.com/questions/50266743/how-to-attach-data-to-socket-passed-to-child-process

In this case, data from the socket (like the headers) might have already been read, so that by the time the socket reaches the child process, there might not be much metadata to be read from it.

So the question is, how can I somehow associate the socket with its headers or metadata about the request, once it reaches the child process?

**Comment by Globik** [comment]
You must to use the shared environment variables between parent and child.

**Comment by ORESoftware** [comment]
@Globik I have to send new data for each request, not just once

**Comment by gireeshpunathil** [comment]
- the first argument is exactly for that purpose
 - for plain sockets, there is no header that is read upon `connection`.
 - for HTTP sockets too, there is no header that is read upon [connection event](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_event_connection)

The code shows how to transfer custom objects across processes:

#cat 1263.js

```js
const cp = require('child_process')
const n = require('net')

if (process.argv[2] === 'child') {
  process.on('message', (m, h) =>  {
    console.log(m)
    console.log(h.bytesRead)
    h.end('ok')
  })
}
else {
  const c = cp.fork(process.argv[1], ['child'])
  const s = n.createServer();
  s.on('connection', (h) => {
    console.log(h.bytesRead)
    const xfer = {name: 'pc', type: 'x86'}
    c.send(xfer, h)
  }).listen(12000, () => {
  const m = n.connect(12000)
  m.on('data', (d) => {
    console.log(d.toString())
  })
 })
}
```

#node 1263.js

```
0
{ name: 'pc', type: 'x86' }
0
ok
^C
```
This code shows the HTTP server.on(connection) is a best place to catch the TCP socket, without any header data being read already:

#cat 1263_1.js

```js
const h = require('http')
const s = h.createServer((q, r) => {
  console.log(r.socket.bytesRead)
  r.end('ok')
});
s.on('connection', (h) => {
  console.log(h.bytesRead)
})
s.listen(12000, () => {
  h.get('http://localhost:12000', (m) => {
    m.on('data', (d) => {
      console.log(d.toString())
    })
  })
})
```
#node 1263_1.js
```
0
60
ok
```

Hope this helps

**Comment by gireeshpunathil** [comment]
closing as answered, let me know if anything is outstanding here
