### ISSUE TITLE
node version 10+ account loop (external script)

### ISSUE THREAD

**Issue by SFx2018** [nodejs/help#1266]
Hello, since orginal author of https://github.com/luk1337/vapor-report is unavailable, I can't figure out why since nodejs version 10, this script is looping at 1st account, everything works good with version: 9.11.1

I'm using this script on windows, its open powershell script, then processing with nodejs
https://github.com/luk1337/vapor-report/blob/master/commend.ps1

Can somebody help me?

**Comment by shellberg** [comment]
@SFx2018 : Sorry to here of your predicament.  Having looked over that github repository, it does look particularly quiet and maybe has lapsed in maintenance.  There seems to be a growing number of open Issues, and not much of community of maintainers or other committers... with perhaps one exception.  You might try and get in touch with Not2EXceL - that appears to be the only other contributor, as well as carrying a fork with a few later commits.  At least, thats evidence of somebody who's taken the time to try and understand how vapor-report is working; either that, or perhaps appeal to someone in the 'vapor' community?  They at least would have most of the dependencies for this system installed?  Just a suggestion anyway.

**Comment by SFx2018** [comment]
no one knows the solution to the problem, it's strange just why with 9.11.1 and lower versions everything works OK

**Comment by gireeshpunathil** [comment]
closing as answered from the scope of Node.js, please engage the repo owner for further clarifications. thanks!
