### ISSUE TITLE
flipping the HTTP status code for a response after writing headers

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1267]
Say I have this function when manually writes an HTTP response to a connection socket, including writing the contents of a requested file:

```js
    const writeResponse = function(file: string, s: Socket){

       s.write([
        'HTTP/1.1 200 OK',
        'Content-Type: text/javascript; charset=UTF-8',
        'Content-Encoding: UTF-8',
        'Accept-Ranges: bytes',
        'Connection: keep-alive',
       ].join('\n') + '\n\n');
            
      getStream(file)
        .once('error', function (e: any) {
          s.end('error: ' + e && e.stack || e.message || util.inspect(e));
        })
        .pipe(s)  // pipe to response
        .once('error', function (e: any) {
          s.end('error: ' + e && e.stack || e.message || util.inspect(e));
        });
    
    }
```

the **problem** that I cannot figure out how to solve - if there is an error reading the file, how can I send this header instead of the success header:

>     HTTP/1.1 500 Cannot read file

the problem is that as far as I know, writing the file to the response has to come *after* writing the headers, but what if there is an error reading the file?

**Comment by gireeshpunathil** [comment]
[http.setHeader](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_request_setheader_name_value)? that lets you set once and modify n number of times before sending. Only caveat is that you shouldn't be flushing the header before you read the file.

**Comment by ORESoftware** [comment]
well all I have is the socket, can I call `socket.setHeader()`?

**Comment by gireeshpunathil** [comment]
ah! I see, sorry! (No, you cannot)

**Comment by ORESoftware** [comment]
yeah that's the problem right now, the code I have is literally all I have, just a filepath to read, and a socket to write to

**Comment by gireeshpunathil** [comment]
will this approach help?

#cat 1267.js 
```js
var head = []
head.push('HTTP/1.1 200 OK')
head.push('Content-Type: text/javascript; charset=UTF-8')
head.push('\n\n\n')

if(process.argv[2] === 'true')
  head[0] = 'HTTP/1.1 500 Cannot read file'
console.log(head.join())
```
```trace
#node 1267.js 
HTTP/1.1 200 OK,Content-Type: text/javascript; charset=UTF-8,
```

```trace
#node 1267.js true
HTTP/1.1 500 Cannot read file,Content-Type: text/javascript; charset=UTF-8,
```

**Comment by ORESoftware** [comment]
@gireeshpunathil I don't think that will work, because I am writing a big file to the response stream and I want it to be performant.

I think something like this has the answers:
https://stackoverflow.com/questions/15305203/what-to-do-with-errors-when-streaming-the-body-of-an-http-request

what do you think?

**Comment by gireeshpunathil** [comment]
@ORESoftware - yes, that looks a better alternative to me.
