### ISSUE TITLE
invalid strLen RangeError

### ISSUE THREAD

**Issue by chatcoder** [nodejs/help#127]
This is throwing this error almost daily now:
strLen += '' + bufferTail[i]; ^ RangeError: Invalid string length at Object.exports.decodePayloadAsBinary
Any ideas how to fix?

**Comment by subfuzion** [comment]
@chatcoder Correct me if I'm wrong, but this looks like a socket.io error. Please report the issue for that project at https://github.com/socketio/socket.io/issues.

**Comment by chatcoder** [comment]
Thank you so much, I have posted it there.
