### ISSUE TITLE
async and await keywords throwing syntax error

### ISSUE THREAD

**Issue by the8thbit** [nodejs/help#1272]
* **Node.js Version**: 10.1.0
* **OS**: Ubuntu GNU/Linux subsystem on Windows 10
* **Scope (install, code, runtime, meta, other?)**: syntax error

I get this error when using the await and async keywords:

```
SyntaxError: missing ) after argument list
```

Sample code:

```js
console.log(await client.time());
```

**Comment by advanceddeveloper** [comment]
Are you sure the syntax error is thrown at that specific line? Can you post the full error message and stack trace? Here is a sample code which works properly:

```js
'use strict';

var client = {async time(){}};
func();

async function func(){
  console.log(await client.time());
}
```

**Comment by gireeshpunathil** [comment]
closing as answered.

corollary:
await lives only in an async context, otherwise it throws such errors. Also not supported by older Node versions.

**Comment by Tatsujinichi** [comment]
> await lives only in an async context, otherwise it throws such errors. Also not supported by older Node versions.

Then that should be the error thrown.
