### ISSUE TITLE
Uninstalling Node

### ISSUE THREAD

**Issue by unclerom** [nodejs/help#1274]
I cannot find a way the works to completely uninstall node. is this possible? i installed for the first time ever using the nodejs.org osx package now i am trying to remove and reinstall with nvm. after reading and trying different commands i still cant remove node if i run node -v i still get 10.1.0

**Comment by gireeshpunathil** [comment]
uninstalling in macos has been an issue historically. How about re-installing using the `pkg` installer of the desired version? If that is not an option, please review [this link](https://wincent.com/wiki/Uninstalling_packages_(.pkg_files)_on_Mac_OS_X) helps you. After which if still node is present, it should be another installation, which you can locate by `which node` command. Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered.
