### ISSUE TITLE
How to preserve Windows attributes when using writeFileSync?

### ISSUE THREAD

**Issue by rfgamaral** [nodejs/help#1275]
When using `writeFileSync` in Windows, the `hidden` attribute is removed from the destination file if it's being overwritten. Is there any way to preserve this attribute from being removed somehow?

I couldn't find any reference to such thing the documentation nor get any helpful response from a Google search. Would appreciate any help regarding this issue.

**Comment by vsemozhetbyt** [comment]
For me (Node.js 10 on Windows 7 x64) this note [here](https://nodejs.org/api/fs.html#fs_file_system_flags) helps:

> On Windows, opening an existing hidden file using the 'w' flag (either through fs.open() or fs.writeFile() or fsPromises.open()) will fail with EPERM. Existing hidden files can be opened for writing with the 'r+' flag.

With this flag, the file remains hidden.

**Comment by rfgamaral** [comment]
Thank you @vsemozhetbyt :)
