### ISSUE TITLE
Debate about whether headers are included in proxied request

### ISSUE THREAD

**Issue by the1mills** [nodejs/help#1276]
I am on the latest Node.js versions v9, v10, etc. I have a simple server which proxies the npm registry:

```js
import http = require('http');

const s = http.createServer(function (clientRequest, clientResponse) {

  const proxy = http.request({
      hostname: 'registry.npmjs.org',
      port: 80,
      path: clientRequest.url,
      method: clientRequest.method
    },
    function (res) {
      res.pipe(clientResponse);
    });

   // do the clientRequest headers get written to the proxy request??
  clientRequest.pipe(proxy);

});

s.listen(3441);
```

I have a debate raging here about whether the original request headers are included in the request that gets sent to NPM:

https://stackoverflow.com/questions/50342072/why-doesnt-node-js-proxy-request-need-headers-included?noredirect=1#comment87711085_50342072

**Comment by the1mills** [comment]
So yeah my question is - are the original headers included or not?

**Comment by bnoordhuis** [comment]
No, they're not.

**Comment by ORESoftware** [comment]
Yeah ok, makes sense, to include them, just do this?

```js
  Object.keys(headers).forEach(function(k){
      proxy.write(`${k}\t${headers[k]}\r\n`);
  });
```

**Comment by bnoordhuis** [comment]
No, that creates an outgoing request with headers in the request body.

Add them as the `.headers` option to `http.request()` but scrub them first if you don't want to get pwned.  Ditto for `.path` and other values that you copy from the incoming request.

Take a look at https://github.com/nodejitsu/node-http-proxy.

**Comment by ORESoftware** [comment]
Yeah I tried adding the headers to the options arg, but I got some JSON parsing errors which I thought was very strange.

**Comment by gireeshpunathil** [comment]
Guessing that this issue is resolved. /cc @ORESoftware and @the1mills (by this time I also have guessed you two are same)

**Comment by gireeshpunathil** [comment]
closing as addressed, please let me know if that is not the case
