### ISSUE TITLE
angular material are not supporing  itis showing some error messages

### ISSUE THREAD

**Issue by sachin-budni** [nodejs/help#1278]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

```
ERROR in node_modules/@angular/material/button-toggle/typings/button-toggle.d.ts(136,20): 
error TS2315: Type 'ElementRef' is not generic. node_modules/@angular/material/button-toggle/typings/button-toggle.d.ts(154,104): 
error TS2315: Type 'ElementRef' is not generic. node_modules/@angular/material/slide-toggle/typings/slide-toggle.d.ts(53,15): 
error TS2315: Type 'ElementRef' is not generic. node_modules/@angular/material/slide-toggle/typings/slide-toggle.d.ts(55,18): 
error TS2315: Type 'ElementRef' is not generic. 
```
will u please give me a solution and next thing i installed node 10.0.0 v

**Comment by advanceddeveloper** [comment]
Body section of an issue is for description and code. Title is just for a short summary of the issue.

According to the error message you get, [a quick google search](http://lmgtfy.com/?q=%27ElementRef%27+is+not+generic) will tell you that it is probably an issue with different versions of Anular and AngularMaterial. One of the answers:

> The problem could be if your you are using Angular Material 6 but still Angular 5 then you will get this error. When installing Angular Material 6 RC 12 it's looking for a peer dependency for Angular 6 Beta 0 while I had a Angular 5.x.x version.
>
>Solution:
>
>1. Downgrade Angular Material to the same major version of Angular (eg. v5.x.x)
>2. Upgrade Angular and Material to the latest RC version and live life on the edge. (eg. v6.x.x RCx)

**Comment by gireeshpunathil** [comment]
closing as answered.
