### ISSUE TITLE
How to signal that readable stream is done/finished

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1279]
Say I create a Readable stream with:

```js
  const r= new Readable({
      read: function(){
      }
    });

```
and say I call:

```js
r.push('foo');
r.push('bar');
```

now, how can I tell the readable and everything downstream that readable is done?

```ja
r.end()  // ? I don't think this is correct.
```

maybe...

```js
r.emit('end')
```

??

**Comment by addaleax** [comment]
[`r.push(null)`](https://nodejs.org/api/stream.html#stream_readable_push_chunk_encoding)? :)

**Comment by ORESoftware** [comment]
oh yeah, duh lol, sorry, but ok but what about a transform stream?
If I create a transform stream and write to it directly, then what do I do?
how do I signal that the transform stream is done?

**Comment by addaleax** [comment]
@ORESoftware `.end()`? That is the way by which you signal to any writable stream that you’re done writing data to it

**Comment by ORESoftware** [comment]
Yeah, streams are confusing sometimes, especially readable streams

**Comment by gireeshpunathil** [comment]
hope this is answered and clarified, so closing. Please let me know if that is not the case
