### ISSUE TITLE
help how and what version of python and node for Samsung avant phone

### ISSUE THREAD

**Issue by ghostsleeper7** [nodejs/help#128]

**Comment by ghostsleeper7** [comment]
Sorry new to this how and what python download for android Samsung avant phone to get node .js

**Comment by bnoordhuis** [comment]
The Avant is an Android phone?  We don't release binaries for Android (yet) so you'd have to (cross)compile from source.  The latest v5.x release probably stands the best chance of working.  You're going to need python 2.7 to build it.
