### ISSUE TITLE
TypeError: fs.writeFile is not a function

### ISSUE THREAD

**Issue by mizramir** [nodejs/help#1280]
* **Node.js Version**: 8.11.2
* **OS**: Win10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: fs

Hello,

I'm trying to write to a file using the 'fs' module.
I have an html page with javascript that I run from my localhost (localhost:8080/test.html) using Chrome browser.
I had an error of "_require is not defined_" and I managed to fix that using [Browserify](http://browserify.org/). It bundles my main script with the required module.
Now, that it's all set with require - I encounter another issue "_TypeError: fs.writeFile is not a function_" when using this code snippet:
```js
mpSdk.Camera.takeScreenShot( dimensions, options)
			.then(function (screenShotUrl) {
				var fs = require('fs');
				fs.writeFile("lol.txt", "Hey there!", function(err) {
				if(err) {
				return console.log(err);
				}

				console.log("The file was saved!");
				});
				return screenShotUrl;
				})
			.catch(function(error) { // Undocumented -- is error logging avialable?
				console.info(error);
				return false;
			});
```

What am I doing wrong?

Thank you,
Amir

**Comment by richardlau** [comment]
According to [browserify's handbook](https://github.com/browserify/browserify-handbook#builtins) `fs` is not one of the builtins. You will probably need to use something like [browserify-fs](https://www.npmjs.com/package/browserify-fs).

**Comment by mizramir** [comment]
It seems to be working with browserify-fs.
I ran the following code snippet and console printed out "The file has been saved!" but I **cannot** find the file anywhere on my local disc:
```js
var fs = require('browserify-fs');
fs.writeFile('message.txt', 'Hello Node.js', (err) => {
if (err) throw err;
console.log('The file has been saved!');
});
```

Did I do anything wrong?

**Comment by advanceddeveloper** [comment]
You cannot modify (create, write) local files using HTML and browser-side JavaScript. In other words, browsers do not provide a way to modify arbitrary files on the local disk.

Node.js is a standalone application and Node's native `fs` module uses libraries written in C++ to actually create, read and modify local files. If your code is written for Node.js, it may be browserified, but only on the logical level. You cannot use things like `process.exit` or `child_process.spawn` directly from webpages. You may do it if you somehow communicate with a Node.js server running in the background which will do all that tasks, but without it, client-side scripts cannot interact with the local operating system or file system. Webpage scripts are sandboxed to prevent malicious scripts from damaging system.

If I understood their implementation correctly, `browserify-fs` simulates a virtual file system. You can read and write files, but such files are stored in RAM memory (or browser's local storage object) and not on the file system (hard disk).

So, if you want to modify local files (create, write, etc), you have to somehow do it from Node.js, not from browser. You can send a message to the Node.js server with details about which file to write and what content to write.

Hope it helps.

**Comment by vsemozhetbyt** [comment]
Maybe something like [puppeteer](https://github.com/GoogleChrome/puppeteer) can help if you need Node.js API + Web API coordination on a local level.

**Comment by mizramir** [comment]
Thank you both for the info.
@advanceddeveloper, can you please clarify your last sentence - "You can send a message to the Node.js server with details about which file to write and what content to write." - how can this be achieved? I have an html file with a script in it. I'm using a specific SDK to control an iframe embedded in my webpage. That SDK enables me, for example, to take snapshots from a video displayed in that iframe. After taking a snapshot, I have the image data (content) and would like to save it on my local disk.
Hope this was clear enough and you could guide me how this can be achieved.

Thank you!

**Comment by advanceddeveloper** [comment]
@mizramir 

> I have the image data (content) and would like to save it on my local disk.

You can use [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) to send data to Node.js and in the Node.js script you can call [FFmpeg](https://www.ffmpeg.org/) to save image on the local disk.

Here I am posting a simple example of how you can save a canvas to a png file (or any other image format) by sending raw image data from browser script to Node.js server. In this example, the browser-side script creates a canvas, draws `Hello, World!` text on it and sends to Node.js server. When receives image data, Node.js server spawns a FFmpeg process, passes the image data to it and then sends the status (or error) back to the browser script. FFmpeg is not Node.js native program, so you need to install it separately.

You can download these files [here](https://github.com/nodejs/help/files/2020468/example.zip), or copy paste the following scripts. Please test it out and let me know if it works for you.

### index.htm

```html
<script src="browser.js"></script>
```

### browser.js

```js
(() => {
  'use strict';

  const HOST = 'localhost';
  const PORT = 8080;

  window.addEventListener('load', () => {
    var w = innerWidth;
    var h = innerHeight;

    setTimeout(main);

    function main(){
      var ctx = createCtx();

      ctx.fillStyle = 'white';
      ctx.fillRect(0, 0, w, h);

      ctx.font = '72px arial';
      ctx.textBaseline = 'middle';
      ctx.textAlign = 'center';

      ctx.fillStyle = 'black';
      ctx.fillText('Hello, World!', w / 2, h / 2);

      saveImageData(ctx, 'C:/example.png')
        .then(console.log)
        .catch(console.log);
    }

    function createCtx(){
      var doc = document;
      var body = doc.body;
      var canvas = doc.createElement('canvas');
      var ctx = canvas.getContext('2d');

      canvas.width = w;
      canvas.height = h;

      body.appendChild(canvas);
      body.style.margin = '0px';

      return ctx;
    }

    async function saveImageData(ctx, filePath){
      var canvas = ctx.canvas;
      var width = canvas.width;
      var height = canvas.height;

      var imgd = ctx.getImageData(0, 0, width, height);
      var data = imgd.data;

      var len = filePath.length + width * height + 3 << 2;
      var buff = new ArrayBuffer(len);
      var view = new DataView(buff);
      var i = 0;

      view.setUint32(0, filePath.length, 1);

      [...filePath].forEach(char => {
        view.setUint32(i += 4, char.charCodeAt(0), 1);
      });

      view.setUint32(i += 4, width, 1);
      view.setUint32(i += 4, height, 1);

      var base = i + 4;

      data.forEach((byte, index) => {
        view.setUint8(base + index, byte);
      });

      return await send(view, 1);
    }

    async function send(data, mode=0){
      var xhr = new XMLHttpRequest();
      xhr.open('POST', `http://${HOST}:${PORT}`);
      xhr.send(data);

      return await new Promise((res, rej) => {
        xhr.onreadystatechange = () => {
          if(xhr.readyState === 4){
            if(xhr.status !== 200)
              return rej(xhr.status);

            switch(mode){
              case 0: res(xhr.responseText); break;             // Plain text
              case 1: res(JSON.parse(xhr.responseText)); break; // JSON
              case 2: res(new Uint8Array(xhr.response)); break; // Binary
            }
          }
        };
      });
    }
  });
})();
```

### server.js

```js
'use strict';

var http = require('http');
var cp = require('child_process');

const PORT = 8080;
const ALLOW_ANY_ORIGIN = 1;

var nop = () => {};
var server = http.createServer(onReq).listen(PORT);

function onReq(req, res){
  if(ALLOW_ANY_ORIGIN)
    res.setHeader('Access-Control-Allow-Origin', '*');

  var data = Buffer.alloc(0);

  req.on('data', d => {
    data = Buffer.concat([data, d]);
  });

  req.on('end', () => {
    processData(data)
      .then(status => {
        res.end(JSON.stringify({status}));
      }).catch(error => {
        error = error.toString();
        res.end(JSON.stringify({error}));
      });
  });
}

async function processData(data){
  var filePathLen = data.readUInt32LE(0);
  var filePathBuff = data.slice(4, filePathLen + 1 << 2);
  data = data.slice(filePathLen + 1 << 2);

  var filePath = '';
  for(var i = 0; i < filePathLen; i++)
    filePath += String.fromCharCode(filePathBuff.readUInt32LE(i << 2));

  var width = data.readUInt32LE(0);
  var height = data.readUInt32LE(4);
  data = data.slice(8);

  return await renderImage(filePath, width, height, data);
}

async function renderImage(filePath, width, height, data){
  var args = [
    `-f`, `rawvideo`,
    `-pix_fmt`, `rgba`,
    `-s`, `${width}x${height}`,
    `-i`, `-`,

    `-y`,
    `${filePath}`,
  ];

  var proc = spawnProc('ffmpeg', args);
  proc.stdin.end(data);

  return await new Promise((res, rej) => {
    proc.on('exit', status => {
      if(status !== 0)
        return rej(status);

      res('OK');
    });
  });
}

function spawnProc(name, args){
  var proc = cp.spawn(name, ['-hide_banner', ...args]);

  proc.stderr.on('data', nop);

  return proc;
}
```

**Comment by mizramir** [comment]
@advanceddeveloper, I used your code and ran it as follows in my Chrome browser:
localhost:8080/index.htm

Should I have expected to see a new example.png on my C local drive?
Browser debug shows me the following:
![image](https://user-images.githubusercontent.com/15358993/40317769-1b379546-5d2b-11e8-8d87-c035a496034e.png)

Could you please assist?

**Comment by advanceddeveloper** [comment]
> I used your code and ran it as follows in my Chrome browser:
localhost:8080/index.htm

Why are you running it on the same port? I guess your server that listens on 8080 interferes with the `server.js` script I posted. Do you have another Node.js (or wamp) server that hosts HTML files? If yes, you need to change the port in the script I posted.

Have you properly ran the `server.js` script using `node server.js` command line option?

**Comment by gireeshpunathil** [comment]
@mizramir - is this still outstanding?

**Comment by mizramir** [comment]
@gireeshpunathil - I managed to workaround this issue. Tnx.

**Comment by gireeshpunathil** [comment]
closing this then, cheers
