### ISSUE TITLE
Disabling Keep-Alive

### ISSUE THREAD

**Issue by koxu1996** [nodejs/help#1281]
* **Node.js Version**: v10.1.0
* **OS**: Linux archPC 4.16.9-1-ARCH <span>#</span>1 SMP PREEMPT Thu May 17 02:10:09 UTC 2018 x86_64 GNU/Linux
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http

I created issue https://github.com/nodejs/node/issues/20807, but I was adivsed to ask here. I want to completely disable _Keep-Alive_, so I use `setKeepAlive(false)`, but it does not have any effect. Server code:

```
var http = require('http')

var server = http.createServer(function(req, res) {
    res.end('Hello Node.js Server!')
})

server.on('connection', function(socket) {
    socket.setKeepAlive(false)
})

server.listen(8080)
```
I tested it with browser and telnet:

```
$ telnet 127.0.0.1 8080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.1 200 OK
Date: Thu, 17 May 2018 21:05:25 GMT
Connection: keep-alive
Content-Length: 21

Hello Node.js Server!
```
As you can see, there is `Connection: keep-alive` header. I also tried _Node.js v8.11.2_ but effect was the same. Am I doing something wrong?

**Comment by advanceddeveloper** [comment]
You can try this code:

```js
'use strict';

var http = require('http');

var server = http.createServer((req, res) => {
  res.setHeader('Connection', 'close');
  res.end('Hello Node.js Server!');
});

server.listen(8080);
```

Here is the output I got:

```console
C:\> telnet 127.0.0.1 8080
GET / HTTP/1.1

HTTP/1.1 200 OK
Connection: close
Date: Sat, 19 May 2018 14:05:27 GMT
Content-Length: 21

Hello Node.js Server!

Connection to host lost.
```

**Comment by koxu1996** [comment]
@advanceddeveloper Thank you, indeed it works. I also found another way:

```
var http = require('http');

var server = http.createServer((req, res) => {
  res.shouldKeepAlive = false 
  res.end('Hello Node.js Server!');
});

server.listen(8080);
```

But these ways are "workarounds" and I am still wondering why using setKeepAlive on socket does not work?

**Comment by devsnek** [comment]
@koxu1996 the keep alive header and setKeepAlive are a bit different. one is for the http transport while the other is for the socket itself.

the keep alive header will keep the connection between the server and client alive for multiple http requests over one socket, while the socket keep-alive will re-use the same socket for consecutive socket connections to the same server (on the same port, ip, etc)

**Comment by koxu1996** [comment]
@devsnek That explains everything. Now I see there is _HTTP Keep-Alive_ and _TCP Keep-Alive_ and they are unrelated.
