### ISSUE TITLE
determine if net.Socket connection is in a good state

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1283]
I have a socket:

```js
const s = net.createConnection({port});
```
how can I determine if the connection is in a good state / bad state.

something like:
```js
if(s.writable)
```

 ?

**Comment by Globik** [comment]
s.on("error",er=>console.log(er))

**Comment by ORESoftware** [comment]
sure I guess if it experiences an error, it is in a bad state and likely won't recover?

but if the 'end' event or 'error' events first - does writable get set to false internally?

**Comment by gireeshpunathil** [comment]
yes - [here](https://github.com/nodejs/node/blob/a69a29da102488a636c5862e5f805658ba32c90d/lib/net.js#L578)

**Comment by gireeshpunathil** [comment]
@ORESoftware - are you happy here?

**Comment by ORESoftware** [comment]
yes it looks good, thanks!
