### ISSUE TITLE
How to define and instantiate a class without Object.prototype in it's prototype chain

### ISSUE THREAD

**Issue by advanceddeveloper** [nodejs/help#1286]
* **Node.js Version**: v10.1.0
* **OS**: windows
* **Scope**: code
* **Module**: /

Is there a way to create and instantiate a class such that the instantiated object doesn't have `Object.prototype` in it's prototype chain? I would like to create an object which is a direct instance of my class and inherits no properties from `Object.prototype` (`toString`, for example). Is there a way to achieve it somehow? Here is what I've tried:

```js
class Empty{};
var inst = new Empty;
console.log(inst instanceof Object); // true
```

So, classes by default inherit `Object.prototype`. I've tried this:

```js
class Empty extends null{};
```

but I got error:

```console
TypeError: Super constructor null of Empty is not a constructor
```

This is a workaround I've found:

```js
class Empty{};
Object.setPrototypeOf(Empty.prototype, null);
var inst = new Empty;
console.log(inst instanceof Object); // false
```

but I don't see why the prototype needs to be changed explicitly. I've found [this](https://stackoverflow.com/questions/41189190/how-and-why-would-i-write-a-class-that-extends-null) thread talking about the fact that classes extending `null` represent a valid JavaScript syntax, so I don't see why it throws an error in my case. The example code snippet from the comment by @ benjamingr:

```js
class Hash extends null {}
var o = {};
var hash = new Hash;
o["foo"] = 5;
hash["foo"] = 5;
// both are used as hash maps (or use `Map`).
hash["toString"]; // undefined
o["toString"]; // function
```

I don't know if it is supposed to work or not, but it throws an error in Node.js. I am wondering is this working as expected, and if yes, what am I doing wrong?

Thanks.

**Comment by addaleax** [comment]
Yes, this is a bug in the spec that is, surprisingly, not all that easy to fix. I remember discussing this in TC39 but I don’t really know what the current state of it is.

I think your workaround is correct (although you might want to add `Object.setProtototypeOf(Empty, null);` for consistency, otherwise you inherit methods like `Object.hasOwnProperty` on the constructor prototype chain.

**Comment by advanceddeveloper** [comment]
Thanks. I'll probably stick with my workaround until the bug is resolved.
