### ISSUE TITLE
Non-existent Hindi Localisation Community

### ISSUE THREAD

**Issue by sambhav2612** [nodejs/help#1287]
* **Node Version**: 9.1.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Other
* **Module (and version) (if relevant)**: N/A

I'm a seasonal content localizer and I've localized content for Mozilla and open-source projects like 24PullRequests. I came around `node-hi` repo sometime ago and found that it was not active at all and that's the primary reason of this issue. If possible can I take the torch and take this opportunity further to build a localisation community starting from my campus?

**Comment by bnoordhuis** [comment]
cc @nodejs/i18n

**Comment by gireeshpunathil** [comment]
@sambhav2612 -  closing on the assumption that you are connected now with https://github.com/nodejs/i18n repo, and you will take it from there. Let me know if that is not the case.
