### ISSUE TITLE
Exec while encoding as buffer still contains question marks instead of special characters

### ISSUE THREAD

**Issue by mm739521** [nodejs/help#1288]
* **Version**:6.10.3
* **Platform**:Windows

I'm attempting to echo a string with special characters in it (téstér) with the `child_process.exec(command[, options][, callback])` .  

stdout is returning `t?st?r`.  As per instructions I added the {encoding: 'buffer'} which is returning the buffer value of `<Buffer 74 82 73 74 82 72 0d 0a>`.  If I create a new Buffer object using `let test = Buffer.from('téstér')` I get back the value of `<Buffer 74 c3 a9 73 74 c3 a9 72>`.  

Why are these returning different values?  I'm about to decode the value from the Buffer.from object I create, with the special characters,  but when I attempt to do the same to the stdout I still get the `t?st?r` value.  

Am I doing something incorrect here?  Any help would be greatly aprreciated.

It seems the {encoding: 'buffer'} is treating the é as 82.  Which is a linebreak according to this https://www.fileformat.info/info/unicode/char/0082/index.htm

**Comment by gireeshpunathil** [comment]
#bash -version
```
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
#node -v
`v10.0.0`
#cat 1288.js 
```js
var cp = require('child_process')
let buf = Buffer.from('téstér')
var child = cp.exec('bash -c "echo -n téstér"', {encoding: 'buffer'} )
child.stdout.on('data', (d) => {
  console.log(d)
  console.log(buf)
  console.log(d.equals(buf))
})
```
#node 1288.js 
```
<Buffer 74 c3 a9 73 74 c3 a9 72>
<Buffer 74 c3 a9 73 74 c3 a9 72>
true
```
#

Everything looks good to me, are we both testing the same thing? please let me know.

**Comment by gireeshpunathil** [comment]
ping @mm739521

**Comment by gireeshpunathil** [comment]
inactive, closing
