### ISSUE TITLE
Is that possible to inject some custom variable when fork a child process

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [nodejs/help#1289]
* **Node.js Version**:v8.9.1
* **OS**:Darwin
* **Scope (install, code, runtime, meta, other?)**:code
* **Module (and version) (if relevant)**:childprocess.js
```js
myObject = { 
  method1 = () => { console.log('1') },
  method2 = () => { console.log('2') } 
}
```
I want to execute a module file at child process, but it isn't execute a file simply, i need inject some custom object into child process' all modules, eg entry module and any modules imported.
I know it's simple if i implement this in node vm, but debugger isn't supported in vm, that's also necessary for me.

**Comment by BeiKeJieDeLiuLangMao** [comment]
I have a GUI application, the js file i want to execute is edit in that application.In that app, if i click run button, that js file will been executed.

What i want to implement is a node execute space(debugger supported), and i need remove all node interfaces, and inject my custom interfaces.

**Comment by gireeshpunathil** [comment]
I am not sure I follow your requirement, but let me try - you want a Javascript execution environment (supported by a JS engine such as v8) with live debugging capability, and that coupled with a GUI front-end? Something similar to what a browser provides?

**Comment by gireeshpunathil** [comment]
ping @BeiKeJieDeLiuLangMao

**Comment by BeiKeJieDeLiuLangMao** [comment]
That's right.

**Comment by gireeshpunathil** [comment]
I guess [electron](https://github.com/electron/electron) may be the closest such thing, but I am not sure how much customizations (removal and addition of custom interfaces to Node) they would have made. Can you have a look at electron documentation and APIs to see how close / far it is from your use case?

**Comment by gireeshpunathil** [comment]
ok, thanks for the clarification. So if you remove all the Node interfaces then what you get is a bare `v8` engine that knows how to execute pure JS code - either via v8 APIs that receive scripts as input, and return result to the caller, or via a custom build `d8` shell that receives scripts as arguments and exits with the exit code from the script. Is that direction you want to take?

**Comment by BeiKeJieDeLiuLangMao** [comment]
You forget that v8 doesn't support debugging

**Comment by gireeshpunathil** [comment]
v8's [inspector apis](https://github.com/v8/v8/wiki/Debugging-over-the-V8-Inspector-API) supports debugging through inspector, and Node's consumer of that can be found here: https://github.com/nodejs/node/blob/master/src/inspector/

Because your front end is GUI, you cannot make use of Node's inspector anyways, why don't you go with the v8's inspector APIs alone? Or when you say `debugging` do you have more than what the inspector provides?

**Comment by BeiKeJieDeLiuLangMao** [comment]
My mistake, i misunderstand v8 to be v8 vm

**Comment by gireeshpunathil** [comment]
no problem - my take is that you will need to deal with `v8` anyways, as your front end is a GUI, so it is worth exploring the inspector APIs.

**Comment by BeiKeJieDeLiuLangMao** [comment]
Could i use v8 APIs in node?Or maybe i must build multi-platform binary and use it by subprocess?

**Comment by gireeshpunathil** [comment]
you CAN use it in Node.

**Comment by BeiKeJieDeLiuLangMao** [comment]
Do you mean this [v8](https://nodejs.org/dist/latest-v10.x/docs/api/v8.html)?

**Comment by gireeshpunathil** [comment]
yes, that `v8` , but those APIs belongs to `Node.js`, as wrappers - the actual APIs sit inside [this v8](https://chromium.googlesource.com/v8/v8.git/) . Once you remove all Node.js interfaces, you will need to directly invoke the v8 APIs which the Node.js's `v8` API abstractions are invoking.

**Comment by BeiKeJieDeLiuLangMao** [comment]
That's written by c++, isn't it?So i ask you previous question "Could i use v8 APIs in node?Or maybe i must build multi-platform binary and use it by subprocess?"Is these any JavaScript wrappers for complete v8 engine?

**Comment by gireeshpunathil** [comment]
yes, that is written in C++ and consumable by C++ apps.

> Is these any JavaScript wrappers for complete v8 engine?

That is Node. :)

So if you want to remove Node interfaces - yes, you must build multi-platform binary and use it by subprocess.
