### ISSUE TITLE
node.js

### ISSUE THREAD

**Issue by hexiaokang** [nodejs/help#129]
javaScript vs node.js

**Comment by lordKnighton** [comment]
nodejs run atop javascript. like rails runs on ruby, django runs on python, c# runs on c.

**Comment by subfuzion** [comment]
Hi @hexiaokang. Node.js is a platform for creating high performance applications (generally servers) based on a non-blocking I/O model. The browser is primarily a platform for the World Wide Web. Both platforms use JavaScript, a programming language. Saying "javascript vs node" is like saying "javascript vs the browser." Neither statement makes sense like that. Closing the issue. If you have any other more specific questions, please submit a new issue.
