### ISSUE TITLE
Child Process launching a shortcut file with spawn not working

### ISSUE THREAD

**Issue by encloinc** [nodejs/help#1290]
* **Version**: 8.11.2 LTS
* **Platform**: Windows 10
* **Subsystem**: childprocess.js

Is there any way to open a shortcut file with child process and spawn and have it use all the parameters found inside it? Ik this is possible with exec() but then i wouldn't be able to get the PID of the shortcut im launching. Thanks in advance :)

**Comment by gireeshpunathil** [comment]
#which node
`/usr/local/bin/node`
#ln -s `which node` foo.ln
#cat 1290.js 
```js
const cp = require('child_process')
const fs = require('fs')
const path = require('path')
var link = fs.readlinkSync('foo.ln')
var real = path.resolve(link)
console.log(real)
const child = cp.spawn(real, ['-v'])
child.stdout.on('data', (d) => {
  console.log(d.toString())
})
```
#node 1290.js 
```
/usr/local/bin/node
v10.0.0
```
#

logic does not change for windows, only the path separators.

Hoep this helps.
