### ISSUE TITLE
Reading incoming HTTPS headers from Spring Boot 2 response with https node.js lib

### ISSUE THREAD

**Issue by Alexis-Dk** [nodejs/help#1291]
I am using  https node.js lib for getting response header. I sent the request using Postman and got the 11 parameters in the response header. Also with Chrome browser I also get 15 params in the response header. But, if use https node.js lib i get only 4 params in the response header (line - console.log("Headers: ", res.headers);).
I need to get at least 11 parameters using https node.js lib.
As the backend server is used Spring Boot 2.
Here screenshot with params getting with Postman, Chrome and https lib: [https://drive.google.com/drive/folders/16kcIeZnFa1pQ7brX62A-uB4YGKgrK2L6](url) 
and code:

` 
    var options = {
    hostname: hostname,
    port: port,
    path: pathMethod,
    method: method,
    headers: { "Content-Type": APPLICATION_JSON, "Authorization": BEARER + localStorage.jwtToken},
    rejectUnauthorized: false,
    agent: false,
    requestCert: false
    }

    return new Promise(function(resolve, reject) {
    var req = https.request(options, function(res) {
    res.setEncoding(ENCODING_UTF8);
    console.log("Headers: ", res.headers);
    res.on("data", function(result) {

            try {
                const obj = JSON.parse(result);
                resolve({ 'httpStatus': PAGE_STATUS_200, 'result': obj });
            }
            catch(error) {
                console.error(error);
                resolve(resolve({ 'httpStatus': PAGE_STATUS_500 }));
            }
        });

        res.on('end', () => {
            console.log('No more data in response.');
        });
    });

    req.on('error', function(err) {
        console.log('problem with request: ${err.message}');
        reject(err);
    });

    if (postData) {
        req.write(postData);
    }

    req.end();
});`

**Comment by gireeshpunathil** [comment]
I don't have the spring boot endpoint so cannot test with that. But as you can see, the headers sent from servers are reaching client without any issues.

#cat 1291.js 
```js
var h = require('http')
var s = h.createServer((q, r) => {
  r.setHeader('Content-Type', 'text/html');
  r.setHeader('Set-Cookie', ['type=ninja', 'language=javascript']);
  r.setHeader('A', 'B')
  r.setHeader('C', 'D')
  r.end('hello')
})
s.listen(8080, () => {
  h.get('http://localhost:8080', (m) => {
    console.log(m.headers)
  })
})  
```
#node 1291.js 
```c++
{ 'content-type': 'text/html',
  'set-cookie': [ 'type=ninja', 'language=javascript' ],
  a: 'B',
  c: 'D',
  date: 'Fri, 25 May 2018 12:43:10 GMT',
  connection: 'close',
  'content-length': '5' }
^C
```

It may be possible that there are some headers that the Node.js client deem invalid and discard before passing onto the app. Can you provide the list of headers that you got from other clients and missing in Node.js client, so that some SMEs can provide guidance.

/cc @nodejs/http

**Comment by gireeshpunathil** [comment]
ping @Alexis-Dk

**Comment by Alexis-Dk** [comment]
i should be added annotation at servev-side spring boot 2:
Access-Control-Expose-Headers: Access-Token, Uid

**Comment by gireeshpunathil** [comment]
thanks, how will I simulate in our JS server? like this?
`response.setHeader('Access-Control-Expose-Headers', 'Access-Token, Uid')`

it does not produce the issue. Is the above semantics right?

**Comment by Alexis-Dk** [comment]
Yes, semantic is right. Maybe, it's only related spring boot 2 backend-server problem.

**Comment by gireeshpunathil** [comment]
@Alexis-Dk - close candidate?

**Comment by Alexis-Dk** [comment]
Yes
