### ISSUE TITLE
Error: connect ECONNREFUSED, CouchDB NANO

### ISSUE THREAD

**Issue by FrancescoXD** [nodejs/help#1294]
* **Node.js Version**: 8.x with ExpressJS
* **OS**: Linux (Ubuntu 18.04)

I use CouchDB, with NANO.
Hello, I have a problem when i run this code:

```js
var nano = require("nano")("http://localhost:9999");
nano.db.create("users");
var utenti = nano.db.use("users");

utenti.insert({name: "Test"}, null, function(err, body) {
  if(!err) {
    console.log(body);
  }
});

utenti.list(function(err, body) {
  console.log(body.rows);
});
```
I have this error:

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 127.0.0.1:9999
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

Thanks!

**Comment by gireeshpunathil** [comment]
Usually `ECONNREFUSED` means the client is not able to reach the server, in this case the nano db. Is its instance running, and listening at `9999`?

**Comment by FrancescoXD** [comment]
@gireeshpunathil Fixed, now I'm using MySQL 6

**Comment by gireeshpunathil** [comment]
closing then, cheers!
