### ISSUE TITLE
how event loop handels multiple request?

### ISSUE THREAD

**Issue by poojaniranjane** [nodejs/help#1295]
I have one question , if event loop picks request one by one then on user side it has to wait for longer time to get that o/p in case of multiple requests.
Suppose n clients send their request to one server and each request require 15 seconds then if go by logic of event loop then if will take first request from event queue and process it and then send response to client , then it will fetch 2nd one and send response so by this logic first client will get data in 15 seconds and then 2nd will get data in 30 and so on.. So how node is handling these things as i know i m interpreting something wrong.

**Comment by gireeshpunathil** [comment]
the connected links should cover what you are asking for, if not please let me know.
