### ISSUE TITLE
HMR with dynamic import() - What are your thoughts about it?

### ISSUE THREAD

**Issue by idleman** [nodejs/help#1297]
* **Node.js Version**: 10.0.0
* **OS**: WIndows 10
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**:

With the latest version of node, is it possible to support hot module replacement, using dynamic import(). What are your thoughts about it? 
Gist: https://gist.github.com/idleman/8d57f7e3479bc8ce534ab330195904fb 

Personally do I like it very much, but wondering if it would be a good idea. What are your thoughts?

**Comment by benjamingr** [comment]
I think that with live bindings and passing a `--loader` you can do this without requiring a `onCodeChange` to be called explicitly inside modules.

Pretty cool by the way.

I want to point out there is a lot of modules discussion going in Node.js and you are welcome to participate! It's in https://github.com/nodejs/modules and there are several areas that could use help.

**Comment by ljharb** [comment]
I would not expect that it is possible at the moment (hot loading with static import might not be either).

The current hacks used to do hot loading with CJS could, however, be eventually replaced with a custom ESM loader.

**Comment by benjamingr** [comment]
@ljharb 

> I would not expect that it is possible at the moment (hot loading with static import might not be either).

What do you mean? Why would it not be possible? It might not be _valid_ since state can change - but if you write code in a certain way it can be done - and the OP actually posted a gist that does this in some capacity I believe.

**Comment by ljharb** [comment]
Because import doesn’t have a mutable module cache like CJS does.

**Comment by ljharb** [comment]
(Note that it’s not hot reloading if the reloaded module has to be authored any differently; in that case it’s just live bindings, and dynamic import can do it too)

**Comment by benjamingr** [comment]
@ljharb I might be misunderstanding, but can't you just import the module separately (for example - copy it elsewhere - import it - and tie in all the live bindings to the latest version)?

> (Note that it’s not hot reloading if the reloaded module has to be authored any differently; in that case it’s just live bindings, and dynamic import can do it too)

Yeah - I'm not sure how that's different from "real" hot reload.

**Comment by devsnek** [comment]
@ljharb you can simulate it with two modules for every module you want to hot swap. if we want to do better than that I would leave it to v8 developer tools mechanisms

**Comment by guybedford** [comment]
Hot reloading could be supported through disposing module records and reinstanatiating them and this is what SystemJS does for these workflows.

Live bindings can't be updated though this way, unless a spec change is made on this front - which is an interesting thing to explore too.

**Comment by ljharb** [comment]
@benjamingr if you do that, then the module path changes for all consumers. “Real” hot reloading is when it’s transparently layered on top.

**Comment by benjamingr** [comment]
@ljharb is there an observable difference from the perspective of the code consuming the "hot reloaded" code?

(Sorry if I'm being annoying with all these questions! I'm a lot less experienced than some of the other members with this!)

**Comment by bmeck** [comment]
I have a question, is this about `import(...)` in particular / absolutely not static importing, or also expecting HMR  to work with `import ... from ...;`?

**Comment by ljharb** [comment]
@benjamingr the observable difference is that any component can be hot-reloaded if it's transparent; otherwise the author has to cooperate.

@idleman a custom loader would basically replace everything with a Proxy, like react-hot-loader and similar does.

**Comment by devsnek** [comment]
@idleman what I did is use dynamic instantiate and a vm.Module which reloads when the fs changes and resets the values of the dynamic instantiate exports.
