### ISSUE TITLE
What is the first parameter of a Writeable stream's close event handler?

### ISSUE THREAD

**Issue by pushkin-** [nodejs/help#1298]
* **Node.js Version**: 8.9.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: code/runtime?
* **Module (and version) (if relevant)**: writeable streams

Copying from [here](https://stackoverflow.com/q/49516512/3479456).

When a [`Writeable` stream](https://nodejs.org/api/stream.html#stream_class_stream_writable) closes, the `close` event handler is executed with the argument `false`. The [docs](https://nodejs.org/api/stream.html#stream_event_close) don't specify what that parameter represents like they do for the [`error`](https://nodejs.org/api/stream.html#stream_event_error) event. What does `false` mean in this case?

```
let proc: ChildProcess = cp.spawn(somePath);
proc.stdin.on("close", () => { // kill the spawned process to execute this handler
    console.log(arguments); // [false]
}
```

**Comment by gireeshpunathil** [comment]
#cat 1298.js 
```js
require('child_process').spawn('ls').stdin.on('close', () => {
    console.trace()
})
```
#node 1298.js
```trace
Trace
    at Socket.require.spawn.stdin.on (/Users/gireeshpunathil/Desktop/support/1298.js:2:13)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```
#

[isException](https://github.com/nodejs/node/blob/7d77068c786d81fa43b6b6d80ac97e1bd53be4c8/lib/net.js#L596)

Hope this helps!

**Comment by pushkin-** [comment]
@gireeshpunathil Thanks! And could you just expand on what `isException` means exactly? So if the process gets force-killed, `isException` is `false` (or if it dies of natural causes), but if an exception within Node causes the stream to close, then `isException` will be `true`?

**Comment by gireeshpunathil** [comment]
that is right. all the child process related errors will be routed to its error handler. 
Only the stream related go into the stream's handler. example: if the child process destroys its stdin the parent side of the pipe errs and gets destroyed and subsequently closed.

In general, a stream.close is invoked if you close the stream manually, or it gets destroyed for various reasons. Unnatural destructions always emit close with the exception value to true.
