### ISSUE TITLE
Help! Understanding stream more

### ISSUE THREAD

**Issue by samundrak** [nodejs/help#1299]
If I have a stream and after some consumption, if I paused the data flow then will it stop reading data from a source or it will continue reading data but will put it in the buffer?

**Comment by gireeshpunathil** [comment]
In tcp streams for example (or any streams whose data source is a remote end point), the read will continue until the internal buffer reaches a threshold (internally termed as high water mark), beyond which it stops reading. Once the stream resumes, the data is drained from the buffer into the user's callback, and the reading starts again. (However, I guess there are core modules that implement the stream abstraction for basic capabilitites but customize data flow models based on their need.)

In general the above explanation holds good for Node.js streams.

Hope this helps.
