### ISSUE TITLE
How to properly extend a buffer?

### ISSUE THREAD

**Issue by advanceddeveloper** [nodejs/help#1300]
* **Node.js Version**: v10.1.0
* **OS**: windows
* **Scope**: code
* **Module**: Buffer

I tried something like

```js
'use strict';

class Bit extends Buffer{
  constructor(...args){
    super(...args);
  }

  getBit(index){
    return (this[index >> 3] >> (index & 7)) & 1;
  }

  setBit(index, value){
    if(this.getBit(index) === value) return;
    this[index >> 3] ^= 1 << (index & 7);
  }
};

var bit = new Bit([1, 255]);
bit.setBit(3, 1);
bit.setBit(15, 0);

console.log(Array(16).fill().map((a, i) => {
  return bit.getBit(i);
}).join(''));
```

and got `TypeError: bit.setBit is not a function`. I know the Buffer constructor is deprecated, but is there a way to extend it then? I didn't get any deprecation warnings for this particular code snippet, I just got the type error.

**Comment by addaleax** [comment]
This has been discussed a couple times in the past – some ways to work around this (although it might not be fast) would be:

- Adding `Object.setPrototypeOf(this, new.target.prototype);` in the constructor, after `super()` (simple, but slow & still gets the deprecation); or:
- Switching to `extends Uint8Array`, and manually adding `Object.setPrototypeOf(Bit.prototype, Buffer.prototype);` after the class definition. (Downside here being that the `Bit` constructor itself does not inherit from `Buffer`, e.g. `Bit.from !== Buffer.from` and that the `Bit` constructor only takes `Uint8Array`-style arguments).

It might be worth taking another look at extensibility here from our side, but generally the decision to deprecate the `Buffer` constructor stands.

**Comment by advanceddeveloper** [comment]
Thanks.

I didn't say I'm against deprecation of the Buffer contructor, I was just wondering what would be the best way to extend the Buffer.

Your workarounds seem helpful and since the performance is not much important to me, I think I'll try it.
