### ISSUE TITLE
Unexpected OUTPUT [child_process.spawn]

### ISSUE THREAD

**Issue by atombug** [nodejs/help#1302]
* **Version**: 10.2.1
* **Platform**: Windows 10 64-bit
* **Subsystem**: child_process.spawn()

Scenario: 
               I was creating a nodejs library but with help of powershell. I used child_process.spawn() and passed two commands in arguments and it gives (lets see practically weired thing).

* **Code**:
```
var spawn = require("child_process").spawn;
child = spawn("powershell.exe", ['echo test1; echo test2']);
child.stdout.on("data", function (data) {
   let inputs = data;
   console.log(typeof(inputs));
});
child.stdin.end();
```

* **OUTPUT**:
```
object
object
```

* **ISSUES**:

 After converting it to a String with ".toString()" methods output remains same.

```
string
string
```

Now if i apply any method it applies to both and i also tried to convert it into array still same output. Now weird thing takes place if i tries to get first element of array then it returns first elements form both array.

So question/issue is how to combin all Buffers into one so output would look like below?

```
string
```

**Comment by ORESoftware** [comment]
try this:

```js
const cp = require('child_process');
const k = cp.spawn("powershell.exe", ['echo test1; echo test2']);
let stdout = '';
k.stdout.on("data", function (data) {
  stdout += String(data);
});
k.stdin.end();

k.once('exit', function(code){
  // now do something with the stdout string data variable
});
```

**Comment by atombug** [comment]
Thank you for your suggestion @ORESoftware . But spwan takes more time then exec am i right?

**Comment by ORESoftware** [comment]
I  think exec buffers the stdout/stderr, so if you want to use streaming output, spawn is better. spawn will be much faster for that reason.

**Comment by atombug** [comment]
@ORESoftware ,

How to access stdout of child_process.exec() in outside of it?

**Comment by gireeshpunathil** [comment]
#cat 1302.js 
```js
var cp = require('child_process')
child = cp.exec('/bin/bash -c "echo test1 && echo test2"')
child.stdout.on('data', (d) => {
   console.log(d)
});
```
#node 1302.js 
```trace
test1
test2
```

you may replace `bash` with `powershell`

**Comment by atombug** [comment]
@gireeshpunathil but in windows bash is not available.

**Comment by gireeshpunathil** [comment]
right - the callbacks are called every time there is a piece of data that is available. So in your case you get 2 callbacks, as the child process made 2 data chunks available, discretely.

Solution is exactly as @ORESoftware mentioned, pile them up into an internal buffer, and use it when the stream ends.

**Comment by atombug** [comment]
Agreed, may be you can close this issue now as i am satisfied with answer.

 :+1: @gireeshpunathil

**Comment by gireeshpunathil** [comment]
cheers!

**Comment by advanceddeveloper** [comment]
@atombug 

What @ORESoftware said is correct, but it doesn't work if multi-byte characters appear in the stream (which, in general case, may happen). See also https://github.com/nodejs/help/issues/1029#issuecomment-352626571

The best solution (and probably the fastest one) is to concatenate all chunks into a single buffer and then stringify it once the powershell exits:

```js
'use strict';

var cp = require('child_process');
var child = cp.spawn('powershell.exe', ['echo test1; echo test2']);
var buffer = Buffer.alloc(0);

child.stdout.on('data', data => {
  buffer = Buffer.concat([buffer, data]);
});

child.on('exit', () => {
  var output = buffer.toString('utf8');
  console.log(output);
})

child.stdin.end();
```
