### ISSUE TITLE
child_process.exec()'s stdout in outerscope

### ISSUE THREAD

**Issue by atombug** [nodejs/help#1303]
* **Version**: 10.2.1
* **Platform**: Windows 10 64-bit
* **Subsystem**: child_process.exec()

Scenario: 
               I was creating a nodejs library now that is nearly complete i just want to export it but problem is how to access stdout of exec() outside of it's scope.

* **Code**:
```
let data = "";
const { exec } = require('child_process');
exec('echo test', (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  data = stdout;
  console.log(`stdout: ${stdout}`);
});
console.log(data);
```

* **OUTPUT**:
```
stdout: test

```

**Comment by atombug** [comment]
@gireeshpunathil that may be inefficient as i wanted to publish library (module) on npm and relying on settimeout doesn't seems to good for that, what is your opinion?

**Comment by gireeshpunathil** [comment]
agree, please treat it as a sample only to show where, and how the data vanished, and how and from where it is replenished.

To export the data to outside, the proposal that @OREsoftware showed looks great to me!

**Comment by atombug** [comment]
i am bit confused now @ORESoftware  @gireeshpunathil 

how to export solution of @ORESoftware with module.exports or exports.lib?

**Comment by ORESoftware** [comment]
@atombug you can't export it synchronously, unless you use `execSync`.

**Comment by atombug** [comment]
Agreed to use execSync, but how ``` stderr ``` is handled in it?

nodejs docs needs to give atleast one example as it only states

```
stdio <string> | <Array> Child's stdio configuration. 
stderr by default will be output to the parent process' stderr unless stdio is specified. 
Default: 'pipe'.

```

**Comment by gireeshpunathil** [comment]
#cat 1303.js
```js
module.exports.echo = function(cb){
  const { execSync } = require('child_process');
  const out = execSync('echo test')
  console.log(`stdout: ${out}`);
}
```
#node
```repl
> var module = require('./1303.js')
undefined
> module
{ echo: [Function] }
> module.echo()
stdout: test

undefined
>
```

Basically the `sync` methods do not call back, instead return with the intended data. Hope this example helps you with that. Please free to come up with PRs if doc needs improvements!

**Comment by atombug** [comment]
so how can i handle errors / return error with execSync?

**Comment by gireeshpunathil** [comment]
errors if any, will be returned to the caller, in the return value.

**Comment by atombug** [comment]
and that isn't good can we supress it or how to tell if isnt worked?

**Comment by gireeshpunathil** [comment]
sorry for misleading: that was an incorrect information.

excerpt from the doc:
`If the process times out or has a non-zero exit code, this method will throw. The Error object will contain the entire result`

So the error does not return to the caller, it throws. the return value is populated with the child's stdout data only.

**Comment by atombug** [comment]
if you don't mind can you give me one example of it (handling error object).

**Comment by gireeshpunathil** [comment]
#cat 1303.js
```js
module.exports.echo = function(cb){
  let data = "";
  const { execSync } = require('child_process');
  const out = execSync('echos test')
  console.log(`stdout: ${out}`);
}
```
#cat 1303_1.js 
```js
var x = require('./1303.js')
try {
  x.echo()
}
catch(e) {
  console.log(e.toString())
}
```
#node 1303_1.js 
```trace
/bin/sh: echos: command not found
Error: Command failed: echos test
/bin/sh: echos: command not found
```
#

**Comment by atombug** [comment]
Thank you for your suggestion.
btw i didnt enjoyed how it handles error (as i wanted it to be done in my module) so i found alternative:
```
const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function test() {
  const { stdout, stderr } = await exec('echo test');
  if (stderr) {
    return {"error": stderr};
  }
  return {"data": stdout};
};

module.exports = test();
```

* Now, a simple call 
```
let test = require('./test');

test.then(x => {
    console.log(x);
});

```

Is this good way ?? if not suggest me a good one. @ORESoftware @gireeshpunathil

**Comment by gireeshpunathil** [comment]
looks great to me!

**Comment by gireeshpunathil** [comment]
@atombug - anything outstanding here? are we good to close this?

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if there is anything outstanding

**Comment by julia-jumpbowed61** [comment]
@gireeshpunathil https://mack-photo.github.io/vasco/
