### ISSUE TITLE
Issue installing Node on 'Deploy Linux' on Android

### ISSUE THREAD

**Issue by siordache94** [nodejs/help#1304]
* **Node.js Version**: should be "8.11.2"
* **OS**: Linux localhost 4.4.78-perf+ #1 SMP PREEMPT Fri Apr 20 12:25:33 CST 2018 aarch64 GNU/Linux
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: not relevant

Hi, 

I have downloaded [node-v8.11.2-linux-arm64](https://nodejs.org/dist/v8.11.2/node-v8.11.2-linux-arm64.tar.gz)
I executed `tar -C /usr/local --strip-components 1 -xzf node-v8.1.1-linux-x64.tar.gz` from [stackoverflow](https://stackoverflow.com/questions/33033538/installing-a-tar-gz-on-linux)
 and this is my problem : 
```
root@localhost:/usr/local# ls -l bin/node
-rwxr-xr-x. 1 root root 35203592 May 16 05:25 bin/node
root@localhost:/usr/local# file bin/node
bin/node: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=59ee95ef38bbe8259a7c2478b67f45ca9facde8b, not stripped
root@localhost:/usr/local# ls -l bin/node
-rwxr-xr-x. 1 root root 35203592 May 16 05:25 bin/node
root@localhost:/usr/local# file bin/node
bin/node: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=59ee95ef38bbe8259a7c2478b67f45ca9facde8b, not stripped
root@localhost:/usr/local# ./bin/node
bash: ./bin/node: No such file or directory

```

Thanks in advance

**Comment by gireeshpunathil** [comment]
do you have `strace` in your system? if so can you issue: `strace -f ./bin/node` and paste the output?

**Comment by siordache94** [comment]
@gireeshpunathil 
'''
root@localhost:/usr/local# strace ./bin/node
execve("./bin/node", ["./bin/node"], [/* 18 vars */]) = -1 ENOENT (No such file or directory)
fstat64(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
write(2, "strace: exec: No such file or di"..., 40strace: exec: No such file or directory
) = 40
getpid()                                = 22240
exit_group(1)                           = ?
+++ exited with 1 +++
'''

**Comment by gireeshpunathil** [comment]
what does `getfacl -a ./bin/node` show? looks like an access issue. are you `root`?

**Comment by siordache94** [comment]
@gireeshpunathil 
```
root@localhost:/usr/local# getfacl -a ./bin/node
# file: bin/node
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
```

my "ls -l" gave you the same information no ? 
and as you can see I'm root

**Comment by gireeshpunathil** [comment]
@siordache94 - thanks. a dot at the end of `-rwxr-xr-x.` and the wrong error message (`No such file or directory`) made me look at the direction of access control issues. 

Now since that does not seem to be the case, barring the word meaning of the error message, it could be due to `Exec format error` (loader expects a file format for the binary but the actual is something else). As Linux here is an emulation on top of Android, does it adhere to the underlying architecture (ARM) or it hides that and provide an X64 binary interface, is something I don't know.

But which Node.js binary needs to be used will depend on that answer.

Let us ask @nodejs/build

**Comment by Trott** [comment]
I'm pretty sure this would be an edge case as we don't have official support for Android. (Would love to have it, but it would require someone championing it and doing a lot of work, not to mention figuring out how to get some Android devices into Jenkins.) I don't even think we have unofficial builds for Android available.

One Collaborator who took an interest in Android is @eljefedelrodeodeljefe. Let's see if pinging him gets us anywhere.

**Comment by gireeshpunathil** [comment]
ping @eljefedelrodeodeljefe to see if we get an insight.

**Comment by gireeshpunathil** [comment]
@siordache94 - is this still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing
