### ISSUE TITLE
cluster worker kill

### ISSUE THREAD

**Issue by hasezoey** [nodejs/help#1306]
* **Node.js Version: 10@latest**
* **Windows 10@latest**
* **Module cluster**

why does `cluster.workers[id].process.kill('SIGTERM')` function while `cluster.workers[id].kill('SIGTERM')` kills only 2

```js
            for (const id in cluster.workers) {
                cluster.workers[id].send(nBlock, (err) => {
                    if (err) console.error(err);
                });
            }

            cluster.on('message', (worker, msg) => {
                console.log(msg); //DEBUG
                if (typeof msg == 'object') {
                        for (const id in cluster.workers) {
                            console.log(`killing ${cluster.workers[id].id}`.red); 
                            //cluster.workers[id].kill('SIGTERM'); // this does only kill 2 workers, others are still active ... why?
                            cluster.workers[id].process.kill('SIGTERM'); // this kills all
                        }
                    } else {
                        console.log(msg);
                    }
            });
```

**Comment by gireeshpunathil** [comment]
@hasezoey - I don't see the problem you are describing.

#cat 1306.js 
```js
const cluster = require('cluster');

if (cluster.isMaster) {
  for (let i = 0; i < 4; i++) {
    cluster.fork();
  }
  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
  
  setTimeout(() => {
    if(process.argv[2] === 'true')
      cluster.workers['1'].process.kill('SIGTERM')
    else
      cluster.workers['1'].kill('SIGTERM')
  }, 4000)

  setInterval(() => {
    console.log(``)
  }, 2000)

} else {
  setInterval(() => {
    console.log(`I am a worker, with ${process.pid}`)
  }, 2000)
}
```
#node 1306.js true
```gdb
I am a worker, with 61059
I am a worker, with 61058
I am a worker, with 61057
I am a worker, with 61056
worker 61056 died

I am a worker, with 61059
I am a worker, with 61057
I am a worker, with 61058

I am a worker, with 61059
I am a worker, with 61057
I am a worker, with 61058

I am a worker, with 61059
I am a worker, with 61058
I am a worker, with 61057
^C
```

#nde 1306.js false
```gdb
I am a worker, with 61062
I am a worker, with 61064
I am a worker, with 61065
I am a worker, with 61063

worker 61062 died
I am a worker, with 61064
I am a worker, with 61065
I am a worker, with 61063

I am a worker, with 61064
I am a worker, with 61065
I am a worker, with 61063

I am a worker, with 61064
I am a worker, with 61063
I am a worker, with 61065
^C
```
#node -v
`v10.0.0`
#

I don't know how big and complex is your code so cannot speculate on the reason of your observation. 

when you say: `this kills all` does it kill the master process too?

**Comment by hasezoey** [comment]
`this kills all` i mean only the workers...
and what should be/ is `argv[2]`?

**Comment by gireeshpunathil** [comment]
> this kills all i mean only the workers...

ok, thanks

> and what should be/ is argv[2]?

true or false

> and i dont know why but only .kill() did not kill all, only 2, everytime

how big is the complete code? is it possible to provide a complete, running code?

**Comment by hasezoey** [comment]
with `and what should be/ is argv[2]?` i mean what is it for a variable, not that it is a bool

> how big is the complete code? is it possible to provide a complete, running code?
no, sorry i already recoded it

**Comment by gireeshpunathil** [comment]
>  i mean what is it for a variable, not that it is a bool

Sorry, I ddn't get you. The point I am making is: in the 2 iterations of my running, first run I pass true, and hence cluster.workers['1'].process.kill() is invoked, and in the second iteration, I pass false, and hence cluster.workers['1'].kill() is being invoked, and if you see the result, there is no change, only one worker is being killed every time, irrespective of the invocation.

So I doubt your code has some unknown issue in it by which you are observing this behavior.

**Comment by hasezoey** [comment]
thanks yet i understand for what `.argv[2]` is, and from where it came (/ the meaning of it)

main.js
```
for (const id in cluster.workers) {
    cluster.workers[id].send('stop');
}
```

child.js
```
class something {
    constructor(d) {
        this.d = d;
        this.stop = false;
    }

    someloop() {
        while (!this.stop) {
            doSomeHashing();
        }
    }
}
var instance;
process.on('message', (msg) => {
    if (msg == 'stop') {
        instance.stop = true;
    } else {
        instance = new something(msg);
        instance.someloop();
    ]
});
```
this didn't work, so i tried to do it with worker.kill

main.js
```
for (const id in cluster.workers) {
    cluster.workers[id].kill('SIGTERM');
}
```
but this only killed at most 2 workers, out of 7

then i found `worker.process.kill`
main.js
```
for (const id in cluster.workers) {
    cluster.workers[id].process.kill('SIGTERM');
}
```
and this worked ... idk where the difference is, but so it worked 

but yet i use instead of worker.send i use yet socketio

**Comment by gireeshpunathil** [comment]
> this didn't work, so i tried to do it with worker.kill
`instance.stop = true;` is what you expect to `stop` the worker? that does not happen. When you pass `stop` message what do you actually want? disconnect the worker from the channel, or terminate the process? you could call `process.disconnect` in the worker if you want to gracefully terminate, or you could do `process.exit()` in worker as well. `instance.stop = true` does not do either.

**Comment by hasezoey** [comment]
i wanted not to kill the workers first, but the `instance.stop` didnt stop the while loop, so i must use kill

**Comment by gireeshpunathil** [comment]
again, unable to follow you fully. Do you mean to say you use `instance.stop = true` as a mean to come out of the while loop, and then expect the worker to terminate naturally? as there is no more code to run?

**Comment by hasezoey** [comment]
```js
         while (!this.stop/*<------*/) {
            doSomeHashing(); 
            // OR
           console.log('still here'); 
           // both are still there
        }
```

**Comment by gireeshpunathil** [comment]
ok, I guess I got what you are saying. Just by exiting the while loop does not end the worker, as it has established communication channels with the master. You need to explicitly disconnect the worker from master.

#cat 1306.js 
```js
const cluster = require('cluster');

if (cluster.isMaster) {
  for (let i = 0; i < 4; i++) {
    cluster.fork();
  }
  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });

  setTimeout(() => {
    for (const id in cluster.workers) {
      cluster.workers[id].send('stop');
    }
  }, 1000)

} else {
  process.on('message', (msg) => {
    if (msg == 'stop') {
      console.log('exiting')
      process.disconnect()
    }
  });
}
```
#node 1306.js 
```
exiting
exiting
exiting
exiting
worker 61815 died
worker 61816 died
worker 61817 died
worker 61818 died
#
```
Hope this helps.

**Comment by hasezoey** [comment]
no, i sayed i will keep the worker alive, but end the while loop ...

**Comment by gireeshpunathil** [comment]
ok - so have your class like this:
```js
class something {
    constructor(d) {
        this.d = d;
        this.stop = false;
        this.count = 0
    }
    someloop() {
      while (!this.stop && this.count++ < 100) {
        // doSomeHashing();   
        console.log('still here');   
      }
      this.count = 0
      setImmediate(() => {
        this.someloop.bind(this)
      })
    }
}
```


Explanation: Once the worker enters the while loop, there is no way for the single thread to come out of it and check the messages. So occasionally (controlled by a count variable) you need to come out for the rest of the code to be executed.

Hope this helps!

**Comment by hasezoey** [comment]
problem: 
i made an console.log to when a msg is received, and it logs it to the console, so i think it checks it.

**Comment by hasezoey** [comment]
the problem dont exists anymore, because i use yet socketio for the "stop" event

and i tried only to keep the workers alive but stopping the while loop to give them a new "job"

**Comment by gireeshpunathil** [comment]
ok, good to know that your problem is resolved.

answer to the question `where is the difference between the two killing things`: there is no difference, my first sample code is the proof.

**Comment by hasezoey** [comment]
but then, why does the first only kill two and the other can kill all? ....

**Comment by gireeshpunathil** [comment]
closing then, cheers!

**Comment by gireeshpunathil** [comment]
we don't know - only if  I see the full code we can figure that out. The sample code which was written to examine the two ways of terminating workers showed they do the same thing, in the same way. 

So that should be it!

**Comment by hasezoey** [comment]
...ok then it is cloesed ... i dont have the full code to that anymore ... *(only a bit ... but not full (means not the important parts from here))*
