### ISSUE TITLE
Installing node modules in my local i am getting this error

### ISSUE THREAD

**Issue by RamuduPara** [nodejs/help#1307]
* **Node.js Version**:6.11.0
* **OS**:Windows
* **Scope (install, code, runtime, meta, other?)**: installing node modules
* **Module (and version) (if relevant)**:All the node modules

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ETIMEDOUT 74.122.238.10:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     d:\01-06-2018All\UUI-3-National-dev-snm\SNM\npm-debug.log

**Comment by ORESoftware** [comment]
firewall or no internet connection?

**Comment by atombug** [comment]
@RamuduPara You might have slower internet connection, try it with high-speed internet connection.

**Comment by RamuduPara** [comment]
@atombug No, The internet connection was fine it will show like firewall issue and I can't understand how to overcome this problem.

**Comment by atombug** [comment]
@RamuduPara You might need to allow nodejs / npm in windows firewall.

**Comment by gireeshpunathil** [comment]
ping @RamuduPara

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if this does not help

**Comment by RamuduPara** [comment]
@gireeshpunathil i am not understanding what you said. ```closing as answered``` what is the meaning in that?

**Comment by gireeshpunathil** [comment]
means, the issue has been addressed with a resolution suggestion, and closing with that as the reason.
