### ISSUE TITLE
npm ERR! Failed at the integer@1.0.3 install script.

### ISSUE THREAD

**Issue by lieuwe-berg** [nodejs/help#1308]
* **Node.js Version**: 8.11.2
* **OS**: Ubuntu 16.04.4 x64
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: quick.db@6.3.1 // integer@1.0.3

I didn't really know where to post this but thought that this was the most fitting place.

So I get the error `npm ERR! Failed at the integer@1.0.3 install script.` when installing quick.db. This happens to other packages rarely. This is not quick.db's fault though.

On Windows, this can be fixed with `npm -g --add-python-to-path install windows-build-tools node-gyp`, but since I'm on Ubuntu (VPS) I cannot. Does someone know the answer? Also please tell me where I should post such a thing, sorry in advance.

This is my debug:
[2018-06-01T19_31_52_541Z-debug.log](https://github.com/nodejs/help/files/2063950/2018-06-01T19_31_52_541Z-debug.log)

**Comment by ORESoftware** [comment]
```
2589 verbose lifecycle integer@1.0.3~install: unsafe-perm in lifecycle false
2590 verbose lifecycle integer@1.0.3~install: PATH: /snap/node/602/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/quick.db/node_modules/integer/node_modules/.bin:/usr/local/lib/node_modules/quick.db/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
2591 verbose lifecycle integer@1.0.3~install: CWD: /usr/local/lib/node_modules/quick.db/node_modules/integer
2592 silly lifecycle integer@1.0.3~install: Args: [ '-c', 'node tools/install' ]
2593 silly lifecycle integer@1.0.3~install: Returned: code: 1  signal: null
2594 info lifecycle integer@1.0.3~install: Failed to exec install script
```

maybe find the integer Github repo and file an issue there.

**Comment by lieuwe-berg** [comment]
I'll try that

**Comment by ORESoftware** [comment]
You should include your package.json file also

**Comment by ORESoftware** [comment]
to find out where integer is coming from, run this:

`$ npm la integer`

**Comment by lieuwe-berg** [comment]
I'm installing globally, so no package.json. What do you mean with where integer is coming from?

**Comment by gireeshpunathil** [comment]
@lieuwe-berg - is this still outstanding?

**Comment by lieuwe-berg** [comment]
Totally forgot about this open issue! `npm install <package> --unsafe-perm` worked for me.
