### ISSUE TITLE
Significant perf difference between Ubuntu 16.04 and MacOS Sierra

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1309]
I filed this issue with Node.js, but I thought I'd add it here too, to get more opinions

https://github.com/nodejs/node/issues/21091

Any idea what might causing the difference? It's rather huge in this case.

**Comment by gireeshpunathil** [comment]
@ORESoftware - I am not sure a complete problem determination has been performed so far to assert that it could be related to the TCP control factors. Should we do that? If you are fine, can you please run with `--prof` option on Linux and MAC for identical workload and identical input?

**Comment by ORESoftware** [comment]
it's basic TCP settings on Mac vs Linux. Outside of Node.js' control basically.
