### ISSUE TITLE
Nodejs install without NPM 

### ISSUE THREAD

**Issue by EslamBhaa** [nodejs/help#1310]
* **Node.js Version : v8.11.2**:
* **OS : debian 9**:
* **Scope (install)**:

I can install Nodejs but , i can not install NPM , However, follow the instructions
in [Installation·nodejs/help Wiki](https://github.com/nodejs/help/wiki/Installation)
When writing `npm version` after install **Nodejs**
The Output is...
`bash: npm: command not found`
This problem exists and all people are looking for it , Even in previous versions

We hope **node-v8.11.2-linux-x64.deb** Instead of the **node-v8.11.2-linux-x64.tar.xz**

**Comment by atombug** [comment]
@EslamBhaa You need to change your installation method. 
Try this method from [Nodejs Docs](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)

* For Nodejs version 8.x
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

* For Nodejs version 10.x
```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by gireeshpunathil** [comment]
@EslamBhaa - is this resolved?

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if this does not help
