### ISSUE TITLE
node-v10.3.0-x64.msi ended prematurely

### ISSUE THREAD

**Issue by githubca** [nodejs/help#1311]
can't install nodejs on windows 10, x64.

* **Node.js Version**:  node-v10.3.0-x64.msi
* **OS**: Windows10
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: 

here is the installation logs:
[nodejs.log](https://github.com/nodejs/help/files/2065288/nodejs.log)

**Comment by vsemozhetbyt** [comment]
See https://github.com/nodejs/node/issues/20538 with comments about antivirus.

**Comment by githubca** [comment]
I read another similar issue:
https://github.com/nodejs/node/issues/14562

then unchecked both performance counter and ETW in the feature list, it works now.

**Comment by vsemozhetbyt** [comment]
If you do need them, you can try to temporarily disable Antivirus during installation.

**Comment by gireeshpunathil** [comment]
closing as answered
