### ISSUE TITLE
Get file descriptor given socket connection

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1312]
This regards any recent Node.js version. Say I have a tcp connection:

```js
const  ws = net.createConnection({port: self.port}, () => {

  });

```

is there a way to get the file descriptor of this socket?

What I am looking to do is pass the file descriptor to a child process written in C and then modify the socket using C code. If I can modify the socket using Node.js that would be more ideal, but I think I need to use C to do it.

**Comment by lpinca** [comment]
You can get it with

```js
socket._handle.fd
```

or 

```js
socket._parent._handle.fd
```

**Comment by ORESoftware** [comment]
thanks let try that

**Comment by ORESoftware** [comment]
this might be a stupid question, but I suppose a socket server does not have a _handle?

```js
const s = net.createServer(s => {

});
```

s._handle is null here

**Comment by lpinca** [comment]
It does unless the socket was destroyed.

**Comment by gireeshpunathil** [comment]
closing as answered

**Comment by ORESoftware** [comment]
@lpinca do you know the difference between `socket._parent._handle.fd` and `socket._handle.fd` ?

**Comment by lpinca** [comment]
Yes.
