### ISSUE TITLE
cluster spawnargs

### ISSUE THREAD

**Issue by hasezoey** [nodejs/help#1313]
* **Node.js Version**: 10.3.0
* **OS**: Windows 10 + SubSystem Ubuntu + Normal Linux
* **Module (and version) (if relevant)**: cluster

Current Project (and working example): https://github.com/hasezoey/SavjeeCoin
and here the non working example: https://github.com/hasezoey/SavjeeCoin/tree/nonworking

i have this code (snippet):
(having required colors)

https://github.com/hasezoey/SavjeeCoin/blob/27a70f5a53bb4cb6ed2cf0932856ff074ec54936/main.js#L60-L73

it worked normal 2 days ago, i didnt change anything in this code, and yet it starts with `spawnargs: [ 'I:\\Programme (x64)\\NodeJS\\node.exe', undefined ]` anyone knows why it starts with undefined?
```
ChildProcess {
  _events:
   { internalMessage: [ [Function], [Function: onInternalMessage] ],
     error: [Function],
     message: [Function],
     exit: { [Function: bound onceWrapper] listener: [Function] },
     disconnect: { [Function: bound onceWrapper] listener: [Function] } },
  _eventsCount: 5,
  _maxListeners: undefined,
  _closesNeeded: 2,
  _closesGot: 0,
  connected: true,
  signalCode: null,
  exitCode: null,
  killed: false,
  spawnfile: 'I:\\Programme (x64)\\NodeJS\\node.exe',
  _handle: Process { owner: [Circular], onexit: [Function], pid: 6492 },
  spawnargs: [ 'I:\\Programme (x64)\\NodeJS\\node.exe', undefined ], //here 
  pid: 6492,
  stdin: null,
  stdout: null,
  stderr: null,
  stdio: [ null, null, null, null ],
  channel:
   Pipe {
     buffering: false,
     pendingHandle: null,
     onread: [Function],
     sockets: { got: {}, send: {} } },
  _channel: [Getter/Setter],
  _handleQueue: null,
  _pendingMessage: null,
  send: [Function],
  _send: [Function],
  disconnect: [Function],
  _disconnect: [Function] }
```

**Comment by ORESoftware** [comment]
not sure, but you can do

`args.filter(Boolean) `

if you want to force remove the undefined for now

note that the above is simpler version of

`args.filter(v => v) `

which will filter out falsy values

**Comment by hasezoey** [comment]
at wich line?

**Comment by hasezoey** [comment]
Addtion: i commentetd ("//") https://github.com/hasezoey/SavjeeCoin/blob/27a70f5a53bb4cb6ed2cf0932856ff074ec54936/main.js#L17-L26
and a `return` (because otherwise it would crash) to https://github.com/hasezoey/SavjeeCoin/blob/27a70f5a53bb4cb6ed2cf0932856ff074ec54936/main.js#L86

and then it then it would do it what it should do... where is the difference???

**Comment by hasezoey** [comment]
...found the mistake, `process.argv.splice()` modifies the original ... and it is used in cluster to fork it, and i removed the path for it >w<

issue closed.
