### ISSUE TITLE
Unix domain socket instead of TCP with host/port

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1316]
This is for all Node.js versions 6+

Say I have currently have a TCP server with multiple clients:

```js
const server = net.createServer(s => {

});

server.listen(6000);
```

and I connect to it with clients:

```js
const s1  = net.createConnection({port:6000});
const s2  = net.createConnection({port:6000});
const s3  = net.createConnection({port:6000});
```

TCP can sometimes be a bit slow on a local machine. I hear that there might be a way to substitute a host/port combination with Unix Domain Sockets, but maintain the TCP server style interface. Is this possible and how?

The Node.js docs mention you can create a server that listens on a path:
https://nodejs.org/api/net.html#net_server_listen_path_backlog_callback

but it doesn't specify what kind of file that needs to be and how to create that file.

**Comment by ORESoftware** [comment]
I actually think this example is sufficient:
https://gist.github.com/Xaekai/e1f711cb0ad865deafc11185641c632a

**Comment by gireeshpunathil** [comment]
@ORESoftware - I guess you answered your own question here? please let me know if that is not the case. In summary, passing a path causes a `FIFO` or a `named pipe` to be created with that file persisting in the file system (UNIX) and used for IPC.

**Comment by ORESoftware** [comment]
yeah all good, thanks
