### ISSUE TITLE
Error: async hook stack has become corrupted in node js

### ISSUE THREAD

**Issue by jayudhandha** [nodejs/help#1317]
* **Node.js Version**: v9.4.0
* **OS**: Windows 7
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: mocha,sleep (system-sleep)

I am writing tests for my Node JS application with mocha

In my test i have mocked 1 function (Which is invoking the HTTP Url) and for some condition, i have added sleep of 1 second.

I am getting below exception due to that sleep function in mocha test. In real application it is working fine.

> Error: async hook stack has become corrupted (actual: 18, expected: 19) 1: v8::SnapshotCreator::default constructor closure 2:
> 
> node::CallbackScope::~CallbackScope 3:
> 
> node::CallbackScope::~CallbackScope 4: RAND_query_egd_bytes 5:
> 
> RAND_query_egd_bytes 6: uv_timer_get_repeat 7: uv_run 8:
> 
> 000007FEF8771261 9: 000007FEF87710B6 10:
> 
> v8::internal::wasm::SignatureMap::Find 11:
> 
> v8::internal::Builtins::CallableFor 12:
> 
> v8::internal::Builtins::CallableFor 13:
> 
> v8::internal::Builtins::CallableFor 14: 000002E6363043C1

Below is my code of **moched function**.

```
somefunction() //In Mock test
{
    let current_time = Math.round((new Date()).getTime() / 1000);
    if (last_execution_time == current_time) {
        admin_delete_user_count++;
        if (admin_delete_user_count >= 3) {
            callback({
                stack: "TooManyRequestsException: Rate exceeded",
                "code": "TooManyRequestsException",
                "statusCode": 400
            }, undefined);
            return;
        }
    } else {
        admin_delete_user_count = 0;
        last_execution_time = Math.round((new Date()).getTime() / 1000);
    }
    callback(undefined, "Test");
}
```

Below is the actual function in my node js application which causing the issue after i am sending exception from above code.

```
somefunction() // In Real applicatio
{
    if (err) {
        if (err.code == "TooManyRequestsException") {
            logger.log("INFO", "TooManyRequestsException, So wait a while for 1 second and retry");
            index = index - 1;
            sleep(1000); // THIS IS CAUSING THE ISSUE
        }
    } else {
        console.log("deletedUsers:" + JSON.stringify(deletedUsers));
    }
}
```

Any Help?

**Comment by jayudhandha** [comment]
I found the issue listed above.

Basically there was timeout of 250ms which was causing the issue in async hooks lifecycle.

I changed from

```
timeout.timeout('waitTimer', 250,
   function() {
     expect(res.statusCode).to.equal(200);
     done();
   }
);
```
to

```
timeout.timeout('waitTimer', 1250,
   function() {
     expect(res.statusCode).to.equal(200);
     done();
   }
);
```
Thanks!

**Comment by skaunited** [comment]
I faced the same problem and I solved it by edit all the Timeout values in async.js file wish indexed in this path ====~> node_modules/async/dist
