### ISSUE TITLE
Question: should userland code introduce custom error code name?

### ISSUE THREAD

**Issue by bitinn** [nodejs/help#132]
moved from https://github.com/nodejs/nodejs.org/issues/629

----

I am thinking about standardizing error object for one of my module, but I can't seem to make up my mind on whether err.code should follow E-style naming like node.js core and linux, or introduce a custom err.type attribute with my custom name.

Does Node.js has a preference on this? On client-side error standardization beyond err.name and err.message isn't going anywhere as far as I can tell...

ref:
https://nodejs.org/api/errors.html#errors_system_errors
bitinn/node-fetch#99

**Comment by pekeler** [comment]
Across the node codebase, I see 74 places where E-style error names are assigned `grep -roE " = \'E[A-Z]+\'" .`

Grepping all strings that could be E-style error names with `grep -rhoE "\'E[A-Z]+\'" . | sort | uniq | grep -Eo "E[A-Z]+"` and then subtracting the ones from http://www.ioplex.com/~miallen/errcmp.html, I get a list of 53 error names that might be invented. https://gist.github.com/429c7b52fe739637902d19c108a1ab60
