### ISSUE TITLE
Recommended Software and Hardware Requirements

### ISSUE THREAD

**Issue by mikhailmendoza** [nodejs/help#1323]
What is the recommended software and hardware requirements to host node.js projects in a physical server

**Comment by nigelhanlon** [comment]
This isn't a straightforward question to answer as it really depends on a number of factors such as: 

- How the projects are deployed (Docker containers?)
- Expected web traffic (assuming you are hosting web apps)
- Resources you wish to allocate to each project (CPUs/Memory/Disk space)
- The tech stack you use for each project and supporting services such as databases

If you could give us more details about the types of project, how many etc, we may be able to give you a better answer.

**Comment by mikhailmendoza** [comment]
Most probably we will go with Docker containers.
The standalone app logic is pretty straight forward it just translate the request and  response from APIs.
For now that server will only host the standalone app
Actually Im not that familiar in deploying a node.js app in a physical server I mostly use cloud for deployment.

**Comment by gireeshpunathil** [comment]
- disc capacity: default will do, as you are just doing request - response stuff
 - physical memory: depends on your peek memory demand. Monitoring the peek load in Cloud and follow that size.
 - if autocaling was used in cloud, you need to account the combined resources in the number of nodes
 - on the other hand if you plan to use clusters in pysical deployment, you can follow the same (memory) configuration as in cloud.
 - cpus: default (4|8) will do, as Node does not use many threads
 - network: nothing specific to Node, depends on your response requirements

Hope this helps

**Comment by gireeshpunathil** [comment]
ping @mikhailmendoza - did this help you?

**Comment by gireeshpunathil** [comment]
closing as answered
