### ISSUE TITLE
Proposal: require double slash path semantic

### ISSUE THREAD

**Issue by pibi** [nodejs/help#1324]
I cannot find any links about why node doesn't resolve this:
```
const module = require("//lib/my.private.module")
```
as 
```
const module =  require(__base + "/" + "lib/my.private.module");
```
where `__base` is the directory where the parent package.json lies. 

This feature prevents ugly hacks while having big nested mono-repos. 

Is there any previous discussion about that?

**Comment by bnoordhuis** [comment]
> Is there any previous discussion about that?

Plenty, search the nodejs/node bug tracker for the 'feature request' + 'module' labels.

The real short answer to your question is: the module system is frozen.

Longer answer: your proposal is problematic for several reasons, one being that `'//lib'` is a valid file path, another that node's module system is largely agnostic to the presence of a package.json - that's a package manager thing.

Your proposal assumes that the Node.js module loader knows the concept of "a project", "related files", etc., but it doesn't, it only knows about individual files.

**Comment by pibi** [comment]
@bnoordhuis sorry, I have searched for issues about the '//' proposal without any luck.

About my assumptions, package.json is actually required to specifying a main file: https://nodejs.org/dist/latest-v8.x/docs/api/modules.html#modules_folders_as_modules . With that in mind, I was just looking to a way to avoid these kind of requires: 
```
var configuration = require ("../../../../config/config.js") 
```
I know that `//` is a valid path, but even in browsers this has a special semantic. 
NODE_PATH could solve that by letting me do a  `require ("config/config.js")` but it could introduce a clash if there's a `node_modules/config/config.js` in one of the parents directory. 
So I actually I don't know of a good way to get rid of this annoying bug (which has a great impact when you are just moving a folder up or down in a big codebase).  
Any other idea?

**Comment by bnoordhuis** [comment]
> package.json is actually required to specifying a main file

That's why I said "largely" and not "completely." :-)

(And I'd say `"main"` is generally considered a mistake.  It's not needed because you can do the same thing with an index.js file.)

If you want a custom module loader, you can write one using `vm.runInThisContext()`.  The built-in module loader uses the same mechanism.

**Comment by gireeshpunathil** [comment]
ping @pibi - is this resolved?

**Comment by pibi** [comment]
@gireeshpunathil Not yet. I'm working on the custom module loader as suggested.

**Comment by gireeshpunathil** [comment]
@pibi - I guess this can be closed now?

**Comment by gireeshpunathil** [comment]
closing, please re-open if there is anything outstanding on this.
