### ISSUE TITLE
the local web server settings problem, the npm start command isnt responding what cam i do

### ISSUE THREAD

**Issue by junior2018c** [nodejs/help#1327]
C:\Users\ebene\Downloads\DVD3>npm start

> dataviz-d3js@1.0.0 start C:\Users\ebene\Downloads\DVD3
> gulp

'gulp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dataviz-d3js@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dataviz-d3js@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ebene\AppData\Roaming\npm-cache\_logs\2018-06-09T09_28_55_475Z-debug.log

**Comment by gireeshpunathil** [comment]
I guess you first need to `npm install gulp`

**Comment by gireeshpunathil** [comment]
ping @junior2018c

**Comment by gireeshpunathil** [comment]
inactive, closing
