### ISSUE TITLE
Is it possible to have single node_modules in a machine/server

### ISSUE THREAD

**Issue by krajasekhar** [nodejs/help#1329]
* **Node.js Version**: 8.11.1
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**: 

Hi,

I have a concern that whether I could have a single repository for all the node_modules in my machine/server.
Suppose, I am having a project and installed all the required modules with the required version. Logged this info in package.json. Now if I make a new project and write same package.json. After giving 'npm install', it gets all node_modules from registry or from local users folder. This copy is taking too much time. Even I tried manually copying the node_modules and no help in the time taken.
Why can't I expect multiple projects in a machine to use same node_modules folder as I have given the module & version required in package.json. If can't, atleast for development purpose.

We need dependencies for delivery, But It can be let to copy all the node_modules required to the project folder when we require to package it or make some docker image.

Thanks & Regards,
RajaSekhar K

**Comment by richardlau** [comment]
> Why can't I expect multiple projects in a machine to use same node_modules folder as I have given the module & version required in package.json. 

Please be aware that Node.js has no runtime notion of a module's version, which is entirely a package manager thing (the only `package.json` field Node.js actually uses is [`main`](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_folders_as_modules)). 

Your options would be [`NODE_PATH`](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_loading_from_the_global_folders) or [`npm link`](https://docs.npmjs.com/cli/link).

**Comment by addaleax** [comment]
You might also want to look at package managers that support this, like https://github.com/pnpm/pnpm ?

**Comment by gireeshpunathil** [comment]
closing as answered.
