### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by Canoob** [nodejs/help#133]
As per the README file, the recommended method of verifying the checksum is incorrect, and does not produce the expected results.

The following command returns an error:

$ grep node-vx.y.z.tar.gz SHASUMS256.txt | sha256sum -c -
grep: SHASUMS256.txt: No such file or directory
sha256sum: standard input: no properly formatted SHA256 checksum lines found

The downloaded file has a .xz extension, and not .gz.

Please post the precise method of verifying the checksum.

**Comment by TheAlphaNerd** [comment]
@Canoob there are both tar.gz and tar.xz downloads available for all platforms, you can see this here
--> https://nodejs.org/download/release/latest-v5.x/

If you think the copy should be updated to specify that the release could be gz or xz please feel free to send a PR to the README
