### ISSUE TITLE
Is it possible to embed Node.JS in a game framework?

### ISSUE THREAD

**Issue by VictorQueiroz** [nodejs/help#1330]
Let's imagine that I'm building a game and I want to handle a specific part of the game using Node.JS code. How would I invoke node.js and take all of it's advantages and also build bindings so this Node.JS code could access other bindings to other functionality of the game framework? Is it possible or I'm talking nonsense? If not, can somebody guide me to the right direction or if I'd be able to do such approach using directly V8 implementation.

Best regards

**Comment by gireeshpunathil** [comment]
@VictorQueiroz  - A trivial place to invoke node from a pre-existing process is to prepare argc and argv, and call [this method](https://github.com/nodejs/node/blob/f86a181d471099417828ffd787aa6b3e0356ac36/src/node.cc#L4267)

Further, there are couple of `Start` methods and an `Init` method that fall in line the sequence that are callable too. Depending on your context, level of isolation that is reqiured as well as level of customization that is required, you can choose which method to invoke. The thumb rule is that the more inner method you make use, the more complex work you need to perform, but more granular control you avail.

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if this does not help
