### ISSUE TITLE
Weird behavior with allocationg memory in node v10.4.0

### ISSUE THREAD

**Issue by user-9826342** [nodejs/help#1331]
* **Node.js Version**: v10.4.0
* **OS**: Windows 10

Hello,

I noticed weird behavior in my Node.js application: my system can allocate up to 32GB of memory, but my Node.js process is crashes when it reaches about ~1.5GB

Example 1:

```js
var a = [];
while(1){
  a.push(Buffer.allocUnsafe(1e9));
}
```

Performance graph 1:

![](https://user-images.githubusercontent.com/39801377/41234877-bf82ae5c-6d8d-11e8-8b98-4ab94c0d2445.png)

You can zoom image to see numbers better. Basically, it allocates about 30GB and then throws buffer allocation failed error, which is ok.

---

Example 2:

```js
var a = [];
while(1){
  a.push(new class{constructor(){
    this.a = 'a'.repeat(1e6);
  }});
}
```

Performance graph 2:

![](https://user-images.githubusercontent.com/39801377/41234978-ff3b3172-6d8d-11e8-8541-7df98f242ec3.png)

In this example, the program crashes when it reaches about 1.5GB and the error is fatal:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed
- JavaScript heap out of memory
```

---

I'm filing issue here because I'm not sure if this is an issue, or I'm doing something wrong, so if it issue, I can file it node repo, for now I would like to hear from you is this an issue in V8's gc?

Obviously, both references to class objects and strings and buffers are stored in heap, so if Node.js is capable to allocate 32GB for buffers, why it isn't capable to allocate more than 1.5GB for classes, objects and strings?

Thanks.

**Comment by bnoordhuis** [comment]
`--max_old_space_size=<size in mb>` is what you're looking for, it defaults to ~1500.

**Comment by user-9826342** [comment]
Thanks bnoordhuis! I must admit it is very useful command line option, I didn't know about it

But wait, why then I can allocate 32GB for buffers, if max old space is still 1500 megabytes??

**Comment by shellberg** [comment]
Buffers are backed by off heap storage, and thus in total just constrained by the address space of your process and other practical limits under OS control.

Strings are stored in the v8 heap, and thus affected by the 'old' heap size option that 'bnoordhuis' supplied.

**Comment by user-9826342** [comment]
thanks shellberg
