### ISSUE TITLE
How to safely call untrusted code that contains file operations?

### ISSUE THREAD

**Issue by johnsoncodehk** [nodejs/help#1332]
I am building a server where users can install any module on the server and then upload and run untrusted code.

I want users to perform file operations but avoid deleting or writing files on the server.

The virtual file system is close to my expectations, but I can't find any sandbox that contains this feature. File operations in the sandbox directly read and write server files.

I don't have any idea how to do this now. I hope someone can give me a direction.

Best regards

**Comment by bnoordhuis** [comment]
Some options: chroot, fs namespaces, seccomp2, containers.

**Comment by johnsoncodehk** [comment]
I did not expect anyone to give a clear answer. Thank you for pointing me in the direction. I will verify every option.

To add that, I hope the solution is cross-OS, but it is not required.

When I solve this problem, I will close this issue and record my approach, thank you.

**Comment by bnoordhuis** [comment]
They're Linux-only except for chroot, which is available on most Unices; chroot is probably the least secure of the bunch though.  FreeBSD has jails, a chroot on steroids.

**Comment by johnsoncodehk** [comment]
This problem has been solved.

This may be a bit stupid. When I tested your options, I accidentally discovered RunKit. This site comes preloaded with all the modules and can execute arbitrary code, so I moved the runtime part to RunKit to do the job. ( Executing code in my project is not the main part)

Your options are absolutely valid, and I learned a lot, thank you again :)
