### ISSUE TITLE
CVE feed?

### ISSUE THREAD

**Issue by beetle-ibm** [nodejs/help#1335]
I would like to automatically gather CVE's that effect Node.js and core modules.  I was thinking of scanning the blog here for any CVE's but I see some are mentioned just to confirm that the CVE does NOT effect node. https://nodejs.org/en/blog/vulnerability/

Is there an easily machine consumable list/rssfeed/etc of CVE's that DO effect Node.js and core modules?

**Comment by richardlau** [comment]
The [Security working group](https://github.com/nodejs/security-wg) maintain a list: https://github.com/nodejs/security-wg/tree/master/vuln

**Comment by beetle-ibm** [comment]
Perfect - thanks!
