### ISSUE TITLE
Who is maintaing this repo.?

### ISSUE THREAD

**Issue by atombug** [nodejs/help#1336]
I've created a pull request on this repo., it's more than a day now and no response :disappointed: !

So tell me who's maintaining this repo. so i can ping him / her.

**Comment by gireeshpunathil** [comment]
@atombug - thanks for the pull request, sorry to see you being upset. 

I have been active in this repo helping users for a while, so I call myself as one of the maintainers.

Couple of more reviews, couple of more approvals, and we should be good to land it - of course consider any suggestions that may come in between!

**Comment by gireeshpunathil** [comment]
link https://github.com/nodejs/help/pull/1334
