### ISSUE TITLE
getSpkacSomehow() is not defined

### ISSUE THREAD

**Issue by fengrongquan** [nodejs/help#1337]
get Spkac occur ReferenceError: getSpkacSomehow is not defined.
Who can help me ?
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by bnoordhuis** [comment]
I think the answer is 'no one' until you post more information... how about showing us your code?

**Comment by vsemozhetbyt** [comment]
It seems @fengrongquan is trying some examples in the `crypto` doc, like [in this section](https://nodejs.org/api/crypto.html#crypto_certificate_exportchallenge_spkac). If so, the `getSpkacSomehow()` is a fictional (dummy) function, it is not defined in the Node,js API, it symbolizes any other ways to get `spkac`.

**Comment by gireeshpunathil** [comment]
```
#grep -i "somehow()" doc/api/* | wc -l
      31
#
```
Looks like this is a pattern. While the intent and meaning is obvious, the fact that these phrases are used in example code snippets which are otherwise syntactically correct and complete may be causing confusion here. 

@vsemozhetbyt - Is it possible to / worth make them appear differently from the normal JS expression?

**Comment by vsemozhetbyt** [comment]
I have no good ideas to fix this. It seems we may have many other dummy functions and variable names with not so easily identifiable pattern. We may add a note in the doc intro, but I doubt this will be much of help(

**Comment by gireeshpunathil** [comment]
thanks. let us ask @Trott then!

**Comment by vsemozhetbyt** [comment]
FWIW, I think "...somehow()" is clumsy enough names to hint they are not valid API functions, so maybe they suffice in most cases.

**Comment by Trott** [comment]
I don't know a good way to reliably signify this. If this is the first time there's been confusion about it, then it may not be worth worrying about. Some ideas that I'm not opposed to but I'm not sure how effective they will be:

* Add a comment that says `dummy function` next to the line. Not everyone will know what a dummy function is. But it probably won't hurt?

* Use `dummy` in the name.

* Maybe change this?:

```js
const spkac = getSpkacSomehow();
```

...to something more like this?:

```js
const spkac = ... // Insert code here to retrieve the spkac data structure.
```

I'm not convinced that's more clear than the current approach in the docs to be honest.

Like I said, I don't oppose any of these suggestions, and we could ask the documentation team for more suggestions, but if this isn't a common thing that comes up, it may not be worth addressing.

**Comment by Trott** [comment]
This question seems answered so I'm going to go ahead and close it. It seems like conversation about possible doc changes can continue here even though it's closed, or we could open a new issue in the main nodejs/node repo.
