### ISSUE TITLE
[memory leak] Sockets / streams: end() / final() vs destroy() - which one cleans up the stream?

### ISSUE THREAD

**Issue by theogravity** [nodejs/help#1338]
I noticed that `destroy()` was added in node 8.

After reading through the docs for both, I'm not entirely clear which I should be calling, especially if I'm concerned about memory leaks.

`destroy()` seems to do some extra stuff, including triggering the `error` event if an error is defined.

It also seems that I should be using `destroy()` when I'm using duplex streams once I'm completely done with the stream in general (eg I'm done with both the read/write side, it's better than having to remember to call `end()`/`final()` individually.)

I'm asking with respect to generic streams, but also when using `http.ClientRequest` (do I need to call it in the res object after I get the end event from the server?).

**Comment by mcollina** [comment]
I would recommend using .destroy() for dealing with error conditions.

Overall, you should be using stream.pipeline or pump most of the time. destroy() is needed for these to work well.

**Comment by gireeshpunathil** [comment]
closing as answered.
