### ISSUE TITLE
console.log memory usage / consumption (with pictures + code!)

### ISSUE THREAD

**Issue by theogravity** [nodejs/help#1339]
Edit - Adding the central discussion for this:

https://github.com/nodejs/node/issues/6379

----

- Under Mac OS, is console.log async or sync? 
- Does the default stream (I'm guessing stdout) for console.log use an infinitely-sized buffer?
- What are ways to garbage collect console.log entries in the default stream?

Sample code:
https://github.com/theogravity/grpc-console-log-memory-issue

I'm using node 8.10, and am noticing that my console.log data stays resident in memory and do not get gc'd. 

![image](https://user-images.githubusercontent.com/855434/41494906-771d3056-70d0-11e8-8062-adf45687dabd.png)

If I remove console.log from my test code, I do not have any lingering memory issues in the allocation timeline view in the memory profiler.

![image](https://user-images.githubusercontent.com/855434/41494908-86f8a06e-70d0-11e8-949f-015c67e61cda.png)

I also read that redirecting output to a file might resolve this, but it did not work in my case, (eg doing `node index.js > file.txt`)

However, if I call `console.clear()`, the memory is reclaimed, but then my terminal output is empty.

This leads me to think that the terminal itself is a stream that node is connecting to, and console.log entries must stay in memory, or else the terminal would not be able to display the data.

(I was thinking that maybe the output from stdout got copied to some other stream that's not directly attached to the node process, but the above behavior says I'm wrong.)

If I use the following code to redirect the output to a file directly, I barely get any resident memory issues (the tiny blue blips eventually subside after some time - probably flushing data to the file?).

```
// https://stackoverflow.com/questions/8393636/node-log-in-a-file-instead-of-the-console
var fs = require('fs');
var util = require('util');
var log_file = fs.createWriteStream(__dirname + '/debug.log', {flags : 'w'});
var log_stdout = process.stdout;

console.log = function(d) { //
  log_file.write(util.format(d) + '\n');
  log_stdout.write(util.format(d) + '\n');
};
```

![image](https://user-images.githubusercontent.com/855434/41494898-5fb2d376-70d0-11e8-945b-1a6c688a0118.png)

**Comment by gireeshpunathil** [comment]
@theogravity - a lot of context can be found in https://github.com/nodejs/node/issues/6379 and the linked issues thereon.

> This leads me to think that the terminal itself is a stream that node is connecting to, and console.log entries must stay in memory, or else the terminal would not be able to display the data.

this is not true. the reason is the asynchronous behavior of `console.log` coupled with data logging sequences in the application that does not account to such behaviors. This can either be addressed, or well documented.

If your application is amendable, can you try using the `process.stdout.write(data, cb)` pattern where `n+1th` write is attempted only after `nth` write is completed, through the completion handler callback?

**Comment by theogravity** [comment]
Thanks for the response, especially the issue link (I'll have to spend time reading through it all). 

It'd be nice if there was some central documentation on perf/scaling concerns when using `console.log`. It was difficult to find resources that talked about memory usage with `console.log` that were not from years back (eg node v0.12 - v4).

Do you have an example somewhere on where the pattern is applied? Would I have to maintain a separate buffer (eg as an array of buffers), where I would use the completion callback to shift the stack?

**Comment by gireeshpunathil** [comment]
AFAIK there are only 2 patterns: bounded writes and unbounded writes. Bounded pattern means your writes are discrete and countable:

```js
console.log('hello')
console.log('wonderful')
console.log('world')
process.exit(0)
```

this can be transformed into chain of callbacks:

```js
process.stdout.write('hello\n', () => {
  process.stdout.write('wonderful\n', () => {
    process.stdout.write('world\n', () => {
      process.exit(0)
    })
  })
})
```

unbounded writes where we don't know how many times we will be writing, so the write count is variable.

```js
for (var i = 0; i < 1000000000; i++) {
    console.log(i);
}
process.exit(0)
```

this can be transformed into recursion with each self-referencing call happens on completion of the current write.

```js
var i = 0
function foo() {
  if (i++ >= 1000000000)
    process.exit(0)
  process.stdout.write(`${i.toString()}\n`, () => {
    foo()
  })
}
foo()
```

I have verified that this addresses the data truncation problem as well as the memory overcommit problem.

in terms of central documentation: yes, we are trying to get to the bottom of it (please see the last discussion in https://github.com/nodejs/node/issues/6379)  to see if this is something that can be addressed on the face. If not, will try to psh for documentation that cover the current behavior and brings in the memory and scaling implications.

**Comment by theogravity** [comment]
I don't want my program to necessarily exit, though - I'm running an HTTP service here.

**Comment by hashseed** [comment]
@ak239 maybe we only need to hold onto these objects if the debugger is active?

**Comment by ak239** [comment]
Unfortunately we need to support case when user opens DevTools with already running application so we can not hold objects only if debugger is active. Currently we bound number of messages and try to bound memory consumption based on estimated object size.

**Comment by hashseed** [comment]
Good point. Does `console.clear()` release these objects?

**Comment by ak239** [comment]
Yes, it should.

**Comment by gireeshpunathil** [comment]
@hashseed - can you please clarify which entity holds on to the console logs? v8? I see these `.log` calls are routed to libuv's normal platform abstractions for writing into devices, and don't see any special consideration for console. Or are you talking about gRPC holding onto the console data?

**Comment by theogravity** [comment]
I don't think this is gRPC specific - it could have been implemented under http too.

**Comment by bnoordhuis** [comment]
@theogravity I see you posted this over at https://www.reddit.com/r/node/comments/8s2y7b/til_consolelog_entries_will_not_get_garbage/ but your summary there is wrong.  You should update it because it's going to mislead others.

The state of things:

1. A connected inspector client will cause `console.log()` to buffer a _bounded_ number of messages (currently 1,000.)

2. Libuv can buffer messages when you print faster than the sink (tty, pipe, file, etc.) can consume them.  That's something you can fix by pacing your writes.

**Comment by theogravity** [comment]
@bnoordhuis Thanks for the clarification. I definitely want to update it, but the link you issued doesn't point me to a comment. I tried looking for the hash in the URL amongst the comments via just cursor inspection, but couldn't find it.

Can you quote the incorrect comment and I will gladly strike it out and update with the correct information?

For #2 - in a more specific context - do you mean that libuv could be buffering console.log entries? How would pacing the writes apply to console.log? (Eg, would you have to pretty much use process.stdout.write with the completion callback like mentioned above?)

**Comment by bnoordhuis** [comment]
@theogravity Your original post in that thread says this:

> TIL that the default stream for console.log in node.js does not get garbage collected.

Which is incorrect because they do get gc'd over time.  "May not get garbage collected right away" would be more factual.

> How would pacing the writes apply to console.log?

Slicing them with `process.nextTick()` or `setImmediate()` is usually enough.

**Comment by theogravity** [comment]
Thanks - updating again.

**Comment by theogravity** [comment]
@bnoordhuis 

(In the context of memory usage)

If you do not require terminal logging, is it better to output logging to a file (or directly) to an external logging service instead?

Docker containers prefer reading from stdout, as most of the log tooling revolves around that, but if you have a ton of stdout writes (eg just doing a lot of console.log like behavior) in your node app that contains large amounts of data, will that hold in memory for a significantly long time until it gets gc'd?

What is the size of the libuv buffer?

**Comment by bnoordhuis** [comment]
> If you do not require terminal logging, is it better to output logging to a file (or directly) to an external logging service instead?

That's a design decision in your application.  I'm not the right person to ask because the answer depends on your specific circumstances.

But for context, people usually hit this when piping stdout to another program or across the network.  Files and ttys are normally so fast you can't exhaust them but pipes and sockets (or ssh connections) are a different matter.

> What is the size of the libuv buffer?

Libuv doesn't bound writes, that's not its job.  Node.js could but doesn't; that's moving from mechanism into policy territory.

**Comment by gireeshpunathil** [comment]
closing as answered, let me know if there is anything outstanding
