### ISSUE TITLE
Deleting native addon during process exit?

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [nodejs/help#1342]
* **Node.js Version**: v8.11.2
* **OS**: Win7 X64

It seems that unlike with requiring .js files, Node locks required .node files and doesn't release them until after exiting.
Is there anything I can do to work around this? (I need this to clean up after myself when the user quits my packaged exe. External workarounds like using `schtasks` or `timeout` either don't work or aren't acceptable.)

This is a minimal example I've been using for testing:

**main.js**
```js
const {spawnSync} = require('child_process');

const native = require('./processlist.node');
const nonnative = require('./something.js');

console.log(nonnative.foo);

process.on('exit', () => {
	let result = spawnSync(
		'cmd',
		//['/C', 'del', 'something.js'], // WORKS!
		['/C', 'del', 'processlist.node'],
		{windowsHide: true}
	).output.toString();

	console.log(result);
});
```

**something.js**
```js
module.exports = {
	foo: 'bar'
};
```

**OUTPUT**
```
bar
,D:\development\node playground\delete-native-addon\processlist.node
,Access is denied.
```

**Comment by trvsapjiac** [comment]
Windows locks `.node` files when Node.js requires them, since `.node` is binary formal (like `.dll` or `.exe`). You have two options:

1. Spawn a detached command prompt which spins in a loop and then deletes the `.node` file once the Node.js process exits or
2. Create another addon which will forcefully close `.node` handle from Node.js process, allowing the Node.js process to keep running

**Comment by s-h-a-d-o-w** [comment]
Hm that's a shame... thanks for the explanation though!

A quick follow-up question regarding 1.:
There's no way to spawn something involving cmd commands without a command prompt popping up, is there? (as cmd seems to be... invulernable towards `windowsHide`)

**Comment by s-h-a-d-o-w** [comment]
That's because it was sync and not running detached. Try this instead - which works but pops up that new prompt...

```js
	spawn(
		'cmd',
		['/C', 'timeout', '/t', '3', '&&', 'del', 'processlist.node'],
		{
			detached:true,
			windowsHide: true
		}
	)
```

Detached node.js process... I'll have to try that. My users won't have node installed but I guess I can maybe spawn my own packaged executable and supply it with some argument like `--cleanup` that triggers the cleanup and exits before anything else is done.

**Comment by trvsapjiac** [comment]
`windowHide` doesn't affect detached processes as I can see, but you can still hide it using a simple addon like this

```c++
#pragma comment(lib, "psapi.lib")

#include <node.h>
#include <windows.h>
#include <psapi.h>

using namespace v8;

void init(Local<Object> exports, Local<Object> module){
  STARTUPINFO st;
  PROCESS_INFORMATION pi;
  CreateProcess(NULL, "cmd /k echo cleanup", NULL, NULL, FALSE,
                CREATE_NO_WINDOW, NULL, NULL, &st, &pi);
}

NODE_MODULE(NODE_GYP_MODULE_NAME, init)
```

This code spawns a hidden detached command prompt (replace `/k` with `/c` in order to let it exit as soon as it finishes the job).

> Most of my users probably won't have node installed

Is you application closed-source?

**Comment by s-h-a-d-o-w** [comment]
> a simple addon like this

Hm... seems more elegant than the "spawning myself but with cleanup argument" option. Cool! But since evaluating these things will take a while, I'll ponder them once I'm done with another project. :+1: 

> Is you application closed-source?

No, I'm using zeit/pkg to package it.
In fact, feel free to check it out: https://github.com/s-h-a-d-o-w/spotify-ad-blocker (This cleanup issue is the last thing keeping me from releasing it)

**Comment by s-h-a-d-o-w** [comment]
Didn't take that long after all, as I quickly realized that the native addon method would create more implementation/maintenance overhead than I would want.

So I did decide on simply spawning myself with `--cleanup` on process.exit, doing this when receiving `--cleanup` in argv:
```js
    let retries = 0;
    const doCleanup = () => {
      try {
        fs.removeSync(APPDATA_PATH);
        process.exit();
      }
      catch(e) {
        retries++;
        if(retries > 20) { // ~10 seconds
          fs.writeFileSync(
            path.join(path.dirname(process.execPath), 'spotify-ad-blocker_error.log'),
            `Could not clean up ${APPDATA_PATH}, please delete it manually.`
          );
          process.exit(1);
        }
        else {
          setTimeout(doCleanup, 500);
        }
      }
    };
    doCleanup();
```

Thank you very much for you help!!
