### ISSUE TITLE
Vue & node.js Unhandled Rejection

### ISSUE THREAD

**Issue by RootPixl** [nodejs/help#1345]
* **Node.js Version**: 8.9.4
* **npm Version**: 5.6.0
* **OS**: Windows 10 (Insider Preview, build: 17677)
```
> Listening at http://localhost:8080
(node:8292) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 1
(node:8292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried to run my Vue project after a while I didn't use it, but when I used `npm run dev` this error became after this: 
![vue_error](https://user-images.githubusercontent.com/30440603/41614449-d23f6b18-73f8-11e8-898f-8f09abb4574b.PNG)

I need help.

**Comment by gireeshpunathil** [comment]
@benjamingr - do you have any insight on what could have been happening here?

**Comment by benjamingr** [comment]
@gireeshpunathil we have updated the errors since Node 8 and in Node 10 they're much better.

In the meantime they can run Node with `--trace-warnings` or update Node.

An unhandled rejection just means some place threw an uncaught exception in an async function most likely

**Comment by gireeshpunathil** [comment]
ping @RootPixl - were you able to follow the above suggestion and resolve your issue?

**Comment by gireeshpunathil** [comment]
closing as inactive
