### ISSUE TITLE
how to work around '../../../' problem in node js while referencing local modules?

### ISSUE THREAD

**Issue by preetham-salehundam** [nodejs/help#1346]
* **Node.js Version**: 8.x
* **OS**: MAC OS X and windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

How to work around with relative paths of modules in nodejs, whenever a directory restructures happen, it's painful to modify the paths.

```js
var local_module = require('../../../../local/module')
```
refer local modules with some prefix and node automatically loads like it does for node_modules
-->

**Comment by trvsapjiac** [comment]
You can implement your own `require` function like so:

```js
'use strict';

const PREFIX = '../../../../';

require = (require =>
  arg => require(PREFIX + arg)
)(require);

var local_module = require('local/module');
```

When you decide to restructure your directory, just update the `PREFIX` constant.

**Comment by preetham-salehundam** [comment]
@trvsapjiac Thanks for help. However i'm afraid the above pattern doesn't actually fit my requirement , as I have local modules relative at different levels
like
```js
const moduleA = require('../../../moduleA')
const moduleB = require('../../moduleB')
const moduleC = require("../moduleC")
```

**Comment by trvsapjiac** [comment]
So then, what do you mean by "restructuring directories"? Can you give an example? Suppose your directory structure is something like

```
dir1
└─dir2
    ├─dir3
    │   ├─dir4
    │   │   ├─dir5
    │   │   └─moduleC
    │   └─moduleB
    └─moduleA
```

How does it look like after "restructuring" so that you cannot address it using the prefix method? Or is your problem updating module paths in multiple files?

**Comment by eilgin** [comment]
you can alter the "scripts.start" value in your `package.json` to includ `NODE_PATH`:

```json
{
  "scripts": {
    "start": "NODE_PATH=. node index.js"
  }
}
```

Iet's say that you have the following dir structure:
```
index.js
lib/
    mod1.js
    helpers/
        utils.js
    components/
        comp1.js
        comp2.js
```

in `index.js` you can have:
```js
const mod1 = require("lib/mod1");
```
Imagine that `comp1.js` needs `comp2.js` and `utils.js`:
```js
// instead of having to use ".." like this:
//const comp2 = require("./comp2");
//const utils = require("../helpers/utils");

// you've got
const comp2 = require("lib/components/comp2");
const utils = require("lib/helpers/utils");
```

**Comment by preetham-salehundam** [comment]
@eilgin 
I have tried the following command  and i used require('gulp-tasks/csv-converter')

```set NODE_PATH=. && node --inspect-brk node_modules\gulp\bin\gulp.js cucumber-examples-insertor```

got the following error

``` Cannot find module 'gulp-tasks/csv-converter' ```

**Comment by eilgin** [comment]
You should'nt use `set` for that (see [details](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)) as it doesn't export the `NODE_PATH` env. variable. Besides you should call `node` like this preferably:

```bash
# i assume you're in a MacOS env. (unix-style folder separator are `/` compared to Windows `\`)
NODE_PATH=. node --inspect-brk node_modules/gulp/bin/gulp.js cucumber-examples-insertor
```

Moreover the "gulp-tasks" folder should be in the same path as the one where you're executing `npm start` (`NODE_PATH` is [another hack](https://gist.github.com/branneman/8048520#4-the-environment) to avoid `../../..`)

**Comment by ORESoftware** [comment]
You can add a custom node_modules folder:
https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders

so your project might look like

```
lib/
  foo/lib/
  foo/
     node_modules/
         mmm.js
     xar/z.js
node_modules/
     node_modules/
         mmm.js
     xar/z.js
node_modules/
```


in z.js if you do:

`require('mmm')`

it will load mmm.js from path

`lib/foo/node_modules/mmm.sj`

this is just how nodejs modules resolution works.

**Comment by preetham-salehundam** [comment]
@eilgin I'm on windows! :-) so u want me to execute this 
```NODE_PATH=. node --inspect-brk node_modules/gulp/bin/gulp.js cucumber-examples-insertor``` from a node task ?
In windows i have used **set** as a repalcement for **export** in mac.
The **gulp-tasks** folder is in the current folder where the npm task is being run.

**Comment by preetham-salehundam** [comment]
@ORESoftware i think this is going to mess up with my ide conf and git ignore as i always ignore node_modules

**Comment by ORESoftware** [comment]
@preetham-salehundam  yeah in this case you don't want to gitignore your custom node_modules folder.

**Comment by trvsapjiac** [comment]
> OS: MAC OS X

> I'm on windows!

??

**Comment by preetham-salehundam** [comment]
@trvsapjiac  My bad, updated the descripton, I have two systems, Currently i'm working on windows.

**Comment by preetham-salehundam** [comment]
@ORESoftware so in this case, the foo.js should be inside same folder (**test**) which has node_modules  inorder for ```require``` to pick ```z.js``` 

![](https://user-images.githubusercontent.com/11139560/41896457-81319486-78d9-11e8-9913-26cdde13f09c.png)

**Comment by preetham-salehundam** [comment]
@eilgin hey, see my folder structure below. I have used the following command in package.json
``` "debugGen":"set NODE_PATH=%CD%&& node --inspect-brk node_modules\\gulp\\bin\\gulp.js cucumber-feature-generator" ```
but I get the module not found error
![image](https://user-images.githubusercontent.com/13018526/41915864-5919b302-7974-11e8-9358-e2abd27e65a4.png)

**Comment by ORESoftware** [comment]
@preetham-salehundam  when you do `require('mmm')`, it will walk down the fs tree, looking for a node_modules folder each time.

**Comment by pibi** [comment]
What do you think of something like:
```
const module = require("//lib/my.private.module")
```
which should be resolved as:
```
const module = require(__base+"/"+"lib/my.private.module")
```
where `__base` is the path to the first directory where the parent package.json lies.
I'm discussing this proposal on #1324 . The special semantic enables a relative path at package.json level,  resolving the directory restructures issue.

With that semantic a classic configuration loader scenario such this:
```
var configuration = require ("../../../../config/config.js") 
```
could be:
```
var configuration = require ("//config/config.js") 
```

**Comment by gireeshpunathil** [comment]
@preetham-salehundam - hope this is resolved for you?

**Comment by gireeshpunathil** [comment]
closing as answered
