### ISSUE TITLE
Upgrade from 10.4.1 -> 10.5.0 breaks experimental-modules

### ISSUE THREAD

**Issue by goyney** [nodejs/help#1349]
* **Node.js Version**: 10.5.0
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

Using `--experimental-modules` on v10.4.1 worked. After an upgrade to v10.5.0, running the same script now simply outputs "(node:26960) ExperimentalWarning: The ESM module loader is experimental." and then dies with no other output.

It doesn't look like anything was changed in the changelog for the v10.5.0 release.

**Comment by addaleax** [comment]
I think this is a real bug, I also ran into it today in https://github.com/nodejs/node/issues/21417.

Apparently, https://github.com/nodejs/node/pull/21350 would fix it…

**Comment by gireeshpunathil** [comment]
@goyney - the linked PR has been merged, though it is not yet generally available in a release. Would you like try one of this week's nightly build to see if it solves your issue?

**Comment by gireeshpunathil** [comment]
I am planning to test this on master and resolve this, but don't know what to test. @addaleax / @goyney do you have an easy script or something?

**Comment by gireeshpunathil** [comment]
@goyney - this has been fixed in `v10.6.0` , specifically through the above mentioned PR. Please verify and let me know!

**Comment by gireeshpunathil** [comment]
fixed, closing
