### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by DonRichards** [nodejs/help#135]
```javascript
// run.js
import helloWorld from './modulepersist';
helloWorld();
console.log(helloWorld);

// modulepersist.js
export default 'hello world';
```
```Terminal
$ node --harmony run.js
```
```stack
import helloWorld from './modulepersist';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

> Node -v : v5.10.1
> OSX 10.11.4

Ran with/without 'strict mode' and --harmony<br/>
Switching to require/exports it works but why isn't the ES6 form working?

**Comment by Cuel** [comment]
Afaik 'import' isn't implemented yet. You can find the discussion here
https://github.com/nodejs/NG/issues/5

You can also use babelJS.

**Comment by lordKnighton** [comment]
👍  @Cuel

**Comment by DonRichards** [comment]
Ok, that's a shame.

**Comment by ajiteshdeb** [comment]
Use BABEL to do this. [](https://github.com/babel/example-node-server)

**Comment by thimmy687** [comment]
your link, links to 404

**Comment by dmyers** [comment]
@thimmy687 Copy and past the url. https://github.com/babel/example-node-server

**Comment by raghulintelizign** [comment]
Find the Below Link to solve this problem....
https://appyz.in
https://stackoverflow.com/questions/37634198/node-error-syntaxerror-unexpected-token-import
