### ISSUE TITLE
Current version or LTS？

### ISSUE THREAD

**Issue by libook** [nodejs/help#1350]
* **6.11.0**:
* **Linux**:
* **other**:

As we know that node6 is no longer supported. I am going to upgrade node.
Which version should I choose? v8.11.3 LTS or v10.5.0 Current?
I have herd that the "Current" version is not stable enough for production. Is that true?
If I won't have the difficulty of deployment, should I always use the latest "Current" version?

**Comment by gireeshpunathil** [comment]
v8: 8.11.3
v6: 6.14.3

This is also captured in the first page of Node.js website:

https://nodejs.org/en/
<img width="554" alt="screen shot 2018-06-21 at 12 03 42 pm" src="https://user-images.githubusercontent.com/6447530/41701758-3a0ff782-754b-11e8-99d1-dfa3f7b2b3e1.png">

**Comment by gireeshpunathil** [comment]
recommendation is to use `8.11.3` and move along with it. i.e., when LTS moves, upgrade. - most reliable approach.

**Comment by gireeshpunathil** [comment]
closing as answered
