### ISSUE TITLE
how to correct my wrong code to extract post data throung json?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#1352]
* **Node.js Version**: current
* **OS**: windows x64
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http, querystring

```js
const http = require('http'),
    { parse } = require('querystring');

http.createServer((request, response) => {

    const { method, url } = request;

    request.on('error', (err) => {
        console.error(err);
        response.statusCode = 400;
        response.end();
    });

    response.on('error', (err) => {
        console.error(err);
    });

    if (method === 'POST' && url === '/echo') {
        console.log(parse(request.pipe(response)));
    } else {
        response.end(`
        <!doctype html>
        <html>
        <body>
            <form action="/echo" method="post">
                <input type="text" name="name" />
                <input type="number" name="age" />
                <input type="file" name="photo" />
                <button>save</button>
            </form>
        </body>
        </html>
       `);
    }

}).listen(8080);
```
**ERROR**:
![image](https://user-images.githubusercontent.com/8686739/41762353-fcf83c0a-762c-11e8-9ab2-2059ac05d009.png)

![image](https://user-images.githubusercontent.com/8686739/41762067-171a9f7a-762c-11e8-8642-fbab39a95741.png)

**EXPECTED**:
// for example:
{
    fname: 'Jermaine',
    age: '29',
    photo: '1.png'
}

**Comment by trvsapjiac** [comment]
Replace

```js
console.log(parse(request.pipe(response)));
```

with

```js
var buff = Buffer.alloc(0);

request.on('data', chunk => {
  buff = Buffer.concat([buff, chunk]);
});

request.on('end', () => {
  var str = buff.toString('utf8');
  response.end(str);
  console.log(parse(str));
});
```

**Comment by anlexN** [comment]
@trvsapjiac , i know some solutions like you , but i don't like. To be me, i am curious about stream whether it can be "toString()" derectly. 
can you help me solve my problem? who can?

**Comment by trvsapjiac** [comment]
Sockets are asynchronous, you can't stringify the response synchronously. You may like or dislike it, but `console.log(parse(request.pipe(response)))` will never work. I'm afraid you'll not find any better solutions than what I've posted.

**Comment by gireeshpunathil** [comment]
closing as answered. I agree with @ghost , irrespective of personal inclination , printing the stream data may be partial, as that is the very nature of streams.
