### ISSUE TITLE
Process.chdir() on Centos 7 

### ISSUE THREAD

**Issue by riccardopirani** [nodejs/help#1355]
* **Node.js Version**: v8.11.3
* **OS** Centos 7
* **Scope runtime with cron**:

Hello then I state that something very strange happens to me, which had never happened to me. So I have a node.js application that runs perfectly on a centos server! Once the application has been loaded on the server, boot with node server.js and everything is working on perfection! As a reboot I set a cron to start the server node with this syntax: **@reboot node /var/www/html/app/main.js**, the problem is that when I restart the machine the cron starts correctly node.js but when I have to do the change of directory below I have this error:

**Node.js Code:**

`process.chdir('./Model');`

**Directory Tree:**

```
/var/www/html/app

/var/www/html/app/main.js

/var/www/html/app/Model
```

**Comment by addaleax** [comment]
Can you show the error message? Does it help when you change `process.chdir('./Model')` to `process.chdir(__dirname + '/Model')`?

**Comment by riccardopirani** [comment]
This is error message: ENOENT: no such file or directory, uv_chdir

**Comment by addaleax** [comment]
Okay, can you add `console.log(process.cwd())` before and/or try the other suggestion above?

**Comment by riccardopirani** [comment]
@addaleax I tried printing me this: /var/www/html/app.  I tried your suggestion from before but I always have the same error!

**Comment by addaleax** [comment]
What does `ls -l /var/www/html/app/Model` print on the command line? Maybe the directory doesn’t actually exist?

**Comment by riccardopirani** [comment]
this is print of directory: 
```

totale 204
-rw-r--r-- 1 root root  4902 25 giu 16.44 ArticoloModel.js
-rw-r--r-- 1 root root  6199 25 giu 16.44 CantiereModel.js
-rw-r--r-- 1 root root   909 25 giu 16.44 ClienteModel.js
-rw-r--r-- 1 root root 26313 25 giu 17.03 firmacliente.jpg
-rw-r--r-- 1 root root  3467 25 giu 16.44 KilometriModel.js
-rw-r--r-- 1 root root 52834 25 giu 16.44 logo.jpg
-rw-r--r-- 1 root root  7318 25 giu 16.44 RapportiniModel.js
-rw-r--r-- 1 root root 75795 25 giu 17.03 rapportino.pdf
-rw-r--r-- 1 root root  1427 25 giu 16.44 report.rb
-rw-r--r-- 1 root root  4626 25 giu 16.44 RisorseModel.js
-rw-r--r-- 1 root root   845 25 giu 16.44 UserModel.js
```

**Comment by riccardopirani** [comment]
@addaleax i have fix with change cron into: @reboot cd /var/www/html/quote/ && node server.js , Thanks for your help
