### ISSUE TITLE
asyncWrite is not a function.

### ISSUE THREAD

**Issue by fishlao** [nodejs/help#1356]
* **Node.js Version**:10.5.0
* **OS**:windows
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**:

when i use npm install or uninstall , it happend an error: asyncWrite is not a function.
and i use cnpm and i before update to 10.5.0 ,it is ok .
i dont know that is a version problem , or something error in my dependent packages.
"dependencies": {
    "alipay-sdk": "^3.0.1",
    "egg": "^2.2.1",
    "egg-cors": "^2.0.0",
    "egg-mongoose": "^2.2.1",
    "egg-scripts": "^2.5.0",
    "egg-validate": "^1.0.0",
    "jsonwebtoken": "^8.3.0",
    "md5": "^2.2.1",
    "moment": "^2.22.2",
    "qs": "^6.5.2",
    "superstruct": "^0.5.4",
    "tenpay": "^2.1.6"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.0.0",
    "egg-bin": "^4.3.5",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.14.0",
    "eslint": "^4.11.0",
    "eslint-config-egg": "^6.0.0",
    "webstorm-disable-index": "^1.2.0"
  },
  "engines": {
    "node": ">=8.9.0"
  },

**Comment by trygve-lie** [comment]
Also reported to npm: https://github.com/npm/npm/issues/21049

**Comment by lordKnighton** [comment]
@fishlao Did you get it sorted yet? Like @trygve-lie mention check that out, and if your still having issues let us know, other wise close this issue, thanks.

**Comment by fishlao** [comment]
@lordKnighton  you can close it.

**Comment by Andrewsopoku** [comment]
If you are using n to switch node version run n as admin

**Comment by copa017** [comment]
I also have "AsyncWrite is not a function" problem, no matter what I am going to install on my Windows 10.
I freshly installed Node 8.12.0 and 10.10.0 - no difference.

I tried: rebooting, force clean cache , run as admin, delete npm&node folders in appdata... to no avail

Thank you in advance!
