### ISSUE TITLE
(node :3536) UnhandledPromiseRejectionWarning ReferenceError: User not defined

### ISSUE THREAD

**Issue by sonaskyla12** [nodejs/help#1357]
basically i have two folder in the root...the structure in like this in the root

models
|----User.js
routes
|----api
|----users.js
1.The code under User.js is:-

const mongoose = require('mongoose');
const Schema = mongoose.Schema;
//create schema
const UserSchema = new Schema({
name: {
type: String,
required: true
},
email: {
type: String,
required: true
},
password: {
type: String,
required: true
},
avatar: {
type: String
},
date: {
type: Date,
default: Date.now
},

});
module.exports = User = mongoose.model('users', UserSchema);
2.The code under users.js
const express = require('express');
const router = express.Router();
const gravatar = require('gravatar');
const bcrypt = require('bcryptjs');
//load user model
const User = require('../../models/User');
router.get('/test', (req, res) => res.json({msg: 'user works'}));
//route Get api/user/register
router.post('/register',(req,res) =>{
User.findOne({email : req.body.email})
.then(user =>{
if(user){
return res.status(400).json({email:'Email already exist'});
}else{
const avatar =gravatar.url(req.body.email,{
s:'200',
r:'pg',
d:'mm'
} );
const User = new User({
name:req.body.name,
email:req.body.email,
avatar,
password:req.body.password

  });
  bcrypt.genSalt(10,(err, salt)=>{
    bcrypt.hash(newUser.password,salt,(err,hash) =>{
      if(err) throw err;
      newUser.password = hash;
      newUser.save()
      .then(user => res.json(user))
      .catch(err => console.log(err));
    }

    )
  }
)
}
})
});

module.exports = router;
3.postman is giving the suitable output on htttp://localhost:5000/api/users/test but not giving the output for http://localhost:5000/api/users/register now it is showing the error:-

error that is coming after this are:-

error (node :7408) UnhandledPromiseRejectionWarning ReferenceError: User not defined

at User.findone.then.user(C:\Users\shubhendu\desktop\mernstack\routes\api\users.js:20:20)

(node:7408) UnhandledPromiseRejectionWarning : Unhandled promise rejection . this error orginated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch . (rejection id:1)

(node :7408) [ DepricationWarning : Unhandled promise rejections are deprecated .In future , promise rejectionsthat are not handled will terminate the nodejs process with thenon zero exit code

could you help me how to resolve it..

**Comment by ORESoftware** [comment]
hard to read the code - can you format it with 3 backticks before and after? like this:

>  ```js
>  code
>  ```

**Comment by sonaskyla12** [comment]
basically i have two folder in the root...the structure in like this in the root

models
|----User.js
routes
|----api
|----users.js
1.The code under User.js is:-
'''js
    const mongoose = require('mongoose');
    const Schema = mongoose.Schema;
    const UserSchema = new Schema({
    name: {
    type: String,
    required: true
   },
   email: {
   type: String,
   required: true
  },
   password: {
   type: String,
   required: true
   },
  avatar: {
  type: String
  },
  date: {
  type: Date,
  default: Date.now
  },
   });
  module.exports = User = mongoose.model('users', UserSchema);
  '''
2.The code under users.js
'''js
   const express = require('express');
   const router = express.Router();
   const gravatar = require('gravatar');
   const bcrypt = require('bcryptjs');
   const User = require('../../models/User');
   router.get('/test', (req, res) => res.json({msg: 'user works'}));
   router.post('/register',(req,res) =>{
   User.findOne({email : req.body.email})
  .then(user =>{
   if(user){
  return res.status(400).json({email:'Email already exist'});
  }else{
  const avatar =gravatar.url(req.body.email,{
   s:'200',
   r:'pg',
   d:'mm'
   } );
   const User = new User({
   name:req.body.name,
   email:req.body.email,
   avatar,
  password:req.body.password

   });
   bcrypt.genSalt(10,(err, salt)=>{
   bcrypt.hash(newUser.password,salt,(err,hash) =>{
   if(err) throw err;
    newUser.password = hash;
    newUser.save()
    .then(user => res.json(user))
    .catch(err => console.log(err));
    }
    )
    }
    )
    }
    })
    });

   module.exports = router;
'''
3.postman is giving the suitable output on htttp://localhost:5000/api/users/test but not giving the output for http://localhost:5000/api/users/register now it is showing the error:-

error that is coming after this are:-

        error (node :3435) UnhandledPromiseRejectionWarning ReferenceError: User not defined

        at User.findone.then.user(C:\Users\shubhendu\desktop\mernstack\routes\api\users.js:20:20)

         (node:7408) UnhandledPromiseRejectionWarning : Unhandled promise rejection . this error 
          orginated either by throwing inside of an async function without a catch block or by rejecting a 
           promise which was not handled with .catch . (rejection id:1)

          (node :3536) [ DepricationWarning : Unhandled promise rejections are deprecated .In future , 
          promise rejectionsthat are not handled will terminate the nodejs process with thenon zero exit 
         code

could you help me how to resolve it..

**Comment by sonaskyla12** [comment]
the thing wat i m doing in postman are as follow:--

first i choose 'post' as the method

secondly typed  http://localhost:5000/api/users/register

thirdly i have x -www-form-urlencoded

fourthly typed the key and value for all the blank

fifthly have clicked on send button

**Comment by sonaskyla12** [comment]
could you help me please

**Comment by ORESoftware** [comment]
instead of this:

```js
const User = new User({
name:req.body.name,
email:req.body.email,
avatar,
password:req.body.password
});
```

do this:


```js
const u = new User({
name:req.body.name,
email:req.body.email,
avatar,
password:req.body.password
});
```

o/w you over-write the User variable

**Comment by sonaskyla12** [comment]
now there is error newUser is not defined

**Comment by sonaskyla12** [comment]
const newUser = new User({
name:req.body.name,
email:req.body.email,
avatar,
password:req.body.password
});
actually i have misprinted the const name User it was actually newUser already in the code

**Comment by sonaskyla12** [comment]
ya that was only the mistake....thank you so much...

**Comment by sonaskyla12** [comment]
my code and server both is running now thank you so much

**Comment by ORESoftware** [comment]
np

**Comment by gireeshpunathil** [comment]
closing as answered

**Comment by danishrajkotiya** [comment]
I'm facing the same issue as above.
How do I solve this?
Could you please help me out?

**Comment by danyal97** [comment]
> basically i have two folder in the root...the structure in like this in the root
> 
> models
> |----User.js
> routes
> |----api
> |----users.js
> 1.The code under User.js is:-
> '''js
> const mongoose = require('mongoose');
> const Schema = mongoose.Schema;
> const UserSchema = new Schema({
> name: {
> type: String,
> required: true
> },
> email: {
> type: String,
> required: true
> },
> password: {
> type: String,
> required: true
> },
> avatar: {
> type: String
> },
> date: {
> type: Date,
> default: Date.now
> },
> });
> module.exports = User = mongoose.model('users', UserSchema);
> '''
> 2.The code under users.js
> '''js
> const express = require('express');
> const router = express.Router();
> const gravatar = require('gravatar');
> const bcrypt = require('bcryptjs');
> const User = require('../../models/User');
> router.get('/test', (req, res) => res.json({msg: 'user works'}));
> router.post('/register',(req,res) =>{
> User.findOne({email : req.body.email})
> .then(user =>{
> if(user){
> return res.status(400).json({email:'Email already exist'});
> }else{
> const avatar =gravatar.url(req.body.email,{
> s:'200',
> r:'pg',
> d:'mm'
> } );
> const User = new User({
> name:req.body.name,
> email:req.body.email,
> avatar,
> password:req.body.password
> 
> });
> bcrypt.genSalt(10,(err, salt)=>{
> bcrypt.hash(newUser.password,salt,(err,hash) =>{
> if(err) throw err;
> newUser.password = hash;
> newUser.save()
> .then(user => res.json(user))
> .catch(err => console.log(err));
> }
> )
> }
> )
> }
> })
> });
> 
> module.exports = router;
> '''
> 3.postman is giving the suitable output on htttp://localhost:5000/api/users/test but not giving the output for http://localhost:5000/api/users/register now it is showing the error:-
> 
> error that is coming after this are:-
> 
> ```
>     error (node :3435) UnhandledPromiseRejectionWarning ReferenceError: User not defined
> 
>     at User.findone.then.user(C:\Users\shubhendu\desktop\mernstack\routes\api\users.js:20:20)
> 
>      (node:7408) UnhandledPromiseRejectionWarning : Unhandled promise rejection . this error 
>       orginated either by throwing inside of an async function without a catch block or by rejecting a 
>        promise which was not handled with .catch . (rejection id:1)
> 
>       (node :3536) [ DepricationWarning : Unhandled promise rejections are deprecated .In future , 
>       promise rejectionsthat are not handled will terminate the nodejs process with thenon zero exit 
>      code
> ```
> 
> could you help me how to resolve it..

It might because of undefined reference in the begining

**Comment by Qodestackr** [comment]
:-1:
