### ISSUE TITLE
question: how-to use npm (binary release)

### ISSUE THREAD

**Issue by nskalis** [nodejs/help#1359]
* **Node.js Version**: 10.5.0
* **OS**: CentOS Linux 7
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: npm

I downloaded today the latest binary release

```
ls -salt bin/
total 36624
    0 drwxrwxr-x. 2 app app       40 Jun 20 19:55 .
    0 drwxrwxr-x. 6 app app      108 Jun 20 19:55 ..
    0 lrwxrwxrwx. 1 app app       38 Jun 20 19:55 npm -> ../lib/node_modules/npm/bin/npm-cli.js
    0 lrwxrwxrwx. 1 app app       38 Jun 20 19:55 npx -> ../lib/node_modules/npm/bin/npx-cli.js
36624 -rwxrwxr-x. 1 app app 37501216 Jun 20 19:55 node
```

But there is an issue when I try to execute the following:
```
bin/npm install bower -g
/usr/bin/env: node: No such file or directory
```

Could you please advise on how to resolve this ?

**Comment by gireeshpunathil** [comment]
the location which you did `ls -slrt` on should be in the `PATH` environment variable. After which, `which node` command should show you the full path of node. Then `node` and `npm` commands will work. Ideally this is setup for the user who runs the installer, I assume that it was influenced by your answer to the installer's question command.

**Comment by nskalis** [comment]
Thanks!
But if I place the executable over here:

```
$ pwd
/usr/local/bin/node/latest/bin
$ ls -salt
total 36624
    0 drwxrwxr-x. 2 app app       40 Jun 20 19:55 .
    0 drwxrwxr-x. 6 app app      108 Jun 20 19:55 ..
    0 lrwxrwxrwx. 1 app app       38 Jun 20 19:55 npm -> ../lib/node_modules/npm/bin/npm-cli.js
    0 lrwxrwxrwx. 1 app app       38 Jun 20 19:55 npx -> ../lib/node_modules/npm/bin/npx-cli.js
36624 -rwxrwxr-x. 1 app app 37501216 Jun 20 19:55 node
```

The `PATH` should set automatically, no ?
```
PATH="$PATH:/usr/local/bin/node/latest/bin"
```
fixes the issue. In case of nodejs what is the best way to set it permanently ?

**Comment by gireeshpunathil** [comment]
what installer did you use? and how? if you elaborate your steps I can tell you.

**Comment by nskalis** [comment]
no installer. I just un-packed the tarsal from the nodejs page.

**Comment by gireeshpunathil** [comment]
sorry for the delay. In case of using the tarball, the way you setup the PATH variable is the best (and only) way of doing this. If you want to persist the PATH variable, I guess `~/.bash_login` or `~/.bash_profile` (assuming your work evironment is bash shell) is where you can place it.

**Comment by gireeshpunathil** [comment]
closing as answered
