### ISSUE TITLE
Linux Ubuntu installation

### ISSUE THREAD

**Issue by ramon175** [nodejs/help#136]
Hello, I am new to Linux environments, and I am trying to install nodejs for study, but I don't know how to do it, I have searched online for a tutorial but didn't find anything.

**Comment by TheAlphaNerd** [comment]
hey @ramon175 you can find the binaries at --> https://nodejs.org/en/download/

Installing via a package manager is going to be specific to your flavor of *nix

There are instructions on our website --> https://nodejs.org/en/download/package-manager/

**Comment by TheAlphaNerd** [comment]
Please feel free to keep questions coming as you are trying to get it running

**Comment by ramon175** [comment]
Thanks for the feedback, I managed to install node by downloading the binaries from the site, I did the configure/make/makeinstall steps and it is now running fine.

**Comment by TheAlphaNerd** [comment]
👍🏽
