### ISSUE TITLE
socket is close

### ISSUE THREAD

**Issue by JSlife23** [nodejs/help#1361]
* **Node.js Version**:V8.10.0
* **OS**:win32
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:net.js

![1](https://user-images.githubusercontent.com/7855952/42034431-97ed4cb6-7b12-11e8-823a-fe1a16e327a7.png)

**Comment by ahmtcn123** [comment]
You have to change your listening port. Looks like it used by another app

**Comment by gireeshpunathil** [comment]
ping @JSlife23

**Comment by ahmtcn123** [comment]
Close this issue seems not responding @JSlife23
