### ISSUE TITLE
Class error?

### ISSUE THREAD

**Issue by littlebroto1** [nodejs/help#1362]
* **Node.js Version**: v8.11.2
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I am having a problem where node.js is reading some of the classes I import as blank objects.

I am wondering if someone could tell me the problem and a possible fix. I cannot see anything wrong with it so it might be a bug and I am also looking for your opinion on if it is a bug or not if you can't find the problem. **Board.js** is the only file that is having a problem currently but I will provide the other ones if needed.

**Board.js**
```js

var request = require("sync-request");
var Card = require("./Card.js");
var List = require("./List");
var Member = require("./Member");

console.log(Card);

class Board {
    /**
     * 
     * @param {string} id
     * @param {string} key
     * @param {string} token
     */
    constructor(id, key, token) {

        var res = request("GET", `https://api.trello.com/1/boards/${id}`, { qs: { key: key, token: token } })

        var body = JSON.parse(res.getBody());
        this.name = body.name;
        this.id = body.id;
        this.closed = body.closed;
        this.pinned = body.pinned;
        this.url = body.url;
        this.shortUrl = body.shortUrl;

        Object.defineProperty(this, "lists", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/boards/${id}/lists`, { qs: { key: key, token: token } })
                var lists = JSON.parse(res.getBody());
                var listsList = [];
                for (var i = 0; i < lists.length; i++) {
                    var list = new List(lists[i].id, key, token);
                    listsList.push(list);
                }
                return listsList;
            }
        });

        Object.defineProperty(this, "cards", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/boards/${id}/cards`, { qs: { key: key, token: token } })
                var cards = JSON.parse(res.getBody());
                var cardslist = [];
                for (var i = 0; i < cards.length; i++) {
                    cardslist.push(new Card(cards[i].id, key, token));
                }
                return cardslist;
            }
        })

        Object.defineProperty(this, "members", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/boards/${id}/members`, { qs: { key: key, token: token } })
                var members = JSON.parse(res.getBody());
                var membersList = [];
                for (var i = 0; i < members.length; i++) {
                    membersList.push(new Member(members[i].id, key, token));
                }
                return membersList;
            }
        })

    }
}

module.exports = Board;
```

**Comment by trvsapjiac** [comment]
> I cannot see anything wrong with it so it might be a bug

Thank you for reporting in nodejs/help repository first. It is very unlikely that there is a bug with Node.js.

I think it would be useful if you provide other scripts too (`"./Card.js"`, `"./List"` and `"./Member"`). Also, what does `console.log(Card)` output from the script you posted?

**Comment by littlebroto1** [comment]
It outputs `{}`.

**Card.js**
`js
var request = require("sync-request");
var List = require("./List");
var Board = require("./Board");

class Card {
    /**
     * 
     * @param {string} id
     * @param {string} key
     * @param {string} token
     */
    constructor(id, key, token) {

        var res = request("GET", `https://api.trello.com/1/cards/${id}`, { qs: { key: key, token: token } })

        var body = JSON.parse(res.getBody());
        this.name = body.name;
        this.id = body.id;
        this.desc = body.desc;
        this.url = body.url;
        this.shortUrl = body.shortUrl;
        this.due = body.due;
        this.closed = body.closed;

        Object.defineProperty(this, "list", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/cards/${id}`, { qs: { key: key, token: token } })
                var body = JSON.parse(res.getBody());
                return new List(body.idList, key, token);
            }
        })

        Object.defineProperty(this, "board", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/cards/${id}`, { qs: { key: key, token: token } })
                var body = JSON.parse(res.getBody());
                return new Board(body.idBoard, key, token);
            }
        })

    }
}

module.exports = Card;
`
**List.js**
`js
var request = require("sync-request");
var Card = require("./Card");
var Board = require("./Board");

class List {
    /**
     * 
     * @param {string} id
     * @param {string} key
     * @param {string} token
     */
    constructor(id, key, token) {

        var res = request("GET", `https://api.trello.com/1/lists/${id}`, { qs: { key: key, token: token } })

        var body = JSON.parse(res.getBody());
        this.name = body.name;
        this.id = body.id;
        this.closed = body.closed;

        Object.defineProperty(this, "board", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/lists/${id}`, { qs: { key: key, token: token } })
                var body = JSON.parse(res.getBody());
                return new Board(body.idBoard, key, token);
            }
        })

        Object.defineProperty(this, "cards", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/lists/${id}/cards`, { qs: { key: key, token: token } })
                var cards = JSON.parse(res.getBody());
                var cardslist = [];
                for (var i = 0; i < cards.length; i++) {
                    cardslist.push(new Card(cards[i].id, key, token));
                }
                return cardslist;
            }
        })

        this.makeCard = function (title, desc, opt = { position: "bottom" }) {
            if (!opt.dueDate) {
                opt.dueDate = {};
            }
            var options = {
                name: title || "food",
                desc: desc || "apple",
                pos: opt.position || "bottom",
                due: opt.dueDate.date || undefined,
                dueComplete: opt.dueDate.completed || undefined
            }
            var req = request("POST", `https://api.trello.com/1/cards`, { qs: Object.assign({ key: key, token: token, idList: this.id }, options) })
        }
    }

}

module.exports = List;
`
**Member.js**
`js
var request = require("sync-request");
var Card = require("./Card");
var Board = require("./Board");

class Member {
    /**
     * 
     * @param {string} id
     * @param {string} key
     * @param {string} token
     */
    constructor(id, key, token) {

        var res = request("GET", `https://api.trello.com/1/members/${id}`, { qs: { key: key, token: token } })

        var body = JSON.parse(res.getBody());
        this.username = body.username;
        this.fullName = body.fullName;
        this.bio = body.bio;
        this.id = body.id;
        this.avatar = body.avatarUrl;
        this.url = body.url;

        Object.defineProperty(this, "boards", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/members/${id}`, { qs: { key: key, token: token } })
                var body = JSON.parse(res.getBody());

                var boards = body.idBoards
                var boardsList = [];
                for (var i = 0; i < boards.length; i++) {
                    boardsList.push(new Board(boards[i], key, token));
                }
                return boardsList;
            }
        });

        Object.defineProperty(this, "cards", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/members/${id}/cards`, { qs: { key: key, token: token } })
                var cards = JSON.parse(res.getBody());
                var cardslist = [];
                for (var i = 0; i < cards.length; i++) {
                    cardslist.push(new Card(cards[i].id, key, token));
                }
                return cardslist;
            }
        })
        
    }

}

module.exports = Member;
`

**Comment by trvsapjiac** [comment]
You have cyclic dependencies. From `Board.js` you're requiring `Card.js` and from `Card.js` you're requiring `Board.js`. Therefore, the empty object you're seeing is actually `module.exports` of the `Card.js` script.

**Comment by littlebroto1** [comment]
Okay. Why does it work with the `Card.js` and the `List.js` and how could I fix this?

**Comment by trvsapjiac** [comment]
> Why does it work with the Card.js and the List.js

It depends on the order of requiring modules.

> how could I fix this

There are several ways. For example, you can use [Lazy loading](https://www.google.co.uk/search?q=Node.js+lazy+loading) technique. In your particular example, the easiest way would be to require modules after you exporting class (move `require(...)` lines after `module.exports = ...`). There are also other techniques (like returning an array and push exported classes asycnhronously, etc).

Note that this is not a Node.js constraint, but a logical constraint. You cannot use something before you define it. If it was possible, it would allow you to extend two classes from each other.

As said, the easiest way to solve this is to move `require` to the end of the script. For example, your `Board.js` should look like

```js
class Board {
    /**
     * 
     * @param {string} id
     * @param {string} key
     * @param {string} token
     */
    constructor(id, key, token) {

        var res = request("GET", `https://api.trello.com/1/boards/${id}`, { qs: { key: key, token: token } })

        var body = JSON.parse(res.getBody());
        this.name = body.name;
        this.id = body.id;
        this.closed = body.closed;
        this.pinned = body.pinned;
        this.url = body.url;
        this.shortUrl = body.shortUrl;

        Object.defineProperty(this, "lists", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/boards/${id}/lists`, { qs: { key: key, token: token } })
                var lists = JSON.parse(res.getBody());
                var listsList = [];
                for (var i = 0; i < lists.length; i++) {
                    var list = new List(lists[i].id, key, token);
                    listsList.push(list);
                }
                return listsList;
            }
        });

        Object.defineProperty(this, "cards", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/boards/${id}/cards`, { qs: { key: key, token: token } })
                var cards = JSON.parse(res.getBody());
                var cardslist = [];
                for (var i = 0; i < cards.length; i++) {
                    cardslist.push(new Card(cards[i].id, key, token));
                }
                return cardslist;
            }
        })

        Object.defineProperty(this, "members", {
            get: () => {
                var res = request("GET", `https://api.trello.com/1/boards/${id}/members`, { qs: { key: key, token: token } })
                var members = JSON.parse(res.getBody());
                var membersList = [];
                for (var i = 0; i < members.length; i++) {
                    membersList.push(new Member(members[i].id, key, token));
                }
                return membersList;
            }
        })

    }
}

module.exports = Board;

var request = require("sync-request");
var Card = require("./Card.js");
var List = require("./List");
var Member = require("./Member");
```

Do the same for your other scripts and it should work. Note that this technique doesn't allow you to extend one class from another.

**Comment by littlebroto1** [comment]
Okay, thank you I will try this.

**Comment by littlebroto1** [comment]
It worked! Thank you very much! @trvsapjiac
