### ISSUE TITLE
How to avoid canary build?

### ISSUE THREAD

**Issue by njohnson77** [nodejs/help#1363]
* **Node.js Version**: v10.5.0
* **OS**: Windows 10 x64
* **Scope**: install

I posted issue at node.js: [#21591](https://njohnson77.github.io/) and @‪vsemozhetbyt in comment said that there is some version called "canary". I googled it and found that it is something like following: 95% of users receive normal version when they download Node.js from official website, but 5% of users receive a version called "canary" which has some experimental features (hidden) and it reports usage info and possible bugs to Node.js servers.

Is it true? How can I be sure that I got normal version and not "canary" version when I download node.js? I feel very unsafe about it (except if I didn't understand the concept correctly).

Can someone tell me how can I be sure to always download regular non-canary version? Thanks.

**Comment by vsemozhetbyt** [comment]
Canary version is the same as nightly version except it contains the latest V8 version. You can only download it deliberately from this location:

https://nodejs.org/download/v8-canary/

**Comment by njohnson77** [comment]
good to know. thanks
