### ISSUE TITLE
--max-old-space-size always reaches the maximum memory size and crashes

### ISSUE THREAD

**Issue by joaodornas** [nodejs/help#1364]
* **Node.js Version**: 8
* **OS**: Windows 10 Pro
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**:

Dear Friend,

I am trying to install Matlab Production Server R2018a. It uses a Http Server using Node.js v8.
When I try to install, and the Matlab installation runs the command Node.exe, the installation crashes with the commom error of GC (Garbage Collection) telling that it reached the maximum amount of memory available.
I tried several times to use the option --max-old-space-size, with several options of memory size, running from 1GB of RAM to even 12GB of RAM and the Node application always reaches the maximum value and crashes.
I am using a Windows 10 Pro in a Virtual Machine with Hyper-V running in a Windows Server 2016.
Anybody knows what I can do and whether this is a bug or not?

Thank you for your help,

best regards,

Joao V Dornas

**Comment by darlandemarco** [comment]
Try to use a older version of node (if you can). My application I'm facing the same issue with node 8. 

(with node 5.7 with --max_old_space_size it works fine)

**Comment by gireeshpunathil** [comment]
@joaodornas - couple of questions:
 - do you have any rough idea about the memory demand of your deployment?
 - did you have it running successfully earlier? or this is first time your are trying node?

**Comment by gireeshpunathil** [comment]
ping @joaodornas

**Comment by hard-quale** [comment]
Hello @gireeshpunathil 

I only need maybe 2 GB RAM.
No, I never had it running before. It is my first time.

Hello @darlandemarco 

I did not have time to test your suggestion. I had to change my priorities last 4 weeks. But I will give it a try soon and give you all a feedback.

best regards,

Joao

**Comment by gireeshpunathil** [comment]
thanks for the response. 

there is no known issue for the latest Node versions in terms of memory consumption. But if you are planning / willing to follow @darlandemarco 's suggestions, please go ahead! if it works it would be a bug in new releases of Node that needs to be diagnosed and fixed.

On the other hand, if you are are pretty sure about the app's memory demand (~2G) but it consistently crashing with 12G settings, one thing that can be suspected is the hypervisor - that may be capping some memory to the guest. Easily verified by running the same app in a bare metal.

**Comment by gireeshpunathil** [comment]
closing as inactive, please re-open if necessary.
