### ISSUE TITLE
Spawning micro buffer with child_process (linux)

### ISSUE THREAD

**Issue by Aetheryx** [nodejs/help#1366]
* **Node.js Version**: 10.4.1
* **OS**: Arch Linux
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: child_process

I'm using a text editor known as `micro` (https://github.com/zyedidia/micro), it aims to be a successor to the well-known `nano`. I am trying to programmatically open a micro buffer with some text. Micro accepts text from stdin, so `echo "hello world" | micro` would open a micro instance with that text, like [so](https://ken.is-into.men/4ff080.png).  

The code is executed in an Electron environment, and so there is no terminal to re-use. When I run `echo "hello world" | micro`, the terminal I ran the command in is the terminal that micro opens in. So, I can't just do `child_process.exec('echo "hello world" | micro')` because there is no terminal to run it from in an Electron environment.  

The attempt that makes most sense to me is spawning a detached micro instance (which should be in a new terminal) and then writing the text to `ChildProcess.stdin`. This didn't work - I am unable to even spawn a detached micro instance. A simple `child_process.spawn('micro', { detached: true })` doesn't seem to do anything at all; no new terminal window.  

I apologize in advance if this issue doesn't suit this repository because it's too niche or more related to linux than nodejs. I will gladly close the issue if that's the case.

**Comment by gireeshpunathil** [comment]
let us probably start with:
`child_process.spawn('micro', { detached: true })` not showing up anything.

what does `strace -f` show? does it show the child as not started, or started but failed?

**Comment by Aetheryx** [comment]
I think it's the former, but I'm not entirely sure if my usage of `strace` is correct:  

![image](https://user-images.githubusercontent.com/25572140/43464006-40dbe2fc-94da-11e8-937b-c51b0d023770.png)  

It should also be noteworthy I (somewhat) fixed this issue already by using a middleman script:
```sh
echo "$@" | micro
```

I can then do this:
```js
child_process.spawn('urxvt', ['-e', '/home/aetheryx/micro-buffer-test/script.sh', ...text.split(' ')]);
```
(with urxvt being my terminal of choice).

I would still love to see if I could get this implemented "natively" though!

**Comment by gireeshpunathil** [comment]
ok, great to know you have some relief!

can you try (on your lambda prompt) this:

strace -f node foo.js

where foo.js contain your spawn code?

**Comment by Aetheryx** [comment]
It looks like the child was spawned and then failed, and I believe to have found the culprit:
```
[pid 26689] newfstatat(AT_FDCWD, "/home/aetheryx/.config/micro/settings.json", {st_mode=S_IFREG|0644, st_size=1091, ...}, 0) = 0
[pid 26690] <... pselect6 resumed> )    = 0 (Timeout)
[pid 26689] newfstatat(AT_FDCWD, "/home/aetheryx/.config/micro/bindings.json",  <unfinished ...>
[pid 26690] pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=160000}, NULL <unfinished ...>
[pid 26689] <... newfstatat resumed> 0xc4201d4c68, 0) = -1 ENOENT (No such file or directory)
[pid 26690] <... pselect6 resumed> )    = 0 (Timeout)
[pid 26690] pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=320000}, NULL <unfinished ...>
[pid 26689] openat(AT_FDCWD, "/dev/tty", O_RDONLY|O_CLOEXEC) = -1 ENXIO (No such device or address)

--> [pid 26689] write(1, "open /dev/tty: no such device or"..., 41 <unfinished ...>

[pid 26683] <... epoll_wait resumed> [{EPOLLIN, {u32=15, u64=15}}], 1024, -1) = 1
[pid 26689] <... write resumed> )       = 41
[pid 26683] read(15,  <unfinished ...>
[pid 26689] exit_group(1 <unfinished ...>

--> [pid 26683] <... read resumed> "open /dev/tty: no such device or"..., 65536) = 41

[pid 26694] <... futex resumed>)        = ?
[pid 26693] <... futex resumed>)        = ?
[pid 26692] <... futex resumed>)        = ?
[pid 26694] +++ exited with 1 +++
[pid 26693] +++ exited with 1 +++
[pid 26692] +++ exited with 1 +++
```  

Is it possible that spawning micro detached is fundamentally impossible? That makes sense to me because micro wouldn't be able to run without a terminal to run it in.

**Comment by gireeshpunathil** [comment]
wow! that was pretty good!

so the child did not have stdin!

but who closes it? when you say:

> micro shouldn't be able to run without a terminal to run it in

who takes that decision? the parent, or the child itself? while Windows has a concept of `win32 console` and `win32 non-console` types with the later started with std streams off, UNIX has no such thing as far as I know.  And in this case, the parent is node, so if someone has to close the std's it has to be node, which it never does.

so who closed `/dev/tty` ? is it the `micro` itself? are there strace data that shows micro closing fd corresponding to `/dev/tty`? how was the micro spawned? `execve`? are there parameters you can capture for the system call?

nevertheless, very good progress.

**Comment by gireeshpunathil** [comment]
ping @Aetheryx

**Comment by gireeshpunathil** [comment]
ping @Aetheryx one last time

**Comment by Aetheryx** [comment]
Sorry for not responding to the pings! Issue was fixed by using a merger script like I had mentioned above :)
