### ISSUE TITLE
Compile as position independent executable with ninja?

### ISSUE THREAD

**Issue by vvdveen** [nodejs/help#1368]
* **Node.js Version**: 8.10.0
* **OS**: Ubuntu 16.04
* **Scope (install, code, runtime, meta, other?)**: build from source

How do I build the node binary as position independent executable with ninja? Settings CFLAGS, CPPFLAGS, and CXXFLAGS does not seem to have any effect on the final binary and I cannot find a command line option for ./configure to set these.

**Comment by vvdveen** [comment]
I fixed it for now by modifying the configure script:
```
Index: configure
===================================================================
--- configure   (revision unknown)
--- configure   (working copy)
@@ -1419,7 +1419,8 @@
   'include_dirs': [],
   'libraries': [],
   'defines': [],
-  'cflags': [],
+  'cflags': [ '-fPIE', ],
+  'ldflags': [ '-fPIE', '-pie', ],
 }

 # Print a warning when the compiler is too old.
```

**Comment by gireeshpunathil** [comment]
I see no problems with exports. Can you double check?
```
#export CPPFLAGS=-Dbogus
#./configure
# make V=1
...
```
c++ '-D_DARWIN_USE_64_BIT_INODE=1' '-DU_COMMON_IMPLEMENTATION=1' '-DU_ATTRIBUTE_DEPRECATED=' '-D_CRT_SECURE_NO_DEPRECATE=' '-DU_STATIC_IMPLEMENTATION=1' '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu-small/source/common  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF /nodeout/Release/.deps//nodeout/Release/obj.target/icuucx/deps/icu-small/source/common/caniter.o.d.raw ***-Dbogus***  -c -o /nodeout/Release/obj.target/icuucx/deps/icu-small/source/common/caniter.o ../deps/icu-small/source/common/caniter.cpp
^C
#

**Comment by vvdveen** [comment]
I recall that this did indeed work, but not when I switched to ninja.

**Comment by vvdveen** [comment]
Hmm, yes, this seems to work. Not sure what I was doing then. Thanks!
