### ISSUE TITLE
No SHASUMS file in binary release

### ISSUE THREAD

**Issue by glenpike** [nodejs/help#137]
The [README](https://github.com/nodejs/node#verifying-binaries) provides a method for verifying binaries, but the current 64bit version for Linux: https://nodejs.org/dist/v4.4.2/node-v4.4.2-linux-x64.tar.xz  doesn't contain these files so there is no way of verifying.

**Comment by TheAlphaNerd** [comment]
You can download the file from [here](https://nodejs.org/dist/v4.4.2/SHASUMS256.txt) or [here](https://nodejs.org/dist/v4.4.2/SHASUMS256.txt.asc).  The second file is signed with a GPG key from the release team.

I'm going to update the copy in the readme to make this clearer
