### ISSUE TITLE
Determine if process / server is already listening on UDS path

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1371]
On Node.js version 10+

Say we have a server listening on a path (unix domain sockets):

```js
const server = net.createServer(socket => {

});

const p = path.resolve(process.env.HOME + '/unix.sock');
server.listen(p);
```

is there a way to determine if some other server is already listening on path p, before running the above code?

**Comment by gireeshpunathil** [comment]
I don't find an easy way.

At high level, you apply try catch block and progress on a best effort basis.
At low level, you use OS primitives such as `lsof | grep FIFO` and search for your pipe in it.

In either way, it is a hacky proposition!

**Comment by gireeshpunathil** [comment]
@ORESoftware - are you happy with what I proposed?

**Comment by ORESoftware** [comment]
the best solution I found was to simply try to connect first, if no connection can be made, then it's free, basically
