### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by krngd2** [nodejs/help#1377]
Trying to build production build of my application
Running

> ionic cordova run android --prod

throwing this error

> Running app-scripts build: --prod --platform android --target cordova
> [16:44:28] build prod started ...
> [16:44:28] clean started ...
> [16:44:28] clean finished in 13 ms
> [16:44:28] copy started ...
> [16:44:29] deeplinks started ...
> [16:44:29] deeplinks finished in 369 ms
> [16:44:29] ngc started ...
> [16:44:56] ngc finished in 27.30 s
> [16:44:56] preprocess started ...
> [16:44:56] preprocess finished in less than 1 ms
> [16:44:56] webpack started ...
> [16:44:57] copy finished in 28.58 s
> <--- Last few GCs --->
> [14264:00000280E7B82FB0] 186352 ms: Mark-sweep 1403.7 (1451.9) -> 1403.7 (1451.9) MB, 2137.0 / 0.0 ms last resort GC in old space requested
> <--- JS stacktrace --->
> ==== JS stack trace =========================================
> Security context: 000000C2FF3A5EE1 
> 1: setEmitFlags [F:\Projects\Ionic Projects\VBFashions\node_modules\typescript\lib\typescript.js:~49349] [pc=000001747BF3AE9F](this=00000307D6F647A1 ,node=00000151153050C1 ,emitFlags=16777216)
> 3: createEntityNameFromSymbolChain(aka createEntityNameFromSymbolChain) [F:\Projects\Ionic Projects\VBFashions\node_modules...
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
> 1: node_module_register
> 2: v8::internal::FatalProcessOutOfMemory
> 3: v8::internal::FatalProcessOutOfMemory
> 4: v8::internal::Factory::NewStruct
> 5: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
> 6: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
> 7: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
> 8: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
> 9: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
> 10: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
> 11: 000001747B4847A1
 

my package.json file

> {
> "name": "vbfashions",
> "version": "0.0.1",
> "author": "Ionic Framework",
> "homepage": "http://ionicframework.com/",
> "private": true,
> "scripts": {
> "clean": "ionic-app-scripts clean",
> "build": "ionic-app-scripts build ",
> "lint": "ionic-app-scripts lint",
> "ionic:build": "ionic-app-scripts build",
> "ionic:serve": "ionic-app-scripts serve"
> },
> "dependencies": {
> "@ angular/animations": "5.2.10",
> "@ angular/common": "5.2.10",
> "@ angular/compiler": "5.2.10",
> "@ angular/compiler-cli": "5.2.10",
> "@ angular/core": "5.2.10",
> "@ angular/forms": "5.2.10",
> "@ angular/http": "5.2.10",
> "@ angular/platform-browser": "5.2.10",
> "@ angular/platform-browser-dynamic": "5.2.10",
> "@ ionic-native/barcode-scanner": "^4.9.0",
> "@ ionic-native/base64": "^4.7.0",
> "@ ionic-native/camera": "^4.7.0",
> "@ ionic-native/core": "4.7.0",
> "@ ionic-native/file": "^4.7.0",
> "@ ionic-native/file-transfer": "^4.7.0",
> "@ ionic-native/google-plus": "^4.7.0",
> "@ ionic-native/image-picker": "^4.7.0",
> "@ ionic-native/image-resizer": "^4.7.0",
> "@ ionic-native/network": "^4.8.0",
> "@ ionic-native/splash-screen": "4.7.0",
> "@ ionic-native/status-bar": "4.7.0",
> "@ ionic/storage": "2.1.3",
> "angularfire2": "^5.0.0-rc.10",
> "com-badrit-base64": "^0.2.0",
> "com.razorpay.cordova": "^1.3.10",
> "cordova-android": "^6.3.0",
> "cordova-browser": "5.0.3",
> "cordova-plugin-camera": "^4.0.3",
> "cordova-plugin-compat": "^1.2.0",
> "cordova-plugin-device": "^2.0.2",
> "cordova-plugin-file": "^6.0.1",
> "cordova-plugin-file-transfer": "^1.7.1",
> "cordova-plugin-firebase": "^1.0.5",
> "cordova-plugin-googleplus": "^5.3.0",
> "cordova-plugin-image-picker": "^1.1.3",
> "cordova-plugin-ionic-keyboard": "^2.1.2",
> "cordova-plugin-ionic-webview": "^1.2.1",
> "cordova-plugin-network-information": "^2.0.1",
> "cordova-plugin-splashscreen": "^5.0.2",
> "cordova-plugin-statusbar": "^2.4.2",
> "cordova-plugin-telerik-imagepicker": "^2.1.10",
> "cordova-plugin-whitelist": "^1.3.3",
> "firebase": "^5.0.3",
> "firebase-admin": "^5.12.1",
> "firebase-functions": "^1.0.2",
> "info.protonet.imageresizer": "^0.1.1",
> "ionic-angular": "3.9.2",
> "ionic-img-viewer": "^2.9.0",
> "ionicons": "3.0.0",
> "phonegap-plugin-barcodescanner": "^8.0.0",
> "promise-polyfill": "^7.1.2",
> "rxjs": "^6.2.1",
> "rxjs-compat": "^6.1.0",
> "sw-toolbox": "3.6.0",
> "zone.js": "0.8.26"
> },
> "devDependencies": {
> "@ionic/app-scripts": "3.1.10",
> "typescript": "~2.6.2"
> },
> "description": "An Ionic project",
> "cordova": {
> "plugins": {
> "cordova-plugin-device": {},
> "cordova-plugin-splashscreen": {},
> "cordova-plugin-ionic-webview": {},
> "cordova-plugin-ionic-keyboard": {},
> "cordova-plugin-statusbar": {},
> "cordova-plugin-camera": {},
> "cordova-plugin-file": {},
> "cordova-plugin-file-transfer": {},
> "cordova-plugin-image-picker": {},
> "cordova-plugin-whitelist": {},
> "com-badrit-base64": {},
> "info.protonet.imageresizer": {},
> "cordova-plugin-googleplus": {
> "REVERSED_CLIENT_ID": "",
> "WEB_APPLICATION_CLIENT_ID": "*"
> },
> "cordova-plugin-compat": {},
> "com.razorpay.cordova": {},
> "cordova-plugin-network-information": {},
> "phonegap-plugin-barcodescanner": {
> "ANDROID_SUPPORT_V4_VERSION": "27.+"
> }
> },
> "platforms": [
> "android"
> ]
> }
> }

**Comment by vsemozhetbyt** [comment]
By default, Node.js sets memory limit near 1.5 GB. Try to increase it by this key (this example sets 4 GB):
```console
node --max_old_space_size=4096 script.js
```

**Comment by krngd2** [comment]
Tried it already, same result again, even used [increase-memory-limit](https://www.npmjs.com/package/increase-memory-limit), no change

**Comment by trvsapjiac** [comment]
> This actually ran for a long time thrown error again,

You probably have a memory leak in your code. But without looking at the code, it is impossible to tell. Please provide your scripts.

**Comment by krngd2** [comment]
Project is too big to paste here, Can we have a VS live code share session when you are free. Or give me any link to learn about memory leaks

**Comment by trvsapjiac** [comment]
> Project is too big to paste here,

You can create a new repository and paste the code there.

**Comment by trvsapjiac** [comment]
It is hard to tell just by looking at that script. There are some cases when a memory leak may occur

1. Pushing elements to an array, but not freeing or resetting the array
2. Attaching closures as event listener handler functions
3. Storing callbacks into an object which lives even if the callbacks are no longer needed
4. Storing symbols (with the same name) as properties of an object
5. Constantly creating new object properties (each with a different name) without deleteing previous ones
6. Adding properties to a Set, a Map, or a WeakMap
7. Storing non-resolved promises in an array

These cases are fine if you use them properly, but the fact that you're getting out-of-memory errors means that you are probably doing some of these cases wrongly. I couldn't see any of them in the script you've provided, so the problem may be in another script, or in the way you're calling methods of `FireDataService`

**Comment by gireeshpunathil** [comment]
@krngd2 - is this still outstanding?

**Comment by imranshad** [comment]
Try Shift+r  in Terminal (Terminal where code is running) and reload

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by Dotemin** [comment]
Hey guys I need a help. I tried to build the sprint boot app using jhipster. I did all configuration and installation but when I tried to run the backend side of my code the configuration gave me these errors everytime, I can't see the localhost:8080. Please is someone face this kind of error before. 


[INFO]
[INFO] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 134
[INFO] npm ERR! fitness@0.0.1-SNAPSHOT webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"`
[INFO] npm ERR! Exit status 134
[INFO] npm ERR!
[INFO] npm ERR! Failed at the fitness@0.0.1-SNAPSHOT webpack script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     C:\Users\AG68837\AppData\Roaming\npm-cache\_logs\2020-02-19T14_37_27_754Z-debug.log
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 134
[INFO] npm ERR! fitness@0.0.1-SNAPSHOT webpack:build:main: `npm run webpack -- --config
webpack/webpack.dev.js --env.stats=minimal`
[INFO] npm ERR! Exit status 134
[INFO] npm ERR!
[INFO] npm ERR! Failed at the fitness@0.0.1-SNAPSHOT webpack:build:main script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     C:\Users\AG68837\AppData\Roaming\npm-cache\_logs\2020-02-19T14_37_27_781Z-debug.log
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 134
[INFO] npm ERR! fitness@0.0.1-SNAPSHOT webpack:build: `npm run cleanup && npm run webpack:build:main`
[INFO] npm ERR! Exit status 134
[INFO] npm ERR!
[INFO] npm ERR! Failed at the fitness@0.0.1-SNAPSHOT webpack:build script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     C:\Users\AG68837\AppData\Roaming\npm-cache\_logs\2020-02-19T14_37_27_882Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:15 min
[INFO] Finished at: 2020-02-19T09:37:28-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:npm (webpack build dev) on project fitness: Failed to run task: 'npm run webpack:build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 134 (Exit value:
134) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to
enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by orcunozbay1** [comment]
this code(node) entering to command line.
>
>
>

**Comment by poorna5500** [comment]
## FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory##

 1: 00007FF6D913058F napi_wrap+109311
 2: 00007FF6D90D52B6 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NumberOfElementsOffset+33302
 3: 00007FF6D90D6086 node::OnFatalError+294
 4: 00007FF6D99A150E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6D998638D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6D983081C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF6D982BC31 v8::internal::Heap::AllocateExternalBackingStore+1569
 8: 00007FF6D9845DD6 v8::internal::Factory::AllocateRaw+166
 9: 00007FF6D98574DD v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray+29
10: 00007FF6D98575DF v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawFixedArray+31
11: 00007FF6D9845959 v8::internal::GCIdleTimeHandler::ShouldDoContextDisposalMarkCompact+905
12: 00007FF6D984743E v8::internal::Factory::CopyFixedArrayWithMap+14
13: 00007FF6D9550941 v8::internal::DeclarationScope::was_lazily_parsed+6689
14: 00007FF6D9553F12 v8::sampler::Sampler::IsActive+4818
15: 00007FF6D9A29EBD v8::internal::SetupIsolateDelegate::SetupHeap+463949
16: 00007FF6D9A79A9A v8::internal::SetupIsolateDelegate::SetupHeap+790570
17: 00007FF6D9A1ACB2 v8::internal::SetupIsolateDelegate::SetupHeap+401986
18: 00007FF6D99C28A2 v8::internal::SetupIsolateDelegate::SetupHeap+40498
19: 00007FF6D99C28A2 v8::internal::SetupIsolateDelegate::SetupHeap+40498
20: 00007FF6D99BC4D9 v8::internal::SetupIsolateDelegate::SetupHeap+14953
21: 0000030CD424647C


# When 
npm run

# How
command-line messages below
