### ISSUE TITLE
Write a HTTP response body to Excel File

### ISSUE THREAD

**Issue by kutlaykural** [nodejs/help#1380]
Hello everyone,
Is there any option to save a HTTP response body to an excel file.
Because code below works without error but excel file seems damaged.
```js
.then((response) => {
    const fs = require('fs');
     fs.writeFile("out.xlsx",response.body,(err) => {
       if (err) throw err;
       console.log('The file has been saved!');
      })
})
```

also i tried
```js
response.body.pipe(fs.createWriteStream("out.xlsx"))
```
Thanks,

**Comment by trvsapjiac** [comment]
As said in the comments on the original issue, you probably want to disable `utf8` encoding of the response body.

> .then((response) => {

That's not the whole, code. What module are you using to fetch the data? Please post the whole script.

**Comment by gireeshpunathil** [comment]
ping @kutlaykural

**Comment by kutlaykural** [comment]
Here is whole code:
```js
var downloadUrl='/v1/enterprise/import/template/'+jobId;
cy.request({
    method: 'GET',
    url: downloadUrl 
}).then((response) => {
    const fs = require('fs');
     fs.writeFile("out.xlsx",response.body,(err) => {
       if (err) throw err;
       console.log('The file has been saved!');
      })
})
```
I am using Cypress test automation tool library. And cy.request is the HTTP request method. Response code is 200 and response body seems like this:
<img width="486" alt="screen shot 2018-07-31 at 23 27 07" src="https://user-images.githubusercontent.com/38225108/43485236-506764fa-9519-11e8-8025-42ec76c4e649.png">

**Comment by gireeshpunathil** [comment]
I think the question is about the format of the excel file. Do you have any idea? Looking at goole, I see this one https://en.wikipedia.org/wiki/Microsoft_Excel#XML_Spreadsheet explaining the file format. There is an XML format, into which you will have to fit in the data. I have tried this for `.xls` format, and it works. Please note for `.xlsx` you may need to do additional steps. The details are there in the mentioned page. Hope this helps.

**Comment by kutlaykural** [comment]
I see. But downloading same file with using Content-Disposition header in response works properly

**Comment by gireeshpunathil** [comment]
thanks for the response. So what is the conclusion here? Is there anything that Node.js need to workaround, or fix? I am unable to figure out one, please clarify

**Comment by gireeshpunathil** [comment]
closing as inactive, please re-open if necessary.
