### ISSUE TITLE
Problem With Transform Stream

### ISSUE THREAD

**Issue by wmgarvin** [nodejs/help#1381]
* **Node.js Version**: v8.10.0 & v8.11.2
* **OS**: Windows 7 & 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: fs, stream

I am trying to use a transform stream to pipe a text file through, make some modifications, and then pipe the result to another text file.  The issue I am having is that the output file has lines where they are cut off and what should be on the next new line starts mid-line.  On my example this happens every 60 lines regardless of file length.  I am using the Notepad++ compare plugin to spot the differences.

https://github.com/wmgarvin/transform-stream-test

This repo is just a quick and dirty test and the transform stream should actually not be making any modifications at all since the filter matches every line.  If I remove the filter and do something simpler like .toUpperCase() there is no lost data.  I also tested by chunking the input file into a buffer and writing to the output instead with the filter in place and there is no lost data.  I also tried the simple fs.readFile and fs.writeFile methods (which Node docs advise against and say to use streams instead) and again, the filter is in place and no data is lost.  I thought that my work PC on Win7 might be too slow and causing issues but the same problem is replicated on my personal, brand new Win10 PC.  I'm not sure if I've run into a bug or I'm just doing something wrong?

**Comment by wmgarvin** [comment]
I think I'm going to go with a combination of the node-stream and through2 packages as they seem to address the problems I'm having.  I'll leave this open for now in case someone with a better understanding of the core Node stream module has some thoughts.

**Comment by trvsapjiac** [comment]
I don't see any problems with the Transform stream. Your code doesn't work for several reasons.

```js
const chunkArray = chunk.toString().split(/\r\n/);

const results = chunkArray.filter((line) =>
  line.includes("STOP") || line.includes("START") || line.includes("ATTEMPT")
).join("\r\n").toString();

callback(null, results);
```

Note that `chunk` may be any part of the input, theoretically it may be even a single byte (character). Suppose you have the following text:

```
START,abc
STOP,def
```

The stream may split it like this:

```json
[
  "STAR",
  "T,abc\r",
  "\nSTOP,d",
  "e",
  "f"
]
```

Your script will output

```
STOP,d
```

You should not assume that the input will be split at the places you expect. Also, the fact that the 60th line is broken is because the stream splits the chunk around that line (on average).

**Comment by wmgarvin** [comment]
I was thinking it seemed like a chunk size issue, and this makes sense. I think the default chunk size is 16KB, the file is 1079KB, which is right around 60 lines per 16KB. I suppose transform streams are more useful for simpler operations like toUpperCase() or replacing characters instead of how I'm trying to use it. It also makes sense why buffering the whole file or using fs.readFile works just fine, too. Can you think of a way to successfully implement this or will it just not work piping read > transform > write streams? Thanks!

**Comment by trvsapjiac** [comment]
>  Can you think of a way to successfully implement this

Not sure what exactly you want to implement. This script extracts lines from chunks and processes lines independently of the chunk boundaries.

```js
'use strict';

const { Transform } = require('stream');

var text = '';
var index = 1;

const TransformStream = new Transform({
  transform(chunk, encoding, callback){
    text += chunk;

    var lines = text.split(/\r\n/);
    text = lines.pop();

    var result = lines.map(line =>
      processLine(line, index++)
    ).join('\r\n') + '\r\n';

    callback(null, result);
  }
});

module.exports = TransformStream;

function processLine(line, index){
  return line.toUpperCase();
}
```

Function `processLine` receives one line at a time, where `line` is the string representing the line (without `\r\n`) and the index is 1-based index of that line (from the start of the file, not the chunk).

**Comment by wmgarvin** [comment]
My goal is to keep lines with certain terms, hence the filter in my original code.  The script you provided gets close but I can't filter on a string.  In my example, every line will start with START, STOP, or ATTEMPT.  I hacked this together and it at least doesn't alter the original file, so it's at least keeping the full lines in tact regardless of chunks.

```
"use strict";

const { Transform } = require("stream");

let text = "";
let index = 1;

const TransformStream = new Transform({
  transform(chunk, encoding, callback) {
    text += chunk;

    const lines = text.split(/\r\n/);
    text = lines.pop();

    const result = lines.map(line =>
      processLine(line, index++)
    ).join("\r\n") + "\r\n";

    callback(null, result);
  }
});

module.exports = TransformStream;

function processLine(line, index) {
  let test = [];
  test.push(line);
  let testStr = test.filter((testing) => testing.includes("STOP") || testing.includes("START") || testing.includes("ATTEMPT")).pop();
  if (testStr) {
    return testStr;
  }
}
```

The only issue now (aside from being a total hackjob) is that if I filter on just one or two terms (say, just STOP) it leaves empty lines.  Probably a quick fix but I didn't dive into it yet.  Thank you for at least getting me this far!

**Comment by trvsapjiac** [comment]
Here you go. If you return `null` from the `processLine`, that line will be ignored (not leaving blank lines, but removing lines completely). In this example, we are leaving only lines that start with `START`. Hope it helps.

```js
const TransformStream = new Transform({
  transform(chunk, encoding, callback){
    text += chunk;

    var lines = text.split(/\r\n/);
    text = lines.pop();

    var result = lines.map(line =>
      processLine(line, index++)
    ).filter(a => a !== null).join('\r\n') + '\r\n';

    callback(null, result);
  }
});

function processLine(line, index){
  if(!line.startsWith('START')) return null;
  return line.toUpperCase();
}
```

**Comment by wmgarvin** [comment]
Amazing, much simpler solution.  I didn't even think about startsWith().  I verified that if I just return line the file is unaltered.  Full code below and committed repo in case anyone happens across this in the future.  Thanks again!  Will leave thread open just a bit longer.

```
"use strict";

const { Transform } = require("stream");

let text = "";
let index = 1;

const TransformStream = new Transform({
  transform(chunk, encoding, callback) {
    text += chunk;

    const lines = text.split(/\r\n/);
    text = lines.pop();

    const result = lines.map(line =>
      processLine(line, index++)
    ).filter(a => a !== null).join("\r\n") + "\r\n";

    callback(null, result);
  }
});

module.exports = TransformStream;

function processLine(line, index) {
  if (!line.startsWith("START")) return null;
  return line;
}
```
