### ISSUE TITLE
Help with IPC and child_process with ES6

### ISSUE THREAD

**Issue by sammyrc34** [nodejs/help#1383]
* 8.11.2 & 10.6
* Linux, debian x86_64
* runtime
* child_process

IPC with a ES6 child process created via child_process.fork() appears to go nowhere. When sending a message, the child appears to never receive it. Further testing shows that other events (eg exit) are working.

To demonstrate, parent.mjs:
```js
import cp from 'child_process';
const kid = cp.fork( 'test.mjs' );
kid.send( { msg: "Hey there kid" } );
setTimeout( () => { process.exit(0) }, 2000 );  
```

And test.mjs
```js
class Test {
  constructor() { }
  msg(message) { console.log( "Kid got", message ); }
}
const test = new Test();
process.on( 'message', (m) => { test.msg(m) } );
```

To test further, I created my own named socket IPC using net.createServer(path), between such a parent and child, and bidirectional communication is working.

I really just want to know if this is something I should create an issue about.

**Comment by vsemozhetbyt** [comment]
cc @nodejs/child_process @nodejs/modules-active-members

**Comment by benjamingr** [comment]
Can you try putting the `.send`  in a `setTimeout`? I think you're calling `.send` synchronously before the child process has run the `process.on( 'message', (m) => { test.msg(m) } );` code.

**Comment by bmeck** [comment]
in general you can see dropped messages due to timing like @benjamingr said, it is a much more foolproof workflow to have your child notify the parent that it is fully loaded before sending it messages from the parent.

**Comment by sammyrc34** [comment]
@benjamingr Thank you! You're correct. 

@bmeck, yes, that is a much better approach. 

Thank you both for the help.
