### ISSUE TITLE
prepackaged binary node 10  for debian stretch i386 missing?

### ISSUE THREAD

**Issue by aletus** [nodejs/help#1384]
* **Node.js Version**: 10.x
* **OS**: debian stretch i386
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Followed instruction at: 
https://nodejs.org/en/download/package-manager/

but when apt-install it does not install node 10 but the old node 4 from debian repository

packages seemed to be empty/zero byte at:
https://deb.nodesource.com/node_10.x/dists/stretch/main/binary-i386/

Same instruction for node 8 works so node 10 binaries seemed to be missing

**Comment by richardlau** [comment]
We stopped providing 32-bit Linux builds in 10.x. See the discussion in https://github.com/nodejs/build/issues/885.

**Comment by aletus** [comment]
Thanks.  Should update website at:
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

It is currently saying

Available architectures:

- **i386 (32-bit)**
- amd64 (64-bit)
- armhf (ARM 32-bit hard-float, ARMv7 and up: arm-linux-gnueabihf)

**Comment by tuxolo** [comment]
What a stupid idea
