### ISSUE TITLE
Help for beginer  Node js

### ISSUE THREAD

**Issue by liorsultan9** [nodejs/help#1388]
Hi .
I  have a github account and I wonder if somene
can help me .
Do  github account(desktop and online) is enough or I need to install somthing?
for example , I want to run this simple code and it doesnt work.
Thank in advanve.

var http = require('http');
// In general, you need to specify a call-back function with most of the Node modules methods
http.createServer(function (request, response) {
    response.writeHead(200); //Status code in header
    response.write("Introduction"); //Response body
    response.end(); //Close the connection
}).listen(8080); //Port in which node will listen for connections

console.log('Listening on port 8080...');

**Comment by liorsultan9** [comment]
thanks

**Comment by lordKnighton** [comment]
@liorsultan9 😃 no worries we will get you sorted. 
here is how i got your program running in under 2 mins - 

first on your desktop:
- make a folder(exampleJS)
on mac:
go into your terminal
cd to that folder(exampleJS) ` $ cd exampleJS `
type: ` $ npm init -y` (it will yield a JSON file which you need for npm packages)
type: ` $npm install node` (if you have permission problems type[sudo npm install node]
type: ` $ touch app.js` (or you can do this manually by going in folder and right click then create file)
then go into app.js - (you can open this in a simple text editor, vscode or brackets & sublime, atom ..)
if your in your terminal: type ` $ vim app.js` (just paste your code then press: ` $:wq` (save & exit file)

photos below: (let us know if you need anymore help) 

![screen shot 2018-07-17 at 5 58 51 pm](https://user-images.githubusercontent.com/1773260/42853656-b5d64dd4-89ec-11e8-9716-1d5789dd2868.png)
![screen shot 2018-07-17 at 5 59 08 pm](https://user-images.githubusercontent.com/1773260/42853660-bf5a0f58-89ec-11e8-9969-ee8e88903832.png)

![screen shot 2018-07-17 at 6 11 34 pm](https://user-images.githubusercontent.com/1773260/42853693-e1d39fb8-89ec-11e8-910c-9aa0c978ad0d.png)

**Comment by liorsultan9** [comment]
Thank you .
I have 2 more questions:
1. if  I will use https://electronjs.org/  I will not need to install node js, this  is correct?
2. I now that this question its a little bit odd, but...
how a user that get an  application that base on node js can tun it without the fact that he 
never installed the software before?
Thank you again

**Comment by ahmtcn123** [comment]
1. You have to install nodejs if you want node-integration .

2. You can use electron to build desktop apps. I recomend you to see this docs it will help you a lot . 

https://electronjs.org/docs

**Comment by lordKnighton** [comment]
@liorsultan9 I hope you are thoroughly sorted, you good?

**Comment by liorsultan9** [comment]
Hi;
thank you for your help, yes I  am.
I  using Atom.
Best

בברכה
ליאור סולטן

2018-07-29 8:03 GMT+03:00 kelvin knighton <notifications@github.com>:
