### ISSUE TITLE
On install mariasql package in node

### ISSUE THREAD

**Issue by sandeepjain2015** [nodejs/help#139]
When i install mariasql than following error is coming
C:\Users\Cres\NodeJS\DatabaseTest\node_modules\mariasql>if not defined npm_confi
g_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
[npm-debug.log.txt](https://github.com/nodejs/help/files/212945/npm-debug.log.txt)

gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Cres\NodeJS\DatabaseTest\node_modules\mariasql
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "mariasql"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! mariasql@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mariasql@0.2.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mariasql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mariasql
npm ERR! There is likely additional logging output above.
   
I have include following file to see error 

Please help 

If anybody have online link for chat support on node js than please provide

Thanks

Sandeep 
skype:sandeepjainmcscet

**Comment by TheAlphaNerd** [comment]
@sandeepjain2015 it looks like you don't have python in your path. Getting windows setup to support native modules is not exactly "intuitive".

You may have better luck posting over on http://github.com/nodejs/help

Here is a a guide that may help --> https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

Closing for now as this issue isn't related to node core, but please feel free to ask more questions (although you will get a better response in help as mentioned above)

**Comment by SomeoneWeird** [comment]
But this is help...

**Comment by TheAlphaNerd** [comment]
@sandeepjain2015 / @SomeoneWeird womp

This is what I get for responding via email. WOMP.

Thanks for reopening @Fishrock123

**Comment by lordKnighton** [comment]
Hey @sandeepjain2015  did you fix your error?

**Comment by sandeepjain2015** [comment]
No  @lordKnighton , i do not know  what is wrong with this, i see mongo db tutorial which also i installed  .But i do not know more in mongo db ,actually i am from php background .so i want node with mysql
I  think this is some problem with setup in node ,But i see many url related to setup but nobody say about this

**Comment by lordKnighton** [comment]
`Try setting it to the path of the python exe`, maybe this is a long shot, but it's a shot

==
she was having the same problem, but a different program [click me](https://github.com/ssbc/scuttlebot/issues/185)  I'll keep updating this until we solve your problem.

**Comment by lordKnighton** [comment]
If none of that worked try this: And be sure to read the README.md 

https://github.com/nodejs/node-gyp#installation

**Comment by lordKnighton** [comment]
feel free to reopen  😸

**Comment by TheDedede** [comment]
For those from google: *python 3.x.x* is not supported. You'll need to download *python 2.7.x or lower*
