### ISSUE TITLE
Проблема с установкой! (Install Issue)

### ISSUE THREAD

**Issue by Forip-Fastiks** [nodejs/help#1391]
**При установки node.js возникает ошибка error code is 2203  первый скриншот + даже не могу удалить node.js из удаление программы при удаление выскакивает предупреждение скриншот второй ниже.
![screenshot_9](https://user-images.githubusercontent.com/41447433/42960706-6cd247f0-8bae-11e8-9770-dc1991cedb00.png)**

![screenshot_1](https://user-images.githubusercontent.com/41447433/42961793-ace9f8a8-8bb1-11e8-85df-231c9c79b0de.png)

**Comment by vsemozhetbyt** [comment]
Generalized translation:
While installing Node.js, there is an "error code is 2203" message (see the second screenshot).
Also, I cannot even uninstall Node.js (see the first screenshot).

**Comment by vsemozhetbyt** [comment]
cc @nodejs/platform-windows

**Comment by Forip-Fastiks** [comment]
Платформа Windows

**Comment by vsemozhetbyt** [comment]
@Forip-Fastiks Вам удалось решить проблему?

**Comment by Forip-Fastiks** [comment]
Ненату кнопку нажал извините! Платформа Windows 7 Ultimate

**Comment by vsemozhetbyt** [comment]
@Forip-Fastiks Вы сможете понять, о чём здесь говорится и проверить предлагаемые решения?

https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/error-code-2203-when-trying-to-install-a-program/a1461ca8-f0fd-406d-ae91-c3afc4cf22ce

**Comment by Forip-Fastiks** [comment]
Гляну если помогут решения напишу вам!

**Comment by vsemozhetbyt** [comment]
Проверьте ещё на всякий случай, не отключён ли «Установщик Windows» в службах.

**Comment by Forip-Fastiks** [comment]
@vsemozhetbyt Установщик Windows работает не понимаю серавно этого доступ модерации полный.

**Comment by vsemozhetbyt** [comment]
Вы давно устанавливали ту версию, которую не можете удалить (восьмая, кажется)? С тех пор ничего в системе не менялось? Другие программы устанавливаются?

**Comment by Forip-Fastiks** [comment]
Версия 8.11.1 эта? Если она пожалуста скажите как её удалить!

**Comment by vsemozhetbyt** [comment]
Вроде она установлена. Может это огрызок от неудавшейся установки, поэтому и не удаляется? Попробуйте поверх неё поставить 10.7.0 отсюда: https://nodejs.org/en/
