### ISSUE TITLE
Must always Atomic.* operations be used on a SharedArrayBuffer + multiple threads?

### ISSUE THREAD

**Issue by idleman** [nodejs/help#1393]
I have a  SharedArrayBuffer that it is shared among multiple threads (some with different v8::Isolate actually) and currently use Atomics operations everywhere, but is it required if we taking into account how our computers work?  CPUs process chunks of data, so if I synchronize a value at [index], using Atomics.load() should not automatically every value after that index to some degree (the next 64/128/256) bits or so be available? Do anyone have any insight into this?

```
    const value1= Atomics.load(buffer, 0)
    const value2 = buffer[1]; // Must this operation be an Atomic operation?
```

**Comment by nidin** [comment]
When you do operation on a SharedArrayBuffer from multiple threads the data will be copied to CPU cache memory. You need to use Atomic operations in order to lock on an address and block other threads to read/write to that address while a thread is performing an operation.
So, Yes. You must always use Atomic operations if you know that multiple threads will read/write same index of SharedArrayBuffer.

**Comment by addaleax** [comment]
You may want to give a more complete example here … what exactly do you mean by “synchronized”? All that is guaranteed by `Atomics` is that the operation executes as a whole and doesn’t conflict with other operations on the same address. It doesn’t specify an order of these operations, and it is *not* a lock/mutex/etc. – for that, you have to turn to `Atomics.wait()`/`Atomics.notify()`.

**Comment by idleman** [comment]
Thanks for your answers Nidin and Anna. Let me take a more complete example, here is my "read" method (handling duplex communication between threads):

```
 read(buffer, position = 0, offset = 0, maxLength = 2**16-1) {
    if(position < 0) {
      return 0;
    }

    return this.sleepUntilReadable(() => {
      const { dataView } = this._Block;
      const length = Math.min(this._getSize() - position, buffer.length - offset, maxLength);
      if(length <= 0) {
        return 0;
      }

      for(let i = 0; i < length; ++i) {
        buffer[offset + i] = load(dataView, position + i); // load === Atomics.load
      }
      return length;
    });
  }
```

It will block the thread until it is readable (no ongoing write operation or so) and then it is readable, will it copy the content of  dataView (shared Uint8Array) to buffer. It is tested and it works. However, the Atomics.load is a bit slow, I got around 100 Mb/s on my machine and it is rather slow for just copying stuff around in memory. So I am looking for ways to improve it. 

One way I thought of if I really need to do Atomics.load on every single byte in the for-loop. I currently process 8 bit per loop-cycle, but I believe CPUs manipulates a 32 bit values internally, and just convert those to uint8 then needed. I know it is common in the code a C++ compilator generates and depending on how Google V8 internally work, may it so something similar. If it would be the case, would I only need to do Atomics.load every 4 th time instead and it will still be safe

But after some thoughts, probably would it be better to just read a Uint32 and convert it to 4 x Uint8 values instead, something if my assumption above is correct is done internally.

**Comment by addaleax** [comment]
@idleman Can you explain why you need atomic loads here? If there is a chance that another thread is writing to the buffer concurrently, you will still have race conditions to take care of. If that is not the case (the `sleepUntilReadable` name hints at that, but it’s not clear from your example), then you don’t need atomic operations anyway, and you can just copy the data as it is.

**Comment by idleman** [comment]
Because the values was wrote from another thread using Atomics.store and I want the receiver the see the actual data, not any cached data. Everything is passed through multiple threads. No data that is written will be consumed by the same thread. And there is no chance another thread is writing to the buffer concurrently.

**Comment by addaleax** [comment]
> I want the receiver the see the actual data

@idleman If this is your main concern, what you want is a memory barrier¹, and it should be safe to assume that the way in which you notified the other thread of readiness already took care of that. For example, `Atomics.wait()`/`Atomics.notify()` issue memory barriers, as does the more complex `messageport.postMessage()`.

<sub>(¹ a CPU memory barrier, not a compiler memory barrier, that is. I don’t think the JS engines (can) perform significant re-ordering of loads/stores that would affect you.)</sub>

**Comment by idleman** [comment]
Well, in that case would I not need the Atomics.load operation at all, because I use Atomics.wait/Atomic.notify a lot Thanks, I didnt knew that!
