### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by ZackZeng123** [nodejs/help#1394]
Versionv 8.11.3
Platform: Windows 7 32-bit

-->
The version of node.js i installed is node-v8.11.3-win-x86, and my laptop is 32-bit window7. After node.js was installed, i tried to use command-line to run "npm install", it kept showing an error log as below, please take a look for me, thank you very much~~~
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session 250dbf6cd94cf533
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall chariotextract@1.0.0
7 info lifecycle chariotextract@1.0.0~preinstall: chariotextract@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly fetchPackageMetaData error for fs@0.0.1-security request to https://registry.npmjs.org/fs failed, reason: certificate is not yet valid
15 silly fetchPackageMetaData error for shelljs@^0.8.2 request to https://registry.npmjs.org/shelljs failed, reason: certificate is not yet valid
16 silly fetchPackageMetaData error for fs@0.0.1-security request to https://registry.npmjs.org/fs failed, reason: certificate is not yet valid
17 silly fetchPackageMetaData error for shelljs@^0.8.2 request to https://registry.npmjs.org/shelljs failed, reason: certificate is not yet valid
18 silly saveTree chariotextract@1.0.0
19 verbose type system
20 verbose stack FetchError: request to https://registry.npmjs.org/fs failed, reason: certificate is not yet valid
20 verbose stack at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
20 verbose stack at emitOne (events.js:116:13)
20 verbose stack at ClientRequest.emit (events.js:211:7)
20 verbose stack at TLSSocket.socketErrorListener (_http_client.js:387:9)
20 verbose stack at emitOne (events.js:116:13)
20 verbose stack at TLSSocket.emit (events.js:211:7)
20 verbose stack at emitErrorNT (internal/streams/destroy.js:64:8)
20 verbose stack at _combinedTickCallback (internal/process/next_tick.js:138:11)
20 verbose stack at process._tickCallback (internal/process/next_tick.js:180:9)
21 verbose cwd C:\Users\Octoscope.Octoscope-PC\Desktop\data process
22 verbose Windows_NT 6.1.7601
23 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
24 verbose node v8.11.3
25 verbose npm v5.6.0
26 error code CERT_NOT_YET_VALID
27 error errno CERT_NOT_YET_VALID
28 error request to https://registry.npmjs.org/fs failed, reason: certificate is not yet valid
29 verbose exit [ 1, true ]

**Comment by NickNaso** [comment]
@ZackZeng123 Dis you solved?

**Comment by ZackZeng123** [comment]
Yes, the problem has gone, thank you for telling me~~~

 

..................................................................................................................................................................

Zack Zeng

 <tel:13761248519> Tel:13761248519

Email:zack.zeng@paralink.com.cn

Address:609,Huawen International Plaza

No999,West Zhong Shan Road,Shanghai

Zip:200051

……………………………………………………………………………………………………………………………………

 

发件人: Nicola Del Gobbo [mailto:notifications@github.com] 
发送时间: 2018年7月31日 2:12
收件人: nodejs/help <help@noreply.github.com>
抄送: ZackZeng123 <zack.zeng@paralink.com.cn>; Mention <mention@noreply.github.com>
主题: Re: [nodejs/help] npm install failed (#1394)

 

@ZackZeng123 <https://github.com/ZackZeng123>  Dis you solved?

**Comment by NickNaso** [comment]
Ok I think that we can close the issue.
