### ISSUE TITLE
callback

### ISSUE THREAD

**Issue by woodyinho** [nodejs/help#1398]
Hello Geeks, could you please tell me how to master callback and callback hell ?

**Comment by gireeshpunathil** [comment]
a detailed explanation on the event driven programming is available here: https://github.com/nodejs/help/issues/1118 . If you have doubts on any specific area(s) please let me know.

`callback hell` is a `meme` and is neither defined nor documented within Node.js project. The wording originates  from complete or partial inability to follow the control flow when large ( more than 3) number of callbacks are connected together. The perceived lack of readability and associated potential program(mer) error is generally referred to as callback hell.

Primary use case for callback is completion handing of an I/O work that happens asynchronously. While this is pervasively used in Node programs, chaining such callbacks deeply is not a common thing, and I am yet to see a real use case where more than 10 callbacks chain up to complete a common business logic. There could be one or two, but then those would probably the central part of an application (such as the composition layer of a webapp that follows microservice architecture) and would be carefully developed and reviewed with control flow well tested.

The meme largely come from programmers from other languages who perceive code sequences to be executed in the order in which those were written.

[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) is a way to circumvent callback chaining. Promise do not avoid callbacks, instead they hide the visibility of the chaining from the user program.

Usage of promise in large scale production systems may degrade overall performance.

**Comment by gireeshpunathil** [comment]
are you willing to be active in the community? then there are a number of things I can suggest:
 - node.js doc: https://nodejs.org/dist/latest-v10.x/docs/api/ [ this gives an idea about what are the Node.js APIs ]
 - node.js test suite: https://github.com/nodejs/node/tree/master/test [ this gives an idea about how the APIs are used
 - https://github.com/nodejs/node/labels/good%20first%20issue [ this gives a list of items one of which you can start reviewing and see if you can work on it ]

Expressjs is not part of Node.js project, so I cannot comment on that.

Good luck!

**Comment by woodyinho** [comment]
Thanks so much I really appreciate that.
Does nodejs is good path to work as web developer in big companies like in europe or usa ?

**Comment by gireeshpunathil** [comment]
ah! although it is an honest and awesome question, I cannot answer it, something that influences your career decision.

However, I will copy @nodejs/community-committee to chime in and advise, assuming they are best placed to respond to that within this project.

If there is anything more on technical help and support, I am happy to assist! thank you.

**Comment by gireeshpunathil** [comment]
Closing as answered.
