### ISSUE TITLE
running node in apachie

### ISSUE THREAD

**Issue by nagababji123** [nodejs/help#14]
Hai,

I am the beginner of nodejs. I created service using express and I am trying to post the data from my application which is running on 8080(tomcat) and my nodejs server is running on port 3000.
Is there a way to combine both of them in tomcat and run in single server?
Thank you,
Babji.

**Comment by bnoordhuis** [comment]
You can configure a connector to reverse-proxy HTTP requests from tomcat to node, or run both behind httpd or nginx.  But this question doesn't really belong here, please try https://github.com/nodejs/help/issues.

**Comment by rvagg** [comment]
this is https://github.com/nodejs/help/issues @bnoordhuis, re-opening because someone might be able to explain the idiomatic ways of configuring these kinds of combinations

**Comment by bnoordhuis** [comment]
Sorry about that, I could swear I was in nodejs/node.

**Comment by lordKnighton** [comment]
@nagababji123 did you still need help with this? Closing for now, please refer [here](https://www.quora.com/Is-there-a-way-to-run-a-Node-js-application-within-a-Tomcat-server) and let me know, if still need help.
