### ISSUE TITLE
How to make variables/classes available without prepending varname

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1400]
Hi all,

I am working with module.exports a lot, and I was wondering:
isnt there a cleaner way of doing this? What I do now is I place all my logic within the brackets of module.exports = {}
And then I have to say var X = require('FILENAME');

Then I have to assign a variable to the module... (Why) is this necessary? Cant I just include all the code of a file, and include it in a way that I can use the exact variable names as in the original file? So without first using a variable name that is assigned to the entire module?

**Comment by NickNaso** [comment]
Hi @WAINGOR maybe you can di this:

```js
function foo() {}
class Zoo() {}
module.exports = {
   foo,
   Zoo
}
```
```js
const {foo, Zoo} = reuire('file-that-contains-foo-and-Zoo')
```
I don't know if this is really your needs. Hope to be helpful.

**Comment by gireeshpunathil** [comment]
> Cant I just include all the code of a file, and include it in a way that I can use the exact variable names as in the original file?

For a single import it might be good, but you start using more modules in this way, you will soon see that the names are colliding each other, and your code soon get cluttered. So modules provide a fine container for the code and data that embodies.

As JS is any other language, it is possible to tweak the grammar definition and the associated parser and compiler to implement the grammar in any way one wish, but it was chosen this way for improving the usability of the modules.

Hope this explanation helps.

**Comment by WAINGOR** [comment]
thanks you all : )
