### ISSUE TITLE
[N-API] How to clone a napi_value of type <any>?

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [nodejs/help#1401]
* **Node.js Version**: v10.5.0
* **OS**: Win7 x64
* **Module (and version) (if relevant)**:

The thing I'm trying to do is to call a native function `foo` that uses N-API from my JS code and provide it with an argument that can be of any type.
This argument should be stored for later use.

Since it seems that you're freeing the memory of arguments provided by `foo`'s `cb_info` once its execution has finished, I can't simply use pointers. (Maybe I'm wrong about this but I have gotten random data when trying to access those locations later on)

Is there any way to do this?

["Google tags": duplicating, copying napi_values]

**Comment by NickNaso** [comment]
Hi @s-h-a-d-o-w you're right the variable is available until the end of the execution of the function, after that it is eligible to be garbage collected. To avoid this behavior you need to store you value on a reference. You can create a **napi_reference** and store the **napi_value** in the reference. See [https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_references_to_objects_with_a_lifespan_longer_than_that_of_the_native_method](https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_references_to_objects_with_a_lifespan_longer_than_that_of_the_native_method)

**Comment by s-h-a-d-o-w** [comment]
Works great, thanks a lot!!

Side note for others possibly stumbling across this: Since one can only use references with objects, I got around the problem of wanting to supply any type by simply wrapping my input in an object. So now, even my Symbols work... :+1:
