### ISSUE TITLE
How do I add a wild card certificate to node.js

### ISSUE THREAD

**Issue by mikhailmendoza** [nodejs/help#1402]
Hi 
do you have any Idea on how to add a wild card certificate in node.js ?
Im using node.js v8.11.1 express framework 4.16.2 deployed in windows server 2016

**Comment by lordKnighton** [comment]
Hey I personally don't have any experience with this, but here are a few links, let me know if they helped.

https://cheapsslsecurity.com/blog/how-to-install-ssl-certificate-on-node-js/

https://www.bennadel.com/blog/3420-obtaining-a-wildcard-ssl-certificate-from-letsencrypt-using-the-dns-challenge.htm

**Comment by mikhailmendoza** [comment]
Thanks for the reference link I'll try to look into it
