### ISSUE TITLE
child_process.spawn does not receive SIGINT.

### ISSUE THREAD

**Issue by heroboy** [nodejs/help#1405]
* **Version**:v10.4.0
* **Platform**:Microsoft Windows [Version 10.0.17134.191]

testspawn.js: create a child process `node child`
```javascript
var child_process = require('child_process');

var childprocess = child_process.spawn('node', ['child'], { cwd: __dirname, shell: true, detached: true, stdio: 'ignore' });

childprocess.on('exit', e =>
{
	console.log('child is exit')
});
```
child.js: listen SIGINT to exit the program
```javascript
var repl = require('repl')
var count = 0;
var interval = setInterval(function ()
{
	console.log(`count = ${count++}`);
}, 500)

process.on('SIGINT', () =>
{
	console.log('sigint exit');
	clearInterval(interval);
})

process.on('SIGBREAK',()=>{
	console.log('sigbreak exit');
	clearInterval(interval);
})
repl.start();
```
Run the `testspawn.js` , I can't use Ctrl+C to exit the program, only Ctrl+Break works. When Ctrl+C pressed or enter `.exit`, the `repl` would stop working.

I don't it is an intend feature, or I pass the wrong paramters of spawn function.

**Comment by heroboy** [comment]
hi @gireeshpunathil ,
The code is `var count = 0;`

Speak to the use case, the testspawn.js actually runs in electron, and it runs another node program. If I doesn't do this, I need to write my own terminal like widget in HTML Dom, it is hard to do and performance is not good as OS native console window.

And for `repl`, it is to demonstrate using `.exit` to exit the program, and strange behavior that stop working when press Ctrl+C. If you remove all `repl` relate code, you can't receive the `SIGINT` event.

**Comment by gireeshpunathil** [comment]
thanks for the info. let me see if I can figure out anything when I get a windows system.

**Comment by heroboy** [comment]
I had tried something else. In child.js , the code is correct:
```javascript
repl.start().on('exit',()=>{
//I can receive exit event.
});
```
But then I inspected the `repl.js` code, and used the way `repl.js` that listening SIGINT. It didn't work when child.js was launched by another process.
```javascript

const utilBinding = process.binding('util');
var count = 0;
var interval = setInterval(function ()
{
	console.log(`count = ${count++}`);
}, 500)


if (!utilBinding.startSigintWatchdog())
{
	console.log('error startSigintWatchdog')
}

waitForPendingSignal(function(){
	requestExit();
})

function waitForPendingSignal(cb)
{
	if (utilBinding.watchdogHasPendingSigint())
		cb();
	else
		setTimeout(waitForPendingSignal, 10, cb);
}

function requestExit()
{
	console.log('sigint exit');
	clearInterval(interval);
}


```

**Comment by gireeshpunathil** [comment]
@heroboy - is this still an issue?

**Comment by heroboy** [comment]
@gireeshpunathil yes, it is still occure in recent node v12.4.0

**Comment by gireeshpunathil** [comment]
In the parent, can you please add this code and test?

```js
process.on('SIGINT', () =>
{
  console.log('parent received sigint');
  child.kill('SIGINT');
})
```

**Comment by heroboy** [comment]
@gireeshpunathil 
tested. Nothing happened when I pressed Ctrl+C in the child console.

**Comment by gireeshpunathil** [comment]
ok, sorry - I did not pay attention to the `detached: true` option that you supplied. According to the doc:

`On Windows, setting options.detached to true makes it possible for the child process to continue running after the parent exits. The child will have its own console window. Once enabled for a child process, it cannot be disabled.`

So basically a `SIGINT` to a detached terminal seem to be a no-op. So:
 - either you could remove `detached: true`
 - or if that does not suit your needs, send another signal - say 'SIGTERM'

**Comment by heroboy** [comment]
1. `childprocess.kill('SIGTERM')` nothing happened.
2. My need is not parent kill child. But wondering the strange behaviour of child console. Doesn't receive ctrl+C, and repl freeze.

**Comment by gireeshpunathil** [comment]
ok, I will investigate more and get back.

**Comment by heroboy** [comment]
After some research, I know why repl freeze.
`repl` receive `SIGINT` event from `readline` module,and close itself. 

And `readline` uses some code like this to receive ctrl+C:
```javascript
process.stdin.on('data', data =>
{
        //data may contains Ctrl+C in raw mode
})
process.stdin.setRawMode(true);
```

**Comment by Ayase-252** [comment]
I'm assuming that the issue has been resolved. Closing, if it is not the case, please feel free to reopen it.

**Comment by heroboy** [comment]
@Ayase-252 no, it is not.
I tried in the latest v16.8.0, the issus is still there.

**Comment by heroboy** [comment]
So what do you think this?
If it is intended, I don't care it is a feature.

**Comment by Ayase-252** [comment]
Sorry, I don't have a windows machine at hand right now. Might people on triager team help?

cc @nodejs/issue-triage

**Comment by bmuenzenmeyer** [comment]
it sounds like this issue should perhaps transfer to https://github.com/nodejs/node/issues as a legitimate issue?

**Comment by preveen-stack** [comment]
@bmuenzenmeyer can we close this issue in light of the closure of nodejs/node#45723
