### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by white-cloud** [nodejs/help#1407]
Hello everyone,

I'm having always this error when trying to execute my function, but i still don't get it:
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'body' of undefined
(node:38) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My current nodejs version is: 8.9.1
Here it is my code:

```js
'use strict';

const rp = require('request-promise-native');

module.exports = async function (context) {
const stringBody = JSON.stringify(context.request.body);
const body = JSON.parse(stringBody);
const location = body.location;

if (!location) {
    return {
        status: 400,
        body: {
            text: 'You must provide a location.'
        }
    };
}

try {
    const response = await rp(`https://query.yahooapis.com/v1/public/yql?q=select item.condition from weather.forecast where woeid in (select woeid from geo.places(1) where text="${location}") and u="c"&format=json`);
    const condition = JSON.parse(response).query.results.channel.item.condition;
    const text = condition.text;
    const temperature = condition.temp;
    return {
        status: 200,
        body: {
            text: `It is ${temperature} celsius degrees in ${location} and ${text}`
        },
        headers: {
            'Content-Type': 'application/json'
        }
    };
} catch (e) {
    console.error(e);
    return {
        status: 500,
        body: e
    };
}

}
```

Please any help with this issue.

Thank you.

**Comment by addaleax** [comment]
I’m just taking a guess here, but maybe in the `stringBody = JSON.stringify(context.request.body);` line `context.request` is `undefined`? If you add `console.log(context);` before, does that help?

If that doesn’t help: If you run `node` as `node --trace-warnings app.js`, you will see a full stack trace instead of just the error message. :)

And by the way, you can wrap pieces of source code that you post on github in  ```` ``` ```` so that it becomes more readable, for example:

    ```js
    console.log('Hello world!');
    ```

becomes

```js
console.log('Hello world!');
```

:slightly_smiling_face:

**Comment by white-cloud** [comment]
hello @addaleax  thank you for your answer, 
i tried your suggestion for adding console.log and here what i got as an output:

curl -H "Content-Type: application/json" -X POST -d '{"location":"Sieteiglesias, Spain"}'  http://172.16.52.11:31112/function/weather
{"location":"Sieteiglesias, Spain"}
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'body' of undefined
(node:38) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by white-cloud** [comment]
Hello again @addaleax i changed the  stringBody = JSON.stringify(context.request.body); to stringBody = JSON.stringify(context); , i have no more that error , but the code is giving me no output !!

**Comment by gireeshpunathil** [comment]
ping @white-cloud

**Comment by gireeshpunathil** [comment]
what does `console.log(context.request)` print? if it is undefined, you would need to investigate how that is happening and fix that.

**Comment by gireeshpunathil** [comment]
ping @white-cloud

**Comment by gireeshpunathil** [comment]
closing as inactive, please re-open if necessary
