### ISSUE TITLE
Odata module for hana db

### ISSUE THREAD

**Issue by Bharath-Basavaraju** [nodejs/help#141]
is their any package which supports odata for hana db

**Comment by lordKnighton** [comment]
https://www.npmjs.com/search?q=hana+db check here :)

**Comment by lordKnighton** [comment]
Gonna close for now, feel free to reopen to extend this discussion.

==
I've googled this again, but not really getting far on this, not really finding a myriad of packages for it, i want to help you, but there is not much to go on. 
check here for a few resources. 

https://www.sapappsdevelopmentpartnercenter.com/en/get-started/big-data/
