### ISSUE TITLE
Connect Nginx / Nodejs / Socket.io

### ISSUE THREAD

**Issue by marccasco** [nodejs/help#1410]
Good Morning,

I am trying to mount a nodejs server in a domain.

So far, along with nginx, I have managed to get it started, but I have a problem with the socket.io module, since it is as if it will not detect me that I enter the web page from the domain.

Do you know the reason or some way to solve the error?

Thank you very much in advance,
A greeting.

Version: 10.6.0
Platform: Ubuntu 16.04

**Comment by ankur-anand** [comment]
Not sure what is the error you've got or where exactly you are stuck but this will help you [Using NGINX and NGINX Plus with Node.js and Socket.IO, the WebSocket API](https://www.nginx.com/blog/nginx-nodejs-websockets-socketio/)

**Comment by kamilorzelek** [comment]
@marccasco Pls, provide some logs about this issue. Then we can try to help u.

**Comment by NickNaso** [comment]
Hi @marccasco,
I suppose that you use NGINX as a proxy could you provide an example of your configuration?

**Comment by marccasco** [comment]
Hello people,

Sorry for not answering, I was on vacation and I did not even notice.

I managed to connect the socket, anyway, I still could not differentiate between different users that connect to the domain.

**Comment by gireeshpunathil** [comment]
if you have a minimal test case to reproduce the issue and the actual error message that you got, please share.

**Comment by gireeshpunathil** [comment]
inactive, closing. please re-open if you have data to share, thnx!
