### ISSUE TITLE
ENOENT: no such file or directory, open './Emailcsv/[object Object]

### ISSUE THREAD

**Issue by susmitha01** [nodejs/help#1411]
How to resolve this ? I'm uploading (csv,html) files using node js & html 

var upload = require("express-fileupload")
app.use(upload())
app.post('/file_upload', function (req, res) {
  if(req.files){
    console.log(req.files)
    let  file = req.files.sampleFile;
    file.mv('.public/Emailcsv/'+file,function(err){
      if(err){
        console.log(err)
        res.send("error occured")
       }
      else{
        res.send("File uploaded")
      }
    })
  }
})

Can you please help me with this issue , Thanks in advance

**Comment by vsemozhetbyt** [comment]
If I get this right, `req.files.sampleFile` is an `Object`:

https://github.com/richardgirges/express-fileupload#example-scenario

So the line with string concatenation should be this:
```js
file.mv('.public/Emailcsv/'+file.name, function(err){
```

**Comment by gireeshpunathil** [comment]
ping @susmitha01 - were you able to resolve this by following @vsemozhetbyt 's suggestion?

**Comment by susmitha01** [comment]
I  used the below code, but it says file is not  defined 

> file.mv('.public/Emailcsv/' + file.name, function(err){

**Comment by gireeshpunathil** [comment]
```
#cat 1411.js
const express = require('express');
const fileUpload = require('express-fileupload');
const app = express();
app.use(fileUpload());
app.post('/upload', function(req, res) {
  let sampleFile = req.files.sampleFile;
  console.log(sampleFile)
  res.send('ok')
});

app.listen(12000)
```

```
#node 1411.js
{ name: 'Screen Shot 2018-08-13 at 8.09.51 PM.png',
  data:
   <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 04 16 00 00 01 f6 08 06 00 00 00 c4 5e 0f 8f 00 00 0a af 69 43 43 50 49 43 43 20 50 72 6f 66 69 ... >,
  encoding: '7bit',
  truncated: false,
  mimetype: 'image/png',
  md5: '40a992722c4da8e9c989a8ef8cac394e',
  mv: [Function: mv] }
^C
```

I am able to get the data, by following the example in the npm package site. Make sure you use the HTML form prescribed in the page for the browser and upload an actual file, not use the `/upload' route directly.

**Comment by susmitha01** [comment]
The above code you mentioned that's working fine, but i just want to save that particular  file in a path , so from that  i can read that data for my purpose..

**Comment by gireeshpunathil** [comment]
#cat 1411.js

```js
const express = require('express');
const fs = require('fs')
const fileUpload = require('express-fileupload');
const app = express();
app.use(fileUpload());
app.post('/upload', function(req, res) {
  let sampleFile = req.files.sampleFile;
  console.log(sampleFile.data)
  fs.writeFileSync('./foo.png', sampleFile.data)
  res.send('ok')
});

app.listen(12000)
```

after running the app and uploading a file:
#file foo.png
`foo.png: PNG image data, 966 x 486, 8-bit/color RGBA, non-interlaced`
#
you may need to customize `foo.png` to your purpose and occasion. can you try this?

**Comment by gireeshpunathil** [comment]
ping @susmitha01

**Comment by ashish-patidar-rau** [comment]
> #cat 1411.js
> 
> ```js
> const express = require('express');
> const fs = require('fs')
> const fileUpload = require('express-fileupload');
> const app = express();
> app.use(fileUpload());
> app.post('/upload', function(req, res) {
>   let sampleFile = req.files.sampleFile;
>   console.log(sampleFile.data)
>   fs.writeFileSync('./foo.png', sampleFile.data)
>   res.send('ok')
> });
> 
> app.listen(12000)
> ```
> 
> after running the app and uploading a file:
> #file foo.png
> `foo.png: PNG image data, 966 x 486, 8-bit/color RGBA, non-interlaced`
> 
> you may need to customize `foo.png` to your purpose and occasion. can you try this?

i will show some error 
Error: ENOENT: no such file or directory, open '/opt/NodeJS/xxxxx/controllers/public/uploads/groups/PVU0dxc.jpg'

**Comment by gireeshpunathil** [comment]
closing as inactive, please reopen if necessary
