### ISSUE TITLE
Build Node.js as static library

### ISSUE THREAD

**Issue by NickNaso** [nodejs/help#1415]
* **Node.js Version**: v10.8.0
* **OS**: Ubuntu / Linux 4.8.0-59-generic 
* **Scope (install, code, runtime, meta, other?)**: Build from source as static library

Hi everyone I'm trying to build Node.js as a stand alone static library. For now I followed this steps

```
> ./configure --fully-static --enable-static
> make -j4
```

I don't know if these are the right options to use on configure. What I need is a unique `libnode.a` file library to load on my C/C++ project. 
Could someone help me? Thanks

**Comment by mhdawson** [comment]
@yhwang can you help out here?

**Comment by yhwang** [comment]
You are doing right and you can use the `libnode.a` in your C/C++ project. However, you still need other static libraries when you build your final executable, like libuv, v8, icu, openssl, http_parser and etc. And you can find these static libraries under `out/deps`

**Comment by NickNaso** [comment]
@yhwang Thank you for your answer I just missed to import the other static libraries.
