### ISSUE TITLE
Not getting correct time

### ISSUE THREAD

**Issue by vaibhavkumar049** [nodejs/help#1416]
* **Node.js Version**: 6.2.0
* **OS**:Linux (mint)
* **Scope (install, code, runtime, meta, other?)**: 
`   conv.close("the time is "+ d.format(date,'hh:mm'));`

* **Module (and version) (if relevant)**:(date-and-time)

I am trying to run this code to get current date and time in Kolkata,India. But output of this code is wrong.

**Comment by bounc3-paradise-on-e** [comment]
What is the expected result and what did you get instead? I guess you probably want to use `HH:mm`

**Comment by gireeshpunathil** [comment]
ping @vaibhavkumar049 . Please share your code and explain what is expected and what is actual, as @bounc3-paradise-on-e asked.

**Comment by vaibhavkumar049** [comment]
I am trying to build a chatbot on action on google, I'll ask questions like what is my next class,or "tell me my class at 9:30", it'll take that value and return my class's routine, So there will be lots of comparisons and additions of time,and input of real time. This is my dummy code, 

`'use strict'

const {dialogflow}=require('actions-on-google');
const functions = require('firebase-functions');
const d=require('date-and-time');
const app=dialogflow({debug : true });
let date = new Date();


app.intent('what should',(conv,{Work})=>{
  const t=d.format(date,'hh:mm')+'05:30';
  console.log(Work);
  if(Work === 'do now'){

 if(d.format(date,'ddd')==='Mon' && (t>'09:00' && t<'09:55'){
   conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
 }
 else if (d.format(date,'ddd')==='Thu' && d.format(date,'hh:mm')==='09:00'){
   conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
 }
 else {
   conv.close("the time is "+ t " and the day is" + d.format(date,'ddd'));
   // conv.close("You should be sleeping now");

 }
}
 // else{
 //   conv.close("i could not understood");
 // }

// conv.close('good night');

});

exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);

//if (d.getDay()








// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });`

**Comment by ankur-anand** [comment]
@vaibhavkumar049 Please use markdown format for code in future for easy reading.

The same code is easier to read now :smile: 
```
'use strict'

const {dialogflow}=require('actions-on-google');
const functions = require('firebase-functions');
const d=require('date-and-time');
const app=dialogflow({debug : true });
let date = new Date();

app.intent('what should',(conv,{Work})=>{
const t=d.format(date,'hh:mm')+'05:30';
console.log(Work);
if(Work === 'do now'){

if(d.format(date,'ddd')==='Mon' && (t>'09:00' && t<'09:55'){
conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
}
else if (d.format(date,'ddd')==='Thu' && d.format(date,'hh:mm')==='09:00'){
conv.close("You have a class of Microprocessor in ICT 308 ,You can go a bit late.");
}
else {
conv.close("the time is "+ t " and the day is" + d.format(date,'ddd'));
// conv.close("You should be sleeping now");

}
}
// else{
// conv.close("i could not understood");
// }

// conv.close('good night');

});

exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);

//if (d.getDay()

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
// response.send("Hello from Firebase!");
// });
```

**Comment by gireeshpunathil** [comment]
inactive, closing
