### ISSUE TITLE
Clustering and cpu bound task

### ISSUE THREAD

**Issue by Brakkar** [nodejs/help#142]
can clustering increase performance of cpu bound task?

Lets say i throw at a node cluster on 4 cores a single operation that is a loop of 1M iterations. Will it get faster on this cluster than if it was on a single process/core ?

My guess is no, because cluster distribute the cpu bound operation to a single process ( even if 4 are available) and there is no way to split a single operation over multiple process. Am i correct?

**Comment by bnoordhuis** [comment]
Correct.  If the work is parallelizable, you can break it up and farm out the pieces to cluster workers, then merge the results afterwards.  That's a manual process, though; you have to design your program to support that.

**Comment by lordKnighton** [comment]
closing for now, happy coding :)
