### ISSUE TITLE
cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Schindar** [nodejs/help#1423]
* **Node.js Version Windows 7**:

0
down vote
favorite

It's about how to add image recognition to my bot framework. but when I try to upload an image to the bot framework, I can see only the Tagname in my terminal, and not in the Bot framework. with the following error:cannot read property '0' of undefined
this is the part of my code in which i got the error above.

` 
bot.dialog('/', function(session) {
    if(utils.hasImageAttachment(session)){
        var stream = utils.getImageStreamFromMessage(session.message); 
        customVisionService.predict(stream)
            .then(function (response) {
                // Convert buffer into string then parse the JSON string to object
                
                var jsonObj = JSON.parse(response.toString('utf8'));

                console.log(jsonObj);

                var topPrediction = jsonObj["Predictions"][0];

                // make sure we only get confidence level with 0.80 and above. But you can adjust this depending on your need
                if (topPrediction.Probability >= 0.80) {
                    session.send(`Hey, I think this image is a ${topPrediction.Tag}!`);
                } else {
                    session.send('Sorry! I don\'t know what that is :(');
                }
            }).catch(function (error) {
                console.log(error);
                session.send('Oops, there\'s something wrong with processing the image. Please try again.');
            });

    } else {
        session.send('I did not receive any image');
    }
});
`

**Comment by Schindar** [comment]
Please need help :(

**Comment by bounc3-paradise-on-e** [comment]
The error is telling you that `jsonObj["Predictions"]` is `undefined`. You can try this:

```js
bot.dialog('/', session => {
  if(utils.hasImageAttachment(session)){
    var stream = utils.getImageStreamFromMessage(session.message);

    customVisionService.predict(stream).then(response => {
      var err = () => session.send('Sorry! I don\'t know what that is :(');
      var jsonObj = JSON.parse(response.toString('utf8'));

      var predictions = jsonObj.Predictions;
      if(!(predictions && predictions.length)) return err();

      var topPrediction = predictions[0];
      if(topPrediction.Probability < .8) return err();

      session.send(`Hey, I think this image is a ${topPrediction.Tag}!`);
    }).catch(error => {
      console.log(error);
      session.send('Oops, there\'s something wrong with processing the image. Please try again.');
    });
  }else{
    session.send('I did not receive any image');
  }
});
```

If this doesn't solve your problem, can you post the full console output of your script? What is the output of `console.log(jsonObj)` from your code?

> I can see only the Tagname in my terminal, and not in the Bot framework

What do you want to say?
