### ISSUE TITLE
N-Api access TCPWrap

### ISSUE THREAD

**Issue by wilhelmmatilainen** [nodejs/help#1424]
* **Node.js Version**: 10.8.0
* **OS**: Linux 64-bit

How could I access node::TCPWrap's uv_tcp_handle_t using N-Api?

**Comment by mhdawson** [comment]
Current that is not possible.  Only a subset of libuv has been wrapped with N-API.  

We do know that means that not all modules will be able to use N-API but the goal was to hit 80% of the modules to start.  There is an ongoing discussion on this front here:  https://github.com/libuv/libuv/issues/1931

But the short answer, for now, is that if you need to use uv_tcp_handle_t then you can't do that with N-API.

**Comment by wilhelmmatilainen** [comment]
Meanwhile it is not possible using n-api, is there any non-hacky way of accessing TCPWrap?

I could not find the TCPWrap from include files installed with the node.js application, so I ended up cloning node.js repository, checking out the same version as the installed node.js and accessing the "internals" that way.

If trying to google this same problem, I am clearly not the first to ask for a solution to this problem.

The easiest and the most correct way to accomplish this would be to expose the `fd` file descriptor on TCPWrap itself. The reasoning behind not doing this was that there is no such thing in Windows. Since I am not going to ever use Windows nor target Windows with server software, It would be nice if there was at least `Socket._handle.__posix_only__.fd`.

The hacky way to retrieve the TCPWrap and uv_tcp_handle would be this: https://github.com/clshortfuse/node-getsockethandleaddress/blob/master/getSocketHandleAddress.cc

It looks like it travels throughout the memory searching for the correct structure.

Is it really better to force using hacks instead of providing the correct and easiest solution?
Another partly wrong solution would probably be providing own TCPWrap or patching each version of node.js with code exposing the needed structure.

**Comment by wilhelmmatilainen** [comment]
Alright, here is the second best solution for accessing the TCPWrap file descriptor.

```js
#include <napi.h>
#include <node.h>
#include <node_api.h>
#include <uv.h>
#include <tcp_wrap.h>
#include <v8.h>

#include "handle.h"


using namespace Napi;
using node::TCPWrap;

typedef v8::Local<v8::Value> local_value;
typedef v8::Local<v8::Object> local_object;

struct napi_env__ {
  explicit napi_env__(v8::Isolate* _isolate, uv_loop_t* _loop) : isolate(_isolate), last_error(), loop(_loop) {}
  v8::Isolate* isolate;
  node::Persistent<v8::Value> last_exception;
  napi_extended_error_info last_error;
  int open_handle_scopes = 0;
  int open_callback_scopes = 0;
  uv_loop_t* loop = nullptr;
};

static_assert(sizeof(v8::Local<v8::Value>) == sizeof(napi_value), "Cannot convert between v8::Local<v8::Value> and napi_value");

static napi_value JsValueFromV8LocalValue(v8::Local<v8::Value> local)
{
  return reinterpret_cast<napi_value>(*local);
}

static v8::Local<v8::Value> V8LocalValueFromJsValue(napi_value v)
{
  v8::Local<v8::Value> local;
  memcpy(static_cast<void*>(&local), static_cast<void*>(&v), sizeof(v));
  return local;
}

napi_value get_handle_fd(napi_env env, napi_callback_info info)
{
  size_t argc = 1;
  napi_value me;
  napi_value _handle;
  TCPWrap* tcpwrap = 0;

  if (napi_ok != napi_get_cb_info(env, info, &argc, &_handle, &me, 0))
  │ napi_throw_error(env, 0, "Unable to get function info");

  local_value value = V8LocalValueFromJsValue(_handle);
  local_object object = value.As<v8::Object>();

  tcpwrap = (TCPWrap*)object->GetAlignedPointerFromInternalField(0);
  uv_tcp_t* tcp = tcpwrap->UVHandle();
  int fd = -1;

  uv_fileno((uv_handle_t*)tcp, &fd);
  //fd = tcp->io_watcher.fd;

  return Number::New(env, fd);
}
```

**Comment by addaleax** [comment]
> Meanwhile it is not possible using n-api, is there any non-hacky way of accessing TCPWrap?

Please don’t, this is not public API. TCPWrap (both the JS class and the C++ class) is purely internal, and chances are that you will get burned by breaking changes to it.

> `Socket._handle.__posix_only__.fd`

`Socket._handle` is internal as well, so this is just not going to happen.

However, you’re right that a way to access this from JS would be ideal, and simply `Socket.fd` could work if you could describe your use case for it?

**Comment by wilhelmmatilainen** [comment]
> However, you’re right that a way to access this from JS would be ideal, and simply Socket.fd could work if you could describe your use case for it?

I am wrapping server software inside node.js module and since all the networking will be managed by node.js I need to provide the original application a correct `fd` or it will be very confused. The file descriptor is unique for a socket (client connection) and that is why it is needed. The software will be able to distinguish between different clients who is who.

**Comment by addaleax** [comment]
@wilhelmmatilainen It seems like you’re describing two different things – do you need the `fd` as an unique identifier, or as a way to pass it to some other program?

**Comment by wilhelmmatilainen** [comment]
Well, if it was a unique identifier other than the `fd`, I would then need to wrap every single networking function there is to enable the functions being called and it would probably still not work.

So, I need to pass the `fd` to my native module. The `Socket.fd` would be perfect.

**Comment by gireeshpunathil** [comment]
@wilhelmmatilainen - is this still outstanding for you?

**Comment by gireeshpunathil** [comment]
inactive, closing. please re-open if there is anything outstanding
