### ISSUE TITLE
Can we launch a node command on a mac without node installed when using electron-packager?

### ISSUE THREAD

**Issue by moki298** [nodejs/help#1428]
* **Node.js Version**: v8.11.3
* **OS**: macOS Sierra
* **Scope (install, code, runtime, meta, other?)**: 
* **Module (and version) (if relevant)**:

I have built a desktop app using electron, and packaged it using electron-packager. The app spawns a child process which uses a 'node' command. My goal is to run the app on a clean mac with no node installed. When I try to launch my app on a clean mac, I am facing "/bin/bash: node not found" error. The electron community said that packaged app does have node bundled into it and it's all about passing right env variables to the child process.

I have been trying to do this and facing various issues, the electron community suggested me to use fork method and when I use 'fork' the child process exits immedately with exit code 1, which as per some documentation is due to some uncaughtexception. So if I am going to use fork I need a way to catch that error. When I use exec method I got stdout.on('data'..) to catch it, Is there similar thing for fork? 

Or if I use exec or spawn methods I still get the "node not found" error. So how can I pass proper environment for the child process to run the node command? I should be able to use the node bundled inside packaged app, rather than the node from the mac. Any help is very much appreciated. Thanks.

Something to note, I am using 'fixpath()' to set the $PATH on macOS when run from a GUI app. Not sure if this is messing up something in my code. https://www.npmjs.com/package/fix-path

Please find my code below:

```js
'use strict'
 const fixPath = require('fix-path');

 let func = () => {
   fixPath();   
   const child = childProcess.exec('node /src/index.js --someFlags', {
     detached: true, 
     stdio: 'ignore',
     env: {
       ELECTRON_RUN_AS_NODE: 1,
     }
 });
 child.on('error', (err) => {
   console.log("\n\t\tERROR: spawn failed! (" + err + ")");
 });

 child.stderr.on('data', function(data) {
   console.log('stdout: ' +data);
 });

 child.on('exit', (code, signal) => {
   console.log(code);
   console.log(signal);
 });

 child.unref();
 }

```

**Comment by richardlau** [comment]
The node bundled in the app should be the value of [`process.execPath`](https://nodejs.org/dist/latest-v10.x/docs/api/process.html#process_process_execpath) -- try using that?

**Comment by MarshallOfSound** [comment]
@moki298 If you use `fork` or spawn with `ELECTRON_RUN_AS_NODE` make sure you spawn the main executable not the helper app.  `XXXXX Helper.app` does not contain node, you need to launch your main apps executable.

If you use `fork` from the main process this will work as expected

**Comment by moki298** [comment]
When I use fork with the process.execPath as command the child process exits immediately with exit code 1, I need a way to catch this if I happen to use fork. Else if I use spawn with process.execPath as command after setting ELECTRON_RUN_AS_NODE, I am getting this error:

````
stdout:/Users/testpc/Desktop/appName.app/Contents/Resources/app/xxxx/node_modules/grpc/src/grpc_extension.js:57
    throw e;
    ^

Error: dlopen(/Users/testpc/Desktop/appName.app/Contents/Resources/app/xxxx/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node, 1): Symbol not found: _GENERAL_NAME_free
  Referenced from: /Users/testpc/Desktop/appName.app/Contents/Resources/app/xxxx/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node
  Expected in: flat namespace
 in /Users/testpc/Desktop/appName.app/Contents/Resources/app/xxxx/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/testpc/Desktop/appName.app/Contents/Resources/app/xxxx/node_modules/grpc/src/grpc_extension.js:32:13)
    at Object.<anonymous> (/Users/testpc/Desktop/appName.app/Contents/Resources/app/xxxx/node_modules/grpc/src/grpc_extension.js:63:3)

/Users/testpc/Desktop/appName.app/Contents/Resources/app/gui/sc.js:44 1
/Users/testpc/Desktop/appName.app/Contents/Resources/app/gui/sc.js:45 null
/Users/testpc/Desktop/appName.app/Contents/Resources/app/gui/sc.js:46 

````

When you say main process what does that mean? Does that mean main.js process of my electron app? And how can I get the path to my main apps executable? Is this the path for the executable? Because consoleLog process.execPath in my main.js file gives me this path.  

````
/Users/userName/Desktop/Proj/proj1/node_modules/electron/dist/Electron.app
````

**Comment by Trott** [comment]
@moki298 Did you find a solution to your problem?

**Comment by moki298** [comment]
Yes I did, check this link https://stackoverflow.com/questions/51730030/how-to-run-an-electron-process-as-plain-node-process/52065980#52065980
