### ISSUE TITLE
My express app takes forever to start on 10.8.0

### ISSUE THREAD

**Issue by Rc85** [nodejs/help#1433]
OS: Windows 10
Node Version: 10.8.0
NPM Version: 6.2

Whenever I start my express app in windows cmd, it takes ~15 seconds to start. I had been using node 10.7.0 since the beginning of the month and this just happened about 2 days ago. Upgraded to 10.8.0, and it's still the same

When I set variable NODE_DEBUG=cluster,net,http,fs,tls,module,timers
and then start my app I get these messages

```
MODULE 17044: looking for "F:\Projects\gongle" in ["C:\Users\roger\.node_modules","C:\Users\roger\.node_libraries","C:\Program Files\nodejs\lib\node"]
MODULE 17044: load "F:\Projects\gongle\index.js" for module "."
MODULE 17044: Module._load REQUEST express parent: .
MODULE 17044: looking for "express" in ["F:\Projects\gongle\node_modules","F:\Projects\node_modules","F:\node_modules","C:\Users\roger\.node_modules","C:\Users\roger\.node_libraries","C:\Program Files\nodejs\lib\node"]
MODULE 17044: load "F:\Projects\gongle\node_modules\express\index.js" for module "F:\Projects\gongle\node_modules\express\index.js"
...
...
...
MODULE 17044: looking for "F:\Projects\gongle\node_modules\finalhandler\node_modules\statuses\index.js\codes.json" in ["F:\Projects\gongle\node_modules\finalhandler\node_modules\statuses"]
MODULE 17044: load "F:\Projects\gongle\node_modules\finalhandler\node_modules\statuses\codes.json" for module "F:\Projects\gongle\node_modules\finalhandler\node_modules\statuses\codes.json"
MODULE 17044: Module._load REQUEST unpipe parent: F:\Projects\gongle\node_modules\finalhandler\index.js
MODULE 17044: looking for "unpipe" in ["F:\Projects\gongle\node_modules\finalhandler\node_modules","F:\Projects\gongle\node_modules","F:\Projects\node_modules","F:\node_modules","C:\Users\roger\.node_modules","C:\Users\roger\.node_libraries","C:\Program Files\nodejs\lib\node"]
MODULE 17044: load "F:\Projects\gongle\node_modules\unpipe\index.js" for module "F:\Projects\gongle\node_modules\unpipe\index.js"
```

This goes for hundreds of lines, which I suspect is what is taking up the ~15 sec to start. What is happening here? Also worth mentioning is, whenever I started my app and go to http://localhost, my app also takes ~15 sec to come up on the browser. After the initial load, it's all good again. But it does that every time I restart my app on command line.

I've tried moving my project to a different directory, suspecting that my current drive is dying or something. But the same thing happens, it's looking for packages in those 7 paths (the bold line) for each package.

Then, I went to my laptop that also have node and pulled from my project repo. Did the same set command in CLI and started my node app and it started up in less than a second. The debug message on my laptop reads exactly this.

`NET 30772 ...`

for 3 lines. My laptop is using Node 10.3.0 and npm 6.0.1.

UDPATE - Downgraded to node 10.6.0 and it's fixed. Is anyone using 10.8.0 not having this issue in a development environment?

**Comment by gireeshpunathil** [comment]
just to clarify: are you saying that:
with and without `NODE_DEBUG=cluster,net,http,fs,tls,module,timers` there is a huge performance difference,
or
with `NODE_DEBUG=cluster,net,http,fs,tls,module,timers` there is a huge performance difference between two versions of node?

if first one is the case that is expected, as the option is a debug option which is going to run additional code inside.

If second is the case it is something worth investigating. But before I put some effort on it, let me know which one is the case. thanks!

**Comment by Rc85** [comment]
When I was running 10.7.0 for about a month, it was fun but suddenly, starting my app took longer than usual. I didn't debug 10.7.0, instead I upgraded to 10.8.0 and it was still taking a long time. So I set NODE_DEBUG and started my app, and got all those lines in my original post.

I opened my laptop, which has 10.3.0 installed and ran NODE_DEBUG, only 3 lines and my app, same one on my laptop as I have pushed to github and pulled on my laptop. App started less than a second.

Downgraded to 10.6.0 on my desktop, app started less than a second, and NODE_DEBUG only showed the 3 lines that showed on my laptop.

Regardless whether NODE_DEBUG is set or not, node 10.8.0 was still running a scan, looking and loading modules from multiple paths.

**Comment by gireeshpunathil** [comment]
ok, so let us do some performance analysis:

run:
$node --prof <app>  // creates a `isolate-xxxx.log` file
and then post-process the log with:
$ node --prof-process isolate-xxxx.log // to produce human readable performance metrics.
please upload the same.

re: NODE_DEBUG: this is normal, we are debugging the Node's internals, with additional verbose messages printed onto the console. Those modules are always searched and / or loaded, only becomes logged if you enable the flag.

Hope this helps.

**Comment by gireeshpunathil** [comment]
ping @Rc85

**Comment by gireeshpunathil** [comment]
inactive, closing
