### ISSUE TITLE
[nodejs/node] (node 122684) Unhandled Promise Rejection Warning: Range Error

### ISSUE THREAD

**Issue by Zainab-hasina** [nodejs/help#1434]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

```trace
[nodejs/node] (node 122684) Unhandled Promise Rejection Warning: Range Error: Invalid String length
at Json.Stringify (<anonymous>) 
at Instance. Page. getresourceTree.then(path of index.js in my desktop) 
at <anonymous> (node 122684) Unhandled Promise Rejection Warning : Unhandled Promise Rejection. This error originated either by throwing inside of an async function with a .catch(). (rejection id:1)
 (node 122684) [DEP0018] Deprecation Warning: Unhandled Promise Rejections are depricated. In the future, promise rejections that are not handled will terminate the node.js process with a non-zero exit code 
```

Edited both title and description for more redability

**Comment by ankur-anand** [comment]
@Zainab-hasina What is the SIZE of STRING Object that you're passing to `JSON.stringify()` method?

**Comment by vsemozhetbyt** [comment]
For what it worth, as for string length limits, see https://github.com/nodejs/node/issues/9489 with comments.

**Comment by Zainab-hasina** [comment]
Hi Ankur,

The string object that I am passing to JSON.stringify() object is a
response from a website. The response is obtained by crawling for
dependencies using z-browse. So I cannot specify the size, sorry about
that. But I can give you certain URLs that on crawling, gave the warning
and they are as follows:
www.bitauto.com , www.3dmgame.com , www.momoshop.com.tw ,  www.banvenez.com
, https://www.ndtv.com.

Thanks and regards,

Hasina.

**Comment by Hakerh400** [comment]
> Unhandled Promise Rejections are **depricated**

How did you copy the error message?

**Comment by Zainab-hasina** [comment]
Thanks

Kind regards,

Hasina

**Comment by ankur-anand** [comment]
@Zainab-hasina Note that if the STRING Object becomes too large it will throw `Range Error: Invalid String length` too. Are you downloading the content at once and then passing it to stringfy function ?. If so split it in small chuck and check

**Comment by Zainab-hasina** [comment]
@ankur-anand No I am not downloading it but just passing it to Stringify function. Can you suggest something to solve that. Thanks

**Comment by Trott** [comment]
@Zainab-hasina Did you eventually find a workaround or solution?

**Comment by gireeshpunathil** [comment]
inactive, closing
