### ISSUE TITLE
udp client.on is called multiple times eventhough server sends a single response

### ISSUE THREAD

**Issue by malasgowda** [nodejs/help#1436]
* **Node.js Version**:v6.9.5
* **OS**: CentOS Linux release 7.0.1406 (Core)
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: udp

**Comment by ankur-anand** [comment]
@malasgowda Kindly Share your code!

**Comment by malasgowda** [comment]
Hi ,
The code is as shown below


var radius = require('radius');
var dgram = require('dgram');

var server = dgram.createSocket('udp4');
var client = dgram.createSocket('udp4');


var PORT = 6789;
var HOST = '172.16.23.27';

var radiusIp = '172.16.23.27';
var radiusPort = 1812;

var user_name = 'test';
var password = "test";
var FramedIpaddress = '';
var secret = 'secret';

var rad_cnt=1;
var rad_recv=1;
var recv=1;
var cnt=1;

server.bind(PORT,HOST);

server.on('listening', function (err,res) {
        var address = server.address();
        if (err){
                console.log('UDP Server listening on ' + address.address +
":" + address.port);
        } else {
                console.log('UDP Server listening on ' + address.address +
":" + address.port);
        }
});

//receive data from WBG
var response = "test message";
server.on('message', function (message, remote) {
        console.log('WBG request received '+ new Date()+ ':' + recv);
        var clientport=remote.port;
        var clientip=remote.address;
        recv++;
        FramedIpaddress = "182.23.4.5";
        var packet = radius.encode({
                code: "Access-Request",
                secret: secret,
                attributes: [
                        ['User-Name', user_name],
                        ['User-Password', password],
                        ['Framed-IP-Address', FramedIpaddress]
                ]
        });
        //send data over radius
        client.send(packet, 0, packet.length, radiusPort ,radiusIp,
function (err, bytes) {
                if (err) {
                        console.log('Error sending response to ', radiusIp);
                }else {
                        console.log('Radius request sent:'+ new
Date()+':'+rad_cnt);
                        rad_cnt++
                }
        });
});
        //receive response over radius
        client.on('message', function (radiusmessage, radiusServerDetls) {
                console.log('Radius Response received:'+new Date()
+':'+radiusServerDetls.address +':'+ radiusServerDetls.port+':'+ rad_recv);
                rad_recv++;
                var decoded = radius.decode_without_secret({ packet:
radiusmessage });
                //console.log (JSON.stringify(decoded));
                response = "test message";
                //server.send(response, 0, response.length, remote.port,
remote.address, function (wbg_send_err, bytes) {
                server.send(response, 0, response.length, '8787',
'172.16.23.27', function (wbg_send_err, bytes) {
                        if (wbg_send_err) {
                                console.log('Error while sending response
to WBG'+remote.address + ':' + remote.port + ' - ' + response);
                                console.log('Error:'+wbg_send_err);
                        } else {
                                console.log('WBG response sent: '+ new
Date() +':'+cnt);
                                cnt++;
                        }
                });
        });

**Comment by Trott** [comment]
@malasgowda Did you ever figure this out?

@nodejs/dgram

**Comment by malasgowda** [comment]
Not exactly but made few changes and wrote Client send message outside the
server and hard coded the recipient IP instead of taking it from the request

**Comment by Trott** [comment]
OK, I'm going to close this out as it's been inactive for a while and it sounds like you have a workaround. By all means, if you think this warrants further attention, comment or re-open. Thanks!
