### ISSUE TITLE
Simple question on connecting through socks...

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1438]
Hi all,

I am following the example code but cant seem to get the HTML back when requesting through this module (want to get the body of a website that uses https... https://github.com/TooTallNate/node-https-proxy-agent

I get a ERRCONREFUSED error :(

I am getting SOCKS proxy IP addresses to connect through from this website: https://hidemyna.me/en/proxy-list/?type=45&anon=34#list

// var url = require('url');
// var https = require('https');
var SocksProxyAgent = require('socks-proxy-agent');

// SOCKS proxy to connect to
var proxy = process.env.socks_proxy || 'socks://177.223.106.232';
console.log('using proxy server %j', proxy);

// HTTP endpoint for the proxy to connect to
var endpoint = process.argv[2] || 'https://geenstijl.nl';
console.log('attempting to GET %j', endpoint);
var opts = url.parse(endpoint);

// create an instance of the `SocksProxyAgent` class with the proxy server information
// NOTE: the `true` second argument! Means to use TLS encryption on the socket
var agent = new SocksProxyAgent(proxy, true);
opts.agent = agent;

https.get(opts, function (res) {
  console.log('"response" event!', res.headers);
  res.pipe(process.stdout);
});

**Comment by gireeshpunathil** [comment]
I tried your example and got `ERRCONREFUSED` but when tried with the latest code in the example, it goes through. Can you try? looks like the code is modified in their website.
