### ISSUE TITLE
Dynamic linking of OpenSSL with node.js in Windows

### ISSUE THREAD

**Issue by Elavarasan83** [nodejs/help#144]
Can any one share the steps for dynamically linking OpenSSL with node.js?
I'm using node.js version 4.4.3.

**Comment by bnoordhuis** [comment]
Can you clarify whether you mean:

1. Linking an add-on dynamically to the copy of OpenSSL that's built into node.js, or
2. Linking the node.js binary dynamically to an OpenSSL DLL?

**Comment by Elavarasan83** [comment]
Thanks for the response. I mean linking OpenSSL DLL dynamically to node.js binary.

**Comment by bnoordhuis** [comment]
There's no support for that on Windows currently, you'd have to hack the build system.  Even if it was supported, you wouldn't be able to drop in a random openssl.dll if that was what you were hoping for, it would have to be v1.0.2.
