### ISSUE TITLE
Continuous calls to /json/version at runtime

### ISSUE THREAD

**Issue by nishant-dani** [nodejs/help#1444]
* **Node.js Version**: v8.9.4
* **OS**: macOS High Sierra, 10.3.5
* **Scope (install, code, runtime, meta, other?)**: runtime

I am using nodejs and recently when I turned on printing of all http requests, I now notice that one call keeps recurring.  The URL is "json/version".  I am using the node server in a docker and the call appears to be originating from the docker gateway ip.  
Sat, 18 Aug 2018 17:14:43 GMT express:router serveStatic  : /json
Sat, 18 Aug 2018 17:14:43 GMT express:router corsMiddleware  : /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router <anonymous>  : /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router jsonParser  : /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router printreq  : /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router session  : /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router initialize  : /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router authenticate  : /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router router  : /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router dispatching GET /json/version
Sat, 18 Aug 2018 17:14:43 GMT express:router corsMiddleware  : /json
Sat, 18 Aug 2018 17:14:43 GMT express:router <anonymous>  : /json
Sat, 18 Aug 2018 17:14:43 GMT express:router jsonParser  : /json
Sat, 18 Aug 2018 17:14:43 GMT express:router printreq  : /json
Sat, 18 Aug 2018 17:14:43 GMT express:router session  : /json
Sat, 18 Aug 2018 17:14:43 GMT express:router initialize  : /json
server.js: remoteAddress : "172.18.0.1"
server.js: method        : "GET"
server.js: url           : "/json/version"
I looked over github and it seems that the the GetVersionResponse is part of the inspector_socket_server.  https://github.com/nodejs/node/blob/master/src/inspector_socket_server.cc.  However, this call happens even when I am not using --inspect on the command line.  I don't like unnecessary computation happening on the servers, particularly when it might be a symptom for something more serious.  I would like to track however who might be calling this and why is it called continuously. 
It appears from the documentation for the inspector protocol that /json/version might be used by the inspector to talk to nodejs.

**Comment by gireeshpunathil** [comment]
Looks like this logic is removed in the latest. ping @nodejs/v8-inspector to get a better guidance.

**Comment by gireeshpunathil** [comment]
@nishant-dani - sorry, I didn't mean to require you to ping them, instead ping them myself. Let me try to figure out what is happening.

**Comment by elipalmer** [comment]
Hello, any news on this issue?

**Comment by JoeTavarez** [comment]
Experiencing issue as well. I need to investigate if this is only occurring during debugging. Any updates?

**Comment by gireeshpunathil** [comment]
the call to `/json/version` route indicates that there is a debugger lingering somewhere that periodically does the health-check. If you cannot determine who it is, a TCP trace will help; or else a reboot.

**Comment by mewc** [comment]
Im in this issue today.

**Comment by bkitaec** [comment]
+1

**Comment by gireeshpunathil** [comment]
can you do:
 - `netstat -ntpl | grep 9229` and
 - `netstat -na | grep 9229`  and provide the output?

**Comment by imsunhao** [comment]
+1

**Comment by PoojaDurgad** [comment]
@nishant-dani , is this issue resolved? did **@msunhao** 's suggestion above help you in getting rid of the issue?

**Comment by gireeshpunathil** [comment]
inactive, and / or resolved, closing. pls feel free to reopen if required
