### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by mhartshorne** [nodejs/help#1446]
* **Node.js Version**:10.9.0
* **OS**:Windows 10
* **Scope (install, code, runtime, meta, other?)**:code and other
* **Module (and version) (if relevant)**:

When i got to put in my command for my discord bot to lead it up and i do npm --harmony . or npm ro any of those nothing works it just gives me the help screen over and over and over

<img width="960" alt="desktop screenshot 2018 08 19 - 13 01 54 69" src="https://user-images.githubusercontent.com/42520545/44311782-b3780800-a3bb-11e8-8ccf-200be17ba5df.png">

<sub>_(edited by @vsemozhetbyt: remove comment markup)_</sub>

**Comment by vsemozhetbyt** [comment]
What is the issue you need help with?

**Comment by vsemozhetbyt** [comment]
Thank you, @Hakerh400. Comment markup removed.

**Comment by tniessen** [comment]
I don't see the issue in your screenshot. If you need help using npm or if you believe that there is a bug in npm, please contact npm directly via [npm.community](https://npm.community/). The package manager is not maintained by the nodejs organization.
