### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by naungmon** [nodejs/help#1447]
/usr/bin/nodejs: symbol lookup error: /usr/bin/nodejs: undefined symbol: uv_os_getpid

**Comment by ORESoftware** [comment]
nodejs version would help, platform would help too

**Comment by gireeshpunathil** [comment]
which distribution of Node.js you are using? I strongly doubt it is one which uses a custom libuv. Please provide what @ORESoftware asked as well as details on the source of download.

**Comment by gireeshpunathil** [comment]
ping @naungmon

**Comment by gireeshpunathil** [comment]
closing as inactive
