### ISSUE TITLE
Nodemailer Help

### ISSUE THREAD

**Issue by tomwilson454** [nodejs/help#1449]
Please i am trying to send emails to multiple emails using nodemailer ,i tried sending messages using an example :  Hello  %Email%               .....i was expecting the %Email% to auto grab the receiver email but it doesnt,it just shows up exactly as it is,any help on how i can set this up will be greatly appreciated.

Thanks

**Comment by Maledong** [comment]
Are you using [nodemailer](https://github.com/nodemailer/nodemailer)?

If yes, maybe you can directly to there for ask, and Node hasn't such functions directly, it should belong to a 3-rd party.

Correct me if I take you wrong.

**Comment by tomwilson454** [comment]
Thanks and yes i am using nodemailer,i just messaged there directly

**Comment by gireeshpunathil** [comment]
thanks, closing this one then, cheers.
