### ISSUE TITLE
Node.js compilation for QNX

### ISSUE THREAD

**Issue by rameshpasunoori** [nodejs/help#145]
Hello All

I want to compile node.js for QNX OS.
Document does not have any reference to cross compilation.
Please provide some document.

Thanks
Ramesh

**Comment by bnoordhuis** [comment]
QNX is not a supported platform and it's unlikely that it's going to work out of the box.  You'll have to experiment and see how far you can get.

**Comment by leesei** [comment]
QNX is a niche platform.
I think the major issue would be C++ compilation and porting of libuv.

**Comment by bnoordhuis** [comment]
I'll close the issue, seeing how the OP didn't follow up.
