### ISSUE TITLE
fs cannot read out of .asar archive

### ISSUE THREAD

**Issue by amenders** [nodejs/help#1450]
* **Node.js Version**: 8.11.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: File System

I am trying to read files out of a .asar archive using readdirSync, and am having trouble. Attempting to read out of the archive returns this error:

```
Error: ENOTDIR: not a directory, scandir 'C:\Users\xxxx\Desktop\xxxxxx\xxxxxx\dist\win-unpacked\resources\app.asar'
    at Object.fs.readdirSync (fs.js:904:18)
```
Code to reproduce:
```js
var fs = require('fs');
fs.readdirSync('C:/path/to/app.asar');
```
For context, this is the app.asar file from my electron-builder output, but I expected that ```fs``` would allow me to read the contents of the archive. I've also tried constructing the path with ```path.join(...)``` but that did not make a difference.

**Comment by amenders** [comment]
Thanks @djmangoo; 
I've saw from other posts/links that Electron packaged ```.asar``` files will be appropriately handled as directories when using ```readdirSync(...)```  (see [this post](https://github.com/electron/electron/issues/5454), or [these docs](https://electronjs.org/docs/all#using-asar-archives)). But perhaps this question would be better posed in an ```electron``` or ```electron-builder``` issue.

**Comment by djmangoo** [comment]
> I've saw from other posts/links that Electron packaged .asar files will be appropriately handled as directories

Yes, but only if you access it using electron. Standard Node.js `fs` module doesn't treat archives as directories.

**Comment by amenders** [comment]
Good to know, thanks!

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if this is still outstanding.
