### ISSUE TITLE
node-chakracore: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mfidemraizer** [nodejs/help#1453]
* **Node.js:** 10.6
* **OS**: Linux Mint 18.3
* **Scope**: install, runtime

I've installed `node-chakracore` using `nvs` and when I run `node` or `npm` I get an error with this text: `Illegal instruction (core dumped)`.

I don't know how to solve this problem. Thank you!

**Comment by shellberg** [comment]
The `Illegal instruction` error concerns the production (by the JIT) of an instruction that the processor does not recognise as valid.  That might arise if the architecture of what was downloaded does not match the real architecture of your machine (you are most likely to be on an x64).  Alternatively, it could also be a genuine defect in chakracore...!  I don't have a Linux Mint distribution image available, but I'd be surprised if you couldn't meet the minimum dependencies.
(I tested nvs downloading a chakracore v10.6 binary to a RHEL platform, and that was working for me in some very brief tests...)

The fact that you were able to use `nvs` suggests that `nvs` was able to detect your platform correctly, and has downloaded and employed a working (not chakracore) node 6 distribution; `nvs` is a combination of shell script and node application.  You might want to check under the `cache` directory of your NVS installation and ensure that all the archives present match based on their architecture (x64?), specifically the chakracore archive.

**Comment by mfidemraizer** [comment]
@shellberg hey! Thank you for your quick answer. 

My CPU is an Ahtlon II X3 450 (it's a Phenom II with 3 cores) which is 64bit. 

I've tried to install the same `node-chakracore` version on some friend Linux Mint same version (18.3) and it worked. 

So I'm afraid that it's something with my CPU!

**Comment by gireeshpunathil** [comment]
@mfidemraizer - is this still an issue for you?

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by ledlamp** [comment]
I think I have the same issue, so my CPU is not supported? What are the CPU requirements for node-chakracore? This is my cpuinfo
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 22
model name	: Intel(R) Celeron(R) CPU          420  @ 1.60GHz
stepping	: 1
microcode	: 0x43
cpu MHz		: 1596.000
cache size	: 512 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm lahf_lm pti dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
bogomips	: 3192.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

```

**Comment by joaocgreis** [comment]
cc @nodejs/node-chakracore
