### ISSUE TITLE
Pulling the data from a function to a div or other HTML element 

### ISSUE THREAD

**Issue by phantompepper** [nodejs/help#1454]
* **8.2.1**:
* **Win32 - 10**:
* **Running Electron-Vue with ssh2 package**:

Hi, I have a pretty simple idea that I've been racking my head on - I am trying to get the "data" from the example on executing a shell command and putting that into an html element. It works great in the console, but I cant seem to see the obvious route. I am specifically testing this out in en Electron-Vue app and so far, all examples have worked great. I'm just trying to get the data to display in the DOM instead of the console.

Specifically the STDOUT bit where I have succesfully executed 'ls' on my remote machine that I am connecting to. I just want to display the results of 'ls' on the webpage. I know my inexperience with Javascript is showing here - but I'd really appreciate any help with this!

Here is an example from my code that I am referring to "data":
```js
conn.on("ready", function() {
console.log("Client :: ready");

      conn.exec("ls", function(err, stream) {
        if (err) throw err;
        stream
          .on("close", function(code, signal) {
            console.log(
              "Stream :: close :: code: " + code + ", signal: " + signal
            );
            conn.end();
          })
          .on("data", function(data) {
            
            console.log("STDOUT: " + data);
          })
          .stderr.on("data", function(data) {
            console.log("STDERR: " + data);
          })
      })
    })
```
-->

**Comment by phantompepper** [comment]
Figured this out

**Comment by Rleit** [comment]
> 
> 
> Figured this out

What was the fix ?
