### ISSUE TITLE
nodeJS restart over cronjob, cPanel

### ISSUE THREAD

**Issue by NesooseN** [nodejs/help#1455]
* **Node.js Version**: v6.9.1
* **OS**: CentOS 7.5
* **Scope (install, code, runtime, meta, other?)**: start of app over cronjob, cpanel, script sh
* **cPanel

Hi, I am trying to set simple script that will execute over cronjob and start app if it is not working, in case server is down, process etc.

When I execute pm2 start app.js it all work OK

but when I execute bellow code over cronjob, it start app but say error, and app do not have ID: https://s22.postimg.cc/k54rw4v0h/20180515_213806.jpg

I presume my file is wrong, but I am not expert, any help would be great

`#!/bin/bash
/home/preppers/bin/node /home/preppers/bin/pm2 start /home/preppers/public_html/lib/MooNodeJsServer/mooServer.js`

**Comment by gireeshpunathil** [comment]
I guess this question may be better addressed in https://github.com/Unitech/pm2/ site than here. Can you please try?

**Comment by gireeshpunathil** [comment]
closing; suggested to raise it with pm2, based on the error message.
