### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DinmaOtutu** [nodejs/help#1456]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

ISSUE:

class Drone {

constructor(id, name) {

this.id = id;
this.name = name;
}

}

let drone = new Drone(A1223, flyer);

console.log('drone :' + drone.id +' ' + drone.name);

I keep getting this error "VM55:1 Uncaught SyntaxError: Identifier 'Drone' has already been declared
at :1:1"

please, can someone tell me why?

**Comment by addaleax** [comment]
Can you post a full example script, and maybe tell us how you are running this code?

**Comment by DinmaOtutu** [comment]
Just trying it out on the console in my browser, my first trial.

**Comment by DinmaOtutu** [comment]
Thanks, @addaleax I have been able to figure out the problem.

**Comment by gdams** [comment]
@DinmaOtutu can this be closed now?

**Comment by DinmaOtutu** [comment]
Yes please, thanks.
