### ISSUE TITLE
Can't send array via POST

### ISSUE THREAD

**Issue by Slowner** [nodejs/help#146]
* **Version**: v5.10.1
* **Platform**: Ubuntu x64
* **Subsystem**: HTTPS

Hello.
I have to send to server (via HTTPS) POST message with JSON like
``` data : [
  {
    dataLvl1 : value
  },
  {
    dataLvl1 : value
  }
]```

I tried to do it with Content-Type = "application/x-www-form-urlencoded", and Content-Type "application/json"
First contentType can't make string from my array (it sends "data=", that's all)
Second contentType sends no POST data.

Node.js 
```
    var postData = JSON.stringify(data);

    var options = {
	protocol: 'https:',
	hostname: 'localhost',
	port: 443,
	path: '/message.php',
	method: 'POST',
	headers: {
            'Content-Type': 'application/json'
	},
    };

    var req = https.request(options, function (res) {
	res.setEncoding('utf8');
	res.on('data', function (chunk) {
	    console.log('BODY: ' + chunk);
	});
	res.on('end', function () {
	    console.log('No more data in response.');
	});
    });

    req.on('error', function (e) {
	console.log("Got error: " + e.message);
    });

    // write the data
    req.end(postData);
```

**Comment by lordKnighton** [comment]
closing for now, if your still in need of help, reopen and we will go from there.

**Comment by DIMITA** [comment]
Hello i have the same problem
