### ISSUE TITLE
Upgrade to NodeJS 8.X from 7.X fails Mocha Tests

### ISSUE THREAD

**Issue by Batman-woman** [nodejs/help#1460]
* **Node.js Version**: 8.11
* **OS**: Windows 
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Trying to upgrade node js version from lower to 8.x and all mocha tests fail.

Uncaught AssertionError: expected [Error: Unauthorized] to equal null

There is a test that directly calls the /authenticate method and previously working test now fails on 8.x by saying the whole object is unauthorized instead of simple error sub object being null

**Comment by gireeshpunathil** [comment]
simple steps to recreate with a sample code please?

**Comment by gireeshpunathil** [comment]
ping @Batman-woman

**Comment by mhdawson** [comment]
@boneskull FYI as well.

**Comment by Batman-woman** [comment]
I found the solution for this, surprisingly all you have to do is update the nock librabry version in package.json to 9.0.14 and voila! all 116 tests passed.

 "nock": "^9.0.14" --- works for both 8.x, 10.x

Thanks all for trying to help!
