### ISSUE TITLE
how to match with two strings with or with out spacing in mongodb & js

### ISSUE THREAD

**Issue by susmitha01** [nodejs/help#1465]
> I have a database field which is "computer mobiles" and i'm passing the string as "computermobiles"

`var data = "computermobiles";
db.getCollection('users').aggregate([ { $match : { firstName : data } } ]);`

But i'm not getting the result as i expected

HELP ME WITH THIS.
Thanks in advance

**Comment by djmangoo** [comment]
1. What are the expected and actual behaviors?
2. Why don't you pass the string with spaces included?
3. Does [this](https://stackoverflow.com/questions/27861704) resolve your problem?

**Comment by susmitha01** [comment]
In front-end the value is represented as like this  "computermobiles" and in database the value is storing as "computer mobiles "

**Comment by djmangoo** [comment]
Can you take a bit of time and answer the questions I asked you? What are the expected and actual behaviors? Why don't you use the same field name in front-end and in the database? Does [this](https://stackoverflow.com/questions/27861704) resolve your problem?

Also, what is your MongoDB version? The `getCollection` method is deprecated in 3.0, and it doesn't even exist in the latest version, as the property of the `db` object. Can you post a bit more code?

If I understand your issue correctly, your database field name contains spaces, while you have a string without spaces. In that case, you can get all field names and find the one that, with spaces removed, matches your string. I don't think there is another way.

**Comment by gireeshpunathil** [comment]
ping @susmitha01
