### ISSUE TITLE
Browser keeps showing busy spinner after api data loads

### ISSUE THREAD

**Issue by linguaphile** [nodejs/help#1466]
* **Node.js Version**: 8.9.4
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: code or runtime
* **Module (and version) (if relevant)**: express 4.16.3 MySQL

This simple api connects to sql server and returns a short chunk of Jason. It works but leaves a browser with a still loading cursor. This may not be important since I want to use the api in an ios app anyway but I wonder if I am sending the response incorrectly.

**Comment by gireeshpunathil** [comment]
are you ending the response in all the possible control flow paths? using a console.log to verify this would be the first thing to.

**Comment by linguaphile** [comment]
Gireesh, Thanks for responding. Here is a portion of my code:
const express = require("express");
const app = express();
const sql = require("mssql");
const db = require("./core/db");


app.get("/", (req, res) => {
    console.log("responding to root route");
    res.send("Hello from Root!");
    res.end;
});

app.get("/id", (req, res) => {

    console.log(`You passed in labelID: ${req.param('labID')}`);

    const myQuery = "SELECT tbl_wms_RSFeed2.ObjectID,
tbl_wms_rsFeed2.ObjectName, tbl_wms_rsFeed2.Creators, \
    tbl_wms_rsFeed2.Medium, tbl_wms_rsFeed2.Titles, BCLabels.LabelUUID \
    FROM           tbl_wms_rsFeed2 INNER JOIN BCLabels ON
tbl_wms_rsFeed2.ObjectID = BCLabels.ID \
    WHERE      ( BCLabels.LabelUUID = '"

    db.executeSql(myQuery + req.param('labID') + "')",  (data, err) => {


        if(err){
            res.writeHead(500, "internal error occurred",{"Content-Type":
"text/html"});
            res.write("<html><head><titile>500</title></head><body>500:
Internal Error. Details: " + err + "</body></html>");
            res.end;
        }
        else {
            res.writeHead(200, {"Content-Type": "application/json"});
            res.write(JSON.stringify(data));
            res.end;
        }
        res.end;
    });
});


app.listen(3003, () => {
    console.log("server is up and listening on port 3003...");
});

I have added redundant res.ends and still no luck. If I write to the log,
what would I be writing?

Jim Allison

**Comment by gireeshpunathil** [comment]
thanks for sharing the code. Please replace all
`res.end;` instances
with 
`res.end();`

reason is that when you code the former, it just evaluates to the name of the function, but does not invoke it. when you code the later, it invokes the method. Most languages follow that semantics - i.e., if you use `()` with a function call it, use the name of the function, just refer it.

Hope this helps.

**Comment by linguaphile** [comment]
Many thanks that worked.

**Comment by gireeshpunathil** [comment]
closing then!
