### ISSUE TITLE
how to use npm when node is built from sources

### ISSUE THREAD

**Issue by mperdikeas** [nodejs/help#1467]
* **Node.js Version**: 8.11.4
* **OS**: Ubuntu 16.04
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

I build Node (8.11.4) from sources (downloaded from https://nodejs.org/en/download/).

In my particular setup I cannot install `node` or `npm` in some system location (e.g. `/usr/bin`) and I may only add the location where they are built in the `$PATH` (to override the older, system versions that are in `/usr/bin` and that I am not supposed to be using or tamper with).

In the case of `node`, following the successful build, it is available in `node-v8.11.4/out/Release` so that's straightforward.

What's not clear to me is how (and where from) I should be using `npm`. In the end, I `cd` in `node-v8.11.4/out/Release` and created a symlink to the file `npm-cli.js`:

    ln -s ../../deps/npm/bin/npm-cli.js npm

Given that the `node-v8.11.4/out/Release` location is now in my `$PATH` I now get both `node` and `npm` from that location. Is this the right way to use `npm` from the sources?

**Comment by richardlau** [comment]
You should be able to run the makefile's `install` target specifying `PREFIX`. The actual logic is in [`tools/install.py`](https://github.com/nodejs/node/blob/v8.11.4/tools/install.py) which will take care of creating the expected `npm` symlinks (alongside the `node` executable).

https://github.com/nodejs/node/blob/0cae3c3fe5e3f4c275701446a4baf1f2727344f6/Makefile#L104-L105

**Comment by gireeshpunathil** [comment]
close-able?

**Comment by gireeshpunathil** [comment]
question answered, closing
