### ISSUE TITLE
pkg install error report

### ISSUE THREAD

**Issue by kazusake2414** [nodejs/help#1468]
* **Node.js Version**: 9.11.1
* **OS**: Android 8.0
* **Scope (install, code, runtime, meta, other?)**: unknown
* **Module (and version) (if relevant)**: unknown

I would like to install packages with Teamux.[](url)
![smartselect_20180901-170742_termux](https://user-images.githubusercontent.com/24887515/44943979-b850a900-ae0a-11e8-9322-9ad910a46e16.jpg)

**Comment by gdams** [comment]
can you upload the debug log please?

**Comment by kazusake2414** [comment]
Ok

0 info it worked if it ends with ok
1 verbose cli [ '/data/data/com.termux/files/usr/bin/node',
1 verbose cli   '/data/data/com.termux/files/usr/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose npm-session c715d92a589b9e31
5 verbose stack TypeError: Cannot read property 'length' of undefined
5 verbose stack     at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:5:61)
5 verbose stack     at Module._compile (internal/modules/cjs/loader.js:654:30)
5 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
5 verbose stack     at Module.load (internal/modules/cjs/loader.js:566:32)
5 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
5 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
5 verbose stack     at Module.require (internal/modules/cjs/loader.js:598:17)
5 verbose stack     at require (internal/modules/cjs/helpers.js:11:18)
5 verbose stack     at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/index.js:3:14)
5 verbose stack     at Module._compile (internal/modules/cjs/loader.js:654:30)
5 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
5 verbose stack     at Module.load (internal/modules/cjs/loader.js:566:32)
5 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
5 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
5 verbose stack     at Module.require (internal/modules/cjs/loader.js:598:17)
5 verbose stack     at require (internal/modules/cjs/helpers.js:11:18)
6 verbose cwd /data/data/com.termux/files/home
7 verbose Linux 4.9.65-14119563
8 verbose argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "i" "-g"
9 verbose node v9.11.1
10 verbose npm  v5.6.0
11 error Cannot read property 'length' of undefined
12 verbose exit [ 1, true ]

**Comment by yathamravali** [comment]
@kazusake2414 
Cannot read property of 'length' undefined. This might occurred because Teamux package has internal dependencies with worker-farm package which is **old** i.e. `require('os').cpus().length` is returning undefined due to cpu's work load.

node-worker-farm/blob/master/lib/farm.js is committed 11 months ago with maxConcurrentWorkers  changed to `(require('os').cpus() || { length: 1 }).length` which returns no of CPUs available on the current system, but it can be any reasonable number, including `1` .

cc @rvagg

**Comment by gireeshpunathil** [comment]
ping @kazusake2414

**Comment by gireeshpunathil** [comment]
inactive, closing
