### ISSUE TITLE
I have just installed Node.js and can`t install any packeges

### ISSUE THREAD

**Issue by pokermanx** [nodejs/help#1469]
I am new to node.js. I am just starting to learn angular and I tried to `npm install` and got this
`npm ERR! request to https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"`
I tried` npm config set strict-ssl false `and npm config set `registry https://registry.npmjs.org/`, neither worked for me.
I tried to download certificate file and manually set path - no result.
node -v: v8.11.4
npm -v: 5.6.0

**Comment by vsemozhetbyt** [comment]
See the last issues in https://npm.community/c/bugs

**Comment by yathamravali** [comment]
@pokermanx Did the issue resolved?
Are you able to install the packages.

**Comment by gireeshpunathil** [comment]
inactive, closing
