### ISSUE TITLE
node-user online/offline issue

### ISSUE THREAD

**Issue by erravi62** [nodejs/help#147]
Hi there,
I'm new to nodejs.I'm trying to integrate real time chat functionality using nodejs,mysql and php.I'm not able to track the bug described as under:
Now what I'm doing that when a new user is connected and logs in to our website,I'm storing the unique USERID in an array, but the moment he leaves the website or close the browser, he is disconnected by splicing out the particular USERID from that array.But the problem arises when the user opens multiple tabs in a browser and closes only single tab, He is displayed as 'offline' which is not true as he is already online.
Here is my code:
io.sockets.on('connection', function(socket){
	socket.on('little_newbie', function(userid,username) {
        socket.userid = userid;
        socket.username = username;
		 if( clients.indexOf( userid ) === -1 )
		 {
			clients.push(userid); 
		 }
		io.sockets.emit('notification', {name:socket.username,message:' is online',socketCount:clients.length});
    });
 socket.on('disconnect', function(data) {
		var index = clients.indexOf( socket.userid );
		if( index !== -1 )
		{
        clients.splice( index, 1 ); 
		}
		io.sockets.emit('notification', {name:socket.username,message:' is offline',socketCount:clients.length});
		
    });
});

Is there any better way? Please suggest!

**Comment by addaleax** [comment]
You could move the “… is offline” bit into the `if( index !== -1 ) { … }` block, I think?

And by the way, you can wrap pieces of source code that you post on github in  ```` ``` ```` so that it becomes more readable, for example:

    ```js
    console.log('Hello world!');
    ```

becomes

```js
console.log('Hello world!');
```

:smile:

**Comment by erravi62** [comment]
Firstly, Thanks for your recommendation.
Well, still I cannot find an optimum solution.
Can you guide me a better logic to track real time online/offline users onto my website.
Thank You

**Comment by lordKnighton** [comment]
Yo @erravi62  closing for now.  But if you still need help, reopen issue  to continue conversation 

 😸 happy coding

**Comment by WisdomProductionz** [comment]
Hi, sorry for re opening this thread but i'm having a similar problem and wondered if someone could help me as it has been racking my brain for the last two days. 

```socket.emit('online',{user_id: data.id});``` works fine by sending the user_id to the client and then saved in the database but ```socket.emit('offline', {user_id:socket.userid});``` doesn't work at all which is baffling me.

Here is my code

```
socket.on('join', function(data){
        if (data !== null)
        {
            socket.userid = data.id;
            socket.join(data.id);
            if(clients.indexOf( data.id ) === -1)
            {
                clients.push(data.id);
            }
            socket.emit('online',{user_id: data.id});
            console.log('user: ' + data.id + ' has come online');
        }
    });

socket.on('disconnect', function() {
        var index = clients.indexOf( socket.userid );
        if( index !== -1 )
        {
            clients.splice( index, 1 );
            socket.emit('offline', {user_id:socket.userid});
            console.log('User: ' + socket.userid + ' disconnected.');
        }
    });
```

I'm thinking it could have something to do with you cant call ```socket.emit();``` in the disconnect method.
Please any help would be greatly appreciated!
