### ISSUE TITLE
Is openssl engine thread-safe?

### ISSUE THREAD

**Issue by matianfu** [nodejs/help#1470]
* **Node.js Version**: 10.x
* **OS**: linux
* **Scope**: other
* **Module**: n/a

We are planning to use microchip/atmel ecc chip for hardware-based TLS. An openssl engine will be ported from microchip official (beta) code. We have checked the code. Essentially it is a shared library providing a bunch of functions to be called by openssl code. But different from a pure software implementation, there is only one crypto processor/accelerator.

Since node.js has statically-linked openssl, we want to know if there are some thread-safety problem. That is, will node.js guarantee the engine function will be called sequentially, or it is possible that they are called concurrently, so the engine must serialize the operation one after another on its own?

**Comment by gireeshpunathil** [comment]
with worker in, Node.js is no more single threaded, so I guess crypto APIs could be entered concurrently
/cc @addaleax @bnoordhuis

**Comment by addaleax** [comment]
Yes, as I understand it, there should be no thread safety issues inherent to using OpenSSL.

**Comment by gireeshpunathil** [comment]
closing as answered, if you have follow up questions please let me know
