### ISSUE TITLE
how to include js file in c style

### ISSUE THREAD

**Issue by maxzhou0** [nodejs/help#1472]
* **Node.js Version**:10.8.0
* **OS**:win7 64bit
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

i got a js file declared many structs and variables , i dont want to use export and require, i need an option .i want to use plain include file just like c header file,

**Comment by djmangoo** [comment]
Why? What is the problem with `require` and `module.exports`? You can't export local variables, and that is the reason why `module.exports` is used instead. It also caches modules to save memory and prevent loading single file multiple times.

However, you can export local variables, but it is not recommended and it results in duplicating memory and may cause a lot of problems, and also prevents any optimizations. Suppose you have file `index.js` and you want to `#include` file `struct.js`. You can do something like this:

**index.js**

```js
// Like #include "struct.js" in C
eval(require('fs').readFileSync('./struct.js', 'utf8'));

// Then you can use it
console.log(new Struct(a, b).add());
```

**struct.js**

```js
var a = 5;
var b = 7;

var Struct = class{
  constructor(c, d){
    this.c = c;
    this.d = d;
  }

  add(){
    return this.c + this.d;
  }
};

// Notice: no require('struct.js'), no module.exports
```

**Comment by maxzhou0** [comment]
thank you @djmangoo ,that's an option, but eval solution is not acceptable for real practice, all i want is use the variable without adding  module prefix. like myModule.a ,myMoudle.Struct, it's quite inconvenience when refer them frequently. otherwise i have to write them all in a huge module

**Comment by djmangoo** [comment]
> all i want is use the variable without adding module prefix

You don't need to use the module prefix. For example:

**main.js**

```js
var {a, b, Struct} = require('./struct.js');
// Then use `a`, `b` and `Struct` like regular variables
```

And in struct.js use `module.exports = {a, b, Struct};`
I think it can't be more user-friendly.

**Comment by maxzhou0** [comment]
that was close. 
is there a 
import * from './struct.js' , //load all 
or 
import auto from './struct.js' , //engine auto search the undefined variable for me

or
var struct = require('./Struct.js')
using namespace struct //c++ style, which would be a perfect approach

**Comment by tniessen** [comment]
No, there is no way to do that in JavaScript, and I doubt there will ever be. Importing and exporting many variables might indicate high [coupling](https://en.wikipedia.org/wiki/Coupling_(computer_programming)) and low [cohesion](https://en.wikipedia.org/wiki/Cohesion_(computer_science)). This is often associated with bad design, so it *might* indiciate that you should restructure your application.
