### ISSUE TITLE
Worker (Multi) Threads

### ISSUE THREAD

**Issue by druny** [nodejs/help#1473]
`https://nodejs.org/api/worker_threads.html`
Hello Guys. I am started working with lecture for JS conf with theme about multi threading in NodeJs. I will so much appreciate, if it possible, get answers on my questions:
1. What Your team think about this.
2. What current status of the module.
3. When We be able expect stable version.
4. What hardest things meet, in implementation process
5. What do You think about it? Do it good idea?
6. What about future plans
It will be fine if NodeJS <multiThreads> team answer at least on one quastion
With best wishes. Thank you in advance

**Comment by addaleax** [comment]
Hi! This is a perfectly timed question, given that I’m just finishing up my notes for my talk about it at http://nordicjs.com/ this week! :smile: 

> When We be able expect stable version.

To a large degree, that depends on how much and what kind of feedback we get from our users. There’s no fixed time frame here.

> What hardest things meet, in implementation process

Windows support, during some of the work leading up to it. https://github.com/nodejs/node/pull/19377 was blocked on that for 2 months, with no progress being made.

> What current status of the module.

It’s experimental, meaning that we consider us free to make changes to it at any time, including breaking changes if necessary. However, I do think that we are committed to keeping this feature and the general API idea around.

> What about future plans

We’re looking for feedback, but generally, there are no large shifts in the feature currently planned.

Some things that I’d like to see and that I’ll try to make happen:

- Passing native handles around (e.g. sockets)
- (Some form of) Deadlock detection
- Naming individual threads

> 

I’m not going to answer the “what do you think about it” questions, I think I’m a tad too biased for that. :wink:

**Comment by AyushG3112** [comment]
I personally believe `worker_threads` are a great way to perform synchronous processing in nodejs without blocking the event loop of the main thread by delegating the processing to a worker(considering workers have their own event loop)

**Comment by gireeshpunathil** [comment]
@druny - are there outstanding questions that need answer? or else are we good to close this?

**Comment by druny** [comment]
@gireeshpunathil It's ok for me. Thank You
