### ISSUE TITLE
How to return to next iteration in loop in node js

### ISSUE THREAD

**Issue by ietuday** [nodejs/help#1475]
Node.js Version: v9.10.1
OS: Window 10
Scope: code
===============================================================================

```js
app.models.newCashTransaction.find(filter, (err, res) => {
        if (err) {
            return cb(err)
        }
        res.forEach(function (element, index) {
            var editGoalId = element.editGoalId;
            app.models.EditGoal.findById(editGoalId, (editGoalErr, editGoalRes) => {
                if (editGoalErr) {
                    return cb(editGoalErr)
                }
               if(editGoalRes ===null){
                 return;
           }
});
```

The Loop get stuck when it get null value. It does not return to next iteration. I also used continue for that,but same result.

Please give me some solution. Thanks in advance

**Comment by addaleax** [comment]
Hm – can you explain what you mean by `get stuck`?

**Comment by ietuday** [comment]
The loop does not move to next iteration.

**Comment by ietuday** [comment]
UndoRecorde = function (editIds, cb) {
    var resArr = [];
    var indexArr = [];
    var updateEditGoalValue = {
        cash: "PROCESSING",
        editGoalStatus: "PROCESSING",
        trade: "BLOCKED"
    }
    var idArr;
    if (queryToIdArr(editIds)) {
        idArr = queryToIdArr(editIds);
    } else {
        return cb(222, 'invalid edit id cannot parsed into int');
    }
    var filter = CashDataFilterGenerator(idArr);
    app.models.newCashTransaction.find(filter, (err, res) => {
        if (err) {
            return cb(err)
        }
        res.forEach(function (element, index) {
            var editGoalId = element.editGoalId;
            app.models.EditGoal.findById(editGoalId, (editGoalErr, editGoalRes) => {
                if (editGoalErr) {
                    return cb(editGoalErr)
                }
                console.log(editGoalRes.trade);
                if (editGoalRes.trade === "NEW") {
                    app.models.newCashTransaction.findOne({ where: { editGoalId: editGoalRes.id } }, (cashTransactionErr, cashTransactionRes) => {
                        if (cashTransactionErr) {
                            return cb(cashTransactionErr);
                        }
                        cashTransactionRes.updateAttributes({ cashStatus: "LIVE" }, function (updateErr, updateRes) {
                            if (updateErr) {
                                return cb(updateErr)
                            }
                            app.models.editGoal.findOne({ where: { id: updateRes.editGoalId } }, function (editGoalErr, editGoalRes) {
                                if (editGoalErr) {
                                    return cb(editGoalErr)
                                }
                                if(editGoalRes !==null){
                                editGoalRes.updateAttributes(updateEditGoalValue, function (updateErr, updateRes) {
                                    if (updateErr) {
                                        return cb(updateErr)
                                    }
                                    app.models.Cash.destroyAll({ editGoalId: updateRes.id }, (cashDeleteErr, cashDeleteRes) => {
                                        if (cashDeleteErr) {
                                            return cb(cashDeleteErr);
                                        }
                                        resArr.push(updateRes);
                                        indexArr.push(index);
                                        if (indexArr.length === res.length - 1) {
                                            // return cb(null, resArr);   
                                            var data = {
                                                status: 200,
                                                message: 'operation on record done'
                                            }
                                            return cb(null, data);
                                        }
                                    })
                                })
                            }else{
                                return;
                            }
                            })
                        })
                    })
                } else {
                    delete res[index];
                    res = res.filter(function (element) {
                        return element !== undefined;
                    });
                }
            })
        })
    })
}

**Comment by addaleax** [comment]
@ietuday Have you tried stepping through the function in e.g. the Chrome debugger, and seeing where it stops? You can do so by running `node` with the `--inspect` flag (or `--inspect-brk` if you want to stop the program at the beginning first), and opening `chrome://inspect` in the Chrome browser.

**Comment by ietuday** [comment]
@addaleax I have used vscode debugger for node js.

Is it correct way to return? 
I also used normal for loop and try with "continue". But it gives Illegal statement error.

**Comment by addaleax** [comment]
@ietuday Okay, that’s about the same thing :+1: 

> Is it correct way to return?
I also used normal for loop and try with "continue". But it gives Illegal statement error.

`return;` inside a `forEach()` callback should have the same effect as `continue` in a for loop, yes. :)

**Comment by ietuday** [comment]
@addaleax Thanks

**Comment by djmangoo** [comment]
> There is no way to exit a forEach loop

Actually, there is a loop called `Array.prototype.some` that can be stopped at any iteration by returning a truthy value.

**Comment by ietuday** [comment]
I tried "Array.prototype.some" but not able to solve this issue

**Comment by ORESoftware** [comment]
Oh man this code needs help.

I recommend using `async.autoInject` for this.

to get an early return, you should pass something as the first argument to any of the callbacks. Then handle that at the end, like so:

https://caolan.github.io/async/docs.html#autoInject

```js
async.autoInject({
  foo(cb){
       setTimeout(() => cb({early: true}), 10);
  },
 bar(foo, cb){
        setTimeout(() => cb(), 10);
 }

}, (err, results) => {

  if(err && err.early === true){
    // you exited early
 }

});
```

most likely, you will at the very least want to change the forEach into `async.eachLimit`:

example:

```js
const list = [1,2,3];

async.eachLimit(list, 1, (v, cb) => {

}, err => {

});
```

since the concurrency limit is 1, this is the same `async.eachSeries`.

**Comment by ORESoftware** [comment]
@ietuday I fixed your code a lot just by utiltizing "early return"

```js
UndoRecorde = function (editIds, cb) {

  var resArr = [];
  var indexArr = [];

  var updateEditGoalValue = {
    cash: "PROCESSING",
    editGoalStatus: "PROCESSING",
    trade: "BLOCKED"
  }
  
  if (!queryToIdArr(editIds)) {
    return cb(222, 'invalid edit id cannot parsed into int');
  }

  const idArr = queryToIdArr(editIds);

  var filter = CashDataFilterGenerator(idArr);

  app.models.newCashTransaction.find(filter, (err, res) => {

    if (err) {
      return cb(err)
    }

    res.forEach(function (element, index) {

      var editGoalId = element.editGoalId;

      app.models.EditGoal.findById(editGoalId, (editGoalErr, editGoalRes) => {

        if (editGoalErr) {
          return cb(editGoalErr)
        }
        console.log(editGoalRes.trade);

        if (editGoalRes.trade !== 'NEW') {
          delete res[ index ];
          res = res.filter(function (element) {
            return element !== undefined;
          });
          return;
        }

        app.models.newCashTransaction.findOne({ where: { editGoalId: editGoalRes.id } }, (err, cashTransactionRes) => {
          
          if (err) {
            return cb(err);
          }
          
          cashTransactionRes.updateAttributes({ cashStatus: "LIVE" },  (err, updateRes) => {
            
            if (err) {
              return cb(updateErr)
            }
            
            app.models.editGoal.findOne({ where: { id: updateRes.editGoalId } },  (err, editGoalRes) => {
              
              if (err) {
                return cb(err)
              }

              if (editGoalRes === null) {
                return;
              }

              editGoalRes.updateAttributes(updateEditGoalValue, function (updateErr, updateRes) {
                if (updateErr) {
                  return cb(updateErr)
                }
                app.models.Cash.destroyAll({ editGoalId: updateRes.id }, (cashDeleteErr, cashDeleteRes) => {
                  if (cashDeleteErr) {
                    return cb(cashDeleteErr);
                  }
                  resArr.push(updateRes);
                  indexArr.push(index);
                  if (indexArr.length === res.length - 1) {
                    // return cb(null, resArr);
                    var data = {
                      status: 200,
                      message: 'operation on record done'
                    }
                    return cb(null, data);
                  }
                })
              })

            })
          })
        })

      })
    })
  })
}

```

I recommend using semi-colons, btw. But anyway, try using the async library, or promises. One or the other, is imperative to survive in Node.js world.

**Comment by ietuday** [comment]
@ORESoftware Thank you so for replying and explaining autoInject. For now, I will try to async library as more as possible.

**Comment by ORESoftware** [comment]
no problem, the async library is fantastic. I recommend using TypeScript as well, in your future JS projects.
