### ISSUE TITLE
Can I create a net.Socket and then have a C++ addon use the underlying uv_tcp_t?

### ISSUE THREAD

**Issue by murgatroid99** [nodejs/help#148]
[I asked this previously on StackOverflow](http://stackoverflow.com/questions/36585464/can-i-use-a-node-tcp-socket-in-a-c-extension), but nobody seemed to know.

I have a Node module including an addon that does networking ([grpc](https://www.npmjs.com/package/grpc)), and I would like to use objects from node whenever possible to integrate better with existing Node libraries. In particular in this case, I want to use the UV event loop instead of running a separate one, and `uv_tcp_t` connections to use the same networking stack, and `net.Socket` and `net.Server` objects to work properly with the cluster library.

The solution I see is to simply create a `net.Socket` object and then extract the `uv_tcp_t` value from the underlying `TCPWrap` object. There are a few issues I see with this option:

 1. The Socket documentation seems to indicate that a socket immediately starts reading when it connects. I would expect that to cause data loss if I want to read on the underlying UV socket in the extension instead of listening for the 'data' event in JavaScript.

 2. While the `TCPWrap` class has a function to get the underlying `uv_tcp_t` struct, it does not seem to have an API to relinquish ownership of that struct. I expect this to cause problems later related to disposing of the struct and ownership of its data member (used for user data).

 3. The `TCPWrap` appears to be a private member of the Socket object (`_handle`).

Is there a good way to do this and avoid these problems?

**Comment by bnoordhuis** [comment]
The short answer is 'no'.  As you figured out, `TCPWrap` is an internal implementation detail.  You could write your own `TCPWrap`-like class and pass that to `new net.Socket({ handle: handle })` but then you'll be on the hook for ensuring it honors the contract for wrapped objects (and the details of that contract can change, even in stable releases; there is no API stability guarantee.)
