### ISSUE TITLE
Soooo, am i suppossed to simply extract the files from the Linux-bin download to root or ......

### ISSUE THREAD

**Issue by TheMalgot** [nodejs/help#1480]
Some small installation instructions would have been nice ...

**Comment by yathamravali** [comment]
@TheMalgot After extracting the files, npm and node will be available under bin.
So export the path into the executable or add the path to your profile.

Installation instructions:
1. Get the required version of node
`wget https://nodejs.org/dist/v11.6.0/node-v11.6.0-linux-x64.tar.xz`
2. Untar the binary
`tar xvf node-v11.6.0-linux-x64.tar.xz`
3. Go to bin folder 
`cd node-v11.6.0-linux-x64/bin`
4. Export the path 
`bash`
`export PATH=`pwd`:$PATH`
5. check the installation
`node -v`

**Comment by mhdawson** [comment]
@yathamravali thanks, that is exactly what I do. @TheMalgot where do you think the instructions would best be located in the existing doc?

**Comment by gireeshpunathil** [comment]
Potential action is to incorporate the above sequence in docs.

**Comment by gireeshpunathil** [comment]
in fact, the installation instructions from the tarball is documented here: https://github.com/nodejs/help/wiki/Installation 

closing.
