### ISSUE TITLE
Expose reason for `DeprecationWarning: Buffer() is deprecated ...` emit so it may be addressed?

### ISSUE THREAD

**Issue by JasonKleban** [nodejs/help#1481]
* **Node.js Version**: 10.7.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime

At runtime startup of an express website, `DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead` is emitted to the console.  I don't know how to find which dependency needs to be updated to resolve this warning.  How can I find out?

Since it is internal/native (I think) there's no breakpoint to hit or anything.

**Comment by addaleax** [comment]
>  I don't know how to find which dependency needs to be updated to resolve this warning. How can I find out?

Passing `--trace-warnings` or `--trace-deprecation` to `node` might help.

If you’re looking for the reason for this, [here](https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe) is a bit of information on this in our docs :)

**Comment by JasonKleban** [comment]
NICE!  Thanks!
