### ISSUE TITLE
urgently need help !!! How to remove a node

### ISSUE THREAD

**Issue by rdbox** [nodejs/help#1482]
I tried all the options I can not remove it from the computer what to do ??
Help urgently need to reinstall the new version

![image](https://user-images.githubusercontent.com/18515862/45187877-e5ea8780-b23a-11e8-8ab4-1d03ddea0f52.png)

**Comment by vsemozhetbyt** [comment]
Maybe try to download `node-v5.6.0-x64.msi` [from here](https://nodejs.org/download/release/v5.6.0/) and set the path to the folder containing this file?

**Comment by rdbox** [comment]
@vsemozhetbyt 
well done. It was necessary to immediately find this version

I have one more question, I run npm through the console and I also have
zsh shell and so here is the error.
I understand that I need to specify environment variables somewhere, but where?
Maybe give a batch of ideas thoughts?

**At the bottom I indicated the output of the log which is triggered when the npm help command is autocomplete**


```
npm ERR! A complete log of this run can be found in:                                              
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-09-06T22_44_50_917Z-debug.log   
_npm:8: command not found: _npm_completion                                                        
npm ERR! code ENOTSUP                                                                             
npm ERR! errno 129                                                                                
npm ERR! nospc npm completion supported only in MINGW / Git bash on Windows                       
npm ERR! nospc There appears to be insufficient space on your system to finish.                   
npm ERR! nospc Clear up some disk space and try                                                                                            
npm ERR! A complete log of this run can be found in:                                              
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-09-06T22_44_51_752Z-debug.log   
_npm:8: command not found: _npm_completion                                                        
npm ERR! code ENOTSUP                                                                             
npm ERR! errno 129                                                                                
npm ERR! nospc npm completion supported only in MINGW / Git bash on Windows                       
npm ERR! nospc There appears to be insufficient space on your system to finish.                   
npm ERR! nospc Clear up some disk space and try again.                                            
                                                                                                  
npm ERR! A complete log of this run can be found in:                                              
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-09-06T22_44_52_538Z-debug.log   
_npm:8: command not found: _npm_completion                                                        
```

**Comment by vsemozhetbyt** [comment]
Sorry, I do not know. Try to ask here:

https://github.com/npm/cli
https://npm.community/

**Comment by KennethSundqvist** [comment]
@rdbox 

I also had the `command not found: _npm_completion` error with zsh.

To fix it I had to add `source <(npm completion)` to my `.zshrc` file.

**Comment by gireeshpunathil** [comment]
@rdbox - did @KennethSundqvist 's suggestion worked for you? pls let me know

**Comment by rdbox** [comment]
> @rdbox - did @KennethSundqvist 's suggestion ~worked~ work for you? pls let me know
It was a long time ago I do not remember exactly.
But I kind of managed to solve the problem as described by the participants.

**Comment by gireeshpunathil** [comment]
thanks for the info. closing then!
