### ISSUE TITLE
Socket.io connection routing with clusters

### ISSUE THREAD

**Issue by berkcent** [nodejs/help#1486]
* **Node.js Version**:8.11.2
* **OS**:Any
* **Scope (install, code, runtime, meta, other?)**:Clusters
* **Module (and version) (if relevant)**:cluster/socket.io

Hi, I have app, which after authentication (through HTTP/Express) sets session variable company_id (stored in Redis). Then it establish socket.io connection, and bind user to matching company in dependence of company_id.

Because of future scale I have to use clusters, and I want to store different companies in different clusters, so I need to "route" every new connection to matching cluster and then to matching company.

For example (in pseudo-code):
```js
io.on('connection', socket => {
if(socket.request.session.company_id === 123) //bind to cluster 1, company 123
else if(socket.request.session.company_id === 321) ///bind to cluster 1, company 321
else if(socket.request.session.company_id === 542) ///bind to cluster 2, company 542
}
```
Of course I need to pass another condition to bind to required cluster, but leave it for now.

I hope you understand what I mean, if not, I will try to explain it more.

**Comment by gireeshpunathil** [comment]
@berkcent - what is the question / request here?

**Comment by gireeshpunathil** [comment]
inactive, closing
