### ISSUE TITLE
Segfault on master

### ISSUE THREAD

**Issue by paradigmf** [nodejs/help#1487]
* **Node.js Version**: master
* **OS**: Windows 8
* **Scope**: Build
* **Module**: Node.js itself

Downloaded source code as zip archive.
Extracted.
Navigated to extracted directory.
Ran vcbuild.bat as administrator.
Build was successfull.
Ran `"./Release/node.exe" -v`
Segfault occured. No output.

What am I doing wrong? Thanks.

**Comment by addaleax** [comment]
@nodejs/platform-windows Any ideas?

**Comment by seishun** [comment]
Can't reproduce. Please run it with a debugger and find out where the segfault occurs.

**Comment by bzoz** [comment]
Also cannot reproduce.

**Comment by paradigmf** [comment]
[screencast.mp4](https://www.youtube.com/watch?v=NEE90OOsCRY)

[debug.png](https://user-images.githubusercontent.com/43129358/45360250-4a0ca300-b5cf-11e8-955b-745f8dd78db5.png)

[debug.log](https://github.com/nodejs/help/files/2370942/debug.log)

[node.exe](https://raw.githubusercontent.com/paradigmf/tutorial/master/node.rar)

Anything else?

**Comment by tniessen** [comment]
@addaleax

```
0:000> gu
Unable to insert breakpoint 10000 at 00000000`00000000, Win32 error 0n299
    "Only part of a ReadProcessMemory or WriteProcessMemory request was completed."
The breakpoint was set with BP.  If you want breakpoints
to track module load/unload state you must use BU.
go bp10000 at 00000000`00000000 failed
WaitForEvent failed
ntdll!LdrInitializeThunk+0xe:
00007ffd`1dc68c8e b201            mov     dl,1
0:000> p
ntdll!LdrInitializeThunk+0x10:
00007ffd`1dc68c90 488bcb          mov     rcx,rbx
0:000> p
ntdll!LdrInitializeThunk+0x13:
00007ffd`1dc68c93 e8487e0700      call    ntdll!ZwContinue (00007ffd`1dce0ae0)
0:000> p
ModLoad: 00007ffd`1ac70000 00007ffd`1acb6000   C:\Windows\SYSTEM32\powrprof.dll
ModLoad: 00007ffd`1a5a0000 00007ffd`1a5f9000   C:\Windows\system32\mswsock.dll
(12f4.d40): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
node!node::options_parser::OptionsParser<node::PerIsolateOptions>::Insert<node::EnvironmentOptions>+0x4d:
00007ff7`11a81f2d 488b12          mov     rdx,qword ptr [rdx] ds:00000000`00000000=????????????????
0:000> p
(12f4.d40): Access violation - code c0000005 (!!! second chance !!!)
node!node::options_parser::OptionsParser<node::PerIsolateOptions>::Insert<node::EnvironmentOptions>+0x4d:
00007ff7`11a81f2d 488b12          mov     rdx,qword ptr [rdx] ds:00000000`00000000=????????????????
```

**Comment by bzoz** [comment]
+1 for the video, thanks!

Everything looks good. Do the official Node builds also fail to run ([latest nightly build is here](https://nodejs.org/download/nightly/v11.0.0-nightly20180911121439a8ff/win-x64/node.exe))? Does Node built from sources checked out with git also fail?

**Comment by paradigmf** [comment]
nightly: works
git checkout: segfault

**Comment by seishun** [comment]
Tried updating your Visual Studio installation?

**Comment by addaleax** [comment]
That this pops up in the options parser points to this being a real bug … having info from a debug build could be really helpful here?

**Comment by tniessen** [comment]
@paradigmf Could you try building a debug build using `vcbuild.bat debug`?

**Comment by refack** [comment]
```
node!node::options_parser::OptionsParser<node::PerIsolateOptions>::Insert<node::EnvironmentOptions>
                                                                                ^^^^^^^^^^^^^^^^^^
```
@paradigmf you have something "strange" in your environment. Not sure if it's a general thing or a misconfigured "NODE_OPTIONS" settings. Could you please paste `cmd /c set`

**Comment by paradigmf** [comment]
> Tried updating your Visual Studio installation?

Reinstalled VS2017 and everything works fine, thanks. It was probably a bug in old msvs version.

> Could you try building a debug build using vcbuild.bat debug?

Too late, sorry :/

---

Thank you everyone for help.

**Comment by joaocgreis** [comment]
I just had the same issue, noticed I couldn't run an executable I built last week (and didn't run at the time). Updating both Windows and Visual Studio fixed it.
