### ISSUE TITLE
How to return response from http module in Node.js?

### ISSUE THREAD

**Issue by DarwishAaron** [nodejs/help#1488]
How do I return the response value, **access_token**, to a variable for use elsewhere? It yields undefined if I try to log its value outside of `res.on('data')` listener.

```javascript
const http = require('http');
const authGrantType = 'password';
const username = '[The username]';
const password = '[The password]';
const postData = `grant_type=${authGrantType}&username=${username}&password=${password}`;
const options = {
  hostname: '[URL of the dev site, also omitting "http://" from the string]',
  port: 80,
  path: '[Path of the token]',
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
  }
};
const req = http.request(options, (res) => {
  console.log(`STATUS: ${res.statusCode}`); // Print out the status
  console.log(`HEADERS: ${JSON.stringify(res.headers)}`); // Print out the header
  res.setEncoding('utf8');
  res.on('data', (access_token) => {
    console.log(`BODY: ${access_token}`); // This prints out the generated token. This piece of data needs to be exported elsewhere
  });
  res.on('end', () => {
    console.log('No more data in response.');
  });
});
req.on('error', (e) => {
  console.error(`problem with request: ${e.message}`);
});

// write data to request body
req.write(postData);
req.end();
```

The token value is logged to the console by the line that reads: ```console.log(`BODY: ${access_token}`);``` The issue is with trying to extract this value to be used elsewhere. Rather than having to encapsulate every new function with an `HTTP` call inside the other call that was required to supersede it and provide it with a response before it could continue. It's sort of enforcing synchronicity in NodeJS.

**Comment by yathamravali** [comment]
@DarwishAaron 
Demonstation on how the execution occurs especially in asynchronous calls.
```js
var http = require('http')
var foo;
var server = http.createServer((q, s) => {
  s.setHeader('foo','bar')
  s.end('hello')
})
console.log(`#1: ${foo}`)
server.listen(30000, () => {
  http.get('http://localhost:30000', (s) => {
    //foo = s.headers.foo
    s.on('data', (m) => {
       foo = m.toString();
    })
    s.on('end', () => {
      server.close();
   })
  })
})
console.log(`#2: ${foo}`)
setTimeout(() => {
  console.log(`#3: ${foo}`)
}, 1000)
```
```
$node 1488.js
#1: undefined
#2: undefined
#3: hello
```
This demonstration is not to suggest to use timeouts but to say that the execution doesn't takes place in chronological order.

In  second `console.log` value is undefined because it is invoked before the callback as the client waits for the response from server.
In third ` console.log` as timeout is set for 1s it is executed after designated time interval so that able to access the response value outside `s.on('data')` 

So, decide on where to access the response value based on your application

**Comment by gireeshpunathil** [comment]
ping @DarwishAaron

**Comment by gireeshpunathil** [comment]
answered, closing
