### ISSUE TITLE
Best way to handle file upload from client to NodeJS API then upload to Google Storage

### ISSUE THREAD

**Issue by fnoori** [nodejs/help#1489]
* **Node.js Version**: 6.11.2
* **OS**: MacOS HighSierra 10.13.4
* **Scope (install, code, runtime, meta, other?)**: runtime/code
* **Module (and version) (if relevant)**: fs

I want help/guidance on how best to approach the following situation.

1. Client wants to upload file to my NodeJS API
2. Client chooses files to upload
3. Client uploads files to my API (files are stored in a tmp directory with timestamped names)
4. API then uploads the clients files to an appropriate Google storage directory
5. API then deletes the clients uploads from the tmp directory on the API using the ```fs``` library

My worry is that the use of the ```fs``` library to constantly rename/delete files is inefficient, especially if a large number of people are making requests to my API simultaneously.

I guess my question is, is this a good approach or is there something I'm doing very wrong? Any insight would be awesome !

**Comment by tedbundymav** [comment]
@fnoori Just wondering, did you finally figure it out?

**Comment by fnoori** [comment]
@tedbundymav Sorry for the super late reply.

I "sort of" figured it out. The most ideal way to handle this would be to just handle the file upload via the frontend with (in my case, VueJS).

Although, this defeats the purpose of having an API to handle all the backend stuff :/

Sorry, I don't have a better solution to this yet.

**Comment by gireeshpunathil** [comment]
@fnoori - why do you want to store the upload file in the server, if the data is anyways going elsewhere? I mean, why can't you just hold the file content in memory?

**Comment by fnoori** [comment]
@gireeshpunathil You have a good point, back when I was actively working on my project, I wanted to have the API handle everything coming from the frontend.
If I were to go back to the project, I would have done it all in the frontend.
