### ISSUE TITLE
Client disconnection not detected inside a net.createServer

### ISSUE THREAD

**Issue by skm2017** [nodejs/help#1492]
I'm trying to detect client disconnection on a server. I used on data, end, close and error events inside net.createServer. Whenever a client connects, data event is fired, but on disconnection no event is fired.

```
var net = require('net');

net.createServer(function (socket) {
    var clients = [];
    socket.name = socket.remoteAddress + ":" + socket.remotePort;

    clients.push(socket);

    socket.on('data', function (data) {
        console.log('data: ', data)
    });

    socket.on('end', function () {
        console.log('end, socket disconnected', socket.name);
    });

    socket.on('close', function () {
        console.log('close, socket disconnected', socket.name);
    });

    socket.on('error', function (error) {
        console.log('error, socket disconnected', error);
    });

}).listen(5000);
```
What is it that I'm doing wrong?

Any help would be much appreciated.

Thanks in advance.

**Comment by gireeshpunathil** [comment]
@skm2017 - is this still an issue? which version of node you are using? and which OS? 
your code looks good to me, but unable to reproduce with latest. Also when you say client `disconnect`, how are you achieving that? I guess by `socket.end()`?

**Comment by skm2017** [comment]
@gireeshpunathil - thanks for your reply, this issue is solved. On the client side I was using "forever-monitor" package and that was causing the issue.
