### ISSUE TITLE
fsPromises undefined

### ISSUE THREAD

**Issue by chrisdel101** [nodejs/help#1495]
* **Node.js Version**:
v8.11.4
* **OS**:
oSX 10.13.5
* **Scope (install, code, runtime, meta, other?)**:
Express 4.14

I am trying to use `fsPromises` from the [`docs`](https://nodejs.org/api/fs.html#fs_fspromises_readdir_path_options). I include it in my code and get undefined. 

```
const fs = require('fs');
const fsPromises = fs.promises;
console.log(fsPromises) //undefined
```

Would appreciate knowing how I can use this rather than the callback version (which is working in same file)

**Comment by vsemozhetbyt** [comment]
You need to upgrade Node.js version, there is no `require('fs').promises` in Node.js 8:

https://nodejs.org/docs/latest-v8.x/api/fs.html

You need Node.js 10:

https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_promises_api

**Comment by chrisdel101** [comment]
Doh! I didn't notice I was in the wrong docs. Thanks
