### ISSUE TITLE
Listen for arrow keys keypress with stdin (using raw mode)

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1496]
I am on Node.js version 8+

I have this question on SO:
https://stackoverflow.com/questions/52351184/cannot-distinguish-between-up-down-arrow-in-stdin-raw-mode

Does anyone know how to distinguish between the four arrow keys using raw mode? At the very least I am looking to distinguish between the up and down arrow keys.

**Comment by ORESoftware** [comment]
let me try it tomorrow will get back soon thx!!

**Comment by gireeshpunathil** [comment]
ping @ORESoftware

**Comment by gireeshpunathil** [comment]
inactive, closing
