### ISSUE TITLE
How to reuse http connection and avoid handshake each time I'm making a request ? 

### ISSUE THREAD

**Issue by constantinpopa11** [nodejs/help#1497]
I'm new to nodejs and and not too experienced with js. At the moment I'm rewriting an old java application which needs to be pretty fast at sending http requests to some server using their apis.

In Java I used to have several OkHttpClients and fire empty requests at those api's at regular intervals so when it was the moment to make a request (a non empty one) , the connection could be established immediately.

Now I'm trying to do the same using js and nodejs but I'm having a really hard time. I've tried to use an agent and keep alive header but it didn't change much, all requests take above one second to establish connection.

Now correct me if I'm wrong but when the code gets inside function(res), it means the connection was established, right?

I've measured the ellapsed time between the moment the request is fired and the moment it gets inside function(res) and it's always above 1 second. This makes me think the connection is NOT reused, because if it wasn't so, it should take less after the 2nd request (or at least that's how it worked in Java)

Here is the code I'm using

```
var https = require('https');
var agent = new https.Agent({
  keepAlive: true,
  maxSockets: 1,
  keepAliveMsecs: 3000
})

function sendReq(startTime){

  var options = {
    headers: {
      'connection': 'keep-alive'
    },
    protocol: "https:",
    host: 'myhost.example',
    method: 'GET',
    path: '/api/?q1=value,
    agent: agent
  };

  var req = https.get(options, function(res) {
    //console.log('PATH:', options.path)
    //console.log('STATUS: ' + res.statusCode);
    //console.log('HEADERS: ' + JSON.stringify(res.headers));

    let nanos = process.hrtime(startTime)
    console.log("Request executed in " + nanos);

    // Buffer the body entirely for processing as a whole.
    var bodyChunks = [];
    res.on('data', function(chunk) {
      bodyChunks.push(chunk);
    }).on('end', function() {
      var body = Buffer.concat(bodyChunks);
    })
  });

  req.on('error', function(e) {
    console.log('ERROR: ' + e.message);
  });
}```

**Comment by gireeshpunathil** [comment]
@constantinpopa11 - the code looks good to me. However, comparing the time to make that observation may not be conclusive, as i) there is remote end point and network data flow involved, ii) we haven't measured the baseline of time in terms of how much time is spend for socket creation vs how much time for data flow.

I suggest printing `ressocket.localPort` with and without `keepAlive` flag and see how it changes. With keep alive ON, we should see the same local port being used, where it will be different (mostly an ever increasing number) otherwise.

Hope this helps!

**Comment by gireeshpunathil** [comment]
ping @constantinpopa11

**Comment by constantinpopa11** [comment]
@gireeshpunathil Thanks a lot for your answer but unfortunately this is not a project I am working on anymore

**Comment by gireeshpunathil** [comment]
ok, thanks for the reply. I will close this as answered then. feel free to reopen if / when you get to work on this again, and my suggestion does not resolve the issue.
