### ISSUE TITLE
Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by BarthesSimpson** [nodejs/help#1498]
* **Node.js Version**: 10.10.0
* **OS**: MacOS 10.13.6 (17G65)
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: worker_threads

I am trying to experiment with the worker_threads module, but I just get `Error: Cannot find module 'worker_threads'` even when running with `--experimental-worker` flag. I installed node using the Mac installer from the nodejs.org website. What am I missing? 

<img width="1440" alt="screen shot 2018-09-16 at 5 53 04 pm" src="https://user-images.githubusercontent.com/6706880/45602838-ee308880-b9d9-11e8-87d4-aa40036c03d2.png">
<img width="1440" alt="screen shot 2018-09-16 at 5 52 46 pm" src="https://user-images.githubusercontent.com/6706880/45602839-ee308880-b9d9-11e8-994e-0c2fd2cc0c29.png">

**Comment by KorkyMonster** [comment]
@BarthesSimpson Did you find a solution? I'm struggling with the same problem.

**Comment by BarthesSimpson** [comment]
@KorkyMonster - yeah, I was putting the --experimental-worker flag after the filename but it has to go before, i.e. `node --experimental-worker index.js`

**Comment by KorkyMonster** [comment]
Wow, thank you! That made it work! Hopefully in the future, worker_threads are moved out of experimental and the flag is not required.
