### ISSUE TITLE
How node server will wait for response from SQL procedure which is running for 15 min

### ISSUE THREAD

**Issue by Shekharrajak** [nodejs/help#1499]
* **Node.js Version**: 10
* **OS**:  Windows 7 (will be deploying it in window 2008 R2 server or linux server)
* **Scope (install, code, runtime, meta, other?)**: 
* **Module (and version) (if relevant)**:

Hello team,

I have a node server, which is running (first connecting to oracle db) SQL procedures. If SQL procedure is small (completed within 2 min form oracle db) then it is fine. Means **oracle db will send response to node server and then it is sending the response to angular** in front end.

But when procedure is very big and it is taking time around 10 to 15 min, then node is not waiting for 15 min and **re-executing the request method** (in back side oracle db is executing the procedure and it is getting completed properly). Since Angular is also not waiting for response (when node server take more than around 2-3 minute), it is throwing error (no response from node server ).

So my question is , why node is **re-executing the request method**, why not it is waiting for oracle db connection response (node should wait for 15 min if procedure execution is taking 15 min).

Let me know if someone have answer for it. 

Thanks and regards,
Shekhar

**Comment by gireeshpunathil** [comment]
@Shekharrajak - is this still an issue for you? if you are using some middleware (such as express) on top of Node.js, you could provide the `timeout` argument to the appropriate middleware API. If you are using core API from Node.js itself such as `http.request` then supply a timeout argument that is more than your typical expected latency. Here is the documentation for request.setTimeout: https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_request_settimeout_timeout_callback 

Hope this helps!

**Comment by gireeshpunathil** [comment]
closing as answered.
