### ISSUE TITLE
Node request high Cpu on adobe suites

### ISSUE THREAD

**Issue by maucamo** [nodejs/help#1502]
* **Node.js Version**: unknown
* **OS**: mac osx 10.11.6
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**:

Hallo, Adobe creative cloud use node for some stuff (I don't know what it does). The process Node uses a lot of Cpu performance, always, and the only solution is to end the process. Adobe support tell me that they cannot solve the problem, probably because my mac with OS X 10.11.6 is too old. Now, how can I check the version in use and what can I do to solve the problem? How can I try to update myself to the last version, if the version inside adobe creative cloud is old? I tried to make the command on terminal node -v but it does not work.
Excuse me but I am not a technical. Thanks

**Comment by addaleax** [comment]
Hi! This is a pretty difficult question to answer.

First of all, it’s *possible* that updating Node will help you, but it’s unlikely – very few of the bugs with Node itself lead to high CPU usage. It’s more likely that the Node.js code inside Adobe Creative Cloud is faulty – but we can’t really do anything about that, and if you can’t update that, this problem gets even harder to fix.

That being said, my best guess would be to look out for places in which Node.js could be installed. You could search directories on your machine that could contain Adobe Creative Cloud and search for files called `node` – if you found one, figuring out its version, (making a backup and) replacing it with a freshly downloaded and recent version of Node.js *might* help.

**Comment by maucamo** [comment]
Ok I will try. Thanks

**Comment by gireeshpunathil** [comment]
ping @maucamo

**Comment by gireeshpunathil** [comment]
inactive, closing
