### ISSUE TITLE
Properly extend stream.Transform

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1503]
On Node.js versions 6+ 

I am wondering how to properly extend stream.Transform...I have this:

```js
export class JSONParser extends stream.Transform {

  lastLineData = '';
  objectMode = true;

  constructor() {
    super();

  }

  _transform(chunk: any, encoding: string, cb: Function) {
    cb();

  }

  _flush(cb: Function) {
     cb();
  }

}
```

looks like using the `_transform()` method is extended properly, but I am wondering if should use `_flush()` or `flush()`?

**Comment by ORESoftware** [comment]
Ultimately stream.Transform, stream.Readable, stream.Writable should be interfaces not classes? hard to say.

**Comment by ORESoftware** [comment]
If you want some SO points, you can copy your answer here:
https://stackoverflow.com/questions/52391773/properly-extend-stream-transform-class-with-typescript

since the OP in that question was wrong about _transform vs transform, it needs to be _transform.

**Comment by ORESoftware** [comment]
Yeah in the SO question, this implementation is correct:

```js
export const createParser = function () {

  let lastLineData = '';

  return new stream.Transform({

    objectMode: true,

    transform(chunk: any, encoding: string, cb: Function) {

      let data = String(chunk);
      if (lastLineData) {
        data = lastLineData + data;
      }

      let lines = data.split('\n');
      lastLineData = lines.splice(lines.length - 1, 1)[0];

      lines.forEach(l => {
        try {
          // l might be an empty string; ignore if so
          l && this.push(JSON.parse(l));
        }
        catch (err) {
          // noop
        }
      });

      cb();

    },

    flush(cb: Function) {
      if (lastLineData) {
        try {
          this.push(JSON.parse(lastLineData));
        }
        catch (err) {
          // noop
        }
      }
      lastLineData = '';
      cb();
    }
  });

};

```

but the class implementation I have above is wrong, it's not working for some reason.

**Comment by justinmchase** [comment]
You need to implement `_flush`. Otherwise what you have looks ok.

**Comment by gireeshpunathil** [comment]
I don't see any documented / code evidence of needing to implement `_flush` . pinging @nodejs/streams to see if they can confirm.

**Comment by mcollina** [comment]
You do not have to implement `_flush`. You _can_, if you have a need for it.
I would recommend setting it as part of your class definition if you inherit.

Passing it as an option is supported in case you are not inheriting:

```js
const ts = new stream.Transform({
  transform(chunk, enc, cb) {
    cb(null, chunk)
  },
  flush(cb) {
   cb()
  }
})
```

**Comment by gireeshpunathil** [comment]
answered, closing.

**Comment by fosk06** [comment]
> So I fixed it by using:
> 
> ```js
> super({objectMode: true});
> ```
> 
> but I still can't figure out if I need to implement `_flush()` or `flush()`, I am guessing the former.

I love you man
