### ISSUE TITLE
Does net.Socket write() method always fire callback in next tick of even loop?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1504]
Say we create a new socket connection:

```js
const s = net.createConnection({port});
```

and we call write:

```js
s.write('foo\n', () => {
   // does this callback always fire in the next tick of the event loop?
});
```

I am wondering if the "success" callback always fires in the next tick of the event loop? Wondering if it's always async, I would assume so, but no 100% sure. I am also wondering why there is never an error passed to the callback? Looks like the API for the callback has no arguments.

**Comment by addaleax** [comment]
The callback can be called later, if data has queued up and can’t be sent yet. So, if you write a lot of data in a close loop without waiting for the callback first, this can definitely occur. (Windows buffers a lot more data internally than other OS do, so it will take longer for this to happen then, at the cost of increased memory usage.)

I think the callback can be called with an error if a write failed, but I’m not sure how often that happens – most of the time, a broken socket would lead to a regular `'error'` first.

**Comment by ORESoftware** [comment]
yeah, to be sure I have just used this:

```js
s.write('foo\n', () => {
   process.nextTick(cb);
});
```

instead of

```js
s.write('foo\n', cb);
```

**Comment by addaleax** [comment]
Oh – sorry, I think I might have misunderstood. The callback can be called *later* than the next tick of the event loop, but it will never be called synchronously (similar to `setImmediate()`).

**Comment by ORESoftware** [comment]
Got it, yeah the OP was just about whether it always fires asynchronously, sounds like that is the case, thanks.

**Comment by addaleax** [comment]
@ORESoftware Just fyi, the 2. option is almost never used (the only exception is the `inspector` module) – it’s usually too hard to get right for users. Most of our callbacks are always-async, so I guess it might make sense to mark the other two types?

**Comment by ORESoftware** [comment]
@addaleax as I was saying the steam API definitely has a mixture, for example on 'data' callbacks etc

**Comment by ORESoftware** [comment]
the socket.write() callback is a great example of an ambiguous one, is it 1, 2 or 3?
