### ISSUE TITLE
Error to compile a Liferay-theme with name livingstone-fjord-theme

### ISSUE THREAD

**Issue by juanbolivar** [nodejs/help#1505]
c:\liferay\livingstone-fjord-theme\node_modules\liferay-theme-tasks\tasks\build\compile-css.js:24
                        throw err;
                        ^
Error: build\_css\_custom.scss
Error: File to import not found or unreadable: porlet/porlet_decorator.
        on line 2 of build/_css/_custom.scss
        from line 21 of build/_css/main.scss
>> @import "porlet/porlet_decorator";

   ^

    at options.error (c:\liferay\livingstone-fjord-theme\node_modules\node-sass\lib\index.js:291:26)

**Comment by gireeshpunathil** [comment]
ping @juanbolivar - can you pls describe what you are doing, and provide any sample test program?

**Comment by gireeshpunathil** [comment]
inactive, closing
