### ISSUE TITLE
What's the correct way to remove a child CJS module from the module cache without leaking memory?

### ISSUE THREAD

**Issue by isiahmeadows** [nodejs/help#1506]
Currently, every loaded CJS module is cached unconditionally. The usual means of forcing a reload is via `delete require.cache[require.resolve("foo")]` or `delete require.cache[__filename]` for removing itself. But that doesn't dereference the child completely, thanks to it being available in `module.parent.children`, so I also have to do `_.remove(module.parent.children, module)` to remove it (I normally use `splice` + `indexOf`, but this is just for clarity).

Is this enough to guarantee removing a CJS module from the cache, or are there more steps I need to take?

```js
// This is realm-independent, and `mod` is the module reference to uncache
function uncache(mod) {
    delete mod.constructor._cache[mod.filename]
    let children = mod.parent.children
    let count = 0
    for (let i = 0; i < children.length; i++) {
        if (children[i] !== mod) children[count++] = children[i]
    }
    children.length = count
}
```

This is useful for things like hot-swapping modules without necessarily having to kill and restart the process, hence why I ask.

**Comment by paradigmf** [comment]
Did a simple test:

```js
// index.js
while(1)
  uncache(require('./mod.js').mod);
```

```js
// mod.js
module.exports.mod = module;
module.exports.buff = Buffer.allocUnsafe(2 ** 30);
```

Observed no memory increase. Therefore, it doesn't leak.

**Comment by isiahmeadows** [comment]
Awesome! So this appears to be a solution.
