### ISSUE TITLE
Need to display the DB records in html or PHP file

### ISSUE THREAD

**Issue by nodejquery11** [nodejs/help#151]
Hi All,

Am beginner of Node JS but try to work on it. I am facing issue when print or display the records in HTML or PHP pages.
It is returning me the JSON formatted data but I am unable to get it in html or php page or else I don't understand how can I send this data in to pages.
Please help me

**Comment by leesei** [comment]
Use HTML template engine to transform the JSON to HTML, e.g.: [Nunjucks](https://mozilla.github.io/nunjucks/)

[So you need a template engine..](https://garann.github.io/template-chooser/)

**Comment by lordKnighton** [comment]
@nodejquery11 how's it going with this?

**Comment by nodejquery11** [comment]
Hey guys,
Thanks all.
I just simply use request and response method on http or https. And combine with the Ajax.
So once I will send the data to the server, it accept data as a request and response will retrieve by the same page, using the jQuery JSON conversion method.

**Comment by lordKnighton** [comment]
Gonna close for now, feel free to reopen 

👍
