### ISSUE TITLE
Node js as platform for client application

### ISSUE THREAD

**Issue by dibakarray** [nodejs/help#1510]
* **8.12.0**:
* **Windows 7 Ultimate**:
* **install, production**:
* **serialport**:

Hello. I am very new to Node js. I have a requirement of reading serial port data and making it available over web page. This application needs to be run on about 100 users Desktops with various OS and configurations. Naturally Node js was my first choice. However when I tried to install serialport package on 3 of my machines I found huge problems, some time it was with Python Version, some times it was VCBuild..exe. Some how I managed to install it in two machines. But now I am confused, even if I could develop the application on Node js ( which seems is not difficult) what would be degree of difficulties when user try to install it on their machines. Any advice will be appreciated.
Thanks in advance.

**Comment by gireeshpunathil** [comment]
I don't think Node.js binary require `python` - what error did you get w.r.t python? can you paste the error?

If you are talking about https://www.npmjs.com/package/serialport then it has native dependencies so you will have C/C++ build and runtime environment in all the systems - such as `gcc / glibc` in UNIX and `MSBuild` or `Visual studio` in Windows.

https://github.com/nodejs/node/blob/master/BUILDING.md lists the pre-requisite for building Node from source on a machine, that roughly applies to building node modules with native bindings too.

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if there is anything outstanding
