### ISSUE TITLE
Unable to update variables as OnInit() is not firing

### ISSUE THREAD

**Issue by partha6369** [nodejs/help#1514]
* **Node.js Version 10.10**:
* **OS Mac OS High Sierra**:
* **Scope Others**:
* **Module **:

Dear Sir/Madam,

I am new to Node.JS. I am learning through Node.JS University.

I want a part of my HTML Page to be updated with some data. For the data, I have written a service and this is returning the data correctly as fetched from the database. However, this is not getting displayed on the page.

I have written a OnInit(). However, OnInit() method is never getting fired.

The variables are referred in the corresponding HTML Files and should display the values as stored in these variables. Also, as the data changes, the listener should update the values.

Please help me solve this.

Thanks and Regards,
Partha

```
import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';

import { Currency } from '../currency.model';
import { CurrencyService } from '../currency.service';

@Component({
    selector: 'app-Currency-Statistics',
    templateUrl: './currencyStatistics.component.html',
    styleUrls: ['./currencyStatistics.component.css']
})
export class AppCurrencyStatisticsComponent implements OnInit {
  strActiveCurrencies = '';
  strDeletedRecords = '7';
  strLastUpdatedBy = 'partham';
  currencyList: Currency[] = [];
  private currencySubscription: Subscription;

  constructor(public currencyService: CurrencyService) {}

  ngOnInit() {
    this.strActiveCurrencies = this.currencyService.getRecordCount().toString();
    alert('Currency Count:' + this.strActiveCurrencies);
    this.currencySubscription = this.currencyService.getCurrencyUpdatedListener()
                    .subscribe( (currencies: Currency[]) => {
                                    this.currencyList = currencies;
                                    // this.refresh();
                                });
  }

}
```

**Comment by gireeshpunathil** [comment]
sorry, but to me this looks like an `angular` question!

**Comment by gireeshpunathil** [comment]
inactive, closing
