### ISSUE TITLE
Clarify example for AsyncResource

### ISSUE THREAD

**Issue by daprahamian** [nodejs/help#1517]
* **Node.js Version**: 10
* **OS**: N/A
* **Scope (install, code, runtime, meta, other?)**: ?Documentation
* **Module (and version) (if relevant)**: async_hooks

Hi there,

Can someone clarify the purpose of the new [`AsyncResource`](https://nodejs.org/dist/latest-v10.x/docs/api/async_hooks.html#async_hooks_class_asyncresource) class? The example provided doesn't seem to show why it is beneficial.

Thanks,
Dan

**Comment by gireeshpunathil** [comment]
ping @nodejs/async_hooks

**Comment by dko-ahoyhoy** [comment]
+1

**Comment by gireeshpunathil** [comment]
pinging @addaleax to see if a short description can be provided here. I can attempt, but cannot guarantee its correctness.

**Comment by gajus** [comment]
Similarly, `worker_threads` documentation is [suggesting to use `AsyncResource`], but there is no example of how:

> When implementing a worker pool, use the AsyncResource API to inform diagnostic tools (e.g. in order to provide asynchronous stack traces) about the correlation between tasks and their outcomes.

**Comment by pioardi** [comment]
+1

**Comment by gireeshpunathil** [comment]
@daprahamian - pls review https://github.com/nodejs/node/pull/31601 and see if that helps you

**Comment by pioardi** [comment]
@gireeshpunathil  yes I will review the PR today or tomorrow and will give a feedback on that , thanks !!!

**Comment by pioardi** [comment]
@gireeshpunathil I reviewed the PR , the example is clear and contains more details than expected ( error handling , wait a free worker, etc... ) :) .

Thanks !!!

**Comment by daprahamian** [comment]
@gireeshpunathil I looked it over, and the example looks good to me, and definitely clears up usage. Thanks!

**Comment by gireeshpunathil** [comment]
closing this as https://github.com/nodejs/node/pull/31601 has landed that covers this.
