### ISSUE TITLE
Run npm from CMD, it's show only blank cursor

### ISSUE THREAD

**Issue by raj967452** [nodejs/help#152]
Hi,

I have installed node 4.4.3, but when i open cmd and run only npm, it's show nothing. i have already created environment variable  but still have problem, please check screen shot

Environment variables:
**Path:** C:\Users\Admin\AppData\Roaming\npm;
          C:\Program Files\nodejs

![capture](https://cloud.githubusercontent.com/assets/2016809/14766709/cb45f896-0a31-11e6-9a4a-dd3fc0707c38.PNG)

**Comment by bharadwajpro** [comment]
Type `node` instead of `npm`

**Comment by lordKnighton** [comment]
try npm -v or node -v

**Comment by lordKnighton** [comment]
npm config get prefix


https://docs.npmjs.com/getting-started/installing-node click the link

**Comment by raj967452** [comment]
Thanks to every one, issue resolved by updating node and remove every entry from registry and all node folder.

**Comment by Sunder33** [comment]
Hello raj967452,

I am facing the same problem, could you please tell me how can I find all node folders in registry? There may be many things (key, value and data) where node would be written..

Thanks in advance..!!
