### ISSUE TITLE
Building Node from git does not show function names in V8

### ISSUE THREAD

**Issue by abhijangda** [nodejs/help#1523]
* **Node.js Version**: current git master and v10.11 from git
* **OS**: 64-bit Linux 4.4  Ubuntu 14.04 
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: V8

I compiled a C file to wasm and js using emcc using -O2 -g options. If I run it in node v10.11 (downloaded from https://nodejs.org/en/download/current/), like below
```
node --print_wasm_code <file.js>
```

Then node print the generated machine code with function names like below:
```
kind = WASM_FUNCTION
name = _main
compiler = turbofan
```
However, if I build node from git both master version or the version tagged at v10.11, I get the output without _name_:

```
kind = WASM_FUNCTION
compiler = turbofan
```
Can anyone please point me what were the build flags used for building node on https://nodejs.org/en/download/current/. I need to build node because I am working on a project, where have to modify node and v8 source code. Any help or pointers will be great. 

Thank You

**Comment by gireeshpunathil** [comment]
You can review (the head of) any of our CI jobs (I guess you will have readonly access) to see how node is built:

https://ci.nodejs.org/job/node-test-commit-linux/27392/nodes=ubuntu1804-64/consoleFull

**Comment by gireeshpunathil** [comment]
ping @abhijangda

**Comment by gireeshpunathil** [comment]
inactive, closing
