### ISSUE TITLE
bash does not propagate signals to subprocesses?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1524]
I am on Node.js version 10, say we have this:

```js
const k = cp.spawn('bash');
k.stdin.end(`node server.js`);

setTimeout(() => {
   k.kill('SIGINT');
}, 4000);
```

what happens is that bash does *not* seem to propagate the SIGINT signal to the node.js process. such that the bash process will be killed, but a server in the node.js process will not receive the signal.  If I restart the node server.js command, I will get EARRADINUSE - the port is still being listened on.

I don't think this is node.js specific, I think it has to do with bash, but I guess maybe someone might know why bash executable doesn't forward signals to processes run from bash?

**Comment by ORESoftware** [comment]
I think the answer is to use exec, like so:

```js
const k = cp.spawn('bash');
k.stdin.end(`exec node server.js`);

setTimeout(() => {
   k.kill('SIGINT');
}, 4000);
```

**Comment by gireeshpunathil** [comment]
@ORESoftware - you are right. There is no reason for bash to propagate the signal to the processes it started. On the other hand when you run `exec`, `k` represents `node` process itself, so it works as expected.

**Comment by gireeshpunathil** [comment]
closing, pls re-open if there is anything outstanding here
