### ISSUE TITLE
[Query] Custom class object as Key in a Map

### ISSUE THREAD

**Issue by jay11ca39** [nodejs/help#1527]
Hello All, 

I am new to nodejs/js, I have some query regarding the implementation of Map [Key-Value pair]

Like in java Maps, we can have custom object as key. 

```
Class Test {
   int i;
}

public static void main(String args[]) {
   Test obj = new Test();
   Map<Test, String> map= new HashMap<Test, String>();
   map.put(obj, "TestString");
}
```

Can we have similar thing in nodejs?

**Comment by jay11ca39** [comment]
@addaleax , 
Thanks for reply. 
As per the documentation of Map:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Map is not fully supported till IE 10 and some methods like (map.set()) is not fully supported in IE 11 as well. Do you have any comments for this?

**Comment by addaleax** [comment]
> Map is not fully supported till IE 10 and some methods like (map.set()) is not fully supported in IE 11 as well. Do you have any comments for this?

Not really. If you want this feature in a Browser environment, you’ll have to look into transpiling options or see how much browser support you want.

**Comment by jay11ca39** [comment]
@addaleax ,
Ok.. I will check regarding browser support. 
Thank for your help.. :)
