### ISSUE TITLE
[Query] How to develop Multi-threaded module in nodejs?

### ISSUE THREAD

**Issue by jay11ca39** [nodejs/help#1531]
Hi All,
I want to develop something in which I want to create threads for specific operations.

**For example:** In my client stack, I want to create a thread which will be sending a Rest request to server at some regular intervals. 

I browsed on internet for multi-threaded query, but I did not get the concrete answer for this. 
Any help will be appreciated.

**Comment by addaleax** [comment]
While Node.js 10 has some multi-threading support, a thread per request is definitely a bad idea in Node.js. You should only be using multi-threading if you bottleneck is a CPU-heavy workload on your end.

Node.js performs asynchronous I/O, which means that it can handle multiple concurrent requests in the same thread performantly and without conflicts. For example:

```js
const https = require('https');

https.get('https://example.org')
  .on('response', (response) => {
    response.pipe(process.stdout));  // Write the response body to stdout
  });

https.get('https://example.com')
  .on('response', (response) => {
    response.pipe(process.stdout));  // Write the response body to stdout
  });
```

In this example, both requests run at the same time without the need for threads.

**Comment by jay11ca39** [comment]
Hi @addaleax ,
Thank you for your reply. I checked node 10 documentation, but seems the work is in progress. So, I can not use for my production environment.

Let me explain my scenario in detail:
I have a publisher which is publishing on some topic. As node js is single threaded. Publisher is in main thread. But along with publish event, I want to send a keep alive rest request to some server. 

I checked the web-worker module of nodejs. But, as per my understanding, the main thread and web worker can not share the data. The data can be sent via methods of web-worker that is sendMessage() method. But, I am facing some problem in sending the custom object, as data is serialized and             
 de-serialized. also data is copied from main thread to worker so, there will be copy of each data that i send.

Do you have any idea how can I achieve my use case ?

**Comment by jay11ca39** [comment]
@addaleax ,
Thanks for your reply.
I have only one doubt, if my publisher is too much thread intensive, I mean to say if it is helding the thread for longer time, meanwhile if my keep alive timeout occured then ?

Do I have to restrict publish API to be called in some gap [using setInterval() API], so that my keepalive request can get the chance to send.

**Comment by addaleax** [comment]
@jay11ca39 That really depends on your application. What you want to avoid is to do a lot of synchronous work that stops other I/O from happening – but I would recommend to not prematurely optimize, and instead first see whether that is even a *potential* problem

**Comment by gireeshpunathil** [comment]
ping @jay11ca39 - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing
