### ISSUE TITLE
Node.js website not responding

### ISSUE THREAD

**Issue by rogermudd009** [nodejs/help#1532]
Hey everyone,
The Nodejs.org is not responding and I really need the download for Microsoft would someone be will to share the file with me, please. 

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by e8kkzbh** [comment]
If you just need the installer and you can't access the official website, you can download it [here](https://drive.google.com/open?id=1u1GC0Jwjsn1_khuYxOBkJ3USxIbMcTuP).

**Comment by shellberg** [comment]
An alternative to nvm that will work on Windows is [nvs](https://github.com/jasongin/nvs) (Node Version Switcher).

**Comment by gireeshpunathil** [comment]
ping @rogermudd009 - is this still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing
