### ISSUE TITLE
Problems setting the correct node version using nvm

### ISSUE THREAD

**Issue by Inkimar** [nodejs/help#1534]
* **Node.js Version**:
v10.1.0 ( but I want v8.9.1 when I start a terminal) 
* **OS**:
Linux Mint 17.3 Rosa

* **Scope (install, code, runtime, meta, other?)**:
1) ```curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash ```
2) ```nvm install 8.9.1```
3) ```nvm alias default v8.9.1```

* **Module (and version) (if relevant)**:
$ ```nvm --version```
0.33.11
$ ```npm --version```
5.5.1

I did install node v8.9.1  first according to the steps above and then later installed node v10.1.10 through synaptic ( guess that was through the update manager'). I want to keep running with the v8.9.1 .
After the installation of v10.1.10 i get the following message  everytime I open a new terminal
>nvm is not compatible with the npm config "prefix" option: currently set to "/usr"
>Run `npm config delete prefix` or `nvm use --delete-prefix v8.9.1 --silent` to unset it

running the cmd : ```nvm alias default v8.9.1```
only changed the version in the current terminal but not the others ?
I guess this has to do with some user-file ( /etc/profile, or ~/bash_profile or ~/bash_login or .bashrc ) 
the .bashrc _seems_ to be correct after searching for a solution.
>$ ```cat .bashrc```
>export JAVA_HOME=/usr
>export PATH="$JAVA_HOME/bin:$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
>export NVM_DIR="$HOME/.nvm"
>[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
>[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads >nvmbash_completion

The solution, which works for me right now, was to uninstall v10.1.0 using synaptic.
Is the answer to never use synaptic when installing other node versions but instead use nvm ?

best, Inkimar

**Comment by gireeshpunathil** [comment]
how about `nvm use <version>` ? does it help?

**Comment by patrickmichalina** [comment]
Seeing this now too

**Comment by gireeshpunathil** [comment]
ping @Inkimar

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by donaldharrington** [comment]
ok
