### ISSUE TITLE
Shared node_modules.

### ISSUE THREAD

**Issue by ThaneswarS** [nodejs/help#1537]
Node.js Version- v8.12.0
Windows 10.

Hi Team.
I have 5 individual angular-v6 projects. Each application having its own  Node_modules, Which is used for development purpose.

I am using JBoss as a application server and maven as a build tool. At the time build it create Node_Modules folder for each application. The problem is the size of node_module is too much, which takes too much space and time to build the application.

Is there any way by which we can share one node_module  across all 5 application?

**Comment by sidvishnoi** [comment]
Have a look at https://github.com/lerna/lerna (specifically the `--hoist` option)

**Comment by ORESoftware** [comment]
Yes, put the node_modules folder in a shared grand-parent directory. See this answer:

https://stackoverflow.com/a/47009146/1223975

Node.js uses a module-resolution algorithm - it walks up the filesystem and looks in node_modules, and keeps walking up until it finds a matching dependency.

**Comment by gireeshpunathil** [comment]
https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_all_together has the module loading algorithm in detail, and the most relevant info here is what was said by @ORESoftware 

Closing this as answered, but feel free to reopen if it you have outstanding question on this.
