### ISSUE TITLE
using Timer._called

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1539]
How stable/safe is it to reference _called on a timer for library code?

```js
const to = setTimeout(() => {
  console.log(to._called);
}, 10);

console.log(to._called);
```

before it times out, it is false, after it times out, it is true.
Is this a stable API, can we use it?

**Comment by ORESoftware** [comment]
bamp

**Comment by addaleax** [comment]
I guess this wouldn’t be removed without a semver-major change, but you can’t be sure of that. It’s not stable API, and it’s not even public API – if you need something like this, you could propose something like `timer.called` as a public API that forwards this.

**Comment by ORESoftware** [comment]
@addaleax since you have Le Clout do you want to propose on the Node Github issues? O/w I can do it

**Comment by gireeshpunathil** [comment]
@ORESoftware - looking at the code, https://github.com/nodejs/node/pull/20555 seems to have removed this field. And given the main intent of that PR is to improve timer performance, I guess an RFE for the above API may require a justification in terms of use case, inability to meet some programming scenarios etc.

**Comment by gireeshpunathil** [comment]
no action identified, closing
