### ISSUE TITLE
v8.setFlagsFromString() security discretion

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#154]
From [v8 docs](https://nodejs.org/api/v8.html#v8_setflagsfromstring_string):

> **`setFlagsFromString(string)`**
>
> Set additional V8 command line flags. Use with care; changing settings after the VM has started may result in unpredictable behavior, including crashes and data loss. Or it may simply do nothing.

Are there any criteria to assume this call to be more or less secure by?

Say, we have [`--harmony_regexp_lookbehind`](https://bugs.chromium.org/p/v8/issues/detail?id=4545) with the [`--es_staging`](https://bugs.chromium.org/p/v8/issues/detail?id=4545#c18) status. It seems that it will be `--es_staging` for a long time (because there is no draft or even proposal as for now if I get it right). Is there any security reason to prefer

`node --harmony_regexp_lookbehind script.js`

to

`v8.setFlagsFromString('--harmony_regexp_lookbehind');`

inside the `script.js`? Apart from security caution for not stable features.

**Comment by bnoordhuis** [comment]
When in doubt, set the flag on the command line.  As a rule of thumb: if you have to ask whether it's safe to use `v8.setFlagsFromString()` for something, you can assume the answer is 'no'.

**Comment by vsemozhetbyt** [comment]
Thank you.
