### ISSUE TITLE
Node js server TCP

### ISSUE THREAD

**Issue by Andreafoxalarm** [nodejs/help#1540]
* **Node.js Version**:        10.11.0
* **OS**:                             Windows 10

Good morning
I'm using NODE JS as a TCP server.
In my development I have an electronic circuit with a WI-FI module that must be permanently connected to the server, and a telephone with an APP, which connects and sends data and disconnects.
I know that a TCP connection after a time of inactivity is closed automatically, how often do I have to send a byte in order to keep the connection always open? it seems to me that in the absence of activity the connection closes in 4 minutes
Thank you all for your help

**Comment by gireeshpunathil** [comment]
not sure  whether we are thinking about the same thing, but could you please try with this:
https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_socket_setkeepalive_enable_initialdelay
and 
https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_socket_settimeout_timeout_callback

**Comment by Andreafoxalarm** [comment]
I did not set the timeout, should I put it?
I tried to set socket.setKeepAlive, on windows 10 it does not seem to change anything.
after about 4 minutes my TCP connection closes and I have to reopen it.
the TCP server never goes to block, it closes the connection with a client after about 4 minutes of data inactivity.
now I set my electronics that every 3 minutes send a data to the server, for now it seems to work well.
My question is :
can I increase this time before the TCP connection with the client closes due to inactivity?
Thank you all

**Comment by gireeshpunathil** [comment]
what is the value you set for `setKeepAlive` ?  I guess it is less than 4 minutes?

Ideally, sockets can be kept alive indefinitely through the keep-alive mechanism even if the apps at both end-points are inactive.

I guess we need to figure out which `entity` has configured 4 minutes life for your socket: defaults on the system vs. any network / firewall configuration etc. ( I don't know how do we figure this out in windows) /cc @nodejs/platform-windows

**Comment by seishun** [comment]
Neither Windows nor Node.js close the connection automatically, so it must be your phone. You can use Wireshark to find out who closes the connection.

**Comment by Andreafoxalarm** [comment]
I'm trying to understand the problem, I think it's as you say, and the WI-Fi module that closes the connection. Thank you all for your help

**Comment by tniessen** [comment]
Closing as answered.
