### ISSUE TITLE
@nodejs/platform-s390 : pb with installing npm 5.4.2

### ISSUE THREAD

**Issue by philippe-richard** [nodejs/help#1541]
* **6.14.3**:  trial version of nodejs 6.14.3 from https://developer.ibm.com/node/sdk/ztp/ 
* **OS**: z/OS 2.3
* **install npm 5.4.2**:

**Comment by gireeshpunathil** [comment]
I remember there was a recent (hang | high-cpu) issue of node on s390, but not sure about the specific details (version, external symptom etc.)

/cc @nodejs/platform-s390

**Comment by gireeshpunathil** [comment]
@philippe-richard - can you check if the process takes high CPU while it thus hangs?

**Comment by sam-github** [comment]
Maybe https://github.com/ibmruntimes/node/issues/104 from  https://github.com/ibmruntimes/node/issues ?  @philippe-richard the ibmruntimes repo is where https://developer.ibm.com/node/sdk/ztp/ suggests posting feedback/bugs.

**Comment by Trott** [comment]
> @philippe-richard the ibmruntimes repo is where https://developer.ibm.com/node/sdk/ztp/ suggests posting feedback/bugs.

@sam-github FWIW, they were redirected here (by me) from the nodejs/node repo. So the above is (at least) their second redirection.... Not sure if there's anything that can be easily done to smooth that sort of thing out in the near-term, but just flagging it for you.

**Comment by philippe-richard** [comment]
Hi Gireesh,
yes it is consuming a lot of CPU, and alos doing many IOs...

when i click this link below , it goes in limbo 'error 404'....
@nodejs/platform-s390

Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 6799580705 (38 0705)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2

**Comment by philippe-richard** [comment]
when i run npm install -g npm@5.4.2, then i get:
#npm install -dd -g npm@5.4.2
?øÁ>ËËÄ?>ÃÑÅÃ/ÑÁÀÁÊÊ?ÊË`ËÈÁ_%ÑÂÊ/Ê`Ã?øÁ>áàäñ+?ËÍÄÇÃÑ%Á?ÊÀÑÊÁÄÈ?Ê`npm info it worked if it ends with ok
npm verb cli [ '/Z23R01/usr/lpp/IBM/node/node-v6.14.3-os390-s390x/bin/node',
npm verb cli   '/var/zowe/0.9.0/EPHAN/tmp/bin/npm',
npm verb cli   'install',
npm verb cli   '-dd',
npm verb cli   '-g',
npm verb cli   'npm@5.4.2' ]
npm info using npm@5.4.2
npm info using node@v6.14.3
npm verb npm-session 6b1387b32cd0cc4a
npm http fetch GET 304 https://registry.npmjs.org/npm 763ms (from cache)
[..................] \ loadRequestedDeps: sill install loadAllDepsIntoIdealTree

and then it freezes, or loops. When i look at the process generated from z/OS monitor (SDSF), then i see that the process is using up a full CPU (25%, and i have 4 CPs defined), and doing many I/Os
JOBNAME   CPU% ASID ASIDX  EXCP-Cnt   CPU-Time 
PRICHAR  24.45  107 006B   30710457     284.47

**Comment by gireeshpunathil** [comment]
the issue was resolved with `v6.14.4`. Closing.

**Comment by philippe-richard** [comment]
when i run npm install -g npm@5.4.2, then i get:
#npm install -dd -g npm@5.4.2
?øÁ>ËËÄ?>ÃÑÅÃ/ÑÁÀÁÊÊ?ÊË`ËÈÁ_%ÑÂÊ/Ê`Ã?øÁ>áàäñ+?ËÍÄÇÃÑ%Á?ÊÀÑÊÁÄÈ?Ê`npm info it worked if it ends with ok
npm verb cli [ '/Z23R01/usr/lpp/IBM/node/node-v6.14.3-os390-s390x/bin/node',
npm verb cli   '/var/zowe/0.9.0/EPHAN/tmp/bin/npm',
npm verb cli   'install',
npm verb cli   '-dd',
npm verb cli   '-g',
npm verb cli   'npm@5.4.2' ]
npm info using npm@5.4.2
npm info using node@v6.14.3
npm verb npm-session 6b1387b32cd0cc4a
npm http fetch GET 304 https://registry.npmjs.org/npm 763ms (from cache)
[..................] \ loadRequestedDeps: sill install loadAllDepsIntoIdealTree

and then it freezes, or loops. When i look at the process generated from z/OS monitor (SDSF), then i see that the process is using up a full CPU (25%, and i have 4 CPs defined), and doing many I/Os
JOBNAME   CPU% ASID ASIDX  EXCP-Cnt   CPU-Time 
PRICHAR  24.45  107 006B   30710457     284.47

**Comment by philippe-richard** [comment]
pb solved after installing nodejs 6.1.4.4 on z/OS.

**Comment by philippe-richard** [comment]
pb solved after installng nodejs 6.14.4
