### ISSUE TITLE
When will "--experimental-modules" be no longer needed?

### ISSUE THREAD

**Issue by zhanzhenzhen** [nodejs/help#1542]
When will "--experimental-modules" be no longer needed?

**Comment by richardlau** [comment]
See the discussion in https://github.com/nodejs/node/issues/22940.

**Comment by zhanzhenzhen** [comment]
Why I can't see your comment? Also, I mean "--experimental-modules", which is for es modules, not for thread workers.

**Comment by gireeshpunathil** [comment]
pinging @nodejs/modules-active-members to learn about exit experimental criteria and status

**Comment by devsnek** [comment]
if say we're still within the territory of "this experimental feature isn't really usable". we still have to fix a lot of bugs and inconsistencies, a lot of compat is still missing, etc.

**Comment by gireeshpunathil** [comment]
answered, closing
