### ISSUE TITLE
How to filter the data from array of objects in js

### ISSUE THREAD

**Issue by susmitha01** [nodejs/help#1545]
I have a resData = [{
                "country": "United States",
                "countryCode": "USA"
            },
            {              
                "country": "Afghanistan",
                "countryCode": "AFG"
            },
            {
                "country": "Albania",
                "countryCode": "ALB"
            }]

I want to remove "USA" field  i'm using below code
 var filterData = resData.filter((itemData) => itemData.countryCode != "USA");

But it's not working can u please help me this out!!

**Comment by gireeshpunathil** [comment]
$ cat 1545.js
```js
const resData = [{
"country": "United States",
"countryCode": "USA"
},
{
"country": "Afghanistan",
"countryCode": "AFG"
},
{
"country": "Albania",
"countryCode": "ALB"
}]


var filterData = resData.filter((itemData) => {
  return itemData.countryCode !== 'USA';
})

console.log(filterData)
```

$ node 1545.js 
[ { country: 'Afghanistan', countryCode: 'AFG' },
  { country: 'Albania', countryCode: 'ALB' } ]
$

**Comment by susmitha01** [comment]
thanks..it worked
