### ISSUE TITLE
(ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors) in Angular 6

### ISSUE THREAD

**Issue by UdaykumarChepuri** [nodejs/help#1547]
When trying to make api calls using proxy in angular 6, getting the error as "(ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)"
Service file:
![image](https://user-images.githubusercontent.com/38068162/46875309-0e2c5e00-ce59-11e8-953b-5a53173985bf.png)
proxy.conf.js:
![image](https://user-images.githubusercontent.com/38068162/46875843-6ca60c00-ce5a-11e8-871a-29405314ca47.png)

Please help on this...

**Comment by gireeshpunathil** [comment]
ping @UdaykumarChepuri - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
