### ISSUE TITLE
get stack trace of process that died

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1549]
Say we have:

```js
const cp = require('child_process');
const k = cp.spawn('bash');
k.stdin.end(`node foo.js`);
k.once('exit', code => {
    // exits with code
});
```

is there a way to capture the stack trace of the process that died? My only idea is to capture the last 20 lines or so, something like this:

```js
const cp = require('child_process');
const k = cp.spawn('bash');
k.stdin.end(`node foo.js`);

const stderr = [];

k.stderr.on('data', d => {
    stderr.push(d);
   if(stderr.length > 10){
      stderr.shift();
   } 
});

k.once('exit', code => {
    // exits with code
});
```

is there a good way to capture the last stack trace that causes a process to crash?

**Comment by gireeshpunathil** [comment]
how about this?

$ cat 1549.js 
```js
const temp = process.exit

process.exit = function() {
  console.trace()
  process.exit = temp
  process.exit()
}
foo()

function foo() {
  bar()
}

function bar() {
  process.exit()
}
```
#node 1549.js 
```
Trace
    at process.exit (/home/gireesh/1549.js:6:11)
    at bar (/home/gireesh/1549.js:17:11)
    at foo (/home/gireesh/1549.js:13:3)
    at Object.<anonymous> (/home/gireesh/1549.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
```
$

**Comment by ORESoftware** [comment]
But if the process crashed, instead of exited programmatically?

**Comment by gireeshpunathil** [comment]
ok - if it crashes:

 - by the time you (a tracking parent) realizes that the subject process crashed (mostly through an exit code or so) it is too late; as the subject process is in it last phase of the cleanup, or already exited fully.

 - if we capture stack trace at every control flow points in the subject process (in anticipation of a future crash) it is too early; and we will end up collecting traces endless times before we actually needing to make use of one.

**Comment by gireeshpunathil** [comment]
ping @ORESoftware

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by SalathielGenese** [comment]
@ORESoftware , if your spawn process is a node script, you can use

`node --require path/to/my/script-that-override-process.exit.js other cli paramaters`...
