### ISSUE TITLE
Ubuntu install of version 6.0.0

### ISSUE THREAD

**Issue by davetorq** [nodejs/help#155]
Hi, could somebody please assist me with installing nodejs version 6.0 to Ubuntu 16.04? I can download and extract the Linux x64 tarball but am not sure what to do with that or what the pre requisites are before doing so. should i just be extracting this over an existing nodejs install? I see reference made to needing specific symlinks created by nodejs-legacy so presumably I need to install that with apt-get install first before extracting the latest version? any help wuld be much appreciated, even if it is just telling me where the instructions are

**Comment by bnoordhuis** [comment]
If you've downloaded the source tarball, you're going to need a compiler toolchain; `apt-get install build-essentials` (IIRC, not a Ubuntu user) should set that up for you, then run `./configure && make -j8 install`.

If you downloaded the binaries tarball, you can just extract that anywhere and run it; the binaries are in the bin/ directory.

**Comment by bnoordhuis** [comment]
> any help wuld be much appreciated, even if it is just telling me where the instructions are

They're in the README, by the way. :-)

**Comment by davetorq** [comment]
Thanks Ben, I read through the README and the only instructions I saw were to refer to the website for installation help, must have missed them, sorry about that.

I noticed that the binaries were in the bin folder but wasn’t sure if it needed to be extracted to a specific path in the file system (like /usr) to keep the relative paths

I will take another look

Kind Regards

Dave Pink
Systems Administrator
Torq Software<http://www.torqsoftware.com/>
"Your business success through software development"

t: +61 8 9409 5605 e: dave@torqsoftware.com<mailto:dave@torqsoftware.com>
f: +61 8 9467 6145 w: www.torqsoftware.com<http://www.torqsoftware.com>
a: Unit 1A 30 Buckingham Drive, Wangara, Western Australia, 6065

**Comment by davetorq** [comment]
Hi

Please find attached the README.md file from the root of the Linux binary tarball I downloaded from your site , I can find no installation instructions in it, contrary to your email

Regards

Dave Pink
Systems Administrator
Torq Software<http://www.torqsoftware.com/>
"Your business success through software development"

t: +61 8 9409 5605 e: dave@torqsoftware.com<mailto:dave@torqsoftware.com>
f: +61 8 9467 6145 w: www.torqsoftware.com<http://www.torqsoftware.com>
a: Unit 1A 30 Buckingham Drive, Wangara, Western Australia, 6065

**Comment by bnoordhuis** [comment]
If you download the binaries tarball, there's only the README.  If you download the source tarball, there's also a `BUILDING.md` in the top-level directory listing the steps and the prerequisites.

**Comment by lordKnighton** [comment]
@davetorq how's it coming with this?
