### ISSUE TITLE
529 verbose stack ZlibError: zlib: unexpected end of file

### ISSUE THREAD

**Issue by AlexandroGonSan** [nodejs/help#1552]
I have this error.
Occurs when I use npm install.

Estou com esse erro .
Ocorre quando uso o npm install .

- 529 verbose stack ZlibError: zlib: unexpected end of file
529 verbose stack     at Zlib.(anonymous function).onerror (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\minizlib\index.js:131:21)
529 verbose stack     at Unzip.write (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\minizlib\index.js:255:31)
529 verbose stack     at Unzip.flush (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\minizlib\index.js:222:10)
529 verbose stack     at Unzip.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\minizlib\index.js:229:10)
529 verbose stack     at Object.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:415:21)
529 verbose stack     at PassThrough.onend (_stream_readable.js:595:10)
529 verbose stack     at Object.onceWrapper (events.js:313:30)
529 verbose stack     at emitNone (events.js:111:20)
529 verbose stack     at PassThrough.emit (events.js:208:7)
529 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
529 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
529 verbose stack     at process._tickCallback (internal/process/next_tick.js:181:9)
530 verbose cwd D:\ALEXANDRO\Google Drive ( PESSOAL - alexandrogonsan )\BANCO DE DADOS EM USO\IAMDinosaur
531 verbose Windows_NT 6.3.9600
532 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
533 verbose node v8.12.0
534 verbose npm  v6.4.1
535 error code Z_BUF_ERROR
536 error errno -5
537 error zlib: unexpected end of file
538 verbose exit [ -5, true ]

Can you help me ?

Pode me ajudar ?

**Comment by gireeshpunathil** [comment]
what module you are trying to install?

**Comment by ALEXANDROGONSAN** [comment]
> what module you are trying to install?

I'm trying to install this here -> https://github.com/ivanseidel/IAMDinosaur
Eu estou tentando instalar isso aqui -> . . .

**Comment by gireeshpunathil** [comment]
ping @AlexandroGonSan - is this still an issue?

**Comment by AlexandroGonSan** [comment]
> ping @AlexandroGonSan - is this still an issue?

Eu conseguir resolver de uma forma alternativa mas penso que conseguiria resolver esse problema hoje normalmente .
