### ISSUE TITLE
How to call API in Node js ?

### ISSUE THREAD

**Issue by patelvanita360** [nodejs/help#1554]
Can any one help ma how can i call PHP api in node js  source ?

**Comment by gireeshpunathil** [comment]
how is your node.js and php servers placed? Do node.js act as a front end proxy for the PHP server or something else? If there is a PHP server, you could make a HTTP request to the server just like any other HTTP client would do. Knowing your topology more in detail will help answer precisely.

**Comment by patelvanita360** [comment]
Let me describe my case. 
I have build up web chat application in node js. Some API built in PHP to support chat. For both PHP API and NODE JS i am using ejabberd as a backend. 

Now i have built up one to one chat in node js using ejabberd. But facing issue to create groupchat module in node js.  So i have PHP API to support group chat which is also using ejabberd as backend. 

Now i want to plug that API in my webchat (nodejs)

**Comment by gireeshpunathil** [comment]
can you review SPHP module https://www.npmjs.com/package/sphp to see if it fits your purpose?

**Comment by gireeshpunathil** [comment]
ping @patelvanita360

**Comment by gireeshpunathil** [comment]
inactive, closing
