### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE problem in mysql (nodejs)

### ISSUE THREAD

**Issue by PpyMohan** [nodejs/help#1555]
Node.js Version : v8.12.0
OS : windows 10
express: "^4.16.4",
 mysql: "^2.15.0"

------------------------------------------------------------------
my code is :
--------------------------------------------------------------------
****
**const mysql = require('mysql');**

**var mysqlconnection = mysql.createConnection({**
    **host:'localhost',**
    **user: 'root',**
    **password:'password',**
    **database:'userdata'**
**});**

**mysqlconnection.connect((err)=>{**
    **if(!err) console.log('database connected..')**
    **else console.log('db not connected \n Error : '+JSON.stringify(err,undefined,2));**
**});**
............................................................................................................................................................
### **Error:**
..............................................................................................................................................................
While running : node file.js
 i am getting error like this but user name ,db name and password are correct can any one help me out...??????
 **Error : {
  "code": "ER_NOT_SUPPORTED_AUTH_MODE",
  "errno": 1251,
  "sqlMessage": "Client does not support authentication protocol requested by server; consider upgrading MySQL client",
  "sqlState": "08004",
  "fatal": true
}**

**Comment by gireeshpunathil** [comment]
not sure what the cause is, but looks like changing root user resolves the issue. Please review https://github.com/mysqljs/mysql/issues/1507 for more context

**Comment by gireeshpunathil** [comment]
I don't see any issues with node.js here

**Comment by ProjetosApps** [comment]
\o/ \o/ \o/ \o/ \o/
ALTER USER 'root'@'localhost' IDENTIFIED BY '';
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';

**Comment by gireeshpunathil** [comment]
ping @PpyMohan

**Comment by Deniernal354** [comment]
Hey I tried the fix ProjetosApps did but it did nothing except giving me an error in my sql syntax.

**Comment by kimeggler** [comment]
@Deniernal354 i think you forgot to put ALTER in front of your query.
This is how it shoult look like: 
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YourRootPasswo';

**Comment by gireeshpunathil** [comment]
ping @PpyMohan again - is this outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by Tamilselvanret** [comment]
Best Solution try this it will resolve:
You installed mysql server using "mysql installer"

1)open -> "mysql intsaller"

2)press reconfig mysql server

3)select left side "authentication method tab"

4)select radio button -->use legacy authentication method

5)now stop and restart the db

**Comment by JainamF** [comment]
> 
> 
> Best Solution try this it will resolve:
> 
> > You got this Error : **ER_NOT_SUPPORTED_AUTH_MODE**
> > this is error is mentioning when you install sql server you selected"strong authentication", but you set a weak password. You need to reset strong password or need to choose legacy authentication method.
> 
> > Follow these steps to choose legacy authentication method
> 
> You installed mysql server using "mysql installer"
> 
> 1)open -> "mysql intsaller"
> 
> 2)press reconfig mysql server
> 
> 3)select left side "authentication method tab"
> 
> 4)select radio button -->use legacy authentication method
> 
> 5)now stop and restart the db

it helped..........

**Comment by jfsilvah** [comment]
> Best Solution try this it will resolve:
> 
> > You got this Error : **ER_NOT_SUPPORTED_AUTH_MODE**
> > this is error is mentioning when you install sql server you selected"strong authentication", but you set a weak password. You need to reset strong password or need to choose legacy authentication method.
> 
> > Follow these steps to choose legacy authentication method
> 
> You installed mysql server using "mysql installer"
> 
> 1)open -> "mysql intsaller"
> 
> 2)press reconfig mysql server
> 
> 3)select left side "authentication method tab"
> 
> 4)select radio button -->use legacy authentication method
> 
> 5)now stop and restart the db

Thanks a lot, it worked for my using MySQL 8.0.18 with NodeJS

**Comment by Ankush-0694** [comment]
> Best Solution try this it will resolve:
> 
> > You got this Error : **ER_NOT_SUPPORTED_AUTH_MODE**
> > this is error is mentioning when you install sql server you selected"strong authentication", but you set a weak password. You need to reset strong password or need to choose legacy authentication method.
> 
> > Follow these steps to choose legacy authentication method
> 
> You installed mysql server using "mysql installer"
> 
> 1)open -> "mysql intsaller"
> 
> 2)press reconfig mysql server
> 
> 3)select left side "authentication method tab"
> 
> 4)select radio button -->use legacy authentication method
> 
> 5)now stop and restart the db

 THANK YOU VERY MUCH IT IS WORKING NOW

**Comment by haribabu499** [comment]
"code": "ER_ACCESS_DENIED_ERROR",
  "errno": 1045,
  "sqlMessage": "Access denied for user 'root'@'localhost' (using password: NO)",
  "sqlState": "28000",
  "fatal": true

**Comment by Archa-legacy** [comment]
> Best Solution try this it will resolve:
> 
> > You got this Error : **ER_NOT_SUPPORTED_AUTH_MODE**
> > this is error is mentioning when you install sql server you selected"strong authentication", but you set a weak password. You need to reset strong password or need to choose legacy authentication method.
> 
> > Follow these steps to choose legacy authentication method
> 
> You installed mysql server using "mysql installer"
> 
> 1)open -> "mysql intsaller"
> 
> 2)press reconfig mysql server
> 
> 3)select left side "authentication method tab"
> 
> 4)select radio button -->use legacy authentication method
> 
> 5)now stop and restart the db

thank you mann,,,its worked,,you r awsome

**Comment by MDFAYSALHOSSAIN019** [comment]
thanks a lot of
