### ISSUE TITLE
Invalid argument: family must be 4 or 6 with npm and debian

### ISSUE THREAD

**Issue by glalaj** [nodejs/help#1556]
* **Node.js Version**: v8.12.0
* **Npm Version**: 6.4.1
* **OS**: Debian GNU/Linux 9
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I am trying to install some simple npm modules for a nodejs project. No matter what modules I try to install, this error is thrown:

> npm ERR! Invalid argument: family must be 4 or 6
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-10-15T15_14_17_664Z-debug.log

The content of the log file (wcih didn't help me at all)

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'async' ]
> 2 info using npm@6.4.1
> 3 info using node@v8.12.0
> 4 verbose npm-session 1b4ff0f916b4759d
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly fetchPackageMetaData error for async@latest Invalid argument: family must be 4 or 6
> 8 timing stage:rollbackFailedOptional Completed in 7ms
> 9 timing stage:runTopLevelLifecycles Completed in 2063ms
> 10 verbose stack TypeError: Invalid argument: family must be 4 or 6
> 10 verbose stack     at lookup (dns.js:129:11)
> 10 verbose stack     at net.js:1091:5
> 10 verbose stack     at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
> 10 verbose stack     at lookupAndConnect (net.js:1090:3)
> 10 verbose stack     at TLSSocket.Socket.connect (net.js:1025:5)
> 10 verbose stack     at Object.exports.connect (_tls_wrap.js:1088:12)
> 10 verbose stack     at HttpsAgent.createConnection (https.js:115:22)
> 10 verbose stack     at HttpsAgent.createSocket (/usr/lib/node_modules/npm/node_modules/agentkeepalive/lib$
> 10 verbose stack     at HttpsAgent.createSocket (/usr/lib/node_modules/npm/node_modules/agentkeepalive/lib$
> 10 verbose stack     at HttpsAgent.addRequest (/usr/lib/node_modules/npm/node_modules/agentkeepalive/lib/_$
> 10 verbose stack     at new ClientRequest (_http_client.js:258:16)
> 10 verbose stack     at Object.request (http.js:38:10)
> 10 verbose stack     at request (https.js:243:15)
> 10 verbose stack     at fetch.Promise (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:$
> 10 verbose stack     at new Promise (<anonymous>)
> 10 verbose stack     at fetch (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:41:10)
> 11 verbose cwd /usr/local/src/magoware
> 12 verbose Linux 4.9.0-6-amd64
> 13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "async"
> 14 verbose node v8.12.0
> 15 verbose npm  v6.4.1
> 16 error Invalid argument: family must be 4 or 6
> 17 verbose exit [ 1, true ]

I read in some sources that the error could be related to faulty dns configuration. I am not a network administrator, all I can tell that the connection to the server via ssh is ok, and that it is possible to download / install from outside sources normally.

**Comment by gireeshpunathil** [comment]
probably related: https://github.com/nodejs/node/issues/8635

can you please run:
`node --trace /usr/lib/node_modules/npm/bin/npm-cli.js install async > output.txt`
and upload  `output.txt` to some public location (such as gist) for me to review?

**Comment by glalaj** [comment]
Thanks for the reply.
However further investigation won't be possible, the OS was reinstalled in the server and npm is working just fine now.
Should I close the issue or reference it as duplicate?

**Comment by StephanX** [comment]
This has also bitten me.  Docker build, Alpine host, Debian container image.  Have attached the output log. A more generic version and details below:
```curl -sL https://deb.nodesource.com/setup_${NODEJS_VERSION}.x | bash - \
    && apt-get install -y nodejs

root@c6f2cd7e8d71:~# cat /root/.npm/_logs/2018-10-26T18_05_06_271Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'ember-cli@2.13.2',
1 verbose cli   '-g' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose npm-session 9172e034c6c682ac
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for ember-cli@2.13.2 Invalid argument: family must be 4 or 6
8 timing stage:rollbackFailedOptional Completed in 8ms
9 timing stage:runTopLevelLifecycles Completed in 2464ms
10 verbose stack TypeError: Invalid argument: family must be 4 or 6
10 verbose stack     at lookup (dns.js:129:11)
10 verbose stack     at net.js:1091:5
10 verbose stack     at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
10 verbose stack     at lookupAndConnect (net.js:1090:3)
10 verbose stack     at TLSSocket.Socket.connect (net.js:1025:5)
10 verbose stack     at Object.exports.connect (_tls_wrap.js:1088:12)
10 verbose stack     at HttpsAgent.createConnection (https.js:115:22)
10 verbose stack     at HttpsAgent.createSocket (/usr/lib/node_modules/npm/node_modules/agentkeepalive/lib/_http_agent.js:265:26)
10 verbose stack     at HttpsAgent.createSocket (/usr/lib/node_modules/npm/node_modules/agentkeepalive/lib/agent.js:77:11)
10 verbose stack     at HttpsAgent.addRequest (/usr/lib/node_modules/npm/node_modules/agentkeepalive/lib/_http_agent.js:239:10)
10 verbose stack     at new ClientRequest (_http_client.js:258:16)
10 verbose stack     at Object.request (http.js:38:10)
10 verbose stack     at request (https.js:243:15)
10 verbose stack     at fetch.Promise (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:54:17)
10 verbose stack     at new Promise (<anonymous>)
10 verbose stack     at fetch (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:41:10)
11 verbose cwd /root
12 verbose Linux 4.14.69-0-virt
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "ember-cli@2.13.2" "-g"
14 verbose node v8.12.0
15 verbose npm  v6.4.1
16 error Invalid argument: family must be 4 or 6
17 verbose exit [ 1, true ]
```
details:
```root@c6f2cd7e8d71:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
root@c6f2cd7e8d71:~# uname -a 
Linux c6f2cd7e8d71 4.14.69-0-virt #1-Alpine SMP Mon Sep 10 19:55:02 UTC 2018 x86_64 GNU/Linux
root@c6f2cd7e8d71:~# node -v 
v8.12.0
root@c6f2cd7e8d71:~# npm -v 
6.4.1
```
install method:
```curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt-get install -y nodejs
```
output log: [output.tar.gz](https://github.com/nodejs/help/files/2521309/output.tar.gz)

**Comment by marsonya** [comment]
Kindly take a look at [issue #8635](https://github.com/nodejs/node/issues/8635) in the node repository and #1752. There is detailed discussion on this problem. Hope this helps.

I am closing this issue now. You can always reopen it incase there is something more to add to it.
