### ISSUE TITLE
Node.js need help getting anything to work while using Node on Flash Drive

### ISSUE THREAD

**Issue by ematt321** [nodejs/help#1557]
* **Node.js version: v8.12.0-win-x86**:
* **OS: Windows**:
I have been having a problem with node for a bit now. I have been using the portable version of node and whenever run cmd in Windows I have to give it the right path in order for it to run node. I use the path path=\tools\node-v8.12.0-win-x64;%path% and copy and paste from a notepad whenever I use node. Once I enter this path, it allows me to enter 'node' and gives '>' back. My problem is my node won't run properly. Whenever I try to enter commands it puts carrots underneath commands such as 'node --version'. I reinstalled the .zip version so I can use it on my flash drive and nothing still registers. 

```js
F:\tools>path=\tools\node-v8.12.0-win-x64;%path%

F:\tools>node
> node --version
node --version
              ^^^^^^^

SyntaxError: Unexpected identifier

> version
ReferenceError: version is not defined
> --version
ReferenceError: version is not defined

**Comment by richardlau** [comment]
When you run `node` without specifying a file it runs an interactive REPL where you can run JavaScript so it hasn't returned you to command prompt: https://nodejs.org/dist/latest-v8.x/docs/api/repl.html

To return to the command prompt from the REPL enter the `.exit` command.

**Comment by ematt321** [comment]
How should I test if node is running properly?

**Comment by richardlau** [comment]
Try the example on https://nodejs.org/dist/latest-v8.x/docs/api/synopsis.html?

**Comment by ematt321** [comment]
I tried it but I think I'm in the wrong folder or I'm doing something wrong with the folder system when I enter the pathway. Should I create a path when I enter the example? I think the path is severely messing me up.
