### ISSUE TITLE
Ubuntu 18.04: nodejs: symbol lookup error: nodejs: undefined symbol: uv_os_getpid

### ISSUE THREAD

**Issue by Antonboom** [nodejs/help#1559]
* **Node.js Version**: 8.x
* **OS**: Ubuntu 18.04
* **Scope**: after install

I run following commands and get error:
```
$ wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ nodejs --version
nodejs: symbol lookup error: nodejs: undefined symbol: uv_os_getpid
```

I tried build nodejs from source or download linux binary, but yarn and npm can not works with it :(

```
$ uname -a
Linux Telyshev 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ apt list --installed | grep libuv
libuv1/bionic,now 1.18.0-3 amd64 [installed,automatic]
libuv1-dev/bionic,now 1.18.0-3 amd64 [installed,auto-removable]
```

Any suggestions?

**Comment by Antonboom** [comment]
[This instruction](https://github.com/nodejs/help/wiki/Installation) helped me.
Everything worked with the downloaded binary, but the binary from the repository still does not work :(

**Comment by gireeshpunathil** [comment]
@Antonboom - this should be reported to node source. The official binary from Node.js does link with an external libuv, so this issue never occurs with that.

**Comment by gireeshpunathil** [comment]
asnwered, closing
