### ISSUE TITLE
share buffer object between javascript and native addon that write by c++?

### ISSUE THREAD

**Issue by csy2002** [nodejs/help#156]
Version:v5.1.1
Platform:window7 x86

can i share buffer object between javascript and native addon that write by c++?
try belowing, but failed;

c++ addon:
```c++
void setBuffer(const v8::FunctionCallbackInfo<v8::Value>& args) {
    Isolate* isolate = args.GetIsolate();
    char* jsBuffer = node::Buffer::Data(Local<Object>::Cast(args[0]));
    memcpy(jsBuffer, "bbbbbbbbbb", 10);
    printf("native addon output:%s\n", jsBuffer);
}
```
javascript:
```js
var native = require('nativeAddon');
var globalBuffer = new Buffer(20).fill('a');
native.setBuffer(globalBuffer); //set globalBuffer to 'bbbbbb....', using memcpy
console.log("js output:" + globalBuffer);
//////////////////////////////////////////
```
result:
native addon output: bbbbbbbbbbaaaaaaaaaaaaaaaa
js output: aaaaaaaaaaaaaaaaaaaaaaaaaa

////////////////////////////////////////
but, globalBuffer not change, why?

**Comment by bnoordhuis** [comment]
That should work, at least in theory.  Try upgrading to v5.11.0.

**Comment by csy2002** [comment]
can get the right answer in node;
