### ISSUE TITLE
How to pipe the output forked/cluster processes into the master stdout/stderr

### ISSUE THREAD

**Issue by IonicaBizau** [nodejs/help#1560]
When doing `worker = cluster.fork()` I would like to be able to forward the stdout and stderr streams into the master Node.js process.

How can I do that?

I tried doing:

    worker = cluster.fork();
    worker.process.stdout.pipe(process.stdout)
    //             ^ this is null

A workaround would be to use messages, but I want to be able to stream content.

    worker.on("message", function(msg){
      console.log("Master says:" + msg);
    });
    ...
    worker.send({message:'hello'});

---

How can I access the stdout of the forked process/cluster?

[**Stackoverflow Question**](https://stackoverflow.com/q/52846069/1420197)

**Comment by ORESoftware** [comment]
try this:

```js
worker.stdout.pipe(process.stdout);
worker.stderr.pipe(process.stderr);
```

**Comment by IonicaBizau** [comment]
@ORESoftware Sorry, but there are no `stdout` or `stderr` properties on `worker`.

**Comment by ORESoftware** [comment]
sorry, my bad. the workers are launched in a separate node.js process from master. do you get it? By default, their stdout/stderr should go to the parent process.

However, I see that worker.process.stdout and worker.process.stderr are defined:

<img width="736" alt="screenshot 2018-10-17 20 39 36" src="https://user-images.githubusercontent.com/11139560/47130103-ecfab180-d24c-11e8-9254-74830d70e932.png">

**Comment by IonicaBizau** [comment]
@ORESoftware I'm not sure what I'm missing, but it simply doesn't work:

```
$ cat t.js 
#!/usr/bin/env node

'use strict';

const Cluster = require('cluster')

Cluster.setupMaster({
    silent: true
});

if (Cluster.isMaster) {
    const w = Cluster.fork();
    console.log('this is the master process:', process.pid);
    w.process.stdout.pipe(process.stdout);
    setInterval(() => {}, 1000);
} else {
    console.log('this is the worker process:', process.pid);
}
$ node t.js 
this is the master process: 67023
^C
```

**Comment by IonicaBizau** [comment]
Figured it out: `setupMaster` should be called in the master process only:

```js
#!/usr/bin/env node

'use strict';

const Cluster = require('cluster')

if (Cluster.isMaster) {
    Cluster.setupMaster({
        silent: true
    });
    const w = Cluster.fork();
    w.process.stdout.pipe(process.stdout);
    console.log('this is the master process:', process.pid);
    setInterval(() => {}, 1000);
} else {
    console.log('this is the worker process:', process.pid);
}
```

And it works now!

Thanks a lot! If you like, you can post an answer on Stackoverflow too!

**Comment by ORESoftware** [comment]
for sure np, what are you using the `cluster` module for by the way? usually cluster module is the first step towards scaling, but when you run servers on AWS, Heroku etc, they will scale and make full use of the hardware.

**Comment by IonicaBizau** [comment]
That's a good question—yes, for scaling. I was using it on my cloud server, but yesterday I started using `pm2`—so, I'm not sure if `pm2` will do the same thing like `cluster` does.

**Comment by ORESoftware** [comment]
yeah this is important. on some systems, cluster might be useful. but on most modern hosting platforms, you will run a server with docker, and basically it will run like 5-10 docker containers on one machine, which means you will use the hardware to the max. So you don't need cluster. You just need one node.js server per docker container. 

Like this:

1:1   - node server : docker container
8:1 - docker containers: machine

no need for the cluster module...you can do your own research, but cluster module probably shouldn't have been included in core, I don't know what the purpose is for it.

**Comment by IonicaBizau** [comment]
Thank you very much!
