### ISSUE TITLE
Ensure stdio lines from subprocesses goes to receiver atomically

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1561]
Say I have this:

```js
[1,2,3].forEach(v => {
  const k = cp.spawn('node foo.js');
  k.stdout.pipe(process.stdout);
  k.stderr.pipe(process.stderr);
});
```

_I am concerned about this issue:_
https://unix.stackexchange.com/questions/476080/what-prevents-stdout-stderr-from-interleaving

What I am thinking of doing is something like this:

```js
const stdoutTransform = new Transform({transform:(chunk, enc, cb) => cb(String(chunk))});
stdoutTransform.pipe(process.stdout);

const stderrTransform = new Transform({transform:(chunk, enc, cb) => cb(String(chunk))});
stderrTransform.pipe(process.stderr);

[1,2,3].forEach(v => {
  const k = cp.spawn('node foo.js');
  readline.createInterface({input: k.stdout}).on('line', l => stdoutTransform.write(l + '\n'));
  readline.createInterface({input: k.stderr}).on('line', l => stderrTransform.write(l + '\n'));
});

```

does this make any sense?

**Comment by gireeshpunathil** [comment]
hi @ORESoftware !

I guess what we want to achieve is:
 - the parent's prints should be meaningful at line boundaries
 - no interleaved messages appear in the same line
 - messages can clutter across lines: i.e, C1L1, C2L1, C2L2, C3L1, etc. where C is a child and L is a line.

Is that so? Then I guess we did not solve the problem, but shifted it from stdout.write to Transform.write ? The same chunking / buffering that the std*.write was subjected to, will affect the new stream write as well?

**Comment by ORESoftware** [comment]
yeah but the `rl.on('line')` thing for each child stream ensures that the writes don't interleave?

**Comment by gireeshpunathil** [comment]
@ORESoftware - sorry for the late response. yes, I see what you are saying, and your transformer make sense to me!

**Comment by gireeshpunathil** [comment]
@ORESoftware - is there anything outstanding here, or are we good to close?
