### ISSUE TITLE
More efficient line parser for streams

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1563]
I have imported:

```js
const readline = require('readline');
```

I have this method:

```js
  combine(readable: Readable) {

    readline.createInterface({
      input: readable
    })
      .on('line', l => {
        this.trans.write(l + '\n');
      });
  }
```

this should ensure that I get a whole line of output from the readable stream input. My question is, is there a better way or simpler way to do this, instead of using `readline.createInterface()`?

**Comment by gireeshpunathil** [comment]
hi @ORESoftware - in core I don't think we have a better interface than this, I am aware of npm modules that do this as their main exported feature, for example:
https://www.npmjs.com/package/linestream
https://www.npmjs.com/search?q=linereader

**Comment by gireeshpunathil** [comment]
ping @ORESoftware

**Comment by ORESoftware** [comment]
hey thanks, yeah np I can work with this

**Comment by gireeshpunathil** [comment]
closing then, thanks!
