### ISSUE TITLE
module.js:549 - Error: Cannot find module '/code/pelias.json'

### ISSUE THREAD

**Issue by ajithcofficial** [nodejs/help#1567]
node -v: v8.12.0
npm -v: 6.4.1
OS : CentOS Linux release 7.5.1804 (Core) 

I was setting up a pelias geocoding server using docker and docker-compose as explained in [https://github.com/pelias/docker/blob/master/README.md](url) . I successfully completed the all steps till starting up the elastic search service. then when I type command 

> pelias download all

it shows an error message as bellow

> 
> [root@barinlab portland-metro]# pelias download all
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module '/code/pelias.json'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at getConfig (/code/pelias/openstreetmap/node_modules/pelias-config/index.js:54:21)
>     at Object.generate (/code/pelias/openstreetmap/node_modules/pelias-config/index.js:28:18)
>     at Object.<anonymous> (/code/pelias/openstreetmap/util/download_data.js:7:43)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
> [root@barinlab portland-metro]# 

I tried reinstalling npm and nodejs but still I am not able to fix this problem. Somebody please help.
@gireeshpunathil

**Comment by yathamravali** [comment]
@ajithcofficial 

No results matched this https://github.com/pelias/docker/blob/master/README.md

**Comment by gireeshpunathil** [comment]
@ajithcofficial - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
