### ISSUE TITLE
Debugging Gulp using node fails in Chrome

### ISSUE THREAD

**Issue by rejkid** [nodejs/help#1570]
* **Node.js Version**: v8.12.0
* **OS**: Windows 7 64 Bit
* **Scope (install, code, runtime, meta, other?)**: Runtime-Debug
* **Module (and version) (if relevant)**: Gulp 4.0

Hi,
I have followed the article [https://stackoverflow.com/questions/40033298/how-to-debug-a-gulp-task](url) to debug my gulp file using chrome with the help of nodejs. My gulpfile.js looks like this:

```js
var gulp = require('gulp');
// Gulp 4
debugger;
gulp.task('cleanTemp', function (done) {
	console.log('Hello world!');
	done();
});
```

When I execute the command from my working folder:
`node --inspect-brk ./node_modules/gulp/node_modules/.bin/gulp cleanTemp`

I am getting an error:
```
Debugger attached.
C:\Workspace\Projects\Eclipse\CommsProc\Source\HttpServer\node_modules\gulp\node_modules\.bin\gulp:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Waiting for the debugger to disconnect...
```

What am I doing wrong. What does this message mean: `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`

Kind Regards,
Janusz

**Comment by davewilton** [comment]
I got this error in windows. I had to supply node_modules/gulp/node_modules/.bin/gulp**.js**

**Comment by gireeshpunathil** [comment]
@rejkid - I am unable to locate the UNIX script in the module. May be that the latest versions do not include one, and they have merged everything to gulp.js for platform neutrality. Could you try once again, with a fresh installation of gulp module? thanks.

**Comment by gireeshpunathil** [comment]
ping @rejkid

**Comment by gireeshpunathil** [comment]
inactive, closing
