### ISSUE TITLE
How many threads does Node actually create?

### ISSUE THREAD

**Issue by nairihar** [nodejs/help#1571]
* **Node.js Version**: v8.11.3
* **OS**: Macos
* **Scope (install, code, runtime, meta, other?)**: runtime

Hi, I am trying to understand how many threads create Node.js simple application.

this signle line creates 6 threads.
```js
setInterval(function() {}, 1000);
```

So as I understood, V8 has own thread pool whose size is 4.
Also libuv thread pool is not initialized so the libuv's thread poll size is 0.
EventLoop uses one thread.

But what about the last thread?
Where it's used?

**Comment by devsnek** [comment]
it has at least: 4 for the libuv event loop, 4 for running background tasks for V8, and 1 for scheduling delayed background tasks for V8.

**Comment by nairihar** [comment]
Yes, I know that that's why I wrote: "Also libuv thread pool is not initialized so the libuv's thread poll size is 0."

**Comment by nairihar** [comment]
@devsnek so finally there is 5 threads for V8, and one for event loop, right?
