### ISSUE TITLE
Node 11.0 Finish box off screen

### ISSUE THREAD

**Issue by highstream** [nodejs/help#1575]
Just finished installing Node 11.0 on a Win 10 Pro x64 (1803) machine. The final window, the one that shows the "Finish" button, was 90% off screen to the top left on a 24" 1920x1200 screen, set at 115% magnification. I was unable to move it, but had to use Task Mgr to close it. Never happened before with Node.

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by gireeshpunathil** [comment]
ping @highstream - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by BlueCannonBall** [comment]
> ping @highstream - is this still an issue?

Yes, this is still an issue.

**Comment by carlos-chinchilla** [comment]
Had the same problem right now

**Comment by Pulz-TCP** [comment]
I have experienced this issue.

**Comment by highstream** [comment]
I haven't experienced it since the initial occurrence

**Comment by bunchofkeysdev** [comment]
> I have experienced this issue. Hitting enter gets past it.

i just experienced it ...and hitting enter does the trick ...thanks

**Comment by PeterCullenBurbery** [comment]
I have experienced the Node JS installer moving to the left of the screen, where I can't control it with the mouse. I tried using Alt-Tab but couldn't.

**Comment by gcnTo** [comment]
Still happens.

**Comment by IsabelBody** [comment]
this is happened to me on 2 separate laptop installs in the last 2 days. so funny

**Comment by avivkeller** [comment]
No. We don't provide any guarantees for EoL Node.js versions

**Comment by frahmed99** [comment]
Just found the best way to do it. Press "Alt+Space". Then select "move". This will enable the window to be moved to where you like.
