### ISSUE TITLE
Node.js logic not running as intended

### ISSUE THREAD

**Issue by ematt321** [nodejs/help#1576]
* **Node.js Version**:v8.12.0
* **OS**:Windows

If I try to run this code in cmd on windows, it outputs a result of 33100. Since I input 10, it should perform the else statement and the output should be 25000.

```js
function tax (income){
	if(income=100000){
		var result1= income*0.331
		return result1
	}
	else if (income < 100000) {
		var result2= income*0.25
		return result2
}
}
console.log (tax (10));
```

**Comment by ORESoftware** [comment]
income === x

not 

income = x

**Comment by ematt321** [comment]
Whenever I run the code it says "unexpected token if"

**Comment by ORESoftware** [comment]
sorry you need the parentheses

if (x === y) {}

you need == or === for comparison...and === is almost always better than ==.

**Comment by ematt321** [comment]
That's what I have but it still doesn't work for some reason

**Comment by gireeshpunathil** [comment]
$ cat 1576.js 
```js
function tax (income) {
  if (income >= 100000) {
    var result1 = income * 0.331;
      return result1;
  }
  else if (income < 100000) {
    var result2 = income * 0.25;
      return result2;
  }
}
console.log (tax (process.argv[2] + 0));
```

```
$ node 1576.js 1
2.5
$ node 1576.js 10
25
$ node 1576.js 100
250
$ node 1576.js 1000
2500
$ node 1576.js 10000
33100
$ node 1576.js 100000
331000
$ node 1576.js 1000000
3310000
```

I am not a tax man, but looks like you want 33.1% tax for any amount exceeding a hundred thousand, not just for that amount? if so you want to go with `>=` , not `=`. ?

**Comment by ematt321** [comment]
I'm trying to make it so those earning $100,000 are taxed at 33.1% and those earning less than $100,000 are taxed at 25%.

**Comment by ematt321** [comment]
But I got it when I implemented some syntax corrections so thank you!
