### ISSUE TITLE
Unable to uninstall previous installed nodejs

### ISSUE THREAD

**Issue by askshinde** [nodejs/help#1577]
I am using windows10 and had use partitioned drive E for my node js apps. Later I formatted the E drive and installed ubuntu16. Now, I have installed wamp on my windows os in D drive. And when I try to install nodejs, the installer fails to install showing to remove previously installed nodejs in E:

Please help what to do

**Comment by gireeshpunathil** [comment]
ping @askshinde - is this still pending?

**Comment by gireeshpunathil** [comment]
inactive, closing
