### ISSUE TITLE
setTimeout group in Node.js, Node -> libuv

### ISSUE THREAD

**Issue by nairihar** [nodejs/help#1578]
Hi, as I understood Node.js creates a group of timeouts, and if there are multiple timeouts with the same timeout number then libuv will work one time for that group.

I have read `timers.js` from Node.js source, and I found a function named `listOnTimeout` which calls all functions from the group. There is LinkedList and each Node has `_onTimeout` function, so it's our callback.

But when I trying to run this code, sometimes it returns 2,1,3 which is the opposite of logic above.

```js

setImmediate(() => {
  setTimeout(() => {
    console.log(2);
  }, 0);
  setTimeout(() => {
    console.log(3);
  }, 0);
  setImmediate(() => {
    console.log(1);
  });
});

```

Could you please explain me, why grouping doesn't work for this case?

<img width="210" alt="screen shot 2018-10-30 at 2 50 07 pm" src="https://user-images.githubusercontent.com/15065065/47713200-1eaf4780-dc53-11e8-9c05-54ac098e61e2.png">

**Comment by nairihar** [comment]
One reason about which I think is, EventLoop calls processTimers very fast two times.

**Comment by nairihar** [comment]
The only reason why I think it happens is because EventLoop calls processTimers very quick two times

**Comment by Eomm** [comment]
Hi,
you should check here:
https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/

In your case:
> For example, if we run the following script which is not within an I/O cycle (i.e. the main module), the order in which the two timers are executed is non-deterministic, as it is bound by the performance of the process

that is just your case.

And if you add an I/O you will notice the event loop queue:
```js
const fs = require('fs')

setTimeout(() => {
  console.log('timeout outside')
}, 0)
setImmediate(() => {
  console.log('immediate outside')
})

fs.readFile(__filename, () => {
  setTimeout(() => {
    console.log('timeout')
  }, 0)
  setImmediate(() => {
    console.log('immediate')
  })
})
```

**Comment by nairihar** [comment]
But what if sane timeout grouped?
I have 2 timeouts with same argument number.

**Comment by nairihar** [comment]
Your example is other case.

**Comment by Eomm** [comment]
> But what if same timeouts are grouped?
> I have 2 timeouts with same argument number.

I don't know how the `setImmediate` impact on the grouped timeouts, but is that the cause of non-deterministic execution.
About this, I want to show you an old question without reply that I asked:
https://stackoverflow.com/questions/53412160/weird-result-testing-operation-per-sec

If you try this:
```js
const bench = require('fastbench')
bench([
  function timeout(done) {
    const array = []
    setTimeout(() => { array.push(1) }, 0);
    setTimeout(() => { array.push(2) }, 0);
    setTimeout(() => {
      if (array[0] === 1 && array[1] === 2) {
        done()
      }
    }, 50);
    // setImmediate(() => { array.push(3) });
  }
], 100)()
```
It will execute correctly, but if you un-comment the setImmediate it will not executes properly.

Will we unveil this `setInterval` mystery? 💪😎

**Comment by nairihar** [comment]
My understanding is that, setImmediate works after I/O process.

If timeouts are grouped then definitely it should log two timeouts behind each other.

But in logs, you can see immediate log sometimes logged in middle of timeouts log.

That's the confusing part for me.



/cc @Eomm @Fishrock123

**Comment by apapirovski** [comment]
This makes complete sense. 0 timeout is the same as 1. Between setting the first timeout and the second, time can pass.

Also immediate can run first depending on how fast the loop runs.

**Comment by nairihar** [comment]
Thanks, @apapirovski, I thought so.
