### ISSUE TITLE
Question about promises

### ISSUE THREAD

**Issue by bluejellybean** [nodejs/help#158]
Is there a way to not have to type 'return new Promise(( resolve, reject ) => {' every single function?

I almost want to get rid of all callbacks from javascript hah!

**Comment by liam4** [comment]
Nope - promises always need a callback function as the argument.

If you find you're using repetitive, similar promises, you could make the promise creating code into a function, though.

For example, you could change this:

```js
new Promise((resolve, reject) => { setTimeout(resolve, 1000) })
  .then(function() { /* do something */ })
  .then(function() { return new Promise(function() { setTimeout(resolve, 1000) }) })
  .then(function() { /* do something */ })
```

Into this:

```js
function delay(ms) {
  return function() {
    return new Promise(function(resolve, reject) {
      setTimeout(resolve, ms)
    })
  }
}

delay(1000)()
  .then(function() { /* do something */ })
  .then(delay(1000))
  .then(function() { /* do something */ })
```

In the future you'll be able to use async/await to make the code generally simpler:

```js
function delay(ms) {
  return new Promise(function(resolve, reject) {
    setTimeout(resolve, ms)
  })
}

async function main() {
  await delay(1000)
  /* do something */
  await delay(1000)
  /* do something */
}

main()
```

But async/await isn't part of the standard yet, and isn't implemented into Node.js for now anyways (though you can use things like [Babel](babeljs.io) to compile programs that use features like async/await).

You can read more about async/await [here](https://www.twilio.com/blog/2015/10/asyncawait-the-hero-javascript-deserved.html).

**Comment by bluejellybean** [comment]
Interesting thank you, still the bit of boilerplate but feels much more clean.

**Comment by saadq** [comment]
There is a [pull request](https://github.com/nodejs/node/pull/5020) pending for adding Promises to node's core. 

So if this pull request lands, instead of doing

```javascript
const { readFile } = require('fs')

readFile('blah.txt', (err, data) => {
  ...
})
```

You'll be able to do

```javascript
const { readFile } = require('fs').promise

readFile('blah.txt').then(data => {
  ...
})
```

They aren't getting rid of the callback API though, so if you want to use promises, you'll have to specify that `.promise` at the end. Although there's talk about it being changed to maybe use submodules

```javascript
const { readFile } = require('fs').promise
```

into

```javascript
const { readFile } = require('fs/promise')
```

Either way, I'm really hoping the pull request gets through.

**Comment by liam4** [comment]
And for now, there's [`fs-promise`](https://www.npmjs.com/package/fs-promise), which is basically the same thing but as an ordinary node module you can use right now:

```js
const { readFile } = require('fs-promise')
```

**Comment by lordKnighton** [comment]
@bluejellybean any progress with this issue?
