### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by Merith-TK** [nodejs/help#1582]
* **Node.js Version**:
Not installed
* **OS**:Ubunt Server 16.04
[npm-debug.log](https://github.com/nodejs/help/files/2540621/npm-debug.log)
this is the document ``npm install node`` said to give with any errors

**Comment by gireeshpunathil** [comment]
while the `npm install` is trivial, the steps taken for installing `node` itself as a node module is internal to the module itself, not in the purview of node. I had a look at the npm-debug.log, but should admit that I am unable to follow what is being tried, and what failed. It is best supported by its maintainers, which seems to be https://github.com/aredridel/node-bin-gen

**Comment by Merith-TK** [comment]
Damn, almost a year later, and I get a reply.

I am. Kinda glad to say my knowledge has increased over the years so I can
get this working on my own for the most part.

**Comment by gireeshpunathil** [comment]
@Merith-TK - glad to know that you are able to resolve this. Closing the issue.
