### ISSUE TITLE
require throws error

### ISSUE THREAD

**Issue by kinfinity** [nodejs/help#1583]
* **Node --version: 10.11.0**:
* **windows 10 pro 64bit(10.0 build 17134)**:
* **Runtime**:
* require/ fs [ fd] : 

my code isn't working as it ought to ... Previously i built and ran without any issues but not anymore. 
it throws Error TypeError [ERR_INVALID_ARG_TYPE]: The "fd" argument must be of type number. Received type string.
```js
// On conditional require for {service}.js files Implementaion of .proto service functions
const wrapper = {

    requireF: (modulePath) => {

        try {

            return require(modulePath);

        } catch (err) {

            console
                .log(`requireF(): The file ${modulePath} could not be loaded :: ${err}`);

            return false;

        }

    }

};
```

**Comment by kinfinity** [comment]
Fixed. Debugged and traced the source of the error. Thanks.

**Comment by Connum** [comment]
Mind sharing the source of the error and the fix?

**Comment by colinodell** [comment]
In my case, I was using `fs.readSync()` when I should have been using `fs.readFileSync()` instead.

**Comment by goodstemy** [comment]
@colinodell had same issue on 'fs.writeSync()' usage but should be 'fs.writeFileSync()'. Maybe solve problem for somebody

**Comment by Necesku** [comment]
> @colinodell had same issue on `fs.writeSync()` usage but should be `fs.writeFileSync()`. Maybe solve problem for somebody

"Maybesolve problem for somebody"
It fixed the problem for me! Thanks!
