### ISSUE TITLE
Nodejs C++ Addons Question

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/help#1584]
* **Node.js Version**: v10.12.0
* **OS**: Windows 10 Home Single Language, version 1803, build 17134.345
* **Scope (install, code, runtime, meta, other?)**: Other (I think?)
* **Module (and version) (if relevant)**: This is just about V8 and C++ Addons

I want to know if the C++ code that I have can easily be made into a Nodejs C++ Addon.  The code is on GitHub here: https://github.com/DragonOsman/currency_converter .  And if so, what changes (if any) do I need to make?

**Comment by NickNaso** [comment]
Hi @DragonOsman ,
in my opinion you can wrap the code inside the function that execute the conversion on a Native Add-on then you can create a server using the Node.js **http** module or something like expressjs or other Node.js web framework to handle the http request.
The Native module at he end will be just an object that will expose function to execute the conversion of the currency.
Below I report what I exposed using expressjs:

```js
'use strict'
const express = require('express')
const conversion = require('bindings')('your-native-addon')
const app = express()
app.get('/convert', (req, res, next) => {
    try {
        conversion.convert(...)
    } catch (err) {
        next(err)
    }
})
app.listen(8080)
```
You can create a simple Native Add-On that expose the convert function like reported in this example:
https://github.com/nodejs/node-addon-examples/tree/master/2_function_arguments/node-addon-api

**Comment by DragonOsman** [comment]
Thanks for the reply.

So I can't expose the networking functionality that my code is using to Node.js?

**Comment by NickNaso** [comment]
If you expose networking functionality it will became more complicated you cannot use them without consider how all the Node.js runtime works so at the end the most simple thing is to use the networking functionalities that Node.js has and call all the business logic provided by your C++ code.

**Comment by DragonOsman** [comment]
I see.  

I wanted to use this as an alternative if I can't build my Docker image.  I want to deploy it to Heroku and they don't run Docker images as root user.  What I tried to do was to push an Ubuntu image with sudo installed to the Docker registry and then pull it in my Dockerfile image.  But when I try to add my user to the sudoers group and use sudo, I get an error saying "sudo: not found".  

Is it okay for me to link the Dockerfile here or should I just keep to the Docker support and community forums for this (I contacted support already)?

**Comment by DragonOsman** [comment]
@NickNaso I need to know how to expose the networking functionality of my C++ app to Node.js, so could you point me to what I need to read to understand how to Node.js runtime and everything works?  I'm having some problem with CMake in the Docker image I'm trying to build and I've asked about it, but I also want to do this just in case.  

For some reason, in my Dockerfile, I can't create folders in my home directory.  I keep "Permission denied" errors.  I have to use sudo.  You wouldn't happen to know how to fix this, would you?

**Comment by DragonOsman** [comment]
@NickNaso I made my C++ webserver app code asynchronous.  If I want to make it into a Node.js C++ Addon, do I take out `main` and put all of the other functions inside a namespace for the module (called `currency_converter_module` or something like that), like how it's done [here](https://nodejs.org/dist/latest-v11.x/docs/api/addons.html) in this tutorial?  My C++ code is updated and is [here](https://github.com/DragonOsman/currency_converter/blob/master/currency_converter.cpp).

**Comment by gireeshpunathil** [comment]
is there anything pending on this issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
