### ISSUE TITLE
create-react-app issue

### ISSUE THREAD

**Issue by Badereedine-Hadef** [nodejs/help#1586]
first time working with react i need your help please

node -v: v8.11.3
npm -v: 5.6.0

I Run:
create-react-app first-app

this mess tell me to waite few sec
Creating a new React app in C:\Users\MAD_MAX\Desktop\New folder (2)\first-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

the this err shows up 

npm ERR! code EINTEGRITY
npm ERR! sha1-8d8kEbcUpOCNG9w0PAoIicaIIQ8= integrity checksum failed when using                                                               sha1: wanted sha1-8d8kEbcUpOCNG9w0PAoIicaIIQ8= but got sha1-RAyRT4FbIbPrPjoMbvuS                                                              0euwmcY=. (1959 bytes)

**Comment by yathamravali** [comment]
@Badereedine-Hadef 
I'm able to create a react app on windows10
```
C:\Users\Administrator>node -v
v8.11.3
C:\Users\Administrator>npm --v
5.6.0
C:\Users\Administrator>npm install create-react-app
C:\Users\Administrator>npm install
C:\Users\Administrator>npx create-react-app first1-app
Creating a new React app in C:\Users\Administrator\first1-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

+ react@16.8.2
+ react-scripts@2.1.5
+ react-dom@16.8.2
added 1814 packages in 177.516s

Success! Created first1-app at C:\Users\Administrator\first1-app
```
Try `npm cache verify`
`npm cache clean --force`
Then re-run
`npm install -g create-react-app`

**Comment by gireeshpunathil** [comment]
ping @Badereedine-Hadef

**Comment by gireeshpunathil** [comment]
inactive, closing
