### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by scalesan** [nodejs/help#1588]
I've downloaded nodejs v 11.1 multiple times today.  This version keeps giving me npm v 5.5.1 which is wrong. It's supposed to come with 6.4.1. I'm trying to do a bootcamp and can't complete it until this is fixed. Can you look into it? Thank you.

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by gireeshpunathil** [comment]
@scalesan - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing
