### ISSUE TITLE
Unexpected token 'else'

### ISSUE THREAD

**Issue by ematt321** [nodejs/help#1589]
I'm having trouble with if/else statements in general and I think something is wrong with my syntax. It appears to read all of the 'if' statements fine but once it starts reading the else statements it gives me an unexpected token. 
Note: It is supposed to take what you put in console.log and output the income and multiply it by the decimal of a specific range created by the if/else statements. Its problem is now with '{' next to the noted line.
```js
var multiTax = function (income) {
		if (income <= 500000) {
			income = income*0.35;
		return income;}
			if (income < 200000) {
				income = income*0.32;
			return income;}
				if (income < 157501) {
					income = income*0.24;
				return income;}
					if (income < 82501) {
						income = income*0.22;
					return income;}
				//             if (income < 38701) {
							income = income*0.12;
							return income;}
							if (income < 9526) {
								income = income*0.10;
							return income;}
						else(income >= 38701) {
							income = income*0.22;
							return income;}
					else {income = income*0.24;
					return income;}
				else {income = income*0.32
				return income;}
			else {income = income*0.35;
			return income;}
		else {income = income*0.37;
		return income;}							
}
	console.log (multiTax(500001));

**Comment by vsemozhetbyt** [comment]
1. `else(income >= 38701)` : there cannot be any parentheses after `else`.
2. `else {income = income*0.24;` : there can be only one `else` after `if` in the same level.

**Comment by Hakerh400** [comment]
> It is supposed to take what you put in console.log and output the income and multiply it by the decimal of a specific range created by the if/else statements.

It's not clear what the code you posted is supposed to do. If you explain precisely which `income` range should be multiplied with which number, I can help you rewrite your code.

> there cannot be any parentheses after else

That's not true in general.

**Comment by ORESoftware** [comment]
@Hakerh400 @ematt321 I don't know what kinda crack ppl been smoking recently, but this is the pattern you want to use:

```js
var multiTax = function (income) {
  if (income <= 500000) {
    income = income * 0.35;
    return income;
  }
  if (income < 200000) {
    income = income * 0.32;
    return income;
  }
  if (income < 157501) {
    income = income * 0.24;
    return income;
  }
  if (income < 82501) {
    income = income * 0.22;
    return income;
  }
  if (income < 38701) {
    income = income * 0.12;
    return income;
  }
  if (income < 9526) {
    income = income * 0.10;
    return income;
  }
  else if (income >= 38701) {
    income = income * 0.22;
    return income;
  }
  else {
    income = income * 0.24;
    return income;
  }
};

console.log(multiTax(500001));

```

**Comment by vsemozhetbyt** [comment]
@Hakerh400 Sorry, more accurate: there cannot be parentheses between `else` and a condition block for this `else`.

**Comment by ORESoftware** [comment]
@vsemozhetbyt yes that's right, but that was not the only problem with the OP :)

**Comment by refack** [comment]
@ORESoftware Please let's keep the language civil. IMHO there's no need to be sarcastic when you are correct ;)

**Comment by ematt321** [comment]
![image](https://user-images.githubusercontent.com/43119960/47970417-155b1c00-e053-11e8-8c75-8564289da5af.png)
The task was to return the amount of individual tax for a given income and tax rate

**Comment by Hakerh400** [comment]
@ematt321 Thanks. Then you probably need something like this:

```js
function multiTax(income){
  if(income > 500000) return income * 0.37;
  if(income > 200000) return income * 0.35;
  if(income > 157500) return income * 0.32;
  if(income > 82500) return income * 0.24;
  if(income > 38700) return income * 0.22;
  if(income > 9525) return income * 0.12;
  return income * 0.10;
}

log(multiTax(500001));
```

**Comment by ematt321** [comment]
Sorry to drag this out but for some reason I still get an unexpected token 'else' when I use the updated code below.
function multiTax (income) {
	if (income > 500000) {return income*0.37;}
		if (income > 200000) {return income*0.35;}
			if (income > 157500) {return income*0.32;}
				if (income > 82500) {return income*0.24;}
					if (income > 38700) {return income*0.22;}
						if (income > 9525) {return income*0.12;}
						else {return income*0.10;}
					else {return income*0.12;}
				else {return income*0.22;}
			else {return income*0.24;}
		else {return income*0.32;}
	else {return income*0.35;}
}
console.log(multiTax(82500));

**Comment by Hakerh400** [comment]
Why complicating? Simply copy-paste my code, that is exactly what you need, don't add `else` keywords.

**Comment by ematt321** [comment]
Trying to get a better handle using if/else for future problems. But thank you it runs good
