### ISSUE TITLE
Where can I get the official t-shirt/stickers with the new nodejs logo?

### ISSUE THREAD

**Issue by stevemao** [nodejs/help#159]
I asked this question a few months ago. I'm asking here again coz I really need them!! 😄

**Comment by martinheidegger** [comment]
@yosuke-furukawa Do we have stickers at hexi?

**Comment by lordKnighton** [comment]
CC @mikeal 

--

my apologies for pinging you in here, but I couldn't think of anyone else better suited to give this question a shot.

**Comment by stevemao** [comment]
CC @rvagg @jbergstroem

**Comment by yosuke-furukawa** [comment]
@martinheidegger yes, of course!
[hexi.pics](https://hexi.pics) can deliver stickers to worldwide.

**Comment by stevemao** [comment]
@yosuke-furukawa Looks like it only has the old logo

**Comment by jbergstroem** [comment]
hm; good question. thinking people from @nodejs/evangelism might know.

**Comment by stevemao** [comment]
cc @gtewallace

**Comment by bnb** [comment]
I've not seen one yet. I tried adding it to hexi.pics, but it didn't quite work. Here's a 600DPI verison  of the new Hex, if someone can make it into a sticker:
![nodejs-new-pantone-black hex](https://cloud.githubusercontent.com/assets/502396/15795717/35cad74a-29c2-11e6-83c7-367107185aec.png)

**Comment by martinheidegger** [comment]
https://hexi.pics/items/2196daf31f6bf65fbd603e13683fd97c

**Comment by bnb** [comment]
From @ag_dubs and @mikeal: https://mobile.twitter.com/mikeal/status/738882725994627072

**Comment by lordKnighton** [comment]
Closing for now, feel free to reopen & continue conversation.

**Comment by stevemao** [comment]
@bnb @ashleygwilliams and @mikeal is the official swag store open?

**Comment by jsynowiec** [comment]
Hexi is now closed. Any updates?
