### ISSUE TITLE
NPM reinstall problem on Windows10 (Can't run it)

### ISSUE THREAD

**Issue by ahsanpervaiz** [nodejs/help#1592]
* **Node.js Version**: 11.1.0
* **OS**: Windows 10 64bit
I uninstalled the older version of Node.js from my PC and installed 11.1 but now whenever I try to run the command "npm install purgecss -g"
A long list of errors appear. Please help me out I am not a pure programmer but a Designer actually
Here is my npm debug.log file

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Ahsan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'purgecss' ]
2 info using npm@3.5.2
3 info using node@v11.1.0
4 verbose stack ReferenceError: internalBinding is not defined
4 verbose stack     at evalmachine.<anonymous>:25:1
4 verbose stack     at Object.<anonymous> (C:\Users\Ahsan\AppData\Roaming\npm\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:707:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:605:32)
4 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:536:3)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:643:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:22:18)
4 verbose stack     at Object.<anonymous> (C:\Users\Ahsan\AppData\Roaming\npm\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\graceful-fs.js:3:27)
5 verbose cwd C:\Windows
6 error Windows_NT 10.0.17134
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ahsan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "purgecss"
8 error node v11.1.0
9 error npm  v3.5.2
10 error internalBinding is not defined
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
-->
[npm-debug.log](https://github.com/nodejs/help/files/2547018/npm-debug.log)
![2018-11-05_1015](https://user-images.githubusercontent.com/5106455/47979348-8d255700-e0e4-11e8-9a82-dc6f55fe7aec.png)

**Comment by vsemozhetbyt** [comment]
It seems you had very old `npm` installed manually, and it outlived old Node.js deinstallation. And it seems this old npm shadows new npm. You can try deinstall Node.js 11, then find your old npm, deinstall it and then install Node.js 11 with its new compatible npm.

**Comment by jacobq** [comment]
After you've uninstalled Node, check `C:\Users\Ahsan\AppData\Roaming` to see if it has an `npm` or `npm-cache` folder (if so, I would suggest deleting those).

**Comment by gireeshpunathil** [comment]
ping @ahsanpervaiz

**Comment by gireeshpunathil** [comment]
inactive, closing
