### ISSUE TITLE
Timer throttling - setTimeout()

### ISSUE THREAD

**Issue by unrealkate** [nodejs/help#1593]
* **Node.js Version**: v11.0.0
* **OS**: Windows 8.1 Pro
* **Scope (install, code, runtime, meta, other?)**: code, runtime

Node documentations states that minimum delay is more than 1 ms. Mozilla docs says that timers will throttle down to >=4-5 ms when calling same function that sets timeout on self.
The following simple code i wrote delivers 64-65 timeout triggers per sec. That means ~15ms delay.
I understand that timer functions do not trigger at precise intervals, but this is out of my understanding.

Consider a following scenario:
1. bring up a console window and run this code with 'node test.js' command.
2. test app will output about 64-65 triggers/sec.
3. open up visual studio code editor
4. start moving mouse over the vscode window (yep, just do that and...)
5. test app will suddenly start printing 140+ triggers/sec as long as you move the mouse.

Test code:
```js
var s = 0.0;
var rate = 0;
var timer;

function update()
{
	console.log(rate, s);
	rate = 0;
	s = 0.0;
}

function payload()
{
	for (var i = 0; i < 10000; i++);
		s += Math.sqrt(i);
	rate++;
}

function run()
{
	payload();
	timer.refresh();
}

setInterval(update, 1000);
timer = setTimeout(run, 1); // it does not matter what to write here: 1, 5, or 10 - the timeout is still 15+
```

The question is, why it starts working as expected? Why moving mouse over another process window (vs code in particular) affects timers in my nodejs app?

How do i prevent timer throttling? Is there are other options i could use?

Here is my app's code that suffers from this issue.
In this case payload() does nothing most of the time and returns false - setTimeout starts throttling down to ~15ms, when payload() wants to do something - the reaction time is ~15ms, how to make it shorter without making an while (true) loop and stressing cpu?

```js
function run()
{
  var keep_running = payload();
  if (keep_running) setImmediate(run); // something is running, keep it fast
  else setTimeout(run, 1); // nothing is running, schedule next poll
}
run();
```

**Comment by Hakerh400** [comment]
> start moving mouse over the vscode window (yep, just do that and...)

I experienced the same behavior a year ago using python and tensorflow-gpu, also on windows 8.1 pro. Not sure why exactly it happens. It's probably related to the windows internal algorithm for process/thread scheduling.

**Comment by gireeshpunathil** [comment]
@unrealkate - how many CPU cores in your system? It would be worthwhile to test in a system that has ample CPUs to make sure the node process has a dedicated CPU.

In addition, some OS schedulers have special treatments between I/O bound process vs. CPU bound processes in an attempt to balance the load. So it is expected that interactive processes get more attention than their normal quota, though these things nullify in the long run.

**Comment by gireeshpunathil** [comment]
inactive, closing
