### ISSUE TITLE
child_process spawn: passing env to child process on macOS

### ISSUE THREAD

**Issue by amatveevprog** [nodejs/help#1594]
Version: 10.13.0 LTS

Platform: 
- Windows 10 (10.0.15063)
- Ubuntu 16.10
- MacOs HighSierra (10.13.6) 
- MacOs Mojave(10.14)

Subsystem: child_process

Hello, I tried to make child process  spawn on different systems and faced with the following problem:

I have two files: test.js and test2.js
the content of test.js:
```
const {spawn} = require('child_process');
const path = require('path');
function serialize(data) {
    if (Buffer.isBuffer(data)) {
        return data.toString();
    }
    return data;
}
console.log('NODE_ENV:',process.env.NODE_ENV);
const childProc = spawn('node',[path.resolve(__dirname,'test2.js')],{env:{NODE_ENV:'some_new_env'}});
childProc.stdout.on('data', (data) => {
    console.log(serialize(data));
});

childProc.stderr.on('data', (data) => {
    console.log(serialize(data));
});

childProc.on('close', (code) => {
    console.log(`childProc closed ${code}`);
});
```
and the content of test2.js is the following (just try to output the environment that was passed):
```
console.log('hello world!!!');
console.log('test2.js: process.env.NODE_ENV: ', process.env.NODE_ENV);
console.log('goodbye!');
```
this works great on Linux and Windows, but on macOS I get the following error:
```
Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

Thank you!

**Comment by Trott** [comment]
Is it possible that `test2.js` does not exist (or is misnamed) on your macOS machine?

**Comment by amatveevprog** [comment]
> Is it possible that `test2.js` does not exist (or is misnamed) on your macOS machine?
@Trott ...no...I think it's a bit more complicated =)
when trying this on macOS:
`const childProc = spawn('node',[path.resolve(__dirname,'test2.js')],{env:{NODE_ENV:'some_new_env'}});` it crashes, but when I am trying this:
`const childProc = spawn('node',[path.resolve(__dirname,'test2.js')]);` it proceeds and executes test2.js

I created a repo on github with this problem so you can see it: https://github.com/amatveevprog/child_process_issue

**Comment by Trott** [comment]
Do you by any chance use `nvm` to install `node`?

**Comment by Trott** [comment]
More to the point, what's result when you type `which node` at the command line?

**Comment by Trott** [comment]
What's going on, I *think*, is that by sending an `env`, you are basically deleting the existing `env` and replacing it with the sent  `env`... and that includes `$PATH`! So the thing it's not finding (`ENOENT`) is the `node` executable when trying to `spawn()` that second file. I predict if you change line 10 of `test.js` to this, it will work:

```js
const childProc = spawn('node',[path.resolve(__dirname,'test2.js')],{env:{NODE_ENV:'debug', PATH: process.env.PATH}});

```

**Comment by Trott** [comment]
(It probably works fine on Linux etc. because there you have `node` installed in a default/standard place for the shell to look for executables. But if you use `nvm` and probably some of the other version managers, it will end somewhere else. I *imagine* that wouldn't happen with the "official" packages, but I could be wrong about that too.)

**Comment by amatveevprog** [comment]
> Do you by any chance use `nvm` to install `node`?

No, but I tried this option once I faced this problem.
Now I use only downloaded packages from nodejs.org

> More to the point, what's result when you type `which node` at the command line?

/usr/local/bin/node

**Comment by amatveevprog** [comment]
> What's going on, I _think_, is that by sending an `env`, you are basically deleting the existing `env` and replacing it with the sent `env`... and that includes `$PATH`! So the thing it's not finding (`ENOENT`) is the `node` executable when trying to `spawn()` that second file. I predict if you change line 10 of `test.js` to this, it will work:
> 
> ```js
> const childProc = spawn('node',[path.resolve(__dirname,'test2.js')],{env:{NODE_ENV:'some_new_env', PATH: process.env.PATH}});
> ```

I tried that and it works! Thank You very much for such detailed help!!!
