### ISSUE TITLE
how can i fixed this error ( spawn solc enoent ) on windows 10

### ISSUE THREAD

**Issue by raft1063** [nodejs/help#1596]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

hello i m learning solc in korea 
i m using editor tools ( Cryptofex) but i compile contract on Cryptofex
error on alert this message error : spawn solc enoent.....

i m instaling solc on npm but Cryptofex don't know i m installed solcjs

plz help me ;ㅅ;  i don't fiexd this error need help,,,

**Comment by gireeshpunathil** [comment]
@raft1063 - please provide full steps that followed, and exact error message you get.

**Comment by gireeshpunathil** [comment]
inactive, closing. please re-open if / when you have more data
