### ISSUE TITLE
Error referencing node.dll in c#/.net.

### ISSUE THREAD

**Issue by mohsini172** [nodejs/help#1598]
* **Node.js Version**: 8.9.3.0
* **OS**: Windows 10

I have build the NodeJS using the target: shared_library and successfully generated the dll. The problem is that when I try to use dll in c#/.net I got the reference error.
![capture](https://user-images.githubusercontent.com/19357286/48249896-40ac8500-e41e-11e8-98ef-1b4d3a135507.PNG)

**Comment by bzoz** [comment]
Node is a native DLL, you cannot add it using "Add Reference". Quick googling found this: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute?redirectedfrom=MSDN&view=netframework-4.7.2 and https://stackoverflow.com/questions/16420595/how-to-add-external-native-dependency-dll
