### ISSUE TITLE
Brew install LTS or Latest?

### ISSUE THREAD

**Issue by muuvmuuv** [nodejs/help#1599]
* **Node.js Version**: 11.1.0
* **OS**: 10.14.1 
* **Scope (install, code, runtime, meta, other?)**: brew
* **Module (and version) (if relevant)**: /

I have installed node via brew and was wondering why this installation is using the latest version and not the LTS (what is recommend for most users)? I came in the problem today, that a program that I wanted to use is not working with the latest but LTS what makes sense to me, because latest features can be buggy.

Is it possible to install the LTS version via brew? I read about that somewhere but the installation had problems and NPM was not installed with it. Would be great to have both; brew with `brew install node@lts` for those who doesn't want the latest and the latest just as before with `brew install node` :)

**Comment by gireeshpunathil** [comment]
@muuvmuuv - agree to your points that lts should be promoted as that is the most stable version. however, `brew` is an package installation manager for macOS and this feature actually depends on its interplay with the node installation package, version selection etc. , not necessarily have anything to do with node.js and its way of building, packaging or releasing versions I guess.

some where we should instruct `brew` to customize its behavior to match the protocol you propose. But I don't know where!

/cc @nodejs/platform-macos

**Comment by richardlau** [comment]
https://formulae.brew.sh/formula/ lists the packages installable via brew. 

https://formulae.brew.sh/formula/node is Node.js, which as you have noted is currently 11.1.0.

https://formulae.brew.sh/formula/node@10, https://formulae.brew.sh/formula/node@8 and https://formulae.brew.sh/formula/node@6 exists (all of these are LTS).

https://github.com/Homebrew/brew/issues is probably the place to request a `node@lts`.

**Comment by muuvmuuv** [comment]
@richardlau thanks! but `node@x` is not installing npm (or in my case it does not and printed some errors). Anyway, a `@lts` version would be cool!

@gireeshpunathil should I go and create an issue there or would you like to? I think a features request from an actual member of the package has more weight.

**Comment by richardlau** [comment]
> 
> 
> @richardlau - would you mind you raising one? I can do that, but i) you seem to be more knowledgeable than me on installer matters, i) I am bit tied up till this weekend, thnx!

Sorry, been out of the office for a week. I'd kind of prefer if it was someone that actually uses a mac (even preferable someone who uses `brew`). cc @nodejs/platform-macos

**Comment by gireeshpunathil** [comment]
this was closed at `homebrew/brew@6317` as:

`A combination of not enough demand, existing solutions (being able to install by version number) perhaps being sufficient and there be no clear implementation in Homebrew for this solution.`

looks like nothing can be done for this now. Closing this issue!
