### ISSUE TITLE
Proper way to do inheritance in nodejs

### ISSUE THREAD

**Issue by kkc** [nodejs/help#16]
Hi, all. I am new to nodejs. 
I don't know if this is a right place to ask such simple question. 

I should write the code that could run on browser side and server side.
I found out that I can use `require('util').inherits` to do inheritance thing in nodejs.
But if I want to let same code run on both client and server side, 
how can I do for that?  Thanks a lot !

**Comment by Trott** [comment]
One way to be able to use `util.inherits()` in the browser is to use [browserify](http://browserify.org/).  I have not used [webpack](https://webpack.github.io/) but it is also likely to supply `util.inherits()`.

**Comment by kkc** [comment]
thanks a lot, I will try to learn how to use browserify!

**Comment by Fishrock123** [comment]
I'd suggest taking a look at the implementation of `util.inherits()`: https://github.com/nodejs/node/blob/master/lib/util.js#L734-L772

JavaScript uses what we call "prototypical inheritance", which is different than some other languages. You can probably find a lot of info by googling something like that. :)

**Comment by kkc** [comment]
@Fishrock123 thanks a lot, your suggestion is very helpful :)

**Comment by lordKnighton** [comment]
Closing for now, feel free to reopen.
