### ISSUE TITLE
installing node.js

### ISSUE THREAD

**Issue by settlepath** [nodejs/help#160]
Hello ,I'm not able to install the node.js 
I'm having issue in locate the installing into the the usr/bin bash..
the terminal doesn't seems to reconize the folder...

**Comment by lordKnighton** [comment]
your on OSX or Windows?

**Comment by settlepath** [comment]
Osx

Il giorno mar 3 mag 2016 alle 07:14 kelvin knighton <
notifications@github.com> ha scritto:

**Comment by lordKnighton** [comment]
Are you getting this far?   

==

 So go to nodejs.org, click on the version you want and then it will download
and the nodejs installer will pop up, guiding you to your fresh installation of nodejs 

![screen shot 2016-05-03 at 8 35 36 am](https://cloud.githubusercontent.com/assets/1773260/14988788/4c5a9ec6-110a-11e6-88f4-56b5bf2fc8b2.png)

**Comment by lordKnighton** [comment]
Don't worry, if your having trouble getting here. I'll keep helping until you do. 😄  🎱

**Comment by settlepath** [comment]
right..until here it's clear...than I can't find the the directory where
has been installen

2016-05-03 17:43 GMT+02:00 kelvin knighton <notifications@github.com>:

**Comment by saadq** [comment]
Can you try typing `which node` into your terminal and say here what it prints out?

**Comment by lordKnighton** [comment]
ok no worries. type ` node -v` & see what pops out 👀

**Comment by settlepath** [comment]
2016-05-03 17:49 GMT+02:00 kelvin knighton <notifications@github.com>:

**Comment by lordKnighton** [comment]
**what this:**  2016-05-03 17:49 GMT+02:00 kelvin knighton <notifications@github.com>:

**Comment by lordKnighton** [comment]
lol, Yea i got that @addaleax  😸 , but i was expecting something about node.js installation. So @settlepath how's it looking?

**Comment by settlepath** [comment]
what does it mean? how should I test if the preogram it works?

2016-05-03 19:33 GMT+02:00 Anna Henningsen <notifications@github.com>:

**Comment by settlepath** [comment]
'm following what you have  told me...

2016-05-03 19:54 GMT+02:00 Matteo Pennacchia <writetoletmeknow@gmail.com>:

**Comment by lordKnighton** [comment]
🎱  type in the terminal ` node ` you should get a response like this: 

-- 


![screen shot 2016-05-03 at 11 18 37 am](https://cloud.githubusercontent.com/assets/1773260/14993688/e0c0903c-1120-11e6-9bba-3caf83ef2b7f.png)

**Comment by settlepath** [comment]
It seem to be a terminal issue is it?

it says server


2016-05-03 20:20 GMT+02:00 kelvin knighton <notifications@github.com>:

**Comment by lordKnighton** [comment]
It's okay, we will work threw it: Let's try ` which node` like @saadq  recommended above 💯

**Comment by settlepath** [comment]
Last login: Tue May  3 20:05:25 on ttys000
nounknown:~ matteo$ node_v
-bash: node_v: command not found
unknown:~ matteo$ node-v
-bash: node-v: command not found
unknown:~ matteo$ which node
/usr/local/bin/node
unknown:~ matteo$

2016-05-03 21:13 GMT+02:00 kelvin knighton <notifications@github.com>:

**Comment by lordKnighton** [comment]
Attention please 💯    `node -v` not `node-v` there's a space

**Comment by settlepath** [comment]
Last login: Tue May  3 20:12:10 on ttys000
nodeunknown:~ matteo$ node -v
v6.0.0
unknown:~ matteo$

2016-05-03 21:19 GMT+02:00 kelvin knighton <notifications@github.com>:

**Comment by lordKnighton** [comment]
Yeah, there we go! 👍

**Comment by settlepath** [comment]
:D thanks a lot sir..so that it shows the node...configuration...?

how to make the code app work now..?

2016-05-03 21:22 GMT+02:00 kelvin knighton <notifications@github.com>:

**Comment by lordKnighton** [comment]
type `node` in your teminal and this should happen: 

--

![screen shot 2016-05-03 at 12 32 55 pm](https://cloud.githubusercontent.com/assets/1773260/14995747/38892d88-112b-11e6-87f0-cd1db57175b7.png)

--

then press `control + c` to exit

**Comment by lordKnighton** [comment]
![screen shot 2016-05-03 at 12 37 28 pm](https://cloud.githubusercontent.com/assets/1773260/14995857/ddf0619c-112b-11e6-9662-a0b80810d5b8.png)

--

copy & paste in empty file name `app.js` or `index.js`
```js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

**Comment by lordKnighton** [comment]
I hope i help you to my fullest potential & if you need more help feel free to reopen and we will go from there. That code is from https://nodejs.org/en/about/

**Comment by settlepath** [comment]
Thanks very much yeah...definetly if I will write if I will find any issue..

cheers

Matteo

2016-05-03 21:40 GMT+02:00 kelvin knighton <notifications@github.com>:
