### ISSUE TITLE
LTS support problem between 10.13.0 and 10.10.10

### ISSUE THREAD

**Issue by Crophone** [nodejs/help#1602]
* **Version**:10.13.0
* **Platform**: 64-bit
* **Subsystem**:Windows 10

when I use the LTS version 10.13.0 of node, I use the command "npm install" to download the required packages of my private repository. The process of downloading package stopped and  a "asyncWrite is not a function" error was reported. Later  I use the 10.10.0.  version of node, the directive was executed, though there were two warning message of "
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}) "

**Comment by gireeshpunathil** [comment]
@Crophone - is this outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing
