### ISSUE TITLE
Porting Boost.ASIO to C++ Addons for Node

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/help#1603]
* **Node.js Version**: v11.1.0
* **OS**: Windows 10 Home Single Language, version 1803 build 17134.345
* **Scope (install, code, runtime, meta, other?)**: Other: want to port Boost.ASIO to Node for app
* **Module (and version) (if relevant)**: V8 (if this counts)

I want to learn how to use ASIO (and Beast) with Node.js C++ Addons.  So I can port my app that uses them as a C++ Addon for Node.  My app [source code](https://github.com/DragonOsman/currency_converter).  And then I'd like help on porting the app itself as well.  It's a web server application, which is why I'm thinking of using it through Node.  I'm sorry I keep opening new issues for this same thing, though.  

I have the documentation open in nodejs.org.  I'd like to know what I should read there if I want to understand completely how the Node runtime works so I can use my app's networking functionality through Node as well.  Thanks in advance.  

WebAssembly would be good too, but after this.

**Comment by DragonOsman** [comment]
I just added an async server version of the C++ code to my `currency_converter` repository.  Someone please look at it and let me know if the client code in it also needs to be asynchronous.  Thanks in advance.

**Comment by gireeshpunathil** [comment]
@DragonOsman - is this still pending?

**Comment by gireeshpunathil** [comment]
inactive, closing
