### ISSUE TITLE
Using for...in/of loops for arrays Node.js

### ISSUE THREAD

**Issue by ematt321** [nodejs/help#1607]
I'm trying to display the values of a property using node by using similar code to apply to the situation below. I'm not fully grasping what is actually happening and I can't figure out how to console.log the right array. I'm trying to get the student objects keys in this example.

```js

//1
for (var student in school) {console.log()};
-->

**Comment by ORESoftware** [comment]
so you have something like this?
```js
const school = {a:1, b:2};
for(let k of Object.keys(school)){

}
```

**Comment by gireeshpunathil** [comment]
ping @ematt321 -

**Comment by gireeshpunathil** [comment]
inactive, closing
