### ISSUE TITLE
Response times of http(s) client requests vary with the no of requests firing.

### ISSUE THREAD

**Issue by rakmovistara** [nodejs/help#161]
This code snippet gives me wrong response time calculations of urls. is there any way to achieve actual response times?
Please help me, i struck at this point after completion of entire project.

moving issue https://github.com/nodejs/node/issues/6518 to support.

Code

var https = require('https'),
hosts = require('./hosts.json');

function request(reqOpts) {
var startTime = Date.now();
var req = require('https').request(reqOpts, function(res) {
console.log(reqOpts.host,'responsetime is : ', Date.now() - startTime);
});
req.on('error', function(error) { });
req.end();
}

for(var i=0; i < process.argv[2]; i++) {
request({host:hosts[i], port:443, method:'GET'});
}
Output

host1 responsetime is : 300ms
host2 responsetime is : 350ms
.
.
.
.
host95 responsetime is : 1436ms
host96 responsetime is : 1460ms
host97 responsetime is : 1467ms
host98 responsetime is : 1476ms
host99 responsetime is : 1477ms
host100 responsetime is : 1493ms

~/node-test# time wget https://host100
--2016-05-02 13:08:46-- https://host100/
Resolving host100 (host100)... 198.35.26.96, 2620:0:863:ed1a::1
Connecting to host100 (host100)|198.35.26.96|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://host100 [following]
--2016-05-02 13:08:46-- https://host100
Reusing existing connection to host100:443.
HTTP request sent, awaiting response... 200 OK

real 0m0.209s
user 0m0.020s
sys 0m0.000s

conclusion : -
getting 209ms using wget but through node 1493ms. how to resolve ?

**Comment by bnoordhuis** [comment]
As explained in the other issue, DNS queries are by default done on a thread.  You can either grow the thread pool with the `UV_THREADPOOL_SIZE` environment variable (set it before start-up) or by looking up the DNS records yourself through the `dns.resolve()` family of functions.  Don't forget to set the Host header when connecting by IP address.

**Comment by lordKnighton** [comment]
If you need some sorted resources, for further exploration, I'll be happy to list them. 🎱

**Comment by rakmovistara** [comment]
the above two things resolved the issue. but  increase of UV_THREADPOOL_SIZE to 128, makes 50 - 70 requests per second.
