### ISSUE TITLE
Need to run NodeJs on Solaris 11 Sparc architecture

### ISSUE THREAD

**Issue by vikki978** [nodejs/help#1614]
* **Node.js Version**: Any
* **OS**: Solaris 11.5 Sparc 
* **Scope (install, code, runtime, meta, other?)**: All
* **Module (and version) (if relevant)**: Any

I have a test automation framework which is nodeJs based for running my testcases on solaris box I need to have nodeJs installed on that Box. 
This is very ***URGENT***

**Comment by gireeshpunathil** [comment]
@vikki978 - solaris on sparc is not a supported platform for node.js. please see the current [supported platforms](https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms-1) list. 

when you say you have a test framework that is node.js based, what the actual test cases are written in? also what language the source code is written in, that is being tested against?

**Comment by yogmk** [comment]
I'm in a similar situation. Developing a Test Framework in Node.js. Test cases are/will be written in javascript and drive our bespoke applications(products). Products are supported on Linux (inclu. z/Linux), SunOS, AIX and HP-UX, so test framework also needs to run on all these platforms. Hp-Ux has already fallen off.

**Comment by gireeshpunathil** [comment]
ya, while z/Linux and AIX among the list are in the supported list, HPUX and SunOS-spark are not! Closing this as answered, please feel free to re-open if there is anything outstanding.
