### ISSUE TITLE
chroot with node.js

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1615]
Is there a way to chroot during runtime with Node.js?
https://unix.stackexchange.com/questions/105/chroot-jail-what-is-it-and-how-do-i-use-it

or perhaps before I run the node.js command? something like this:

```bash
$ chroot . -c node foo.js
```

anybody know?

**Comment by gireeshpunathil** [comment]
@ORESoftware - `chroot` call is not abstracted in Node.js means there is no API that helps achieve that. However, I see a userland module https://www.npmjs.com/package/chroot which claims to achieve the same, I haven't tested it, so cannot vouch for its functional correctness.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to reopen if there is anything outstanding here
