### ISSUE TITLE
Symbol property on array

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1617]
On latest Node.js versions. I have this SO question:

https://stackoverflow.com/q/53345921/1604294

**Comment by addaleax** [comment]
Yes, you can assign a Symbol property to an Array the way it is described in the question, and it will not be encountered when iterating over the array with `for (let i = 0; i < arr.length; i++)`, `for (const element of arr)`, or `for (const index in arr)`.

**Comment by gireeshpunathil** [comment]
answered, closing.
