### ISSUE TITLE
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'

### ISSUE THREAD

**Issue by MubarakSULAYMAN** [nodejs/help#1618]
I just reinstalled node and I have been having issues with npm...

C:\Users\Mubarak>node -v
v10.13.0

C:\Users\Mubarak>npm -v
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by refack** [comment]
Hello @MubarakSULAYMAN, a good place to start is to run `where node` and `where npm`. If you find a degenerate node installation, remove it then uninstall and install your desired node version.

**Comment by lovelldies** [comment]
Running `npm i npm -g` does the trick sometimes.

**Comment by TerenceSperringerJr** [comment]
Ah, I had this same problem with version `v10.15.3` on the [Ubuntu subsystem for Windows 10](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab), and suspect it is **probably the same problem across multiple platform distributions**.
The issue is the scripts for `npm` and `npx` aren't even calling the correct files and are *also using relative paths incorrectly*!

I did the following to fix:
1. Locate nodejs bin
Ubuntu Example:
```
which node
/usr/local/lib/nodejs/node-v10.15.3-linux-x64/bin/node
```

2. Navigate to NodeJS bin
Ubuntu Example:
```
cd /usr/local/lib/nodejs/node-v10.15.3-linux-x64/bin
```

3. View the problematic files
Ubuntu Example:
```
cat npm
../lib/node_modules/npm/bin/npm-cli.js
cat npx
../lib/node_modules/npm/bin/npx-cli.js
```

4. Shake/smack head
Ubuntu Example:
```
🤦‍♀️
```

5. Rename (or remove) the bad files
Ubuntu Example:
```
mv npm npm-wrong
mv npx npx-wrong
```

6. Replace bad files with relative symbolic links to the correct locations
Ubuntu Example:
```
ln -s ../lib/node_modules/npm/bin/npm npm
ln -s ../lib/node_modules/npm/bin/npx npx
```

7. Also add a symbolic link to the node_modules directly itself, because **another broken reference** occurs without it
Ubuntu Example:
```
ln -s ../lib/node_modules/ node_modules
```

8. Test
Ubuntu Example:
```
cd ../../..
pwd
/usr/local/lib/nodejs/node-v10.15.3-linux-x64/bin
npm version
{ npm: '6.4.1',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.3',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.51',
  zlib: '1.2.11' }
```

**Comment by gireeshpunathil** [comment]
ping @MubarakSULAYMAN - is your problem solved?

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by 8ctopotamus** [comment]
Updating to the latest version of NPM fixed it for me. `npm install npm@latest -g`

**Comment by suniel26** [comment]
reboot your C:/ drive , worked out for me !

**Comment by Andraide** [comment]
In the case you are in Windows Subsystem for Linux, just have to close an re open the terminal. 
That work for me.

**Comment by hasham7861** [comment]
So I installed the npm and then just reopened it and it worked as well. Thanks to @Andraide

**Comment by dasari1729** [comment]
λ npm i -g create-react-native-app                                                                            
internal/modules/cjs/loader.js:796                                                                            
    throw err;                                                                                                
    ^                                                                                                         
                                                                                                              
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'      
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)                               
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)                                          
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)                                       
    at internal/main/run_main_module.js:17:11 {                                                               
  code: 'MODULE_NOT_FOUND',                                                                                   
  requireStack: []                                                                                            
}                                                                                                             
internal/modules/cjs/loader.js:796                                                                            
    throw err;                                                                                                
    ^                                                                                                         
                                                                                                              
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'      
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)                               
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)                                          
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)                                       
    at internal/main/run_main_module.js:17:11 {                                                               
  code: 'MODULE_NOT_FOUND',                                                                                   
  requireStack: []                                                                                            
}

**Comment by ndianabasi** [comment]
I'm having this issue too.

> internal/modules/cjs/loader.js:1017
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:884:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> internal/modules/cjs/loader.js:1017
>   throw err;
>   ^
> 

`where node `

> C:\Program Files\nodejs\node.exe


`where npm`

> C:\Users\ndianabasi\npm
> C:\Program Files\nodejs\node_modules\npm\bin\npm
> C:\Program Files\nodejs\node_modules\npm\bin\npm.cmd
> C:\Program Files\nodejs\npm
> C:\Program Files\nodejs\npm.cmd
> C:\Users\ndianabasi\AppData\Local\Yarn\bin\npm
> C:\Users\ndianabasi\AppData\Local\Yarn\bin\npm.cmd


`where npx`

> C:\Program Files\nodejs\node_modules\npm\bin\npx
> C:\Program Files\nodejs\node_modules\npm\bin\npx.cmd
> C:\Program Files\nodejs\npx
> C:\Program Files\nodejs\npx.cmd
> C:\Users\ndianabasi\AppData\Local\Yarn\bin\npx
> C:\Users\ndianabasi\AppData\Local\Yarn\bin\npx.cmd


Please, how can I solve this? 

`node --version`

> v14.0.0

Windows 8.1

**Comment by aghos4306** [comment]
Install the latest version of node, make sure that the js file e.g app.js is located inside the created folder that holds the file you want to read

**Comment by yougongdeyu** [comment]
I had the same error, and solved it totally, in my case, " v12.18.2\node_modules\npm " not exist, so I  
manually add npm which match to v12.18.2 to v12.18.2\node_modules\npm , and open a new terminal, the npm work well.

how can I find the match npm version ?
when you install the node by nvm, it will be logged in the terminal like "Installing npm v6.14.5..".
The content of my terminal is as follows.

C:\windows\system32>nvm install v12.18.2
Downloading node.js version 12.18.2 (64-bit)...
Complete
Downloading npm version 6.14.5... Complete
Installing npm v6.14.5...

The directory structure after the problem is solved is as follows. The nvm is the nvm  root path. 
nvm\v12.18.2\node_modules\npm\bin\npm-cli.js

**Comment by djbrown** [comment]
My fix was to `unset MSYS_NO_PATHCONV` in the Git Bash.
The variable is set from my .bashrc in Order for Docker to work properly.

**Comment by sanjaypaghadalss-sdm** [comment]
> My fix was to `unset MSYS_NO_PATHCONV` in the Git Bash. The variable is set from my .bashrc in Order for Docker to work properly.
