### ISSUE TITLE
Windows 10 Installer is broken due to lack of file permissions

### ISSUE THREAD

**Issue by mgara** [nodejs/help#1619]
Errors when installing node on windows 10.

* **Version**: 8.11.3
* **Platform**: Windows 
* **Subsystem**:  

![image](https://user-images.githubusercontent.com/6472786/41753456-97f2d34c-759b-11e8-8b9b-612bc4fb53a8.png)

I just ignored these errors but I have no shortcuts

**Comment by fakhamatia** [comment]
I have same problem 
create folders manually and uncheck creation of shortcut but not working

![{C2AF6BF5-3805-4188-B9F1-FAD3F3ED23DE} png](https://user-images.githubusercontent.com/20030910/61456466-5a25a980-a97b-11e9-9150-cf2af6922e27.jpg)
