### ISSUE TITLE
install nodejs v4 on ubuntu 14

### ISSUE THREAD

**Issue by aanelzam93** [nodejs/help#162]
i wanna install nodejs v4 or higher,, any one can help e

**Comment by lordKnighton** [comment]
yea sure, i got ya man. :)

**Comment by aanelzam93** [comment]
emm, i have download it, but i dont know how to install it

**Comment by lordKnighton** [comment]
click on the link above, and it should be a breeze

**Comment by lordKnighton** [comment]
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
this is a better link, directly to it

--

![screen shot 2016-05-06 at 11 00 58 am](https://cloud.githubusercontent.com/assets/1773260/15081906/edd1567a-1379-11e6-8928-8cc6b4eb2bbd.png)

**Comment by lordKnighton** [comment]
Hey bud, how's it going?

**Comment by aanelzam93** [comment]
oke thank you very much, i will try it

**Comment by lordKnighton** [comment]
Cools, I'm gonna close for now, if you need more help, don't hesitate to let me know :) enjoy the rest of you day
