### ISSUE TITLE
openssl engine clientCertEngine "no client cert method"

### ISSUE THREAD

**Issue by maddeezy** [nodejs/help#1622]
* **Node.js Version**: 11.2.0
* **OS**: debian
* **Scope (install, code, runtime, meta, other?)**: issue with 'no client cert method' in tls handshake
* **Module (and version) (if relevant)**: openssl node tls clientCertEngine

Having issues with this trying to use a Hardware Security Module which stores the private key.  (non readable/non exportable)

Without the HSM, there are no issues.  Maybe I am calling clientCertEngine incorrectly?  Or is there issue not allowing us to enter -keyform e?

although using s_client works as follows:
openssl s_client -host myHost.com -port 3000 -key fake.key -cert device.crt -CAfile ca.crt -engine hsm_engine -keyform e

_tls_common.js:204
      c.context.setClientCertEngine(options.clientCertEngine);
                ^

Error: error:1412214B:SSL routines:SSL_CTX_set_client_cert_engine:no client cert method
    at Object.createSecureContext (_tls_common.js:204:17)
    at Object.connect (_tls_wrap.js:1205:48)
    at Object.<anonymous> (/home/pi/test/tls.js:20:19)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)

```js
const tls = require('tls');
const fs = require('fs');

const options = {
  // key: null //cannot be exported nor read.  Ive tried with both null and removed key entirely
  cert: fs.readFileSync('client.crt'),
  clientCertEngine: '/path/to/hsm/.so file',
  ca: [fs.readFileSync('ca.crt')],
};

const socket =tls.connect({
   host: 'myHost.com',
   port: 3000
   }, options, () => {
  console.log('client connected', socket.authorized ? 'authorized' : 'unauthorized');
  process.stdin.pipe(socket);
  process.stdin.resume();
});

socket.setEncoding('utf8');

socket.on('data', (data) => {
  console.log(data);
});

socket.on('end', () => {
  console.log('server ends connection');
});

```
-->

**Comment by dhavald99** [comment]
I am getting same Issue :(

**Comment by maddeezy** [comment]
I find that the crypto module setEngine seems compliant to the openssl function


    int SSL_CTX_set_client_cert_engine (SSL_CTX * 	ctx, ENGINE * )

Where we pass two arguments.

But in the clientCertEngine we only pass one...

Am I needing to specify a default Engine?

**Comment by tniessen** [comment]
cc @nodejs/crypto

**Comment by sam-github** [comment]
@maddeezy  The string value of that property is passed to `SecureContext::SetClientCertEngine()`, you can read it to see what it does (baslically, ENGINE_by_id(), SSL_CTX_set_client_cert_engine()). The property value doesn't take context because it's being passed as an argument to `tls.createSecureContext()`, which creates the context that will be passed as the first arg to SSL_CTX_set_client_cert_engine().

Your second question I don't understand. Is it related to the first? You can specify crypto.constants.ENGINE_METHOD_ALL to `crypto.setEngine()` if you want, see the docs.

Also, your question does not appear to be related to this issue. Could you please open a new issue in https://github.com/nodejs/help if you have further questions?

Or, if you believe there is a bug or missing feature, open a new issue in nodejs/node, with information on how to reproduce.

And I'll be honest, I'm not sure how many people here have actually used the engine capabilities, so while I'm perfectly happy to read the code and help with how the node.js API maps to the OpenSSL one, if it doesn't work, you'll have to be pretty clear about what you are doing, and why it isn't working (and possibly what OpenSSL API calls would be necessary for it to work).

**Comment by maddeezy** [comment]
Thanks so much for the reply!

cURL and s_client work, so I am lost why Node cannot

Basically the issue I am experiencing is this (and it very well could be 
my error?)

We have a hardware security module (HSM) that stores the private keys.  
These keys are used to generate CSR and the server signs these and gives 
back the cert to be used to connect to our sockets.

 From CLI:

cURL works fine by adding --key-type ENG

s_client works fine by adding -keyform ENG


In Nodes https I cannot even get passed the key being required, but it 
cannot with an HSM as we cannot export the Private Key or even read it.


When we use NodeJS for tls, we get this: (using the client tls example)

(Method below has been tried against keys on disk and works fine when 
adding key: fs.readFileSync('/path/to/key') in options)


// Assumes an echo server that is listening on port 8000.
const tls = require('tls');
const fs = require('fs');
const crypto = require('crypto');

crypto.setEngine('/path/to/so/file', crypto.constants.ENGINE_METHOD_ALL)

const options = {
   host: 'ourhost.com',
   port: 3000,
   cert: fs.readFileSync('/path/to/crt')
};

const socket = tls.connect(options, () => {
   console.log('client connected',
               socket.authorized ? 'authorized' : 'unauthorized');
   process.stdin.pipe(socket);
   process.stdin.resume();
});
socket.setEncoding('utf8');
socket.on('data', (data) => {
   console.log(data);
});
socket.on('end', () => {
   console.log('server ends connection');
});


If we use clientCertEngine: '/path/to/so/file' in tls options we get 
this error fired:

Fires this error

< _tls_common.js:205
< c.context.setClientCertEngine(options.clientCertEngine);
<                 ^
< Error: error:1412214B:SSL routines:SSL_CTX_set_client_cert_engine:no 
client cert method


What I think we need, it tell Openssl the key is ENGINE

Am I doing something wrong?

Also have tried using openssl.cnf as follows (which we use for the cURL 
and s_client mentioned above):

openssl_conf = conf_section

[conf_section]
engines = engine_section

[engine_section]
myengine = myengine_section

[myengine_section]
engine_id = myengine_ssl
dynamic_path = /path/to/so/file
default_algorithms = EC
init = 1

**Comment by sam-github** [comment]
Just to be clear, I have never personally used an engine, though perhaps someone else around here has and can help you.

> I am lost why Node cannot

Perhaps a completely different code base and a user community that rarely uses engines would explain it? :-)

> What I think we need, it tell Openssl the key is ENGINE

What OpenSSL API should be called, with what value, to accomplish this? I don't know what "key" means.

As for ENGINE, you may have to reverse engineer the correct string to pass as the `clientCertEngine` option. Start at https://github.com/nodejs/node/blob/6447be620304256c0b9f9050dfbcecd39b01b674/src/node_crypto.cc#L1447-L1456, `args[0]` is your string, and perusing `LoadEngineById()` will show you how the string is mapped to an ENGINE.

I might have time to look at this sometime, but since I don't have a HSM, I'd need exact repro instructions, so probably would need some kind of soft HSM. Perhaps OpenSSL has a demo engine in their code tree? I have ossl builds around, so I could use that, or any other one that builds on Linux.

**Comment by maddeezy** [comment]
Thank you Sam...I would be more than happy to ship you a setup with the 
HSM installed....can you PM me and we set that up?

Ill take a look at that link.

As for the "key" it is the Private Key used to make the Certificate 
Signing Request and the key will be used for the cert signed by our servers.

 From what I see, https requires a key to be in either PEM | DER format 
and fires an error if not present.

     What OpenSSL API should be called, with what value, to accomplish 
this? I don't know what "key" means.

     We need to call "-keyform ENG" for openssl s_client

     On creating the CSR, similar call

     openssl req -key fake.key -new -out /path/to/csr -engine myengine 
-keyform e -subj "/CN=whatever@whatever.com"

     So on the "req" we have to use "fake.key" which is really just an 
empty file.

     I also tried that in Node, but then Node forcefully tries to use 
this key with the cert, and of course cannot.o

     Openssl docs for CLI is

     -keyform arg   input private key format (PEM or ENGINE)

    I tried looking for the CLI code on github to track down where this 
flag is used, but there are quite a bit of files there :O any idea where 
they load from?

**Comment by gireeshpunathil** [comment]
ping @maddeezy to see where this stands

**Comment by mobarakat** [comment]
Hello,

Any solution here? I face the same problem, please

**Comment by maddeezy** [comment]
Depends on what a "solution" really is...I only have a work around using shelljs and calling curl there.

Are you using hardware based keys?  If so, I'm curious to know which?

⁣


-------- Original Message --------

**Comment by mobarakat** [comment]
no, I do not use hardware-based keys. I was trying out clientCertEngine and I stuck with the same point

**Comment by PoojaDurgad** [comment]
@mobarakat , is this issue resolved? did @maddeezy' s suggestion above help you in getting rid of the issue?

**Comment by gireeshpunathil** [comment]
inactive, closing. pls feel free to reopen if required

**Comment by dnoliver** [comment]
I am running into this same issue. I have a gist to test TLS connections with PKCS11 engine here https://gist.github.com/dnoliver/388303c94639b763e9f120e2cbcccf8f

It works fine with the private key in the engine, and I am able to test the connection using `openssl s_client` and the nodejs client in https://gist.github.com/dnoliver/388303c94639b763e9f120e2cbcccf8f#file-tls-js. 

Problem starts when the cert is in the engine. Unfortunately, `openssl s_client` does not supports fetching the cert from the engine, so I don't know what I should be seeing in nodejs

```shell
+ openssl s_client -engine pkcs11 -keyform engine -key 'pkcs11:id=%61%65%36%62%65%66%32%39%63%39%32%62%35%37%34%35;type=private;pin-value=userpin' -CAfile ca.crt -certform engine -cert 'pkcs11:id=%61%65%36%62%65%66%32%39%63%39%32%62%35%37%34%35;type=cert'
engine "pkcs11" set.
s_client: Bad format "engine"; must be pem or der
s_client: Invalid format "engine" for -certform
s_client: Use -help for summary.
```

Anyways, trying to set `clientCertEngine: "pkcs11"` generates the error described in the title of this issue

```shell
_tls_common.js:288
      c.context.setClientCertEngine(options.clientCertEngine);
                ^

Error: error:1412214B:SSL routines:SSL_CTX_set_client_cert_engine:no client cert method
    at Object.createSecureContext (_tls_common.js:288:17)
    at Object.<anonymous> (/home/test/tls-pkcs11-cert/tls.js:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  library: 'SSL routines',
  function: 'SSL_CTX_set_client_cert_engine',
  reason: 'no client cert method',
  code: 'ERR_SSL_NO_CLIENT_CERT_METHOD'
}
```
