### ISSUE TITLE
Basic Web Server: Chrome displays text, Edge displays (almost) HTML

### ISSUE THREAD

**Issue by gedamial** [nodejs/help#1623]
* **Node.js Version**: v10.13.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: code/runtime

The code:
```
var http = require('http');
var fs = require('fs');

const port = 3000;

var server = http.createServer(function(req, res)
{
    res.writeHead(200, {'Content-Type': 'text/html'});
    var fileReadStream = fs.createReadStream(__dirname+"/lol.html", 'utf8');
    fileReadStream.pipe(res);
});

server.listen(port, "127.0.0.1");

console.log("Listening on port "+port);
```

Using Chrome the result is:

![111](https://user-images.githubusercontent.com/16063251/48768300-0910c900-ecb9-11e8-95fb-bfe25e1fb3a7.png)

Using Microsoft Edge the result is:

![222](https://user-images.githubusercontent.com/16063251/48768314-129a3100-ecb9-11e8-8ab7-754ccac6c725.png)

The real HTML page is:

```
<!DOCTYPE html>
<html>
<head>
<title>Mypage</title>
</head>
<body>
<span>Hello!</span>
</body>
</html>
```

Chrome displays everything as plain text.
Edge displays the span and the title BUT with random Chinese text along with it (huh?)

**Comment by Hakerh400** [comment]
Unable to reproduce the issue on Windows 10 using Node.js v10.13.0 and Chrome 72.0.3610.0

Does it work if you remove the `'utf8'` parameter?
Does it work if you use `res.end(fs.readFileSync(require('path').join(__dirname, 'lol.html')))` instead?

What is the output of

```js
let file = require('path').join(__dirname, 'lol.html');
console.log(fs.readFileSync(file, 'hex'));
```

**Comment by gedamial** [comment]
> Unable to reproduce the issue on Windows 10 using Node.js v10.13.0 and Chrome 72.0.3610.0
> 
> Does it work if you remove the `'utf8'` parameter?

**Yes.**

This creates some doubts:

1) How can the utf8 parameter be the problem if everyone uses it and it works for them? In fact, the code work for you, while I need to remove the utf8 parameter.

**Comment by gireeshpunathil** [comment]
@gedamial - is this still pending?

**Comment by gireeshpunathil** [comment]
inactive, closing
