### ISSUE TITLE
decorators/annotations for object props

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1624]
Someday annotations/decorators will come to JS, I imagine. One feature I have been looking for many times is a way to decorate objects or object properties, something like this:

```js
@bop('top')
const v = {};
```

which would yield
`v => {bop: top}`

now the above is not that useful for top-level objects, but for properties it becomes kind of convenient:

```js
const v = {
  @bop('top')
  foo: getSomeObject()
}
```

using the above, the decorator will decorate the return value of getSomeObject()...

is something like this ever going to be possible in JS? Decorators seem to be geared towards classes but not objects.

**Comment by devsnek** [comment]
this question would be better suited for https://github.com/tc39/proposal-decorators

node doesn't define how decorators work.

**Comment by ORESoftware** [comment]
@devsnek thx will do
