### ISSUE TITLE
agent.createConnection not working for https

### ISSUE THREAD

**Issue by yibopi** [nodejs/help#1625]
* **Node.js Version**: v10.13.0
* **OS**: linux
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: https

I am trying to use agent.createConnection() in the https module to set the client local port (localPort=34567 in the example below), but this only works when port = 80, not when port = 443. Following is the code I used to test. Thanks!

```
const https = require('https');
const url = require('url');

var req = https.get({
    host: 'google.com',
    pathname: '/',
    port: 443,   // works when equal to 80, but not 443
    family: 4,
    localPort: 34567,
    createConnection: require('net').createConnection
}, function(res) {
    console.log('localPort:', req.socket.localPort, "remotePort:", req.socket.remotePort);
});

req.on('error', console.error);

```

**Comment by gireeshpunathil** [comment]
@yibopi - is this still outstanding? if yes, can you elaborate on what do you mean by it does not work on 443? does it throw some error, or the response is not received, or something else?

**Comment by yibopi** [comment]
@gireeshpunathil I remember whatever ports you use, the destination port is always the default value. This post was long time ago. The issue should have been addressed already in newer versions.
