### ISSUE TITLE
First certificate error discord.js

### ISSUE THREAD

**Issue by SpeedyCraftah** [nodejs/help#1627]
* **Node.js Version**:11.2.0 
* **OS**:Windows 7 
* **Scope (install, code, runtime, meta, other?)**:Runtime 

Hello, I'm trying to run a discord bot with node, i have installed everything necessary to do so. But when I try run it, I get this error \|/ (detailed) 
https://pastebin.com/xkQDL0NC
Help would be appreciated! Thanks.

**Comment by SpeedyCraftah** [comment]
Bobsssssssaaaaboobnnigniggaaa

**Comment by gireeshpunathil** [comment]
@SpeedyCraftah - is this still pending?

**Comment by gireeshpunathil** [comment]
inactive, closing
