### ISSUE TITLE
Node.JS https getting ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by RafaelBeliveo92** [nodejs/help#1628]
* v11.0.0:
* Linux 4.8.0.39::
* NPM, 6.4.1; Nodemon, 1.18.6; Screen, 4.04.00 (GNU):

We are having an issue when trying to use Nodemon's Token Generator. We are running Node.JS on the port 3000 and listening through it, the workflow we're following goes like this: when users click a button on our page, we run an AJAX that fetches for us information from our database and we save each element in a corresponding variable. After this, we run a second ajax that serves as our link with port 3000 of our instance and with this, we obtain a Token Generator that we will be sending to our Firebase database.

All goes well during the first AJAX, it's the second one which apparently generates this error for us:
![capture](https://user-images.githubusercontent.com/45273265/48923024-79157f80-ee70-11e8-9f51-0895c7828e08.PNG)

From what I've gathered so far, it seems to be an issue with either of the endpoints whose certificate isn't properly working or validated...but the problem here is, they are within our server that runs a valid certificate. Actually, this is the fun part, this only happens when we try to serve and pick everything through HTTPS, whereas if we use HTTP (this is from an identical environment that we use for testing) it works perfectly fine.

Could this be an issue of our Firewall, PROXY, a communications error within the ports? I'm thankful for any help or suggestions I could get.
Thank you!

**Comment by gireeshpunathil** [comment]
ping @RafaelBeliveo92 - is this still pending?

**Comment by gireeshpunathil** [comment]
inactive, closing
