### ISSUE TITLE
node require('child_process').spawn throws ENOENT

### ISSUE THREAD

**Issue by prashathsenthil** [nodejs/help#163]
I'm using the node child process to spawn a shell and run a binary inside of it. I'm referencing the binary something like below but i get ENOENT error.

`var spawn  = require('child_process').spawn;`
    `binary = spawn('PATH_TO_BINARY')`

I refer it like   app.get('Config').ROOT_PATH + '/folderName/Binary -c' + app.get('Config').ROOT_PATH + '/configfolderName/BinaryConfig.cfg'

Then i have binary.stdout.on, binary.stderr.on listeners but when i run the app i get this error uncaughtException: spawn "binary path" ENOENT

On the other hand if i use "exec" it works, any idea why it's failing while using spawn and running while using exec.

I cannot use exec in this case because i'm dealing with event streams here so it looks like the ideal thing for streams is spawn and not exec.Got that from here http://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html

**Comment by julianduque** [comment]
@prashathsenthil using `exec` you can pass the full command with arguments as a parameter ([check docs](https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback))

But with `spawn` you'll need to pass the arguments as an array, as shown in the [docs](https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options)

So, in your case you'll need to execute it like

```
var spawn = require('child_process').spawn
var path = require('path')
var pathToBinary = path.join(app.get('Config').ROOT_PATH, 'folderName', 'Binary'))
var pathToConfig = path.join(app.get('Config').ROOT_PATH, 'configFolderName', 'BinaryConfig.cfg'))
var binary = spawn(pathToBinary, [ '-c', pathToConfig ]) // -> note the command arguments as an array
```

**Comment by prashathsenthil** [comment]
@julianduque Awesome, That worked like a charm. Thank you.

**Comment by julianduque** [comment]
@prashathsenthil you are welcome!

**Comment by baignoman** [comment]
@julianduque  I don't know where to put those code you mentioned. is this code go to App.js .I am the very beginner of react native.Will you please tell me? 
Thanks

**Comment by julianduque** [comment]
@baignoman it depends of your issue, what are you experiencing?
