### ISSUE TITLE
How to make the whole world waiting for a Promise.

### ISSUE THREAD

**Issue by ybbpgfjtey** [nodejs/help#1630]
* **Node.js v10.12.0**:
* **OS win10**:
* **Scope runtime**:
* **Module (and version) (if relevant)**:

---
How can I just make the mainthread wait for a async function.

```js
async function boo() {
    // some async call
    await fetch('www.google.com')
    return true
}
boo()
dostaff()
```
I want function dostaff runs just after boo had finished.
Because my code is called from someone's code I can not change, I can't use .then method or other callback way.
---
Since I can't use await outside async function, I've tried sleep module.
```js
import { nsleep } from 'sleep'
let finished = false
async function boo() {
    // some async call
    await fetch('www.google.com')
    finished = true
}
boo()
while (! finished) {
    nsleep(500)
}
dostaff()
```
but I got trapped in the nsleep loop, and boo never runs anymore.
---

What can I do?

**Comment by ORESoftware** [comment]
all you need to do is:

```js
import { nsleep } from 'sleep'

async function boo() {
    // some async call
    return fetch('www.google.com')
}
```

boo().then(result => {
   // result is the result! :)
});
```

async functions **always** return a promise, even if you don't return a promise explicitly, the return value is always wrapped in a promise.

**Comment by vsemozhetbyt** [comment]
Can you wrap the top-level code in the async IIFE?
```js
(async function main() {
  async function boo() {
      // some async call
      await fetch('www.google.com')
      return true
  }
  boo()
  dostaff()
})();
```

**Comment by ybbpgfjtey** [comment]
@vsemozhetbyt 
@ORESoftware 

Thanks, but I can't do staff like that.
Because my code is called by someone's code like this:
```js
require('myCode')
```
so if I wrap the top-level code in async IIFE, the subsequence code will not get Promise's result.

**Comment by devsnek** [comment]
you could export the promise from your module. definitely do not halt execution with sleep and such.

**Comment by ybbpgfjtey** [comment]
@devsnek 
Thank you. 
But I've tried export promise, but that still can't make subsequent code waiting for my code to be finished.

**Comment by ybbpgfjtey** [comment]
I've used a very weird way to do this.

1. In main process, start a detached child process, while-sleep loop waiting for it's **result file**
2. In child process, do the promise, when finished, write **result file**
3. In main process, when **result file** appeared, kill child process, break sleep loop, and go on.

Is there any better solution?

**Comment by ybbpgfjtey** [comment]
@devsnek 
I can't change user's code, so I must finish all my job with in my file.
If I return a promise, user's code must change 
from
```js
require('mycode')
dostaff()
```
to:
```js
require('mycode').then(result => {
    dostaff()
})
```
I simply can't change that code.

**Comment by ISpoonJelly** [comment]
I believe that by definition, the function you're trying to write is not really an async function.

**Comment by gireeshpunathil** [comment]
ping @ybbpgfjtey - is this still pending?

**Comment by ybbpgfjtey** [comment]
@gireeshpunathil 
No, but I think that solution I mensioned sucks.

**Comment by gireeshpunathil** [comment]
@ybbpgfjtey - I think the ask here is tough to achieve with Node.js, and moreover it works against its principles:
 - you have a network call, that is inherently asynchronous, without a sync alternative
 - if you wrap this call in any abstraction, the async nature of it does not get eliminated.
 - if you `async`ify or promisify the caller function, it helps sequencing call inside the function only, no effect is observed outside of it.

If you still want to meet your stated purpose, I would recommend to look for a `sync` version of `fetch` . May be sub-optimal, but!

**Comment by ybbpgfjtey** [comment]
@gireeshpunathil 
Thanks for your help.
But I don't have any network call, I just want **pause main thread**.

**Comment by ybbpgfjtey** [comment]
@ISpoonJelly 
Yes, that function I wrote is a sync function.
But I'd to call some sub-async-function that return Promise, this makes my question.

**Comment by PoojaDurgad** [comment]
@ybbpgfjtey , any updates regarding the issue?

**Comment by gireeshpunathil** [comment]
inactive, closing. pls feel free to reopen if required
