### ISSUE TITLE
Cannot extend the response object at runtime

### ISSUE THREAD

**Issue by thysultan** [nodejs/help#1633]
* **Version**: v9.7.1
* **Platform**: OSX Darwin 16.5.0 Darwin Kernel Version 16.5.0: RELEASE_X86_64 x86_64
* **Subsystem**:

Is there any reason the following neither works nor throws an error?

```js
const http = require('http')
const port = 3000

const server = http.createServer((request, response) => {
	console.log('url:', request.url)

	const res = Object.create(response)

	res.write('Hello')
	res.end("World!")
	// this works
	// response.write(...)
	// response.end(...)
})

server.listen(port, (err) => {
	if (err) return console.log(err)
	console.log(port)
})
```

**Comment by gireeshpunathil** [comment]
I see the problem as you have observed. When creating objects from existing prototype objects that have native backends, neither the inheritance model nor the inherited capabilities are well understood. IMO this should be covered under a Node.js documentation, but I am not sure whether one exists or not. /cc @nodejs/v8 @nodejs/http

**Comment by benjamingr** [comment]
> Is it an artefact of the implementation details that these methods don't work when extended in this fashion, or is this expected?

In general extending internals is never supported and in particular extending internals' prototypes. Node.js may explode (e.g. segfault) when you do this.
