### ISSUE TITLE
Basic Web Server: Chrome displays text, Edge displays (almost) HTML

### ISSUE THREAD

**Issue by gedamial** [nodejs/help#1635]
The code:

```
var http = require('http');
var fs = require('fs');

const port = 3000;

var server = http.createServer(function(req, res)
{
    res.writeHead(200, {'Content-Type': 'text/html'});
    var fileReadStream = fs.createReadStream(__dirname+"/lol.html", 'utf8');
    fileReadStream.pipe(res);
});

server.listen(port, "127.0.0.1");

console.log("Listening on port "+port);
```

Using Chrome the result is:

![111](https://user-images.githubusercontent.com/16063251/48768300-0910c900-ecb9-11e8-95fb-bfe25e1fb3a7.png)

Using Microsoft Edge the result is:

![222](https://user-images.githubusercontent.com/16063251/48768314-129a3100-ecb9-11e8-8ab7-754ccac6c725.png)

The real HTML page is:

```
<!DOCTYPE html>
<html>
<head>
<title>Mypage</title>
</head>
<body>
<span>Hello!</span>
</body>
</html>
```

Chrome displays everything as plain text.
Edge displays the span and the title BUT with random Chinese text along with it (huh?)

**Comment by gireeshpunathil** [comment]
@gedamial - is this still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing
