### ISSUE TITLE
How to fix 504 gateway issue and immediate response from graphql api

### ISSUE THREAD

**Issue by susmitha01** [nodejs/help#1638]
I'm calling an  graphql api , it has collection of records in mongo(i.e 100000 users)  using postman that i'm  getting response data with in fraction of seconds.But in AJAX calling of UI sometimes its showing 504 bad gateway issue and some times it takes 40-50 sec to load the data ...can you please help me out ?

**Comment by gireeshpunathil** [comment]
@susmitha01 - probably you have two issues, and we need to isolate those.

For the AJAX issue, I guess we need to check whether the data come in right time, but the data rendition takes more time, or the data itself takes 40-50 seconds or not. You may confirm that by adding some debug statement?

I have no idea how to debug 504 bad gateway error.

**Comment by gireeshpunathil** [comment]
ping @susmitha01 - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
