### ISSUE TITLE
chroot jail for node_modules

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1639]
For testing purposes I am looking to find a way to prevent the node.js executable from searching for node_modules below a certain directory, sort of like a chroot jail but specific to node only.

For example:

```
node_modules/
project/
    node_modules/
    foo/bar.js
```

if I run:

```bash
cd project && node foo/bar.js
```

then if it can't find a package in `project/node_modules`, then it will also look in `node_modules` (the sibling folder to the project folder).

My feature request is an executable option for node (or env variable) that can prevent node from looking for node_modules outside a certain dir, something like this:

```js
node --modules-jail="." foo/bar.js
```

or

```bash
export NODE_MODULES_JAIL="$HOME/project"
node foo/bar.js
```

the purpose is for testing packages and to ensure the end user is not "cheating themselves" by accidentally relying on installed packages outside/below the package itself.

**Comment by ORESoftware** [comment]
@bnoordhuis not so much a question as a feature request - I haven't tried the symlinks trick, but that doesn't yet seem to me like an ideal solution tho

**Comment by gireeshpunathil** [comment]
@ORESoftware - is there anything outstanding here?

**Comment by ORESoftware** [comment]
Basically the original issue, is for testing:

```
/home/me/.foo/testing_dir
```

the above dir can access node_modules in these 3 places:


```
/home/me/.foo/testing_dir/node_modules
/home/me/.foo/node_modules
/home/me/node_modules
```

I am simply looking to restrict it to only access the first folder, of the 3.
One solution I thought of was to temporarily mv the 2nd two dirs:

```
mv /home/me/.foo/node_modules  /home/me/.foo/node_modules_temp
mv /home/me/node_modules /home/me/node_modules_temp
```
and then move them back, after I run my process. but that's not ideal. Looking back on this thread, I really don't grok the symlinks solution, although would be happy to use it if I can figure it how it's supposed to work.
