### ISSUE TITLE
Version differences in documentation?

### ISSUE THREAD

**Issue by anotherHobbyist** [nodejs/help#164]
I had downloaded and installed node.js verion 0.10.33. I have been using the Apress publication 
Beginning Node.js. That text is recent: c right 2014, but it does not specify what version was current.
Now it is obviously superceeded and I am wondering about the significant differences and improvements,
bug fixes, etc. I did not find this in the documentation. The node.js web site doesn't appear to list docs
related to v 0.x.

So far everything is going well with local development on Mac OSX.

Thanks for time and attention.

**Comment by bnoordhuis** [comment]
> I am wondering about the significant differences and improvements, bug fixes, etc.

You can find release notes for individual releases on [the blog](https://nodejs.org/en/blog/).  If you want to see them all, consult the [master CHANGELOG](https://github.com/nodejs/node/blob/master/CHANGELOG.md) and the [archive](https://github.com/nodejs/node/blob/master/doc/CHANGELOG.ARCHIVE.md) (warning: big files, your browser may freeze for a few seconds.)

> The node.js web site doesn't appear to list docs related to v 0.x.

They exist: https://nodejs.org/docs/v0.10.33/api/
