### ISSUE TITLE
Question about chain of promises (disordered)

### ISSUE THREAD

**Issue by anialamo** [nodejs/help#1644]
Hi NodeJs people! I am trying to understand the promises with a sample of chain of promises...

I have this code....(using Twilio platform)
```js
TwilioChat.prototype.getChannel = function (channel_sid) {
        console.log("I am in getChannel.....");
        for (var channel in this.channels) {
            if (this.channels[channel].sid == channel_sid) {
                return this.channels[channel].getChannel(); // I see this is a Twilio code and it's a Promise
            }
        } 
        return null;
    };
```

Now I call this method getChannel from a chain of promises... like this.... I try to make a "sequential" loop each iteration wait the previous iteration is "resolved" (I need to do this with Promises not use Async/Await because I want this code also works in IExplorer):
``` js
function mainCall() { 
               for (let c = 0, p = Promise.resolve(); c < items.length; c++) 
                {
                    p = p.then(function() {
                        let channelDescriptor = items[c];                        
                        console.log("SID ", channelDescriptor.sid);
                        
                         
                        getPreviousMessages(channelDescriptor, that)
                        .then(function() {
                            resolve();
                        }); 

                    });    
                }
}


// Get Messages for a previously created channel
function getPreviousMessages(channelDescriptor, chat) {
    return new Promise((_) => { 
        console.log("p2.....step0.....", channelDescriptor.sid);     
        console.log("p2.....step1.....", channelDescriptor.sid); 
        let promise = chat.getChannel(channelDescriptor.sid);
        console.log(promise);
        return promise.then(channel => {
            console.log("p2.....step2.....", channelDescriptor.sid); 
            return channel;
        });
    });
}
```
I see this result:

SID  CH09c567eeebab4dabb5fa8594a44d774e
twilio_helper.js:147 p2.....step0..... CH09c567eeebab4dabb5fa8594a44d774e
twilio_helper.js:148 p2.....step1..... CH09c567eeebab4dabb5fa8594a44d774e
twilio_helper.js:388 I am in getChannel.....
twilio_helper.js:392 Promise {<pending>}
twilio_helper.js:72 SID  CH369ca3cc46d74886b031a52fd2e7dc29
twilio_helper.js:147 p2.....step0..... CH369ca3cc46d74886b031a52fd2e7dc29
twilio_helper.js:148 p2.....step1..... CH369ca3cc46d74886b031a52fd2e7dc29
twilio_helper.js:388 I am in getChannel.....
twilio_helper.js:392 Promise {<pending>}
twilio_helper.js:150 p2.....step2..... CH09c567eeebab4dabb5fa8594a44d774e
twilio_helper.js:150 p2.....step2..... CH369ca3cc46d74886b031a52fd2e7dc29

But I need this kind of result:

My question is... why this log twilio_helper.js:150 p2.....step2 I see outside my Chain of promises. I need to see this result:  

SID  CH09c567eeebab4dabb5fa8594a44d774e
twilio_helper.js:147 p2.....step0..... CH09c567eeebab4dabb5fa8594a44d774e
twilio_helper.js:148 p2.....step1..... CH09c567eeebab4dabb5fa8594a44d774e
twilio_helper.js:388 I am in getChannel.....
twilio_helper.js:392 Promise {<pending>}
twilio_helper.js:150 p2.....step2..... CH09c567eeebab4dabb5fa8594a44d774e
twilio_helper.js:72 SID  CH369ca3cc46d74886b031a52fd2e7dc29
twilio_helper.js:147 p2.....step0..... CH369ca3cc46d74886b031a52fd2e7dc29
twilio_helper.js:148 p2.....step1..... CH369ca3cc46d74886b031a52fd2e7dc29
twilio_helper.js:388 I am in getChannel.....
twilio_helper.js:392 Promise {<pending>}
twilio_helper.js:150 p2.....step2..... CH369ca3cc46d74886b031a52fd2e7dc29

Please! Give me some ideas to resolve this...Thanks!

**Comment by Hakerh400** [comment]
It's unclear what you want. Can you provide the full code? What is the `items` variable, where is its definition? What is `that` variable in `getPreviousMessages`? What is the `resolve` function that is called in the `then` callback (reference error, or never gets called)?

The issue template is there for a reason. What is your Node.js version? Assuming that `items` is an array of objects that contain `sid` strings and assuming that `that` is an instance of `TwilioChat`, running the code on Node.js v8.x, v10.x and latest v11.x gives the correct result according to your post.

**Comment by ORESoftware** [comment]
One thing, you are going to want to always return a promise here:

```js
TwilioChat.prototype.getChannel = function (channel_sid) {
        for (var channel in this.channels) {
            if (this.channels[channel].sid == channel_sid) {
                return this.channels[channel].getChannel(); 
            }
        } 
        return null;  // probably bad
    };
```

try this:

```js
TwilioChat.prototype.getChannel = function (channel_sid) {
        for (let channel of this.channels) {
            if (this.channels[channel].sid === channel_sid) {
                return this.channels[channel].getChannel();
            }
        } 
        return Promise.reject('no channel');  // ?
    };
```

**Comment by gireeshpunathil** [comment]
ping @anialamo

**Comment by gireeshpunathil** [comment]
inactive, closing
