### ISSUE TITLE
net.Socket write() fire callback no error on half-closed tcp connection

### ISSUE THREAD

**Issue by OlivierCuyp** [nodejs/help#1645]
* **Node.js Version**: v10.11.0
* **OS**: OSX
* **Scope**: code
* **Module**: net.Socket

The callback of `net.Socket.prototype.write` seems to be call without error even when the end socket is destroyed (half-closed tcp connection situation).

Please see the following test case and the output:

**Test case code:**
```js
const net = require('net');
const host = 'localhost';
const port = 3000;
const connections = {};
let client;

const server = net.createServer((connection) => {
  const key = `${connection.remoteAddress}:${connection.remotePort}`;
  connections[key] = connection;
  connection.on('data', (data) => {
    console.log('SERVER_RECEIVED', data.toString());
  });
});

server.on('error', (err) => {
  console.error('SERVER_FAIL', err.code);
});

server.kill = (callback) => {
  console.log('SERVER_KILL');
  server.close(callback);
  for (const key in connections) {
    connections[key].destroy();
  }
};

server.listen(port, host, () => {
  console.log('SERVER_LISTENING');
  client = net.createConnection(port, host);
  client.on('error', (err) => {
    console.error('CLIENT_FAIL', err.code);
  });
  console.log('CLIENT_WRITE1');
  client.write('Message 1', (err) => {
    if (err) {
      console.error('CLIENT_WRITE1_ERROR', err.code);
    }
    console.log('CLIENT_WRITE1_SUCCESS');
    // Wait 1 sec to kill the server !
    setTimeout(() => {
      server.kill(() => {
        console.log('SERVER_KILLED');
        // Server is down let's try to send a 2nd message
        console.log('CLIENT_WRITE2');
        client.write('Message 2', (err) => {
          if (err) {
            // Expect to end up here
            return console.log('CLIENT_WRITE2_ERROR', err.code);
          }
          // Not expected at all
          console.log('CLIENT_WRITE2_SUCCESS');
        });
      });
    }, 1000);
  });
});
```

**Shell output:**
```
SERVER_LISTENING
CLIENT_WRITE1
CLIENT_WRITE1_SUCCESS
SERVER_RECEIVED Message 1
SERVER_KILL
SERVER_KILLED
CLIENT_WRITE2
CLIENT_WRITE2_SUCCESS
CLIENT_FAIL ECONNRESET
```

I was not expecting `CLIENT_WRITE2_SUCCESS` but rather `CLIENT_WRITE2_ERROR EPIPE`...
So now, I don't know how to be 100% data was really send to and received by server.

**Comment by gireeshpunathil** [comment]
ping @OlivierCuyp - is this still an issue?

**Comment by OlivierCuyp** [comment]
@gireeshpunathil I'm on version `v10.11.0` and this is still an issue.
I don't know if this is fixed for newer version though.

**Comment by gireeshpunathil** [comment]
@OlivierCuyp - this showed the same result in v12.x as well.

However, I patched your code thus:
```patch
--- 1645.js.org	2019-07-22 13:26:28.000000000 +0530
+++ 1645.js	2019-07-22 13:27:47.000000000 +0530
@@ -39,6 +39,7 @@
     // Wait 1 sec to kill the server !
     setTimeout(() => {
       server.kill(() => {
+        setTimeout(() => {
         console.log('SERVER_KILLED');
         // Server is down let's try to send a 2nd message
         console.log('CLIENT_WRITE2');
@@ -50,6 +51,7 @@
           // Not expected at all
           console.log('CLIENT_WRITE2_SUCCESS');
         });
+        }, 100);
       });
     }, 1000);
   });
```

and I got:
```
#node 1645
SERVER_LISTENING
CLIENT_WRITE1
CLIENT_WRITE1_SUCCESS
SERVER_RECEIVED Message 1
SERVER_KILL
SERVER_KILLED
CLIENT_WRITE2
CLIENT_FAIL EPIPE
CLIENT_WRITE2_ERROR EPIPE
#
```
the socket that got closed may be in its `FIN_WAIT` state or so in the kernel, so an additional delay actually made the code work as intended.

Hope this helps!

**Comment by gireeshpunathil** [comment]
ping @OlivierCuyp

**Comment by OlivierCuyp** [comment]
@gireeshpunathil adding 100 ms after the server got killed and before the second write defeat the purpose of the test.
After that time everything fine, but point of the test was to show the uncertainty of the message being delivered after the server got killed.

**Comment by santigimeno** [comment]
I think the problem is how it works (at least on linux). As I understand it, a successful `write()` call doesn't mean the data successfully reaches the other side, but that the data has successfully been passed to the local TCP stack. In this case, the problem is that the write is performed before the TCP stack detects the closed connection so there was no way that the `write()` could return error, and the reason why adding a small timeout worked.

**Comment by OlivierCuyp** [comment]
@santigimeno exactly, the write callback is triggered before server received confirmation in this case.
This means can you find yourself in a position where you juste don't know if the message have been successfully received by the server or not.

**Comment by santigimeno** [comment]
Yeah, but I think that's not a nodejs specific issue but how the os works.

**Comment by OlivierCuyp** [comment]
@santigimeno yes I believe you are right but would it be possible to know for sure a message has been received by the server ? A part from waiting 100 ms, which is really long when you have a lot of messages to send ...

**Comment by santigimeno** [comment]
If you want to be 100% sure that the other end not only has received the message but read it, you'd have to build some kind of protocol on top (sending some kind of ack's for example). Another story is whether you really need that kind of realibility or even if TCP is the correct protocol election for what you're trying to accomplish.

**Comment by OlivierCuyp** [comment]
@santigimeno true, I'll close the issue since there is nothing to a part from avoiding TCP ;)
