### ISSUE TITLE
Node.js help with using typeof objects and strings

### ISSUE THREAD

**Issue by ematt321** [nodejs/help#1646]
I am trying to write code that will export a function named dog that returns a size from X-small to 2X-large when passed a weight, and returns three top suggested breeds when passed a size from X-small to 2X-large. I am having difficulty using the typeof object so that if you enter a string into the parameter of console.log, it will return 3 breeds, and when passed a weight it will return the corresponding size. I am mainly getting stuck on the syntax of using typeof.

```js
var dog = function size {
	
	if (typeof dog == 'X-Small' ) 
	{
	return 'Shitzu, Pomeranian, Maltese';
	}
	if (typeof dog == 17)
	{
	return 'Medium';
}
console.log(dog('X-Small'));
console.log(dog(17)):

**Comment by gireeshpunathil** [comment]
please try this:

```js
function dog(input) {
  if (typeof input === 'string')
    return 'Shitzu, Pomeranian, Maltese'
  else if (typeof input === 'number')
    return 'Medium'
}
console.log(dog('X-Small'))
console.log(dog(17))
```

**Comment by ematt321** [comment]
What should I change if I want the X-Small to matchup with where it says "string' so that I can have multiple strings? Such as say for size Small I return 'Cockapoo, Poodle' and so on. Would I not use typeof at all and just create multiple if loops?
