### ISSUE TITLE
Need clarification on cipher.update & cipher.final usage

### ISSUE THREAD

**Issue by gmk292** [nodejs/help#1648]
* **Node.js Version**: 8.12.0 & 11.2
* **OS**: Mac OS
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: crypto

I am trying to encrypt & decrypt a string using nodejs crypto module.

```javascript
const secretKeyHex = "e835e3c6e6b32d9d25932e23c2f98e3cae4886636b3b923920c9de1ea5d486f8";
const ivHex = "7220e8d5fcc14a8c2cb1a551df30a7cb";

const secretKeyBuffer = Buffer.from(secretKeyHex, ENCODING.HEX);
const IV = Buffer.from(ivHex, ENCODING.HEX);

const cipher = crypto.createCipheriv('aes-256-ctr', secretKeyBuffer, IV);
let encrypted = cipher.update('some clear text data');
```

As per documentation
> **cipher.update**
> If the inputEncoding argument is given, its value must be one of 'utf8', 'ascii', or 'latin1' and the data argument is a string using the specified encoding. If the inputEncoding argument is not given, data must be a Buffer, TypedArray, or DataView. If data is a Buffer, TypedArray, or DataView, then inputEncoding is ignored. Source [nodejs-8 LTS](https://nodejs.org/docs/latest-v8.x/api/crypto.html#crypto_cipher_update_data_inputencoding_outputencoding)

> If the inputEncoding argument is given, the data argument is a string using the specified encoding. If the inputEncoding argument is not given, data must be a Buffer, TypedArray, or DataView. If data is a Buffer, TypedArray, or DataView, then inputEncoding is ignored. Source [nodejs-11.3](https://nodejs.org/api/crypto.html#crypto_cipher_update_data_inputencoding_outputencoding)

**I am expecting an error will be displayed when calling ```cipher.update``` without inputEncoding and the data to be encrypted is normal string.**

----

Also when I check the length of ```cipher.final()```, it is displayed as 0.

> Once the cipher.final() method has been called, the Cipher object can no longer be used to encrypt data. Attempts to call cipher.final() more than once will result in an error being thrown.

>Output of cipher.final(): Any remaining enciphered contents. If outputEncoding parameter is one of 'latin1', 'base64' or 'hex', a string is returned. If an outputEncoding is not provided, a Buffer is returned.

**When we will get the *remaining enciphered contents*?**

**Comment by gireeshpunathil** [comment]
ping @nodejs/crypto

**Comment by tniessen** [comment]
> I am expecting an error will be displayed when calling `cipher.update` without inputEncoding and the data to be encrypted is normal string.

For backward compatibility, `cipher.update` accepts strings and interprets them as UTF-8. It is not recommended to use this legacy behavior.

> When we will get the remaining enciphered contents?

You are using `aes-256-ctr` which acts like a stream cipher. Stream ciphers do not need to cache partial sequences and return all of the data via `cipher.update`.

**Comment by gireeshpunathil** [comment]
answered, closing
