### ISSUE TITLE
Can't install v8.11.3 Nodejs for Ubuntu 16.04 Linux

### ISSUE THREAD

**Issue by Dycedlp** [nodejs/help#1650]
* **v8.11.3**:
* **Linux**:
* **Scope (install, code, runtime, meta, other?)**:  install
* **Module (and version) (if relevant)**:
I'm following these exact steps.  https://medium.com/@tgmarinho/how-to-install-node-js-via-binary-archive-on-linux-ab9bbe1dd0c2

I used nano to edit the profile to add the node_js path to /usr/local/lib/node/nodejs/bin
Never sets it to the nodejs packages...
Always says to install nodejs type...

What am I missing in setting the nodejs path here?

**Comment by yathamravali** [comment]
```trace
$ pwd
/home/ravali/1650
$ cat .profile
export NODEJS_HOME=/home/ravali/1650/node-v8.9.4-linux-x64
export PATH=$NODEJS_HOME/bin:$PATH
$ ./.profile
bash: ./.profile: Permission denied
$ chmod +x .profile
$ ./.profile
$ node -v
The program 'node' can be found in the following packages:
 * node
 * nodejs-legacy
Ask your administrator to install one of them
$ . .profile
$ node -v
v8.9.4

```
In the above you can see how it differentiates.So it depends on the way we execute commands. We need to be in the current shell to execute (.)
 So after executing `. .profile `it is working fine

**Comment by gireeshpunathil** [comment]
ping @Dycedlp

**Comment by gireeshpunathil** [comment]
inactive, closing
