### ISSUE TITLE
(node:7999) DeprecationWarning: (node-watch) First param in callback function  is replaced with event name since 0.5.0, use  `(evt, filename) => {}` if you want to get the filename

### ISSUE THREAD

**Issue by diners-admin** [nodejs/help#1651]
Hello, I have this error:
(node: 7999) DeprecationWarning: (node-watch) First param in callback function is replaced with event name since 0.5.0, use `(evt, filename) => {}` if you want to get the filename

Some way to solve it. Thank you.

**Comment by addaleax** [comment]
Can you share your code that causes this? Running your code with the `--trace-warnings` flag could help locate the source of this issue, e.g. `node --trace-warnings app.js`?

**Comment by diners-admin** [comment]
I do not understand your answer very well, I followed all the steps exposed at: https://github.com/zone117x/node-open-mining-portal and when I get to the command:
3) Start the portal
node init.js
It is where the error appears and does not continue, attached screenshot, thanks.
![captura de pantalla de 2018-12-01 21-16-51](https://user-images.githubusercontent.com/45186395/49332528-d4511b80-f5ae-11e8-84f4-65e8d071711f.png)

**Comment by diners-admin** [comment]
![captura de pantalla de 2018-12-01 21-34-54](https://user-images.githubusercontent.com/45186395/49332640-0fece500-f5b1-11e8-89a3-664422e8450d.png)
![captura de pantalla de 2018-12-01 21-35-16](https://user-images.githubusercontent.com/45186395/49332642-14b19900-f5b1-11e8-84da-07c42c96f743.png)

**Comment by diners-admin** [comment]
I have uploaded the work done here so that it can be easier to locate: https://github.com/diners-admin/node-open-mining-portal
What we are trying to do is a pool for Diners, the new cryptocurrency, and we use Linux Mint, thanks for your help.

**Comment by diners-admin** [comment]
Is any help possible to correct this error?

Thank you

**Comment by aduh95** [comment]
I think this issue is meant for [zone117x/node-open-mining-portal](https://github.com/zone117x/node-open-mining-portal/issues)'s repo, I doesn't seem to related with Node.js core. Try to create an issue there, and don't forget to include what node version you are using.

BTW, posting screenshots (especially when semi-opaque background is involved) makes it very hard to read, try to copy and paste instead.

**Comment by diners-admin** [comment]
ok, thanks
