### ISSUE TITLE
No output printing in stdout using process.stdout.write when running the code in codechef ide?

### ISSUE THREAD

**Issue by prasoonmayank** [nodejs/help#1654]
I was working on a competitive programming problem in nodejs. The question being to print all combinations of words possible from the letters of the given word for n number of test cases.

The code is wrote is as shown below:

               var n = -1

		var charar = Array.apply(null, Array(26)).map(Number.prototype.valueOf,0);

		function fact(length) {
			var product = 1;
			if(length>0) {

				while(length>1) {
					product = product * length;
					length=length-1;
				}
			}
			return product
		}

		function getoutput(charar, length) {
			var num = fact(length)
			var ans = num
			for(var i=0; i<charar.length; i++) {
				ans = ans/fact(charar[i])
			}
			return ans
		}

		process.stdin.on("data", function (data) {
			i = data.toString().trim()
			if(n==-1) {
				n = parseInt(i, 10)
			}
			else {
				getResult(i)
			}
			if(n>0) {
				n--;
			}
			else {
				process.exit()
			}
		})

		function getResult(inp) {
			for(var j=0; j<inp.length; j++) {
				var code = inp.charCodeAt(j);
				charar[code-97]++;
			}
			process.stdout.write(getoutput(charar, inp.length).toString().trim())
			charar = Array.apply(null, Array(26)).map(Number.prototype.valueOf,0);
		}

When I run the above code in terminal, the code works fine. But running the code in codechef ide, I dont get any output in stdout, after adding the custom input. It will be really helpful if someone could help me.

**Comment by Hakerh400** [comment]
According to the CodeChef docs, every Node.js application must execute

```js
process.stdin.resume();
process.stdin.setEncoding('utf8');
```

at the beginning. Also, you should never use `process.exit`, since it stops the event loop and there may be a chance that `process.stdout.write` (which is asynchronous) doesn't get a chance to finish. Use `process.stdin.unref()` instead.

**Comment by gireeshpunathil** [comment]
ping @prasoonmayank - is this still pending?

**Comment by prasoonmayank** [comment]
No, The issue is resolved.
