### ISSUE TITLE
N-API: slice buffer

### ISSUE THREAD

**Issue by jorangreef** [nodejs/help#1657]
I am working on an N-API module.

The C N-API module allocates a buffer using `napi_create_buffer()`, references the buffer using `napi_create_reference()` and then queues an `async_work` request with the pointer to the buffer stored in the `void* data` argument.

Later, from within `async_complete()`, it needs to adjust the length of this `napi_value` buffer. In other words, it needs to slice the buffer just before returning it to the user.

What is the best way to go about this using N-API? I can't afford to create a copy of the buffer.

**Comment by gireeshpunathil** [comment]
ping @nodejs/n-api

**Comment by gabrielschulhof** [comment]
@jorangreef if you need to manipulate the memory for the buffer yourself, you should use `napi_create_external_buffer()`. Then you can create multiple views of the same buffer by creating a second buffer using the same pointer, and making sure that the finalizers free the pointer only once.

**Comment by gabrielschulhof** [comment]
@jorangreef basically, if the buffer gets garbage-collected before `async_complete()` you want its finalizer to actually free the buffer, and you want to handle the case in `async_complete()` where the buffer is already gone.

If the buffer survives until `async_complete()` you wanna set a flag that tells the first finalizer to not do anything, but you would also create a second buffer using `napi_create_external_buffer()` that has the new size and whose finalizer actually frees the buffer.

**Comment by gabrielschulhof** [comment]
Just noticed the date on the OP. Sorry for the late response!

**Comment by jorangreef** [comment]
Thanks @gireeshpunathil and @gabrielschulhof
