### ISSUE TITLE
really need thread / core / concurrency vs parallel clarification

### ISSUE THREAD

**Issue by kylepwarren** [nodejs/help#1658]
node version: latest stable december 2018.

I see varying contradictory explanations of how node processes a script. 

some snippets/paraphrasing:

-node runs a single thread
-- *clarification a single main thread, which can create more threads for *async* calls
--    ^^^ all of this really needs a lot of clarification:
**---  does "async" mean literally async-functions, or could it be promises as well?
---   do the threads created by the main process to handle the *async* function have the same processor, and/or core affinity as the main thread?** I'm pretty surprised I haven't found a clear description of how this works in the documentation - I guess it may be partially v8 and system dependent. I'd greatly appreciate link to documentation that clarifies these things. It seems essential to have a general idea which system resources[especially cores] a program may use and which constraints exist. All of the information I'm finding seems incomplete, ambiguous, and almost never offers citation to official documentation.

I find a few posts asking for these kinds of clarifications, and most of the responses seem at best incomplete. If I run a script with many http requests (they have asynchronous responses) I notice all [>10] cpu cores appear to be used. If it's as appears - threads that handle async functions do get shared between other cores - then wouldn't "clusters" not necessarily be needed to multi-core processing?
example: https://stackoverflow.com/questions/51362308/promise-parallelism-and-cpu

**Comment by gireeshpunathil** [comment]
@kylepwarren - let me know if is this still outstanding. If so, I will come up with some plans to help you on this.

**Comment by gireeshpunathil** [comment]
inactive, closing
