### ISSUE TITLE
TCO - gone

### ISSUE THREAD

**Issue by kylepwarren** [nodejs/help#1659]
node version: latest stable december 2018

with all the nested callbacks required to handle asynchronous result processing this[tail callback optimization] seemed like a GREAT idea. Now that it's not longer supported is there another method from achieving the same thing? same thing being: preventing duplicated function frames for each recursive call - since the recursive call is one of javascripts primary control flows there could feasibly be very very very large amounts of recursive callbacks - would be essential to NOT duplicate function in memory(like TCO did) for things that take more than a second or two to run.

side note:
I actually bought a print copy of "understanding es6". At the end of many sections it has warnings that "these things may have major syntax changes in the near future". Often when I find something that seems like it would be useful and look for the most recent references to it I find it's no longer supported at all. I wonder if this is ever, in the somewhat near future, going to stabilize. if not Node it going to have to change it's tag line to: "none of this stuff is going to work six months from now".

**Comment by devsnek** [comment]
> I wonder if this is ever, in the somewhat near future, going to stabilize.

Bit of background on TCO, as it is unique in this regard: it was added during the rough time of ES6, and wasn't vetted as thoroughly as it should have been. JavaScriptCore (safari) was and remains the only engine willing to implement it, and the other engines would like it to be removed from js for various reasons (debugging, perf, etc)

> Now that it's not longer supported is there another method from achieving the same thing?

You should just use loops. for ex:
```js
function a(list) {
  const item = list[0];
  // do magic with item
  a(list.slice(1));
}
```
becomes:
```js
list.forEach((item) => {
  // do magic with item
});
```

**Comment by addaleax** [comment]
> if not Node it going to have to change it's tag line to: "none of this stuff is going to work six months from now".

Another thing: Node.js by itself doesn’t make any decisions about JS as a language. It is developed and standardized by [TC39](https://github.com/tc39), and implemented by JS engines such as Google’s V8 engine (which Chrome and Node.js both use). However, you can assume the language itself will *never* do actual breaking changes.

**Comment by kylepwarren** [comment]
> You should just use loops. for ex:

OK, but then most of the methods *I see* for [a]waiting ansync results one way or another rely on callbacks..

let one_million_urls = [....]
for~(urls){
    http.request(  == asyn = one million simultaneous requests = memory problem and then some. 

seems like the most direct solution is like:
process_urls(urls,callback){
  http.request(url,callback business and at end call process_url with next url << 

I'm no js expert, maybe there is an elegant way to do this without duplicating the process_urls function in memory a million times, but most of the solutions for ... the first thing I said. It looks like they just re-arrange where the recursive callback happen, e.g. the 'async' library. It seems like it's one of various efforts to make this possible, or easier to understand (e.g. TCO). It seems like there may be some way to do it if you just organize your code the right way.. Is there? again I'm not a javascript/node expert.

**Comment by devsnek** [comment]
you can recursively call process_url from the http request callback because it's on a new tick, so the call stack won't overflow.

**Comment by kylepwarren** [comment]
Just want to clarify: does it being on a new tick mean that the function will not be duplicated in memory? It seems like TCO specifically addressed this, which makes me doubt it's done by default. I bet this is clearly stated in some js reference guide, I haven't found it yet

**Comment by kylepwarren** [comment]
According to this https://javascript.info/recursion
 the outer recursive function will be moved to the "execution context stack". i.e. duplicated in memory

**Comment by devsnek** [comment]
@kylepwarren just to clarify, the function itself is never duplicated. what TCO does is pop the call stack before a function finishes executing, which prevents the call stack from getting too large.

However in the next tick, the call stack is already empty, as the function has finished executing, so you can call it again without worry.

**Comment by kylepwarren** [comment]
ok thanks for the clarification

**Comment by kylepwarren** [comment]
hmm, it seems like this would happen: http://davidshariff.com/blog/what-is-the-execution-context-in-javascript/ - one million execution contexts in memory

**Comment by kylepwarren** [comment]
or since the [http]request is async, maybe the outer function reaches the end - since there is not a closure the outer references / context can be garbage collected? is a closure *really* the only thing that would prevent it (from it being ready for gc)?

**Comment by kylepwarren** [comment]
yes, it works:
memory keeps going down, only visible though if gc called - I imagine would happen later anyhow.
Are there any pitfalls to look out for here? like accidentally having a closure that would prevent gc from freeing memory?

`let list = [];
for(let i=0;i<100;i++){
    list.push(i);
}

function process_list(list){
  let list_item = list.pop();
  setTimeout(function(){
    //let list_item = list.pop();
    console.log(list_item,process.memoryUsage());
    global.gc();
    process_list(list);
  },1000);
}

process_list(list);`
