### ISSUE TITLE
url.parse interprets '/' as part of the query string

### ISSUE THREAD

**Issue by MaxenceMaire** [nodejs/help#1661]
* **Node.js Version**: v10.13.0
* **OS**: Debian Stretch
* **Scope (install, code, runtime, meta, other?)**: core URL module, URL parsing

`require('url').parse('/1234/ForumTitle?page=2/tests', true).query` returns `{ "page": "2/tests" }` where I expected `{ "page": "2" }` or even nothing altogether.

Is this WHATWG URL Standard-compliant? I would have thought the slash to be considered as a delimiter and therefore part of the pathname instead of the query string.

**Comment by gireeshpunathil** [comment]
ping @nodejs/url

**Comment by watilde** [comment]
With the current version, you can use WHATWG URL.
```
let url = new URL('http://example.com/1234/ForumTitle?page=2/tests')
url.search // => "?page=2/tests"
```

**Comment by watilde** [comment]
Please feel free to reopen if my comment does not resolve your issue. Thank you for asking!
