### ISSUE TITLE
Frequent network disconnect/reconnect issue

### ISSUE THREAD

**Issue by hatimn02** [nodejs/help#1667]
* **Node.js Version - 8.11.4**:
* **OS - Amazon Linux - 4.5.4**:
* **Scope - runtime**:
* **Module - socket-io**:

We have a node app based on web socket and facing frequent network disconnect/reconnect issue

```
on disconnect transport close
vendors~main.1cc202f1588a0f9254fb.chunk.js:1 on reconnect_attempt 1
vendors~main.1cc202f1588a0f9254fb.chunk.js:1 on reconnect 1
vendors~main.1cc202f1588a0f9254fb.chunk.js:1 on disconnect transport close
vendors~main.1cc202f1588a0f9254fb.chunk.js:1 on reconnect_attempt 1
vendors~main.1cc202f1588a0f9254fb.chunk.js:1 on reconnect 1
vendors~main.1cc202f1588a0f9254fb.chunk.js:1 on connect undefined lHzkAS0SqKj-dV0dAAAc
```

**Comment by Qix-** [comment]
Buy a better router? Upgrade your ISP plan? There's nothing obvious here about why this is anyone's problem but your network's.

**Comment by gireeshpunathil** [comment]
agree with @Qix- this looks like a network issue at your end. Were you able to resolve it?

**Comment by gireeshpunathil** [comment]
inactive, closing
