### ISSUE TITLE
Spawning a backround process and communicating with it and use output later

### ISSUE THREAD

**Issue by FleXoft** [nodejs/help#1668]
Node.js Version >8:
All OS:

 I'm very newby in node.js but what I want is to run a background process and send some command to it via its stdin pipe (which arrives) and use its results later BUT I never get back any result out of the child.stdout.on function. child.stdout.on works beacuse I can see the outputs there
All of my OUTSIDE0 outputs are empty array. 

How could I solve this? (Soulution examples would be better for me than a simple explanation!)

Cheers,
_flex.

```js
var child_pr = require( "child_process" );

var buffer = [];
var bufferReady = false;

process.stdout.write( "OUTSIDE0: [" + buffer.length + "]\n" );
buffer.forEach( function( s ) { process.stdout.write( "OUTSIDE0: [" + buffer.length + s + "]\n" ); } );

const child = child_pr.spawn( 'command', [ '-ID=a', '-PASSW=a' ], { detached: true } );

child.once( "exit", function ( errocode, signal ) {
    console.log( "exited ".red + "with code: " + errorcode + "SIGNAL: " + signal );
} );

child.once( "close", function ( errocode, signal ) {
    console.log( "closed ".red + "with code: " + errorcode + "SIGNAL: " + signal );
} );

child.stderr.once( "data", data => reject( String( data || "empty stderr.\n" ) ) );

child.stdout.on( "data", function( data ) {

    var s = String( data );
    buffer = buffer.concat( s.split( "\n" ) );

    process.stdout.write( "BUFFERPACK: [" + buffer.length + "]\n" );
    buffer.forEach( function( s ) {
        process.stdout.write( "BUFFER PACK: [" + s + "]\n" );
    } );

    var match = buffer[buffer.length - 1].match( /^Protect/ ); // last line
    if ( match ) {

        buffer.pop();                       // remove last line we dont need
        buffer = buffer.filter( n => n );   // clean empty lines

        buffer.forEach( function( s ) { process.stdout.write( "INSIDE: [" + s + "]\n" ); } );
        
        bufferReady = true;

    }

} );

child.stdout.on( 'end', function() {
        console.log( "\nENDEND\n" );
    }
);

process.stdout.write( "OUTSIDE1: [" + buffer.length + "]\n"  );
buffer.forEach( function( s ) { process.stdout.write( "OUTSIDE1: [" + buffer.length + s + "]\n" ); } );

child.stdin.write( "select * from table" + "\n" );

process.stdout.write( "OUTSIDE2: [" + buffer.length + "]\n"  );
buffer.forEach( function( s ) { process.stdout.write( "OUTSIDE2: [" + buffer.length + s + "]\n" ); } );
```

**Comment by Hakerh400** [comment]
The `buffer` is empty because you need to await the data asynchronously. Here is an example of how your code should look like:

```js
'use strict';

const cp = require('child_process');
require('colors');

main().catch(console.log);

function main(){
  return new Promise((resolve, reject) => {
    (async () => {
      let str = '';
      let buffer = [];
      let bufferReady = false;

      const child = cp.spawn('node', ['-e', `(${() => {
        const log = a => console.log(`${a}\nProtect`);
        log('example 1');
        process.stdin.on('data', data => {
          log('example 2');
          process.stdin.unref();
        });
      }})()`], {detached: true});

      console.log(`OUTSIDE0: [${buffer.length}]`);
      buffer.forEach(s => console.log(`OUTSIDE0: [${buffer.length} ${s}]`));

      child.on('error', reject);
      child.once('exit', (c, d) => console.log(`${'Exited'.red} with code: ${c}, SIGNAL: ${d}`));
      child.once('close', (c, d) => console.log(`${'Closed'.red} with code: ${c}, SIGNAL: ${d}`));
      child.stderr.once('data', data => reject(data.length !== 0 ? data : 'Empty stderr'));
      child.stdout.on('end', () => console.log('\nEND\n'));

      child.stdout.on('data', data => {
        str += data;

        while(1){
          var m = str.match(/\r\n|\r|\n/);
          if(m === null) break;

          let s = str.slice(0, m.index);
          str = str.slice(m.index + m[0].length);
          buffer.push(s);

          console.log(`BUFFERPACK: [${buffer.length}]`);
          buffer.forEach(s => console.log(`BUFFER PACK: [${s}]`));

          if(/^Protect/.test(s)){
            buffer = buffer.filter((s, i) => s.length !== 0 && i !== buffer.length - 1);
            buffer.forEach(s => console.log(`INSIDE: [${s}]`));
            bufferReady = true;
          }
        }
      });

      const wait = () => new Promise(res => {
        const f = () => {
          if(bufferReady) res(bufferReady = false);
          else setTimeout(f);
        };
        f();
      });

      await wait();
      console.log(`OUTSIDE1: [${buffer.length}]`);
      buffer.forEach(s => console.log(`OUTSIDE1: [${buffer.length} ${s}]`));

      child.stdin.write('select * from table');
      buffer.length = 0;

      await wait();
      console.log(`OUTSIDE2: [${buffer.length}]`);
      buffer.forEach(s => console.log(`OUTSIDE2: [${buffer.length} ${s}]`));
    })().catch(reject);
  });
}
```

Hope this helps. Note: it's unclear what `command` you are trying to spawn. In this example, we spawn a Node.js process instead. You can replace `node -e` with your own program name.

**Comment by FleXoft** [comment]
Hello Hakerh400,

 Thanks for your answer and time!

 Here is another example: this is somthing I really want to create. A CLI (dsmadmc) command line tool(which runs in the background) wrapper.

---
#! /usr/bin/env node

function prompt() {
  var arrow  = '> ', 
      length = arrow.length;
  rl.setPrompt( arrow.bold.red, length );
  rl.prompt();
}

function quit() {

  process.stdout.write( '\nGoodbye! Thanks for using it!'.green );
  process.exit( 0 );

}

function exec( command ) {

    process.stdout.write( "DEBUG: Received command [".bold.green + command.bold.yellow + "]\n".bold.green );

    switch ( command.toLowerCase() ) {

        case 'print':
            buffer.forEach( function( s ) {
                process.stdout.write( s + "\n" );
            } );
            prompt()
            break;

        case 'exit':
        case 'quit':
        case 'q':
            quit();
            break;

        default:
            child.stdin.write( command + "\n" );

            // clear the buffer if not needed anymore
            buffer = [];
    }

}

// main()
var colors   = require( "colors" );
var readline = require( "readline" );
var child_pr = require( "child_process" );

var screenColumns = 80, screenRows = 25;

// https://nodejs.org/api/child_process.html
// https://github.com/nodejs/help/issues/1183
// https://www.ibm.com/support/knowledgecenter/SSEQVQ_8.1.6/srv.reference/r_cmdline_adclient_options.html
const child = child_pr.spawn( 'dsmadmc', [ '-ID=support', '-PA=asdpoi123', '-comma', '-ALWAYSPrompt' ], { detached:true } );
// '-NEWLINEAFTERPrompt'

child.once( "exit", function ( errocode, signal ) {
    console.log( "DSMADMC: exited ".red + "with code: " + errorcode + "SIGNAL: " + signal );
} );

child.once( "close", function ( errocode, signal ) {
    console.log( "DSMADMC: closed ".red + "with code: " + errorcode + "SIGNAL: " + signal );
} );

buffer = [];
var bufferReady = false;

child.stderr.once( "data", data => reject( String( data || "empty stderr.\n" ) ) );

child.stdout.on( "data", function( data ) {

    var s = String( data );
    buffer = buffer.concat( s.split( "\n" ) );

    process.stdout.write( "DEBUG: ".bold.green + "-".repeat( screenColumns - 7 ).grey );
    buffer.forEach( function( s ) {
        process.stdout.write( "DEBUG: [".bold.green + s.grey + "]\n".bold.green );
    } );
    process.stdout.write( "DEBUG: ".bold.green + "-".repeat( screenColumns - 7 ).grey );

    var match = buffer[buffer.length - 1].match( /^Protect: (\w+)>/ );
    if ( match ) {

        buffer.pop();                       // remove it we dont need
        buffer = buffer.filter( n => n );   // clean empty lines

        var line = "-".repeat( screenColumns - 4 );
        process.stdout.write( "\rTSM " + line.grey + "\n" );

        buffer.forEach( function( s ) {

            if ( s.match( /^(\s*$|IBM Spectrum Protect|\(c\) Copyright by IBM Corporation and other\(s\) 1990, \d\d\d\d\. All Rights Reserved\.|\s+Server Version \d, Release \d, Level \d\.\d+|\s+Server date\/time.*|Command Line Administrative Interface - Version \d, Release \d, Level \d\.\d+)$/ ) ) {
                // skip it      
            }
            else {

                match = s.match ( /^ANS8001I.*\s+(\d+)\.$/ )
                if ( match ) {
                    process.stdout.write( "DEBUG: LAST ERROR [".bold.green + match[1].bold.red + "]\n".bold.green );
                }
                else {
                    // output 
                    process.stdout.write( s + "\n" );
                }
            }

        } );

        process.stdout.write( line.grey + " TSM\n" );
        
        bufferReady = true;
        prompt();

    }

} );

child.stdout.on( 'end', function() {
        console.log( "\nENDEND\n".bold.red );
    }
);
      
rl = readline.createInterface( {
    input: process.stdin,
    output: process.stdout
} );

rl.on( 'line', function( cmd ) {

    if ( cmd.match( /^\s*$/ ) ) {
        prompt();
    }
    else {
        exec( cmd.trim() );
    }

} );

rl.on( 'close', function() {

    quit();

} );
 
prompt()

console.log ( 'dsmadmc PID#: [' + child.pid.toString().bold.red + ']' );


child.stdin.write( "select node_name from nodes where node_name like '%'" + "\n" );
buffer.forEach( function(s) { console.log*( s ) } );
---

What I need:
 - keep the dsmadmc process running in the background
 - and sometimes just send a command and print its output (this is already working as expected)
 - and sometimes send a command to the background process via its own stdin and get back the output in that buffer and made some transfomation after it and print the transfomed text to the console (for example the last two lines would make it) (and this is not working, beacause the buffer is always empty)
 - the strangest thing is when i use type my own print command in the readline prompt IT WORKS as i expected, that buffer is not empty and prints the last buffer content (why that part works???)  

Cheers.

**Comment by FleXoft** [comment]
I made a more simple example:

`
var colors   = require( "colors" );
var readline = require( "readline" );
var child_pr = require( "child_process" );

var buffer = [];
var bufferReady = false;

const child = child_pr.spawn( 'dsmadmc', [ '-ID=support', '-PA=asdpoi123', '-comma', '-ALWAYSPrompt' ], { detached:true } );

child.stdout.on( "data", function( data ) {

    var s = String( data );
    buffer = buffer.concat( s.split( "\n" ) );

    buffer.forEach( function( s ) {  process.stdout.write( "STDOUT:" + s + "\n" ); } );

    prompt();

} );

function exec( command ) {

    switch ( command.toLowerCase() ) {

        case 'select':
        	buffer = [];
            child.stdin.write( "select node_name from nodes where node_name like '%'" + "\n" );

**// I want to wait for the buffer here and print it**
buffer.forEach( function( s ) {  process.stdout.write( "SELECT:" + s + "\n" ); } );
           
            prompt();
            break;

        case 'print':
            buffer.forEach( function( s ) { process.stdout.write( "STDOUT:" + s + "\n" ); } );

            prompt()
            break;

        case 'exit':
        case 'quit':
        case 'q':
            quit();
            break;

        default:
            buffer.length = 0;
            child.stdin.write( command + "\n" );

    }

}

function prompt() {
  var arrow  = '> ', 
      length = arrow.length;
  rl.setPrompt( arrow.bold.red, length );
  rl.prompt();
}

var rl = readline.createInterface( {
    input: process.stdin,
    output: process.stdout,
} );

rl.on( 'line', function( cmd ) {

    if ( cmd.match( /^\s*$/ ) ) {
        prompt();
    }
    else {
        exec( cmd.trim() );
    }

} );

prompt();`

**Comment by Hakerh400** [comment]
In the simplified example, where do you set the `bufferReady` to `true`? It always remains `false`. You probably want to set it to `true` in the `on('data', ...)` listener.

But I already posted the solution you need. Did you read the code I wrote above? You need to use `async` function and call `await wait()` before accessing buffer (see the definition `const wait = () => ...` in my example). Then you need to make your `exec` function asynchronous by adding `async` before it (`async function exec( command ) { ... }`) and you need to add `await wait()` after the `child.stdin.write` in the `select` branch of the `switch` statement.

That should solve your problem. Not sure what difficulties you're having with applying these suggestions.

```js
var colors   = require( "colors" );
var readline = require( "readline" );
var child_pr = require( "child_process" );

var buffer = [];
var bufferReady = false;

const wait = () => new Promise(res => {
  const f = () => {
    if(bufferReady) res(bufferReady = false);
    else setTimeout(f);
  };
  f();
});

const child = child_pr.spawn( 'dsmadmc', [ '-ID=support', '-PA=asdpoi123', '-comma', '-ALWAYSPrompt' ], { detached:true } );

child.stdout.on( "data", function( data ) {

    var s = String( data );
    buffer = buffer.concat( s.split( "\n" ) );

    buffer.forEach( function( s ) {  process.stdout.write( "STDOUT:" + s + "\n" ); } );

    if(/^Protect/.test(buffer.slice(-1)[0])){
      buffer = buffer.filter((s, i) => s.length !== 0 && i !== buffer.length - 1);
      buffer.forEach(s => console.log(`INSIDE: [${s}]`));
      bufferReady = true;
    }

    prompt();

} );

async function exec( command ) {

    switch ( command.toLowerCase() ) {

        case 'select':
            buffer.length = 0;
            child.stdin.write( "select node_name from nodes where node_name like '%'" + "\n" );

            await wait();
            buffer.forEach( function( s ) {  process.stdout.write( "SELECT:" + s + "\n" ); } );
           
            prompt();
            break;

        case 'print':
            buffer.forEach( function( s ) { process.stdout.write( "PRINT:" + s + "\n" ); } );

            prompt()
            break;

        case 'exit':
        case 'quit':
        case 'q':
            quit();
            break;

        default:
            buffer.length = 0;
            child.stdin.write( command + "\n" );

    }

}

function prompt() {
  var arrow  = '> ', 
      length = arrow.length;
  rl.setPrompt( arrow.bold.red, length );
  rl.prompt();
}

var rl = readline.createInterface( {
    input: process.stdin,
    output: process.stdout,
} );

rl.on( 'line', function( cmd ) {

    if ( cmd.match( /^\s*$/ ) ) {
        prompt();
    }
    else {
        exec( cmd.trim() );
    }

} );

prompt();
```

**Comment by FleXoft** [comment]
It's clear now. Thanks for your help, I really appreciate it!
