### ISSUE TITLE
Install node.js on new PC

### ISSUE THREAD

**Issue by derman10** [nodejs/help#1669]
* **Node.js Version**: node-v10.14.2-win-x64
* **OS**: windows 10 x64

I started install Node.js/Ionic framework in a new PC (notebook Windows 10 x64).

I installed node.js, Visual Studio Code and Java JDK.

Then from command line run:

`npm install -g ionic cordova`

Install finish OK.

But when run node --version I get this result (link image)

https://i.stack.imgur.com/PfubX.jpg

If I run` ionic start helloWorld blank --cordova` I get the same result.

I have uninstalled and reinstalled node.js but the problem persists.

Any idea???

Thanks!

**Comment by richardlau** [comment]
What does `where node` report?

Is it possible you are running into https://stackoverflow.com/questions/14882427/running-node-js-code-just-displays-a-node-identifier?

**Comment by gireeshpunathil** [comment]
ping @derman10 - let me know if this is resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing
