### ISSUE TITLE
Node JS with Angular 7 --> ng new app cmd results in Error: Cannot find module './fs.js'

### ISSUE THREAD

**Issue by zoezydk** [nodejs/help#1670]
* **Node.js Version**: v10.14.2
* **OS**: Windows 10/64-bit
* **Scope (install, code, runtime, meta, other?)**: Runtime (Angular 7 --> ng new app)
* **Module (and version) (if relevant)**: FS module

Trying to run the following command _ng new app_ in my workspace using Angular 7 with latest Node.js suddenly results in the below error using the CLI.
![image](https://user-images.githubusercontent.com/12489567/49996066-400f8d00-ff8e-11e8-9b1d-9f58611d1194.png)

Tried to reinstall latest version of Node.js server which didn't change the above behavior.

**Wanted:** Steps to fix the above error.

Thanks in advance.

**Comment by matthewpurchese** [comment]
I got this error and resolved by deleting
%appdata%\npm\node_modules\@angular\cli\node_modules

Then running
npm install -g @angular/cli

**Comment by zoezydk** [comment]
@matthewpurchese Hi there! And many thanks for the feedback. Thanks a million actually! :-) This fixed it. Even made it better with options to decide on whether or not to use routing and which CSS type to use which I think, I didn't get before. Outstanding! Thank you very much! 👍 🥇 If you need help and I can give you back some day, please do let me know. Wishing you a nice day.

**Comment by matthewpurchese** [comment]
You're welcome!  Not sure why it works, it seems like the package cache got corrupted somehow.  Other members of my team with an identical setup have had no issues.

**Comment by zoezydk** [comment]
@matthewpurchese Yes, I was surprised as well as I'm unable to trace the cause of this error. I don't recall having done anything to corrupt the files nor the node_modules directory. But then again..., with IT it's a bit like Murphy's law. ;-) So I'm just happy that things work again. Thanks a mountain again! 👍

**Comment by gireeshpunathil** [comment]
resolved, closing

**Comment by barry-ruprai** [comment]
I removed the node modules folder and
then reinstall all the packages 

Error goes away
