### ISSUE TITLE
NPM Uninstall/Remove fails on macOs Mojave

### ISSUE THREAD

**Issue by foo-baar** [nodejs/help#1671]
* **Node.js**: v11.3.0
* **OS**: macOs Mojave
* **Scope**:  Global Packages

After updating to Mojave I ran into lot of issues with terminal & packages, most of them got sorted, but not able to remove NPM packages, this is what it shows after running the command:

![](https://i.stack.imgur.com/hVoUB.png)

npm prune shows:

![screen shot 2018-12-14 at 10 38 04 am](https://user-images.githubusercontent.com/13655874/50012350-616f7980-ff8c-11e8-98ea-6a979e84b1a2.png)

(any help would be highly appreciated).

Thanks

**Comment by Hakerh400** [comment]
I think you need to run `uninstall yo` instead of `uninstall yo@2.0.5`. This is what I get:

```console
$ npm list -g --depth=0
/usr/local/lib
├── npm@5.6.0
└── yo@2.0.5

$ sudo npm uninstall -g yo@2.0.5
up to date in 0.054s
$ sudo npm uninstall -g yo
removed 542 packages in 6.842s
$ npm list -g --depth=0
/usr/local/lib
└── npm@5.6.0
```

**Comment by foo-baar** [comment]
@Hakerh400 : Can' believe I can be this Idiot at the times, Worked like a charm, you are the saver.
