### ISSUE TITLE
I am not able to understand the Node.Js architecture in context of event loop.

### ISSUE THREAD

**Issue by akshayarise** [nodejs/help#1672]
I am not able to understand the Node.Js architecture in context of event loop inspite of following the official docs. Can anyone please share the resources?

**Comment by ORESoftware** [comment]
It's a bit complicated. Basically, V8 interprets the JavaScript, and Libuv provides the event loop. But that begs the question - what provides the event loop in the Chrome browser? I don't know the answer.

**Comment by AyushG3112** [comment]
This might help explain a little: https://youtu.be/8aGhZQkoFbQ

**Comment by akshayarise** [comment]
Already watched this but not got it in depth.

**Comment by Qix-** [comment]
Actually @AyushG3112's link goes **very** deep into what an event loop is and why it's helpful. I'd recommend re-watching it and really trying to understand what the talk is about.

**Comment by gireeshpunathil** [comment]
@akshayarise - are there any specific questions you have, and if so please post it here, I will try to explain.

**Comment by gireeshpunathil** [comment]
inactive, closing
