### ISSUE TITLE
Socket event 'timeout' is fired why?

### ISSUE THREAD

**Issue by RadoslavMarinov** [nodejs/help#1676]
* **v10.11.0**:
* **Win 7**:
* **Other**:

I have simple server example. In my server I have to close the underlying `NET` socket after the response is sent to the client. I tried this.

```
    var counter = 0;
    
    app.post("/enddev", (req, res) => {
      console.log("REQUEST TO ", req.route.path);
    
      setInterval(() => {
        console.log(++counter);
      }, 1000);
    
      setTimeout(() => {
        res.write("upd\r\n");
        res.end();
      }, 1000);
    
      res.on("finish", () => {
        console.log("Res socket: ", res.socket);
      });
    });


    server.on("connection", socket => {
      console.log(
        "New connection",
        "Address: " + socket.address().address,
        "Port: " + socket.address().port
      );
    
      socket.on("timeout", () => {
        console.log("socket timeout");
        socket.end();
      });
    
      socket.on("error", err => {
        console.log("Socket error: ", err);
      });
    
      socket.on("close", hadError => {
        console.log(
          hadError
            ? "Socket closed due to ERROR during transmission"
            : "Socket closed"
        );
      });
    });
```

When I run this program I observe that the socket is closed about 5 seconds after request is issued. Socket do not close upon `res.end()` but 5 seconds later.

This is console snapshot of program running:
![capture](https://user-images.githubusercontent.com/15731937/50090824-5cbbf700-0212-11e9-9cd8-e450bbbd80e1.PNG)

I want to close the socket immediately after `res.end()`.
And why is the event `timeout` fired?

**Comment by gireeshpunathil** [comment]
@RadoslavMarinov - I ran a basic version of this code (without a middleware, but using only node core APIs) and could not observe this behavior.

So it is possible that the middleware has additional logic that holds the socket beyond its requirement.

In the server's `connection` callback, can you print the entire `socket` object, and see specific attributes pertinent to timeout etc.? IIUC, this socket object will be an integrated one with the core's socket and the middleware's additional attributes, and those additional one may throw light into why it is being held for long.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if there is anything outstanding here
