### ISSUE TITLE
How to spawn a vimdiff session in node js?

### ISSUE THREAD

**Issue by niwsa** [nodejs/help#168]
Inside a node js program I need to spawn vimdiff(vim -d).I am not getting it right with the below settings.

```
  var spawn = require('child_process').spawn;
  var args =  ['-d', file1 , file2];
  var options = { stdio: 'inherit' };
  var vimdiff = spawn('/usr/bin/vim',args,options);

```
What is the perfect way to achieve this?

**Comment by bnoordhuis** [comment]
You probably want https://www.npmjs.com/package/pty.js.

**Comment by niwsa** [comment]
Thanks that was quick :) will give it a try

**Comment by niwsa** [comment]
But the module installation is failing with errors.
[npm-debug.zip](https://github.com/nodejs/help/files/272128/npm-debug.zip)

**Comment by niwsa** [comment]
I just needed spawnSync http://stackoverflow.com/questions/27045726/stdio-piping-issues-when-using-vim-in-child-process-in-node-js/28491176#28491176.
