### ISSUE TITLE
gulp watch issue

### ISSUE THREAD

**Issue by sbcmeg** [nodejs/help#1680]
* **v10.14.2**:
* **OS High Sierra**:

I'm running gulp watch in a project that uses sage 8.5.1. I followed the setup process:
Install gulp and Bower globally with npm install -g gulp bower
Navigate to the theme directory, then run npm install
Run bower install

I then run gulp watch within the theme directory and get this:
gulp watch[8188]: ../src/node_contextify.cc:633:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x10003b125 node::Abort() [/usr/local/bin/node]
 2: 0x10003a183 node::AddEnvironmentCleanupHook(v8::Isolate*, void (*)(void*), void*) [/usr/local/bin/node]
 3: 0x100064bc1 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x10023122f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1002303cb v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x10022fde7 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x22e57615be3d 
Abort trap: 6

**Comment by Qix-** [comment]
I can't speak for why you're getting that abort, but I just wanted to mention that [Bower is deprecated](https://bower.io/blog/) and should no longer be used.

**Comment by gireeshpunathil** [comment]
in either case, this should be reported to Bower. Closing as wrong repo
