### ISSUE TITLE
agent.createConnection() === net.createConnection() ??

### ISSUE THREAD

**Issue by spazmodius** [nodejs/help#1681]
* **Node.js Version**: v10.14.2
* **OS**: Windows 10
* **Scope**: runtime and doc
* **Module**: `net` and `http`

The documentation says, of `agent.createConnection()`, "[by default, this function is the same as net.createConnection()](https://nodejs.org/docs/latest-v10.x/api/http.html#http_agent_createconnection_options_callback)".  Sure enough, a quick 

```js
new http.Agent().createConnection === net.createConnection   // true
```

seems to confirm this statement.

However, the callback arguments are different:
 - net.createConnection takes a `connect` event listener, and has no arguments
 - agent.createConnections takes a `(err, stream)` callback

So how can one function substitute for the other?  Please clear up my confusion.

**Comment by gireeshpunathil** [comment]
ping @nodejs/http

**Comment by benjamingr** [comment]
This is just because while all these overloads are in fact supported in `agent.createConnection` it limits the API surface for custom `http.Agent` implementations. Namely as you quoted it is the same _by default_ :)

**Comment by spazmodius** [comment]
So, by default, the callback to `agent.createConnection` _will not_ receive the documented arguments?

**Comment by benjamingr** [comment]
By default there are several overloads depending on what parameters you pass it - but don't rely on that if accepting an `http.Agent` instead only rely on the overload documented since that is the one custom agents will always support.

**Comment by spazmodius** [comment]
I'm not clear what you mean. Should I rely on "callback has a signature of (err, stream)"? That doesn't seem to hold.

**Comment by spazmodius** [comment]
Hm, maybe what you're saying is that the signature of `agent.createConnection` matches one of the signatures of `net.createConnection`. I agree the headline looks that way.

However, they document different semantics for their `callback`/`connectListener` parameter, making them incompatible.
