### ISSUE TITLE
create HTTP server from incoming raw socket

### ISSUE THREAD

**Issue by FranckFreiburger** [nodejs/help#1682]
* **Node.js Version**: v11.3.0
* **OS**: win7 64
* **Scope**: net + http

I am trying to create an HTTP server from incoming net Socket.
The following code uses a "private API" : `_connectionListener` ([src](https://github.com/nodejs/node/blob/e1ab457490925ddbf9f234973c4338bd0690acb5/lib/_http_server.js#L323))
I wondering if there is another way to achieve this using only public API ?

```js
const Net = require('net');
const Http = require('http');

var httpServer = new Http.Server( (req, res) => {

	res.write('hello at '+req.url);
	res.end();
});
var server = Net.createServer(Http._connectionListener.bind(httpServer));
server.listen(80);
```

_details:_ I am building an application server where the protocol related to the incoming socket is selected subsequently.

**Comment by gireeshpunathil** [comment]
ping @nodejs/http

**Comment by gireeshpunathil** [comment]
@FranckFreiburger - I guess I miss-interpreted your second comment. Looking at that again, I see you proposed the resolution itself, and there is nothing left to resolve here. So closing, let me know if I am wrong.
