### ISSUE TITLE
[HELP] customize ETIMEDOUT limit time

### ISSUE THREAD

**Issue by nameszian** [nodejs/help#1686]
* **Node.js Version**: v10.14.2 | v12.0.0-pre
* **OS**: macOS 10.14
* **Scope**: Official module
* **Module**: net

How can I change the time for an `ETIMEDOUT` to come out/trigger? (I'd like to reduce it, because now it's 1 minute and 15 seconds `wow!`, and it's too much)

I'm using `socket.connect()` from the [official](https://nodejs.org/docs/latest-v10.x/api/net.html#net_socket_connect) `net` module and I do not see by any means how I can reduce this time, e.g. to 10 seconds.

Any ideas?

Thank you!.

**Comment by nameszian** [comment]
That's how the code is, and now it takes 1 minute and 17 (or 18) seconds... I tried it also on Linux and it also took more than 30 seconds... Can not force a custom time?
```
  this.device = new net.Socket();
  [...]
  [...]
  this.device.setTimeout(2000);
  this.device.on("error", (err) => {
      [...]
  });
  this.device.connect(this.port, this.address, function(err){
      [...]
  });
```

**Comment by gireeshpunathil** [comment]
I don't see any issues. Here is my output with ndoe `v10.5.0`. Can you pls check it out yourself?

$ cat 1686.js 
```js
  const n = require('net')
  const p = new n.Socket()
  p.setTimeout(process.argv[2] / 1)
  var start = process.hrtime()
  p.on('timeout', () => {
    var diff = process.hrtime(start)
    console.log(`timed out in ${diff[0]} seconds, ${diff[1] / (1000 * 1000)} millseconds`)
  })
  p.connect(32000, () => {
    console.log('connected')
  })
```

```gdb
#node 1686 100
timed out in 0 seconds, 110.314481 millseconds
^C
#node 1686 200
timed out in 0 seconds, 215.212073 millseconds
^C
#node 1686 300
timed out in 0 seconds, 310.561246 millseconds
^C
#node 1686 400
timed out in 0 seconds, 411.230087 millseconds
^C
#node 1686 500
timed out in 0 seconds, 509.372174 millseconds
^C
#node 1686 1000
timed out in 1 seconds, 12.355001 millseconds
^C
```

**Comment by nameszian** [comment]
I think you have not understood the problem or I have not explained myself, I DO NOT want to add more waiting time for trigging `ETIMEDOUT`, I want to remove it (or change it), the only thing that is done with `setTimeout` is add more waiting time.

So you can see what the problem is, I will execute your code (with `time` unix-like command to observe how long it takes), with argument `0`, basically `setTimeout(0)` and observe `real 1m15.361s` or `[AAAA@@@@!!!!]` (ignore the exception, that is simply because the ETIMEDOUT error is not controlled in your code):

*$* cat index.js # modified version with address and port in .connect().

```
  const n = require('net');
  const p = new n.Socket();
  p.setTimeout(process.argv[2] / 1);
  var start = process.hrtime()
  
  p.on('timeout', () => {
    var diff = process.hrtime(start)
    console.log(`timed out in ${diff[0]} seconds, ${diff[1] / (1000 * 1000)} millseconds`)
  })
  p.connect(9100, '192.168.1.10', () => {
    console.log('connected');
  })
```

*$* time node index.js 0
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.10:9100
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

real	1m15.361s # <-- [AAAA@@@@!!!!]
user	0m0.068s
sys	0m0.023s
```

**Comment by Qix-** [comment]
You can't - and why would you? Either a connection can succeed, or it can't. If you want something to reconnect, you need to implement this logic yourself.

What the kernel is doing underneath is trying to send a TCP `SYN` packet to the remote host. Based on roundtrip time, the kernel attempts to calculate how long a connection **should** take. This is what determines the `ETIMEDOUT` delay time. It's not customizable - there is nothing Node.js can do.

It look like you're trying to solve the problem of a host being up or down randomly. You need to add your own logic surrounding TCP reconnects. Node won't do it for you (and that's okay).

**Comment by gireeshpunathil** [comment]
@nameszian - is this still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by rioastamal** [comment]
My solution to this problem is to use global Timer setTimeout function and call `destroy()`.

```javascript
  const n = require('net');
  const p = new n.Socket();
  p.setTimeout(process.argv[2] / 1);
  var start = process.hrtime()
  
  p.on('timeout', () => {
    var diff = process.hrtime(start)
    console.log(`timed out in ${diff[0]} seconds, ${diff[1] / (1000 * 1000)} millseconds`)
  })
  p.connect(9100, '192.168.1.10', () => {
    console.log('connected');
  })

  // Abort the request if longer then 10 seconds
  setTimeout(() => p.abort(), 10000)
```
