### ISSUE TITLE
Node is not reading first stdout from childprocess.exec

### ISSUE THREAD

**Issue by elpeleq42** [nodejs/help#1688]
* **Node.js Version**:Last
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: Child Process

I'm using the code bellow to spawn a .exe file, which is quite simple: It writes "Enter a value :", waits for your input and then writes "You entered:"+yourinput

I expect it to spawn a the .exe, receive it's initial message("Enter a value :"), then send an input and receive the output.

Problem is: It's not receiving the first "Enter a value :" message before I send it an input to the child process. Only when I send, I receive all the text I expected. How could I manage to receive the first message right when I open the test.exe(in a "Live" way)?

```
var child = require('child_process');


meudeus=child.exec('test.exe',{
  cwd: 'c:/Users/gabriel/desktop'
},function(error, stdout, stderr) {
  if(error){console.log(error)}
    else {if(stdout){console.log(stdout)}
if(stderr){console.log(stderr)
  }
}

});

//// In another function there's this:
meudeus.stdin.write('Input')
```

The C code in the test.exe file is:

```
#include <stdio.h>
int main( ) {

   int c;

   printf( "Enter a value :");
   c = getchar( );

   printf( "\nYou entered: ");
   putchar( c );

   return 0;
}
```

**Comment by Hakerh400** [comment]
The stdout buffer must be explicitly flushed from C program using `fflush` function.

```c
// test.c

#include <stdio.h>

int main(){
  int c;

  printf("Enter a value: ");
  fflush(stdout);
  
  c = getchar();
  printf("\nYou entered: ");
  putchar(c);

  return 0;
}
```

```js
// index.js

const cp = require('child_process');
const child = cp.spawn('test.exe');
const input = 'A';

child.stdout.once('data', data => {
  process.stdout.write(data);
  process.stdout.write(input);
  child.stdin.write(input);
  child.stdout.pipe(process.stdout);
});
```

### Result

```console
> node index.js
Enter a value: A
You entered: A
```

**Comment by elpeleq42** [comment]
> The stdout buffer must be explicitly flushed from C program using `fflush` function.
> 
> ```c
> // test.c
> 
> #include <stdio.h>
> 
> int main(){
>   int c;
> 
>   printf("Enter a value: ");
>   fflush(stdout);
>   
>   c = getchar();
>   printf("\nYou entered: ");
>   putchar(c);
> 
>   return 0;
> }
> ```
> 
> ```js
> // index.js
> 
> const cp = require('child_process');
> const child = cp.spawn('test.exe');
> const input = 'A';
> 
> child.stdout.once('data', data => {
>   process.stdout.write(data);
>   process.stdout.write(input);
>   child.stdin.write(input);
>   child.stdout.pipe(process.stdout);
> });
> ```
> 
> ### Result
> ```
> > node index.js
> Enter a value: A
> You entered: A
> ```

I had found a "solution" to a similar issue, which didn't require that flush(but it is for "spawn" not "exec"). Would there be a similar way to do so with exec? I would prefer to not demand those who will use my application to modify their files(if possible, obviously)

**Comment by gireeshpunathil** [comment]
ping @elpeleq42

**Comment by gireeshpunathil** [comment]
inactive, closing
