### ISSUE TITLE
why https did not response?

### ISSUE THREAD

**Issue by williambai** [nodejs/help#169]
I try to access https://cbss.10010.com use https module as followings:

var https = require('https');
var options = {
	// key: fs.readFileSync(keyFile),
	// cert: fs.readFileSync(certFile),
	// ca: fs.readFileSync(caFile),
	rejectUnauthorized: false,
	family: 4,
	hostname: 'cbss.10010.com',
	port: 443,
	path: '/essframe',
	method: 'GET',
	headers: {
		'Accept-Language': 'zh-CN',
		'Accept': 'text/html, application/xhtml+xml, */*',
		'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
		'Connection': 'Keep-Alive',		
	}
};

options.agent = new https.Agent(options);
// process.debug = true;
var req = https.request(
	options, function(res){
  console.log('statusCode: ', res.statusCode);
  console.log('headers: ', res.headers);

  res.on('data', function(d){
    process.stdout.write(d);
  });
});
req.end();
req.on('error', function(e){
  console.error(e);
});
--------
and after serval seconds, it timeouts and get the following error:
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

whenever I changed the options, it is still the same problem.

but when i  can use curl to get response quickly.

curl -k https://cbss.10010.com

why?

**Comment by lordKnighton** [comment]
Hey @williambai are you still having problems with this?
