### ISSUE TITLE
Problem Building V8 Bundled with Nodejs Source

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/help#1691]
* **Node.js Version**: 11.5.0
* **OS**: Windows 10 Home Single Language, 10.0.17134 Build 17134
* **Scope (install, code, runtime, meta, other?)**: building
* **Module (and version) (if relevant)**: (not sure what to put here)

When building Nodejs after running `git pull` and also updating submodules, I generated project files with `vcbuild` with the `nobuild` setting so that I could manually provide settings in the IDE when building, like the location of zlib and correct name of the input file to link against.  Then I decided I'd build the dependencies first and then the main stuff like node_lib.vcxproj.  I built the OpenSSL and Libuv stuff fine, but 18 out of 32 of the projects for V8 failed to build.  I have 1,899 errors.  I used C++17 with Standards conformance mode on (`/permissive-` flag).  

In the documentation for `std::unary_function` on cppreference.com, it says that 
```cpp
template <typename ArgumentType, typename ResultType>
struct unary_function;
```
is deprecated in C++11 and removed in C++17.  A lot of the errors are because of this.  I'll build those projects using C++14 rules for now, but I think you guys should consider updating the code so that it compiles under C++17 rules.  Just a suggestion.

**Comment by DragonOsman** [comment]
I successfully built all of the dependencies by using C++14 for the ones where `std::unary_function` was being used and C++17 for the rest.  But building cctest failed with a linker error saying that certain symbols were already defined in zlib.lib.  These errors are from zlib.dll.  What should I do?  Remove cctest from the build until I find a fix?  

And speaking of a fix, I'd like it if you guys could help me find one.

**Comment by gireeshpunathil** [comment]
ping @DragonOsman - is this still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing
