### ISSUE TITLE
Leaving NodeJS after years of learning and writting projects - Back to PHP

### ISSUE THREAD

**Issue by azev** [nodejs/help#1693]
After years of learning and writting projects in NodeJS, I've just loved it. It is powerful, portable and fit all my needs as a developer.

However, after looking up the internet for hosting a NodeJS application, I stumble upon a big problem that seems to be global.

All major web hosting services I've tried do not support NodeJS natively in their regular plans/packages.
To run a NodeJS server I'd have to hire a VPS service which costs at least 10x more than regular PHP hosting.

No matter how good NodeJS is. If it costs 10x more to be hosted online then it is time to move back to PHP.

That is very sad. So long NodeJS. Back to the 90s.

**Comment by gireeshpunathil** [comment]
there is no request that needs a help here, closing.
