### ISSUE TITLE
npm ERR! 403 Forbidden: path-is-absolute@^1.0.0 installing angular cli

### ISSUE THREAD

**Issue by amathm** [nodejs/help#1694]
node: v11.6.0
os: macOS 10.13.6

I can't solve this problem and can really do with some help, I have a problem running 

> `npm install -g @angular/cli`

I keep getting the following error

> `npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 403 Forbidden: https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz
> 
> npm ERR! code E403
> npm ERR! 403 Forbidden: path-is-absolute@^1.0.0
> `

prior to this error i was getting 
`

> Error 418 "I'm a teapot", 

`

which i believe is to do with the registry; I've tried to solve that error though changing ... 

> `npm config set registry https://registry.npmjs.org`

from https to http but that didn't work, I've deleted prier node installs and have tried a litany of things. 

can anyone help me figure this out. 

**update:** I am behind a proxy; I have homebrew, nvm installed and I am currently experiencing nvm isuess as well

> `nvm ls-remote `

returns N/A; 
not sure if its related. I had a perfectly functional installation but problems started overnight; this might be a proxy related issue, and the fact that I've been trying to solve it for a while has probably created more problems.

**Comment by amathm** [comment]
oh alright thanks QIX and Yes I am behind a proxy.

**Comment by amathm** [comment]
> * Don't change `https` to `http`, there's no need and `https` is more secure - that is the source of your `418 I'm a teapot` message
> * Anything that says `WARN optional` can be safely ignored. `fsevents` is a common culprit here, as it tries to install native (C or C++) code that speeds up some filesystem operations, but doesn't work on all platforms.
> * The 403 is strange - are you behind a proxy?

oh alright thanks QIX and Yes I am behind a proxy.

**Comment by Qix-** [comment]
Check your proxy settings, make sure npm can reach the registry from behind it. That's the most common culprit of 403's.

**Comment by amathm** [comment]
> Check your proxy settings, make sure npm can reach the registry from behind it. That's the most common culprit of 403's.

Its a corporate proxy, so I have limited control in terms setting access; But what I don't understand is that it was working perfectly, till overnight.

QIX I'm think of opening a new issue and closing this one, since the error has to change to 

> `npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>`

**Comment by amathm** [comment]
> Check your proxy settings, make sure npm can reach the registry from behind it. That's the most common culprit of 403's.

it's configured through a proxy pac file.

**Comment by jamivinaysagar** [comment]
This can be fixed by the doiing following: this worked for me
npm logout
npm login https://registry.npmjs.org
provide your user name, password and email id

**Comment by kkrpati** [comment]
Any resolution for this? I am facing the same issue.
