### ISSUE TITLE
Unresolved External Symbol Error -- "__imp_read", "__imp_write", "__imp_open"

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/help#1695]
* **Node.js Version**: 11.6.0
* **OS**: Windows 10 Home Single Language. Version 1803, Build 17134.472
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**:

I downloaded the source code for version 11.6.0 from the Nodejs website and tried to build it (directly using IDE GUI).  Before running `vcbuild`, I ran this command: 
```
set config_flags=--shared-zlib --shared-zlib-libname=zlibstatic.lib --shared-zlib-libpath="C:\\zlib_library\\lib" --shared-zlib-includes="C:\\zlib_library\\include" --fully-static --with-ltcg --dest-cpu=x64 --without-etw
```
And then I ran `vcbuild` like this:
```
.\vcbuild release static vs2017 noetw ltcg no-cctest nobuild
```
Most of it builds successfully, but I have these linker errors when I try to build node.vcxproj:
```

39>zlibstatic.lib(gzlib.obj) : error LNK2001: unresolved external symbol __imp_open
39>OLDNAMES.lib(open.obi) : error LNK2001: unresolved external symbol __imp_open
39>zlibstatic.lib(gzread.obj) : error LNK2001: unresolved external symbol __imp_read
39>OLDNAMES.lib(read.obi) : error LNK2001: unresolved external symbol __imp_read
39>zlibstatic.lib(gzwrite.obj) : error LNK2001: unresolved external symbol __imp_write
39>OLDNAMES.lib(write.obi) : error LNK2001: unresolved external symbol __imp_write
39>C:\node-v11.6.0\Release\node.exe : fatal error LNK1120: 3 unresolved externals
```
What library am I missing?  Could someone please help me out?  Thanks in advance.

Note: When I try to link against zlib.lib, it also brings in zlib.dll and then I get multiply-defined symbol errors.

**Comment by gireeshpunathil** [comment]
with `--shared-zlib`, I guess the builder expects a system supplied zlib. On the face of it, the error looks like either the library is not picked for linking, or it is picked up, due to version mismatch, it does not have enough symbols that node is expecting it to have. cc @nodejs/zlib

**Comment by addaleax** [comment]
I feel like this might be a question more for @nodejs/platform-windows than specifically zlib, if @DragonOsman is still looking for an answer :)

**Comment by gireeshpunathil** [comment]
@DragonOsman - is this still unresolved?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
