### ISSUE TITLE
git batch and node version

### ISSUE THREAD

**Issue by Asmith68** [nodejs/help#1697]
* **Node.js Version**:latest just downloaded today
* **OS**:win 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Not sure if this is the correct place for this question sorry if it is not. 
I am working on a tut the uses get batch and nodejs, I installed git batch then nodejs.  when I run node --version I get the below message.
Any ideas what my issue is?

$ node -- version                                                                    internal/modules/cjs/loader.js:583                                                       throw err;                                                                           ^                                                                                                                                                                     Error: Cannot find module 'C:\Users\Smith\version'                                       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)          at Function.Module._load (internal/modules/cjs/loader.js:507:25)                     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)                   at startup (internal/bootstrap/node.js:283:19)                                       at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
--

**Comment by vsemozhetbyt** [comment]
There should be no space between `--` and `version`.

**Comment by Asmith68** [comment]
Thanks, worked this time, I have never worked with this try of program.  Was not sure if I messed something up on install. Did not mean to put that space there, should have seen that myself.
