### ISSUE TITLE
[expressjs] what happens if request to an api bursts in short period of time?(feat. message queue)

### ISSUE THREAD

**Issue by cjsjyh** [nodejs/help#1698]
* Node.js Version: 11.0
* OS : Ubuntu 14.04 LTS
* Module (and version) (if relevant):  "express": "^4.16.4"

let's say i have an api with the name "articles" with method "post".
it inserts articles into my database. How does express handle the next request if the previous db call is still being processed?

it probably has a way to handle concurrent request but then why do we need message queue if it does some sort of queue action by itself apart from decoupling of client and server?

Thank you!

**Comment by gireeshpunathil** [comment]
if it is a question on the internal working on express, it should go to https://github.com/expressjs/express

On the other hand, if the question is around concurrency, the `db` call in question (if implemented asynchronously) does not complete fully and thereby does not block Node from progressing towards other pending tasks - in your case the next request that is waiting in the listen queue. This is the fundamental premise of asynchronous, event driven programming that Node.js pioneers.

Hope this helps!

**Comment by gireeshpunathil** [comment]
closing as answered
