### ISSUE TITLE
crash error local category_set->GetFunction(env->context()).ToLocalChecked())

### ISSUE THREAD

**Issue by ghost** [nodejs/help#1699]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

hello 
my code uses mongodb and electron but throws error

db.inventory.insertMany([
   { item: "journal", qty: 25, size: { h: 14, w: 21, uom: "cm" }, status: "A" },
   { item: "notebook", qty: 50, size: { h: 8.5, w: 11, uom: "in" }, status: "A" },
   { item: "paper", qty: 100, size: { h: 8.5, w: 11, uom: "in" }, status: "D" },
   { item: "planner", qty: 75, size: { h: 22.85, w: 30, uom: "cm" }, status: "D" },
   { item: "postcard", qty: 45, size: { h: 10, w: 15.25, uom: "cm" }, status: "A" }
]);

db.inventory.find( {
     status: "A",
     $or: [ { qty: { $lt: 30 } }, { item: /^p/ } ]
} )

```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [node]
 2: 0xac5ab4 [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: MongoDB::detectPayload(v8::Local<v8::Object>) [C:\Users\nixiyang\Desktop\node_modules\mongodb\src\build\Release\mongo.node]
Aborted
```

**Comment by addaleax** [comment]
That’s a problem with your MongoDB driver – It might make sense to report this at https://jira.mongodb.org/? When you do, *please* make sure that you’re using the latest versions of your dependencies and of Node.js, and include then in the report.

**Comment by gireeshpunathil** [comment]
wrong repo, closing
