### ISSUE TITLE
Cross-Compile NPM?

### ISSUE THREAD

**Issue by luisfpinto** [nodejs/help#17]
I've cross-compiled nodejs successfully. However, I want to cross compile some npm modules. Do you know how can I cross compile node modules?

Thank you in advance!

**Comment by bnoordhuis** [comment]
If you're targeting another architecture, you can pass `--arch <name>` to npm or node-gyp.  If you're targeting another operating system, I think you'll need to `export GYP_DEFINES="-DOS=<name>"` before running node-gyp.  You should also set the `CC.target` and `CXX.target` environment variables.

Keep in mind that not all modules are amenable to cross-compiling so YMMV.

**Comment by luisfpinto** [comment]
Where is node located once I have compiled nodejs soruce files?

**Comment by bnoordhuis** [comment]
In `deps/npm`?  It's not installed until you run `make install` but you would not normally do that when you're cross-compiling.

**Comment by luisfpinto** [comment]
Then, what have I to do? :]

**Comment by bnoordhuis** [comment]
Do what?  Please be specific and ask closed questions when possible.

**Comment by luisfpinto** [comment]
Well, I will try to be more specific. I have cross compiled Nodejs. But now, I'm trying to cross-compile a npm module. I've seen that I have npm in deps/npm but I don't know how to continue.

Thank you :D

**Comment by bnoordhuis** [comment]
Let's make sure we're talking about the same thing.  What module in "trying to cross-compile a npm module" are you referring to?

**Comment by luisfpinto** [comment]
The express module

**Comment by bnoordhuis** [comment]
You don't need to cross-compile express.  It's just JS, no compiling needed.

**Comment by luisfpinto** [comment]
Well I also want socket.io module. I think I have to compile that.

**Comment by bnoordhuis** [comment]
It has native bits but I think those are optional.  If you want to give cross-compiling a go, see my first comment on how to approach that.

**Comment by luisfpinto** [comment]
This issue can be closed. Thank you!
