### ISSUE TITLE
How to navigate to other web pages from Node.js page using hyperlink ?

### ISSUE THREAD

**Issue by PrasadBehare** [nodejs/help#170]
Using Hyperlink in HTML(DOM) in Node.js file doesn't seems to be work. I wanted to know if there is way to navigate to other web pages from Node.js page using Hyperlink. Using different Port numbers for every single page may be a solution,  but is not if no more ports are available. In essence, I want to know how do I use Node.js for multi-page web application.

**Comment by addaleax** [comment]
Node.js has nothing to do with HTML or the DOM by itself, but you can use it to send those things to a web browser.

Maybe an extended version of the [usage example for Node.js](https://nodejs.org/api/synopsis.html#synopsis_example) helps you along:

```js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/html');
  if (req.url === '/other-page') {
    res.end('<p>Hello from the other page!</p>\n');
  } else {
    res.end('<p><a href="/other-page">Click here!</a></p>\n');
  }
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

This shows how you can inspect e.g. `req.url` to see which page was requested by the browser/client.

**Comment by PrasadBehare** [comment]
Is it recommended using Express.js to sort it out ?

**Comment by addaleax** [comment]
That decision is up to you, but I don’t think there’s anything generally speaking against that.

**Comment by Fishrock123** [comment]
You'd probably want to use a Web Framework from npm, such as Express, Hapi, Koa, or Kraken. (All have their difference compromises depending on your needs.)

**Comment by PrasadBehare** [comment]
@addaleax Your code is working fine, but it is over writing contents of the 'other-page' with the string 'Hello from other page' (as it should be). Your code is not 'Redirecting' in real sense but rather creating illusion of redirection. Because even if I deleted 'other-file' from directory, it is showing like redirection has happened. Anyway thanks a lot for the code !

**Comment by PrasadBehare** [comment]
Thanks @Fishrock123 for your suggestions !

**Comment by fa7ad** [comment]
@PrasadBehare try using a static server. I fee like that's what you are looking for

First, Install this module **http-server**
```bash
[sudo] npm i -g http-server
```
Then just launch it from the directory you want to serve
```bash
cd myAwesomeHTMLProj
http-server . -p 1234
```

and then just navigate to [http://localhost:1234](http://localhost:1234)

**Comment by PrasadBehare** [comment]
Thanks @fa7ad

**Comment by Satyam-Samal** [comment]
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/html;charset=utf8');
  if (req.url === '/other-page') {
    res.end('<p>Hello from the other page!</p>\n');
  } else {
    res.end('<p><a href="/other-page">Click here!</a></p>\n');
  }
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
