### ISSUE TITLE
Difference between Node.js Addon API and NAPI

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1707]
I filed this issue here:
https://github.com/nodejs/node-addon-examples/issues/74

Does anyone know what the difference is between these two:

![xxx](https://user-images.githubusercontent.com/11139560/50720519-9f2f6180-1063-11e9-87f8-7e45bb0262a9.png)

**Comment by devsnek** [comment]
napi is a C api and node-addon-api is a C++ api

**Comment by ORESoftware** [comment]
@devsnek thanks - https://github.com/nodejs/node-addon-examples/issues/74

I think 

> napi is a C api and node-addon-api is a C++ api

belongs in the readme here:
https://github.com/nodejs/node-addon-examples/blob/master/README.md

do you think so?

**Comment by mhdawson** [comment]
I agree we should update the README.md to have more information about each of the options including a link to the node-addon-api repo.  Do you want to submit a PR?

**Comment by gireeshpunathil** [comment]
@ORESoftware - are you happy with the doc that is merged?

**Comment by gireeshpunathil** [comment]
addressed, closing
