### ISSUE TITLE
Can't find module after install

### ISSUE THREAD

**Issue by pamam** [nodejs/help#1709]
* **Node.js Version**: 10.15.0
* **OS**: windows 10 home
* **Scope (install, code, runtime, meta, other?)**: install
λ npm install --save-dev --global express<CR>
<results>
λ npm i --save-dev --global express
+ express@4.16.4
updated 1 package in 3.485s

My node app can't find the module express using 'require'

**Comment by pamam** [comment]
My node app
var express = require('express');
var app = express();
var global = 0;
app.get('/', function(req, res){
	global = global + 1;
	res.send('<h2>Beware of global scope.</h2>'+
	'Global scope variable: ' + global)
});
app.Listen(8888);

**Comment by pamam** [comment]
Sorry did not mean to close the issue

**Comment by WAINGOR** [comment]
Hi pamam, try just using 'npm install' from the directory where package.json is. Also try to look if your $PATH is set correctly

**Comment by gireeshpunathil** [comment]
@pamam - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing
