### ISSUE TITLE
Error: connect EPROTOTYPE <socket_path>

### ISSUE THREAD

**Issue by gabsn** [nodejs/help#1710]
* **node**: v11.3.0
* **OS**: Mac OS Mojave 10.14.2
* **Scope (install, code, runtime, meta, other?)**: runtime
* **ts-node**: v7.0.1
* **typescript**: v3.2.2

Got the following error:
```sh
> ts-node connect_to_uds_socket.ts
Error: connect EPROTOTYPE /var/run/dogstatsd/dsd.sock
```

Here is the code I used:
```ts
import * as net from "net";

let client = net
  .createConnection("/var/run/dogstatsd/dsd.sock")
  .on("connect", () => {
    console.log("Connected.");
  })
  // Messages are buffers. use toString
  .on("data", function(data: any) {
    data = data.toString();
    console.log(data);
  })
  .on("error", function(data: any) {
    data = data.toString();
    console.error(data);
  });
```
[Here](https://github.com/nodejs/help/issues/702) is a similar issue.

**Comment by mpowell90** [comment]
I'm also suffering from this same issue.

terminal output:
`{ Error: connect EPROTOTYPE /var/run/arcontroller-master.socket
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'EPROTOTYPE',
  errno: 'EPROTOTYPE',
  syscall: 'connect',
  address: '/var/run/arcontroller-master.socket' }
`
My node script is a socket client, the same as @gabsn - preferred to keep C program as the socket manager.
.socket file created by a C program on Linux OS.

Any suggestions greatly appreciated

**Comment by gireeshpunathil** [comment]
@gabsn - are you running this code in the server? or client? can you share the server code too?

**Comment by gireeshpunathil** [comment]
inactive, closing
