### ISSUE TITLE
equivalent function to curl --verbose?

### ISSUE THREAD

**Issue by cailin-lai** [nodejs/help#1711]
Dear Folks,
Is there equivalent function to curl --verbose? See following outputs, it will be good for trouble-shooting connection issue. Thanks!

curl --verbose -I https://github.com

Rebuilt URL to: https://github.com/
Trying 192.30.253.112...
TCP_NODELAY set
Connected to github.com (192.30.253.112) port 443 (#0)
ALPN, offering h2
ALPN, offering http/1.1
Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@strength
successfully set certificate verify locations:
CAfile: /etc/ssl/cert.pem
CApath: none
TLSv1.2 (OUT), TLS handshake, Client hello (1):
TLSv1.2 (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (IN), TLS handshake, Server key exchange (12):
TLSv1.2 (IN), TLS handshake, Server finished (14):
TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
TLSv1.2 (OUT), TLS change cipher, Client hello (1):
TLSv1.2 (OUT), TLS handshake, Finished (20):
TLSv1.2 (IN), TLS change cipher, Client hello (1):
TLSv1.2 (IN), TLS handshake, Finished (20):
SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
ALPN, server accepted to use http/1.1
Server certificate:
subject: businessCategory=Private Organization; 1.3.6.1.4.1.311.60.2.1.3=US; 1.3.6.1.4.1.311.60.2.1.2=Delaware; serialNumber=5157550; C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
start date: May 8 00:00:00 2018 GMT
expire date: Jun 3 12:00:00 2020 GMT
issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
SSL certificate verify ok.
.....
I know that TLSSocket.getPeerCertificate() works well to get certificate, but how to get the handshake process?
Thanks a lot.

**Comment by gireeshpunathil** [comment]
@cailin-lai - `curl` being a tool specific for URL fetching, it's verbose option printing the most relevant information makes sense. Node.js however is a general purpose programming platform, so verbose option needs to be applied on each methods inside, to get the desired experience.

This is what you can do: https://nodejs.org/api/cli.html#cli_node_debug_module

there is a NODE_DEBUG=<modules> and NODE_DEBUG_NATIVE=<modules> that you can apply in the command line prior to your program. All the `debug` statements inside the API and its helpers will be printed. However, I am not expecting parity with `curl`.

Hope this helps

**Comment by gireeshpunathil** [comment]
When you apply this and review your debug data, if you believe there are some useful information that is missing, please share it so that we can consider adding that, and alternatively, feel free to come up with a PR that bridges the gap!

**Comment by cailin-lai** [comment]
Thanks @gireeshpunathil ! Let me have tries.

**Comment by gireeshpunathil** [comment]
ping @cailin-lai - were you able to resolve the issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
