### ISSUE TITLE
Why are the methods of a request to an HTTP server limited to the RFC defined methods?

### ISSUE THREAD

**Issue by AlexisWilke** [nodejs/help#1712]
* **Node.js Version**: 10.15.0 (not that relevant, though)
* **OS**: Linux (definitely not relevant)
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: http, https, http2

Today I tried to send a `LIST` method to my server:

    curl -XLIST -v 'http://api.example.com/some/path'

As an answer I received:

    < HTTP/1.1 400 Bad Request
    * no chunk, no close, no size. Assume close to signal end
    < 
    * Closing connection 0

I want to use a `LIST` on a certain connection point to get the list of children:

    # Request
    LIST /foo
    # Response
    [
        "/foo/item1",
        "/foo/item2",
        ...
        "/foo/itemN",
    ]

Whereas a `GET` gives me the data of the object at that connection point.

    # Request
    GET /foo
    # Response
    {
        "color": "pink",
        "size": 123,
        ...
        "fieldN": "valueN"
    }

Only I was up for a surprise, as shown above, I got what looked like a _"crashing error"_. The server replies with a _«400 Bad Request»_ an empty line and nothing else. At least, I was expecting a _«405 Method Not Allowed»_ or maybe a _«501 Not Implemented»_ when I send the _wrong method_...

So... since the documentation did not say anything and I have the source, I looked at the source, which is documentation too, right? You **cannot** decide which methods are acceptable! They are currently 100% hard coded in the `http_parser.c` state machine (ugly, if you ask me. I understand the concept of speed, but I would definitely not waste my time with such a complex state machine! It would probably be a lot faster to read the whole method because it's anyway going to already be in the socket buffer and then check it with a simple set of switches. But I guess that's a different discussion...)

Why can't I decide what methods I'm going to accept in my very own server?

Here is [the C code](https://github.com/nodejs/node/blob/master/deps/http_parser/http_parser.c#L721) I'm talking about above. We see that the methods are limited to the standard GET, POST, DELETE, PATCH, PUT, TRACE, CONNECT, etc. Any other method generates an error with a call to `SET_ERRNO(HPE_INVALID_METHOD);`.

      case s_start_req:
      {
        if (ch == CR || ch == LF)
          break;
        parser->flags = 0;
        parser->content_length = ULLONG_MAX;

        if (UNLIKELY(!IS_ALPHA(ch))) {
          SET_ERRNO(HPE_INVALID_METHOD);
          goto error;
        }

        parser->method = (enum http_method) 0;
        parser->index = 1;
        switch (ch) {
          case 'A': parser->method = HTTP_ACL; break;
          case 'B': parser->method = HTTP_BIND; break;
          case 'C': parser->method = HTTP_CONNECT; /* or COPY, CHECKOUT */ break;
          case 'D': parser->method = HTTP_DELETE; break;
          case 'G': parser->method = HTTP_GET; break;
          case 'H': parser->method = HTTP_HEAD; break;
          case 'L': parser->method = HTTP_LOCK; /* or LINK */ break;
          case 'M': parser->method = HTTP_MKCOL; /* or MOVE, MKACTIVITY, MERGE, M-SEARCH, MKCALENDAR */ break;
          case 'N': parser->method = HTTP_NOTIFY; break;
          case 'O': parser->method = HTTP_OPTIONS; break;
          case 'P': parser->method = HTTP_POST;
            /* or PROPFIND|PROPPATCH|PUT|PATCH|PURGE */
            break;
          case 'R': parser->method = HTTP_REPORT; /* or REBIND */ break;
          case 'S': parser->method = HTTP_SUBSCRIBE; /* or SEARCH, SOURCE */ break;
          case 'T': parser->method = HTTP_TRACE; break;
          case 'U': parser->method = HTTP_UNLOCK; /* or UNSUBSCRIBE, UNBIND, UNLINK */ break;
          default:
            SET_ERRNO(HPE_INVALID_METHOD);
            goto error;
        }
        UPDATE_STATE(s_req_method);

        CALLBACK_NOTIFY(message_begin);

        break;
      }

      case s_req_method:
      {
        const char *matcher;
        if (UNLIKELY(ch == '\0')) {
          SET_ERRNO(HPE_INVALID_METHOD);
          goto error;
        }

        matcher = method_strings[parser->method];
        if (ch == ' ' && matcher[parser->index] == '\0') {
          UPDATE_STATE(s_req_spaces_before_url);
        } else if (ch == matcher[parser->index]) {
          ; /* nada */
        } else if ((ch >= 'A' && ch <= 'Z') || ch == '-') {

          switch (parser->method << 16 | parser->index << 8 | ch) {
    #define XX(meth, pos, ch, new_meth) \
            case (HTTP_##meth << 16 | pos << 8 | ch): \
              parser->method = HTTP_##new_meth; break;

            XX(POST,      1, 'U', PUT)
            XX(POST,      1, 'A', PATCH)
            XX(POST,      1, 'R', PROPFIND)
            XX(PUT,       2, 'R', PURGE)
            XX(CONNECT,   1, 'H', CHECKOUT)
            XX(CONNECT,   2, 'P', COPY)
            XX(MKCOL,     1, 'O', MOVE)
            XX(MKCOL,     1, 'E', MERGE)
            XX(MKCOL,     1, '-', MSEARCH)
            XX(MKCOL,     2, 'A', MKACTIVITY)
            XX(MKCOL,     3, 'A', MKCALENDAR)
            XX(SUBSCRIBE, 1, 'E', SEARCH)
            XX(SUBSCRIBE, 1, 'O', SOURCE)
            XX(REPORT,    2, 'B', REBIND)
            XX(PROPFIND,  4, 'P', PROPPATCH)
            XX(LOCK,      1, 'I', LINK)
            XX(UNLOCK,    2, 'S', UNSUBSCRIBE)
            XX(UNLOCK,    2, 'B', UNBIND)
            XX(UNLOCK,    3, 'I', UNLINK)
    #undef XX
            default:
              SET_ERRNO(HPE_INVALID_METHOD);
              goto error;
          }
        } else {
          SET_ERRNO(HPE_INVALID_METHOD);
          goto error;
        }

        ++parser->index;
        break;
      }

Note, the llhttp.c does the same thing. It has the methods hard coded. It's just even harder to see how that stuff works. It's a very complex lexer written by hand...

**Comment by Hakerh400** [comment]
It is possible to support custom TCP request types using net server:

```js
const netPort = 80;
const httpPort = 12345;
const crlf = (n=1) => '\r\n'.repeat(n);

const netServer = net.createServer(netOnReq);
netServer.listen(netPort);

const httpServer = http.createServer(httpOnReq);
httpServer.listen(httpPort);

function netOnReq(con){
  const bufs = [];
  let len = 0;

  con.on('data', onData);

  function onData(data){
    bufs.push(data);
    len += data.length;

    if(len >= 5){
      const buf = Buffer.concat(bufs);
      con.removeListener('data', onData);

      if(String(buf).startsWith('LIST ')){
        const data = ['item1', 'item2', 'item3'];
        con.end(crlf() + JSON.stringify(data, null, 2) + crlf(2));
      }else{
        const proxy = net.createConnection(httpPort, () => {
          proxy.write(buf);
          con.pipe(proxy).pipe(con);
        });
      }
    }
  }
}

function httpOnReq(req, res){
  res.end('<h1>Hello</h1>' + crlf(2));
}
```

**Output**

```console
$ curl -X LIST localhost
[
  "item1",
  "item2",
  "item3"
]

$ curl -X GET localhost
<h1>Hello</h1>
```

**Comment by AlexisWilke** [comment]
Hi @Hakerh400 -- only if you want to support HTTP, HTTPS, and HTTP2, it's a bit more work! All of that because someone decided that only basic HTTP/RESTful/WebDav methods should be allowed... Rather strange to me.

**Comment by gireeshpunathil** [comment]
@AlexisWilke - I don't think any one decided to do so (I don't see any documentation to that effect). Please feel free to come up with PRs if you see missing capabilities / functions / protocols that are useful for general web applications.

**Comment by gireeshpunathil** [comment]
inactive, closing
