### ISSUE TITLE
java script test : not able to identify function

### ISSUE THREAD

**Issue by arindam-b** [nodejs/help#1714]
Hello there,

I am trying to create a simple Hash using SHA256. While testing it, I am getting following error:

TypeError: cryptoHash is not a function

> at Object.<anonymous> (<filename>)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:612:3
> 

**Here is my code:

crypto-hash.js**

`const crypto = require("crypto");

const cryptoHash = (...inputs) => {
  const hash = crypto.createHash("sha256");
  hash.update(inputs.sort().join(" "));
  return hash.digest("hex");
};

module.export = cryptoHash;
`

**Testcase:**

crypto-hash.test.js

`const cryptoHash = require("./crypto-hash");

describe("cryptoHash()", () => {
  it("produces same hash with same input in any order", () => {
    expect(cryptoHash("one", "two", "three")).toEqual(
      cryptoHash("three", "one", "two")
    );
  });
});
`

My versions of node and npm:

**npm -v
6.5.0

node -v
v8.11.3**

Regards,
Arindam

**Comment by vsemozhetbyt** [comment]
You need `module.exports`, not `module.export`.

**Comment by arindam-b** [comment]
Its resolved.

I changed it to:

crypto-hash.js

`const crypto = require("crypto");

exports.cryptoHashGen = (...inputs) => {
  const hash = crypto.createHash("sha256");
  hash.update(inputs.sort().join(" "));
  return hash.digest("hex");
};
`

and 

crypto-hash.test.js

`const cryptoHash = require("./crypto-hash");

describe("cryptoHash()", () => {
  it("produces same hash with same input in any order", () => {
    expect(cryptoHash.cryptoHashGen("one", "two", "three")).toEqual(
      cryptoHash.cryptoHashGen("three", "one", "two")
    );
  });
});
`
