### ISSUE TITLE
What i do in terminal

### ISSUE THREAD

**Issue by LachieDaGamer** [nodejs/help#1715]
What happens when I use terminal:
Say in doing node .
It doesn’t do anything. It comes up with something saying “what application do you want to use” and then I click Visual Studio Code, then it opens up a tab called node

**Comment by ORESoftware** [comment]
your node executable is pointing to the wrong program. Are you on windows?

what does this command:

`$ which node`

output?

**Comment by LachieDaGamer** [comment]
`your node executable is pointing to the wrong program. Are you on windows?
what does this command:
$ which node
output?`
@ORESoftware 
umm. idk what you mean. Yes I am on windows. If you mean $ which node. it doesn't output anything. if you want to know what node I have I have the Recommended one from nodejs.org

**Comment by LachieDaGamer** [comment]
Nvm I’ve fixed it.

**Comment by gireeshpunathil** [comment]
closing then!
