### ISSUE TITLE
How many timer callbacks (macrotasks) are run in one iteration of event loop

### ISSUE THREAD

**Issue by Vyshakh18** [nodejs/help#1716]
* **Node.js Version**: Any
* **OS**: Any
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**:

Hi,
This is to understand about the 'timers' phase in the nodejs event loop. As per nodejs [documentation](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/), and also the libuv design [doc](http://docs.libuv.org/en/v1.x/design.html), all the timers whose timeout is less than the loop's concept of 'now', will be picked up for execution. And this can be seen from the loop [here ](https://github.com/libuv/libuv/blob/c5593b51dc98715f7f32a919301b5801ebf1a8ce/src/timer.c#L163)
But at many other places, i have across the statement that, only 'one' macro task will be picked up in one iteration of the event loop - that would mean that, even if, lets say, 10 timers have expired, only one from the front of the queue is picked up, in that iteration of the loop. Some links, that speak this way:
SOF answer [here](https://stackoverflow.com/questions/25915634/difference-between-microtask-and-macrotask-within-an-event-loop-context)
YT [video ](https://www.youtube.com/watch?v=cCOL7MC4Pl0) at 27:35

Can someone shed some light on this?

**Comment by Vyshakh18** [comment]
Hi, 
Can someone help answer this?

**Comment by gireeshpunathil** [comment]
@Vyshakh18 - the code link which you quoted is the most authentic, so that is the right one.

**Comment by gireeshpunathil** [comment]
answered, closing
