### ISSUE TITLE
426 Upgrade Required

### ISSUE THREAD

**Issue by mallikarjunbangargi** [nodejs/help#172]
sir i am going to build a webrtc video conference application using nodejs .. 

server.js is working but When i am trying to run the localhost:9090..i am getting the below error 

Upgrade Required on web page
and in  console
Failed to load resource: the server responded with a status of 426 (Upgrade Required) -- favicon.ico
Failed to load resource: the server responded with a status of 426 (Upgrade Required)-- localhost:9090

please tel me whats is wrong....

code:server.js

//require our websocket library 
var WebSocketServer = require('ws').Server; 

//creating a websocket server at port 9090 
var wss = new WebSocketServer({port: 9090}); 

//all connected to the server users 
var users = {};
  
//when a user connects to our sever 
wss.on('connection', function(connection) {
  
   console.log("User connected");
	
   //when server gets a message from a connected user 
   connection.on('message', function(message) { 
	
      var data; 
		
      //accepting only JSON messages 
      try { 
         data = JSON.parse(message); 
      } catch (e) { 
         console.log("Invalid JSON"); 
         data = {}; 
      }
		
      //switching type of the user message 
      switch (data.type) { 
         //when a user tries to login
         case "login": 
            console.log("User logged", data.name); 
				
            //if anyone is logged in with this username then refuse 
            if(users[data.name]) { 
               sendTo(connection, { 
                  type: "login", 
                  success: false 
               }); 
            } else { 
               //save user connection on the server 
               users[data.name] = connection; 
               connection.name = data.name; 
					
               sendTo(connection, { 
                  type: "login", 
                  success: true 
               }); 
            } 
				
            break;
				
         case "offer": 
            //for ex. UserA wants to call UserB 
            console.log("Sending offer to: ", data.name);
				
            //if UserB exists then send him offer details 
            var conn = users[data.name]; 
				
            if(conn != null) { 
               //setting that UserA connected with UserB 
               connection.otherName = data.name; 
					
               sendTo(conn, { 
                  type: "offer", 
                  offer: data.offer, 
                  name: connection.name 
               }); 
            }
				
            break;
				
         case "answer": 
            console.log("Sending answer to: ", data.name); 
            //for ex. UserB answers UserA 
            var conn = users[data.name]; 
				
            if(conn != null) { 
               connection.otherName = data.name; 
               sendTo(conn, { 
                  type: "answer", 
                  answer: data.answer 
               }); 
            } 
				
            break; 
				
         case "candidate": 
            console.log("Sending candidate to:",data.name); 
            var conn = users[data.name];
				
            if(conn != null) { 
               sendTo(conn, { 
                  type: "candidate", 
                  candidate: data.candidate 
               }); 
            } 
				
            break;
				
         case "leave": 
            console.log("Disconnecting from", data.name); 
            var conn = users[data.name]; 
            conn.otherName = null; 
				
            //notify the other user so he can disconnect his peer connection 
            if(conn != null) {
               sendTo(conn, { 
                  type: "leave" 
              }); 
            }
				
            break;
				
         default: 
            sendTo(connection, { 
               type: "error", 
               message: "Command not found: " + data.type 
            }); 
				
            break; 
      }
		
   }); 
	
   //when user exits, for example closes a browser window 
   //this may help if we are still in "offer","answer" or "candidate" state 
   connection.on("close", function() { 
	
      if(connection.name) { 
         delete users[connection.name]; 
			
         if(connection.otherName) { 
            console.log("Disconnecting from ", connection.otherName); 
            var conn = users[connection.otherName]; 
            conn.otherName = null;
				
            if(conn != null) { 
               sendTo(conn, { 
                  type: "leave" 
               }); 
            }
         } 
      }
		
   });  
	
   connection.send("Hello world");  
});
  
function sendTo(connection, message) { 
   connection.send(JSON.stringify(message)); 
}

**Comment by lordKnighton** [comment]
https://httpstatuses.com/426  
![screen shot 2016-05-24 at 9 13 21 pm](https://cloud.githubusercontent.com/assets/1773260/15527980/6f9645de-21f4-11e6-83e4-e39cc8764eb5.png)

--

OTHER LINKS: http://stackoverflow.com/questions/35515398/how-to-solve-spacebrew-error-the-server-responded-with-a-status-of-426-upgrade

http://stackoverflow.com/questions/17873247/is-http-status-code-426-upgrade-required-only-meant-signal-an-upgrade-to-a-secur

**Comment by RadwanNada** [comment]
@mallikarjunbangargi I am facing the same error did you solve it.

if you did please let me know how 

I am following the same tutorial

Regards

**Comment by mallikarjunbangargi** [comment]
nope..

**Comment by She2016** [comment]
Hi guys, @mallikarjunbangargi @RadwanNada 
I have the same probelm, did you find any solution ?
