### ISSUE TITLE
getting 2330 while trying to reinstall node.js 

### ISSUE THREAD

**Issue by dhirajkumarsinha** [nodejs/help#1722]
![image](https://user-images.githubusercontent.com/12100267/51207905-fb468100-18c0-11e9-9a5f-289eaf4e5daf.png)

* **Node.js 10**:
* **Windows 10**:
* **Scope (install)**:

**Comment by HrithikMittal** [comment]
try with this
`npm cache clear`

or try with this
`npm cache clear --force`

**Comment by alipiry** [comment]
I strongly recommend you to use `yarn`.
So you will never get such these errors at all!

**Comment by gireeshpunathil** [comment]
@dhirajkumarsinha - is your problem resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing
