### ISSUE TITLE
Better error messages for attempted fs.writefile from browser

### ISSUE THREAD

**Issue by FrancisVila** [nodejs/help#1725]
I have spent hours and hours trying to write to a file on the server side using React + modules such as fs, fs-extra, etc. Some of the steps in that attempt (not all) are logged in this StackOverflow query: https://stackoverflow.com/questions/54201101/react-write-file-nothing-works-fs-file-system. I'm not the only one to be confused. 
The error messages displayed don't **at all** suggest that what you are trying to do just can't be done. They make you think somehow the module is badly installed, or that the syntax is wrong. Errors such as **TypeError: fs.writeFile is not a function**. 

While searching I did read about API calls and such, but when you're trying unsuccessfully to get something seemingly simple to work, you don't want to plunge into something looking more complex. Here's a message that would have saved me a lot of time:

_You are attempting to write to a file on the server directly from a web application. This is not possible, for security reasons. To achieve this, you must send an API request to a web server; you can use the Axios module for that purpose, for example. If necessary you can create a web server with a module such as Express._

**Comment by Hakerh400** [comment]
I'll try to resolve your confusion.

**Server** - Application that runs in the background on a single machine. Usually developed in JavaScript and ran using Node.js engine. Server is able to interact with the file system (create, read, modify files) and other operating system features (bind to a port, start an executable file, terminate a process, etc).

**Browser** - Engine that executes client-side scripts. This is done on all machines that connect to the server. Browser is unable to interact with the file system and has very limited access to operating system features. Browser cannot read and write arbitrary files. It is impossible to implement `fs` module in a browser.

> Better error messages for attempted fs.writefile from browser

There is no `require` function in a browser, so if you try to execute `require('fs')` it will fail with `ReferenceError: require is not defined`, unless you are using a framework that provides global `require` function. In any case, there is no `fs` module in a browser (with all functionalities that Node.js provides) and it cannot be implemented even theoretically.

The command from the answer from your link is wrong (at least on windows), since batch system treats `"`s differently than Unix systems. The correct command is `node -pe "require('fs').writeFile"` and it should output `[Function: writeFile]`

> While searching I did read about API calls and such, but when you're trying unsuccessfully to get something seemingly simple to work, you don't want to plunge into something looking more complex.

The simplest thing you can do is to make sure your Node.js installation is valid and that you can properly read/write files. Create a script named `server.js` and write the following content:

```js
const fs = require('fs');
fs.writeFile('test.txt', 'Test', err => {
  if(err) throw err;
  console.log('OK');
});
```

Then navigate to the directory and run `node server.js` from the command prompt. It should print `OK` and create file named `test.txt` (or `test` if extensions are hidden) with content `Test`

After you make sure this code works, you can start researching APIs for client-server communication. One solution is to send `fs` requests from browser over HTTP protocol to the Node.js server and perform `fs` operations from there.

Hope this helps.

**Comment by FrancisVila** [comment]
Hi @Hakerh400 ,
Thank you so much for your patient explanations. 
I tried the test you suggested and it did return OK.

I am indeed using a framework - React with applications created using create-react-app. For someone like me who knows html, javascript and css, and who always has loads of suggestions to make about app design, this has opened the door to start creating web applications instead of mock-ups. 
Maybe the error message should come from react rather than node.js.

All this to say that the framework I am using is masking a lot of the complexity related to developing web apps, that people who's job it is have been working with for years. In most cases, solving this kind of technical problem has been a matter of installing a module, copy-paste-adapting some code, in the right place. This leaves lots of interesting problems such as how to give the user the best experience, and how to architecture the components structure in the most logical and reusable way, how to best use the react life cycle, etc.
 
I understand that in this case I need to get deeper into the workings of nodejs. It would have saved time to be told so in the first place, hence the suggestion about the error message. 

Finally I don't really get the logic of prohibiting a web app from writing to a file on the server side. On the client side, sure you don't want malicious apps writing on the user's disk. But on the server side, it's the programmer controlling what's happening on his/her own environment. And what's the difference between a) writing directly to the server disk from the web app, and b) putting up a separate server app with a separate port, to do exactly the same thing via API calls?

With the advent of easy-to-use frameworks such as React and Vue, more and more people will be coming in with less knowledge of server-side basics. I can appreciate that this may be annoying to some who have spent years overcoming technical hurdles; on the other hand, it's the whole history of technology. One layer builds on top of another, we are but dwarfs on the shoulders of giants, etc.

**Comment by Hakerh400** [comment]
>  what's the difference between a) writing directly to the server disk from the web app, and b) putting up a separate server app with a separate port, to do exactly the same thing via API calls?

Web apps can't access server disk. Server is the one that writes to the disk. Web app can only ask the server to perform a disk operation.

> On the client side, sure you don't want malicious apps writing on the user's disk. But on the server side, it's the programmer controlling what's happening on his/her own environment.

[Electron](https://electronjs.org/) does exactly that.

**Comment by FrancisVila** [comment]
Web apps can't access server disk. : yes I guess that makes sense. If I understand correctly, the whole advantage of environments like react is that the apps, once built, can run locally anywhere, without any server. You can just double-click on the file on the disk and launch the browser. So expecting them to save data on the server would be like having your cake and eating it.

**Comment by FrancisVila** [comment]
On the other hand, it would make sense to point this out to unsuspecting users who expect it to work. Seeing messages in Stackoverflow, I'm not the only one who was confused by the issue.

**Comment by gireeshpunathil** [comment]
let me see if this way of explanation helps:

#cat 1735.js

```js
require('fs').writeFile('test.txt', 'foo', () => {})
```

#../node_modules/.bin/browserify 1735.js > 1735.1.js

#cat 1735.1.js
```js
(function(){function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}return e})()({1:[function(require,module,exports){

},{}],2:[function(require,module,exports){
require('fs').writeFile('test.txt', 'foo', () => {})

},{"fs":1}]},{},[2]);
```

#node 1735.1

```trace
/Users/gireeshpunathil/Desktop/support/1735.1.js:4
require('fs').writeFile('test.txt', 'foo', () => {})
              ^

TypeError: require(...).writeFile is not a function
    at Object.2.fs (/Users/gireeshpunathil/Desktop/support/1735.1.js:4:15)
    at s (/Users/gireeshpunathil/Desktop/support/1735.1.js:1:265)
    at e (/Users/gireeshpunathil/Desktop/support/1735.1.js:1:436)
    at Object.<anonymous> (/Users/gireeshpunathil/Desktop/support/1735.1.js:1:465)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
#
```

if your application is `browserified` (or  subjected to processing that transforms the backend code to the most meaningful front end code which can be run in the browser) then the `fs` object is emulated through a different module that does not have the disk accessor APIs.

Hope this helps?

**Comment by FrancisVila** [comment]
Is the last phrase an error message?
If so, personally I wouldn't know whether or not my application was browserified...
I'd say something like:
`If your application is generated by a web platform such as react, vue or angular, then you cannot use fs to perform write operations on a file. In this case, you must send an API request to a web server; you can use the Axios module for that purpose, for example. If necessary you can create a web server with a module such as Express  `

**Comment by gireeshpunathil** [comment]
sorry, the last phrase is my interpretation of what could have happened, not an error message.

> If so, personally I wouldn't know whether or not my application was browserified...
It may not be done the way I hand-crafted the code, but given react, vue and angular all being front-end frameworks, those may be `browserifying` code implicitly ( this is my guess, not proven)

now, coming to the actual writing itself:
`fs.write` in the backend is a trivial and essential task.
`fs.write` in the front-end is not a secure operation, so it is inhibited.

`fs.write` in the server but initiated by the client side program conditions: sending an API request to the server is the most common way to do that - which looking from the server side, falls into the first category for most part.

In general, I agree with your statement.

**Comment by FrancisVila** [comment]
OK for me!

**Comment by gireeshpunathil** [comment]
closing then, cheers!
