### ISSUE TITLE
nodejs proper use

### ISSUE THREAD

**Issue by flexxall** [nodejs/help#1728]
* **Node.js Version**: 11.7.0
* **OS**: Ubuntu 18
* **Scope (install, code, runtime, meta, other?)**:code conversion
* **Module (and version) (if relevant)**:

I am attempting to learn and setup nodebb. I have started developing on SMF and php. I am wanting to know how would i convert this code to nodejs or what would I use in nodejs to achieve this.

`$imagesDir = 'images/eggs/';

    $eggs = array();
		foreach (glob("images/eggs/*.{jpg,png,gif}", GLOB_BRACE) as $filename) {
    		$eggs[] = $filename;
	}
		echo "<script>var eggs =" . json_encode($eggs) . "</script>";

	echo'
    <div id="baloon1">
    	';
    	$images = array();
    	$images = glob($imagesDir . '*.{jpg,png,gif}', GLOB_BRACE);
    	$randomImage = $images[array_rand($images)];
    	echo'
        <img src="' . $randomImage . '">        	        
    </div>`

**Comment by Hakerh400** [comment]
Here you go:

```js
'use strict';

const fs = require('fs');
const path = require('path');
const http = require('http');
const urlm = require('url');
const fsp = fs.promises;

const imagesDir = path.normalize('images/eggs/');
const exts = ['png', 'jpg', 'gif'];
const port = 80;

const cwd = __dirname;
const fullPath = path.join(cwd, imagesDir);
const server = http.createServer(onReq).listen(port);

const jsonEncode = data => JSON.stringify(data).replace(/\//g, '\\/');
const randElem = arr => arr[Math.random() * arr.length | 0];
const getExt = file => path.parse(file).ext.slice(1);

function onReq(req, res){
  (async () => {
    const p = path.normalize(urlm.parse(req.url).path.slice(1));

    if(p === '.'){
      const files = await fsp.readdir(fullPath);
      const images = files
        .filter(file => exts.includes(getExt(file)))
        .map(file => path
          .join(imagesDir, path.parse(file).base)
          .replace(/\\/g, '/')
        );
      res.setHeader('content-type', 'text/html');
      res.end(`
        <script>
          var eggs = ${jsonEncode(images)};
        </script>
        <div id="baloon1">
          <img src="${randElem(images)}">
        </div>
      `);
      return;
    }

    if(p.startsWith(imagesDir)){
      const img = path.relative(imagesDir, p);
      if(/^\.{1,2}$|[\/\\]/.test(img)) return e404();
      const ext = getExt(img);
      if(!exts.includes(ext)) return e404();
      const mime = ext === 'jpg' ? 'jpeg' : ext;
      res.setHeader('content-type', `image/${ext}`);
      fs.createReadStream(p).pipe(res);
      return;
    }

    e404();
  })().catch(err => {
    console.log(err);
    res.statusCode = 500;
    res.end(err.toString());
  });

  function e404(){
    res.statusCode = 404;
    res.end();
  }
}
```

**Comment by Hakerh400** [comment]
Have you modified the script? From the stack trace I see you used `fs.readdir` instead of `fsp.readdir`

**Comment by flexxall** [comment]
HAHA good catch. I had adjusted a couple things and missed resetting that one. Thank you. Next step is to figure out how to set this to change on a onclick  method and make it unavailable for another user until it refreshes with a new random image... Weee

**Comment by gireeshpunathil** [comment]
ping @flexxall - anything pending here?

**Comment by gireeshpunathil** [comment]
inactive, closing
