### ISSUE TITLE
problem with code that i do not now how to fix 

### ISSUE THREAD

**Issue by willhnew2503** [nodejs/help#1729]
Hello i have a issue with trying to run my code whenever i type in node . it says that i get a Unhandled 'error' event 
![image](https://user-images.githubusercontent.com/46866460/51488447-7dd9af80-1d9d-11e9-8fc8-7e1a5e06a838.png)

**Comment by addaleax** [comment]
I’m just guessing that `bot.on('error', (err) => console.log(err))` might be a bit more helpful here? Not sure, though…

**Comment by gireeshpunathil** [comment]
ping @willhnew2503 - is this still pending?

**Comment by gireeshpunathil** [comment]
inactive, closing
