### ISSUE TITLE
Question about sockets & http.request 

### ISSUE THREAD

**Issue by Avcajaraville** [nodejs/help#173]
Im writing some integration tests for a node project.

We need to get reliable metrics about server performance. For that, we want to open a socket between the server and the client before any test is performance, this way, we can eliminate the time needed to create a socket between client and server.

I have created a small test case like this:
````js
'use strict';

var express = require( 'express' ),
    net     = require('net'),
    http    = require('http');

var host    = 'localhost',
    port    = 8000;

describe( 'dummy describe', function() {
  var app, server, agent, opts;
  before( function( done ) {
    app = express();
    app.get( '/', function( req, res, next ) {
      res.send( 'stuff' );
    });
    server = http.createServer( app );
    server.listen( 8000 );
    agent = new http.Agent({ maxSockets: 1 });
    agent.createConnection({ port: port, host: host }, function() {
      return net.createConnection({ port: port, host: host }, function() {
        console.log( 'Socket fd open on before block: ' + this._handle.fd );
        done();
      });
    });
    opts = {
      hostname: host,
      port: port,
      path: '/',
      agent: agent,
      method: 'GET',
    };
  });
  it( 'dummy test', function ( done ) {
    var req = http.request( opts, function( res ) {
      console.log( 'Socket fd used on GET: ' + res.socket._handle.fd );
      done();
    });
    req.end();
  });
}); 
````
Here, I can see the execution of the before block, where I console.log the socket file descriptor.

Reading node documentation, I figured out that his was the right way to pass a socket to a agent. But its not working, its output different sockets.

I tried a thousands combinations, but got no luck.

I want to manually connect to a socket, and then use it to perform http.request without having to re open a different socket.

What would be the correct way of doing this ?

**Comment by lordKnighton** [comment]
To my knowledge, if you're gonna be using things like describe: Be sure to import a test library. And it seems like your doing way to much in one module. I think you should go back and read the docs.

**Comment by SomeoneWeird** [comment]
@lordKnighton if you're using `mocha` (or a number of other test frameworks) it injects those globals at runtime.

@Avcajaraville What version of node are you using?

**Comment by Avcajaraville** [comment]
@SomeoneWeird  4.4.3

Thanks for the help, Im really struggling with this issue :)

**Comment by Avcajaraville** [comment]
@lordKnighton 

What Im trying to do is the following:
- Start the server
- Establish connection to that server through a socket
- With the already open socket, test server response (thats the only module being tested here)

The problem I have:
- I am able to establish a socket connection, and to mimic a http get request via socket.write.
- But I want to use a callback for that response that receives a response object as they are provided to the http.request or http.get function

Why I want to do this?:
Because we are going to test different end points on a server and we want to test their latency. For do that, we want to eliminate external factors, such as socket connection latency. Probably we will need to do something with DNS as well. 

What I have so far:
You can pass an Agent object to http.request as an option. But even when an agent created, and also after call agent.createConnection, I can see that there is no way that that socket is used by http.request or http.get

Any direction or help will be very appreciated.

**Comment by lordKnighton** [comment]
what packages did you `npm install`?

**Comment by lordKnighton** [comment]
I reiterate, **READ the Docs**, I'm not to mocha savvy, but I have seen it done a few times, and I haven't come across a bogged down: describe function.

**Comment by Avcajaraville** [comment]
@lordKnighton That would be awesome. Again, re read the docs. and have no way of figuring out. Maybe Im too dumb, or my English is not very good, but I still couldn't figure out 😂

**Comment by lordKnighton** [comment]
don't be hard on yourself. Don't worry we will figure it out later today. 💯  😄

**Comment by lordKnighton** [comment]
I didn't get far as well, but I've used my limited knowledge of how test work and set it up like this: 

**[note]** I honestly just started learning to test with mocha, lol so excuse my poor code. 

![screen shot 2016-05-23 at 3 22 24 pm](https://cloud.githubusercontent.com/assets/1773260/15486432/889e6a0c-20fa-11e6-88f1-e7d7f745e1ed.png)

![screen shot 2016-05-23 at 3 22 39 pm](https://cloud.githubusercontent.com/assets/1773260/15486433/8e670890-20fa-11e6-850e-17d836d28634.png)

**Comment by Avcajaraville** [comment]
Hey @lordKnighton thank you so much for your help !

So, no, I am the only developer here, or the higher ranked (lets say).

The goal is to start the app, and then create a client that connect to that app through an already created socket (this mean, on the response callback, the file descriptor of that connection should be the same).

This way we reduce the time to set up a connection and we can test the response time without external interferences. 

Does this info helps ? Or how can I provide you with more accurate one ?

Thanks again for your help !

**Comment by Trott** [comment]
Sorry this thread kind of died down. You might have better luck in a Mocha forum. You can also try to ask this question in the [#Node.js IRC channel](https://webchat.freenode.net/?channels=node.js&uio=d4) or on [StackOverflow](https://stackoverflow.com/).
