### ISSUE TITLE
Cross compile nodejs module (Epoll)

### ISSUE THREAD

**Issue by xSimonM** [nodejs/help#1731]
* **Version**: 10.15.0
* **Platform**: amd64/armv7
* **Subsystem**: Linux

Hi, I am trying to cross compile a node module (epoll) to run on a armv7 architecture using node-gyp. But I cannot seem to get it working. I got it pointing to the correct compiler, but node-gyp gives it the flag "-m64" which is not supported. Can anyone help me in the right direction? :)

I have set thees environment variables:
`export CC=/usr/bin/armcompiler-gcc`
`export CXX=/usr/bin/armcompiler-g++`
`export LINK=/usr/bin/armcompiler-g++`
`export AR=/usr/bin/armcompiler-ar`
`export GYP_CROSSCOMPILE=1`

**Comment by gireeshpunathil** [comment]
After the `node-gyp configure` phase the makefiles are created in the `build` folder. So you may open it, remove the unsupported flag and do a `make` in that location.

Of course, you may raise an issue with `node-gyp` project to address this at its root.

hope this helps

**Comment by gireeshpunathil** [comment]
answered, closing
