### ISSUE TITLE
npm ERR! Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by anas142** [nodejs/help#1732]
Hi , 
when I install npm via npm install 
This error appears
 
D:\htdocs\lcsyslaravel>npm install

> npm ERR! Cannot read property 'startsWith' of null

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2019-01-22T07_23_27_443Z-debug.log

**Comment by gireeshpunathil** [comment]
ping @anas142

**Comment by gireeshpunathil** [comment]
inactive, closing
