### ISSUE TITLE
Accurate EOL date for Node.js v6?

### ISSUE THREAD

**Issue by thathollywood** [nodejs/help#1734]
* **v6**:
* **Specific EOL date**:

```js
Question regarding Node.js v6 EOL date. It is not specific. Just says April 2019. 
Does that mean 1 April 2019 or 30 April 2019?
```

**Comment by gireeshpunathil** [comment]
According to this page, it is 30th April 2019, that is today:

https://nodejs.org/en/about/releases/

![image](https://user-images.githubusercontent.com/6447530/56958504-18e5e080-6b68-11e9-8352-d85527d0680b.png)

Hope this helps!

**Comment by gireeshpunathil** [comment]
closing as answered
