### ISSUE TITLE
The file's SHA1 value does not match in windows and MAC OSX

### ISSUE THREAD

**Issue by zwlijun** [nodejs/help#1737]
The file's SHA1 value does not match in Windows and MAC OSX

the code is:

```js
var sum = crypto.createHash(algorithm);
var opts = /\.(jpg|png|jpeg)$/i.test(filename) ? null : {
    "encoding": CheckSum.getCharset()
};
var stream = fs.readFileSync(filename, opts);
var digest = null;

sum.update(stream);
digest = sum.digest("hex");`
```

**Comment by addaleax** [comment]
Can you check the `encoding` values? Are they different on the different platforms?

Generally, if you want a hash of a file, you do *not* want to specify any encoding at all. Hashes are defined for sequences of bytes (= Buffers), not sequences of characters (= strings).

When you set `encoding`, what you do is you convert the file from a list of bytes to a string using one encoding, and then later (inside `.update()`) convert back from a string to a list of bytes using the default encoding (`utf8`). The result might not match the original file, if it contained non-UTF-8 data or the specified encoding was a different one.

**Comment by zwlijun** [comment]
> Can you check the `encoding` values? Are they different on the different platforms?
> 
> Generally, if you want a hash of a file, you do _not_ want to specify any encoding at all. Hashes are defined for sequences of bytes (= Buffers), not sequences of characters (= strings).
> 
> When you set `encoding`, what you do is you convert the file from a list of bytes to a string using one encoding, and then later (inside `.update()`) convert back from a string to a list of bytes using the default encoding (`utf8`). The result might not match the original file, if it contained non-UTF-8 data or the specified encoding was a different one.

I try use ReadSteam and set encoding is null. On the different platform  the result still not same.
the test code is: 
`const crypto = require('crypto');
const fs = require('fs');
const hash = crypto.createHash('sha1');

const filename = "static/v1.0/src/js/logic/m/sign/login.js";
const input = fs.createReadStream(filename);
input.setEncoding(null);


input.on('data', function(d) {
  hash.update(d);
});

input.on('end', function() {
  var d = hash.digest('hex');
  console.log("a: " + d);
});


const hash2 = crypto.createHash('sha1');
const input2 = fs.readFileSync(filename, {
	"encoding": null
});

var digest = null;

hash2.update(input2);
digest = hash2.digest("hex");

console.log("b: " + digest);


// D:\tmp>node hash.js
// b: d4a8cda8d1d2486dcb76ed5d99653d3f6b86914f
// a: d4a8cda8d1d2486dcb76ed5d99653d3f6b86914f

// Lijuns-MacBook-Air:tmp lijun$ node hash.js
// b: abed8a1107927c3a0875ba9d35c82b099a8327fd
// a: abed8a1107927c3a0875ba9d35c82b099a8327fd
`

**Comment by zwlijun** [comment]
resolved
