### ISSUE TITLE
Why the same file's line endings on different platform what it print the buffer value in console is not same.

### ISSUE THREAD

**Issue by zwlijun** [nodejs/help#1738]
* **Node.js Version**: v8.11.3(Windows)   v8.12.0(MAC OSX)
* **OS**: Windows / MAC OSX
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: fs

#1737 
Why the same file's line endings on different platform what it print the buffer value in console is not same.
-------->
in windows is 0D 0A
in mac is 0A

```js
const crypto = require('crypto');
const fs = require('fs');
const hash = crypto.createHash('sha1');

const filename = "static/v1.0/src/js/logic/m/sign/login.js";
const input = fs.createReadStream(filename);
input.setEncoding(null);


input.on('data', function(trunk) {
  console.log(new Buffer(trunk))
  hash.update(trunk);
});

input.on('end', function() {
  var d = hash.digest('hex');
  console.log("a: " + d);
});


const hash2 = crypto.createHash('sha1');
const input2 = fs.readFileSync(filename, {
	"encoding": null
});

var digest = null;

hash2.update(input2);
digest = hash2.digest("hex");

console.log("b: " + digest);


// D:\tmp>node hash.js
// b: d4a8cda8d1d2486dcb76ed5d99653d3f6b86914f
// a: d4a8cda8d1d2486dcb76ed5d99653d3f6b86914f

// Lijuns-MacBook-Air:tmp lijun$ node hash.js
// b: abed8a1107927c3a0875ba9d35c82b099a8327fd
// a: abed8a1107927c3a0875ba9d35c82b099a8327fd

// Mac OSX:
// <Buffer 3b 64 65 66 69 6e 65 28 66 75 6e 63 74 69 6f 6e 28 72 65 71 75 69 72 65 2c 20 65 78 70 6f 72 74 73 2c 20 6d 6f 64 75 6c 65 29 7b **0a** 20 20 20 20 76 61 ... >
// Windows
// <Buffer 3b 64 65 66 69 6e 65 28 66 75 6e 63 74 69 6f 6e 28 72 65 71 75 69 72 65 2c 20 65 78 70 6f 72 74 73 2c 20 6d 6f 64 75 6c 65 29 7b **0d 0a** 20 20 20 20 76 ... >
```

**Comment by Hakerh400** [comment]
The files you're comparing are not the same and therefore give different hash values. You should not rely on hashes of text files for several reasons:

 - Line endings are different: `\r\n` on Windows, `\n` on Linux and `\r` on Mac
 - Different text editors may replace tabs with spaces and vice versa
 - Some text editors leave a new line at the end of file, but don't display it
 - Some editors use various encodings, such as UTF-8, UTF-16, 16bit unicode (little or big endian), etc
 - Unicode files may contain invisible byte order mark (BOM) at the beginning

Despite all of these differencies, text files (including .js files) are displayed and interpreted in the same way. But file's low-level byte representation on disk is different and results in different hash values.

That is something related to your text editor, not the Node.js itself. If you literally copy-paste the file from Windows to Mac you will get the same SHA1.

Although it's unclear why you want to hash text files, but one solution would be to read the file as UTF8 string, then replace each new line with `\n` and convert to byte array.

**Comment by zwlijun** [comment]
@Hakerh400 Thanks~

**Comment by zwlijun** [comment]
I solved my problem using the code below.
-----------
```js
if(!/\.(jpg|png|jpeg)$/i.test(filename)){
    const startTime = Date.now();
    console.log("transform line endings before: ", stream.length);
    const copyBuffer = new Int32Array(stream, 0, stream.length);
    const newBuffer = new Buffer(copyBuffer.filter((element, index, typedArray) => {
        if(0x0d === element){
            if(0x0a === typedArray[index + 1]){ //Windows -> Unix
                return false;
            }else{
                typedArray[index] = 0x0a; //Mac OS -> Unix
            }
        }
        return true;
    }));
    console.log("transform line endings after: ", newBuffer.length);
    const costTime = Date.now() - startTime;
    console.log("transform line endings cost: " + costTime + "ms.");
    hash.update(newBuffer);
}else{
    hash.update(stream);
}    
```

**Comment by Domi83s** [comment]
> Replacing line endings fixes the issue for me
> 
> ```
> function fileHash(filePath, algorithm = 'sha256') {
>   const fileData = fs.readFileSync(filePath, 'utf8').toString();
>   const normalizedFileData = fileData.replace(/\r\n/g, '\n');
>   return createHash(algorithm).update(normalizedFileData, 'utf8').digest('hex');
> }
> ```

**Comment by Domi83s** [comment]
function fileHash(filePath, algorithm = 'sha256') {
  const fileData = fs.readFileSync(filePath, 'utf8').toString();
  const normalizedFileData = fileData.replace(/\r\n/g, '\n');
  return createHash(algorithm).update(normalizedFileData, 'utf8').digest('hex');
}

**Comment by Domi83s** [comment]
function fileHash(filePath, algorithm = 'sha256') {
  const fileData = fs.readFileSync(filePath, 'utf8').toString();
  const normalizedFileData = fileData.replace(/\r\n/g, '\n');
  return createHash(algorithm).update(normalizedFileData, 'utf8').digest('hex');
}
