### ISSUE TITLE
event loop tick id

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1740]
On Node.js version 10

Is there a way to access the event loop tick id? The use case is simple:  When writing a library you can easily detect whether the user fired a callback synchronously or asynchronously - ultimately the purpose of detecting this is to prevent Zalgo and keep APIs/libraries consistent and performant.

For example, with the async libary, a user can do this:

```js
async.parallel([
   cb => cb(),
   cb => process.nextTick(cb)
]);
```

to my knowledge, the async lib doesn't call process.nextTick on behalf of the user when the user makes this mistake (but the async lib could do that if it wanted to and there was an easily and performant way to check if the user fired the callback in the same tick).

So I am thinking of Node.js API that can allow for detecting the current event loop tick, something like this:

```js
const id = process.currentTickId();
 /// ...do some stuff then...
if(id !== process.currentTickId()){
  throw new Error('You cannot call this code asynchronously!');
}
```

the idea is to prevent someone from calling certain code asynchronously. the only way I know how to do this now is with this _hack_:

```js
let before = false;
process.nextTick(() => {
   before = true;
});
process.nextTick(() => {
 if(before === true){
   throw new Error('You cannot call this code asynchronously!');
 }
}
```

but that's not very performant or convenient. the hack simply relies on the fact that the first process.nextTick call will happen before any other async callbacks get fired.

**Comment by gireeshpunathil** [comment]
there is a `time` field in the event loop that gets updated everytime it enters the polling loop. This can be meaningfully interpreted as an `id`. Though I am not sure whether this is exposed through any JS API.

https://github.com/nodejs/node/pull/25378/ seems to be a good candidate for exposing it, if at all. @jasnell

**Comment by ChALkeR** [comment]
https://github.com/nodejs/node/pull/22584 could use similar functionality too.

@ORESoftware does `let flag = true; process.nextTick(() => { flag = false; });` work for your usecase?

**Comment by ORESoftware** [comment]
@ChALkeR  can you elaborate on that here?

**Comment by Hakerh400** [comment]
Try this:

```js
process.currentTickId = (a =>
  (b => () => a = a || [b(() => {})])
  (process.nextTick = ((b, c) => (...d) => (
    c || b(() => a = c = 0, c = 1),
    b.apply(process, d)
  ))(process.nextTick))
)();
```

**Comment by PoojaDurgad** [comment]
@ORESoftware , is this issue resolved? any updates?

**Comment by gireeshpunathil** [comment]
inactive, and / or resolved, closing. pls feel free to reopen if required
