### ISSUE TITLE
Sending SMTP message using Net module

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/help#1741]
* **Node.js Version**: v11.8.0
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: Code / Runtime
* **Module (and version) (if relevant)**: Net

I'm learning about Network Programming and I'm trying to use Net to send an SMTP message over a TCP connection. I have a working implementation with Python but I'd like to learn how Net works and how I could achieve this in JavaScript.

I have posted a stackoverflow question: https://stackoverflow.com/questions/54407086/how-to-send-smtp-message-using-node-js-net-without-nodemailer/54408547#54408547 and I'll repost relevant information here for convenience. 

--

I'm trying to do a fairly simple task: send an SMTP email using TCP sockets. I have a working implementation in Python 3.6:
```python
from socket import socket, AF_INET, SOCK_STREAM
# Choose a mail server (e.g. Google mail server) and call it mailserver
mailserver = 'gmail-smtp-in.l.google.com'

# Create socket called clientSocket and establish a TCP connection with mailserver
clientSocket = socket(AF_INET, SOCK_STREAM)

def recv():
    print(clientSocket.recv(1024).decode())

# Port number may change according to the mail server
clientSocket.connect((mailserver, 25))
recv()

# Send HELO command and print server response.
clientSocket.send('HELO gmail \r\n'.encode())
recv()

# Send MAIL FROM command and print server response.
clientSocket.send('MAIL FROM: <ethan.arrowood@gmail.com>\r\n'.encode())
recv()

# Send RCPT TO command and print server response. 
clientSocket.send('RCPT TO: <ethan.arrowood@gmail.com>\r\n'.encode())
recv()

# Send DATA command and print server response. 
clientSocket.send('DATA\r\n'.encode())
recv()

# Send message data. Make sure to include header lines: From, To, Subject
clientSocket.send('FROM: <ethan.arrowood@gmail.com>\r\n'.encode())
clientSocket.send('TO: <ethan.arrowood@gmail.com>\r\n'.encode())
clientSocket.send('SUBJECT: Testing\r\n'.encode())
clientSocket.send('This is cool!\r\n'.encode())
# Message ends with a single period.
clientSocket.send('.\r\n'.encode())
recv()
# Send QUIT command and get server response
clientSocket.send('QUIT\r\n'.encode())
recv()
```

It works and outputs the following into my console:
```bash
220 mx.google.com ESMTP m30si710943qtg.40 - gsmtp
250 mx.google.com at your service
250 2.1.0 OK m30si710943qtg.40 - gsmtp
250 2.1.5 OK m30si710943qtg.40 - gsmtp
354  Go ahead m30si710943qtg.40 - gsmtp
250 2.0.0 OK 1548694151 m30si710943qtg.40 - gsmtp
221 2.0.0 closing connection m30si710943qtg.40 - gsmtp
```
I'm now trying to implement this same thing using Node.js 11.8.0 using the Net module. My code:
```javascript
const net = require('net')

const socket = net.createConnection(25, 'gmail-smtp-in.l.google.com', () => {
  console.log('Connected!')

  socket.write('HELO gmail\r\n')

  socket.write('MAIL FROM: <ethan.arrowood@gmail.com>\r\n')

  socket.write('RCPT TO: <ethan.arrowood@gmail.com>\r\n')

  socket.write('DATA\r\n')

  socket.write('FROM: <ethan.arrowood@gmail.com>\r\n')
  socket.write('TO: <ethan.arrowood@gmail.com>\r\n')
  socket.write('SUBJECT: Testing\r\n')
  socket.write('This is cool!\r\n')
  socket.write('.\r\n')

  socket.write('QUIT\r\n')
})

socket.on('data', buff => console.log(buff.toString()))
```
I've also tried rewriting it making use of the callback in `socket.write()`:
```javascript
const socket = net.createConnection(25, 'gmail-smtp-in.l.google.com', () => {
  console.log('Connected!')
  socket.write('HELO gmail\r\n', () => {
    socket.write('MAIL FROM: <ethan.arrowood@gmail.com>\r\n', () => {
      socket.write('RCPT TO: <ethan.arrowood@gmail.com>\r\n', () => {
        socket.write('DATA\r\n', () => {
          const data = 'FROM: <ethan.arrowood@gmail.com>\r\n' +
                                'TO: <ethan.arrowood@gmail.com>\r\n' +
                                'SUBJECT: Testing\r\n' +
                                'This is cool!\r\n'
          socket.write(data, () => {
            socket.write('.\r\n', () => {
              socket.write('QUIT\r\n')
            })
          })
        })
      })
    })
  })
})

socket.on('data', buff => console.log(buff.toString()))
```
Both of these return the same console output:
```bash
Connected!
220 mx.google.com ESMTP c13si7326141qtg.329 - gsmtp
250 mx.google.com at your service
451 4.5.0 SMTP protocol violation, see RFC 2821 c13si7326141qtg.329 - gsmtp
```
The 451 error does not tell anything. I do not believe the issue is with encoding as Node.js and Python3 both default to UTF-8.

I think my error has to do with how I'm calling .write. Like the SMTP server is receiving commands before it gets a chance to respond to a previous one. This leads me to believe there is something missing from my Node.js implementation that is provided by default in the Python3 version.

Any clues or other ideas will be much appreciated.

I expect my Node.js implementation to work just like the Python3 implementation.

**Comment by devsnek** [comment]
Your code does not wait for responses from the SMTP server. In your python example, you are using blocking sockets, meaning that each time you use `recv` you wait for the server to send a response.

In node, you'll need to use that `data` event you've subscribed to for timing when to send your messages. If you don't wait for these messages, you are violating the linked RFC 2821 (and google will start to consider your server a source of spam email)

**Comment by Ethan-Arrowood** [comment]
Yes! Okay this was the current idea/issue I was pondering. Are blocking sockets implementable in Node.js?

**Comment by addaleax** [comment]
> Are blocking sockets implementable in Node.js?

No, that would be a bad idea. As @devsnek said, you need to listen to the `data` event in order to know when server responses come in.

**Comment by Ethan-Arrowood** [comment]
Okay awesome. I think I now have a working solution. Now I'm going to read more into blocking/non-blocking sockets and what that means. Thank you for the help @devsnek and @addaleax 😄

**Comment by Ethan-Arrowood** [comment]
For anyone arriving on this thread in the future here is the code I ended up with:

```javascript
const net = require('net')

const commands = [
  'HELO gmail\r\n',
  'MAIL FROM: <ethan.arrowood@gmail.com>\r\n',
  'RCPT TO: <ethan.arrowood@gmail.com>\r\n',
  'DATA\r\n',
  'FROM: <ethan.arrowood@gmail.com>\r\nTO: <ethan.arrowood@gmail.com>\r\nSUBJECT: Testing\r\nThis is cool!\r\n.\r\n',
  'QUIT\r\n'
]

let i = 0

const socket = net.createConnection(25, 'gmail-smtp-in.l.google.com', () => console.log('Connected to gmail SMTP server.'))

socket.on('data', buff => {
  const res = buff.toString()
  console.log(res)
  if (res.includes('221 2.0.0 closing connection')) {
    socket.destroy()
  } else if (i < commands.length) {
    socket.write(commands[++i])
  } else {
    console.log('Ran out of commands but did not receive 221 response from SMTP server')
    socket.destroy()
  }
})

socket.write(commands[i])
```
