### ISSUE TITLE
Setting Chrome as my default browser for Node.js/Gulp

### ISSUE THREAD

**Issue by GusGF** [nodejs/help#1743]
* **Node.js v10.15.0**:
* **Win 10**:
* **Scope running a WP site)**:
* **Module (and version) (if relevant)**:

Incidentally I apologise in advance if the formatting of this cry for help goes awry. Can't see any way of deleting messages on here, bit puzzling why a poster isn't allowed to do this?!

I'm new to Node.js and have just installed Gulp as I'm learning WP. My default browser is Firefox but I want Chrome to be my default when using Gulp/Node.js so how do I do this as I've spent the last couple of hours looking for a solution?

I've installed the following files to my WP core directory where wp-admin, wp-content, wp-includes reside:
gulpfile.js, package.json, settings.js, webpack.config.js

I'm running the commands below in Git bash and changed the directory to the above WP core directory.

I've tried...
`Fer@DESKTOP-644OP5U MINGW64 ~/Local Sites/fictional-university/app/public
$ gulp --version
[16:34:00] CLI version 2.0.1
[16:34:00] Local version 4.0.0

Fer@DESKTOP-644OP5U MINGW64 ~/Local Sites/fictional-university/app/public
$ npm install --save set-default-browser
npm WARN fictional-university-lwc@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ set-default-browser@1.0.1
updated 1 package and audited 19790 packages in 7.013s
found 0 vulnerabilities

Fer@DESKTOP-644OP5U MINGW64 ~/Local Sites/fictional-university/app/public
$ set-default-browser chrome
bash: set-default-browser: command not found`

**Comment by addaleax** [comment]
Does `./node_modules/.bin/set-default-browser chrome` (after having installed set-default-browser), or `npx set-default-browser chrome` help?

**Comment by GusGF** [comment]
Tried both....

`$ ./node_modules/.bin/set-default-browser chrome                                                                                                       Browser not found 🙀

$ npx set-default-browser chrome help?                                                                                                                 Browser not found 🙀
--


`
--

**Comment by vsemozhetbyt** [comment]
It seems `set-default-browser` [does not support Windows](https://github.com/gokulkrishh/set-default-browser/blob/master/README.md#set-default-browser----):

> Supported platform OSX

**Comment by GusGF** [comment]
Okay so I take it their is no way of doing this in Windows unless I set Chrome as the system default whilst I'm coding!

**Comment by vsemozhetbyt** [comment]
You can try to google something like "Windows set default browser command line" — it seems there are some variants with PowerShell or VBS scripts.

Maybe somebody from @nodejs/platform-windows can help to automate this?

**Comment by GusGF** [comment]
Okay I've given up and set Chrome as default browser in Windows. But when I make a change only the first edit to my website is update in Chrome subsequent edits are ignored and I have to physically reload the page. I presume this is a Gulp issue and I'm in the wrong place for this.

```
$ gulp watch
[18:03:42] Using gulpfile ~\Local Sites\fictional-university\app\public\gulpfile.js
[18:03:42] Starting 'watch'...
[Browsersync] Proxying: http://fictionaluniversity
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.56.1:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[18:03:53] Starting '<anonymous>'...
[Browsersync] Reloading Browsers...
```

**Comment by GusGF** [comment]
> 
> 
> You can try to google something like "Windows set default browser command line" — it seems there are some variants with PowerShell or VBS scripts.
> 
> Maybe somebody from @nodejs/platform-windows can help to automate this?

@nodejs/platform-windows comes up as a clickable link that goes nowhere?!

**Comment by vsemozhetbyt** [comment]
@GusGF Sorry, I was not clear about this: this a way to mention Windows users from Node.js collaborators in case they have a bit of advice. You need not to follow this link, it is just a way to make them know they can help here.

**Comment by PoojaDurgad** [comment]
@GusGF , is this issue resolved?
