### ISSUE TITLE
Access task or microtask queue

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1744]
I am wondering if there is a way to access the task or microtask queues from vanilla node.js code? Anybody know? Say I want to put a function call on the task or microtask queue

I assume that this puts it on the task queue?

```js
process.nextTick(() => {
   thisWillGetCalledOnTheTaskQueue();
});
```

**Comment by devsnek** [comment]
you can use queueMicrotask to put a function in the microtask queue, although it's not "vanilla" (it's a function provided by node and browsers)

**Comment by ORESoftware** [comment]
Ok so that looks like: https://nodejs.org/api/globals.html

```js
process.queueMicrotask(function);
```

@devsnek so browsers provide it as window.queueMicrotask()?
