### ISSUE TITLE
HOW TO install node on a server?

### ISSUE THREAD

**Issue by tim89schulz** [nodejs/help#1745]
Please, could you make an easy-to-use step-by-step tutorial for stupid newbies?
Topics:
- node installation on ftp server
- package installation on ftp server
Thank you!

**Comment by jacob-hd** [comment]
Seriously?

http://lmgtfy.com/?q=how+to+install+nodejs

**Comment by gireeshpunathil** [comment]
ping @tim89schulz

**Comment by tniessen** [comment]
> node installation on ftp server
> package installation on ftp server

FTP has nothing to do with Node.js and you will at the very least need SSH / shell access to the maschine to install Node.js. [This page](https://nodejs.org/en/download/) contains a variety of information for various platforms and architectures.

**Comment by gireeshpunathil** [comment]
answered, closing
