### ISSUE TITLE
Running the npm link command with child_process.exec makes the callback very slow.

### ISSUE THREAD

**Issue by oftem-r** [nodejs/help#1746]
In the node.js application, executing the npm link command with child_process.exec immediately creates a linked folder in the application's node_modules, but the callback is very slow.

However, if we execute the npm link command at the command prompt, it will be returned immediately.

Please tell me why calling back with child_process.exec is very slow.

Here is the sample code.

Supplement

・windows10

・node version: 8.14.0

・my-module is installed globally.

```js
public async doNpmLink() {
    await this.execCmd("npm link my-module");
}

private execCmd(cmd: string): Promise<string> {
    return new Promise((resolve, reject) => {
        child_process.exec(cmd, (err: Error, stdout: string, stderr: string) => {
            if (err) {
                // failure
                reject(stderr);
            } else {
                // success
                resolve(stdout);
            }
        });
    });
}
```

**Comment by gireeshpunathil** [comment]
@oftem-r - is this still outstanding?

when you say `callback is very slow.` - does this mean:
 - the execution time of the callback takes more time,
or
- the delay between the child process trigger and the callback entrance is more?

**Comment by oftem-r** [comment]
> @oftem-r - is this still outstanding?
> 
> when you say `callback is very slow.` - does this mean:
> 
> * the execution time of the callback takes more time,
>   or
> * the delay between the child process trigger and the callback entrance is more?
Thanks for your comment.
It is still unsolved.

Calling the doNpmLink () method and calling the execCmd () method in it means that the link folder will be created immediately, but the callback of the child_process.exec () method will not be called immediately. (Not immediately resolved)

**Comment by gireeshpunathil** [comment]
ok - can you please tell me how are the measurements looking like, for both the baseline and the faulty one?

**Comment by oftem-r** [comment]
> ok - can you please tell me how are the measurements looking like, for both the baseline and the faulty one?

In this source code, it takes about 3 minutes before the resolve () method is called.

On the other hand, "npm link" on the command line will return in a few seconds.

**Comment by gireeshpunathil** [comment]
@oftem-r - thanks for the info. Do you have a linux environment to try out as well? Why I say that is, issue often manifest through environmental peculiarities (in this case say file system, process management etc.) so trying out in a different box will reveal more insights.

**Comment by oftem-r** [comment]
> @oftem-r - thanks for the info. Do you have a linux environment to try out as well? Why I say that is, issue often manifest through environmental peculiarities (in this case say file system, process management etc.) so trying out in a different box will reveal more insights.

Thank you for your reply.
We tried before, but it was the same result with windows and linux.

**Comment by davestewart** [comment]
Having the same issue.

FWIW I used the programmatic method as I needed to link several packages, but just found out you can pass multiple package names to `npm link`:

```
npm link foo bar baz
```

If you do as follows:

```
npm link foo
npm link bar
npm link baz
```

Then the later ones reinstall all packages, and only links the last package.

Hopefully that helps someone, if not solves the problem here.

**Comment by benjamingr** [comment]
This seems to be inactive, if you'd like Node to investigate a perf regression nowadays please open an issue in https://github.com/nodejs/performance - cheers.
