### ISSUE TITLE
node@6.16

### ISSUE THREAD

**Issue by AndriyHromyak** [nodejs/help#1747]
* **Node.js Version**: 6.16.0
* **OS **:- macOS
* **Scope (install, code, runtime, met

Why after updating node to 6.16.0 Intl is now empty object? toLocaleString now does nothing. After googling found that now i should install Intl via npm however after installing Intl, global Intl is not empty object but still it does nothing. any suggestions? problem is that in my Jest tests (3500).toLocaleString was supposed to convert it to 3,500 but it doesnt so my tests fail

**Comment by vsemozhetbyt** [comment]
cc @nodejs/intl

**Comment by gireeshpunathil** [comment]
cc @nodejs/intl @nodejs/i18n again - don't know whether @vsemozhetbyt 's ping has worked or not (the text is not bold)

**Comment by gireeshpunathil** [comment]
@AndriyHromyak - also a reminder that node v6.x is out of support

**Comment by AndriyHromyak** [comment]
Will v6.x be still available for use? I am not ready to migrate to latest version since it will require a lot of time to migrate. And is there any end date when everybody should be migrate to newest version?

**Comment by gireeshpunathil** [comment]
@AndriyHromyak - while outdated versions (including v6.x) will be available for download for an unspecified amount of time, there will not be any development and support effort spent on those. This will mean you will miss a number of bug fixes which are applied on the latest version, at a minimum.

There is no end date for migration.

Let me know if I can be of any help with your migration!

**Comment by bnb** [comment]
@AndriyHromyak it's also worth noting that any security issues disclosed post EOL will not be patched with new releases to the 6.x release line. This includes dependency updates, like OpenSSL which has semi-frequent patches for vulnerabilities.

**Comment by srl295** [comment]
Hi, I couldn't reproduce on 6.16 or 6.17:

```
$ nvm i 6.16
v6.16.0 is already installed.
Now using node v6.16.0 (npm v3.10.10)
$ node
> (3500).toLocaleString()
'3,500'
```

What do you mean by `Intl` is an empty object?

**Comment by AndriyHromyak** [comment]
Hi all, thx for response, i have followed gireeshpunathil advice and have updated my node version, also srl295 thx for reply, this happened while running unit tests using jest, maybe there is some relativeness because of that, i will try to reproduce it later and post here error. but since its working on your env might be because of some other dependencies in my project.

**Comment by srl295** [comment]
@AndriyHromyak it would be interesting to see what failures you encountered. If you think this is working for you now, you might close this issue since it does not seem easily reproducible.

**Comment by AndriyHromyak** [comment]
Yes i will close issue, tried to reproduce issue however it is working now, and i don't understand why. the only difference is that i have previously installed node v 16.6.0 using brew on mac, now i have installed it via npm and tests passed ok. strange. any way thx all
