### ISSUE TITLE
Node stuck on v8.0.0

### ISSUE THREAD

**Issue by mesamhaider** [nodejs/help#1749]
* **Node.js Version**:v8.0.0
* **OS**:Mac OS
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**:

I am having trouble installing a version of node higher than v8.0.0. I am attempted to install v11.8.0 or whatever the most stable version is however I am not able to. The command I am running is "sudo n stable" which installs v11 however when I do node -v it still returns v8.0.0. What could I be missing or doing wrong?

**Comment by yathamravali** [comment]
It is working fine for me with `sudo n stable` and upgraded to v11.8.0.
Could u run `which node` so that if the path is still pointing to the older one prior to the new one, then even when  new node version is installed :`node -v` gives older version.

**Comment by mesamhaider** [comment]
Yeah, its pointing to the older version!!

**Comment by mesamhaider** [comment]
Need
