### ISSUE TITLE
sockets

### ISSUE THREAD

**Issue by niwsa** [nodejs/help#175]
var ws = new WebSocket("wss://websocket.kite.trade/?api_key=xxx&user_id=AB0012&public_token=xxxx")

Is there a way to open a socket connection as shown above in internal net module,as you can see I am sending query parameters.

**Comment by lordKnighton** [comment]
I'm sure there are multiple ways to go about it. But what springs to mind is socket.io
Go and check out the **`docs`**
 it should be something like this:

var socket = io.connect('http://localhost:3000/', { query: 'token=12345' });

so in your case, maybe something like:

var ws = io.connect("wss://websocket.kite.trade/?api_key=xxx&user_id=AB0012&public_token=xxxx")

Be sure to check out the docs, if you need further help, reopen & go from there.

**Comment by niwsa** [comment]
Thanks but I was checking whether its possible via the internal sockets library of node js

**Comment by lordKnighton** [comment]
If you have your heart set on internal net module
then i think this is your best bet
```js 
socket.write
```
docs
https://nodejs.org/dist/latest-v4.x/docs/api/net.html#net_socket_write_data_encoding_callback

Other wise, people are mostly using socket.io to deal with socket work. 
Anyway, happy coding 👍
