### ISSUE TITLE
npm install family must be 4 or 6 error

### ISSUE THREAD

**Issue by eatthoselemons** [nodejs/help#1752]
* **Node.js Version**: 8.10.0
* **OS**: Ubuntu 18.04 VM
* **Scope (install, code, runtime, meta, other?)**: NPM install
* **Module (and version) (if relevant)**: Seems to be anything NPM related

I cannot seem to pin down where this error is coming from. I cannot use `npm install` on anything I tried using these other 2 issues: 
https://github.com/nodejs/help/issues/1556
https://github.com/nodejs/node/issues/8635

However I cannot seem to get npm to work

The full output of `node --trace /usr/lib/nodejs/npm/bin/npm-cli.js install async > output.txt` as suggested in the github issue (modified to use `nodejs/` instead of `node_modules`

npm i npm -g
npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "npm" "-g"
npm ERR! node v8.10.0
npm ERR! npm v3.5.2

npm ERR! Invalid argument: family must be 4 or 6
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>

After spitting out this error npm just hangs till you `^C`

I have no idea where to go from here, does anyone have any ideas on what could be causing this or where I should look?

**Comment by yathamravali** [comment]
Can u post the `--trace` output (output.txt)

**Comment by eatthoselemons** [comment]
Would you like the whole file from the node --trace command? the output.txt file is 24151 lines long (for a quick escape and a 15-minute wait produced a 406,037 line file) and the node command just hangs waited for 15 minutes and it just had the output above.

**Comment by yathamravali** [comment]
@eatthoselemons 
I want to see the call sequences that is leading to `Invalid argument: family must be 4 or 6`. So can u do reverse search(start from bottom)  in trace output and fetch 1000 lines above the error `family must be 4 or 6` including that line.

You can upload those 1000 lines trace output on gist.

**Comment by eatthoselemons** [comment]
I have made I paste with the 1000 lines before the error: https://pastebin.com/LHGwVUyM

Based on my understanding of the code that I have dug through it seems to be a networking issue? It appears that that error is from the dns.js files? I don't know if that helps at all, or maybe you already suspected it anyway hopefully it helps!

https://github.com/nodejs/node/blob/0ce615c4af2fbd19f99b5c65c044ce33cd4e1eba/doc/api/dns.md

https://github.com/nodejs/node/blob/master/lib/dns.js

**Comment by vidsgr** [comment]
I have seen same issue, with various versions of npm and nodejs on Ubuntu 18.04, Debian (8/9) and Alpine (docker). In all these cases, except Alpine, I have use debootstrap to install OS. When I used minimal server iso to install Ubuntu, it simply worked without any issue. I feel it is not really related to nodejs, but it's dependencies. I hope it helps.

**Comment by Michael-Sivalls** [comment]
@yathamravali were you able to figure out the issue?

**Comment by marsonya** [comment]
Kindly take a look at [issue #8635](https://github.com/nodejs/node/issues/8635) in the node repository. There is detailed discussion on this problem. Hope this helps.

I am closing this issue now. You can always reopen it incase there is something more to add to it.
