### ISSUE TITLE
How to prepend Node.js switch thread when working with some third-party library

### ISSUE THREAD

**Issue by vit1251** [nodejs/help#1753]
I work with third-party library (readonly) and this library create thread pool and when I receive call from another one thread library abort with assertion 🎉

Yet another difficult is assertion in Node.js when some external thread call a С callback with ```napi_call_function``` in this case Node.js also abort 🎉

Do u have a way to prepend (similar OsLockThread in Golang) switching threads in Node.js and right I understand that I should review ```napi_call_threadsafe_function``` help section?

Do u know npm packet with similar problem for I can review source code? Or even node.js have example with N-API on plain C source code about thread pool examples?

**Comment by ORESoftware** [comment]
Probably want to check these examples out:

https://github.com/nodejs/node-addon-examples
https://github.com/nodejs/node-addon-api

**Comment by gireeshpunathil** [comment]
also cc @gabrielschulhof and @mhdawson

**Comment by gabrielschulhof** [comment]
@vit1251 you may want to use https://nodejs.org/api/n-api.html#n_api_asynchronous_thread_safe_function_calls

**Comment by gireeshpunathil** [comment]
ping @vit1251

**Comment by gireeshpunathil** [comment]
answered, closing
