### ISSUE TITLE
Nodejs halted/stopped client to access the site or crashing browser

### ISSUE THREAD

**Issue by josephmiller2000** [nodejs/help#1756]
* **Node.js Version**: v8.15.0
* **OS**: Ubuntu 18.10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: socket.io, react redux, server NGINX
Database : mongodb

Last day, we made beta testing in our chat site using 20+ users. This is not the first time we are doing this beta test. But, before we used to have bugs and fixed everything now. So we made another beta test to make sure the chat can hold more users at a time (concurrent). 

Technically, it works like a charm when we have 10 or 15 users at a time, but when we reach more than 20+ or 30+ it crashes in client side, Attaching screenshot of the chat, HTOP result and console logs.

![snap_shot_00384](https://user-images.githubusercontent.com/24210340/52485300-8d028f00-2bde-11e9-8304-1b188cdbfac7.jpg)

I have increased the ulimit system wide from 1024 to 90000 for all process.

Open file limits also increased system wide in root and nginx too.

Our developer also confused and have no idea what is cusing this issue, becoz there is not log error when this happens.

Just take a look at the HTOP result in the screenshot and confirm me,  what is going on, it is NODEJS causing this issue?

![snap_shot_00385](https://user-images.githubusercontent.com/24210340/52485611-45c8ce00-2bdf-11e9-99a3-74630e04a662.jpg)

**Comment by gireeshpunathil** [comment]
@josephmiller2000 - can you clarify:
 - when you say crash, did you mean the client just terminates? or becomes un-usable?
 - what is the data you want to highlight from the `HTOP` tool? memory / CPU / I/O ?

high CPU or high I/O are not expected to crash the process, they can potentially slow down things. So it is important to know what happened to the process - termination or hang, and what you see in the `top` output.

**Comment by gireeshpunathil** [comment]
no followup, closing. feel free to reopen if the issue resurfaces
