### ISSUE TITLE
Question for nodejs

### ISSUE THREAD

**Issue by chandankrishnan** [nodejs/help#176]
can we install any software by using nodejs??

**Comment by lordKnighton** [comment]
can you expand on this question?

**Comment by chandankrishnan** [comment]
suppose,in my computer not install node or npm or any software ...then install those software install via by node app's...is it possible????
I can try using child_process module but i have problem with follow cmd
sudo apt-get update
sudo apt-get install nodejs

can you help me??

**Comment by lordKnighton** [comment]
sure: so you do or don't have node.js & nom installed on your computer?

**Comment by lordKnighton** [comment]
I think i see what you mean: To my knowledge I don't think you can. Before you can use node, you computer has to have it. 

You can't use it, if you don't have it. 😄

**Comment by chandankrishnan** [comment]
I installed already installed but  I develope a one app those installed node by one click if i want to install node....

**Comment by lordKnighton** [comment]
Closing for now, but if you wish to further pursue this, feel free to reopen & ✨ spark the conversation.

**Comment by chandankrishnan** [comment]
very good developer...???
