### ISSUE TITLE
Node return value in native C binding

### ISSUE THREAD

**Issue by vit1251** [nodejs/help#1761]
Could I leave ```nullptr``` return value in my own export function in ```napi_result``` or I always should return N-API value by ```napi_get_null```?

Example:

```
napi_value MyFunction(napi_env env, napi_callback_info info)
{
    napi_value result = nullptr;
    napi_status status;
    // TODO - implement it little later ...
    return result;
}
```

**Comment by addaleax** [comment]
> Could I leave `nullptr` return value in my own export function in `napi_result` 

Yes, that is the same as returning `undefined`.

**Comment by vit1251** [comment]
@addaleax thanx.
