### ISSUE TITLE
How to enable libuv socket debug enable?

### ISSUE THREAD

**Issue by vit1251** [nodejs/help#1762]
How to determine socket errors i.e. TCP RST event on Node.js HTTP server (i.e. using ```express``` server) on long term service? Service work more than 10 hour and some connections was abort ( i.e. less than 1% ). I want to avoid dump all HTTP sessions.

Any ideas are welcome I use localhost socket binding on Node.js version 11,

**Comment by aymen94** [comment]
You can try to use these libraries to debug socket:
[node-monkey](https://github.com/jwarkentin/node-monkey )
[socket.io](https://socket.io/)
[longjohn](https://github.com/mattinsler/longjohn)
[socket.io-tester](https://github.com/AppSaloon/socket.io-tester)
these are just a few, there are many others.
let me know what you've used 😄

**Comment by gireeshpunathil** [comment]
closing as answered
