### ISSUE TITLE
Multiple process.stdin.write

### ISSUE THREAD

**Issue by Ladvace** [nodejs/help#1763]
* **11.6.0**:
* **win 10**:
* **child_process**:

I'm trying to make multiple stdin.write of a process, the problem is that only the first one is runned, other stdin.write below the first one are ignored.

```js
const  stringio = require('@rauschma/stringio');
const child = require('child_process');

const start = child.spawn(`java -Xms512M -Xmx1024M -jar ./TEST-FILE.jar`,
  [], { shell: true });


async function writeToWritable(writable, data) {
  console.log("WRITABLE", writable);
  //await stringio.streamWrite(writable, data);
  // await streamWrite(writable, 'Second line\n');
  //await stringio.streamEnd(writable);
  await writable.write(data);
  await writable.end(data);
}

async function runCommand(){
  try {
    const paramL = `/command commandParameter`;
    await writeToWritable(start.stdin, paramL);
  } catch {

  }
}

(() => {
try{
    setTimeout(runCommand, 20000);
    setTimeout(runCommand, 30000);
}catch(err){
  console.log(err);
}

})();
```
-->

**Comment by addaleax** [comment]
Can you maybe provide a full example?

**Comment by Ladvace** [comment]
What do you mean with "full example" this is a working example

**Comment by addaleax** [comment]
@Ladvace This uses an external program (the java program you’re using here).

When I simply use `cat` as the command that is spawned and add `start.stdout.pipe(process.stdout);`, I get the expected result.

**Comment by Ladvace** [comment]
sorry, the external java program is a java server

**Comment by addaleax** [comment]
@ladvace Yes, but without it it’s hard to understand what you are seeing; in particular, why you think that the second `.write()` call gets lost?

**Comment by Ladvace** [comment]
https://minecraft.net/en-us/download/server/ here is the file

**Comment by Ladvace** [comment]
because if i look at the console it doesn't run while the first yes

**Comment by Ladvace** [comment]
Can i ask why are you adding `start.stdout.pipe(process.stdout);`?

**Comment by addaleax** [comment]
@Ladvace Because that’s the easiest way to see what data `cat` is getting.

It’s usually a good idea to pipe stdout and stderr for a process unless you are using them, or already inherit them explicitly.

Either way, I’m guessing that turning

```js
const paramL = `/command commandParameter`;
```

into

```js
const paramL = `/command commandParameter\n`;
```

might help, because otherwise both chunks of data you’re writing end up being part of the same line.

**Comment by Ladvace** [comment]
i didn't understand the difference between `.write(**command**)` and `.end(**command**)`, at the moment i do a `.write (**command**)` and then a `.end()`

**Comment by Ladvace** [comment]
i thought the `\n`, i will try it and i will tell you then, for the momentt thanks for your help

**Comment by Ladvace** [comment]
adding `\n` i get the follow error **NodeError: write after end**

**Comment by addaleax** [comment]
@Ladvace That’s because you call `.end()` twice – once for the first `writeToWritable()`, once for the second `writeToWritable()`.

You should only call `.end()` if you intend not to write any more data to the stream.

**Comment by Ladvace** [comment]
I think I've solved, THANKS!

**Comment by Ladvace** [comment]
i thought that the `.end()` essential but i understood i don't need it

**Comment by gireeshpunathil** [comment]
closing as answered.
