### ISSUE TITLE
Test  parallel/test-assert failing?

### ISSUE THREAD

**Issue by dankegel** [nodejs/help#1767]
* **Node.js Version**: debian/10.4.0_dfsg-2
* **OS**: ubuntu 18.04
* **Scope (install, code, runtime, meta, other?)**: build/test
* **Module (and version) (if relevant)**: 

My skill level is "comfortable with assembly, C, C++, perl, python, authoring and building debian packages, not so comfortable with node or rollup or all the new web-ish toys".

ubuntu 18.04's packaged node has some openssl-related issues
(see https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/1794589 for the sad story)
so I thought I'd try building a slightly newer version from source, using the system's default openssl.
Debian and ubuntu share a nice git repo showing exactly how they build nodejs,
so it's relatively easy to try the experiment.

My first try was to use the same git revision that Ubuntu 19.04 will use, but that
was so fresh that it was out of sync with Ubuntu 18.04 (see #1760).
So I scrolled back in git history to an earlier release, and tried building as follows:

```
$ git clone https://salsa.debian.org/js-team/nodejs.git 
$ cd nodejs
$ git checkout debian/10.4.0_dfsg-2
$ vi debian/control    # and remove version specifier from libhttp-parser-dev; 18.04's is older
$ sudo mk-build-deps -i
$ debuild -b -uc -us
```
This went smoothly.  Not surprisingly, there were a few test failures:
```
not ok 4 parallel/test-assert
not ok 743 parallel/test-http-methods
not ok 818 parallel/test-http-upgrade-advertise
not ok 1363 parallel/test-repl-preprocess-top-level-await
not ok 1694 parallel/test-tls-server-verify
```

Looking at the test failures:

- The http ones are probably because of the old libhttp-parser-dev, and might be skippable.
- The test-tls-server-verify one is some cert problem, and might be skippable.
- The parallel/test-repl-preprocess-top-level-await looks like the way debian pulls in the acorn dependency is unhappy (mumble mumble rollup; here be packaging magic, the latest ubuntu acorn mentions 'Rebuild against new bootstrapped rollup.', https://launchpad.net/ubuntu/+source/acorn/5.5.3+ds3-1ubuntu2 )

Which leaves test-assert, for which I don't have a theory yet:
```
not ok 4 parallel/test-assert
  ---
  duration_ms: 0.713
  severity: fail
  exitcode: 1
  stack: |-
    /home/dank/xsrc/nodejs-10.4.0/test/common/index.js:728
            throw new assert.AssertionError({
            ^

    AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
    + expected - actual

      Comparison {
        code: 'ERR_ASSERTION',
        type: [Function: AssertionError],
    -   message: 'false == true'
    +   message: 'The expression evaluated to a falsy value:\n\n  assert.ok(typeof 123 === \'string\')\n'
      }
```

Can I buy a clue?  What's going on in that assertion assertion failure?

**Comment by gireeshpunathil** [comment]
@dankegel - is this still happening?

**Comment by gireeshpunathil** [comment]
inactive, closing
