### ISSUE TITLE
Node stacktrace on a single line?

### ISSUE THREAD

**Issue by justechn** [nodejs/help#177]
I am just getting started with Node and Docker and I am trying to use the docker logging drivers for graylog. I have it working, but I ran into a problem when node prints out a stacktrace. Since docker sends each newline to graylog a stacktrace ends up split up in a bunch of separate logs. 

I asked the docker group about this and they said they have no way of knowing when a log starts and ends, so they can't help.

I was wondering if there was a way to get node to output each error and debug on a single line in json object or something similar?

the logs in graylog look like this, which you can see is not helpful
![image](https://cloud.githubusercontent.com/assets/1508662/15551308/9dac1bb4-2272-11e6-97e4-97f234f169b5.png)

**Comment by lordKnighton** [comment]
This is my first time seeing anything with docker error. can you share some of your code?

**Comment by lordKnighton** [comment]
Closing for now, reopen if you need further help.

happy coding 🎱

**Comment by justechn** [comment]
What? This has nothing to do with my original question. The issue you linked to is about symlinks, I need help getting stack traces onto a single line

So instead of printing a stack trace on 10 lines, it would print the stack trace on one line in a json object or something similar.

**Comment by addaleax** [comment]
One thing you can do, in general, is modify how stack traces are generated:

```js
Error.prepareStackTrace = (err, stack) => JSON.stringify({
  message: err.message,
  stack: stack.map(frame => ({
    file: frame.getFileName(),
    column: frame.getColumnNumber(),
    line: frame.getLineNumber(),
    functionName: frame.getFunctionName()
  }))
});
```

(See https://github.com/v8/v8/wiki/Stack-Trace-API).

However, inserting that will only help as far as your own Node code is concerned. This is an error from `npm` command line output, and if you want to debug, the `npm-debug.log` contents will often be more helpful than the error message itself.

**Comment by lordKnighton** [comment]
My apologies, I'm a bit tired 😫 and was aiming to fix your errors, which that link would fix. But As I stated above i have no prior docker experience. And will leave this for one of my cohorts to deal with.

**Comment by justechn** [comment]
Thanks, I will try that. 

Is there a way to get the npm-debug.log to print to stdout and then do something similar and put it in a json object?

**Comment by Trott** [comment]
> Is there a way to get the npm-debug.log to print to stdout and then do something similar and put it in a json object?

Sorry no one has answered that question. You might try asking in an npm forum.

This issue has been quiet for four almost months so I'm going to close it. If you feel that it should remain open, feel free to comment to that effect. (Just tidying up around here; not looking to close things that shouldn't be closed though.)
