### ISSUE TITLE
how to import css file in node not express

### ISSUE THREAD

**Issue by Macfa** [nodejs/help#1771]
* **Node.js Version**: 10.10
* **OS**: Mac mojave
* **Scope (install, code, runtime, meta, other?)**: import css
* **Module (and version) (if relevant)**: ..? 

hi, I build up http server, 
I setting up a router and provide html file and css, js 

```html
...
<head>
<script>
<link href="..."
</script>
</head>
```
and..

```js
require './file/css/index.css'
```
wrote each above, but, I couldn't import css and js
how to using external css

**Comment by alipiry** [comment]
@Macfa hello there, could you explain what you want to do in more detail?

**Comment by Macfa** [comment]
@alipiry 
Hello, 
first, I really aprociate response
here's my answer

reqHandler
```js
var exec = require("child_process").exec;
var fs = require('fs');


function start(res) {
  console.log("Request handler 'start' was called.");
  var body = fs.readFileSync('./html/index.html', 'utf8');
    res.writeHead(200, {"Content-Type": "text/html"});
    res.write(body);
    console.log(body);
    res.end();
}

function upload(res) {
    console.log("Request handler 'upload' was called.");
    res.writeHead(200, {"Content-Type": "text/plain"});
    res.write("Hello Upload");
    res.end();
}

exports.start = start;
exports.upload = upload;
```

here's index.html
```html
<html>
	<head>
		<meta charset="UTF-8">
		<style>(./css/index.css)</style>
	</head>
	<body>
		<div class="main">
			<div class="main_section_items">
				<div class="main_section_item">
					<h2>환영합니다.</h2>
					<p>
						공고생의 블로그입니다.
					</p>
				</div>
				<div class="main_section_item">
				</div>
			</div>
		</div>
	</body>
</html>
```

now, I want to add import external css file on index.html file
I had a lot thing for...
npm install import-css  and add 
"<style>(critical css)</style>" on index.html file
but, there a page except css file..
I want to a personal webpage : )

**Comment by alipiry** [comment]
@Macfa I think you should use `link` tag:

```html
<head>
  <link rel ="stylesheet" type ="text/css" href ="./css/index.css" />
</head>
```
and you do not need to install any npm extra package to do that!

**Comment by Macfa** [comment]
@alipiry 
thanks answer

I write like this
```html
<html>
    <head>
        <meta charset="UTF-8">
        <link rel ="stylesheet" type ="text/css" href ="./html/css/index.css" />
    </head>
    <body>
        <div class="main">
            <div class="main_section_items">
                <div class="main_section_item">
                    <h2>환영합니다.</h2>
                    <p> 
                        공고생의 블로그입니다. 
                    </p>
                </div>
                <div class="main_section_item">
                    <form action="/upload" method="post">
                        <textarea name="text" rows="20" cols="60"></textarea>
                        <input type="submit" value="Submit text" />
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>
```

and start node server, but i got this error

onRequest() /css/index.css received
About to route a request for /css/index.css
No request handler found for /css/index.css
^C

I install 'import-css' using npm 
and I following package's example
site:https://www.npmjs.com/package/import-css

but it didn't worked  : (

**Comment by alipiry** [comment]
@Macfa you probably inserted wrong `href` to your `link` tag,

where is your `css` dir? 
could you mention your project tree here?

**Comment by HrithikMittal** [comment]
This code will help to import CSS file only in Node Js (without using expres Js) -  

```
var http = require('http');
var url = require('url');
var fs = require('fs');
var path = require('path');

const mimetypes = {
    'html': 'text/html',
    'css': 'text/css',
    'js': 'text/javascript',
    'png': 'image/png',
    'jpeg': 'image/jpeg',
    'jpg': 'image/jpg'
};

var portname = '127.0.0.1';
var port = '3000';

http.createServer((req, res) => {
    var myuri = url.parse(req.url).pathname;
    var filename = path.join(process.cwd(), unescape(myuri));
    console.log('File you are looking for is:' + filename);
    var loadFile;

    try {
        loadFile = fs.lstatSync(filename);
    } catch (error) {
        res.writeHead(404, {
            "Content-Type": 'text/plain'
        });
        res.write('404 Internal Error');
        res.end();
        return;
    }

    if (loadFile.isFile()) {
        var mimeType = mimetypes[path.extname(filename).split('.').reverse()[0]];
        res.writeHead(200, {
            "Content-Type": mimeType
        });
        var filestream = fs.createReadStream(filename);
        filestream.pipe(res);
    } else if (loadFile.isDirectory()) {
        res.writeHead(302, {
            'Location': 'index.html'
        });
        res.end();
    } else {
        res.writeHead(500, {
            "Content-Type": 'text/plain'
        });
        res.write('500 Internal Error');
        res.end();
    }

}).listen(port, portname, () => {
    console.log(`Server is running on server http://${portname}:${port}`);
});
```

**Comment by Macfa** [comment]
@alipiry 

/Users/???/git/node // all node file in this path
/Users/???/git/node/html // all html file in this path
/Users/???/git/node/html/css // all css file
/Users/???/git/node/html/js // all js file

@HrithikMittal 

thanks
I'll reponse a result of try it

**Comment by aymen94** [comment]
For  a cleaner code, create in root a folder to insert all static files (CSS, JS) with name `assets`
```
const path = require('path');
const basePath = __dirname;

var assets = path.join(basePath,'assets');
```
and use this code for get reference. 😄

**Comment by HrithikMittal** [comment]
@Macfa 
If you get any error just tell me

**Comment by Macfa** [comment]
@HrithikMittal 
@aymen94 
@alipiry 
thanks all !!

I solved this problem
problem is priority in my logic and how to load css

modify a logic that load asset first than load html ( see my router.js )
and I add link tag in html 
I really didn't know how to load css in nodejs before read nodejsgarden site
actually I can't see a log load css cuz wrong logic above
so.. I've modify a logic then, I can see a log:PATHNAME : index.css

Thanks all guys.

HERE is my site
https://github.com/macfa/nodejs
Thanks to Helpful
https://nodejsgarden.wordpress.com/2013/07/16/render-static-files-with-node-js/#more-24

**Comment by alipiry** [comment]
@Macfa you're welcome! Good luck

**Comment by Hariprabu94** [comment]
I have problems with node js file.......... kindly assist. When i load my HTML file normally everything works fine. When it's loaded through node server, my css background colors are changed....images are not loading

**Comment by George-giorgi** [comment]
var http = require('http');
var url = require('url')
var fs = require('fs')
// var path = require("path")

// var formidable =require("formidable")

http.createServer((req,res)=>{
    console.log(req.url)
        if(req.url == "/test.css"){
            res.writeHead(200, {'Content-Type': 'text/css'})
            fs.readFile("test.css", (err, data)=>{
                res.write(data)
                res.end()
            })
        }else{
            res.writeHead(200, {'Content-Type': 'text/html'})
            fs.readFile("test.html", (err, data)=>{
                
                res.write(data)
                res.end()
            })
        }
  
}).listen(8080,()=>console.log("server started !"))
