### ISSUE TITLE
if nodejs can support armv5 cpu?

### ISSUE THREAD

**Issue by hnhuangda** [nodejs/help#1772]
Node.js Version: 0.10.43
OS: Linux router 4.1.0 #1 PREEMPT Tue Jan 29 18:08:34 HKT 2019 armv5tejl GNU/Linux

nodejs  v0.10.43 run error Segmentation fault.

![image](https://user-images.githubusercontent.com/47627432/52830972-bf941680-310d-11e9-8b01-59125731ee79.png)

I want to know if nodejs can support armv5 cpu? i have a project need use nodejs on armv5 cpu.

**Comment by aymen94** [comment]
The latest versions of node.js require at least one CPU compatible with ARMv6. You can use the v0.10 branch for armv5.

**Comment by hnhuangda** [comment]
> The latest versions of node.js require at least one CPU compatible with ARMv6. You can use the v0.10 branch for armv5.

thanks aymen94.

But many versions(0.10.x) have been tested, they all  failed the test. run node segmentation fault. you can see the screenshot.

Do you have any idea for this problem?

**Comment by gireeshpunathil** [comment]
unfortunately node v0.10 is out of support!

**Comment by gireeshpunathil** [comment]
closing; please re-open if there is anything outstanding here
