### ISSUE TITLE
Debug in Visual Studio 2017

### ISSUE THREAD

**Issue by iwl** [nodejs/help#1773]
* **Node.js Version**: v0.12.2
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Debug

How can I debug node.js in Visual Studio 2017, I can only choose browsers?

What Do I have to add, cmd line, options?

**Comment by aymen94** [comment]
Of course, you can do it debug with Visual Studio 2017, follow this [guide](https://github.com/Microsoft/nodejstools/wiki/Debugging). 😃

**Comment by iwl** [comment]
I have a project from GitHub     https://github.com/zigbeer/cc-znp

and tried to import it as node.js from existing code into Visual Studio 2017, have to chose
File/New/Project/JavaScript/Node.js/From existing Code

It seems like a web project is created then (runs in browsers to choose)

I can make a new empty Node.js console project and that is running in node.js then

Question is how I can make such a node.js console project from above existing code

I tried to mix together the new console project with the existing code on my own, 
but doesn't work straight forward.

-----Ursprüngliche Nachricht-----
Von: "Aymen Naghmouchi" <notifications@github.com>
Gesendet: Freitag, 15. Februar 2019 09:34
An: nodejs/help <help@noreply.github.com>
Cc: iwl <ingo.wolf@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [nodejs/help] Debug in Visual Studio 2017 (#1773)

Of course, you can do it debug with Visual Studio 2017, follow this [guide](https://github.com/Microsoft/nodejstools/wiki/Debugging). 😃 -- You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub:https://github.com/nodejs/help/issues/1773#issuecomment-463952370

**Comment by gireeshpunathil** [comment]
ping @iwl - is this still an issue?

**Comment by gireeshpunathil** [comment]
answered, closing
