### ISSUE TITLE
Visual Studio 2017 node.js console project existing Code

### ISSUE THREAD

**Issue by iwl** [nodejs/help#1774]
* **Node.js Version**: v0.12.2
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Visual Studio

Creating a new node.js project from existing code in Visual Studio 2017 a web browser project is made, browser to run in choosable.
I have a existing node.js standalone/console code.
I can make a new empty node.js console project and that runs in node.js as I need.
How Do I do that from existing code?
I couldn't manage to mix the new empty with the existing code yet.

As far I understand if it runs in a browser it is just Javascript, node.js is outside a browser.
So that is a wrong systematics in Visual Studio.

**Comment by gireeshpunathil** [comment]
@iwl - Is this still an issue? If so, could you please post this with Visual Studio Project? Node.js does not develop or maintain Visual Studio.

**Comment by gireeshpunathil** [comment]
inactive, closing
