### ISSUE TITLE
modify require.main doesn't works

### ISSUE THREAD

**Issue by AlvinYuXT** [nodejs/help#1775]
* **Node.js Version**:v10.13.0
* **OS**: MacOS
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

I run `node /User/yxt/a.js`  in the ` /Users/yxt/test` directory.  `a.js` looks like this:

```js
const aa = require('an npm package')
aa()
```

and in the `aa` method, it wants to require an module installed in `/User/yxt/test/node_modules`. So I modify code like this:

```js
const aa = require('an npm package')
require.main.path.push(path.resolve('/User/yxt/test/node_modules'))
aa()
```
It still cannot require module from `/User/yxt/test/node_modules`

**Comment by gireeshpunathil** [comment]
Here is the complete sequence of module loading logic: https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_all_together

I am not sure modifying `require.main.path` is legal or not. Can you try with createRequireFromPath to see if it helps? https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_module_createrequirefrompath_filename

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if there is anything outstanding
