### ISSUE TITLE
How to convert doc to pdf with SDK approach with nodeJS.

### ISSUE THREAD

**Issue by naresh101010** [nodejs/help#1776]
Hello all,
I am working on a node application, the requirement is to convert word document to pdf with real ms word application. There are a lot of module available on npm but all are libra office based and not able to convert properly.

**Comment by aymen94** [comment]
Try this 
[node-msoffice-pdf](https://www.npmjs.com/package/node-msoffice-pdf)
or
[office-converter](https://www.npmjs.com/package/office-converter)

**Comment by gireeshpunathil** [comment]
answered, closing
