### ISSUE TITLE
linux system node js core module path Where?

### ISSUE THREAD

**Issue by Luncher** [nodejs/help#178]
I'm reading nodejs modules system, ask a question， linux system node js core module path Where?

**Comment by r1b** [comment]
When you install modules with `npm install pkg`, they go into a `node_modules/` folder in your current package root (the folder where your package.json resides).

When you install a module _globally_, like `npm install -g pkg`, they go into your prefix directory. This location varies depending on your platform, you can print out the global prefix with `npm prefix -g`.

Here are some more details:
https://docs.npmjs.com/files/folders

**Comment by Luncher** [comment]
I say `core module`,such `http`, `fs` and so on.

**Comment by r1b** [comment]
Ah, apologies for misunderstanding. I do not know the answer for sure, but I believe these modules are included in the nodejs runtime. That is, they are not loaded from disk. The [require algorithm](https://nodejs.org/api/modules.html#modules_all_together) supports this conclusion.

**Comment by addaleax** [comment]
@r1b is correct, the core modules are built into the `node` executable that you are running and are not loaded from the file system.

**Comment by Luncher** [comment]
thanks @r1b @addaleax
