### ISSUE TITLE
The worker_threads to create threads pool,how to lock the work thread? 

### ISSUE THREAD

**Issue by chengdonglin** [nodejs/help#1786]
* **Node.js Version**:11.10.0
* **OS**:win10
The worker_threads to create threads pool to deal tasks,how to lock the work thread ?

**Comment by addaleax** [comment]
Can you explain what you mean when you say “locking” the thread?

**Comment by chengdonglin** [comment]
When we create thread pool, When there is a thread  to take the task in the task queue, other threads are waiting, so that multiple threads will not take the same task at the same time, just like the thread lock mechanism in java.

发送自 Windows 10 版邮件应用

发件人: Anna Henningsen
发送时间: 2019年2月21日 18:41
收件人: nodejs/help
抄送: chengdonglin; Author
主题: Re: [nodejs/help] The worker_threads to create threads pool,how tolock the work thread? (#1786)

Can you explain what you mean when you say “locking” the thread?

**Comment by addaleax** [comment]
> When we create thread pool, When there is a thread to take the task in the task queue, other threads are waiting, so that multiple threads will not take the same task at the same time, just like the thread lock mechanism in java. 

@chengdonglin You should almost never need to do that in JS, as there is no access to the same JS  data structures from multiple threads. If you do need locking, there’s the [`Atomics.wait() / Atomics.notify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics#Wait_and_notify) API that does provide “real” locking abilities.

**Comment by gireeshpunathil** [comment]
closing as answered

**Comment by amrendra007** [comment]
fghjkl

**Comment by amrendra007** [comment]
How to create threads pool using wokrer_threads ?
