### ISSUE TITLE
About Promise & process.nextTick

### ISSUE THREAD

**Issue by xysDavid** [nodejs/help#1789]
* **Version**: v10.10.0
* **Platform**: macOS Mojave 10.14.1 
* **Subsystem**:

Why dose the code outputs 123564? But not 123456?
I suppose that `process.nextTick` would run with a higher priority than `Promise`.

```
process.nextTick(() => console.log(1));
Promise.resolve().then(() => console.log(2));
Promise.resolve().then(() => {
    console.log(3);
    process.nextTick(() => console.log(4));
    Promise.resolve().then(() => console.log(5));
}).then(() => {
    console.log(6);
})
```

**Comment by ORESoftware** [comment]
Yes there is a microtask queue and macrotask queue in V8...but beyond that I don't know.

**Comment by Hakerh400** [comment]
I think that's the effect of *deduplication*. From the documentation:

*Because of deduplication, the event loop does not transition back to the C/C++ layer to check if there are items in the nextTickQueue immediately. It instead continues to process any remaining events.*

Example which better demonstrates it:

```js
const f = () => {
  process.nextTick(() => console.log(1));
  Promise.resolve().then(() => console.log(2));
};
f();
Promise.resolve().then(f);
```

It outputs `1221`. The second time `f` is called from a promise and as long as there are ready promises no `nextTick` events will be processed. Another example:

```js
const f = g => Promise.resolve().then(g);
const g = () => f(g);
f(() => {
  process.nextTick(() => console.log(1));
  g();
});
```

It will never print `1`, despite the fact that promise returned control to the event loop.

**Comment by onkarjanwa** [comment]
When we run the code:

1 callback in `process.nextTick` is added to `process.nextTick queue`.
2 callback in `promises` are added to `promises microtask queue`.

Event loop executes tasks in following order: `process.nextTick queue`, `promises microtask queue`, `setTimeout queue`, `setImmediate queue`

1. Event loop will execute callback from `process.nextTick queue` and prints `1`.
2. Event loop will look for `promises microtask queue `and then processes them. So it prints 2 and 3. On the next line it again adds a callback to `process.nextTick queue` which will be executed once `promises microtask queue` is finished.
So the next 5 and 6 will be printed. Now `promises microtask queue` is empty
3. Event loop will again check if there is any handler in `process.nextTick queue` and will execute them. So it now prints 4.

**Comment by xysDavid** [comment]
@Hakerh400 @onkarjanwa Oh I get it. Thanks!

**Comment by Eugene-M-Code-Care** [comment]
> When we run the code:
> 
> 1. callback in `process.nextTick` is added to `process.nextTick queue`.
> 2. callback in `promises` are added to `promises microtask queue`.
> 
> Event loop executes tasks in following order: `process.nextTick queue`, `promises microtask queue`, `setTimeout queue`, `setImmediate queue`
> 
> 1. Event loop will execute callback from `process.nextTick queue` and prints `1`.
> 2. Event loop will look for `promises microtask queue `and then processes them. So it prints 2 and 3. On the next line it again adds a callback to `process.nextTick queue` which will be executed once `promises microtask queue` is finished.
> 3. So the next 5 and 6 will be printed. Now `promises microtask queue` is empty
> 4. Event loop will again check if there is any handler in `process.nextTick queue` and will execute them. So it now prints 4.

OMG, man, that's exactly what I was looking like!

**Comment by gowthm** [comment]
process.nextTick() is not technically part of the event loop. Instead, the nextTickQueue will be processed after the current operation is completed, regardless of the current phase of the event loop.

after complete --> 1,2,(3, --> is current task for),5,6,4

#Reference
https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#understanding-process-nexttick.

**Comment by donaldshen** [comment]
> Understanding `setImmediate()`

https://blog.insiderattack.net/new-changes-to-timers-and-microtasks-from-node-v11-0-0-and-above-68d112743eb3

nodejs change this behavior since v11. Before it node ran microtask queue between each phase in event loop; since v11 and above node will also flush microtask queue between each task in timer phase

**Comment by ishwar00** [comment]
Hey @tk-425, I get the same output as you mentioned. Any updates?
