### ISSUE TITLE
Http sever: unfinished upgrade event is blocking other upgrade events

### ISSUE THREAD

**Issue by oldrich-s** [nodejs/help#1793]
* **Node.js Version**: node-v11.10.0-x64.msi
* **OS**: Win64
* **Scope (install, code, runtime, meta, other?)**: Runtime
* **Module (and version) (if relevant)**: HTTP

This server code:

```
const http = require("http");

const srv = http.createServer(function(req, res) {
    console.log('req-open', req.url);
    setTimeout(() => {
        console.log('req-close', req.url);
        res.end()
    }, 5000)
});

srv.on("upgrade", (req, socket, head) => {
    console.log('ws-open', req.url);
    setTimeout(() => {
        console.log('ws-close', req.url);
        socket.end()
    }, 5000)
});

srv.listen(80, "127.0.0.1");
```

and this client code:

```
<!doctype html>
    <head></head>
    <body>
        <script>
            for (var i = 0; i < 3; i++) fetch('http://127.0.0.1')
            for (var i = 0; i < 3; i++) new WebSocket('ws://127.0.0.1')
        </script>
    </body>
</html>
```

produces this output:

```
> node  server.js
ws-open /
req-open /
req-open /
req-open /
ws-close /
req-close /
req-close /
req-close /
ws-open /
ws-close /
ws-open /
ws-close /
```

It can be seen that ordinary HTTP requests `req-open` are opened all in once and after 5 seconds they all close at once.

Websockets upgrade events `ws-open` on the other hand open sequentially, only after the previous upgrade event is closed.

Is that a feature / architectural decision or is it a bug?

Is there any documentation / description that would explain the blocking behaviour of the upgrade events?

**Comment by bnoordhuis** [comment]
> Is that a feature / architectural decision or is it a bug?

Neither - or the former, but in your browser; you're hitting the per-host connection limit.

**Comment by oldrich-s** [comment]
Thanks, interesting that chrome only allows one upgrade request at a time. Wonder if there is a flag that removes that limit...

**Comment by gireeshpunathil** [comment]
answered, closing. let me know if there is anything outstanding here
