### ISSUE TITLE
how to create a directory of files?]

### ISSUE THREAD

**Issue by mdmasumbillah** [nodejs/help#1796]
![screenshot 2019-02-26 at 14 00 42](https://user-images.githubusercontent.com/17563505/53397004-24822300-39d0-11e9-919d-3df97e636888.png)

**Comment by mdmasumbillah** [comment]
@bnoordhuis  thanks for reply. Actually my app is implement by node js with graphql, express and sequlize. I'm not understand how to implement a base url. I want to use a common folder. 

not:  import userResolvers from './../users/index.js';  etc
want to:   import userResolvers from 'src/resolvers/index.js ';

**Comment by ORESoftware** [comment]
@mdmasumbillah you don't want to do that. If you eventually use TypeScript you will want the complete path (static not dynamic path).

**Comment by mdmasumbillah** [comment]
@ORESoftware thanks your advise.

**Comment by gireeshpunathil** [comment]
answered, closing
