### ISSUE TITLE
Any solutions for synchronous ReadStream and synchronous WriteStream with Await/async  examples?

### ISSUE THREAD

**Issue by systemaker** [nodejs/help#1798]
Looking for examples or alternatives in synchronous ReadStream and synchronous WriteStream  with Await/async operations
(Still need it in some use cases like working with third-party dependencies )

**Comment by aymen94** [comment]
Hello @systemaker, On this article you will find `readStream ` with Await/async.
[Link here](http://2ality.com/2018/04/async-iter-nodejs.html)

**Comment by systemaker** [comment]
@aymen94 
Cool !  thanks i will try that.
