### ISSUE TITLE
Timeframe for when ES7 async await is available in a node release?

### ISSUE THREAD

**Issue by kirkouimet** [nodejs/help#18]
Just curious to hear best guesses about how far out this is - 1 year, 2 years, 3 years, etc.? Is this actually more of a v8 question than a node question?

**Comment by Trott** [comment]
Yes, this is a v8 question. The short answer is: "Not too long after it is in v8."

**Comment by mikeal** [comment]
It's still highly experimental, the *earliest* the spec will be ratified is for ES2016 and some time after that you might see it in v8. However, you can use it pretty effectively today with compilers and see if it's a good idea for yourself :) the spec needs some practical experience injected into it :)

**Comment by Fishrock123** [comment]
If you mean  "when will it work with core APIs?" the answer you should keep in mind unless otherwise stated is "maybe never".

See https://github.com/nodejs/node/issues/11

**Comment by kirkouimet** [comment]
I should note that async/await is in Chrome 52

**Comment by lordKnighton** [comment]
@kirkouimet feel free to reopen, if you wish to continue this convo.

**Comment by eliranmal** [comment]
async/await is available in node.js version 7.x with the `--harmony_async_await` flag.

**Comment by kirkouimet** [comment]
Thanks @eliranmal ! Love that it is available now
