### ISSUE TITLE
fs.createReadStream has issues with MAC 

### ISSUE THREAD

**Issue by itsaakashpatel** [nodejs/help#1801]
## What are you doing?

```js
fs.createReadStream(path.join(__dirname, '../Files/Country.csv'))
    .pipe(csv(['id', 'country', 'is_active']))
    .on('data', (row) => {
        console.log(row);
        results.push(row)
    })
    .on('end', () => {
        console.log('CSV file successfully processed');
    });
```

## What do you expect to happen?
_I want to read each row and push it to results array._

## What is actually happening?
```js
3,US Land,1
     ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
```
**Note :** _This code is working fine with windows and linux as I tested, but, It's not working in MAC._

* **8.11.4**:
* **MAC OS X EI Caption 10.11.6**:

**Comment by sam-github** [comment]
The data event promises no line-by-line behaviour, please refer to its docs.

I suggest using https://www.npmjs.com/package/byline

**Comment by gireeshpunathil** [comment]
ping @itsaakashpatel

**Comment by gireeshpunathil** [comment]
answered, closing
