### ISSUE TITLE
socket.io-client Issue

### ISSUE THREAD

**Issue by BelkissZroud** [nodejs/help#1804]
So I'm currently getting uuid and rssi from Beacon and send it to the server using socket.io

Actually I get the necessary data : when I test in client side it show 1:undefined(ed6cfa91cbf1) RSSI-50

but when I test in the server side, I get : { mac: undefined, rssi: undefined }

I can not find what's wrong in my code so I hope you guys can help me.

Client Side :

    socket.on('connect', function(device){

    var noble = require('noble');
    var knownDevices = [];

    function discovered (peripheral) {

    var device = {
        name: peripheral.advertisement.localName,
        uuid: peripheral.uuid,
        rssi: peripheral.rssi
    };
    knownDevices.push(device);

    console.log(`${knownDevices.length}:${device.name}(${device.uuid})RSSI${device.rssi}`); 

     //working, it show uuid and rssi

    socket.emit(device.uuid ,device.rssi ); //don't working
    }

Server Side :

       var scanner = io.of('/scanner')

       scanner.on('connection', function(device) {

    let payload = {
        mac: device.uuid,
        rssi: device.rssi
    }
    console.log(payload);

    connection.query("INSERT INTO DataTable values ?", payload,   function(err, rows) {

    })

**Comment by gireeshpunathil** [comment]
#cat server.js 
```js
const server = require('http').createServer();
const io = require('socket.io')(server);
io.on('connection', client => {
  client.on('foo', data => { console.log(data) })
});
server.listen(3000);
```
#cat client.js 
```js
var io = require('socket.io-client');
var s = io.connect('http://localhost:3000');
s.emit('foo', {name: 'devicename', uuid: 1804, rssi: 'RSSI-50'})
```

#node server.js 
```
{ name: 'devicename', uuid: 1804, rssi: 'RSSI-50' }
^C
```

@BelkissZroud - basically you need to emit on a custom event that the other end point should capture on the same event name (in my case it is `foo`)

Hope this helps!

**Comment by gireeshpunathil** [comment]
ping @BelkissZroud - did this help?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to reopen if this is still outstanding
