### ISSUE TITLE
Return always index; Hash of Folder excluded one file; CORS;

### ISSUE THREAD

**Issue by Mlocik97-issues** [nodejs/help#1805]
Hello,

I'm newboy in programming in node.js , I'm so long programming client-side (SPA/PWA), but I tried on server-side only few things in Golang. I have one project, which will be on **Heroku**, it's PWA, and I want to do 3 things:

1. regular URL routing, so I need server-side,.. I need always return index.html if client visit any URL, only if client is asking for specific files, I want return these files (yes, it's for UI-router for using history API fo regular URLs without hashbang). I need return it with correct Mime Type (Content-Type). I was looking on https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework and modify it to my requires. But it doesn't worked well. - THIS IS MOST IMPORTANT
2. I need to allow CORS on my second domain for specific domains. I will transfer only JSONs and XMLs between these domains.
3. I need to calculate hash of one of folder without one file inside this folder, and bind this hash to variable in that excluded file, which will be sent on client.

Can You help me how to do these things?

Thanks and sry for my bad English, I hope You understand.

**Comment by Hakerh400** [comment]
> I need to calculate hash of one of folder without one file inside this folder, and bind this hash to variable in that excluded file, which will be sent on client.

If I understand your question: you have a folder which contains a script and you want to compute hash of the entire folder and insert the hash into the script before sending to the client? This is how you can do it:

```js
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const calcHash = (folder, exclude) => {
  folder = path.normalize(folder);
  exclude = path.normalize(exclude);

  const push = val => bufs.push(Buffer.from(val));
  const esc = val => push(JSON.stringify([val]));
  const entry = (name, type) => esc([name, type]);

  const queue = [folder];
  const bufs = [];

  while(queue.length !== 0){
    const dir = queue.shift();
    const fileNames = fs.readdirSync(dir);

    fileNames.sort((a, b) => (a > b) - (a < b));
    entry(dir, 1);

    for(const name of fileNames){
      const file = path.join(dir, name);
      const stat = fs.statSync(file);

      if(stat.isFile()){
        if(file !== exclude){
          entry(file, 0);
          const data = fs.readFileSync(file);
          esc(data.length);
          push(data);
        }
      }else if(stat.isDirectory()){
        queue.push(file);
      }else{
        entry(file, 2);
      }
    }
  }

  const buf = Buffer.concat(bufs);
  const chash = crypto.createHash('sha256');

  chash.update(buf);
  const hash = chash.digest('hex');

  const script = fs.readFileSync(exclude, 'utf8');
  const modified = script.replace(
    /const hash = null/,
    `const hash = '${hash}'`
  );

  return modified;
};

const folder = path.join(__dirname, 'folder');
const exclude = path.join(folder, 'script.js');

const result = calcHash(folder, exclude);
console.log(result);
```

Suppose you have this structure:

```
server.js
folder
  \---script.js
  \---some-toher-files
```

File `server.js` contains the above code. Content of `script.js` is

```js
const hash = null;
```

When you run `node server.js` it will compute hash of all files inside local directory `folder` except `script.js` and assign the resulting hash to variable `hash` inside `script.js`.

Hope this helps. The rest of your questions are unclear and I'm not sure what exactly you want to do.

**Comment by Mlocik97-issues** [comment]
Thank You so much. it's working perfectly.

**Comment by Mlocik97-issues** [comment]
all solved
