### ISSUE TITLE
Nodejs/Socket.emit not working, data not found

### ISSUE THREAD

**Issue by BelkissZroud** [nodejs/help#1806]
So I'm currently getting uuid and rssi from Beacon and send it to the server using socket.io

Actually I get the necessary data : when I test in client side it show 1:undefined(ed6cfa91cbf1) RSSI-50

but when I test in the server side, I get : { mac: undefined, rssi: undefined }

I can not find what's wrong in my code so I hope you guys can help me.

Client Side :

    socket.on('connect', function(device){

    var noble = require('noble');
    var knownDevices = [];

    function discovered (peripheral) {

    var device = {
        name: peripheral.advertisement.localName,
        uuid: peripheral.uuid,
        rssi: peripheral.rssi
    };
    knownDevices.push(device);

    console.log(`${knownDevices.length}:${device.name}(${device.uuid})RSSI${device.rssi}`); 

     / /working, it show uuid and rssi

    socket.emit(device.uuid ,device.rssi ); //don't working
    }

Server Side :

       var scanner = io.of('/scanner')

       scanner.on('connection', function(device) {

    let payload = {
        mac: device.uuid,
        rssi: device.rssi
    }
    console.log(payload);

    connection.query("INSERT INTO DataTable values ?", payload,   function(err, rows) {

    })

**Comment by gireeshpunathil** [comment]
is this still and issue? If so, I guess couple of things to check would be:
 - identify what is `device` - print the object as is - this will tell us is it actually receiving what the client has sent.
 - check whether `scanner.on('connection' .. ` is the right event for the client data receiver. I am not a specialist on socket.io so don't know.

**Comment by gireeshpunathil** [comment]
ping @BelkissZroud

**Comment by gireeshpunathil** [comment]
inactive, closing
