### ISSUE TITLE
util.types.isAsyncFunction on bound async function

### ISSUE THREAD

**Issue by wreckah** [nodejs/help#1808]
* **Node.js Version**: v11.10.1
* **OS**: Ubuntu 18.04
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: util

Async function is not detected as async after binding:
```js
> a = async () => {}
[AsyncFunction: a]
> util.types.isAsyncFunction(a)
true

> b = a.bind({})
[AsyncFunction: bound a]
> util.types.isAsyncFunction(b)
false
```
Is it correct behavior?

**Comment by devsnek** [comment]
yes this is correct, bind returns an ordinary function.

**Comment by wreckah** [comment]
@devsnek thanks!

But why is bound function displayed as `[AsyncFunction: bound a]`, not as `[Function: bound a]`, and does return Promise object?

**Comment by addaleax** [comment]
@wreckah `Function.prototype.bind` carries over the prototype of the original function:

```js
> class X extends Function {}
undefined
> fun = new X()
[X: anonymous]
> fun.bind({})
[X: bound anonymous]
```

**Comment by wreckah** [comment]
@addaleax thanks!

I understand that bind returns "de jure" an ordinary function. But "de facto" it is still an "async" function (because it returns Promise object) and I need the ability to detect this without calling a bound function. I found an ugly workaround `func.__proto__.constructor.name === 'AsyncFunction'`, but I don't like it :(

**Comment by addaleax** [comment]
@wreckah The thing is, you can’t really detect in advance whether a function is going to return a Promise or not, independently of whether it’s an `AsyncFunction`?

**Comment by Hakerh400** [comment]
Checking for `b.__proto__.constructor.name === 'AsyncFunction'` is deprecated and not reliable.
This allows you to detect whether a function is defined using `async` syntax:

```js
const asyncCtor = (async () => {}).constructor;
const isAsyncFunction = func => func instanceof asyncCtor;

const a = async () => {};
const b = a.bind({});
const c = () => new Promise();

console.log(isAsyncFunction(a)); // true
console.log(isAsyncFunction(b)); // true
console.log(isAsyncFunction(c)); // false
```

You can't predict what be the type of the return value will be. The third example returns a promise, but it's not syntactically async.

Another solution would be to implement your own `bind` method:

```js
Function.prototype.bind = (bind =>
  function(target, ...args){
    return this instanceof (async () => {}).constructor ?
    async (...newArgs) => this.call(target, ...args, ...newArgs) :
    bind.call(this, target, ...args);
  }
)(Function.prototype.bind);

const a = async () => {};
const b = a.bind({});
const c = () => new Promise();

console.log(util.types.isAsyncFunction(a)); // true
console.log(util.types.isAsyncFunction(b)); // true
console.log(util.types.isAsyncFunction(c)); // false
```

Note: modifying `Function.prototype` is bad practice, better define `bind` as local function.

**Comment by wreckah** [comment]
@Hakerh400 thanks a lot! :pray:

**Comment by addaleax** [comment]
Umm, why is `b.__proto__.constructor.name === 'AsyncFunction'` deprecated?

`.__proto__` is discouraged but `Object.getPrototypeOf(b).constructor.name` should do the trick as well.

And it’s more accurate, I would say, because it catches async functions from other realms as well:

```js
> const fn = vm.runInNewContext('async () => {}')
undefined
> fn instanceof ((async () => {}).constructor)
false
> Object.getPrototypeOf(fn).constructor.name
'AsyncFunction'
```

**Comment by wreckah** [comment]
Thanks a lot, you are the best :)

**Comment by Hakerh400** [comment]
@addaleax 

I think the best solution would be:

```js
const isAsyncFunction = f => {
  if(typeof f !== 'function') return false;
  const ps = [f];
  for(let p = f; p = Object.getPrototypeOf(p);) ps.push(p);
  if(ps.length < 3) return false;
  let ctor = ps[ps.length - 2].constructor;
  if(typeof ctor !== 'function') return false;
  ctor = ctor('return (async () => {}).constructor')();
  return f instanceof ctor;
};

[
  async () => {},                             // true
  (async () => {}).bind({}),                  // true
  null,                                       // false
  Object.create(null),                        // false
  {constructor: {name: 'AsyncFunction'}},     // false
  new class AsyncFunction extends Function{}, // false
  vm.runInNewContext(`() => {}`),             // false
  vm.runInNewContext(`async () => {}`),       // true
].forEach(f => console.log(isAsyncFunction(f)));
```

While naively checking for constructor name gives the following result:

```js
true
true
Error
Error
false
true
false
true
```

**Comment by addaleax** [comment]
@Hakerh400 I think that’s the most complete check you could reasonably get, yeah :)

In production, I’d maybe cache the result of `ctor(...)` in a `WeakMap` or something, because compiling that string each time could get somewhat expensive.
