### ISSUE TITLE
Clarification on memory management behavior that amounts to a memory leak.

### ISSUE THREAD

**Issue by danielluc** [nodejs/help#1810]
* **v10.14.2*:
* **Win 10**:

I am reading a portion a large TSV file using the Buffer class. The individual lines of the TSV are then extracted using .slice() and the the line is then .split() again to extract the columnar data.

A single piece of the resulting data (i.e. one cel of the TSV) is then passed back to a method that stores the result (a string) as value in an Object literal. This is being done 10's of thousands of times into an Object I am trying to build in memory.

The issue is that the memory (heapTotal) grows at an alarming rate, 4Mb for about 80 strings, far exceeding what one would expect for the the average string length which is about 15 characters.

My hypothesis is that that string interning is being used, and that because a reference (or index) is being used to point into the original buffer, the memory for the whole buffer is not being released during garbage collection, despite the fact that only a tiny portion of the buffer is being referenced.

What complicated the detection of the issue is that several techniques one might hope would create 'new' strings do not seem to work. newStr = String(oldStr), newStr = oldStr.splice(0), Object.assign and Object destructuring all fail to create new references. We finally figured this out because newStr = oldStr.toLowerCase() worked, obviously with this, the string itself will potentially mutate, so new memory must be allocated and string interning can not be used.

The final solution we found was to use newStr = Buffer.from(oldStr).toString()

Can anyone confirm that the hypothesis is correct?

Does this qualify as a bug? I can rationalize the behavior, but if the point of using string interning is to save memory, it is a complete failure in this example.

**Comment by Hakerh400** [comment]
Probably a duplicate of https://github.com/nodejs/node/issues/25846

**Comment by dv-ds** [comment]
If indeed this is due to V8 string slicing, I would strongly suggest adding a comment here:
https://bugs.chromium.org/p/v8/issues/detail?id=2869

The V8 team has yet to indicate if and when they will provide a solution.
