### ISSUE TITLE
fs.promise readfile is throwing a syntax error in V10

### ISSUE THREAD

**Issue by PedroMalSavis** [nodejs/help#1811]
If you have a question about Node.js that is not a bug report or feature
request, please post it in https://github.com/nodejs/help!

Questions posted to this repository will be closed.

Hi! 
I am experimenting the fs.promise module. I know the fs.promise is a experimental. But during the execution the fileHandle.readFile  it throws an unexpected token '.'.. 
I read the docs it says normal on what should as a readFile do and return a promise. 

node Version: 10
os: linux - ubuntu 
![selection_014](https://user-images.githubusercontent.com/36861114/54004859-31520400-4192-11e9-8e09-7a4cbd3db276.png)

ps: I am not accustom with bugs and i don't know if it is a bug or a question. please delete if needed.. thanks.

**Comment by gireeshpunathil** [comment]
ping @PedroMalSavis

**Comment by gireeshpunathil** [comment]
inactive, closing
