### ISSUE TITLE
How to use native C/C++ library with nodejs

### ISSUE THREAD

**Issue by tbhaxor** [nodejs/help#1813]
* **Node.js Version**: 10.15.1
* **OS**: Arch linux
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**: 

I want to use c/c++ library (in _/usr/lib_ directory)
For example, libncurses, libc

Like in python we use `ctypes`

**Comment by richardlau** [comment]
I think the Node.js equivalent of `ctypes` is https://github.com/node-ffi/node-ffi.

**Comment by devsnek** [comment]
i'd recommend https://github.com/node-ffi-napi/node-ffi-napi

**Comment by tbhaxor** [comment]
Thank you @richardlau @devsnek

**Comment by wanglin86769** [comment]
It seems that node-ffi-napi is not maintained anymore, not updated for two years.

**Comment by wanglin86769** [comment]
Now in 2023, I would recommend koffi package.
https://www.npmjs.com/package/koffi
