### ISSUE TITLE
HTTP Server not sending requests to handler

### ISSUE THREAD

**Issue by mattgogerly** [nodejs/help#1814]
* **Node.js Version**: 8.11.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Running code
* **Module (and version) (if relevant)**: http module

I'm starting a local server within Electron using the Node http module to handle Google's OAuth callback. I can verify that the server is listening on the port specified. However when I click Allow and the tab is redirected to the callback URI, the response handler is never called (verified with a console.log on line one). 

Weirdly if I keep refreshing the page and clicking Allow it does eventually go through. I can also open a new tab and go to 127.0.0.1:18363 and get the error response as expected. I'm therefore stumped as to why the first few requests seemingly just disappear.

For reference the callback URI is 127.0.0.1:18363, and LOCAL_SERVER_PORT is also 18363.

```ts
this.server = http.createServer((request, response) => {
      console.log("triggered"); // this isn't called
      const { query } = url.parse(request.url, true);
      if (query.code) {
        this.onCodeReceived(query.code);
        // do something nicer here eventually
        response.end();
      } else {
        response.end('Error');
        this.authStatus = 'error';
      }
    }).listen(this.LOCAL_SERVER_PORT);
```

Thanks all!

**Comment by gireeshpunathil** [comment]
@mattgogerly - after you setup the server and before you issue a request from the client, can you issue 

`netstat -na | grep 18363`

from a terminal and see what it shows?

**Comment by gireeshpunathil** [comment]
ping @mattgogerly

**Comment by gireeshpunathil** [comment]
inactive, closing
