### ISSUE TITLE
HTTPS Server is not responding with data

### ISSUE THREAD

**Issue by dldereklee** [nodejs/help#1815]
* **Node.js Version**: v11.10.1
* **OS**: Red Hat Enterprise Linux Server 7.6 (Maipo)
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: https

Hi there,

I'm having a weird issue where I am trying to start an Express application and serve it over HTTPS using the https module, but I am getting no data from the HTTPS server at the port specified. The code I have to start up the HTTP and HTTPS servers is below:
```
#!/usr/bin/env node

/**
 * Module dependencies.
 */

// var app = require('../app');
var app = function (req, res) { res.end('hello!') };
var debug = require('debug')('robotapp:server');
var http = require('http');
var fs = require('fs');
var https = require('https');

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '8000');
// app.set('port', port);
console.log('Listening on localhost:', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Add HTTPS server if production
 */

    https
        .createServer(
            {
                key: fs.readFileSync('sslcerts/server.key', 'utf8'),
                cert: fs.readFileSync('sslcerts/server.pem', 'utf8')
            },
            app
        )
        .listen(8443, function() {
            console.log('HTTPS listening on PORT 8443');
        });

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
	var port = parseInt(val, 10);

	if (isNaN(port)) {
		// named pipe
		return val;
	}

	if (port >= 0) {
		// port number
		return port;
	}

	return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
	if (error.syscall !== 'listen') {
		throw error;
	}

	var bind = typeof port === 'string' ? 'Pipe ' + port : 'Port ' + port;

	// handle specific listen errors with friendly messages
	switch (error.code) {
		case 'EACCES':
			console.error(bind + ' requires elevated privileges');
			process.exit(1);
			break;
		case 'EADDRINUSE':
			console.error(bind + ' is already in use');
			process.exit(1);
			break;
		default:
			throw error;
	}
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
	var addr = server.address();
	var bind = typeof addr === 'string' ? 'pipe ' + addr : 'port ' + addr.port;
	debug('Listening on ' + bind);
}
```
To rule out if Express was causing an issue, I substituted my Express app var with a simple function (per recommendation from the Express issue tracker board). I have an ongoing issue on their board as well at https://github.com/expressjs/express/issues/3906
```
// var app = require('../app');
var app = function (req, res) { res.end('hello!') };
```
When I start up the app, I see the following which I says that both servers successfully started
```
Listening on localhost: 8000
HTTPS listening on PORT 8443
```
Now when I navigate to port 8000, I see the hello! message that I expect to see. However, when I go to port 8443, I get no data sent from the server.

Is there any reason why the HTTPS server would successfully start, but no data would be sent? I also tried substituting out my certificates for self-signed ones instead of the ones given to me by my workplace and I still get the same behavior.

**Comment by wrightkhlebisol** [comment]
@dldereklee were you able to fix this issue, seeing that you closed it. If yes, can you kindly explain what you did to solve the issue? Thanks

**Comment by DaviMoreira27** [comment]
As explained in this [discussion](https://github.com/expressjs/express/issues/3906). He was using http:// instead of https://
