### ISSUE TITLE
Node Not sending/handling Events in each minute from each hour

### ISSUE THREAD

**Issue by z3ro** [nodejs/help#1816]
Hello,
we are working with node for a while, and we fall into a bug from the start of our project.
we have calling system with live events comes from our PBX system,
we noticed that in minute 3-4 from each hour node or node modules is stuck or crash or reload (really cant know where is the issue) and not hanging up the calls and the call keep sucked in our system.
all other times of the day calls works fine but when we reach this time between minute 3-4 from each hour this happened all the time.

any one have notice any thing like this, our is there any scheduled processes runs from node in each hour can make this issue ?

**Comment by z3ro** [comment]
Using Modules,
axios, asterisk-ami-client, socket.io
events,  http

OS: linux 
PM2: v3.2.4
Node: v10.15.0

**Comment by shellberg** [comment]
@z3ro : Your problem sounds very specific in the context of the Asterisk PBX system.  You might well try and find some assistance in the context of the 'asterisk-ami-client', or another of the 'asterisk-' npm projects, or at the main Asterisk project itself.  Its also very unclear whether the 'asterisk-ami-test-server' would be sufficient as a minimally mocked system to try and help you.

Nevertheless, the answer for your final question is that Node.js doesn't have any default jobs/workload that would occur at hourly intervals or 'on-the-hour'.  Nor does it appear that the asterisk-ami-client has a scheduler interface either; although you might consider whether you can 'ping' (through the client) your Asterisk PBX instance in these 3-4 min intervals just-after-the-hour, and you should review logs on both Asterisk server and client sides for any messages/errors, or any insight at these times.

Good luck!

**Comment by gireeshpunathil** [comment]
answered, closing. pls reopen if there is anything outstanding
