### ISSUE TITLE
Question: what would happens on buffer level when an input stream piping to multi output stream?

### ISSUE THREAD

**Issue by gonejack** [nodejs/help#1819]
```js
const input = fs.createReadStream('img.jpg');
const target1 = input.pipe(fs.createReadStream('target1.jpg'));
const target2 = input.pipe(fs.createReadStream('target2.jpg'));
```
-->
Hi, I'm reading stream document and looking for buffering behavior description about streams, and https://nodejs.org/api/stream.html#stream_buffering seems not mentioning about what would happen to inputstream buffer(or buffers?) when piping to multiple outputs as different output have different consuming speeds?

**Comment by gireeshpunathil** [comment]
@gonejack - 
1. I guess you meant `createOutStream` for target1 and target2?
2. when an input is piped to multiple outputs of differing velocities, I guess it will `slow down` to match the slower consumer. However, I haven't tested or verified if this is true.

**Comment by gireeshpunathil** [comment]
ping @gonejack

**Comment by gonejack** [comment]
@gireeshpunathil Yes you are right .it will `slow down`.

I bring up the same question on stackoverflow and get the same answer weeks ago, Thank you.
