### ISSUE TITLE
how to use "a+"  when using fs.writeFile()

### ISSUE THREAD

**Issue by hwbeauty** [nodejs/help#182]
fs.writeFile("host.txt","12324356",['utf-8','0o66','a+'],function(err){
	
		if(err) {  console.log("write error");}
	});
but the contents of the file “host.txt”  are overwritten  rather than appended

**Comment by bnoordhuis** [comment]
The `options` argument should be a dictionary, not an array.  Try passing `{ flag: 'a+' }`, the other values are the defaults.

You could use `fs.appendFile()` instead of `fs.writeFile()` as well.

**Comment by hwbeauty** [comment]
thank u，ur answer is very useful

**Comment by saadq** [comment]
Hey @hwbeauty, do you have any other questions about this? If not, feel free to close this issue.

**Comment by alex-deb** [comment]
> You could use `fs.appendFile()` instead of `fs.writeFile()` as well.
Why we should use `fs.appendFile()` instead of `fs.writeFile({flag: 'a'})`? That methods have same function. Even if file does not exist, they both of methods creating a new one.
