### ISSUE TITLE
WebDriverError: Failed to interpret value as array

### ISSUE THREAD

**Issue by Ch84** [nodejs/help#1821]
See attached image for more details:

![webdriverBugArrayInterpretError](https://user-images.githubusercontent.com/33604841/54223518-f6383380-44f7-11e9-9804-92c809dfbfed.JPG)

**Comment by Ch84** [comment]
Whats the status on this one?

**Comment by gireeshpunathil** [comment]
@Ch84 - does not look like a Node.js issue on the face of it; but can you provide discrete steps to reproduce? so that I can produce the error myself and debug?

**Comment by Ch84** [comment]
Since this was a while ago I had to re run the file to see at which step it fails. Though it will not run to the end barely, stops in the beginning most of the time right after it has given input to the google txt search field. Therefore can't reproduce. Closing this thread since I have moved on to running mocha tests nowadays. I thank you for the response anyway.
