### ISSUE TITLE
Error: write after end issue. Nodejs Server

### ISSUE THREAD

**Issue by zankhanarana9** [nodejs/help#1822]
* **Node.js Version**: 10.15.3
* **OS**: windows 2012 R2
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

I have the following directory structure - 

C drive
  -test
        - app
         -node_modules
        - test_1
             -new.txt
             -new1.txt
             -new2.txt
             -new3.txt
         -package.json
         -package-lock.json
         -server.js

I am trying to implement a file server which gets the directory structure (files and directories within it); Logic: Return response status 404 if the searching URL points to a directory or return the contents of the file if the file exists.

package.json looks something like this

{
  "name": "fileserver",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "dependencies": {
    "cpx": "^1.5.0",
    "directory-tree": "^2.2.1",
    "express": "^4.16.4",
    "serve": "^10.1.2",
    "serve-handler": "^5.0.8"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Zankhana Rana",
  "license": "ISC"
}

Here is the server.js code:

var handler = require('serve-handler');
var path = require('path');
var http =  require('http');
var cpx= require("cpx");
var fs = require('fs');
var express = require("express");
var app = express();
var rootDir = "C:/test";
const dirTree = require("directory-tree");

function findFile(arr, name) {
  const { length } = arr;
  const id = length + 1;
  const found = arr.some(el =>  {

  	return el.name === name && el.type === 'file'
  });
  console.log(found)
 return found;
}

function preprocess(req,res)  {
	let body = ' ';
	req.on('data', function(chunk) {
		body += chunk
	});

	req.on('end', function() {
		req.body =body;
		// console.log(body);
		server(req,res);
	})
}

function serverResponse(req,res) {
	var serverRes;

	switch(req.url) {
		case '/initialize': //move ISIR files 

			//delete the files and copy ISIRs
			fs.readdir("C:/test/app", (err, files) => {
			  if (err) throw err;

			  for (const file of files) {
			    fs.unlink(path.join("C:/test/app", file), err => {
			      if (err) throw err;
			    });
			  }
			});

			//Copy the files from sourc folder
			cpx.copy( "C:/test/test_1/**/*.*", "C:/test/app", {},function() { console.log("File Copied") });
			serverRes = {"message" : "Files Copied"}
			break;

		case '/files':
			try {
				var data = JSON.parse(req.body);
				serverRes = { "fileName" : data["fileName"], "result": 'success'}
				console.log(serverRes);
			} catch(e) {
				return 'malformed request';
			}
			break;

		default: 
			dir = rootDir + req.url.slice(req.url.indexOf('/'),req.url.lastIndexOf('/'));
			var tree = dirTree(dir);
			let request = "";
			let found = false;
			if(tree) {
				request = req.url.slice(req.url.lastIndexOf('/')).replace(new RegExp("/","g"), "");
				found = findFile(tree.children,request)
			}
			
			if(found) {
				return handler(req,res);
			}else {
				res.writeHead(404, {"Content-Type": "text/plain"});
	  			res.write("404 Not Found\n");
	  			res.end();
			} 
			break;
	}

	return serverRes
}

function server(req,res) {

	const payload = serverResponse(req,res)
	res.end(JSON.stringify(payload));
}

http.createServer(preprocess).listen(3000);

When I start the server and navigate to http://localhost:3000/test_1, the response is 404 Not found (as expected, because test_1 is a directory)

On navigating to http://localhost:3000/test_1/new.txt, sometimes returns the contents of the file; the other times the response is { } (plain text) and I see following error on command prompt- 

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:572:17)
    at ServerResponse.write (_http_outgoing.js:567:10)
    at ReadStream.ondata (_stream_readable.js:689:20)
    at ReadStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ReadStream.Readable.push (_stream_readable.js:220:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:462:17)
Emitted 'error' event at:
    at ServerResponse.onerror (_stream_readable.js:713:12)
    at ServerResponse.emit (events.js:189:13)
    at writeAfterEndNT (_http_outgoing.js:634:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I am trying to implement the same server on another folder where always when I try to read the contents of the file, I see the error above.

I updated the node version to be the latest. And tried a couple of solutions to get it to work but I still get the same error. 

Can anyone tell me what am I doing wrong? Is there any code error or if the folder properties are likely to cause this issue

**Comment by calebc01** [comment]
Did you find a solution for this?  I'm having the exact issue.

**Comment by marsonya** [comment]
Kindly take a look at [issue #8635](https://github.com/nodejs/node/issues/8635) in the node repository. There is detailed discussion on this problem. Hope this helps.

I am closing this issue now. You can always reopen it incase there is something more to add to it.

**Comment by marsonya** [comment]
Sorry for closing it. It was my mistake. Reopening it again.
