### ISSUE TITLE
behavior from reading chunk size that is greater than highWaterMark

### ISSUE THREAD

**Issue by PacoHuerta** [nodejs/help#1823]
v10.8.0
Windows 10 x64

Can someone please tell me what the expected behavior is when we read a chunk size that is greater than the highWaterMark?

When executing the following: 

```
const fs = require('fs');
const rr = fs.createReadStream('foo.txt', {highWaterMark: 10});
rr.setEncoding('utf-8');
rr.on('readable', () => {
    console.log('readable event received');
    console.log('read 1:', rr.read(11));
});

rr.on('end', () => {
  console.log('end');
});
```

Where foo.txt contains (on Windows, so has carriage return):

```
12345678
abcdefgh
ijklmnop
qrstuvwx
12345678
abcdefgh
ijklmnop
qrstuvwx
```

I get the following output:

```
readable event received 1
read 1: null
readable event received 2
read 1: 12345678
a
readable event received 2
read 1: bcdefgh
ij
```

I'm sure the first read there is null because we are attempting to read more than what is available (11 > 10); however, I don't know why the program stops there. If I change the 'readable' callback to have the following two reads as opposed to the original read, the file is printed out completely:

```
...
    console.log('readable event received');
    console.log('read 1:', rr.read(6));
    console.log('read 2:', rr.read(5));
...
```
Output:
```
readable event received
read 1: 123456
read 2: null
readable event received
read 1: 78
ab
read 2: cdefg
readable event received
read 1: h
ijk
read 2: lmnop
readable event received
read 1:
qrst
read 2: uvwx
readable event received
read 1:
12345
read 2: 678

readable event received
read 1: abcdef
read 2: null
readable event received
read 1: gh
ij
read 2: klmno
readable event received
read 1: p
qrs
read 2: tuvwx
readable event received
read 1: null
read 2: null
readable event received
read 1:


read 2: null
end
```
Again, the first "read 2" line here is probably null because we want 5 bytes but only 4 are available. I don't understand why only a bit of the file is read when the chunk size is greater than the highWaterMark. Why is this the case? Are we not depleting the internal buffer on each readable event in both of the above cases? Apologies for the massive post.

**Comment by PacoHuerta** [comment]
Added a log of the readableLength property, and I believe I see why we do not see the entire file when reading 11 bytes at a time but do see the entire file being printed when reading 6 bytes first and then 5 bytes right after.

When reading 11 bytes at a time, the output is:
```
readable event received
readable length: 10
read 1: null
readable length: 10
readable event received
readable length: 26
read 1: 12345678
a
readable length: 15
readable event received
readable length: 31
read 1: bcdefgh
ij
readable length: 20
```
In the beginning, 11 bytes were requested but only 10 were available. Bytes were requested in the amount of the next power of 2 above 11, which is 16. This brings us to 26 bytes available and the readable event triggering. We take 11 from the 26, which leaves us at 15. At this point, 15 is still above the highWaterMark, which is 10. The interesting thing here is that it decided to pull in another 16 bytes and take us to 31 bytes available, even though 15 > highWaterMark.

When reading 6 bytes first and then 5 bytes afterward, the output is:
```
readable event received
readable length: 10
read 1: 123456
readable length: 4
read 2: null
readable length: 4
readable event received
readable length: 14
read 1: 78
ab
readable length: 8
read 2: cdefg
readable length: 3
readable event received
readable length: 13
read 1: h
ijk
readable length: 7
read 2: lmnop
readable length: 2
readable event received
readable length: 12
read 1:
qrst
readable length: 6
read 2: uvwx
readable length: 1
readable event received
readable length: 11
read 1:
12345
readable length: 5
read 2: 678

readable length: 0
readable event received
readable length: 10
read 1: abcdef
readable length: 4
read 2: null
readable length: 4
readable event received
readable length: 14
read 1: gh
ij
readable length: 8
read 2: klmno
readable length: 3
readable event received
readable length: 13
read 1: p
qrs
readable length: 7
read 2: tuvwx
readable length: 2
readable event received
readable length: 4
read 1: null
readable length: 4
read 2: null
readable length: 4
readable event received
readable length: 4
read 1:


readable length: 0
read 2: null
readable length: 0
end
```
Each time the readable event is handled, the readableLength falls below the highWaterMark threshold of 10 and is then refilled either to 10 or above 10. Falling below the highWaterMark threshold and then refilling up to or above the threshold seems to explain why we get the readable event enough times to read the entire file.

**Comment by gireeshpunathil** [comment]
@PacoHuerta -  is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
