### ISSUE TITLE
issue while installing the http server

### ISSUE THREAD

**Issue by phanindraj** [nodejs/help#1824]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'http-server',
1 verbose cli   '-g' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose npm-session b926483e7351902f
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for http-server@latest request to https://registry.npmjs.org/http-server failed, reason: connect ETIMEDOUT 104.16.24.35:443
8 timing stage:rollbackFailedOptional Completed in 3ms
9 timing stage:runTopLevelLifecycles Completed in 134175ms
10 verbose type system
11 verbose stack FetchError: request to https://registry.npmjs.org/http-server failed, reason: connect ETIMEDOUT 104.16.24.35:443
11 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:189:13)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:392:9)
11 verbose stack     at TLSSocket.emit (events.js:189:13)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:82:8)
11 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
12 verbose cwd Y:\
13 verbose Windows_NT 6.1.7601
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "http-server" "-g"
15 verbose node v10.15.3
16 verbose npm  v6.4.1
17 error code ETIMEDOUT
18 error errno ETIMEDOUT
19 error network request to https://registry.npmjs.org/http-server failed, reason: connect ETIMEDOUT 104.16.24.35:443
20 error network This is a problem related to network connectivity.
20 error network In most cases you are behind a proxy or have bad network settings.
20 error network
20 error network If you are behind a proxy, please make sure that the
20 error network 'proxy' config is set properly.  See: 'npm help config'
21 verbose exit [ 1, true ]

**Comment by yathamravali** [comment]
@phanindraj
I’m not sure but I think your internet connection is causing this issue. Maybe you are behind a proxy or a firewall that is causing the requests to timeout?

try `rm -rf node_modules`
`npm install`

To install behind a proxy server try:
`npm config set http-proxy http://username:password@ip:port`
`npm config set https-proxy http://username:password@ip:port`

[your username and password for the corporate proxy server, it’s IP address and port number]

If HTTP_PROXY is set in your environment and NPM read it from there.Then try this
`npm config set proxy http://proxy.address:proxy.port`
`npm set strict-ssl false`

**Comment by gireeshpunathil** [comment]
ping @phanindraj

**Comment by gireeshpunathil** [comment]
inactive, closing
