### ISSUE TITLE
Get a 409 conflict issue

### ISSUE THREAD

**Issue by shaliniranga** [nodejs/help#1829]
* **Node.js Version**: v10.15.3
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: all modules

I get below error, I am on corporate network with proxy enabled. I did set the proxy. On installing i get below error.

I am new to node and hence struggling. Please help.

PS C:\Users\Shalini.Ranga\Documents\nodejs_training\node-app> npm install chalk --timing
npm http fetch GET 409 https://registry.npmjs.org/chalk 42ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 306ms
npm ERR! code E409
npm ERR! 409 Conflict: chalk@latest

**Comment by shaliniranga** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'chalk',
1 verbose cli   '--timing' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose npm-session 5aa753c5ef74501d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 409 https://registry.npmjs.org/chalk 42ms
8 silly fetchPackageMetaData error for chalk@latest 409 Conflict: chalk@latest
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 306ms
11 verbose stack Error: 409 Conflict: chalk@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd C:\Users\Shalini.Ranga\Documents\nodejs_training\node-app
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "chalk" "--timing"
15 verbose node v10.15.3
16 verbose npm  v6.4.1
17 error code E409
18 error 409 Conflict: chalk@latest
19 verbose exit [ 1, true ]

**Comment by gireeshpunathil** [comment]
@shaliniranga - is this still an issue?

**Comment by JSalazar88** [comment]
> @shaliniranga - is this still an issue?

I also saw this error today when running `npm install @angular/cli@7.3.9`

**Comment by theCreatorAniket** [comment]
> > @shaliniranga - is this still an issue?
> 
> I also saw this error today when running `npm install @angular/cli@7.3.9`: `npm ERR! 409 Conflict - GET https://registry.npmjs.org/pacote`.
> 
> And when re-attempting the same, got: `npm ERR! 409 Conflict - GET https://registry.npmjs.org/css-select/-/css-select-1.2.0.tgz`

Hi! Were You able to solve the issue? I am getting similar error while installing a package. Kindly if you can help me.

**Comment by preveen-stack** [comment]
@shaliniranga @theCreatorAniket Are we still having this issue 

Ref https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409
