### ISSUE TITLE
Not able to hit breakpoints in vscode

### ISSUE THREAD

**Issue by suraj1249** [nodejs/help#1830]
Version:11.10.0
OS:Ubuntu
Scope:Debugging testcases
Module: Zest Test Framework
IDE:VSCode

I'm trying to debug my test cases. All breakpoints in spec.ts file works. but breakpoints in src/folders, ie, controller files never works. VSCode shows them as a unverified breakpoints.

launch.json:
 {
        "type": "node",
        "request": "launch",
        "name": "Jest Tests",
        "program": "${workspaceRoot}/node_modules/jest/bin/jest.js",
        "args": ["--runInBand","-i", "--config=${workspaceFolder}/jest.config.js"],
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen",
        "outFiles": [
            "${workspaceRoot}/dist/**/*"
        ],
        "envFile": "${workspaceRoot}/.env"
    }

**Comment by aymen94** [comment]
@suraj1249 The configuration you have set Work only in test case because you set  `jest ` for debugging:
Change `program `  in `launch.json`:
```
    "program": "${workspaceFolder}/server.js",
```
where `server.js ` is your entry point.
To learn more, I suggest you take a look at the[ official guide](https://code.visualstudio.com/docs/editor/debugging).

**Comment by suraj1249** [comment]
@aymen94  In that case I won't be able to debug my test cases.

**Comment by aymen94** [comment]
@suraj1249 Ok.
Example:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Server",
            "program": "${workspaceFolder}/server.js",
            "cwd": "${workspaceFolder}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Client",
            "program": "${workspaceFolder}/client.js",
            "cwd": "${workspaceFolder}"
        }
    ],
    "compounds": [
        {
            "name": "Server/Client",
            "configurations": ["Server", "Client"]
        }
    ]
}
```
For More info [Doc](https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations).

**Comment by gireeshpunathil** [comment]
ping @suraj1249 - is this resolved?

**Comment by gireeshpunathil** [comment]
answered, closing
