### ISSUE TITLE
npm run sass rendering to wrong c:\user 

### ISSUE THREAD

**Issue by whiterain** [nodejs/help#1831]
* **Node.js Version**:Both...
* **OS**:windows10 home
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

learning web design. performing a simple exercise, rendering a css color change
background red to blue. The rendering is wrong and writes css to wrong 
C:\user file.
![Annotation 2019-03-11 224131](https://user-images.githubusercontent.com/7719364/54484836-468afa80-4844-11e9-89a8-15500fdbd272.png)

look at the red comment lines at bottom instead of c:\users\aries
the output is trying to go to c:\users\arble
which doesnt exist.
I'm using visual studio code editor.

**Comment by aymen94** [comment]
I had the same problem with node-sass.
Install globally : `npm install -g node-sass`

**Comment by whiterain** [comment]
aymen I have again uninstalled the ext from VScode edittor . but... I just noticed N email from the Creator Retwick Dey. Asking what is the issue i'm having . so Im going to reinstall it and see if I can make it happen again.

**Comment by aymen94** [comment]
@whiterain Ok, Good luck!!!

**Comment by whiterain** [comment]
I have Live Sass Compiler installed , I have an index.html file 
I just notice The Ext. is not running no "watch Sass" icon on task bar of VSc editor. and yes the extension is listed as installed.
I hit F1 typed   liveSass:watch my Sass    and got this error
command 'liveSass.command.watchMySass' not found

**Comment by gireeshpunathil** [comment]
@whiterain - is this resolved?

**Comment by gireeshpunathil** [comment]
answered, closing
