### ISSUE TITLE
Iterate over WeakSet

### ISSUE THREAD

**Issue by ghost** [nodejs/help#1832]
* **Node.js Version**: 11.x
* **OS**: all
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: /

Hello,
We want to ask: is there any way to iterate over values added to WeakSet/WeakMap or at least get its size?

This is our use case: we want to limit a script to use at most thousand alive instances of a class. That means: the script can instantiate any number of our class instances, but garbage collector will clean up unused references. However, if script tries to store all previously instantiated references and exceeds thousand refs, then we firstly run global.gc and if ref count is still larger than thousand, we want to kill the script.

What we tried: in the class constructor, add `this` into a global WeakSet, then get the size of the weakset and perform the beforementioned check.

Problem: there is no `size` property on weak set.

---

Another use case: we have a class that lets users redefine some properties. After some period of time (i.e. 10 minutes) we want to delete some specific property on all instances that user instantiated.

Our attempt: in the constructor store all instances in a weak set, then after timeout fires, iterate over weak set and delete the properties we want (or perform any other processing on the instances). The problem is: we want to do it in interval of 10 minutes, and the rate of instantiating objects is high, so using `Set` instead is not an option, as it would eventually cause memory leak.

Problem: weak set is not iterable.

---

We read somewhere that iterating and retrieving size of weak set/map has been reported as a feature request to V8/TC39 team and it was rejected for some reasons that we still don't understand well.

Is there a polyfill for this? According to the fact that `console` is able to display properties of weak set, we assume it can be done from C++ land, but that is not an option, as we want it to work in browsers too.

---

Our idea: define new class `IterableWeakSet` that implements `add` and `delete methods` and internally uses both `Set` and `WeakSet` (method add adds both to set and weak set). Then we periodically iterate over the `Set` and remove from it all elements that are not in `WeakSet`.

Problem: it doesn't work, because no element will be implicitly removed from the weak set as long as it belongs to the `Set`. And we can't keep track of elements if we don't store them in a `Set`.

---

Also one more question: if iterating over weak set is not implemented because there are no use cases that make sense for it (or all use cases can be refactored to use only available properties of weakset without iterating), then can someone explain how these two use cases can be refactored to achieve the goal, but to avoid iterating?
And is there a way to implement a polyfill somehow?

Any help would be greatly appreciated. Thanks.

**Comment by wide4head** [comment]
Don't think so. From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet
`The WeakSet is weak: References to objects in the collection are held weakly. If there is no other reference to an object stored in the WeakSet, they can be garbage collected. That also means that there is no list of current objects stored in the collection. WeakSets are not enumerable.`

**Comment by gireeshpunathil** [comment]
ping @ghost - does the above explanation help you?

**Comment by devsnek** [comment]
ghost is how GitHub shows a deleted user.

**Comment by gireeshpunathil** [comment]
ah! I did not know that, thanks!

**Comment by vilic** [comment]
Maybe combining `Set` and `WeakRef`?

**Comment by whysosergious** [comment]
viic is correct here, I've made a class that holds weakref collection of pointers to weakset/weakmap, did it as an experiment though. I would use caution before using anywhere in prod
