### ISSUE TITLE
npm cant install

### ISSUE THREAD

**Issue by dimput** [nodejs/help#1833]
* **6.9.0**
* **Win 10**

> npm i next --save react react-dom
npm WARN unistore@3.2.1 requires a peer of preact@* but none is installed. You must install peer dependencies yourself.
npm WARN nextjs@1.0.0 No description
npm WARN nextjs@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ next@8.0.3
+ react-dom@16.8.4
+ react@16.8.4
updated 3 packages and audited 7006 packages in 11.699s
found 0 vulnerabilities

**Comment by yathamravali** [comment]
@dimput 
Looks like everything installed prior to warnings. Can u explain what's the exact problem??

**Comment by dimput** [comment]
the problem is after installed, folder is empty.

**Comment by dimput** [comment]
> @dimput
> Looks like everything installed prior to despite of warnings. Can u explain what's the exact problem??
the problem is after installed, folder is empty.
