### ISSUE TITLE
How to handle multiple request on on node/express API.

### ISSUE THREAD

**Issue by naresh101010** [nodejs/help#1835]
Hi all,

I am working on a project, The **project requirement** is to make an API that accepts .docx and return .pdf (base 64) without using LibreOffice.

So I am working in Window invoirement and using [node-msoffice-pdf](https://www.npmjs.com/package/node-msoffice-pdf) **to convert .docx to .pdf**.

Node-msoffice-pdf module **opens Ms-word in the background and then save as pdf**.

If my **API requests one by one then it works fine**, but if my **API requests more then one client simoustanly then my application break,** it shows error word application is busy. 

node-msoffice-pdf open ms-word one by one request and complete task but failed to handle a multipal request it takes some time to close ms-word and if ms-word did not close properly then my next request failed and show "error word application is busy".

**My code file:**
[router.txt](https://github.com/nodejs/help/files/2996634/router.txt)

**Comment by dipakchavda2912** [comment]
Hey,

As I have reviewed your issue when multiple requests come from client or request comes from multiple clients, you should use the queueing mechanism.

With the help of Redis, you should  solve this issue.

Probably following way comes to end your problem.
Step 1: Get the multiple requests from client or multiple requests from multiple clients.
Step 2: Express JS receive request to convert from docx to pdf
Step 3: Now add required metadata (information about conversion) and add in redis queue.
Step 4: Create the seperate which receive tasks from redis queue and process, Until process the current one it will not receive next one from redis.
Step 5: Above process step from 1 to 4 iterates until empty the redis queue.

With this basic idea or flow you should accomplish your task.

**Comment by gireeshpunathil** [comment]
@naresh101010 - is this resolved, by following @dipakchavda2912 's suggestion?

**Comment by gireeshpunathil** [comment]
answered, closing
