### ISSUE TITLE
Data about the typical Windows setup

### ISSUE THREAD

**Issue by ehmicky** [nodejs/help#1836]
Your [2018 report](https://nodejs.org/en/user-survey-report/#Primary-OS-Distro) indicates that 24% of Node.js developers use Windows in development.

This is very valuable information for users [making sure their Node.js code is cross-platform](https://github.com/ehmicky/portable-node-guide). However this largely depends on the Windows setup when running Node.js. Whether a Windows developer uses `cmd.exe`, Powershell, Git Bash, WSL or Cygwin results in different ways to approach code-platform compatibility.  

Do you have some data about the typical Node.js setup for Windows developers?

Thanks!

**Comment by gireeshpunathil** [comment]
@ehmicky - I am not aware of any such data points, may be @nodejs/platform-windows know

**Comment by ehmicky** [comment]
Thanks @gireeshpunathil for your answer. Looking forward to see if @nodejs/platform-windows has some information about this.

**Comment by gireeshpunathil** [comment]
@ehmicky - are you still looking for an answer to this? from the age of the issue, I fear we may not get one!

**Comment by ehmicky** [comment]
Oh that's too bad, that would have been some interesting information :)

I will close this issue, thanks for following up!
