### ISSUE TITLE
Node.js HTTP request socket hangup for any Google Video URL

### ISSUE THREAD

**Issue by jbis9051** [nodejs/help#1837]
https://stackoverflow.com/questions/55326668/node-js-http-request-socket-hangup-for-any-google-video-url

I am having a recurring issue where any Google Video videoplayback URL gets a socket hangup when requested from node.  Whether it is requested from `HTTP`,`HTTPS`, `HEAD` or `GET` nothing works.

If I edit `/etc/hosts` to point the url to `127.0.0.1` I don't get the error. So it's not a problem with the domain it self.

If I change the url to just `https://r6---sn-ab5szn76.googlevideo.com` I also don't get the error. Which leaves me to believe its something with the server, however the request works correctly via `curl`,`python`, and the browser.

    const http = require('http');
    const https = require('https');
    const url_lib = require('url');
    
    let url = "https://r6---sn-ab5szn76.googlevideo.com/videoplayback?test";
    const q = url_lib.parse(url);
    https.request({
        method: 'HEAD',
        path: q.pathname,
        host: q.hostname,
        port: (q.protocol === "http:") ? 80 : 443,
        url: url,
    }, res => {
        console.log(Number(res.headers['content-length'] || "0"));
    }).end();

Error:

    events.js:183
          throw er; // Unhandled 'error' event
          ^
    
    Error: socket hang up
        at createHangUpError (_http_client.js:331:15)
        at TLSSocket.socketOnEnd (_http_client.js:423:23)
        at emitNone (events.js:111:20)
        at TLSSocket.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)
    
    Process finished with exit code 1

**Comment by Hakerh400** [comment]
Replace `url: url` with `path: q.path`

There's no parameter `url` for `https.request` method, so it's ignored. You're trying to access path `/`, for which Chrome also complains about socket error.

**Comment by jbis9051** [comment]
@Hakerh400 Please note, `videoplayback` is an error on chrome however, `videoplayback?test` is not. As I have used the `videoplayback?test` in the request, there should be no error.

**Comment by jbis9051** [comment]
`path` seems to work. Thanks!
