### ISSUE TITLE
`crypto.generateKeyPair` without passphrase

### ISSUE THREAD

**Issue by CupCakeArmy** [nodejs/help#1839]
* **Node.js Version**: 11.10.0
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

```js
const { generateKeyPair } = require('crypto');
generateKeyPair('rsa', {
  modulusLength: 4096,
  publicKeyEncoding: {
    type: 'spki',
    format: 'pem'
  },
  privateKeyEncoding: {
    type: 'pkcs8',
    format: 'pem',
    cipher: 'aes-256-cbc',
    passphrase: 'top secret'
  }
}, (err, publicKey, privateKey) => {
  // Handle errors and use the generated key pair.
});
```

is it possible to create an rsa key pair inside the `crypto` module without a passphrase?

**Comment by bnoordhuis** [comment]
The answer is 'yes'. I assume you tried it and it somehow didn't work? What was the error you got?

Note that when you leave out `passphrase`, then you also need to leave out `cipher`.

**Comment by CupCakeArmy** [comment]
Yes, now it works.
I was using typescript and the typing are wrong, so I thought there was no way to do that

```typescript
import { generateKeyPair } from 'crypto'

async function main() {
	// @ts-ignore
	generateKeyPair('rsa', {
		modulusLength: 4096,
		publicKeyEncoding: { type: 'pkcs1', format: 'pem' },
		privateKeyEncoding: { type: 'pkcs1', format: 'pem' },
	}, (err: string, publicKey: string, privateKey: string) => {
		console.log(publicKey, privateKey) // => Works
	})
}

main()
```

Thanks! 🎉

**Comment by huevoncito** [comment]
@cupcakearmy I'm wondering if you could help me.

I created a privateKey an emptry string as the passphrase. Now, when I try to decrypt, I get 

`Error: error:09000068:PEM routines:OPENSSL_internal:BAD_PASSWORD_READ
[1]     at Object.createPrivateKey (internal/crypto/keys.js:329:10)
` 
Also I can't seem to change the password either. Am I missing something?

**Comment by bnoordhuis** [comment]
@huevoncito What do `node -v`, `node -p process.versions` and `otool -L $(which node)` print?

**Comment by cupcakearmy** [comment]
@huevoncito I wrote a small wrapper around the node crypto api.

https://github.com/cupcakearmy/occulto#rsa this example is for RSA

or check the source code here 
https://github.com/cupcakearmy/occulto/blob/master/src/RSA.ts

The example works in the latest version of node.

Hope it helps :)

**Comment by cupcakearmy** [comment]
@huevoncito just tested it on catalina 10.15.2 with node v12.13.1

**Comment by huevoncito** [comment]
@cupcakearmy @bnoordhuis I was able to solve the problem. The issue is the empty passphrase. In the normal node app, I used the exact same pk, exported it with a new passphrase, and was able to consume it in Electron no problem. Something about the electron version of node or openssl doesn't like the empty passphrase.

**Comment by cupcakearmy** [comment]
I see. probably a openssl discrepancy between `1.1.1d` and `1.1.0`.

**Comment by bnoordhuis** [comment]
@huevoncito Can you share a minimal test case? Perhaps there's a bug somewhere in node that needs to be fixed but I'm not able to reproduce that BAD_PASSWORD_READ error when e.g. you take @cupcakearmy's example from the top post and replace `'top secret'` with an empty string.

**Comment by huevoncito** [comment]
@bnoordhuis Yes it can but it will take a few days (busy time). Hope that's OK.
