### ISSUE TITLE
RSS grows all the time, what is the cause?

### ISSUE THREAD

**Issue by roman-io** [nodejs/help#184]
Node v4.4.4
Ubuntu LTS 14.04 3.13.0-86-generic
E3, 4 cores, 16Gb Ram

I have an issue with the service written in Node. It grows in memory and after it reaches the server memory limit, the process crashes with an error:

```
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory

<--- Last few GCs --->

37136896 ms: Mark-sweep 35.6 (5345832.9) -> 35.5 (5424623.9) MB, 445.4 / 0 ms [allocation failure] [GC in old space requested].
37137314 ms: Mark-sweep 35.5 (5424624.9) -> 35.5 (5503415.9) MB, 412.8 / 3 ms [allocation failure] [GC in old space requested].
37138040 ms: Mark-sweep 35.5 (5503416.9) -> 35.3 (5580419.9) MB, 641.8 / 0 ms [last resort gc].
37138321 ms: Mark-sweep 35.3 (5580419.9) -> 34.6 (5651262.9) MB, 211.2 / 0 ms [last resort gc].
```

Memory logs shows:
Stared with: `Total: 61mb, Used: 35mb, RSS: 104mb`
After ~30 minutes: `Total: 62mb, Used: 33mb, RSS: 903mb`

The total heap and used heap are staying the same, but the RSS grows up to 16GB and process crashes.

In memwatch-next, that I 'diffed' after 3 minutes of processing, I don't see anything wrong with my classes.

How I can solve this issue?
Thanks

**Comment by bnoordhuis** [comment]
Try node-inspector or node-heapdump.  You can also try `--inspect` with the latest v7 nightly from [here](https://nodejs.org/download/nightly/).

**Comment by roman-io** [comment]
What would help me to look at **heap**dump if the heap doesn't grow?
How I can look what is growing inside the RSS? 
Thanks

**Comment by bnoordhuis** [comment]
Have you tried them?  The original memwatch (and AFAIK memwatch-next is no different) doesn't really understand external data objects like buffers and typed arrays, the other tools do.

**Comment by chuangtim** [comment]
@bnoordhuis I also meet that, I can look at heapdump total and heapdump used,how can I understand what is store inside the  RSS? which tool can be help?

**Comment by chuangtim** [comment]
@roman-io Hi.I meet the same situation as you meet, which tool can be helped to detect rss?

**Comment by roman-io** [comment]
@chuangtim If you don't see it in the heap, it may mean that an external library is not running inside Node VM scope but embedded into the process leaks. For example, external C library calls. I just checked the few libraries my software is using that make such calls, and one of them was leaking.

@bnoordhuis I have tried the heapdump, but it doesn't show signs of leak.

You can try to find the way to detect such leaks with this example:
```
var Xsd = require('libxml-xsd'); // v0.5.1 leaks
var schema = [
'<?xml version="1.0" encoding="ISO-8859-1" ?>',
'  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">',
'    <xs:element name="test" type="xs:string" />',
'  </xs:schema>'
].join('');
var validator = Xsd.parse(schema);

for (var i = 0; i < 10000; i++) {
        var temp = validator.validate('<test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Roman</test>');
}
```
