### ISSUE TITLE
node js version stuck on v6.11

### ISSUE THREAD

**Issue by ShangruTian** [nodejs/help#1841]
I downloaded the v11.13.0-x64 msi from the node js website and installed it on my pc. But running 
node -v
in the command line, it is showing the version as v6.11.0

**Comment by yathamravali** [comment]
@ShangruTian 
Just to know, How did u installed v6.11.0, is it also an msi ?

Two things 
1. node-v6.11.0 might not be deleted
2. Check the path whether it is pointing to the older one prior to the newer one.

**Comment by gireeshpunathil** [comment]
ping @ShangruTian

**Comment by gireeshpunathil** [comment]
answered, closing
