### ISSUE TITLE
Err! code MODULE_NOT_FOUND './package.json' when run any command like ng serve, ng new project_name

### ISSUE THREAD

**Issue by firoz5674** [nodejs/help#1842]
I install node js 10.15 but when i try to execute npm command like ng serve or ng new project_name. Please help me to sort out this issue.

Error Name: ERR! code MODULE_NOT_FOUND './package.json'

* **Node.js Version**: 10.15
* **OS**: Windows 7 64bit
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by gireeshpunathil** [comment]
`ng` is not an npm command, but and `angular` module. without knowing what that (`ng start`) is doing and what is the call stack etc. it is difficult to provide any suggestions. Do you have any debug logs generated when this error happens?

**Comment by gireeshpunathil** [comment]
ping @firoz5674

**Comment by gireeshpunathil** [comment]
answered, closing
