### ISSUE TITLE
Node.js Setup Wizard ended prematurely

### ISSUE THREAD

**Issue by DeVeLy1** [nodejs/help#1847]
can't install nodejs on windows 10, x64.

Node.js Version: node-v10.1.0-x64.msi
OS: Windows10
Scope (install, code, runtime, meta, other?): install
Module (and version) (if relevant):
here is the installation logs:
MSI (c) (14:90) [19:54:51:021]: Enabling baseline caching for this transaction since all active patches are MSI 3.0 style MSPs or at least one MSI 3.0 minor update patch is active
=== Logging started: 06.04.2019  19:54:51 ===
Action start 19:54:51: INSTALL.
Action start 19:54:51: SetInstallScope.
MSI (c) (14:90) [19:54:51:054]: Creating MSIHANDLE (1) of type 790542 for thread 6288
MSI (c) (14!4C) [19:54:51:115]: Creating MSIHANDLE (2) of type 790541 for thread 13900
MSI (c) (14!4C) [19:54:51:115]: Creating MSIHANDLE (3) of type 790541 for thread 13900
MSI (c) (14!4C) [19:54:51:116]: Creating MSIHANDLE (4) of type 790540 for thread 13900
MSI (c) (14!4C) [19:54:51:116]: Creating MSIHANDLE (5) of type 790531 for thread 13900
MSI (c) (14!4C) [19:54:51:116]: Closing MSIHANDLE (5) of type 790531 for thread 13900
MSI (c) (14!4C) [19:54:51:116]: Creating MSIHANDLE (6) of type 790531 for thread 13900
MSI (c) (14!4C) [19:54:51:116]: Closing MSIHANDLE (6) of type 790531 for thread 13900
MSI (c) (14!4C) [19:54:51:116]: Closing MSIHANDLE (2) of type 790541 for thread 13900
MSI (c) (14!4C) [19:54:51:116]: Closing MSIHANDLE (4) of type 790540 for thread 13900
MSI (c) (14!4C) [19:54:51:116]: Closing MSIHANDLE (3) of type 790541 for thread 13900
MSI (c) (14:A0) [19:54:51:116]: Closing MSIHANDLE (1) of type 790542 for thread 6288
Action ended 19:54:51: SetInstallScope. Return value 1.
Action start 19:54:51: FindRelatedProducts.
Action ended 19:54:51: FindRelatedProducts. Return value 1.
Action start 19:54:51: PrepareDlg.
Info 2898. For WixUI_Font_Normal textstyle, the system created a 'Tahoma' font, in 0 character set, of 13 pixels height.
Info 2898. For WixUI_Font_Bigger textstyle, the system created a 'Tahoma' font, in 0 character set, of 19 pixels height.
Action ended 19:54:51: PrepareDlg. Return value 1.
Action start 19:54:51: AppSearch.
Action ended 19:54:51: AppSearch. Return value 1.
Action start 19:54:51: LaunchConditions.
Action ended 19:54:51: LaunchConditions. Return value 1.
Action start 19:54:51: ValidateProductID.
Action ended 19:54:51: ValidateProductID. Return value 1.
Action start 19:54:51: CostInitialize.
MSI (c) (14:90) [19:54:51:157]: Baseline: Sorting baselines for {5EEFB772-5056-46E9-8209-B4BAC3171C52}.
MSI (c) (14:90) [19:54:51:157]: Baseline: New baseline 10.15.3 from transaction.
MSI (c) (14:90) [19:54:51:178]: Baseline: Sorted order Native: Order 0.
MSI (c) (14:90) [19:54:51:178]: Baseline Data Table:
MSI (c) (14:90) [19:54:51:178]: ProductCode: {5EEFB772-5056-46E9-8209-B4BAC3171C52} Version: 10.15.3 Attributes: 0 PatchId: Native BaselineId: -2147483648 Order: 0
MSI (c) (14:90) [19:54:51:178]: Baseline File Table:
Action ended 19:54:51: CostInitialize. Return value 1.
Action start 19:54:51: FileCost.
Action ended 19:54:51: FileCost. Return value 1.
Action start 19:54:51: CostFinalize.
Action ended 19:54:51: CostFinalize. Return value 1.
Action start 19:54:51: MigrateFeatureStates.
Action ended 19:54:51: MigrateFeatureStates. Return value 0.
Action start 19:54:51: WelcomeDlg.
Info 2898. For WixUI_Font_Title textstyle, the system created a 'Tahoma' font, in 0 character set, of 14 pixels height.
Info 2898. For WixUI_Font_Normal__UL textstyle, the system created a 'Tahoma' font, in 204 character set, of 13 pixels height.
Action ended 19:54:57: WelcomeDlg. Return value 1.
Action start 19:54:57: ProgressDlg.
Action ended 19:54:57: ProgressDlg. Return value 1.
Action start 19:54:57: ExecuteAction.
Action ended 19:54:57: ExecuteAction. Return value 3.
Action start 19:54:57: FatalError.
Action ended 19:54:59: FatalError. Return value 2.
Action ended 19:54:59: INSTALL. Return value 3.
=== Logging stopped: 06.04.2019  19:54:59 ===
MSI (c) (14:90) [19:54:59:318]: Product: Node.js -- Installation failed.

MSI (c) (14:90) [19:54:59:319]: Windows Installer installed the product. Product Name: Node.js. Product Version: 10.15.3. Product Language: 1033. Manufacturer: Node.js Foundation. Installation success or error status: 1603.

**Comment by DeVeLy1** [comment]
help!

**Comment by gireeshpunathil** [comment]
@DeVeLy1 - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
