### ISSUE TITLE
Does Adobe Creative Cloud use node.js?

### ISSUE THREAD

**Issue by michael-reisman08** [nodejs/help#1848]
Hello,

I have entries in my Windows 10 background processes in my task manager.  They all read:

Node.js: Server-side-JavaScript(32 bit)

They are using a lot of memory and I thought I would remove them. Choosing to open the file's location shows that node.js.exe is in an Adobe Creative Cloud folder:

C:\Program Files (x86)\Adobe\Adobe Creative Cloud Experience\libs

Is this normal?

It appears Dreamweaver uses this? Why then 3 entries all the same in the task manager?

I reinstalled Node.js and then uninstalled, but this didn't change the entries in my background processes.

Thanks,

Michael

**Comment by kahwee** [comment]
Adobe Creative Cloud does use Node.js as a runtime. It's best to seek out [Adobe's forum](https://forums.adobe.com/thread/2243475) for more information. Any software can use Node.js and bundle it within their app and it's how the software utilize Node result in the memory it requires as a process.

Also, uninstalling and reinstalling Node.js doesn't modify the runtime that Adobe uses. Best to seek out Adobe through their support channels.

**Comment by gireeshpunathil** [comment]
@michael-reisman08 - does @michael-reisman08 's answer help you?

**Comment by gireeshpunathil** [comment]
answered, closing
