### ISSUE TITLE
Import json file with different name

### ISSUE THREAD

**Issue by johnroper100** [nodejs/help#1850]
* **Node.js Version**: 11
* **OS**: Ubuntu 18.04
* **Scope (install, code, runtime, meta, other?)**: Code

I have been able to import json files using `require("myfile.json");`. I have some files that are actually json but are named with a different file extension (`myfile.jlib` for example). How can I require them as normal json without changing the filename?

**Comment by richardlau** [comment]
The deprecated way is to use [`require.extensions`](https://nodejs.org/dist/latest-v11.x/docs/api/modules.html#modules_require_extensions).

I'm not aware of a replacement for the CommonJS module loader (`require()`) other than to read the file in with something like `fs.readFile()` and calling `JSON.parse()` on the results.

For [ECMAScript modules (esm)](https://nodejs.org/dist/latest-v11.x/docs/api/esm.html) the replacement seems to be to use [loader hooks](https://nodejs.org/dist/latest-v11.x/docs/api/esm.html#esm_loader_hooks).

cc @nodejs/modules
