### ISSUE TITLE
Is it possible to use Valgrind or other memory leak detector to debug native Node.js addons?

### ISSUE THREAD

**Issue by VictorQueiroz** [nodejs/help#1851]
I use Valgrind to detect memory leaks in my C/C++ code so I'm wondering if it'd be possible to do the same to my C++ code that I write to create bindings to my Node.js code. Downloading Node.js from source and building it with debug flag and then using Valgrind would be a reasonable option?

Also would be possible to integrate it with IDE like CLion? It'd definitely be something else.

Thank you in advance.

**Comment by bnoordhuis** [comment]
You can and you probably don't even need to build Node.js in debug mode, just your add-on. Pass `--debug` to npm or node-gyp.

There's [a suppression file](https://github.com/nodejs/node/blob/master/tools/valgrind.supp) but it's best effort and against master, it might not work (fully) against release versions.

I don't know about IDE integration, I don't use those.

**Comment by mhdawson** [comment]
Don't know about IDE integration either, but I can confirm that I've used valgrind with Node.js and addons (for example in https://github.com/nodejs/node/issues/26667).  I did use --debug but even without that I got useful data.

**Comment by gireeshpunathil** [comment]
answered, closing.
