### ISSUE TITLE
Unable to create-reacte-app my-app using cmd. What could be the problem???

### ISSUE THREAD

**Issue by Nketsia** [nodejs/help#1852]
* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by DylanMerigaud** [comment]
https://github.com/zkat/npx/issues/100#issuecomment-344293820

> running cmd through administrator works for me

**Comment by gireeshpunathil** [comment]
ping @Nketsia - does @DylanMerigaud 's suggestion help you?

**Comment by gireeshpunathil** [comment]
answered, closing
