### ISSUE TITLE
How to install on OSX - Could not find instructions on the website

### ISSUE THREAD

**Issue by velara3** [nodejs/help#1853]
Sorry for the seemingly basic question but how do I install node.js on Mac OSX? I couldn't find instructions on the site. I was directed here to install node.js, https://nodejs.org/en/ and I see a link to download. 

<img src="https://user-images.githubusercontent.com/1084127/55756629-d74d9400-5a06-11e9-9c4c-ae1d8b26ad63.png" alt="drawing" width="600" />

When I click on that link it shows a list of files in a folder. 

<img src="https://user-images.githubusercontent.com/1084127/55755840-ffd48e80-5a04-11e9-819a-cf0551a7ad7a.png" alt="drawing"  width="500" />

Which do I download? 

I guessed that it may be node-v10.15.3-darwin-x64.tar.gz? Is this right? I downloaded it and uncompressed it and it shows a list of files. 

<img src="https://user-images.githubusercontent.com/1084127/55755891-1e3a8a00-5a05-11e9-8644-932aace54535.png" alt="drawing" width="450" />

Where do I put these? 

When I opened the read me I found a reference to "installation" and it points back to the download page lol

_Binaries, installers, and source tarballs are available at
<https://nodejs.org/en/download/>._

**Comment by Hakerh400** [comment]
If you want the full installation download `node-v10.15.3.pkg` then install using the installation manager (it should be the default program to open .pkg files, so just double click on it)

If you want just the node executable, you can download the `.tar.gz` (like you did), then extract it and navigate to the `bin` directory using terminal. Then you can start node using `./node` command.

![](https://user-images.githubusercontent.com/13399152/55773837-de21e880-5a92-11e9-935f-989db03804df.png)

**Comment by gireeshpunathil** [comment]
answered, closing
