### ISSUE TITLE
Calling OPC-UA Methods with custom objects as parameters

### ISSUE THREAD

**Issue by Katakana54** [nodejs/help#1854]
Hi guys,
I have a project where one of my colleagues is trying to read data from an RFID reader which it seems has some methods which require as parameters Custom Objects, and he was not able to pass that type with this implementation. I know that method calling using normal params works, but do you have any idea if we can pass a custom object, and if yes, how?

Thanks in advance and excuse the possible lack of knowledge :)

**Comment by kaczynskij** [comment]
Hello @sam-github and thanks for your prompt response.
To explain the story short: We're investigating a possibility to invoke methods of the OPC-UA server, using node-opcua package. In general, when input params are standard types, it's working perfectly. But when a method requires input param of a custom namespace, it doesn't.

![image](https://user-images.githubusercontent.com/24609545/55899637-9d76bc00-5bc5-11e9-8b32-dd8e5786471f.png)

In fact, this is one input param, which is a custom object, which contains a couple of configuration attributes:

![image](https://user-images.githubusercontent.com/24609545/55899768-e75fa200-5bc5-11e9-8b77-0765bb1ce2bb.png)

In fact I'm aware OPC-UA allows to use ExtensionObjects here, but to be honest, it didn't work for me, probably doing something wrong (or it's not supported in such a straightforward way).

I tried to initialize value Extension Object in a couple of ways, simpler or more complex, below you can find one of trials.

`
var opcua = require("node-opcua");
var async = require("async");
var client = new opcua.OPCUAClient();
var endpointUrl = "xxx";
var VariantArrayType = opcua.VariantArrayType;
var DataType = opcua.DataType;

var the_session, the_subscription;

async.series([

    function(callback)  {
        client.connect(endpointUrl,function (err) {
            if(err) {
                console.log(" cannot connect to endpoint :" , endpointUrl );
            } else {
                console.log("connected !");
            }
            callback(err);
        });
    },
	
    function(callback) {
        client.createSession( function(err,session) {
            if(!err) {
                the_session = session;
            }
            callback(err);
        });
    },
	
	function(callback) {
	
		var objNodeId = "ns=3;i=5024";
		var metNodeId = "ns=3;i=7028";
		
		var methodsToCall = [];
		methodsToCall.push({
			objectId: objNodeId,
			methodId: metNodeId,
			inputArguments: [{
				dataType:DataType.ExtensionObject,
				value: { 
					Duration: 0,
					Cycles: 0,
					DataAvailable: true
				}
			}]
		});
		
		the_session.call(methodsToCall,function(err,results){
			console.log("Result: " + results);
			callback(err);
		});
		
	},
	
	function(callback) {
		console.log("Logout");
        the_session.close(function(err){
            if(err) {
                console.log("session closed failed ?");
            }
            callback();
        });
    }

], function(err) {
    if (err) {
        console.log(" failure ",err);
    } else {
        console.log("done!");
    }
    client.disconnect(function(){});
}) ;
`

Error returned:

> xxxxxxxxx encoding ExtObj  { Duration: 0, Cycles: 0, DataAvailable: true }
ERROR !!! , please check here !!!! callback may be called twice !!  Error: Cannot find encodingDefaultBinary for this object


Any feedback or suggestion appreciated.

**Comment by sam-github** [comment]
Sorry, there isn't a single line of code in that example that uses the node API, shouldn't you be asking the node-opcua project about how to do this? I thought you were talking about passing custom types to *node's* API. but that doesn't seem to  be the case.

**Comment by Katakana54** [comment]
My bad. I misposted since I was in a hurry it seems.

**Comment by gireeshpunathil** [comment]
@Katakana54 - I have the admin rights to nodejs organization, but `node-OPCua` does not belong here, so cannot transfer , you may please post over there manually.

closing here, pls let me know if there is anything outstanding on this that needs assistance!
