### ISSUE TITLE
Kernel panic after Node.js installation on MacOS 10.7.5.

### ISSUE THREAD

**Issue by imgmkrz** [nodejs/help#1855]
* **Node.js Version**: 10.15.3 LTS
* **OS**: OS X 10.7.5
* **Scope (install, code, runtime, meta, other?)**: Install on MacMini 2,1 alright but after reboot
keep crashing at bootload
* **Module (and version) (if relevant)**: not installed

I have followed the install instruction and finished OK. I heard that this Node.js is not compatible with old OS, is that right, or could it be something to do with me meddling with system before, like using a beta graphic kext, replacing HD with SSD with no-Apple TRIM support, etc? 
All I can provide is a recovery mode install error report and photo of kernel panic screen.
Thank you.

![IMG_3922](https://user-images.githubusercontent.com/49447470/55813440-bb8ddf00-5b27-11e9-8560-82d1c2a70b5e.JPG)

Apr  8 15:39:10 localhost Unknown[655]: kern.boottime: { sec = 1554762360, usec = 0 } Mon Apr  8 15:26:00 2019
Apr  8 15:39:22 localhost Unknown[667]: Launching the Language Chooser for an OS Install
Apr  8 15:41:56 localhost LCA[668]: Bookmark failed to issue extension for item  (depth=4000): No such file or directory
Apr  8 21:55:36 localhost configd[111]: subnet_route_if_index: can't get interface name
Apr  8 21:55:42 localhost configd[111]: subnet_route_if_index: can't get interface name
Apr  8 21:56:32 localhost LCA[668]: Launching the Springboard using language code "English"
Apr  8 21:57:44 localhost OSIESpringboard[693]: Bookmark failed to issue extension for item  (depth=4000): No such file or directory
Apr  8 21:58:03 localhost Unknown[669]: Keyboard Layouts: duplicate keyboard layout identifier -16899.
Apr  8 21:58:03 localhost Unknown[669]: Keyboard Layouts: keyboard layout identifier -16899 has been replaced with -28673.
Apr  8 21:58:03 localhost Unknown[669]: Keyboard Layouts: duplicate keyboard layout identifier -16900.
Apr  8 21:58:03 localhost Unknown[669]: Keyboard Layouts: keyboard layout identifier -16900 has been replaced with -28674.
Apr  8 21:58:34 localhost Unknown[669]: objc[699]: Class IFJS_Context is implemented in both /System/Library/PrivateFrameworks/Install.framework/Frameworks/DistributionKit.framework/Versions/A/DistributionKit and /System/Library/PrivateFrameworks/Install.framework/Versions/A/Install. One of the two will be used. Which one is undefined.
Apr  8 21:58:34 localhost Unknown[669]: objc[699]: Class IFJS_Cache is implemented in both /System/Library/PrivateFrameworks/Install.framework/Frameworks/DistributionKit.framework/Versions/A/DistributionKit and /System/Library/PrivateFrameworks/Install.framework/Versions/A/Install. One of the two will be used. Which one is undefined.
Apr  8 21:58:34 localhost Unknown[669]: objc[699]: Class PKRequiredCLDevice is implemented in both /System/Library/PrivateFrameworks/Install.framework/Frameworks/DistributionKit.framework/Versions/A/DistributionKit and /System/Library/PrivateFrameworks/Install.framework/Versions/A/Install. One of the two will be used. Which one is undefined.
Apr  8 21:58:34 localhost Unknown[669]: objc[699]: Class PKRequiredGLRenderer is implemented in both /System/Library/PrivateFrameworks/Install.framework/Frameworks/DistributionKit.framework/Versions/A/DistributionKit and /System/Library/PrivateFrameworks/Install.framework/Versions/A/Install. One of the two will be used. Which one is undefined.
Apr  8 21:58:34 localhost Unknown[669]: objc[699]: Class PKGraphicsHardwareRequirements is implemented in both /System/Library/PrivateFrameworks/Install.framework/Frameworks/DistributionKit.framework/Versions/A/DistributionKit and /System/Library/PrivateFrameworks/Install.framework/Versions/A/Install. One of the two will be used. Which one is undefined.
Apr  8 22:19:34 localhost Unknown[669]: 2019-04-08 22:19 Mac OS X Utilities[693] (CarbonCore.framework) FSEventStreamStart: ERROR: FSEvents_connect() => Unknown service name (1102)
Apr  8 22:19:44 localhost opendirectoryd[100]: 380.1 - Client: coreservicesd, UID: 0, EUID: 0, GID: 0, EGID: 0
Apr  8 22:19:44 localhost opendirectoryd[100]: 380.1 - ODNodeCreateWithName request, SessionID: 00000000-0000-0000-0000-000000000000, Name: /Local/Default
Apr  8 22:19:45 localhost opendirectoryd[100]: 380.1 - loading configuration for '/Local' from '/System/Library/OpenDirectory/Configurations/Local.plist'
Apr  8 22:19:47 localhost opendirectoryd[100]: Loaded bundle at path '/System/Library/OpenDirectory/Modules/PlistFile.bundle'
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.1 - unable to find authentication module 'ConfigurationProfiles'
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.1 - unable to find service discovery callback for module 'PlistFile'
Apr  8 22:19:48 localhost opendirectoryd[100]: Registering for network changes
Apr  8 22:19:48 localhost opendirectoryd[100]: Registered subnode with name '/Local/Default'
Apr  8 22:19:48 localhost opendirectoryd[100]: failed to open local node for internal record copy
Apr  8 22:19:48 localhost opendirectoryd[100]: Registering for power changes
Apr  8 22:19:48 localhost opendirectoryd[100]: Registering for network power changes
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.1, Node: /Local/Default - node assigned UUID - 1B9E465F-EBC7-4993-A6F0-BB387F3A5564
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.1, Node: /Local/Default - ODNodeCreateWithName completed
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.2 - Client: coreservicesd, UID: 0, EUID: 0, GID: 0, EGID: 0
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.2 - ODQueryCreateWithNode request, NodeID: 1B9E465F-EBC7-4993-A6F0-BB387F3A5564, RecordType(s): dsRecTypeNative:config, Attribute: dsAttrTypeStandard:RecordName, MatchType: EqualTo, Equality: CaseExact, Value(s): SharePoints, Requested Attributes: dsAttributesAll, Max Results: 1
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.2, Node: /Local/Default, Module: PlistFile - client is using a native record type 'config' which is not portable
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.2, Node: /Local/Default, Module: PlistFile - client is using a native record type 'config' which is not portable
Apr  8 22:19:48 localhost opendirectoryd[100]: 380.2, Node: /Local/Default, Module: PlistFile - ODQueryCreateWithNode completed
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.3 - Client: coreservicesd, UID: 0, EUID: 0, GID: 0, EGID: 0
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.3 - ODNodeCreateRecord request, NodeID: 1B9E465F-EBC7-4993-A6F0-BB387F3A5564, RecordType: dsRecTypeNative:config, RecordName: SharePoints, Attributes: <none>
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.3, Node: /Local/Default, Module: PlistFile - client is using a native record type 'config' which is not portable
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.3, Node: /Local/Default, Module: PlistFile - ODNodeCreateRecord completed, delivered 1 result
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.4 - Client: coreservicesd, UID: 0, EUID: 0, GID: 0, EGID: 0
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.4 - ODQueryCreateWithNode request, NodeID: 1B9E465F-EBC7-4993-A6F0-BB387F3A5564, RecordType(s): dsRecTypeNative:config/SharePoints, Attribute: dsAttrTypeStandard:RecordName, MatchType: Any, Equality: CaseExact, Value(s): dsRecordsAll, Requested Attributes: dsAttrTypeNative:ftp_guestaccess,dsAttrTypeNative:smb_name,dsAttrTypeNative:sharepoint_account_uuid,dsAttrTypeNative:smb_createmask,dsAttrTypeNative:sharepoint_version,dsAttrTypeStandard:AppleMetaNodeLocation,dsAttrTypeNative:afp_guestaccess,dsAttrTypeNative:afp_shared,dsAttrTypeStandard:RecordType,dsAttrTypeNative:ftp_shared,dsAttrTypeNative:afp_name,dsAttrTypeNative:smb_oplocks,dsAttrTypeNative:afp_use_parent_owner,dsAttrTypeNative:smb_directorymask,dsAttrTypeStandard:RecordName,dsAttrTypeNative:afp_use_parent_privs,dsAttrTypeNative:smb_guestaccess,dsAttrTypeNative:smb_inherit_permissions,dsAttrTypeStandard:AppleMetaRecordName,dsAttrTypeNative:smb_shared,dsAttrTypeNative:directory_path,dsAttrTypeNative:smb_strictlocking,dsAttrTypeNative:sharepoint_group_id,dsAttrTypeNative:ftp_name, Max Results: 2147483647
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.4, Node: /Local/Default, Module: PlistFile - client is using an old record type 'dsRecTypeNative:config/SharePoints' should be using kODRecordTypeSharePoints
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.4, Node: /Local/Default, Module: PlistFile - client is using an old record type 'dsRecTypeNative:config/SharePoints' should be using kODRecordTypeSharePoints
Apr  8 22:19:49 localhost opendirectoryd[100]: 380.4, Node: /Local/Default, Module: PlistFile - flushing record '/private/var/db/dslocal/nodes/Default/config/SharePoints'
Apr  8 22:19:50 localhost opendirectoryd[100]: Module: PlistFile - ___index_record_block_invoke_1: sqlite3_prepare_v2: 21
Apr  8 22:19:50 localhost opendirectoryd[100]: Module: PlistFile - ___index_record_block_invoke_1: sqlite3_prepare_v2: 21
Apr  8 22:19:50 localhost opendirectoryd[100]: 380.4, Node: /Local/Default, Module: PlistFile - ODQueryCreateWithNode completed

**Comment by gireeshpunathil** [comment]
@imgmkrz - though the node was built on `v10.11.x` I don't think `v10.7.x` should suffer to the extend of kernel panic. It could be some thing else in my opinion. However, let us ask @nodejs/platform-macos

**Comment by gireeshpunathil** [comment]
@imgmkrz - is this still happening?

**Comment by imgmkrz** [comment]
Yes, I have given up for the time being since. I plan to access MacMini's HD by Target mode and copy the files for backup and see what else I can do later. Thank you.

**Comment by gireeshpunathil** [comment]
closing then, cheers!
