### ISSUE TITLE
read/stream from named pipe without using child process

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1857]
* **Node.js Version 11**:
* **OS any**:

Is there a way to read from a named pipe using Node.js without using a child process?

i would guess that using

```
fs.createReadStream('/named/pipe.fifo')
```

wouldnt keep listening

whereas

```
const k = cp.spawn('bash');
k.stdin.end(`
    while true; do
        cat /named/pipe.fifo
    done;
`);
```

would remain open/listening forever (until the fifo got deleted or something).

**Comment by gireeshpunathil** [comment]
@ORESoftware - I guess the issue with `fs.createReadStream` is that the stream would treat the source (named pipe) as a file, and when a null chunk is read the stream would assume the end of file has reached, and close the stream.

If you are not interested in listening on the pipe and act like a server, then you need probably a custom stream implementation that reads from the pipe, but does not close the stream when no data is present.

Hope this helps!

**Comment by gireeshpunathil** [comment]
@ORESoftware - does this help your scenario?

**Comment by gireeshpunathil** [comment]
answered, closing; pls re-open if it is still not helping
