### ISSUE TITLE
Platform Compatibility

### ISSUE THREAD

**Issue by Jasjeet-sh** [nodejs/help#1858]
Is nodejs compatible with Citrix VDI environment?

**Comment by gireeshpunathil** [comment]
@Jasjeet-sh - according to https://www.citrix.co.in/glossary/vdi.html this is a desktop virtualization environment without any stated caveats around limitations on running specific processes etc. , so it should work, though I did not try it out myself. Node.js is a standard C++ process which runs in bare metal, virtual machines and containers, so I don't see any reason why it shouldn't be compatible with Citrix VDI.

If you are planning a commercial product to be developed under this environment, I would recommend you to get in touch with Citrix support to get clarity on this specific question, not just relying on my assumptions based on general knowledge.

Hope this helps!

**Comment by gireeshpunathil** [comment]
answered, closing
