### ISSUE TITLE
Node.js connection to mongo times out after 4000 active connections

### ISSUE THREAD

**Issue by mb999** [nodejs/help#1859]
Hi I have an issue with a node.js application running locally on the same host as a Mongo DB on an aws ec2 instance. The node.js application will not release the connections to the mongodb. They are only released when we kill the node.js app. Mongo is working fine, and can be connected to directly with robo3t. Once the connections to mongo reach around 4000-4200 node.js hangs. New connections can be created to mongo. 

 What is interesting is that the forever agent monitoring it does not detect it is down, when the count

node / npm / and mongo versions below:

thank in advance,

M

xxxxxxxxxxxxxxxxxxxxxxxx mongodb]# node -version
node: bad option: -version
[xxxxxxxxxxxxxxxxxxxxxxxx mongodb]# node -v
v8.10.0
[xxxxxxxxxxxxxxxxxxxxxxxx mongodb]# npm -v
6.7.0
[xxxxxxxxxxxxxxxxxxxxxxxx mongodb]#
[xxxxxxxxxxxxxxxxxxxxxxxx mongodb]#
[xxxxxxxxxxxxxxxxxxxxxxxx mongodb]# mongo --version
MongoDB shell version v3.6.3
git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64

**Comment by gireeshpunathil** [comment]
@mb999 - sorry, but I am unable to follow few of your descriptions; can you please clarify those?

> Hi I have an issue with a node.js application running locally on the same host as a Mongo DB on an aws ec2 instance.

1. are you running locally of AWS EC2?
2. are you running both node and mongo on the same host?

> The node.js application will not release the connections to the mongodb.

1. what does this mean? node is unable to connect to mongodb? or connected sessions are not terminated? or something else?
2. which mongo client library you are using?

> What is interesting is that the forever agent monitoring it does not detect it is down, when the count

you mean when the count reaches ~4000 ?

**Comment by wide4head** [comment]
@mb999 Can you post the relevant snippet of the code that interfaces with mongodb. Perhaps somebody with mongo experience can take a look and advise.

**Comment by gireeshpunathil** [comment]
ping @mb999

**Comment by gireeshpunathil** [comment]
inactive, closing
