### ISSUE TITLE
installing nodejs and visual studio.

### ISSUE THREAD

**Issue by endencia** [nodejs/help#186]

**Comment by endencia** [comment]
I downlaoded both programs and have been working on courses via udemy.com.  When I tried out exercises, the command prompt of node js cannot find the visual studio code.  How do you integrate both software?  the error message state it does not recognize as an internal or external command.
https://www.dropbox.com/s/hw7zhiceo9jgrpg/Screenshot%202016-06-03%2020.58.40.png?dl=0

**Comment by lordKnighton** [comment]
I don't have to much experience in windows, but I'll help as much as i can.

I'm referring you here - there running a simple program, If this program works for you, then we will know your system is set up right. 
http://stackoverflow.com/questions/6737824/how-to-run-a-hello-js-file-in-node-js-on-windows

**Comment by lordKnighton** [comment]
@endencia how is progress with this?

**Comment by hanu412** [comment]
Go to the folder where you have the project 
1. Right click on the folder -> select open with VS Code
2.Once the project is open , right click on the index.js/app.js and select Open in Command Prompt.

This should get you going.
