### ISSUE TITLE
Error in using port 80

### ISSUE THREAD

**Issue by modhealth** [nodejs/help#1860]
* **Node.js Version**:10.x
* **OS**:ubuntu
* **Scope (install, code, runtime, meta, other?)**:code
* **Module (and version) (if relevant)**:

I am trying to run sudo node server.js command.And I get Error: listen EADDRINUSE: address already in use :::80.
But when I checked using sudo lsof -i :80 ,no process is shown running.
I am new to node. Any help will be much appreciated

```js

```

**Comment by gireeshpunathil** [comment]
@modhealth - by default I guess `lsof` does not show devices that are owned by other processes. Either:
- run the `lsof` command as root to figure out who owns `80`
or
- run `lsof -h` to see whether it was compiled with security ON or OFF

In either way, running with `strace -f node <cmd>` will produce system trace, and you can search for `bind` call to see the return value of it to confirm whether the port was actually in use or not, from the system's perspective.

Hope this helps!

**Comment by wide4head** [comment]
@modhealth Perhaps you can specify a listening port preferably larger than 1024 like 8080 as detailed in [https://stackoverflow.com/questions/12181253/changing-node-js-listening-port](url)

**Comment by gireeshpunathil** [comment]
answered, closing
