### ISSUE TITLE
Stop debugger attached

### ISSUE THREAD

**Issue by MattBristowLF** [nodejs/help#1861]
* **Node.js Version**: 10.15.3
* **OS**: Windows 10

I am debugging a node.js app on Visual Studio 2019 Preview 5.0 however when node.exe command prompt displays, it says "Debugger attached". When I run multiple node.js apps, I usually get separate node.exe command prompts but now they run under one prompt and always saying "Debugger attached".
 
Is there a way to stop this? 
![Screenshot_3](https://user-images.githubusercontent.com/46758040/55963996-bfc31500-5c6b-11e9-980b-4c6bed9604ca.png)

**Comment by gireeshpunathil** [comment]
@MattBristowLF - shouldn't that (whether to show single vs. multiple prompts, whetherto print `debugger attached` message or not) be a feature of tunable at Visual studio 2019 rather than in Node?

**Comment by gireeshpunathil** [comment]
answered, closing
