### ISSUE TITLE
Understanding generator + iterator behavior

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1862]
I having trouble understanding the rationale for the generator behavior here:
https://stackoverflow.com/questions/55644116/getting-return-value-of-generator-via-iteration

Any help appreciated. Sorry for the x-post but hopefully you like the question?

**Comment by devsnek** [comment]
loops drop the value associated with `done: true`. there's no way to get it with a loop.

**Comment by ORESoftware** [comment]
yeah but i wonder why, why that design choice?

**Comment by gireeshpunathil** [comment]
@ORESoftware - I guess this is a Javascript question, not node.js specific. I understand your concern, but don't know the reason - whether it is a concsious design choice or a side effect.
