### ISSUE TITLE
../src/objects.h:2794:20: error: invalid use of incomplete type ‘class v8::internal::Heap’ [-Werror]

### ISSUE THREAD

**Issue by dhokivijay** [nodejs/help#1864]
* **Version**:
[Error_in_Libv8.txt](https://github.com/nodejs/node/files/3075810/Error_in_Libv8.txt)
* **Platform**:
* **Subsystem**:

**Comment by addaleax** [comment]
@dhokivijay You can probably manually fix this by adding the required `#include <...>` statements to the file in question directly.

Your OS version is unlikely to be relevant here.

**Comment by dhokivijay** [comment]
@addaleax  ,Actually i'm not getting the required header  file to add it.
my OS version is 18.04 ubuntu .but it is unable to solve it.

**Comment by gireeshpunathil** [comment]
@dhokivijay - is this still an issue? if so, can you please provide a full description on:
 - your objective
 - the steps that you have performed that led to the issue
 - the doc that you referred for the steps

**Comment by gireeshpunathil** [comment]
answered, closing
