### ISSUE TITLE
Overriding console.log breaks inspector - and cannot be undone.

### ISSUE THREAD

**Issue by thomasmichaelwallace** [nodejs/help#1865]
* **Node.js Version**: v8.10.0
* **OS**: MacOS
* **Scope**: code/runtime
* **Module**: inspector / console

It looks like if you reassign the global `console.log` (or `.info`, etc.) functions, then the `inspector` module will no send console messages to devtools.

For example:

```js
const inspector = require('inspector');

inspector.open();
console.log('this will appear in devtools');
console.log = () => {};
console.log('this will be lost...');
```

The problem is that once `console.log` has been reassigned, there doesn't seem to be a way of getting the original (`inspector` compatible) version back, or a way of making the custom implementation compatible with the `inspector`.

Any guidance on getting `inspector` to play well with overridden `console.log` would be extremely helpful. Either by letting me restore the original (v8) implementation, or by making the custom log functions inspectable, or maybe there's a better way I haven't thought of!

Thanks!

n.b. In my case I'm not the one reassigning `console.log` &c, I'm writing code that is called by something else.

**Comment by gireeshpunathil** [comment]
$  cat 1865.js 
```js
const inspector = require('inspector');

inspector.open();
console.log('this will appear in devtools');
console.log = (d) => {
  process.stdout.write(d + '\n');
};
console.log('this will be lost...');
```

$ node 1865

```trace
Debugger listening on ws://127.0.0.1:9229/21cfa23f-7131-4ccd-bef1-1909f007289c
For help, see: https://nodejs.org/en/docs/inspector
this will appear in devtools
this will be lost...
$
```

@thomasmichaelwallace - if I replace your dummy implementation with something like as shown above, it still works? As long as `console.log` was a valid implementation that writes to the console device, we are good? If `console.log` is overriden to perform something else, and if inspector is writing into that, then loosing data is obvious? Am I missing something here?

**Comment by thomasmichaelwallace** [comment]
Hi,

Thanks for taking a look at this. However the output you've included looks like just what is appearing in the terminal from of `stdout` rather than what gets sent to devtools. If I do this and attach a listener, it you can see that overriding console.log means that devtools no longer receives the message:

<img width="585" alt="Screenshot 2019-04-29 at 07 35 50" src="https://user-images.githubusercontent.com/1954845/56882043-46446880-6a5a-11e9-9f05-d7eaa1dd33d0.png">

I did a lot of digging since posting this. And it is because the inspector patches the v8 console instance, which is not the same as the global node console instance. When node bootstraps it links the console.log implementation to call the v8 version, and then deletes the reference to the v8 console.

This isn’t a problem if _you_ are the one overriding console.log, because you can maintain that reference, but if something else does (which is the case in some managed environments like AWS’ lambda and logging libraries) then you can never find a reference to the original v8 console to restore the inspector from.

I later discovered that this was fixed in Node v10, by adding [`inspector.console`])https://nodejs.org/docs/latest-v10.x/api/inspector.html#inspector_inspector_console). But I had hoped that someone would know a workaround for Node v8.10.

**Comment by gireeshpunathil** [comment]
thanks @thomasmichaelwallace - I see your issue better now. pinging @nodejs/v8-inspector to get an authentic information.

**Comment by thomasmichaelwallace** [comment]
Given that this was fixed in Node v10, and that Node v8 is out of LTS, I'm going to close this.

Thanks for everyone who chipped in!
