### ISSUE TITLE
NodeCategorySet::Initialize function call 

### ISSUE THREAD

**Issue by doaga-alin** [nodejs/help#1866]
NodeJs Version: 11.13.0
OS: AWS Lambda custom runtime
Scope: code -> [NodeCategorySet](https://github.com/nodejs/node/blob/master/src/node_trace_events.cc) object

I'm trying to make a nodejs custom runtime in [AWS](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html). I tried to add  --trace-events-enabled as a parameter and the runtime failed. After that I tried to enable logs programmatically as is described in documentation:
` const trace_events = require('trace_events');
const tracing = trace_events.createTracing({ categories: ['node.perf'] });
tracing.enable();  // Enable trace event capture for the 'node.perf' category
// do work
tracing.disable();  // Disable trace event capture for the 'node.perf' category`

In the second scenario, the runtime produce a timeout. I tried to investigate where the timeout happens, and I found that after the [NodeCategorySet::Initialize](https://github.com/nodejs/node/blob/master/src/node_trace_events.cc) the code stuck. If somebody have some information about AWS custom runtime problem is welcomed, or at least if somebody can provide some information about from where this method (NodeCategorySet::Initialize) is called. It seems the code stuck after this method is called.

**Comment by gireeshpunathil** [comment]
@doaga-alin - if you have ability to collect and transport core dump in the deployment, then doing so when the code is stuck (`gcore pid`), launching it in `gdb` and issuing `bt` will show us who calls this method.

when you say with `--trace-events-enabled` the runtime failed, what was the symptom? and what error message or debug data we have? if we were to look from that direction?

**Comment by gireeshpunathil** [comment]
ping @doaga-alin

**Comment by gireeshpunathil** [comment]
inacrtive, closing
