### ISSUE TITLE
node build tests are failing on mac os mojave 10.14.4

### ISSUE THREAD

**Issue by devasci** [nodejs/help#1871]
* **Node.js Version**: git build
* **OS**: Mac OS Mojave 10.14.4
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**: src/

Trying to contribute by fixing a first-timer issue. setup git repo locally from my personal fork and built. build went fine. Then ran ```./configure && make -j4 test```, but this failed with below error: (note: all prerequisites i've verified and they are matching as required)

 ```
SOLINK_MODULE(target) Release/binding.node
  CXX(target) Release/obj.target/binding/binding.o
  SOLINK_MODULE(target) Release/binding.node
  CXX(target) Release/obj.target/binding/binding.o
  SOLINK_MODULE(target) Release/binding.node
  CC(target) Release/obj.target/ping/ping.o
  SOLINK(target) Release/ping.so
Building addon in /Users/devsci/d3v/gitprojects/node/test/addons/non-node-context
Building addon in /Users/devsci/d3v/gitprojects/node/test/addons/not-a-binding
Building addon in /Users/devsci/d3v/gitprojects/node/test/addons/null-buffer-neuter
/Users/devsci/d3v/gitprojects/node/tools/build-addons.js:58
main(process.argv[3]).catch((err) => setImmediate(() => { throw err; }));
                                                          ^

Error: spawn /Users/devsci/d3v/gitprojects/node/out/Release/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
make[1]: *** [test/addons/.buildstamp] Error 1
make[1]: *** Waiting for unfinished jobs....
  touch /Users/devsci/d3v/gitprojects/node/out/Release/obj.target/rename_node_bin_win.stamp
  c++ -Wl,-force_load,/Users/devsci/d3v/gitprojects/node/out/Release/libv8_base.a 
<Skipped few lines here….>
make: *** [test] Error 2
```

I am running build on master branch which is in sync with nodejs/node upstream repo.
I've no clue what's the error, please help me.

**Comment by bnoordhuis** [comment]
Does `out/Release/node` exists and is it executable? If you run it, the REPL should come up.

Does `make -j4 && make test` work? It's possible the `test` target doesn't like concurrency.

**Comment by devasci** [comment]
Hi Ben Noordhuis, Thank you for the response. 

I ran the ```out/Release/node``` exe and it gave me REPL prompt. 

As you mentioned, i've removed *-j4* while running tests, and it went fine. 100% test were executed successfully. Thank you so much 👍 .
