### ISSUE TITLE
Inconsistent handling of undefined variables between two image based off same node version

### ISSUE THREAD

**Issue by joe-hilling** [nodejs/help#1873]
* **Node.js Version** : 8.14
* **OS**: Linux 

I have a scenario under which my testing environment passes all tests. The problem is that the deployment environment complains about undefined variables.

Somewhere in my code I have some thing like the following;
```
a_function(an_arg) {
   return do_the_thing(an_arg, my_undefined_variable)
}
```
The function `do_the_thing` does not accept a second argument. Now clearly `my_undefined_variable` does not exist (it is not in a wider scope either) and this code is wrong.

However, this function is completely covered by our mocha tests which run in a container based off `circleci/node:8.14` in our CI environments. The tests also pass locally where I am running `node:8.11`.

The deployment uses a docker image build on top of `FROM node:8.14`. I.e almost exactly matches the CI environment (and is close to the local environment).

The deployment however throws a `ReferenceError:my_undefined_variable is undefined`.

I know this easy to fix but I am curious as to what might be the source of my deployment environment and testing environment having different opinions on the validity of this code? Especially since they seem to be running compatible Node versions.

Any ideas welcome and thanks in advance.

**Comment by bnoordhuis** [comment]
It's possible you're hitting a bug in V8, the JS engine, but it's hard to say for sure without a standalone test case.

There was at least one bug where the deoptimizer didn't always deoptimize properly that was fixed sometime between v8.11.0 and v8.14.0.

**Comment by joe-hilling** [comment]
Thanks for responding @bnoordhuis . We are spotting the discrepancy between `circleci/node:8.14` and `node:8.14` so that bug should have been fixed? I think I am going to tighter our linter to fail rather than warn on undefined variables and just move on. It's going to be a faff to produce a replicable test case and given that you are now on V11 (ish) I can't see this being of much interest to anyone. It's a niggle I will live with :)

**Comment by gireeshpunathil** [comment]
answered, closing
