### ISSUE TITLE
Is the license free for a legal entity?

### ISSUE THREAD

**Issue by ArslanaliDag** [nodejs/help#1874]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by ArslanaliDag** [comment]
Is the license free for a legal entity?

**Comment by ArslanaliDag** [comment]
Nodejs

**Comment by gireeshpunathil** [comment]
@ArslanaliDag - can you please clarify your question?

**Comment by gireeshpunathil** [comment]
inactive, closing
