### ISSUE TITLE
Console.log bug: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by Zoddo** [nodejs/help#1876]
* **Version**: v11.14.0
* **Platform**: Linux zoddo 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
* **Subsystem**:

I got this error:
```
(node:7834) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:251:17)
    at WriteStream.addListener (events.js:267:10)
    at WriteStream.Readable.on (_stream_readable.js:838:35)
    at WriteStream.once (events.js:296:8)
    at Console.(anonymous function) (internal/console/constructor.js:240:12)
    at Console.log (internal/console/constructor.js:287:26)
    at Logger.log (/<snip>/src/util/Logger.js:50:13)
    at Shard.onLog (/<snip>/src/Shard.js:51:25)
    at Shard.emit (events.js:193:13)
    at Shard.EventEmitter.emit (domain.js:481:20)
```
I was not able to produce a simple script that reproduce this error (I don't know exactly which condition trigger this bug), but I'm able to reproduce it anytime in my code.

From what I can see on the stacktrace, the EventEmitter instance which produce this warning is internal to node. The listeners seem to be registered during a `console.log()` call.

**Comment by ollisal** [comment]
Ditto, on Node.js v12.0.0.

**Comment by Zoddo** [comment]
I don't know why this issue was moved there. It's a bug report, not an help request.

**Comment by gireeshpunathil** [comment]
@Zoddo - can you please share your test case?

**Comment by Zoddo** [comment]
As said, I'm not able to produce a simple test case (this bug is probably triggered under a specific conditions). But the EventEmitter generating this error is internal to node (just take a look at the stack trace).

**Comment by zetos** [comment]
Had the same issue when i was using `node v12.9.0` it was solved when i upgraded to `node v12.10.0`.

**Comment by gianpaj** [comment]
I'm getting this issue on OSX `node v13.5.0` when running:
```
npx npkill
```

```
(node:11672) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [Socket]. Use emitter.setMaxListeners() to increase limitess
```

**Comment by PoojaDurgad** [comment]
@Zoddo , is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
