### ISSUE TITLE
npm does not support Node.js v10.15.2

### ISSUE THREAD

**Issue by aguilared** [nodejs/help#1877]
info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.15.2
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'eslint' ]
7 info using npm@5.8.0
8 info using node@v10.15.2
9 verbose npm-session 64c32217b44a7927

**Comment by yathamravali** [comment]
@aguilared 

It looks like current installed `npm` is not compatible with Node.js version you are using. You’ll probably need to update your `npm` using `npm install npm@latest -g`. And looks like everything fine despite of warnings.

**Comment by aguilared** [comment]
Ready, Thanks yathamravali, execute:
npm install npm@latest -g

$ npm -v
6.9.0

**Comment by aguilared** [comment]
Ready, Thanks yathamravali, execute:
npm install npm@latest -g

$ npm -v
6.9.0

**Comment by rafaelvalentimzup** [comment]
I'd suggest to try install it from source by:
curl https://www.npmjs.com/install.sh | sudo sh

**Comment by Daniel-Griffiths** [comment]
Thanks! yathamravali's suggestion worked for me :smile:

**Comment by ferenczy** [comment]
I have installed node.js and npm on Debian 10 without explicitly specifying the version:

    apt-get install nodejs
    apt-get install npm

I ended up with the node.js version `10.15.2` and npm `5.8.0`. There are no other versions of either of two in Debian 10's repository anyway.

But I'm getting the "does not support" error now. I can probably somehow manage to hack a different version of one of those things into there I guess, but really Debian maintainers picked incompatible versions into their distribution?

**Comment by Pair5Studios** [comment]
@ferenczy I had the same problem in Ubuntu 19.04.  However after reloading my shell, it seems the solution suggested by @aguilared worked

**Comment by sitiojcb** [comment]
Thanks rafaelvalentimzup, that worked for me. I'm on MXLinux 19.

**Comment by matinwd** [comment]
@Pair5Studios i have the same problem on ubuntu 19.04. Did u find any way ?

**Comment by thesomeexp** [comment]
> @Pair5Studios i have the same problem on ubuntu 19.04. Did u find any way ?

i have the same problem on ubuntu 19.04. Did u find any way ?

> I have installed node.js and npm on Debian 10 without explicitly specifying the version:
> 
> ```
> apt-get install nodejs
> apt-get install npm
> ```
> 
> I ended up with the node.js version `10.15.2` and npm `5.8.0`. There are no other versions of either of two in Debian 10's repository anyway.
> 
> But I'm getting the "does not support" error now. I can probably somehow manage to hack a different version of one of those things into there I guess, but really Debian maintainers picked incompatible versions into their distribution?

i have the same problem on Debian 10.1  Did u find any way ?

**Comment by nunoguerreiro** [comment]
> I'd suggest to try install it from source by:
> curl https://www.npmjs.com/install.sh | sudo sh

worked for me.

**Comment by alisonjo315** [comment]
Me too on ubuntu 19.04 (originally installed both via apt, without any version specifications) -- same "does not support" error.  The suggestion from @yathamravali (make npm update itself to the latest version) cleared the error from me.  Thanks, all!

**Comment by ggichure** [comment]
> I'd suggest to try install it from source by:
> curl https://www.npmjs.com/install.sh | sudo sh

shows it worked ,but npm -v still is at 5.8.0 .

**Comment by HenGrP** [comment]
> Ready, Thanks yathamravali, execute:
> npm install npm@latest -g
> 
> $ npm -v
> 6.9.0

Don't forget to close the shell and open it again

**Comment by zurieelrdz** [comment]
> @aguilared
> 
> It looks like current installed `npm` is not compatible with Node.js version you are using. You’ll probably need to update your `npm` using `npm install npm@latest -g`. And looks like everything fine despite of warnings.

Still working. ty

**Comment by david8dixon** [comment]
> @ferenczy I had the same problem in Ubuntu 19.04. However after reloading my shell, it seems the solution suggested by @aguilared worked

Same exact result for me on 19.0.4.

**Comment by ArnoYan** [comment]
> I'd suggest to try install it from source by:
> curl https://www.npmjs.com/install.sh | sudo sh

Thanks, this helped me a lot!

**Comment by gabrielamorimpy** [comment]
> I'd suggest to try install it from source by:
> curl https://www.npmjs.com/install.sh | sudo sh

Thanks! Worked for me.

**Comment by snxiong** [comment]
> I'd suggest to try install it from source by:
curl https://www.npmjs.com/install.sh | sudo sh
This worked, using ubuntu 19.10
using npm@5.8.0
using node@v10.15.2

Thank you!!!!!!!! This problem has been driving me crazy for the past week.

**Comment by pomil-1969** [comment]
> I'd suggest to try install it from source by:
> curl https://www.npmjs.com/install.sh | sudo sh

upgraded to 6.13.4

**Comment by caco13** [comment]
> @ferenczy I had the same problem in Ubuntu 19.04. However after reloading my shell, it seems the solution suggested by @aguilared worked

Installed from Debian 10 global repositories. Started a new shell and the warings has gone.

**Comment by mrsetiawan** [comment]
not working for win 10

**Comment by pierre89** [comment]
I'd suggest to try install it from source by:
curl https://www.npmjs.com/install.sh | sudo sh
Thanks very much this works for me ubuntu 19.10

**Comment by antoniotrkdz** [comment]
On Debian 10 (or Devuan 3) this warn messages issue can be resolved also by apt pinning:
add `sid` (or `ceres`) sources to `/etc/apt/sources.list` and then create a file in `/etc/apt/preferences.d/` (you can name it as you please, but giving it a sensible name such as `npm-sid` [or `npm-ceres`] it is not a bad idea).
Edit it:
```sh
# This is needed to prevent your install to become
# a buster/sid (beowulf/ceres) Frankestein. 
Package: *
Pin: release n=sid #or n=ceres
Pin-Priority: -1 
 
# Your mileage may vary here...
# Try to comment (temporarily) the rule above to check the dependencies needed by
# 'apt-get install npm' and add them one by one, it shouldn't be a long list...
Package: npm node-define-properties node-npm-package-arg node-psl libjs-psl
Pin: release n=sid #or n=ceres
Pin-Priority: 500
```
Then `apt-get install npm` should give you a later and warn-free version of npm.
Please note that mixing stable and unstable releases is generally considered a bad practice.
Having said that, in this particular case an inspection of the dependencies being installed revealed that it is (hopefully) most likely to be trouble-free, hence this post.

**Comment by richRemer** [comment]
I have been using Node 10 with npm 5 without any trouble for some time.  Can anyone point out what exactly does not work?

**Comment by maidmeow4** [comment]
Recently I ran into this problem, and I just discovered there is a compatible version in `debian-backports`.
In my case I can use command `apt install node-npm-package-arg=6.1.1-1~bpo10+1` and then `apt install npm=6.14.3+ds-1~bpo10+1`, after that the `npm` will be upgraded to a warning-free version for Node.js v10.
p.s. : `node-npm-package-arg` version 6.1.1-1~bpo10+1 is a required dependency by the newer version of `npm`.
p.s.s : check [HERE](https://www.debian.org/distrib/packages) for latest `npm` and related deb packages version numbers.

**Comment by khaledBou** [comment]
for me i remove yarn and i  execute react-native init myProject
This command install automatically a new version of yarn and it works for me

**Comment by unclehowell** [comment]
> I'd suggest to try install it from source by:
> curl https://www.npmjs.com/install.sh | sudo sh

I had to wget the install.sh and run `sudo sh ./install.sh` but it worked. Good drills

**Comment by Issam-AB** [comment]
> I'd suggest to try install it from source by:
> curl https://www.npmjs.com/install.sh | sudo sh

Thanks very much this working for win 10

**Comment by leonardomarcao** [comment]
> > I'd suggest to try install it from source by:
> > curl https://www.npmjs.com/install.sh | sudo sh
> 
> worked for me.

this worked for me. thanks.

**Comment by Insistem** [comment]
install node package from https://nodejs.org, then reinstall it's pkg package!

**Comment by izvadim** [comment]
thank you very much!

**Comment by sawan5216977** [comment]
Error: Node.js v10.0.0 is a minimum requirement. To learn about legacy version support visit: https://github.com/googleapis/google-cloud-node#supported-nodejs-versions
    at new GrpcClient (/srv/node_modules/google-gax/build/src/grpc.js:62:19)
    at new FirestoreClient (/srv/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:98:25)
    at ClientPool.Firestore._clientPool.pool_1.ClientPool [as clientFactory] (/srv/node_modules/@google-cloud/firestore/build/src/index.js:370:26)
    at ClientPool.acquire (/srv/node_modules/@google-cloud/firestore/build/src/pool.js:88:35)
    at ClientPool.run (/srv/node_modules/@google-cloud/firestore/build/src/pool.js:165:29)
    at _retry (/srv/node_modules/@google-cloud/firestore/build/src/index.js:1112:30)
    at Firestore._retry (/srv/node_modules/@google-cloud/firestore/build/src/index.js:978:30)
    at <anonymous>
Caused by: Error
    at Firestore.getAll (/srv/node_modules/@google-cloud/firestore/build/src/index.js:755:23)
    at DocumentReference.get (/srv/node_modules/@google-cloud/firestore/build/src/reference.js:201:32)
    at exports.sendNotification.functions.firestore.document.onWrite (/srv/index.js:14:112)
    at cloudFunction (/srv/node_modules/firebase-functions/lib/cloud-functions.js:134:23)
    at /worker/worker.js:825:24
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

I am getting this error every time I try to send the notification, anyone please help me. It is asking for min. version to be 10 but from this 10 version firebase is charging fees. Is there any way to use cloud functions for free.


The cloud function that I wrote is this please tell me how to solve this error.


'use-strict'

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

exports.sendNotification = functions.firestore.document("Users/{user_id}/Notifications/{notification_id}").onWrite((change, context) =>{
    
    const user_id = context.params.user_id;
    const notification_id = context.params.notification_id;

    console.log("User Id : " + user_id + " Notification Id : " + notification_id);

    return admin.firestore().collection("Users").doc(user_id).collection("Notifications").doc(notification_id).get().then((query_result) => {

        const from_user_id = query_result.data().from;

        const from_data = admin.firestore.collection("Users").doc(from_user_id).get();
        const to_data = admin.firestore.collection("Users").doc(user_id).get();

        return Promise.all([from_data, to_data]);

    }).then((result) => {

        const from_name = result[0].data().name;
        const to_name = result[1].data().name;

        return console.log("FROM : " + from_name + " TO : " + to_name);

    }).catch((error) => {
        console.error(error);
        return null;
      });

});

**Comment by evil-shrike** [comment]
Hi.
what to do on Win (not WSL)?
```
C:\Work\>npm i npm -g
npm WARN npm npm does not support Node.js v15.3.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shrike\AppData\Roaming\npm-cache\_logs\2020-12-08T17_00_02_716Z-debug.log
```

```
C:\Work\>npm --version
6.7.0

C:\Work\>node --version
v15.3.0
```

**Comment by bigal2112** [comment]
rafaelvalentimzup - your option still worked perfectly on Debian 10.  Thanks.

**Comment by 96rafi** [comment]
I am trying to buy a host for my website that is built using node js and the hosting provider told me that the only version on node js that they provide is Node.js (v12.4.x). and I an using the following npm packages in my project(@sendgrid/mail,body-parser,connect-flash,cookie-session,dotenv,express,express-handlebars,express-session,file-saver,handlebars,method-override,MySQL) and the devDependencies i am using (cross-env).will the version work fine with my website or will be problems?

**Comment by mauricio-toledo-ti** [comment]
> Recently I ran into this problem, and I just discovered there is a compatible version in `debian-backports`.
> In my case I can use command `apt install node-npm-package-arg=6.1.1-1~bpo10+1` and then `apt install npm=6.14.3+ds-1~bpo10+1`, after that the `npm` will be upgraded to a warning-free version for Node.js v10.
> p.s. : `node-npm-package-arg` version 6.1.1-1~bpo10+1 is a required dependency for the newer version of `npm`.
> p.s.s : check [HERE](https://www.debian.org/distrib/packages) for latest `npm` and related deb packages version numbers.

E: Version '6.14.3+ds-1~bpo10+1' for 'npm' was not found

**Comment by csdal** [comment]
None of the above solutions work for me. This work:

```
# Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Follow this [link](https://github.com/nodesource/distributions/blob/master/README.md#deb).

**Comment by Qasem-moh** [comment]
# Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
it's work , and thank you @csdal

**Comment by Qasem-moh** [comment]
> None of the above solutions work for me. This work:
> 
> ```
> # Using Ubuntu
> curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> Follow this [link](https://github.com/nodesource/distributions/blob/master/README.md#deb).

thank you

**Comment by donPabloNow** [comment]
> 

Great Stuff, this worked for me - big time hair saver haha

**Comment by InspireGeo** [comment]
> # Using Ubuntu
> 
> curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - sudo apt-get install -y nodejs it's work , and thank you @csdal

only that worked for me... many thanx

**Comment by InspireGeo** [comment]
> None of the above solutions work for me. This work:
> 
> ```
> # Using Ubuntu
> curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> Follow this [link](https://github.com/nodesource/distributions/blob/master/README.md#deb).

+1

**Comment by LwandaMagere** [comment]
It worked for me too thank you inspireGeo

**Comment by Insistem** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vit0rr** [comment]
I achieved fix my issue with this doc https://nodejs.org/en/download/package-manager/

**Comment by elvisef** [comment]
> None of the above solutions work for me. This work:
> 
> ```
> # Using Ubuntu
> curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> Follow this [link](https://github.com/nodesource/distributions/blob/master/README.md#deb).

The only that **worked** for my Debian 10.x, without errors (as on the screenshot attached)
![2022-01-02_23-32](https://user-images.githubusercontent.com/25976749/147891116-dfc36d34-f8c9-4080-88ff-f5be2a3b1c53.png)

Bravo ! Thanks !

**Comment by rsa408** [comment]
I have an issue :

```
OS : windows 7 x64

C:\>node --version
v15.8.0
C:\>npm version
npm does not support Node.js v15.8.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
npm does not support Node.js v15.8.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
{
  npm: '8.3.0',
  node: '15.8.0',
  v8: '8.6.395.17-node.23',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}
```

```
C:\Program Files\nodejs>npm install npm@latest -g
npm does not support Node.js v15.8.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
npm does not support Node.js v15.8.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@8.4.0
npm ERR! notsup Not compatible with your version of node/npm: npm@8.4.0
npm ERR! notsup Required: {"node":"^12.13.0 || ^14.15.0 || >=16"}
npm ERR! notsup Actual:   {"npm":"8.3.0","node":"v15.8.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxx\AppData\Local\npm-cache\_logs\2022-01-28T14_14_59_094Z-debug-0.log
```

**Comment by Bitharis** [comment]
> win 10

if you run docker on windows 10 i found that setting the build kit to false solved my problem

![image](https://user-images.githubusercontent.com/22401199/154797051-34b0b150-d596-4911-80f4-bd13e27927a8.png)

**Comment by mircobabini** [comment]
**For Mac Users.**

First of all check which node provider you are using `$ which node`

**NVM**
```
$ nvm install node --reinstall-packages-from=node
```

**BREW**
```
$ brew update
$ brew upgrade node
```

**Comment by A7Lavinraj** [comment]
> npm install npm@latest -g

thanks bro you are awesome.

**Comment by Insistem** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Avinashbawage** [comment]
npm uninstall -g create-react-app
yarn global remove create-react-app
npx create-react-app my-app
yarn create react-app my-app

**Comment by Insistem** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by aloklearning** [comment]
> **BREW**
> 
> ```
> $ brew update
> $ brew upgrade node
> ```

This worked for me as I had the latest node installed, however, it was not being reflected unless I used `brew` command.

**Comment by Insistem** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
