### ISSUE TITLE
Node.js C++ Native Addon - calling setlocale

### ISSUE THREAD

**Issue by JCMais** [nodejs/help#1878]
* **Node.js Version**: 10
* **OS**: whatever
* **Scope (install, code, runtime, meta, other?)**: native addon

My addon has some dependencies that require a valid locale being set (to be more specific, `libidn2` which depends on `libunistring`), however looks like Node.js does not set any locale, I found no calls to `setlocale`.

What would be recommended action? Should I just call `setlocale` during addon initialization and be done with it?

I've tested that and looks like it does work, but I don't know if that is the correct step. I imagine this can cause undesirable side effects on the addon users.

Other options:

* build a small addon that acts as a wrapper around `setlocale`, and leave the responsibility of calling it to the user.
* verify if no locale was set, and retrieve the environment locale (using `setlocale(AC_ALL, "")`) before calls that need one, after those calls revert it back to the previous default locale.

**Comment by gireeshpunathil** [comment]
@JCMais - IMO both the options look good, but I am more biased towards first option, as it is more explicit. If we are going with the second, it is worthwhile to document clearly what your module is going to do with the locale, under the cover.

Hope this helps!

**Comment by JCMais** [comment]
@gireeshpunathil thanks for the answer!

For now I'm going with the second one since it's simpler. I will allow a flag to disable this behavior and leave it documented on the project README.

Later I will see if I can create an addon to act as a wrapper to setlocale, and then leave the responsibility upon the user. I saw there is already a wrapper here, but it's outdated: https://github.com/tokuhirom/node-setlocale/blob/master/setlocale.cc

**Comment by gireeshpunathil** [comment]
I am closing this as answered, please re-open if that is not the case.
