### ISSUE TITLE
Node server crashes when the version number is changed in package.json

### ISSUE THREAD

**Issue by cronus00101110** [nodejs/help#1879]
* **Version**:  v11.12.0
* **Platform**: Windows 10 64-bit
* **Subsystem**: 10.0.18362 Build 18362

My node server is running on Heroku and it crashes after changing the version number from "1.0.2" to "1.1"  in package.json file.

> 2019-04-23T11:30:18.174854+00:00 heroku[web.1]: State changed from crashed to starting
> 2019-04-23T11:30:20.062339+00:00 heroku[web.1]: Starting process with command `npm start`
> 2019-04-23T11:30:21.766443+00:00 heroku[web.1]: State changed from starting to crashed
> 2019-04-23T11:30:21.745413+00:00 heroku[web.1]: Process exited with status 1
> 2019-04-23T11:30:21.684827+00:00 app[web.1]: npm ERR! Invalid version: "1.1"
> 2019-04-23T11:30:21.691517+00:00 app[web.1]:
> 2019-04-23T11:30:21.691757+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
> 2019-04-23T11:30:21.691831+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-04-23T11_30_21_686Z-debug.log

Why is this the case? Is it not possible to change the package version number to a number I like?

**Comment by addaleax** [comment]
@cronus00101110 That looks like an error from npm, not from node – node doesn’t deal with package versions. If you want to raise an issue about npm, https://npm.community/ is the right place for that.

That being said, npm generally expects version numbers to follow [Semantic Versioning](https://semver.org/), so `1.1.0` would be valid but `1.1` wouldn’t be. I don’t expect them to change their usage of semver.

**Comment by cronus00101110** [comment]
> @cronus00101110 That looks like an error from npm, not from node – node doesn’t deal with package versions. If you want to raise an issue about npm, https://npm.community/ is the right place for that.
> 
> That being said, npm generally expects version numbers to follow [Semantic Versioning](https://semver.org/), so `1.1.0` would be valid but `1.1` wouldn’t be. I don’t expect them to change their usage of semver.

Thanks for the information. I like semantic versioning too(and using it in some docs) but I didn't really expect to see my application crash because of just a version number. Anyway, thanks again.
