### ISSUE TITLE
This is probably not a problem with npm. There is likely additional logging output above.

### ISSUE THREAD

**Issue by PrashanthAdurugatla** [nodejs/help#1880]
* **OS**: windows 10

I'm using node version ( v10.15.3) and npm version (6.4.1) and I tried to create a simple react-app by using the following commands:

1. npx create-react-app <my-app name>
2. cd <my-app-name>
3. npm start

I had no issues in creating an app and my app got created sucessfully. 

**_Success! Created myapp at C:\Users\padur\Desktop\myapp
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd myapp
  npm start

Happy hacking!_**

But when I tried to run my start script I'm facing an error 

![bug3](https://user-images.githubusercontent.com/33069358/56632640-90b78680-660f-11e9-8872-7fce2b8e3bac.JPG)

**Comment by gireeshpunathil** [comment]
`ENOENT` generally means the script was unable to find the target executable path that was specified. Can you please provide the `debug.log` that is mentioned as generated, at the the bottom of your console screen shot? thanks!

**Comment by wide4head** [comment]
@PrashanthAdurugatla A possible solution to the error

> Error: spawn cmd ENOENT

is detailed at 
https://stackoverflow.com/questions/28624686/get-spawn-cmd-enoent-when-try-to-build-cordova-application-event-js85

**Comment by davisjam** [comment]
@PrashanthAdurugatla Is this still an issue? If not, can you close it?

**Comment by rahmaaa123** [comment]
what was the solution for this ??

**Comment by vizz1234** [comment]
add C:\Windows\System32 to your path environment variable

**Comment by RezaulKarimSadi** [comment]
i am fialed to create and ran react app,,i dont undersatnd how to solve this error..
![React](https://user-images.githubusercontent.com/32489165/65837207-7746f480-e2a9-11e9-91c8-9230da55fa81.PNG)

**Comment by VicRmzChz** [comment]
The solution for me was that I close the terminal with out first ''npm eject' put on the terminal "npm eject" after that "npm start" post if it work

**Comment by RezaulKarimSadi** [comment]
but still dont work,,

**Comment by koualsky** [comment]
I had the same problem on Ubuntu: 'sudo npm start'

**Comment by Lugaga** [comment]
> I had the same problem on Ubuntu: 'sudo npm start'
Thank you. Worked Like charm!

**Comment by wedwin53** [comment]
Here the solution https://medium.com/@devmrin/complete-how-to-create-react-native-app-with-genymotion-android-emulator-on-windows-10-in-10-3834fd90b074

**Comment by ralzoubi** [comment]
Hi I tried the above solutions but none of them work. Any other suggestions please?

**Comment by lapii-ui** [comment]
i try it all but still not work any suggestions?

**Comment by kaveh1985** [comment]
> i try it all but still not work any suggestions?

I think you need to kill the port and it would probably work, i did it and it worked!

**Comment by HimanshuChhikara** [comment]
> > I had the same problem on Ubuntu: 'sudo npm start'
> > Thank you. Worked Like charm!

Thanks worked for me

**Comment by will0225** [comment]
I am getting same issue
My react version 6.12.0
OS: window 10

error:

![image](https://user-images.githubusercontent.com/51754234/75005285-e61b2900-54a8-11ea-87e4-66058db4224a.png)
Can you help me?

**Comment by mahdisalmanzade** [comment]
@will0225 
i have the same issue as you i think this problem is for windows!
did you fixed your issue?

**Comment by Sachin-7409** [comment]
> what was the solution for this ??

Delete your package-lock.json file and node_modules folder. Then do "npm cache clean"
and run this command npm install 
and now start your npm project, I hope this solution is work.

**Comment by kritarth2121** [comment]
nothong worked ,please someone help

**Comment by nidesh1997** [comment]
@will0225 
Iam getting the same error!!
We have fixed your problem ah..??

**Comment by will0225** [comment]
Hi
Yes
I have fixed this problem
You need to consider your code first

**Comment by Chamithfernando** [comment]
> add C:\Windows\System32 to your path environment variable

thank you very much error solved

**Comment by debora-dcs** [comment]
> I had the same problem on Ubuntu: 'sudo npm start'
@koualsky 
You saved my life. Thank you!

**Comment by Chamithfernando** [comment]
👍👍👍

**Comment by nithinkjoy-tech** [comment]
https://youtu.be/jChDhP_G4F4 this may work for some users

**Comment by yeji0120** [comment]
Guys... Nothing works..

**Comment by slavrom** [comment]
> I had the same problem on Ubuntu: 'sudo npm start'

I was trying to solve it 2 days... and I was so hard laughing when it workd with just adding sudo...thx man !!!

**Comment by Chamithfernando** [comment]
🙂🙂🙂

**Comment by mdtowhid** [comment]
i have tried all of the solutions above! but still not working. Please help me out

**Comment by kristinaiv992** [comment]
same problem

**Comment by will0225** [comment]
Hi
You exactly have problem with your code.
You environment variable is correct now.
Please consider with the code

**Comment by kristinaiv992** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kate_\AppData\Roaming\npm-cache\_logs\2020-04-27T21_44_07_307Z-debug.log

**Comment by will0225** [comment]
Your code logic have error now

**Comment by will0225** [comment]
Please point to task_queues.js:84 line

**Comment by kristinaiv992** [comment]
Thanks a lot @will0225 . This tutorial https://www.youtube.com/watch?v=3FKMOxz05Tg helped me with my npm installation which I did it again. 
I had no clue what the problem was lol, hope will help 2 other beginners like me.
Happy coding folks! xx

**Comment by hamzasiraj** [comment]
> same problem...how to do this?
> add C:\Windows\System32 to your path environment variable???

How to add environment variable?

**Comment by hyped0001** [comment]
_Add this to the package.json:_
`
"scripts": {
       "start": "node ."
}
`

_When you want to run the script do:_
`npm run start`

**Comment by khadafirp** [comment]
I have problem with AsyncStorage and react-native-shared-preferences libraries, and check in package.json, and remove those libraries and the restart your project.

it works for me

**Comment by SHREYASH-MUKESH** [comment]
> Here the solution https://medium.com/@devmrin/complete-how-to-create-react-native-app-with-genymotion-android-emulator-on-windows-10-in-10-3834fd90b074

working solution thanks

**Comment by arnaldoquagliato** [comment]
> I am getting same issue
> My react version 6.12.0
> OS: window 10
> 
> error:
> 
> ![image](https://user-images.githubusercontent.com/51754234/75005285-e61b2900-54a8-11ea-87e4-66058db4224a.png)
> Can you help me?

Dude I have that kind of error happening to me right now, pls help me

**Comment by Chamithfernando** [comment]
Did you try import react project

**Comment by DalalMostafa** [comment]
I had the same error, also I tried all solution and nothing happen 
anyone can help.. 

![error](https://user-images.githubusercontent.com/65855872/82755546-dc250100-9ddc-11ea-8b89-d5b2ff31fae4.JPG)
` at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47`

**Comment by DalalMostafa** [comment]
I had the same error, also I tried all solution and nothing happen
anyone can help..

![error1](https://user-images.githubusercontent.com/65855872/82755606-5786b280-9ddd-11ea-9ddd-9671506fa57b.JPG)
`at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47`
`
![image](https://user-images.githubusercontent.com/65855872/82755594-40e05b80-9ddd-11ea-9b2b-8fdec875960b.png)
`

**Comment by MohammadShakilCSE** [comment]
C:\Users\Shakil Talukder\Desktop\wabpackB4>npm run bulid

> wabpackB4@1.0.0 bulid C:\Users\Shakil Talukder\Desktop\wabpackB4
> webpack

(node:14656) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Chunk.js:866
                throw new Error(
                ^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Chunk.js:866:9)
    at C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\extract-text-webpack-plugin\dist\index.js:176:48
    at Array.forEach (<anonymous>)
    at C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\extract-text-webpack-plugin\dist\index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Compilation.js:1342:27)
    at C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Compiler.js:675:18
    at C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Compilation.js:1253:28)
    at C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Compiler.js:672:17
    at eval (eval at create (C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Compilation.js:1185:12
    at C:\Users\Shakil Talukder\Desktop\wabpackB4\node_modules\webpack\lib\Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:76:11)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wabpackB4@1.0.0 bulid: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wabpackB4@1.0.0 bulid script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shakil Talukder\AppData\Roaming\npm-cache\_logs\2020-06-07T06_30_45_877Z-debug.log

**Comment by MohammadShakilCSE** [comment]
why show this problem

**Comment by Sachin-7409** [comment]
step:1 Delete your package-lock.json file and node_modules folder. Then do npm cache clean

step:2 npm install

I think this solves your problem

**Comment by ashutoshbhardwaj16** [comment]
Use **npm eject** to clear the stack memory of npm( this issue is due to memory) and then again run it

**Comment by LexusLXR** [comment]
Delete your package-lock.json file and node_modules folder where i can found this folder

**Comment by tanvirch0750** [comment]
> very

Thank you, its work for me.

**Comment by mnzm** [comment]
I run "npm start" on powershell instead cmd
work for me!!!!!

**Comment by sangeethamohandas** [comment]
VS 
![1 8](https://user-images.githubusercontent.com/62987357/89917831-e950cf80-dc16-11ea-9b0f-5c6c334716c6.png)
![1 9](https://user-images.githubusercontent.com/62987357/89917845-eeae1a00-dc16-11ea-8e83-27781d442167.png)

Version: 1.47.3 (user setup)
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

how to solve this? anybody please help?
it was fine till last run

**Comment by karuna-keshar** [comment]
> > what was the solution for this ??
> 
> Delete your package-lock.json file and node_modules folder. Then do "npm cache clean"
> and run this command npm install
> and now start your npm project, I hope this solution is work.

not working for me !

**Comment by bruno-silva5** [comment]
I just deleted the entire project, then I made a 

`git clone ...`
`npm install`

and now everything works fine

**Comment by webDyatan** [comment]
### ERROR please help .
![Screenshot (88)](https://user-images.githubusercontent.com/56783136/94342270-a2376600-002d-11eb-9e0f-90f1348dd0f9.png)

**Comment by webDyatan** [comment]
> > I am getting same issue
> > My react version 6.12.0
> > OS: window 10
> > error:
> > ![image](https://user-images.githubusercontent.com/51754234/75005285-e61b2900-54a8-11ea-87e4-66058db4224a.png)
> > Can you help me?
> 
> Dude I have that kind of error happening to me right now, pls help me


>###  Hey Pal! .. i've got the same error .
> You can try these steps..

**1.go to the file:
node_modules/parallelshell/index.js:105

2.Then change this line:
cwd: process.versions.node < '8.0.0' ? process.cwd : process.cwd(),

3.To this:
cwd: parseInt(process.versions.node) < 8 ? process.cwd : process.cwd(),


here's the stackoverflow link:
https://stackoverflow.com/questions/53461626/problem-running-parallelshell-nodejs-script**  


> This worked For me!!

**Comment by oybek9508** [comment]
I had the same problem, and I fixed it by running 'npm audit fix' and then 'npm start' worked perfectly

**Comment by hariasimov21** [comment]
> > I had the same problem on Ubuntu: 'sudo npm start'
> > Thank you. Worked Like charm!

Thanks!!!

**Comment by argorninc** [comment]
> I had the same problem on Ubuntu: 'sudo npm start'

Thanks so much. works like magic

**Comment by shrutik27** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle backend@1.0.0~prestart: backend@1.0.0
6 info lifecycle backend@1.0.0~start: backend@1.0.0
7 verbose lifecycle backend@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle backend@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Lenovo\Desktop\3-D-Globe-master\backend\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Users\Lenovo\Desktop\Scripts\;C:\Users\Lenovo\Desktop\;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;C:\Users\Lenovo\.windows-build-tools\python27\;C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\python.exe;C:\Users\Lenovo\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.8;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.4\bin;C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Python 3.8;C:\Users\Lenovo\python;C:\Users\Lenovo\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.7;C:\Users\Lenovo\AppData\Local\GitHubDesktop\bin;C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Lenovo\AppData\Roaming\npm;C:\Users\Lenovo\AppData\Local\Yarn\bin;D:\heroku\bin
9 verbose lifecycle backend@1.0.0~start: CWD: C:\Users\Lenovo\Desktop\3-D-Globe-master\backend
10 silly lifecycle backend@1.0.0~start: Args: [ '/d /s /c', 'node ./backend/index.js' ]
11 silly lifecycle backend@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle backend@1.0.0~start: Failed to exec start script
13 verbose stack Error: backend@1.0.0 start: `node ./backend/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid backend@1.0.0
15 verbose cwd C:\Users\Lenovo\Desktop\3-D-Globe-master\backend
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error backend@1.0.0 start: `node ./backend/index.js`
22 error Exit status 1
23 error Failed at the backend@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


This is my debug file can someone help me to find error i think i have 2 folder frontend and backend so this might create 2 output
https://github.com/shrutik27/startupscrap - link to code

**Comment by EmmanuelTheCoder** [comment]
Apparently, this error is still a thing. Has anyone solved it? 
Help!!!

**Comment by EugeneGohh** [comment]
Same problem here has anyone solved it?

**Comment by shrutik27** [comment]
I have solved the error by making 2 server on for frontend another for backend in my project this was appearing due to parcel i was having backend script and frontend script separately

**Comment by equationalapplications** [comment]
> > Delete your package-lock.json file and node_modules folder. Then do "npm cache clean"
> > and run this command npm install
> > and now start your npm project, I hope this solution is work.

How to completely remove and reinstall node.js on Windows 10
https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows
https://docs.microsoft.com/en-us/windows/nodejs/setup-on-windows

**Comment by sanchita2017** [comment]
I tried all the steps. Server is running if I make any new react app. But, it won't open for the existing project.

**Comment by kamaladebayo** [comment]
I changed my buildpack on heroku and it works!

**Comment by ayyappamalla123** [comment]
> i am fialed to create and ran react app,,i dont undersatnd how to solve this error..
> ![React](https://user-images.githubusercontent.com/32489165/65837207-7746f480-e2a9-11e9-91c8-9230da55fa81.PNG)

use --silent argument for your command

**Comment by GhislainS** [comment]
> @will0225
> i have the same issue as you i think this problem is for windows!
> did you fixed your issue?

Hello  Sir,  having the same problem . Please can you tell me how you have fixed it. thanks

**Comment by shilpatailor** [comment]
Install NPM and start NPM then showing an error and npm is not start. http://localhost:3030/ not worked.

**Comment by PaiteIsaac** [comment]
> Hi
> Yes
> I have fixed this problem
> You need to consider your code first

**Comment by ELKAAKOUZ** [comment]
you can solve this problem by creating afile in src and name this file=>   .env
and in the .env file put this line of code=>     SKIP_PREFLIGHT_CHECK=true;
and run npm start and it will work

**Comment by Musaif786** [comment]
f

**Comment by Musaif786** [comment]
PS E:\for react\Firebase\firebase\my-firebase> npm run build         ion complete!
                       e\firebase\my-firebase
> my-firebase@0.1.0 build E:\for react\Firebase\firebase\my-firebase 
> react-scripts build  

E:\for react\Firebase\firebase\my-firebase\node_modules\react-scripts\config\webpack.config.js:664
        new MiniCssExtractPlugin({
        ^

TypeError: MiniCssExtractPlugin is not a constructor
    at module.exports (E:\for react\Firebase\firebase\my-firebase\node_modules\react-scripts\config\webpack.config.js:664:9)
    at Object.<anonymous> (E:\for react\Firebase\firebase\my-firebase\node_modules\react-scripts\scripts\build.js:58:16)
    at Module._compile 
(internal/modules/cjs/loader.js:1085:14)      
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) 
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)     
    at internal/main/run_main_module.js:17:47 
npm ERR! code ELIFECYCLE
npm ERR! errno 1       
npm ERR! my-firebase@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 
my-firebase@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output 
above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\it-fks\AppData\Roaming\npm-cache\_logs\2022-01-15T19_48_23_393Z-debug.loglog                    e\firebase\my-firebase
how to fix this error plzz help me guys i tried all the given trikes like 
npm update ,
clear cache and deleted the modules also and 
json files also reinstalled but still problem didnt solved pls help me

**Comment by evie-adenoyin** [comment]
i went to this directory on my PC C:\Users\HP and then i saw that node_module was installed in that directory. all i did was cut and pasted the node_module in my projects directory. My project directory was also in C:\Users\HP on my PC... so check if you have node_module in your projects directory. This helped me.

**Comment by ELKAAKOUZ** [comment]
Run command => npm install
It will set the node modules and acctivate it
Dont cut and paste node modules

Ekong, Emmanuel ***@***.***> schrieb am Fr. 21. Jan. 2022 um
12:16:

**Comment by ShashankKrM** [comment]
> i went to this directory on my PC C:\Users\HP and then i saw that node_module was installed in that directory. all i did was cut and pasted the node_module in my projects directory. My project directory was also in C:\Users\HP on my PC... so check if you have node_module in your projects directory. This helped me.

Never ever cut/paste node module folder. Always install this folder using 'npm install' command and not any other way around. 

Cup/Paste may work for you in some small folder case, but will always cause problems if the project is large.

**Comment by sameerwatts** [comment]
Use the latest node version. Node version should be 14 or above 14.

**Comment by will0225** [comment]
:)

**Comment by owaisniaz** [comment]
> I faced this error when I was on the node version 14.17.0 and I changed my node v16.16.0 and it's wor fine

**Comment by owaisniaz** [comment]
> > I faced this error when I was on the node version 14.17.0 and I changed my node v16.16.0 and it's working fine.
