### ISSUE TITLE
process.env.PWD is not set on Windows 10 when using powershell

### ISSUE THREAD

**Issue by Raiondesu** [nodejs/help#1881]
* **Version**: `v8.12.0`
* **Platform**: Windows 10 Education 1803; Build `17134.706`
* **Subsystem**: Process

## Description

`process.env.PWD` logs `undefined` on Windows 10 PC using **batch/powershell**. Issue does **not** seem to be present when using **bash** on windows (either GitBash or using an Ubuntu subsystem).

## Reproduction

Just do
```ps
> node
> process.env.PWD
```
( yields `undefined` )
on a Windows 10 PC.

If cannot reproduce - proceed to `npm i https://github.com/ke-mantha/mantha.git#test` in an empty directory.

**Comment by addaleax** [comment]
@Raiondesu I’ve moved this issue to nodejs/help, that should be a good place for this – it doesn’t appear to be an issue with node itself, though.

> And, btw, aren't some env variables set directly by node and npm?

Some are used internally by node (e.g. for communicating with child processes), but generally, node doesn’t set generic env vars. npm does so, a lot – mostly to communicate the current npm config with processes – but it’s a completely different piece of software, it just happens to be shipped together with node.

> And, btw, aren't some env variables set directly by node and npm?

I mean, you an always include `process.env.PWD = process.cwd();` in your code? That’s the most reliable thing to do anyway.

**Comment by Raiondesu** [comment]
@addaleax, thank you very much for moving this!

PWD and cwd sometimes seem to be different (as stated [here](https://stackoverflow.com/questions/31414852/process-env-pwd-vs-process-cwd)): `PWD` consistently points to a folder with `node_modules` (project directory), whereas cwd() points to directory from which the command was executed. Even though, these things often mean the same, sometimes they're not equal.\
For example, if you run some npm script not from the project's root, but from an `src` directory:
```
project/ <-- project root (PWD)
  - dist/
  - src/ <-- we run command from here (cwd)
```
in bash:
```bash
user@pc: /home/user/project/src$ npm run script-that-logs-cwd-and-pwd
cwd: /home/user/project/src
PWD: /home/user/project
user@pc: /home/user/project/src$ _
```
or
```bash
user@pc: /home/user/project/src$ node
> process.cwd()
/home/user/project/src
> process.env.PWD
/home/user/project
```

In Windows PowerShell, however, this behaviour is broken:
```ps
PS ...\project\src> npm run script-that-logs-cwd-and-pwd
cwd: ...\project\src
PWD: undefined
```
or
```ps
PS ...\project\src> node
> process.cwd()
...\project\src
> process.env.PWD
undefined
```

hence, there is no reliable way to determine the project root directory by running the script.

It is not obvious, if PWD is related to node or to OS, since there's practically no documentation for it anywhere.

**Comment by addaleax** [comment]
@Raiondesu As the linked stackoverflow question states, the reason that the two are different is that not every code that changes the current working directory also updates the `PWD` environment variable.

> hence, there is no reliable way to determine the project root directory by running the script.

You could look up `process.cwd()` when the process is first started. The two values are typically only different when a part of the program explicitly calls `process.chdir()`.

> It is not obvious, if PWD is related to node or to OS, since there's practically no documentation for it anywhere.

It’s a bash feature: https://manpage.me/?q=bash (you can search for `PWD`).

**Comment by Raiondesu** [comment]
Ok, I guess, I clearly misunderstood this part.

Thank you very much for making it clear for me and everyone else who sees this. 😊
