### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by leonekmi** [nodejs/help#1882]
* **Node.js Version**: 11.14.0 (can reproduce on 12.0.0)
* **OS**: Linux (Debian 9.8; [Package list](https://paste.tuto-craft.com/?3b308879dba5150b#opfpzWpvCWb8QzaAoi6CaGYo2D7ebZFIB7RpweZSnAk=))
* **Scope (install, code, runtime, meta, other?)**: runtime, tls/ssl
* **Module (and version) (if relevant)**: node-fetch 2.3.0 (issue reproduced on axios)

```js
require("node-fetch")("https://misskey.anjara.eu/").then(res => console.log(res)).catch(err => console.error(err))
```

:arrow_up: This doesn't work on some of our machines and i don't know why. The error is always the same. It works with `curl`, `wget` or even a normal browser.

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1176:34)
    at TLSSocket.emit (events.js:193:13)
    at TLSSocket.EventEmitter.emit (domain.js:504:23)
    at TLSSocket._finishInit (_tls_wrap.js:667:8)
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
```

| Test env : Node.JS 11.14.0 `node-fetch@2.3.0` Same CA trusts | leonekmi-PC (Arch Linux)  | hifumin (Debian 9)                    | mozuku (Debian 9)                      | Desktop (Windows 8.1)     | Manjaro                   | Ubuntu Server 19.01       | Debian 9.8 fresh VM       |
|--------------------------------------------------------------|---------------------------|---------------------------------------|----------------------------------------|---------------------------|---------------------------|---------------------------|---------------------------|
| leonekmi.fr                                                  | :heavy_check_mark: Works! | :heavy_check_mark: Works!             | :heavy_check_mark: Works!              | :heavy_check_mark: Works! | :heavy_check_mark: Works! | :heavy_check_mark: Works! | :heavy_check_mark: Works! |
| misskey.anjara.eu                                            | :heavy_check_mark: Works! | :x: `UNABLE_TO_VERIFY_LEAF_SIGNATURE` | :x:  `UNABLE_TO_VERIFY_LEAF_SIGNATURE` | :heavy_check_mark: Works! | :heavy_check_mark: Works! | :heavy_check_mark: Works! | :heavy_check_mark: Works! |

#### What we've tested

* Regen the cert
* Change SSL config on server
* Add the CA by passing it to [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file)
* Use `--use-openssl-ca`
* Regenerate ca-certificates

[`openssl s_client` on hifumin](https://paste.tuto-craft.com/?cff9ef05d095bba7#NbjEY9AFliLNI1M+eaiw+rYJ2WhE6XCKoah9F5JXX0Q=)

**Update** : It seems to affect only servers on the same network (mozuku and hifumin are on subnet01.anjara.eu). We are seeking for Pfsense issues.

_Issue related to https://github.com/syuilo/misskey/issues/4774_

**Comment by gireeshpunathil** [comment]
ping @nodejs/crypto to see if they know the answer.

**Comment by tniessen** [comment]
This is the certificate:

```
-----BEGIN CERTIFICATE-----
MIIGWDCCBUCgAwIBAgISAx79a/G70fo+zDWAvZ3cf6FyMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTA0MjQxNDA2MDVaFw0x
OTA3MjMxNDA2MDVaMBQxEjAQBgNVBAMTCWFuamFyYS5ldTCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBALBqN7qcA6uGq5rcGuf9IwNaAdH9+WaG4f6RSz7Y
s7f6LdUxarJ11MBqu6LAhIvbnem2/PdkOCrg6X4ziKQGZ9E3BI09rtn1SZthpt+k
DfjkeWJCCSxfIVST/PnAb4nFp14VUeuZaeId7QdF267ALt5ynxPIFmrrwrp20lCn
a8sqyJeqw/mehqqlfZ343nxanfa89Ej5ztS9BP26xPdckQ5R1j7sPJ3YeNqzZAnH
h3U7p6bDdW+6e9IT8XH9zOO8Ztg+BbXPGoxJ7z5a/U+HP3Cwbadz7GsJAOUu0vM5
xBxrrSvDjxI4KE0ryBIsybKw2lVW1D/aez67t8o82xLthVMBlhM2V4qi1wEWeevP
MqO/TlN+ejId140sCN2DpRywpURyi2agDaFngU0m9W7fMkt60nrLddMwRoYeGGq/
ZAj1M3/mIAcYXVwy+AFxwQAzra1NIo/xZayzr301bG2ypir/LSi6gFkbauVroe/d
qK0Ay7XMteC5zfp6b0tigVTuowo9DK8d3f7BSsoyTnv3uw9UE+07G8oUQmS5oDKR
Wb/aXiW8YyG20Dw3lPRpkELDQ3bUVsxxPF9Zw9p4AO8zFnMNkWEKb80JPj0HnNYA
B0gmkgHPvBZWrm8J9RMMlMErKbQkuhYORah/W/vyHQzaQ7ofBRvCO6C3aEorSaMX
hKWxAgMBAAGjggJsMIICaDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFK5BMmB0ZdCK
VGjiX3xeBuHLoNfrMB8GA1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8G
CCsGAQUFBwEBBGMwYTAuBggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxl
dHNlbmNyeXB0Lm9yZzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxl
dHNlbmNyeXB0Lm9yZy8wIQYDVR0RBBowGIILKi5hbmphcmEuZXWCCWFuamFyYS5l
dTBMBgNVHSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEBATAoMCYGCCsGAQUF
BwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQUGCisGAQQB1nkCBAIE
gfYEgfMA8QB2AHR+2oMxrTMQkSGcziVPQnDCv/1eQiAIxjc1eeYQe8xWAAABak/h
5l8AAAQDAEcwRQIhAP7yNJf0sAlGOUBBzkX1ksvCnfx56DTYdp4xsgxdm34bAiAE
rauCD7lQ/dmxslzM7Jlk4xgxLgx3/opTteKS+a8eXwB3ACk8UZZUyDlluqpQ/FgH
1Ldvv1h6KXLcpMMM9OVFR/R4AAABak/h5mUAAAQDAEgwRgIhANtegeVP171eNPy5
plb0XqAxT0oPwPN+cQRpbVTvTFiPAiEAl5BHgk5lzILmkb7ejmmPmU3ohbCIu3sF
t/1y9RVHH/UwDQYJKoZIhvcNAQELBQADggEBACtP7l+NIIWkhO59YNBJxgqRXFfO
b5a8vz9bCJUwh/aDTc4FDwFjROscIWWAYA51UkoNrmpuBRhWNdieZESMEr9Hc4R8
7i6fGJVSF1sUCf9U85J3UpUnEPcM5YWDKZAwlolb+3I2Xjgj0pW0swfpiyFzUIx8
W3cvdE2JoMDAAiuncmNXn+Kr710QAFBMsNdhzJy0k26+zKPfAb5uQd8Hu79RnA8R
QpEUJY469XQJlMp1/P2J3UsIRIBxWVkzkbjgjaCQTa2wZoDmhJQ9o+lOY/qOKPU9
2SZN+dxTn5y3im+WHA2+NPTbIEvvpk+Z3D9kJSHEVr2JAlXPYAp95bZnqB0=
-----END CERTIFICATE-----
```

Here is the output of `openssl s_client` using OpenSSL 1.1.0h:

```
CONNECTED(00000003)
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
---
Certificate chain
 0 s:/CN=anjara.eu
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGWDCCBUCgAwIBAgISAx79a/G70fo+zDWAvZ3cf6FyMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTA0MjQxNDA2MDVaFw0x
OTA3MjMxNDA2MDVaMBQxEjAQBgNVBAMTCWFuamFyYS5ldTCCAiIwDQYJKoZIhvcN   AQEBBQADggIPADCCAgoCggIBALBqN7qcA6uGq5rcGuf9IwNaAdH9+WaG4f6RSz7Y
s7f6LdUxarJ11MBqu6LAhIvbnem2/PdkOCrg6X4ziKQGZ9E3BI09rtn1SZthpt+k
DfjkeWJCCSxfIVST/PnAb4nFp14VUeuZaeId7QdF267ALt5ynxPIFmrrwrp20lCn   a8sqyJeqw/mehqqlfZ343nxanfa89Ej5ztS9BP26xPdckQ5R1j7sPJ3YeNqzZAnH
h3U7p6bDdW+6e9IT8XH9zOO8Ztg+BbXPGoxJ7z5a/U+HP3Cwbadz7GsJAOUu0vM5
xBxrrSvDjxI4KE0ryBIsybKw2lVW1D/aez67t8o82xLthVMBlhM2V4qi1wEWeevP
MqO/TlN+ejId140sCN2DpRywpURyi2agDaFngU0m9W7fMkt60nrLddMwRoYeGGq/
ZAj1M3/mIAcYXVwy+AFxwQAzra1NIo/xZayzr301bG2ypir/LSi6gFkbauVroe/d
qK0Ay7XMteC5zfp6b0tigVTuowo9DK8d3f7BSsoyTnv3uw9UE+07G8oUQmS5oDKR
Wb/aXiW8YyG20Dw3lPRpkELDQ3bUVsxxPF9Zw9p4AO8zFnMNkWEKb80JPj0HnNYA   B0gmkgHPvBZWrm8J9RMMlMErKbQkuhYORah/W/vyHQzaQ7ofBRvCO6C3aEorSaMX
hKWxAgMBAAGjggJsMIICaDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFK5BMmB0ZdCK
VGjiX3xeBuHLoNfrMB8GA1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8G
CCsGAQUFBwEBBGMwYTAuBggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxl
dHNlbmNyeXB0Lm9yZzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxl
dHNlbmNyeXB0Lm9yZy8wIQYDVR0RBBowGIILKi5hbmphcmEuZXWCCWFuamFyYS5l
dTBMBgNVHSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEBATAoMCYGCCsGAQUF
BwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQUGCisGAQQB1nkCBAIE
gfYEgfMA8QB2AHR+2oMxrTMQkSGcziVPQnDCv/1eQiAIxjc1eeYQe8xWAAABak/h
5l8AAAQDAEcwRQIhAP7yNJf0sAlGOUBBzkX1ksvCnfx56DTYdp4xsgxdm34bAiAE
rauCD7lQ/dmxslzM7Jlk4xgxLgx3/opTteKS+a8eXwB3ACk8UZZUyDlluqpQ/FgH
1Ldvv1h6KXLcpMMM9OVFR/R4AAABak/h5mUAAAQDAEgwRgIhANtegeVP171eNPy5
plb0XqAxT0oPwPN+cQRpbVTvTFiPAiEAl5BHgk5lzILmkb7ejmmPmU3ohbCIu3sF
t/1y9RVHH/UwDQYJKoZIhvcNAQELBQADggEBACtP7l+NIIWkhO59YNBJxgqRXFfO
b5a8vz9bCJUwh/aDTc4FDwFjROscIWWAYA51UkoNrmpuBRhWNdieZESMEr9Hc4R8
7i6fGJVSF1sUCf9U85J3UpUnEPcM5YWDKZAwlolb+3I2Xjgj0pW0swfpiyFzUIx8
W3cvdE2JoMDAAiuncmNXn+Kr710QAFBMsNdhzJy0k26+zKPfAb5uQd8Hu79RnA8R
QpEUJY469XQJlMp1/P2J3UsIRIBxWVkzkbjgjaCQTa2wZoDmhJQ9o+lOY/qOKPU9
2SZN+dxTn5y3im+WHA2+NPTbIEvvpk+Z3D9kJSHEVr2JAlXPYAp95bZnqB0=
-----END CERTIFICATE-----
subject=/CN=anjara.eu
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3539 bytes and written 269 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: C2C3E45CBB09E87EC1B6AECD7BB2CC991294038015A6C528F9555BFD7EE6C5F7
    Session-ID-ctx:
    Master-Key: 2E5FE847D46921561E3DA76937F42FB9E9B45FDA92C169D59130A08E5C4F88688876CF916C5BA998BFA09CE04F9A4138
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1556522495
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)    Extended master secret: yes
```

Can you try using the whole certificate chain instead of the peer certificate only?

**Comment by leonekmi** [comment]
:thinking: We use nginx 1.15.9 as webserver and the full cert chain is correctly configured. Maybe a nginx bug ? 

_Sent from my Poco F1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sam-github** [comment]
an nginx bug would be low down on my list of possibilities.

From the s_client output, the chain received ended with `i:/O=Digital Signature Trust Co./CN=DST Root CA X3`, so its necessary that that cert be in your local CA store. You aren't using our node builds, so you aren't using our hardcoded CA list, node will use whatever CAs debian has configured in its root store. That the behaviour depends on the OS makes it seem likely that the default root store is different across your OSes.

**Comment by leonekmi** [comment]
![image](https://user-images.githubusercontent.com/20224422/56925887-b7befe00-6ad0-11e9-89cc-60511702488a.png)

There is `DST_Root_CA_X3.pem` on our CAs directory (`/etc/ssl/certs`).

I can't point the finger at the problem. The most shocking is that [`leonekmi.fr`](https://tls.imirhil.fr/https/leonekmi.fr) and [`misskey.anjara.eu`](https://tls.imirhil.fr/https/misskey.anjara.eu) has the same SSL/TLS server configuration. The only difference is the RSA key length.

_Sidenote : i edited the OP with some other logs_

**Comment by leonekmi** [comment]
O-K, i feel dumb. Pfsense does MITM by default in https in NAT. Nevermind.
