### ISSUE TITLE
How to create true Singleton without relying on cache system

### ISSUE THREAD

**Issue by xxRockOnxx** [nodejs/help#1883]
Based on the documentation: https://nodejs.org/api/modules.html#modules_module_caching_caveats

> Modules are cached based on their resolved filename. Since modules may resolve to a different filename based on the location of the calling module (loading from node_modules folders), it is not a guarantee that require('foo') will always return the exact same object, if it would resolve to different files.

How do we create a real singleton? Almost every google results I found always rely on Node's caching system.

Sometimes singleton is wanted. Is it possible?

**Comment by devsnek** [comment]
your singleton is safe, the cache works by resolved filename. require returning a different thing based on the file it's in is very rare as it kind of requires a purposeful and weird setup (like multiple node_modules in a single project)

**Comment by xxRockOnxx** [comment]
Thanks for the assurance that it's safe. Closing.
