### ISSUE TITLE
What does “info.GetReturnValue().Set(obj);” return?

### ISSUE THREAD

**Issue by nitishsaboo** [nodejs/help#1884]
Hi,

I am new to Nan and I want to get rid of the following code snippet

But before that I need to understand what exactly is being returned from this method.

```c++
Local<Object> obj;

NAN_METHOD(process) {
    if (info.Length() == 0 || !info[0]->IsObject()) {
      std::cerr << "Must pass event object as first argument" << std::endl;
      info.GetReturnValue().Set(Nan::Null());
      return;
  }

  auto req = info[0]->ToObject();
  auto program = Nan::Get(req, Nan::New<String>("program").ToLocalChecked()).ToLocalChecked();
  auto message = Nan::Get(req, Nan::New<String ("message").ToLocalChecked()).ToLocalChecked();
  if (!program->IsString() || !message->IsString()) {
    std::cerr << "Must provide program and message keys in event object" << std::endl;
    info.GetReturnValue().Set(Nan::Null());
    return;
  }

  Nan::Utf8String app(Nan::To<String>(program).ToLocalChecked());
  Nan::Utf8String msg(Nan::To<String>(message).ToLocalChecked());
  obj = req;
  match(*msg, msg.length(), *app, app.length());
  info.GetReturnValue().Set(obj);
}
```
program and message both are strings.

match is a C method that is being called with return type void.

1)What is info.GetReturnValue().Set(obj) doing? Is this making any changes to obj because of some manipulation in the match function?

2)What is being returned from this method?

**Comment by gireeshpunathil** [comment]
@nitishsaboo  -

1. `info.GetReturnValue().Set(obj)` - assuming info is the incoming parameter to the NAN method - sets `obj` as the return value that goes back to the JS land. In other words, a JS code that calls this method can receive `obj` as the return value of the call.

2. It is not possible to statically determine what this method is going to return I guess, as it has 3 control paths that return; so will depend on the input params.

Hope this helps!

**Comment by nitishsaboo** [comment]
@gireeshpunathil 
Thanks for the response.Since I am new to Nan, please don't mind if I ask a very dumb question:

This ' process; method is being called from a js file in the following manner:

var envelope = {
    program: program,
    message: message
  };
  var res = native_parser.process(envelope);

  where program and message both are strings

1)Let me know if 'info' is  envelope in this case ?
2)How the method has 3 control paths in this case ? 'match' method is a C method that has return type as 'void'.  'info.GetReturnValue().Set(obj)' -->> this is where the method is returning ..right ?

3)Does the match method modify the 'obj' internally in some way?

>> I am asking this because, if match function is not manipulating the 'obj' then whatever we are passing to the 'process' method is getting returned as it is to the JS land.Let me know If my understanding is correct ?

**Comment by gireeshpunathil** [comment]
1. Yes, `info` is envelope
2. I mean 3 return paths. wherever there is a return statement, it is a possible return path, but will critically depend on the input data. wherever `info.GetReturnValue().Set()` and `return` are called those are returns paths. And you have 3 of those.
3. `match` does not seem to be  a standard C function! do you have the definition of it in your source unit? I cannot find it.

**Comment by nitishsaboo** [comment]
Match is simply a wrapper method that internally calls few syslog-ng methods.It is a standard C method.

void match(const gchar *pattern, size_t pattern_len, const gchar *program, size_t program_len)
{
LogMessage *msg = log_msg_new_empty();
PDBInput input;

log_msg_set_value(msg, LM_V_MESSAGE, pattern, pattern_len);
log_msg_set_value(msg, LM_V_PROGRAM, program, program_len);
pattern_db_process(patterndb, PDB_INPUT_WRAP_MESSAGE(&input, msg));
log_msg_unref(msg);
}

**Comment by gireeshpunathil** [comment]
> It is a standard C method.

Can you please provide a public link that refers to this?

**Comment by nitishsaboo** [comment]
Following is the public link to the code.I am planning to replace the Nan code(process method) with the Go Code.
But before that I need to understand what exactly is being returned from this' process' method.
Is the match method in any way manipulating the 'obj' in the Nan code ?

https://github.com/nitishsaboo/Testing/blob/master/syslog-node.c

**Comment by gireeshpunathil** [comment]
@nitishsaboo - thanks for the link. My definition for standard API is that it belongs to the C compiler or C runtime ( satisfying the comppiler through some `#includes` from `/usr/include` and satisfying the linker by some `-l` from `/usr/lib64` etc.) Anyways!

1. `*msg` is the C++ string equivalent of `Nan::Utf8String`
2. As `match` function receives this through `const gchar *` , this is passed as a readonly copy to the `match` function, so it cannot modify it in any manner. So `match` method does not modify `obj` in any manner.

Let me know if you have more questions.

**Comment by nitishsaboo** [comment]
@gireeshpunathil 
Thanks for the response.I came across this link 'https://nodejs.org/api/addons.html#addons_wrapping_c_objects' , where they are wrapping C++ objects.
Under '**Wrapping C++ objects**' topic, how is the value under 'obj' is getting printed without returning 'obj'.
I feel the same thing is being done in my case as well.They are following a similar approach as given in the link.In my case the obj is getting updated after the 'match' function is getting executed and the result is getting reflected back to the JS Land

var envelope = {
program: program,
message: message
};
var res = native_parser.process(envelope);

//process method already shown above

**Comment by gireeshpunathil** [comment]
@nitishsaboo - it is impossible, at least in `match` method. It takes 4 params: 2 const strings, and 2 integers. Modifying integers do not reflect back into caller, as they are stack frame variables. constant strings cannot be modified, by specification.

So if you explain your problem, I can help further. On the other hand, if you are just suspecting whether `match` will modify its input, NO is the answer.

**Comment by nitishsaboo** [comment]
@gireeshpunathil 



Following is the constructor:

NAN_METHOD(P::New) {
  if (info.IsConstructCall()) {
    P* obj = nullptr;
    if (info[0]->IsObject()) {
      auto arguments = info[0]->ToObject();
        Nan::Utf8String p_path(p->ToString());
        Nan::Utf8String m_path(m->ToString());
        obj = new P(*p_path, *m_path); 
    }
    else {
      obj = new P();
    }
    obj->Wrap(info.This());
    info.GetReturnValue().Set(info.This());
  }
  else {
    auto cons = Nan::New<Function>(constructor);
    info.GetReturnValue().Set(Nan::NewInstance(cons).ToLocalChecked());
  }
}

P::P(const char* p, const char* m) {
  initialize(p, m, cb);
}

P::P() {
  const char* p = "/X/ABC";
  const char* m = "/Y/ABC";
  initialize(p, m, cb);
}


Following is the call back function:
-------------------------------------

auto cb = [](const char* key, const char* value, std::size_t value_len) -> void {
  auto Z = ABC.find(key);
  if (Z != std::end(ABC)) {
    Nan::Set(obj, Nan::New<String>(Z->second).ToLocalChecked(), Nan::New<String>(value, value_len).ToLocalChecked());
  }
  else {
    Nan::Set(obj, Nan::New<String>(key).ToLocalChecked(), Nan::New<String>(value, value_len).ToLocalChecked());
  }
};

NOTE: callback function is getting passed in the initialize. initialize is a C method.
After the constructor initialisation that is being done from a js file, 'process' method is called that internally calls 'match' function.
By any chance because of this callback function that is getting passed in initialize method,  the 'obj' is getting modified when the 'process' method is called and the result is getting reflected in the js file.
What is 'obj->Wrap(info.This())' doing ?

My reference: https://github.com/nodejs/nan/blob/master/doc/object_wrappers.md

**Comment by gireeshpunathil** [comment]
@nitishsaboo - yes, `Nan::Set` is setting a key-value pair onto the obj. So if the callback is called, depending on the condition (if-else) one of the Nan::Set will modify obj content. (but this was different from what you asked earlier!)
Hope this helps!

**Comment by wide4head** [comment]
@nitishsaboo Please use <> (Insert code) when inserting code into github comments.

This makes the code much more readable.

 More info at https://help.github.com/en/articles/creating-and-highlighting-code-blocks.

**Comment by gireeshpunathil** [comment]
ping @nitishsaboo

**Comment by gireeshpunathil** [comment]
answered, closing
