### ISSUE TITLE
C++ Addon - What is the difference between AddEnvironmentCleanupHook and AtExit

### ISSUE THREAD

**Issue by JCMais** [nodejs/help#1886]
To support worker threads, a new function was added: [`AddEnvironmentCleanupHook`](https://nodejs.org/api/addons.html#addons_worker_support)

We previously had other cleanup hook, [`AtExit`](https://nodejs.org/api/addons.html#addons_atexit_hooks)

What exactly is the difference between them?

Are `AtExit` hooks called from the main thread while `AddEnvironmentCleanupHook` from their respective own threads? If not, how I can accomplish that (Running something when the main thread is exiting, instead of the current worker thread)?

**Comment by wide4head** [comment]
@JCMais In https://github.com/nodejs/node/commit/ba269585ed3194bcf5aa5a08b0c316e89d64663c @addaleax commented

> Unlike `AtExit`, this API targets addon developers rather than
embedders, giving them (and Node’s internals) the ability to register
per-`Environment` cleanup work.

**Comment by JCMais** [comment]
If I have a function that should be called after all threads exit, should I add it on the AtExit then? Or is that currently not possible? @wide4head @addaleax

**Comment by gireeshpunathil** [comment]
fwiw, `AtExit` for the main process is invoked here:

https://github.com/nodejs/node/blob/fa3eefcb83c35a804a612a030313d6e2906038b6/src/node_main_instance.cc#L149

As we can see, at that point all Node's subsystem have been destroyed, except C/C++ runtime. So I would say you can invoke
 - your `own` function that does not meddle with Node / V8 structures,
 - C/C++ runtime functions like `malloc`, `printf`, etc.

However, I will leave it to @addaleax for a more assertive opinion!

**Comment by JCMais** [comment]
Thanks for the link to that code.

From what I can see here: https://github.com/nodejs/node/blob/fa3eefcb83c35a804a612a030313d6e2906038b6/src/node_main_instance.cc#L190

The main environment has a specific flag, however, I don't see any method of retrieving the current environment from the addon, is that even possible?

The environment is added to the current context here:
https://github.com/nodejs/node/blob/7cfcf8069bb91240d25f83fa5ab5b7af2da49260/src/env-inl.h#L294-L295

I suppose I could just do:
```
  node::Environment *env = static_cast<node::Environment *>(ctx->GetAlignedPointerFromEmbedderData(32));
```

But that feels really hacky and I think I would still not be able to access Environment members

**Comment by gireeshpunathil** [comment]
either `Environment *env = Environment::GetCurrent(context);`
or
`Environment *env = Environment::GetCurrent(isolate);`

are the standard way of obtaining the current env, in an addon method. If the addon method in question is an entry point method (from JS to C++) then `isolate` and `context` are part of the input params to the method. If your method is a helper function but not an entry point one, then you will can obtain the `env` through the said method and `cache` it with you - when you do that, of course you need to track the life cycle of the current environment, as the validity of the pointer is limited to that.

Having said all these, if your desire is to use `env` at `AtExit` then no!, as that is called soon after the Environment has cleaned up, so it leads to inevitable crash!

Going back to your original question: yes, `AtExit` is invoked after all the workers are down, and the main is about to wind up.

**Comment by gireeshpunathil** [comment]
ping @JCMais

**Comment by JCMais** [comment]
@gireeshpunathil I have not had time to test this, I'm closing the issue for now, I will make sure to reopen it if I have any more questions.

Thanks for the answers
