### ISSUE TITLE
npm ERR!   code: 'ECONNREFUSED',

### ISSUE THREAD

**Issue by CXX22** [nodejs/help#1887]
![npm](https://user-images.githubusercontent.com/47452951/57069858-b149a580-6ccd-11e9-8c6e-ee9d03bd6e3d.JPG)

Hello everyone,

Please I need an assistance in fixing my npm usage.

I am using vs code and have installed node js but noticed whenever I try to npm installation on the terminal, I am shown some error notifications. I have updated, set and gotten proxy, set and gotten a registry but still to not avail, I have also cleared the cache but still having same error.

The following are what pops up whenever I try to install using npm:

npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/lite-server failed, reason: connect ECONNREFUSED 10.32.47.71:80
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:189:13)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:100:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:122:5)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR!  { FetchError: request to https://registry.npmjs.org/lite-server failed, reason: connect ECONNREFUSED 10.32.47.71:80
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:189:13)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:100:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:122:5)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR!   message:
npm ERR!    'request to https://registry.npmjs.org/lite-server failed, reason: connect ECONNREFUSED 10.32.47.71:80',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack:
npm ERR!    'FetchError: request to https://registry.npmjs.org/lite-server failed, reason: connect ECONNREFUSED 10.32.47.71:80\n    at ClientRequest.req.on.err (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n    at ClientRequest.emit (events.js:189:13)\n    at onerror (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\agent-base\\index.js:100:9)\n 

---------------------------------------------------------------------------------------------------------

Please kindly give me the step by step guide in resolving this issue.
caseyviva1@gmail.com

**Comment by preveen-stack** [comment]
@VivaRunor Looks like on your system registry.npmjs.org resolves to 10.32.47.71 which is a private ip address. Can you check your DNS pls.

On my system registry.npmjs.org resolves to 104.16.17.35 a public ip address.

**Comment by VivaRunor** [comment]
I'm trying my best but not yielding any positive result but errors

**Comment by wide4head** [comment]
Can you please post the results of the following command on your system 

>  ping -c 4 registry.npmjs.org

On my system the results look like this
> PING registry.npmjs.org (104.16.22.35): 56 data bytes
64 bytes from 104.16.22.35: icmp_seq=0 ttl=55 time=27.237 ms
64 bytes from 104.16.22.35: icmp_seq=1 ttl=55 time=23.215 ms
64 bytes from 104.16.22.35: icmp_seq=2 ttl=55 time=24.693 ms
64 bytes from 104.16.22.35: icmp_seq=3 ttl=55 time=23.407 ms

>--- registry.npmjs.org ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 23.215/24.638/27.237/1.605 ms

**Comment by VivaRunor** [comment]
@wide4head thanks for the followup.

I tried what you suggested and I was told:
Access denied. Option -C requires administrative privileges.


I did this on vs code terminal and my command prompt terminal. I even run my cmd as an administrator but still denied access

**Comment by wide4head** [comment]
@VivaRunor please use lower case letter -c option and  not the upper case one

**Comment by wide4head** [comment]
@VivaRunor Oh, I forgot that you are on windows. 

You only need 

> `ping registry.npmjs.org`

**Comment by VivaRunor** [comment]
Alright. Let me try.
Please kindly reach me via email caseyviva1@gmail.com

**Comment by VivaRunor** [comment]
Although, my system is not having internet presently. There's a disruption some minutes ago in my server.

I tried ping registry.npmjs.org and was told ping request could not find host registry.npmjs.org

Does ping work without internet plz?

**Comment by wide4head** [comment]
@VivaRunor  But the whole point of conversing through github comments in the nodejs/help repository is that the conversation is potentially helpful to other people with similar problems.

Sorry. the ping command will not work without the internet ;-)

**Comment by VivaRunor** [comment]
I know.
I wanna share something with you via email so you use to assist me

**Comment by wide4head** [comment]
@VivaRunor go ahead and share in the comments so that other people, with far more experience than I have, can potentially help out

**Comment by VivaRunor** [comment]
You arent serious. I should share my personal details with you publicly cos
I need speedy assistance?

You can go

**Comment by wide4head** [comment]
I think this issue is caused by an unreachable proxy on the local network.

Anybody comes across similar issues, make sure that the proxy server software is up and running on the designated proxy server machine  on the local network and is listening to the correct port # as configured in the npm configuration.

More about proxy configuration can be found in 
[https://docs.npmjs.com/misc/config](url)

Also
[https://jjasonclark.com/how-to-setup-node-behind-web-proxy/](url)
[http://luxiyalu.com/how-to-remove-all-npm-proxy-settings/](url)

**Comment by VivaRunor** [comment]
I started attempting to fix this issue since last week. I tried updating
the proxy, getting and setting it according to some steps I followed on
stackoverflow, I have also cleared the cache but to no avail.

Now, I need someone with teamviewer to help check. That's all

**Comment by VivaRunor** [comment]
![Github](https://user-images.githubusercontent.com/47452951/57364162-87372e00-717a-11e9-812b-c954b1055753.jpg)

With internet, that's what I got.
@wide4head

**Comment by gireeshpunathil** [comment]
@VivaRunor - is this still an issue?

If so, the fact that `registry.npmjs.org` is not getting resolved is critically blocking our progress. But unfortunately, I don't think I can help you here. This issue needs to be diagnosed and resolved with the help of someone with windows system admin skills.

**Comment by VivaRunor** [comment]
Quite a long time for you to reply. Incredible

**Comment by gireeshpunathil** [comment]
@VivaRunor - yes, I see that the last update was more than a month back. is this resolved in between?

**Comment by VivaRunor** [comment]
No, it is not. Are you on whatsapp?

**Comment by gireeshpunathil** [comment]
sorry, I am not. but let me try to contact you through email, if that helps

**Comment by VivaRunor** [comment]
No problem. Do you use teamviewer? If yes, what about connecting to my
system to help try to fix it?

**Comment by akbarali0203** [comment]
Try this:

**Comment by gireeshpunathil** [comment]
ping @VivaRunor - is this still outstanding?

**Comment by VivaRunor** [comment]
I need someone to help me with a softcopy of PYTHON GUI, A STEP BY STEP
GUIDE TO DATABASE PROGRAMMING by Vivian, S.

**Comment by Abhinav-vats** [comment]
I got the same issue while installing nodemailer
I used the command **npm install nodemailer**
please help me out

following is what pops up whenever I try to install

npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://registry.npmjs.org/nodemailer failed, reason: connect ECONNREFUSED 127.0.0.1:3000npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:311:20)
npm ERR!     at Socket.socketErrorListener (_http_client.js:426:9)
npm ERR!     at Socket.emit (events.js:311:20)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR!  FetchError: request to http://registry.npmjs.org/nodemailer failed, reason: connect ECONNREFUSED 127.0.0.1:3000
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:311:20)
npm ERR!     at Socket.socketErrorListener (_http_client.js:426:9)
npm ERR!     at Socket.emit (events.js:311:20)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
npm ERR!   message: 'request to http://registry.npmjs.org/nodemailer failed, reason: connect ECONNREFUSED 127.0.0.1:3000',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to http://registry.npmjs.org/nodemailer failed, reason: connect ECONNREFUSED 127.0.0.1:3000\n' +
npm ERR!     '    at ClientRequest.<anonymous> (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n' +
npm ERR!     '    at ClientRequest.emit (events.js:311:20)\n' +
npm ERR!     '    at Socket.socketErrorListener (_http_client.js:426:9)\n' +
npm ERR!     '    at Socket.emit (events.js:311:20)\n' +
npm ERR!     '    at emitErrorNT (internal/streams/destroy.js:92:8)\n' +
npm ERR!     '    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n' +
npm ERR!     '    at processTicksAndRejections (internal/process/task_queues.js:84:21)'
npm ERR! }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abhi\AppData\Roaming\npm-cache\_logs\2020-04-09T14_11_25_943Z-debug.log

**Comment by raedbenz** [comment]
on going issue with any **npm install package** or **npx package args**. commands

**Comment by givingwu** [comment]
try this command :

```bash
sudo npm install
```

we resolved this problem.

**Comment by erikeckhardt** [comment]
> try this command :
> 
> ```shell
> sudo npm install
> ```
> 
> we resolved this problem.

sudo installing of npm packages will just lead to more problems down the road.

The correct answer is to chown all of the folders that npm uses, not to use sudo. Or uninstall npm/node, delete all their folders, and reinstall.

Use of sudo with npm install is actually a security issue, because any random package that you happen to be including could be hacked, and if it detects it has sudo access, it can then do malicious stuff to your computer.

**Comment by VGerris** [comment]
The cause is likely :+1:
1 - your internet is down
2 - your dns is not resolving properly
3 - your regstry is not pointing to the right registry

As posted above, run the following:
npm set registry https://registry.npmjs.org

This sets the registry to the main npm registry and if you fix point 1 and 2 it should work.
And please do not post unrelated questions and mark this as resolved if it works, thanks.

**Comment by pborregg** [comment]
Hello, I don't have a proxy at all. 

I have been "able" to do npm install. I'm using windows 11 pro now as of August 2021

This is what I'm getting:

`$ npm install
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://localhost:4873/proxy-addr/-/proxy-addr-2.0.5.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:4873
npm ERR!     at ClientRequest.<anonymous> (C:\Users\Peter\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:97:14)
npm ERR!     at ClientRequest.emit (events.js:315:20)
npm ERR!     at Socket.socketErrorListener (_http_client.js:469:9)
npm ERR!     at Socket.emit (events.js:327:22)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:106:8)
npm ERR!     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR!  FetchError: request to http://localhost:4873/proxy-addr/-/proxy-addr-2.0.5.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:4873
npm ERR!     at ClientRequest.<anonymous> (C:\Users\Peter\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:97:14)
npm ERR!     at ClientRequest.emit (events.js:315:20)
npm ERR!     at Socket.socketErrorListener (_http_client.js:469:9)
npm ERR!     at Socket.emit (events.js:327:22)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:106:8)
npm ERR!     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 4873,
npm ERR!   type: 'system'
npm ERR! }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
`

I didn't have this problem before... but I had broadband with an ARRIS MODEM, now, I have just internet through the same company Wavebroadband but now, I'm using a different modem and router

Motorola MB8600 DOCSIS 3.1 Cable Modem, 6 Gbps Max Speed. Approved for Comcast Xfinity Gigabit, Cox Gigablast, and More, Black

And

TP-Link Deco Mesh WiFi System(Deco M3) –Up to 4,500 sq.ft Whole Home Coverage, Replaces WiFi Router/Extender, Plug-in Design, Works with Alexa, 3-Pack

So, I wonder if there's something I need to open on the modem to make NPM work?

**Comment by rb-mwindh** [comment]
I had a similar issue.
I'm working behind a Corporate NTLMv2 Proxy and need to authenticate for internet access.
I'm using a local NTLM-Authenticating Proxy ([genotrace/px](https://github.com/genotrance/px)).

My proxy settings in `.npmrc` look like this:
```
proxy=http://localhost:3128
https-proxy=http://localhost:3128
```

Recently, I had to change my password and ran into all kinds of annoying authentication issues.
Long story short, I suddenly kept running into this error:
`request to https://registry.npmjs.org/@angular/cli/-/cli-12.2.18.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:3128`

My final solution was to switch from `localhost` to `127.0.0.1`, which I assume might be caused by my px-proxy config.

**Solution**
```
// .npmrc
proxy=http://127.0.0.1:3128
https-proxy=http://127.0.0.1:3128
```

**Comment by nagadomi** [comment]
I encountered this problem too.
```
FetchError: request to https://registry.npmjs.org/npm failed, reason: connect ECONNREFUSED 2606:4700::6810:1823:443
```
In my case, this seems to be an IPv6 or DNS related issue.  
I manually added the IPv4 address of `registry.npmjs.org` to `/etc/hosts` and this problem is solved.

check ipv4 address.
```
$ nslookup registry.npmjs.org
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	registry.npmjs.org
Address: 104.16.21.35
....
```
Add to /etc/hosts
```
104.16.21.35 registry.npmjs.org
```

However, this is workaround, as IP addresses may change.
I've never encountered this kind of problem so I'm suspecting a problem with the nodejs network library or the server configuration of registry.npmjs.org.

**Comment by RedYetiDev** [comment]
I'm closing this issue for a few reasons, but if you disagree, please have a team member re-open it.

1) the original requester preferred to be contacted via alternative methods, so tracking this issue would IMO probably be a challenge

> Quite a long time for you to reply. Incredible

2) Everyone here is a **volunteer**. While our response times may seem sub-par, we are here to help, so messages like these are not appreciated
> Note that this is my opinion, and it may differ from the rest of the team

3) This issue appears to have gotten some answers from other users, so hopefully those should help.
