### ISSUE TITLE
exec node --experimental-modules

### ISSUE THREAD

**Issue by NickRimer03** [nodejs/help#1888]
* **Version**: v11.8.0
* **Platform**: Windows 10 64-bit
* **Subsystem**: -

Hello there!
There is a very strange behavior with the `exec` function from `child_process`.

First I'll start with the current code.

_run.js_
```javascript
#!/usr/bin/env node
const { exec } = require("child_process");
exec(`node --experimental-modules ${__dirname}/server.mjs`);
```
_server.mjs_
```javascript
// a bit of code to execute next
console.log("THIS IS LOG FROM SERVER.MJS");
```

And when I'm executing `run.js` nothing happens. And expected to see the console.log message and other code running.
The whole magic is when debugging with `ndb` all works!!

The reason I need to do this kind of 'sheet':
under *nix system (I've just tried to build code with the help of teamcity) there is an error.

There was no `run.js` file earlier, `server.mjs` only. And its header looks like this:
```javascript
#!/usr/bin/env node --experimental-modules
// other code
```
The error message is:
`/usr/bin/env: ‘node --experimental-modules’: No such file or directory`
It's only when *nix build. Under MacOS & Windows platforms everything looks good.

What am I doing wrong? Or this is a kind of bug?
`execSync` (not)works similar way.

UPD: the file really exists and the path is correct (checked out with ndb debugger)

**Comment by gireeshpunathil** [comment]
ping @NickRimer03

**Comment by NickRimer03** [comment]
@gireeshpunathil
for now me and my team we pissed on this bug :)
not so cool, but we relocate `--experimental-modules` to npm commands
it made our paths more longer, but it works this way

**Comment by gireeshpunathil** [comment]
@NickRimer03 - did you apply @bnoordhuis 's suggestion? and what was the result?

**Comment by gireeshpunathil** [comment]
answered, closing

**Comment by Hydroper** [comment]
The piping solution from @aduh95 works, but sadly we've to accept the lack of colors.

<description>

<summary>A bit formatted</summary>

```
#!/usr/bin/env node
const path = require('path')
const {spawn} = require('child_process')
const QUIET_OPTION = false // flag to disable output from your server
const FLAGS = '--experimental-modules'
const EXEC_FILE = path.join(__dirname, '../src/index.js')

const options = [FLAGS, EXEC_FILE, ...process.argv.slice(2)];
const subprocess = spawn(process.argv0, options, {
    windowsHide: true,
})

// if your server subprocess crashes
subprocess.on('error', err => console.error(err))

if (!QUIET_OPTION) {
    subprocess.stderr.pipe(process.stderr)
    subprocess.stdout.pipe(process.stdout)
}
```

</description>

**Comment by aduh95** [comment]
Reading the documentation, turns out there is a cleaner way to achieve this using [inherited stdio](https://nodejs.org/dist/latest-v12.x/docs/api/child_process.html#child_process_options_stdio):

```js
#!/usr/bin/env node
const QUIET_OPTION = false; // flag to disable output from your server

const { spawn } = require("child_process");
const path = require("path");

const FLAGS = "--experimental-modules";
const EXEC_FILE = path.join(__dirname, "server.mjs");

const options = [FLAGS, EXEC_FILE].concat(process.argv.slice(2));
const subprocess = spawn(process.argv0, options, {
        windowsHide: true,
        stdio: QUIET_OPTION ? ["inherit", "ignore", "ignore"] : "inherit",
});

subprocess.on("error", console.error);
subprocess.on("exit", code => {
  process.exit(code || 0);
});

```

That might even fix your color issue @Hydroper..?
