### ISSUE TITLE
brew install node --without-npm  -  Error: invalid option: --without-npm

### ISSUE THREAD

**Issue by mystikodesign** [nodejs/help#1889]
brew install node --without-npm
error message: Error: invalid option: --without-npm

Version: output of `node -v` -bash: /usr/local/bin/node: No such file or directory
Platform: macOS

**Comment by Trott** [comment]
This would be an issue with `brew`, not `node`.  Perhaps try https://discourse.brew.sh?

**Comment by Trott** [comment]
I'm going to close this, but feel free to comment if there's something more to talk about here from a Node.js perspective, or if someone else has a solution.
