### ISSUE TITLE
v8::internal::GlobalHandles::PendingPhantomCallback => Handle not reset in first callback

### ISSUE THREAD

**Issue by sam-wilson-bentley-com** [nodejs/help#1891]
* **Node.js Version**: 10.15.3
* **OS**: Windows X64
* **Scope (install, code, runtime, meta, other?)**: runtime (v8)

My node.js program terminates every so often in v8::internal::GlobalHandles::PendingPhantomCallback with a V8 fatal error, stating that a weak-reference callback has failed to do the correct cleanup. The V8 fatal error is: "Handle not reset in first callback." 

I don't understand this, as my addon does not create weak references or register callbacks. My addon creates references using N-API ObjectReferences (napi_create_reference). All have a non-zero reference count. My addon uses N-API exclusively and does not register any V8-specific weak-reference callbacks. It seems like N-API would handle that?

The failure callstack is:
```
node.exe!v8::base::OS::Abort() Line 897 C++
node.exe!V8_Fatal(const char * file, int line, const char * format, ...) Line 171   C++
node.exe!v8::internal::GlobalHandles::PendingPhantomCallback::Invoke(v8::internal::Isolate *) Line 910  C++
node.exe!v8::internal::GlobalHandles::DispatchPendingPhantomCallbacks(bool synchronous_second_pass) Line 870    C++
node.exe!v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector collector, const v8::GCCallbackFlags gc_callback_flags) Line 930   C++
node.exe!v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector collector, const v8::GCCallbackFlags gc_callback_flags) Line 1775  C++
node.exe!v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace space, v8::internal::GarbageCollectionReason gc_reason, const v8::GCCallbackFlags gc_callback_flags) Line 1392    C++
node.exe!v8::internal::Heap::CollectAllGarbage(int) Line 1156   C++
node.exe!v8::internal::Heap::HandleGCRequest() Line 1053    C++
node.exe!v8::internal::StackGuard::HandleInterrupts() Line 517  C++
node.exe!v8::internal::__RT_impl_Runtime_StackGuard(v8::internal::Arguments) Line 270   C++
node.exe!v8::internal::Runtime_StackGuard(int args_length, v8::internal::Object * * args_object, v8::internal::Isolate * isolate) Line 260  C++
```

How can I find out what object is being referenced or where the reference is being held?

**Comment by addaleax** [comment]
Any chance you could share a reproduction for this issue? If you’re only using N-API, then it’s either a bug in your code or in N-API itself.

**Comment by sam-wilson-bentley-com** [comment]
This fatal error happens often, but we don't know how to reproduce it. This is a server program that can perform various functions on demand. We don't know which of them may be involved.

Are there any diagnostics that we could enable in our server or addon that might help?

Our addon creates several references. Here is an example of code in our addon of one of them:
```
static Napi::ObjectReference s_logger;

static void setLogger(Napi::CallbackInfo const& info)
    {
    s_logger = Napi::ObjectReference::New(info[0].ToObject(), 1);
    s_logger.SuppressDestruct();
    }
```
And an example of how we use that particular ObjectReference:
```
    auto env = s_logger.Env();
    Napi::HandleScope scope(env);

    auto method = s_logger.Get("isEnabled").As<Napi::Function>();
    if (method == env.Undefined())
        {
        Napi::Error::New(JsInterop::Env(), "Invalid Logger").ThrowAsJavaScriptException();
        return true;
        }
...
    return method({catJS, levelJS}).ToBoolean();
```

**Comment by sam-wilson-bentley-com** [comment]
I found what I was doing wrong. The destructor of one of my ObjectWraps resulted a call to a JavaScript function. This was occurring at a time when code execution was forbidden.
