### ISSUE TITLE
prompt is not defined

### ISSUE THREAD

**Issue by Dhanu-codes** [nodejs/help#1894]
iam using node.js with visual studio code 
when i use prompt function is shows prompt is not defined
even when i run the code in node.js it is not working
![js](https://user-images.githubusercontent.com/50212541/57183468-0272b880-6ecb-11e9-98c7-1773948ce8b2.PNG)

**Comment by Dhanu-codes** [comment]
hey man iam new to programming so please explain me clearly

**Comment by wide4head** [comment]
@Dhanu-codes which library are you trying to use? node is basically telling you that it can't find the 'prompt()' function. If you describe a little more about your use case, somebody can point you to the right reference material.

**Comment by gireeshpunathil** [comment]
ping @Dhanu-codes

**Comment by gireeshpunathil** [comment]
inactive, closing
