### ISSUE TITLE
npm version prompt Aborted (core dumped)

### ISSUE THREAD

**Issue by LittleControl** [nodejs/help#1896]
* **Node.js Version**:v10.5.3
* **OS**:Ubuntu19.04
* **Scope (install, code, runtime, meta, other?)**:runtime

When I compile nodejs with source code,
When executing the npm version command，
Finally prompted the following information
Abort(core dumped)，
I don't know why this happens.

**Comment by wide4head** [comment]
@LittleControl can you post the console logs
