### ISSUE TITLE
Error:Module did not self-register ---node-addon-examples

### ISSUE THREAD

**Issue by yangjun9772** [nodejs/help#1897]
Node.js Version: 10.15.3
* **OS**: centos7-64
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Hi, I'm a new one for nodejs.
Now, I was testing the c++ addon examples of node-addon-examples.
I tried the nan/node-0.1/node-0.2 examples.
And I followed the steps of the Readme.md
But when I run : node hello.js, it always report error like this:
home/georgeyang/workspace/cmodule/node_modules/bindings/bindings.js:121
throw e;
^

Error: Module did not self-register.
at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
at Function.Module._load (internal/modules/cjs/loader.js:531:3)
at Module.require (internal/modules/cjs/loader.js:637:17)

Please help. Is it possible that I missed something of node?
BTW, Ibuild the node by the source code.

**Comment by wide4head** [comment]
@yangjun9772 A possible solution is described at 
https://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register

**Comment by yangjun9772** [comment]
> @yangjun9772 A possible solution is described at
> https://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register

thx @wide4head But it seems useless for me..... I just build the latest node and the code is the same as the example of c++ addon "helllo world". But the steps of building Nodejs 
$./configure 
$make -j4 
$sudo make install
$sudo npm install -g node-gyp 
Is it OK?

**Comment by gireeshpunathil** [comment]
@yangjun9772 - I guess the steps are correct.

Can you run:
1. node -v
2. npm -v
3. show your `C++` code - especially, the bottom portion where you are registering your module.

It is possible that multiple node / npm versions exist in your system that are causing trouble here.

**Comment by yangjun9772** [comment]
> @yangjun9772 - I guess the steps are correct.
> 
> Can you run:
> 
> 1. node -v
> 2. npm -v
> 3. show your `C++` code - especially, the bottom portion where you are registering your module.
> 
> It is possible that multiple node / npm versions exist in your system that are causing trouble here.
@gireeshpunathil  Thx for your reply.
[georgeyang@localhost cmodule]$ node -v
v10.15.3
[georgeyang@localhost cmodule]$ npm -v
6.4.1

C++ code: I studied it from [https://github.com/nodejs/node-addon-examples/tree/master/1_hello_world](url)
this is node-0.10. But I have tried the nan/node-0.12. They are the same issue.
---------------------------------
#include <node.h>
#include <v8.h>

using namespace v8;

Handle<Value> Method(const Arguments& args) {
  HandleScope scope;
  return scope.Close(String::New("world"));
}

void Init(Handle<Object> exports) {
  exports->Set(String::NewSymbol("hello"),
      FunctionTemplate::New(Method)->GetFunction());
}

NODE_MODULE(hello, Init)

**Comment by gireeshpunathil** [comment]
can you please follow this example instead:
https://nodejs.org/dist/latest-v12.x/docs/api/addons.html#addons_hello_world

(I see minor differences, but difficult to pinpoint where the issue is.)

**Comment by yangjun9772** [comment]
> can you please follow this example instead:
> https://nodejs.org/dist/latest-v12.x/docs/api/addons.html#addons_hello_world
> 
> (I see minor differences, but difficult to pinpoint where the issue is.)

@gireeshpunathil I have tried this demo. But the result is still NG.
----------log---------------------
georgeyang@localhost cmodule]$ node hello.js 
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
----------------------------------
1. three files: binding.gyp hello.cc hello.js
2. node-gyp configure
3. node-gyp build
4. node hello.js 
then error occured.....

**Comment by gireeshpunathil** [comment]
@yangjun9772 - ok, let me see if I can recreate it from my side. will keep you posted.

**Comment by gireeshpunathil** [comment]
@yangjun9772 - I am unable to repro your scenario. The same code runs well, all the time.

 - are you using the same `node-gyp` that was installed? what does `which node-gyp` show?
 - after `node-gyp build` are you copying the built `addon.node` to your project location?
 - can you show me your JS sample code?

**Comment by yangjun9772** [comment]
> @yangjun9772 - I am unable to repro your scenario. The same code runs well, all the time.
> 
> * are you using the same `node-gyp` that was installed? what does `which node-gyp` show?
> * after `node-gyp build` are you copying the built `addon.node` to your project location?
> * can you show me your JS sample code?

@gireeshpunathil this is my js code :

var addon = require('./build/Release/hello');

console.log(addon.hello());
------------------------------------------
[georgeyang@localhost cmodule]$ node-gyp -v
v4.0.0
[georgeyang@localhost cmodule]$ which node-gyp 
/usr/local/bin/node-gyp

my binding.gyp:
------------------
{
  "targets":[
    {
      "target_name":"hello",
      "source":["hello.cc"]
    }
  ]
}
--------------------

After node-gyp build, I didn't copy the hello.node to the location.It is just in ./build/Release/

**Comment by yangjun9772** [comment]
@gireeshpunathil I tried to put the hello.node in the location. And change the hello.js just like 
var addon = require('./hello.node');
console.log(addon.hello());
but still NG.
The hello.cc wasn't changed
-----
#include <node.h>

using namespace v8;

namespace demo {
  using v8::FunctionCallbackInfo;
  using v8::Isolate;
  using v8::Local;
  using v8::NewStringType;
  using v8::Object;
  using v8::String;
  using v8::Value;

void Method(const FunctionCallbackInfo<Value>& args){
  Isolate* isolate = args.GetIsolate();
  args.GetReturnValue().Set(String::NewFromUtf8(
       isolate, "world", NewStringType::kNormal).ToLocalChecked());
}

void Initialize(Local<Object> exports){
  NODE_SET_METHOD(exports, "hello", Method);
}

NODE_MODULE(NODE_GYP_MODULE_NAME, Initialize)

}
-------

**Comment by yangjun9772** [comment]
the file size of the hello.node 

-rwxrwxr-x. 1 georgeyang georgeyang 7448 May  8 14:35 hello.node

**Comment by gireeshpunathil** [comment]
@yangjun9772 - thanks for quick response, and following all diagnostic steps as suggested.

The versions and locations of node, npm, node-gyp look to be coherent, and the addon code and build procedure seem to be trivial.

At this point I am short on ideas. Let me ping @addaleax and @gabrielschulhof to see if they can provide insights.

**Comment by yangjun9772** [comment]
@gireeshpunathil  thank you for your replies so much.

**Comment by yangjun9772** [comment]
@gireeshpunathil The issue can be closed.
It works when I just "git clone" the example code.
And use cli:
$npm install
$node ./hello.js
This can work.
At the first time, I just did the code by myself. So I think I used the wrong way to do the code. I'll study it again.
Thank you very much for your reply.

**Comment by Zhangkc** [comment]
in file "binding.gyp", key “source" should be ”sources“. I have the same problem with you, and It takes me one morning to find this typo. damn.
