### ISSUE TITLE
Debugging long GC times

### ISSUE THREAD

**Issue by lostthetrail** [nodejs/help#190]
I am seeing GC times reported via `gc-profiler` with a duration regularly over 300ms. The specific event is the MarkSweepCompact. Since this event halts execution, it spikes TTFB for our users.

Node 4.4.5
CentOS 7.2 (via Docker)
Memory: 2048 gb
Framework: Express

The spikes are reproducible under load for me using JMeter on a single thread.

The request handler is returning a single word string. `res.send('OK');`. And I have removed all of the middleware and continued to see this issue.

Any suggestions on how to determine what is causing the GC event to take so long?

**Comment by Trott** [comment]
Sorry no one has responded. Since GC happens in V8, let's see if anyone on @nodejs/v8 is interested in commenting. (No guarantees though!)

**Comment by indutny** [comment]
Hello!

I wonder if using `heapdump` may reveal some information about objects that are alive? Such a long times usually mean lots of objects being created and abandoned.

Hope this helps,
Fedor.

**Comment by bnoordhuis** [comment]
Another thing to try are the `--trace_gc --trace_gc_verbose` flags.
