### ISSUE TITLE
Node.js script is swallowing thrown error

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1900]
I have this script (I am using Node.js v11.14.0):

```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const cp = require('child_process');
const {JSONParser} = require('@oresoftware/json-stream-parser');


process.on('uncaughtException', err => {
    console.error('uncaughtException:', {err});
    process.exit(1);
});

process.on('unhandledRejection', (reason, p) => {
    console.error('unhandledRejection:', reason);
    process.exit(1);
});


console.log('Running test', __filename);

const k = cp.spawn('bash');
const foo = 'medicine';

k.stdin.end(`

  foo="${foo}"
  
  cat <<EOF
  
  {"foo":"$foo"}    ∆∆
  {"foo":"$foo"} ∆
  ∆{"foo":"$foo"}∆
  {"foo":"$foo"}      ∆
  
  EOF

`);

const to = setTimeout(() => {
    console.error('did not receive parsed JSON object within alloted time.');
    process.exit(1);
}, 2000);


let count = 0;

k.stdout.pipe(new JSONParser({delimiter:'∆'})).on('data', d => {

    count++;

    if(count > 3){

        console.error('HELLLLOOOOO:',{count});
        throw new Error('too many json blobs.');  // this never gets caught, no evidence of it whatsoever...!
    }

    if(count === 3){

        setTimeout(() => {

            clearTimeout(to);
            try {
                assert.deepStrictEqual(d, {foo: foo});
                process.exit(0);
            }
            catch (err) {
                console.error(err.message);
                process.exit(1);
            }

        },1000);

    }
});
```
the problem is that 

```js
throw new Error('too many json blobs.')
```

is never raised anywhere as far as I can tell.

here is a simple example project, just clone it and run it:
https://github.com/ORESoftware/swallow-error

**Comment by Hakerh400** [comment]
In your JSON parser implementation on lines 58-64 (https://github.com/ORESoftware/json-parser/blob/ac183a5957b4e33e5e917e0819605480defba402/src/index.ts#L58-L64) you basically catch the error silently. If you enable debug mode (replace `new JSONParser({delimiter:'∆'})` with `Object.assign(new JSONParser({delimiter:'∆'}), {debug: 1}`) then you'll get the output

```
json-parser: error parsing line: {"foo":"medicine"}
json-parser: too many json blobs.
```

Also, keep in mind that `console.error` is asynchronous and calling `process.exit` immediatelly after it may terminate the process before printing the string (though that's not the case here, as explained).

**Comment by ORESoftware** [comment]
@Hakerh400  thanks! that was a really nice catch, much appreciated...I love Node.js but this is definitely one of the downsides of unchecked exceptions or whatever
