### ISSUE TITLE
Why does node.exe always popup a new window in Windows?

### ISSUE THREAD

**Issue by stalkercn** [nodejs/help#1901]
* **Node.js Version**: 10.15.3
* **OS**: Win10 1803
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: web app

whereever I execute node.exe, it always popup a new window, but not output execution result in the original window, this causes I can't debug with breakpoint in VSCode or any other ide.

**Comment by stalkercn** [comment]
Seems it'a problem related to powershell , I tried cmd.exe minutes ago, it works fine. I tried other command-line program in powershell, it works fine too. So only when node.exe is ran in powershell, it always spawns a new console window.

**Comment by gireeshpunathil** [comment]
closing then, cheers!

**Comment by Seraphace** [comment]
For me this happens whether or not I use powershell, cmd, or VSC.  As of 2 days ago I was using Visual Studio Code's terminal to run scripts and it would log the results there.  Now it opens up a node.exe window which runs the script and closes instantly upon execution.  How do I get nodes output to display in the embedded terminal once again?  Picture of it staying open attached as I'm running nodemon.

`<img>https://imgur.com/OoOCyae</img>`

**Comment by gireeshpunathil** [comment]
sorry, that should be a question to the maintainers of the editor. this project does not work on VSC.

> For me this happens whether or not I use powershell, cmd, or VSC

Can you show a similar screen shot for window popup when you use `CMD`? that would be interesting. Also, please check if the `node` that is prevalent in the PATH is a binary executable or a shell script. If it is the later, please open it and see the content.

**Comment by Seraphace** [comment]
> sorry, that should be a question to the maintainers of the editor. this project does not work on VSC.
> 
> > For me this happens whether or not I use powershell, cmd, or VSC
> 
> Can you show a similar screen shot for window popup when you use `CMD`? that would be interesting. Also, please check if the `node` that is prevalent in the PATH is a binary executable or a shell script. If it is the later, please open it and see the content.

Hi Gireesh, 

I'm not sure how to check that, could you let me know? CMD still opens node instead of running in cmd.  I only want to use node for NPM etc, but I want it all to run in the terminal like cmd or the embedded one in VSC.  A huge disadvantage of the way this is doing it is if I'm using NPM to install packages, I can't see what it's doing, if it failed or did it properly, as the window just opens and closes almost immediately.  I know it's not crashing because I can see it working in situations like this where it is listening to the port as per the script, but it's unfavourable in many instances.

<a href="https://imgur.com/7zg49Da"><img src="https://i.imgur.com/7zg49Da.png" title="source: imgur.com" /></a>

**Comment by gireeshpunathil** [comment]
how about doing a webex session to debug this further?

**Comment by Seraphace** [comment]
That would be appreciated.  I uninstalled and reinstalled, and it didn't fix the issue.  I uninstalled both again, deleted all the relevant folders under AppData, and it's back to working.  

<a href="https://imgur.com/yFq0BqN"><img src="https://i.imgur.com/yFq0BqN.png" title="source: imgur.com" /></a>

Considering though that it's the second time in a week that it's happened after installing extra stuff, I'd like to know how to avoid it or fix it without having to reinstall everything :(

**Comment by gireeshpunathil** [comment]
sure, let me know your convenient date, time and timezone.

**Comment by Seraphace** [comment]
Hi Gireesh, 

I don't want to waste your time and appreciate your help, so I will wait until it happens again before I call on you.  Thank you.

**Comment by b26** [comment]
Problem is with running `npm install -g node`

**Comment by Seraphace** [comment]
Hi B26, 

It hasn't happened again despite happening 3 times when I first started programming.  I'm pretty sure each time though, I did a standalone installer and had this happen, or had installed other packages (likely by using the -g parameter).  So I'm not sure how accurate this is as a reason, but thank you for your insight.  I'm bookmarking this to try to see if this ever happens again, thank you!

**Comment by 1xo2** [comment]
i am experiencing the same issue... i have tried to  npm remove -g node but it did not remove the node..
i am considering reinstalling node and vscode... any suggestions?
(as well i am a beginner with node/terminal)
regards.

**Comment by ach4ndi** [comment]
i got this problem when reinstalled/remove current nodejs with newer or older version using msi installer if i not cleaning up npm folder (before install) on AppData on each user profile. so i think, official msi installer should cleaning up npm folder too.

**Comment by Janvier123** [comment]
Ive had "C:\Program Files\nodejs\node.exe" checked as "Run this program as an administrator" for an issue. Unchecked the box => fixed

**Comment by SebastianPost1996** [comment]
My node would open up everytime I save a file (both on Webstorm and VSC), but it was specific to just one project.

It worked again after deleting node_modules and running `npm i`.
