### ISSUE TITLE
N-API - Cache async resource names

### ISSUE THREAD

**Issue by battila7** [nodejs/help#1905]
* **Node.js Version**: v12.0.0
* **OS**: Ubuntu 16.04
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: N-API

Hi!

**Context**

I'm developing an addon using N-API directly. I'd like to expose async functions, therefore I'm currently making use of [Simple Asynchronous Operations](https://nodejs.org/api/n-api.html#n_api_simple_asynchronous_operations).

**Question**

When calling `napi_create_async_work` one must provide an `async_resource_name` which isan *identifier for the kind of resource*.

Since this value will never change, I was thinking if it was possible to create this identifier only once and then use a cached value. AFAIK, simple `napi_value`s are just weak references, therefore I guess, I must use some smarter mechanism, such as `napi_create_reference`.

However, is it okay to create a reference with ref count being constantly one, and then unreffing it only when the module is being torn down?

Maybe, this whole caching idea is completely off, but I was just thinking if I could save a few clocks using this trick.

Thanks!

**Comment by mhdawson** [comment]
@battila7 using napi_create_reference to keep something alive for the life of the module makes sense to me.  I also think that caching the async_resource_name makes sense as well.

**Comment by battila7** [comment]
@mhdawson Thanks for your reply, will try it out then! Gonna report back with the results and close the issue afterwards.

**Comment by battila7** [comment]
@mhdawson Well, it turns out that you cannot create references to Strings. I did not pay attention to the docs which state this explicitly.  Of course, this is enforced by `napi_create_reference` that will return `napi_object_expected` if you pass it a String.

I tried caching the `napi_value` pointing to the created String, but, as you'd expect, it was GC'd and my module crashed.

Am I missing something or is it really the case that you cannot create a reference to a String? Do you know maybe the intentions behind this?

Thanks!

**Comment by bnoordhuis** [comment]
@gabrielschulhof can say for sure but I expect it's greatest common denominator functionality. n-api is not just supposed to abstract differences between node versions, but also JS engines.

As a workaround, you could store the strings in an array and `napi_create_reference()` that.

**Comment by gabrielschulhof** [comment]
@battila7 @bnoordhuis is correct. The reason we restricted persistent references to objects is that other engines do not support references to primitive types. The workaround suggested by @bnoordhuis certainly works. I would add that you should profile whether retrieving a local reference to the persistent reference of the array, followed by retrieving the item at index 0 is cheaper than creating the string every time you need it.

If it isn't, then creating the string every time is probably the better solution, however, you could also create a string object. Like
```C
napi_value global, string_ctor, string, string_object;
NAPI_CALL(env, napi_get_global(env, &global));
NAPI_CALL(env, napi_get_named_property(env, global, "String", &string_ctor));
NAPI_CALL(env, napi_create_string_utf8(env, "MyString", NAPI_AUTO_LENGTH, &string));
NAPI_CALL(env, napi_new_instance(env, string_ctor, 1, &string, &string_object));
```
Now `string_object` is of type object, but it's an instance of class `String`. Thus, you can store a persistent reference to it.

**Comment by gireeshpunathil** [comment]
ping @battila7

**Comment by battila7** [comment]
Sorry, I never answered, somehow got lost :)

The String object solution proposed by @gabrielschulhof looks pretty good, however I haven't had the chance since to benchmark it. However, I definitely consider it as a solution, and close the issue.

Thanks for the very detailed and helpful answers!
