### ISSUE TITLE
Handle TLS renegotiation at client side

### ISSUE THREAD

**Issue by jotaeler** [nodejs/help#1906]
* **Node.js Version**: v8.10.0
* **OS**: Ubuntu 18.10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: HTTPS module

I have a Nodejs server with some API endpoints. One of them requires client authentication through SSL certificates, so server initiates a TLS renegotiation in that endpoint. That works fine if I go to this endpoint with Firefox or Chrome but not with a custom nodejs client.

```js
const https = require('https');
const fs = require('fs');

const options = {
  hostname: 'localhost',
  port: 1337,
  path: '/api/nodes_endpoint/json/20?data=eeeeeee',
  method: 'GET',
  key: fs.readFileSync('/home/jose/Escritorio/test.key'),
  cert: fs.readFileSync('/home/jose/Escritorio/test.cert'),
  rejectUnauthorized: false
};

options.agent = new https.Agent(options);

const req = https.request(options, (res) => {
  console.log('statusCode:', res.statusCode);
  console.log('headers:', res.headers);

  res.on('data', (d) => {
    process.stdout.write(d);
  });
});

req.on('error', (e) => {
  console.error(e);
});
req.end();
```
After the server request the TLS renegotiation, the object that should contain the client certificate is NULL, so I suppose that the client is not handling correctly the TLS renegotiation.

The output when I execute the above code:
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }

```

**Comment by jotaeler** [comment]
It seems that adding `secureOptions: constants.SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION ` to the options of `https.createServer({secureOptions:...})` solved the issue.

Got from [this issue](https://github.com/nodejs/node/issues/2259)

**Comment by gireeshpunathil** [comment]
@jotaeler - is there anything outstanding here?

**Comment by gireeshpunathil** [comment]
answered, closing
