### ISSUE TITLE
Inspector port 127.0.0.1:9229 timing out

### ISSUE THREAD

**Issue by 4rch1m3d35** [nodejs/help#1909]
Node.js Version: 12.2.0
OS: Windows 10
Using: VSC
I'm trying to use the debugger and it keeps giving me this error
 ```
$ node inspect app.js
Timeout (2000) waiting for 127.0.0.1:9229 to be free
```
no other terminals are open and i used netstat in the command terminal to see if the port is being used and it isn't

Can someone plz give me a hand

**Comment by gireeshpunathil** [comment]
@4rch1m3d35 - for diagnostic purpose, can you just change the port and see if it connects?

**Comment by 4rch1m3d35** [comment]
@gireeshpunathil 
```
$ node inspect --port=9227 app.js
Timeout (2000) waiting for 127.0.0.1:9227 to be free
```

**Comment by gireeshpunathil** [comment]
I mean to ask, to use another port - to isolate the issue between node that is unable to listen, or port being reported as in use incorrectly:
```
node --inspect=127.0.0.1:9230
```

**Comment by 4rch1m3d35** [comment]
it worked, but any idea why the default port isn't working?

**Comment by gireeshpunathil** [comment]
I don't know! btw, 
 - default port is `9229`, not `9227`. 
 - you don't need to specify `--port` flag for default, it picks it up being default.
 - probably a reboot and try may be a good idea.

**Comment by 4rch1m3d35** [comment]
already rebooted multiple times still doesn't work

**Comment by gireeshpunathil** [comment]
ok, I see you first tried the default (`9229`) as well.

I don't know how to debug this in windows. In UNIX, typically I will:
 - run node under system trace (`strace`) and see what happens to `bind` system call that actually binds the port the socket.
 - if it passes then debug further in node to see why the listening fails
 - if it fails then use network diagnostics to see who `owns` the port (`lsof` etc.)

**Comment by 4rch1m3d35** [comment]
Update: changing the port only allows inspector to run on the container folder not on the actual js file

**Comment by gireeshpunathil** [comment]
I am not sure I follow that; however pinging @nodejs/v8-inspector to see if they know about this and provide further guidance.

**Comment by 4rch1m3d35** [comment]
thank you

**Comment by PoojaDurgad** [comment]
@4rch1m3d35 , is this issue still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing. feel free to reopen if still an issue
