### ISSUE TITLE
Approach to store image data on third party server

### ISSUE THREAD

**Issue by mehta-rohan** [nodejs/help#191]
*node @0.12.2 *:
window 64:
Cloudinary:
Hi there I have my project requirement: to upload image on server
I am using multer module to take it from locale machine to server 
I am using Cloudinary as third party server to hold my image
It's Like 
Browser->NodeServer->Cloudinary
I don't want a copy of my image on Node Server 
Is this right approach to handle this.

**Comment by lordKnighton** [comment]
Hey @mehta-rohan you still need help with this? I'm down, to give it a shot.

**Comment by mehta-rohan** [comment]
yes please Sir @lordKnighton

**Comment by addaleax** [comment]
@mehta-rohan Have you seen https://github.com/cloudinary/cloudinary_npm#cloudinaryupload_stream ? It sounds like you can call `stream.pipe(cloudinary.uploader.upload_stream(function(result) { console.log(result); }))` on any kind of input `stream`, it doesn’t have to be an `fs.ReadStream`.

**Comment by mehta-rohan** [comment]
@addaleax thank you sir...
can you comment on the way I am doing this stuff?

**Comment by addaleax** [comment]
> thank you sir...

@mehta-rohan not exactly a sir. :)

> can you comment on the way I am doing this stuff?

You mean, uploading the file to your node server and directly streaming it to the storage site, without using a temporary file? That sounds perfectly good to me.

**Comment by mehta-rohan** [comment]
@addaleax :)
sorry ma'am pardon!!
thanks for comment
Cheers
