### ISSUE TITLE
How to build node without standard include paths?

### ISSUE THREAD

**Issue by niks3089** [nodejs/help#1910]
* **11.14.0:**:
* **Ubuntu 18.04**:
* **Runtime**:

I would like to build node with `-nostdinc` and `-nostdinc++` and by specifying my custom include headers with `-I/custom/include/path/goes/here`, how to I modify the build system to be able to build node like this?

**Comment by gireeshpunathil** [comment]
@niks3089 - `node.gyp` in the top level source folder defines and controls the build configuration. It is not easy to describe its structure in a couple of lines, but it is organized, and you can find your section based on your target (node exe or node shlib) and within that based on your other constraints (like OS). In that section you could append your compiler options to existing flags.

**Comment by niks3089** [comment]
Thanks @gireeshpunathil : I am trying to build node as a static library. i.e by doing `/configure  --fully-static --enable-static`. Does that come under node exe? Also after I change `node.gyp`, will running make be sufficient? I tried to change some setting and when I run `make`, I  don't see those changes reflected during make. May be I am missing something?

**Comment by gireeshpunathil** [comment]
@niks3089 -
 - any changes to node.gyp, you need to reconfigure: `./configure --fully-static ...` prior to make
 - if you are building static lib, I guess your target in node.gyp is going to be `'target_name': '<(node_lib_target_name)'` ... meaning your custom changes should go under this section
 - if you want to see the changes are reflected in the makefiles, you could turn on verbosity. Run `make V=1` to see the full compiler / linker command line arguments.

**Comment by gireeshpunathil** [comment]
ping @niks3089

**Comment by gireeshpunathil** [comment]
answered, closing
