### ISSUE TITLE
CLI arg handling affected by `argv[0]`

### ISSUE THREAD

**Issue by matthew-mcallister** [nodejs/help#1914]
* **Node.js Version**: 10.10 through 11.6
* **OS**: Debian buster / Linux 4.19 / x86_64
* **Scope (install, code, runtime, meta, other?)**: cli
* **Module (and version) (if relevant)**:

I'm having an issue that may or may not be a bug. I'm using nvm to download node. If one of the above versions of node is on the path and I execute it as `node`, some CLI args are effectively ignored and node drops into a REPL:
```bash
mattmcal:~$ cp ~/.nvm/versions/node/v10.15.3/bin/node /tmp
mattmcal:~$ sudo adduser --no-create-home tmpuser
mattmcal:~$ cd /tmp
mattmcal:/tmp$ sudo -u tmpuser env - sh
$ export
export PWD='/tmp'
$ export PATH="/tmp:$PATH"
$ which node
/tmp/node
$ node -v
v10.15.3
$ node -h
> Aborted
$ node -p 42
> Aborted
$ node -e "console.log(42)"
> Aborted
```
However, if I run it by file path as `./node`, everything works fine:
```
$ ./node -h
Usage: ...
$ ./node -p 42
42
$ ./node -e "console.log(42)"
42
```
I found this issue because a package on npm used `node -e` in a post-install command.

This only affects my system; if I test node on the `debian:buster-slim` docker image, there is no issue. Since I couldn't reproduce it, I'm hesitant to assert that it's a bug, but later and earlier versions of node work fine, so something did change somewhere in node.

EDIT: I ran `git bisect` on this and found that it was fixed by https://github.com/nodejs/node/commit/c6adf4b44fc44e6d6137054ed44b68e217c59811. A bit uncertain about that though.

**Comment by gireeshpunathil** [comment]
@matthew-mcallister - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive; closing. pls reopen if still outstanding
