### ISSUE TITLE
update to Node v12.2 Got A Https Request Error

### ISSUE THREAD

**Issue by moriyalb** [nodejs/help#1915]
My Https Server Got A Request Error When I Upgrade Node from v11.10.1 to v12.2.0

![image](https://user-images.githubusercontent.com/6511081/57838269-f81fbb00-77f6-11e9-8000-8c6f8cddfb03.png)

The Code is simple Like that. before upgrading everything is fine.

when upgraded. 
Https Server On Windows ---- Everything is Fine.
Https Server On Linus(CentOS7.4) ----> Browser/HttpDebug in windows is fine. But In Unity Client, we got an error like 

> ","System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. --

Is that our unity problem or a new node version problem ?

**Comment by shellberg** [comment]
The errors you are getting are associated with .NET rather than Node.  I'd start by prioritising this as a Unity Client on Windows problem rather than an Node issue.

**Comment by bnoordhuis** [comment]
Note that Node.js v12 disables TLS versions < v1.2. You can re-enable them (for now) with the `--tls-min-v1.0` and `--tls-min-v1.1` flags.

If that fixes your issue you should get in touch with the maintainers of Unity Client because support for TLS < v1.2 will eventually be removed altogether.

**Comment by moriyalb** [comment]
> Note that Node.js v12 disables TLS versions < v1.2. You can re-enable them (for now) with the `--tls-min-v1.0` and `--tls-min-v1.1` flags.
> 
> If that fixes your issue you should get in touch with the maintainers of Unity Client because support for TLS < v1.2 will eventually be removed altogether.

Ok, Thank you.
