### ISSUE TITLE
How to open terminal/shell session via server request

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1917]
I can open up bash and type commands from my local terminal into a remote bash process like so:

```js
const net = require('net');
const cp = require('child_process');

const server = net.createServer(s => {

  const bash = cp.spawn('bash');
  s.pipe(bash.stdin, {end:false});
  bash.stdout.pipe(s);
  bash.stderr.pipe(s);


});

server.listen('4004');
```

but the problem is, I don't get prompts like this:

```
<hostname>:<basename> <user> $`
```

I just get blank space which I can type into which is different than a terminal

**Comment by ORESoftware** [comment]
I am still looking for answers to this, I updated the question with a bounty here:
https://stackoverflow.com/questions/56174957/open-up-shell-on-server-via-http-request/56175507

**Comment by gireeshpunathil** [comment]
I ran `bash` with output as console and with output redirecting to a file. In the former case, the `bash` itself prints the necessary `eye-catcher` text, but in later, it does not.

So it looks like in our case we won't have it coming from `bash`.

**Comment by gireeshpunathil** [comment]
in either way, can you try forcing interactive flag ? `cp.spawn('bash', ['-i']); `

I am not sure whether it will have any other side effect on other parts of its execution though

**Comment by gireeshpunathil** [comment]
@ORESoftware - is this resolved?
