### ISSUE TITLE
EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by Crazie-ash** [nodejs/help#1923]
![image_2019_05_21T04_31_51_305Z - Copy](https://user-images.githubusercontent.com/45698249/58179478-e68e5580-7cc5-11e9-9587-1b0018f72b24.png)

npm v6.4.1
node v10.15.3

can u pls help me resolving this issue??

**Comment by LittleControl** [comment]
That's meaning you have no permission to do this operation
you can have a try in Windows Administrator

**Comment by gireeshpunathil** [comment]
ping @Crazie-ash

**Comment by Crazie-ash** [comment]
@gireeshpunathil yes... 
I got it resolved.... it is because the process was running before the user login to their PC. i then handled it accordingly

**Comment by gireeshpunathil** [comment]
@Crazie-ash - thanks for the info. closing this, cheers!
