### ISSUE TITLE
Unhandled rejection Error: EISDIR: illegal operation on a directory, open '/Users/robert/.npm/_cacache/content-v2/sha512/c7/06'     at Error (native)

### ISSUE THREAD

**Issue by wiroger9595** [nodejs/help#1925]
* **10.15.3**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robert/.npm/_logs/2019-05-24T19_09_49_247Z-debug.log
roberts-MacBook-Air:~ robert$

**Comment by gireeshpunathil** [comment]
@wiroger9595 - can you please make `/Users/robert/.npm/_logs/2019-05-24T19_09_49_247Z-debug.log` available for inspection?

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by noufal-kmc** [comment]
@gireeshpunathil here is the complete log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'apollo' ]
2 info using npm@6.9.0
3 info using node@v9.4.0
4 verbose npm-session 3b1d2e42f0881f12
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 timing npm Completed in 845ms
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://npm.community>

**Comment by noufal-kmc** [comment]
It worked after I installed the latest node package v10.16.0
