### ISSUE TITLE
tls connection to remote server fails to check server identity

### ISSUE THREAD

**Issue by danieljee** [nodejs/help#1928]
* **Node.js Version**: 11.7.0
* **OS**: Linux Mint 19
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Hi,

I was using a [NATS server client module](https://github.com/nats-io/nats.js) which tried to establish TLS connection to my remote server. TLS handshake was successful but the problem occurred in the certificate checking code in 'onConnectSecure' function in [_tls_wrap.js](https://github.com/nodejs/node/blob/master/lib/_tls_wrap.js). The code where the problem occurred is
```js
if (!verifyError && !this.isSessionReused()) {
    const hostname = options.servername ||
                   options.host ||
                   (options.socket && options.socket._host) ||
                   'localhost';
    const cert = this.getPeerCertificate(true);
    verifyError = options.checkServerIdentity(hostname, cert);
  }
```
The _hostname_ variable was assigned value of 'localhost' because _options.host_ was not defined and _options.socket._host_ was set to null. However the value of _options.socket.remoteAddress_ did have the correct IP address of the remote server.

Shouldn't this code also check for _options.socket.remoteAddress_ for the remote hostname?

Cheers.
-->

**Comment by wide4head** [comment]
@danieljee Not necessarily. The IP Address can change across sessions.

**Comment by danieljee** [comment]
@wide4head Oh right my bad.
