### ISSUE TITLE
Http Request: Socket Hang Up

### ISSUE THREAD

**Issue by ChrisX212** [nodejs/help#193]
Moved over because I got the wrong place in the first go.

I am running the Tutorial Point of Node JS and found a problem in the web module section on how to create a web client with Node. Full page here:

http://www.tutorialspoint.com/nodejs/nodejs_web_module.htm

I already set up the server with server.js and ran it, but when I try to run the client.js, which is like this:

```js
var http = require('http');

// Options to be used by request
var options = {
host: 'localhost',
port: '8081',
path: 'index.html'

};

// Callback function is used to deal with response
var callback = function(response){
// Continuously update stream with data
var body = '';
response.on('data', function(data) {
body += data;
});

response.on('end', function() {
// Data received completely.
console.log(body);
});
}
// Make a request to the server
var req = http.request(options, callback);
req.end();
```
It gives out a 'Socket Hang Up' error. I don't know what just happened here and how to fix it.

Can anyone help?

Thanks.

**Comment by lordKnighton** [comment]
```js path: 'index.html ```  

--
try   ```js path: '/index.html ```
