### ISSUE TITLE
node https module as a client  prevent middlemen from capturing packets

### ISSUE THREAD

**Issue by LNyears** [nodejs/help#1931]
Hello, I have a need for help here.
I use the node https module as a client to send https requests. How to prevent middleman packet capture attacks, what should I do?

**Comment by wide4head** [comment]
@LNyears My understanding is that https by itself is designed to prevent those attacks. Correct me if I am wrong.

**Comment by gireeshpunathil** [comment]
ping @LNyears

**Comment by gireeshpunathil** [comment]
inactive; closing. pls reopen if still outstanding
