### ISSUE TITLE
console.log does not output the request and response objects

### ISSUE THREAD

**Issue by midnightcoder-pro** [nodejs/help#1933]
* **Version**: 12.3.1
* **Platform**: Windows 10 1809

console.log does not output the request and response objects

```js
require('http').createServer((req, res) => {
  res.end('test')
  console.log(res)
}).listen(80)
```

**Comment by renanbastos93** [comment]
I tested now your code in the same version and on windows 10. It was worked with succeed.

**Comment by yathamravali** [comment]
@midnightcoder-pro 
Even I have tested and it is working fine.

Regarding your statement - it doesn't work the second time : U mean not able to print the response object?

**Comment by midnightcoder-pro** [comment]
@yathamravali 
The code just hangs
I also forgot to mention that I use the --inspect switch

**Comment by midnightcoder-pro** [comment]
I found a problem
I use this command to restart node:
```
tskill node > nul 2>&1 & node --inspect=9000 ./api/index.js | node --inspect=9001 ./web/index.js
```
And parallel launch somehow prevents this

**Comment by midnightcoder-pro** [comment]
This solved the problem:
```
tskill node > nul 2>&1 & node --inspect=9000 D:/Desktop/midnightcoders.pro/api/index.js > nul 2>&1 | node --inspect=9001 D:/Desktop/midnightcoders.pro/web/index.js > nul 2>&1
```
