### ISSUE TITLE
where is bootstrap_node.js file

### ISSUE THREAD

**Issue by Mllions-c** [nodejs/help#1935]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by Mllions-c** [comment]
1.When was it removed? 
2.What is being replaced now?

**Comment by yathamravali** [comment]
@Mllions-c 
In source code `bootstrap_node.js` file is in this path `node/lib/internal/bootstrap/node.js` (For current release and LTS v10.x)

**Comment by gireeshpunathil** [comment]
ping @Mllions-c

**Comment by gireeshpunathil** [comment]
answered, closing
