### ISSUE TITLE
persistent global configuration

### ISSUE THREAD

**Issue by sysmat** [nodejs/help#1937]
* **Node.js Version**: v10.16.0
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**: runtime, meta(don't know)
* **Module (and version) (if relevant)**:

Node support cli options, but why doesn't support some persistent configuration (aka. some json file in installation directory)?

Regards, Tomaž

**Comment by gireeshpunathil** [comment]
@sysmat - we have `NODE_OPTIONS` environment variable that can be used to pass many of the cli options, and `NODE_OPTIONS` can be persisted.

hope that helps with your use case?

**Comment by gireeshpunathil** [comment]
answered, closing
