### ISSUE TITLE
node.js equivalent to telnet

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1939]
I am looking for the Node.js equivalent for:

```bash
telnet <host> <port>
```

I would guess it's

```js
const s = net.connect(port,host);

s.once('data', () => {
  // OK
});

s.once('error', () => {
  // not ok
});
```

or is there a better way to replicate telnet?

**Comment by wide4head** [comment]
@ORESoftware 
Please check https://www.npmjs.com/package/telnet-client

**Comment by gireeshpunathil** [comment]
ping @ORESoftware - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if this is still outstanding.
