### ISSUE TITLE
Will 'ReadLine' load the whole of the file into memory?

### ISSUE THREAD

**Issue by hanu412** [nodejs/help#194]
Hello ,

I am trying to build a module which would read each line from a given flat file , process the string and then store it in a database/write to another file.

The requirement says the file could be as huge as 1Gb and can go upto 3Gb. I am using 'ReadLine' module so as to read the stream line by line.

Will the following code result in loading the whole of the 1Gb file into the memory? Kindly advise! 

const readline = require('readline');
const fs = require('fs');
const fileName = 'HR.KIM.TF.MI04MR2H.TANF0416.txt';
const rl = readline.createInterface({
  input: fs.createReadStream(fileName),
  output: outputStream
});

var outputStream = fs.createWriteStream('result.txt');

var counter =0 ;
rl.on('line', (line) => {
//Do some processing and then write it to the file
outputStream.write(line);
});

rl.on('close', (line) => {
console.log('total number of lines ' + counter);
});

**Comment by vsemozhetbyt** [comment]
Could you add the code example?

**Comment by hanu412** [comment]
I had added the code.

**Comment by vsemozhetbyt** [comment]
I've read files up to 2GB with `readline` without any memory problems. However I used synchronous processing/writing, I don't know if async writing can create a big buffer queue in the memory. It seems synchronous writing could not.

**Comment by hanu412** [comment]
could you add the code/pseudo code you had written as an example?

**Comment by vsemozhetbyt** [comment]
It's pretty much as yours. This script reads input file line and write it to output file with line number. For 1.6 GB file and ~ 30 000 000 lines it takes ~ 60 MB memory.

```js
/******************************************************************************/
'use strict';
/******************************************************************************/
const fpath = process.argv[2];

if (!fpath) {
  console.error('Add the file path, please.');
  process.exit(1);
}
/******************************************************************************/
const fs = require('fs');
const rl = require('readline');

const inCoding  = 'utf16le';
const outCoding = 'utf16le';
const bomRE = /^\uFEFF/;

const rli = rl.createInterface({ input: fs.createReadStream(fpath, inCoding) });

const toChangeFileNameRE = /(\.[^.]+)?$/;
const outfile =  fs.openSync(fpath.replace(toChangeFileNameRE, '.new$1'), 'w');
fs.writeSync(outfile, '\uFEFF', null, outCoding);
/******************************************************************************/
let lineNumber = 0;

rli.on('line', line => {
  if (++lineNumber === 1) line = line.replace(bomRE, '');

  fs.writeSync(outfile, `${lineNumber} ${line}\n`, null, outCoding);
}).on('close', () => {
  console.log(`Lines processed: ${lineNumber}.`);
  console.log(process.memoryUsage());
});
/******************************************************************************/
```

```
Lines processed: 29293359.
{ rss: 63279104, heapTotal: 50327552, heapUsed: 13451592 }
```

**Comment by vsemozhetbyt** [comment]
And I've watched the memory during all the processing, it remained the same all the time.

**Comment by Trott** [comment]
(Closed this because it's been inactive for three months and it seems like there is something like an answer to the question. However, if I'm mis-reading and it should really stay open, please comment to that effect. Thanks!)

**Comment by gonzazoid** [comment]
Hi, guys!
I'm not sure, may be there is no problem here, but I'm curious. Look at this code:

```javascript
const readline = require('readline');
const fs = require('fs');

if(true){

    const xxxxx = readline.createInterface({
      input: fs.createReadStream('sample.txt'),
      crlfDelay: Infinity
    });

    xxxxx.on('line', function(line){
      console.log(`Line from file: ${line}`);
    });
} 
```

It's mostly the same as code from documentation (https://nodejs.org/api/readline.html#readline_example_read_file_stream_line_by_line) except that readline interface is in local scope. And it works fine which is a problem in my opinion. Because I believe it shouldn't.
When we go beyond `if(true)` scope,  `const xxxxx` supposed to be destroyed but it isn't. So question is - if it is not destroyed after out of scope how can we be sure it is destroyed at all (even after reading whole file and `close` event)?
I'm trying to figure out it with debugger and profiler but it seems like I don't have yet enough skills to do it, so I'll be happy with any help.

**Comment by Trott** [comment]
Hi, @gonzazoid! Your code does not use `xxxxx` outside of the `if(true)` block scope. It both creates and uses `xxxxx` inside that block.  Here it is modified with assertions to confirm:

```js
const readline = require('readline');
const fs = require('fs');

if(true){

    const xxxxx = readline.createInterface({
      input: fs.createReadStream('sample.txt'),
      crlfDelay: Infinity
    });

    xxxxx.on('line', function(line){
      console.log(`Line from file: ${line}`);
    });

    console.log(typeof xxxxx); // 'object'
} 

console.log(typeof xxxxx); // 'undefined'
```

(Also: Not all of us are _guys_. Consider using _everyone_, _people_, _friends_, _folks_,  or something like that.)
