### ISSUE TITLE
question about process.stdin.on

### ISSUE THREAD

**Issue by PkNuAbrahim** [nodejs/help#1940]
i wanna connect app<->raspberry pi server <-> arduino bluetooth module 
and i used this code 

```js
if(req.payload.toString() ==='0'){
           console.log('0');
            process.stdin.on('data', function (data) {
                var buf1 = Buffer.from(data);
                serial.write(buf1, function(err, bytesWritten){
                    if(err) console.log(err);
                });
            });

            serial.on('data', function(data) {
                console.log('Received: '+data );
            });
```

this code need console input but i want to send value without console input
how can i do?

**Comment by addaleax** [comment]
Depends – what data do you want to send?

If you “just” want to send a Buffer with a fixed content, you can use something like `buf1 = Buffer.from("hello, world!");`, and then send that.

**Comment by PkNuAbrahim** [comment]
@addaleax  i wanna send '0' to bluetooth module when i got '0' from app 
as you say i fixed code 
if(req.payload.toString() ==='0'){
            process.stdin.on('data', function (data) {
                var buf1 = Buffer.from(data);
                serial.write(buf1, function(err, bytesWritten){
                    if(err) console.log(err);
                });
            });
            serial.on('data', function(data) {
                console.log('Received: '+data );
            });

but it still doesnt work  
i used 'bluetooth-serial-port' lib
i think that process.stdin need console input but i just want to send '0' without console input

**Comment by addaleax** [comment]
@PkNuAbrahim If you do not want to wait for console input, can you explain why you are using `proecss.stdin.on('data')`? I don’t think that should be necessary here…

And by the way, you can wrap pieces of source code that you post on github in  ```` ``` ```` so that it becomes more readable, for example:

    ```js
    console.log('Hello world!');
    ```

becomes

```js
console.log('Hello world!');
```

:slightly_smiling_face:

**Comment by PkNuAbrahim** [comment]
oh thank you to teach that 

'''js
 if(req.payload.toString() ==='0'){
        
        serial.write(Buffer.from('0'), function (err, bytesWritten) {
        if (err) {
            console.log('Error!');
        } else {
            console.log('Send ' + bytesWritten + ' to the client!');
        }
    });
    serial.on(Buffer.from('0'), function() {
                console.log('Received: ');
            });
            
    }
'''
so i changed that , but nothing show in arduino serial monitor

**Comment by addaleax** [comment]
@PkNuAbrahim I’m not sure why nothing is shown as being transmitted (wild guess – maybe you need newlines, e.g. `Buffer.from('0\n')`?), but you definitely want to keep `serial.on('data', ...)` instead of `serial.on(Buffer.from('0'), ...)`.

**Comment by gireeshpunathil** [comment]
ping @PkNuAbrahim

**Comment by gireeshpunathil** [comment]
answered, closing
