### ISSUE TITLE
Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by sudrizzz** [nodejs/help#1941]
node -v
> v10.16.0

npm -v
> 6.9.0

commad
> npm install -g hexo-cli
> from https://hexo.io/docs/

platform
> windows 1903 18362.145 with Windows PowerShell

log
```log
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Software\\nodejs\\node.exe',
1 verbose cli   'D:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'hexo-cli' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 63fbe32fbd21f92e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for hexo-cli@latest Cannot read property 'resolve' of undefined
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 32ms
10 verbose stack TypeError: Cannot read property 'resolve' of undefined
10 verbose stack     at regFetch (D:\Software\nodejs\node_modules\npm\node_modules\npm-registry-fetch\index.js:76:23)
10 verbose stack     at fetchPackument (D:\Software\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:42:10)
10 verbose stack     at packument (D:\Software\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:20:10)
10 verbose stack     at getManifest (D:\Software\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:22:10)
10 verbose stack     at manifest (D:\Software\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:13:10)
10 verbose stack     at Object.manifest (D:\Software\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\index.js:17:12)
10 verbose stack     at Object.Fetcher#manifest [as manifest] (D:\Software\nodejs\node_modules\npm\node_modules\genfun\lib\genfun.js:15:38)
10 verbose stack     at manifest (D:\Software\nodejs\node_modules\npm\node_modules\pacote\lib\fetch.js:23:18)
10 verbose stack     at pinflight (D:\Software\nodejs\node_modules\npm\node_modules\pacote\manifest.js:24:12)
10 verbose stack     at D:\Software\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
10 verbose stack     at Promise._execute (D:\Software\nodejs\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:313:9)
10 verbose stack     at Promise._resolveFromExecutor (D:\Software\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:483:18)
10 verbose stack     at new Promise (D:\Software\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
10 verbose stack     at _inflight (D:\Software\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
10 verbose stack     at D:\Software\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
10 verbose stack     at tryCatcher (D:\Software\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose cwd D:\Blog
12 verbose Windows_NT 10.0.18362
13 verbose argv "D:\\Software\\nodejs\\node.exe" "D:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "hexo-cli"
14 verbose node v10.16.0
15 verbose npm  v6.9.0
16 error Cannot read property 'resolve' of undefined
17 verbose exit [ 1, true ]

```

**Comment by ganapativs** [comment]
Same issue with node 10.16.0 to 12.4.0. Works fine with 10.6.0 though!

**Comment by ganapativs** [comment]
Re installing latest `npm` using the command `curl -L https://www.npmjs.com/install.sh | sh` fixes the issue in MacOS 🎉

**Comment by PowerfulPony** [comment]
on windows a similar situation, rolled back to 6.8.0, there is no such problem.

**Comment by sudrizzz** [comment]
> Re installing latest `npm` using the command `curl -L https://www.npmjs.com/install.sh | sh` fixes the issue in MacOS 🎉

thx a lot, I rolled nodejs back to `v8.16`, and it works fine.

**Comment by WriestTavo** [comment]
Yo igual tenía problemas con la versión de Windows e instale esta versión y se solucionó el problema 
Windows 64-bit Installer: https://nodejs.org/dist/v10.15.3/node-v10.15.3-x64.msi

**Comment by GaryB432** [comment]
is it the official recommendation to downgrade to 10.15 for windows?

**Comment by danieldicesare** [comment]
I downgraded to 10.15 and it worked

**Comment by contrerasmarc** [comment]
Downgrade works for me (node 10.15)!

**Comment by jongfeel** [comment]
God save me!

I have same error and node downgraded to 10.15.3 and works!

Detail info
- Windows 10.0.18362.207
- node 12.5.0
- npm 6.9.0

Do not works any command "npm i xxx"
and got this error
----
TypeError: Cannot read property 'resolve' of undefined
----

**Comment by jenergm** [comment]
I don't believe. I f**** my build server because this version!

**Comment by reyou** [comment]
Thanks to @jongfeel for his tip installing following fixed the problem;
https://nodejs.org/download/release/v10.15.3/

All Releases:
https://nodejs.org/en/download/releases/

**Comment by Codedecks** [comment]
I too has the same problem, downgraded to Node 10.15.0 work for me.

**Comment by brainee** [comment]
i resolve it with curl -L https://www.npmjs.com/install.sh |sodu sh

**Comment by eballeste** [comment]
this was happening to me as well but I was using the `n` package manager

what I did to solve it was downgrade my node version to an old version where `npm` doesn't throw a tantrum and install the latest version of `n`, after that all was good

`npm i -g n@latest`

**Comment by iampeterbanjo** [comment]
version 12.6.0 worked for me

**Comment by mkotsollaris** [comment]
What solved it for me (Windows 10) was to install the 32 bit of 10.16.3 version.

**Comment by arushraj** [comment]
I'm also having the same problem, installed the 10.15.3 version of node js and problem got solved...

**Comment by davidkeaveny** [comment]
Downgrading from 10.16.3 to 10.15.3 fixed things for me. Even the 12.3 LTS version didn't work.

**Comment by zhan4139** [comment]
I'm using `n` and switching node from `10.16.3` to `10.15.0` works for me:
```
n 10.15.0
```

**Comment by ccarv** [comment]
I am too experiencing this on Windows.

**Comment by TheRyanHickman** [comment]
> i resolve it with curl -L https://www.npmjs.com/install.sh |sodu sh

curl -L https://www.npmjs.com/install.sh | sudo sh

**Comment by hackerstarkr** [comment]
> Yo igual tenía problemas con la versión de Windows e instale esta versión y se solucionó el problema
> Windows 64-bit Installer: https://nodejs.org/dist/v10.15.3/node-v10.15.3-x64.msi

thanks for your help it really worked

**Comment by AlienLogic** [comment]
I had the same problem with @vue/cli, solved without downgrade.

Completelly uninstalled node.js
Manually delete node.js installation folder and any node's folder in %appdata% and &localappdata%
Reboot system
Reinstall node.js and reboot again

Windows 10 1809

![2020-06-01 18-24-00 (Amministratore_Prompt_dei_comandi)](https://user-images.githubusercontent.com/47600882/83429963-2c334180-a435-11ea-8e43-ff52ca192afa.png)

Probably cache mistake?

**Comment by crtl** [comment]
**`import * as path from "path"`** instead of `import path from "path"` fixed it for me without updating node.
