### ISSUE TITLE
node.js install location

### ISSUE THREAD

**Issue by agiantfreakingsteak** [nodejs/help#1943]
When installing node.js, it ends up installing it in an incorrect location. I place the installer package in the correct folder for my JS code: /Users/lucas/Coursera/Site

But when I run the 'echo $PATH' in my terminal to check if the location is correct, I get...
echo $PATH
/Users/lucas/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Why is it going into my Python directory? I've tried uninstalling and deleting this file path, but it seems stuck on it... Even though that file path no longer exists

Thanks!

**Comment by gireeshpunathil** [comment]
ping @agiantfreakingsteak

**Comment by gireeshpunathil** [comment]
answered, closing
