### ISSUE TITLE
Is there any way to prevent sorting npm-packages automatically in package.json after “npm install”?

### ISSUE THREAD

**Issue by nh0627** [nodejs/help#1946]
* **Node.js Version*8*:
* **OS*Linux*:
* **Scope (runtime)**:
* **Module (and version) (if relevant)**:

Hi! My team wants to sort a list of packages in pacakge.json by ourselves (to group them).

However, after "npm install some-package", the list is automatically sorted alphabetically in package.json.

Is there any npm-package or any way to prevent this automatic sorting in package-json?

Thanks!

**Comment by wide4head** [comment]
@nh0627 Hopefully this article will give you a clue https://www.npmjs.com/package/sort-package-json

**Comment by gireeshpunathil** [comment]
ping @nh0627

**Comment by gireeshpunathil** [comment]
inactive; closing. pls reopen if still outstanding
