### ISSUE TITLE
Node profiling/isolate processing produces Chinese text.

### ISSUE THREAD

**Issue by denholtz** [nodejs/help#1947]
* **Node.js Version**: 10.15.3
* **OS**: Windows 10 
* **Scope **: Profiling

I'm trying to work with node's built in profiling tools. Here is the code I am trying to profile:
`console.log('hello world');`

node --prof app.js produces an isolate file as expected:
`v8-version,6,8,275,32,-node.51,0
shared-library,C:\Program Files\nodejs\node.exe,0x7ff6c05a0000,0x7ff6c1d0a000,0
shared-library,C:\Windows\SYSTEM32\ntdll.dll,0x7ffafe730000,0x7ffafe91d000,0
shared-library,C:\Windows\System32\KERNEL32.DLL,0x7ffafbb80000,0x7ffafbc33000,0
shared-library,C:\Windows\System32\KERNELBASE.dll,0x7ffafb2b0000,0x7ffafb543000,0
shared-library,C:\Windows\System32\ADVAPI32.dll,0x7ffafe650000,0x7ffafe6f3000,0
shared-library,C:\Windows\System32\msvcrt.dll,0x7ffafe1b0000,0x7ffafe24e000,0
shared-library,C:\Windows\SYSTEM32\dbghelp.dll,0x7ffaed090000,0x7ffaed27d000,0
...`

node --prof-process isolate-00000200908C4840-v8.log > processed.txt produces the following text file:

`瑓瑡獩楴慣⁬牰景汩湩⁧敲畳瑬映潲⁭獩汯瑡ⵥ〰〰㈰〰〹䌸㠴〴瘭⸸潬Ⱨ⠠㤳琠捩獫‬‱湵捡潣湵整Ɽ〠攠捸畬敤⥤ਮ 卛慨敲⁤楬牢牡敩嵳਺†琠捩獫†潴慴⁬渠湯楬⁢†慮敭 ††㜲†㘠⸹┲†††††㩃愀⁭楆敬ੳ摯橥ੳ摯⹥硥੥††ㄠ‱†㠲㈮‥††††䌠:獷䴀㈳琊汤⹬汤੬ 䩛癡卡牣灩嵴਺†琠捩獫†潴慴⁬渠湯楬⁢†慮敭ਊ嬠⭃崫਺†琠捩獫†潴慴⁬渠湯楬⁢†慮敭ਊ嬠畓浭牡嵹਺†琠捩獫†潴慴⁬渠湯楬⁢†慮敭 ††〠††⸰┰††⸰┰†慊慶捓楲瑰 ††〠††⸰┰††⸰┰†⭃ਫ†††‱†㈠㘮‥ㄠ〰〮‥䜠੃††㌠‸†㜹㐮‥††††匠慨敲⁤楬牢牡敩ੳ†††‱†㈠㘮‥††††唠慮捣畯瑮摥ਊ嬠⭃‫湥牴⁹潰湩獴㩝 †楴正⁳†挠灰†琠瑯污†渠浡੥ 䉛瑯潴⁭灵⠠敨癡⥹瀠潲楦敬㩝 丠瑯㩥瀠牥散瑮条⁥桳睯⁳⁡桳牡⁥景愠瀠牡楴畣慬⁲慣汬牥椠⁮桴⁥潴慴੬†浡畯瑮漠⁦瑩⁳慰敲瑮挠污獬ਮ†慃汬牥⁳捯畣祰湩⁧敬獳琠慨⁮⸱┰愠敲渠瑯猠潨湷ਮ †楴正⁳慰敲瑮†慮敭 ††㜲†㘠⸹┲†㩃愀⁭楆敬ੳ摯橥ੳ摯⹥硥੥††㈠‴†㠸㤮‥†䌠:浡䘠汩獥漊敤獪漊敤攮數 ††㜠†㈠⸹┲†††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‷ㄠ〰〮‥†††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥敲畱物⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㔱㨰㐳 ††㈠†㈠⸸┶†††††捓楲瑰›㱾湡湯浹畯㹳愠獳牥⹴獪ㄺㄺ਱†††′ㄠ〰〮‥†††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥潣灭汩⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳〳㨳㐴 ††ㄠ†ㄠ⸴┳†††††捓楲瑰›㱾湡湯浹畯㹳甠楴⹬獪ㄺㄺ਱†††‱ㄠ〰〮‥†††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥潣灭汩⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳〳㨳㐴 ††ㄠ†ㄠ⸴┳†††††捓楲瑰›㱾湡湯浹畯㹳渠瑥樮㩳㨱ㄱ ††ㄠ†〱⸰┰††††††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‱†㐱㌮‥††††匠牣灩㩴縠愼潮祮潭獵‾湩整湲污是⽳瑳敲浡⹳獪ㄺㄺ਱†††‱ㄠ〰〮‥†††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥潣灭汩⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳〳㨳㐴 ††ㄠ†ㄠ⸴┳†††††慌祺潃灭汩㩥縠瑳牡畴⁰湩整湲污戯潯獴牴灡港摯⹥獪㌺㨰㤱 ††ㄠ†〱⸰┰††††††捓楲瑰›找潯獴牴灡潎敤半潃敲椠瑮牥慮⽬潢瑯瑳慲⽰潮敤樮㩳㔱㌺ਰ†††‱†㐱㌮‥††††䰠穡䍹浯楰敬›獾瑥灵湉灳捥潴⁲湩整湲污戯潯獴牴灡港摯⹥獪㐺㈴㈺ਸ਼†††‱ㄠ〰〮‥†††††䰠穡䍹浯楰敬›獾瑥灵汇扯污潃獮汯⁥湩整湲污戯潯獴牴灡港摯⹥獪㐺㐰㌺ਰ†††′†㠠㌮‥††䰠穡䍹浯楰敬›獾慴瑲灵椠瑮牥慮⽬潢瑯瑳慲⽰潮敤樮㩳〳ㄺਹ†††′ㄠ〰〮‥†††匠牣灩㩴縠潢瑯瑳慲买摯䩥䍓牯⁥湩整湲污戯潯獴牴灡港摯⹥獪ㄺ㨵〳 ††㈠††⸸┳†††慌祺潃灭汩㩥縠楢摮湩⁧湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㜷㌺ਹ†††‱†〵〮‥†††匠牣灩㩴縠愼潮祮潭獵‾湩整湲污甯楴⽬湩灳捥⹴獪ㄺㄺ਱†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥潣灭汩⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳〳㨳㐴 ††ㄠ†〱⸰┰††††††慌祺潃灭汩㩥縠慎楴敶潍畤敬爮煥極敲椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪ㄺ〵㌺਴†††‱†〵〮‥†††匠牣灩㩴縠愼潮祮潭獵‾湩整湲污支牲牯⹳獪ㄺㄺ਱†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥潣灭汩⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳〳㨳㐴 ††ㄠ†〱⸰┰††††††慌祺潃灭汩㩥縠慎楴敶潍畤敬爮煥極敲椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪ㄺ〵㌺਴†††‱†㐠㈮‥††匠牣灩㩴縠潢瑯瑳慲买摯䩥䍓牯⁥湩整湲污戯潯獴牴灡港摯⹥獪ㄺ㨵〳 ††ㄠ††⸴┲†††捓楲瑰›找潯獴牴灡湉整湲污潌摡牥⁳湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㈴㌺ਵ†††‱†㐠㈮‥††匠牣灩㩴縠愼潮祮潭獵‾湩整湲污甯汲樮㩳㨱ㄱ ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥敲畱物⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㔱㨰㐳 ††ㄠ†〱⸰┰††††††捓楲瑰›㱾湡湯浹畯㹳椠瑮牥慮⽬獦猯牴慥獭樮㩳㨱ㄱ ††ㄠ††⸴┲†††捓楲瑰›㱾湡湯浹畯㹳椠瑮牥慮⽬畢晦牥樮㩳㨱ㄱ ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥敲畱物⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㔱㨰㐳 ††ㄠ†〱⸰┰††††††捓楲瑰›㱾湡湯浹畯㹳戠晵敦⹲獪ㄺㄺ਱†††‱†㐠㈮‥††䰠穡䍹浯楰敬›獾慴⁴湩整湲污洯摯汵獥振獪氯慯敤⹲獪㠺㨴㐱 ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠潍畤敬弮楦摮慐桴椠瑮牥慮⽬潭畤敬⽳橣⽳潬摡牥樮㩳㈲㨱㠲 ††ㄠ†〱⸰┰†††††慌祺潃灭汩㩥縠潍畤敬弮敲潳癬䙥汩湥浡⁥湩整湲污洯摯汵獥振獪氯慯敤⹲獪㔺㠴㌺ਵ†††‱ㄠ〰〮‥†††††䰠穡䍹浯楰敬›䵾摯汵⹥江慯⁤湩整湲污洯摯汵獥振獪氯慯敤⹲獪㔺㌰㈺਴†††‱†㐠㈮‥††䰠穡䍹浯楰敬›獾楨瑦椠瑮牥慮⽬楦數彤畱略⹥獪ㄺ㐰㠺 ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠瑟捩䍫污扬捡⁫湩整湲污瀯潲散獳港硥彴楴正樮㩳ㄴ㈺ਵ†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›䵾摯汵⹥畲䵮楡⁮湩整湲污洯摯汵獥振獪氯慯敤⹲獪㜺ㄴ㈺ਸ਼†††‱ㄠ〰〮‥†††††䰠穡䍹浯楰敬›獾慴瑲灵椠瑮牥慮⽬潢瑯瑳慲⽰潮敤樮㩳〳ㄺਹ†††‱†㐠㈮‥††䰠穡䍹浯楰敬›潾据⁥癥湥獴樮㩳㠲㨹㐴 ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠牷瑩⁥潣獮汯⹥獪ㄺ㘴ㄺਵ†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›汾杯挠湯潳敬樮㩳㤱㨹㜳 ††ㄠ†〱⸰┰††††††㩃愀⁭楆敬ੳ摯橥ੳ摯⹥硥੥†††‱†㐠㈮‥††䰠穡䍹浯楰敬›摾扥杵潬⁧瑵汩樮㩳㠱㨱㠱 ††ㄠ†〱⸰┰††††捓楲瑰›㱾湡湯浹畯㹳张瑳敲浡牟慥慤汢⹥獪ㄺㄺ਱†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥潣灭汩⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳〳㨳㐴 ††ㄠ†〱⸰┰††††††慌祺潃灭汩㩥縠慎楴敶潍畤敬爮煥極敲椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪ㄺ〵㌺਴†††‱†㐠㈮‥††䰠穡䍹浯楰敬›捾敲瑡坥楲慴汢卥摴潩瑓敲浡椠瑮牥慮⽬牰捯獥⽳瑳楤⹯獪ㄺ㠵㌺ਵ†††‱ㄠ〰〮‥†††䰠穡䍹浯楰敬›松瑥瑓潤瑵椠瑮牥慮⽬牰捯獥⽳瑳楤⹯獪ㄺ㨸ㄲ ††ㄠ†〱⸰┰†††††捓楲瑰›㱾湡湯浹畯㹳挠湯潳敬樮㩳㨱ㄱ ††ㄠ†〱⸰┰††††††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‱†㐠㈮‥††䰠穡䍹浯楰敬›坾楲慴汢卥慴整张瑳敲浡睟楲慴汢⹥獪㔺㨲㌲ ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠牗瑩扡敬张瑳敲浡睟楲慴汢⹥獪ㄺ㠹ㄺਸ†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›䑾灵敬⁸獟牴慥彭畤汰硥樮㩳㜴ㄺਸ਼†††‱ㄠ〰〮‥†††††䰠穡䍹浯楰敬›卾捯敫⁴敮⹴獪㈺㐲ㄺਸ਼†††‱†㐠㈮‥††䰠穡䍹浯楰敬›䵾摯汵⹥楟楮側瑡獨椠瑮牥慮⽬潭畤敬⽳橣⽳潬摡牥樮㩳㘷㨷㤲 ††ㄠ†〱⸰┰††††捓楲瑰›㱾湡湯浹畯㹳椠瑮牥慮⽬潭畤敬⽳橣⽳潬摡牥樮㩳㨱ㄱ ††ㄠ†〱⸰┰†††††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‱ㄠ〰〮‥†††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥敲畱物⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㔱㨰㐳 ††ㄠ††⸴┲†††慌祺潃灭汩㩥縠潍畤敬弮硥整獮潩獮⸮獪椠瑮牥慮⽬潭畤敬⽳橣⽳潬摡牥樮㩳ㄷ㨰㜳 ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠潍畤敬氮慯⁤湩整湲污洯摯汵獥振獪氯慯敤⹲獪㔺ㄹ㌺ਲ਼†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›瑾祲潍畤敬潌摡椠瑮牥慮⽬潭畤敬⽳橣⽳潬摡牥樮㩳㌵㨶㌲ ††ㄠ†〱⸰┰††††††慌祺潃灭汩㩥縠潍畤敬弮潬摡椠瑮牥慮⽬潭畤敬⽳橣⽳潬摡牥樮㩳〵㨳㐲 ††ㄠ††⸴┲†††慌祺潃灭汩㩥縠潍畤敬弮潣灭汩⁥湩整湲污洯摯汵獥振獪氯慯敤⹲獪㘺㜵㌺਷†††‱ㄠ〰〮‥†††䰠穡䍹浯楰敬›䵾摯汵⹥敟瑸湥楳湯⹳樮⁳湩整湲污洯摯汵獥振獪氯慯敤⹲獪㜺〱㌺਷†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›䵾摯汵⹥潬摡椠瑮牥慮⽬潭畤敬⽳橣⽳潬摡牥樮㩳㤵㨱㌳ ††ㄠ†〱⸰┰††††††慌祺潃灭汩㩥縠牴䵹摯汵䱥慯⁤湩整湲污洯摯汵獥振獪氯慯敤⹲獪㔺㘳㈺ਲ਼ ††ㄱ†㈠⸸┲†㩃眀s㍍ਲ摴汬搮汬 ††㘠†㔠⸴┵††㩃愀⁭楆敬ੳ摯橥ੳ摯⹥硥੥†††‱†㘱㜮‥††匠牣灩㩴縠愼潮祮潭獵‾瑳敲浡樮㩳㨱ㄱ ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥敲畱物⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㔱㨰㐳 ††ㄠ†〱⸰┰††††††捓楲瑰›㱾湡湯浹畯㹳椠瑮牥慮⽬獦猯牴慥獭樮㩳㨱ㄱ ††ㄠ†ㄠ⸶┷†††捓楲瑰›㱾湡湯浹畯㹳椠瑮牥慮⽬瑵汩椯獮数瑣樮㩳㨱ㄱ ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‱ㄠ〰〮‥††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥敲畱物⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㔱㨰㐳 ††ㄠ†〱⸰┰††††††捓楲瑰›㱾湡湯浹畯㹳甠楴⹬獪ㄺㄺ਱†††‱†㘱㜮‥††匠牣灩㩴縠愼潮祮潭獵‾㔺ㄺਰ†††‱ㄠ〰〮‥†††匠牣灩㩴縠愼潮祮潭獵‾ㄺㄺ ††ㄠ†ㄠ⸶┷†††慌祺潃灭汩㩥縠敳畴偰潲散獳扏敪瑣椠瑮牥慮⽬潢瑯瑳慲⽰潮敤樮㩳㌳㨱〳 ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠瑳牡畴⁰湩整湲污戯潯獴牴灡港摯⹥獪㌺㨰㤱 ††ㄠ†〱⸰┰†††††捓楲瑰›找潯獴牴灡潎敤半潃敲椠瑮牥慮⽬潢瑯瑳慲⽰潮敤樮㩳㔱㌺ਰ†††‱†㘱㜮‥††䰠穡䍹浯楰敬›獾瑥灵牐捯獥䥳啃敖獲潩獮椠瑮牥慮⽬潢瑯瑳慲⽰潮敤樮㩳㌵㨶㔳 ††ㄠ†〱⸰┰††††慌祺潃灭汩㩥縠瑳牡畴⁰湩整湲污戯潯獴牴灡港摯⹥獪㌺㨰㤱 ††ㄠ†〱⸰┰†††††捓楲瑰›找潯獴牴灡潎敤半潃敲椠瑮牥慮⽬潢瑯瑳慲⽰潮敤樮㩳㔱㌺ਰ†††‱†㘱㜮‥††䰠穡䍹浯楰敬›楾桮牥瑩⁳瑵汩樮㩳㜲㨴㠱 ††ㄠ†〱⸰┰††††捓楲瑰›㱾湡湯浹畯㹳椠瑮牥慮⽬瑳敲浡⽳敬慧祣樮㩳㨱ㄱ ††ㄠ†〱⸰┰†††††慌祺潃灭汩㩥縠慎楴敶潍畤敬挮浯楰敬椠瑮牥慮⽬潢瑯瑳慲⽰潬摡牥⹳獪㌺㌰㐺਴†††‱ㄠ〰〮‥†††††䰠穡䍹浯楰敬›乾瑡癩䵥摯汵⹥敲畱物⁥湩整湲污戯潯獴牴灡氯慯敤獲樮㩳㔱㨰㐳ਊ†††‱†㈠㘮‥唠䭎低乗ਊ`

It seems to be producing the same Chinese text for any profiling I attempt to do. All of my language and region settings are English. I have no idea what might be causing this.

**Comment by denholtz** [comment]
If I open this with vscode it shows a message about unsupported text encoding. If I "show anyway" I get a very broken looking version of the processed report.

What determines the encoding used by node with the --prof-process flag?

**Comment by ChALkeR** [comment]
This is apparently in `utf16le`, because Windows cmd supports only that and ascii.

You can read it e.g. with `fs.readFileSync('processed.txt', 'utf16le')`.

**Comment by denholtz** [comment]
I'll give that a try. Thanks for the help!

**Comment by Hakerh400** [comment]
@denholtz 

Here is your log properly formatted, if it helps:

<details>
<summary>Click to expand</summary>

```
Statistical profiling result from isolate-00000200908C4840-v8.log, (39 ticks, 1 unaccounted, 0 excluded).

 [Shared libraries]:
   ticks  total  nonlib   name
     27   69.2%          C:\Program Files
odejs
ode.exe
     11   28.2%          C:\windows\system32
tdll.dll

 [JavaScript]:
   ticks  total  nonlib   name

 [C++]:
   ticks  total  nonlib   name

 [Summary]:
   ticks  total  nonlib   name
      0    0.0%    0.0%  JavaScript
      0    0.0%    0.0%  C++
      1    2.6%  100.0%  GC
     38   97.4%          Shared libraries
      1    2.6%          Unaccounted

 [C++ entry points]:
   ticks    cpp   total   name

 [Bottom up (heavy) profile]:
  Note: percentage shows a share of a particular caller in the total
  amount of its parent calls.
  Callers occupying less than 1.0% are not shown.

   ticks parent  name
     27   69.2%  C:\Program Files
odejs
ode.exe
     24   88.9%    C:\Program Files
odejs
ode.exe
      7   29.2%      LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      7  100.0%        LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      2   28.6%          Script: ~<anonymous> assert.js:1:11
      2  100.0%            LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1   14.3%          Script: ~<anonymous> util.js:1:11
      1  100.0%            LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1   14.3%          Script: ~<anonymous> net.js:1:11
      1  100.0%            LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1   14.3%          Script: ~<anonymous> internal/fs/streams.js:1:11
      1  100.0%            LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1   14.3%          LazyCompile: ~startup internal/bootstrap/node.js:30:19
      1  100.0%            Script: ~bootstrapNodeJSCore internal/bootstrap/node.js:15:30
      1   14.3%          LazyCompile: ~setupInspector internal/bootstrap/node.js:442:26
      1  100.0%            LazyCompile: ~setupGlobalConsole internal/bootstrap/node.js:404:30
      2    8.3%      LazyCompile: ~startup internal/bootstrap/node.js:30:19
      2  100.0%        Script: ~bootstrapNodeJSCore internal/bootstrap/node.js:15:30
      2    8.3%      LazyCompile: ~binding internal/bootstrap/loaders.js:77:39
      1   50.0%        Script: ~<anonymous> internal/util/inspect.js:1:11
      1  100.0%          LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%            LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      1   50.0%        Script: ~<anonymous> internal/errors.js:1:11
      1  100.0%          LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%            LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      1    4.2%      Script: ~bootstrapNodeJSCore internal/bootstrap/node.js:15:30
      1    4.2%      Script: ~bootstrapInternalLoaders internal/bootstrap/loaders.js:42:35
      1    4.2%      Script: ~<anonymous> internal/url.js:1:11
      1  100.0%        LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%          LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      1  100.0%            Script: ~<anonymous> internal/fs/streams.js:1:11
      1    4.2%      Script: ~<anonymous> internal/buffer.js:1:11
      1  100.0%        LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%          LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      1  100.0%            Script: ~<anonymous> buffer.js:1:11
      1    4.2%      LazyCompile: ~stat internal/modules/cjs/loader.js:84:14
      1  100.0%        LazyCompile: ~Module._findPath internal/modules/cjs/loader.js:221:28
      1  100.0%          LazyCompile: ~Module._resolveFilename internal/modules/cjs/loader.js:548:35
      1  100.0%            LazyCompile: ~Module._load internal/modules/cjs/loader.js:503:24
      1    4.2%      LazyCompile: ~shift internal/fixed_queue.js:104:8
      1  100.0%        LazyCompile: ~_tickCallback internal/process/next_tick.js:41:25
      1  100.0%          LazyCompile: ~Module.runMain internal/modules/cjs/loader.js:741:26
      1  100.0%            LazyCompile: ~startup internal/bootstrap/node.js:30:19
      1    4.2%      LazyCompile: ~once events.js:289:44
      1  100.0%        LazyCompile: ~write console.js:146:15
      1  100.0%          LazyCompile: ~log console.js:199:37
      1  100.0%            C:\Program Files
odejs
ode.exe
      1    4.2%      LazyCompile: ~debuglog util.js:181:18
      1  100.0%        Script: ~<anonymous> _stream_readable.js:1:11
      1  100.0%          LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%            LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      1    4.2%      LazyCompile: ~createWritableStdioStream internal/process/stdio.js:158:35
      1  100.0%        LazyCompile: ~getStdout internal/process/stdio.js:18:21
      1  100.0%          Script: ~<anonymous> console.js:1:11
      1  100.0%            LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1    4.2%      LazyCompile: ~WritableState _stream_writable.js:52:23
      1  100.0%        LazyCompile: ~Writable _stream_writable.js:198:18
      1  100.0%          LazyCompile: ~Duplex _stream_duplex.js:47:16
      1  100.0%            LazyCompile: ~Socket net.js:224:16
      1    4.2%      LazyCompile: ~Module._initPaths internal/modules/cjs/loader.js:767:29
      1  100.0%        Script: ~<anonymous> internal/modules/cjs/loader.js:1:11
      1  100.0%          LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%            LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      1    4.2%      LazyCompile: ~Module._extensions..js internal/modules/cjs/loader.js:710:37
      1  100.0%        LazyCompile: ~Module.load internal/modules/cjs/loader.js:591:33
      1  100.0%          LazyCompile: ~tryModuleLoad internal/modules/cjs/loader.js:536:23
      1  100.0%            LazyCompile: ~Module._load internal/modules/cjs/loader.js:503:24
      1    4.2%      LazyCompile: ~Module._compile internal/modules/cjs/loader.js:657:37
      1  100.0%        LazyCompile: ~Module._extensions..js internal/modules/cjs/loader.js:710:37
      1  100.0%          LazyCompile: ~Module.load internal/modules/cjs/loader.js:591:33
      1  100.0%            LazyCompile: ~tryModuleLoad internal/modules/cjs/loader.js:536:23

     11   28.2%  C:\windows\system32
tdll.dll
      6   54.5%    C:\Program Files
odejs
ode.exe
      1   16.7%      Script: ~<anonymous> stream.js:1:11
      1  100.0%        LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%          LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      1  100.0%            Script: ~<anonymous> internal/fs/streams.js:1:11
      1   16.7%      Script: ~<anonymous> internal/util/inspect.js:1:11
      1  100.0%        LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%          LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34
      1  100.0%            Script: ~<anonymous> util.js:1:11
      1   16.7%      Script: ~<anonymous> :5:10
      1  100.0%        Script: ~<anonymous> :1:1
      1   16.7%      LazyCompile: ~setupProcessObject internal/bootstrap/node.js:331:30
      1  100.0%        LazyCompile: ~startup internal/bootstrap/node.js:30:19
      1  100.0%          Script: ~bootstrapNodeJSCore internal/bootstrap/node.js:15:30
      1   16.7%      LazyCompile: ~setupProcessICUVersions internal/bootstrap/node.js:536:35
      1  100.0%        LazyCompile: ~startup internal/bootstrap/node.js:30:19
      1  100.0%          Script: ~bootstrapNodeJSCore internal/bootstrap/node.js:15:30
      1   16.7%      LazyCompile: ~inherits util.js:274:18
      1  100.0%        Script: ~<anonymous> internal/streams/legacy.js:1:11
      1  100.0%          LazyCompile: ~NativeModule.compile internal/bootstrap/loaders.js:303:44
      1  100.0%            LazyCompile: ~NativeModule.require internal/bootstrap/loaders.js:150:34

      1    2.6%  UNKNOWN
```
</details>

**Comment by davisjam** [comment]
@denholtz If your issue has been resolved, can you close it? Or do you have more questions?

**Comment by denholtz** [comment]
Thanks for the help!
