### ISSUE TITLE
Shutdown SSL but keeping socket alive

### ISSUE THREAD

**Issue by Neilpang** [nodejs/help#1955]
I created a tls socket from a live socket instance.

Is there a way to gracefully shutdown tls,  but keep the socket alive?   I need to send more plain data over the raw socket.

**Comment by gireeshpunathil** [comment]
@Neilpang - is this still an issue?

**Comment by Neilpang** [comment]
@gireeshpunathil   Yes.

**Comment by preveen-stack** [comment]
I guess downgrading from secure to raw is not allowed as per standard. please refer https://datatracker.ietf.org/doc/html/rfc8446
