### ISSUE TITLE
Error: Cannot Find Module

### ISSUE THREAD

**Issue by Tf2Trader** [nodejs/help#1956]
C:\Users\danie>node bot.js
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'C:\Users\danie\bot.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

I have retried, Checked other posts and searched on google of this problem but no one but me has had this problem when it should be working. Its even the right directory.

**Comment by shakoismyname** [comment]
hey i have same issue pls help me guys ქართველი თუ ხარ მიშველე რამე :დდ exactly same think look at screenshots

**Comment by fel-hita** [comment]
> Nvm i just found out

At least share the solution, it may help future visitors.

**Comment by leslaliun** [comment]
motherfucker share the fucking solution

**Comment by techieeliot** [comment]
@Tf2Trader what did you do to figure this out?

**Comment by ItzWillie** [comment]
lmao

**Comment by milkgaming** [comment]
omg. he didnt tell us.

**Comment by SakshiNyati** [comment]
So I had the same problem though the thing was I entered 'npm i mangodb' instead of 'npm i mongodb'. lol.  Make sure you have not made any typo in the terminal while running npm install command.
