### ISSUE TITLE
Request body received on server is different from what I sent

### ISSUE THREAD

**Issue by rnons** [nodejs/help#1957]
* **Version**: v10.15.3 & v12.3.1
* **Platform**: Linux ubuntu 5.0.0-15-generic 16-Ubuntu SMP Mon May 6 17:41:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: http, stream

I have a reproducible repo at https://github.com/rnons/nodejs-http-issue
I made a simple http server that write the request body to a file, then compare it with what I sent to the server, the diff is like
```
1083c1083
<         ["¥state¤None¦screen¥Large¤name¨lg:-m-10", "¥value§-2.5rem¨property¦margin¨disabledÂ"],
---
>         ["¥state¤None¦screen¥Large¤name¨lg:-m-10", "¥value§-2.5rem¨property��margin¨disabledÂ"],
2130c2130
<         ["¥state¤None¦screen¥Large¤name¯lg:inline-block", "¥value¬inline-block¨property§display¨disabledÂ"],
---
>         ["¥state¤None¦screen¥Large¤name��lg:inline-block", "¥value¬inline-block¨property§display¨disabledÂ"],
6869c6869
<         ["¥state¤None¦screen¥Large¤name´xl:align-text-bottom", "¥value«text-bottom¨property®vertical-align¨disabledÂ"],
---
>         ["¥state¤None¦screen¥Large¤name´xl:align-text-bottom", "��value«text-bottom¨property®vertical-align¨disabledÂ"],
```

**Comment by addaleax** [comment]
I’m confused – you posted the same thing in #1945, and found a solution, so … is there anything you think we should do, or that you need help with?

**Comment by rnons** [comment]
I didn't open this issue, it was transferred here.
> Trott transferred this issue from nodejs/node 6 hours ago

The has been resolved, thank you.
