### ISSUE TITLE
Virus alert when installing node-v12.4.0-x64.msi

### ISSUE THREAD

**Issue by dbkaynor** [nodejs/help#1958]
When installing node-v12.4.0-x64.msi a virus alert was triggered. This happened after the node.js successfully installed and I was given an option to install tools to be used when installing node.js modules (Python, Microsoft, and Chocolaty. 

System: Microsoft Windows [Version 10.0.17134.191]
Node.js: node-v12.4.0-x64.msi
F-Secure Client:  DeepGuard  warning
Definitions version:
    Viruses: 2019-06-06_01
    Spyware: 2019-06-06_01
Scanning Engines:
   F-Secure Aquarius: 18.00.519, 2019-06-06
   F-Secure Hydra: 5.22.46, 2019-06-05
   F-Secure Online: 16.26.39, 0-00-00
   F-Secure Gemini: 3.02.414, 2019-06-05

**Comment by gireeshpunathil** [comment]
I don't have a windows system to attempt a reproduce, so pinging @nodejs/releasers to see if they know of it - probably it has to do digital signing?

**Comment by ThomasMatthis** [comment]
Hi! I experienced almost the same issue yesterday with node-v12.18.3-x64.msi and McAffee, during installation of the "additional tools" (Chocolatey etc.):
System: Microsoft Windows Home Version 1909
Node.js: node-v12.18.3-x64.msi (downloaded 07/28/20)
McAffee LifeSave V16.0 R26
McAffee VirusScan Build 23.2.1999, last updated 07/29/20
MacAffee wasn't reporting any downloaded virus but malicious actitivty during installation 
https://service.mcafee.com/webcenter/portal/oracle/webcenter/page/scopedMD/s55728c97_466d_4ddb_952d_05484ea932c6/Page29.jspx?wc.contextURL=%2Fspaces%2Fcp&articleId=TS102828&lang=de&lcid=1031&langid=52&culture=de-DE&rcode=WSS16026&version=18.6&wuiv=12.0&build=18.6.164&affid=1357&resellerid=1&ContentIterationID=7.5.109&OCVersion=3.0&OCEnable=1&CommonBuild=1&GCB=1&pef=1&jeulaversion=eula_v2019h1&AWVersion=4.0&EulaDt=20191214&domain=de.mcafee.com&ClientOSV=17&ocsku=1357-35-48627&hres=1920&vres=1080&coreui_enabled=1&coreui_version=1&EulaState=1&bsn=4CE9351FQQ&EulaTrackingStatus=1&mcafeesku=1357-35-48627&defaultSKUused=0&partnersku=1357-35-48627&stpcheck=1&LaunchPoint=3&IPRDt=20200112&IPRcomp=1&IPRdone=1&Activated=1&pkgs=431_1357_de-de_0_0F9AE594-B1D2-420D-B1B9-7F37BCE7CF88_20210113_167_1&email=ef57b25b5cd876f27705adfcd2ad3bb8001d18050f5719563b37543a0414743d24421e1502005551577d3c41&hardware_id=fb7fcc77a77c419ce92787b55a3b68c05940400f03065113356b137c5552077f320a43440d500a0410633b472f530001&windows_id=617bf303bd10162c13776efe7e69170f30084d2e270307126a1e0909275e0161635a424c4123740d607e1a127f55240509652e4042551c&pk=046000467a6e2e2ea3673c937557c41d5f354d2d24070d117e1a150e534b007e672b5e365d230b1912156b13082223030f11574b&pkgid=431&os_country=DE&os_culture=de&cui=f98500667d5c4403ae3d39c248cb1bef-1e89a3b341f9&_afrLoop=183170506402418&leftWidth=0%25&showFooter=false&showHeader=false&rightWidth=0%25&centerWidth=100%25#!%40%40%3Faffid%3D1357%26showFooter%3Dfalse%26defaultSKUused%3D0%26IPRcomp%3D1%26cui%3Df98500667d5c4403ae3d39c248cb1bef-1e89a3b341f9%26Activated%3D1%26OCVersion%3D3.0%26articleId%3DTS102828%26hres%3D1920%26EulaTrackingStatus%3D1%26wc.contextURL%3D%252Fspaces%252Fcp%26os_country%3DDE%26partnersku%3D1357-35-48627%26pkgid%3D431%26centerWidth%3D100%2525%26stpcheck%3D1%26leftWidth%3D0%2525%26bsn%3D4CE9351FQQ%26email%3Def57b25b5cd876f27705adfcd2ad3bb8001d18050f5719563b37543a0414743d24421e1502005551577d3c41%26wuiv%3D12.0%26ocsku%3D1357-35-48627%26culture%3Dde-DE%26pk%3D046000467a6e2e2ea3673c937557c41d5f354d2d24070d117e1a150e534b007e672b5e365d230b1912156b13082223030f11574b%26langid%3D52%26OCEnable%3D1%26CommonBuild%3D1%26hardware_id%3Dfb7fcc77a77c419ce92787b55a3b68c05940400f03065113356b137c5552077f320a43440d500a0410633b472f530001%26rcode%3DWSS16026%26build%3D18.6.164%26pkgs%3D431_1357_de-de_0_0F9AE594-B1D2-420D-B1B9-7F37BCE7CF88_20210113_167_1%26lang%3Dde%26resellerid%3D1%26version%3D18.6%26vres%3D1080%26domain%3Dde.mcafee.com%26jeulaversion%3Deula_v2019h1%26AWVersion%3D4.0%26IPRdone%3D1%26ContentIterationID%3D7.5.109%26os_culture%3Dde%26_afrLoop%3D183170506402418%26windows_id%3D617bf303bd10162c13776efe7e69170f30084d2e270307126a1e0909275e0161635a424c4123740d607e1a127f55240509652e4042551c%26LaunchPoint%3D3%26ClientOSV%3D17%26lcid%3D1031%26coreui_version%3D1%26IPRDt%3D20200112%26showHeader%3Dfalse%26EulaDt%3D20191214%26pef%3D1%26rightWidth%3D0%2525%26GCB%3D1%26coreui_enabled%3D1%26EulaState%3D1%26mcafeesku%3D1357-35-48627%26_adf.ctrl-state%3Dxn2g7qxer_67

**Comment by gireeshpunathil** [comment]
@dbkaynor - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.

**Comment by aiyaash-aman** [comment]
Hi! I experienced almost the same issue yesterday with node-v12.18.3-x64.msi and McAffee, during installation of the "additional tools" (Chocolatey etc.):
System: Microsoft Windows Home
Node.js: node-v16.15.0-x64.msi (downloaded 05/21/22)
McAffee LifeSave V16.0 R26
McAffee VirusScan  last updated 05/21/22
MacAffee wasn't reporting any downloaded virus but malicious actitivty during installation

**Comment by mateusmorgado** [comment]
I had the same issue last month. I think that I had a Trojan horse while installing the other plug-ins after node

**Comment by EvanHsieh0415** [comment]
Same issue now

**Comment by Kharfman** [comment]
Same issue now

**Comment by IglKa** [comment]
If any of you, guys, after this problem appears experienced the problem with installing/deleting other programs, you should type this in your cmd, while running as administrator:

DISM.exe /Online /Cleanup-image /Restorehealth
sfc /scannow

Those commands will scan and detect damaged files on your computer and restore them

**Comment by kevin202108** [comment]
I have the same issue, but I use Avira. It said:
threaten name : LNK/Dldr.Agent.VPHK

**Comment by farhadmn** [comment]
Some problem with Avira, I closed Avira but the powershell window closed immediately after it was run.

**Comment by AdhiMvm** [comment]
welp fellas, I can say that I have had the exact same issue today with the exact same file download. I looked it up and people have suggested submitting the issue as a false negative, but people have noted it down as a false negative in the past and yet mcaffe still flags it as a threat, so I don't know wether to turn off mcaffe and install chocolatey anyway or to wait till mcaffe can resole the issue.
