### ISSUE TITLE
Issue with 'add() requires Middleware'

### ISSUE THREAD

**Issue by ChrisX212** [nodejs/help#196]
Once again I ran into trouble in following Tutorial Point's node js tutorial (by the way, last solution works wonders, thank you! I didn't get to say thanks before it was locked). This time, it's on the file upload section as seen here.

http://www.tutorialspoint.com/nodejs/nodejs_express_framework.htm

Whenever I tried to call in Server.js, it will give out Type Error: 

`app.use() requires middleware functions`

I managed to have a workaround with using this instead of app.use():

`var upload = multer({ dest: './uploads'}).single("file");`

However this would result this kind of error:

`TypeError: Cannot read property 'file' of undefined`

I wonder how do I get past that? Really new on this node js business. Thanks for any help!

**Comment by lordKnighton** [comment]
You're welcome for the last go round. Let me see you're current code.
