### ISSUE TITLE
Accessing the original (platform dependent) error code?

### ISSUE THREAD

**Issue by TanninOne** [nodejs/help#1961]
* **Node.js Version**: 10.11.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: fs

Our application is very heavy on filesystem operations, having to read and write on user-configured file systems.
The result is of course that we get a lot of errors (regarding file permissions, files being locked, disks being damaged or full, network drives being disconnected and so on) that we want to report to users in as useful a way as we can.

Now on windows at least node.js (or libuv) seems to be throwing away a ton of useful information. Windows knows almost 16000 error codes, they get translated to around a dozen in node.js and - to add insult to injury - the error _message_ is based on the "simplified" error code.
The end result is that just about everything that goes wrong on a network drive or virtual directories (stuff like onedrive or dropbox) for example just produces "UNKNOWN" as an error message and so all we can tell the user is "something happened, it wasn't good".
We have no way of knowing if the problem is temporary and may be solved by retrying, whether it's safe to ignore and we can't provide any guidance to the user.

So I was wondering if there is any way to access the original error code so that applications, aware of the platform, can provide better error messages.

**Comment by gireeshpunathil** [comment]
let me re-phrase the issue for my own understanding. There are 2 issues:
 - fs APIs `generalize` 16K error codes.
 - A specific API throws `UNKNOWN`

Please let me know if this is the gist of this problem report.

**Comment by TanninOne** [comment]
* generalize - yes, you could phrase it like that. But also, it's not just generalizing the error codes but also base the error message on the generalized code instead of the original one
* no, I wouldn't say "a specific api". We've seen a lot of common fs calls (read, write, unlink, ..) produce UNKNOWN errors.

**Comment by gireeshpunathil** [comment]
@TanninOne - ok, thanks for the clarification.

for the first one: given that node runtime (or any runtime for that matter) is a sophisticated abstraction layer on top of the system to improve programming experience and developer productivity, generalizing / grouping error codes / messages make sense to me. If we were to percolate 16K discrete error types as is to the user program, then there is minimal or zero abstraction.

for the second one: I deem it as a bug. Can you please provide / come up with a minimal test case that throws an `UNKNOWN` error?

**Comment by TanninOne** [comment]
Well, yes, error messages need to be "classified" so that they can be handled in a sensible way, but that doesn't mean that information needs to be lost, the original system error code could still be there as an additional parameter of the error object, if devs don't use it, nothing changes for them.
I don't see a reason for the textual error message to be derived from the generalized error code instead of the native one either, what do we get from that? How does that make the runtime more "abstract"? It's text.
Sure, having the software deal with 16k error types would be problematic but displaying one of 16k error texts to give users a clue what's going on isn't.

The problem with providing a test case is that I'd have to know what causes the error to produce a test case. That's my entire point: With the lack of information in these error messages I don't.
Just to clarify: We have an application that sees ~100k unique users per day and lets users report any "not properly handled" errors as a bug to us. From time to time we get reports with an UNKNOWN error code. This isn't happening a lot but it can cause serious problems when it does. And the users don't usually have the knowledge to track the problem down.

I know from a native node module that doesn't lose error information that users are sometimes seeing ERROR_USER_MAPPED_FILE - probably caused by virus scanners locking files exclusively. That code gets mapped to UNKNOWN in nodejs/libuv. It should probably be mapped to EBUSY so that we (or gracious-fs or whatever) knows to retry the fs operation.

But that's just one case of many, my point is: had the problem been reported as "UNKNOWN - The requested operation cannot be performed on a file with a user-mapped section open." we would have immediately known, and could have reported, that this error should be an EBUSY.
But instead we get "UNKNOWN - something happened, it wasn't good" and search for the cause for months, wasting dozens of hours of development time trying to figure out what's happening.

**Comment by gireeshpunathil** [comment]
> I don't see a reason for the textual error message to be derived from the generalized error code instead of the native one either, what do we get from that? How does that make the runtime more "abstract"? It's text.

I get that point, and agree - the error messages becomes more consumable if those carry the original code and / or the message from the system.

But looks like this conversation is not leading us to any actionables without a test case, unless someone want to come up with a PR that appends system error to every `fs` errors. Copying @joyeecheung who was championing the error messages initiative to get her opinion.

**Comment by joyeecheung** [comment]
If I understand correctly the requested feature is a way to get to the original error code? That is possible through `err.errno` - but not for every error we get from libuv at the moment:

https://github.com/nodejs/node/blob/0059b877e35eb933b2e544d1e33bccb16e05545b/lib/internal/errors.js#L458-L459

It's possible to correct this, though I believe that would be semver-major at this point.

To translate the numeric error code into Windows-specific messages I believe you still need to call something like [`FormatMessage()`](https://docs.microsoft.com/en-us/windows/desktop/api/WinBase/nf-winbase-formatmessage). If calling into native is a problem for you (since it may require a C++ addon), off the top my head it would be reasonable to open a feature request in the main repo to add an API to util similar to [`util.getSystemErrorName()`](https://nodejs.org/docs/latest/api/util.html#util_util_getsystemerrorname_err) but returns something more informative like a `{name, message}` structure instead.

**Comment by joyeecheung** [comment]
Although, I can see that having a way to programmatically get more useful information out of these errors is still not that ergonomic - I have no idea why there was a decision to normalize the messages on Windows, it may simplify the whole model for certain errors, but I can see it could be just more confusing for many others. It may be possible to add some global option to opt out of this kind of translation, but that should be discussed in the main repo and get the opinions from people who have more context about this behavior.

**Comment by joyeecheung** [comment]
hmm, I just noticed that even `err.errno` are always normalized by libuv. From Node.js there isn't even a way to get to the original error numbers. I guess you'll need to file an issue in https://github.com/libuv/libuv for an option to opt out of this behavior before we can do anything in Node.js.

**Comment by TanninOne** [comment]
Thank you for the replies!
Yes, the errno parameter looked like it could be useful but in practice all reports contain something unusable like -4094.
