### ISSUE TITLE
Discard chunk in NodeJS Transform stream and read the next one

### ISSUE THREAD

**Issue by satishrao84** [nodejs/help#1963]
* **Node.js Version  **:10.8.0
* **OS  **: MacOS
* **Scope (install, code, runtime, meta, other?) : **:Code
* **Module (and version) (if relevant)  **:streams

How do I discard a chunk in a NodeJS transform stream and read the next one from the previous stream?

```
stream.on('data',function(data){}).pipe(rulesCheck).pipe(step1).pipe(step2).pipe(step3).pipe(insertDataIntoDB);
```

I would like to discard the chunk if it doesn't pass certain criteria in the ruleCheck stream.

**Comment by Hakerh400** [comment]
Something like this?

```js
const stream = require('stream');

const check = new stream.Transform({
  transform(data, encoding, callback){
    // Discard if the string representation of the the chunk is "abc"
    if(data.toString() === 'abc') callback(null, Buffer.alloc(0));
    else callback(null, data);
  },
});

check.pipe(process.stdout);
check.write('123');
check.write('4567');
check.write('abc');
check.write('defg\n');
check.end();
```

**Comment by gireeshpunathil** [comment]
ping @satishrao84

**Comment by satishrao84** [comment]
Hi Gireesh! Sorry for the bad delay in responding! Thanks for your help! Yes, this works.

**Comment by gireeshpunathil** [comment]
closing then, thanks!
