### ISSUE TITLE
Packaging NodeJS

### ISSUE THREAD

**Issue by dr-nyt** [nodejs/help#1965]
* **Node.js Version**:
10.16.0
* **OS**:
Windows 10 64-bit
* **Scope (install, code, runtime, meta, other?)**:
install

Hey,
I use a module called [cfscrape](https://github.com/Anorov/cloudflare-scrape) in my project to bypass Cloudflare. cfscrape uses NodeJS to work. I want my project to be standalone and run without the user needing to install any dependencies, so I was wondering if there is a way to safely package NodeJS along with cfscrape. Thank you for your time.

Kind Regards,
dr_nyt.

**Comment by wide4head** [comment]
@dr-nyt Hopefully this can help you out
https://github.com/zeit/pkg

**Comment by tniessen** [comment]
For Windows 10, download the "Windows Binary (.zip)" distribution package from https://nodejs.org/en/download/ and just copy the binary `node.exe` into your application directory. If you distribute your application, make sure to meet the LICENSE requirements.

**Comment by gireeshpunathil** [comment]
ping @dr-nyt

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if this is still outstanding.
