### ISSUE TITLE
Help understanding context inside vm

### ISSUE THREAD

**Issue by einicher** [nodejs/help#1967]
I have a file `view.js`:
```
View = class {
    constructor(file, callback) {
        if (IS_SERVER) {
            console.log('ON SERVER');
        }
    }
}
```

I need to run this inside a vm, so I add it to context:

```
const vm = require('vm');
GLOBALS: {
	CLIENT_DIR: 'some/path'
};
require('view'); // Since View is global it is available now without ugly module.exports
var context = {
	View: View
	GLOBALS: GLOBALS
};
vm.runInContext(`
	IS_SERVER = true;
	new View(GLOBALS.CLIENT_DIR + 'index.html', {
		
	}, view => {
		console.log(view);
	});
`, vm.createContext(context));
```

Now I get `ReferenceError: IS_SERVER ist not defined`.

How do I define globals inside my sandbox that are seen by the other globals added outside context? Scopes in JavaScript generally confuse me. If View only sees variables from the scope where it is defined, the whole concept of oop like I expect it to work is total trash since I would ALWAYS need an object to bee in the scope of where it is instanciated, its completely useless to access the scope from where it is defined since its just a template.

**Comment by Hakerh400** [comment]
That can be solved in various ways. `View` sees only variables in the scope where it is defined, including the global scope (global object). You need to provide it the reference to the `global` object of the vm context.

### Solution 1

In the main script, put line `View.vmGlobal = this` just above `IS_SERVER = true`
In `view.js` replace `IS_SERVER` with `View.vmGlobal.IS_SERVER`

<details>
<summary>Full code (click to expand)</summary>

**main.js**

```js
const vm = require('vm');
GLOBALS = {
  CLIENT_DIR: 'some/path'
};
require('./view');
var context = {
  View: View,
  GLOBALS: GLOBALS
};
vm.runInContext(`
  View.vmGlobal = this;

  IS_SERVER = true;
  new View(GLOBALS.CLIENT_DIR + 'index.html', {
    
  }, view => {
    console.log(view);
  });
`, vm.createContext(context));
```

**view.js**

```js
View = class {
  constructor(file, callback) {
    if (View.vmGlobal.IS_SERVER) {
      console.log('ON SERVER');
    }
  }
}
```

</details>

### Solution 2

In the main script reinterpret the `View` class using the function constructor and provide the reference to the global console to the vm context. Leave the `view.js` file as is.

<details>
<summary>Full code (click to expand)</summary>

**main.js**

```js
const vm = require('vm');
GLOBALS = {
  CLIENT_DIR: 'some/path'
};
require('./view');
var context = {
  View: View,
  GLOBALS: GLOBALS,
  console,
};

vm.runInContext(`
  View = new Function(\`return \${View}\`)();

  IS_SERVER = true;
  new View(GLOBALS.CLIENT_DIR + 'index.html', {
    
  }, view => {
    console.log(view);
  });
`, vm.createContext(context));
```

**view.js**

```js
View = class {
  constructor(file, callback) {
    if (IS_SERVER) {
      console.log('ON SERVER');
    }
  }
}
```

</details>

**Comment by gireeshpunathil** [comment]
@einicher - were you able to apply either of the solutions proposed?

**Comment by einicher** [comment]
I went with solution 2, but I am still in heavy development. To early to say if that solution will do it. For now it does.

**Comment by gireeshpunathil** [comment]
thanks for the quick revert. so for now let us keep the issue open. pls update when you have more info to share!

**Comment by einicher** [comment]
I would need now the same thing for objects, like `observer = new Object(\`return \${observer}\`);` since i collect those observer calls outside the vm, but need them inside it.

**Comment by einicher** [comment]
I ended up recreating objects inside the vm this way (Object.assign wasnt enough):
```
		recreateObjectInThisScope = function(source, target) {
			for (i in source) {
				l('tof', i, typeof source[i])
				if (typeof source[i] == 'function') {
					target[i] = new Function(\`return \${source[i]}\`)();
				} else if(Array.isArray(source[i])) {
					target[i] = recreateObjectInThisScope(source[i], []);
				} else if(typeof source[i] == 'object') {
					target[i] = recreateObjectInThisScope(source[i], {});
				} else {
					target[i] = source[i];
				}
			}
			return target;
		}
```

**Comment by gireeshpunathil** [comment]
is there anything left here to discuss? or are we good to close?

**Comment by einicher** [comment]
Big problem are ES6 classes now.
