### ISSUE TITLE
cluster workers are block after running some time 

### ISSUE THREAD

**Issue by miser** [nodejs/help#1969]
* **Version**: 9.11.1
* **Platform**:
* **Subsystem**:

I have a web app with Koa, I create many workers process through child_process.fork.

It can't response HTTP request after runs some time. All request are blocked.

Example, I have two server nodes. A is normal, but B maybe block after some time.  Seem to have anything with the program.

Who does meet the same problem?

**Comment by addaleax** [comment]
> I don't know where the issue is and repetition, I don't extract what code to generate a simple case from the current project.

If you cannot provide a test case, that’s going to make this pretty difficult. Can you provide any other information?
