### ISSUE TITLE
Discord bot problems. Help!

### ISSUE THREAD

**Issue by Maevo** [nodejs/help#1971]
Hey there! I have some problems with creating Discord Bot.
When I trying to use my first command, I get error: UnhandledPromiseRejectionWarning: ReferenceError: MessageEvent is not defined.

Here's my code:

--Main file

const Discord = require('discord.js');
const bot = new Discord.Client();
bot.commands = new Discord.Collection();
const fs = require("fs");
let config = require("./botconfig.json");
let token = config.token;
let prefix = config.prefix;

fs.readdir('./cmds/',(err,files)=>{
  if(err) console.log(err);
  let jsfiles = files.filter(f => f.split(".").pop() === "js");
  if(jsfiles.length <=0) console.log("Команды отсутсвуют!");
  console.log(`Загружено ${jsfiles.length} комманд.`);
  jsfiles.forEach((f, i) =>{
    let props = require(`./cmds/${f}`);
    console.log(`${i+1}.${f} Загружен!`);
    bot.commands.set(props.help.name,props);
  })

});

bot.on('ready', () => {
  console.log(`Starting bot ${bot.user.username}!`);
  bot.generateInvite(["ADMINISTRATOR"]).then(link =>{
    console.log(link);
  })
});

bot.on('message', async message => {
  if (message.author.bot) return;
  if(MessageEvent.channel.type == "dm") return;
  let user = message.autor.username;
  let userid = message.author.id;
  let messageArray = message.content.split(" ");
  let command = messageArray[0].toLowerCase();
  let args = messageArray.slice(1);
  if(!message.content.startsWith(prefix)) return;
  let cmd = bot.commands.get(command.slice(prefix.length));
  if(cmd) cmd.run(bot,message,args);
});

bot.login(token);

--Command file

const Discord = module.require("discord.js");
const fs = require("fs");
module.exports.run = async (bot,message,args) => {
    message.channel.send('pong!');
};
module.exports.help = {
    name: "ping"
};

**Comment by wide4head** [comment]
@Maevo probably caused by this line 
`if(MessageEvent.channel.type == "dm") return;`

**Comment by gireeshpunathil** [comment]
ping @Maevo

**Comment by gireeshpunathil** [comment]
inactive; closing. pls reopen if still outstanding
