### ISSUE TITLE
Unable to connect NodeJS with MSSQL

### ISSUE THREAD

**Issue by yeehengoh** [nodejs/help#1972]
Node.js Version: 12.3.1
OS: Windows 
Scope: Code
Module (and version): studentWebsite

I am facing difficulties of connecting my web apps to my MSSQL database.
After compiling program in Visual Studio 2017, once starting my program, it comes out with this error.

"Error while connecting to database :- ConnectionError: Login failed for user 'mylocal'."

The Google chrome web browser appears to have the following error.
{"code":"ELOGIN","originalError":{"message":"Login failed for user 'mylocal'.","code":"ELOGIN"},"name":"ConnectionError"}
For your information, I used NodeJS version 12.3.1, Express JS with version 14.7.1, and MSSQL with version 5.1.0.

I've located my source code inside my public GITHUB as following address.
https://github.com/yeehengoh/studentNodes 

In my db.js, my connection string is written as below.

const db =
{
    user: "mylocal",
    password: "my123",
    server: "localhost\\LocalDBDemo",
    database: "studentData",
    port: 1433
};

module.exports = db;

Not so sure is there anything wrong with my setting over here, and i've also attached the snapshot for database's SQL server authentication.  

![SQL_Server](https://user-images.githubusercontent.com/50520352/59243120-f94ed700-8c40-11e9-8ac0-8db944db1b9d.jpg)

Please help on that. Thanks...

**Comment by gireeshpunathil** [comment]
I am not an MSSQL expert, but the abstraction for the server does not look intuitive - is it the IP address or the well known name, or the name of the DB server instance, or a combination of all these - https://www.npmjs.com/package/mssql#general-same-for-all-drivers is not very specific on this. 

Having said that, in your image the server name is shown as `(LocalDb)\LocalDBDemo` while your string is `localhost\LocalDBDemo` - could this be a reason?

**Comment by gireeshpunathil** [comment]
it would also be great if the GUI provides a `copy` button that composes a connection string from the input that we provide.

**Comment by yeehengoh** [comment]
Hi Gireesh,

Maybe i can try to change my connection string to format as below, see
whether it works well or not...
 mssql://username:password@localhost:1433/database?encrypt=true

Regards,
YeeHeng Oh

**Comment by gireeshpunathil** [comment]
@yeehengoh - were you successful with the new connection string?

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by yeehengoh** [comment]
Hello there,

I just signed the petition "United Nations: Call for the resignation of
Tedros Adhanom Ghebreyesus, WHO Director General" and wanted to see if you
could help by adding your name.

Our goal is to reach 1,500,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/sYwMWdTDMb

Thanks!
Mandy
