### ISSUE TITLE
Net module can not make a connection to SMTP, but windows telnet can do.

### ISSUE THREAD

**Issue by wtflove** [nodejs/help#1973]
I am trying to use node's net module to make connection to my company's SMTP server for sending emails. 

However when I tried to use Windows Telnet to connect, it succeed.

My node script:
```javascript
'use strict'
const net = require('net')

const conn = net.connect(25, 'xxx.xxx.xxx.xxx')

conn.on('connect', function() {
    console.log('connected');
})

conn.on('close', function() {
    console.log('close');
})


setTimeout(function() {
	conn.close()
}, 5000)
```

The error is:

**Error: connect EACCES xxx.xxx.xxx.xxx:25
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)**

Telnet terminal information shows when connected:

**220 xxx.xxx.xxx.xxx ESMTP ready**

**Comment by gireeshpunathil** [comment]
ping @wtflove

**Comment by gireeshpunathil** [comment]
inactive; closing. pls reopen if still outstanding
