### ISSUE TITLE
node v12.4 can not use buf.readBigUInt64LE

### ISSUE THREAD

**Issue by BigEgret** [nodejs/help#1975]
![W%5EQ9684GD9R8JHHCJS6ND](https://user-
![MO{Y8YAU_``5%6}ZCOSLC{1](https://user-images.githubusercontent.com/35915085/59259650-c7536a00-8c6c-11e9-87e1-5ec066f61249.png)
images.githubusercontent.com/35915085/59259617-bc98d500-8c6c-11e9-8bd4-e321ac446b11.png)

Version: v12.4
Platform: Windows 64

**Comment by gireeshpunathil** [comment]
ping @BigEgret

**Comment by gireeshpunathil** [comment]
inactive; closing. pls reopen if still outstanding
