### ISSUE TITLE
server not responding  after some requests 

### ISSUE THREAD

**Issue by nithinkumarsn** [nodejs/help#1976]
const express = require('express');
const mysql = require('mysql');
const bodyParser=require('body-parser');
const app = express();
const cors = require('cors');
const http=require('http')

http.globalAgent.maxSockets = 100;

app.use(bodyParser.urlencoded({extended:true}));
app.use(bodyParser.json());
app.use(cors());

// Creating a GET route that returns data from the 'users' table.
app.get('/users', function (req, res) {
    // Connecting to the database.
    
    connection.getConnection(function (err, connection) {

        // Executing the MySQL query (select all data from the 'users' table).
        connection.query('SELECT * FROM products', function (error, results, fields) {
            // If some error occurs, we throw an error.
            if (error) throw error;

            // Getting the 'response' from the database and sending it to our route. This is were the data is.
            res.send(results)
            res.end()
            .on("socket", function (socket) {
                socket.emit("agentRemove");
              });
        });
    });
});

**Comment by davisjam** [comment]
@nithinkumarsn 

Welcome to nodejs/help!

Can you provide more detail about the test you are running and the behavior you observe? Are the first requests you submit satisfied? Is the server receiving the new requests but not responding to them?

**Comment by gireeshpunathil** [comment]
ping @nithinkumarsn

**Comment by nithinkumarsn** [comment]
Thank you for your response, i solved the problem by calling
connection.end() func after request response ...

After that i m getting connection.end() depricated warning but now works
fine.

**Comment by gireeshpunathil** [comment]
closing then, cheers!
