### ISSUE TITLE
(node:26504) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

### ISSUE THREAD

**Issue by saydulk** [nodejs/help#1977]
username@TerraDEX-ETH-Node:~/DEX3/dex-back-end$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
username@TerraDEX-ETH-Node:~/DEX3/dex-back-end$ node -v
v8.16.0
username@TerraDEX-ETH-Node:~/DEX3/dex-back-end$ sudo yarn start
yarn run v1.16.0
warning ../../package.json: No license field
$ node app
(node:26504) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/home/username/DEX3/dex-back-end/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/username/DEX3/dex-back-end/app.js:153:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
username@TerraDEX-ETH-Node:~/DEX3/dex-back-end$ uname -a
Linux TerraDEX-ETH-Node 4.4.0-150-generic #176-Ubuntu SMP Wed May 29 18:56:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
![Screenshot from 2019-06-13 01-06-25](https://user-images.githubusercontent.com/1058663/59379164-c8bd8900-8d77-11e9-9d46-d5b9a0bcd2bb.png)

**Comment by addaleax** [comment]
Any chance you are already running the same program?

In any case, running `sudo netstat -natp | grep 9000` should tell you what program is currently running on port 9000.

**Comment by saydulk** [comment]
i was looking for (node:26504) DeprecationWarning to fix. 

9000 port running Back End of BitDex - Decentralized cryptocurrency exchange for ETH and tokens. 

![Screenshot from 2019-06-13 01-32-36](https://user-images.githubusercontent.com/1058663/59380598-4d5dd680-8d7b-11e9-9b44-3cf49ad9fa25.png)

**Comment by addaleax** [comment]
If you want to know where the deprecation warning came from, using `node --trace-warnings ...` might help?

**Comment by saydulk** [comment]
username@TerraDEX-ETH-Node:~/DEX3/dex-back-end$ node --trace-warnings ...
module.js:550
    throw err;
    ^

Error: Cannot find module '/home/username/DEX3/dex-back-end/...'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Is their any commands which will fixed all of this issue?

![Screenshot from 2019-06-13 02-09-31](https://user-images.githubusercontent.com/1058663/59382815-5a30f900-8d80-11e9-8d09-925c1dc86b82.png)

**Comment by addaleax** [comment]
@sayduk You do need to replace `...` with the command that you want to run trace warnings for (the one run by `yarn start`; if you don’t know that command, you can try `sudo env NODE_OPTIONS=--trace-warnings yarn start`.

**Comment by gireeshpunathil** [comment]
ping @saydulk

**Comment by gireeshpunathil** [comment]
inactive; closing. pls reopen if still outstanding

**Comment by saydulk** [comment]
It was fixed, Thanks  :)
