### ISSUE TITLE
Client authentication using certificate store

### ISSUE THREAD

**Issue by nrdobie** [nodejs/help#1978]
* **Node.js Version**: 12.0.0
* **OS**: Windows 7 / macOS 10.14.3
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: Electron 5.0

I'm trying to perform client authentication using a private machine certificate that is stored in the Windows Certificate Store or macOS System Keychain. I'm calling an API that needs to authenticate the machine that is calling it and our old system uses the machine's certificate to authorize the request so I need to do the same. I am using Electron 5 to do this and while I can make the requests while in the Chromium scope, I cannot make the request while in the Node scope which is where I am more concerned with making the requests. All the tutorials I've read show the following example.

```js
var fs = require('fs'); 
var https = require('https'); 

var options = { 
    hostname: 'localhost', 
    port: 4433, 
    path: '/', 
    method: 'GET', 
    key: fs.readFileSync('client1-key.pem'), 
    cert: fs.readFileSync('client1-crt.pem'), 
    ca: fs.readFileSync('ca-crt.pem') }; 

var req = https.request(options, function(res) { 
    res.on('data', function(data) { 
        process.stdout.write(data); 
    }); 
}); 

req.end(); 

req.on('error', function(e) { 
    console.error(e); 
});
```

My issue is that I have no way to access the private key, nor will I be allowed access to the private key. Is there a way to get Node.js to read from the machine's certificate store to respond to client certificate requests?

**Comment by gireeshpunathil** [comment]
ping @nodejs/crypto

**Comment by sam-github** [comment]
> Is there a way to get Node.js to read from the machine's certificate store to respond to client certificate requests?

In brief, no.

Bring this up on the openssl user's mailing list if its of interest to you. If you can find a way to do it with OpenSSL, then we could see what it would take to expose that in Node.js

**Comment by gireeshpunathil** [comment]
ping @nrdobie - is this resolved?
