### ISSUE TITLE
npm problem

### ISSUE THREAD

**Issue by Zeon-4** [nodejs/help#1981]
When i write any command npm in command line
>npm -v
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules
\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external com
mand, operable program or batch file
6.9.0
![image](https://user-images.githubusercontent.com/39654434/59428972-60a68b80-8de7-11e9-8993-996e5cae3043.png)
![image](https://user-images.githubusercontent.com/39654434/59429035-86cc2b80-8de7-11e9-8024-256e519774b8.png)

**Comment by gireeshpunathil** [comment]
can you paste the first line of `C:\Program Files\nodejs\npm` ?

**Comment by gireeshpunathil** [comment]
ping @Zeon-4

**Comment by gireeshpunathil** [comment]
inactive; closing
