### ISSUE TITLE
require module "without" the module

### ISSUE THREAD

**Issue by Firlfire** [nodejs/help#1982]
* **Node.js Version**: 10.15.1
* **npm Version**: 6.4.1
* **OS**: Windows

Hi,

(sorry for this long post)
I hope a solution exists for my problem :
I have to create a script (main.js) which will be compile into a setup using [pkg](https://github.com/zeit/pkg).
This setup have to use some other scripts. I call them plugins/addon/external scripts/... as you like.
Obviously, the main and these external scripts are coded in nodeJS and requires some module. In my example, the external script requires [fs-extra](https://github.com/jprichardson/node-fs-extra)  while the main one is not.

**[How pkg works ](https://github.com/zeit/pkg#Config)**:
To compile a script into an executable, pkg looks for all 'require' calls to include all the modules and dependencies in the executable.
In main.js, the 'require' gets the name of the module to load from a variable, not a literal and static string. Therefore, pkg can not include dependencies (and I do not want these external scripts and their dependencies to be included! So that's fine).

The executable works completely when he and the external scripts are in the project, with the node_modules/ folder.
But when I move them to another location (without "node_modules"), the executable can do its job and find the external scripts, but the external scripts can not load their dependencies and crash

Is it possible to do something like this? I do not want the dependencies of external scripts to be integrated.
If not : the purpose is to have : an executable (developped in nodeJS) that can run js script (like 'file.js'), have you an idea about how can I done this ?
For example, one of the external scripts have to use [systeminformation](https://systeminformation.io/filesystem.html) to get really complete informations about the machine. I don't think that "standard js without any require can done this"...

I hope that I have explained myself in an understandable way
Thanks in advance

**./main.js**
```js
const path = require ('path');

// external script to require
var filePath = path.join(process.cwd(), 'test', 'externalScript');
try {
	var run = require(`${filePath}`); // require the external script
	run(); // launch the script
}
catch(ex) {
	console.log(`!!!!! AN ERROR OCCURED !!!!!`);
	console.log(ex.message);
}
finally {
	console.log('Press any key to exit');
	process.stdin.setRawMode(true);
	process.stdin.resume();
	process.stdin.on('data', process.exit.bind(process, 0));
}
```

**./test/externalScript.js**
```js
const path = require('path');    // works because it is a "standard nodejs module", no need to "npm install path" to use it
const fse = require('fs-extra'); // throw an error error if the executable is not in the same folder as "node_modules/" because it require a "npm install fs-extra"

const filePath = path.join(process.cwd(), 'output', 'output.json');
const options = { spaces: 2 }  // indent
const data = { "prop1": "val1", "prop2": "val2", "prop3": "val3" }

module.exports = function () {
  // create folder structure and file if not exists
	fse.ensureFileSync(filePath);

  // write in the file
  fse.writeJsonSync(filePath, data, options, err => {
    if (err) return console.error(err)
    console.log(`${file} saved!`);
  })
};
```

**Comment by Hakerh400** [comment]
Add file `./package.json`

```json
{
  "bin": "main.js",
  "name": "main",
  "pkg": {
    "scripts": "test/*.js"
  },
  "dependencies": {
    "fs-extra": "^8.0.1"
  }
}

```

Then run `pkg . --targets win`

**Comment by Firlfire** [comment]
Thanks to ypur answer

I already have a ./package.json file that I forgot to show (I will add it in my post tomorrow).
if i add the "pkg" property to it like you shown, does not it add "fs-extra" into the executable?
I don't want to. Is there absolutely no other way ?

**Comment by Hakerh400** [comment]
If you don't want `fs-extra` to be in the executable, simply delete your `node_modules` folder. It will throw warning while compiling `Warning Cannot find module 'fs-extra'`, but it is ok. The executable will require dependencies to be installed by the user.

**Comment by gireeshpunathil** [comment]
ping @Firlfire

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if this is still outstanding.
