### ISSUE TITLE
How does node/npm find modules

### ISSUE THREAD

**Issue by nealef** [nodejs/help#1983]
I built nodejs v10.16.0 and attempted to build a container image with it. When I try and run the container I get the following:
 ```
[neale@docker 10]$ docker run --rm -it clefos/node:10 bash
bash-4.2# id
uid=0(root) gid=0(root) groups=0(root)
bash-4.2# npm
fs.js:114
    throw err;
    ^
 
Error: ENOENT: no such file or directory, open '/usr/lib/utils/unsupported.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:786:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/bin/npm:19:21
    at Object.<anonymous> (/usr/bin/npm:152:3)
bash-4.2# exit
 ```
However, if I add the ```--privileged``` option to the run command it works:
 ```
[neale@docker 10]$ docker run --privileged --rm -it clefos/node:10 bash
bash-4.2# npm
 
Usage: npm <command>
 
where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami
 
npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview
 
Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config
 
npm@6.9.0 /usr/lib/node_modules/npm
```
I am trying to work out why. Note unsupported.js lives in ```/usr/lib/node_modules/npm/lib/utils/unsupported.js``` so I am wondering what type of things influences node/npm search choices.

**Comment by gireeshpunathil** [comment]
@nealef - tricky indeed!
 - can you please run `which npm` within the container, with and without `--privileged` option? do those differ?
 - `[neale@docker 10]$`: is this already a container image, or a bare metal?

**Comment by nealef** [comment]
> @nealef - tricky indeed!
> 
> * can you please run `which npm` within the container, with and without `--privileged` option? do those differ?
* Privileged:
```
# which npm
/usr/bin/npm
# npm --version
no6.9.0
# node --version
v10.16.0
```
* Non-privileged:
```
# which npm
/usr/bin/npm
# node --version
v10.16.0
# npm --version
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/lib/utils/unsupported.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:786:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/bin/npm:19:21
    at Object.<anonymous> (/usr/bin/npm:152:3)
```
> * `[neale@docker 10]$`: is this already a container image, or a bare metal?
* Bare metal (well a virtual machine actually)

I am interested in what node's/npm's strategy is for trying to resolve "require" targets. What is _telling_ it to look in ```/usr/lib/utils``` or ```/usr/lib/node_modules/npm/lib/utils/```?

**Comment by Trott** [comment]
/ping @nodejs/docker 

I'm not 100% sure what the cause would be here, but things I'd check for clues might be:

* Check to see if the `NODE_PATH` environment variable is set to different values between privileged and non-privileged.

* Check that you `ls -l /usr/lib/utils` gives the same results with and without `--privileged`.

* Even though the `node` binaries report the same version, check that they are the same by running `which node` with and without `--privileged`.

**Comment by nealef** [comment]
> /ping @nodejs/docker
> 
> I'm not 100% sure what the cause would be here, but things I'd check for clues might be:
> 
> * Check to see if the `NODE_PATH` environment variable is set to different values when run with and without `--privileged`
* Non-privileged:
```
# echo $NODE_PATH

# export NODE_PATH=/usr/lib/node_modules/:/usr/lib/node_modules/npm
bash-4.2# npm --version
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/lib/utils/unsupported.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:786:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/bin/npm:19:21
    at Object.<anonymous> (/usr/bin/npm:152:3)
```
* Privileged:
```
# echo $NODE_PATH

```
> * Check that `ls -l /usr/lib/utils` gives the same results with and without `--privileged`.
* Non-privileged:
```
# ls -l /usr/lib/utils
ls: cannot access /usr/lib/utils: No such file or directory
```
* Privileged:
```
# ls -l /usr/lib/utils 
ls: cannot access /usr/lib/utils: No such file or directory
```
> * Even though the `node` binaries report the same version, check that they are the same by running `which node` with and without `--privileged`.
* Non-privileged:
```
# which node
/usr/bin/node
# sha256sum `which node`
2bf90b8bd628abdb9e0945d388d9970b2e616300f2791c393f36e05be9ba0ef6  /usr/bin/node
# sha256sum `which npm`
54eb2244f9d01c46de843e1d08374956ff1608aaef49e9c5f8e87ee7572fcb65  /usr/bin/npm
```
* Privileged:
```
# which node
/usr/bin/node
# sha256sum `which node`
2bf90b8bd628abdb9e0945d388d9970b2e616300f2791c393f36e05be9ba0ef6  /usr/bin/node
# sha256sum `which npm` 
54eb2244f9d01c46de843e1d08374956ff1608aaef49e9c5f8e87ee7572fcb65  /usr/bin/npm
```

**Comment by richardlau** [comment]
> at /usr/bin/npm:19:21

Can you check if `/usr/bin/npm` is a real file or a symlink? Usually it would be a symlink to `npm`'s `bin/npm-cli.js`. [Line 19 of `npm`'s `bin/npm-cli.js` is:](https://github.com/nodejs/node/blob/6e849c33266ab397a19a1c199945256c6f8e5180/deps/npm/bin/npm-cli.js#L19)

```js
 var unsupported = require('../lib/utils/unsupported.js')
```

which would work out if the code is executed from (in your case) `/usr/lib/node_modules/npm/bin/npm-cli.js` but not from `/usr/bin/npm`.

I don't know if it would help much but if you set the `DEBUG` environment variable to `module` Node.js will dump the search paths being used to lookup modules.

**Comment by nealef** [comment]
> Can you check if `/usr/bin/npm` is a real file or a symlink? Usually it would be a symlink to `npm`'s `bin/npm-cli.js`. [Line 19 of `npm`'s `bin/npm-cli.js` is:](https://github.com/nodejs/node/blob/6e849c33266ab397a19a1c199945256c6f8e5180/deps/npm/bin/npm-cli.js#L19)
> 
> ```js
>  var unsupported = require('../lib/utils/unsupported.js')
> ```
> 
> which would work out if the code is executed from (in your case) `/usr/lib/node_modules/npm/bin/npm-cli.js` but not from `/usr/bin/npm`.
> 
> I don't know if it would help much but if you set the `DEBUG` environment variable to `module` Node.js will dump the search paths being used to lookup modules.

* Non-privileged:
```
# ls -l `which npm`
lrwxrwxrwx. 1 root root 38 Jun 10 18:29 /usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```
* Privileged:
```
# ls -l /usr/bin/npm
lrwxrwxrwx. 1 root root 38 Jun 10 18:29 /usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```
#### With NODE_DEBUG - 
* Non-privileged
```
# npm --version |& grep unsupported
MODULE 8: Module._load REQUEST ../lib/utils/unsupported.js parent: .
MODULE 8: RELATIVE: requested: ../lib/utils/unsupported.js set ID to: /lib/utils/unsupported.js from .
MODULE 8: looking for "/lib/utils/unsupported.js" in ["/usr/bin"]
Error: Cannot find module '../lib/utils/unsupported.js'
```
* Privileged
```
# npm --version |& grep unsupported
MODULE 52: Module._load REQUEST ../lib/utils/unsupported.js parent: .
MODULE 52: RELATIVE: requested: ../lib/utils/unsupported.js set ID to: /lib/utils/unsupported.js from .
MODULE 52: looking for "/lib/utils/unsupported.js" in ["/usr/lib/node_modules/npm/bin"]
MODULE 52: load "/usr/lib/node_modules/npm/lib/utils/unsupported.js" for module "/usr/lib/node_modules/npm/lib/utils/unsupported.js"
MODULE 52: Module._load REQUEST semver parent: /usr/lib/node_modules/npm/lib/utils/unsupported.js
MODULE 52: Module._load REQUEST ../lib/utils/unsupported.js parent: /usr/lib/node_modules/npm/lib/npm.js
MODULE 52: RELATIVE: requested: ../lib/utils/unsupported.js set ID to: /usr/lib/node_modules/npm/lib/utils/unsupported.js from /usr/lib/node_modules/npm/lib/npm.js
MODULE 52: looking for "/usr/lib/node_modules/npm/lib/utils/unsupported.js" in ["/usr/lib/node_modules/npm/lib"]
```

**Comment by Hakerh400** [comment]
Can you put the following on the beginning of `npm-cli.js` and post the result

```js
console.log(process.env);
console.log(process.argv);
console.log(process.cwd());
console.log(__filename);
return;
```

**Comment by nealef** [comment]
> Can you put the following on the beginning of `npm-cli.js` and post the result
> 
> ```js
> console.log(process.env);
> console.log(process.argv);
> console.log(process.cwd());
> console.log(__filename);
> return;
> ```

* Non-privileged:
```
{ HOSTNAME: '74008f6566e4',
  TERM: 'xterm',
  PATH:
   '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  PWD: '/root',
  SHLVL: '1',
  HOME: '/root',
  OLDPWD: '/data',
  _: '/usr/bin/npm' }
[ '/usr/bin/node', '/usr/bin/npm', '--version' ]
/root
/usr/bin/npm
```
* Privileged:
```
{ HOSTNAME: '2e5015742410',
  TERM: 'xterm',
  PATH:
   '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  PWD: '/root',
  SHLVL: '1',
  HOME: '/root',
  OLDPWD: '/data',
  _: '/usr/bin/npm' }
[ '/usr/bin/node', '/usr/bin/npm', '--version' ]
/root
/usr/lib/node_modules/npm/bin/npm-cli.js
```
Interesting that ```__filename``` is different.

**Comment by nealef** [comment]
It's something to do with Docker's seccomp profile. Using strace it seems the change in behaviour occurs when the --privileged version (or one that is run with 
```
26    syscall_379(0xffffffffffffff9c, 0x3ffcdafd2c0, 0, 0xfff, 0x3ffcdafcd50, 0x9328) = -1 (errno 38)
```
Whereas the non-privileged version is issuing:
```
27    exit(-100)                        = ?
```
It appears this docker issue is relevant: https://github.com/docker/for-linux/issues/208
```
you will need to install libseccomp-2.3.3 on the host for this to work
```
So I am happy to close this issue and look at getting hold of a higher level of libseccomp.

**Comment by nealef** [comment]
Confirmed the problem is with docker-1.13-88/94 which doesn't whitelist the statx() call. docker-ce does have the required support and node/npm runs as expected.
