### ISSUE TITLE
npm -v is not returning the version of npm on Windows 8.1

### ISSUE THREAD

**Issue by vikram-varshney** [nodejs/help#1984]
* I have installed the latest version of node.js with inbuilt npm in my Windows 8.1 operating system using .msi
* I am getting the version ***"v10.15.3"*** from command `node -v`
* But when I type the command `npm -v`, the batch is started and it is not giving me the version.  The cursor is staying same place:<Pre>
C:*directory*> node -v
v10.15.3
C:*directory*> npm -v
_</Pre>
* When I interrupt the batch using <kbd>Ctrl</kbd>+<kbd>C</kbd>, it shows the message "Terminate batch job (Y/N)?"
* I have installed lower version of node too, but same issue is occurring

**Please let me know from where I was wrong or please provide the solution for this.**

**Comment by wide4head** [comment]
@vikram-varshney Can you try `npm version ` and see the output

**Comment by vikram-varshney** [comment]
> @vikram-varshney I have also tried `npm version`, but the result was same. Attached the screenshot.

![attached_npm](https://user-images.githubusercontent.com/22209630/59964464-d95fc300-951e-11e9-9017-cde1176d52ef.png)
.

**Comment by gireeshpunathil** [comment]
@vikram-varshney - what does `node <path>/node_modules/npm/bin/npm-cli.js -v` (where <path> is your path to the node installation folder) prints?

**Comment by gireeshpunathil** [comment]
ping @vikram-varshney

**Comment by vikram-varshney** [comment]
Sorry, for late response @gireeshpunathil 
I have tried the `node "C:/Program Files/nodejs/node_modules/npm/bin/npm-cli.js" -v`. It returns me the version of the npm. Thanks!

It seems that the npm path was not set to the environment variable or any other issue. Please suggest?

**Comment by gireeshpunathil** [comment]
@vikram-varshney - it looks to me like `npm` is pointing to something else, than the `npm` that is present in `C:/Program Files/nodejs/npm` . Can you do: `echo %PATH%` in a terminal, loop through each of the folders that it gives and see which PATH contains `npm` for the first time? If it is something else other than `C:/Program Files/nodejs/npm`, then you probably have to move it out and then try again.

**Comment by vikram-varshney** [comment]
I have already check this to uninstall node and put `npm` into terminal. It returns me there is not recognized as an internal or external command.
So that there is not any folder contains `npm` first time into the PATH.
I have seen that `npm` running as the batch not as the command line cli. I have also tried the `npm install -g` still the result is same.

**Comment by gireeshpunathil** [comment]
ok, what if you do:
`set PATH=C:/Program Files/nodejs:%PATH%` and then do `npm -v` ? does it work?

**Comment by vikram-varshney** [comment]
Still the result is same. See the screenshot.

![image](https://user-images.githubusercontent.com/22209630/61627816-5efd9c80-ac9e-11e9-9c08-37dfb8b0a4af.png)

**Comment by gireeshpunathil** [comment]
very tricky indeed! can you please paste the first few lines of `npm` file?

**Comment by vikram-varshney** [comment]
Below are the lines inside `npm` file:
<Pre>
#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix

basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

NODE_EXE="$basedir/node.exe"
if ! [ -x "$NODE_EXE" ]; then
  NODE_EXE=node
fi

NPM_CLI_JS="$basedir/node_modules/npm/bin/npm-cli.js"

case `uname` in
  *MINGW*)
    NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
    NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
    if [ -f "$NPM_PREFIX_NPM_CLI_JS" ]; then
      NPM_CLI_JS="$NPM_PREFIX_NPM_CLI_JS"
    fi
    ;;
  *CYGWIN*)
    NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
    NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
    if [ -f "$NPM_PREFIX_NPM_CLI_JS" ]; then
      NPM_CLI_JS="$NPM_PREFIX_NPM_CLI_JS"
    fi
    ;;
esac

"$NODE_EXE" "$NPM_CLI_JS" "$@"
</Pre>

**Comment by gireeshpunathil** [comment]
this is invoked / executed properly only by a cygwin / bash shell; not an MS-DOS prompt. Do you have an `npm.bat` in the same folder? if so, can you pls paste its content?

**Comment by vikram-varshney** [comment]
Yes, Please have a look below lines inside `npm.bat` :

<Pre>
:: Created by npm, please don't edit manually.
@ECHO OFF

SETLOCAL

SET "NODE_EXE=%~dp0\node.exe"
IF NOT EXIST "%NODE_EXE%" (
  SET "NODE_EXE=node"
)

SET "NPM_CLI_JS=%~dp0\node_modules\npm\bin\npm-cli.js"
FOR /F "delims=" %%F IN ('CALL "%NODE_EXE%" "%NPM_CLI_JS%" prefix -g') DO (
  SET "NPM_PREFIX_NPM_CLI_JS=%%F\node_modules\npm\bin\npm-cli.js"
)
IF EXIST "%NPM_PREFIX_NPM_CLI_JS%" (
  SET "NPM_CLI_JS=%NPM_PREFIX_NPM_CLI_JS%"
)

"%NODE_EXE%" "%NPM_CLI_JS%" %*

</Pre>

**Comment by gireeshpunathil** [comment]
ok, so can you remove the `@echo off` and run once? it will show in which command it is hanging.

**Comment by vikram-varshney** [comment]
It is hanging on line
<Pre>
FOR /F "delims=" %%F IN ('CALL "%NODE_EXE%" "%NPM_CLI_JS%" prefix -g') DO (
  SET "NPM_PREFIX_NPM_CLI_JS=%%F\node_modules\npm\bin\npm-cli.js"
)
</Pre>
![image](https://user-images.githubusercontent.com/22209630/61634558-2d410180-acaf-11e9-911b-fe45a08736cc.png)

**Comment by gireeshpunathil** [comment]
So essentially `npm prefix -g` is the command that is failing. (aka `node C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js prefix -g`)

what is the state / contents of `C:\Users\Administrator\AppData\Roaming\npm` ? are there lot of stale elements sitting there? can you temporarily move the content once and try?

**Comment by vikram-varshney** [comment]
I have not any contents over `C:\Users\V4Vikram\AppData\Roaming\npm`

**Comment by gireeshpunathil** [comment]
ok, one last try before we look for alternative debugging arrangements: what does 
`node C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js prefix -g` output?

**Comment by vikram-varshney** [comment]
This returns nothing. See the below screenshot

![image](https://user-images.githubusercontent.com/22209630/61639453-20291000-acb9-11e9-9de2-75f5832e4fbc.png)

**Comment by gireeshpunathil** [comment]
ok; one more thing! :)

do you have a `C:\Users\V4Vikram\.npmrc` file? if so, pls will you show the content?
`type C:\Users\V4Vikram\.npmrc`

**Comment by vikram-varshney** [comment]
Yes, I have that file. Great! 

The path of `preifix` is incorrect. Let me change this to `C:\Users\V4Vikram\AppData\Roaming\npm`

![image](https://user-images.githubusercontent.com/22209630/61640540-25875a00-acbb-11e9-9b66-a8f93f9f8b2d.png)

**Comment by vikram-varshney** [comment]
Got the response. You nailed it ;)

 Thanks for your help.

![image](https://user-images.githubusercontent.com/22209630/61640883-b6f6cc00-acbb-11e9-9488-cca5a1b1c599.png)

**Comment by gireeshpunathil** [comment]
awesome! I was about suggest to take that off, but you got it!

thanks for quick reverts on the debugging exercise, happy to be of help!
