### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: gravator.url is not a function

### ISSUE THREAD

**Issue by danishrajkotiya** [nodejs/help#1985]
const newUser = new User({
name:req.body.name,
email:req.body.email,
avatar,
password:req.body.password
});
actually i have misprinted the const name User it was actually newUser already in the code

_Originally posted by @sonaskyla12 in https://github.com/nodejs/help/issues/1357#issuecomment-400276180_

```
 UnhandledPromiseRejectionWarning: TypeError: gravator.url is not a function

at User.findOne.then.user (/home/danish/NODEJS/devconnector/routes/api/users.js:24:31)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7) (node:22545)

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:22545) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wide4head** [comment]
@danishrajkotiya  It is difficult to pinpoint the cause without seeing more of your code

**Comment by gireeshpunathil** [comment]
@danishrajkotiya - is this still an issue? if so, can you show your full code?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
