### ISSUE TITLE
cannot install npm install -g @angular/cli@latest

### ISSUE THREAD

**Issue by siva1981** [nodejs/help#1986]
Cannot install npm install -g @angular/cli@latest
 

npm ERR! network connect ETIMEDOUT 104.16.18.35:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a507607\npm-debug.log

[npm-debug.log](https://github.com/nodejs/node/files/3294808/npm-debug.log)

**Comment by wide4head** [comment]
Looks like a internet connectivity problem

**Comment by gireeshpunathil** [comment]
ping @siva1981 - is this resolved?

**Comment by siva1981** [comment]
No not yet , windows 10 I guess has problems

**Comment by PoojaDurgad** [comment]
@siva1981 , is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive. closing !!
