### ISSUE TITLE
process.nextTick get called between I/O events

### ISSUE THREAD

**Issue by Zyc0017** [nodejs/help#1987]
* **Node.js Version**: 8.15.1
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I'm having something trouble understanding **poll phase** and **nextTick**

consider the code  below:
```js
http.createServer(async function(req, res) {
    console.log('request');
    
    process.nextTick(() => {
        console.log('tick')
    });
    
    setImmediate(() => {
        console.log('immediate')
    });
    
    console.log('end')
    
    res.end();
}).listen(5000, '127.0.0.1');
```

node should be blocking at poll phase before any requests comes in. then If I send two requests to the server, node should enqueue two events into the poll queue and then process them.

my expectation is that node should process all the events before move to check phase. since the nextTick callback will be called at the end of any phase, so the order of the console should be:
  request
  end
  request
  end
  tick
  tick
  immediate
  immediate

but the actual result is:
  request
  end
  tick
  request
  end
  tick
  immediate
  immediate

I don't know what went wrong....it seems that nextTickQueue will be processed between I/O events?

**Comment by addaleax** [comment]
Yes, the naming here is super unfortunate. `process.nextTick()` does not schedule something on the event loop; instead, it works (and intertwines with) the microtask queue used for Promises, i.e. it runs after the current event handler is finished executing and before returning control back to the event loop. `setImmediate()` is the thing that does actually wait for the next tick of the event loop.

**Comment by Zyc0017** [comment]
@addaleax thanks, that clear things up...
