### ISSUE TITLE
fs.createWriteStream does not recreate file when deleted while stream is still active

### ISSUE THREAD

**Issue by homiedopie** [nodejs/help#1988]
* **Node.js Version**: 10.4.0, 
* **OS**: Ubuntu 16.04
* **Scope (install, code, runtime, meta, other?)**: streams???
* **Module (and version) (if relevant)**:  `rotating-file-stream@1.4.1`

fs.createWriteStream does not recreate file when deleted while still active (file is recreated on windows)

I am expecting the same behavior on Linux but no luck.

```js
let fs = require('fs')

let stream = fs.createWriteStream('test.log', {
    flags: "a",
    mode: 0o777
})

stream.on("open", function (number) {
    console.log('stream open', number)
    let count = 100;
    let interval = setInterval(function () {
        stream.write("the quick brown fox jumps over the lazy dog \n", function (err) {
            console.log('chunk flushed', err)
        })
        console.log('write stream')
        count--
        if (count == 50) {
            fs.unlink('test.log', function (err) {
                console.log('removed file', err)
            })
        }
        if(!count) {
            clearInterval(interval)
            stream.end()
        }
    }, 50)
})
stream.on("ready", function (number) {
    console.log('stream ready', number)
})
stream.on("finish", function (number) {
    console.log('stream finish', number)
})
stream.on("close", function (number) {
    console.log('stream close', number)
})
stream.on("drain", function (number) {
    console.log('stream drain', number)
})
stream.on("error", function (number) {
    console.log('stream error', number)
})
```

**Comment by homiedopie** [comment]
Adding SO Reference: 

https://stackoverflow.com/questions/19301438/node-js-detecting-a-file-opened-with-fs-createwritestream-becoming-deleted/19304284

**Comment by addaleax** [comment]
This is the behaviour that I would expect, and I’m not sure if this issue is requesting a change in Node’s behaviour or asking for an explanation of why – the one answer you got on SO so far seems pretty good for the latter.

**Comment by homiedopie** [comment]
Hey @addaleax ,

Thank you so much for the prompt response! I was referring to the latter, asking for explanation of why. 

Have you encountered this such issue before? Do you have like an idea or workaround for this scenario? It would be awesome (like references and stuff). If none, no worries, im really grateful you responded to this question in a short notice. 

Thanks again and have a nice day!

**Comment by addaleax** [comment]
> Do you have like an idea or workaround for this scenario?

The SO answer provides one option: Using a signal to tell the process to re-open the file. You could also periodically check if the filename exists, but that seems brittle and comes with some overhead.

I think in the end it depends on your use case – why is it important to re-create the file, or why is it being deleted in the first place?

**Comment by homiedopie** [comment]
Well I have a worker that scans a log directory and detects if it is stale or not so it periodically scans the log folder and removes old files. The worker cannot detect if the file is in use by other processes (which can be a nodejs application)

**Comment by addaleax** [comment]
> The worker cannot detect if the file is in use by other processes (which can be a nodejs application)

Maybe looking at the last modification timestamp of the file might help?

But yeah, that sounds basically like what logrotate does, right? In that case, `SIGHUP` might be the way to go :)

**Comment by homiedopie** [comment]
@addaleax - gotcha! thank you for your time once again! will let you know if i am able to make it work. Closing this issue at the moment. Have a nice day! Cheers!
