### ISSUE TITLE
Problem with npm install gulp-cli -g 

### ISSUE THREAD

**Issue by pawel86k** [nodejs/help#1991]
I have a problem with installing the gulp, problems are displayed globally that I have to update the modules that are up to date.
```
C:\Users\pawel>npm install gulp-cli -g
npm WARN deprecated mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
C:\Users\pawel\AppData\Roaming\npm\gulp -> C:\Users\pawel\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js
+ gulp-cli@2.2.0
updated 1 package in 13.966s
```
```
C:\Users\pawel>npm -v
6.9.0

C:\Users\pawel>node -v
v12.4.0
```

This problem occurs when installing node 10 and earlier

**Comment by cutephoton** [comment]
Looks like a recent change. Check out the project pages. They were updated 2 days ago to "disallow proto keys". https://github.com/jonschlinkert/set-value/commit/95e9d9923f8a8b4a01da1ea138fcc39ec7b6b15f or https://github.com/jonschlinkert/mixin-deep/issues/4

I wish the author defined what he meant by critical.

**Comment by AmrAlmagic** [comment]
Have you solved this issue?

**Comment by gireeshpunathil** [comment]
ping @pawel86k

**Comment by AmrAlmagic** [comment]
I solved this issue by removing the full node from the machine and install it again thanks to this [solution](https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows).

**Comment by gireeshpunathil** [comment]
ping @pawel86k again - is it resolved? by following @AmrAlmagic 's workaround?

**Comment by PoojaDurgad** [comment]
@pawel86k  , were you able to follow @AmrAlmagic 's suggestion, or is it still an issue?

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing. feel free to reopen if still an issue
