### ISSUE TITLE
How to use ffmpeg in node and make a list of urls to be download 

### ISSUE THREAD

**Issue by TeRrOkToR** [nodejs/help#1992]
Node version: 10.16.0 LTS
OS: Windows 10

I need help...

I'm using this script to download the video and audio fragments from the vimeo server.

''js

// 1. Open the browser developper console on the network tab
// 2. Start the video
// 3. In the dev tab, locate the load of the "master.json" file, copy its full URL
// 4. Run: node vimeo-downloader.js "<URL>"
// 5. Combine the m4v and m4a files with mkvmerge

const fs = require('fs');
const url = require('url');
const https = require('https');

let masterUrl = process.argv[2];
if (!masterUrl.endsWith('?base64_init=1')) {
  masterUrl+= '?base64_init=1';
}

getJson(masterUrl, (err, json) => {
  if (err) {
    throw err;
  }
  
  const videoData = json.video.pop();
  const audioData = json.audio.pop();
  
  const videoBaseUrl = url.resolve(url.resolve(masterUrl, json.base_url), videoData.base_url);
  const audioBaseUrl = url.resolve(url.resolve(masterUrl, json.base_url), audioData.base_url);
  
  processFile('video', videoBaseUrl, videoData.init_segment, videoData.segments, json.clip_id + '.m4v', (err) => {
    if (err) {
      throw err;
    }
    
    processFile('audio', audioBaseUrl, audioData.init_segment, audioData.segments, json.clip_id + '.m4a', (err) => {
      if (err) {
        throw err;
      }
    });
  });
});

function processFile(type, baseUrl, initData, segments, filename, cb) {
  if (fs.existsSync(filename)) {
    console.log(`${type} already exists`);
    return cb();
  }
  
  const segmentsUrl = segments.map((seg) => baseUrl + seg.url);
  
  const initBuffer = Buffer.from(initData, 'base64');
  fs.writeFileSync(filename, initBuffer);
  
  const output = fs.createWriteStream(filename, {flags: 'a'});
  
  combineSegments(type, 0, segmentsUrl, output, (err) => {
    if (err) {
      return cb(err);
    }
    
    output.end();
    cb();
  });
}

function combineSegments(type, i, segmentsUrl, output, cb) {
  if (i >= segmentsUrl.length) {
    console.log(`${type} done`);
    return cb();
  }
  
  console.log(`Download ${type} segment ${i}`);
  
  https.get(segmentsUrl[i], (res) => {
    res.on('data', (d) => output.write(d));
    
    res.on('end', () => combineSegments(type, i+1, segmentsUrl, output, cb));
    
  }).on('error', (e) => {
    cb(e);
  });
}

function getJson(url, cb) {
  let data = '';
  
  https.get(url, (res) => {
    res.on('data', (d) => data+= d);
    
    res.on('end', () => cb(null, JSON.parse(data)));

  }).on('error', (e) => {
    cb(e);
  });
}

As you can see the script creates the .m4v file for video and .m4a for audio separately.

I know ffmpeg can combine both files with a simple command line such as:

"ffmpeg -i video.mp4 -i audio.wav -c copy output.mkv"

I would like to know how to make the script run the ffmpeg command automatically, ie after downloading the .m4v and .m4a files, the script would execute the ffmpeg command and combine the files into a single .mkv by deleting the source files.

Another question is how to make the script download several URLs with a single command, as if it were a waiting list.

by the way I tried to add the following command line to the script to activate the ffmpeg function, but it did not work.

''ffmpeg command line

const exec = require('child_process').exec;

const child = exec('ffmpeg -i video.mp4 -i audio.wav -c copy output.mkv', (error, stdout, stderr) => {
    if (error) {
        console.error('stderr: =============================', stderr);
        throw error;
    }
    console.log('stdout: ==========================', stdout);
});

console.log('here');

**Comment by Hakerh400** [comment]
> I tried to add the following command line to the script to activate the ffmpeg function, but it did not work.

What exactly did not work? What error did you get? Why do you use `m4v` and `m4a` in the download script, but the you use `mp4` and `wav` formats in the ffmpeg script?

> Another question is how to make the script download several URLs with a single command, as if it were a waiting list.

The easiest way to achieve that is using async functions. I can show you how to do that, but I need to know what exactly the problem with your current script is and what exactly you want to achieve.

**Comment by TeRrOkToR** [comment]
I did a google search and found this script that does exactly what I need.

"https://github.com/eMBee/vimeo-download"

I made some changes in the script to work in python 3.7.3.

I switched .mp3 from the audio to .m4a and .mp4 from the video to .m4v by letting the fragments download faster and at the end by changing the final file to .mkv

Now my only problem is to find a way to create a list of urls for the script to download them in sequence and save the video of each url with a different name, for example 1.mkv, 2.mkv, 3.mkv, 4.mkv ........

If you need I can send you the modified script.

Anyway thank you very much for the help.

**Comment by Hakerh400** [comment]
So, you switched from JavaScript to Python? How is that related to Node.js now? If your goal is just to download several videos from some website, you can use [youtube-dl](https://github.com/ytdl-org/youtube-dl), which supports myriad of websites, including Vimeo (they also provide executable file, so you don't even need Python).

If you still want to download videos using Node.js and FFmpeg, then answer to *"How to create a list of urls for the script to download them in sequence and save the video of each url with a different name?"* would go like this:

```js
const util = require('util');

function download(videoURL, filePath, callback){
  /*
    Download single video from url `videoURL` and save it
    to file at path `filePath`. When the FFmpeg process exits
    call the `callback` function.
  */
}

const urls = [
  // Put some URLs here
];

const promisified = util.promisify(download);

(async () => {
  for(let i = 0; i !== urls.length; i++)
    await promisified(urls[i], `${i + 1}.mkv`);
})().catch(console.log);
```

**Comment by TeRrOkToR** [comment]
Haker I put your code in script trying to use node.js, but it's not worked too...

Your code was put in final part of script.

What I am doing wrong ??? 

Thank very much for your help

**Comment by Hakerh400** [comment]
> I put your code in script trying to use node.js, but it's not worked too...

That's too broad statement. What do you mean by "code doesn't work"? Do you get any errors? Please note that literally copy-pasting the code is not enough, you need to put your script inside `download` function and provide some urls inside the `urls` array.

**Comment by gireeshpunathil** [comment]
ping @TeRrOkToR

**Comment by gireeshpunathil** [comment]
@TeRrOkToR - is this resolved?

**Comment by TeRrOkToR** [comment]
Yes My friend!! Thank you!!

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by gireeshpunathil** [comment]
closing then, cheers!
