### ISSUE TITLE
Buffer.concatenate only produces buffer of last buffer in the array

### ISSUE THREAD

**Issue by sgarcia30** [nodejs/help#1994]
Version: >=10.15.0
Platform: macOS Mojave v 10.14.2

          let buffLength = 0;
          for (let i = 0; i <= arrBuffers.length - 1; i++) {
            buffLength = buffLength + arrBuffers[i].length;
          }
         const buffer = Buffer.concat(arrBuffers, buffLength);
          const attachments = [{
            content: buffer.toString('base64'),
            filename: `invoice-${invoiceDate}.pdf`,
            type: 'application/pdf',
            disposition: 'attachment',
            content_id: customer.id
          }];
          return resolve(attachments);

I am trying to concatenate an array of buffers using the `Buffer.concat()` function.  From the documentation it appears that the first input is an array of buffers, and the second input is the buffer total length.  I then convert that to a string and pass it to another function to be emailed to the client... but when I get the email, it only contains a PDF of the last buffer in the stream.  I was hoping it would put all the invoices (as separate pages) in the pdf attachment. I've googled a bunch and can't find anyone that has a solution to this issue... just people who are having the same issue

**Comment by gireeshpunathil** [comment]
$ cat 1994.js
```js
const buf1 = Buffer.alloc(1024)
const buf2 = Buffer.alloc(1024)
const buf3 = Buffer.alloc(1024)

const arrBuffers = []

arrBuffers.push(buf1)
arrBuffers.push(buf2)
arrBuffers.push(buf3)

let buffLength = 0;
for (let i = 0; i < arrBuffers.length; i++) 
  buffLength = buffLength + arrBuffers[i].length
const buffer = Buffer.concat(arrBuffers, buffLength)
console.log(buffer.length)
```

$ node 1994
3072

I don't see any issue; can you check the content / content length before sending?

**Comment by sgarcia30** [comment]
Yeah.  I did a console.log() of the buffLength, and I got... (452737)
<img width="69" alt="Screen Shot 2019-06-22 at 7 42 57 AM" src="https://user-images.githubusercontent.com/31214561/59963494-8d326580-94c1-11e9-8538-db38e6f30716.png">

**Comment by gireeshpunathil** [comment]
ok, so! was that the expected number?

if not, let us debug the code prior to the concatenation.
If this is the right number, let us debug the code after the concatenation.

In either case, providing the relevant code may help!

**Comment by gireeshpunathil** [comment]
ping @sgarcia30

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if this is still outstanding.
