### ISSUE TITLE
unable to run npm install gulp-cli -g

### ISSUE THREAD

**Issue by jessakim** [nodejs/help#1995]
* **Version**: v.10.16.0
* **Platform**: Win 7
![sc](https://user-images.githubusercontent.com/52117270/59970654-0614da00-9521-11e9-9a0e-af0bcfb76e58.PNG)

* **Subsystem**:

**Comment by devsnek** [comment]
```
+ gulp-cli@2.2.0
updated 1 package in 29.686s
```

this install was successful.

**Comment by gireeshpunathil** [comment]
ping @jessakim

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if this is still outstanding.
