### ISSUE TITLE
How to open external application on TOP

### ISSUE THREAD

**Issue by MucaInera** [nodejs/help#1999]
* **Node.js Version**:
10.16.0
* **OS**:
macOS Mojave (10.14.5)
* **Module (and version) (if relevant)**:
child_process

```
const { spawn } = require('child_process')

spawn('/Applications/Firefox.app/Contents/MacOS/firefox')
```

I try to open an external application using **child_process.spawn** but the problem is that the opened application run always on bottom of the current one.

Is there a way to run the external app on TOP? 

**Current**
![current](https://user-images.githubusercontent.com/26329969/60162525-00a5e100-97fa-11e9-9fa4-1bdddbd86546.png)

**Needed**
![needed](https://user-images.githubusercontent.com/26329969/60162524-00a5e100-97fa-11e9-9c25-8703e23517b6.png)

**Comment by gireeshpunathil** [comment]
can you see if it helps by passing `-foreground` option to the executable?

```js
const { spawn } = require('child_process')
spawn('/Applications/Firefox.app/Contents/MacOS/firefox', ['-foreground'])
```

**Comment by gireeshpunathil** [comment]
ping @MucaInera

**Comment by MucaInera** [comment]
Sorry for the delay.

I'll try this solution asap, although I don't think it works in Windows.

**Comment by MucaInera** [comment]
As I thought, it has no effect on windows.

**Comment by gireeshpunathil** [comment]
thanks for testing this, and the info. How about on mac? did it resolve in mac? this will tell us whether it is a windows specific issue, or a generic one.

**Comment by MucaInera** [comment]
On mac it works fine.

**Comment by gireeshpunathil** [comment]
cc @nodejs/platform-windows

**Comment by benjamingr** [comment]
This is not supported "out of the box" you would need to use a separate tool like https://ritchielawrence.github.io/cmdow/ for controlling window positioning via `spawn`
