### ISSUE TITLE
problem during event transmission node 0.12.7 on windows 

### ISSUE THREAD

**Issue by bbsalsero** [nodejs/help#20]
hi!

here is my problem:

i've got two files,a and b.

in file a , there is a listener that emit event with ,the received data and some manipulation, to file b.

in file b , there is a function that check data and return a true or false state inside an object ,trough an event emits to file a.

so it look like that:

file a
```js
var event = new eventEmiter()

var listener = new listener();

var format = function(){....}
var b = require('b.js')

b(event)
listener.on('data',function(data){

// data here is a json string

event.emit('data',format(data)/it's an object/)

})

events.on('checked',function(data){

// data here is an object

listener.write(format(object)/it's a string/)

})
```
file b:
```js
module.exports=function (event){

var checkdata = function(data){

return new object();
} 
event.on('data',function(){

event.emit('checked',checkdata(data))
})

}
```

so long everything is fine;
my problem now is in my format function return me an error when i try parsing object to string 
it tell me :

```
�,{"type":"handshake","data":{"isvalid":true}}
[SyntaxError: Unexpected token �]
```

and it's right!

but why the hell when i sent an object in evnet it turn like this?

**Comment by Fishrock123** [comment]
@bbsalsero  I added some ```js formatting to mkae it more readable, but it looks like there's some syntax errors. :)

**Comment by bbsalsero** [comment]
thank you for your fast reply,

this is what i've noticed 
'''js

�,{"type":"handshake","data":{"isvalid":true}}
[SyntaxError: Unexpected token �]
js'''


but it should not be, as i already explain in file b i'm emitting an event with an object for second parameter.

when i received it it's still an object but node just added the two first character that way when i parse it i've got syntax error.

**Comment by bbsalsero** [comment]
it wa a problem in my format function my bad .
