### ISSUE TITLE
Installation node

### ISSUE THREAD

**Issue by marcos57** [nodejs/help#200]
I downloaded node for linux (suse 11), then I executed  tar -xvf node-v4.4.6-linux-x64.tar.xz

How Do I install node ?

Best regards
Marcos Baquero

**Comment by marcos57** [comment]
I already  installed node for linux (suse 11), nodejs-6.2.1-105.1.x86_64.rpm, but nmp was not installed.
How Do I install npm ?

Best regards
Marcos Baquero

**Comment by bnoordhuis** [comment]
Presumably your distro vendor has a separate npm package that you can install.  The binary tarball from nodejs.org (the one you mention in your original post) includes npm.

**Comment by marcos57** [comment]
Good morning.
I downloaded from nodejs.org, node v6.2.2 for linux, then I executed tar -xvf node-v4.4.6-linux-x64.tar.xz and was created the directory node-v4.4.6-linux-x64.

Please, How Do I install node ?
Thanks,

Best regards
Marcos Baquero

**Comment by marcos57** [comment]
Good morning.
Sorry, I had an error about version

I downloaded from nodejs.org, node v6.2.2 for linux, then I executed tar -xvf node-v6.2.2-linux-x64.tar.xz and was created the directory node-v6.2.2-linux-x64.

I have Suse Linux Enterprise 11.

Please, How Do I install node ?
Thanks,

Best regards
Marcos Baquero

**Comment by bnoordhuis** [comment]
`node-v6.2.2-linux-x64/bin/node` is the binary to run.  If that doesn't answer your question, please be more specific.

**Comment by marcos57** [comment]
Thanks.

How I run a bin file?
On the directory node-v6.2.2-linux-x64, I write: ./bin/node and appears the ">". What must I write to continue ?

gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64 # ./bin/node
>

**Comment by saadq** [comment]
@marcos57 When you run `node` by itself, it just opens up a JS REPL/prompt. You can type in JavaScript code into it the same way you would do it in a browser console.

Try running `node` on a file. Create a file called `hello.js` and put 

```javascript
console.log('Hello!');
```

inside it. Then run `./bin/node hello.js` and it should run the file.

**Comment by marcos57** [comment]
Thanks.

I'm asking about of installation node because I can't run nmp
When I run "nmp" I have the next error

gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64/bin # npm install -g
express-generator
If 'npm' is not a typo you can run the following command to lookup the
package that contains the binary:
    command-not-found npm
bash: npm: command not found
gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64/bin #

It seems nmp was not installed

The directory :/var/opt/nodejs/node-v6.2.2-linux-x64/bin, contents:

gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64/bin # ls -la
total 26880
drwxrwxr-x 2 500 500     4096 Jun 17 10:32 .
drwxrwxr-x 6 500 500     4096 Jun 17 10:32 ..
-rwxrwxr-x 1 500 500 27481801 Jun 17 10:32 node
lrwxrwxrwx 1 500 500       38 Jun 17 10:32 npm ->
../lib/node_modules/npm/bin/npm-cli.js

**Comment by marcos57** [comment]
Thanks.

I'm asking about of  node installation because I can't run "npm"

When I run "npm" I have the next error:
gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64/bin # npm install -g
express-generator
If 'npm' is not a typo you can run the following command to lookup the
package that contains the binary:
command-not-found npm
bash: npm: command not found
gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64/bin #

It seems "npm" was not installed

The directory :/var/opt/nodejs/node-v6.2.2-linux-x64/bin, contents:
gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64/bin # ls -la
total 26880
drwxrwxr-x 2 500 500 4096 Jun 17 10:32 .
drwxrwxr-x 6 500 500 4096 Jun 17 10:32 ..
-rwxrwxr-x 1 500 500 27481801 Jun 17 10:32 node
lrwxrwxrwx 1 500 500 38 Jun 17 10:32 npm ->
../lib/node_modules/npm/bin/npm-cli.js

**Comment by marcos57** [comment]
Thanks.
Sorry I bother you.

I'm asking about of  node installation because I can't run "npm"

When I run "npm" I have the next error:

gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64/lib/node_modules/npm/bin
# sh ./npm install -g express-generator
npm: line 34: node: command not found

**Comment by marcos57** [comment]
Good afternoon.

When I run "nmp" I have the next error:

gye-srvlinux:/var/opt/nodejs/node-v6.2.2-linux-x64/bin # ./npm install -g
express-operator

/usr/bin/env: node: No such file or directory

Please, Could you help me?

**Comment by bnoordhuis** [comment]
npm expects node to be on the PATH.  Try this:
```
$ export PATH="/var/opt/nodejs/node-v6.2.2-linux-x64/bin:$PATH"
$ npm install -g express-operator
```

**Comment by marcos57** [comment]
Good morning.

Thanks.

This worked !!
