### ISSUE TITLE
http2: match push streams to client requests

### ISSUE THREAD

**Issue by jackhaughton-argon** [nodejs/help#2001]
* **Node.js Version**: 12.4.0
* **OS**: Windows

I'm trying to write an http2 reverse proxy in node. The backend uses http2 server push, so I need to forward pushed streams to the appropriate client. As far as I can tell, as a node http2 client handling the session 'stream' event, there's no way to tell which request the pushed stream relates to. This information seems to be lost in Http2Session::HandleHeadersFrame(), as GetFrameID() returns the ID of the pushed stream rather than the original stream, so only that information makes it through to JS. Is this correct? Is there any other way to accomplish this?

**Comment by gireeshpunathil** [comment]
ping @nodejs/http2
