### ISSUE TITLE
asynchrone JSON RPC API with http

### ISSUE THREAD

**Issue by Firlfire** [nodejs/help#2002]
* **Node.js Version**: 10.15.1
* **Npm Version**: 6.4.1
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:
- [pg-promise](https://github.com/vitaly-t/pg-promise) : 8.7.2
- http

Hi,

I need to implement a JSON RPC API and I chose to make my own with http.
This API will have to :

- Manage a PostgreSQL database (with pg-promise)
- Support a big traffic

The "JSON RPC side" works well but I think I have some difficulties with the "asynchronous" side. I begin with the Promise & async/await so maybe there is no problem and it's all good.

### How my API works : 

1. **simpleServer.js** imports the exposed methods from '**database.js**'. The server use the function _requestHandler_ as listener.
2. This function read the body and then give it the **async** function '_requestProcessor_'.
3. '_requestProcessor_' call the 'database.js' method which (**in a promise constructor**)
   a. build the query from the params
   b. use the query in a pg-promise method (wich is a promise..) and resolve/reject the Promise
   c. '_requestProcessor_' return the result in the response

### My problem
I wrote a script that sends 10000 (adjustable) requests to the API and here is why I think I have a problem : My server processes in two steps:
All the requests until the above 3.1
end all the requests (from 3.2 to the end)

Is there a problem or not ? (I can provide the complete code if it is necessary)

A bit of code
**_simpleServer.js_**
```js
// simpleServer.js
const methods = require('./db/simpleDb').methods;

 /* hidden for brevity */ 

const requestHandler = (req, res) => {
  Log('HANDLED REQUEST');

  const body = [];
  req.on('data', (chunk) => {
    body.push(chunk);
  }).on('end', () => {
    const request = /* extracted from req, hidden for brevity */

    requestProcessor(request).then((response) => {
      sendResponse(res, response);
    });
  });
}

async function requestProcessor(request) {
  Log(`PROCESSING ${request.id}`);
  let response = {
    id: request.id,
    jsonrpc: '2.0',
  };

  try {
    response.result = await Promise.resolve(methods[request.method](request.params));
  } catch (err) {
    const message = err.message || err;
    response.error = { message };
    response.error.code = 15000;
    Promise.reject(response);
  }

  return response;
}

const server = http.createServer(requestHandler);
server.listen(port, (err) => { /* hidden for brevity */ })
```

**_simpleDb.js_**
```js
const pgp = require('pg-promise')();
const conf = require('./conf.json');

const db = pgp(conf);

const methods = {
  'roles.insert': InsertRolesPromise
}

/* hidden for brevity */

// retourne les resultats
function InsertRolesPromise(params) {
  return new Promise((resolve, reject) => {

    var query = pgp.helpers.insert(params.data, Collections.role);
    if(params.return) query += " RETURNING roleId, name";

    Log(`inserting role ${JSON.stringify(params)}`);
    db.any(query)
            .then(data => {
              Log(`INSERTED role ${JSON.stringify(data)}`);
              resolve(data);
            })
            .catch(ex => {
              reject(ex);
            });
  });
}

module.exports = {
  methods
}
```

**Comment by gireeshpunathil** [comment]
@Firlfire - is this still an issue?

looking at your design, I don't see it as a problem, since the batches of db requests will go in one shot (as the db requests are I/O bound and will take time to process), and then when the results start arriving, it is so possible that they all come together. 

do you have any specific concern / observation?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
