### ISSUE TITLE
Decrypting a base64 string encrypted externally using AES-256-GCM

### ISSUE THREAD

**Issue by nero120** [nodejs/help#2003]
I want to use node to decrypt an encrypted base64 string that was encrypted externally using a different system. I am using pbkdf2 with sha256 to generate the key and aes-256-gcm for encryption/decryption.

My code is as follows (I've not include the `getPasswordHash` function for brevity):

```
const key = getPasswordHash();
const keyData = Uint8Array.from(Buffer.from(key, 'base64'));
const encrypted_bytes = Uint8Array.from(Buffer.from(encryptedBookmarks, 'base64'));
const iv = encrypted_bytes.slice(0, 16);
const enc = encrypted_bytes.slice(16);
const encHex = (new Buffer.from(enc)).toString('hex');
const decipher = crypto.createDecipheriv('aes-256-gcm', keyData, iv);

let decrypted = decipher.update(encHex, 'hex', 'utf8');
decrypted += decipher.final('utf8');
```

This code fails with an error `Unsupported state or unable to authenticate data` when calling `decipher.final`, apparently because I have not called `decipher.setAuthTag` according to the [docs](https://nodejs.org/api/crypto.html#crypto_decipher_setauthtag_buffer). But how can I set the auth tag when the encryption was done externally?

If I output `decrypted` to the console after calling `decipher.update` I can see most of the text has been decrypted successfully, so why can't I call `decipher.final` to complete the decryption without calling `decipher.setAuthTag`?

**Comment by abudden** [comment]
I don't claim to have any expertise on this at all, but this intrigued me so I did some googling...

It looks to me like it might be a case of taking the last 128 bytes from the encrypted data and using that as the tag.  [This link](https://developer.mozilla.org/en-US/docs/Web/API/AesGcmParams) suggests that the `tagLength` parameter (if not specified) defaults to 128.  [This link](https://stackoverflow.com/a/44831114/72791) suggests that `crypto.subtle` appends the tag onto the end of the encrypted text.

**Comment by nero120** [comment]
@abudden you STAR! Taking 16 bytes from the end of the encrypted data for the key sorted it, so for completeness:

```
const keyData = Uint8Array.from(Buffer.from(key, 'base64'));
const encrypted_bytes = Uint8Array.from(Buffer.from(encryptedBookmarks, 'base64'));
const iv = encrypted_bytes.slice(0, 16);
const tag = encrypted_bytes.slice(-16);
const enc = encrypted_bytes.slice(16, encrypted_bytes.length - 16);

const decipher = crypto.createDecipheriv('aes-256-gcm', keyData, iv, { authTagLength: 16 });
decipher.setAuthTag(tag);
const decrypted = Buffer.concat([decipher.update(enc), decipher.final()]);
```

**Comment by addaleax** [comment]
@nero120 @abudden Not being a crypto expert by any means, do you think there’s anything we could or should add to the Node.js documentation that would help with that? If so, feel free to suggest something or open a PR if you like :slightly_smiling_face:

**Comment by nero120** [comment]
@addaleax not sure exactly what you're asking for?

**Comment by addaleax** [comment]
@nero120 Rephrasing, do you think the text of https://nodejs.org/api/crypto.html#crypto_decipher_setauthtag_buffer should be modified, in a way that could have helped you with this issue?

**Comment by nero120** [comment]
Ah gotcha! Sorry, being dim - didn't check which repo I was in!! Mondays... 😖

No actually I think the documentation is fine, it was for me to understand that how the platform I was using to encrypt was encoding the auth tag so I think we're all good. Thanks!
