### ISSUE TITLE
Running Node on s390x with Updated GCC

### ISSUE THREAD

**Issue by james-crowley** [nodejs/help#2004]
* **Node.js Version**: 10.15.2
* **OS**: ClefOS on s390x
* **Scope (install, code, runtime, meta, other?)**: Install

I am trying to install Node 10.15.2 on ClefOS which is the clone of Centos on s390x. 

I download the tar from [here](https://nodejs.org/dist/v10.15.2/node-v10.15.2-linux-s390x.tar.gz). After I unpack it, I try running the bin via `./node`, but get the follow error, ``./node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./node)``

After checking what version of GCC came with ClefOS 7, `4.8.5`, I realized it does not meet the minimum version of `4.9.4`. After reading the build docs for Node I decided to install GCC 6.X utilizing the devtoolset-6 packages. 

I issued the following, `yum install -y devtoolset-6-gcc devtoolset-6-gcc-c++`. After the install I sourced the enable file which sets a bunch of environment variables. Now if I issued a `gcc -v` it states, `gcc version 6.3.1 20170216`. 

Then I tried to rerun the node binary but I still get the previous error. It seems to be that node is still trying to look for `libstdc++.so.6` in `/usr/lib64/`.

From reading online it looks like I need to `LD_LIBRARY_PATH` to point to the new `libstdc++.so.6` file. But after issuing a find on my system:

```
bash-4.2# find / -name "*libstdc*"
/opt/rh/devtoolset-6/root/usr/lib/gcc/s390x-redhat-linux/6.3.1/libstdc++.a
/opt/rh/devtoolset-6/root/usr/lib/gcc/s390x-redhat-linux/6.3.1/libstdc++_nonshared.a
/opt/rh/devtoolset-6/root/usr/lib/gcc/s390x-redhat-linux/6.3.1/libstdc++fs.a
/opt/rh/devtoolset-6/root/usr/lib/gcc/s390x-redhat-linux/6.3.1/32/libstdc++.a
/opt/rh/devtoolset-6/root/usr/lib/gcc/s390x-redhat-linux/6.3.1/32/libstdc++.so
/opt/rh/devtoolset-6/root/usr/lib/gcc/s390x-redhat-linux/6.3.1/32/libstdc++_nonshared.a
/opt/rh/devtoolset-6/root/usr/lib/gcc/s390x-redhat-linux/6.3.1/32/libstdc++fs.a
/opt/rh/devtoolset-6/root/usr/lib/gcc/s390x-redhat-linux/6.3.1/libstdc++.so
/usr/lib64/libstdc++.so.6
/usr/lib64/libstdc++.so.6.0.19
/usr/share/gcc-4.8.2/python/libstdcxx
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.19-gdb.py
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.19-gdb.pyc
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.19-gdb.pyo
/var/lib/yum/yumdb/d/257bd3b3f5a210f28f78d78e7b811eee0db0f37c-devtoolset-6-libstdc++-devel-6.3.1-3.1.el7-s390x
/var/lib/yum/yumdb/l/84484066904b2fe7770d552753489f222a2f7a20-libstdc++-4.8.5-36.el7_6.2-s390x
```

It does not look like the updated GCC package produces a `libstdc++.so.6` file. I tried messing around with various environment variables to get node to pick up on the "newer" `libstdc++.*` files, but nothing seems to work.

Another issue I came across was https://github.com/nodejs/node/issues/25774, which seems to pretty much describe my issue, but from reading the post, I do not really see a solution.

Any help you guys can give me is appreciated!

**Comment by james-crowley** [comment]
@nealef maybe you could provide some insights?

**Comment by nealef** [comment]
Node has to be built with gcc >= 4.8.9. The distro has 4.8.5 so we build it with rh-devtoolset-7. The version of node you have was built without including the static library that comes with devtoolset that contains some APIs that are otherwise resolved to a higher level of glibc that comes with devtoolset. 

I rebuilt node-8/-10/-12 with the static library in place and the RPMs may be found in the ClefOS EPEL. https://download.sinenomine.net/epel/epel-7:

* http://download.sinenomine.net/epel/epel-7/s390x/node-8.16.0-1.el7.s390x.rpm
* http://download.sinenomine.net/epel/epel-7/s390x/node-10.16.0-1.el7.s390x.rpm
* http://download.sinenomine.net/epel/epel-7/s390x/node-12.4.0-1.el7.s390x.rpm

**Comment by james-crowley** [comment]
@nealef I saw those packages, and was looking at the `10.16.0` version. My end goal is to install Kibana 7.1.1, but it ships with Node `10.15.2`, hence I was trying to stick with that version. Maybe the minor version update would not affect anything? I am not sure. 

If I wanted Node `10.15.2`, would I need to build it myself? 

The other option I can think of is to build GCC myself, as that should produce the `libstdc++.so` file that I am getting stuck on.

**Comment by nealef** [comment]
I uses 8.x with my kibana. I don't think a dot release will make any difference so I think the node-10 rpm should be fine.

**Comment by mhdawson** [comment]
@james-crowley our expectation was that building/installing the compiler should have provided the required libc++.  @miladfarca could you reach out to @james-crowley to see if you can help debug what's going on.

**Comment by mhdawson** [comment]
One thing I can think of is that the DevToolset is "special" in that it handles this kind of issue by statically linking in things that are not in the default libstdc++ which could explain why it does not have an updated version.  Building it would probably resolve the problem.

We are working on improving this.  Now that DevToolset is available on s390,  we've switched master for Node.js to build using the DevToolset.  We are hoping to backport this for Node.js 12.x as well.  Going further back (ex 10.x) will be more of a challenge but something we'll revisit when/if we get the backport for 12.x completed.

**Comment by nealef** [comment]
When I build it I make sure devtoolset-8-libstdc++-devel is installed (or in the BuildRequires) so that /opt/rh/devtoolset-8/root/usr/lib/gcc/s390x-redhat-linux/8/libstdc++.a is present during the node build. Attached is the RPM spec file I use to build -10.

[node.spec.txt](https://github.com/nodejs/help/files/3331867/node.spec.txt)

**Comment by miladfarca** [comment]
We will be looking at this on a rhel box with and without devtoolset installed to investigate further.

**Comment by miladfarca** [comment]
Looking at devtoolset 6 and 7 on rhel, it only includes `libstdc++.so.6.0.19` (we need 6.0.20 as a minimum, to match GLIBCXX_3.4.20).

The trick is to find a libstdc++-4.9 which is compiled with glibc-2.17 or earlier and extract the libstdc++.so file and adding it to the `LD_LIBRARY_PATH` path.
```
rpm2cpio <package>.rpm | cpio -idmv
```
A more straight forward solution would be to building glibc and libstdc++ (which requires building gcc).

**Comment by nealef** [comment]
I build node/8/10/12 with devtoolset-8 and its libstdc++_nonshared.a archive that comes with devtoolset-8-libstdc++-devel has seems to have everything that is required.

**Comment by james-crowley** [comment]
@miladfarca I can confirm that building GCC 8.3 provides the needed `libstdc++.so` file.

It looks like either we build GCC and use the files that are generated with the prepacked Node. Or we install devtoolset-X and build Node. Unless there is some fix we can do upstream like @mhdawson mentioned.

Ideally I am trying to avoid manually building things since I will be passing this setup on to others. I am going to try to install devtoolset and Node via the provide packages to see if that combination will work for Kibana.

**Comment by nealef** [comment]
> Ideally I am trying to avoid manually building things since I will be passing this setup on to others. I am going to try to install devtoolset and Node via the provide packages to see if that combination will work for Kibana.

Do you have access to devtoolset-8? If so, try it. This is what works for me.

**Comment by james-crowley** [comment]
@nealef Looks like Kibana hard codes in the needed Node version.

```
bash-4.2# kibana
Kibana does not support the current Node.js version v10.16.0. Please use Node.js v10.15.2.
```

@miladfarca @mhdawson This is for a potential client of IBM's do you guys have any suggestions on where to go from here? I am thinking manually building Node v10.15.2 would be the next step, but like I mentioned before I am trying to avoid passing that burden off to the client.

**Comment by nealef** [comment]
I'll put 10.15.2 through my build process and add it to the EPEL repo.


-------- Original message --------

**Comment by miladfarca** [comment]
@james-crowley If the current node 10 binary is going to be used as is then the user needs to make sure their system libstdc++ matches either by:
- Using docker and running it within an Ubunutu container (since it should have the latest lib by default, this would be the easier method)
- Upgrade their system to have the a matching libstdc++
- Finding a libstdc++-4.9 snd extracting the libstdc++.so
- Compiling gcc from source and pointing `LD_LIBRARY_PATH` to the generated libstdc++

**Comment by nealef** [comment]
> I'll put 10.15.2 through my build process and add it to the EPEL repo.
```
=======================================================================================================================================
 Package                      Arch                          Version                                 Repository                    Size
=======================================================================================================================================
Installing:
 node                         s390x                         10.15.2-1.el7                           epel                          13 M

Transaction Summary
=======================================================================================================================================
Install  1 Package

Total download size: 13 M
Installed size: 52 M
Is this ok [y/d/N]: y
Downloading packages:
node-10.15.2-1.el7.s390x.rpm                                                                                    |  13 MB  00:00:04     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : node-10.15.2-1.el7.s390x                                                                                            1/1 
  Verifying  : node-10.15.2-1.el7.s390x                                                                                            1/1 

Installed:
  node.s390x 0:10.15.2-1.el7                                                                                                           

Complete!
bash-4.2# node --version
v10.15.2
bash-4.2# npm --version
6.4.1
```
