### ISSUE TITLE
gradually increasing cpu usage on large scale application

### ISSUE THREAD

**Issue by aetheryx** [nodejs/help#2007]
* **Node.js Version**: 10.16.0 (LTS), also tested on 12.4 (latest)
* **OS**: Debian 9
* **Scope (install, code, runtime, meta, other?)**: code/runtime

We're running a large scale application in Node.js that's currently maxing out our CPU relatively quickly. Our load average sits at ~50% once the application is fully booted and gradually increases to over 100% in a matter of just a few hours - it's almost as if there's a "cpu leak". The application is clustered and spawns 48 processes (1 for each CPU thread).

We're trying to hunt down what's specifically causing this issue. We took the following v8 profile log: https://aeth.dev/AWb  

We'd love some help trying to get a better idea of what could have caused this CPU usage issue.  The profile log seems to point to `epoll_pwait`:
![image](https://user-images.githubusercontent.com/25572140/60302372-115a7200-9934-11e9-8952-4f10125306dc.png)  

We tried to find more information about this and we could only really find [this](https://github.com/libuv/libuv/issues/2162) libuv issue, for which a fix shipped in `1.26`, but our version of Node ships with `1.28`.  

Since `epoll_pwait` specifically seems to refer to file descriptors, we took a look at the file descriptors used by one of the cluster processes. There are 48 of these clusters, and the amount of file descriptors they each have opened ranges from ~120 to ~160. Out of the 154 file descriptors opened by the cluster we chose, 135 were `socket:`s, 8 were `pipe:`s, 6 were `anon_inode:`s and the remaining 5 were irrelevant (full log [here](https://aeth.dev/8FQ)). 

We're hoping someone could offer us some help with reading these logs, as we have little to no idea what they actually mean on such a bare metal level. Or we'd love it if someone could point us in the right direction to find the culprit.

**Comment by gireeshpunathil** [comment]
@aetheryx - when you experience high CPU, can you attach sytem tracer and see what happens around the polling loop? basically its input, output and the rate at which the poller returns.
`strace -f -ttt -T -p <pid>`

**Comment by melmsie** [comment]
Hiya @gireeshpunathil

I work with Aetheryx. I'm fairly new to this type of debugging, especially low level stuff like this. 
I took [a screenshot](https://i.imgur.com/BiOfEMa.png) of a bit of the strace. Hopefully this is helpful.

**Comment by gireeshpunathil** [comment]
@melmsie - thnx. unfortunately your link is not accessible to me, browser blocks it for being insecure. Can you place it in a gist?

also pinging @nodejs/libuv if they can provide additional recommendations.

**Comment by melmsie** [comment]
@gireeshpunathil Sorry, was an imgur link. Here's a gist [GIST](https://gist.github.com/melmsie/f6952453f87413c934fa760c25429be2)

I just grabbed a random chunk from the output, it's moving a million miles per hour. If you need more, let me know and I can try my luck at capturing it. It's difficult to pin down when a single cluster is ramping up it's cpu usage more than the rest as we have 48 clusters running.

**Comment by gireeshpunathil** [comment]
this pattern:
`epoll_pwait(4, [], 1024, 1, NULL, 8) = 0`

I am not sure why the poll is called with NULL timeout - that leads to immediate return, wasting CPU if there are no readied fds.

I will not make any inferences from it, as I don't know if there is a valid case for it.

**Comment by gireeshpunathil** [comment]
> If you need more, let me know and I can try my luck at capturing it.

@melmsie - if this is captured when you experienced high CPU, this snapshot is fine I guess.

**Comment by melmsie** [comment]
@gireeshpunathil What could cause this in a node project?

**Comment by gireeshpunathil** [comment]
@melmsie - let us wait to hear from libuv!

**Comment by gireeshpunathil** [comment]
@melmsie - a quick check, do you have a `setInterval` with little or 0 interval and tiny code in it somewhere in you app?

**Comment by aetheryx** [comment]
@gireeshpunathil Melmsie went to bed for the night.  

Your comment made me want to verify something, and I think we *might have* found our culprit. We did indeed have a `setInterval` with the interval being undefined, so basically `setInterval(func, 0);`. I've fixed this interval and I really hope this was the issue, but we won't be able to tell for a few hours.  

The function that was being ran at an interval of `0`: 
```js
_sweep () {
  for (const [key, inactiveSince] of this._entitiesAge) {
    if ((inactiveSince + this.ttl) < Date.now()) {
      this.remove(key);
      this._entitiesAge.delete(key);
    }
  }
}
```

**Comment by gireeshpunathil** [comment]
awesome! thanks for the confirmation. So depending on the number of entries in `this._entitiesAge` the degree of `tiny-ness` can vary, but as we are deleting things from the object, the speed of this loop will increase, and for most practical purposes, I guess this can lead to high CPU in the event loop. Let us see!

**Comment by aetheryx** [comment]
In this specific instance of the class, entitiesAge was seeing 40 new entries roughly every minute

**Comment by aetheryx** [comment]
@gireeshpunathil after about 8 hours of uptime things are stable - can confirm this solved the issue. Thank you so, so much, we spent a lot of time trying to debug this and we have you to thank for it finally being over. :heart: :heart:

**Comment by bnoordhuis** [comment]
@gireeshpunathil 

> epoll_pwait(4, [], 1024, 1, NULL, 8) = 0

That's not a NULL timeout but a NULL signal mask. The timeout is the 4th argument and it's 1 ms.

**Comment by gireeshpunathil** [comment]
@bnoordhuis - thanks for the correction! It is then a very interesting coincidence that we eventually caught the issue, starting with a wrong premise! :)
