### ISSUE TITLE
Virus alert with node-v10.16.0

### ISSUE THREAD

**Issue by leviathan009** [nodejs/help#2012]
* **Node.js Version**: 10.16.0
* **OS**: Windows 10

Hi, just today I have installed node.js after downloading it from nodejs.org. When I installed @angular/cli, the operation was cancelled by BitDefender issuing an virus alert for nodejs.exe.

Hence I am currently unable to use node.js on this machine.

**Comment by wide4head** [comment]
@leviathan009 Thanks for letting us know. Can you pls provide the link to the executable file in question.

**Comment by leviathan009** [comment]
> @leviathan009 Thanks for letting us know. Can you pls provide the link to the executable file in question.

Sure, here it is: https://nodejs.org/dist/v10.16.0/node-v10.16.0-x64.msi

**Comment by wide4head** [comment]
@leviathan009 <https://github.com/leviathan009>  The install file itself
seems to be okay with most virus definitions.

Can you please upload the nodjs.exe to
https://www.virustotal.com/gui/home/upload and check.

**Comment by leviathan009** [comment]
@wide4head  Here is the result of virustotal as you have requested:
https://www.virustotal.com/gui/file/4d106b32293453f1ed037650c3051db854f853f7cef5a06e659e5c7d978cadb7/community

It does appear to be flawless.

**Comment by gireeshpunathil** [comment]
so this would essentially mean an issue with the virus definition of the antivirus software in your system I guess.

**Comment by leviathan009** [comment]
I have tried again, this time the installation went fine. Bitdefender was triggered during installation of angular/cli though. After another run the installation of angular/cli worked and Bitdefender fired an alert during creating a new project in angular (ng new foobar). I will also reach out to the Angular and Bitdefender team.

**Comment by leviathan009** [comment]
Bitdefender did reply and they recommended to release the file from virus quarantine and use it regularily.
So...here I go I guess.
