### ISSUE TITLE
EACCES: permission denied Node v12.4.0 while installing ElectronJs

### ISSUE THREAD

**Issue by the-blackpirate** [nodejs/help#2013]
Raghus-MacBook-Pro% **sudo** npm i -D electron@latest

> electron@5.0.6 postinstall /Users/raghusharma/node_modules/electron
> node install.js

Downloading tmp-1488-1-SHASUMS256.txt-5.0.6
[============================================>] 100.0% of 4.74 kB (4.74 kB/s)
/Users/raghusharma/node_modules/electron/install.js:49
  throw err
  ^

[Error: EACCES: permission denied, mkdir '/Users/raghusharma/node_modules/electron/dist'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/raghusharma/node_modules/electron/dist'
}
npm WARN enoent ENOENT: no such file or directory, open '/Users/raghusharma/package.json'
npm WARN raghusharma No description
npm WARN raghusharma No repository field.
npm WARN raghusharma No README data
npm WARN raghusharma No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@5.0.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@5.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raghusharma/.npm/_logs/2019-06-29T05_40_23_410Z-debug.log

![Screenshot 2019-06-29 at 11 14 53 AM](https://user-images.githubusercontent.com/48377045/60380232-c50c5080-9a5f-11e9-9bb7-e42693ef70ab.png)

**Issue**
I am facing this issue few days I used chown and change the directory privileges and tried sudo many times but I don't know why this problem occurs. you can see i am using sudo but why its dont getting written to the node_modules directory

Version - 12.4.0 (Node -v report)
System - OS X 
Subsystem - Darwin Mac Mojave 10.14.5

**Log file in .npm/logs report**
-----------------------------
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--ignore-scripts',
1 verbose cli   'types-registry@latest'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose npm-session 976be6e5dbb22c8d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/types-registry 2484ms
8 silly fetchPackageMetaData error for types-registry@latest EACCES: permission denied, mkdir '/Users/raghusharma/.npm/_cacache/index-v5/48/6e'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 2577ms
11 verbose stack Error: EACCES: permission denied, mkdir '/Users/raghusharma/.npm/_cacache/index-v5/48/6e'
12 verbose cwd /Users/raghusharma/Library/Caches/typescript/3.5
13 verbose Darwin 18.6.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--ignore-scripts" "types-registry@latest"
15 verbose node v12.4.0
16 verbose npm  v6.9.0
17 error path /Users/raghusharma/.npm/_cacache/index-v5/48/6e
18 error code EACCES
19 error errno -13
20 error syscall mkdir
21 error Error: EACCES: permission denied, mkdir '/Users/raghusharma/.npm/_cacache/index-v5/48/6e'
21 error  [OperationalError: EACCES: permission denied, mkdir '/Users/raghusharma/.npm/_cacache/index-v5/48/6e'] {
21 error   cause: [Error: EACCES: permission denied, mkdir '/Users/raghusharma/.npm/_cacache/index-v5/48/6e'] {
21 error     errno: -13,
21 error     code: 'EACCES',
21 error     syscall: 'mkdir',
21 error     path: '/Users/raghusharma/.npm/_cacache/index-v5/48/6e'
21 error   },
21 error   isOperational: true,
21 error   stack: 'Error: EACCES: permission denied, mkdir ' +
21 error     "'/Users/raghusharma/.npm/_cacache/index-v5/48/6e'",
21 error   errno: -13,
21 error   code: 'EACCES',
21 error   syscall: 'mkdir',
21 error   path: '/Users/raghusharma/.npm/_cacache/index-v5/48/6e'
21 error }
22 error The operation was rejected by your operating system.
22 error It is likely you do not have the permissions to access this file as the current user
22 error
22 error If you believe this might be a permissions issue, please double-check the
22 error permissions of the file and its containing directories, or try running
22 error the command again as root/Administrator (though this is not recommended).
23 verbose exit [ -13, true ]

**Comment by addaleax** [comment]
> [Error: EACCES: permission denied, mkdir '/Users/raghusharma/node_modules/electron/dist'] {

I’d start by looking at the output of `ls -lhd /Users`, `ls -lhd /Users/raghusharma`, etc. and seeing if any of those directories have obviously odd permissions?

Also, it’s probably worth a try to run `npm install` without `sudo` and/or not in the top level of your user’s home directory.

**Comment by bhamon** [comment]
Same error here.
A local `npm install electron` with simple user privileges works.

When you perform a `sudo npm install -g electron` you got the EACCES error.
Here is the relevant portion in the error log file:
```
4149 verbose stack Error: electron@5.0.6 postinstall: `node install.js`
4149 verbose stack Exit status 1
4149 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
4149 verbose stack     at EventEmitter.emit (events.js:203:13)
4149 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4149 verbose stack     at ChildProcess.emit (events.js:203:13)
4149 verbose stack     at maybeClose (internal/child_process.js:1021:16)
4149 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

It seems that the postinstall script doesn't inherit the root rights from the npm process.

**Comment by gireeshpunathil** [comment]
related: #2041

**Comment by gireeshpunathil** [comment]
I think either:
 - remove `sudo` and try or
 - download the packge, edit the `postInstall` step and percolate the `sudo` to the child node as well and run `npm install` ?

**Comment by gireeshpunathil** [comment]
@the-blackpirate - were you able to apply one of the above suggestions and workaround the issue?

**Comment by gireeshpunathil** [comment]
reported to upstream npm: https://npm.community/t/inability-to-percolate-sudo-mode-to-postinstall/10809

**Comment by gireeshpunathil** [comment]
@the-blackpirate , @bhamon - please add `--unsafe-perm` option as documented in https://docs.npmjs.com/misc/config#unsafe-perm . This is the recommendation we got from the npm community.

**Comment by gireeshpunathil** [comment]
closing as answered; pls re-open if the supplied solution (previous comment) is not working for you
