### ISSUE TITLE
compare two date object

### ISSUE THREAD

**Issue by etrikhayri** [nodejs/help#2016]
i'm trying to get date from mongodb using mongoose .
i'm working on nodejs v10.16 and mongoose v5.6.

so my issue is how to get list of users who subscribed before 30 days, i used $lt to compare date but i get nothing.

- this is my schema model:

`
var VisitorsSchema = new Schema({ firstname: String, lastname: String, subDate: Date }, { collection: 'users' });`

- this how i'm trying to get users subscribed before 30 days :

`users.find({ "subDate": { $lt: new Date(new Date().setDate(new Date().getDate() - 30)) } }, function (err, resp) { if (err) { return next(err); } console.log(resp); res.send(resp); });`

- Note: when i get one user and compare his date of subscribe like this:

`var de=new Date(new Date().setDate(new Date().getDate()-30)); res.send(resp[0]['subDate']>de);
`it works fine and i get correct result(true or false).

subDate's format in mongo is like this : 2017-10-05T11:25:00+02:00

i try also  to work with moment.js library, i have added this part of code just to get all users subscribed before to day but i get nothing :

const today = moment().startOf('day'); visitors.find({ "creationDate": { $lte:today } }

**Comment by wide4head** [comment]
@etrikhayri Please check if this module will help you https://www.npmjs.com/package/date-diff

**Comment by etrikhayri** [comment]
i think tha the problem is how using $lt

**Comment by gireeshpunathil** [comment]
@etrikhayri - is this still outstanding? I think the `$lt` semantics is interpreted by the db client, not node.js. It is worthwhile to see if the date format that is produced for filter is matching the expectation of the client driver; and if not translate that to meet the criteria.

**Comment by PoojaDurgad** [comment]
@etrikhayri , is this still an issue?

**Comment by etrikhayri** [comment]
problem resolved by adding toISOString() :

$lte: new Date(new Date().setDate(new Date().getDate()-daysNumber)).toISOString()
