### ISSUE TITLE
[TLS/HTTPs] Accept a specific invalid certicate

### ISSUE THREAD

**Issue by julien-f** [nodejs/help#2019]
* **Node.js Version**: Node 8, 10 & 12
* **OS**: Fedora 30 (Workstation Edition)
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Is your feature request related to a problem? Please describe.**

My application connects to HTTPs servers which may have invalid certificates (self-signed, expired, invalid domains, etc.) and I want to handle this the best way possible.

Initially I thought of falling back to HTTP when the certificate was invalid but it would allow anyone to spy on the request (e.g. in broadcast networks like WiFi).

Then I decided to always use HTTPs but to ask the user to accept the error and to voluntarily disable `rejectUnauthorized` in case of invalid certificates.

But it is, IMHO, still not good enough because is is vulnerable to man-in-the-middle attacks.

**Describe the solution you'd like**

What I would like to do is very similar to what browsers are doing: display the invalid certificate to the user, and let them accept this specific one if they trust it.

Is there any way of doing this?
If not, don't you think this should be implemented?

**Describe alternatives you've considered**

I've tried fetching the certificate via `rejectUnauthorized: false` and `socket.getPeerCertificate()` and using it as a `ca` but it only works for self-signed certs, not other kinds of invalidity.

Moved from nodejs/node#28496

**Comment by bnoordhuis** [comment]
How do browsers actually implement that? My guess is that they use the invalid certificate for encryption only, not authentication.

> not good enough because is is vulnerable to man-in-the-middle attacks

I expect browsers aren't any different.

I suppose, as a special case, an expired certificate can have some measure of authentication by checking whether it still chains to a trusted CA.

I don't think Node.js currently lets you do that. You could feature request it but I don't know how much traction it'll get. It seems like a very marginal use case. Potentially dangerous too, if misused.

> I've tried fetching the certificate via rejectUnauthorized: false and socket.getPeerCertificate() and using it as a ca but it only works for self-signed certs, not other kinds of invalidity.

Just curious, why would you expect that?

**Comment by julien-f** [comment]
> How do browsers actually implement that? My guess is that they use the invalid certificate for encryption only, not authentication.

I'm not familiar with TLS specifics but I guess it should be possible to validate a certificate by identity instead of validating the authorities chain.

Which is really better than simply `rejectUnauthorized: false` because it is only sensitive to MiM on the first connection, not on the following ones.

What I would like to do in my app is present the certificate to the user, and if they choose to accept it, save it in a store for subsequent uses.

> I expect browsers aren't any different.

I've not check that yet but I think browser would detect if the certificate change and is no longer the manually accepted one.

> Just curious, why would you expect that?

I've saw in the documentation that self-signed certificates can be validate against themselves as a CA.

I guessed this would not work for invalid certificates but I tried anyway :slightly_smiling_face:

**Comment by bnoordhuis** [comment]
Persistence of certificates is something you can already do with `socket.getPeerCertificate()`, can't you? On the next connection attempt, you'd check that `.raw` or `.fingerprint256` matches what you stored in your data store after the first connection.

**Comment by julien-f** [comment]
Thank you for your answer, I'll run some tests and get back to you :slightly_smiling_face:

**Comment by julien-f** [comment]
AFAIU, using `checkServerIdentity` appears ideal for my use case, unfortunately:

- it does not replace the default validation, only complements it, and will not allow accepting an invalid (or self-signed) cert
- it is not ran if `rejectUnauthorized` is `true`
