### ISSUE TITLE
how many files can I create in a for loop

### ISSUE THREAD

**Issue by hwbeauty** [nodejs/help#202]

**Comment by hwbeauty** [comment]
![image](https://cloud.githubusercontent.com/assets/19684476/16331175/f445e5de-3a20-11e6-8773-ec3e4bc53593.png)

**Comment by addaleax** [comment]
The exact value depends on your operating system.

You may also want to look into using https://www.npmjs.com/package/graceful-fs instead of the core `fs` module if you keep hitting EMFILE errors.
