### ISSUE TITLE
Can we do stuff like pirates (require hooks) with ES modules?

### ISSUE THREAD

**Issue by trusktr** [nodejs/help#2020]
For example, can we make things like `ts-node` or `@babel/register`, but that work with require hooks? Or, is `require` already used under the hood and it already works?

**Comment by devsnek** [comment]
You can use https://nodejs.org/api/esm.html#esm_experimental_loader_hooks for anything loaded with import. If the import is cjs and uses require(), require extensions will additionally work.

**Comment by gireeshpunathil** [comment]
@trusktr - is this resolved?

**Comment by PoojaDurgad** [comment]
@trusktr , is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing. feel free to reopen if still an issue
