### ISSUE TITLE
read only calendar events - exchange server

### ISSUE THREAD

**Issue by shashi004** [nodejs/help#2021]
Hi,

Am able to connect and pull emails from microsoft exchange server and gmail imap server using nodejs imap library.

But

1. how can i read/pull only calendar events (not required normal emails).
2. how can i read/parse the complete event data such as From address, To address (participants), event location, from datetime and end datetime etc., as microsoft exchange server calendar event is different than gmail calander event
Please share the sample script, if possible :)

Thanks in advance.

**Comment by wide4head** [comment]
Hopefully node exchange web services module (
https://www.npmjs.com/package/node-ews) can help you out.

**Comment by shashi004** [comment]
Thanks @wide4head for quick reply, sure will look into it.  :)

**Comment by gireeshpunathil** [comment]
@shashi004 - is this resolved?

**Comment by PoojaDurgad** [comment]
@shashi004 , is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
