### ISSUE TITLE
1 net.Server vs 100 net.Server

### ISSUE THREAD

**Issue by nimit95** [nodejs/help#2023]
Node v6
Linux

I did a kind of benchmarking, 
I made two node scripts, 
1) With 1 net.Server
2) With 100 net.Server

Sent in total 100000 request on first script server and 1000 request each of the 100 server in second script ie 100 * 1000 = 100000 request

I see a huge difference between the performance, with 1 net.Server I see major improvement over 100 net.Servers

**Comment by addaleax** [comment]
Is your question why there’s a difference? That’s going to be hard to answer without knowing what code exactly you benchmarked…

**Comment by nimit95** [comment]
https://gist.github.com/Raj-7799/f31d2680d70716256fd77697ad471889
