### ISSUE TITLE
undefined reference to class property when calling function

### ISSUE THREAD

**Issue by rjinski** [nodejs/help#2027]
* **Version**: v12.5.0
* **Platform**: MacOS 10.14.5 (Darwin Kernel Version 18.6.0)
* **Subsystem**: N/A

```js
class Foo {
  constructor() { this.foobar = "hello World"; }
  bar() {
    console.log(this.foobar);
  }
}

function main() {
  const f = new Foo();
  f.bar();
  setInterval(f.bar, 300);
}

main();
```

**Expected Output**
```
hello World
hello World
hello World
hello World
hello World
hello World
^C
```

**Actual**
```
hello World
undefined
undefined
undefined
undefined
undefined
^C
```

It seems as through the class has been destroyed and only the reference to the function still exists in scope

**Comment by addaleax** [comment]
> `setInterval(f.bar, 300);`

This makes `setInterval` call the `f.bar` function, but unfortunately it does *not* store `f` as the `this` object for it well; what essentially happens is this:

```js
class Foo {
  constructor() { this.foobar = "hello World"; }
  bar() {
    console.log(this.foobar);
  }
}

const f = new Foo();
const timer = { callback: f.bar };
// prints 'undefined', because the bar() function is called with `timer` as `this` instead of `f`
timer.callback(); 
```

Using either `setInterval(f.bar.bind(f), 300);` or `setInterval(() => f.bar(), 300);` should work.

**Comment by BridgeAR** [comment]
@addaleax description seems to the point, thus I'll close this as answered.
