### ISSUE TITLE
not able to install node js . plz  help 

### ISSUE THREAD

**Issue by vijayrahul0787** [nodejs/help#2029]
an error such as missing dll file , is coming 
![Untitled](https://user-images.githubusercontent.com/29709030/60721526-e4b5e400-9f4b-11e9-84e4-d01274f465f8.jpg)

**Comment by yathamravali** [comment]
@vijayrahul0787 
Go to `C:\Users\<username>\AppData\Local\Temp` and right click on Temp folder and click on properties. In properties tab goto Security and everyone will be selected, click on edit and give all permissions i.e. ( (Full control, Modify, read and execute, list folder contents, read, write) and click apply and then ok.

**Comment by gireeshpunathil** [comment]
ping @vijayrahul0787 - is this still outstanding?

**Comment by PoojaDurgad** [comment]
@vijayrahul0787 , were you able to follow @yathamravali 's suggestion? or still an issue?

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing. feel free to reopen if still an issue
