### ISSUE TITLE
how can i write big file in  res.on('data',chunk){ }  to not make  out of memory  

### ISSUE THREAD

**Issue by hwbeauty** [nodejs/help#203]

**Comment by addaleax** [comment]
An example of your current code (that does hit memory limits?) would probably be helpful

**Comment by hwbeauty** [comment]
CODE here:
var options = {
         hostname: '127.0.0.1',
         port: 8000,
         path:'/package/software.tar.gz',
         method: 'GET',
         headers: {
             'Content-Type': 'application/x-www-form-urlencoded',
         }
  };



var req = http.request(options, function(res){
            var data = '';
 
     res.on('data',function(chunk){
              data+= chunk;
     });
         
     res.on('end',function(){
	      fs.writeFileSync("software.tar.gz",data,'binary');
	 
	 })
}
req.end();


if  the file(  software.tar.gz, )  size is very big  (2GB  or 4GB ),  i am worried about   there  is (  data+= chunk;)   out of memery risk

**Comment by addaleax** [comment]
Well, yes, if you’re buffering all the data a local variable, you’re probably in danger of hitting some memory limit (even if it’s just the size limit for `Buffer`s, it doesn’t have to be a real out-of-memory).

You can avoid this (and simplify your code) by using the the fact that Node.js supports streaming data directly into its destination:

```js
var req = http.request(options, function(err, res){
  res.pipe(fs.createWriteStream('software.tar.gz'));
});

req.end();
```

Also, generally in Node.js there’s an `error` argument to callbacks that’s at the first position and that you won’t be able to leave out.

You may also want to be careful about storing binary data in a string – by default, the incoming `Buffers`s are decoded using UTF8 when appended to a string (as in `data+= chunk`), which may lead to data corruption if the contents are not actually encoded using UTF8 (e.g. your code above will always fail for actual .gz files).

**Comment by addaleax** [comment]
And by the way, you can wrap pieces of source code that you post on github in  ```` ``` ```` so that it becomes more readable, for example:

    ```js
    console.log('Hello world!');
    ```

becomes

```js
console.log('Hello world!');
```

:smile:
