### ISSUE TITLE
Node Server msg error

### ISSUE THREAD

**Issue by liscuate** [nodejs/help#2030]
* **Node.js Version**: 10.16.0
* **OS**: Windows 7
* **Scope (install, code, runtime, meta, other?)**: Server

I keep getting this error. 

https://cdn.discordapp.com/attachments/597131931406172180/597132031289327629/unknown.png

**Comment by gireeshpunathil** [comment]
@liscuate - could you please provide a standalone test case that reproduces the issue?

**Comment by gireeshpunathil** [comment]
@liscuate

**Comment by liscuate** [comment]
Sorry for the late reply but I got it fixed. I used a non-stable version.

**Comment by gireeshpunathil** [comment]
closing then, cheers!
