### ISSUE TITLE
worker_threads master thread is freezed

### ISSUE THREAD

**Issue by gunterdo** [nodejs/help#2031]
* **Node.js Version**: 12.6.0
* **OS**: Ubuntu 18.04

I've written scrapper, which uses tor and chrome through puppeteer. It has master thread, 2 thread slaves which parse search page and 2 thread slaves which parse the last page from search.

After about 9 minutes of work master thread stops working (doesn't write to stdout, doesn't save pages etc), then in about 12 minutes it become working again and then the same happens again and again. But slave threads work okay.

The same on 2 computers.

I've tried to do ```sudo renice -10 `pidof pgrep Master.js```, but it didn't help.

What could be the reason?

Thanks!

**Comment by gireeshpunathil** [comment]
@gunterdo - could you please provide a standalone test case that shows the issue?

**Comment by gunterdo** [comment]
The problem was with cheerio. I've deleted it, wrote regexp and the problem has disappeared :)
