### ISSUE TITLE
Cannot install node

### ISSUE THREAD

**Issue by hjvday73** [nodejs/help#2036]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

< I am trying to learn to code with Javascript and all tutorials recommend downloading node.js. I cannot do this at the moment though. The problem is at the end of the installation process. This is pasted from the window: 

This package has installed:
	•	Node.js v10.16.0 to /usr/local/bin/node
	•	npm v6.9.0 to /usr/local/bin/npm
Make sure that /usr/local/bin is in your $PATH.

I cannot find the application though.

**Comment by yathamravali** [comment]
@hjvday73 

Export the path of the node that you have installed. 
`bash`
`export PATH=<PATH OF INSTALLED NODE>:$PATH`

In your case it seems like `export PATH=/usr/local/bin:$PATH`

check installation: `node -v`

**Comment by hjvday73** [comment]
@yathamravali thank you for replying - I'm not sure what to do to apply your advice though. I've tried entering 'bash
export PATH=<PATH OF INSTALLED NODE>:$PATH' into my terminal but it just responds:

'bash: PATH: No such file or directory
bash-3.2$'

When I enter: 'export PATH=/usr/local/bin:$PATH'

it responds with nothing. and when I enter 'node -v', it just says: 'v10.16.0': i still can't access the application anywhere.

Thanks again

**Comment by yathamravali** [comment]
@hjvday73 
The problem description u specified is "can't install node" so I thought u are facing problem installation now that `node -v` says version it is installed successfully. 
What application is that u are not able to access. Can u describe it more briefly?.
 Thanks!!

**Comment by hjvday73** [comment]
@yathamravali 
Ah okay - my problem is that I don't have access to the node app; it is not in my finder (i run iOS). I can't open node anywhere in order to start learning to code.

**Comment by yathamravali** [comment]
@hjvday73 
Sorry I couldn't get ur point. Node app in the sense you need to write an application and run that application through the node that u have installed.
Sample Demo:
A sample program where server listens at port 8080 and prints the data.
`vi clientserver.js`
```
var http = require('http');
  
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/html'});
  res.end('Hello World!');
}).listen(8080);
```
Run the program using `node clientserver.js`[For using the node export the PATH as I illustrated in previous comment].

 In the browser do http://localhost:8080/

Thanks!!

**Comment by gireeshpunathil** [comment]
@hjvday73 - is this still outstanding?

**Comment by PoojaDurgad** [comment]
@hjvday73 ,were you able to follow @yathamravali 's suggestion ?or still an pending issue?

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing. feel free to reopen if still an issue
