### ISSUE TITLE
How to combine streams and not lose data

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2037]
I have this question on SO:

https://stackoverflow.com/questions/56945909/combine-fs-createreadstream-with-process-stdin-stream

Basically I am continually writing to a file to keep track of old data.
At some point, I want to read the data from the file and then start reading the new data from stdin. I don't want to duplicate data nor do I want to lose data.

Is there some reliable way to do this?

```js
process.stdin.resume().pipe(fs.createWriteStream('file'));

{
  // much later on

  const sws = new SomeWriteStream({end:false});

  fs.createReadStream('file').pipe(sws).once('end', () => {
    process.stdin.pipe(sws);
  });

}
```

**Comment by RaisinTen** [comment]
Is this still relevant?

* `once` should be `on`
* [`pipe`](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options) returns the `destination` and in this case you need the `readable`
* `end` [as an option for `fs.createReadStream`](https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options) is different from using it [as an option for `readable.pipe`](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options), in this case you need to pass it as an option for `readable.pipe`

Additionally, I added a slight delay of `5 seconds` to your code to signify when `sws` starts reading from `stdin`.
```js
const fs = require('fs');

process.stdin.resume().pipe(fs.createWriteStream('file'));

{
  // much later on

  setTimeout(() => {

    const sws = fs.createWriteStream('sws');
    const file = fs.createReadStream('file');

    file.pipe(sws, {end: false});

    file.on('end', () => {
      console.log('reading sws from stdin');
      process.stdin.pipe(sws);
    });
  }, 5000);

}
```
Here is the log of a demo run:
```zsh
❯ node index.js
1
2
3
reading sws from stdin
4
5
6
❯ cat file
1
2
3
4
5
6
❯ cat sws
1
2
3
4
5
6
```

**Comment by ORESoftware** [comment]
thx

**Comment by RaisinTen** [comment]
Feel free to close this if you are satisfied with the answer :)
