### ISSUE TITLE
Does `crypto` block the Node.js event loop?

### ISSUE THREAD

**Issue by lffg** [nodejs/help#2038]
* **Node.js Version**: 10.x
* **OS**: OS X
* **Scope (install, code, runtime, meta, other?)**: Runtime
* **Module (and version) (if relevant)**: `crypto`

I recently found out that the `crypto` Node.js module is *not* asynchronous.

In my application, I am validating a JWT token on every request, so should I worry about the fact that this module is synchronous? My biggest concern is that this module could block the event loop.

Thanks in advance. :)

**Comment by addaleax** [comment]
Most crypto work is synchronous, but there are a few exceptions (e.g. random bytes generation, key pair generation, PBKDF2/scrypt).

For a lot of operations, and in particular hashes, I would expect the overhead of moving tasks to a threadpool to outweigh the cost of a synchronous call.

There are some cases where this is a known issue though, see e.g. https://github.com/nodejs/node/issues/28404.

**Comment by gireeshpunathil** [comment]
ping @lffg - is there anything outstanding here, to be clarified?

**Comment by lffg** [comment]
No, thanks. Forgot to close. :)
