### ISSUE TITLE
All Node.JS updates reported as security updates

### ISSUE THREAD

**Issue by tadthies** [nodejs/help#2039]
* **Scope OTHER

All Node.JS updates are tagged as security updates even if there is no security fix noted in the release notes.  We Use Ivanti Security controls for patching.  i am trying to confirm if this security tagging is from Node.js or if Ivanti is adding the tag in their patch database.

We have some production systems that we only apply security patches to until teams can verify and test non security patches and updates.

**Comment by tniessen** [comment]
We do not tag all releases as security updates. If we consider releases to be "security releases", we usually announce that on https://nodejs.org/en/blog/.

**Comment by richardlau** [comment]
We also mark security releases in [`index.json`](https://nodejs.org/dist/index.json) and [`index.tab`](https://nodejs.org/dist/index.tab).

**Comment by gireeshpunathil** [comment]
closing as answered, pls re-open if there is anything outstanding
