### ISSUE TITLE
Websocket / event emitter issue??

### ISSUE THREAD

**Issue by jay-cordo** [nodejs/help#204]
Hi,

I'm relatively new to node and im struggling to find the answers!

I've created a very basic node script that is used to connect to a rs232 serial device, at the same time it serves as a websocket server so that clients can connect to it to get live output from the rs232 device but i keep getting event emitter max listeners errors after 11 clients have connected.

If any one can help me here or if i've gone about the code the wrong way give some advice it would be appreciated.

Thanks
Jamie
[serialport.txt](https://github.com/nodejs/help/files/331856/serialport.txt)

**Comment by lordKnighton** [comment]
Closing this issue, if you could still use help with it. Let us know. Sorry we couldn't get to this sooner.
