### ISSUE TITLE
Wrong timezone in node

### ISSUE THREAD

**Issue by yooouuri** [nodejs/help#2040]
* **Node.js Version**: v10.16.0
* **OS**: Mac OS 10.14.5 (18F203)
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

The timezone is set to "Europe/Amsterdam", but node gives me the wrong time...

```
$ date
Thu Jul 11 10:13:54 CEST 2019
$ sudo systemsetup -gettimezone
Time Zone: Europe/Amsterdam
$ node
> new Date
2019-07-11T08:14:12.389Z
```

**Comment by bnoordhuis** [comment]
Try `new Date().toString()`, otherwise the REPL prints it using `Date.prototype.toISOString()`.

**Comment by yooouuri** [comment]
@bnoordhuis so how can I create a new date object with the correct timzone?

**Comment by robert-gogolan** [comment]
@yooouuri we have the same problem, did you managed to solve this issue?
both browser and terminal show up the correct local time, but in node i get -1 hour.

**Comment by gireeshpunathil** [comment]
@yooouuri  / @robert-gogolan  - can you show your code that fails?

**Comment by yooouuri** [comment]
@gireeshpunathil 

```
    console.info(sheetBlock);
    console.info({
      type: sheetBlock.type,
      start: sheetBlock.start.toJSON(),
      end: sheetBlock.end.toJSON(),
      shift_id: sheetBlock.shiftId,
      sheet_id: sheetBlock.sheetId,
      sheet_block_id: sheetBlock.sheetBlockId,
    });
```

![image](https://user-images.githubusercontent.com/12934957/72440557-5b5c5580-37a9-11ea-9da8-4c9dc03f5f12.png)

![image](https://user-images.githubusercontent.com/12934957/72440584-6616ea80-37a9-11ea-9f4e-a786fb231a27.png)

**Comment by yooouuri** [comment]
@gireeshpunathil also...

![image](https://user-images.githubusercontent.com/12934957/72442555-091d3380-37ad-11ea-80c1-62d61ee13074.png)

**Comment by gireeshpunathil** [comment]
@yooouuri - 
 - by default Date object is constructed with GMT for the timezone
 - this is converted to your timezone if used `toString()`
 - this is not converted to the timezone if used `toJSON()`
 - looks like `console.info(sheetBlock)` is using `toString()` to print `sheetBlock`
 - when you are printing individual fields, `toJSON` is used for the date fields
 - difference between your timezone and GMT: https://24timezones.com/difference/cet/gmt

and hence the difference. I suggest you use only one form of formatting across the code. A best practice would be to store absolute values for computational purposes, use localized dates when interacting to the client programs.

does this help?

**Comment by PoojaDurgad** [comment]
@yooouuri - were you able to follow @gireeshpunathil 's suggestion? @robert-gogolan - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing. feel free to reopen if still an issue

**Comment by CyberCookie** [comment]
Still present

Node.js Version: v20.9.0
OS: Mac OS 14.2


**new Date** in Chrome and **date** command in terminal both show correct result
unline Node 's **new Date**


<img width="582" alt="Screenshot 2024-01-04 at 17 36 21" src="https://github.com/nodejs/help/assets/9907516/50a97b84-c104-4c2c-8833-0a30b9ecc885">


I've searched among stackOverflow questions and so far the only solution is to set **process.env.TZ**
