### ISSUE TITLE
jest: command not found

### ISSUE THREAD

**Issue by avvazana** [nodejs/help#2041]
* **Node.js Version**: 12.2.0
* **OS**: 10.13.6
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: jest

I'm trying to install jest, but I'm getting errors: 

sudo npm install -g jest 

-->
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@12.2.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/build'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/bin/node" "/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/bin/node /Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1011:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/bin/node" "/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents
node-pre-gyp ERR! node -v v12.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/bin/node /Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/me/.nvm/versions/node/v8.9.4/lib/node_modules/node/lib/node_modules/jest/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/jest/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ jest@24.8.0
added 479 packages from 342 contributors in 32.465s

**Comment by gireeshpunathil** [comment]
recreated easily with this:

#cat package.json 
```js
{
  "name": "foo",
  "version": "1.0.0",
  "scripts": {
    "postinstall": "node ./index.js"
  }
}
```
#cat index.js 
```js
console.log('hello')
```

#sudo npm install -g

```
> foo@1.0.0 postinstall /usr/local/lib/node_modules/foo
> node ./index.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:976
      const path = i >= 0 ? args[i] : process.cwd();
                                              ^

Error: EACCES: permission denied, uv_cwd
    at Object.resolve (path.js:976:47)
    at patchProcessObject (internal/bootstrap/pre_execution.js:73:28)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:10:3)
    at internal/main/run_main_module.js:7:1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foo@1.0.0 postinstall: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foo@1.0.0 postinstall script.
```

The reason is that the installation happens with admin user, while the postInstall step is carried out through login user, who has less privilege to access the installation location.

not aware of any prior art on this, and not able to think of a solution. Pinging @nodejs/npm for an opinion.

**Comment by gireeshpunathil** [comment]
@avvazana - can you pls try applying one of the workaround suggested in https://github.com/nodejs/help/issues/2013#issuecomment-514258686 and see if it works around your issue?

**Comment by gireeshpunathil** [comment]
reported to upstream npm: https://npm.community/t/inability-to-percolate-sudo-mode-to-postinstall/10809

**Comment by gireeshpunathil** [comment]
@avvazana - please add `--unsafe-perm` option as documented in https://docs.npmjs.com/misc/config#unsafe-perm . This is the recommendation we got from the npm community.

**Comment by gireeshpunathil** [comment]
closing as answered; pls re-open if the provided solution does not work
