### ISSUE TITLE
How to remove lines/bytes from a file "in-place"

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2044]
As a file grows in size (think of a log file) I want to remove the first 5 lines, or first 5000 bytes. From a web search it says I can use `sed -i` to remove lines in place. But I am looking for a Node.js library utility (like `fs.x()`) which can remove bytes from a file, not just read them. Is this possible somehow?

Note: I am definitely looking to avoid the traditional method of reading the whole file into memory splitting by lines, shifting off the first 5 and then overwriting the file with the new contents - this is not really performant and potentially loading up a big file in memory is no bueno.

**Comment by tniessen** [comment]
That is not a simple problem. I don't think that operating systems usually provide this feature, and I cannot think of an efficient way to implement this on most file systems. How should the disk "remove" a part of a file without having to rewrite everything? (You might be able to find an efficient solution for removing segments whose size is a multiple of the disk's block size, but that would likely require low-level disk operations.)

> Note: I am definitely looking to avoid the traditional method of reading the whole file into memory splitting by lines, shifting off the first 5 and then overwriting the file with the new contents - this is not really performant and potentially loading up a big file in memory is no bueno.

That does, indeed, sound terribly inefficient. But you can use a stream, ignore the first few lines and write everything else into a new file, and then move the new file to the path of the original file.

**Comment by gireeshpunathil** [comment]
or, if you are looking for a circular log buffer kind of implementation, may be you could use a native addon that manages the file content using `fseek` primitive?

**Comment by ORESoftware** [comment]
that could work

**Comment by gireeshpunathil** [comment]
ok, [fs.truncate](https://nodejs.org/dist/latest-v13.x/docs/api/fs.html#fs_fs_truncate_path_len_callback) exists, but it truncates from the trail end, not from the start.

that is a thin wrapper around [truncate2](http://man7.org/linux/man-pages/man2/ftruncate.2.html)

may be time for `fs.seek(path, seek, callback)` API?

alternatively we could overload `fs.truncate` with an option that tells from where to truncate?

`fs.truncate(path[, len], [{start: true}], callback)`

cc @nodejs/fs

**Comment by tniessen** [comment]
@gireeshpunathil How would we implement that without rewriting the entire file? `truncate` can only remove from the end of the file.

**Comment by gireeshpunathil** [comment]
@tniessen - let me clarify:

option 1: implement `fs.seek` and expose `fseek|lseek` syscall to the user - and let them deal with the complexity of writing at right places and moving around the file pointer.

option 2: (I guess this is where you had concern): provide an option to `fs.truncate` to truncate in the start, that internally uses `seek` primitives - saves programmer from the complexity.

**Comment by tniessen** [comment]
@gireeshpunathil Mhhh does truncate really consider the current offset in the file? So does it really discard parts before the current offset? That surprises me.

**Comment by gireeshpunathil** [comment]
@tniessen - current [fs.truncate](https://nodejs.org/dist/latest-v13.x/docs/api/fs.html#fs_fs_ftruncate_fd_len_callback) API does not; it is my proposal . If you are talking about the syscall `truncate`, I don't know how that is implemented, but what ever it is, those implementation details could be abstracted in the JS API.

**Comment by tniessen** [comment]
> If you are talking about the syscall `truncate`, I don't know how that is implemented, but what ever it is, those implementation details could be abstracted in the JS API.

Yes, I meant the syscall. As far as I know, it does not support truncating the beginning of the file, only the end.
