### ISSUE TITLE
How can i get value from i18n-express inside the routers

### ISSUE THREAD

**Issue by Coyas** [nodejs/help#2047]
I have this app using the i18n-express to translate it, inside the views i can get the language value with lang variable, but i cat get the value inside the routes, i want to get this value inside routes but i need a help to know how?

**Comment by gireeshpunathil** [comment]
@Coyas  - can you please explain your issue with an example code?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
