### ISSUE TITLE
These dependencies were not found (`fs` and `net`)

### ISSUE THREAD

**Issue by ashwinsoni** [nodejs/help#2048]
Getting `fs` and `net` missing dependencies error at runtime.  

* **Version**: v10.15.1
* **Platform**: Darwin Ashwins-MacBook-Air.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
* **Subsystem**:

## Issue Details:

I am trying to use below npm packages,
https://www.npmjs.com/package/geoip-lite

Below is the error encountered after installing geoip-lite,
```
These dependencies were not found:

* fs in ./node_modules/geoip-lite/lib/geoip.js, ./node_modules/geoip-lite/lib/fsWatcher.js
* net in ./node_modules/geoip-lite/lib/geoip.js

To install them, you can run: npm install --save fs net
```

One issue found in the same repo was ["missing dependency fs"](https://github.com/bluesmoon/node-geoip/issues/125). But turns out to be node's core `fs` module which is breaking. Please refer the [comment](https://github.com/bluesmoon/node-geoip/issues/125#issuecomment-288782233)

Then later I confirmed by,
1. Installing `fs` module separately in the repo although it comes inbuilt with node
2. Trying to install below two packages as well as,
	- https://www.npmjs.com/package/node-geocoder
	- https://www.npmjs.com/package/iplocation

Still getting ```These dependencies were not found``` issue.

My machine details:
OS: Mac OS Mojave v10.14.5
node: v10.15.1
yarn: v1.15.2

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help because it's very unlikely to be an issue with Node.js itself.

**Comment by ashwinsoni** [comment]
Just to add more thoughts here, I was trying to install and use the above-mentioned packages in my next.js application. Also found the exact closed issue in [next.js repo - Missing dependencies: fs, net and tls](https://github.com/zeit/next.js/issues/860)

So seems like **client/browser is trying to access fs, net and tls utilities which are more specific to server-side** which might be resulting in this issue.

**Comment by gireeshpunathil** [comment]
@ashwinsoni - you are right, several node.js APIs (including fs) are unavailable at the browser side.

I guess you will need to find out a module that fit your needs and that is not server-only.

I am closing this as self-answered; feel free it re-open if your issue is unresolved
