### ISSUE TITLE
return empty if call function from dll

### ISSUE THREAD

**Issue by ylyxf** [nodejs/help#205]
Version: v6.1.0
Platform:  Windows7,  32-bit
Subsystem: c++ add on 

I write a simple c++ add on to call a dll function (there are only dll file ,without source code or head code).
the struct is 

![qq 20160626173916](https://cloud.githubusercontent.com/assets/3871920/16361494/ee561658-3bc4-11e6-8a95-21469a8a0ce8.png)

I run `node-gyp configure build` , `node ..\..\test.js` in path `myapp\node_modules\explato` 

the problem is the function in dll is efficient ， but the addon's  return value can't return to the js.
![123](https://cloud.githubusercontent.com/assets/3871920/16361446/0589903a-3bc4-11e6-8409-1fd402e3d6cf.png)

when i don't call the function in dll , the result can return .
![com](https://cloud.githubusercontent.com/assets/3871920/16361450/1e1d49de-3bc4-11e6-940b-4e0017cce1be.png)

the code is 
![code](https://cloud.githubusercontent.com/assets/3871920/16361454/52e12b5e-3bc4-11e6-87d7-e89325d68703.png)

the test code is 
![test](https://cloud.githubusercontent.com/assets/3871920/16361460/8c48c992-3bc4-11e6-8feb-a65dfe2ebfde.png)

 how can a successful dll call can change the behaviour of args.GetReturnValue().Set(xxx) ?

all files is here 
[myapp.zip](https://github.com/nodejs/node/files/333509/myapp.zip)
[dlls.zip](https://github.com/nodejs/node/files/333516/dlls.zip)

**Comment by addaleax** [comment]
Are you asking how you can return the `result` string from the `decode` function? Or are you asking how to throw an error from it?

**Comment by ylyxf** [comment]
I'm very curious about how a inner call can change the export function 's return behaviour . <code>>DecryptPassword</code>  does not throw an exception ,because printf after  <code>>DecryptPassword</code> output the right result .
How can i debug the addon's return process ?

**Comment by bnoordhuis** [comment]
You turn the return value of the DLL-exported function into something that you can pass to `args.GetReturnValue().Set()`.

In your example, if `result` is an ASCII or UTF-8 string, you would pass it to `v8::String::NewFromUtf8()`.  If it is a binary blob, pass it to `v8::ArrayBuffer::New()`, `node::Buffer::New()` or `node::Buffer::Copy()`, etc.
