### ISSUE TITLE
How to create a dynamic-sized Buffer?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2051]
I am failing to see why Buffer exists. I have a couple questions:

1. How to initialize an empty Buffer? `Buffer.from('')`
2. But if the size is fixed, then an empty buffer is not very useful?
3. If we can dynamically add to a buffer, how to do so?  

The only way I have found is to create a new buffer:

```js
const b = Buffer.concat([a,b]);
```

If I need a dynamic-sized buffer, should I just use an Array?

**Comment by addaleax** [comment]
> I am failing to see why Buffer exists.

It really only does for historical reasons – it’s just a fany `Uint8Array`, basically. `Uint8Array`s aren’t resizable, though, either.

> If we can dynamically add to a buffer, how to do so?

Yeah, `Buffer.concat()` is about the closest thing you can get. A lot of the time, an Array of Buffers (or `Uint8Array`s) will do just fine – it really depends on your use case.

**Comment by ORESoftware** [comment]
Thanks, so if I want to convert an Array of int8 to a String, is this the fastest way?

```js
const dynamicUIntArray = [];
console.log(Buffer.from(dynamicUIntArray).toString())
```

on a related note, I am also looking for the fastest way to get the number of bytes in a string, the only way I know how to do that is:

```js
const bytes = Buffer.from(str).length;
```

is there a more performant way?

**Comment by addaleax** [comment]
> Thanks, so if I want to convert an Array of int8 to a String, is this the fastest way?

If you are dealing with an Array of raw JS numbers to begin with, yes, I would say so.

> I am also looking for the fastest way to get the number of bytes in a string, the only way I know how to do that is:

`Buffer.byteLength(str)` might be just what you’re looking for. :slightly_smiling_face:

**Comment by ORESoftware** [comment]
@addaleax thanks 

```js
Buffer.byteLength(str)
```

is good to know. I wonder if it's more permant than `Buffer.from(str).length` or just a wrapper.

**Comment by addaleax** [comment]
@oresoftware `Buffer.byteLength()` does not create an intermediate `Buffer` instance, so it does do less work if all you’re looking for is the length of a string in bytes (after encoding).

**Comment by ORESoftware** [comment]
thanks, yeah so if I have an Array of int8:

```js
const a = [10,12,33]
```

what is the fastest way to convert to a String? I suppose it's:

```js
Buffer.from(a).toString()?
```

thanks for your help

**Comment by addaleax** [comment]
@ORESoftware Yes, that’s what I would do.

**Comment by gireeshpunathil** [comment]
closing as answered
