### ISSUE TITLE
Create a Typescript array with all the  branch in my repo using  child_process

### ISSUE THREAD

**Issue by Philrobots** [nodejs/help#2052]
So I am trying to make a vscode extension with typescript  that will run a few git commands.

My problem : I need to make an array with all the branch that are show  when I write git branch. After reading the child_process documentation , I have though of this:

const cp = require('child_process');
let branchs = cp.execSync('git branch');

or 

const cp = require('child_process');
let branchs = cp.exec('git branch');

but it doesn't seem to work because my extension works when I use 

let branche = ['master', 'dev', 'production']; but it doesnt work when I try to create the array with child-process.

 Can someone helps me?

**Comment by ORESoftware** [comment]
For sure, this is the more versatile way:

```js

const cp = require('child_process');
const readline = require('readline');

const k = cp.spawn('bash');

k.stdin.end(`
   git branch -v
`);

const rl = readline.createInterface({
  input: k.stdout
});

k.stderr.pipe(process.stderr);

const branches = []

rl.on('line', l => {
  branches.push(l);
});

k.once('exit', code => {
  console.log('git command exiting with code:', code);
});

```

**Comment by Philrobots** [comment]
Thanks for the help, it is really appreciate but your way  doesnt seem to work, maybe I am the problem

**Comment by Philrobots** [comment]
> For sure, this is the more versatile way:
> 
> ```js
> const cp = require('child_process');
> const readline = require('readline');
> 
> const k = cp.spawn('bash');
> 
> k.stdin.end(`
>    git branch -v
> `);
> 
> const rl = readline.createInterface({
>   input: k.stdout
> });
> 
> k.stderr.pipe(process.stderr);
> 
> const branches = []
> 
> rl.on('line', l => {
>   branches.push(l);
> });
> 
> k.once('exit', code => {
>   console.log('git command exiting with code:', code);
> });
> ```
> 
> there may be some lines that arent branches, so you will have to filter and parse the branches array.
> 
> Or file an issue with git and tells those tards to support a --json flag, like everyone should.

**Comment by ORESoftware** [comment]
You're right, I tried my code, it's a problem with readline module, I guess. This works though:

```js
const cp = require('child_process');
const readline = require('readline');

const k = cp.spawn('bash');

k.stdin.end(`
   git branch -v
`);


const result = {
  stdout: ''
};


k.stdout.on('data', d => {
  result.stdout+=String(d);
});

k.stderr.pipe(process.stderr);


k.once('exit', code => {
  console.log('git command exiting with code:', code);
  console.log(result.stdout.split('\n'));  // git commands !! here
});

```

**Comment by Philrobots** [comment]
Interesting, as soon as I write the line 

"k.stdin.end(`
   git branch -v
`);"

My extension stop working but thanks for your time !
