### ISSUE TITLE
Output intensive spawned process doesn't exit when stdout is not consumed

### ISSUE THREAD

**Issue by tiagonapoli** [nodejs/help#2053]
* **Node.js Version**: v11.4.0
* **OS**: Ubuntu 19.04
* **Scope (install, code, runtime, meta, other?)**: ChildProcess and Streams

I have the following sample code that spawns an output intensive process and doesn't consumes `stdout`. When `stdout` is not consumed the process spawned doesn't exit. I think this is not a bug, but i'm trying to understand this behavior, if it's related to how Linux pipes processes, or how node does it. If anyone has links for me to read I would be glad :)
```js
const eos = require("end-of-stream");
const { spawn } = require("child_process");

const getStreamPromise = (stream, { readable, name }) => {
  return new Promise((resolve, reject) => {
    const cleanListeners = eos(stream, { readable }, err => {
      console.log(`${name} done`);
      cleanListeners();
      if (err) return reject(err);
      resolve();
    });
  });
};

const getSpawnedPromise = proc => {
  return new Promise((resolve, reject) => {
    proc.once("exit", () => {
      resolve();
    });

    proc.once("close", () => {
      resolve();
    });

    proc.once("error", error => {
      reject(error);
    });
  });
};

(async () => {
  // 1 GB output
  const size = 1000 * 1000 * 1000;
  const spawned = spawn("python", ["-c", `print("a" * ${size})`]);
  const procDone = getSpawnedPromise(spawned);

  // when each stream is done a message `${stream name} done` will be printed
  const stdoutPromise = getStreamPromise(spawned.stdout, { name: "stdout" });
  const stderrPromise = getStreamPromise(spawned.stderr, { name: "stderr" });

  // spawned.stdout.resume();
  await procDone;
  // this is never printed if spawned.stdout.resume is not called
  console.log("done process");

  await stdoutPromise;
  await stderrPromise;
  console.log("all done");
})();

```

**Comment by vsemozhetbyt** [comment]
Maybe this note from the [Child Process doc introduction](https://nodejs.org/api/child_process.html#child_process_child_process) is relevant?

> By default, pipes for `stdin`, `stdout`, and `stderr` are established between the parent Node.js process and the spawned child. These pipes have limited (and platform-specific) capacity. If the child process writes to stdout in excess of that limit without the output being captured, the child process will block waiting for the pipe buffer to accept more data. This is identical to the behavior of pipes in the shell. Use the `{ stdio: 'ignore' }` option if the output will not be consumed.

**Comment by tiagonapoli** [comment]
Thanks! I missed this part on the docs
