### ISSUE TITLE
NPM issues

### ISSUE THREAD

**Issue by ChepoZA** [nodejs/help#2054]
Hi, I came across the following error when trying to check npm version, I also cannot install Angular CLI as a subsequent error. 

'CALL "C:\node\\node.exe" "C:\node\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.

Please Help.
![2019-07-16](https://user-images.githubusercontent.com/52921525/61301576-6e836e00-a7e4-11e9-9fd3-ebd4cc85e8c9.png)

**Comment by bnoordhuis** [comment]
Moved to nodejs/help since it's not an issue with Node.js itself.

**Comment by gireeshpunathil** [comment]
@ChepoZA - is this still pending?

**Comment by PoojaDurgad** [comment]
@ChepoZA - is this still an issue ?
looks like  Same error as in #1019, #1981, #2054, #2266, explanation in  #1019 in the comment section somehow can resolve the problem.

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing
