### ISSUE TITLE
How to upgrade on Windows 10

### ISSUE THREAD

**Issue by likethegoddess** [nodejs/help#2055]
* **Node.js Version**: v10.15.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: upgrade
* **Module (and version) (if relevant)**:

How do I upgrade Node on Windows 10? I used your download to do the initial install. Do I run that again or is there command line instructions?

**Comment by Hakerh400** [comment]
Updating to newer version can be done by simply running the installer of that version. However, if you want to degrade to older version, you need to uninstall the new version first. There are also third-party command line programs that manage Node.js versions on Windows (like [Node Version Switcher](https://github.com/jasongin/nvs)).

**Comment by gireeshpunathil** [comment]
ping @likethegoddess

**Comment by PoojaDurgad** [comment]
@likethegoddess , were you able to follow @Hakerh400' s suggestion ?

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing
