### ISSUE TITLE
Promise(async(resolve, reject)=>{ throw new Error(); }) make me confused

### ISSUE THREAD

**Issue by weijiafu14** [nodejs/help#2059]
* **Version**:
* **Platform**:
* **Subsystem**:

As the title, 
new Promise(async (resolve, reject) => { throw new Error(); })
The promise will not be rejected. It is not consistent with sync function.
new Promise( (resolve, reject) => {throw new Error();})
The promise will be rejected in this case.
Could anybody could help me to explain why it is?
Thanks so much

**Comment by devsnek** [comment]
You can think of the promise constructor as calling your callback inside a try catch block, but it doesn't check if your callback returns a rejected promise.

**Comment by weijiafu14** [comment]
Thanks

**Comment by weijiafu14** [comment]
Thank you, I'm confused why it wasn't designed like this:

**Comment by weijiafu14** [comment]
Thanks very much
