### ISSUE TITLE
Error in running this command npm install -g composer-cli in Window 10

### ISSUE THREAD

**Issue by adeelnaqvi172** [nodejs/help#2060]
Hello,

Following error is getting generated while running "npm install -g composer-cli" - please clarify how to get this issue resolved: in window 10 and show me this error plz  help me
![1](https://user-images.githubusercontent.com/53054023/61473452-45c1bc80-a93b-11e9-8f3c-2e30fded6fc6.PNG)
![2](https://user-images.githubusercontent.com/53054023/61473459-48241680-a93b-11e9-8dcd-278c4379e880.PNG)

**Comment by adeelnaqvi172** [comment]
![1](https://user-images.githubusercontent.com/53054023/61521755-c7f6c300-a9c5-11e9-978f-e5362edc5dfa.PNG)
![2](https://user-images.githubusercontent.com/53054023/61521757-c9c08680-a9c5-11e9-8610-89fd8acad2b7.PNG)
![3](https://user-images.githubusercontent.com/53054023/61521770-d2b15800-a9c5-11e9-8cb4-07353d776fd0.PNG)
![4](https://user-images.githubusercontent.com/53054023/61521777-d80ea280-a9c5-11e9-8e67-dab9e9db64a9.PNG)
![5](https://user-images.githubusercontent.com/53054023/61521791-e066dd80-a9c5-11e9-8121-6fee628d2244.PNG)
![6](https://user-images.githubusercontent.com/53054023/61521799-e361ce00-a9c5-11e9-955c-a474b37e99c7.PNG)

**Comment by PoojaDurgad** [comment]
@adeelnaqvi172 , is this issue still outstanding?
