### ISSUE TITLE
Instalation Errors with Node JS

### ISSUE THREAD

**Issue by ChepoZA** [nodejs/help#2062]
* **Version**:v12.6.0
* **Platform**:Microsoft Windows Version 1903 (OS Build 18362.239)
* **Subsystem**:

Hi 

I have been installing NodeJS with errors. I have logged my installation and taken screenshots of all the errors. I have also altered the permissions of my C:\Users\Tshepo\AppData\Roaming\npm folder with no success. 

Please Help
![CMD Errors](https://user-images.githubusercontent.com/52921525/61385396-a0630600-a8b2-11e9-8115-bfc1521e92ae.png)
[Uploading InstallLog.txt…]()
![Uploading NodeJS_Erro-r1.png…]()
![Uploading NodeJS_Error-2.png…]()

**Comment by bnoordhuis** [comment]
Moved to nodejs/help as it's unlikely to be an issue with Node.js itself.

**Comment by gireeshpunathil** [comment]
ping @ChepoZA

**Comment by PoojaDurgad** [comment]
@ChepoZA , is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
