### ISSUE TITLE
Turn string into binary data

### ISSUE THREAD

**Issue by adamkarb** [nodejs/help#2063]
* **Node.js Version**: 8.x
* **OS**: linux
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**: Buffer

Should be a relatively simple code question, just not sure about the solution. My goal is to convert a stringified object into binary data which will then be saved in Redis. Currently my code looks like
```
const obj = {name: 'john', age: 99};
Buffer.from(JSON.stringify(obj)); // returns <Buffer 7b 22 73 69 74 65 49 64 22 3a 32 32....
```
but when this result is passed as a parameter to Redis to be saved, it is saving it as a json string. I have tried using `.toString('binary')` and have not gotten any traction by changing up the encoding. Before I dig into the source code of the redis library to see if it does any conversions, is it possible that I am using `Buffer` improperly? I definitely don't understand it completely after reading docs and other issues.

**Comment by bnoordhuis** [comment]
It indeed sounds like your redis client is changing the buffer back to a string. You're using `Buffer.from()` correctly, FWIW.

**Comment by gireeshpunathil** [comment]
ping @adamkarb

**Comment by PoojaDurgad** [comment]
@adamkarb , is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing
