### ISSUE TITLE
How to determine whether a file has been run directly inside ES module

### ISSUE THREAD

**Issue by sosoba** [nodejs/help#2065]
* **Node.js Version**:
12.6.0
* **OS**:
Windows
* **Scope (install, code, runtime, meta, other?)**:
runtime, documentation

Current documentation says: 

1. [Accessing the main module](https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_accessing_the_main_module):

> When a file is run directly from Node.js, require.main is set to its module. That means that it is possible to determine whether a file has been run directly by testing require.main === module.

2. [Differences Between ES Modules and CommonJS](https://nodejs.org/api/esm.html#esm_no_code_require_code_code_exports_code_code_module_exports_code_code_filename_code_code_dirname_code):

> These CommonJS variables are not available in ES modules.

The new challege is - how to determine whether a file has been run directly inside ES module?

**Comment by devsnek** [comment]
the concept of a main is mostly considered a mistake, so we haven't exposed such a thing to esm. It's generally considered best practice to have separate files for your bin and lib functionality.

**Comment by gireeshpunathil** [comment]
ping @sosoba

**Comment by PoojaDurgad** [comment]
@sosoba , were you able to follow @devsnek 's suggestion? or it is still an issue?

**Comment by sosoba** [comment]
Hi @PoojaDurgad.

Temporary I using:
```js
import url from 'url';

if (url.fileURLToPath(import.meta.url) === process.argv[1]) {
    // Loaded as main module
}
```
but finally community proposing `import.meta.main` which looking god.
Please merge with https://github.com/nodejs/modules/issues/274

**Comment by PoojaDurgad** [comment]
@sosoba , thanks for the information. as nodejs/modules#274 is still open and under discussion, let us wait to its resolution

**Comment by sosoba** [comment]
It works now! https://github.com/nodejs/node/pull/57804
