### ISSUE TITLE
Node.js Stalls and Runs Super Slow After Running

### ISSUE THREAD

**Issue by fishcharlie** [nodejs/help#2068]
* **Node.js Version**: v10.16.0
* **OS**: macOS 10.15 Beta (19A512f) - Darwin Charlies-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Jul 11 18:37:36 PDT 2019; root:xnu-6153.0.59.141.4~1/RELEASE_X86_64 x86_64
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: NA

Cloning [this repo](https://github.com/fishcharlie/tmp1) and running `node test.js` works fine for the first 288 reduce callback methods, then just stalls there for a while.

When looking at the process in activity monitor it is using just over 1gb of RAM, and roughly 90-95% CPU usage.

I know that the way I'm doing this is probably not the most efficient and can be cleaned up a lot, but why would it be doing 11 items per second, then stall after the 288th one? Is this a problem with Node.js?

```
[=--------------------------------------------------------------------------------------------------------------------------] 288 11/bps 27.4 0% 2751.1
```

**Comment by Hakerh400** [comment]
Simpler repro:

```js
const obj = Object.create(null);
const num = 2 ** 26;
const k = 2 ** 20 - 1;

console.time('');
for(let i = 0; i !== num; i++){
  obj[i] = 1;
  if((-~i & k) === 0){
    console.timeEnd('');
    console.time('');
  }
}
```

Output (added arrows to highlight relevant iterations):

```
: 34.349ms
: 43.867ms
: 40.156ms
: 11.048ms
: 52.661ms
: 10.966ms
: 71.339ms
: 10.997ms
: 11.427ms
: 97.829ms
: 11.159ms
: 11.245ms
: 11.370ms
: 11.424ms
: 137.083ms  <-----
: 11.024ms
: 11.371ms
: 11.601ms
: 11.177ms
: 11.262ms
: 11.632ms
: 198.986ms  <-----
: 11.274ms
: 11.147ms
: 11.391ms
: 11.286ms
: 10.976ms
: 11.321ms
: 11.564ms
: 10.977ms
: 11.425ms
: 292.905ms  <-----
: 11.221ms
: 11.386ms
: 11.416ms
: 11.032ms
: 11.368ms
: 12.002ms
: 11.150ms
: 11.200ms
: 11.577ms
: 11.221ms
: 11.127ms
: 11.371ms
: 13.603ms
: 12.595ms
: 13.245ms
: 791.598ms  <-----
: 11.045ms
: 11.177ms
: 13.080ms
: 11.405ms
: 11.043ms
: 11.261ms
: 11.562ms
: 10.954ms
: 11.465ms
: 11.501ms
: 11.273ms
: 11.247ms
: 11.489ms
: 11.262ms
: 11.234ms
: 11.480ms
```

It seems that on every `2 ** 23` (which is `8388608`) iterations some internal reallocation or data structure expansion happens inside V8 (Node's JavaScript engine).

In your example, the length of your `jsonA` is `29192` and your loop creates `29192 * (29192 + 1) / 2` properties on the `acc` object, which is total of `426101028` properties. It is about `2 ** 29`, which means you will experience `2 ** (29 - 23)`  (which is 64) slow iterations and other iterations will remain fast.

Maybe someone from V8 team can confirm this, or provide more datails...

**Comment by fishcharlie** [comment]
@Hakerh400 Thanks so much for your insight! Really appreciate it.

Should I submit this as an issue on the main Node.js repo? Or should I look into how to create an issue for V8?

**Comment by Hakerh400** [comment]
Why do you think it is an issue? I tried to explain why it happens, not to suggest that it may be considered as a bug. No matter how the internal implementation works, at some point a hash table (used for mapping keys represented as strings and/or symbols to property values) expansion must happen when too much collisions start to occur. Other JavaScript engines show very similar results. For example, the Gecko engine (Firefox's JavaScript engine) outputs the following:

<details>
<summary>Click to expand</summary>

```
: 19ms
: 14ms
: 16ms
: 25ms
: 28ms
: 29ms
: 37ms
: 39ms
: 47ms
: 5ms
: 55ms
: 6ms
: 60ms
: 6ms
: 66ms
: 6ms
: 84ms
: 8ms
: 5ms
: 98ms
: 4ms
: 7ms
: 108ms
: 7ms
: 6ms
: 132ms
: 7ms
: 5ms
: 130ms
: 6ms
: 5ms
: 153ms
: 7ms
: 6ms
: 10ms
: 175ms
: 6ms
: 183ms
: 6ms
: 5ms
: 6ms
: 5ms
: 220ms
: 7ms
: 6ms
: 7ms
: 288ms
: 6ms
: 7ms
: 6ms
: 7ms
: 6ms
```
</details>

**Comment by fishcharlie** [comment]
@Hakerh400 Got it. So now I just gotta think of a better way to achieve what I want then, since obviously the path I'm going down isn't gonna work.

**Comment by gireeshpunathil** [comment]
ping @fishcharlie

**Comment by fishcharlie** [comment]
@gireeshpunathil What is the purpose of pinging me here? Do you have something to add? Just pinging a thread with no information months after the last comment when there was nothing actionable isn’t helpful at all.

**Comment by gireeshpunathil** [comment]
@fishcharlie - apologies if it caused inconvenience to you. I am trying to cleanup dormant issues; so pinged to see if this is still outstanding, and anything actionable here. Is there any next level of details that we are looking for here? I can try to be of some help.

**Comment by fishcharlie** [comment]
Kinda let this project be for a while. Haven’t gotten a chance to come back and figure out a better solution. I mean I wish it wasn’t this slow. Seems like there should be some way to optimize this. But it’s also not the highest priority for me right now. It would be cool to have a better solution here tho, obviously there is some optimization that could be done either in Node or in my code. It’d be nice to have a solution so when I come back to this at some point I have more information, along with it being a good learning opportunity. But not high priority by any means.

Hopefully that answers your question.
