### ISSUE TITLE
How LibUv actually work?

### ISSUE THREAD

**Issue by viet-vo-360** [nodejs/help#2069]
Hi all,
It's my first time to work with NodeJS. I spent my whole week to understand what NodeJS actually does but there are still some concerns:
![image](https://user-images.githubusercontent.com/53222983/61714117-42d42b00-ad84-11e9-8a3a-3a5acf591f0b.png)

1. V8 engine in NodeJS is a different version to V8 on Chrome. Chrome's V8 supports methods that allow interacting to OS, disk... but LibUv is using to replace these methods because it is faster? In other words: NodeJS's V8 = Chrome's V8 optimized + NodeJS binding?

2. LibUv **only** serve I/O operations (asynchronous). If so, how's about synchronous function? 
For example with ReadFileSync. Does LibUv handle it through Event Loop and provide a thread for it? 

3. For my understand, some functions (console.log) can be served and done in NodeJS V8. Is it correct?

Please help for these questions. Thanks

**Comment by devsnek** [comment]
chrome's V8 doesn't provide any I/O, it's the same one we use.

libuv does both async and sync operations.

many things, including console, are provided by node itself, not v8

**Comment by gireeshpunathil** [comment]
ping @viet-vo-360 -

**Comment by PoojaDurgad** [comment]
@viet-vo-360 , looks like this can be closed now. let me know if that is not the case
