### ISSUE TITLE
npm audit fix: invalid reporting

### ISSUE THREAD

**Issue by comwt** [nodejs/help#2070]
* **Version**:  v10.16.0
* **Platform**:  MS Windows 64-bit  (Windows 10)
* **Subsystem**:

Hi Node Team,
I posted an issue like this about a year ago where npm audit indicates that a certain version of a file is needed to fix a security issue, but when you install to the requested version or later npm audit still complains about it.  Here is an example that is repeatable for me...

Steps to repeat:
    npm install --global express-generator
    express myTestApp
    cd myTestApp
    npm install
    npm outdated
    npm install --save debug@latest express@latest http-errors@latest
    npm audit
    npm install --save constantinople@latest uglify-js@latest clean-css@latest
    npm audit fix     <-- "fixed 0 of 4 vulnerabilities in 321 scanned packages" ... "require manual review"

OUTPUT:
-----------------------------------------------------------------------------------------
$ npm audit

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Critical        Sandbox Bypass Leading to Arbitrary Code Execution

  Package         constantinople

  Patched in      >=3.1.1

  Dependency of   jade

  Path            jade > constantinople

  More info       https://npmjs.com/advisories/568

  Low             Incorrect Handling of Non-Boolean Comparisons During
                  Minification

  Package         uglify-js

  Patched in      >= 2.4.24

  Dependency of   jade

  Path            jade > transformers > uglify-js

  More info       https://npmjs.com/advisories/39

  Low             Regular Expression Denial of Service

  Package         uglify-js

  Patched in      >=2.6.0

  Dependency of   jade

  Path            jade > transformers > uglify-js

  More info       https://npmjs.com/advisories/48

  Low             Regular Expression Denial of Service

  Package         clean-css

  Patched in      >=4.1.11

  Dependency of   jade

  Path            jade > clean-css

  More info       https://npmjs.com/advisories/785

found 4 vulnerabilities (3 low, 1 critical) in 200 scanned packages
  4 vulnerabilities require manual review. See the full report for details.

$ npm install --save constantinople@latest uglify-js@latest clean-css@latest pug@latest
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1

> core-js@2.6.9 postinstall C:\Users\vn509ck\dev\test\myTest\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ uglify-js@3.6.0
+ clean-css@4.2.1
+ constantinople@3.1.2
+ pug@2.0.4
added 48 packages from 120 contributors, updated 4 packages, moved 2 packages and audited 321 packages in 50.041s
found 4 vulnerabilities (3 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

$ npm audit fix
up to date in 6.127s
fixed 0 of 4 vulnerabilities in 321 scanned packages
  4 vulnerabilities required manual review and could not be updated

Hope this helps!
Thanks,
Justin Francis
justin.francis.4@gmail.com

**Comment by igoradamenko** [comment]
@comwt, it's a issue for https://npm.community/c/bugs, isn't it?

**Comment by gireeshpunathil** [comment]
agree, this should be reported to npm community

**Comment by KelseyMetter** [comment]
I keep getting this error too. I've been trying to fix it all day. I even uninstalled Node.js and re-installed.

**Comment by yldrmali** [comment]
This problem mainly stems from 'jade' dependecy package. 'jade' is renamed to 'pug' and deprecated. The solution below should fix the problem.
express  myTestApp --view=pug

**Comment by Zagoshipda** [comment]
also same issue... I should use pug instead...!
