### ISSUE TITLE
Send Post request with data to a remote api

### ISSUE THREAD

**Issue by animefn** [nodejs/help#2071]
* **Node.js Version**: v10.16.0
* **OS**: windows 10/debian 9
* **Scope**:code 
* **Module: axios**:

Hello, I'm trying to send a post  request to an api
In order to use the api I have to send a pass and an action, with ajax I use this code and it works fine:

```js
      $.ajax({
            url: 'https://example.com/api.php',
            method: 'post',
            data: {'pass': 'mypass', 'action': 'someaction'},
        }).done(function(results){
            //results = JSON.parse(results); //no need to parse it!
            console.log(results);

            });
        })
```

I'm trying to write a similar thing in node js, So I tried axios:
```js
axios.post('https://example.com/api.php', {
    'pass': 'passs',
    'action': 'someaction'
})
.then((res) => {
  console.log(`statusCode: ${res.status}`)
  console.log(res)
  console.log(`statusCode: ${res.data}`)
})
.catch((error) => {
  console.error(error)
})
```

I can't get it to work at all! res.status returns 200 and res.data returns nothing at all. The server logs the actions each user tries to execute via the api. In the log I see each of my connections as "connection with no pass nor action.

I would appreciate if someone can help me to get it to behave like the jquery code above?

Using axios is not a must, if there's a simpler solution with request or any other module it's fine I just need to send the data to the api.

Thanks in advance

**Comment by addaleax** [comment]
My first guess is that the difference between axios and jQuery which matters here is that jQuery defaults to using the application/x-www-form-urlencoded format for POST data, whereas axios defaults to JSON. (i.e. for jQuery the server receives `pass=mypass&action=someaction`, and for axios `{"pass":"passs","action":"someaction"}`).

Maybe https://www.npmjs.com/package/axios#using-applicationx-www-form-urlencoded-format is helpful for this? If you have control over the server, it might also be helpful to print out the POST data it receives for further debugging.

**Comment by animefn** [comment]
Can't thank you enough :) 
Your guess is exactly the piece of information that I needed to know. I managed to change axios to use  application/x-www-form-urlencoded format  for post data and it's working now!

Thanks a lot!
