### ISSUE TITLE
Error: getaddrinfo ENOTFOUND ff05::2:1001%br-client

### ISSUE THREAD

**Issue by anoymouserver** [nodejs/help#2073]
If I send to an udp6 dgram socket on the IPv6 multicast address `ff05::2:1001` (site-local) I get the following error. But sending to `ff02::2:1001` (link-local) works without any problems.
```
{ Error: getaddrinfo ENOTFOUND ff05::2:1001%br-client
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ff05::2:1001%br-client' }
```
Do you have any idea what causes the error and how it could be resolved?

Full source code: [hopglass-server/modules/receiver/announced.js#L80](https://github.com/hopglass/hopglass-server/blob/f0e2c0a58b8947176f7c87680c2bcb27f302f14c/modules/receiver/announced.js#L80)
Excerpt with the error output:
```js
  var collector = dgram.createSocket('udp6')
  // [...]
  var req = Buffer.from('GET ' + stat)
  collector.setMulticastInterface('ff05::2:1001%br-client')
  collector.send(req, 0, req.length, 1001, 'ff05::2:1001%br-client', function (err) {
    if (err) console.error(err)
  })
```
Relates to hopglass/hopglass-server#107

**Comment by bnoordhuis** [comment]
Node.js does not understand link-local addresses (the `%br-client` suffix), it treats them as a hostname to resolve over DNS.

More precisely: some functions (like `dgram.Socket#setMulticastInterface()`) understand them, but e.g. `dgram.Socket#send()` does not.

Teaching it to deal with link-local addresses may have security implications. Note for example that the WHATWG URL spec explicitly disallows them for security reasons.

**Comment by anoymouserver** [comment]
Thx, that's good to know.
But if I omit the interface on `send`, how can I be sure that it will still only be sent to that interface?

**Comment by bnoordhuis** [comment]
You can't right now.

**Comment by T-X** [comment]
> You can't right now.

@anoymouserver, @bnoordhuis: Actually, you can: You can set a more specific multicast route for the multicast group and interface you want to send it to. Usually this should work:

<pre><code>$ ip -6 route add ff05::2/128 dev bat0
$ ip -6 route add ff05::2/128 dev bat0 table local
</code></pre>

Also see: https://stackoverflow.com/a/13149495

But if hopglass could add a configuration option to bind the network socket to a specific interface that would be the better solution. As that would allow multiple instances on the same host, too. (which the multicast route option probably will not work with)
