### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by XIOLog** [nodejs/help#2076]
* **Node.js Version**: 10.16
* **OS**: Ubuntu 18.04
* **Scope (install, code, runtime, meta, other?)**: install

Hello. 
I do:

`sudo npm i -g gulp rimraf npm-check-updates bower`

and get an error:

`request to https://registry.npmjs.org/rimraf failed, reason: Client network socket disconnected before secure TLS connection was established`

I don`t understand what I must to do.
Please, help me.

P.S. Sorry for my bad English

**Comment by gireeshpunathil** [comment]
@XIOLog - is this still an issue?

**Comment by zy-zero** [comment]
@gireeshpunathil Yes, this issue will happen in Node version 12.15.0
not sure why. It not always happen.

**Comment by zy-zero** [comment]
@XIOLog 
Hi, did you resolve?
I get that error in node version 12.15.

**Comment by PoojaDurgad** [comment]
@XIOLog , is this issue resolved? if not , to me this issue looks similar to nodejs/node#21088 and partially it was fixed, hopefully you can resolve the issue by looking at the conversation.

**Comment by zy-zero** [comment]
@PoojaDurgad 
Hello, we are not resolve it. in https://github.com/nodejs/node/issues/21088 this issue link, we use axios, we use -tls-min-v1.0 to run app. both can't resolve the problem, and it is not always reproduce.

**Comment by XIOLog** [comment]
> @XIOLog , is this issue resolved? if not , to me this issue looks similar to [nodejs/node#21088](https://github.com/nodejs/node/issues/21088) and partially it was fixed, hopefully you can resolve the issue by looking at the conversation.

Hello. I returned to Windows. The problem has disappeared. Thanks :-)

**Comment by PoojaDurgad** [comment]
@zy-zero - ok. I don't have much deeper insight about axios , let me know you if I could spot a solution.

**Comment by gireeshpunathil** [comment]
closing as issue is resolved
