### ISSUE TITLE
npm ERR! Failed at the node-sass@4.12.0

### ISSUE THREAD

**Issue by rohithrajeev33** [nodejs/help#2077]
I am getting the below error while i am running a script. 

npm ERR! node-sass@4.12.0 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Node Version: v8.11.0
npm version: 6.10.2
Platform: rhel7

**Comment by Aarthy-Palanivelu** [comment]
Am facing the same issue right now. Not sure how to fix this.

**Comment by gireeshpunathil** [comment]
@rohithrajeev33 / @Aarthy-Palanivelu - is this still a problem? if so can you share the npm installer's debug log?

**Comment by Aarthy-Palanivelu** [comment]
No, The problem was fixed.

Thanks
Aarthy

**Comment by gireeshpunathil** [comment]
thanks @Aarthy-Palanivelu for the info. @rohithrajeev33 - how about you?

**Comment by PoojaDurgad** [comment]
@rohithrajeev33 , is this issue resolved?

**Comment by gireeshpunathil** [comment]
problem fixed, closing
