### ISSUE TITLE
global.require === module.require return false

### ISSUE THREAD

**Issue by wangning0** [nodejs/help#2078]
* **Node.js Version**: v8.9.3
* **OS**: macos
* **Scope (install, code, runtime, meta, other?)**: runtiom
* **Module (and version) (if relevant)**:

hello, everyone, I have a question want to know?
when i run the example code in repl, it get something make me confused，Can someone explain? Thx！

```
global.require === module.require // false
```

**Comment by bnoordhuis** [comment]
They're different functions. You can see it when you inspect them:
```
> module.require
[Function (anonymous)]

> global.require
[Function: require] {
  resolve: [Function: resolve] { paths: [Function: paths] },
  main: undefined,
  extensions: [Object: null prototype] {
    '.js': [Function (anonymous)],
    '.json': [Function (anonymous)],
    '.node': [Function (anonymous)],
    '.mjs': [Function (anonymous)]
  },
  cache: [Object: null prototype] {}
}
```

**Comment by gireeshpunathil** [comment]
closing as answered; pls re-open if there is anything outstanding
