### ISSUE TITLE
Can't use npm.

### ISSUE THREAD

**Issue by Ayzrian** [nodejs/help#2079]
* **Version**: v10.16.0
* **Platform**: Windows 10 Proffesional 64-bit
* **Subsystem**: None

I have an error when i type npm inside the comand prompt.
Сбой выполнения программы npm.cmd: Не удается найти указанный файлстрока:1 знак:1
+ npm
+ ~~~.
строка:1 знак:1
+ npm
+ ~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

Also i catch error when i open npm.bat inside the nodejs's folder

![npmError](https://user-images.githubusercontent.com/44115170/61993227-61cb0980-b071-11e9-85e7-433d1a6acb9b.JPG)

**Comment by bzoz** [comment]
Can you try reinstalling node?

**Comment by Ayzrian** [comment]
> Can you try reinstalling node?
Reintalled a few times. No result.

**Comment by Ayzrian** [comment]
> Can you try reinstalling node?

Reinstalled a few times. No result.

**Comment by gireeshpunathil** [comment]
can you try running npm from a command prompt, as opposed to from the explorer?

**Comment by PoojaDurgad** [comment]
@Ayzrian , is this issue resolved?

**Comment by Ayzrian** [comment]
@PoojaDurgad I think we can close this issues. 
I do not remember how, but npm works now. I believe that I reinstall the OS.

**Comment by AkromSaidxonov** [comment]
@Ayzrian can you tell how resolved this issue
