### ISSUE TITLE
(node:6040) [DEP0005] DeprecationWarning

### ISSUE THREAD

**Issue by mubaidr** [nodejs/help#2080]
* **Node.js Version**: 12.0.0 (running in electronjs enviroment)
* **OS**: Winodws 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: N/A

`buff.toString()` triggers deprecation warning: 
```bash
(node:6040) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

But I am just using existing buffer. What am I doing wrong here?

```ts
      worker.stdout.on('readable', () => {
        const buff: Buffer = worker.stdout && worker.stdout.read()
        if (!buff) return

        console.info(buff.toString()) // error here
      })
```

**Comment by addaleax** [comment]
Do you think you could share a full reproduction, and or run node with `--trace-warnings` to get a better idea of where that warning is coming from?

**Comment by mubaidr** [comment]
Sure please, more information: 

`devtools` point at the exactly this line: `console.info(buff.toString())`

This is the source file: https://github.com/mubaidr/image-parsing/blob/master/src/utilities/%40classes/WorkerManager.ts#L116
