### ISSUE TITLE
Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by TheNeoTV** [nodejs/help#2082]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bcrypt' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 1b00258fbf622ef8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for bcrypt@latest Cannot read property 'resolve' of undefined
8 timing stage:rollbackFailedOptional Completed in 5ms
9 timing stage:runTopLevelLifecycles Completed in 115ms
10 verbose stack TypeError: Cannot read property 'resolve' of undefined
10 verbose stack     at regFetch (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\index.js:76:23)
10 verbose stack     at fetchPackument (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:42:10)
10 verbose stack     at packument (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:20:10)
10 verbose stack     at getManifest (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:22:10)
10 verbose stack     at manifest (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:13:10)
10 verbose stack     at Object.manifest (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\index.js:17:12)
10 verbose stack     at Object.Fetcher#manifest [as manifest] (D:\Program Files\nodejs\node_modules\npm\node_modules\genfun\lib\genfun.js:15:38)
10 verbose stack     at manifest (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetch.js:23:18)
10 verbose stack     at pinflight (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\manifest.js:24:12)
10 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
10 verbose stack     at Promise._execute (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:313:9)
10 verbose stack     at Promise._resolveFromExecutor (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:483:18)
10 verbose stack     at new Promise (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
10 verbose stack     at _inflight (D:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
10 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
10 verbose stack     at tryCatcher (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose cwd C:\Users\Buttler\Desktop\opensourcerpragemp-master
12 verbose Windows_NT 10.0.18362
13 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
14 verbose node v10.16.0
15 verbose npm  v6.9.0
16 error Cannot read property 'resolve' of undefined
17 verbose exit [ 1, true ]

**Comment by addaleax** [comment]
I think this could require some more context.

But either way, since this looks like a problem with npm and not with Node.js, https://npm.community/ might be a better place to get help.
