### ISSUE TITLE
internal/modules/cjs/loader.js:628     throw err

### ISSUE THREAD

**Issue by Kukac113** [nodejs/help#2084]
* **Node.js Version**: 6.10.2
* **OS**:Windows
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I get this error and i was trying to find a solution but i haven't found anything.
Could someone please help me ?

```js
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'C:\Users\marti\OneDrive\Počítač\Music_bot'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}
```
-->

**Comment by addaleax** [comment]
What command are you trying to run? Are there `.js` files in the mentioned directory (`C:\Users\marti\OneDrive\Počítač\Music_bot`)?

**Comment by Kukac113** [comment]
Yes, I have .js file and this is the code https://pastebin.com/VnswEgLV

**Comment by Kukac113** [comment]
I want to create a music bot for discord. I have downloaded node-opus and ytdl-core windows-build-tools
Visual studio code build tools

Do I need to download any more modules?

**Comment by Navjeet220** [comment]
i also have the same problem ... any solution for this?

**Comment by jimmynames** [comment]
same, I have tried completely removing node and installing again to no avail

**Comment by mulife90** [comment]
same here ?

**Comment by junhwong** [comment]
https://github.com/nodejs/help/issues/2644#issuecomment-649075086

**Comment by marsonya** [comment]
Hi @Kukac113, @Navjeet220, @jamesryan-dev, @mulife90 

The problem in case of @Kukac113's issue is the use of special characters (`č`, `í`,  and `č`) in the path.
Remove/replace the characters and it should start working.

**Comment by marsonya** [comment]
I am closing this issue. Further discussion on this issue along with whether it's a bug is being discussed in #2644.
You can always reopen this issue if you are still facing the problem after removing the special characters from your path.
