### ISSUE TITLE
Node-opus install erorr

### ISSUE THREAD

**Issue by Kukac113** [nodejs/help#2085]
* **Node.js Version*12.7.0*:
* **OS*Windows 10*:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Could someone help me with this error?
Thank you for help in advance.

```gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\marti\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\marti\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\marti\Desktop\Music_bot\node_modules\ref
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
-->

**Comment by addaleax** [comment]
Do you think you could share more information here, e.g. the full npm debug log (as an attachment)?

**Comment by Kukac113** [comment]
[2019-08-03T23_40_15_263Z-debug.log](https://github.com/nodejs/help/files/3464424/2019-08-03T23_40_15_263Z-debug.log)

here is the npm debug log

**Comment by Choko256** [comment]
It seems the `ref ` module is not compatible with node 12+ which is used by `ref-struct` itself used by `ogg-packet`.

Here is the result of `npm ls` of one of my projects. It's not related to node itself I may think.

```
├─┬ node-opus@0.3.3
│ ├── bindings@1.2.1
│ ├── commander@2.20.0
│ ├── nan@2.14.0 deduped
│ └─┬ ogg-packet@1.0.1
│   └─┬ ref-struct@1.1.0
│     ├── debug@2.6.9 deduped
│     └── UNMET DEPENDENCY ref@1
```

**Comment by PoojaDurgad** [comment]
@Kukac113 , is this still an issue ? did @Choko256 's suggestion helped you to resolve the issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
