### ISSUE TITLE
Why doesn't this code hang forever?

### ISSUE THREAD

**Issue by zaynv** [nodejs/help#209]
I'm starting to get the hang of async code and promises with generators, but I'm a bit confused about this:

```javascript
let co = require('co')

co(function * () {
  yield new Promise(r => r)
})
```

I thought if I were to yield on a promise that never resolves, it would just hang. However, the process seems to exit immediately. What is the reason for this?

**Comment by addaleax** [comment]
Are you talking “hang” as in infinite loop or “hang” as in wait for Promise resolution? The latter won’t happen because there’s nothing that keeps the event loop alive, which also means that there’s nothing that could lead to resolving the promise.

**Comment by zaynv** [comment]
Kind of both? :p

I thought it would be stuck in a kind of "infinite loop" because it would be waiting for the resolution of the Promise. I thought yielding on the promise would be what kept the event loop alive.

**Comment by addaleax** [comment]
I don’t think there’s anything special about `yield`ing a value – `co` would wait for your original Promise to be resolved, but that’s nothing the event loop knows anything about.

I think the above code is pretty much equivalent to
```js
(function() {
    return new Promise(r => r);
})().then(…);
```

which will also exit immediately.

**Comment by zaynv** [comment]
hmm okay
