### ISSUE TITLE
BigInt ctor incorrectly parses some values

### ISSUE THREAD

**Issue by patixa** [nodejs/help#2090]
* **Version**:
v10.16.0
v12.7.0
* **Platform**:
Darwin Black-Mirror.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
* **Subsystem**:
`BigInt`

BigInt is inconsistent when parsing some unsafe numbers passed to the constructor:
```
> 995000000359499150
995000000359499100     // cast as number; expected
> 995000000359499150n
995000000359499150n    // OK
> BigInt(995000000359499138n)
995000000359499150n    // OK
> BigInt('995000000359499150')
995000000359499150n    // OK
> BigInt(995000000359499150)
995000000359499136n    // wut
```

Shockingly, this same problem affects Firefox!

**Comment by addaleax** [comment]
I think the reason for this lies in step 6 of https://tc39.es/ecma262/#sec-tostring-applied-to-the-number-type:

> If k ≤ n ≤ 21, return the string-concatenation of:
> * the code units of the k digits of the decimal representation of s (in order, with no leading zeroes)
> * n - k occurrences of the code unit 0x0030 (DIGIT ZERO)

That is, for sufficiently large values, using `.toString()` on a plain JS number will not return the string corresponding to the closest mathematical value of the underlying bit pattern, but instead will append zeroes at the end of the number. I agree in finding this surprising but it’s what the spec says and likely won’t change.

**Comment by patixa** [comment]
In rereading the [BigInt spec](https://tc39.es/proposal-bigint/#sec-bigint-constructor-number-value), I see I drew the wrong conclusion by thinking `ToBigInt(value)` would be called instead of `NumberToBigInt(value)`. It is certainly reasonable that the constructor argument would be converted to Number before being passed to the constructor implementation. I inaccurately assumed the interpreter would pass the argument unmodified for parsing, not type it first.
