### ISSUE TITLE
Sync utility in node.js to check if a server is listening on unix domain socket

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2091]
I am on node.js version 12..I have this question on unix.stackexchange.com:

https://unix.stackexchange.com/questions/533258/producer-connect-to-consumer-with-unix-domain-sockets

Basically I am wondering if there is some sync utility to check if the server has started listening yet.
I have this code right now:

```js
const udsFile = path.resolve(process.env.HOME + '/uds-1.sock');

setTimeout(() => {
  
  const conn = net.createConnection(udsFile);
  
  conn.once('connect', () => {
    console.log('connected');
  });
  
  conn.pipe(new JSONParser()).on('data', (d: any) => {
    
    if (d.bunionType && d.bunionType === 'read') {
      return read(d.value);
    }
    
  });
  
}, 400);
```

but I would like to get the declaration of the connection out of the callback, make it synchronous.
One improvement to the Node.js API (it might exist) would be something like this:

```js
  const conn = net.createConnection(null);  // declare variable synchronously

 setTimeout(()=> {
   conn.connect(udsFile); // ... but make the connection asynchronously
 }, 400);
  
  conn.once('connect', () => {
    console.log('connected');
  });
  
  conn.pipe(new JSONParser()).on('data', (d: any) => {
     // ...
  });
```

**Comment by igoradamenko** [comment]
`net.createConnection` creates a new `net.Socket` and instantly invokes `socket.connect()`:

https://nodejs.org/docs/latest-v10.x/api/net.html#net_net_createconnection

So if you want to make something that you're describing, you should do it like this:

```js
const socket = new net.Socket();  // create a socket instead of conneciton

setTimeout(()=> {
   socket.connect(udsFile); // and then connect
}, 400);
  
socket.once('connect', () => {
    console.log('connected');
});
  
socket.pipe(new JSONParser()).on('data', (d: any) => {
     // ...
});
```

Not sure that it would work, but looks a bit better than your example.

**Comment by ORESoftware** [comment]
yes thats much better, thank you
