### ISSUE TITLE
What is state of h2c (unencrypted http2.0) in nodejs?

### ISSUE THREAD

**Issue by IdeaHunter** [nodejs/help#2095]
* **Node.js Version**: 12+
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: n/a

The documentation [https://nodejs.org/api/http2.html](https://nodejs.org/api/http2.html#http2_http2_createserver_options_onrequesthandler) mentions its possible to create start unencrypted http2 server, but how much standard complaint/complete it is?

**Comment by addaleax** [comment]
I’m not sure if that’s what you’re asking, but it’s the same as the encrypted version – Node doesn’t make much of a difference between those two. The thing you’d want to be aware about is that browsers won’t support it.

**Comment by IdeaHunter** [comment]
>but it’s the same as the encrypted version 
you mean same feature-wise?
>The thing you’d want to be aware about is that browsers won’t support it.
This is what made me ask this question because if browsers doesnt support it NodeJs foundation may slack on some features too 😇
