### ISSUE TITLE
Avoid logging symbols using util.inspect

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2096]
I am on Node.js v12, I am using:

```js
util.inspect(v, {showHidden: false})
```

but it's still logging symbol properties:

```console
{
  foo: 'bar',
  [Symbol(raw.json.bytes)]: 13,
  [Symbol(raw.json.str)]: '{"foo":"bar"}'
} 

```

I am just adding symbols using:

```js
v[Symbol('x')] = 'foo'
```

for debugging I want to be able to log the symbols on occasion, but with util.inspect(),  I want to be able to avoid displaying the symbol props, anybody know how?

**Comment by devsnek** [comment]
define them as non-enumerable

**Comment by ORESoftware** [comment]
Yeah I was under the impression that Symbol props were non-enumerable by default, but I guess not
