### ISSUE TITLE
fs.watch should accept file descriptor

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2097]
Given a file descriptor, I am not sure how to discover the path of the file, maybe there is a way to do that. But according to the docs and the TS typings, the fs.watch API cannot accept a file descriptor as an argument.

I am looking for something like:

```js
const fd = fs.openSync(file, 'r');

fs.watch(fd, (ev,pth) => {
  createTimeout();
});
```

or perhaps as an option:

```js
fs.watch({fd}, (ev,pth) => {
  createTimeout();
});

```

here are the docs on the subject:
https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener

**Comment by addaleax** [comment]
Transferred the issue as this isn’t going to happen but there’s follow-up questions.

One thing you can do at least on Linux is to use `readlink` on `/dev/fd/${fd}` or `/proc/self/fd/${fd}`. It may not always give you helpful results, in particular, if the file is not a regular file, has multiple paths, or a containing directory has been deleted. But as Ben said, this isn’t portable.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
