### ISSUE TITLE
async-hello-world can be a more universal example??

### ISSUE THREAD

**Issue by classfellow** [nodejs/help#210]
I read the example async-hello-world
```c++
void Method(const v8::FunctionCallbackInfo<v8::Value>& args) {
  v8::Isolate* isolate = args.GetIsolate();
  v8::HandleScope scope(isolate);

  async_req* req = new async_req;
  req->req.data = req;

  req->input = args[0]->IntegerValue();
  req->output = 0;
  req->isolate = isolate;

  v8::Local<v8::Function> callback = v8::Local<v8::Function>::Cast(args[1]);
  req->callback.Reset(isolate, callback);

  uv_queue_work(uv_default_loop(),
                &req->req,
                DoAsync,
                (uv_after_work_cb)AfterAsync);
}
```
If codes above not run in main, error occurs. Suppose that other threads want the main thread's working queue to do something, then AfterAsync runs in main.Because js context is in main. You know my meaning, Ok ? The above example is not universal. Can you give a example that meet the demand.

My codes like --:
```c++
void RcibHelper::PrintLogs(const std::string & info, async_req * req){
if (fp_){
std::string content = info + "\n";
fputs(content.c_str(), fp_);
}
//TODO use direct way
uv_queue_work(uv_default_loop(),
&req->req,
DoNopAsync,
(uv_after_work_cb)AfterAsync);
}
```
PrintLogs runs in a new thread that created when my c++ module required. But uv_queue_work actually only can be invoked on the main thread.

Is there a way to do same thing safely?

**Comment by addaleax** [comment]
Did you take a look at http://docs.libuv.org/en/v1.x/async.html?

**Comment by classfellow** [comment]
To give example , ：） is more better

**Comment by bnoordhuis** [comment]
Yeah, we're not going to do your homework for you.

I'm closing this issue.  If you keep filing issues without putting in some effort, I'll give you a temp ban.  You've been significantly lowering the signal-to-noise ratio in my inbox this morning.
