### ISSUE TITLE
nohup server kills automatically with no errors

### ISSUE THREAD

**Issue by jankhunter** [nodejs/help#2101]
* **Version**: v8.12.0
* **Platform**: Linux
* **Subsystem**: nohup server

I run a node app (express app) with nohup server.

**Command i run to start the server** :  `nohup npm server &`

**Message i get after running the above command** : `appending output to nohup.out`

**What should happen?**
      Server should stop when a error is with the app i run and the same error should be thrown in nohup.out also

**What actually is happening?**
     Server is getting killed with no error thrown in nohup.out. This is happening very **randomly** and also the main point is Not only for one app this is happening, but for all node servers we are running.

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help because I see no indication that it's a bug with Node.js itself. Can move back if that turns out to be mistaken.

**Comment by ORESoftware** [comment]
try

```
nohup echo && node app.js
```

just to see what happens

**Comment by jankhunter** [comment]
Tried the above command and the app not even starts 😞

**Comment by jankhunter** [comment]
Could anyone help for this? 😞

**Comment by gireeshpunathil** [comment]
@jankhunter - is this still outstanding? I followed your suggestions on a simple express app, but unable to reproduce the issue. Can you please post your code and the steps you used?

**Comment by PoojaDurgad** [comment]
@jankhunter - is this still an issue ?

**Comment by PoojaDurgad** [comment]
inactive . closing!!!
