### ISSUE TITLE
vnode.exe keeps popping up on my screen

### ISSUE THREAD

**Issue by princewillopah** [nodejs/help#2103]
i am quite new on nodejs. i installed the version 10.16.1 LTS. i installed yarn. i used the yarn to install node-sass and create-react-app.
Having installed these, i worked with the node-sass and it was good. my problems started when i enter the command "yarn start" for react app. there is this **vnode.exe console that pops up whenever i run any of the npm or yarn commands** and when it pops up, it terminates the original cmd or gitbash i used. even when i completely closed it from the task manager's processes. it stills pop of overtime. 
i uninstalled the node v10+ and installed version 12. 7. it worked well for sass, but when i switched to react, i started seeing the same console popup.
pls what should i do

![node issues pic](https://user-images.githubusercontent.com/25676343/62432818-90a84600-b729-11e9-8fc6-9053521eddee.JPG)

**Comment by bnoordhuis** [comment]
Moving to nodejs/help because this is almost guaranteed not to be an issue with Node.js itself. For starters, we don't distribute a vnode.exe.

**Comment by princewillopah** [comment]
i just realize it was due to a virus attack. mine was this paint.exe virus attacking node.exe and some other app, adding "v" in front of the app eg vnode.exe.

**Comment by Milan-Popich** [comment]
//Master Builder 
##Unstoppable Greatness##
‘’’https://api.travis-ci.org/atom/superstring.svg?branch=master’’’

**Comment by Milan-Popich** [comment]
https://api.coinmarketcap.com/v1/ticker/bitcoin/?convert=EUR

**Comment by king517** [comment]
> i just realize it was due to a virus attack. mine was this paint.exe virus attacking node.exe and some other app, adding "v" in front of the app eg vnode.exe.

how did you solve this finally please?

**Comment by lekarane** [comment]
I have same problem, how to fix please

**Comment by noruwa03** [comment]
I have same problem too, how to fix please
