### ISSUE TITLE
How to serve a pre generated brotli js file?

### ISSUE THREAD

**Issue by Livog** [nodejs/help#2107]
* **Node.js Version**: 12.7
* **OS**: Mac OS 10.14.6
* **Scope (install, code, runtime, meta, other?)**: Express@^4.16.1
* **Module (and version) (if relevant)**: brotli@1.3.2

So I have successfully pre-generated a javascript file but I m unable to serve the already compressed file? This should be the fastest way to serve my file since there is no generating needed. The best that I get is just random characters in the browser.

```js
//How I generate the file.
let compressedContent = brotli.compress('test', {
  extension: 'br',
  mode: 1,
  quality: 11,
  lgwin: 12
});
fs.writeFileSync(`generateUniqCodeForThisVersion.js.br`, compressedContent, 'utf8');

//How I m trying to serve the file
if (fs.existsSync(`generateUniqCodeForThisVersion.js.br`)) {
  res.set({
    'content-type': 'text/javascript; charset=utf-8',
    'Content-Encoding': 'br'
  })
  return res.sendFile(`generateUniqCodeForThisVersion.js.br`).end()
}
```

If I understood what the browser is expecting maybe I would have solved it by now, but hopefully someone can give me a working example. 

Any help is super appreciated.

**Comment by tniessen** [comment]
Have you checked the request/response headers in your browser? Does your browser accept brotli according to the request headers?

**Comment by gireeshpunathil** [comment]
ping @Livog - is this still pending?

**Comment by PoojaDurgad** [comment]
@Livog , is this still an issue?
