### ISSUE TITLE
Downstream error handling with streams

### ISSUE THREAD

**Issue by fbiville** [nodejs/help#2108]
* **Node.js Version**: v12.8.0
* **OS**: Mac OS Mojave (10.14.6)
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: `stream`

First, a big BIG thank you for this repository! It's a wonderful idea! 🙏

I am trying to understand how errors and `Transform#_transform`'s `callback` parameter interact.

The setup is like this (all streams are object streams):
```
(Transform stream "input")
   .pipe(Transform stream "function")
   .pipe(Transform stream "output")
   .pipe(PassThrough stream "destination")
```

The `function` Transform is implemented as follows:

```js
class SimpleTransform extends Transform {
    constructor(options, fn) {
        super(options);
        this.fn = fn;
    }

    _transform(chunk, _, callback) {
        callback(null, this.fn(chunk));
    }
}
```

The test I am running makes the `function` stream produce something that the `output` stream rejects, i.e. the `output` streams does something like: 
```js
_transform(chunk, _, callback) {
    try {
        callback(null, doSomeConversionThatMayFail(chunk));
    } catch (err) {
        callback(new MyCustomError('error-output-invalid', err));
    }
}
```
where `MyCustomError` subclasses the standard `Error` class.

What happens in practice is that this `MyCustomError` will somehow bubble back to the `input` stream. If there is no `catch` in `input#_transform` around its `callback` call, then there the error remains uncaught and the program crashes.
I have added a small running sample (with instructions) based on the above example: https://github.com/fbiville/nodejs_help_issue2108.

The thing I don't understand is: why do I need to catch the error in the `input#_transform` implementation and not in the `function#_transform`?

More generally, what is the relation between downstream errors and the `callback` argument whose "instance" seems to be shared amongst all streams in the pipeline?

**Comment by fbiville** [comment]
I have added a small running and sample (with instructions) based on the above example, I hope it helps: https://github.com/fbiville/nodejs_help_issue2108.

**Comment by gireeshpunathil** [comment]
pinging @nodejs/streams to see if they can help

**Comment by mcollina** [comment]
I'm not exactly sure what is the question. Can you paste a single-file example that I can easily run?

The short answer (from what I can gather from the text) is:

None of the stream API add a try-catch for you. These are "old school" APIs that assume that any uncatched throw results in an `uncaughtException` and therefore a crash.

**Comment by ORESoftware** [comment]
don't do this:

```js
_transform(chunk, _, callback) {
    try {
        callback(null, doSomeConversionThatMayFail(chunk));
    } catch (err) {
        callback(new MyCustomError('error-output-invalid', err));
    }
}

```

that's a no-no, instead do this:

```js
_transform(chunk, _, callback) {

  let val = null;

    try {
     val = doSomeConversionThatMayFail(chunk);
    } catch (e) {
      return cb(e);
    }

   cb(null, val);   
}

```

otherwise you are running the callback in the try/catch, but you only want to run the doSomeConversionThatMayFail in the try/catch.

**Comment by fbiville** [comment]
Ah I see, in the first version, I would end up catching errors thrown from the callback in the try clause and end up calling callback a second time, which is prohibited.
