### ISSUE TITLE
Cannot locate npm executable after installation NodeJS 6.2.2

### ISSUE THREAD

**Issue by conradwt** [nodejs/help#211]
I recently installed `nodejs6 @6.2.2_0` via MacPorts.  The `node` executable exists.  However, I cannot locate `npm` and the documentation indicate that `npm` is now bundled with `node` releases.  Does anyone have ideas as to what's happening here?

**Comment by SomeoneWeird** [comment]
Does macports ship npm as a separate thing?

**Comment by conradwt** [comment]
@SomeoneWeird They did previously but I'm not sure of the protocol regarding NodeJS 6.2.2.  I ended up uninstalling the `nodejs6` port all together and downloading/installing the macOS package from nodejs.org.  Thus, I'll close this issue for now.

**Comment by conradwt** [comment]
@SomeoneWeird I also sent a message to MacPorts maintainer regarding the port and I'll update this ticket when that information becomes available.
