### ISSUE TITLE
npm-cli.js not recognizing node

### ISSUE THREAD

**Issue by arun-vijayakumar** [nodejs/help#2114]
* **Node.js Version**: 10.16.2
* **OS**: RedHat Linux 7.6
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: npm
I have followed the instructions for installing node binary. The installation has created symbolic link to npm-cli.js.
 npm -> ../lib/node_modules/npm/bin/npm-cli.js

However when I execute npm-v I get error --> Error: Cannot find module '/home/userapp/node'
node is already added to the path.
As a workaround, I have pasted the node binary to the directory from where I execute npm -v.
Now I get a different error.
 /usr/local/lib/nodejs/node-v10.16.2-linux-x64/bin/node:1
ELF
^

SyntaxError: Invalid or unexpected token

It looks like for some reason npm-cli.js is not able to recognize npm.

Can you please help.
Thanks

**Comment by HarshithaKP** [comment]
@arun-vijayakumar Looks like your node installation is corrupted. 
Is this issue still exists for you ?, If yes I would recommend to re-install node.

**Comment by gireeshpunathil** [comment]
inactive, closing; pls re-open if this is still outstanding
