### ISSUE TITLE
Node.js listen on *pre-existing* unix domain socket file

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2115]
I am on Node.js version 8-12.. I want to be able to start a server listening on a Unix Domain Socket, where that file already exists, something like this:

```bash
#!/usr/bin/env bash
export socket_file_path='unix-domain-socket.sock'
netcat make "$socket_file_path"  # whatever utility can make a unix domain socket file
node client.js | node server.js
```

and where the server listens on that existing socket file, instead of creating a new file in the server. Is there a way to do this? My socket code is like so:

```js
const net  = require('net');

const server = net.createServer(c => {
    // ...
});

const fp = process.env.socket_file_path;

server.listen(fp, () => {  // this always seems to attempt to create the file
  consumer.debug('Listening on unix domain socket:', udsFile);
});
```

**Comment by bnoordhuis** [comment]
You can't really do that. Not because Node.js won't let you but because UNIX sockets are a bit magic. For starters, you can't open them like a regular file, it'll fail with `ENXIO`.

Something clever like trying to bind to `/proc/$(pidof netcat)/fd/<num>` won't work either, it'll fail with `EADDRINUSE` (because the file path already exists, not because it's an already bound socket.)

**Comment by ORESoftware** [comment]
thanks Ben thats what i figured, yeah i am launching two node processes with bash in  a pipeline and right now there is no easy way to know when the client can connect to the server. 

```
export create_unix_domain_sock="here somehow?"
node client.js |  node server.js
```

is there some way with bash to create a .sock that can be used by the sibling procs in the pipeline?

**Comment by bnoordhuis** [comment]
netcat is a pretty simple tool but I bet socat can do it.

**Comment by gireeshpunathil** [comment]
Closing as answered, pls re-open if anything pending to be discussed / clarified.
