### ISSUE TITLE
Confirming my understanding of the nodejs Event Loop

### ISSUE THREAD

**Issue by AyushG3112** [nodejs/help#2117]
I have created a (very) rudimentary implementation of the nodejs Event Loop using nodejs Event Emitter, and I am looking for inputs whether I have missed something. Comments and suggestions appreciated:

``` javascript
const eventEmitter = new (require("events"))();

let events = [
  "poll",
  "check",
  "close-callbacks",
  "timers",
  "pending-callbacks",
  "idle-prepare",
];

eventEmitter.once("poll", () => {
  console.log("in poll");
  eventEmitter.once("nextTick", () => console.log("nextTick 1"));
});

eventEmitter.once("nextTick", () => {
  console.log("nextTick 2");
  eventEmitter.once("check", () => console.log("check 1"));
  eventEmitter.once("nextTick", () => console.log("nextTick 3"));
  eventEmitter.once("timers", () => console.log("timers 1"));
  eventEmitter.once("poll", () => console.log("poll 2"));
});

while (true) {
  for (let event of events) {
    eventEmitter.emit(event);
    eventEmitter.emit('nextTick');
  }
  const totalLength = events.reduce((sum, item) => {
    return sum + eventEmitter.listenerCount(item);
  }, 0);
  console.log(totalLength);
  if (totalLength === 0) {
    return;
  }
}
```

**Comment by addaleax** [comment]
I’m not quite sure about this analogy, but one things that should be pointed out (and that confuses a lot of people) is that, despite its unfortunate naming, `process.nextTick()` is *not* integrated into the event loop, and does not delay functions until the next event loop turn; instead, the callbacks run after each callback, before control is given back to C++ code/to the event loop.

**Comment by AyushG3112** [comment]
@addaleax I'm not completely able to understand what you mean. Just to clarify, do you mean that `NextTickQueue` is processed implicitly after each event loop phase instead of the event loop explicitly initiating its processing?
