### ISSUE TITLE
how to create node API with await ?

### ISSUE THREAD

**Issue by tamuchevaibhav** [nodejs/help#2120]
var express = require('express');
const mongoose = require('mongoose');
const bodyParser = require('body-parser');

var app = express()
port = process.env.PORT || 3000;

const connectionString = 'mongodb+srv://vaibhav_1995:XXXXXXXXXXXXXXXXXXXXXXXXXXXX'

const userS = require('./model/userSchema.js')
userSchema = mongoose.model('User', userS);

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
console.log(app)
var routes = require('./routes/adduserinmongo');

(async () => {
      let user = await mongoose.connect(connectionString)
      routes(app)
})()

app.listen(port);
app.listen(port);

**Comment by AlexWehe** [comment]
```
(async () => {
let user = await mongoose.connect(connectionString)
routes(app)
console.log('coonect database')
})()

app.listen(port);
```

**Comment by tamuchevaibhav** [comment]
ya it's looks good, Thanks

**Comment by gireeshpunathil** [comment]
closing as answered; pls re-open if anything outstanding here
