### ISSUE TITLE
Last argument for loop to accept return function 

### ISSUE THREAD

**Issue by tonystaark** [nodejs/help#2121]
function check(arr,index){
      return arr[index] ? 1 : 0;
    }

    const test = function (arr) {
      for (let i = 0; i<arr.length; i+=check(arr, i)){
        if (arr[i] === 0) {
         doSomething
        } else {
          doAnother
       }
     }

    test()

Possible to enable the last argument of for loop to accept the increment result from a function, as illustrated above? If there is no implementation, I would like to contribute, but need some guidance.

**Comment by tonystaark** [comment]
Oh thanks :)

**Comment by gireeshpunathil** [comment]
closing as answered; pls re-open if anything outstanding here
