### ISSUE TITLE
Node failed to install

### ISSUE THREAD

**Issue by JaybeeClassical** [nodejs/help#2122]
* **Node.js Version**:v12.8.1- 64bit
* **OS**:windows 10

So, i just downloaded the lastet version of node v12.8.1 and tried installing it on my windows 10 after deleting the node version 10. On the installation process it popped up and error message saying **"The installer has insufficient privileges to access this directory: C:/Program Files/node.js. The installation cannot continue. Log on as administrator or contact System Administrator"**

I need help please

**Comment by ExillustX** [comment]
Right-click on the file and run it as administrator.

**Comment by JaybeeClassical** [comment]
Okay, i just have to reboot my system and reboot it then ran the .msi file again and automatically it started with administrator access(showing the administrator icon) then everything worked
