### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by Jones-Thomas** [nodejs/help#2124]
* **Node-Version**: v10.16.0
* **Npm-Version**: 6.9.0
* **Platform**: Linux lxes5dta01 3.10.0-957.21.3.el7.x86_64 nodejs/node#1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: JavaScript heap out of memory

![image](https://user-images.githubusercontent.com/42827211/63195806-a3801c00-c041-11e9-93e2-99329677c511.png)

*echo $NODE_OPTIONS* : --max_old_space_size=4096

**Comment by gireeshpunathil** [comment]
@Jones-Thomas - is this still an issue? May be you need to increase your heap size? Is there a rough estimate on your heap memory requirement?

**Comment by PoojaDurgad** [comment]
@Jones-Thomas , is this still an issue ?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
