### ISSUE TITLE
why i can't  get the file of path2?

### ISSUE THREAD

**Issue by hwbeauty** [nodejs/help#213]
var req = http.request(options, function(res){
            var writer = fs.createWriteStream(path1);
                                res.pipe(writer,{flag:'w+',autoClose:true});
                                res.on('end',function(){
                            optins ........
                             writer.end();
                             var req = http.request(options, function(res){
                                          var writer = fs.createWriteStream(path2);
                                                               res.pipe(writer,{flag:'w+',autoClose:true});
                                                                res.on('end',function(){
                                                      writer.end();
                                              });
                              });

```
                });
     });
```

**Comment by addaleax** [comment]
I’m not fully sure what you’re asking, but a couple of things:

* The options `{flag:'w+',autoClose:true}` are ignored when passed to `pipe()`. Did you mean to pass them to `fs.createWriteStream()`?
* The second `res.on('end',function(){ writer.end(); });` bit is unnecessary, as `pipe()` will do that automatically by default (see [stream.pipe()](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options)).
* Is the second HTTP request (if that is what it is) actually executed? Can you verify that using some `console.log()` calls?
* It’s optional, but wrapping your code in ```` ```js … ``` ```` when posting it on Github can be pretty helpful for making it more readable.
* Is there some kind of error (message)?

**Comment by hwbeauty** [comment]
var req = http.request(,,,){
         res.pipe(fs.createWriteStream(despath[index+1],{flag:'w+',encoding:encoding,autoClose:true}));
         var req = http.request(,,,){
                 res.pipe(fs.createWriteStream(path2,{flag:'w+',encoding:encoding,autoClose:true}));
                 childProcess.exec('dos2unix -q '+path2,function(error, stdout, stderr) {
               ,,,js,,,
              });

         });
  });
 after execute  childProcess.exec() ,the context in the file (path2) is gone ,the size of path2  turns out to be 0B ,I dont know why ?  is  the method pipe() is a Synchronous method?

**Comment by addaleax** [comment]
>  is the method pipe() is a Synchronous method?

`pipe()` won’t wait until the stream has ended, no.

It looks like you want to execute `dos2unix` *after* the file has been written to disk. In that case, the following might do what you want:

```js
var req = http.request(…){
var writer = fs.createWriteStream(path2,{flag:'w+',encoding:encoding,autoClose:true});
res.pipe(writer);
writer.on('finish', function() {
childProcess.exec('dos2unix -q '+path2,function(error, stdout, stderr) {
…
});
});
```
