### ISSUE TITLE
Attaching terminal debugger to a docker container.

### ISSUE THREAD

**Issue by creativecreaturex** [nodejs/help#2130]
Hi, I have been running a node.js server locally and debugging it using `node --inspect app.js`

It works great and I'm using repl and evaluating variables at runtime. 

I have now dockerized my application and running it using `docker-compose up`. 

Here is a more detailed description that I posted to stackoverflow: https://stackoverflow.com/questions/57574555/attach-cli-debugger-to-node-application-running-in-docker#

The issue is that now that I'm running the application in docker I can only attach a debugger using some other software like vs-code or google chrome. I want to just keep debugging in my terminal the same way I did before running it in docker. 

I'm looking for some cli command to attach to the node process running in docker. I'm not sure if this is possible but since chrome and vscode running on my machine can attach to the node process running in docker I'm thinking my terminal should be able to do it as well. Really thankful for any help on this.

**Comment by bnoordhuis** [comment]
Are you looking for the `node inspect <host>:<port>` command?

**Comment by creativecreaturex** [comment]
What should the startup command be for the docker container then? node app.js or node --inspect app.js? 

And all I have to do for the container is expose the debug port?

**Comment by bnoordhuis** [comment]
You want to use `node --inspect=<host>:<port> app.js` where `host` is either `0..0.0.0` or the address of the specific interface it should listen on (e.g. `10.0.0.2`.)

9229 is a good default for `<port>`. :-)

**Comment by gireeshpunathil** [comment]
closing as answered; pls re-open if anything outstanding here
