### ISSUE TITLE
How to pass globals from main thread to workers

### ISSUE THREAD

**Issue by vitaly87** [nodejs/help#2132]
I am starting to use nodejs 12 and trying to pass from main thread that open workers I need to pass some globals this run with codeceptjs automation, The issue that before I have one main thread and now I want to handle workers also but don't know how the globals will be available on workers. My code for single is

  global.host =getHost();
node.js multithreading globals

**Comment by tniessen** [comment]
I assume you are using the `worker_threads` module? You can use [postMessage](https://nodejs.org/api/worker_threads.html#worker_threads_worker_postmessage_value_transferlist) to pass data to worker threads.

**Comment by ORESoftware** [comment]
use env variables to pass primitives as JSON

**Comment by gireeshpunathil** [comment]
@vitaly87 - were you able to apply the suggestions and solve it?

**Comment by PoojaDurgad** [comment]
@vitaly87 , is this still an issue ?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
