### ISSUE TITLE
node: undefined symbol: uv_os_free_environ

### ISSUE THREAD

**Issue by sorleone** [nodejs/help#2133]
When executing the `node` command on the terminal I get: 

`node: undefined symbol: uv_os_free_environ`

with Node.js versions >= 12.8.1 

System: Linux x86/64 5.2.9-arch1-1-ARCH

**Comment by mathieujobin** [comment]
did anyone suggested Arch to update their package version requirement? 
they should have been automatically installed as dependencies...

**Comment by gireeshpunathil** [comment]
> did anyone suggested Arch to update their package version requirement?

None that I am aware of.

closing as resolved, feel free to re-open if it is outstanding
