### ISSUE TITLE
"a" || "b" ? 1 : 2 vs "a" || ("b" ? 1 : 2) - bug or feature? really

### ISSUE THREAD

**Issue by btzsoft** [nodejs/help#2135]
* **Version**: v8.11.1
* **Platform**: osx

```js
console.log("a" || "b" ? 1 : 2) // 1
console.log("a" || false ? 1 : 2) // 1
console.log("a" || ("b" ? 1 : 2)) // 'a'
```

why?
can someone give some explanation, or I don't know JS.

**Comment by devsnek** [comment]
@btzsoft 

```js
'a' || 'b' ? 1 : 2
```
is the same as
```js
('a' || 'b') ? 1 : 2
```

`'a' || 'b'` returns `'a'` because `'a'` is truthy, and `'a' ? 1 : 2` is `1`.

On the third line though, you change the grouping:
```js
'a' || ('b' ? 1 : 2)
```

`'a'` is truthy, so its returned, and the right-hand side of the `||` isn't evaluated.

**Comment by btzsoft** [comment]
@devsnek thx, it was unexpected for me. closing this.
