### ISSUE TITLE
how to get file descriptor of process.{stdin,stdout,stderr}

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2136]
On Node.js 8+, is there a way to get file descriptors for process.stdin, process.stdout, process.stderr in the node.js runtime?

**Comment by addaleax** [comment]
Is `process.stdin.fd`, `process.stdout.fd`, `process.stderr.fd` what you’re looking for? They do have fixed values, i.e. 0, 1 and 2, unless you are running code inside a Worker (in which case they are not associated with fds) or the streams have been overwritten with other objects.

**Comment by ORESoftware** [comment]
that should do, i think i had this same problem before, typescript typings didnt mention the fd's

**Comment by gireeshpunathil** [comment]
closing as answered

**Comment by ORESoftware** [comment]
anyone know how this can be accomplished given a file descriptor perhaps in a Node.js process?
https://unix.stackexchange.com/questions/576954/discover-what-file-stdout-is-being-written-to
