### ISSUE TITLE
nodejs.pkg on macOS catalina platform

### ISSUE THREAD

**Issue by MajuMadhusudanan** [nodejs/help#2137]
NodeJS.v12.9.0.pkg
macOS Mojave 10.14.6 and Catalina 10.15
install
nodeJS package

I have downloaded latest nodeJS.v12.9.0 package file from nodejs website and bundled it into our product setup. Apple introduced notarization of package files and binaries recently from Mojave 10.14.6 and macOS catalina onwards. So i need to notarize my package file for deploying it on catalina.

But notarization failed due to nodejs .pkg file. Apple expects all package files to be notarised from catalina onwards. Can anyone send me link of nodeJS package file (notarized one)?  Is there anychange required in distribution package?

**Comment by Hakerh400** [comment]
See https://github.com/nodejs/node/issues/29216

**Comment by MajuMadhusudanan** [comment]
Yes. Sorry. I'm new to nodeJS. I thought nodejs/node#29216 is for reporting bug.  I was integrating and testing latest version of nodeJS. But I don't see any difference in behaviour. That is why i posted a question in nodes\help link

**Comment by gireeshpunathil** [comment]
@MajuMadhusudanan - is this still an issue?

**Comment by MajuMadhusudanan** [comment]
Yes. Tested using v12.14.0 build and Apple still reporting warnings for the below executables (term-size and node). 

 "issues": [
    {
      "severity": "warning",
      "code": null,
      "path": "Sample.pkg Contents/Payload/Library/Application Support/iManage/Script/node-v12.14.0.pkg/npm-v6.13.4.pkg Contents/Payload/usr/local/lib/node_modules/npm/node_modules/term-size/vendor/macos/term-size",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "warning",
      "code": null,
      "path": "Sample.pkg Contents/Payload/Library/Application Support/iManage/Script/node-v12.14.0.pkg/npm-v6.13.4.pkg Contents/Payload/usr/local/lib/node_modules/npm/node_modules/term-size/vendor/macos/term-size",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "warning",
      "code": null,
      "path": "Sample.pkg Contents/Payload/Library/Application Support/iManage/Script/node-v12.14.0.pkg/npm-v6.13.4.pkg Contents/Payload/usr/local/lib/node_modules/npm/node_modules/term-size/vendor/macos/term-size",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "warning",
      "code": null,
      "path": "Sample.pkg Contents/Payload/Library/Application Support/iManage/Script/node-v12.14.0.pkg/node-v12.14.0.pkg Contents/Payload/usr/local/bin/node",
      "message": "The signature algorithm used is too weak.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "warning",
      "code": null,
      "path": "Sample.pkg Contents/Payload/Library/Application Support/iManage/Script/node-v12.14.0.pkg/node-v12.14.0.pkg Contents/Payload/usr/local/bin/node",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
