### ISSUE TITLE
how to write to running bash process

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2141]
I have this code:

```js

  const procs: Array<ChildProcess> = [];
  
  for (let p of servers) {
    
      const k = cp.spawn('bash');
      
      k.stdin.write(`
          ssh -Y root@${p.dns} -i $PEM_HOME/prod.pem bash
      `);
      
      k.stdout.pipe(process.stdout);
      k.stderr.pipe(process.stderr);
      
      procs.push(k);
    
  }
  
  
  const run = () => {
  
    for(const p of procs){
      p.stdin.write('echo "foo"');
    }
  
  };
```

in the run function I am trying to write to the bash procs launched by ssh,  basically trying to re-use procs instead of always launching new ones, unfortunately it doesn't seem to log any stdout/stderr, if I write things like `echo x` to it.

any idea why?

**Comment by tniessen** [comment]
`write` outputs `echo "foo"`, but no line feed. `bash` won't run a command that is not terminated by a line feed.

**Comment by PoojaDurgad** [comment]
@ORESoftware , is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
