### ISSUE TITLE
Error -13

### ISSUE THREAD

**Issue by PointZeroSeven** [nodejs/help#2142]
10.16.3
* **OS**:
version checking

Following is error code I'm receiving. Even with hidden files shown, I can't find the relevant file to set permissions:

{ [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/agentkeepalive']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/npm/node_modules/agentkeepalive\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path:
npm ERR!    '/usr/local/lib/node_modules/npm/node_modules/agentkeepalive' }

```
-->

**Comment by PointZeroSeven** [comment]
Mac OS 10.14.6

**Comment by tniessen** [comment]
Please tell us which command you were running that led to the error.

**Comment by gireeshpunathil** [comment]
ping @PointZeroSeven

**Comment by PoojaDurgad** [comment]
@PointZeroSeven , can you elaborate the issue please? so that it will be helpful for me to identify the bug.

**Comment by PoojaDurgad** [comment]
inactive. closing!!
