### ISSUE TITLE
create new Date issue

### ISSUE THREAD

**Issue by SongThien** [nodejs/help#2143]
* **Version**:12.9.0
* **Platform**:Windows 10 64-bit
* **Subsystem**:

![image](https://user-images.githubusercontent.com/52626973/63645030-fa5fb280-c71f-11e9-8374-2147dfca9f6f.png)

code:
`var time = new Date(2019,8,24,0,0,0,0);
console.log(time.getMonth());
console.log(time.toString());;`

must be return: Sat Aug 24 2019

**Comment by gireeshpunathil** [comment]
closing as answered
