### ISSUE TITLE
node 10 memory leak 

### ISSUE THREAD

**Issue by abdelmun3m** [nodejs/help#2144]
Version: v10.15.1
Platform: TC 2017 x86_64 x86_64 x86_64 GNU/Linux

* **v10.15.1**:
* **TC 2017 x86_64 x86_64 x86_64 GNU/Linux**:

i am running a web application which join both http server a socket.io 
and i am trying to create a load test using artillery.io to test my server 
i have script which simulate a login processes for more than 600 user which login and open a socket to transfer data in a real time way then 
i noticed that my application is eating the memory with each run for the test script 

by monitoring the memory usages  of my process i found that 

before test running 
** values are in Mb

start :  { heapTotal: 86.28515625,
  rss: 105.7265625,
  heapUsed: 58.0430908203125,
  external: 21.159916877746582 }

after run the test file for the first time 
 { heapTotal: 174.875,
  rss: 359.0625,
  heapUsed: 144.08592224121094,
  external: 154.9897975921631 }

after run the test file for the second time 
{ heapTotal: 232.875,
  rss: 434.21484375,
  heapUsed: 189.2647247314453,
  external: 20.66956901550293 }

after run the test file for the third time 

{ heapTotal: 313.875,
  rss: 524.3984375,
  heapUsed: 248.91544342041016,
  external: 20.82130527496338 }

and it is increasing with every run which mean that my application in holding the memory and neither set it free nor reuse it again, and the memory growth increasing with increasing the number of login users  

this is the packages i am using 

[package.json.txt](https://github.com/nodejs/node/files/3538136/package.json.txt)

can any one help in solving such memory problem

**Comment by addaleax** [comment]
I’ve moved this to nodejs/help because the chances of it being a bug with Node.js seem low so far.

> it seems that the size of strings in the heap increased

While the overview that DevTools provides is a nice visualization, it’s often much more helpful to look at the Summary view in it, because that helps showing which JS objects exactly are involved.

**Comment by gireeshpunathil** [comment]
@abdelmun3m - is this still a problem? were you able to figure out which objects are growing by looking at the summary view? If not, can you collect and provide few instances of heapdumps that represent the memory growth? I can inspect and provide some insights

**Comment by PoojaDurgad** [comment]
@abdelmun3m ,is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
