### ISSUE TITLE
creating writeStream on non-existent file descriptor works?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2145]
I have this code:

```js
#!/usr/bin/env node

const fs = require('fs');

try{
  var w = fs.createWriteStream(null, {fd:3});
}
catch(err){
  throw 'moop: ' + err;
}

w.write('foo');
```

if I run it like this:

```bash
node foo.js 3> temp.log
```

it work fine, but if I do this:

```bash
node foo.js
```

then I will get this error:

```bash
oleg@xps:~/codes/oresoftware/bunion$ node foo.js 
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: EINVAL: invalid argument, write
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:449:5)
    at onwrite (_stream_writable.js:470:5)
    at internal/fs/streams.js:313:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:525:5) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'write'
}
Aborted (core dumped)
```

it seems odd that I can create the writeStream on that non-existent file descriptor? B/C it's erroring out on the w.write call, not the fs.createWriteStream call.

**Comment by ORESoftware** [comment]
as an aside, using Node.js is there a way to test if a file descriptor is valid? determine if it's writable or readable?

**Comment by gireeshpunathil** [comment]
when you redirect, a pipe is created between node and shell for the data xfer. that pipe potentially holds fd 3. (fd 0, 1, and 2 being used up already for std streams). 

So you are writing onto some `arbitrary` fd

when you don't redirect, fd 3 is actually invalid, and hence the error

this behavior is not consistent across platforms. For example, fds may not be created in incremental sequence in all platforms.

> using Node.js is there a way to test if a file descriptor is valid?

there is an internal  function `util.guessHandleType` but is not exposed as an API

```js
> var u = process.binding('util')
undefined
> u.guessHandleType
[Function: guessHandleType]
> u.guessHandleType(0)
'TTY'
> u.guessHandleType(10)
'PIPE'
> u.guessHandleType(30)
'UNKNOWN'
> 
```

**Comment by PoojaDurgad** [comment]
@ORESoftware , is this still outstanding? did @gireeshpunathil 's suggestion help you to resolve the issue?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
