### ISSUE TITLE
"node ." No Such Thing Is A Command

### ISSUE THREAD

**Issue by MichaelIsCold31** [nodejs/help#2147]
Hi, There I Was MAking A Discord Bot And Try to Run The Command to Turn On The Bot "node ." And Is Not A Command Becuase Last Time It Worked And This Time It Did Not Work Please Help Thanks

![image](https://user-images.githubusercontent.com/54568048/63740914-f762ee80-c8e6-11e9-96d3-29cabd742ede.png)

**Comment by fbarda** [comment]
You need to restart vs code if you installed nodejs after opening vscode. Also, giving away the token is not a good idea.

**Comment by tniessen** [comment]
Check your `PATH` environment variable, it should include the installation path of Node.js. It will only affect processes that were started after installing Node.js, as @fbarda wrote. Let us know if you need further assistance.
