### ISSUE TITLE
async hooks: relationship between async resource created and resource executing init event

### ISSUE THREAD

**Issue by matej-prokop** [nodejs/help#2149]
* **Node.js Version**: v10.16.3
* **OS**: MacOS 10.14.6

I have following module that I use for playing with `async_hooks`.

```js
const asyncHooks = require("async_hooks");

const treeMap = new Map();

const init = (asyncId, type, triggerId, resource) => {
  const tree = `${treeMap.get(triggerId)} - ${asyncId}`;
  treeMap.set(asyncId, tree);

  process._rawDebug(`init - tree: ${tree}`);
  process._rawDebug(`init - asyncId: ${asyncId}`);
  process._rawDebug(`init - triggerId: ${triggerId}`);
  process._rawDebug(`init - executionAsyncId(): ${asyncHooks.executionAsyncId()}`);
};

const before = (asyncId) => {
  process._rawDebug(`before - entering: ${asyncId}`)
}

asyncHooks.createHook({ init, before }).enable();
```

When I use it within my application, it prints following output (showing only part of output):
```
...
before - entering: 76
init - tree: undefined - 6 - 18 - 21 - 41 - 42 - 43 - 44 - 51 - 69 - 79
init - asyncId: 79
init - triggerId: 69
init - executionAsyncId(): 76
....
```

From this output, I see that
- `before` event was most recently invoked for resource with asyncId 76
- new resource with asyncId 79 is being created
- `init` event is executed in context of 76 but triggerId is 69

Is there any relationship between 79 and 76 or it is only coincident that `init` event was called within context of 76?

**Comment by matej-prokop** [comment]
I am asking because I am evaluating https://github.com/Jeff-Lewis/cls-hooked for storing request context data (Request ID) and I want to be sure that it uses async hooks properly.

`cls-hooked` is implemented in way that assumes that resource executing `init` event is "parent" of resource being created (`asyncId`) so context is shared between them. However, I didn't find anywhere within documentation that it would be true.

**Comment by matej-prokop** [comment]
@bnoordhuis Would you be able to answer this? Or can you please point out someone else who could know? Thank you!

**Comment by bnoordhuis** [comment]
I think the answer is 'coincidence' but @addaleax can probably say for sure.

**Comment by addaleax** [comment]
@matej-prokop A full example might be helpful :)

The `executionAsyncId()` gives you the resource that is currently active when the new resource is created, and `triggerId` gives you the resource that is responsible for creating this action.

For example, when you’re running an HTTP server and you manually inject a new connection via `server.emit('connection', stream');`, the `HTTPParser` instance created for that should have the `executionAsyncId()` of whatever you are running during that call, but the `triggerId` should be the one of the HTTP server.

(I don’t fully agree with this design but I guess it is what it is.)

**Comment by gireeshpunathil** [comment]
ping @matej-prokop - should this remain open?

**Comment by matej-prokop** [comment]
Response from addaleax is what I was looking for so it is fine to close this issue. Sorry that I didn't do it earlier and thank you for response!

My conclusion was that it would be dangerous to rely on https://github.com/Jeff-Lewis/cls-hooked because it isn't using async hooks properly.
