### ISSUE TITLE
node-gyp not pulling src/win_delay_load_hook.cc

### ISSUE THREAD

**Issue by robogen** [nodejs/help#215]
I'm having a slight issue with the fix at nodejs/node#7513 of `npm install -g npm@next`, the src folder and the file win_delay_load_hook.cc are not being automatically created for node-gyp v3.4.0. It's a simple enough thing to manually create them, but was curious if others were having this issue. 

I'm on Win7 x64, node v.4.4.6, npm v3.10.4

**Comment by rvagg** [comment]
The fix didn't go in properly to npm v3.10.4, see https://github.com/npm/npm/issues/13256, new release hopefully out today. npm@2 should work though if you really need it.
