### ISSUE TITLE
Intl.DateTimeFormat - wrong long weekday

### ISSUE THREAD

**Issue by arxeiss** [nodejs/help#2150]
* **Version**: v12.9.0
* **Platform**: Ubuntu 19.04 *Linux 5.0.0-25-generic nodejs/node#26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux*

I think it is related to nodejs/node#26790 because when no full ICU is installed and I have different locale, weekday long always returns short.

```js
new Intl.DateTimeFormat('cs-CZ', { weekday: 'long', timeZone: 'UTC' }).formatToParts(new Date('2017-10-30'))[0].value; // Mon

new Intl.DateTimeFormat('en-US', { weekday: 'long', timeZone: 'UTC' }).formatToParts(new Date('2017-10-30'))[0].value; // Monday
```

If localisation for cs-CZ is not installed, it returns fallback English name? Because for months it works differently, for cs-CZ it returns M10

**Comment by bnoordhuis** [comment]
The answer to your questions is mostly 'because ICU' - that's the library that implements the i18n logic, not node or V8 itself.

**Comment by arxeiss** [comment]
OK, according to issue into which I referenced before (nodejs/node#26790) I thought, that this is nodejs thing. But if it has nothing to do with node itself, than there is no place to fix it.

So probably it can stay closed - thank you
