### ISSUE TITLE
Class method doesn't show up in value of the instance

### ISSUE THREAD

**Issue by fbarda** [nodejs/help#2151]
* **Version**:v12.9.0
* **Platform**:Linux localhost 3.18.91-16437666 nodejs/node#1 SMP PREEMPT Tue Jul 23 17:05:45 KST 2019 armv8l Android
* **Subsystem**: none

Tried to create a class function without a constructor but with a function.
Created an instance of it.
The object has the key for the method but the method doesn't show up in value.

```js
class a{
  test(){ console.log("test"); }
}
console.log(a); // [Function: a]
var b = new a();
console.log(b); // a{}
console.log(b.test); // [Function: test]
b.test() // test
```

**Comment by fbarda** [comment]
Oh, is there any way to change that property to true by default?

**Comment by Hakerh400** [comment]
> The object has the key for the method

That's incorrect. The object is empty, but its prototype is equal to the `prototype` property of the class `a`

> Is there any way to change that property to true by default

The JavaScript does not provide a way to do so, but if you just want to include it in the console log output, you can use a custom inspect function:

```js
const inspect = require('util').inspect.custom;
class Base{
  [inspect](){
    const obj = Object.create(null);
    for(let elem = this; elem !== Base.prototype; elem = Object.getPrototypeOf(elem)){
      for(const key of Reflect.ownKeys(elem)){
        if(key !== inspect) Object.defineProperty(obj, key, {
          value: this[key],
          enumerable: true,
        });
      }
    }
    return obj;
  }
}

class a extends Base{
  test(){ console.log("test"); }
}

console.log(new a()); // a { constructor: [Function: a], test: [Function: test] }
```

**Comment by fbarda** [comment]
Understood. Thanks again.
