### ISSUE TITLE
Write chinese character in file

### ISSUE THREAD

**Issue by yongzhe-han** [nodejs/help#2153]
```javascript
const fs = require('fs');

fs.appendFileSync('test.txt', '哈哈', 'utf8');
```
open with notepad result:
![image](https://user-images.githubusercontent.com/52684304/63942446-5cae0f80-caa0-11e9-93b2-820335564ee5.png)

open with wordpad result:
![image](https://user-images.githubusercontent.com/52684304/63942479-6fc0df80-caa0-11e9-977e-b109b7b73099.png)

nodejs version: v10.15.3
OS: windows10 x64

**Comment by simonkcleung** [comment]
I mean the .js file

**Comment by Hakerh400** [comment]
That's a WordPad issue, not a Node.js issue. There is probably some option in WordPad to open the file as UTF-8 encoding.

**Comment by Hakerh400** [comment]
It seems that WordPad defaults to ASCII unless the file contains [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). The following code works fine:

```js
const fs = require('fs');

fs.writeFileSync('test.txt', Buffer.from('EFBBBF', 'hex'));
fs.appendFileSync('test.txt', '哈哈');
```

**Comment by yongzhe-han** [comment]
@Hakerh400, Thanks for your reminder.
