### ISSUE TITLE
(node:4) UnhandledPromiseRejectionWarning: Error: ETELEGRAM: 400 Bad Request: chat not found

### ISSUE THREAD

**Issue by tanc41** [nodejs/help#2154]
`(node:4) UnhandledPromiseRejectionWarning: Error: ETELEGRAM: 400 Bad Request: chat not found
    at request.then.resp (/app/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)`

Help solve. I decided to make a bot in telegram, but something came to a standstill how to solve it. In which part of the code I can’t solve the problem.

maybe the problem is somewhere here? because after the user clicks start, this error comes out

`		if(typeof(message.text.split("/start ")[1]) === "string") {
			let link = await Ref.findOne({ name: message.text.split("/start ")[1] });

			if(link) {
				if(!link.refs.find((x) => x === message.from.id)) {
					link.refs.push(message.from.id);
					await link.save();
				}
			}
		}

		let user = new User(schema);
		await user.save();

		return message.send(`Выберите действие. ⤵️`, {
			reply_markup: {
				keyboard: $menu,
				resize_keyboard: true
			}
		});
	});

	message.user = await User.findOne({ id: message.from.id });
	
	let { status } = await bot.getChatMember(-1001457333935, message.from.id);
	if(status === 'left') return message.send(`➕ *Для того, чтобы* начать/продолжить работу с ботом, *вы должны быть подписанным* на канал https://t.me/joinchat/AAAAAFbi0989`, {
		parse_mode: 'Markdown',
		reply_markup: {
			inline_keyboard: [
				[{ text: '➕ Подписаться', url: 'https://t.me/joinchat/AAAAiir0ot' }]
			]
		}
	});
`

**Comment by danger89** [comment]
Did you tried an older server configuration with SSL?

Nginx example:
https://ssl-config.mozilla.org/#server=nginx&server-version=1.17.0&config=old

**Comment by danger89** [comment]
In my case I use Nginx as reverse proxy for my Bot (so my bot is running on port 3005 without SSL), but Nginx will make my bot available to my.domain.com running on port 80/443 with SSL:

Something like (I'm using Let's Encrypt to get free SSL/TLS certificates):
```
server {
    listen 443 ssl http2;
    server_name your.domain.com;
    server_tokens off;

    ssl on;
    # Certificate & key
    ssl_certificate /etc/letsencrypt/live/your.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/your.domain.com/privkey.pem; # managed by Certbot

    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    ssl_dhparam /etc/ssl/certs/dhparam.pem;

    # old configuration
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-S$
    ssl_prefer_server_ciphers on;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://localhost:3005;
    }
}
```
