### ISSUE TITLE
Buffer.from(str, 'base64').buffer has wrong length/data

### ISSUE THREAD

**Issue by sheinzle** [nodejs/help#2156]
Affects
* v10.16.3 & v12.9.1
* Darwin Kernel Version 18.7.0

I am working in a scenario where the server receives a `Float32Array` encoded as base64 `string`. Based on the doc, the straightforward way is decode the base64 is:

1. Create a `Buffer` from the base64 string
2. Re-interpret the `Buffer` as `Float32Array`. 

See a version that works and one that doesn't below:

```JavaScript
function decodeBase64ToFloat32_Wrong (str) {
  return new Float32Array(Buffer.from(str, 'base64').buffer)
}

function decodeBase64ToFloat32_Works (str) {
  // decode base64 to Buffer
  const buffDecoded = Buffer.from(str, 'base64')
  
  // create new ArrayBuffer
  const buffer = new ArrayBuffer(buffDecoded.byteLength)
  // create a UInt8Array view & copy the decoded data
  const decodedUint8 = new Uint8Array(buffer).set(buffDecoded)
  // return Float32Array view
  return new Float32Array(buffer)
}

// simulate input
const input = Float32Array.from([0.25, 0.5, 0.75, 1])
const base64 = Buffer.from(input.buffer).toString('base64')

// gives back wrong result
console.log(decodeBase64ToFloat32_Wrong(base64))

// gives back correct result
console.log(decodeBase64ToFloat32_Works(base64))

```

Notes:
* `Buffer.from(str, 'base64')` seems to work and has the right `byteLength`
* `Buffer.from(str, 'base64').buffer` however either points to some other data and/or other length.

**Comment by sheinzle** [comment]
Great! Thanks a lot for your response @bnoordhuis.

I assume you're referring to the [section on Buffer.allocUnsafeSlow(size)](https://nodejs.org/dist/latest-v12.x/docs/api/buffer.html#buffer_class_method_buffer_allocunsafeslow_size)? That seems to be the only reference to slicing and reusing 4KB buffers. Reading between the lines, when calling `Buffer.from(...)` will use `.allocUnsafeSlow`. Hence slicing will occur for small buffers, and we need to account for `.byteOffset` and `.length` when accessing the `.buffer` directly. I think a note on this already in the `.from(...)` section or the `.buffer` section might help other users.

For future reference, the most straightforward way seems to be: 

```
function decodeBase64ToFloat32(str) {
  const decoded = Buffer.from(str, 'base64')
  return new Float32Array(decoded.buffer, decoded.byteOffset, decoded.byteLength/4)
}
```

**Comment by tniessen** [comment]
This appears to be solved. Feel free to comment or reopen if not.
