### ISSUE TITLE
lib: DNS getting info more same the "dig"

### ISSUE THREAD

**Issue by renanbastos93** [nodejs/help#2160]
Have is possible to get info more based on `dig`?
I want to get info as an authority, etc: ` QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1`

Example:
```
dig google.com

; <<>> DiG 9.10.6 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11907
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		299	IN	A	216.58.202.142

;; Query time: 60 msec
;; SERVER: 2001:4860:4860::8888#53(2001:4860:4860::8888)
;; WHEN: Mon Sep 02 13:48:36 -03 2019
;; MSG SIZE  rcvd: 55

```

**Comment by tniessen** [comment]
I find it hard to understand what you are trying to achieve, could you clarify? What information from the above output are you trying to obtain using node?

**Comment by renanbastos93** [comment]
I will to try expression better my idea.
Well, I want know how to get parameters in resolution info equals the `dig`. Example:
Get additional section in resolução DNS

Do you understand?

**Comment by tniessen** [comment]
I understand that you want to get more information, but I am not entirely sure which sections you need, and I also don't know what dig supports that Node.js doesn't.

I think the "PSEUDOSECTION" is related to EDNS/DNSSEC, which is not supported.

The "ANSWER SECTION" is just the result of the query, and can be retrieved using Node.js.

**Comment by renanbastos93** [comment]
I wish to use to validate info to test a resolver DNS. But thanks a lot for contributing information
