### ISSUE TITLE
Can someone help me???

### ISSUE THREAD

**Issue by raica98** [nodejs/help#2162]
* **Version**:
* **Platform**:
* **Subsystem**:

var msg = "hello world";
console.log(msg);

Terminal result:

c:\Users\flori\OneDrive\Desktop\JS>node test.js

c:\Users\flori\OneDrive\Desktop\JS>node test.js

c:\Users\flori\OneDrive\Desktop\JS>node test.js

c:\Users\flori\OneDrive\Desktop\JS>node test.js

c:\Users\flori\OneDrive\Desktop\JS>node test.js

c:\Users\flori\OneDrive\Desktop\

Terminal is not running test.js

can someone please help me?

**Comment by ORESoftware** [comment]
try:

```bash
echo 'console.log("hello world")' > test.js
node test.js
```

**Comment by raica98** [comment]
Thank you soo much ! I figured it out I wasn't saving the file before node index.js

**Comment by ORESoftware** [comment]
fo sho

**Comment by gireeshpunathil** [comment]
closing as answered
