### ISSUE TITLE
write huge data into a file in crashes node

### ISSUE THREAD

**Issue by ask-khan** [nodejs/help#2164]
**The node crashes when writing around ~600MB of data into a file. It works fine if the writable data is smaller.
P.S. My server has 4 GB of ram.
How to solve this issue? Any help would be highly appreciated. The code is list below I am using **write** function of fs and I can used pipe for it but for this i have to readstream function in it with writestream**

```js
function logIntoFile (logObject){
  let date = new Date();
  let currentDate = date.getFullYear() + '-' + (((date.getMonth() + 1) < 10) ? '0' : '') + (date.getMonth() + 1) + '-' + ((date.getDate() < 10) ? '0' : '') + date.getDate();
  let currentHour = ( (date.getHours() < 10 ? '0' : '') + date.getHours() );

  let fileName = '/custom-logs/resultSet_' + currentDate + '_' + currentHour + '@' + logObject.dbName;
  let logFile = fs.createWriteStream(__dirname + fileName, { flags: 'a' });

  logFile.write(util.inspect(logObject, false, null) + '\n');
  logFile.end();
}

// doQuery contains logic to connect to DB and run the query provided
doQuery(req, res, sql, false, function(err, result){
   if (err) {
      ...
      console.error(err);
      res.send(err);
   } else {
      ...
      res.send(result);
      ...
      logIntoFile({
         timeStamp : getCurrentDateTime(),
         dbName    : req.session.iss.dbname,
         userId    : inuserid,
         sql       : sql,
         error     : err,
         response  : result
      });
});
```

**Comment by MeetPatel5** [comment]
I think you should use read/write stream API instead of writing entire file to the system.

**Comment by addaleax** [comment]
It would be helpful if you could share the error message you’re seeing, as well as provide info about the kind of data you’re writing (i.e. whether the file is 600 MB in size or you’re writing 600 MB in one call).

**Comment by ask-khan** [comment]
> I think you should use read/write stream API instead of writing entire file to the sys

> It would be helpful if you could share the error message you’re seeing, as well as provide info about the kind of data you’re writing (i.e. whether the file is 600 MB in size or you’re writing 600 MB in one call).

<img width="476" alt="WdpZu" src="https://user-images.githubusercontent.com/11369261/64379238-e97c3e80-d047-11e9-8812-0e3c66a40916.png">

**Comment by addaleax** [comment]
This sounds like an issue with reading too much data from the database, rather than writing too much data?

**Comment by gireeshpunathil** [comment]
ping @ask-khan - is this still pending?

**Comment by PoojaDurgad** [comment]
@ask-khan - is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
