### ISSUE TITLE
How to have Node/Express respond to both IPv4 and IPv6 on CentOS 7

### ISSUE THREAD

**Issue by devlocalca** [nodejs/help#2167]
* **Node.js Version**: 10.10.0
* **OS**:  CentOS 7
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: express

Node/Express under CentOS 7 defaults to listen on IPv6 when host is omitted as per the documentation, but connecting from IPv4 does not work.

--
Under CentOS 7, if I do not specify the host like:
`server.listen(port)`, by default it will listen on **IPv6**, but the web server will not respond to request made by clients with an IPv4 address.

```netstat -nlt``` shows:

`tcp6       0      0 :::3001                 :::*                    LISTEN`

now if I specify the host by:   `server.listen(port, '0.0.0.0')`, the `tcp6 0 ::3001 LISTEN` entry goes away, and an entry for `0.0.0.0:3001 LISTEN` appears, and it will accept requests from clients with a IPv4 ip address, but **not** hosts with IPv6.

how do I configure so that it will respond to requests for both IPv4, and IPv6?

If you have access to CentOS 7 and Node.js 10.10.0, with an express project, please give this a try.  This behavior is happening on a CentOS 7 VM running on GCP.  The same behavior may not be seen on other OS's (speculating), not sure.

**Comment by bnoordhuis** [comment]
Check out the `net.ipv6.bindv6only` sysctl. It defaults to off but it sounds like on your system it's turned on.

**Comment by gireeshpunathil** [comment]
ping @devlocalca - is this issue resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
