### ISSUE TITLE
Package empty in nodejs 12 i368

### ISSUE THREAD

**Issue by NebzHB** [nodejs/help#2170]
https://deb.nodesource.com/node_12.x/dists/stretch/main/binary-i386/

the Package file is 0...
"i386 (32-bit)—not available for Node.js 10 and later"

how to install then ?

**Comment by tniessen** [comment]
We have downgraded i386 to an experimental platform (as stated in [this list](https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list)), and do not provide the same level of support, and no precompiled binaries. We recommend using the fully supported x64 versions when possible.

If you are using an older architecture that only supports i386, you can [build node from source](https://github.com/nodejs/node/blob/master/BUILDING.md#unix-and-macos).

**Comment by NebzHB** [comment]
thank you for you reply

**Comment by richardlau** [comment]
You can also try https://unofficial-builds.nodejs.org/.
