### ISSUE TITLE
Node.js and testcafe issues

### ISSUE THREAD

**Issue by SpencerWaller** [nodejs/help#2174]
HI,  We had version node.js 12.1.8 install along with Visual Studio Code and Testcafe.  We kept getting DNS Record Not Found At errors each time.  When we rolled back to Version 11.15 all works great.  Version 12 does not work.

Does anyone know what changed between version 11.15 and Version 12.# to cause these DNS issues?

Many thanks in advance

**Comment by tniessen** [comment]
Can you provide example code that demonstrates the issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
