### ISSUE TITLE
Too many additional tools, how to delete them?

### ISSUE THREAD

**Issue by NeoFantom** [nodejs/help#2177]
* **Node.js Version**: v12.10.0
* **OS**: Windows 10 Home 1903
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

**Problem**: I used the .msi installer to install nodejs. During guidance, there is a checkbox which asks me whether or not to install "additional tools" including `chocolatey`, `vstools `etc. I checked it (by default, it is unchecked). After installation, I found the so called "additional tools" are too much for me. So I have two questions:
1. Why does nodejs need these so many additional tools? Are they neccessary (I'm assuming not since it is by default unchecked)?
2. After installation, how can I know what softwares and packages are installed by nodejs? I want to delete them if they're not neccessary for nodejs.

**Comment by Hakerh400** [comment]
> Why does nodejs need these so many additional tools?

Node.js does not need anything besides the `node.exe` executable file that is automatically placed into `C:\Program Files\nodejs` folder after installation.

> Are they neccessary?

No. Node.js itself does not need these tools to run properly. However, if you plan to use external modules (for example from npm) that need to be compiled, you will need node-gyp, which requires python and msvs.

> After installation, how can I know what softwares and packages are installed by nodejs? I want to delete them if they're not neccessary for nodejs.

It installs:

* Python 2
* node-gyp
* NPM
* Visual Studio Build Tools
* Chocolatey
* Global dependencies in `%appdata%\npm\node_modules`
* NPM dependencies in `C:\Program Files\nodejs\node_modules\npm\node_modules`

**Comment by mclods** [comment]
Please help I also have the same issue!

**Comment by aavhanchatse** [comment]
I have the same problem. Please help.

**Comment by MAG-98** [comment]
someone help same issue!!!

**Comment by eclairevoyant** [comment]
Hello all, I wrote a stackoverflow answer about this here: https://stackoverflow.com/a/72409239/950837
> Assuming you don't use python or those VS tools, you can uninstall those additional tools by running
> `choco uninstall python visualstudio2019-workload-vctools`
> in a command line (cmd, powershell, etc). If you want, you can also [uninstall chocolatey afterwards](https://docs.chocolatey.org/en-us/choco/uninstallation).

**Comment by benjamingr** [comment]
This seems to be inactive so I'm going to go ahead and close this issue - cheers.
