### ISSUE TITLE
vm   vs  child_process??  which  should  use?

### ISSUE THREAD

**Issue by hwbeauty** [nodejs/help#218]
vm can excute **.js   and  child.exec(node  **.js)   which is better or safer ?

**Comment by addaleax** [comment]
These are quite different things, and there is no “better” or “safer” in this context. Do you want to run a script that can access the variables from your program or where you can pass data directly to it? Then `vm` should work for you.

If you want to run something that is an entirely different program and doesn’t interact with the rest of your code (other than its input/output), like `npm install`, `child_process` should be the right choice.

**Comment by addaleax** [comment]
@hwbeauty If that answered your question, feel free to close this issue. If not, you may want to be a bit more specific about what you’re intending to do.
