### ISSUE TITLE
"TLS" module cannot finish TLS handshake on self signed CA and certificate bound to IP

### ISSUE THREAD

**Issue by gnaggnoyil** [nodejs/help#2180]
Suppose there is a machine avaliable under IP `A.B.C.D` with port `E` open. Under a Linux environment the following commands is run to generate a bundle of self signed CA and certificate bound to IP `A.B.C.D`:

```shell
cd ~/certificate
openssl req -config config.conf -subj "/C=Q/ST=W/O=E" -new -x509 -extensions v3_ca -keyout private/myca.crt -out certs/myca.crt -days 365000
openssl req -config config.conf -subj "/C=FO/ST=FO/O=Bar/CN=A.B.C.D" -new -nodes -keyout private/server.key -out server.csr -days 365000
openssl ca -config config.conf -subj "/C=FO/ST=FO/O=Bar/CN=A.B.C.D" -policy policy_anything -out certs/server.crt -infiles server.csr
```

where the `[ ca ]` and `[ CA_default ]` section of `~/certificate/config.conf` is as the following: 

```
[ ca ]
default_ca      = CA_default            # The default ca section

[ CA_default ]

dir             = .             # Where everything is kept
certs           = $dir/certs            # Where the issued certs are kept
crl_dir         = $dir/crl              # Where the issued crl are kept
database        = $dir/index.txt        # database index file.
#unique_subject = no                    # Set to 'no' to allow creation of
                                        # several certs with same subject.
new_certs_dir   = $dir/newcerts         # default place for new certs.

certificate     = $dir/certs/myca.crt   # The CA certificate
serial          = $dir/serial           # The current serial number
crlnumber       = $dir/crlnumber        # the current crl number
                                        # must be commented out to leave a V1 CRL
crl             = $dir/crl.pem          # The current CRL
private_key     = $dir/private/myca.key # The private key
```

Then, on the machine that has IP `A.B.C.D`, an HTTPS server is run on port `E` with server certificate set as `certs/server.crt`, root CA set as `certs/myca.crt` and server key set as `private/server.key`. Then, to confirm that HTTP server has been sucessfully set up, the following two commands is run on any machine that is accessible to `A.B.C.D:E`:

```shell
curl --cacert ~/certificate/certs/myca.crt -L https://A.B.C.D:E/
openssl s_client -connect A.B.C.D:E -state -nbio -CAfile ~/certificate/certs/myca.crt
```

Both the following two commands can finish TLS handshake and return corresponding HTTP reponse.

 However, when the following script is run using nodejs on the same machine the previous two commands were run,

```javascript
"use strict";

const tls = require("tls");
const fs = require("fs");
const path = require("path");

const homedir = require("os").homedir();

options_tls = {
    host: "A.B.C.D",
    port: E,
    ca: fs.readFileSync(path.join(homedir, "certificate/certs/myca.cert"))
};
conn = tls.connect(options_tls);
conn.on("error", (e) => console.log(e));
```

the following error was outputed:

```
> Thrown:
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: A.B.C.D is not in the cert's list:
    at Object.checkServerIdentity (tls.js:279:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1327:27)
    at TLSSocket.emit (events.js:209:13)
    at TLSSocket.EventEmitter.emit (domain.js:499:23)
    at TLSSocket._finishInit (_tls_wrap.js:792:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12) {
  reason: "IP: A.B.C.D is not in the cert's list: ",
  host: 'A.B.C.D',
  cert: {
    subject: [Object: null prototype] {
      C: 'FO',
      ST: 'FO',
      O: 'Bar',
      CN: 'A.B.C.D'
    },
    issuer: [Object: null prototype] {
      C: 'Q',
      ST: 'W',
      O: 'E'
    },
......
```

Replacing all occurances of `A.B.C.D` into a domain name for the above steps won't cause any error.

I've tried making TLS connection to the HTTPS server both on Archlinux and Windows 10, neither of which works. The nodejs version I tried is `v12.10.0`

**Comment by bnoordhuis** [comment]
Node.js _only_ looks at IP address Subject Alternative Names when the hostname is an IP address. You need to add a `subjectAltName = IP:A.B.C.D` stanza to your config file.

**Comment by gnaggnoyil** [comment]
Thanks! Confirmed adding a `subjectAltName = IP:A.B.C.D` to the certificate made it work not only in openssl and curl but also in Node.js. Is this behavior a feature by design? AFAIK there aren't any hints about this behavior in the documentation of Node.js's `tls` module.
