### ISSUE TITLE
Memory leak in http example docs?

### ISSUE THREAD

**Issue by Antti-Kaikkonen** [nodejs/help#2181]
* **Node.js Version**: v10.16.3
* **OS**: ubuntu 16.04
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http

Nodejs [docs](https://nodejs.org/api/http.html#http_http_request_url_options_callback) include the following example:

```js
const postData = querystring.stringify({
  'msg': 'Hello World!'
});

const options = {
  hostname: 'www.google.com',
  port: 80,
  path: '/upload',
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Content-Length': Buffer.byteLength(postData)
  }
};

const req = http.request(options, (res) => {
  console.log(`STATUS: ${res.statusCode}`);
  console.log(`HEADERS: ${JSON.stringify(res.headers)}`);
  res.setEncoding('utf8');
  res.on('data', (chunk) => {
    console.log(`BODY: ${chunk}`);
  });
  res.on('end', () => {
    console.log('No more data in response.');
  });
});

req.on('error', (e) => {
  console.error(`problem with request: ${e.message}`);
});

// Write data to request body
req.write(postData);
req.end();
```
I'm using the http module in a similiar way but getting out of memory error after millions of requests. I noticed that the req 'error' listener doesn't get removed after a successful request. Should the error listener be removed automatically or manually in res.on('end') listener? Is this missing from the example in the docs?

**Comment by Hakerh400** [comment]
> I'm using the http module in a **similiar** way

How much similar? Please post the exact code you're using. I'm unable to reproduce any memory leak using the sample script from the docs.

> Should the error listener be removed automatically or manually in `res.on('end')` listener? Is this missing from the example in the docs?

Once the `req` object is [garbage collected](https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)), all listeners are implicitly removed. You're probably doing something else in a wrong way.

**Comment by Antti-Kaikkonen** [comment]
> Once the req object is garbage collected, all listeners are implicitly removed. You're probably doing something else in a wrong way.
I didn't know that it can something can get garbage collected if there is listeners attached. I now think that I'm probably just doing too many concurrent requests and the requests can be very large.

Thank you for quick response!
