### ISSUE TITLE
exec(command) need to preserve colors

### ISSUE THREAD

**Issue by ankitmobiuso** [nodejs/help#2183]
Hello, I need help with 

`exec(command` preseving colors

the command I am passing is `ng build TestLibrary` 

```
const buildAngularProject = exec(command,
    (error, stdout, stderr) => {
//end



// use event hooks to provide a callback to execute when data are available: 
buildAngularProject.stdout.on('data', (data) => {
    console.log(data);
});
```

here I want to show the colors. I tried to find it but unable to get any hints.

**Comment by robertblackwell** [comment]
try adding an option object to the exec call with {stdio : "inherit"} something like 
= exec(command, {stdio : 'inherit'}, (error, stdout, stderr) => {}
this worked for me in an app where I was calling execSync()

**Comment by dholakiyaankit** [comment]
@robertblackwell  thanks, I will take a look.

**Comment by tniessen** [comment]
The behavior depends on whether stdout/stderr are TTY streams (e.g., a console) or not (e.g., a file or piped into a nother process). Most applications do not output colors on non-TTY streams. Inheriting the file descriptors for stdout/stderr should resolve the issue. Please let us know if you need further assistance.
