### ISSUE TITLE
[HELP] [ExpressJS] patch returns 400 bad request

### ISSUE THREAD

**Issue by aprilmintacpineda** [nodejs/help#2184]
* **Version**: v12.10.0
* **Platform**: Darwin Aprils-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
* **Subsystem**: (Sorry, don't know what to put here...)

This issue was migrated from ExpressJS repository https://github.com/expressjs/express/issues/4054 

![image](https://user-images.githubusercontent.com/21032419/64915816-83f42480-d7a2-11e9-81e5-1783f78a52c2.png)

**server.js**

```js
app.patch('/api/test', () => {
  console.log('hit');
});
```

**frontend**

```js
fetch('/api/test', {
  method: 'patch'
});
```

POST, PUT, GET all works well though...

express^4.17.1

I think I may be doing it incorrectly, I can't find any instructions as to how I should handle patch requests...

**Comment by wide4head** [comment]
Can you try this in server.js
`app.patch('/api/test', (req, res) => {
  console.log('hit');
});`

**Comment by aprilmintacpineda** [comment]
I just tried it out now, it's throwing the same error.

**Comment by lamilsage** [comment]
Hi, I'm getting the exact same error.
node version : v12.19.1
express version : 4.17.1

Any news on it ?

**Comment by RedYetiDev** [comment]
This is an issue with Express, not Node.js, I'm closing this issue.
