### ISSUE TITLE
Application hangs periodically when using request.pipe in Node.js

### ISSUE THREAD

**Issue by bhanukayapa** [nodejs/help#2185]
Hi all,

Recently I added a new function which acts as a proxy to my application since i need to consume some 3rd party endpoints with some authorization headers from my front-end UI. What I did is I added a new controller to my Node.js back-end which dynamically creates the URL according to the parameters it receives and makes requests to this 3rd part and pipe the response to the response stream of my controller function. It works perfect. But since I introduced this new feature, my application began to hang/stuck periodically(like once a week). Application is loading. But does not work as expected. The requests I send to this 3rd party always get stuck. No useful log is printed in the log. Start, requestDetails and stop logs print as usual. But no data receiving! Once I restart the application, all work as expected! But again this will happens about after a week! Here is the proxy function I used.
`
var contentRetriever = function (req, res) {

      logger.info('ContentRetriever() - start');
      var contentURL = 'some base url' + req.params.url;
		
      var requestDetails = {
        method: 'GET',
        url: contentURL,
        headers: {//Some auth headers}
      };

      logger.info('Request details :', requestDetails);
      request(requestDetails).pipe(res);
      logger.info('ContentRetriever() - stop');
}
`
Node Version - 0.10.35v (Unfortunately I cannot upgrade this due to some dependencies)
npm libraries involved to function - express, request
Deployed platform - AWS EC2 - Ubuntu 16.04 LTS
Enough RAM and HDD spaces is allocated to the application. (

I also tried to replicate this scenario in a lower environment by triggering 1000 requests using a for loop for debugging purposes. Still no luck. 

I just need to know the impact that can cause from the usage of request().pipe function here. Because that function is highly used within my application. I have around 1000 users in my application and 2 Node.js application servers to handle the load.

There is a thumbnail on my GUI on top of every page in the application. Every time this thumbnail loads, that request go through the proxy function I have showed above. Thumbnail size is less than 1MB in most of the cases. 

Appreciate if someone can help me out here. Thanks in advance.

**Comment by Hakerh400** [comment]
> Node Version - 0.10.35

That version was [EOL](https://en.wikipedia.org/wiki/End-of-life_(product)) 5 years ago. It is highly unlikely that anyone can help you with that.

**Comment by bhanukayapa** [comment]
I just need to know the impact that can cause from the usage of request().pipe function here.

**Comment by ORESoftware** [comment]
its probably just because the response does not get received from the remote server

**Comment by bhanukayapa** [comment]
Thanks for the reply @Hakerh400 . But I checked with the remote server URL every time I get this error. It was working fine.

**Comment by PoojaDurgad** [comment]
@bhanukayapa - is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
