### ISSUE TITLE
Disable report?

### ISSUE THREAD

**Issue by bzmlxos** [nodejs/help#2186]
* **Node.js Version**: v12.10.0
* **OS**: windows/linux
* **Scope (install, code, runtime, meta, other?)**: report
* **Module (and version) (if relevant)**: process

Hello

How am I supposed to disable diagnostic reporting? When my code encounters a fatal error, a file named "report.***.json" is created where *** is current date or something like that. How to disable this feature?

There is documentation: https://nodejs.org/api/report.html and as I understand it is disabled by default, right? I didnt pass any command line arguments and the file is still appearing on fatal error (like out of memory). I also tried to pass "--experimental-report" and then set "process.report.reportOnFatalError = false;" but still without luck. The report file is always generated when application crashes with fatal error.

**Comment by mhdawson** [comment]
@gireeshpunathil can you take a look at this one?

**Comment by bzmlxos** [comment]
Please move the conversation to https://github.com/nodejs/node/issues/29601
