### ISSUE TITLE
napi addon - call_js function and lifetime management of napi_value instances

### ISSUE THREAD

**Issue by robertblackwell** [nodejs/help#2188]
* **Node.js Version**: 11.9.0
* **OS**:OSX 10.14.2
* **Scope (napi addon using C++ )**:
* **Module (and version) (if relevant)**:

I am writing a node addon using the napi api (via node-api.h) as well as the C++ wrapper in node-addon-api. The addon passes back a stream of events from a worker thread to javascript callback. It all seems to work and I am sure the lifetimes of all my own C++ objects are correctly managed .
However I am not sure how to manage the lifetime of the napi_values I create in my call_js function. Here is the code for my call_js function
```cpp
void WorkerThread::CallJs(napi_env env, napi_value callback, void* context, void* data)
{
    std::cout << "Worker::CallJs : [" << std::hex << context << "] data : [" << std::hex << data << "]" << std::endl;
    Event *event = (Event*)data;
    
    napi_value recv;
    napi_value args[2];
    CHECK(napi_get_null(env, &recv) == napi_ok);
    std::stringstream stream;
    stream << std::hex << this->_thread;
    std::string result( stream.str() );
    Napi::String type = Napi::String::New(env, this->_type);
    Napi::String thread = Napi::String::New(env, result);
    Napi::String timestamp = Napi::String::New(env, this->_time_stamp);
    Napi::Object obj = Napi::Object::New(env);
    obj["type"] = type;
    obj["thread"] = thread;
    obj["timestamp"] = timestamp;
   args[0] = obj;

    CHECK(napi_call_function(env, recv, callback, 1, args, &recv) == napi_ok);
}  
``` 
should I be creating a napi_callback_scope around the napi_value instances being created here.? Or maybe something else I have entirely missed. What makes sure that these 4 napi_value dont get collected while or before the callback runs?

**Comment by mhdawson** [comment]
The first question is if you are making N-API/node-addon-api calls on a thread other than the main thread.  If so then you need to look at either AsyncWorker or The Thread-safe Function Calls APIs: https://nodejs.org/dist/latest-v12.x/docs/api/n-api.html#n_api_asynchronous_thread_safe_function_calls

**Comment by gireeshpunathil** [comment]
@robertblackwell - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
