### ISSUE TITLE
Unable to Publish libraries in nexus using NPM

### ISSUE THREAD

**Issue by ruchithakur** [nodejs/help#2189]
* **Node.js Version**: 4.12.0
* **OS**: Linux
Nexus version :2.10
While im trying to publish npm libraries via jenkins jobs to nexus , Libraries are not uploading but nexus but it's present in jenkins workspace.

I'm getting below error in nexus repositories:
404 - Path /@test_job/ not found in group repository "npm-all" [id=npm-all].
Path /@test_job/ not found in group repository "npm-all" [id=npm-all].

**Comment by gireeshpunathil** [comment]
@ruchithakur - node version 4.12 is long out of support. Could you use latest from here? https://nodejs.org/

**Comment by gireeshpunathil** [comment]
inactive, closing; pls re-open if this is outstanding
