### ISSUE TITLE
how to install nodejs in linux

### ISSUE THREAD

**Issue by zhangzlili** [nodejs/help#219]
I have downloaded node-v4.4.7.tar.gz and decompressed on my shared hosted web server. Then, how can I install it?

**Comment by rvagg** [comment]
@zhangzlili you've downloaded the source file which will require compiling. You should grab the file that has "linux" in it that matches your architecture (x64, x86, arm, arm64?) and uncompress that. The files inside, one level in, could be placed in /usr/local/, often a `tar zxvf --strip-components=1 -C /usr/local <file.tar.gz>` does the trick (although it leaves some README and other files in /usr/local which you might want to clean up).

Alternatively, just use the NodeSource Linux distributions which work on most popular Linux distributions via your package manager, see https://github.com/nodesource/distributions for that.

**Comment by zhangzlili** [comment]
After decompressing it, how can I install it?

**Comment by bnoordhuis** [comment]
Untar it to a directory of your liking, then run `$dir/bin/node`or `$dir/bin/npm`.
