### ISSUE TITLE
.gitignore file in package removed when installed

### ISSUE THREAD

**Issue by pdcavaco1** [nodejs/help#2191]
* **Version**: v12.6.0
* **Platform**: Darwin C02YR412LVDQ 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
* **Subsystem**:

To reproduce:

`mkdir test`
`cd test`
`npm init -f`
`touch .npmignore`
`touch .gitignore`
Set package.json to:
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "files": [
    ".npmignore",
    ".gitignore"
  ]
}
```
`npm pack`
The .gitignore is present in the geneated tgz file
`cd ..`
`mkdir test_install`
`cd test_install`
`npm init -f`
`npm install ../test/test-1.0.0.tgz`
`ls -a node_modules`
There will not be a .gitignore in the node_modules folder

Is it possible to get the .gitignore to survive installation?

**Comment by addaleax** [comment]
This is an issue with npm, not with Node.js. I don’t know why npm isn’t extracting that file, but you may find that https://npm.community/ is a better place to get answers to those kinds of questions.

**Comment by pdcavaco1** [comment]
Thanks Anna I'll try there.

**Comment by sam-github** [comment]
https://docs.npmjs.com/files/package.json#files --- not possible, to my knowlege.
