### ISSUE TITLE
how to replicate async.eachLimit with vanilla promises

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2192]
I am on Node.js 12 on a Mac...

I have this question:
https://stackoverflow.com/questions/58035623/how-to-use-vanilla-node-js-to-run-500-requests-20-in-parallel

basically, I have this vanilla Node.js code:

```js
    const http = require('http');
    
    const host = 'example.com';
    const path = '/';
    
    let i = 0;
    
    const run = () => {
      
      console.log(i++);
      
      return new Promise(resolve => {
        
        const req = http.request({host, path}, res => {
          res.pipe(process.stdout);
          res.once('end', resolve);
        });
        
        req.end();
        
      });
      
    };
    
    async function doall() {
      for (let i = 0; i < 50; i++) {
        await Promise.all(new Array(10).fill(null).map(run));
      }
    }
    
    const now = Date.now();
    
    console.log('Starting up.');
    
    doall().then(_ => {
      console.log('done after:', Date.now() - now, 'millis');
    });
```

this works - it runs 50 sets of 10... except the problem is that, all 10 complete, then the next 10 start, then the next 10 complete. So there are moments when 0 requests are in progress, between each set.

Is there some way using vanilla Node.js and promises to replicate `async.eachLimit(new Array(500), 20, ...)`?

**Comment by addaleax** [comment]
```js
async function runner(items, fn) {
  while (items.length > 0)
    await fn(items.pop()) ;
}

async function eachLimit(items, fn, limit) {
  Promise.all([...Array(limit)].map(() => runner(items, fn)));
}
```

Does that work for you?

**Comment by ORESoftware** [comment]
maybe, what is `fn`?

**Comment by addaleax** [comment]
An async function that takes one `item` from the list as an argument and processes it.

**Comment by PoojaDurgad** [comment]
@ORESoftware - is this still an issue? were you able to follow @addaleax 's suggestion?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
