### ISSUE TITLE
simple node.js server hiccups (long pauses) upon speed test

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2193]
I am on node.js version 12.6.0:

I have this simple http server:

```js
const http = require('http');

const s = http.createServer((req, res) => {
  
  setTimeout(() => {
    res.end('OK');
  }, Math.random() * 10)
  
});

s.listen(3000);
```

and then I have this vanilla node.js code requiring no external dependencies to speed test the server:

```js
const http = require('http');

const host = 'localhost';
const path = '/';
const port = 3000;

let i = 0;

const makeRequest = () => {
  
  console.log(i++);
  
  return new Promise(resolve => {
    
    const req = http.request({host, path, port}, res => {
      res.pipe(process.stdout);
      res.once('end', resolve);
    });
    
    req.end();
    
  });
  
};

const run = (v) => {
  
  v.count++;
  v.total++;
  
  if (v.total > v.max) {
    return;
  }
  
  return makeRequest().then(_ => {
    v.count--;
    
    if (v.count < v.concurrency) {
      return run(v);
    }
  });
};

async function doall() {
  
  const v = {
    count: 0,
    total: 0,
    max: 5000,
    concurrency: 15
  };
  
  return Promise.all(new Array(v.concurrency).fill(null).map(_ => {
    return run(v);
  }));
  
}

const now = Date.now();

console.log('Starting up.');

doall().then(_ => {
  console.log('done after:', Date.now() - now, 'millis');
});
```

the behavior I see is that the server will pause for up to 5 or 6 seconds sometimes, in the middle of processing the 5000 requests. These seem like very long pauses, I cannot figure out why it happens.

I see this behavior on Node.js 10, 11 and 12, so I don't think it has to do with Node.js, so not sure what's up with it, it's not my code TMK, such a long pause and then a recovery doesn't make sense for my code.

**Comment by tamlyn** [comment]
I was seeing something similar in an Express.js server running on Kubernetes. It turned out to be resource limits being set too low. Upping `resources.limits.cpu` for the containers resolved the problem.

**Comment by gireeshpunathil** [comment]
@ORESoftware - is this still happening? I am unable to recreate in my mac box. If it is a pressing issue for you even in the latest versions, let me know; I can dig a little more.

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.

**Comment by jonaskello** [comment]
@tamlyn Thank you! I had the exact same scenario but did not think of resources in k8s :-)
