### ISSUE TITLE
Nobjs

### ISSUE THREAD

**Issue by edd04** [nodejs/help#2194]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by edd04** [comment]
/usr/local/lib/nodejs

**Comment by yorkie** [comment]
@edd04 May I ask you to describe the details about your question?

**Comment by edd04** [comment]
> * **Node.js Version**:
> * **OS**:
> * **Scope (install, code, runtime, meta, other?)**:
> * **Module (and version) (if relevant)**:
