### ISSUE TITLE
utf-8 character isnt showed

### ISSUE THREAD

**Issue by deltreemassive** [nodejs/help#2199]
node.js version:12.10.0
os:windows 10
scope:code
module:ı haven't a module

'use strict';
var http = require('http');
var port = process.env.PORT || 1337;

http.createServer(function (req, res) {
    res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end('Gökhan topal\n');
}).listen(port);

this is default visual studio 2019 start code I only changed "res.end('Gökhan topal\n');" this part.and it is showed G�khan topal   how can I solve this problem.thank you for your helps

**Comment by Hakerh400** [comment]
> it is showed G�khan topal how can I solve this problem

Where is it shown like that? If it is shown only in VS code editor, then it is not related to Node.js. If the problem occurs in a browser, which browser? I tested using Chrome, Firefox, IE, Edge and works properly.

**Comment by deltreemassive** [comment]
in chrome. and ı tested in firefox.result is the same

**Comment by deltreemassive** [comment]
how can I solve this problem?

**Comment by deltreemassive** [comment]
yes.this solved my problem.thank you
