### ISSUE TITLE
How to specify the timezone when spawn a child process

### ISSUE THREAD

**Issue by zhaoyu0810** [nodejs/help#220]
Hi team,

When spawn a child process, how to specify the timezone?

- According to [this thread](https://groups.google.com/forum/#!topic/nodejs/s1gCV44KYrQ), the TZ (timezone) environment variable is valid.
- According to [the spawn API](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options), we can pass in environment variables to child process.

I tried below code, while it doesn’t work. The child process timezone is not changed. Could you suggest?

```
var childprocess = require("child_process");

console.log((new Date()).getTimezoneOffset()); // 420

childprocess.spawn(
  process.execPath,
  ["date.js"],
  { env:{ TZ: "Europe/Amsterdam" } }
 ).stdout.on('data', (data) => {
  console.log(data.toString());
});
```

date.js:
`  console.log((new Date()).getTimezoneOffset()); // 420
`

**Comment by addaleax** [comment]
Unfortunately, your test case does work for me (with other time zones, I’m already in `Europe/Amsterdam` ;))… can you give some more information, e.g. Node.js version, OS, etc.?

**Comment by zhaoyu0810** [comment]
Thank you for taking care of this issue. I'm using windows 10 Enterprise, 64-bit system+ nodejs 6.2.2

console.log(process.arch); // x64
console.log(process.version); // v6.2.2

**Comment by bnoordhuis** [comment]
@zhaoyu0810 See [this page](https://msdn.microsoft.com/en-us/library/90s5c885.aspx), the TZ environment variable has a different format on Windows.

**Comment by zhaoyu0810** [comment]
Thanks @bnoordhuis , @addaleax!! You are right, Windows is using different TZ format. Below code works well for me now.

```
var childprocess = require("child_process");

console.log((new Date()).getTimezoneOffset()); // 420
childprocess.spawn(
  process.execPath,
  ["date.js"],
  { env:{ TZ: "28800" } }
 ).stdout.on('data', (data) => {
  console.log(data.toString());
});
```

date.js:
`console.log((new Date()).getTimezoneOffset()); // 480 `
