### ISSUE TITLE
Only node.exe is installed when downloading installer

### ISSUE THREAD

**Issue by Isabella-Pham** [nodejs/help#2202]
* **Node.js Version: 10.16.3**
* **OS: Windows**
* **Scope: Install**

node.js installer not working. A pop up appears saying "preparing to install" but nothing appears after that. When checking program files, only node.exe is installed. ~10 minutes later a another pop up appears saying "Installer no longer responding". Tried installing using scoop in Windows Powershell but ran into troubles as well.

**Comment by gireeshpunathil** [comment]
cc @nodejs/platform-windows

**Comment by tniessen** [comment]
Which Windows version and architecture are you using? This command should work on most systems to find the relevant information:

```
wmic os get Caption,CSDVersion,Version,BuildNumber,OSArchitecture
```

**Comment by gireeshpunathil** [comment]
ping @Isabella-Pham

**Comment by Isabella-Pham** [comment]
Hi! I recently tried redownloading it again and it worked, thank you.
