### ISSUE TITLE
Help with Node Please

### ISSUE THREAD

**Issue by Derektvann** [nodejs/help#2204]
I have a problem getting this to work file name : index.js

```javascript
const express = require(‘express’);
const bodyParser = require(‘body-parser’);
const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.listen(3000, () => console.log(‘Webhook server is listening, port 3000’));
```

but when I type `node index.js`, this is what I get....

```
Dereks-iMac:msgbot derekvann$ node index.js
/Users/derekvann/Desktop/msgbot/index.js:1
const express = require(‘express’);
                        ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by ORESoftware** [comment]
you are likely using an older node.js version, whereby it doesn't recognize the `const` keyword.

when you type `node -v` in the terminal, what do you get?

to install a newer version of node.js on a non-windows machine, I recommend [NVM](https://github.com/nvm-sh/nvm).

**Comment by ORESoftware** [comment]
on this note @bnoordhuis  it would be kinda neat to display the node.js version in all node.js stacktraces, at the end. think about how much time this would save users debugging etc, and on online messsage boards.

**Comment by Derektvann** [comment]
I have Version 10.16.3
is that too old?

**Comment by bruce-one** [comment]
That version should support `const`.

It is possible that the quotes you have are not `'` but instead are another character.

Could you try replacing the quotes (eg rewriting them or replacing with double quotes) to see whether that resolves the issue?

The quotes on all the lines look they are `’` rather than `'`. This is a common issue if copying from sites like Medium which can replace quotes with the "nicer looking" alternatives.

**Comment by tniessen** [comment]
@bruce-one is right, you are using some fancy unicode quote characters instead of "normal" single-quotes. If you replace them, it should work.

**Comment by han-so1omon** [comment]
I am having this same error, but it only occurs when splitting a string into multiple lines. When the string is in one line the error goes away.

Error example:
```
'String 1
is this string
';
```

Correct example:
```
'String 2 is this string';
```

This is using nodejs v12.13.1

**Comment by tniessen** [comment]
@han-so1omon That's intentional. If you want line feeds, use the `\n` escape sequence:

```
'String 1\nis this string\n';
```
