### ISSUE TITLE
Using Visual C++ MFC with node addon api

### ISSUE THREAD

**Issue by pospich0815** [nodejs/help#2207]
* **Node.js Version**: 10.16.3
* **OS**:  Windows 10 Pro, V1903
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I have a C++ project which is using Visual C++ MFC Components and I want to create a node addon from this project to use it in an electronjs project. 
I have written a test project with the necessary cpp files and an extra wrapper class like in the node addon api examples. It compiles without any error and builds the _.node_ file. 
But when I want to use the addon in my electronjs project _require_ can't open it. 

When I try this with a simple example without any MFC components all works fine.

Is it possible to use MFC with node addon api?

**Comment by gireeshpunathil** [comment]
> But when I want to use the addon in my electronjs project require can't open it.

what is the error you are getting? is there a callstack / error message?

are you building the addon as a `win 32 console dll` ? or a `win32 windows dll`?

**Comment by pospich0815** [comment]
`Error: Cannot find module 

\\?\Path\To\MyProject\build\Release\myAddon.node`

This is the message I get. I want to use this in an electron app. 

I have build the addon as a x64 dll.

**Comment by gireeshpunathil** [comment]
ok, thanks for the info. I would suggest to debug this further by:
 - opening the build configuration,
 - copying the compiler / linker flags that are used for building the dll,
 - comparing it with the working set (simple example without any MFC components),
 - incrementally adding / removing flags until you converge to one of more offending flags

and then we can look at the documentation to see what the implication of that flag etc. and then take it from thereon.

does it make sense to you ?

**Comment by pospich0815** [comment]
Ok, that make sense, thank you. But I can try this on next monday at the earliest. I will give you feedback.

**Comment by pospich0815** [comment]
So... I have checked the compiler flags and found that there is an issue that the `cflags!` and `cflags_cc!` regions in the binding.gyp file will be ignored during compiling. I have found a solution to add the compiler flag for precompiled headers that I need for MFC components. 

`        'msvs_settings': {
          'VCCLCompilerTool': { 'AdditionalOptions': [ '/Yc', '/Yustdafx.h' ] }
        },`

I have added this section to the gyp file. But now there is a build error which says that the `stdafx.pch` file can not be found. I think this file must me create by the compiler with the `/Yc` flag.

**Comment by gireeshpunathil** [comment]
IIUC from https://docs.microsoft.com/en-us/cpp/build/reference/yc-create-precompiled-header-file?view=vs-2019 , `/Yc<filename>` create the pre-compiled header, while `/Yu<filename>` consumes it. So do you have a `/Ycstdafx.h` somewhere in the options list?

**Comment by pospich0815** [comment]
Yes, sorry that was wrong. I have forgott the name of the header after the `/Yc`. But now there is the next problem. I have included the stdafx.h in all of my cpp files, but there is a cpp file "_win_delay_load_hook.cc_" which is added to the "to compile list" in the vcxproj file automaticaly. It is located under `..\nodejs\node_modules\npm\node_modules\node-gyp\src`. 
The Error is that the afxwin.h header file cannot be opened during the compiling of this file. I cannot add the `#include stdafx.h` to this because it is a nodejs package file. And I have all necessary include directories in my .gyp file. Do you know what this file is for and is it possible to compile the project without this file?

**Comment by gireeshpunathil** [comment]
can you once try disabling the pre-compilation altogether, with `/Y-` option?
ref: https://docs.microsoft.com/en-us/cpp/build/reference/y-ignore-precompiled-header-options?view=vs-2019

after all, precompiled headers is an optimization, so does not influence anything in the final object code.

**Comment by gireeshpunathil** [comment]
at this point let me also cc @nodejs/platform-windows to see if there are better recommendations

**Comment by pospich0815** [comment]
Without the precompiled header options, the project builds without any error. But the problem with the builded addon persists. The `require` - function can't open the addon.

**Comment by richardlau** [comment]
The `win_delay_load_hook` is for things like electron that aren't called `node`, see https://electronjs.org/docs/tutorial/using-native-node-modules#a-note-about-win_delay_load_hook.

**Comment by gireeshpunathil** [comment]
ping @pospich0815 - is this still outstanding?

**Comment by pospich0815** [comment]
Sorry, I had no time to work on this problem the last few weeks. So yes, it is outstandig and I will work further on this problem shortly.

**Comment by PoojaDurgad** [comment]
@pospich0815, is this still outstanding?

**Comment by pospich0815** [comment]
Yes, this is still outstanding. We haven't found any solution for this Problem and switched to another technology.

**Comment by Craigzyc** [comment]
For anyone in the future here looking for a solution for this. node-activex has stdafx.h included in an addon and working. 
See https://github.com/durs/node-activex

**Comment by ej-toita** [comment]
what you should do when you face this problem, i believe, is to add the following to your gyp file:

```
      'msbuild_settings': {
        'ClCompile': {
          'PrecompiledHeaderFile': "<(module_root_dir)/.../stdafx.h",
        },
      },
```
