### ISSUE TITLE
Node.exe used by Adobe Creative Cloud Experience repetitively does Full Domain User enumeration

### ISSUE THREAD

**Issue by Warlord711** [nodejs/help#2213]
* **Node.js Version**: 6.12.3
* **OS**: Win 10 
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**:

While investing in an issue with a client system that does domain user enumeration every 30 seconds for like 30 Minutes after going online, I found that the node.exe is doing massive LDAP enumeration targeting  both domain controllers and clients at is seems.

I checked the file integrity, it's unaltered, digitally signed and passed virustotal.com scan.
Why does the node.exe need to enumerate all domain users every 30 seconds ?

**Comment by bnoordhuis** [comment]
By whom is the executable signed? Adobe? If that's the case you should direct your question to them because they're probably distributing a modified copy of node.

**Comment by Warlord711** [comment]
No, signed by Node.js

Ben Noordhuis <notifications@github.com> schrieb am Mo., 30. Sept. 2019,
15:04:

**Comment by bnoordhuis** [comment]
Okay, but what script is it executing? Node.js itself is just a runtime, much like .NET or the JVM.

**Comment by vweevers** [comment]
@Warlord711 The script is in `%ProgramFiles(x86)%\Adobe\Adobe Creative Cloud Experience\js\main.js` (or similar, check the arguments passed to `node.exe`) and can be freely inspected. In the version that I'm looking at there's - among other things - a native addon that integrates with Adobe IMS which in turn uses LDAP. That would be my bet. In any case, it's not Node.js that's doing the LDAP enumeration.

**Comment by Warlord711** [comment]
Yes I came to same result. We reimaged the system and it did not happened
on the system again. If one system behave different than all other, format
and reinstall is the quickest solution.

Vincent Weevers <notifications@github.com> schrieb am Sa., 19. Okt. 2019,
15:09:

**Comment by vweevers** [comment]
Good to close, then.
