### ISSUE TITLE
new Date (year,month,day) incorrect on Windows 10

### ISSUE THREAD

**Issue by andyfripp** [nodejs/help#2214]
* **Node.js Version**: Version 10.0.18362.356
* **OS**: Microsoft Windows 10, Version 10.0.18362.356
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: n/a

On Windows 10, both the Windows native binary and a Ubuntu binary, under Windows Subsystem For Linux, construct dates incorrectly:

> new Date(1995,3,1)
1995-03-31T23:00:00.000Z  
> new Date(1995,3,2)
1995-04-01T23:00:00.000Z

both are a day out, whereas under Linux with the same version of node.js the result is correct:

> new Date(1995,3,1)
1995-04-01T00:00:00.000Z
> new Date(1995,3,2)
1995-04-02T00:00:00.000Z

However, strangely, for later months such as November, it is correct (on Windows 10):

> new Date(1995,10,1)
1995-11-01T00:00:00.000Z
> new Date(1995,10,2)
1995-11-02T00:00:00.000Z

Any ideas?

**Comment by andyfripp** [comment]
Ok, it's a summertime timezone issue, but strange that I get a different answer running the Date constructor using node within a Cmd shell under WIndows 10 than I do from javascript in Chrome on the same machine.

**Comment by bnoordhuis** [comment]
I don't know what Chrome does but for node, the presence (or absence) of the TZ environment variable affects how dates are formatted.
