### ISSUE TITLE
node and npm dont working pls help 

### ISSUE THREAD

**Issue by noah512** [nodejs/help#2215]
i try create react app in visual stideo code when i tybe on terminal create react app . 
it shows :  TypeError: Cannot read property 'loaded' of undefined

PS C:\Users\nur alamo\dropbox\code_prod\REACT_CRASH-TODO> npx create-react-app . Error: EISDIR: illegal operation on a directory, read TypeError: Cannot read property 'loaded' of undefined at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27) at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3) at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:77:20 at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22) at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24 at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7 at Array.forEach () at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13 at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25) at finalize (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:189:14) C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98 var doExit = npm.config.loaded ? npm.config.get('_exit') : true ^

TypeError: Cannot read property 'loaded' of undefined at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27) at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3) at process.emit (events.js:198:13) at process._fatalException (internal/bootstrap/node.js:496:27) Command failed: C:\"Program Files"\nodejs\node.exe "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" config get cache --parseable Error: EISDIR: illegal operation on a directory, read TypeError: Cannot read property 'loaded' of undefined at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27) at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3) at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:77:20 at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22) at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24 at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7 at Array.forEach () at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13 at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25) at finalize (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:189:14) C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98 var doExit = npm.config.loaded ? npm.config.get('_exit') : true ^

TypeError: Cannot read property 'loaded' of undefined at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27) at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3) at process.emit (events.js:198:13) at process._fatalException (internal/bootstrap/node.js:496:27)

**Comment by mfaheemakhtar** [comment]
Hey @noah512 , 

What happens if you try `npx create-react-app react-crash-todo`? Are you getting the same error?

**Comment by honorableisrael** [comment]
Hi i am experiencing the same with setting up a new react application issue at the moment what can be done.

**Comment by PoojaDurgad** [comment]
@noah512 - were you able to follow @mfaheemakhtar 's suggestion?  @honorableisrael - is this still an issue? 
for me this issue looks similar to https://github.com/facebook/create-react-app/issues/6512 , hopefully this may help you to resolve the issue.

**Comment by PoojaDurgad** [comment]
inactive. closing!!
