### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by KaranBE** [nodejs/help#2216]
<--- Last few GCs --->

[6688:00000265CEB76EB0] 410012252 ms: Mark-sweep 6722.7 (8352.3) -> 6721.8 (8352.8) MB, 190.6 / 0.1 ms  (average mu = 0.142, current mu = 0.035) allocation failure scavenge might not succeed
[6688:00000265CEB76EB0] 410012447 ms: Mark-sweep 6729.3 (8352.8) -> 6728.3 (8353.8) MB, 188.4 / 0.1 ms  (average mu = 0.092, current mu = 0.035) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000013D3D55C5C1]
Security context: 0x0109c2e1e6e9 <JSObject>
    1: /* anonymous */ [0000036CDAD21C49] [C:\socketserver\app-mafDemo1.js:~979] [pc=0000013D401BC959](this=0x00ea4c18d5e1 <JSGlobal Object>,element=0x01b68fec5f79 <String[28]: /report#wucZY-c2bt0ll457AHBA>,i=20)
    2: arguments adaptor frame: 3->2
    3: forEach [00000109C2E06DF1](this=0x036cdad20831 <JSArray[442]>,0x036cdad21c49 <JSFunction (sfi = 00000...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7EC8CF04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF7EC8AA0C6 node::MakeCallback+4518
 3: 00007FF7EC8AAA30 node_module_register+2032
 4: 00007FF7ECB320EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7ECB3201F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7ED052BC4 v8::internal::Heap::MaxHeapGrowingFactor+9556
 7: 00007FF7ED049C46 v8::internal::ScavengeJob::operator=+24310
 8: 00007FF7ED04829C v8::internal::ScavengeJob::operator=+17740
 9: 00007FF7ED050F87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF7ED051006 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF7ECC0CBE8 v8::internal::Factory::AllocateRawArray+56
12: 00007FF7ECC0D562 v8::internal::Factory::NewFixedArrayWithFiller+66
13: 00007FF7ECC83A3F v8::internal::HashTable<v8::internal::NumberDictionary,v8::internal::NumberDictionaryShape>::KeyAt+51007
14: 00007FF7ECC76F32 v8::internal::HashTable<v8::internal::NumberDictionary,v8::internal::NumberDictionaryShape>::EntryToIndex+80050
15: 00007FF7ECD1BE90 v8::internal::InterpreterDispatchDescriptor::InitializePlatformIndependent+1696
16: 00007FF7ECD1D425 v8::internal::InterpreterDispatchDescriptor::InitializePlatformIndependent+7221
17: 00007FF7ECD1D265 v8::internal::InterpreterDispatchDescriptor::InitializePlatformIndependent+6773
18: 00007FF7ECCD7241 v8::internal::wasm::WasmInterpreter::Thread::Step+99441
19: 00007FF7ECCD78A0 v8::internal::wasm::WasmInterpreter::Thread::Step+101072
20: 0000013D3D55C5C1

**Comment by bnoordhuis** [comment]
Moving to nodejs/help because it's likely an issue with your application, not node itself.

**Comment by gireeshpunathil** [comment]
pls try increasing your JS heap limit by `--max-old-space-size=X` where X is in megabytes

**Comment by PoojaDurgad** [comment]
@KaranBE - were you able to follow @gireeshpunathil 's suggestion? or is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
