### ISSUE TITLE
Having problem pulling numeric value from .ENV file.

### ISSUE THREAD

**Issue by uclnj** [nodejs/help#2217]
Trimmed down .env file:
PORT = 4000
JWTKEY = "somekey"
JWTEXPIRES = 600

server.js
const port = process.env.PORT - this works, the server starts on port 4000

user.auth.js
        const token = jwt.sign({ 'id': user.id
        }, process.env.JWTKEY, { <--- that works, the key is pulled from the ENV file
            algorithm: 'HS256',
            expiresIn: process.env.JWTEXPIRES <---this fails
        })
console.debug(`${process.env.JWTEXPIRES}`)

Node.js Version: 10.16.3
OS: Winblows 10
Scope: Code
Module (and version) (if relevant): dotenv

Started pulling values out of code to put in ENV file - the port # and key string all work but when I put JWTEXPIRES into the jwt sign method, the JWT key is signed to expire immediately.  If I manually type in the # 600 it works as expected.  The console.debug also prints "600" out.  Even surrounding the 600 in quotes does nothing.

**Comment by Hakerh400** [comment]
According to the [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) documentation, if the `expiresIn` is a number, it is treated as seconds, but if it is a string, it is parsed as [zeit/ms](https://github.com/zeit/ms) format. If the string consists of a single number, the number is treated as milliseconds, then it is divided by 1000 and rounded down - for 600 it gives 0, as documented.

Process environment variables are always strings. To solve this problem, convert the value to integer by adding `| 0` operator:

```js
expiresIn: process.env.JWTEXPIRES | 0
```

**Comment by ORESoftware** [comment]
try using JSON in your env file

```
json_conf='{"num": 42, "bool": true}'
```

**Comment by gireeshpunathil** [comment]
or even
```js
expiresIn: +process.env.JWTEXPIRES
```
?

**Comment by jnach** [comment]
Hit an identical problem today and solved by appending `| 0`, thank you, @Hakerh400

**Comment by PoojaDurgad** [comment]
resolved issue. closing!!

**Comment by inctnce** [comment]
This helped:
```javascript
Number(String(process.env.JWTEXPIRES))
```

**Comment by Xairoo** [comment]
I am using parseInt: https://jsbench.me/pokty2hchw/1

**Comment by StefanWW** [comment]
> or even
> 
> ```js
> expiresIn: +process.env.JWTEXPIRES
> ```
> 
> ?

Love this, but how does it work? @gireeshpunathil
