### ISSUE TITLE
How to read environment variable from windows in node.js ?

### ISSUE THREAD

**Issue by kumaresan-subramani** [nodejs/help#2220]
* **Node.js Version**: 10.16.3
* **OS**: 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

### Is there any way to read environment variable which is set in windows like below:

![env](https://user-images.githubusercontent.com/36756050/66252757-c1821700-e77c-11e9-8904-669dec59593c.PNG)

### This is my requirement, in here I want to read above-mentioned variables values:

https://stackoverflow.com/questions/58236303/run-gulp-task-after-npm-package-install-without-any-command?noredirect=1#comment102845830_58236303

### tagchange.js
```
var fs = require('fs');
var oldtag = process.env.oldtag;
var newtag = process.env.newtag;
var glob = require('glob');
 
require('dotenv').config()

console.log(process.env);

var files = glob.sync('./@syncfusion/*');
 
 for (var i = 0; i < files.length; i++) {
 var sourceFile = fs.readFileSync(files[i],'utf8');
 sourceFile = sourceFile.replace(`selector: '[ejs-button]'`,`selector: '[Kumar-button]'`);
// sourceFile = sourceFile.replace(oldtag,newtag);
 fs.writeFileSync(files[i], sourceFile, 'utf8');
 }

```

### package.json
```
  "dependencies": {
    "postinstall": "*"
  },
  "scripts": {
    "postinstall": "node ./tagchange.js",
    "packagr": "ng-packagr -p ng-package.json && gulp npmrc-changelog-schematics-injection && gulp path-change"
  }
```

**Comment by Hakerh400** [comment]
What is the problem you're experiencing? This should work just fine

```js
oldtag = process.env.oldtag;
newtag = process.env.newtag;
```

**Comment by kumaresan-subramani** [comment]
It throws error like:


Process.env.oldtag is undefined

**Comment by addaleax** [comment]
@kumaresan-subramani Sharing the full error, possibly including a stack trace, might be helpful.

**Comment by kumaresan-subramani** [comment]
Hi @addaleax ,

Sorry, here you can find my error. please see below screenshot:

![asdf](https://user-images.githubusercontent.com/36756050/66287430-6d4d7300-e8f3-11e9-9646-acbe1d0f696a.PNG)

**Comment by kumaresan-subramani** [comment]
While trying below command, I can able read variables:

> SET oldtag=[ejs-button,ejs-chart] && SET newtag=[kumar-button,kumar-chart] && npm i @syncfusion/ej2-angular-buttons

### tagchange.js file

```
var fs = require("fs");
var glob = require("glob");

var oldtag = process.env.oldtag;
var newtag = process.env.newtag;

console.log(`Your oldtag is ${oldtag}`);
console.log(`Your newtag is ${newtag}`);


var files = glob.sync("./@syncfusion/*");

for (var i = 0; i < files.length; i++) {
  var sourceFile = fs.readFileSync(files[i], "utf8");
  sourceFile = sourceFile.replace(
    `selector: '[ejs-button]'`,
    `selector: '[Kumar-button]'`
  );
  // sourceFile = sourceFile.replace(oldtag,newtag);
  fs.writeFileSync(files[i], sourceFile, "utf8");
}
```

### ouptut

```
D:\today\check834>SET oldtag=[ejs-button,ejs-chart] && SET newtag=[kumar-button,kumar-chart] && npm i @syncfusion/ej2-angular-buttons

> @syncfusion/ej2-angular-buttons@17.3.14 postinstall D:\today\check834\node_modules\@syncfusion\ej2-angular-buttons
> node ./tagchange.js

Your oldtag is [ejs-button,ejs-chart]
Your newtag is [kumar-button,kumar-chart]
+ @syncfusion/ej2-angular-buttons@17.3.14
updated 1 package and audited 25918 packages in 22.258s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

D:\today\check834>

```

**Comment by addaleax** [comment]
> if i written like below: it shows all refer below content

That makes it seem like it’s more an issue with setting the environment variable than with reading it?

**Comment by kumaresan-subramani** [comment]
Sorry @addaleax , i cant understand

**Comment by addaleax** [comment]
@kumaresan-subramani It sounds like the environment variables aren’t actually set when you run the Node.js code. So you *are* reading them correctly, they’re just not there to begin with.

Why that is, I don’t know. Maybe somebody with more Windows expertise will give an answer, but it doesn’t seem to be related to Node.js itself.

**Comment by kumaresan-subramani** [comment]
okay @addaleax , THanks for your fast and nice reply. i will close this issue now.

**Comment by Amrkamel1** [comment]
@kumaresan-subramani 
did you manage to solve this issue, im facing same one

**Comment by kumaresan-subramani** [comment]
> @kumaresan-subramani
> did you manage to solve this issue, im facing same one

Yes i have resolved like below:
https://github.com/nodejs/help/issues/2220#issuecomment-538876427

but this command wont work in lastest Vs code terminal

**Comment by Amrkamel1** [comment]
@kumaresan-subramani  im using intellij did u find any issue

**Comment by njevdjo** [comment]
Try to run script with user "KumaresanSubramani" or define variable as system one.

![image](https://user-images.githubusercontent.com/4265234/81966067-396cc580-9619-11ea-9feb-e3795a45cd1b.png)

**Comment by Amrkamel1** [comment]
resolved, i just had to restart the editor every time i change the env

**Comment by MrSharpp** [comment]
> resolved, i just had to restart the editor every time i change the env

Thanks Buddy. It really helped me!

**Comment by EmptyBox-Design** [comment]
Is there a better method where you don't have to restart the editor to see the updated system environmental variable?

**Comment by feliceferri** [comment]
Same problem, closing and re-opening VS Code worked for me as well.

Thank you!

**Comment by anas1149** [comment]
The reason why this was happening was that the current terminal session in vscode did not get updated env variable or something along those lines ?
