### ISSUE TITLE
Stop JSON.parse on condition.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [nodejs/help#2221]
* **Version**: latest
* **Platform**: any
* **Subsystem**:

https://github.com/ibmruntimes/yieldable-json/issues/19#issuecomment-538639182

how we should stop json.parse process?

let obj = {a:1, b:2, c:[1,2,3], d:[{a:1},{b:1,a:1}]};
let str = JSON.stringify(obj);
let max = 5, i=0;
let c = JSON.parse(str, function(key, value){
if(++i>max)throw new Error('message');//will this stop parse process in v8?
if(++i>max) return undefined;//or will this stop parse process?
return value;
});

i need json.parse in future will be cleared by gc and destructor called in engine.

**Comment by gireeshpunathil** [comment]
@afwn90cj93201nixr2e1re - is this resolved?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
