### ISSUE TITLE
Identify what the default browser is

### ISSUE THREAD

**Issue by oonqt** [nodejs/help#2226]
* **Node.js Version**: 10.16.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: N/A
* **Module (and version) (if relevant)**: N/A

Hi, I'm looking for a package or a way to identify the default application on windows. Specifically, I'm looking for a way to identify what the default browser is set for Windows. I know I can OPEN something in the default browser, but I don't know HOW I can identify what browser that actually is (ex: chrome, firefox, edge)

I found [this](https://github.com/sindresorhus/default-browser) which is everything I need, except it's lacking windows support:

**Comment by Hakerh400** [comment]
Try this:

```js
const defaultBrowser =
  require('child_process').execSync(`
    reg query HKEY_CURRENT_USER\\Software\\Classes\\http\\shell\\open\\command
  /ve`.replace(/\s/g, ' ')).toString().trim().split(/\t|\s{2,}/).pop().
  match(/".*?"|\S+/)[0].replace(/"/g, '');

console.log(defaultBrowser);
```

**Comment by gireeshpunathil** [comment]
closing as answered
