### ISSUE TITLE
Searching nodejs.org

### ISSUE THREAD

**Issue by PaulBags** [nodejs/help#2229]
Hi, there's no search on nodejs.org? And the docs index doesn't have what I'm looking for. And searching site:nodej.org <term> isn't helping, I'm guessing the docs aren't spidered properly?

Just looking for docs on the built in Promise module.

**Comment by devsnek** [comment]
Promises are part of JavaScript, not Node.js. You can find documentation about them here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by PaulBags** [comment]
This doesn't include Promise.promisify?

**Comment by tniessen** [comment]
@PaulBags I assume you mean `util.promisify`? Anyway, searching for `site:nodejs.org promisify` on Google should give you the correct result instantly, so I don't see a need for a built-in search feature.

**Comment by gireeshpunathil** [comment]
closing as answered; pls re-open if there is anything outstanding here

**Comment by lobsterkatie** [comment]
I'd request that this be reopened. Sure, one can scope google down to the node site and then run a search, but why should users have to do that? Search is, IMHO, one of the very most basic features of any docs. It's always been baffling (and frustrating) to me that the node docs don't have it.

**Comment by gireeshpunathil** [comment]
@nodejs/website - pls evaluate and share your opinion.
@lobsterkatie - are you willing to implement one, if a feature request is accepted by the team?

**Comment by Trott** [comment]
Duplicate of https://github.com/nodejs/nodejs.org/issues/4064

**Comment by PaulBags** [comment]
Heh, much better asked.. but two years later and this is the dupe?

Oh well, quality wins. Closing.

**Comment by lobsterkatie** [comment]
@gireeshpunathil - No, I unfortunately don't have the bandwidth right now. I'll subscribe to that other issue for updates, though, thanks!
