### ISSUE TITLE
This result is correct or bug?

### ISSUE THREAD

**Issue by uxitten** [nodejs/help#2230]
Please see this picture:

![Screen Shot 2019-10-14 at 4 27 20 PM](https://user-images.githubusercontent.com/1549069/66753048-becfa200-ee9f-11e9-8e29-89562b8df826.png)

**Comment by Hakerh400** [comment]
JavaScript stores all numbers as double-precision binary [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) floating point values. Each number is internally stored on 64 bits: 1 bit for sign, 52 for mantissa and 11 for exponent. Given that it has limited number of bits available, it can therefore represent only a limited number of different values. Integers are just a small subset of that.

The maximal integer you can safely represent (without losing the precision) is `Number.MAX_SAFE_INTEGER`, whose value is `9007199254740991`. You are trying to represent `123456789012345678`, which is larger than max safe integer, so you lost precision. That is expected.

To solve the problem, you can use [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) (simply add `n` to the end of your number).

**Comment by gireeshpunathil** [comment]
closing as answered
