### ISSUE TITLE
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203.

### ISSUE THREAD

**Issue by Generousjo** [nodejs/help#2231]
**The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203.

Help me plz**

**Comment by Generousjo** [comment]
Why closed?

**Comment by fivdi** [comment]
Did this error occur while attempting to install Node on Windows?
If so, [this](https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/error-code-2203-when-trying-to-install-a-program/a1461ca8-f0fd-406d-ae91-c3afc4cf22ce) may help.

**Comment by gireeshpunathil** [comment]
@Generousjo - is this still outstanding?

**Comment by PoojaDurgad** [comment]
@Generousjo - is this still an issue ? did @fivdi 's suggestion help you to resolve the issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
