### ISSUE TITLE
`const` declaration causes side-effect issues

### ISSUE THREAD

**Issue by EnriqueCano12** [nodejs/help#2233]
* **Version**: v10.16.3
* **Platform**: Darwin Kernel Version 17.7.0 x86_64
* **Subsystem**:

Running the following code from the command prompt gives wrong results:
```
$ cat test.js 
const a = () => {
	return [[],[]]
}
let b,d
const c = 'hi'
[b,d] = a()
console.log(b)
console.log(d)
console.log(c)

$ node test.js 
undefined
undefined
[ [], [] ]
```
Moving the const definition to the top of the line gives the right result:
```
$ cat test.js 
const c = 'hi'
const a = () => {
	return [[],[]]
}
let b,d
[b,d] = a()
console.log(b)
console.log(d)
console.log(c)

$ node test.js 
[]
[]
hi
```
Adding a semicolon at the end of the const definition also gives the right result:
```
$ cat test.js 
const a = () => {
	return [[],[]]
}
let b,d
const c = 'hi';
[b,d] = a()
console.log(b)
console.log(d)
console.log(c)

$ node test.js 
[]
[]
hi
```

Feature or defect?

**Comment by BridgeAR** [comment]
This is working as expected. The automatic semicolon insertion is not always perfect. In case the following line contains a possible valid addition, it's interpreted as a single statement.
It has nothing to do with `const` but the fact that `'hi'\n[variable]` is a legit way of accessing string entries. So it "assigns" the result of `a()` to `'hi'[undefined]` (`b,d` evaluates to `undefined`). The return value of that is the actual result and that is saved in c.
