### ISSUE TITLE
Add a link to Downloads page regarding recommended Windows install on Linux subsystem

### ISSUE THREAD

**Issue by mattwojo** [nodejs/help#2234]
* **Node.js Version**: ALL
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: Install

Windows is recommending that Node.js be installed on WSL2 (the subsystem for Linux, running the latest version of Ubuntu) for an optimal experience doing Node.js development.

Could this link be added to the Downloads page links? (https://nodejs.org/en/download/)  

- [Install Node.js via the Windows subsystem for Linux (WSL2)](https://docs.microsoft.com/windows/nodejs/setup-on-wsl2)

This is a MUCH more happy path for anyone using Node.js on Windows!

**Comment by fivdi** [comment]
A better repository for this suggestion is https://github.com/nodejs/nodejs.org

I made a similar suggestion to add an "Unoffical builds" link to the download page with [this issue](https://github.com/nodejs/unofficial-builds/issues/3) and was asked to make [this PR](https://github.com/nodejs/nodejs.org/pull/2216) at https://github.com/nodejs/nodejs.org.

**Comment by mattwojo** [comment]
Thanks @fivdi! Closing my issue here and just moved it over there: https://github.com/nodejs/nodejs.org/issues/2684
 :) Appreciate the assist!
