### ISSUE TITLE
how to run ESLint (including running rules on commit messages) in Node core?

### ISSUE THREAD

**Issue by aug2uag** [nodejs/help#2236]
for new contributors who are unfamiliar with subsystem names and linting rules is there a way to run the linting tests for the code and commit messages in isolation?

it doesn't seem `make -j4 tests` runs those, would it also be worthwhile to add those checks to the tests suite?

**Comment by bnoordhuis** [comment]
`make lint`

There are specialized lint rules like `lint-js` and `lint-cpp`:
```
$ grep ^lint Makefile 
lint-md-rollup:
lint-md-clean:
lint-md-build:
lint-md: | tools/.mdlintstamp
lint-js-fix:
lint-js:
lint-js-ci:
lint-cpp: tools/.cpplintstamp
lint-addon-docs: tools/.doclintstamp
lint-py-build:
lint-py:
lint-py:
lint: ## Run JS, C++, MD and doc linters.
lint-ci: lint-js-ci lint-cpp lint-py lint-md lint-addon-docs
lint:
lint-ci: lint
lint-clean:
```

> it doesn't seem make -j4 tests runs those

It should. What's the output you get?

**Comment by aug2uag** [comment]
@bnoordhuis i didn't get any errors and the CI would fail, i thought they were intentionally left out and this is very helpful! Thank you.

Should I close this issue? Please let me know if you would like me to open an issue for running the lint tests in `make -j4 tests`

**Comment by richardlau** [comment]
Commit message linting isn't part of the makefile lint targets as those targets must be able to run outside of a git checkout (e.g. from an extracted source tarball). 

The commit message linting is done by running [`core-validate-commit`](https://github.com/nodejs/core-validate-commit). The CI runs it via https://github.com/nodejs/node/blob/master/tools/lint-pr-commit-message.sh (which assumes you have a PR opened).

**Comment by aug2uag** [comment]
thank you @richardlau

should the other lints (e.g. lint-md) run as part of the makefile?

**Comment by richardlau** [comment]
They are run as part of `make test`.

**Comment by aug2uag** [comment]
Incredible. Thank you.
