### ISSUE TITLE
having problems running node on a chromebook

### ISSUE THREAD

**Issue by fcc366** [nodejs/help#2239]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by ORESoftware** [comment]
I don't think you can install node.js on a chromebook, (you won't have access to terminal, etc)

**Comment by fcc366** [comment]
Ok well I found out this chromebook has its own terminal its called crosh. I need to know how to use it like a website or something. Amd how to make a directory inside terminal and clone a repo from github

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 17, 2019 at 3:16 PM, Operations Research Engineering Software+<notifications@github.com> wrote:   
I don't think you can install node.js on a chromebook, (you won't have access to terminal, etc)

**Comment by tniessen** [comment]
I don't think git or node or npm or anything else will work on the default operating system, but you might be able to install a different operating system on the Chromebook, e.g., Ubuntu.

**Comment by gireeshpunathil** [comment]
ping @fcc366 - anything pending here?

**Comment by PoojaDurgad** [comment]
@fcc366 - is this still an issue? looks like this can be closed now . please let me know if that is not the case.

**Comment by PoojaDurgad** [comment]
inactive. closing!!
