### ISSUE TITLE
compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 73 (with Electron)

### ISSUE THREAD

**Issue by trusktr** [nodejs/help#2240]
* **Node.js Version**: 12.12.0
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: dependency compiliation
* **Module (and version) (if relevant)**:

No matter how I rebuild (I've tried `npm rebuild` and `npx electron-rebuild` to no avail), I always end up with

```
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module
```

The dependency being compiled is `zeromq`.

But I don't even see a `73` on the [ABI releases list](https://nodejs.org/en/download/releases/). Is this even possible? What does this mean?

Any ideas what is going on or what to investigate?

**Comment by richardlau** [comment]
`NODE_MODULE_VERSION 73` is for electron: https://github.com/nodejs/node/blob/c8df5cf74a2b495ccbc8b25a29c1692391c505f3/doc/abi_version_registry.json#L9

**Comment by trusktr** [comment]
Ok, I see, the Node.js website doesn't list ABI versions for Electron. Someone had to point me to the list on GitHub. Totally not obvious!

So looks like I need to use electron-rebuild, so I'll open an issue on Electron.
