### ISSUE TITLE
readStream.on("close") appears to end an http response

### ISSUE THREAD

**Issue by prettydiff** [nodejs/help#2241]
* **Node.js Version**: 12.10.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: fs and http

I am creating a fs.createReadStream as follows:

```javascript
let readStream = fs.createReadStream("my/file/path.txt");
readStream.setEncoding("utf8");
readStream.pipe(response); // response is an http response object declared earlier
console.log(response.finished); // false
readStream.on("close", function () {
    console.log(response.finished); // true
    response.write("some text"); // error here, cannot write to a closed response
    response.end();
});
```

Does node automatically end an http response on the close of a read stream?

**Comment by addaleax** [comment]
> Does node automatically end an http response on the close of a read stream?

When using `.pipe()`, if the source finishes successfully, the destination will also be ended. You can turn this off by [passing the `{ end: false }` option to `.pipe()`](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options).

**Comment by prettydiff** [comment]
That is exactly what I needed!
