### ISSUE TITLE
NODE_MODULE_VERSION 69 does not officially exist

### ISSUE THREAD

**Issue by roguexiaohuihui** [nodejs/help#2249]
**error message:**
“node-pty\build\Release\pty.node”
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**In the development of vscode plug-in, the node-pty module was introduced, and then the spawn method was called to report the error**

![image](https://user-images.githubusercontent.com/22930711/67351988-5bb9cb80-f581-11e9-98ee-e37c13584fa7.png)

![image](https://user-images.githubusercontent.com/22930711/67351913-2e6d1d80-f581-11e9-8324-601dd985a91c.png)

I checked the official version number, but I couldn't find 69

**Comment by PoojaDurgad** [comment]
@roguexiaohuihui - were you able to follow @richardlau 's suggestion ?or is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
