### ISSUE TITLE
MSVC and GCC use different mangling algorithm for exported C++ functions.

### ISSUE THREAD

**Issue by Iruora** [nodejs/help#2250]
MSVC and GCC use different mangling algorithm for exported C++ functions.
To fix that, add `extern "C"` in header files and disable safe exception handlers in MSVC.
See [this](https://github.com/Hakerh400/node-gyp-windows-staticlib/commit/a19085e2e12f0bb12dae274880a4e19ed7e3133a)

_Originally posted by @Hakerh400 in https://github.com/nodejs/help/issues/1788#issuecomment-466447566_

**Comment by tniessen** [comment]
The issue is unclear to me as well, but I assume that @Iruora was hoping for that gyp configuration. Closing as answered.
