### ISSUE TITLE
Docker Ubuntu installing from source npm issue.

### ISSUE THREAD

**Issue by truestblue** [nodejs/help#2252]
v14.0.0-pre
Ubuntu 18.04.3 LTS (Bionic Beaver)
Install

When installing node from source in an ubuntu docker image, npm gives the following warnings:
```npm WARN npm npm does not support Node.js v14.0.0-pre
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12, 13.
npm WARN npm You can find the latest version at https://nodejs.org/
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN You are using a pre-release version of node and things may not work as expected
```

Dockerfile looks like this:
```
FROM ubuntu:latest
ENV NODE_BASE=/home/node
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -yqq
RUN apt-get install bison \ 
        lbzip2 \
        vim \
        git \ 
        python \
        gdb \
        sudo \
        tzdata \
        pkg-config \
        gperf \
        curl \
        libc++-dev \
        libc++abi-dev \
        bzip2 \ 
        gcc \
        make \
        lsb-release \ 
        g++ \
        flex -y

RUN git clone https://github.com/nodejs/node.git $NODE_BASE
WORKDIR $NODE_BASE

RUN ./configure
RUN make -j4 
RUN make install
```

**Comment by gireeshpunathil** [comment]
@truestblue - first, thank you for sharing your Dockerfile, this is awesome, and can be used as a reference material for anyone who wants to build node in containers!

coming to the issue itself - I think it is known - when you build from master, the node's version string will be `+1` to the last release, and a `+.-pre` - in this case, `v14.0.0-pre`.

https://github.com/nodejs/node/blob/71bcd05232b4fc21db20e5acf019f97780050568/deps/npm/lib/utils/unsupported.js#L3-L11 defines the list of supported node versions, and https://github.com/nodejs/node/blob/71bcd05232b4fc21db20e5acf019f97780050568/deps/npm/lib/utils/unsupported.js#L43 performs the check. In this case, `v14` is not in the list and hence the warning.

My assertion is that `make install` from master is prone to this warning, always.

I may be wrong to, so pinging @nodejs/npm to double confirm.

**Comment by truestblue** [comment]
Ah @gireeshpunathil Thank you. 
Typically I would have used wget to grab a tar from dist repo, but for building v8 within node it seems to need to be a git repository. Seems like a simple checkout of a previous npm supported release should work.

**Comment by gireeshpunathil** [comment]
> but for building v8 within node it seems to need to be a git repository

pinging @nodejs/v8 to see if we get an explanation to why that is required. IMO that kind of defeats the purpose of distribution tar balls.

**Comment by truestblue** [comment]
@gireeshpunathil 
Sure, maybe I'm missing something and they can help me out.

Dockerfile:
```FROM ubuntu:latest
ENV NODE_VERSION=node-v13.0.1
ENV NODE_BASE=/home/${NODE_VERSION}
ARG DEBIAN_FRONTEND=noninteractive
ENV PATH="/usr/local/bin/node:${PATH}"
ENV NODE_PATH="/usr/local/bin/node"

RUN apt-get update && apt-get upgrade -yqq

RUN apt-get install bison \ 
        lbzip2 \
        vim \
        git \ 
        python \
        gdb \
        sudo \
        tzdata \
        pkg-config \
        gperf \
        curl \
        libc++-dev \
        libc++abi-dev \
        bzip2 \ 
        gcc \
        make \
        lsb-release \ 
        g++ \
        wget \
        flex -y

WORKDIR /home/

RUN wget http://nodejs.org/dist/latest-v13.x/node-v13.0.1.tar.gz; \
        tar zxvf node-v13.0.1.tar.gz

WORKDIR $NODE_BASE

ENV PATH="/home/node/deps/v8/_depot_tools:${PATH}"
RUN make v8

RUN ./configure; \
        make -j4; \
        make install; 
```

Docker build fails duing v8/tools/node/fetch_deps.py (This doesn't happen when cloned from git):

```
tools/make-v8.sh x64.release 
+ BUILD_ARCH_TYPE=x64.release
+ V8_BUILD_OPTIONS=
+ cd deps/v8
+ tools/node/fetch_deps.py .
Cloning into '/home/node-v13.0.1/deps/v8/_depot_tools'...
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
fatal: not a git repository (or any of the parent directories): .git
Checking out depot_tools.
Using depot tools in /home/node-v13.0.1/deps/v8/_depot_tools
Traceback (most recent call last):
  File "tools/node/fetch_deps.py", line 101, in <module>
    FetchDeps(sys.argv[1])
  File "tools/node/fetch_deps.py", line 75, in FetchDeps
    temporary_git = EnsureGit(v8_path)
  File "tools/node/fetch_deps.py", line 56, in EnsureGit
    actual_git_dir = git("rev-parse --absolute-git-dir")
  File "tools/node/fetch_deps.py", line 53, in git
    "git " + args, cwd=v8_path, shell=True).strip()
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'git rev-parse --absolute-git-dir' returned non-zero exit status 128
Makefile:292: recipe for target 'v8' failed
```

**Comment by gireeshpunathil** [comment]
ok, 2 things:

1. `ENV PATH="/home/node/deps/v8/_depot_tools:${PATH}"`: why are you doing this? the path is wrong anyways I guess, `node` should be `node-v13.0.1`?

2. `RUN make v8` : we don't need to do this step? the next step `make -j4` takes care of building `v8` too.


So in summary, can you try removing these two steps and try?

**Comment by gireeshpunathil** [comment]
with those changes, I am able to build node successfully. Please see the trail below (captured in a second run so that only the highlights are shown):

```
#docker build -t t2252 .
Sending build context to Docker daemon   2.56kB
Step 1/12 : FROM ubuntu:latest
 ---> 2ca708c1c9cc
Step 2/12 : ENV NODE_VERSION=node-v13.0.1
 ---> Using cache
 ---> 6a880e54e475
Step 3/12 : ENV NODE_BASE=/home/${NODE_VERSION}
 ---> Using cache
 ---> 6c6ccf8d1048
Step 4/12 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 6aa5e84681ca
Step 5/12 : ENV PATH="/usr/local/bin/node:${PATH}"
 ---> Using cache
 ---> 4da44d6d0919
Step 6/12 : ENV NODE_PATH="/usr/local/bin/node"
 ---> Using cache
 ---> ef07b674ee93
Step 7/12 : RUN apt-get update && apt-get upgrade -yqq
 ---> Using cache
 ---> 844438c2bb49
Step 8/12 : RUN apt-get install bison         lbzip2         vim         git         python         gdb         sudo         tzdata         pkg-config         gperf         curl         libc++-dev         libc++abi-dev         bzip2         gcc         make         lsb-release         g++         wget         flex -y
 ---> Using cache
 ---> 90e4e0fd8c66
Step 9/12 : WORKDIR /home/
 ---> Using cache
 ---> b1ea4032525e
Step 10/12 : RUN wget http://nodejs.org/dist/latest-v13.x/${NODE_VERSION}.tar.gz;         tar zxvf ${NODE_VERSION}.tar.gz
 ---> Using cache
 ---> 84f3d255672d
Step 11/12 : WORKDIR $NODE_BASE
 ---> Using cache
 ---> 1fe52ac863bc
Step 12/12 : RUN ./configure;     make -j4;     make install;
 ---> Using cache
 ---> 830d299677ac
Successfully built 830d299677ac
Successfully tagged t2252:latest
#docker run -it t2252 bash
root@7a820e07f264:/home/node-v13.0.1# ./node -v
v13.0.1
root@7a820e07f264:/home/node-v13.0.1# 
```

So in summary, remove those two lines in the previous comment, and we are through.

Hope this helps.

**Comment by truestblue** [comment]
@gireeshpunathil so are you saying the recipe for 'make v8' just doesn't work and that's fine? Also, the path is necessary for what I'm doing because I use gclient. Running make -j4 compiles node with v8, but does not pull the dependencies that allow me to run tools within v8. (which I need, this is a condensed Dockerfile that removes all of my projects work). 

I realized it is by design that it needs to be a git tree:
```.PHONY: v8
# Related CI job: node-test-commit-v8-linux
# Rebuilds deps/v8 as a git tree pulls its third-party dependencies, and
# builds it.
v8:
        tools/make-v8.sh $(V8_ARCH).$(BUILDTYPE_LOWER) $(V8_BUILD_OPTIONS)```

I guess my question is just why the tarball removes the files necessary to run the v8 make command.

**Comment by ryzokuken** [comment]
👋 @nodejs/v8 here!

> but for building v8 within node it seems to need to be a git repository

Not surprising at all, actually, git would likely not suffice either, and you should ideally have depot_tools (https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up) in order to build V8 from source?

**Comment by gireeshpunathil** [comment]
@ryzokuken - thanks. Unfortunately, I guess the OP's question is still outstanding:

> I guess my question is just why the tarball removes the files necessary to run the v8 make command.

i.e., why node packager decides to purge those files, leading to this situation. This does not look like to be the case with master. Only pre-packaged tarballs suffer from this!

**Comment by targos** [comment]
Node.js does not officially support building V8 from the tarball. The `make v8` target is here for us to run V8 tests in our CI.

**Comment by truestblue** [comment]
Thanks @targos 
Closing-- seems like all behavior is expected.
