### ISSUE TITLE
Transform stream not outputting any lines

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2256]
* **Node.js Version**: 12.9
* **OS**:  Ubuntu

I have this project
https://github.com/ORESoftware/line-stream-parser

You can clone and install and run it with:

```shell
npm install
npm run tsc
node dist/test.js
```

```typescript
'use strict';

import LineParser from './main';
import {Transform} from "stream";

const t = new Transform({
  transform(chunk, enc, cb){
    cb(null, Buffer.from([Buffer.from('prepend:'),chunk]));
  }
});

t.pipe(new LineParser()).on('data', l => {
  console.log('line:', String(l));
});

const input = [
  'abc',
  '\n',
  'def\nghijk\nlmnop',
  '\nqrstu',
  '\nvwxyz'
];

for(const line of input){
  // console.log('t:', line)
  t.write(Buffer.from(line));
}

t.end();

```

when I run the above, all I get is:

```
line:
```

just 1 empty line of ouptut. Can anyone help me figure out why?

**Comment by bmuenzenmeyer** [comment]
This question is idle and left unanswered for years now.

- Does the behavior persist if you upgrade to a new version of Node.js? This reported version is [end of life](https://github.com/nodejs/release#release-schedule).
- Have you attempted to ask this question within other communities, such as [stackoverflow](https://stackoverflow.com/questions/tagged/node.js?tab=Newest)?

I am going to circle back in a couple weeks to see if we can close as no-longer relevant.

**Comment by bmuenzenmeyer** [comment]
closing per the above plan
