### ISSUE TITLE
fs: fs.writeFile not truncating file content well or throws an error in a concurrent writes.

### ISSUE THREAD

**Issue by Akumzy** [nodejs/help#2257]
* **Version**: `12.13.0`
* **Platform**: `Linux akuma 4.15.0-66-generic nodejs/node#75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* **Subsystem**: `fs`
With the code below 
```js
const fs = require('fs')
const path = require('path')

const filePath = path.join(__dirname, 'text.txt')
fs.existsSync(filePath) && fs.unlinkSync(filePath)

const one = async () => {
    fs.writeFile(filePath, `[one] Hello World\n`.repeat(2), err => {
        if (err) {
            console.error(err)
        }
    })
}

const two = () => {
    fs.writeFile(filePath, `[two] Hello World\n`, err => {
        if (err) {
            console.error(err)
        }
    })
}
one()
two()
setTimeout(() => { }, 2000)

```
I was expecting the content of `text.txt` file to be either 
```txt
[one] Hello World
```
or
```txt
[two] Hello World
```
or better an error indicating a write conflict but none of that happened rather what I saw was this
```txt
[two] Hello World
[one] Hello World
```

Going through the documentation again I came across this warning

> It is unsafe to use fs.writeFile() multiple times on the same file without waiting for the callback. For this scenario, fs.createWriteStream() is recommended.

And clearly I was passing in a callback. So I don't know if this is an expected behaviour.

**Comment by bnoordhuis** [comment]
Moved and reopened. To answer your question: node.js (well, libuv) uses a thread pool for file operations. Those two requests run in separate threads, i.e., concurrently and in parallel.

There's no reliable way for them to detect they'll be writing to the same file, they just hand off the data to the operating system and the OS then acts as it sees fit.

**Comment by Akumzy** [comment]
Is it possible to referenced this issue in the documentation as one of the unexpected behaviour?

For example:
> It is unsafe to use fs.writeFile() multiple times on the same file without waiting for the callback [see issue](https://github.com/nodejs/help/issues/2257#event-2751491000) For this scenario, fs.createWriteStream() is recommended.

**Comment by addaleax** [comment]
@Akumzy It’s possible, but could you explain why it would be helpful? It’s not like there’s a guarantee that other people will see the same behaviour as you.

**Comment by Akumzy** [comment]
@addaleax the explanation given by @benjamingr [here](https://github.com/nodejs/help/issues/2257#issuecomment-547343498) can  be beneficial to others that are curious like me.

**Comment by benjamingr** [comment]
@Akumzy did you mean to tag Ben? 

In any case - I warmly recommend checking our [guides](https://nodejs.org/en/docs/guides/) and in particular those under "Node.js core concepts". They touch on these things :]

**Comment by Akumzy** [comment]
Ooh sorry, yes I did meant to tag Ben.
