### ISSUE TITLE
fs.writeFileSync inside a loop 

### ISSUE THREAD

**Issue by JavierPons** [nodejs/help#2258]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by JavierPons** [comment]
Node.js : 12.8.0
macOS Catalina 10.15

I´m  trying to write a file with data using fs.writeFileSync and after that Im running child_process with spawn  inside a loop. 

The loop runs three times. The output is always three with the data of the last written code via fs.writeFileSync. So, the loop write automatically  the three different files and it doesn't give time to spawn to do each time what is order/code.

How I can do that first fs.writeFileSync write a file and run first child_process with first data and after another write and run and so on?

Here below part of the code.

The code is inside a loop and it runs well. It should create three different output with the different data.  => sumSetting  console.log three different data.
Thank you for your time.

`fs.writeFileSync("./some/settings.json", sumSetting);
      console.log("_____", sumSetting);


      const { spawn } = require("child_process");
      const child = spawn("node", ["app.js", "test/something", "exports/", "test/settings.json"]);

      child.stdout.on("data", childData => {
        console.log("This childData ", childData.toString());
      });
      child.stderr.on("data", childData => {
        console.log("** ", childData.toString());
      });

      child.on("error", err => {
        console.log("ERROR: ", err);
      });
      child.on("close", code => {
        console.log("This close ", code);
      });`

**Comment by addaleax** [comment]
I’m not sure if I’m understanding you correctly, but maybe the issue is that you’re using `fs.writeFileSync()`, which waits until the data to the file is written, but then use `child_process.spawn()`, which creates a child process but doesn’t wait for anything else to finish? It’s hard to tell without actually seeing your code.

Do you run the child processes sequentially, i.e. one after another? Or do you run them in parallel?

**Comment by JavierPons** [comment]
Thank you for your response. I'm running child process sequentially. One after another.

**Comment by JavierPons** [comment]
As well I try with fs.writeFile (url, data, err function). The output is always a object json. When Im running writeFile add a extra "}” to the end. So file become corrupt.

**Comment by JavierPons** [comment]
`const fs = require("fs");

fs.readFile("./test/settings.json", "utf8", (err, data) => {
  try {
    // const testSetting = JSON.parse(data);

    let arrayValues = [[a, b, c, "d", e)], [f, g, h, i, j], [(k, l, m, n, o)]];
    let arrayKey = [1, 2, 3, 4, 5];
    // stringify testSetting
    var newSetting = JSON.parse(data);

    for (var i = 0; i < arrayValues.length; i++) {
      for (var j = 0; j < arrayValues[i].length; j++) {
        var variableString = arrayKey[j];

        // gives keys value  if exist if not keep older value
        newSetting[variableString] = arrayValues[i][j];
        // console.log("newSetting ", newSetting);
        var sumSetting = JSON.stringify(newSetting);

        // writing into testSettings
      }

      fs.writeFileSync("./test/settings.json", sumSetting);
      console.log("_____", sumSetting);

    
      const { spawn } = require("child_process");
      const child = spawn("node", ["app.js", "test/something", "exports/", "test/settings.json"]);

      child.stdout.on("data", childData => {
        console.log("This childData ", childData.toString());
      });
      child.stderr.on("data", childData => {
        console.log("** ", childData.toString());
      });

      child.on("error", err => {
        console.log("ERROR: ", err);
      });
      child.on("close", code => {
        console.log("This close ", code);
      });
    }
  } catch (err) {
    console.log("Error parsing string", err);
  }
});
`

**Comment by JavierPons** [comment]
Thanks Anna. Its solve.

**Comment by addaleax** [comment]
> Thank you for your response. I'm running child process sequentially. One after another.

That’s not what your code says, though. You spawn child processes in parallel, continuing with the loop before the previous child process finished.

You may want to use `child_process.spawnSync()` as a workaround for this, which *will* wait for the child process to finish. If your application is one where not blocking the event loop is important (e.g. a web server), this is not a good idea, but it will work.

Any proper solution would likely involve refactoring your code to use `async` functions, which come with the ability to wait for an asynchronous operation to finish without actually having to block other operations, or some other way to manage asynchronous operations.

**Comment by JavierPons** [comment]
Before I said it works. But it wasn't :(   I used child_process.spawnSync() and now it works well. For this moment is what I need. Maybe in the future using async functions. And It is true my process is in parallel. Many thanks for your time!
