### ISSUE TITLE
Net socket (telnet) crashes on a larger data

### ISSUE THREAD

**Issue by keevitaja** [nodejs/help#226]
```js
"use strict";

const net = require('net');

const socket = net.createConnection(4000, 'aardmud.org', ()=> {    
    socket.pipe(process.stdout);
    process.stdin.pipe(socket);
});

socket.on('error', (error)=> {
    console.log(error);
});
```
This script creates a tcp/telnet connection to the MUD. MUD is a text based telnet RPG game. Now when i send a command (areas) to the server, and the response is like 300 lines long, the script hangs. Also i cannot discover any errors as `error` event is not triggered.

Any idea how to fix this?

There are some dedicated MUD clients (tintin, mush, mudlet etc) which do not have this issue. MUD client is pretty much a sophisticated telnet client.

**Comment by addaleax** [comment]
I get the same behaviour with `nc aardmud.org 4000`, so this is very likely not related to your script (which does look correct).

**Comment by keevitaja** [comment]
@addaleax yeah,  but it does not hang with mud clients like tintin, mush, mudlet ... i posted a note to the service provider. hope they reply

**Comment by keevitaja** [comment]
Got this problem solved. By enabling MCCP (zlib) the data size was shrunk down and problem went away.
