### ISSUE TITLE
Get Readable._readableState.ended using official API

### ISSUE THREAD

**Issue by postatum** [nodejs/help#2265]
* **Node.js Version**: 13.0.1
* **OS**: Linux Mint 18.3 64-bit
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: _stream_readable.js

Hi.
I have a code written at times of Nodejs v0.10- 0.12 (2015) which uses [Readable._readableState.ended](https://github.com/nodejs/node/blob/v13.0.1/lib/_stream_readable.js#L173).

Please advice me on what's the "official way" to get that property value in Node 12-13?

**Comment by tniessen** [comment]
Are you looking for [`readableEnded`](https://nodejs.org/api/stream.html#stream_readable_readableended)?

**Comment by postatum** [comment]
> Are you looking for [`readableEnded`](https://nodejs.org/api/stream.html#stream_readable_readableended)?

Yes, that's probably what I need. Thank you!
