### ISSUE TITLE
prefix -g is not recognized as internal or external command

### ISSUE THREAD

**Issue by ShaiLesh-Haldankar** [nodejs/help#2266]
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.

**Comment by addaleax** [comment]
@ShaiLesh-Haldankar This isn’t an issue with Node.js or with npm, it’s the Windows CLI not being able to parse your command. However, with only the error message, it’s impossible for me to tell what went wrong.

**Comment by DerekNonGeneric** [comment]
Cross-repo issue links seemed to have vanished after the transfer. Re-linking https://github.com/nodejs/help/issues/2642 so as to re-establish.

A couple of commands associated w/ the error message seen here have been identified, which is evident in https://github.com/nodejs/help/issues/2642#issue-605962527.

- From the 1st image, 2nd command: `npm -v`.
- From the 2nd image, 3rd command: `npm install -g @angular/cli`.

**Comment by PoojaDurgad** [comment]
@ShaiLesh-Haldankar - is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
