### ISSUE TITLE
bug in assigning big numbers to variable

### ISSUE THREAD

**Issue by nourziady** [nodejs/help#2268]
* **Version**:v10.16.0
* **Platform**: Darwin MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

Issue is simple as
```
let int = 36028797018963973;
console.log(int) // 36028797018963976
```

how is that?

**Comment by tniessen** [comment]
As @Hakerh400 explained, this is a known deficiency of the `number` type in JavaScript. Representing your number as a binary sequence requires 56 bits, but the JavaScript `number` type cannot represent integers with more than 52 bits accurately. Sadly, the only true integer type provided by JavaScript is `BigInt`.

This is a common problem and appears to have been answered sufficiently.
