### ISSUE TITLE
The date offset in Brazil (America/Sao_Paulo) is incorrect

### ISSUE THREAD

**Issue by hiagodotme** [nodejs/help#2269]
* **Node.js Version**: v10.16.0
* **OS**: Ubuntu 18.04 LTS
* **Scope (install, code, runtime, meta, other?)**: runtime

The date offset in Brazil is incorrect. The javascript offset returns 120 (GMT-0200), the government canceled our daylight saving time. Our time zone still requires offset 180 (GMT-0300) I can't find anything about that. How do I update the time tables?

```js
process.env.TZ = 'America/Sao_Paulo';
console.log(new Date().getTimezoneOffset()); // returning 120 not 180...
```

**Comment by richardlau** [comment]
See https://github.com/nodejs/node/issues/30211. This requires an update to ICU in Node.js (https://github.com/nodejs/node/issues/29540, https://github.com/nodejs/node/pull/30232).

**Comment by PoojaDurgad** [comment]
@hiagodotme - is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
