### ISSUE TITLE
Seems, 'url.parse' isn't working properly

### ISSUE THREAD

**Issue by shunanya** [nodejs/help#227]
**URL**: doesn't matter
**Browser version**: doesn't matter
**Operating system**: Ubuntu 14.x
**Node.js version**: 4.3.1

Seems, 'url.parse' isn't working properly in case when the query string in URL is ended by '&'. 
The parsing contains **blank key with blank value** (see below example)

```
var util = require('util');
var url = require('url');

var u = '/b?/b?&page_rendering_time=544&total_load_time=1735&';
console.log('input: '+u);
var urlObj = url.parse(u, true, true);
console.log(util.inspect(urlObj))
console.log('query: ' + JSON.stringify(urlObj.query))


```

The output of this code is the following

```
input: /b?page_rendering_time=544&total_load_time=1735&
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '?page_rendering_time=544&total_load_time=1735&',
  query: { page_rendering_time: '544', total_load_time: '1735', '': '' },
  pathname: '/b',
  path: '/b?page_rendering_time=544&total_load_time=1735&',
  href: '/b?page_rendering_time=544&total_load_time=1735&' }
query: {"page_rendering_time":"544","total_load_time":"1735","":""}
```

**Comment by bnoordhuis** [comment]
That's because your input is ambiguous, it looks like a file path to url.parse().  Try this:
```
> url.parse('http://www.example.com' + '/b?/b?&page_rendering_time=544&total_load_time=1735&', true, true)
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'www.example.com',
  port: null,
  hostname: 'www.example.com',
  hash: null,
  search: '?/b?&page_rendering_time=544&total_load_time=1735&',
  query: 
   { '/b?': '',
     page_rendering_time: '544',
     total_load_time: '1735' },
  pathname: '/b',
  path: '/b?/b?&page_rendering_time=544&total_load_time=1735&',
  href: 'http://www.example.com/b?/b?&page_rendering_time=544&total_load_time=1735&' }
```

**Comment by shunanya** [comment]
Sorry, but probably you're wrong - the issue is repeated in case of wholly correct URL. 
```
var util = require('util');
var url = require('url');

var u = 'http://www.example.com/b?page_rendering_time=544&total_load_time=1735&';
console.log('input: '+u);
var urlObj = url.parse(u, true, true);
console.log(util.inspect(urlObj))
console.log('query: ' + JSON.stringify(urlObj.query))

```
The output
```
input: http://www.example.com/b?page_rendering_time=544&total_load_time=1735&
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'www.example.com',
  port: null,
  hostname: 'www.example.com',
  hash: null,
  search: '?page_rendering_time=544&total_load_time=1735&',
  query: { page_rendering_time: '544', total_load_time: '1735', '': '' },
  pathname: '/b',
  path: '/b?page_rendering_time=544&total_load_time=1735&',
  href: 'http://www.example.com/b?page_rendering_time=544&total_load_time=1735&' }
query: {"page_rendering_time":"544","total_load_time":"1735","":""}

```

**Comment by kahwee** [comment]
There's indeed a difference of behavior in node v4 and v5/v6.

Behavior in v4:

* Input: `http://www.example.com/b?/b?&page_rendering_time=544&total_load_time=1735&`
* Output: `{ '/b?': '', page_rendering_time: '544', total_load_time: '1735', '': '' }`


Behavior in v5 and v6:

* Input: `http://www.example.com/b?/b?&page_rendering_time=544&total_load_time=1735&`
* Output: `{ '/b?': '', page_rendering_time: '544', total_load_time: '1735' }`

**Comment by shunanya** [comment]
So, now, my question is - will this issue be patched in the next 4.x release? or I should wait for stable 6.x release?

**Comment by bnoordhuis** [comment]
If you can identify the commit or commits that fixed the issue, you can request a backport to v4.  That said, if they haven't been backported already, it's probably because they are considered too risky for the LTS branch.

v6 _is_ stable, by the way.  Or were you thinking of LTS?  The LTS cycle for v6 starts in October.

**Comment by shunanya** [comment]
Thanks for suggestion. I will try to use v6.
