### ISSUE TITLE
gyp verb `which` failed Error: not found: python2

### ISSUE THREAD

**Issue by bobKasbi** [nodejs/help#2270]
I'am using the following versions to run an angular app locally:

Angular CLI: 7.3.9
Node: 12.13.0
OS: darwin x64
Angular: 7.0.2
... animations, common, compiler, compiler-cli, core, http
... language-service, platform-browser, platform-browser-dynamic

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.7
@angular-devkit/build-angular      0.10.7
@angular-devkit/build-optimizer    0.10.7
@angular-devkit/build-webpack      0.10.7
@angular-devkit/core               7.0.7
@angular-devkit/schematics         7.3.9
@angular/cdk                       7.3.7
@angular/cli                       7.3.9
@angular/flex-layout               7.0.0-beta.24
@angular/forms                     7.2.15
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@angular/router                    7.2.15
@ngtools/webpack                   7.0.7
@schematics/angular                7.3.9
@schematics/update                 0.13.9
rxjs                               6.5.3
typescript                         3.1.6
webpack                            4.19.1

But I do have following versions globally:
node: v12.13.0
npm:  6.12.0

Angular CLI: 8.3.8
Node: 12.13.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.8
@angular-devkit/core         8.3.8
@angular-devkit/schematics   8.3.8
@schematics/angular          8.3.8
@schematics/update           0.803.8
rxjs                         6.4.0
    
When I try to run `npm install` I keep getting the following error all the time:
`gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2` and:

`../src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
  v8::String::Utf8Value string(value);
                        ^      ~~~~~
/Users/me/.node-gyp/12.13.0/include/node/v8.h:3046:5: note: candidate constructor not viable: no known conversion from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/me/.node-gyp/12.13.0/include/node/v8.h:3039:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.`

`1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/me/MyWorkSpace/projectName/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/me/MyWorkSpace/projectName/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/me/MyWorkSpace/projectName/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1`

I have been searching on S. Overflow etc. and found some kind of similar issues, but none of suggested fixes did help. Actually it looks to me as it's an issue, when we upgrade to 
node version 12.x. In the other hand, I don't think we must downgrade to version 11 or 10 to fix this. 

Any Fix for this please?

**Comment by PoojaDurgad** [comment]
@bobKasbi - with your issue it looks like you are getting error about python2, to fix this issue probably you need to use python3 to compile native modules.

**Comment by PoojaDurgad** [comment]
inactive. closing!!

**Comment by amroosobhy** [comment]
>  with your issue it looks like you are getting error about python2, to fix this issue probably you need to use python3 to compile native modules.

@PoojaDurgad Can you clarify what to do as I have same error?
