### ISSUE TITLE
Memory usage jumps +100% each 5 minutes and grow over time

### ISSUE THREAD

**Issue by alexandershiltcev-gelato** [nodejs/help#2272]
* **Node.js Version**: 12.13.0
* **OS**: Debian GNU/Linux 9
* **Scope**: runtime
* **Server configuration:** docker container with 4GB of memory and 1 CPU

We have Node JS server doing SSR for React JS application. After  ~15 minutes under load it starts to get memory usage spikes +100% ref current memory usage. Also memory usage slowly grows over time as requests keep coming. The spikes happen exactly each 5 minutes and continue to happen even when production load is removed and there are no requests reaching server. It is also visible that CPU is heavily used during spikes.

Mem stats during pick:
{
   "rss":657969152,
   "heapTotal":479604736,
   "heapUsed":454440744,
   "external":39580559
}

Mem stats during after:
{
   "rss":180793344,
   "heapTotal":37830656,
   "heapUsed":32426920,
   "external":1438562
}

Memory consumption in the beginning:
<img width="644" alt="Picture how it was starting" src="https://user-images.githubusercontent.com/51781420/68197358-d4c61380-ffc2-11e9-8273-69bd6f1bfff5.png">

Memory consumption after 12 hours without requests coming:
<img width="650" alt="Current behavior without load" src="https://user-images.githubusercontent.com/51781420/68197392-e3acc600-ffc2-11e9-94c2-a603264ee4f5.png">

Node is started as:
NODE_ENV=production node --max-old-space-size=4000 build/server.js

I tried to use --trace-gc option and I see that memory usage gets higher during GC phase, then it is released. Still it grows over time in general.

Heap Dump which I create using "v8.writeHeapSnapshot();" stays at about 30MB and doesn't grow.
<img width="766" alt="Heap dump" src="https://user-images.githubusercontent.com/51781420/68198218-4ce10900-ffc4-11e9-83d7-3c40c7b8da4c.png">

Please help me to understand what is happening.

**Comment by gireeshpunathil** [comment]
@alexandershiltcev-gelato - as I understand from the graph, the spike remains roughly between 30 second to 1 minute? If so, the easier thing to do would be:
 - take one heap snapshot before the spike starts - say any time between 8.50 and 8.54, analogous to the graph
 - take another one at 8.55, assuming that corresponds to the memory peak.
 - load both the dumps in the google chrome developer tools, and do a `diff` - it will show up the new comers, with their retention size, caller etc.

Another option is to run with `--experimental-report --report-on-signal` and collect reports a couple of times while the bad behavior has started to manifest. The `libuv` section in the report will confirm whether we have a `setInterval of 5 minutes` in the application or not.

**Comment by alexandershiltcev-gelato** [comment]
Thank you @gireeshpunathil for a hint. It turned out npm package node-persist which I used for caching tried to cleanup old files each 5 minutes, but because they weren't old enough, they were never deleted. For some reason this process was so memory intense.
