### ISSUE TITLE
Is it possible to implement Transaction in nodejs?

### ISSUE THREAD

**Issue by Jeff-Tian** [nodejs/help#2275]
**Is your feature request related to a problem? Please describe.**
Some actions are not directly on database, but a series of invoking other services. However, if one action fails it should not affect the system state.

**Describe the solution you'd like**
In C#, there is `System.Transaction` class. Can nodejs provide that equivalent feature too?
```C#
using(TransactionScope tran = new TransactionScope()) {
    CallAMethodThatDoesSomeWork();
    CallAMethodThatDoesSomeMoreWork();
    tran.Complete();
}
```

**Describe alternatives you've considered**
I did some searching and find a npm package: https://www.npmjs.com/package/node-transactions

However it is not that active and seems the solution is not that elegant. And the downloads is only a few.

**Comment by tniessen** [comment]
I am not sure what you are expecting. Do you want an API that can "rollback" any modifications of the system state if an error occurs? I am relatively sure that such an API would not be feasible.

**Comment by Jeff-Tian** [comment]
Yes exactly. Ok now I kniw it's not feasible though. Thanks for your reply.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tniessen** [comment]
I have never used the `TransactionScope` class in C#, but I would be surprised if that is what it does.

In general, such a concept is infeasible in computing, especially in a highly concurrent environment such as Node.js. Also, the system state often cannot be rolled back: How would you rollback a network connection? How would you rollback a created file that the user has overwritten with their own data by the time an error occurs?

**Comment by gireeshpunathil** [comment]
some modern h/w implement [transactional memory](https://en.wikipedia.org/wiki/Transactional_memory) as a primitive for the OS / compilers to mimic tiny user operations as transactions - by running things in a sandbox and commit / rollback based on the interference in the execution path.

This can be extended to achieve higher level transactional abstractions at user space, but the scope has to be limited to in-memory operations. Side effects caused by the transaction external to the system (such as pointed out by @tniessen ) cannot be meaningfully rolled back.

**Comment by gireeshpunathil** [comment]
@Jeff-Tian - do you have a specific workload example that you are interested in transaction-alizing?

**Comment by ORESoftware** [comment]
you can use a distributed lock/mutex for this

**Comment by Jeff-Tian** [comment]
> @Jeff-Tian - do you have a specific workload example that you are interested in transaction-alizing?

@gireeshpunathil There is a popular nodejs package: `semantic-release`. To setup it automatically you just need to type in some credentials. 

For example, you need to type npm credential and github credential sequentially. If you failed at the github authentication, then the npm authentication  still succeeded and created a token there. 

Although it doesn't matter much for the unnecessary tokens, but ideally no token should be created on whichever step fails.

```bash
➜ semantic-release-cli setup
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? jeff-tian
? What is your npm password? [hidden]

npm token created

? What is your GitHub username? jeff-tian
? What is your GitHub password? [hidden]
failed here, github token was not created, but the npm token still there
```

**Comment by tniessen** [comment]
There really is nothing we can do there, that is application-level logic. Rolling that back would potentially involve revoking a GitHub / npm access token, and that is nothing we can do without application logic.

**Comment by ORESoftware** [comment]
transactions can be done with a relational db

you need a networked mutex

better to not do it at application level

**Comment by tniessen** [comment]
@ORESoftware That is one kind of transaction, but it won't help here.

**Comment by Jeff-Tian** [comment]
Thank you all for your brilliant thoughts!
