### ISSUE TITLE
I have this issue on same windows. I had node installed, but I think it was installed on an external drive. Now I'm getting this error when I try to install it again. 

### ISSUE THREAD

**Issue by ihavenokia** [nodejs/help#2276]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by thekemkid** [comment]
Please provide a screenshot, or copy-paste the error.

**Comment by tniessen** [comment]
Please provide the erorr message, your Windows version and edition, the installation log when attempting to install Node.js, and any other information that might be helpful. We cannot help you based on the issue title only. Please reopen the issue when ready.
