### ISSUE TITLE
npx Error on mkdir when running on Windows10

### ISSUE THREAD

**Issue by Toordokter** [nodejs/help#2279]
When I try to run npx create-react-app, it always fails on this line:
Error: C:\new-app\node_modules\core-js: EINVAL: invalid argument, mkdir 'C:\Users\andre\AppData\Local\Temp;;C:\WINDOWS\system32\yarn--1573267623945-0.6642629310289891'

I am running cmd as administrator. Any ideas on how to resolve?
[yarn-error.log](https://github.com/nodejs/node-report/files/3826862/yarn-error.log)

**Comment by tniessen** [comment]
```
'C:\Users\andre\AppData\Local\Temp;;C:\WINDOWS\system32\yarn--1573267623945-0.6642629310289891'
```

That is not a valid path on Windows (it contains a colon which is not a valid file name character), it looks like it is a concatenation of two paths.

`C:\WINDOWS\system32\yarn`. This looks weird. Yarn should not touch that directory.

**Comment by milindbajaj** [comment]
@Toordokter
Is your problem resolved?? 
if yes please tell me how you reslove it , I am also getting same error

**Comment by Toordokter** [comment]
I managed to resolve it - but honestly I can't remember how. I played
around with npm and npx for different phases and finally it started working.

**Comment by PoojaDurgad** [comment]
@milindbajaj - is this still an issue? if that is not the case hopefully https://github.com/zkat/npx/issues/146 it may help you to resolve the issue.

**Comment by PoojaDurgad** [comment]
issue resolved. closing!!
