### ISSUE TITLE
Node API identifiers list

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#228]
Is there a way to get a list of all the Node.js API identifiers (including documented methods and properties of deep levels) to update an editor autocompletion file? Currently I've thought up this naive script:
```js
/******************************************************************************/
'use strict';
/******************************************************************************/
const libNames = require('repl')._builtinLibs.concat('timers', 'module');

const globs = [global, module, require].concat(libNames.map(libName => require(libName)));
const orphanedNames = ['__dirname', '__filename', 'require'];
const identifiers = new Set(libNames.concat(orphanedNames));
const processedObjects = new Set();
/******************************************************************************/
globs.forEach(processKeys);
console.log([...identifiers].sort().join('\n'));
/******************************************************************************/
function processKeys(obj) {
  processedObjects.add(obj);

  Object.getOwnPropertyNames(obj).forEach(prop => {
    identifiers.add(prop);
    try {
      const value = obj[prop];
      if (value instanceof Object && !processedObjects.has(value)) {
        processKeys(value);
      }
    } catch (err) {
      console.error(err.message);
    }
  });
}
/******************************************************************************/
```
However, I am not sure it is an exhaustive way. Maybe there is a curated library like  [globals](https://github.com/sindresorhus/globals/)?

**Comment by addaleax** [comment]
Well, there are two things I can think of in the grey area that is not documented as part of the public API, but likely won’t be removed in the overseeable future, which could help with the `libNames` part:

- `repl._builtinLibs` – Not exhaustive, but everything that’s available in the REPL by default
- `Object.keys(process.binding('natives'))` – Stuff from core you can `require()`

**Comment by vsemozhetbyt** [comment]
@addaleax Thank you. I've updated the script and added some recursion for deeper levels. However, the list still lacks some documented identifiers (for example, properties of returned class instances) and includes many internal properties (it is good for Node.js developers, but excessive for users). Also, before filtered, it contains many strange keys, such as negative integers, pathes and file names, strings like or "#UE#FNI#" ). It seems, a naive autogeneration is not a good way)

I wonder, are there any such lists for the JavaScript built-ins API and for the WEB API (for the browser context)?
