### ISSUE TITLE
Getting “Segmentation fault” after installing nodejs on arm

### ISSUE THREAD

**Issue by hiwoodpecker** [nodejs/help#2280]
![image](https://user-images.githubusercontent.com/33960888/68530645-1ea55580-0345-11ea-84d5-8e8db82b18a6.png)
can anyone help me?

**Comment by tniessen** [comment]
cc @nodejs/platform-arm

Does this also happen with more recent Node.js versions, e.g., 12.13.0?

**Comment by rvagg** [comment]
You're going to need to tell us what kind of ARM processor this is, what Node binary you've downloaded and installed and what version. It would also be good to know what distro and version you're using. All of those things matter and you have only told us "arm" so far.

**Comment by PoojaDurgad** [comment]
ping, @hiwoodpecker

**Comment by PoojaDurgad** [comment]
inactive. closing!!
