### ISSUE TITLE
jsonwebtoken is not working in nodejs version 10x

### ISSUE THREAD

**Issue by poojasree406** [nodejs/help#2282]
Node.js Version - 10x

jsonwebtoken is not working in nodejs version 10x. But it is working in nodejs version 8.

**Comment by Hakerh400** [comment]
Post your source code and the exact error message you got.

**Comment by poojasree406** [comment]
error - jsonwebtoken is returning null

please find the below code

```
var jwt = require('jsonwebtoken');

	var authToken = jwt.sign({ selectedOption: selOption },
		'key', { expiresIn: 90000 });
```

**Comment by Hakerh400** [comment]
It works for me.

```js
'use strict';

const jwt = require('jsonwebtoken');
const token = jwt.sign({}, 'key', {expiresIn: 90000});

console.log(process.version);;
console.log(token);
```

Output:

```
v10.17.0
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NzM2Mjk3OTcsImV4cCI6MTU3MzcxOTc5N30.hfMKs5-zUBlm8w7vQVd4ZLYxgoXQEVyH8qAJIJS4L-o
```

**Comment by PoojaDurgad** [comment]
@poojasree406 - were you able to follow @Hakerh400 's suggestion? or is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to reopen the issue if that is not the case.
