### ISSUE TITLE
How To Substitute Env Variable in .npmrc -- .bashrc Not An Option

### ISSUE THREAD

**Issue by stephencweiss** [nodejs/help#2283]
* **Node.js Version**: 12.5.0
* **OS**: OSX 10.15.1
* **Scope (install, code, runtime, meta, other?)**: Install, runtime, other?
* **Module (and version) (if relevant)**:

Hi!

I was directed here by the npm team, but I'm trying to understand how I might substitute an environment variable in my .npmrc that is _NOT_ saved in my .bashrc.

In my particular case, we are using `vault` (from Hashi Corp) to manage secrets and I'd like to use that to manage the replacement of the variable, but I need to get past the first few steps in the node/npm process in order to get there.

Background:

1. We are using a scoped package that we're installing from a private repository. That requires an `_authToken` property.
2. We do not want to check in that auth token or require each user to configure their `.bashrc` (this is why we have `vault`)
3. When building on `gitlab` we're able to run a `before_script` which sets the variable to temporary and then is replaced before the install.

Is there a way to mimic that behavior locally?

The error I'm getting currently:

```
$ npm run
Error: Failed to replace env in config: ${FONTAWESOME_NPM_AUTH_TOKEN}
at /usr/local/lib/node_modules/npm/lib/config/core.js:415:13
at String.replace (<anonymous>)
at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:411:12)
at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:389:7)
at /usr/local/lib/node_modules/npm/lib/config/core.js:330:24
at Array.forEach (<anonymous>)
at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:328:23)
at ConfigChain.addString (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:316:10)
at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
/usr/local/lib/node_modules/npm/lib/npm.js:59
throw new Error('npm.load() required')
^
Error: npm.load() required
at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:59:13)
at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:32)
at process.emit (events.js:200:13)
at process._fatalException (internal/process/execution.js:146:25)
```

My `.gitlab-ci.yml`

```
variables:
DOCKER_BUILDER_VERSION: 'v16'
before_script:
- export FONTAWESOME_NPM_AUTH_TOKEN=temporary
- source /setup-build-env
- nvm use
build:
image: ${DOCKER_BUILDER_IMAGE_US}:${DOCKER_BUILDER_VERSION}
stage: prepublish
only:
- branches
except:
- master
script:
- shackle hydrate-secrets --host vault.remine.com --argset='global|FONTAWESOME_NPM_AUTH_TOKEN|${FONTAWESOME_NPM_AUTH_TOKEN}' --filepath .npmrc --no-base64
- npm install
- npm run build
```

The `.npmrc` that's local to my project:

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
```

Some relevant parts of my `package.json`:

```
{
  "name": "repaint",
  "scripts": {
    "configure-development": "vaultinit --host vault.remine.com --path 'global'",
    "prepare": "export FONTAWESOME_NPM_AUTH_TOKEN=temporary",
    "preinstall": "export FONTAWESOME_NPM_AUTH_TOKEN=temporary && npm run configure- 
development && source .env",
  },
}
```

As you can see - i tried several of the hooks - but the process seems to be erroring out before we get that far. I've also tried placing the variable into a `config` node within the

Summary: Is there a way to have npm pass the first steps in its process by setting a variable _within_ the project (i.e. nothing that requires modifying the `.bashrc`)?

Thank you in advance!

**Comment by gireeshpunathil** [comment]
@stephencweiss - is this still an issue?

not sure how this is a Node.js issue as opposed to npm. the standard way of setting a process env variable X to Y is `process.env.X = Y;` and if you want to make sure this is enforced at the very beginning of the process, then set this and spawning child will make sure the child gets this setting in the very beginning (several unit tests in our source repository can show examples) . How this logic is used in the application is purely specific to the app itself.

**Comment by stephencweiss** [comment]
@gireeshpunathil - I don't believe so. I actually wrote up my solution here: https://stephencharlesweiss.com/collaborating-with-npm-and-sharing-secret-env-variables/

(Sorry for leaving the issue open)

**Comment by gireeshpunathil** [comment]
sure! happy to know that your issue is resolved, and that is what is more important!

closing the issue then, cheers!

**Comment by nemoDreamer** [comment]
@stephencweiss your blog post's URL changed, but I found the original: https://stephencharlesweiss.com/collaboration-local-development-secret-environment-variables-and-npm

**Comment by tomaszs** [comment]
Is there any other solution that's not so painful?

**Comment by noelblaschke** [comment]
@tomaszs Maybe this package does match your requirements: https://github.com/dennzimm/npmrc-replace-env
