### ISSUE TITLE
spawnSync shell command, error cut: -: Bad file descriptor

### ISSUE THREAD

**Issue by Tatsujinichi** [nodejs/help#2284]
Here is my stackoverflow link to the question. https://stackoverflow.com/questions/58796378/spawnsync-for-shell-commands

I wonder if this may be a bug?

```
const { spawnSync } = require('child_process');
const fs = require('fs-extra');

function trimFile() {
    let rfd;
    let wfd;
    try {
        rfd = fs.openSync('filelist.txt', 'r');
        wfd = fs.openSync('filesonly.txt', 'w');
        spawnSync('cut -d" " -f1', { stdio: [wfd, rfd, 'inherit'] });
    }
    finally {
        fs.closeSync(rfd);
        fs.closeSync(wfd);
    }
}
```

* **Version**:
11.8.0
* **Platform**:
Ubuntu 18.04
Linux computerName 4.15.0-66-generic nodejs/node#75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**:
child_process

**Comment by Tatsujinichi** [comment]
Oh I see.  Is this correct with shell: true?

**Comment by andres-lowrie** [comment]
so this may still be an issue perhaps?

With latest lts version

```
node --version
v18.14.0
```

Given I have 2 files in some directory 
```
touch err out
```

and write a script like this 

```javascript
const { spawnSync } = require('child_process')
const fs = require('fs')

const out = fs.openSync('./out')
const err = fs.openSync('./err')

spawnSync('echo', ['hello'], { stdio: ['pipe', out, err]})
```

the script runs without errors but the file used for stdout is empty

```
ls -l
-rw-r--r--   1 andreslowrie  staff     0 Feb 10 16:37 err
-rw-r--r--   1 andreslowrie  staff   264 Feb 10 16:37 index.js
-rw-r--r--   1 andreslowrie  staff     0 Feb 10 16:37 out
```

Where I'm expecting there would be `hello` in the file `out` 

-------

If I instead use `fs.createWriteStream` 

```javascript
const { spawnSync } = require('child_process')
const fs = require('fs')

//const out = fs.openSync('./out')
//const err = fs.openSync('./err')
//

const out = fs.createWriteStream('./out')
const err = fs.createWriteStream('./err')

out.on('open', () => {
  err.on('open', () => {
    spawnSync('echo', ['hello'], { stdio: ['pipe', out, err] })
  })
})
```
it in fact writes to the output

```
ls -l
-rw-r--r--   1 andreslowrie  staff     0 Feb 10 16:40 err
-rw-r--r--   1 andreslowrie  staff   352 Feb 10 16:40 index.js
-rw-r--r--   1 andreslowrie  staff     6 Feb 10 16:40 out
cat out
hello
```

-----

This is probably a user error in reading the docs, but shouldn't the first method work the same way the second method does?, given that the script passes open fd numbers to the stdio option ?
