### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by willhelmx** [nodejs/help#2286]
Hi, I downloaded the x86 version a few hours ago, trying to make a api connect to TTN, however the npm module always call for https://github.com/thethingsnetwork/api.git  ... a file that doesent seem to exist in the github directory
wich file to use, and where do i change it in the powershell?

Br
/A

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by tniessen** [comment]
> however the npm module

Which npm module are you talking about?

> always call for https://github.com/thethingsnetwork/api.git  ... a file that doesent seem to exist in the github directory

That is a link to a GitHub repository, and the link works, the repository exists.

> wich file to use, and where do i change it in the powershell?

I have no idea what you are talking about. It sounds like you are on Windows. We prepared an issue template for you, which you chose to ignore. Could you please provide your OS edition and version, the Node.js version that you are using, the error message that you are encountering, and any commands or code snippets that we can use to reproduce the problem?

**Comment by willhelmx** [comment]
Hi tniessen

Sorry my misstake, i´m new at node.js and tried to implement my C #include thinking in this matter, issue solved by now, and i assure you i dident ignore anything, dident know it existed any issue template that needed my attention sorry for that... as i said i´m a newbee at this community too :-)

Thank you for all help

BR
/A

**Comment by tniessen** [comment]
No problem, glad your problem is resolved.
