### ISSUE TITLE
how to upload byte image file array in node js

### ISSUE THREAD

**Issue by Runa-Redapple** [nodejs/help#2287]
Byte file array how to  uplaod in node js
 in api request

**Comment by tniessen** [comment]
Depends on the kind of request. Is it a POST request, or a PUT request? If it is a POST request, what encoding does the server accept? Which API or module are you using to make the request? There are literally hundreds of existing solutions online, and it is very difficult to help you if you don't provide any information.

**Comment by Runa-Redapple** [comment]
Post request ,  Send byte array in file uploading time  .  But I get some  unknown symbol.   From frontend side they  are sending byte array multi part. @tniessen

**Comment by tniessen** [comment]
Based on the very limited information you provide, it seems like you might be trying to implement the server that the data is uploaded to, and not a request that uploads data? If that is the case, there are hundreds of solutions online, one of the most popular middleware modules is [multiparty](https://www.npmjs.com/package/multiparty).

**Comment by PoojaDurgad** [comment]
@Runa-Redapple - is this issue resolved? were you able to follow @tniessen 's suggestion?

**Comment by PoojaDurgad** [comment]
inactive . closing!! feel free to reopen the issue if it is outstanding.
