### ISSUE TITLE
Unable to Create String Literal of Only "\"

### ISSUE THREAD

**Issue by AdamYoungberg** [nodejs/help#2288]
* **Version**: v12.13.0
* **Platform**: 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
* **Subsystem**:

I am unable to create a string that contains only a literal `\`.

Examples using the node REPL (v12.13.0):
```javascript
var str='\\';
str 
/* output: '\\' */
```
```javascript
var str = "\u005C";
str 
/* output: '\\' */
```
```javascript
var input = "\\\\.test\\\\.test"
var output = input.replace(/\\\\/gi,"\\");
output
/* output: '\\.test\\.test'; CORRECT */
var output2 = output.replace(/\\\\/gi,"\\");
output2
/* output: '\\.test\\.test'; INCORRECT: expected: '\.test\.test' */
```

---

* **Version**: v13.1.0
* **Platform**: 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
* **Subsystem**:

Same result as with version 12.13.0 _(showing REPL output directly this time)_
```bash
> var input = "\\\\.test\\\\.test"
undefined
> var output = input.replace(/\\\\/gi,"\\");
undefined
> output
'\\.test\\.test'
> var output2 = output.replace(/\\\\/gi,"\\");
undefined
> output2
'\\.test\\.test'
```

**Comment by addaleax** [comment]
> ```js
> var str='\\';
> str 
> /* output: '\\' */
> ```

This is the right one. The REPL just displays it in a format that you can use to create strings, and not as the string itself.

Using `console.log(str);` directly should give you the right result here, though.

**Comment by tniessen** [comment]
This appears to have been answered by @addaleax: The string literal is created as intended, it is just a matter of interpreting the REPL output. Using `console.log` will output the string as expected.
