### ISSUE TITLE
test depandancy on logger

### ISSUE THREAD

**Issue by raja8861** [nodejs/help#229]
Hai

This is my Task..

i need a sample scenario..which is perfectly works..

TASK:
DESCRIPTION:
As a developer, I want to fix the issue test dependency with logger" so that the test will not be depend on logger module and no log files created while running test part of jenkin job.
 
AC:
Fix the unit test.
Code is reviewed.
The github issue is closed.
 
Note:
When we run Ripe Build, the Error/Info log files are getting created indicating we have direct dependency on logger and it is not stubbed.

Thank You please get back me ASAP.

**Comment by kahwee** [comment]
You have to describe your problem better for others to help you.

**Comment by raja8861** [comment]
while we run the any application in any technology the "log" files will get created right,
This is what happening 💯 
as well as while i am running the **UNIT TEST CASES** as part of jenkin's jobs ,the log files were creating . 

I need Solution like this:

while i run the **UNIT TEST CASES** as part of jenkin's jobs , the "log" files should not be created

**Comment by raja8861** [comment]
i am creating the BizEvent Api in this i am having this problem

**Comment by TheAlphaNerd** [comment]
@raja8861 I'm having a hard time understanding exactly what the problem is with the way you have described it.

Please let me know if I am incorrect.

  *  You have an application
  *  That application logs to a file
  *  When running tests you do not want the file to be created?

**Comment by raja8861** [comment]
yes ,but i need to create log files when i run my whole application,comming to the jenkin jobs when i run only test cases that time also the log files were creating.

i dont wont to create log files when i run my unit test cases.

**Comment by TheAlphaNerd** [comment]
are you using a particular module to generate the log files?

**Comment by raja8861** [comment]
we have created a logging.js file 
let log =bunnyan.createLogger({
name : config.service.name,
streams: [
{
type : "rotating-file",
period:"1h",
count:720
level:"info",
path: "../Info.log"
}
{
type : "rotating-file",
period:"1h",
count:720
level:"error",
path: "../Error.log"
}
{
type : "rotating-file",
period:"1h",
count:720
level:"Trace",
path: "../Trace.log"
}
],

**Comment by TheAlphaNerd** [comment]
you can use rewire mentioned above to stub the log function in your modules.

**Comment by raja8861** [comment]
in this way we are creating logs files and using sinon framework ,i want to stub my logging file also("That is the log module")

**Comment by raja8861** [comment]
so that while running the test cases we don't wont to create log files

**Comment by raja8861** [comment]
Hey buddy if you have any other resource please send me the links

**Comment by raja8861** [comment]
so that i can wrap up my work ...

Thank Yoou

**Comment by TheAlphaNerd** [comment]
@raja8861 I can't really suggest anything more aside from stubbing your logging module.

Good luck. This thread emails many people so I would advise against spamming it.
