### ISSUE TITLE
Issue with setNickname in Discord.js

### ISSUE THREAD

**Issue by jakerdou** [nodejs/help#2290]
* **Node.js Version**: 10.15.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

I am trying to set a simple nick naming function for my Discord Bot, but when I type in "!setNickname @username" it gives me **this error message**:

`(node:20440) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at item.request.gen.end (C:\Code\ACCBot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15)
    at then (C:\Code\ACCBot\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Here is my code:** (prefix is !)

```
const Discord = require('discord.js'); //looks in node_modules folder for discord.js
const {prefix, token} = require('./config.json');
const client = new Discord.Client();

client.once('ready', () => {
	console.log('Ready!')
})

client.on('message', message => { 
	
	if(message.content.startsWith(`${prefix}setNickname`)){
		
		let member = message.mentions.members.first();
		member.setNickname('cool guy').then((member) => {
			message.channel.send(member.displayName + "is a cool guy")
		})
	}
})

client.login(token);
```

Thanks in advance!

**Comment by Olybear9** [comment]
This is a permission issue (discord not allowing you to do this) not a library issue. However a way to filter errors like this would be to use a try and catch block (I also made it Async for you):

```js
const Discord = require('discord.js');
const {prefix, token} = require('./config.json');
const client = new Discord.Client();

client.once('ready', () => {
	console.log('Ready!')
})

client.on('message', async (message) => { 
       try {
	if(message.content.startsWith(`${prefix}setNickname`)){
		let member = message.mentions.members.first();
		member = await member.setNickname('cool guy');
		message.channel.send(member.displayName + "is a cool guy");
	}
       } catch (e) {
          console.error(e); // It's always useful to log your errors.
          return message.channel.send("Something went wrong when running this command!");
       }
});

client.login(token);
```

**Comment by jakerdou** [comment]
Thanks! Do you by chance know how to modify permissions on a Discord Bot?

**Comment by daekwon12** [comment]
Love it. Thank you for your help

**Comment by plaraje** [comment]
whwn i use 
`message.author.setNickname('not-verificated');` it says to me thet setNickname is not a function, someone else?

**Comment by MrNNP** [comment]
> when i use
> `message.author.setNickname('not-verificated');` it says to me that setNickname is not a function, someone else?
> 
> ```js
> message.author.setNickname('nick');
> ```
it should be message.**member**.setNickname('nick')

member is a guildmember object, and author is just a user object.

**Comment by VivianKwan1** [comment]
hi i'm trying to use `message.member.setNickname('nick')` but i'm getting a type error that says "Cannot read properties of undefined (reading 'setNickname')" ?

**Comment by plaraje** [comment]
My problema were the bot perms but you code seems like the code is bad if u
are copying from a vídeoake sure that u are using message.author or
m.author or check the bot perms
