### ISSUE TITLE
Is there a module wrapper for ES modules?

### ISSUE THREAD

**Issue by kimamula** [nodejs/help#2292]
* **Node.js Version**: v13
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: ECMAScript module

CommonJS module's code is executed in a function wrapper [as described](https://nodejs.org/api/modules.html#modules_the_module_wrapper).
I guess that as each ES module has different `import.meta.url`, ES module's code might also be executed in a function wrapper that provide the ES module with the `import` object.
Is this correct?

**Comment by devsnek** [comment]
there is no wrapper for es modules. they are native to the underlying js engine.

**Comment by kimamula** [comment]
Thanks for the explanation!
