### ISSUE TITLE
Why is it not possible to require() ES modules from CommonJS modules?

### ISSUE THREAD

**Issue by kimamula** [nodejs/help#2293]
* **Node.js Version**: v13
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**: ECMAScript modules

Using dual package which exports both CommonJS and ES modules can be problematic as [described](https://github.com/nodejs/node/blob/31ea341ab0cf8edc25b544dc9b71f3f70cc4558c/doc/api/esm.md#divergent-specifier-hazard).

If CommonJS modules could `require()` ES modules, both CommonJS modules and ES modules could always use the same ES modules in dual package and the problem should not occur.
I would like to know the reason why this is not possible.

**Comment by devsnek** [comment]
esm is asynchronous, which means require would have to return a promise. At that point, you should just use import().

**Comment by kimamula** [comment]
Thank you so much for the explanation.
That makes sense.

However, I can not find any description in the ECMAScript specification which says "esm is asynchronous".
Is it specified in any standard or only specific to Node.js?

**Comment by devsnek** [comment]
in the current specification you could technically resolve, link, and execute the entire graph synchronously. however, there is a stage 3 proposal called top level await which does force the graph loading to be async.

**Comment by kimamula** [comment]
Thanks for navigating me to top-level `await`!
I read [here](https://github.com/tc39/proposal-top-level-await#faq) and [here](https://v8.dev/features/top-level-await) and understood why it's not possible for CommonJS modules to `require()` ES Modules!
