### ISSUE TITLE
IBM i nodever list is not working

### ISSUE THREAD

**Issue by sce001** [nodejs/help#2295]
Good day,

On a qshell interactive session, I typed the following command:  'export PATH=/QOpenSys/pkgs/bin:$PATH' and then
'nodever list' and i got:
 "Could not load program node:                                  
rtld: 0712-001 Symbol ENGINE_by_id was referenced             
      from module node(), but a runtime definition            
            of the symbol was not found.                      
rtld: 0712-001 Symbol ENGINE_ctrl_cmd_string was referenced   
      from module node(), but a runtime definition            
            of the symbol was not found.                      
rtld: 0712-001 Symbol ENGINE_finish was referenced            
      from module node(), but a runtime definition            
            of the symbol was not found.                      
rtld: 0712-001 Symbol ENGINE_free was referenced              
      from module node(), but a runtime definition            
            of the symbol was not found.                      
rtld: 0712-001 Symbol ENGINE_init was referenced              
      from module node(), but a runtime definition            
            of the symbol was not found.                      
 rtld: 0712-001 Symbol ENGINE_load_builtin_engines was referenced          
       from module node(), but a runtime definition                        
             of the symbol was not found.                                  
 rtld: 0712-001 Symbol ENGINE_load_private_key was referenced              
       from module node(), but a runtime definition                        
             of the symbol was not found.                                  
 rtld: 0712-001 Symbol ENGINE_set_default was referenced                   
       from module node(), but a runtime definition                        
             of the symbol was not found.                                  
 rtld: 0712-001 Symbol ERR_load_ENGINE_strings was referenced              
       from module node(), but a runtime definition                        
             of the symbol was not found.                                  
 rtld: 0712-001 Symbol SSL_CTX_set_client_cert_engine was referenced       
       from module node(), but a runtime definition                        
             of the symbol was not found.                                  
 rtld: 0712-002 fatal error: exiting."                                      

Could you please help?

Thank you,

Serge

**Comment by ThePrez** [comment]
I suspect this is a dup of the following issue: https://bitbucket.org/ibmi/opensource/issues/91/nodejs12-v12130-0-errors-when-running-node

Please upgrade openssl libs via `yum upgrade libopenssl1_1` (you may need a `yum clean expire-cache` first) and report if that resolves your issue.

**Comment by ThePrez** [comment]
An upgrade of the nodejs12 package should also fix this issue

**Comment by gireeshpunathil** [comment]
@ThePrez - you are super fast! I was trying to search for your github handle to ping, but you are already on it! thnx.

**Comment by sce001** [comment]
It works!
Thank you very much :-)
