### ISSUE TITLE
http localAddress not working with same subnet on multiple network interfaces

### ISSUE THREAD

**Issue by bl0ggy** [nodejs/help#2296]
* **Node.js Version**: 8.15.1
* **OS**: Ubuntu 14.04
* **Scope (install, code, runtime, meta, other?)**: runtime?
* **Module (and version) (if relevant)**: http

Hello,
I work on an embedded system that uses 2 hardware ethernet interfaces, both having a Link-Local Address alias as you can see here (using `ip a`):

```
eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 3000
    link/ether 00:1e:2d:00:40:6d brd ff:ff:ff:ff:ff:ff
    inet 10.251.25.206/24 brd 10.251.25.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet 169.254.11.1/16 scope global eth1
       valid_lft forever preferred_lft forever
eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc htb qlen 3000
    link/ether 00:1e:2d:00:40:6c brd ff:ff:ff:ff:ff:ff
    inet 192.43.182.23/20 brd 192.43.191.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 169.254.10.1/16 scope global eth0
       valid_lft forever preferred_lft forever
```

some cameras are connected on both interfaces, each of them having a link-local address, I need to send http requests to all of the cameras, but I am having trouble sending http requests using the official `http` module to these cameras.
An option for the `request` function called `localAddress` allows to use the correct interface/address, however, it does not work when both interfaces have the same subnetwork (link-local here).

Let's suppose that my system does not have the link-local aliases and we have 1 camera connected on each interface :
* camera0: connected to eth0 with the address 169.254.10.50
* camera1: connected to eth1 with the address 169.254.11.50

Now let's follow these steps:
* I cannot communicate with the cameras yet as I am not on the same subnet.
* I add the alias 169.254.10.1/16 to eth0.
* => Now I can send a request to camera0 (setting the option `localAddress` to 169.254.10.1 or not is the same, it is smart enough to find it)
* I add the alias 169.254.11.1/16 to eth1
* => I can still send a request to camera0 (setting `localAddress` or not), but, I cannot send a request to camera1, even if I set `localAddress` to 169.254.11.1
* Next, I delete the alias on eth0, then create it again
* => Now I can send a request to camera1, whetever the value of `localAddress`, but I cannot access camera0 anymore, even if I set `localAddress` to 169.254.10.1

The error appearing is EHOSTUNREACH.

Am I doing something wrong ? Is that a bug ? Is it a limit of Linux/IP ? How can I be able to send requests to both eth without having to delete/create aliases ?

Thank you

**Comment by bnoordhuis** [comment]
From your description of the problem, it sounds like something is wrong with the setup of the routing tables (`route -vn`) - there should be a route from the address you bind to to the address you want to connect to. You probably need to set up a bridge between 169.254.10.0/24 and 169.254.11.0/24.

You mention your networks are /16s. Are you sure that's correct? That'd mean they both map the range 169.254.0.0-169.254.255.255.

**Comment by bl0ggy** [comment]
Yes the networks are /16, these networks are called link-local, [Wikipedia](https://en.wikipedia.org/wiki/Link-local_address) can tell you more about this.

Actually I succeed to make this work by modifying the route rules/tables, but I would like to know if we need to modify the route because of the way Linux deals with networks, or if this can also be done with NodeJS/http by selecting the local address. I don't know much about routing, that's why I am still asking about that.

Anyway here is what I did to make it work :
* First I added 2 tables `lla_eth0` and `lla_eth1` ('lla' stands for link-local address) :
```
# echo -e "1\tlla_eth0" >> /etc/iproute2/rt_tables
# echo -e "2\tlla_eth1" >> /etc/iproute2/rt_tables
```
note that the numbers '1' and '2' are the IDs of the tables, they should be unique, and in my case they were not used.
* Then on each table, I want to route every destination address within the network 169.254.0.0/16 to their corresponding interface :
```
# ip route add 169.254.0.0/16 dev eth0 table lla_eth0
# ip route add 169.254.0.0/16 dev eth1 table lla_eth1
```
* Finally, I set 2 rules, every time the source 169.254.10.1 is used we use the table lla_eth0, and similarly with 169.254.11.1 and lla_eth1 :
```
# ip rule add from 169.254.10.1 table lla_eth0
# ip rule add from 169.254.11.1 table lla_eth1
```
