### ISSUE TITLE
Xcode 10 Build Requirement in Node Version 13.1.0

### ISSUE THREAD

**Issue by debohman** [nodejs/help#2297]
* **Node.js Version**: 13.1.0
* **OS**: macOS 10.12.6
* **Scope (install, code, runtime, meta, other?)**: build

I noticed the new requirement for Xcode or the command line tools >= 10 to build Node 13.1.0.

I was wondering what the actual issue was? Is a newer compiler needed? It would be helpful to understand this issue.

**Comment by debohman** [comment]
Closing.

**Comment by richardlau** [comment]
The issue was that V8 was starting to use things that required the later Xcode (https://github.com/nodejs/node/pull/29493#issuecomment-530457360).

**Comment by debohman** [comment]
Moved over to nodejs/node#30500.
