### ISSUE TITLE
weird problem with process.title

### ISSUE THREAD

**Issue by bbsalsero** [nodejs/help#23]
hello,

something weird is happening,

on windows10, when i use in cmd and run node myscript , if i set process.title and then console.log it,
it work like a charm, but, if i spawn the process then process.title when changed just show me unreadable character.

could some ne explain me that?

myscript:
```javascript

var name = __filename.replace(__dirname,'')
console.log(name);

process.title=name

console.log(process.title)

```

will show "myscript"

but,

spawn:

```javascript

spawn('node', ['myscript'], {
   detached: true,
   stdio: [ 'ignore', out, err ]
 }).unref();

````

will show "h�06_Q<t�"

 

any idea?

**Comment by Trott** [comment]
What values are you assigning to `out` and `err`?

**Comment by bbsalsero** [comment]
i pointed then var err= fs.openSync(errfile,a) and var out= fs.openSync(outfile,a)

**Comment by lordKnighton** [comment]
feel free to reopen & happy coding :)
