### ISSUE TITLE
https.request get a read ECONNRESET error, but curl can get response of the url requested

### ISSUE THREAD

**Issue by IchiNiNiIchi** [nodejs/help#2300]
* **Version**: 7.0.0
* **Platform**: Windows 7 64-bit
* **Subsystem**: https

```

const https = require('https');

https.get('https://myportal.vtc.edu.hk/wps/portal', (res) => {
  console.log('statusCode:', res.statusCode);
  console.log('headers:', res.headers);

  res.on('data', (d) => {
    process.stdout.write(d);
  });

}).on('error', (e) => {
  console.error(e);
});
```
output:
```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

**Comment by dhiraj-cd** [comment]
> > @AHgPuK Were you able to resolve this issue? I am getting this same error with Node 8 and Node 10 using request.
> 
> I resolved this annoying issue by using request module from npm. All my tries to use http.request directly failed. I did not find what a difference but it is working now.

can you share your solution?

**Comment by AHgPuK** [comment]
> can you share your solution?

Use [request](https://www.npmjs.com/package/request)
