### ISSUE TITLE
run command after npm install command

### ISSUE THREAD

**Issue by skirankumar7** [nodejs/help#2301]
run command after npm install command

What I want to do is after npm install I want to run webpack server.

Any ideas, hints...

**Comment by renatajarmova** [comment]
Have you modify your scrips in your package.json file? Once you've done that you'll be able to run a command to start the webpack server. e.g: 

Modify your package.json:
```
"scripts": {
  "start:dev": "webpack-dev-server"
} 
```

and then run this in your CLI:
```
npm run start:dev
```

It is all very clear in the npm documentation, have a look: https://www.npmjs.com/package/webpack-dev-server

Hope it helps!

**Comment by skirankumar7** [comment]
> Have you modified your scripts in your package.json file? Once you've done that you'll be able to run a command to start the webpack server. e.g:
> 
> Modify your package.json:
> 
> ```
> "scripts": {
>   "start:dev": "webpack-dev-server"
> } 
> ```
> 
> and then run this in your CLI:
> 
> ```
> npm run start:dev
> ```
> 
> It is all very clear in the npm documentation, have a look: https://www.npmjs.com/package/webpack-dev-server
> 
> Hope it helps!

Hi @renatajarmova 
Maybe you understood it in a different manner what I am asking is the 

**For Ex: I did `npm install some-package`**

hereafter installing the **some-package** immediately it has to run the webpack server I don't want to run `npm run start:dev` command explicitly

**Comment by PoojaDurgad** [comment]
@skirankumar7 - typically webpack run using npm scripts ,  running the webpack explicitly without npm scipts is impracticable .for me with your issue these are the references- https://www.npmjs.com/package/webpack-dev-server#attribution and https://webpack.js.org/guides/installation/ hope it may help.

**Comment by PoojaDurgad** [comment]
inactive . closing!! let me know if its still outstanding
