### ISSUE TITLE
Metro bundler closing  for node version 12.03 after running a react-native project

### ISSUE THREAD

**Issue by jeringeorge98** [nodejs/help#2302]
* **Version**:
* **Platform**:
* **Subsystem**:

The Metro bundler keeps closing everytime i run the react native project .The metro bundler is only stable for node 10.15 version.Please look into it

**Comment by gireeshpunathil** [comment]
@jeringeorge98 - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
