### ISSUE TITLE
heroku deployment issue

### ISSUE THREAD

**Issue by sasi1997** [nodejs/help#2304]
* **version 12.13**:
* **Windows**:

I deployed my node js code in Heroku I can able to run in localhost but I can't run in Heroku

`
// video stream by id and title
router.get("/videos", function (req, res) {
  let query, param;
  if (req.query.id) {
     query = "Select * from videos WHERE id = ?";
     param = req.query.id;
  } else if (req.query.title) {
    query = "Select * from videos WHERE title = ?";
     param = req.query.title;
  }
  db.query(query,param, function (err, result) {
    if (err) {
      res.send(err);
    } else {
      // console.log(result);
      let datafilter = result.filter((data, index) => {
        const video_path = data.videoUrl;
        const path = video_path;
      const stat = fs.statSync(path);
      const fileSize = stat.size;
      const range = req.headers.range;
      if (range) {
        const parts = range.replace(/bytes=/, "").split("-");
        const start = parseInt(parts[0], 10);
        const end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;
        const chunksize = end - start + 1;
        const file = fs.createReadStream(path, { start, end });
        const head = {
          "Content-Range": `bytes ${start}-${end}/${fileSize}`,
          "Accept-Ranges": "bytes",
          "Content-Length": chunksize,
          "Content-Type": "video/mp4"
        };
        res.writeHead(206, head);
        file.pipe(res);
      } else {
        const head = {
          "Content-Length": fileSize,
          "Content-Type": "video/mp4"
        };
        res.writeHead(200, head);
        fs.createReadStream(path).pipe(res);
      }
    });
    }
  });
});

-->

**Comment by Edmund1645** [comment]
Do you get some kind of error in the logs? and can you please format your code properly using the Markdown syntax? [here's a guide](https://guides.github.com/features/mastering-markdown/)

**Comment by PoojaDurgad** [comment]
ping - @sasi1997

**Comment by sasi1997** [comment]
@PoojaDurgad  what ??

**Comment by PoojaDurgad** [comment]
@sasi1997 -I wanted to check if this issue is resolved or not

**Comment by sasi1997** [comment]
That's was 11 months ago !

**Comment by sasi1997** [comment]
I resolved by next day itself... no wries

**Comment by gireeshpunathil** [comment]
closing then, cheers
