### ISSUE TITLE
I need nodeJS v5 in intel edison to run angular 2 app - issue 

### ISSUE THREAD

**Issue by neuberfran** [nodejs/help#231]
Hi guys,

I downladed nodejs V5 from here: http://nodejs.org/dist/latest-v5.x/
and I have this issue
Can you can help me?
https://drive.google.com/file/d/0B9gPdWq4OH-XRjk2UV92czJHbHM/view?usp=sharing
https://communities.intel.com/message/410550#410550

root@neuberfran:~# node -v
-sh: node: command not found
root@neuberfran:~# uname -a
Linux neuberfran 3.10.17-poky-edison+ #1 SMP PREEMPT Fri Jun 19 12:06:40 CEST 2015 i686 GNU/Linux

**Comment by lordKnighton** [comment]
you are using the intel edison board, correct?

**Comment by neuberfran** [comment]
yes why?
