### ISSUE TITLE
Node js server is not running with private IP address and throwing EINVALIDIPADDR error, how to use custom sockets in node js to make to work with private IP address ?

### ISSUE THREAD

**Issue by venkappa1** [nodejs/help#2310]
I want to use below c code in node js , my Private IP address is bind with ctxid, so , i need to below one and nodejs http server should be up and listen with my private IP. 
int sockfd;

    if ( 0 == ctxid )
        return socket(domain, type, protocol);

    /* Otherwise, use context-awared socket */
    sockfd = rbos_socket(domain, type, protocol);
    if ( sockfd < 0 ) {
        return sockfd;
    }

    ret = rbos_setsockopt( sockfd, SOL_SOCKET, SO_RBN_CONTEXT, &ctxid, sizeof(ctxid) );
    if ( 0 > ret ) {
        rbos_close( sockfd );

        return ret;
    }

**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by venkappa1** [comment]
Hi, i want to use socket fd (created by my application uinx based socket) in listen.server(handler, backlog) function, please can you explain ,how can i implement to start listen with application socket in nodejs

**Comment by gireeshpunathil** [comment]
@venkappa1 - is this resolved?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
