### ISSUE TITLE
can not uninstall node.js

### ISSUE THREAD

**Issue by duylongpro99** [nodejs/help#2317]
when i uninstall node.js on my computer, i have a problem  
![image](https://user-images.githubusercontent.com/47562458/69612914-3843de00-1063-11ea-83f2-34d2d955d2df.png)
Can anyone help me please???

**Comment by tniessen** [comment]
Does the file at that path exist? If it does, can you delete it?

**Comment by duylongpro99** [comment]
i find it, but the file is broken so i can not delete it

**Comment by tniessen** [comment]
What do you mean with "the file is broken"? Is the file system damaged? Is it write-protected? Are the permissions corrupted?

**Comment by duylongpro99** [comment]
i think that's permissions corrupted

**Comment by tniessen** [comment]
If that is the case, you should be able to remove it as a system administrator. How do you know that you can't delete it? What is the error message, or the observed behavior?

**Comment by Zabrah** [comment]
If you didn't got it deleted: Long time ago I used the tool Unlocker for files that I weren't able to delete. I don't know, if this tool is still good for those things or compatible with current versions of Windows. But maybe it could help, if there's no other way.

**Comment by PoojaDurgad** [comment]
@duylongpro99 - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing, inactive
