### ISSUE TITLE
errors that from requiring files at /temp get added a private prefix

### ISSUE THREAD

**Issue by danielo515** [nodejs/help#2319]
* **Version**: 8.15
* **Platform**: OSX Catalina

Today I got surprised by the following (you can try at node repl):

    require("/tmp/bad.json")
    SyntaxError: /private/tmp/bad.json: Unexpected token n in JSON at position 3

As you can see, I required (intentionally) a JSON file that contains a syntax error. However, on the error message, instead of the actual file path, which starts at `/tmp/` you can see that it has been replaced by the string `/private/`.

Why is this?
I'm using node v8.15.0

**Comment by cjihrig** [comment]
On macOS, `/tmp` is a symlink to `/private/tmp`. If you run `ls -la /`, you should see something like `tmp -> private/tmp` in the output.

**Comment by danielo515** [comment]
Yeah! that's it.
Thanks and sorry.
