### ISSUE TITLE
Expected Modules Functionality in Coming Releases (2020)

### ISSUE THREAD

**Issue by kirkouimet** [nodejs/help#2320]
* **Node.js Version**: 13.2.0

Hi devs,

Had a question for when the ESM module loader is no longer experimental. I understand the feature may graduate early next year and this warning will be removed:

`(node:73264) ExperimentalWarning: The ESM module loader is experimental.`

Will there continue to be a requirement to either name your module file with a `.mjs` ending or include a package.json with `type="module"`? Hoping we will be able to run any `.js` file and use imports and exports without a package.json or `.mjs` ending.

Thanks!

**Comment by devsnek** [comment]
it's very unlikely that js will ever become the esm default. it would require the vast majority of commonjs to switch to the .cjs extension, and at the very least there's a lot of unmaintained code out there that will never change.

**Comment by gireeshpunathil** [comment]
answered, closing
