### ISSUE TITLE
Is it possible to add a path for the new ESM module loader to include for import statements?

### ISSUE THREAD

**Issue by kirkouimet** [nodejs/help#2321]
* **Node.js Version**: 13.2.0

Is there anyway to configure Node with additional directories to search when doing `import`? For example, this package modifies the `Module._resolveFilename` method to add new search paths for `require` calls:

https://www.npmjs.com/package/module-alias

**Comment by devsnek** [comment]
You can use loader hooks for that https://nodejs.org/docs/latest/api/esm.html#esm_experimental_loader_hooks

**Comment by kirkouimet** [comment]
Any way to configure the loader manually after Node has started?
