### ISSUE TITLE
is make jstest fiable?

### ISSUE THREAD

**Issue by juanarbol** [nodejs/help#2322]
* **Node.js Version**: current
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: building/testing
* **Module (and version) (if relevant)**:

Running `make jstest` is fiable? If I do a change, on JS lands, should I run entire test suite, or is it enought by `jstest` _Make_ script?

Same for linting, I think I can save a little of time by just running `make lint-js`, after `make jstest` passed, instead of `make -j4 test`, that takes too long.

**Comment by addaleax** [comment]
Honestly, this depends on what kind of change you’re making.

If you’re modifying something that potentially impacts any Node.js test, running `make test` is recommended.

If you’re modifying something that would only reasonably affect the `http2` module, it should be okay to just run `make -j4 && python tools/test.py -J '*/*http2*' && make lint`.

Generally, try to make sure that the tests that you think *could* be broken by a change still pass afterwards, but keep in mind that even if you don’t run the full test suite, the CI jobs *will* run the full test suite and tell you about issues you might have missed.

**Comment by juanarbol** [comment]
Could you explain me how do I determine "_that potentially impacts any Node.js test_"? I think I don't get it.

**Comment by addaleax** [comment]
@juanarbol I don’t know if I can give you concrete rules, but as an example: If I make changes to our bootstrapping code or to the async hooks code or streams, I know that that runs as part of many tests in our test suite, and so I run `make test`. But if I make changes to HTTP/2, UDP, Workers, or the child process code, then that’s code that’s not run as part of many tests, and usually only the test specifically for that part of the codebase.

**Comment by juanarbol** [comment]
Thank U!

I'm now closing this issue.
