### ISSUE TITLE
Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by honglei** [nodejs/help#2324]
* **Node.js Version**:v12.13.1
* **OS**: Win7 64bit
* **Scope (install, code, runtime, meta, other?)**:  
https://nodejs.org/dist/v12.13.1/node-v12.13.1-x64.msi
* **Module (and version) (if relevant)**: npm 6.12.1

(win64py37) E:\PythonLibs\dmaproxy\tests\grpclib_>npm install -g @angular/cli
npm ERR! Cannot read property 'resolve' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-11-28T06_22_38_
423Z-debug.log

#####

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose npm-session 49f65dec36cd2adf
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest Cannot read property 'resolve' of undefined
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 41ms
10 verbose stack TypeError: Cannot read property 'resolve' of undefined
10 verbose stack     at regFetch (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\index.js:76:23)
10 verbose stack     at fetchPackument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:42:10)
10 verbose stack     at packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:20:10)
10 verbose stack     at getManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:22:10)
10 verbose stack     at manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:13:10)
10 verbose stack     at Object.manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\index.js:17:12)
10 verbose stack     at Object.Fetcher#manifest [as manifest] (C:\Program Files\nodejs\node_modules\npm\node_modules\genfun\lib\genfun.js:15:38)
10 verbose stack     at manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetch.js:23:18)
10 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\manifest.js:24:12
10 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
10 verbose stack     at Promise._execute (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:313:9)
10 verbose stack     at Promise._resolveFromExecutor (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:488:18)
10 verbose stack     at new Promise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
10 verbose stack     at _inflight (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
10 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
10 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose cwd C:\Users\Admin
12 verbose Windows_NT 6.1.7601
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
14 verbose node v12.13.1
15 verbose npm  v6.12.1
16 error Cannot read property 'resolve' of undefined
17 verbose exit [ 1, true ]

**Comment by addaleax** [comment]
This sounds like an issue with npm rather than with Node.js. I’d recommend taking this to https://npm.community/, that’s usually a better place with getting help with npm.

**Comment by richardlau** [comment]
> 
> 
> This sounds like an issue with npm rather than with Node.js. I’d recommend taking this to https://npm.community/, that’s usually a better place with getting help with npm.

https://blog.npmjs.org/post/188841555980/updates-to-community-docs-more
https://npm.community/ is now archived and issues moved back to https://github.com/npm/cli/issues.

**Comment by stringang** [comment]
I too has the same problem.

**Comment by nero120** [comment]
Still getting this on Node.js 12.14.0 / npm 6.13.4 (x64). I had to downgrade to Node.js 11.5.0 / npm 6.4.1 x64 to resolve the issue.

Can we get a fix please?

**Comment by carolalertsense** [comment]
I have the same issue.

Node: 12.16.1 x64
NPM:    6.13.4
Windows 10, 64-bit OS

**Comment by filmaj** [comment]
Same issue here after upgrading from node v10 to v12.

node v12.16.1
npm  v6.13.4
Mac OS X 10.13.6

I ended up removing the `node_modules` for global `npm` package installs, reinstalled `npm` via `npm i -g npm` (which bumped me to npm 6.14.4) and now things are working again.

**Comment by mxmauro** [comment]
It happened to me when I upgraded to the latest release (v12.16.2) by downloading the Windows binary version.

When I compared the `node_modules\npm` directories in my installation and the .zip package, noticed lot of files that seems they were removed on the newer version. Deleted them and NPM stated to work again.

So, before manually upgrade, delete `node_modules\npm` directory.

**Comment by PoojaDurgad** [comment]
@honglei - is this still an issue? I also tried to mimic the steps what you performed in windows 10.
- Download nodejs 12.13.1 (msi installer)
- Install
- In cli 'npm install -g @angular/cli '
didn't throw any error installed successfully, maybe reinstallation of node.js might help you to resolve the problem.

**Comment by gireeshpunathil** [comment]
answered, no follow up, closing
