### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by kacpiy** [nodejs/help#2325]
Hello. I have an issue with mysql connection.
![Przechwytywanie](https://user-images.githubusercontent.com/57981802/69782323-f032d180-11b0-11ea-8b92-0ab946a3632b.PNG)

I always get this error at 17:00 when reading from the database.
Today i got error:  **ECONNABORTED**. Interestingly first query passed successfully and at the second node threw error.

I am sending queries at: 7am, 8am, 9am, 5pm and 6pm. 
At 7,8,9am everything is good, but at 5pm (17:00) an error appears

I noticed that node.js always loses connection with the database at 5pm and repeats the connection because I catch error. Is it possible that because of this? I am using MySQL from xaamp.

**Comment by tniessen** [comment]
There really is no way for us to tell you what is wrong there. Showing us the code that is causing the error might be a start.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
