### ISSUE TITLE
remote controle for  node.js app from my phone

### ISSUE THREAD

**Issue by MaxESP** [nodejs/help#2326]
dear All,

Config:

I have deployed a full home automation app in android studio  in webview.

in this APP I have deploy a Camera index that provide live stream Camera 
by using ffmpeg and node js

That really cooll and working good.

The problem is that my APP.js is running ever and ever consumming a lot  in my node.js Server

PC I5  has server. windows seven
ffmpeg as service 
node js installed.
The goal would be to control this remotely from my app :
how to stop the node.js app from server and start in again when you want to see the stream

**Comment by Strikeeaglechase** [comment]
I dont know if you specifically want an in-app solution, however, in general, you could use a remote connection app such as Termius to control your server from command line

**Comment by Strikeeaglechase** [comment]
Alternatively, you could use [child_process.fork()](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) And just use a low-power server to listen for the start command to start your APP

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
