### ISSUE TITLE
Does Node.js support single byte encoding?

### ISSUE THREAD

**Issue by WasimNaffar** [nodejs/help#233]
We have our software product and it is running in M mode rather than UTF-8 mode, So we use encoding (cp1256 / WINDOWS-1256) for Arabic characters.
My question is: Does the Node.js support M mode (single byte encoding)? Or do I have to define a conversion tool in our application layer to convert from UTF-8 to cp1256 for every transaction between application and Node.js?
BTW when we use a conversion mechanism in our application level from UTF-8 to cp1256, we got some characters as rubbish such as "لا" which is "U+06D9" in Unicode - Arabic table.

Any advice will be highly appreciated.

**Comment by bnoordhuis** [comment]
It's not clear from your description where the data in your application is coming from and going to.

If you only use buffers (i.e., instances of the `Buffer` class), then you don't need to worry about encoding because it's all opaque binary data to node.  Are you converting to or from strings?

**Comment by WasimNaffar** [comment]
to simplify our problem , we do the below example:
1- open a text file and write console.log("مرحبا").
2- then, we save a file as "cp1256" charset in a .js extension.
3- from a terminal we execute the file to display the Arabic output by run : node filename.js.
(the terminal encoding is cp1256 too) 
4- the output will come out as a rubbish

**Comment by bnoordhuis** [comment]
I understand now.  Your issue is that node.js always reads source files as UTF-8.

**Comment by WasimNaffar** [comment]
Exactly... that's why I'm asking if Node.js support "cp1256/windows-1256" as a charset rather than UTF-8. maybe this will solve our issue!

**Comment by bnoordhuis** [comment]
The answer is no, it does not.

**Comment by Kamill90** [comment]
I guess I have same problem but with windows-1250 charset in csv source file. I havent found method to load that file (containing polish symbols ("łódź") as example) and store it in proper encoding. 

Can you help me with it? @WasimNaffar have you managed to solve your problem?

**Comment by bnoordhuis** [comment]
@Kamill90 Read the file as a `Buffer` from disk (with e.g. `fs.readFile()`), then convert it to CP-1250 with iconv or iconv-lite.

**Comment by FazilMuhammed** [comment]
@WasimNaffar how you solve the issue I have too the issue to print Arabic text please help me.

**Comment by fahedyasin** [comment]
HI @FazilMuhammed were you able to resolve the issue for displaying Arabic text?
