### ISSUE TITLE
Brotli compression produces error: ERR_PADDING_2

### ISSUE THREAD

**Issue by prettydiff** [nodejs/help#2330]
I think I am writing the streams wrong.  Would anybody mind reviewing the decompression code and recommend where I am in error?  The following code samples are in TypeScript.  I have searched the web and the nodejs/node repository and cannot find any mention of `ERR_PADDING_2`.

* **Node.js Version**: 13.2.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

## Decompress
```typescript
function (fileResponse:http.IncomingMessage):void {
    const fileName:string = <string>fileResponse.headers.file_name,
        decompress:zlib.BrotliDecompress = zlib.createBrotliDecompress(),
        writeStream:fs.WriteStream = vars.node.fs.createWriteStream(fileName);
    decompress.pipe(writeStream);
    fileResponse.on("data", function (fileChunk:Buffer):void {
        decompress.write(Buffer.from(fileChunk));
    });
    fileResponse.on("end", function ():void {
        decompress.end();
    });
    fileResponse.on("error", function (error:nodeError):void {
        console.log(error);
    });
}
```
## Compress
I am using this code in a peer-to-peer application.  The file is at: https://github.com/prettydiff/share-file-systems/blob/brotli/lib/terminal/server/fileService.ts and the code above is abbreviated from the writeStream function on line 331.

On line 831 is where I am appling the compression: https://github.com/prettydiff/share-file-systems/blob/brotli/lib/terminal/server/fileService.ts#L831

```
readStream.pipe(compress).pipe(response);
```

## Error message

```
Error: Decompression failed
    at BrotliDecoder.zlibOnError [as onerror] (zlib.js:170:17)
Emitted 'error' event on BrotliDecompress instance at:
    at BrotliDecoder.zlibOnError [as onerror] (zlib.js:173:8) {
  errno: -15,
  code: 'ERR_PADDING_2'
}
```

**Comment by Hakerh400** [comment]
> I have searched the web and the nodejs/node repository and cannot find any mention of ERR_PADDING_2

That error is defined [here](https://github.com/nodejs/node/blob/7da6630aa4a3ba7f866be3af83ccd812102c281b/deps/brotli/c/dec/decode.c#L2414-L2417) and [here](https://github.com/nodejs/node/blob/7da6630aa4a3ba7f866be3af83ccd812102c281b/deps/brotli/c/include/brotli/decode.h#L85). The error simply tells you that the buffer represented by the stream is not properly compressed, so it cannot be decompressed. For example, if you run

```js
zlib.brotliDecompressSync(Buffer.from([0x0E]));
```

it will throw the same error. Try to pipe `fileResponse` directly to some file, then inspect it using a hex editor and see if you can figure out what the problem is. If the file does not look like an array of random bytes, it is probably not compressed properly.

**Comment by prettydiff** [comment]
I have altered my approach so that I am passing in chunks from the response into the zlib.brotliDecomparess method and it always results in a `Error: Decompression failed` for each chunk.

```typescript
fileResponse.on("data", (fileChunk:Buffer):void {
    zlib.brotliDecompress(fileChunk, function (brotliError:nodeError, segment:Buffer):void {
        if (brotliError !== null) {
            console.log(brotliError.toString());
        } else {
            writeStream.write(segment);
        }
    });
});
```

Am I compressing incorrectly?
```typescript
const hash:Hash = crypto.createHash("sha512"),
    hashStream:fs.ReadStream = fs.ReadStream(data.location[0]);
hashStream.pipe(hash);
hashStream.on("close", function ():void {
    const readStream:fs.ReadStream = fs.ReadStream(data.location[0]),
        compress:zlib.BrotliCompress = zlib.createBrotliCompress();
    response.setHeader("hash", hash.digest("hex"));
    response.setHeader("file_name", data.remoteWatch);
    response.setHeader("file_size", data.depth);
    response.setHeader("cut_path", data.location[0]);
    response.writeHead(200, {"Content-Type": "application/octet-stream; charset=binary"});
    readStream.pipe(compress).pipe(response);
});
```

**Comment by Hakerh400** [comment]
Consider the following two pieces of code. They represent the correct way to compress and decompress a file and send it over the network. You probably have some mistake somewhere deep in your code, but it is hard to tell without digging too much into it. I suggest you to compare your code with this and try to see what you are doing wrong.

**Example 1**

1. Client reads a local file
2. Client compresses it
3. Client sends it to the server
4. Server decompresses the file
5. Server saves the file

```js
const port = 80;
const input = 'input.txt';
const output = 'output.txt';
const server = http.createServer((req, res) => {
  req.pipe(zlib.createBrotliDecompress()).
    pipe(fs.createWriteStream(output)).
    on('close', () => (res.end(), server.close()));
}).listen(port);
const req = http.request({
  hostname: 'localhost',
  port,
  path: '/',
  method: 'POST',
});
fs.createReadStream(input).
  pipe(zlib.createBrotliCompress()).
  pipe(req);
```

**Example 2**

1. Server reads a local file
2. Server compresses it
3. Server sends it to the client
4. Client decompresses the file
5. Client saves the file

```js
const port = 80;
const input = 'input.txt';
const output = 'output.txt';
const server = http.createServer((req, res) => {
  fs.createReadStream(input).
    pipe(zlib.createBrotliCompress()).
    pipe(res);
}).listen(port);
const req = http.request({
  hostname: 'localhost',
  port,
  path: '/',
  method: 'POST',
}, res => {
  res.pipe(zlib.createBrotliDecompress()).
    pipe(fs.createWriteStream(output)).
    on('close', () => server.close());
});
req.end();
```

**Comment by prettydiff** [comment]
The compression streams are working for me now.  I had to delete this branch and work out some serious regression issues.

I am testing a large file transfer, 17.8gb, from one computer to another on my home network.  I am using all the defaults for Brotli compression, which is maximum performance at setting `11`.  I am noticing this is dramatically slower than transfers without compression.  I am watching the CPU and network performance graphs on Windows and my big learning here is that compression is not CPU heavy, but it takes time per chunk resulting in fewer packets per second.  The result, in this case, is hours of transfer time instead of maybe 10-15 seconds.
