### ISSUE TITLE
Previous Package Download

### ISSUE THREAD

**Issue by autumnHoward** [nodejs/help#2333]
* **Node.js Version**: 10.x
* **OS**: Mac
* **Scope**: install

Hi all, I'm trying to find where to download the node-v10.17.0.pkg file,
forgive me if it should be obvious. I found the index of recent builds, but am not sure how to download the actual package?

**Comment by gireeshpunathil** [comment]
https://nodejs.org/download/release/v10.17.0/node-v10.17.0.pkg

For previous releases, I go like this:
 - https://nodejs.org/en/
 - click on other downloads
 - then go to previous releases
 - search and find the version you want
 - click on Downloads option
 - pick choose the right platform you want from the list

Hope this helps!

**Comment by PoojaDurgad** [comment]
@autumnHoward - were you able to follow @gireeshpunathil 's suggestion?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
