### ISSUE TITLE
Make node docker friendly

### ISSUE THREAD

**Issue by temirfe** [nodejs/help#2335]
I started learning node.I don't want to download and install mysql, instead I wanted to use it on docker where I already have a mysql container. But dockerizing nodejs is not the easiest thing in the world, creating volumes overrides npm install on container and stuff..

Please make it easier for beginners.

**Comment by gireeshpunathil** [comment]
@temirfe  - multiple dockerized versions of node exists; please review the content of https://github.com/nodejs/docker-node and see if it helps you

> creating volumes overrides npm install on container

can you elaborate on this part? what exactly the problem here is?

**Comment by temirfe** [comment]
@gireeshpunathil thanks for the link, it now works. I was misled by this article from official node guide which installs modules on container. After following that guide I also wanted to create volume, but that deletes modules on container.
