### ISSUE TITLE
external/integratedTerminal issues and readline, ttys, readline-sync, prompt, node module errors etc.

### ISSUE THREAD

**Issue by A-Here-And-Now** [nodejs/help#2338]
* **Version**: v10.13.0
* **Platform**: VS Code 1.36.0
* **Subsystem**: ??

I hope you all enjoyed your Thanksgiving holiday.

I am having a lot of trouble just trying to get a simple user-interactive username/password input running on node in Visual Studio Code.

First I saw that I just needed the readline library then use the following:

```
var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

rl.question("password : ", function(password) {
    console.log("Your password : " + password);
});
```

but even though i put "externalTerminal" in the launch.json's 'console' property, I saw no terminal show up at any time in my script.

So I thought to try readline-sync, as maybe I wasn't understanding the asynchronous processing.

But when I use the following from readline-sync:

```
readlineSync = require('readline-sync');

uName = readlineSync.question("password?");
```

I got this error which I've found out must be some kind of node problem (didn't seem to be a problem for node 8.x.x versions but before and after it has been reported to be a problem):

```
C:\Program Files\nodejs\node.exe[11016]: src\node_file.cc:1610: Assertion `(argc) == (5)' failed.
  1: 00007FF66BD4ECE5 
  2: 00007FF66BD28196 
  3: 00007FF66BD28261 
  4: 00007FF66BCED571 
  5: 00007FF66C552E52 
  6: 00007FF66C5542ED 
  7: 00007FF66C553349 
  8: 00007FF66C55322B 
  9: 0000019E319DC5C1 
```

I have no idea what to do about this, but I read that it happens because readline-sync can't operate without tty or ttys, so I downloaded and incorporated those libraries but now when ttys tries to load with:

`ttys = require('ttys');`

I just get this error (which when I navigate to the github repository @ https://github.com/TooTallNate/ttys/issues the error is reported but not solved or commented on in over a year):

`Error: ENOENT, no such file or directory '/dev/tty'`

Any help, pointers, insight or work-arounds of any kind would be very much appreciated... Ultimately I would very much like to receive an explanation of what is going on with these errors and why these environments are having these issues, whether there is anything I myself can do to avoid these errors or understand them so that I can work towards a simple fix myself.

Thank you all.

**Comment by PoojaDurgad** [comment]
@A-Here-And-Now - Please close the issue, as it already mentioned in the https://github.com/nodejs/help/issues/2337

**Comment by gireeshpunathil** [comment]
answered in #2337,  closing. feel free to re-open if it is outstanding
