### ISSUE TITLE
NPM Packages keep installing into a non existing node version

### ISSUE THREAD

**Issue by jaredStevens** [nodejs/help#2339]
* **Node.js Version**:  11.0.0
* **OS**: Mac
* **Scope (install, code, runtime, meta, other?)**: Install . Any npm package I install goes to v11.0.0 and I don't have that version installed.  I can't get my npm packages to install in the right versions.
* **Module (and version) (if relevant)**:

```js
<img width="1185" alt="Screen Shot 2019-12-04 at 4 11 40 PM" src="https://user-images.githubusercontent.com/33605663/70186390-74092400-16b1-11ea-877f-61c8fc24b958.png">

```

**Comment by marialani** [comment]
If you have to install an older version of a package just specify it

npm install <package>@<version>

**Comment by PoojaDurgad** [comment]
@jaredStevens - did @marialani 's suggestion help you to resolve the issue? or is this still outstanding?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
