### ISSUE TITLE
Can't start node.js installer

### ISSUE THREAD

**Issue by takeoveragario** [nodejs/help#234]
While I download node.js (any version) on Windows 10 it downloads as an WinRAR archieve. While I open it it says: "WinRAR: This archieve is corrupt". What should I do?

**Comment by addaleax** [comment]
Where are you downloading from? The official files can be found at https://nodejs.org/en/download/current/ or https://nodejs.org/en/download/.

**Comment by kahwee** [comment]
If you try to open the `.exe` or `.msi` file, it should not be launching WinRAR. If it did the extensions may be wrongly associated. 

There are [some instructions here](http://www.askvg.com/solution-exe-files-always-open-with-notepad-or-other-applications/) once you determine this is the case.
