### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by josevitormorais** [nodejs/help#2343]
Node.js  - 10.16.3

---------- este é o erro que aparece no meu terminal -----------
(node:2776) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type 
undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:161:7)
    at ExpressHandlebars._resolveLayoutPath (C:\Users\Notebook\Documents\Curso Rocketseat\nodejs\modulo3\node_modules\express-handlebars\lib\express-handlebars.js:342:17)
    at ExpressHandlebars.<anonymous> (C:\Users\Notebook\Documents\Curso Rocketseat\nodejs\modulo3\node_modules\express-handlebars\lib\express-handlebars.js:223:35)
(node:2776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). (rejection id: 1)

------- este é o meu codigo ------------
--------- Controller.js ------------

const Ad = require('../models/Ad')
const User = require('../models/User')
const Mail = require('../services/Mail')

class PurchaseController {
  async store (req, res) {
    const { ad, content } = req.body

    const purchaseAd = await Ad.findById(ad).populate('author')

    const user = await User.findById(req.userId)

    await Mail.sendMail({
      from: '"Jose Vitor morais" <josevitormorais100@gmail.com>',
      to: purchaseAd.author.email,
      subject: `Solicitação de compra: ${purchaseAd.title}`,
      template: 'purchase',
      context: { user, content, ad: purchaseAd }
    })
    return res.send()
  }
}

module.exports = new PurchaseController()

------ Mail.js ----------

**Comment by josevitormorais** [comment]
----- Mail.js -------------
const path = require('path')
const nodemailer = require('nodemailer')
const mailConfig = require('../../config/mail')
const hbs = require('nodemailer-express-handlebars')
const exphbs = require('express-handlebars')
const transport = nodemailer.createTransport(mailConfig)

const viewPath = path.resolve(__dirname, '..', 'views', 'emails')

transport.use('compile', hbs({
  viewEngine: exphbs.create({
    partialsDir: path.resolve(viewPath, 'partials')

  }),
  viewPath,
  extName: '.hbs'
}))

module.exports = transport

**Comment by viniciusaugutis** [comment]
I have the same problem here

**Comment by viniciusaugutis** [comment]
@josevitormorais I resolved this in this way:

I installed the express3-handlebars and replaced the dependency "express-handlebars"

yarn add express3-handlebars

This work for me!!!

Here the final code:

`const path = require('path')
const nodemailer = require('nodemailer')
const mailConfig = require('../../config/mail')
const hbs = require('nodemailer-express-handlebars')
const exphbs = require('express3-handlebars')
const transport = nodemailer.createTransport(mailConfig)

const viewPath = path.join(__dirname, '..', 'views', 'emails')

transport.use('compile', hbs({
  viewEngine: exphbs.create({
    partialsDir: path.join(viewPath.toString(), 'partials')

  }),
  viewPath: viewPath.toString(),
  extName: '.hbs'
}))

module.exports = transport
`

**Comment by Ezequiel1057** [comment]
thanks pikinin this helped me

**Comment by josevitormorais** [comment]
hello, beauty friends ?, thanks for the help, I was kind of idle for a while. but thank you for your attention

**Comment by PoojaDurgad** [comment]
@josevitormorais - is this still outstanding? if that is not the case can you please close the issue .

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
