### ISSUE TITLE
async disabled on 32 bits :/

### ISSUE THREAD

**Issue by mikiiiiiiiiiii** [nodejs/help#2344]
async is disabled on 32 bits but async is really useful why is it disabled ?
![32bitsasync](https://user-images.githubusercontent.com/58670436/70397636-4525e180-1a14-11ea-9950-882af25c9f0a.PNG)

**Comment by bnoordhuis** [comment]
See commit nodejs/node@a0895ed6c48 - the V8 inspector uses 32 bits values (on 32 bits platforms) while Node.js needs 64 bits values to record the necessary metadata.

There might be ways around that but no one probably cared enough to fix it. If you've felt the urge to get involved with Node.js core development but never knew where to start, hey, you might just have found yourself a good project. :-)

**Comment by PoojaDurgad** [comment]
ping @mikiiiiiiiiiii - did @bnoordhuis 's  suggestion help you to get rid of this issue?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
