### ISSUE TITLE
Error: The module '/apps/node-apps/server/node_modules/node-expat/build/Release/node_expat.node' was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by ashishprasher** [nodejs/help#2345]
I am upgrading my node version from v8.9.4 to node v12.13.1 on my test server
steps I followed for the same:
upgraded node version by this command
> nvm install  v12.13.1

removed node_modules folder 

> rm -rf node_modules

removed package-lock.json

> rm package-lock.json

installed node modules

> npm install

modules got installed succesfully, but when I am reloading the server I am getting this error
**Error: The module '/apps/node-apps/server/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)**

I have tried npm rebuild as well

**Comment by richardlau** [comment]
@ashishprasher `This version of Node.js requires NODE_MODULE_VERSION 57` implies that you are running your server with Node.js 8 still (while the `was compiled against a different Node.js version using
NODE_MODULE_VERSION 72` implies that your `npm rebuild` used Node.js 12).

**Comment by abuabbas1991365** [comment]
rm -rf node_modules
yarn install

**Comment by cboy19** [comment]
Not able to install bot with nodejs (typescript). getting the below error when try to deploy to azure D:\home\site\wwwroot\node_modules\node-expat\build\Release\node_expat.node is not a valid Win32 application

Update the appservice with bit 64, still no luck

**Comment by PoojaDurgad** [comment]
@ashishprasher - is this still outstanding? were you able to follow @richardlau 's and @abuabbas1991365 's suggestion?
 to me this issue looks similar to https://github.com/mscdex/cap/issues/92 hopefully this may help you to resolve the issue.

**Comment by rachitkohli7** [comment]
> rm -rf node_modules
> yarn install

This worked for me, Thanks.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
