### ISSUE TITLE
writeFile corrupts data with high frequency requests on same file

### ISSUE THREAD

**Issue by anywhichway** [nodejs/help#2346]
* **Version**: v12.13.0
* **Platform**: 64-bit (Windows 10)
* **Subsystem**:  fs

```
const fs = require('fs'),
  assert = require('assert')
  file = './foo.json';

const numbers = [];
async function verify() {
	const number = Math.random();
	numbers.push(number);
	await fs.promises.writeFile(file, JSON.stringify({number}), "utf-8");
	const data = JSON.parse(fs.readFileSync(file,"utf-8"));
	// since we await the write and then read synchronously immediately
	// we expect the data to be what was just written
	assert.equal(data.number,number);
	// what is actually experienced is a corrupt file
	// SyntaxError: Unexpected token } in JSON at position 29
	// Modifying the read to be asynchronous will also throw an error
	// but this is expected since another write may have been done before the read.
	// Expected behavior: The file should never be in a partially written state
	// once the writeFile await is resolved. We presume that internally, Node is
	// not truncating the file to the new length prior to resolving the Promise.
}

try {
	fs.unlinkSync(file);
} catch(e) {
	if(e.code!=="ENOENT") {
		throw(e)
	}
}
(async () => {
	for (var i = 0; i < 10; i++) {
		await verify();
	}
	console.log("await loop ok")
})().then(() => {
	const promises = [];
	for (var i = 0; i < 10; i++) {
		promises.push(verify());
	}
	Promise.all(promises)
		.then(() => console.log("no await loop ok"))
		.catch((e) => {
			console.log(numbers);
			console.error(e);
		})
})
```

Although we have not been able to reproduce it with a small code sample, under high load we have experienced the same corruption when both the write and the read use the fs.promises module and the writes and reads are always awaited with moderate file content sizes, e.g. 1K or less. For now, if we make everything synchronous, we have no issues. This is a big step up from earlier versions of node; however, it obviously has a negative impact on our app overall. 

A similar issue is documented here: https://github.com/nodejs/node-v0.x-archive/issues/4965

**Comment by anywhichway** [comment]
@addaleax please see the code below (cut from the example), it does wait for the callback, that is what resolves the promise. I do understand that if I await in the outer loop things are fine (my very first example does that). What I am trying to get my head wrapped around is how to get high speed writes invoked by arbitrary clients to not collide with each other without going synchronous.

```js
return new Promise((resolve,reject) => {
		fs.writeFile(file, JSON.stringify({number}),{flag},() => resolve());
	}).then(() => {
		const data = JSON.parse(fs.readFileSync(file,"utf-8"));
		// since the callback to writeFile has been invoked
		// we expect the data to be what was just written
		assert.equal(data.number,number);
		// what is actually experienced is a corrupt file
		// SyntaxError: Unexpected token } in JSON at position 29
	})
```

The below code using streams is subject to the same issue:

```js
function verifyWithStream() {
	const number = Math.random(),
		wstream = fs.createWriteStream(file);
	numbers.push(number);
	wstream.on("finish", () => {
		const data = JSON.parse(fs.readFileSync(file,"utf-8"));
		//assert.equal(data.number,number);
	})
	wstream.write(JSON.stringify({number,stream:true}))
	wstream.end();
}
```

There are only two hypotheses I can arrive at given the extra "}". Either Node is opening the file for the next write while the sync read is occurring and manages to get characters in after the reads gets the first few and a new "}" is picked-up at  the end before read returns. Or, the write operations are surrendering without truncating the file to the new length and flushing to disk.

If a developer has to understand all of the nesting down to file operations (in code the developer potentially did not write) it will make debugging really hard.

**Comment by anywhichway** [comment]
@addaleax I realized that there is one other possibility, the way Promises get queued:

Let P1,P2,P3 be promises and T1,T2,T3 be their respective thens.

Option 1:

P1 resolves and the processing of the next promise P2 starts then T1 is invoked

Option 2:

P1 resolves and the processing of T1 is started prior to starting P2.

I realize now that Option 1 is what is occurring because Promises don't actually wait to start. A theoretical complaint a few people have made about Promises. 

I will just have to create a queue.

**Comment by addaleax** [comment]
> I realize now that Option 1 is what is occurring because Promises don't actually wait to start.

Yes, that’s probably it – Promises aren’t asynchronous tasks, they represent the results of asynchronous tasks.
