### ISSUE TITLE
socket: (10022) An invalid argument was supplied.

### ISSUE THREAD

**Issue by Strikeeaglechase** [nodejs/help#2348]
* **Version**: 12.13.1 LTS
* **Platform**: WIndows 64
* **Subsystem**: n/a

Whenever I run nodejs I get "socket: (10022) An invalid argument was supplied.". I the same problem [here](https://github.com/npm/npm/issues/6518), however, their solution listed [here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/3076a9cd-57a0-418d-8de1-07adc3b486bb/socket-fails-with-error-10022-when-application-is-run-from-certain-network-shares-on-vista-and?forum=wsk) had to do with their permissions on the network drive.

I am also attempting to run my code on a network drive however am unable to change the owner file permissions as we are using this type of format: 
share -> users -> myuser
I have permissions over myuser and the subdirectories however not over the "users" folder. How can I get nodejs to work without it?

P.S. Im running the node excludable directly from the extracted zip, no installation of nodejs

**Comment by bnoordhuis** [comment]
I'm moving this issue to nodejs/help because the answer to this question:

> How can I get nodejs to work without it? (where it=appropriate permissions)

Is pretty much "you don't" - it's basically a system error that Node.js can't work around. It sounds like you'll have to contact your system administrator.

**Comment by Strikeeaglechase** [comment]
Why does nodejs need the permissions? I have full ownership over the files it's running in. I am wondering if there is a method to run it that doesn't require the permissions about it

**Comment by bnoordhuis** [comment]
Node.js needs those permissions indirectly / transitively because the user-space part of the TCP stack needs them. It's not specific to Node.js, other Winsock-based programs need them too.

**Comment by Strikeeaglechase** [comment]
Is the TCP stack critical in non-network related usage of nodejs? Is there any way to run node without it?

**Comment by bnoordhuis** [comment]
That question comes up from time to time. The answer is that yes, it's _probably_ possible to modify node / libuv to run in such an environment but no one cared enough so far to do the work.

**Comment by Strikeeaglechase** [comment]
Well seems like no easy way to get around needing permissions as of right now so closing it. Thanks for you help
