### ISSUE TITLE
Import ED25519 Key generated from golang into Nodejs

### ISSUE THREAD

**Issue by pdufour** [nodejs/help#2349]
* **Node.js Version**: 12.13.1
* **OS**: Mac OS
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: crypto

Hello! So I have a ED25519 key I am generating in Golang: 

https://play.golang.org/p/6GHGBJssVmJ

(I have an existing resource generating these keys that I cannot move to Nodejs)

I then try to load the same key and I am getting an error that says `error loading private key`

````
const crypto = require('crypto');
crypto.sign(
  null,
  Buffer.from('msg'),
  { key: Buffer.from(key, 'base64'). format: 'der', type: 'pkcs8' }
````

Using a key generated from Nodejs using generateKeyPairSync works, so I'm not sure what the difference between the two keys would be. They are both 64 bytes.

**Comment by bnoordhuis** [comment]
I'm going to guess that golang emits the raw key. It's not PKCS#8 at any rate. You can check like this:
```
$ ./a.out | base64 -D | openssl pkcs8 -inform der
Error reading key
4303037888:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:/build/openssl/openssl/crypto/asn1/asn1_lib.c:101:
```
Where `a.out` is your go program.

**Comment by pdufour** [comment]
Solved! You're a champ @bnoordhuis .
````
    const CryptoKeyComposer = require('crypto-key-composer');
    const pem = CryptoKeyComposer.composePrivateKey({
      format: 'pkcs8-pem',
      keyAlgorithm: KEY_ALGORITHM,
      keyData: {
        seed
      },
      encryptionAlgorithm: null
    });
````
