### ISSUE TITLE
Node.js Problems

### ISSUE THREAD

**Issue by PaulTsai20160627** [nodejs/help#235]
Hi Node.js Members:

I am using node-v4.4.7-linux-x86 as my platform for coding Node.js

I encouter one problem that can not figure out.

The main problem is why the node.js can not found my localhost/start and localhost/upload

So, the output always show No request handler found for /start or /upload

I check serveral times that the program does not have any typing errors or usage errors.

Can anyone know why this problems happen ?

Besides, what is the /favicon.ico ?

PS: My coding program and outputs are all shown as attached files, please review. !
![prob1](https://cloud.githubusercontent.com/assets/20158340/17268452/e2efad30-565c-11e6-9a45-90f9b0b5830b.jpg)
![prob2](https://cloud.githubusercontent.com/assets/20158340/17268453/e2f4faa6-565c-11e6-8be4-4e75d0963642.jpg)
![prob3](https://cloud.githubusercontent.com/assets/20158340/17268454/e2f53368-565c-11e6-8f12-7addd8b8497a.jpg)
![prob4](https://cloud.githubusercontent.com/assets/20158340/17268455/e2fb568a-565c-11e6-9329-9a73a4ca6cbf.jpg)
![prob5](https://cloud.githubusercontent.com/assets/20158340/17268456/e2fe93e0-565c-11e6-8422-525a51b3b74d.jpg)
![prob6](https://cloud.githubusercontent.com/assets/20158340/17268457/e2ffcfb2-565c-11e6-9073-3a4e3d7b03de.jpg)

**Comment by kahwee** [comment]
There's a missing file `requestHandlers.js` in your screenshots. Can you commit your code to GitHub so we can take a look easily?

Also, `favicon.ico` is a file that browsers request from the root path to check if there's an icon that can be used for the website. You can learn more [on favicons here](http://www.webdesignerdepot.com/2012/11/whats-the-point-of-favicons/).

**Comment by PaulTsai20160627** [comment]
Hi Kahwee:

The requestHandlers.js is shown as attached file below. please check and give some help ! 
![prob4](https://cloud.githubusercontent.com/assets/20158340/17269238/bcce7e7e-5675-11e6-9266-c812ea0892ce.jpg)

**Comment by kahwee** [comment]
@PaulTsai20160627 Can you commit your source code to GitHub?

**Comment by PaulTsai20160627** [comment]
index.js
`var server = require("./server5");
var router = require("./route");
var requestHandlers = require("./requestHandlers");
var handle ={}
handle["/"] = requestHandlers.start;
handle["/start"] = requestHandlers.start;
handle["/upload"] = requestHandlers.upload;
server.start(router.route,handle);`

server5.js
`var http = require("http");
var url = require("url");
function start(route,handle){
function onRequest(request,response) {
  var pathname = url.parse(request.url).pathname;
  console.log(" Request for "+ pathname + "received" );
  route(route,pathname,response);
}
http.createServer(onRequest).listen(8888);
console.log("Server has Started");
}
exports.start = start;
`
route.js
`function route(handle,pathname,response){
  console.log("About to route a request for "+ pathname);
  if(typeof handle[pathname] === 'function') {
    handle[pathname](response);
  } else {
    console.log("No request handler found for " + pathname);
    response.writeHead(404,{"Content-Type": "text/plain"});
    response.write("404 Not found");
    response.end();
  }
}


exports.route = route;`

requestHandlers.js
`var exec = require("child_process").exec;
function start(response){
  console.log("Request handler 'start' was called");
  //var content = "empty";
  exec("find /",{timeout: 10000,maxBuffer:20000*1024},
  function(error,stdout,stderr){
    response.writeHead(200,{"Content-Type": "text/plain"});
    response.write(stdout);
    response.end();
});
/*
  exec("ls -lah", function (error,stdout,stderr){
    response.writeHead(200,{"Content-Type": "text/plain"});
    response.write(stdout);
    response.end();
    //content = stdout;
  });
*/
  //return content;
/*
  function sleep(milliSeconds){
  var startTime = new Date().getTime();
  
  while(new Date().getTime() < startTime + milliSeconds);
  }
  sleep(10000);
  
  return "Hello Start";
*/
}


function upload(response){
  console.log("Request handler 'upload' was called");
  response.writeHead(200,{"Content-Type": "text/plain"});
  response.write("Hello Upload");
  response.end();

  //return "Hello Upload";
}

exports.start = start;
exports.upload = upload;`

**Comment by PaulTsai20160627** [comment]
index.js

`var server = require("./server5");
var router = require("./route");
var requestHandlers = require("./requestHandlers");
var handle ={}
handle["/"] = requestHandlers.start;
handle["/start"] = requestHandlers.start;
handle["/upload"] = requestHandlers.upload;
server.start(router.route,handle);`

**Comment by PaulTsai20160627** [comment]
server5.js

`var http = require("http");
var url = require("url");
function start(route,handle){
function onRequest(request,response) {
  var pathname = url.parse(request.url).pathname;
  console.log(" Request for "+ pathname + "received" );
  route(route,pathname,response);
}
http.createServer(onRequest).listen(8888);
console.log("Server has Started");
}
exports.start = start;
`

**Comment by PaulTsai20160627** [comment]
`function route(handle,pathname,response){
  console.log("About to route a request for "+ pathname);
  if(typeof handle[pathname] === 'function') {
    handle[pathname](response);
  } else {
    console.log("No request handler found for " + pathname);
    response.writeHead(404,{"Content-Type": "text/plain"});
    response.write("404 Not found");
    response.end();
  }
}


exports.route = route;`

**Comment by PaulTsai20160627** [comment]
`function route(handle,pathname,response){
  console.log("About to route a request for "+ pathname);
  if(typeof handle[pathname] === 'function') {
    handle[pathname](response);
  } else {
    console.log("No request handler found for " + pathname);
    response.writeHead(404,{"Content-Type": "text/plain"});
    response.write("404 Not found");
    response.end();
  }
}
exports.route = route;`

**Comment by PaulTsai20160627** [comment]
`var exec = require("child_process").exec;
function start(response){
  console.log("Request handler 'start' was called");
  //var content = "empty";
  exec("find /",{timeout: 10000,maxBuffer:20000*1024},
  function(error,stdout,stderr){
    response.writeHead(200,{"Content-Type": "text/plain"});
    response.write(stdout);
    response.end();
});
/*
  exec("ls -lah", function (error,stdout,stderr){
    response.writeHead(200,{"Content-Type": "text/plain"});
    response.write(stdout);
    response.end();
    //content = stdout;
  });
*/
  //return content;
/*
  function sleep(milliSeconds){
  var startTime = new Date().getTime();
  
  while(new Date().getTime() < startTime + milliSeconds);
  }
  sleep(10000);
  
  return "Hello Start";
*/
}
function upload(response){
  console.log("Request handler 'upload' was called");
  response.writeHead(200,{"Content-Type": "text/plain"});
  response.write("Hello Upload");
  response.end();
  //return "Hello Upload";
}
exports.start = start;
exports.upload = upload;`

**Comment by kahwee** [comment]
I'm not sure what you are trying to achieve here. In `server5.js`, you are passing `route` parameter into your `route()`. This should be passing in `handle`.

Your `server5.js` should look like this with `route` changed to `handle`:

```
var http = require('http')
var url = require('url')
function start (route, handle) {
  function onRequest (request, response) {
    var pathname = url.parse(request.url).pathname
    console.log(' Request for ' + pathname + 'received')
    route(handle, pathname, response)
  }
  http.createServer(onRequest).listen(8888)
  console.log('Server has Started')
}
exports.start = start
```

**Comment by kahwee** [comment]
I committed the source code here ([kahwee/help-235](https://github.com/kahwee/help-235)) if someone else have a better idea.
