### ISSUE TITLE
npm_package_version is undefined

### ISSUE THREAD

**Issue by cawoodm** [nodejs/help#2354]
* **Version**: v13.2.0
* **Platform**: Windows Server 2012 R2

`process.env.npm_package_version` is "sometimes" undefined i.e. on some of our systems/apps it appears and on others it's `undefined` although we have a valid value set in `package.json`.

What is the rule/reason for npm_package_version being set or not?

**Comment by richardlau** [comment]
At a guess it'll be whether the app was started via an `npm` script (in which it should be set) or run directly as `node <app>` as Node.js doesn't know anything about npm environment variables.

**Comment by cawoodm** [comment]
You nailed it!

What a pity as we want our running apps to know their version. I guess we'll have to `require('./package.json')` or something.

**Comment by davidzwa** [comment]
@cawoodm you can still provide interoperability by setting the environment variable yourself. Yes this does include path.join(__dirname, 'package.json') kind of approach, but to be honest this is what you do by running NPM scripts.

**Comment by Benjythebee** [comment]
> What a pity as we want our running apps to know their version. I guess we'll have to require('./package.json') or something.

An issue I have with `require('./package.json')` is the security concern:

```
Doing this with Browserify has security implications.
Be careful not to expose your package.json to the client, as it means that all your dependency version numbers, build and test commands and more are sent to the client.
If you're building server and client in the same project, you expose your server-side version numbers too. Such specific data can be used by an attacker to better fit the attack on your server.
```
 [good old stackoverflow](https://stackoverflow.com/questions/9153571/is-there-a-way-to-get-version-from-package-json-in-nodejs-code)

I guess I'll use [genversion](https://www.npmjs.com/package/genversion)

**Comment by TheMangoTrain** [comment]
**Re: package.json method**

If it helps, you would presumably just pass the `version` ...

```
const fs = require('fs')
const packageJson = fs.readFileSync('./package.json')
const version = JSON.parse(packageJson).version || 0
```
Use discretion, you know, just like... other important data (like env's), some you pass to client, some not.

**Comment by Lsnsh** [comment]
https://docs.npmjs.com/cli/v10/using-npm/scripts#packagejson-vars

> [package.json vars](https://docs.npmjs.com/cli/v10/using-npm/scripts#packagejson-vars)
The package.json fields are tacked onto the `npm_package_` prefix. So, for instance, if you had `{"name":"foo", "version":"1.2.5"}` in your package.json file, then your package scripts would have the `npm_package_name` environment variable set to "foo", and the `npm_package_version` set to "1.2.5". You can access these variables in your code with `process.env.npm_package_name` and `process.env.npm_package_version`, and so on for other fields.

> See [package.json](https://docs.npmjs.com/cli/v10/configuring-npm/package-json) for more on package configs.
