### ISSUE TITLE
Buffers Character Encodings `binary` and `latin1`, which is more recommended?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [nodejs/help#2355]
nodejs v6.4.0 Introduced `latin1` as an alias for `binary`.
 
Buffers Character Encodings `binary` and `latin1`, which is more recommended?

**Comment by bnoordhuis** [comment]
latin1 - binary is just an alias for latin1 at this point.

**Comment by addaleax** [comment]
Also, shameless plug: [Twitter thread by me](https://twitter.com/addaleax/status/1189711048682680320) on why we had `binary` and why it’s not really an accurate name

**Comment by PoojaDurgad** [comment]
@xiaoxiangmoe - is this still outstanding?

**Comment by PoojaDurgad** [comment]
@xiaoxiangmoe - is this still outstanding?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
