### ISSUE TITLE
Node.js server don't show up

### ISSUE THREAD

**Issue by mehedi-tanjil** [nodejs/help#2356]
Please help me
 
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\Mehedi\test-node.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:690:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by ankushsomani09** [comment]
I am facing same error. Did you get any solution ?
are you using it for lwc-service of salesforce?

**Comment by PoojaDurgad** [comment]
@mehedi-tanjil and @ankushsomani09 - can you elaborate the issue please? Like which command you are trying to run? which version of nodejs you are currently using? so that it will be helpful to debug your error.

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
