### ISSUE TITLE
Deadlock calling a function on null - v12.13.1 Windows64

### ISSUE THREAD

**Issue by cracker0dks** [nodejs/help#2357]
Version: v12.13.1
OS: Win64

If have this function
```
var test = function (obj) {
    obj.getId();
}
```
and call: `test(null)`
I get: `TypeError: Cannot read property 'getId' of null` this is correct!

But here: 
```
dc.on('DC_EVENT_INCOMING_MSG', () => { //this is a binding on a rust program
    test(null)
})
```
I get a deadlock... no retrun, no crash... but also not working any further.

------------
PS: On Node v11 I get this error on the same code:
```
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
 1: 00007FF7E2AFF43A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4618
 2: 00007FF7E2AAD186 uv_loop_fork+86646
 3: 00007FF7E2AADC4D uv_loop_fork+89405
 4: 00007FF7E30A9DCA v8::internal::HandleScope::Extend+90
 5: 00007FF7E2AE30C9 node::Stop+33561
 6: 00007FF7E2ECC597 _v8_internal_Print_TransitionTree+3671
 7: 00007FF7E2ECC0F9 _v8_internal_Print_TransitionTree+2489
 8: 00007FF7E2A53420 v8::internal::StackGuard::ArchiveSpacePerThread+49344
 9: 00007FF7E2A53A00 v8::internal::StackGuard::ArchiveSpacePerThread+50848
10: 00007FF7E2B4E294 uv_dlerror+2452
11: 00007FF7E2B4F068 uv_run+232
12: 00007FF7E2ADA381 node::Init+2097
13: 00007FF7E2ADAB57 node::Start+1159
14: 00007FF7E363408C v8::internal::AsmJsScanner::IsNumberStart+127292
15: 00007FFBFC237974 BaseThreadInitThunk+20
16: 00007FFBFE78A271 RtlUserThreadStart+33
```

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help as, per your comment, this is an issue with an add-on, not node itself.

**Comment by cracker0dks** [comment]
@bnoordhuis Don't know, but does it matter that the callback is coming from an other program before calling the test() function? I know that the problem only occurs If we get to this point by an external callback... but if we reach the point of  `obj.getId()` in the process (no matter how),
should `obj.getId()` not always return `TypeError: Cannot read property 'getId' of null` inside test if "obj" is  null...?

**Comment by addaleax** [comment]
@cracker0dks It’s really hard to tell without knowing what the addon looks like. There’s a good chance it just ends up catching the error and swallowing it, for example.

**Comment by cracker0dks** [comment]
I looked deeper into this and it is not the fault of nodejs. I opend a issue on the main repo, thanks.
