### ISSUE TITLE
How to Setup Nodejs in My Linux Server (Godadday)

### ISSUE THREAD

**Issue by birender** [nodejs/help#236]
Hi,
Can you please let me know that How do I  Setup Nodejs in My Linux Server (Godadday)

Thanks
Birender

**Comment by kahwee** [comment]
Have you seen this? 

https://www.godaddy.com/help/how-to-install-nodejs-on-centos-12159 (For VPS and dedicated servers)

**Comment by birender** [comment]
Thanks Lot ...........

**Comment by lordKnighton** [comment]
you wanna close this? @kahwee or @birender
