### ISSUE TITLE
Connect with ssl3/tls1

### ISSUE THREAD

**Issue by YuriyTigiev** [nodejs/help#2362]
Hello, 

Which version of a nodejs and modules support sslv3/tls1.  I'm developing a client which should take information from the remote server which supports only https (sslv3/tls1)

**Comment by bnoordhuis** [comment]
That must have been one of the v0.12.x releases. Good luck getting that to work with any recent npm packages - that release line has been officially out of support for over 3 years and was effectively dead well before that.

**Comment by YuriyTigiev** [comment]
Thank you for your attention.

Should I downgrade openssl library installed on the os?  Or nodejs 0.12.x contains all necessary independent libraries?

**Comment by bnoordhuis** [comment]
Node.js has its own vendored copy of openssl.

**Comment by YuriyTigiev** [comment]
Dear @bnoordhuis 

I hope for your support. I'm trying to connect to a legacy remote server using a simple code, but getting an error  "SSLv3 method disabled". Might you can suggest a solution to how to modify existing code to resolve the issue.

I have installed the node js by an instruction 
https://computingforgeeks.com/how-to-install-nodejs-on-centos-fedora/

[root@localhost ~]# node -v
v12.14.0
[root@localhost ~]# npm -v
6.13.4


Source Code 

```
const https = require('https');
const request = require('request');
const fs = require('fs');
const port = 8000

const options = {
  key: fs.readFileSync('./key.pem'),
  cert: fs.readFileSync('./cert.pem')
};

https.createServer(options, function (req, res) {

  var options = {
      url : "https://172.30.129.98:8446/script",
      agentOptions: {
        securityOptions: 'SSLv3_method',
        secureProtocol: 'SSLv3_client_method' 
        
    },
     secureProtocol: 'SSLv3_client_method' 
    };

    request.get(options, function(error, response, body) {
      console.log('error:', error); 
      console.log('statusCode:', response && response.statusCode); 
      console.log('body:', body);       
    } );

    res.end("test test");

}).listen(port);

```

Error Message

```
TypeError: SSLv3 methods disabled
index.js:25
statusCode: undefined
index.js:26
body: undefined
```
