### ISSUE TITLE
Python 3 support in Node.js 12

### ISSUE THREAD

**Issue by adamjstewart** [nodejs/help#2363]
* **Node.js Version**: 12.14.0
* **OS**: macOS 10.15.2
* **Scope (install, code, runtime, meta, other?)**: install

Hi, I'm updating our package for `node-js` in the [Spack package manager](https://spack.io) and was wondering if you could help. It looks like Node.js version 12 added experimental support for Python 3, and version 13 added full support, is that correct? How can I experiment with that Python 3 support? I tried setting `PYTHON` to my Python 3 executable, but it looks like the configure script still uses the system Python 2 instead.

I tried Node.js 13, but it seems that the libraries vendored with `npm` (specifically `sharp`) do not yet support Node.js 13.

@tgamblin

**Comment by adamjstewart** [comment]
Looking at the Travis config files, do I need to set `NODE_GYP_FORCE_PYTHON` in addition to `PYTHON`?

**Comment by adamjstewart** [comment]
Update: I got things working by running `configure.py` directly with the `python3` executable instead of running the `configure` shell script.

**Comment by gireeshpunathil** [comment]
thanks for self-diagnosing this! 

maybe worthwhile to add a note to that effect in https://github.com/nodejs/node/blob/master/BUILDING.md#note-about-python-2-and-python-3 ? do you want to try a PR for that?

**Comment by richardlau** [comment]
> thanks for self-diagnosing this!
> 
> maybe worthwhile to add a note to that effect in https://github.com/nodejs/node/blob/master/BUILDING.md#note-about-python-2-and-python-3 ? do you want to try a PR for that?

Should be unnecessary for Node.js 13 and later because of https://github.com/nodejs/node/pull/30091.
