### ISSUE TITLE
Exception stopping the program automatically

### ISSUE THREAD

**Issue by vijayalakshmi1995** [nodejs/help#2364]
Am trying to get the ciphers used in the website i have to call the request using the proxy. When i mention secureProtocol with unsupported version of ssl, node throwing the exception and closing the program automatically. 
Please check the below code. Here am trying to connect badssl.com with sslv3 through corporate proxy.

var https = require('https');
var HttpsProxyAgent = require('https-proxy-agent');

var options = {
    url: "https://badssl.com/",
    rejectUnauthorized : false,
    secureProtocol : "SSLv3_method",
    agent : new HttpsProxyAgent("http://127.0.0.1:8088")
}

https.get(options, function (res) {
    console.log('"response" event!', res.socket.getCipher());
});

**Output :** 

_tls_common.js:71
  this.context.init(secureProtocol,
               ^

TypeError: SSLv3 methods disabled
    at new SecureContext (_tls_common.js:71:16)
    at Object.createSecureContext (_tls_common.js:98:13)
    at Object.connect (_tls_wrap.js:1429:48)
    at ondata (D:\WORKING SOURCE CODE\Test\node_modules\https-proxy-agent\index.js:154:20)
    at Socket.read (D:\WORKING SOURCE CODE\Test\node_modules\https-proxy-agent\index.js:89:12)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at emitReadable_ (_stream_readable.js:597:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:21) {
  code: 'ERR_TLS_INVALID_PROTOCOL_METHOD'
}

**Comment by sam-github** [comment]
> TypeError: SSLv3 methods disabled

SSLv3_method has not been supported by node.js for a long time, its not secure.

**Comment by vijayalakshmi1995** [comment]
Actually its not about sslv3 support. Exception closing the complete program. Its not caught in catch block also. My entire program get closed because of this unexpected close. It will be good if it's just throw the error and didn't close it..

**Comment by sam-github** [comment]
> Its not caught in catch block also. 

You have no try/catch in your reproduction, you are also using a thirdparty https-proxy-agent module.

If you can reproduce with just node, and can't catch with `try {..} catch() {}`, then report as a bug to node.

If you can only repro with https-proxy-agent, report to its author.
