### ISSUE TITLE
How to make a jsonp request in server-side nodejs?

### ISSUE THREAD

**Issue by zhijunzhou** [nodejs/help#2366]
How to make a jsonp request in server-side nodejs?

**Comment by gireeshpunathil** [comment]
does this help? https://www.npmjs.com/package/jsonp

**Comment by zhijunzhou** [comment]
> does this help? https://www.npmjs.com/package/jsonp

That package wont work because it is a client-side jsonp library. See details [here](https://github.com/webmodules/jsonp/blob/790398945dc391ad2f06b365193a040a3dc01977/index.js#L68).
