### ISSUE TITLE
Module Install Err

### ISSUE THREAD

**Issue by HashedDev** [nodejs/help#2368]
* **Node.js Version**:  v12.13.0.
* **OS**: Win10 Enterprise
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**: text-2-ascii

Hi! I want to install an module but i get this error: 
```npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\private\AppData\Roaming\npm-cache\_logs\2019-12-23T20_37_26_993Z-debug.log```

**Comment by gireeshpunathil** [comment]
@R3T1K0 - 
 - which module you were trying to install?
 - can you pass on the `2019-12-23T20_37_26_993Z-debug.log` for inspection?

**Comment by PoojaDurgad** [comment]
ping ,@HashedDev - is this issue resolved?

**Comment by HashedDev** [comment]
Issue is resolved.
