### ISSUE TITLE
Nan::addon: [NAN_METHOD(serialize)] call to [Serializer.WriteValue() core dumps when called within a worker thread. 

### ISSUE THREAD

**Issue by ron7777777** [nodejs/help#2369]
**Nan::addon: [NAN_METHOD(serialize)]
[test.gz](https://github.com/nodejs/node/files/3992347/test.gz)

call to [Serializer.WriteValue()] core dumps when called within a worker thread. _I ran exact code found in [log()] function below in the main thread [NAN_METHOD(serialize)] without problems._**

NOTE: All other code in [log()] function runs without issue except for serialize.WriteValue().

***Attached files format: tar cfZ format
################################################
void log(Isolate *isolate)
{
  v8::Locker locker(isolate);
  isolate->Enter();
  v8::HandleScope scope(isolate);

  v8::ValueSerializer serializer(isolate);
  serializer.WriteHeader();
  Local<Object> target = Local<Object>::New(isolate, persist);
  **if (serializer.WriteValue(isolate->GetEnteredOrMicrotaskContext(), target)
            .FromMaybe(false))**
  {
      
  }
  v8::Locker unlocker(isolate);
  isolate->Exit();
}

NAN_METHOD(serialize)
{
    v8::Isolate *isolate = info.GetIsolate();
    persist.Reset(isolate, info[0].As<v8::Object>());
    v8::Unlocker unlocker(isolate);
    std::thread t(log, isolate);
    t.join();
}

NAN_MODULE_INIT(init)
{
  NAN_EXPORT(target, serialize);
}

NODE_MODULE(native, init)
################################################

**Test env:** 
**node -v:** [v10.16.2]
**uname -a:** Darwin ...MacBook-Air.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:.../RELEASE_X86_64 x86_64
**clang -v:** Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**package.json:** "nan": "^2.14.0"

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help because it's an issue with an add-on, not node itself.
