### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by misanet** [nodejs/help#237]
Hi, I can't install npm on ubuntu. I got :
`Unable to correct problems, you have held broken packages`
on `sudo apt-get install npm`

**Comment by addaleax** [comment]
That sounds like an issue with your apt-get/dpkg configuration (I would assume that `sudo apt-get -f install` results in the same error message?).

Either way, the `npm` from Ubuntu’s own sources is pretty outdated. You can use the packages from NodeSource ([installation instructions](https://github.com/nodesource/distributions#installation-instructions)), or download and install the Node.js distribution tarballs from [nodejs.org](https://nodejs.org/en/) which include `npm`.

**Comment by misanet** [comment]
Thanks for response, but  i got error `Illegal instruction (core dumped)` when i want to use npm ( like check version etc) 

I installed node using tarball

**Comment by addaleax** [comment]
Can you run node from that tarball itself? Which version did you download/what is your system architecture (`uname -a` output?)

**Comment by misanet** [comment]
I can run it from tarball
Node v is 4.4.7 and ubuntu v is 14.2.0

**Comment by addaleax** [comment]
What is the output of `node -p process.arch` and, again, of `uname -a`?

**Comment by misanet** [comment]
for `node -p process.arch` is `illegal instruction` and `uname -a` is `Linux gps-tracking.xyz 4.2.0-27-generic #32~14.04.1-Ubuntu SMP  Thu Avg 6 14:55:27 UTC 2016 i686 athlon i686 GNU/Linux`

**Comment by addaleax** [comment]
> for `node -p process.arch` is `illegal instruction` 

That does *not* sound like you can run node. Which tarball did you download? https://nodejs.org/dist/v4.4.7/node-v4.4.7-linux-x86.tar.xz should be the right one for you.

**Comment by misanet** [comment]
Yes, that one and installed using `tar -C /usr/local --strip-components 1 -xJf node-v4.4.7-linux.x86.tar.xz `

**Comment by addaleax** [comment]
Sounds about right. Can you open node in a debugger? I know other people like other debuggers, but with gdb, it should be about the following:

- Run `gdb node`
- You should get a bunch of text and a command prompt that reads `(gdb)`. Enter `run -p process.arch`.
- The program should break with something like `Thread 1 "node" received signal SIGILL`
- You can run `disassemble $eip-40,$eip+40` and `backtrace` and paste the output of these commands somewhere (might be a bunch of text), that should help debug this problem.
- (You can use `quit` or Ctrl+D to exit gdb)

**Comment by misanet** [comment]
`[Thread debugging using libtheread_db_enable]
Using host libthread_db library "/lib/i386-linux-gnu/libthead_db.so.1".
[New Thread 0xb7ca6b40 (LWP 9047)]
[New Thread 0xb74a5b40 (LWP 9048)]
[New Thread 0xb6ca4b40 (LWP 9049)]
[New Thread 0xb64a3b40 (LWP 9050)]`

**Comment by addaleax** [comment]
That’s just output from node starting. Is there anything else?

**Comment by misanet** [comment]
I forgot last 2 line, it's updated

**Comment by addaleax** [comment]
Oh, thanks, that’s definitely more helpful. It might still be cool if you could show what `disassemble $eip-40,$eip+40` and `backtrace` (directly after that crash) print.

**Comment by addaleax** [comment]
nvm, that’s not necessary (just would have been a bit quicker):

```
 865b472:       f2 0f 10 00             movsd  (%eax),%xmm0
```

Just to be sure, `grep sse2 /proc/cpuinfo` prints out nothing for you, right?

**Comment by misanet** [comment]
Thanks :) thats better
`=> 0x0865b472 <_ZN2v88internal19ComputerFlagListHashEv+850>: movsd  (%eax),%xmm0`

Yes, thats prints nothing

**Comment by addaleax** [comment]
https://groups.google.com/forum/#!topic/v8-users/cIVgTxcDrNI – V8 (the JS engine used by node) requires SSE2 support on your machine, so you’re probably out of luck here. The last release line that with V8 versions from before that seems to be 0.10, so you can try installing that, but beware that 0.10 will hit its end of life in 2 months and not even receive security updates after that (it’s also quite outdated in general and not very well-supported by the ecosystem anymore).

**Comment by misanet** [comment]
Thanks a lot !

**Comment by bnoordhuis** [comment]
V8 has a non-SSE2 x87 backend maintained by Intel.  Node.js doesn't support it out of the box but it can probably be made to work if you're not afraid to dig into the build scripts.

(The bundled openssl uses SSE2 too but only when the CPUID says it's supported - I think.)
