### ISSUE TITLE
Node Modules Not Found (when configuring Zowe)

### ISSUE THREAD

**Issue by jimmschlo89** [nodejs/help#2371]
* **Node.js Version**: 8.16.1
* **OS**: z/OS 2.2
* **Scope (install, code, runtime, meta, other?)**: Other (installing Zowe)
* **Module (and version) (if relevant)**: CXXRT64

![image](https://user-images.githubusercontent.com/49279914/71522799-d78b0980-288b-11ea-8a6a-9ccdc0637923.png)

I run into this error when I try to run a script that does an install of the Zowe product.

I verifed that the necessary PTF's are installed, which is what makes this error confusing to me.
I can run "node --version" and it works properly.

I ran into this issue before, when I did the initial Node.js install, but it turned out to be a permission/path issue, rather than a PTF issue. Not sure about this one though.

Anything to point me in the right direction would be great!

Thank you,

James

**Comment by gireeshpunathil** [comment]
James: is this still an issue?

looks like some of the z/OS Language Environment pre-requisites may be missing. Can you review this and see if you have everything required?
 
https://www.ibm.com/support/knowledgecenter/SSTRRS_8.0.0/com.ibm.nodejs.zos.v8.doc/smpe.htm

/cc @nodejs/platform-s390

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if you still have issue
