### ISSUE TITLE
Package installation disturbing

### ISSUE THREAD

**Issue by JosiasAurel** [nodejs/help#2372]
When i want to install packages and dependencies for a project like electron, emberjs, etc, the first thing that shows is a fail. It takes alot of time to install a package and usually freezes at a point. I

  I use tha latest version of nodejs i.e 13.X

**Comment by gireeshpunathil** [comment]
@JosiasAurel - is this still an issue? is it reproducible consistently with the said version? and latest versions? and on which OS version?

**Comment by JosiasAurel** [comment]
This issue is no longer to be open.
