### ISSUE TITLE
new Date gives wrong datetime by ~17 seconds compared to system time

### ISSUE THREAD

**Issue by cjh9** [nodejs/help#2375]
* **Version**:
node -v v13.5.0

* **Platform**:
Ubuntu 18.04.3 LTS (Digital ocean server)
 4.15.0-70-generic nodejs/node#79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Ssh:ing in having two terminal windows open simultaneously, opening node in one:
```
sudo hwclock --show
2019-12-28 21:26:50.403548+0000
```
(this is the correct time)

 In node:
```
new Date
2019-12-28T21:26:33.216Z
```

Seems to be lagging behind by 18 seconds?

**Comment by bnoordhuis** [comment]
@cjh9 What you're seeing is not unexpected. Most hardware clocks have considerable drift, they gain or lose time over, er, time.

The operating system normally adjusts the reported time automatically, that's probably why you're seeing a discrepancy between the two.

Try installing ntpdate(1), that should keep them in sync (mostly - they might still disagree by a few seconds every once in a while until they're synchronized again.)

**Comment by PoojaDurgad** [comment]
ping - @cjh9 , is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
