### ISSUE TITLE
\o/ \o/ \o/ \o/ \o/

### ISSUE THREAD

**Issue by yarallira** [nodejs/help#2378]
Deu certo! Muito obrigada!

\o/ \o/ \o/ \o/ \o/
ALTER USER 'root'@'localhost' IDENTIFIED BY '';
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';

_Originally posted by @ProjetosApps in https://github.com/nodejs/help/issues/1555#issuecomment-459555005_

**Comment by ORESoftware** [comment]
?

**Comment by the-blackpirate** [comment]
If your version of MySQL is v5.7.x or MySQL v8.x.
**(this will work with node+mysql development)**
Deu certo! Muito obrigada!
This will absolutely work !!!!

> ALTER USER 'root'@'localhost' IDENTIFIED BY 'NEW_PASSWORD';

**Comment by PoojaDurgad** [comment]
@yarallira - I don't have much deeper insight about your issue . hopefully https://dev.mysql.com/doc/refman/5.7/en/alter-user.html this documenation may help you to get rid of this issue.

**Comment by gireeshpunathil** [comment]
ping @yarallira - is this still outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
