### ISSUE TITLE
New ECMAScript module._compile doesn't being called for "import from"

### ISSUE THREAD

**Issue by mamaniv** [nodejs/help#2379]
* **Node.js Version 13.5.0 **:
* **OS Windows 7**:
* **Scope runtime**:

We wrap the function `module._compile` in order to monitor and replace the compilation of JS files, right before it is being loaded. Using that technique, we can replace the source-code of JS files.

With the new ECMAScript modules, using `import from` keywords, we are no longer get those invocations, so we can't monitor the module compiling.

Is there any other function that is being called and also exported that we can instrument, in order to "catch" the compilation call?

Note:
We could maybe instrument to a function such as `ESMLoader.import`, but unfortunately this module is an internal module, `lib/internal/process/esm_loader`, which is not exported as public to the node.js library and therefore can't be reached.

Thanks,
Niv

**Comment by gireeshpunathil** [comment]
@nodejs/loaders

**Comment by GeoffreyBooth** [comment]
The ESM loader intentionally isn’t exposed for patching the way the CommonJS one was. There is currently no way to achieve what you’re requesting, though there are efforts to try to support what we’ve been calling hot reloading: https://github.com/nodejs/loaders/issues/22. It’s one of the [use cases](https://github.com/nodejs/loaders/blob/main/doc/use-cases.md) that ES module loaders aim to support, though there’s a lot to build before it can be achieved so it won’t be implemented soon.
