### ISSUE TITLE
npm >= 3.10.4

### ISSUE THREAD

**Issue by quaidn** [nodejs/help#238]
Is there any ETA when npm will be upgraded to v3.10.4 or later?
I'm asking because npm v3.10.4 contains node-gyp v3.4.0 which fixes native addon builds with VS2015.

**Comment by lordKnighton** [comment]
I'll refer you here, -> https://github.com/npm/npm/issues 

--- 

but for your information, npm has current versions of 3.10.6 & 3.10.5 & lower
