### ISSUE TITLE
How to create pointer in N-API and return pointer to javascript

### ISSUE THREAD

**Issue by shivam201312** [nodejs/help#2381]
* **Node.js Version**:13
* **OS**:iOS
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I am trying to create node-js module using N-API. I have to create pointer/reference of the javascript string and vice-versa
<br>

```c
napi_value Method(napi_env env, napi_callback_info info) {
  napi_status status;
  napi_value world;
  status = napi_create_string_utf8(env, "world", 5, &world);
  assert(status == napi_ok);
  return world;
}
#define DECLARE_NAPI_METHOD(name, func)                                        \
  { name, 0, func, 0, 0, 0, napi_default, 0 }

napi_value Init(napi_env env, napi_value exports) {
  napi_status status;
  napi_property_descriptor hello = DECLARE_NAPI_METHOD("hello", Method);
  status = napi_define_properties(env, exports, 1, &hello);
  assert(status == napi_ok);
}
NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
```

I can create reference of the object using following code .

```c
napi_ref referncevalue;
napi_value structureobj;

status = napi_create_object(env,&structureobj);
printf("\nStatus Object create : %d \n",status);
assert(status == napi_ok);


status = napi_create_reference(env,structureobj,0,&referncevalue);
printf("\nStatus ref : %d \n",status);
assert(status == napi_ok);
```

1) How can i create pointer/reference of the string type ?
<br> 
2) How can i send napi_ref type variable to the javascript ?

**Comment by addaleax** [comment]
> How can i create pointer/reference of the string type ?

Can you be more specific here? You cannot use `napi_create_reference()` on JS primitives like strings, if that’s what you’re looking for.

> How can i send napi_ref type variable to the javascript ? 

You can use `napi_get_reference_value()` to lookup the `napi_value` stored in a `napi_ref`, and then use that to return it to JS.

Does this help?

**Comment by shivam201312** [comment]
@addaleax  Thank you for replying .
So we can only send napi_value to the javascript, cannot send napi_ref variable to the javascript ,right ?
 if we cannot send ref type to the javascript and vice-versa , how can we avoid  copying of data from one variable to another ?

**Comment by addaleax** [comment]
> So we can only send napi_value to the javascript, cannot send napi_ref variable to the javascript ,right ?

@shivam201312 Yes, that’s correct.

Could you maybe explain where you think the copying takes place? There shouldn’t be any, so maybe that’s the underlying question here?

**Comment by shivam201312** [comment]
@addaleax 

From javascript if we have to send object or array with data to c code and use those value in c structure/array  
Suppose if i pass this value from javascript to N-Api/C file
    javascript object 
    {
        obj1 : {
            obj2:{
                data:'world'
            },
            data : 'hello'
        }
    }

    To use javascript object in c code .
    1) I have to read NAPI value from NAPI object
    2) Store NAPI value in c variable type 
    3) Pass those value to c function 
    Now if i have larger number of array / object whole javascript value will get copied from the javascript to c .
    if i have to pass these value to  multiple function then it will get copied every time i pass this value .
    i want to create array/structure in javascript 
    pass those function value to N-API , create reference of the those value ,and use those ref variable in other function for getting value.

**Comment by addaleax** [comment]
@shivam201312 It might be helpful if you could share your code? I don’t quite know what you’re looking for here…

**Comment by shivam201312** [comment]
@addaleax  i will try to send sample code in few days

**Comment by shivam201312** [comment]
@addaleax  i am trying to implement function . in this function have to read file and pass JavaScript buffer to test.cc . i don't want to pass buffer by value but i want to pass value by reference . i have tried to use **napi_get_buffer_info** for using buffer data in c file (test.cc). Code for the same is attached .
Using sample code i am able to get the length of buffer passed to test.cc file

Question 
1) How can i fetch data using napi_get_buffer_info function ?
2) Can i get pointer (uint8_t) to data from the napi_get_buffer_info function so that i can directly pass javascript buffer pointer to c function ?
[test.zip](https://github.com/nodejs/help/files/4041365/test.zip)
