### ISSUE TITLE
HTTPS Request Hangup Issue

### ISSUE THREAD

**Issue by jAddict7** [nodejs/help#2382]
* **Node.js Version**: 10.17.0
* **OS**: Ubuntu
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

We have GPS server running Node JS, from where the co-ordinates are pushed to another server using HTTPS node module. Every second we need to send around 60-80 requests. Node JS is running out of memory, so on a regular basis we restart the server. After every restart, requests are hanged for several hours and are triggered only for every 5 seconds. And rest requests are hanged and not working. After some hours, it works fine even with high load of 80 requests per second.

```
const query = JSON.stringify({
	'device_id': XXX,
	'items': YYY,
});

const options = {
	hostname: 'HOST',
	port: 443,
	path: 'Page Link',
	method: 'POST',
	headers: {
		'Connection': 'keep-alive',
		'Content-Type': 'application/json',
		'Content-Length': query.length
	}
};

var request = https.request(options, (res) => {
	res.on('data', (data) => {
		console.log('Response Data :: '+data);
	}).on('end', () => {});
	res.on('error', (e) => {
		console.error('Response :: '+e);
	});
});

request.on('error', (e) => {
	console.error('Request :: '+e);
});
request.write(query);
request.end();
```

Our all requests pushed to the same URL. Is there any problem in the implementation? Please do guide us.

**Comment by devsnek** [comment]
If you can't use websockets (which would be ideal here) you should try using an `http.Agent` to keep the connection between node and the other serves open between requests.

**Comment by jAddict7** [comment]
Thanks @devsnek as you suggested will plan for web sockets. Is there any sample for us to begin? At present, whether default agent would work well by changing any config or please suggest any agent which would help us to handle current scenario sir.

**Comment by jAddict7** [comment]
Thanks @devsnek as you suggested, tried using [http.Agent](https://www.npmjs.com/package/agentkeepalive), at present handling smoothly. We will check in some other scenarios and update if any issues arise.

**Comment by PoojaDurgad** [comment]
@jAddict7 - looks like this issue can be closed now as, it no longer an issue .please let me know if that is not the case.

**Comment by gireeshpunathil** [comment]
resolved, closing
