### ISSUE TITLE
Can i use rest api which is created by node.js in android application?

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [nodejs/help#239]
I created web application using node.js further i need to use the same api for my android application Can you please let me know that How to use it.

**Comment by danielkhan** [comment]
You don't provide much details about your application, e.g. which framework you use (express, restify, self made, ...) but regardless of that every request can return arbitrary data like JSON instead of a HTML page. This data can be consumed by your mobile application. Don't forget to think about authentication and security.

**Comment by BUHARIMOHAMEDISMAIL** [comment]
I'm using express web framework. For authentication and security i used npm passport-http-bearer.

**Comment by danielkhan** [comment]
Then it's something like that:
```javascript
router.get('/API/something', function(req, res) {
    return res.json({"say": "hello!"});
});
````
Use express router to separate your API into some sub application.
As you see a REST route is not different from any other route except the returned format.

**Comment by BUHARIMOHAMEDISMAIL** [comment]
var express = require('express'),
  router = express.Router(),
  Restaurantdet = require('../models/restaurant');
  console.log("outside restaurant controller");

router.get('/restaurants', function(req, res) {
  console.log("insdie restaurants function");
  var page = (req.query.page - 1) || 0,
    pageSize = req.query.pageSize || 10;
  Restaurantdet.find()
    .sort('name')
    .skip(page * pageSize)
    .limit(pageSize)
    .exec(function(err, restaurants) {
      if (err) {
        throw err;
      }
      Restaurantdet.count().exec(function(err, count) {
        if (err) {
          throw err;
        }
        res.json({
          count: count,
          restaurants: restaurants
        });
      });
    });
});

In the above code i planned to do token based authentication using npm passport-http-bearer.

If i did authentication using that npm. Wheather we can able to access this api in mobile client(Android, Ios) or not?

I have an another one alternative to use socket.io. If i used socket.io in web application i can do token based authentication for my web application and mobile client application. For mobile client application we have an socket.io set up file android(java) and Ios(swift).
for Iost: https://github.com/socketio/socket.io-client-swift

Let me know wich one is better further anyother doc is there please attach the link.

**Comment by danielkhan** [comment]
Using sockets or regular HTTP does not really make a difference. It really depends on if and how your users are authenticated.
In its simplest form use some hash as part of the payload (headers) you send along with your requests and use a middleware that checks this credentials in your route.

````javascript
app.get('/api/something', isAuthenticated, function(req, res) {
    // ...
});
````
`isAuthenticated(req, res, next)` would check your token and return a forbidden if it's invalid.
Against *what* you check it and what makes a token valid or invalid is really highly dependent from your use case.

**Comment by BUHARIMOHAMEDISMAIL** [comment]
Let me know how to do authentication for my api. Is there any doc please share with me.


Thanks a lot.

**Comment by danielkhan** [comment]
There is no generic answer to that.
As I said - it really depends very much on how / if your users are authenticated - if you just want to authenticate your app or a distinct user against the API ...
Analyze your use case and find out what you actually want to achieve. There is a lot documentation available if you are clear about your goal.
