### ISSUE TITLE
getaddrinfo EBUSY

### ISSUE THREAD

**Issue by ryo372000** [nodejs/help#2390]
* **Version**: v12.14.0
* **Platform**: Amazon Linux 2 (Linux 4.14.138-114.102.amzn2.x86_64)
* **Subsystem**:

I've a website using Vuejs as frontend and Expressjs as backend API. It is hosted on AWS EC2 and used RDS serving the database. Recently, I've got a lot of errors on the API ```getaddrinfo EBUSY (the RDS database address)```.

My web app has two more functions which can also lead to the same errors:

1. Users are allowed to upload images and the API saves to S3.
2. Users can login with Facebook / Google which ask the API to verify the access_token by making request to corresponding server.

I couldn't find similar issue on the internet but I recognized that might be related to DNS problem. Does anyone have the same issue ? Sorry for bad English.

**Comment by addaleax** [comment]
This error is reported to Node.js from the operating system during DNS resolution; Node.js cannot necessarily do something about it.

Depending on what part of your applications performs the DNS lookups, valid options might be caching the result yourself, using the `dns.resolve()` function instead of the default of `dns.lookup()`, or figuring out why your DNS is failing with `EBUSY`.

**Comment by bnoordhuis** [comment]
A common cause is running out of file descriptors; every call needs at least one file descriptor. Check that `ulimit -n` prints something reasonable.

**Comment by shrutishresth-bst** [comment]
We are also facing a similar issue with the same node version. In our case, we are using DynamoDB.

It is intermittent which comes every few hours and stops the process.

`error: getaddrinfo EBUSY dynamodb.us-east-2.amazonaws.com {"errno":-16,"code":"NetworkingError","syscall":"getaddrinfo","hostname":"dynamodb.us-east-2.amazonaws.com","region":"us-east-2","retryable":true,"time":"2020-01-08T12:08:20.485Z"}`

**Comment by ryo372000** [comment]
@bnoordhuis I think running out of file descriptors was the root cause to the issue. 

In my case, I used winston.js as a middleware to do logging. After checking the file descriptors of my node application, I found that there were a lot of file transport descriptors of the logger. That was because I created a new file transport instance each time the API being requested. I have already fixed that and see if that can solve the problem.

@shrutishresth-bst you can check the file descriptor of your node application by ```lsof -p (pidof your app)``` to see if you are having the same issue. On the other hand, take a look on https://aws.amazon.com/premiumsupport/knowledge-center/dns-resolution-failures-ec2-linux/?nc1=h_ls to see if you need DNS caching in such way. 

Also, thanks for @addaleax your quick response.

**Comment by wmertens** [comment]
I'm experiencing the same thing from time to time. I don't think it's the file descriptors, `/proc/$PID/limits` shows `Max open files            524288               524288               files`, and `lsof -p` shows it using 26 fds.

This is happening via node-fetch, which is just using `http(s).request`, which just uses `dns.lookup`, which goes to the Linux `nscd`, which is almost certainly beyond reproach. The lookups are for a very small set of names that are used in a bunch, every few minutes, so caching should be perfect.

I never see these issues with other programs, only Node.js. 

Would it not be an option to have Node.js perform an automatic retry when busy?

Are there other failure conditions that could cause this error?
