### ISSUE TITLE
for and fs don't work correctly

### ISSUE THREAD

**Issue by ThumusLive** [nodejs/help#2392]
I got an output unexpected with this code :  
```JS
var fs = require('fs')

for(var a = 0; a<5 ;a++){
    fs.readFile('Nothing', (err,data) => {
        console.log(a)
    })
}
```
I got this :
![image](https://user-images.githubusercontent.com/42680097/71785792-23644e00-3004-11ea-9fb9-49a1b04baa0f.png)
Or the right output is :
![image](https://user-images.githubusercontent.com/42680097/71785829-ae454880-3004-11ea-9bde-2a757a48fa14.png)

* **Version**: v12.13.1
* **Platform**: Windows 64-bit
* **Subsystem**: /

**Comment by devsnek** [comment]
This is because the `var` is changed synchronously before the fs callbacks run. It has nothing to do with fs. Using `let` instead of `var` will get rid of the issue.

```js
> for (var i = 0; i < 5; i += 1) { Promise.resolve().then(() => console.log(i)) }
5
5
5
5
5

> for (let i = 0; i < 5; i += 1) { Promise.resolve().then(() => console.log(i)) }
0
1
2
3
4
```

**Comment by ThumusLive** [comment]
Thanks !
