### ISSUE TITLE
How to implement meta tags on domain

### ISSUE THREAD

**Issue by sahithinaik** [nodejs/help#2394]
Hi, I have node server configure with one domain and runs on 3333 port. while I am sending url like https://********.com:3333 in social apps metatags are reflecting. But while I am sending url like https://********.com in social apps metatags are not reflecting. Can anybody help with the solution?

**Comment by gireeshpunathil** [comment]
@sahithinaik - is this issue resolved?

what is your issue? metatags reflecting, or not reflecting? reflecting where? and where you want that to be reflected instead? a small example with what is expected  and actual behavior will be usseful!

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
