### ISSUE TITLE
Node Node.js 8.10 jumping up due to end of life questions.

### ISSUE THREAD

**Issue by rarenet1976** [nodejs/help#2395]
Hi All:

Just using Node .JS. 8.10 for a minor lambda function.  Can I keep the existing cost to upgrade to 10.x or even 12.x?

I read the functionality changes and it does look like it is code related.  So based on my quickly scan, no code changes would be impacted, but I will test either way.

Regards,

-Mike Franklin

**Comment by gireeshpunathil** [comment]
@rarenet1976 - is this still outstanding?

`8.x` is no longer supported. That means issues reported out of that release will not be fixed. If your lambda is working fine and you are comfortable with that, you don't need to move ahead. But when eventually you move, the then versions may be too distant, and can cause you some inconvenience. That is one of the main reason people move along with LTS lines.

hope this helps.

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
