### ISSUE TITLE
TLS sockets Protocol version

### ISSUE THREAD

**Issue by Marf97** [nodejs/help#2397]
* **Node.js Version**: 13.5.0 
* **OS**: Win 7 
* **Scope**: tls 

I have a problem with my application when I use TLS. I want to get information about TLS version and cipher used for the communication with server. I need to use TLS 1.3 and my server says:

*Session started: TLSv1.3:TLS_AES_....*

Problem is that my client says something else. When I try to get version of TLS used it says TLSv 1.2 which doesn't make sense to me. I tried to get more information like in documentation provided and I only get undefined values.
```js
var socket = tls.connect(configuration);
console.log( socket.getProtocol() );   //gives me TLSv 1.2
console.log( socket.getCipher() );    //gives me undefined
```

<hr>
<b>First</b> problem is why server and client tells me they use different version of TLS.<br>
<b>Second</b> problem is why I can't see any more information from client side.

**Comment by bnoordhuis** [comment]
Is your server a Node.js program? What options do you pass to the server and the client?

Client and server can negotiate a different protocol version, that by itself is not out of the ordinary.

**Comment by Marf97** [comment]
Server is not Node.js program. I don't know options of the server right now and client has these options:
```
0: "aes128-gcm-sha256"
1: "aes128-sha"
2: "aes256-gcm-sha384"
3: "aes256-sha"
4: "des-cbc3-sha"
5: "ecdhe-ecdsa-aes128-gcm-sha256"
6: "ecdhe-ecdsa-aes128-sha"
7: "ecdhe-ecdsa-aes256-gcm-sha384"
8: "ecdhe-ecdsa-aes256-sha"
9: "ecdhe-ecdsa-chacha20-poly1305"
10: "ecdhe-psk-aes128-cbc-sha"
11: "ecdhe-psk-aes256-cbc-sha"
12: "ecdhe-psk-chacha20-poly1305"
13: "ecdhe-rsa-aes128-gcm-sha256"
14: "ecdhe-rsa-aes128-sha"
15: "ecdhe-rsa-aes256-gcm-sha384"
16: "ecdhe-rsa-aes256-sha"
17: "ecdhe-rsa-chacha20-poly1305"
18: "psk-aes128-cbc-sha"
19: "psk-aes256-cbc-sha"
20: "tls_aes_128_ccm_8_sha256"
21: "tls_aes_128_ccm_sha256"
22: "tls_aes_128_gcm_sha256"
23: "tls_aes_256_gcm_sha384"
24: "tls_chacha20_poly1305_sha256"
```

Server says: `TLSv1.3:TLS_AES_128_GCM_SHA256` which is also in client options so that's ok.
My problem is why server is telling that TLSv1.3 was used but client says TLSv1.2. Probably the ciphersuite in server is benevolent enough to accept TLSv1.2 connection cihpers so everything is OK?

**Comment by bnoordhuis** [comment]
`node --trace-tls client.js` should show why it ends up using TLSv1.2. See if adding `--tls-min-v1.3` makes a difference.

**Comment by PoojaDurgad** [comment]
@Marf97 - were you able to follow @bnoordhuis 's  suggestion? or is this still outstanding?

**Comment by Marf97** [comment]
Sorry for not responding. I don't remember it all now but I don't think it helped me resolve my problem. I decided to put don't this feature because there are still problems on the server-side of TLS communication. This issue can be probably closed by my side because I think it's not just a problem of nodejs.

**Comment by gireeshpunathil** [comment]
closing then, cheers!
