### ISSUE TITLE
require can't acces my file

### ISSUE THREAD

**Issue by bbsalsero** [nodejs/help#24]
hello,

when i use require(myfile) it's not working but if i do  fs.readFileSync(myfile) it work.

any idea?

**Comment by rosskukulinski** [comment]
hi @bbsalsero.  What is the actual filename/extension of myfile?

require() does not need you to specify the .js or .json extensions, but readFile/readFileSync do.

So:

```require('mylib')``` and ```fs.readFileSync('mylib.js')``` will both utilize the same file, while ```fs.readFileSync('mylib')``` will fail.

**Comment by bbsalsero** [comment]
thanks for your reply,

let's be more specific:



```javascript


var fs =  require('fs')

var root ='./modules/configs/'
var dir = fs.readdirSync(root)
console.log(dir)
var moduleConfig={}


for(e in dir){

console.log("####")
console.log(dir[e])


console.log(fs.readFileSync(root+dir[e]).toString())//// so this is working
 moduleConfig[dir[e]]= require(root+dir[e]) //// but this is not:(




console.log( moduleConfig[dir[e]])
console.log("####")
}





```

**Comment by bbsalsero** [comment]
ok this is really odd,

ok let's much more specific:

i'm loading a module that is loading it self some json file dynamically,

but even if i use the file full path it throw error.

like require('c:\\list.jon')

Error : cannot find module 'c:\\list.jon'

i'm on windows 10 en nodejs 0.12.7

**Comment by bbsalsero** [comment]
ooooooooookay, i'm using node since v 0.5 but i've never seen that;

so , i run myscript.js who  load  mymodules.js, in mymodules.js i put:


````javascript
module.exports=function( ){
var list =  require(__filename)
console.log(__filename) // this gave me mymodule.js 
console.log(list.toString()) // this show me myscript.js
}

````


can anyone could explain it?

**Comment by Slayer95** [comment]
@bbsalsero, with Node 0.12.7@Win7x64 I get the source of ``mymodule.js`` with that last script.

The way it's intended to work, relative paths passed to ``fs`` work relative to the root of your project, while relative paths passed to ``require`` work relative to the folder containing the file calling ``require``.

**Comment by lordKnighton** [comment]
feel free to reopen, happy coding :)
