### ISSUE TITLE
socket usage issues !

### ISSUE THREAD

**Issue by PaulTsai20160627** [nodejs/help#240]
Hi All:

Here is a testing of server and client intercommunication using socket udp4 protocols: 

the codes are shown as belows:

My problems is that ${statements} does not work , it shows only the orginal source code contents,
not the real transferred ones. like address or port informations. So , Is there any wrong with that ? 

Because these samples is from node.js v6.3.1 documentations: https://nodejs.org/api/dgram.html#dgram_udp_datagram_sockets

`const dgram = require('dgram');
const server = dgram.createSocket('udp4');

server.on('error',(err)=>{
        console.log('error:\n${err.stack}');
});
server.on('message',(msg,rinfo)=>{
        console.log('Received %d bytes from %s:%d\n',msg.length,rinfo.address,rinfo.port);
});
/*
server.on('message',(msg,rinfo)=>{
        console.log('server got: ${msg} from ${rinfo.address}:${rinfo.port}');
});
*/
server.on('listening',()=>{
        var address = server.address();
        console.log('server listening ${address.address}:${address.port}');
});
server.bind({
        address: 'localhost',
        port:8000,
        exclusive: true
});`

**Comment by addaleax** [comment]
If you want `${…}` to be expanded, you need to use template strings that are enclosed with backticks (`` ` ``) instead of regular strings using single quotes (`"`).

For example:

```js
console.log(`${2+2}`); // prints 4
console.log('${2+2}'); // prints ${2+2}
```
