### ISSUE TITLE
Sometime I got UNABLE_TO_VERIFY_LEAF_SIGNATURE error

### ISSUE THREAD

**Issue by lomaster1** [nodejs/help#2401]
* **Version**: v10.16.3
* **Platform**: Linux zagent 4.4.0-159-generic nodejs/node#187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: tls

Sometimes I got UNABLE_TO_VERIFY_LEAF_SIGNATURE error for the same requests when I didn't get before.
For example: 
- https://images-eu.ssl-images-amazon.com:443/images/I/412W1GAcm3L.js?AUIClients/CardJsRuntimeBuzzCopyBuild
- https://play.google.com/store/apps/details?id=com.lemondo.Roll&gl=

Why? How can I get a server certificate to verify it if error raised?

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help because it's unlikely to be an issue with node itself.

**Comment by gireeshpunathil** [comment]
@lomaster1 - is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
