### ISSUE TITLE
App CPU Spikes

### ISSUE THREAD

**Issue by eduarhasanaj** [nodejs/help#2402]
* **Node.js 10.17.0**:
* **Ubuntu**:

The problem started when we upgraded from Node 8 to  Node 10. 
PM2 is used to manage cluster instances.
It reported cpu spikes up to 100% sometimes.
I tried to interpret the profiling dumps and the only conclusion is that it 
is taking time to do read operations and then gcc.
I am sending the profile  in case someone can help.
SpeedScope for opening the profile [viewer](https://www.speedscope.app)
[Profiler](https://ufile.io/zcoc1wqg)

Our system is large and for this we are forced to stick to some old packages like sequelize v3.

**Comment by gireeshpunathil** [comment]
@eduarhasanaj - where is the profile data? the first link takes me to the flame graph viewer app, and the second link is not working.

**Comment by gireeshpunathil** [comment]
if the spikes are very much reproducible, and remains for a reasonable amount of time (like minutes) then I suggest to collect --prof profile (it is not that it is better than flame graph, but I am more comfortable with that)

```
$ node --prof <app> // produces a profile log (isolate-xxx.log)
$ node --prof-process isolate-xxx.log // produces readable CPU sample profiles.
```

**Comment by eduarhasanaj** [comment]
@gireeshpunathil thank you for your time.
I tried the second link and it works. It contains the flame graph.
[b632c066-b3f1-407c-af63-ed7c7d01da86 (1).zip](https://github.com/nodejs/help/files/4060444/b632c066-b3f1-407c-af63-ed7c7d01da86.1.zip)

We encounter this problem on a live environment in cluster mode. Attached flamegraph is taken from pm2. We are afraid that due to  high spikes, if we profile on a single instance it can freeze etc.
Is there any chance that you can read attached flamegraph?

**Comment by gireeshpunathil** [comment]
Here is my interpretation of the flame graph (I am doing it for the first time, so it can be error prone)

The graph contains two dominant spikes, both involving `Model.bulkBuild` being invoked recursively, and eating 100% CPU for  ~150 ms. Here is one such sequence:

```js
(garbage collector)
> Instance.set (file:///home/backoffice-administration/node_modules/sequelize/lib/instance.js:250:33)
> initValues (file:///home/backoffice-administration/node_modules/sequelize/lib/instance.js:14:25)
> Instance (file:///home/backoffice-administration/node_modules/sequelize/lib/instance.js:84:23)
> Instance (file:///home/backoffice-administration/node_modules/sequelize/lib/model.js:684:26)
> Model.build (file:///home/backoffice-administration/node_modules/sequelize/lib/model.js:1739:32)
> (anonymous) (file:///home/backoffice-administration/node_modules/sequelize/lib/model.js:1786:31)
> map
> Model.bulkBuild (file:///home/backoffice-administration/node_modules/sequelize/lib/model.js:1767:36)
> Instance._setInclude (file:///home/backoffice-administration/node_modules/sequelize/lib/instance.js:444:41)
> Instance.set (file:///home/backoffice-administration/node_modules/sequelize/lib/instance.js:250:33)
> Instance.set (file:///home/backoffice-administration/node_modules/sequelize/lib/instance.js:250:33)
> initValues (file:///home/backoffice-administration/node_modules/sequelize/lib/instance.js:14:25)
> Instance (file:///home/backoffice-administration/node_modules/sequelize/lib/instance.js:84:23)
> Instance (file:///home/backoffice-administration/node_modules/sequelize/lib/model.js:684:26)
> Model.build (file:///home/backoffice-administration/node_modules/sequelize/lib/model.js:1739:32)
> (anonymous) (file:///home/backoffice-administration/node_modules/sequelize/lib/model.js:1786:31)
> map
> Model.bulkBuild (file:///home/backoffice-administration/node_modules/sequelize/lib/model.js:1767:36)
> AbstractQuery.handleSelectQuery (file:///home/backoffice-administration/node_modules/sequelize/lib/dialects/abstract/query.js:621:52)
> Query.formatResults (file:///home/backoffice-administration/node_modules/sequelize/lib/dialects/mysql/query.js:74:40)
> (anonymous) (file:///home/backoffice-administration/node_modules/sequelize/lib/dialects/mysql/query.js:39:44)
> (anonymous) (file:///home/backoffice-administration/node_modules/mysql/lib/Connection.js:518:18)
> (anonymous) (file:///home/backoffice-administration/node_modules/mysql/lib/Connection.js:480:18)
> Sequence.end (file:///home/backoffice-administration/node_modules/mysql/lib/protocol/sequences/Sequence.js:56:33)
> Query._handleFinalResultPacket (file:///home/backoffice-administration/node_modules/mysql/lib/protocol/sequences/Query.js:125:51)
> Query.EofPacket (file:///home/backoffice-administration/node_modules/mysql/lib/protocol/sequences/Query.js:104:39)
> Protocol._parsePacket (file:///home/backoffice-administration/node_modules/mysql/lib/protocol/Protocol.js:241:42)
> _parsePacket (file:///home/backoffice-administration/node_modules/mysql/lib/protocol/Parser.js:-1:-1)
> write (file:///home/backoffice-administration/node_modules/mysql/lib/protocol/Parser.js:28:39)
> Protocol.write (file:///home/backoffice-administration/node_modules/mysql/lib/protocol/Protocol.js:36:35)
> (anonymous) (file:///home/backoffice-administration/node_modules/mysql/lib/Connection.js:89:62)
> (anonymous) (file:///home/backoffice-administration/node_modules/mysql/lib/Connection.js:518:18)
> emit (events.js:146:43)
> addChunk (_stream_readable.js:-1:-1)
> readableAddChunk (_stream_readable.js:-1:-1)
> Readable.push (_stream_readable.js:205:34)
> onStreamRead (internal/stream_base_commons.js:86:21)
```

 - It is possible that this stack represents a deep, data-centric (CPU bound) activities without requiring to go back to the OS for any services.
 - gc at the tip of it also would have contributed to lot of CPU / memory bound activities
 - tools would show it as an abnormal thing, but is just that node is leveraging the full quota of CPU in the scheduling cycles.
 - A high level assessment of the design of the involved code would be good to confirm this theory.
 - I would not call it an issue, unless you also observe distortion in responsiveness on those spike periods

**Comment by eduarhasanaj** [comment]
@gireeshpunathil  Thank you very much for your time. 
And sorry for late reply.
Yes as you said there is not any thing obvious thing that can cause these problem, at least in this instance. I am suspecting that it is another thing related to pm2 load balancing.

**Comment by PoojaDurgad** [comment]
@eduarhasanaj - is this  still outstanding? looks like this can be closed now .please let me know if that is not the case.

**Comment by eduarhasanaj** [comment]
Hi @PoojaDurgad 
The problem was due to geoip in memory database which was being parsed in every request. That was the cause of the bug.
I am closing this.
