### ISSUE TITLE
Nodejs + kahoot.js Kahoot answering bot

### ISSUE THREAD

**Issue by OoDone** [nodejs/help#2404]
* **most recent**:
* ****:
* **Scope code**:
* **Module kahoot.js:latest**:
So basicially i've been working on a bot to answer kahoot questions right but when it gets to (bot.js) ```
var questionnum;
var choice;
var answer2;
client.on("questionStart", question => {
  /*THIS LINE EXECUTES */ console.log("A new question has started, answeringsadasdasdsa the first answer."); 
  questionnum = question.number - 1; // <--- THIS LINE DOES NOT EXECUTE
  choice = global.question[questionnum].choices;
  for (var i = 0; i < choice.length; i++) {
    answer2 = choice[i].correct;
    if (answer2 == true) {
      a = answer2;
      console.log("answer: " + a);
    } else {
      a = answer2;
      console.log(" NOT answer: " + a);
    }
  }
});```
Main repo:
https://github.com/OoDone/kahootbotter/tree/correct

**Comment by Hakerh400** [comment]
Without running you code, my guess is that `question` is either `undefined` or `null`, so `question.number` fails with a `TypeError`, but the library you're using probably encapsulates the callback invocation into a `try..catch` block and swallows the error.

Try to log the `question` object instead of the string `"A new question has started ..."` and see what it prints.

**Comment by OoDone** [comment]
UPDATE it goes farther after a little tweaking but i didn't change anything but removing a console.log it gets to `` var choice = quest[questionnum].choices;`` then after that stops but question is defined b/c the event is called on a new question so question has a value

**Comment by OoDone** [comment]
I found the problem line it is ``console.log(quest[questionnum].choices);``` i don't know why the json looks something like this 
Kahoot:
    questions:
         0:
              choices:
                  1:
                  2:
                  3:
                  4:
                       question: "String question"
                       iscorrect: BOOLEAN VALUE
         1:
             ETC

**Comment by OoDone** [comment]
UPDATE:fixed the problem i still don't know what it was though
