### ISSUE TITLE
Downgrade node ABI to specific version?

### ISSUE THREAD

**Issue by akmadian** [nodejs/help#2405]
* **Node.js Version**: 12.14.1
* **npm Version**: 6.13.6
* **OS**: Windows 10 1809 17763.914

Hello! This is a really unorthodox use case so I wouldn't be surprised if there is no solution, or if the solution is impractical. Long thread ahead.

I'm trying to pull a package from a built and installed electron app, and Frankenstein it into being functional, for fun! This package is not published publicly, and I don't have access to the source. Here's a tree of the resources directory of the electron app: 
```
C:.
├───app.asar.unpacked
│   └───node_modules
│       └───@nzxt
│           └───rust-cam
│               ├───dist
│               │   ├───lib
│               │   ├───native
│               │   │   └───target
│               │   │       └───release
│               │   ├───nzxt-device
│               │   ├───overlay
│               │   │   └───Release
│               │   ├───proxy
│               │   │   ├───client
│               │   │   ├───server
│               │   │   ├───services
│               │   │   └───types
│               │   └───rust-cam-worker
│               │       └───drivers
│               │           ├───asetek
│               │           │   ├───x64
│               │           │   └───x86
│               │           ├───chipset
│               │           │   ├───Driver Installation Tool
│               │           │   │   ├───x64
│               │           │   │   └───x86
│               │           │   └───Legacy Driver
│               │           └───nahimic
│               │               ├───x64
│               │               └───x86
│               └───docs
└───static
    ├───app_icons
    ├───games
    ├───images
    │   └───theme_packs
    ├───legal
    ├───patch-notes
    └───translations
        ├───de
        ├───en
        ├───es
        ├───fr
        ├───it
        ├───ja
        ├───ko
        ├───pt
        ├───ru
        ├───zh-CN
        └───zh-TW
```

## The Error
The package is contained in `app.asar.unpacked/node_modules/@nzxt/rust-cam/`. There are also some docs that didn't show in the tree, but that doesn't really matter. I tried replicating the most basic code example in the docs (**not in an electron app, just with `> node test.js`**), and I got this error:
```
internal/modules/cjs/loader.js:1021
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\src\rust-cam\crAPI\dist\native\index.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\src\rust-cam\crAPI\dist\lib\index.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
```
After upgrading node.js to latest, and npm to latest, I now get 
```
Error: The module '\\?\C:\src\rust-cam\crAPI\dist\native\index.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
```

## What I tried
 - Updating npm and node to most current LTS version
 - Running `npm rebuild` in my project's root dir, and in the package's root dir
 - Installing the package with npm and importing with `require('@nzxt/rust-cam')` instead of `require('./rust-cam/lib/index.js')` as was suggested in the docs.

I did a few hours of digging, and found that:
 - NODE_MODULE_VERSION seems to correspond (is synonymus with?) the node ABI version. 
 - ABI version 70 does not exist on [the node.js releases page (https://nodejs.org/en/download/releases/), it skips from 67 to 72. 
 - The only mention I can find of ABI version 70 is in [this file in the `nodejs/node` repo](https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json#L14). This mention seems to me to show that ABI v70 is related to an electron runtime? 
 - [This issue from the `nodejs/help` repo (#2249)](https://github.com/nodejs/help/issues/2249) that also mentions electron and ABI versions.

A repo with the package's code and my testing code can be found [here](https://github.com/akmadian/nzxt-rust-cam)

Am I only able to use this package from an electron app, considering it was built against ABI v70, and the only mentions I can find of v70 are in relation to electron? Are there any tools out there that can rebuild the package for ABI v72? Am I just out of luck?

Any help is appreciated, thanks :)

**Comment by bnoordhuis** [comment]
> The only mention I can find of ABI version 70 is in this file in the nodejs/node repo. This mention seems to me to show that ABI v70 is related to an electron runtime?

That's correct.

> Am I only able to use this package from an electron app, considering it was built against ABI v70, and the only mentions I can find of v70 are in relation to electron?

That, too, is correct.

> Are there any tools out there that can rebuild the package for ABI v72? Am I just out of luck?

That last one, I'm afraid. The ABI is set in stone once compiled. ABI affects sizes of objects, names of API methods, etc. It's pretty fundamental.

**Comment by akmadian** [comment]
Thanks!

Will try to get it working through electron, and do more reading on ABIs :)

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
