### ISSUE TITLE
Strange issue when trying to write a file from a readStream

### ISSUE THREAD

**Issue by vomc** [nodejs/help#2406]
* **Node.js Version**: v10.15.3
* **OS**: macos catalina 10.15.2
* **Scope (install, code, runtime, meta, other?)**: code?
* **Module (and version) (if relevant)**: fs

I kind of expected that the file generated (since its just basically the data of the file that was read) would be the same as the input file. But what happens is that the output file is not valid... 

```js
const zipPath = path.join(__dirname, 'inputFile.zip')

        const rs = fs.createReadStream(zipPath, { encoding: 'ascii' }) // yes it is ascii
        let fileData = ''
        rs.on('data', chunk => fileData += chunk)
        rs.on('end', () => { 
            console.log("data written got ", fileData)
            // now test making a file from this
            fs.writeFile('./outputFile.zip', fileData, 'ascii', (err) => { 
                if (err) console.error(err)
                console.log("WRITTEN")
            })
        })
```

**Comment by Hakerh400** [comment]
From the [documentation](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings):

> 'ascii': For 7-bit ASCII data only. This encoding is fast and will strip the high bit if set.

Not all encodings are bijections. The `ascii` is an example. You probably want `latin1` instead.

**Comment by vomc** [comment]
Yeah that could have been it. As a sanity test I ended up just removing all `encoding` params and just piping the read stream to a writestream and that worked... so likely this was an issue with encoding...
