### ISSUE TITLE
fs.readdirSync is not a function 

### ISSUE THREAD

**Issue by vishalc129** [nodejs/help#2408]
Version: v12.14.1
Platform:  Windows 64

When using fs library getting an error as 'fs.readdirSync is not a function'.
When debugged in console, fs is as below.(Please see console where in logged fs.)
![image](https://user-images.githubusercontent.com/38748244/72199477-a94c2300-3462-11ea-9346-11f602ce96f6.png)

There are other functions are also missing from fs library like - fs.readFileSync, readDir = fs.readdirSync, stat = fs.statSync;

Environment Variable user path 
![image](https://user-images.githubusercontent.com/38748244/72199581-f67cc480-3463-11ea-8ceb-b4a132f41e0e.png)

Environment Variable system- path
![image](https://user-images.githubusercontent.com/38748244/72199563-b4ec1980-3463-11ea-9a68-80d7635d4842.png)

**Comment by gireeshpunathil** [comment]
@vishalc129 - is this issue outstanding?

If so - are you running this code in the server side, or in the client side (did you do `browserify`?)

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
