### ISSUE TITLE
Error Handlers Events !!!

### ISSUE THREAD

**Issue by PaulTsai20160627** [nodejs/help#241]
Hi All:
Here is one event handlers errors , after I adding the codes below 

![codes](https://cloud.githubusercontent.com/assets/20158340/17454135/6c4e8bbc-5bbe-11e6-9a08-46aff8ba2f01.png)

The outputs on the web browser is really what I expected, but the temrinals will show these

errros.

![image](https://cloud.githubusercontent.com/assets/20158340/17454120/15c3f43a-5bbe-11e6-838b-a56af9bd27eb.png)

So , I do not know what's the problems ?

**Comment by lordKnighton** [comment]
show me the full `start `function, because it's saying your code is busy, even after you call the res.end() method, & even if you're not using req, use `(req, res)`

**Comment by PaulTsai20160627** [comment]
Hi lordKnighton:
Below is my writing source codes , the problems is happening in requestHandlers.js scripts,
please check and give some directions about the problems issues.! Like coding ways or some suggestions! Thanks you. 

index.js full code
`var router = require("./router");
var server = require("./server");

var handlers = require("./requestHandlers");
var req = {	"/": handlers.start,
	 	"/start": handlers.start,
		"/send": handlers.send};
//var socket_client =require("./udp_socket_client");
server.start(router.route,req);`

server.js full code

`var http = require("http");
var url = require("url");
function start(route,handlers){
function onRequest(request,response){
	var pathname = url.parse(request.url).pathname;
	console.log("request for "+ pathname +" response");
	console.log("Request url: " + request.url);
	route(pathname,handlers,response);
	response.writeHead(200,{"Content-Type": "text/plain"});
	response.write("Hello World!!!");
	response.end();
/*
	var pathname = url.parse(request.url).pathname;
	route(route,pathname);
*/	
}
	http.createServer(onRequest).listen(8080);
	console.log("Server has Started");
}
exports.start = start;`


router.js full codes
`/*
function route(handle,pathname){
	if(typeof handle[pathname] === 'function'){
	handle[pathname];
	}
	else {
	console.log("failed to connect !!\n");

	response.writeHead(404,{"Content-Type": "text-plain"});
	response.write("404 Not found");
	response.end();

	}
}
*/
function route(pathname,handlers,response){
	console.log("Route this request "+ pathname);
	if(typeof handlers[pathname] == "function"){
	handlers[pathname](response);
	}
	else {
	console.log("failed to connect !!\n");
	console.log("No request handler for this pathname: '" + pathname + "'");
	}
}	
exports.route = route;`

start function & upload function full codes(requestHandlers.js )
`//var exec = require("child_process").exec;
function start(response){
	console.log("Request handler 'start' was called");
	//const dgram = require('dgram');
/*
	const dgram = require('dgram');
	const server = dgram.createSocket('udp4');
	server.on('message',(msg,rinfo)=>{
	console.log(`server got: ${msg} from ${rinfo.address}:${rinfo.port}`);
});
*/

	const message = Buffer.from('Hello Server ! I am Client ','utf8');
	response.writeHead(200,{"Content-Type": "text/plain"});
	response.write(message);
	response.end();

/*
	const client = dgram.createSocket('udp4');
	client.send(message,8080,'localhost',(err)=>{
	client.close();
*/
//});
       
/*
	exec("ls -lah",function(error,stdout,stderr){
	response.writeHead(200,{"Content-Type": "text/plain"});
	response.write(stdout);
	response.end();
*/
//});
/*
	response.writeHead(200,{"Content-Type": "text-plain"});
	response.write("Hi How are you ?");
	resposne.end();
*/
}
function send(response){
	console.log("Request handler 'send' was called");
/*
	const dgram = require('dgram');
	const message = Buffer.from('Hello Server ! I am Client ','utf8');
	const client = dgram.createSocket('udp4');
	client.send(message,8080,'localhost',(err)=>{
	client.close();
});
*/
}

exports.start = start;
exports.send = send;`

**Comment by danielkhan** [comment]
Could you please use code formatting - this is almost impossible to decipher.

    ````javascript
    if (isAwesome){
      return true
    } 
    ````

Thank you.

**Comment by lordKnighton** [comment]
get rid of response.write(message); and insert message into res.end( )

**Comment by PaulTsai20160627** [comment]
Hi lordKnighton:

Even though get rid of response.write(message) and insert to response.end(message),
there is still showing the wrong messages output as shown below, Its very strange.

Server has Started
request for /start response
Request url: /start
Route this request /start
Request handler 'start' was called
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:426:15)
    at Server.onRequest (/home/esp8266/node-v6.3.1-linux-x86/node-prac/udp_test/server.js:10:11)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)

requestHandlers.js 

````javascript
//var exec = require("child_process").exec;
function start(response,request){
	console.log("Request handler 'start' was called");
	//const dgram = require('dgram');
/*
	const dgram = require('dgram');
	const server = dgram.createSocket('udp4');
	server.on('message',(msg,rinfo)=>{
	console.log(`server got: ${msg} from ${rinfo.address}:${rinfo.port}`);
});
*/

	const message = Buffer.from('Hello Server ! I am Client ','utf8');
	response.writeHead(200,{"Content-Type": "text/plain"});
	//response.write(message);
	response.end(message);

/*
	const client = dgram.createSocket('udp4');
	client.send(message,8080,'localhost',(err)=>{
	client.close();
*/
//});
       
/*
	exec("ls -lah",function(error,stdout,stderr){
	response.writeHead(200,{"Content-Type": "text/plain"});
	response.write(stdout);
	response.end();
*/
//});
/*
	response.writeHead(200,{"Content-Type": "text-plain"});
	response.write("Hi How are you ?");
	resposne.end();
*/
}
function send(response){
	console.log("Request handler 'send' was called");
/*
	const dgram = require('dgram');
	const message = Buffer.from('Hello Server ! I am Client ','utf8');
	const client = dgram.createSocket('udp4');
	client.send(message,8080,'localhost',(err)=>{
	client.close();
});
*/
}

exports.start = start;
exports.send = send; 
````

**Comment by lordKnighton** [comment]
I'd like you to try:   `route` function res.end() in the bottom of `route` 

======

`send` function: put res.end() at the bottom

because your coding in async, you're code is active, so we need to make sure every thing has ended.
