### ISSUE TITLE
Transform stream `end` call does not emit `finish` event subsequently - only with Node 13.x

### ISSUE THREAD

**Issue by fbiville** [nodejs/help#2412]
* **Node.js Version**: 13.5.0
* **OS**: Mac OS 10.15.2
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: streams

**TL;DR**

I have set up a very simple project to reproduce the issue (https://github.com/fbiville/node-stream-callback). Just run `npm test` and you will see the failing test.

**Longer version**

I have a simple `Transform` stream implementation:
```js
const {Transform} = require('stream');

module.exports = class SquareStream extends Transform {

    constructor(opts) {
        super(opts);
        this.on('error', () => {
            this.end();
        });
    }

    _transform(data, _, callback) {
        if (typeof data !== 'number') {
            callback(new Error(`NaNNaNNaNNaNNaN: ${data} is not a number!`));
            return;
        }
        callback(null, data ** 2);
    }
};
```

The failing test is as follows (edit: **fails with Node 13 only**, passes with Node LTS versions 10/12):

```js
    // [...]
    beforeEach(() => {
        squareStream = new SquareStream({objectMode: true});
    });
    // [...]
    it('rejects non-numbers', (done) => {
        const fixedSource = new FixedSource(['batman'], {objectMode: true});

        squareStream.on('data', () => {
            done(new Error('should not have received data'));
        });
        let errored = false;
        squareStream.prependListener('error', (err) => {
            expect(err.message).toEqual('NaNNaNNaNNaNNaN: batman is not a number!');
            errored = true;
        });
        squareStream.on('finish', () => {
            expect(errored).toBeTruthy('should have errored');
            done();
        });

        fixedSource.pipe(squareStream);
    });
```

Interestingly, `SquareStream`'s `error` handlers are all properly called, which means `this.end();` should be evaluated as well.
In my understanding, [a call to `end` for a `Writable` stream should lead to the emission of a `finish` event and](https://nodejs.org/docs/latest/api/stream.html#stream_event_finish), therefore, the synchronous execution of all the corresponding registered listeners. 

If I change the constructor to do this:
```js
        this.on('error', () => {
            console.dir(this.listeners.on('finish').map(_ => _.toString()));
            this.end();
        });
```
I can see that the test `finish` listener is properly registered.

Why is this listener not called (thus causing jasmine to time out)?

**Comment by fbiville** [comment]
Paging @nodejs/streams: is this a bug or am I missing something?

**Comment by addaleax** [comment]
I’m assuming that this is because passing an error to the callback implicitly destroys the stream.

@ronag would probably know for sure.

**Comment by ronag** [comment]
Once a Writable/Transform has errored only `'error'` and then `'close'` will be emitted.

Calling `end()` inside an `'error'` handler will not work.

**Comment by ronag** [comment]
I think what you actually want to use is `'close'` not `'finish'`?

**Comment by fbiville** [comment]
I changed the test to observe `'close'` events, i.e.:
```js
squareStream.on('close', () => {
// [...]
```
it fails in the same way.

> Once a Writable/Transform has errored only `'error'` and then `'close'` will be emitted.
> 
> Calling `end()` inside an `'error'` handler will not work.

How do I trigger the end of a stream if it has errored? Should I avoid calling `end` and manually emit a `finish` or `close` event?

**Comment by ronag** [comment]
> How do I trigger the end of a stream if it has errored? Must I manually emit a finish or close event instead, as in the following:

You don't end the stream if it has errored. It should be destroyed automatically. Never emit finish or close manually.

Can you try:

```js
    constructor(opts) {
        super({ ...opts, autoDestroy: true });
    }
```

**Comment by fbiville** [comment]
Thanks, I'll give it a try.

> You don't end the stream if it has errored. It should be destroyed automatically. Never emit finish or close manually.

Would you mind elaborating a bit?

**Comment by ronag** [comment]
> Would you mind elaborating a bit?

On which part?

**Comment by ronag** [comment]
FYI: `autoDestroy` is true be default in Node v14

**Comment by fbiville** [comment]
> On which part?
On why emitting `finish` or `close` manually is a bad idea.

**Comment by ronag** [comment]
> On why emitting finish or close manually is a bad idea.

Because it bypasses the stream assumptions and invariant and can lead to unexpected behavior.

**Comment by fbiville** [comment]
Thanks for the help!

**Comment by fbiville** [comment]
Re-opening because the fix works only with Node 13, but not with LTS versions 10 & 12. Any idea why? (cc @ronag)

**Comment by fbiville** [comment]
One change I see is in the default `onerror` handler registered somehow automatically.
In Node 10 and 12:
```js
function onerror(er) {
  debug(onerror, er);
  unpipe();
  dest.removeListener(error, onerror);
  if (EE.listenerCount(dest, error) === 0)
    errorOrDestroy(dest, er);
}
```

In Node 13:
```
function onerror(er) {
  debug(onerror, er);
  unpipe();
  dest.removeListener(error, onerror);
  if (EE.listenerCount(dest, error) === 0) {
    if (!dest.destroyed) {
      errorOrDestroy(dest, er);
    } else {
      dest.emit(error, er);
    }
  }
}
```

**Comment by fbiville** [comment]
Is there a solution that works with Node 13.x as well as with LTS versions 12.x and 10.x? Or shall I file a bug? cc @ronag

**Comment by ronag** [comment]
@fbiville Can you use https://nodejs.org/api/stream.html#stream_stream_finished_stream_options_callback?

**Comment by fbiville** [comment]
@ronag Same problem with `finished` (test passes with Node 13, not with 12 or 10.
I have rewritten the test as:
```js
    it('rejects non-numbers', (done) => {
        const fixedSource = new FixedSource(["batman"], {objectMode: true});

        squareStream.on('data', () => {
            done(new Error("should not have received data"));
        });
        finished(squareStream, (err) => {
            expect(err.message).toEqual('NaNNaNNaNNaNNaN: batman is not a number!');
            done();
        });
        fixedSource.pipe(squareStream);
    });
```

**Comment by ronag** [comment]
@fbiville: Thanks. I will dig into this when I get the opportunity. Might be a bug fix we want to backport.

**Comment by fbiville** [comment]
@ronag have you had a chance to take a look at this? Shall I open an issue against https://github.com/nodejs/node/?

**Comment by ronag** [comment]
> Shall I open an issue against nodejs/node?

Yes, please! I was trying to find this issue there but failed. Now I see why.

**Comment by fbiville** [comment]
@ronag here is it: https://github.com/nodejs/node/issues/31750

**Comment by fbiville** [comment]
The related Node issue has been closed. Closing this now.
