### ISSUE TITLE
Is there anyway to conditionally thread inside my code?

### ISSUE THREAD

**Issue by darthzeran** [nodejs/help#2413]
* **Node.js Version**: // 13.x.x, the latest version
* **OS**: // Windows 10
* **Scope (install, code, runtime, meta, other?)**:// runtime

So I have an express router call that takes 3 seconds because of heavy computation.  I want to be able to receive the api call, create a thread, and return the result when it eventually finishes.

However, all the tutorials and docs I read make it seem that my main.js must be the one that creates/handles the threads, and trying to do it inside of a function call won't work.

Is this a true assumption, or do I just have a lot more to learn?

**Comment by Hakerh400** [comment]
> However, all the tutorials and docs I read make it seem that my main.js must be the one that creates/handles the threads, and trying to do it inside of a function call won't work.

You can create a thread from any function you want. Here is an example using express:

**main.js**

```js
'use strict';

const fs = require('fs');
const path = require('path');
const {Worker} = require('worker_threads');
const express = require('express');

const app = express();
const port = 3000;

const relative = file => path.join(__dirname, file);

app.get('/', (req, res) => {
  res.setHeader('Content-Type', 'text/html');
  fs.createReadStream(relative('index.htm')).pipe(res);
});

app.post('/', (req, res) => {
  const bufs = [];
  req.on('data', buf => bufs.push(buf));
  req.on('end', () => {
    const worker = new Worker(relative('worker.js'), {
      workerData: Buffer.concat(bufs),
    });
    worker.on('message', buf => res.end(Buffer.from(buf)));
  });
});

app.listen(port);
```

**worker.js**

```js
'use strict';

const {workerData, parentPort} = require('worker_threads');

let newData = Buffer.from(workerData);

// Do some computation...
// Can be asynchronous as well
// ........

// After the computation is done
parentPort.postMessage(newData);
```

**index.htm**

```htm
<form method="post" action="/">
  Enter your name:
  <input type="text" name="name" autofocus><br>
  <input type="submit" value="Submit">
</form>
```

How to run:

```console
> npm i express
> node main
```

Then open `localhost:3000` and submit the form. You can see that the computation is performed by a thread.

**Comment by PoojaDurgad** [comment]
@darthzeran -is this still outstanding? were you able to follow @Hakerh400 's suggestion ?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
