### ISSUE TITLE
Looking for guidance on stream throughput

### ISSUE THREAD

**Issue by lukiano** [nodejs/help#2416]
* **Node.js Version**: 12
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: stream

Hi, I'm looking for some guidance on a problem I'm working on. What I'd like to do is maximise performance and throughput as much as possible. Regretfully I'm not good at profiling in Node.JS, so this is all theoretical

I have a Node.JS web server that for sake of simplicity has one endpoint 
`GET /file/{id}` which currently has the following:
```js
const sourceData = ... // a readable stream obtained by doing an http request to an upstream server.
const decipher = ... // an instance of crypto.Decipher
const hasher = ... // an instance of crypto.Hash
const sizeCalculator = ... // an easy stream.Transform that sums the length of each buffer that goes through it
const serverResponse = ... // the server response of this request.
sourceData.pipe(decipher).pipe(hasher).pipe(sizeCalculator).pipe(serverResponse);
```

So you get the idea: a readable, a writable, and lots of transformations in the middle. This endpoint is called concurrently many times so lots of these operations happen at the same time.

As I said, I'm not happy with the throughput I'm getting, compared with the speed of the upstream server. Also since the CPU of this service is low I have doubt that the decipher or hasher are bottlenecks.

Currently the ideas I have in mind are:
- tweak the watermarks of all the objects involved. I'm concerned that the buffers present in the stream.Transform objects may be affecting the throughput.
-  use `read()` and event `'readable'` instead of `pipe`. https://nodejs.org/api/stream.html says it might provide better throughput.
- convert the source readable stream to an `AsyncIterable` and use `for await` all the way. Perhaps with a library like https://github.com/bustle/streaming-iterables . My concern here is that `decipher`, `hasher` and the size calculator are all synchronous functions, so it's like calling `await foo()` where `foo` doesn't return a `Promise`.
- use a library like https://github.com/mcollina/syncthrough for the transform operations.

So if anyone here has experience with any of these different options and wants to comment their findings I would appreciate it.

**Comment by gireeshpunathil** [comment]
@lukiano - very interesting problem statement indeed! is this still outstanding?

it may be worthwhile to profile the workload to see which takes relatively more CPU, to start with.

`node --prof <app>` - run this for sufficient load

this produces a profiling log - `isolate-xxx-v8.log`
`node --prof-process solate-xxx-v8.log` - will generate a human readable CPU profile

**Comment by gireeshpunathil** [comment]
ping @lukiano - were you able to  make progress?

**Comment by lukiano** [comment]
Hi there. Regretfully not really as I was required to work on other stuff. We're accepting the performance that we get right now and will go back to this issue probably next year.

**Comment by gireeshpunathil** [comment]
@lukiano - thanks. feel free to close the issue and re-open, or open a new one when you think it is a problem and are prepared to investigate.
