### ISSUE TITLE
Fetching with a custom content-type

### ISSUE THREAD

**Issue by KoenvGinkel** [nodejs/help#2418]
Version: v8.11.2
Platform: 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

Fetching with a custom Content-Type is not allowed. 
I think the body gets cleared out when the content type doesn't match. 
The only possible way is to use the axios package to fetch, which is the way I'm doing it now.

What i'd like to do is the following.

```
fetch('https://example.com/profile', {
  method: 'POST'
  headers: {
    'Content-Type': 'application/vnd.shipment+json',
  },
  body: JSON.stringify(data),
})
```
But the response is 422.

**Comment by addaleax** [comment]
How does your example differ from the way you do it with axios? Can you share an actual reproduction in some way?

Fwiw, I moved this to the nodejs/help repository because this doesn’t look like an issue with Node.js core specifically.

**Comment by KoenvGinkel** [comment]
Ofcourse, hereby my axios solve.
```
 axios({
      method: 'post',
      url: 'https://example.com/profile',
      headers: { 'Content-Type': 'application/vnd.shipment+json; charset=UTF-8', 'Authorization': this.authorization },
      data: {
```
