### ISSUE TITLE
Detect if NODE.JS script is called direct via bash (unix) / cmd (windows) or imported (ESM module loader)

### ISSUE THREAD

**Issue by mxcd** [nodejs/help#2420]
* **Node.js Version**: 13.6
* **OS**: Windows 7 (RIP)

How can I detect whether my node.js file was called directly from console (windows and unix systems) or loaded using the ESM module import ( `import {foo} from 'bar.js'`)

The question was already answered for regular node.js files ([Detect if called through require or directly by command line](https://stackoverflow.com/questions/6398196/detect-if-called-through-require-or-directly-by-command-line)) but since require is not available with ESM modules, I am in need of a different solution.

Please feel free to also answer this on stackoverflow for future reference:
https://stackoverflow.com/questions/59752798/detect-if-node-js-script-is-called-direct-via-bash-unix-cmd-windows-or-imp

**Comment by devsnek** [comment]
Such functionality is not exposed. For the moment you should separate your cli and library logic into separate files.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding

**Comment by electrovir** [comment]
[`import.meta.main` is in v24 now](https://github.com/nodejs/node/pull/57804) and can be used for this purpose (`if (import.meta.main)`)
