### ISSUE TITLE
Cal SHA1 fails due to uint32 being treated as int32

### ISSUE THREAD

**Issue by MarcKarasek** [nodejs/help#2421]
Created a Array:
let workspace_buffer = new ArrayBuffer(320) // 80 x uint32
let workspace = new Uint32Array(workspace_buffer)

Then filled the first 16 words with values prior to starting the SHA1 calulations.
When the code was filling in 17-80 in the array it was doing ^ and rol32 operations:

workspace[i+16] = ROL32(workspace[i+13] ^ workspace[i+8] ^ workspace[i+2] ^ workspace[i], 1)
If this ^ calulation ended up as a "neg" number 0xBA91DD01 for example the ROL32(x,1) would return 0xFFFFFFFF.

* **Version**: v12.13.1
* **Platform**: Win10 64
* **Subsystem**:

I have seen the same issue with different data sets (int 0-15 in the array) but always  the same behavior the result from the ^ is a 'neg' number  and results in 0xFFFFFFFF as output from ROL32 

prior -1164845823  -- This is just the ^ cal prior to doing the rol32 (this is 0xBA91DD01) 
after 4294967295

The ROL32 function is:
function  ROL32(_x, _r) {
  return (((_x) << (_r)) | ((_x) >> (32 - (_r))))
}

This works for "non-neg" values...

**Comment by Hakerh400** [comment]
I'm not sure what exactly your question is, but I think you probably want to use `>>>` instead of `>>`

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
