### ISSUE TITLE
ECMAScript modules not working with client side

### ISSUE THREAD

**Issue by techno021** [nodejs/help#2423]
* **Version**: v13.6.0
* **Platform**: Windows 10 x64
* **Subsystem**: N/A

So I am using the nodejs ecmascript loader in my express + ejs project, and the client side javascript has no access to the ecmascript modules for some reason, here is the [code](https://github.com/Gizmo-Rishab/ExModule.git)

**Comment by agnjunio** [comment]
ECMAScript modules aren't supported in their pure form in browsers without transpiling. 

That's where Babel enters. Please check: https://babeljs.io/

**Comment by gireeshpunathil** [comment]
@techno021 - is this resolved?

**Comment by techno021** [comment]
yea it is resolved, forgot to close the issue, sorry about that
