### ISSUE TITLE
Error trying to install node 

### ISSUE THREAD

**Issue by theguy718** [nodejs/help#2424]
/node-v13.6.0/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/diagnostics/arm/eh-frame-arm.o.d.raw   -c
make[1]: *** [tools/v8_gypfiles/v8_base_without_compiler.target.mk:639: /tmp/tmp.MtKgDUrI3c/node-v13.6.0/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/codegen/arm/assembler-arm.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm ef9cba33accb1c167e10fc2b39194c9e569d390b.intermediate c8b4941f81dc87a6527503629c6515c0f23acb60.intermediate
make: *** [Makefile:101: node] Error 2

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.
 PLEASE HELP!!!!!! 

* **Version**:
* **Platform**:
* **Subsystem**:

node-v13.6.0
kali linux
on raspberry pi 4

**Comment by gireeshpunathil** [comment]
@theguy718 - are you able to resolve this issue, by following the suggestions?

**Comment by leovegas** [comment]
I got same error today...

**Comment by Blackout271** [comment]
files(install)
  File "/tmp/tmp.EpczFz4K3v/node-v15.12.0/tools/install.py", line 137, in files
    action([output_prefix + output_file], 'bin/' + output_file)
  File "/tmp/tmp.EpczFz4K3v/node-v15.12.0/tools/install.py", line 76, in install
    try_copy(path, dst)
  File "/tmp/tmp.EpczFz4K3v/node-v15.12.0/tools/install.py", line 66, in try_copy
    return shutil.copy2(source_path, target_path)
  File "/usr/lib/python3.9/shutil.py", line 436, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 375, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
FileNotFoundError: [Errno 2] No such file or directory
make: *** [Makefile:158: install] Error 1

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.
   getting this error while using this command


sudo fakeroot checkinstall -y --install=no --pkgversion $(echo $(pwd) | sed -n -re's/.+node-v(.+)$/\1/p') make -j$(($(nproc)+1)) install

**Comment by benjamingr** [comment]
This seems to be inactive so I'm going to go ahead and close this issue - cheers.

**Comment by somecakemake** [comment]
Buongiorno. Sto tentando di installare node.js versione 18.18.1 su kali linux versione 2023.3. ma ricevo un errore.
Ho dato i seguenti comandi:

`sudo apt-get install python g++ make checkinstall fakeroot
src=$(mktemp -d) && cd $src
wget -N https://nodejs.org/dist/v18.18.1/node-v18.18.1.tar.gz
tar xzvf node-v18.18.1.tar.gz
cd node-v18.18.1
./configure
sudo fakeroot checkinstall -y --install=no --pkgversion $(echo $(pwd) | sed -n -re's/.+node-v(.+)$/\1/p') make -j$(($(nproc)+1)) install
`

Di seguito l'output del terminale:
`if [ ! -r node ] || [ ! -L node ]; then \
  ln -fs out/Release/node node; fi
/usr/bin/python3.11 tools/install.py install '' '/usr/local'
installing /usr/local/bin/node
Traceback (most recent call last):
  File "/tmp/tmp.ca4o0y2j7E/node-v18.18.1/tools/install.py", line 351, in <module>
    run(sys.argv[:])
  File "/tmp/tmp.ca4o0y2j7E/node-v18.18.1/tools/install.py", line 342, in run
    files(install)
  File "/tmp/tmp.ca4o0y2j7E/node-v18.18.1/tools/install.py", line 150, in files
    action([output_prefix + output_file], 'bin/' + output_file)
  File "/tmp/tmp.ca4o0y2j7E/node-v18.18.1/tools/install.py", line 77, in install
    try_copy(path, dst)
  File "/tmp/tmp.ca4o0y2j7E/node-v18.18.1/tools/install.py", line 67, in try_copy
    return shutil.copy2(source_path, target_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shutil.py", line 437, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 376, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
FileNotFoundError: [Errno 2] No such file or directory
make: *** [Makefile:190: install] Errore 1

****  Installazione fallita. Creazione del paccheto annullata.

Pulitura in corso...OK

Ciao.`

Sono alle prime armi e ho una conoscenza base di Linux.
Sembra che provi ad installare node in /usr/local/bin
Ho verificato e tale percorso esiste sulla macchina.
Ho cercato in rete ma non ho trovato nulla di utile a riguardo.
Qualcuno potrebbe gentilmente aiutarmi a risolvere il problema?
