### ISSUE TITLE
Deleted module still running

### ISSUE THREAD

**Issue by barhamada** [nodejs/help#2425]
I have a Node.js application in which users can start and stop modules.

To start module I use this function in app.js:
    `module.exports = { 
    loadModule: function (_module, callback) {
    // Check if module path exists
    try {
        require.resolve(_module);
    }
    catch (error) {
        callback({ message: 'Cannot find module path: ' + _module, error: error });
    }
    // Load module
    try {
        require(_module);
        callback(null);
    }
    catch (error) {
        callback({ message: 'Cannot load module: ' + _module, error: error });
    }
}`

I call this function in app.js as below:

`// app.js
moduleLoader.loadModule(path.join(__dirname, '/modules/', _module), (error) => {
    if (error) {
        // Throw error
    }
});`

And to stop it:

`let name = require.resolve('./modules/' + _module);
delete require.cache[name];
logger.debug('DELETED MODULE: ' + require.cache[name]); // print undefined `

When I call stopModule I can see the module is actually removed from the cache but strangely, it is still running

The strangest thing is when I start this module again(which is deleted from the cache but still running), It seems being loaded from disk.

What am I doing wrong ? Is this a bug ?

You can see the output image in this [link](https://stackoverflow.com/questions/59803220/deleted-module-still-running)

* **Node.js Version**: v10.16.0
* **OS**: Windows 10
* **Scope**: Runtime

**Comment by devsnek** [comment]
you aren't deleting the module, you're just deleting the entry in the cache that points to the module. you can't "delete" objects in js, only references to them.

**Comment by barhamada** [comment]
@devsnek  so what is the best way to remove a loaded module ?

**Comment by devsnek** [comment]
it's not possible.

**Comment by Hakerh400** [comment]
What do you mean by *stopping a module*? Can you provide a full example?

**Comment by ORESoftware** [comment]
deleting the require.cache is fine. 
but all the references to the original module will still exist. so you have to de-reference the old module and reference the new module everywhere.
its possible to hot-reload node.js modules (files) but your program needs to be architected in a specific way.  dependency injection is most likely the kind of pattern you would need.

**Comment by PoojaDurgad** [comment]
ping - @barhamada , is this still outstanding?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
