### ISSUE TITLE
Add text when no billable ASK ID found

### ISSUE THREAD

**Issue by naregal4** [nodejs/help#2427]
Is your feature request related to a problem? Please describe.
The search ASK ID component will only show ASK IDs that have GL_ASSIGNED = Yes. This is to make sure that projects, VMs, etc are not craeted against a non-billable ASK ID. If a user searches for an ASK that exists, but is not billable, the form just returns 0 results.

Describe the solution you'd like
We have had feedback from NPS, users and incidents that users are confused and ask questions about why it is not showing up. It would be good if we could display red text under the field that says something like "No Billable ASK IDs found" or something that would inform the user that they one they searched for can't be used.

OR

Show all ASK names in the list and when someone clicks on an ASK name that hast GL_ASSIGNED=NO, then display text saying it's not billable and can't be used (and maybe link to the instructions on how to assign a GL

**Comment by gireeshpunathil** [comment]
@naregal4 - how this problem statement is related to node.js? you most probably reported this in a wrong repo. can you check?
