### ISSUE TITLE
On creation of new product the Dismiss button need to clear the values entered

### ISSUE THREAD

**Issue by naregal4** [nodejs/help#2428]
Is your feature request related to a problem? Please describe.
The Dismiss button should clear the values for any product but when i start provisining the same product i see the values left in it.

Describe the solution you'd like
On click of Dismiss button the fields should be cleared.

Steps
Select Products, start provisining a VM/AEM/Openshift etc..
Click on Dismiss
Open the same product and try to provision the same product - you would see the values entered previously.

**Comment by gireeshpunathil** [comment]
@naregal4 - how this problem statement is related to node.js? you most probably reported this in a wrong repo. can you check?
