### ISSUE TITLE
Connecting to MongoDB

### ISSUE THREAD

**Issue by edgarasben** [nodejs/help#2429]
* **Node.js Version**: v12.14.1
* **OS**: OS X 10.15.2
* **Scope (install, code, runtime, meta, other?)**: runtime

I am having trouble connecting NodeJS with MongoDB locally. I use .evn to set up the DATABASE_URL:
```js
DATABASE_URL=mongodb://localhost/nodejs-app-db
```

In server.js I try connecting to the MongoDB:
```js
const mongoose = require('mongoose')
mongoose.connect(process.evn.DATABASE_URL, { useNewUrlParser: true })
const db = mongoose.connection
db.on('error', error => {console.error(error)})
db.once('open', () => {console.log('Connected to Mongoose')})
```

Unfortunately, I am getting this error:
```
TypeError: Cannot read property 'DATABASE_URL' of undefined
```

**Comment by gireeshpunathil** [comment]
@edgarascom -

> I use .evn to set up the DATABASE_URL:

can you explain what is `.evn` ? and what is special with that? did you mean environment variable exported / set on the invoking shell? 

if so, here is how you would do it:

`$ export DATABASE_URL=mongodb://localhost/nodejs-app-db`

and then, use

```js
process.env.DATABASE_URL
```

in the code. Please note `env` as opposed to `evn`

**Comment by the-blackpirate** [comment]
process.env.PORT || [PORT NO] this is used to define port address. you can set the environment variable PORT to tell your web server what port to listen on and which port is going to be used. 

> const mongoose = require("mongoose");
> module.exports = {
>   DB: "mongodb://localhost:27017/dashboard"
> };
> const dbURI =
>   "mongodb+srv://username:pass@dbname-hjvjo.gcp.mongodb.net/test?retryWrites=true&w=majority";
> ^^^^^^^ **this is used when you're using mongodb atlas**
> const options = {
>   reconnectTries: Number.MAX_VALUE,
>   poolSize: 10
> };
> 
> mongoose.connect(dbURI, options).then(
>   () => {
>     console.log("Database connection established!");
>   },
>   err => {
>     console.log("Error connecting Database instance due to: ", err);
>   }
> );
> 

Please pass the url string in inverted comma. cheeck above example. i am using local and atlas both in my application.

**Comment by edgarascom** [comment]
> @edgarascom -
> 
> > I use .evn to set up the DATABASE_URL:
> 
> can you explain what is `.evn` ? and what is special with that? did you mean environment variable exported / set on the invoking shell?
> 
> if so, here is how you would do it:
> 
> `$ export DATABASE_URL=mongodb://localhost/nodejs-app-db`
> 
> and then, use
> 
> ```js
> process.env.DATABASE_URL
> ```
> 
> in the code. Please note `env` as opposed to `evn`

**Comment by PoojaDurgad** [comment]
@edgarasben - is this still outstanding?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
