### ISSUE TITLE
Travis CI setup in i18n group

### ISSUE THREAD

**Issue by marocchino** [nodejs/help#243]
Hi.
We have some permission problem.
We recently migrated our repo <https://github.com/nodejs/nodejs-ko> to hexo.
After that, we need some CI since it is not supported by the GitHub pages.

So, I clicked request permission button at travis. and @ChALkeR got private request.
And we don't want **private** permission.

Is there any other way? Can we setup CI without got private permission? Please help us---

**Comment by bnoordhuis** [comment]
I just replied to the GH notification but for the record, there doesn't appear to be a way to give Travis access without also giving it read access to private repositories.

**Comment by Fishrock123** [comment]
I'll set this up, I've done it for the other repos before. The setup is messy and does require giving temporary access to everything.

**Comment by ChALkeR** [comment]
Btw, /cc @henrikhodne — this is not very nice usability- and security-wise. Perhaps something could be done about that on the Travis side?

**Comment by bnoordhuis** [comment]
> The setup is messy and does require giving temporary access to everything.

I don't think that is acceptable.  Are you saying you've done this before?

**Comment by Fishrock123** [comment]
@bnoordhuis Yes. I will need to do it this week **at least** for the github bot so I might as well just do it for the Korean WG too.

**Comment by Fishrock123** [comment]
The process is something like:

- let it have access
- sign in to travis
- turn on the wanted repos
- deny travis access again

**Comment by ChALkeR** [comment]
@Fishrock123 That still sounds pretty bad. Is there a way to enable the repos manually on Travis (i.e. add hooks manually) if that doesn't require access to actually work?

**Comment by bnoordhuis** [comment]
I'm really not pleased to hear about this.  If Travis is compromised at the time of access, our private repositories are comprised.  If we want to be strict about security, we should replace our infra's ssh keys.

/cc @nodejs/build

**Comment by jasnell** [comment]
I agree with @bnoordhuis on this. I'm -1 to enabling travis this way.

**Comment by Starefossen** [comment]
Infra keys managed in the private build repo are all encrypted to prevent a compromise in case of unauthorized access.

But giving Travis all access to everything sounds like a very bad idea in the first place.

**Comment by Fishrock123** [comment]
@ChALkeR Not reliably iirc.

It won't let you admin it without giving it access permission.

--

Choose one this week:

- Move security repos out of the org
- Move all travis-requiring repos out of the org
- Not worry about it

I'm going to get projects the CI access they need and we've done this before. So we need to do something about those because I'm not interested in this getting blocked up again. (we had this issue with the website and readable-stream for a long time)

**Comment by Fishrock123** [comment]
> Infra keys managed in the private build repo are all encrypted to prevent a compromise in case of unauthorized access.

It is possible the private built repo did not exist last time.

**Comment by jasnell** [comment]
-1 to options 1 and 2 (moving any of the repos out of the org). Until travis can be set up in such a way that does not requiring giving access to private repos, we simply should not enable travis.

**Comment by ChALkeR** [comment]
@Fishrock123 That happened at least three times this year, and the private repo did exist back then.

Also, a reminder: we are discussing this on a public repo.

**Comment by Fishrock123** [comment]
> we simply should not enable travis.

Sorry, not an option. Projects have needed this and continue to need it and otherwise we'll need to at least move the github bot out of the org. 
¯\\\_(ツ)\_/¯

**Comment by bnoordhuis** [comment]
Does the GH bot run on our own infrastructure?  The reason Travis is forbidden is that it's an external service that we have no control over and cannot audit (so please don't do that again.)

**Comment by ChALkeR** [comment]
Based on reply from @henrikhodne, http://travis-ci.org should request access only to public repos.
Can we confirm that somehow?

**Comment by ChALkeR** [comment]
Note that «Travis CI for Private Projects» never got approved, «Travis CI» did several times.

**Comment by bnoordhuis** [comment]
The requested access was this:

> @marocchino has requested approval for a third-party application to access Node.js Foundation organization resources via the GitHub API:
>
>  "Travis CI for Private Projects" from Travis CI GmbH
>
> Until it is approved, this application will have no access to private resources and will have read-only access to public resources belonging to your organization.

Read-only access is not a problem, that doesn't require explicit permission.

**Comment by ChALkeR** [comment]
@bnoordhuis That one is surely not needed, and that one was never approved. «Travis CI» was approved, though.

The thing is, that if I understand things correctly we can't verify the access level of any thirdparty application by the users — we could either allow the app or block the app. Allowing the app would allow it to use any scopes given by individual users, but we can't review or check those on the org side.

E.g. if «Application X» requested access from CTC member 1 for private repos, from CTC memeber 2 for public repos — we could either allow all of those or block all of those. We also don't see which scopes were requested or given to the app.

**Comment by ChALkeR** [comment]
Btw, what could be done is: for each sensitive private repo, everyone who has access to that repo could confirm that the appication that we are giving temporary access (in this case, «Travis CI») doesn't have any [scopes](https://developer.github.com/v3/oauth/#scopes) that would give that app access to private repos, once the org would enable that app.

I'm pretty sure that's the case for «Travis CI» (not the «Travis CI for Private Projects»), but we _should_ check that.

**Comment by bnoordhuis** [comment]
@ChALkeR That doesn't sound like a solution to me, that is basically crossing our collective fingers and hoping that the third-party service is never comprised or turns evil.

**Comment by ChALkeR** [comment]
@bnoordhuis No, it's not. If the necessary precautions I described are taken, how excactly would it be possible to evade those to reach private repos?

**Comment by bnoordhuis** [comment]
Wait, I think I understand the confusion.  The page you link to describes scopes as a way for third-party services to voluntarily reduce their access token's, er, scope (the intersection of allowed_permissions_set and requested_permissions_set) but you are talking about handing out pre-generated access tokens from https://github.com/settings/tokens/new with reduced permissions.

**Comment by outsideris** [comment]
Is there any progress?

**Comment by marocchino** [comment]
Our team decide to use a private CI.
Fell free to close this. :3

**Comment by bnoordhuis** [comment]
Thanks, I'll close.

**Comment by ChALkeR** [comment]
Btw, https://developer.github.com/early-access/integrations/ should fix the security concerns about granting access to Travis, so when/if Travis adopts that, we could install Travis CI to repos on a per-repo basis.
