### ISSUE TITLE
Using Windows dlls from nodejs

### ISSUE THREAD

**Issue by EducadorProgramadorProfeta** [nodejs/help#2432]
* **Version**:
* **Platform**:
* **Subsystem**:

Hi people.

I tried to find out which package / lib / fw allows me to open Windows dlls in node.js. I found a npm lib called ffi that "promises" to make it easy. When I tried to install ... ERROR !!!

I saw an comment that version 12 of node.js cannot allow the installation of such a package, only in the previous ones. They gave a link to a lib on GitHub that promised to resolve the incompatibility of node.js 12 with this ffi.

I tried both: I downloaded the lib and tried to install: NOTHING! I downloaded version 10 of node.js and installed and tried to install ffi: NOTHING !!! Any other normal npm package installs without problems. I already checked prerequisites and everything was ok.

Has anyone been through this or can you shed some light on the problem, please?

Thanks in advance.

**Comment by Hakerh400** [comment]
You don't need any external package. You can simply write a native addon (in C++) and compile it using node-gyp, then in the addon you can use functions from `windows.h` to load external dynamic library (DLL) and call any function you want. Note: you need to know in advance for each function from the DLL what arguments it takes and the type of the return value.

**Comment by PoojaDurgad** [comment]
@EducadorProgramadorProfeta - is this still an issue? did @Hakerh400 ' s suggestion help you to resolve the issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!! please feel free to re-open the issue if it is outstanding

**Comment by Pomax** [comment]
Small note on Hakerh400's comment: that's not a "just", that's using a second programming language (which you don't know) to use a library that you may not even control. If all you have is a dll file and you want to work with it, you'd expect Node to have something similar to Python's [ctypes](https://docs.python.org/3/library/ctypes.html) package, with things like `windll.LoadLibrary(library_path)`.

**Comment by wanglin86769** [comment]
Strongly agree with Pomax's point!
Python provides ctypes as a straightforward way to load an existing C/C++  shared library. Therefore, I thought node has the same mechanism. However, node officially only provide addon which is complicated (even node-addon-api). The ffi modules of node are typically provided and maintained by other persons, so the lifecycle is very short and the quality is not guaranteed.

**Comment by wanglin86769** [comment]
Now in 2023, I would recommend koffi package.
https://www.npmjs.com/package/koffi

**Comment by ewwink** [comment]
4 years laters, nodejs still busy adding more versions but not adding essential library 😁
