### ISSUE TITLE
Thread pool implementations

### ISSUE THREAD

**Issue by pioardi** [nodejs/help#2433]
Hi ,
I would like to receive feedbacks on my thread pool implementations https://github.com/pioardi/poolifier , this contain two implementations a fixed and a dynamic one .

I would appreciate very much your feedbacks .

**Comment by bmuenzenmeyer** [comment]
This question is idle and left unanswered for years now.

I am happy to see the project linked above continuing to have active development. 

- I wonder if feedback has been received through other channels in the meantime and that this question could be closed?
- Have you attempted to ask this question within other communities, such as [stackoverflow](https://stackoverflow.com/questions/tagged/node.js?tab=Newest) or [slack channels](https://nodejs.org/en/get-involved/)
- Soliciting for more-specific dimensions of feedback might yield better results.

I am going to circle back in a couple weeks to see if we can close as no-longer relevant.

**Comment by pioardi** [comment]
Hello @bmuenzenmeyer ,
I have not received a feedback but the thread pool is working properly and is pretty used today.

We can close the issue at this point, thanks
