### ISSUE TITLE
ETIMEDOUT error most of the time

### ISSUE THREAD

**Issue by mayankagarwal900** [nodejs/help#2434]
{ Error: connect ETIMEDOUT 13.110.0.73:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.110.0.73',
  port: 443 }
i am connecting my node.js server to salesforce after some time i get this error? And i am using the express framework.Please provide me solution?

Thanks!!!

**Comment by gireeshpunathil** [comment]
@mayankagarwal900 - from the box where you host the server, can you try pinging the target system and see what happens?

**Comment by mayankagarwal900** [comment]
No this do not help me, the problem is when i connect node.js to salesforce through oAuth connection and start downloading the files and attachments from salesforce its after some time through this error if you can suggest me also how can i handle this error this also be very helpful to me.

**Comment by gireeshpunathil** [comment]
@mayankagarwal900 - ok, so the connection was previously established, and then it times out in the middle of it?

if so I would not debug at the node side, instead at the other end point.

In either way, employing [tcpdump](https://linux.die.net/man/8/tcpdump) or [wireshark](https://www.wireshark.org/) to see what happens in the wire seems to be a good idea for me.

**Comment by mayankagarwal900** [comment]
Actually can you give me idea how much node.js will be wait for response from other endpoints if files are larger?

**Comment by gireeshpunathil** [comment]
that depends on:

 - which API you are using to make the request
 - and whether you are relying on the default timeout defined by the API, or overriding it

can you share your that piece of code?

**Comment by gireeshpunathil** [comment]
file being larger should cause `timeout` for a well designed API IMO. As long as the `flow` is ON, it should treat the connection as active. The timeout should kick-in only for inactive connections, counting from the time the last byte sent.

I may be wrong.

**Comment by mayankagarwal900** [comment]
function attachments(attachmentInfo, conn, fileOut) {
    try {
        return new Promise((resolve, reject) => {
            setTimeout(function () {
                conn.sobject('Attachment').record(attachmentInfo.Id).blob('Body').pipe(fileOut).on("error", (err) => {
                    console.log("ERROR::::: while download attachment --> ", err);
                    reject(err);
                }).on("finish", (finish) => {
                    console.log('INFO:::: Finish -======>>>>>>   ', attachmentInfo.Id);
                    resolve(true);
                })
            }, 1000);
        });
    } catch (e) {
        console.log('error', e);
    }
}
This line is making the request in salesforce to download the file.
conn.sobject('Attachment').record(attachmentInfo.Id).blob('Body').pipe(fileOut)
where attachmentInfo.Id is record id 
and fileOut is the path where to write file.

**Comment by gireeshpunathil** [comment]
ok, thnx. what that object `conn` represents? you might need to check the doc for `sobject` API in that module's documentation, to see what is the default timeout, and how to override that.

**Comment by mayankagarwal900** [comment]
I did not find their solution, the conn represent the the connection between salesforce and node.js

**Comment by gireeshpunathil** [comment]
> the conn represent the the connection between salesforce and node.js

ok, but it may be an implementation in your program, or an npm module, not an node.js API (because there is no `sobject` function in any of our HTTP/S implementations). that is why I suggested to identify and check with the module.

**Comment by mayankagarwal900** [comment]
Okay @gireeshpunathil  i will look it out thanks for your support.

**Comment by PoojaDurgad** [comment]
@mayankagarwal900 - is this issue resolved? did @gireeshpunathil 's suggestion help you to resolve the issue?

**Comment by mayankagarwal900** [comment]
Yes this is resolved @PoojaDurgad

**Comment by PoojaDurgad** [comment]
@mayankagarwal900 - as this issue is resolved can you close the issue please?

**Comment by Shivamsharma009** [comment]
I am Facing this same problem what can i do

**Comment by Mahmod9674** [comment]
How did you solve this issue ?

**Comment by da-nazy** [comment]
Please include how an issue was resolved

**Comment by utkarsh6300** [comment]
@mayankagarwal900 do share solution

**Comment by radhewro** [comment]
Hey, boy, share your experience with the pub

**Comment by benjamingr** [comment]
@radhewro hey, can you please self-moderate your comment? Namely, calling people "boy" doesn't really translate well into international culture and can mean something insensitive/racist which you probably didn't mean.
