### ISSUE TITLE
Require not recognized by the node.js

### ISSUE THREAD

**Issue by farynam** [nodejs/help#2436]
* **Version** : v13.7.0
* **Platform**: Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
* **Subsystem**: fs

When I try:

```
const fs = require('fs');
console.log(fs.mkdirSync);
```

I get message:

> (node:2442) ExperimentalWarning: The ESM module loader is experimental.
> file:///Users/marcin/projects/webdiff-all/webdiff-test/src/index.js:1
> const fs = require('fs');
>            ^
> 
> ReferenceError: require is not defined
>     at file:///Users/marcin/projects/webdiff-all/webdiff-test/src/index.js:1:12
>     at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
>     at async Loader.import (internal/modules/esm/loader.js:164:24)

It is also impossible to use import like:

```
import {fs} from "fs";
console.log(fs.mkdirSync);
```

I get:

> node src/index.js 
> (node:2431) ExperimentalWarning: The ESM module loader is experimental.
> file:///Users/marcin/projects/webdiff-all/webdiff-test/src/index.js:1
> import {fs} from "fs";
>         ^^
> SyntaxError: The requested module 'fs' does not provide an export named 'fs'
>     at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
>     at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
>     at async Loader.import (internal/modules/esm/loader.js:164:24)
> 

my package.json:
```
{
  "name": "webdiff-test",
  "version": "1.0.2",
  "description": "12345689",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "app": "node src/index.js"
  },
  "keywords": [],
  "author": "Marcin Faryna",
  "license": "ISC",
  "dependencies": {

  },
  "devDependencies": {

  }
}
```

**Comment by PoojaDurgad** [comment]
@farynam - were you able to follow @lundibundi 's suggestion? or is this still an issue?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
