### ISSUE TITLE
How to change default http parser or edit response headers?

### ISSUE THREAD

**Issue by UnknownDevBY** [nodejs/help#2437]
* **Node.js Version**: 10.15.2
* **OS**: 
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

When i run server locally, I'm able to change default http parser this way?

```js
process.binding('http_parser').HTTPParser = require('http-parser-js').HTTPParser;
```

But when I deploy it, it doesn't affect anything. The reason why i need to do that is HPE_UNEXPECTED_CONTENT_LENGTH error that is thrown when there-are 2 content-length headers or if there are transfer-encoding:chunked and content-length provided simultaneously.

Please provide other ways to change default http parser or edit response headers

**Comment by Hakerh400** [comment]
> But when I deploy it, it doesn't affect anything.

Where do you deploy it? Most of the popular Node.js application hosting services (Heroku, RedHat, OpenShift, Zeit, etc..) use a proxy server between end users and Node.js application.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding

**Comment by kimnamcham** [comment]
same issues. Anyone can resolve it ?
