### ISSUE TITLE
Issue: I am calling a function in a different class that makes A network call and processes the results. However, meanwhile the calling code starts executing and the proper results are not received from the called code

### ISSUE THREAD

**Issue by Garv-Sharma** [nodejs/help#2439]
* **Node.js Version**: 10.16.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: azure-storage

Here is the called function:
`class ChatTranscripts{

    constructor(conversationID, channel){
        super();
        // prefix = channel + "/" + conversationID;
        prefix = channel1 + "/" + conversationID1
    }

    fetchTranscripts(context){
        console.log('in fetchTranscripts');
        var blobService = azure.createBlobService(storageAccount, key);
        console.log(prefix);
        blobService.listBlobsSegmentedWithPrefix(container, prefix, null, function(err, results, resp){
        console.log('AAAAAAAAAAAAA');
        if(err)
            console.log(err);
        // else   
        //     console.log(results);
        results.entries.forEach(element => {
            
            blobService.getBlobToText(container, element.name, function(err, results, resp){
                console.log('BBBBBBBBBBBBBBBB');
                if(err)
                    console.log(err);
                // console.log('Transcript:', results, '\t');
                var jsobject = JSON.parse(results);
                // console.log(jsobject);
                if (jsobject.type == "message"){
                    sendConv.push(results);  
                    console.log('>>>>>>>>',jsobject.text);     
                    // console.log(sendConv);      
                }
            });
        });
    });
    
    console.log('1',sendConv,'\n');
    return sendConv;
    }
}
module.exports.ChatTranscripts = ChatTranscripts;    `

The calling code:
`var chatT = new ChatTranscripts(chatP.conversationId, stepContext.context.activity.channelId);
 var transcripts = chatT.fetchTranscripts();`

I am receiving empty [] in transcripts and the code goes ahead while the called function is still executing.
How do I make it synchronous?

**Comment by Hakerh400** [comment]
```js
class ChatTranscripts{
  constructor(conversationID, channel){
    prefix = channel + '/' + conversationID;
  }

  fetchTranscripts(context){
    return new Promise((res, rej) => {
      const blobService = azure.createBlobService(storageAccount, key);
      const sendConv = [];

      blobService.listBlobsSegmentedWithPrefix(container, prefix, null, (err, results, resp) => {
        (async () => {
          if(err) return rej(err);

          for(const element of results.entries){
            await new Promise((res, rej) => {
              blobService.getBlobToText(container, element.name, (err, results, resp) => {
                if(err) return rej(err);

                const jsobject = JSON.parse(results);
                if(jsobject.type === 'message')
                  sendConv.push(results);

                res();
              });
            });
          }

          res(sendConv);
        })().catch(rej);
      });
    });
  }
}

(async () => {
  const chatT = new ChatTranscripts(chatP.conversationId, stepContext.context.activity.channelId);
  const transcripts = await chatT.fetchTranscripts();

  console.log(transcripts);
})().catch(console.error);
```

**Comment by Garv-Sharma** [comment]
Thank you @Hakerh400 for the clear and precise solution. It worked.

**Comment by Garv-Sharma** [comment]
Hi @Hakerh400 I thought I understood the code but I didn't. Can you explain the need for two Promises? What is the use of res() and where should it be placed?
I have a requirement of fetching transcripts from multiple conversation Ids. I used a loop for this but all transcripts started coming in parallel and it was a mess. Do I need another promise inside the loop?

**Comment by Hakerh400** [comment]
This may help you:

* https://nodejs.org/uk/docs/guides/event-loop-timers-and-nexttick/
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
