### ISSUE TITLE
How to upgrade the Node in macOS

### ISSUE THREAD

**Issue by LeiSe7en** [nodejs/help#244]
Hello, i have installed the node -v 4.4.1, now i want to upgrade to the newest one for launching ES6
, but i dont find how to upgrade.

Thanks in advance!

**Comment by Fishrock123** [comment]
Using [`nvm.sh`](https://github.com/creationix/nvm/blob/master/README.markdown) is probably the best way right now.

Alternatively, you could just download the desired version installer from https://nodejs.org/en/download/ and re-install it (which is safe to do).

**Comment by LeiSe7en** [comment]
Thanks for your answer;
If i re-install the node, do i need to uninstall the pre- version?

**Comment by LeiSe7en** [comment]
THANKS

**Comment by LeiSe7en** [comment]
Thanks for your answer @Fishrock123 

But if i want to re-install the node , should i uninstall the pre-version first? Or only straightly re-install a new one?

Best wish
