### ISSUE TITLE
childprocess.execSync for curl request not returning error if curl request is 404 or 403

### ISSUE THREAD

**Issue by Aghamyr** [nodejs/help#2441]
* **Version**: 8.16.2
* **Platform**: windows
* **Subsystem**:

Hi, this might not be an issue per say but here is my problem : I'm using childprocess.execSync to execute curl request on pages I need the html content of. It works perfectly fine for valid pages but if the curl request to a page return pretty much any error code such as 404 or 403, then the result of the execSync is empty and I have no way to know what error code the curl encountered. 
Is there any way to know the curl error code that happens during the childprocess.execSync ?

**Comment by Aghamyr** [comment]
Well, I found a way, look like I just had to pass "-i" with my curl request to return the response headers too and not just the body, now I can just parse that and see the error code I got.
Not exactly the easiest way, but I guess that works for now.

Would still be interested in knowing if there is a better way to just get the curl error directly instead

**Comment by richardlau** [comment]
Does `-f` work for your use cases?

**Comment by Aghamyr** [comment]
I don't think it would, as I actually want to know if I got a 404 or 403 response from the server, if I understood curl documentation correctly '-f' makes it so curl doesn't return any response when there is an error and instead gives a curl error 22.
