### ISSUE TITLE
How to persist 3 models with single controller 

### ISSUE THREAD

**Issue by rajkumar364** [nodejs/help#2443]
**1 st Model**

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Create Shema
const UserAuth = new Schema({

  user_auth_id: {
    type:Number,
    required: true
  },
  userprofile: {
    type: Schema.Types.ObjectId,
    ref: 'userprofiles'
  },
  otp: {
    type:Number
  },
  pwd: {
    type:String
  },
  loginmode: {
    type:String
  },
  deviceid: {
    type:String
  },
  authorized: {
    type:String
  },
  status: {
    type:String
  }
});

// Create collection and add schema
mongoose.model('userauths', UserAuth,'userauths');

2nd Model

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Create Shema
const UserEntity = new Schema({

  user_entity_id: {
    type:Number,
  },
  userprofile: {
    type: Schema.Types.ObjectId,
    ref: 'userprofiles'
  },
  userwallet: {
    type: Schema.Types.ObjectId,
    ref: 'wallets'
  },
  gender: {
    type: String
  },
  dob: {
    type: Date
  },
  primaryaddress: {
    type: Schema.Types.ObjectId,
    ref: 'addresses'  
  },
  addresses: {
    type: Schema.Types.ObjectId,
    ref: 'addresses'
  },
  status: {
    type: String
  }
});

// Create collection and add schema
mongoose.model('users', UserEntity, 'users');

3 rd Model 

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Create Shema
const UserProfile = new Schema({

  user_profile_id: {
    type:Number,
    required: true
  },
  mobile: {
    type:Number
  },
  email: {
    type:String
  },
  firstname: {
    type:String
  },
  lastname: {
    type:String
  },
  googleid: {
    type:String
  },
  facebookid: {
    type:String
  },
  twitterid: {
    type:String
  },
  profilephoto: {
    type:String
  },
  status: {
    type:String
  }
});

// Create collection and add schema
mongoose.model('userprofiles', UserProfile,'userprofiles');

**Comment by gireeshpunathil** [comment]
@rajkumar364 - is this issue outstanding? If so, I suggest this to be asked in mongoose' repository.

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
