### ISSUE TITLE
Why Node uses syscalls instead libuv's abstractions

### ISSUE THREAD

**Issue by juanarbol** [nodejs/help#2444]
* **Node.js Version**: Current
* **Scope (install, code, runtime, meta, other?)**: codebase
* **Module (and version) (if relevant)**: fs

Why are syscalls used on some `fs` internal binding methods? Like [chmod](https://github.com/nodejs/node/blob/master/src/node_file.cc#L1900), insead of using libuv methods, like -in this case- [uv_fs_chmod](http://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_chmod).

**Comment by santigimeno** [comment]
Indeed, they're using `libuv` functions. Take a look at [`FSReqBase` implementation](https://github.com/nodejs/node/blob/52a3e3560484ec3ad4479ef80d829f7c99d39e80/src/node_file-inl.h#L219-L252) which inherits from [`ReqWrap`](https://github.com/nodejs/node/blob/52a3e3560484ec3ad4479ef80d829f7c99d39e80/src/req_wrap-inl.h#L137-L164).

**Comment by juanarbol** [comment]
¡Gracias Santiago!
