### ISSUE TITLE
install react app command doesn't work properly. CALL ... is not recognized as an internal or external command appears

### ISSUE THREAD

**Issue by sahin52** [nodejs/help#2445]
I am trying to create a react application in my localhost, but I am not able to. 
When I type "npm install -g create-react-app" and hit enter an error happens:
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command, operable program or batch file.

After that when I create a react app and start I get this:
npm ERR! missing script: start
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sahin\AppData\Roaming\npm-cache\_logs\2020-01-27T03_57_12_848Z-debug.log

when I add start script in manifest I get these:

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn C:\Python27\Scripts
npm ERR! file C:\Python27\Scripts
npm ERR! path C:\Python27\Scripts
npm ERR! errno ENOENT
npm ERR! reacta@1.0.0 start: `node your-script.js`
npm ERR! spawn C:\Python27\Scripts ENOENT
npm ERR!
npm ERR! Failed at the reacta@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Hakerh400** [comment]
Same error as in https://github.com/nodejs/help/issues/1019, https://github.com/nodejs/help/issues/1981, https://github.com/nodejs/help/issues/2054, https://github.com/nodejs/help/issues/2266

However, none of the linked issues seem to provide a solution or explanation why it happens. The explanation in https://github.com/nodejs/help/issues/1019#issuecomment-354652365 seems reasonable.

**Comment by PoojaDurgad** [comment]
@sahin52 - is this issue resolved? 
for me with your issue seems like your installation requires python , if it is installed make sure it is configured correctly  or else installing python may resolve your issue

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to re-open if that is not the case.
