### ISSUE TITLE
Are there some test cases for `node/lib`?

### ISSUE THREAD

**Issue by zeroFruit** [nodejs/help#2447]
I want to write a test cases for `node/lib/internal` to see how actually linkedlist, timers work

Are there any existing test cases for `node/lib`?

**Comment by zeroFruit** [comment]
Ok I found it on https://github.com/nodejs/node/blob/8baaa25aec5a052c32d63f1f7f77bbd0e4a78796/test/parallel/test-timers-linked-list.js

**Comment by PoojaDurgad** [comment]
@zeroFruit - looks like it is no longer an issue if that is the case can you close the issue please.

**Comment by gireeshpunathil** [comment]
answered, closing
