### ISSUE TITLE
HTTP request body stream receive only half and hang up with incomplete data randomly

### ISSUE THREAD

**Issue by haiqwu** [nodejs/help#2449]
* **Node.js Version**: v12.13.0
* **OS**: OS X El Capitan Version 10.11.6 15G31
* **Scope (install, code, runtime, meta, other?)**:code & runtime
* **Module (and version) (if relevant)**: body-parser: 1.19.0

Hello,

I am using expressJS with Node to implement server of a web application.
I am sending a JSON(about 300KB in size) in request body through a POST request to the server by POSTMAN and Axios from react frontend (attacher here)
[testdata.txt](https://github.com/nodejs/help/files/4123253/testdata.txt)
However, the data trunk is not properly received, it will stuck in the middle of receiving the request data. If I enable the body-parser middleware (Line CODE 1 below), it will stuck in the body-parser. So I write my own parser (CODE 2 below) to see what happened, I get random behaviour that sometimes it will work, all the data received and processed successfully, but sometimes it will stuck, and waiting there for the rest of data to be sent by the stream.
More technically, the expected behaviour is
the stream listens for 'data' coming in until all being processed, then 'end' event will be send out to indicate all data received.
But it happens that the stream waiting for 'data' infinitely.

Please give any suggestion, thanks in advance.

Best,
Haiqi 

//code below
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const router = require('./router');
const path = require('path');

function initialize() {
  return new Promise((resolve, reject) => {
    const app = express();
    app.use(cors());
    app.use(express.static(`${__dirname}/../public`));

    // app.use(bodyParser.json({limit: '50mb'})); // CODE 1

    app.use(function(req, res, next) { // CODE 2
      const l = req.headers['content-length'];
      console.log('Total len:', l);
      var data = '';
      req.on('data', function(chunk) {
        console.log('recieved: ', chunk.length);
        data += chunk;
      });
      req.on('end', function() {
        console.log('ending...  ');
        req.rawBody = data;
        //console.log( 'on end: ', data );
        if (data && data.indexOf('{') > -1 ) {
          req.body = JSON.parse(data);
        }
        next();
      });
      req.on('close', function() {
        console.log('REQUEST CLOSED!');
      });
      req.on('error', function(err) {
        console.log('On ERROR');
        console.log(err);
      });
    }); // hand-written body parser- @TEST 

    app.listen(webServerConfig.port)
      .on('listening', () => {
        logger.warn(`Web server listening on port ${webServerConfig.port}`);
        resolve();
      })
      .on('error', err => { });
  });
}
-----------------------------------------------------------------------------------------------------
Test Result (4) (POSTMAN)

warn: Web server listening on port 8080 {"service":"services.web-server","timestamp":"2020-01-28 10:45:52"}
POST /api/production/
req params:  {}
Total len: 329525
recieved:  65045
recieved:  65536
recieved:  65536
recieved:  2336
(FAIL CASE : server hang up here, and stuck until timeout)
============================
POST /api/production/
req params:  {}
Total len: 329525
recieved:  65045
recieved:  65536
recieved:  65536
recieved:  65536
recieved:  65536
recieved:  2336
ending...  
(SUCCESS CASE)
============================
POST /api/production/
req params:  {}
Total len: 329525
recieved:  65045
recieved:  65536
recieved:  2336
(FAIL CASE : server hang up here, and stuck until timeout)
=============================
POST /api/production/
req params:  {}
Total len: 329525
recieved:  65045
recieved:  65536
recieved:  65536
recieved:  2336
(FAIL CASE : server hang up here, and stuck until timeout)

**Comment by haiqwu** [comment]
Update': I tried the same code on another Linux Mint system and Mac OS Mojave , and it works. So it seems like the OS matters here?

**Comment by gireeshpunathil** [comment]
@haiqwu - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
