### ISSUE TITLE
how to install node.js from downloads?

### ISSUE THREAD

**Issue by nealjwang** [nodejs/help#245]
I downloaded the node-v4.4.7-linux-x64.tar.xz and moved it into my linux vm, i tar'd it using the command tar-xvf node-v4.4.7-linux-x64.tar.xz

what do i do next? 

I went here, http://www.thegeekstuff.com/2015/10/install-nodejs-npm-linux, and to similar sites but it doesn't seem to help

**Comment by addaleax** [comment]
The `Install it under /usr/local` of the site you linked to seems to be pretty accurate, did you try that?

**Comment by nealjwang** [comment]
I tried it and got this

**Comment by nealjwang** [comment]
[root@interstagedemo ~]# cd /usr/local/
[root@interstagedemo local]# ls
bin  games    lib    libexec                       sbin   src
etc  include  lib64  node-v4.4.7-linux-x64.tar.xz  share
[root@interstagedemo local]# tar --strip-components 1 -xzf /usr/save/node-v4.4.7-linux-x64.tar.xz
tar (child): /usr/save/node-v4.4.7-linux-x64.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by addaleax** [comment]
@nealjwang Instead of `/usr/save/node-v4.4.7-linux-x64.tar.xz` in the command, can you just try `node-v4.4.7-linux-x64.tar.xz` (no `/usr/save/`)?

**Comment by lordKnighton** [comment]
Try this link as well   🔥  [click me](http://ask.xmodulo.com/install-node-js-linux.html) 🔥

**Comment by nealjwang** [comment]
@addaleax I got this: [root@interstagedemo local]# tar --strip-components 1 -xzf node-v4.4.7-linux-x64.tar.xz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by addaleax** [comment]
@nealjwang, oh yeah, right, `-xzf` is for `.gz` files. `-xJf` should work instead :)

**Comment by nealjwang** [comment]
@addaleax hmm the -xjF didn't work, I did the original tar --strip-components -xvf node-v4.4.7-linux-x64.tar.xz and it seems to work now, thank you! I did not know you were supposed to download and unzip it to /usr/local, I am now able to type in node -v and get something back from the console, thanks so much!
