### ISSUE TITLE
Error: async hook stack has become corrupted (actual: 205, expected: 185)

### ISSUE THREAD

**Issue by ayushantiwal** [nodejs/help#2451]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by PoojaDurgad** [comment]
@ayushantiwal - can you elaborate the issue please? so that it will be helpful to debug your error. like  which os you are using ?what version of node.js you are using? which instruction is leading to this error?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
