### ISSUE TITLE
WriteFile/writeFileSync problem with 2 letter words while saving JSON in a specific path

### ISSUE THREAD

**Issue by banjo** [nodejs/help#2453]
* **Version**: v12.14.0
* **Platform**:64-bit Windows
* **Subsystem**:

There is a problem while trying to save stringified JSON files when the file name is 2 letters long. Somehow, it prints things that has been printed way before into the file.

The code is running in the ClientApp folder within a ASP.NET Core, Angular application. 

Code:
 
```
const fs = require(`fs`);

const example = {
  "hello": 1,
  "something": {
    "helloAgain": "hello",
    "godday": 2
  }
}

fs.writeFileSync(`../wwwroot/assets/i18n/he.json`, JSON.stringify(example)); // 2 letters
fs.writeFileSync(`../wwwroot/assets/i18n/hej.json`, JSON.stringify(example)); // 3 letters

```

he.json:
![he.json](https://i.imgur.com/WuiOmk0.png)

The file is way longer... and includes many previous WriteFile JSONs.

hej.json:
![hej.json](https://i.imgur.com/8Al3DcZ.png)

It's quite specific, but I figured it was worth reporting. Might happen somewhere else as well.

**Comment by addaleax** [comment]
@banjo The data in the screenshots doesn’t match your example – can you maybe share a full reproduction?

**Comment by banjo** [comment]
Exactly, the data was way of. However, the problem does not seem to be with WriteFile. There was something with a file in that folder, which in some way corrupted other files... So I'll close this issue. Thank you anyways!
