### ISSUE TITLE
Do we need to build a new addon for each version of Node?

### ISSUE THREAD

**Issue by TCourtneyOwen** [nodejs/help#2456]
* **Node Version**: Node 10
* **Platform**: Windows
* **Compiler**: msbuild
* **Module**: an addon

I built a Node addon using Node 10, but it doesn't work in Node 8, or presumably in Node 12. Is it required to build separate addons for each and every version of Node? I was hoping that I could build an addon in a single version and it would be compatible with all LTS versions of Node.

Here's the error I get when I try to use the addon with a different version of Node than I built it with:

Error: The module '\\?\D:\VS-Code-Edge-Debugger-Extension\out\lib\Addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing

Thanks,

Courtney

**Comment by mhdawson** [comment]
@TCourtneyOwen as @richardlau mentions one of the reasons for N-API was to allow use across Node.js LTS versions.

**Comment by TCourtneyOwen** [comment]
So I could in theory build the addon on Node 10, for example, and then use the N-API conversion tool on Node 12 to convert the addon to work on Node 12.? Is that the workflow?

**Comment by bnoordhuis** [comment]
No. You compile it once. The add-on should then work with both v10.x and v12.x.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
