### ISSUE TITLE
unable to add property to object from within a function.

### ISSUE THREAD

**Issue by 3AUCE** [nodejs/help#2457]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:
for some reason i cant seem to figure out how to add a new property to an object from within a function. i keep getting an undefined response when i try to print the value from outside of the function. 

```
							getid(function(result){
								employeeSchedule.scheduleid = 9999;
								return 9999;
							});
```
scheduleid is not being added to the employeeSchedule object and when i try to console.log(getid()) i get undefined. perhaps my frustration is causing me to not see the issue.

**Comment by agnjunio** [comment]
There can be many reasons you can't find the object you want. You example has little information, but since I can't help you with the exact answer I will leave a post that might help you understand what you need to do.

http://ryanmorr.com/understanding-scope-and-context-in-javascript/

**Comment by ArkinSolomon** [comment]
Your example isn't clear. You might want to use arrow functions which keep the scope. You do however need to provide more explanation, such as the parameters and usage of parameters of `getid()` as well as the scope of both `getid()` and `employeeSchedule`.

**Comment by gireeshpunathil** [comment]
@3AUCE - is this outstanding?
