### ISSUE TITLE
impossible to install @angular cli

### ISSUE THREAD

**Issue by nailik86** [nodejs/help#2458]
* **Version**:13.0.0-nightly20190802452b393c
* **Platform**: 5.3.0-26-generic nodejs/node#28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**:

Hi, 

node : 
platform:  ubuntu
I try to install globally angular-cli with the version of node (npm -install -g @angular/cli)

For information, I have install node 12 and it's working correctly.

I got the following error :
npm WARN npm npm does not support Node.js v13.0.0-nightly20190802452b393c1f
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/2494/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @angular/cli@8.3.24 postinstall /usr/local/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

cannot create user data directory: /nonexistent/snap/node/2494: Permission denied
npm WARN You are using a pre-release version of node and things may not work as expected

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/cli@8.3.24 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @angular/cli@8.3.24 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-31T20_58_05_693Z-debug.log

**Comment by ArkinSolomon** [comment]
Have you updated npm with `npm install -g npm`?

**Comment by nailik86** [comment]
No, maybe this can solve the issue. 

But I have install node from the ubuntu catalog and npm was also install by this action.

With best regards,
Kilian

**Comment by rmckeel** [comment]
@nailik86 This Q&A may be related to this issue, worth checking out https://stackoverflow.com/a/19132229/3232832.

**Comment by PoojaDurgad** [comment]
@nailik86 - is this still outstanding? were you able to follow the suggestions mentioned in comment section?
for me with your issue looks similar to https://github.com/angular/angular-cli/issues/14584 hopefully this may help you to get rid of this issue.

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to reopen the issue if its still outstanding
