### ISSUE TITLE
`fs.writeFileSync` results in `EBUSY` error but no processes using the destination file

### ISSUE THREAD

**Issue by SterlingButters** [nodejs/help#2459]
* **Node.js Version**: v12.14.0
* **OS**: Raspbian Buster
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: fs 6.13.4

Greetings,

I am having an issue with `fs.writeFileSync` in the following manner:

I am trying to write to a system file under `/sys/kernel/config/usb_gadget` with `fs.writeFileSync` but when writing `""` as the contents, the file remains unchanged (with original contents in tact) - same for `fs.truncateSync`. Additionally, I get
```
Error: EBUSY: resource busy or locked, write
    at Object.writeSync (fs.js:581:3)
    at Object.writeFileSync (fs.js:1275:26)
    at Socket.<anonymous> (/opt/sterling/ip-kvm-interface/app.js:249:6)
    at Socket.emit (events.js:210:5)
    at /opt/sterling/ip-kvm-interface/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -16,
  syscall: 'write',
  code: 'EBUSY'
}
```
when writing some other contents. Permissions for the destination write file are 777.

Using `fsuser /sys/kernel/config/usb_gadget/kvm-gadget/UDC` returns nothing (even when Node process is running) and `lsof | grep /sys/kernel/config/usb_gadget/kvm-gadget/UDC` also returns nothing.

Are there undocumented limitations to `fs.writeFileSync` that I am unaware of?

**Comment by bnoordhuis** [comment]
> Are there undocumented limitations to fs.writeFileSync that I am unaware of?

Nothing specific to `fs.writeFileSync()`, you can get the same error with a plain C program.

`/sys/kernel/config/usb_gadget` is not a real file, it's a communication channel with the kernel's usb gadget driver. It's that driver that is returning the error.

(I could point you to the line of code if you're really interested. It's `drivers/usb/gadget/configfs.c` in the kernel source tree in any case.)

**Comment by SterlingButters** [comment]
@bnoordhuis thank you! So are there any alternatives I might be left with using the `fs` package? Or maybe I should use this: https://www.npmjs.com/package/node-echo?

**Comment by SterlingButters** [comment]
@bnoordhuis Also what does that mean "not a real file" - how can I interact with a file that isn't real, `fs` or otherwise?

**Comment by bnoordhuis** [comment]
"Not a real file" means it's not an actual file that exists on disk. sysfs (files under /sys) is a virtual file system where the kernel exposes its configuration knobs as file-like entities.

You'd have to consult the driver's documentation to see if there's a workaround for your issue. Right now, it's telling you it's not accepting input at this time.

**Comment by SterlingButters** [comment]
@bnoordhuis thank you for that clarification

I found a workaround by creating a `bash` file that contains an `echo` process to feed to the desired contents into the desired file-destination when I synchronously `spawn` the bash file. 

While I would prefer to use `fs`, this works acceptably for now - perhaps writing to virtual files would be a good feature suggestion?
