### ISSUE TITLE
Problem with importing/requiring modules

### ISSUE THREAD

**Issue by IssaAbdullah** [nodejs/help#246]
Hello guys, i'm new to Node, so help me out;
Each time i require/import my own modules i keep getting the following error;
![noderror](https://cloud.githubusercontent.com/assets/19847742/17513742/6347a2bc-5e37-11e6-8330-d92d3646d774.png)

**Comment by lordKnighton** [comment]
Hey bro, show us the bit, the part where your requiring files/modules 💾

**Comment by IssaAbdullah** [comment]
Here is the code and directory structure;
![capture-20160810-235836](https://cloud.githubusercontent.com/assets/19847742/17571202/e71e4822-5f57-11e6-86ce-e49e578d8263.png)
<hr>
![capture-20160810-235928](https://cloud.githubusercontent.com/assets/19847742/17571228/0910aec0-5f58-11e6-9bb2-ab69a5dc6fbb.png)
<hr>
![capture-20160811-000025](https://cloud.githubusercontent.com/assets/19847742/17571249/1fa6e88e-5f58-11e6-9416-12bc19fe4d61.png)

**Comment by addaleax** [comment]
Wild guess, what encoding are you using for your files? “weird characters at the start of the file” is usually a good candidate for BOMs, but usually Node should strip them.

Either way, the output of `node -p "require('fs').readFileSync('app.js')"` might be helpful here.

**Comment by bnoordhuis** [comment]
> "weird characters at the start of the file” is usually a good candidate for BOMs, but usually Node should strip them.

Only the UTF-8 BOM, EF BB BF.  Node always parses source files as UTF-8.

**Comment by kahwee** [comment]
<img width="560" alt="screen shot 2016-08-10 at 2 54 50 pm" src="https://cloud.githubusercontent.com/assets/262105/17572649/7c3ff4a8-5f0a-11e6-850b-a6ed7aef5c38.png">

Try saving as UTF-8 in Sublime Text.
