### ISSUE TITLE
Proper way of stopping a thread

### ISSUE THREAD

**Issue by darthzeran** [nodejs/help#2461]
* **Node.js Version**: 12.14.1
* **OS**: Win10
* **Scope (install, code, runtime, meta, other?)**: runtime/code

I have worker threads running in my node application to do calculations in the background as not to stop all incoming requests.

However, today I got this error
`Error: Worker stopped with exit code 1`
And I do not know why the error occurred.  But my real question is if I am killing the thread the correct way or not.

My thread code is mostly copied from Node docs
```
	const worker = new Worker(__filename, {
			workerData: data,
		})
		worker.on('message', result=> {
			worker.terminate()
			resolve(result)
		})
		worker.on('error', reject)
		worker.on('exit', code => {
			if (code !== 0) reject(new Error(`Worker stopped with exit code ${code}`))
		})
```

Is calling terminate to stop the process before resolve causing my error?
If so , what is the best way to end the process?

**Comment by addaleax** [comment]
@darthzeran Wthout knowing more about your code, it’s hard to tell, but at least to some degree everything seems to be working as expected – when you get a message, you call `.terminate()`, which in turn makes the Worker exit with exit code 1.

It’s odd that the `resolve()` doesn’t seem to be taking effect here, but again, that’s hard to investigate without more context.

**Comment by darthzeran** [comment]
do I need to kill my worker?
Or does it resolve itself?

What would be the most correct way in ending a process?

All the worker is doing is calculating some numbers, and returning an object full of results.

**Comment by addaleax** [comment]
@darthzeran All of these questions depend on your application, so it’s hard to give an answer without knowing the code.

> All the worker is doing is calculating some numbers, and returning an object full of results.

That makes it most likely that you’d want to let the Worker end by clearing the event loop (since there shouldn’t be anything on it).

**Comment by PoojaDurgad** [comment]
ping , @darthzeran - is this still outstanding?

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to reopen the issue if that is not the case

**Comment by darthzeran** [comment]
Yah, the originally idea we had to use threads had to be scrapped, and since it was a year ago, i do not remember more what my specific questions were, sorry, but thank you @addaleax for helping
