### ISSUE TITLE
How to highlight numbers with util.inspect

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2462]
I am on MacOS with Node.js version v12.14.1

I have this code:

```js
const util = require('util');

console.log(util.inspect({
    "foo": "bar",
    "star": true,
    bar: 'car',
    boop: 555
}, {colors: true, depth: 5, breakLength: 30}));
```

I was under the assumption that numbers were highlighted in red or blue, but they are hightlighted with yellow, just like booleans, seems weird that strings, bools, and numbers aren't all unique colors.

see this screenshot:

<kbd>
<img width="225" alt="Screen Shot 2020-02-07 at 11 31 26 AM" src="https://user-images.githubusercontent.com/11139560/74059712-69168c80-499d-11ea-9768-0fe4d4330337.png">
</kbd>

**Comment by PoojaDurgad** [comment]
@ORESoftware - with this documentation https://nodejs.org/dist/latest-v12.x/docs/api/util.html#util_util_inspect_object_showhidden_depth_colors the default associated color for the type number is yellow and in powershell also color looks same no changes in it.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
