### ISSUE TITLE
--experimental-modules ReferenceError of inheriting classes

### ISSUE THREAD

**Issue by josephnormandev** [nodejs/help#2464]
* **Version: 12.15.0**:
* **OS: Ubuntu 19.10**:
* **Scope: Code**:

So I'm trying to have some inheritance, one called Player and another called GamePlayer, which will be a subclass of the Player class. I'm using the flag --experimental-modules to use the import/export stuff. However, I get this error when trying to start up the project:
```
joseph@InsaneMachine:~/placeholder2/main-server$ npm start

> main-server@1.0.0 start /home/joseph/placeholder2/main-server
> nodemon --experimental-modules src/index.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --experimental-modules src/index.js`
(node:7620) ExperimentalWarning: The ESM module loader is experimental.
file:///home/joseph/placeholder2/main-server/src/games/game-player.js:3
export default class GamePlayer extends Player
                                        ^

ReferenceError: Cannot access 'Player' before initialization
    at file:///home/joseph/placeholder2/main-server/src/games/game-player.js:3:41
    at ModuleJob.run (internal/modules/esm/module_job.js:109:37)
    at async Loader.import (internal/modules/esm/loader.js:132:24)
[nodemon] app crashed - waiting for file changes before starting...
```

Here is Player, the parent class:
```js
import ...;

export default class Player
{
    constructor(object)
    {
        ...
    }
    ...
}
```

And GamePlayer, the child class:
```js
import Player from '../players/player.js';

export default class GamePlayer extends Player
{
    constructor(token, player)
    {
        super(player);
    }
}
```

And here is the file structure:
src/
----games/
--------game-player.js
----players/
--------player.js

**Comment by Hakerh400** [comment]
`.js` files cannot be loaded as ESM modules unless `"type": "module"` is specified in `package.json` (which I guess you have set correctly, since you got `ReferenceError` instead of `SyntaxError`).

Can you share the entire project (including `package.json` and all relevant files)? What you have currently posted is not enough to determine what the problem is.

**Comment by josephnormandev** [comment]
https://github.com/josephnormandev/placeholder2.0

It's a pretty big project, but here

**Comment by josephnormandev** [comment]
Since this is a lot to look through and it'd take a long time to sift through, what do you know this error generally indicates?

**Comment by josephnormandev** [comment]
Something funny, there's another child class for Player called OnlinePlayer that extends the same but doesn't throw the error:
```js
import Player from '../players/player.js';

export default class OnlinePlayer extends Player
{
    constructor(player, socket)
    {
        super(player);

        this.socket = socket;
    }

    send(message)
    {
        this.socket.send(JSON.stringify(message));
    }

    kick()
    {
        this.socket.close();
    }
}
```

**Comment by josephnormandev** [comment]
Also, is this a problem that would be solved by going back to commonjs? Is the --experimental-modules flag fully hashed out or would things be normal with the old way of things

**Comment by Hakerh400** [comment]
The problem is that you have a circular  dependency. In `player.js` you are importing `players.service.js`, but in `players.service.js` you are trying to import `player.js`. It results in class `Player` not being initialized when you try to define `GamePlayer`.

Simplified version of that would be:

```js
// A.js
import B from './B.js'
export default class A{}
```

```js
// B.js
import A from './A.js'
export default class B extends A{}
```

**Comment by josephnormandev** [comment]
@Hakerh400 
Thanks so much for helping me with this issue. I've since done a bit of refactoring and fixed all of those circular dependencies. I appreciate it!
