### ISSUE TITLE
How of set the chunk's size of subprocess.stdout?

### ISSUE THREAD

**Issue by TKONIY** [nodejs/help#2467]
* **Node.js Version**: 8.10.0
* **OS**: ubuntu18.04LTS
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: child_process

I use `child_process` module to run a python script, from which I want to get the stdout immediately. However, I found that the callback function in `subprocess.stdout.on("data", (chunk)=>{})`will not be triggered untill the chunk reach a certain size. This size is too big for me,
```js
subprocess.stdout.on("data",(chunk)=>{
    console.log(chunck.toString());
})
```
By reviewing the docs, I found that this size of a stream can be set with the `HighWaterMark` option when it was created, but didn't found in which way that of child process's stdout stream can be set. 
 
How can I set this chunk size?  Thank you and I'll wait for your reply.

**Comment by Hakerh400** [comment]
> I found that the callback function in `subprocess.stdout.on("data", (chunk)=>{})` will not be triggered untill the chunk reach a certain size

That is not true in general. Here is a counterexample:

```js
const cp = require('child_process');
const proc = cp.spawn(process.execPath, ['-e', 'console.log(123);for(;;);']);

proc.stdout.once('data', buf => {
  console.log(buf.toString()); // Prints immediately
  proc.kill();
});
```

> How can I set this chunk size?

You cannot. See https://github.com/nodejs/help/issues/1688#issuecomment-449671775 for details. The Python interpreter is the one who buffers the data, not Node.js. Basically, Node.js can do nothing to prevent Python from buffering output data.

If you can modify your python code, then add whatever needs to be added to tell python interpreter to flush data. If you cannot modify python code, you can use [Unbuffer](https://linux.die.net/man/1/unbuffer) (on Linux), or [WinPTY](https://github.com/rprichard/winpty) (on Windows) to artificially unbuffer the data.

**Comment by TKONIY** [comment]
Thanks a lot !

**Comment by PoojaDurgad** [comment]
@TKONIY - is this issue resolved? looks like this issue can be closed now. please let me know if that is not the case.

**Comment by TKONIY** [comment]
Yes it is. I forgot. Thanks a lot.
