### ISSUE TITLE
Get full version of coverage data with v8

### ISSUE THREAD

**Issue by jehy** [nodejs/help#2468]
* **Node.js Version**: 12, 13
* **OS**: Ubuntu 18
* **Scope (install, code, runtime, meta, other?)**: V8 coverage
* **Module (and version) (if relevant)**:

I'm trying to make a tool for getting V8 coverage from node process during runtime using `Profiler.startPreciseCoverage` and other relevant commands.
The only issue I have is regarding modules loading.

If you start coverage *before* loading modules, then you have a full coverage which includes all non covered code.
But if you start coverage *after* module load and first call, you only get partial coverage for this call, and you can't make a full report basing on it. But I want to make a runtime coverage, and most modules would be already loaded and called...

Here is a minimal example of problem: https://github.com/jehy/node-v8-coverage-wtf/blob/master/index.js

How can I solve it? For example, may be there is a way to get "empty" coverage report which includes all blocks and marks them as uncovered? Then I could just write covered blocks on top of it and everything would be fine.

**Comment by gireeshpunathil** [comment]
@nodejs/v8
