### ISSUE TITLE
Can't install Node for MacOS

### ISSUE THREAD

**Issue by evan-k-wright** [nodejs/help#2469]
* 12.16.0
* macOS Catalina 10.15.3:
* Install:

I am not able to install node from the node package downloaded from the website

<img width="483" alt="Screen Shot 2020-02-13 at 5 16 38 PM" src="https://user-images.githubusercontent.com/35173538/74490215-0a617f00-4e85-11ea-9387-7cbf75dbac99.png">

**Comment by nschonni** [comment]
This one is being tracked over on https://github.com/nodejs/node/issues/29216

**Comment by PoojaDurgad** [comment]
@evan-k-wright - is this still outstanding ? 
for me with your issue ,looks similar to https://github.com/nodejs/help/issues/2243 hopefully this may help you to resolve the issue.

**Comment by PoojaDurgad** [comment]
inactive . closing!! feel free to re-open if it is needed.
