### ISSUE TITLE
How to install ```Node.js

### ISSUE THREAD

**Issue by Mariaed74** [nodejs/help#2472]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)
```
-->

**Comment by mStirner** [comment]
For simple and quick version specific installations i use: https://github.com/nodesource/distributions
The offical way is documented here: https://nodejs.org/en/download/
Depending on your OS  you can install it via your packet manager, eg. `apt`: `apt install nodejs`

**Comment by PoojaDurgad** [comment]
@Mariaed74 - is this issue resolved? any updates?

**Comment by PoojaDurgad** [comment]
closing as resolved. please feel free to reopen the issue if that is not the case.
