### ISSUE TITLE
(Transform) streams, promises and error handling

### ISSUE THREAD

**Issue by fbiville** [nodejs/help#2477]
* **Node.js Version**: 10.18.1, 12.14.1, 13.6.0
* **OS**: Mac OS 10.15.3
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: streams

I need to provide a [`map`-like operation](https://rxjs-dev.firebaseapp.com/api/operators/map) on Node streams.

The map function can be synchronous or asynchronous, hence the use of Promises in the following implementation:

```js
const {Transform} = require('stream');

module.exports = class MapTransform extends Transform {

    constructor(fn, options = {}) {
        super(options);
        this._function = fn;
    }

    _transform(chunk, _, callback) {
        Promise.resolve(chunk)
            .then(value => this._function(value))
            .then(
                result => callback(null, result),
                err => callback(err));
    }
};
```

This works all fine until an error occurs.
Indeed, when such a thing happens, `callback(err)` throws and leaves the whole promise rejected, leading to a `UnhandledPromiseRejectionWarning`.

You can see that for yourself by executing the following:

```shell script
 $ cd $(mktemp -d) && git clone https://github.com/fbiville/stream-map && cd stream-map && node example.js
Send an integer, Ctrl-C to stop
// and send 0 to see an example of rejection
```

I could surround `callback(err)` with a try-catch block and ignore the error, but that does not seem right. Is there a better way to avoid the promise rejection warning?

**Comment by Hakerh400** [comment]
Try this:

```js
Promise.resolve(chunk)
  .then(value => this._function(value))
  .then(
    result => callback(null, result),
    err => callback(err))
  .catch(err => process.nextTick(() => { throw err; }));
```

**Comment by fbiville** [comment]
Thanks @Hakerh400!
After reading https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#process-nexttick, I understand that doing as you suggest will allow the promise to run to completion before the error is thrown, is that correct?
