### ISSUE TITLE
Installer could not be open

### ISSUE THREAD

**Issue by Sharma-Shivam** [nodejs/help#248]
I have downloaded nodejs installer...
https://nodejs.org/dist/v4.4.7/node-v4.4.7-x64.msi
But it could not be openend.
![image](https://cloud.githubusercontent.com/assets/15942322/17561652/b82c817c-5f44-11e6-8899-08c6cc03edca.png)

**Comment by addaleax** [comment]
Just to be sure, are you running a 64-bit system?
