### ISSUE TITLE
Small changes on objects doesn't fire the proxy...

### ISSUE THREAD

**Issue by mnini** [nodejs/help#2480]
```
// This with complete pathes
var foo = {}
var fo = new Proxy(foo, {
    set: function(obj, prop, newval) {
        console.log('Set hit...')
        console.log(prop, newval)
        obj[prop] = newval
    }
})
console.log('Value set lvl2')
fo.bar = {
    baz: {
        bark: true
    }
}
console.log('Value set lvl3')
fo.bar.baz.bark = false
console.log(fo.bar.baz.bark)
```

Current state is:
```
Value set lvl2
Set hit...
bar { baz: { bark: true } }
Value set lvl3
false
```

Which is somehow... Do I have to create new object, just purely out of proxies? If variable over there is not objects, it's not possible to proxy it down.

Solution:`prop: [objNested0, objNested1]`
If property is deep, array that separates object is returned as property, then there is full programmatic control around subtle deep changes.

Actually every call accessed trough proxy should be catched by it.

**Comment by bnoordhuis** [comment]
Moving to nodejs/help because this is working as per spec. I recommend you consult MDN or the ECMA spec on how proxies work.

**Comment by gireeshpunathil** [comment]
@mnini - is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
