### ISSUE TITLE
cant run node.js on mac plz help 

### ISSUE THREAD

**Issue by ItsACodeWorld** [nodejs/help#2481]
i installed the latest node.js straight from their homepage and followed all the instruction but when i open terminal to check the build number with the command "node -v". i get Illegal instruction: 4 . when i check the npm -v i get segmentation fault:11. ive already installed and uninstalled like 5 times and tried 3 different node builds and still i get the same results. im on a mac thats running osx lion 10.7.5 and im using sublime as my editor. pleaae help me , ive been trying to figure this out the past 4 days and im getting super fustrated lol.

**Comment by gireeshpunathil** [comment]
@ItsACodeWorld -  could you try after setting this:
`$ ulimit -c unilmited`

so that it produces a core dump?

and then you can launch the dump in a debugger and collect the stack trace:

```
$ lldb <path-to-node> <path-to-core>
(lld) bt
```

**Comment by gireeshpunathil** [comment]
bye default core files go to `/cores/` in mac

**Comment by ItsACodeWorld** [comment]
hey thank you so much for taking the time out the day to help me out, thanks again.

 now when i used those command i got a syntax error near unexpected token '<'. i tried to check the node version

**Comment by gireeshpunathil** [comment]
ok, `<path-to-node>` and `<path-to-core>` are placeholders that you need to replace with the actual file names! for example, `lldb /usr/local/bin/node /cores/core.34234`; not to be used as-is.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
