### ISSUE TITLE
"Cannot find module 'worker_threads'" using sudo

### ISSUE THREAD

**Issue by SuperstrongBE** [nodejs/help#2482]
* **Node.js Version**:
13.9.0
* **OS**:
Rapsbian / Linux 9
* **Scope (install, code, runtime, meta, other?)**:
runtime
`{ Worker,SHARE_ENV } = require('worker_threads')`

These lines result an "Cannot find module 'worker_threads'" using sudo when running the main thread (sudo node dist/app/app.js). Same without sudo result no error, but sudo is required because i'm using the rpi-ws281-native lib.

I've found no information about this issue anywhere. Please some one have information about resolution ?

**Comment by addaleax** [comment]
Comparing the output of 

1. `sudo node --version` and `node --version` and
2. `sudo which node` and `which node` 

is very likely helpful here, as the most probable cause is that a different Node.js binary is being executed when run under sudo.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
