### ISSUE TITLE
Are symbolic links for both Linux installs and AIX installs?

### ISSUE THREAD

**Issue by MikeyBeez** [nodejs/help#2486]
Are symbolic links at the end of the installation instructions for both Linux installs and AIX installs?  The Installation Doc doesn't make that clear.   

sudo ln -s /usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin/npx /usr/bin/npx

**Comment by gireeshpunathil** [comment]
@MikeyBeez - 
 
> Are symbolic links at the end of the installation instructions for both Linux installs and AIX installs?

sorry, did not follow you. Did you mean to ask:
     - are those links same, or
     - are the executable `npx` a symbolic link
?
 - which installer you are using to install in those platforms?

**Comment by MikeyBeez** [comment]
There's a section for Linux and then a section for AIX.  Finally there's a section for creating links.  Is that link section just for the AIX installation or for both.

**Comment by gireeshpunathil** [comment]
thanks, now I follow you, and agree! 
 - pinging @sam-github - who seem to have developed that instruction, to double check.
 - feel free to raise a PR to disambiguate it
 - or else np, let me know, I will try to fix it

**Comment by sam-github** [comment]
wiki's don't use PRs (for better and worse, depending on the moment), I updated the text, is it more clear now @MikeyBeez ?

**Comment by MikeyBeez** [comment]
@sam-github Yes, thank you.  Now I see that if I'd thought about this more, I could have understood it.

**Comment by sam-github** [comment]
Probably, but it shouldn't take that much thought to follow the docs!  ;-).
