### ISSUE TITLE
Behavior of Promise.all with Promises that resolve a Stream

### ISSUE THREAD

**Issue by nanokina** [nodejs/help#2487]
* **Node.js Version**: 13.9.0
* **OS**: Windows 10 x64
* **Scope (install, code, runtime, meta, other?)**: code (i guess)
* **Module (and version) (if relevant)**: `http` `stream` (or possibly `joepie91/node-combined-stream2`)

### abstract sample code

```js
/** @returns {Promise<Readable[]>} */
function getStreamsOfHugeData() {
  const promiseA = getDataStreamFromHttp();
  const promiseB = getDataStreamFromFile();
  const promiseC = getDataStreamFromSomewhereElseWhichIsAlsoFailable();
  return Promise.all([promiseA, promiseB, promiseC]);
}

async function main() {
  let streams;
  try {
    streams = await getStreamsOfHugeData();
  } catch(err) {
    // we know since we used `Promise.all` 
    // this `err` is from one of the promises that was failed.
    // But what if one of the other promises is already finished successful?
    // Assume that `getDataStream...();` returns a promise
    // resolving a manually piped stream (still fulfills stream.Readable) .
    console.log('Sorry, no idea what to do here...');
    return -1; // <- (Edited) the actuall app never ends here
  }
  // code goes with the streams...
}
```

### actual code
https://github.com/Ebycow/hanako/blob/0.2/adapters/audioadapter.js#L79-L80

## Question

Using `Promise.all` with promises that resolve a readable stream (stream.Readable),
is it safe for leaving the resource management to node, 
or do I have to do a little hack and manually destroy already resolved streams in the case which `Promise.all` rejects because at least one of the underlying promise rejected?

Thanks in advance for your helps 😄

**Comment by bnoordhuis** [comment]
You have to clean up manually, if I understand your question correctly. There's no way for node to know the stream isn't going to be used. [`Promise.p.finally`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) might come in handy.

**Comment by nanokina** [comment]
@bnoordhuis Oh, then I'm gonna clean them up in one way or another. Thanks for the advice!

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
