### ISSUE TITLE
Read-only file with fs.createWriteStream

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2489]
Is there a way to create a read-only file with `fs.createWriteStream` after the last bit is written or do I have to call `chmod` after the fact?

**Comment by gireeshpunathil** [comment]
@ORESoftware - what is the use case for it? while the stream is flowing, the destination has to be writable right? if the destination has to be read-only, it has to be after the last bit is written (as you already said), in which case the stream's life cycle has ended. So I would see this has detached from stream's scope, and so yes, doing `chmod` after the write looks like the most reasonable thing to me!

**Comment by gireeshpunathil** [comment]
closing, pls reopen if you still have issue
