### ISSUE TITLE
fs.chmodSync deletes my file contents

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2490]
I have this:

```js
const s = fs.createWriteStream('/home/oleg/codes/channelmeter/js-common/types.ts');

s.write('foo');

process.once('exit', code => {
  fs.chmodSync(f, fs.constants.O_RDONLY);
  console.log('Exiting with code:', code);
});
```

if I don't include the fs.chmodSync call then my 'foo' data is there, what's up with that?

**Comment by ORESoftware** [comment]
this seems like a bug because this works:

```js
process.once('exit', code => {
  // fs.chmodSync(f, fs.constants.O_RDONLY);  // this deletes my file content
  cp.execSync(`chmod 444 ${f}`);    // this works
  console.log('Exiting with code:', code);
});
```

**Comment by addaleax** [comment]
@ORESoftware It’s hard to tell what’s going on without having more information, but: `fs.constants.O_RDONLY` is not a file mode. You want to pass `0o444` instead. Using `fs.constants.O_RDONLY` won’t make your file disappear, but depending on your operating system it might make the file inaccessible to you (e.g. by removing read permissions along with write and execute permissions).

**Comment by gireeshpunathil** [comment]
@ORESoftware - is it still an issue?

**Comment by ORESoftware** [comment]
ah yeah, can close, thx
