### ISSUE TITLE
Is Node.js installation package allow for commercial use?

### ISSUE THREAD

**Issue by Erin452** [nodejs/help#2492]
Actually we want to include Node.js installation package into our installation package, and use silent install to install it before install our product.

**Comment by mhdawson** [comment]
I think you'd have to look at the LICENCE file which is shipped in the binaries to figure out if your specific use case is acceptable or not and if so what you need to do.

**Comment by Erin452** [comment]
@mhdawson 
Thinks, I'll check the LICENCE.
