### ISSUE TITLE
nodejs without request/response

### ISSUE THREAD

**Issue by mariomuja** [nodejs/help#2497]
The code below is provided on the nodejs home page as a quickstart for beginners. It handles a client request and generates a response.

How can I create an application with node that does NOT listen for client requests and also does NOT create a response?

We want to create applications that handle processing of files. We want to use MS Azure Service Bus to publish processing messages, when new files are created. For example, if a ZIP file is created in a specific folder, the file shall be unzipped to another folder. For this application, we do not need a request nor a response. The application recognizes itself that there is a new file, extracts it and be silent again.

I found no way with nodejs to omit the definition of a port where the application is listening for requests as you can see in the code below. Such requests do not exist in our application model and therefore, our applications do not need to "listen" for something that they will never handle. Hope, I could make it clear what we are searching for. 

----
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});

**Comment by ORESoftware** [comment]
Try Unix domain sockets and listen on a local file.

```
const net = require('net');
const f = path.resolve(process.cwd() + '/x.sock'))

const s = net.createServer(f, ()=>console.log('listening'))

s.listen();
```

look at the 'net' package

**Comment by gireeshpunathil** [comment]
or even better, how about [file watcher](https://nodejs.org/dist/latest-v13.x/docs/api/fs.html#fs_fs_watch_filename_options_listener)?

**Comment by mariomuja** [comment]
watching for files was just an example; my question was about how to avoid listening for requests if I don't need that; 

many thanks to ORE for making it clear that launching a server and listening to a port is not something that must ultimately exist in every node app

**Comment by gireeshpunathil** [comment]
@mariomuja -

> my question was about how to avoid listening for requests if I don't need that;

unless I am missing something here, it is as simple as not using those example snippets where you don't need those?

the most common use case of node.js is webapps, and hence most examples showing that.  But node.js is [Turning complete](https://en.wikipedia.org/wiki/Turing_completeness) which means it has semantics and APIs to cover the full data-manipulation spectrum defined by the said specification.

**Comment by gireeshpunathil** [comment]
pls let me know if it helps, or if things are more deviating / complicating. If so, please illustrate with a concrete example of your requirement.

**Comment by ORESoftware** [comment]
@mariomuja a nodejs program can do pretty much anything you want, it doesn't have to be a server

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
