### ISSUE TITLE
evented listener for linux for fs.watchFile

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2499]
I am wondering if there is an evented API for watching files:

https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener

looks like it uses polling on Linux?

**Comment by ORESoftware** [comment]
looks like `fs.watch` is evented, but `fs.watchFile` is not?

**Comment by bnoordhuis** [comment]
Correct.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
