### ISSUE TITLE
Installing Node on Armv5tel Linux

### ISSUE THREAD

**Issue by QuinDennis** [nodejs/help#250]
I use node a lot (Ubuntu,Windows..), but now have a project on Linux storm 2.6.33 armv5tel GNU/Linux.  I've tried numerous sources, compiling, binaries,... and just can't make it work.  I would appreciate some guidance.

Thanks

**Comment by addaleax** [comment]
Hm, maybe see https://github.com/nodejs/node/issues/8015? tl;dr: That might not be possible at all, unfortunately…

**Comment by QuinDennis** [comment]
Thanks!  This is an Arm5, doesn't seem to be supported anymore, I'm intent
on getting a more up to date piece of hardware.
On Aug 12, 2016 9:03 PM, "kelvin knighton" <notifications@github.com> wrote:

I hope these links help:

[image: screen shot 2016-08-12 at 6 57 39 pm]
<https://cloud.githubusercontent.com/assets/1773260/17640854/b4d1eb72-60be-11e6-8322-c8eff47dadbe.png>

links:

http://superuser.com/questions/739387/installing-nodejs-on-a-low-power-arm-
device
&
nodejs/node-v0.x-archive#6158
<https://github.com/nodejs/node-v0.x-archive/issues/6158>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nodejs/help/issues/250#issuecomment-239595740>, or mute
the thread

**Comment by lordKnighton** [comment]
last resort is: You could use an online IDE until better hardware falls into your lap. ( i.e. ) c9.io & nitrous.io 

====

Anyway close this issue :) or keep the conversation going if you feel we could still help you.
