### ISSUE TITLE
Bluetooth desn't work

### ISSUE THREAD

**Issue by MathiasJZ** [nodejs/help#2501]
I use Raspberry PI4 with the lastest Raspian,
IObroker and all adapters there are the lastest
But at the adapters ble and radar2 bluetooth doesn't work with node/nodejs 12.x 

Greetings,
Mathias

**Comment by gireeshpunathil** [comment]
@MathiasJZ  - is this still an issue? if so, can you elaborate your problem? which Node.js API you are using? what you expect, and what you observe?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
