### ISSUE TITLE
Looking for guidance on proxying a server using Node.js

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2502]
I am on Node.js 12/13

I put the question on StackOverflow - https://stackoverflow.com/questions/60473707/how-to-properly-proxy-a-server-using-node-js

**Comment by PoojaDurgad** [comment]
@ORESoftware - If I'm not wrong , looks like this issue was removed from stackoverflow. Can you elaborate the issue please? so that it will be helpful to debug your issue.

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
