### ISSUE TITLE
how ftp、ldap、... over http server, by bind one port

### ISSUE THREAD

**Issue by hktalent** [nodejs/help#2504]
how ftp、ldap、... over http server, by bind one port
under code not run:
```
function cbkFtp(conn)
{
    conn.on('data',function(s){
        console.log(s)
    });
}

cbkFtp(req.connection)

req.on('socket',function(s)
{
    s.on('socket',function(x){
        console.log(x)
    });
    
});
```

**Comment by gireeshpunathil** [comment]
@hktalent - is this still outstanding? if so, can you elaborate a little more on your requirement? as we know, multiple processes cannot bind to one port by design, so what you are trying to achieve?

**Comment by hktalent** [comment]
if I am hacker, now ,the server has other web server port 7001, how bind 7001 for my hacker web server @gireeshpunathil

**Comment by gireeshpunathil** [comment]
still not very clear on the requirement. However, if you want to overload one port for multiple protocols, you can use a socket multiplexer, with TCP as the vehicle. That is,
 - open a socket and listen at X
 -  publish port X for all your purposes
 - when the connection arrives, parse the header and figure out which protocol it has
 - implement different handlers that understand the specific protocol
 - collect the response from the handler, fully wrapped in the protocol
 - send it through the TCP socket.
 
Hope this helps?

**Comment by hktalent** [comment]
ok,i know, thanks @gireeshpunathil
