### ISSUE TITLE
node-v12.16.1.pkg” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by jesuasir007** [nodejs/help#2505]
node-v12.16.1.pkg” can’t be opened because Apple cannot check it for malicious software.

now I have change the then click privacy and security settings
select allow Appstore downloads to installation working fine.
not select allow App Store and identifier

**Comment by borislavski** [comment]
the same, please help

**Comment by tiffanydenny** [comment]
Same here.

**Comment by gireeshpunathil** [comment]
unable to recreate. with default settings itself, the popup is appearing for me. 

@nodejs/releasers - anything changed recently, or any advise here?

**Comment by richardlau** [comment]
See https://github.com/nodejs/node/issues/29216. Work is going on under https://github.com/nodejs/node/pull/31459.

**Comment by gireeshpunathil** [comment]
ok, thanks explains (I tested in mohave). @jesuasir007 , @borislavski , @tiffanydenny - are you on catalina?

**Comment by borislavski** [comment]
yep, catalina

**Comment by jesuasir007** [comment]
yes , catalina

**Comment by tiffanydenny** [comment]
Yes to Catalina

**Comment by egall18** [comment]
This helped me fix it for mac:
-Download the package
1. Right click the pkg.
2. Click Open With / Installer.
3. You'll get the error described above. Dismiss it.
4. Go to System Preferences / Security & Privacy.
   On the bottom of the General tab you'll see something like "Allow apps downloaded from" and then below that something like "Node tried to install earlier but it wasn't a recognized, install anyway?" Click Allow / Yes

**Comment by jesuasir007** [comment]
Thank you .

**Comment by aweissman11** [comment]
Thank you @egall18

**Comment by fmabid** [comment]
@egall18 Thanks man

**Comment by LaptopTheOne** [comment]
Thx :)
Every MacOs update adds additional step for allowing unrecognised apps to run....pfff

**Comment by PoojaDurgad** [comment]
@jesuasir007 - looks like this issue can be closed now .please let me know if that is not the case.
