### ISSUE TITLE
'binary' buffer and raw bytes on file are different

### ISSUE THREAD

**Issue by Yang-z** [nodejs/help#2507]
Hi,
'binary' buffer content is modified when it is saved to a file.

```js
const fs = require('fs');
var arr = [129,165,181,174];  // 0x[81 a5 b5 ae]
var buff = Buffer.from(arr);  // ✔️ Buffer(4) [129, 165, 181, 174] it is 'binary'
fs.writeFileSync(`.test/out_buff`, buff);   // ⚠️ 0x[d0 91 d0 b5 e2 95 a1 d0 be] on file
var buff_r = fs.readFileSync(`.test/out_buff`);  // ✔️ Buffer(4) [129, 165, 181, 174]
```

So, it can be seen that the content of the out put file is encoded by some kind of method, similar to 'utf8' but not. And if we read the file, 'fs' gives a buff with the exactly original bytes.
It shows that 'binary' and raw bytes on file are different.
Is there a way to obtain the raw bytes on file, although the 'binary' buffer is the raw content we need?

(And after I test other soft ware to write `0x[81 a5 b5 ae]` to a file, it is just not possible, when I save the file, it turn out to be `0x[d0 91 d0 b5 e2 95 a1 d0 be]` automatically. So it is not a nodejs behavior, it is an operation system behavior. What's it?)

**Comment by addaleax** [comment]
What do you use to inspect the file contents? I’m pretty sure the actual file contains the right bytes, the one you have written using `fs.writeFileSync()`, but whatever you’re using to read the file messes this up?

**Comment by Yang-z** [comment]
> What do you use to inspect the file contents? I’m pretty sure the actual file contains the right bytes, the one you have written using `fs.writeFileSync()`, but whatever you’re using to read the file messes this up?

Oh, I use Notepad++ (x86) with the plug-in of HEX-Editor.
Is the tool messes this up?

**Comment by addaleax** [comment]
@Yang-z It probably is, yes – Googling a bit shows issues like https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3697, which sound **very** similar to what you’re experiencing. I’m assuming that this is a bug in the hex editor plugin.

**Comment by Yang-z** [comment]
Thanks mate, it's really where things go wrong. 
`Notepad++` modifies the content by `Autodetect character encoding` for displaying, and the `HEX-Editor` plug-in is fed by the modifies content rather than the original bytes from file.
The solution should be:
`preferences >> MISC >> disable the Autodetect character encoding`
Now, everything is reasonable:)

**Comment by addaleax** [comment]
Okay, great to hear that that worked out for you :)
