### ISSUE TITLE
How to write the response of other events back to the corresponding socket? This seems to do a lot of things for node, but Java is very easy

### ISSUE THREAD

**Issue by mmm8955405** [nodejs/help#2509]
```
var ws = new WebSocket('ws://test.com');
ws.on('date', function open(date) {
      console.log(date);
      //How to write something into net socket here??
      //............
});
```
```
const server = net.createServer((socket) => {
          socket.on('data', (data) => {
              console.log(socket);
              ws.send('aaaaa');
          });
}).listen(9999, () => {
        console.log(server.address());
});

```
Like the above situation, how to write the data of websocket response back to the socket? Or other events need to be written back to the corresponding socket? How to do it correctly?

**Comment by gireeshpunathil** [comment]
@mmm8955405 - is this still an issue?

the websocket in the web socket block and the socket in the net socket block have different life time - for example, every time a new client connects, the `net` block will be invoked with new socket object. So retaining the variables across blocks (net socket object in ws block and vice versa) is not a good idea. At the same time, if that is what is desired for the use case, you could define a socket variable globally, like you did for `ws`, and assign the new sockets to the global variable, and then use that in the `ws` block. But tbh, the code cannot be more ugly!

May be, you can explain your scenario with the help of any Java snippet, so I understand it a little better?

**Comment by PoojaDurgad** [comment]
@mmm8955405 - is this still outstanding? did @gireeshpunathil 's suggestion help you to get rid of this issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to re-open if that is not the case.
