### ISSUE TITLE
Memory Issues with Node 10

### ISSUE THREAD

**Issue by nimit95** [nodejs/help#2512]
* **10.16.0**:
* **CentOS**:
* **4 Gb memory**:
My memory Usage looks like this before usage -->
{"rss":33607680,"heapTotal":16498688,"heapUsed":12249688,"external":104174}

My memory Usage looks like this after usage --> {"rss":3519221760,"heapTotal":194232320,"heapUsed":183946368,"external":4255851993}}

High external memory usage. GC trigger is not helping. How to debug what is taking the external memory. Heap snapshots(Chrome) are only giving heap space used.

The memory graph is:- 
<img width="702" alt="Screenshot 2020-02-29 at 12 09 17 PM" src="https://user-images.githubusercontent.com/14093420/75957987-46668d80-5ee1-11ea-8b30-842ee026cf94.png">

Can't figure out the reason. How to monitor the External memory and figure out the leak? Any help or leads

**Comment by mhdawson** [comment]
My suggestion would be to try to use valgrind as outlined here: https://github.com/nodejs/node/blob/master/doc/guides/investigating_native_memory_leak.md

It can give you information about native memory.

**Comment by mhdawson** [comment]
The other thing to note is that RSS will not necessarily go down just because there is free memory in the heap.

**Comment by nimit95** [comment]
I don't understand it, initially, node process was taking say 400 Mb of memory, then RSS started taking 3.5 GB of RAM. Is there a reason why it wouldn't give memory back to the OS? 
If an object in RSS(external) is taking that much space I should be able to see it somewhere.

**Comment by gireeshpunathil** [comment]
here is the explanation for the said `rss` behavior: https://github.com/nodejs/node/issues/21266#issuecomment-580655540

btw, looking at your data, looks like your heap has grown as well, so it may be that there are JS objects getting piled up in the heap?
```
{"rss":33607680,  "heapTotal":16498688, "heapUsed":12249688, "external":104174}
{"rss":3519221760,"heapTotal":194232320,"heapUsed":183946368,"external":4255851993}
```

**Comment by nimit95** [comment]
I agree heap has increased as well, that may be because I store some objects in the memory. Even still the heap memory increase like ~10x to 1.5 GB still manageable. But the external memory increase from 0.15 MB to 4.5 Gb(~50000x). That's is what for me is the low hanging fruit to fix first.

**Comment by nimit95** [comment]
I understood the point that RSS will be reserved with the process. But in my case, OOM killer is killing the process that means the process must be asking for more memory. Will try Valgrind to figure out what is causing memory issues.

**Comment by gireeshpunathil** [comment]
@nimit95 - 

> that may be because I store some objects in the memory.

do you have any insights into what type of objects are going there? I am asking this because, the `external` memory typically contain backend C++ objects that provide low level capability to the JS objects, so knowing what goes into JS heap will help us to know what to expect in `external`. Then using `valgrind` we could validate the theory.

**Comment by nimit95** [comment]
So basically heap objects have plain javascript objects, couple of arrays. What I suspect is happening is when I am writing large chunks into WebSockets, both heap and external memory increase.

**Comment by gireeshpunathil** [comment]
@nimit95 - 

> But I am not able to prove or disprove this theory.

your theory may be correct. Let us look at the `valgrind` report, which may give more conclusive hints.

**Comment by gireeshpunathil** [comment]
@nimit95 - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
