### ISSUE TITLE
Cannot find module './_contains'

### ISSUE THREAD

**Issue by Arthur-xu** [nodejs/help#2514]
* **Node.js Version**:v10.19.0
* **OS**: linux
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: internal/modules/cjs/loader.js:638

internal/modules/cjs/loader.js:638
--
  | throw err;
  | ^
  |  
  | Error: Cannot find module './_contains'

**Comment by shellberg** [comment]
What are you trying to install?  Is this Rambda (or Lodash) perhaps?

**Comment by Arthur-xu** [comment]
> What are you trying to install? Is this Ramda (or Lodash) perhaps?

Use serverless to deploy cloud function.

**Comment by jwoldan** [comment]
We saw a similar error due to a caching issue in CircleCI- for us, clearing the cache resolved it.

**Comment by Arthur-xu** [comment]
Solved this issue by another way. Maybe helpful for others:
Seems it caused by serverless. so i used fixed version serverless@1.64.0.

**Comment by Arthur-xu** [comment]
> We saw a similar error due to a caching issue in CircleCI- for us, clearing the cache resolved it.

Thanks. haha, i tried to clean cache. it doesn't work for me.
