### ISSUE TITLE
i was using VSC to make my discord bot and fucked up,now it wont run.

### ISSUE THREAD

**Issue by 4N63L-CAA** [nodejs/help#2516]
if you are willing to help out i am using Noide.js and Discord.js,if you want to help please contact my discord at Angel27#9658.

**Comment by gireeshpunathil** [comment]
@4N63L-CAA - is this still an issue? if so, pls explain your issue, and state what is expected and what is not working.

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
