### ISSUE TITLE
npm ERR! code MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by shockwave57yt** [nodejs/help#2518]
Several days ago I always have the same problem when I try to do **npm install discord.js**
![image](https://user-images.githubusercontent.com/47750020/76168077-331b2280-616c-11ea-9aa0-094bb425b139.png)

Can you help me pls?

**Comment by gireeshpunathil** [comment]
@shockwave57yt - is this still an issue? which OS version? can you pass the debug log that was produced?

**Comment by PoojaDurgad** [comment]
ping, @shockwave57yt

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to reopen the issue if its still outstanding!!
