### ISSUE TITLE
Send Message and Save to MongoDB problems

### ISSUE THREAD

**Issue by PaulTsai20160627** [nodejs/help#252]
Hi NodeJS:

There is one problem when I coding about the message saving to mongodB.

When I use the assert to compare err and null , there shows the following errors:

I do not know whether My code is wrong on server.on parts,

So, If there is any suggestable way to implement , please show !

esp8266@esp8266-VirtualBox:~/node-v6.3.1-linux-x86/node-prac/data_storage$ node data_storage_server.js 
server listening 127.0.0.1:8080
connected correctly to server

/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
AssertionError: null == true
    at /home/esp8266/node-v6.3.1-linux-x86/node-prac/data_storage/data_storage_server.js:59:2
    at /home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb/lib/collection.js:511:5
    at /home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb/lib/collection.js:694:5
    at handleCallback (/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb/lib/utils.js:96:12)
    at executeCommands (/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb/lib/bulk/ordered.js:405:12)
    at resultHandler (/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb/lib/bulk/ordered.js:433:5)
    at /home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:405:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Server and MongoDB Part Source
(data_storage_server.js)

``` javascript
// declare the variables object MongoClient and assert
var MongoClient = require('mongodb').MongoClient,assert = require('assert');
// Connection URL declartion
var url = 'mongodb://localhost:27017/paultsai';

// MongoClient connect to the Database
/*
MongoClient.connect(url,function(err,db){
    assert.equal(null,err);
    console.log("connected correctly to server");
/*
    insertDocuments(db,function(){
    db.close();
    });

}
*/
/*
// find document method implementation
var findDocuments = function(db, callback) {
  // Get the documents collection
  var collection = db.collection('documents');
  // Find some documents
  collection.find({}).toArray(function(err, docs) {
    assert.equal(err, null);
    console.log("Found the following records");
    console.dir(docs);
    callback(docs);
  });
}
// insert document method implementation
var insertDocuments = function(db, callback) {
  // Get the documents collection
  var collection = db.collection('documents');
  // Insert some documents
  collection.insert([{msg : 1}], function(err, result) {
    assert.equal(err, null);
    console.log("Inserted 1 documents into the document collection");
    callback(result);
  });
}
*/

// import datagram modules and create const object dgram
const dgram = require('dgram');
// create socket with udp ipv4 protocol 
const server = dgram.createSocket('udp4');
// show error messages when some thing errors.
server.on('error',(err)=>{
    console.log(`error: ${err.stack}`);
});
// when client bind with server, server response the msg got from client
server.on("message",(msg,rinfo)=>{
    MongoClient.connect(url,function(err,db){
    assert.equal(null,err);
    console.log("connected correctly to server");
    var collection = db.collection('documents');
        collection.insert({"msg": msg},function(err,doc){
    assert(null,err);
    console.log("data has been saved to MongoDB");
    //callback(doc);
    }); 
    });     
});
// listening the client of address localhost and port 8000
server.on('listening',()=>{
    var address = server.address();
    console.log(`server listening ${address.address}:${address.port}`)})
// bind a client 
server.bind({
    address: 'localhost',
    port:8080,
    exclusive: true
});
```

Clinet Part Source Code
(data_storage_client.js)

``` javascript
const dgram = require('dgram');
const message = Buffer.from('Hello Server ! I am Client ','utf8');
const client = dgram.createSocket('udp4');
client.send(message,8080,'localhost',(err)=>{
    client.close();
});
```

**Comment by danielkhan** [comment]
There are a few things I would change here but first of all, please do a `console.log(err)` to see if there's anything in there. 

I would stick to something like 

```js
if(err) throw err;
// or
if(err) return someCallback(err);
```

**Comment by PaulTsai20160627** [comment]
Hi danielkhan:

After adding the codes you mentioned above, and disable the previous assert.equal(err,null) codes, it does not show anymore about that "Assertion Error null==true" messages. But If I add this code assert(null,err), it will generate. I can not figure out because err was printed "null" , but assert shows error? 
![image](https://cloud.githubusercontent.com/assets/20158340/17875219/1a204900-6903-11e6-940d-1d22fa4dd78d.png)

data_storage_server.js source code

````javascript
// declare the variables object MongoClient and assert
var MongoClient = require('mongodb').MongoClient,assert = require('assert');
// Connection URL declartion
var url = 'mongodb://localhost:27017/paultsai';

// MongoClient connect to the Database
/*
MongoClient.connect(url,function(err,db){
	assert.equal(null,err);
	console.log("connected correctly to server");
/*
	insertDocuments(db,function(){
	db.close();
	});
	
}
*/
/*
// find document method implementation
var findDocuments = function(db, callback) {
  // Get the documents collection
  var collection = db.collection('documents');
  // Find some documents
  collection.find({}).toArray(function(err, docs) {
    assert.equal(err, null);
    console.log("Found the following records");
    console.dir(docs);
    callback(docs);
  });
}
// insert document method implementation
var insertDocuments = function(db, callback) {
  // Get the documents collection
  var collection = db.collection('documents');
  // Insert some documents
  collection.insert([{msg : 1}], function(err, result) {
    assert.equal(err, null);
    console.log("Inserted 1 documents into the document collection");
    callback(result);
  });
}
*/

// import datagram modules and create const object dgram
const dgram = require('dgram');
// create socket with udp ipv4 protocol 
const server = dgram.createSocket('udp4');
// show error messages when some thing errors.
server.on('error',(err)=>{
	console.log(`error: ${err.stack}`);
});
// when client bind with server, server response the msg got from client
server.on("message",(msg,rinfo)=>{
	MongoClient.connect(url,function(err,db){
	assert.equal(null,err);
	console.log("connected correctly to server");
	var collection = db.collection('documents');
        collection.insert({"msg": msg},function(err,doc){
        if(err) throw err;
	//assert(null,err);
        console.log(err);
	console.log("data has been saved to MongoDB");
 	//callback(doc);
	});	
	});		
});
// listening the client of address localhost and port 8000
server.on('listening',()=>{
	var address = server.address();
	console.log(`server listening ${address.address}:${address.port}`)})
// bind a client 
server.bind({
	address: 'localhost',
	port:8080,
	exclusive: true
});
````
data_storage_client.js source code
````javascript
const dgram = require('dgram');
const message = Buffer.from('Hello Server ! I am Client ','utf8');
const client = dgram.createSocket('udp4');
client.send(message,8080,'localhost',(err)=>{
	client.close();
});
````

**Comment by danielkhan** [comment]
Could you try `assert.ifError(err);`?
Asserting against `null`is risky as `err` may be anything not truthy (0, undefined, '', false, ...) if there was no error. That's why the `ifError()` assertion exists.

**Comment by PaulTsai20160627** [comment]
Hi Danielkhan:

The following test results shows below:
Modification of code block:
![inputs1](https://cloud.githubusercontent.com/assets/20158340/17966234/231c0c46-6af3-11e6-9838-4a5df5e7b83e.png)
Output result
![outputs1](https://cloud.githubusercontent.com/assets/20158340/17966244/300e4a0e-6af3-11e6-8661-46e01a3d5907.png)
There does not show any problems . But why,why add assert(null,err) will produce that message?

**Comment by danielkhan** [comment]
Got it. If you use `assert(v)` this defaults to `assert.ok()` and this just tests if `v` is truthy. The second parameter is the error message already. The error message you get is a bit misleading as it uses your `err` object which is null. See here https://github.com/nodejs/node/blob/master/lib/assert.js#L105.

What you want to use is `assert.equal(v)` or better `assert.ifError(err);` or simply `if(err) throw err` or if there is a callback you can use `if(err) return cb(err)`.
