### ISSUE TITLE
Which LTS version will include libuv 1.34.2 ?

### ISSUE THREAD

**Issue by rafabenmar-te** [nodejs/help#2520]
* **Node.js Version**: 13.9.0
* **OS**: Ubuntu 16
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

This [fix for libuv](https://github.com/nodejs/node/commit/464f4afa66) was released on node 13.9.0, my question is if this fix will be released in the current LTS major version (12) or next one (14, i think?).
Thanks

**Comment by gireeshpunathil** [comment]
yes. if you go to the PR pertinent to that commit and scroll to the bottom, you can see that the same thing went into `v13.9.01, `v10.20.0`, and `v12.16.2`. Obviously, it would have been carried over to `v14`.

Hope this helps!

**Comment by gireeshpunathil** [comment]
closing as answered, pls re-open it it is still an issue
