### ISSUE TITLE
Downgrade to Stable

### ISSUE THREAD

**Issue by varlevi** [nodejs/help#2521]
* **Node.js Version**: 13.10.1
* **OS**: Raspian Linux

Hey! I have the newest version of node.js installed globally on my computer and am trying to create a site locally using Gatsby. However, there is an issue with Gatsby's ```gatsby develop``` command and node.js v13.10.1, so I need to downgrade to the stable version of node (v12.16.1). I've tried using **n**, but while it installs the older version, it doesn't remove 13.10.1 from being used actively.

**Comment by gireeshpunathil** [comment]
@varlevi - is this still an issue? I have not used `n` personally, so don't know about that. One option is to download the binary zip for the stable version, and unzip it at the location of the unwanted node (13.x).

hope this helps.

**Comment by PoojaDurgad** [comment]
@varlevi - basically 'n' Interactively Manage Your Node.js Versions . means that will let us easily switch between Node versions.
-  npm install -g n        (Install n globally)
- n rm <version..>        ( removes given <version..>)
for me wrt your issue ,.Hopefully https://www.npmjs.com/package/n this documentation will help you to resolve the issue.

**Comment by varlevi** [comment]
Thanks @gireeshpunathil and @PoojaDurgad for your help! I actually ended up using `nvm` to help me manage versions, but your advice will definitely make things easier in the future!
