### ISSUE TITLE
async hook stack has become corrupted

### ISSUE THREAD

**Issue by JoeEarly** [nodejs/help#2523]
* **Node.js Version**: 10.16.3 (previously 8.10.0)
* **OS**: NAME="Ubuntu" VERSION="18.04.4 LTS (Bionic Beaver)"

I am having this odd issue and cant seem to work out why. My running is fairly small, with around 70 API endpoints connected to a mongodb and one filewatcher setup using chokidar

You can see the full detail of my issue here including error stack and sample code that I think may be causing it. 

https://stackoverflow.com/questions/60642082/async-hook-stack-has-become-corrupted

**Comment by gireeshpunathil** [comment]
@nodejs/async_hooks
