### ISSUE TITLE
Assert failed! Expression: object->internalFieldCount() > 0

### ISSUE THREAD

**Issue by Misiur** [nodejs/help#2524]
* v13.11.0
* Windows 10 x64

### What steps will reproduce the bug?

```
const {
  loadImage,
} = require('canvas');

async function main() {
  const image = await loadImage('./assets/simple.gif');
  console.log(image);
}

main();
```

Run node debugger, breakpoint on console log, hover over image, try to inspect `__proto__`
### What is the expected behavior?
Working debug
### What do you see instead?
Assert failed! Expression: object->internalFieldCount() > 0
https://i.imgur.com/81MxbKB.png

### Additional information
Hover via VSCode, but related issues point to that being directly node bug.

**Comment by addaleax** [comment]
I’ve moved this to the help repo but it’s unlikely that we can actually help you, as @mscdex pointed out.

**Comment by Misiur** [comment]
https://github.com/Automattic/node-canvas/issues/1534

**Comment by gireeshpunathil** [comment]
looks like this has been fixed in node-canvas repo through https://github.com/Automattic/node-canvas/pull/1550. closing, re-open if there is anything outstanding
