### ISSUE TITLE
Can't download on MacOS Catalina 10.15.3

### ISSUE THREAD

**Issue by jonas0915** [nodejs/help#2525]
Software needs to be updated. Mac unable to check content.

**Comment by jonas0915** [comment]
node still unable to get downloaded

**Comment by jonas0915** [comment]
please give me a solution

**Comment by MetCoder95** [comment]
Have you tried using `nvm` instead of downloading it from the node.org website?

**Comment by crzytaghi** [comment]
I am running into the same issue and this is the error message I am getting. I am currently running Catalina (10.15.4)

![Screen Shot 2020-04-01 at 1 30 36 PM](https://user-images.githubusercontent.com/20955491/78173856-f61a1700-741d-11ea-96ed-8baf83c30fca.png)

**Comment by jonas0915** [comment]
once you download the file you need to manually install it. Go to the folder where it's stored and press right click on the file and install.

**Comment by PoojaDurgad** [comment]
@crzytaghi - did @jonas0915 's suggestion help you to resolve the issue? or still outstanding? and @jonas0915 - is there anything pending in this issue?

**Comment by PoojaDurgad** [comment]
inactive . closing!! please feel free to reopen the issue if it is outstanding!!
