### ISSUE TITLE
C++ module by node-gyp in win10, call LoadLibrary Failed

### ISSUE THREAD

**Issue by zengdongbao** [nodejs/help#2526]
* **Node.js Version**: 12.3
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**: addon

I write a native C++ module（name: MyCppModule） by node-gyp，it work ok，but now I have another DLL， so  I call LoadLibrary(“myDLL.dll”) in “MyCppModule”，but it not work， it return NULL, GetLastError return 126， means not found the module, if I call LoadLibrary(“myDLL.dll”) in other program, it work, need help

same as [https://github.com/microsoft/nodejs-guidelines/issues/92](https://github.com/microsoft/nodejs-guidelines/issues/92)

![issue](https://user-images.githubusercontent.com/265074/76684108-2bfc8480-6644-11ea-95dc-297c7eacb57b.jpg)

**Comment by NickNaso** [comment]
Hi @zengdongbao,
could you post your `binding.gyp` file? Maybe you only need to set the shared libraries  that you want use on your `binding.gyp` like reported on the following example:
```gyp
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "addon.cc" ],
      "lbraries": [
         // Set the path of your shared library or dll
      ]
    }
  ]
}
```
I hope that this could help you.

**Comment by zengdongbao** [comment]
I think i found the reason. the target library link another dll, but the %PATH% not include directory yet.
