### ISSUE TITLE
`fs.promises` API documentation should be clearer about using pooled Buffers, unlike the callback‑based `fs`

### ISSUE THREAD

**Issue by ExE-Boss** [nodejs/help#2529]
* **Version**: v13.11.0
* **Platform**: 64‑bit Windows 10.0.18363.720 (v1909)
* **Subsystem**: `fs`

### What steps will reproduce the bug?

Run the **JSDOM** [`test/api/encoding.js`](https://github.com/jsdom/jsdom/blob/88868e86a139598ffcbc6a58247d578dd8521e80/test/api/encoding.js) **Mocha** test replacing `util.promisify(fs.readFile)` with `fs.promises.readFile`

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

The test behaviour is identical as with `util.promisify(fs.readFile)`.

### What do you see instead?

https://travis-ci.org/github/jsdom/jsdom/jobs/650962643#L6403-L8584

### Additional information

Encountered during development of <https://github.com/jsdom/jsdom/pull/2839>.

---

<details>
<summary><strong>Simple reproduction test case</strong></summary>

**Note:** Requires [the `fixtures` directory](https://github.com/jsdom/jsdom/tree/88868e86a139598ffcbc6a58247d578dd8521e80/test/api/fixtures) from **JSDOM’s API** tests.

```js
"use strict";
const fs = require("fs");
const path = require("path");
const util = require("util");
const assert = require("assert");

/** @param {string} fixture */
function fixturePath(fixture) {
	return path.resolve(__dirname, "fixtures/encoding", fixture);
}

/** @param {string} fixture */
function readFixture(fixture) {
	const path = fixturePath(fixture);
	return Promise.all([
		fs.promises.readFile(path),
		util.promisify(fs.readFile)(path),
	]);
}

/** @param {Buffer} buffer */
const toInt8Array = buffer => {
	// Test a view that is indexing into a larger ArrayBuffer
	const target = new Int8Array(buffer.buffer);
	const bigger = new Int8Array([0, 0, 0, ...target, 0, 0, 0]);
	const subView = new Int8Array(bigger.buffer, 3, buffer.buffer.byteLength);

	return subView;
};

/** @type {{ [factory: string]: (fixture: string) => Promise<[ArrayBufferView, ArrayBufferView] | [ArrayBuffer, ArrayBuffer]>}} */
const factories = {
	Buffer: fixture => readFixture(fixture),
	Uint8Array: fixture =>
		readFixture(fixture).then(([buffer1, buffer2]) => {
			return [Uint8Array.from(buffer1), Uint8Array.from(buffer2)];
		}),
	ArrayBuffer: fixture =>
		readFixture(fixture).then(([buffer1, buffer2]) => {
			return [buffer1.buffer, buffer2.buffer];
		}),
	DataView: fixture =>
		readFixture(fixture).then(([buffer1, buffer2]) => {
			return [new DataView(buffer1.buffer), new DataView(buffer2.buffer)];
		}),
	Int8Array: fixture =>
		readFixture(fixture).then(([buffer1, buffer2]) => {
			return [toInt8Array(buffer1), toInt8Array(buffer2)];
		}),
};

const encodingFixtures = {
	"no-bom-charset-http-equiv-no-quotes.html": {
		name: "ISO-8859-5",
		nameWhenOverridden: "ISO-8859-8",
		body: "Ђ",
		bodyWhenOverridden: "¢",
	},
	"no-bom-charset-http-equiv-tis-620.html": {
		name: "windows-874",
		nameWhenOverridden: "ISO-8859-8",
		body: "ข",
		bodyWhenOverridden: "¢",
	},
	"no-bom-charset-koi8.html": {
		name: "KOI8-R",
		nameWhenOverridden: "ISO-8859-8",
		body: "╒",
		bodyWhenOverridden: "¢",
	},
	"no-bom-charset-utf-16.html": {
		name: "UTF-8",
		nameWhenOverridden: "ISO-8859-8",
		body: "Є",
	},
	"no-bom-charset-utf-16be.html": {
		name: "UTF-8",
		nameWhenOverridden: "ISO-8859-8",
		body: "Є",
	},
	"no-bom-charset-utf-16le.html": {
		name: "UTF-8",
		nameWhenOverridden: "ISO-8859-8",
		body: "Є",
	},
	"no-bom-no-charset.html": {
		name: "windows-1252",
		nameWhenOverridden: "ISO-8859-8",
		body: "®",
	},
	"utf-8-bom.html": {
		name: "UTF-8",
		nameWhenOverridden: "UTF-8",
		body: "Є",
		bodyWhenOverridden: "Є",
	},
	"utf-16be-bom.html": {
		name: "UTF-16BE",
		nameWhenOverridden: "UTF-16BE",
		body: "Є",
		bodyWhenOverridden: "Є",
	},
	"utf-16le-bom.html": {
		name: "UTF-16LE",
		nameWhenOverridden: "UTF-16LE",
		body: "Є",
		bodyWhenOverridden: "Є",
	},
};

const thenCatch = reason => console.error(reason);

for (const binaryDataType of Object.keys(factories)) {
	const factory = factories[binaryDataType];
	for (const encodingFixture of Object.keys(encodingFixtures)) {
		const { name, body } = encodingFixtures[encodingFixture];
		factory(encodingFixture)
			.then(([buffer1, buffer2]) => {
				assert.strictEqual(
					buffer1.byteLength,
					buffer2.byteLength,
				);
			})
			.catch(thenCatch);
	}
}
```

**Comment by ExE-Boss** [comment]
In that case, the bug is actually in `fs.readFile`, which likely has to keep it due to backwards compatibility concerns.

That said, the docs for `fs.promises` should be clearer about this, since it’s not just a drop‑in replacement for `util.promisify(fs.<api>)`.

**Comment by addaleax** [comment]
> That said, the docs for `fs.promises` should be clearer about this, since it’s not just a drop‑in replacement for `util.promisify(fs.<api>)`.

To be completely honest, I don’t think that’s a fair statement. It is a drop-in replacement if you stick to supported API usage, and the fact that you cannot assume that a `Buffer` is a view over its underlying `ArrayBuffer` is documented explicitly at the link above.

If you have concrete suggestions for improving the documentation, that would be very welcome, though.

**Comment by ExE-Boss** [comment]
I think that both `fs.readFile(…)` and `fs.promises.readFile(…)` should link to <https://nodejs.org/api/buffer.html#buffer_buf_byteoffset>, with the former stating that it uses unpooled buffers for backwards compatibility, whereas the latter uses pooled buffers for faster performance.
