### ISSUE TITLE
SHA-1 cipher suites were detected Ibm cloud

### ISSUE THREAD

**Issue by shadeel** [nodejs/help#2533]
Node Version:12.13.0
ibm cloud

I have a cloud foundary application deployed over ibm cloud, we went through appscan and it is reporting vulnerability that SHA-1 Cipher suites were detected

The following weak cipher suites are supported by the server:
LS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

any idea how I can fix this ?

**Comment by gireeshpunathil** [comment]
@shadeel - is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
