### ISSUE TITLE
Verdaccio can't start after updating

### ISSUE THREAD

**Issue by wchalmers** [nodejs/help#2534]
Not sure if this is the right place to put this?

I don't know much about verdaccio as i normally wokr on Windows, verdaccio was working fine, then to update it i types "npm install -g verdaccio" then let it do its thing and restarted both verdaccio and nginx, nginx started fine but verdaccio will not start and is throwing a weird missing syntax token error:

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/verdaccio/node_modules/jsdom/lib/jsdom/living/helpers/form-controls.js:18:5)
 
Can anyone please help me out?

**Comment by GlenTiki** [comment]
What is your node.js version? run `node -v`.

Also what is your verdaccio version? run `verdaccio -v`

**Comment by enzy20000** [comment]
Its node.js version 8.10.0 and i cant see the verdaccio version because it comes up with the same error as posted above, anytime i try to do a verdaccio command it throws it, i'd imagine it would be quite a new version since its updated every month though.

**Comment by GlenTiki** [comment]
Node version 8+ shouldn't be causing the issue, as Verdaccio requires 6+. This may require an issue to be opened in verdaccio itself, over here: https://github.com/verdaccio/verdaccio/issues

**Comment by juanpicado** [comment]
@enzy20000 your issue is explained here https://github.com/verdaccio/verdaccio/pull/1753

If you cannot upgrade to node v10 , then use 

```
npm i -g verdaccio@4.4.4
```

We have dropped Node 8 since is not longer maintained also to help users to easy migrate to a future Verdaccio 5.

**Comment by enzy20000** [comment]
Thank you Juan!!
