### ISSUE TITLE
Is asking about CentOS6 a bad idea?

### ISSUE THREAD

**Issue by johnhosie** [nodejs/help#2535]
I have an 88 node cluster still running **_CentOS 6_**. I'm trying to get a **_CentOS 7_** cluster started, but since I'm supporting this solo, it will be a while before I can offer it on the cluster. Is there a way to get this code running on **_CentOS 6_**?

**Comment by gireeshpunathil** [comment]
@johnhosie -  is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
