### ISSUE TITLE
Apple won't let me install node.js:  "node-v12.16.1.pkg” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by Cruebee** [nodejs/help#2536]
* **Node.js Version**: any
* **OS**: macOS
* **Scope (install)**: Install issue

I've tried installing node directly in the terminal and from nodejs.org. Apple prompts me with an error saying: "node-v12.16.1.pkg” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. contact the developer for more information.

**Comment by Hakerh400** [comment]
https://github.com/nodejs/node/issues/29216

**Comment by Cruebee** [comment]
Kinda figured it out. Forced the install myself. Appreciate apple security but damn.
