### ISSUE TITLE
AsyncLocalStorage loses a context

### ISSUE THREAD

**Issue by Doc999tor** [nodejs/help#2537]
* **Node.js Version**: 13.11
* **OS**: Win10
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: async_hooks

[Docs](https://github.com/nodejs/node/blob/master/doc/api/async_hooks.md) say: In this example, the store is only available in the callback function and the functions called by `foo`. Outside of `runSyncAndReturn`, calling `getStore` will return `undefined`.  
I need the store available in the scope of `asyncRouter` only
How should I persist context is the example below? 
Thanks

`Express` plain example: 
File: async-store.js
```
const { AsyncLocalStorage } = require("async_hooks");
exports.asyncLocalStorage = new AsyncLocalStorage();
```
File: app.js
```
const { asyncLocalStorage } = require("./async-store");
const { asyncRouter } = require("./async-router");
const app = express();
asyncLocalStorage.runSyncAndReturn({}, async () => {
    console.log(asyncLocalStorage.getStore()); // Prints `{}` - as expected
    app.use(asyncRouter); // neither a regular
    // await Promise.resolve(app.use(asyncRouter)); # neither promised call keeps the context
});
```

File async-router.js
```
const { asyncLocalStorage } = require("./async-store");
exports.asyncRouter = router;
router.get('/async-test', async (req, res) => {
    console.log(asyncLocalStorage.getStore()); // _undefined_
    res.send();
});
```

**Comment by gireeshpunathil** [comment]
cc @vdeturckheim

**Comment by vdeturckheim** [comment]
Thanks for the heads up @gireeshpunathil !

@Doc999tor so, you are entering the AsyncLocalStorage context outside of a transaction. You want to call `run` or `runSyncAndReturn` _inside a middleware_.

The solution here is to change the first piece of code by something like
```js
app.use((req, res, next) => {
    asyncLocalStorage.runSyncAndReturn({}, () => next());
});
app.use(asyncRouter.asyncRouter);
```
and you should see what you want.

Let me know if that works!

**Comment by Doc999tor** [comment]
Thanks @vdeturckheim 
You've provided a very basic naive example
But as you saw from my example I have the `store` created in `app.js` and required `router` object defined in another file that has a bunch of routes - all of these should have an access to the `store`
How should I manage correctly a little more real world project?
Thanks again for the help!

**Comment by vdeturckheim** [comment]
I am not sure I understand your need here. In my example, I still add `asyncRouter` to the middleware list and within it, it will have access to the store.

In term of async operation, the code running inside a middleware is not a child of the code that instanciated the middleware itself. AsyncLocalStrorage is a transactional API that spread a context through the event loop.

**Comment by Doc999tor** [comment]
@vdeturckheim 

> In term of async operation, the code running inside a middleware is not a child of the code that instanciated the middleware itself

If I wrap the express instantiating **and** the middleware use call, the async context is kept the same:
```
asyncLocalStorage.run({}, async () => {
    const app = express();
    app.use(asyncRouter); // inside all the middlewares the async context kept the same
}
```

**Comment by vdeturckheim** [comment]
I am not sure I get this one, do you mean the store you get inside middlewares execution is the one you instanciated when registering the middlewares?

**Comment by Doc999tor** [comment]
I tested it first place - this store is fully available in all the middlewares invoked inside the `.run` callback
Because of this, I expected `runSyncAndReturn` behaving the same 
```
asyncLocalStorage.run({}, async () => {
    const app = express();
    app.use(asyncRouter); // inside all the middlewares the async context kept the same, works fine
    // asyncRoute has access to the 	same asyncLocalStorage.getStore()
}
```

**Comment by vdeturckheim** [comment]
Have you tried the same thing with `runSyncAndReturn` with the line `const app = express();` inside the callback?

**Comment by Doc999tor** [comment]
Sure, thus I did
But the point of my experiment is to have separate stores for specific routes: 
>  I need the store available in the scope of asyncRouter only

Instead of creating a *God-object* stores all kinds of information ever being useful in the whole nodejs server, I wanted to create smaller separate stores for different kinds of nodejs services, to decouple logic
But one store for all http routes is definitely good enough for me. Thanks for your help!
