### ISSUE TITLE
Can't spawn with quotes in options. 

### ISSUE THREAD

**Issue by physiii** [nodejs/help#2542]
System: Ubuntu 19.10, node -v v13.11.0

I need to reliably spawn and kill this process:

ffmpeg -re -i video.avi -f tee -codec:v mpeg1video -map 0:a -map 0:v -r 20 
'[f=mpegts:select=v]http://127.0.0.1:8083/video_token/|[f=mpegts:select=a]http://127.0.0.1:8083/audio_token/'

I switched from double to single quotes ([as mentioned in previous issues](https://github.com/nodejs/node/issues/5060)) to no avail.

I tried using `shell: true` but then I can't reliable `.kill()` the process. Same with execFile.

Also tried more options:

`fileStreamProcess = spawn('ffmpeg', options, { shell: true, stdio: ["ignore", "pipe", "inherit"], detached: true });`

How do I use spawn without the shell with an option that contains double quotes?

**Comment by Hakerh400** [comment]
* What is your operating system?
* What is your Node.js version?

> I switched from double to single quotes (as mentioned in **previous issues**) to no avail.

Which issues?

Can you share the exact full code that your are using to spawn the process?

What exactly are you trying to achieve? The ffmpeg configuration you provided cannot be run on windows, since the official ffmpeg installation for windows does not include the `tree` output format decoder.

**Comment by physiii** [comment]
> * What is your operating system?
> * What is your Node.js version?
> 
> > I switched from double to single quotes (as mentioned in **previous issues**) to no avail.
> 
> Which issues?

Added system details and issue link.

> Can you share the exact full code that your are using to spawn the process?

Sure, see below.  Or my [repo](https://github.com/physiii/camera/blob/master/video-streamer.js#L108)

> What exactly are you trying to achieve? The ffmpeg configuration you provided cannot be run on windows, since the official ffmpeg installation for windows does not include the `tree` output format decoder.

No sure what you are asking? I am trying to reliably run and kill that ffmpeg process like I've done hundreds of times of the paste few years. Problem is quotes in the options mess things up and this seems to be a common issue.


```
	getAudioVideoStreamUrl (streamId) {
		let audioUrl = config.relay_server + ':' + (config.video_stream_port || defaultStreamPort) + '/' + streamId + '/' + audioStreamToken + '/',
			videoUrl = config.relay_server + ':' + (config.video_stream_port || defaultStreamPort) + '/' + streamId + '/' + videoStreamToken + '/';

		if (config.use_ssl) {
			audioUrl = 'https://' + audioUrl;
			videoUrl = 'https://' + videoUrl;
		} else {
			audioUrl = 'http://' + audioUrl;
			videoUrl = 'http://' + videoUrl;
		}

		let url =  "\'" + "[f=mpegts:select=v]" + videoUrl + "|" + "[f=mpegts:select=a]" + audioUrl + "\'";
		return url;
	}


	streamAudioFile (streamId, streamToken, file) {

		audioStreamToken = streamToken;

		let options = [
			'-loglevel', 'panic',
			'-re',
			'-i', file,
			'-f', 'tee',
				'-codec:v', 'mpeg1video',
				'-q:v', '0',
				'-b:v', '900k',
				'-c:a', 'mp2',
				'-flags', '+global_header',
				'-b:a', '128k',
				'-map', '0:a',
				'-map', '0:v',
				'-r', '20',
			this.getAudioVideoStreamUrl(streamId)
		];

		let command = this.printFFmpegOptions(options);

		if (fileStreamProcess) fileStreamProcess.kill();

		console.log(TAG, 'Starting audio/video file stream. Stream ID:', command);

		fileStreamProcess = spawn('ffmpeg', options, { stdio: ["ignore", "pipe", "inherit"] });
		fileStreamProcess.on('close', (code) => {
			console.log(TAG, `Audio/video file stream exited with code ${code}. Stream ID:`, streamId);
		});
	}

	printFFmpegOptions (options) {
		let options_str = 'ffmpeg';
		for (let i = 0; i < options.length; i++) {
			options_str += ' ' + options[i];
		}
		return options_str;
	}

```

**Comment by Hakerh400** [comment]
> Added system details and issue link.

How is that issue related? That issue is about verbatim arguments for command prompt on windows, and you are using linux...

> The ffmpeg configuration you provided cannot be run on windows, since the official ffmpeg installation for windows does not include the tree output format decoder.
>>No sure what you are asking?

I am talking about `tree` output format being excluded from the official ffmpeg binaries, both for windows and linux. You are probably using a custom ffmpeg build if that command works for you.

Back to your issue, I think you don't need any quotes at all. Try to change

```js
let url =  "\'" + "[f=mpegts:select=v]" + videoUrl + "|" + "[f=mpegts:select=a]" + audioUrl + "\'";
```

to

```js
let url =  "[f=mpegts:select=v]" + videoUrl + "|" + "[f=mpegts:select=a]" + audioUrl;
```

because `spawn` internally escapes each argument, so you don't need extra escaping.

**Comment by physiii** [comment]
> because `spawn` internally escapes each argument, so you don't need extra escaping.

That worked! 

Much appreciated.
