### ISSUE TITLE
Probable generator context switch in a loop

### ISSUE THREAD

**Issue by Misiur** [nodejs/help#2547]
Version: v13.11.0
Platform: Windows 10 x64
Subsystem: WSL Ubuntu 18

### What steps will reproduce the bug?
```js
function *gen(cb) {
  while (true) {
    const input = yield;
    console.log(input);

    yield 5 + input;
  }
}

const values = [];
const geng = gen();
for (let index = 0; index < 5; index++) {
  console.log(geng.next(index));
  values.push(geng.next().value);
}
console.log(values);
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

```
0
{ value: 5, done: false }
1
{ value: 6, done: false }
2
{ value: 7, done: false }
3
{ value: 8, done: false }
4
{ value: 9, done: false }
[ 5, 6, 7, 8, 9 ]
```

### What do you see instead?

```
{ value: undefined, done: false }
undefined
{ value: undefined, done: false }
undefined
{ value: undefined, done: false }
undefined
{ value: undefined, done: false }
undefined
{ value: undefined, done: false }
undefined
[ NaN, NaN, NaN, NaN, NaN ]
```

### Additional information

One way to move it a little bit is to force `.next()` call, but it does not work as expected:
```js
const geng = gen();
geng.next();
for (let index = 0; index < 5; index++) {
  values.push(geng.next(index).value);
  geng.next();
}
```

Which is not intuitive for me, as it does not make any sense, or does it?

**Comment by Hakerh400** [comment]
Please note that:

* The first call to `next` method on a generator object discards the argument, because it is not blocked on the first `yield` invocation, but on the function entry itself. It is used to start the generator. Your second example (where you call `geng.next()` once before the loop is more correct).
* The `yield` operator is used both for receiving and sending values from/to generator and each `yield` consumes a single `next` call.
* You have two `yield` operators. One of them always yields undefined, while the other yields a number. You cannot expect both of them to give you a number.

This gives you the *"expected output"* you proposed:

```js
const values = [];
const geng = gen();
geng.next();
for(let index = 0; index < 5; index++){
  const result = geng.next(index);
  console.log(result);
  values.push(result.value);
  geng.next();
}
console.log(values);
```

> Which is not intuitive for me, as it does not make any sense, or does it?

It depends on what you consider to be an intuitive behavior. This behavior is correct per the specification.

**Comment by Misiur** [comment]
I think you are a bit wrong, as the first (or second as you explained) call to `.next` only should take a value, not yield anything, or is it blocked on second `yield`, *after* returning the value?

**Comment by Hakerh400** [comment]
> I think you are a bit wrong, as the first (or second as you explained) call to .next only should take a value, not yield anything, or is it blocked on second yield, after returning the value?

I really don't understand what you want to say... Are you talking about something not working as expected, or just about your disagreement regarding the specification intuitiveness? I asure you that the current behavior is expected and specification compliant and thus is not going to change.

If you are confused by how generators work, look at the following example:

```js
function *a(){
  let a = yield 'x';
  let b = yield a + 'y';
  let c = yield b + 'z';
  return c;
}

a = a();

console.log(a.next(1).value);
console.log(a.next(2).value);
console.log(a.next(3).value);
console.log(a.next(4).value);
```

and try to guess what it will output, before actually running the code. Was your guess correct?

**Comment by vsemozhetbyt** [comment]
@Misiur Maybe this can help: https://exploringjs.com/es6/ch_generators.html

Especially, this part: https://exploringjs.com/es6/ch_generators.html#sec_generators-as-observers

There is indeed a confusing moment in the generators consuming data:

 > Unfortunately, `next()` is asymmetric, but that can’t be helped: It always sends a value to the currently suspended `yield`, but returns the operand of the following yield.

**Comment by Misiur** [comment]
@vsemozhetbyt thanks, that's the clearest explanation. I made an edit to MDN to highlight this
