### ISSUE TITLE
Save Octet-stream data as PDF file in javascript

### ISSUE THREAD

**Issue by sriramgroot** [nodejs/help#2550]
* **Node.js Version**: 8.10.0
* **OS**: macOS Mojave - version 10.14.6 (18G3020)
* **Scope (install, code, runtime, meta, other?)**: Final output should be a PDF file and it should not be blank document
* **Module (and version) (if relevant)**:

How to convert the below mentioned stream data into PDF file in nodejs
**Stream data sample:** https://gist.github.com/sriramgroot/33e6e4934081f3d1b9d70c88873f2ad9

**Response Header**
<img width="1157" alt="Screenshot 2020-03-25 at 11 01 40 AM" src="https://user-images.githubusercontent.com/58930932/77562696-5a048300-6ee6-11ea-8b8f-f8c704dc8cf5.png">

**Comment by sriramgroot** [comment]
Found a solution for saving the file, and it if possible in **Scenario 1**.    

- In Octet-stream you will be receiving the response as "Encoded Binary Data"
- Your need to convert the response data into "Decoded Base64 String"
- Finally save it as PDF

Also we can use NPM package - [Base64toPDF](https://www.npmjs.com/package/base64topdf) for making the listed process as automated.

**Comment by sriramgroot** [comment]
Team,
If there is any proper/best solution regarding this question please reply in the comment

Thanks in advance.

**Comment by levitomer** [comment]
I'm also experiencing the same issue.. [pdf-doesnt-downloaded-node-express-puppeteer](https://stackoverflow.com/questions/61887975/pdf-doesnt-downloaded-node-express-puppeteer)

 I get the following headers in the response:
![image](https://user-images.githubusercontent.com/18260079/82330004-e4e79280-99ea-11ea-8716-63e1ed87b908.png)

As well as the content body as base64:
![image](https://user-images.githubusercontent.com/18260079/82330051-f9c42600-99ea-11ea-8dbe-693a0f1307bc.png)

I am seeking for a way to download/save it as PDF.

Help

**Comment by sriramgroot** [comment]
> I'm also experiencing the same issue.. [pdf-doesnt-downloaded-node-express-puppeteer](https://stackoverflow.com/questions/61887975/pdf-doesnt-downloaded-node-express-puppeteer)
> 
> I get the following headers in the response:
> ![image](https://user-images.githubusercontent.com/18260079/82330004-e4e79280-99ea-11ea-8716-63e1ed87b908.png)
> 
> As well as the content body as base64:
> ![image](https://user-images.githubusercontent.com/18260079/82330051-f9c42600-99ea-11ea-8dbe-693a0f1307bc.png)
> 
> I am seeking for a way to download/save it as PDF.
> 
> Help

Hi @levitomer 

Please check this solution, it solved [my issue](https://github.com/nodejs/help/issues/2550#issuecomment-605752862)

**Comment by levitomer** [comment]
Sorry @sriramgroot , I don't want to use external library such as Base64toPDF library.

Only node..

**Comment by levitomer** [comment]
@sriramgroot can you show me how to use that library in the client, in order to download the pdf?

**Comment by sriramgroot** [comment]
Hi @levitomer 
We could not use this library in frontend/browser. It should be used in Node.js

**Comment by yossely** [comment]
hi @sriramgroot I'm using the library you mentioned like this 
```js
const base64 = require('base64topdf');
let decodedBase64 = base64.base64Decode(resp.data, 'file.pdf');
``` 
but I'm getting a corrupt pdf file, not able to open it. I'm using your [Stream data sample]( https://gist.github.com/sriramgroot/33e6e4934081f3d1b9d70c88873f2ad9) and still get the corrupt pdf file.

Do you know why is this happening?

**Comment by yossely** [comment]
I could solve my problem, I needed to add `responseType: 'arraybuffer'` option in the get request like:
```js
Axios.get(
  URL,
  {
    headers: {
      Authorization: `Bearer TOKEN`,
    },
    responseType: 'arraybuffer', // <- I was missing this option
  }
)
```
With that `responseType` option I get a buffer in `response.data`
![image](https://user-images.githubusercontent.com/5514988/95218273-b90e5300-07b9-11eb-9734-f52064361662.png)

And finally I can create the pdf file with:
```js
var fs = require('fs');
fs.writeFileSync('docName.pdf', resp.data);
```

**Comment by AdrianTudC** [comment]
Why is the `responseType: 'arraybuffer'` so important in this case though?

**Comment by yossely** [comment]
@AdrianTudC without that option, the `response.data` is not parsed correctly, that's why I was getting a corrupt file when trying to save the pdf

**Comment by AdrianTudC** [comment]
I know that, but I was trying to understand how is axios manipulating the data with and without that option. It seems like without it it's just stringified with the default utf8 encoding which leads to data loss. I just wanted to be sure that it's not something reversible in my code.

**Comment by chcalibrr** [comment]
@yossely I'm getting a blank white pdf even with the `responseType: 'arraybuffer'`

```
'content-type': 'application/octet-stream',
'content-disposition': 'attachment;filename=944883.pdf',
```

**Comment by levibeach** [comment]
I found it works if I set `responseType:'blob'` and then generate the PDF link like so:
```
const url = window.URL.createObjectURL(new Blob([response.data]))
const link = document.createElement('a')
link.href = url
link.setAttribute('download', 'myPDF.pdf')
document.body.appendChild(link)
link.click()
```
Hope this helps someone ¯\\\_(ツ)\_/¯

**Comment by artsooter** [comment]
when i use axios, i make a mistake
![image](https://user-images.githubusercontent.com/33850363/210292040-27a3b83a-4827-4ead-b9b7-ef10423866f5.png)


and i change the  `responseType: 'arraybuffer'` config. it useful
![image](https://user-images.githubusercontent.com/33850363/210292106-7d765b6e-a406-4ff4-8562-0d6a843e5e83.png)

**Comment by preveen-stack** [comment]
@sriramgroot were you able to use the above suggestion

**Comment by ajaytomarfideo** [comment]
<img width="1107" alt="Screenshot 2023-10-17 at 12 07 53 PM" src="https://github.com/nodejs/help/assets/145985329/e78da914-065b-46e5-b0e6-2044b0d1d8fd">
<img width="1071" alt="Screenshot 2023-10-17 at 12 08 39 PM" src="https://github.com/nodejs/help/assets/145985329/739a15ac-a6ce-402b-8f23-e62ad6a99c1d">

I have tried "responseType:'blob' and responseType:'arraybuffer'" too. But everytime I am getting empty pdf. @artsooter @yossely @levitomer @skylarmb Can you guys suggest something?
