### ISSUE TITLE
 Does not work response.redirect

### ISSUE THREAD

**Issue by ALCOFO** [nodejs/help#2551]
Please help. Redirecting from post request to get on Linux does not occur. Everything is fine on Windows. Node 12.16.1, Linux pop os 19.10. I tried in fedora 32, the same problem
https://github.com/ALCOFO/reestr

[get.txt](https://github.com/nodejs/help/files/4382902/get.txt)
[post.txt](https://github.com/nodejs/help/files/4382903/post.txt)

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
