### ISSUE TITLE
How to truncate file while writing to it

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2554]
I put this question on SO https://stackoverflow.com/questions/60875131/how-to-truncate-file-from-node-js

basically, as my node process is writing to the file, every once in a while, I want to read the last 500 lines of the file (`tail -n 500`) and then truncate the file, and write the remaining 500 lines to it. any idea how to do that safely?

**Comment by addaleax** [comment]
1. Open a new, temporary file
2. Read the last 500 lines from the old file
3. Write that data to the new file
4. Move the new file to the location of the old file

Obviously, that’s assuming that no other processes write data to the file between 2. and 4. and that no other processes keep the old file open. But judging from your description that seems like accurate assumptions?

**Comment by ORESoftware** [comment]
a good way to read the last 500 lines with a child process?

**Comment by insfrag** [comment]
As a basic first implementation, you could use https://nodejs.org/api/readline.html#readline_example_read_file_stream_line_by_line and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift, assuming it's ok to read the entire file and store all lines in memory.
