### ISSUE TITLE
When addContext(IPv6, ...), should the IPv6 has square brackets / be short style / lowsercase?

### ISSUE THREAD

**Issue by LongTengDao** [nodejs/help#2555]
* **Node.js Version**: unrelated
* **OS**: unrelated
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: tls https http2

```js
const server = https.createServer();
const options = { /* ... */ };
server.addContent('[::f]', options);
server.addContent('::f', options);
server.addContent('0000:0000:0000:0000:0000:0000:0000:000F', options);
```

Which is correct? What will SNI send, and will nodejs transform it before compare?

(I thought IP couldn't have a TLS certificate, but then I saw <https://1.1.1.1/> and realized that it could.)

**Comment by addaleax** [comment]
https://tools.ietf.org/html/rfc6066 answers this (although probably not in the way you were hoping for):

> Literal IPv4 and IPv6 addresses are not permitted in "HostName".

**Comment by devsnek** [comment]
(unless you're using AnyIP) there's no way you could be listening to multiple IP addresses with a single https server instance. If you aren't trying to use SNI just pass your key and cert to the https.createServer function.

**Comment by LongTengDao** [comment]
> https://tools.ietf.org/html/rfc6066 answers this (although probably not in the way you were hoping for):
> 
> > Literal IPv4 and IPv6 addresses are not permitted in "HostName".

Oh... Thank you! It means when I open <https://1.1.1.1/>, there won't be a SNI sent to the server?

**Comment by LongTengDao** [comment]
> (unless you're using AnyIP) there's no way you could be listening to multiple IP addresses with a single https server instance. If you aren't trying to use SNI just pass your key and cert to the https.createServer function.

It need to be removed while running, but there is only ways to set default secureOptions (`createServer` / `setSecureOptions`), but no `removeSecureOptions`, it can't achieve my aim.

**Comment by devsnek** [comment]
You can also issue an https cert with multiple subject names (using Subject Alternate Name fields)

**Comment by LongTengDao** [comment]
I'm develop an common server for different users' sites.

Now I try to `setSecureContext({})` to simulate `removeSecureContext`.
