### ISSUE TITLE
Program started with child_process.spawn stops working after some time, but child_process.exec works.

### ISSUE THREAD

**Issue by hedgehog90** [nodejs/help#2557]
The following command encodes an input video and outputs out.mkv.

```
var default_settings = { "width":1920, "height":1080 };
var settings = Object.assign({}, default_settings);

var encoding_args = ["--of=mpegts", "--ovc=libx264", `--ovcopts=profile=main,preset=veryfast,level=4,crf=20,maxrate=5000k`, `--vf=lavfi=[format=yuv420p,yadif=mode=1:deint=1,scale=(iw*sar)*min(${settings.width}/(iw*sar)\\,${settings.height}/ih):ih*min(${settings.width}/(iw*sar)\\,${settings.height}/ih),pad=${settings.width}:${settings.height}:(${settings.width}-iw*min(${settings.width}/iw\\,${settings.height}/ih))/2:(${settings.height}-ih*min(${settings.width}/iw\\,${settings.height}/ih))/2]`, `--oac=aac`, `--oacopts=ac=2,b=160k`];
var mpv_args = ["input-video.mkv", "-v", '--no-config', '--log-file=mpv.log', ...encoding_args, "--o=out.mkv"];

console.log("mpv "+mpv_args.join(" "));
var mpv = child_process.spawn("mpv", mpv_args);
```

In the command prompt, the same command it works perfectly.
If I join the arguments into a string and use child_process.exec, it works perfectly.
If I use child_process.spawn, it works for about 5 seconds... and then the encoding pauses. No crash, no exit, just pauses.

Tried using Node 10, 12 + 13 (Windows 10 64 bit). Issue is present in all.
Is this some kind of buffer limit issue? How do I get around it while still using spawn?

**Comment by hedgehog90** [comment]
The process needs to stay alive for very long periods of time, I need to monitor the stderr for messages but I don't need a huge backlog.
How do I make it so the buffer resets before it ever reaches a buffer limit... or is that a silly question?

**Comment by hedgehog90** [comment]
Still having trouble with this.
I find I get varying results if I reduce the amount of logging generated by mpv, however after a period of time it's still stopping due to some kind of piping / buffer issue.

I can only assume I'm hitting the pipe limit, but I don't know what I can do to fix this.

In my tests I've found simply acknowledging the stderr pipe with an on('data') listener improved matters in some scenarios.
I've also found that using an npm package 'execa' which wraps child_process.spawn, has helped (which uses a much bigger maxBuffer by default)
Before, my process would run for about 7 minutes before stopping.
Now it lasts for around 30 minutes.

The most frustrating thing about this issue is the lack of errors or any kind of clue as to what is happening. The child process, for all intents and purposes, appears to pause. And that's it.

I need a solution that will effectively allow me to run this process for long periods of time, reliably.

**Comment by gireeshpunathil** [comment]
@hedgehog90 - is this still an issue? 

what is `mvp` ? which direction data is flowing? why the destination process is unable to consume data at the rate in which it was supplied? before I can provide any pointers, I would like to know the data flow characteristics.

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
