### ISSUE TITLE
Implementing a Readable stream

### ISSUE THREAD

**Issue by fbiville** [nodejs/help#2558]
* **Node.js Version**: v10.18.1, v12.14.1, v13.6.0
* **OS**: Mac OS 10.15.4
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: streams

I'm trying to come up with a naive implementation for zipping streams together. Here is what I currently have:

```js
const {Readable} = require("stream");

class Zipper extends Readable {

    constructor(...streams) {
        super({objectMode: true});
        this.arrays = streams.map(() => []);
        streams.forEach((stream, index) => {
            stream.on('data', (chunk) => {
                this.arrays[index].push(chunk);
            });
        })
    }

    _read(size) {
        const bound = Math.min(size, Math.min(...this.arrays.map(a => a.length)));
        if (bound === 0) {
            return;
        }
        this.arrays
            .map(a => a.splice(0, bound))
            .reduce((prev, curr) => {
                const result = [];
                for (let i = 0; i < bound; i++) {
                    const previous = (Array.isArray(prev[i])) ? prev[i] : [prev[i]];
                    result.push([...previous, curr[i]]);
                }
                return result
            })
            .forEach((result) => {
                console.dir(result);
                this.push(result);
            })
    }
}
```
It seems there is something I fundamentally did not understand about Readable streams, but it's not super explicit in the docs so I would like to clarify this here.

Quoting the [official Readable implementation guide](https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_readable_read_size_1):

> When readable._read() is called, if data is available from the resource, the implementation should begin pushing that data into the read queue using the this.push(dataChunk) method.

And:

> Once the readable._read() method has been called, it will not be called again until more data is pushed through the readable.push() method.

Does that mean that if the `_read` call does not trigger any `push`, `_read` will never be called again?
If that's so, what am I supposed to do if the upstream streams do not have any data yet when `_read` is called for the first time?

**Comment by devsnek** [comment]
You can call push without _read being called. _read just lets you know the consumer wants data in case you're building a pull stream.

**Comment by addaleax** [comment]
> Does that mean that if the `_read` call does not trigger any `push`, `_read` will never be called again?

Yes, that’s right :+1:

> If that's so, what am I supposed to do if the upstream streams do not have any data yet when `_read` is called for the first time?

You could set e.g. a `this.waitingForData` property that is set to true in the `bound === 0` case, and check for that in the `stream.on('data', (chunk) => {` handlers – if you receive a chunk and `waitingForData` is set, then you can call `.push()` (or possibly just call `this._read()` from there to re-start the reading process). 

One other thing you may want to be aware about is that your stream example doesn’t implement backpressure – the `Zipper` reads and buffers data from other streams even if that is not being consumed. Depending on your use case, that’s something you want to look out for.

**Comment by fbiville** [comment]
Thanks @devsnek and @addaleax for your quick responses!
@addaleax this implementation is not intended for production, hence no backpressure mechanism in place.

**Comment by fbiville** [comment]
Apologies for resurrecting this old thread, but I started writing a couple of blog posts about Node streams and I want now to talk about backpressure. In particular, I would like to exhibit backpressure issues in tests and I opened [this issue](https://github.com/nodejs/help/issues/2639).
I was wondering if you maybe had some advice @addaleax / @devsnek.
