### ISSUE TITLE
Why can't I get util.isPromise to work?

### ISSUE THREAD

**Issue by asishallab** [nodejs/help#2565]
* **Node.js Version**: v10.19.0
* **OS**: Linux Ubuntu 18.04
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: core's util.isPromise

When trying out `util.isPromise` on a newly created Promise it returns false. What am I doing wrong?

```js
var Promise = require('promise')
var util = require('util')
util.types.isPromise(new Promise((res,rej) => {res('I resolved successfully')}))
// returns: false
```

Help is much appreciated. Thank you in advance

**Comment by tmvoe** [comment]
I get the same result, both with this script and with the example given on https://nodejs.org/api/util.html#util_util_types_ispromise_value - but with the node shell I get _true_

**Comment by Hakerh400** [comment]
`require('promise')` is external NPM module. It is, as said in their [readme](https://github.com/then/promise#readme), a super set of ES6 Promises. Their promises are [regular clases](https://github.com/then/promise/blob/91b7b4cb6ad0cacc1c70560677458fe0aac2fa67/src/core.js#L54), not real promises. Method `util.types.isPromise` can detect only real promises (`global.Promise` instances).

**Comment by asishallab** [comment]
Thank you @Hakerh400 ! That cleared the fog.
