### ISSUE TITLE
How to pass data to Express function with jQuery and JavaScript

### ISSUE THREAD

**Issue by TonyScarpelli** [nodejs/help#2567]
* **Node.js Version**: current version
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I have an Express function that runs a SQLite3 Select statement against a table:
For example in my script.js file I have:
**uName = "smi";**
**var sql = 'SELECT * FROM myTable WHERE Name LIKE "' + uName+ '%" ORDER BY Name;**
 **$.get("/myTable", function (data) {** etc.

In the Server.js file is the **app.get** function with this in it
**db.all(sql, function(err, rows){** etc.

I need to pass the "**sql**" statement to the **app.get** function and can't figure out how to do this.
I tried using a global variable and that didn't work, and a few other things that didn't work.
Is this possible, and if so, how can I do this?
Much thanks.

**Comment by Hakerh400** [comment]
Can you please provide the entire script? It is hard to answer your question without looking at the code.

**Comment by TonyScarpelli** [comment]
[MyCode.txt](https://github.com/nodejs/help/files/4415601/MyCode.txt)
Here's my code.
Thanks.

**Comment by Hakerh400** [comment]
In `script.js` change this line

```js
$.get("/myTable", function (data) {
```

to

```js
$.post("/myTable", {sql: sql}, function (data) {
```

and in `server.js` change

```js
app.get('/myTable', function (request, response) {
```

to

```js
app.post('/myTable', function (request, response) {
```

On the server side, the SQL statement is located at `request.body.sql`

**Comment by TonyScarpelli** [comment]
I changed the code, but it still didn't work.
I got this when I opened my page:
**DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map**

And I got this when I ran the code:
**Error: Error: SQLITE_MISUSE: not an error**

Does my version of jQuery matter?
**<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>**

Does my version of SQLite3 make a difference?

And I'm not sure what this means:
**On the server side, the SQL statement is located at request.body.sql**

Thanks.

**Comment by Hakerh400** [comment]
> I changed the code, but it still didn't work.

How did you change the code? Can you post your code with the modifications I suggested?

> I got this when I opened my page:
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map

It is unrelated to this issue. That error means you are using AdBlock extension.

> And I got this when I ran the code:
Error: Error: SQLITE_MISUSE: not an error

You probably passed an empty string to the `db.all` method. You need to use `request.body.sql` instead.

> Does my version of jQuery matter?
&lt;script src="https&#58;//code.jquery.com/jquery-3.4.1.min.js"&gt;&lt;/script&gt;

Not really.

> And I'm not sure what this means:
On the server side, the SQL statement is located at request.body.sql

It means that in your function on the server side:

```js
app.get('/myTable', function (request, response) {
  console.log('GET request received for table');
  // Here is the where the sql string should go
  db.all(sql, function (err, rows) {
    if (err) {
      console.log("Error: " + err);
    }
    else {
      response.send(rows);
    }
  });
});
```

you need to replace `sql` with `request.body.sql`, like this:

```js
app.get('/myTable', function (request, response) {
  console.log('GET request received for table');
  // Here is the where the sql string should go
  db.all(request.body.sql, function (err, rows) {
    if (err) {
      console.log("Error: " + err);
    }
    else {
      response.send(rows);
    }
  });
});
```

and make sure that you added `{sql: sql}` to the `$.post` method in `script.js`

**Comment by TonyScarpelli** [comment]
Now that you showed me where the **request.body.sql** was supposed to be it **worked great**.
Thanks so much for your help. You didn't know but you helped a 77 year old retired programmer, and the brain isn't as quick as it used to be. I started programming in 1976 with a simple programming language called **Assembly**, and then **Basic**. The modern languages are really a lot more complicated.
Well, I can close this problem now, and **many thanks again**.
