### ISSUE TITLE
Error node:1368, node:1368 rocketseat Omnistack

### ISSUE THREAD

**Issue by DenilsonGit** [nodejs/help#2568]
* **Node.js Version**: 12
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: Run an insominia with method POST using Json
* **Module (and version) (if relevant)**: express, knex, crypto

Hi guys!

I'm doing a project with RocketSeat Omnistack 11.0 and when I'll send Post method for return an ID and create a new list in my database, return for me a error that I don't how resolve.. I've been search but I did not can nothing..

Follow:
![image](https://user-images.githubusercontent.com/50993735/78096521-317dfc80-73b0-11ea-8b67-d4fe5ecdd578.png)

My code:
```js
const express = require('express');
const crypto = require('crypto');

const connection = require('./database/connection');

const routes = express.Router();

routes.post('/ongs', async (request, response) => {
    const {name, email, whatsapp, city, uf} = request.body;

    const id = crypto.randomBytes(4).toString('HEX');

    await connection('ongs').insert({
        id,
        name,
        email,
        whatsapp,
        city,
        uf,
    })

    return response.json({ id });
});

module.exports = routes;
```
Follow the error in my console.log:
(node:1368) UnhandledPromiseRejectionWarning: Error: insert into `ongs` (`city`, `email`, `id`, `name`, `uf`, `whatsapp`) values ('Rio do Sul', 'contato@apad.com.br', '2f36315e', NULL, 'SP', '11900000000') - SQLITE_CONSTRAINT: NOT NULL constraint failed: ongs.name
(node:1368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with 
a non-zero exit code.

**Comment by Hakerh400** [comment]
Isn't the error clear enough? As it says, `name` cannot be `null`

**Comment by gireeshpunathil** [comment]
@DenilsonGit - is it resolved? as @Hakerh400 suggested, the incoming record seem to be having a null field which is violating the db's constraint on the table. Either address it at the source by making sure no null appears here, or relax the constraint at the db site - whichever fits your use case.

Closing this as answered, however pls reopen if you still have questions!
