### ISSUE TITLE
Assertion `(Buffer::HasInstance(args[0])) == (true)' failed on   node::{anonymous}::Parser::Execute

### ISSUE THREAD

**Issue by yanou75pro** [nodejs/help#2572]
* **Version**: 10.16.0
* **Platform**: Linux vp-scc-core-901 3.10.0-957.10.1.el7.x86_64 nodejs/node#1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux Centos 7.6.1810

* **Subsystem**: node_http_parser.cc

Hi,

I get the following crash from time to time (we got it Twice on production  in september and March 31th ):

    
    node[1210]: ../src/node_http_parser.cc:418:static void node::{anonymous}::Parser::Execute(const 
    v8::FunctionCallbackInfo<v8::Value>&): Assertion `(Buffer::HasInstance(args[0])) == (true)' failed.
    1: 0x8f9d10 node::Abort() [node]
    2: 0x8f9de5  [node]
    3: 0x963d91  [node]
    4: 0x27282e5878a1

We had this bug also on dev environment but yet we have no clue  to reproduce it.
We have no log from the Js script when the crash occured.

What is very strange is that the process core dump  alway 4 times in a short period of time  (on production and on dev).

We looked at the similar issue already declared but we didn't  find any connection to our case.

You'll find the core dump attached.
[ccpp-2020-03-30-17.zip](https://github.com/nodejs/node/files/4421158/ccpp-2020-03-30-17.zip)

**Comment by addaleax** [comment]
@yanou75pro Right – the `'data'` event on streams takes a single `Buffer` as an argument, not an array of `Buffer`s. It looks like that’s what’s going wrong here, at least on an immediate level. Using `Buffer.concat()` might be a straightforward fix for this, although tbh it’s very concerning that you’re emitting `data` events directly – you probably shouldn’t do that and are bound to run into more trouble with it.

> By the way, I would be interested to know how you did to get so quickly information on where the program crashed.
I get headache for 2 days trying to get interesting information from this core file.

https://github.com/nodejs/llnode is very helpful for this – basically, `llnode <node binary> <core dump>` loads the core file, `v8 bt` gives you a meaningful stack trace for both C++ and JS frames.

**Comment by yanou75pro** [comment]
Thank you very much. 

I close the issue.
