### ISSUE TITLE
Installer does not install?

### ISSUE THREAD

**Issue by VickoLand** [nodejs/help#2575]
* **Node.js Version**: Node-v12.16.1
* **OS**: MacOs Mojave
* **Scope**: Install

Hello, I downloaded the Nodejs installer for mac from the website. After finishing the installation which shows as if successfully installed, I can't find it in the destination directory (the one mentioned during the installation)
There's nothing inside my .local directory
Could you help me please?

**Comment by padamata** [comment]
I have also downloaded the installer for the macOS Catalina and it is saying the nodejs is not supported to this version can someone help me in this

**Comment by HarshithaKP** [comment]
@VickoLand, Can you do `which node` and `ls /usr/local/bin` in terminal ? and let me know what it says.

**Comment by VickoLand** [comment]
> @VickoLand, Can you do `which node` and `ls /usr/local/bin` in terminal ? and let me know what it says.

I tried installing node a couple of days after and it worked thank you!
