### ISSUE TITLE
How to include js file in ejs?

### ISSUE THREAD

**Issue by azartheen** [nodejs/help#2576]
I am using nodejs login and signup page with my custom TWO FACTOR AUTHENTICATION  over thee backend of MongoDB 

i need to include as a server-side  on my home page (home.ejs) i tired to many ways but i cannot get the correct output 

Anyone help me

**Comment by ljharb** [comment]
I don't think this has anything to do with modules, fwiw - ejs isn't a module format, it's a template format, and you'd generally use an EJS library or similar to render the template contents.

I think a more appropriate place to file this issue is on the repo for whatever EJS tool you're using.

**Comment by gireeshpunathil** [comment]
closing this as answered, pls re-open if you think anything is outstanding here
