### ISSUE TITLE
Transform Stream in Object mode for input and output

### ISSUE THREAD

**Issue by alexanderankin** [nodejs/help#2577]
I am trying to write a stream that will take in objects from the pipe and send new objects to the output.

```js
var { Transform } = require('stream');
var v = new Transform({ objectMode: true, transform: (ch, e, d) => d(null, ch.values()) });
var sum = new Transform({ writableObjectMode: true, transform: (ch, enc, cb) {
  /* complex logic, count objects print lines */
} });
process.stdin.pipe(require('csv-parser')).pipe(v).pipe(sum).pipe(process.stdout);
```

I cannot get the `v` stream to behave like it can output objects, it keeps saying that the callback must take a buffer or string.

My immediate fix is to print tab separated values, tab is a character not present in these files but i was wondering what the official solution is.

**Comment by Hakerh400** [comment]
What is the `s` variable (from `pipe(s)`)? Where have you defined it? Or is it just the `v` stream?

The first argument of a stream callback is an error, so `d(ch.values())` is telling the stream that an error has occured. You probably want `d(null, ch.values())`. See this simplified example:

```js
const {Transform, PassThrough} = require('stream');
const v = new Transform({objectMode: true, transform(ch, enc, cb){
  cb(null, ch.values());
}});
const sum = new Transform({writableObjectMode: true, transform(ch, enc, cb){
  cb(null, `${ch.reduce((a, b) => a + b, 0)}\n`);
}});
const a = new PassThrough({objectMode: true});
a.pipe(v).pipe(sum).pipe(process.stdout);
a.write({values: () => [1, 2, 3, 4]});
```

**Comment by alexanderankin** [comment]
meant v sorry

**Comment by alexanderankin** [comment]
huh how did i not get this to work? thanks for the tip.

**Comment by alexanderankin** [comment]
for anyone reading this later, the `csv-parser` module will give you objects, and so what i was thinking of was `Object.values(ch)`, which would make my complete example:

```js
var { Transform } = require('stream');
var v = new Transform({ objectMode: true, transform: (ch, e, d) => d(null, Object.values(ch)) });
var sum = new Transform({ writableObjectMode: true, transform: (ch, enc, cb) {
  cb(null, `${ch.reduce((a, b) => a + b, 0)}\n`);
} });
process.stdin.pipe(require('csv-parser')).pipe(v).pipe(sum).pipe(process.stdout);
```
