### ISSUE TITLE
Errors are no longer emitted on stdout starting from v13.x

### ISSUE THREAD

**Issue by ryzy6** [nodejs/help#2578]
when we updated nodejs from v12 to v13 we noticed that errors that occur in streams that are piped to stdout no longer displayed if not caught

```
var s = new (require('stream')).PassThrough({objectMode: true});
s.pipe(process.stdout);
s.write({});
```

^ this was throwing error in v12, but not in v13

we bisected to https://github.com/nodejs/node/commit/4a2bd69db99c1bb8692e1f653edcb225fbc23032, which is semver major so it makes sense

but reading the changelog does not seem to say anything related to this situation. we just want to confirm that this behavior is correct and intentional?

if working as intended, what is the solution in this situation? To explicitly attach `process.stdout.on('error', error => {throw error})` listener? we developed the entire code base on the assumption that uncaught errors will crash the process. but since errors are swallowed now, is there an easy way to work around this?

**Comment by bnoordhuis** [comment]
cc @ronag

**Comment by ronag** [comment]
I believe this is by design and the previous behavior was a bug. Why this is the expected behaviour I believe @addaleax can give some more insight into.

See, https://github.com/nodejs/node/blob/master/lib/internal/console/constructor.js#L216.

Basically we don't want `console.log` to be able to crash the process. Whether that should apply to `process.stdout` as well I'm unsure.

**Comment by addaleax** [comment]
@ronag This doesn’t appear like the expected behavior to me – I’d expect an exception trying to pipe an object to `process.stdout`.

That being said, this seems to be fixed on master. Given that Node 13 soon goes out of support, maybe we should add a regression test and call it a day?

**Comment by ronag** [comment]
> I’d expect an exception trying to pipe an object to process.stdout.

You right. Emitting an error is not expected, but throwing is. This was fixed in https://github.com/nodejs/node/pull/31831.

**Comment by ryzy6** [comment]
thanks
