### ISSUE TITLE
different error codes between kubuntu/manjaro while executing command

### ISSUE THREAD

**Issue by kinghat** [nodejs/help#2579]
* **Node.js Version**: 13.12.0
* **OS**: kubuntu/manjaro
* **Scope (install, code, runtime, meta, other?)**: runtime

im trying to figure out why i get two different error codes when executing the same command on kubuntu vs manjaro which use the same shell. i have code `127` handled for when command is not found on kubuntu but why would the error code on manjaro be returning `1`?
```js
return (
	await Promise.all(
		BROWSERS_DATA.flatMap((browser) => browser.linux.aliases).map(async (browser) => {
			const childProcess = await exec(`command -v ${browser}`).catch((error) => {
				console.log("THE ERROR", error);
			});
			console.log(`LOG: getBrowsers -> childProcess`, childProcess);
		}),
	)
).filter(Boolean);
```
Kubuntu:

> THE ERROR Error: Command failed: command -v firefox-beta
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1026:16)
>     at Socket.<anonymous> (internal/child_process.js:441:11)
>     at Socket.emit (events.js:315:20)
>     at Pipe.<anonymous> (net.js:674:12) {
>   killed: false,
>   code: 127,
>   signal: null,
>   cmd: 'command -v firefox-beta',
>   stdout: '',
>   stderr: ''
> }
> LOG: getBrowsers -> childProcess undefined

Manjaro:

> THE ERROR Error: Command failed: command -v firefox-beta
> 
>     at ChildProcess.exithandler (child_process.js:295:12)
>     at ChildProcess.emit (events.js:210:5)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Socket.<anonymous> (internal/child_process.js:430:11)
>     at Socket.emit (events.js:210:5)
>     at Pipe.<anonymous> (net.js:659:12) {
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: 'command -v firefox-beta',
>   stdout: '',
>   stderr: ''
> }
> LOG: getBrowsers -> childProcess undefined

**Comment by gireeshpunathil** [comment]
because you are running this in two different OS's , the error codes as produced from those OS will be different.

https://docs.libuv.org/en/v1.x/errors.html

**Comment by gireeshpunathil** [comment]
closing as answered
