### ISSUE TITLE
cannot find module '/usr/bin/npm'

### ISSUE THREAD

**Issue by pagkly** [nodejs/help#2580]
* **Node.js Version**:10.17.0, also already tried the one downloaded from nodejs version 12 and 13
and the one from nvm all gave similar error
* **OS**:Kali Linux 2019.2 amd64
* **Scope (install, code, runtime, meta, other?)**:
cannot run npm at all
already reinstall kali, nodejs, and npm several times but same result
Kali linux 2019.2 arm64 with the same nodejs and npm version is working but not this one strangely

* **Module (and version) (if relevant)**: npm 6.14.3 same with 6.14.4

![image](https://user-images.githubusercontent.com/28628331/78528722-66aca380-7823-11ea-8b3e-70f83370cfc1.png)

**Comment by gireeshpunathil** [comment]
can you share the output of:
`which node`
and 
`which npm` ?

**Comment by ochen1** [comment]
I'm having the same issue. `which node` and `which npm` output `/usr/bin/node` and `/usr/bin/npm` respectively.

I'm running node inside a chroot (proot), so I think that may be the reason.

**Comment by RehanPlayz** [comment]
I can install NodeJS and NPM fine using the apt install nodejs npm command but the version is really outdated so I used the NodeSource PPA to install the latest version but I'm getting this issue with NPM

**Comment by RehanPlayz** [comment]
Let me know if anyone finds a solution

**Comment by ulrichard** [comment]
Yes, same issue when installed inside a fakechroot chroot.
