### ISSUE TITLE
500 Internal Error for any https://nodejs.org/dist/

### ISSUE THREAD

**Issue by bogomazov** [nodejs/help#2581]
Website is down, we cant nvm install any node version
https://nodejs.org/dist/ check any version

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by dborishansky** [comment]
Reported several times here as well: https://github.com/nodejs/nodejs.org/issues

**Comment by bnoordhuis** [comment]
Closing as resolved.
