### ISSUE TITLE
doc: No explanation of exports vs module.exports

### ISSUE THREAD

**Issue by ghost** [nodejs/help#2582]
Both `exports` and `module.exports` are introduced in https://nodejs.org/docs/latest-v10.x/api/modules.html#modules_modules, but the difference between them (if any), i.e. why you'd use one and not the other (if that's so), isn't explained.

**Comment by PoojaDurgad** [comment]
@willnwhite - is this still outstanding?

**Comment by willnwhite** [comment]
I think the section I linked to should link to the section sam-github linked to. Perhaps the link could say something like "The relationship between exports and module.exports is explained in the exports shortcut subsection."

**Comment by preveen-stack** [comment]
> I think the section I linked to should link to the section sam-github linked to. Perhaps the link could say something like "The relationship between exports and module.exports is explained in the exports shortcut subsection."

Would you mind raising a PR for this @willnwhite

**Comment by RedYetiDev** [comment]
Author is @ghost
