### ISSUE TITLE
Strange behavior between setTimeout / Promise Resolution / Native Addon which uses libuv

### ISSUE THREAD

**Issue by JCMais** [nodejs/help#2586]
* **Node.js Version**: v13.12.0 and v12.16.1
* **OS**: Windows x64 (But happens elsewhere)
* **Scope**: code / runtime
* **Module**: node-libcurl@2.1.0-3

As I don't know if this is really a Node.js bug or something wrong with the addon code, I'm posting here first. I'm the author of the [`node-libcurl`](https://github.com/JCMais/node-libcurl) native addon and some time ago an issue came up with some really weird behavior.

## Steps to reproduce:

1 - First install the addon:
```shell
yarn add node-libcurl@2.1.0-3
```

2 - Run the code:
```js
const { Curl } = require('node-libcurl')

const startTime = process.hrtime()

setTimeout(() => {
  console.log('[%d.%ds] - setTimeout callback', ...process.hrtime(startTime))
}, 15000)
const makeCall = () =>
  new Promise((resolve, reject) => {
    const curl = new Curl()

    curl.setOpt('URL', 'http://localhost:8080')
    curl.setOpt('CONNECTTIMEOUT', 1)
    curl.setOpt('TIMEOUT', 1)

    curl.on('error', () => {
      console.log(
        '[%d.%ds] - on error: before reject',
        ...process.hrtime(startTime),
      )
      curl.close()
      reject()
      console.log(
        '[%d.%ds] - on error: after reject',
        ...process.hrtime(startTime),
      )
    })

    curl.on('end', () => {
      console.log(
        '[%d.%ds] - on end: before resolve',
        ...process.hrtime(startTime),
      )
      curl.close()
      resolve()
      console.log(
        '[%d.%ds] - on end: after resolve',
        ...process.hrtime(startTime),
      )
    })

    console.log('[%d.%ds] - before perform', ...process.hrtime(startTime))
    curl.perform()
    console.log('[%d.%ds] - after perform', ...process.hrtime(startTime))
  })

makeCall()
  .then(() =>
    console.log(
      '[%d.%ds] - promise resolved: no error',
      ...process.hrtime(startTime),
    ),
  )
  .catch((error) =>
    console.error(
      '[%d.%ds] - promise resolved: error',
      ...process.hrtime(startTime),
    ),
  )

```

## Expected:
As the libcurl request is being made against `http://localhost:8080` which probably does not exists locally, and the CONNECTTIMEOUT is set to 1, the request is going to fail fast, so the promise then/catch callback should be called right after resolve/reject is called

## Current Behavior:
Promise then/catch callback takes a really long time to be executed after resolve/reject is called, when running on my machine this time is consistently around 8s after resolve/reject is called, here is the output:
```
[0.1382900s] - before perform
[0.5620600s] - after perform
[0.726592500s] - on error: before reject
[0.727835099s] - on error: after reject
[8.119500200s] - promise resolved: error
[15.1750300s] - setTimeout callback
```

Weirdly enough, if I place a `setImmediate(() => {})` call inside the end/error event callbacks, like so:
```js
    curl.on('error', () => {
      setImmediate(() => {})
      console.log(
        '[%d.%ds] - on error: before reject',
        ...process.hrtime(startTime),
      )
      curl.close()
      reject()
      console.log(
        '[%d.%ds] - on error: after reject',
        ...process.hrtime(startTime),
      )
    })

    curl.on('end', () => {
      setImmediate(() => {})
      console.log(
        '[%d.%ds] - on end: before resolve',
        ...process.hrtime(startTime),
      )
      curl.close()
      resolve()
      console.log(
        '[%d.%ds] - on end: after resolve',
        ...process.hrtime(startTime),
      )
    })
```

The promise is resolved/rejected immediately:
```
[0.1685899s] - before perform
[0.5027599s] - after perform
[0.722392200s] - on error: before reject
[0.723412399s] - on error: after reject
[0.724483799s] - promise resolved: error
[15.1817100s] - setTimeout callback
```

This is also the case if the `setTimeout` is removed, the promise then/catch is called immediately after resolve/reject.

I've tried my best to debug this, but debugging time-sensitive issues is really cumbersome, and I'm out of ideas on what might be causing this.

The addon makes heavy use of libuv internally, most of the addon code that is probably related to this issue is in the file [`src/Multi.cc`](https://github.com/JCMais/node-libcurl/blob/v2.1.0-3/src/Multi.cc).

This is all based on the libcurl usage in an event-based way, see the following links for more details:
https://curl.haxx.se/libcurl/c/libcurl-multi.html (`MULTI_SOCKET` section)
https://curl.haxx.se/libcurl/c/curl_multi_socket_action.html

**Comment by bnoordhuis** [comment]
You're using `Nan::Call()`. Try `Nan::MakeCallback()` instead.

The former is a wrapper around `v8::Function::Call()` and doesn't drain microtask and nexttick queues, etc.

**Comment by JCMais** [comment]
@bnoordhuis thank you so much for that insight, it worked.

I've looked into the `Nan::MakeCallback()` and as it's deprecated, I've used `AsyncResource` directly, so basically, I've replaced [this code](https://github.com/JCMais/node-libcurl/blob/c0bc54128d01d6be3142401dd02a67b1ea45941d/src/Multi.cc#L288):
```cpp
  Nan::Call(*(this->cbOnMessage), obj->handle(), argc, argv);
```

with
```cpp
  Nan::AsyncResource resource("Multi::CallOnMessageCallback");
  resource.runInAsyncScope(obj->handle(), this->cbOnMessage->GetFunction(), argc, argv);
```

I'm going to replace all other uses `->Call` with the `runInAsyncScope` call to avoid any other issues.

**Comment by JCMais** [comment]
@bnoordhuis reading this gave me some doubts: https://github.com/nodejs/nan/pull/747#discussion_r173544959

Should I create the `AsyncResource` when the `onMessage` callback is first stored then? Otherwise the context is going to be lost like said on the comment above by @ofrobots
