### ISSUE TITLE
Terminal/Win Powershell not recognizing npm or node commands

### ISSUE THREAD

**Issue by timmythecat** [nodejs/help#2588]
* **Node.js**: 12.16.1
* **OS**: Windows x64
* **Scope**: 
* **Module (and version) (if relevant)**:

I keep running into this problem after opening a new application that run these commands (things like windows powershell and i've reinstalled a few times

node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check     the spelling of the name, or if a path was included, verify that the path is correct and try again.                     At line:1 char:1                                                                                                        + node --version                                                                                                        + ~~~~                                                                                                                      + CategoryInfo          : ObjectNotFound: (node:String) [], CommandNotFoundException                                    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by PoojaDurgad** [comment]
@timmythecat -
- what command you are trying to run? does it work fine in start cmd? 
- what is the output of `where node` in cmd prompt or `which node` in powershell

> Check the spelling of the name, or if a path was included, verify that the path is correct and try again

check that the output of `where node` I mean the path is included in the environment variable or not. if that is not the case ,update the path and restart your powershell . Hope it may help.

**Comment by timmythecat** [comment]
the problem seems to have fixed itself a while ago and I'm no-longer running into that issue.

**Comment by PoojaDurgad** [comment]
closing as resolved. feel free to reopen if it is necessary.

**Comment by Umer919** [comment]
i am having the same error on running command npm start and node -v in Vs code terminal, i have installed all the dependencies in my project
Type = React Native
