### ISSUE TITLE
How to create an string and get bytelengh  in node.js core ? (use c++)

### ISSUE THREAD

**Issue by hanrea** [nodejs/help#259]
Hi~gays:
       I'm writing a c++ addon , I need to creat `const char*` string  value ,and get it's length.  

CODE  here:(c++)

``` c++
const char * cstr = "abcdef";
    Local<String> str = OneByteString(args.GetIsolate(), cstr);
    ssize_t srLen = Buffer::Length(str.As<Value>());
```

In Buffer::Length function:

``` c++
size_t Length(Local<Value> val) {
  CHECK(val->IsUint8Array());
  Local<Uint8Array> ui = val.As<Uint8Array>();
  return ui->ByteLength();
}
```

CHECK(val->IsUint8Array()); this function will be shutdown Assertion failed: val->IsUint8Array()

how to know this object is Uint8Array? and how to create?
Thanks!

**Comment by addaleax** [comment]
Well, one thing you can do is just use `size_t length = strlen(cstr)`.

You can create `Buffer` instances from `const char*` using `Buffer::Copy` and `Buffer::New`, but for that, you’ll have to know the byte length beforehand, so you’d probably have to use `strlen()`, too.

**Comment by hanrea** [comment]
Thanks @addaleax ,I know `strlen()` function ,but it are argument (See below).  other ,`sizeof()` will read object pointers .  I want read  vlaue->ByteLength(). 

Although the problem has been solved, but I do not understand why new Local<Value> not is Uint8Array, and how create a new Local<Value> can use Buffer::length().  

Another , `Buffer::Copy` need to know length in arguments.

strlen() will get inaccurate value:
```c++
	char str1[] = "abcdefig";
	char str2[] = "01234\056789";
	char str3[] = "abcse\0fgkij";
	printf("strlen(str1)=%d\n", strlen(str1));
	printf("strlen(str2)=%d\n", strlen(str2));
	printf("strlen(str3)=%d\n", strlen(str3));
Echo
	strlen（str1） = 8
	strlen（str2） = 9
	strlen（str3） = 5
```

**Comment by addaleax** [comment]
@hanrea I’m afraid `value->ByteLength()` can’t help you here – using something like `OneByteString()` also uses `strlen()` to get the string length internally.

> Although the problem has been solved, but I do not understand why new Local not is Uint8Array

A `Local<String>` is not a Uint8Array, just like it is on the JS side:
`'abcdef' instanceof Uint8Array === false`.

> , and how create a new Local can use Buffer::length(). 

If you want an `Uint8Array` or an `ArrayBuffer`, you’ll need to create that using `ArrayBuffer::New`. But for that, you’ll also need to know the length beforehand.

> strlen() will get inaccurate value:

Yes, and in C/C++, there’s simply no way around that. You either *know* how long your string is in the first place, or you need to look for the terminating `\0` byte using `strlen()` and accept that anything after a `\0` byte in the string gets truncated.
