### ISSUE TITLE
Nodejs problems

### ISSUE THREAD

**Issue by montelin** [nodejs/help#2595]
Hello,
I need help with nodejs. Please watch the attached movie.

https://bildnet.info/node.mp4

**Comment by addaleax** [comment]
The link you provided 404s. That being said, a description of your problem is probably more helpful than a video.

**Comment by montelin** [comment]
Hello,
I don't get nodejs to work. Have installed and when I should check the version on node and npm it just flashes and cmd window opens and flashes, and then go back to the starting position. Have tried everything.

**Comment by PoojaDurgad** [comment]
@montelin - is this still an issue? the attached link what you provided is currently not found for me. so can you elaborate your issue more please? so that it will be helpful for me to debug your issue. like which os you are using? what version of nodejs you are running?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
