### ISSUE TITLE
Command Line Options (--unhandled-rejections)

### ISSUE THREAD

**Issue by raziEiL** [nodejs/help#2596]
* **Node.js Version**:v12.16.1
* **OS**:win10
* **Node command line**: `node -r dotenv/config --unhandled-rejections=strict index.js` 

I got UnhandledPromiseRejectionWarning but I want to terminate the node process on unhandled promise rejection. If I remove `-r` option:  `node --unhandled-rejections=strict index.js` everything works as it should. So, how to use `-r` and `--unhandled-rejections` options  together?

**Comment by gireeshpunathil** [comment]
@raziEiL - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
