### ISSUE TITLE
trap invalid opcode ip

### ISSUE THREAD

**Issue by kjdamy** [nodejs/help#2597]
Today, the server suddenly crashes. There is no dumpcore, only the following is found. CPU and memory monitoring seem to be normal：
node10.15.3           
kernel: traps: node[9573] trap invalid opcode ip:16cdea9 sp:7ffcc78c3aa8 error:0 in node[400000+1e96000]

**Comment by gireeshpunathil** [comment]
@kjdamy - is this still an issue? which os? which node version? can you run with `ulimit -c unlimited` set on the shell prior to the run, so that a core dump is captured?
