### ISSUE TITLE
child_process & workers sending strings?

### ISSUE THREAD

**Issue by ronag** [nodejs/help#2598]
When sending string to worker is that string copied or is just the reference sent over similar to ArrayBuffer?

**Comment by addaleax** [comment]
@ronag I’m not sure if you’re referring to “worker” as in “Worker threads”, but either way, strings are fully copied both for child processes and for Worker threads. ArrayBuffers are copied too, by default, unless explicitly transferred.

**Comment by ronag** [comment]
Thanks. That answers my question.
