### ISSUE TITLE
Is this posible/reachabe code?

### ISSUE THREAD

**Issue by juanarbol** [nodejs/help#2600]
* **Node.js Version**: current
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: current

```c++
// src/node_os.cc:133
static void GetFreeMemory(const FunctionCallbackInfo<Value>& args) {
  double amount = uv_get_free_memory();
  if (amount < 0) // This
    return;
  args.GetReturnValue().Set(amount);
}
```
Is it possible to have `amount < 0` ? Based on libuv codebase (at least on LINUX), the free mem (also total mem) is taken from `/proc/meminfo`, based on that, is it possible to have a negative amount?

**Comment by gireeshpunathil** [comment]
@juanarbol - may be this, for example? https://github.com/libuv/libuv/blob/2ab3dc1567d67924b634be6f478d25f4528ce574/src/unix/darwin.c#L101

**Comment by juanarbol** [comment]
Yeap, I think it is a possible "non-positive amount", in that case, don't you think that we should provide a better error handling on the implementation? I mean, at least use `CHECK_GT` or something like that...

I don't know, this is just a proposal because I don't know why we are dealing with invalid amount in this way.

**Comment by gireeshpunathil** [comment]
> don't you think that we should provide a better error handling on the implementation?

@juanarbol - makes sense to me! but throw an exception that carries the original `libuv` error message, with a doc update, instead of `CHECK_GT`?

**Comment by juanarbol** [comment]
Yeap, it is a better approach, I think that:

```cc
if (amount < 0) {
  return uv_err_name(amount);
}
```

But amm... the free memory method is `void` so that won't work, and I don't know how to throw an exception with a given `FunctionCallbackInfo`

**Comment by gireeshpunathil** [comment]
here is a recent PR which did a similar thing: you need to:

 - get the error message from libuv,
 - compose a full exception message with that,
 - define a new error type if need be, in `src/node_errors.h`
 - and throw

https://github.com/nodejs/node/pull/32344/files#diff-853c968290ed44d71c73689242b1fab4R648-R661

/cc @addaleax for a better suggestion!

**Comment by bnoordhuis** [comment]
> Is it possible to have `amount < 0`? 

No, because the return type of `uv_get_free_memory()` is `uint64_t`, i.e, an unsigned value. Those are always `>= 0`.

**Comment by juanarbol** [comment]
Thanks for the support! I'm closing this issue now.
