### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Stefqnutz** [nodejs/help#2601]
Hello everyone, this is my first post on here, I was working on a small project and im almost done with it but I ran into this problem, I was working on a node.js code and everything is great so far but Im getting this error: SyntaxError: Unexpected token '.'

This is my code:
var websocket = require('websocket');

var ws = require('ws');

var WebSocket = require('ws')

var http = require('http');

var server = http.createServer(function (request, response) {
  console.log(request.url);
});

var master = require('master-server')
 

var connector = new master.Connector({ 
    ip: '127.0.0.1', 
    port: 3333, 
    password: 'my password', 
    onConnect: () => {   
        connector.send({
            connector.send('{"payload":{"state":"Connecting"},"name":"StatusUpdate"}');
            connector.send('{"payload":{"totalPlayers":1,"connectedPlayers":1,"state":"Connecting"},"name":"StatusUpdate"}');
            connector.send('{"payload":{"ticketId":"TICKET_ID","queuedPlayers":1,"estimatedWaitSec":0,"status":{},"state":"Queued"},"name":"StatusUpdate"}');
            connector.send('{"payload":{"matchId":"f31ce23e4201430ebed925a98c73d036","state":"SessionAssignment"},"name":"StatusUpdate"}');
            connectoar.send('{"payload":{"matchId":"f31ce23e4201430ebed925a98c73d036","sessionId":"f31ce23e4201430ebed925a98c73d036"},"name":"Play"}')};

        // Service has successfully closed.
        connector.close(1000, 'service.success.0');

}

Sorry for the unorganized code but I really need help, my node.js version is v13.11.0

**Comment by Hakerh400** [comment]
You have unmatched parentheses in your code. All open parentheses must be closed. This also applies to brackets and braces.

What are you trying to achieve? According to the [master-server package](https://github.com/timetocode/master-server/blob/0f47697bbbe9b77ffb587c10ed0ad5abaa4f1e9c/Connector.js), method `Connector.prototype.send` returns void, so the result of `connector.send` call cannot be passed to another `connector.send` call.

Why have you required `ws` module two times and assigned it to two different variables? What is the `connectoar` variable? Shouldn't it be `connector`?

You probably have a better chance of getting more detailed help if you ask on [their repo](https://github.com/timetocode/master-server/issues) instead.

**Comment by gireeshpunathil** [comment]
@Stefqnutz - is this resolved?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
