### ISSUE TITLE
[Seeking Clearity] The NodeJS Event Loop

### ISSUE THREAD

**Issue by OPARA-PROSPER** [nodejs/help#2602]
## Summary

I checked out the explanation for the event loop on (https://nodejs.dev/the-nodejs-event-loop) and is based off heavily on the browsers event Loop. The NodeJS documentation (https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/) offers a totally different explanation of the event loop based off Libuv (Including the different event loop phases).

I'm having issues reconciling both.

**Comment by bnoordhuis** [comment]
> Is Libuv event loop implementation similar to the browser event loop implementation?

An event loop at its core is a mechanism for dispatching notifications to interested parties, so yes, in that respect they're similar.

**Comment by OPARA-PROSPER** [comment]
Thanks @Trott @bnoordhuis for your effort in answering my questions.

It makes sense now.
