### ISSUE TITLE
util inspect covert function to [Function]

### ISSUE THREAD

**Issue by AruXc** [nodejs/help#2604]
* **Node.js Version**: 12.16.2
* **OS**: MacOs
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

```js
const obj = {a: 123, b() {}, c: { d: { e: { f: {}, g: '123'}}}}

fs.writeFile('./static/schema/test.js', `module.exports = ${util.inspect(obj, { depth: null})}`, () => null)

```

It's will get 
```
module.exports = {
  a: 123,
  b: [Function: b],
  c: { d: { e: { f: {}, g: '123' } } }
}
```

How should I do that get key `b` function correctly  just like `b() {}`

**Comment by addaleax** [comment]
@AruXc `util.inspect()` is not supposed to provide JS code that would allow one to create equivalent objects, and instead intended to give easily human-readable output. As part of that tradeoff, functions are printed  as `[Function name]`, and the function’s code is omitted (as that can be quite large).

It sounds to me like `util.inspect()` might not be what you are looking for, but I’m not sure what kind of tool would give you the exact same output as the object you originally wrote. It might help if you could describe what your goal is here.

**Comment by AruXc** [comment]
@addaleax Thanks for your response, I want to merge multiple object schema that spread in multiple js file, and the last step is use ‘writeFile’ to merge schema in one js file.

You’re right, but I still need completely function after use ‘until.inspect’ , so I give up to use ‘until.inspect’, and create a function to convert object to string by myself.
