### ISSUE TITLE
How to cancel request and return a timeout error if request takes more than a particular time

### ISSUE THREAD

**Issue by abdul-rahman052** [nodejs/help#2605]
Hi,
I want to write an API which will return an error if the excution takes more than a particular time otherwise will proceed normally. How to do that??

Regards,
Abdul

**Comment by addaleax** [comment]
Can you give an example of what your API would look like without a timeout mechanism? E.g. are you talking about an API that performs a HTTP request and uses async/await to return its results, or one that responds to an HTTP request, or something else?

**Comment by abdul-rahman052** [comment]
@addaleax I have written an REST API that fetch some data from another REST API. The process takes around 3-4 seconds. But if the API end point is not correct (from which my API i fetching data), it returns error after 2.5 minutes with message that endpoint is not correct. So i want to abort the request send response with an error message if it takes more than 30 seconds

**Comment by bnoordhuis** [comment]
There are several ways to skin that cat but arguably simplest is `req.setTimeout(30 * 1000, cb)` on the API endpoint request and have `cb` send an error to the client.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
