### ISSUE TITLE
npm security check issue

### ISSUE THREAD

**Issue by asrivastava2017** [nodejs/help#2606]
* **Node.js Version - 12.16.1**:
* **ubuntu**:
* **npm audit cli**:
* ****:

While running npm audit I am experiencing below error :

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/jenkins/.nvm/versions/node/v12.16.1/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'audit'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.1
4 verbose npm-session 164c38f979bfe542
5 http fetch POST 500 https://registry.npmjs.org/-/npm/v1/security/audits 325ms
6 verbose stack Error: Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.
6 verbose stack     at /home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/lib/audit.js:204:18
6 verbose stack     at tryCatcher (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
6 verbose stack     at Promise._settlePromiseFromHandler (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
6 verbose stack     at Promise._settlePromise (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
6 verbose stack     at Promise._settlePromise0 (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
6 verbose stack     at Promise._settlePromises (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)
6 verbose stack     at _drainQueueStep (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
6 verbose stack     at _drainQueue (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
6 verbose stack     at Async._drainQueues (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
6 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/home/jenkins/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
6 verbose stack     at processImmediate (internal/timers.js:456:21)
7 verbose cwd /home/jenkins/workspace/Mosaic/Build-Service/PR_Checks/mosaic-asset-mgmt-service
8 verbose Linux 4.4.0-1022-aws
9 verbose argv "/home/jenkins/.nvm/versions/node/v12.16.1/bin/node" "/usr/bin/npm" "audit"
10 verbose node v12.16.1
11 verbose npm  v6.14.4
12 error code ENOAUDIT
13 error audit Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.
14 verbose exit [ 1, true ]

May I know what could be the possible issue , because it was working perfectly fine till yesterday. Now its blocking our pipeline and deployments.

**Comment by asrivastava2017** [comment]
if someone can reply it will be a big help

**Comment by asrivastava2017** [comment]
HI Team,

Any update/info here yet ??

Thanks,
Animesh

**Comment by bdharrington7** [comment]
(not from the team, just a passer-by)

npm audit seems to be working fine now, I just checked with all the same versions you have in the logs. Did you try again recently?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
