### ISSUE TITLE
Socket factory method for net.Server

### ISSUE THREAD

**Issue by fu-hsi** [nodejs/help#2607]
**Is there factory method for creating self derived socket object?**
For example, now I must use decorator pattern:

```js
class MySocket {
    constructor(socket) {
        this._socket = socket
    }
}

class MyServer extends net.Server {
    constructor() {
        super((socket) => {
            let mySocket = new MySocket(socket)
            // but internal, Server store only Socket objects
        })
    }
}
```

I want use class extending instead of decorator, it would be nice to see some Dependency Injection pattern or something like this:

```js
class MyServer extends net.Server {
    constructor() {
        super((socket) => {
            // socket is MySocket now
        })
    }
}

let myServer = MyServer((socketFactory) => {
    let socket = new MySocket()
    // initialization
    return socket
    // or return 'MySocket'
}) {
}
```

Or did I miss something?

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because as a question it's reasonable but as a feature request, it's not something that'll show up in node core.
