### ISSUE TITLE
Proper fs.close w/ nested fs.open

### ISSUE THREAD

**Issue by squarewav** [nodejs/help#2608]
What is considered to be the "correct" way to properly execute cleanup conditions with nested open calls? Specifically, it seems to me there are great opportunities to leak file descriptors in JS if you're not careful. Does the following code exemplify how this should be done? For example, I presume it's ok to just ignore the close callbacks? Otherwise, this could get out-of-hand quickly.
```js
const fs = require('fs');

({
    doProperClose: function (callback) {

        fs.open('hello.txt', (err, fd0) => {
            if (err) return callback(err);

            console.log('fd0:', fd0);

            fs.open('hello.txt', (err, fd1) => {
                if (err) {
                    fs.close(fd0, (cerr) => {});
                    return callback(err);
                }

                console.log('fd1:', fd1);

                fs.open('XXXhello.txt', (err, fd2) => {
                    if (err) {
                        fs.close(fd0, (cerr) => {});
                        fs.close(fd1, (cerr) => {});
                        return callback(err);
                    }   
        
                    console.log('fd2:', fd2);

                    fs.close(fd2, (cerr) => {});
                    fs.close(fd1, (cerr) => {});
                    fs.close(fd0, (cerr) => {});

                    return callback();
                });
            }); 
        }); 
    }   
}).doProperClose((err) => {
    if (err)
        return console.log(err);
    console.log('success');
});
```

**Comment by addaleax** [comment]
> For example, I presume it's ok to just ignore the close callbacks? Otherwise, this could get out-of-hand quickly.

There’s not much that you can do with a possible error besides to log it, yes.

**Comment by squarewav** [comment]
Yup. Just thought there might be a clever option like using throw somehow. But I suppose this is about as clean as it's going to get with a declarative language.

**Comment by bnoordhuis** [comment]
If you use the promisified version of `fs.open()` you can do something like this:
```js
async function go() {
  let fd1;
  let fd2;
  try {
    fd1 = await fs.open('hello.txt');
    fd2 = await fs.open('XXXhello.txt');
    // do something with fd1 and fd2
  } finally {
    if (fd2 !== undefined) await fs.close(fd2);
    if (fd1 !== undefined) await fs.close(fd1);
  }
}
```
You can wrap `fs.close(fd2)` in a try/catch block if you're worried about errors.

Then again, that probably means something is wrong with the program. I'd just let the exception bubble up and terminate.

**Comment by gireeshpunathil** [comment]
@squarewav - is this resolved?

**Comment by gireeshpunathil** [comment]
closing as answered, pls re-open if this is outstanding
