### ISSUE TITLE
net.js:1474     throw new ERR_INVALID_ARG_VALUE('options', options,     ^  TypeError [ERR_INVALID_ARG_VALUE]: The argument 'options' must have the property "port" or "path". Received Server {   _events: [Object: null prototype] {     request: [Function: app] EventEmitter {       _events: [Object: null prototyp...     at Server.listen (net.js:1474:11)     at Object.<anonymous> (A:\Node js\Trail\Example\app.js:96:24)     at Module._compile (internal/modules/cjs/loader.js:959:30)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)     at Module.load (internal/modules/cjs/loader.js:815:32)     at Function.Module._load (internal/modules/cjs/loader.js:727:14)     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)     at internal/main/run_main_module.js:17:11 {   code: 'ERR_INVALID_ARG_VALUE' }

### ISSUE THREAD

**Issue by Chitturiarunkrishna** [nodejs/help#2612]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

This is my code
var express = require('express');
var routes = require('./routes');
var http = require('http');
var path = require('path');
var urlencoded = require('url');
var bodyParser = require('body-parser');
var json = require('json');
var logger = require('logger');
var methodOverride = require('method-override');
var nano = require('nano')('http://localhost:5984/');
var db = nano.use('address');

var app = express();
app.set('port', process.env.PORT || 3000);
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true}));
// app.use(express.urlencoded({ extended: true }))
app.use(methodOverride());
app.use(express.static(path.join(__dirname, 'public')));

app.get('/',routes.index);

app.post('/createdb', function(req,res)
{
    nano.db.create(req.body.dbname, function(err)
    {
        if(err)
        {
            res.send("Error creating databse"+req.body.dbname);
            return;
        }
        res.send("Datbase"+req.body.dbname+"created successfully");
    });
});

app.post('/new_contact', function(req,res)
{
    var name = req.body.name;
    var phone = req.body.phone;
    db.insert({name:name, phone:phone, crazy:true}, phone, function(err,body,header)
    {
        if(err)
        {
            res.send("Error inserting contact");
            return;
        }
        res.send("Contact created successfully");
    });
});

app.post('/view_contact', function(req, res)
{
    var alldoc = "Following are the contacts"
    db.get(req.body.phone, {revs_info:true}, function(err,body)
    {
        if(!err)
        {
            console.log(body);
        }
        if(body)
        {
            alldoc+= "Name: "+body.name+"<br/>Phone number: "+body.phone;
        }
        else
        {
            alldoc="No records found";
        }
        res.send(alldoc);
    });
});

app.post('/delete_contact', function(req,res)
{
    db.get(req.body.phone, {revs_info:true}, function(err,body)
    {
        if(!err)
        {
            db.destroy(req.body.phone, body._rev, function(err, body)
            {
                if(err)
                {
                    res.send("Error deleting the contact");
                }
                else
                {
                    res.send("Contact deleted");
                }
            });
        }
    });
});

http.createServer(app).listen(app.listen('port'), function()
{
    console.log("Listening on port: "+app.get('port'));
});

**Comment by squarewav** [comment]
The error means pretty much what it says. Server.listen needs an object with a 'port' property. But you're passing the return value of app.listen('port') which is clearly not what you want. I don't use express and this is not a forum for that module either. But presumably you want something like .listen({ app.get('port') }) or maybe it looks like express has it's own idea of how to listen(). Again, I know nothing of express.

Also, you really should really format your message a little better with a sane subject, code tags and explicitly state what your question is. Most people would probably just skip a post like this because it's so poorly crafted.
