### ISSUE TITLE
Appium Package (WinAppDriver) Not Working with node-v12.16.2-x64.msi

### ISSUE THREAD

**Issue by ckimball875** [nodejs/help#2614]
While taking Marcel de Vries' first Pluralsight course on Appium, I attempted to do what he did on his computer, on my computer, by installing the Appium desktop (1.15.1), and then installing the "WindowsApplicationDriver.msi", and then also installing the latest stable version of Node.js, which appears to be 12.16.2 at this writing.

Then, when I attempted to ".Build()" the appium server, locally to my Automated UI Testing application, I got an "Unknown Server ... error", which suggested that I re-install "WinAppDriver".  After trying several times without success, and trying to uninstall and reinstall the Appium desktop, and the "...ApplicationDriver.msi", and "Node.js", I tweeted Marcel to see if he knew anything that might work to fix the problem.

He mentioned to me that he had the same issue with the pre-release version of Appium, but that by using the "latest stable" version it worked for him.

Well, I noticed that the ONLY difference between what he installed in his course, and what I installed, was the version of Node.js.  When he installed, it appears that the latest stable version was 12.14.1, but when I installed, a couple months later, the latest stable version was 12.16.2.

After I uninstalled 12.16.2, and got and installed version 12.14.1 of Node.js, everything is now working for me.

I can only surmise that the latest stable version of Node.js, and/or the Appium package associated with it, is no longer compatible with the latest version(s) of the Appium desktop, and/or the latest WinAppDriver, installable via .msi.

I have to use version 12.14.1 of Node.js, until I am confident that the latest stable version has been fixed relative to the WinAppDriver.

Any fix(es) would be greatly appreciated!  Thank you!

Charles Kimball

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help because this looks like a support question more than a bug report.

If you do have reason to believe it's a Node.js issue, you'll have to be a lot more specific in order for it to be actionable for us.

**Comment by ckimball875** [comment]
Thank you!

I am (REALLY) Not trying to be sarcastic, but - can you tell me what kind
of specifics you would need from me?

Thanks again!

Charlie Kimball

**Comment by bnoordhuis** [comment]
A good starting point would be to figure out whether this is actually an issue with Node.js, Appium or a third-party library (e.g., libraries you install through npm.)

If you have reasonable cause to believe it's Node.js, what's the last known-good version and what change in the next version looks like it could be responsible?

**Comment by ckimball875** [comment]
Thanks!  I'll start looking at that as soon as possible.

Charlie Kimball

**Comment by gireeshpunathil** [comment]
@ckimball875 - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive.
