### ISSUE TITLE
renative issue: 'rnv new' gets me error

### ISSUE THREAD

**Issue by benz0is** [nodejs/help#2616]
* **Node.js Version**:12.16.2
* **OS**:windows
* **Scope (install, code, runtime, meta, other?)**:install and runtime
* **Module (and version) (if relevant)**:

I try install renative with npm install rnv -g, and then try to run rnv new and get this error:
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Users\user\AppData\Roaming\npm\node_modules\rnv\bin\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []

**Comment by gireeshpunathil** [comment]
@benz0is - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
