### ISSUE TITLE
Passing arguments to a script using node.exe from the Windows command line

### ISSUE THREAD

**Issue by robertellisuk** [nodejs/help#2617]
* **Node.js Version**: 12.16.2
* **OS**: Win Server 2016
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:  Haraka

I think I must be missing something obvious but I cannot quite pin down what it is I'm doing wrong. I have Haraka installed, with a configuration that I'm happy with. I can start my Haraka instance by opening the Node.js command prompt and entering: 

`haraka -c C:\path\to\my\config
`

Now I would like to work out how to run this with exactly the same results but from the Windows command line rather than the Node.js command prompt.

To this end, I have tried various different syntax calling node.exe and the following has gotten me closest to where I want to be...

`"C:\Program Files\nodejs\node.exe" C:\path\to\npm\node_modules\Haraka\haraka.js -c C:\path\to\my\config
`

...but with this syntax, my haraka.js script is not recognising the '-c' switch and argument and is therefore not loading the configuration I want to use. The behaviour with this syntax is as if the '-c' switch isn't present at all.

I'm considering creating a 'bootstrap' script which calls haraka.js with the -c argument, and then calling that bootstrap script using node.exe.   However, before I go down that road, I wanted to try to find out if there is some simple modification to the syntax above that will do the job 'on a single line' ?

Many thanks

Robert

**Comment by Hakerh400** [comment]
Try this

`"C:\Program Files\nodejs\node.exe" "%appdata%\npm\node_modules\Haraka\bin\haraka" -c C:\path\to\my\config`

**Comment by robertellisuk** [comment]
Yes, Spot on. Thank you. Much appreciated.
