### ISSUE TITLE
Execute command line in javascript 

### ISSUE THREAD

**Issue by cba16** [nodejs/help#262]
Hello,
 I have a javascript program that runs on linux. It receives various data and I would like it to execute command lines (entering a folder+executing a program) when it receives specific data. 
 How can I do that on a javascript program? 
 Thanks (I hope I'm in the right place for that question!)

**Comment by addaleax** [comment]
Hi again – could you give a more specific example of what you are trying to do? The API for that, along with examples, is described in https://nodejs.org/api/child_process.html.

**Comment by lordKnighton** [comment]
sounds a bit of abstract but I think, you would want to read through the file system docs : https://nodejs.org/dist/latest-v4.x/docs/api/fs.html
