### ISSUE TITLE
Nodejs and MongoDB connection error with Express and Mongoose.

### ISSUE THREAD

**Issue by gedda68** [nodejs/help#2620]
* **Node.js Version**: v13.12.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: Mongoose 3.5.5
* **DB (and version) (if relevant)**: MongoDB v4.2.1 & Express v6.14.4

Looking at connecting my app code onto the Atlas MongoDB.  Naturally a very common task to do.  However, I keep having this issue when I restart my server.   So would like to see what I'm doing wrong here please from the knowledgeable community

**ERROR MESSAGE**
App running on port 8000... �
(node:21208) UnhandledPromiseRejectionWarning: Error: queryTxt EBADNAME cluster0-vedax.gcp.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:207:19)
(node:21208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a 
promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**server.js**
```js
const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config({ path: './config.env' });
const DB = process.env.DATABASE.replace('<PASSWORD>', process.env.PASSWORD);

mongoose
  .connect(DB, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false,
  })
  .then((con) => {
    console.log(con.connections);
    console.log('DB Connection successful');
  });

const app = require('./app');

// 4) START SERVER
const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`App running on port ${port}... 😃`);
});

const MongoClient = require('mongodb').MongoClient;

```

**config.env**
```js
NODE_ENV=development
PORT=8000
DATABASE=mongodb+srv://gedda:<PASSWORD>@cluster0-vedax.gcp.mongodb.net/natours?retryWrites=true&w=majority
DATABASE_LOCAL=mongodb://localhost:27017/natours
DATABASE_PASSWORD=xxxxxxxxxxxx
```

***EOF***

**Comment by gireeshpunathil** [comment]
@gedda68 -  is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
