### ISSUE TITLE
node 13.13 often returning null for connection.remoteAddress and connection.socket.remoteAddress

### ISSUE THREAD

**Issue by andrewhodel** [nodejs/help#2624]
Since they deprecated connection.remoteAddress, using connection.remoteAddress || connection.socket.remoteAddress often returns null.

This is for https.createServer and we are talking about the response object.

I am unsure if the tcp client is creating some strange socket or using some odd set of TCP flags.  Regardless, null is being returned often not the remoteAddress.

Please resolve this.

My boss hired some non-english speaking developer to build this client and he cannot tell me what his client code is.

Thanks.

**Comment by andrewhodel** [comment]
https.createServer creates a function thay returns a request object. 

That request object used .connection.remoteAddress before and with the latest node that is deprecated. 

I am telling you that I am getting a null value for both .connection.remoteAddress and .socket.remoteAddress often from http clients. 

That is actionable. 



Thank You,
Andrew Hodel

**Comment by bnoordhuis** [comment]
When you opened the issue over at nodejs/node, it asked you to fill out an issue template. Please do that.

**Comment by andrewhodel** [comment]
No, I work with node every day I know what you need for this issue. 13.13 latest. 

This is certainly understandable. 

I am trying to help, just take a look at that part of the code it is probably a stupid bug or typo. 




Thank You,
Andrew Hodel

**Comment by bnoordhuis** [comment]
> I work with node every day I know what you need for this issue

You're talking to someone who has worked with node every day for the last 10 years... I'll be the one to decide what I need to know for this issue.

That issue template is there for a reason. If you can't bring yourself to put in the effort, then so be it. I'm closing this.

**Comment by andrewhodel** [comment]
You know that when you are sitting next to or video conferencing with your
co-worker that what I provided is completely adequate.

It's a real issue, the problem here is that you are sick and tired of
people making up bullshit and this is your way of coping with it.

No problem, I'm the same way and that's the truth.  There are too many
making shit up.




Andrew

**Comment by addaleax** [comment]
@andrewhodel If you cannot provide us with more information **in order to help you**, then it’s just something you’ll have to figure out on your own time. We try to help people wherever possible, but like Ben said, your report just isn’t actionable. Insisting that this is a “real issue” doesn’t change that, at all.

Node.js is provided without cost, the nodejs/node and nodejs/help repositories are provided for resolving issues without cost, and generally we are under no obligation to help you if you don’t want to be helped by us.

**Comment by andrewhodel** [comment]
That is not true Anna.

All he needs to do is look at the socket code for 13.13 and the returned
request object of the http/https module (which is really net.socket) and
see where connection.remoteAddress and connection.socket.remoteAddress are
being set.

Something isn't being set right there.  There's no point in my filling out
that template.




Andrew

**Comment by andrewhodel** [comment]
It is my belief that one of our developers is working at the socket level
in C and sending messed up packets or flags on packets or something but the
guy doesn't even speak English.

I don't know what else to tell you, robot.




Andrew

**Comment by andrewhodel** [comment]
Might be more clear if you substitute robot for:

* 3rd world script kiddie
* White hat penetration tester
* nmap code reader
* [while loop that compares bits or bytes]



Andrew

**Comment by andrewhodel** [comment]
So FYI...

I don't know how often people are looking at the output of remoteAddress
(because it just returns null in this failure).

I am writing software for ISP's, so we constantly do and I'm just trying to
help and point out this issue.

It is said that you cannot just say 13.13 and the socket module, as far as
can explain to you TCP/IP is an RFC and the implementation difference
between Operating Systems should not have any affect at the input and
output level of the socket code in Node.

So what's the point of telling you I am using Linux 4.9.0-11-amd64




Andrew

**Comment by andrewhodel** [comment]
s/said/sad/

**Comment by addaleax** [comment]
> but the guy doesn't even speak English.

Since you don’t seem to be willing to engage in meaningful conversation, maybe “the guy” could come and open an issue here? Whatever his language, chances are somebody around here speaks it.

**Comment by andrewhodel** [comment]
I don't think the guy even knows he is doing it.

**Comment by andrewhodel** [comment]
Hence, script kiddie.

**Comment by andrewhodel** [comment]
I don't know what else to say, here they pay people to find and throw
everything bad they can find at our code.



Andrew

**Comment by andrewhodel** [comment]
I'm familiar with socket code, just trying to help.

https://github.com/andrewhodel/http-dl/blob/master/http-dl.c
