### ISSUE TITLE
Node 13.X for ARMv6

### ISSUE THREAD

**Issue by vsphagura** [nodejs/help#2625]
* **Node.js Version**: Node 13.x
* **OS**: RasPi Zero
* **Scope (install, code, runtime, meta, other?)**: all
* **Module (and version) (if relevant)**:

Will there be ARMv6l version for node 13.x? I can only see a version for armv7l which does not run on RasPi Zero W.

Thx

**Comment by richardlau** [comment]
Not officially. There are binaries available from https://unofficial-builds.nodejs.org/.

**Comment by gireeshpunathil** [comment]
closing as answered, pls re-open if this is outstanding
