### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by M4X-pixel** [nodejs/help#2628]
* **atomsetup-x64.exe**:
* **windows 7**:
* **Error update package**:
* ****:

I cannot install atom, please help. i tried some tips like turning off antivirus systems but did not help. what can i do?

Max.ikramov@gmail.com
thank you beforhand.
-->

**Comment by Hakerh400** [comment]
What error do you see? Please share all relevant information.

**Comment by M4X-pixel** [comment]
it showing error with update, saying programm update is not working and installation is being cancelled. Not even showing setup log

**Comment by bnoordhuis** [comment]
I'm not sure why you're opening an issue here. You're better off getting in touch with the people associated with the atom project.
