### ISSUE TITLE
Issue with playing Videos and Audios from S3--Network connection lost in Safari

### ISSUE THREAD

**Issue by NeelaSurendra** [nodejs/help#2631]
* **Node.js Version**:10.20.1
* **OS**: Ubuntu

We are using NodeJs to upload and stream video and audio files from S3 bucket. While trying to play those files in Safari and Mozilla FireFox we are facing MIME type error along with Network connection lost error. 
We have included content type in the headers and we have set the access as public.
We tried installing nginx server to solve it but it didn't resolve the issue.

Your help is highly appreciated.
Thank you.

Code snippet used to upload and get contents from S3:
To upload files:
async uploadByContentId(files,data,typeDetails,content,callback){     
    try{
      const {  id  } = data;
      const { fieldName,originalFilename,path,headers,size } = files.file && files.file[0];
      const { name } = typeDetails;
      this.logger.info(`Uploaded content - 'FileName' : ${fieldName} , 'Size' : ${size} `);
      if(size === 0){
        return callback(null, { ...ErrorConstants.ERRORS.CONTENT.NOT_FOUND });
      }
     const key = id+Path.extname(originalFilename) ; 
      const fileContent = fs.createReadStream(path);
      const params = {
          Bucket : BUCKET_NAME,
          Key: key,
          Body: fileContent,
          ContentType: contentType
         };
      this.logger.info(`Content uploaded started - 'FileName' : ${fieldName} , 'Size' : ${size}`);
      const s3_upload = s3.upload(params).promise();
      s3_upload.then(dataLocation => {
        this.logger.info(`Content uploaded successfully - 'FileName' :  ${fieldName} , 'Size' : ${size}, 'Location' : ${dataLocation.Location}`);
        this.sendUploadMail(id);
        return callback(null, { status: 200 , message: constants.MESSAGES.CONTENT_CREATED , 'data': content });
      },this).catch( async(error) =>{
        await app.Content.deleteById(id);
        this.logger.error(`Content delete successfully - 'content_id' :  ${id}`);
        return callback(null, ErrorConstants.ERRORS.CONTENT.UPLOAD_FAILED );
      });

    }catch(error){
      return callback(new ChilluppError(error));
    }
  }

To get Video and Audio files:
 async getContent(contentId,range,res, callback ){
    try{
      const contentDetails =await app.Content.findById(contentId,{ include: [ 'contentType','roles' ]});
      if(!contentDetails) {
      	return callback(null, { ...ErrorConstants.ERRORS.CONTENT.NOT_FOUND });
      }
      const { contentType , file_name , roles} = contentDetails.toJSON();
      const extname = Path.extname(file_name);
      let bucketName = {};
      if(roles.name == UserConstants.USER_ROLE_NAMES.TSI){
        bucketName = BUCKET_NAME;
      }else{
        bucketName = await this.formBucketName(contentType.name);
      }
      if (range) {
       const streamParams = {
          Bucket : bucketName,
          Key: contentId.concat(extname),
          Range: range                      
        };
        const { ContentLength , ContentType } = await this.headObject(contentId.concat(extname),bucketName);   
        const parts = range.replace(/bytes=/, "").split("-");
        const start = parseInt(parts[0], 10);
        const end = parts[1]  ? parseInt(parts[1], 10) : ContentLength-1;
        const chunksize = (end-start)+1;    
        let s3Stream = s3.getObject(streamParams).createReadStream().pipe(res)
        s3Stream.on('error',(error) => callback(new ChilluppError(error)));
        const head = {
            'Content-Range': `bytes ${start}-${end}/${ContentLength}`,
            'Accept-Ranges': 'bytes',
            'Content-Length': ContentLength,
            'Content-Type': ContentType,
        }
        res.writeHead(206, head);
      }else{
        if(contentType.name === contentConstants.CONTENT_TYPE.WORD || contentType.name === contentConstants.CONTENT_TYPE.AUDIO  ){
          contentId = contentId.concat(constants.EXTENTION.TEXT);
        }else{
          contentId = contentId.concat(extname);
        }
        const params = {
            Bucket : bucketName,
            Key: contentId
        }
        await this.headObject(contentId,bucketName);
        let s3Stream = s3.getObject(params).createReadStream().pipe(res)
        s3Stream.on('error',(error) => callback(new ChilluppError(error)));
      }
    }catch(error){
      return callback(null, { ...ErrorConstants.ERRORS.CONTENT.NOT_FOUND });
    }
  }

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
