### ISSUE TITLE
Is it possible to get larger compressed data while using bigger gzip compress level?

### ISSUE THREAD

**Issue by LongTengDao** [nodejs/help#2632]
* **Node.js Version**: 12
* **OS**:
* **Scope (install, code, runtime, meta, other?)**: runtine
* **Module (and version) (if relevant)**: zlib.gzip

```js
const original = Buffer.from('...');
console.log(zlib.gzipSync(original, { level: 1 }).length);
console.log(zlib.gzipSync(original, { level: 2 }).length);
console.log(zlib.gzipSync(original, { level: 3 }).length);
console.log(zlib.gzipSync(original, { level: 4 }).length);
console.log(zlib.gzipSync(original, { level: 5 }).length);
console.log(zlib.gzipSync(original, { level: 6 }).length);
console.log(zlib.gzipSync(original, { level: 7 }).length);
console.log(zlib.gzipSync(original, { level: 8 }).length);
console.log(zlib.gzipSync(original, { level: 9 }).length);
```

In other words, if I want to get smallest compressed data, could I simply pass level 9 to do that? Or I need to compare each with all other levels, to get smallest one, because in some cases, high level could get bigger output? Which is true?

**Comment by bnoordhuis** [comment]
> high level could get bigger output?

I think that might be the case for small inputs, yes. The size of the bigger dictionary can outweigh the increased compression rate.

**Comment by LongTengDao** [comment]
Could we find a input case to verify that? In my limited amount test for small inputs, high level output keep same with low level output, won't be larger. But I'm not sure, if it's always so.

**Comment by bnoordhuis** [comment]
Here's an example where level 0 (no compression) is smaller than max compression.
```js
const bytes = crypto.randomBytes(128);  // doesn't compress
console.log(zlib.gzipSync(bytes, {level: 0, memLevel: 1}).length);  // 151
console.log(zlib.gzipSync(bytes, {level: 9, memLevel: 1}).length);  // 153
```

**Comment by LongTengDao** [comment]
According to my daily observations, the compression behavior of 0 and -1 levels is relatively special, so here I mainly try to study 1-9.
