### ISSUE TITLE
got error when run program that generate by nexe

### ISSUE THREAD

**Issue by pichai9c** [nodejs/help#2634]
* **Node.js Version**:12.16.1
* **OS**:windows server 2012
* **Scope (install, code, runtime, meta, other?)**:runtime
* **Module (and version) (if relevant)**:   "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "jsonwebtoken": "^8.5.1",
    "msnodesqlv8": "^0.8.12"
    nexe: v3.3.2

I got following error after run the binary code which generated by nexe

internal/assert.js:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
[90m    at assert (internal/assert.js:14:11)[39m
[90m    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:129:
3)[39m
[90m    at internal/main/run_main_module.js:7:1[39m {
  code: [32m'ERR_INTERNAL_ASSERTION'[39m
}

Please help. Thank you.
Pichai
[server.zip](https://github.com/nodejs/help/files/4514894/server.zip)

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
