### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YapYeeQiang** [nodejs/help#2636]
* **Node.js Version**:
* **Window**:
PS C:\Users\johny\Downloads\pwj-module-8-my-blog-api-master\pwj-module-8-my-blog-api-master\exercise> npm init
or operable program. Check the spelling of the name, or if a path was included, verify  
At line:1 char:1
+ ~~~
   n
    + FullyQualifiedErrorId : CommandNotFoundException

Someone help please!!

**Comment by PoojaDurgad** [comment]
@YapYeeQiang - can you elaborate the issue more please ?are you running the commands in powershell? its little gritty to identify your error with your description. so can you provide the full error log message? and what command you are trying to run?

**Comment by PoojaDurgad** [comment]
inactive!! closing . please let me know if that is not the case
