### ISSUE TITLE
Error when using global package's command in spawn

### ISSUE THREAD

**Issue by amjedomar** [nodejs/help#2638]
* **Version**: 12.16.2
* **Platform**: Windows 10, 64 bit
* **Subsystem**: none

### What steps will reproduce the bug?
Open terminal and install global package whether by `npm` or `yarn` then use package's command in `cp.spawn()`

### How often does it reproduce? Is there a required condition?
It happens always, It is inescapable

### What is the expected behavior?
The package's command runs well and I get its result as stream 

### What do you see instead?
I got this error
```
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn tsc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn tsc',
  path: 'tsc',
  spawnargs: [ '--help' ]
}
```

### Additional information
When I run package's command using `cp.exec()` it works however when I run it using `cp.spawn()` (I got error as I explained above). **This is my code**

```
const cp = require('child_process');
const fs = require('fs');

// Works
const buffer = cp.exec('tsc --help');
buffer.stdout.on('data', console.log);

// The problem comes here
const stream = cp.spawn('tsc', ['--help']);
stream.stdout.pipe(fs.createWriteStream('example.txt'));
```

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help because that's expected and documented behavior. See the ["Spawning `.bat` and `.cmd` files on Windows"](https://nodejs.org/docs/v14.0.0/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows) section in the child_process documentation.

**Comment by bzoz** [comment]
You should use `exec`. The npm commands are shell scripts, the `tsc` is `tsc.cmd` somewhere in npm installation path. Either:
 - use `exec`
 - use `spawn` with `shell:true`
 - use `spawn` but spawn `cmd.exe` with `/d /s /c script` arguments ([just like Node does](https://github.com/nodejs/node/blob/master/lib/child_process.js#L490))
