### ISSUE TITLE
How to exhibit backpressure issues in test

### ISSUE THREAD

**Issue by fbiville** [nodejs/help#2639]
* **Node.js Version**: 10, 12, 13, 14
* **OS**: Mac OS 10.15.4
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: streams

I’m currently working on a series of blog posts (well, at least 2) about Node.js streams.
The second one is about backpressure and I want to revisit the custom implementation of the [“zip operator”](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/doc-files/marbles/zipIterableSourcesForFlux.svg) Readable stream I introduced in the first blog post.
So far, everything has been driven by test and I would like to continue that way.

Is there a way to exhibit backpressure problems in a test, ideally resulting in an error in the consumer (PassThrough) stream?

In particular, I thought this particular test would at least trigger some issues (notice the `highWaterMark: 1` setting on the destination stream):

```js
const { PassThrough, pipeline, Readable } = require('stream');

    it("respects backpressure", (done) => {
        const upstream1 = Readable.from([1, 2, 3], { objectMode: true });
        const upstream2 = Readable.from(["Un", "Deux", "Trois"], { objectMode: true });
        const zipSource = new ZipReadable(upstream1, upstream2);
        const destination = new PassThrough({ objectMode: true, highWaterMark: 1 });
        const result = [];

        destination.on('data', (chunk) => {
            result.push(chunk);
        });

        pipeline(
            zipSource,
            destination,
            (err) => {
                expect(err).toBeFalsy('pipeline should successfully complete');
                expect(result).toEqual([
                    [1, "Un"],
                    [2, "Deux"],
                    [3, "Trois"]
                ]);
                done();
            }
        );
    })
```
The test passes, which is not 100% surprising.

However, there should be some signs of backpressure in `ZipReadable` but I see none.
Calls to `push` in `ZipReadable` continues to return `true`, even if the `highWaterMark` of the downstream consumer is reached.

Must I implement a custom `Writable` stream instead of using `PassThrough`?
If that is the only way, how can I emit an `error` when the internal buffer of the custom `Writable` reaches the high water mark?

Thanks in advance for your help!

**Comment by addaleax** [comment]
Can you share the current implementation of `ZipReadable` for reference here?

> Must I implement a custom `Writable` stream instead of using `PassThrough`?

No.

> If that is the only way, how can I emit an `error` when the internal buffer of the custom `Writable` reaches the high water mark?

You can use `stream.destroy(err)` if you want to emit `'error'` events on a stream, but doing that when hitting the high water mark seems to be a big mismatch with how the high water mark option generally works.

**Comment by fbiville** [comment]
@addaleax thanks for your reply!
Here is `ZipReadable`, which currently does not handle backpressure at all. I think I have a good idea on how to fix it, but I'd really like to have a failing test first:

```js
const { Readable } = require("stream");

class ZipReadable extends Readable {

    constructor(...upstreams) {
        super({ objectMode : true });
        this.initialized = false;
        this.waitingForData = false;
        this.endedUpstreamCount = 0;
        this.streams = upstreams;
        this.chunks = upstreams.map(() => []);
    }

    _read(size) {
        if (!this.initialized) {
            this._startReading();
            this.initialized = true;
        }
        const bound = Math.min(size, ...this.chunks.map(array => array.length));
        if (bound === 0) {
            this.waitingForData = true;
            return;
        }
        this.waitingForData = false;
        this.chunks
            .map(a => a.splice(0, bound))
            .reduce((prev, curr) => {
                const result = [];
                for (let i = 0; i < bound; i++) {
                    const previous = (Array.isArray(prev[i])) ? prev[i] : [prev[i]];
                    result.push([...previous, curr[i]]);
                }
                return result
            })
            .forEach((pair) => {
                this.push(pair); // should check return value but currently does not :)
            })
    }

    _startReading() {
        this.streams.forEach((stream, index) => {
            stream.on('end', () => {
                this.endedUpstreamCount++;
                if (this.endedUpstreamCount === this.streams.length) {
                    this.push(null);
                }
            });
            stream.on('data', (chunk) => {
                const streamChunks = this.chunks[index];
                streamChunks.push(chunk);
                if (this.waitingForData) {
                    this._read(streamChunks.length);
                }
            });
        });
    }
}
```

**Comment by addaleax** [comment]
As for writing a test:

Firstly, you probably also want to provide an explicit high water mark to the `ZipReadable` instance, otherwise its own buffer will get in the way of testing this.

After that, you could base a test on something like

```js
const upstream1 = new PassThrough({ highWaterMark: 1, objectMode: true });
const upstream2 = new PassThrough({ highWaterMark: 1, objectMode: true });
const zipSource = new ZipReadable({ highWaterMark: 1 }, upstream1, upstream2);

upstream1.write(1);
upstream2.write('Un');
upstream1.write(2);
upstream2.write('Deux');
upstream1.write(3); // These writes should start returning `false` to propagate backpressure.
upstream2.write('Trois');
```

> > [...] seems to be a big mismatch with how the high water mark option generally works.
> 
> Do you have any pointers about how high water marks internally works?

Not really how it works internally, but throwing exceptions is definitely not the goal here; instead, it’s to provide information to the data source that tells it to stop writing and when to resume doing so.

**Comment by fbiville** [comment]
@addaleax gotcha
I was initially thinking of throwing an exception to have the test fail in some ways.
I agree that throwing exceptions when backpressure happens is not a good idea in general, but wouldn't it make sense in this particular test context?

**Comment by addaleax** [comment]
@fbiville I mean, that’s kind of what `expect()` does, right? Throw exceptions if something isn’t right? :)

Like, sure, for tests, do whatever works for you :+1:

**Comment by fbiville** [comment]
Oh wait, I misread your snippet and thought only of `ZipReadable` internal `this.push` calls returning `false`, not the actual `upstreamX.write` calls in the test. Everything is clear now. Thanks again!

**Comment by fbiville** [comment]
Apologies, I must be missing something but I'm not following. 
I'm aware of `expect` and how it works. 

However, I fail to see how it can be used here.

`expect(upstream1.write(3)).toBeFalsy()` or `expect(upstream2.write('Trois')).toBeFalsy()` would only test the built-in backpressure mechanism, so not very useful.

The expectation should be set on `zipSource`, but what would the expectation be?

This is why I was thinking of introducing a custom `Writable` destination stream.
That stream would emit an error when it received extra chunks of data despite signalling it could not handle more. 
I could listen to `'error'` events on that destination stream and fail the test if it occurs.
Observing such an error would be the proof that `ZipReadable` does not handle backpressure.

Does it make sense?
Do you think there is a way have the test fail that does not require a custom implementation like this?

**Comment by addaleax** [comment]
> `expect(upstream1.write(3)).toBeFalsy()` or `expect(upstream2.write('Trois')).toBeFalsy()` would only test the built-in backpressure mechanism, so not very useful.

I’m not sure what you mean – the point is that if you don’t consume data from `zipSource`, then providing input to it should return `false`. That’s exactly what this would test.

> This is why I was thinking of introducing a custom `Writable` destination stream.
> That stream would emit an error when it received extra chunks of data despite signalling it could not handle more.

Sure, yes, that works too. :+1:

**Comment by fbiville** [comment]
Ah, I finally understand. Apologies it took me a while :)
