### ISSUE TITLE
How to make any command that returns a file return stream instead

### ISSUE THREAD

**Issue by amjedomar** [nodejs/help#2640]
> My question is about any command that returns a file but I will take `tsc` command as example

Now if we running `tsc example.ts` this command will compile `example.ts` content then return `example.js` file

**My question is how to make any command that returns a file, return stream instead**

So I can do something similar to the following:

```js
const spawn = require('child_process').spawn;
const fs = require('fs');

const stream = spawn('tsc', ['src/example.ts'], {
  shell: true
});

setTimeout(() => {
  stream.stdout.pipe(fs.createWriteStream('./go/to/example.js'));
}, 5543);
```

**Comment by Hakerh400** [comment]
In general, you cannot, unless you implement a fully virtual machine. Once you spawn a process, you cannot control what files it accesses. In your example, `tsc` is a batch (or bash) file that spawns a new Node.js process. It does not *"return a file"*, it does a lot of things, among which is creating `example.js` file. Some programs support outputting to stdout, some not. Some programs do not create any files. Some programs create multiple files. Your requirements are really not precisely defined.
