### ISSUE TITLE
Windows have problems uninstalling, updating or installing Node JS

### ISSUE THREAD

**Issue by Malavassi98** [nodejs/help#2643]
* **Node.js Version**: 12.14
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: uninstall, install or update
* **Module (and version) (if relevant)**:

When I try to do any of the above actions on the title, windows throws me this.

![image](https://user-images.githubusercontent.com/37245533/80176513-102abd80-85b6-11ea-8541-3794dac26408.png)

Windows Installer works on any of the other programs except Node JS.

**Comment by Hakerh400** [comment]
What version of Windows do you use? That error message is specific to Windows 7 and Windows Vista systems. Try [these suggestions](https://support.microsoft.com/en-us/help/2642495/the-windows-installer-service-could-not-be-accessed-error-when-you-try) and see if that helps.

**Comment by PoojaDurgad** [comment]
@Malavassi98 - is this still an issue? were you able to follow  @Hakerh400 's suggestion ?

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to re-open the issue if that is not the case
