### ISSUE TITLE
Unnexpected behavior in RegExp 

### ISSUE THREAD

**Issue by danielbom** [nodejs/help#2645]
* **Version**: node v10.16.0
* **Platform**: Linux daniel-Aspire-V3-571 5.3.0-46-generic nodejs/node#38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: RegExp

### What steps will reproduce the bug?

In interactive mode of node:

r = /mongodb:\/\/((?'username'\w+):(?'password'\w+)@)?(?'hosts'\w+[,\w]*)(\/(?'defaultdb'[\w\.]+))([?](?'options'.*))?$/mg
a = "mongodb://user:password@host,host2,host3,host4/databasename?options=1&options=2"
r.test(a) === r.test(a) # !!! FALSE !!!
r.exec(a) // Some times return null and some times the match result
r.exec(a) // Some times return null and some times the match result

### What is the expected behavior?

Expect the regex 'test' and 'exec' return the same result for same input and context. 

### What do you see instead?

The regex 'test' and 'exec' return differents results with same input and context.

### Additional information

https://stackoverflow.com/questions/61417049/regex-its-possible-to-do-submatching-in-regex

**Comment by PoojaDurgad** [comment]
@danielbom - is there anything pending in this issue?

**Comment by PoojaDurgad** [comment]
closing as resolved. please feel free to reopen the issue if its still outstanding!!
