### ISSUE TITLE
NODEJS Installation Issue

### ISSUE THREAD

**Issue by Tobijudah** [nodejs/help#2647]
* **Node.js Version**: 12.16.2 (and every other version)
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

HELP! I initially installed NodeJS V12.16.2. Somehow I mistakenly deleted a program folder. I tried to uninstall it so I could install it afresh but it didn't work and the error message was **The Windows Installer Service could not be accessed. This can occur if you're running Windows in safe mode, or if the Windows Installer is not correctly installed. Contact your personnel for assistance** [as seen in Image 1] and this error was only unique to NodeJS. Other installations worked fine. So I deleted all NodeJS files from the initial download but it still showed as an installed program. I then manually uninstalled it from Windows registry and it no longer showed as an installed program. Then I downloaded the same version and attempted to install but it displays [image 2] even though there isn't NodeJS or any related file on my computer (at least to the best of my knowledge). and moving forward with any of the three options always ends up with the error message in [image 1]. I tried other versions but came up with the same results.
after about a month I tried again with the new 14.0.0 version. After downloading I started up the installer and it displays [image 3]. I continue with the installation but it still ended up with the error message in [image 1]
I know I made some silly mistakes but I don't know what to do any longer.
Any help will be appreciated

![Screenshot (153)](https://user-images.githubusercontent.com/58530782/80288143-daa8e000-872d-11ea-8f65-728ad4d7030f.png)
![Screenshot (132)](https://user-images.githubusercontent.com/58530782/80288137-d11f7800-872d-11ea-8360-cd055554cbaa.png)
![Screenshot (194)](https://user-images.githubusercontent.com/58530782/80288258-cd402580-872e-11ea-8ca1-c7fb980efc9a.png)

**Comment by addaleax** [comment]
@Tobijudah I’m not really sure that I can help here for a broken installation of Node.js, but you can always download the `.zip` variant instead of the installer, unpack it somewhere, and then add that to your `PATH` environment variable on Windows.

**Comment by Tobijudah** [comment]
If it wouldn't cause any problems I'm game.
I'm not sure how to do that though...
@addaleax
