### ISSUE TITLE
    channel.join()               TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by Paramonow** [nodejs/help#2648]
Hi

I have a problem with the discord.js file because I took my discord bot to the voice channel, but when I write a message, my bot crashes an error in my terminal (when I wrote a message from the bot, I was in the voice channel) 

channel.join()
            ^

TypeError: Cannot read property 'join' of undefined
    at Client.<anonymous> (D:\JP2BOT\index.js:17:13)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (D:\JP2BOT\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\JP2BOT\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:\JP2BOT\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (D:\JP2BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (D:\JP2BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (D:\JP2BOT\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (D:\JP2BOT\node_modules\ws\lib\websocket.js:801:20)

help me

**Comment by Hakerh400** [comment]
Please share your code.

**Comment by Strielok2137** [comment]
if (message.content === 'Dość') {
    const channel = message.member.voiceChannel;
    channel.join()
    .then(connection => console.log('Connected!'))
    .catch(console.error);
  }

**Comment by Hakerh400** [comment]
How do you expect anyone to help you when you provide only a few lines of code? Please share the entire script including all relevant other scripts that you import.

**Comment by Strielok2137** [comment]
ok 

const discord = require ("discord.js");
var client = new discord.Client(); 

const token = "XYZ";
client.on ("ready", () => {
});
const prefix = "!jp2 ";
client.on ("message", (message) => { 
  if (message.content === 'Dość') {
    const channel = message.member.voiceChannel;
    channel.join()
    .then(connection => console.log('Connected!'))
    .catch(console.error);
  }
}},
)
client.login (token);

**Comment by Hakerh400** [comment]
Please read their [documentation](https://discord.js.org/#/docs/main/stable/general/welcome). You can find answer to your questions there.

It clearly says that `message.member.voiceChannel` is defined only in case when `message.member` is an instance of `VoiceChannel`.

**Comment by Strielok2137** [comment]
Thank you bro, but i have next error 

   connection.play('https://www.youtube.com/watch?v=AlIiIBP6oII');
                 ^

TypeError: connection.play is not a function
    at Client.<anonymous> (D:\JP2BOT\index.js:20:18)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (D:\JP2BOT\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\JP2BOT\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:\JP2BOT\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (D:\JP2BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (D:\JP2BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (D:\JP2BOT\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (D:\JP2BOT\node_modules\ws\lib\websocket.js:801:20)


my code :
const discord = require ("discord.js");
var client = new discord.Client();

const token = "XYZ";
client.on ("ready", () => {
});
const prefix = "!jp2 ";
client.on ("message", (message) => {
if (!message.guild) return;
  if (message.content === 'Dość') {
    if (message.member.voice.channel) {
      const connection = message.member.voice.channel.join();
      const dispatcher = connection.play('my path ');
      dispatcher.pause();
      dispatcher.resume();
      
      dispatcher.setVolume(0.5); // half the volume
      
      dispatcher.on('finish', () => {
        console.log('Finished playing!');
      });
      
      dispatcher.destroy()
    } else {
      message.reply('XYZ');
    }}
}},
)
client.login (token);

**Comment by Hakerh400** [comment]
Once again, please read the documentation. I see what the problem is in your new code, but I want you to learn to follow the documentation and try to solve the problem yourself.

**Comment by Strielok2137** [comment]
i was look to the documentation but function connection.play is in the documentation

https://discord.js.org/#/docs/main/stable/topics/voice

**Comment by Hakerh400** [comment]
> i was look to the documentation but function connection.play is in the documentation

Yes, but it returns a Promise object. You need to make your function `async` and put `await` before `message.member.voice.channel.join()`, as can be seen in the example from the documentation.

**Comment by Strielok2137** [comment]
Thanks bro 

  if (!message.guild) return;
if (message.content === 'Dość') {
if (message.member.voice.channel) {
const connection = await message.member.voice.channel.join();
const dispatcher = connection.play('https://www.youtube.com/watch?v=n7hHlh2IusY');
} else {
  message.reply('XYZ');
}}

unfortunately my bot doesn't start music but doesn't give me any error

**Comment by AV77** [comment]
I am also experiencing issues with the same topic so @Hakerh400, could you pls help me?


```
const Discord = require('discord.js');
const client = new Discord.Client();
const{Prefix, token} = require('./config.json')

// const token = 'NzI4Mjg3OTA2NDM0OTA4MTgw.Xv4WRQ.PaxrpL8aTyLBTp7zCWuJ4mk09B0';

// const Prefix = '.';


const ytdl = require('ytdl-core')

var servers = {};



client.on('ready', () => {
    console.log('Ready!');
    // message.send
});

client.on('message', message => {
    
    let args = message.content.substring(Prefix.length).split(" ");

    switch(args[0]){
        // case 'ping':
        //     message.channel.send('pong');
        // break;
            

        // case 'website':
        //     message.channel.send('http://anmolv.co/');
        // break;


        // case 'info':

        //     switch(args[1]){
        //         case undefined :
        //             message.channel.send('Bro, I need more information, pls specify.');
        //         break;

        //         case 'version' :
        //             const {version} = require('./package.json')
        //             message.channel.send(`Current version is **${version}**`)
        //         break;

        //         case 'author' :
        //             const {author} = require('./package.json')
        //             message.channel.send(`Current author is **${author}**`)
        //             break;
                    
        //         case 'lisence' :
        //                 const {license} = require('./package.json')
        //                 message.channel.send(`Current lisence is **${license}**`)
        //         break;
        //     }
        //     // if (args[1] === undefined) {
        //     //     message.channel.send('Bro, I need more information, pls specify.');
        //     // }
            
        //     // else if (args[1] === 'version') {             
        //     //     const {version} = require('./package.json')
        //     //     message.channel.send(`Current version is **${version}**`)
        //     // }
            
        //     // else if (args[1] === 'author') {             
        //     //     const {author} = require('./package.json')
        //     //     message.channel.send(`Current author is **${author}**`)
        //     // }
            
        //     // else if (args[1] === 'lisence') {             
        //     //     const {license} = require('./package.json')
        //     //     message.channel.send(`Current lisence is **${license}**`)
        //     // }
            
        //     // else {
        //     //     // message.channel.send('Bruh, The dev (ie. **Anmol** the great) was toooo **lazy** to impliment this feature lol.')
        //     //     message.reply('Bruh, The dev (ie. **Anmol** the great) was toooo **lazy** to impliment this feature lol.')
        //     // }
        // break;


        // case 'clear' :
        //     if(!args[1]) return message.reply(`**Error :** Please give appropriate number such as:\n\`${Prefix}${args[0]} 10\``)
            
        //     message.channel.bulkDelete((parseInt(args[1])+1).toString());
        //     // message.channel.send();
        //     break;

            
        case 'play' :

            function play(connection, message){
                var server =  servers[message.guild.id];

                server.dispatcher = connection.playStream(ytdl(server.queue[0], {filter: "audioonly"}));

                server.queue.shift();

                server.dispatcher.on("end", function(){
                    if(server.queue[0]){
                        play(connection, message)
                    } else {
                        connection.disconnect();
                    }
                })
            }

            if(!args[1]) return message.reply(`**Error :** Please give appropriate link such as :\n\`${Prefix}${args[0]} https://www.youtube.com/watch?v=AX5xHz_Sm6A\``);
            if(!args[1]) return message.reply(`**Error :** Please go in a voice channel first.`);
            
            if(!servers[message.guild.id]) servers[message.guild.id] = {
                queue: []
            };

            var server =  servers[message.guild.id];

            server.queue.push(args[1]);

            if(!message.guild.voiceConnection) message.member.voice.channel.join().then(function(connection){
                play(connection, message);
            });
        break;
    };
});

client.login(token);
```

**Comment by Wozeismaybedead** [comment]
vive les juifs
