### ISSUE TITLE
node-gyp:call Windows API GetModuleFileNameA directory contains'\\?\'

### ISSUE THREAD

**Issue by tangjiang** [nodejs/help#2649]
* **Version**:12.16.0
* **Platform**:64-bit(Windows10)
* **Subsystem**:bindings

### What steps will reproduce the bug?

I'm developing a node c++ windows project , when I type some c++ code like this:
```
#include <Windows.h>
char szPath[256];
memset(szPath, 0, sizeof(szPath));
::GetModuleFileNameA(::GetModuleHandleA("bp_com.dll"), szPath, sizeof(szPath) - 1);
std::cout << szPath << std::endl;
```
then the output of the console like this:
```
\\?\E:\work\git\nodesvc-dev\build\Debug\bp_com.dll
```
I don't known why the directory of the 'bp_com.dll' contains '\\\\?\' .

### How often does it reproduce? Is there a required condition?
I use npm config: npm config set msvs_version 2017
### What is the expected behavior?

When  GetModuleFileNameA function is called, the directory of the 'bp_com.dll' may be like this 
```
E:\work\git\nodesvc-dev\build\Debug\bp_com.dll
```

**Comment by bzoz** [comment]
The `\\?\` prefix is the "file namespace" - https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces. With this, you can have filenames longer than 260 bytes, have files with reserved names (like `..` or `con`) but you must use absolute paths and the Unicode variant of the functions (with a `W` at the end, not with the `A`).

Besides that, this is completely unrelated to Node, so I'm going to close this 🙂.
