### ISSUE TITLE
Node installation

### ISSUE THREAD

**Issue by gcrowcroft** [nodejs/help#265]

**Comment by gcrowcroft** [comment]
Ive downloaded the program but im new to Raspberry pi and dont know how to install the zipped file

**Comment by r1b** [comment]
Hi @gcrowcroft,

Can you try following the instructions here:
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by gcrowcroft** [comment]
Got it thanks
