### ISSUE TITLE
nodejsversion 14 

### ISSUE THREAD

**Issue by inspirator453** [nodejs/help#2650]
ever since installled nodejs 14 this keeps poping out 
(node:4896) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4896) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency  
(node:4896) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency   
(node:4896) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

```
-->

**Comment by addaleax** [comment]
Can you run Node.js with `--trace-warnings` as suggested by the output?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
