### ISSUE TITLE
Postmortem CPU leak debug

### ISSUE THREAD

**Issue by drobnikj** [nodejs/help#2651]
* **Node.js Version**:  v12.13.0
* **OS**:
* **Scope runtime**:

Hey guys,

I try to hunt CPU leak in my app for some days, but I'm not still able to create a solution which helps me to find postmortem the bug in my app. The problem is that the CPU leak appears randomly, probably in some package I used and when it appears it kills the host.

I tried to do a solution with:
1) --experimental-report --report-on-signal -> but it didn't work, it will not generate the report because there was no free CPU capacity on the server.
2) Then I tried to hack it with solution https://gist.github.com/mraleph/6453431#file-infinite-loop-trick-log-L4 , but it didn't work, probably because of some internal stuff change in nodejs.
3) I also tried to --prof, but it didn't work for me as the leak appears randomly and I'm not able to run profiling all the time.
4) I tried --cpu-prof, but I can not find the way to generate CPU report on some signal or for exit process with no success.

Can somebody point me to a solution, which can work in this case? 
Maybe I just use tools bad way. Any help is welcome.

**Comment by addaleax** [comment]
Is CPU leak = infinite loop here for you?

>     2\. Then I tried to hack it with solution https://gist.github.com/mraleph/6453431#file-infinite-loop-trick-log-L4 , but it didn't work, probably because of some internal stuff change in nodejs.

What exactly didn’t work? This is what I would have recommended you to do here, so more information would be helpful.

If you are assuming that an infinite loop is happening in JS, you can also use `kill -USR1 $pid` to enable the Chrome Debugger for a given Node.js process.

**Comment by drobnikj** [comment]
@addaleax Thanks for the response.
You are right, I mean infinite loop.

The trick didn't work for me as I can not schedule interrupt using 
`(gdb) print 'v8::V8::TerminateExecution'(0)`
I'm getting just
`No symbol "v8::V8::TerminateExecution" in current context.`

I also tried the second option with isolate
```
(gdb) print 'v8::Isolate::GetCurrent'()" 
(gdb) print 'v8::Isolate::TerminateExecution'($1)" 
```
but with the same issue.

**Comment by addaleax** [comment]
@drobnikj Right – but using `TerminateExecution()` doesn’t really seem like something that would help anyway, tbh?

If you do have an infinite loop in JS, it’s usually easiest to start the debugger by sending `SIGUSR1` to the process, and attaching Chrome DevTools or an equivalent tool that supports debugging Node.js to it. That should give you a stack trace (and much more information than that, if necessary).

**Comment by drobnikj** [comment]
@addaleax Thanks for the response, you are right.

But I can not easily kill it with SIGUSR1 and attach debugger, as I run the app in stateless k8s container and I can not reproduce the bug on the other environment.

In the end, I get the script from https://gist.github.com/mraleph/6453431#file-infinite-loop-trick-log-L4 work. I just need to use the right Linux distribution for my container, where gdb works correctly.
