### ISSUE TITLE
Stuck with spawn=ENOENT error on all commands after new install on Windows 10

### ISSUE THREAD

**Issue by Tidmand** [nodejs/help#2652]
* **Node.js Version 12.16.2 :
* **OS Windows 10:
* **Scope error on all commands after new install:
* **Module next 6.14.4 - unable to finish postinstalls and basic calls like npm run dev:

New install of Node.js. I can't build anything with npm run dev, always getting the same type of error (screendump). Have no clue why I can't get Node.js to work proberly. Don't know if it's something with permissions or anything else. Please help me, since I'm clueless and very frustrated.

Thanks,
Søren Tidmand
Web developer 

![vscode_npm_spawn_enoent](https://user-images.githubusercontent.com/4766336/80371935-fbd71100-8892-11ea-9709-cb586d7d72bc.png)

**Comment by addaleax** [comment]
@Tidmand This seems like it’s not really related to Node.js, but more to the package you’re trying to work with.

I’m guessing that is https://github.com/oryam/hello-next/? Have you run `npm install`, and if yes, was that successful? That should have installed `next`.

**Comment by Tidmand** [comment]
Hi Anna,
I'm working on a brand new Windows 10, installed Node.js via the .msi package and was going through the https://github.com/zeit/next-learn-demo. Everything worked okay until lesson 8 (as I remember), where the last excercise was running to environments .. and at some point I was derailed .. have maybe added a plugin ... maybe even globally ... and shortly after this everything broke. I reset my Windows 10 and reinstalled everything ... but still no luck. I get the error as shown above on practically every command, sometimes even as a postinstall error. I'm really frustrated and have no clue what I did wrong and why I just can't get back to zero.
Any help is very appreciated.

**Comment by addaleax** [comment]
@Tidmand I’m sorry to repeat my question, but did you run `npm install`, and if yes, was that successful?

**Comment by Tidmand** [comment]
@addaleax yes, I ran npm install succesfully. The error happens afterwards

**Comment by addaleax** [comment]
I think the debug log mentioned by npm here might be helpful then.

**Comment by Tidmand** [comment]
I didn't find any solutions, so decided to make a clean reinstall of Windows 10 and start from scratch. Now everything is working again.
