### ISSUE TITLE
ionic installation failure

### ISSUE THREAD

**Issue by Aklilufregzi** [nodejs/help#2653]
* **Latest**:
* **Debian/Kubuntu**:
* **installation**:
* **ionic CLI**:

I was trying to install ionic CLI from linux terminal and I keep getting an ERROR message saying that the package namem has changed to @ionic/cli, and I've tried that too.
the error also keeps giving me some debug log .

I've tried
sudo npm install ionic -g
sudo npm install @ionic/cli -g  

the error is 

npm ERR! Unexpected end of JSON input while parsing near '...NDhbkD7EpQstegLW3SmjK'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/frezgi/.npm/_logs/2020-04-27T16_18_59_750Z-debug.log

//here's the debug log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '@ionic' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose config Skipping project config: /home/frezgi/.npmrc. (matches userconfig)
5 verbose npm-session fb863ad811d92d32
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 17ms
10 verbose stack Error: Invalid tag name "@ionic": Tags may not have any characters that encodeURIComponent encodes.
10 verbose stack     at invalidTagName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:91:15)
10 verbose stack     at fromRegistry (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:296:13)
10 verbose stack     at resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:81:12)
10 verbose stack     at npa (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:52:10)
10 verbose stack     at /usr/lib/node_modules/npm/lib/install/deps.js:227:14
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
10 verbose stack     at Array.forEach (<anonymous>)
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
10 verbose stack     at Array.forEach (<anonymous>)
10 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
10 verbose stack     at exports.getAllMetadata (/usr/lib/node_modules/npm/lib/install/deps.js:224:3)
10 verbose stack     at Installer.loadArgMetadata (/usr/lib/node_modules/npm/lib/install.js:366:3)
10 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:701:16
10 verbose stack     at BB.join.then (/usr/lib/node_modules/npm/lib/install/read-shrinkwrap.js:33:16)
10 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
11 verbose cwd /home/frezgi
12 verbose Linux 5.0.0-23-generic
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "@ionic"
14 verbose node v10.20.1
15 verbose npm  v6.14.4
16 error code EINVALIDTAGNAME
17 error Invalid tag name "@ionic": Tags may not have any characters that encodeURIComponent encodes.
18 verbose exit [ 1, true ]

**Comment by addaleax** [comment]
@Aklilufregzi It looks like either your `package.json` or your `package-lock.json` is broken? Removing `package-lock.json` might already help.

If not, can you share the debug log that npm is referring to?

**Comment by Aklilufregzi** [comment]
> @Aklilufregzi It looks like either your `package.json` or your `package-lock.json` is broken? Removing `package-lock.json` might already help.
> 
> If not, can you share the debug log that npm is referring to?

**Comment by PoojaDurgad** [comment]
@Aklilufregzi - is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to reopen the issue if that it is outstanding
