### ISSUE TITLE
PassThrough, why is resume() required even with end: false?

### ISSUE THREAD

**Issue by arcanis** [nodejs/help#2655]
* **Node.js Version**: 12.16.1
* **OS**: Unix
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: stream

Why is the `resume` call needed for `end` to be printed? Note that I'm using `end: false` in order to call it myself.

```js
const {PassThrough} = require(`stream`);

const a = new PassThrough();

const b = new PassThrough();
a.pipe(b, {end: false});

b.on(`end`, () => {
    console.log(`end`);
});

a.write(`foo`);
a.end();

// v--- Why is the resume needed?
b.resume();

b.end();
```

**Comment by kk456852** [comment]
In your case, `readable.resume() `switches the `readable.readableFlow` to true, and the readable stream starts to actively generate data and trigger events.
Please refer to the official documents [http://nodejs.cn/api/stream.html#stream_event_pipe](url)
