### ISSUE TITLE
How to make use of js-xls module in my app?

### ISSUE THREAD

**Issue by tanmay-saxena** [nodejs/help#266]
I am new to node and express. I want help on how to make this module work in my express app.(using express myapp). i.e. how to add this module to my app.  I wanted to add js-xls module so that i can make a dynamic app where when i update a excel file it automatically shows on to my web app.

**Comment by Trott** [comment]
What have you tried?

**Comment by tanmay-saxena** [comment]
I was able to use the module from node terminal. But I don't know how to implement this in  my express app.

**Comment by Trott** [comment]
Show the code you tried.
