### ISSUE TITLE
issue in creating React app

### ISSUE THREAD

**Issue by adeelnaqvi172** [nodejs/help#2662]
I am using window 10. My node version is  12 and NPM version is 6. but after installing they show me this message.And did not show public folder and src folder.when i start react app by using NPM start they show me this error:
![2](https://user-images.githubusercontent.com/53054023/80693511-f7c01480-8a87-11ea-8fe3-63ab721b3f46.PNG)
![3](https://user-images.githubusercontent.com/53054023/80693519-fc84c880-8a87-11ea-8ae2-5d8a2770ae0f.PNG)
![5](https://user-images.githubusercontent.com/53054023/80693534-ff7fb900-8a87-11ea-88de-fa4f58705ea9.PNG)

![2](https://user-images.githubusercontent.com/53054023/80692652-baa75280-8a86-11ea-9995-4bafb17cced5.PNG)

**Comment by mahalde** [comment]
Hello, your package.json has no scripts in it. The command `npm start` uses a script which is called start in your package.json.

For example:
```json
{
    "name": "my-first",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "start": "node -v"
    }
}
```

If you type `npm start` while in the folder with the package.json or a child folder, the current node version gets logged. If you are trying to create a new React project, please follow the guide [here](https://reactjs.org/docs/create-a-new-react-app.html). The command which gets shown there initialises a correct package.json with scripts for you. Additionally click [here](https://docs.npmjs.com/misc/scripts) to read more about npm scripts.

**Comment by adeelnaqvi172** [comment]
Thanks @mahalde
