### ISSUE TITLE
Cluster: how to inspect and act upon incoming requests

### ISSUE THREAD

**Issue by bohlec** [nodejs/help#2664]
* **Node.js Version**: 10.15.0
* **OS**: Unix
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: cluster

Hi all,

We are using cluster to fork a number of worker processes based on the number of cores available. I've been looking at the cluster source trying to determine ways that we can insert application logic that could inspect incoming requests and perform specific actions such as triggering scale-outs or load shedding.

However, I'm not finding a way to reference or access the incoming requests to the server on master before they get handed off to a worker (round_robin_handle.js). I feel like ideally an app could provide its own scheduling policy as part of `setupMaster`, but currently that ability is not allowed.

Does anyone have any insight here? Are there other options available?

Thanks in advance.

**Comment by bnoordhuis** [comment]
See https://github.com/nodejs/node/issues/10880 and the issues/pull requests linked therein. It's been requested (and discussed - at length) in the past but it ultimately never went anywhere.

If you want to see it happen, your best bet is to dust off https://github.com/nodejs/node/pull/11546 and submit it again.

> to determine ways that we can insert application logic that could inspect incoming requests

If that's just an unfortunate choice of nomenclature then never mind but `cluster` operates on TCP connections, not HTTP requests.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
