### ISSUE TITLE
node.js support model

### ISSUE THREAD

**Issue by zorro2003** [nodejs/help#2665]
newbie here - I work in an IT shop and working with some folks that are supporting our website, which uses node.js, supporting the current website for a client.  They are coming to me and saying that the support for node.js is much more complex than it was a few years ago when they implemented the website.  They implemented it in 2017.  They are telling me that they're going to need to charge $2,000 per month to maintain node.js because it's significantly more involved.  I'm having a really hard time believing that.  My question is when an even numbered release is in Active LTS or Maintenance LTS status, are the upgrades that involved to justify a $2,000/mo fee?  Thanks a ton for any insight.

**Comment by zorro2003** [comment]
Thanks so much for your response.  Very helpful!  I was really looking for level of effort between maintenance releases which seemed like a low effort and appreciate the confirmation.

Take care and thanks again!

Jesse

**Comment by PoojaDurgad** [comment]
@zorro2003 - is there anything pending in this issue?

**Comment by PoojaDurgad** [comment]
closing as resolved. please feel free to reopen the issue if that is not the case
