### ISSUE TITLE
why is nodejs console different with browser one? can we have a standard?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#2667]
* **Node.js Version**: any
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: code, runtime
* **Module (and version) (if relevant)**: console

**Comment by bnoordhuis** [comment]
Unclear question. Different how?

**Comment by puf17640** [comment]
why are you specifing so much information but do not explain what you really mean?

**Comment by anlexN** [comment]
something like [nodejs console docs](https://nodejs.org/api/console.html) say The global console object's methods are neither consistently synchronous like the browser APIs they resemble,

**Comment by devsnek** [comment]
Browsers and Node.js follow this standard: https://console.spec.whatwg.org/

**Comment by anlexN** [comment]
ok, in the case, you should update nodejs console module docs that says difference between them.
