### ISSUE TITLE
Declarative / Callback Style for Readable, pipe, etc

### ISSUE THREAD

**Issue by squarewav** [nodejs/help#2669]
Why do createReadStream, pipe and so many other function not use callback conventions? Just spit-balling here but would the following not be worlds better wrt error handling, resource leaks, etc?

```js
sendLogFile: function (path, resp, callback) {
    openReadStream(path, (err, rs) => {
        if (err) return callback(err);
        rs.pipe(resp, (err) => {
            rs.destory();
            return callback(err);
        });
    ...etc
```

**Comment by gireeshpunathil** [comment]
the pipe returns instead of calling back, so that chaining is possible.

I guess createReadStream returns instead of calling back due to its legacy nature (I may be wrong here)

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
