### ISSUE TITLE
Import Export

### ISSUE THREAD

**Issue by caperavensoftware** [nodejs/help#267]
Trying to run mocha with standard es6 modules.
I was told that it depends on the system it runs "node".
From what I recall you can use import to some degree but I thought I would just check in and see what the expact issue is with using import and export in nodejs as per es6?

Is this possible today or is there something we need to do?

**Comment by addaleax** [comment]
The short answer is “Node doesn’t support `import`/`export` yet”; a better, slightly longer answer is e.g. https://github.com/nodejs/node/issues/6526#issuecomment-231605096.

For now, if you really want to use `import`/`export`, you need to use a JS transpiler like [`babel`](https://github.com/babel/babel).

**Comment by caperavensoftware** [comment]
@addaleax thank you for your reply.
Some of the architects insist on using typescript but now they want to use async await and that only works if you transpile to es6.

I tried yesterday with piping it to mocha using babel and that works, but now you have "double" transpilation and I must say that I am not keen on that.

Adding injury to insult instabul also does not support es6 fully yet so you need to use esprima.
I think that as soon as nodejs starts supporting import/export out of the box much of this pain goes away, but we will have to wait a while. :)

**Comment by addaleax** [comment]
> I tried yesterday with piping it to mocha using babel and that works, but now you have "double" transpilation and I must say that I am not keen on that.

If you mean that `babel` is necessary as a second independent transpilation… there seem to be plugins for `babel` that support `async`/`await`. Haven’t used any of that myself, though.

> Adding injury to insult instabul also does not support es6 fully yet so you need to use esprima.

Have you seen/tried https://github.com/istanbuljs/nyc?

**Comment by kahwee** [comment]
You can try this too with mocha:

```
mocha --compilers js:babel-core/register
```

For information in [babel](https://babeljs.io/docs/setup/#installation), click on "Mocha".

**Comment by lordKnighton** [comment]
@caperavensoftware It look like these guys helped you out just fine.  Please close issue asap 👍
