### ISSUE TITLE
This application is only supported on Windows 8.1, Windows Server 2012 R2, or higher

### ISSUE THREAD

**Issue by charmickey** [nodejs/help#2671]
* **Node.js Version**: 14.1.0
* **OS**: Windows 7
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: -

Hello! The problem is command ```node -v``` in CLI  throws an error: "This application is only supported on Windows 8.1, Windows Server 2012 R2, or higher"
But command ```nvm list``` in CLI shows 14.1.0
What nodejs version is supported on Windows 7?

**Comment by Hakerh400** [comment]
See https://github.com/nodejs/node/pull/33108

**Comment by xCykrix** [comment]
@charmickey Hey! There are actually 2 PRs with alternatives to making Windows 7 an available but minimally supported platform. One uses a mutable warning that will be posted to all applications that run the Node.js binary, and the other requires an environment variable is set to enable using deprecated Windows operating systems.

If you want to show support for them, leave a comment or thumbs up the original post to get one of them landed in the future.

For now, you can use the latest v13.13.0 while we wait to see what happens. :slightly_smiling_face:

**Comment by Mustafa-Hayati** [comment]
This is the most ridiculous error I've ever seen. Don't ruin Node.js, please. Fix it, please.

**Comment by PoojaDurgad** [comment]
@charmickey - is this still an outstanding?

**Comment by Adriano87** [comment]
this application is only supported on Windows 8.1, Windows Server 2012 R2, or higher
Eu estou usando o windows 8
a versão do node que uso é Node.js	Node.js Foundation	12.19.0
a nova versão seria 14.15.0

**Comment by Adriano87** [comment]
this application is only supported on Windows 8.1, Windows Server 2012 R2, or higher

**Comment by Adriano87** [comment]
this application is only supported on Windows 8.1, Windows Server 2012 R2, or higher
Eu estou usando o windows 8
a versão do node que uso é Node.js Node.js Foundation 12.19.0
a nova versão seria 14.15.0

**Comment by soupIsTheCurrencyOfTheFuture** [comment]
Im getting this error running windows 8...

**Comment by Adriano87** [comment]
Exatamente isso
Eu uso o sistema operacional windows 8!!

**Comment by Adriano87** [comment]
Na verdade quando baixo a versão 14 em diante
O node funciona corretamente com a versão 13.14.0
Esse ocorre apartir da versão 14 em diante!!

**Comment by RedYetiDev** [comment]
This question was answered, closing as completed
