### ISSUE TITLE
npm ERR! error in C:\Users\Gauta\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\fsevents: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by baliyan9887** [nodejs/help#2672]
Please help me to out these problems I tried all the ways to create a new app Please let me how to resolve below errors - 

E:\worked>npm ls -g --depth=0
C:\Users\Gauta\AppData\Roaming\npm
+-- @types/react@16.9.34
+-- acorn@6.0.0
+-- babel-eslint@10.1.0
+-- create-react-app@3.4.1
+-- eslint@6.8.0
+-- gatsby-cli@2.12.8
+-- ink@2.7.1
+-- npm@6.14.4
+-- npx@10.2.2
+-- react@16.13.1
+-- rimraf@3.0.2
+-- webpack@4.43.0
`-- windows-build-tools@5.2.2

npm ERR! error in C:\Users\Gauta\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\fsevents: ENOENT: no such file or directory, open 'C:\Users\Gauta\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\fsevents\package.json'
npm ERR! peer dep missing: gatsby@^2.0.0, required by babel-plugin-remove-graphql-queries@2.9.0
npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-dynamic-import@4.0.0
npm ERR! error in C:\Users\Gauta\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents: ENOENT: no such file or directory, open 'C:\Users\Gauta\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\package.json'

* **Node.js Version**: v10.14.0
* **NPM Version**: 6.14.4

* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: gatsby,  Gatsby CLI version: 2.12.8

**Comment by bnoordhuis** [comment]
fsevents is a macos-only module, don't install it on windows.

**Comment by baliyan9887** [comment]
I've not installed fsevents. I just install the gatsby and get these error

**Comment by baliyan9887** [comment]
But in gatsby how can I solve below error


pngquant-bin@5.0.2 postinstall E:\worked\appp\node_modules\pngquant-bin
node lib/install.js

‼ spawn UNKNOWN
‼ pngquant pre-build test failed
i compiling from source
× Error: pngquant failed to build, make sure that libpng-dev is installed
at Promise.all.then.arr (E:\worked\appp\node_modules\bin-build\node_modules\execa\index.js:231:11)
at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: node lib/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Gauta\AppData\Roaming\npm-cache_logs\2020-05-04T05_39_57_172Z-debug.log

**Comment by bnoordhuis** [comment]
That looks to be an issue with pngquant, it probably doesn't support windows. Try getting in touch with the maintainers of that module.
