### ISSUE TITLE
Please help to handstand how to use protobuf and http/2 together

### ISSUE THREAD

**Issue by vhovvhannisyan** [nodejs/help#2673]
I wrote a code that uses protobuf and generates data then through HTTP / 2, I send this data to the client’s request, for small values, everything works fine, for example for 10 elements, for example, 1000 data does not work, I have the impression that packets are lost

//server.js
const http2 = require('http2');

const fs = require('fs');
const BalancesReadableStream = require('./balances/BalancesReadableStream')
const port = process.env.PORT || 8443;

const server = http2.createSecureServer({
    key: fs.readFileSync(__dirname + '/certs/localhost-privkey.pem', 'utf8'),
    cert: fs.readFileSync(__dirname + '/certs/localhost-cert.pem', 'utf8')
});

const ACCOUNT_COUNT = process.env.ACCOUNT_COUNT || 1000;
const VECTOR_COUNT = process.env.VECTOR_COUNT || 1;

function parseValue(value, base){
    const parsed = parseInt(value, base);
    if(isNaN(parsed)){
        throw new Error('Not a number');
    }
    return parsed;
}

const {
    HTTP2_HEADER_METHOD,
    HTTP2_HEADER_PATH
} = http2.constants

server.on('request', (req, res) => {
    // stream is a Duplex
    const accountCount =  parseValue(ACCOUNT_COUNT, 10);
    const vectorCount =  parseValue(VECTOR_COUNT, 10);
    const balancesReadableStream = new BalancesReadableStream(accountCount, vectorCount);
    balancesReadableStream.on('data', data => {
        let bp = res.write(data);
        if(!bp) {
            console.log(bp);
        }
    });

    balancesReadableStream.on('end', () => {
        res.end();
    });
});
///client.js
'use strict'

const http2 = require('http2');
const fs = require('fs');
const { messages } = require('./protos');

const client = http2.connect('https://localhost:8443', {
    ca: fs.readFileSync(__dirname + '/certs/localhost-cert.pem', 'utf8')
});

client.on('error', (err) => console.error(err));

const req = client.request({ ':path': '/stream' });

req.on('response', (headers, flags) => {
    for (const name in headers) {
        console.log(`${name}: ${headers[name]}`);
    }
});

req.on('data', (chunk) => {
    try{
        let balances = messages.Balances.deserializeBinary(Buffer.from(chunk));
        let msgId = balances.getMessageId();
        let elapsedTime = balances.getElapsedTime();
        const start = BigInt(elapsedTime);
        const end = process.hrtime.bigint();
        console.log(`message with ${msgId} arrived, Benchmark took ${end - start} nanoseconds ${(end - start)/BigInt(1000000)} ms`);
    } catch (e) {
        console.error(e.message);
    }
});

req.on('end', () => {
    client.close();
    client.destroy();
});

req.end();

**Comment by gireeshpunathil** [comment]
@nodejs/http2

**Comment by mcollina** [comment]
Please use `require('stream').pipeline` to pipe the streams together.
