### ISSUE TITLE
EHOSTUNREACH 224.0.0.251:5353 on 14.1.0 but not 14.0.0 or 12.16.3

### ISSUE THREAD

**Issue by macjeff** [nodejs/help#2675]
* **Node.js Version**: 14.1.0
* **OS**: Both Mac OS 10.9-10.15 and Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime bug
* **Module (and version) (if relevant)**: NPM (homebridge- https://github.com/homebridge/homebridge)

<!-- Please write your issue here and remove this line and the example code part. If relevant, provide some code following the example:

I am not an expert on this but when running 14.1.0 I get the error below but if I downgrade to 14.0.0 or run 12.16.3 (LTS) it works fine.  Error will come once in 24 hour period.   At first I thought it was just my system but posted on other forums and others reporting same issue on multiple mac and windows OS.   So I am putting it here.

this is the error I get usually during the night.   Again sorry if I dont give enough info here. I am trying to help you fix a bug and will do more testing if you want.   I only run ONE thing under NPM so not sure if its just with Homebridge or other things. 

Error: send EHOSTUNREACH 224.0.0.251:5353
at doSend (dgram.js:681:16)
at defaultTriggerAsyncIdScope (internal/async_hooks.js:313:12)
at afterDns (dgram.js:627:5)
at processTicksAndRejections (internal/process/task_queues.js:85:21)

**Comment by bnoordhuis** [comment]
I strongly doubt that a change in v14.1.0 was responsible but you can verify that by running `git bisect` on commits between v14.0.0 and v14.1.0. There are only about a hundred of them.

**Comment by macjeff** [comment]
Well I ran 14.0.0 for a few days and no issues.  then updated to 14.1.0 and within 24 hours I had the issue.  I left it another 24 hours and had it again.  Went to 12.16.3 for 2 days and no issue.  Just went back to 14.1.0.  If I get the issue I will roll back again to 14.0.0.   I posted and others said same issue since upgrading to 14.1.0.  So its not 100% sure yet but worse case I can go back to 12.16.3 and it works fine.

**Comment by bnoordhuis** [comment]
`EHOSTUNREACH` means the operating system reported that there's no connection (no route or path) between you and the destination.

Like I said, it's extremely unlikely that a change in Node.js is responsible for that. More likely it's an intermittent network fluke. Note that 224.0.0.251 is a mDNS address.

**Comment by macjeff** [comment]
Updated to 14.2.0.  Now 24 hours and no issues.   I will keep this open until Monday and close if no issues

**Comment by macjeff** [comment]
Version 14.2.0 has fixed the issue.
