### ISSUE TITLE
questions about node.js collaborator

### ISSUE THREAD

**Issue by XenoAmess** [nodejs/help#2676]
Hi. I want to ask about two things. 
1. how to become a node.js collaborator?
 2. How many node.js collaborators are now in the world?

**Comment by bnoordhuis** [comment]
1. If you send enough good enough pull requests or participate in the bug tracker, eventually someone will nominate you.

2. About 100 although some are a lot more active than others. Most day-to-day work is done by a group of 20 or 30 people.

**Comment by XenoAmess** [comment]
> 1. If you send enough good enough pull requests or participate in the bug tracker, eventually someone will nominate you.
> 2. About 100 although some are a lot more active than others. Most day-to-day work is done by a group of 20 or 30 people.

got it. thx.
