### ISSUE TITLE
how to build node file in mingw64 without vs settings

### ISSUE THREAD

**Issue by starhan** [nodejs/help#2678]
Hi,
  Now, I'm using mingw64 on win10. And I want to build some c++ files with nodejs. I have installed node-gyp. After node-gyp configure, it gens vxcproj file. But I want to use Makefile to build those c++ files(some c++ file include pthread.h). 
  Is there any way to do this? Thanks a lot.

**Comment by bnoordhuis** [comment]
Wrong repo, moved.

Short answer: you can't.

Longer answer: you can't, not for C++ source files - incompatible name mangling. C source files  using N-API probably work but that's untested.

**Comment by starhan** [comment]
thanks for answer. Wow not support. Bad news.

**Comment by starhan** [comment]
thanks for answer. Wow not support. Bad news.

**Comment by starhan** [comment]
thanks for answer. Wow not support. Bad news.

**Comment by bnoordhuis** [comment]
You can try clang-cl if that's an acceptable substitute for you. Its name mangling is (or should be) compatible with cl.exe.
