### ISSUE TITLE
CTRL + C could not kill node, and it would waste many memory which may make my device very slow. How to easily kill node process on Terminal ?

### ISSUE THREAD

**Issue by assmdx** [nodejs/help#2679]

**Comment by bnoordhuis** [comment]
What's your question?

**Comment by assmdx** [comment]
> What's your question?
how to kill node program on terminal
, for example: node server.js

**Comment by ORESoftware** [comment]
listen for a signal

```js

process.once('SIGINT', s => {
   // cleanup
   // exit
});

process.once('SIGTERM', s => {});

```

sometimes bash doesnt forward signals to subprocs, so you may need to send a signal to the proc directly given the pid

**Comment by assmdx** [comment]
> listen for a signal
> 
> ```js
> process.once('SIGINT', s => {
>    // cleanup
>    // exit
> });
> 
> process.once('SIGTERM', s => {});
> ```
> 
> sometimes bash doesnt forward signals to subprocs, so you may need to send a signal to the proc directly given the pid

It doesn‘t work for me.
```
var express = require('express')
var app = express()

// respond with "hello world" when a GET request is made to the homepage
app.get('/', function (req, res) {
  res.send('hello world')
})

app.listen(22020, () => {
    console.log('server is listen on 22020 now!');
});

process.once('SIGINT', s => {
    // cleanup
    // exit
    console.log('get SIGINT', s);
    process.exit();
 });
 
 process.once('SIGTERM', s => {
    console.log('get SIGTERM', s);
    process.exit();
 });
```

And I tried kill the process by CTRL + C. and node process still listen at 22020 port.

**Comment by ORESoftware** [comment]
get the pid, and do 

```
kill -INT <pid>
```


like is said, bash doesnt always forward the signal from parent to child process in some edge cases.

you can log the node pid with

```
console.log(process.pid)

```

you will figure out how to do it better later

**Comment by assmdx** [comment]
> get the pid, and do
> 
> ```
> kill -INT <pid>
> ```
> 
> like i said, bash doesnt always forward the signal from parent to child process in some edge cases.
> 
> you can log the node pid with
> 
> ```
> console.log(process.pid)
> ```
> 
> you will figure out how to do it better later

Thank you , I use `` kill -9 $(lsof -t -i:22020)`` and finally fix it .
