### ISSUE TITLE
When I type "hexo d", an error is reported：TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object

### ISSUE THREAD

**Issue by wsp666** [nodejs/help#2680]
* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by YuleZhang** [comment]
> * **Version**:
> * **Platform**:
> * **Subsystem**:
> 
> ### What steps will reproduce the bug?
> ### How often does it reproduce? Is there a required condition?
> ### What is the expected behavior?
> ### What do you see instead?
> ### Additional information

Have you finished this problems?

**Comment by PoojaDurgad** [comment]
@wsp666 - is this issue resolved? can you elaborate your issue more please?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
