### ISSUE TITLE
max-old-space-size could be consider deprecated on > 12?

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/help#2681]
* **Node.js Version**: 12>
* **OS**: Linux

Hello all!

I have a doubt about usage of `max-old-space-size` cli on Node 12>. According of [this post](https://medium.com/@nodejs/introducing-node-js-12-76c41a1b3f3f)

> This update will configure the JavaScript heap size based on available memory instead of using defaults that were set by V8 for use with browsers. In previous releases, unless configured, V8 defaulted to limiting the max heap size to 700 MB or 1400MB on 32 and 64-bit platforms respectively. Configuring the heap size based on available memory ensures that Node.js does not try to use more memory than is available and terminating when its memory is exhausted.

> This is particularly useful when processing large data-sets. As before, it will still be possible to set — max-old-space-size to use a different limit if the default is not appropriate for your application. 

I do not understand how set manually `max-old-space-size` can be good, consider that is already automatic on node > 12.

Thanks!

**Comment by addaleax** [comment]
@RafaelGSS Just because Node.js now configures the heap limits based on more sensible defaults, that doesn’t mean that there aren’t still limits and that you may want to expand or shrink them.

**Comment by RafaelGSS** [comment]
@addaleax thanks for the reply. So, it still has a default size, and which is? Have a doc about it?

**Comment by bnoordhuis** [comment]
> it still has a default size

What does "it" refer to in this sentence? `--max-old-space-size` or the auto-tuned default?

The former you can see in the output of `node --v8-options`, the latter is explained in the blog post you linked to.

**Comment by RafaelGSS** [comment]
It is about first option. Thanks so much! @bnoordhuis.
