### ISSUE TITLE
Retrieve Node.js root certificates from native addon or JS code?

### ISSUE THREAD

**Issue by JCMais** [nodejs/help#2682]
* **Node.js Version**: >= 10
* **OS**: Any
* **Scope (install, code, runtime, meta, other?)**: native addons

The root certs used by Node.js are defined on [`node_root_certs.h`](https://github.com/nodejs/node/blob/86fdaa745572a3bec4370ac7bd05d18e6bf64c01/src/node_root_certs.h)

Is there any way to access them from a native addon or JS code?

**Comment by addaleax** [comment]
Is `tls.rootCertificates` what you are looking for?

**Comment by JCMais** [comment]
Yep, that was exactly it, thank you @addaleax
