### ISSUE TITLE
how to use HTTP/2 module?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#2683]
* **Node.js Version**: all
* **OS**: all
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http/2

official docs [http/2 module](https://nodejs.org/dist/latest-v12.x/docs/api/http2.html) , there is very few code snippet, i can't understand. for example, how to set up post rest api endpoint, can you give me some demos?

**Comment by gireeshpunathil** [comment]
@anlexN - is this still an issue?

IIUC, the `stream` event and its handler on the server is enough to handle POST requests, but I may be wrong. /cc @nodejs/http2

**Comment by anlexN** [comment]
Yes, and now i am reviewing nodejs source code. just now, i have done learned C++ syntax. so much time to learn. oh my god. 2 weeks.

**Comment by gireeshpunathil** [comment]
@anlexN - let me know if this is a close candidate

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
