### ISSUE TITLE
i have got hanged up here 

### ISSUE THREAD

**Issue by ghost** [nodejs/help#2684]
![Screenshot (1)](https://user-images.githubusercontent.com/63095784/81405721-da5d0b80-9155-11ea-91e4-741d09365f84.png)
actually i got stucked up here and i am not able to create a react app further since i have tried uninstalling it and again reinstalling the node.js but even nothing worked out here i don't know what i should do further and even i have tryed updating it but nothing is working out !!!!!!!    please provide a solution soon

**Comment by PoojaDurgad** [comment]
@ghost - for me with your issue looks similar to  https://github.com/facebook/react/issues/17196 try this . not sure, I hope it may help.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
