### ISSUE TITLE
Error: EINVAL: invalid argument, mkdir 'C..... when install create-react-app

### ISSUE THREAD

**Issue by nhoiyee** [nodejs/help#2685]
I used this:

npx create-react-app my-app
cd my-app

when I entered

npm start

I got this error.:

<img width="573" alt="Untitled" src="https://user-images.githubusercontent.com/62700570/81410950-2e76e880-9174-11ea-974e-b8a2c3a9ffd1.png">

what should I do to install create-react-app?

**Comment by PoojaDurgad** [comment]
@nhoiyee - is this issue resolved? with your issue I'm guessing your path statement may be messed up try using a new directory and there is a new way to create react-app `npm init react-app my-app` or `(npm create react-app my-app)` this will run `npx create-<name> <args>` hope it may help https://github.com/facebook/create-react-app/issues/4578

**Comment by PoojaDurgad** [comment]
closing as answered. please feel free to reopen the issue if its still outstanding.
