### ISSUE TITLE
missing items in process.argv when using node -e

### ISSUE THREAD

**Issue by atuttle** [nodejs/help#2686]
* **Version**: 12.16.1
* **Platform**: Darwin Adams-iMac.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
* **Subsystem**: ?

### What steps will reproduce the bug?

    $ echo "'{\"foo\":\"bar\"}'" | node -e 'console.log(process.argv)'

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

Expected log: 

    [ '/usr/local/bin/node', '{"foo":"bar"}' ]

### What do you see instead?

    [ '/usr/local/bin/node' ]

### Additional information

I'm attempting to use a simple `node -e` command to process the JSON output of another CLI command. Expected workflow was:

    $ something-produces-json | node -e '...'

where `...` would be a one-liner to handle the JSON appropriately.

The [CLI arguments docs](https://nodejs.org/en/knowledge/command-line/how-to-parse-command-line-arguments/) don't mention `node -e` at all, so I'm not sure if this is expected behavior or a bug.

**Comment by addaleax** [comment]
If something is passed into Node.js as stdin, as in your examples, then it will also be available in the Node.js process as a stream at `process.stdin`.

If you want something to be an entry in `process.argv`, it needs to be passed to Node.js as an argument – e.g. ``node -e '...' `something-procudes-json` ``, maybe that is what you are looking for?

**Comment by atuttle** [comment]
That does work, thank you.
