### ISSUE TITLE
problem with NODE

### ISSUE THREAD

**Issue by mitko1717** [nodejs/help#2687]
i start learn JS. and i was learning it with one inline-course. there was a way to building land-page with node. i downloaded it, and made everything in manual of my teacher, my node worked, i could create the folders, npm and connect it with github i guess. 
but i screwed up with my learning and decided to start over with my online course.

so, i deleted old project, and when i came back to NODE, it doesn't work. a read a lot of stuff, redownloaded a couple of times the application. 

and i know about command prompt. there i can see my version or something but i cant work with my folder

[thats my screenshot](https://sun6-19.userapi.com/qlM8uEPg_xujEUVIKpVT6PgMviup2I7ciG04vA/OihRA4fECos.jpg) 

in NODE i can make console.log and some math function, but when a add folder from my pc it doesn`t work. i always see "Uncaught ReferenceError: node is not defined" or "Uncaught SyntaxError: Invalid or unexpected token"

please help me 

[thats my screenshot](https://sun6-19.userapi.com/qlM8uEPg_xujEUVIKpVT6PgMviup2I7ciG04vA/OihRA4fECos.jpg)

**Comment by gireeshpunathil** [comment]
from your screenshot it is evident that you are issuing commands in the Node.js' shell (also known as REPL) that should be executed in the operating system's shell (MS-DOS prompt in this case)

here is the doc for REPL: https://nodejs.org/dist/latest-v16.x/docs/api/repl.html . You can run small JS expressions in the REPL. However if you are looking for building applications that persist, you could write your program in a file, save it, and execute that from the prompt like `node foo.js` where `foo.js` is the name of the program.

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if this is still outstanding.
