### ISSUE TITLE
Getting an error while starting npm after sucessfull installation of it

### ISSUE THREAD

**Issue by shashankhb** [nodejs/help#2688]
![Capture](https://user-images.githubusercontent.com/25588597/81476644-968b0480-9230-11ea-886a-03a0b07d0160.JPG)
I have installed npm but while entering command "npm start" it's showing an error can anyone help me to solve this issue! thanks in advance.

C:\Users\vinay>npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\vinay\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\vinay\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vinay\AppData\Roaming\npm-cache\_logs\2020-05-09T14_00_58_853Z-debug.log

**Comment by gireeshpunathil** [comment]
@shashankhb - is this still an issue? fi so, what you are trying to start?
