### ISSUE TITLE
How do I use the local built headers to build native?

### ISSUE THREAD

**Issue by jrgleason** [nodejs/help#2689]
* **15.0.0-pre**:
* **OSX**:
* **Headers (node-v15.0.0-pre-headers.tar.gz)**:

I am building node from source like this...
 
```
./configure --release-urlbase=/.../Code/node
make DISTTYPE=custom CUSTOMTAG=pre tar-headers
make
make install
```

When I run `node -p process.release` I see...

```
{
  name: 'node',
  sourceUrl: '/.../Code/nodev15.0.0-pre/node-v15.0.0-pre.tar.gz',
  headersUrl: '/.../Code/nodev15.0.0-pre/node-v15.0.0-pre-headers.tar.gz'
}
```

But when I run npm install I get...

```
info DIST Downloading distribution files.
http DIST       - https://nodejs.org/dist/v15.0.0-pre/SHASUMS256.txt
http DIST       - https://nodejs.org/dist/v15.0.0-pre/node-v15.0.0-pre-headers.tar.gz
ERR! OMG Error: incorrect header check
ERR! OMG     at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
ERR! OMG Error: incorrect header check
ERR! OMG     at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
What am I missing?

**Comment by bnoordhuis** [comment]
No surprise, they need to be actual URLs. Litmus test: if `url.resolve()` won't accept it, then neither will node-gyp.

I'm closing this but let me know if you have follow-up questions.

**Comment by bnoordhuis** [comment]
Let me trim that down to just "need to be actual URLs" - `url.resolve()` is notoriously forgiving in what it accepts, hence why it was superseded by the `URL` class. :-)

The tl;dr: must be HTTP or HTTPS URLs.

**Comment by bnoordhuis** [comment]
And sorry about closing, I thought this was posted in nodejs/node-gyp for some reason.

**Comment by gireeshpunathil** [comment]
@jrgleason - is this resolved?

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if you still have issue
