### ISSUE TITLE
https API call is not working while calling with client certificate

### ISSUE THREAD

**Issue by prapakaransp** [nodejs/help#2692]
* **Node.js Version**:v10.16.3
* **OS**:Mac
* **Scope (install, code, runtime, meta, other?)**:runtime
* **Module (and version) (if relevant)**:"https": "^1.0.0"

Issue description
I have created a client certificate(self-signed for two way SSL call for calling REST service. In node js, i am getting the error below. 
**{ Error: write EPROTO 4484117952:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1536:SSL alert number 42
at WriteWrap.afterWrite (net.js:788:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }**

steps for a generatining SSL certificate on client-side.
https://docs.mulesoft.com/runtime-manager/rtm-agent-REST-connections#insecure-connection-channel (refer the section : Submit Two-Way TLS REST Requests)
**************************************************
Steps for SSL 

```js
router.get('/', (request, reseponse) => {
  debugger
  const options = {
    hostname: '******************',
    port: 9999,
    path: '/mule/agent/applications/',
    method: 'GET',
    cert: fs.readFileSync('/Users/4556/OneDriveLocal/reactportal/catalyst-mule-agentservice/src/routes/clientkeystore.pem') ,
    passphrase: "**********"
  }

  const req = https.request(options, res => {
    console.log(`statusCode: ${res.statusCode}`)
    require("tls").DEFAULT_ECDH_CURVE = "auto"
  
    res.on('data', d => {
      process.stdout.write(d)
    })
  })

**Comment by gireeshpunathil** [comment]
@prapakaransp - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
