### ISSUE TITLE
my project is working fine in development server and i wanted to deploy that into git hub pages but is not allowing me to do that.when i enter "npm run deploy" this occurs

### ISSUE THREAD

**Issue by Dhanushreddy09** [nodejs/help#2694]
* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by gireeshpunathil** [comment]
@Dhanushreddy09 - is this still an issue?

> "npm run deploy" this occurs

what happens when you do that?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
