### ISSUE TITLE
Use node using fetch script

### ISSUE THREAD

**Issue by mohsen2014** [nodejs/help#27]
Our company uses software that makes web app. All pages by jquery, html is made. In this case, the page after making a code stored in the database and each time Web service and then fetch the page html, jquery to together and it gives iis.
Is there a way we can make any file without using code fetch from the database instead of the node and frameworks used jquery
Sorry if English is not good
Thank you for answers

**Comment by Trott** [comment]
I'm sorry. I do not understand. What language do you speak? We may be able to find someone who can translate.

**Comment by waqasmughal** [comment]
@mohsen2014  i understand what you talking about . there is another way use cdn and like jquery load  from google server rather than yours .
