### ISSUE TITLE
Need a way to configure http pool not for per host but for all hosts.

### ISSUE THREAD

**Issue by namhong2001** [nodejs/help#2701]
**Is your feature request related to a problem? Please describe.**
I want to flatten network load, so thought pooling outgoing http requests with restricted max sockets.  But current http agent only pooling requests per host, so I cannot achieve restricting total max sockets.

**Describe the solution you'd like**
Http agent option to set max sockets in total.

**Describe alternatives you've considered**
Http agent classify requests by host and port, so make a local proxy server and proxy all requests to that server.

**Comment by bnoordhuis** [comment]
The `maxFreeSockets` option to the `http.Agent` constructor covers that, if I understand your question correctly. If not, can you elaborate?

**Comment by namhong2001** [comment]
Hi
I eventually figure out what I need is not pool but queue indeed. Restricting concurrency requests is what I wanted, but actually pool is for restricting sockets not requests so not suit for this job.
Thanks @bnoordhuis anyway and I would close this comment
