### ISSUE TITLE
Problemas al instalar paquetes vía npm

### ISSUE THREAD

**Issue by Jemendieta** [nodejs/help#2703]
* **12.16.3**:
* **Windows 10**:
* **Subsystem**:

### What steps will reproduce the bug?

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3..

**Comment by PoojaDurgad** [comment]
@Jemendieta - can you elaborate your issue more please? what command you are trying to run?

> npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3..

By looking at the error log we may say core-js needs to be updated to the version above 3 and also try to update the dependencies to the version of core-js@3..

**Comment by PoojaDurgad** [comment]
inactive . closing!! please let me know if its still outstanding
