### ISSUE TITLE
Creating React App on Windows

### ISSUE THREAD

**Issue by Bambillo1** [nodejs/help#2706]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:
 

When I enter the following:

```js
npx create react app myportfolio
```

 using npm on my command prompt interface: the error in the screenshot surfaces:
[Create react npm error.docx](https://github.com/nodejs/help/files/4638341/Create.react.npm.error.docx)

How can it be resolved as I cannot continue to building my app again? Is their any way of creating react app without using npm?

**Comment by Hakerh400** [comment]
Command

```
npx create react app myportfolio
```

should be

```
npx create-react-app myportfolio
```

How is your screenshot related to this command? In the screenshot I see you executing command
`npx i axios`, which has incorrect syntax. It should be `npm i axios` (note that `npm` and `npx` are not the same thing).

**Comment by PoojaDurgad** [comment]
@Bambillo1 - is this issue resolved ? did @Hakerh400 's suggestion help you to resolve the issue?

**Comment by PoojaDurgad** [comment]
inactive . closing! please feel free to reopen the issue if that is not the case.
