### ISSUE TITLE
ERR_INTERNAL_ASSERTION

### ISSUE THREAD

**Issue by gondone666** [nodejs/help#2708]
* **Node.js Version**: v15.0.0-nightly20200516b533fb3508
* **OS**: Windows 10 x64
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: https, h2-wrapper (https://github.com/gondone666/h2-wrapper/blob/master/index.js)

I made multiple requests to the server and all reqs work well, but one causes an error.
Responses of all requests are the same 
```
internal/assert.js:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (internal/assert.js:14:11)
    at TLSSocket.socketOnData (_http_client.js:511:3)
    at TLSSocket.emit (events.js:327:22)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:281:9)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:191:23) {
  code: 'ERR_INTERNAL_ASSERTION'
}
```
```js
self.res = { _headers: options.headers,headers: res.headers, data: [], url: options.url, httpVersion: self.sessions[options.origin].version};
res.on('data', function (chunk) {
	self.res.data.push(chunk);
});
res.on('end', () =>Promise.all([self.decodeReseponse(), self.setCookies()]).then(() => resolve(self.res)));
```

**Comment by hnviradiya** [comment]
We are also facing this in 12.x (we are using AWS lambda), we have so many requests and this occurs around 30% of requests.

**Comment by Trott** [comment]
I'm going to close this and point people to https://github.com/nodejs/node/issues/35384. (@gondone666 If you are still experiencing this and are able to share your code so the core team can figure out what's going on, please comment in that issue. Thanks!)
