### ISSUE TITLE
where is nodejs roadmap?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#2709]
* **Node.js Version**: latest
* **OS**: all
* **Scope (install, code, runtime, meta, other?)**: all
* **Module (and version) (if relevant)**: all

[deno](https://github.com/denoland/deno) is so awesome, but i want to know nodejs **future**.

**Comment by bnoordhuis** [comment]
There isn't one. Plenty of strategic initiatives though: modules, quic, openssl 3, etc.

**Comment by anlexN** [comment]
can you make a roadmap?

**Comment by BridgeAR** [comment]
That is unlikely. Node.js is driven by people investing their private time and only few are paid to work on it. The strategic initiatives are the main goals some people work on.

**Comment by anlexN** [comment]
what do you think of nodejs and deno?

**Comment by BridgeAR** [comment]
@anlexN I enjoy writing JavaScript and thus it's great to have good runtimes. I am going to close this since the original question seems to be answered.
