### ISSUE TITLE
Cannot read output from another node process installed with snap

### ISSUE THREAD

**Issue by angryziber** [nodejs/help#2713]
When node is installed via snap (14/stable channel).

`execSync('node something').toString()` always returns an empty string with no errors.
This is a problem as many transforming packages use this trick to deasync processing.

`execSync('node something', {stdio: 'inherit'}).toString()`
would correctly display the output in parent process's stdout, but there is no way of capturring it.

If node is installed via deb package, there is no such problem.

Makes jest/etc unusable in many cases.

**Comment by bnoordhuis** [comment]
That's almost certainly caused by snap's security sandbox. Try getting in touch with the maintainer of the node snap, he or she can probably provide more details.

**Comment by angryziber** [comment]
The problem is only when node reads output of another node.
No problems with reading output of other apps, nor other apps reading output of node...

**Comment by angryziber** [comment]
Added issue here: https://github.com/nodesource/distributions/issues/1053

**Comment by gireeshpunathil** [comment]
@angryziber - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
