### ISSUE TITLE
How to convert Buffer(http package) into http.ClientRequest or http.ServerResponse into Buffer(http package)?

### ISSUE THREAD

**Issue by jacksonfu** [nodejs/help#2714]
**Is your feature request related to a problem? Please describe.**
After embedding node.js into my cpp app, I want to convert data(already node.js Buffer), which 
 is a http package(binary) and read in cpp, into `http.ClientRequest` in node.js script, because I would like to process http requests in node.js. In addition, node.js don't need to listen ports and call http.createServer. In the end, node.js script will return `http.ServerResponse` to cpp, which will converted into buffers.

**Describe the solution you'd like**
Please describe the desired behavior.
I wonder if there is an api already in node.js like stream.encode() and it can straightly help a lot in this situation. Furthermore, a handle can passed to `IncomingMessage.prototype._read` or `OutgoingMessage.prototype._send` to fetch the http buffers.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
Also, I try to find some useful codes in http.js(or more) and Imitate.

Many thanks for response!!!

**Comment by squarewav** [comment]
I have no idea but I stumbled onto this project:

  https://github.com/dcodeIO/node-memcpy

which has code that directly manipulates Buffer and ArrayBuffer in cpp. Maybe it will give you some ideas.

**Comment by jacksonfu** [comment]
> I have no idea but I stumbled onto this project:
> 
> https://github.com/dcodeIO/node-memcpy
> 
> which has code that directly manipulates Buffer and ArrayBuffer in cpp. Maybe it will give you some ideas.

thx. Maybe I don't clearly describe my requirement.
In my situation, input is already a `Buffer` object, which should be converted to `http.ClientRequest` object. And output is `http.ServerResponse`, which should be converted to a `Buffer` object.

**Comment by jacksonfu** [comment]
I have read some node.js source codes (http_parser.cc and more), and partly understood the parse process in node.js so far. `http.ClientRequest` and `http.ServerResponse` object have some redundancy fields in my usage, such as socket. 
Now, I try to encapsulate parse event(such as kOnMessageComplete) to a promise, and store it in `HttpParser` object or other objects.
Maybe I will use it as follows:
```javascript
// reqBuf: Buffer
async function process(reqBuf) {
  req = await decode(reqBuf); // req: http.ClientRequest
  // rsp: http.ServerResponse
  rsp = somefun(req); // node.js code to handle the request
  rspBuf = await encode(rsp); // rspBuf: Buffer
  return rspBuffer;
}
```

**Comment by gireeshpunathil** [comment]
@jacksonfu - is this still outstanding?

your approach looks good by the way, and I am not aware of any capability that will convert a JS buffer into a CPP object of your custom type.

**Comment by jacksonfu** [comment]
> @jacksonfu - is this still outstanding?
> 
> your approach looks good by the way, and I am not aware of any capability that will convert a JS buffer into a CPP object of your custom type.

Not a CPP object but a object that js script can directly use. And http-parser in node.js helps a lot.
