### ISSUE TITLE
openssl 1.0.2 support on nodejs 12.16.0 

### ISSUE THREAD

**Issue by kemaangu** [nodejs/help#2715]
Node.js 12.16.0:
linux 4.9 kernel:
ARM v7 Cross Compile:
Openssl  1.0.0

Hi 
I am cross compiling nodejs 12.16.0  for ARM v7 platform, and using openssl  1.0.2j/q (libssl.so.1.0.0/libss1.so.1.0.2)library. I am facing the error on  EVP_MD_CTX_free/HMAC_CTX_free as declaration unavailable. Below is error:   

ERROR: oe_runmake failed
| In file included from ../src/node.cc:42:0:
| ../src/node_crypto.h:70:46: error: 'EVP_MD_CTX_free' was not declared in this scope
|  using EVPMDPointer = DeleteFnPtr<EVP_MD_CTX, EVP_MD_CTX_free>;
|                                               ^~~~~~~~~~~~~~~
| ../src/node_crypto.h:70:61: error: template argument 2 is invalid
|  using EVPMDPointer = DeleteFnPtr<EVP_MD_CTX, EVP_MD_CTX_free>;
|                                                              ^
| ../src/node_crypto.h:591:25: error: 'HMAC_CTX_free' was not declared in this scope
|    DeleteFnPtr<HMAC_CTX, HMAC_CTX_free> ctx_;
|                          ^~~~~~~~~~~~~
| ../src/node_crypto.h:591:38: error: template argument 2 is invalid
|    DeleteFnPtr<HMAC_CTX, HMAC_CTX_free> ctx_;

But these declaration are present in libssl.so.1.1.0. Can I get any resource/patch being backported for libssl.so.1.0.0/libssl.so.1.0.2 in nodejs-12.16 or similar nodejs version being provided support of libssl.so.1.0.0 instead of libssl.so.1.1.0.

**Comment by richardlau** [comment]
> But these declaration are present in libssl.so.1.1.0. Can I get any resource/patch being backported for libssl.so.1.0.0/libssl.so.1.0.2 in nodejs-12.16 or similar nodejs version being provided support of libssl.so.1.0.0 instead of libssl.so.1.1.0.

Not officially as we've never built Node.js 12 with OpenSSL 1.0.2 (see https://github.com/nodejs/TSC/blob/master/OpenSSL-Strategy.md). Some Linux distributions do build against OpenSSL 1.0.2, e.g. Centos/Red Hat (https://cbs.centos.org/koji/rpminfo?rpmID=193439) so you could try applying the patches from their source rpm (https://cbs.centos.org/koji/buildinfo?buildID=29041).

**Comment by kemaangu** [comment]
Hi 
Thank you for your valuable input. I  apologise for delayed reply.
