### ISSUE TITLE
is there side effect when return functional parameter 

### ISSUE THREAD

**Issue by Djunnni** [nodejs/help#2717]
i have wondering this side effect in node

ex) 
when using lodash , 
const example = (plan : Object) => {
_.set(plan,'item',xx);
return plan;
}

example function parameter plan is updating by set (lodash) then return plan .

i think it is violated, so. i think it's right 
const example = (plan : Object) => {
/* ***
 const temp_obj : plan object deep copy
*** */
_.set(temp_obj,'item',xx);
return temp_obj;
}

what happen?

**Comment by Hakerh400** [comment]
Assuming you meant `_.set(plan,'item',xx)` instead of `_.set(Object,'item',xx)`, the answer is yes. Modifying an object that is passed as an argument does have side effects.

**Comment by Djunnni** [comment]
@Hakerh400 
then, we use variables using Object that deep copied except for parameter in function
