### ISSUE TITLE
nodejs install but not runing

### ISSUE THREAD

**Issue by rahulmandkriya** [nodejs/help#272]
Hello,

I have Ubuntu 14.04.1 LTS server and connect with using ssh command
I installed node v5.12.0 version
Now i am running a simple program of nodejs

File name : server.js
var http = require("http");
http.createServer(function (request, response) {
response.writeHead(200, {'Content-Type': 'text/plain'});
response.end('Hello World\n');
}).listen(8081);
console.log('Server running at http://127.0.0.1:8081/');

go to directory where put server.js

user@server_ip:/opt$ node server.js then press enter It's showing Server running at http://127.0.0.1:8081/
After that i am running server_ip:8081 at browser but it's loading possess long time

**Comment by addaleax** [comment]
can you show the output of `netstat -natp | grep 8081` while server.js is running?

**Comment by lordKnighton** [comment]
did you just installed it, before running this program? 

You're code works fine, But i think it's something on your local system
