### ISSUE TITLE
NAN compatibility issues when moving from Node 10 -> 12 -> 14

### ISSUE THREAD

**Issue by sregger** [nodejs/help#2722]
* **Node.js Version**: 14.2.0, 12.16.3, 10.19.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: NaN

I'm using an out of date nodejs module (the [sspi-client](https://github.com/tvrprasad/sspi-client)) which has forced my project to be stuck on **Node 10**. I'd like to solve that by contributing a PR to this library. The error I see, if we move past **Node 10**, is

> error C2660: 'v8::Value::BooleanValue': function does not take 0 arguments

Looking into the issue the 0 arg BooleanValue function was removed. It was replaced by the `Context` versions as detailed in [this issue](https://github.com/bcoin-org/bcrypto/issues/7).

With this info in hand I [forked and upgraded](https://github.com/sregger/sspi-client/commit/47209609b563d8ae39a3f01f9c0023037c73d5e2) the module. That worked well for **Node 12**. However I ran into numerous issues running the modules tests and got side tracked / lost interest. Now with a renewed interest I got the tests to an _okay_ (sort of) state. But I  noticed that last time I only tried the stable release of Node (12). Assuming the latest, **Node 14**, would be fine I checked it out and ran an install. I saw the following error

> error C2664: 'v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate *) const': cannot convert argument 1 from 'v8::Local<v8::Context>' to 'v8::Isolate *'

Re-checking **Node 12** I also see a warning

> warning C4996: 'v8::Value::ToBoolean': was declared deprecated

I was able to "fix" the code for **Node 14** using

    info[0]->BooleanValue(Nan::GetCurrentContext()->GetIsolate())

But that, in turn, causes errors with **Node 10**. e.g.

    error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>'

What is the correct upgrade path here?

**Comment by bnoordhuis** [comment]
Try `Nan::To<bool>(info[0]).FromJust()`. Or better yet:
```c++
bool on;
if (!Nan::To<bool>(info[0]).To(&on)) {
  // exception pending
} else if (on) {
  // ...
} else {
  // ....
}
```

**Comment by sregger** [comment]
Spot on @bnoordhuis. That works perfectly across all 3 versions of Node. Thank you. 

PS: Any chance you know the upgrade path for

    callback->Call(4, argv);

which produces

> warning C4996: 'Nan::Callback::Call': was declared deprecated

It's only a warning but figure if I can I should tidy it up too.

**Comment by bnoordhuis** [comment]
You're probably looking for `Nan::Call()`. It also works with a `Nan::Callback`:
```c++
Local<Value> retval;
if (Nan::Call(callback, recv, 4, argv).To(&retval)) {
  // ...
} else {
  // exception pending
}
```
`recv` is the receiver, the `this` object. It needs to be _something_ but you can always use `Nan::GetCurrentContext()->Global()` to use the global object (i.e., `globalThis`.)

**Comment by sregger** [comment]
Thanks for all the help @bnoordhuis. That answers my question.
