### ISSUE TITLE
Problema al usar comandos de módulos instalados

### ISSUE THREAD

**Issue by Carlos-Martinezz** [nodejs/help#2723]
* **Node.js Version: v12.16.3**:
* **Windows 10 **:
* **Scope (install, code, runtime, meta, other?)**:
* **Moduls: httpster & node-dev**:

**Problema:**
La consola de comandos de Windows no reconoce los comandos de los módulos instalados con npm, al parecer podría ser un problema con las variables PATH pero no he conseguido resolverlo.

**Error:**
PS C:\Users\myuser\Desktop\CursoNodeJS\Reinicio> httpster -p 3000 -d ./public
httpster : El término 'httpster' no se reconoce como nombre de un cmdlet, función, archivo de script o programa     
ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha     
ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ httpster -p 3000 -d ./public
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (httpster:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DigitalMoster** [comment]
Hellow Carlos
Tenes que probar de esta manera :
/////////////////////////////////////////////////////
npx nodemon hhtpster -p 3000 -d ./public
/////////////////////////////////////////////////////

/*nodemon es opcional si lo tenes entre tus dependencias obvió*/

Además de claro esta que tenes que instalar npm y httpster ( nodemon es opcional jajajajaja) listo eso es todo espero haberte ayudado.

**Comment by RedYetiDev** [comment]
Hi! The Node.js maintainers primarily communicate in English. It seems like your issue is not in English, which may make it difficult for us to understand and provide assistance. Could you please translate your issue to English? Thank you!
