### ISSUE TITLE
Need help related to Add another Page

### ISSUE THREAD

**Issue by ashishsme14** [nodejs/help#2726]
We have Given task as per attach file, for which we had written code as -

But it is not working, please suggest
![Add another Page](https://user-images.githubusercontent.com/61864865/82832270-4078bb00-9ed8-11ea-8999-e5cd30625ead.JPG)

```

var express = require('express');
var app = express();

app.get('/', function(req, res) {
res.send = ('Hello, World!');
});

app.get('/second', function(req, res) {
res.send = ('Build another page now');
});

var server = app.listen(8000, function() {
 var host = server.address().address;
 var port = server.address().port;
console.log(`Build another page now http://%s:%s` host, port);
});
```
-->

**Comment by Hakerh400** [comment]
Remove `=` after `res.send`

**Comment by ashishsme14** [comment]
Did same but test case did not passed

**Comment by Hakerh400** [comment]
> Did same but test case did not passed

Which test? Are you using some program to test your app? What is the program on your screenshot?

**Comment by ashishsme14** [comment]
![Add another Page 1](https://user-images.githubusercontent.com/61864865/82895177-6a31f080-9f71-11ea-8587-b7efe56bf509.JPG)

See test result not passed.
