### ISSUE TITLE
how to manage variable called by reference in Node.js?

### ISSUE THREAD

**Issue by Djunnni** [nodejs/help#2727]
hi, i have question about "how to manage variable called by reference in Node.js"

when we use C language, we are allocating for variable then dealloc.

but in nodejs. how to manage about garbage collection?

**Comment by ORESoftware** [comment]
no need to alloc/malloc

a good way to mutate a primitive from within a function is to wrap the primitive in a container object

**Comment by Djunnni** [comment]
@ORESoftware 
oh, sorry i have question about garbage collection handling

**Comment by gireeshpunathil** [comment]
@Djunnni - is this still an issue?
