### ISSUE TITLE
Install nodejs on NetBSD (apple capsule) for homebridge

### ISSUE THREAD

**Issue by exrector** [nodejs/help#2728]
Hey.  I am inspired by the article https://m.habr.com/en/post/501404/ (you will understand it because there is a lot of code) here it is described how to get root access to apple time capsule.  Based on this, I decided that you can install nodejs on netbsd as a package.  therefore, you can install homebridge for homekit (homebridge.io).  Do you have any ideas?

**Comment by gireeshpunathil** [comment]
@exrector - is this still outstanding?

**Comment by exrector** [comment]
> @exrector - это все еще выдающееся?

I have no ideas😕
