### ISSUE TITLE
How to secure udp for multiplayer ?

### ISSUE THREAD

**Issue by extremety1989** [nodejs/help#2729]
v12.7.0
linux
nodejs  udp4,dgram module

i want to build multiplayer game.
I did a lot of research for " how to secure nodejs udp  and nodejs upd DTLS" nothing found. 
How can secure nodejs 's udp ?
Any help is appreciated !

**Comment by bnoordhuis** [comment]
What do you mean by "secure"? Secure against what (and why)?

Node.js doesn't support DTLS natively if that's your question, although there is a dtls package on npm.

**Comment by extremety1989** [comment]
@bnoordhuis  against hackers and abusers, flood spoofing, i read in internet that if hacker got my server ip address ,he can then send malious data to client etc,
