### ISSUE TITLE
reading line number from an module

### ISSUE THREAD

**Issue by ev1stensberg** [nodejs/help#273]
Hey! I've come across `readLine` and I wonder if it is possible to read line numbers from modules, not CLI. This is a rather dumb question, but I wonder how I can do this :) thanks xoxo 

https://nodejs.org/api/readline.html

**Comment by Fishrock123** [comment]
This is totally possible.

What you'll need to do is use [`readline.createInterface()`](https://nodejs.org/api/readline.html#readline_readline_createinterface_options) to create a readline instance, but change the `input` to be a [`fs.ReadStream`](https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options).

If you need to do something else with the output, it can go to any Stream interface, such as a `fs.WriteStream`.

**Comment by ev1stensberg** [comment]
Great, thank you so much!
