### ISSUE TITLE
Help with error message

### ISSUE THREAD

**Issue by rvakid82** [nodejs/help#2730]
* **Node.js Version**: I don't know what this means 
* **OS**: Apple
* **Scope (install, code, runtime, meta, other?)**: I don't know what this means
* **Module (and version) (if relevant)**: I don't know what this means

Can anyone please help with this issue. ....What does this error message mean and what do I do? 

"The git repository at '/Users/Brad' has too many active changes, only a subset of Git features will be enabled. Would you like to add 'node_modules' to .gitignore?"  Yes/No

I'm learning code and keep getting this message in Visual Studio Code. I don't know Node yet, I'm still learning javaScript. Do I need to learn git first? I don't really understand what it does either. Thank you in advance

**Comment by Hakerh400** [comment]
Yes, it is recommended to add `node_modules` to `.gitignore`.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
