### ISSUE TITLE
/tools/v8_gypfiles folder unclear license

### ISSUE THREAD

**Issue by Silviu-Caprar** [nodejs/help#2732]
* **Node.js 12.16.3**:
* **all OS**:
* **license applicable**:

Hi there,

For the following files:
tools/v8_gypfiles/ForEachFormat.py
tools/v8_gypfiles/ForEachReplace.py
tools/v8_gypfiles/GN-scraper.py

Can you please specify the full license of the MIT-style license referenced inside ?
Since both authors contributed to the V8 project, is it the LICENSE.v8 that applies on these files or which license ? (https://github.com/nodejs/node/blob/v12.16.3/deps/v8/LICENSE.v8)

Thanks,
Silviu Caprar

**Comment by bnoordhuis** [comment]
They're authored (and maintained) by Node.js contributors, not V8 team members. They're covered by the MIT license that covers Node.js (the LICENSE file that's found in the top-level directory.)

Does that answer your question?

**Comment by Silviu-Caprar** [comment]
Yes, thank you.

**Comment by PoojaDurgad** [comment]
@Silviu-Caprar - is this still an issue? looks like this issue can be closed now. please let me know if that is not the case.

**Comment by Silviu-Caprar** [comment]
No, this is not an issue anymore. Thank you.

**Comment by PoojaDurgad** [comment]
ok . closing as issue is resolved.
