### ISSUE TITLE
What does the dot slash colon dot slash do in package.json exports?

### ISSUE THREAD

**Issue by brainkim** [nodejs/help#2733]
* **Node.js Version**: 13+
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: configuration, modules
* **Module (and version) (if relevant)**: ???

```json
{
  "exports": {
    "./": "./"
  }
}
```
-->
What does the `"./": "./"` (dot slash colon dot slash)
I’ve seen this written in the exports of several package.jsons (https://github.com/preactjs/preact/blob/1834cd70adf5758541d6167ba8c2c42778443d04/package.json#L53) and I’d like to understand what it actually does.

**Comment by mStirner** [comment]
https://nodejs.org/api/esm.html#esm_packages

**Comment by brainkim** [comment]
> As a last resort, package encapsulation can be disabled entirely by creating an export for the root of the package "./": "./". This will expose every file in the package at the cost of disabling the encapsulation and potential tooling benefits this provides. As the ES Module loader in Node.js enforces the use of the full specifier path, exporting the root rather than being explicit about entry is less expressive than either of the prior examples. Not only will encapsulation be lost but module consumers will be unable to import feature from 'my-mod/feature' as they will need to provide the full path import feature from 'my-mod/feature/index.js.

Last paragraph of that page. Can you reexplain this? Does this essentially invalidate the exports paths?
