### ISSUE TITLE
No me abre nodejs

### ISSUE THREAD

**Issue by xXTheMrSebasYTXx** [nodejs/help#2734]
cuando abro nodejs se me abre una consola, que hago porfavor necesito ayuda

**Comment by Hakerh400** [comment]
What is your question?

**Comment by PoojaDurgad** [comment]
@xXTheMrSebasYTXx - can you elaborate your issue more please? like which os you are using ? which version of node you are using? what you are trying to do?

**Comment by PoojaDurgad** [comment]
@xXTheMrSebasYTXx - when you open a node js , it will prompt you a console where you can check the version of node.js and npm by using `node -v` and `npm -v` for the successful installation of node.

**Comment by PoojaDurgad** [comment]
closing as answered. feel free to reopen the issue if that is not the case
