### ISSUE TITLE
Debugging on production

### ISSUE THREAD

**Issue by dddDestruction** [nodejs/help#2738]
14.3.0
Amazon AWS AMI ec2

I'm having problems using a deployed laravel+node app that works fine on local environment and i would like to find that problem, so i want to check if my node client connects to node server and see console logs from server. How can i do that?
Greetings

**Comment by gireeshpunathil** [comment]
@dddDestruction  - is this still outstanding? If so, why don't you SSH into the server system and check the logs, as opposed to obtaining it through a Node.js client? However, if you still want to read it through a client, that is still possible, like this:
 - in the server, write all the console.log into a file
 - in the server, implement an end point (such as `/console` or something)
 - the end point, upon invocation, will read the file and send the content as response
 - the client can access `http://host:port/console` to get the server console.log

Hope this helps?

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
