### ISSUE TITLE
Understanding and digesting Node.js changelog

### ISSUE THREAD

**Issue by szepeviktor** [nodejs/help#2739]
I'm trying to digest the information found in the changelog for each version
e.g. https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md
but I cannot :(

Running Node.js web applications in a responsible manner I do not dare to blindly upgrade the engine.

Please advise.
Thank you.

Cc @thekalko

**Comment by bnoordhuis** [comment]
Can you phrase your support request as one or more questions? Bonus points if they're closed questions (the yes/no kind.) :-)

**Comment by szepeviktor** [comment]
I follow the changelog of almost all software I use on clients' servers.

Node.js' changelog is longer than I can bear.
Could you suggest a solution for keep up with the changes?

**Comment by bnoordhuis** [comment]
Node.js follows semver so in general you can expect only bug fixes in patch releases and new (additive) features in minor releases.

Breaking changes are only made in major releases except when it's a critical security fix but a) that almost never happens, and b) gets called out very clearly in the release notes.

For everything else, just look at the noteworthy changes that are relevant to your projects.

**Comment by szepeviktor** [comment]
Thank you.

I suspect I won't sleep that much!
