### ISSUE TITLE
How to add Nodejs test or tool folder in yocto image?

### ISSUE THREAD

**Issue by MukeshSingh024** [nodejs/help#274]
Hi,
Could you help me to include nodejs test folder in yocto image?

Regards,
Mukesh

**Comment by Trott** [comment]
You might be better off asking in a yocto forum, but let me try pinging the only embedded systems person I know on the project to see if they might be able to help. Not sure they've every worked with yocto or have interest in it though. Guess we'll find out. @imyller

**Comment by imyller** [comment]
Yes, Yocto Project provides embedded Linux development environment with tools, metadata, and documentation and is powered by OpenEmbedded build framework.

I'd suggest you take a look at meta-nodejs at https://github.com/imyller/meta-nodejs providing Node.js runtime and cross-compiling npm for OpenEmbedded based distributions, including Yocto/Poky.

We have dedicated git branches for most recent Yocto releases (Yocto 2.0 Jethro, Yocto 2.1 Krogoth) and a development branch currently focused on upcoming Yocto 2.2 release. 

If you need help with building Node.js for inclusion into Yocto system image, you'll be able get more Yocto/OE oriented answers to your questions at https://github.com/imyller/meta-nodejs/issues 

I'm also personally available to assist you here or trough other Node.js Foundation support channels - if you so prefer.
