### ISSUE TITLE
streamifier is not working, how to send buffer array to stream under this code?

### ISSUE THREAD

**Issue by MinhoChoi-a** [nodejs/help#2740]
* **Node.js
* **OS: Windows 10
* **Scope : code
* **Module : express, streamifier, multer, etc.

I made some code to play video with buffer array, but when I submit the file, the browser just showed a empty video player.

--view

    block content
      h1= title
      p Welcome to #{title}
    
      form.upload(method='POST' enctype='multipart/form-data' action='')
        input#video(type='file' name='video')
        button#uploadButton(type='submit') Upload

--controller

    exports.uploadVideo_post = function(req, res, next) {
      
      var fileName = req.file.buffer;
    
      console.log(req.headers);
    
      const size = req.file.size
      const range = req.headers.range;
      
      if (range) {
        let [start, end] = range.replace(/bytes=/, '').split('-');
        start = parseInt(start, 10);
        end = end ? parseInt(end, 10) : size - 1;
        res.writeHead(206, {
           'Content-Range': `bytes ${start}-${end}/${size}`,
           'Accept-Ranges': 'bytes',
           'Content-Length': (end-start) + 1,
           'Content-Type': 'video/mp4'
        })
        streamifier.createReadStream(fileName, { start, end }).pipe(res);
      } else {
        res.writeHead(200, {
          'Content-Length': size,
          'Content-Type': 'video/mp4'
        });
        (streamifier.createReadStream(fileName)).pipe(res);
      }
      
    }

I used multer to get the uploaded file, and the 'fileName' is buffer array.
Can anybody help me to solve this problem?
In addition to that, it would be great if you can let me know how to re-design this player with the 'video' attribute on html.

![Capture](https://user-images.githubusercontent.com/58061895/83203368-83b87100-a106-11ea-8fd6-442649b8c65b.PNG)

**Comment by Hakerh400** [comment]
Are you trying to upload or download (stream) videos? Your client-side script shows a form for uploading a video, while your server-side script shows code for streaming a video. What do you exactly have troubles with? Can you share the entire code?

**Comment by PoojaDurgad** [comment]
ping- @MinhoChoi-a

**Comment by PoojaDurgad** [comment]
inactive . closing !! please feel free to reopen the issue if its  still outstanding.
