### ISSUE TITLE
How to handle http with micro-tasks loop full ?

### ISSUE THREAD

**Issue by BenjD90** [nodejs/help#2741]
Hello,

I'm facing a blocking issue with Node.js, and I'd like to know if one of you may have a solution.

I hava an API, that is running intensive work by calling several time a database (MongoDB) and working with those data.
This API also expose a route to check its healthy, we use to call it `/ping` it's the same idea of a `/health`, this route respond instantly with a status 200.

**What I observe :**
When the app is under charge, a few calls to the endpoint that create a lot of promise (around 10 - 20) that run at the same time to fetch the MongoDB datas, the health-check route doesn't respond.

**What I understand :**
The micro event loop in Node.js is full with those promises, and wait them to be completed before looking at the door who is calling.

**Actual workaround :**
For now I have 2 possible workaround :
* reduce number of promise generated, by using a smaller [promise pool](https://www.npmjs.com/package/promise-pool-executor)
* add a break to the micro task loop by calling a setTimeout ([thanks to this answer](https://stackoverflow.com/questions/25915634/difference-between-microtask-and-macrotask-within-an-event-loop-context/25933985#25933985))

h1. Question :
* How can I tell my server to stop working on micro task to answer the health-check ?
* I don't understand why the call to the health-check doesn't break the micro-tasks loop, I thought it was I/O interruption, isn't ?

Thanks in advance for your answers, tell me if a part is not clear

* **Node.js Version**: 12.12.0
* **OS**: Alpine in Docker ([image](https://hub.docker.com/layers/node/library/node/12.12.0-alpine/images/sha256-949c17b87a998cb1d18f7ac88e4d416a3009e7eb675565860f68ffceb0b49878?context=explore))
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: express 4

**Comment by dark-magic** [comment]
### I don't understand why the call to the health-check doesn't break the micro-tasks loop, I thought it was I/O interruption, isn't ?

When the eventloop starts executing microtasks, it executes all of them without doing anything else inbetween. This is also explained very nicely here: https://javascript.info/event-loop#summary, and here: https://www.youtube.com/watch?v=cCOL7MC4Pl0

### How can I tell my server to stop working on micro task to answer the health-check ?

That doesn't sound like an easy task, but shouldn't micro-tasks be micro and not delay the event loop that much? I think breaking the microtask loop, or maybe somehow adding microtasks which check for this route (I'm not sure if that's possible) is the only solution there...

**Comment by BenjD90** [comment]
Thanks, I deduce that when a node doesn't respond to a healthecheck means that it is full/averloaded.
I'll take that as a fact to adjust components around, on kub for example, stop sending traffic to that pod.
