### ISSUE TITLE
dgram socket send udp frame twice?

### ISSUE THREAD

**Issue by whuer-xiaojie** [nodejs/help#2744]
* **Node.js Version**: V10.16.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: dgram

Hello: 
    I'm using the dgram module for sending and receiving UDP datas. When I call `udp.send(msg,port,ip)`,I can catch this msg frame twice via Wireshark [(Image)](https://github.com/whuer-xiaojie/NodeUtils/blob/master/doc/Wireshark.png) ,But I only call the send function once.Why that happen? Could anyone to help me?Thanks so much!
```js
const dgram = require('dgram');
let udp = dgram.createSocket('udp4');

function init(port, ip) {
    udp.bind(port, ip, () => {
        udp.setBroadcast(true);
        udp.send('12356556', 17222, '255.255.255.255');
    });

    udp.on('message', function (msg, rinfo) {

    });

    udp.on('listening', () => {
        console.log('udp start with: ip=%s port=%s', ip, port);
    });

    udp.on('error', (error) => {
        if (error.syscall === 'bind') {
            console.log(error);
            process.exit(-1);
        }
        console.log(error);
    });

}
function test() {
    let msg = Buffer.from('132sdfsvsdgdfgdlkfgplbdf');
    for (let i = 0; i < 5; i++) {
        udp.send(msg, 1234, '192.169.144.1');
    }
}

init(12345, '192.169.1.100');
test();
```

-->

**Comment by bnoordhuis** [comment]
> I only call the send function once

Your sample calls it six times, once to the broadcast address...

**Comment by whuer-xiaojie** [comment]
That means I catched 12 udp frames from 192.168.1.100:12345  :(

**Comment by whuer-xiaojie** [comment]
I noticed if I disable IPv6 of my network interface,will catch the frame twice.after I enable the IPv6 everything seems OK

**Comment by PoojaDurgad** [comment]
@whuer-xiaojie - is this issue resolved?

**Comment by whuer-xiaojie** [comment]
I think it's a bug of Wireshark [npcap driver issue](https://github.com/nmap/npcap/issues/51)  

Even Wireshark shows duplicate sent,the dest device will only receive the frame once

@PoojaDurgad
