### ISSUE TITLE
Cannot find module(es6) node 12.14.1

### ISSUE THREAD

**Issue by sujeet-agrahari** [nodejs/help#2746]
* **Node.js Version**: 12.14.1
* **OS**: Win 10 1909 build 18363
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: es6

I am trying to use `ES6`  modules feature.
I checked on [node.green](https://node.green/) that node 12 supports `ES2019` 100%

**Why do I still have to use `type: module and  --experimental-modules` tweaks?**

Anyhow, I enable those configs.

I have two files in current  directory along with a `package.json` file.

**main.js**
```
import { a } from './somemodule.js';

console.log(a);
```

**somemodule.js**
```
export  const a = 10;
```
Above files are in the same directory from where I am running this command.
`node --experimental-modules main.js`

But still getting below error.

> (node:1164) ExperimentalWarning: The ESM module loader is experimental.
> internal/modules/esm/default_resolve.js:84
>   let url = moduleWrapResolve(specifier, parentURL);
>             ^
> 
> Error: Cannot find module C:\Users\sujee\Desktop\import\j imported from C:\Users\sujee\Desktop\import\b.js
>     at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
>     at Loader.resolve (internal/modules/esm/loader.js:73:33)
>     at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
>     at link (internal/modules/esm/module_job.js:40:36) {

**Comment by sujeet-agrahari** [comment]
Found another issue https://github.com/nodejs/modules/issues/442

Turns out, I have to use another flag. 
`node --experimental-modules --es-module-specifier-resolution=node main.js`

**Still why 100% if everything is experimental?**

**Comment by lundibundi** [comment]
It's 100% based on the features tested, not features total in the spec. As you can see on `node.green` it doesn't include `ECMAScript modules` / `ESM` / `import` .
You can check out the modules support in the [official documentation](https://nodejs.org/docs/latest-v14.x/api/esm.html) (Node.js version can be changed at the top with `View another version`) or i.e. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) (note that MDN doesn't yet include info regarding Node.js 12.17.0 working with ESM without a flag)

As you can see in the documentation in Node.js 12,13,14 the ESM are still marked as experimental.
As for the flag it was removed in the most recent release of Node.js 12 (12.17.0) and is not present going forward (v13, v14).

Regarding the resolution, ESM have much stricter resolution than Node.js's `require`, you can find the info here
https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_resolution_algorithm and here https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_enabling.

**Comment by PoojaDurgad** [comment]
@sujeet-agrahari - is this still an issue ? did @lundibundi 's suggestion help you to get rid of this issue?

**Comment by sujeet-agrahari** [comment]
No he didn't suggest anything, he was only justifiying the `100%` thing. You still can't use that without using flags. Better to use Babel or some other tools. But, with native node support it's only possible with flags.

**Comment by preveen-stack** [comment]
@sujeet-agrahari Any updates on this. Is this still an issue? Could you get a chance to try out the latest versions

**Comment by sujeet-agrahari** [comment]
> Turns out, I have to use another flag.
node --experimental-modules --es-module-specifier-resolution=node main.js

@preveen-stack

**Comment by sujeet-agrahari** [comment]
Hi @preveen-stack, I have tested it on node `v20.5.0`. It doesn't require any experimental flag, we just need to change `type: module` in pacakge.json.
