### ISSUE TITLE
Inconsistency on push 2d Array

### ISSUE THREAD

**Issue by mateuschaves** [nodejs/help#2747]
* **Version**: 10.17.0
* **Platform**: Windows 10 Pro 64-bit
* **Subsystem**:

### What steps will reproduce the bug?
```
let myArray = Array(13).fill([]);
myArray[0].push(1);
```

### How often does it reproduce? Is there a required condition?

No require condition

### What is the expected behavior?

Only the referenced index is modified

```
[ [ 1 ],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [] 
]
```

### What do you see instead?

All indexes will be pushed resulting in this output

```
[ [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ],
  [ 1 ] 
]
```

**Comment by addaleax** [comment]
> let myArray = Array(13).fill([]);
> myArray[0].push(1);

I think there is a bit of a misunderstanding here about what `.fill()` does.

`Array(n).fill(x)` creates an `Array` with `n` entries, each of which will be `x`, i. e. `[x, x, x, x, ..., x]`. There is no built-in concept of copying objects in JS – so if `x` is an object (and Arrays are objects, too), then all these `x`es won’t be copies, they will be *the same* `x`. So modifying “one” of them will also modify the others.

It sounds like what you want might be e.g. `Array(13).fill().map(() => [])`, which would be something that creates a new empty array (`[]`) for each entry in the outer array?

**Comment by mateuschaves** [comment]
> > let myArray = Array(13).fill([]);
> > myArray[0].push(1);
> 
> I think there is a bit of a misunderstanding here about what `.fill()` does.
> 
> `Array(n).fill(x)` creates an `Array` with `n` entries, each of which will be `x`, i. e. `[x, x, x, x, ..., x]`. There is no built-in concept of copying objects in JS – so if `x` is an object (and Arrays are objects, too), then all these `x`es won’t be copies, they will be _the same_ `x`. So modifying “one” of them will also modify the others.
> 
> It sounds like what you want might be e.g. `Array(13).fill().map(() => [])`, which would be something that creates a new empty array (`[]`) for each entry in the outer array?

Thank you very much, now it's clearer.
