### ISSUE TITLE
using C++ Embedder API error 

### ISSUE THREAD

**Issue by zhangwinning** [nodejs/help#2748]
* **Node.js Version**: v14.3.0
* **OS**: mac os
* **Scope (install, code, runtime, meta, other?)**: code 
* **Module (and version) (if relevant)**: 

I using the [embedding api](https://nodejs.org/api/embedding.html). when I using **node -e embedtest.cc** execution below code 
[embedtest.cc](https://raw.githubusercontent.com/nodejs/node/master/test/embedding/embedtest.cc). show below errors. 
```
➜  ~ node -e embedtest.cc
[eval]:1
embedtest.cc
^

ReferenceError: embedtest is not defined
    at [eval]:1:1
    at Script.runInThisContext (vm.js:131:18)
    at Object.runInThisContext (vm.js:295:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at evalScript (internal/process/execution.js:98:25)
    at internal/main/eval_string.js:23:3
```
so how I can solve it.

**Comment by addaleax** [comment]
@zhangwinning `node -e string` interprets `string` as JavaScript code, so that’s why that failing.

If you want to run the embedding test manually, you can run `./out/Release/embedtest` after building Node.js from source.
