### ISSUE TITLE
resolveCname returns old value

### ISSUE THREAD

**Issue by patrickgulas** [nodejs/help#2750]
* **Node.js Version**: 10.20.1
* **OS**: Ubuntu 18.04.2 LTS

I'm using nodejs dns to verify if a domain has correct CNAME record before inserting it into DB. To verify that I use following code:

```js
import dns from 'dns'

// ...
   const dnsResolver = new dns.promises.Resolver()
   const cNameRecords = await dnsResolver.resolveCname(url)

   // check records...
// ...
```
When I change CNAME records in DNS registry its updated after a while and I checked it with a dig command in terminal. However, dnsResolver.resolveCname is still returning old values, even after almost 30 hours after change.

Do dnsResolver.resolveCname works in much different way than dig? How long may it take to get updated values or is it something broken? Did you have similar problem? I will be grateful for any information.

**Comment by bnoordhuis** [comment]
What server does dig use (`dig example.com | grep SERVER`) and is that server listed in `/etc/resolv.conf`? If not, that's probably where the difference comes from. :-)

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
