### ISSUE TITLE
Using Golang WASM with experimental WebAssembly System Interface

### ISSUE THREAD

**Issue by carlskii** [nodejs/help#2752]
Hi, I'm not sure if this is a bug or just missing some documentation.

* **Version**: v14.4.0
* **Platform**: Darwin Carls-MBP 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

I'm following the docs for the experimental WebAssembly System Interface (WASI) here: https://nodejs.org/api/wasi.html. 

However, I can't see a way to reference the `./wasm_exec.js` that is provided by golang. If I use this code: 

```
'use strict';
const fs = require('fs');
const { WASI } = require('wasi');
require('./wasm_exec.js');

const wasi = new WASI({
  args: process.argv,
  env: process.env,
  preopens: {
    '/sandbox': '/Users/user/development/go-wasm/'
  }
});
const importObject = { wasi_snapshot_preview1: wasi.wasiImport };


(async () => {
  const wasm = await WebAssembly.compile(fs.readFileSync('./main.wasm'));
  const instance = await WebAssembly.instantiate(wasm, importObject);

  wasi.start(instance);
})();
```
Then: 
`node --experimental-wasi-unstable-preview1 --experimental-wasm-bigint scratch8.js`
I get the following TypeError error:
```
TypeError: WebAssembly.instantiate(): Import #0 module="go" error: module is not an object or function
```

If I use this code as per the golang docs it works perfectly in my Chrome browser.
```
<script src="wasm_exec.js"></script>
	<script>
		if (!WebAssembly.instantiateStreaming) { // polyfill
			WebAssembly.instantiateStreaming = async (resp, importObject) => {
				const source = await (await resp).arrayBuffer();
				return await WebAssembly.instantiate(source, importObject);
			};
		}

		const go = new Go();
		let mod, inst;
		WebAssembly.instantiateStreaming(fetch("test.wasm"), go.importObject).then((result) => {
			mod = result.module;
			inst = result.instance;
			document.getElementById("runButton").disabled = false;
		}).catch((err) => {
			console.error(err);
		});

		async function run() {
			console.clear();
			await go.run(inst);
			inst = await WebAssembly.instantiate(mod, go.importObject); // reset instance
		}
	</script>
```

So my question, is how do I do the equivalent using node?

**Comment by PoojaDurgad** [comment]
@carlskii - is this issue resolved?

**Comment by guybedford** [comment]
This isn't a WASI module. Rather you should just use normal Web Assembly. It would probably look something like:

main.mjs
```js
import './wasm-exec.js';
import { readFileSync } from 'fs';

const go = new Go();
const mod = await WebAssembly.compile(readFileSync('./test.wasm'));
let inst = await WebAssembly.instantiate(mod, go.importObject);

async function run () {
  console.clear();
  await go.run(inst);
  inst = await WebAssembly.instantiate(mod, go.importObject);
}

await run();
```

**Comment by PoojaDurgad** [comment]
closing as answered. pls feel free to reopen the issue if its still outstanding.

**Comment by Dhanush1409** [comment]
> This isn't a WASI module. Rather you should just use normal Web Assembly. It would probably look something like:
> 
> main.mjs
> 
> ```js
> import './wasm-exec.js';
> import { readFileSync } from 'fs';
> 
> const go = new Go();
> const mod = await WebAssembly.compile(readFileSync('./test.wasm'));
> let inst = await WebAssembly.instantiate(mod, go.importObject);
> 
> async function run () {
>   console.clear();
>   await go.run(inst);
>   inst = await WebAssembly.instantiate(mod, go.importObject);
> }
> 
> await run();
> ```

when i am using this code an error occurred Go is not defined
