### ISSUE TITLE
Node js sequential call for 50 times with each request dependent on data of previous request

### ISSUE THREAD

**Issue by kiranraytank** [nodejs/help#2753]
I want to write code in node js such that it should make 50 sequential api calls where each new api request requires data from previous request 

I have tried for loop but failed to pass the previous data in next api call

const request   = require("request");
const express   = require('express');
const router    = express.Router();

router.get('/apiInit', async(req, res) => {
    
    let somedata;
    callMainReqMapFun(somedata) /* call main request for url parellal call && 0 meance counter_of_request */
        .then((result) => { res.send(result); })
        .catch((rejectArr) => { res.send(rejectArr); });    
        
}) 

function callMainReqMapFun(somedata){
    return new Promise((resolve, reject) => {  
    
        let link1;          
        for(let tCount = 0; tCount <= 49; tCount++){ 
            
            if(somedata == 'undefined'){
                link1 = "https://myurl.com/data?val=123";
            } else{    
                link1 = "https://myurl.com/data?val=123&somedata"+somedata;   
            }
            let options = { 
                method  : 'GET',
                url     : link1,
                headers : { 
                    Accept          : '*/*',
                    'Content-Type'  : 'text/html; charset=utf8, application/xhtml+xml, application/x-www-form-urlencoded',
                },
            };
           
            request(options,function(error, response) {    
                if (error) {
                   console.log(error);                   
                }else{
                   let res_some_data = response.someData;

                   /**** 
                        * this res_some_data <= vriable/data used in next request url
                        * this same process 50 times
                            * 1 request's (someData) used in 2nd request
                            * 2nd  request's (someData) used in 3rd request
                            * contines this process until 50
                        * only 1st request set without somedata
                        * after 1st request all request url used somedata of previous request
                    *****/

                }
                
            }); 
            
        }
    });
}
   
module.exports = router;

can you suggest what should i do for efficient code?

Thank you in advance...!!!

**Comment by Hakerh400** [comment]
Please show your code.

**Comment by kiranraytank** [comment]
const request   = require("request");
const express   = require('express');
const router    = express.Router();

router.get('/youtubeInit', async(req, res) => {
    
    let somedata;
    callMainReqMapFun(somedata) /* call main request for url parellal call && 0 meance counter_of_request */
        .then((result) => { res.send(result); })
        .catch((rejectArr) => { res.send(rejectArr); });    
        
}) /* end main routes */

function callMainReqMapFun(somedata){
    return new Promise((resolve, reject) => {  
    
        let link1;          
        for(let tCount = 0; tCount <= 49; tCount++){ 
            
            if(somedata == 'undefined'){
                link1 = "https://myurl.com/data?val=123";
            } else{    
                link1 = "https://myurl.com/data?val=123&somedata"+somedata;   
            }
            let options = { 
                method  : 'GET',
                url     : link1,
                headers : { 
                    Accept          : '*/*',
                    'Content-Type'  : 'text/html; charset=utf8, application/xhtml+xml, application/x-www-form-urlencoded',
                },
            };
           
            request(options,function(error, response) {    
                if (error) {
                   console.log(error);                   
                }else{
                   let res_some_data = response.someData;

                   /**** 
                        * this res_some_data <= vriable/data used in next request url
                        * this same process 50 times
                            * 1 request's (someData) used in 2nd request
                            * 2nd  request's (someData) used in 3rd request
                            * contines this process until 50
                        * only 1st request set without somedata
                        * after 1st request all request url used somedata of previous request
                    *****/

                }
                
            }); 
            
        }
    });
}
   
module.exports = router;

**Comment by Hakerh400** [comment]
Try this:

```js
const request = require('request');
const express = require('express');
const router = express.Router();

const callMainReqMapFun = async someData => {
  for(let tCount = 0; tCount <= 49; tCount++){
    someData = await new Promise((resolve, reject) => {
      let link1;

      if(typeof someData === 'undefined'){
        link1 = 'https://myurl.com/data?val=123';
      }else{
        link1 = 'https://myurl.com/data?val=123&someData=' + someData;
      }

      const options = {
        method: 'GET',
        url: link1,
        headers: {
          Accept: '*/*',
          'Content-Type': 'text/html; charset=utf8, application/xhtml+xml, application/x-www-form-urlencoded',
        },
      };

      request(options, (error, response) => {
        if(error){
          console.log(error);
          reject(error);
        }else{
          resolve(response.someData);
        }
      });
    });
  }

  return someData;
};

router.get('/apiInit', (req, res) => {
  let someData;
  callMainReqMapFun(someData).
    then(result => { res.send(result); }).
    catch(error => { res.send(error); });    
});

module.exports = router;
```

**Comment by PoojaDurgad** [comment]
@kiranraytank - is this still an issue? did @Hakerh400 's suggestion help you to resolve the issue

**Comment by PoojaDurgad** [comment]
closing as inactive!! feel free to reopen the issue if its still outstanding
