### ISSUE TITLE
Cant fetch all the tickets using  jira-client 

### ISSUE THREAD

**Issue by anjneeksharma** [nodejs/help#2755]
Hi 
i am using jira-client library to fetch jira ticket there is field called maxResults but i dont know how many tickets are there in jira.
So how can i fetch all the ticket ?

```
getAllJiraIssues(root: any, args: any, ctx: any) {
      const jira = new JiraApi({
        protocol: 'https',
        host: process.env.JIRA_HOST,
        username: process.env.JIRA_USERNAME,
        password: process.env.JIRA_PASSWORD,
        apiVersion: '2',
        strictSSL: false
      });
      return jira.getIssuesForBoard(process.env.JIRA_BOARD_ID, startAt=0, maxResults=10)
        .then(function (getIssuesForBoard: any) {
          return getIssuesForBoard['issues'].map((issue: any) => {
            issue['fields']['ticketID'] = issue['key'];
            return issue['fields'];
          });
        })
        .catch((err: any) => {
          throw err;
        });
    },

```

**Comment by dark-magic** [comment]
The maxresults option, only sets the maximum issues you get for this request. the default is 50.

So if you want to get all issues, you simply need to send more requests when needed. According to the Jira Api Docs, the total number of issues is also returned (https://developer.atlassian.com/cloud/jira/software/rest/ see pagination)

so then it would simply be sending multiple requests and checking the total, for example:

1. request (startsat: 0,  maxresults: 50)
 if total > 50
2. request (startsat: 50, maxresults: 50)
....

**Comment by PoojaDurgad** [comment]
@anjneeksharma - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to re-open the issue if its still outstanding.
