### ISSUE TITLE
doc: https://nodejs.org/api/esm.html#esm_dual_commonjs_es_module_packages

### ISSUE THREAD

**Issue by smriti-spotnana** [nodejs/help#2756]
- I have a monorepo written in Typescript with 3 packages - 
```
monorepo 
|_ package1
|_ package2
|_ package3 
```
- package3 is a CRA. And, `package1` uses/imports `package2` and `package3` imports `package2`.
- I build a `lib` and a `lib-esm` for both package1 and package2 and expose them via package.json - 
```
  "main": "./lib/index.js",
  "module": "./lib-esm/index.js",
  "types": "./lib/index.d.ts",
```
`lib` - is my typescript package transpiled to cjs 
`lib-esm` - is my typescript package transpiled to es6/esnext

- my `./lib/index.js` looks like this - (simplified) - 
```
export * from file1;
export * from file2; 
```
now, can I just create a ./wrapper.js - 
```
import * as cjs  from './lib/index.js';
export const {cjs,};
```
and have my package1 look like this - 
```
{
  "type": "module",
  "main": "./lib/index.js",
 "types": "./lib/index.d.ts",
  "exports": {
    "import": "./wrapper.js",
    "require": "./lib/index.js"
  }
}
```
- will it not break and support all the browsers that having 2 copies like - lib and lib-esm were supporting? 
- this approach as I see from the docs is new, <1year. is it safe to use this? 
- **all this wrapper.js has is commonjs inside, so how is it able to help anyone?** 
- but I had also read that `main` in your package.json is used when someone using your package imports your package via require(), and `module` - when they import it via ES6 import. but, now there will be no `module` in my package.json
- how do i know or make sure that my package's state is isolated? what does that mean? as written in the docs?

- please direct me to some article, if you think these questions are already answered somewhere else - would be really helpful!

**Comment by DerekNonGeneric** [comment]
> this approach as I see from the docs is new, <1year. is it safe to use this?

It's experimental meaning it can change at any time. I'm not sure how you define safe, but it's not recommended for production software.

**Comment by PoojaDurgad** [comment]
> please direct me to some article, if you think these questions are already answered somewhere else - would be really helpful

 you may refer this https://www.digitalocean.com/community/tutorials/new-ecmascript-modules-in-node-v12 , https://blog.risingstack.com/node-js-at-scale-module-system-commonjs-require/  not sure but I hope it helps

**Comment by PoojaDurgad** [comment]
closing as answered. pls feel free to reopen the issue if its still outstanding.
