### ISSUE TITLE
throw error while installing node.js with window powershell

### ISSUE THREAD

**Issue by naseemkhan7021** [nodejs/help#2759]
* **12.18.0 (includes npm 6.14.4)-x86**:
* **window 7**:
* **Scope (install, runtime)**:
* **Module (and v12.18.0-x86) (if relevant)**:

 There is a problem while installing node.js. this is window powershell.
Here is photo link  --- > https://photos.app.goo.gl/v49bJspqUsBQ26Nk7
please help ...I try many times...but same issue..
please help

**Comment by PoojaDurgad** [comment]
closing this issue as it already mentioned and resolved in https://github.com/nodejs/help/issues/2757
