### ISSUE TITLE
Node process starts inflating memory and cpu usage making server unresponsive for few minutes

### ISSUE THREAD

**Issue by Senglean** [nodejs/help#2762]
* **Node.js Version**: v12.18.0
* **OS**: Ubuntu 19.10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: 
Express, MongoDb, RedisDB, socket.io

I have a web socket game server which runs very good except of some 3 times a day when I can observe memory inflating from constant 500mb to ±3Gb and massive cpu spikes in all cores , after a minute or two everything goes back to normal as if nothing happened. During this anomaly the game server becomes unresponsive and lose packets

I captured the event on video you may check here : 

https://www.youtube.com/watch?v=gMctGII26eY

sometimes during this event node instance crashes with the following error : 

BadRequestError: request aborted
IncomingMessage.onAborted (node_modules/raw-body/index.js:231:10)
at IncomingMessage.emit (events.js:315:20)
at abortIncoming (_http_server.js:532:9)
at socketOnClose (_http_server.js:525:3)
at TLSSocket.emit (events.js:327:22)
at net.js:674:12
at Socket.done (_tls_wrap.js:574:7)
at Object.onceWrapper (events.js:422:26)
at Socket.emit (events.js:315:20)
at TCP. (net.js:674:12)

So far I tried :
disable perMessageDeflate in engine.io 
starting node instance with LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2

Any help is much appreciated

**Comment by Hakerh400** [comment]
Please share your project source files and all relevant scripts, including instructions on how to build and run the server locally. There is a high probability that you are doing something wrong in your code, but there is no way anyone can tell without looking at the source files. Or, in case you project is not open-source, feel free to pay a professional developer to solve the problem for you.

**Comment by Senglean** [comment]
Which code in particular you have in mind that has the high probability of suddenly writing 3Gb in memory randomly ±3 times a day?

I am also ok with the idea of paying anyone solving this issue so anyone please feel free to get in touch

**Comment by Hakerh400** [comment]
> Which code in particular you have in mind that has the high probability of suddenly writing 3Gb in memory randomly ±3 times a day?

I have no clue without looking at the code.

> I am also ok with the idea of paying anyone solving this issue so anyone please feel free to get in touch

The nodejs/help repository is not a place for job advertisements. People here spend their free time to answer questions, especially when the entire community can benefit from the answer, if the question being asked is a common problem that a lot of evelopers struggle with. In contrast, you ask for a very specific problem related to your server, which is not open-source, so neither anyone can reliably tell what the problem is, nor anyone except you can benefit from the answer. I would like to spend my free time to help you resolve the problem if you share the source code of your project publicly.

**Comment by Senglean** [comment]
Thanks for your input, I hoped someone would have encountered such thing taking place monitoring their server with htop as shown in the video.

There is no indication that such thing is caused by the server code which runs good all day long. Monitored memory usage with heap dumps which shows no memory leak, it is a game server so the source code is not small.
