### ISSUE TITLE
error C2440: 'initializing': cannot convert from 'napi_ref (__cdecl *)(napi_env,napi_callback_info)' t o 'napi_callback'

### ISSUE THREAD

**Issue by aggarwalanubhav** [nodejs/help#2764]
* **Node.js Version**: v12.18.0
* **OS**: Windows 10 Pro
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Hi, I've written the following C code to return a napi_ref type variable from the function:

```
napi_ref create_referencec(napi_env env, napi_callback_info info) {
    char* str = "Hello storj";
    napi_status status;
    napi_value napiString;

    status = napi_create_string_utf8(env, str,
        NAPI_AUTO_LENGTH, &napiString);
    assert(status == napi_ok);

    napi_ref napiRef;
    status = napi_create_reference(env, napiString, 0, &napiRef);
    printf("\nStatus ref : %d \n", status);
    assert(status == napi_ok);

    return napiRef;
}

napi_value Init(napi_env env, napi_value exports) {
    napi_status status;
    napi_property_descriptor create_reference =
        DECLARE_NAPI_METHOD("create_reference", create_referencec);
    status = napi_define_properties(env, exports, 1, &create_reference);
    assert(status == napi_ok);

    loaddll();
    return exports;
}
```

On running the ```npm install``` command I get the following error:
```
error C2440: 'initializing': cannot convert from 'napi_ref (__cdecl *)(napi_env,napi_callback_info)' t o 'napi_callback'
```

Kindly look into this and help me get rid of this. 

Thanks.

**Comment by addaleax** [comment]
The problem is that functions should return `napi_value`, not `napi_ref`.

**Comment by aggarwalanubhav** [comment]
Thank you for the reply.

Further, I have a requirement to fulfill which goes as follows:
I have a handle, say filehandle, created using `cgo` library in c file which I want to return from that c file to JS code which can further be used by other functions.

Is there any way I can do so? If yes, kindly mention the same.
