### ISSUE TITLE
creating a new project after fresh installation with latest version error related to deprecation and unstable version

### ISSUE THREAD

**Issue by apurv09** [nodejs/help#2765]
* **Node.js Version**:12.18.0
* **OS**:windows 10 pro
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**:npm

When i was creating the first project it gives an error related to npm and also i got error while installation
error while installation-npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 error while creating application on cmd-npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! Unexpected end of JSON input while parsing near '...ERXBEg==","shasum":"8'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\apurv\AppData\Roaming\npm-cache\_logs\2020-06-10T14_03_26_302Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

error from log file-4771 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
4771 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
4771 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
4771 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
4772 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ERXBEg==","shasum":"8'
4772 verbose stack     at JSON.parse (<anonymous>)
4772 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
4772 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
4772 verbose stack     at runMicrotasks (<anonymous>)
4772 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
4773 verbose cwd D:\angular\hello-app
4774 verbose Windows_NT 10.0.18363
4775 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--quiet"
4776 verbose node v12.18.0
4777 verbose npm  v6.14.4
4778 error Unexpected end of JSON input while parsing near '...ERXBEg==","shasum":"8'
4779 verbose exit [ 1, true ]

I have tried various solution available over forums and blogs but i was unable to resolve issue.

**Comment by PoojaDurgad** [comment]
@apurv09 - try to refer this https://github.com/npm/npm/pull/19198  hope it may help

**Comment by apurv09** [comment]
Thank you i will check it

**Comment by apurv09** [comment]
> @apurv09 - try to refer this [npm/npm#19198](https://github.com/npm/npm/pull/19198) hope it may help

Thank you i will check it

**Comment by PoojaDurgad** [comment]
closing as answered.
