### ISSUE TITLE
Get origin of request using express

### ISSUE THREAD

**Issue by ChezCoder** [nodejs/help#2768]
* **Node.js Version**: 12.16.3
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: Code; express
* **Module (and version) (if relevant)**: Express 4.17.1

Basically, I am using https://repl.it to make a nodejs project. Thing is, everytime I do something with nodejs, people think it's funny to send my server malicious POST requests and mess up my project's database. I've been using a method where the client has a key and the server has a key. Both keys are the same and are in an `.env` file (`env` files are hidden for viewers of a project in replit). The client sends the key and if it matches the server key, then it is a safe post request. This has been working until a few days ago, I made a chatroom.

The client wasn't Python, or another NodeJS script where it can easily get the `.env` file, but rather HTML, CSS, and JavaScript. Thing is, normal JavaScript can't get `.env` files so there wasn't a way to hide the key, so I just didn't make one and hope no one would notice — but they did. By chatroom was bombarded with hackers sending non-filtered messages and blacklisted usernames and everything was all wrong.

So then, I thought of a genius idea. What if I just got the origin of the request (the url)? Then all I had to do is to add code to test the url and see if it was a safe domain! I searched google, stackoverflow, and many other sources telling me to use things like `req.hostname`, `req.get("host")`, and many other variations. But the problem was, when I tried it, it either returned `undefined`, or it just returned the host of the application, which was useless.

By the way, if you where wondering how they bypassed CORS, they probably used an online resource like https://reqbin, which bypasses cors.

So then, I turned to the last and only source available, this. I searched up my question and it gave me the exact same answer, which is why i have decided to create a new question.

Any help would be greatly appreciated :D

**Comment by Hakerh400** [comment]
> Thing is, normal JavaScript can't get .env files

If by *"normal"* you mean *"browser"* JavaScript, they can read any file using [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) or [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).

> What if I just got the origin of the request (the url)?

Any request header can be faked by an attacker, including the origin URL.

---

In general, if you want to create a chat server, the best option is to create some login form and when a user enters valid credentials, the server can send him some secret token (key) and server can accept only requests containing that key.

**Comment by ChezCoder** [comment]
Yes but I can't get the env file through an XMLHttpRequest, I have already tried :(

Also, for your idea, you where saying that once the user logs in, the server sends it a token that can be used to communicate with the server?

**Comment by Hakerh400** [comment]
> Yes but I can't get the env file through an XMLHttpRequest, I have already tried :(

Then you have probably tried it in a wrong way. `XMLHttpRequest` can read any file.

> Also, for your idea, you where saying that once the user logs in, the server sends it a token that can be used to communicate with the server?

Yes, that is a common practice.

**Comment by PoojaDurgad** [comment]
@ChezCoder - is this still outstanding?

**Comment by PoojaDurgad** [comment]
inactive closing! please feel free to reopen the issue if its still outstanding
