### ISSUE TITLE
--max-old-space-size not using full memory before heap error

### ISSUE THREAD

**Issue by awsirkis** [nodejs/help#2769]
* **Node.js Version**: 12.18.0
* **OS**: Windows 10 x64
* **Scope (install, code, runtime, meta, other?)**: Runtime
* **Module (and version) (if relevant)**: @nuxt/cli 2.11.0

I am attempting to build my Nuxt.js SSR application using the normal ```nuxt generate --max-old-space-size=320000" command, where 320000 is the total amount of memory (32GB) and virtual memory (288GB) that I'm able to allocate for it. It's an application of around 3.5 GB of uncompiled code, with only 1,200 pages and a few dozen videos (more incoming, hoping this will scale well).

**UPDATE: Video files are causing the problem. Removed them and was able to build all pages that didn't have them. However, I still need them for actual use of the site**

When running the command with the full memory allocated, including the virtual memory space, I got the ```FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory``` error. However, when looking at the system performance as it was running, memory usage never once went over 30%, including the 18% used in background processes. It's not a problem of the system actually accessing these resources, as I was exceeding 75% while committing the source code to GH.

What is preventing Node from using the full amount of memory, and thus from building my app? How can I force Node to use the full memory before trying to crash?

Repository: https://github.com/awsirkis/heap-problem

**Comment by Hakerh400** [comment]
> I am attempting to build my Nuxt.js SSR application using the normal ```nuxt generate --max-old-space-size=320000" command, where 32000 is the total amount of memory (32GB)

Is it `32000` or `320000`? Please note that these numbers are not the same.

> Video files are causing the problem. Removed them and was able to build all pages that didn't have them. However, I still need them for actual use of the site

I'm not familiar with `nuxt`, but I am sure there is some way to include resource files (like videos and images), without loading all of them into the memory.

---

What I can see from the crash reports from your repository is that the arguments of the crashed process are:

```json
"commandLine": [
  "node",
  "C:\\Users\\awsir\\CMAA\\\\node_modules\\nuxt\\bin\\nuxt.js",
  "generate",
  "--max-old-space-size=32000"
]
```

which explains what the problem is: `nuxt` passes the `--max-old-space-size` as a script argument, rather than a Node.js argument. It needs to be before the script path, but `nuxt` probably does not support it.

**Comment by awsirkis** [comment]
Issue is not with Node.JS, therefor closed it.
Meant 320,000, since it's in MB
