### ISSUE TITLE
illegal access

### ISSUE THREAD

**Issue by piyushbeli** [nodejs/help#277]
0.12.5:
Unix:
ubuntu:

We suddenly started getting "illegal access" in our log file. Everything was working fine till now but because of no reason this problem started coming. We had to restart the server to fix the issue.
I tried to search on web if somebody is having a similar issue. I ended up understanding that it could be related to wrongly calling the JSON.parse/stringify function, is it true ? Do you think there can be any other situation where this problem may come ?

Can somebody please help me on this if he/she has encountered similar problem in past ?

Many thanks
Piyush

**Comment by kahwee** [comment]
It could be related to a buggy v8. https://github.com/expressjs/express/issues/2652

Related: https://bugs.chromium.org/p/v8/issues/detail?id=2397

Doug Wilson made a useful comment there:

> For those that are getting this error, it would be useful to also open an issue up on the Node.js repo, as this looks like it's actually a v8 bug, which isn't too surprising, as Node.js 0.12 chose a version of v8 that is pretty buggy. A core v8 function (like decodeURIComponent) throwing the error illegal access as is the case here, is a signal that the machine code v8 generated for decodeURIComponent is invalid or corrupted in some way.

**Comment by piyushbeli** [comment]
Yes, we plan to upgrade to latest node version. Surprising thing is it happned first time since last 6 months , we were always on old node version. It should have come at an early stage itself. I went through the posts in above link, but nothing relavant for us. Thanks for the help and suggestion.

**Comment by lordKnighton** [comment]
hi @piyushbeli  please close issue if content with answer. 😄

**Comment by piyushbeli** [comment]
Hi @lordKnighton , Sorry for a very late reply. Till now we did not see the problem again in production logs (after upgrading to latest node version).
Closing this issue until we encounter the problem again.
Thanks all for your comments.
