### ISSUE TITLE
same instance of imported json file

### ISSUE THREAD

**Issue by Royalsspirit** [nodejs/help#2770]
* **Node.js Version**: v10.0.0
* **OS**: Ubuntu 18.04.4 LTS x86_64
* **Scope (install, code, runtime, meta, other?)**: runtime

Hello guys, i'm facing a strange behavior with nodejs which can be explain in a few lines.
The purpose is to have a kind of snapshot in json file and use it into a je unit test to avoid having a big shitty json into it.

file.json
```
{
 "name":"fo",
 "firstname":"do"
}
```
Node -i:
```js
> const json = require('./test-data.json');
undefined
> const array = []
undefined
> array.push(json)
1
> array.push(json)
2
> console.log(array)
[ { name: 'fo', firstname: 'do' },
  { name: 'fo', firstname: 'do' } ]
undefined
> array[0].firstname="myname"
'myname'
> console.log(array)
[ { name: 'myname', firstname: 'do' },
  { name: 'myname', firstname: 'do' } ]
```

As we can see, it seems that the same instance of imported file is used in my array but i don't firgure out why whereas i would like to have something like:

```
[ { name: 'update', firstname: 'do' },
  { name: 'fo', firstname: 'do' } ]`
```
Otherwise i found a workaround. it's to use `fs`

I don't know if it's a bug or a normal behavior of node. 
I would like to know just why it acts like that if someone know.

In the case where this kind of topic is already solved, sorry for the noice.

Ryl

**Comment by Hakerh400** [comment]
That is the expected behavior. Objects are copied by reference, not by value. To work around that, you can replace `array.push(json)` with `array.push(JSON.parse(JSON.stringify(json)))`

**Comment by Royalsspirit** [comment]
Hello @Hakerh400 ,
I known that objects are copied by reference but not in this contexte. I thought that the json file is exported as json not as Object to have something like that:
```
array.push({ name: 'myname', firstname: 'do' })
```
But i understand that it's not :)

Thank you for this quick answer and explaination of this behavior.
