### ISSUE TITLE
Queued buffers seemingly not cleaned up in closed sockets

### ISSUE THREAD

**Issue by Euregan** [nodejs/help#2771]
* **Node.js Version**: 12.9.1
* **OS**: Debian 10

We have a websocket server that seems to be leaking RSS, quite like in https://github.com/nodejs/node/issues/4779. I also tried the fixes in https://github.com/nodejs/help/issues/1518, to no avail. For around 500 sockets at the same time (Very short lived, a few seconds at most usually), we can go to up to 5G in RSS, while the heap used stays at around 800M. My observations are pretty much the same as in https://github.com/nodejs/node/issues/4779.

## Observations
- Slow clients (clients receiving data slower than server sends it) causes socket to increase their bufferSize
- This typically increases the RSS of the node process
- Upon disconnections of clients, we expect RSS to fall
- The RSS grows to up to ~7G across 3 instances (The server has 8G), and then stays there until it gets killed for using too much when it goes a bit above.
- The RSS is order of magnitude bigger than the actual `Socket.bufferSize`

## Reproduction Steps
Test cases are in https://github.com/euregan/node-ws-slow-client-buffer-leak repository
Run server on a separate machine over the network
Run 200 clients for 30 seconds
RSS builds up.
Disconnects clients.
RSS stays built up

## Graphs
Below are some graphs of the 3 instances. Sharp drops happen when the instance gets restarted either by pm2 or the system
### Memory
Red is RSS
Yellow is Heap Total
Blue is Heap Used
![0 - memory](https://user-images.githubusercontent.com/6170695/84512766-be0a3c80-acc8-11ea-9575-c9e3bed10301.png)
![1 - memory](https://user-images.githubusercontent.com/6170695/84512772-bfd40000-acc8-11ea-9274-164370776021.png)
![2 - memory](https://user-images.githubusercontent.com/6170695/84512775-c1052d00-acc8-11ea-8aee-1839e34ddfde.png)
### Buffer size (`bufferSize`)
![0 - buffer size](https://user-images.githubusercontent.com/6170695/84512850-e134ec00-acc8-11ea-8427-ee682be63c5b.png)
![1 - buffer size](https://user-images.githubusercontent.com/6170695/84512857-e2feaf80-acc8-11ea-9035-254e9d58f17b.png)
![2 - buffer size](https://user-images.githubusercontent.com/6170695/84512862-e42fdc80-acc8-11ea-8822-e0fd0d398d6a.png)
### Websockets connected
![0 - websockets](https://user-images.githubusercontent.com/6170695/84512871-e7c36380-acc8-11ea-97c7-4c388216bdbd.png)
![1 - websockets](https://user-images.githubusercontent.com/6170695/84512875-e85bfa00-acc8-11ea-82c8-79c025d58f19.png)
![2 - websockets](https://user-images.githubusercontent.com/6170695/84512881-e98d2700-acc8-11ea-8775-9fc7286136a1.png)

**Comment by bnoordhuis** [comment]
Did you check with the inspector or node-heapdump that there's no leak in your program?

If heapdumps don't show anything but RSS peaks and won't come down, you might be running into (a variation on) https://github.com/nodejs/node/issues/8871 or https://github.com/nodejs/node/issues/33790 - tl;dr glibc memory fragmentation.

Switching to jemalloc can help, see the second issue.

**Comment by Euregan** [comment]
Thanks for the quick response, heapdump were not showing anything indeed, since the heap total was never too high.
We switched to jemalloc yesterday, that seems to do the trick, though we can't figure out how to make it work with pm2. I'm closing the issue, but maybe a warning could be added to the doc?

**Comment by eladnava** [comment]
@Euregan by running the following command, you can get `pm2` and `node` to use `jemalloc` for memory allocation:

```
sudo -i
echo "/usr/lib/x86_64-linux-gnu/libjemalloc.so" >> /etc/ld.so.preload
```
