### ISSUE TITLE
Hide node_modules by default folder like git does

### ISSUE THREAD

**Issue by ivanjeremic** [nodejs/help#2774]
Like the title says I would like the node_modules folder to be hidden by default like for example Git does it with the .git folder, it is really rare that you need to look up something in node_modules and if you really need you can make it visible for a short time while you look into it.

The reason is simple, the project directory will look cleaner.

**Comment by addaleax** [comment]
I think it could help a bit – where do you want to see the folder be hidden? In your filesystem browser? That’s probably going to depend on your operating system and the particular folder that you use.

**Comment by devsnek** [comment]
Generally files starting with a `.` are hidden by default by file browsers. `git` isn't explicitly telling the os to hide it.

**Comment by PoojaDurgad** [comment]
@ivanjeremic - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive . closing . please feel free to reopen the issue if that is not the case
