### ISSUE TITLE
SSE is blocking long polling requests 

### ISSUE THREAD

**Issue by Johnny421** [nodejs/help#2775]
I'm trying to write to multiple browser clients by using Server-Sent Events (SSE) and long polling as fallback with Node.js and HTTP/2.

Everything is working. But it looks like SSE is blocking the long polling HTTP POST request when used in the same server.

if make 2 server, one with SSE logic and the other for long polling and connect as client from a single html file with 2 different ports they work fine.

Is that a normal behaviour ? that SSE and long polling in Node.js can not be in 1 single server without blocking each other?

Can somone please explain to me what is wrong ... is that a bug?

**Comment by Hakerh400** [comment]
> Can somone please explain to me what is wrong ... is that a bug?

It is impossible to know without looking at the code. Please show your scripts.

**Comment by Johnny421** [comment]
HI @Hakerh400 I will make a small clean simple code. 

But i have discovered that


readable.on('readable', () => {
  let chunk;
  while (null !== (chunk = readable.read(N))) {
    console.log(`Received ${chunk.length} bytes of data.`);
  }
});

**Comment by Johnny421** [comment]
HI @Hakerh400 I will make a small clean simple code later.

But i have discovered that **readable.read** is not behaving correctly.
If the server is awaiting SSE and also accepting long polling requests in the same time inside 
**server.on('stream',...**  then readable.read returns **null** if N is higher than what the requests sent of data.  readable.read should at least return 1 byte, but that don't happens. It only 

By N i mean this:
```

readable.on('readable', () => {
let chunk;
while (null !== (chunk = readable.read(N))) {
console.log(Received ${chunk.length} bytes of data.);
}
});
```

**Comment by Hakerh400** [comment]
> readable.read should at least return 1 byte even if N is high, but that don't happen always.

That is incorrect. From the [documentation](https://nodejs.org/api/stream.html#stream_readable_read_size):

*"If `size` bytes are not available to be read, `null` will be returned **unless** the stream has ended."*

**Comment by Johnny421** [comment]
That clear things more to me. Thank you very much, i thought that it worked like the read() function from **C** when doing socket stuff:

> This call returns up to N bytes of data. If there are fewer bytes available than requested, the call returns the number currently available.
