### ISSUE TITLE
[jira-client]:- Not able to pass -1 as a function argument its treating it as possitive 1 

### ISSUE THREAD

**Issue by anjneeksharma** [nodejs/help#2776]
I am using Jira-client and inside that getIssuesForBoard  libery for fetching the jira ticket at a time its fetch only 50 ticket but if i will pass in URL maxResults=-1 it will fetch me my all ticket 

so i will pass   getIssuesForBoard("xxxx", 0 , -1, jql)  it will return me only 1 ticket instead of all and its treating -1 as 1

**Comment by dark-magic** [comment]
Where did you read that -1 gives all tickets, jira uses paging to avoid massive payloads.
Great answer on how to get all tickets at AtlassionCommunity by sayeed1310:
https://community.atlassian.com/t5/Jira-questions/REST-Client-get-all-issues-of-project/qaq-p/494826#qanda-message-842076

**Comment by PoojaDurgad** [comment]
@anjneeksharma - is this still outstanding?

**Comment by PoojaDurgad** [comment]
inactive. closing!! please feel free to reopen the issue if its still outstanding
