### ISSUE TITLE
setImmediate and setTimeout

### ISSUE THREAD

**Issue by jasonjiflyer** [nodejs/help#2777]
* **Node.js Version**: v12.14.0
* **OS**: MAC OS Catalina 10.15.4
* **Scope (install, code, runtime, meta, other?)**: setImmediate and setTimeout
* **Module (and version) (if relevant)**:

```js
setTimeout(() => {
  console.log('setTimeout1');
  setImmediate(() => {
    console.log('setImmediate');
  })
}, 500);


setTimeout(() => {
  console.log('setTimeout2');
}, 500);
```
-->
case1: Most of the time, the order is:
setTimeout1
setTimeout2
setImmediate

case2: but sometime, the order is:
setTimeout1
setImmediate
setTimeout2

I can understand case1, but I really can't understand case2.

**Comment by dark-magic** [comment]
It's possible that setTimeout1 finishes before the timer of setTimout2 is done, that would lead to case 2. The order of setTimeouts isn't ensured: https://ehikioya.com/execution-order-multiple-settimeout-functions-javascript/

**Comment by jasonjiflyer** [comment]
@dark-magic , in my test, setTimeout2 is always behind setTimeout1, so my confusion is not the order of setTimeout, my confusion is the order of the setTimeout2 and setImmediate.
when the callback of the setTimeout1 gets executed, the callback of the setTimeout2 should be already in the queue of timer phase, so the tasks in the queue should be executed first, then setImmediate in checker phase get executed. 
So why setImmediate gets executed before setTimeout2, it doesn't make sense.
I think node.js document should explain it in more detail to help developer to understand setTimeout and setImmediate

**Comment by dark-magic** [comment]
It can be that setTimeout2 is delayed so much that setTimeout1 added the setImmediate already, before setTimeout2 is added to the EventQueue. so then the setTimeouts are still in order, but setImmediate comes vetween them.

**Comment by dark-magic** [comment]
but yeah, would be nice if the docs were more clear about it.

**Comment by PoojaDurgad** [comment]
@jasonjiflyer - is this still an issue ?

**Comment by PoojaDurgad** [comment]
inactive!! closing . let me know if its still outstanding
