### ISSUE TITLE
C++ Addon segment fault, caused by "can not access TLSv1_2_enc_data"

### ISSUE THREAD

**Issue by zhouchifelix** [nodejs/help#2778]
* **Version**:v8.15.1
* **Platform**:ubuntu1804
* **Subsystem**:64bit

### What steps will reproduce the bug?

1. Build node addon which contains socketio cpp in openssl 1.1.0

2. Try connect socketio Server with node xx.js

3. Crashed in  ssl/method.c L18 /*-
 * TLS/SSLv3 methods
 */

IMPLEMENT_tls_meth_func(TLS_ANY_VERSION, 0, 0,
                        TLS_method,
                        ossl_statem_accept,
                        ossl_statem_connect, TLSv1_2_enc_data)

4. "client_finished_label" is "can not access memory at 0xC",  i doubt that, nodejs has the same symbol with cpp addon,  how can i use cpp symbol instread?
 
### How often does it reproduce? Is there a required condition?
always

### What is the expected behavior?
link to socketio server succeed as cpp

### What do you see instead?
segment fault

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help. You can find older discussions here and in nodejs/node (and probably also in nodejs/node-gyp.)

**Comment by gireeshpunathil** [comment]
@zhouchifelix -  is this still outstanding?

**Comment by zhouchifelix** [comment]
> @zhouchifelix - is this still outstanding?

no, seems fine now
