### ISSUE TITLE
node process crashes on Mac OS X 10.15.5 (Catalina)

### ISSUE THREAD

**Issue by shinobi64** [nodejs/help#2780]
* **Version**: 10.21.0
* **Platform**: Darwin C02C42QKMD6T 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
* **Subsystem**:

### What steps will reproduce the bug?
Start nodejs (10.19 or higher) based application (using express) on Mac OS X 10.15.5 from Visual Studio Code. Node process will crash with a reference to /usr/lib/libssl.dylib

Crash details
Process:               node [4065]
Path:                  /usr/local/bin/node
Identifier:            node
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Code Helper (Renderer) [4056]
Responsible:           Electron [1030]
User ID:               501

Date/Time:             2020-06-16 16:16:17.210 +0200
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     4.5 (17P5300)
Anonymous UUID:        63966108-ED73-7B4D-2EEC-A81EF373E45B

Time Awake Since Boot: 11000 seconds

System Integrity Protection: enabled

Crashed Thread:        29

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/usr/lib/libssl.dylib
abort() called
Invalid dylib load. Clients should not load the unversioned libssl dylib as it does not have a stable ABI.

### How often does it reproduce? Is there a required condition?
No condition required

### What is the expected behavior?
Node should not crash, works properly with node 10.16.3

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help because I can tell from the stack trace that's not an official node binary from https://nodejs.org/dist/

**Comment by shinobi64** [comment]
@bnoordhuis I tried it again with a clean install from http://nodejs.org/dist/latest-v10.x/node-v10.21.0.pkg

Process:               node [31833]
Path:                  /usr/local/bin/node
Identifier:            node
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [31830]
User ID:               501

Date/Time:             2020-06-16 21:37:12.627 +0200
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        807D5424-D46B-50CF-996F-409F8AC5E8D0


Time Awake Since Boot: 1200000 seconds

System Integrity Protection: enabled

Crashed Thread:        29

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/usr/lib/libssl.dylib
abort() called
Invalid dylib load. Clients should not load the unversioned libssl dylib as it does not have a stable ABI.

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff731ca766 kevent + 10
1   node                          	0x00000001009f2a38 uv__io_poll + 819
2   node                          	0x00000001009e39ba uv_run + 359
3   node                          	0x0000000100041c00 node::Start(v8::Isolate*, node::IsolateData*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) + 946
4   node                          	0x0000000100040cc2 node::Start(uv_loop_s*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) + 329
5   node                          	0x0000000100040984 node::Start(int, char**) + 681
6   node                          	0x0000000100001034 start + 52

**Comment by bnoordhuis** [comment]
You can probably figure out which one it is with lldb:
```
$ lldb node app.js
> b dlopen
> r
# wait for breakpoint
> bt
> c
```
You may have to repeat bt+c a few times.
