### ISSUE TITLE
Receiving packets in node.js dgram is too slow

### ISSUE THREAD

**Issue by baharb** [nodejs/help#2781]
* **Node.js Version**:
* **Android**:
* **code**:
* **react-native-udp**:

Hi
I'm using node.js Dgram udp packet in react native. But there is a problem in some Android Devices Android version 7 or  more. 
Packets receive too slow. when a packet send , it takes about 20 seconds to get response.
I can't find any solution for this.
And I don't know is this right section for this issue or not

**Comment by gireeshpunathil** [comment]
@nodejs/dgram

**Comment by mcollina** [comment]
react-native does not run on Node.js, closing.
