### ISSUE TITLE
Regex parsing from string not behaving as expected

### ISSUE THREAD

**Issue by jonashdown** [nodejs/help#2782]
Parsing a regex from a string seems to strip out characters.

* **Version**: 4, 10, 12, 14
* **Platform**: Mac Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
* **Subsystem**:

### What steps will reproduce the bug?

Create a regex from a string as follows : 
```
var x = new RegExp('\bhi\b', 'i');
console.log(x)
```
console.log prints out `h/i`

### How often does it reproduce? Is there a required condition?
consistently, no required condition
### What is the expected behavior?
console.log prints out `/hi/i`
N.B firefox & chrome consoles do this 

### What do you see instead?
console.log prints out `h/i`

**Comment by addaleax** [comment]
Did you mean to write `'\\bhi\\b'` instead of `'\bhi\b'`? `\b` is the backspace character, so that’s why some characters in the `console.log()` output are overwritten here.

(In other words: If you want the same regexp as `/\bhi\b/i`, then the way to re-create that with the constructor is `new RegExp('\\bhi\\b', 'i')`)

**Comment by jonashdown** [comment]
`\b` is not the backspace character, its the word boundary character, `[\b]` is the backspace character. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes.

it looks like the browsers are using raw string in their implementation, whilst node is using escaped string

**Comment by addaleax** [comment]
> `\b` is not the backspace character, its the word boundary character, `[\b]` is the backspace character.

@jonashdown That is true **in regular expression literalls**. However, you’re using `new RegExp()`, not a regexp literal, and you are passing a **string literal**, and inside those `\b` is the backspace character.

**Comment by jonashdown** [comment]
so is node's implementation correct and firefox's incorrect ?

**Comment by addaleax** [comment]
@jonashdown I think the Regexp implementation is correct in both cases – the problem is that Firefox just drops the `\b` characters when printing the RegExp to the console, instead of showing that they are there.
