### ISSUE TITLE
problem with the file manager

### ISSUE THREAD

**Issue by AlexDiego123** [nodejs/help#2783]
* **Node.js Version**:v12.16.2
* **OS**:Windows 7
* **Scope (install, code, runtime, meta, other?)**:code
* **Module (and version) (if relevant)**:

hi,i was creating a game in my discord bot and when a member does a command it writes 5 things at a time with the fs module in a json file and then the json file corrupts

**Comment by dark-magic** [comment]
code? without code its gonna be hard for us to help you. but js normally only does 1 thing at the same time, so corrupted json would be an interesting result

**Comment by PoojaDurgad** [comment]
@AlexDiego123 - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
