### ISSUE TITLE
How can I get out of debugging?

### ISSUE THREAD

**Issue by CharlieIoD** [nodejs/help#2784]
* **Node.js 12.16.3
* **OS**: Windows 10 using Visual Studio Code
* **Scope When I test with Postman
* **Module (and version) (if relevant)**:

I am following a series of web developers tutorials and somehow, I have switched on the Debug module in Node and I can’t get rid of it. I am using postman to test the code I get a whole lot of messages like “Promise rejection warning…” and console.log no longer brings any results. Also an ominous button: ‘Debug’ has appeared in my package.json file .I’ve looked on the internet  but nothing seems to work. I found: require('inspector').close(), but where do I put it? In Node? In a .js file? Node just ignores it, as with ‘.exit’ and ‘kill script’. The Debugger documentation is no help “Why would you want to exit our wonderful debugger?”
I found: ‘unwatch('my_expression').’ But what is the expression? What do I put in there?
 I spent most of last evening on this, but no luck. Why is the thing so difficult to get rid of? I want to take back control. I switched it on accidentally, now I want to know how to turn it off please.

I am testing the following code using Postman:
const express = require('express');
const bcrypt = require('bcryptjs');
const stop = require('inspector').close()

const app = express();
app.use(express.json());

const database = {
    users: [
        {
        id: '123',
        name: 'John',
        email: 'john@yahoo.com',
        password: 'jaffa',
        entries: 0,
        joined: new Date()
        },
        {
        id: '124',
        name: 'Sally',
        email: 'sally@yahoo.con',
        password: 'cake',
        entries: 0,
        joined: new Date()
            }
    ]
}

app.get('/', (req, res) => {
    res.send(database.users);
})

app.post('/signin', (req, res) => {
    if (req.body.email === database.users[0].email &&
        req.body.password === database.users[0].password) {
            res.json('Success!');
        }else{
            res.status(400).json('Error logging in.')
        }
})

app.post('/register', (req, res) => {
    const {email, name, password} = req.body;
    bcrypt.hash(password, null, null, function(err, hash){
        console.log(hash);
    })
    database.users.push({
            id: '125',
            name: name,
            email: email,
            password: password,
            entries: 0,
            joined: new Date()
                
    })
    res.json(database.users[database.users.length-1]);
})

app.get('/profile/:id', (req, res) => {
    const {id} = req.params;
    let found = false;
    database.users.forEach(user => {
        if (user.id === id) {
            found = true;
            return res.json(user);
        }
    })
    if (!found) {
        res.status(404).json('No such user');
    }
})

app.post('/image', (req, res) => {
    const {id} = req.body;
    let found = false;
    database.users.forEach(user => {
        if (user.id === id) {
            found = true;
            user.entries++
            return res.json(user.entries);
        }
    })
    if (!found) {
        res.status(404).json('No such user');
    }

})

app.listen(3000,() =>{
    console.log('app is running on port 3000');

})

**Comment by dark-magic** [comment]
how do you start your code? launch.json? if yes, please send it so we can see what it does.

**Comment by CharlieIoD** [comment]
Thank you for your response.

I am working through the Zero to Mastery web developer course on Udemy. I have got to the stage where I have two instances of Visual Studio Code running simultaneously. One with the front end App.js, with all its components and one with the serve.js file and all its controllers. Each one has the terminal open and node is started by entering 'npm start'. There is also a Post Gres database open to which stores the data.

The debugging started quite by accident. I must have mistyped some keys and there it was.

I have attached a screen shot with the messages the debugger spits out and the debug button that has appeared in the package.js file. I really want to understand what is going on and regain control, so that I can invoke this feature, when I want and turn it off, when I don't. At the moment, I feel like I've been hacked.

I would be very grateful for your assistance.

Bets regards

Charles Efford

________________________________

**Comment by dark-magic** [comment]
I dont see the screenshot you sent, but I think the debugger you mean is nodemon.

**Comment by CharlieIoD** [comment]
Thanks Lance.

Yes, it is nodemon.

Here is a copy of the package.json.

{
  "name": "node",
  "version": "1.0.0",
  "main": "script.js",
  "scripts": {
    "start": "nodemon server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.18.2",
    "clarifai": "^2.9.1",
    "cors": "^2.8.5",
    "express": "^4.16.2",
    "knex": "^0.21.1",
    "mysql": "^2.18.1",
    "node-trx": "^0.9.1",
    "pg": "^7.18.2"
  },
  "devDependencies": {
    "nodemon": "^2.0.4"
  },
  "description": ""
}


________________________________

**Comment by dark-magic** [comment]
spam ctrl+c till it works

**Comment by dark-magic** [comment]
and maybe dont reply by mail and look into markdown

**Comment by CharlieIoD** [comment]
OK.
![Screenshot (23)](https://user-images.githubusercontent.com/19762472/85225574-44f69d80-b3ca-11ea-9e08-8c762be173ec.png)
I added the screenshot as an image.

**Comment by dark-magic** [comment]
if you dont want nodemon simply uninstall it, idk what you want

**Comment by CharlieIoD** [comment]
Nodemon was installed as part of the tutorial and it has been running without the debugger for some time. Is there a way to turn the debugger back off please?

**Comment by CharlieIoD** [comment]
The penny has dropped. Is the debugger an integral part of nodemon and the debug button has been there since I installed it and I just didn't notice it? Could the error codes be generated by using Postman and I can ignore them?

**Comment by dark-magic** [comment]
nodemon automatically restarts the project when you change the code, therefore there is no normal debugger then. the debug button is a new vs code feature I believe. The error outputs are errors in your code

**Comment by CharlieIoD** [comment]
Thanks for all your trouble and patience. I had the wrong end of the stick. It's a steep learning curve, with this tutorial.  I thought I had triggered function that I could turn of, when it was there all the time, and it just responded to a mistake. Newcomers eh? Sorry about that chief.

**Comment by dark-magic** [comment]
haha, that happens sometimes
