### ISSUE TITLE
Public and Source folder's are not creating in React

### ISSUE THREAD

**Issue by nikilssriram** [nodejs/help#2787]
The public and the source folder's are not creating in create-react-app I've looked at every post and I tried removing everything and nothing works! Please help me I'll send a few screenshots

![irandacommand](https://user-images.githubusercontent.com/67137222/85208713-7185b900-b2e7-11ea-8843-e0b57652bea3.PNG)
So I ran the command correctly then I will show you that it skipped the Public and the Source
![noworking](https://user-images.githubusercontent.com/67137222/85208737-9da13a00-b2e7-11ea-992c-67b1383b2810.PNG)

So I had the node_modules but I deleted it to fix something and yeah so It doesn't work

Hope you are having a nice day and see you later

**Comment by addaleax** [comment]
Hi @nikilssriram!

So, for one, this is not a problem with Node.js itself, but probably either with `npx`/`npm` or `create-react-app`. So while we’re still happy to help you if we can, you might find the issue trackers of those projects more helpful.

Can you share the output of `npx create-react-app other-app`? I know it prints quite a large amount of text, but it would still be useful. If the output mentions a reference to some kind of debug log (e.g. an npm debug log), sharing that file might also help with diagnosing what’s wrong here.

**Comment by nikilssriram** [comment]
Thank you for the response @addaleax  I tried npm create-react-app other-app and it doesn't work here I will send you the output
![okaythen](https://user-images.githubusercontent.com/67137222/85209464-1a82e280-b2ed-11ea-92ce-6e042d81c1ea.PNG)

That's the output thank you in advance


>

**Comment by addaleax** [comment]
Not sure about that output – did you press Ctrl+C? Doing that is expected to result in an incomplete directory, because it interrupts `create-react-app` at a random point in time, at which it might not be done yet.

**Comment by nikilssriram** [comment]
okay this case is closed i found another computer to work on thanks for trying to help me
