### ISSUE TITLE
How do i fix ReferenceError: require is not defined?

### ISSUE THREAD

**Issue by LonlyGamerX** [nodejs/help#2788]
* **Node.js Version**: v12.18.1
* **OS**: Windows 10

I normally dont recieve this sort of error before. I know if i run it in the browser i will get this error but currently what im working on is a randomizer for a game where no html, css, or php is used. 
Below you can see what line is causing this error:
`const chalk = require('chalk');`
Ive used chalk before so i dont understand why im getting this error now.

**Comment by dark-magic** [comment]
so you run this with nodejs? could you send a screenshot on how you run it and the error it outputs? with this single line its gonna be hard to find the cause of the error

**Comment by LonlyGamerX** [comment]
Yeah here:
![bn](https://user-images.githubusercontent.com/49322497/85226187-90af4400-b3d6-11ea-814c-95051d2f56c3.png)
Note ive censored some stuff i dont want u to see and the reason in part of the code at location it says %20 was cause the file location has spaces in the name. Its run on visual studio code.

**Comment by dark-magic** [comment]
Hej, interesting..
I noticed that you use some `ModuleJob.run` which starts this code, do you have the same issue when you start this file manually with `node main.js`?

**Comment by LonlyGamerX** [comment]
Yes the exact same, ive already tried it.

**Comment by dark-magic** [comment]
looks like a problem with node, maybe reinstalling it works 🤷‍♂️

**Comment by addaleax** [comment]
The fact that `ModuleJob.run` is in the stack trace means that Node.js thinks it should execute this file as an ES module, rather than a CommonJS module.

I think the main two ways for influencing that decision are:

- The `NODE_OPTIONS` environment variable. Maybe print its contents (e.g. with `console.log(process.env.NODE_OPTIONS)` before the `require()` call in question)?
- The nearest `package.json` could also indicate that modules should be interpreted as ES Modules by default?

**Comment by LonlyGamerX** [comment]
This is how the package.json file looks like.
![bv](https://user-images.githubusercontent.com/49322497/85226819-cc97d880-b3d9-11ea-8858-bdd1efa3814a.png)
Note the gape is meant to be where the keywords ares

**Comment by dark-magic** [comment]
the `type: module` is the problem

**Comment by LonlyGamerX** [comment]
okay thanks for the info but if this is the case how would i import files into my main because i normally did `import {runes0, runes1, runes2, runes3, runes4, runes5} from './runes.js';` this worked when i have 
`type: module` but it doesnt when i dont have it.

**Comment by dark-magic** [comment]
I believe, you can either use es6 imports, or nodejs requires, but not both at the same time.

**Comment by LonlyGamerX** [comment]
kk thanks for the info it help a lot.
