### ISSUE TITLE
Need helping finding some key areas of the source code (for sandboxing)

### ISSUE THREAD

**Issue by wysisoft** [nodejs/help#2789]
* **Node.js Version**:Latest release
* **OS**:Ubuntu 20
* **Scope (install, code, runtime, meta, other?)**: Build
* **Module (and version) (if relevant)**:N/A

I would like help in finding 3 key areas of the Nodejs source code
1 - anywhere a file is written or read from the OS
2 - anywhere a network socket (or other networking item) is opened or closed
3 - anywhere a process is spawned / launched.

I can take it from there. Any help finding these .cc locations? I would like to try to remove these functionalities to better create a sandbox

**Comment by addaleax** [comment]
@wysisoft I think the best thing you can do is look through the list of libuv functions and then grep for those in Node.js core?

**Comment by wysisoft** [comment]
Thank you for the excellent answer! I will try it out and see how it works. Am I the first to attempt something like this, or is there previous work I can borrow from?

**Comment by addaleax** [comment]
@wysisoft I think the closest thing might be https://github.com/nodejs/node/pull/33504 (and its predecessor https://github.com/nodejs/node/pull/22112). Those operate at the C++ binding layer, instead of the libuv layer, though, so it’s a bit of a different approach with its own upsides and downsides

**Comment by PoojaDurgad** [comment]
@wysisoft - is this issue still outstanding? did @addaleax 's suggestion help you to resolve your issue?

**Comment by wysisoft** [comment]
Yes this was helpful thanks

**Comment by PoojaDurgad** [comment]
closing the issue as it resolved.
