### ISSUE TITLE
node . not working

### ISSUE THREAD

**Issue by Sicko-Pikachu** [nodejs/help#2791]
An error happens to me when I do node . I'm making a discord bot and the command "node ." Is one of the most important. Here is the error:
 SyntaxError: Identifier 'Discord' has already been declared
[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

**Comment by dark-magic** [comment]
this means that you declared the variable `Discord` multiple times in the same scope

**Comment by PoojaDurgad** [comment]
@Sicko-Pikachu - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
