### ISSUE TITLE
npm install -g apiconnect 

### ISSUE THREAD

**Issue by singhdamodar3** [nodejs/help#2792]
* **Node.js Version --> v10.21.0, NPM -6.14.5**:
* **MacOS**:
* **Module apiconnect**:

Trying to install IBM apiconnect and getting below error **when using V10.X**
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for apiconnect-config@2.0.0: wanted: {"node":">=6 <10"} (current: {"node":"10.21.0","npm":"6.14.5"})
npm ERR! notsup Not compatible with your version of node/npm: apiconnect-config@2.0.0
npm ERR! notsup Not compatible with your version of node/npm: apiconnect-config@2.0.0
npm ERR! notsup Required: {"node":">=6 <10"}
npm ERR! notsup Actual:   {"npm":"6.14.5","node":"10.21.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Damodar.kumar@ibm.com/.npm/_logs/2020-06-23T14_36_39_060Z-debug.log
[2020-06-23T14_36_39_060Z-debug.log](https://github.com/nodejs/help/files/4820104/2020-06-23T14_36_39_060Z-debug.log)

**When using V9.X getting below error.**
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for apiconnect-cli-pm@5.0.3: wanted: {"node":">=10 <12"} (current: {"node":"9.0.0","npm":"5.5.1"})
npm ERR! notsup Not compatible with your version of node/npm: apiconnect-cli-pm@5.0.3
npm ERR! notsup Not compatible with your version of node/npm: apiconnect-cli-pm@5.0.3
npm ERR! notsup Required: {"node":">=10 <12"}
npm ERR! notsup Actual:   {"npm":"5.5.1","node":"9.0.0"}

**Please the attached debug file. Can you please suggest me which node version I should install to make sure I will be able to install IBM API connect.**

**Comment by joesepi** [comment]
I think your version of API Connect may need to be updated.

**Comment by mhdawson** [comment]
I agree I think this line:

> npm ERR! notsup Required: {"node":">=6 <10"}

Says your current version requires greater or equal to Node 6 and less than Node 10.  Since Node 10 is the earliest LTS upgrading API Connect would be the best bet.

**Comment by singhdamodar3** [comment]
npm ERR! notsup Required: {"node":">=10 <12"} When using "node":"9.0.0"
npm ERR! notsup Required: {"node":">=6 <10"} when using "node":"10.21.0"

That is the confusion, I don't understand which I should install, 9, 10 or 11 version of node. :(

thanks for the reply @mhdawson and @joesepi

**Comment by singhdamodar3** [comment]
Hey All, thank you for all the valuable comments. I was able to fix this issue, Share the details so that everyone can get the benefit of it.
 I had so many node versions installed in my system so I did clean up including cache cleaning. Make sure no node_module should be there in the system.

sudo rm -rf ~/.npm ~/.nvm ~/node_modules ~/.node-gyp ~/.npmrc ~/.node_repl_history
sudo rm -rf /usr/local/bin/npm /usr/local/bin/node-debug /usr/local/bin/node /usr/local/bin/node-gyp
sudo rm -rf /usr/local/share/man/man1/node* /usr/local/share/man/man1/npm*
sudo rm -rf /usr/local/include/node /usr/local/include/node_modules
sudo rm -rf /usr/local/lib/node /usr/local/lib/node_modules /usr/local/lib/dtrace/node.d
sudo rm -rf /opt/local/include/node /opt/local/bin/node /opt/local/lib/node
sudo rm -rf /usr/local/share/doc/node
sudo rm -rf /usr/local/share/systemtap/tapset/node.stp
brew uninstall node
brew doctor
brew cleanup --prune-prefix
Then, I reinstalled v10.21.0
nvm install v10.21.0

Verified the version
System - Mac OS
node -v
v10.21.0
npm -v
6.14.4

Then, run the below command, and thankfully I was able to install apiconnect. :)
npm i -g apiconnect@5.1.22
![Screenshot 2020-07-05 at 18 49 35](https://user-images.githubusercontent.com/16591532/86538882-b0735b80-bef0-11ea-898d-3981e392bcd8.png)

:)

**Comment by mhdawson** [comment]
@singhdamodar3 thanks for the update, closing.
