### ISSUE TITLE
EBADF closing file descriptor

### ISSUE THREAD

**Issue by TanninOne** [nodejs/help#2793]
Version: Electron 8.3.1/Node 12.13.0
Platform: Windows 10 64bit (up to date)
Subsystem: fs

### What steps will reproduce the bug?

I have not been able to reproduce this on my system but the code in question is simply this:
```
        fs.open(fullPath, 'wx')
          .then((newFd) => {
            fd = newFd;
            return fs.close(newFd);
```
The file basically just acts as a lock, all we want to do here is create the file.

### How often does it reproduce? Is there a required condition?

Unknown but it seems to be extremely rare, As in: probably runs fine a couple million times before failing. So far no pattern as to which users are affected.
Antivirus software may be involved.

### What is the expected behavior?

It just works

### What do you see instead?

The close call raises an Error with code "EBADF".
Important: It's not the fs.open that fails but the close!
My assumption is that the open already failed to actually open the file but instead of throwing an error continues as if it hat succeeded but that's just a guess really.

### Additional information

Sorry, I don't know anything else, all I know is that the function fails with EBADF and the stack points at fs.close.
As I said, this problem is quite rare and seemingly random so I don't know how to further investigate. Why would close fail with EBADF if the open was successful?

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because it's unlikely to be a bug in Node.js itself. Can move it back if needed.

**Comment by TanninOne** [comment]
It's true that I'm using a wrapper library but this is exactly why I didn't want to tell that. It's always the same, every problem is immediately rejected without anyone willing to dig deeper as soon as you see an opportunity to blame it on something else, without checking or even asking whether that's plausible.

I use fs-extra which in turn uses graceful-fs but before I reported this I looked into both their code. fs-extra does nothing for these functions apart from promisifying the calls. graceful-fs does nothing except catching certain errors (EMFILE specifically) and retrying.
Neither of these libraries could possibly introduce a new error that wasn't first thrown by node.js. Neither of them will report success on an open if node.js reported a problem.

@bnoordhuis this is definitively not in the wrapper libraries so unless you can point at my code and show me what I'm doing wrong this is almost certainly a bug and not a help request.
I won't rule out that it's in libuv instead of node but at the very least someone should look into it.

**Comment by bzoz** [comment]
@TanninOne 

> every problem is immediately rejected without anyone willing to dig deeper

That is not true. One example I remember - [libuv now exposes original fs error](https://github.com/libuv/libuv/commit/457285827cfcc6bbe33abe9bd211e7cee332b3c5), it will be soon(ish) added to Node.

It is defiantly possible that the libs you are using are causing this bug. AFAICT no one has reported such bug before, but I guess Vortex is something special w/g file access. I'll take a look, but please post some source that I can try to reproduce on my local machine without guessing what libs (and how) you are using.

**Comment by bzoz** [comment]
@TanninOne I've found EBADF issue in close here: https://github.com/facebook/jest/issues/7709, didn't see this in Node so my guess it was decided it was a bug in one of the libs. Maybe take a look there and see if by chance you are also using one of the libs mentioned there?

Anyway, I've taken a look at the code in libuv and everything looks ok. The EBADF will happen when [`_close`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/close?view=vs-2019) fails for whatever reason, like double close or `-1` passed as fd.

**Comment by TanninOne** [comment]
> That is not true. One example I remember - [libuv now exposes original fs error](https://github.com/libuv/libuv/commit/457285827cfcc6bbe33abe9bd211e7cee332b3c5), it will be soon(ish) added to Node.

look at the referenced issue, how much time and energy I had to spend on that to convince someone there is a use to accessing the native error code. The initial reaction was still "p**s off, if you don't like it, fix it yourself".
Sorry, but I just don't have the energy to go through this every time.

> It is defiantly possible that the libs you are using are causing this bug. 

how? How would promisifying the functions suddenly introduce EBADF errors?

> AFAICT no one has reported such bug before, but I guess Vortex is something special w/g file access. I'll take a look, but please post some source that I can try to reproduce on my local machine without guessing what libs (and how) you are using.

Vortex is special insofar as it primarily focuses on Windows, has hundreds of thousands of users, does potentially tens of thousands of file operations in quick succession and also, Vortex reports every "unexpected" error to the user. In this case for example, if I did what most developers do - log the EBADF to console and go on as if nothing had happened - it would probably just never have come up. If the problem here is that the fd is -1 then there probably wouldn't be a problem, close failed on a file that was never opened, end result is the same, could be ignored. But it doesn't explain why open returned success with a fd of -1.

My approach has been to report every possible error and only "suppress" them after I've convinced myself it's not an issue and/or can't be fixed.
So yes, I will encounter more problems than most developers, that doesn't mean I'm doing anything wrong or that the problems aren't problems.
It means I will be able to investigate more obscure problems that might otherwise elude you for ages, imho you should be happy about that. Filesystem functions are not something where bugs can just be ignored, no matter how obscure. imho.

> I'll take a look, but please post some source

As I said, I wasn't able to reproduce this myself. As I said, this code probably runs successfully 50 million times before it fails once. And even then, there is a good chance some shitty AV is involved or a broken disk or a bad connection to a network mounted drive or something.
Considering how rare it is I don't see how I could narrow it down to figure out the exact circumstances. And yes, that's annoying, but we have to work with what we have, and that is an open call that, under unknown circumstances, seems to report success even though it failed to open a file or a close that reports EBADF even though it was passed a valid fd.
The only other explanation is that the fd became invalid asynchronously but I'm not aware of anything that could cause that.

I will certainly add some logging so that, in the error case, we will see what the fd was (should help test the theory of whether the open reported success and then returned a fd of -1) but maybe someone has another idea what might be going wrong here. 

> Maybe take a look there and see if by chance you are also using one of the libs mentioned there

No, not using that write-file-atomic lib.

**Comment by bzoz** [comment]
> "p**s off, if you don't like it, fix it yourself"
I'm sorry you feel this way. We are all trying to do our best, but there is only so much we can do.

> how? How would promisifying the functions suddenly introduce EBADF errors?
IDK, I haven't seen the code. That's the point. `fs.open` can fail with EMFILE, so the libs you are using could interfere here. 

Oh, and it is unlikely `open` returned success with invalid fd. We do check every WinAPI call for the result.

> but maybe someone has another idea what might be going wrong here.
The AV/network issues sound most probable. More logging will defiantly help.

**Comment by PoojaDurgad** [comment]
@TanninOne - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive .closing. feel free to reopen the issue if its still outstanding
