### ISSUE TITLE
memory leak in filereadsync

### ISSUE THREAD

**Issue by Itayp1** [nodejs/help#2795]
i get a memory leak in the running of this program 
i read all files from a dir one by one 
i have 630 files and every file is 80 mega 
when the program get to file number 30 i get memory leak 

all the file are almost the same in size and content 
its looks like the node dosent release the memory from that line 

    let filecontent = fs.readFileSync(files[file] ,"utf8").split("\n")

```
const fs = require("fs")

const files = fs.readdirSync(".","utf8")




const start = ()=> {
    const ipList=new Map(); 

    for(let file in files){
        let filecontent = fs.readFileSync(files[file] ,"utf8").split("\n")
        for(let line in filecontent ){
    
            const [date , time , ip , port , cs] = filecontent[line].split(" ")
           cs && cs.toLowerCase().includes("administrator") ?ipList.set(ip , cs) : null
           
        }

    
    }

    const arr =Array.from(ipList).map(arr=>arr[0])
    fs.writeFileSync("list.csv" , arr )
    console.log(arr)
}

start()
```

**Comment by addaleax** [comment]
@zhangwinning Using `fs.readFileSync()` does not inherently lead to a memory leak.

Having a full reproduction would be helpful here, though.

**Comment by zhangwinning** [comment]
@addaleax tks, I got it.

**Comment by Itayp1** [comment]
i tried to restore this on another computer and its worked file 
without memoryleak  in my current computer i have node version v12.18.1 
i my orginal computer i have older node version 
i will tried to upgrade the nodeversion and will updatet

**Comment by PoojaDurgad** [comment]
@Itayp1 - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive issue.
