### ISSUE TITLE
the options columnOffset property of vm module 

### ISSUE THREAD

**Issue by zhangwinning** [nodejs/help#2798]
* **Node.js Version**:v12.14.0
* **OS**:vm
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

Hello everyone, I execute below code. 
```js
const vm = require('vm');
let code = `throw new Error();`;
vm.runInNewContext(code, {}, {columnOffset: 10});

```
errors is below. 
```
evalmachine.<anonymous>:1
throw new Error();
^

Error
    at evalmachine.<anonymous>:1:17
    at Script.runInContext (vm.js:127:20)
    at Script.runInNewContext (vm.js:133:17)
    ......
```

while when I run below code. 
```js
const vm = require('vm');
let code = `throw new Error();`;
vm.runInNewContext(code, {});
```
error is below it. 
```
evalmachine.<anonymous>:1
throw new Error();
^

Error
    at evalmachine.<anonymous>:1:7
    at Script.runInContext (vm.js:127:20)
    at Script.runInNewContext (vm.js:133:17)
    .....
```
The different is **evalmachine.<anonymous>:1:17** from **evalmachine.<anonymous>:1**

from the [runInNewContext](https://nodejs.org/api/vm.html#vm_vm_runinnewcontext_code_contextobject_options) I get the 
> columnOffset <number> Specifies the column number offset that is displayed in stack traces produced by this script. Default: 0. 

however I don't know the columnOffset what is the works? for the developer, Can I get any useful information from the columnOffset property?

**Comment by devsnek** [comment]
Column offset is used to represent JS code embedded into other sources, such as html:
```html
<head>
  <script>let a = 1;
let b = 2;
  </script>
</head>
```

In this example, the first line of js code needs a column offset. The JS source inside the script tag starts at index 0, but within the larger html document it starts at the tenth column.

**Comment by zhangwinning** [comment]
@devsnek  Good to know, thanks!
