### ISSUE TITLE
node ./bin/www throwing error

### ISSUE THREAD

**Issue by aneezx** [nodejs/help#2799]
* **Version**: 12.18.0
* **Platform**: 64-bit (Windows)
* **Subsystem**: 

### What steps will reproduce the bug?

I am trying to run my nodejs api usng npm start which is 'node ./bin/www' but it doesn't start and throws error

### How often does it reproduce? Is there a required condition?
No

### What is the expected behavior?

The applicaiton should connect to MSSQL

### What do you see instead?

> amat.partpricing.api@0.0.0 start C:\TFS\Spares Part Pricing\SPP_SECURED\AMAT.PARTPRICING.API
> node ./bin/www

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\TFS\Spares Part Pricing\SPP_SECURED\AMAT.PARTPRICING.API\bin\www'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amat.partpricing.api@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amat.partpricing.api@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AMohammedSalX0115481\AppData\Roaming\npm-cache\_logs\2020-06-25T06_03_48_719Z-debug.log

### Additional information

**Comment by bzoz** [comment]
Transferred to nodejs/help.

Node complains that it cannot load `./bin/www` file

**Comment by bzoz** [comment]
Is `./bin/www` a file or folder?

**Comment by aneezx** [comment]
> Is `./bin/www` a file or folder?

it is a folder. I am not able to find it outside the node_modules folder. I am trying to execute my project using this command.

**Comment by bzoz** [comment]
Whats inside the folder?

**Comment by aneezx** [comment]
Nothing

> Whats inside the folder?

**Comment by aneezx** [comment]
is there any other way to exeucute the solution. I am not able to do it for quite sometime now

**Comment by bzoz** [comment]
So.. If there is nothing in the folder, what do you expect Node will run?

**Comment by bzoz** [comment]
Do you have any Node.js code?

**Comment by aneezx** [comment]
I mean not inside that folder. I have a nodejs project and I am trying to run that. These are the script we use for starting the application. 

 "scripts": {
    "start": "node ./bin/www",
    "devmode": "set NODE_ENV=development | nodemon app.js --experimental-modules",
    "qamode": "set NODE_ENV=qa | nodemon app.js",
    "prodmode": "set NODE_ENV=prod | nodemon app.js "
  },

**Comment by bzoz** [comment]
Node.js takes the .js file as its first argument. You need to change this start script,  try maybe `node app.js`?

**Comment by bzoz** [comment]
I guess this can be closed now.

**Comment by RISHAB-182001** [comment]
I'm getting the same doubt ....I didnt quite understand how u made it work later
