### ISSUE TITLE
Node.js Compute Resources

### ISSUE THREAD

**Issue by kmcohens** [nodejs/help#2800]
* **Node.js Version**: 7
* **OS**: Red Hat
* **Scope (install, code, runtime, meta, other?)**: Installation, Optimal RAM and Hard Disk Space
* **Module (and version) (if relevant)**:

I am working to determine the recommended RAM (GB) and hard disk space (GB) required to install and optimally use the GNU GCC. Any help would be greatly appreciated.

Thank you!

Kahdeem Cohens

**Comment by PoojaDurgad** [comment]
@kmcohens - is the requirements for to install Node.js or  gcc ?
there is no well defined rule about the actual amount of these resources, as it depends on a lot of other factors such as the CPU clock speed, CPU count etc. But a reasonable configuration for building and running Node.js can be: 8 GB of RAM, 2 GB of disk, with a system that has 4 or 8 logical CPUs (a combination of core and hyper-threading).

**Comment by PoojaDurgad** [comment]
inactive. closing please feel free to re-open the issue if its still outstanding
