### ISSUE TITLE
Node.JS installation ended prematurely [Windows 7]

### ISSUE THREAD

**Issue by RebugSEN** [nodejs/help#2801]
Hello, I have a problem. I am using a Windows 7 Ultimate 64 bit processing system.
I remember this program .msi used to install 100%  fully for me, but now it doesn't I need help!

It ends up saying, "Node.JS ended up prematurely"

**Comment by PoojaDurgad** [comment]
@RebugSEN - for me with your issue I guess it is not a problem with Node.js . can you refer this https://www.thewindowsclub.com/this-installation-package-could-not-be-opened hope it helps.

**Comment by PoojaDurgad** [comment]
inactive. closing!! please feel free to re-open the issue if its still outstanding!!
