### ISSUE TITLE
Redirect to last page with scroll position

### ISSUE THREAD

**Issue by chandruv21** [nodejs/help#2802]
I have a issue after adding items to cart.
After adding items to cart my code is 
res.redirect('back'); ---> it is taking me to last page. But what I need is redirect to last page and last item(scroll position) that user clicked.

Thanks in Advance🙂.

**Comment by HarshithaKP** [comment]
@chandruv21, Can you please provide minimal reproducible code ?

**Comment by chandruv21** [comment]
> @chandruv21, Can you please provide minimal reproducible code ?

router.get('/cart/add/:product', function (req, res) {

    var slug = req.params.product;

    Product.findOne({ slug: slug }, function (err, product) {
        console.log( "Product Details",product);
        if (err)
            console.log(err);

        if (typeof req.session.cart == "undefined") {
            req.session.cart = [];
            req.session.cart.push({
                title: slug,
                qty: 1,
                price: parseFloat(product.price).toFixed(2),
                image: '/product_images/' + product._id + '/' + product.image
            });
        } else {
            var cart = req.session.cart;
            var newItem = true;

            for (var i = 0; i < cart.length; i++) {
                if (cart[i].title == slug) {
                    cart[i].qty++;
                    newItem = false;
                    break;
                }
            }
            if (newItem) {
                cart.push({
                    title: slug,
                    qty: 1,
                    price: parseFloat(product.price).toFixed(2),
                    image: '/product_images/' + product._id + '/' + product.image
                });
            }
        }
        var cart = req.session.cart;
        console.log("req.session.cart in add product",req.session.cart);
        res.redirect('back'); //HERE I WANT TO GO BACK AND TO LAST SCROLL POSITION.
    });
});
