### ISSUE TITLE
Can't Delete!

### ISSUE THREAD

**Issue by HannexYT** [nodejs/help#2803]
* **Current And Recommended**:
* **Windows**:
* **Other**:
* **Not English So I don't really Understand**:

So I have downlded Node.Js, And I can't delete it, I want to downda the new Recommended one but when I deleted the current one it said: A later version of node.js is installed, Setup will now exit
when I already have deleted it, Any fxes? Sorry if my english is bad

**Comment by Hakerh400** [comment]
Go to Control Panel and find "Add or Remove Programs" option. Open it and uninstall Node.js from there. If you can't find it, I think it is enough (but not recommended) to simply delete the `nodejs` folder from `C:\Program Files`

**Comment by PoojaDurgad** [comment]
@HannexYT - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive closing. feel free to re-open the issue if its still outstanding
