### ISSUE TITLE
EPROTO wrong signature error on http fetch

### ISSUE THREAD

**Issue by gc** [nodejs/help#2804]
* **Node.js Version**: 12.18.1
* **OS**: Debian 10
* **Scope (install, code, runtime, meta, other?)**: Runtime
* **Module (and version) (if relevant)**: node-fetch 2.6.0

**Code:**
```js
const fetch = require('node-fetch');
fetch('https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws?player=magnaboy');
```

**Problem:**

It gives me a really weird error, that I have never seen before and can't find any information about:

```request to https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws?player=magnaboy failed, reason: write EPROTO 140266961057664:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:../deps/openssl/openssl/ssl/t1_lib.c:1146:```

- The debian 10 server is almost completely fresh with no changes made to it, just installed nodejs and running this. 
- I don't encounter this issue with other websites
- I don't encounter this problem, running the same nodejs version on my *ubuntu 16.04* server, but I do on my debian 10 server.
- From my googling, it seems related to openSSL, and maybe is an issue with the website itself? If it is an issue with the website, and not nodejs, some clarification on what exactly is wrong with the website would be helpful too so I could ask them to look at fixing it.

**EDIT:** I found that this fixes the problem:

- Edit `/etc/ssl/openssl.cnf`
- Change `CipherString = DEFAULT:@SECLEVEL=2` to `CipherString = DEFAULT:@SECLEVEL=1`

I don't know fully what this does, but lowering the "sec level" doesn't sound like it's a good thing to do.

**Comment by Joran-s** [comment]
Thanks a lot, I had the exact same issue. After trying this it didn't work straight away, I had to run it with sudo. Now it works on a Rasperry Pi 3B+.

**Comment by MatiasFilho** [comment]
Thank you very much for share. I was trying to solve this problem in my aplication.

**Comment by PoojaDurgad** [comment]
Looks like this can be closed now. please let me know if that is not the case.

**Comment by MwumLi** [comment]
Why simply close this question? Why don't say what the reason is here？ I can still recover this

**Comment by MwumLi** [comment]
> Why simply close this question? Why don't say what the reason is here？ I can still recover this. Switch to node@16.18.1, everything is okay, but switch to node@18.12.1, this question must be happen when `yarn add <pacakge>`, but npm package can be downloaded in browser.

This question happened in private npm registry, but not happed in public registery https://registry.npmjs.org/.

**Comment by hellojukay** [comment]
+1
