### ISSUE TITLE
node-v12.18.1-x82.msi does not want to install

### ISSUE THREAD

**Issue by Azeenia** [nodejs/help#2808]
Hello, I have an installation problem, it is that when I install Node.JS correctly. It remains blocked at the end of loading and the status is marked nothing. Thank you for responding in advance.

* **Node.js Version** : node-v12.18.1-x82.msi
* **OS** : Windows 7
* **Scope (install, code, runtime, meta, other?)** : Install
* **Module (and version) (if relevant)** :

Here is the image that loading is blocked. [
![image](https://user-images.githubusercontent.com/54627756/85947805-2ace3980-b94d-11ea-94d6-7343063ce074.png)
](url)

**Comment by PoojaDurgad** [comment]
@Ethann45140 - is this issue still outstanding? not sure but can you try  by disabling the network connection and make sure that you don't have any previous installed version of node and see what it shows? meanwhile you can try this also https://github.com/nodejs/node/issues/4329#issuecomment-169952550 .

**Comment by Ethann45140** [comment]
Hi @PoojaDurgadI managed to solve the problem you gave me. But I have another issue that there is on [nodejs/node/issues/4329#issuecomment-201617098](url), When I type the command ```npm i install``` , it gives me an error with a log : 

``` 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose npm-session 464869112ed5f771
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for install@latest network timeout at: https://registry.npmjs.org/install
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 160205ms
10 verbose type request-timeout
11 verbose stack FetchError: network timeout at: https://registry.npmjs.org/install
11 verbose stack     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:61:18)
11 verbose stack     at listOnTimeout (internal/timers.js:549:17)
11 verbose stack     at processTimers (internal/timers.js:492:7)
12 verbose cwd C:\Windows\system32
13 verbose Windows_NT 6.1.7601
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "install"
15 verbose node v13.14.0
16 verbose npm  v6.14.4
17 error network timeout at: https://registry.npmjs.org/install
18 verbose exit [ 1, true ]
```
So I'm guessing there is a package installation problem?

**Comment by RaisinTen** [comment]
It seems to be a problem with `npm v6.14.4`. Does this help: https://github.com/npm/cli/issues/1185?

**Comment by PoojaDurgad** [comment]
@Ethann45140 - what is the output of `where node` and `where npm` ? and what is `npm i install` ? you can give  `npm install / npm i`  and give `npm install -g npm@latest`  in the command prompt to update the npm later check the version of node and npm by giving `node -v` and `npm -v`

**Comment by Ethann45140** [comment]
@RaisinTen The output of ```where node``` is ```C:\Program Files\nodejs\node.exe``` and that of npm is ```C:\Program Files\nodejs\npm C:\Program Files\nodejs\npm.cmd```. The version of node and npm are: ```v.13.14.0``` and ```6.14.4```

**Comment by Ethann45140** [comment]
@RaisinTen I will try if I can fix the problem

**Comment by PoojaDurgad** [comment]
@Ethann45140 - looks good.
