### ISSUE TITLE
Reading line numbers and lines 

### ISSUE THREAD

**Issue by ev1stensberg** [nodejs/help#281]
Hey! I'm a bit confused on how node reads line numbers on `start` and `end` in options of a write stream. I want to output something on line 5, but rather than going to line number 5, it goes to line 5 in the first line.

```js
  const options = {
                flags: 'r+',
                defaultEncoding: 'utf8',
                fd: null,
                start: 5,
                end: 6,
                mode: 0o666,
                autoClose: true
                }
```

=> outputs on first line, not fifth

**Comment by ev1stensberg** [comment]
With other words, how can I make it so start and end works correctly without setting the start to something like `140`, I need this to work like this :/

**Comment by lordKnighton** [comment]
@ev1stensberg did you solve this issue?

**Comment by ev1stensberg** [comment]
Yes, I did! But this should really be built in node. If not, it's hard to relate to the data properly on read/write-streams.
