### ISSUE TITLE
Understanding time elapsed on async functions

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/help#2810]
* **Node.js Version**: v12.13.1
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: runtime

Hi everyone,

I created some benchmarking tests around my application and noticed the async function take more time to run, my hypothesis is that async function is executed on the next tick of loop, but I don't know how I can make assurance of it. 

How I can understand the elapsed code in this case and why this occurs?

Example code
```js
async function a() {
  return 'hello world'
}

function b() {
  return 'hello world'
}

async function main() {
  console.time('time-a')
  await a();
  console.timeEnd('time-a')

  console.time('time-b')
  b();
  console.timeEnd('time-b')
}

main()
// time-a: 0.353ms
// time-b: 0.027ms
```

Note: If I invert the function to call `b()`  earlier the `a()` take longer.

**Comment by devsnek** [comment]
async functions have a lot more to do than normal functions. they allocate promises, capture stack information into the heap for suspending and resuming, etc.

**Comment by ORESoftware** [comment]
async functions use generators under the hood. to understand async/await you must understand how generator functions work. generator functions are suspended and resumed, very differently from how normal functions work.

**Comment by devsnek** [comment]
@ORESoftware it might be more accurate to say that async functions and generators use the same mechanism under the hood.

**Comment by RafaelGSS** [comment]
Thanks all.

How I can discover it myself? Reading the source code of `internals/*` or exists some documentation about these implementations?

**Comment by RafaelGSS** [comment]
The answers are enough. If anyone has the doc or some paths feel free to comment here.

Thanks.
