### ISSUE TITLE
problem with ng json module 

### ISSUE THREAD

**Issue by sunilchalla** [nodejs/help#2812]
C:\Users\isolvers>ng -v
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'C:\Users\isolvers\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:859:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by PoojaDurgad** [comment]
@sunilchalla - for me your issue looks like a dependency was removed somewhere.  can you try this for global angular-cli:  
`npm install -g @angular-devkit/core` .

**Comment by PoojaDurgad** [comment]
inactive ! closing. please feel free to re-open the the issue if its still outstanding
