### ISSUE TITLE
Hit error {"errno":"ENOBUFS","code":"ENOBUFS","syscall":"write"} when using net to write about 800MB data

### ISSUE THREAD

**Issue by xizhu-mstr** [nodejs/help#2814]
* **Node.js Version**: 10.15.3 and 12.18.1
* **OS**:Windows Server 2019 Datacenter
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: net

Example:
var client = net.connect({host:addr, port:parseInt(portnu,10)});
client.on('error', (error)=>{mylogger.log('error:', JSON.stringify(error));});
client.write(data, function(){
            mylogger.log("Send data, length:", length.toString())
});

We have set --max-old-space-size=4096 already. 
When the data size is around 800MB, error the "ENOBUFS" will be reported. I tried the same code with Node.js V8.11.1 the data can be sent successfully. 

I know that it is not good to write too much data in one chunk. But it takes time to shift to new code for our partner.

Is there any solution for this?

**Comment by sapics** [comment]
It looks similar issue with https://github.com/nodejs/node/issues/15617.
So, adding the option `agent:false` might help you, it is answered in [stackoverflow](https://stackoverflow.com/questions/10603860) (which is suggested in https://github.com/nodejs/node/issues/15617#issuecomment-331999323).

**Comment by PoojaDurgad** [comment]
@xizhu-mstr - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive issue . pls feel free to reopen the issue if its still outstanding
