### ISSUE TITLE
Replacing v8 with another JS engine in node

### ISSUE THREAD

**Issue by zherczeg** [nodejs/help#2816]
I would like to replace v8 with another engine in v8. I suspect this is a complex task, and it would be great if you could give me any advice how to do it. My plan is to keep v8.h and create an emulation layer to reduce changes in node. Any kind of documentation, key things I need to be aware of, build system changes I need to do, anything related could be helpful. Thank you!

**Comment by PoojaDurgad** [comment]
@zherczeg - did @devsnek ' s suggestion help you to resolve your issue?

**Comment by zherczeg** [comment]
We got some ideas from those other projects.

If somebody has a similar issue, this commit is mostly about creating empty stubs for each API function:
https://github.com/Samsung/node-jerryscript/commit/dabb7a6fad3717d3faffceb32cf73aa18eb1d7f7

These stubs can be replaced by an actual implementation later.

We currently have 71% pass rate on parallel tests, maybe it would be good to write something about the challenges we had. Anyway, I think this bug can be closed.
