### ISSUE TITLE
wasm debug crash in lldb on MacOSX

### ISSUE THREAD

**Issue by hardfist** [nodejs/help#2817]
* **Version**: 14.5.0
* **Platform**:  Darwin C02CTBPHMD6M 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
* **Subsystem**:

### What steps will reproduce the bug?

you can reproduce it in https://github.com/hardfist/wasm-demo,

![image](https://user-images.githubusercontent.com/8898718/86346209-28dae200-bc8f-11ea-8277-2233dba8ec01.png)

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because it's likely a toolchain issue, almost certainly not an issue with node itself.

**Comment by ggreif** [comment]
did you
```
(lldb) settings set plugin.jit-loader.gdb.enable on
```
?

**Comment by hardfist** [comment]
> did you
> 
> ```
> (lldb) settings set plugin.jit-loader.gdb.enable on
> ```
> 
> ?

yes, I set it on .lldbinit

**Comment by ggreif** [comment]
I am asking because that made breakpoints of `lldb-10` work for me. under `wasmtime-0.17`.

**Comment by hardfist** [comment]
> I am asking because that made breakpoints of `lldb-10` work for me, under `wasmtime-0.17`.

yes , it works well for wasmtime but not nodejs

**Comment by hardfist** [comment]
@bnoordhuis I can debug node using lldb my built node(https://github.com/nodejs/node/issues/34340) , but it seems that
node still doesn't not support wasm debug
![image](https://user-images.githubusercontent.com/8898718/88923015-99334e00-d2a3-11ea-9c09-b91ad75bac06.png)
