### ISSUE TITLE
BUG FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Akurejs** [nodejs/help#2821]
I'm having problems with the node I use to leave the discord bot online but I'm always getting this error, and it makes the bot go offline, the bug happens in intervals of about 1 hour and a half

node version: 12.18.2
64 bit 
linux
bug: https://hasteb.in/foheroti.php

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

\u003c--- Last few GCs ---\u003e

[1:0x3a94350] 17789228 ms: Scavenge 216.4 (256.5) -\u003e 215.7 (256.5) MB, 2.2 / 0.2 ms  (average mu = 0.223, current mu = 0.057) allocation failure 
[1:0x3a94350] 17789245 ms: Scavenge 216.7 (256.5) -\u003e 216.0 (256.8) MB, 2.6 / 0.2 ms  (average mu = 0.223, current mu = 0.057) allocation failure 
[1:0x3a94350] 17791720 ms: Mark-sweep 217.0 (256.8) -\u003e 213.0 (256.8) MB, 2406.5 / 0.4 ms  (average mu = 0.212, current mu = 0.197) allocation failure scavenge might not succeed


\u003c--- JS stacktrace ---\u003e

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1351acd]
Security context: 0x0ab2b39c08d1 \u003cJSObject\u003e
    1: dataMessage [0x1c1d403f50d9] [/home/node/node_modules/ws/lib/receiver.js:~406] [pc=0xa4e50d0fa](this=0x0e2f5ad5e521 \u003cWritable map = 0x15f3cd86e929\u003e)
    2: _write [0x1c1d403f5e01] [/home/node/node_modules/ws/lib/receiver.js:~72] [pc=0xa4e56aa65](this=0x0e2f5ad5e521 \u003cWritable map = 0x15f3cd86e929\u003e,0x2611ae48b5c9 \u003cUint8Array map = 0x2b188a5252d9\u003e,0x0b72a0503...

 1: 0xa07f90 node::Abort() [node]
 2: 0xa0839c node::OnFatalError(char const*, char const*) [node]
 3: 0xb80d9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb81119 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd2d875  [node]
 6: 0xd2df06 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd3a785 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd3b635 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd3e0ec v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd0c62d v8::internal::Factory::NewRawTwoByteString(int, v8::internal::AllocationType) [node]
11: 0xd0c71c v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector\u003cchar const\u003e const\u0026, v8::internal::AllocationType) [node]
12: 0xb990ff v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [node]
13: 0xadef50 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local\u003cv8::Value\u003e*) [node]
14: 0x9e25a6  [node]
15: 0x1351acd  [node]
```

**Comment by addaleax** [comment]
It sounds like you have a memory leak in your application, hence the “JavaScript heap out of memory” part. It’s hard to diagnose what that memory leak is exactly without more information.

Does the memory leak always occur with the same JS stack trace (in `node_modules/ws/lib/receiver.js`)? Are you able to take a heap snapshot (run Node.js with `node --inspect application.js`, then connect Chrome DevTools to the application and take a heap snapshot in the “Memory” tab)?

**Comment by powerflips** [comment]
`\u003c--- Last few GCs ---\u003e

[1:0x3505350] 14344215 ms: Scavenge 219.3 (256.3) -\u003e 218.6 (256.3) MB, 2.2 / 0.1 ms  (average mu = 0.307, current mu = 0.383) allocation failure 
[1:0x3505350] 14344691 ms: Scavenge 219.6 (256.3) -\u003e 218.9 (256.3) MB, 3.3 / 0.3 ms  (average mu = 0.307, current mu = 0.383) allocation failure 
[1:0x3505350] 14345154 ms: Scavenge 219.9 (256.3) -\u003e 219.2 (256.8) MB, 3.0 / 0.2 ms  (average mu = 0.307, current mu = 0.383) allocation failure 


\u003c--- JS stacktrace ---\u003e

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13cb519]
Security context: 0x1d5e051c08d1 \u003cJSObject\u003e
    1: assign [0x1d5e051c11f9](this=0x1d5e051c0969 \u003cJSFunction Object (sfi = 0x13361418a1b9)\u003e,0x0cd418a8aea1 \u003cObject map = 0x37b910b74d29\u003e,0x30626c55ca39 \u003cObject map = 0x37b910b74cd9\u003e)
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
    2: handle [0x113bcd25fd11] [/home/node/node_modules/discord.js/src/client/actions/PresenceUpdate.js:~7] [pc=0x2bff68ffab77](this=0x0e9c507669b9 \u003cGenericAction map = 0x1a56e1c9d...

 1: 0xa07f90 node::Abort() [node]
 2: 0xa0839c node::OnFatalError(char const*, char const*) [node]
 3: 0xb80d9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb81119 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd2d875  [node]
 6: 0xd2df06 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd3a785 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd3b635 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd3e0ec v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd0502d v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::RootIndex, int, v8::internal::Object, v8::internal::AllocationType) [node]
11: 0xd05120 v8::internal::Handle\u003cv8::internal::FixedArray\u003e v8::internal::Factory::NewFixedArrayWithMap\u003cv8::internal::FixedArray\u003e(v8::internal::RootIndex, int, v8::internal::AllocationType) [node]
12: 0xf3049d v8::internal::OrderedHashSet::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [node]
13: 0xeeca9f v8::internal::KeyAccumulator::AddKey(v8::internal::Object, v8::internal::AddKeyConversion) [node]
14: 0xf2d7d2 v8::internal::BaseNameDictionary\u003cv8::internal::NameDictionary, v8::internal::NameDictionaryShape\u003e::CollectKeysTo(v8::internal::Handle\u003cv8::internal::NameDictionary\u003e, v8::internal::KeyAccumulator*) [node]
15: 0xeed76d v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle\u003cv8::internal::JSReceiver\u003e, v8::internal::Handle\u003cv8::internal::JSObject\u003e) [node]
16: 0xeee17e v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle\u003cv8::internal::JSReceiver\u003e, v8::internal::Handle\u003cv8::internal::JSObject\u003e) [node]
17: 0xeeed7e v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle\u003cv8::internal::JSReceiver\u003e, v8::internal::Handle\u003cv8::internal::JSReceiver\u003e) [node]
18: 0xeef098 v8::internal::KeyAccumulator::GetKeys(v8::internal::Handle\u003cv8::internal::JSReceiver\u003e, v8::internal::KeyCollectionMode, v8::internal::PropertyFilter, v8::internal::GetKeysConversion, bool, bool) [node]
19: 0xeda9a7 v8::internal::JSReceiver::SetOrCopyDataProperties(v8::internal::Isolate*, v8::internal::Handle\u003cv8::internal::JSReceiver\u003e, v8::internal::Handle\u003cv8::internal::Object\u003e, v8::internal::ScopedVector\u003cv8::internal::Handle\u003cv8::internal::Object\u003e \u003e const*, bool) [node]
20: 0x105fc23 v8::internal::Runtime_SetDataProperties(int, unsigned long*, v8::internal::Isolate*) [node]
21: 0x13cb519  [node]`

**Comment by markskayff** [comment]
I'm having the same issue with a "webpacker-dev-server". I'm getting a **javscript heap out of memory**, even though I'm trying to control it via --max-old-space-size=4096

Here attached is the V8 report.

I'm using Node v12.16.3 in Ubuntu 20.04.

[report.20200916.004834.7828.0.001.txt](https://github.com/nodejs/help/files/5234426/report.20200916.004834.7828.0.001.txt)

**Comment by abdulmajidkazi** [comment]
> It sounds like you have a memory leak in your application, hence the “JavaScript heap out of memory” part. It’s hard to diagnose what that memory leak is exactly without more information.
> 
> Does the memory leak always occur with the same JS stack trace (in `node_modules/ws/lib/receiver.js`)? Are you able to take a heap snapshot (run Node.js with `node --inspect application.js`, then connect Chrome DevTools to the application and take a heap snapshot in the “Memory” tab)?

I am getting similar error while building my application. Allocating more memory does not help..
