### ISSUE TITLE
internal/modules/cjs/loader.js:985   throw err;   ^

### ISSUE THREAD

**Issue by mraees93** [nodejs/help#2822]
* **Node.js Version 12.16.1**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by PoojaDurgad** [comment]
@mraees93 - can you elaborate your issue more please? what command you are trying to run? which os you are using?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
