### ISSUE TITLE
Can we update registry value in package.json publishconfig section at runtime using npm

### ISSUE THREAD

**Issue by khanaman22** [nodejs/help#2825]
Hi
I am new to node so need below help and suggestion
I have a pipeline in Jenkins which is publishing latest artifact using npm publish to private nexus location eg :app-test folder from where the latest is picked.
Jenkins does below on every master push: update minor version,push to master,create tag and publish in nexus under npm folder app-test and deploy on test environment (uses package.json publishconfig registry to publish)
At the time of code cut i need to publish the release version inside nexus app-release folder instead of app-test from where qa and prod can be deployed.
Is there a way to update package.json publish config registry value automatically at runtime using npm command. The version command updates version in json but cannot see option to update registry value in publishconfig.
Please suggest.
Thanks
Aman

**Comment by addaleax** [comment]
@khanaman22 It’s not really clear whether this is what you are asking for, but you can use the `npm_config_registry` environment variable or the `--registry=...` CLI flag for npm to set the value explicitly.

**Comment by khanaman22** [comment]
@addaleax 
Thanks for quick reply.
I want to use different registry location then one mentioned in package.json so if i set npm_config_registry env variable or use --registry flag in my pipeline job will npm publish command pick registry defined in npm_config_registry instead of package.json?

**Comment by addaleax** [comment]
@khanaman22 I don’t know. You might have to try it out.

**Comment by PoojaDurgad** [comment]
@khanaman22 - is this issue resolved?
