### ISSUE TITLE
Support for DNS Update packets & TSIG etc.

### ISSUE THREAD

**Issue by michaelrommel** [nodejs/help#2828]
Hello,

I was scouting the Internet high & low to find a module that allows me to create TSIG signed DNS update packets or AXFR Requests etc. The current module supports mainly DNS resolution.

* **Node.js Version**: 14.x
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: DNS

Are there any plans to enhance the core DNS module with this functionality or can anyone recommend another 3rd party module, which implements the above mentioned function?

Thank you all!

  Michael.

**Comment by gireeshpunathil** [comment]
@nodejs/dns

**Comment by michaelrommel** [comment]
I solved my issues without using node.
