### ISSUE TITLE
Why are event handlers not fired on nextTick?

### ISSUE THREAD

**Issue by dreamsinspace** [nodejs/help#2830]
* **Node.js Version**: 12.16.1
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: `events`

I was expecting event handlers to be executed after other synchronous code, but it turned out to be wrong:
```js
const EventEmitter = require('events');

const ev = new EventEmitter();

ev.on('test', () => {
  console.log('1');
});

ev.emit('test');

console.log('2'); // Outputs '1 2' instead of '2 1'
```

It would be nice for someone to explain why events are treated just like any other synchronous code. It would make more sense for me to fire them on nextTick, like callbacks and stuff...

Thanks a lot for your time.

-->

**Comment by devsnek** [comment]
@dreamsinspace events don't impose scheduling. you can emit them from your own nextTick, your own queueMicrotask, synchronously, etc.

**Comment by dreamsinspace** [comment]
@devsnek I'm modifying an object both inside and outside of the event (these 2 modifications are not related to each other). Should I just clone the object inside the event instead of directly mutating it, because I'm not sure when the event fires and it might end up messing with other sections outside of the handler...
