### ISSUE TITLE
Is there a way to programmatically add import paths for ECMAScript Modules without using experimental loaders?

### ISSUE THREAD

**Issue by kirkouimet** [nodejs/help#2831]
* **Node.js Version**: 14

Back in the day we could mess around with possible import paths by modifying the `module._resolveFileName` function. With the new `import` statement from ECMAScript Modules in Node 14 this method no longer works. It looks like the API for specifying manual import paths is coming via a command line argument, e.g. `-loader=myloader.js`. I'd like to be able to add a custom path for `import` calls to look into without specifying it with the command line argument and instead setting these import paths dynamically with code. Is there some underlying function the new `import` statement is using that I can modify in order to add additional or custom module lookup paths?

Reference:
https://www.npmjs.com/package/module-alias

**Comment by devsnek** [comment]
This functionality is currently not available, and probably won't be available in the form that you're asking for. I have been thinking of exploring ways of loading loaders at runtime, so if anything comes of that you'd still have to write a loader.

**Comment by kirkouimet** [comment]
I'd be up for putting in the work to create a solution allowing users to add custom import paths after their node app has started running. I'm guessing this would need to align with whoever ultimately approves code changes to the node repo. What's the best way for me to propose this functionality?

Thanks!

**Comment by kirkouimet** [comment]
Nice, setting a new loader at runtime that would solve everything for me. Anything I can do to help?

It seems like the new system is resistant to monkey-patching like we were previously doin with Module._resolveFileName. So perhaps exposing some type of function on `process` or `module` or whichever node object owns `ESMLoader` would be the path forward. Maybe something like:

MyLoader.js:
```
export async function resolve(specifier, context, defaultResolve) {
  return defaultResolve(specifier, context, defaultResolve);
}
```

Main.js
```
import module from 'module';
import MyLoader from 'MyLoader.js'
module.setLoader(MyLoader);
```
Thoughts?

Reference:

https://github.com/nodejs/node/blob/master/lib/internal/process/esm_loader.js#L37

**Comment by marcuspoehls** [comment]
Hey, I found this issue while searching for a way to manually/programmatically add ESM loader hooks.

Would be nice to have a way in the Node core supporting this functionality. I guess it can be done somehow because it's supported using `node` on the CLI with a flag.
