### ISSUE TITLE
internal/modules/cjs/loader.js:969 

### ISSUE THREAD

**Issue by smitad30** [nodejs/help#2834]
* **Node.js Version**: v12.18.2
* **OS**: windows 64-bit
* **Scope**: runtime

I am working on Jsontron module.Everytime I restart my laptop and then try to run my commands through cmd, i get the following error.

_internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\jsontron\node_modules\jsontron\examples\jsontronpo
c\%JSONTRON_HOME%\bin\JSONValidator.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}_

Then after reinstalling the jsontron module 2 3 times it works fine, but everytime after restarting the laptop,same issue persists.

**Comment by StEvUgnIn** [comment]
Same problem here

**Comment by manenigma** [comment]
Same problem here

**Comment by chrisdunne** [comment]
Same problem here

**Comment by PoojaDurgad** [comment]
@StEvUgnIn and @smitad30 - is this still an issue ? IDK exactly what might be the reason but can you try updating npm and see what it throws? and for more details you can refer this I guess https://github.com/amer-ali/jsontron

**Comment by StEvUgnIn** [comment]
I presume I had this problem on `next.js` with a repository with dot inside the name : `meishicorp.github.io`

**Comment by PoojaDurgad** [comment]
closing as inactive issue
