### ISSUE TITLE
Giving incorrect output while manipulating large number input

### ISSUE THREAD

**Issue by touchnewshiva** [nodejs/help#2838]
* **Version**:12.8.1
* **Platform**:Windows 10 Pro 64-bit
* **Subsystem**:

### What steps will reproduce the bug?

       var aa = 125029734092369566;
       var bb = 2;
       var sum = aa + bb;
       console.log(sum);

### How often does it reproduce? Is there a required condition?
This issue started from 18th digit onwards.

### What is the expected behavior?
125029734092369568 or Crossed the input size limit

   125029734092369570

### What do you see instead?

125029734092369570 

### Additional information

It would be nice If JavaScript handles this.
![JS Bug](https://user-images.githubusercontent.com/65024196/87174657-2151b380-c2f5-11ea-91e2-6360c3b4b658.png)

**Comment by addaleax** [comment]
JS uses floating-point numbers as its default number type, which means that large numbers will not be represented exactly. The documentation on [`Number.isSafeInteger`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger) has a few more details.

Recent versions of Node.js, including v12.x, support `BigInt`s, i.e. arbitrary-precision integers:

```js
> 125029734092369566n + 2n
125029734092369568n
> Number(125029734092369568n)
125029734092369570 // Imprecise, because converted to Number instead of BigInt
```

**Comment by touchnewshiva** [comment]
> JS uses floating-point numbers as its default number type, which means that large numbers will not be represented exactly. The documentation on [`Number.isSafeInteger`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger) has a few more details.
> 
> Recent versions of Node.js, including v12.x, support `BigInt`s, i.e. arbitrary-precision integers:
> 
> ```js
> > 125029734092369566n + 2n
> 125029734092369568n
> > Number(125029734092369568n)
> 125029734092369570 // Imprecise, because converted to Number instead of BigInt
> ```

Thanks for the suggestion addaleax. with your modification its working. But it'll be awesome if Node throws warning or exception instead of incorrect answer.

**Comment by PoojaDurgad** [comment]
I'm wandering about next steps here, given that type-definitions are part of v8 , there is no role of node.js here (node.js can handle and control it's own API calls.)

**Comment by PoojaDurgad** [comment]
@touchnewshiva - anything pending on this issue?

**Comment by touchnewshiva** [comment]
It would be good if we add some auto comments or pop ups to notify that,
it's not possible
