### ISSUE TITLE
Node JS Test Coverage

### ISSUE THREAD

**Issue by hyndav** [nodejs/help#284]
Hi 
Can someone please recommend few Node Js unit testing and code coverage tools ?

**Comment by danielkhan** [comment]
I use [Mocha](https://mochajs.org/) as test runner and [should](https://github.com/tj/should.js/) as  assertion library. For coverage most use [istanbul](https://github.com/gotwarlost/istanbul) I'd say.

**Comment by addaleax** [comment]
Some people also swear on [node-tap](https://github.com/tapjs/node-tap), although I personally prefer mocha, too. [nyc](https://github.com/istanbuljs/nyc) is becoming the official CLI for istanbul and has nice features like support for subprocesses, so I’d recommend that (full disclosure: I’m on the nyc team. :smile:).

**Comment by lordKnighton** [comment]
@hyndav Please close issue, if you're happy with these answers :)
