### ISSUE TITLE
Node is not removed from the machine

### ISSUE THREAD

**Issue by lineuxyz** [nodejs/help#2840]
* **Node.js Version**: 13.0.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**: 

I can't uninstall the node, I have already followed all kinds of tutorials, I have done all kinds of processes, there is no more node folder on my machine and even then it appears in my task manager. When I try to see the version it says it doesn't recognize the command, but when I try to install it again it says it already exists. I need to use the machine and I can't because of this problem

**Comment by ScSofts** [comment]
you can delete it and remove it from registry

**Comment by lineuxyz** [comment]
I managed to solve the problem, I uninstalled and installed using the standard installer, it was not possible via package manager, but the dependencies are being installed normally
