### ISSUE TITLE
Node.js and npm download not matching

### ISSUE THREAD

**Issue by ts346** [nodejs/help#2842]
On the website, it says for the latest version of node (14.5.0), npm version 6.14.5 will be included. But, when checking on my command prompt, I only have npm versoin 5.6.0. It is not compatible with this new version and thus I am experiencing difficulties 

* **Version**:
* **Platform**:
* **Subsystem**:

### What steps will reproduce the bug?
npm start

### How often does it reproduce? Is there a required condition?
It is always there, I am unable to use the npm start. 
### What is the expected behavior?
Opens up the react app on a local host

### What do you see instead?
npm WARN npm npm does not support Node.js v14.5.0 npm WARN npm You should probably upgrade to a newer version of node as we npm WARN npm can't make any promises that npm will work with this version. npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9. npm WARN npm You can find the latest version at https://nodejs.org/ 
above is when I do npm install

ELIFECYCLE 
this pops up as an error when I use npm start (along with other errors)

**Comment by PoojaDurgad** [comment]
@ts346 - make sure you don't have any previous installed version of node on your system. if that is the case try to completely delete the node and npm and do `npm install -g npm@latest` . hope it helps

**Comment by PoojaDurgad** [comment]
inactive. closing !! please feel free to re-open the issue if its still outstanding
