### ISSUE TITLE
Failed: 403 == '201' in Chakram module

### ISSUE THREAD

**Issue by MinarvaTR** [nodejs/help#2844]
Node Versions : 8.x.x/10.x.x/12.x.x
OS: Windows
Module(version) : Chakram (v 1.5)

While executing script with Chakram module ,getting 403 everytime in GET call even if Chakram module is there in package.json .
 After re-installing 'npm install chakram' the issue is getting reolved.

Why is being it's required to again install Chakram separately to get rid off 403 errors ?
NOTE : Before 2 months this problem was not coming up and the scripts were running in one go after 'npm install'.

**Comment by gireeshpunathil** [comment]
@MinarvaTR - is this still an issue? do you have a program to recreate?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
