### ISSUE TITLE
QUIC for Node.js client implementation

### ISSUE THREAD

**Issue by Geshode** [nodejs/help#2846]
* **Node.js Version**: 14.5.0
* **OS**: Windows 10

I have been following the QUIC implementation process and was giving it a try now that it got added to the node master.

I also got an example to work, after realizing, that QUIC is now included inside the net module and not the quic module anymore.

All samples, which I have found ([one example](https://www.nearform.com/blog/a-quic-update-for-node-js/)), talk about using the QUIC implementation in Node being usable for server and client. I have been able to successfully create a server and client in my application's index.js, but I have no idea how I am supposed to make the QUIC implementation usable in the web browser. Because when I hear client, I think of web browsers.

Is there a way to use the QUIC implementation in a web browser? Or is it wrong to understand client as web browser?

@jasnell

**Comment by gireeshpunathil** [comment]
@nodejs/quic
