### ISSUE TITLE
while installing angular . this is the error. how to resolve it

### ISSUE THREAD

**Issue by amansingh3368** [nodejs/help#2847]
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://registry.npmjs.org/@angular%2fcli failed, reason: connect ETIMEDOUT 93.184.216.34:8080
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-07-15T12_24_32_775Z-debug.log

while installing angular . this is displaying. how to resolve it?

**Comment by PoojaDurgad** [comment]
@amansingh3368 - 
> npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

looks like you have some problems with your global proxy setting. set the proxy and make sure you have descent network connection. refer this https://github.com/npm/npm/issues/17947  it may help

**Comment by PoojaDurgad** [comment]
closing as answered . please feel free to reopen the issue if its still an issue

**Comment by iamsanjeet** [comment]
in my case, it was because of VPN. Disconnected VPN and then it worked.

**Comment by lordmartin26** [comment]
npm config rm proxy
npm config rm https-proxy

npm config set proxy http://username:password@host:port
npm config set https-proxy http://username:password@host:port

npm config set registry https://registry.npmjs.org/

**Comment by Akshay-halge** [comment]
ok

**Comment by Akshay-halge** [comment]
ok
