### ISSUE TITLE
nodejs installation error

### ISSUE THREAD

**Issue by briana214** [nodejs/help#2850]
After I installed the node js package on my mac, whenever I go to the terminal to verify the download it says "command not found" what can I do to solve this? 

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by PoojaDurgad** [comment]
@briana214 - personally I have not used mac but what command you are trying to run? for me by looking at your error seems like this is much similar to these links https://github.com/npm/npm/issues/3125, https://github.com/preactjs/preact-cli/issues/487 not sure , hope it may help.

**Comment by PoojaDurgad** [comment]
inactive! closing . please feel free to re-open the issue if its still outstanding
