### ISSUE TITLE
Reccomend a good way to create a simple nodejs server project quickly

### ISSUE THREAD

**Issue by ItamarSmirra** [nodejs/help#2852]
Express generator creates a big nodejs server project with some unnecessary files, libraries and code.
It will be very nice if you (Nodejs owners) recommend a more basic package to initialize simple nodejs server template to give us developers an easy start. I personally using the [create-nodejs ](https://www.npmjs.com/package/create-nodejs)  package on npm because it is really simple and creates only the basic requirements for standard nodejs server. I really appreciate if you just have it in mind. Thank you.

**Comment by gireeshpunathil** [comment]
/cc @bnb who is building a nodejs example documentation - does it make sense to maintain a most common nodejs server code, for easy download and re-use?

https://github.com/nodejs/examples

@ItamarSmirra - are you willing to contribute one, if we go for it?

**Comment by ItamarSmirra** [comment]
Yea sure, i will be honored

**Comment by bnb** [comment]
My understanding is that we don't currently recommend Express anywhere (outside of Examples!) and typically have avoided doing so with some intent. Is there a place where we do suggest Express explicitly?

**Comment by ItamarSmirra** [comment]
I didnt find the exact words - "we offer you to use Express for nodejs servers" (and i can understand why 😅) but you mention it [here](https://nodejs.dev/learn) among with other modules that most of them is based on Express.
Maybe it is right for you not to reccomend a specific module after all, but still as nodejs developer i was looking a simple and cleen way forquick start of nodejs application (like express-generator but much smaller) and didn't any.
What about @gireeshpunathil most common nodejs server code idea?
