### ISSUE TITLE
node.js and socket.io

### ISSUE THREAD

**Issue by meysamzi** [nodejs/help#2858]
Hi dear programmers
i'm trying to access request object in node.js but since i'm using socket.io, i can't route so that i don' have access to req and res, i want to know how i can gain access to them without routing.
here is my code

[socket.io.txt](https://github.com/nodejs/help/files/4939155/socket.io.txt)

**Comment by gireeshpunathil** [comment]
@meysamzi - is this outstanding? IIUC, `socket.io` is implemented on top of `websocket` protocol, and the request and response objects that you mention are artifacts of HTTP protocol, so those are not available to use in the `socket.io` based networking. Further queries can be clarified at  https://github.com/socketio/socket.io

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
