### ISSUE TITLE
How to hot update the certificate and private key of the HTTPS server without restarting the server?The old ssl/tls certificate should be deleted.

### ISSUE THREAD

**Issue by masx200** [nodejs/help#2859]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

How to hot update the certificate and private key of the HTTPS server without restarting the server?

For example, whenever the ssl/tls certificate expires soon, how to replace the hostname certificate specified by the HTTPS server with the correct new one?

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by bnoordhuis** [comment]
Look up `server.addContext()` in the tls docs, that's probably what you want to use.

**Comment by masx200** [comment]
https://github.com/nodejs/node/blob/2e6c3e2301cb443a72c3659fffa24815b4660815/lib/_tls_wrap.js#L1439


https://github.com/nodejs/node/blob/2e6c3e2301cb443a72c3659fffa24815b4660815/lib/_tls_wrap.js#L1420


After reading the source code, I found that when adding multiple ssl/tls certificates to the same domain name, the ones added later will not take effect, only the first one that meets the conditions will take effect.  If the ssl/tls certificate expires, you need to replace the old one with a new one. Using "addcontext" will not solve the problem because the old one will still be used.

**Comment by masx200** [comment]
@bnoordhuis

**Comment by bnoordhuis** [comment]
If "update" means "replace", the answer is "you can't for technical reasons" - there's no good way to tell when it's safe to stop using the old key+cert because of existing clients and sessions. See https://github.com/nodejs/node/issues/15115#issuecomment-326257131 for an SNI-based solution and https://github.com/nodejs/node/issues/15115#issuecomment-607728397 for why that won't always work.

There are a bunch of workarounds but they all boil down to doing rolling restarts.

**Comment by TDurrr1** [comment]
This is the code I'm currently using. When the HTTPS key and/or certificate are overwritten while the server is running, this code will update them for the server without needing a reboot and [without interrupting current connections](https://nodejs.org/api/tls.html#tls_server_setsecurecontext_options):

```js
let timeout;
fs.watch(certFolder, (event, filename) => {
   clearTimeout(timeout);
   timeout = setTimeout(() => {
      httpsServer.setSecureContext({
         key  : fs.readFileSync(keyPath).toString(),
         cert : fs.readFileSync(certPath).toString()
      });
      console.log('Secure context updated.');
   }, 5000);
});
```

`certFolder` is the directory where the key and certificate file are stored; `keyPath` and `certPath` are the paths to your key and certificate, respectively; and `httpsServer` is the server Node gives you when you call `http.createSecureServer(options, handler)`.

The reason the call to `setSecureContext` is surrounded by timeout stuff is to debounce it, or keep it from being called too frequently. This prevents an issue where the key is overwritten and before your certificate finishes copying the secure context gets updated with the non-matching key-cert pair.

**Comment by masx200** [comment]
But for the case of using snicallback to select the certificate, this will not work properly.  Because for the same domain name, snicallback will only be called once

**Comment by masx200** [comment]
@TDurrr1

**Comment by masx200** [comment]
https://github.com/nodejs/node/pull/34444
