### ISSUE TITLE
process.on('exit') equivalent within C++ addons

### ISSUE THREAD

**Issue by JoshuaWise** [nodejs/help#286]
I'm wondering if there's a way to register (and unregister?) a C++ callback within a node addon for when the process is about to exit. Something equivalent to `process.on('exit', fn)` but for C++ functions.

**Comment by bnoordhuis** [comment]
`node::AtExit()`

**Comment by JoshuaWise** [comment]
beautiful, thank you

**Comment by JoshuaWise** [comment]
oh wait, I forgot to ask, is there a way to remove a callback added by `node::AtExit()`?

**Comment by bnoordhuis** [comment]
No.  You'd have to track that yourself.

**Comment by JoshuaWise** [comment]
Okay, thanks
