### ISSUE TITLE
Unexpected "Error: ENOENT: no such file or directory" while successfully deleting file with fs.unlink.

### ISSUE THREAD

**Issue by NickEmpetvee** [nodejs/help#2861]
* **Version**: 14.5.0
* **Platform**: Windows
* **Subsystem**:

Weird error... I'm sending the following delete call from Axios in React to my Node / Express file attachment utility in order to delete an uploaded file on disk. The deletion works fine. However after about a minute the node server throws the error: `[Error: ENOENT: no such file or directory, unlink '<PATH>`. It looks like it's making another pass at finding the file it just deleted which is obviously now gone. Any idea why this is and how to resolve?

_**REACT CODE:**_

`await API.delete("http://localhost:8001/eraser/" + targetAttachmentToDelete.stored_file_name)`

**_NODE SERVER CODE:_**

```
var cors = require('cors');
var express = require('express');
const fs = require('fs')
var multer = require('multer')

var app = express();
app.use(cors());

...

app.delete('/eraser/:file_to_delete', async (req, res) =>
{
    const path = 'assets/uploads/' + req.params.file_to_delete;

    //var file_to_delete = req.params.file_to_delete;

    console.log(path);

    try
    {
        await unlink(path);
        // NOTE: `unlinkSync(path) yields the same behavior

        console.log('File deleted!');

        return res.status(200);
    }
    catch(err)
    {
        console.error(err)
        return res.status(500).json(err)
    }
});
```

**Comment by gireeshpunathil** [comment]
@NickEmpetvee - is this outstanding? do you have the complete call stack of the error?

**Comment by NickEmpetvee** [comment]
@gireeshpunathil Thanks, I took a different approach by using a binary data store to house binary files. What you see above was abandoned. I don't unfortunately have a stack trace.
