### ISSUE TITLE
crypto module reference error

### ISSUE THREAD

**Issue by rashidvali** [nodejs/help#2863]
* **Node.js Version**: 12.18.2
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: crypto

I get the following:

external "crypto":1 Uncaught ReferenceError: require is not defined
at Object.crypto (external "crypto":1)
at webpack_require (bootstrap:19)
at Object../src/Lib/Util.ts (Util.ts:1)
at webpack_require (bootstrap:19)
at Object../src/init.ts (init.ts:1)
at webpack_require (bootstrap:19)
at bootstrap:83
at bootstrap:83

My code:

import * as crypto from 'crypto'
...
let hx = crypto.randomBytes(Math.ceil(1));

In my package.js:

  "devDependencies": {
    "@types/lodash": "^4.14.107",
    "@types/uuid": "^8.0.0",
    "ts-loader": "^8.0.1",
    "typescript": "^3.9.7",
    "typings-for-css-modules-loader": "^1.7.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "@types/node": "^14.0.23",
    "css-loader": "^1.0.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "uuid": "^8.2.0"
  }

This is plain TypeScript/Webpack project

**Comment by gireeshpunathil** [comment]
@rashidvali - is this outstanding?  as per https://nodejs.org/api/esm.html#esm_enabling , you can tell Node.js to treat a JavaScript code as ECMAScript modules via the .mjs file extension, the package.json "type" field, or the --input-type flag. See [Modules: Packages](https://nodejs.org/api/packages.html#packages_determining_module_system) for more details.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
