### ISSUE TITLE
Help needed on tls.createSecureContext with minVersion and maxversion

### ISSUE THREAD

**Issue by llecocq** [nodejs/help#2865]
* **Node.js Version**: v14.5.0
* **OS**: Centos 7.7
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

Hi,
I need some help understanding how min and max version work for TLS connections
I create an HTTP/2 client and an HTTP/2 server as below, with minVersion set to TLSv1.3 for the client, and maxVersion set to TLSv1.2 for the server.
I was expecting the server will reject the connection, but it does not, question is why ?
Thanks for explaining.
Client:
```js
   Https_Options['secureContext']=tls.createSecureContext({'minVersion':'TLSv1.3'});
    client = http2.connect(Client_To_Use[URL_idx], Https_Options);
```
Server:
```js
   server = http2.createSecureServer({
                key: fs.readFileSync(Server_Key_File),
                cert: fs.readFileSync(Server_Cert_File),
                ca: fs.readFileSync(Server_CA_File),
                secureContext: tls.createSecureContext({'maxVersion':'TLSv1.2'})
            });
            server.listen(port,"0.0.0.0");
```
-->

**Comment by preveen-stack** [comment]
cc @nodejs/crypto 

>  with minVersion set to TLSv1.3 for the client, and maxVersion set to TLSv1.2 for the server.
I was expecting the server will reject the connection, but it does not, question is why ?

**Comment by mcollina** [comment]
I have actually no clue. Maybe @nodejs/crypto.

**Comment by tniessen** [comment]
@llecocq While I realize that this issue is several years old, I still want to provide an answer.

`createSecureServer()` does not have a `secureContext` option. If you set the `maxVersion` option directly, it will work, i.e., `createSecureServer({ ..., maxVersion: 'TLSv1.2' })`.
