### ISSUE TITLE
How to cross compile node.js with snapshot?

### ISSUE THREAD

**Issue by qnxqnxqnx** [nodejs/help#2866]
Hi All,

I'm trying to build node.js with a snapshot on linux *x86_64* for linux *arm64*.
I can't manage to build it. What is the correct way to do it?

These are the options with which I start configure:

```./configure --shared-zlib --shared-openssl --without-npm --with-intl=system-icu --with-snapshot --dest-cpu=arm64 --cross-compiling --dest-os=linux```

Then I start the build:
```make -j4```

It fails with this error:

*"/node-v8.16.2/out/Release/mksnapshot" --startup_src "/node-v8.16.2/out/Release/obj.host/v8_snapshot/geni/snapshot.cc" ""*
*/bin/sh: 1: /node-v8.16.2/out/Release/mksnapshot:* ***Exec format error***
*make[1]: *** [deps/v8/src/v8_snapshot.host.mk:13: /node-v8.16.2/out/Release/obj.host/v8_snapshot/geni/snapshot.cc] Error 2*

It seems that the build process creates the binary *mksnapshot* that is used then for building the snapshot part of node.js. The binary *mksnapshot* is built for *arm64*, but it's started during the build under *x86_64*, which leads to *"Exec format error"*.
It seems that in spite of the configure options ```"--dest-cpu=arm64 --cross-compiling"``` the build process does not know that the utility *mksnapshot* has to be built for *x86_64*.

So, I've tried first to build node.js for my native environment, that is for *x86_64*. Then I've started the build for *arm64* as described above, but with one hack:
in file ```out/deps/v8/src/v8_snapshot.target.mk``` I've replaced all occurrences of ```"$(builddir)/mksnapshot"``` with the path to my *mksnapshot* that I've built for *x86_64*.

This worked very well. The build was successful. The problem is that the node crashes on target straight after the start with this error: 

*Fatal error in ../deps/v8/src/snapshot/deserializer.cc, line 665*
*Check failed: limit == current.*
*Trace/breakpoint trap (core dumped)*

Then I've tried another approach. I've looked at what exactly the binary *mksnapshot* does. It generates the file *snapshot.cc* that is used further in the build process. I've taken *mksnapshot* built for *arm64* and started it on my *arm64* target and generated the *snapshot.cc* file with this command taken from *v8_snapshot.target.mk*:

```mksnapshot --startup_src snapshot.cc ""```

This file *snapshot.cc* generated on my *arm64* target I've copied then in my *x86_64* environment and used it further in the build. The build was successful, but the problem was again that the node crashes on target:

*Program terminated with signal SIGSEGV, Segmentation fault.
#0  v8::base::Relaxed_Load (ptr=0x0) 
        at ../deps/v8/src/base/atomicops_internals_portable.h:168*

So, I'm now stuck with this problem and I'll be very thankful for any suggestions and tips!

Kind Regards,
Aleksej.

**Comment by kmaincent** [comment]
Hello, 
I am tackling the same issue. Did you manage to solve it?
Regard,
Köry

**Comment by gireeshpunathil** [comment]
@qnxqnxqnx -  is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
