### ISSUE TITLE
SyntaxError: Unexpected token { while 

### ISSUE THREAD

**Issue by nabodhe** [nodejs/help#2867]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by PoojaDurgad** [comment]
@nabodhe - can you please elaborate your issue more? which os and node version you are using? what you are trying to run?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
