### ISSUE TITLE
"SyntaxError: Unexpected token { " occurred while exporting & importing class

### ISSUE THREAD

**Issue by nabodhe** [nodejs/help#2868]
* **Node.js Version**: 10.15.1
* **OS**: MacOs (10.15.6)
* **Scope (install, code, runtime, meta, other?)**: error while running Node Js program
* **Module (and version) (if relevant)**: 

Stack trace is as below: 

Then I try to import that class using ES2015 syntax. 
"import { HelloWorld } from "./helloWorld";"
I am getting below error.

Documents/NodeDemo/src/index.js

Debugger listening on ws://127.0.0.1:52106/c682bf69-5b4d-4071-8576-129aeffc81c3

For help, see: https://nodejs.org/en/docs/inspector

Debugger attached.

Documents/NodeDemo/src/index.js:1

(function (exports, require, module, __filename, __dirname) { import { HelloWorld } from "./helloWorld";
^
SyntaxError: Unexpected token {
at new Script (vm.js:79:7)
at createScript (vm.js:251:10)
at Object.runInThisContext (vm.js:303:10)
at Module._compile (internal/modules/cjs/loader.js:657:28)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
at startup (internal/bootstrap/node.js:283:19)
Debugger listening on ws://127.0.0.1:52106/c682bf69-5b4d-4071-8576-129aeffc81c3

For help, see: https://nodejs.org/en/docs/inspector
Process exited with code null

**Comment by gireeshpunathil** [comment]
@nabodhe - is this outstanding? as per https://nodejs.org/api/esm.html#esm_enabling , you can tell Node.js to treat a JavaScript code as ECMAScript modules via the .mjs file extension, the package.json "type" field, or the --input-type flag. See [Modules: Packages](https://nodejs.org/api/packages.html#packages_determining_module_system) for more details.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
