### ISSUE TITLE
When the push method returns false, the event on ('data ') still reads data

### ISSUE THREAD

**Issue by mmm8955405** [nodejs/help#2869]
In the latest stable version of nodejs, windows 10 environment
A simple implementation of stream duplex stream.
When the push method returns false, the event on ('data ') still reads data

```js
const myDuplex = new Duplex({

read(size) {

// ...

}

write(chunk, encoding, callback) {

// ...

}

};



for(var i=0; i<1000; i++){

console.log (myDuplex .push("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));



}



var j = 0;

myDuplex .on('data', (chunk) => {

console.log ('stream on data', chunk.length , j++);

}
```

Myduplex. Push has returned false when I > 174
But myduplex. On ('data ') still receives 1000 outputs

**Comment by addaleax** [comment]
The return value of `.push()` is only advisory – it tells the data source to stop pushing more data, but if it ignores that, then it will still store the data (and not silently discard it).

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
