### ISSUE TITLE
NPM install failed ENOENT

### ISSUE THREAD

**Issue by Simon686** [nodejs/help#2872]
* **Node.js Version**: 14.6.0
* **OS**:windows 10
* **Scope (install, code, runtime, meta, other?)**:install npm
* **Module (and version) (if relevant)**:

Hello, dear NPM team,

 I recently try to install the npm with the NodeJs, everything worked fine, 

node js version:v 14.6 0
npm version:: 6.14.7

on my windows 10 system.

when i tried to: npm install, it came like this:
image.png
Could you please help me to fixe this ?

[https://drive.google.com/file/d/1QNtXZpjHONMXWgbFyzhcJiOVAEZHwuDf/view?usp=sharing](url)
https://drive.google.com/file/d/1QNtXZpjHONMXWgbFyzhcJiOVAEZHwuDf/view?usp=sharing
thank you so much in advance!

**Comment by PoojaDurgad** [comment]
@Simon686 , The reason for the failure looks like it not finding the git command in your system if git is installed.If not please install the git and try again and see if it helps.

**Comment by PoojaDurgad** [comment]
inactive. closing!!
