### ISSUE TITLE
Installing npm Packge exact Version on windows

### ISSUE THREAD

**Issue by NaveenaTsLivearea** [nodejs/help#2873]
How can we install exact version of all npm packages as mentioned in package.json on windows machine

**Comment by PoojaDurgad** [comment]
@NaveenaTsLivearea , we can install the exact version of all npm packages as mentioned in package.json without specifying '~' and '^' before the version number.That means
- foo: ~1.0.0 indicates 1.0.0 or above
- foo: ^1.0.0 indicates 1.0.0 or below
- foo: 1.0.0 indicates exact version 

let me know if it makes sense to you

**Comment by PoojaDurgad** [comment]
Inactive. closing
