### ISSUE TITLE
Can Node.js's clustering feature leverage multiple CPUs? (referring to multi socket systems, not cores)

### ISSUE THREAD

**Issue by jt0dd** [nodejs/help#2875]
Let's say I buy a dual cpu motherboard that runs two 16 core cpus. Would this return 32?

```
const os = require('os')
const cpuCount = os.cpus().length // 32
```

And could I use Node.js Cluster to leverage all 32 cores, or would the extra CPU not be recognized / Node.js be unable to leverage a second processor?

**Comment by bnoordhuis** [comment]
> Would this return 32?

Yes, it should. If `/proc/cpuinfo` prints 32 cpus, then so will `os.cpus()`.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
