### ISSUE TITLE
npx Error on mkdir when making react app with "create-react-app" in Windows 10 

### ISSUE THREAD

**Issue by milindbajaj** [nodejs/help#2877]
Node.js Version: 14.5.0
OS: Windows 10

I installed yarn with "npm install -g yarn"

error An unexpected error occurred: "D:\\vscode\\react-app\\node_modules\\core-js: EINVAL: invalid argument, mkdir 'C:\\Users\\Dell\\AppData\\Local\\Yarn;C:\\Users\\Dell\\AppData\\Local\\Temp;\\yarn--1595656447620-0.14905958763107185

Any ideas on how to resolve?

**Comment by bmuenzenmeyer** [comment]
This question is idle and left unanswered for years now.

- Does the behavior persist if you upgrade to a new version of Node.js? This reported version is [within maintenance but newer versions exist](https://github.com/nodejs/release#release-schedule).
- Have you attempted to ask this question within other communities, such as [stackoverflow](https://stackoverflow.com/questions/tagged/node.js?tab=Newest) or [create-react-app](https://github.com/facebook/create-react-app/issues)

I am going to circle back in a couple weeks to see if we can close as no-longer relevant.

**Comment by bmuenzenmeyer** [comment]
closing per the above plan
