### ISSUE TITLE
node-sass doesn't work on 32 bit windows error message on 64 bit windows

### ISSUE THREAD

**Issue by ThiccoMode2** [nodejs/help#2878]
* **14.6.0**:
* **64 bit Windows 10 Home**:
* **issue running program**:
* **node-sass 4.14.1**:

I don't code in js, I installed BetterDiscord and tried to run it but I got the error that it doesn't support my current environment of Windows 32-bit, I can't find any help online and it seems no one's ever faced this issue before, I've spent hours just to be told node-sass doesn't run on 32-bit Windows, can anyone help?

**Comment by Dalrae1** [comment]
I have this same issue. I even reinstalled Discord and no fix. Pretty annoying being told that I am on 32 bit windows, even though I am not

**Comment by Jackaed** [comment]
This is also happening to me. No clue what the cause is, but still getting a node-sass error.

Have any of you found a fix?

**Comment by ThiccoMode2** [comment]
I haven't found a fix to that issue but what worked for me was installing
betterdiscord from the website instead of github and it just worked.
