### ISSUE TITLE
Discord Bot Issue

### ISSUE THREAD

**Issue by GOP14** [nodejs/help#2879]
HELP, mu program ain't working, its just saying ` identifier 'embed' has already been declared`

This is the coding:
bot.on('message', message=>{

    let args = message.content.substring(PREFIX.length).split(" ");

    switch(args[0]){
        case 'user':
            const embed = new Discord.MessageEmbed()
            .setTitle('User Information')
            .addField('Player Name', message.author.username)
            .addField('Version', version)
            .addField('Current Server', message.guild.name)
            .setColor(0xD195C4)
            .setThumbnail(message.author.displayAvatarURL())
            .setFooter('Join Discord.gg/5CPP6fR')
            message.channel.send(embed);
        break;
        case 'help':
            const embed = new Discord.MessageEmbed() 
            .setTitle("Helper Embed")
            .setColor(0xFF0000)
            .setDescription("Make sure to use the !help to get access to the commands")
            message.channel.send(embed);
        break;

**Comment by addaleax** [comment]
You probably want to turn 

```js
switch (...) {
  case 'user':
    const embed = ...;
    ...
  break;
  case 'help':
   const embed = ....;
   ...
  break;
}
```

into

```js
switch (...) {
  case 'user': {
    const embed = ...;
    ...
  break; }
  case 'help': {
   const embed = ....;
   ...
  break; }
}
```

because otherwise you end up having two `embed` variables in the same scope.

**Comment by marsonya** [comment]
@GOP14 - I believe this issue is properly addressed above. 

I am closing this issue now. Feel free to reopen it incase there is 
more to be discussed about this issue.
