### ISSUE TITLE
when we run nodejs test suite, few test cases is Done with errors.

### ISSUE THREAD

**Issue by MukeshSingh024** [nodejs/help#288]
Hi All,
when I run nodejs test suite, few test cases are Done with errors.
I want to know if there is some issue in nodejs or nodejs integration or Done is ok?
My NodeJs version is 4.5.0

Regards,
Mukesh

**Comment by bnoordhuis** [comment]
More information would be helpful.  Can you post the output?

**Comment by yorkie** [comment]
What's the Node.js test suite what you mean? And could you please post your logs/errors here so that we could track what happened, thank you @MukeshSingh024 :)

**Comment by lordKnighton** [comment]
@MukeshSingh024 did you have any luck with this yet? if so please close this issue. If not continue seeking further help. 


Happy coding ✅
