### ISSUE TITLE
In vm module, 'value instanceof Array' returns false when array is defined inside the execution string

### ISSUE THREAD

**Issue by saurabhdaware** [nodejs/help#2880]
* **Version**: I tried in v10.21 and v10.16
* **Platform**: Ubuntu 
* **Subsystem**: vm

### What steps will reproduce the bug?

```js
const vm = require("vm");

const aInstanceOf = `
  var a = [1, 2, 3]
  a
`;

const bInstanceOf = `
  b
`;

const aScript = new vm.Script(aInstanceOf);
const bScript = new vm.Script(bInstanceOf);

const aOut = aScript.runInContext(new vm.createContext({}));
const bOut = bScript.runInContext(new vm.createContext({ b: [1, 2, 3] }));

console.log("Output!");
console.log(aOut, aOut instanceof Array); // outputs [1, 2, 3] false
console.log(bOut, bOut instanceof Array); // outputs [1, 2, 3] true
```

CodeSandbox: https://codesandbox.io/s/vm-instanceof-error-d79ut?file=/src/index.js

### How often does it reproduce? Is there a required condition?

Nope. Happens every time. 

### What is the expected behavior?

Both of the outputs are supposed to be true I believe

Expected:
```
Output!
[1, 2, 3] true
[1, 2, 3] true
```

### What do you see instead?

```
Output!
[1, 2, 3] false
[1, 2, 3] true
```

### Additional information

Not sure if this is expected behavior or bug. I tried `Array.isArray(aOut)` and it outputs the expected value (`true`)

Thanks! and lots of love to Node Team!

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help. To answer your question: it's expected behavior, the vm context has its own set of built-ins (Array, Object, Date, etc.), separate from the built-ins of the outer context:
```
$ node
> vm.runInNewContext('Array') === Array
false
```

**Comment by saurabhdaware** [comment]
Ohh got it! Thank you so much

**Comment by tqma113** [comment]
@bnoordhuis Is there any way to set the built-ins same with current context?

**Comment by gireeshpunathil** [comment]
[vm.runInThisContext](https://nodejs.org/dist/latest-v15.x/docs/api/vm.html#vm_script_runinthiscontext_options) ?

```
> vm.runInThisContext('Array') == Array
true
> 
```

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if you still have issue
