### ISSUE TITLE
date convert error

### ISSUE THREAD

**Issue by JoeyBling** [nodejs/help#2881]
* **Version**:v12.18.2
* **Platform**:Windows
* **Subsystem**:

### What steps will reproduce the bug?
```javascript
let nowDate = new Date().toLocaleString("zh-CN")
console.log(nowDate)
// output: 2020-7-23 7:16:11 ├F10: AM┤
// if convert to ISOString An exception will occur
console.log(new Date(nowDate).toISOString())
```

### How often does it reproduce? Is there a required condition?

On Windows,always

### What is the expected behavior?

> 2020-7-23 7:16:11 AM

### What do you see instead?

> 2020-7-23 7:16:11 ├F10: AM┤

### Additional information

I tried to install the global internationalization support dependency,but it didn't work

> ```npm install -g full-icu```

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because I'm fairly sure this is a problem with your local setup, not a node bug.

With v14.6.0:
```
$ node
> new Date().toLocaleString("zh-CN")
'2020/7/28 下午2:03:12'
> new Date().toISOString()
'2020-07-28T12:03:28.113Z'
```
Note that v14.x has full-icu built in, v12.x doesn't. My guess is that node can't find the full-icu package on your system.

**Comment by JoeyBling** [comment]
This problem was not found in v12.14.0

**Comment by richardlau** [comment]
We updated ICU in Node.js 12.17.0 to a more recent version (ICU 67.1). If you've previously installed full-icu with an older version of Node.js 12 you will need to reinstall full-icu as unfortunately the data is specific to the version of ICU being used.

cc @nodejs/i18n-api

**Comment by srl295** [comment]
@JoeyBling full-icu is not a normal module. It's just a shortcut to load the ICU data. As @richardlau said, you must reinstall it if your node version changes.

**Comment by JoeyBling** [comment]
@srl295 I re installed `full-icu`, but it didn't work too

**Comment by srl295** [comment]
Try this in a new empty directory:  `npm i full-icu`

When it installs it will give you a command to run to test it. Can you try running that ?

**Comment by JoeyBling** [comment]
I did, then code output ```M01```
```javascript
let date = new Intl.DateTimeFormat('es',{month:'long'}).format(new Date(9E8));
console.log(date)
```

**Comment by srl295** [comment]
What was the node.js command line that it told you to run?

**Comment by JoeyBling** [comment]
@srl295 
```
Node will use this ICU datafile if the environment variable NODE_ICU_DATA is set to “node_modules\full-icu”
or with node --icu-data-dir=node_modules\full-icu YOURAPP.js
 For package.json:
{"scripts":{"start":"node --icu-data-dir=node_modules\\full-icu YOURAPP.js"}}

By the way, if you have full data, running this in node:
> new Intl.DateTimeFormat('es',{month:'long'}).format(new Date(9E8));
... will show “enero”. If it shows “January” you don't have full data.
News: Please see https://github.com/icu-project/full-icu-npm/issues/6
```

**Comment by srl295** [comment]
Ok and did you start node with:


node --icu-data-dir=node_modules\full-icu

?

**Comment by JoeyBling** [comment]
sorry,now is right
```
C:\Users\24343\Desktop\test>npm run start

> @ start C:\Users\24343\Desktop\test
> node --icu-data-dir=node_modules\full-icu index.js

enero
```

**Comment by srl295** [comment]
> sorry,now is right

So first: If you can upgrade to 14 do that and forget about full icu, it's there by default. 

Otherwise; what can we improve?

**Comment by JoeyBling** [comment]
allright,i try to upgrade to 14

**Comment by srl295** [comment]
great! please close the issue if it's fixed for you

>

**Comment by JoeyBling** [comment]
use function toLocaleString and parameter `zh-CN` ,The output is normal,but convert to date exception
```
2020/7/29 下午3:10:41
F:\workSpaces\openteam-postinstall\postinstall.js:20
console.log(new Date(nowDate).toISOString())
                              ^

RangeError: Invalid time value
```

**Comment by srl295** [comment]
> use function toLocaleString and parameter `zh-CN` ,The output is normal,but convert to date exception
> 
> ```
> 
> 2020/7/29 下午3:10:41
> 
> F:\workSpaces\openteam-postinstall\postinstall.js:20
> 
> console.log(new Date(nowDate).toISOString())
> 
>                               ^
> 
> 
> 
> RangeError: Invalid time value
> 
> ```

What is nowDate here?

**Comment by JoeyBling** [comment]
@srl295 zh-CN

**Comment by srl295** [comment]
`2020/7/29 下午3:10:41` is not a valid input to the `Date()` constructor. Don't use toLocaleString, see below:

```
let nowDate = new Date().toString();
console.log(nowDate)
console.log(new Date(nowDate).toISOString())
// 2020-08-07T06:20:35.000Z
```

**Comment by JoeyBling** [comment]
OK, I understand, thanks
