### ISSUE TITLE
Chocolately et. al. PowerShell script error post-Node installation

### ISSUE THREAD

**Issue by ebpatton** [nodejs/help#2882]
Getting the following error (see attached screen shot) when the PowerShell script runs to install Chocolately, Python, and the Visual Studio Build Tools after installing Node v.12. 

![Error](https://user-images.githubusercontent.com/68947994/88783512-e0fb8d80-d15c-11ea-961a-f9dd26984cd3.jpg)

**Comment by ebpatton** [comment]
Never mind.  It appears to have worked after a Windows update.

**Comment by kasem533** [comment]
![لقطة الشاشة 2023-12-31 202337](https://github.com/nodejs/help/assets/155380543/36ad8eb3-374a-4258-a60f-1eb60ff5a878)
Please help
