### ISSUE TITLE
fs.renameSync() incorrect working

### ISSUE THREAD

**Issue by odfrontendeveloper** [nodejs/help#2883]
I have file structure:

./F1
./F2
./F3
./F4

Then i use fs.renameSync() to move F4 to F3. Operation was completed.

./F1
./F2
./F3/F4

Then i want to use fs.renameSync() to move F3 to F2. But i have error as result:

UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted

I use the standart windows file manager to do this operation, but have a message "Operation can`t be ended, because this folder or file is open in another program".

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because this is unlikely to be an issue with Node.js itself. Next time, please fill out the issue template.

**Comment by gireeshpunathil** [comment]
@odfrontendeveloper - is this still an issue? can you share the code that you used?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
