### ISSUE TITLE
Print the resetPasswordToken but does not save it in mondoDB

### ISSUE THREAD

**Issue by adit2400** [nodejs/help#2884]
* **Node.js Version**:
* **OS**: OSX
* **Scope (install, code, runtime, meta, other?)**: trying to create a forgot password link 
* **Module (and version) (if relevant)**:

**Comment by adit2400** [comment]
I have attached screen shots of the code and the mongo schema.
<img width="626" alt="Screen Shot 2020-07-30 at 4 00 36 PM" src="https://user-images.githubusercontent.com/69016575/88974145-cff66d80-d27d-11ea-845a-89ac3961533d.png">
<img width="499" alt="Screen Shot 2020-07-30 at 4 01 03 PM" src="https://user-images.githubusercontent.com/69016575/88974200-e0a6e380-d27d-11ea-9c54-9aaf4e1fa30c.png">

**Comment by gireeshpunathil** [comment]
@adit2400 -  is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
