### ISSUE TITLE
Long Build Times on WSL 2 Normal?

### ISSUE THREAD

**Issue by arminlinzbauer** [nodejs/help#2885]
I'm experiencing very long build times when building node.js from source and was wondering if build times of about 15 to 20 minutes are normal. I think I've read somewhere that it usually should take about 5 minutes.

If my build times indeed seem too slow: I'm compiling on WSL2 with Ubuntu 20.04 - is it possible that WSL2 is causing this? In case you need to know, I'm building from within the Linux file system, not on the mounted windows partitions. 
My system has 32GB of RAM and a quite recent i7 CPU so that shouldn't be the bottleneck IMO.

I'm also using the -j4 option with make, but that didn't do much for the compilation times either.

**Comment by bnoordhuis** [comment]
How many CPUs do you see in `/proc/cpuinfo`? If it's only one, then 15-20 minutes is about par for the course.

**Comment by arminlinzbauer** [comment]
Thanks for the reply. I am seeing 8 cores. The processor model is `Intel(R) Core(TM) i7-8565U` with a clock speed of `1.80 GHz` and turbo boost to up to `3 GHz`. If this is indeed the case, then 15-20 minutes is a lot, correct?
I am compiling on Windows Subsystem for Linux (Version 2). Could WSL 2 cause such slow compilation performance?
