### ISSUE TITLE
Object.getOwnPropertyNames when called on context does not return properties with enumerable=false in vm.runInContext / vm.runInNewContext

### ISSUE THREAD

**Issue by KyranRana** [nodejs/help#2887]
* **Node.js Version**: 14.7.0
* **OS**:  Mac OSX Catalina
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: vm

```js
var vm = require('vm')

var ctx = {}
Object.defineProperty(ctx, 'a', {
    configurable: true,
    enumrable: false,
    value: 123,
    writable: true
})

vm.createContext(ctx)

console.log(Object.getOwnPropertyNames(ctx).indexOf('a')) // 'a' is in list
console.log(vm.runInContext('Object.getOwnPropertyNames(this)', ctx).indexOf('a')) // 'a' is not in list
```

I'm not sure if this a security constraint or an actual bug but any help is appreciated. :)

**Comment by bnoordhuis** [comment]
It's an artifact of history more than anything else. :-)

The original vm module worked by copying the properties from the sandbox object in and out of the VM context on every call, in a manner that mirrors how for/in iterates over an object's enumerable properties from both the object itself and its prototype chain.

Changing that behavior after 10 years is unlikely to happen, the risk of breaking existing code is too great.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
