### ISSUE TITLE
Can't kill node process - Error: listen EADDRINUSE: address already in use /tmp/echo.sock

### ISSUE THREAD

**Issue by davecarela** [nodejs/help#2888]
* **Node.js Version**: 12.16.1
* **OS**: Mac OS 10.15.5
* **Scope (install, code, runtime, meta, other?)**:

* **Module (and version) (if relevant)**: net

 As I follow through the API documentation, I fell into an issue. I continue to get the following ERROR, although I've killed the process using CTRL-C as well as, killing all NODE processes using `killall node`

**ERROR Message:**
`Error: listen EADDRINUSE: address already in use /tmp/echo.sock`

`...`

`at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '/tmp/echo.sock',
  port: -1
}`

```
const net = require('net');
const server = net.createServer((c) => {

  console.log('client connected');
  c.on('end', () => {
    console.log('client disconnected');
  });
  c.write('hello\r\n');
  c.pipe(c);
});
server.on('error', (err) => {
  throw err;
});



server.listen('/tmp/echo.sock', () => {
  console.log('server bound');
});
```
Searching through the help forum I found a similar issue where, the responder suggested rebooting if the the action mentioned above don't work.

Is there an alternative? or should I just reboot and include an `'close'` event at the end of 
`server.listen('/tmp/echo.sock', () => {
  console.log('server bound');
});`

**Comment by bnoordhuis** [comment]
The error here means `/tmp/echo.sock` already exists. Just `fs.unlinkSync()` it and try again.

**Comment by davecarela** [comment]
Hello @bnoordhuis ,

Thank you for responding.
so  I'm guessing I enter from console:
`fs.unlinkSync('/tmp/echo.sock')` ?

**Comment by davecarela** [comment]
Hi @bnoordhuis ,

running it via console didn't work, so I created a separate file with the 'fs' module and ran` fs.unlinkSync('/tmp/echo.sock')` .
This worked : )

Thanks for pointing me to a resolution
