### ISSUE TITLE
Please help me, I am a mechanical Engineer

### ISSUE THREAD

**Issue by dhruvashvi** [nodejs/help#2892]
I had installed Node js version V12.18.3 and it had by default npm version of 6.14.4. And was developing React Native Expo-Cli
later after learning React native expo cli I had to learn Node Js. So
I  took up a course on Udemy of Node js of Mosh Hamedani. In which he tells to downgrade your npm version to 5.5.1 by using the command line :- npm i -g npm@5.5.1. (Which I did)
 Right Now, I want to upgrade my npm version back to 6.14.4. 
So i Uninstalled the node Js from my pc and re-installed it expecting to get latest version of npm version.
 as I put the comand line :- npm -v  I still get 5.5.1

then i googled the problems and did the following 
I typed this npm uninstall -g npm  in my CMD
And I get error. (The picture of it has been attached)
![image](https://user-images.githubusercontent.com/63359382/89121332-a33f9180-d4db-11ea-8951-bbf9baf91338.png)

and then I tried this in my cmd
npm install npm@latest -g
And still i continue to get an error (Shown in screenshot i have attached)
![image](https://user-images.githubusercontent.com/63359382/89121371-fa456680-d4db-11ea-8211-cbb65e1a884f.png)

**Comment by bnoordhuis** [comment]
You're probably going to have more luck reporting this over at https://npm.community/. npm is bundled with node.js but it's not maintained by us, it's a separate project.

**Comment by PoojaDurgad** [comment]
@dhruvashvi -  I think due to the previous installed version of npm you are unable to install the latest version of npm . so you can manually delete the folders `npm_cache` and `npm` (i.e, node_modules) and reboot if needed and later you do `npm install npm@latest -g` which will install the latest version of npm

**Comment by PoojaDurgad** [comment]
inactive. closing !! feel free to re-open the issue if its  still outstanding
