### ISSUE TITLE
Two Phase commit

### ISSUE THREAD

**Issue by kumarmpk** [nodejs/help#2893]
Does the latest Node version support two phase commit for MySQL database. Can you share any reference for that?

**Comment by addaleax** [comment]
Node.js does not have any built-in support for MySQL, so it probably depends on which npm package you’re using for MySQL support?

**Comment by kumarmpk** [comment]
Thanks for the response. I am using latest mysql library version number: 2.18.1.
Using this how can I do two phase commit in nodejs.
Can you help?
