### ISSUE TITLE
Startup time issue on ARM

### ISSUE THREAD

**Issue by stewy** [nodejs/help#2895]
* **Node.js Version**: >= 10.22.0 
* **OS**: Linux (Yocto) @ ARM
* **Scope**: startup time

Hello,

  I've come across a significant startup performance issue on CPU constrained hardware (running at 600MHz).

Using official meta-embedded Yocto recipes as here: http://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-devtools/nodejs/nodejs_10.16.3.bb?h=zeus
, but also upgrading manually to latest v10.22.0 I get similar results in the order of 10s:

```
time ./node.y -e ''
real	0m9.438s
```

whereas using precompiled binary downloaded from https://nodejs.org//dist/v10.22.0/node-v10.22.0-linux-armv7l.tar.gz, the startup time is definitely more acceptable:

```
time ./node.bin -e ''
real	0m1.560s
```

**Note**: the issue seems somehow proportional to the codebase because it wasn't noticeable in using a much older 0.10.45 and attempting upgrade to 12.4.1 (always using Yocto as a build system), it explodes crazily:

```
time ./node.y12 -e ''
real	0m 19.18s
```

I've excluded several variables (such as misaligned dependencies and compilation flags), but still haven't found the culprit.

Would it be possible for you to share more info on the setup/configure/compilation flags used for the prebuilt binaries? Perhaps an inbuilt snapshot is used to speed up initialization? (Yocto configures Node with `--without-snapshot`..) Any other ideas otherwise?

Thanks a lot in advance

**Comment by addaleax** [comment]
> Perhaps an inbuilt snapshot is used to speed up initialization? (Yocto configures Node with `--without-snapshot`..

That sounds like a likely candidate, yes.

**Comment by stewy** [comment]
Many thanks @addaleax.

Is there any way you could help me confirm by checking how the official arm binaries are built? Is this documented somewhere or shall I just assume default configure flags? I can't see anything specific in ```BUILDING.md```.

**Comment by stewy** [comment]
No longer required thanks @addaleax: I just hacked a manually-created snapshot into Yocto and confirmed that the startup time is coherent with the official binary.

**Comment by alex88** [comment]
@stewy I'm running into the same issue, do you have an example you can share on how you've solved the problem? Thanks!

**Comment by stewy** [comment]
@alex88 as a workaround to this issue I basically:
- removed the `--without-snapshot` compilation flag from Node
- generated the snapshot.cc file via mksnapshot tool (taken from Node build dir) directly on my ARM target
- inserted the .cc file within Node source - in my Yocto recipe:
```
do_compile_prepend_class-target () {
    mkdir -p ${S}/out/Release/obj.target/v8_snapshot/geni
    cp ${WORKDIR}/snapshot.cc ${S}/out/Release/obj.target/v8_snapshot/geni
}
```
- stopped the Node build system from overwriting my binary:
```
Index: node-v10.22.0/deps/v8/gypfiles/v8.gyp
===================================================================
--- node-v10.22.0.orig/deps/v8/gypfiles/v8.gyp
+++ node-v10.22.0/deps/v8/gypfiles/v8.gyp
@@ -391,8 +391,8 @@
           ],
           'process_outputs_as_sources': 1,
           'action': [
-            '>@(_inputs)',
-            '>@(mksnapshot_flags)',
+#            '>@(_inputs)',
+#            '>@(mksnapshot_flags)',
           ],
         },
       ],
```
- installed the resulting (snapshot optimized) node binary on the target

As a cleaner solution, it should be possible to generate the snapshot directly on your buildsystem via an emulated qemu invocation of mksnapshot, but I didn't have enough time to waste on this.

Let me know if you succeed either way, cheers.

**Comment by alex88** [comment]
Thank you so much! I'll give it a try!
