### ISSUE TITLE
Crypto.createDecipheriv() using aes-256-cbc on an encrypted XML document

### ISSUE THREAD

**Issue by Bytegardener** [nodejs/help#2896]
* **Node.js Version**:  13.10.1
* **OS**: MacOS Mojave 10.14.6
* **Scope (install, code, runtime, meta, other?)**: Code

I have an encrypted xml file that contains an encrypted session key, and the ciphertext that is encrypted using this session key. 
I have verified that my decryption of the session key is correct. Using this to decrypt the utf-8 encoded ciphertext is failing. 
I have asked about this on online forums and not received an answer, and am at my wit's end as to why the decipher is failing. 
If this is not an issue within nodejs itself, any guidance on where to look for help is appreciated. 
Thank you

```
const cryptoAlgorithm = 'aes-256-cbc';

const message = Buffer.from(fs.readFileSync('/Users/anishshah/Programming/mediref/message1.txt', 'utf-8'));
console.log(message.length) //85228

// Initialization vector in xml files is prefixed to the ciphertext
const iv = Buffer.alloc(16, message.slice(0, 16)); 


const decipher = crypto.createDecipheriv(cryptoAlgorithm, decryptedSessionKey, iv);

let decrypted = Buffer.concat([decipher.update(message) , decipher.final()]);

error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length 

```

**Comment by bnoordhuis** [comment]
aes-256-cbc is a block cipher and 85,228 is not a multiple of the block size (16) so node/openssl is right to complain. Calling `decipher.setAutoPadding(false)` before the first `decipher.update()` call should fix it.

**Comment by PoojaDurgad** [comment]
@Bytegardener - did @bnoordhuis 's suggestion help you to resolve your issue?

**Comment by Bytegardener** [comment]
Hi Pooja,
My problems, which Ben kindly helped me solve -
a. I was not converting the encoded ciphertext/payload to base-64 , which
is the correct encoding.
b. I was not using regex to retrieve the relevant strings

They were all a result of errors on my part, and not Node.

**Comment by PoojaDurgad** [comment]
issue can be closed now.!!
