### ISSUE TITLE
Best method to detect brotli support in Node.js runtime

### ISSUE THREAD

**Issue by dougwilson** [nodejs/help#2897]
This is a generic question regarding support for multiple Node.js versions in the ecosystem. I'm looking for input on what the project thinks is the most robust way to detect if a given Node.js version supports brotli or not in the `zlib` module. I have seen the following methods used around:

1. `if (zlib.createBrotliDecompress) { ... }`
2. `if ('brotli' in process.versions) { ... }`
3. `if (zlib.constants.BROTLI_PARAM_MODE) { ... }` (or some other brotli constant)

This is mainly around that Node.js 10 (currently in maintenance mode) entered LTS before brotli was added.

**Comment by devsnek** [comment]
Well are you trying to figure out if brotli was linked into node or if `zlib.createBrotliDecompress` is available?

**Comment by danielgindi** [comment]
@devsnek It's basically about trying to figure out if we can use the `zlib` to decompress brotli. I guess the detection in this case should be `'createBrotliDecompress` in zlib`, but then different people have different opinions on what's "right" regarding feature detection.

Also on one hand we could say that we only trust node's builtin brotli codecs, and trust node's declarations about it.  
Personally I don't care, and any kind of feature detection is "good enough" for me. But if we're diving into technicalities, I would say that any polyfill that might add/replace `brotli` into `zlib` - should behave in a compatible and predicted way, and that it's the user's responsibility to know what libraries he/she is installing.

**Comment by silverwind** [comment]
`'createBrotliDecompress' in zlib` is what I'd do.

**Comment by PoojaDurgad** [comment]
@dougwilson - is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive . closing!! feel free to reopen the issue if its still outstanding
