### ISSUE TITLE
NodeJs is getting upgraded automatically from 8.15.0 to 10.19.0

### ISSUE THREAD

**Issue by sudhir007rawat** [nodejs/help#2898]
I am getting a weird issue where my Nodejs version is automatically getting upgraded from 8.15.0 to 10.19.0...Any idea why? I don't want to get this upgraded.

**Comment by mmarchini** [comment]
@sudhir007rawat which environment are you running on (Linux, Windows, OS X, with or without Docker, etc.)? How was Node.js installed? What is triggering the update? Please provide as much detail as you can.

**Comment by sudhir007rawat** [comment]
Here are the details:
- Windows 10
- Node js installed using MSI, downloaded from here https://nodejs.org/dist/v8.15.0/node-v8.15.0-x64.msi
- what is triggering the update.? - It's showing the system has installed the new version.
FYI - I don't have admin access on system, so I cannot install a new version.

**Comment by mmarchini** [comment]
@nodejs/platform-windows any ideas?

**Comment by nschonni** [comment]
If you don't have access to install it yourself, it's likely your system administrator is pushing the new version through the Company Portal or another patching mechanism for you, because Node 8 is end of life, and 10 is an LTS release

**Comment by PoojaDurgad** [comment]
@sudhir007rawat - is this still outstanding?

**Comment by tniessen** [comment]
There might be another Node.js version in your `PATH` environment variable. Check `where node`.

**Comment by PoojaDurgad** [comment]
closing as answered. please feel free to reopen the issue if that is not the case
