### ISSUE TITLE
dns.resolve() returns ESERVFAIL error for localhost

### ISSUE THREAD

**Issue by vinitshahdeo** [nodejs/help#2899]
* **Node.js Version**: `v10.14.1`
* **OS**: macOS
* **Module**: [DNS](https://nodejs.org/api/dns.html)

```js

dns.resolve('localhost', (err, res) => {
    if (err) {
        console.log(err);
    }
    else {
        console.log(res);
    }
});
```

The above code-snippet returns `ESERVFAIL` error. I tried using `resolve4`, `resolve6`, `resolveAny` which also gives the same error. **Am I missing anything?**

My use case is to resolve a given hostname into **IPv4** and **IPv6** addresses. As using `dns.lookup` is not recommended, **is there any other way to resolve hostname into its **A** and **AAAA** records with timeout options?**

**Comment by bnoordhuis** [comment]
`dns.resolve()` contacts the DNS servers listed in `/etc/resolv.conf` and those may not know about (or want to return something for) `localhost`. Example: querying 8.8.8.8 (Google's public DNS) fails with `ENOTFOUND`.

Try `dns.lookup()`, that calls libc's `getaddrinfo(3)`.

> As using dns.lookup is not recommended

Define 'not recommended'? It's perfectly okay to use it as long as you are aware of the differences with `dns.resolve()`.

**Comment by PoojaDurgad** [comment]
@vinitshahdeo - is this issue resolved? did @bnoordhuis 's suggestion help you to get rid of this issue?

**Comment by vinitshahdeo** [comment]
@PoojaDurgad My use case was little different, couldn't get much help from his solution.

**Comment by gireeshpunathil** [comment]
@vinitshahdeo - is this still an issue? does `/etc/resolv.conf` of your system has an entry for `localhost`?

**Comment by vinitshahdeo** [comment]
@gireeshpunathil Yes.

**Comment by Trott** [comment]
If you still need help, feel free to comment and provide:

* Contents of `/etc/resolv.conf`
* Results of `nslookup localhost` from the command line

Thanks!

I'm closing this, but happy to re-open if there's further activity.
