### ISSUE TITLE
Trying to run grunt on a remote app with expandrive (SSH)

### ISSUE THREAD

**Issue by omarhab** [nodejs/help#29]
I need to install grunt on my staging server... I do not work with local files. I use expanDrive to ssh in to the staging server and that allows me to edit files as if they are local. I figured I could still run node.js locally to create file on the docked drive the expanDrive would upload them. Maybe it is a permission issue but i cant get that to work... 

	
	npm ERR! Darwin 15.0.0
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
	npm ERR! node v5.0.0
	npm ERR! npm  v3.3.6
	npm ERR! path /Volumes/SFD/magento_carts/videoplus_basic1_younglivinggear_2015_08_dir/videoplus_basic1_younglivinggear_2015_08/node_modules/.staging/abbrev-5d3fad76853172fe50fff9204f01c834
	npm ERR! code ENOTEMPTY
	npm ERR! errno -66
	npm ERR! syscall rmdir

	npm ERR! ENOTEMPTY: directory not empty, rmdir '/Volumes/SFD/magento_carts/videoplus_basic1_younglivinggear_2015_08_dir/videoplus_basic1_younglivinggear_2015_08/node_modules/.staging/abbrev-5d3fad76853172fe50fff9204f01c834'
	npm ERR! 
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <https://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Volumes/SFD/magento_carts/videoplus_basic1_younglivinggear_2015_08_dir/videoplus_basic1_younglivinggear_2015_08/npm-debug.log
	```


Should I install node.js / grunt on my server? How?

**Comment by Trott** [comment]
The error messages seem to suggest that npm is failing to delete a directory because the directory is not empty. That suggests that it tried and failed to delete files in that directory. Perhaps try manually deleting the `node_modules` directory and re-running `npm install`.

**Comment by lordKnighton** [comment]
@omarhab if you still need help, let us know, closing for now.
