### ISSUE TITLE
Incorrect process id from spawn method, while spawning gnome-terminal, it results bash process id, not the gnome-terminal

### ISSUE THREAD

**Issue by VEmpink** [nodejs/help#2902]
* **Node.js Version**: 10.21.0
* **OS**: Linux Mint Cinnamon 19.1
* **Module**: child_process

Is possible to get spawned process id? While `spawn` `exec` `fork` etc. is the method where basically executing a shell and create the process id to that shell

```index.js
const { spawn } = require('child_process');

const xec = spawn('gnome-terminal', ['--wait', '-x', 'bash', '-c', '"tail -f app.log; exec bash"'], {
    shell: true
});

console.log(xec.pid); // resulting a bash process id not gnome-terminal process id
```

**Comment by bnoordhuis** [comment]
gnome-terminal probably forks itself out of the way, or attaches to an already running instance, that's why you don't see its pid. Unless it has some out-of-band means of sending the pid back to you, the answer is "no, you can't."
