### ISSUE TITLE
ERROR but how can I fix it 

### ISSUE THREAD

**Issue by Skiddybison5924** [nodejs/help#2904]
* **Node.js Version = v12.18.3**:
* **OS= Windows 10**:
 

Hi i wanna install armor paint and i need node js for thet too and ther is an error : 
command : node Kromx/make -g direct3d11
 Output : internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\tmp\armor\Kromx\make'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
 i hope u can help me

**Comment by PoojaDurgad** [comment]
@Skiddybison5924 - can you refer this https://github.com/armory3d/armorpaint/issues/524 ? hope it helps

**Comment by PoojaDurgad** [comment]
closing as answered. feel free to reopen if that is not the case
