### ISSUE TITLE
--disable-proto=delete flag does not allow to set a key named __proto__ using object literal

### ISSUE THREAD

**Issue by Media-Evil** [nodejs/help#2906]
* **Node.js Version**: 14.7.0
* **OS**: Windows 10 x64
* **Scope (install, code, runtime, meta, other?)**: other

**example**
```js
// invoked with --disable-proto=delete flag
const myObj = {
  __proto__: 'hui-pizda-jigurda'
};

console.log(myObj.__proto__); //yields undefined, expected 'hui-pizda-jigurda'
```
There is no bug if computed property with the same string is used instead. But more canonical form of defining simple properties in not supported =/

**Comment by devsnek** [comment]
the proto flag only disables the prototype accessor. the literal syntax is not considered a security concern so it is not included.

**Comment by Media-Evil** [comment]
Are there any plans to support a flag disabling `__proto__`'s magical meaning?

May the demand demand for a concise syntax to extend objects be satisfied via some new operator, like this:
```js
let a = { greeting: 'hello' };
let b = someNewOperator a {
  greet() {
     console.log(this.greet); //yields 'hello'
  }
};
```

**Comment by ljharb** [comment]
No, the proto syntax is required by JS and can’t and shouldn’t ever be disabled.
