### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by mrddo-com** [nodejs/help#2907]
I wrote a simple program:
```
console.log('Hello world');
console.log(__dirname);
```
Error:
```
Hello world
file:///C:/prj/akb48teamsh/html/t.js:2
console.log(__dirname);
            ^

ReferenceError: __dirname is not defined
    at file:///C:/prj/akb48teamsh/html/t.js:2:13
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

The following version got error:
Node latest v14.7.0
Node LTS v12.8.2
Node LTS v12.8.3

But Node version v10.15.3 works fine.
Please help.

**Comment by PoojaDurgad** [comment]
@mrddo-com - is this issue resolved? if yes can you close the issue please?

**Comment by mrddo-com** [comment]
The issue seem to be fix in v14.13.0

**Comment by dcjayasuriya2020** [comment]
this way it works:
```
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

```
1st get the __filename and then __dirname
both these CommonJs variables are not in ES modules, as per Node.org
we have replicate with `import.meta.url`

Source:[https://nodejs.org/api/esm.html#esm_no_require_exports_module_exports_filename_dirname](url)

**Comment by corydorning** [comment]
> The issue seem to be fix in v14.13.0

I'm using node v14.15.4 and this issue persists. The workaround from @lundibundi and @dcjayasuriya2020 does work though.

**Comment by blachawk** [comment]
I'm working off of node.js 14.15, and making use of the `import.meta.url`

* I have my main app named as `app.mjs` within my root directory.
* Within my package.json file I defined my start script as ` "start": "node app.mjs"`
* I then have  the following configured in my app.mjs file...

```js
import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const app = express();

//we need to change up how __dirname is used for ES6 purposes
const __dirname = path.dirname(fileURLToPath(import.meta.url)); 
app.use(express.static(path.join(__dirname ,'dist')));
```

perhaps a little more than the question needed, but shows the process.

**Comment by Mustafa-Agha** [comment]
I think we can create a `global.__dirname = process.cwd();`

**Comment by addaleax** [comment]
@dcjayasuriya2020’s answer is the right one. `process.cwd()` will not give you the right directory under most circumstances.

**Comment by p3k** [comment]
> As we can see from the stacktrace it looks like you are loading the file as a ECMAScript module (do you have `"type": "module"` in `package.json`?) which _doesn't_ have `__dirname` or `__filename`, you can emulate those as explained in this documentation https://nodejs.org/api/esm.html#esm_no_require_exports_module_exports_filename_dirname.

the url is now leading to the latest docs where the corresponding section has been removed. this is the url i found:

**Comment by peterp** [comment]
```
```

**Comment by tchetwin** [comment]
The docs have updated slightly, the new location is https://nodejs.org/api/esm.html#esm_no_filename_or_dirname

**Comment by neodau** [comment]
Uncaught ReferenceError: __dirname is not defined

**Comment by HunterKohler** [comment]
@sunmar25 The `__dirname` and `__filename` globals are [not defined in esm modules]( https://nodejs.org/api/esm.html#esm_no_filename_or_dirname). To get the path do one of the following:

#### Method 1: `URL` (global)
```js
function dirname(meta) {
    return new URL("", meta.url).pathname;
}

// call with import.meta
const __dirname = dirname(import.meta);
```

#### Method 2: `fileURLToPath` (requires an import)
```js
import { fileURLToPath } from "url"; // the node package 'url'

function dirname(meta) {
    return fileURLToPath(meta.url);
}

// call with import.meta
const __dirname = dirname(import.meta);
```

**Do not use `process.cwd()`.** This fetches the current working directory, which will be the call location of the project, and thus inaccurate for other files. You have to pass `import.meta` to a function because `import.meta` varies values over files. 

#### Use Globally

If you want this globally, add it to the Node.js `global` object like such:

```js
Object.defineProperty(global, "dirname", dirname) // where dirname is one of the two functions above
```

**Comment by fnpen** [comment]
You can use it in head of entry:

```

import { fileURLToPath } from 'url';

Object.defineProperty(global, '__dirname', {
	__proto__: null,
	get: function () {
		return dirname(fileURLToPath(import.meta.url));
	},
});
```

**Comment by addaleax** [comment]
> Method 1: URL (global)

**Do not do this**. `new URL(...).pathname` may contain percent-encoded characters, which do not match the actual file path in that case.

> You can use it in head of entry:

**Do not do this**. The point of `__dirname` is that it has different values in different scripts. Defining it on the global object has the exact opposite effect. 

I’ll lock this thread – @dcjayasuriya2020’s answer is the right one, for everybody who comes looking: https://github.com/nodejs/help/issues/2907#issuecomment-757446568. If you have another question, open a new ticket.
