### ISSUE TITLE
SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80

### ISSUE THREAD

**Issue by xcodebuild** [nodejs/help#2908]
* **Version**:
v12.18.3
* **Platform**:
Darwin xcmac.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
* **Subsystem**:

### What steps will reproduce the bug?

```shell
n 12.18.3
node --tls-min-v1.0
require('https').get('https://h5api.wapa.taobao.com/h5/mtop.alibaba.atmp.jsconfig.get/1.0/').on('error', e => {console.log(e)})
```

got output

```js
Error: write EPROTO 4592000448:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
    at WriteWrap.callbackTrampoline (internal/async_hooks.js:120:14) {
  errno: 'EPROTO',
  code: 'EPROTO',
  syscall: 'write'
```

but works in `node 8.0.0`

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

No tls-related error.

### What do you see instead?

Errors above

**Comment by shellberg** [comment]
I agree with @bnoordhuis.  I think this is an expected behaviour if the 'Hello' handshake is conducted with say, TLS 1.2, but then tries to re-negotiate the secure communication to a lower TLS level cipher of TLS 1.0 or 1.1.

This has been the case for some time.  From the [openSSL Changelog](https://www.openssl.org/news/changelog.html#x28):
> Some servers which support TLS 1.0 can choke if we initially indicate support for TLS 1.2 and later renegotiate using TLS 1.0 in the RSA encrypted premaster secret. As a workaround use the maximum permitted client version in client hello, this should keep such servers happy and still work with previous versions of OpenSSL.

**Comment by Summer-Time-2020** [comment]
所以这个问题怎么解决诶？
