### ISSUE TITLE
Error causing and can't build front end .

### ISSUE THREAD

**Issue by sangeethamohandas** [nodejs/help#2909]
VS Version: 1.47.3 (user setup)
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

The code was running smothly and suddenly it shows error while am trying to execute it.
![1 9](https://user-images.githubusercontent.com/62987357/89917029-f0c3a900-dc15-11ea-8e47-2ec522cd12c2.png)

![1 8](https://user-images.githubusercontent.com/62987357/89916987-e0abc980-dc15-11ea-832b-d5dcc890e301.png)

**Comment by PoojaDurgad** [comment]
@sangeethamohandas - I don't have deeper insight about this, but for me with your error log it looks like it require some additional peer dependency called `@babel-runtime`  .may be you could refer this https://github.com/meteor/meteor/issues/10128 , https://github.com/airbnb/babel-preset-airbnb/issues/56 to get rid of the issue.

**Comment by PoojaDurgad** [comment]
inactive issue. pls feel free to reopen the issue if its still outstanding
