### ISSUE TITLE
nodejs installation error

### ISSUE THREAD

**Issue by AmitVerma0893** [nodejs/help#291]
My computer is Windows 32-bit operating system. During installation of nodejs for windows 32-bit, the following problem is showing-
"There is a problem with Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor."

Now what I do?

**Comment by lordKnighton** [comment]
check out the `solution`:   [here](https://support.pix4d.com/hc/en-us/articles/202560999-Error-There-is-a-problem-with-this-Windows-Installer-package-A-DLL-required-for-this-install-to-complete-could-not-be-run-Contact-your-support-personnel-or-package-vendor-#gsc.tab=0)
