### ISSUE TITLE
Optional chaining on node.js

### ISSUE THREAD

**Issue by NMW03** [nodejs/help#2912]
* **Node.js Version**: 13.9.0
* **OS**: Centos 7
* **Scope**: code

Hello. I wanted to ask can we use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) on node.js? I can't find anything on google.

**Comment by devsnek** [comment]
You can use it in the latest 14.x releases.

**Comment by vsemozhetbyt** [comment]
See also https://node.green/#ES2020-features-optional-chaining-operator-----

**Comment by NMW03** [comment]
thanks
