### ISSUE TITLE
Node.js 12.18.3 comes with npm 6.0.1 instead of 6.14.6

### ISSUE THREAD

**Issue by HWHofstee** [nodejs/help#2913]
* **Node.js Version**: 12.18.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: npm

Reproduction:
* uninstall nodejs (also uninstalls npm)
* download Latest LTS Version: 12.18.3 (includes npm 6.14.6) for Windows (x64.msi) from https://nodejs.org/en/download/ 
* run the installation
after that:
```bash
$ npm -v
6.0.1
$ node -v
v12.18.3

```
```bash
$ npm install npm@latest -g
npm WARN npm npm does not support Node.js v12.18.3
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Harm\AppData\Roaming\npm-cache\_logs\2020-08-15T11_23_01_134Z-debug.log

```
Expected that the installed npm version would be 6.14.6.
Expected that the installed npm version would be compatible with the installed node.js version.
How can I install the correct npm version?

**Comment by bnoordhuis** [comment]
You have a stale copy of npm somewhere on your path (sorry, Windows - `%PATH%`.)

Delete it manually or reorder your `%PATH%` environment variable and the problem should be fixed.

**Comment by HWHofstee** [comment]
```
$ which npm
/c/Program Files/nodejs/npm

$ which node
/c/Program Files/nodejs/node
```

**Comment by HWHofstee** [comment]
I installed an older version:
[https://nodejs.org/download/release/v12.7.0/node-v12.7.0-win-x64.zip](url)

```bash
$ npm -v
6.10.0
```

**Comment by HWHofstee** [comment]
The date of the npm file (version 12.18.3) in the installation directory was of an older date.

That is also the case for the date of the npm file in the .zip distribution file.

That confirms to me that the distribution for Windows is incorrect.

**Comment by HWHofstee** [comment]
For the moment I can live with the V12.7.0 and 6.10.0 for the npm version. These seem to work fine.

**Comment by bnoordhuis** [comment]
> The date of the npm file (version 12.18.3) in the installation directory was of an older date.
> That is also the case for the date of the npm file in the .zip distribution file.
> That confirms to me that the distribution for Windows is incorrect.
```
$ unzip -c node-v12.18.3-win-x64.zip node-v12.18.3-win-x64/node_modules/npm/package.json | grep -w version
  "version": "6.14.6",
```
It must've been something else that made you end up with an outdated npm.

**Comment by HWHofstee** [comment]
Thanks, Ben. Now I see that npm in the installation is a shell script file. 
I installed the current version again.
To the NPM script file in the installation directory I added:
```bash
echo "$NODE_EXE" "$NPM_CLI_JS" "$@"
```
With the result:
```
$ npm -v
/c/Program Files/nodejs/node.exe C:\Users\Harm\AppData\Roaming\npm/node_modules/npm/bin/npm-cli.js -v
6.0.1
```
Then I removed the C:\Users\Harm\AppData\Roaming\npm/node_modules/npm directory.
And now:
```
$ npm -v
/c/Program Files/nodejs/node.exe /c/Program Files/nodejs/node_modules/npm/bin/npm-cli.js -v
6.14.6
```

So, that leaves me with some questions:
* What created this directory in AppData\Roaming, npm install npm -g?
* Should the uninstall for node have removed this installation of npm on AppData\Roaming?
* Should the .msi have overwritten the npm module in AppData\Roaming?
* What is the correct procedure for upgrading node.js and npm on Windows 10?

**Comment by bnoordhuis** [comment]
My guess (but that's just a guess) is `npm install -g npm`.

Node's installer is oblivious to AppData\Roaming, to the best of my knowledge. It won't install (but neither overwrite or remove) things in that directory.

**Comment by HWHofstee** [comment]
The next time nodejs and npm must be updated, I will use the following procedure:

1.
```bash
$ npm uninstall npm -g
```
Check that the C:\Users\<you>\AppData\Roaming\npm/node_modules/npm does not exist

2.
Run the uninstall of nodejs. Check that C:\Program Files\nodejs does not exist.

3.
Download and run the .msi file from [https://nodejs.org/en/download/](url)
