### ISSUE TITLE
How to pipe a request stream to a fork process?

### ISSUE THREAD

**Issue by talentlessguy** [nodejs/help#2916]
* **Node.js Version**: 14.8.0
* **OS**: 5.7.14-1-MANJARO
* **Scope (install, code, runtime, meta, other?)**: runtime 
* **Module (and version) (if relevant)**: `child_process`

Hello, I'm writing a tutorial of making a simple mutli-threaded HTTP server. I ran into an issue of that I don't understand how I can pipe the `req` readable stream object to a fork process. I'm trying to tweak `stdio` descriptors but no success yet :(.

Here's the code I have:

**main.mjs**:

```js
import { fork } from 'child_process'
import { createServer } from 'http'

const port = parseInt(process.env.PORT) || 3000

const processes = []

for (let i = 0; i < 4; i++) {
  const serv = fork(`${process.cwd()}/server.mjs`, {
    stdio: ['pipe', 'ipc', 'pipe'],
  })
  processes.push(serv)
}

let currProc = 0

const inc = () => (currProc = currProc === processes.length - 1 ? 0 : currProc + 1)

createServer(async (req, res) => {
  inc()

  req.pipe(processes[currProc].stdin)

  res.end('Hello World!')
}).listen(port, () => console.log(`Listening on http://localhost:${port}`))
```

**server.mjs** (ik unrelated name):

```js
process.stdin.on('data', (d) => {
  console.log(d)
})
```

The output I get is:

```
Listening on http://localhost:3000
(node:42308) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of null
    at IncomingMessage.Readable.pipe (_stream_readable.js:665:8)
    at Server.<anonymous> (file:///home/v1rtl/Coding/we_use_js/multithread/child_process/main.
```

Because I try to pipe to a non-existent process `stdin` descriptor.

I couldn't find any information about this on the internet, so I'm opening the issue here.

although, there is one related thread (which didn't work in my case, getting same error):

https://github.com/nodejs/node-v0.x-archive/issues/4374

**Comment by bnoordhuis** [comment]
You're using `child_process.fork()`. Replace `process.stdin.on('data', d => {})` with `process.on('message', m => {})`.

**Comment by bnoordhuis** [comment]
Oh, wait - you're trying to pipe the output from the master to the worker? This line is incorrect at any rate:
```js
req.pipe(processes[currProc].stdout)
```
Because you're piping to the worker's stdout, not stdin. And you probably want to use `child_process.spawn()` instead.

**Comment by talentlessguy** [comment]
> You're using `child_process.fork()`. Replace `process.stdin.on('data', d => {})` with `process.on('message', m => {})`.

IPC messages AFAIK can only send plain text

at least this:

```js
import { fork } from 'child_process'
import { createServer } from 'http'

const port = parseInt(process.env.PORT) || 3000

const processes = []

for (let i = 0; i < 4; i++) {
  const serv = fork(`${process.cwd()}/server.mjs`)
  processes.push(serv)
}

let currProc = 0

const inc = () => (currProc = currProc === processes.length - 1 ? 0 : currProc + 1)

createServer(async (req, res) => {
  inc()

  req.pipe(processes[currProc].stdout)

  res.end('Hello World!')
}).listen(port, () => console.log(`Listening on http://localhost:${port}`))

```

returns me this:

```
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of null
```

**Comment by talentlessguy** [comment]
> Oh, wait - you're trying to pipe the output from the master to the worker? This line is incorrect at any rate:
> 
> ```js
> req.pipe(processes[currProc].stdout)
> ```
> 
> Because you're piping to the worker's stdout, not stdin. And you probably want to use `child_process.spawn()` instead.

* I need to pipe the `req` stream to another process - if I'm doing it wrong, what's the better way?
* > And you probably want to use `child_process.spawn()` instead.

It's mentioned in the docs that `spawn()` method is used to spawn processes from the shell, which I don't need, so I followed the docs later and found this `fork()` description, which matched my requirements:

> `child_process.fork()`: spawns a new Node.js process and invokes a specified module with an IPC communication channel established that allows sending messages between parent and child.

[docs ref](https://nodejs.org/api/child_process.html#child_process_child_process)

**Comment by talentlessguy** [comment]
for the note: what I'm trying to do is to remake `cluster` with a very basic implementation
