### ISSUE TITLE
How to run python script with pip installed imports with Node.js child process

### ISSUE THREAD

**Issue by Brandhsu** [nodejs/help#2917]
* **Node.js Version**: 12.18.1
* **OS**: Mac Mojave 10.14
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

```
**js**
const express = require("express");
const app = express();
const port = 3000;

// python script
let runPy = new Promise(function (success, nosuccess) {
  const { spawn } = require("child_process");
  const pyprog = spawn("python", ["-u", "./main.py"]);

  pyprog.stdout.on("data", function (data) {
    console.log("Pipe data from python script ...");
    success(data);
  });

  pyprog.stderr.on("data", function (data) {
    console.log("Pipe data from python script ...");
    nosuccess(data);
  });
});

app.get("/getSongs", (req, res) => {
  runPy.then(function (fromRunpy) {
    console.log(":0");
    console.log(fromRunpy.toString());
    res.send(fromRunpy.toString());
  });
});

app.get("/", (req, res) => {
  res.send("Home!");
});
app.listen(port, () => console.log("Application listening on port 3000!"));

```

```
**py**
from youtube_search import YoutubeSearch
print('Hello World')
```

Not sure what the exact issue is, but it seems that the import is causing an UnhandledPromisRejection error but I dont know why or how to fix...

```
**Error Message**
(node:619) UnhandledPromiseRejectionWarning: [object Uint8Array]
(node:619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

Help would be appreciated :)

**Comment by bnoordhuis** [comment]
You're probably calling `success` and `nosuccess` multiple times.

**Comment by Brandhsu** [comment]
Can this occur even if the prints don't occur multiple times??

I am finding that if the python script doesn't include any imports or includes python standard imports there is no UnhandledPromiseRejection warnings and I get the correct value.

**Comment by Brandhsu** [comment]
Additionally adding a catch chain 
```
app.get("/getSongs", (req, res) => {
  runPy.then(function (fromRunpy) {
    console.log(":0");
    console.log(fromRunpy.toString());
    res.send(fromRunpy.toString());
  }).catch(function (error) {
    console.log(error);
  });
```
doesn't remove the promise rejection and it seems that the python subprocess stream always activates stderr

**Comment by Umang-19** [comment]
> Can this occur even if the prints don't occur multiple times??
> 
> I am finding that if the python script doesn't include any imports or includes python standard imports there is no UnhandledPromiseRejection warnings and I get the correct value.

I'm facing the same issue. Could you help me with this?

**Comment by amirgamil** [comment]
Were u able to figure how to import external packages in the python script called from the node child process?

**Comment by egeergul** [comment]
could this problem be solved?

**Comment by YounesBensoudaMourri** [comment]
Any updates on this?

**Comment by jesmeister78** [comment]
also trying to load the dependencies - did you get it working?>

**Comment by robiulhr** [comment]
Did anyone get the solution to this problem?
