### ISSUE TITLE
Heap out of memory with no modification

### ISSUE THREAD

**Issue by Mdsp9070** [nodejs/help#2918]
* **Version**: 14.7.0
* **Platform**: Manjaro 64bits
* **Subsystem**:

### What steps will reproduce the bug?

Just clone my repo: https://github.com/Mdsp9070/gitlocalstats and try to run as follows:
```sh
    ts-node src/main.ts <folder> <email>
    # OR
    tsc && node build/src/main.js <folder> <email>
```

I know my code is kinda big, but the point is: out of the blue, my code started to heap ou of memory with any changes. I really didn't understand why this's happening.

### How often does it reproduce? Is there a required condition?
Every time I try to run. No, simply try to run.

### What is the expected behavior?
At least execute `printMonths()` and `printCell()` functions.

### What do you see instead?
```sh
<--- Last few GCs --->

[895735:0x3c668c0]    13961 ms: Mark-sweep 1299.1 (1344.8) -> 1299.1 (1313.8) MB, 1891.3 / 0.0 ms  (average mu = 0.296, current mu = 0.000) last resort GC in old space requested
[895735:0x3c668c0]    15727 ms: Mark-sweep 1299.1 (1313.8) -> 1299.1 (1313.8) MB, 1766.1 / 0.0 ms  (average mu = 0.171, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xf77598dbe1d]
    1: ConstructFrame [pc: 0xf775988d145]
    2: StubFrame [pc: 0xf7759909d9d]
Security context: 0x37a8e021e6c1 <JSObject>
    3: DoJoin(aka DoJoin) [0x37a8e0205e69] [native array.js:1] [bytecode=0x15ce24d570c9 offset=148](this=0x21342e6026f1 <undefined>,l=0x0cb84816ac99 <JSArray[16777217]>,m=16777217,A=0x21342e6028c9 <true>,w=0x014d871b4901 <String[1]\: \n>,v=0x21342e6029a1 <false>)
    4: Join(aka Jo...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x8fb090 node::Abort() [node]
 2: 0x8fb0dc  [node]
 3: 0xb0322e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb03464 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef74c2  [node]
 6: 0xf06cdf v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
 7: 0xecfd36 v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [node]
 8: 0xed05ba v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [node]
 9: 0xed0b77 v8::internal::Factory::NewUninitializedFixedArray(int, v8::internal::PretenureFlag) [node]
10: 0xe922f0  [node]
11: 0xe95662  [node]
12: 0xe959c2  [node]
13: 0xe95e72 v8::internal::ArrayConstructInitializeElements(v8::internal::Handle<v8::internal::JSArray>, v8::internal::Arguments*) [node]
14: 0x112a15f v8::internal::Runtime_NewArray(int, v8::internal::Object**, v8::internal::Isolate*) [node]
15: 0xf77598dbe1d 
^C[1]    895735 abort (core dumped)  node main.js /home/mdsp/Documents/ matheus_pessanha2001@outlook.com
```

Could anyone help me to find where it's happening this heap out?

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because it's unlikely to be an issue with Node.js itself.

As a hint, I can tell from the stack trace that you're calling `Array.p.join()` on what is presumably a rather large array.

**Comment by Mdsp9070** [comment]
Actually, there's no problem with program, file generated by it was about 46k+ lines...

**Comment by abdulmajidkazi** [comment]
> I've moved this to nodejs/help because it's unlikely to be an issue with Node.js itself.
> 
> As a hint, I can tell from the stack trace that you're calling `Array.p.join()` on what is presumably a rather large array.

@bnoordhuis : Do we have a solution for this yet? I have exactly the same error. I have to increase heap size to 6 GB for the build to succeed in about 30 minutes. Is this acceptable?

**Comment by abdulmajidkazi** [comment]
> nodejs/help

@bnoordhuis : How can i track Array.p.join() call to my source code?
