### ISSUE TITLE
An initialization routine dynamic link library (DLL)

### ISSUE THREAD

**Issue by pjdepractica** [nodejs/help#292]
I'm starting with Node.js Addons, I made my own addons node.js guiding me to the documentation.

**This script returns:**

**Uncaught error: an initialization routine dynamic link library (DLL).**
**\? \ C: \ Users \ .......\addons.node**

```
<body>
  <h1>Addons</h1>
  <p>
    Lorem ipsum dolor sit amet.
  </p>


  <script type="text/javascript">
  alert("hello");
    var addon = require('./build/Release/addon');


    alert(addon.walk()); // 'walking'
    alert(addon.fly()); // 'flying'


  </script>
</body>
```

I have also built all of the above with node-pre-gyp, nw-gyp. All this guiding me to the documentation.

But nowhere you put a precise / clear example of how to implement it.

I have to do something else to use my module in nw.js?
I omitted some way?

**Thanks to all who can help, any suggestions are welcome.**

_Excuse my English, I speak Spanish. Gracias._

**Comment by Trott** [comment]
Hi! I'm not sure there's going to be too many people in this repository with specific experience building native add-ons for Windows. However, let me try pinging a few folks just in case:  @nodejs/platform-windows @nodejs/addon-api

You might have better luck trying to ask this question in the [#Node.js IRC channel](https://webchat.freenode.net/?channels=node.js&uio=d4) or on [StackOverflow](https://stackoverflow.com/).

**Comment by lordKnighton** [comment]
@pjdepractica hey did you have any luck getting this puppy working? I don't have any experience with this, but it looks straight-forward, show me your code for the `addon` module. addon.js
