### ISSUE TITLE
Get the shell of node process

### ISSUE THREAD

**Issue by LitileXueZha** [nodejs/help#2920]
* **Node.js Version**: 12
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**:  runtime
* **Module (and version) (if relevant)**:

What's the shell which start node? It's not the default system shell, just which execute node command.
For example:

***windows:***
```shell
## run at cmd
node xxx.js
# the shell is cmd.exe

## switch to powershell
node xxx.js
# so it is powershell.exe
```

***linux:***
```shell
## run at bash
node xxx.js # ==> /bin/bash

## switch zsh
node xxx.js # ==> /bin/zsh
```

I tried `process.execPath`, but it returns node itself. I also read nodejs docs, and find out the default shell is `process.env.ComSpec` or `process.env.SHELL`.
But what's the runtime shell?

**Comment by bnoordhuis** [comment]
It's kind of the wrong question to ask because there doesn't need to be a parent shell but that aside... `process.ppid` is the pid of the parent process. Linux-specific example: ```fs.readlinkSync(`/proc/${process.ppid}/exe`)```

Can I ask what you want to use it for?

**Comment by LitileXueZha** [comment]
emmm... Command's stdout may be a little different when it executed by `child_process.exec` and the runtime shell.

```shell
# usually launch powershell.exe on windows
$ aka_command # run command
# output1...
# ...
$
# use nodejs execute it
$ node -e "child_process.exec('aka_command')"
# output2...
# ...

# some different because of this shell and child process's default shell
```
So i want the same behavior, no matter execute directly or use nodejs:
```js
child_process.spawn('aka_command', {
  shell: true,
  // use the shell which launch this process
  // where's it?
  // shell: '...',
  stdio: 'inherit',
});
```

Maybe i can try to find the shell by `process.ppid`.
