### ISSUE TITLE
From node js 12 +versions our base station devices are not getting connected

### ISSUE THREAD

**Issue by UmaMuthu** [nodejs/help#2922]
* **Node.js Version**:12+
* **OS**:Ubuntu
* **Scope (install, code, runtime, meta, other?)**:runtime
* **Module (and version) (if relevant)**:

From node js 12 +versions our base station devices are not getting connected.
In our application the base station devices will connect with our application to get the configuration data, but from node version 12+, devices are not getting connected with our application
In the devices we see <6> [CFG]File download failure by "The requested URL returned error: 400 Bad Request(400)[E22]"
And in our application log we dont see any logs

It is working fine till node version 11.15.0, what is the difference in node 12 for this behaviour

**Comment by PoojaDurgad** [comment]
@UmaMuthu - What type of client device you are running? can you 'export NODE_DEBUG=http' on client terminal and then try to connect? it will show up additional debug messege that give some hint.

**Comment by PoojaDurgad** [comment]
inactive. closing!!
