### ISSUE TITLE
Nodejs Worker Thread Execution 

### ISSUE THREAD

**Issue by muhammadfahad93** [nodejs/help#2923]
Hi all,

Any have an idea about the execution of the worker thread. Does this worker thread utilize all System Core or run on a single thread?

**Comment by addaleax** [comment]
> Does this worker thread utilize all System Core or run on a single thread?

Worker threads are OS-level threads, so they participate in the distribution of system cores to processes by the operating system itself (although they can be moved between CPU cores as the operating system sees fit), and every Worker thread occupies one CPU at a time at most.

**Comment by muhammadfahad93** [comment]
@addaleax  thanks.
