### ISSUE TITLE
How to iterate into the collection of class objects in node.js

### ISSUE THREAD

**Issue by Shweta2910** [nodejs/help#2927]
I have two classes one and two

class One{
constructor(field1, field2)
{
this.field1=field1;this.field2=field2;
}
}
module.exports = one

class Two{
constructor(field11, field22, list[])
{
this.field11=field11;this.field22=field22; 
this.list = list
}
}

add(one)
{
this.list.push(one);
}

module.exports = Two
Third class imports both classes

    const one= require('./one.js');
const two= require('./two.js');
Now, I have a function which creates an object of class two and add some values like,

two = new two();
two.add(new one(1,1000)); 
two.add(new one(2,2000));

console.log(two.list); 
////list is a collection of class one object Till this point is working fine, I am getting collection

My query is how to iterate through collection like, I want to access two.list[0].field1
// not getting the property field1

**Comment by addaleax** [comment]
Hm, it might help if you could clarify whether you’re having problems with runnable code, or with how your IDE/editor interacts with the code? If there’s a problem that others would be able to reproduce using only the `.js` files you’re using, it would be good if you could share them + the expected/actual outputs.

> (list of properties and methods not visible in intellisense when I type '.' )

I’m not sure if this is your problem, but arrays in JavaScript aren’t typed, so autocompletion tools won’t be able to know the type of array entries for sure. If you’re working with TypeScript, adding a type to the array property might help?

**Comment by PoojaDurgad** [comment]
@Shweta2910 - is this still outstanding?

**Comment by PoojaDurgad** [comment]
inactive issue
