### ISSUE TITLE
All exit codes?

### ISSUE THREAD

**Issue by JavascriptLearner815** [nodejs/help#2929]
* **Node.js Version**: 14.7.0
* **OS**: HP Slim Desktop | Windows Build 10
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: Process

From [the node.js documentation](https://nodejs.org/api/process.html#process_process_exitcode):

> A number which will be the process exit code, when the process either exits gracefully, or is exited via `process.exit()` without specifying a code.

This explanation is good, but it neither mentions a list of all exit codes, nor links to a page explaining it.

Aren't there other exit codes other than 0 or 1? It would make sense if there wasn't, but normally there would be many exit codes.

**Comment by vsemozhetbyt** [comment]
See https://nodejs.org/api/process.html#process_exit_codes

**Comment by addaleax** [comment]
Other than that, Node.js provides the same range of exit codes as the operating system, i.e. you can generally assume that the exit codes 0 through 127 are freely available to you.

**Comment by JavascriptLearner815** [comment]
Okay, thanks for answering! I was on the right track on my thoughts, I just wasn't completely sure.

To any potential viewers that also need answers, try looking [here](http://www.hiteksoftware.com/knowledge/articles/049.htm).
