### ISSUE TITLE
Refused to apply style from "http://localhost:8080/assets/main.css"

### ISSUE THREAD

**Issue by jjuannn** [nodejs/help#2930]
* **Node.js Version**: v12.18.3
* **OS**: Windows 10 Pro
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Hello, im trying to load CSS in my app. JS and HTML (express-handlebars) files loads correctly. But when i try to load the CSS styles for the HTML, i get this error in the console:

```js
Refused to apply style from 'http://localhost:8080/assets/main.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
When i go to the network tab, i see 

```js
main.css || status (cancelled) || type stylesheet
```
I revised the path, but its correct and i don't know why i cannot load my file.

in my html i have:
`<link rel='stylesheet' type='text/css' media='screen' href='assets/main.css'>`

and in my js file i have :
`app.use("/public", express.static("public"))`

My workspace is 
+node_modules

+public
   ++assets
      +++main.css

+template-engine
++main.js

Any help? Thanks

**Comment by addaleax** [comment]
I’m not sure if this is the problem, but if you use `app.use("/public", express.static("public"))`, that only affects URLs whose path starts with `/public`, so `http://localhost:8080/assets/main.css` is not the right URL? What happens if you use `href="/public/assets/main.css"` instead?

**Comment by jjuannn** [comment]
It doesn't work either
