### ISSUE TITLE
Error: unexpected end of file - zlib.zipOnError

### ISSUE THREAD

**Issue by ParshantMehra** [nodejs/help#2931]
* **Node.js Version**: 12.18.2
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: code, runtime
* **Module (and version) (if relevant)**: zlib
 
Hi,

My use case is that I am downloading .ndj.gz file from Object storage. So I am using pipe with streams. 

this._s3.getObject(params).createReadStream()
    .pipe(zlib.createGunzip())
    .pipe(this.lineTransfromerStream());

lineTransformerStream() converts chunks to lines.  _s3 is aws-sdk s3 client.
In production, intermittently but very frequently, it is failing with error stack as - 

2020-08-24 21:56:11 -0700 [error] d8d41f40-6a07-4791-92bb-64c954aab321 Error: unexpected end of file ... Backtrace: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
    Logged from:     at process.<anonymous> (/opt/skulk/scripts/abstract_script.js:222:12)
    at process.emit (events.js:327:22)
    at process.EventEmitter.emit (domain.js:482:12)

How can I workaround this? I thought zlib is duplex stream and it handles errors if source stream is slow or fast?
Am I missing something?

Thanks for pointers.

Regards,
Parshant

**Comment by ParshantMehra** [comment]
Any pointers please

**Comment by addaleax** [comment]
The problem most likely isn’t stream performance, but rather actual invalid stream content. Can you store the stream (pre-gunzip) in a file and check whether a program like `gunzip` can compress it?

**Comment by ParshantMehra** [comment]
Yes, If i download that file and gunzip that, it works fine but if I take that stream and pipe it to zlib, it fails with exception given above. This is an intermittent but very frequent error we are encountering. 

As a workaround for time beling, we are now first downloading full file from Object storage and then unzipping that downloaded file using zlib.createGUnzip()
