### ISSUE TITLE
Import order of ES6 modules in node

### ISSUE THREAD

**Issue by Twiggeh** [nodejs/help#2934]
* **Node.js Version**: v14.7.0
* **OS**:       Operating System: Manjaro Linux
* **Kernel**:   Linux 5.4.57-1-MANJARO
 
* **Scope**: code 

I have a couple of questions : 

1.  If the entry imports a function from a file, does it start executing the imported function as soon as the import is done ?

3.  If the file that is being imported has other imports, do they run before the import of the entry ? 

5.  Is the order in which the imports have been specified important? Do those imports execute in order?  How does export const function affect things ? 

I am super confused, because the files that I am importing are not imported in order, nor do the imported files import their imports first. The order doesn't change though, so there must be some logical reason why it does them out of order / doesn't respect child imports' imports. 

```js
example : 
(async()=>{
  await init();
  ...
})()

import { stuff } from "./utils/emojiInteractions.js"
import { stuff } from "./utils/utils.js"
import { stuff } from "./EMOJIS.js"
import init, { stuff } from "./init.js" 
```

It imports emojiInteractions.js then Emoji.js then runs init() then throws from inside init that it cannot access stuff before 
initialization from utils.js

I couldn't find the portion about importing order in the node docs / don't know where  to look that up.

I would gladly appreciate any help, because so far my solution was to up everything into one masterutils file and then import that

**Comment by Twiggeh** [comment]
Found the part of [the documentation](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#3-semantics) that refers to this, and it clarified all of the previous questions. 

So another question arose : 
> Order of module evaluation within a module graph will always be preserved.

What exactly is a module graph ?

**Comment by MylesBorins** [comment]
I gave a talk about esm and there is a section specifically about the order for load / execution

https://youtu.be/bP0tlIcA3ns?t=573

The order for load / execution is outlined in the ECMA specification, not by node. All static imports are hoisted to the top and loaded in `pre-traversal order`. E.g. the order that you call them, with depth first traversal. In your example `emojiInteractions.js` will get loaded first, then it's dependencies prior to loading anything else. Load only includes fetching the resource and parsing it, it does not execute. After the graph is loaded there in a link phased, also in pre-order traversal, that links the graph and resolves any cycles. Finally the execution phase runs in post-order traversal... starting at the bottom left node, resolving siblings, and then moving to parents (and parent siblings). If you look at my talk there are more visuals to help describe it.
