### ISSUE TITLE
Unable to run a javascript file even though node is installed, same code works when pasted into the REPL

### ISSUE THREAD

**Issue by ryanbishop12** [nodejs/help#2935]
* **Version**: 12.18.3
* **Platform**: Windows Server 2016 x86-64
* **Subsystem**:

### What steps will reproduce the bug?

running `node filename.js` does nothing, there's no error the terminal just prompts you for input again

### How often does it reproduce? Is there a required condition?
Always
### What is the expected behavior?
To run the javascript file

### What do you see instead?
nothing, there's no error the terminal just prompts you for input again

### Additional information
node is in fact installed I've checked this with `node -v` another interesting thing that is happening is i can use `node` to go into the REPL and then paste the code in and it works correctly

**Comment by ryanbishop12** [comment]
@MylesBorins It does have this in it
```
app.listen(port, hostname, () => {
    console.log(`Server running at http://${hostname}:${port}/`);
});
```

which logs when I run it in the REPL but does nothing when I do `node filename.js`

**Comment by MylesBorins** [comment]
Can you try running a simpler script with only console log. Perhaps there is an issue in your application logic.

**Comment by ryanbishop12** [comment]
Yeah I can give me a while though I don't currently have access to our dev server, I just don't understand why it would work in the REPL but not from running a script

**Comment by ryanbishop12** [comment]
Ok I'm dumb I had forgotten to save that part of the file when I was making it.

**Comment by trucker-military-industr** [comment]
> Yeah I can give me a while though I don't currently have access to our dev server, I just don't understand why it would work in the REPL but not from running a script





https://lnkr.fun/88aee88
