### ISSUE TITLE
Please help me with this problem

### ISSUE THREAD

**Issue by Nilay1995** [nodejs/help#2936]
* **Node.js Version 12.18.3**:
* **OS - windows 10**:
* **Scope (runtime)**:

C:\Users\Nilava&Nilay>npx create-react-app brick-wal
'Nilay\' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\Nilava\node_modules\create-react-app\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by addaleax** [comment]
I think this might be happening because of something `npx` does when running in directories with special characters like `&`. Does it help when you run it in another directory?

**Comment by ofirshe** [comment]
also have this same problem save version of node

**Comment by ofirshe** [comment]
if someone can help it will be great

**Comment by PoojaDurgad** [comment]
@ofirshe - can you try running `npx create-react-app my-app` in an empty folder?

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to re-open the issue if its still outstanding
