### ISSUE TITLE
Javascript heap out of memory

### ISSUE THREAD

**Issue by KrupaThaker** [nodejs/help#2937]
* **Node.js Version**: V10.16.1
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: Gulp 2.2.1

**Comment by PoojaDurgad** [comment]
@KrupaThaker , Can you elaborate on what program you are running? and steps that reproduce the problem? does it go away if you increase the default heap size?

**Comment by PoojaDurgad** [comment]
no response, closing this issue as inactive. feel free to re-open if this is outstanding
