### ISSUE TITLE
why not use modern syntax in node lib? for example: default value

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#2939]
* **Node.js Version**: LTS ans current
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: any

for example
![image](https://user-images.githubusercontent.com/8686739/91252961-38f3d700-e791-11ea-8fda-bc6a50c8b7bf.png)
![image](https://user-images.githubusercontent.com/8686739/91253008-5b85f000-e791-11ea-914c-3fc76695ae2f.png)

you can do
`Buffer.prototype.toString = function toString(encoding = 'utf8', start = 0, end)`

**Comment by bnoordhuis** [comment]
`Buffer.prototype.toString` _far_ predates the default arguments feature of modern JS.

As a rule, Node.js core doesn't update to newer syntax unless there are clear benefits, like better readability, better performance, etc.

In this specific case there's a subtle difference between the old and the new syntax. Compare:
```js
function f(x, y, z) {}
console.log(f.length)  // 3
```
Vs.
```js
function f(x=0, y=0, z=0) {}
console.log(f.length)  // 0
```
It _probably_ doesn't matter for `Buffer.prototype.toString` but people do all kinds of weird things. Any change risks introducing regressions.

**Comment by anlexN** [comment]
when default value, why f.length == 0? what design idea is it?
