### ISSUE TITLE
Problem to access socketIO behind my rooter

### ISSUE THREAD

**Issue by splootch** [nodejs/help#294]
Hello everybody, 

I created a web server with NodeJS and socketIO.
When you arrive on my adress, the server send to you a HTML page. This works fine.

On the HTML page there is my socket connected to the server. 
-> If someone out of my local network go on the adress it does work.
-> If someone in my local network go on the adress it does NOT work and i have the error : "ReferenceError: io is not defined" .

I look for many solutions on forums/chat/IRL, but i do not understand why IO is not defined in my local network ( why my application works out of my network and not in) ?

**Comment by lordKnighton** [comment]
can you share some logs?

**Comment by splootch** [comment]
What do you mean by logs please?

**Comment by lordKnighton** [comment]
server outputs: errors messages about this situation.

**Comment by splootch** [comment]
My server works with no error, this is when the client try to use a socketIO function **io.connect()** from into my network. The console logs: "ReferenceError: io is not defined" after a short time.
In order to access my application, i use my public IP in the browser.  It does not work for the machines in the network, i have to use my private adress ( but it works from beyond my network).

**Comment by lordKnighton** [comment]
http://stackoverflow.com/questions/11995406/socket-io-referenceerror-io-is-not-defined
