### ISSUE TITLE
Code style recommendation: sync/async polymorphism

### ISSUE THREAD

**Issue by ghost** [nodejs/help#2940]

**Comment by bnoordhuis** [comment]
In the category crude-but-effective hacks, here's one way of "deasyncifying" an async function:
```js
var f = async function(k) { return await k() }

var g = eval('(' + f.toString().replace(/\b(async|await)\b/g, '') + ')')

f(async () => console.log('from f'))
g(      () => console.log('from g'))
```
The more principled approach is to use a parser like https://www.npmjs.com/package/acorn to rewrite the AST but, honestly, a quick search and replace works 98% of the time.

**Comment by mike-litoris-96** [comment]
You misunderstood the question. The question is not how to deasyncify a function.

Let me try to explain better. I have a synchronous algorithm for traversing some data structure. The algorithm takes a function as argument and for each element of the structure it calls the function, passing the element as the argument to the function. The point is that the function may be asynchronous and the algorithm should not visit the next element until the previous promise returned by the function is resolved (in case of async function).

Your answer explains how to make async function sync, but I am failing to see how is that related to my question? Look at this pseudo code:

```js
class Structure {
  elements = [1, 2, 3];

  traverse (func) {
    for (const element of this.elements)
      func(element);
  }

  async traverseAsync (func) {
    for (const element of this.elements)
      await func(element);
  }
}

const struct = new Structure();

struct.traverse(elem => console.log(elem));

struct.traverseAsync(async elem => new Promise(x => {
  setTimeout(() => { console.log(elem); x(); }, 1000);
}));
```

Now imagine that `traverse` method has few thousands lines of code. Do we need to copy all of that into `traverseAsync`, or can we somehow merge the two methods without affecting the performance or code readability? What would be recommended here?

**Comment by bnoordhuis** [comment]
I think I understood your question alright because my answer remains the same. :-)
```js
const deasyncify = (f) => eval('(' + f.toString().replace(/\b(async|await)\b/g, '') + ')')

Structure.prototype.traverse = deasyncify(Structure.prototype.traverseAsync)
```
Think about it: the methods are identical except for the `async` and `await` keywords.

**Comment by PoojaDurgad** [comment]
@ghost - is this issue resolved?

**Comment by SlavKing98** [comment]
AFAIK ghost stands for a deleted user. They can't respond.

**Comment by PoojaDurgad** [comment]
closing!!
