### ISSUE TITLE
can nodejs embed sqlite3 like php?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#2941]
* **Node.js Version**: all
* **OS**: all
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: no

[node-sqlite3 needs more hands on the deck](https://github.com/mapbox/node-sqlite3/issues/1292)

**Comment by stoneRdev** [comment]
This would be nice, and very helpful to the server community, but would definitely need to be based on [Joshua Wise's](https://github.com/JoshuaWise/better-sqlite3) implementation, as his is by far the best around. But his has issues building on windows for me, so I was stuck using node-sqlite3 for windows and Joshua Wise's better-sqlite3 for other platforms, and had to write adapters so the code could switch between the two. That all could have been avoided with a native implementation of sqlite3, which I was very fond of back in the PHP days
