### ISSUE TITLE
Getting problem in installing Node.js

### ISSUE THREAD

**Issue by kardasvenkatesh** [nodejs/help#2942]
Iam unable to install Node.js on my machine getting issue as could not access network location *:\. Even though iam deleting all the old node files from system. Please help me to resolve this problem.

**Comment by PoojaDurgad** [comment]
@kardasvenkatesh , Can you elaborate the steps you performed and the results of each steps?

**Comment by kardasvenkatesh** [comment]
> @kardasvenkatesh , Can you elaborate the steps you performed and the results of each steps?

![Capturenode](https://user-images.githubusercontent.com/29150010/92123261-0e9dbb80-ee1a-11ea-9e90-16110f59a7a3.PNG)

After successful downloading node.js on (D: Drive) on my machine, when i try to install that getting issue as above.
After completing half laoding issue getting like this.

![Capturenode](https://user-images.githubusercontent.com/29150010/92123605-748a4300-ee1a-11ea-9273-8a8400aff167.PNG)

**Comment by kardasvenkatesh** [comment]
> @kardasvenkatesh , Can you elaborate the steps you performed and the results of each steps?


![Capturenode](https://user-images.githubusercontent.com/29150010/92224645-b9b48080-eebf-11ea-9342-0b4ee517def9.PNG)

After Downloading successfully getting error as above image

**Comment by PoojaDurgad** [comment]
@kardasvenkatesh ,The default location for installation of Node.js is C:\Program Files . The 'C' drive is actually where windows, network is located and D drive provides additional disk space so try to install in 'c' drive.

**Comment by PoojaDurgad** [comment]
@kardasvenkatesh ,~The default location for installation of Node.js is C:\Program Files . The 'C' drive is actually where windows, network is located and D drive provides additional disk space so try to install in 'c' drive.~ 

I tried to mimic the error you got by:
 - downlaoding the same installer,
 - shutting down my network connection,
 - and installing
it worked successfully, did not face any error whatsoever

**Comment by kardasvenkatesh** [comment]
> @kardasvenkatesh ,~The default location for installation of Node.js is C:\Program Files . The 'C' drive is actually where windows, network is located and D drive provides additional disk space so try to install in 'c' drive.~
> 
> I tried to mimic the error you got by:
> 
> * downlaoding the same installer,
> * shutting down my network connection,
> * and installing
>   it worked successfully, did not face any error whatsoever

Even  though iam following the above steps, the problem persists the same. Even though turned off my network and tried and but the problem didn't resolved.

**Comment by PoojaDurgad** [comment]
@kardasvenkatesh , when I searched for this error, I get this document. Not sure whether the instructions in the below document will resolve your issue or not, but may be worth giving a try?
- https://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/Error-1606-when-installing-2014-product.html

**Comment by PoojaDurgad** [comment]
inactive, closing!
