### ISSUE TITLE
I'm trying to install node.js v14.8.0 on my old laptop with 32-bit Linux installed.

### ISSUE THREAD

**Issue by Indexerrowaty** [nodejs/help#2943]
* **Node.js Version**: v14.8.0
* **OS**: Lubuntu 18.04
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**: Nah

Hello. I try to install node v14.8.0 on my 32-bit machine. Unfortunately I cannot find this version that is already pre built for i368 so I tried to build node.js from source. Unfortunately enough for me I can't build it because my old laptop turns off after some time without any reason. **Are there any pre-built versions of node.js 14.8.0 for 32-bit Linux** because as I said before I can't build node.js on my old laptop.

Any help is appreciated.

**Comment by bnoordhuis** [comment]
Short answer: no - we stopped providing linux-x86 binaries after Node.js v8.x

Longer answer: try cross-compilation with `./configure --dest-cpu=ia32`. Build on a beefier machine, then copy over the binary to your laptop.

You probably also want to run Ubuntu 18.04 on the beefy machine for maximum compatibility.

**Comment by Indexerrowaty** [comment]
I'm getting this error rn:

```
In file included from ../deps/zlib/contrib/optimizations/inffast_chunk.c:10:0:
../deps/zlib/contrib/optimizations/chunkcopy.h: In function ‘loadchunk’:
../deps/zlib/contrib/optimizations/chunkcopy.h:52:5: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
     const unsigned char FAR* s) {
     ^~~~~
In file included from ../deps/zlib/contrib/optimizations/chunkcopy.h:32:0,
                 from ../deps/zlib/contrib/optimizations/inffast_chunk.c:10:
../deps/zlib/contrib/optimizations/chunkcopy.h: In function ‘v_load64_dup’:
/usr/lib/gcc/x86_64-linux-gnu/7/include/emmintrin.h:630:1: error: inlining failed in call to always_inline ‘_mm_set1_epi64x’: target specific option mismatch
 _mm_set1_epi64x (long long __A)
 ^~~~~~~~~~~~~~~
In file included from ../deps/zlib/contrib/optimizations/inffast_chunk.c:10:0:
../deps/zlib/contrib/optimizations/chunkcopy.h:215:10: note: called from here
   return _mm_set1_epi64x(i64);
          ^~~~~~~~~~~~~~~~~~~~
deps/zlib/zlib.target.mk:109: recipe for target '/home/index/node/out/Release/obj.target/zlib/deps/zlib/contrib/optimizations/inffast_chunk.o' failed
make[1]: *** [/home/index/node/out/Release/obj.target/zlib/deps/zlib/contrib/optimizations/inffast_chunk.o] Error 1
make[1]: *** Oczekiwanie na niezakończone zadania....
rm 999054f89d37015a668a3c76f7c04c2221e2e92f.intermediate 725623f2044763a40de2d06cf3ae2fb68480ec02.intermediate
Makefile:104: recipe for target 'node' failed
make: *** [node] Error 2
```

**Comment by richardlau** [comment]
@Indexerrowaty You could see if https://github.com/nodejs/node/pull/33044 (which ports the gn build scripts for the Chromium fork of zlib to gyp) helps (there were reports that it helped others on 32-bit Linux). That PR is held up because it regresses relevant benchmarks.

**Comment by Indexerrowaty** [comment]
Worked. Thanks for help.
