### ISSUE TITLE
module isnt opening

### ISSUE THREAD

**Issue by miracle09** [nodejs/help#2944]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by addaleax** [comment]
Can you share any information, for example what you are doing and expected/actual results?

**Comment by miracle09** [comment]
C:\Users\Lenovo\Desktop\Angular>ng new project1
internal/modules/cjs/loader.js:328
      throw err;
      ^

Error: Cannot find module 'C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\symbol-observable\lib\index.js'. Please verify that the package.json has a valid "main" entry
[90m    at tryPackage (internal/modules/cjs/loader.js:320:19)[39m
[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:533:18)[39m
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:742:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:964:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\[4m@angular[24m\cli\lib\init.js:10:1)
[90m    at Module._compile (internal/modules/cjs/loader.js:1075:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:940:32)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  path: [32m'C:\\Users\\Lenovo\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\symbol-observable\\package.json'[39m,
  requestPath: [32m'symbol-observable'[39m
}
______________________________________________________________
this is cmd actual error......can you troubleshoot it please...!!!!!

**Comment by miracle09** [comment]
It's solved...!!🥳🥳🥳

**Comment by Mozhgan-Hatami** [comment]
I have this issue, too 
Can you tell me please, how did you solve it?
