### ISSUE TITLE
command syntax is not correct.

### ISSUE THREAD

**Issue by torric0** [nodejs/help#2945]
### i got nodejs installed but i have problems with npm

* **Version: v12.18.3**:
* **Platform: 64-bit (Windows)**:
* **Subsystem**:

### when i wrote npm (something) i got
command syntax is not correct.
command syntax is not correct.
command syntax is not correct.
not expected /F at this time

### what should be shown? 
it should show npm version if i wrote npm -v or whatever i want to do

### What do you see instead?
La sintaxis del comando no es correcta.
La sintaxis del comando no es correcta.
La sintaxis del comando no es correcta.
No se esperaba /F en este momento.

### Additional information: 
i install nodejs twice and the problem persist, it has the files but i don´t know why that happened

**Comment by PoojaDurgad** [comment]
@torric0 - can you refer this https://github.com/nodejs/help/issues/379 , hope it helps

**Comment by PoojaDurgad** [comment]
inactive. closing
