### ISSUE TITLE
Node.js Worker Thread Support Sockets?

### ISSUE THREAD

**Issue by muhammadfahad93** [nodejs/help#2949]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by PoojaDurgad** [comment]
@muhammadfahad93 ,Can you please elaborate your issue.Please fill-in the template issuse.

**Comment by muhammadfahad93** [comment]
@PoojaDurgad  okay, Mainly my questions is about to know about does Nodejs worker thread support socket-based communication?.

Node.js Version:  v12.14.1
OS: Window 10
Scope (install, code, runtime, meta, other?):

Module (and version) (if relevant):
  "dependencies": {
    "express": "^4.17.1",
    "node-schedule": "^1.3.2",
    "request": "^2.88.2",
    "socket.io": "^2.3.0",
    "ws": "^7.3.1"
  }

Currently, When the express application starts it create number of thread worker dependent on the settings. It also starts the socket server.  My goal is to fetch data in the worker thread. Run a number of evaluation on it and if data matching some conditions sending it socket which will emit it front end application . But when worker thread call the socketApi.sendNotification function nothing get emitted. But if i use rest end  point to emit it works fine

app.js
//change nodejs time
process.env.TZ = "America/Chicago";

console.log("new Date ", new Date());
var app = require("express")();
var http = require("http").createServer(app);

const { Worker } = require("worker_threads");
const path = require("path");
var socketApi = require("./socket/appsocket.js");
const { clear } = require("console");
//for the stock setting
const symbolSetting = [{ symbol: "AAPL" }];

// const symbolSetting = [
//   { symbol: "IBM" },
//   { symbol: "AAPL" },
//   { symbol: "AMZN" },
// ];
//for the work instance
const worker = [];
// create some big array
const elements = 1000000;
const bigArray = Array(elements)
  .fill()
  .map(() => Math.random());

//const myEmitter = new MyEmitter();

//starting socket server
socketApi.startSocket(http);
// we get the path of the script
const workerScript = path.join(__dirname, "./worker/worker.js");

//startTrading function to start trading and creating required threads
// create a new worker from our script base on setting object
function startTrading() {
  for (const i in symbolSetting) {
    worker[i] = new Worker(workerScript, { workerData: [symbolSetting[i]] });
    worker[i].on("error", (error) => console.error("error", error));
    //listenToWorker(worker[i]);
  }
  // for (let i = 0; i < 50; i++) {
  //   worker[i] = new Worker(workerScript, { workerData: [symbolSetting[0], i] });
  //   worker[i].on("error", (error) => console.error("error", error));
  //   listenToWorker(worker[i]);
  // }
}

//stopTrading functions to stop trading at any moment
// create a new worker from our script base on setting object
function stopTrading() {
  for (const i in symbolSetting) worker[i].terminate();
}

// listenToWorker receive events from the worker
function listenToWorker(workerInstance) {
  workerInstance.on("message", (sortedArray) =>
    console.log("message:", sortedArray[0])
  );
  workerInstance.on("error", (error) => console.error("error", error));
  workerInstance.on("exit", () => console.log("exit"));
}

startTrading();
socketApi.sendNotification("AAPL", "working hard");
// setInterval(() => {
//   const used = process.memoryUsage().heapUsed / 1024 / 1024;
//   console.log(`Main app ${Math.round(used * 100) / 100} MB`);
// }, 65000);

// myEmitter.on("stopTrading", function (a) {
//   for (const i in symbolSetting) worker[i].terminate();
// });
// writing callback for the API callback
app.get("/", (req, res) => {
  console.log("req", req);
  res.send("<h1>TAP Stock backend is working</h1>");
});

app.get("/callback", (req, res) => {
  socketApi.sendNotification("msg", "working hahah hard");
  res.send("<h1>done</h1>");
});
app.get("/sockets", (req, res) => {
  console.log("get", req);
  res.send("<h1>done</h1>");
});

app.post("/callback", (req, res) => {
  console.log("post done", req);
  res.send("<h1>post done</h1>");
});

http.listen(3000, () => {
  console.log("listening on *:3000");
});


/************************appsocket.js
const socket_io = require("socket.io");
const port = process.env.SOCKET_PORT || 4000;
const socketApi = {};
const io = socket_io();
var conn = [];
console.log("Date", new Date());

socketApi.startSocket = function (server) {
  io.on("connection", function (socket) {
    console.log("A user connected");
    conn[socket.id] = socket;
    //console.log("socket", socket);
    // let counter = 0;
    // setInterval(() => {
    //   socket.emit("AAPL", ++counter);
    // }, 1000);
    //socket.emit("msg", { msg: "connected" });
  });

  //if (!process.env.SOCKET_STANDLONE)
  io.listen(port);
};
// setInterval(() => {
//   io.sockets.emit("AAPL", { msg: "dsfsadsfsa" });
// }, 1000);
socketApi.sendNotification = function (topic, data) {
  console.log("socketApi", topic, data);
  // io.sockets.emit("AAPL", { msg: data });
  // io.emit("AAPL", { msg: data });
  try {
    console.log("io", io);
    io.sockets.emit("msg", { msg: "connected" });
    io.emit("msg", { msg: data });
  } catch (e) {
    console.log("entering catch block");
    console.log(e);
    console.log("leaving catch block");
  }
};
socketApi.io = io;
module.exports = socketApi;

************************************************* worker.js
const schedule = require("node-schedule");
const { parentPort, workerData, isMainThread } = require("worker_threads");
const request = require("request");

var socketApi = require("../socket/appsocket.js");
console.log("workerData", workerData);

// CPU consuming function (sorting a big array)
function sortBigArray(bigArray) {
  return bigArray.sort((a, b) => a - b);
}

setTimeout(function () {
  socketApi.sendNotification("msg", workerData);
}, 10000);
// check that the sorter was called as a worker thread
if (!isMainThread) {
  // make sure we got an array of data
  if (!Array.isArray(workerData)) {
    // we can throw an error to emit the "error" event from the worker
    throw new Error("workerData must be an array of numbers");
  }
}
var from = new Date(1572651390).getTime();
var to = new Date(1572651390).getTime();
//setting the job schedular
var j = schedule.scheduleJob("* * * * *", function () {
  to = new Date(to).setMinutes(new Date(to).getMinutes() + 1);
  request(
    `https://finnhub.io/api/v1/stock/candle?symbol=${workerData[0].symbol}&resolution=1&from=${from}&to=${to}&token=`,
    { json: true },
    (err, res, body) => {
      if (err) {
        return console.log(err);
      }
      console.log("s", body.s);
      if (body.s == "ok") {
        from = to;
        console.log(
          workerData[0],
          " ",
          workerData[1],
          "CLOSE LENGTH",
          body.c.length
        );

        socketApi.sendNotification(workerData[0].symbol, body);

        const used = process.memoryUsage().heapUsed / 1024 / 1024;
        console.log(`${workerData[1]} ${Math.round(used * 100) / 100} MB`);
        //);
      }
    }
  );
  // we post a message through the parent port, to emit the "message" event
  parentPort.postMessage(sortBigArray(workerData));
});


Just want to clearify that worker thread can socket for communction ?

**Comment by PoojaDurgad** [comment]
@muhammadfahad93 , I think the socket created in the main thread is not visible in the worker thread and hence you see this behaviour. Is it possible to pass the same socket object as a messege to the worker, instead of requiring the socket object, and try?
I don't have deeper insight into the issue, so please ignore my suggestion, if it does not work

**Comment by PoojaDurgad** [comment]
inactive, closing!

**Comment by nomankt** [comment]
+1
