### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by MugeshBTech** [nodejs/help#295]
D:\Mugesh\SAMPLES\Node Samples\createServer>tsd query node express --action install
'tsd' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Trott** [comment]
It looks like you are trying to use TypeScript. You can try running `npm install -g tsd` and seeing if that fixes your issue. If not, please seek help in a TypeScript support forum. You might try [the TypeScript repo](https://github.com/Microsoft/TypeScript) but it appears that the project suggests using [StackOverflow](http://stackoverflow.com/questions/tagged/typescript) for general help questions.
