### ISSUE TITLE
now what?

### ISSUE THREAD

**Issue by cellurl3** [nodejs/help#2950]
![image](https://user-images.githubusercontent.com/53091899/91743631-b8145100-eb7d-11ea-8e13-687a6a30359f.png)

**Comment by cellurl3** [comment]
this is where i suffer in silence. Interface question. No one ever cares about each other.....

**Comment by DerekNonGeneric** [comment]
You may want to consider using the issue template. This partial screenshot provides very little context.

**Comment by cellurl3** [comment]
i am at work and i cant use npm.   I dont know any more than that screenshot.  Thanks

**Comment by ORESoftware** [comment]
now what? answer: you will suffer. 😋

that is the code life
