### ISSUE TITLE
Downloading NodeJS on MacBook

### ISSUE THREAD

**Issue by code-good-life** [nodejs/help#2951]
Hi. I downloaded NodeJS 12.18.3 LTS and NodeJS 14.9.0 Current on a MacBook. However, after the download and installation it was impossible to locate. What do I do?

**Comment by PoojaDurgad** [comment]
> it was impossible to locate
@code-good-life , I am assuming  that you are talking about missing installers .Is this correct?
typically those are located in download folder by the name node-v12.18.3.pkg and node-v14.9.0.pkg can you confirm it

**Comment by PoojaDurgad** [comment]
inactive . closing !!
