### ISSUE TITLE
Does node still have optimizations for high concurrency?

### ISSUE THREAD

**Issue by sbfkcel** [nodejs/help#2953]
Does node still have optimizations for high concurrency?
It performs very well in the web field, but its concurrent processing capability in the game field is much worse than erlang.

If the concurrent performance can be improved a lot, it will be a normal and good game full-stack solution.

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because your question is too broad and open-ended to be a good fit for the bug tracker. If you have specific feature requests or suggestions for improvement, please file new issues.

**Comment by gireeshpunathil** [comment]
@sbfkcel - is this still outstanding? as already suggested, if there are:

 - specific ideas,
 - specific areas of concern,
 - specific API / capability observed as performing sub-optimal
 - specific numbers to compare with erlang
 
etc. , then this can be taken forward.

Hope this helps!

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
