### ISSUE TITLE
Node.js Installation Issue

### ISSUE THREAD

**Issue by kardasvenkatesh** [nodejs/help#2956]
Hi team,
Iam unable to install node.js on system. While installing iam facing an issue which i attached below
![Capturenode](https://user-images.githubusercontent.com/29150010/92203102-01c2ab80-ee9e-11ea-982a-e70bbe7927bd.PNG)

Thank You!

**Comment by PoojaDurgad** [comment]
@kardasvenkatesh - isn't this issue same as #2942? if so, pls close this?

**Comment by PoojaDurgad** [comment]
no response , closing this issue as it is same as https://github.com/nodejs/help/issues/2942
