### ISSUE TITLE
Doesnot support node 

### ISSUE THREAD

**Issue by Estehsan** [nodejs/help#2957]
npm WARN npm npm does not support Node.js v12.18.3
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AALA\AppData\Roaming\npm-cache\_logs\2020-09-04T10_57_49_082Z-debug.log

**Comment by PoojaDurgad** [comment]
@Estehsan , can you provide the content of  C:\Users\AALA\AppData\Roaming\npm-cache_logs\2020-09-04T10_57_49_082Z-debug.log  file to debug your error.

**Comment by PoojaDurgad** [comment]
inactive. closing!!
