### ISSUE TITLE
events.js:291       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by MuDzYNN** [nodejs/help#2958]
* **Node.js Version**: v14.5.0
* **OS**: Debian 9
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: I don't know

Error:
```
events.js:291
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 127.0.0.1:30120
[90m    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)[39m
Emitted 'error' event on ClientRequest instance at:
[90m    at Socket.socketErrorListener (_http_client.js:469:9)[39m
[90m    at Socket.emit (events.js:314:20)[39m
[90m    at emitErrorNT (internal/streams/destroy.js:100:8)[39m
[90m    at emitErrorCloseNT (internal/streams/destroy.js:68:3)[39m
[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)[39m {
  errno: [33m-111[39m,
  code: [32m'ECONNREFUSED'[39m,
  syscall: [32m'connect'[39m,
  address: [32m'127.0.0.1'[39m,
  port: [33m30120[39m
}
```

I got this error from this part of code:
```js
var onlinePlayers = 0;

function MakeRequest() {
	try {
		var http = require('http');

		var options = {
			host: '127.0.0.1',
			port: '30120',
			path: '/players.json'
		};

		callback = function(response) {
			var str = '';

			response.on('data', function (chunk) {
				str += chunk;
			});

			response.on('end', function () {
				let players = 0;
				for (letter of str) {
					if (letter == "{") {
						players++;
					}
				}
				onlinePlayers = players;
			});
		}

		http.request(options, callback).end();
	} catch (error) {
		console.log(error);
	}
}


function SetStatusAndStats() {
    setTimeout(function () {
		MakeRequest();

		setTimeout(function () {
			client.user.setActivity(onlinePlayers +' graczy'); //Discord.js
			SetStatusAndStats();
		}, 1500);
	}, 10000);
}
```

How can i fix it? This error is random, it occurs at different intervals.

**Comment by dark-magic** [comment]
`Error: connect ECONNREFUSED 127.0.0.1:30120` this means you either connect to the wrong host/port or the error is on the serverside.

**Comment by MuDzYNN** [comment]
It's very random. This script running 24/7 and sometime i have this problem. But I changed HTTP request method + used .catch and i think it's working

**Comment by hotboyer** [comment]
const express = require("express");
const bodyParser = require("body-parser");
const request = require("request");
const https = require("https");


const app = express();

app.use(express.static("public"));
app.use(bodyParser.urlencoded({extended: true}));


app.get("/", function(req, res) {
res.sendFile(__dirname + "/signup.html")
});

app.post("/", function(req, res) {
    const firstName = (req.body.first_name);
    const lastName = (req.body.last_name);
    const email = (req.body.email);
    const data = {
        members: [
            {
                email_address: email,
                status: "subscribed",
                merge_fields: {
                    FNAME: firstName,
                    LNAME: lastName,
                }

            }
        ]
    };

    const jsonData = JSON.stringify(data);
    const url = "https://us13.api.mailchimp.com/3.0/lists/e598f4082b";

    const options = {
        method: "POST",
        auth: "Pinnacle:c72360e0a9e0b0039a7e9874ce26ee88-us13"
    }
    
    const request = https.get(url, options, function(response) {
        response.on(data, function (data) {
            console.log(JSON.parse(data));
        })
    });
    console.log(request)

    request.write(jsonData); 
    request.end();

})


app.listen(3000, function() {
    console.log("server is running on port 3000");
})







I've been trying to run this code ever since and my nodemon app keeps crashing.
