### ISSUE TITLE
Nodemon causes issue while starting the server. This critical issue needs a fix

### ISSUE THREAD

**Issue by lopeselio** [nodejs/help#2959]
λ nodemon server
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server`
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\Elio\Desktop\github\muzik\server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[nodemon] app crashed - waiting for file changes before starting...

## I've tried deleting node-modules and npm install.  Not fixed yet.

![Capture](https://user-images.githubusercontent.com/43913734/92318892-1d5dbb80-f030-11ea-94ba-e1d5e17babd9.PNG)

**Comment by RaisinTen** [comment]
You need to pass a valid file path for the script you want to run using nodemon. In this case, `nodemon server/server.js` assuming that you're trying to run this: https://github.com/MUZIK-IWP/MUZIK.

**Comment by RaisinTen** [comment]
Feel free to reopen, if you're still in doubt.

**Comment by Muhammadcodes112** [comment]
This was very helpful, Thanks a lot
