### ISSUE TITLE
Error-throwing bug

### ISSUE THREAD

**Issue by Matto58** [nodejs/help#2961]
Whenever I run a program with a coding mistake, instead of erroring the line where the mistake is, Node.js, instead, gives an error about line:
```js
throw err;
```
_PS: it only does that sometimes_

* **Node.js Version**: 14.7.0
* **OS**: Windows 10 version 1909 build 18363.1016
* **Scope (install, code, runtime, meta, other?)**: Any program I run in Node.js
* **Module (and version) (if relevant)**: None

**Comment by addaleax** [comment]
Can you share a full example with output, and what you would expect to be different about that output?

By default, in a situation like `throw err`, Node.js should print both the line of the throw (i.e. where the uncaught exception came from) and the stack trace for when the error was originally created.

**Comment by Matto58** [comment]
Sadly, I cannot. It's simply very rare to get me at this point.
Here are all the lines, which are attempts to trigger this bug:

```js
c
console.pog();
for(e====dede==)
int
```

**Comment by PoojaDurgad** [comment]
@Matto58 - is this still outstanding?
> Whenever I run a program with a coding mistake, instead of erroring the line where the mistake is, Node.js, instead, gives an error about line:

I run the code what you provided, it prints where the uncaught exception occurred and also stack trace when the error originated instead of your output.

**Comment by PoojaDurgad** [comment]
closing as inactive!! feel free to re-open the issue if its still outstanding

**Comment by Matto58** [comment]
Welp, it happened again, again it pointed to `throw err;` but this time I managed to capture it! But now I know the actual cause of it.
```
PS C:\Users\Think\Desktop\Matto\old english proglang> node i      
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Think\Desktop\Matto\old english proglang\i'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
FYI: I have 2 files inside this folder: i.oe and i.oe.js.
