### ISSUE TITLE
FFI and Garbage Collection

### ISSUE THREAD

**Issue by jmacmahon** [nodejs/help#2962]
* **Node.js Version**: 10
* **OS**: GNU/Linux
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: `node-ffi`

I hypothetically have some code which fills a Buffer with bytes, and then passes that out to an FFI function:

```
const ffi = require('ffi')
const ref = require('ref')
const ArrayType = require('ref-array')

const Uint8Array = ArrayType(ref.types.uint8)

const someLibrary = ffi.Library('/some/foreign/library.so', {
  receiveBuffer: [ref.types.void, [Uint8Array, ref.types.size_t]]
})

function doStuff (inputStr) {
  const buf = Buffer.from(inputStr, 'utf-8')
  const pointer = new Uint8Array(buf)

  someLibrary.receiveBuffer(pointer.buffer, pointer.length)
}

doStuff('🙈')
doStuff('🙉')
doStuff('🙊')
```

I want each version of the Buffer `buf` to be garbage collected at some point, because I'm calling the function multiple times and don't want to cause a memory leak, but I also don't want it to be garbage collected "too soon", because the foreign function in the library needs to read it.

So my question is at what point, if at all, does the Buffer `buf` get garbage-collected, and how can I make sure it's in the right place?

**Comment by gireeshpunathil** [comment]
@jmacmahon - is this still outstanding? IIUC, the object `buf` is garbage collected not because the function is called repeated times, but it is defined in the function scope. And the eligibility (for gc) is attained as soon as the function returns (because the object goes out of scope on function return)

does it make sense to you?

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
