### ISSUE TITLE
No start line

### ISSUE THREAD

**Issue by ManojRakshu** [nodejs/help#2964]
* **12.18.3**:
* **Windows 10 64 bit**:

### I had a problem in my expo sdk, so that i thought of deleting node modules and package-lock.json files and then again i run node install command. If i try to do that then I'm getting "11668 error code ERR_OSSL_PEM_NO_START_LINE
11669 error error:0909006C:PEM routines:get_name:no start line" this error.

### What is the expected behavior?

Install node modules and start the apk

### What do you see instead?

Error 
11668 error code ERR_OSSL_PEM_NO_START_LINE
11669 error error:0909006C:PEM routines:get_name:no start line

**Comment by bnoordhuis** [comment]
You're trying to load something as a PEM file (like a TLS certificate, or a key) which isn't actually proper PEM. PEM files look like this:
```
-----BEGIN CERTIFICATE-----
<base64-encoded data>
-----END CERTIFICATE-----
```

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
