### ISSUE TITLE
When detached spawnned python server restarts,it opens a terminal window in windows OS.

### ISSUE THREAD

**Issue by harshkoralwala** [nodejs/help#2966]
Hello all,

I am creating an Electron desktop application. There is a requirement of starting the python server from a desktop application.so for that, I have used node's spawn class.

There is a feature(button) to restart the server from the application. So on click of it, the API called and the server restarts itself.

But the issue in windows OS is that when a server started by a desktop application and the server restarts itself, a terminal window opens.

Below is the code I have used to start the detached server.
```
let spawn = window['require']('child_process').spawn;
  const out = this.fs.openSync('file location here', 'w');  
 const subprocess = spawn("server0.0.1.exe", [ "-p", 2500, "-ip","localhost"],
          {
            detached: true,
            windowsHide: true,
            stdio: ['ignore', out, out]
          });
        subprocess.unref();
```

When the server starts for the first time no terminal window opened and it's perfect.

I have used '_windowsHide_' property still why terminal window opened on the restart server?

When the server installed system, entry to the system environment variable(PATH) also done. So server0.0.1.exe command will be found and it also works fine.

When I click on the restart server button from application, the below the window is opened.where the title bar shows the location of the server0.0.1.exe location.

![popup_window](https://user-images.githubusercontent.com/33347464/92473835-c2c38b80-f1f8-11ea-9054-e5219f51bbff.png)

If I close this terminal window then my server also gets closed. So it is compulsory for me to keep open this terminal window and it gives a really bad experience.

All application functionality works fine when this terminal window is open.

So how can I hide this window?

`node version :v10.22.0`

Kindly help.

Thankx in advance

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because I doubt this is an issue with Node.js itself. It might be an issue with Electron's integration of Node.js.

**Comment by gireeshpunathil** [comment]
@harshkoralwala - can you also add (for debugging purpose) the options
`shell: false`, and / or `stdio: inherit` and see if it makes any difference?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
