### ISSUE TITLE
npm installation

### ISSUE THREAD

**Issue by shahebaz-wandrick** [nodejs/help#2969]
* **Node.js Version**: v12.18.3
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**: While using in vs code

I am getting following error

![error in npm](https://user-images.githubusercontent.com/10008400/92498897-dde7c880-f203-11ea-8bb4-9b882fca1498.jpg)

I am providing my log file also
[2020-09-08T15_34_50_545Z-debug.log](https://github.com/nodejs/help/files/5189390/2020-09-08T15_34_50_545Z-debug.log)

Can anyone can help me with this.

Regards,

Shahebaz Wandrick

**Comment by addaleax** [comment]
Can you report this at https://github.com/npm/cli/issues?

Also, I have no idea if this is the case, but maybe it helps if the directory you’re working in doesn’t contain spaces. It would obviously still be a bug if that was the cause, but unfortunately, spaces in directory names are a common source of problems.

**Comment by PoojaDurgad** [comment]
@shahebaz-wandrick - is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
