### ISSUE TITLE
Node JS command prompt bad display - how to switch back to windows cmd?

### ISSUE THREAD

**Issue by Kaddath-R** [nodejs/help#297]
Hi,

I am sorry if this problem has been answered already, i have been searching a lot of time without finding anything, and cannot take more on the company time for this.. (I first submitted the issue on npm repo and was told it was not npm, so i post it here).
I did the mistake to choose NodeJS command prompt window at the installation, and it is kind of buggued: the display is not correct (displays a serie of numbers for ionic build instead of what is done for example), but the most important is that this NodeJS window closes as soon as execution finished. It means i cannot see versions when i ask, cannot read logs and so on. (Windows 10 family edition)
Is there a way to configure it again to switch back to windows cmd? I tried to search for that, didn't find, tried to uninstall, did nothing. Sorry for being a noob about this, but it blocks me currently for debugging reasons.

Can someone help me?
Kaddath.

**Comment by addaleax** [comment]
> displays a serie of numbers for ionic build instead of what is done for example

I think I’ve seen a bug like that … do your problems still occur with the latest Node.js version?

(sorry I’m not really going to much of a help here as a non-Windows person =/)

**Comment by Kaddath-R** [comment]
Yes, there is already an issue about that (the numbers for ionic build) in the node bug repo, but there was no solution found yet. Your answer gave me a little clue for that, as i had installed the last version and already tried to uninstall/reinstall, but with the same version. I just downgraded to the last stable version (the one recommended for most users) and the numbers are now relevant text again.
But unfortunately the main problem is still there, when i use the node js command prompt for doing stuff, it still opens another window (Node JS, without the command prompt label) for the execution, and that window closes so quick i cannot read the logs. Even for a basic command as "npm -v".. any clue?

**Comment by Kaddath-R** [comment]
After a lot of searching, i found the solution by trying to solve something else:
the Node command prompt was not set to run as an Administrator, probably because i uninstalled/reinstalled at some moment in the past.
If that can help someone else... now it shows the logs in the same window and i can read them again.
