### ISSUE TITLE
Running MSI installer in Windows 10, but status never progresses.

### ISSUE THREAD

**Issue by oteboy** [nodejs/help#2972]
* 12.18.3:
* Windows 10:
* install:

Trying to install Node.js using node-v12.18.3-x64.msi installer using all default install options, but after I click 'Install' button, the status never progresses.  Just sits at the screen shot below, and there is not error in Event Viewer.  I have to kill everything in Task Manager and restart PC to be able to run installer again, but the same thing continues to occur.  I've searched hi and low, but seem to me the only person having an issue like this.  Any suggestions?

![image](https://user-images.githubusercontent.com/68923127/92617011-e33d2580-f28c-11ea-84c4-6b2855591ee2.png)

**Comment by PoojaDurgad** [comment]
@oteboy - For your issue probably make sure that you don't have any previous installed nodejs version on your system and try to disable the network connection  or antivirus and try to install it.

**Comment by riskycase** [comment]
Have you granted the installer the permissions? I experience this quite often where the User Access Control prompt takes too long to show up...

Possibly try right clicking and selecting `Run As Administrator`

**Comment by PoojaDurgad** [comment]
closing as answered . please feel free to re-open the issue if its still an issue.
