### ISSUE TITLE
Why isn't process.stdout an instanceof fs.WriteStream?

### ISSUE THREAD

**Issue by Thomazella** [nodejs/help#2973]
* **Node.js Version**: 14.9.0
* **OS**: Linux Arch7 5.8.7-arch1-1 #1 SMP PREEMPT Sat, 05 Sep 2020 12:31:32 +0000 x86_64 GNU/Linux
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: fs

```js
> let s = require('fs').WriteStream
undefined
> s
[Function: WriteStream]
> process.stdout instanceof s
false
> process.stdout
<ref *1> WriteStream {
 ...
> process.stdout.constructor.name
'WriteStream'
```

this is confusing because process.stdout __appears__ to be a WriteStream as far as I can tell.

**Comment by devsnek** [comment]
It is a WriteStream, just not a fs WriteStream. Check out https://nodejs.org/api/tty.html#tty_class_tty_writestream.
