### ISSUE TITLE
cant install angular/cli

### ISSUE THREAD

**Issue by phileinSophos** [nodejs/help#2978]
While trying to install angular/cli using following command

`npm install -g @angular/cli
`

i am getting followning error

`npm ERR! Unexpected end of JSON input while parsing near '...AQBQJbymRHCRA9TVsSAnZ'
`

**Comment by PoojaDurgad** [comment]
@phileinSophos - I also faced the same issue while installing dependencies, IMO intermittent network connection may lead to this error. If that is the case, clear the npm cache and  try to install the dependencies with good network connection.

**Comment by PoojaDurgad** [comment]
inactive. closing !!!
