### ISSUE TITLE
HandleScope woes in v8 using low-level audio callback that needs to return values to a js function

### ISSUE THREAD

**Issue by ilzxc** [nodejs/help#298]
Forgive me for a wall of text, but this is a rather specific use-case that is giving me trouble. I reviewed v8 docs, created a handful of tests to ensure things are working correctly, but issues pop up when assembling.

```
$ node --version
v6.5.0
$ node-gyp --version
v3.4.0
```

I'm working on an audio system for Node.js, currently testing with portAudio. Defining the callback & getting audio out from Node is not a problem (I can assure you that linking with PortAudio and getting an audio callback executed in Node is well-tested). The issue arises when I need to:

* bring audio vector data into node;
* call a user-defined js function that will forward the audio data from the portAudio callback into Node.

----

I create a new `Isolate` during initialization to be used by the audio callback (that will be used in an audio callback on a high-priority audio thread):

```cpp
Isolate::CreateParams cp;
cp.array_buffer_allocator = new AudiioArrayBufferAllocator();
auto callbackIsolate = Isolate::New( cp );
std::cout << "storing function ...\n";
callback.Reset( callbackIsolate, Local< Function >::Cast( args[ 5 ] ) );
```

where `callback` is

```cpp
Persistent< Function > callback; 
// js function to hand the audio input to
```

We can test this callback from within the initialization function as follows:

```cpp
/// test the callback:
// https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/
auto callbackHandle = Local< Function >::New( isolate, callback ); 
// define function arguments & call the function:
Local< Value > arguments[] = { Number::New( isolate, 3.14159 ) };
callbackHandle->Call( Null( isolate ), 1, arguments );
```

Calling the function from Node results in:

```javascript
a = require('./build/Release/audiio');
{ audioDeviceInfo: [Function: audioDeviceInfo],
  initialize: [Function: initialize],
  wrapup: [Function: wrapup],
  updateBuffer: [Function: updateBuffer] }
> a.initialize(2, 2, 44100, 1024, '', function(v){ console.log(v); });
storing function ...
2016-09-19 12:40:08.325 node[39985:4071059] 12:40:08.325 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
3.14159
```

(The bit of text is due to portAudio and it doesn't matter, but useful to see that PortAudio gears are churning...)

In the PortAudio Callback, we need to call the JS function that will (eventually) receive the array of sample values from the input. I'm including the full code here. Note that userData passed to the audio callback is given the callbackIsolate I have defined during the initialization.

```cpp
static int nodeAudioCallback( const    void* input,
                                       void* output,
                              unsigned long numFrames,
                              const    PaStreamCallbackTimeInfo* /* timeInfo */,
                                       PaStreamCallbackFlags /* staticFlags */,
                                       void* userData )
{
    auto isolate = static_cast< Isolate* >( userData );
    std::cout << "static_cast< Isolate* > ok.\n";
    Isolate::Scope isolateScope( isolate );
    std::cout << "Isolate::Scope ok\n";
    std::cout << "isolate is " << ( ( isolate == nullptr ) ? "" : "NOT" ) << " nullptr\n";

    Locker lock( isolate );
    HandleScope scope( isolate );
    std::cout << "Locker lock( isolate ) ok.\n";

    // 2. forward the input buffer into the Node callback:
    Local< Value > result[] = { Number::New( isolate, 3.14159 ) };

    std::cout << "Generating a local callbackHandle ... \n";
    auto callbackHandle = Local< Function >::New( isolate, callback );
    std::cout << "Attempting to call the local callbackHandle... \n";
    auto returned = callbackHandle->Call( Null( isolate ), 1, result );
}
```

I'm certain that I'm the one being the idiot here, but the error message is somewhat mystifying and I'm not sure how to fix:

```
> a = require('./build/Release/audiio');
{ audioDeviceInfo: [Function: audioDeviceInfo],
  initialize: [Function: initialize],
  wrapup: [Function: wrapup],
  updateBuffer: [Function: updateBuffer] }
> a.initialize(2, 2, 44100, 1024, '', function(v){ console.log(v); });
storing function ...
2016-09-19 12:56:31.341 node[40063:4089863] 12:56:31.341 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
3.14159
undefined
> static_cast< Isolate* > ok.
Isolate::Scope ok
isolate is NOT nullptr
Locker lock( isolate ) ok.
Generating a local callbackHandle ... 
Attempting to call the local callbackHandle... 

#
# Fatal error in v8::HandleScope::CreateHandle()
# Cannot create a handle without a HandleScope
#

Illegal instruction: 4
```

It seems to me that the `HandleScope` that the error message refers to must be different from one I defined in the callback function above.

Tried to:

* Enter the `callbackIsolate` in initialization & define a `HandleScope` prior to calling `callback.Reset` (no change)
* Tried changing the function call to a `MaybeValue`-returning call that takes a context, which resulted in Bus Error: 10, which means I'm really messing things up with memory access.

Since I'm asking for help with a rather particular thing, full code that I have [can be seen in a gist here](https://gist.github.com/ilzxc/7ebda4f61e844804459d1fc3fa72f1e4) -- but I'm also rather self-conscious asking others to look at a bunch of code.

Any advice would be sincerely appreciated.

**Comment by bnoordhuis** [comment]
Are you calling a function from one isolate in another isolate?  That is not going to work, JS values (including functions) are intrinsically tied to the isolate they are created in.

**Comment by ilzxc** [comment]
Ben: Thank you very much for responding. I realized I had a bit more homework to do, so I ended up isolating the problem into a smaller toy example. The new question is: if portAudio (or any other audio library) is calling the C/C++ callback using the hardware interrupt, and I would need to get some data from that callback into Node's main event loop, what would be the best approach for this?

(I've looked at a number of things, but in all of the examples, there's a `libuv` worker that spawns the worker thread. I'm thinking of providing a FIFO queue for getting the data I'd need from the audio callback into Node.)

**Comment by bnoordhuis** [comment]
You could create a `uv_async_t` handle at start-up with `uv_async_init()` and then use `uv_async_send()` to wake up the event loop from another thread.  You can then safely call into the VM from the callback because it runs on the main thread.

**Comment by ilzxc** [comment]
Thank you very much for pointing me to the right direction, and thank you for the note that is attributed to you in the libuv book on inter-thread communication. This solved my issues.
