### ISSUE TITLE
what ecmascript, C, C++ version is nodejs written by?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#2980]
if i know those, i can better understand nodejs source code. i hope, in every source code file, tag ecmascript, C, C++ version.

**Comment by anlexN** [comment]
@Himself65 you don't understand my meanings, i say source code syntax problem, not toolchains problem. for example, nodejs use C++17, or other C++ version?

**Comment by bnoordhuis** [comment]
Node.js builds with `-std=gnu++1y` - C++14 with some extras. I expect it to move to C++17 in the not too distant future.

**Comment by anlexN** [comment]
i think if use C++20, nodejs source code size can be decreased very much.

**Comment by RaisinTen** [comment]
Closing this as it is answered already.
