### ISSUE TITLE
Missing dependency in the armv7 release of node v12.18.3

### ISSUE THREAD

**Issue by mugi-luffy** [nodejs/help#2981]
* **Version**: v12.18.3
* **Platform**: ARMv7

Running node on an embedded linux device produces the following error:

`node-v12.18.3-linux-armv7l/bin/node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

I used the official binaries from here: https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-armv7l.tar.gz

Previous versions (like v10.22.0 and v11.15.0) worked without a problem.

**Comment by mugi-luffy** [comment]
ok thanks, will try.

**Comment by codestorycooked** [comment]
Hi  @mugi-luffy ,
I am getting the same error and exactly in same situation where hardware vendor has linux 4.1.5 and none of the commands work to install libatomic. When i run existing arm7 package provided by node js , it gives me same error. Did you remove those two lines? Did it work for you? What else did you try?

Thanks
kunal
