### ISSUE TITLE
Node Caching DNS (improperly??)

### ISSUE THREAD

**Issue by edgework** [nodejs/help#2983]
Node Version  v12.17.0
OS:  Ubuntu 14.x and 16.x

We've been running on Node since 4.x  for everything.  We use DNS to move services from one server (HAP) to another if we need to do some maintenance on a group of servers.  We run HAProxy in front of many server instances all running Node apps.  Moving a service from one to the other is done through a DNS change then waiting a bit for everything to start sending requests to the new server group.  That's worked great for us on 4.x 6.x and 8.x.  We haven't done this since moving to Node 12.x ...

Today we did a switch and it didn't completely work.  Clients were still trying to get to the old server even though the DNS was updated and verified on the client machines via a ping and nslookup from an SSH session. BUT using a test interface on the running node client processes we saw they're still going to the old address.  This persisted even after the TTL set on the A record expired and then hours later.  Most, but not all client processes just got stuck on the old address.  A restart of the process solves the issue.

Is Node caching DNS now? If so is there a way to tell Node not to do that?

**Comment by bnoordhuis** [comment]
Node.js itself doesn't cache DNS records but if you use `dns.lookup()`, then the request goes through your local system's resolver and that can do all kinds of caching. On Linux, `dns.lookup()` is a wrapper around `man 3 getaddrinfo`.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
