### ISSUE TITLE
why regular user cannot start server with 127.0.0.1 81?

### ISSUE THREAD

**Issue by SongJuXin** [nodejs/help#2984]
* **Node.js Version**:v12.13.1
* **OS**:macOs Catalina 10.15.2
* **Scope (install, code, runtime, meta, other?)**:runtime
* **Module (and version) (if relevant)**:http,net

code:
```js
const http=require('http')
http.createServer().listen(81,'127.0.0.1')//error
http.createServer().listen(82,'0.0.0.0')//success
```
`127.0.0.1:81` is failed.
<img width="636" alt="err" src="https://user-images.githubusercontent.com/20874344/93585954-2e1c1300-f9da-11ea-92bc-4de94a20abd9.png">

`0.0.0.0:82` is ok.

Why is it like above?
Where could i find related doc about  above?

**Comment by addaleax** [comment]
Can you share any more information, specifically, *how* does this fail?

**Comment by SongJuXin** [comment]
> Can you share any more information, specifically, _how_ does this fail?

I've updated it

**Comment by addaleax** [comment]
You generally need admin/root access to listen to ports less than 1024 (they are called “well-known ports”), so that would be the most likely cause of that

I don’t know why that wouldn’t also fail for `0.0.0.0:82`, though

**Comment by SongJuXin** [comment]
> You generally need admin/root access to listen to ports less than 1024 (they are called “well-known ports”), so that would be the most likely cause of that
> 
> I don’t know why that wouldn’t also fail for `0.0.0.0:82`, though

Yes,I know a little about "below 1024".

**Comment by Monoverde888** [comment]
then use sudo..?

**Comment by SongJuXin** [comment]
On the base of  non-root user and port less than 1024,I try different system and diferent command.

Result as follows.As a record.

|system |command | host/network interface | success/fail | 
|  ----    | ----          |  ----                                 |----              |
|macOS |nodejs  |127.0.0.1|fail|
|macOS |nodejs  |0.0.0.0|success|
|centOS |nodejs  |127.0.0.1|fail|
|centOS |nodejs  |127.0.0.1|fail|
|centOS |nc  |-|success|
|centOS |nc |network interface|success|
