### ISSUE TITLE
Corrupt .jar file in Docker image when built by Maven through a child_process in Node.js

### ISSUE THREAD

**Issue by DevMcC** [nodejs/help#2985]
* **Node.js Version**: v12.18.4
* **OS**: Ubuntu 18.04.5 LTS
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: child_process

# Context
I am working on a Node.js application that will start up my docker environments. I would simply have to go to a project directory, run the command and it will start up the container.

I already have a simple version of this command in bash, but I wanted to be able to provide options, which was easier to do with Node.js.

I have environments in different languages, for example some are written in Java. This requires the Docker image to first be built by Maven after which, I can run docker-compose. This command automates these things for me.

Now I completed the application, but when I started to do a real test, I got an issue.

# Issue
It turns out that in the Java environments, the .jar file in the image is corrupted when the image is built by this Node.js application.
When the image built by a shell script in bash (like the simple version), everything is fine.

Running `ls -l` on my host machine shows a .jar file of around 75 MB, but doing the same in the container shows a .jar file of only 4096 bytes.

I initially built the image through `child_process.spawn` (and some different options, like encoding and shell.) 
After that I tried `child_process.exec`, but it got me the same result.
I read something about `--max-old-space-size=8192`, tried it, same result.

I have no idea how to fix this. Is this some memory issue? Or some limitation? Or am I missing some options? Or is this some specific issue with the command?

# Code sample
This is a simple script used to reproduce the issue:
```js
const { spawn } = require('child_process');

/**
 * @param {string} command
 * @returns {Promise<void>}
 */
function spawnAsync(command) {
    return new Promise((resolve) => {
        const commandArray = command.split(' ').filter((part) => part != '');
        const childProcess = spawn(commandArray.shift(), commandArray, { shell: true, encoding: 'utf8' });

        childProcess.stdout.pipe(process.stdout);
        childProcess.stderr.pipe(process.stderr);

        childProcess.on('close', () => resolve());
    });
}

async function run() {
    await spawnAsync('mvn clean package dockerfile:build -DskipTests');
    await spawnAsync('docker-compose up -d --build');
}
run();
```

**Comment by AqilCont** [comment]
Are you checking any exit codes or errors? There could be a potential system-related problem.

**Comment by DevMcC** [comment]
Yes, I just extended the example to log the status code and it just logged
a 0 status code when I ran it.

**Comment by DevMcC** [comment]
This error is caused by starting up a Java container by service name
I tested the generated docker-compose command in bash directly and could reproduce the issue.

Issue is out of scope, so I will close this.
