### ISSUE TITLE
How can I verify a RSA-PSS signature using crypto module in node.js?

### ISSUE THREAD

**Issue by milad2golnia** [nodejs/help#2990]
* **Node.js Version**: v14.10.0
* **OS**: Linux 5.4.64-1-MANJARO
* **Scope (install, code, runtime, meta, other?)**: code, runtime
* **Module (and version) (if relevant)**: [crypto
](https://nodejs.org/docs/latest-v13.x/api/crypto.html)

I created a signature in browser using [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) but now I'm not able to verify it using crypto module in node. at below I provide the Code of the **private key** which is in charge of signing and the Information of **sign**
1. private key information:

```js
let keypair = crypto.subtle.generateKey({
    name: 'RSA-PSS',
    modulusLength: 4096,
    publicExponent: new Uint8Array([1,0,1]),
    hash: 'SHA-256'
}, true, ['sign', 'verify']);

```
2. signing operation:
```js
crypto.subtle.sign({
          name: "RSA-PSS",
          saltLength: 32
        },
        keypair.privateKey,
        new TextEncoder().encode("hello")
).then((signValue)=>{
//converting to base64
})
```
3. exporting public key to be able use it in server:
```js
let exported = crypto.subtle.exportKey('spki', keypair.publicKey);
    exported.then((value)=>{
        console.log('successful');
        const exportedAsString = ab2str(value);
        const exportedAsBase64 = btoa(exportedAsString);
        const pemExported = `-----BEGIN PUBLIC KEY-----\n${exportedAsBase64}\n-----END PUBLIC KEY-----`;
})
```
I read the [documentation](https://nodejs.org/docs/latest-v13.x/api/crypto.html) almost completely but due to lack of examples I'm unable to verify the signature yet. After 8 hours working on it I didn't have any progress so I decided to ask my question here.
one of the last my attempts:
```js
const publicKey = crypto.createPublicKey({
    key: pemExported,
    format: 'pem',
    type: 'spki',
});
        
 let signature = Buffer.from(signValue, 'base64').toString();
 signature = stringToArrayBuffer(signature);
 
 const result = crypto.verify('rsa-sha256', new TextEncoder().encode('hello'),
                                                     publicKey, signature);
```
Unfortunately the result is always false.
If you need to see the whole code, please let me know.
Any help is appreciated.

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node/blob/1390574d66c1be8da899d18fe09afc5cc568fb79/test/parallel/test-crypto-sign-verify.js#L617-L651 - perhaps try what the test does, double-checking with `openssl dgst`.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
