### ISSUE TITLE
Node inspect color choice clashes with terminal background

### ISSUE THREAD

**Issue by veganaize** [nodejs/help#2991]
* **Version**: v14.12.0
* **Platform**: 64-bit Windows 8.1 (6.3.9600)

The `Array.prototype.forEach()`'s `index` value doesn't seem to be handled properly when passed as a comma-separated parameter to `console.log()`.

The `index` value is echoed in yellow unless concatenated with the string addition operator (`+`).

### What steps will reproduce the bug?

```
var my_array = ['a', 'b', 'c'];
 
function my_func(value, index, array) {
  console.log(index, value);
}
 
my_array.forEach(my_func);
```
### How often does it reproduce? Is there a required condition?

It happens every time in a Windows CMD console window.

### What is the expected behavior?

//Expected console output (all text with default foreground color):
```
0 a
1 b
2 c
```

//Similar to output produced by this code:
```
var my_array = ['a', 'b', 'c'];
 
function my_func(value, index, array) {
  console.log(index +'  '+ value);
}
 
my_array.forEach(my_func);
```

### What do you see instead?

I see bright yellow index numbers and normally colored values.

### Additional information

//When invoked in a console with a yellow background, as my code editor does, the output appears like this:
```
  a
  b
  c
```
//But I can copy & paste the output and it actually contains the index values.

*When I run it with **[GraalJS](https://github.com/graalvm/graaljs)**, at the `cmd.exe` prompt, the behavior works as expected.

**Comment by devsnek** [comment]
You should adjust your terminal's configuration so that ANSI 4 bit colors are readable.

**Comment by veganaize** [comment]
I'm using `cmd.exe` on Windows 8.1.  It doesn't understand ANSI escape codes.  All I can do is set the default foreground and background colors.

Node.js should set the background color if it alters the foreground color.

I didn't ask Node.js to change the color value of `index`, in the `Array.prototype.forEach()` callback, when echoed via `console.log`.  But you don't seem to care about making software accessible.

Is this how you treat black people which the Node.js project claims to care so much about?  You guys claim to be  systematically complicit in perpetuating the issues that led us to where we are yet you take no action to the contrary.  You continue to assert you dominance as white men even though you say you'll how you build it, moving forward.  Was that nothing more than virtue signalling?  I don't feel that I've had access to collaboration nor amplification -- just shut down.

**Comment by Trott** [comment]
Might be good to get some other opinions in here as to whether Node.js could and should do more to keep background/foreground contrast adequate in the terminal on Windows. @nodejs/console @nodejs/repl @nodejs/platform-windows

**Comment by mildsunrise** [comment]
For context (no windows knowledge here, but on every other OS):

I don't think it's actually possible to query background or graphical attributes from the terminal, you can only set them.

Like @devsnek said, most applications don't typically specify exact colors, they use the 8-color palette that is known to work everywhere. We do that, too. So when users change the terminal's colors, as long as they don't choose clashing colors for their palette, things are good.

**Comment by veganaize** [comment]
It is possible to query colors but that isn't necessary.  The plain and simple fact is that, when setting either the foreground or background color, one should also attempt to set the other.  So, keeping it simple, if Node.js selects a color that one would typically describe as "light" then the background should be set to a color typically described as "dark".

Otherwise Node.js should (ideally) default to no color and allow color to be enabled separately (e.g. like most GNU/Linux terminals).

**Comment by veganaize** [comment]
Here are some sample colorings using QBasic, in DOSBox, on Windows.  I think it's a nice example of the variations (from the stated color) that @devsnek was referring to.  From my experience the _light over dark_ & _dark over light_ thing works well enough.  But if we really can't be certain then I'm still behind no color as the default.  (And I'll shut up now ☺)
![image](https://user-images.githubusercontent.com/7102064/94586476-21978600-0236-11eb-986b-678dab8e8944.png)

**Comment by mildsunrise** [comment]
> The plain and simple fact is that, when setting either the foreground or background color, one should also attempt to set the other

Not sure what you mean, but I know no programs that output colored text (i.e. grep, git diff, less) that explicitely set a background when changing foreground :thinking: Demo with grep:

![Captura de 2020-10-01 13-54-05](https://user-images.githubusercontent.com/1177304/94806018-99f47780-03ed-11eb-9e60-1b1773773445.png)

*Some* of them use `CSI m` to reset the foreground color, which has the side-effect of also resetting the background to its default color. This can be seen above, notice the ! doesn't have red background.

**Comment by veganaize** [comment]
@mildsunrise `grep` does **_NOT_** default to using color.  You can find out if `grep` is being aliased by running the following command:
```
$ alias grep
```
Otherwise try echoing the following `grep` environment variables:
```
$ echo $GREP_OPTIONS $GREP_COLORS $GREP_COLOR
```
The culprit is probably the `alias` and it's probably set in `.bashrc`:
```
$ grep -i grep .bash*
```

Even when color is enabled `grep` also fails to set the background color, as you've demonstrated --but color output is disabled by default.

My specific issue is surrounded by the fact the `node` is changing the output color produced by **_MY_** program, an effect which I do **_not_** desire, in a confusing manner, without my specifying any such behavior..

**Comment by AqilCont** [comment]
I think this can maybe be solved if you just set the background color to something else yourself, maybe by logging a code to change the background before execution.

This can definitely get taken into more consideration if more people support it by the way, but I don't feel it as necessary to go through and recode how node colors its output even though you can just change your background. It is a commercially used program, and everyone is fine with how it currently works. I personally love the colors and use the black background like the basic person I am, and adding lag for this edge case sounds horrific.

note: it would be a truly massive undertaking to still support every terminal and being able to detect their backgrounds simultaneously.

**Comment by AqilCont** [comment]
then again, someone could just have a theme where your suggestion looks really messed up... which would omit the whole point of this :D

**Comment by veganaize** [comment]
@AqilCont am I not part of _"everyone"_?  I suppose I'm just some nobody.  I don't matter?

Node.js is welcome to break the decades old tradition of robust Unix-like utilities.  That's fine.  But I never asked Node.js to color **_MY_** index value in the `console.log()` statement in **_MY_** program.  That's the primary problem.

That's unexpected behavior.
That's obviously confusing.  Even to nobodies, who's opinions don't matter, like me.

Node.js can go against the accessibility standards set forth by world-wide standards body (W3C) when displaying it's own output -- **but it should not do so with the output of individual programs unless specifically asked to do so.**

With that, I rest my case.

**Comment by veganaize** [comment]
_What a bunch of haters._

**Comment by AqilCont** [comment]
nononono you're taking me too seriously! I meant to say that most people I have met, and most other devs on the internet are fine with with the current output, and I even brought up the fact that if more people support this, we can obviously bring a change. I was just saying that changing the whole colorization of the output is a bit of an undertaking, as there are obviously many things that node tries to bring out. I even brought up the fact that anyone can contribute, including you, to change this to your liking and add a sought out feature if it sits well with the team.

Also, with your most recent point, I think I misunderstood what you meant, because you brought up detecting the backgroind color and other things in the conversation, and I thought you were talking about entirely recoding the way Node output works. I had no intention of degrading or hurting you, and I am really sorry for the misunderstanding! With your recent argument, I think you should rephrase your original question to a simple, "Is there a way to stop Node from colorizing my output?", to which there might be more obvious and viable solutions all parties can agree upon.

**Comment by veganaize** [comment]
@devsnek decided to close the issue for no apparent reason.  So obviously the "team" could care less about what I think or how I feel.  Thank you for the actionable advice @AqilCont.

### Major consultants are actually advising that people avoid using Node.  I think I am beginning to understand why.

**Comment by AqilCont** [comment]
I love node, and I can't recommend completely quitting just for this reason. I guess there's no point in staying if you really hate it, but keep in mind that there is a very large and supportive community behind Node outside of this repository too. You might not see it here, as not many people really come here and a lot of these issues are really unnecessary so the people who handle these repositories are just tired of dealing with people xd. I still apreciate them, as they do whatever they can most of the time and don't get any payment for for their efforts.

If you want more real and friendlier help, I would suggest asking a larger part of the community(maybe like reddit) or researching something yourself. This repository has never really ever really helped me with any real issues either(at least the one I opened), but I still come here when I want to help some people out sometimes.

**Comment by AqilCont** [comment]
Oh btw, check out Deno too, it's really cool :D
https://deno.land/

**Comment by AqilCont** [comment]
this was closed because it's extremely off topic by the way(my best guess), not because anyone hates you or anything. I - should stop commenting here too ngl...
