### ISSUE TITLE
Frequent 'BadRequestError: request aborted' errors

### ISSUE THREAD

**Issue by dmahely** [nodejs/help#2992]
* **Node.js Version**: 12.13.0
* **OS**: Ubuntu 16.04.6
* **Scope (install, code, runtime, meta, other?)**: Runtime

```
BadRequestError: request aborted
     at IncomingMessage.onAborted (/home/bitnami/htdocs/node_modules/raw-body/index.js:231:10)
     at IncomingMessage.emit (events.js:210:5)
     at IncomingMessage.EventEmitter.emit (domain.js:476:20)
     at abortIncoming (_http_server.js:492:9)
     at socketOnClose (_http_server.js:485:3)
     at Socket.emit (events.js:215:7)
     at Socket.EventEmitter.emit (domain.js:476:20)
     at TCP.<anonymous> (net.js:658:12)
```

I see this error increasingly frequently, only in my production server so unfortunately it's not easily reproducible. I can't figure out a pattern for it.
I traced it to this snippet in `node_modules/raw-body/index.js`. Any idea when the `aborted` event is emitted?

```javascript
  stream.on('aborted', onAborted)

   ....

  function onAborted () {
    if (complete) return

    done(createError(400, 'request aborted', {
      code: 'ECONNABORTED',
      expected: length,
      length: length,
      received: received,
      type: 'request.aborted'
    }))
  }

```

It's really clogging up the logs 👇  and I'd appreciate any workarounds.

<img width="1165" alt="Screen Shot 2020-09-28 at 4 38 43 PM" src="https://user-images.githubusercontent.com/21047475/94437297-9aeb9600-01ae-11eb-92cf-43f893eeb880.png">

Related issue [here](https://github.com/nodejs/help/issues/2166)

**Comment by dmahely** [comment]
@danielpetrocchi Nope, unfortunately

**Comment by benjamingr** [comment]
For what it's worth you can do this natively without raw-body today doing:

```js
const content = Buffer.concat(await req.toArray()); // get whole request body, better to stream it somewhere usually though
```

**Comment by DM390** [comment]
Check the rate at which you're sending requests from your frontend. It has come to my attention that when you send too many frequent requests, they're likely to jam each other hence the error. Try increasing the interval times to solve the issue.
