### ISSUE TITLE
Illegal Instruction on "alpine linux v3.12 at ebox-3350-mx-ap"

### ISSUE THREAD

**Issue by zenbooster** [nodejs/help#2994]
* **Version**:
```
zenbooster@zenpc:~$ node -v
v12.18.4
```
* **Platform**:
```
zenbooster@zenpc:~$ uname -a
Linux zenpc 4.19.118-0-vanilla nodejs/node#1-Alpine SMP Thu Apr 23 11:19:40 UTC 2020 i586 Linux
```
* **Subsystem**:
Nettop "ebox 3350mx ap"
```
zenbooster@zenpc:~$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
zenbooster@zenpc:~$
```

### What steps will reproduce the bug?
1.
`zenbooster@zenpc:~/git/node$ make
make -C out BUILDTYPE=Release V=0
  touch 10035ee4ef2baf3258e9171841ec0538111e264d.intermediate
  LD_LIBRARY_PATH=/home/zenbooster/git/node/out/Release/lib.host:/home/zenbooster/git/node/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p /home/zenbooster/git/node/out/Release/obj/gen/src/node/inspector/protocol; python tools/inspector_protocol/code_generator.py --jinja_dir tools/inspector_protocol --output_base "/home/zenbooster/git/node/out/Release/obj/gen/src/" --config src/inspector/node_protocol_config.json
  touch 76be8f0056ffd51ea79b75b4bc101c2d1792f206.intermediate
  LD_LIBRARY_PATH=/home/zenbooster/git/node/out/Release/lib.host:/home/zenbooster/git/node/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../tools/v8_gypfiles; mkdir -p /home/zenbooster/git/node/out/Release/obj/gen/torque-output-root/torque-generated/../../deps/v8/src/builtins /home/zenbooster/git/node/out/Release/obj/gen/torque-output-root/torque-generated/../../deps/v8/test/torque /home/zenbooster/git/node/out/Release/obj/gen/torque-output-root/torque-generated/../../deps/v8/third_party/v8/builtins /home/zenbooster/git/node/out/Release/obj/gen/torque-output-root/torque-generated/../../deps/v8/src/wasm /home/zenbooster/git/node/out/Release/obj/gen/torque-output-root/torque-generated/../../deps/v8/src/ic /home/zenbooster/git/node/out/Release/obj/gen/torque-output-root/torque-generated/../../deps/v8/src/objects /home/zenbooster/git/node/out/Release/obj/gen/torque-output-root/torque-generated; "/home/zenbooster/git/node/out/Release/torque" ../../deps/v8/src/builtins/array-copywithin.tq ../../deps/v8/src/builtins/array-every.tq ../../deps/v8/src/builtins/array-filter.tq ../../deps/v8/src/builtins/array-find.tq ../../deps/v8/src/builtins/array-findindex.tq ../../deps/v8/src/builtins/array-foreach.tq ../../deps/v8/src/builtins/array-from.tq ../../deps/v8/src/builtins/array-isarray.tq ../../deps/v8/src/builtins/array-join.tq ../../deps/v8/src/builtins/array-lastindexof.tq ../../deps/v8/src/builtins/array-map.tq ../../deps/v8/src/builtins/array-of.tq ../../deps/v8/src/builtins/array-reduce-right.tq ../../deps/v8/src/builtins/array-reduce.tq ../../deps/v8/src/builtins/array-reverse.tq ../../deps/v8/src/builtins/array-shift.tq ../../deps/v8/src/builtins/array-slice.tq ../../deps/v8/src/builtins/array-some.tq ../../deps/v8/src/builtins/array-splice.tq ../../deps/v8/src/builtins/array-unshift.tq ../../deps/v8/src/builtins/array.tq ../../deps/v8/src/builtins/base.tq ../../deps/v8/src/builtins/bigint.tq ../../deps/v8/src/builtins/boolean.tq ../../deps/v8/src/builtins/builtins-string.tq ../../deps/v8/src/builtins/collections.tq ../../deps/v8/src/builtins/cast.tq ../../deps/v8/src/builtins/convert.tq ../../deps/v8/src/builtins/console.tq ../../deps/v8/src/builtins/data-view.tq ../../deps/v8/src/builtins/finalization-registry.tq ../../deps/v8/src/builtins/frames.tq ../../deps/v8/src/builtins/frame-arguments.tq ../../deps/v8/src/builtins/growable-fixed-array.tq ../../deps/v8/src/builtins/ic-callable.tq ../../deps/v8/src/builtins/ic.tq ../../deps/v8/src/builtins/internal-coverage.tq ../../deps/v8/src/builtins/iterator.tq ../../deps/v8/src/builtins/math.tq ../../deps/v8/src/builtins/number.tq ../../deps/v8/src/builtins/object-fromentries.tq ../../deps/v8/src/builtins/object.tq ../../deps/v8/src/builtins/promise-abstract-operations.tq ../../deps/v8/src/builtins/promise-all.tq ../../deps/v8/src/builtins/promise-all-element-closure.tq ../../deps/v8/src/builtins/promise-any.tq ../../deps/v8/src/builtins/promise-constructor.tq ../../deps/v8/src/builtins/promise-finally.tq ../../deps/v8/src/builtins/promise-misc.tq ../../deps/v8/src/builtins/promise-race.tq ../../deps/v8/src/builtins/promise-reaction-job.tq ../../deps/v8/src/builtins/promise-resolve.tq ../../deps/v8/src/builtins/promise-then.tq ../../deps/v8/src/builtins/promise-jobs.tq ../../deps/v8/src/builtins/proxy-constructor.tq ../../deps/v8/src/builtins/proxy-delete-property.tq ../../deps/v8/src/builtins/proxy-get-property.tq ../../deps/v8/src/builtins/proxy-get-prototype-of.tq ../../deps/v8/src/builtins/proxy-has-property.tq ../../deps/v8/src/builtins/proxy-is-extensible.tq ../../deps/v8/src/builtins/proxy-prevent-extensions.tq ../../deps/v8/src/builtins/proxy-revocable.tq ../../deps/v8/src/builtins/proxy-revoke.tq ../../deps/v8/src/builtins/proxy-set-property.tq ../../deps/v8/src/builtins/proxy-set-prototype-of.tq ../../deps/v8/src/builtins/proxy.tq ../../deps/v8/src/builtins/reflect.tq ../../deps/v8/src/builtins/regexp-exec.tq ../../deps/v8/src/builtins/regexp-match-all.tq ../../deps/v8/src/builtins/regexp-match.tq ../../deps/v8/src/builtins/regexp-replace.tq ../../deps/v8/src/builtins/regexp-search.tq ../../deps/v8/src/builtins/regexp-source.tq ../../deps/v8/src/builtins/regexp-split.tq ../../deps/v8/src/builtins/regexp-test.tq ../../deps/v8/src/builtins/regexp.tq ../../deps/v8/src/builtins/string-endswith.tq ../../deps/v8/src/builtins/string-html.tq ../../deps/v8/src/builtins/string-iterator.tq ../../deps/v8/src/builtins/string-pad.tq ../../deps/v8/src/builtins/string-repeat.tq ../../deps/v8/src/builtins/string-replaceall.tq ../../deps/v8/src/builtins/string-slice.tq ../../deps/v8/src/builtins/string-startswith.tq ../../deps/v8/src/builtins/string-substring.tq ../../deps/v8/src/builtins/string-substr.tq ../../deps/v8/src/builtins/symbol.tq ../../deps/v8/src/builtins/torque-internal.tq ../../deps/v8/src/builtins/typed-array-createtypedarray.tq ../../deps/v8/src/builtins/typed-array-every.tq ../../deps/v8/src/builtins/typed-array-filter.tq ../../deps/v8/src/builtins/typed-array-find.tq ../../deps/v8/src/builtins/typed-array-findindex.tq ../../deps/v8/src/builtins/typed-array-foreach.tq ../../deps/v8/src/builtins/typed-array-from.tq ../../deps/v8/src/builtins/typed-array-of.tq ../../deps/v8/src/builtins/typed-array-reduce.tq ../../deps/v8/src/builtins/typed-array-reduceright.tq ../../deps/v8/src/builtins/typed-array-set.tq ../../deps/v8/src/builtins/typed-array-slice.tq ../../deps/v8/src/builtins/typed-array-some.tq ../../deps/v8/src/builtins/typed-array-sort.tq ../../deps/v8/src/builtins/typed-array-subarray.tq ../../deps/v8/src/builtins/typed-array.tq ../../deps/v8/src/builtins/wasm.tq ../../deps/v8/src/ic/handler-configuration.tq ../../deps/v8/src/objects/allocation-site.tq ../../deps/v8/src/objects/api-callbacks.tq ../../deps/v8/src/objects/arguments.tq ../../deps/v8/src/objects/cell.tq ../../deps/v8/src/objects/code.tq ../../deps/v8/src/objects/contexts.tq ../../deps/v8/src/objects/data-handler.tq ../../deps/v8/src/objects/debug-objects.tq ../../deps/v8/src/objects/descriptor-array.tq ../../deps/v8/src/objects/embedder-data-array.tq ../../deps/v8/src/objects/feedback-cell.tq ../../deps/v8/src/objects/feedback-vector.tq ../../deps/v8/src/objects/fixed-array.tq ../../deps/v8/src/objects/foreign.tq ../../deps/v8/src/objects/free-space.tq ../../deps/v8/src/objects/heap-number.tq ../../deps/v8/src/objects/heap-object.tq ../../deps/v8/src/objects/js-aggregate-error.tq ../../deps/v8/src/objects/js-array-buffer.tq ../../deps/v8/src/objects/js-array.tq ../../deps/v8/src/objects/js-collection-iterator.tq ../../deps/v8/src/objects/js-collection.tq ../../deps/v8/src/objects/js-generator.tq ../../deps/v8/src/objects/js-objects.tq ../../deps/v8/src/objects/js-promise.tq ../../deps/v8/src/objects/js-proxy.tq ../../deps/v8/src/objects/js-regexp-string-iterator.tq ../../deps/v8/src/objects/js-regexp.tq ../../deps/v8/src/objects/js-weak-refs.tq ../../deps/v8/src/objects/literal-objects.tq ../../deps/v8/src/objects/map.tq ../../deps/v8/src/objects/microtask.tq ../../deps/v8/src/objects/module.tq ../../deps/v8/src/objects/name.tq ../../deps/v8/src/objects/oddball.tq ../../deps/v8/src/objects/ordered-hash-table.tq ../../deps/v8/src/objects/primitive-heap-object.tq ../../deps/v8/src/objects/promise.tq ../../deps/v8/src/objects/property-array.tq ../../deps/v8/src/objects/property-cell.tq ../../deps/v8/src/objects/property-descriptor-object.tq ../../deps/v8/src/objects/prototype-info.tq ../../deps/v8/src/objects/regexp-match-info.tq ../../deps/v8/src/objects/scope-info.tq ../../deps/v8/src/objects/script.tq ../../deps/v8/src/objects/shared-function-info.tq ../../deps/v8/src/objects/source-text-module.tq ../../deps/v8/src/objects/stack-frame-info.tq ../../deps/v8/src/objects/string.tq ../../deps/v8/src/objects/struct.tq ../../deps/v8/src/objects/synthetic-module.tq ../../deps/v8/src/objects/template-objects.tq ../../deps/v8/src/objects/template.tq ../../deps/v8/src/wasm/wasm-objects.tq ../../deps/v8/test/torque/test-torque.tq ../../deps/v8/third_party/v8/builtins/array-sort.tq ../../deps/v8/src/objects/intl-objects.tq -o "/home/zenbooster/git/node/out/Release/obj/gen/torque-output-root/torque-generated" -v8-root ../../deps/v8
make[1]: *** [tools/v8_gypfiles/run_torque.target.mk:17: 76be8f0056ffd51ea79b75b4bc101c2d1792f206.intermediate] Illegal instruction
make[1]: *** Deleting file '76be8f0056ffd51ea79b75b4bc101c2d1792f206.intermediate'
rm 10035ee4ef2baf3258e9171841ec0538111e264d.intermediate
make: *** [Makefile:104: node] Error 2
zenbooster@zenpc:~/git/node$`

2.

```
zenbooster@zenpc:~$ sudo apk update
fetch http://mirror.yandex.ru/mirrors/alpine/latest-stable/main/x86/APKINDEX.tar.gz
fetch http://mirror.yandex.ru/mirrors/alpine/latest-stable/community/x86/APKINDEX.tar.gz
fetch http://mirror.yandex.ru/mirrors/alpine/edge/testing/x86/APKINDEX.tar.gz
v3.12.0-353-g75c1a6bb6e [http://mirror.yandex.ru/mirrors/alpine/latest-stable/main]
v3.12.0-354-gc7808252a3 [http://mirror.yandex.ru/mirrors/alpine/latest-stable/community]
v20200917-1312-g103084030b [http://mirror.yandex.ru/mirrors/alpine/edge/testing]
OK: 16229 distinct packages available

zenbooster@zenpc:~$ sudo apk add nodejs
(1/3) Installing c-ares (1.16.1-r0)
(2/3) Installing libuv (1.38.1-r0)
(3/3) Installing nodejs (12.18.4-r0)
Executing busybox-1.31.1-r19.trigger
OK: 1342 MiB in 311 packages

zenbooster@zenpc:~$ npm --help
/bin/ash: npm: not found

zenbooster@zenpc:~$ sudo apk add npm
(1/1) Installing npm (12.18.4-r0)
Executing busybox-1.31.1-r19.trigger
OK: 1370 MiB in 312 packages

zenbooster@zenpc:~$ npm --help
Illegal instruction

zenbooster@zenpc:~$ node --help
Illegal instruction

zenbooster@zenpc:~$

```

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help. I think you've already figured it out yourself but to confirm, your CPU is unsupported.

**Comment by gireeshpunathil** [comment]
@zenbooster - is there anything pending here? were you successful in building node for your target?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding

**Comment by yangkkokk** [comment]
``
root@OpenWrt:/# node


#
# Fatal err[ 1101.316414] traps: node[5772] trap invalid opcode ip:85eb86d sp:bfbdce9c error:0 in node[85dd000+a09000]
or in , line 0
# Check failed: cpu.has_sse2().
#
#
#
#FailureMessage Object: 0xbfbdceb4
Illegal instruction
root@OpenWrt:/#



> Made some changes. So far, building ...
> 
> ```
> --- /home/zenbooster/git/node/tools/v8_gypfiles/toolchain.gypi.bak
> +++ /home/zenbooster/git/node/tools/v8_gypfiles/toolchain.gypi
> @@ -993,8 +993,7 @@
>           or OS=="netbsd" or OS=="mac" or OS=="android" or OS=="qnx") and \
>          v8_target_arch=="ia32"', {
>          'cflags': [
> -          '-msse2',
> -          '-mfpmath=sse',
> +          '-mfpmath=387',
>            '-mmmx',  # Allows mmintrin.h for MMX intrinsics.
>          ],
>        }],
> ```
> 
> ```
> --- /home/zenbooster/git/node/tools/gyp/tools/emacs/testdata/media.gyp.bak
> +++ /home/zenbooster/git/node/tools/gyp/tools/emacs/testdata/media.gyp
> @@ -547,7 +547,7 @@
>          }],
>          [ 'os_posix == 1 and OS != "mac" and OS != "android"', {
>            'cflags': [
> -            '-msse2',
> +            '-mmmx',
>            ],
>          }],
>          [ 'OS == "mac"', {
> ```
> 
> ```
> --- /home/zenbooster/git/node/tools/gyp/tools/emacs/testdata/media.gyp.fontified.bak
> +++ /home/zenbooster/git/node/tools/gyp/tools/emacs/testdata/media.gyp.fontified
> @@ -548,7 +548,7 @@
>          }],
>          [ 'os_posix == 1 and OS != \"mac\" and OS != \"android\"', {
>            'cflags': [
> -            '-msse2',
> +            '-mmmx',
>            ],
>          }],
>          [ 'OS == \"mac\"', {
> ```

root@OpenWrt:/# node


#
# Fatal err[ 1101.316414] traps: node[5772] trap invalid opcode ip:85eb86d sp:bfbdce9c error:0 in node[85dd000+a09000]
or in , line 0
# Check failed: cpu.has_sse2().
#
#
#
#FailureMessage Object: 0xbfbdceb4
Illegal instruction
root@OpenWrt:/#

The v8_target_arch='x87' support has been officially removed in V8 6.1.534, see [link](https://chromium-review.googlesource.com/c/v8/v8/+/575756)
