### ISSUE TITLE
FS module implementation

### ISSUE THREAD

**Issue by Slender1808** [nodejs/help#2995]
Is there a place explaining how the node's file system works behind it?

**Comment by PoojaDurgad** [comment]
@Slender1808 - https://nodejs.org/docs/latest-v14.x/api/fs.html It may help you.

**Comment by Slender1808** [comment]
> @ Slender1808 - https://nodejs.org/docs/latest-v14.x/api/fs.html Isso pode ajudá-lo.

In the documentation there is no part of how it works at the lowest level

**Comment by Slender1808** [comment]
it was this documentation that I was looking for

[https://www.zlib.net/manual.html](url)
