### ISSUE TITLE
How to set globalAgent (options) using ES modules

### ISSUE THREAD

**Issue by joachimroeleveld** [nodejs/help#2996]
* **Node.js Version**: 14
* **OS**: macOS Catalina
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: https

How do I set `https.globalAgent`'s options when using ES modules? I cannot do 

`require('https').globalAgent.options.keepAlive = true`

 because `options` is [set on the agent object](https://github.com/nodejs/node/blob/v14.13.0/lib/_http_agent.js#L89). 
I cannot override `globalAgent` either, as that would only apply to the local ES module.

**Comment by guybedford** [comment]
@joachimroeleveld try using the following in ES modules:

 ```js
import { globalAgent } from 'https';
globalAgent.options.keepAlive = true;
```

Setting the `globalAgent` isn't possible in ES modules yes, but the mutations still reflect.

**Comment by joachimroeleveld** [comment]
@guybedford this indeed does set the option on the object, however the options are transferred onto the main object on construction and therefore not applied during requests 😕. Setting `globalAgent.keepAlive` does work but it's undocumented and the TypeScript compiler doesn't allow it as it is not in the types.

**Comment by guybedford** [comment]
@joachimroeleveld but you're saying that `require('https').globalAgent.options.keepAlive = true` does work in this same case? I'm not sure I follow where that divergence is happening here as it sounds to me like it's more about setting `globalAgent.keepAlive = true` than setting `globalAgent.options.keepAlive`. Alternatively perhaps because of the async nature of ES modules there is a timing issue here that is the difference?

**Comment by joachimroeleveld** [comment]
> you're saying that require('https').globalAgent.options.keepAlive = true does work in this same case?

It doesn't work. If I inspect the object the property is reflected in options, but it's not applied on a subsequent request. The following doesn't work.
```javascript
import { globalAgent } from 'https';
globalAgent.options.keepAlive = true;

const server = createHttpsServer({
  cert,
  key,
});
server
  .on('request', (_, response): void => {
    expect(response.shouldKeepAlive).toStrictEqual(true);
    response.end();
  })
  .listen(serverPort);

httpsGet(
  'https://localhost:8000/',
  {
    rejectUnauthorized: false,
  },
  (): void => {
    resolve();
    server.close();
  },
);
```

**Comment by guybedford** [comment]
But you are saying that using `require('https').globalAgent.options.keepAlive = true` in the same example definitely does work?

I'm not that up to date on this API, but browsing the code I can't see how there is divergence between these two at all.

**Comment by joachimroeleveld** [comment]
I wasn't clear. In the case of require I would use:
require('https').globalAgent = new Agent({keep live:true});
This doesn't work with ES modules.

**Comment by guybedford** [comment]
@joachimroeleveld did you try using `import https from 'https; https.globalAgent = new Agent({keepAlive: true})` here?

**Comment by joachimroeleveld** [comment]
@guybedford `https` has no default export so that doesn't work unfortunately.

**Comment by guybedford** [comment]
@joachimroeleveld it very much does have a default.

**Comment by joachimroeleveld** [comment]
I'm not able to use with TS, I can only import it using `import * as https from 'https';
![image](https://user-images.githubusercontent.com/5803704/94730188-2148d900-0363-11eb-96ea-f6f0821fb432.png)
But I'm not sure if it would work otherwise.

**Comment by joachimroeleveld** [comment]
@guybedford thanks for your answers. I'm choosing a different approach, because overriding `globalAgent` does not feel supported enough.
