### ISSUE TITLE
using child_process more effectively

### ISSUE THREAD

**Issue by rexlx** [nodejs/help#2999]
* **v12.18.4**:
* **centos 7**:
* **Scope (not sure what you mean)**:
* **Module ("body-parser": "^1.19.0", "express": "^4.17.1")**:

hello all,

I have a tool that sends commands to remote servers over ssh, called send. I use child_process in nodejs so that a user who may not understand how to use the cli version can do it using a web interface. To accomplish this i use a simple node/express api with the following contents (some lines removed for brevity)

```
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

app.post("/send", (req, res) => {
    // log request
    const s = spawn("/home/user/bin/send", [req.body.cmd, `-u ${req.body.user}`, `-m "${req.body.host}"`], { shell: true })
    s.stdout.on('data', (data) => {
        res.end(data)
      })
      
    s.stderr.on('data', (data) => {
       res.end(data)
      })
      
    s.on('close', (code) => {
       res.end(code)
      })
    let date = new Date()
    let msg = `\n${date}\n\t => ${req.body.cmd} as ${req.body.user} on ${req.body.host}`
    fs.appendFile(log, msg, (e) => {
        if (e) throw e
    })
    // res.end("processed")
})
```

works as expected, except when we send a command to multiple hosts at once. the tool "send", written in go, leverages concurrency to blast out all the commands at once and listen for either stderr, stdout, or a timeout. so essentially once one server has processed the command, node receives stdout, and thats the only output i get.

ideas?

**Comment by addaleax** [comment]
Sooo … I’m not quite sure what exactly you”re asking for here, but some things that might be worth pointing out:

> `const s = spawn("/home/user/bin/send", [req.body.cmd, `-u ${req.body.user}`, `-m "${req.body.host}"`], { shell: true })`

Are you sure that that is what you want, and not `... [req.body.cmd, '-u', req.body.user, '-m', req.body.host], ...`? This way you are passing the options to `-u` and `-m` as part of the same argument, something that would be rejected by most options parsers

(Maybe you just omitted it for this example, but you probably also want to do some kind of validation on `req.body` here?)

> ```js
>  s.stdout.on('data', (data) => {
>     res.end(data)
>   })
>  s.stderr.on('data', (data) => {
>    res.end(data)
>   })
> ```

There might be some confusion about what’s happening here – `s.stdout.on('data')` is an event that is usually emitted multiple times, and there are no hard guarantees about the chunk boundaries in which you receive data from stdout. Do you really want to *end* the stream once the first bit of data is received? My guess is that you’d probably want something closer to 

```js
// Passing end: false so both streams can get the full data
s.stdout.pipe(res, { end: false }); 
s.stderr.pipe(res, { end: false }); 
s.on('close', () => res.end());  // Only actually end once all data has been received
```

> ```js   
> s.on('close', (code) => {
>    res.end(code)
>   })
> ```

This seems odd – `code` is a number and `res.end()` expects a string or buffer, you probably shouldn’t to pass it to `res.end()` as-is.

**Comment by rexlx** [comment]
```
// Passing end: false so both streams can get the full data
s.stdout.pipe(res, { end: false }); 
s.stderr.pipe(res, { end: false }); 
s.on('close', () => res.end());  // Only actually end once all data has been received
```

This did it, thanks! to answer a few of your questions:

in regards to your question about the args array. -u and -m both expect a string., so -u user -m "host1 host2 diff-user@host3"

in regards to my lack of validation on the request, i totally plan on doing that next, i just needed to the code to what i wanted without error before moving on.

any other questions may be answered with the fact that this is day two of writing in node :)

thanks again for you time
