### ISSUE TITLE
httpServer.setTimeout callback is called twice for a single request (not favicon)

### ISSUE THREAD

**Issue by taitulism** [nodejs/help#30]
hey all.

Considering this code:
```js
// file: index.js
var http = require('http');

// create a server with a basic request-handler
var server = http.createServer(function (req, res) {
	console.log('request'); // happens once

	res.end('end');
});


// set a socket 4 sec timeout 
server.setTimeout(4000, function (socket) {
	console.log('destroyed'); // happens twice
	socket.destroy();
});


// start listening
server.listen(3000, '127.0.0.1', function () {
	console.log('listening...');
});
```

4 seconds after a **single** request, the "onTimeout" callback gets called twice. 
This is **not a favicon.ico issue**. The "request" log shows only once but the "destroyed" log shows twice.

```sh
$ node index.js
request     # a single request
# 4 seconds later...
destroyed   #1
destroyed   #2
```

**NOTE:** This happens only when I pass the `host` argument to the `listen` function. When i omit the `host` it works as expected.
i.e.
```js
// start listening
server.listen(3000, function () {
	console.log('listening...');
});
```
```sh
$ node index.js
request     # a single request
# 4 seconds later...
destroyed   #1
```

I'm not sure if this is a bug or an expected behavior from [Node's docs](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback).

I'm using node 5.0 on windows 7 ultimate.

Additional info
------------------
Actually the first "destroyed" log happen 4 seconds after the first request even if requests keep coming. If the timeout value condition is not met (i.e. keep the requests coming), the first "destroyed" log comes 4 seconds after the first request (no matter what) and the second log comes 4 seconds after the last request.
```sh
$ node index.js
# make a request every second
request    <──
request
request
request
destroyed  <── 4 sec after the first request
request
request
# keep 'em coming...
request
request
request
request
request   # stop requesting
# 4 seconds after the last request...
destroyed
```

Additionally, I've added a `console.log(socket)` in the `timeout` callback and a diff shows these props are different:
```js
_events: [ [Function: serverSocketCloseListener] ]
vs
_events: [Function: serverSocketCloseListener]

sync: false
vs
sync: true

_bytesDispatched: 102
vs
_bytesDispatched: 0

_idleStart: 1845
vs
_idleStart: 2086

incoming: IncomingMessage {...}
vs
none

_httpMessage: null
vs
none

```

Sorry if that was too hmm.. verbose.
Thanks a lot!

**Comment by Trott** [comment]
What version of Node are you running and what operating system are you using? I'm having trouble replicating this.

**Comment by taitulism** [comment]
node 5.0
win 7 ultimate
i'll update the issue with this, thanks.

**Comment by Trott** [comment]
It's unlikely to fix it, but just in case, can you try with Node 5.1.0?

**Comment by taitulism** [comment]
The problem remains with 5.1.0.

Reproduction steps (just to make it clear):

1. create an `index.js` file.
2. copy the following and paste it the index file:
    ```js
	var http = require('http');

	var server = http.createServer(function (req, res) {
	    console.log('request');
	    res.end('end');
	});

	server.setTimeout(4000, function (socket) {
	    console.log('destroyed');
	    socket.destroy();
	});

	server.listen(3000, '127.0.0.1', function () {
	    console.log('listening...');
	});
    ```
3. start the server up `$ node index.js`
4. make a request to `localhost:3000` (i'm using "postman")
5. expected logs:
```sh
	request
	# 4 seconds later
	destroyed
```

actual logs:
```sh
	request
	# 4 seconds later
	destroyed
	destroyed
```

If you'll remove the `127.0.0.1` argument from the `server.listen` function and try again (from step 3) you'll see the expected logs.

**Comment by Trott** [comment]
The fact that the behavior changes when you omit the hostname suggests that this may be an issue with how it may accept IPv6 connections if you omit hostname, but will not if you supply an IPv4 address like `127.0.0.1`. I'm not looking at this too closely right now and I don't have a plausible mechanism to explain this, but if that small tweak alters the behavior, I'd look into that. Like, can you use postman to request `http://[::1]:3000/` instead of `http://localhost:3000/` and does the problem manifest there? Chrome does a lot of IPv6 probing in my experience, so that may be the source of the issue. Er, maybe. Like I said, I'm having a hard time coming up with a plausible story here, but that's the thing that's leaping out at me...

**Comment by taitulism** [comment]
It looks like "postman" doesn't support ipv6 and I couldn't make this ipv6 request from firefox either.
I guess it's not that important anyway. Thanks a lot!
