### ISSUE TITLE
Nodejs and npm tools installation problem

### ISSUE THREAD

**Issue by shterionyanev** [nodejs/help#300]
- **Version**: 6.6.0
- **Platform**: Windows 8 64 bit
- **Subsystem**:

Hey guys,

I have the following problem. I installed node with npm which work perfectly but when I want to install, let's say _typings_ or _yeoman_ or _gulp_ then I receive the following mesage in terminal `C:\Users\Shterion Yanev\Desktop\Test>typings install dt~node --global --save
'typings' is not recognized as an internal or external command,
operable program or batch file.`.  I see that npm has installed typings in folder `~
**C:\Users\Shterion Yanev\Desktop\Test\'~\npm-global'\node_modules\typings** 

What could be the reason and how can I fixed it?

I also want to say that no dependencies were made in package.json file.

Thanks!

**Comment by lordKnighton** [comment]
I Apologize we didn't get to this issue in time, if you still in need of help reopen & discuss
