### ISSUE TITLE
how to cache normalized data?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#3001]
* **Node.js Version**: all
* **OS**: all
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: all

[i can not understand this statement](https://nodejs.org/en/docs/guides/working-with-different-filesystems/#comparing-different-unicode-forms)
![image](https://user-images.githubusercontent.com/8686739/94939581-eda5b480-0504-11eb-8572-6c3d09b91314.png)

**Comment by gireeshpunathil** [comment]
@nodejs/i18n-api

**Comment by anlexN** [comment]
![image](https://user-images.githubusercontent.com/8686739/98378318-ccdefa80-2080-11eb-91f6-142d0ec79231.png)
@gireeshpunathil what happened?

**Comment by gireeshpunathil** [comment]
I pinged that team in expectation of they helping you with this. You don't have access to that team information, so you will see the 404 page. 

in summary, action is not on you, we will wait to hear from them

**Comment by anlexN** [comment]
@gireeshpunathil can you give me some example right now? please teach me.

**Comment by gireeshpunathil** [comment]
I don't know examples myself, that is why I pinged the team! :) let us wait to hear from them

**Comment by srl295** [comment]
I don't have a good example. Any general caching mechanism could work.

**Comment by RedYetiDev** [comment]
@srl295 thanks for your insight!
