### ISSUE TITLE
toLocaleString Australian Dollar

### ISSUE THREAD

**Issue by outbackStack** [nodejs/help#3002]
Hi All,

Is there a way to remove that letter 'A' in font of the dollar sign? In the browser(Chrome + Firefox) just have the $ symbol.

```js
let amount = 124.00
console.log(amount.toLocaleString('en-AU', {style: "currency", currency: "AUD"}))
```

output as: `A$123.00`

---

* Node.js Version**: 12.18.4
* OS: Mac OS Catalina

**Comment by 0wx** [comment]
I think this problem solved in Node.js version 14, I tried using Node.js v14 on Ubuntu 20 works fine for me.

**Comment by outbackStack** [comment]
Thanks @0wx 

Also, I just found that you could set the `currencyDisplay` option to `narrowSymbol` which will remove this.

```js
amount.toLocaleString('en-AU', {style: "currency", currency: "AUD", currencyDisplay: "narrowSymbol" })
```
