### ISSUE TITLE
Achieve True Multi-Threading in NodeJS

### ISSUE THREAD

**Issue by telecomsxchange** [nodejs/help#3004]
We have an smpp server/client written in NodeJS. The bottleneck is currently related to NodeJS being single threaded. 

We have tried several work arounds but didn't really work for SMPP to achieve multi-threading. We are thinking maybe to write a load balancer in Go language to distribute traffic across multiple NodeJS smpp proxies. 

Before we do that I thought maybe there is some reliable and tested solution in NodeJS that allows us to achieve this without having to use another programming language. 

We are happy to pay someone from the community for consulting with this. Thanks

**Comment by addaleax** [comment]
There’s https://nodejs.org/api/worker_threads.html, which does give you multithreading in Node.js.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
