### ISSUE TITLE
NODEJS for Windows10 on ARM(Surface Pro X)

### ISSUE THREAD

**Issue by justrach** [nodejs/help#3007]
Is there a current version which can be ran on an ARM machine from windows?

* **Node.js Version**: 12.18.4
* **OS: Windows10ARM
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**:

**Comment by richardlau** [comment]
@justrach One was built yesterday: https://github.com/nodejs/build/issues/2450#issuecomment-703371601

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to reopen the issue if that is not the case
