### ISSUE TITLE
should i use node:12.13.1 or alpine docker image for production?

### ISSUE THREAD

**Issue by Divine1** [nodejs/help#3010]
which nodejs docker image is recommended for production? 
sizeOf `node:12.13.1` image is `940mb` (just the image).
i have to build an image in one machine(jenkins) and then move it to another machine(production environment) for deployment. Bundling up my source code will increase the size by another 1024mb. 
Is transferring a large custom docker image for production release such as this one normal or abnormal? This will be happening between the aws instances over the same region in my case. is there a better approach i can follow?
Is using node:12.13.1 image over alpine has benefits? what is it?
When should i go for node:12.13.1 image?

**Comment by mhdawson** [comment]
My suggestion would be to use a 2 stage docker build (https://docs.docker.com/develop/develop-images/multistage-build/) where you use the regular image (for example 12.19-buster) for the build stage and the slim image to build the final image (for example 12.19-buster-slim)

**Comment by Divine1** [comment]
@mhdawson checking out this one. will share the feedback

**Comment by Divine1** [comment]
@mhdawson 
i tried the multi stage build that you recommended , it seems to work for me. i came up with below `Dockerfile` config for checking out multi-stage build.

Thank you @mhdawson  👍 

```
FROM node:12.13.1 as stage1
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install

FROM node:12.13.1-buster-slim
WORKDIR /usr/src/app
COPY . /usr/src/app
COPY --from=stage1 /usr/src/app /usr/src/app
EXPOSE 3000
CMD ["node","server.js"]
```

This is not the final config which i will be using in production
