### ISSUE TITLE
Unable to update nodejs

### ISSUE THREAD

**Issue by Temepest74** [nodejs/help#3012]
I have an old version of node js. i try to update it but i get the following errors when i run yum install nodejs -y on centos 7. P.S. I get the same error when i use yum update / upgrade. 
`[root@vps82008 prestashop]# yum install nodejs -y
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.hostico.ro
 * epel: fedora.mirrors.telekom.ro
 * extras: mirrors.hostico.ro
 * remi-php74: mirrors.neterra.net
 * remi-safe: mirrors.neterra.net
 * updates: mirrors.hostico.ro
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 1:6.17.1-1.el7 will be updated
--> Processing Dependency: nodejs = 1:6.17.1-1.el7 for package: 1:npm-3.10.10-1.6.17.1.1.el7.x86_64
---> Package nodejs.x86_64 2:12.19.0-1nodesource will be an update
--> Finished Dependency Resolution
Error: Package: 1:npm-3.10.10-1.6.17.1.1.el7.x86_64 (@epel)
           Requires: nodejs = 1:6.17.1-1.el7
           Removing: 1:nodejs-6.17.1-1.el7.x86_64 (@epel)
               nodejs = 1:6.17.1-1.el7
           Updated By: 2:nodejs-12.19.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.19.0-1nodesource
           Available: 2:nodejs-12.0.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.0.0-1nodesource
           Available: 2:nodejs-12.1.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.1.0-1nodesource
           Available: 2:nodejs-12.2.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.2.0-1nodesource
           Available: 2:nodejs-12.3.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.3.0-1nodesource
           Available: 2:nodejs-12.3.1-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.3.1-1nodesource
           Available: 2:nodejs-12.4.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.4.0-1nodesource
           Available: 2:nodejs-12.5.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.5.0-1nodesource
           Available: 2:nodejs-12.6.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.6.0-1nodesource
           Available: 2:nodejs-12.7.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.7.0-1nodesource
           Available: 2:nodejs-12.8.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.8.0-1nodesource
           Available: 2:nodejs-12.8.1-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.8.1-1nodesource
           Available: 2:nodejs-12.9.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.9.0-1nodesource
           Available: 2:nodejs-12.9.1-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.9.1-1nodesource
           Available: 2:nodejs-12.10.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.10.0-1nodesource
           Available: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.11.1-1nodesource
           Available: 2:nodejs-12.12.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.12.0-1nodesource
           Available: 2:nodejs-12.13.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.13.0-1nodesource
           Available: 2:nodejs-12.13.1-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.13.1-1nodesource
           Available: 2:nodejs-12.14.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.14.0-1nodesource
           Available: 2:nodejs-12.14.1-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.14.1-1nodesource
           Available: 2:nodejs-12.15.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.15.0-1nodesource
           Available: 2:nodejs-12.16.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.16.0-1nodesource
           Available: 2:nodejs-12.16.1-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.16.1-1nodesource
           Available: 2:nodejs-12.16.2-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.16.2-1nodesource
           Available: 2:nodejs-12.16.3-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.16.3-1nodesource
           Available: 2:nodejs-12.17.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.17.0-1nodesource
           Available: 2:nodejs-12.18.0-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.18.0-1nodesource
           Available: 2:nodejs-12.18.1-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.18.1-1nodesource
           Available: 2:nodejs-12.18.2-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.18.2-1nodesource
           Available: 2:nodejs-12.18.3-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.18.3-1nodesource
           Available: 2:nodejs-12.18.4-1nodesource.x86_64 (nodesource)
               nodejs = 2:12.18.4-1nodesource
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@vps82008 prestashop]# yum install nodejs -y --skip-broken
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.hostico.ro
 * epel: fedora.mirrors.telekom.ro
 * extras: mirrors.hostico.ro
 * remi-php74: mirrors.neterra.net
 * remi-safe: mirrors.neterra.net
 * updates: mirrors.hostico.ro
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 1:6.17.1-1.el7 will be updated
--> Processing Dependency: nodejs = 1:6.17.1-1.el7 for package: 1:npm-3.10.10-1.6.17.1.1.el7.x86_64
---> Package nodejs.x86_64 2:12.19.0-1nodesource will be an update

Packages skipped because of dependency problems:
    2:nodejs-12.19.0-1nodesource.x86_64 from nodesource
[root@vps82008 prestashop]# node -b
node: bad option: -b
[root@vps82008 prestashop]# node -v
v6.17.1
`

**Comment by Truth1984** [comment]
```npm i -g n
n lts```

**Comment by PoojaDurgad** [comment]
@Temepest74 - is this issue resolved? before updating to the latest version of node check current version of node and update the npm and then install the stable version of node. meanwhile you can refer this https://phoenixnap.com/kb/update-node-js-version
it may help!!

**Comment by PoojaDurgad** [comment]
inactive. closing!!
