### ISSUE TITLE
Current status Object.setPrototypeOf()?

### ISSUE THREAD

**Issue by BerendKemper** [nodejs/help#3013]
* **Node.js Version**: v12.19.0
* **OS**: Linux, Windows 10, Mac
* **Scope**: Object.setPrototypeOf()
* **Module**: [files-json@2.0.2](https://www.npmjs.com/package/files-json/v/2.0.2)

My intention was to use Object.setPrototypeOf() in various occasions. In **case 1** and **case 2** Object.setPrototypeOf() is used to extend a Request and Response, Object.create() is also an option. However in **case 3** Object.setPrototypeOf() is used to extend an (ordinary) Object, that was created from JSON.parse(), to the prototype from the class FileJSON. There is even a case 4 where i use Object.setPrototypeOf() in order to extend every sub-Object from a certain FileJSON to another class with prototype methods. 

Recently i read the docs from Mozilla about [Object.setPrototypeOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain#Summary_of_methods_for_extending_the_prototype_chain), a quote: _"many browsers optimize the prototype and try to guess the location of the method in the memory when calling an instance in advance, but setting the prototype dynamically disrupts all these optimizations and can even force some browsers to recompile for deoptimization your code just to make it work according to the specs."_. 

Currently in Node JS how is the current situation of Object.setPrototypeOf()? Is dynamically setting the prototype disrupting any optimizations? From Node JS's source-code i've observed ObjectSetPrototypeOf() (a method from primordials) is used in every code i've read so far, and thanks to that is what made me use Object.setPrototypeOf() in the first place.

```js
/* case 1 */
function Request(socket) {
	http.IncomingMessage.call(this, socket);
};
Object.setPrototypeOf(Request.prototype, http.IncomingMessage.prototype);

/* case 2 */
function Response(request) {
	http.ServerResponse.call(this, request);
};
Object.setPrototypeOf(Response.prototype, http.ServerResponse.prototype);

/* case 3  */
/* From the module files-json@2.0.2 - InternalFileJSON.prototype.onRead at line 16*/
this.external = Object.setPrototypeOf(JSON.parse(data), FileJSON.prototype);
/* data is the content that has been read from a json-file through fs.readFile() */
```

**Comment by addaleax** [comment]
You can generally assume that modifying the prototype of a `constructor.prototype` property is just fine as long as no instances have been created from that constructor.

The problems that do arise occur when you modify the prototype chain of objects that have already been used in optimized code. I would assume that case 3 is also fine here, for example, but not necessarily if the parsed data had already been processed before and the `Object.setPrototypeOf()` call occurred at a later point in time.

Generally, I would not worry too much about this unless you know that this is a performance bottleneck for you.

Note that for case 1 and case 2, if you want compatibility with ES6 classes, you should also add `Object.setPrototypeOf(subclass, superclass);` in addition to `Object.setPrototypeOf(subclass.prototype, superclass.prototype);`.

**Comment by BerendKemper** [comment]
Thank you and for the additional advice!

**Comment by PoojaDurgad** [comment]
closing as answered. feel free to re-open the issue if its still outstanding.
