### ISSUE TITLE
how much time do you cost to build nodejs?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#3015]
* **Node.js Version**: 14.13.1
* **OS**: Windows WSL ubuntu
* **Scope (install, code, runtime, meta, other?)**:  all
* **Module (and version) (if relevant)**: all
* **gcc/g++ version**:  9.3.0
* **python**: 3.8.5
* **make**:  4.2.1

i have tried to build nodejs for 13 times, and every time, it cost me about 1 hours and 13 minutes. oh my god. please help me. teachers!

**Comment by PoojaDurgad** [comment]
@anlexN - IMO, I have also tried to build nodejs on ubuntu platform. It cost more than an hour to build due to intermittent network connection. to increase the speed of building make use of make -j5 or make -j10 command (depending on your system) which will split the thread into multiple threads and allows you to cost less time. 
let me know if it makes sense to you.

**Comment by anlexN** [comment]
oh my god. so what system do you recommand to build nodejs?

**Comment by gireeshpunathil** [comment]
My observation is ~20 minutes of work - in a single CPU system
 - if you have 2 CPUs, run with `-j2` , makes it ~10 mins
 - " " 4 CPUs, " .. `-j41` to make it ~5 mins
 - so on and so forth

**Comment by anlexN** [comment]
why need `-j` arg? i just `make`, in theory, make should use infinite jobs.
![image](https://user-images.githubusercontent.com/8686739/96226496-4d9c6080-0fc5-11eb-97da-378fec2f5209.png)

**Comment by gireeshpunathil** [comment]
`infinite jobs with no arg.` is meant for `-j` flag. That is:
 -j100 means 100 jobs at once
 -j means infinite jobs at once // this can be tricky, based on your CPU availability though. (I never tried this)

**Comment by anlexN** [comment]
@gireeshpunathil 

1. this is my system information:
![image](https://user-images.githubusercontent.com/8686739/96279267-05069680-1009-11eb-935a-2cbf3ae1f747.png)
2. i am using windows wsl ubuntu 20.04
3. i turn on my computer performance mode.

**but i `make -j4`, it still costs me more than 1 hour, and you can see my cpu temperature is almost 100C. oh my god! what happened?**

**Comment by gireeshpunathil** [comment]
@anlexN - sorry, most of the letters in the screen is not readable for me (I guess it is Chinese?).  Do you have a mechanism to figure out how many CPUs are there in your system? If not, can you get the output of `systeminfo` in the command line ? that will tell us.

If there is only one CPU, then adding `-j` flag is of no use. Only if there are multiple CPUs, the work can be parallelized and thereby time saved.

with respect to CPU temperature - I guess most of the work involved in building node from source is compilation, which is heavily CPU bound, the momentary spike in heat level is justified.

**Comment by anlexN** [comment]
this is my `systeminfo`:
![image](https://user-images.githubusercontent.com/8686739/96326187-15e2f680-1061-11eb-9a67-c1f934f8bc8b.png)

my computer customer service tell me all lenovo computer have only one CPU, include me. so i can not `make -j`, so nodejs need us have a very high hardware requirement? @gireeshpunathil , can you give me your `systeminfo`?

**Comment by gireeshpunathil** [comment]
I have many systems that I work on.

Mainly, a linux box with 120 CPUs and 1 TB memory - this takes only `a` minute to build node.

My laptop is an apple macbook with:
```
  Processor Name:	Intel Core i5
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
```

as I told, this takes ~20 minutes with `-j4`.

This this because when there are 2 cores, it is as good as having 2 CPUs from the program's perspective.

Again, with 2 cores and hyperthreading, each core can execute roughly 2 jobs in parallel.

So consider this as having ~4 CPUs. So I usually give `-j4`. It still heats up the CPU a little, but as I know it is a computation intensive operation and is bound to limited time, I will wait.

**Comment by anlexN** [comment]
@gireeshpunathil can you try to build in windows wsl ubuntu 20.04? please.

**Comment by gireeshpunathil** [comment]
@anlexN - sorry, I don't have such a system. But let me see, if one of my colleague can try this. Will get back in couple of days.

**Comment by anlexN** [comment]
i am waiting for you, teacher.

**Comment by sxa** [comment]
I would say that an hour or so for building Node.js was reasonable for such a configuration. There is a lot of code in Node.js including athe V8 runtime. If you're going to be building it multiple times I'd recommend using ccache which will make subsequent runs significantly faster.

**Comment by anlexN** [comment]
changing nodejs build system is so necessary!

**Comment by sxa** [comment]
Do you have any specific proposals? I'm not sure (other than ccache, or using a very large machine) how you can speed it up with a change to the build system.

**Comment by anlexN** [comment]
i turn on my lenovo computer performance mode: Fn+Q, high performance NVIDIA GPU, battery high performance plan.
but still cost 1 hour. oh my god.

**Comment by sxa** [comment]
No - my main system is Linux and about an hour seems consistent with what we'd expect. I'm not sure what you expect us to do here. If you have any specific suggestions on how to speed things up then let us know, but compilation of the amount of code we have is going to take time.

**Comment by anlexN** [comment]
i hope to decrease build time, i think you can try another build system: GN or Ninja or Bazel.

**Comment by anlexN** [comment]
nodejs source code have perl file, oh my god! now at total, there are 7 languages: c, c++, python, javascript, torque, shell, perl. oh my god. can we give up perl language?

**Comment by sxa** [comment]
The Node.js codebase includes versions of third party components which are built and statically linked in during the build process. The perl code is mostly from the openssl and ICU componenets (plus the one from the CURL project for SSL CA certs) and it would not be appropriate to diverge from what those dependent projects use.

**Comment by anlexN** [comment]
it costs me so long time to understand node source code, oh my god.

**Comment by PoojaDurgad** [comment]
looks like it can be closed now . pls let me know if that is not the case

**Comment by J-Cake** [comment]
> I have many systems that I work on.
> 
> Mainly, a linux box with 120 CPUs and 1 TB memory - this takes only `a` minute to build node.

@gireeshpunathil  Good sir, where does one buy such a machine ? I want one :P

**Comment by F3n67u** [comment]
> > I have many systems that I work on.
> > Mainly, a linux box with 120 CPUs and 1 TB memory - this takes only `a` minute to build node.
> 
> @gireeshpunathil Good sir, where does one buy such a machine ? I want one :P

I am also very curious how you can buy such a monster computer?

**Comment by leizongmin** [comment]
It took 7 minutes to compile on my machine (32 cores 64G memory, GCC 8.3.0).

**Comment by J-Cake** [comment]
> It took 7 minutes to compile on my machine (32 cores 64G memory, GCC 8.3.0).

~ 11 mins. and two failed attempts on my end. not too bad

**Comment by gireeshpunathil** [comment]
> @gireeshpunathil Good sir, where does one buy such a machine ? I want one :P

honestly, I don't know. I use machines from my company, that are purchased and installed by h/w folks. :P

**Comment by gireeshpunathil** [comment]
> Wow that's quite the equipment they've got there. Mind me asking what the company is?

sorry, but I think it is off-topic as it does not directly contribute to the resolution of the issue. (my GitHub profile contains my details)

**Comment by anlexN** [comment]
it's nodejs build system problem by itself, not a money problem, not a computer problem.

**Comment by ytxmobile98** [comment]
Tried using a DELL Inspiron 14 Plus laptop and a DELL Optiplex 7090 desktop.

* OS: Inspiron 14: Ubuntu 22.04 LTS; Optiplex: Ubuntu 22.04 LTS as WSL on Windows 11 21H2.
* CPU: Inspiron 14 uses i7-12700H; Optiplex uses i7-12700.
* Memory: Inspiron 14 has 16 GB (8 integrated + 8 slot); Optiplex has 32 GB (8 + 8 + 8 + 8).

Build commands:
```bash
sudo apt install build-essential ninja-build
./configure --ninja
make -j
```

* Inspiron 14 Plus: **The build process died half-way.**
* Optiplex 7090: **11m23.318s**
     ![Screenshot_20221130_045709](https://user-images.githubusercontent.com/5900105/204753639-9822a278-5753-4d74-bcad-125a661c9b09.png)
