### ISSUE TITLE
Debugging Node

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/help#3016]
How do I generate a stack trace like [this](https://github.com/nodejs/node/issues/35559#issuecomment-705994460) for Node.js?

**Comment by addaleax** [comment]
@RaisinTen That stack trace comes from `gdb`, a popular debugger for C/C++ code. `lldb` would also be able to generate similar stack traces.

**Comment by RaisinTen** [comment]
@addaleax thanks for the response. I did use `gdb` for debugging some C/C++ codes but I'm not quite sure how I'm supposed to use it for node.

**Comment by Srinivasa314** [comment]
Run `gdb --args node file.js`

**Comment by addaleax** [comment]
@RaisinTen In a case like the one you linked, you could either:

- Run `gdb --args node test.js`, then `run` to start the program and use `bt` for the backtrace once it crashes
- Run `node test.js` (in a way that would generate a coredump, i.e. with `ulimit -c unlimited`), then use `gdb node core` to load the core file and then run `bt` once that is loaded.

You can also always run `gdb --args node ...`, use `run`, and then press Ctrl+C to interrupt the process and then generate a backtrace.

**Comment by RaisinTen** [comment]
Thank you so much! :slightly_smiling_face:
