### ISSUE TITLE
not able to handle large amount of xlsx data, any suggestion for it.  

### ISSUE THREAD

**Issue by Mkishanparmar** [nodejs/help#3018]
not able to read 80000 records from xlsx, facing stack smashing.

**Comment by PoojaDurgad** [comment]
@Mkishanparmar  - can you elaborate your issue more please? and https://github.com/SheetJS/sheetjs/issues/1136 does this answer to your question ?

**Comment by jansivans** [comment]
You can use https://github.com/Claviz/xlstream library.

**Comment by PoojaDurgad** [comment]
closing as answered. pls feel free to reopen the issue if its still outstanding
