### ISSUE TITLE
Double Backslash Escape Problem

### ISSUE THREAD

**Issue by MrAkblt** [nodejs/help#3019]
* **Version**: 13.12.0
* **Platform**: arch
* **Subsystem**:

Escape does not work as expected in node shell.

![image](https://user-images.githubusercontent.com/9157723/95754057-2a16a480-0cab-11eb-984b-fbdc1a37567b.png)

![image](https://user-images.githubusercontent.com/9157723/95754333-8974b480-0cab-11eb-9385-5a4ea01c48d3.png)

**Comment by MrAkblt** [comment]
@addaleax I know but is this behavior misleading just to me? I don't think it is correct. Then how can i produce a single backslash in node shell ?

**Comment by addaleax** [comment]
@MrAkblt You just did – when you write `'\\'` in a Node.js program, including in the REPL, you get a string containing a single backslash. Using `console.log(str)` will print the raw content of `str` if it is a string, so you can use that to display it.

**Comment by amokmen** [comment]
@addaleax 
> when you write `'\\'` in a Node.js program, including in the REPL, you get a string containing a single backslash

Wrong. For Node 14.16.0 REPL:
```
> "\\"
'\\'
```

So, no way to get single backslash.

**Comment by addaleax** [comment]
Let’s close this, it’s been answered.

**Comment by jakepielage** [comment]
So what is the solution? Google chrome throws a fit when I do \\
