### ISSUE TITLE
Want team maintainer permission for nodejs/nodejs-ko

### ISSUE THREAD

**Issue by marocchino** [nodejs/help#302]
Hi.
Recently we noticed that mentioning @nodejs/nodejs-ko does not reaching to all members.
It is because some members are repository maintainers. 
So, we want rearrange our members, but we do not have permission for that.

ref:
nodejs/nodejs-ko#425
https://help.github.com/articles/giving-team-maintainer-permissions-to-an-organization-member/

**Comment by bnoordhuis** [comment]
Apparently nodejs-ko was never migrated to the new GH team structure.  I just did that and I promoted you to team maintainer.  Anything else that needs to be done?

**Comment by marocchino** [comment]
That is it for now.
Thanks! 👍
