### ISSUE TITLE
Node.js cannot find the module.

### ISSUE THREAD

**Issue by wariomejia** [nodejs/help#3020]
* **Version**: v14.13.1
* **Platform**: Windows (10)
* **Subsystem**:10

![error node](https://user-images.githubusercontent.com/72531016/95782709-8f5b9d00-0c8d-11eb-95ab-9b607e1eef52.png)

![json file](https://user-images.githubusercontent.com/72531016/95783023-38a29300-0c8e-11eb-86e0-774a14c922b4.png)

![myfirstjs](https://user-images.githubusercontent.com/72531016/95783065-4a843600-0c8e-11eb-8561-c5939e42f54a.png)

I don't know why doesn't work.
I have uninstalled, delete the cache and installed again, but doesn't work.

**Comment by wariomejia** [comment]
> 
> 
> What's the result if you type `DIR` in the command prompt?

It shows this:

![dir screenshot](https://user-images.githubusercontent.com/72531016/95799704-bbd5e000-0cb2-11eb-893c-505318669a39.png)

**Comment by alex996** [comment]
@wariomejia Did you save the file as `myfirst.js.txt` instead of `myfirst.js`?

**Comment by wariomejia** [comment]
Wait a second... 
No, the file was saved as myfirst.js, but apparently the bloc adds the ".txt" extension *__*.
![screenshot js](https://user-images.githubusercontent.com/72531016/95821335-f9546080-0ce6-11eb-9d5c-8a1274cbdd8f.png)

Thank you!
If I add the extension it works.
