### ISSUE TITLE
directions for checksum verification don't work for windows. 

### ISSUE THREAD

**Issue by karinaGuenther** [nodejs/help#3021]
* **Node.js Version**: 6.9.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: checksum verification instructions
* **Module (and version) (if relevant)**:

Your webpage of how to perform checksum assumes the use has linux / mac commands available and not windows. specifically

`grep node-vx.y.z.tar.gz SHASUMS256.txt | sha256sum -c -`

doesn't work. 

```
10/13/2020  01:08 AM    <DIR>          .
10/13/2020  01:08 AM    <DIR>          ..
10/13/2020  01:04 AM        19,865,600 node-v12.19.0-x64.msi
10/13/2020  01:10 AM            10,858 SHASUMS256.txt
               2 File(s)     19,876,458 bytes
               2 Dir(s)  1,959,602,720,768 bytes free

D:\myProgramming\checksum>grep node-v12.19.0-x64.msi SHASUMS256.txt | sha256sum -c -
'grep' is not recognized as an internal or external command,
operable program or batch file.'

```
Could you put on your checksum page instructions for windows 10 users? If you are doing it for mac users you should also do it for windows. or point to a place for windows users. 
`This is the links: https://github.com/nodejs/node#verifying-binaries`

-->

**Comment by gireeshpunathil** [comment]
@karinaGuenther - good catch! do you want to raise a PR to fix this? If so, here is the contribution guidelines:  https://github.com/nodejs/node/blob/master/CONTRIBUTING.md .
