### ISSUE TITLE
Cannot upgrade or uninstall node.js v0.12.18

### ISSUE THREAD

**Issue by whitekd** [nodejs/help#3022]
* **0.12.18**:
* **Windows 10**:
* **install/update**:

I currently have node.js v0.10.24-x64 installed on my machine and am attempting to update to v12.19.0-x64. When I run the v12.19.0-x64.msi installer, I see this error message: https://i.stack.imgur.com/J1mAK.png

Clicking 'cancel' then gives this message, indicating that the installer is trying to remove a prior installation of node: https://i.stack.imgur.com/6Vcme.png

I've tried uninstalling my current node.js installation and then installing the newer version from scratch, but this process gives me the same result. How can I completely remove node.js from my system so that I can install the new version without errors?

**Comment by leaverger** [comment]
Could you still explain how you uninstalled your node.js? I am a complete noob and I installed this today, thinking i would know how to use it, but i have no clue and would like to get rid of it now.

**Comment by PoojaDurgad** [comment]
@whitekd - for me your issue looks like there are still pending folders of current version of node which is not allowing to install updated version. can you try `npm cache clean --force` and uninstall from 'programs and features' with uninstaller. look for the folders `npm` `Nodejs` `npm-cache` remove them if they still exist and make sure there is no references to `npm` and `Nodejs` and reboot if needed and then try to install updated version. I guess it will work.

@leaverger -  In a web browser, navigate to https://nodejs.org/en/download/. Click the Windows Installer button to download the latest default version.  The Node.js installer includes the NPM package manager. after the installation check node and npm version with `node -v` and `npm -v` on prompt.
for your reference https://phoenixnap.com/kb/install-node-js-npm-on-windows

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to reopen the issue if its still outstanding
