### ISSUE TITLE
Child_Process not working properly with Python

### ISSUE THREAD

**Issue by 23subbhashit** [nodejs/help#3023]
I am making a Command Line interface using nodejs for a packet sniffer.

 Link: https://github.com/23subbhashit/Command-Line-Interface

As part of my college curriculum, i have to use python for writing sniffing algorithms. But it was not showing any output when i installed some python packages(dpkt, pcap).

I am using Child_process to connect both. 
I am not able to understand how to deal with it.

* **Node.js Version**: v12.18.1
* **OS**: Windows

For the code, you can visit the repo link attached.

**Comment by gireeshpunathil** [comment]
@23subbhashit - is it outstanding? if yes, can you share the code that you are attempting and still not working?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
