### ISSUE TITLE
Worker thread post message performance

### ISSUE THREAD

**Issue by davidchappelle** [nodejs/help#3026]
* **Node.js Version**: v12.18.4
* **OS**: Ubuntu 18.04 LTS
* **Scope (install, code, runtime, meta, other?)**: code/runtime
* **Module (and version) (if relevant)**: worker_threads

I am using perf_hooks to help track down some issues that I have with the event loop getting blocked. I am measuring the overhead of posting a message to a worker thread and noticed that sometimes it can take upwards of 100+ms to post a message to a thread. I am curious where this latency is coming from as it seems that posting a message should be more or less constant time and very lightweight:
```js
            const message = 'marco'
            const start = performance.now();
            myWorker.postMessage(message);
            const end = performance.now();
            console.log(`worker_thread:postMessage ${end - start} ms`);
```

I also tried to find the underlying code for the postMessage but was unable to locate any specific code. If someone could point me to that code as well that would be great.

**Comment by gireeshpunathil** [comment]
@davidchappelle - is it outstanding? Is the message that is being sent a constant one, or what you supplied was just an example? IOM, the effort in the `postMessage` is a function of the nature, type and size of the message.

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
