### ISSUE TITLE
addon object destructed

### ISSUE THREAD

**Issue by craterone** [nodejs/help#3027]
* **Node.js Version**:
13.0.0+
* **OS**:
Ubuntu 18.04
* **Scope (install, code, runtime, meta, other?)**:
node & node addon(C++)
* **Module (and version) (if relevant)**:
nan

I implement a udp server by libuv(node addon), and I find wrapper object in nodejs will be released if I use node's version after 13.0.0

I can also reproduce this issue by  [node-addon-examples](https://github.com/craterone/node-addon-examples/tree/master/6_object_wrap/nan)

**Comment by addaleax** [comment]
> I can also reproduce this issue by node-addon-examples

This is expected, unless you call `Ref()` on an `ObjectWrap`, it will be considered weak and garbage-collectible.

**Comment by craterone** [comment]
@craterone Thanks for your reply. I s there  any document or demo about how to use `Ref()`?

**Comment by addaleax** [comment]
There is https://github.com/nodejs/nan/blob/master/doc/object_wrappers.md#api_nan_object_wrap

**Comment by craterone** [comment]
I tried to call `Ref()` in `New` method, but I got an error. 

```bash
node: ../node_modules/nan/nan_object_wrap.h:93: virtual void Nan::ObjectWrap::Ref(): Assertion `!persistent().IsEmpty()' failed.
```

**Comment by addaleax** [comment]
Then you called `Ref()` on an `ObjectWrap` that has no object associated with it, or that has already been garbage-collected

It’s unlikely that we can help you more without you sharing your code

**Comment by craterone** [comment]
Sorry, I didn't make it clear. How about this demo? Where should I call `Ref()`? 
c++ : https://github.com/craterone/node-addon-examples/blob/master/6_object_wrap/nan/myobject.cc
js : https://github.com/craterone/node-addon-examples/blob/master/6_object_wrap/nan/addon.js

**Comment by addaleax** [comment]
Right after `obj->Wrap(...)` should work (and keep in mind that you also need to call `Unref()` once you’re done with the object)

**Comment by craterone** [comment]
Thank you very much, it worked.
