### ISSUE TITLE
terminal color goes wrong after spawn

### ISSUE THREAD

**Issue by ui3o** [nodejs/help#3028]
# Syndrome

**On windows after spawn** the terminal color are not displayed well.

* **Node.js Version**: v12.19.0
* **OS**:  windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: spawn

✔ The first colored line display well but after the spawn
✖ The **second colored line wrong**

```js
const { spawn } = require('child_process');

async function test() {
    console.log('\x1b[36m%s\x1b[0m', 'I am cyan');
    await run('echo Hello world!');
    console.log('\x1b[36m%s\x1b[0m', 'I am cyan');

    async function run(scrpt) {
        const cmd = spawn('bash', ['-c', scrpt], { stdio: 'inherit' });
        return new Promise((resolve) => {
            cmd.on('close', (code) => resolve(code));
        });
    }
}

test();
```

- Cygwin is installed
- bash is available on the path

![image](https://user-images.githubusercontent.com/43638725/96153298-d22ba800-0f0d-11eb-97e9-6b005d655ceb.png)

Anybody knows what is wrong with this code? 

Thank you!

**Comment by bmuenzenmeyer** [comment]
This question is idle and left unanswered for years now.

- Does the behavior persist if you upgrade to a new version of Node.js? This reported version is [end of life](https://github.com/nodejs/release#release-schedule).
- Have you attempted to ask this question within other communities, such as [stackoverflow](https://stackoverflow.com/questions/tagged/node.js?tab=Newest)?

I am going to circle back in a couple weeks to see if we can close as no-longer relevant.

----


FWIW, I ran the above in a Node 16.X REPL and got correct behavior:

![image](https://user-images.githubusercontent.com/298435/201336995-50e192f1-1bdf-45f8-a514-7f5582f8e3f4.png)

**Comment by bmuenzenmeyer** [comment]
closing per the above plan
