### ISSUE TITLE
Not able to install Appium on ubuntu : Please tell further steps

### ISSUE THREAD

**Issue by jayshreekant** [nodejs/help#303]
I am getting below error

0.9 

npm WARN optional Skipping failed optional dependency /appium/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jay/npm-debug.log
[npm-debug.txt](https://github.com/nodejs/help/files/491816/npm-debug.txt)

**Comment by addaleax** [comment]
Hi! https://docs.npmjs.com/getting-started/fixing-npm-permissions might help you?

**Comment by bnoordhuis** [comment]
Or drop the -g (for 'global') flag.  It's trying to install to /usr/local but most of the time you can just install packages somewhere under your home directory.

**Comment by Vikas-Jilla** [comment]
go through this link and follow each step it worked fine for me
https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md
