### ISSUE TITLE
show error can you please tell me the solution of error

### ISSUE THREAD

**Issue by akshin531** [nodejs/help#3031]
## Populating apt-get cache...

+ apt-get update
Ign:1 http://ppa.launchpad.net/micahflee/ppa/ubuntu groovy InRelease          
Err:2 http://ppa.launchpad.net/micahflee/ppa/ubuntu groovy Release            
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Hit:3 https://packages.atlassian.com/debian/atlassian-sdk-deb stable InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/micahflee/ppa/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

**Comment by PoojaDurgad** [comment]
@akshin531 - For me this issue looks like, this is not a problem with nodejs may be you are using old launchpad PPA which is not stable. so can you please try to use our Nodesource distributions https://github.com/nodesource/distributions instead.
hope it may help.

**Comment by PoojaDurgad** [comment]
closing as answered. please let me know if its  still outstanding.
