### ISSUE TITLE
Running Node results in "Dependencies were not found"

### ISSUE THREAD

**Issue by ChrisMcHarvey** [nodejs/help#3035]
* **Version**: 12.19.0
* **Platform**:  Windows 10 64-bit
* **Subsystem**:  Issue arises when requiring node-odbc in a NuxtJS project

### What steps will reproduce the bug?
Have NuxtJS and at some point in your project include the lines:
`const odbc = require('odbc')` or `const mysql = require('mysql')` or any other libraries that require fs or child_process or tls

### How often does it reproduce? Is there a required condition?
Every time as far as I've been able to create.

### What is the expected behavior?
The expected behavior would be the Nuxt project fully compiles but no luck.

### What do you see instead?
![image](https://user-images.githubusercontent.com/14862980/96936393-f3534200-1493-11eb-92f1-c8d1105cf988.png)

**Comment by PoojaDurgad** [comment]
@ChrisMcHarvey - is this still an issue ? by looking at the error I can say it requires some of the dependencies to run. have you installed those dependencies? if not can you install and try what it comes?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
