### ISSUE TITLE
Tool to check package quality

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/help#304]
Hello there, I am looking for a tool to test the quality of a package that I am writing. I am looking for following features (some would be good, all would be great):
- It should be possible to be run just like "standard" as part of my tests (so either exiting with 1 or 0)
- It should check if my package is loaded quickly (< 10ms)
- It should check if there is a license & readme at my package
- It should check the contributors field of the package json and compare it to the git contributors
- It should check if it has a valid license field
- It should check for the use of deprecated API's
- It should check (in case its published) if there is more than one person added as owner in npm
- It should check if the package uses non-simple require statements (i.e.: `require('data/' + some + '/.json')`)
- It should have a flag to check if it uses API to access the filesystem or subprocesses (i.e.: `require('fs')` and `require('child_processes')`)
- It should fail if a file-system or subprocess API is called before the module finishes loading
- It should check ALL depending packages for non-simple dependencies and require('fs') tags as well...
- It should fail if the version is `< 1.0.0` (pre-version)
- It should check if there are `images` - that are part of the `Readme` also published 
- By default it should check that there is max. 1 binary and it should point to `./bin/<package-name>`
- It should verify that there is a `lint` script as part of the scripts section, and it returns without error
- It should check if a `test` script exists and that test returns 0 _(maybe even support for coverage?)_
- It should check if the package points to a github repo and that repo contains a package.json with the same name
- It should check if it uses global variables (such as process.env) outside of the binary.
- It should check whether none of the dependencies is circular.

Preferably: it checks everything highly parallel and not serial (because that takes time) and it has flags to en/disable everything

**Comment by martinheidegger** [comment]
cc. @Richardlitt

**Comment by RichardLitt** [comment]
This would be a great tool to have. 

We have something similar set up at github.com/ipfs/project-repos: you can see our Readme's at https://project-repos.ipfs.io/. However, this mostly does soft checks at the moment - is there a README, what's in it. It doesn't do stuff like check the package load or the actual code itself, it just tests what you've put in the README. I am hoping to extend it over the next few months to fill a few of the needs you've specified here. 

I'll happily keep this open and keep referring to it; I think this tool would be a good thing to make.
