### ISSUE TITLE
(node:87) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by siddjain** [nodejs/help#3040]
* **Node.js Version**: 

node -v
v12.18.1

* **OS**:

uname -a
Linux b8d5107fc64e 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64 Linux

(using node:12-alpine Docker image)

I have following code:

```
process.on('unhandledRejection', (reason, promise) => {
  logger.error(`Unhandled Rejection at: ${promise} reason: ${reason}`);        
});
```

and it is triggering following warning:

```
(node:87) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**The code is not inside any for loop**. I am executing it only once. It seems like a bug.

**Comment by dark-magic** [comment]
add a log above the `process.on('unhandledRejection', ...)` and see how often it is logged. those 11 eventlisteners have to come from somewhere

**Comment by siddjain** [comment]
That's a good idea. Thanks. I tried it and see log message only once.
2020-10-28T17:36:59.813Z [Main] info: adding unhandledRejection handler
(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit

________________________________

**Comment by dark-magic** [comment]
thats weird. is it possible you add that event handler somewhere else? maybe log the event-emitter with console.dir. i believe it shows the registered event handlers.

**Comment by preveen-stack** [comment]
@siddjain any updates on this issue? Did you get a chance to try with latest nodejs version
