### ISSUE TITLE
Add bom to stream

### ISSUE THREAD

**Issue by codevladimir** [nodejs/help#3043]
Hi, I am having issue when generating CSV file and opening it in excel. This is known issue and this can be fixed when downloading some CSV like this encodeURIComponent("\uFEFF"+csvString), basically just by adding "\uFEFF" at the beginning. 

Now the issue I have is when generating CSV with stream. I use pg-query-stream and then I use pipe createGzip() to zip the CSV. So I can't use "\uFEFF" anymore as I described above. Is there any way to solve this?

**Comment by gireeshpunathil** [comment]
@codevladimir - is this still outstanding? If I understand your issue correctly, you will need to `prepend` a specific character at the beginning of a string. And you are able to do it when the data is buffered , but unable to do it when the data is flowing, as a stream. Is this correct? If so, you can use [transform streams](https://nodejs.org/dist/latest-v16.x/docs/api/stream.html#stream_implementing_a_transform_stream), that allow flowing data to be transformed / altered on the fly. 

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
