### ISSUE TITLE
internal/modules/cjs/loa der.js:638     throw err;

### ISSUE THREAD

**Issue by lopeselio** [nodejs/help#3046]

**Comment by PoojaDurgad** [comment]
@lopeselio - can you elaborate your issue more please?

**Comment by lopeselio** [comment]
Hey @PoojaDurgad I tried workarounds and finally resolve the issue: 
1.Delete the node_modules directory
2.Delete the package-lock.json file
3.Run npm install
4.Run npm start
OR
rm -rf node_modules package-lock.json && npm install && npm start

There were some conflicts after installing npm package.
