### ISSUE TITLE
nodejs version 12 has different behavior depending on if await is called or not 

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#3047]
Node.js Version: 12.18.1
OS: ubuntu linux

this script:

```js
let i = 0;
(async function foo(){
  console.log(i++);
  foo()
})()

foo()
```

runs different than this:

```js
let i = 0;
(async function foo(){
  console.log(i++);
  await 3;
  foo()
})()

foo()
```

in the latter I get "foo is undefined"

**Comment by vsemozhetbyt** [comment]
You have no function `foo` in both variants: you have named function expression, its name can be used only inside this named function, no `foo` variable in the outer context is created. In the first code you have unbreakable recursion so the reference error cannot be reached: no `await` means all the recursion is executed in one mikrotask. In the second variant await breaks recursion and reference error is reached.

**Comment by vsemozhetbyt** [comment]
Compare the order:

```js
(async function foo(){
  console.log(1);
  console.log(2);
})()

console.log(3);
```

vs

```js
(async function foo(){
  console.log(1);
  await '';
  console.log(3);
})()

console.log(2);
```

**Comment by RedYetiDev** [comment]
Hi! Sorry for the long delay,
NodeJS v12 is **no longer supported**.

I'm working on closing out some old issues on the nodejs/help repository, and if you disagree with this decision, please **ping** me.
