### ISSUE TITLE
What are test fixtures?

### ISSUE THREAD

**Issue by whosmayank** [nodejs/help#3049]
From what I understand from googling, test fixtures are meant to be just readable. Is that right? If I create a new file in test/fixtures, can I assume that other tests will not change the file?

For a unit test I am writing, I need to use the 'x.txt' file in test/fixtures. If I use that file, is it confirmed that x.txt will never change?

Also, my requirement is basically a file with some text in it. Is it advised to create a new file using fs.writeFile (in test/fixtures?) and write text in it or use existing files in test/fixtures? Why?

**Comment by PoojaDurgad** [comment]
@iammack - I don't have deeper insight about this test-fixtures but if you create a new file in test/fixtures other tests will not change the file it seems . for example if you write a code test-fixtures.js , it will create test snippet for each one of the test fixtures that you specified within the fixtures directory. of-course You can implement this script in many different ways, its scope, however, should ideally not change much but  it should be to glue your scenarios and the underlying test runner.
for more detail I suggest you to refer this https://goodguydaniel.com/blog/unit-testing-with-fixtures-unleashed

**Comment by vyomks5** [comment]
If we have some tests that have similar needs we can group them into a TestFixture.

**Comment by marsonya** [comment]
I believe @PoojaDurgad has answered this question and the [link](https://goodguydaniel.com/blog/unit-testing-with-fixtures-unleashed) she share is quite informative on this topic. I hope it helped.
I am going ahead and closing this issue for now. In case there is anything else you want to add to it, you can always reopen this issue.
