### ISSUE TITLE
Nodejs Session in socket.io

### ISSUE THREAD

**Issue by ajithv11** [nodejs/help#305]
Hello,

In my project I used nodejs and socket.io for a chat application. My purpose is to integrate nodejs chat in a section on another website build using php  frmeworks . So my request are all through socket.io emit. So user registration authentication etc is done using emit data. I face a problem for managing section < so is it possible to set session using socket.io emit either through any extention. Now i face the problem of login on each page refresh.

**Comment by addaleax** [comment]
So, maybe this is just saying something obvious, but maybe you can store authentication data in `document.cookies` or `localStorage`?

**Comment by lordKnighton** [comment]
are you having any luck with this ajithv11?

**Comment by ajithv11** [comment]
Hi,

Here I will describe the requirement for my project.

Basically I want to build a chat application which I can embed to different websites for example , site build using wordpress, magento, drupal, custom frameworks ... etc . What I actually need is to embed JavaScript for handling socket chat using (socket.io) . The problem I faced is to manage session for registered users after login. **Since my code is embedded on different websites and the node server  resides on other server , On each page refresh I faced difficult to set session.** Could you please help me how I can manage session in a best way for this application.

If you feel difficulty to understand my need , I can explain in detail with examples

Thanking You
Ajith V

**Comment by ajithv11** [comment]
Any help or suggestion, Please reply
