### ISSUE TITLE
npm not installed

### ISSUE THREAD

**Issue by VictorPro007** [nodejs/help#3050]
Hello, I recently installed NodeJS and  when I check if npm is installed, it says this:
```
C:\Users\victo>npm -v
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\victo\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```
and here's my OS and NodeJS version:
* **Node.js Version**: 14.15.0
* **OS**: Windows 10 64 bits
Can someone help me, please?

**Comment by PoojaDurgad** [comment]
@VictorPro007 - run `where node` and `where npm` and update the node path on system variable . if you still coming around this thread install node from official website https://nodejs.org/en/download/ which will install the latest stable version of node and npm.

**Comment by VictorPro007** [comment]
Fixed! Thanks

**Comment by PoojaDurgad** [comment]
closing as resolved.
