### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by ThiliniWijekoon** [nodejs/help#3051]
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by ORESoftware** [comment]
npm install

**Comment by PoojaDurgad** [comment]
@ThiliniWijekoon - looks like no longer an issue . if yes can you close the issue please?

**Comment by PoojaDurgad** [comment]
closing as answered. please feel free to reopen the issue if that is not the case

**Comment by vamsi4593** [comment]
Hi, I am facing the same issue , how was it fixed ?
node version : . 14.15.4

I sued npm install command , but ended up with the same error.Help is much appreciated.

**Comment by sachin-007** [comment]
i have this error please help me get out me from here

**Comment by ThiliniWijekoon** [comment]
while installing nodejs I have changed the custom setup to npm package
manager. then my error was cleared. also please check whether path of npm
is set or not

**Comment by Nelson877** [comment]
i am only facing Error please can someone help me out ..........this are the error [
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
