### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by rabeeshcharles** [nodejs/help#3053]
* **Node.js Version - 12.16.1**:
* **OS - Windows**:
* **Scope  - runtime**:

Explaination
-------------------
- I have Run this below sample using pm2 npm 
- Then monituring the memory usage,its getting increased automatically even without giving any load test on this API or a single Call

So Guys, Plz Suggest me some ideas regarding this...

```js
Sample Code
------------------
try {
    const express = require('express');
    const app = express();
    var port = 3007;
    // var cron = require('node-cron');

    app.get('/', (req, res) => {
        res.send('SUCCESS');
    });
	
    app.listen(port, () => {
        console.log(`server is listening in PORT - ` + port);
    });
} catch (error) {
    console.log(error, '============ Catch Error ==============');
}

```

![image](https://user-images.githubusercontent.com/30102705/97896645-62198080-1d5b-11eb-9559-50ad900d9f49.png)

**Comment by gireeshpunathil** [comment]
@rabeeshcharles - is it still outstanding? where and how is memory growing? In the screenshot you shared, I see 29.1 MB as a constant value between iterations?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
