### ISSUE TITLE
Node js

### ISSUE THREAD

**Issue by Adriano87** [nodejs/help#3056]
this application is only supported on Windows 8.1, Windows Server 2012 R2, or higher
Eu estou usando o windows 8
a versão do node que uso é Node.js Node.js Foundation 12.19.0
a nova versão seria 14.15.0
Não estou conseguindo baixar essa nova versão 14.15.0

**Comment by PoojaDurgad** [comment]
@Adriano87 -  Install the latest node version by visiting the official website https://nodejs.org/en/download/ for node.js and you'll be able to download the Windows Node.js installer by clicking the Windows Installer option at the top of the page - when you click this, you'll get an MSI installer download. run the node.js installer.

**Comment by Adriano87** [comment]
[image: node.PNG]

Em qua., 4 de nov. de 2020 às 09:52, Pooja D P <notifications@github.com>
escreveu:

**Comment by PoojaDurgad** [comment]
@Adriano87 - I am unable to open your tagged image. can you explain the context please?

**Comment by PoojaDurgad** [comment]
inactive. closing, please feel free to reopen the issue if it is still outstanding
