### ISSUE TITLE
Node for windows 64 bits

### ISSUE THREAD

**Issue by websus** [nodejs/help#306]
Hello thanks for redirect me here, I've been having troubles to download the 64 bits version of node. Its like the internet connection dies at the few bytes downloaded and then marks a download speed of 0 bytes.

I tried to download it yesterday same problem. Got no choice so I downloaded it from bitnami with no problem but I would like to download it from your source.

If anyone can help me would be great, thanks!

**Comment by GitterHubber** [comment]
What version of node are you trying to download? Also if you could provide the link that is failing I could check if out on my side and see if its failing for me too!

**Comment by websus** [comment]
I did it today and it worked lol, it was this link https://nodejs.org/dist/v4.6.0/node-v4.6.0-x64.msi

Thanks!
