### ISSUE TITLE
Permission issue for windows 10 for execSync(`cd ${test}`);

### ISSUE THREAD

**Issue by subasu1** [nodejs/help#3060]
I am trying to enter to cd C:\Program Files\WindowsApps\ and trying to get all file path and file sizes. Seems like it is not able to cd to that location on windows 10. Can someone quickly help here ?

**Comment by bzoz** [comment]
`WindowsApps` is a special folder for sandboxing UWP apps. You won't be able to access it with other tools too, at least without [taking some extra steps](https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/what-is-windows-apps-hidden-folder-and-why-cant-i/40a60508-c409-422a-af92-bd51fe5a4ca9).

I'm going to close this, as this is just the way things are on the Windows OS.
