### ISSUE TITLE
Nodejs 10.17.0 NASM version

### ISSUE THREAD

**Issue by 3DGISKing** [nodejs/help#3061]
* **Node.js 10.17.0**:
* **Windows10 64bit**:
* **building Nodejs**:

I have tried to build nodejs 10.17.0
What I tried
1 install Python 2.7.17
2 install NASM 2.13
3 install Visual Studio 2017 Community
4 build
  “cmd /c vcbuild.bat x64 noetw nosign noperfctr”
   After the build was completed, I checked nasm version.
   It shows 2.14. Actually, I installed 2.13.

   Why does this happen

  
![image](https://user-images.githubusercontent.com/26606704/98239780-718b0a80-1fa3-11eb-82dd-94c38b92d467.png)

**Comment by gireeshpunathil** [comment]
@3DGISKing  - what does `asm -v`print?
looks like
https://github.com/nodejs/node/blob/869ded3b0e9b1f53b7161827bc2275a584881fc7/configure.py#L854-L855

is where `nasm_version` is computed.

**Comment by 3DGISKing** [comment]
Thank you for your response. 
It was fixed. Really my mistake. A previous pyc file was used.

Sorry, but can you explain the meaning of this command?

“cmd /c vcbuild.bat x64 noetw nosign noperfctr”

I have this [issue](https://github.com/vercel/pkg/issues/998).
Any tips would be appreciated!.

**Comment by gireeshpunathil** [comment]
x64: the target platform / arch
noetw: built without windows event tracing
nosign: don't (digital) sign the resulting binary
noperfctr: no performance counters in the build

**Comment by 3DGISKing** [comment]
great!
any tip for [issue](https://github.com/vercel/pkg/issues/998)

**Comment by gireeshpunathil** [comment]
replied there, inline. closing this issue are resolved, cheers!
