### ISSUE TITLE
avast blocked node.js

### ISSUE THREAD

**Issue by VictorPro007** [nodejs/help#3062]
Hello, I was creating my project and installing my modules,  but when I installed boxen from npm, avast alerted me that the app node.js was blocked because it's a ransomware and it was modifying the mit-text.txt or something like that. What should I do?

**Comment by nkrad** [comment]
Got this too. Sorry I can't help, but I'm in the same boat as you. 99% sure it's just a false positive, but would be nice to hear from someone with a bit better knowledge on the topic.

**Comment by Sylack-lab** [comment]
Disable avast if your working with node, and if possible report it as a false positive.

I personally never use antiviruses, they seem quite useless and cause more trouble.

**Comment by marsonya** [comment]
Hi @VictorPro007 - Incase you are sure that the version of node you have installed is download from the official source, you can follow the instructions [here](https://support.avast.com/en-ww/article/Antivirus-unblock-program-website/) to add ndoe to avast exclusion list.

If you haven't downloaded node from official source, I would strongly suggest you uninstall it and reinstall by downloading it from [https://nodejs.org](https://nodejs.org)

I hope this helps. I am going ahead and closing this issue. You can always reopen it incase there is more to add to the issue discussion.
