### ISSUE TITLE
Downloaded Latest Current Version: 15.1.0 (includes npm 7.0.8) but npm version 6.14.8 was installed instead

### ISSUE THREAD

**Issue by keaedwar** [nodejs/help#3063]
* **Node.js Version**: Latest Current Version: 15.1.0
* **OS**: Windows 10 Enterprise Version 1809
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

I uninstalled Node.js version 14.15.0 from my machine and made sure everything was gone (node was gone and npm was gone too).  I made sure to reboot after the uninstall to be sure nothing was locked.

I downloaded the "Latest Current Version: 15.1.0 (includes npm 7.0.8)" and ran the node-v15.1.0-x64.msi in an Administrator cmd tool.

Once it was installed I ran node -v and npm -v and got:

```
$ node -v
v15.1.0
$ npm -v
6.14.8
```

It looks like node got installed fine, but I didn't get npm version 7.0.8.  I know npm was removed because the folder where everything was installed is gone and now node and npm are installed in C:\Program Files\nodejs

Has anyone see this before?

**Comment by gireeshpunathil** [comment]
@keaedwar - is this still outstanding? it is worthwhile to review your `PATH` variable and see how `node` and `npm` are getting resolved. Many times we have seen that the stale values in the variable cause wrong / unexpected targets being picked up.

**Comment by keaedwar** [comment]
You can probably just close it. I started updating npm manually for a while.

When I went to Windows 10 Enterprise Version 20H2 I started to use Chocolatey to install tools.

**Comment by gireeshpunathil** [comment]
closing then, cheers! feel free to re-open if you happen to encounter this issue again.
