### ISSUE TITLE
Error: The module '\\?\C:\Users\gohid\Desktop\Zeltux_v1.1\node_modules\better-sqlite3\build\better_sqlite3.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 83. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).

### ISSUE THREAD

**Issue by Epic99992** [nodejs/help#3064]
Error: The module '\\?\C:\Users\gohid\Desktop\Zeltux_v1.1\node_modules\better-sqlite3\build\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

This what it says so I need to know how to fix it?

**Comment by PoojaDurgad** [comment]
@Epic99992 - can you refer this https://github.com/serialport/node-serialport/issues/1910 hope it helps.

**Comment by PoojaDurgad** [comment]
inactive. pls feel free to reopen the issue if its still outstanding
