### ISSUE TITLE
Date constructor

### ISSUE THREAD

**Issue by oleg-kucherenko** [nodejs/help#3066]
* **Node.js Version**: 12.18.1
* **OS**: Win10 64bit
* **Scope (install, code, runtime, meta, other?)**: Date object
* **Module (and version) (if relevant)**:

```js
let a = new Date();
a.setFullYear(2020);
a.setMonth(11);
a.setDate(1); // <--

let b = new Date(2020, 11, 1); 
let c = new Date(2020, 11, 2); // <--

console.log(a); // 2020-12-01T12:59:27.723Z
console.log(b); // 2020-11-30T22:00:00.000Z
console.log(c); // 2020-12-01T22:00:00.000Z

a = new Date();
a.setFullYear(2020);
a.setMonth(11);
a.setDate(31); // <--

b = new Date(2020, 11, 31);
c = new Date(2020, 11, 32); // <--

console.log("---");
console.log(a); // 2020-12-31T12:59:27.732Z
console.log(b); // 2020-12-30T22:00:00.000Z
console.log(c); // 2020-12-31T22:00:00.000Z
```

**Comment by addaleax** [comment]
Hi @oleg-kucherenko! Do you have a specific question? 

If not, consider that:

- `new Date()` creates an object representing the current date *and time*, i.e. current hours/minutes/seconds
- `new Date(year, month_minus_one, day)` creates a date representing midnight (00:00) on that day *in your current timezone*, which can be on the previous day if represented in UTC (which is the case when the formatted string ends in `Z`)

**Comment by oleg-kucherenko** [comment]
Thank you for support
