### ISSUE TITLE
Emails Save To File (Test Mail Server Tool for Node) For Development Testing Purposes

### ISSUE THREAD

**Issue by trymeouteh** [nodejs/help#3069]
Please add a easy setting for Node which will disable emails being sent out to the internet and instead when an email is being send by node, it will instead save it as a EML file somewhere on the computer. This will be similar to [Test Mail Server Tool](https://toolheap.com/test-mail-server-tool/) for PHP but for Node which allows developers to test email functionality and view the emails generated by Node in a development environment without the need to use a testing email account or the need to be online.

This would be much approached for Node developers.

**Comment by vdeturckheim** [comment]
Closing as out of scope/low activity. Please reopen if needed.
