### ISSUE TITLE
Centos And Windows Building, after 'make' or 'vcbuild.bat', how can we package a binary zip or tar.gz?

### ISSUE THREAD

**Issue by WitLouis** [nodejs/help#3070]
* **Node.js 12.18.4**:
* **Centos7 & Windows 10**:
* **code**:
* **null**:

1. In Centos7, after 'make', I just successfully compile an 'out' directory which has the 'node' binary file in 'Release', and then use 'make install' could install the NodeJs by compiling. **But How can I get the binary package tar.gz as I download in the website 'nodejs.org' **

2. In Windows, I met the same question. **But How can I get the binary package 'node-binary.zip' as I download in the website 'nodejs.org' **

**Is there any shell script or bat script that could automatically make the package? Thank u so much! **

**Comment by richardlau** [comment]
> **Is there any shell script or bat script that could automatically make the package? Thank u so much! **

Yes, `make binary` and `vcbuild.bat build-release`.

**Comment by WitLouis** [comment]
@richardlau which directory that `make binary` and `vcbuild.bat build-release` output is in the root directory?

**Comment by WitLouis** [comment]
I get it. The command is `vcbuild.bat build-release openssl-no-asm nosign`

**Comment by WitLouis** [comment]
@richardlau Thank u soooooo much!!!!
