### ISSUE TITLE
Unhandled rejection Error: connect ETIMEDOUT 136.147.109.158:443

### ISSUE THREAD

**Issue by girasedinesh** [nodejs/help#3071]
Hi All,

From 9th Nov, I am facing this. I have GitLab for CI/CD and am using sfdx commands for validation and quick deployment. This is an intermittent issue, it starts the validation job, but in between, it throws below error and keeps going on till log timeout ends.
ERROR:  Error: connect ETIMEDOUT 136.147.109.158:443
Unhandled rejection Error: connect ETIMEDOUT 136.147.109.158:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)

![GitLab Salesforce deployment issue](https://user-images.githubusercontent.com/59448789/98867599-d5e31980-243c-11eb-9a4c-7b68f9354da8.jpg)

**Comment by girasedinesh** [comment]
I am still facing this issue, any thoughts?

**Comment by andronux** [comment]
Hello!
did you find what was the issue?

I'm experiencing the same behavior.

**Comment by RedYetiDev** [comment]
Hi! Timeout issues *usually* mean an issue on the server side, not the client side. You seem to be experiencing a server-side issue while Node.js is running on the client side. I'd contact your CI/CD manager and go from there. I'm closing this issue, as we are unlikely to resolve it.
