### ISSUE TITLE
While connecting Helper to Helper (Mixer to Adder ,...) the back-propagation of Actuator Data the cue Node relies on throws

### ISSUE THREAD

**Issue by Jacobtarango21** [nodejs/help#3076]
While connecting Helper to Helper (Mixer to Adder ,...) the back-propagation of Actuator Data the cue Node relies on throws

a Key error

 Error: Traceback (most recent call last):
  File "C:\Users\wiredworks\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\wiredworks_winches\Node\Helpers\Mixer\SFX_Mixer_Op.py", line 19, in modal
    self.MotherNode.sfx_update()
  File "C:\Users\wiredworks\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\wiredworks_winches\Node\Helpers\Mixer\SFX_Mixer_Node.py", line 115, in sfx_update
    sfx.helpers[self.name].Actuator_basic_props.diff_Vel                                     = sfx.actuators[o.to_socket.node.name].Actuator_basic_props.diff_Vel
KeyError: 'mixer.001'

__Originally posted by @martburg in https://github.com/wiredworks/wiredworks_winches/issues/1__

**Comment by gireeshpunathil** [comment]
@Jacobtarango21 - is this still an issue? if so, can you elaborate the problem statement? I fear that it is difficult to make an analysis and recommendation from the given information .

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
