### ISSUE TITLE
Is there any way to prevent unnecessary changes to package.json after “npm install”?

### ISSUE THREAD

**Issue by Asaf-S** [nodejs/help#3077]
* **Node.js Version**: v14.8.0
* **OS**: macOS Cataline Version 10.15.5
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: -

Hey guys,
thank you for making Node.js so great!

I understand that package.json is recreated every time "npm i" runs, but that prevents me from grouping my many scripts with empty rows between them. Also, I saw others are trying to group modules in that way (#1946), or order them in a non-alphabetical order.

Is there a way to make changes only where needed and only when needed?
If not - please see this issue as a feature request.

Example of a package.json with grouping:
```json
{
  "scripts": {
    "a_magic_A1": "...",
    "some_magic_A2": "...",

    "another_magic_B1": "..."
  },
  "dependencies": {
    "aws-related": "^1.0.0",
    "related-to-aws": "^1.0.0",

    "other-dependencies": "^1.0.0"
  }
}
```

And after running 'npm i'
```json
{
  "scripts": {
    "a_magic_A1": "...",
    "another_magic_B1": "...",
    "some_magic_A2": "..."
  },
  "dependencies": {
    "aws-related": "^1.0.0",
    "other-dependencies": "^1.0.0",
    "related-to-aws": "^1.0.0"
  }
}
```

**Comment by emilioplatzer** [comment]
I' need this too.

**Comment by gireeshpunathil** [comment]
@nodejs/npm

**Comment by Itharen** [comment]
I need this too.

**Comment by isaacs** [comment]
It's best to consider package.json and package-lock.json as being "owned" by npm.

It does some work to maintain line endings and indentation levels, but it assumes standard `JSON.stringify` formatting with a canonical key order, where dependencies are alphabetized.

Maintaining the shape of the json text, while making changes to the logical structure of the object, would be a very daunting task, adding significant complexity and performance overhead, which is pretty difficult to justify when the status quo (ie, JSON.stringify) is a highly optimized one-liner included in the language runtime.

**Comment by emilioplatzer** [comment]
@isaacs has a point. We don't expect that `npm i` preserves formats, spaces or any non pretty printed when we use it for changing `package.json` file. But when we use `npm i` without other parameters there is absolutely no need to change it. 

That is what we are asking. Don't change `package.json` when is no needed: when no usefull information is changing or added to it.
