### ISSUE TITLE
Storing query results in variables

### ISSUE THREAD

**Issue by lel1234** [nodejs/help#308]
I'm wondering if it's a good idea (performance wise) to store queries results in variables and update them only every few minute, since I have multiple database queries(MongoDB) in my node application that don't need to be up to date and some of them are a bit complex. 

In other words, should I simply use variables to display data to multiple clients requests or should I use a cache module like Redis or memory-cache ?

I'm thinking about something like this :

```
var queryResults = [];
myModel.find().exec(function(err, results) {
        queryResults = results;
});
```

Then : 

```
var interval = 10 * 60 * 1000;
    setInterval(function() {
    myModel.find().exec(function(err, results) {
        queryResults = results;
    });
}, interval);
```

And when I need to send the query results to my views engine :

```
app.get('/', function(req, res) {
    res.render('index.ejs', {entries : queryResults});
});
```

**Comment by danielkhan** [comment]
Sure it can make sense do 'cache' query results in one or the other way. Everything else highly depends on your use case. I'd recommend to use `ab`to measure the performance. Run 10000 requests with or without your caching and see what it gives you.
Come back here and let us know.

Redis or memory cache are also viable solutions if you need to store more than one result under one key.
