### ISSUE TITLE
hms@1.0.0 No repository field.

### ISSUE THREAD

**Issue by Gilbert5262** [nodejs/help#3080]
hello i copied a project in github have  been trying to run it my local computer but its not working every time i run npm install i get this error
npm WARN hms@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
how do i solve this

**Comment by aduh95** [comment]
It's a warning you can safely ignore. If you wish to remove it, you'd need to add a `repository` field to the `package.json` file of `hms`:

```json
"repository": {
    "type": "git",
    "url": "https://github.com/Gilbert5262/hms.git"
  },
```

**Comment by Gilbert5262** [comment]
thank you sir for your help, have incurred another error help me to handle it
    On Tuesday, December 1, 2020, 03:31:33 AM GMT+3, Antoine du Hamel <notifications@github.com> wrote:  
 
 


It's a warning you can safely ignore. If you wish to remove it, you'd need to add a repository field to the package.json file of hms:
"repository": {
    "type": "git",
    "url": "https://github.com/Gilbert5262/hms.git"
  },

**Comment by Gilbert5262** [comment]
On Sunday, December 6, 2020, 03:41:33 PM GMT+3, gilbert okoth <gilbertokoth63@yahoo.com> wrote:  
 
  thank you sir for your help, have incurred another error help me to handle it
    On Tuesday, December 1, 2020, 03:31:33 AM GMT+3, Antoine du Hamel <notifications@github.com> wrote:  
 
 


It's a warning you can safely ignore. If you wish to remove it, you'd need to add a repository field to the package.json file of hms:
"repository": {
    "type": "git",
    "url": "https://github.com/Gilbert5262/hms.git"
  },

**Comment by marsonya** [comment]
@Gilbert5262 -  I believe this issue is resolved and it's safe to close it.
Feel free to reopen it incase there is something you would like to add to it.
