### ISSUE TITLE
idk whats wrong

### ISSUE THREAD

**Issue by wim874** [nodejs/help#3082]
* **Node.js Version**:
* **windows**:
* **Scope (install)**:
* **Module (and version) (if relevant)**:

idk

```js
//npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Wim874\AppData\Roaming\npm-cache\_logs\2020-11-16T16_25_08_110Z-debug.log
```
-->

**Comment by addaleax** [comment]
Can you remove `C:\Users\Wim874\Desktop\bot\node_modules\.staging` and start over?

**Comment by wim874** [comment]
> Can you remove `C:\Users\Wim874\Desktop\bot\node_modules\.staging` and start over?

i did it

**Comment by marsonya** [comment]
> i did it
Did it work?
