### ISSUE TITLE
wrong answer with add integer 

### ISSUE THREAD

**Issue by Merevoli-DatLuu** [nodejs/help#3083]
* **Version**: 12.18.2
* **Platform**: 64-bit Windows
* **Subsystem**: 

### What steps will reproduce the bug?

```js
let sum = 0;

for (let i = 1; i<=1000000000; i++){
    sum += i;
}

console.log(sum); /* output: 500000000067109000 instead of 500000000500000000
```

### What is the expected behavior?

```js
/** Output (Right Answer) **/
500000000500000000
```

### What do you see instead?

```js
/** Output (Wrong Answer) **/
500000000067109000 
```

**Comment by vsemozhetbyt** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

You can use BigInt:

```js
let sum = 0n;

for (let i = 1n; i<=1000000000n; i++){
    sum += i;
}

console.log(sum); // 500000000500000000n
```

**Comment by Merevoli-DatLuu** [comment]
@vsemozhetbyt Thank you for the advice.

**Comment by PoojaDurgad** [comment]
closing as answered. please let me know if that is not the case.
