### ISSUE TITLE
Fs.writeFileSync not updating a JSON file in Github. When i update the value. It updates for me but it doesn't update the file in github. This is for updating a JSON file containing money balance(bal) as a person's money 

### ISSUE THREAD

**Issue by jaipack17** [nodejs/help#3086]
const Fs = require("fs");

        if(args == "stroll"){
            let UserJSON = JSON.parse(Fs.readFileSync("./DB/users.json"));
            let check = Math.floor(Math.random() * 3);
            let money = Math.floor(Math.random() * 100 + -100);
            if(check == 1){
                money = money * -1;
            }
            if(money < 0){
                money = 0;
            }
            UserJSON[message.author.id].bal += money;
            Fs.writeFileSync("./DB/users.json", JSON.stringify(UserJSON));

            if(money > 0){
                    message.channel.send(`${message.author.username} went outside for a stroll and found ${money} dollars on the floor.`)
                }
                else{
                    message.channel.send(`${message.author.username} went outside for a stroll and found a bottle cap on the floor.`)
                }
            
        }

**Comment by GrosSacASac** [comment]
Did you git commit and git push ?
