### ISSUE TITLE
Any way to reload the built-in modules?

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/help#3087]
Is there any way to reload the built-in modules into the node executable generated by `make` without recompiling the C++ part entirely?

**Comment by richardlau** [comment]
There's some functionality that was added in https://github.com/nodejs/node/pull/31321/. You will need to rebuild Node.js once with the `--node-builtin-modules-path` configure option to enable it.

**Comment by RaisinTen** [comment]
Thank you so much!

Which of these two should I execute at the top of the `git` repo of `node`:

*   ```
    ./configure --node-builtin-modules-path=.
    ```

*   ```
    ./configure --node-builtin-modules-path=lib
    ```

Both seem to produce the same output:

```
Node.js configure: Found Python 3.6.9...
Warning! Loading builtin modules from disk is for development
INFO: configure completed successfully
```

**Comment by richardlau** [comment]
It looks like between those two choices it would be the first as `lib` gets appended:
https://github.com/nodejs/node/blob/bb3cbba9533b37429292fd1005efb8099e7ba872/src/node_native_module.cc#L198

(FWIW I've never used this build feature before)

**Comment by RaisinTen** [comment]
Thank you for the help. I'll try using it. :slightly_smiling_face:

**Comment by RaisinTen** [comment]
After building node with this mod I figured out that I should have used the absolute path to the node git repo instead. When using node from a different location, I get this error:
```
node/node[3415]: ../src/node_native_module.cc:215:v8::MaybeLocal<v8::String> node::native_module::NativeModuleLoader::LoadBuiltinModuleSource(v8::Isolate*, const char*): Assertion `(req.result) >= (0)' failed.
```
I was thinking about changing this functionality a bit. Instead of fixing the path in the configuration stage maybe we can enable this feature using a binary flag and during execution node will read in the builtin modules path from an environment variable.

**Comment by devsnek** [comment]
@RaisinTen if you give it an absolute path you won't have that issue.

**Comment by bl-ue** [comment]
@RaisinTen did you ever get it working? I tried running this:
```
./configure --debug --debug-node --gdb --v8-non-optimized-debug --v8-enable-object-print --debug-nghttp2 --node-builtin-modules-path=$PWD/lib --enable-asan --debug-lib
```
but the resulting `node` aborts, just like yours did.
```
❯ echo $PWD/lib
/Users/me/node/lib
```

**Comment by RaisinTen** [comment]
@bl-ue Yes, this works for me. :)
I think the value for `--node-builtin-modules-path` should be set to just `$PATH` without the `/lib` suffix because https://github.com/nodejs/help/issues/3087#issuecomment-731089552.

**Comment by bl-ue** [comment]
Ohhh... I saw that message, but I didn't read it correctly.  Makes perfect sense.  Thank you 👍🏻
