### ISSUE TITLE
the new crypto package for node 15 is great, can we have a backport or some polyfill for old versions?

### ISSUE THREAD

**Issue by sibelius** [nodejs/help#3089]
* **Node.js Version**: 12,14
* **OS**: mac
* **Scope (install, code, runtime, meta, other?)**: module
* **Module (and version) (if relevant)**: crypto

I'd like to use the new crypto module (node 15 only) in older node versions (12,14).

what is the best approach for this right now?

**Comment by chibbi** [comment]
Why dont you just update? xD

**Comment by sibelius** [comment]
node 15 break other deps
