### ISSUE TITLE
Node.js cannot find module & etc.

### ISSUE THREAD

**Issue by strykesgamer** [nodejs/help#309]
So i have a node.js script that came with some modules and i am struggling to run it (Debian 7).

this is my console output:

`root@185:/home/bot# node sell.js
module.js:457
throw err;
^

Error: Cannot find module './parser/token_analyzer'
at Function.Module._resolveFilename (module.js:455:15)
at Function.Module._load (module.js:403:25)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
at Object. (/home/bot/node_modules/steam/resources/steam_language_parser/index.js:2:22)
at Module._compile (module.js:556:32)
at Object.Module._extensions..js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)
`
I have searched through and not found an answer, please help.

**Comment by danielkhan** [comment]
Is there a package.json? Did you run `npm install`?

**Comment by ito2307** [comment]
i have a similar issue i ran npm install
 npm install
npm WARN cheque No repository field.
npm WARN cheque No license field.
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path ../node-sass/bin/node-sass
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../node-sass/bin/node-sass' -> '/home/vagrant/Code/cheque/node_modules/.bin/node-sass'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/cheque/npm-debug.log

**Comment by ito2307** [comment]
gulp
module.js:457
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/Code/cheque/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by strykesgamer** [comment]
I did do npm install, no difference

**Comment by danielkhan** [comment]
@strykesgamer does the file `./parser/token_analyzer` exist?
@ito2307 please open a new issue

**Comment by strykesgamer** [comment]
@danielkhan I have uninstalled debian, switched to ubuntu, and everything is working fine now, thankyou for the assistance

**Comment by narutoadi** [comment]
I am using ubuntu and still facing the same problem

**Comment by lordKnighton** [comment]
@narutoadi did you have any luck yet?

**Comment by narutoadi** [comment]
Yeah. I was facing a lot of similar problems even after installing and reinstalling nodejs.
But then I read about the correct way ' https://gist.github.com/isaacs/579814#file-node-and-npm-in-30-seconds-sh  ' of installing node and things are going good now.

**Comment by lordKnighton** [comment]
perfect 👍

**Comment by sjais789** [comment]
Can you help me out ? nothing is working (mentioned  tips above )

**Comment by gibfahn** [comment]
>Can you help me out ? nothing is working (mentioned tips above )

@sjais789 what exactly is the error you're seeing?

**Comment by sjais789** [comment]
Just solved the issue. I also wrote the answer too on stackoverflow.
[https://stackoverflow.com/a/46514356/6932864]()

**Comment by thefakhreddin** [comment]
hello everyone.
I have the same exact problem. I have already tried running cmd as administrator and installed 'node bluetooth' package both globally and locally with npm install command but the still the code doesn't recognize the packages. (cannot find module)
