### ISSUE TITLE
npm is not working with node js 14+ version (npm version 6.9.0)

### ISSUE THREAD

**Issue by moizalikhan119** [nodejs/help#3090]
![Untitled design (20)](https://user-images.githubusercontent.com/38657358/99844088-6552a000-2b94-11eb-8415-c5b3d92176c4.png)

**Comment by PoojaDurgad** [comment]
@moizalikhan119 - can you try to uninstall npm and install node with latest stable version of npm?

**Comment by cbuchacher** [comment]
I had to uninstall Node.js, delete %USERPROFILE%\AppData\AppData\Roaming\npm, and re-install Node.js to fix this. Uninstalling Node.js is not enough.

**Comment by PoojaDurgad** [comment]
closing as answered .
