### ISSUE TITLE
This is probably not a problem with npm. There is likely additional logging output above

### ISSUE THREAD

**Issue by srimansagar5** [nodejs/help#3095]
Please find the below log details. 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jiohoux@0.1.0~prestart: jiohoux@0.1.0
6 info lifecycle jiohoux@0.1.0~start: jiohoux@0.1.0
7 verbose lifecycle jiohoux@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle jiohoux@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Sagar\Projects\JaiHo\JaiHoWebSourceCode\JaiHo_Web_SourceCode_Nov_18_2020\node_modules\.bin;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\91888\AppData\Local\Microsoft\WindowsApps;;C:\Users\91888\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\91888\AppData\Roaming\npm
9 verbose lifecycle jiohoux@0.1.0~start: CWD: D:\Sagar\Projects\JaiHo\JaiHoWebSourceCode\JaiHo_Web_SourceCode_Nov_18_2020
10 silly lifecycle jiohoux@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle jiohoux@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle jiohoux@0.1.0~start: Failed to exec start script
13 verbose stack Error: jiohoux@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid jiohoux@0.1.0
15 verbose cwd D:\Sagar\Projects\JaiHo\JaiHoWebSourceCode\JaiHo_Web_SourceCode_Nov_18_2020
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error jiohoux@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the jiohoux@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by PoojaDurgad** [comment]
@srimansagar5 - looks like the start script in your package.json is `react-scripts start` not `start script` so I think delete your packagelock.json and do `npm cache clean --force` and  do ` npm install`   it may help.
and can you try `npm react-scripts start` ?

**Comment by cc-max** [comment]
same problem 
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Node.js\\node_global\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.1
4 verbose npm-session 47ea674f2864d8eb
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall @3.0.5
7 info lifecycle @3.0.5~preinstall: @3.0.5
8 verbose lifecycle @3.0.5~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle @3.0.5~preinstall: PATH: D:\Node.js\node_global\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\vue源码\vue-next\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\zwx897575\bin;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Windows;C:\Windows\system32;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;%JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;C:\python\Scripts;C:\python;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\TortoiseSVN\bin;D:\software\wecode\WeCode\ide\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Git\cmd;D:\IDE\Gradle\gradle-1.9-all\gradle-1.9\bin;D:\IDE\MinGW\MinGW\bin;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs;D:\vscode\VSCode-huawei\bin;C:\python\Scripts;C:\python;C:\Users\zwx897575\AppData\Local\Microsoft\WindowsApps;C:\Users\zwx897575\AppData\Roaming\np;C:\Users\zwx897575\Desktop\临时文档收集\MinGW\MinGW\bin";C:\Program Files (x86)\Git\bin;C:\Users\zwx897575\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\bin;C:\thrift;D:\IDE\Gradle\gradle-1.9-all\gradle-1.9\bin;C:\Program Files (x86)\Java\jdk1.6.0_22\bi;C:\Program Files (x86)\Java\jdk1.6.0_22\jre\bin;.;C:\Users\zwx897575\AppData\Local\Microsoft\WindowsApps;C:\Users\zwx897575\AppData\Local\Yarn\bin;D:\Node.js\node_global;C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Git;C:\Users\zwx897575\AppData\Roaming\npm
10 verbose lifecycle @3.0.5~preinstall: CWD: D:\vue源码\vue-next
11 silly lifecycle @3.0.5~preinstall: Args: [ '/d /s /c', 'node ./scripts/checkYarn.js' ]
12 silly lifecycle @3.0.5~preinstall: Returned: code: 1  signal: null
13 info lifecycle @3.0.5~preinstall: Failed to exec preinstall script
14 timing stage:rollbackFailedOptional Completed in 1ms
15 timing stage:runTopLevelLifecycles Completed in 107ms
16 verbose stack Error: @3.0.5 preinstall: `node ./scripts/checkYarn.js`
16 verbose stack Exit status 1
16 verbose stack     at EventEmitter.<anonymous> (D:\Node.js\node_global\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
16 verbose stack     at EventEmitter.emit (events.js:315:20)
16 verbose stack     at ChildProcess.<anonymous> (D:\Node.js\node_global\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
16 verbose stack     at ChildProcess.emit (events.js:315:20)
16 verbose stack     at maybeClose (internal/child_process.js:1048:16)
16 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
17 verbose pkgid @3.0.5
18 verbose cwd D:\vue源码\vue-next
19 verbose Windows_NT 10.0.19041
20 verbose argv "C:\\Program Files\\nodejs\\node.exe" "D:\\Node.js\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "install"
21 verbose node v14.15.1
22 verbose npm  v6.14.10
23 error code ELIFECYCLE
24 error errno 1
25 error @3.0.5 preinstall: `node ./scripts/checkYarn.js`
25 error Exit status 1
26 error Failed at the @3.0.5 preinstall script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]
