### ISSUE TITLE
How Do I Remove the Node.js Certificate without Affecting Compiling the Node Binary?

### ISSUE THREAD

**Issue by xuhp5** [nodejs/help#3096]
Node.js Version:12.18.4

Urgent! I need to download the node.js source code and compile it into the node binary code. However, the source code has certificates that do not comply with my company regulations. Therefore, the related certificate description needs to be removed. The description needs to be understood how to remove the certificates without affecting the compilation of binary files or whether the certificates can be removed after compilation. If convenient, please also provide the functions and use time of the certificate. We are looking forward to your reply.

```js
// node-v12.18.4\src\node_root_certs.h
```

**Comment by bigtree9307** [comment]
给你花花

**Comment by bigtree9307** [comment]
Oh I have met this problem too!!! Waiting for the answers!

**Comment by bigtree9307** [comment]
up

**Comment by bigtree9307** [comment]
up

**Comment by bigtree9307** [comment]
up+3

**Comment by bigtree9307** [comment]
up+4

**Comment by bigtree9307** [comment]
up+5

**Comment by katusiimeconrad** [comment]
up + 6
