### ISSUE TITLE
How to ensure Single Thread execution model in NodeJS?

### ISSUE THREAD

**Issue by galvesribeiro** [nodejs/help#310]
Hello guys.

I'm trying to implement the [Distributed Virtual Actors model](http://research.microsoft.com/pubs/210931/Orleans-MSR-TR-2014-41.pdf) which is an enhanced implementation of the [Actor model](https://en.wikipedia.org/wiki/Actor_model) and is the core of [Orleans](http://dotnet.github.io/orleans/).

The idea is to implement the Virtual Actors with NodeJS just like EA Games did for java with their port called [Orbit](https://github.com/orbit/orbit) so we would bring distributed computing to NodeJS community.

In my initial research, the first barrier I found was the Single Thread guarantee defined in the Virtual Actors model. With this guarantee, each actor activation can only process a single message at time, removing problems like race conditions and help ensure the Actor state is consistent across the system (more details check the [Turns](http://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Grains.html) in Orleans docs).

So, how can I ensure that in JavaScript and NodeJS? In Orleans implementation there is a custom Task Scheduler that make sure there is a single Actor message being processed at a time on an Actor instance.

Can anyone point me out the right resources?

Thanks!

**Comment by danielkhan** [comment]
If Node.js does not run in cluster mode and your jobs don't contain asynchronous tasks, there is only one task at a time processed as Node.js' userland is strictly single threaded.

**Comment by galvesribeiro** [comment]
Yeah but in Orleans one thread run multiple workitem cooperatively. So we can multiplex the thread with multiple actor activations and all the code must be async for that. 

So, I know the userland in nodejs is a single thread but the point is that inside that single thread I need to ensure that one Actor can execute one message at a time. I could use 1 thread/worker per actor but that obviously would not scale. By having the cooperative multitask in Orleans we have hundreds of thousands of actors in a single server using multiple cores and the reason it work, is because of the Turn-based execution model, which makes the actors to cooperatively multitask in a single thread.

So the basic idea is that an actor class would have a mailbox that can process a single message at time asynchronously. So it would have an internal lock on this mailbox avoiding subsequent messages to being processed on that same actor while it is processing another message. All it asynchronously, so other actors in the same thread can process its messages n parallel while it is asynchronously awaiting the execution of other messages in other actors.

Does that make sense?

**Comment by martinheidegger** [comment]
Node.js in cluster-mode has [Workers](https://nodejs.org/api/cluster.html#cluster_class_worker), workers are basically what you call "Actors". The Node vm is inherently Single-threaded but each worker runs in its own, single, thread.

**Comment by galvesribeiro** [comment]
No... we can compare workers with an Actor.

An actor in Orleans does not have a full blow .Net Framework runtime copy in memory. This is what happen when spawning a new worker in node. The memory footprint for it is terrible and it will not scale well.

Again, if you have a look on the paper you will see that a single physical thread is multiplexed between multiple actors. Hence the cooperative multi threading.

As I'm seeing, truly distributed computing is not something node.js was designed for. It was created to handle simple web requests. Big challenge here to change that...

**Comment by danielkhan** [comment]
In Node.js, threading is abstracted away from you and you can either spawn workers, which are full blown Node processes, or use native modules to create threads or run tasks through libuv.
The only viable solution I can think of would be to create a native module and do the threading there. But then you're in C++ land. So Node.js is most probably not the platform you want to use for that.

**Comment by martinheidegger** [comment]
I know this is only little of help but you could make a cluster of the amount of cpu cores that are in a system. With one worker per core you can still consume every core and with messages exchange between the core semi-efficiently.

**Comment by galvesribeiro** [comment]
@martinheidegger that would be more close to the OrleansTaskScheduler which maintains the Turn-based threading model and Cooperative multitask on top of physical cores.

@danielkhan yeah, I though about that... Use native threads may do the trick but it would be waaayyy too much extreme... 

I'll think more about it and come here with the solution we found. 

Thank you all about the input. Will keep this issue updated.
