### ISSUE TITLE
Detecting if a spawned process is trying to read a line of input?

### ISSUE THREAD

**Issue by Ishaangandhi** [nodejs/help#3100]
Basically, I'm interested in detecting if a spawned process is trying to read a line of input. Is that possible?

```
const { spawn } = require('child_process');
let x = spawn('zsh');
```

Can you tell if x is blocked on reading from stdin?

**Comment by addaleax** [comment]
@Ishaangandhi No, unfortunately not. You can generally not tell whether and how a child process reads stdin. Even for Node.js child processes, you probably wouldn’t be able to figure out if this was the only thing that keeps them from progressing.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
