### ISSUE TITLE
replaceAll("localhost:3000", "example.com") doesn't work / readSync doesnt read

### ISSUE THREAD

**Issue by chibbi** [nodejs/help#3101]
Version:v15.2.1
Platform: Linux raspberrypi 5.4.51-v7+ nodejs/node#1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
               Linux manjaroPC 5.9.10-1-MANJARO nodejs/node#1 SMP PREEMPT Sun Nov 22 11:25:19 UTC 2020 x86_64 GNU/Linux

### What steps will reproduce the bug?
run 
``` replaceAll("localhost:3000", "example.com") ```
on a String containing it
 (i use it to run go through my html and js files that have links like that to quickly change between
  localhost:3000 => testServer
   example.com  => Production)

### How often does it reproduce? Is there a required condition?
Nearly always.
I think it worked once but i tried it like 20times or smth like that xD
### What is the expected behavior?
to change every occurance of "localhost:3000" to "example.com"

### What do you see instead?
It changes no occurance at all

### Additional information

i am thinking, that maybe splitting it to
```
replaceAll("localhost", "example")
replaceAll(":3000", ".com")
```
 will work, but i havent tried it yet

but that would still be more a hack to get it to work than have it actually working (in my mind)

**Comment by aduh95** [comment]
What happens if you run in your terminal:

```console
$ node -p '"localhost:3000".replaceAll("localhost:3000", "example.com")'
```

**Comment by chibbi** [comment]
That works
Output: ```example.com```

**Comment by aduh95** [comment]
> That works

Great, that means `<string>.replaceAll` is available on the Node.js version you're using. I couldn't find any occurence of `localhost:3000` in your code, maybe that's why you're having this issue.

FWIW, I'd advise you to use relative URLs instead of absolute ones (`/index.html` instead of `http://localhost:3000/index.html`) to workaround your issue without needing to replace anything.

**Comment by chibbi** [comment]
Ok so i dont know any more why i used absolute path, but jeah i changed it to relative paths now. 
i would still "need" it to work for mailto:support@example.com but i am planning to change that to not use mailto:
so that would not be an issue any more too.

The only reason i am not closing it yet, is because i don't understand why it is not working and it SHOULD work xD.

the occurence exists in adminpass.html (now only pastebin) and static/js/de_siteLoader.js at mailto:

the index.js file reads those files, does replaceAll on the string with the whole file, and then writes the whole file again. (at the end of the index.js file you can find the code that does that).

**Comment by aduh95** [comment]
Can you give me a link to the actual line of code that is supposed to do that?

**Comment by chibbi** [comment]
The function: https://github.com/chibbi/HomePage/blob/25350c0bceebde54967d5147d5ff8b8077769c13/index.js#L522-L532

where it is called: https://github.com/chibbi/HomePage/blob/25350c0bceebde54967d5147d5ff8b8077769c13/index.js#L540

the file that is getting changed: https://pastebin.com/EnVZbijk
(at line 62 "localhost:3000")
it is not existent in my repo because i changed it to be relative (those functions changing localhost will be removed as well)

**Comment by aduh95** [comment]
It seams that you are calling async FS functions (`readFile` and `writeFile`) on the same file, it seams very likely that you are creating a race condition here. To solve this, you'd need to either:

- use `fs/promises` functions, and await for the previous read/write to complete before start the next one on the same file.
- use `readFileSync` and `writeFileSync` (that might be way less efficient than handling multiple files in parallel, but maybe worth it)
- add a queue system that would gather all the change requests for each files, read each file only once, apply changes all at once, then write back to the file only once. That's certainly the most efficient solution.

Here's a naive implementation:

```js
const queue = {};
function redo(path, find, real) {
  queue[path] = (queue[path] ?? fs.promises.readFile(path, 'utf8')).then(data => data.replaceAll(find, real)));
}
function commit() {
  const promises = [];
  for (const [path, promise] of Object.entries(queue)) {
    promises.push(promise.then(data => fs.promises.writeFile(path, data));
  }
  return Promise.allSettled(promises);
}

/* … redo() calls … */
commit().then(console.log);
```

**Comment by chibbi** [comment]
Okay so after changing it to be synced, it doesnt work at all any more xD.

if I have the read and write functions on sync, it just doesnt read or writes those files, and i have no idea why.

**Comment by aduh95** [comment]
What do you mean? What is the code you are using?

**Comment by chibbi** [comment]
```
    fs.readFile(path, 'utf8', function (err, data) {
        if (err) {
            return printlog(err, 0);
        }
        var result = data.replaceAll(find, real);
        fs.writeFile(path, result, 'utf8', function (err) {
            if (err) return printlog(err, 0);
        });
    });
```
just with writeFileSync and readFileSync

AND now i have found it it did SOMETHING, because the file is now EMPTY.

**Comment by aduh95** [comment]
> just with writeFileSync and readFileSync

Don't you want to share the actual code you tried? It would be much easier to help you…

**Comment by chibbi** [comment]
The function
```
dirname = __dirname // i know uneccessary but it was easier like that 
function redo(path, find, real) {
    path = dirname + path;
    printlog("Remaking " + path + " with config " + find + " to " + real,5);
    log("TEST", 5);
    fs.readFileSync(path, 'utf8', function (err, data) {
        if (err) { return printlog(err, 0); }
        log("TEST 22", 5);
        var result = data.replaceAll(find, real);
        fs.writeFileSync(path, result, 'utf8', function (err) {
            if (err) { return printlog(err, 0); }
            log("TEST 333", 5);
        });
        printlog("Remaking " + path + " with config " + find + " to " + real,5);
    });
}
```
The call:
```
siteName = "schoki.duckdns.org";
placeSiteName = "localhost:3000";
redo('static/js/en_siteLoader.js', placeSiteName, siteName);
```

If you want more Code i am afraid you gonna have to look into my [repo](https://github.com/chibbi/HomePage).

**Comment by aduh95** [comment]
Hum, that's not how `readFileSync` works. You'd need to do instead:

```js
function redo(path, find, real) {
  path = dirname + path;
  printlog("Remaking " + path + " with config " + find + " to " + real,5);
  log("TEST", 5);
  try {
    const data = fs.readFileSync(path, 'utf8').replaceAll(find, real);
    log("TEST 22", 5);
    fs.writeFileSync(path, data);
    log("TEST 333", 5);
  } catch (err) {
    printlog(err, 0);
  }
}
```

**Comment by chibbi** [comment]
Oh right XD i forgot that it doesnt need callback if it is synced 
Gonna try that now

**Comment by chibbi** [comment]
Now it is WORKING so the Problem had to be that it wasn't in Sync.

THANKS A LOT. xD <3

**Comment by daboujohan-hub** [comment]
Bonjour
