### ISSUE TITLE
question: How much is the size of limitation of permanent area?

### ISSUE THREAD

**Issue by hasegawa-d** [nodejs/help#3102]
* **Node.js Version**:12
* **OS**:CentOS 7
* **Scope (install, code, runtime, meta, other?)**:runtime

Is there any limitation of **permanent area** in allocated memory?
I know there's an option and default value for heap size. 
* --max-old-space-size

But I didn't find information about permanent area.

What is the default size of limitation of permanent area allocated for Node.js ?
How can we change the size ? There's no limitation ?

**Comment by addaleax** [comment]
@hasegawa-d What’s the permanent area?

If you’re talking about the [Resident Set Size](https://en.wikipedia.org/wiki/Resident_set_size), then the `ulimit` shell command should be able to help you.

**Comment by gireeshpunathil** [comment]
I guess the question is related to code heap (based on my understanding with Java, which uses `permgen` - a permanent generation area for classes) - but will be great if @hasegawa-d clarifies.

**Comment by hasegawa-d** [comment]
@gireeshpunathil 
thank you for your help.
Yes, I'm talking about a permanent generation area for classes.

In Java, there's maximum value for permanent generation area and options for controlling it like below. (before v7)
* -XX:MaxPermSize

I want to know whether there're similar value and options  also in Node.js.
If no, is allocated memory size for Node.js unlimited ?

**Comment by gireeshpunathil** [comment]
The `generated` code is kept in an area called `code_space` which is part of the Javascript heap, but not sure whether it stores the original script or not, or if it is generated on demand. Also not sure if there is a flag that controls this space. I will request @addaleax for finest level of details on that.

**Comment by addaleax** [comment]
> Also not sure if there is a flag that controls this space.

I don’t think so, no.

> but not sure whether it stores the original script or not

I also don’t think so.

**Comment by RedYetiDev** [comment]
This should've closed as stale, but since I added the `question` label, it didn't. Feel free to re-open if this is still relevant.
