### ISSUE TITLE
Implementing Tensorflowjs model in Ionic Framework using Node.js

### ISSUE THREAD

**Issue by Tanush99** [nodejs/help#3107]
* **Node.js Version**: 6.14.8
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: Tensorflowjs-node module

I am working on a project where I am using Ionic and TensorFlow for machine learning. I have converted my TensorFlow model to a tensorflowjs model. I have put the model.json file and shard files of the tensorflowjs model in the assets folder in Ionic. Basically, I have put my tensorflowjs model in the assets folder of ionic. I am wanting to use Capacitor to access the camera and allow users to take photos. Then, the photos will be passed to the tensorflowjs model in assets to get and display a prediction for that user.

Here is my typescript code:

import { Component, OnInit, ViewChild, ElementRef, Renderer2 } from '@angular/core';
import { Plugins, CameraResultType, CameraSource} from '@capacitor/core';
import { DomSanitizer, SafeResourceUrl} from '@angular/platform-browser';
import { Platform } from '@ionic/angular';
import { rendererTypeName } from '@angular/compiler';
import { Base64 } from '@ionic-native/base64/ngx';
import { defineCustomElements } from '@ionic/pwa-elements/loader';
import { Buffer } from 'buffer';
import * as tf from '@tensorflow/tfjs-node';

const { Camera } = Plugins;

@Component({
  selector: 'app-predict',
  templateUrl: 'predict.page.html',
  styleUrls: ['predict.page.scss'],
})
export class PredictPage {
  linearModel : tf.Sequential;
  prediction : any;
  InputTaken : any;
  ctx: CanvasRenderingContext2D;
  pos = { x: 0, y: 0 };
  canvasElement : any;
  photo: SafeResourceUrl;
  model: tf.LayersModel;
  constructor(private sanitizer: DomSanitizer) 
  {}

  async takePicture() {
  
    const image = await Camera.getPhoto({
        quality: 90,
        allowEditing: true,
        resultType: CameraResultType.Uri,
        source: CameraSource.Camera});
      this.photo = this.sanitizer.bypassSecurityTrustResourceUrl(image.base64String);
      defineCustomElements(window);
      const b = Buffer.from(image.base64String, 'base64')
      const r = tf.node.decodeImage(b)
      const output = this.model.predict(r) as any;
  }
  
  
}

Here, in the above code, I have imported the necessary tools. Then, I have my constructor function and a takepicture() function. In the takepicture function, I have included functionality for the user to take pictures. I have converted the pictures to tensor form to pass to model.predict. Then, I will use html to display the prediction. However, when I import @tensorflow/tfjs-node, I get the following error:

 using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\Users\isusu\Documents\third\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
          using description file: C:\Users\isusu\Documents\third\myApp\node_modules\request\package.json (relative path: ./node_modules/https)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./node_modules/https)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.tsx doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https doesn't exist
              C:\Users\isusu\Documents\third\myApp\node_modules\https.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\node_modules\https doesn't exist
          C:\Users\isusu\Documents\third\node_modules\https.js doesn't exist
        as directory
          C:\Users\isusu\Documents\third\node_modules\https doesn't exist
[C:\Users\isusu\Documents\third\myApp\https]
[C:\Users\isusu\Documents\third\myApp\https.ts]
[C:\Users\isusu\Documents\third\myApp\https.tsx]
[C:\Users\isusu\Documents\third\myApp\https.mjs]
[C:\Users\isusu\Documents\third\myApp\https.js]
[C:\Users\isusu\Documents\third\myApp\node_modules\node_modules]
[C:\Users\isusu\Documents\node_modules]
[C:\Users\isusu\node_modules]
[C:\Users\node_modules]
[C:\node_modules]
[C:\Users\isusu\Documents\third\node_modules\package.json]
[C:\Users\isusu\Documents\third\node_modules\https\package.json]
[C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https]
[C:\Users\isusu\Documents\third\myApp\node_modules\https]
[C:\Users\isusu\Documents\third\node_modules\https]
[C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https.ts]
[C:\Users\isusu\Documents\third\myApp\node_modules\https.ts]
[C:\Users\isusu\Documents\third\node_modules\https.ts]
[C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https.tsx]
[C:\Users\isusu\Documents\third\myApp\node_modules\https.tsx]
[C:\Users\isusu\Documents\third\node_modules\https.tsx]
[C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https.mjs]
[C:\Users\isusu\Documents\third\myApp\node_modules\https.mjs]
[C:\Users\isusu\Documents\third\node_modules\https.mjs]
[C:\Users\isusu\Documents\third\myApp\node_modules\request\node_modules\https.js]
[C:\Users\isusu\Documents\third\myApp\node_modules\https.js]
[C:\Users\isusu\Documents\third\node_modules\https.js]
 @ ./node_modules/request/request.js 4:12-28
 @ ./node_modules/request/index.js
 @ ./node_modules/node-pre-gyp/lib/install.js
 @ ./node_modules/node-pre-gyp/lib sync ^\.\/.*$
 @ ./node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ ./node_modules/@tensorflow/tfjs-node/dist/index.js
 @ ./src/app/predict/predict.page.ts
 @ ./src/app/predict/predict-routing.module.ts
 @ ./src/app/predict/predict.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\isusu\Documents\third\myApp\node_modules\tunnel-agent'
resolve 'https' in 'C:\Users\isusu\Documents\third\myApp\node_modules\tunnel-agent'
  Parsed request is a module
  using description file: C:\Users\isusu\Documents\third\myApp\node_modules\tunnel-agent\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/Users/isusu/Documents/third/myApp
        using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./https)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\https doesn't exist
      C:\Users\isusu\Documents\third\myApp\node_modules\tunnel-agent\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\third\myApp\node_modules\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\node_modules doesn't exist or is not a directory
      C:\Users\isusu\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\isusu\Documents\third\myApp\node_modules
        using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\Users\isusu\Documents\third\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
          using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./node_modules/https)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.tsx doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\https.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\node_modules\https doesn't exist
          C:\Users\isusu\Documents\third\node_modules\https.js doesn't exist
        as directory
          C:\Users\isusu\Documents\third\node_modules\https doesn't exist
[C:\Users\isusu\Documents\third\myApp\https]
[C:\Users\isusu\Documents\third\myApp\https.ts]
[C:\Users\isusu\Documents\third\myApp\https.tsx]
[C:\Users\isusu\Documents\third\myApp\https.mjs]
[C:\Users\isusu\Documents\third\myApp\https.js]
[C:\Users\isusu\Documents\third\myApp\node_modules\tunnel-agent\node_modules]
[C:\Users\isusu\Documents\third\myApp\node_modules\node_modules]
[C:\Users\isusu\Documents\node_modules]
[C:\Users\isusu\node_modules]
[C:\Users\node_modules]
[C:\node_modules]
[C:\Users\isusu\Documents\third\node_modules\package.json]
[C:\Users\isusu\Documents\third\node_modules\https\package.json]
[C:\Users\isusu\Documents\third\myApp\node_modules\https]
[C:\Users\isusu\Documents\third\node_modules\https]
[C:\Users\isusu\Documents\third\myApp\node_modules\https.ts]
[C:\Users\isusu\Documents\third\node_modules\https.ts]
[C:\Users\isusu\Documents\third\myApp\node_modules\https.tsx]
[C:\Users\isusu\Documents\third\node_modules\https.tsx]
[C:\Users\isusu\Documents\third\myApp\node_modules\https.mjs]
[C:\Users\isusu\Documents\third\node_modules\https.mjs]
[C:\Users\isusu\Documents\third\myApp\node_modules\https.js]
[C:\Users\isusu\Documents\third\node_modules\https.js]
 @ ./node_modules/tunnel-agent/index.js 6:12-28
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/node-pre-gyp/lib/install.js
 @ ./node_modules/node-pre-gyp/lib sync ^\.\/.*$
 @ ./node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ ./node_modules/@tensorflow/tfjs-node/dist/index.js
 @ ./src/app/predict/predict.page.ts
 @ ./src/app/predict/predict-routing.module.ts
 @ ./src/app/predict/predict.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ../node_modules/needle/lib/needle.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\isusu\Documents\third\node_modules\needle\lib'
resolve 'https' in 'C:\Users\isusu\Documents\third\node_modules\needle\lib'
  Parsed request is a module
  using description file: C:\Users\isusu\Documents\third\node_modules\needle\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/Users/isusu/Documents/third/myApp
        using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./https)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\https.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\https doesn't exist
      C:\Users\isusu\Documents\third\node_modules\needle\lib\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\third\node_modules\needle\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\third\node_modules\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\node_modules doesn't exist or is not a directory
      C:\Users\isusu\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\isusu\Documents\third\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.tsx doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\https.js doesn't exist
        as directory
          C:\Users\isusu\Documents\third\node_modules\https doesn't exist
[C:\Users\isusu\Documents\third\myApp\https]
[C:\Users\isusu\Documents\third\myApp\https.ts]
[C:\Users\isusu\Documents\third\myApp\https.tsx]
[C:\Users\isusu\Documents\third\myApp\https.mjs]
[C:\Users\isusu\Documents\third\myApp\https.js]
[C:\Users\isusu\Documents\third\node_modules\needle\lib\node_modules]
[C:\Users\isusu\Documents\third\node_modules\needle\node_modules]
[C:\Users\isusu\Documents\third\node_modules\node_modules]
[C:\Users\isusu\Documents\node_modules]
[C:\Users\isusu\node_modules]
[C:\Users\node_modules]
[C:\node_modules]
[C:\Users\isusu\Documents\third\node_modules\package.json]
[C:\Users\isusu\Documents\third\node_modules\https\package.json]
[C:\Users\isusu\Documents\third\node_modules\https]
[C:\Users\isusu\Documents\third\node_modules\https.ts]
[C:\Users\isusu\Documents\third\node_modules\https.tsx]
[C:\Users\isusu\Documents\third\node_modules\https.mjs]
[C:\Users\isusu\Documents\third\node_modules\https.js]
 @ ../node_modules/needle/lib/needle.js 10:18-34
 @ ./node_modules/node-pre-gyp/lib/install.js
 @ ./node_modules/node-pre-gyp/lib sync ^\.\/.*$
 @ ./node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ ./node_modules/@tensorflow/tfjs-node/dist/index.js
 @ ./src/app/predict/predict.page.ts
 @ ./src/app/predict/predict-routing.module.ts
 @ ./src/app/predict/predict.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\isusu\Documents\third\myApp\node_modules\forever-agent'
resolve 'net' in 'C:\Users\isusu\Documents\third\myApp\node_modules\forever-agent'
  Parsed request is a module
  using description file: C:\Users\isusu\Documents\third\myApp\node_modules\forever-agent\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/Users/isusu/Documents/third/myApp
        using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\net doesn't exist
      C:\Users\isusu\Documents\third\myApp\node_modules\forever-agent\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\third\myApp\node_modules\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\node_modules doesn't exist or is not a directory
      C:\Users\isusu\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\isusu\Documents\third\myApp\node_modules
        using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\Users\isusu\Documents\third\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
          using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./node_modules/net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\net doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\net.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\net.tsx doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\net.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\node_modules\net doesn't exist
          C:\Users\isusu\Documents\third\node_modules\net.js doesn't exist
        as directory
          C:\Users\isusu\Documents\third\node_modules\net doesn't exist
[C:\Users\isusu\Documents\third\myApp\net]
[C:\Users\isusu\Documents\third\myApp\net.ts]
[C:\Users\isusu\Documents\third\myApp\net.tsx]
[C:\Users\isusu\Documents\third\myApp\net.mjs]
[C:\Users\isusu\Documents\third\myApp\net.js]
[C:\Users\isusu\Documents\third\myApp\node_modules\forever-agent\node_modules]
[C:\Users\isusu\Documents\third\myApp\node_modules\node_modules]
[C:\Users\isusu\Documents\node_modules]
[C:\Users\isusu\node_modules]
[C:\Users\node_modules]
[C:\node_modules]
[C:\Users\isusu\Documents\third\node_modules\package.json]
[C:\Users\isusu\Documents\third\node_modules\net\package.json]
[C:\Users\isusu\Documents\third\myApp\node_modules\net]
[C:\Users\isusu\Documents\third\node_modules\net]
[C:\Users\isusu\Documents\third\myApp\node_modules\net.ts]
[C:\Users\isusu\Documents\third\node_modules\net.ts]
[C:\Users\isusu\Documents\third\myApp\node_modules\net.tsx]
[C:\Users\isusu\Documents\third\node_modules\net.tsx]
[C:\Users\isusu\Documents\third\myApp\node_modules\net.mjs]
[C:\Users\isusu\Documents\third\node_modules\net.mjs]
[C:\Users\isusu\Documents\third\myApp\node_modules\net.js]
[C:\Users\isusu\Documents\third\node_modules\net.js]
 @ ./node_modules/forever-agent/index.js 6:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/node-pre-gyp/lib/install.js
 @ ./node_modules/node-pre-gyp/lib sync ^\.\/.*$
 @ ./node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ ./node_modules/@tensorflow/tfjs-node/dist/index.js
 @ ./src/app/predict/predict.page.ts
 @ ./src/app/predict/predict-routing.module.ts
 @ ./src/app/predict/predict.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\isusu\Documents\third\myApp\node_modules\tough-cookie\lib'
resolve 'net' in 'C:\Users\isusu\Documents\third\myApp\node_modules\tough-cookie\lib'
  Parsed request is a module
  using description file: C:\Users\isusu\Documents\third\myApp\node_modules\tough-cookie\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/Users/isusu/Documents/third/myApp
        using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\net.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\net doesn't exist
      C:\Users\isusu\Documents\third\myApp\node_modules\tough-cookie\lib\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\third\myApp\node_modules\tough-cookie\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\third\myApp\node_modules\node_modules doesn't exist or is not a directory
      C:\Users\isusu\Documents\node_modules doesn't exist or is not a directory
      C:\Users\isusu\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\isusu\Documents\third\myApp\node_modules
        using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\Users\isusu\Documents\third\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
          using description file: C:\Users\isusu\Documents\third\myApp\package.json (relative path: ./node_modules/net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\net doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\net.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\net.tsx doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
          C:\Users\isusu\Documents\third\node_modules\net.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
              C:\Users\isusu\Documents\third\myApp\node_modules\net.js doesn't exist
            as directory
              C:\Users\isusu\Documents\third\myApp\node_modules\net doesn't exist
          C:\Users\isusu\Documents\third\node_modules\net.js doesn't exist
        as directory
          C:\Users\isusu\Documents\third\node_modules\net doesn't exist

**Comment by bmuenzenmeyer** [comment]
This question is idle and left unanswered for years now.

- Does the behavior persist if you upgrade to a new version of Node.js? This reported version is [end of life](https://github.com/nodejs/release#release-schedule).
- Have you attempted to ask this question within other communities, such as [stackoverflow](https://stackoverflow.com/questions/tagged/node.js?tab=Newest)?

I am going to circle back in a couple weeks to see if we can close as no-longer relevant.

**Comment by bmuenzenmeyer** [comment]
closing per the above plan
