### ISSUE TITLE
Performance price of  script.runInThisContext([options])

### ISSUE THREAD

**Issue by exx8** [nodejs/help#3110]
* **Node.js Version**: any
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:
VM

How performance intensive is to run for each request :
script.runInThisContext([options])?
I believe the function might spawn a new thread each time, which might have a great cost.

**Comment by addaleax** [comment]
> I believe the function might spawn a new thread each time, which might have a great cost.

It does not, unless you specify the `timeout` or `breakOnSigint` options.

**Comment by exx8** [comment]
> > I believe the function might spawn a new thread each time, which might have a great cost.
> 
> It does not, unless you specify the `timeout` or `breakOnSigint` options.

Actually, the timeout feature is what I'm interested.

**Comment by addaleax** [comment]
Then, yes, it will spawn a new native thread each time. If you want to figure out the performance impact of that, it’s going to vary from system to system, so you’d probably have to do some benchmarking for this.

**Comment by exx8** [comment]
> Then, yes, it will spawn a new native thread each time. If you want to figure out the performance impact of that, it’s going to vary from system to system, so you’d probably have to do some benchmarking for this.

Does node recycle the thread it uses for the vm?

**Comment by addaleax** [comment]
> > Then, yes, it will spawn a new native thread each time. If you want to figure out the performance impact of that, it’s going to vary from system to system, so you’d probably have to do some benchmarking for this.
> 
> Does node recycle the thread it uses for the vm?

No, it spawns a new thread every time.

**Comment by exx8** [comment]
> > > Then, yes, it will spawn a new native thread each time. If you want to figure out the performance impact of that, it’s going to vary from system to system, so you’d probably have to do some benchmarking for this.
> > 
> > 
> > Does node recycle the thread it uses for the vm?
> 
> No, it spawns a new thread every time.

can you please send me where this function is implemented?
Thanks

**Comment by addaleax** [comment]
Sure!

https://github.com/nodejs/node/blob/20de5f7efce655d435cfb5ae0811577314fbdeb9/src/node_contextify.cc#L949-L985 might be relevant for you, and in particular the `Watchdog` class which is implemented in https://github.com/nodejs/node/blob/20de5f7efce655d435cfb5ae0811577314fbdeb9/src/node_watchdog.h and https://github.com/nodejs/node/blob/20de5f7efce655d435cfb5ae0811577314fbdeb9/src/node_watchdog.cc.
