### ISSUE TITLE
How get  a PID and KILL it by node.js

### ISSUE THREAD

**Issue by iranweld** [nodejs/help#3112]
I need  Node.js cod to get PID by port number and then kill this program in windows

In cmd command this work : 

netstat -ano | findstr :port_number        // this code return PID a program listen to given port

taskkill /PID  PID_Number /F       // this code kill this program

**Comment by Lxxyx** [comment]
this npm package will help you. [cross-port-killer](https://www.npmjs.com/package/cross-port-killer)

**Comment by iranweld** [comment]
My Dear

tanks for yours Answer.
This is a useful to help me.

**Comment by Lxxyx** [comment]
If Issue resolves, you can close this issue. @iranweld
