### ISSUE TITLE
NPM Build Error 

### ISSUE THREAD

**Issue by mrfortune** [nodejs/help#3113]
Hi,
I am trying to buid a react project and I am getting this error when I do the npm run build:
info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle trydo@0.1.0~prebuild: trydo@0.1.0
6 info lifecycle trydo@0.1.0~build: trydo@0.1.0
7 verbose lifecycle trydo@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle trydo@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/robertharris/Desktop/worldshaker/reactproject/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin
9 verbose lifecycle trydo@0.1.0~build: CWD: /Users/robertharris/Desktop/worldshaker/reactproject
10 silly lifecycle trydo@0.1.0~build: Args: [ '-c', 'node scripts/build.js' ]
11 silly lifecycle trydo@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle trydo@0.1.0~build: Failed to exec build script
13 verbose stack Error: trydo@0.1.0 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid trydo@0.1.0
15 verbose cwd /Users/robertharris/Desktop/worldshaker/reactproject
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error trydo@0.1.0 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the trydo@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

> trydo@0.1.0 build /Users/robertharris/Desktop/worldshaker/reactproject
> node scripts/build.js

/Users/robertharris/Desktop/worldshaker/reactproject/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:104
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
    at validate (/Users/robertharris/Desktop/worldshaker/reactproject/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at new TerserPlugin (/Users/robertharris/Desktop/worldshaker/reactproject/node_modules/terser-webpack-plugin/dist/index.js:118:31)
    at module.exports (/Users/robertharris/Desktop/worldshaker/reactproject/config/webpack.config.js:182:9)
    at Object.<anonymous> (/Users/robertharris/Desktop/worldshaker/reactproject/scripts/build.js:47:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: { additionalProperty: 'sourceMap' },
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: {
        definitions: {
          Rule: {
            description: 'Filtering rule as regex or string.',
            anyOf: [Array]
          },
          Rules: { description: 'Filtering rules.', anyOf: [Array] }
        },
        title: 'TerserPluginOptions',
        type: 'object',
        additionalProperties: false,
        properties: {
          test: {
            description: 'Include all modules that pass test assertion.',
            oneOf: [Array]
          },
          include: {
            description: 'Include all modules matching any of these conditions.',
            oneOf: [Array]
          },
          exclude: {
            description: 'Exclude all modules matching any of these conditions.',
            oneOf: [Array]
          },
          terserOptions: {
            description: 'Options for `terser`.',
            additionalProperties: true,
            type: 'object'
          },
          extractComments: {
            description: 'Whether comments shall be extracted to a separate file.',
            anyOf: [Array]
          },
          parallel: {
            description: 'Use multi-process parallel running to improve the build speed.',
            anyOf: [Array]
          },
          minify: {
            description: 'Allows you to override default minify function.',
            instanceof: 'Function'
          }
        },
        default: {
          definitions: { Rule: [Object], Rules: [Object] },
          title: 'TerserPluginOptions',
          type: 'object',
          additionalProperties: false,
          properties: {
            test: [Object],
            include: [Object],
            exclude: [Object],
            terserOptions: [Object],
            extractComments: [Object],
            parallel: [Object],
            minify: [Object]
          }
        }
      },
      data: {
        terserOptions: {
          parse: { ecma: 8 },
          compress: { ecma: 5, warnings: false, comparisons: false, inline: 2 },
          mangle: { safari10: true },
          output: { ecma: 5, comments: false, ascii_only: true }
        },
        parallel: true,
        cache: true,
        sourceMap: true
      },
      children: [
        {
          keyword: 'additionalProperties',
          dataPath: '',
          schemaPath: '#/additionalProperties',
          params: { additionalProperty: 'cache' },
          message: 'should NOT have additional properties',
          schema: false,
          parentSchema: {
            definitions: [Object],
            title: 'TerserPluginOptions',
            type: 'object',
            additionalProperties: false,
            properties: [Object],
            default: [Object]
          },
          data: {
            terserOptions: [Object],
            parallel: true,
            cache: true,
            sourceMap: true
          },
          children: undefined
        }
      ]
    }
  ],
  schema: {
    definitions: {
      Rule: {
        description: 'Filtering rule as regex or string.',
        anyOf: [
          { instanceof: 'RegExp', tsType: 'RegExp' },
          { type: 'string', minLength: 1 }
        ]
      },
      Rules: {
        description: 'Filtering rules.',
        anyOf: [
          { type: 'array', items: [Object] },
          { '$ref': '#/definitions/Rule' }
        ]
      }
    },
    title: 'TerserPluginOptions',
    type: 'object',
    additionalProperties: false,
    properties: {
      test: {
        description: 'Include all modules that pass test assertion.',
        oneOf: [ { '$ref': '#/definitions/Rules' } ]
      },
      include: {
        description: 'Include all modules matching any of these conditions.',
        oneOf: [ { '$ref': '#/definitions/Rules' } ]
      },
      exclude: {
        description: 'Exclude all modules matching any of these conditions.',
        oneOf: [ { '$ref': '#/definitions/Rules' } ]
      },
      terserOptions: {
        description: 'Options for `terser`.',
        additionalProperties: true,
        type: 'object'
      },
      extractComments: {
        description: 'Whether comments shall be extracted to a separate file.',
        anyOf: [
          { type: 'boolean' },
          { type: 'string', minLength: 1 },
          { instanceof: 'RegExp' },
          { instanceof: 'Function' },
          {
            additionalProperties: false,
            properties: [Object],
            type: 'object'
          }
        ]
      },
      parallel: {
        description: 'Use multi-process parallel running to improve the build speed.',
        anyOf: [ { type: 'boolean' }, { type: 'integer' } ]
      },
      minify: {
        description: 'Allows you to override default minify function.',
        instanceof: 'Function'
      }
    },
    default: {
      definitions: {
        Rule: {
          description: 'Filtering rule as regex or string.',
          anyOf: [ [Object], [Object] ]
        },
        Rules: {
          description: 'Filtering rules.',
          anyOf: [ [Object], [Object] ]
        }
      },
      title: 'TerserPluginOptions',
      type: 'object',
      additionalProperties: false,
      properties: {
        test: {
          description: 'Include all modules that pass test assertion.',
          oneOf: [ [Object] ]
        },
        include: {
          description: 'Include all modules matching any of these conditions.',
          oneOf: [ [Object] ]
        },
        exclude: {
          description: 'Exclude all modules matching any of these conditions.',
          oneOf: [ [Object] ]
        },
        terserOptions: {
          description: 'Options for `terser`.',
          additionalProperties: true,
          type: 'object'
        },
        extractComments: {
          description: 'Whether comments shall be extracted to a separate file.',
          anyOf: [ [Object], [Object], [Object], [Object], [Object] ]
        },
        parallel: {
          description: 'Use multi-process parallel running to improve the build speed.',
          anyOf: [ [Object], [Object] ]
        },
        minify: {
          description: 'Allows you to override default minify function.',
          instanceof: 'Function'
        }
      }
    }
  },
  headerName: 'Terser Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trydo@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trydo@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robertharris/.npm/_logs/2020-12-04T21_22_55_850Z-debug.log

Please help resolve.

**Comment by Lxxyx** [comment]
It seems to be a Webpack sourcemap configuration issue, so check the documentation to see if the input parameters are wrong

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
