### ISSUE TITLE
Why Node.exe doubled .exe filesize? v12 vs v14

### ISSUE THREAD

**Issue by jardicc** [nodejs/help#3114]
* **Node.js Version**: 12 vs 14
* **OS**: win10 -64bit

Why Node.exe doubled .exe filesize?
It has 53,8MB in version 14 but 27,9MB in version 12

**Comment by addaleax** [comment]
A large part of that addition is that Node.js now ships with [full internationalization data](https://github.com/nodejs/node/pull/29522) by default. If necessary, you can build Node.js from source with minimal internationalization data instead.

**Comment by jardicc** [comment]
Oh no... I don't need internationalization. Thanks for the explanation anyway.

Is there any easy tutorial on how to do that? Or perhaps is such a .exe already available? Also, I do use node-gyp. Will be node-gyp affected when the .exe file will have an unexpected structure?

**Comment by addaleax** [comment]
> Is there any easy tutorial on how to do that?

https://github.com/nodejs/node/blob/master/BUILDING.md#windows-3

> Or perhaps is such a .exe already available? 

Not that I am aware of.

> Also, I do use node-gyp. Will be node-gyp affected when the .exe file will have an unexpected structure?

I don’t think so.

**Comment by jardicc** [comment]
Ok, thanks! It doesn't seem to be like 15 minutes of work for me.
