### ISSUE TITLE
Error: unexpected end of file at Zlib.zlibOnError when loading very large file

### ISSUE THREAD

**Issue by mcv** [nodejs/help#3118]
* **Node.js Version**: v12.13.1
* **OS**: Windows, Docker + Alpine
* **Scope (install, code, runtime, meta, other?)**: loading a 245 MB file from an AWS S3 bucket, gunzipping it to process the contents
* **Module (and version) (if relevant)**: zlib

Loading a very large gzip file from an s3 bucket, zlib.gunzip randomly throws an "unexpected end of file" error. Sometimes it succeeds, usually it fails, but at different points in the file.

```js
const file = await readS3File( s3options );
return new Promise(((resolve, reject) => {
  Papa.parse(file.createReadStream().pipe(zlib.createGunzip()), papaparseOptions);
});
```

The error is:
 Error: unexpected end of file
     at Zlib.zlibOnError [as onerror] (zlib.js:180:17) {
   errno: -5,
   code: 'Z_BUF_ERROR'

I have used this or similar code dozens of times with smaller files, and that worked fine. Undoubtedly the size of this file (250 MB gzipped, 1.1 GB unzipped) is the cause, but sometimes it does succeed, so it's not impossible.

**Comment by PoojaDurgad** [comment]
@mcv - probably you can refer this https://github.com/jeffijoe/typesync/issues/37 to resolve your issue.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.

**Comment by MGH2558** [comment]
This problem was solved for me when I deleted the whole directory of the project and cloned it again and followed the setup instructions of the project.
