### ISSUE TITLE
Regarding nodejs support for Win CE with ARM Processor

### ISSUE THREAD

**Issue by ashokvardhank** [nodejs/help#312]
We have requirement to run node js server on 2 different devices with ARM processor which runs on Win CE OS on one device and Linux OS on another device.  Since node is complied for Linux, we were able to run a node js server on device that has Linux OS.  But there is no Win CE compatible version of node available.

I would like to know how to run node on Win CE running devices?  Is there a plan for supporting node js for Win CE platform?  If yes, is there any timeline that we can expect? Any kind of help is appreciated?

Regards
Ashok

**Comment by bnoordhuis** [comment]
Win CE is currently not supported and neither are there plans to support it.  I don't expect that to change anytime soon because at least some of our build dependencies don't support it either.
