### ISSUE TITLE
(Install Issue) "is not valid short file name"

### ISSUE THREAD

**Issue by OCsonic** [nodejs/help#3122]
* **Node.js Version**: 14.15.1
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Install

When installing NodeJS I get this error, I previously had it installed but uninstalled it, Presumably some of it didn't fully uninstall?

![image](https://user-images.githubusercontent.com/50123826/102002521-28209000-3cb2-11eb-826c-ae9d4bcc7e82.png)

**Comment by PoojaDurgad** [comment]
@xXOCsonicLeEpicMemeXx - looks like this is not a problem with the node but the windows installer where the previous installed version of node is not removed. what you can do is select `nodejs` from the list of installed programs and remove nodejs and also remove the entry for node and then click ok to confirm the removal. Restart your computer if needed and then install the latest stable version of node from the official website https://nodejs.org/en/download/ hope it helps

**Comment by xXOCsonicLeEpicMemeXx** [comment]
> 
> 
> @xXOCsonicLeEpicMemeXx - looks like this is not a problem with the node but the windows installer where the previous installed version of node is not removed. what you can do is select `nodejs` from the list of installed programs and remove nodejs and also remove the entry for node and then click ok to confirm the removal. Restart your computer if needed and then install the latest stable version of node from the official website https://nodejs.org/en/download/ hope it helps

I already tried that, but it comes up with errors when I attempt to remove it via the installed programs list.

**Comment by mweiss237** [comment]
Same problem over here... Uninstalling is impossible as the same installer window appears with the same error.

**Comment by OCsonic** [comment]
> Same problem over here... Uninstalling is impossible as the same installer window appears with the same error.

The thing that fixed the issue for me was updating, I thought I was up-to-date but version 202H was bugged and refusing to update, So I had to uninstall a *supposedly* corrupted version of VirtualBox and use the manual Windows updater. Since then it worked no problem.

**Comment by water007melon** [comment]
use windows tool MicrosoftProgram_Install_and_Uninstall.meta.diagcab uninstall node  can fix this bug.

**Comment by DoramisStudio** [comment]
> use windows tool MicrosoftProgram_Install_and_Uninstall.meta.diagcab uninstall node can fix this bug.

and how do you run that? with Command Prompt or something?
