### ISSUE TITLE
My Discord Bot will not stay online using the Sudo Main.js Command it throws and error 

### ISSUE THREAD

**Issue by Ufreewoody** [nodejs/help#3125]
When I execute the Sudo Main.js command to bring the Bot online I get this error

node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module '/Users/ufreewoody/main.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js Version 15.4.0
IOS Big Sur v11.0.1

Here is a copy of my Index.js which has been renamed Main.js

const Discord = require('discord.js');

const client = new Discord.Client();

const prefix = '-';

const fs = require('fs');

client.commands = new Discord.Collection();

const commandFiles = fs.readdirSync('./commands/').filter(file => file.endsWith('.js'));
for(const file of commandFiles){
    const command = require('./commands/${file}');

    client.commands.set(command.name.command);

}

client.once('ready',() => {
    console.log('Walter is Online!');
});

client.on('message', message=>{
    if(!message.content.startsWith(prefix) || message.author.bot) return;

    const args = message.content.slice(prefix.length).split(/ +/);
    const command = args.shift().toLowerCase();

    if (command === 'ping'){
        client.commands.get('ping').execute(message, args);
    } else if (command == 'youtube'){
        client.commands.get('youtube').execute(message, args);
    } else if (command == 'Strawberry'){
        message.channel.send('Lite Blue Butterfly');
    } else if (command == ('Blue Butterfly')){
        message.command.send('Sugie StrawBerry');
    }

});

client.login('NzgwNTA1ODM1NDk0MTc4ODE2.X7wEtA.fy9ssTMv4P7LJFZ26MXGFyNrSGs');

I downloaded and installed Node.js Runtime and Discord.js for the Discord Bot
then I executed the Sudo Node Main.js when I get the error.

Please help
Thanks so much,
Woody

**Comment by RaisinTen** [comment]
> Error: Cannot find module '/Users/ufreewoody/main.js'

The error message claims that you ran `main.js` instead of `Main.js`. Is that the case?

**Comment by Ufreewoody** [comment]
Darshan Sen, I tried using Main.js instead of main.js and its still not
working.
I checked in the folder and the file is in fact main.js in the folder.
I have tried it both ways and that doesn't work either.

Well i’m still working on it the problem still exists

Thanks so  much for your help

**Comment by Ufreewoody** [comment]
Darshan Sen, I put the error in google and did a search and there are a lot
of hits with this problem but
I have not found one that provides a solution that fixes the problem. Just
so you know ok.

Thanks so much,
Woody

**Comment by RaisinTen** [comment]
Btw, is using `sudo` necessary here?

Consider pasting in the logs you get when you run `dir main.js`, `dir Main.js`, `node main.js` and `node Main.js` in the same directory where your file is placed.

Also, enclose your logs with surrounding \`\`\`s like this:
````
```
<paste-your-log-here>
```
````

**Comment by Ufreewoody** [comment]
Darshan Sen, I'm not sure what you are asking me to do. I used terminal to
get in the folder and attempted the dir main.js command you have listed
above
it says Command Not Found. So how do i create this log file that you are
asking for?
Darshan Sen, I am more than willing to give you access to my desktop
remotely and you can show me what you are speaking of.

Thanks so much,
Woody

**Comment by RaisinTen** [comment]
Okay, then try doing the same by replacing `dir` with `ls` in the commands.

**Comment by Ufreewoody** [comment]
Hello to everyone that helped on this issue, I was able to fix the problem.
It turned out to be a capitalization issue with the syntax of the commands being in 
lowercase made this edit and everything is working now. thanks so much to you all.
