### ISSUE TITLE
do promises get resolved between the end of eventloop phase and before the start Phase of the eventloop?

### ISSUE THREAD

**Issue by Divine1** [nodejs/help#3126]
This is my understanding on promises 
- promises are handled by the microtaskqueue in v8. promises are not handled by the libuv eventloop

in the output of the below example you can see the `promise resolved` output gets printed 
- **before** `nexttick` 
- **above**  `settimeout` and `setimmediate` 

i'm not able to understand, the execution order of promise while it is used  along with `setTimeout` `process.nextTick` `setImmediate`. The **output** i received makes me to think as if  promises always execute before the beginning phase of the eventloop. 

**Please clarify this**

**Example program**
```
const p1 = new Promise((resolve,reject)=>{
    console.log("inside promise");
    resolve()
})

p1.then((da)=>{
    console.log("promise resolved ");
})
process.nextTick(()=>{
    console.log("nexttick")
})
console.log("demo1");

setTimeout(()=>{
    console.log("settimeout")
},0)
setImmediate(()=>{
    console.log("setimmediate")
})
console.log("demo2");
console.log("demo3");

**output**
inside promise
demo1
demo2
demo3
nexttick
promise resolved 
settimeout
setimmediate
```

Could you tell me the execution order of promises when it is mixed with async functions like `setTimeout` `setImmediate` `process.nextTick` ..?

[screenshot taken from this link](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#event-loop-explained)
<img width="790" alt="image" src="https://user-images.githubusercontent.com/10482177/102282944-77d3b580-3f57-11eb-958b-6e61bb139781.png">

**Comment by addaleax** [comment]
>     * promises are handled by the microtaskqueue in v8. promises are not handled by the libuv eventloop

:+1:

> The **output** i received makes me to think as if promises always execute before the beginning phase of the eventloop.

It’s always at the end of a callback from the event loop, after returning control from C++ to JS.

> Could you tell me the execution order of promises when it is mixed with async functions like `setTimeout` `setImmediate` `process.nextTick` ..?

With `setTimeout` and `setImmediate` it’s easy – the `process.nextTick` and microtask/promise queues are run immediately after the callbacks passed to the timer functions. The ordering of `nextTick` and the microtask queue is a bit more complex – the nextTick queue and microtask queue are run alternatingly until both are empty, starting with the nextTick queue.

**Comment by Divine1** [comment]
@addaleax thank you.

> It’s always at the end of a callback from the event loop, after returning control from JS to C++.

i'm not able to understand this part. could you detail me on this?
What would return the control from JS to C++ ? What is holding the control in JS?

**Comment by addaleax** [comment]
```js
setTimeout(() => { console.log('This is JS code'); });
```

After the function returns, the event loop is in control again and no JS is running anymore. That’s in C/C++ land.

**Comment by Divine1** [comment]
@addaleax thank you :)
