### ISSUE TITLE
IPV4 / IPV6

### ISSUE THREAD

**Issue by toinelin** [nodejs/help#3127]
* **Node.js Version**: 14.13.0
* **OS**: MacOS Catalina 10.15.7
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: /

Hello ! 🖖 

I would like to geolocalise my users by getting their IP address on my NodeJS app.
The problem I had is that with a classic IPv4 all is working like a charm and the user is localized pretty accurately, but when it connects using IPv6 the geolocation is at miles of being accurate.
Is there a way to get both IPv4 and IPv6 (While doing some researches I found that this is not possible but some services like [https://www.whatismyip.com/](https://www.whatismyip.com/) succeed to get and display both, maybe there is a solution I did not found out yet).

Thank you 🙏

**Comment by gireeshpunathil** [comment]
@toinelin -  is this outstanding? which Node.js API / capability is the subject of this question?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
