### ISSUE TITLE
How to tell the real source of an error in a callback?

### ISSUE THREAD

**Issue by ugultopu** [nodejs/help#3129]
I'm trying to use a function as a callback in possibly multiple places. However, I can't figure out how to make the callback function tell me the real source of the error.

```javascript
// `throwIfError` is a function that could be used as a callback
// in multiple places.
function throwIfError(err) {
  if(err) {
    // Some code that will tell me that the error originated from a call
    // to `fs.writeFile` in this file (that is, line 13), instead of
    // from the internals of the `writeFile` function. After that, it
    // will throw the same or a new error so that the program will fail
    // early, instead of continuing with the wrong data.
  }
}

require('fs').writeFile(
  'some_non_existent_directory/test.txt',
  '',
  throwIfError
);
```

Somebody suggested this solution:

```javascript
function throwIfError(err, fromwhere) {
  if(err) {
    console.log(`Error came from ${fromwhere}`);
  }
}

require('fs').writeFile(
  'some_non_existent_directory/test.txt',
  '',
  err => throwIfError(err, 'fs.writeFile')
);
```

But I don't like it because:
- You have to manually indicate it. This feels just wrong.
- It will not include the file name/path and line number.

So, what's the solution for this?

**Comment by RaisinTen** [comment]
How about this:
```js
require('fs').writeFile(
  'some_non_existent_directory/test.txt',
  '',
  err => console.trace()
);
```
It produces:
```sh
❯ node index.js
Trace
    at <file-name>.js:4:18
    at node:fs:1472:7
    at FSReqCallback.oncomplete (node:fs:179:23)
```

**Comment by ugultopu** [comment]
That defeats the purpose because now the callback is being defined at the place that it is passed (to a function). The purpose was to define a "general-purpose" callback _once_, and use it in multiple places.

As far as I can tell, this is impossible. That is, if I'm not wrong, the only way to understand this is to supply the stack trace information in the error. Normally, when you create an error (say, using `const err = Error('A message')`), the stack information at the time that the error is created is included in the error object (`err`). However, for some reason, the stack information is not present in the error object that is passed by `fs.writeFile`. Instead, there is only a copy of the error message with `Error: ` prepended to it.

https://github.com/nodejs/node/blob/b49145f795658c7187a94897d31f665c2fbff471/lib/fs.js#L1499:

```javascript
openErr: Error: ENOENT: no such file or directory, open 'some_non_existent_directory/test.txt'
  code: "ENOENT"
  errno: -2
  path: "some_non_existent_directory/test.txt"
  syscall: "open"
  message: "ENOENT: no such file or directory, open 'some_non_existent_directory/test.txt'"
  stack: "Error: ENOENT: no such file or directory, open 'some_non_existent_directory/test.txt'"
  __proto__:
    constructor: ƒ Error()
    message: ""
    name: "Error"
    toString: ƒ toString()
    __proto__: Object
```

Hence, when I print or `throw` this error in in `throwIfError` function, I don't get a stack trace simply because there is no stack trace information present in the `error` object that has been passed to the callback.
