### ISSUE TITLE
Unable to install NodeJS in Windows 10

### ISSUE THREAD

**Issue by rejunp** [nodejs/help#313]
Error : the installer has encountered an unexpected error installing this package 2503

**Comment by lordKnighton** [comment]
when you installed it, where did you install it?

this problem appears to be a windows problem not a node.js problem #googlesearch 

Here's a few links:  
 https://www.youtube.com/watch?v=_3LvrDd3KUk
http://stackoverflow.com/questions/27344045/installing-node-js-and-npm-on-windows-10

**Comment by lordKnighton** [comment]
closing for now. If you need more help, let us know. 😄

**Comment by balalaXD** [comment]
Hi, i am encoutered this error too!
But what lordKnighton said doesnt help at all for me,
the good news is that i fix this error.
maybe some help for you.

![img](http://www.urtech.ca/wp-content/uploads/2016/02/error-2503-2502-windows-10-change-temp-permissions.jpg)

**Comment by rejunp** [comment]
@balalaXD Thanks alot. The solution of giving Full control to temp folder for Everyone worked.

**Comment by refack** [comment]
Marking for follow up

**Comment by lexxpalad31** [comment]
![image](https://user-images.githubusercontent.com/67300913/103458625-f2b51280-4d44-11eb-8fea-cb196b2a90fb.png)


How about this? Please help

**Comment by Perfect-Dav** [comment]
I got this error when I'm trying to install node.js. I've tried all the listed answers, none worked. 
![Screenshot (2)](https://user-images.githubusercontent.com/60663925/105024620-29578200-5a01-11eb-842e-795d7fdc226c.png)

**Comment by MitulPanchal** [comment]
Any idea how to resolve this issue?
![image](https://user-images.githubusercontent.com/14980961/116065197-65574e80-a6a4-11eb-9873-d532b476edd6.png)

**Comment by Olatisunkanmi** [comment]
@MitulPanchal have you found any solution yet ? I am having the same problem

**Comment by bl-ue** [comment]
@Olatisunkanmi can you open a command prompt and run `echo %TEMP%`, and then check the permissions on that folder as directed in @snowman's comment above?

**Comment by dududeuner** [comment]
i got this error, someone know something about?
![111111](https://user-images.githubusercontent.com/86847578/124305406-72c50500-db3b-11eb-99e1-9137cee91c16.jpeg)

**Comment by ladinasedera** [comment]
@Olatisunkanmi , i have a same problem, but it's solved by changing TEMP directory at global Environment Variables as described here https://github.com/nodejs/help/issues/313#issuecomment-295527378

**Comment by umarnsisar021** [comment]
Follow the to install without getting any errors 

please subscribe and like
https://youtu.be/lkJZQ6V3J0k
