### ISSUE TITLE
Windows 10 Installation Hangs

### ISSUE THREAD

**Issue by malkavsheir** [nodejs/help#3130]
I am unable to complete the full installation of NodeJS using the LTS version (file downloaded was "node-v14.15.0-x64.msi"). I am installing this on a brand new EC2 Instance on AWS so there is no conflicting software. I literally only installed Firefox to download the installer.

I am using the base Windows Server 2019 AMI as my starting point on a t3a Large EC2 with 150GB of storage.

Installation seems to work great and then it begins to install chocolatey. This is the output during the installation:
`Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.15.
Downloading 7-Zip commandline tool prior to extraction.
Extracting C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstall\chocolatey.zip to C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstall...
Installing chocolatey on this machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
chocolatey.nupkg file not installed in lib.
 Attempting to locate it from bootstrapper.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\Administrator\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
Chocolatey v0.10.15
Upgrading the following packages:
python;visualstudio2017-workload-vctools
By upgrading you accept licenses for the packages.
python is not installed. Installing...
Progress: Downloading python3 3.9.0... 100%
Progress: Downloading python3 3.9.0... 100%
Progress: Downloading vcredist2015 14.0.24215.20170201... 100%
Progress: Downloading vcredist2015 14.0.24215.20170201... 100%
Progress: Downloading vcredist140 14.27.29112... 100%
Progress: Downloading vcredist140 14.27.29112... 100%
Progress: Downloading chocolatey-core.extension 1.3.5.1... 100%
Progress: Downloading chocolatey-core.extension 1.3.5.1... 100%
Progress: Downloading KB3033929 1.0.5... 100%
Progress: Downloading KB3033929 1.0.5... 100%
Progress: Downloading chocolatey-windowsupdate.extension 1.0.4... 100%
Progress: Downloading chocolatey-windowsupdate.extension 1.0.4... 100%
Progress: Downloading KB3035131 1.0.3... 100%
Progress: Downloading KB3035131 1.0.3... 100%
Progress: Downloading KB2919355 1.0.20160915... 100%
Progress: Downloading KB2919355 1.0.20160915... 100%
Progress: Downloading KB2919442 1.0.20160915... 100%
Progress: Downloading KB2919442 1.0.20160915... 100%
Progress: Downloading KB2999226 1.0.20181019... 100%
Progress: Downloading KB2999226 1.0.20181019... 100%
Progress: Downloading python 3.9.0... 100%
Progress: Downloading python 3.9.0... 100%

chocolatey-core.extension v1.3.5.1 [Approved]
chocolatey-core.extension package files upgrade completed. Performing other installation steps.
 Installed/updated chocolatey-core extensions.
 The upgrade of chocolatey-core.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-core'

chocolatey-windowsupdate.extension v1.0.4 [Approved]
chocolatey-windowsupdate.extension package files upgrade completed. Performing other installation steps.
 Installed/updated chocolatey-windowsupdate extensions.
 The upgrade of chocolatey-windowsupdate.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-windowsupdate'

KB3035131 v1.0.3 [Approved]
kb3035131 package files upgrade completed. Performing other installation steps.
Skipping installation because update KB3035131 does not apply to this operating system (Microsoft Windows Server 2019 Datacenter).
 The upgrade of kb3035131 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB3033929 v1.0.5 [Approved]
kb3033929 package files upgrade completed. Performing other installation steps.
Skipping installation because update KB3033929 does not apply to this operating system (Microsoft Windows Server 2019 Datacenter).
 The upgrade of kb3033929 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2919442 v1.0.20160915 [Approved]
kb2919442 package files upgrade completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The upgrade of kb2919442 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2919355 v1.0.20160915 [Approved]
kb2919355 package files upgrade completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The upgrade of kb2919355 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2999226 v1.0.20181019 [Approved] - Possibly broken
kb2999226 package files upgrade completed. Performing other installation steps.
Skipping installation because update KB2999226 does not apply to this operating system (Microsoft Windows Server 2019 Datacenter).
 The upgrade of kb2999226 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

vcredist140 v14.27.29112 [Approved]
vcredist140 package files upgrade completed. Performing other installation steps.
Downloading vcredist140-x86
  from 'https://download.visualstudio.microsoft.com/download/pr/48431a06-59c5-4b63-a102-20b66a521863/CAA38FD474164A38AB47AC1755C8CCCA5CCFACFA9A874F62609E6439924E87EC/VC_redist.x86.exe'
Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp\chocolatey\vcredist140\14.27.29112\VC_redist.x86.exe (13.62 MB).
Download of VC_redist.x86.exe (13.62 MB) completed.
Hashes match.
Installing vcredist140-x86...
vcredist140-x86 has been installed.
Downloading vcredist140-x64 64 bit
  from 'https://download.visualstudio.microsoft.com/download/pr/48431a06-59c5-4b63-a102-20b66a521863/4B5890EB1AEFDF8DFA3234B5032147EB90F050C5758A80901B201AE969780107/VC_redist.x64.exe'
Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp\chocolatey\vcredist140\14.27.29112\VC_redist.x64.exe (14.16 MB).
Download of VC_redist.x64.exe (14.16 MB) completed.
Hashes match.
Installing vcredist140-x64...
vcredist140-x64 has been installed.
  vcredist140 may be able to be automatically uninstalled.
 The upgrade of vcredist140 was successful.
  Software installed as 'exe', install location is likely default.

vcredist2015 v14.0.24215.20170201 [Approved]
vcredist2015 package files upgrade completed. Performing other installation steps.
 The upgrade of vcredist2015 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

python3 v3.9.0 [Approved]
python3 package files upgrade completed. Performing other installation steps.
Installing 64-bit python3...
python3 has been installed.
Python installed to: 'C:\Python39'
Restricting write permissions to Administrators
  python3 can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The upgrade of python3 was successful.
  Software installed as 'exe', install location is likely default.

python v3.9.0 [Approved]
python package files upgrade completed. Performing other installation steps.
 The upgrade of python was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.
visualstudio2017-workload-vctools is not installed. Installing...
Progress: Downloading chocolatey-visualstudio.extension 1.8.1... 100%
Progress: Downloading chocolatey-visualstudio.extension 1.8.1... 100%
Progress: Downloading chocolatey-visualstudio.extension 1.8.1... 100%
Progress: Downloading visualstudio2017-workload-vctools 1.3.2... 100%
Progress: Downloading visualstudio2017-workload-vctools 1.3.2... 100%
Progress: Downloading visualstudio2017-workload-vctools 1.3.2... 100%
Progress: Downloading visualstudio-installer 2.0.1... 100%
Progress: Downloading visualstudio-installer 2.0.1... 100%
Progress: Downloading visualstudio-installer 2.0.1... 100%
Progress: Downloading visualstudio2017buildtools 15.9.28.0... 100%
Progress: Downloading visualstudio2017buildtools 15.9.28.0... 100%
Progress: Downloading visualstudio2017buildtools 15.9.28.0... 100%
Progress: Downloading dotnetfx 4.8.0.20190930... 100%
Progress: Downloading dotnetfx 4.8.0.20190930... 100%
Progress: Downloading dotnetfx 4.8.0.20190930... 100%
Progress: Downloading chocolatey-dotnetfx.extension 1.0.1... 100%
Progress: Downloading chocolatey-dotnetfx.extension 1.0.1... 100%
Progress: Downloading chocolatey-dotnetfx.extension 1.0.1... 100%

chocolatey-visualstudio.extension v1.8.1 [Approved]
chocolatey-visualstudio.extension package files upgrade completed. Performing other installation steps.
 Installed/updated chocolatey-visualstudio extensions.
 The upgrade of chocolatey-visualstudio.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-visualstudio'

visualstudio-installer v2.0.1 [Approved]
visualstudio-installer package files upgrade completed. Performing other installation steps.
 The upgrade of visualstudio-installer was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

chocolatey-dotnetfx.extension v1.0.1 [Approved]
chocolatey-dotnetfx.extension package files upgrade completed. Performing other installation steps.
 Installed/updated chocolatey-dotnetfx extensions.
 The upgrade of chocolatey-dotnetfx.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-dotnetfx'

dotnetfx v4.8.0.20190930 [Approved]
dotnetfx package files upgrade completed. Performing other installation steps.
Downloading dotnetfx 64 bit
  from 'https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0fd66638cde16859462a6243a4629a50/ndp48-x86-x64-allos-enu.exe'
Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp\chocolatey\dotnetfx\4.8.0.20190930\ndp48-x86-x64-allos-enu.exe (111.94 MB).
Download of ndp48-x86-x64-allos-enu.exe (111.94 MB) completed.
Hashes match.
Installing dotnetfx...`

After this it has been hanging for over 45 minutes. On a much weaker and older computer I was able to install this without any issues.

**Comment by PoojaDurgad** [comment]
inactive. closing the issue . Please feel free to reopen the issue if its still outstanding

**Comment by wizofaus** [comment]
Happening for me too...and had an error about setup timing out. Couldn't even cancel and install again, said another installation is already running (how to kill msi-service from command line and restart service).  But now hanging again with no progress update...

**Comment by UngureanuOvidiu-Costin** [comment]
@malkavsheir, after a restart, I uninstalled the Node.js. I restarted again, installed without checking the `box` which tells about using choco to install other tools. Now all is good. Happy dev!
