### ISSUE TITLE
Why are static and dynamic imports in node.js treated differently wrt read-only?

### ISSUE THREAD

**Issue by clecap** [nodejs/help#3131]
* **Node.js Version**: 15.4.0
* **OS**: MacOS 10.15.6
* **Scope (install, code, runtime, meta, other?)**: code

Why would node.js 15.4.0 treat static and dynamic imports differently wrt to their read-only behavior?

I have a file test.mjs which reads

```js
let a = {x: 1};
export default a;
```
When i use this in a dynamic import:

```js
async function run () {
  var m = await import ("./test.mjs");
  m.d=45;
  console.log (m);
}
run();
```
it complains that the object is not extensible (and this conforms to my reading of the standard that imports provide read-only bindings).

However, when I use this statically as in

```js
import m from './test.mjs';
m.d = 44;
console.log (m);
````

this works nicely and outputs {x:1, d:44}.

Why does this work? Is this not in violation of the standard?

The question is of particular importance for a design decision to be taken now and I am afraid eventually node would also treat static imports as read-only.

**Comment by addaleax** [comment]
> Why does this work? Is this not in violation of the standard?

I don’t think the standard says anything about what you can do with the imported/exported *values*, only with the imports and exports themselves. `m` is just the value of the default here, not a module binding or any other special type of object.

**Comment by clecap** [comment]
I had in mind the remark on MDN: "The static import statement is used to import read only live bindings which are exported by another module."

My concern is that my second example in a later version of node might break and I fail to see why the two cases are delat differently.

**Comment by addaleax** [comment]
@clecap The point is that you can’t assign to the variable `m`, but you can still modify its properties. It’s like a `const` variable declaration – it’s read-only in the sense you can’t change the value itself, but you *can* change properties of that variable.

**Comment by clecap** [comment]
@addaleax Yeah. But why would the behavior be **different** in the static and dynamic import? I fail to understand why my two examples produce different reactions.

**Comment by RaisinTen** [comment]
@clecap you were importing the `default`, not `a`. This works:
```mjs
async function run () {
  var m = (await import ("./test.mjs")).default;
  m.d=45;
  console.log (m);
}
run();
```
It produces this:
```mjs
{ x: 1, d: 45 }
```

**Comment by vsemozhetbyt** [comment]
Another illustration of the difference:

```js
import m1 from 'data:text/javascript,let a = {x: 1}; export default a;';

(async function main() {
  const m2 = await import ('data:text/javascript,let a = {x: 1}; export default a;');
  console.log(m1);
  console.log(m2);
})();

// { x: 1 }
// [Module] { default: { x: 1 } }
```

**Comment by clecap** [comment]
Ahhhh. Import syntax 101. ;-) Of course.
