### ISSUE TITLE
Two consecutive console.logs produce different output + out of memory

### ISSUE THREAD

**Issue by anor731** [nodejs/help#3132]
https://github.com/anor731/pipe_dream/

It does out of memory, IDK why.

It also does only two consecutive console.logs instead of three.

**Comment by ChALkeR** [comment]
That code is basically equivalent to this + console logs:
```
const tick = () => {
  new Promise((res) => {
      res(1)
  }).finally(() => {
      tick()
  })
}
while (true) tick()
```

Which obviously consumes memory.

**Comment by PoojaDurgad** [comment]
closing as answered . feel free to reopen if there is anything pending on this issue
