### ISSUE TITLE
Invalid keystore format for tested pkcs12, jks key

### ISSUE THREAD

**Issue by deathsonic18** [nodejs/help#3133]
* **Node.js Version**: v14.15.3
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:  parse-jks: 0.1.12 , fs:0.0.1-security

Hello :) 

I am creating a key using  for a spring mirco-service : 
`keytool -genkeypair -alias aliasName -keyalg RSA -keysize 10000 -dname "CN=Name, OU=Org, O=Org, L=Place, ST=Place, C=PL" -keypass pass -validity 360 -storetype pkcs12 -keystore key.jks -storepass pass`

I manage to connect to it using the key with postman. 

When it comes to node.js, i keep getting 
`throw new Error('Invalid keystore format');`

example:

```
const jks = require('parse-jks');
const fs = require('fs');

const keystore = jks.toPem(
    fs.readFileSync('key.jks'),
    'pass'
);

const { cert, key } = keystore['aliasName'];

tls.connect('443', 'localhost', {
    key: key,
    cert: cert,
});

```

**Comment by marsonya** [comment]
Hi @deathsonic18, I checked `parse-jks` documentation on npm. And I believe you are doing everything right.
So, this seems like an issue with the npm package. I would recommend opening an issue in the `parse-jks` repo [here](https://github.com/hoangbaoit95/parse-jks/issues).
