### ISSUE TITLE
im having issues to create a advanced command handler

### ISSUE THREAD

**Issue by BonnieTheBunnystar** [nodejs/help#3139]
all the code is working exept :

client.commands = new Discord.Collection();

heres the image 

![Shot 0158](https://user-images.githubusercontent.com/76566924/103100867-73606a00-45f3-11eb-95c0-6b32ada42bb4.png)

**Comment by vsemozhetbyt** [comment]
Should it be `const Discord = require('discord.js');`  and `const client = new Discord.Client();` — with consistent upper case?

**Comment by BonnieTheBunnystar** [comment]
im goin to check dat

**Comment by BonnieTheBunnystar** [comment]
i think it worked 
but it gave me another error

**Comment by BonnieTheBunnystar** [comment]
hers is the new problem it gave me

![Shot 0159](https://user-images.githubusercontent.com/76566924/103102331-3ba8f080-45fa-11eb-8f09-edd6d11a159c.png)

**Comment by incomingstick** [comment]
@BonnieTheBunnystar check your import statements, I bet you are missing a `.`

Notice the error code is `MODULE_NOT_FOUND` this should suggest to you either something you are trying to import, such as a dependency, has not been installed yet, or that you are trying to import a local file directly, but that files location could not be found.

If you look at the error, I bet you can see the file you are trying to import!

**Comment by BonnieTheBunnystar** [comment]
alr thank you
