### ISSUE TITLE
How do you install nodejs from the Linux binary tarball

### ISSUE THREAD

**Issue by schmichael** [nodejs/help#314]
Steps to reproduce:
1. Want to install node
2. Visit https://nodejs.org/en/ and click Current
   - Spend a few minutes looking around the site for installation docs before giving up
3. `tar xaf ...` and look at README.md
4. Follow README's instructions to this project's readme. (see last paragraph of node's readme for instructions+link to come here for installation help).
5. This site has no installation instructions.

Fix:

Go does it ok:
1. Want to install go
2. Visit https://golang.org
3. Click Download
4. See installation link at top of page: https://golang.org/dl/
5. Read installation instructions: https://golang.org/doc/install
6. Have a working Go install
7. Complain about $GOPATH on Twitter

**Comment by bnoordhuis** [comment]
Download and decompress the tarball and the binary is in bin/.  Optionally pass `--strip-components=1` if you want to extract it in e.g. /usr/local.  I don't think it's wildly different from how other projects distribute UNIX binaries.

If you think the website or the bundled documentation can be improved, please file an issue with the website repo or the main repo.

**Comment by jackysmith3344** [comment]
I found some help here:
http://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/
but I've still not really got it working.
Most projects do provide something.
In what sense is this not "filing an issue with the repo"?

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/help is a support forum, it's not the bug tracker that is used by the main project or the website people.
