### ISSUE TITLE
how to enable V8's visibility setting in common.gypi?

### ISSUE THREAD

**Issue by navegador5** [nodejs/help#3140]
* **Node.js v16.0.0-pre.**:
* **Linux**:

example:

common.gypi
{
  'variables': {
    'configuring_node%': 0,
    'asan%': 0,
    'werror': '',                     # Turn off -Werror in V8 build.
    'visibility%': 'hidden',          # V8's visibility setting===============================>

how to enable this?  set to true ? 
what is the word to fill here?

**Comment by RaisinTen** [comment]
Probably `'default'`.

**Comment by marsonya** [comment]
visibility can have one of the following values:-
`default` `internal` `hidden` `protected`

for more details visit [here](https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Code-Gen-Options.html#Code-Gen-Options) (scroll to end for visibility section)
