### ISSUE TITLE
[potentially off-topic] What's the fastest and most reliable way to use fs?

### ISSUE THREAD

**Issue by o0101** [nodejs/help#3142]
Node.JS latest --lts and up
OS: any and all
Threads/processes: from single to multi-process

I want to use fs for reliable, and fast disk access. Fast means "as fast as possible" given reliability. 
Reliable means (all or the largest subset of): Atomicity, Consistency, Isolation and Durability.

For reference, my "awakening" to the issues of files was assisted by: https://danluu.com/deconstruct-files/

I'm wondering is there a pattern of API usage of fs that gives us the fastest and more reliable disk access? This might include special flags for opening, or the inclusion of falls like "fs.fdatasyncSync" for example, or other best practices.

**Comment by marsonya** [comment]
cc @nodejs/fs
