### ISSUE TITLE
Start extremely slowly on windows

### ISSUE THREAD

**Issue by FYWindis** [nodejs/help#3143]
* **Node.js Version**:v14.15.3
* **OS**:Windows 10 20H2 19042.685
* **Scope (install, code, runtime, meta, other?)**:runtime
* **Module (and version) (if relevant)**:

Starting any application based on node.js such as Atom and Visual Studio Code response very very slow.
And I found that even the basic `node -v` command takes long time to response.
I've tried several ways to fix it but no one worked.
Could anybody help me please.

![image](https://user-images.githubusercontent.com/61300312/103148339-8770ac80-4756-11eb-9fb8-0370343c27b4.png)
![image](https://user-images.githubusercontent.com/61300312/103148346-948d9b80-4756-11eb-9749-f8defcee1326.png)

**Comment by PoojaDurgad** [comment]
>Starting any application based on node.js such as Atom and Visual Studio Code response very very slow.

@orangeWindis - IMO node is not that slow as it is a single threaded Non-blocking I/O . may be its some bad code which kills the performance of the language and affects development agility

**Comment by orangeWindis** [comment]
> may be its some bad code which kills the performance of the language and affects development agility
Come on it cant be that. Look at the pictures I uploaded. It's the response time of node when I use the command in Powershell.
It took node.js 2 seconds to echo its version when i type```node -v```

**Comment by PoojaDurgad** [comment]
@orangeWindis - yeah right. but I'm addressing your first comment where you said that ,node based applications are very slow. so I'm saying node is not that slow as it contain the concept of non-blocking I/O. and some bad code affects the performance of lang
>It took node.js 2 seconds to echo its version when i type node -v

what is the response time in other prompts like git bash or windows terminal? not sure but sometimes if you have lot of stuffs in path also drags response time . IMO you can refer this https://en.wikipedia.org/wiki/PATH_(variable) for more detail I guess

**Comment by ondrej-111** [comment]
Even worse here:
![image](https://user-images.githubusercontent.com/17861399/214042764-e4d4e60c-2b2f-4520-8444-38ce80444e41.png)
