### ISSUE TITLE
Require cache problem/question

### ISSUE THREAD

**Issue by nairihar** [nodejs/help#3144]
* **Node.js v12.18.1**:
* **OS**: MacOS
* **Scope runtime**:

I'm trying to create a JSON file after running node, and then require it.

This code works fine.

<img width="298" alt="Screen Shot 2020-12-26 at 3 34 22 PM" src="https://user-images.githubusercontent.com/15065065/103150709-f74f5900-478f-11eb-8eb9-049e73da9928.png">

When I tried to require the file inside try-catch before creation, I wasn't able to require it after creation.

<img width="311" alt="Screen Shot 2020-12-26 at 3 36 48 PM" src="https://user-images.githubusercontent.com/15065065/103150734-2bc31500-4790-11eb-94d7-5285628395ca.png">

Error:
<img width="632" alt="Screen Shot 2020-12-26 at 3 38 40 PM" src="https://user-images.githubusercontent.com/15065065/103150757-6e84ed00-4790-11eb-8602-6b19be353a08.png">

This error related to my second requires, since the first one is inside trying catch. Meanwhile, my file was created.

<img width="202" alt="Screen Shot 2020-12-26 at 3 39 33 PM" src="https://user-images.githubusercontent.com/15065065/103150768-8e1c1580-4790-11eb-851d-e9268d1a2ae0.png">

I thought there is a cache, so I need to delete the value for my file from `require.cache`.

<img width="514" alt="Screen Shot 2020-12-26 at 3 40 55 PM" src="https://user-images.githubusercontent.com/15065065/103150784-befc4a80-4790-11eb-9ed0-53accaeb11d2.png">

But it didn't help:

<img width="622" alt="Screen Shot 2020-12-26 at 3 41 11 PM" src="https://user-images.githubusercontent.com/15065065/103150787-ca4f7600-4790-11eb-86ee-d328ac0bce61.png">

Could you please help me to understand how Node.js works in this case? And how can I solve this issue?

**Comment by vsemozhetbyt** [comment]
It seems failed requires are not cached:

```js
try {
  require('./test.json');
} catch (err) {}

console.log(require.cache); // no json entries
```

**Comment by RaisinTen** [comment]
No errors for `v15.2.0` though.

**Comment by vsemozhetbyt** [comment]
It seems there may be some race conditions.

With Windows 10 x64 and Node.js 15.5.0:

Error:

```js
const fs = require('fs');

try { require('./test.json'); } catch (err) {}

fs.writeFileSync('test.json', '[]');
console.log(require('./test.json'));
```

OK:

```js
const fs = require('fs');

try { require('./test.json'); } catch (err) {}

fs.writeFileSync('test.json', '[]');
setTimeout(() => { console.log(require('./test.json')); }, 1000);
```

OK:

```js
const fs = require('fs');

try { require('./test.json'); } catch (err) {}

fs.writeFile('test.json', '[]', () => { console.log(require('./test.json')); });
```

Also OK (without failed try):

```js
const fs = require('fs');

fs.writeFileSync('test.json', '[]');
console.log(require('./test.json'));
```

**Comment by vsemozhetbyt** [comment]
Should this be transferred to https://github.com/nodejs/node/issues as a bug?

**Comment by vsemozhetbyt** [comment]
Reported in https://github.com/nodejs/node/issues/36638

**Comment by marsonya** [comment]
This issue was reported as a bug in nodejs/node [here](https://github.com/nodejs/node/issues/36638).
It was fixed in [this](https://github.com/nodejs/node/pull/36642) PR.
