### ISSUE TITLE
npm commands always throwing Segmentation Fault

### ISSUE THREAD

**Issue by crisefd** [nodejs/help#3145]
I work with Angular7 in Macbook Pro Retina, 13-inch, Early 2015 with Processor 2.7 GHz Intel Core i5 8 GB RAM and OSX Mojave version 10.14.5. I installed NodeJS version v11.12.0 via NVM (version 0.34.0) and 9 out 10 times I try to run a npm command it always terminates with Segmentation Fault.

For example to start and app I run 
```
npm run install
```

But the output most of the time is something like:
```
10% building 3/3 modules 0 active[1]    5581 segmentation fault  npm start
```

I need to run the command several times until it works.

**Comment by gireeshpunathil** [comment]
@crisefd - is this still an issue?

**Comment by crisefd** [comment]
No. This turned out to be a hardware issue in the computer's RAM.

**Comment by gireeshpunathil** [comment]
closing as not a node.js issue
