### ISSUE TITLE
ENAMETOOLONG for arguments

### ISSUE THREAD

**Issue by ffMathy** [nodejs/help#3146]
I get a `ENAMETOOLONG` when I try to invoke a process with very long arguments. I was under the impression that this would only happen for long filenames?

Is there anything I can do to pass long arguments to a commandline operation?

Or is there a workaround that can allow me to do it?

I'm on Windows.

**Comment by gireeshpunathil** [comment]
doesn't looks like node can do anything here - a platform limitation.
