### ISSUE TITLE
Stream question doc

### ISSUE THREAD

**Issue by nairihar** [nodejs/help#3147]
* **Node.js Version**: v12.18.1
* **OS**: MacOS
* **Scope**: runtime/doc

<img width="561" alt="Screen Shot 2020-12-27 at 9 10 02 PM" src="https://user-images.githubusercontent.com/15065065/103176018-fe599280-4887-11eb-8848-963236f514f8.png">

<img width="880" alt="Screen Shot 2020-12-27 at 9 09 58 PM" src="https://user-images.githubusercontent.com/15065065/103176019-00235600-4888-11eb-8b49-d39fc826dd52.png">

<img width="1607" alt="Screen Shot 2020-12-27 at 9 11 22 PM" src="https://user-images.githubusercontent.com/15065065/103176029-14675300-4888-11eb-9fa6-4197ac78a270.png">

Could you please help us to understand why the script doesn't work as it should work(see doc).

**Comment by RaisinTen** [comment]
What's printing `false` here?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
