### ISSUE TITLE
Error when installing node.js [windows 10]

### ISSUE THREAD

**Issue by AlyyMagdy** [nodejs/help#3148]
![lllll](https://cloud.githubusercontent.com/assets/17381972/23313476/8cb4ea34-fac6-11e6-9888-edfa0ce489f3.JPG)
I installed node-v7.6.0-x64 on windows 10 and when installation I got the following error but the installation completed.
`Warning 1909. Could Not Create Shortcut Node.js command prompt.lnk. Verify that the destination folder exists and that you can access it.`

And I am getting the following error when trying to write in cmd "npm --version"
`'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.`
`4.1.2`

* **Version**: node-v7.6.0-x64
* **Platform**: Windows 10

**Comment by kiran262** [comment]
Im trying to install node-v14.15.3-x64  on windows 10...and it gives the same error could not create shortcut node.js

**Comment by PoojaDurgad** [comment]
@kiran262 - as I said its not a problem with the node but your windows os . what you can do is try to manually add system variable to the path and see if it works. meanwhile you can refer this https://turtlesandgoliath.wordpress.com/2016/10/16/warning-1909-could-not-create-shortcut/ hope it helps

**Comment by kiran262** [comment]
@PoojaDurgad - still its not working..

**Comment by wildbook** [comment]
For anyone still experiencing this the command `icacls "C:\ProgramData\Microsoft\Windows\Start Menu\Programs" /reset` resets permissions to default, which after hours of trying to figure out what caused this solved the issue for us.

Interestingly we only ever ran into problems with node.js, while other programs seemed to handle the corrupted (?) permissions just fine, but I'm assuming that is more due to luck than anything else.

**Comment by SaiKeerthana05** [comment]
I still have the same issue

npm --version
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
8.1.2

Someone please help. 
Thanks in advance.

**Comment by Depact** [comment]
Also had this problem. Tried various solutions. Found this solution.
1. Open `C:\ProgramData\Microsoft\Windows\Start Menu` in file manager
2. Open `Propeties` of `Programs` folder inside. 
3. Set `Read-only` checkbox to false.
4. Apply
5. Run node.js installation.
Before those actions I also deleted empty `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js` folder. But I doubt it will make any change.

**Comment by kulakaka** [comment]
The issue still happening on 2022, all solution above tried and not work.  please help !

**Comment by kulakaka** [comment]
> 

This issue has been solve through this link: https://stackoverflow.com/questions/69571258/npm-does-not-work-after-node-installation-program-npm-cmd-failed-to-run

Step 1: you needed to completely remove "ComSpec" variable from your windows Environment Variable [enter image description here](https://i.stack.imgur.com/EX2G3.png) Step2: open shell console in mode admin and go to the directory of where your nodejs is located. In most case it is: c:\Program files\nodejs> Step3: install npm latest version in the nodejs file

c:\Program files\nodejs> npm install npm@latest.

That's All!
