### ISSUE TITLE
How to read memory stream of a pdf and open it

### ISSUE THREAD

**Issue by hishobhit82** [nodejs/help#315]
Node Version: 5.7.1
Platform:  64-bit (Windows)

Hi, 

I am a newbie in working with node. I have built an app in electron (which uses node internally) which communicates with a .net restful service to fetch data from db and display it on the screen. One of the data has a pdf path on the server which i read onto the server and convert it into the memory stream and send it to the client app.

The issue how can i read this memory stream in node js and open the pdf file on my windows machine through adobe acrobat reader which is installed on my windows machine? Here is a sample code which i already tried :

```
var optionsGetPDF= {
           host: 'localhost',
           port: 8080,
           path: '/GetPDFDoc?docid=' + docid,
           method: 'GET'
};

var memStream = new memorystream(null, { readable: false });
http.request(optionsGetPDF, function (res) {
     res.pipe(memStream);
     res.on('end', function () {
          alert(memStream.toString().length)
     });
}).end();
```

Any help is much appreciated.
Thanks and Regards
Shobhit

**Comment by lordKnighton** [comment]
@hishobhit82 my apologies for late responding, Im gonna close this for now. If you still need help let me know. Disclamer - I haven't done anything like this, but hopefully we can get something done.
