### ISSUE TITLE
Using getInternalBinding: A C++ File

### ISSUE THREAD

**Issue by joeymalvinni** [nodejs/help#3150]
* **Node.js Version**: 15.5
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: http/https

As mention before in a question about primordials, I am trying to use and customize the http (and https in this case) files. I already got http to work, thanks to @RaisinTen 's genius hack of defining primordials, and thought https was working also. However, for some dumb reason, I forgot to use the custom https, and was using the https module instead. So when I changed the require to my https, I got an error: InternalBinding is not defined. I searched the github and found the `loader.js` file (from which I exported internalBinding). Then, once internalBinding was defined, I got a new error: getInternalBinding is not defined. After another github search, it appears to be defined in a couple of C/C++ files, found [here](https://github.com/nodejs/node/search?q=getInternalBinding). I think it's [node_binding.cc](https://github.com/nodejs/node/blob/2310f679a1c200b8c4a35749703ce1e3429f65f5/src/node_binding.cc) that I want to export from, but as I don't know how to use addons I can't seem to figure node-gyp out, getting an error when trying to import:

```
#include "node_binding.h"
^^^^^^^^

SyntaxError: Unexpected identifier
```
Is there any way to work around this?

Help very much appreciated. Thanks

**Comment by addaleax** [comment]
> Is there any way to work around this?

`node_binding.h` is not a public API header – and even if it were, you couldn’t use it from JS files anyway, and even if you could, the source code of the native HTTP C++ code is written to be used by Node.js internals themselves, not by native addons, and attempting to use it for them would probably crash.

If you really want to do this, you’ll probably have to write a native addon based on the HTTP bindings from the Node.js source code.

**Comment by addaleax** [comment]
Oh, by the way: There has been at least one project to re-write the HTTP bindings in JS, https://github.com/creationix/http-parser-js

**Comment by joeymalvinni** [comment]
@addaleax thanks for responding! I spaghetti'd the Node.js Internals and now have them. I am trying to edit the Internals, not bindings, it's just that for some odd reason getInternalBindings isn't defined (just like primordials ugh). Is there a good example of writing a native addon in Node.js? All the ones I found were really confusing. Thanks

**Comment by joeymalvinni** [comment]
@addaleax Or alternatively, is the source code of the HTTP and HTTPS modules available (put in a separate repo and tested)? Because thats all I'm trying to do, get the source of http + https and make a request from it.

**Comment by addaleax** [comment]
> Or alternatively, is the source code of the HTTP and HTTPS modules available (put in a separate repo and tested)?

Not in a separate repository, no – there’s https://github.com/nodejs/node/blob/master/src/node_http_parser.cc, which contains all of the C++ bindings for HTTP (but not the C library behind the parser itself, llhttp, that’s a separate project). The bindings for TLS (which HTTPS uses) are a bit more involved though, with many internal dependencies.

> it's just that for some odd reason getInternalBindings isn't defined (just like primordials ugh).

That’s because Node.js core source modules, while they look like common JS modules, are not really written with the expectation that they can be run outside of Node.js core.

> Is there a good example of writing a native addon in Node.js?

I’d guess there might be decent ones out there for N-API, but that would imply writing the parser from scratch – all Node.js bindings use the V8 API directly.

**Comment by joeymalvinni** [comment]
@addaleax  that makes a lot of sense. Thanks for helping!
