### ISSUE TITLE
Are there any package managers for Node.js that installs a particular package only once?

### ISSUE THREAD

**Issue by ugultopu** [nodejs/help#3152]
Right now, when I look at `node_modules/` in a project, every dependency is installed right there. If there are multiple projects using the same packages and same versions, they are duplicated under `node_modules/` of each project. This is wasteful. Hence, I would like the package manager to install the packages in only one place in my computer and only symlink to that place from `node_modules/`. Example:

package.json:

```json
{
  "dependencies": {
    "a": "^3.4.5",
    "b": "~5.3.2"
  }
}
```

Let's say that at the time that I run the install command, `a`'s version resolved to 3.12.4 and `b`'s version is resolved to 5.3.8. The package manager will install them to a central location (let's say to `~/node_packages`) like:

    ~/node_packages/
      a@3.12.4/
      b@5.3.8/
      <other packages and other versions of a and b packages>

and in the `node_modules` folder of my project, it will just symlink to them

    node_modules/
      a -> ~/node_packages/a@3.12.4
      b -> ~/node_packages/b@5.3.8

Is such package manager exists? Or is it possible to configure any existing Node.js package managers to work like that?

**Comment by addaleax** [comment]
I think you’re basically describing `pnpm`?
