### ISSUE TITLE
Administrator mode error

### ISSUE THREAD

**Issue by m-Phoenix852** [nodejs/help#3153]
* **12.13.1**:
* **Windows**:

### What steps will reproduce the bug?

Whenever I run a node program with administrator privileges, it throws this error 
```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Windows\system32'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### How often does it reproduce? Is there a required condition?
Every time I run a program in administrator mode, it throws that error.

### What is the expected behavior?
I don't even know why that error, its most probably because the working directory should be set to `C:/Windows/System32` instead of `C:/Windows/system32` (probably case sensitive).

**Comment by m-Phoenix852** [comment]
> @m-Phoenix852 - well looks like your install path may be corrupted. what does `where node` and `where npm` gives? its a duplicate of #1618 . I hope you can refer this.

`where node` gives me 
```
C:\Program Files\nodejs\node.exe
```
and `where npm` gives me
```
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
```

**Comment by Pindicator** [comment]
I m having the same problem
