### ISSUE TITLE
Need help with packaging/building NodeJS and deploy to production

### ISSUE THREAD

**Issue by pnrkumar** [nodejs/help#3154]
* **Node.js Version**: 12.15.0
* **OS**: Windows 10 and Windows 2012
* **Scope (install, code, runtime, meta, other?) : packaging and publishing
* **Module (and version) (if relevant)**: React JS

Hi All,

I work as a sysadmin for a company. The developers in our company have developed an application using Node JS + React JS. This needs to be deployed to production in few days.

The challenge is that neither our developers nor me know how to package the node js app and create a production ready package.

I have experience only in VB, C, ASP.net and IIS. I'm a Microsoft shop guy. So need your help, Kindly let me know the steps that I need to follow to package and publish the node js app.

The developer machine is running on Windows 10 with Node JS v12.15 and the production server is Windows 2012.

I tried googling and found few articles, but I'm not able to connect the dots. 

Thanks in advance.

Kumar

**Comment by gireeshpunathil** [comment]
@pnrkumar - is this still an issue?

**Comment by pnr-kumar** [comment]
Hi @gireeshpunathil ,

I figured it out. This is a closed issue now.


Thanks and Regards,

Rajakumar
