### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by marciscool1h** [nodejs/help#3156]
* **Node.js Version**: latest
* **OS**:Windows 10 Pro
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**:

see photo for the error
![Capture](https://user-images.githubusercontent.com/40239906/103443573-e788b680-4c60-11eb-8edf-7aec5118749f.PNG)

please help

**Comment by PoojaDurgad** [comment]
@marciscool1h - can you try these steps https://kb.foxitsoftware.com/hc/en-us/articles/360040660391-Fix-Error-2502-and-2503-while-installing-or-uninstalling ?  its not a problem with the node but windows I guess. hope it helps
