### ISSUE TITLE
Unable to install NodeJS in Windows 10

### ISSUE THREAD

**Issue by lexxpalad31** [nodejs/help#3157]
![image](https://user-images.githubusercontent.com/67300913/103458596-a7026900-4d44-11eb-8452-e44b0c72500d.png)

Guys please help how ti fix this :(

**Comment by lexxpalad31** [comment]
I have trouble installing it and its been days and i cant able to fix it.

**Comment by PoojaDurgad** [comment]
@lexxpalad31 - looks like this is not a problem with the node but your windows. does other installer works properly ? and what you can do is either install the latest updated windows version and  try to set windows registry configuration or if you have older version of node , install latest stable version of node.

**Comment by lexxpalad31** [comment]
@PoojaDurgad You're right the problem is my windows OS. I resolved it by resetting my windows. Thanks.

**Comment by PoojaDurgad** [comment]
closing as resolved.
