### ISSUE TITLE
Is there a way to identify Persistent<Function> uniqueness?

### ISSUE THREAD

**Issue by kuzenko** [nodejs/help#3158]
I am storing js callbacks in vector:
```
std::vector<std::unique_ptr<Persistent<Function>>> callbacks;
```
Everything is working fine. The problem is that I do not want to store duplicated callbacks because I do not want to notify the same callback twice. I have to compare them somehow. Here is my full function but that does not work:

```
void ProcessCallback(const FunctionCallbackInfo<Value>& args)
{
    std::string returnInfo;

    Isolate* isolate = args.GetIsolate();
    Local<Function> notifyFunction = Local<Function>::Cast(args[0]);
    
    auto predicate = [&](const std::unique_ptr<Persistent<Function>>& c)
    {
        return c->Get(isolate)->StrictEquals(notifyFunction);
    };

    auto it = std::find_if(callbacks.begin(), callbacks.end(), predicate);
    if (it == callbacks.end())
    {
        returnInfo = "Did not find callback. Adding..." + std::to_string(callbacks.size());

        auto persistentCallback = std::make_unique<Persistent<Function>>(isolate, notifyFunction);
        callbacks.emplace_back(std::move(persistentCallback));
    }
    else
    {
        returnInfo = "Callback already exist in a list.\n";
    }
    
    args.GetReturnValue().Set(String::NewFromUtf8(isolate, returnInfo.c_str()).ToLocalChecked());
}
```

In js:
```
function callback(msg) {
    console.log(msg);
}

let addon = require('./build/Release/addon');

console.log(addon.on(callback));
console.log(addon.on(callback));
```

Is there something that I can rely on to uniquely identify function that is passed from js? Thanks.

**Comment by addaleax** [comment]
> Is there something that I can rely on to uniquely identify function that is passed from js?

No. For equality comparisons, you’ll need to use `persistent1.Get(isolate) == persistent2.Get(isolate)` (or `value->StrictEquals()`). If you want to use a hash-based data structure, you can also use `obj->GetIdentityHash()`, but that’s not guaranteed to be unique, so you’ll still need to implement an equality operator.

**Comment by kuzenko** [comment]
Thank you for your response. Will try.

**Comment by kuzenko** [comment]
I am concerning what should I do with isolation? They are different for these two objects. (One is local and one is Persistent)

**Comment by kuzenko** [comment]
I added such equality operator
```
template <class T, class M> class Persistent : public v8::PersistentBase<T> {
 public:
 bool operator==(const Persistent& persistent) const
  {
      v8::Isolate* isolate = v8::Isolate::GetCurrent();
      return this->Get(isolate) == persistent.Get(isolate);
  }
};
```

And replaced Local with Persistent to be able to call it but that does not work:
```
Persistent<Function> callback(isolate, Local<Function>::Cast(args[0]));
```
Do I miss something?

**Comment by addaleax** [comment]
> I am concerning what should I do with isolation? 

I don’t think this is too relevant here, since you’re most likely using only a single `Isolate`.

> They are different for these two objects. (One is local and one is Persistent)

You could still use something like `return c->Get(isolate) == callback;` in your `predicate` function.

> I added such equality operator

I don’t think using a subclass would be what you want here (nor would be using `v8::Isolate::GetCurrent()`.

**Comment by kuzenko** [comment]
> I don’t think using a subclass would be what you want here (nor would be using v8::Isolate::GetCurrent().
Sure I just tried to make it work somehow and test it.

> You could still use something like return c->Get(isolate) == callback; in your predicate function.
I already tried that but that does not work for me. Please advice how can I make it work. Thanks.

**Comment by addaleax** [comment]
> > You could still use something like return c->Get(isolate) == callback; in your predicate function.
> 
> I already tried that but that does not work for me. Please advice how can I make it work. Thanks.

Well, how did it fail?

**Comment by addaleax** [comment]
Also, could you see if `c->Get(isolate)->StrictEquals(callback)` gives a different result?

**Comment by kuzenko** [comment]
I updated the code that I am using right now.

> Well, how did it fail?

It gives such result:
```
Did not find callback. Adding...0
Did not find callback. Adding...1
```
I expect that the second log will be "Callback already exist in a list."

> Also, could you see if c->Get(isolate)->StrictEquals(callback) gives a different result?
Will try that.

**Comment by kuzenko** [comment]
It works for me.
