### ISSUE TITLE
Need Suggestion

### ISSUE THREAD

**Issue by nazirahmadnoori** [nodejs/help#3159]
I am working on a SaaS Application tracking system for Learning purposes. using ExpressJS and MongoDB.

I have a Schema for the applicant, where the applicant can build their profile and resume as below Schema.
`const mongoose = require('mongoose');

const CandidateprofileSchema = new mongoose.Schema({
    candidate: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'candidate'
    },
    address: {
        type: String,
       
    },
    summery: {
        type: String,
       
    },
    linkend: {
        type: String,
       
    },
    skills: {
        type: [String]
    },
    experience: [
        {
            title: {
                type: String,
                required: true
            },
            company: {
                type: String,
                required: true
            },
            location: {
                type: String,
                required: true
            },
            from: {
                type: Date,
                required: true
            },
            to: {
                type: Date,
                
            },
            current: {
                type: Boolean
            },
            summery: {
                type: String,
                required: true
            }

        }
    ],
    education: [
        {
            title: {
                type: String,
                required: true
            },
            school: {
                type: String,
                required: true
            },
            location: {
                type: String,
                required: true
            },
            from: {
                type: Date,
                required: true
            },
            to: {
                type: Date,
                
            },
            current: {
                type: Boolean
            },
            type: {
                type: String,
                required: true
            }

        }
    ],
    training: [
        {
            title: {
                type: String,
                required: true
            },
            school: {
                type: String,
                required: true
            },
            location: {
                type: String,
                required: true
            },
            from: {
                type: Date,
                required: true
            },
            to: {
                type: Date,
                
            },
            details: {
                type: Boolean
            },
            type: {
                type: String,
                required: true
            }

        }
    ],
    certificate: [
        {
            title: {
                type: String,
                required: true
            },
            source: {
                type: String,
                required: true
            },
            location: {
                type: String,
                required: true
            },
            date: {
                type: Date,
                required: true
            },
            details: {
                type: String
            },
            certified: {
                type: Boolean
               
            }

        }
    ],
    refrence: [
        {
            name: {
                type: String,
                required: true
            },
            email: {
                type: String,
                required: true
            },
            phone: {
                type: String,
                required: true
            },
            company: {
                type: String,
                required: true
            },
            title: {
                type: String,
                required: true
                
            },
            location: {
                type: String,
                required: true
            },
            type: {
                type: String,
                required: true
            }

        }
    ],
    data: {
        type:Date,
        default:Date.now
    }

}); 

module.exports = Candidateprofile = mongoose.model('Candidateprofile', CandidateprofileSchema);`

Now I want to that when an applicant wants to apply for a specific job, I want the same user-filled profile should be copied to another MongoDB documents, where the user should not be able to modify that after he applied for the job. below is the return JSON for the applicant profile
`
{
"skills": [],
"_id": "5ff1f0aba9702d0baca6d03d",
"candidate": {
    "_id": "5ff09fc72cb32297d42b390c",
    "name": "nazir",
    "lastname": "noori",
    "email": "nazir@yahoo.com",
    "mobile": 7984545
},
"address": "2nd street",
"summery": "Hello World, I am developer",
"linkend": "https://linkend.com/nazir",
"experience": [
    {
        "_id": "5ff2add0628072523415f5e8",
        "title": "Admin Assistant",
        "company": "ABC",
        "location": "abc, xyz",
        "from": "2012-01-31T19:30:00.000Z",
        "to": "2016-01-01T19:30:00.000Z",
        "summery": "I have been working as an office Assistant"
    }
],
"education": [
    {
        "_id": "5ff2e1feeb5e17194cb2210c",
        "title": "MBA",
        "school": "zyx",
        "location": "XYZ, Xyz",
        "from": "2016-10-11T19:30:00.000Z",
        "to": "2019-01-04T19:30:00.000Z",
        "type": "degree"
    }
],
"training": [
    {
        "_id": "5ff2e3e9374cf034fc38d97e",
        "title": "MBA",
        "school": "XYZ Uni",
        "location": "xyz, xyz",
        "from": "2016-10-11T19:30:00.000Z",
        "to": "2019-01-04T19:30:00.000Z",
        "type": "degree"
    }
],
"certificate": [
    {
        "_id": "5ff2e495d984588178335c24",
        "title": "MBA",
        "source": "uni",
        "location": "xyz, abc",
        "date": "2016-10-11T19:30:00.000Z",
        "details": "degree"
    }
],
"refrence": [
    {
        "_id": "5ff2e62dd984588178335c26",
        "name": "Ahmad",
        "email": "me@me.com",
        "phone": "07888877",
        "company": "Abc",
        "title": "CEO",
        "location": "delhi",
        "type": "academic"
    }
],
"data": "2021-01-03T16:28:27.099Z",
"__v": 7
}`
Could you kindly please suggest to me the best method to solve this issue and send a copy of applicant profile for the job, where the employer can review it and still the applicant has access to his/her profile

**Comment by hostmepanda** [comment]
Seems like your questions can be answered in the mongoose repo, peek at https://github.com/Automattic/mongoose. BC it's not being connected straightly with nodejs. 

Maybe a better idea is not to duplicate the Document, but make it readable for the applicant right after the resume was sent to the employer. I would suggest using a flag one/several to indicate that resume can be updated by the applicant or it can't be updated anymore, with that the Document can be still shown to the candidate in a read-only mode.

The start point can be the following: 
The flag indicates that the resume can be updated by the applicant. 
It is illustrated below. flag `canBeUpdatedByCandidate` is set to `true` by default which means a candidate can update the resume before sending it to the reviewer. 
When a candidate puts new data to the resume, before updating the Mongoose Document you can check whether the Document has `canBeUpdatedByCandidate` set to `true` and reject it if it's not. 
Or you can put condition in mongoose query `findOneAndUpdate({ canBeUpdatedByCandidate: true , ...updateData })` and check how many documents has been updated, if 0 then throw the error.
When resume has been sent to reviewer `canBeUpdatedByCandidate` is set to false and any further updates should be rejected before performing `findOneAndUpdate()` or alike mongoose methods.
```
const CandidateprofileSchema = new mongoose.Schema({
 canBeUpdatedByCandidate: { type: Boolean, default: true },
 candidate: {...},
 ...,
});
```

**Comment by nazirahmadnoori** [comment]
> Seems like your questions can be answered in the mongoose repo, peek at https://github.com/Automattic/mongoose. BC it's not being connected straightly with nodejs.
> 
> Maybe a better idea is not to duplicate the Document, but make it readable for the applicant right after the resume was sent to the employer. I would suggest using a flag one/several to indicate that resume can be updated by the applicant or it can't be updated anymore, with that the Document can be still shown to the candidate in a read-only mode.
> 
> The start point can be the following:
> The flag indicates that the resume can be updated by the applicant.
> It is illustrated below. flag `canBeUpdatedByCandidate` is set to `true` by default which means a candidate can update the resume before sending it to the reviewer.
> When a candidate puts new data to the resume, before updating the Mongoose Document you can check whether the Document has `canBeUpdatedByCandidate` set to `true` and reject it if it's not.
> Or you can put condition in mongoose query `findOneAndUpdate({ canBeUpdatedByCandidate: true , ...updateData })` and check how many documents has been updated, if 0 then throw the error.
> When resume has been sent to reviewer `canBeUpdatedByCandidate` is set to false and any further updates should be rejected before performing `findOneAndUpdate()` or alike mongoose methods.
> 
> ```
> const CandidateprofileSchema = new mongoose.Schema({
>  canBeUpdatedByCandidate: { type: Boolean, default: true },
>  candidate: {...},
>  ...,
> });
> ```

Thank you, I have found other option, I have created another Schema, once the candidate creates a profile,  while the candidate applies for a position I render the user profile on the application form after the user confirmation or update, I will save the application profile in a document with the details of the job where the reviewer can access it.

Please suggest to me if it will work and it may not make an issue in the future for me. as of my knowledge, it will create more dummy data on the database, but I will clean the database after the job get close
