### ISSUE TITLE
How can we prevent wrong execution of Node.js files on Windows?

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/help#316]
At Nodeschool we sometimes get this sort of issue: https://github.com/nodeschool/discussions/issues/1894

its pretty disturbing to see it as someone who knows about node but it seems like some basic communication improvement on the Node.js website is needed. Something like: double-click on javascript files will start them in a browser environment.

Any Idea how to better prevent this from happening?

cc. @hackygolucky

**Comment by oliversalzburg** [comment]
The NodeJS installer could offer to associate `.js` files with `node.exe`. If that would have a beneficial outcome is debatable though.

I doubt that a note on the website or the installer would reach the people who run into this issue.

**Comment by vsemozhetbyt** [comment]
See also https://github.com/nodejs/node/issues/6273
