### ISSUE TITLE
how nodejs handles the http requests that are triggered from nodejs?

### ISSUE THREAD

**Issue by Divine1** [nodejs/help#3160]
Please consider below scenarios
**Scenario 1** http request triggered from a web browser (chrome or firefox) to a nodejs server
**Scenario 2** http request triggered from a nodejs server to another external server (like google api's or a java based system or .net based system or nodejs based system)

**in case of scenario 1** 
 i'm aware that http requests sent by browser is received by the system in which the corresponding nodejs server is running. Then the system creates an event about this request in the socket in which nodejs server is listening. By making use of `epoll api`, nodejs fetches the http request and does further processing _(please correct me if you think i have misunderstood some important details here)_

**in case of scenario2** _( this is my question. how does nodejs handles this scenario?)_
when nodejs server triggers http request to another external server, how is the request <-> response handled ?

**Here is my vague understanding of this topic** 
Lets assume, i'm using [axios](https://www.npmjs.com/package/axios) library to trigger http request from nodejs server to external server, `axios.get(url).then(...)`  ....
     - Will libuv get hold of a  random port, then trigger the http request via this port and still use `epoll api`?
     - or does libuv pick one of the threads from thread_pools available in libuv, then get hold of a random port, and do the processing?
     - does `axios` library internally invoke `libuv api`?

Also, does `nodejs` handle all the file handling operations asynchronously by picking threads from `libuv threadpool`? does it also mean that all the i/o operations in nodejs are handled asynchronously by picking threads from `libuv threadpool` but not `epoll api`? is `epoll api` applicable only for network calls?

Please clarify.

**Comment by addaleax** [comment]
> - Will libuv get hold of a random port, then trigger the http request via this port and still use `epoll api`?

It’s the kernel that implicitly provides a random port (not fully random, though – usually in the range 49152–65535, to avoid conflicts with actual servers), not libuv.

> - does `axios` library internally invoke `libuv api`?

It uses the built-in `http` module, which in turn uses the `net.Socket` API (or the libuv API directly) for communication. Once a socket is established, there’s no difference on the I/O level between a server socket and a client socket.

> Also, does `nodejs` handle all the file handling operations asynchronously by picking threads from `libuv threadpool`?

Yes.

> is `epoll api` applicable only for network calls?

It is usable for most libuv features, including network calls, and most non-filesystem I/O.

**Comment by Divine1** [comment]
@addaleax thank you for the clear responses anna 

**i have one additional doubt**
`
It uses the built-in http module, which in turn uses the net.Socket API (or the libuv API directly) for communication. Once a socket is established, there’s no difference on the I/O level between a server socket and a client socket.`

does `net.Socket API` invoke `epoll api` to handle the `request-response` asynchronously ? how does this flow work? 

**does this flow go like ...** 

->> nodejs`net.Socket API` -> kernel (select port) -> networkInterface -> send the request
->> networkInterface receives the response -> forwards the response to the logical port-> kernel forwards it to the callback registered by nodejs

does epoll api come into picture in this flow? 
does epoll api come into picture in the kernel part ...
 - before sending request via networkInterface and then after receiving response from networkInterface ?
