### ISSUE TITLE
Profiling with source maps

### ISSUE THREAD

**Issue by MatteoGioioso** [nodejs/help#3164]
* **Node.js Version**: > 10
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: runtime, debugging, v8
* **Module (and version) (if relevant)**:

Hello, I was wondering if profiling supports source maps as well.
If for example I have a transpiled file with babel/webpack that I want to profile

```
node --prof index.js
```

Thanks

**Comment by MatteoGioioso** [comment]
Hello, any answer?

**Comment by mhdawson** [comment]
@bcoe can correct me if I'm wrong since he did some work on this front with respect to code coverage but I think the current answer is no.

**Comment by bcoe** [comment]
@mhdawson I don't believe we'd be remapping lines in profiles right now. But, we have all the machinery necessary to do so in the codebase now -- this sounds like it would be a great feature request.

**Comment by mbrevda** [comment]
is there a feature request for this? If not, where would be the appropriate place to open one?

**Comment by bcoe** [comment]
> is there a feature request for this? If not, where would be the appropriate place to open one?

@mbrevda I would open a feature request on https://github.com/nodejs/node

**Comment by mbrevda** [comment]
thanks! https://github.com/nodejs/node/issues/50894
