### ISSUE TITLE
Parallel Execution of Multiple Functions in a Lambda using Node.js

### ISSUE THREAD

**Issue by ThirumalaV** [nodejs/help#3165]
Can we execute multiple functions parallelly/asynchronously in a lambda with synchronous flow using node.js. We tried using run-parallel, async.parallel, async/await, and promise.all. But, the functions are executing synchronously one after another rather than the required asynchronous process. Can anyone suggest best approach?

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
