### ISSUE TITLE
deprecated Dependences in package.json

### ISSUE THREAD

**Issue by YallaDealz** [nodejs/help#3166]
this my package.json file in the current production project, so i want to know which dependency  should be removed from list as a deprecated version 

my current server nodejs version : 15.5.1  with expressjs 

{
  "name": "Backend_API",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "pm2-runtime start ecosystem.config.js --env production",
    "nodemon": "nodemon ./bin/Backend_API",
    "debug": "nodemon --inspect ./bin/Backend_API",
    "test": "jest tests/integration --watch  --verbose",
    "dev": "SET NODE_ENV=development && nodemon ./bin/Backend_API"
  },
  "dependencies": {
    "@airbrake/node": "^1.2.0",
    "@hapi/joi": "^17.1.0",
    "@types/babel-types": "^7.0.4",
    "@types/babylon": "^6.16.4",
    "@types/dotenv": "^8.0.0",
    "@types/node": "^14.0.0",
    "@vitalets/google-translate-api": "^4.0.0",
    "accesscontrol": "^2.2.1",
    "adm-zip": "^0.5.0",
    "aws-sdk": "^2.664.0",
    "axios": "^0.21.0",
    "bcryptjs": "^2.4.3",
    "bluebird": "^3.5.3",
    "body-parser": "^1.19.0",
    "chai": "^4.2.0",
    "chai-sorted": "^0.2.0",
    "cloudinary": "^1.19.0",
    "config": "^3.2.5",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.5",
    "cron": "^1.6.0",
    "crypto": "^1.0.1",
    "crypto-js": "^4.0.0",
    "debug": "^4.1.1",
    "decompress": "^4.2.0",
    "dotenv": "^8.2.0",
    "elasticsearch": "^16.0.0",
    "eslint": "^7.0.0",
    "express": "^4.17.1",
    "express-async-errors": "^3.1.1",
    "express-handlebars": "^5.0.0",
    "express-rate-limit": "^5.0.0",
    "express-session": "^1.17.0",
    "extract-zip": "^2.0.0",
    "fawn": "^2.1.5",
    "fs-extra": "^9.0.0",
    "google-translate-api": "^2.0.0",
    "http-errors": "~1.8.0",
    "jade": "~1.11.0",
    "joi-objectid": "^3.0.1",
    "jsonwebtoken": "^8.5.1",
    "languagedetect": "^2.0.0",
    "lodash": "^4.17.15",
    "lodash.omit": "^4.5.0",
    "mime": "^2.4.4",
    "mime-types": "^2.1.22",
    "minio": "^7.0.5",
    "mocha": "^8.0.0",
    "moment": "^2.24.0",
    "mongodb": "^3.1.13",
    "mongoose": "^5.7.13",
    "mongoose-shortid-nodeps": "^0.6.5",
    "morgan": "^1.9.1",
    "multer": "^1.4.2",
    "multer-s3": "^2.9.0",
    "node-cron": "^2.0.3",
    "nodemailer": "^6.3.1",
    "passport": "^0.4.1",
    "passport-facebook": "^3.0.0",
    "passport-google-oauth": "^2.0.0",
    "qrcode": "^1.4.4",
    "queue-fifo": "^0.2.5",
    "randomstring": "^1.1.5",
    "redis": "^3.0.2",
    "request": "^2.88.0",
    "request-promise": "^4.2.2",
    "rimraf": "^3.0.2",
    "sha256": "^0.2.0",
    "sib-api-v3-sdk": "^8.0.0",
    "translatte": "^3.0.0",
    "underscore": "^1.9.2",
    "uuidv4": "^6.0.7",
    "validation-helpers": "^1.1.1",
    "validator": "^13.0.0",
    "winston": "^3.2.1",
    "winston-mongodb": "^5.0.1",
    "xlsx": "^0.16.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-config-prettier": "^7.0.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-react": "^7.17.0",
    "jest": "^26.0.0",
    "nodemon": "^2.0.2",
    "prettier": "^2.2.1",
    "supertest": "^6.0.1"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "jest": {
    "verbose": true,
    "testURL": "http://localhost/"
  }
}

**Comment by Lxxyx** [comment]
Try this script

```
jq -r '.dependencies,.devDependencies|keys[]' package.json | while read line; do \
  printf "$line: "
  [ "$(npm show "$line" | grep -ic 'DEPRECATED')" != "0" ] && \
  printf "\e[1;31m""DEPRECATED\n""\e[0m" || \
  printf "\e[1;32m""not deprecated.\n""\e[0m"
done
```

Refs: https://github.com/npm/npm/issues/15536#issuecomment-392657820

**Comment by droobertzka** [comment]
Sorry to Frankenstein this thread, but I wanted to:

1. Post a tip for people who don't want to install `jq` because Node already handles JSON quite well:
```
 node -e "Object.entries(require('./package-lock.json').packages).filter(([_,x])=>x.deprecated).forEach(([pkg,{deprecated:msg}])=>{console.log(pkg + ': ' + msg + '\n')})"
 ```
 
 2. Ask if there is a better way to get a list of deprecations via the `npm` cli yet, as well as what the reasoning behind only showing these on clean installs?

I'd always assumed deprecations were logged the same in both cases. It'd be more transparent and prudent to be told about them more often than less (even if it's an annoying amount). People can always use `--log-level=error` to suppress the warnings if they'd like.
