### ISSUE TITLE
Can't install......

### ISSUE THREAD

**Issue by ryansaginaw** [nodejs/help#3169]
I install node.js and it says I need windows 8.1 or higher. I have windows 10, and have went through all the updates. 
I did get an older version of node to install through a command prompt, but I can't find a text editor to actually install npm packages.

PLEASE HELP!!

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by PoojaDurgad** [comment]
@ryansaginaw - which version of node you are using? you can install node on windows by visiting node official site https://nodejs.org/en/download/. Click the Windows Installer button to download the latest stable version which automatically installs the `npm` . later check the version of `node` and `npm`

**Comment by moatefdev** [comment]
@ryansaginaw
Hi. Please, I would like to ask, Do Nodejs and all packages built on it, support or work very well on the new Apple M1 chip for MACs (like MacBook Pro M1 or Mac Mini M1)?

**Comment by PaulaFernandezTeves** [comment]
Hi! I am trying to install node.js but when it is about to finish installing I get a warning saying that it could not finish installing because there is a problem with the package. I did it several times but it still does not allow me to install it. Help me please.

**Comment by PoojaDurgad** [comment]
@PaulaFernandezTeves - I guess you can refer this https://github.com/nodejs/help/issues/264 hope it helps

**Comment by RedYetiDev** [comment]
*(This issue seems resolved)*
