### ISSUE TITLE
Node.js giving less performance than Java EE on Tomcat Server

### ISSUE THREAD

**Issue by nischay13may** [nodejs/help#317]
I made a  single player game of Snakes and Ladders using AngularJS and Java(Spring and Hibernate). Then I read some blogs and forums about game development, and decided to switch to Node.JS. But after developing the backend on Node.JS, I decided to do some Performance Testing using JMeter.
I have used Threads(200), Ramp Up Time(1),, Loop Count(2)
I was amused after looking at the results.
The throughput of the Java based games was 27.1/sec and that of Node.JS was 8.1/sec.
This was after using compression package on Node.JS.

Is there any solution to increase Node.JS performance?

**Comment by bnoordhuis** [comment]
Are you using the cluster module in your application?  If not, you should use the cluster module in your application. :-)

**Comment by nischay13may** [comment]
System Info:
4GB RAM
Intel Core i5 2.00 GHz Processor
Windows 7 OS

Performance of both Tomcat and Node server:
![tomcatserver](https://cloud.githubusercontent.com/assets/22675218/19186577/8fe4e37a-8ca4-11e6-907b-39ec5d5e8fa3.PNG)
![nodeserver](https://cloud.githubusercontent.com/assets/22675218/19186582/94f1ec1e-8ca4-11e6-988a-46bde9cd2b51.PNG)

Note: I am not using cluster module as of now

**Comment by bnoordhuis** [comment]
You should - without it, node.js uses only one core while tomcat will use all cores.

I should mention that Windows is not the best platform for cluster.  Because of Windows quirks, round-robin scheduling doesn't work well (and is disabled by default), so you might get unevenly distributed loads.

**Comment by nischay13may** [comment]
Thanks. Used Cluster but still same result :( Tomcat is still giving better result than NodeJS

Note: Still using Windows platform.

**Comment by nischay13may** [comment]
Will cluster not at all work in Windows, or it should show "some" increased performance?

**Comment by lordKnighton** [comment]
feel free to reopen & seek further help.
