### ISSUE TITLE
error.status returns 1 when command is not found (on windows 10)

### ISSUE THREAD

**Issue by CelDaemon** [nodejs/help#3170]
* **Version: v15.5.0**:
* **Platform: Microsoft Windows NT 10.0.19042.0 x64**:

### What steps will reproduce the bug?

```js
const child_process = require("child_process");

try{
    child_process.execSync("nonexistantcommand", {stdio: 'ignore'})
} catch (error) {
    console.log(error.status);
}
```

### How often does it reproduce? Is there a required condition?

Always happens on windows 10

### What is the expected behavior?

Should print out: "127"

### What do you see instead?

Prints out: "1"

### Additional information

cmd normally outputs error code 9009 when command is not found, but because node is made to be cross-platform, should be the same as on linux (127)

**Comment by gireeshpunathil** [comment]
there is a numbering convention that explains the ChildProcess error code in windows and UNIX, but I can't recollect it. @nodejs/platform-windows

**Comment by VoidStoneDev** [comment]
@gireeshpunathil This is only the case for error codes for nodejs itself, not for programs executed with child_process
