### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by WHOAMI-DISC** [nodejs/help#3172]
* **Node.js Version**: 14.15.4
* **OS**: Windows 7 
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

How do I install on windows 7

**Comment by PoojaDurgad** [comment]
@WHOAMI-DISC - Node v14.0.0 and above program can be run on windows 8.1 and above. for more detail you can refer this https://github.com/nodejs/node/pull/31954

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
