### ISSUE TITLE
Vnode.exe keeps popping up whenever i execute node commands (node -v, npm -v...) in terminal, and the commands generate no output, not even an error output.

### ISSUE THREAD

**Issue by jerry-ebikari** [nodejs/help#3174]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by PoojaDurgad** [comment]
@lekarane - which version of node you are using?  looks like you have not installed node properly. node.exe is node executable file where you need to run node.js applications on os.

**Comment by lekarane** [comment]
> @lekarane - which version of node you are using? looks like you have not installed node properly. node.exe is node executable file where you need to run node.js applications on os.

Version 14.15.4 LTS, and I have tried uninstalling and reinstalling. Can you walk me through the correct installation process?

**Comment by PoojaDurgad** [comment]
@lekarane - To install node on windows, In a web browser, navigate to https://nodejs.org/en/download/. Click the `Windows Installer` button to download the latest default version. The Node.js installer includes the NPM package manager. 
- Once the installer finishes downloading, launch it. open the downloaded file and click it. 
- `Run` the software and set the node setup wizard. review the license agreement and either you can leave the `default 
   location` or select the location to install
-  later you can either select the components to include or remove from the installation(in case-of specific need)
- Finally, click the `Install` button to run the installer. When it finishes, click `Finish`.
To verify the installation, open the command prompt and type `node -v` and `npm -v`

**Comment by lekarane** [comment]
@PoojaDurgad I have just done that and the commands worked the first time but after a reboot, it has gone back to the previous behaviour.

**Comment by zulqifelkhan** [comment]
1.Uninstall Node.js:
2.Reinstall N
3.Verify PATH:ode.js:
4.Check for vnode.exe:
5.Clear npm Cache:
6.Test Node.js:

For more details, visit: `<a href="https://apkwink.net/">Fix vnode.exe Issue with Node.js</a>`.
