### ISSUE TITLE
Serial port looping problem

### ISSUE THREAD

**Issue by JanNaklicki** [nodejs/help#3175]
Hi, I'm trying to make a simple node website that reads a value from the serial port. But I run into a weird problem. When I make one post request I want to just read the value from serial port once but instead, it starts some kind of loop and reads without stopping.  I have an Arduino sending value from the potentiometer on the serial port.

My post:

```js

app.post('/serial',function(req,res){
    const parser = new Readline();
    serialport.pipe(parser);
    parser.on('data', console.log);
    console.log('works!');
    
    res.status(200).end();
})



```

example output:

PS G:\......\WouldTheyRather> node .\server.js
```
8080 is the magic port
works!
54
54
54
54
54
54
54
52
52
52
52
51
51
51

````

**Comment by gireeshpunathil** [comment]
@JanNaklicki - is this still an issue? What is the terminator for the stream data? does the stream source send the EOF character, or something similar? Your code looks clean and good, but not sure how the stream reader determine the serial port has no more data in this iteration, and it should close the stream?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
