### ISSUE TITLE
Apple M1 with older version of Node.js support

### ISSUE THREAD

**Issue by ponichWebKnight** [nodejs/help#3176]
* **Node.js Version**: 8.16.1
* **OS**: MacOS Big Sur
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Hello there! Is it possible to work with older version of Node.js on new brand macbook pro on Apple Silicon m1 CPU?
Looking to buy this laptop, but not sure, if it is possible to work on with older version.

**Comment by devsnek** [comment]
Older versions are not supported. Aside from the effort of recompiling every old version of node, we would need to ensure support for every old dependency of every old version of node, which is an impossible undertaking.

**Comment by ponichWebKnight** [comment]
@devsnek Thanks a lot for the response! That is a sad thing. Need to look for another laptop model then.

**Comment by devsnek** [comment]
@ponichWebKnight well the m1's rosetta system can run older x64 builds of node.

**Comment by ponichWebKnight** [comment]
@devsnek So it is possible to run version 8.16.1 via Rosetta 2 backward compatibility?
That is everything i need to know. Thanks again!

**Comment by Jarzka** [comment]
Why was this issue closed as the question remains open?

**Comment by ponichWebKnight** [comment]
@Jarzka Question was answered. You can run older versions of Node.Js via Rosetta 2. Sorry, if my last message led you to misunderstanding.

**Comment by Jarzka** [comment]
Ah yes, the question was answered, I didn't notice it. Sorry, my bad. 🙈
