### ISSUE TITLE
Failed to upgrade to NPM 7.4.2

### ISSUE THREAD

**Issue by markddrake** [nodejs/help#3179]
## Environment
C:\Development\YADAMU>docker info
Client:
 Debug Mode: false

Server:
 Containers: 14
  Running: 14
  Paused: 0
  Stopped: 0
 Images: 28
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-041900-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.83GiB
 Name: yadamu-db2
 ID: Z6TT:RSUR:5RD6:MWKY:ZZWF:KCAA:XNET:CRAA:XW4M:ZOUR:N75G:B2XN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

use image node:latest

## Expected Behavior

Should be able to upgrade or downgrade NPM....

## Current Behavior

Use the following script 
```
docker rmi -f yadamu/docker:test
set DOCKER_BUILDKIT=1
docker info
docker build -t  yadamu/docker:test . -fdockerfile --no-cache --progress=plain
```
and the following dockerfile 
```
FROM node:latest
RUN node --version \
 && npm --version  \
 && npm install -g npm@7.4.2 \ 
 && npm --version
```

I get the following output 

Node Version:
```
nodejs/docker-node#5 0.436 v15.5.1
```

NPM Version (before upgrade attempt)
```
nodejs/docker-node#5 0.624 7.3.0
```

NPM Upgrade output
```
nodejs/docker-node#5 5.625 npm notice
nodejs/docker-node#5 5.625 npm notice New minor version of npm available! 7.3.0 -> 7.4.2
nodejs/docker-node#5 5.625 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.4.2>
nodejs/docker-node#5 5.626 npm notice Run `npm install -g npm@7.4.2` to update!
nodejs/docker-node#5 5.626 npm notice
nodejs/docker-node#5 5.631 npm ERR! code EISDIR
nodejs/docker-node#5 5.631 npm ERR! syscall copyfile
nodejs/docker-node#5 5.631 npm ERR! path /usr/local/lib/node_modules/npm
nodejs/docker-node#5 5.632 npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI
nodejs/docker-node#5 5.632 npm ERR! errno -21
nodejs/docker-node#5 5.638 npm ERR! EISDIR: illegal operation on a directory, copyfile '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'
nodejs/docker-node#5 5.666
nodejs/docker-node#5 5.666 npm ERR! A complete log of this run can be found in:
nodejs/docker-node#5 5.666 npm ERR!     /root/.npm/_logs/2021-01-17T23_52_15_510Z-debug.log
```

**Comment by gireeshpunathil** [comment]
comparing the failing sequence with that of https://github.com/nodejs/help/issues/3036

this one:
```
nodejs/docker-node#5 5.631 npm ERR! syscall copyfile
nodejs/docker-node#5 5.631 npm ERR! path /usr/local/lib/node_modules/npm
nodejs/docker-node#5 5.632 npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI
nodejs/docker-node#5 5.632 npm ERR! errno -21
```


the linked issue:
```
syscall: 'rename',
  code: 'EXDEV',
  path: '/usr/local/lib/node_modules/npm',
  dest: '/usr/local/lib/node_modules/.npm-i9nnxROI'
```

looks like similar to me. As the linked issue has a recreate outside of node, it is potentially a docker issue, or the base image that the docker uses?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
