### ISSUE TITLE
nodejs cannot find module on a mac!!!

### ISSUE THREAD

**Issue by ahreg2002** [nodejs/help#318]
here is the error code i am getting when i try to run node.js on my mac 
module.js:457
    throw err;
    ^

Error: Cannot find module '/Users/ahmedsalem/global.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by danielkhan** [comment]
Please post the piece of code that contains the `require` calls.

**Comment by ahreg2002** [comment]
i am new to node js. what require code you mean?

**Comment by vsemozhetbyt** [comment]
When does this error appear exactly? Do you try to execute your own script by node? What is the code of this script?

**Comment by ahreg2002** [comment]
yes i am trying to execute my script. here is the piece of code : 
console.log("hello world");

**Comment by ahreg2002** [comment]
in terminal i am writing node global.js then the error apears

**Comment by vsemozhetbyt** [comment]
Your script named `global.js` and it contains only one line `console.log("hello world");`, right?

Does your script exist in the same folder as the current folder of the shell in the moment of `node global.js` call?

**Comment by ahreg2002** [comment]
yes it contains only this line of code
no its on the desktop

**Comment by vsemozhetbyt** [comment]
I am not a Mac user, so may be someone will correct me. If I get it right, you can these options of script call:

1. `node global.js` if `global.js` is in the current shell folder.
2. 'node /full/path/to/global.js`

**Comment by ahreg2002** [comment]
lovely, that worked for me. thank you very much for your help
