### ISSUE TITLE
REPL hijacks node js commands

### ISSUE THREAD

**Issue by jerry-ebikari** [nodejs/help#3182]
* **Node.js Version**: 15.6.0
* **OS**: Windows 10 64-bit
* **Scope (install, code, runtime, meta, other?)**: Install
![vnode](https://user-images.githubusercontent.com/71222695/104908238-79453300-5986-11eb-9654-bb27c2d7225f.PNG)
 

The REPL window opens every time I enter a node command ("node -v", "npm -v", etc) in terminal, the commands do not execute. Commands work after a fresh install but stop after a reboot.

**Comment by gireeshpunathil** [comment]
@jerry-ebikari - is this outstanding? the vital part of your attempt is masked off in the screen shot. That is, the command that you issued. If plain `node` was issued without an additional flag, the REPL prompt appearing is expected, and working as designed. On the other hand if there are flags supplied, it should honor that, as opposed to open up REPL. Can you pls confirm?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
