### ISSUE TITLE
Node version seems to be upgrading on it's own

### ISSUE THREAD

**Issue by khurshidso** [nodejs/help#3183]
* **14.15.4/15.5**:
* **Windows**:
* **install**:
* ****:

I am noticing that node seems to be upgrading to version 15.5 on it's own. I manually downgraded my node version to 14.15.4, but somehow it keeps going back to 15.5 after a day or so. Does anyone know why this issue occurs? I have certain packages in my project that do not seem to compile under the 15.5 version and only seem to work when I downgrade, but then the next day I am forced to downgrade as the node version seems to auto upgrade once again?

Any idea on why this occurs would be extremely helpful, thanks in advance!

**Comment by PoojaDurgad** [comment]
@khurshidso - not sure but if you have previous installed node version of 15.5 uninstall it or zip the binary and install your required version of node . if you want to switch between the node version then you can use nvm

**Comment by PoojaDurgad** [comment]
inactive issue. pls feel free to reopen the issue if anything pending

**Comment by lebnic** [comment]
Try running the command `nvm list`, to see what version is configured as your "default":

``` bash
$ nvm list
->     v16.18.1
       v18.12.1
         system
default -> v18.12.1
```

Try changing the default version via the `nvm install --default <VERSION>` command:

``` bash
$ nvm install --default v16.18.1
v16.18.1 is already installed.
Now using node v16.18.1 (npm v8.19.2)
default -> v16.18.1
```
