### ISSUE TITLE
Node . doesn´t work.

### ISSUE THREAD

**Issue by ThePangel** [nodejs/help#3185]
`let score = 100 

score = 130

let bonus = 50

let finalScore = (score + bonus) * 1.8

let complex = ((4 + 4) * 5) / 2

let multiplier = (finalScore * 2)

// Diferent console logs for the socore of the "game"

// console.log(multiplier);
// console.log(finalScore);
// console.log(complex);`

* **Node.js Version**: 15.6.0
* **OS**:Win10 Pro 64bit
* **Scope (install, code, runtime, meta, other?)**: I'm new don't now the difference
* **Module (and version) (if relevant)**: Again I don't now

So i'm following a java course and i had some experience before coding a discord bot and i used `node .` but it doesn´t work  and gives me this error: PS C:\Users\Censored\Censored\Desktop\Im bored> node .
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'C:\Users\Censored\Censored\Desktop\Im bored'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)        
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Hope you can help me
ThePangel 👍

**Comment by Lxxyx** [comment]
`node .` will running index.js, so try naming the file to `index.js` and running `node .`

**Comment by ThePangel** [comment]
> `node .` will running index.js, so try naming the file to `index.js` and running `node .`

Ok ill try

**Comment by ThePangel** [comment]
> `node .` will running index.js, so try naming the file to `index.js` and running `node .`

No it doesn´t work

**Comment by Lxxyx** [comment]
> > `node .` will running index.js, so try naming the file to `index.js` and running `node .`
> 
> No it doesn´t work

You can run it directly by specifying a filename, such as `node index.js`

**Comment by ThePangel** [comment]
I now I just want to run all the scripts in my folder

**Comment by galaxy-01-6182** [comment]
`node .` actually runs the `main` file mentioned in your `package.json`. That is if i have `index.js` value in `main` key of `package.json`. Whenever I type `node .` node treat it as typing `node index.js`. Check with your package.json file

**Comment by RedYetiDev** [comment]
*With the information provided, it's hard to see exactly what's going wrong. If you disagree, please followup with **more information***
