### ISSUE TITLE
zlib gzip one xlsx file get a folder

### ISSUE THREAD

**Issue by chenkai0520** [nodejs/help#3187]
* **Version**: v12.19.0
* **Platform**: Darwin localhost 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:47:48 PST 2020; root:xnu-6153.101.6~16/RELEASE_X86_64 x86_64
* **Subsystem**: zlib

### What steps will reproduce the bug?
```js
  pipeline(
    fs.createReadStream('./_offer_report.xlsx'),
    createGzip(),
    fs.createWriteStream('./_offer_report.xlsx.gz'),
    (err) => {
      if (err) {
        console.error('Pipeline failed.', err);
      } else {
        console.log('Pipeline succeeded.');
      }
    }
  );
```

### What is the expected behavior?

I want to zip a xlsx file use zlib， when i unzip the file i get a folder like the following code

```
├── [Content_Types].xml
├── _rels
├── docProps
│   ├── app.xml
│   └── core.xml
└── xl
    ├── _rels
    │   └── workbook.xml.rels
    ├── styles.xml
    ├── theme
    │   └── theme1.xml
    ├── workbook.xml
    └── worksheets
        └── sheet1.xml
```

**Comment by addaleax** [comment]
What @aduh95 says – you’ll want to use a zip library, not the raw gzip/gunzip functionality provided by Node.js core.

**Comment by chenkai0520** [comment]
> I believe XLSX files are already a ZIP archive, you could rename the file and get the same result. The folder you described is the internal XLSX structure.

thanks，I changed the suffix of the xlsx folder to zip, which is the same as the file obtained after decompression，Only changing the file suffix is incorrect, it needs to be unzipped before it be opened。
i use [archiver](https://www.npmjs.com/package/archiver) decompression after compression is a file
