### ISSUE TITLE
npm -v showing error in windows 10

### ISSUE THREAD

**Issue by yusufhussain028** [nodejs/help#3189]
* **Version**: 14.15.4
* **Platform**: window 10
* **Subsystem**:

**Comment by PoojaDurgad** [comment]
@yusufhussain028 - can you elaborate your issue more please? what error you are facing?

**Comment by yusufhussain028** [comment]
i installed node on my machine on windows 10,
i have set the path variable,
now on running the same on cmd node -v is ok, its version is showing 14.15.4
but when i run npm -v on same it shows the error which i have mentioned.(
'CALL "C:\Users\MohdYusufHussain\nodejs\\node.exe"
"C:\Users\MohdYusufHussain\nodejs\\node_modules\npm\bin\npm-cli.js" prefix
-g' is not recognized as an internal or external command,
operable program or batch file.
6.14.10)
because of this i am not able to create react application
