### ISSUE TITLE
linux32位安装express问题

### ISSUE THREAD

**Issue by vswen** [nodejs/help#319]
![j mpm elpdqus2k oy nt](https://cloud.githubusercontent.com/assets/16498070/19266335/ac496b3c-8fdb-11e6-9f90-10fcbe949024.png)
每次安装nodejs环境 都是好麻烦 哎 菜鸟一枚对命令那些完全不懂

**Comment by bnoordhuis** [comment]
Can you post your question in English?

**Comment by vswen** [comment]
Ha ha English level 4 so embarrassed
Why at the time of installation Say not found install

**Comment by Fishrock123** [comment]
cc @nodejs/nodejs-cn

**Comment by feit** [comment]
npm -v => v6.2.0 ?
you can try (nvm)[https://github.com/creationix/nvm] to install nodejs

**Comment by lordKnighton** [comment]
gonna close for now, feel free to reopen & pursue answer 

--

現在關閉，隨時重新打開和追求答案。 謝謝 😃
