### ISSUE TITLE
Call 50 APIs at a regular interval of <=1s

### ISSUE THREAD

**Issue by harshbhadoria011** [nodejs/help#3190]
I need to write a script which can pull data from more than 50 APIs in every 1sec. I know basics of node js, any type of help will be appreciated. if anyone can provide some resources or learning resource it would be very beneficial.

Thanks

**Comment by bnb** [comment]
Moved to the help repo.

**Comment by gireeshpunathil** [comment]
@harshbhadoria011 - is this outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
