### ISSUE TITLE
Compiling node 10 with Open SSL 1.0.2 to support FIPS mode

### ISSUE THREAD

**Issue by mehran63** [nodejs/help#3191]
* **Node.js Version**: Node 10.x or Node 12.x
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: FIPS
* **Module (and version) (if relevant)**: Open SSL 1.0.2

Hi, Node 10 and 12 are compiled with OpenSSL 1.1.0 and 1.1.1 which don't support FIPS mode. Is there any way to compile Node 10.x or Node 12.x with OpenSSL 1.0.2 to make it FIPS compliant? Is there any other option to have Node 10 or 12 Fips compliant?

**Comment by mhdawson** [comment]
The short answer is no. More details from a tweet I answered last week:

The challenge for community #nodejs FIPS support is waiting for an OpenSSL that will support FIPS again.  We are hoping that will be 3.0.0 and there is work to be ready to integrate OpenSSL 3 into #nodejs but still not clear when that will be available.

Also worth noting that although community #nodejs does not have support for FIPS, Linux distributions do provide support, for example the #nodejs binaries that come with  @RedHat  Enterprise Linux do support FIPS.

The reason that is possible is that the Linux distro's do their own certifications on the OS and shared openssl libraries and the #nodejs binaries on RHEL dynamically link to that shared openssl.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
