### ISSUE TITLE
Docker file for async handler

### ISSUE THREAD

**Issue by Mukesh9092** [nodejs/help#3192]
I am trying to Dockerize below code and want to deploy on knative. I will pas event by trigger. Can someone help me to dockerize it.

async function justWait() {
  return new Promise((resolve, reject) => setTimeout(resolve, 100));
}
module.exports.sayHelloAsync = async (event) => {
  await justWait();
  return {hello: event && event.name || "Good Morning !"};
};

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by gireeshpunathil** [comment]
@Mukesh9092 - is this outstanding? IIUC, there are two parts to it - i) dockerizing a Node.js app, ii) defining a trigger and implementing it for a `serverless` architecture.  which one you are seeking help for?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
