### ISSUE TITLE
Does worker.terminate() always return code 1?

### ISSUE THREAD

**Issue by shadowgate15** [nodejs/help#3193]
* **Node.js Version**: v12.20.0
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: runtime/code
* **Module (and version) (if relevant)**: Worker

When `worker.terminate()` is called, in particular from the main thread, should it always return an `exitCode` of `1`? Or are there situations in which it would return `0`?

**Comment by RaisinTen** [comment]
Doesn't this return `0`?
```js
const { Worker, isMainThread } = require('worker_threads');

if(isMainThread) {
  const worker = new Worker(__filename);
  worker.terminate().then((exitCode) => {
    console.log(exitCode);
  });
}
```

**Comment by addaleax** [comment]
@RaisinTen That code is going to behave unpredictably – it can return either `1` or `0` or `undefined`, depending on which branch of the race condition you hit.

**Comment by RaisinTen** [comment]
@addaleax Ah, yes, `worker.terminate` does set the exit code to `1` unless the worker exits before `terminate` is called.

**Comment by shadowgate15** [comment]
What if a setInterval or setTimeout is called in the worker?

**Comment by RaisinTen** [comment]
Do you mean something like this?
#### test.js
```js
const { Worker, isMainThread } = require('worker_threads');

if(isMainThread) {
  const worker = new Worker(__filename);

  worker.on('exit', (exitCode) => {
    console.log(exitCode);
  });

  setTimeout(() => {
    worker.terminate();
  }, 2000);
} else {
  setTimeout(() => {
    process.exit(2);
  }, 1000);
}
```
In this case, since the worker has already exited by the time terminate is called, you just see this printed in the console:
```zsh
❯ time node test.js
2
node test.js  0.17s user 0.03s system 9% cpu 2.094 total
```

**Comment by shadowgate15** [comment]
So yes but terminate() would have been called before the worker exits.

**Comment by RaisinTen** [comment]
No, in `test.js`, the worker exits (after 1 second) before `terminate` is even called (after 2 seconds). If `terminate` is called before the worker has exited, the worker would have an exit code of `1`.

**Comment by shadowgate15** [comment]
Alright great! That is what I needed to confirm. Thank you everyone!!!
