### ISSUE TITLE
Installer help

### ISSUE THREAD

**Issue by Ricardo1045** [nodejs/help#3195]
* **Node.js Version**:14.15.4
* **OS**:windows 10
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**:

**Comment by dark-magic** [comment]
GG

**Comment by PoojaDurgad** [comment]
@efebalkar - visit the node.js official website https://nodejs.org/en/download/ and install the windows installer  version of node

**Comment by efebalkar** [comment]
didnt help i cant download it it says ended prematuraly

**Comment by RedYetiDev** [comment]
It seems this issue may be invalid. For issues with the download of an installer, consult your browser or system support. If you disagree, please let me know.
