### ISSUE TITLE
Total newb, need help with Installing Nodejs on windows issue...

### ISSUE THREAD

**Issue by plumtree87** [nodejs/help#3196]
I get through installation process to a point on Shell where it says "Installing VisualStudios2017 build tools...." 

and it stays there forever, and no signs of progress. I do not code, I have recently got interested and trying to follow this youtuber who was saying get Node.js to follow him through and then.. meh, couldn't download it properly.

* **Node.js Version**: current LTS
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**:

**Comment by addaleax** [comment]
Are you downloading/installing from https://nodejs.org/en/, or from another source?

**Comment by plumtree87** [comment]
from nodejs.org/en

**Comment by plumtree87** [comment]
should have showed you what happen, it gave me some error saying it didnt download finally...  i exited. Let me run it again.

**Comment by plumtree87** [comment]
![20210125_035954](https://user-images.githubusercontent.com/77940589/105646459-e7778180-5ec1-11eb-9d9e-37bddf0ec42b.jpg)
![Uploading 20210125_044148.jpg…]()

**Comment by plumtree87** [comment]
![Uploading 20210125_044148.jpg…]()

**Comment by plumtree87** [comment]
![image](https://user-images.githubusercontent.com/77940589/105647781-bf096c00-5e5c-11eb-912f-bc5e51d95257.png)

**Comment by PoojaDurgad** [comment]
@plumtree87 - can you try installing the node without selecting the additional tools options and see whether it will install the node properly or not? later you can download the additional tools if required

**Comment by regularnoobie** [comment]
What am I suppose to do as of right now.

**Comment by RedYetiDev** [comment]
This installer is many years old, and if this issue still occurs, please open a new issue.

Thank you
