### ISSUE TITLE
Installer error 2894 help please

### ISSUE THREAD

**Issue by efebalkar** [nodejs/help#3197]
* **Node.js Version**:14.15.4
* **OS**:Windows
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**:i dont know

**Comment by PoojaDurgad** [comment]
@efebalkar - looks like this is not an issue with the node but your windows problem. It is a system error and it has some repair methods . I am not sure about repair methods but you may refer this https://www.errorvault.com/en/troubleshooting/runtime-errors/microsoft/microsoft-access/error-2894_microsoft-access-error-2894

**Comment by PoojaDurgad** [comment]
closing as answered. feel free to reopen the issue if there is anything pending on this issue.
