### ISSUE TITLE
use windows service to run node 

### ISSUE THREAD

**Issue by zenzedoon** [nodejs/help#3198]
* **Node.js Version**:  v14.15.4
* **OS**: Windows Server 2016 
* **Scope (install, code, runtime, meta, other?)**: Other
* **Module (and version) (if relevant)**: --

```js
i want to create a windows service that can run my node js application even when windows go down and restart.
Can any one have a solution to this.
```

**Comment by PoojaDurgad** [comment]
@nodejs/platform-windows
