### ISSUE TITLE
Node incompatible with this module expecting newer version

### ISSUE THREAD

**Issue by CRMIII** [nodejs/help#3199]
error postcss@8.2.4: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || >=14".
error Found incompatible module

The current version is 8.2
8.2.4 • Public • Published 17 days ago

**Comment by tniessen** [comment]
Which version of Node.js are you using?

**Comment by CRMIII** [comment]
Sorry for the trouble, I figured it out, no idea how, but I did.

Thanks,
Charles
