### ISSUE TITLE
Install node

### ISSUE THREAD

**Issue by chadkill89** [nodejs/help#3200]
Node.js Version: 14.15.4
    OS: Windows 10
    Scope (install, code, runtime, meta, other?):install
    Module (and version) (if relevant):

when I run the command node -v nothing happens and the installation is successful

**Comment by PoojaDurgad** [comment]
@chadkill89 - what is the output of `where node` and `where npm`?

**Comment by marsonya** [comment]
@chadkill89, is this issue resolved?

**Comment by RedYetiDev** [comment]
*(No response, assuming closed)*
