### ISSUE TITLE
Need for Installation Guide for Windows in Wiki Section .

### ISSUE THREAD

**Issue by NegiAkash890** [nodejs/help#3204]

**Comment by PoojaDurgad** [comment]
can you refer https://phoenixnap.com/kb/install-node-js-npm-on-windows?

**Comment by NegiAkash890** [comment]
@PoojaDurgad . Thanks for responding . I was  asking whether I can help adding installation steps (for windows) to install nodejs in the wiki section  as we have for Linux and AIX  . It was not an issue but a suggestion .
