### ISSUE TITLE
How to load module correctly (error: module is not an object or function)? #13387

### ISSUE THREAD

**Issue by paulocoutinhox** [nodejs/help#3206]
Hi guys. Im trying load WASM module here:
https://paulo-coutinho.github.io/pdfium-lib/

But you can see on log/console that is throwing error:
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function

I tried a lot of things to make it work as standalone wasm module. 

My html code is here:
https://github.com/paulo-coutinho/pdfium-lib/blob/support-wasm/extras/wasm/template/index.html

Can anyone help me?

**Comment by cjihrig** [comment]
I'm moving this to the help repo because it is not a Node.js issue.

It looks like your import object does not match up with the expected imports. `WebAssembly.Module.imports(module);` shows that the wasm module is expecting a number of imports that aren't being provided.

**Comment by paulo-coutinho** [comment]
Ok. I will search more.

But i don't understand three things. Can you answer me?

1. The standalone mode let me use it without a browser with wasmer for example? But it cannot be used on web like im doing now?
2. What is the "correct" compile mode to make it be used optimised for web? Im using today these flags inside pdfium.rsp:
```
-s DEMANGLE_SUPPORT=1
-s USE_PTHREADS=1
-s USE_ZLIB=1
-s USE_LIBJPEG=1
-s WASM=1
```

And when compile:

```
"emcc",
"-o",
"index.html",
"-s",
'EXPORTED_FUNCTIONS="$(node function-names ../xml/index.xml createDocFromBuffer)"',
"-s",
'EXTRA_EXPORTED_RUNTIME_METHODS=\'["ccall", "cwrap"]\'',
"--pre-js pre-js.js",
"avail.c",
"@pdfium.rsp",
"-Os",
```

3. Without standalone mode what is the correct way/flow to generate a library that others can use on their website and in my web demo site?

Thanks.
