### ISSUE TITLE
Difference in binary build size between official distribution package and self-compiling (Arch Linux)

### ISSUE THREAD

**Issue by hansmiller75** [nodejs/help#3208]
I previously opened this issue on the nodejs main repo but it seems to have been deleted.

I'm an Arch Linux user and the official build size of node when installed as a package is about 29 MB. When I download the PKGBUILD file myself (the file containing instructions how to build the package) and run makepkg, I also get a binary that's the same size as the official one.

But when I clone the nodejs repository, switch to the v15.7.0 tag, run configure with the same flags as in the PKGBUILD:

./configure \
  --prefix=/usr \
  --with-intl=system-icu \
  --without-npm \
  --shared-openssl \
  --shared-zlib \
  --shared-libuv \
  --experimental-http-parser \
  --shared-nghttp2
    
and then run make, I get a build that's about 10 MB larger, 39 MB.

Am I doing something wrong or missing something?

Thanks.

**Comment by addaleax** [comment]
Is there maybe just a version mismatch? Are you comparing two x64 binaries or are they for different architectures?

**Comment by hansmiller75** [comment]
> Is there maybe just a version mismatch? Are you comparing two x64 binaries or are they for different architectures?

I'm doing everything on the same computer, running a x64 system (and building for this arch too as I haven't specified anything difference).

uname -a
Linux [computer-name] 5.10.11-arch1-1 #1 SMP PREEMPT Wed, 27 Jan 2021 [time] +0000 x86_64 GNU/Linux

**Comment by hansmiller75** [comment]
Just compared the two binaries using the file command:
file /usr/bin/node
/usr/bin/node: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9c483d914973f8c45f5ea5d94d8fcc343c3e2533, for GNU/Linux 3.2.0, stripped

file out/Release/node
out/Release/node: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=90e6d2990d7ffbc4829815c55f52c781167caa7c, for GNU/Linux 3.2.0, with debug_info, not stripped

How would I remove the debug_info and strip the executeable?

**Comment by addaleax** [comment]
Okay, that makes sense :) https://linux.die.net/man/1/strip is your friend here :)
