### ISSUE TITLE
npm login - registration disabled error

### ISSUE THREAD

**Issue by ericjunkins** [nodejs/help#3213]
* **Node.js Version**: 6.14.10
* **OS**: Catalina 10.15.7
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: N/A

Trying to run `npm login` always gives me an error of npm, regardless of if the username/pass are active. I've verified that I can login to the browser using the credentials I supply here though

`ERR! 409 Conflict - PUT <url>.user:<user> - registration is disabled`

I've tried deleting the `~/.npmrc`, as well as running `sudo npm uninstall npm -g` and then reinstalling `npm` and still have the same issue

**Comment by PoojaDurgad** [comment]
for me it looks similar to https://github.com/verdaccio/verdaccio/issues/441#issuecomment-353063903

**Comment by ericjunkins** [comment]
hm reading through it that seems similar yes, I can't quite tell what the resolution is though.  This comment makes it seem like they added the check for `add_user` to exist?
https://github.com/verdaccio/verdaccio/issues/441#issuecomment-360695667

It seems that this is caused by not having an `add_user` function, would that not come standard with a fresh install of `npm v 6.14.10` ?

**Comment by RedYetiDev** [comment]
Hi! If this is still outstanding, please follow up with the NPM team.
