### ISSUE TITLE
fsPromises.writeFile lost files issue

### ISSUE THREAD

**Issue by PandaBalls** [nodejs/help#3214]
* **Node.js Version**:v15.8.0
* **OS**:osx 10.15.7
```js
  for (let i = 0; i < files_list.length; i++) {
    let file = files_list[i];
    let file_path = `input_File_${file.seq}.txt`;
    let new_file_path = `output_File_${file.seq}.html`;
    let data = await fsPromise.readFile(file_path);
    await fsPromise.writeFile(new_file_path, data);
  }
```

I use this loop to read files from an Array, and write out without data changing , just rename them.
I tried `readFile/writeFile callback` method  and `readFileSync/writeFileSync` method and this `fsPromises await` method,
the written result alway be different , will lose files with different amount.

**Comment by RaisinTen** [comment]
What does `files_list` contain? If it is just a list of `string`s, then I guess you didn't mean to do `file.seq` in `file_path` and `new_file_path`. Your code does work for me if I move the `seq` outside the braces:
```zsh
❯ ls
input_File_1.seq.txt  input_File_2.seq.txt  test.js
❯ cat test.js
```
```js
'use strict';
const fs = require('fs');
const fsPromise = fs.promises;
const files_list = ['1', '2'];
(async() => {
  for (let i = 0; i < files_list.length; i++) {
    let file = files_list[i];
    let file_path = `input_File_${file}.seq.txt`;
    let new_file_path = `output_File_${file}.seq.html`;
    let data = await fsPromise.readFile(file_path);
    await fsPromise.writeFile(new_file_path, data);
  }
})();
```
```zsh
❯ cat input_File_1.seq.txt
Hello, from file 1!
❯ cat input_File_2.seq.txt
Hello, from file 2!
❯ node test.js
❯ diff input_File_1.seq.txt output_File_1.seq.html
❯ diff input_File_2.seq.txt output_File_2.seq.html
```

**Comment by PandaBalls** [comment]
> What does `files_list` contain? If it is just a list of `string`s, then I guess you didn't mean to do `file.seq` in `file_path` and `new_file_path`. Your code does work for me if I move the `seq` outside the braces:
> 
> ```shell
> ❯ ls
> input_File_1.seq.txt  input_File_2.seq.txt  test.js
> ❯ cat test.js
> ```
> 
> ```js
> 'use strict';
> const fs = require('fs');
> const fsPromise = fs.promises;
> const files_list = ['1', '2'];
> (async() => {
>   for (let i = 0; i < files_list.length; i++) {
>     let file = files_list[i];
>     let file_path = `input_File_${file}.seq.txt`;
>     let new_file_path = `output_File_${file}.seq.html`;
>     let data = await fsPromise.readFile(file_path);
>     await fsPromise.writeFile(new_file_path, data);
>   }
> })();
> ```
> 
> ```shell
> ❯ cat input_File_1.seq.txt
> Hello, from file 1!
> ❯ cat input_File_2.seq.txt
> Hello, from file 2!
> ❯ node test.js
> ❯ diff input_File_1.seq.txt output_File_1.seq.html
> ❯ diff input_File_2.seq.txt output_File_2.seq.html
> ```

`files_list` is an Array contained JSON object, each object has a `key` named "seq"

**Comment by RaisinTen** [comment]
Could you share what error you get when you run the script?

**Comment by PandaBalls** [comment]
> Could you share what error you get when you run the script?

No errors are  thrown,  But the amount of output files alway less than Array length, lost files after resaving.

**Comment by PandaBalls** [comment]
fixed, sorry... the files_list got some duplicated files.... :(
