### ISSUE TITLE
Segmentation fault Error

### ISSUE THREAD

**Issue by ms6rb** [nodejs/help#3216]
* **Node.js Version**: 15.8.0
* **OS**: linux - debian
* **Scope**: runtime

i am getting this error ``Segmentation fault`` i don't know why or where 

```js
PID 22564 received SIGSEGV for address: 0xffffffff
/root/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x2cc1)[0x7f7c345f1cc1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7f7c35ba60e0]
node[0xa1c7fe]
node[0xcaedfb]
node[0xcb03ac]
node(_ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE+0x16)[0xcb0a26]
node[0x14cfc59]
```
-->

**Comment by RaisinTen** [comment]
I believe this should be reported here too: https://github.com/ddopson/node-segfault-handler
Also, how do we recreate this error?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
