### ISSUE TITLE
child_process's stdout

### ISSUE THREAD

**Issue by Bobricko** [nodejs/help#3219]
I have to bind child process.spawn().stdout later, than I spawn the command, therefore I have unpleasant feeling, that something could not be catched by stdout's function. Events should be always bound, before first emmit possible occurs, and in this case it seems stupid.

**Comment by RaisinTen** [comment]
I don't think any data is lost though:
```zsh
❯ cat script.sh
#!/bin/bash

# echoes 1 to 5 with
# a 1 second delay each
for i in $(seq 1 5)
do
  echo $i
  sleep 1
done
❯ cat test.js
const { spawn } = require('child_process');
const cp = spawn('bash', ['script.sh']);

// attaching the event handlers after 2 seconds
setTimeout(function() {
  cp.stdout.on('data', (data) => {
    console.log(`stdout: ${data}`);
  });

  cp.on('close', (code) => {
    console.log(`child process close all stdio with code ${code}`);
  });

  cp.on('exit', (code) => {
    console.log(`child process exited with code ${code}`);
  });
}, 2000);
❯ node test.js
stdout: 1

stdout: 2

stdout: 3

stdout: 4

stdout: 5

child process exited with code 0
child process close all stdio with code 0
```
As soon as 2 seconds pass, the data from the internal buffer gets drained by the attached handler.
Also, check this out:
https://stackoverflow.com/questions/35463707/how-to-ensure-we-listen-to-a-child-process-events-before-they-occur

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
