### ISSUE TITLE
Does nodejs have an equivalent to interface definition language(.idl) files for https://nodejs.org/api/?

### ISSUE THREAD

**Issue by crocket** [nodejs/help#322]
DOM has .idl files, and alternative javascript languages have DOM bindings automatically generated from those .idl files.

Does nodejs have an equivalent to .idl files from which a binding for alternative javascript language can be automatically generated?

**Comment by lordKnighton** [comment]
Hey @crocket apologies about being late. I see your brief convo over @ https://github.com/nodejs/node/issues/9075  But to my knowledge i don't think so. 

--

I'm gonna close this issue for now, but if you want to reopen this, you can do that, & i'll spend time finding out with you.
