### ISSUE TITLE
can not start local http server using nodejs with remote files on a NAS

### ISSUE THREAD

**Issue by bwanaaa** [nodejs/help#3222]
node 14.15.5
ubuntu 20.04

I have a website that I am working on and keep the html, css, and javascript in a folder on a NAS. On my local machine, I have installed 'serve' with 'npm i -g serve'. I can copy the website folder to my machine , open a terminal in that folder, and type 'serve'. It gives me an ip and the website is accessible as it should be. This allows me to test the websites features as I build it.

However, if I navigate to the website folder on the NAS, and try to serve from there I get this:
```console
% serve
WARNING: Checking for updates failed (use `--debug` to see full error)
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at /Users/stefan/.nvm/versions/node/v15.8.0/lib/node_modules/serve/bin/serve.js:419:22 {
  errno: -1,
  code: 'EPERM',
  syscall: 'uv_cwd'
}
```
The NAS has read/write permissions for everyone so I do not understand why I am getting a permissions error.

How can I work on a website that is stored remotely?

**Comment by RaisinTen** [comment]
Is this related? https://github.com/vercel/serve/issues/536

I wonder what this prints when you run it from the folder inside the NAS (where you  ran `serve`):
```c
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int main() {
  char buf[BUFSIZ];

  if(getcwd(buf, BUFSIZ) == NULL) {
    fprintf(stderr,
            "ERROR: %s "
            "(errno = %d)\n",
            strerror(errno),
            errno);
    exit(EXIT_FAILURE);
  }

  printf("getcwd returned: "
         "\"%s\"\n",
         buf);

  return 0;
}
```

**Comment by bwanaaa** [comment]
Actually, I discovered this only happens on a Mac. If I mount the share on a linux box

 sudo mount -t cifs //NAS/files -o username=user,password=passwd,rw,nounix,iocharset=utf8,file_mode=0644,dir_mode=0755,sec=ntlmssp /mnt/NAS


then I can start a server just fine and it works.

It is weird because even tho I am owner of the folder on the NAS, I can navigate the NAS on the desktop, open and copy and modify all the files through the finder. I can not even look at the directory with ls in terminal. I am opening a terminal on the NAS using go2shell.

**Comment by RaisinTen** [comment]
>Actually, I discovered this only happens on a Mac.

Ah, I thought this was an Ubuntu issue since you mentioned that at the top.

>I can not even look at the directory with ls in terminal.

Does it print some kind of an error when you do that? Are you able to run `pwd` there, because that's the function in question here?

**Comment by bwanaaa** [comment]
turns out it is something unrelated to nodes. Rather it's an issue that BigSur (MacOS 11.2) has with terminal having trouble with smb. See this:
https://developer.apple.com/forums/thread/673970
and
https://forums.macrumors.com/threads/big-sur-problems-with-smb.2268613/

If I mount the NAS share through the finder and then open a terminal window in the shared folder directly, nodes works fine.
