### ISSUE TITLE
How to use encoding in child_process.fork()?

### ISSUE THREAD

**Issue by hwahyang1** [nodejs/help#3223]
* **Node.js Version**: v15.8.0
* **OS**: Windows 10 20H2 (x64)
* **Scope (install, code, runtime, meta, other?)**: 
* **Module (and version) (if relevant)**: child_process

```javascript
// ./core.js is the file that I want to run as a child process.
child_process.fork(path.join(__dirname, './', 'core.js'), [], {stdio: [0, 1, 2, null, 'ipc'], env: {...process.env, ...data}});
```

I was using the `child_process.fork()` function to create execution checks and communications for the child process.

However, the Korean encoding continued to be broken, and the code page was 65001, but the Korean language was still broken.

(If the code page is set to 65001 and the child process file is run directly, the Korean language is not broken, but if the `child_process.fork()` function is run through the parent process, the Korean language is broken.)

I also thought about communication through `child_process.execFile()` and `socket.io`, but there are too many codes to modify, so I want to specify encoding in child_process module.

Is there any way I can specify the encoding in `child_process.fork()`?

**Comment by RaisinTen** [comment]
>but there are too many codes to modify

Anything other than your cmd's encoding?

The function `execFile` does have an `encoding` option
which defaults to `'utf8'` (which is the same as 65001?)
unlike `fork` which doesn't allow you to set the encoding,
so I'm curious to know whether `execFile` works for you.

**Comment by hwahyang1** [comment]
> > but there are too many codes to modify
> 
> Anything other than your cmd's encoding?
> 
> The function `execFile` does have an `encoding` option
> which defaults to `'utf8'` (which is the same as 65001?)
> unlike `fork` which doesn't allow you to set the encoding,
> so I'm curious to know whether `execFile` works for you.

I'll try that
Thanks!
