### ISSUE TITLE
Where did the nodjs QUIC support / documentation go?

### ISSUE THREAD

**Issue by Amyy** [nodejs/help#3228]
* **Node.js Version**: 15.15.1
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**:  QUIC [draft-27](https://tools.ietf.org/html/draft-ietf-quic-http-27)

Until recently, nodejs had a [QUIC support
](https://nodejs.org/api/quic.html) by compiling nodejs via the --experimental-quic flag. (It's also described in [this](https://github.com/nodejs/node/issues/23064#issuecomment-702169489) comment.)

We implemented a QUIC server+client setup for a university project in nodejs and everything works fine. But now the QUIC documentation is gone and we still have work to do on that project...
I hope I didn't overlook anything, but I can't find the documentation anywhere right now. Does somebody know more about the current state of QUIC in nodejs?

**Comment by richardlau** [comment]
It was removed in https://github.com/nodejs/node/pull/37067.

**Comment by Amyy** [comment]
Oh that's unfortunate. Thank you for the fast reply!

Is there any possibility to at least read the deprecated documentation? We can't find it [here](https://nodejs.org/docs/).
That would already help us a lot.

**Comment by RaisinTen** [comment]
Here: https://nodejs.org/dist/v15.7.0/docs/api/quic.html

**Comment by Amyy** [comment]
That was fast, thanks a lot!! :)
