### ISSUE TITLE
Допоможіть будь ласка

### ISSUE THREAD

**Issue by Serg1yk0** [nodejs/help#3229]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by Serg1yk0** [comment]
Стикнувся з проблемою :
TypeError: Assignment to constant variable.
    at Object.<anonymous> (C:\Users\Taras\Desktop\fls-gulp\gulpfile.js:36:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireOrImport (C:\Users\Taras\AppData\Roaming\npm\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)
    at execute (C:\Users\Taras\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:37:3)
    at Liftoff.handleArguments (C:\Users\Taras\AppData\Roaming\npm\node_modules\gulp-cli\index.js:211:24)
    Не знаю як її вирішити.
перепробував багато варіантів.
1)очищав пакетний менеджер(декілька раз) cache-clean --force
2)Перевстановлював  nod.js
3)видаляв вузол.
4).....
нічого не помогло.
Буду вдячний за любу пораду!

**Comment by vsemozhetbyt** [comment]
Без коду в C:\Users\Taras\Desktop\fls-gulp\gulpfile.js буде важко зрозуміти, в чому проблема. Якщо файл не дуже великий, надайте код в коментарі, або завантажте кудись і дайте посилання.

**Comment by Serg1yk0** [comment]
const fileinclude = require('gulp-file-include');

let project_folder="dist";
let source_folder="src";

let path={
  build:{
    html:project_folder + "/",
    css:project_folder + "/css/",
    js:project_folder + "/js/",
    img:project_folder + "/img/",
    fonts:project_folder + "/fonts/",

  },
  src:{
    html:source_folder + "/*.html",
    css:source_folder + "/scss/style.scss",
    js:source_folder + "/js/script.js",
    img:source_folder + "/img/**/*.{jpg,png,svg,gif,ico,webp}",
    fonts:source_folder + "/fonts/*.ttf",

  },
  watch:{
    html:source_folder + "/**/*.html",
    css:source_folder + "/scss/**/*.scss",
    js:source_folder + "/js/**/*.",
    img:source_folder + "/img/**/*.{jpg,png,svg,gif,ico,webp}",

  },
  clean:"./"+ project_folder + "/"
}

let{src,dest} = require('gulp'),
gulp = require('gulp'),
browsersync = require('browser-sync').create();
fileinclude = require('gulp-file-include');
function browserSync(params) {
  browsersync.init({
    server:{
      baseDir:"./"+ project_folder + "/"
    },
    port:3000,
    notify:false
  })  
}
function html() {
  return src(path.src.html)
  .pipe(fileinclude())
  .pipe(dest(path.build.html))
  .pipe(browsersync.stream())
}
let build = gulp.series(html);
let watch = gulp.parallel(build,browserSync);

exports.html = html;
exports.build = build;
exports.watch = watch;
exports.default = watch;
ось,будь ласка.

**Comment by vsemozhetbyt** [comment]
У вас в першому рядку оголошена `const` змінна:
```js
const fileinclude = require('gulp-file-include');
```
А в 36-му рядку ви намагаєтесь її перевизначити:
```js
fileinclude = require('gulp-file-include');
```

Оскільки цей рядок нічого нового не робить, його можна просто видалити, якщо я не помиляюсь. Або можна замінити в першому рядку `const` на `let`.

**Comment by Serg1yk0** [comment]
дякую,але не помогло.
спробував обидва варіанти.все те саме.

**Comment by vsemozhetbyt** [comment]
Ви видалили 36-й рядок, замінили в 1-му `const` на `let` і повідомлення про помилку лишилось тим самим? З точністю до назв файлів и номерів рядків?

**Comment by Serg1yk0** [comment]
//Замінив const на Let
let fileinclude = require('gulp-file-include');
let source_folder="src";

let path={
  build:{
    html:project_folder + "/",
    css:project_folder + "/css/",
    js:project_folder + "/js/",
    img:project_folder + "/img/",
    fonts:project_folder + "/fonts/",

  },
  src:{
    html:source_folder + "/*.html",
    css:source_folder + "/scss/style.scss",
    js:source_folder + "/js/script.js",
    img:source_folder + "/img/**/*.{jpg,png,svg,gif,ico,webp}",
    fonts:source_folder + "/fonts/*.ttf",

  },
  watch:{
    html:source_folder + "/**/*.html",
    css:source_folder + "/scss/**/*.scss",
    js:source_folder + "/js/**/*.",
    img:source_folder + "/img/**/*.{jpg,png,svg,gif,ico,webp}",

  },
  clean:"./"+ project_folder + "/"
}

let{src,dest} = require('gulp'),
gulp = require('gulp'),
browsersync = require('browser-sync').create();
//видалив fileinclude = require('gulp-file-include');

function browserSync(params) {
  browsersync.init({
    server:{
      baseDir:"./"+ project_folder + "/"
    },
    port:3000,
    notify:false
  })  
}
function html() {
  return src(path.src.html)
  .pipe(fileinclude())
  .pipe(dest(path.build.html))
  .pipe(browsersync.stream())
}
let build = gulp.series(html);
let watch = gulp.parallel(build,browserSync);

exports.html = html;
exports.build = build;
exports.watch = watch;
exports.default = watch;

**Comment by Serg1yk0** [comment]
Ура ,пішло.
Дай вам Боже здоров*я!!!

**Comment by vsemozhetbyt** [comment]
І вам) Якщо проблему вирішено, будь ласка, закрийте issue)
