### ISSUE TITLE
How to implement mail service?

### ISSUE THREAD

**Issue by kirahmadlare** [nodejs/help#323]
Hi do you know how can i install an smtp in node.js?

**Comment by lordKnighton** [comment]
Can you give details about what you're trying to do?

**Comment by kirahmadlare** [comment]
Hi Kelvin,

What I want to do is to have a forgot password module in my app, and I'm
really pretty new to this. I want to add it to this app I've created

https://thawing-badlands-22593.herokuapp.com/login

I hope you can help me

Thank you.

**Comment by lordKnighton** [comment]
So sorry for responding 42 hours later. But i have found an excellent article for you. [click me 🐱 ](http://sahatyalkabov.com/how-to-implement-password-reset-in-nodejs/) 

--

I'm actually gonna do this tutorial myself pretty soon. Any way, if you need further help, do let me know. 

💯 Happy coding.

**Comment by kirahmadlare** [comment]
Thank you so much for your help :) please share it to me your own tutorial!
video please Thanks

**Comment by lordKnighton** [comment]
I won't be making a video, but i will push the result to my github repo. 👍
