### ISSUE TITLE
Is there a way to ignore custom CA common name?

### ISSUE THREAD

**Issue by rotegott** [nodejs/help#3232]
I develop decentralized p2p app with Node.JS. Each client has own master x.509 cert and signed cert for each device (node). When client A wants to add client B to a friends list, he just add his master cert in own CA list and trust all node certs of Client B. It works as I expected, but there is one problem - "common name" colission in CA list makes trusted signed certificates untrusted. Two clients with the same Common Name can't reach each other, and I think if Client B make the same CN as Client C, Client A wouldn't connect with Client C because of B&C CN colission. In my program will not be any domains and SNI and I want to identify client only by his certificate. So, how can I avoid problem caused by CA common names colission? As temporary solution I added random uuid for CN in certificate generator, but it isn't an option.

**Comment by marsonya** [comment]
cc @nodejs/crypto
