### ISSUE TITLE
Clarification on pipeline docs: event listeners

### ISSUE THREAD

**Issue by bdharrington7** [nodejs/help#3234]
* **Node.js Version**: 15.10
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: Docs
* **Module (and version) (if relevant)**: N/A

Trying to get some clarity on the documentation: At the end of this [section on pipelines](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback), there's a note that:

> `stream.pipeline()` leaves dangling event listeners on the streams after the callback has been invoked. In the case of reuse of streams after failure, this can cause event listener leaks and swallowed errors.

It's weirdly worded, but is this basically saying if you're reusing the streams used in the pipeline function, it doesn't do any cleanup on the listeners (but will be taken care of with garbage collection?)?  It sounds like a developer would only need to care if they're doing something with the streams outside of the pipeline function. 

Is this a bug?

**Comment by marsonya** [comment]
cc @nodejs/documentation

**Comment by gireeshpunathil** [comment]
@nodejs/streams

**Comment by mcollina** [comment]
I think the text is properly worded and describe exactly how it is implemented. This is not a bug. If you think you can be worded better, would you like to raise a PR?

> It sounds like a developer would only need to care if they're doing something with the streams outside of the pipeline function.

Exactly
