### ISSUE TITLE
Slack Community Registration link is Invalid

### ISSUE THREAD

**Issue by marsonya** [nodejs/help#3235]
The Node.js Slack Community [registration link](http://www.nodeslackers.com/) in [README.md](https://github.com/nodejs/help#chat) of this repo is invalid.

**Comment by gireeshpunathil** [comment]
looks like the site has moved? @RaisinTen - do you remember what it was supposed to point to?

**Comment by RaisinTen** [comment]
I'm sorry, I'm not aware of that.
It was introduced in this PR: https://github.com/nodejs/help/pull/1777 and the link hasn't changed since.
Even the get involved page for Node.js has the outdated link (Node Slackers):
https://nodejs.org/en/get-involved/

**Comment by RaisinTen** [comment]
cc @aymen94
Could you please help us out with the Node Slackers link?

**Comment by gireeshpunathil** [comment]
o, sorry! for some reason I thought it was you who developed it!

**Comment by marsonya** [comment]
The [registration link](http://www.nodeslackers.com/) is now back up.
I signed up and received the slack invite.

Think it's safe to close this issue now.
