### ISSUE TITLE
Build node.js isnt working on windows

### ISSUE THREAD

**Issue by itssigron** [nodejs/help#3236]
* **Node.js Version**: 14.15.5
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: not relevant

So i've cloned the github repo of nodejs tag 14.15.5, i've runned "vcbuild.bat openssl-no-asm" and its runned for a few minutes and then done, now im trying to do out/release/node as this image shows:
![IMAGE](https://user-images.githubusercontent.com/52041489/109047998-32fa9680-76df-11eb-9c69-a2002bacf0c6.png)
but there is no node.exe in the release folder, why isnt it creating that file? (it does have out/release folder but no node.exe in it.)

**Comment by marsonya** [comment]
hey @itssigron, is this issue resolved or do you need help with it?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
