### ISSUE TITLE
npm i fails

### ISSUE THREAD

**Issue by iamjoytank** [nodejs/help#3237]
* **Node.js Version**: 12.x,14.x
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: 
![WhatsApp Image 2021-02-25 at 8 56 52 AM](https://user-images.githubusercontent.com/54657458/109115404-07ba8a80-7765-11eb-95b4-80cd6850593c.jpeg)

![w](https://user-images.githubusercontent.com/54657458/109114960-5e739480-7764-11eb-9e6f-770000fea1bd.PNG)

* **Module (and version) (if relevant)**:

I'm unable to execute command **npm i** to install packages. Every time I do the process goes in halt state.
I have tries node version 12.18.4, 12.21.0, 14.15.5 and 14.16.0, and also reinstall them many times.
Also, this issue frequently occurs.

**Comment by marsonya** [comment]
Hey @iamjoytank, can you share your package.json file?

**Comment by iamjoytank** [comment]
I have solved this issue by upgrading npm version to latest one.
Problem was with npm and also asus framework driver
