### ISSUE TITLE
The program is stuck and cannot continue

### ISSUE THREAD

**Issue by githubhanjunjun** [nodejs/help#3238]
**The problem**: Cannot get the result of within async.eachLimit. I don't get “success” or “failed”. I don't have any error. The program is stuck and cannot continue. What should I do to solve this problem. Thank you so much.

**NodeJS Version**: 13.x
**Platform**: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-171-generic x86_64)
**Codeing**:
```js
const eachLimit = require('async/eachLimit'),
download = require('image-downloader');
const IMGPATH = '/images';
**// Each picture is 3-4M**
const urllist = [
    '1.jpg','2.jpg','3.jpg', ...... ,'362.jpg'
]
eachLimit(urllist, 5, (url, cb) => download.image({
         url: url,
         dest: IMGPATH
}).then(() => cb()).catch(err => cb(err)))
.then(() => {
    console.log("success")
})
.catch(err => {
    console.log("failed")
})
```

**Comment by marsonya** [comment]
@githubhanjunjun, kindly share your full code or a reproducible example so that we can help you resolve the issue.

**Comment by RedYetiDev** [comment]
*(Closing, as no response)*
