### ISSUE TITLE
Use of child_process.spawn to pipe data

### ISSUE THREAD

**Issue by targos** [nodejs/help#324]
Hello. I would like to the the following using `child_process.spawn`:

string (input of command 1) -> `command1 | command2 | command3` -> string (output of command3)

I wrote a script like that (simplified):

``` js
var spawn = require('child_process').spawn;

var cp1 = spawn('/bin/command1', ['arg1', 'arg2'], {stdio: 'pipe'});
var cp2 = spawn('/bin/command2', ['arg1', 'arg2'], {stdio: [cp1.stdout, 'pipe', 'pipe']});
var cp3 = spawn('/bin/command3', ['arg1', 'arg2'], {stdio: [cp2.stdout, 'pipe', 'pipe']});

var result = '';
cp3.stdout.on('data', data => result += data);
cp3.on('close', () => console.log(result));

cp1.stdin.end('mydata');
```

The problem is I sometimes get the correct result and sometimes it finishes with an empty string (given the same input data).
Am I doing something obviously wrong ?

**Comment by addaleax** [comment]
> Am I doing something obviously wrong ?

If it’s any consolation, no, there’s nothing obviously wrong to me, and the code looks about like what I would have written.

I tried turning your example into a runnable script spawning `cat`, and it seems to work okay…

**Comment by targos** [comment]
Closing in favor of https://github.com/nodejs/node/issues/9413
