### ISSUE TITLE
Piping redable from to response with content-length produces cuted result when emoji used

### ISSUE THREAD

**Issue by RastaAlex** [nodejs/help#3243]
* **Version**: v14, v15
* **Platform**: Linux
* **Subsystem**: http

### What steps will reproduce the bug? 

When I pipe stream created from string with emoji to response i get result cuted. I set content-length with size of a string and cant understand why should i add additional 2 bytes to get full result. 

```js
const http = require('http')
const {stringify} = JSON;

const server = http.createServer((req, res) => {
    const {path, files} = {
        path: "😀",
        files: [], 
    };

    const {Readable} = require('stream');
    const json = stringify({
        path,
        files,
    }, null, 4);

    const stream = Readable.from(json);
    res.setHeader('Content-Length', json.length + 2);
    stream.pipe(res);
});

server.listen(1337)
```
When i try to download i recive response without "}":

```
curl localhost:1337
{
    "path": "😀",
    "files": []
```
When i change content-length: 

```diff
-res.setHeader('Content-Length', json.length);
+res.setHeader('Content-Length', json.length + 2);
```

I recive result with "}":
 
```
curl localhost:1337
{
    "path": "😀",
    "files": []
}
```

### How often does it reproduce? Is there a required condition?
Allways.

### What is the expected behavior?
I expected that i set content-length to length of a string with emoji i recive full result.

### What do you see instead?
I see cuted result.

**Comment by mscdex** [comment]
You should always use `Buffer.byteLength()` to find how many *bytes* the string consists of (this is what you want for something like Content-Length, which is a measure of *bytes*). `string.length` only tells you how many *characters* are in the string.

**Comment by marsonya** [comment]
@RastaAlex,  I hope mscdex's explanation resolved this issue.
Do you need more help with this issue?

**Comment by RastaAlex** [comment]
@marsonya , no thanks. @mscdex  answer really helps me.
