### ISSUE TITLE
The specified module could not be found.

### ISSUE THREAD

**Issue by NicoFNBR** [nodejs/help#3246]
* **Version**: 14.16.0
* **Platform**: Windows 10
* **Subsystem**:

Hi, I run node ./src/index,js to start my bot, and I get the following error 
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Administrator\Desktop\Cyclo\cyclo\node_modules\node-wick\bin-package\index.node

I only get this on my VPS, however it works perfectly fine on my PC.

**Comment by NicoFNBR** [comment]
![image](https://user-images.githubusercontent.com/62701876/109442947-484e2880-7a31-11eb-9daa-669922813331.png)
Here is a image.

**Comment by marsonya** [comment]
Hey @NicoFNBR,  can you share your full code?
It will help me understand the problem.

**Comment by marsonya** [comment]
> Hey @NicoFNBR, can you share your full code?
> It will help me understand the problem.

ping @NicoFNBR
is this still an issue?
