### ISSUE TITLE
I know how to make a port version of the python 2.x files in the org should I and pr them when done?

### ISSUE THREAD

**Issue by AraHaan** [nodejs/help#325]
A lot of people find it strange that they cant use their favorite 3.x because it uses old style eval's and things I plan to make a version that if their interpreter is 3.x or above then they can use that instead. When I do this it will import separate files however to avoid `SyntaxError`'s in 2.x. So, it should really not break anything if done right.

The pro's is that I the the difference between the 2.7.x and the 3.x Syntax and so that should not be a total or real issue really.

**Comment by lordKnighton** [comment]
This doesn't appear to be a node.js problem.

**Comment by lordKnighton** [comment]
I'm gonna close this issue, but before i go. It looks like you have a good idea, but the topic is python.
Here's a link: https://github.com/python
