### ISSUE TITLE
vcbuild

### ISSUE THREAD

**Issue by jianweiqin** [nodejs/help#3250]
* **Node.js Version**:14.16.3
* **OS**:Windows 10 x64
* **Scope (install, code, runtime, meta, other?)**: build
* **Module (and version) (if relevant)**:

What do you mean by the param 'dll' in vcbuild.bat? Do you mean that will compile to a 'node.dll' file?
![1](https://user-images.githubusercontent.com/26958373/109941692-5ee4d000-7d0e-11eb-9c9a-da15136a195a.png)

And I got errors when I run:
> vcbuild.bat x86 dll

![2](https://user-images.githubusercontent.com/26958373/109941714-660bde00-7d0e-11eb-9b2b-a7fc17b3d17c.png)

>    正在创建库 out\Release\libnode.lib 和对象 out\Release\libnode.exp
> v8_libbase.lib(platform-win32.obj) : error LNK2019: 无法解析的外部符号 __imp__timeGetTime@0，该符号在函数 "public: void __thiscall v8::base::Win32Time::SetToCurrentTime(void)" (?SetToCurrentTime@Win32Time@base@v8@@QAEXXZ) 中被引用 [C:\.mount\sdb1\ides\nodejs\node-v14.16.0\libnode.vcxproj]
> v8_libbase.lib(time.obj) : error LNK2001: 无法解析的外部符号 __imp__timeGetTime@0 [C:\.mount\sdb1\ides\nodejs\node-v14.16.0\libnode.vcxproj]
> out\Release\libnode.dll : fatal error LNK1120: 1 个无法解析的外部命令 [C:\.mount\sdb1\ides\nodejs\node-v14.16.0\libnode.vcxproj]

When I run 'vcbuild.bat x86' or 'vcbuild.bat', I can both get the 'node.exe' of 32-bit and 64-bit.

**Comment by gireeshpunathil** [comment]
@jianweiqin - is this still outstanding? `LNK2001` means unresolved symbol due to a potentially missing link library; but not sure how that can happen, as the default build system does not require the user to add any libraries or anything. @nodejs/platform-windows

**Comment by jianweiqin** [comment]
Still that error. But first I really want to know what you mean by the param `dll`. Do you mean that will compile to a `node.dll` file, which can be used by an `.exe` file to run a `.js` file?
