### ISSUE TITLE
jupyterlab y nodejs. Configuration problems

### ISSUE THREAD

**Issue by akitxu** [nodejs/help#3251]
On my computer's system I have the following version of node installed.

`enri @ enri-260-p100ns: ~ $ node -v
v15.9.0`

Jupyterlab 3.08 and python 3.85 are installed in the base virtual environment, among other packages. In this same environment I have the following extensions installed

`(base) enri @ enri-260-p100ns: ~ $ jupyter labextension list
JupyterLab v3.0.8
/ home / enri / anaconda3 / share / jupyter / labextensions
        @ jupyter-widgets / jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: / home / enri / anaconda3 / share / jupyter / lab
        @ jupyterlab / plotly-extension v1.0.0 enabled X
        @ jupyterlab / translation v3.0.5 enabled OK
        jupyter-matplotlib v0.8.3 enabled OK
        jupyterlab-spreadsheet v0.4.0 enabled OK
        jupyterlab-tutorial v1.1.0 enabled OK

   The following extension are outdated:
        @ jupyterlab / plotly-extension
        
   Consider running "jupyter labextension update --all" to check for updates.
Build recommended, please run `jupyter lab build`:
    jupyterlab-spreadsheet needs to be included in build
    jupyter-matplotlib needs to be included in build`

When trying to update these extensions it returns:

`(base) enri @ enri-260-p100ns: ~ $ jupyter labextension update --all
An error occured.
ValueError: Please install nodejs> = 12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details: /tmp/jupyterlab-debug-e8lfztv1.log`

Which is contradictory with the version installed on the system, which is, as seen at the beginning of this text, v15.9.0

In the base environment I run

`(base) enri @ enri-260-p100ns: ~ $ node -v
v6.13.1`

And it returns me another version. Does this mean that I have two versions of nodejs installed, one in the system and the other in the virtual environment? Could it cause a problem to install with conda in this environment, a version> 12 to fulfill the requirement that they demand of me for the update? Or how could I configure version 15.9.0 to work in the base environment as well? I will appreciate help to solve this problem

**Comment by gireeshpunathil** [comment]
@akitxu - is this still outstanding? I don't know too much details about your environment, but an easy thing to validate the prevalent node installation in any system is to check the `PATH` environment variable, and see where, and how the node executable is being picked up.

**Comment by akitxu** [comment]
@gireeshpunathil Thanks for your interest. I have installed, starting from scrach, LinuxMint 20.2 and, since then, everything works fine for me. Kind regards

**Comment by gireeshpunathil** [comment]
good to know! closing this then, cheers!
