### ISSUE TITLE
intercept network traffic using localhost as proxy

### ISSUE THREAD

**Issue by realrecordzLab** [nodejs/help#3252]
* **Node.js Version**: 15.4.0
* **OS**: macOS 10.13.6
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http, child_process

I'm using `require('child_process').exec` to open an application from a node cli script. I'm trying to intercept the network traffic of the opened app but I've noticed that the app opened is unable to connect to internet. Is possible to intercept the traffic using `http` module and after the request is logged pass it to the internet connection so the app is able to work as expected?

**Comment by RaisinTen** [comment]
Could you please share the code?
The child process does seem to be able to connect to the internet here:
```js
// test.js
require('child_process').
  exec('node child.js').
  stdout.pipe(process.stdout);
```
```js
// child.js
require('dns').
  resolve('www.google.com', function(err) {
    if (err) {
      console.log('Not connected');
    } else {
      console.log('Connected');
    }
  });
```
```zsh
❯ node test.js
Connected
```

**Comment by realrecordzLab** [comment]
> Could you please share the code?
> The child process does seem to be able to connect to the internet here:
> 
> ```js
> // test.js
> require('child_process').
>   exec('node child.js').
>   stdout.pipe(process.stdout);
> ```
> 
> ```js
> // child.js
> require('dns').
>   resolve('www.google.com', function(err) {
>     if (err) {
>       console.log('Not connected');
>     } else {
>       console.log('Connected');
>     }
>   });
> ```
> 
> ```shell
> ❯ node test.js
> Connected
> ```

Here is the code. 

```js
#!/usr/bin/env node

const spawn = require('child_process').exec;
const http = require('http');

spawn('open "/Users/dev/Applications/Tv Go.app" --args \ --proxy-server=localhost:5000 \ --ingnore-certificate-errors', async (err, stdout, stderr) => {
    console.log(err, stdout, stderr);
});

http.createServer( (req, res) => {
    console.log(req, res);
}).listen(5050);

```
