### ISSUE TITLE
[DISCORD BOT] UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by Devcode101** [nodejs/help#3253]
* **Node.js Version**: v14.15.5
* **OS**: Windows 10
* module: google-scrapper (NPM) > https://www.npmjs.com/

code:
```
`var Scraper = require('images-scraper');

const google = new Scraper({
    puppeteer: {
        headless: true
    }
})

module.exports = {
    name: 'image',
    description: 'Sends a image to text channels',
    async execute(client, message, args){
        const image_query = args[0].join(' ');
        if(!image_query) return message.channel.send('Please enter an image name');

        const image_results = await google.scrape(image_query, 1);
        message.channel.send(image_results[0].url);
    }
}`
```

Console error:
`(node:32) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'join' of undefined`

**Comment by mollthecoder** [comment]
This may be a bug in one of the APIs you are using.

**Comment by galaxy-01-6182** [comment]
As marsonya mentioned, the issue is within `args` parameters, so far I explored discord.js library, I understand by `args` it marks the user's input with the command. If there is no input, It will be undefined Obviously. I would recommend to to check `args[0]` instead of checking `image_query`
