### ISSUE TITLE
Incremental GC calls were twice after upgrading from 12 to 14

### ISSUE THREAD

**Issue by frimuchkov** [nodejs/help#3255]
* **Node.js Version**: 14.19
* **OS**: Ubuntu 18.04

Hi!

After upgrading from node.js 12 to node.js 14 we found some problems with performance: answers became slower for 1 ms. We found that after upgrading incremental GC calls were twice.

How it's possible? And is it possible to fix this behaviour?

**Comment by frimuchkov** [comment]
> @frimuchkov - is it still outstanding? if so, do you have a test case to reproduce the issues?

Nope, we deployed node.js with pointer compression and it solved our problem

**Comment by gireeshpunathil** [comment]
closing then, cheers!
