### ISSUE TITLE
O F8 não funciona  no VSC para node.js

### ISSUE THREAD

**Issue by AMIM901** [nodejs/help#3258]
VSC :- 1.54.1

* **Node.js Version**: 12.18.3
* **OS**: Wind nt x64
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

O F8 não executa o Node do VSC 

```js
// I am an example of JS code
// please remove me too
```
-->

**Comment by tanjilk** [comment]
Experimenta abrir o terminal no vsc e use o comando `node nome_da_aplicacao.js`
