### ISSUE TITLE
Change primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/help#3259]
Refs: https://github.com/nodejs/node/issues/33864

I don't think changing the primary branch to main should affect the activity in the help repo and don't think there are any external dependencies.

Any concerns? If not I'm happy to go ahead an do the update.

**Comment by gireeshpunathil** [comment]
as such there is no code in this repo, and none of the links in the readme are pointing to any parts of the core repo, so I guess we are good!

**Comment by mhdawson** [comment]
@gireeshpunathil, in terms of links I think they will redirect anyway.  Do you want to do the rename or should I?

**Comment by gireeshpunathil** [comment]
let me do it!

**Comment by gireeshpunathil** [comment]
done - 

**before:**

![image](https://user-images.githubusercontent.com/6447530/111016449-185d3880-83d4-11eb-9ede-d641884cf572.png)

**after:**

![image](https://user-images.githubusercontent.com/6447530/111016449-185d3880-83d4-11eb-9ede-d641884cf572.png)

@mhdawson - I guess that is it?
