### ISSUE TITLE
Run .js without cmd

### ISSUE THREAD

**Issue by Skasix** [nodejs/help#326]
So there's a discord bot that runs with API and all that but I would prefer to not have to do work everytime I run the bot.js. I start node.js command prompt and type "cd C:\Stuff\Here" and once I do that I type "node bot.js". Is there a way to make a shortcut that would type those two commands after the other or make it so that I only have to click bot.js to start it without going through the whole change directory and node bot.js.

**Comment by Flet** [comment]
It sounds like you're on windows, so you should be able to create a Batch file (.bat) with those two commands in it and just double-click it to start.

1. Right-click on the Desktop and select **New > Text Document**
2. Type in a name like `runbot.bat` Note: be sure to remove the .txt at the end of the name.
3. The icon should change to look like this:

<img width="89" alt="screen shot 2016-10-16 at 10 22 59 pm" src="https://cloud.githubusercontent.com/assets/360233/19424490/30fad34a-93ef-11e6-8c85-89b3a1cb3b52.png">

4. Now, right click the file and choose **Edit**. This will open up your text editor.
5. Type your two commands in the file, each on their own line:

```batch
cd c:\stuff\Here
node bot.js
```

6. Choose **File > Save** and close the editor.
7. Thats it! Double-click the file and it should start the program!

Note: if you run it and it just flashes the command window quickly, there may be an issue. Adding a line that says `pause` to the end of the file will make the window stay up so the error can be seen.

Give it a try!

**Comment by Skasix** [comment]
When the answer is simple and you just a donkey. I thought I had to use the node.js command prompt with the proper setup so I had to use that node cmd but I didn't and I'm mentally unable. Thx for the help
