### ISSUE TITLE
Install Node.js

### ISSUE THREAD

**Issue by DavidShandor** [nodejs/help#3261]
* **Node.js Version**: node-v15.11.0-x64
* **OS**: win 10 Home 64 bit
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

Hi! I'm trying to install Node.js with the installer above, and every time got an error message :
![image](https://user-images.githubusercontent.com/65463550/110831854-53ac1a00-82a3-11eb-93b4-ea6cca9c1f4c.png)
any idea?
thnx

**Comment by yan76net** [comment]
I try to install Node.js on Win 10 64 bit too and the same error comes out. Found how to check windows installer 
https://www.r-datarecovery.com/windows-installer-service-failure.html
But it is not help me. I try uninstall and I see the same error.
I try to switch off my antivirus. It is not help to install Node.js

**Comment by DavidShandor** [comment]
> I try to install Node.js on Win 10 64 bit too and the same error comes out. Found how to check windows installer
> https://www.r-datarecovery.com/windows-installer-service-failure.html
> But it is not help me. I try uninstall and I see the same error.
> I try to switch off my antivirus. It is not help to install Node.js

I found a solution going like this:
Method: 2
Run system file checker (SFC) and see if it helps. Please follow these steps:
a. Press Windows + X keys and click command prompt (admin).
b. Type the following command in command prompt and press Enter.
sfc /scannow

this one found some corrupted files and fix them.

then I succeed to install Node.js

**Comment by yan76net** [comment]
Thanks. It worked

**Comment by marsonya** [comment]
@nodejs/build, you might want to take a look at this.
Is this something that needs looking into?
