### ISSUE TITLE
Node and Authentication

### ISSUE THREAD

**Issue by rayj00** [nodejs/help#3262]
* **Node.js Version**:  v14.4.0
* **OS**: Ubuntu 20.04 Server
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**:

I am trying to implement node authentication

```js
// I am an example of JS code

Server.js code:
```
const fs = require('fs');
const path = require('path');
const url = require('url');
var httpServer = require('http');
const auth = require("http-auth");
const basic = auth.basic(
        {
         realm: "Private Area",
         file: __dirname + "/htpasswd",
        });
...
...
function serverHandler(request, response) {

console.log("dirname = ", __dirname);
//console.log(`user = ${basic.file} + ${user}`);

    basic.check(request, response => {
            response.end(`Welcome to private area, ${basic.file} + ${username}`);

  });
```

I know I'm missing something....but what?

Thanks,

Ray

**Comment by addaleax** [comment]
Can you share what happens when you run that code?

**Comment by rayj00** [comment]
> 
> 
> Can you share what happens when you run that code?

Ironically, absolutely nothing happens!  The node server just goes on it's merry way and gets and displays the webpage.

Ray

**Comment by addaleax** [comment]
Could you maybe share your full code in that case? What webpage is being displayed?

**Comment by rayj00** [comment]
> Could you maybe share your full code in that case? What webpage is being displayed?

I am actually testing another method from https://www.dotnetcurry.com/nodejs/1237/digest-authentication-nodejs-application
I have it working but still need to figure out how to differentiate two classes of users.

Ray

**Comment by rayj00** [comment]
Actually it works for md5 but I can't get it to work for sha256?

**Comment by marsonya** [comment]
> Actually it works for md5 but I can't get it to work for sha256?

Hi @rayj00, did you find the solution for your problem?
In case you haven't, kindly share your full code if possible.
