### ISSUE TITLE
Fix: Node Ram usage in M1 macbook

### ISSUE THREAD

**Issue by sivin-git** [nodejs/help#3265]
**Describe the issue**

The node is taking lots of Ram usage in M1 Macs
Verson : 15.11.0

<img width="1020" alt="Screenshot 2021-03-17 at 12 15 22 AM" src="https://user-images.githubusercontent.com/64252451/111363390-ff93a200-86b5-11eb-816d-f1149ca544e3.png">

**Comment by addaleax** [comment]
It’s impossible to tell whether this is normal or not without having any context.

In any case, keep in mind that `Memory` and `Real Memory` are different things, and as far as availability of memory to other processes is concerned, `Real Memory` is what you want to be looking at.

**Comment by marsonya** [comment]
@sivin-git, it would be very helpful if you can provide more context and details surrounding the screenshot in your description. This will help us understand better.

**Comment by sivin-git** [comment]
> @sivin-git, it would be very helpful if you can provide more context and details surrounding the screenshot in your description. This will help us understand better.


<img width="1149" alt="Screenshot 2021-03-21 at 1 12 56 PM" src="https://user-images.githubusercontent.com/64252451/111897643-374c7200-8a47-11eb-9685-b5dde4c3351d.png">

**Comment by marsonya** [comment]
cc @nodejs/performance

**Comment by benjamingr** [comment]
@marsonya I think (?) in general we don't ping core teams in the help repo as far as I know :) Although in this case the preferred approach:

 - Get the user to provide a reproducing example of the problem and triage whether or not it's a real issue in Node.js or something the user needs help with.
 -  If it's a real issue in core (which is very possible since M1 support is new afaik) - migrate the issue to Node.js/node and ping the mac team.

**Comment by marsonya** [comment]
> @marsonya I think (?) in general we don't ping core teams in the help repo as far as I know :) Although in this case the preferred approach:
> 
> * Get the user to provide a reproducing example of the problem and triage whether or not it's a real issue in Node.js or something the user needs help with.
> * If it's a real issue in core (which is very possible since M1 support is new afaik) - migrate the issue to Node.js/node and ping the mac team.

Sorry. My bad. 
Thanks for clarifying the approach. 
I will follow it from here on.

**Comment by marsonya** [comment]
> @marsonya I think (?) in general we don't ping core teams in the help repo as far as I know :) Although in this case the preferred approach:
> 
> * Get the user to provide a reproducing example of the problem and triage whether or not it's a real issue in Node.js or something the user needs help with.
> * If it's a real issue in core (which is very possible since M1 support is new afaik) - migrate the issue to Node.js/node and ping the mac team.

On a side note, I was thinking we could document this approach in [`Triaging a bug report` section in `issues.md`](https://github.com/nodejs/node/blob/master/doc/guides/contributing/issues.md#triaging-a-bug-report).

**Comment by sivin-git** [comment]
> > @marsonya I think (?) in general we don't ping core teams in the help repo as far as I know :) Although in this case the preferred approach:
> > 
> > * Get the user to provide a reproducing example of the problem and triage whether or not it's a real issue in Node.js or something the user needs help with.
> > * If it's a real issue in core (which is very possible since M1 support is new afaik) - migrate the issue to Node.js/node and ping the mac team.
> 
> On a side note, I was thinking we could document this approach in [`Triaging a bug report` section in `issues.md`](https://github.com/nodejs/node/blob/master/doc/guides/contributing/issues.md#triaging-a-bug-report). The description you provided is quite clear and it might be helpful for anyone who wants to help with triaging in this repo.

Is there any solution to this issue?

**Comment by thanhson1994** [comment]
Nodejs team don't want to face the issue and pass the issue for mac team :)

**Comment by morja** [comment]
Same issue here.

**Comment by LizAinslie** [comment]
My m1 mac has ran out of ram twice at this rate so i can't provide a screenshot but i can definitely confirm this is *still* an issue.

Is there a flag i can set or something at the very least to limit the memory node uses? This is seriously bad.

**Comment by DevFCosta** [comment]
Any solution? I have the same problem.

**Comment by AXSJ** [comment]
Having same issue

**Comment by ntobolski-coursera** [comment]
Yeah same on m1 max 32GB. If I kill it it comes back and consume up to 8GB memory for no clear reason.
