### ISSUE TITLE
Intention of the assert package- Is it for testing or is it for sanity checks ?

### ISSUE THREAD

**Issue by bvandenbon** [nodejs/help#3266]
What exactly is the Node.js assertion package intended for ?
 https://nodejs.org/dist./v6.3.0/docs/api/assert.html#assert_assert

In java there is an `assert` keyword. This keyword is intended to put sanity checks in production code. e.g. halfway a function you could state that `assert variable > 0` . For clarity, it is not intended to be used in tests. It is intended to be used in functions. One of the advantages of using the `assert` keyword is that during production all assertion logic can be disabled. So, it is more like a sanity check that helps us while developing. It's usage can be enabled/disabled with a `--enable-assertions` flag for the java process. It also helps IDE's like IntelliJ to show more appropriate warnings to the developer.

And now, we get to Node.js. The documentation says that the `assert` is not intended to be a testing framework.
My guess is that the assert function usages are certainly not disabled in production. (nobody cares I think).

But I'm really wondering what the intention is.
Is it intended to put sanity checks in production code.
Or is it intended to be used in tests after all.

Thank you for clarifying this in advance,
Bram

**Comment by addaleax** [comment]
The original intention was using it inside Node.js’s own test suite. Practically speaking, lots of people use it in their own testing frameworks, and some (fewer but still a lot, I guess) people also use it for consistency checks in their production code.

Ultimately, this is up to you, but there’s no widespread equivalent to the Java functionality that I am aware of.

**Comment by bvandenbon** [comment]
Thank you for clarifying that. :)
