### ISSUE TITLE
Question: Does `vm.runInContext` use the same Isolate as `vm.runInThisContext`, from 8.9.4 onward?

### ISSUE THREAD

**Issue by zyrolasting** [nodejs/help#3267]
* **Node.js Version**: 8.9.4
* **OS**: GNU/Linux, Debian
* **Scope (install, code, runtime, meta, other?)**: runtime.
* **Module (and version) (if relevant)**: vm`

Question: Does `vm.runInContext` use the same Isolate as `vm.runInThisContext`, from 8.9.4 onward?

I'm reviewing a program that uses `vm.runInThisContext` under an old Node version, where `vm` is `require('vm')`. This program mutates the global object and `Module.prototype`. I was hoping to refactor the code to use `vm.runInContext` to make the code easier to extend and maintain by avoiding the mutations in the first place.

However, it is important that this program use the same underlying V8 [Isolate](https://v8docs.nodesource.com/node-0.8/d5/dda/classv8_1_1_isolate.html) for a given context, hence the initial decision to use `vm.runInThisContext`.

I looked at [node_contextify.cc](https://github.com/nodejs/node/blob/v8.9.4/src/node_contextify.cc) in 8.9.4, and it appears that the isolate is pulled from the "current" environment reference, and the isolate is fetched using `env->isolate()`. Even though that's just an accessor, it could theoretically return something else. I stopped reading at this point because it would take longer to answer my own question than to check with someone who knows off hand.

**Comment by addaleax** [comment]
> Question: Does `vm.runInContext` use the same Isolate as `vm.runInThisContext`, from 8.9.4 onward?

Yes, it has always done that and will always do that.

**Comment by zyrolasting** [comment]
Thank you.
