### ISSUE TITLE
Error while trying to Uninstall and reinstall Node.js

### ISSUE THREAD

**Issue by OverlordAnders** [nodejs/help#3268]
![node js error](https://user-images.githubusercontent.com/53455199/111504427-0655ff80-871e-11eb-82ad-e4e6e093f115.PNG)

* **Node.js Version**: 14.16.0 LTS
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**: install/uninstall
* **Module (and version) (if relevant)**:

I need to uninstall node.js because I installed it wrong I believe. I went to uninstall and it gives this error. Not sure why it's doing that. No matter what I do it won't uninstall so i can make a fresh install.

**Comment by marsonya** [comment]
This seems like a Windows registry issue. 
The solution is to remove a certain registry key in order to get it working.
But beware, as editing windows registry might cause unintended issues.

Alternatively, I would recommend posting this issue on Windows forums.
Hope this helps.
