### ISSUE TITLE
Context differences between RunInContext and RunInThisContext

### ISSUE THREAD

**Issue by zyrolasting** [nodejs/help#3269]
* **Node.js Version**: 8.9.4
* **OS**: GNU/Linux, Debian
* **Scope (install, code, runtime, meta, other?)**: runtime.
* **Module (and version) (if relevant)**: vm`

This is a follow up question to #3267. I am trying to understand the differences between [`RunInContext`](https://github.com/nodejs/node/blob/v8.9.4/src/node_contextify.cc#L675) and [`RunInThisContext`](https://github.com/nodejs/node/blob/v8.9.4/src/node_contextify.cc#L652) beyond what the names imply.

The implication is obviously that the functions only differ in what context is used. Right now I expect the contexts to differ in two ways:

1. They are different instances of the same class in the C++ runtime.
2. They may reflect different properties provided by the JavaScript caller.

Do they differ in any other way? Related question: is there any functional difference (no matter how nuanced) between calling `require('vm').runInThisContext` and using `global` for `require('vm').runInContext`?

**Comment by addaleax** [comment]
The two main differences are:

- `runInThisContext()` uses the existing context. This means that, inside the script that is run, the same global object and the same set of JS language builtins is used. 
- `runInContext()` uses a different context. The global object is different from the “main” Node.js global object, and there will be a different set of JS language builtins. This includes the fact that no Node.js APIs are available.

**Comment by zyrolasting** [comment]
So, using `global` for `runInContext` won't work the same way?

**Comment by addaleax** [comment]
@zyrolasting You’ll have to be more specific – what does “the same way” mean here?

**Comment by zyrolasting** [comment]
A program I'm responsible for modifies the prototype of the Module API, and replaces the `require` function. As in, it adjusts the APIs available to it before passing control to `runInThisContext`.

```javascript
const Module = require('module');
const vm = require('vm');

Module.prototype._load = ...

vm.runInThisContext(...);
```
This obviously causes some problems if we want to continue our analysis recursively, i.e. if the program in the VM contains nested `eval()`s. You'd have to undo or otherwise account for the mutations somehow.

Hence why I was suggesting something like:

```javascript
const Module = require('module');
const vm = require('vm');

const ctx = vm.createContext(Object.assign({}, global, {
  require: (...) => {
    // Maybe return a modified Module API, etc.
  },
});

vm.runInContext(ctx);
```

The maintainers are concerned that doing so will make it harder to dynamically analyze JavaScript programs, because some difference would make it impossible for them to make the same claims in their analyses.

If this is the case, then we need to know how to account for those differences without imperatively "resetting" the environment every time.

Does this answer your question?

**Comment by addaleax** [comment]
@zyrolasting I think the big landmines here are that a) `require` is not a global in Node.js, and code inside the inner context might be surprised by the fact that it is one in the example you’re providing, and b) that, in order to make `require()` usable inside a new context, you would essentially have to re-implement the Node.js CommonJS module system here.

**Comment by zyrolasting** [comment]
First of all, thank you for your patience. It means a lot that you would take the time to dig into this, and it's really helping us understand what to do.

> re-implement the Node.js CommonJS module system here.

With the `runInThisContext` approach we're already generating code to wrap scripts before evaluation, so that's already happening somewhat.

But I must apologize for omitting one detail, because I gave the wrong impression. We do use the original `require` in the caller's context, we just make a decision over whether to proxy the exports to monitor interactions.

```
const ctx = vm.createContext(Object.assign({}, global, {
  require: function (...args) {
    const exports = require(...args);
    return (shouldProxy) ? new Proxy(exports, ...) : exports;
  },
});
```

So I'm hoping that would at least dodge the CommonJS scope of work. My question about functional equivalence and surprises assumes that we *selectively* use the caller's context, not replace it entirely.

> require is not a global in Node.js

`global.require === require` in my REPL, so I'm a little confused here. I thought the whole point of ECMAScript was that all contact between a script and the outside world was gated by a singular object like `window` or `global`. If `require` is a property of `global`, but `require` is not a global, then I don't understand what you mean by "global".

**Comment by addaleax** [comment]
> I must apologize for omitting one detail, because I gave the wrong impression. We do use the original `require` in the caller's context, we just make a decision over whether to proxy the exports to monitor interactions.

That should be fine then, as long as you’re okay with this modified `require()` only applying to the immediate code you’re running (and not, say, nested dependencies).

> > require is not a global in Node.js
> 
> `global.require === require` in my REPL, so I'm a little confused here.

That’s the case only in the REPL, because there’s no other way to get a decent `require()` function in there, but *only* in the REPL.

Concretely, `require('./foo')` will give a different result depending on which path you call it from. That means that `require` somehow has to know which module is calling it – the way that Node.js implements this is by giving each module *its own* `require()` function.

Specifically, it wraps CommonJS module code in a function and passes its own `require` to it: https://nodejs.org/api/modules.html#modules_the_module_wrapper (this is also why you can `return;` from a CommonJS module)

**Comment by zyrolasting** [comment]
Doy, forgot about `require` being passed in that way. My bad. Consider my example mistaken then, since I'm not too worried about generating wrapping code.

So to wrap this up: if we are especially careful to always use the calling context's bindings in our overrides, and wrap modules to provide what (appear to be) equivalent module-level bindings, there is no meaningful difference between us using `runInThisContext` and `runInContext`?

**Comment by addaleax** [comment]
@zyrolasting Well... you'd still use a different set of JS builtin language objects, no matter how much you make the two globals look alike. Whether that's okay or not will depend on your use case.

**Comment by zyrolasting** [comment]
Yes, understood. Thank you for your help on this. I think that we have enough information to make a decision.

**Comment by zyrolasting** [comment]
To add on to OP: There's a difference in scoping information b/c `runInThisContext` behaves like an indirect `eval` and `runInContext` doesn't.

```
const vm = require('vm');
const str = `(function () { let a = 1; console.log(eval('a')) })()`;
eval(str);
vm.runInThisContext(str);
vm.runInContext(str, vm.createContext(global));                                        
```
