### ISSUE TITLE
"resolv.h" doesn't compile on MacOS for c++ native modules

### ISSUE THREAD

**Issue by neilxa** [nodejs/help#327]
Moved from here:

https://github.com/nodejs/node/issues/9129

**Comment by bnoordhuis** [comment]
Welcome to the wonderful world of cross-platform software development.  You can try fixing it by tweaking include_dirs in your binding.gyp or guarding the includes with `#ifdef __APPLE__`, `#ifdef __linux__`, etc.

**Comment by neilxa** [comment]
@bnoordhuis 
Thanks for your reply.

But what dir should I include here ?  the header is just system header file, and it's in the clang searching path.
What it is not found when compiling on Mac.

My code is working for nodejs 0.12 on Mac.  but not work for nodejs 4.

Can you please just take a short look at the code: 
https://github.com/neilxa/mytest/blob/master/src/mytest.cc

It's not reasonable to break on Mac.

**Comment by neilxa** [comment]
@bnoordhuis 

My code was working for years, it just broke on nodejs v4.

**Comment by neilxa** [comment]
@bnoordhuis 

The really wired issue is that:   the "resolv.h" is found,  but the type `ns_tsig_key` is not found.

`ns_tsig_key` is defined in `nameser.h`, which is included by  `resolv.h`.   
Both of the 2 header files are in system searching path.

Take a look at the error log: 
https://github.com/neilxa/mytest/blob/master/logs.txt

**Comment by bnoordhuis** [comment]
This issue has been inactive for some months now so I'm going to close it out.  Hope you got it working.
