### ISSUE TITLE
Need Node.js authentication help!

### ISSUE THREAD

**Issue by rayj00** [nodejs/help#3270]
I have a node server that I need to add authentication to.   The node server was not created with express. All the examples I am running into on the web are based on Express.

Can anyone point me to examples of Basic or Digest code for node.js that are not depended on Express?

Thanks,

Ray

**Comment by marsonya** [comment]
You can use passport.js
I understand that it might be hard to find examples without express or some other framework. But, you don't need to have express to use passport js just take any example which u find with express remove everything related to express and replace it with similar things from plain node/ or other framework.

**Comment by rayj00** [comment]
Thanks marsonya.

I am using the digest example from here:  https://thetiwari-tiwari01.medium.com/digest-authentication-in-node-js-f4ca152d4302

I have this working, however I am stuck on the credentials.  It seems this code allows for only one user?  I need to differentiate
between at least two users.  I don't know much about json,  but the credential variable only allows for one user.  Am I correct in this assumption? 

Thanks,

Ray

**Comment by marsonya** [comment]
That's right. The code in the link you shared allows for only one user. `credentials` is an object that can hold one user.
If you want to authenticate more users, you might want to store users in an `array` instead and adapt your code to handle credentials accordingly.

**Comment by marsonya** [comment]
It seems you have figured this out. I am going to close this issue now. You can always reopen it incase there is anything else.
