### ISSUE TITLE
NodeJS shows some strange behavior I do not understand

### ISSUE THREAD

**Issue by gogo9th** [nodejs/help#3271]
* **Node Version 15**:
* **Linux**:
* **execution Result**:

```
{
function a (){ console.log("Hello");}
a = 1;
console.log(a)
}
console.log(a)
a();
```

If I run this code, I get the output:

```
1
[Function: a]
Hello
```

However, I was expeting to get:
```
1
1
<error!>
```
Do you know why does the type of the variable 'a' changes to the original function once it exits the code block?

**Comment by RaisinTen** [comment]
I think this happens because of function hoisting: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting.

**Comment by Ayase-252** [comment]
I think it could be the behavior of so-called _sloppy mode ES6_ in this post: https://stackoverflow.com/a/31461615

With all the quirks with function hositing and , the code snippet is equivalent to

```javascript
// Function hoisting
var a0 = undefined
{
  // function a (){ console.log("Hello");}
  let a = function () { console.log("Hello") }
  a0 = a
  a = 1
  console.log(a) // 1
}
// a() is equivalent to
a0() // "Hello"
```

I'm not very familiar with the relevent [spec](https://262.ecma-international.org/11.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics), please correct me if I'm wrong.

**Comment by Shivamsen12579** [comment]
> I think it could be the behavior of so-called _sloppy mode ES6_ in this post: https://stackoverflow.com/a/31461615
> 
> With all the quirks with function hoisting combining block statement , the code snippet is equivalent to
> 
> ```js
> // Function hoisting, 
> var a0 = undefined
> {
>   // function a (){ console.log("Hello");}
>   let a = function () { console.log("Hello") }
>   a0 = a
>   a = 1
>   console.log(a) // 1
> }
> // a() is equivalent to
> a0() // "Hello"
> ```
> 
> I'm not very familiar with the relevent [spec](https://262.ecma-international.org/11.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics), please correct me if I'm wrong.

hii sir i need your help.i was installing node js in my laptop and suddenly stuck due to net ..now console of backend node is not runningplease help me out sir I am in great trouble. Due to this issue i am not keep forwarding my web development course.🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by Ayase-252** [comment]
@Shivamsen12579
Keep clam sir. 
I would recommend you open a new issue in this repo with description what problem you met and what you want to achieve.
