### ISSUE TITLE
Node.js v14.15.0 gives incorrect PID of child_process

### ISSUE THREAD

**Issue by 64J0** [nodejs/help#3274]
* **Version**: v14.15.0
* **Platform**: Ubuntu 20.04
* **Subsystem**:

### What steps will reproduce the bug?

Create a spawn process with shell: true and monitor it's PID. In my case I'm running a Ffmpeg script in the spawn with shell: true. Then I read the process PID with Node.js and it tells me that the PID is 8556 for example. But, if I ask the SO the PID of the ffmpeg it tells me a different value, like 8557.

### How often does it reproduce? Is there a required condition?

I've noticed it in this week, maybe in 17/03/2021 and doesn't found much information about this issue online. I think that there's no required condition.

### What is the expected behavior?

I want that Node.js tells me the correct PID of the child process created.

### What do you see instead?

A wrong PID.

### Additional information

There are some prints to illustrate the problem.

![image](https://user-images.githubusercontent.com/50725287/111820362-26252900-88c0-11eb-8894-df532e95b41c.png)

In this first picture there is the log of the child process PID informed by Node.js: 87254.

![image](https://user-images.githubusercontent.com/50725287/111820473-4fde5000-88c0-11eb-99f0-71a11f464c83.png)

In this second picture there is a print of the terminal showing the correct PID of the Ffmpeg process: 87255. To log the PID in the console with Node.js I'm using a method like this:

```javascript
const ffmpeg = spawn("ffmpeg ...", {
  shell: true
});

ffmpeg.stderr.on("data", (data) => {
  console.log(`ffmpeg PID: ${ffmpeg.pid}`);
});
```

This information is crucial for my algorithm because later the server should kill this process using the PID directly with other child_process.

**Comment by 64J0** [comment]
Hi @mscdex. In the first time I've really passed the entire command as a string like ```spawn("ffmpeg -y -i http://... -f hls ...", { shell: true, })```. But later I've tried the option to pass each flag in a field of an array, like ```spawn("ffmpeg", ["-y", "-i http://...",  "-f hls", "..."], { shell: true, })```.
Those commands results in the same wrong PID captured by Node.js.

**Comment by 64J0** [comment]
Well, maybe I've found a way to overcome this situation. The process of restart the Ffmpeg is made inside the Node program and it is controlled by a object store in Redis. My idea is to change the program to kill the process using the .kill() method if a specific value in this config object has a value like "FINISHED", so it won't need to know the correct PID of the process. This really can work... I'll test in the office this monday.

**Comment by 64J0** [comment]
I've found other people with the same problem:

* https://stackoverflow.com/questions/11646671/wrong-pid-returned-in-node-executable/14096922 -> This behaviour is the same I'm facing because the correct PID of the process is bounded to a +1 or +2 value in the OS.
* https://github.com/nodejs/node/issues/4289 -> This one was even answered by @mscdex

**Comment by 64J0** [comment]
Thank you very much @mscdex and @aduh95 for your time. I've noticed that the arguments passed to spawn in the array should not contain a blank space. To show an example, later I was doing something like this:

```javascript
const ffmpeg = spawn("ffmpeg", [
      "-hide_banner",
      "-y",
      "-vcodec copy",
     ...
])
```

As you can see, the "-vcodec copy" has a blank space between the flags. Today I tried with this other syntax and it worked without the ```{shell: true}```.

```javascript
const ffmpeg = spawn("ffmpeg", [
      "-hide_banner",
      "-y",
      "-vcodec", "copy",
     ...
])
```

Also, in my initial tests the ffmpeg in Node.js now gives the correct PID. Now I want to understand why the spawn doesn't accepts a flag with blank space, do you guys know?

**Comment by aduh95** [comment]
I think the first version is somewhat similar to `ffmpeg -hide_banner -y "-vcodec copy"`, which `ffmpeg` fails to parse.

Do you need further help or can we close this?

**Comment by 64J0** [comment]
I'll keep the issue open a little longer because doesn't tried the full algorithm here. Maybe I'll need more help when there are other process running @aduh95 . x.x

**Comment by 64J0** [comment]
Alright, everything seems to be running fine. Thank you very much again @aduh95  and @mscdex for the support, have a nice dar. I'll close the issue now with this comment.
