### ISSUE TITLE
NODE.JS / DISCORD.JS | Online member count also counts bots. > Only want members to be count it

### ISSUE THREAD

**Issue by Devcode101** [nodejs/help#3276]
Read titel ^

Is there a way that i can also filter out the bots in couting output? 

code:

`module.exports = async (client) =>{
             const guild = client.guilds.cache.get('GUILD-ID');
             setInterval(async() =>{
                 onlineCount = guild.members.cache.filter(members => members.presence.status === 'online' && 'dnd').size;
                 const channel = guild.channels.cache.get('CHANNEL-ID');
                 channel.setName(`Online Members: ${onlineCount} `);
                 console.log(onlineCount);
        } 10000);
  }`

**Comment by Ayase-252** [comment]
There is a `bot` field in `member.user` which may be helpful.

See https://discord.com/developers/docs/resources/user#user-object

**Comment by LegendaryEmoji** [comment]
this is not node.js related, you have to join discord.js support server for discord.js related help

and you have to use [filter](https://discord.js.org/#/docs/collection/master/class/Collection?scrollTo=filter) to filter bots

Tip: for checking bot you can use **user.bot** (it will return boolean) (thanks Ayase-252)
