### ISSUE TITLE
node 14.15.3 on x86-64 reporting 32 bit to npm install electron

### ISSUE THREAD

**Issue by sdetweil** [nodejs/help#3277]
electron install fails on x86-64 os

Linux raspberry 4.19.0-8-amd64 nodejs/node#1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

Official Linux ia32 support is deprecated
![ia32](https://user-images.githubusercontent.com/1498142/111876691-e4eb5280-896d-11eb-9d1e-b0d186e641bb.png)
see https://github.com/electron/electron/issues/27972#issuecomment-792968401

node was installed with 
sudo apt update
sudo apt-get install -y nodejs

**Comment by mscdex** [comment]
Executing

```console
$ file `which node`
```

should tell you what kind of node executable you have.

**Comment by sdetweil** [comment]
thanks 

but there is the binary executable, and what it reports to others..

the binary is 
```
/usr/bin/node: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=fb4c0b76094120bba4582c8501d5415d3499aec5, with debug_info, not stripped
```
but somehow electron install via npm got 32bit...  lot of layers in between

**Comment by sdetweil** [comment]
also failed on node v10.24.0

**Comment by Sylack-lab** [comment]
Weird bug
