### ISSUE TITLE
Why can't source files be specified in Binding.gyp with a wildcard?

### ISSUE THREAD

**Issue by alexp1917** [nodejs/help#3278]
* **Node.js Version**: 14, 15 (tried both)
* **OS**: ubuntu 20
* **Scope (install, code, runtime, meta, other?)**: code/runtime
* **Module (and version) (if relevant)**: node builtins

When following these docs [C++ addons: Wrapping C++ objects: https://nodejs.org/api/addons.html#addons_wrapping_c_objects](https://nodejs.org/api/addons.html#addons_wrapping_c_objects), I can't seem to refactor it to compile with the source code in a `src` folder. I instead get `Error: Module did not self-register`. I have made a repository to demonstrate the issue [here](https://github.com/alexp1917/native-addons-node-help-cpp-wrapping-objects).

Basically, I am unable to use a wildcard for specifying c++ source files (this seems like something i should be able to do). The docs say to do this:

```python
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [
        "addon.cc",
        "myobject.cc"
      ]
    }
  ]
}
```

and I was doing this and confused why it wasnt working (and started making this issue):

```python
{
  "targets": [
    {
      "target_name": "addon",
      "sources": ["src/**.cc"]
    }
  ]
}
```

And i thought it was an issue with the folder being introduced, but somehow this works:

```python
{
  "targets": [
    {
      "target_name": "addon",
      # this does not work
      # "sources": ["src/*"]
      # this does
      "sources": [
        "src/addon.cc",
        "src/myobject.cc"
      ]
    }
  ]
}
```

seems like im missing something here.

**Comment by richardlau** [comment]
Supposedly it was intentional from the original gyp authors to require the list to be explicit: https://groups.google.com/g/gyp-developer/c/rEB2aHf9Dbg

The suggestion is to use command expansion: https://chromium.googlesource.com/external/gyp/+/md-pages/docs/InputFormatReference.md#Command-Expansions

See also https://stackoverflow.com/questions/15397582/is-there-wildcard-mechanism-for-listing-sources-in-node-gyp

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
