### ISSUE TITLE
How to update Node.js on Mac? as of March 2021

### ISSUE THREAD

**Issue by wzup** [nodejs/help#3280]
* **Node.js Version**: `(current: {"node":"11.6.0","npm":"6.14.5"}`
* **OS**: MacOS Big Sur v. 11.1
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

There is no official text on how to update node.js on official https://nodejs.org/en/ site.
My question is very simple. HOW TO UDATE Node.js? I want an official way, not something strange from strange blogs out there in the Internet.

**Comment by Ayase-252** [comment]
https://nodejs.org/en/download/package-manager/

I would recommend `nvm`.
It allows you to switch btw multiple versions and offers good flexibility.

**Comment by wzup** [comment]
@Ayase-252 
Yes, they suggest it everywhere to use either `nvm` or `n` for that.
But this is what I'd like to avoid - installing more and more new tools in order to operate my current tools. Not a fan of that.

I just downloaded latest version of Node.js v15.12.0 and just installed it like the fist time. Didn't delete current version. All works well so far.
