### ISSUE TITLE
Embedding NodeJS on Windows

### ISSUE THREAD

**Issue by martin5233** [nodejs/help#3281]
* **Node.js Version**: 14.16.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime/build
* **Module (and version) (if relevant)**: -

I am trying to build an application embedding NodeJS on Windows. I have built NodeJS itself following the build instructions using MSVC 2017. The result is a working installation, at least the tests run OK, especially 'embedtest' is successful.
I try to build my application using CMake and link against node.lib generated as part of the NodeJS build. The source code itself is identical to the one shown on the [here](https://nodejs.org/docs/latest-v14.x/api/embedding.html).

My CMakeLists.txt
```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 3.17 FATAL_ERROR)

PROJECT(nodeTest CXX)

ADD_LIBRARY(node STATIC IMPORTED GLOBAL)
SET_TARGET_PROPERTIES(node PROPERTIES IMPORTED_LOCATION D:/tst/node/Debug/node.lib)

INCLUDE_DIRECTORIES(       D:/tst/node/src
                           D:/tst/node/deps/v8/include
                           D:/tst/node/deps/uv/include)

ADD_EXECUTABLE(InProcessTest main.cpp)
SET_TARGET_PROPERTIES(InProcessTest PROPERTIES
                                    COMPILE_DEFINITIONS "NAPI_VERSION=7;_UNICODE=1;V8_DEPRECATION_WARNINGS;V8_IMMINENT_DEPRECATION_WARNINGS;WIN32;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_DEPRECATE;_HAS_EXCEPTIONS=0;BUILDING_V8_SHARED=1;BUILDING_UV_SHARED=1;OPENSSL_NO_PINSHARED;OPENSSL_THREADS;FD_SETSIZE=1024;NODE_PLATFORM=win32;NOMINMAX;_UNICODE=1;NODE_USE_V8_PLATFORM=1;NODE_HAVE_I18N_SUPPORT=1;HAVE_OPENSSL=1;UCONFIG_NO_SERVICE=1;U_ENABLE_DYLOAD=0;U_STATIC_IMPLEMENTATION=1;U_HAVE_STD_STRING=1;UCONFIG_NO_BREAK_ITERATION=0;NGHTTP2_STATICLIB;DEBUG;_DEBUG;V8_ENABLE_CHECKS"
                                    COMPILE_OPTIONS "/GS;/W3;/wd4351;/wd4355;/wd4800;/wd4251;/wd4275;/wd4244;/wd4267;/Zc:wchar_t;/Gm-;/Od;/Zc:inline;/fp:precise;/GF;/WX-;/Zc:forScope;/RTC1;/Gd;/Oy-;/MTd;/FC"
                                    CXX_STANDARD 17
                                    MSVC_RUNTIME_LIBRARY MultiThreadedDebug)
TARGET_LINK_LIBRARIES(InProcessTest node)
```

I have copied all the compiler settings from the subproject 'embedtest', but not the linker settings. 'embedtest' links against a multitude of libraries, which from my understanding should be part of node.lib/node.exe.
Building my executable works without problems, but it crashes, when it invokes the first Windows system function CreateEvent called from uv__once_inner. To me it looks like the library import does not work this way, but I haven't found any information on the build settings for an embedding application on Windows.
Any help would be appreciated.

**Comment by PoojaDurgad** [comment]
@nodejs/build

**Comment by mhdawson** [comment]
@joaocgreis

**Comment by GreenGary** [comment]
I can confirm issues reported here.  

Sample code is working on Linux (CentOS) platform, but on Windows we get the behavior reported here. I also tried several other NodeJS versions without success (15.8 faces same issue, 13.x cannot be used with the sample code, because API changed). CreateEvent can be called from my main application without issues, but not from within node lib; if I skip CreateEvent call crashing (using the debugger), the application simply crashes on the next system call.

**Comment by martin5233** [comment]
Any chance for help on this one?
