### ISSUE TITLE
error code ERR_CL_SPACE

### ISSUE THREAD

**Issue by prettydiff** [nodejs/help#3284]
* **Node.js Version**:  15.6.0
* **OS**:  Windows 10
* **Scope (install, code, runtime, meta, other?)**:  runtime
* **Module (and version) (if relevant)**:  error generated by attempting to brotli decompress

```js
//  how I compress
const compress = vars.node.zlib.createBrotliCompress({
        params: {[zlib.constants.BROTLI_PARAM_QUALITY]: 7}
    }),
    readStream = fs.ReadStream(data.file_location);
readStream.pipe(compress).pipe(serverResponse);

// how I decompress
const decompress = zlib.createBrotliDecompress(),
    writeStream = fs.createWriteStream(filePath);
fileResponse.pipe(decompress).pipe(writeStream);
// fileResponse is of type IncomingMessage as an argument from a callback of an HTTP client request
```

The code is file is located at https://github.com/prettydiff/share-file-systems/blob/user/lib/terminal/fileService/serviceCopy.ts

I am receiving error code ERR_CL_SPACE when performing a brotli decompress on a stream passed through a proxy.  It works in reverse such that the remote requests files from my local computer, but fails when my local computer requests files from the remote.  There is a device between these two directing traffic.  The problem is confirmed limited to Brotli as the transfer works correctly on multiple files without compression and I can verify everything is correct with hashes.  The local computer is Windows 10 and all the remote computers are Ubuntu VMs.  The proxy is one of those Ubuntu VMs running this application.

The means to reproduce this error are by running the user test automation scenario, which requires 5 devices (I use 4 VMs).  Four of those will listen for tests with command: `node js/application test_browser mode:remote` while the primary device runs the tests with `node js/application test_browser mode:user`.  I know this is complicated to reproduce, but its a serverless peer-to-peer (point-to-point) application and so it is a bit more challenging to test.

**Comment by prettydiff** [comment]
Upon further research this seems to be related to the Brotli library and not node:

https://github.com/google/brotli/blob/master/c/include/brotli/decode.h#L76

Unfortunately that is the only mention of CL_SPACE in all of google/brotli.  Still looking.

**Comment by eustas** [comment]
Hi. Could you check that the result of compression is the same as what is passed to decompressor? E.g. that any digest of both and compare. Proxy could do crazy things with traffic unless it is opaque (i.e. https).

**Comment by prettydiff** [comment]
I am attempting to add hashing after compression and before decompression, but the code change is breaking node without any error messaging.  I am looking at this.

**Comment by prettydiff** [comment]
So providing hashing for the compressed state did not work and that could be some undocumented state with Node's stream handling or I am just doing something wrong.  Considering the state of node's error messaging for absolutely everything the lack of error messaging in this case suggests the problem is not my code.

As for the real problem there are two possibilities:

* There is a data padding problem with Node stream handling.  Node streams are composed of data type Uint8Array as the representation of binary data.  I believe this is the least likely scenario because Node stream handling even through proxies is common.
* More probably is that there is a data formatting error with Brotli between operating systems.  I consider this the more likely scenario because in my test automation compressed file copy via relay works from Windows to Linux (user test 61) but fails on compressed copy via relay from Linux to Windows (user test 69).  The problem is specific to decompression on Windows.

**Comment by eustas** [comment]
Brotli relies on the fact that input/output consists of 8-bit binary values. If anything happens to values of those bytes between compression and decompression - there is nothing brotli could do to fix that...

**Comment by prettydiff** [comment]
This is the data format Node uses to stream binary: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array

I don't have any integrity issues in either direction when I turn Brotli off.  Forcing Brotli off in my application universally is as simple as adding `data.brotli=0;` to the end of https://github.com/prettydiff/share-file-systems/blob/user/lib/terminal/fileService/serviceCopy.ts#L456

**Comment by eustas** [comment]
As you mentioned in the issue description, there is a proxy. It might alter the payload... Especially that explains why directionality matters - there is no need for filtration for outgoing traffic, while incoming might look "suspicious" to proxy...

**Comment by prettydiff** [comment]
The proxy isn't there to filter traffic for security.  It is there for redirection to bypass the network limitations of NAT and simultaneously suppress identity much like NAT without need for server or third party service.  The application is strictly point-to-point which is otherwise not a viable option on today's internet.

**Comment by prettydiff** [comment]
Anybody reading I have closed the issue I opened with Google/brotli - https://github.com/google/brotli/issues/894#issuecomment-805314805

I will pursue this as a defect with Node - https://github.com/nodejs/node/issues/37891
