### ISSUE TITLE
HIGH CPU   when  using   for-await/async-generaor

### ISSUE THREAD

**Issue by navegador5** [nodejs/help#3285]
* **Version**:  tested on v15.8.0.  and v16.0.0-pre
* **Platform**: ubuntu
* **Subsystem**: fs

### What steps will reproduce the bug?

I am NOT  sure if the below  usage is CORRECT .

```
const fs = require("fs");

async function * async_gen_from_file(fn,encoding="utf8") {
    let rs$=fs.createReadStream(fn,{encoding:encoding});
    for await (let chunk of rs$) {
        for(let ch of chunk) {
            yield(ch);               //my application need to pass the char-after-decoding  
        }
        chunk = null;
    }
    await rs$.close();
    await rs$.destroy();
    rs$ = null;
}
```

```
//just use a big file,such as snap-shot or prof-file to test
/*

@##ls -l
total 267248
-rw-r--r-- 1 root root      617 Mar 23 05:09 big.sync.tst.js
-rw-r--r-- 1 root root 82527857 Mar 24 05:44 Heap-20210324T134015.heapsnapshot =============>
-rw-r--r-- 1 root root      593 Mar 24 05:38 high-cpu.js
-rw-r--r-- 1 root root  5200201 Mar 24 04:45 isolate-0x55746114c8a0-50308-v8.log
-rw-r--r-- 1 root root  4139147 Mar 24 04:38 isolate-0x5b63a10-50250-v8.log
-rw-r--r-- 1 root root     1005 Mar 24 05:25 mem-leak.js
-rw-r--r-- 1 root root    60547 Mar 24 04:40 processed.txt
-rw-r--r-- 1 root root 72942078 Mar 24 04:45 s2.json=======================================>
-rw-r--r-- 1 root root 26345709 Mar 23 05:44 svelte-compiler-3.15.0.json
-rw-r--r-- 1 root root  9452583 Mar 24 03:17 svelte.json
-rw-r--r-- 1 root root 72942078 Mar 24 04:45 tmp.json

*/
```

```
var ag = async_gen_from_file("./Heap-20210324T134015.heapsnapshot");
var fake_char_stream_parser; 

(async () => {
    for await (let ch of ag) { 
        fake_char_stream_parser = ch;  //pass the char one-by-one to another  function ...
    }
    console.log("finished,the last char is :  ",fake_char_stream_parser)
})();
```

```
top - 05:45:05 up 54 days, 12:37,  8 users,  load average: 0.38, 0.19, 0.17
   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 50640 root      20   0  645380  54364  30212 R 98.0  2.7   0:11.88 node   
 ===============>VERY HIGH CPU, MEM is OK. 
```

### How often does it reproduce? Is there a required condition?

always  when using  async-generator

### What is the expected behavior?

since using ASYNC ,  i think the CPU should NOT  so HIGH

### What do you see instead?

top - 05:45:05 up 54 days, 12:37,  8 users,  load average: 0.38, 0.19, 0.17
   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 50640 root      20   0  645380  54364  30212 R 98.0  2.7   0:11.88 node   
 ===============>VERY HIGH CPU, MEM is OK.

**Comment by addaleax** [comment]
> since using ASYNC , i think the CPU should NOT so HIGH

What @sz-coder says -- you're still in a single-threaded, JS-only environment here. async operations are great for performance when you can actually offload things like I/O from the main thread and don't have to actively wait for them to end, but that's far from the case here. You're just creating a massive amount of work for the CPU by passing characters one-by-one, wrapping them in Promises, then unwrapping them, and concatenating them one-by-one again.

**Comment by navegador5** [comment]
@addaleax , thanks for the explanation.  

Maybe I did NOT  describe it clearly:   please see below:

If  did  NOT  use   for-await,   
instead , just  use a normal-loop,  and with  sync-style  code, the CPU  only  35%, 
 i can NOT understand   why  for-await  always nearly 100%;

```
var big_str= fs.readFileSync("./Heap-20210324T134015.heapsnapshot").toString()
> big_str.length
82527857
>
var fake_handler;
for(let ch of big_str) {fake_handler =ch;}

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 52281 root      20   0  798240 132448  31924 R 35.1  6.6   2:34.14 node==============>only 35%



```

**Comment by sz-coder** [comment]
@addaleax already did an excellent job explaining why you're seeing such a high CPU load.

Async isn't a free performance boost, it comes with a small cost.

Since you're using async for each character read, this cost quickly accumulates and instead of getting the performance boost ASYNC definitely _can_ offer, you're making the CPU do **UNECESSARY** work.

To summarize:

> I am NOT sure if the below usage is CORRECT .

The answer is: No, this is not a valid usage of async.
