### ISSUE TITLE
Nodejs server is making a request by itself.

### ISSUE THREAD

**Issue by soonJ817** [nodejs/help#3287]
* **v6.11.0**:
* **CentOS Linux release 7.6.1810 (Core)**:
* **runtime**:
* **express - Router (express@4.0.39), express-async-wrap@1.0.0**:

I'm not sure this is Node.js problem, but I have a question.
I clicked a button to send a POST request from Angular Client, and Node + express server received this request.
In this api, there was a long Promise handled function, so 2 minutes later, I expected this request socket will be destroyed as https://nodejs.org/docs/latest-v6.x/api/http.html#http_server_settimeout_msecs_callback

But for some reason, socket was not destroyed, and server received the same request.
This request repeated every 2 minutes until sending response or closing session with client.

I logged these request headers to find out some differences or errors but they were exactly the same except the request time.
How could it happend?

```ts
import { Router } from 'express';
import * as wrap from 'express-async-wrap';

const route = Router();
route.post(`${URL}`, wrap(callback));
```

**Comment by RedYetiDev** [comment]
Hi! This looks like an issue with **express**, and not **Node.js**. I suggest reaching out to them before filing a issue here.
