### ISSUE TITLE
node install

### ISSUE THREAD

**Issue by hqzhu0913** [nodejs/help#329]
node-6.8.1 already installed, it's just not linked.

when i try brew link node, it shows Error: Could not symlink share/systemtap/tapset/node.stp
/usr/local/share/systemtap/tapset is not writable.

**Comment by bnoordhuis** [comment]
You may have more luck reporting that to the homebrew project.

**Comment by lordKnighton** [comment]
[link😄  ](http://stackoverflow.com/questions/31374143/trouble-install-node-js-with-homebrew) 

If the link doesn't help, reopen & we will go from there.
