### ISSUE TITLE
Can I call the native console.log function from a WASI WASM module

### ISSUE THREAD

**Issue by arthurgreef** [nodejs/help#3290]
* **Node.js Version**:15.12.0
* **OS**:ubuntu
* **Scope (install, code, runtime, meta, other?)**:runtime
* **Module (and version) (if relevant)**:

I have a WASM module and I would like to call the nodejs console.log function. Can I call javascript functions from WASM? Thanks.

**Comment by addaleax** [comment]
You can call JS functions when you pass them in as an import to the WASM module.

For WASI specifically, you do have access to the classic C stdio from inside the WASI module, through the standard file descriptors, so you can use that as well. (WASI only supports file descriptors at this point, though.)

**Comment by arthurgreef** [comment]
Thanks. I found that println!("something") works when I have no code exceptions but when I do have one I get no messages sent to std out. Any ideas how I can get println to flush?
