### ISSUE TITLE
Updated dubnium-alpine3.11 tag leads to the problem with "sharp" npm module

### ISSUE THREAD

**Issue by krabradosty** [nodejs/help#3291]
## Environment

* **Platform**: AWS Fargate 1.4.0
* **Docker Version**: N/A
* **Node.js Version**: dubnium
* **Image Tag**: dubnium-alpine3.11

## Expected Behavior

`sharp` npm module worked properly before `node:dubnium-alpine3.11` image was updated recently
## Current Behavior

After nodejs image tagged with dubnium-alpine3.11 was updated 4 days ago in docker hub, `sharp` npm module causes errors during runtime:
```
Error:
Something went wrong installing the "sharp" module
Error relocating /usr/lib/libvips.so.42: g_date_time_format_iso8601: symbol not found
Remove the "node_modules/sharp" directory then run
...
```

## Steps to Reproduce

- Get into the docker container shell based on the `node:dubnium-alpine3.11` image

- Install `sharp` module using npm 

- Run any nodejs script which requires `sharp`

**Comment by Ayase-252** [comment]
Could you provide a minimal dockerfile to reproduce the issue?
