### ISSUE TITLE
Impossible to decompress file inside memory

### ISSUE THREAD

**Issue by HerissonMignion** [nodejs/help#3292]
**Is your feature request related to a problem? Please describe.**
I am building my own search engine for fun. I have so many indexed websites that i need to store them compressed with deflate. I have 2 programs/scripts : one is the server, the other one is a web crawler. My problem is with the crawler. Before the crawling begin, i have to know which websites it has already indexed. Therefore i need to decompress my files synchronously. However i can't figure out how to do pipe things synchronously, and i can't figure out how to decompress the files while keeping the decompressed content inside my memory. It seems like i can only send the decompressed stream into another file then read that file. It's a step that could be avoided but i can't find how. I have tried "memory-streams" with npm but i get an error i don't understand.

**Describe the solution you'd like**
Anything sync, that can be done inside memory, not third party, within 5 hours of googling.

**Describe alternatives you've considered**
Going full c#

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
