### ISSUE TITLE
nodejs with playwrght

### ISSUE THREAD

**Issue by Afoxcute** [nodejs/help#3293]
Is it possible to run a aws lambda function using nodejs with playwright?

If its possible, can you guide me or provde links on how to do it?

**Comment by benjamingr** [comment]
> Is it possible to run a aws lambda function using nodejs with playwright?

Yes, but it is hard since it means running chrome in single-process mode so don't expect this to be very smooth. Some companies (like WiX) run this configuration (with puppeteer which is pretty close).

You can use something like https://github.com/JupiterOne/playwright-aws-lambda

**Comment by Afoxcute** [comment]
@benjamingr Thank you very much for your response, Actually, the link you sent is for python but its fine....I already deployed the code to aws lambda. The issue I am having now is how to launch firefox using my aws lambda function.....Please suggest for me.

Thank you in advance.

**Comment by benjamingr** [comment]
Is there any reason you're not asking the Playwright people that :)? None of that is Node.js specific

**Comment by RedYetiDev** [comment]
*(closing, as this is an issue with playwright, not Node.js)*
