### ISSUE TITLE
Can I donate lexical information to new Contexts?

### ISSUE THREAD

**Issue by zyrolasting** [nodejs/help#3294]
* **Node.js Version**: 8.9.4 to LTS
* **OS**: GNU/Linux, Debian
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: vm

The docs show that `vm.runInContext` does not share the same scopes as the main Context, meaning that it alone cannot see local variables with `eval`.

```js
const vm = require('vm');
const str = `(function () { let a = 1; console.log(eval('a')) })()`;
eval(str);
vm.runInThisContext(str);
vm.runInContext(str, vm.createContext(global));
```

The last line in this example fails with a `ReferenceError`. I'd like to replace that last line with a function that behaves like `runInContext`, such that the main context donates its lexical information to the given context.

Why? For dynamic analysis. My goal is to wrap `global` in a `Proxy` to dynamically analyze runtime behavior, without worrying about breaking the runtime's treatment of `eval`.

The below hypothetical code shows my intentions.

```js
const vm = require('vm');
const str = `(function () { let a = 1; console.log(eval('a')) })()`;
eval(str);
vm.runInThisContext(str);

// hypothetical
runInDerivedContext(str, new Proxy(vm.createContext(global), {
  /* Install monitoring stuff, knowing that eval will still print 1. */
});
```

Right now the options seem to be:

* "Pass" a new global object (which won't actually end up being that) to code used with `runInThisContext`
* Rewrite all variable declarations to global assignments for code used with `runInContext`

Is a less error-prone solution possible with a C++ addon, ideally leading back to v8.9.4? If so, has it already been done?

**Comment by addaleax** [comment]
I think the problem here is that the `eval` inside the context is taken from the global object of the *outer* context. If you update your Proxy to act as if `eval` wasn’t a property that’s present, I think this should actually work just fine.

(You can do a simple test by deleting `eval` manually:

```js
const vm = require('vm');
const str = `(function () { let a = 1; console.log(eval('a')) })()`;
delete global.eval;
vm.runInContext(str, vm.createContext(global));
```
)

**Comment by zyrolasting** [comment]
Wow! You're awesome. So contexts have a parent/child relationship? Where can I do some more reading on why this works?

**Comment by addaleax** [comment]
@zyrolasting It’s not V8 – it’s you that’s specifically providing the properties of the outer context to the inner context by using `vm.createContext(global)`. It’s the same for all other globals as well:

```js
// Uses 'Array' global
> vm.runInContext('new Array()', vm.createContext(global)) instanceof Array
true
// Uses context’s own Array constructor
> vm.runInContext('[]', vm.createContext(global)) instanceof Array
false
```

**Comment by zyrolasting** [comment]
Yes, I understood that much. I think I'm seeing what I didn't understand, and it comes down to this paragraph in the [`createContext` docs](https://nodejs.org/api/vm.html#vm_vm_createcontext_contextobject_options) (one bit bolded by me):

> If given a contextObject, the vm.createContext() method will prepare that object so that it can be used in calls to vm.runInContext() or script.runInContext(). Inside such scripts, the contextObject will be the global object, retaining all of its existing properties but **also having the built-in objects and functions any standard [global object](https://es5.github.io/#x15.1) has. Outside of scripts run by the vm module, global variables will remain unchanged.**

I thought that the inner context was _totally dependent_ on the JS object provided, such that even `[]` would fail if the second `runInContext` argument didn't provide `Array`.

---

That being said, there is one other thing that's bugging me. I'd like to track calls to `eval` in the inner context, hence the broad `Proxy`. If merely adding `eval` to the context object is enough to force the inner context to lose access to its own lexical information, then that seems to mean that I can only ever monitor what that `eval` is _doing_ when it interacts with other properties of the proxy, but I wouldn't be able to notice when `eval` itself was called. Is there a way to close that gap, so to speak?

**Comment by addaleax** [comment]
> Is there a way to close that gap, so to speak?

https://tc39.es/ecma262/#sec-function-calls-runtime-semantics-evaluation – you’re only going to get normal eval semantics if you actually provide the built-in `eval` method for the given context, as I understand it.

**Comment by zyrolasting** [comment]
Alright, I think that gives me enough to go on. Thank you again for all of your patience on this.
