### ISSUE TITLE
Question: Understanding How C++ layer talk to JS layer of Node.js

### ISSUE THREAD

**Issue by Darkripper214** [nodejs/help#3299]
As a C++ beginner, I'm trying to wrap my head around how the connection between C++ from `src/`  an JS from `lib/internal`. And how it all comes together in bootstrpping of nodejs `src/node.cc`.

I find this http://lanceball.com/process-bindings/#/1 and the Readme.md in `src/` helpful, but it kind of confusing. I hope to get an overall understand of how this works as there is little documentation on it (Or I'm searching using the wrong keyword here, most of article stops at saying `process.binding` or `internalBinding` is the bridge. 

For example in `lib/internal/async_hooks.js`

```Javascript
const {
  ArrayPrototypePop,
 ...
  Symbol,
} = primordials;

const async_wrap = internalBinding('async_wrap');
const { setCallbackTrampoline } = async_wrap; 
```
I understand that `setCallbackTrampoline` destructed from `internalBinding('async_wrap')` is actually calling the C++ function in `async_wrap.cc`

``` C++
void AsyncWrap::SetCallbackTrampoline(const FunctionCallbackInfo<Value>& args) {
  Environment* env = Environment::GetCurrent(args);

  CHECK(args[0]->IsFunction());

  env->set_async_hooks_callback_trampoline(args[0].As<Function>());
}
```

and this line is setting the method somehow.
```C++
Environment* env = Environment::GetCurrent(context);
  Isolate* isolate = env->isolate();
  HandleScope scope(isolate);
env->SetMethod(target, "setCallbackTrampoline", SetCallbackTrampoline)
```
The `env` is supposed to be the `Node.js` instance while `isolate` is the JS engine instance` . This is where I totally lost it.

Furthermore, I understand that `BaseObject` is the abstraction for tying C++ and JS object. How is this possible? Like are we accessing some part of the memory to retrieve the data, then do some checking to ensure it is right and proceed to use it?

Thank you in advance.

**Comment by benjamingr** [comment]
Hey, so I think the best way to understand this is probably to use the V8 API yourself. The embedding guide V8 has is pretty good and goes over these concepts and should answer your questions. https://v8.dev/docs/embed

**Comment by Darkripper214** [comment]
I'm trying to use V8 API to understand this. The difficulty is definitely there. I'm thinking it would be great if someone could share this knowledge as there is not much info out there.

Will try to work on it and ask again.

**Comment by benjamingr** [comment]
Did you read the embedding guide above?

**Comment by addaleax** [comment]
> The `env` is supposed to be the `Node.js` instance while `isolate` is the JS engine instance` . 

That’s correct, yes :+1: 

> Furthermore, I understand that `BaseObject` is the abstraction for tying C++ and JS object. How is this possible? Like are we accessing some part of the memory to retrieve the data, then do some checking to ensure it is right and proceed to use it?

There’s a two-way tie between the two:

- The JS object has what V8 calls an “internal field”, basically a hidden property that contains a pointer. In our case, it contains a pointer to the `BaseObject*`.
- The `BaseObject*` has a `v8::Global` handle (not actually related to anything like the global object or the global scope!) to the JS object, which it can use to refer to the JS object from C++.

**Comment by Darkripper214** [comment]
@addaleax Thank you for the explanation.
@benjamingr Yeap, but I felt like I wasn't really getting the explanation from V8 as my C++ isn't that great.

I'm taking some time off to touch up my C++ before coming back to this.
