### ISSUE TITLE
Sending Multicast Messages not working in linux

### ISSUE THREAD

**Issue by kae24** [nodejs/help#330]
Tested against linux node version 5.5, 6.7, 6.9
Same code test on Windows 7, node version 6.7 and multicast message is received.

Throws error:
```
{ [Error: send ENETUNREACH 239.1.1.1:8989]
  code: 'ENETUNREACH',
  errno: 'ENETUNREACH',
  syscall: 'send',
  address: '239.1.1.1',
  port: 8989 }

```
I did test if machine is able to send multicast using python

code below:

```
var dgram = require('dgram');
var socket = dgram.createSocket('udp4');
var multicastip = "239.1.1.1";
var cnet = "172.16.110.61";
socket.bind(function() {
    // set multicast
    socket.setBroadcast(true);
    socket.setMulticastTTL(128);
    // set hosts
    socket.addMembership(multicastip, cnet);
});
setTimeout(function() {
    var message = "Hello";
    socket.send(message, 0, message.length, 8989, multicastip, (err) => {
        console.log(err);
    });
});
```

**Comment by bnoordhuis** [comment]
That ENETUNREACH error comes from the kernel.  Try tracing your node and python script with strace to see what node and python do different.

**Comment by kae24** [comment]
Another issue, associated to multicast, though I didn't want to make another issue ticket.
On Ubuntu 16.04 using node 5.5. 6.7, 6.9. 

With two networks 10.40.1.1 and 172.16.110.1.
After the addMembership call, the multicast message received is always from the 10.40.1.1 adapter not the 172. The message is only correctly sent from 172.16 when 10.40 is disabled

**Comment by kae24** [comment]
python code
```
import socket

MCAST_GRP = '239.1.1.1'
MCAST_PORT = 8989
addr = "172.16.110.30"

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton(addr))
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 128)
sock.sendto("robot", (MCAST_GRP, MCAST_PORT))
```


python strace:
```
socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 3
setsockopt(3, SOL_IP, IP_MULTICAST_IF, [510529708], 4) = 0
setsockopt(3, SOL_IP, IP_MULTICAST_TTL, [128], 4) = 0
sendto(3, "robot", 5, 0, {sa_family=AF_INET, sin_port=htons(8989), sin_addr=inet_addr("239.1.1.1")}, 16) = 5
```

node strace:
```
bind(9, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
setsockopt(9, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
setsockopt(9, SOL_IP, IP_MULTICAST_TTL, [128], 4) = 0
setsockopt(9, SOL_IP, IP_ADD_MEMBERSHIP, {imr_multiaddr=inet_addr("239.1.1.1"), imr_interface=inet_addr("172.16.110.30")}, 8) = 0
sendmsg(9, {msg_name(16)={sa_family=AF_INET, sin_port=htons(8989), sin_addr=inet_addr("239.1.1.1")}, msg_iov(1)=[{"Hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5

```

**Comment by santigimeno** [comment]
> With two networks 10.40.1.1 and 172.16.110.1.
After the addMembership call, the multicast message received is always from the 10.40.1.1 adapter not the 172. The message is only correctly sent from 172.16 when 10.40 is disabled

Maybe I'm wrong, but I think `addMembership` doesn't have to do with the origin address but with which group you are joining and in which interface are you going to receive the multicast messages.
Have you tried binding the socket to your `172.16.` address?

**Comment by kae24** [comment]
Yep, that did the trick. 
Ahh stupid mistake. 

Thanks for the help!
