### ISSUE TITLE
Conditional Statement: Using AND and OR in node js if statement

### ISSUE THREAD

**Issue by chuksgpfr** [nodejs/help#3300]
I need to understand why this doesn't work 

```js
if(x%2 === 0 && y%2 === 0){
 ...
}
```

But this works.

```js
if((x%2 === 0) && (y%2 === 0)){
 ...
}
```

The first works in languages like java and c#.
If this needs to be worked on, I'd LOVE to CONTRIBUTE to it.

**Comment by Ayase-252** [comment]
Hello, 

I see the first example works

```
let x = 2
let y = 2
if (x % 2 === 0 && y % 2 === 0) {
  console.log("both are even")
}
```

```
node index.js 
both are even
```

What do you want to do? Could you please provide your goal?

**Comment by chuksgpfr** [comment]
I was solving an algorithm question where i was suppose to 
1. print fizz if the number passed into is a multiple of 3 and not 5 
2. prints fizzbuzz if the number is a multiple of 3 and 5
3. prints buzz if it's a multiple of 5 and not 3

**Comment by Ayase-252** [comment]
Just solve your first question

```js
function printFizz(num) {
  if(num % 3 === 0 && num % 5 !== 0) {
    console.log('fizz')
  }
}

printFizz(3) // fizz
printFizz(4) // nothing to print
printFizz(15) // nothing to print
```

You can take this as a propotype to explore another questions
