### ISSUE TITLE
Node 12 fs.createReadStream giving promise as a response

### ISSUE THREAD

**Issue by Surajsdalvi** [nodejs/help#3301]
I am using node 12 to run my application and I am using the fs.createReadStream() method to create a readable stream. The code is running fine in node 10. but in node 12 it gave me the following response:

```js
Promise {
  _handler: Pending {
    consumers: undefined,
    receiver: undefined,
    handler: undefined,
    resolved: false
  }
}
```

sample code
```js
var fs = require('fs')
var getDimension =  function (path) {
let stream = fs.createReadStream(path)
 console.log("Stream:",stream)
}

getDimension('/tmp/YBXXvSKRTKbz7P1eV9jG0cbsF.png')
```

can any one help me here to understand what is wrong here?
why it is giving me this resposne?

**Comment by Surajsdalvi** [comment]
Help me here to fix this

**Comment by addaleax** [comment]
Is this the *full* script that you are running? What command are you using to run it?
