### ISSUE TITLE
Building NodeJS with a shared v8

### ISSUE THREAD

**Issue by fmoraes74** [nodejs/help#3302]
It is possible to build node to use the embedded deps for v8 but built as a shared library? Seems like node always wants `v8` to be built as a static library but I want it to use `v8` as shared library.

**Comment by addaleax** [comment]
> I guess the reason is that many of those components are packages as part of the OS, based on specific distributions, and v8 is not incldued in any OS.

One main reason is that Node.js also liberally applies patches against V8 and is unlikely to build or link successfully against a precompiled, unpatched version of V8.

**Comment by richardlau** [comment]
It used to be possible a long time ago but was removed (https://github.com/nodejs/node/pull/1331) due to issues with compatibility between different versions of V8 (which does not follow semantic versioning).
