### ISSUE TITLE
Issue with nickname command discord.js

### ISSUE THREAD

**Issue by ItsGamingTube** [nodejs/help#3305]
Node.js Version: Idk
OS: N/A (Repl.it hacker plan)
Scope (install, code, runtime, meta, other?): code
Module (and version) (if relevant):

My command is not working i tried a lot i also searched on google and nothing works pls help i also don't have a command handler.

Here is my code:

  if(command === `nick`) {
        if(!message.mentions.users.first()) return message.channel.send("You didn't specify a user!");
         const user = message.mentions.members.first();
         var newNickname = args.slice(2).join(" ");
         user.setNickname(newNickname);
  }

Thanks in advance!

**Comment by marsonya** [comment]
Hi, can you share your full code. It's hard to understand the problem from the snippet.

**Comment by ItsGamingTube** [comment]
> Hi, can you share your full code. It's hard to understand the problem from the snippet.
I can't cuz it's a big code i don't have a command handler

**Comment by marsonya** [comment]
It's not possible to figure out the issue without having the context this snippet runs in.
I would suggest filing this issue on [Discord.js Github](https://github.com/discordjs/discord.js) since they can understand the context of your code snippet and help you with the problem.

**Comment by marsonya** [comment]
I hope the answer was helpful. This issue has been open for a long time now so I am going ahead and closing it. Feel free to reopen if necessary.
