### ISSUE TITLE
Differences in setting NODE_ENV before of after starting Node.js process

### ISSUE THREAD

**Issue by ArthurKa** [nodejs/help#3306]
* **Node.js Version**: latest
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: runtime

Are there any differences for Node process between setting NODE_ENV to production like
```
{
  "scripts": {
    "start": "NODE_ENV=production node app.js"
  }
}
``` 
or 
```
{
  "scripts": {
    "start": "node -r dotenv/config app.js"
  }
}
``` 

I mean setting NODE_ENV=production right before running Node.js process will lead to different behaviour than setting it right after Node.js start?

**Comment by Ayase-252** [comment]
It depends what your app is doing. Some app may relay on `NODE_ENV` to determine which enviroment it is in (like `development` or `testing` or `production`) then pick up a configration for that enviroment. But it is really an application behavior, Node.js remains same whatever `NODE_ENV` is.

 FYI, `NODE_ENV` can be access by `process.env.NODE_ENV`.

**Comment by ArthurKa** [comment]
Does Node.js' behavior itself depend on NODE_ENV variable?

**Comment by addaleax** [comment]
@ArthurKa No. It’s only a convention in the ecosystem, Node.js itself does not rely on it.

**Comment by ArthurKa** [comment]
Thanks!
