### ISSUE TITLE
Node.js for dummy

### ISSUE THREAD

**Issue by toba1812** [nodejs/help#3307]
* **Node.js 12**:
* **Windows 10**:
* **Document**:
* **Module (and version) (if relevant)**:

Hello,

I have very little knowledge about programming, and would like to learn javascript.
Where can I find a document about some basic things such as: where to write the script, how to run the script, etc.
Basically, I need help on very basic stuff.

Thanks

**Comment by marsonya** [comment]
Hi @toba1812 - Welcome to the world of programming.
I would suggest W3Schools ([https://www.w3schools.com/default.asp](https://www.w3schools.com/default.asp)).
It will help you learn Javascript along with other languages like HTML and CSS.
The Tutorials are well suited for beginners and they are documented with amazing examples and live playgrounds.

I hope this helps you getting started :)

**Comment by vsemozhetbyt** [comment]
See also https://eloquentjavascript.net/ and https://javascript.info/

**Comment by marsonya** [comment]
I hope the answers were helpful. This issue has been open for a long time now so I am going ahead and closing it. Feel free to reopen if necessary.
