### ISSUE TITLE
has default heap memory size change to 4GB in nodejs 14 (vs 2GB in nodejs 12) ? I

### ISSUE THREAD

**Issue by kumarrishav** [nodejs/help#3308]
I expected it to be part of some release blog. I couldn't find it anywhere. Did I miss something? Apps (running multiple processes) could have crashed if it goes unnoticed. 

* **Node.js Version**: 14
* **OS**: Mac os
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by gireeshpunathil** [comment]
no, as far as I know. do you have data to share or code to look at?

**Comment by gireeshpunathil** [comment]
ok, I see what you are saying. I don't know about this change, and I kind of agree with you that it deserves a doc.

/cc @nodejs/v8 - do you know if the default heap size was changed between v12 and v14, and if so, what do you think of documenting that change?
