### ISSUE TITLE
How to handle request disconnect in an node/express app

### ISSUE THREAD

**Issue by prashathsenthil** [nodejs/help#331]
I have an express/node app and I would like to run a function to perform an action when there is an unexpected interruption in the connection. I tried the following:

`req.on('close', function () {`
  `//this captures the browser/tab close scenarios, redirects`
`})`
The above code does not work in the following scenarios:

Wifi is disconnected
Device shuts down due to lack of power
Is there a built in event handler that could be leveraged in these scenarios?

**Comment by bnoordhuis** [comment]
Your question is: how can I reliably determine if the TCP connection has been severed?  The short answer is: you can't.

TCP was designed to persevere in the presence of unreliable networks.  The best you can do are heuristics like 'if I don't get a reply within 15 seconds, it's probably not going to happen at all.'

**Comment by prashathsenthil** [comment]
@bnoordhuis in this particular use case i'm dealing with streaming response (text/event-stream), fundamentally the response is streamed and broadcasted via SSE (Server Sent Events). 

UseCase: I hit an end point which would look something like this /api/stream and in the browser i could see the streaming JSON data and now while it is streaming if the browser or the tab is closed then the req.on close event triggers and things are fine there, on the other hand while the streaming is active if i lose the internet connection, some how i need to trigger a function to capture that the stream was disrupted unexpectedly and that's the reason i'm looking for some event handler for this use case.

As you specified if i have to wait for 15 seconds or so then inside the stdout.on handler i need to perform a check and if the data is not received within 15 seconds then i may have to trigger the function that would record this unexpected disruption. Please correct me if i were wrong.

**Comment by bnoordhuis** [comment]
That sounds about right.

**Comment by prashathsenthil** [comment]
Ok, cool... I'll give it a try.. Interesting Socket.io has a disconnect handler in place but not sure if that will capture the internet disruption. Also i cannot use Socket.io in this use case because the service streams the data via SSE.

**Comment by bnoordhuis** [comment]
> but not sure if that will capture the internet disruption

Probably not.  When the other end sends an explicit "I'm closing the connection" message (through a TCP RST, say), that's something you can detect.  But when the other end simply stops sending, you can't really distinguish between simple congestion or the remote end having gone away.
