### ISSUE TITLE
Is there a way to reduce the size of the NodeJS Shared Library?

### ISSUE THREAD

**Issue by benjamintli** [nodejs/help#3311]
* **Node.js Version**: 15.0.1
* **OS**: MacOS
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**:

If I compile nodejs into a single shared library it ends up being pretty massive (~70MB). does anyone know of good ways to reduce the size of this? Perhaps some combination of flags in configure script?

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
