### ISSUE TITLE
Performance considerations using Streams with small highWaterMark

### ISSUE THREAD

**Issue by benjreinhart** [nodejs/help#3313]
* **Node.js Version**: 15+ (or any version)
* **OS**: macOS Big Sur (or any)
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: Streams

Hello, I'm wondering if there is any performance considerations when using streams with a small `highWaterMark`, say, `1`?

As an example, I was playing with the idea of a streaming parser and I started implementing it by having the lexer take in one character at a time, maintain its own buffer, and emit/yield tokens. I could split the data myself into characters, or I could set the `highWaterMark` to 1 which would yield me the characters.

```javascript
const fs = require('fs');
const stream = fs.createReadStream("./file.ext", {highWaterMark: 1, encoding: "utf8"});
const lex = new Lexer;
stream.on('data', (char) => lex.accept(char));
stream.on('end', ()=> doSomething());
```

My question is, is there any performance considerations when using small `highWaterMark`? Are there any side effects, such as needing to perform more system calls to read contents of the file (or an external buffer of some sort)? Or does this not make a difference?

**Comment by addaleax** [comment]
> or I could set the `highWaterMark` to 1 which would yield me the characters.

For one, keep in mind that while this might currently work, the high water mark is generally advisory and it’s still possible to receive more than one character in the `.on('data')` callback, e.g. when you use `.unshift()` to add multiple characters back to the stream.

> My question is, is there any performance considerations when using small `highWaterMark`? 

It’s designed to provide a way to configure the trade-off between CPU and memory load, so yes, it’s always a performance tuning knob.

> Are there any side effects, such as needing to perform more system calls to read contents of the file (or an external buffer of some sort)?

Yes. Currently, this will work by reading one character per system call (which is what you requested).

---

> I could split the data myself into characters

Then I think that might be nicer: 

```js
const fs = require('fs');
const stream = fs.createReadStream("./x.js", {encoding: "utf8"});
const lex = new Lexer;

for await (const chunk of stream) {
  for (const char of chunk) {
    lex.accept(char);
  }
}
```

**Comment by benjreinhart** [comment]
This is very helpful, thank you @addaleax!
