### ISSUE TITLE
Does NodeJS have a bundle id on MacOS

### ISSUE THREAD

**Issue by TopSiS** [nodejs/help#3316]
Hi
I need to enable NodeJS-traffic on my "corporate" Macbook that is "controlled" by Microsoft Intune.

Intune can enable firewall-traffic for specific apps by register their Bundle ID. 
But I'm not able to finde the bundle ID for NodeJS. I have tried this command: **osascript -e 'id of app "node"'** whiteout any luck.

Does anyone know the NodeJS Bundle ID for MacOS?

**Comment by marsonya** [comment]
Hi, there's this `bundle-id` npm package that should help.
Here's the [link](https://www.npmjs.com/package/bundle-id).
