### ISSUE TITLE
Documentation fsPromises.readdir: possibly superfluous await

### ISSUE THREAD

**Issue by michaelrommel** [nodejs/help#3317]
The documentation at: https://nodejs.org/api/fs.html#fs_fspromises_readdir_path_options provides an example to iterate over the returned file array. It uses the construct:
```
for await (const file of files)
    console.log(file);
``` 

I thought, that this `await` would only be necessary, if the returned array would contain objects of a class, which provides an asyncIterator, like fs.Dir (https://nodejs.org/api/fs.html#fs_dir_symbol_asynciterator).

Why is this await statement necessary? I would understand, if the example had the `options` object set to `withFileTypes` set to true, because in this case the returned array is of type `fs.Dirent` and not an array of `String`s or `Buffer`s. (But even then it is questionable, since also `fs.Dirent` does not document an asyncIterator.

If this is an error in the documentation, I am happy to open an issue on the node repository.

**Comment by addaleax** [comment]
> If this is an error in the documentation, I am happy to open an issue on the node repository.

It is. :) You can also submit a PR for this directly if you like, the documentation files are in `doc/api/` in the node repo.

**Comment by marsonya** [comment]
Hi @michaelrommel - Is it okay if I go ahead and create a PR for fixing this issue?
It's okay if you wanna create a PR instead.

**Comment by michaelrommel** [comment]
I'll create the PR tomorrow morning. I was snowed under last week...

**Comment by michaelrommel** [comment]
So, it took me some learning and reformatting the commit message to conform to the guidelines. I should have done that right away using the commandline, instead of trying that in the github UI... It's my first PR to node...

Thank you all for your help and patience. Node is awesome. I would now close this issue, as it is now in the hands of the node project repo itself or will that close by itself, once the referenced PR lands or is closed?

**Comment by Trott** [comment]
Thanks for the contribution! 🎉
