### ISSUE TITLE
Can you please help me solve this error?

### ISSUE THREAD

**Issue by vishnu-mevada** [nodejs/help#3318]
E:\Angular\nodejs course>node start
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'E:\Angular\nodejs course\start'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
![error](https://user-images.githubusercontent.com/71388551/114581244-2cc77600-9c9d-11eb-84b4-131777588db2.jpg)

**Comment by Ayase-252** [comment]
It seems your start command is `node start src/index.js`. While the first argument of `node` is entry file, there is no file named as `start.js`, then failed.

Try `node src/index.js` to start up your app instead.

**Comment by vishnu-mevada** [comment]
This is package.json file.
![error](https://user-images.githubusercontent.com/71388551/114586387-3a332f00-9ca2-11eb-86ee-2e738d93270f.jpg)

**Comment by Ayase-252** [comment]
> This is package.json file.
> ![error](https://user-images.githubusercontent.com/71388551/114586387-3a332f00-9ca2-11eb-86ee-2e738d93270f.jpg)

Try `npm run start`?

**Comment by vishnu-mevada** [comment]
thank you so much @Ayase-252  :)
