### ISSUE TITLE
Node JS fs.createWriteStream with local user using 

### ISSUE THREAD

**Issue by JohnnyBravo1972** [nodejs/help#3319]
Version v14.16.1
Win10
Code

For this line in our Node JS script….
var output = fs.createWriteStream('C:\\Users\\JohhnyBravo1972\\Dropbox\\File.txt');

Do you know the way to Environ local user? Can’t find the answer anywhere…

Example, For VBA….
ActiveWorkbook.SaveAs Filename:= _
        Environ$("UserProfile") & "\Dropbox\File.txt"

…allows me to save on any PC that has dropbox.  

Thanks,
  Chris

**Comment by marsonya** [comment]
You can use `os.homedir()` from`os` module to get a User's Home directory.
Documentation [here](https://nodejs.org/api/os.html#os_os_homedir)

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
