### ISSUE TITLE
writing to child process stdin

### ISSUE THREAD

**Issue by ry99** [nodejs/help#332]
I have a readable stream I'd like to pipe into my custom writable stream. My writable stream redirects the data it gets to a child process. I have some code that works, and some that hangs. I suspect the code that doesn't work hangs because of buffers filling up, but I don't know how to avoid it. I'm not sure what to do when the drain event fires, as I don't know how to access my readable stream at that point (the actual code defines the writer in a different file).

Advice? Pointers? I'll take any help I can get. Thanks.

Works:
```
var input = fs.createReadStream(...)
var writer= function ( input ) {
  ...
  var exe = child_process.spawn( prog, args )
  input.pipe( exe.stdin )
  ...
}
```

Doesn't work:
```

var input = fs.createReadStream(...)
var exe = child_process.spawn( prog, args )
var writer = new Writable( {
    write ( chunk, encoding, done ) {
      var ok = exe.stdin.write( chunk, encoding )
      if( ok ){
        done()
      }
      else{
        console.log( 'waiting to drain')
        this.once('drain', done)
      }
    }    
} )

input.pipe( writer )
```

**Comment by bnoordhuis** [comment]
It's not clear to me what `input` in your examples is.

> but it's obviously not a stream

I also don't quite understand what you mean by (or are referring to with) 'not a stream'.

**Comment by ry99** [comment]
Sorry for the confusion. I've reworded the issue to (hopefully) make it clearer. Anyway, input is the readable stream. I was referring to 'writer' as not a stream in the first sample code.

**Comment by bnoordhuis** [comment]
Thanks.  You have this in your second example:
```js
this.once('drain', done)
```
But I think it should be this:
```js
exe.stdin.once('drain', done)
```

**Comment by ry99** [comment]
Perfect. Yes, that solves the hanging during the drain. However, the code still hung after all the data was written to the pipe. I finally added a listener for the input's end signal, and that seems to have solved the problem. Thanks for your help. Here's my current code:

```
var input = fs.createReadStream(...)
var exe = child_process.spawn( prog, args )
var writer = new Writable( {
    write ( chunk, encoding, done ) {
      var ok = exe.stdin.write( chunk, encoding )
      if( ok ){
        done()
      }
      else{
        exe,stdin.once('drain', done)
      }
    }    
} )

writer.on( 'pipe', function( src ){
  src.on( 'end', function(){
    console.log( 'pipe is ended')
    exe.stdin.end()
  })
})
input.pipe( writer )
```
