### ISSUE TITLE
Why is host undefined here?

### ISSUE THREAD

**Issue by LightningRpper** [nodejs/help#3320]
I am currently working on a video watching application and I've come across an error that prevents the website from fully working. The error is             
```
C:\Users\Jack\workspace\source\server.js:185
            io.sockets.adapter.rooms['room-' + socket.roomnum].host = host
                                                                    ^

TypeError: Cannot set property 'host' of undefined
    at Socket.<anonymous> (C:\Users\Jack\workspace\source\server.js:185:69)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (C:\Users\Jack\workspace\source\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\Jack\workspace\source\node_modules\socket.io\dist\socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
``` 

Does anyone know how to fix this problem?

Code lines in question: 
(server.js:185:69)
```
require('dotenv').config();

var express = require('express');
var app = express();
var server = require('http').createServer(app);
var io = require('socket.io')(server);
users = [];
connections = [];
rooms = [];
userrooms = {}
.
.
.
.
.
socket.on('new room', function(data, callback) {
//callback(true);
socket.roomnum = data;

userrooms[socket.id] = data

var host = null
var init = false

if (socket.roomnum == null || socket.roomnum == "") {
socket.roomnum = '1'
userrooms[socket.id] = '1'
}

if (!rooms.includes(socket.roomnum)) {
rooms.push(socket.roomnum);
}

// console.log(io.sockets.adapter.rooms['room-' + socket.roomnum] !== undefined)
if (io.sockets.adapter.rooms['room-' + socket.roomnum] === undefined) {
socket.send(socket.id)
host = socket.id
init = true

socket.emit('setHost');
//console.log(socket.id)
} else {
console.log(socket.roomnum)
host = io.sockets.adapter.rooms['room-' + socket.roomnum].host
}

console.log(socket.username + " connected to room-" + socket.roomnum)
socket.join("room-" + socket.roomnum);

if (init) {
   io.sockets.adapter.rooms['room-' + socket.roomnum].host = host //This line
```

(node_modules\socket.io\dist\typed-events.js:69:22)

```
emitUntyped(ev, ...args) {
  return super.emit(ev, ...args); //This line
}
```

(node_modules\socket.io\dist\socket.js:428:39)

```
    dispatch(event) {
        debug("dispatching an event %j", event);
        this.run(event, (err) => {
            process.nextTick(() => {
                if (err) {
                    return this._onerror(err);
                }
                if (this.connected) {
                    super.emitUntyped.apply(this, event); //This line
                }
                else {
                    debug("ignore packet received after disconnection");
                }
            });
        });
    }
```

**Comment by Ayase-252** [comment]
This `io.sockets.adapter.rooms['room-' + socket.roomnum]` is `undefined` somehow. Maybe `room-${socket.roomnum}` is wrong for a room identifier. You could check it why.

**Comment by LightningRpper** [comment]
> 
> 
> This `io.sockets.adapter.rooms['room-' + socket.roomnum]` is `undefined` somehow. Maybe `room-${socket.roomnum}` is wrong for a room identifier. You could check it why.

I'm sorry but I don't understand. What do you mean?

**Comment by Ayase-252** [comment]
@LightningRpper 
I'm sorry if it's too rough because I don't have complete code.

Since the error says `TypeError: Cannot set property 'host' of undefined`. It means `io.sockets.adapter.rooms['room-' + socket.roomnum]` is `undefined`. I'm not sure that why it is accessing a **non-existing property** on `io.sockets.adapter.rooms`.  Maybe you format the room identifier (which is `'room-' + socket.roomnum` I assume) mistakely.  You could print a log or debug into your code to see what is `'room-' + socket.roomnum` is before crash. Then you may know why it happens.

**Comment by LightningRpper** [comment]
@Ayase-252 Can't find the debug log since it refuses to connect to Chrome through no fault of its own, but do you think this code could have something to do with it?

```
        // console.log(io.sockets.adapter.rooms['room-' + socket.roomnum] !== undefined)
        if (io.sockets.adapter.rooms['room-' + socket.roomnum] === undefined) {
            socket.send(socket.id)
            host = socket.id
            init = true

            socket.emit('setHost');
            //console.log(socket.id)
        } else {
            console.log(socket.roomnum)
            host = io.sockets.adapter.rooms['room-' + socket.roomnum].host
        }

        console.log(socket.username + " connected to room-" + socket.roomnum)
        socket.join("room-" + socket.roomnum);
```

**Comment by LightningRpper** [comment]
Please help me, anyone. I don't have all the time in the world to fix this error and finish this task.

**Comment by marsonya** [comment]
Hey @LightningRpper - based on the code snippet shared by you,
`io.sockets.adapter.rooms['room-' + socket.roomnum]` value is undefined.
You need to make sure `'room-' + socket.roomnum` in `io.sockets.adapter.rooms` array is defined.
That will help you get rid of the `undefined` error.

**Comment by LightningRpper** [comment]
@marsonya 
```
        socket.roomnum = data;
```
That's an earlier line in the code.

**Comment by LightningRpper** [comment]
@marsonya @Ayase-252 If this helps, this is what the debug console told me.
![debugger](https://user-images.githubusercontent.com/54909296/115156779-905df480-a04b-11eb-8d60-b0dd250594ae.PNG)

**Comment by Ayase-252** [comment]
If possible, could you print all keys in `io.sockets.adapter.rooms` before you accessing `io.sockets.adapter.rooms['room-' + socket.roomnum]`, like

```js
if (init) {
  console.log(Object.keys(io.sockets.adapter.rooms)) // add this line
  io.sockets.adapter.rooms['room-' + socket.roomnum].host = host //This line
}
```

**Comment by LightningRpper** [comment]
@Ayase-252 
```
api ready Event {isTrusted: false, type: 'apiready', target: iframe#player-daily.video, currentTarget: iframe#player-daily.video, eventPhase: 2, …}
arg1:Event {isTrusted: false, type: 'apiready', target: iframe#player-daily.video, currentTarget: iframe#player-daily.video, eventPhase: 2, …}
bubbles:true
cancelable:true
cancelBubble:false
composed:false
currentTarget:null
defaultPrevented:false
eventPhase:0
isTrusted:false
path:(10) [iframe#player-daily.video, div#dailyArea, div.col-lg-7, div.row.my-4, div#roomArea, div.container, body#Home.bg-light, html.fontawesome-i2svg-active.fontawesome-i2svg-complete, #document, Window]
returnValue:true
srcElement:iframe#player-daily.video
target: iframe#player-daily.video
timestamp: 1879.9850000068545
type: 'apiready'
__proto__:Event
```

Debug console gave me this.

Powershell gave me 
```
[]
```

**Comment by Ayase-252** [comment]
> Powershell gave me

That's the problem. When you try to access `io.sockets.adapter.rooms['room-' + socket.roomnum]`, there is actually nothing in `io.sockets.adapter.rooms`. From [the docs](https://github.com/kyle8998/Vynchronize/wiki/Important-Dev-Functions) from project you linked, I think you should wrap related code in `new room` event,

```
socket.on('new room', (room, cb) => {
  // use `room` or `io.sockets.adapter.rooms['room-' + socket.roomnum]`? I'm not sure.
})
```

You can also reach to [the author](https://github.com/kyle8998/Vynchronize/wiki) for any question in the project.

**Comment by marsonya** [comment]
I hope the answers were helpful.
A proper workaround/resolution has been provided so I am closing this issue.
Please feel free to reopen this issue if there is more to be added.
