### ISSUE TITLE
Log API response body

### ISSUE THREAD

**Issue by chuksgpfr** [nodejs/help#3324]
* **Node.js Version**: 14.x
* **OS**: MacOS
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I'm trying to create a middleware that reads response body going out to a client. This is my code so far

```js
function readBody(req, res, next) {
    res.on('finish', (chunk, encoding) => {
        // Do your logging here.
        //log outgoing response body

      });

    next()
}
```

Nothing i saw online was useful.
Any pointers or help ?

**Comment by Ayase-252** [comment]
What module/library do you use? Is that koa, express or native http module?

**Comment by chuksgpfr** [comment]
I want it to be used on any web framework.

But I am using express for now.

**Comment by Ayase-252** [comment]
This [thread](https://stackoverflow.com/questions/19215042/express-logging-response-body) may be helpful.

**Comment by chuksgpfr** [comment]
I have tried the solution given in that thread, bod comes back empty.

**Comment by chuksgpfr** [comment]
Ok. Why does it not return a body on my browser, but returns on postman.

**Comment by chuksgpfr** [comment]
The browser caches the data i guess.
