### ISSUE TITLE
Private github repository unable to download with `npm ci`

### ISSUE THREAD

**Issue by aprokopenko** [nodejs/help#3325]
## Environment

* **Platform**: Ubuntu 20.04
* **Docker Version**: Docker version 20.10.5, build 55c4c88
* **Node.js Version**: 14.16.1
* **Image Tag**: 14-buster

## Expected Behavior

`npm i`, `npm ci` have to download node modules from github private repositories with and without `package-lock.json` files. 
With the same behavior as it works without docker.

## Current Behavior

For some reason when you try to build a project with `npm ci` inside docker container with existed `package-lock.json` file it fails to connect to the private github repository, however `npm i` works well if I remove `package-lock.json` file.

## Possible Solution

don't know

## Steps to Reproduce

- create private github repository with dummy npm package
- add this package to the project dependencies
- run docker container with mounted id_rsa connected to your github account
- run ssh agent to fill known_hosts
- try install project inside docker container (when docker container is running and you opened bash inside)
- `npm i` works well for the first time
- now remove node_modules folder
- `npm ci` failed due to error that it can't check known hosts for github.com for private repository
- if you remove `package-lock.json` and run `npm i` it will run well

## Additional Information

I think it's a critical bug, because a lot of developers use private github repositories

**Comment by gireeshpunathil** [comment]
@nodejs/npm

**Comment by wraithgar** [comment]
There is an issue tracking this, with potential workarounds, here: https://github.com/npm/cli/issues/2610#issuecomment-914610832
