### ISSUE TITLE
property 'forEach'

### ISSUE THREAD

**Issue by JBLearnDebian** [nodejs/help#3326]
### How often does it reproduce? Is there a required condition?
Ever since I rebooted. Tried repairing Node.js
### What is the expected behavior?
node-red should start when I enter node-red in CMD.

### What do you see instead?

19 Apr 22:37:45 - [error] TypeError: Cannot read property 'forEach' of undefined    at Object.addModule (C:\Users\BrianS\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\registry.js:195:27)
    at C:\Users\BrianS\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\loader.js:153:34
### Additional information

?

**Comment by Ayase-252** [comment]
You can seek help in [node-red](https://github.com/node-red/node-red/issues). It seems not related to node itself.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
