### ISSUE TITLE
Trouble installing Node.js

### ISSUE THREAD

**Issue by ddhay** [nodejs/help#3328]
When trying to install Node.js form the Node.js web site and downloading through windows installer I get the following error message and unable to complete installation:  Webroot virus protector is disabled. Using latest version of Windows 10 and Google Chrome.

![node js error messzge](https://user-images.githubusercontent.com/44911197/115491755-28173a80-a226-11eb-9d90-243d1995492f.PNG)

Darrell Haywood

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
