### ISSUE TITLE
Is it possible to modify/suppress the Garbage Collector logs?

### ISSUE THREAD

**Issue by jomi-se** [nodejs/help#3329]
_Note: I'm not asking for help with a memory issue, I'm asking for help on handling the logs written by NodeJS when Memory and GC issues happen_

I'm using NodeJS in production and consuming the app logs with [filebeat](https://www.elastic.co/beats/filebeat) to push them somewhere. Some of node's internal logs don't follow any regular structure so they're not consumed well by this tool (either each line is a separate log or trying to pack them together is hard)

I monkey-patched `console.log`, `console.warn` and `console.error` which helps with most internal errors and warnings but a few things NodeJS logs don't seem to go through those functions. An example is Garbage Collector warnings/logs:

For example:
On `stderr`
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa15410 node::Abort() [/usr/bin/node]
 2: 0xa157d0 node::OnFatalError(char const*, char const*) [/usr/bin/node]
 3: 0xb7f04c v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xb7f24c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xd2a000 v8::internal::Heap::EnsureFromSpaceIsCommitted() [/usr/bin/node]
...
```

On `stdout`
```
<--- Last few GCs --->

[3802:0x12446aa0]  6230872 ms: Scavenge 2030.1 (2051.5) -> 2029.9 (2052.3) MB, 6.1 / 0.0 ms  (average mu = 0.290, current mu = 0.260) allocation failure
[3802:0x12446aa0]  6231406 ms: Mark-sweep 2031.4 (2052.8) -> 2027.3 (2049.6) MB, 505.8 / 0.1 ms  (average mu = 0.202, current mu = 0.081) allocation failure scavenge might not succeed
[3802:0x12446aa0]  6231424 ms: Scavenge 2031.1 (2052.7) -> 2030.9 (2053.2) MB, 6.3 / 0.0 ms  (average mu = 0.202, current mu = 0.081) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0000551c08d1 <JSObject>
    0: builtin exit frame: parse(this=0x0000551dee79 <Object map = 0x45303639>,0xffff06240119 <Very long string[3193062]>,0x0000551dee79 <Object map = 0x45303639>)
...
```

Is there any way to manipulate these logs (modify the format, remove the empty lines, etc)? Or maybe silence the stdout ones which don't seem very useful? Is there any documentation on this kind of logs?

Thank you for any help

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
