### ISSUE TITLE
win7 64bit os failed to install nodejs

### ISSUE THREAD

**Issue by fwp728** [nodejs/help#333]
I wanted to install the node.js. The installer was downloaded from https://nodejs.org/en/,however, when
I double clicked the installer , an error dialog was thrown and described like that "there is a problem with this Windows Installer package . A DLL required for this install to complete could not be run. Contact your personal or package vendor."  How to deal with this problem?

**Comment by vsemozhetbyt** [comment]
Please check these issues, maybe some tips there could help:

https://github.com/nodejs/node/issues/3431
https://github.com/nodejs/node/issues/4086
https://github.com/nodejs/node/issues/5759
https://github.com/nodejs/help/issues/264
https://github.com/nodejs/node/issues/8402
https://github.com/nodejs/help/issues/291
https://github.com/nodejs/node/issues/8663

**Comment by lordKnighton** [comment]
I don't know if your still having issues, but this link should help: [click-me](https://support.pix4d.com/hc/en-us/articles/202560999-Error-There-is-a-problem-with-this-Windows-Installer-package-A-DLL-required-for-this-install-to-complete-could-not-be-run-Contact-your-support-personnel-or-package-vendor-#gsc.tab=0)

**Comment by fwp728** [comment]
Thanks for you help! I had solved that problem. Because of the OS authority.






|
方文平
fangwenping728@163.com
公司名称：杭州戬威机电科技有限公司
地址：杭州市余杭区荆长路768#顺帆信息产业园B区6#楼405室
电话：18158147116
手机：15858222483
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|


At 2016-11-21 04:38:54, "kelvin knighton" <notifications@github.com> wrote:


I don't know if your still having issues, but this link should help: click-me

**Comment by danicoolpak17** [comment]
@fwp728 Hi 
I was having the same trouble with my Node.JS installer . It is not issue that the installer has just need to change some settings. I did the below steps.

1 - Clean **TEMP** Folder
2 - Disable your **antivirus** for 10 mins or so.
3 - Then do the below steps. 
4 - Go to C:>users>"UserName">AppData>Local>Temp
5 - Right Click on Temp and go to Properties 
6 - Select Security Tab 
7 - Select the User and check the permission and controll give the user full control by Checking Full Control on permission 
8 - Go Ahead and Install Node.js and Enjoy.

**Comment by CarloCattano** [comment]
having same issue . Followed the steps without luck.
unistall/install/repair not possible

**Comment by xprimate** [comment]
Thanks. It worked.

**Comment by danicoolpak17** [comment]
@xprimate you are welcome glad to hear that it worked.

**Comment by Larryster** [comment]
worked for me...twice (after uninstalling, getting the same issues when reinstalling and finding this post again)
