### ISSUE TITLE
Connect to MongoDB by IPv6: err:connect EINVAL fe80::a00:27ff:fee8:b298:27017 - Local (:::0)

### ISSUE THREAD

**Issue by Scott-Zou-Developer** [nodejs/help#3330]
node v12.18.3

We connect to MongoDB by IPv4 is OK, but IPv6 is not support.

**Comment by gireeshpunathil** [comment]
@Scott-Zou-Developer - is this outstanding? if so pls share a minimal code / steps to reproduce?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
