### ISSUE TITLE
is there any way to kill MySQL idle connection from NodeJS code?

### ISSUE THREAD

**Issue by bhaveshkumbhaniidentixweb** [nodejs/help#3331]
I am using node.js with MySQL, in the database, I can see much connection which is idle but it's open, is there any way to kill idle connection which is not in use, I found a solution for ideal time connection kills from MySQL but I want to kill only idle connection from node.js code.
Thank you

**Comment by marsonya** [comment]
Incase you are using connection pooling, you will have to end the each connection once you are done using it. Else the connection(s) will stay alive until MySQL kills them.

`pool.end(function (err) {
  // all connections in the pool have ended
});`

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
