### ISSUE TITLE
Worker terminate doesn't kill child processes

### ISSUE THREAD

**Issue by pofider** [nodejs/help#3332]
* **Node.js Version**: 14, 16
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: worker_threads

I am using nodejs worker_threads module and inside worker I start child processes (chrome). 
When I call `process.exit()` from inside the worker, it kills also spawned child processes. Great! However, when I call `worker.terminate()` from outside, it keeps child processes from thread pending. 
Is there a way to kill thread including child processes it did create? Just like it happens automatically when calling `process.exit()` inside worker? Thank you

`main.js`
```js
const {
  Worker
} = require('worker_threads')

const worker = new Worker('./worker.js')
worker.on('message', async (m) => {  
  await worker.terminate()  
  setTimeout(() => {
    // during this time the chrome processes are pending until the main processes finishes
  }, 10000)
})
```

`worker.js`
```js
const {
  parentPort
} = require('worker_threads')

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  // not closing chrome intentionally
  parentPort.postMessage('I am done terminate me')  
})()
```

**Comment by Jinul** [comment]
Surprisingly, It works for the playwright but not for the puppeteer.

**Comment by gireeshpunathil** [comment]
@nodejs/workers

**Comment by addaleax** [comment]
> When I call `process.exit()` from inside the worker, it kills also spawned child processes.

I’d say that this is a bug, not the other way around.

**Comment by VitaliiKhomiakov** [comment]
> > When I call `process.exit()` from inside the worker, it kills also spawned child processes.
> 
> I’d say that this is a bug, not the other way around.

I would like to confirm that the bug still exists

**Comment by entrptaher** [comment]
I did this in a roundabout way. This way I can listen to anything and then terminate or exit the process from the worker itself.

```js
worker.on('message', async (m) => {  
  await worker.postMessage('TERMINATE_FORCEFULLY');
})

parentPort.on('message', function(signal){
  if (signal === 'TERMINATE_FORCEFULLY') {
    process.exit(0);
  }
})
```
