### ISSUE TITLE
build fails on cygwin

### ISSUE THREAD

**Issue by mintty** [nodejs/help#3334]
- download source
- configure
- make:
/usr/bin/python3.8.exe tools/gyp_node.py -f make
make -C out BUILDTYPE=Release V=0
  touch 5a276bcbdddf7a49a49f49aea4be9f1f45251285.intermediate
  LD_LIBRARY_PATH=/cygdrive/c/tmp/node-v14.16.1/out/Release/lib.host:/cygdrive/c/tmp/node-v14.16.1/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p tools/msvs/genfiles; **"mc src/res/node_etw_provider.man -h tools/msvs/genfiles -r tools/msvs/genfiles"**
/bin/sh: mc src/res/node_etw_provider.man -h tools/msvs/genfiles -r tools/msvs/genfiles: No such file or directory

Highlighting by me. The quoted command string is in fact not an executable command, also what would "mc" be supposed to be? The midnight commander?

**Comment by gireeshpunathil** [comment]
@mintty - is this outstanding?

**Comment by mintty** [comment]
It actually got worse:

- configure:
Node.js configure: Found Python 3.8.10...
gyp: --sysconfdir=/etc not found (cwd: /cygdrive/c/tmp/node) while trying to load --sysconfdir=/etc
Error running GYP
