### ISSUE TITLE
What are these strings causing high memory usage

### ISSUE THREAD

**Issue by nikitpanchal** [nodejs/help#3335]
Hello I'm running a Node server it run stable with following heap memory usage but rss keep increasing 1mb every hour

`["Memory: rss 63.71 MB","Memory: heapTotal 35.69 MB","Memory: heapUsed 27.54 MB","Memory: external 18.98 MB","Memory: arrayBuffers 17.51 MB"]`

* **Node.js Version: v12.18.2**:
* **Windows**:

Im dumping heap node every hour and compare heaps in my local computer. 
I notice some very huge string consuming retaining size. Could anyone let me know should i be worry about this ?

![string-mem](https://user-images.githubusercontent.com/51583436/115880483-6ac85500-a468-11eb-8699-cc2fa2abd113.png)

**Comment by gireeshpunathil** [comment]
@nikitpanchal - is this outstanding? is the heap dump collection performed after you notice the rss increase? or the heap dump collection was always there? I am trying to associate heap dump collection activity itself as a trigger for rss increase, the heap dump collection requires some memory intensive activity in the v8.

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.

**Comment by rafaelhrtd** [comment]
I am having the exact same issue here. I am running a test suite, and taking two heap snapshots (before and after a test) and comparing them to each other shows a massive increase in the memory allocated to strings:

<img width="1217" alt="Screen Shot 2022-01-24 at 5 03 56 PM" src="https://user-images.githubusercontent.com/78874301/150885728-b3859e99-ee69-442e-8a6b-8e599ad5d723.png">

**Comment by gireeshpunathil** [comment]
@rafaelhrtd - it is kind of expected, but the key questions are:

 - do those result in eventual build-up of rss?
 - do those result in eventual build-up of virtual memory?

if not, it may be safely ignored. if yes, then we may have a working theory, for which a solution is not yet known.
