### ISSUE TITLE
npm internal/modules/cjs/loader.js:883   throw err;   ^  Error: Cannot find module 'code-point-at' Require stack: - C:\Users\(File Name)\AppData\Roaming\npm\node_modules\npm\node_modules\gauge\node_modules\string-width\index.js

### ISSUE THREAD

**Issue by HamzaZaidiX** [nodejs/help#3336]
**Hello Everyone!** 
  **I am Having an Error in Node Js Please! Take a look at my problem I have tried all the commands but no change Please! see my error and tell me where I am wrong I have tried Everything Please! Tell me how to solve this Problem if u know!
The error (down below) is coming in when I type `npm `or `npx` .**

```
C:\Users\Hamza Zaidi>npm
internal/modules/cjs/loader.js:883
  throw err;
   ^
Error: Cannot find module 'code-point-at'
Require stack:
- C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\npm\node_modules\gauge\node_modules\string-width\index.js
- C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\npm\node_modules\gauge\wide-truncate.js
- C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\npm\node_modules\gauge\render-template.js
- C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\npm\node_modules\gauge\plumbing.js
- C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\npm\node_modules\gauge\index.js
- C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\log.js
- C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\npm\lib\cli.js
- C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\Hamza Zaidi\AppData\Roaming\npm\node_modules\←[4mnpm←[24m\node_modules\←[4mgauge←[24m\node_modules\←[4mstring-width←[24m\index.js:3:19)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Hamza Zaidi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\gauge\\node_modules\\string-width\\index.js'←[39m,
    ←[32m'C:\\Users\\Hamza Zaidi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\gauge\\wide-truncate.js'←[39m,
    ←[32m'C:\\Users\\Hamza Zaidi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\gauge\\render-template.js'←[39m,
    ←[32m'C:\\Users\\Hamza Zaidi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\gauge\\plumbing.js'←[39m,
    ←[32m'C:\\Users\\Hamza Zaidi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\gauge\\index.js'←[39m,
    ←[32m'C:\\Users\\Hamza Zaidi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npmlog\\log.js'←[39m,
    ←[32m'C:\\Users\\Hamza Zaidi\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\cli.js'←[39m,
    ←[32m'C:\\Users\\Hamza Zaidi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js'←[39m
  ]
}
```

I have Uninstall the Node js and Reinstall again but no change I have tried The Commands like:
Delete the` node_modules`
Delete the `package-lock .json file`
Run `npm `install
Run `npm `start
Run This command: `rm -rf node_modules package-lock.json && npm install && npm start` but this command is also giving error `'rm'` is not recognized as an internal or external command, operable program or batch file.

![Screenshot (54)](https://user-images.githubusercontent.com/52501040/115443597-e63dc280-a22c-11eb-96d5-eee3a096c8da.png)

**Comment by aduh95** [comment]
Duplicate of https://github.com/nodejs/node/issues/38317 and https://github.com/npm/cli/issues/2850.

**Comment by KrishnaPrabha13** [comment]
I am facing this problem please help me out 

I am getting error when I type npm.

![Capture](https://user-images.githubusercontent.com/86238794/123518431-88fa3d80-d6c3-11eb-9a19-04f322b1f4d4.PNG)

**Comment by Maxintoworld** [comment]
i had the same problem.
fix it with this command " npm install git-remote-origin-url "

**Comment by mohininalla** [comment]
I have Uninstall the Node js and Reinstall it. The problem is resolved for me.

**Comment by dawn-hacker** [comment]
this issue sucks, npm start  
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'node:path'
Require stack:
- /home/kali/.config/nvm/versions/node/v14.17.6/lib/node_modules/npm/lib/cli.js
- /home/kali/.config/nvm/versions/node/v14.17.6/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/kali/.config/nvm/versions/node/v14.17.6/lib/node_modules/npm/lib/cli.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kali/.config/nvm/versions/node/v14.17.6/lib/node_modules/npm/lib/cli.js',
    '/home/kali/.config/nvm/versions/node/v14.17.6/lib/node_modules/npm/bin/npm-cli.js'
  ]
}
