### ISSUE TITLE
Installing Node is stuck in "preparing the disk" forever

### ISSUE THREAD

**Issue by fanglinlu** [nodejs/help#3337]
* **Node.js Version**: 16.0.0
* **OS**: Mojave 10.14.6
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: 

I tried to install node by downloading the package here https://nodejs.org/en/. But my installation is stuck in the "preparing for disk" step and never move forward.

**Comment by gireeshpunathil** [comment]
@fanglinlu - is this outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
