### ISSUE TITLE
Streaming module

### ISSUE THREAD

**Issue by jayesh-sapkale** [nodejs/help#334]
# Feature request | solution request : 

Case : 
Streaming module is perfectly work for me on video stream,

Need: 
After video paused Node.js read specific range of buffer and then stop video loading

my question/request  is : how to make continuous stream even after video was paused?

Is any solution exists on this approach?

::::Thanks in Advance::::
# createReadStream | #pipe | #range

**Comment by lordKnighton** [comment]
HI @jayesh-sapkale so for clarification, you're building a video client. And you want it to keep loading the video even, while it's paused, is this correct?

**Comment by jayesh-sapkale** [comment]
Hi @lordKnighton really sorry for delay in clarification confirmation(my Internet problem) and thank you for considering the question.

Yes : { Video buffering } 
is there any way to stream original MP4 video with buffer even after video was paused???

**Comment by lordKnighton** [comment]
I don't have any experience working with video streams with node.js. So I'm pretty sure someone else can help you better. But for now, I hope these links can help: 


 http://blog.dojchinovski.mk/?p=41 

https://www.youtube.com/watch?v=OZHinPswQ1g

https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_readable_resume

**Comment by lordKnighton** [comment]
closing for now, feel free to reopen & further the discussion.
