### ISSUE TITLE
Unjank linux installs so it's not trash

### ISSUE THREAD

**Issue by cal97g** [nodejs/help#3342]
**Is your feature request related to a problem? Please describe.**
The fact that your Linux installation is a joke, and if you use apt install npm by default it's literally broken. I know the JS ecosystem sucks pretty hard but that's pretty trash. I literally had to find a jank ass repo maintained by some random company in order to install node on Linux.

**Describe the solution you'd like**
I'd like the download page on nodejs.org to provide more instructions in the readme than:
```
Binaries, installers, and source tarballs are available at
<https://nodejs.org/en/download/>.
```
Huh? I just did that and these are the instructions you give me?

Also somebody just update the package in ubuntu repo's. Cheers.

**Describe alternatives you've considered**
WebAssembly

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
