### ISSUE TITLE
Secure connections to MySQL

### ISSUE THREAD

**Issue by D4V3M0NK** [nodejs/help#3343]
**Is your feature request related to a problem? Please describe.**
I have the requirement to connect to a remote MySQL server and in order to do so, I have to be able to connect securely using TLS1.2+ - the MySQL server itself has been configured to require these secure connections at the server level, as well as at the user level.

**Describe the solution you'd like**
When connecting to this server via a mysql command line, and alongside providing `host`, `user` and `password`, I have to 
1. specify the location of a certificate 
2. set the ssl-mode to VERIFY_IDENTITY
... so I'm guessing a way to mimic that set up to permit the application that I'm using (that relies on node.js) to be able to connect too.

From what I can see, this hasn't been requested before which I find remarkable - unless I'm missing something?!

**Comment by gireeshpunathil** [comment]
@D4V3M0NK - is this outstanding? for me it looks like a requirement to mysql, as opposed to Node.js?

**Comment by D4V3M0NK** [comment]
@gireeshpunathil apologies, I should've closed this. Found an accompanying package that permits Node.js to securely connect to a MySQL server. Closing this now sir.
