### ISSUE TITLE
Buildroot compiled Node.JS Slow Startup times. 

### ISSUE THREAD

**Issue by swanav** [nodejs/help#3344]
* **Node.js Version**: v12.22.1
* **OS**: Linux (Custom Build - Buildroot)
* **Scope (install, code, runtime, meta, other?)**: runtime

I have cross compiled Node.JS for my custom board as part of a buildroot build process.

But whenever I start a new application it takes very long to startup. I have tried debugging using strace, but I am not able to make sense of the output. Can someone tell me what's causing these long startup times?

I have also tried a pre-compiled build for the armv7 target and it is _relatively_ way faster. Takes ~ 2s for the below mentioned 9 second operation. (I can't use the pre-compiled version though, since I need to build Node.JS as part of the build process to be able to build native-addons later in my pipeline).

node -v takes 0.02s
```
# time node -v
v12.22.1
real	0m 0.02s
user	0m 0.01s
sys	0m 0.00s
```

node -h takes ~ 9 seconds
```
# time node -h
real	0m 9.06s
user	0m 8.49s
sys	0m 0.43s
```

**strace** output of a successful run attached: [out2.log](https://github.com/nodejs/help/files/6397685/out2.log)

I feel these lines are somehow the fault (the strace logs are flooded with them), but I am not really sure what's the issue at play here.

```
mprotect(0x2fbc2000, 249856, PROT_READ|PROT_EXEC) = 0
mprotect(0x2fbc2000, 249856, PROT_READ|PROT_WRITE) = 0
cacheflush(0x2fbc27c0, 0x2fbc27c8, 0, 0, 0x18ba004) = 0
mprotect(0x2fbc2000, 249856, PROT_READ|PROT_EXEC) = 0
mprotect(0x2fbc2000, 249856, PROT_READ|PROT_WRITE) = 0
```
I have also attached the mk file for the node compilation process. [node12.mk](https://github.com/nodejs/help/files/6397724/node12.txt)

This contains all the options I use to configure the build as well as the build commands.

Can someone point me as to what might be the culprit for the issue that I am facing?

**Comment by noctarius** [comment]
Same issue here. It looks like it's coming from the fact, that nodejs is built without a valid startup snapshot (-without-snapshot). You can generate the snapshot (with the tool mksnapshot from the tools subdirectory) manually and put it into the build. That's at least what I'm trying to do right now. The problem is, you have to generate the snapshot for the specific version which is built. Updating the nodejs version forces you to regenerate it.

**Comment by gireeshpunathil** [comment]
@swanav / @noctarius can you try running with `--prof` option that will produce v8 profiler output, which you can post-process with `--prof-process` to show where the CPU is really spent?

ref: https://nodejs.org/dist/latest-v17.x/docs/api/cli.html#--prof

**Comment by gireeshpunathil** [comment]
ping @noctarius @swanav - is this outstanding?

**Comment by noctarius** [comment]
No, buildroot patched it into one of the latest releases using QEMU and stuff :-) From my side this is fixed and I also have a patch for older buildroot and node versions, in case somebody is interested 👍

**Comment by humingchun** [comment]
@noctarius Could you share how to patch old buildroot with node v12 version?

**Comment by noctarius** [comment]
Hey @xeis sorry, I completely missed your request. @humingchun I had nodejs updated to 12.22.6 in the end, but I guess the patches may work on 12.18 too.

If there are missing elements let me know. We had a few more patches for buildroot that were applied before those two.
[buildroot_0007_nodejs_v8_wrapper.txt](https://github.com/nodejs/help/files/8691275/buildroot_0007_nodejs_v8_wrapper.txt)
[buildroot_0008_nodejs_enable_host_snapshot.txt](https://github.com/nodejs/help/files/8691276/buildroot_0008_nodejs_enable_host_snapshot.txt)

**Comment by humingchun** [comment]
@noctarius Hi, thank you very much for the help. I have studied the latest Node.js package in Buildroot v2022.02 and found out how the QEMU fixs the snapshot issue of cross-compiling Node.js. I have successfully backported the QEMU fix to the old Buildroot version I have to use.

Here are steps if it helps anyone, or just check the patched Node.js v12.21.0 package [buildroot_nodejs_v12.20.0_with_snapshot.zip](https://github.com/nodejs/help/files/8696463/buildroot_nodejs_v12.20.0_with_snapshot.zip).

**Step 1**: Copy _v8-qemu-wrapper.in_ to Node.js package directory.

```
#!/usr/bin/env sh

# Pass -r to qemu-user as to trick glibc into not errorings out if the host kernel
# is older than the target kernel.
exec @QEMU_USER@ -r @TOOLCHAIN_HEADERS_VERSION@ \
    @QEMU_USERMODE_ARGS@ \
   -L "${STAGING_DIR}/" \
    "$@"
```

**Step 2**: Modify nodejs.mk file

1. Add _host-qemu_ to NODEJS_DEPENDENCIES
2. Remove _--without-snapshot_ from NODEJS_CONF_OPTS and HOST_NODEJS_CONFIGURE_CMDS
3. Remove _the two foreach loops_ which modify source file _$(@D)/tools/v8_gypfiles/v8.gyp_ and _$(@D)/node.gyp_ from NODEJS_CONFIGURE_CMDS
4. Define NODEJS_INSTALL_V8_QEMU_WRAPPER, NODEJS_WRAPPER_FIXUP, and add them to NODEJS_PRE_CONFIGURE_HOOKS

```
define NODEJS_INSTALL_V8_QEMU_WRAPPER
        $(INSTALL) -D -m 755 $(NODEJS_PKGDIR)/v8-qemu-wrapper.in \
                $(@D)/out/Release/v8-qemu-wrapper
        $(SED) "s%@QEMU_USER@%$(QEMU_USER)%g" \
                $(@D)/out/Release/v8-qemu-wrapper
        $(SED) "s%@TOOLCHAIN_HEADERS_VERSION@%$(BR2_TOOLCHAIN_HEADERS_AT_LEAST)%g" \
                $(@D)/out/Release/v8-qemu-wrapper
        $(SED) "s%@QEMU_USERMODE_ARGS@%$(call qstrip,$(BR2_PACKAGE_HOST_QEMU_USER_MODE_ARGS))%g" \
                $(@D)/out/Release/v8-qemu-wrapper
endef
NODEJS_PRE_CONFIGURE_HOOKS += NODEJS_INSTALL_V8_QEMU_WRAPPER

define NODEJS_WRAPPER_FIXUP
        $(SED) "s%@MAYBE_WRAPPER@%'<(PRODUCT_DIR)/v8-qemu-wrapper',%g" $(@D)/node.gyp
        $(SED) "s%@MAYBE_WRAPPER@%'<(PRODUCT_DIR)/v8-qemu-wrapper',%g" $(@D)/tools/v8_gypfiles/v8.gyp
endef
NODEJS_PRE_CONFIGURE_HOOKS += NODEJS_WRAPPER_FIXUP

# Do not run the qemu-wrapper for the host build.
define HOST_NODEJS_WRAPPER_FIXUP
        $(SED) "s%@MAYBE_WRAPPER@%%g" $(@D)/node.gyp
        $(SED) "s%@MAYBE_WRAPPER@%%g" $(@D)/tools/v8_gypfiles/v8.gyp
endef
HOST_NODEJS_PRE_CONFIGURE_HOOKS += HOST_NODEJS_WRAPPER_FIXUP
```

**Step 3**: Create Config.in.host in Node.js package directory.

```
config BR2_PACKAGE_HOST_NODEJS
        bool "host nodejs"
        depends on BR2_PACKAGE_HOST_QEMU_USER_ARCH_SUPPORTS
        depends on BR2_HOST_GCC_AT_LEAST_7
        select BR2_PACKAGE_HOST_QEMU
        select BR2_PACKAGE_HOST_QEMU_LINUX_USER_MODE
        help
          Event-driven I/O server-side JavaScript environment based on
          V8.

          http://nodejs.org/

comment "host nodejs needs a host gcc >= 7"
        depends on BR2_PACKAGE_HOST_QEMU_USER_ARCH_SUPPORTS
        depends on !BR2_HOST_GCC_AT_LEAST_7
```

**Step 4**: Create 0001-add-qemu-wrapper-support.patch using quilt and move it to Node.js package directory.

_Note: the content of this qemu patch file may be varies on different Node.js version. So don't copy it. Read it to learn how to modify node.gyp and tools/v8_gypfiles/v8.gyp._

```
Index: node-v12.21.0/node.gyp
===================================================================
--- node-v12.21.0.orig/node.gyp
+++ node-v12.21.0/node.gyp
@@ -475,7 +475,7 @@
               'action_name': 'run_mkcodecache',
               'process_outputs_as_sources': 1,
               'inputs': [
-                '<(mkcodecache_exec)',
+                @MAYBE_WRAPPER@ '<(mkcodecache_exec)',
               ],
               'outputs': [
                 '<(SHARED_INTERMEDIATE_DIR)/node_code_cache.cc',
@@ -500,7 +500,7 @@
               'action_name': 'node_mksnapshot',
               'process_outputs_as_sources': 1,
               'inputs': [
-                '<(node_mksnapshot_exec)',
+                @MAYBE_WRAPPER@ '<(node_mksnapshot_exec)',
               ],
               'outputs': [
                 '<(SHARED_INTERMEDIATE_DIR)/node_snapshot.cc',
Index: node-v12.21.0/tools/v8_gypfiles/v8.gyp
===================================================================
--- node-v12.21.0.orig/tools/v8_gypfiles/v8.gyp
+++ node-v12.21.0/tools/v8_gypfiles/v8.gyp
@@ -133,7 +133,7 @@
         {
           'action_name': 'run_torque_action',
           'inputs': [  # Order matters.
-            '<(PRODUCT_DIR)/<(EXECUTABLE_PREFIX)torque<(EXECUTABLE_SUFFIX)',
+            @MAYBE_WRAPPER@ '<(PRODUCT_DIR)/<(EXECUTABLE_PREFIX)torque<(EXECUTABLE_SUFFIX)',
             '<@(torque_files)',
           ],
           'outputs': [
@@ -255,7 +255,7 @@
         {
           'action_name': 'generate_bytecode_builtins_list_action',
           'inputs': [
-            '<(PRODUCT_DIR)/<(EXECUTABLE_PREFIX)bytecode_builtins_list_generator<(EXECUTABLE_SUFFIX)',
+            @MAYBE_WRAPPER@ '<(PRODUCT_DIR)/<(EXECUTABLE_PREFIX)bytecode_builtins_list_generator<(EXECUTABLE_SUFFIX)',
           ],
           'outputs': [
             '<(generate_bytecode_builtins_list_output)',
@@ -446,7 +446,7 @@
             ],
           },
           'inputs': [
-            '<(mksnapshot_exec)',
+            @MAYBE_WRAPPER@ '<(mksnapshot_exec)',
           ],
           'outputs': ["<(INTERMEDIATE_DIR)/snapshot.cc"],
           'process_outputs_as_sources': 1,
@@ -1394,7 +1394,7 @@
         {
           'action_name': 'run_gen-regexp-special-case_action',
           'inputs': [
-            '<(PRODUCT_DIR)/<(EXECUTABLE_PREFIX)gen-regexp-special-case<(EXECUTABLE_SUFFIX)',
+            @MAYBE_WRAPPER@ '<(PRODUCT_DIR)/<(EXECUTABLE_PREFIX)gen-regexp-special-case<(EXECUTABLE_SUFFIX)',
           ],
           'outputs': [
             '<(SHARED_INTERMEDIATE_DIR)/src/regexp/special-case.cc',
```

**Step 5**: Add $buildroot_root_directory/package/nodejs/Config.in.host to $buildroot_root_directory/package/Config.in.host

```
menu "Host utilities"

        source "package/mtools/Config.in.host"
        source "package/mxsldr/Config.in.host"
        source "package/nodejs/Config.in.host"
        source "package/ntfs-3g/Config.in.host"
        source "package/omap-u-boot-utils/Config.in.host"
```

**Step 6**: Select _nodejs_ in "Target packages > Interpreter languages and scripting" and _host nodejs_ in "Host utilities" using _make menuconfig_ in Buildroot $CONFIG_DIR
