### ISSUE TITLE
Why is stream file handle not closed by GC?

### ISSUE THREAD

**Issue by misos1** [nodejs/help#3345]
* **Node.js Version**: v15.12.0
* **OS**: Darwin Kernel Version 20.3.0
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: fs

For example when using `fs.createReadStream` and not using result then it is garbage collected but seems file handle is not closed:

```js
require("posix").setrlimit("nofile", { soft: 1000 });
require("fs").writeFileSync("file", "file");

let created = 0;
let collected = 0;
let register = new FinalizationRegistry(() => collected++);

setInterval(function()
{
	console.log("created", created, " collected", collected);
	for(let i = 0; i < 100; i++)
	{
		let stream = require("fs").createReadStream("file");
		register.register(stream);
		created++;
	}
	if(typeof global.gc == "function") global.gc();
}, 1000);
```

When run with `node --expose-gc` gives for example this:
```
created 0  collected 0
created 100  collected 0
created 200  collected 100
created 300  collected 200
created 400  collected 300
created 500  collected 400
created 600  collected 500
created 700  collected 600
created 800  collected 700
created 900  collected 800
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'file'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: 'file'
}
```

I would be interested to know some rationale behind this (as I was not able to find on internet).

**Comment by gireeshpunathil** [comment]
@nodejs/streams

**Comment by ronag** [comment]
You should not rely on GC to free resources. You need to call `.destroy()` on stream you are done with.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.

**Comment by misos1** [comment]
But also memory is a resource. I expected something like "it is just our design decision". Python has (or had) such closing files but maybe it was good, maybe not. I would just expect at least something like Python `with` or RAII. I am not sure whether GC helps me so much if I can have an even worse problem with leaking files unlike in languages like Rust or modern C++ where resource freeing is automatic thanks to RAII.

**Comment by benjamingr** [comment]
> I would just expect at least something like Python with

There is a proposal for `using` in JavaScript https://github.com/tc39/proposal-explicit-resource-management

**Comment by gireeshpunathil** [comment]
looks like this can be re-opened, as there is still discussion happening
