### ISSUE TITLE
windows drive letter is set as protocol in an URL class object

### ISSUE THREAD

**Issue by MartyHav** [nodejs/help#3348]
* **Node.js Version**: 14.0.0
* **OS**: Windows
* **Scope**:runtime
* **Module**: url

When I construct an URL object, a given base URL object ( and its protocol scheme ) will be ignored, when the given url is a full path containing a drive letter. 
Drive letter on its own is set as protocol in URL class object.
Not sure if this is intended. 

```js
const URL = require("url");
const baseUrl = URL.pathToFileURL("c:/foo/bar);

const url = "c:/foo/bar";

const urlObject = new URL.URL(url, baseUrl);

urlObject.protocol // "c:"

```
I would have expected that the file protocol of baseUrl would be used.

**Comment by RaisinTen** [comment]
The base URL is disregarded as the input is not a relative-URL string.
Refs: https://url.spec.whatwg.org/#concept-base-url

**Comment by MartyHav** [comment]
@RaisinTen Thanks, I get it.

And when I am right a path such "/Users/foo/bar" is a relative path.

This little code snippet leads to different behaviour in macOS and Windows.

```js
const URL = require('url');
const baseUrl = URL.pathToFileURL(process.cwd() + '/');
URL.fileURLToPath(new URL.URL(__dirname, baseUrl)); // throws an error in windows - works fine in macOS
```

In macOS `__dirname` will give back a relative path ( regarding the specs of WHATWG ) and it use the file scheme of baseUrl. 
And in Windows it is treated as a full path and it will ignore baseUrl and its file scheme.
And when we want to convert it via fileURLToPath we get an error there : "URL is not a file scheme".

**Comment by RaisinTen** [comment]
You could use `'file://' + __dirname` instead of `__dirname` directly for the input URL to prevent the platform dependent error.

**Comment by marsonya** [comment]
Hope the answers were helpful.
A workaround/resolution has been provided so I am closing this issue.
Please feel free to reopen this issue if there is more to be added.
