### ISSUE TITLE
Request Feature come back

### ISSUE THREAD

**Issue by Arsyad07-ByArsyad06** [nodejs/help#3349]
# why when i make a bot ...?

the bot is doesn't work in 15.5.1 when im press ```node src/index.js```
is error but when im ```cd src``` and ```node index.js``` is worked ... ?
whether in version 15.5.1 the feature has been removed?...

### Ok Thanks OpenJS Foundation was Created Node.JS :)

**Comment by Ayase-252** [comment]
What version of node you are comparing to? Could you please paste message stack you saw?

I don't think we introduce any sematic change regarding CLI usage `node filePath`.

**Comment by marsonya** [comment]
From what I make out of the issue description is that there is a `src` folder housing the `index.js` file.
So, there is no way `node index.js` is gonna work at project root level unless there was a `index.js` file available in the root folder.

Ultimately, if your `index.js` file is located in `src` folder, you will have to use `node src/index.js` command.
