### ISSUE TITLE
Node.js error opencv

### ISSUE THREAD

**Issue by hbklenin** [nodejs/help#335]
Hello ,I need your help..!! please help me....
I can not install opencv.
when I run npm install opencv
show this:
npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\server\Documents\IMAGMED\npm-debug.log

C:\Users\server\Documents\IMAGMED>npm install fallback-to-build
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\server\AppData\
\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "fallback-to-build"

npm ERR! node v4.6.0
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/fallbac
k-to-build
npm ERR! 404
npm ERR! 404  'fallback-to-build' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\server\Documents\IMAGMED\npm-debug.log

C:\Users\server\Documents\IMAGMED>npm install opencv

> opencv@6.0.0 install C:\Users\server\Documents\IMAGMED\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-opencv.s3.amazonaws.com/opencv
/v6.0.0/Release/node-v46-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@4.6.0 (
node-v46 ABI) (falling back to source compile with node-gyp)
C:\Users\server\Documents\IMAGMED\node_modules\opencv\utils\find-opencv.js:57
                throw new Error("ERROR: couldn't read the lib directory " + err)
;
                ^

Error: ERROR: couldn't read the lib directory Error: ENOENT: no such file or dir
ectory, scandir 'C:\OpenCV\build\x86\vc12;% OPENCV_DIR% \ bin\lib'
    at C:\Users\server\Documents\IMAGMED\node_modules\opencv\utils\find-opencv.j
s:57:23
    at FSReqWrap.oncomplete (fs.js:82:15)
gyp: Call to 'node utils/find-opencv.js --libs' returned exit status 1 while in
binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\server\Documents\IMAGMED\n
ode_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\server\Docum
ents\IMAGMED\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback
-to-build" "--module=C:\Users\server\Documents\IMAGMED\node_modules\opencv
\build\opencv\v6.0.0\Release\node-v46-win32-ia32\opencv.node" "--module_na
me=opencv" "--module_path=C:\Users\server\Documents\IMAGMED\node_modules\o
pencv\build\opencv\v6.0.0\Release\node-v46-win32-ia32" "--python=c:\python
27"
gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Users\server\Documents\IMAGMED\node_modules\node-gyp\bin\node-gyp.js confi
gure --fallback-to-build --module=C:\Users\server\Documents\IMAGMED\node_modules
\opencv\build\opencv\v6.0.0\Release\node-v46-win32-ia32\opencv.node --module_nam
e=opencv --module_path=C:\Users\server\Documents\IMAGMED\node_modules\opencv\bui
ld\opencv\v6.0.0\Release\node-v46-win32-ia32 --python=c:\python27' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\server\Documen
ts\IMAGMED\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:
29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\serv
er\Documents\IMAGMED\node_modules\opencv\node_modules\node-pre-gyp\bin\n
ode-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv
node-pre-gyp ERR! node -v v4.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\server\Documents\IM
AGMED\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --modu
le=C:\Users\server\Documents\IMAGMED\node_modules\opencv\build\opencv\v6.0.0\Rel
ease\node-v46-win32-ia32\opencv.node --module_name=opencv --module_path=C:\Users
\server\Documents\IMAGMED\node_modules\opencv\build\opencv\v6.0.0\Release\node-v
46-win32-ia32 --python=c:\python27' (1)
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre
-gyp@0.6.30
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\server\AppData\
\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "opencv"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\server\Documents\IMAGMED\npm-debug.log

C:\Users\server\Documents\IMAGMED>npm install opencv-node
npm WARN prefer global coffee-script@1.11.1 should be installed with -g

> opencv-node@0.2.6 install C:\Users\server\Documents\IMAGMED\node_modules\openc
> v-node
> node-gyp configure build

C:\Users\server\Documents\IMAGMED\node_modules\opencv-node>if not defined npm_co
nfig_node_gyp (node "C:\Users\server\AppData\Roaming\npm\node_modules\npm\bin\no
de-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure build )  else
 (node "" configure build )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
MSBUILD : error MSB3428: No se pudo cargar el componente "VCBuild.exe" de Visua
l C++. Para corregir este problema, 1) instale .NET Framework 2.0 SDK, 2) insta
le Microsoft Visual Studio 2005 o 3) agregue la ubicación del componente a la r
uta de acceso del sistema si está instalado en otro lugar.  [C:\Users\server\Do
cuments\IMAGMED\node_modules\opencv-node\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\server\AppData\Roaming\npm\n
ode_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\server\AppDa
ta\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "
configure" "build"
gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv-node
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\server\AppData\
\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "opencv-node"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! opencv-node@0.2.6 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-node@0.2.6 install script 'node-gyp configure buil
d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\server\Documents\IMAGMED\npm-debug.log

C:\Users\server\Documents\IMAGMED>npm install Opencv

> opencv@6.0.0 install C:\Users\server\Documents\IMAGMED\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-opencv.s3.amazonaws.com/opencv
/v6.0.0/Release/node-v46-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@4.6.0 (
node-v46 ABI) (falling back to source compile with node-gyp)
C:\Users\server\Documents\IMAGMED\node_modules\opencv\utils\find-opencv.js:57
                throw new Error("ERROR: couldn't read the lib directory " + err)
;
                ^

Error: ERROR: couldn't read the lib directory Error: ENOENT: no such file or dir
ectory, scandir 'C:\OpenCV\build\x86\vc12;% OPENCV_DIR% \ bin\lib'
    at C:\Users\server\Documents\IMAGMED\node_modules\opencv\utils\find-opencv.j
s:57:23
    at FSReqWrap.oncomplete (fs.js:82:15)
gyp: Call to 'node utils/find-opencv.js --libs' returned exit status 1 while in
binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\server\Documents\IMAGMED\n
ode_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\server\Docum
ents\IMAGMED\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback
-to-build" "--module=C:\Users\server\Documents\IMAGMED\node_modules\opencv
\build\opencv\v6.0.0\Release\node-v46-win32-ia32\opencv.node" "--module_na
me=opencv" "--module_path=C:\Users\server\Documents\IMAGMED\node_modules\o
pencv\build\opencv\v6.0.0\Release\node-v46-win32-ia32" "--python=c:\python
27"
gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Users\server\Documents\IMAGMED\node_modules\node-gyp\bin\node-gyp.js confi
gure --fallback-to-build --module=C:\Users\server\Documents\IMAGMED\node_modules
\opencv\build\opencv\v6.0.0\Release\node-v46-win32-ia32\opencv.node --module_nam
e=opencv --module_path=C:\Users\server\Documents\IMAGMED\node_modules\opencv\bui
ld\opencv\v6.0.0\Release\node-v46-win32-ia32 --python=c:\python27' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\server\Documen
ts\IMAGMED\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:
29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\serv
er\Documents\IMAGMED\node_modules\opencv\node_modules\node-pre-gyp\bin\n
ode-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv
node-pre-gyp ERR! node -v v4.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\server\Documents\IM
AGMED\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --modu
le=C:\Users\server\Documents\IMAGMED\node_modules\opencv\build\opencv\v6.0.0\Rel
ease\node-v46-win32-ia32\opencv.node --module_name=opencv --module_path=C:\Users
\server\Documents\IMAGMED\node_modules\opencv\build\opencv\v6.0.0\Release\node-v
46-win32-ia32 --python=c:\python27' (1)
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre
-gyp@0.6.30
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\server\AppData\
\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "Opencv"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\server\Documents\IMAGMED\npm-debug.log

C:\Users\server\Documents\IMAGMED>

**Comment by lordKnighton** [comment]
show me your npm & node -v

**Comment by addaleax** [comment]
> `% OPENCV_DIR%`

There’s a typo in this, maybe some environment variable of yours contains that?

> `npm install fallback-to-build`

That’s supposed to be `npm install --fallback-to-build`.

**Comment by hbklenin** [comment]
@lordKnighton Thanks for answering, npm -v 3.10.9 and node v4.2.2......... and I know not to do to install opencv, I'm working on windows, I'm desperate

**Comment by hbklenin** [comment]
@addaleax Hello,
I have set my environment variables, view C: \ OpenCV \ build \ x86 \ VC12;% OPENCV_DIR% \ bin

It is misconfigured my environment variable? I'm working on windows

and this error I don´t know node-pre-gyp ERR! Tried to download: https://node-opencv.s3.amazonaws.com/opencv
/v6.0.0/Release/node-v46-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@4.2.2 (
node-v46 ABI) (falling back to source compile with node-gyp)

I run npm install fallback-to-build but and show this:

C:\Users\server\Documents\IMAGMED>npm install opencv

> opencv@6.0.0 install C:\Users\server\Documents\IMAGMED\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-opencv.s3.amazonaws.com/opencv
/v6.0.0/Release/node-v46-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@4.2.2 (
node-v46 ABI) (falling back to source compile with node-gyp)
C:\Users\server\Documents\IMAGMED\node_modules\opencv\utils\find-opencv.js:57
                throw new Error("ERROR: couldn't read the lib directory " + err)
;
                ^

Error: ERROR: couldn't read the lib directory Error: ENOENT: no such file or dir
ectory, scandir 'C:\OpenCV\build\x86\vc12;% OPENCV_DIR% \ bin\lib'
    at C:\Users\server\Documents\IMAGMED\node_modules\opencv\utils\find-opencv.j
s:57:23
    at FSReqWrap.oncomplete (fs.js:82:15)
gyp: Call to 'node utils/find-opencv.js --libs' returned exit status 1 while in
binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\server\Documents\IMAGMED\n
ode_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\server\\Docum
ents\\IMAGMED\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback
-to-build" "--module=C:\\Users\\server\\Documents\\IMAGMED\\node_modules\\opencv
\\build\\opencv\\v6.0.0\\Release\\node-v46-win32-ia32\\opencv.node" "--module_na
me=opencv" "--module_path=C:\\Users\\server\\Documents\\IMAGMED\\node_modules\\o
pencv\\build\\opencv\\v6.0.0\\Release\\node-v46-win32-ia32" "--python=c:\\python
27" "--msvs_version=2015"
gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Users\server\Documents\IMAGMED\node_modules\node-gyp\bin\node-gyp.js confi
gure --fallback-to-build --module=C:\Users\server\Documents\IMAGMED\node_modules
\opencv\build\opencv\v6.0.0\Release\node-v46-win32-ia32\opencv.node --module_nam
e=opencv --module_path=C:\Users\server\Documents\IMAGMED\node_modules\opencv\bui
ld\opencv\v6.0.0\Release\node-v46-win32-ia32 --python=c:\python27 --msvs_version
=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\server\Documen
ts\IMAGMED\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:
29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\serv
er\\Documents\\IMAGMED\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\n
ode-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\server\Documents\IM
AGMED\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --modu
le=C:\Users\server\Documents\IMAGMED\node_modules\opencv\build\opencv\v6.0.0\Rel
ease\node-v46-win32-ia32\opencv.node --module_name=opencv --module_path=C:\Users
\server\Documents\IMAGMED\node_modules\opencv\build\opencv\v6.0.0\Release\node-v
46-win32-ia32 --python=c:\python27 --msvs_version=2015' (1)
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre
-gyp@0.6.30
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\server\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "opencv"
npm ERR! node v4.2.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\server\Documents\IMAGMED\npm-debug.log

C:\Users\server\Documents\IMAGMED>

**Comment by addaleax** [comment]
> It is misconfigured my environment variable?

yes, there should be no spaces in it (or at least no space after `%`).

**Comment by hbklenin** [comment]
@addaleax  look this:


C:\Users\server\Documents\IMAGMED>npm install opencv --fallback-to-build

> opencv@6.0.0 install C:\Users\server\Documents\IMAGMED\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-opencv.s3.amazonaws.com/opencv
/v6.0.0/Release/node-v46-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@4.2.2 (
node-v46 ABI) (falling back to source compile with node-gyp)
C:\Users\server\Documents\IMAGMED\node_modules\opencv\utils\find-opencv.js:57
                throw new Error("ERROR: couldn't read the lib directory " + err)
;
                ^

Error: ERROR: couldn't read the lib directory Error: ENOENT: no such file or dir
ectory, scandir 'C:\OpenCV\build\x86\vc12;%OPENCV_DIR%\bin\lib'
    at C:\Users\server\Documents\IMAGMED\node_modules\opencv\utils\find-opencv.j
s:57:23
    at FSReqWrap.oncomplete (fs.js:82:15)
gyp: Call to 'node utils/find-opencv.js --libs' returned exit status 1 while in
binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\server\Documents\IMAGMED\n
ode_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\server\\Docum
ents\\IMAGMED\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback
-to-build" "--module=C:\\Users\\server\\Documents\\IMAGMED\\node_modules\\opencv
\\build\\opencv\\v6.0.0\\Release\\node-v46-win32-ia32\\opencv.node" "--module_na
me=opencv" "--module_path=C:\\Users\\server\\Documents\\IMAGMED\\node_modules\\o
pencv\\build\\opencv\\v6.0.0\\Release\\node-v46-win32-ia32" "--python=c:\\python
27" "--msvs_version=2015"
gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Users\server\Documents\IMAGMED\node_modules\node-gyp\bin\node-gyp.js confi
gure --fallback-to-build --module=C:\Users\server\Documents\IMAGMED\node_modules
\opencv\build\opencv\v6.0.0\Release\node-v46-win32-ia32\opencv.node --module_nam
e=opencv --module_path=C:\Users\server\Documents\IMAGMED\node_modules\opencv\bui
ld\opencv\v6.0.0\Release\node-v46-win32-ia32 --python=c:\python27 --msvs_version
=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\server\Documen
ts\IMAGMED\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:
29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\serv
er\\Documents\\IMAGMED\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\n
ode-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\server\Documents\IMAGMED\node_modules\opencv
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\server\Documents\IM
AGMED\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --modu
le=C:\Users\server\Documents\IMAGMED\node_modules\opencv\build\opencv\v6.0.0\Rel
ease\node-v46-win32-ia32\opencv.node --module_name=opencv --module_path=C:\Users
\server\Documents\IMAGMED\node_modules\opencv\build\opencv\v6.0.0\Release\node-v
46-win32-ia32 --python=c:\python27 --msvs_version=2015' (1)
npm WARN In opencv@6.0.0 replacing bundled version of node-pre-gyp with node-pre
-gyp@0.6.30
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\server\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "opencv" "--fallbac
k-to-build"
npm ERR! node v4.2.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallb
ack-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\server\Documents\IMAGMED\npm-debug.log

C:\Users\server\Documents\IMAGMED>

**Comment by sharath-c-n** [comment]
I'm having the same issue.

**Comment by lordKnighton** [comment]
@hbklenin Are you still having problems with this?  

@dindar123 how's is your progress with this problem?
@sharath-c-n  did you already try the suggestions above, provided by @addaleax

**Comment by hbklenin** [comment]
@lordKnighton Yes, I can`t install....!!!

**Comment by lordKnighton** [comment]
I'm gonna go with the obvious here. I assume you have followed the: `Specific for Windows` section correct? 


----
`disclaimer`:  I have zero experience with this technology. So I plan to refer you to someone who has experience to extensive experience with opencv.

**Comment by lordKnighton** [comment]
@hbklenin have you solved this issue?
