### ISSUE TITLE
prefix -g is not recognized as internal or external command

### ISSUE THREAD

**Issue by gitChicoHub** [nodejs/help#3352]
Hi client team:

The problem that I am getting when installing new modules (i.e., fs-extra, fs) using the npm command is:

'CALL "C:\ProgramTools\nodejs\\node.exe" "C:\ProgramTools\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command 

Can you provide your feedback? I provided more information below.
I would appreciate your help.
/Chic0

 
// Configuration ++++++++++++
* **Node.js Version**:     v14.16.0
* **OS**:                          Windows 10 x64 10.0.19042
* **Scope (install, code, runtime, meta, other?)**: MS Visual Studio Code version 1.55.2
* **Module (and version) (if relevant)**:       fs, fs-extra

<!-- Please write your issue here and remove this line and the example code part. If relevant, provide some code following the example:
// ISSUE-1 +++++++++++++++++
created a folder
executed: npm init -y
executed; npm install fs

// LOG INFORMATION FROM Terminal Window:
**'CALL "C:\ProgramTools\nodejs\\node.exe" "C:\ProgramTools\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,**
operable program or batch file.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN reading_a_file@1.0.0 No description
npm WARN reading_a_file@1.0.0 No repository field.

+ fs@0.0.1-security
added 1 package and audited 1 package in 0.392s
found 0 vulnerabilities

// ISSUE-2 +++++++++++++++++
executed; npm install fs-extra

// LOG INFORMATION FROM Terminal Window:
**'CALL "C:\ProgramTools\nodejs\\node.exe" "C:\ProgramTools\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,**       
operable program or batch file.
npm WARN reading_a_file@1.0.0 No description
npm WARN reading_a_file@1.0.0 No repository field.

+ fs-extra@10.0.0
added 4 packages from 2 contributors and audited 5 packages in 0.649s
found 0 vulnerabilities

// SAMPLE CODE:
var fs = require('fs');
 
// read file sample.txt
var data = fs.readFileSync('./input_files/sample.txt');
console.log("Reading file completed : " + new Date().toISOString());
console.log("After readFileSync statement : " + new Date().toISOString());

**Comment by marsonya** [comment]
Can you share the `npm command` that throws this error? I mean the exact phrase that you are using.

**Comment by gitChicoHub** [comment]
Hi, Marsonya,

If you expand the message above, I included the npm command that I use.  It happened two times when installing node modules.
But here you have of the first issue:
// ISSUE-1 +++++++++++++++++
created a folder
executed: npm init -y
executed; npm install fs

// LOG INFORMATION FROM Terminal Window:
**'CALL "C:\ProgramTools\nodejs\\node.exe" "C:\ProgramTools\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,**
operable program or batch file.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN reading_a_file@1.0.0 No description
npm WARN reading_a_file@1.0.0 No repository field.

+ fs@0.0.1-security
added 1 package and audited 1 package in 0.392s
found 0 vulnerabilities

Let me know if this is what you are looking for.
Thank you for your help.
/Chic0

**Comment by marsonya** [comment]
This looks like a [npm](https://github.com/npm/cli) issue. I would suggest opening an issue in the [npm/cli repo](https://github.com/npm/cli/issues).
