### ISSUE TITLE
Python Child Process Stdout does not work

### ISSUE THREAD

**Issue by esmeevandenberg** [nodejs/help#3354]
* **Node.js Version**:  v14.16.1
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: 

Hi, 

Currently I have developed a very basic js and python script. 
The problem is that the python text is not displayed after running the JS file in the CMD. 

Does someone see what I am doing wrong? 

```js
const {spawn} = require('child_process')
const child = spawn('python3', ['hello.py'])


child.stdout.on('data', (data) => {
  console.log(data.toString());
});

```
-->

Python Code for testing: 
`print("hello from Python")`

**Comment by RaisinTen** [comment]
The code invoked the python code successfully for me. Could you please run this code instead? I have added a callback to log any data from the stderr of the spawned child process to the console so that we can know if there is any error.
```js
const {spawn} = require('child_process')
const child = spawn('python3', ['hello.py'])


child.stdout.on('data', (data) => {
  console.log(data.toString());
});

child.stderr.on('data', (data) => {
  console.log(data.toString());
});
```

**Comment by esmeevandenberg** [comment]
Thank you for your reply! I found that as well. 

But if I run the code, the error is displayed as follows: 
Error: spawn UNKNOWN
←[90m    at ChildProcess.spawn (internal/child_process.js:403:11)←[39m
←[90m    at spawn (child_process.js:553:9)←[39m
    at Object.<anonymous> (C:\Users\esmee\EthereumScriptie\scriptie.js:14:13)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  errno: ←[33m-4094←[39m,
  code: ←[32m'UNKNOWN'←[39m,
  syscall: ←[32m'spawn'←[39m


I have already checked the app aliases, but it does not help

**Comment by RaisinTen** [comment]
Do you get the required message printed to the console when you run `python3 hello.py` from the same directory?

>I have already checked the app aliases, but it does not help

What is the app alias?

**Comment by esmeevandenberg** [comment]
Thanks, found the solution! Seemed like python3 was not found. 

Solved it with the following post: 
https://stackoverflow.com/questions/40914108/bash-python3-command-not-found-windows-discord-py
