### ISSUE TITLE
How can I use Jmeter desktop application as web app and expose this on some port ?

### ISSUE THREAD

**Issue by gg-gg-v1** [nodejs/help#3355]
As we know Jmeter is desktop based application which will get launched in our OS and we can use it to do performance testing but what if I want to use it as web application rather than desktop application.

How can I use Jmeter desktop application as web app and expose this on some port ?

I tried following but none of them launched Jmeter as webapp.

1. Converting the jmeter desktop application to webapp using webswing, java web start but was not successful in that.
2. Running the jmeter jar directly in rest controller to launch it as webapp but it did not launch as webapp.
3. Also tried to run the jmeter docker image but that also did not help. 

Can anyone please tell me ? do we have web app of jmeter or web version of jmeter so that I can use it as webapp and access it from web browser via some port ? like this **localhost:8080/jmeter**

**Comment by gireeshpunathil** [comment]
@gg-gg-v1 - this project does not maintain jmeter, you may pls ask this question in their repo.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
