### ISSUE TITLE
C++ Addon - How to check if running in the main thread or not from a Node.js native addon?

### ISSUE THREAD

**Issue by JCMais** [nodejs/help#3356]
* **Node.js Version**: v16
* **OS**: Unix / Windows
* **Scope (install, code, runtime, meta, other?)**:  code, runtime

This is somewhat relevant to https://github.com/nodejs/help/issues/1886

I have an addon that needs to call a cleanup function **only** in the main thread (libcurl cleanup), currently, the only ways to add a cleanup hook are using `AtExit` or `AddEnvironmentCleanupHook`, but those run for each thread, including the main one.

Is there any way for me to check if the code is running in the main thread or not?

I see that there is a `is_main_thread()` function available inside the `Environment` instance (added with Node.js v11): https://github.com/nodejs/node/blob/f607e169612ff60a00f456f3c698a6b41792a8f5/src/env-inl.h#L707-L709

However, the add-on code cannot access the Environment class itself, as it is not exposed by Node.js.

Theoretically, I could retrieve this by calling the Node.js `worker_thread` module directly from the addon, but this does not seem right, as it would add unnecessary context-switching.

**Comment by JCMais** [comment]
Hi @addaleax , basically I'm trying to make my library ([`node-libcurl`](https://github.com/JCMais/node-libcurl)) work with the threading support now available in Node.js.

Right now `curl_global_init` is called directly from JS using a function exposed by the addon:
https://github.com/JCMais/node-libcurl/blob/1563bb7699eb9b22989058a0d018c59a460aaf37/lib/Curl.ts#L73-L75

So it is easy to make sure that this only runs in the main thread (by checking `isMainThread`).

Now about `curl_global_cleanup`,

> We recommend you do not run libcurl from any module that may be unloaded dynamically. This behavior may be addressed in the future.

I think I missed that part of the documentation, or just ignored it when I first read it. In this case, it seems that it is not feasible to add support for worker threads at all. I will try to get in touch with the maintainers of libcurl and check if this is still the case.

In the meantime, ignoring the above point, `curl_global_cleanup` is currently called using the `AtExit` hook, which does not really work with worker threads (as each thread calls the AtExit callback, and thus `curl_global_cleanup`).

https://github.com/JCMais/node-libcurl/blob/b8d0fac0e820645088ad4ab68c790b24fb3d4d15/src/node_libcurl.cc#L22-L26

I will take a look at using a shared counter like you said, thank you for the suggestion!

**Comment by addaleax** [comment]
> So it is easy to make sure that this only runs in the main thread (by checking `isMainThread`).

That kind of begs the question, what happens if the first time the addon is loaded happens on a worker thread?

**Comment by JCMais** [comment]
> That kind of begs the question, what happens if the first time the addon is loaded happens on a worker thread?

Good thinking, in this case, it is necessary to require the addon or call `globalInit` manually in the main thread, as libcurl cannot be initialized outside of the main thread.
