### ISSUE TITLE
Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by Evox2008** [nodejs/help#3359]
Node.js 13.14.0:
Win7:
  
After installation, show the following error

C:\blockpeer>start.bat

C:\blockpeer>npm i   && node src/index.js
audited 109 packages in 1.447s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- C:\blockpeer\src\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962
:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:838:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1022:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\blockpeer\src\index.js:2:20)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1118:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:1
0)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\blockpeer\\src\\index.js'←[39m ]
}

**Comment by Ayase-252** [comment]
According to [change log](https://nodejs.org/api/fs.html#fs_promises_api), you have to use at least Node.js v14.0.0. Otherwise, you should use `require('fs').promises`.

I'd recommand you upgrade Node.js to latest v14 if possible, since v13 has reached End-of-Life long time ago.

**Comment by Evox2008** [comment]
Hi Ayase

I would use v14 if my system was running win8.1 or later. However, on Win7 only version up to 13 are supported...

**Comment by Ayase-252** [comment]
Or, you could use `require('fs').promises`, which is both supported by both v14 and v13, if you have to maintain compatibility between your machines.

**Comment by Evox2008** [comment]
Where would I add this function please?

**Comment by Ayase-252** [comment]
@Evox2008

Did you copy my code in last comment? The quote `"` is not quite right, since I'm typing from my phone.

I tried on v12, it works

```
const fsp = require('fs').promises;
```

**Comment by Evox2008** [comment]
yeay! worked, thank you!!!

**Comment by Evox2008** [comment]
Thanks again!
