### ISSUE TITLE
Need to install node v4 on old system. Is there any way?

### ISSUE THREAD

**Issue by ismael-rivera** [nodejs/help#336]
I have an old Mac Pro 3'1 (late 2008 model) running on OS X 10.6.8 that I am using as a backup right now(no choice). I can't upgrade beyond 10.6.8, there's not even a DVD drive on this thing anymore. However, it's all I have right now and I need to install nodejs in order to setup a dev environment for a ReactJS project. I've already checked the documentation and tried to N install the upgrade but I can't get any further on terminal beyond v0.12. Is there any way, at all, that I can upgrade to at the very least to v4.x of node? React router won't npm install without it.

**Comment by bnoordhuis** [comment]
v4.x is compiled with `-mmacosx-version-min=10.5` so in theory it should work (although we don't and didn't test 10.6 so YMMV.)  Have you tried the official binaries from nodejs.org?

**Comment by lordKnighton** [comment]
Try as well: ✨ Homebrew✨  via homebrew you can install node.js  by extension you should be able to run react apps, at least that's the idea. If you need any more help let us know


link: https://www.youtube.com/watch?v=0WrrWKqVppY

**Comment by ismael-rivera** [comment]
Thanks but I already have homebrew. I thought I had installed node using NPM but it was actually via brew. Ran brew update node and of course no go (it went straight to v7, which I knew would not work). I then unlinked the node version I had and brew installed homebrew/versions/node4-lts and this is what I got spit back out at me:

```
Warning: You are using macOS 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```
It then did it's downloading bar thing and went into make install and gave me the following output:

```
Last 15 lines from /Users/myusername/Library/Logs/Homebrew/node4-lts/02.make:
cc1plus: error: unrecognized command line option "-std=gnu++0x"
make[1]: *** [/private/tmp/node4-lts-20161027-5116-1k5rc46/node-v4.6.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-port.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/private/tmp/node4-lts-20161027-5116-1k5rc46/node-v4.6.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-death-test.o] Error 1
make[1]: *** [/private/tmp/node4-lts-20161027-5116-1k5rc46/node-v4.6.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-test-part.o] Error 1
make[1]: *** [/private/tmp/node4-lts-20161027-5116-1k5rc46/node-v4.6.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-filepath.o] Error 1
cc1plus: error: unrecognized command line option "-std=gnu++0x"
cc1plus: error: unrecognized command line option "-std=gnu++0x"
cc1plus: error: unrecognized command line option "-std=gnu++0x"
cc1plus: error: unrecognized command line option "-std=gnu++0x"
make[1]: *** [/private/tmp/node4-lts-20161027-5116-1k5rc46/node-v4.6.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-typed-test.o] Error 1
make[1]: *** [/private/tmp/node4-lts-20161027-5116-1k5rc46/node-v4.6.1/out/Release/obj.target/gtest/deps/gtest/src/gtest-printers.o] Error 1
make[1]: *** [/private/tmp/node4-lts-20161027-5116-1k5rc46/node-v4.6.1/out/Release/obj.target/gtest/deps/gtest/src/gtest_main.o] Error 1
make[1]: *** [/private/tmp/node4-lts-20161027-5116-1k5rc46/node-v4.6.1/out/Release/obj.target/gtest/deps/gtest/src/gtest.o] Error 1
make: *** [node] Error 2
```

**Comment by lordKnighton** [comment]
what about cloud development, Is that an option for you? 

sites : c9.io and https://www.nitrous.io/

**Comment by ismael-rivera** [comment]
Maybe. All the more I'd still would like to be able to develop on my private server. Any help much appreciated.

**Comment by lordKnighton** [comment]
So why not v7, try to get it again, and let's do some testing lets see how far we can get down the rabbit hole, before it turns erroneous. Try to install react with it.

**Comment by SomeoneWeird** [comment]
Hey @ismael-rivera,

Try installing either `nvm` or `n` and using that as your node version manager, if you install `nvm` then it's simple as running `nvm install 4` and it will install the latest version of v4.

@lordKnighton There's probably a reason that he wants version 4 specifically, we can't just assume that everything will work with 7 :)

**Comment by ismael-rivera** [comment]
@lordKnighton First of all, thank you so much for the input. I really do appreciate the advice. However, if you read above, you'll see I already tried installing v7. No luck. In fact, the only version from v7 on down that successfully installed was 0.12. Everything else including v4, v5 and v6 gives me errors. @lordKnighton Thank you! That is an excellent point. However, in this situation I'll be glad to get whatever I can get that can run reactjs, preferably with reactor. I asked for v4 because it's the minimum requirement for running reactor and reactjs. I read somewhere that it was able to run on OS X 10.5 and above. So It's probably the highest I'd be able to get installed on Snow Leopard, however, if I can get anything higher than v4, that would be a major plus. Sure. I just can't seem to get past 0.12. I will try nvm and n route. Thank you to everyone here. This is all very helpful.

**Comment by gibfahn** [comment]
Could you try downloading this tarball, extracting it, and then trying to run the node binary?

https://nodejs.org/dist/v4.6.1/node-v4.6.1-darwin-x64.tar.gz

If you extract it the binary is `./bin/node`

If it doesn't work please post the error.

**Comment by ismael-rivera** [comment]
@gibfahn Wait. you want me to extract the binary and drag the ./bin/node and replace it with the node in my PATH? or... Honestly Idk what to do next. I've never installed a binary manually. I tried to google it but I still can't find any specific instructions. When I do `which node ` I get the following: `/usr/local/bin/node` but when I do `open .` all I find is an alias for node which points to the original in: `/usr/local/Cellar/node/0.10.26/bin/node`. So I guess my question is: Do I switch the binary with the node alias which is in my actual PATH variable or do I go to where the original file is in /usr/local/Cellar/node/0.10.26/bin/node. Not sure what to do here.

**Comment by SomeoneWeird** [comment]
@ismael-rivera Did you follow my advice and try and use `nvm` or `n`?

**Comment by ismael-rivera** [comment]
@SomeoneWeird I did. Sorry for not posting the results. I kept getting Error: invalid version for pretty much all versions.

**Comment by ismael-rivera** [comment]
@SomeoneWeird Actually THIS is what I got. 
```
nvm install v4.0.0
######################################################################## 100.0%
Computing checksum with shasum -a 256
Provided checksum to compare to is empty.
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
Binary download failed, trying source.
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
nvm: install v4.0.0 failed!

```
This here is from nvm. Had the same results with various versions.
I think the error invalid came from trying to install n. Sorry about that. I did all of this yesterday. I had to run out so I forgot to save the logs. All I know is neither one of them worked for various versions throughout.

**Comment by gibfahn** [comment]
@ismael-rivera Sorry, never sure how much detail to go into. To try it out you don't need it in the path, you can just use the full file path by running `/path/to/node` instead of just `node`. The reason installing binaries isn't documented is that there isn't actually an install process. A binary is a self-contained thing that will just run when you open it.

Basically to run a binary you can just navigate to it in the finder and double-click on the node binary. Or if you're in the terminal you can (in any folder) download, extract, and then just run.

```bash
curl -O https://nodejs.org/dist/v4.6.1/node-v4.6.1-darwin-x64.tar.gz
tar -xvf ./node-v4.6.1-darwin-x64.tar.gz
cd node-v4.6.1/bin
./node
```

`./node` means run the file/binary called node in the current directory. If you just use `node` then the terminal will search every directory in the path for a binary called node.

**Comment by ismael-rivera** [comment]
@gibfahn Thanks for the info. I did as you said and simply opened the file it's own path and... well, my mac froze. I got that blackish screen of death with the banner in the middle asking me to restart the computer. I think I'm going to go another route. A friend of mine recommended docker, but that did not seem to work on my system either so I installed an older version of vagrant. So far so good. I'm up and running so I guess that will have to do. Thank you so much for your help. To everyone, really, thank you so much for all the advice. In the end, the solution wasn't what I was expecting but the help I got here from everyone was what helped me resolve the problem and find a viable solution. Thank you everyone. You guys are all awesome!! Thank you.

**Comment by lordKnighton** [comment]
No Problem 😄

**Comment by barracuda156** [comment]
> Thanks but I already have homebrew. I thought I had installed node using NPM but it was actually via brew. Ran brew update node and of course no go (it went straight to v7, which I knew would not work). I then unlinked the node version I had and brew installed homebrew/versions/node4-lts and this is what I got spit back out at me:
> 
> ```
> Warning: You are using macOS 10.6.
> We (and Apple) do not provide support for this old version.
> ```

@ismael-rivera MacPorts has far better support for old systems.
