### ISSUE TITLE
I really want to contribute to nodejs, how do I start?

### ISSUE THREAD

**Issue by TiseySoft-Js** [nodejs/help#3363]

**Comment by marsonya** [comment]
Contributions are always welcome to Node.js
You can find all the details regarding contribution [here](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md).

You can help by filing issues, help the community resolve issues and patching issues (via pull requests).

**Comment by gireeshpunathil** [comment]
another option is https://www.nodetodo.org . this provides a hierarchical and comprehensive list of items for new comers.

Hope this helps. closing as answered, feel free to re-open if you still need help
