### ISSUE TITLE
Can't use require("os").version() with root permission

### ISSUE THREAD

**Issue by Zyn-Ky** [nodejs/help#3365]
Hello, I'm confused is this a bug or not
I can't use `require("os").version()` while running node with root permission

Without root permission
![image](https://user-images.githubusercontent.com/67272419/117682586-6c6e7880-b1dd-11eb-8382-7f0a9d2c3eb8.png)

With root permission

![image](https://user-images.githubusercontent.com/67272419/117682740-94f67280-b1dd-11eb-88d5-510a8a906831.png)

**Comment by RedYetiDev** [comment]
Both node versions are EoL, if you can reproduce in the latest version, please open a new issue
