### ISSUE TITLE
The order of promise and nextTick

### ISSUE THREAD

**Issue by helloking000** [nodejs/help#3366]
* **Node.js Version**:  10.24.1 and 12.20.1
* **OS**: macOS Big Sur 11.1
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: 

```js
process.nextTick(() => console.log('nextTick'));
Promise.resolve().then(() => console.log('promise resolve'))
```
in 10.24.1，it outputs:
_nextTick
promise resolve_

in 12.20.1，it outputs:
_promise resolve
nextTick_

however, when I put these two lines into the callback of setTimeout:
```js
setTimeout(() => {
    Promise.resolve().then(() => console.log('promise resolve'))
    process.nextTick(() => console.log('nextTick'));
}, 0);
```
despite the version of node，the nextTick is always has the preference:
_nextTick
promise resolve_

**Comment by Ayase-252** [comment]
Tested on 12.20.1, it works as expected.

```
> node -v
v12.20.1

> node index.js
nextTick
promise resolve
```

**Comment by marsonya** [comment]
There is no bug here. The order is as expected.
You can refer to this [issue](https://github.com/nodejs/node/issues/38630) in nodejs/node for more details.

**Comment by helloking000** [comment]
This is my screen shot:

![image](https://user-images.githubusercontent.com/11470306/117927740-36400e80-b32d-11eb-8921-7a93386f7189.png)

I had tried in another computer which is macOS catalina 10.15.7. The result is diffrent from mine. Did it also depend on the os version?

**Comment by RedYetiDev** [comment]
If you can reproduce in the latest version, please open a new issue
