### ISSUE TITLE
WHATWG URL API bug with parsing url

### ISSUE THREAD

**Issue by mblandr** [nodejs/help#3369]
Hello! There is a bug with parsing url from request, when path constist more then one slash nearby at the start
Node version 16.1.0

There is a simple code
```js
const http = require('http')
const url = require('url')

const server = http.createServer((req, resp) => {
	const baseURL = req.socket.encrypted ? 'https://' : 'http://' + req.headers.host + '/'
	const parsedURL = new url.URL(req.url, baseURL)
	console.log(parsedURL)
	resp.end('Hello world\n')
})

server.listen(80, () => console.log('Working...'))
```
For this request
```console
curl http://localhost:80/test//fasdfasdf
```
I have 
```js
URL {
  href: 'http://test/fasdfasdf',
  origin: 'http://test',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'test',
  hostname: 'test',
  port: '',
  pathname: '/fasdfasdf',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```
but there are all wrong - href, origin, hostname and pathname!

**Comment by mblandr** [comment]
const http = require('http')
const url = require('url')

const server = http.createServer((req, resp) => {
	const baseURL = req.socket.encrypted ? 'https://' : 'http://' + req.headers.host + '/'
	console.log('baseURL: ' + baseURL)
	const parsedURL = new url.URL(req.url, baseURL)
	console.log('parsedURL: ' + parsedURL)
	resp.end('Hello world\n')
})

server.listen(80, () => console.log('Working...'))


Here request: 
curl http://localhost:80/test//fasdfasdf

Here console output:
baseURL: http://localhost/
parsedURL: http://localhost/test//fasdfasdf

When request is:
curl http://localhost:80/test/fasdfasdf

code working fine:
baseURL: http://localhost/
parsedURL: http://localhost/test/fasdfasdf

**Comment by aduh95** [comment]
Are you saying it's working correctly now?

Note that you need too add parentheses to your `baseURL` assignment:
```js
const baseURL = (req.socket.encrypted ? 'https://' : 'http://') + req.host + '/'
```
Otherwise, when `req.socket.encrypted`, it's going to be `https://` instead of `https://localhost/`.

**Comment by mblandr** [comment]
I'm sory, bug was when
curl http://localhost:80//fasdfasdf
not
curl http://localhost:80/test//fasdfasdf

So:
here is the code:
//begin
const http = require('http')
const url = require('url')
const server = http.createServer((req, resp) => {
	const baseURL = req.socket.encrypted ? 'https://' : 'http://' + req.headers.host + '/'
	console.log('baseURL: ' + baseURL)
	const parsedURL = new url.URL(req.url, baseURL)
	console.log('parsedURL: ')
	console.log(parsedURL)
	resp.end('Hello world\n')
})
server.listen(80, () => console.log('Working...'))
//end

here is request:
curl http://localhost//fasdfasdf 

here is the console output:
baseURL: http://localhost/
parsedURL:
URL {
  href: 'http://fasdfasdf/',
  origin: 'http://fasdfasdf',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'fasdfasdf',
  hostname: 'fasdfasdf',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
so baseurl is correct, but parsing is totally wrong

when request is 
curl http://localhost/test//fasdfasdf
or
curl http://localhost/test//fasdfasdf//
nothing is wrong
So the bug is only when path start with '//'

**Comment by mblandr** [comment]
> Are you saying it's working correctly now?
> 
> Note that you need too add parentheses to your `baseURL` assignment:
> 
> ```js
> const baseURL = (req.socket.encrypted ? 'https://' : 'http://') + req.host + '/'
> ```
> 
> Otherwise, when `req.socket.encrypted`, it's going to be `https://` instead of `https://localhost/`.



> Are you saying it's working correctly now?
> 
> Note that you need too add parentheses to your `baseURL` assignment:
> 
> ```js
> const baseURL = (req.socket.encrypted ? 'https://' : 'http://') + req.host + '/'
> ```
> 
> Otherwise, when `req.socket.encrypted`, it's going to be `https://` instead of `https://localhost/`.

Oh, yes, thanks

**Comment by aduh95** [comment]
Oh I see, this is not a bug: when the URL starts with `//`, it's a protocol relative URL (https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL) or [scheme-relative-URL string](https://url.spec.whatwg.org/#scheme-relative-url-string) as the spec calls them. Maybe this would work:

```js
const http = require('http')
const server = http.createServer((req, resp) => {
	const baseURL = (req.socket.encrypted ? 'https://' : 'http://') + req.headers.host + '/'
	console.log('baseURL: ', baseURL)
	const parsedURL = new URL(baseURL + req.url)
	console.log('parsedURL: ', parsedURL)
	resp.end('Hello world\n')
})
server.listen(80, () => console.log('Working...'))
```

**Comment by mblandr** [comment]
> Oh I see, this is not a bug: when the URL starts with `//`, it's a protocol relative URL (https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL) or [scheme-relative-URL string](https://url.spec.whatwg.org/#scheme-relative-url-string) as the spec calls them. Maybe this would work:
> 
> ```js
> const http = require('http')
> const server = http.createServer((req, resp) => {
> 	const baseURL = (req.socket.encrypted ? 'https://' : 'http://') + req.headers.host + '/'
> 	console.log('baseURL: ', baseURL)
> 	const parsedURL = new URL(baseURL + req.url)
> 	console.log('parsedURL: ', parsedURL)
> 	resp.end('Hello world\n')
> })
> server.listen(80, () => console.log('Working...'))
> ```

Ya, I fogot about this type of url, thanks.
