### ISSUE TITLE
Node 0.10.48 for arm

### ISSUE THREAD

**Issue by nicoali** [nodejs/help#337]
is it possible to compile v0.10.48 for raspberrypi?

**Comment by bnoordhuis** [comment]
Probably not unless you're comfortable with patching the source.  Quite a bit of effort went into v4.x to make it work out of the box on ARM.

**Comment by nicoali** [comment]
the problem is that i need to install
https://github.com/CartoDB/Windshaft-cartodb

that needs nodejs v  0.10 :(
https://github.com/CartoDB/Windshaft-cartodb/blob/master/INSTALL.md

**Comment by TheAlphaNerd** [comment]
@nicoali it only says > 0.8 afaict

**Comment by nicoali** [comment]
I've this issue tryng to install Windshaft-cartodb on Ubuntu 16.04 on a Raspberrypi
using node v0.10.48 and npm v2.15.1

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/home/carto/.nvm/v0.10.48/bin/node" "/home/carto/.nvm/v0.10.48/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! mapnik@1.4.15-cdb10 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@1.4.15-cdb10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR! npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/carto/Windshaft-cartodb/npm-debug.log
carto@carto-desktop:~/Windshaft-cartodb$ sudo pico /home/carto/Windshaft-cartodb/npm-debug.log

This is the log
http://www.gisna.altervista.org/npm-debug.log

**Comment by nicoali** [comment]
yes it's an old readme.
Now they need node v0.10.48 and some dependencies v0.12.0 :(

2016-10-24 23:00 GMT+02:00 Myles Borins <notifications@github.com>:

**Comment by nicoali** [comment]
the problem is that i need to install
https://github.com/CartoDB/Windshaft-cartodb/blob/master/INSTALL.md

that needs nodejs v  0.10 :(

2016-10-24 20:49 GMT+02:00 Ben Noordhuis <notifications@github.com>:

**Comment by gibfahn** [comment]
@nicoali It looks like that module needs `npm >=1.2.1 <2.0.0`, which means npm 1. Node v0.10 has been on npm 2 for a while, so you'd need to get an old version of v0.10.

Bear in mind that node v0.10 goes out of support at the end of this week.

**Comment by nicoali** [comment]
now i've "node":"0.10.48","npm":"2.15.1"

but still fail npm install mapnik :(

2016-10-25 21:08 GMT+02:00 Gibson Fahnestock <notifications@github.com>:

**Comment by gibfahn** [comment]
Right, so you have npm 2 but you need npm 1. The last version of Node 0.10 to have npm 1 was 0.10.43.

If that fails there's not much you can do (except ask the package maintainers to upgrade to a supported version of node and npm.

**Comment by lordKnighton** [comment]
Are you still experiencing issues with this @nicoali, if you've solved this, close issue, if not let us know and we will continue to support you.
