### ISSUE TITLE
How do I uninstall node.js 

### ISSUE THREAD

**Issue by zzamchick** [nodejs/help#3373]
* 14.17.0 LTS:
* MacOS Catalina 10.15.7:
* Uninstall:

I am about to begin learning Javascript and downloaded node.js from the nodejs.org homepage about a week ago. I've noticed a significant impact on my computer's battery life, so I'd like to uninstall it and use a different computer for my lessons instead. How do I do this?

**Comment by PoojaDurgad** [comment]
@zzamchick - I don't use Macos version of OS but I guess https://reactgo.com/uninstall-node-npm-from-macos/ this may help

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
