### ISSUE TITLE
fds

### ISSUE THREAD

**Issue by eggratanurag** [nodejs/help#3374]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by marsonya** [comment]
Hi, can you share a screenshot of the data use list showing Node.js?

**Comment by eggratanurag** [comment]
See this Is taking up a lot of data and it happens on regular purpose. As I only use mobile data its so hard for me Sent from Mail for Windows 10 From: akhil marsonyaSent: Tuesday, May 18, 2021 1:12 PMTo: nodejs/helpCc: eggratanurag; AuthorSubject: Re: [nodejs/help] i dont know what is node. its not even installed in my pc its still taking up my lot of data it takes up to 1gb per day data and im unable to get rid of it cannot uninstall somehow it doesn't exist in my pc. pls help (#3374) Hi, can you share a screenshot of the data use list showing Node.js?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
