### ISSUE TITLE
expo init not working anyone can help me?

### ISSUE THREAD

**Issue by abhiishekk02** [nodejs/help#3375]
C:\Users\*****>expo
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\VINNU nani\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []

**Comment by Ayase-252** [comment]
It seems not a Node.js issue. Unfortunately, I'm not familar with the tool. You could look FAQ or ask question per [FAQ](https://github.com/expo/expo#-faq) section in their repo.

**Comment by osheenjain20** [comment]
Upgrade your node version and if you are working using a VPN for a corporate then turn it ON while performing the task.
