### ISSUE TITLE
Can't install any modules.

### ISSUE THREAD

**Issue by DanielBenkisos** [nodejs/help#3376]
16.1
Windows 10 64 bit
installing modules
all modules

Hi, im working on a project for school with a group. Suddenly my webstorm cant install any npm modules. I have reinstalled node, and webstorm and even factory reset my pc. I tried in vs code and it couldnt install either. My group members have no issues and run the same version of node and webstorm as me. I have a long debug log, i hope someone can help...
[2021-05-18T15_05_10_074Z-debug.log](https://github.com/nodejs/help/files/6502348/2021-05-18T15_05_10_074Z-debug.log)

**Comment by Ayase-252** [comment]
```
479 error gyp ERR! find VS **************************************************************
479 error gyp ERR! find VS You need to install the latest version of Visual Studio
479 error gyp ERR! find VS including the "Desktop development with C++" workload.
479 error gyp ERR! find VS For more information consult the documentation at:
479 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
479 error gyp ERR! find VS **************************************************************
```

It seems you didn't set Visual Studio correctly, see https://github.com/nodejs/node-gyp#on-windows.

**Comment by Ayase-252** [comment]
```
479 error gyp ERR! find VS **************************************************************
479 error gyp ERR! find VS You need to install the latest version of Visual Studio
479 error gyp ERR! find VS including the "Desktop development with C++" workload.
479 error gyp ERR! find VS For more information consult the documentation at:
479 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
479 error gyp ERR! find VS **************************************************************
```

It seems you didn't set Visual Studio correctly, see https://github.com/nodejs/node-gyp#on-windows.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
