### ISSUE TITLE
Node js Cross-domain session ids 

### ISSUE THREAD

**Issue by ajithv11** [nodejs/help#338]
Hi,

Here I will describe the requirement for my project.

Basically I want to build a chat application which I can embed to different websites for example , site build using wordpress, magento, drupal, custom frameworks ... etc . What I actually need is to embed JavaScript for handling socket chat using (socket.io) on some of the website(wordpress, magento, drupal ....), so what I finally have is a set of javascript code (client side), and a server running in nodejs (with socket.io)

The problem I faced is to manage session for registered users after login. Since my code is embedded on different websites and the node server resides on other server , On each page refresh I faced difficult to validate user session session. Could you please help me how I can manage session in a best way for this application.

If you feel difficulty to understand my need , I can explain in detail with examples

Thanking You
Ajith V

**Comment by ajithv11** [comment]
Any Help for this ?

**Comment by lordKnighton** [comment]
personally, this sounds abstract & difficult to understand, could you simplify with details.

**Comment by lordKnighton** [comment]
Closing for now. Because lack of response, feel free to reopen.
