### ISSUE TITLE
Getting RSA_padding_check_PKCS1_type_2:pkcs decoding error

### ISSUE THREAD

**Issue by ridoy19** [nodejs/help#3381]
The encryption is working fine. But when I am trying to decrypt the encrypted message I am getting the following error. Can someone assist me with this?

`internal/crypto/cipher.js:63
    return method(data, format, type, passphrase, buffer, padding, oaepHash,
           ^

Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error
    at Object.privateDecrypt (internal/crypto/cipher.js:63:12)
    at decryptDataWithPrivateKey (C:\pgNagadAPI\server.js:94:32)
    at Object.<anonymous> (C:\pgNagadAPI\server.js:105:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  opensslErrorStack: [
    'error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed'
  ],
  library: 'rsa routines',
  function: 'RSA_padding_check_PKCS1_type_2',
  reason: 'pkcs decoding error',
  code: 'ERR_OSSL_RSA_PKCS_DECODING_ERROR'
}`

**Comment by ridoy19** [comment]
> Could you provide a minimal repo code to demonstrate the issue?

`const encryptionKey = new NodeRSA({
  b: 2048,
  publicKey
});
encryptionKey.setOptions({
  encryptionScheme: {
    scheme: 'pkcs1',
    padding: crypto.constants.RSA_PKCS1_PADDING
  }
});

const decryptionKey = new NodeRSA({
  b: 512,
  privateKey
});
decryptionKey.setOptions({
  encryptionScheme: {
    scheme: 'pkcs1',
    padding: crypto.constants.RSA_PKCS1_PADDING
  }
});


const encryptSensitiveData = encryptionKey.encrypt(JSON.stringify(sensitiveData), 'base64');
console.log(encryptSensitiveData);


const decryptSensitiveData = decryptionKey.decrypt(encryptSensitiveData, 'utf8');
console.log(decryptSensitiveData);`

Please have the sample code from my side.

**Comment by ksuh90** [comment]
> > Could you provide a minimal repo code to demonstrate the issue?
> 
> `const encryptionKey = new NodeRSA({ b: 2048, publicKey }); encryptionKey.setOptions({ encryptionScheme: { scheme: 'pkcs1', padding: crypto.constants.RSA_PKCS1_PADDING } });
> 
> const decryptionKey = new NodeRSA({ b: 512, privateKey }); decryptionKey.setOptions({ encryptionScheme: { scheme: 'pkcs1', padding: crypto.constants.RSA_PKCS1_PADDING } });
> 
> const encryptSensitiveData = encryptionKey.encrypt(JSON.stringify(sensitiveData), 'base64'); console.log(encryptSensitiveData);
> 
> const decryptSensitiveData = decryptionKey.decrypt(encryptSensitiveData, 'utf8'); console.log(decryptSensitiveData);`
> 
> Please have the sample code from my side.

have you resolved this issue? I am facing the same issue.
