### ISSUE TITLE
when i am trying to install node.js in my computer it gives an error like"windows installer service could not be accessed" how can i resolve this issue?

### ISSUE THREAD

**Issue by muhammadsamishoukat** [nodejs/help#3385]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by shashank-001** [comment]
you can download the .msi file manually and then install it. it may help [NodeJS Windows Installer](https://nodejs.org/dist/v14.17.0/node-v14.17.0-x86.msi)
If you still found any error share screenshot of the error. it will be helpful.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
