### ISSUE TITLE
Installer failed to update to latest version

### ISSUE THREAD

**Issue by parker564** [nodejs/help#3386]
* **Node.js Version**: v14.17.0
* **OS**: Mac
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**: Catalina 10.15.7

Failed to upgrade to v14.17.0 using installer fro nodejs.org

**Comment by seezy92** [comment]
Same problem here, nobody helped me. Did you find any solution?

**Comment by gireeshpunathil** [comment]
@parker564 - are there steps to reproduce the issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
