### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by saisumanthss** [nodejs/help#3387]
* **Node.js Version**:16.2.0
* **OS**: Windows 10

When trying to start the local development server using npm start, I'm getting an error stating that missing script: "start". I've checked package.json file for the missing script and the scripts are intact in the debug portion of package.json code. I tried installing the previous builds of node js but it doesn't work even then. I'm new to node js, can anyone let me know how to rectify this error?

**Comment by benhalverson** [comment]
👋🏻 if you see this error it is because you are missing the start property in your package.json
Here's an example. https://nodejs.dev/learn/an-introduction-to-the-npm-package-manager#running-tasks

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
