### ISSUE TITLE
htttp  request.headers  has no accept-encoding

### ISSUE THREAD

**Issue by itotoo** [nodejs/help#3389]
* **Version**:
node v10 +
* **Platform**:
* **Subsystem**:

### What steps will reproduce the bug?

http.createServer(function main(req, res) {
            console.log("... req", req.headers, req.headers["accept-encoding"]);
            // req.headers["accept-encoding"] === undefined
            router_router(req, res);
        })
        .listen("80");

### What is the expected behavior?
I hope so

### What do you see instead?
Is accept-encoding filtered out? Still don't support it

http.createServer(function main(req, res) {
            console.log("... req", req.headers, req.headers["accept-encoding"]);
            // req.headers["accept-encoding"] === undefined
            router_router(req, res);
        })
        .listen("80");

**Comment by gireeshpunathil** [comment]
ping @itotoo for the above clarification

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
