### ISSUE TITLE
upgrade issue from node v 4.2.6 to LTS 

### ISSUE THREAD

**Issue by pandeysoni** [nodejs/help#339]
I run these command:

sudo npm cache clean --force
sudo npm install -g n
sudo n 6.0.0

After that i see on cli:
install : node-v6.0.0
mkdir : /usr/local/n/versions/node/6.0.0
fetch : https://nodejs.org/dist/v6.0.0/node-v6.0.0-linux-x64.tar.gz
######################################################################## 100.0%
installed : v6.0.0

but when i run node -v, still i found previous version of node.

**Comment by TheAlphaNerd** [comment]
@pandeysoni it sounds to me like you don't have your environment properly configured for n.

what is the output of `echo $PATH`, do you have `/usr/local/bin` in there?

Also I noticed you are installing v6.0.0, that is a fairly old version, you might want to try and install node v6.9.1

**Comment by gibfahn** [comment]
You could also try `which node`, and see where it points to

**Comment by pandeysoni** [comment]
@TheAlphaNerd  and @gibfahn I tried both version (latest one), here i mentioned that one and my path is  /usr/local/bin/node

**Comment by pandeysoni** [comment]
I just restarted, so i got updated version, so this is not the issue from installing side.

**Comment by dotnetspec** [comment]
I have same problem, but restart didn't resolve

![node version](https://cloud.githubusercontent.com/assets/27340988/25511685/e540b9d4-2bfa-11e7-9264-734c7e3699ca.png)

make
make install
were run without error in the downloaded node-v6 folder

**Comment by gibfahn** [comment]
>can you re-open this issue?

I see you've already opened #607, so we can just use that.
