### ISSUE TITLE
Issue with Buffer.from base64url

### ISSUE THREAD

**Issue by abdollahkahne** [nodejs/help#3391]
* **v14.16.1**:
* **Ubuntu 20.04**:
* **code**:
* **Buffer**:
* 
I am trying to verify a signedRequest from Facebook. just for reminding I have this signedRequest
`KYx10JUlII51Fe19CZ4anFAVlm8n8FwloiIks_Lunmk.eyJ1c2VyX2lkIjoiMTAxNjIwMTg1ND....`

Here at the end of code I shall get similar `decodedSig.toString()`,  `hashed` variables

After multiple hours of trying, I found out that the error is with base64url encoding in Buffer module.
The following code only has one line of difference but one works fine and another errors!
```
getFacebookUserNativeLib: (req, res, next) => {
    const signedRequest = req.body.signedRequest;
    const fbSecret = process.env.FACEBOOK_APP_SECRET;
    const [encodedSig, encodedPayload] = signedRequest.split(".");
    var decodedSig = base64UrlDecode(encodedSig); // The line with error
    const hashed = signHmacSha256(fbSecret, encodedPayload);
    console.log(hashed.toString(), encodedSig.toString(),decodedSig.toString());
    res.send(hashed);
  },
```
Here error is with **Base64UrlDecode** function. I use a native modules as below:
```
function base64UrlDecodeUsingBuffer(input) {
  return Buffer.from(
    input.replace("-", "+").replace("_", "/"),
    "base64",
  ).toString("ascii");
}
```
This give **errors** with `base64url` and I try to replace it with `base64` encoding and that returns something none-sense.

But when I use `CryptoJS` npm modules for this purpose it works like a charm!
```
function base64UrlDecode(input) {
  return CryptoJS.enc.Base64.parse(
    /******** Decode */
    input.replace("-", "+").replace("_", "/"), // Replace characters
  );
}
```
It may be a bug with nodejs base64url and base64 encoding but it may be because of my lack of knowledge and lack of work with `Buffers`. Please give me the native nodejs solution using **Buffer** it exist.
Thanks for your attention and your response

**Comment by addaleax** [comment]
@abdollahkahne A runnable example and the actual errors would be very helpful.

Also, generally speaking, you want `.replace(/-/g, "+").replace(/_/g, "/")` (or for really new Node.js versions, `.replaceAll("-", "+").replaceAll("_", "/")`) instead of `.replace("-", "+").replace("_", "/")`, because `.replace()` with strings replaces only the first instance of that string.

**Comment by abdollahkahne** [comment]
@addaleax . Thanks for your reply. 
[buffer.zip](https://github.com/nodejs/help/files/6571509/buffer.zip)

Please just simply run this attached javascript file with node. You see the error. You can then replace the `base64UrlDecodeUsingBuffer` with the `base64UrlDecodeUsingBufferByBase64`. The error gone but the signedToken does not verify (`hashed` is not equal to `encodedSig`  ). Only after installing CryptoJS and using the `base64UrlDecode` function I get what I wanted (`hashed=encodedSig`)

```

const crypto = require("crypto");
// var CryptoJS = require("crypto-js");

// function base64UrlDecode(input) {
//   return CryptoJS.enc.Base64.parse(
//     /******** Decode */
//     input.replace("-", "+").replace("_", "/"), // Replace characters
//   );
// }


function base64UrlDecodeUsingBuffer(input) {
  return Buffer.from(
    input,
    "base64url",
  ).toString("ascii");
}

function base64UrlDecodeUsingBufferByBase64(input) {
  return Buffer.from(
    input.replace(/-/g, "+").replace(/_/g, "/"),
    "base64",
  ).toString("ascii");
}

function signHmacSha256(key, str) {
  let hmac = crypto.createHmac("sha256", key).update(str);
  let signed = hmac.digest("hex");
  return signed;
}

const signedRequest1="KYx10JUlII51Fe19CZ4anFAVlm8n8FwloiIks_Lunmk.eyJ1c2VyX2lkIjoiMTAxNjIwMTg1NDc4MDc1IiwiY29kZSI6IkFRQk52akQxNXlPZk5NMHNXSGFFWnJiWmZMUUN2NWZYUmxmNDdVanJGbVR2UUo2a1BBdy1nT3ZiNUhwUE1LMU5sRVYzdUM5U1kyN0pvdkNISjl6Qk5WOE9NbzlzVnd5a0k2YjZ1VUpqeE9sUk9fR0R2LXRZRWctTWR3U09HQlZvbzNVV0hkVVhBeXBiWk41QVVIMUk0a3llQ3puYlNPXzZfUkoxRi0xUF9tRWtJVEtJMERvanZQVEdfcFNrdGhiMlBRcW1LNDRGbGxiS0FscG5HVXJCbU5jeTFGTk00QzJvd0g3RlBmUF9LOWl5RHZQRjFRdlVCNXE2ZV91VHZ5dkpxNm9peW9XUEFrRmN2QTdiVUNyN1lpMU5LcjF6cGNKYUN2c3dYWHB6Yk5XVnNtd2FZZ25kc1h2Y05yTTdlMmdJV3kxMXNhSWFXVWpfaklkT3Buak9UMVJBIiwib2F1dGhfdG9rZW4iOiJFQUF6SDZUZ2ppbG9CQU5qYmRDenc4M1pCckltN3FLYjJDb29VTDNmOWxWd1FBWkJPNGxTZmh6ck9hYWpLTXBvZDVQbmE2TTY2VHhnMFpDaDZRYXFRSGxmMlB1NzJSTlBlWXpoZTIwellRQVpBeW5MYVd5ejJ3YndxYlpBc2hzM3ZaQXRmcE1EREVzQ2JTbFhRUU85cmJYYjRiMjh2QTFtRlFGNzRManRUTFpDOUM2N0ZweFpBd0xJZnZ5S3NValpDeGZ4OFpEIiwiYWxnb3JpdGhtIjoiSE1BQy1TSEEyNTYiLCJpc3N1ZWRfYXQiOjE2MjI0Njc0NzZ9"

const getFacebookUserNativeLib= (signedRequest) => {
    const fbSecret = "f239979e2eeea36dfa31ba091603bb2f";
    const [encodedSig, encodedPayload] = signedRequest.split(".");
    var decodedSig = base64UrlDecodeUsingBuffer(encodedSig); // The line with error
    const hashed = signHmacSha256(fbSecret, encodedPayload);
    console.log(hashed, encodedSig, decodedSig.toString());
  };

  getFacebookUserNativeLib(signedRequest1);
```

**Comment by abdollahkahne** [comment]
As a matter of fact, I replace my Faceook-Secret in Facebook. So nobody worry about sharing it here.

**Comment by addaleax** [comment]
Right – sorry I didn’t notice this before, but why are you using `.toString("ascii")`? Did you mean `.toString('hex')`? That gives me the same results as crypto-js then.

**Comment by abdollahkahne** [comment]
I get this error with base64url (which possibly a bug with Node.JS Buffer):
![image](https://user-images.githubusercontent.com/48277995/120226539-a40c9580-c25c-11eb-941b-246654011944.png)
but with `hex` and `base64` encoding.errors gone and it runs OKay. Thank you very much
![image](https://user-images.githubusercontent.com/48277995/120226959-855ace80-c25d-11eb-8530-6865d4519e53.png). It was a magic for me. Thank you again
