### ISSUE TITLE
"Access denied" when running a command (Win10)

### ISSUE THREAD

**Issue by saugstauberr** [nodejs/help#3392]
* **Node.js Version**: 14.17.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Execution
* **Module (and version) (if relevant)**:

Hello,
I have an issue while running Node.js. After I've installed it without any problems and then tried to run it, I'll **always** get an "Access denied" error. Also running "npm i" throws me the same error.
I tried to reinstall Node in many different folders, disabled the UAC dialog, gave Admin permissions everywhere but nothing worked. Also I didn't find any solution for my problem.

Please let me know if you have an idea or solution for my problem.

With best regards,
Martin
![grafik](https://user-images.githubusercontent.com/57033944/120404543-e27e7f00-c346-11eb-9d39-680bebd79c6a.png)

**Comment by shashank-001** [comment]
you should look into the system environment variable and check there should be the present Nodejs file path.
e.g: in my case
```
C:\Program Files\nodejs
```

**Comment by bl-ue** [comment]
This is a bit odd because it's just printing a message, no stack trace or even additional error code or anything like that 🤔

**Comment by shashank-001** [comment]
As @ItsMartin030 mentioned his error 
```
 I've installed it without any problems and then tried to run it, I'll always get an "Access denied" error.
 Also running "npm i" throws me the same error.
```
I think the .exe file path is not accessible so it shows the error "Access denied" while he using npm or node commands.

**Comment by ItsMartin030** [comment]
> 
> 
> As @ItsMartin030 mentioned his error
> 
> ```
>  I've installed it without any problems and then tried to run it, I'll always get an "Access denied" error.
>  Also running "npm i" throws me the same error.
> ```
> 
> I think the .exe file path is not accessible so it shows the error "Access denied" while he using npm or node commands.

Yes, but it's only not accessible when MacType is running. After I stop the MacType Service/Process, everything works fine. I can run every NPM command or whatever I want.

**Comment by shashank-001** [comment]
> 
> 
> I found the solution, it was because a process accessed it. After I stopped it, everything worked fine.
> 
> Gonna create another issue on their GitHub, thank you for your help anyways. :)

that's good.

**Comment by bl-ue** [comment]
What process was it, @ItsMartin030?

**Comment by bl-ue** [comment]
Linking for reference: https://github.com/snowie2000/mactype/issues/758

**Comment by ItsMartin030** [comment]
> 
> 
> What process was it, @ItsMartin030?

It was MacType.
