### ISSUE TITLE
Hola, como puedo instalar node js para windows 7 con procesador de 2.5 Ghz y RAM de 2GB

### ISSUE THREAD

**Issue by Brian-Henao** [nodejs/help#3393]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by bl-ue** [comment]
Hi @Brian-Henao! Are you having trouble installing Node.js from https://nodejs.org/en/download/?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
