### ISSUE TITLE
A problem with Destruction in Node. 

### ISSUE THREAD

**Issue by abdollahkahne** [nodejs/help#3394]
* **Node.js V14**:
* **Ubuntu 20.04**:
* **code**:

I see something inconsistent in **Destructing Object** which makes errors for me sometimes. I wanted to just ask that see this is the case or I have been wrong about it. 
When I destruct a **nested Object** in backend with express js in node js I have both of `user` object and their `fullname` string in the following case:
```
const {
      user: { url, fullname },
    } = req.body;
```
But when I use it in React in front-end using node.js I got the error that `user` is not defined here.
```
const {
      user: { url, fullname },
    } = this.props;
```
I have to add the following code to have both of them. 
```
const { user } = this.props;
    const {  url, fullname } = user;
```

What do you suggest?
Sorry If it is not related to node.js very much but I don't know other reference for my JS Errors (I am not very easy with stack-overflow or stack-exchange and even I don't understand when we should use which of these. I appreciate answers to that questions too).
Thanks in advance.

**Comment by Ayase-252** [comment]
Are you sure that `this.props.user` is not `undefined`?

**Comment by abdollahkahne** [comment]
@Ayase-252 . Thanks for your answer. No that is not the case. My question is that when destructing I loose the upper level of nested object. If it was undefined then I should not have the fullname and url either. but I have them and I use them. I think it is a mechanism with destruction!

**Comment by Ayase-252** [comment]
@abdollahkahne 

I'm not sure I really get your question. Sorry.

For descructing a nest object

```js
const {
     user: { url, fullname },
 } = this.props;

// is equivalent to

const { url, fullname } = this.prop.user
```

**Comment by Ayase-252** [comment]
@abdollahkahne 

Aha... If you means why `user` is not defined, I'd say it is how Object destruction works. The outer property will not be considered as a `const`.
