### ISSUE TITLE
Update Wiki content

### ISSUE THREAD

**Issue by Noahigh** [nodejs/help#3395]
* **Node.js Version**: v14.17.0
* **OS**: CentOS Linux release 8.3.2011
* **Scope (install, code, runtime, meta, other?)**: Wiki
* **Module (and version) (if relevant)**:

Wiki Link: https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux

> Installation - How to install Node.js via binary archive on Linux? - 4. Test installation using
the normal output is:
```shell
➜  node -v
v10.15.1
➜  npm version
{ npm: '6.4.1',
 ares: '1.15.0',
 cldr: '33.1',
 http_parser: '2.8.0',
 icu: '62.1',
 modules: '64',
 napi: '3',
 nghttp2: '1.34.0',
 node: '10.15.1',
 openssl: '1.1.0j',
 tz: '2018e',
 unicode: '11.0',
 uv: '1.23.2',
 v8: '6.8.275.32-node.12',
 zlib: '1.2.11' }
```

**Update the above content to the following ↓↓↓↓↓↓**

```shell
➜  node -v
v10.15.1
➜  npm version
{ npm: '6.4.1',
 ares: '1.15.0',
 cldr: '33.1',
 http_parser: '2.8.0',
 icu: '62.1',
 modules: '64',
 napi: '3',
 nghttp2: '1.34.0',
 node: '10.15.1',
 openssl: '1.1.0j',
 tz: '2018e',
 unicode: '11.0',
 uv: '1.23.2',
 v8: '6.8.275.32-node.12',
 zlib: '1.2.11' }
➜  npx -v
6.4.1
```

**Comment by bl-ue** [comment]
Ah yes, this should be done.  @sam-github could you please add
```
➜  npx -v
6.4.1
```
to [this wiki page on nodejs/help](https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux) (which you last modified)?
Before it there is
- `$ node -v`
- `$ npm version`
- `$ npx -v`
And whoever wrote the content that @Noahigh references forgot to add `npx` to it.

**Comment by gireeshpunathil** [comment]
@Noahigh @bl-ue - I modified it. can you pls check? also, any other relevant changes?

**Comment by Noahigh** [comment]
> @Noahigh @bl-ue - I modified it. can you pls check? also, any other relevant changes?

oh, no...    It seems like that you modified it wrong... :joy:

And I find that there are some else error places in [this wiki page on nodejs/help](https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux)...

**Comment by gireeshpunathil** [comment]
@Noahigh - can you explain what is wrong, and what needs fixing?

also, does it help if I change all the versions with a latest Node.js?

**Comment by Noahigh** [comment]
Wiki Link: https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux

>**Installation - How to install Node.js via binary archive on Linux?**
>...snip...
>**4. Test installation using**
>...snip...
>the normal output is:

```markdown
➜  node -v
v10.15.1
➜  npm version
{ npm: '6.4.1',
 ares: '1.15.0',
 cldr: '33.1',
 http_parser: '2.8.0',
 icu: '62.1',
 modules: '64',
 napi: '3',
 nghttp2: '1.34.0',
 node: '10.15.1',
 openssl: '1.1.0j',
 tz: '2018e',
 unicode: '11.0',
 uv: '1.23.2',
 v8: '6.8.275.32-node.12',
 zlib: '1.2.11' }
```

**Update the above content to the following ↓↓↓↓↓↓**

```markdown
➜  node -v
v10.15.1
➜  npm version
{ npm: '6.4.1',
 ares: '1.15.0',
 cldr: '33.1',
 http_parser: '2.8.0',
 icu: '62.1',
 modules: '64',
 napi: '3',
 nghttp2: '1.34.0',
 node: '10.15.1',
 openssl: '1.1.0j',
 tz: '2018e',
 unicode: '11.0',
 uv: '1.23.2',
 v8: '6.8.275.32-node.12',
 zlib: '1.2.11' }
➜  npx -v
6.4.1
```
Please focus on the ***last two lines***.

**Comment by gireeshpunathil** [comment]
@Noahigh - how about now?

**Comment by Noahigh** [comment]
> @Noahigh - how about now?

Niceeeee! It's right. :clap:

By the way, `npx -v` in [this part(how-to-install-nodejs-via-binary-archive-on-aix)](https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-aix)  should be **`6.11.3`**.

**Comment by gireeshpunathil** [comment]
fixed, thanks!

**Comment by gireeshpunathil** [comment]
closing as addressed, cheers!
