### ISSUE TITLE
How to customise Console class output?

### ISSUE THREAD

**Issue by ishuen** [nodejs/help#3396]
* **Node.js Version**: v14.16.1
* **OS**: macOS v10.15.7
* **Scope (install, code, runtime, meta, other?)**: N/A
* **Module (and version) (if relevant)**: N/A

Hi. I'm trying to make a customised Console class instance. I would like to change its colouring. I'm able to find some options from [util.inspect](https://nodejs.org/api/util.html#util_custom_inspection_functions_on_objects) and apply them to Console class. However, I have no idea how to apply the styles mentioned [here](https://nodejs.org/api/util.html#util_customizing_util_inspect_colors) to it. Is there any sample code available somewhere (e.g. how to apply the modifier or bg color)?

```js
const { Console } = require('console');
const logger = new Console({
    stdout: process.stdout,
    stderr: process.stderr,
    inspectOptions: {
        sorted: true,
        colors: true // The output is styled with ANSI color codes. But how to let it apply the customised styling rules?
    }
});
logger.log('sample log output');
```

**Comment by RaisinTen** [comment]
You can try modifying the properties on `util.inspect.styles` and `util.inspect.colors`:
```js
const { Console } = require('console');
const logger = new Console({
    stdout: process.stdout,
    stderr: process.stderr,
    inspectOptions: {
        sorted: true,
        colors: true // The output is styled with ANSI color codes. But how to let it apply the customised styling rules?
    }
});

const util = require('util');
util.inspect.styles.number = 'red';
logger.log({
    z: 1,
    y: 2,
    x: 3,
});
```
Now the numbers are red:
![](https://user-images.githubusercontent.com/42526976/120499074-62efbf00-c3dd-11eb-8594-0dd47d4691ad.png)

**Comment by ishuen** [comment]
Thanks for your response. I guess it's a kind of global setting? That is, if I have 2 different loggers, both of them will be affected, right?

**Comment by RaisinTen** [comment]
Yes, that is correct.

**Comment by ishuen** [comment]
Alright, thanks. Seems like there is no class specific setting for this.
