### ISSUE TITLE
TypeError: Cannot read property 'write' of null at Zlib.callback (zlib.js:499:33) for Nodejs 14.5

### ISSUE THREAD

**Issue by naren0021** [nodejs/help#3397]
I have recently experienced the issue on node 14.x on the production
```

uncaughtException: Cannot read property 'write' of null
TypeError: Cannot read property 'write' of null
    at Zlib.callback (zlib.js:499:33)
```

**Comment by aduh95** [comment]
Hi @naren0021, from what I can see of the error stack you copied (BTW, it's usually better to copy the whole output if you want someone to help you to have the correct info), it seems you have a module called `zlib.js` which has a bug on line 499: it tries to read a property of an object which is in fact `null`. It should look something like that:

```js
   myObject.write('data');
```

It either means that you need to add a check before trying to call the method:

```js
  if (myObject != null) myObject.write('data');
```

Or that there's somewhere else in your app, in which case there's not much I can do to help you...

I see in the issue title that you are using Node.js 14.5, kindly consider [upgrading to the latest version](https://nodejs.org/en/download/), lots of bugs are fixed simply by keeping up-to-date with the tools you're using.

**Comment by naren0021** [comment]
correct error is this @Ayase-252 

```
     at Zlib.callback (zlib.js:499:33)
    TypeError: Cannot read property 'write' of null
    at Zlib.callback (zlib.js:499:33)
   TypeError: Cannot read property 'write' of null
    at Zlib.callback (zlib.js:499:33)
   TypeError: Cannot read property 'write' of null
   at Zlib.callback (zlib.js:499:33)
   TypeError: Cannot read property 'write' of null
   at Zlib.callback (zlib.js:499:33)
   TypeError: Cannot read property 'write' of null
   at Zlib.callback (zlib.js:499:33)
   TypeError: Cannot read property 'write' of null
   at Zlib.callback (zlib.js:499:33)
   TypeError: Cannot read property 'write' of null
   at Zlib.callback (zlib.js:499:33)

```

yes sure I will update the Node version and will update you @aduh95

**Comment by bl-ue** [comment]
@aduh95 this looks like a case of https://github.com/nodejs/node/issues/36421 :(

**Comment by KRAUS1203** [comment]
This issue is not as simple as since Zlib is a submodule of core node js and is used internally when web sockets are used. so if we write something on websocket i.e. socket.emit we dont have access to zlib. so cannot do the check mentioned by @aduh95 .
also this is when socket connection is closed by client side while server is writing something.

**Comment by aduh95** [comment]
@KRAUS1203 I didn't realize `zlib.js` was referring to a core module, thanks for pointing it out – stack traces in Node.js v15+ would refer to it as `node:zlib` to remove the ambiguity, I forgot v14.x still has the old style ones.

Line 499 of `zlib.js` is an empty line in v14.5.0: https://github.com/nodejs/node/blob/v14.5.0/lib/zlib.js#L499
@naren0021 are you using a modified version of Node.js?

**Comment by bl-ue** [comment]
>@naren0021 are you using a modified version of Node.js?

I wouldn't think so — you can see in https://github.com/nodejs/node/issues/36421 that three different people have the same line (`499`).

**Comment by bl-ue** [comment]
That looks like node 8 actually https://github.com/nodejs/node/blob/v8.x/lib/zlib.js#L499 ❓

**Comment by bl-ue** [comment]
@naren0021 you said:

>on node 14.x on the production

but this appears to be like @KRAUS1203's problem, and in https://github.com/nodejs/node/issues/36421 they said that they were using 8.9.4 🤔
