### ISSUE TITLE
The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operab le program.

### ISSUE THREAD

**Issue by nevuss** [nodejs/help#3399]
I have this error when try to install Expo on Windows 10. Help me please.

PS C:\Users\сер гей> npm i -g expo-cli
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operab
le program. Check the spelling of the name, or if a path was included, verify that the path is c
orrect and try again.
At line:1 char:1
+ npm i -g expo-cli
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bl-ue** [comment]
Hi @nevuss! First, let me verify: did you install Node.js for Windows from https://nodejs.org/en/download/?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.

**Comment by visssmay05** [comment]
> Hi @nevuss! First, let me verify: did you install Node.js for Windows from https://nodejs.org/en/download/?

hey man, ive got the same prblem i hv installed node js. is there asolution to this? dc z3us#0139

**Comment by cafeTechne** [comment]
This is a live issue. Here's the terminal output on latest version of VS code on windows 10 64, amd:

PS C:\Program Files> npm -v
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At line:1 char:1
+ npm -v
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by SahilGulghane** [comment]
hit  command  in terminal  npm --version  if it is showing then reload it will work
