### ISSUE TITLE
HI I can't Install any package  by Npm Install  in My window 10 system

### ISSUE THREAD

**Issue by karangoswami31** [nodejs/help#340]
D:>npm install -g polymer-cli
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "polymer-cli"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
**npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate**
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm-debug.log

**Comment by karangoswami31** [comment]
HI I got he Solution ...
I just need to Run this command its will work
now i can install any package by Npm install 
>npm config set strict-ssl false

**Comment by lordKnighton** [comment]
Nice, it looks like you solved your issue, before we could help you with it. 
--
Close the issue if your finish, but if you wish to continue, we will be there. 

💯  happy coding

**Comment by karangoswami31** [comment]
NO still I am facing Issue 

I can install polymer but not completely  , so I can't lode polymer
@lordKnighton .lordKnighton please give me a solution for "UNABLE_TO_VERIFY_LEAF_SIGNATURE"

**Comment by bnoordhuis** [comment]
No action for a few months so I'm going to close this out.  FWIW, my first guess would be that you are using an alternative npm registry that serves a wonky TLS certificate.
