### ISSUE TITLE
Cant resolve ?

### ISSUE THREAD

**Issue by StarkPro1** [nodejs/help#3403]
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'colors'
Require stack: 
- C:\Users\rivan\Downloads\Bot de divulgaçao\index2.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:774:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1013:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:93:18)←[39m
    at Object.<anonymous> (C:\Users\rivan\Downloads\Bot de divulgaçao\index2.js:4:16)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1109:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:989:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:829:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\rivan\\Downloads\\Bot de divulgaçao\\index2.js'←[39m ]
}

**Comment by bl-ue** [comment]
Hi @StarkPro1 — looks like you need the [`colors`](https://www.npmjs.com/package/colors) module installed.  Try this:
1. Open a command prompt (hit Win + R → type `cmd.exe` → hit Enter)
2. run `C:`
3. run `cd "C:\Users\rivan\Downloads\Bot de divulgaçao"`
4. run `npm install`
5. run `npm install colors`

Let me know if that works.

**Comment by gireeshpunathil** [comment]
@StarkPro1 - does the solution proposed work for you?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.

**Comment by YujithIsura** [comment]
/Users/yujith/Desktop/TodoApp/server/models/index.js:26
    db[model.name] = model;
             ^

TypeError: Cannot read property 'name' of undefined
    at /Users/yujith/Desktop/TodoApp/server/models/index.js:26:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/yujith/Desktop/TodoApp/server/models/index.js:24:4)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/yujith/Desktop/TodoApp/server/index.js:4:12)

Getting this error from the models/index.js file, any idea 
used sequelize
