### ISSUE TITLE
error while install nodejs

### ISSUE THREAD

**Issue by kdsinghak47** [nodejs/help#3404]
### while iam install nodejs .I found an installing error which is "A DLL required for this to install to complete could not be run  " how can i remove this error.

**Comment by bl-ue** [comment]
Hi @kdsinghak47! Could you please try the solution documented [here](https://stackoverflow.com/a/39773248) and tell me if it worked?

**Comment by gireeshpunathil** [comment]
@kdsinghak47 - does the solution proposed by @bl-ue work for you?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
