### ISSUE TITLE
Write stream error.

### ISSUE THREAD

**Issue by Folliant** [nodejs/help#3405]
OS: `Ubuntu 20.04.`
NODE: `14.17.`

In first i have four streams.
- Read.
- Transform stream for calculate hash.
- Duplex stream for change.
- Write stream for save to file.

I get `read stream` through [multer](https://www.npmjs.com/package/multer), when upload file. (I wrote own [engine](https://github.com/expressjs/multer/blob/master/StorageEngine.md))

I create `transform stream` as:
```js
getHashSummingStream(hashName) {
    const hash = crypto.createHash("md5");

    const hashTransformStream= new stream.Transform({
        transform: (chunk, encoding, done) => {
            hash.update(chunk);
            done(null, chunk);
        },
    });

    return {hash, hashTransformStream};
}
```

`Duplex stream` i get from [sharp](https://www.npmjs.com/package/sharp).
And i create it as:
```js
const roundedCornerResizer = sharp().resize(500, 500) //Options only for example.
```

`Write stream` i create as:
```js
const writeStream = fs.createWriteStream(path);
```

And i also subscribe to `"end"` event on `Read stream`, as:
```js
const {hash, hashTransformStream} = class.getHashSummingStream()

fileStream.on("end", async () => {
    //Here i calculate hash, for example.
    const hex = hash.digest("hex");
});
```

In the end i put streams in `pipeline`:
```js
await stream.pipeline(readStream, hashTransformStream, sharpStream, writeStream)
```

In described above all works fine, and i get correct md5 hash of uploaded image.

But if i remove `sharpStream` from `pipeline`, as:
```js
await stream.pipeline(readStream, hashTransformStream, writeStream)
```

I get error:
```
internal/crypto/hash.js:79
    throw new ERR_CRYPTO_HASH_FINALIZED();
Error [ERR_CRYPTO_HASH_FINALIZED]: Digest already called
    at Hash.update (internal/crypto/hash.js:79:11)
    at Transform.transform [as _transform] (file:///www/services/crypto.js:420:22)
    at Transform._read (_stream_transform.js:205:10)
    at Transform.Readable.read (_stream_readable.js:481:10)
    at flow (_stream_readable.js:992:34)
    at WriteStream.pipeOnDrainFunctionResult (_stream_readable.js:816:7)
    at WriteStream.emit (events.js:315:20)
    at afterWrite (_stream_writable.js:461:12)
    at onwrite (_stream_writable.js:446:7)
    at internal/fs/streams.js:408:5
    at FSReqCallback.wrapper [as oncomplete] (fs.js:638:5)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:129:14) {
code: 'ERR_CRYPTO_HASH_FINALIZED'
}
```

And i  can't got correct md5 hash of provided image.

I'm suspect, that `Write stream` somehow affect on `Transform stream`.

### Update:
Error is gone, when i subscribe as:
```js
const {hash, hashTransformStream} = class.getHashSummingStream()

writeStream.on("finish", async () => {
    //Here i calculate hash, for example.
    const hex = hash.digest("hex");
});
```
Why?

**Comment by bl-ue** [comment]
Hi @Folliant — can you send the whole file(s) related in a zip archive? That would make it easier for me to investigate.

**Comment by Folliant** [comment]
@bl-ue, I'm sorry. I can't send files, through gdpr issues.
But i can answer for you questions.

Also, i solved this issues through subscribe on write stream. I think it related with that i subscribed on read stream and make stuffs, when hash is calculating.

I described almost all, but i can add, that all stuffs i make in [_handleFile](https://github.com/expressjs/multer/blob/master/StorageEngine.md) from multer engine. There i get read stream.
