### ISSUE TITLE
Very weird issue with the compilation path

### ISSUE THREAD

**Issue by Emkrypted** [nodejs/help#3406]
* **Node.js Version**: v14.15.4
* **OS**: CENTOS 7.8 
* **Scope (install, code, runtime, meta, other?)**: npm run watch
* **Module (and version) (if relevant)**:

When I execute:

`npm run watch`

displays:

 `/public/js/app.js  1.94 MiB  /public/js/app  [emitted]  /public/js/app
          0.js  40.4 KiB               0  [emitted]
          1.js   690 KiB               1  [emitted]
         10.js  47.6 KiB              10  [emitted]
        100.js  31.2 KiB             100  [emitted]
        101.js  26.6 KiB             101  [emitted]
        102.js  15.4 KiB             102  [emitted]
        103.js  15.8 KiB             103  [emitted]
        104.js    30 KiB             104  [emitted]
        105.js  23.6 KiB             105  [emitted]
        106.js  17.8 KiB             106  [emitted]
        107.js  19.3 KiB             107  [emitted]
        108.js  64.6 KiB             108  [emitted]
        109.js  21.4 KiB             109  [emitted]
         11.js  44.7 KiB              11  [emitted]
        110.js  7.95 KiB             110  [emitted]
        111.js    21 KiB             111  [emitted]
         12.js  44.5 KiB              12  [emitted]
         13.js  32.7 KiB              13  [emitted]
         14.js  44.7 KiB              14  [emitted]
         15.js    47 KiB              15  [emitted]
         16.js  29.9 KiB              16  [emitted]
         17.js  57.1 KiB              17  [emitted]
         18.js  37.8 KiB              18  [emitted]
         19.js  40.6 KiB              19  [emitted]
          2.js  29.1 KiB               2  [emitted]
         20.js  53.6 KiB              20  [emitted]
         21.js  30.6 KiB              21  [emitted]
         22.js  46.9 KiB              22  [emitted]
         23.js  44.5 KiB              23  [emitted]
         24.js  30.5 KiB              24  [emitted]
         25.js  42.7 KiB              25  [emitted]
         26.js  28.6 KiB              26  [emitted]
         27.js  37.7 KiB              27  [emitted]
         28.js  41.1 KiB              28  [emitted]
         29.js  74.1 KiB              29  [emitted]
          3.js  45.6 KiB               3  [emitted]
         30.js  39.5 KiB              30  [emitted]
         31.js  57.2 KiB              31  [emitted]
         32.js  28.6 KiB              32  [emitted]
         33.js  31.7 KiB              33  [emitted]
         34.js  30.7 KiB              34  [emitted]
         35.js    39 KiB              35  [emitted]
         36.js  28.2 KiB              36  [emitted]
         37.js    62 KiB              37  [emitted]
         38.js  30.1 KiB              38  [emitted]
         39.js  47.8 KiB              39  [emitted]
          4.js  72.7 KiB               4  [emitted]
         40.js  36.3 KiB              40  [emitted]
         41.js  41.7 KiB              41  [emitted]
         42.js  35.7 KiB              42  [emitted]
         43.js    40 KiB              43  [emitted]
         44.js  62.2 KiB              44  [emitted]
         45.js  29.2 KiB              45  [emitted]
         46.js  45.5 KiB              46  [emitted]
         47.js  35.5 KiB              47  [emitted]
         48.js  30.9 KiB              48  [emitted]
         49.js    45 KiB              49  [emitted]
          5.js    61 KiB               5  [emitted]
         50.js  35.2 KiB              50  [emitted]
         51.js  37.9 KiB              51  [emitted]
         52.js  30.3 KiB              52  [emitted]
         53.js  57.1 KiB              53  [emitted]
         54.js  39.1 KiB              54  [emitted]
         55.js  41.9 KiB              55  [emitted]
         56.js  23.2 KiB              56  [emitted]
         57.js  29.9 KiB              57  [emitted]
         58.js  24.9 KiB              58  [emitted]
         59.js  25.2 KiB              59  [emitted]
          6.js    65 KiB               6  [emitted]
         60.js    39 KiB              60  [emitted]
         61.js    41 KiB              61  [emitted]
         62.js  35.4 KiB              62  [emitted]
         63.js  49.5 KiB              63  [emitted]
         64.js  72.9 KiB              64  [emitted]
         65.js  57.1 KiB              65  [emitted]
         66.js  60.7 KiB              66  [emitted]
         67.js  39.4 KiB              67  [emitted]
         68.js  29.9 KiB              68  [emitted]
         69.js  72.7 KiB              69  [emitted]
          7.js  62.4 KiB               7  [emitted]
         70.js  53.4 KiB              70  [emitted]
         71.js  50.9 KiB              71  [emitted]
         72.js  79.2 KiB              72  [emitted]
         73.js  38.8 KiB              73  [emitted]
         74.js  56.6 KiB              74  [emitted]
         75.js  50.6 KiB              75  [emitted]
         76.js    68 KiB              76  [emitted]
         77.js    34 KiB              77  [emitted]
         78.js  45.9 KiB              78  [emitted]
         79.js  37.9 KiB              79  [emitted]
          8.js  77.1 KiB               8  [emitted]
         80.js    32 KiB              80  [emitted]
         81.js  40.3 KiB              81  [emitted]
         82.js  56.6 KiB              82  [emitted]
         83.js  50.3 KiB              83  [emitted]
         84.js    45 KiB              84  [emitted]
         85.js    48 KiB              85  [emitted]
         86.js  42.6 KiB              86  [emitted]
         87.js  62.4 KiB              87  [emitted]
         88.js  29.4 KiB              88  [emitted]
         89.js  29.3 KiB              89  [emitted]
          9.js  73.3 KiB               9  [emitted]
         90.js  49.5 KiB              90  [emitted]
         91.js    20 KiB              91  [emitted]
         92.js   8.3 KiB              92  [emitted]
         93.js  8.09 KiB              93  [emitted]
         94.js  35.9 KiB              94  [emitted]
         95.js  30.6 KiB              95  [emitted]
         96.js  28.7 KiB              96  [emitted]
         97.js  40.2 KiB              97  [emitted]
         98.js  17.6 KiB              98  [emitted]
         99.js  14.3 KiB              99  [emitted]
 public/css/app.css   193 KiB  /public/js/app  [emitted]  /public/js/app`

How you can see the compilation should be inside public folder, but that is the problem I do not know why it is putting the compiled data out of public folder, it is putting the compiled data in public_html, and I do not know why because if I check webpack.js, it indicates this:

`mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');`

So I wonder why if it says that the data will be in public folder it sets the data out of public folder?

I wonder where can I check tha path?
I need help please. Thanks.

**Comment by bl-ue** [comment]
Hi @Emkrypted! Would it be possible for you to put your repository on GitHub (or GitLab) so that I could take a look at its configuration?

**Comment by gireeshpunathil** [comment]
ping @Emkrypted

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
