### ISSUE TITLE
stream url from https://nodejs.org/api/http.html#http_http_get_options_callback 

### ISSUE THREAD

**Issue by Slasshh** [nodejs/help#3407]
* **Node.js v14.15.4**:
* **OS windows 10**:
* **Module http**:

Hello everyone, I made a bot radio discord.

But I have a problem with the feed.
My problem is that every morning the bot is in the channel but it doesn't talk anymore,
I tried to put these events (close, finish) They are not triggered

For me the problem is that stream the url, but there are more audios

If some help me  

I would like to know if there is an event when it has more audio 

Here is the code:
```js
/**
 * @param connection equal to the connection of the channel discord
 * @param url url stream = (http://streamer-02.rtl.fr/fun-1-44-64?listen=webCwsBCggNCQgLDQUGBAcGBg)
 */
function play(connection, url) {

	// méthode https://nodejs.org/api/http.html#http_http_get_options_callback 
    require('http').get(url, (res) => {
        res.on('close', () => {
            console.log("close");
            play(connection, url);
        });
        connection.play(res, {
            volume: 0.5
        }).on('finish', (raison) => {
            console.log(raison);
            play(connection, url);
        }).on('error', (err) => {
            console.log(err);
        });
    });
}
```

**Comment by bl-ue** [comment]
Hey @Slasshh did you figure this out?  This issue got lost in my notifications :/
