### ISSUE TITLE
From what version is the async function* syntax supported?

### ISSUE THREAD

**Issue by bosskmk** [nodejs/help#3409]
From what version is the `async function*` syntax supported?

**Comment by addaleax** [comment]
7.6.0 – for many language features, you can look up their date of introduction in MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function :)

**Comment by bosskmk** [comment]
@addaleax 
I was asking for an async function* not an async function. iterator.
But thanks for the reply.
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/function*

**Comment by addaleax** [comment]
Ah yeah, that would be Node.js 10.0.0 then, I think.

**Comment by bosskmk** [comment]
@addaleax 
Thank you. I think you're right. It works fine in 10.3.

**Comment by bl-ue** [comment]
>7.6.0 – for many language features, you can look up their date of introduction in MDN: developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function :)

@addaleax date of introduction into ES or Node?

**Comment by addaleax** [comment]
@bl-ue Node (in the browser compatibility data).
