### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by kirkouimet** [nodejs/help#341]
* **Version**: 7.0.0
* **Platform**: Windows 10 x64
* **Subsystem**: fs

I'm getting this warning:

`(node:7512) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

The offending line of the stack trace:

`at Object.fs.write (fs.js:698:14)`

Using this code:

```
static write(fileDescriptor, buffer, offset, length, position) {
    return new Promise(function(resolve, reject) {
        fs.write(fileDescriptor, buffer, offset, length, position, function(error, written, buffer) {
            if(error) {
                reject(error);
            }
            else {
                resolve({
                    'written': written,
                    'buffer': buffer,
                });
            }
        });
    });
}
```

I'm not sure why it is complaining about the callback missing, as there is one provided. Anyone know what I am doing wrong?

**Comment by lordKnighton** [comment]
take the comma `,` away after buffer

**Comment by kirkouimetsnapchat** [comment]
Got this solved here:

https://github.com/nodejs/node/issues/9346
