### ISSUE TITLE
Docker: NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 83. Please try re-compiling or re-installing

### ISSUE THREAD

**Issue by snaildos** [nodejs/help#3414]
* **Node.js Version**: Docker
* **OS**: Docker
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:
Using image latest, nodejs buster slim.

NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
"Error: The module '/home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node'"

<!-- Please write your issue here and remove this line and the example code part. If relevant, provide some code following the example:

I'm not sure why i am getting this, does the node module version need to be updated? Is there something i can add to my docker image?

**Comment by bl-ue** [comment]
1. What command are you running? 
2. How did you install your modules?
3. Could you share your Dockerfile?

**Comment by snaildos** [comment]
Hello @bl-ue ! Thanks for that fast reply!
I own a hosting service and I am doing this for a client.
The command that the server runs is basically npm install, and starting a index.js.
NPM is getting used.
For the Dockerfile, It's on my GitHub repo, https://raw.githubusercontent.com/snaildos/images/images-debian-nodejs-14/Dockerfile

**Comment by snaildos** [comment]
Hey @bl-ue , I have resolved the issue, Using v12 resolved it. Thanks for checking in and helping though! 
Regards,
SnailDOS
