### ISSUE TITLE
stack size

### ISSUE THREAD

**Issue by Shreyasbabaladi** [nodejs/help#3415]
* **Node.js Version 12.13.0**:
* **OS:-Windows**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I can able to Increase stack size allotted to node. 

I have tryd all most every thing 

i am getting this things 

$ node --max-stack-size=4194304
C:/Program Files/nodejs/node.exe: bad option: --max-stack-size=4194304

$ node --stack-size=4194304
undefined:0
RangeError: Maximum call stack size exceeded

plz help me with this 
*/

**Comment by Shreyasbabaladi** [comment]
.

**Comment by bl-ue** [comment]
Hey @Shreyasbabaladi! What code are you trying to run?  Are you running code directly in the repl or are you running a `.js` file?

**Comment by gireeshpunathil** [comment]
ping @Shreyasbabaladi

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
