### ISSUE TITLE
Can't use some of the functions of HTTP request

### ISSUE THREAD

**Issue by vodenkaj** [nodejs/help#3416]
* **Node.js Version**: v16.3.0
* **OS**:  Windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: HTTP v7.15.1

Some of the functions that are in the [documentation](https://nodejs.org/api/http.html) are not present in current version of the HTTP module. 

Even after looking into source of the module, I can't find those functions inside request object.
For example **protocol** variable is undefined and **getHeader()** is present just in response object, even that the documentation says that it should be present in the request object too.

Maybe I'm just missing something, so I'm glad for any response and help.

**Comment by bl-ue** [comment]
Hey @vodenkaj!  I'd say you're probably just missing something (or maybe you're using an older version of node that you're not realizing?), because I'm unable to reproduce.
```console
❯ node
Welcome to Node.js v16.3.0.
Type ".help" for more information.
> req = http.request('http://google.com')
ClientRequest {
  ...
  protocol: 'http:',
  ...
}
> req.protocol
'http:'
> req.getHeader('User-Agent')
undefined
> req.getHeader('Host')
'google.com'
>
```

**Comment by vodenkaj** [comment]
Hey @bl-ue,

I just looked more into it, and it seems that the **http.server.on("request", (req, res))** is giving me incoming message object not the request one. So the request is just to make a requests from the code to some server? I guess there is no way of forcing this on request event to give me request object, right?

**Comment by bl-ue** [comment]
I guess so, though that seems odd. 🤷🏻‍♂️

**Comment by vodenkaj** [comment]
I'm sorry then, I thought that the **http.server.on("request", (req, res))** would give me request object, but based on [this](https://nodejs.org/api/http.html#http_event_request) it gives me just the incoming message, which is sadly not extending request object. 

Thanks for the help anyways, now I'm a bit smarter! 😄
