### ISSUE TITLE
bad option: --report-signal=SIGBUS

### ISSUE THREAD

**Issue by sushmitha2612** [nodejs/help#3419]
* **Node.js Version**: v12.20.1
* **OS**: MAC OS v11.4
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

whenever i use --report-signal=SIGBUS i am getting ERR node: bad option: --report-signal=SIGBUS

example code : node --report-signal=SIGBUS --report-on-signal node_modules/***** --exit

**Comment by bl-ue** [comment]
@sushmitha2612 what happened? Did you resolve your issue?

**Comment by sushmitha2612** [comment]
Hi yeah i was able to resolve it

one small question: i am getting this sigbus error from a sub-process but i am using this --report-signal=SIGBUS to parent process, will --report-signal=SIGBUS --report-on-signal be able to detect the signal ??

**Comment by bl-ue** [comment]
That's an interesting question and I don't know the answer.  I'd guess it wouldn't, because I'd think that the `--report-...` options are for when `node` itself gets a signal, but I really have no idea.  I'll have to take a look at the docs for those options — I've never actually even known about them before.

**Comment by bl-ue** [comment]
So here's what I figured out:
```console
❯ node --report-on-signal
Welcome to Node.js v16.3.0.
Type ".help" for more information.
> 
Writing Node.js report to file: report.20210618.153309.50943.0.001.json
Node.js report completed
```
then in another terminal (`50943` is the PID of the above `node` process):
```
❯ kill -USR2 50943
```
Then the node process prints this:
```
Writing Node.js report to file: report.20210618.153309.50943.0.001.json
Node.js report completed
```

**Comment by bl-ue** [comment]
Testing if `--report-...` work for child processes:

Here's a simple C program, `test.c`, compiled to `a.out`, which generates a segmentation fault `SIGSEGV`:
```c
#include <stdio.h>
int main()
{
    printf("%d\n", ((struct {int a;}*)0)->a);
}
```
I try running node with `--report-signal=SIGSEGV` to catch segfaults and run the child process:
```console
❯ node --report-on-signal --report-signal=SIGSEGV
Welcome to Node.js v16.3.0.
Type ".help" for more information.
> child_process.execSync('./a.out')
Uncaught Error: Command failed: ./a.out
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15) {
  status: null,
  signal: 'SIGSEGV',
  output: [ null, <Buffer >, <Buffer > ],
  pid: 51486,
  stdout: <Buffer >,
  stderr: <Buffer >
}
>
```
But `node` doesn't catch that.  I didn't think it would — the `--report-...` options are only for when signals hit the `node` process itself.

**Comment by bl-ue** [comment]
@sushmitha2612 for future reference, how'd you fix the original bad argument error?  Were you using an old version of node (pre v11.8.0)?

**Comment by sushmitha2612** [comment]
yes i was using node 10
