### ISSUE TITLE
n00b taking a DS course--can I use nds in python?

### ISSUE THREAD

**Issue by ajbentley** [nodejs/help#342]
I guess it's all in the title.

I'm taking a Data Science Intensive and doing a project that I would love to use the imdb api. I am unlearned in the ways of the javascript and so I don't know how / if I can use this api in python. 

Any help would be much appreciated.

Joshua

**Comment by lordKnighton** [comment]
try something like http://imdbpy.sourceforge.net/

**Comment by lordKnighton** [comment]
closing for now, feel free to reopen.
