### ISSUE TITLE
I cannot store the input from rl.question method because of a Node.js bug

### ISSUE THREAD

**Issue by arthurestigarribia** [nodejs/help#3420]
Hi Node.js team,

I'm using Node.js 16.3.0 x64 on my Windows 10 21H1 desktop.

I'm trying to store the typed text in the input of the rl.question method, but I can't. Here is the code.

`
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

var x = ''

rl.question('Type here: ', (answer) => {	
  x = answer
  rl.close()
})

console.log('You typed: ' + x)
`

And here's what's being shown in the Node.js command prompt, without giving the user a chance to make their input where it should happen:

`
Type here: You typed:
`

Only after executing the code of the entire file, the input of the rl.question method is opened. When trying to store the input of the rl.question method, in addition to the input not being stored, Node.JS is opening the input only after the entire file is executed.

Sorry for the errors in English and communication problems, but I'm not a native of this language, I'm from the extreme south of Brazil and I'm using Google Translate for help me to write this text in English. I and the beginning programmers wish a fix or another solution for this problem, because I couldn't find other alternatives on the internet to store the text typed by user in a variable in Node.JS, just like the input(text) method of Python and Console.ReadLine() method of C# do. That typed code seemed to me to be a hope for the problem, but this code is not working as expected. This issue causes many beginning programmers to give up on Node.js. I'm writing here because it seems to me to be a Node.js bug.

Thank you very much in advance.

Arthur Estigarribia
Student of the Bachelor in Applied Mathematics course at Furg Carreiros and graduated from IFRS Rio Grande as a technician in Computer Science for the Internet in a course integrated with High School.

**Comment by Ayase-252** [comment]
In short, you should get the input from user in the *callback* function of `rl.question`, like

```js
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

var x = ''

rl.question('Type here: ', (answer) => {
  x = answer
  console.log(`Answer: ${x}`)
  rl.close()
})
```

It will print the input from user. See https://nodejs.org/dist/latest-v16.x/docs/api/readline.html#readline_rl_question_query_options_callback

**Comment by arthurestigarribia** [comment]
Hi,

Thanks for trying to help me, but it wasn't what I wanted. What I actually wanted, although I forgot to say, was to store the variable so that I can perform operations outside the scope of rl.question.

If I run the suggested code with other console.log methods after the rl.question method, the bug happens that all the strings from the console.log methods are being concatenated with the question string from rl.question. 

I used the following variation of your code:

const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

var x = ''

rl.question('Type here: ', (answer) => {
  x = answer
  console.log(`You typed: ${x}`)
  rl.close()
})

console.log('You typed (again): ' + x)

Here's the output in my Command Prompt, after just putting one more console.log, this time external to rl.question. This is the bug I face.

Type here: You typed (again):
2
You typed: 2

I'm already thinking that JavaScript/Node.js is not a good language for beginners in the language itself or for those who come from other programming languages like me. If there is no solution, I will drop this topic.
