### ISSUE TITLE
CMakeLists.txt of node js

### ISSUE THREAD

**Issue by exx8** [nodejs/help#3421]
* **Node.js Version**:
* pre 17
* **OS**:
* inux
* **Scope (install, code, runtime, meta, other?)**:
* compile

Is there a CMakeLists.txt of nodejs?
I see there is a makefile for the project. Is there a pre-made CMakeLists.txt ?

**Comment by bl-ue** [comment]
No, there isn't @exx8.

@gengjiawen in https://github.com/nodejs/node/pull/37793 I see that you use CMake — are there official instructions somewhere, or can you give us some hints on how to do this?

**Comment by gengjiawen** [comment]
```console
npm i -g @gengjiawen/node-dev # only once
# after you execute config like `./configure --ninja` in Node.js repo 
node-cmake-generator -x -p python3 && node-dev patch-v8
```

**Comment by RedYetiDev** [comment]
*(question appears to have been answered)*
