### ISSUE TITLE
can--report-on-signal detect the signal on the spawned subprocess

### ISSUE THREAD

**Issue by sushmitha2612** [nodejs/help#3423]
Node.js Version: v12.20.1
OS: MAC OS v11.4
Scope (install, code, runtime, meta, other?): runtime
Module (and version) (if relevant):

can --report-signal=SIGBUS --report-on-signal be able to detect the signal on the spawned subprocess

**Comment by sushmitha2612** [comment]
any update on this??

**Comment by gireeshpunathil** [comment]
> can --report-signal=SIGBUS --report-on-signal be able to detect the signal on the spawned subprocess

the command line arguments do not inherit. the reason being that not all child processes are node processes, plus we haven't come across use cases where child process need command line inheritance.

hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
