### ISSUE TITLE
Syntax for "exports" is different in JavaScript and Node.js

### ISSUE THREAD

**Issue by htartisan** [nodejs/help#3426]
The syntax for "exports" is different in JavaScript (as used in browsers) and Node.js.  

This is an annoyance because I have created a JavaScript library (for logging) and I have been able to make the ",js" module work in both client browsers and in Node.js with 1 exception:

In browser JavaScript code, the syntax for exporting (a variable, function, or class) is by using the "export" keyword.

In Node.js code, the syntax for  exporting (a variable, function, or class) is by using "module.exports".

And of course, neither syntax is supported by the other.  Why doesn't Node.js just support the "export" keyword, the same as the browsers???

**Comment by vsemozhetbyt** [comment]
Node.js supports the "export" keyword. See some explanations in these posts:

https://dmitripavlutin.com/ecmascript-modules-nodejs/

https://dev.to/bnb/explicit-esm-in-node-js-with-mjs-3ooh (and 2 next posts)

See also Node.js docs: https://nodejs.org/api/esm.html

**Comment by gireeshpunathil** [comment]
ping @htartisan . does the solution provided by @vsemozhetbyt help you?

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
