### ISSUE TITLE
NodeJS error on execute file but on mode debug is OK

### ISSUE THREAD

**Issue by tienmanhhust** [nodejs/help#3428]
When I compile the project to execute file (.exe), the application export only log:
```
 Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
    at EventSource.n.onmessage (6.f84319ca.chunk.js:2)

```
Moreover, console.debug is hidden and project on mode debug is running OK.
Please help me!!

**Comment by gireeshpunathil** [comment]
@tienmanhhust - is this outstanding? is it possible to provide a standalone test case that reproduce the error?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
