### ISSUE TITLE
require('fs/promises') throws an error if semi colon is omitted

### ISSUE THREAD

**Issue by Clearbryan** [nodejs/help#3429]
* **Version**:v14.17.0
* **Platform**:Win 10

### What steps will reproduce the bug?
```
const fs = require('fs')
fs.unlink('path/to/file', (err) => {
// do something
})
```
The above works fine, however
```
const fs = require('fs/promises')

(async (filepath) => {
 try{
// do something
}catch(err) {
// do something
}
})('path/to/file')
```
The promise-based version throws an error if a semi-colon is omitted. Not sure if this is by design or bug

**Comment by vsemozhetbyt** [comment]
It is how JS parser works. Without semicolon, the code is parsed as consecutive function calls, which is not what you need:
```js
const fs = require('fs/promises')(/* async ... */)('path/to/file')
```
So using semicolons is more safe way till you can predict all parser quirks (see [Automatic semicolon insertion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#automatic_semicolon_insertion) or [Semicolons](https://javascript.info/structure#semicolon)).
