### ISSUE TITLE
Version not reconized

### ISSUE THREAD

**Issue by UHKing123** [nodejs/help#3432]
$ npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for main@index1.js.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hp\AppData\Local\npm-cache\_logs\2021-06-30T10_51_10_845Z-debug.log

**Comment by addaleax** [comment]
It might be helpful if you could share your `package.json` file.

**Comment by UHKing123** [comment]
{
  "name": "sdk",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "webpack": "^4.41.5",
  "scripts": {
    "postinstall": "typings install && bower install --production && jspm install && node src/tools/updateDependencies.js && npm run bundle-dep",
    "_jspm": "jspm install",
    "_postjspm": "node src/tools/updateDependencies.js && npm run bundle-dep",
    "bundle-dep": "jspm bundle \"src - [src/**/*] - [components/**/*]\" www/bundle.js",
    "start": "node dev-server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "core-util-is": "^1.0.2",
    "jspm": "^0.17.0-beta.12",
    "typings": "^0.7.12"
  },
  "devDependencies": {
    "angular2": "2.0.0-beta.15",
    "chokidar-socket-emitter": "^0.5.1",
    "express": "^4.13.4",
    "open": "0.0.5",
    "rxjs": "5.0.0-beta.2",
    "spdy": "^3.2.3"
  },
  "jspm": {
    "name": "sdk",
    "directories": {
      "lib": "src"
    },
    "dependencies": {
      "angular2": "npm:angular2@2.0.0-beta.15",
      "es6-shim": "github:es-shims/es6-shim@^0.35.0",
      "json": "github:systemjs/plugin-json@^0.1.0",
      "systemjs-hot-reloader": "github:capaj/systemjs-hot-reloader@^0.5.6"
    },
    "devDependencies": {
      "os": "github:jspm/nodelibs-os@^0.2.0-alpha",
      "plugin-typescript": "github:frankwallis/plugin-typescript@^4.0.5"
    },
    "peerDependencies": {
      "fs": "github:jspm/nodelibs-fs@^0.2.0-alpha",
      "net": "github:jspm/nodelibs-net@^0.2.0-alpha",
      "process": "github:jspm/nodelibs-process@^0.2.0-alpha",
      "reflect-metadata": "npm:reflect-metadata@0.1.2",
      "rxjs": "npm:rxjs@^5.0.0-beta.2",
      "tty": "github:jspm/nodelibs-tty@^0.2.0-alpha",
      "util": "github:jspm/nodelibs-util@^0.2.0-alpha",
      "zone.js": "npm:zone.js@^0.6.6"
    },
    "overrides": {
      "npm:angular2@2.0.0-beta.15": {
        "main": false,
        "dependencies": {
          "reflect-metadata": "npm:reflect-metadata@0.1.2",
          "rxjs": "npm:rxjs@^5.0.0-beta.2",
          "zone.js": "npm:zone.js@^0.6.6"
        },
        "peerDependencies": {
          "reflect-metadata": "npm:reflect-metadata@0.1.2",
          "rxjs": "npm:rxjs@^5.0.0-beta.2",
          "zone.js": "npm:zone.js@^0.6.6"
        },
        "jspmNodeConversion": false,
        "map": {
          "crypto": "@empty"
        },
        "meta": {
          "src/*.js": {
            "deps": [
              "reflect-metadata",
              "zone.js"
            ]
          }
        },
        "format": "detect"
      },
      "npm:reflect-metadata@0.1.2": {
        "map": {
          "crypto": "@empty"
        }
      },
      "npm:typescript@1.8.9": {
        "browser": {},
        "map": {
          "buffer": "@empty",
          "child_process": "@empty",
          "fs": "@empty",
          "path": "@empty",
          "process": "@empty",
          "readline": "@empty"
        }
      }
    }
  }
}

**Comment by UHKing123** [comment]
now I have other error

**Comment by UHKing123** [comment]
witch is this

**Comment by UHKing123** [comment]
> sdk@1.0.0 postinstall
> typings install && bower install --production && jspm install && node src/tools/updateDependencies.js && npm run bundle-dep

typings ERR! message Unable to resolve Typings dependencies
typings ERR! caused by Unable to find "typings.json" from "C:\Users\Hp\Documents\GitHub\kosovo-travel"

typings ERR! cwd C:\Users\Hp\Documents\GitHub\kosovo-travel
typings ERR! system Windows_NT 10.0.19041
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hp\\Documents\\GitHub\\kosovo-travel\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v16.4.0
typings ERR! typings -v 0.7.12

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
npm ERR! code 1
npm ERR! path C:\Users\Hp\Documents\GitHub\kosovo-travel
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c typings install && bower install --production && jspm install && node src/tools/updateDependencies.js && npm run bundle-dep

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hp\AppData\Local\npm-cache\_logs\2021-07-01T12_04_58_639Z-debug.log

**Comment by RedYetiDev** [comment]
Hi there! It seems like you've only provided the error without any context. Please give some context or describe the situation leading to this error to better assist you. This will help us understand the problem and provide a more accurate solution. Thank you!
