### ISSUE TITLE
Error: Users is not a valid user or group

### ISSUE THREAD

**Issue by devakumetsu** [nodejs/help#3436]
* **Node.js Version**: 16.4.1 and 14.17.2
* **OS**: Window 10
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

have this error while trying to install nodejs: 

An error has occurred while applying security settings. Users is not a valid user or group." This could be a problem with the package or a problem connecting to a domain controller on the network. Check your network connecting and click retry or cancel to end install

**Comment by KyntoxyJF** [comment]
I'm having the same issue !

![image](https://user-images.githubusercontent.com/46093832/124203863-f05a2800-dadd-11eb-87ec-36a8a13254cb.png)

**Comment by SetaWinsU** [comment]
Im having the same issue too!
![image](https://user-images.githubusercontent.com/76455599/124205003-9ad34a80-dae0-11eb-8a0c-497ca668b1a4.png)

**Comment by Ayase-252** [comment]
It has been tracked on https://github.com/nodejs/node/issues/39224

**Comment by Neocriss** [comment]
I'm having the same issue too!
I have Windows 10 version 20H2 (build 19042.1052).

**Comment by RoelofSandP** [comment]
Same problem here running Windows 10

**Comment by Maxou44** [comment]
Same issue on Windows 11/21H2 (build 2000.51)

**Comment by astrutz** [comment]
Try running `net localgroup /add "Authenticated Users` in your cmd as admin. Then click on "retry"

**Comment by JeremyJeanson** [comment]
Same problem on Windows 10 Enterprise (2004) connected to Active Directory. I have no problems to join or manage the domain.

**Comment by RoelofSandP** [comment]
I workes around the issue by installing nvm and updating to version 14.17.2 from there. See https://stackoverflow.com/questions/8191459/how-do-i-update-node-js

**Comment by Ayase-252** [comment]
Already resolved in Node.js v12.22.3, v14.17.3 and v16.4.2. use them or versions above them. Closing as resolved.

**Comment by Holdulv-official** [comment]
this should fix the issue
https://www.systemcamp.com/tutorial-fixing-vmware-17-6-installation-error-on-non-english-windows-systems/
