### ISSUE TITLE
Not supported Node js 10 version

### ISSUE THREAD

**Issue by DIUSII** [nodejs/help#3438]
Our project is now on version 10 of node js and it is not supported, how can this affect our project

**Comment by Ayase-252** [comment]
In short, EoL version like Node.js v10.x will not

- receive security patch
- new feature and perf. optimization
- receive bug fixing patch

Continuing use them incurs security issue in production while no further improvement will be done on them.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
