### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Szabbiii** [nodejs/help#3439]
* **Node.js Version**: 14
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: 

i get this error when i'M trying to install nodejs. I switched to another computer, and got the same issue.

![image](https://user-images.githubusercontent.com/60015127/124272096-989fd900-db3e-11eb-9bfe-82ead33a4467.png)

**Comment by Ayase-252** [comment]
Duplicated as https://github.com/nodejs/node/issues/39224

**Comment by Ayase-252** [comment]
Already resolved in Node.js v12.22.3, v14.17.3 and v16.4.2. use them or versions above them. Closing as resolved.
