### ISSUE TITLE
Please help me to solve the issue in Flash message

### ISSUE THREAD

**Issue by kirahmadlare** [nodejs/help#344]
Hi there,

I'm trying to solve the issue in my code the FLASH message is not showing when the login is successful or the login was not successful.

You can check  my code on this link:
https://github.com/kirahmadlare/AuthenticationV1

Please help!!

**Comment by lordKnighton** [comment]
So not one of your flash instances are working: Try something small just to see if it's registering in your app like:   

  ```js 
app.get('/', function (req, res) {
    req.flash('info', 'Welcome');
    res.render('index', {
      title: 'Home'
    })
  });  
```     
mostly focusing on  
```js 
req.flash('info', 'welcome') 
```
---

If thats not working, you may want to try: connect-flash ⚡️  - https://github.com/expressjs/flash

**Comment by lordKnighton** [comment]
Let me know if you need further help 💯

**Comment by kirahmadlare** [comment]
You are great :)!
