### ISSUE TITLE
Node.js Setup Wizard was interrupted

### ISSUE THREAD

**Issue by GonzagaBr** [nodejs/help#3441]
When I try to install nodejs this error happens. I tried it on 3 different computers and the same error happened. 
https://prnt.sc/1822xun
https://prnt.sc/1822z5r
How to fix?

**Comment by dududeuner** [comment]
i got the same from the first image, if u solve tell me please

**Comment by Ayase-252** [comment]
Duplicate of https://github.com/nodejs/node/issues/39224

For now, it may work to create an user named as “Authenticated Users” as reported in https://github.com/nodejs/node/issues/39224#issuecomment-872950332

Once we get a fix, a new release will be issued on all release line.

**Comment by lwhluvdemo** [comment]
I installed node .js for a brand new computer, and encountered the same problem as Figure 2, the version has been tried from 16.4.0 to 16.17.1, do you have a solution at present?
