### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by irontrol** [nodejs/help#3445]
Necesito ayuda ya que cuando intento instalar node js en mi pc me dice el siguiente mensaje "An error occurred while appiving security settings, Authenticated users is not a valid user or group. This could be a problem with the package, or a problem connecting to a doman controller on the network. Check your network connection and cick Retry, or Cancel to end the install"

![imagen_2021-07-02_173147](https://user-images.githubusercontent.com/86857339/124333991-618bf080-db5b-11eb-95dd-157b514fc7e5.png)

**Comment by vsemozhetbyt** [comment]
See https://github.com/nodejs/node/issues/39224

**Comment by Ayase-252** [comment]
Already resolved in Node.js v12.22.3, v14.17.3 and v16.4.2. use them or versions above them. Closing as resolved.
