### ISSUE TITLE
node.js setup

### ISSUE THREAD

**Issue by Cilander** [nodejs/help#3448]
![image](https://user-images.githubusercontent.com/86857899/124362319-855a3f80-dc0a-11eb-946f-52d06767ea79.png)

*Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by Cilander** [comment]
windows x64

**Comment by vsemozhetbyt** [comment]
See https://github.com/nodejs/node/issues/39224

**Comment by Ayase-252** [comment]
Already resolved in Node.js v12.22.3, v14.17.3 and v16.4.2. use them or versions above them. Closing as resolved.
