### ISSUE TITLE
Error installing NodeJs

### ISSUE THREAD

**Issue by KailashBharat** [nodejs/help#3449]
Error: I can't seem to install nodejs, it keeps sending me this error. I also tried installing on another network, but it doesn't work.
anyone have any suggestions?

![Schermopname (81)](https://user-images.githubusercontent.com/71580375/124382931-278d2c80-dcca-11eb-9b89-c425d315f93b.png)

**Comment by vsemozhetbyt** [comment]
See https://github.com/nodejs/node/issues/39224

**Comment by Ayase-252** [comment]
Already resolved in Node.js v12.22.3, v14.17.3 and v16.4.2. use them or versions above them. Closing as resolved.
