### ISSUE TITLE
UNIX sockets and passing file descriptors

### ISSUE THREAD

**Issue by ktimothy** [nodejs/help#345]
UNIX sockets have a "killer feature" - they allow to pass file descriptors from one process to another. Seem nodejs currently does not support it, though it did a long time ago http://stackoverflow.com/questions/23172610/can-you-send-a-unix-domain-file-descriptor-over-another-unix-domain-socket-in-no. 

Are there plans to add full support for UNIX sockets?

**Comment by bnoordhuis** [comment]
Node.js supports them but in an indirect way.  If you spawn a child process with `{ stdio: [ ..., 'ipc', ... ] }`, you can send  and receive handles (sockets, pipes, etc.)  Also works on Windows.

You can wrap existing file descriptors in a handle with `new net.Socket({ fd: fd })` and send over the socket but with the restriction that the file descriptor should refer to something that is pollable by interfaces like epoll.  A regular file won't work, for example.

**Comment by ktimothy** [comment]
In my case I need to pass tcp socket to nodejs process over UNIX domain socket. And I do not spawn child processes with nodejs, so I cannot use the built-in mechanism. Maybe there is way to extend it to not only nodejs-spawned processes?

> You can wrap existing file descriptors in a handle with
If I try to create socket from `fd`, I get the following error:
```
TypeError: Unsupported fd type: UNKNOWN
    at createHandle (net.js:35:9)
    at new Socket (net.js:144:20)
```
I tried to investigate the issue, and it looks like under the hood libuv cannot determine type of fd.

**Comment by bnoordhuis** [comment]
Is it a AF_UNIX+SOCK_DGRAM type socket?  Those aren't supported.  AF_UNIX+SOCK_STREAM should work though.

**Comment by ktimothy** [comment]
Yep, its Datagram. I can read work with it using ```fs.read```.

What is the reason to not to support Datagram sockets?

**Comment by bnoordhuis** [comment]
Lack of Windows support, basically.

**Comment by rektide** [comment]
Look at https://www.npmjs.com/package/usocket for an implementation of passing file descriptors over UNIX domain sockets. Thanks UNIX.

**Comment by pauldraper** [comment]
> Lack of Windows support, basically.

Thanks Windows.
