### ISSUE TITLE
Node.js Setup error while applying security settings

### ISSUE THREAD

**Issue by risingwolf21** [nodejs/help#3450]
* **16.4.1**:
* **Windows 10**:
* **Node.js Instllation Process**:

When I try to install any version of Node.js I get this error message:

![image](https://user-images.githubusercontent.com/29673745/124384400-47741e80-dcd1-11eb-951a-932607426779.png)

I don't really know what to do. 
FYI: In my Network is a pihole installed as a DHCP. Maybe there is some sort of networking problem, altough I disabled it and tried it again.

**Comment by vsemozhetbyt** [comment]
See https://github.com/nodejs/node/issues/39224

**Comment by risingwolf21** [comment]
This solved it for me, thanks.
[issuecomment-872734113](https://github.com/nodejs/node/issues/39224#issuecomment-872734113)
