### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by MeMatt-OvOvOvOvO** [nodejs/help#3452]
node-v14.17.2-x64
windows
install

I can't install it, last thing that i did, was clicking an install button, then i accept that this file will bring some changes in my PC
and the progress bar was in like 60% and it displays me something like this:
![sth](https://user-images.githubusercontent.com/85708973/124398148-719b0000-dd14-11eb-8000-ab7282ad1265.png)

**Comment by vsemozhetbyt** [comment]
See https://github.com/nodejs/node/issues/39224

**Comment by Ayase-252** [comment]
Already resolved in Node.js v12.22.3, v14.17.3 and v16.4.2. use them or versions above them.

**Comment by Ayase-252** [comment]
Already resolved in Node.js v12.22.3, v14.17.3 and v16.4.2. use them or versions above them.
