### ISSUE TITLE
Install Ghostscript in docker-node

### ISSUE THREAD

**Issue by phpgraduate** [nodejs/help#3453]
Hi,
I'm trying to install ghostscript in this docker-node. I'm creating image from <code>FROM node:8.15.0</code>
I tried following to install but it's not working. 

<code>apt-get install ghostscript</code>

Can anyone help?

**Comment by jeff-nz** [comment]
Hey @phpgraduate 

I'm assuming you are running this from your Dockerfile??

try adding the "-y" paramenter
so your code should look something like.

`apt-get install -y ghostscript`

or 
if on Dockerfile, this will start with the `RUN` command followed by the `apt-get install -y ghostscript`

so the line should look like...
`RUN apt-get install -y ghostscript`

**Comment by phpgraduate** [comment]
Hi @jeff-nz,

Thanks for the reply. Following worked for me.

<code>RUN apt-get -y update && apt-get -y install ghostscript</code>

I was missing <code>apt-get -y update</code> in my docker file.
