### ISSUE TITLE
Trying to run npm install i got this error

### ISSUE THREAD

**Issue by brizleir** [nodejs/help#3454]
C:\Users\Brizleir Tee>npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'got@5.7.1',
npm WARN EBADENGINE   required: { node: '>=0.10.0 <7' },
npm WARN EBADENGINE   current: { node: 'v14.0.0', npm: '7.17.0' }
npm WARN EBADENGINE }
 How do i correct this error

**Comment by leesei** [comment]
The package requires 0.10 <= node < 7.
Hence your Node v14 is not supported.

You can try https://github.com/nvm-sh/nvm to install an older version.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
