### ISSUE TITLE
_Authenticated user is not a valid user or group_ error message during installation

### ISSUE THREAD

**Issue by gospodnetic** [nodejs/help#3456]
I am installing latest Node.js to a Windows10 with German language pack.

Since the `Users` directory is named `Benutzer` in the German version, Node.js fails to proceed with the following message 
![image](https://user-images.githubusercontent.com/15703361/124446372-a775ce00-dd80-11eb-8f23-cf96cfa84be0.png)

The system information are as follows:
```
Betriebsystemname	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
Betriebsystemhersteller	Microsoft Corporation
Systemmodell	Pentino_H-Series A_MT_B365
Systemtyp	x64-basierter PC
System-SKU	Pentino_H-Series A_MT_B365
Prozessor	Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz, 3000 MHz, 8 Kern(e), 8 logische(r) Prozessor(en)
BIOS-Version/-Datum	American Megatrends Inc. 9001, 14.05.2019
SMBIOS-Version	3.1
```

It is possible to see related problems in other projects such as
https://github.com/GPUOpen-Archive/CodeXL/issues/2

**Comment by richardlau** [comment]
See [nodejs/node#39224](https://github.com/nodejs/node/issues/39224). We're aiming to get fixed releases out later today.

**Comment by Ayase-252** [comment]
Already resolved in Node.js v12.22.3, v14.17.3 and v16.4.2. use them or versions above them.
