### ISSUE TITLE
Default file opener for JavaScript

### ISSUE THREAD

**Issue by haneenmahd** [nodejs/help#3457]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
Nodejs should open javascript files and execute just like how we run `node program.js` in the command line⏩

**Describe alternatives you've considered**
Python files are opened default by python interpreter. 
I would like to have nodejs open javascript files by default.

**Comment by vsemozhetbyt** [comment]
May be connected: https://github.com/nodejs/node/issues/6273
