### ISSUE TITLE
HA using nodejs, Sharing variables

### ISSUE THREAD

**Issue by sunojvijayan** [nodejs/help#346]
Hi 

I am designing a High availability system and planning to use nodejs for it. My system will consist of two virtual servers. Now i will be storing some variables in server using app.locals. Is there any way these can be made available in both the servers.

Thanks in advance.

**Comment by sunojvijayan** [comment]
Hi, Any suggestions please.

**Comment by lordKnighton** [comment]
Not that I'm aware of, can't you just copy & paste the vars in the other project? 
But to get you an answer you can work with, here is something in the ballpark. 

http://stackoverflow.com/questions/11278921/how-to-share-code-between-node-js-apps

**Comment by lordKnighton** [comment]
If you need more help, do let us know.
