### ISSUE TITLE
Node.js request error： scoket hang up

### ISSUE THREAD

**Issue by godlanbo** [nodejs/help#3460]
### Version

v10.17.0 

### Platform

Darwin godlanbo 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

I want to upload a file like this:
```js
            let q = https.request({
                hostname: 'xxxx',
                path: '/service/tosupload/',
                method: 'POST',
                headers: {
                    "Content-Type": "multipart/form-data"
                }
            }, (res) => {
                console.log('错误：：：', res);
            })
            // formData is my file data
            q.write(JSON.stringify(formData))
            q.end()
```

### How often does it reproduce? Is there a required condition?

When I try to upload a smaller file (about 20kb), this problem does not occur frequently, but when I upload a file of about 50kb, this situation always occurs.

### What is the expected behavior?

Upload normally

### What do you see instead?

response is empty, err: socket hang up.
I tried it with a packet capture tool, and found that the request failed at all, and no logs were found on the server that received the file.
this is error info:
```shell
Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at TLSSocket.socketOnEnd (_http_client.js:426:9)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Additional information

This situation is currently only reproduced on my computer, and no one else has this situation, which makes me very confused

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
