### ISSUE TITLE
Node Stream Read large zip file from URL and then Unzip it 

### ISSUE THREAD

**Issue by saket-sahi** [nodejs/help#3462]
I am reading a large zip file(500MB) from a URL using request.get(url).File contains one CSV file which is pretty huge in size. I am reading the response and writing the filestream into a zip file using fs.createWriteStream(zipFile). On close event of the fs.createWriteStream I have tried using adm-zip file with which i got "error invalid or unsupported zip format. no end header found" and with Unzipper npm package I am getting "invalid signature unzip ". Below is the code

What is the  event which is triggered when  createWriteStream has completed writing the response. It is not working with 'close' , 'finish'. Only part of the file is gettin written into the zip when callback function for close event is getting triggered.
This code works well with small zip files

   const request = require('superagent');
const fs = require('fs');
const unzip = require('unzipper');
request.get(url).on('error', function(err) { console.log(err) }
                .pipe(fs.createWriteStream(zipFile))
                .on('close', function() {
                    const admZip = require('adm-zip');
                    console.log('start unzip');
                    var zip = new admZip(zipFile);
                    console.log('unzipping ' + uploadDir + "to");
                    zip.extractAllTo(uploadDir, true);
                    console.log('finished unzip');

})

With Unzipper

 request.get(url)
            .on('error', function(err) { console.log(err) }
                .pipe(fs.createWriteStream(zipFile))
                .on('close', function() {
                    fs.createReadStream(zipFile)
                        .pipe(unzipper.Extract({ path: UploadDir }));`enter code here`
                })

**Comment by VoltrexMaster** [comment]
> I am reading a large zip file(500MB) from a URL using request.get(url).File contains one CSV file which is pretty huge in size. I am reading the response and writing the filestream into a zip file using fs.createWriteStream(zipFile). On close event of the fs.createWriteStream I have tried using adm-zip file with which i got "error invalid or unsupported zip format. no end header found" and with Unzipper npm package I am getting "invalid signature unzip ". Below is the code

The larger the file size is, the more it will take to write the stream of the file into a zip file, but it really depends on your machine.

If you're having issues with those npm packages you mentioned, I suggest opening an issue in their own github repositories: [adm-zip's github repository](https://github.com/cthackers/adm-zip), [unzipper's github repository](https://github.com/ZJONSSON/node-unzipper).

> What is the event which is triggered when createWriteStream has completed writing the response. It is not working with 'close' , 'finish'.

The event is called `finish` when the write stream is finished, the `close` event is emitted when the write stream is destroyed.

> function for close event is getting triggered.
This code works well with small zip files

It just depends on your machine, how fast it will write all the stream to the zip file, it also depends on your implementation, but I don't really see anything wrong there.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
