### ISSUE TITLE
about "crypto" output problem

### ISSUE THREAD

**Issue by lanz0519** [nodejs/help#3463]
### Version

v10.6.0

### Subsystem

crypto

### What steps will reproduce the bug?

`const crypto = require("crypto");`

`let sign1, sign2, resSign1;`

`sign1 = crypto
  .createHmac("sha256", "abc")
  .update("12345678910qwertyuiop")
  .digest("hex")
  .toString();`

`sign2 = crypto
  .createHmac("sha256", "abc")
  .update("12345678910qwertyuiop")
  .digest("base64");`

`resSign1 = new Buffer(sign1).toString("base64");`

`// b3c2ef8a20f69b691982eae3e9a26b14145fc0f5c6080d90ec970af6719f2dc3`
`console.log("================sign1", sign1);`

`// s8LviiD2m2kZgurj6aJrFBRfwPXGCA2Q7JcK9nGfLcM=`
`console.log("================sign2", sign2);`

`//YjNjMmVmOGEyMGY2OWI2OTE5ODJlYWUzZTlhMjZiMTQxNDVmYzBmNWM2MDgwZDkwZWM5NzBhZjY3MTlmMmRjMw==`
console.log("================resSign1", resSign1);`

### What do you see instead?

The output of base64 encoding is inconsistent

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
