### ISSUE TITLE
Can't get path.posix

### ISSUE THREAD

**Issue by CactusWren2020** [nodejs/help#3464]
* **Node.js Version**: v14.17.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: path

I am trying to figure out why the path.basename(__filename) doesn't work in my Cypress. According to the docs, it is supposed to have path.posix that:

The path.posix property provides access to POSIX specific implementations of the path methods. The API is accessible via require('path').posix or require('path/posix').

It says it will do this:

path.posix.basename('/tmp/myfile.html'); // Returns: 'myfile.html'

Which is exactly what is not happening with path.basename(__filename). The thing is, I can't seem to access these methods. require('path').posix just gives me an undefined. I get a module not found when I require('path/posix'). Any ideas why I can't access this module?

**Comment by mStirner** [comment]
```
const path = require("path/posix");
```
Works for me neiter, moudle not found.
But the other 2 examples work fine.

Tested on Ubuntu x64 18.04. 
Perhaps the error is to Windows related?

**Comment by leesei** [comment]
POSIX standard is implemented in *nix systems only (which are not Windows).

What's the issue with `path.basename()` that you specifically need the posix version?

**Comment by CactusWren2020** [comment]
@leesei the legacy code I am working with is: 

```var path = require('path');
console.log('path', path);
var scriptName = path.basename(__filename);```

This doesn't work on my computer--it just outputs the entire path. It apparently works fine on the other developer's non-Windows system.

The node documentation says, "To achieve consistent results when working with POSIX file paths on **any operating system**, use path.posix:"

**Comment by leesei** [comment]
Can you print `__filename`? Do obfuscate any sensitive content, I just want to check the format.

**Comment by leesei** [comment]
> ```
> const path = require("path/posix");
> ```
> 
> Works for me neiter, moudle not found.
> But the other 2 examples work fine.
> 
> Tested on Ubuntu x64 18.04.
> Perhaps the error is to Windows related?

The documentation already stated (click and expand the "History") that `"path/posix"` module is available since v15.3.0.

**Comment by CactusWren2020** [comment]
```
console.log("__filename: ", __filename);

//__filename:  cypress\integration\03000_REDACTED\01000_general_test\00000_test_settings_printed_in_console.js
00000_test_settings_printed_in_console.js:8 path.basename(__filename):  

console.log("path.basename(__filename): ", path.basename(__filename));

//[[cypress\integration\03000_REDACTED\01000_general_test\00000_test_settings_printed_in_console.js]]

var path2 = require('path/posix');

//Module not found: Error: Can't resolve 'path/posix' in 'C:\xampp\htdocs\cypress_tests\duplicator-pro-tests\cypress\integration\03000_duplicatorPro\01000_general_test'

var path = require('path');
console.log(path.posix);

//undefined
```

**Comment by leesei** [comment]
Can you print `process.version`? `path.posix` module is introduced in v0.11.15 and I'm afraid your Node is older than that.

Given your code, `path.posix` is not the solution.
Did you noticed that the path separator `'\'` is escaped as `"\\"` in strings? Otherwise `'\'` will be used to escape the next character instead of being parsed as path separator.
And `02000`, `01000`, `00000` are being interpreted as octal character code which is also unexpected.
Using `String.raw()` will solve both issues, but I don't think this is available on your Node version.

Node 16.3 on Linux (so I specify the `basename()` version to be used explicitly):

```js
> path.win32.basename("cypress\integration\03000_REDACTED\01000_general_test\00000_test_settings_printed_in_console.js")
'cypressintegration\x1800_REDACTED\b00_general_test\x0000_test_settings_printed_in_console.js'
> path.win32.basename(String.raw`cypress\integration\03000_REDACTED\01000_general_test\00000_test_settings_printed_in_console.js`)
'00000_test_settings_printed_in_console.js'
> path.posix.basename(String.raw`cypress\integration\03000_REDACTED\01000_general_test\00000_test_settings_printed_in_console.js`)
'cypress\\integration\\03000_REDACTED\\01000_general_test\\00000_test_settings_printed_in_console.js'
```

Pulling code out and iterate quickly is the key for debugging.

Can you update your node version?

**Comment by CactusWren2020** [comment]
@leesei 
I updated from 14-something to 16.5. But I found out the first problem here.

All of this code is being run by Cypress and that's why it's not working. When I made a new file and just call it from the command line (node stuff.js), path.win32 and path.posix are present in the path object and work normally.

This code based on your second example:

```
console.log('1', path.win32.basename("cypress\integration\03000_REDACTED\01000_general_test\00000_test_settings_printed_in_console.js"))
```
outputs 
```
console.log('2', path.win32.basename(String.raw`cypress\integration\03000_REDACTED\01000_general_test\00000_test_settings_printed_in_console.js`))
```
Which is the end result I'm looking for. 

I still have two problems:
1.  I need to figure out how to get these functions in Cypress
2.  I need something that will properly process either linux or windows paths.

**Comment by leesei** [comment]
1. This is a Cypress issue, not Node issue. You may need to update Cypress.
2. `path.basename()` will call respective version in the platform it is running.  
    If the path you are working on matches the local platform, just use `path.basename()`. 
    Otherwise you've to detect what path it is (win32 or posix) and call the respective `basename()`

**Comment by CactusWren2020** [comment]
@leesei thank you for your help!
