### ISSUE TITLE
Program node bin\www exited with code 3221225477

### ISSUE THREAD

**Issue by hansaliyad1** [nodejs/help#3468]
### Platform

v14.17.3 32bit

### What steps will reproduce the bug?

My application is crashing with error "Program node bin\www exited with code 3221225477". If I run my app with `node bin\www`, it crashes with no message. If I run my app with `supervisor bin\www` it gives me the above error message. I read all the available articles on Google. I found no solution to it. 

### How often does it reproduce? Is there a required condition?

It crashed right after a few seconds. Supervisor will restart it, but it will keep crashing.

**Comment by gireeshpunathil** [comment]
convert this number to hexadecimal, and you will see the windows code

`3221225477 (base 10) = 0xC0000005 (base 16)` : general protection violation (equivalent to SIGSEGV)

I suggest:
 - run it without supervisor,
 -  allow it to crash
 - load the resultant core dump in windbg
 - inspect the failing context and take it from thereon

**Comment by hansaliyad1** [comment]
@gireeshpunathil I will try this. I will keep you posted. Thank you!

**Comment by gireeshpunathil** [comment]
ping @hansaliyad1

**Comment by hansaliyad1** [comment]
@gireeshpunathil 

I apologize. Right after I posted this, we moved to Azure and we no longer have the issue. We can go ahead and close the issue.
