### ISSUE TITLE
Is there any harm in using global variables in Node.js?

### ISSUE THREAD

**Issue by efkan** [nodejs/help#347]
I wonder that does using a global variable impact to my server performance, if I use 1 mb data on the `global` object in Node.js?

I want to store the static `i18n` data in `global` object.

By static `i18n` data, I mean the all things like currency codes, city names, county names etc. for several countries. I guess it occupies about 1 MB. 

And most of the views (pages) and routes woud use this `i18n` data, intensely. 

I've encountered several comments about `global` variables [over here](http://stackoverflow.com/a/10987543/3765109)

On the other hand, some modules assign themselves into the `global` object like [Intl](https://github.com/andyearnshaw/Intl.js#intljs-and-node).

Otherwise I'll import `i18n` data when I need to use it by using `require()` method. _And I cannot use my `i18n` object in a JS template system like [EJS](https://github.com/tj/ejs)_.

Also I've asked this question on [stackoverflow](http://stackoverflow.com/questions/40378768/is-there-any-harm-in-using-global-variables-in-node-js).

In addition there is [another issue](http://stackoverflow.com/questions/5447771/node-js-global-variables) on Stackoverflow. But I cannot find _why_ I should not use it.

**Comment by jasnell** [comment]
@srl295 @nodejs/intl may be able to help here.

**Comment by efkan** [comment]
I've found two answers ([fisrt](http://stackoverflow.com/a/4246397) and [second](http://stackoverflow.com/a/18635444)) about using `global` variables. 

None of them mention performance issue. I guess the main problem is traceability about an object / a function which is assigned to `global` by the programmer.

However, a confirmation of that from someone would be great.

**Comment by srl295** [comment]
I don't know about the performance. However, I'd think that what you store in the `global` is just a pointer to some other object, so it shouldn't make anything slow just by having data stored.

**Comment by efkan** [comment]
@srl295,  thank you for your comment.
Actually, I had thought just like you. However, after readng some negative comments I wanted to open this issue.
Thanks, again..
