### ISSUE TITLE
Setting up sharepoint framework development environment

### ISSUE THREAD

**Issue by sexyzahid** [nodejs/help#3471]
![npminstall](https://user-images.githubusercontent.com/14357628/125784952-da0edaab-fd08-411d-8902-dfef0819a9a3.png)

**Comment by VoltrexMaster** [comment]
Not sure what the issue here really is, what the `npm` CLI is telling you is that it created a `package.json` and `package-lock.json` file as there weren't any available in the working directory, if you want to initialize it yourself, you can just run the `npm init` npm CLI command.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
