### ISSUE TITLE
ERESOLVE unable to resolve dependency

### ISSUE THREAD

**Issue by wcomicho** [nodejs/help#3472]
Node.js Version: 14.17.3 
OS: Windows 10
Scope (install, code, runtime, meta, other?): runtime

1 Updated my nodejs 12 to 14.17.3.  
2 Opened one of my projects and ran npm i
3 Nodejs prompted vulnerabilities and ran npm audit fix
4 Error

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: type-fest@0.8.1
npm ERR! node_modules/type-fest
npm ERR!   type-fest@"^0.8.1" from globals@12.4.0
npm ERR!   node_modules/@eslint/eslintrc/node_modules/globals
npm ERR!     globals@"^12.1.0" from @eslint/eslintrc@0.3.0
npm ERR!     node_modules/@eslint/eslintrc
npm ERR!       @eslint/eslintrc@"^0.3.0" from eslint@7.19.0
npm ERR!       node_modules/eslint
npm ERR!         peer eslint@"^5.0.0 || ^6.0.0 || ^7.0.0" from @typescript-eslint/eslint-plugin@4.14.2
npm ERR!         node_modules/@typescript-eslint/eslint-plugin
npm ERR!         13 more (@typescript-eslint/experimental-utils, ...)
npm ERR!   type-fest@"^0.8.1" from read-pkg-up@7.0.1
npm ERR!   node_modules/@jest/core/node_modules/read-pkg-up
npm ERR!     read-pkg-up@"^7.0.1" from jest-resolve@26.6.2
npm ERR!     node_modules/@jest/core/node_modules/jest-resolve
npm ERR!       jest-resolve@"^26.6.2" from @jest/core@26.6.3
npm ERR!       node_modules/@jest/core
npm ERR!         @jest/core@"^26.6.0" from jest@26.6.0
npm ERR!         node_modules/jest
npm ERR!         1 more (jest-cli)
npm ERR!   7 more (read-pkg-up, globals, read-pkg-up, read-pkg-up, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional type-fest@"^0.13.1" from @pmmmwh/react-refresh-webpack-plugin@0.4.3
npm ERR! node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   @pmmmwh/react-refresh-webpack-plugin@"0.4.3" from react-scripts@4.0.3
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"^4.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by VoltrexMaster** [comment]
It seems like you're using some dependencies that the `npm` CLI wasn't able to resolve, I suggest doing a clean install by running the `npm cl` npm CLI command.

**Comment by wcomicho** [comment]
Closing this one. updated NPM and its working now.
