### ISSUE TITLE
This dependency was not found: * worker_threads

### ISSUE THREAD

**Issue by leoplaw** [nodejs/help#3475]
I previously tested and used `worker_threads` in my project.

Now when attempting to `npm run serve` or `npm run build` I'm getting the following error:

This dependency was not found:

* worker_threads

I am running `node --version  v14.17.2` so I know that `worker_threads` are supported.

I have even created a clean project with Vue CLI and when adding the following code, I still see the same error.

    const {
      Worker, isMainThread, parentPort, workerData
    } = require('worker_threads');

I've searched extensively, but all of the problems and solutions relate to earlier versions of the node that did not support it.

**Comment by gireeshpunathil** [comment]
@leoplaw - it is possible that your node binary is pointing to an older version, while you may have the said version installed in your system but not in the PATH. Can you pls double check and validate this aspect?

**Comment by leoplaw** [comment]
node --version
v14.17.2

I've also checked the install directories, and binaries, there is only Node 14 installed.

**Comment by Ayase-252** [comment]
That's weird. Could you add a line to print [`process.version`](https://nodejs.org/dist/latest-v16.x/docs/api/process.html#process_process_version)?

```js
console.log(process.version)
```
