### ISSUE TITLE
installation instructor for ubuntu from binary doesn't work with sudo

### ISSUE THREAD

**Issue by likecodeingloveproblems** [nodejs/help#3478]
* **Node.js Version**:14.17.3
* **OS**:
* Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-22-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-3320M CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000
* **Scope (install, code, runtime, meta, other?)**:install
* **Module (and version) (if relevant)**:

[installation instructors for ubuntu from binary](https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux)  does not work in the sudo. there is a note that every place you want paste it but for me as a beginner was not clear.
[this](https://stackoverflow.com/questions/63312642/how-to-install-node-tar-xz-file-in-linux)  stackoverflow answer help me.

**Comment by gireeshpunathil** [comment]
@likecodeingloveproblems - thanks for pointing this out. which specific step was the issue for you? we are ready to improve the doc, but would like to know which was right and which was misleading, thanks!

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
