### ISSUE TITLE
npm update -g npm

### ISSUE THREAD

**Issue by leokrlewis** [nodejs/help#348]
I hadn't used node in a while and was looking at my notes to update all node modules.

npm update -g npm

I had this in my notes, but when I ran it I got an error and then npm no longer worked.  I had to reinstall node.  This should be prevented from updating or installing npm like this.

Thanks,

Kenneth

**Comment by SomeoneWeird** [comment]
`npm update -g npm` is the recommended way of updating npm.

What was the error that occurred when you ran it?

**Comment by leokrlewis** [comment]
ok after I updated to the latest via nodejs.org it's not giving me the error I had originally reported.  I believe it was because I was in /usr/local/lib/node_modules when I did npm update -g npm

And npm was an earlier version.

Hope that helps.

**Comment by leokrlewis** [comment]
When I did the update this time with sudo npm update -g npm I now get the 4.0.1 but when I download and install the latest it was 3.10.8

**Comment by addaleax** [comment]
Are you an OS X user? Did you get an “uid must be an unsigned int” error? In that case, yeah, sorry, that was a bug but it has been fixed in all subsequent versions of npm (and Node).

**Comment by lordKnighton** [comment]
@leokrlewis If your still experiencing errors, reopen this issue & we will continue to help you with it. 


---

+1 @addaleax 
`yeah, sorry, that was a bug but it has been fixed in all subsequent versions of npm (and Node).`
