### ISSUE TITLE
TypeError: OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by niramay447** [nodejs/help#3480]
I have been trying to figure out how to proceed next, anyone knows any fixes?

```js
passport.use(
    new GoogleStrategy(
        {
    clientID: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    callbackURL: "http://localhost:3000/auth/google/secrets",
    userProfileURL: "https://googleapis.com/oauth2/v3/userinfo"
  },
  function(accessToken, refreshToken, profile, cb) {
    User.findOrCreate({ googleId: profile.id }, function (err, user) {
      return cb(err, user);
    });
  }
));

```
-->

**Comment by sharmankita** [comment]
Are you storing value in these enviroment variables `GOOGLE_CLIENT_ID` , `GOOGLE_CLIENT_SECRET`?

**Comment by niramay447** [comment]
> Are you storing value in these environment variables `GOOGLE_CLIENT_ID` , `GOOGLE_CLIENT_SECRET`?

Yep

**Comment by sharmankita** [comment]
> > Are you storing value in these environment variables `GOOGLE_CLIENT_ID` , `GOOGLE_CLIENT_SECRET`?
> 
> Yep

try hardcoding the values if that works then u can debug easily why it is not working.

**Comment by code123841** [comment]
fudgin hell pls help me am ded i hav been tryong to solve this error

**Comment by creativogee** [comment]
I just got this error too. What drives me nuts is that the variable is literally there in the .env which I duly required in the file of interest. It works perfectly for both google and facebook in development but my application ran into an error when deployed citing `TypeError: OAuth2Strategy requires a clientID option` please help

**Comment by GarinMcCullick** [comment]
any fix yet 😭

**Comment by Maisam-Hussain** [comment]
Don't use underscore between cliend and id, and clien and secret. e.g.
    clientID: process.env.CLIENTID,
    clientSecret: process.env.CLIENTSECRET
