### ISSUE TITLE
Nodejs installed. Bash: nvm:command not found

### ISSUE THREAD

**Issue by janekia** [nodejs/help#3481]
Nodejs 1.1.7

I downloaded nodejs and the install was successful but when I tried to use to use the command nvm -v it says command not found. 

```js
// I am an example of JS code
// please remove me too
```
-->

**Comment by vsemozhetbyt** [comment]
Did you mean `npm -v`?
`npm` (Node.js Package Manager) is installed with Node.js, while [`nvm`](https://github.com/nvm-sh/nvm) (Node.js Version Manager ) needs to be installed separately.

Alse, Node.js `1.1.7` seems to be very old version. [The last](https://nodejs.org/en/download/current/) is `16.5.0` (includes `npm` `7.19.1`).

**Comment by Ayase-252** [comment]
Yeah, `nvm` is not bound with Node.js itself. It should be installed seperately.

Closing as presumably resolved. If you have any further question about the issue, please free to comment here or reopen the issue.

**Comment by rohi221b** [comment]
check if the command prompt working or not?
