### ISSUE TITLE
ckeditor for nodejs

### ISSUE THREAD

**Issue by postgres-lang** [nodejs/help#3482]
can you help me how to show html of ckeditor from database to nodejs ui. not like this
![Capture](https://user-images.githubusercontent.com/61835216/127137370-262d6dea-3dd8-411c-96b7-1c1bfcca6c10.PNG)

**Comment by himadriganguly** [comment]
Can you please post what you have tried?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
