### ISSUE TITLE
Erro de compilação de projeto 

### ISSUE THREAD

**Issue by filipegoes98** [nodejs/help#3483]
PS C:\Projetos\4it\Project.Ui> npm install
npm WARN @vue/cli-plugin-eslint@4.5.13 requires a peer of eslint@>= 1.6.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.2.1 requires a peer of eslint@>=1.6.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-flatpickr-component@9.0.3 requires a peer of vue@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1621 packages in 19.266s

91 packages are looking for funding
  run `npm fund` for details

found 121 vulnerabilities (119 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Tentei instalar o npm e deu esse problema aqui, alguem sabe resolver ?

**Comment by GrosSacASac** [comment]
Poder ignorar aviso (WARN)

**Comment by RedYetiDev** [comment]
*Hi! Thanks for the issue. Unfortunately, Node.js (and it's maintainers) is mostly English, so it may be hard for us to understand your issue*
