### ISSUE TITLE
Inject c/c++ addons to wasm

### ISSUE THREAD

**Issue by xiangtianheng** [nodejs/help#3484]
* **Node.js Version**:v16.5.0
* **OS**:Ubuntu 20.04.2
* **Scope (install, code, runtime, meta, other?)**:other
* **Module (and version) (if relevant)**:

I am currently trying to use the injected c/c++ addons into a wasm file compiled from c/c++, and I hope to use nodejs to run that wasm file and help to inject these addons. Is this feature supported in current nodejs?

```cpp
//hello.cc
#include <iostream>
#include <stdio.h>
#include <string>

#ifdef __cplusplus
extern "C"
{
#endif

   __attribute__((import_module("env"), import_name("externalFunction"))) std::string externalFunction(void);

#ifdef __cplusplus
}
#endif

int main()
{
   std::string testString = externalFunction();
   std::cout << testString;

   return 0;
}
```
```cpp
//externs.cc
#include <napi.h>

Napi::String Method(const Napi::CallbackInfo &info)
{
    Napi::Env env = info.Env();
    return Napi::String::New(env, "hello");
}

Napi::Object Init(Napi::Env env, Napi::Object exports)
{
    exports.Set(Napi::String::New(env, "externalFunction"),
                Napi::Function::New(env, Method));
    return exports;
}

NODE_API_MODULE(hello, Init)
```
```js
//test.js
'use strict';
const fs = require('fs');
const { WASI } = require('wasi');
const { argv, env } = require('process');

const addon = require('./build/Release/externalFunction');

const wasi = new WASI({
    args: argv,
    env,
    preopens: {
        '/sandbox': '/home/sskk/intern/hello/node_wasm'
    }
});

const importObject = {
    wasi_snapshot_preview1: wasi.wasiImport,
    module: { externalFunction: addon },
    env: {
        memory: new WebAssembly.Memory({ initial: 256 }),
        table: new WebAssembly.Table({ initial: 0, element: 'anyfunc' }),
        externalFunction: addon.externalFunction
    }
};

(async () => {
    let fileContents = fs.readFileSync('./wasm/hello_SAL.wasm')
    const wasm = await WebAssembly.compile(fileContents);
    const instance = await WebAssembly.instantiate(wasm, importObject);

    wasi.start(instance);
})();
```
So from the example above, I would like to import an undefined function called _externalFunction_, and this function will be an addon in hello.cc file. Where in test.js I would like to add the addon into the wasm file compiled from the hello.cc and run this wasm file. Although there is no error message, the externalFunction seems not doing its work.

**Comment by mhdawson** [comment]
I'm not as up to speed on WASM as I'd like to be, but my first impression is that is something the WASM security model would not allow.

There would be more overhead but I think you should be able to create an addon that exports a JavaScript function that contains the code for your "externalFunction" and then call that JavaScript function from WASM.

**Comment by gireeshpunathil** [comment]
ping @xiangtianheng . does the suggestion provided help you?

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
