### ISSUE TITLE
while reading data from excell getting "Error: ENAMETOOLONG: name too long, stat" error in node.js

### ISSUE THREAD

**Issue by mreddy25** [nodejs/help#3485]
* **Node.js Version: ts-node@8.10.2**:
* **Linux**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

error description: 
while reading data from excell,  getting "Error: ENAMETOOLONG: name too long, stat" error in node.js

```
-->

**Comment by Ayase-252** [comment]
It seems to indicate that the filename of your excel file is too long. It may help to shorten the name of file.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
