### ISSUE TITLE
Cannot import fs module but all other imports work fine

### ISSUE THREAD

**Issue by jaywal1320** [nodejs/help#3486]
* **Node.js v14.17.3**:
* **macOS**:
* **Scope runtime**:
* **Module fs**:

example:
I am trying to write a json object to a csv file using json-2-csv and fs modules
I did an npm install on both modules.
But I get an error "Uncaught ReferenceError: require is not defined" for fs module only.
If I remove require("fs"), it works fine for require("json-2-csv")
I read that require cannot be used on client side, but isnt this server side?
and why does the other require work for "json-2-csv"?

```
const fs = require('fs');
const converter = require('json-2-csv');
$('#download-csv').on('click', function() {
    exportCsv("{hello}");
    //alert("Stay tuned!")
});

function exportCsv(jsonString){
    const todos = [
        {
            "id": 1,
            "title": "hello",
            "completed": false
        },
        {
            "id": 2,
            "title": "how are you",
            "completed": false
        },
        {
            "id": 3,
            "title": "have a good day",
            "completed": false
        }];
    converter.json2csv(todos, (err, csv) => {
        if (err) {
            throw err;
        }

        // print CSV string
        console.log(csv);
        //fs.writeFileSync('todos.csv', csv);
    })
}
```

**Comment by gireeshpunathil** [comment]
client side JS code (interpreted by embedded JS engine in the browser) cannot require the `fs` module which is part of the server side JS engine (Node.js). Please refer to your client side JS framework's documentation to see how this can be achieved alternatively.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
