### ISSUE TITLE
High memory overhead to represent short binary data

### ISSUE THREAD

**Issue by dapplion** [nodejs/help#3487]
I'm building a memory intensive application that needs to hold +10_000_000 roots (32 bytes) of binary data. Using Uint8Array instances they appear to have an overhead of between 150-180 bytes each. So to represent 320MB worth of root data, with Uint8Arrays the application needs about ~2GB.

Is there an efficient way in NodeJS to represent binary data? Ideally that 32 bytes require just 32 bytes in memory, or at least just a x2 overhead for length and other properties. Thank you!

**Comment by addaleax** [comment]
Is there a reason that using a single Uint8Array is not an option?

**Comment by dapplion** [comment]
> Is there a reason that using a single Uint8Array is not an option?

Yes, this data represents a binary tree for hashing, which is structurally shared by different consumers. So we need a garbage collector to manage de-allocations. The time when parts of the tree stop having references is unpredictable. So using a single Uint8Array would require to build a custom GC engine on top of it, which I'm not sure if it's feasible.

**Comment by addaleax** [comment]
Well – unfortunately, yes, `ArrayBuffer`s in V8 come with quite some overhead. `Uint8Array`s less so, but if you can’t share the `Uint8Array`, then you probably also can’t share a single underlying `ArrayBuffer`, as it’s going to be the same thing from a GC perspective.

It might be worth to try using plain arrays in your case; they are probably going to have similar overhead when compared to `Uint8Array`s, but maybe that’s a little smaller.

> So using a single Uint8Array would require to build a custom GC engine on top of it, which I'm not sure if it's feasible.

If this doesn’t need to be a super-high performance GC, and you can know when a block of memory is no longer in use (i.e. you don’t really need to implement GC per se, but rather an allocator/deallocator), this might still be a reasonable approach, tbh.

**Comment by dapplion** [comment]
> If this doesn’t need to be a super-high performance GC, and you can know when a block of memory is no longer in use (i.e. you don’t really need to implement GC per se, but rather an allocator/deallocator), this might still be a reasonable approach, tbh.

Should I use the [FinalizationRegistry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) for that? Or what other primitive would you recommend to know when a block of memory is no longer used?

**Comment by addaleax** [comment]
> > If this doesn’t need to be a super-high performance GC, and you can know when a block of memory is no longer in use (i.e. you don’t really need to implement GC per se, but rather an allocator/deallocator), this might still be a reasonable approach, tbh.
> 
> Should I use the [FinalizationRegistry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) for that? Or what other primitive would you recommend to know when a block of memory is no longer used?

I was thinking about cases in which the consumers would have a way of telling you that they are no longer using a specific block of memory. If you’re using `FinalizationRegistry`, that probably comes with a lot of overhead too.

**Comment by dapplion** [comment]
> I was thinking about cases in which the consumers would have a way of telling you that they are no longer using a specific block of memory. If you’re using FinalizationRegistry, that probably comes with a lot of overhead too.

Unfortunately you are right, the overhead using that is almost the same as Uint8Array.
