### ISSUE TITLE
DNS records

### ISSUE THREAD

**Issue by md-madhoun** [nodejs/help#3490]
Hello

My NodeJS App is working on my hosting on Godaddy.
Their help center asked me to contact NodeJS support to make them share some records with me. after that Godaddy will update that record in domain DNS.
How can I get these records?
Any one tried something similar?

Please advise

**Comment by frank-dspeed** [comment]
@md-madhoun i think they made jokes nodejs has nothing to do with godaddy no records are involved sorry.

**Comment by gireeshpunathil** [comment]
> Their help center asked me to contact NodeJS support to make them share some records with me. 

@md-madhoun - can you elaborate this statement so that I understand it? For example, what records? and to achieve what? in which context this is information was sought?

**Comment by md-madhoun** [comment]
When I run NPM install, an error message gets out:
"An error occured during installation of modules. The operation was performed, but check availability of application has failed. Web application responds, but its return code "500 Internal Server Error" or content type before operation "text/html; charset=UTF-8" doesn't equal to contet type after operation "text/html; charset=UTF-8".

**Comment by md-madhoun** [comment]
> > Their help center asked me to contact NodeJS support to make them share some records with me.
> 
> @md-madhoun - can you elaborate this statement so that I understand it? For example, what records? and to achieve what? in which context this is information was sought?

They mean DNS records

**Comment by RedYetiDev** [comment]
Node.js itself isn't a DNS, try reaching out to whoever is hosting your code.
