### ISSUE TITLE
Intercom from my phone

### ISSUE THREAD

**Issue by tunerooster** [nodejs/help#3492]
* **Node.js Version**: v14.15.4
* **OS**: termux
* **Scope**: code
* **Module**: sox-audio (I guess?)

I have node.js installed and running on Android in termux.  Though, ultimately I want the code to run in the chrome browser.  I have the following working via the termux command line:
```
pulseaudio -k 2 >/dev/null
LD_LIBRARY_PATH= pulseaudio -L "module-sles-source" -D  > /dev/null 2>&1
rec -V1 -q -b 16 -c 1 -e signed-integer -r 16000 -t wav - vol 25dB silence 1 0.1 3% 1 2.0 10% pad 1 1 |
  curl -s --data-binary @- http://frontdoor-camera/cgi-bin/speaker.sh -o /dev/null
```
This records (using sox) from the phone's mic until it hears silence, then pipes the resulting .wav stream to an IP cammera where is is played (spoken) through the camer's speaker (eg, at the front door).

This is intended to happen when a button is pressed in Home Assistant (eg, in the chrome browser).  Since browsers cannot run shell commands, and because I want it to be as responsive as possible, I would like to do the same thing, but in javascript.

Can anyone tell me how to do this (what packages to use, and maybe some example code)?

If there are better places to post this request, please let me know.

Thanks!!!

**Comment by gireeshpunathil** [comment]
though I did not try, from your explanation [electron](https://www.electronjs.org) looks like a good choice here, but pls see if it matches your requirements before spending lot of effort.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
