### ISSUE TITLE
Memory overwriting if concat vars from fs module (file read)

### ISSUE THREAD

**Issue by ticketsvl** [nodejs/help#3494]
### Version

14.17.4

### Platform

Microsoft Windows NT 10.0.19042.0 x64

### Subsystem

fs module or (maybe) array saving behavior

### What steps will reproduce the bug?

```
fs = require('fs')

function getRandomLine(filename) {
    var data = fs.readFileSync(filename, "utf8");
    var lines = data.split('\n');

    return lines[0]
}
var line1 = getRandomLine('test1.txt');
var line2 = getRandomLine('test2.txt');
console.log('line1: '+ line1);
console.log('line2: '+ line2);

console.log('concat line: '+ line1 +'_'+ line2)
```

file test1.txt contents:
```
test1aaaa
test1cccccc
```

file test2.txt contents:
```
test2bbbbbbbb
test2ddddd
```

### How often does it reproduce? Is there a required condition?

Always, checked pc and laptop with windows 10 different versions installed.

### What is the expected behavior?

Like regular on linux
```
line1: test1aaaa
line2: test2bbbbbbbb
concat line: test1aaaa_test2bbbbbbbb
```

### What do you see instead?

```
line1: test1aaaa
line2: test2bbbbbbbb
_test2bbbbbbbbest1aaaa
```

### Additional information

Looks like memory overwrite in Windows for fs module. Tried some more node.js versions too. Last current 16.6.1 - same behavior.
It killed some neural cells in my brain, coz I thought concat should work anytime.

So - 2 lines with same values, 1 line and string - concat with no problems. If only add 3rd arg to concat - it overwrites whole string.
But even 2 args are overwrited, if its from fs module. File to read can be the same, not necessary different.
If each file has only one string - no error.

It can be some array saving problem, but I didn`t tested it.

**Comment by ticketsvl** [comment]
@mscdex Any testing before move to help?

**Comment by antishok** [comment]
It only happens when the .txt files have windows line endings (CRLF or `\r\n`),
because `.split('\n')` leaves the `\r` at the end, causing the console.log to go back to beginning of the line

**Comment by ticketsvl** [comment]
Thanks for explanation! Regards.
