### ISSUE TITLE
A litle help with libs

### ISSUE THREAD

**Issue by CleytonSousa** [nodejs/help#3499]
I'am newbie, maybe that feature exist and i don't know, but we have a lot libs and tools,  to use in us projects, if... we have a graphic interface or site, comand... to show us good libs to be used in us project, or the monst used libs, or recomendation, i don't know, but we have so much libs and something to help us to know what the best or the monts recommended lib to use, gonna be good.

**Comment by gireeshpunathil** [comment]
@CleytonSousa - this is Node.js core project, and develops and maintains the core APIs, as documented here: https://nodejs.org/dist/latest-v16.x/docs/api. We generally do not make recommendation statements on libraries, tools and frameworks that are built on top of the Node.js platform, at the same time we do not restrict people making opinions here either.

So I suggest wait and see if you get some recommendations from this project, or else try in some other general purpose developer forums such as stackoverflow.

Having said that, here are some best practices that may be helpful. I would prioritize library selection based on:
 - review the API documentation of the library for its completeness and coverage
 - review the project area of the library for its activities, maintanance and release cadence
 - review the project area to see the number of active maintainers
 - review the bug tracking system of the project and see how healthy it is

hope this helps
