### ISSUE TITLE
Npm Path

### ISSUE THREAD

**Issue by NightRaidGamer** [nodejs/help#3500]
I built the node js from the source, and then I added the out / release folder to the system variables, it worked, but what about npm, I don't know where it is located, could anyone help me?

I'm using windows 10.0.19042.546
and node v17.0.0-pre

**Comment by VoltrexMaster** [comment]
The npm CLI is located at the `deps` directory (Refs: https://github.com/nodejs/node/tree/master/deps/npm).

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
