### ISSUE TITLE
Unable to import https within Expo app

### ISSUE THREAD

**Issue by mrkprdo** [nodejs/help#3503]
### Version

v14.17.3

### Platform

Microsoft Windows NT 10.0.19042.0 x64

### What steps will reproduce the bug?

By just importing https module within an expo app.
Not sure if its Node or Expo issue.

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Importing https and be able to use https.Agent() to create custom Agent

### What do you see instead?

Missing https module

### Additional information

My goal is to import https and be able to call Agent class and set custom httpAgent, specially in setting SSL cert on client side request to secure API.

**Comment by VoltrexMaster** [comment]
By looking up a few issues from the Expo project, I've noticed that this could probably be an issue with your Expo version being outdated, can't reproduce.

**Comment by chapmanh123** [comment]
Can I import through a Google mail...and option to make some Private changes.

**Comment by mrkprdo** [comment]
Found my answer couple weeks ago, tldr, i cant use node.js built-in modules within react-native apps.
But for those interested on the work-around, build the api call using java (in my case its android) and bridge java class to react-native.
https://reactnative.dev/docs/native-modules-android

as for alternative to `http` module, in java i used `HttpsURLConnection`, other alternative is `okHttp` and or `volley` / `retrofit`.

Goodluck! :)
