### ISSUE TITLE
Readline shows arrow when text is backspaced

### ISSUE THREAD

**Issue by GoBoopADog** [nodejs/help#3504]
* **Node.js Version**: v16.6.2
* **OS**: Windows 10 Home 20H2
* **Module (and version) (if relevant)**: readline

Hello everyone,
I've been trying to make a terminal client in which a user can at any time type any command and get a response back. I recently noticed that in a line, whenever text is typed, it shows up normally with nothing around it. However, when backspace is pressed, it shows > to the left of it. Is there any way to have that always show up? Or completely remove it?

![k9psUGZkyL](https://user-images.githubusercontent.com/25517283/129547687-e042ba92-2647-4da0-b4c6-35849fb41b82.gif)

```js
const readline = require('readline');
console.clear();
console.log('Hello!')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.on('line', (input) => {
  const argsV = input.split(/ +/g);
  const args = input.trim().split(/ +/g);
  const command = args.shift().toLowerCase();
  console.clear()

  if (command === 'pog') {
  console.log('poggers')
  console.log('loggers')
  }

  else {
  console.log(`Received: ${argsV}`);
  }
});
```

**Comment by GoBoopADog** [comment]
After looking into it a little more, it seems to be coming from [line 171](https://github.com/nodejs/node/blob/802ceea905848fea64a4d0630ebff1e949dc3707/lib/readline.js#L171). Still, is there any reason it keeps popping up like that? And is there any way to have it constantly up/completely remove it?

**Comment by Ayase-252** [comment]
You could set `prompt` option of `createInterface`

**Comment by GoBoopADog** [comment]
That only seems to change the arrow itself, not whether it appears or not
![A61KPT2Rdn](https://user-images.githubusercontent.com/25517283/129642074-a668b298-8723-4f5e-b64c-bbd5a8583883.gif)

**Comment by Ayase-252** [comment]
As it can be set to empty string `""` and disable it effectively

**Comment by GoBoopADog** [comment]
That helps a ton! Thank you so much!
I wish I knew what was causing it or if there's a fix someone knows about, but I'll be doing that for now. Thank you again!

**Comment by Ayase-252** [comment]
Prepending a `prompt` string before user input is part of the design. I think the purpose is to highlight the lines that user inputs. Its default value is `> `.

**Comment by GoBoopADog** [comment]
The issue is it's only showing the prompt line when (and only when) text is deleted with backspace, which I don't think is intended

**Comment by Ayase-252** [comment]
> The issue is it's only showing the prompt line when (and only when) text is deleted with backspace, which I don't think is intended

Well, it's likely a known bug. See https://github.com/nodejs/node/issues/12606.

**Comment by marcus-pousette** [comment]
Temporary fix: 
Do this after `readline.createInterface(...)`

```readline.prompt(false)```
