### ISSUE TITLE
Hh

### ISSUE THREAD

**Issue by chuky1234** [nodejs/help#3507]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by Trott** [comment]
2-day old account with lots of weird behavior indicative of a bot. (Forked the node admin repo, which is a weird thing for a 2-day old account to fork. Forked the node repo but not from nodejs--instead forked from Ethan-Arrowood, which is also very strange, especially for a 2-day-old account. Also cloned the github/docs repo which seems to be the thing all bots apparently must do or something.)

There's very little gained in blocking them, other than the avoidance of a little future annoyance as they open other issues elsewhere in the org. But there are so many of these accounts out there that it's a bit like Sisyphus and the boulder.  Only GitHub can solve this problem, but until they do (if they ever do), here's to blocking bots.

Blocked.
