### ISSUE TITLE
Export between scripts not working

### ISSUE THREAD

**Issue by chickenPizza** [nodejs/help#3508]
* **Node.js Version**: 16.6.2
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: discord.js

-So i have two scripts, on the first one i create a const ign that changes depending on what the user types on the discord server. When i read it on console.log() it return correctly but if I export it to the script2.js it returns undefined.
Also i've tried to replace the args[1] with like "banana" and it worked, I cant make the const ign static since it changes, any clue on how to do this?

discordserver.js
```js
const ign = args[1];
exports.getIgn = ign;
```
script2.js
```js
const ignMC = require('./discordserver.js');
console.log(ignMC.getIgn);
```
-->

**Comment by vsemozhetbyt** [comment]
If you need live binding, try [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get):

`discordserver.js`
```js
module.exports = {
  get getIgn() {
    return args[1];
  }
}
```
`script2.js`
```js
const ignMC = require('./discordserver.js');
console.log(ignMC.getIgn);
```

**Comment by chickenPizza** [comment]
> 
> 
> If you need live binding, try [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get):
> 
> `discordserver.js`
> 
> ```js
> module.exports = {
>   get getIgn() {
>     return args[1];
>   }
> }
> ```
> 
> `script2.js`
> 
> ```js
> const ignMC = require('./discordserver.js');
> console.log(ignMC.getIgn);
> ```

Tried but still get undefined.

**Comment by vsemozhetbyt** [comment]
Maybe you need to add more elaborated example. The current one may be oversimplified. Try to make a minimal example that reproduces the issue.

**Comment by chickenPizza** [comment]
> 
> 
> Maybe you need to add more elaborated example. The current one may be oversimplified. Try to make a minimal example that reproduces the issue.

Basically I have a discord bot where you input an command. The message then is separated and depending on the command you typed in it runs 

First script discordbot.js:
```js
client.on('message', message => {
    if(!message.content.startsWith(prefix)) return
    const author = message.author.id;
    let args = message.content.substring(prefix.length).split(/ +/);
    switch(args[0]) {
                case 'own':
                    if (args[1] === undefined && args[2] === undefined) { 
                      message.channel.send('Please input a correct minecraft or bot name')
                      break;
                    } else {
                      if(args[2] === 'bot1' && bot1 != 1) { changeTrueBot1(); iniciarScript(author, message, args)} //bot1 is a constant with value 0, if i type in discord correcty (-own blabla bot1) it changes it value to 1 with the first function and then I call the second function.
                      else {  
                      message.channel.send('error')
              } 
            }         
          break;      
})

function iniciarScript(author, message, args) {
    module.exports = {
      get getIgn() {
        return args[1];
      }
    }
    message.channel.send(args[1] + ', The ' + args[2] + ` are now yours! \n discord: <@${author}> `)

                  //this then opens the other script.js depending on which one they selected.

                  var childProcess = require('child_process');
                  
                  function runScript(scriptPath, callback) {
                      var invoked = false;
                      var process = childProcess.fork("./"+args[2]+".js");

                      process.on('error', function (err) {
                          if (invoked) return;
                          invoked = true;
                          callback(err);
                      });

                      process.on('exit', function (code) {
                          if (invoked) return;
                          invoked = true;
                          var err = code === 0 ? null : new Error('exit code ' + code);
                          callback(err);
                      });
                  
                  } 
                  runScript("./"+args[2]+".js", function (err) {
                      if (err) throw err;
                      console.log("finished running ./"+args[2]+".js");
                  })       
                } else {
                  message.channel.send('You are already using a bot!')
                }    
}

Now going to the other script I put in:
const ignMC = require('./discordbot.js');
console.log(ignMC.getIgn);
```
This gives me undefined, sorry if Its too long, theres even more code and commands in between , ive cut code but I dont think anything is missing cause these are the events that are influential in what im trying to accomplish.

**Comment by vsemozhetbyt** [comment]
Are you sure `args[1]` exists when you call `console.log(ignMC.getIgn);`?

What do you get with:
```js
    module.exports = {
      get getIgn() {
        return args;
      }
    }
```

**Comment by vsemozhetbyt** [comment]
Moreover, are you sure `iniciarScript()` is called (and `module.export` is populated) before you call `console.log(ignMC.getIgn);`?

**Comment by chickenPizza** [comment]
> 
> 
> Moreover, are you sure `iniciarScript()` is called (and `module.export` is populated) before you call `console.log(ignMC.getIgn);`?

Yep im positive, tested it without this and it runs, also passing just args gives me still undefined.
Another questions, when I do const ignMC = require('./discordbot.js'); , does this execute discordbot.js and then gets the variable  or just access it for the variable?

**Comment by chickenPizza** [comment]
> 
> 
> > Moreover, are you sure `iniciarScript()` is called (and `module.export` is populated) before you call `console.log(ignMC.getIgn);`?
> 
> Yep im positive, tested it without this and it runs, also passing just args gives me still undefined.
> Another questions, when I do const ignMC = require('./discordbot.js'); , does this execute discordbot.js and then gets the variable or just access it for the variable? Because when I do this it triggers an error and in inicializarScript() an error appears terminating everything

Yep adding const ignMC = require('./discordbot.js'); makes it execute again, and crashes it, 
is there any other way to access the first script without having to do an require()
