### ISSUE TITLE
spawn EPERM when spawning a child_process as a different group and/or user

### ISSUE THREAD

**Issue by JonnygamingTv** [nodejs/help#3510]
* **v12.19.0** & **v14.16.0**:
* **Xubuntu; Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-74-generic x86_64)** & **SUSE Linux Enterprise Server 12 (x86_64)**:
* **child_process**:

adduser --no-create-home --disabled-login --disabled-password --quiet testuser -u 1041
chown testuser:testgroup example.sh

-rwxrwx---

testuser's uID = 1041
testgroup's gID = 1005

```js
child_process.spawn("./example.sh", [], {cwd: "/home/main/test/", uid: 1041, gid: 1005});
```
-->
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:553:9)
   . . . {
  errno: 'EPERM',
  code: 'EPERM',
  syscall: 'spawn'
  } 
Promise {
  <rejected> Error: spawn EPERM
      at ChildProcess.spawn (internal/child_process.js:407:11)
      at Object.spawn (child_process.js:553:9)
. . . . {
    errno: 'EPERM',
    code: 'EPERM',
    syscall: 'spawn'
  }
}

How to get it working as desired?

**Comment by JonnygamingTv** [comment]
Possible the user running NodeJS is not allowed to spawn as another user/group?

**Comment by Ayase-252** [comment]
Yes, it probably does according to docs. Do you get a solution?

Refs: 
- https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options
- https://man7.org/linux/man-pages/man2/setuid.2.html

**Comment by JonnygamingTv** [comment]
Yes, it was exactly that (user spawning process wasn't allowed to spawn as another)
