### ISSUE TITLE
An error occurs during the source code compilation and installation of node v14.17.5 in centos7

### ISSUE THREAD

**Issue by xujiakai1990** [nodejs/help#3511]
g++ -o /root/node-v14.17.5/out/Release/obj.target/icuucx/deps/icu-small/source/common/stringtriebuilder.o ../deps/icu-small/source/common/stringtriebuilder.cpp '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DU_COMMON_IMPLEMENTATION=1' '-DU_ATTRIBUTE_DEPRECATED=' '-D_CRT_SECURE_NO_DEPRECATE=' '-DU_STATIC_IMPLEMENTATION=1' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu-small/source/common  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -Wno-strict-aliasing -O3 -fno-omit-frame-pointer -fno-exceptions -std=gnu++1y -frtti -MMD -MF /root/node-v14.17.5/out/Release/.deps//root/node-v14.17.5/out/Release/obj.target/icuucx/deps/icu-small/source/common/stringtriebuilder.o.d.raw   -c
  g++ -o /root/node-v14.17.5/out/Release/obj.target/icuucx/deps/icu-small/source/common/uarrsort.o ../deps/icu-small/source/common/uarrsort.cpp '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DU_COMMON_IMPLEMENTATION=1' '-DU_ATTRIBUTE_DEPRECATED=' '-D_CRT_SECURE_NO_DEPRECATE=' '-DU_STATIC_IMPLEMENTATION=1' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu-small/source/common  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -Wno-strict-aliasing -O3 -fno-omit-frame-pointer -fno-exceptions -std=gnu++1y -frtti -MMD -MF /root/node-v14.17.5/out/Release/.deps//root/node-v14.17.5/out/Release/obj.target/icuucx/deps/icu-small/source/common/uarrsort.o.d.raw   -c
../deps/icu-small/source/common/uarrsort.cpp: In function ‘constexpr int32_t sizeInMaxAlignTs(int32_t)’:
../deps/icu-small/source/common/uarrsort.cpp:40:34: error: ‘max_align_t’ is not a member of ‘std’
     return (sizeInBytes + sizeof(std::max_align_t) - 1) / sizeof(std::max_align_t);
                                  ^
../deps/icu-small/source/common/uarrsort.cpp:40:34: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from ../deps/icu-small/source/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ‘max_align_t’
 } max_align_t;
   ^
../deps/icu-small/source/common/uarrsort.cpp:40:66: error: ‘max_align_t’ is not a member of ‘std’
     return (sizeInBytes + sizeof(std::max_align_t) - 1) / sizeof(std::max_align_t);
                                                                  ^
../deps/icu-small/source/common/uarrsort.cpp:40:66: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from ../deps/icu-small/source/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ‘max_align_t’
 } max_align_t;
   ^
../deps/icu-small/source/common/uarrsort.cpp:41:1: error: body of constexpr function ‘constexpr int32_t sizeInMaxAlignTs(int32_t)’ not a return-statement
 }
 ^
../deps/icu-small/source/common/uarrsort.cpp: In function ‘void insertionSort(char*, int32_t, int32_t, int32_t (*)(const void*, const void*, const void*), const void*, UErrorCode*)’:
../deps/icu-small/source/common/uarrsort.cpp:144:26: error: ‘max_align_t’ is not a member of ‘std’
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                          ^
../deps/icu-small/source/common/uarrsort.cpp:144:26: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from ../deps/icu-small/source/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ‘max_align_t’
 } max_align_t;
   ^
../deps/icu-small/source/common/uarrsort.cpp:144:26: error: ‘max_align_t’ is not a member of ‘std’
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                          ^
../deps/icu-small/source/common/uarrsort.cpp:144:26: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from ../deps/icu-small/source/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ‘max_align_t’
 } max_align_t;
   ^
../deps/icu-small/source/common/uarrsort.cpp:144:77: error: template argument 1 is invalid
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                                                                             ^
../deps/icu-small/source/common/uarrsort.cpp:144:76: error: ‘constexpr int32_t sizeInMaxAlignTs(int32_t)’ called in a constant expression
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                                                                            ^
../deps/icu-small/source/common/uarrsort.cpp:144:77: note: in template argument for type ‘int’ 
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                                                                             ^
../deps/icu-small/source/common/uarrsort.cpp:144:80: error: invalid type in declaration before ‘;’ token
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                                                                                ^
../deps/icu-small/source/common/uarrsort.cpp:145:40: error: request for member ‘getCapacity’ in ‘v’, which is of non-class type ‘int’
     if (sizeInMaxAlignTs(itemSize) > v.getCapacity() &&
                                        ^
../deps/icu-small/source/common/uarrsort.cpp:146:15: error: request for member ‘resize’ in ‘v’, which is of non-class type ‘int’
             v.resize(sizeInMaxAlignTs(itemSize)) == nullptr) {
               ^
../deps/icu-small/source/common/uarrsort.cpp:151:62: error: request for member ‘getAlias’ in ‘v’, which is of non-class type ‘int’
     doInsertionSort(array, length, itemSize, cmp, context, v.getAlias());
                                                              ^
../deps/icu-small/source/common/uarrsort.cpp: In function ‘void quickSort(char*, int32_t, int32_t, int32_t (*)(const void*, const void*, const void*), const void*, UErrorCode*)’:
../deps/icu-small/source/common/uarrsort.cpp:238:26: error: ‘max_align_t’ is not a member of ‘std’
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                          ^
../deps/icu-small/source/common/uarrsort.cpp:238:26: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from ../deps/icu-small/source/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ‘max_align_t’
 } max_align_t;
   ^
../deps/icu-small/source/common/uarrsort.cpp:238:26: error: ‘max_align_t’ is not a member of ‘std’
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                          ^
../deps/icu-small/source/common/uarrsort.cpp:238:26: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from ../deps/icu-small/source/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ‘max_align_t’
 } max_align_t;
   ^
../deps/icu-small/source/common/uarrsort.cpp:238:81: error: template argument 1 is invalid
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                                                                                 ^
../deps/icu-small/source/common/uarrsort.cpp:238:76: error: ‘constexpr int32_t sizeInMaxAlignTs(int32_t)’ called in a constant expression
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                                                                            ^
../deps/icu-small/source/common/uarrsort.cpp:238:81: note: in template argument for type ‘int’ 
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                                                                                 ^
../deps/icu-small/source/common/uarrsort.cpp:238:85: error: invalid type in declaration before ‘;’ token
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                                                                                     ^
../deps/icu-small/source/common/uarrsort.cpp:239:42: error: request for member ‘getCapacity’ in ‘xw’, which is of non-class type ‘int’
     if(sizeInMaxAlignTs(itemSize)*2 > xw.getCapacity() &&
                                          ^
../deps/icu-small/source/common/uarrsort.cpp:240:16: error: request for member ‘resize’ in ‘xw’, which is of non-class type ‘int’
             xw.resize(sizeInMaxAlignTs(itemSize) * 2) == nullptr) {
                ^
../deps/icu-small/source/common/uarrsort.cpp:246:21: error: request for member ‘getAlias’ in ‘xw’, which is of non-class type ‘int’
                  xw.getAlias(), xw.getAlias() + sizeInMaxAlignTs(itemSize));
                     ^
../deps/icu-small/source/common/uarrsort.cpp:246:36: error: request for member ‘getAlias’ in ‘xw’, which is of non-class type ‘int’
                  xw.getAlias(), xw.getAlias() + sizeInMaxAlignTs(itemSize));
                                    ^
make[1]: *** [/root/node-v14.17.5/out/Release/obj.target/icuucx/deps/icu-small/source/common/uarrsort.o] Error 1
make[1]: Leaving directory `/root/node-v14.17.5/out'
make: *** [node] Error 2

**Comment by addaleax** [comment]
https://github.com/nodejs/node/blob/v14.x/BUILDING.md#fn2 says:

> GCC 6 is not provided on the base platform. Users will need the devtoolset-6 or later to source a newer compiler.
