### ISSUE TITLE
Event Loop  performance different in different version

### ISSUE THREAD

**Issue by pandaCure** [nodejs/help#3512]
* **Node.js Version**: v15.7.0 & v10.18.1
* **OS**: mac
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

```js
setTimeout(() => {
  console.log(1);
  Promise.resolve().then(() => {
    console.log(2);
  });
}, 100);
setTimeout(() => {
  console.log(3);
  Promise.resolve().then(() => {
    console.log(4);
  });
}, 100);
// version v10.18.1 1 3 2 4
// version v15.7.0 1 2 3 4
```

**Comment by Ayase-252** [comment]
Execution order between timer queue, next-tickers and microtask queue was changed in Node.js v11

Refs: https://github.com/nodejs/node/pull/22842

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
