### ISSUE TITLE
Error: Cannot find module 'C:\Users\nodemon\bin\nodemon.js'

### ISSUE THREAD

**Issue by Matias1108** [nodejs/help#3519]
### Version

Ultima Version - latest version

### Platform

VSC - Windows 10 x64

### What steps will reproduce the bug?

Cuando ejecuto npm run watch-css, execution of npm run watch-css comand.

### How often does it reproduce? Is there a required condition?

Every time i try to execute that comand - Cada vez que ejecuto ese comando.

### What do you see instead?

Error: Cannot find module 'C:\Users\nodemon\bin\nodemon.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by Ayase-252** [comment]
Could you try `npm install -g nodemon` then run your script?

**Comment by Matias1108** [comment]
> Could you try `npm install -g nodemon` then run your script?

I did it, but didn't work.

**Comment by Mesteery** [comment]
How do you run nodemon?

**Comment by Matias1108** [comment]
> How do you run nodemon?

npm install -D node-sass nodemon

**Comment by Mesteery** [comment]
Yes, okay, this is how you install it. My question is how do you run it, with what command?

**Comment by AdeetyAraJsaH** [comment]
I recently got the same problem any solution

**Comment by RedYetiDev** [comment]
> Yes, okay, this is how you install it. My question is how do you run it, with what command?

No response from author, this issue should've stale-d.

**Comment by RedYetiDev** [comment]
>  I recently got the same problem any solution

If you are experiencing similar issues with the currently supported Node.js versions, please open a new issue with detailed reproduction steps
