### ISSUE TITLE
Is fs.read() the best function for read the last chars of a file?

### ISSUE THREAD

**Issue by JTorresConsulta** [nodejs/help#352]
Hi everyone !

I need to read the last 30 chars of a .txt file with node.
Is fs.read() the best way for it? If yes, wich ones would be the rigth params? 

`fs.read(fd, buffer, offset, length, position, callback)`

Thank you very much !!

**Comment by vsemozhetbyt** [comment]
It would be helpful to know the encoding of the file — ASCII, UTF16, UTF8.

**Comment by JTorresConsulta** [comment]
Hi vsemozhetbyt, thanks


Its UTF8

The file content is like next: 

" ... [1478454838824,3296698885528]-[1478454839326,3296698885758]-[1478454839827,3296698885663]-[1478454840328,3296698885521]-[1478454840829,3296698885520]-[1478454841331,3296698885607]-"

**Comment by vsemozhetbyt** [comment]
@JTorresConsulta 

If you need asynchronous calls, the possible approach could be something like this (we assume  the file is not changed during the calls and 1 byte == 1 char): 

```js
const fs = require('fs');

fs.stat('test.txt', function postStat(errStat, stats) {
  fs.open('test.txt', 'r', function postOpen(errOpen, fd) {
    fs.read(fd, Buffer.alloc(30), 0, 30, stats.size - 30, function postRead(errRead, bytesRead, buffer) {
      console.log(buffer.toString('utf8'));
    });
  });
});
```

If you do not need asynchronous calls and the file is not big, you could do something like this:

```
const fs = require('fs');

console.log(
  fs.readFileSync('test.txt', 'utf8').slice(-30) // or .substr(-30)
);
```

**Comment by JTorresConsulta** [comment]
@vsemozhetbyt **Thank you so much!**

The synchronous (slice) method work perfect. 

The asynchronous  doesnt work, it launch:
```

 fs.read(fd, Buffer.alloc(30), 0, 30, stats.size - 30, function postRead(er
                       ^
TypeError: Object function Buffer(subject, encoding, offset) {
  if (!(this instanceof Buffer)) {
    return new Buffer(subject, encoding, offset);
  }

  var type;

  // Are we slicing?
  if (typeof offset === 'number') {
    if (!Buffer.isBuffer(subject)) {
      throw new TypeError('First argument must be a Buffer when slicing');
    }
.
.
. etc....
.
.


```

**Comment by vsemozhetbyt** [comment]
@JTorresConsulta What Node.js version do you use? It seems it does not [`Buffer.alloc`](https://nodejs.org/dist/latest-v7.x/docs/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding) (Added in v5.10.0 and, if I get it right, backported to last v4 versions). Could you upgrade? If you could not, try this legacy variant:
```js
const fs = require('fs');

fs.stat('test.txt', function postStat(errStat, stats) {
  fs.open('test.txt', 'r', function postOpen(errOpen, fd) {
    fs.read(fd, new Buffer(30), 0, 30, stats.size - 30, function postRead(errRead, bytesRead, buffer) {
      console.log(buffer.toString('utf8'));
    });
  });
});
```

**Comment by JTorresConsulta** [comment]
Yes, i had installed 4.6 

Thank you @vsemozhetbyt !
