### ISSUE TITLE
Is there a FileHandle class

### ISSUE THREAD

**Issue by lil5** [nodejs/help#3523]
* **Node.js Version**: v16.8.0
* **OS**: Linux mint 20.2
* **Scope (install, code, runtime, meta, other?)**: Typescript definitions and Documentation
* **Module (and version) (if relevant)**: n/a

I am trying to create a test to see if a variable contains a `fs.FileHandle`.

```ts
import fs, { promises as fsp } from "fs"

const f = await fsp.open(fpath, "a+")
expect(f).toBeInstanceOf(fs.FileHandle)
```

**Problem**
I can't see to find the class FileHandle, neither in `fs` nor `fs.promises`.

https://nodejs.org/api/fs.html#fs_class_filehandle
This documentation states that FileHandle is a class.

I have found the FileHandle interface in fs.promises but I'm interested in using `instanceof <class>`.

**Question**
Is there a FileHandle class and where is it?

**Comment by lil5** [comment]
I have found the FileHandle interface in `fs.promises` but the documentation appears to state the properties of a FileHandle class.

**Comment by Mesteery** [comment]
The `FileHandle` class isn't exported. Is there a reason to access it?

**Comment by lil5** [comment]
@Mesteery For my use case it is handy to beable use `instanceof` in tests

My code example should explain it.

**Comment by Mesteery** [comment]
You can get the `constructor`, and therefore `FileHandle`, but it's useless, since instanceof will always be true:
```js
const fh = await fsp.open(...);
fh instanceof fh.constructor /* FileHandle */;
```

**Comment by lil5** [comment]
Yeah that works but for unit tests is useless.

Indeed there are better tests to write, but with large functions it is good to be able to test is a value is what it says it is.
For now I will keep to using a test that expects what it is not.
