### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Nomad-TXT** [nodejs/help#3529]
Failed to install a new version of Node. js How can i fix it?
![Captura de pantalla 2021-09-07 204102](https://user-images.githubusercontent.com/90296170/132434992-b0fb8efc-03f3-4a1c-afcb-b952f6354f50.png)

**Comment by suryapratapsinghsuryavanshi** [comment]
This is not a huge problem use the below steps.
* Go to the `C:\Windows` and find the `Temp` folder.
* Right click on the "Temp" folder and choose `Properties` Option.
* After clicking `Properties` navigate to the `Security` Tab.
* And click to the `Edit` Button.
* Select your `Desktop` name or `Admin` name.
* And allow the `Full Control`.
![Screenshot (476)](https://user-images.githubusercontent.com/67123991/134188723-2c55e8b2-2992-45e7-aa0d-42397338c870.png)
After all the steps restart your machine. :)

**Comment by gireeshpunathil** [comment]
@Nomad-TXT - does the provided suggestion help solve your issue?

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
