### ISSUE TITLE
clear process.nextTick() is possible?

### ISSUE THREAD

**Issue by eugen35** [nodejs/help#353]
Hello!

Is it possible to clear process.nextTick(), - refuse frome something, that you have planned to run with __process.nextTick()__ ? It is need to free computer ressources, if it turns out that I do not need a result delayed function.

__I search for functionality like this__:
clearImmediate( id ) or clearTimeout( id )

__example__:
let idOfMyDeferredFunc = process.nextTick( () => longSyncOperation(1000 ms) )
...
if ( i dont need the result ) clearProcessNextTick( idOfMyDeferredFunc )

**Comment by Fishrock123** [comment]
Not at the current time and it is not exactly planned. Is there any reason you cannot use `setImmediate()` instead?

**Comment by eugen35** [comment]
I can use setImmediate in general. And use now.
But as known there is the difference between these methods.
setImmediate is slower in the cases where is I/O, because it runs after i/O (as i have read)

**Comment by eugen35** [comment]
So i only will use the fastest methods in my code. And clearNextTick(id) will add the code more quickness (or more exact - more perfomance, when refuse from deferred with nextTick, but not needed tasks).

**Comment by eugen35** [comment]
May be is there any hack to do this?

For example:

```
process.nextTick( () => longSyncOperation(1000 ms) )
let idOfMyDeferredFunc = process.deferredTaskIds[ process.deferredTaskIds.length - 1 ]
process.deferredTasks.splice(idOfMyDeferredFunc, 0, 1)

```

**Comment by Fishrock123** [comment]
`setImmediate `is not slower but I/O does run before it. In most cases that is what you probably want and it should not make a practical difference on your application's performance unless you are doing something incorrectly.

**Comment by eugen35** [comment]
Thank you for answer. Good luck!
