### ISSUE TITLE
PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false } Error: Cannot enqueue Query after fatal error.

### ISSUE THREAD

**Issue by Pragati87** [nodejs/help#3532]
I am using node js and mysql. and i am making single connection. Everything was working fine but got this error only once : PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false } Error: Cannot enqueue Query after fatal error. at Protocol._validateEnqueue
Restarted the mysql server,it started working fine again and problem did not reoccur since. Is there any way to reproduce this issue to further apply a proper solution to the problem.as for now error is not coming at all but it could. I tried load testing with 1000s of requests but it ran fine.

* **Node.js Version**: 15.11.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by VoltrexMaster** [comment]
This should help: https://github.com/mysqljs/mysql/issues/900

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
