### ISSUE TITLE
Nothing is reflected when entering the command（node/npm）

### ISSUE THREAD

**Issue by lyxsilence** [nodejs/help#3538]
### Version

14.17.6

### Platform

win10

### Subsystem

Microsoft Windows NT 10.0.18362.0 x64

### What steps will reproduce the bug?

Not sure

### How often does it reproduce? Is there a required condition?

It's not working properly, I just restarted the computer

### What is the expected behavior?

use

### What do you see instead?

![image](https://user-images.githubusercontent.com/32365105/133420773-a290e83b-f24b-49f3-b5eb-41944683ede2.png)

![image](https://user-images.githubusercontent.com/32365105/133421135-9320d814-4111-48fa-bf29-07b9444f087f.png)

Nothing is reflected when entering the command（node/npm）, and nothing is reflected when double-clicking the installation package. Installed using'msiexec /package'

**Comment by Ayase-252** [comment]
How do you install Node.js? How about try a installer listed on https://nodejs.org/en/download/current/?

**Comment by lyxsilence** [comment]
is here http://nodejs.cn/

**Comment by lyxsilence** [comment]
> How do you install Node.js? How about try a installer listed on https://nodejs.org/en/download/current/?

Was downloaded here http://nodejs.cn/

**Comment by Ayase-252** [comment]
Could you try https://nodejs.org/dist/v16.9.1/node-v16.9.1-x86.msi?

**Comment by lyxsilence** [comment]
> Could you try https://nodejs.org/dist/v16.9.1/node-v16.9.1-x86.msi?
> 
> https://nodejs.org/dist/v16.9.1/node-v16.9.1-x64.msi if you use 64 bit OS

yeah   nothing happened

**Comment by lyxsilence** [comment]
> Could you try https://nodejs.org/dist/v16.9.1/node-v16.9.1-x86.msi?
> 
> https://nodejs.org/dist/v16.9.1/node-v16.9.1-x64.msi if you use 64 bit OS

msiexec Can be installed， But it's still useless after installation 
![image](https://user-images.githubusercontent.com/32365105/133426303-b4acc984-35fd-46ff-bd07-cf95b35d9c07.png)

**Comment by lyxsilence** [comment]
> Could you try https://nodejs.org/dist/v16.9.1/node-v16.9.1-x86.msi?
> 
> https://nodejs.org/dist/v16.9.1/node-v16.9.1-x64.msi if you use 64 bit OS

sorry    Blocked by the company's security policy

**Comment by Ayase-252** [comment]
I think that something is messed up in your CLI. However, I'm not familiar with cmd on Windows. Maybe folks on @nodejs/issue-triage spot something unusual? 

cc @nodejs/issue-triage

**Comment by lyxsilence** [comment]
> I think that something is messed up in your CLI. However, I'm not familiar with cmd on Windows. Maybe folks on @nodejs/issue-triage spot something unusual?
> 
> cc @nodejs/issue-triage

solved,  Blocked by the our company's security policy 
Thank you!!!!
