### ISSUE TITLE
Permitir arquivos estáticos no HTML sem o uso de bibliotecas?

### ISSUE THREAD

**Issue by carcleo** [nodejs/help#3539]
Então, estou fazendo
```
fs.readFile(
      dirname + "/index.html",
      "utf8",
      function (err, data) {      
        response.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });  
        response.write(data)
        return  response.end();
     }
 )
```
Para ler arquivo **html**

Funciona corretamente.

No entanto, preciso adicionar links imagens, folhas de estilo, etc... mas dá erro quando adiciono!

Existe uma forma de permitir isso no HTML sem o uso de bibliotecas?

**Comment by RedYetiDev** [comment]
Hi! Node.js isn't an HTML interpreter, so there isn't a way to achieve what you're looking for natively.
