### ISSUE TITLE
Discrepancy in regex engine

### ISSUE THREAD

**Issue by crimson-med** [nodejs/help#3542]
* **Node.js Version**: 16.9.0
* **OS**: MacOS
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: RegExp

I have a regex that executes with no issues on all platforms but that fails in nodejs

```js
const regex = /(?<email>((?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])))\s*\|\s*(?<name>([a-zA-Z]{2,}\s[a-zA-Z]{1,}'?-?[a-zA-Z]{2,}\s?([a-zA-Z]{1,})?))\s*\|\s*(?<address>.*)\s*\|\s*(?<country>(\w|\.|\s*){1,})\s*\|\s*(?<phone>(\d|-|\ |\+|\(|\)|\.|\/){7,})/gm;
const uniqueStr = `jane.doe@aol.test| Jane Doe| 8415 45th St| Lyons IL 60534| United States| 0005800000`

const test = regex.exec(uniqueStr)
if (test && test.groups) {
    console.dir(test.groups)
} else {
    console.log('could not match')
    console.log(uniqueStr)
}
```

Executing this in the browser (firefox, chrome) brings up a match
Executing this on Regex101 (https://regex101.com/r/52kpRD/1/) brings up a match
Executing this in NodeJS brings NO match

This is a simplified example if you need for `uniqueStr` that don't match only on NodeJS I can give more.

**Comment by vsemozhetbyt** [comment]
I cannot reproduce on Node.js 16.9.0 on Windows. Your code logs:
```
[Object: null prototype] {
  email: 'jane.doe@aol.test',
  name: 'Jane Doe',
  address: '8415 45th St| Lyons IL 60534',
  country: 'United States',
  phone: '0005800000'
}
```

**Comment by devsnek** [comment]
your regex uses the `/g` flag, if you're running other matches on it, you'd need to reset the `lastIndex` property on it before matching again.

**Comment by crimson-med** [comment]
> I cannot reproduce on Node.js 16.9.0 on Windows. Your code logs:
> 
> ```
> [Object: null prototype] {
>   email: 'jane.doe@aol.test',
>   name: 'Jane Doe',
>   address: '8415 45th St| Lyons IL 60534',
>   country: 'United States',
>   phone: '0005800000'
> }
> ```

Wednesday ill be in office ill quote exact version of os and other information.



> your regex uses the `/g` flag, if you're running other matches on it, you'd need to reset the `lastIndex` property on it before matching again.

this regex is used only on that line and it gives me a negative match.
