### ISSUE TITLE
Creating `node.js` Script will Result in Any Commands Error

### ISSUE THREAD

**Issue by stanleyowen** [nodejs/help#3547]
### Version

v14.17.6

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### What steps will reproduce the bug?

1. Create a file named `node.js`
2. In the same **directory**, run node commands which execute any files in the **current** directory such as `node node.js` to execute the file
3. See the error

### How often does it reproduce? Is there a required condition?

I notice that this error can always be reproduced when the `node.js` file is present on the current directory, until I rename the file name.

### What is the expected behavior?

The `node <filename>` command shouldn't return any error when `node.js` filename is present.

### What do you see instead?

![Creating node.js Script will Result in Any Commands Error](https://user-images.githubusercontent.com/69080584/134662234-2aa60e31-7ee3-4899-95f5-dbe2c5082985.png)

**Comment by RedYetiDev** [comment]
Hi! This seems like an issue with the Windows computer settings. Make sure to open the file using Node, not the Windows default (or set Node as the default).

I'm closing this issue because it's been a few years since the last activity. If you disagree, please let me know.
