### ISSUE TITLE
trigger default actions of uncaughtException and signal events from own handlers

### ISSUE THREAD

**Issue by Flarna** [nodejs/help#355]
Is there a way to trigger the default actions of uncaughtException and signal events even in case I have installed my own listeners?

I would like to install such listeners to have the chance for some logging/... but after that I would like to do the same as what would happen if my listeners are not installed.
e.a. log the uncaughtException cause like nodejs (not just the stack trace itself).

**Comment by bnoordhuis** [comment]
I think you could simply rethrow the exception if you remove your uncaughtException listener first.

**Comment by Flarna** [comment]
Unfortunately this is not working.
The printed error object of the re-thrown error is the same but the location of the throw statement (arrow line) is not pointing to the original location it points to the throw statement in my listener.

To my understanding the relevant info is in the message argument of OnMessage() in node.cc which is not passed from native to JS.
