### ISSUE TITLE
USING REACT NATIVE CANNOT USE THIS COMMAND GIT INIT REACT-NATIVE

### ISSUE THREAD

**Issue by faisalmirji123** [nodejs/help#3553]
expo init React-Native
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'C:\Users\dell\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:730:27)←[39m     
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by VoltrexMaster** [comment]
Seems like you didn't correctly install the `expo` CLI correctly, I suggest trying to uninstall `expo-cli` using the `npm uninstall <package name>` subcommand and reinstalling it using the `npm install <package name>` subcommand, if that doesn't work; you should try to do a clean install by using the `npm ci` subcommand.

**Comment by faisalmirji123** [comment]
Thanks ill check it out
