### ISSUE TITLE
LetsEncrypt CA expiry - Tomorrow? Thursday?

### ISSUE THREAD

**Issue by btsimonh** [nodejs/help#3555]
* **Node.js Version**: 6.9.11/12.13.0
* **OS**:all
* **Scope (install, code, runtime, meta, other?)**:other
* **Module (and version) (if relevant)**:https (CA certificates)

I can't find any info about the LetsEncrypt CA cert running out in (1 day's?) time with references to NodeJS clients.

Has anyone investigated what may happen when NodeJS (specifically the versions above...) tries to access a site protected by a LetsEncrypt cert after the older CA expires?

in Chrome, I can see:
![image](https://user-images.githubusercontent.com/3137332/135131419-9dbc1f0a-17fd-45d1-a4dc-a95839fc50a4.png)

and

![image](https://user-images.githubusercontent.com/3137332/135131566-7e603e91-0643-4f89-b868-03530acaff27.png)

and

![image](https://user-images.githubusercontent.com/3137332/135131630-f33e0433-4da9-4c33-b085-92bd75330a4d.png)

but I'm not sure if Chrome is hiding the cross-signed cert, or if it will all break tomorrow?

br,

Simon

**Comment by btsimonh** [comment]
OK, so the intermediate 'R3' cert expired today.

Chrome now shows:

![image](https://user-images.githubusercontent.com/3137332/135400723-4bc23016-b1ae-4776-bf9c-85101cc085b8.png)

which includes the new certificate, and the NodeJS clients are still working.... (at least those based on 12.13.0).

**Comment by btsimonh** [comment]
Update:
**Later builds of my 12.13.0 clients work, earlier builds do not.  At first I thought it had merely cached the certs, and failed whilst running, but even restarting them they can no longer access my Let's Encrypt SSL site.** 

So... if you have a similar problem, you MUST use a later build of nodejs.

Q: does the nodejs build process download the CA certs as part of the build process?  I'm pretty sure I have clients of different build ages but the same version (both 12.13.0) behaving differently....?

**Comment by RedYetiDev** [comment]
Currently, this issue is hard to understand, as little code is provided. If you still believe it is valid, please provide more context.

**Comment by btsimonh** [comment]
Since NodeJS builds in the certs, when a CA cert expires, node executables that do not include the new certs will no longer be able to access certain HTTPS sites without reducing the security, and ignoring cert errors.
For MOST users, this is not a problem, as they can upgrade nodejs.  But because we build an application which includes NodeJS, unless we rebuild it with each change, it can fail in this way.

For future people searching, the way I got around this in Windows was by creating this repo:
https://github.com/btsimonh/node-windows-root-certs
This loads the root certs installed in windows, and adds them to the NodeJS root certs available dynamically.
(Maybe this is something that could be considered for NodeJS itself, if it has not already?).

Note that this ALSO solves the issue of using nodejs behind a WAF where the WAF is a 'legalised' man in the middle with certs installed on the machine.  Arguably a better solution than reducing the security by ignoring TLS errors.

I'm happy for the issue to remain closed :).
