### ISSUE TITLE
Get protocol (easily) vanilla style (no express here)?

### ISSUE THREAD

**Issue by blaasvaer** [nodejs/help#3557]
I've been trying to simply get the protocol from a request in Node (v.14.15.0), but after hours I still haven't found it ... is it there?

The docs claim that request.protocol was added in v 14.5.0 and I'm running v 14.15.0 ... but req.protocol is always undefined. As is req.headers.referer and all the other hundreds of suggestions on stackoverflow that I've tried.

Anyone have any idea about what I'm obviously missing?

**Comment by aduh95** [comment]
It'd be helpful to share a minimal example of code so it's clear what you are trying to do. By protocol, do you mean "is it `http` or `https`"? What does "received request" means in this context?

**Comment by blaasvaer** [comment]
If I do:
```
http.createServer( (req, res) => {
	// The ONLY way I can get the protocol from here is by: req.headers.referer.split('://')[0]
	// Which I find damn ugly. Why this isn't simply part of the framework itself surprices me?
} ).listen(port, hostname, () => {
	console.log(`Server running at http://${hostname}:${port}`);
});
```

**Comment by mscdex** [comment]
If you want a generic request handler that can detect whether the request came in via http or https, you can simply just check [`req.socket.encrypted`](https://nodejs.org/docs/latest/api/tls.html#tls_tlssocket_encrypted), if it's `true`, then it's a request over https. If not, then http.

**Comment by blaasvaer** [comment]
Yeah, that's was one of the many 'solutions' I found in my search ... still feels very counter intuitive. But thanks anyway.
