### ISSUE TITLE
Installing packages error

### ISSUE THREAD

**Issue by kaytitulaer3820** [nodejs/help#3569]
* **Node.js Version**: 10.19.0
* **OS**: Linux mint
* **Scope (install, code, runtime, meta, other?)**: Installing pakages

When i try to install the needed packages for my discord bot. it doesn't work. idk where.

Logs:
[2021-10-08T16_41_30_975Z-debug.log](https://github.com/nodejs/help/files/7312986/2021-10-08T16_41_30_975Z-debug.log)

**Comment by theifedayo** [comment]
why not upgrade to the recent stable node version? most of these issues have been fixed there

**Comment by i5ik** [comment]
Hey @kaytitulaer2008 try using [nvm](https://github.com/nvm-sh/nvm#installing-and-updating) to keep track of your node versions and let you install the latest versions, and have multiple versions on the system at the same time. Try nvm today!!! :) ;p xx
