### ISSUE TITLE
Running same command on the terminal and child_process.spawn lead to different results

### ISSUE THREAD

**Issue by ianho7** [nodejs/help#3573]
### Version

v14.17.0

### Platform

Darwin Ians-MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Subsystem

MacOs Big Sur 11.4

### What steps will reproduce the bug?

Hi guys, I'm developping a 3D printing electron app, some of its features require using child_process.spawn to call the SDK command to complete, however I find that the results produced by `child_process.spawn`are different and incorrect most of time. Meanwhile, running the same command in terminal produce a unique and correct result.The details are as follows:

Code of using child_process.spawn:
```
const process = spawn(
    CURA_ENGINE_PATH,
    ['slice', '-v', '-p', '-j', configPath, '-o', targetPath, '-l', sourcePath]
  )

  process.stdout.on('data', (data) => {
    console.log(data.toString())
  })

  process.stderr.on('data', (data) => {
    console.log('err: ' + data.toString())
  });

  process.on('error', e => {
    console.log(e)
  })

  process.on('close', (code) => {
      console.log('slice progress closed with code ' + code);
  });
```
Incorrect results of using child_process.spawn
```
// Result 1
Progress:export:284:286 	0.995846%
Progress:export:285:286 	0.997747%
Progress:export:286:286 	0.999648%
Progress: export accomplished in 0.065s
Progress:process:1:1 	1.000000%
Total time elapsed  0.11s.
Gcode header after slicing:
;FLAVOR:Marlin
;TIME:135
;Filament used: 0.036069m
;Layer height: 0.2
;MINX:-14.852
;MINY:284.912
;MINZ:0.2
;MAXX:20.004
;MAXY:312.165
;MAXZ:57.2
End of gcode header.
Print time (s): 135
Print time (hr|min|s): 0h 2m 15s
Filament (mm^3): 86

// Result 2
Progress:process:1:1 	1.000000%
Total time elapsed  0.26s.
Gcode header after slicing:
;FLAVOR:Marlin
;TIME:474
;Filament used: 0.0801326m
;Layer height: 0.2
;MINX:-16.325
;MINY:282.656
;MINZ:0.2
;MAXX:26.565
;MAXY:310.518
;MAXZ:59.4
End of gcode header.
Print time (s): 474
Print time (hr|min|s): 0h 7m 54s
Filament (mm^3): 192
```

Command of using Mac terminal
`CuraEngine slice -v -p -j config.json -o target.gcode -l source.stl`

Correct result of running command in Mac terminal
```
Progress:process:1:1 	1.000000%
Total time elapsed  2.83s.
Gcode header after slicing:
;FLAVOR:Marlin
;TIME:6590
;Filament used: 4.13689m
;Layer height: 0.2
;MINX:-26.331
;MINY:278.953
;MINZ:0.2
;MAXX:26.663
;MAXY:324.672
;MAXZ:66.6
End of gcode header.
Print time (s): 6590
Print time (hr|min|s): 1h 49m 50s
Filament (mm^3): 9950
```

As you can see, the  correct and unique print time is `1h 49m 50s`, however got ` 0h 7m 54s`,`0h 2m 15s` and mang other wrong results via child_process.spawn, which confuses me 😭 , did I do something wrong in the code?

### How often does it reproduce? Is there a required condition?

Most of time

**Comment by gireeshpunathil** [comment]
@ianho7 - without knowing the logic that computes the print time, it is hard to tell where things are going wrong. Given the relatively smaller time in the bad case, I would assume that the child process is exiting early (due to a potential error) and then the exit time is used to compute the print time, or something similar.

Is there a way to figure out if the child process has executed completely or not, externally to this program?

**Comment by ianho7** [comment]
> @ianho7 - without knowing the logic that computes the print time, it is hard to tell where things are going wrong. Given the relatively smaller time in the bad case, I would assume that the child process is exiting early (due to a potential error) and then the exit time is used to compute the print time, or something similar.
> 
> Is there a way to figure out if the child process has executed completely or not, externally to this program?

Hi @gireeshpunathil , thanks for your response.

The logic of computing print time is packaged in the SDK, so I can't figure it out too. After testing, some error logs will be printed while using child_process.spawn, which will not appear in terminal, and both of their exit code is 0, it is reasonable to say that they both exit normally?

I also asked the author of SDK just now, he told me that the situation of SDK runs well in terminal but goes wrong in child_process.spawn, more likely causes by Node or child_process.spawn using problems.

So is it possible cause by some envirment params or other child_process.spawn options etc...

**Comment by gireeshpunathil** [comment]
the only difference between running a process in the shell versus chid of a Node process AFAIK is that the former shares the standard streams with the parent (shell), while the child process uses pipes to connect those streams with the parent Node (through which you tap the child data). If the SDK logic somehow depends on this, then the timing can change; but I don't know!

Another reasonable way is to use `strace` in both cases and see if the sdk process is spawned with the same input in both cases.

`strace -f <program>`

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
