### ISSUE TITLE
pass args for a js in Node.js

### ISSUE THREAD

**Issue by jpmfa** [nodejs/help#3575]
Hello,

I have a js that I use as an app where I pass username and password.

this is how it works in prompt: node main.js --username admin --password pass

now, I'm trying to execute it in my node server via browser with:

const bundle = require ('./js/main.js')("--username admin --password pass")

the require runs the app but args are not working. How to fix this?

BR,

Joao

**Comment by RedYetiDev** [comment]
Node.js doesn't support arguments (in CLI form) for requiring modules. 

You could make your module can in them as a object?
```js
require("module")({username, password})
```

With your module excepting them like:
```js
module.exports = ({username, password}) => ...
```
