### ISSUE TITLE
Why `domainToASCII` is written by C++ not JS?

### ISSUE THREAD

**Issue by wafuwafu13** [nodejs/help#3577]
* **Node.js Version**: 16.11.1
* **OS**: macOS Big Sur
* **Scope (install, code, runtime, meta, other?)**: code

Why `domainToASCII` is written by C++(internalBinding) not JS?

https://github.com/nodejs/node/blob/76249170691b8bf08e5cd81a13f123f3586525d0/lib/internal/url.js#L86-L87

https://github.com/nodejs/node/blob/76249170691b8bf08e5cd81a13f123f3586525d0/src/node_url.cc#L1717-L1733

**Comment by RaisinTen** [comment]
Since it makes use of the C++ class `URLHost` - https://github.com/nodejs/node/blob/76249170691b8bf08e5cd81a13f123f3586525d0/src/node_url.cc#L56, which is written in C++ for perf reasons

**Comment by wafuwafu13** [comment]
I understand that perf is the reason.
Thank you!
