### ISSUE TITLE
🆘  Node.js is not installed

### ISSUE THREAD

**Issue by prolayc** [nodejs/help#3578]
### Version

v14.18.1

### Platform

Microsoft Windows NT 10.0.19043.0 x64

### What steps will reproduce the bug?

I have installed the Node.JS latest stable version. The steps to produce the Bug are as follows -

1. Run the command  `npx create-lwc-app my-app`
2. npx will start running. Then it will show the error  `? Node.js is not installed`

### How often does it reproduce? Is there a required condition?

I have done several times installing and uninstalling Node.JS to my local laptop. I followed the uninstallation steps from this StackOverflow article[Uninstall Node completely]( https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows).

**Let me tell you, I installed Node.JS in my Windows VM and it is working. So if you would ask me to reproduce it with some other laptop, I might not be.**

Things I tried. 
1. I tried to search Windows 10 registry and did not find any trace of Node.JS.

![image](https://user-images.githubusercontent.com/5306583/137591624-e685654a-e0ae-4cd6-8815-8751ee053e49.png)

2. I visited the NPM Docs website and followed the steps to update NPM. [ NPM Docs website and followed the steps to update NPM. [](https://docs.npmjs.com/try-the-latest-stable-version-of-npm)](https://docs.npmjs.com/try-the-latest-stable-version-of-npm)

But I was not successful. Please see the screenshot below.
![image](https://user-images.githubusercontent.com/5306583/137591870-6a16cae9-3ae8-43e7-9b5c-03a0ca81d714.png)

### What is the expected behavior?

The expected behavior is as below screenshot
![image](https://user-images.githubusercontent.com/5306583/137591896-f9743855-3bbc-49ee-8afc-17beb59792e3.png)

### What do you see instead?

![image](https://user-images.githubusercontent.com/5306583/137591956-fb5eec4a-6e12-4ebe-802f-8606e57382b7.png)

### Additional information

I am following the steps from the Salesforce Lightning Web Component Open Source website. [LWC OSS Dev Guide](https://lwc.dev/guide/install).

I am following the instructions of the [Build Apps with Lightning Web Components Open Source](https://trailhead.salesforce.com/en/content/learn/projects/build-your-first-app-with-lightning-web-components-open-source/create-the-application?trail_id=build-apps-lightning-web-components-open-source)

Please let me know if you require further information.

**Comment by prolayc** [comment]
Here is the output of the Node.JS Script. I am not an expert on Node. So I need your help to understand the error. 

```
D:\>node nodetest.js
Error: spawnSync node ENOENT
    at Object.spawnSync (internal/child_process.js:1077:20)
    at spawnSync (child_process.js:776:24)
    at Object.<anonymous> (D:\nodetest.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync node',
  path: 'node',
  spawnargs: [ '-v' ]
}

D:\>
```

**Comment by VoltrexMaster** [comment]
@prolayc according to the output, seems like the Node.js isn't correctly installed on your machine, where did you install Node.js from?

**Comment by prolayc** [comment]
Again sorry for the delayed response. I installed Node.JS in the following default path `C:\Program Files\nodejs`

Please see the below screenshot
![image](https://user-images.githubusercontent.com/5306583/143669038-49ad19c7-d0d9-4e05-b747-1dc25ff2a0e7.png)

**Comment by prolayc** [comment]
Here is the screenshot of my laptop path settings.

![image](https://user-images.githubusercontent.com/5306583/144025635-82c55fe7-0734-4d32-976a-14a0c215553f.png)

**Comment by VoltrexMaster** [comment]
> Again sorry for the delayed response. I installed Node.JS in the following default path `C:\Program Files\nodejs`
> 
> Please see the below screenshot ![image](https://user-images.githubusercontent.com/5306583/143669038-49ad19c7-d0d9-4e05-b747-1dc25ff2a0e7.png)

I meant like from which source did you install the Node.js runtime? From https://nodejs.org? Or from where exactly?

**Comment by prolayc** [comment]
Hello @VoltrexMaster, Are there any updates? I am looking forward to your kind help.

**Comment by VoltrexMaster** [comment]
> Hello @VoltrexMaster, Are there any updates? I am looking forward to your kind help.

Oh sorry for the late response, life things you know; if you haven't already figured this out, I'm looking forward to your answer to my previous question.

Where exactly did you download and install Node.js from?

**Comment by prolayc** [comment]
I download the Node.JS from [Node.JS](https://nodejs.org/en/).

I installed Node.JS in the following default path` C:\Program Files\nodejs`

**Comment by prolayc** [comment]
![image](https://user-images.githubusercontent.com/5306583/146125921-5934a1b4-f486-4871-8f35-f9b631be638e.png)

**Comment by prolayc** [comment]
@VoltrexMaster 

I download the Node.JS from [Official Node.JS Website](https://nodejs.org/en/).

I installed Node.JS in the following default path `C:\Program Files\nodejs`

**Comment by VoltrexMaster** [comment]
> @VoltrexMaster
> 
> I download the Node.JS from [Official Node.JS Website](https://nodejs.org/en/).
> 
> I installed Node.JS in the following default path `C:\Program Files\nodejs`

That should work, what do you see when you run `ls` in that directory?

**Comment by prolayc** [comment]
@VoltrexMaster 

I am on Windows 10 Home Edition OS.  Please find the directory listing below.

![image](https://user-images.githubusercontent.com/5306583/148693666-6e3eab34-338a-48b3-ab85-ad5e69ee76a9.png)

**Comment by VoltrexMaster** [comment]
> @VoltrexMaster
> 
> I am on Windows 10 Home Edition OS. Please find the directory listing below.
> 
> ![image](https://user-images.githubusercontent.com/5306583/148693666-6e3eab34-338a-48b3-ab85-ad5e69ee76a9.png)

Try running the EXE file by running `./node.exe` and see what happens, it should be working in the other places if the installation was done in the proper path.

**Comment by RedYetiDev** [comment]
More information was requested on this issue over 2 years ago. Closing.
