### ISSUE TITLE
installation error.. please help me please

### ISSUE THREAD

**Issue by doodoococo** [nodejs/help#358]
![dwfew](https://cloud.githubusercontent.com/assets/23336840/20113766/1eeaedb8-a635-11e6-8575-cc415b72e784.png)

 it is not working with this message.
there's no 'node.js' folder while installing node.js setup program (x64 LTS or Current).
please help me how to fix it..

**Comment by lordKnighton** [comment]
what's your OS -operating system?

**Comment by lordKnighton** [comment]
Link: https://www.youtube.com/watch?v=36e4Yv3LjE8

how to fix 1909 error

---

Let me know if this help. Either you can close or i will close this issue.
