### ISSUE TITLE
man im tired of this

### ISSUE THREAD

**Issue by potato-baby** [nodejs/help#3582]
```js
~ $ vim image2.js
~ $ npm install node-html-to-image
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-10-19T05_25_39_045Z-debug.log
```

**Comment by J-Human** [comment]
> npm ERR! ENOTEMPTY: directory not empty, rename '/data/data/com.termux/files/usr/lib/node_modules/npm' -> '/data/data/com.termux/files/usr/lib/node_modules/.npm-Ad3JtrjG'
Hmm, perhaps you can try renaming it manually and verifying if the error is true? Otherwise, deleting the node_modules folder (if it's empty or has nothing significant) then install npm globally again?

**Comment by J-Human** [comment]
Hopefully someone else could investigate
