### ISSUE TITLE
display data from mongodb

### ISSUE THREAD

**Issue by ahmadmaz** [nodejs/help#3584]
![las](https://user-images.githubusercontent.com/28919498/138137738-e2453db5-a148-4802-901a-28fad265ac80.png)
![Screenshot 2021-10-20 145307](https://user-images.githubusercontent.com/28919498/138137744-7c2c8cd0-a36a-4912-83da-340b3b58b5dd.png)
![Screenshot 2021-10-20 145325](https://user-images.githubusercontent.com/28919498/138137753-15f093e5-a10c-4213-8832-0a34e286d2ad.png)
![Screenshot 2021-10-20 145344](https://user-images.githubusercontent.com/28919498/138137760-b18fd6f1-d90c-49ef-abcc-78d0a1275614.png)
![Screenshot 2021-10-20 194302](https://user-images.githubusercontent.com/28919498/138137765-9cc2d388-6ec3-440f-bc09-ecfd1624566d.png)

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by cayank** [comment]
Hello, you need to change `docs`  to `docs.result[0]` on studentController:23

That document is defined as an object and the results are defined as an array, so we need to manipulate it.
