### ISSUE TITLE
403 Forbidden - GET https://registry.npmjs.org/@types/react-redux/-/react-redux-7.1.20.tgz

### ISSUE THREAD

**Issue by charishmanadipalli** [nodejs/help#3586]
### Details

npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/@types/react-redux/-/react-redux-7.1.20.tgz
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

### Node.js version

v16.6.1

### Operating system

Windows 10

### Scope

I'm unable to install any packages related to npm

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
