### ISSUE TITLE
router.use middleware is called twice

### ISSUE THREAD

**Issue by kri7217** [nodejs/help#3587]
### Version

12.22.3

### Platform

Darwin 3655368-6357e 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

**app.js**

`
var express = require('express');
var router = require('./router');
var app = express();
app.use("/v1",router);

app.use("*",(req,res)=>{
  return res.end("Started")
})
app.listen(3001,()=>console.log("Started on port 3001"));
`

**router.js**

`
var express = require('express');
var router = express.Router();
var axios = require('axios')

function makeApiCall(req) {
  return Promise.race([
    axios.request({
      url: "http://temp.dash.zeta.in/food.php",
      method: 'GET',
      headers: req.headers
    }),
    new Promise(resolve => {
      setTimeout(() => {
        const timeOutErrorObj = {
          errorMessage: "API cancelled. Request TimeOut",
          errorStatus: 408
        };
        return resolve(timeOutErrorObj);
      },0);
    })
  ]);
}

router.use('/food',(req, res, next) => {
  req.socket.setTimeout(0);
  console.log("Set timeout", req.res.socket.timeout)
  next();
});
router.use('/food', (req, res, next) => {
  console.log("URL request for --->", req.url);
  return makeApiCall(req).then(response => {
      const { errorStatus, errorMessage } = response;
      if (errorStatus) {
        return res.status(errorStatus).send({ message: errorMessage });
      } else {
        console.log(
          `>>>> Received response for >>>> ${response.config.url}}`
        );
        return res.send(response.data);
      }
    }).catch(error => {
      console.log("caught");
    })
})
module.exports = router;
`

Dependencies
axios 0.23v
express 4.17.1v

Please install the above dependencies.
Run node app.js
Open browser 

http://localhost:3001/v1/food

### How often does it reproduce? Is there a required condition?

For every long running request I see the request triggered multiple times.
In the browser i see single request, i saw logs twice as below.

Set timeout 0
URL request for ---> /

Set timeout 0
URL request for ---> /

### What is the expected behavior?

I expect single log and the middleware should run once.
For a single request matching middleware should execute once not twice.
Expected log

Set timeout 0
URL request for ---> /

**Comment by RedYetiDev** [comment]
If you are experiencing an issue with Express, please file it with them.
