### ISSUE TITLE
Node js conceptes

### ISSUE THREAD

**Issue by rohitbaisane** [nodejs/help#3588]
### Details

My doubt is not much technical, I want to ask like how much in depth should I go in functions or node api's in  nodejs , is it necessary to check how functions are working internally and how events are triggered behind the scene , or should I just ignore it.

### Node.js version

v14.17.1

### Operating system

windows 10

### Scope

Runtime

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
You don't really need to go that deep into the structure and code base of the Node.js runtime itself, you can just refer to the documentation as it will explain everything you know to know, but it's not a bad idea to know what goes on internally so you get implement work arounds when you're stuck or easily report bugs if you think you've found one.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
