### ISSUE TITLE
Windows docker image

### ISSUE THREAD

**Issue by psrodka-neurosys** [nodejs/help#359]
Hi guys!

Is there any plan to issue Docker Windows container with node.js based on microsoft/windowsservercore image?

Also, a little bit misleading link on the https://nodejs.org/en/download/current/ as there is link called:
**Official Node.js Docker Image**
But since there are Linux and Windows contatiners now it should be separated and labeled :)

**Comment by lordKnighton** [comment]
did you still need help with this?

**Comment by psrodka-neurosys** [comment]
Well, I have created the windows image quite easily, but the Node Download site is still misleading... :) Cheers!

**Comment by danielkhan** [comment]
Please create an issue for the website repo then https://github.com/nodejs/nodejs.org/issues

**Comment by psrodka-neurosys** [comment]
Ok :)
