### ISSUE TITLE
Garbage collector doesn't work for typed arrays

### ISSUE THREAD

**Issue by vitaly-t** [nodejs/help#3590]
### Version

14.18.1 and 16.3.0

### Platform

Windows 10

### What steps will reproduce the bug?

Compare the two code pieces below...

This one works perfectly, GC releases the array memory right away, the process sits at 10MB:

```js
let arr = new Array(100_000_000);

for(const a of arr) {
}

console.log('releasing...');
arr = null;

setTimeout(() => {
}, 1_000_000);
```

And this one never releases the array memory, the process sits at 108MB:

```js
let arr = new Uint8Array(100_000_000);

for(const a of arr) {
}

console.log('releasing...');
arr = null;

setTimeout(() => {
}, 1_000_000);
```

### How often does it reproduce? Is there a required condition?

100%, all the time

### What is the expected behavior?

GC is supposed to collect the unused array memory, which would go down to 10MB, consistent with regular arrays.

### What do you see instead?

The process sits at its maximum memory usage of 108MB permanently.

### Additional Information

Increasing array to `1_000_000_000` sets process memory at 1GB permanently, it is never released.

**Comment by RaisinTen** [comment]
@vitaly-t did you try reproducing this issue with d8? If this issue still exists there, maybe you could try to report this to V8?

**Comment by vitaly-t** [comment]
@RaisinTen I've never used d8.

**Comment by RaisinTen** [comment]
For more context, you can refer to https://v8.dev/docs/d8 to get yourself a build of d8. If you are able to reproduce your issue there, it would probably mean that your issue belongs in https://bugs.chromium.org/p/v8/issues/list!
