### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by RosaMoran** [nodejs/help#3591]
### Details

i have this problem when i'm trying to create a new file, i'm using postman to run my web app and the error is like this `ERR_INVALID_ARG_TYPE`

### Node.js version

Not applicable.

### Example code

```js
app.post('/files/:name', async (req, res) => {
  const path = `./files/${req.params.name}.txt`;
  if (fs.existsSync(path)) {
    res
      .status(409)
      .send({ ok: false, message: 'file with that name already exists!' });
    return;
  }
  try {
    await write(path, req.body);
    res.send({ ok: true, message: `file ${path} created successfully` });
  } catch (error) {
    res
      .status(500)
      .send({ ok: false, message: 'error writing file', err: error });
  }
});
```

### Operating system

linux

### Scope

code

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
The `ERR_INVALID_ARG_TYPE` is just the error type, can you show us what error you're exactly getting?

**Comment by gireeshpunathil** [comment]
ping @RosaMoran

**Comment by shannonenz** [comment]
app.post('/files/:name', async (req, res) => {
  const path = `./files/${req.params.name}.txt`;
  if (fs.existsSync(path)) {
    res
      .status(409)
      .send({ ok: false, message: 'file with that name already exists!' });
    return;
  }
  try {
    await write(path, req.body);
    res.send({ ok: true, message: `file ${path} created successfully` });
  } catch (error) {
    res
      .status(500)
      .send({ ok: false, message: 'error writing file', err: error });
  }
});
