### ISSUE TITLE
Image is getting generated from an raw pixel data in node js but not opening

### ISSUE THREAD

**Issue by NonlinearNimesh** [nodejs/help#3592]
### Details

Hi, I am trying to get JPEG/PNG image from a Dicom image using Dicom parser.

Initially i am reading the Dicom file and converting it into raw pixel data 

```
var dicom = require('dicom-parser');
var fs = require('fs');
var jpeg = require('jpeg-js');

var dicomFileAsBuffer = fs.readFileSync('/Users/nimesh/Downloads/Work/1_Mine/TBClassification3.7/TBClassifications/test/1.01.868.8289.50550.763722.6242389.2076076331839821530808901804551332385943463553544.dcm');

var dataSet = dicom.parseDicom(dicomFileAsBuffer);

var rawImageData = new Uint8Array(dataSet.byteArray.buffer,
                                dataSet.elements.x00280004.dataOffset);
								//dataSet.elements.x00280004.length);
console.log(rawImageData)
```
Next after generating raw pixel data, i am trying to save it into an image file and for that i am using writefileSync.
```
let data = rawImageData
data = Buffer.from(data);
fs.writeFileSync(`test.png`, data, err => {
      if (err) {
         console.log(err);
      } else {
         console.log('File created successfully!');
      }
}); 
```

And, the image file is also generated but it is not opening, seems like the generated image is corrupt.

Can anyone help me on this 

Thanks.

### Node.js version

npm: '7.19.1',
  node: '16.5.0',
  v8: '9.1.269.38-node.20',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'

### Operating system

Mac OS Big Sur

### Scope

The problem I am facing is, I am able to generate an image file from the raw pixel data using writeFileSync but when I am trying to open an image it shows the image may be damaged.

### Module and version

Not applicable.

**Comment by Dev-Paulo-Henrique** [comment]
## Installation
```bash
npm install dcmjs
```
## Usage
```
const dcmjs = require("dcmjs");
const fs = require("fs");

let arrayBuffer = fs.readFileSync("C:\\tmp\\attachment.file.9a386d4b4506001a.646374303035372e64636d.dcm").buffer;

let DicomDict = dcmjs.data.DicomMessage.readFile(arrayBuffer);

DicomDict.upsertTag("x00100010", "PN", "JAYKUMAR THAKER");

let new_file_WriterBuffer = DicomDict.write();

fs.writeFileSync("C:\\tmp\\attachment_test.dcm", new Buffer.from(new_file_WriterBuffer), , err => {
    if (err) {
       console.log(err);
    } else {
       console.log('File created successfully!');
    }
});
```
