### ISSUE TITLE
Why no Let's Encrypt certificate is included in NodeJS root cert list?

### ISSUE THREAD

**Issue by ptcalex** [nodejs/help#3593]
### Details

https://github.com/nodejs/node/blob/master/src/node_root_certs.h does not include any Let's Encrypt certificate.
Is it going to be added or is there a specific reason why it hasn't yet? 

### Node.js version

Not applicable.

### Operating system

Any

### Scope

meta

### Module and version

Not applicable.

**Comment by RaisinTen** [comment]
Because we use the certificates from Mozilla, more details here -> https://github.com/nodejs/node/blob/eb65871ab4ec6e73bf8febb7bd373c3f22857988/doc/guides/maintaining-root-certs.md

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
