### ISSUE TITLE
OSSL_EVP is not supported

### ISSUE THREAD

**Issue by yalattas** [nodejs/help#3595]
## Environment

* **Platform**: Linux
* **Docker Version**:
* GitLab runner
* **Node.js Version**:
* ^16
* **Image Tag**:
Using docker image sha256:7220633f01cdab3c20b7ded7f04e43e5b1ca95a5c5376a27e8fe41793d2dba6f for node:latest with digest node@sha256:a562ce5da0b5e43107b4acbc5d8845129370f11bcb81c795601dc3d6004d6158

## Expected Behavior
npm run build:prod to build a production dist folder to deploy it

Our CI/CD on GitLab used to work when using node:latest images, suddenly stopped working even on healthy code that has been built before. Here is error results
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/builds/path/to/project/node_modules/webpack/lib/util/createHash.js:135:53)
...
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

## Current Behavior
Failure to build a production build. Currently resolved by downgrading node to use node:16.13 docker image

## Possible Solution
Currently resolved by downgrading node to use node:16.13 docker image

## Steps to Reproduce
build React application using latest image, make sure that React require OSSL_EVP

**Comment by tniessen** [comment]
Node.js 17 uses OpenSSL 3, which disables some legacy algorithms by default. You should avoid using such algorithms because they are considered insecure, but if you really need to keep using them, you can use the workaround from https://github.com/nodejs/node/pull/40478.
