### ISSUE TITLE
RequestReply patter with kafkajs

### ISSUE THREAD

**Issue by artemitcraft** [nodejs/help#3598]
### Details

Hi, I know it's not completely related to the subject but I have an issue and cannot resolve it by myself so asking for help. So I am going to implement sync request-reply pattern based on kafka. here is a short prototype: [gist link](https://gist.github.com/artemitcraft/5f04fea00fdee1f33078eee31aa5ee32)

I am faced with the problem on the second iteration (start), eventEmitter uses old object and promise cannot be resolved. Will be grateful for any thoughts.

### Node.js version

v12.18.2

### Operating system

Windows 10

### Scope

npm install kafkajs

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Please file an issue with Kafka, rather than with Node.js
