### ISSUE TITLE
Delete of Property in Object leads to Memory duplication

### ISSUE THREAD

**Issue by soccermax** [nodejs/help#3599]
### Version

v14.18.1

### Platform

Darwin C02FLADZMD6M 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

I observed that deleting a property of an object leads to a huge amount of memory allocation which is not cleaned for the garbage collector. The strange thing here is that it seems that during the delete the object is copied and after that, the given property is deleted. Even using `global.gc()` is not triggering the free up of the memory. 
I attached a minimal executable code snippet which shows the memory allocation of the steps:

```js
global.gc();
console.log(process.memoryUsage().heapUsed / byteToMegaByte); // --> 2.01956
const testArray = [];
for (let i = 0; i < 10000; i++) {
  testArray.push({
    Key01: null,
    Key02: null,
    Key03: null,
    Key04: "76bb0d60-13c8-4ccc-1700-06025792f14d",
    Key05: "34fadfb5-92f9-442f-981f-c3f2481d7384",
    Key06: "9ab7228f-d7e6-4fb8-9cee-35d7968fd90d",
    Key07: "f1f424d6-62b9-4e4a-baad-6aa37ddcec66",
    Key08: "d66ead84-9400-4e6b-871f-ea76b4b40016",
    Key09: null,
    Key10: null,
    Key11: null,
    Key12: "A",
    Key13: null,
    Key14: "A",
    Key15: false,
    Key16: true,
    Key17: true,
    Key18: "2021-11-02 16:58:25",
    Key19: "",
    Key20: null,
  });
}
console.log(process.memoryUsage().heapUsed / byteToMegaByte); // --> 4.345456

for (let object of testArray) {
  delete object["Key13"];
}


console.log(process.memoryUsage().heapUsed / byteToMegaByte); // --> 18.939704
global.gc();
console.log(process.memoryUsage().heapUsed / byteToMegaByte); // --> 18.447144

setTimeout(() => {
  console.log(testArray[0]);
  console.log(process.memoryUsage().heapUsed / byteToMegaByte); // --> 18.949792
}, 10000);

``` 

### What is the expected behavior?

The expected behaviour would be that the allocated memory should not change or even slightly decrease by the delete. Even if for the delete of an property a copy is required the memory should be freed up afterwards. afterward

### What do you see instead?

See the comments in the code snipped with the allocated memory

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
