### ISSUE TITLE
how to set the timezone for node.js app

### ISSUE THREAD

**Issue by Crystal4545** [nodejs/help#36]
Hi team,
When I debug a node.js app, I'd like the timestamp of the log to be set to a certain timezone.  How can I realize that?  Can anyone here shed some light on how to set the timezone for node.js app?

**Comment by bnoordhuis** [comment]
If you're deploying on UNIX machines, setting the TZ environment variable before starting your application should do it.

**Comment by srl295** [comment]
Yes, the timezone would be set/detected from the underlying OS. On Windows it would be affected by the control panel /configuration settings for date and time.

**Comment by Crystal4545** [comment]
@srl295 @bnoordhuis  Thank you for your suggestions. 
I was once wondering whether there is any runtime environment variables that we can configure to realize that.  If no such thing,  then okay we can just modify the OS settings. Again. thanks!
