### ISSUE TITLE
Node.js version v17.0.1 detected. Odd numbered Node.js versions will not enter LTS status and should not be used for production. For

### ISSUE THREAD

**Issue by rpiadam** [nodejs/help#3602]
ng run app:build exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
adamhockley@Adams-MBP UPLoveApP % apt-get install ng
zsh: command not found: apt-get
adamhockley@Adams-MBP UPLoveApP % ionic cap build ios
> ng run app:build
Node.js version v17.0.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
✔ Browser application bundle generation complete.

Error: node_modules/ionicons/dist/types/components.d.ts:66:15 - error TS2320: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'IonIcon' and 'HTMLStencilElement'.
  Named property 'ariaHidden' of types 'IonIcon' and 'HTMLStencilElement' are not identical.

66     interface HTMLIonIconElement extends Components.IonIcon, HTMLStencilElement {
                 ~~~~~~~~~~~~~~~~~~


Error: node_modules/ionicons/dist/types/components.d.ts:66:15 - error TS2320: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'IonIcon' and 'HTMLStencilElement'.
  Named property 'ariaLabel' of types 'IonIcon' and 'HTMLStencilElement' are not identical.

66     interface HTMLIonIconElement extends Components.IonIcon, HTMLStencilElement {
                 ~~~~~~~~~~~~~~~~~~

Error: node_modules/typescript/lib/lib.dom.d.ts:4632:101 - error TS2344: Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Element'.
  Type 'HTMLElement | HTMLImageElement | HTMLVideoElement | HTMLCanvasElement | HTMLAnchorElement | ... 151 more ... | HTMLIonVirtualScrollElement' is not assignable to type 'Element'.
    Type 'HTMLIonIconElement' is not assignable to type 'Element'.
      Property 'ariaHidden' is optional in type 'HTMLIonIconElement' but required in type 'Element'.

4632     getElementsByTagName<K extends keyof HTMLElementTagNameMap>(qualifiedName: K): HTMLCollectionOf<HTMLElementTagNameMap[K]>;
                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/typescript/lib/lib.dom.d.ts:4953:101 - error TS2344: Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Element'.
  Type 'HTMLElement | HTMLImageElement | HTMLVideoElement | HTMLCanvasElement | HTMLAnchorElement | ... 151 more ... | HTMLIonVirtualScrollElement' is not assignable to type 'Element'.

4953     getElementsByTagName<K extends keyof HTMLElementTagNameMap>(qualifiedName: K): HTMLCollectionOf<HTMLElementTagNameMap[K]>;
                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~

[ERROR] An error occurred while running subprocess ng.
        
        ng run app:build exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
adamhockley@Adams-MBP UPLoveApP %

**Comment by mani-1986** [comment]
> ng run app:build exited with exit code 1.
> 
> ```
>     Re-running this command with the --verbose flag may provide more information.
> ```
> 
> adamhockley@Adams-MBP UPLoveApP % apt-get install ng zsh: command not found: apt-get adamhockley@Adams-MBP UPLoveApP % ionic cap build ios
> 
> > ng run app:build
> > Node.js version v17.0.1 detected.
> > Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
> > ✔ Browser application bundle generation complete.
> 
> Error: node_modules/ionicons/dist/types/components.d.ts:66:15 - error TS2320: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'IonIcon' and 'HTMLStencilElement'. Named property 'ariaHidden' of types 'IonIcon' and 'HTMLStencilElement' are not identical.
> 
> 66 interface HTMLIonIconElement extends Components.IonIcon, HTMLStencilElement { ~~~~~~~~~~~~~~~~~~
> 
> Error: node_modules/ionicons/dist/types/components.d.ts:66:15 - error TS2320: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'IonIcon' and 'HTMLStencilElement'. Named property 'ariaLabel' of types 'IonIcon' and 'HTMLStencilElement' are not identical.
> 
> 66 interface HTMLIonIconElement extends Components.IonIcon, HTMLStencilElement { ~~~~~~~~~~~~~~~~~~
> 
> Error: node_modules/typescript/lib/lib.dom.d.ts:4632:101 - error TS2344: Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Element'. Type 'HTMLElement | HTMLImageElement | HTMLVideoElement | HTMLCanvasElement | HTMLAnchorElement | ... 151 more ... | HTMLIonVirtualScrollElement' is not assignable to type 'Element'. Type 'HTMLIonIconElement' is not assignable to type 'Element'. Property 'ariaHidden' is optional in type 'HTMLIonIconElement' but required in type 'Element'.
> 
> 4632 getElementsByTagName(qualifiedName: K): HTMLCollectionOf<HTMLElementTagNameMap[K]>; ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Error: node_modules/typescript/lib/lib.dom.d.ts:4953:101 - error TS2344: Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Element'. Type 'HTMLElement | HTMLImageElement | HTMLVideoElement | HTMLCanvasElement | HTMLAnchorElement | ... 151 more ... | HTMLIonVirtualScrollElement' is not assignable to type 'Element'.
> 
> 4953 getElementsByTagName(qualifiedName: K): HTMLCollectionOf<HTMLElementTagNameMap[K]>; ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> [ERROR] An error occurred while running subprocess ng.
> 
> ```
>     ng run app:build exited with exit code 1.
>     
>     Re-running this command with the --verbose flag may provide more information.
> ```
> 
> adamhockley@Adams-MBP UPLoveApP %

I have the same issue while trying to create a docker image for production.

**Comment by mhdawson** [comment]
I believe this would be a message from ng run.  It is correct that Node.js 17.x will never become LTS and it sounds like ng run does a check and recommends agsinst using it.  

I think you should open an issue in the angular repos instead of the Node.js repo.

**Comment by GuitarHero1969** [comment]
I get the following when typing ng serve -o into my vs code terminal to run an Angular app 

Node.js version v17.1.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
- Generating browser application bundles...(node:17652) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
\ Generating browser application bundles (phase: building)...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\loader-runner\lib\LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:48:13)
    at processResource (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\webpack\lib\Compilation.js:739:10)
    at C:\Users\\Desktop\Software Development\Angular\recipe-project-ngrx\node_modules\webpack\lib\Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by yaron-shamul** [comment]
I'm getting this while trying to run a new nuxt project

**Comment by GuitarHero1969** [comment]
I loaded the previous even numbered version and all is ok.

**Comment by asimazam343** [comment]
> 

Same still looking for solution

**Comment by asimazam343** [comment]
> I get this when running ng update after I updated my node version to 17.9.0 ![grafik](https://user-images.githubusercontent.com/55798556/163207414-be4cd6f9-5b4a-4d91-8484-d2b94e33f119.png)

I downloaded the even 16 ver and now all working good

**Comment by mani-1986** [comment]
@asimazam343 According to your screenshot I see that it couldn't find your package.json file in that directory.
