### ISSUE TITLE
node-serialport

### ISSUE THREAD

**Issue by Rezcue** [nodejs/help#3603]
### Details

I cant install node-red-node-serialport on windows 10.

You need to install the latest version of Visual Studio
including the "Desktop development with C++" workload.  --> I got the Visual Studio Community 2022 with  Dekstop C++

Can someone help me out here pls ;)?

### Node.js version

node --version && npm --version
v14.17.5
6.14.14

### Example code

`> @serialport/bindings@9.2.5 install C:\Users\Rezcue\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.17.5 runtime=node arch=x64 libc= platform=win32)

C:\Users\Rezcue\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:397:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rezcue\node_modules\@serialport\bindings
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Rezcue\package.json'
npm WARN Rezcue No description
npm WARN Rezcue No repository field.
npm WARN Rezcue No README data
npm WARN Rezcue No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@9.2.5 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@9.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rezcue\AppData\Roaming\npm-cache\_logs\2021-11-11T18_09_21_175Z-debug.log`
`

### Operating system

Windows 10

### Scope

Installation

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
@Rezcue - instead of running in a normal command prompt, can you use the command prompt that comes with the VS installation? that will make sure the variables are set necessary for the VS execution environment. Other alternative is to explicitly run `vsvars.bat` or similar that comes as part of the VS installation (don't remember the exact name and location of the file) on your prompt, prior to the build.

Hope this helps.

**Comment by Rezcue** [comment]
Hello, 

i made it work. 

"On Windows

Install the current version of Python from the Microsoft Store package.

Install tools and configuration manually:

    Install Visual C++ Build Environment: Visual Studio Build Tools (using "Visual C++ build tools" workload) or Visual Studio Community (using the "Desktop development with C++" workload)
    Launch cmd, npm config set msvs_version 2017

If the above steps didn't work for you, please visit Microsoft's Node.js Guidelines for Windows for additional tips.

To target native ARM64 Node.js on Windows 10 on ARM, add the components "Visual C++ compilers and libraries for ARM64" and "Visual C++ ATL for ARM64"." 

1. https://visualstudio.microsoft.com/de/thank-you-downloading-visual-studio/?sku=Community
**2. npm config set msvs_version 2019** 


When i had the C++ 2022 installed i tried **2. npm config set msvs_version 2022* but it did not work out.

After several attempts

1. https://visualstudio.microsoft.com/de/thank-you-downloading-visual-studio/?sku=Community  <--- VS. 2019
**2. npm config set msvs_version 2019** 

Did the trick for me.


Thanks

**Comment by VoltrexMaster** [comment]
Seems like this issue is resolved.
