### ISSUE TITLE
 Hangs on adding 48 million keys (properties) to an object.

### ISSUE THREAD

**Issue by manking99** [nodejs/help#3604]
### Details

Hey!
When trying to add 48 million keys to an object
const asMap = {};
asMap [str] = item;

the process freezes and stops responding to commands. Is it possible to remove this limit (to work with billions)? What's the fastest way to work with associative arrays in javascript (when have a lot of RAM)?

### Node.js version

11.14

### Example code

```
let cicles = 0;
const asMap = {};

result.map((item) => {
    const k_ = Object.keys(item);
    let str = '';

    for (let i = 0; i < k_.length; i++) {
      str += `${item[k_[i]]}_`;
      cicles++;
    }
  
    asMap[str] = item;
    if(cicles % 100000 === 0){
      console.log('result3 map cicles='+cicles);
    }
  });
```

### Operating system

Docker 
FROM node:11.14.0

### Scope

runtime

### Module and version

Not applicable.

**Comment by tniessen** [comment]
> Is it possible to remove this limit (to work with billions)?

Billions of properties would take many, many gigabytes of memory. And even if memory wasn't an issue, you'd quickly run into performance issues. You can try and see if `Map` is any faster for a large number of key value pairs, but in general, you might want to consider more advanced data structures for millions to billions of properties.
