### ISSUE TITLE
How to Uninstall older version of Node JS installed in Ubuntu

### ISSUE THREAD

**Issue by prakhyatik** [nodejs/help#3605]
### Details

How to uninstall remove older version of node js and install newer version. 

Need some help regarding this.

### Node.js version

10.19.0

### Operating system

Ubuntu / LInux

### Scope

Not applicable

### Module and version

Not applicable.

**Comment by shreedharhegde99** [comment]
``` 
run node command in terminal it will show you the current node version installed
$ node
then again run the below command to get the desired version of node.js(latest version is 16.13.0)
$ nvm install 16.13.0
```

**Comment by SebasQuirogaUCP** [comment]
@prakhyatik did it solve the problem?

**Comment by SebasQuirogaUCP** [comment]
The NVM stands for Node Version Manager, it will let you choose the proper Node version for you, if this solves the problem let us now, in case you  need to remove it, try `sudo apt-get remove nodejs`

**Comment by prakhyatik** [comment]
@SebasQuirogaUCP  Solved ! Thanks for your help everyone :)
