### ISSUE TITLE
node: bad option: -version

### ISSUE THREAD

**Issue by MinhVuAlinco** [nodejs/help#3607]
### Details

Hi all, I install node js, and I get this error:

C:\Users\MinhVu>node -version
node: bad option: -version

So I can't create new project react, nextjs in VS code.

### Node.js version

I in stall node 16.13.0 and lastest version.

### Operating system

WIN 10 with Ryzen 7-4800H

### Scope

I can't run any thing with NodeJs

### Module and version

Not applicable.

**Comment by Naman23-coder** [comment]
try `node --version`

**Comment by YonatanZewude** [comment]
I think you wrote node --virsion in your terminal. Try withe  node --version

**Comment by rajroshan0** [comment]
thank you it worked
node --version

**Comment by Saikatray1** [comment]
> I think you wrote node --virsion in your terminal. Try withe node --version

Yes.I typed node --verson.But it have node --version.(typing mistake)

**Comment by ACEmmanuel** [comment]
node --version worked but node --v doesn't, why?

**Comment by Monshem** [comment]
node -version it's return bad option, But npm -version it's worked, why?
