### ISSUE TITLE
uninstall error

### ISSUE THREAD

**Issue by sajjirey** [nodejs/help#3609]
### Details

![image](https://user-images.githubusercontent.com/87379513/141828622-c61b8760-214b-45c6-a166-5b7401b49ea2.png)
It shows me this when I try to delete it

### Node.js version

17.1.0

### Operating system

windows 10

### Scope

uninstallation

### Module and version

Not applicable.

**Comment by Kotaviy** [comment]
I have the same problem (( If you solved this problem, please tell me how you did it
