### ISSUE TITLE
http.IncomingMessage 'error' event

### ISSUE THREAD

**Issue by tadjik1** [nodejs/help#361]
Hi there,

please help me to understand when 'error' event can be emitted by IncomingMessage object created by http.Server.

I've read documentation and source code (especially [this](https://github.com/nodejs/node/blob/master/lib/_http_server.js#L358) place) and noticed that 'error' event can never happen. Is it a right assumption?
At the same time I've read [this](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/) article on nodejs official website and it was specified by required to handle this event on request object.

Also I've tried to write a request with wrong behaviour and with possible error, but I'm not sure that it's "deep" enough. However, this simple code also emits error on IncomingMessage (create by http.request), but not on node.js side:

```javascript
const assert = require('assert');
const http = require('http');
const { Server } = require('http');

const server = new Server((request, response) => {
  request.pipe(response);
});;

describe('server tests', () => {
  before(() => server.listen(3333));
  after(() => server.close());

  it('should handle error', done => {
    const options = {
      port: 3333
    };

    const req = http.request(options);

    req.on('error', err => {
      assert.equal(err.message, 'socket hang up');

      done();
    });

    req.on('response', response => {
      response.on('data', () => {
        response.socket.emit('error');
      });
    });

    req.write('content');
  });
});
```

the same ticket on nodejs repo nodejs/node#9592

**Comment by lordKnighton** [comment]
Sorry for late response
are you still having problems?

**Comment by tadjik1** [comment]
@lordKnighton sorry, didn't see your comment. yes - my question is actual and both tickets still have no answers.

**Comment by lordKnighton** [comment]
Actually ticket https://github.com/nodejs/node/issues/9592 has activity.

**Comment by Infirmnick** [comment]
Catch this https://nodeer.space/questions/encountering-a-socket-hangup-issue-when-incorporating-assert-and-http-modules-in-nodejs explanation
