### ISSUE TITLE
node is spitting an error and I have no idea what it might be! I have a job to deliver and if this continues I will have to pay fines

### ISSUE THREAD

**Issue by Theryston** [nodejs/help#3614]
### Version

v16.13.0

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### Subsystem

got

### What steps will reproduce the bug?

the following error appears on the console:
 `
Fatal error in , line 0
Fatal JavaScript invalid size error 169220804
FailureMessage Object: 00000088B66FE590
 1: 00007FF772A0013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
 2: 00007FF77291D3CF v8::CFunctionInfo::HasOptions+7055
 3: 00007FF7735F3202 V8_Fatal+162
 4: 00007FF77317CC85 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArray+101
 5: 00007FF773026483 v8::internal::FeedbackNexus::ic_state+62771
 6: 00007FF77303CFE0 v8::Message::GetIsolate+15840
 7: 00007FF772EB1731 v8::internal::CompilationCache::IsEnabledScriptAndEval+26849
 8: 00007FF77334F3E1 v8::internal::SetupIsolateDelegate::SetupHeap+494417
 9: 00000223EC3A5462
`

### How often does it reproduce? Is there a required condition?

after uploading 2 large files to an api using stream

**Comment by gireeshpunathil** [comment]
> after uploading 2 large files to an api using stream

can you share the code or snippet that caused this issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
