### ISSUE TITLE
Node 16.13 with FIPS (OpenSSL 3.0.0)

### ISSUE THREAD

**Issue by djgruja** [nodejs/help#3616]
### Details

Hello, 

Has anyone managed to make this work, following the instructions from Node 16.13 BUILDING.md I managed to compile but when I run:

 node --enable-fips -p 'crypto.getFips()'

I get:

```
OpenSSL error when trying to enable FIPS:

00801AB2C97F0000:error:1C8000D5:Provider routines:SELF_TEST_post:missing config data:providers/fips/self_test.c:289:

00801AB2C97F0000:error:1C8000E0:Provider routines:ossl_set_error_state:fips module entering error state:providers/fips/self_test.c:387:

00801AB2C97F0000:error:1C8000D8:Provider routines:OSSL_provider_init_int:self test post failure:providers/fips/fipsprov.c:706:

00801AB2C97F0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto/provider_core.c:903:name=fips
```

There is a couple of mentions of this issue online, but none is resolved.

Thanks

### Node.js version

16.13.0

### Operating system

Ubuntu 20.04

### Scope

runtime, other

### Module and version

Not applicable.

**Comment by mhdawson** [comment]
I assume
1) You are compiling to link dynamically against openssl
2) You have an openssl wtih a FIPs enabled provider ?

I would guess from the error message that the fips provider is not being found?

I had thought we had a job which tested dynamically linking with OpenSSL 3, but I'm not sure we had enabled the fips provider. The only job I can find now is https://ci.nodejs.org/view/All/job/node-test-commit-linux-fips but that does not seem to have run for a while.

@richardlau is there another job that I did not find?

**Comment by richardlau** [comment]
@mhdawson we have a job that dynamically links OpenSSL 3 in https://ci.nodejs.org/job/node-test-commit-linux-containered/ but we don't currently enable the FIPS provider.

**Comment by djgruja** [comment]
Thanks for the reply.

**1.** I am compiling to link dynamically with OpenSSL, using the steps provided in BUILDING.md, but slightly altered, cause the path to lib folder is different.

./configure \
  --shared-openssl \
  --shared-openssl-libpath=/usr/local/openssl3/lib64 \
  --shared-openssl-includes=/usr/local/openssl3/include \
  --shared-openssl-libname=crypto,ssl \
  --openssl-is-fips
  
export LD_LIBRARY_PATH=/usr/local/openssl3/lib64

make -j8

The change is that the lib folder in OpenSSL 3 is actually lib64

**2.** I have built OpenSSL 3 also by  the steps provided in BUILDING.md

./config --prefix=/usr/local/openssl3 shared enable-fips linux-x86_64

make -j4
sudo make install
sudo make install_ssldirs
sudo make install_fips

I tried Node.js 17.1 with static linking and the command:  **node --enable-fips -p 'crypto.getFips()'** returns 1.
Does that mean that in version 17 the FIPS module is working as it should?
Is it safe to say that version 17 is safe for production use with FIPS?

**Comment by djgruja** [comment]
One more thing, I built node 17 with FIPS with static linking, and its working.

Since I cant find openssl.cnf in install dir, how can I make node to always run with FIPS enabled?

**Comment by mhdawson** [comment]
> 1. I am compiling to link dynamically with OpenSSL, using the steps provided in BUILDING.md, but slightly altered, cause the path to lib folder is different.

I've not looked at the providers in detail, but my guess is that an openssl 3.0 that comes with an OS as a shared library will quite likely not include providers like the FIPs one by default and that is why you see that failure.  

> Is it safe to say that version 17 is safe for production use with FIPS? 
I'm not an expert but there is no "simple" answer to that from my understanding. There are a number of rules that must be followed to meet the FIPs requirements and simply compiling the code without being aware/following those rules is unlikely to get you something you can claim as FIPS.  You'll need to become familiar enough with the rules to be able to make the case that what you've done and how meets the requirements for FIPS that you/customer needs.

Further, this announce says that the module has been submitted for validation - https://www.openssl.org/blog/blog/2021/09/22/OpenSSL3-fips-submission/ but I don't believe it is expected to complete the validation until Q3-Q4 2022. Until that completes I don't think there is a way to claim openssl from the code included in Node.js.

@richardlau thanks for pointing to that job.

> Since I cant find openssl.cnf in install dir, how can I make node to always run with FIPS enabled?

In section 7.2 in https://wiki.openssl.org/index.php/OpenSSL_3.0 it would seem to say you an set the directory that it is in by setting OPENSSL_CONF.  If that works then I would try to find what the default is for OpenSSL 3.0 and try that. Section7.1 in the same doc has some discussion of finding the path which may vary by platform.

**Comment by djgruja** [comment]
Again, thanks for the reply.

I have another problem her, since when I do: 

make install

Node gets installed in /usr/local, but it still depends on /out/Release folder, openssl.cnf and fipsmodule.cnf are still in that folder, and if I try to copy openssl.cnf somewhere else and export the path with OPENSSL_CONF env var, the node still tries to load the cnf from Release folder?

How to make install without depending on Release folder?

**Comment by mhdawson** [comment]
@djgruja do the Node.js 17.x binaries from https://nodejs.org/en/download/ try to look for /out/Release?  If so that is likely a bug that we'd need to raise as an issue.

**Comment by djgruja** [comment]
The binaries are from download page, I made it work by doing dynamic linking with OpenSSL.

So maybe there is a bug when using static linking?

When I build OpenSSL 3 on my own and than install it with:

make install
make install_ssldirs
make install_fips

and then build Node against that, than Node is not depending on out/Release folder.

Just to mention again, its Node v17, I couldn't make v16 work.
