### ISSUE TITLE
Environment variables dropping out

### ISSUE THREAD

**Issue by hardyb** [nodejs/help#3618]
### Details

In light of some anecdotally observed issues with environment variables, I decided to do a proper check.

I have some code that checks the existence of about the 25 existing environment variables in the .env using process.env.MYVAR etc every 5 minutes.

I also check and record start ups so effectively (re)starts.

The majority of the time every 5 minutes all of the environment variables are reported as present, but very occasionally hours between restarts while the app is running the code suddenly finds that a subset of the variables are missing / not set, i.e some of the process.env.MYVAR are undefined.

I am trying to analyse what could possibly cause this and if there is anything I can do to prevent it or should i perhaps trigger restart of the app, since generally on restart all the variables are present again.

Anyone any thoughts how I should go about investigating the cause of this?

Running off Linux managed by pm2

### Node.js version

14.18.1

### Example code

Snippet:

const envVars = {
    EXAMPLE: process.env.EXAMPLE,
    ...
  };

  try {
    const startMS = Date.now();

    let numEnvVarFailures = 0;
    for (const envVar in envVars) {
      if (!envVars[envVar] || !envVars[envVar].length) {
        const dbOK = await logHealth({
          ...context,
          type: "Environment variables",
          status: "failure",
          detail: `Critical environment variable ${envVar} not set!`
        });
        if (!dbOK) {
          return false;
        }
        numEnvVarFailures++;
      }
    }

### Operating system

Red Hat 7.9

### Scope

runtime

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
@hardyb - what would be the rationale behind using:

```js
!envVars[envVar].length
``` 
?

**Comment by hardyb** [comment]
Tbf the code is actually taken from a general check to ensure that even if the user has set the env var they have set it to something, but the point is which ever the failure it occurs out if the blue hours between restarts and I am trying to understand what might cause this

**Comment by gireeshpunathil** [comment]
anomalies that occur after a long time since the start can be attributed to wrong optimizations by JIT compiler. We haven't seen a lot of those, but logically that can explain it, as the code optimization occurs after the code has run many times and saturates.

`node --opt=false app.js`  may be an option to isolte the issue. If the issue resolves, then we might need further steps to identify the faulty methods.

**Comment by hardyb** [comment]
Thank you.  Appreciate your input.
When you say "if the issue resolves". Do you mean as a result of --opt or on its own.

I haven't noticed a clear relationship between the occurrence of the subset of lost env vars and the number of hours running.

I guess in the short term, restarting when it occurs will be a solution.

**Comment by gireeshpunathil** [comment]
> When you say "if the issue resolves". Do you mean as a result of --opt or on its own.

as a result of the option, yes.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.

**Comment by hardyb** [comment]
Thank you so much @gireeshpunathil - sorry for the late follow-up.  Can you tell me the impact of  --opt=false ?  Mainly performance?  To what extent do you think performance would be impacted?

If we use this option and wait a considerable length of time and never see lost environment variables again, what steps / instrumentation may be necessary to identify the faulty methods?

In the initial question I mentioned "...Running off Linux managed by pm2..." - is this likely to be a factor?  For example...

//app-in-question is at id 2
pm2 env 2|grep -i UMBRELLA
UMBRELLA_AUTH_SECRET_KEY: *****************************
pm2 delete app-in-question
pm2 start ecosystem.config.js
//app-in-question is now at id 5
pm2 env 5|grep -i UMBRELLA
UMBRELLA_LOG_LEVEL: silly
UMBRELLA_LOG_BASE_DIR: /bla/bla//logs/
UMBRELLA_ENVIRONMENT: Prod
UMBRELLA_SECRET_KEY: *****************************

This is clearly something awkward to investigate, with no clearly defined trigger, while we investigate can you suggest any kind of work around?

For example, what if we copied the environment variables into global constants at start up and then accessed these instead?

const myenvvars = {
    BLA1: `${process.env.BLA1}`, // endevour to create a brand new string
    BLA2: `${process.env.BLA2}`,
    BLA3: `${process.env.BLA3}`
}

I have seen process.env.BLA1 unexpectedly evaluate to undefined, but never at startup and I have never seen a global const suddenly loose it's value.

What do you think?

Many thanks again for your input.

Andrew

**Comment by hardyb** [comment]
@gireeshpunathil - so sorry to trouble you - I have added comment above, you suggest above "...pls reopen if there is anything outstanding...", but I understand '_you cannot re-open your own issues if a repo collaborator closed them_' - could you possibly reopen this issue for me - many thanks indeed,

Andrew

**Comment by gireeshpunathil** [comment]
@hardyb - yes, the only implication to the option is performance. The extent of performance loss actually depends on the extent to optimisation that was possible in your app, and is completely unique to each application. However, it can be substantial.

you can pass `--trace-opt-verbose` option in the command line, that may show up an entry for the faulty method `very close` to the fault occurrence. Then we can exclude that method alone from being optimised and see if things go away.

Here is an example usage:

```
#node --trace-opt-verbose .rec.js
[not yet optimizing , not enough ticks: 1/3 and ICs changed]
[not yet optimizing , not enough ticks: 2/3 and  too large for small function optimization: 113/81]
[marking 0x04fe908029d1 <JSFunction (sfi = 0x4feb276b8e9)> for optimized recompilation, reason: hot and stable]
[compiling method 0x04fe908029d1 <JSFunction (sfi = 0x4feb276b8e9)> (target TURBOFAN) using TurboFan OSR]
[optimizing 0x04fe908029d1 <JSFunction (sfi = 0x4feb276b8e9)> (target TURBOFAN) - took 3.639, 39.304, 0.079 ms]
```

**Comment by gireeshpunathil** [comment]
more elaborative example:

```
#node --trace-opt-verbose foo.js
[marking 0x274720942969 <JSFunction createTree (sfi = 0x274796dab9e1)> for optimized recompilation, reason: hot and stable]
[compiling method 0x274720942969 <JSFunction createTree (sfi = 0x274796dab9e1)> (target TURBOFAN) using TurboFan]
```

this shows function `createTree` was optimized using tubofan.

Now if we see this method as the culprit method, exclude it like this:


```
#node --trace-opt-verbose --turbo-filter=-createTree foo.js
[marking 0x1358c7a82969 <JSFunction createTree (sfi = 0x1358418ab9e1)> for optimized recompilation, reason: hot and stable]
[marking 0x1358c7a82969 <JSFunction createTree (sfi = 0x1358418ab9e1)> for optimized recompilation, reason: hot and stable]
[marking 0x1358c7a82969 <JSFunction createTree (sfi = 0x1358418ab9e1)> for optimized recompilation, reason: hot and stable]
```

you will see that the method `createTree` is being picked up for compilation, but never gets compiled due to the exclusion plan, so `compiling method...` line will not appear. Please note the `-` sign before the function name.
