### ISSUE TITLE
Trying to access global object

### ISSUE THREAD

**Issue by Gmunker** [nodejs/help#362]
I literally just started learning NodeJS, i'm on the 3rd video of my course and I'm being introduced to the global object. The instructor just typed in >global and out came a bunch of stuff. When I type in global or console.log(global) it boots me back to the command line. This happens on both my PC and Laptop both running Windows10. 

```
bilio@vitalityHomeOne ~/desktop
$ node -v
v7.1.0

bilio@vitalityHomeOne ~/desktop
$ node
> global

bilio@vitalityHomeOne ~/desktop
$
```

Like I said i'm VERY new to NodeJS, i'm not sure what you would need to help me with this. It's very odd to me because it's happening on both my laptop and my PC, but no one else i have asked for help can recreate the issue. 

Thanks in advance!

**Comment by vsemozhetbyt** [comment]
@Gmunker If you use Node.js 7.1.0 on Windows 10 , it may be [this bug](https://github.com/nodejs/node/issues/9546). For me, the length of the `global` output is 8760 chars. i.e. it exceeds the buggy limit.

**Comment by vsemozhetbyt** [comment]
@Gmunker Until bug fix, you can inspect big objects gradually. Just paste in the node REPL this line after each `$ node` call:
```
 util.inspect.defaultOptions.depth = 1;
```
Then, if you type `global`, the output will be less verbose.

**Comment by Gmunker** [comment]
I ended up installing 6.9 for now and it works, i'm happy this is something known and is being addressed. Thank you so much for your responses!

**Comment by vsemozhetbyt** [comment]
@Gmunker It is fixed in Node.js 7.2.0.
