### ISSUE TITLE
Where are process.stdin and process.stdout defined?

### ISSUE THREAD

**Issue by jsDobromir** [nodejs/help#3620]
### Details

Hey guys, I recently started digging in the node.js source code, can someone guide me where are process.stdin and process.stdout defined?

### Node.js version

16.13.0

### Operating system

Linux

### Scope

Non-aplicable.

### Module and version

Not applicable.

**Comment by jsDobromir** [comment]
I found it, it is defined in /lib/internal/bootstrap/switches/is_main_thread.js.
If someone find this topic some day looking for the same answer.

**Comment by gireeshpunathil** [comment]
so closing as answered, cheers!
