### ISSUE TITLE
match(/regex/)

### ISSUE THREAD

**Issue by megahypercat** [nodejs/help#3621]
### Version

v14.17.1

### Platform

MINGW64_NT-6.3-9600 Virtual_win8 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys

### What steps will reproduce the bug?

`const fs = require('fs');
var datainput = fs.readFileSync('testinput.txt', 'utf-8')
var ids = datainput.match(/[0-9]{17,18}/g)
ids = ids.join("\n")
fs.appendFileSync("testoutput.txt", ids);
console.log("Done. Written file.")
`

[testinput.txt](https://github.com/nodejs/node/files/7577153/testinput.txt)

### How often does it reproduce? Is there a required condition?

From my data something like 1/250 matches or so that it fails to match.
Duplicate matches that do not exist in source happens about 480% of the time, as in on average 4.8 duplicates for every **actual** match in the input.

### What is the expected behavior?

This should match 17-18 numbers.
Once for every time the number exists.

### What do you see instead?

This matches numbers twice & more.
For example, "750730516940193866" appears once in the input, and matches 5 times.
This, however is not the main problem. it is easily fixed by removing duplicates. The main problem is:
Some sets of numbers **that should match do not match.**

**Comment by adelphes** [comment]
The test file you've provided gives the same results between the node script and the grep command:

```javascript
const fs = require('fs');
var datainput = fs.readFileSync('testinput.txt', 'utf-8')
var ids = datainput.match(/[0-9]{17,18}/g)
ids = ids.join("\n")

const sha1 = require('crypto').createHash('sha1');
sha1.update(ids + '\n');
console.log(sha1.digest('hex'));
// 'b37f4a9851a2b974fb3b1b52f4c846e9af925090'
```

```sh
> grep -E -o '[0-9]{17,18}' testinput.txt | shasum
b37f4a9851a2b974fb3b1b52f4c846e9af925090  -
```


I suspect the problem might be because you're using `fs.appendFileSync` instead of `fs.writeFileSync`- you are *appending* (adding) to an output file, instead of replacing it. That means each time you run the script, you'll see duplicates and/or values saved from earlier runs in the output file.
