### ISSUE TITLE
doc: When did request.end started to support Uint8Array?

### ISSUE THREAD

**Issue by jimmywarting** [nodejs/help#3622]
...Think i remembered a time when `Uint8Array` was not supported by the request send/end method...?

I just tried to send a Uint8Array and it did work. 
When did it become possible? are other typed arrays/arrayBuffer possible too? 

> <img src="https://user-images.githubusercontent.com/1148376/142774125-4722ee67-3e74-443a-9695-920f216c700e.png" width="400px"/>
>
> think ☝️ needs to be updated... ref: https://nodejs.org/dist/latest-v17.x/docs/api/http.html#requestenddata-encoding-callback

Got me thinking: (bit off-topic for this issue but...)
- should it support sending the new Blob class as well - just like browser can send a blob? `req.end(new buffer.Blob(...))`
- and how about sending a `URLSearchParams`? `req.end(new URLSearchParams(...))`

suggestion: default to cast anything to string if not understood by what gets passed in? just like the fetch api?

**Comment by nicofrand** [comment]
Hi,

my 2 cents: [we](https://framagit.org/kresusapp/kresus/-/issues/1147) had a case where it did not fully work when sending a JSON with French text in it, passed through `new TextEncoder.encode()` and resulted in this error: `The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Uint8Array`.
