### ISSUE TITLE
Node-red remote access is not connecting

### ISSUE THREAD

**Issue by syedaminulhaq** [nodejs/help#3624]
### Details

Hi,
install node-red-contrib-remote from manage pallet and did basic setting but it is not connecting with the network, i have seen on my command prompt that node-red-contrib-remote when i start flows see pic for reference!
![nodered3](https://user-images.githubusercontent.com/94774388/142844707-981f54a1-ccb9-4b10-80a1-92b482a3e415.PNG)
![nodered4](https://user-images.githubusercontent.com/94774388/142844721-428eda39-c943-4ce8-8a4f-c5bc1f4a69b7.PNG)
![nodered5](https://user-images.githubusercontent.com/94774388/142844729-e3db361d-d26f-4efc-a019-6c72f3389b94.PNG)

### Node.js version

Not applicable.

### Example code

not applicable

### Operating system

winsows10

### Scope

not applicable

### Module and version

Not applicable.

**Comment by elockman** [comment]
Old, but I ran across this.

Your Base URL should be **/ui** not **ui/**

Did you find any other fixes for you connectivity issues?

**Comment by RedYetiDev** [comment]
Hi! This looks like an issue with Node-Red, not Node.js. Please file an issue there.
