### ISSUE TITLE
METRO does not automatically open NODE.JS on Yarn Android [REACT-NATIVE]

### ISSUE THREAD

**Issue by gianseneda** [nodejs/help#3625]
### Details

I have this apk on REACT-NATIVE and by the script YARN ANDROID, it is automatically to open NODE.JS to run METRO, but it does not. It seems there is anything missing in Windows to allow it to open.

### Node.js version

10.18.0 or 12.22.0

### Operating system

WINDOWS 10

### Scope

SCRIPT YARN ANDROID TO AUTOMATICALLY BUILD WITH METRO

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Hi! As it currently stands, your issue seems to be regarding a software built with Node.js rather than Node.js itself. If you disagree, please let me know.
