### ISSUE TITLE
Error: listen EACCES: permission denied 127.0.0.1:80

### ISSUE THREAD

**Issue by songtianrui** [nodejs/help#3626]
### Version

v16.13.0

### Platform

Darwin songrui.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

在80端口起的服务,总是报权限不足,换为node的低版本后就可以了

### How often does it reproduce? Is there a required condition?

100%

### What is the expected behavior?

可以在80端口起服务

**Comment by addaleax** [comment]
@songtianrui You usually need to be to have admin permissions to listen on ports up to `1024`.

**Comment by songtianrui** [comment]
> @songtianrui You usually need to be to have admin permissions to listen on ports up to `1024`.
切换为低版本就没有这种问题

**Comment by gringofe** [comment]
Ching chong
