### ISSUE TITLE
node-v16.13.0 (2).pkg can't be installed because its digital signature is invalid.

### ISSUE THREAD

**Issue by laurazielinski97** [nodejs/help#3627]
### Details

I am trying to download Node.js v16.13 from https://nodejs.org/en/
Each time I download the app and try to open it I receive the error in the photo below.

<img width="1072" alt="Node js trouble" src="https://user-images.githubusercontent.com/94857968/143105701-d4c07dc7-9fb1-4cfd-aea9-b4e2ba1eb34d.png">

About my MacBook Pro:
OS X El Capitan
Version 10.11.6

Could the OS be the problem? Is there another way to download Node.js v16.13?

### Node.js version

Not applicable.

### Operating system

OS X El Capitan
Version 10.11.6

### Scope

I am not able to download the app.

### Module and version

Not applicable.

**Comment by addaleax** [comment]
> Could the OS be the problem?

I can tell you that El Capitan is quite old and even if you managed to install Node.js 16.x on it, it would not meet the minimum platform requirements to actually *run* Node.js: https://github.com/nodejs/node/blob/v16.x/BUILDING.md#platform-list

You can try installing a Node.js v14.x version instead, maybe that works (https://github.com/nodejs/node/blob/v14.x/BUILDING.md#platform-list lists it as supported).

**Comment by 0liver** [comment]
@laurazielinski97 Did Node.js v14.x work for you? Please let us know so we can close this issue.

**Comment by 0liver** [comment]
@laurazielinski97 Does that mean yes?

**Comment by laurazielinski97** [comment]
Yes. Sorry for the abruptness. I'm bit new to this community.

**Comment by 0liver** [comment]
No problem - me too 😀 I'm glad to hear though that you were able to move forward.

**Comment by Iemand005** [comment]
> > Could the OS be the problem?
> 
> I can tell you that El Capitan is quite old and even if you managed to install Node.js 16.x on it, it would not meet the minimum platform requirements to actually _run_ Node.js: https://github.com/nodejs/node/blob/v16.x/BUILDING.md#platform-list
> 

> You can try installing a Node.js v14.x version instead, maybe that works (https://github.com/nodejs/node/blob/v14.x/BUILDING.md#platform-list lists it as supported).

That's not true though, Node 16.x does run perfectly fine on El Capitan, it's just an expired certificate issue due to the old certificates in El Capitan having expired and not because Node isn't capable of running on it.
![Node running on El Capitan](https://github.com/nodejs/help/assets/65569591/d9392322-25a4-4af0-ba47-8069cfad2c0b)
