### ISSUE TITLE
spawn c:\Program Files\Git\bin; ENOENT  

### ISSUE THREAD

**Issue by Samiullah110** [nodejs/help#3628]
### Details

when I try to create a react project it shows the error below. any idea what's the issue 

### Node.js version

16.13.0

### Example code

spawn c:\Program Files\Git\bin; ENOENT  

### Operating system

windows 10 pro

### Scope

installation

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
The `ENOENT` error code refers to an entry not existing, the path `C:\Program Files\Git\bin` seems to be referring to the [Git CLI](https://github.com/git/git), you must have it installed to run whatever you're trying to run (In this case you're creating a new React project).

You can download and install the Git CLI for the specific operating system you're using from [here](https://git-scm.com/downloads).

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
