### ISSUE TITLE
Server Operating System Dependency for node.js

### ISSUE THREAD

**Issue by vdesai007** [nodejs/help#3629]
### Details

I have Windows 10 client side OS on my machine. I need to know what Server OS dependency is required to install latest 16.3 node.js

### Node.js version

16.3.0

### Operating system

Client OS: Windows 10

### Scope

Installation

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
@vdesai007 - can you clarify what you mean by client OS?

https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions

I could not locate a specific `client OS` version in this list.

do you mean that the resource configurations (such as memory and disk) are fit for a client as opposed to a server? or there is a real server-specific OS flavor for windows 10?

**Comment by gireeshpunathil** [comment]
if it is the former, then no specific dependencies exist. You can just install Node.js as is. If it is the later, I would like to know more details before commenting.

**Comment by vdesai007** [comment]
On my machine that had Windows 7, when I tried to install latest nodejs it did not allow me to, said it required >  Windows 7.
Then I upgraded my local desktop client to Window 10, after which it successfully installed nodejs 16

We need to install nodejs on the machine that has build agent Windows 2012 OS. So my question is there any dependency on what OS do we need to have to install nodejs?

**Comment by gireeshpunathil** [comment]
@vdesai007 - thanks.
this is not a list of runtime-supported platforms, instead for the build , but would suffice for the question at hand:

https://github.com/nodejs/node/blob/a2572940cdff72cdaa361b78389f05e5b91de315/BUILDING.md#platform-list

that contain the list of windows version as well.

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.

**Comment by AbdullahRumayah** [comment]
Setting up a Node development environment - Learn web  For any of those
operating systems, this article provides ... >node hellonode.js Server
running at ...

**Comment by AbdullahRumayah** [comment]
Server Operating System Dependency for node.js  Closed  vdesai007  2mo
Details  I have Windows 10 client side OS on my machine. I need to know
what Server OS dependency is required to install latest 16.3 node.js
Node.js version  16.3.0

Pada Jum, 21 Jan 2022, 11:19 PTG Abdullah Rumayah ***@***.***>
menulis:

> Setting up a Node development environment - Learn web  For any of those
> operating systems, this article provides ... >node hellonode.js Server
> running at ...
>
