### ISSUE TITLE
Debugger works with "node debug <uri>" but does not work with "node debug -p <pid>"

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#363]
I am having success debugging with 

`node debug <uri>`

but if I do 

`node debug -p <pid>`

success does not happen

I have this:

```
pid =>  14202 stderr =>  [test0.js] Debugger listening on 127.0.0.1:5304
pid =>  14203 stderr =>  [test1.js] Debugger listening on 127.0.0.1:5305
pid =>  14204 stderr =>  [test2.js] Debugger listening on 127.0.0.1:5306
pid =>  14207 stderr =>  [test5.js] Debugger listening on 127.0.0.1:5309
pid =>  14208 stderr =>  [test6.js] Debugger listening on 127.0.0.1:5310
pid =>  14205 stderr =>  [test3.js] Debugger listening on 127.0.0.1:5307
pid =>  14206 stderr =>  [test4.js] Debugger listening on 127.0.0.1:5308
```

As you can see, I started 7 child processes, and I have their PIDs and URIs.

If I do 

` node debug 127.0.0.1:5304`

I get this:

![screenshot 2016-11-12 22 04 19](https://cloud.githubusercontent.com/assets/11139560/20243982/0239c3aa-a924-11e6-8801-df7fffb8b5ab.png)

but if I do:

`node debug -p 14216`

I don't get the same result:

![screenshot 2016-11-12 22 05 31](https://cloud.githubusercontent.com/assets/11139560/20243989/2a296690-a924-11e6-999e-f16faa9ae00b.png)

It looks like it's trying to connect to port 5858, but that's definitely not the right port for that child process, so that's probably what's happening, but that seems like an implementation flaw?

(all of these child processes are pointing to the same files with the same debugger; statements , so there should be no difference in the behavior of each child process)

**Comment by bnoordhuis** [comment]
`node debug -p <pid>` is short-hand for `kill -USR1 <pid> && node debug localhost:5858`.  You can instruct it to use a different port with `node --debug-port=1234 debug -p <pid>`.

**Comment by ORESoftware** [comment]
nice, thanks
