### ISSUE TITLE
npm ERR! Cannot read properties of undefined (reading 'isServer')

### ISSUE THREAD

**Issue by ChiragSayaLife** [nodejs/help#3630]
### Version

v16.13.0

### Platform

Windows 64 bit

### What steps will reproduce the bug?

Whenever I tries to create a  new angular project shows me following error:
npm ERR! Cannot read properties of undefined (reading 'isServer')

### How often does it reproduce? Is there a required condition?

When we creates a new angular project

### What is the expected behavior?

Should create angular project and install all the required packages

### What do you see instead?

npm ERR! Cannot read properties of undefined (reading 'isServer')

**Comment by RedYetiDev** [comment]
As it currently stands, your issue lacks sufficient information to be reproducible
