### ISSUE TITLE
getting error install Amplify CLI

### ISSUE THREAD

**Issue by islahulislam** [nodejs/help#3633]
### Details

always facing this issue while  configure amplify CLI ,even i removed and re installed ,

### Node.js version

8.1.4

### Operating system

iOS

### Scope

changed 1530 packages, and audited 1560 packages in 2m

50 packages are looking for funding
  run `npm fund` for details

43 vulnerabilities (16 low, 6 moderate, 20 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
esar@eSars-MacBook-Pro-2 ~ % npn audit
zsh: command not found: npn
esar@eSars-MacBook-Pro-2 ~ % `npm audit`
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file

npm ERR! A complete log of this run can be found in:

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.

**Comment by gireeshpunathil** [comment]
sorry, closed too early.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
