### ISSUE TITLE
Issue with setting NODE_EXTRA_CA_CERTS

### ISSUE THREAD

**Issue by ndhambi** [nodejs/help#3636]
### Details

I am trying to  set extra CAs for my nodejs project, I tried using " set NODE_EXTRA_CA_CERTS={directorty}/ca.pem" but the nodejs project still cannot pick up the set env variable.

How can set this variable?

### Node.js version

V16.13.0

### Operating system

Windows 10

### Scope

server is up

server running

Error: unable to get local issuer certificate
   at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}

### Module and version

Not applicable.

**Comment by tniessen** [comment]
Is the Node.js process the client or the server application? Both should be aware of the CA, so you might have to add the CA list to both processes.

**Comment by nengluo** [comment]
Same error！Please help us!!!

**Comment by kleinmanshloma** [comment]
same problem Please can same one help us???!!!

**Comment by tniessen** [comment]
@WakandaKing @nengluo @kleinmanshloma We will need more information. A self-contained example that demonstrates the problem. An answer to my question in https://github.com/nodejs/help/issues/3636#issuecomment-1004517353. An example peer and CA certificate forming a full chain.
