### ISSUE TITLE
got an error trying to build node js from source

### ISSUE THREAD

**Issue by AdamKaScripter** [nodejs/help#3639]
### Details

Greetings!
Got an error trying to build lst version of node js.

### Node.js version

16.13.1

### Example code

../src/node_http_parser.cc:863:7: error: ‘llhttp_set_lenient_headers’ was not declared in this scope
       llhttp_set_lenient_headers(&parser_, 1);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/node_http_parser.cc:863:7: note: suggested alternative: ‘llhttp_set_lenient’
       llhttp_set_lenient_headers(&parser_, 1);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
       llhttp_set_lenient
../src/node_http_parser.cc:866:7: error: ‘llhttp_set_lenient_chunked_length’ was not declared in this scope
       llhttp_set_lenient_chunked_length(&parser_, 1);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/node_http_parser.cc:866:7: note: suggested alternative: ‘llhttp_set_lenient’
       llhttp_set_lenient_chunked_length(&parser_, 1);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       llhttp_set_lenient
../src/node_http_parser.cc:869:7: error: ‘llhttp_set_lenient_keep_alive’ was not declared in this scope
       llhttp_set_lenient_keep_alive(&parser_, 1);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/node_http_parser.cc:869:7: note: suggested alternative: ‘llhttp_should_keep_alive’
       llhttp_set_lenient_keep_alive(&parser_, 1);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       llhttp_should_keep_alive
../src/node_http_parser.cc: At global scope:
../src/node_http_parser.cc:978:1: error: too many initializers for ‘const llhttp_settings_t {aka const llhttp_settings_s}’
 };
 ^

### Operating system

linux

### Scope

Installation

### Module and version

Not applicable.

**Comment by marsonya** [comment]
Can you share the commands/procedure you used to build from source?

**Comment by gireeshpunathil** [comment]
ping @AdamKaScripter

**Comment by WammKD** [comment]
I got the same error. I'm building with Guix (and'm not terribly familiar with C so I'm not entirely sure what's going on) but, if I've understood things correctly, the command which triggered the resulting error was: `g++ -o /tmp/guix-build-node-16.16.0.drv-0/node-v16.16.0/out/Release/obj.target/libnode/src/node_metadata.o ../src/node_metadata.cc '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-D__STDC_FORMAT_MACROS' '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_OPENSSL_SYSTEM_CERT_PATH=""' '-DHAVE_INSPECTOR=1' '-DNODE_ENABLE_LARGE_CODE_PAGES=1' '-D__POSIX__' '-DNODE_USE_V8_PLATFORM=1' '-DNODE_HAVE_I18N_SUPPORT=1' '-DHAVE_OPENSSL=1' '-DOPENSSL_API_COMPAT=0x10000000L' -I../src -I/tmp/guix-build-node-16.16.0.drv-0/node-v16.16.0/out/Release/obj/gen -I/tmp/guix-build-node-16.16.0.drv-0/node-v16.16.0/out/Release/obj/gen/include -I/tmp/guix-build-node-16.16.0.drv-0/node-v16.16.0/out/Release/obj/gen/src -I../deps/googletest/include -I../deps/histogram/src -I../deps/uvwasi/include -I../deps/v8/include -I../deps/llhttp/include  -Wall -Wextra -Wno-unused-parameter -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++14 -MMD -MF /tmp/guix-build-node-16.16.0.drv-0/node-v16.16.0/out/Release/.deps//tmp/guix-build-node-16.16.0.drv-0/node-v16.16.0/out/Release/obj.target/libnode/src/node_metadata.o.d.raw   -c`

I'm using `llhttp` v2.1.5 and building `node` v6.16.0.
