### ISSUE TITLE
Docker run for node version 14.18.1 and 14.18.2 is not working with the same package.json which is working with 14.18.0

### ISSUE THREAD

**Issue by dyutis** [nodejs/help#3642]
### Version

14.18.2

### Platform

alpine

### What steps will reproduce the bug?

FROM node:14-alpine3.14 --> this base image has the underlying node version as 14.18.2, with this having as base image when we are trying to build a docker image of an application, the image is generated but while spinning up the container it is not executing the npm start command and exiting with exit code with 0. But the same application without any content changes if we build the image using base image as : FROM node:14.18.0-alpine3.14, then upon image built, when we are trying to spin up the container it is spinning up fine and not exiting. Below is the Dockerfile where the working base image is mentioned, here if we use 14-alpine3.14 which has node version 14.18.2 it doesn't spin up the container properly. PFA the sample package.json we are using.

Dockerfile (correct one)
```
FROM node:14.18.0-alpine3.14

# Set work directory to /usr/src/app
WORKDIR /usr/src/app

RUN apk update && apk upgrade

# Install app dependencies/www/package.json
COPY package*.json ./
RUN npm install

#switch to non-priviliaged user
RUN chown -R node:node /usr/src/app
USER node:node

# Copy app source
COPY --chown=node:node . .

# set your port
ENV PORT 3030

# expose the port to outside world
EXPOSE  3030

# start command as per package.json
CMD ["npm", "start"]

```

![CustomerAPI](https://user-images.githubusercontent.com/51526942/144884631-c7eb653e-ea9d-4401-9d4d-a808f71e27fb.PNG)
g.

### How often does it reproduce? Is there a required condition?

Every time we try

### What is the expected behavior?

The container won't exit and should execute the commands in it. Must execute npm start command and container should run.

### What do you see instead?

Docker conianter exits with code 0

**Comment by lenichols** [comment]
+1

**Comment by lenichols** [comment]
I was able to get it working by switching my deployment version number
