### ISSUE TITLE
scraping using puppeteer in nodejs-react-native

### ISSUE THREAD

**Issue by huriza** [nodejs/help#3643]
### Details

i have installed the package Node.js for Mobile Apps React Native plugin and inside my main.js file of node project i am creating a function for scraping in which i am trying to run some basic scrapper code using puppeteer. i have installed puppeteer in my nodeJs folder but its not really giving some output. Can someone explain if its even possible or not?

### Node.js version

node version: 14.18.1

### Example code

```js
var rn_bridge = require('rn-bridge');

async function scrape () {
   const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch();
    const page = await  browser.newPage();
    await page.goto('https://example.com');
    await page.screenshot({ path: 'example.png' });
    await browser.close();
}
rn_bridge.channel.send(scrape());
```

### Operating system

windows 10

### Scope

nodejs-react-native

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
It seems like you're trying to screenshot a website inside an async function called `scrape()`, but you don't seem to be returning anything as the value, and you're passing it to the `rn_bridge.channel.send()` without resolving the function's promise, what output are you exactly expecting?

**Comment by huriza** [comment]
@VoltrexMaster  I want the puppeteer code to execute inside the `rn_bridge.channel.send()` .This is just a dummy code i have written to test, the actual error occurs at line "const page = await  browser.newPage();" where it says that browser has no function of type "newPage()". I will be returning a value from it but that value can only be returned after the scraper code executes and it is not executing at the moment.

**Comment by VoltrexMaster** [comment]
@huriza

> the actual error occurs at line "const page = await browser.newPage();" where it says that browser has no function of type "newPage()".

Can you show the actual error you get on your terminal/console with it's stacktrace?

**Comment by huriza** [comment]
@VoltrexMaster can you tell me if its possible to scrape using node package?

**Comment by RedYetiDev** [comment]
Hi! Unfortunately, this looks like an issue with a third party package. I suggest you reach out to them to find the support you are looking for to for.
