### ISSUE TITLE
npm does not support Node.js v10.19.0

### ISSUE THREAD

**Issue by barjenbruchlaw** [nodejs/help#3644]
### Details

I cannot access npm right now.  My node version is 10.19.0, and my npm version is 6.14.  Here is the error message I am getting:

npm does not support Node.js v10.19.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

I have installed nodejs and npm from the command line.

### Node.js version

10.19.0

### Operating system

Kubuntu 20.04

### Scope

Global

### Module and version

Not applicable.

**Comment by rbjnazz** [comment]
same to me on linux mint xfce

**Comment by rAiZeNXD** [comment]
same on Rasbian

**Comment by EladAvni** [comment]
Same on Ubuntu 20

**Comment by theguitarvity** [comment]
anyone has fixed this?

**Comment by harikishantk** [comment]
Update node to current version

**Comment by JoKalliauer** [comment]
> Update node to current version

How?
(PS I'm using Ubuntu 20.04 on WSL on Windows 11-21H2)

**Comment by JoKalliauer** [comment]
I used 

```
# Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
```
according to  https://askubuntu.com/a/548776/676490.
And it worked. :-D

**Comment by hassonor** [comment]
Thank you JoKalliauer

**Comment by calisven** [comment]
> I used
> 
> ```
> # Using Ubuntu
> curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/548776/676490. And it worked. :-D

JoKalliauer I don't think this is a valid solution. Doing so would very likely cause breaking changes in the application as this would install the latest version of Node (currently 16.x) which is a big jump from 10.x. If you have a reasonably large Node app this would likely be a very bad idea unless you are willing to also fix any breaking changes that occur during the upgrade.

**Comment by JoKalliauer** [comment]
@calisven Thanks for your input. I don't have knowledge about node/npm. For me everything works with nodejs17.2, so I don't know what should be broken. Since the update it is less brocken than before.

Do you think updating to Node.js12 might be the best workaround?

```
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Or should we downgrade npm to 6.14.12? (How?)

**Comment by BlockchainSpot** [comment]
@JoKalliauer Thanks bro !

**Comment by ToucanBran** [comment]
> @calisven Thanks for your input. I don't have knowledge about node/npm. For me everything works with nodejs17.2, so I don't know what should be broken. Since the update it is less brocken than before.
> 
> Do you think updating to Node.js12 might be the best workaround?
> 
> ```
> curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> Or should we downgrade npm to 6.14.12? (How?)

I think we really need the node devs to weigh in on this at this point. This is pretty unacceptable since many applications run on lower versions were working and now are suddenly not...

**Comment by maxbettercloud** [comment]
If you have `nvm` you can try re-installing node versions. Make sure you switch to the version of node for which your npm works first.  For example switch to node 8 and then re-install other versions. 
```
nvm use 8
nvm uninstall 10
nvm uninstall 12
nvm install 10
nvm install12
nvm use 10
nvm uninstall 8
```

**Comment by awaism551** [comment]
I was facing this issue on my centos7 when my node version was `11.5.0` and npm version was `8`, I was able to run any command via npm and this error kept on coming, with yum installed nodejs and npm again with this command `sudo yum install -y nodejs`, it installed node@12.22.8 and npm@6.14.15

**Comment by cale-mcnulty** [comment]
Be sure to restart your shell after upgrading node if `node -v` is still returning the old version.

**Comment by NanoApes** [comment]
Thank you JoKalliauer

**Comment by ek08** [comment]
> I improved the post because of a [later post](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) by @calisven
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/1382566/676490 And it worked, whithout any problems. :-D

This is not working for me  :-( . The error that I am getting is 
```
W: GPG error: https://dl.winehq.org/wine-builds/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 76F1A20FF987672F
E: The repository 'https://dl.winehq.org/wine-builds/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

**Comment by adithyakirank** [comment]
I had to delete the node_modules dir and follow the instructions from @JoKalliauer here. Finally a functional electron installation!

**Comment by BrunoKoppel** [comment]
I had this issue recently, with the same output as above, for me @maxbettercloud solution solved the issue.

**Just uninstall all npm versions and reinstall them over.**

Hope this helps someone!

**Comment by IgnatBeresnev** [comment]
I made the mistake of updating npm before updating node, and had an error that Node 10.x is not supported.

I then wanted to update node using npm and got this error :(

**Comment by ramezwy5** [comment]
> I improved the post because of a [later post](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) by @calisven
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/1382566/676490 And it worked, whithout any problems. :-D

thank you for sharing this solution thumps up

**Comment by wetbadger** [comment]
I get this error with the latest version of node.

I typed npm --version
Apparently I am using npm version:

```
npm does not support Node.js v10.19.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```


Funny. I didn't know there was a version of npm called "npm does not support Node.js v10.19.0"

Ah, maybe 'npm help' will show me a useful list of commands.

```
npm does not support Node.js v10.19.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```
Hmm. None of those commands appear to work.

Let's uninstall with sudo apt remove npm.

```
blah blah blah
Removing npm (6.14.4+ds-1ubuntu2) ...
Processing triggers for man-db (2.9.1-1) ...
```

Okay, uninstalled.

Let's see what npm does, now that it's not a command.

```
npm does not support Node.js v10.19.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

Hmm, interesting that npm is now a default system command that only prints the above message.

I'm not sure this program is working as expected.

JoKalliauer's suggestion did not change anything for me.

**Comment by wetbadger** [comment]
Tries reinstalling and JoKalliauer's suggestion. Problem persists. I'd like to know what is causing it. It appeared in the middle of development after creating a sqlite database.

**Comment by JoKalliauer** [comment]
> I tried reinstalling, and JoKalliauer's suggestion, but this problem persists. I'd like to know what is causing it. It appeared in the middle of development after creating a sqlite database.

@wetbadger Which nodejs-version do you have installed? (`apt list nodejs -a` ,`node -v`, `npm version`)
The output of all three commands should be at least 12.22.8

**Comment by rajeshbnv1994** [comment]
i have just tried uninstalling and installing again and it worked for me 

nvm uninstall 10 
nvm install 10

**Comment by wetbadger** [comment]
> @wetbadger Which nodejs-version do you have installed? (`apt list nodejs -a` ,`node -v`, `npm version`) The output of all three commands should be at least 12.22.8

@JoKalliauer I had version 10.19.0 which was installed from apt. I went to the node website and downloaded v16.13.2 and I no longer have this problem.

Since problem is solved you don't need to see the outputs, but here they are:

```
$apt list nodejs -a
Listing... Done
nodejs/focal 10.19.0~dfsg-3ubuntu1 amd64

$node -v
v16.13.2

$npm version
{
  npm: '8.1.2',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
Why is apt so far behind even after update?

**Comment by Davidfree2** [comment]
> I improved the post because of a [later post](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) by @calisven
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/1382566/676490 And it worked, whithout any problems. :-D

Thank you so much. This worked great!

**Comment by juaurqui** [comment]
> If you have `nvm` you can try re-installing node versions. Make sure you switch to the version of node for which your npm works first. For example switch to node 8 and then re-install other versions.
> 
> ```
> nvm use 8
> nvm uninstall 10
> nvm uninstall  12
> nvm install 10
> nvm install 12
> nvm use 10
> nvm alias default 10   
> nvm uninstall 8
> ```

Thanks this is the perfect solution for me

**Comment by RonyMacfly** [comment]
I deleted the folder. The old version, installed through the file manager, now works.
`sudo rm -r /usr/local/lib/node_modules/`

I interrupted the execution of the commands.
`sudo npm install npm@latest -g`
`curl https://www.npmjs.com/install.sh | sudo sh`
```
npm -v
npm does not support Node.js v10.24.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

**Comment by sys128** [comment]
> I improved the post because of a [later post](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) by @calisven
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/1382566/676490 And it worked, whithout any problems. :-D

Was unsuccessful. Just reported an error, exiting. Nothing else specified.

**Comment by JoKalliauer** [comment]
@sys128 Please stay focused, declare the error you are getting and answer the questions in https://github.com/nodejs/help/issues/3644#issuecomment-1027773016 .

**Comment by dongnaebi** [comment]
maybe some package put npm in dependencies, such as js-beautify:
https://github.com/beautify-web/js-beautify/issues/2005

run `npm list npm` to find it

**Comment by Edwardchorius** [comment]
> If you have `nvm` you can try re-installing node versions. Make sure you switch to the version of node for which your npm works first. For example switch to node 8 and then re-install other versions.
> 
> ```
> nvm use 8
> nvm uninstall 10
> nvm uninstall  12
> nvm install 10
> nvm install 12
> nvm use 10
> nvm alias default 10   
> nvm uninstall 8
> ```

Uninstalling and installing just the nvm version that was needed as stated in the .nvmrc file was enough

**Comment by snowpilot** [comment]
> i have just tried uninstalling and installing again and it worked for me
> 
> nvm uninstall 10 nvm install 10

This worked for me too!

**Comment by TenzinJhopee** [comment]
> I improved the post because of a [later post](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) by @calisven
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/1382566/676490 And it worked, whithout any problems. :-D

thanks it fixed for me

**Comment by RajaSJN** [comment]
> I improved the post because of a [later post](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) by @calisven
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/1382566/676490 And it worked, whithout any problems. :-D

Thank you very much, this fixed my problem !

**Comment by Ahmedou-mdl** [comment]
did anyone solve the problem for windows

**Comment by JoKalliauer** [comment]
> did anyone solve the problem for windows

Try remove any old nodejs-version, and then try installing https://nodejs.org/en/download/

**Comment by being-nitin** [comment]
> sudo apt-get install -y nodejs

thanks for resolving the issue man , got the issues fixed

**Comment by kaddyadriano** [comment]
### To install the latest node version use the following
#### Using Ubuntu
```
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
```

#### Using Debian, as root
```
curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
apt-get install -y nodejs
```

**Comment by JoKalliauer** [comment]
This info had already been posted how to install the latest version, please do not make double-posts.

@kaddyadriano 
Please read [3644#issuecomment-996048756](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) in short:

### **Do not install the latest development-node-version, install the stable maching version.**

```sh
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by RenardFoxZorro** [comment]
Worked for me thank you brother!

**Comment by RenardFoxZorro** [comment]
> I improved the post because of a [later post](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) by @calisven
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/1382566/676490 And it worked, whithout any problems. :-D

Thank you all brothers, it worked perfect for us. Thank you

**Comment by LeoInCode** [comment]
Happening something like that for me. Was more about like:
ERROR: npm is known not to run on Node.js v19.7.0 Node.js 19 is supported but the specific version you're running has a bug known to break npm. Please update to at least 9..5.0 to use this version of npm. You can find the latest release of Node.js at https://nodejs.org/

I try a lot of solutions, but anyone works as well, so I went on MyComputer/<user>/AppData/Roaming and remove npm and npm-cache.
After that, I went on MyComputer/<user>/AppData/Roaming/nvm/<version>/node_modules/npm and delete the node_modules inside the npm
Change my version of the node using nvm use <stable version>
Run npm update -g npm
Run npm install -g npm@latest (or the version you want)
Run npm -v to certify if npm was in the version you want
Finally, inside of this path MyComputer/<user>/AppData/Roaming/nvm/<version>/node_modules/npm
Run npm i

After that, change the version of the node using nvm use <version you want>
And try again npm -v

This worked for me!

**Comment by dmitryartuh** [comment]
> I improved the post because of a [later post](https://github.com/nodejs/help/issues/3644#issuecomment-996048756) by @calisven
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```
> 
> according to https://askubuntu.com/a/1382566/676490 And it worked, whithout any problems. :-D

Thanks, still working for 18.x version

**Comment by patrickchoi** [comment]
> i have just tried uninstalling and installing again and it worked for me
> 
> nvm uninstall 10 nvm install 10

This worked for me, thank you!

**Comment by LeBron-Jian** [comment]
windows solution.
If you use `npm uninstall npm -g`, the following error will occur
```ERROR: npm v10.1.0 is known not to run on Node.js v10.24.1. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.```

Go to C:\Users\admin\AppData\Roaming and manually delete the npm and npm-cache folders (to be deleted as an administrator)

Uninstall node, then reinstall the corresponding version of node, and npm will also be reinstalled.

Then it's OK

**Comment by RedYetiDev** [comment]
The question appears to be asked and answered, if anyone has further issues, please open a new issue
