### ISSUE TITLE
HTTP Server POST request lost.

### ISSUE THREAD

**Issue by Gao996** [nodejs/help#3645]
### Version

12.8.1

### Platform

Microsoft Windows NT 6.1.7601 Service Pack 1 x64

### What steps will reproduce the bug?

After sending about a thousand requests, there will be a requestListener function that cannot enter the server.

Sometimes the http code of 400 will be returned successfully, which is not what I returned.

### How often does it reproduce? Is there a required condition?

Lost post requests appear almost every time.

Return 400 status code uncertain.

### What is the expected behavior?

I logged and proved that the actual number of posts is not the same as the number obtained in requestListener

### What do you see instead?

I logged and proved that the actual number of posts is not the same as the number obtained in requestListener

**Comment by tniessen** [comment]
This will be nearly impossible to solve without some code demonstrating the issue, or way more information.

**Comment by Gao996** [comment]
```JavaScript
var express = require('express');
var app = express();
var multer = require('multer');
var http = require('http');

app.get('/', function (req, res) {
    res.send('Hello World!');
});
app.use(express.static('public'));


var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        // After the file is uploaded successfully, it will be placed in the following folder
        cb(null,'./public/FileServer/uploads')
    },
    filename: function (req, file, cb) {
        // Set the name of the file to its original name, you can also add other characters to distinguish the same file, such as file.originalname+new Date().getTime(); use time to distinguish
        cb(null, new Date().getTime() + file.originalname)
    }
});
var upload = multer({
    storage: storage
});

app.post('/FileServer/fileupload', upload.single('file'), function (req, res, next) {
    console.log('fileserver fileupload\r\n');
    res.end(req.file.originalname);
});

var server = app.listen(8080, function () {
    var host = server.address().address;
    var port = server.address().port;

    console.log('file server listening at http://%s:%s\r\n', host, port);
});
```
About one thousandth

**Comment by Bavfalcon9** [comment]
This might be because of a maximum transfer limit set internally through the http module or express, is this occurring with every file or just subsequently larger ones?

**Comment by Gao996** [comment]
Every file will happen, and I will lose it after sending a picture hundreds of times.
I also wrote a file server myself, there is no maximum connection and transmission limit, I log and count the request out, in fact, there may be one-thousandth of loss
