### ISSUE TITLE
Compiler errors AIX 64-bit

### ISSUE THREAD

**Issue by Gumbit** [nodejs/help#3646]
### Details

Build command: CXXFLAGS='-funsigned-char' CFLAGS=$CXXFLAGS gmake -j4

Output:
 cc -o /app/engine_space/tgundrum/v8_builds/node-17.2.0/out/Release/obj.target/genccode/deps/icu/source/tools/genccode/genccode.o ../deps/icu/source/tools/genccode/genccode.c '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_HAS_QUIC' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_THREADS' '-DOPENSSL_NO_ASM' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu/source/common -I../deps/icu/source/i18n -I../deps/icu/source/tools/toolutil  -pthread -Wall -Wextra -Wno-unused-parameter -fPIC -maix64 -Wno-attributes -O3 -fno-omit-frame-pointer  -MMD -MF /app/engine_space/tgundrum/v8_builds/node-17.2.0/out/Release/.deps//app/engine_space/tgundrum/v8_builds/node-17.2.0/out/Release/obj.target/genccode/deps/icu/source/tools/genccode/genccode.o.d.raw  -funsigned-char -c
gmake[1]: cc: Command not found
gmake[1]: *** [tools/icu/genccode.target.mk:108: /app/engine_space/tgundrum/v8_builds/node-17.2.0/out/Release/obj.target/genccode/deps/icu/source/tools/genccode/genccode.o] Error 127
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:110: node] Error 2

A large number of source files compile successfully before encountering this error. The successful compiles use g++ rather than cc.

### Node.js version

Node version 17.2.0

### Operating system

AIX 64-bit version 7.2.0.0

### Scope

Installation

### Module and version

genccode is not compiling in this example. However, there have been others. One compilation failure was in openssl.

**Comment by richardlau** [comment]
You should be able to set `CXX=g++` as either an environment variable or make variable to tell make where your g++ compiler is (Node.js requires gcc to build).

**Comment by Gumbit** [comment]
Still getting the same issue. I tried setting CXX to g++ and also tried with the full path of g++. I was wondering whether this might need to be done before the configure. So, I again un-tared the source and reran the configure. Still fails on the same source file. Following is my configure command: "./configure --dest-cpu=ppc64 --shared --enable-static --with-intl=full-icu --with-icu-source=./deps/icu4c-69_1-src.tgz --openssl-no-asm"

**Comment by richardlau** [comment]
What does `configure --verbose` report?

Should be something like
```console
Detected C++ compiler (CXX=g++) version: 8.3.0
Detected C compiler (CC=gcc) version: 8.3.0
```

**Comment by Gumbit** [comment]
Detected C++ compiler (CXX=g++) version: 8.5.0
Detected C compiler (CC=gcc) version: 8.5.0

**Comment by richardlau** [comment]
Those look okay. Could you also try setting `CXX_host` to `g++`?
(In the Node.js CI we set `CC`, `CXX` and `CXX_host`,
```console
export CC=gcc CXX=g++ CXX_host=g++
```
for AIX.)

**Comment by Gumbit** [comment]
Richard, thank you so much for your help. My builds are now completing.
