### ISSUE TITLE
UV_THREADPOOL_SIZE not working inside a docker container

### ISSUE THREAD

**Issue by Patick-Bateman** [nodejs/help#3649]
I have a machine with 8 cpu cores. And i have a native C++ addon that my nodejs app is using. If i try to run it locally without docker, with `UV_THREADPOOL_SIZE` set to 8, it uses all 8 cores as expected. But, if i try to do the same within a docker container, seems like it only uses one core and changing `UV_THREADPOOL_SIZE` doesn't affect anything. When i log `os.cpus().length` inside a docker container it's showing all 8 cores correctly. What could be the problem?

**Comment by mhdawson** [comment]
What container are you running in?

**Comment by Patick-Bateman** [comment]
@mhdawson Problem was on my side, main thread is under heavy load that my program could not benefit from additional cores. Thx. I'm closing this issue.
