### ISSUE TITLE
Capturing secondary / tertiary stream to terminal / TTY

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#365]
Looking for an answer to this question I asked earlier today on SO, so far no responses, (a solution will be Node.js specific I think) =>

http://stackoverflow.com/questions/40598075/capturing-secondary-tertiary-stream-to-terminal-tty

The question is:

I run a command from the terminal which starts a server, and the server in turn will start workers (child processes). I want to stream the stdout/stderr of the server to some log file, but I want the stdout and stderr of the workers to stream back to the terminal. All processes here are Node.js processes.

No idea how to do this or if it's possible. My only guess as to how it might work is if the terminal session has some sort of handle or id which I can use and tell the worker processes to stream to that handle or id. I don't know enough about *nix to know how this works. Any explanation would help.

As it stands now, my guess is that I would have to pass some sort of file descriptor somehow to the server process somehow that points to the current terminal, but again I don't know much about this.

A visual:

![20161114_131544](https://cloud.githubusercontent.com/assets/11139560/20288763/917f0964-aa8a-11e6-8dd9-081a5497958b.jpg)

**Comment by bnoordhuis** [comment]
Untested, but I think you should be able to open and pass /dev/tty like this:
```js
const { O_RDWR, O_NOCTTY } = fs.constants;
var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);
var proc = child_process.spawn(cmd, args, { stdio: [fd, fd, fd] });
```
O_NOCTTY probably isn't necessary in the scenario you describe but it won't hurt either.

**Comment by ORESoftware** [comment]
Thanks :)

I assume the child_process.spawn() call above is to start the server

So you pass the file descriptors to the server, and eventually those fd's will be passed to the workers. 

But I guess what I am missing is how to pipe stdout/stderr of the server to a log file and (not to the terminal).

And also, I am guessing/assuming that those fs.constants values simply point to the current terminal fd somehow?

**Comment by bnoordhuis** [comment]
> I am assuming that the child_process.spawn() call above is to start the server

It's to start the child process.  To redirect the output of the server, just use standard shell redirection: `node server.js 2>&1 >server.log`.

> And also, I am guessing/assuming that those fs.constants values simply point to the current terminal fd somehow?

I'm not sure what you're asking.  It opens /dev/tty in read/write mode without becoming the controlling tty of the server process.  O_NOCTTY probably isn't necessary but neither should it hurt.

**Comment by ORESoftware** [comment]
Yeah one catch, is that I want the user to be able to close the terminal window without affecting anything, but I think if I do  node server.js 2>&1 >server.log. &, then it should work, right?

My question regarding the fd's was => what is it about the code you used gives the system information to point back to the current terminal session?

One more quick question - I can pass the fd's to the child process using the stdio option, but how do I prevent the server itself from writing stdout/stderr to those fd's? Do I use the silent option or something?

**Comment by ORESoftware** [comment]
Ok just to see if it works, I tried your code sample - originally I have this:


     ```js
   const p = path.resolve(global.sumanHelperDirRoot + '/logs/server.log');

        n = cp.spawn('node', [ file ], {
          env: Object.assign({}, process.env, {
            SUMAN_SERVER_OPTS: sumanCombinedOpts,
            NODE_ENV: $NODE_ENV || process.env.NODE_ENV,
            SUMAN_CONFIG: JSON.stringify(sumanConfig)
          }),
          detached: true,
          stdio: [ 'ignore', fs.openSync(p, 'a'), fs.openSync(p, 'a') ]
        });
```

if I change the above to:

```js

    
        const { O_RDWR, O_NOCTTY } = fs.constants;
        var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);


        n = cp.spawn('node', [ file ], {
          env: Object.assign({}, process.env, {
            SUMAN_SERVER_OPTS: sumanCombinedOpts,
            NODE_ENV: $NODE_ENV || process.env.NODE_ENV,
            SUMAN_CONFIG: JSON.stringify(sumanConfig)
          }),
          detached: true,
          stdio: [ 'ignore', fd, fd]
        });

```

I don't get anything logged to terminal, but I would except the server stdout/stderr to get logged to terminal

**Comment by ORESoftware** [comment]
However if I do this:


  ```js
      n = cp.spawn('node', [ file ], {
          env: Object.assign({}, process.env, {
            SUMAN_SERVER_OPTS: sumanCombinedOpts,
            NODE_ENV: $NODE_ENV || process.env.NODE_ENV,
            SUMAN_CONFIG: JSON.stringify(sumanConfig)
          }),
          detached: true,
          stdio: [ 'ignore', 1, 2, 'ipc' ]   // <<< now server stdout/stderr gets logged to current terminal
    
        });
```

so instead of the above, I want the worker stdout/stderr to go to current terminal, but the server stdout/stderr to go to a log file.

**Comment by ORESoftware** [comment]
I made some progress. By passing this:

stdio: [ 'ignore', 1, 2, 'ipc' ]   // <<< now stdout/stderr gets logged to current terminal

to both the server child_process and the worker child processes (launched by server child process), then I get the stdout/stderr in my terminal, which is progress.

My guess is to get this to work,  I need to pass fd's via IPC (or socket.io?)

Another feature is that I need to figure out how to pipe stdout/stderr to at least 2 different places for the worker processes. And I am not sure how to do that with the stdio array option; the stdio option array seems to give you only one location to pipe stdout/stderr.

**Comment by ORESoftware** [comment]
I got it to work, but the only step that I have to currently do manually is to get the fd of the current TTY..

normally we could do that with cp.execSync('tty') but that is not working for me, and I filed an help issue for that separately, thanks for your help

**Comment by addaleax** [comment]
@ORESoftware Is there something left unanswered here or can this be closed?

**Comment by ORESoftware** [comment]
yep, thanks!

basically as a synopsis, the solution that seems to work is that I get the current TTY with

`const tty = String(cp.execSync('tty', {stdio:['inherit','pipe','pipe']})).trim();`

I pass that dynamic value ( a string) to the child process using socketio.

In the child process, I use `fd = fs.openSync(tty)` to get the right file descriptor.

Then I can write to the terminal that I want to write to with

`fs.createWriteStream(null, {fd: fd});`

this took me all day to figure out, so leaving this here for anyone to see

https://stackoverflow.com/questions/40621761/on-macos-error-ebadf-bad-file-descriptor-close
