### ISSUE TITLE
SSL certificate in node.js on windows server

### ISSUE THREAD

**Issue by NewFran2021** [nodejs/help#3650]
### Details

I am trying to create an SSL certificate for a node.js application running on a Windows server. Unfortunately, it does not work through the server's IIS, nor through my previous attempts to implement it in the server.js file code. The node.js application runs on the localhost on the windows server without any problems. However, it cannot be accessed from outside because the certificate is not set up properly. How can I set up the SSL certificate correctly?

### Node.js version

v12.18.4

### Operating system

Microsoft Windows Server 2019

### Scope

server is up, server is running on localhost, website is not working due to ssl certificate

### Module and version

Not applicable.

**Comment by tniessen** [comment]
I have (luckily) never had to configure IIS, but it can probably act as a reverse proxy just like Apache etc. In that case, IIS can take care of TLS and certificates.

If that isn't an option for some reason, you can configure TLS sockets and secure contexts within Node.js to use a custom certificate using the [`cert` option](https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener).
