### ISSUE TITLE
How to close inspector in worker thread?

### ISSUE THREAD

**Issue by ds3p2** [nodejs/help#3651]
### Details

I am trying to enable some debugging in the worker thread programmatically. I read the [Inspector](https://nodejs.org/docs/latest-v14.x/api/inspector.html) API and trying to implement it in the worker thread model.   
Currently I am not sure which is the proper way to use the `inspector` module in worker thread.    
The sample code shows how I am using `inspector`. 

- I found `inspector.open` can be called in the worker thread, and the created inspector only works in the current thread. Breakpoints in other thread / main thread will be just ignored.
- However, I found `inspector.close` is `undefined` in worker thread. According to https://github.com/nodejs/node/pull/30680, this is the expected behavior. But the question is how do I close the debugger port created in the worker thread?

### Node.js version

14.15.5

### Example code

``` javascript
const {
  isMainThread,
  parentPort,
  Worker,
  workerData,
} = require("worker_threads");
const inspector = require("inspector");

if (isMainThread) {
  console.log("in main thread", inspector.close);
  // inspector.open(9231, "127.0.0.1", true);  // Uncomment this line will get error "Inspector is already activated"
  const worker1 = new Worker(__filename, { workerData: { id: 1 } });
  const worker2 = new Worker(__filename, {
    workerData: { id: 2 },
  });
  let cnt = 0;
  worker1.on("message", () => {
    cnt++;
  });
  worker2.on("message", () => {
    cnt++;
  });
} else {
  if (workerData.id === 1) {
    console.log("in worker thread", inspector.close);
    inspector.open(9229, "127.0.0.1", true);
    const content = "I am worker: " + workerData.id;
    setInterval(() => {
      console.log(content);
      parentPort.postMessage("done");
    }, 1000);
  } else {
    console.log("in worker thread", inspector.close);
    inspector.open(9230, "127.0.0.1", true);
    const content = "I am worker: " + workerData.id;
    setInterval(() => {
      console.log(content);
      parentPort.postMessage("done");
    }, 1000);
  }
}
```

### Operating system

Mac OS 12.0.1

### Scope

code, runtime

### Module and version

Not applicable.

**Comment by addaleax** [comment]
@ds3p2 I think the best way to address this would be to always open/close the inspector server from the main thread, and then communicate to the worker threads using that?

**Comment by ds3p2** [comment]
@addaleax 
My case is a little special.  
I suppose different threads are running tasks belongs to different owners, and there will be more than one developer doing debugging at the same time, each focusing on one specific thread. If I use an inspector from the main thread, then developer may accidentally comes across breakpoint from other thread or the main thread (when some of them do not set proper breakpoint condition).   
Although I did not find relative statement in any document, I am quite satisfied with the current behavior that the inspector created in a worker thread is "scoped".

**Comment by addaleax** [comment]
@ds3p2 I guess you could also use the `inspector.Session` API and host the TCP server yourself, for each thread?

> Although I did not find relative statement in any document, I am quite satisfied with the current behavior that the inspector created in a worker thread is "scoped".

I don’t think this is the intended use case here – if you do want to get into a situation in which there can be more than one built-in inspector TCP server per process, I think that would require some work on Node.js itself.

**Comment by ds3p2** [comment]
> I guess you could also use the inspector.Session API and host the TCP server yourself, for each thread?

I do not quite understand your suggestion. In the main process I cannot call `inspector.open` multiple times (Error `Inspector is already activated. Close it with inspector.close() before activating it again.`). Even if I can create separate session for each thread, how do the developer specify which thread to debug when trying to attach to the same debug port?

> I don’t think this is the intended use case here – if you do want to get into a situation in which there can be more than one built-in inspector TCP server per process, I think that would require some work on Node.js itself.

I am not sure if I understand this correctly. Are you suggesting that `inspector.open` should bot be called inside a worker thread? If so, why not disable the API just like `inspector.close`?

**Comment by addaleax** [comment]
> Are you suggesting that `inspector.open` should not be called inside a worker thread?

Yes.

> If so, why not disable the API just like `inspector.close`?

I don’t know?

**Comment by ds3p2** [comment]
@addaleax 
OK, it seems I need to look for some other approach.   
Is there any official document where usage of `inspector.open` in worker thread is discouraged?

**Comment by addaleax** [comment]
@ds3p2 No, but I assume there should be one in https://nodejs.org/api/inspector.html#inspectoropenport-host-wait. It’s a bit unfortunate that the inspector API was never really well-documented to begin with :confused:

**Comment by ds3p2** [comment]
@addaleax 
It's OK, thanks for your kind help. I am closing this issue.
