### ISSUE TITLE
Visual Studio Coding  python error.  "node" not recognized

### ISSUE THREAD

**Issue by kelseyp99** [nodejs/help#3652]
### Details

after node.js install, Visual Studio Coding python error:   
> node --version node 
message: The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check  the spelling of the name, or if a path was included, verify that the path is correct and try again. 

I tried changing path as in https://stackoverflow.com/questions/27344045/installing-node-js-and-npm-on-windows-10/42731621#42731621

### Node.js version

Not applicable.

### Operating system

windows 10

### Scope

code

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Hi! It seems your issue may be an issue with your specific system installation, and not an issue with Node.js itself. If you disagree, please reach out
