### ISSUE TITLE
npm commands return "& was unexpected at this time" on windows

### ISSUE THREAD

**Issue by paulbnder** [nodejs/help#3653]
### Details

I am trying to install nodejs but any npm command such as "npm -v" returns "& was unexpected at this time." 
"node -v" is working fine.
I have tried installing several nodejs versions such as 16.13.1, 15.14.0 and 17.2.0
My operating system is Windows 11.
The correct folder was also added to path as shown in the screenshot.
I dont really know what else I could try out at this point except for reinstalling windows, which I would like to avoid.

### Node.js version

Not applicable.

### Operating system

Windows 11

### Scope

Installation

### Module and version

Not applicable.
![Screenshot (23)](https://user-images.githubusercontent.com/63110737/146371180-ef32bed4-4444-49fc-ad9a-9ae028c1af76.png)

**Comment by rohi221b** [comment]
check whether the command prompt is working or not if not then try -->**https://stackoverflow.com/questions/66335300/cmd-crashes-with-exit-code-1-after-uninstalling-anaconda**
