### ISSUE TITLE
Nest + Fastify + AsyncLocalStorage middlewares

### ISSUE THREAD

**Issue by ghost** [nodejs/help#3661]
### Details

The middlewares are not working if fastify (adapter) is installed. When it is removed the middleware starts to work (express adapter), for both GET and POST requests.

### Node.js version

14/16/17

### Example code

https://github.com/B4nan/nest-fastify-als

### Operating system

Ubuntu 20.04

### Scope

yarn
yarn start
curl localhost:3000
curl -X POST localhost:3000

To return stored value not undefined.

### Module and version

Not applicable.

**Comment by B5nan** [comment]
nestjs/nest#8843
https://github.com/B4nan/nest-fastify-als

**Comment by B5nan** [comment]
https://github.com/fastify/fastify/issues/3568
