### ISSUE TITLE
Possible bug - output of echo will not run

### ISSUE THREAD

**Issue by JESUSrosetolife** [nodejs/help#3662]
### Version

v16.13.1

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### What steps will reproduce the bug?

Open a PowerShell command prompt
Run this command: `echo "console.log('hi');" > sandbox.mjs; node sandbox.mjs`

### How often does it reproduce? Is there a required condition?

It consistently reproduces

### What is the expected behavior?

I expect to see `hi` outputted from the console:
```
PS C:\[omitted]> echo "console.log('hi');" > sandbox.mjs; node sandbox.mjs
hi
```

### What do you see instead?

I see this error message:

```
PS C:\[omitted]> echo "console.log('hi');" > sandbox.mjs; node sandbox.mjs
file:///C:/[omitted]/sandbox.mjs:1
��c


SyntaxError: Invalid or unexpected token
←[90m    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)←[39m
←[90m    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)←[39m
←[90m    at async link (node:internal/modules/esm/module_job:67:21)←[39m
```

### Additional information

My PowerShell is version: `5.1.22000.282` (`Get-Host | Select-Object Version`)

**Comment by RedYetiDev** [comment]
*(question was answered in first comment)*
