### ISSUE TITLE
Nodejs auto upgrade issue

### ISSUE THREAD

**Issue by dsankarraj** [nodejs/help#3663]
### Details

I have installed nodejs 14.14 in my pc to work with angular application on visual studio 2019 IDE.

In 6 days it was upgraded 3 times from 14.14 to 17.0.1 automatically. In windows 10 control panel nodejs installation date is showing as 23.12.2021 in which i have not installed it.

everytime i need to uninstall it again reinstall the 14.14 version to do downgrade.

few of my team members also faced same issue. Few faced the issue only once and few faced the issue more than once.

Kindly help me out to resolve the issue. This is hammering my development activities.

### Node.js version

nodejs 14.14

### Operating system

Windows 10

### Scope

auto upgrade

### Module and version

Not applicable.

**Comment by dsankarraj** [comment]
{
  "name": "CROMC.SPA",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "echo Starting... && ng serve -o",
    "build": "ng build",
    "build-dev": "ng build --configuration=dev",
    "build-qa": "ng build --configuration=qa",
    "build-uat": "ng build --configuration=uat",
    "build-prod": "ng build --configuration=prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.2",
    "@angular/cdk": "^10.2.2",
    "@angular/common": "~10.1.2",
    "@angular/compiler": "~10.1.2",
    "@angular/core": "~10.1.2",
    "@angular/forms": "~10.1.2",
    "@angular/localize": "~10.1.2",
    "@angular/material": "^10.2.2",
    "@angular/platform-browser": "~10.1.2",
    "@angular/platform-browser-dynamic": "~10.1.2",
    "@angular/router": "~10.1.2",
    "@azure/msal-browser": "^2.14.1",
    "@ng-bootstrap/ng-bootstrap": "^8.0.0",
    "@ng-select/ng-select": "^5.0.8",
    "angular-datatables": "^9.0.2",
    "bn-ng-idle": "^1.0.1",
    "bootstrap": "^4.5.2",
    "crypto-ts": "^1.0.2",
    "datatables.net": "^1.10.22",
    "datatables.net-bs4": "^1.10.22",
    "datatables.net-buttons-dt": "^1.6.4",
    "datatables.net-dt": "^1.10.24",
    "datatables.net-fixedcolumns-dt": "^3.3.2",
    "datatables.net-fixedheader-dt": "^3.1.7",
    "datatables.net-responsive-dt": "^2.2.6",
    "datatables.net-rowgroup-dt": "^1.1.2",
    "datatables.net-searchbuilder-dt": "^1.0.0",
    "datatables.net-searchpanes-dt": "^1.2.0",
    "datatables.net-select-dt": "^1.3.3",
    "jquery": "^3.5.1",
    "minimatch": "^3.0.4",
    "moment": "^2.28.0",
    "moment-timezone": "^0.5.33",
    "ngx-bootstrap": "^6.2.0",
    "ngx-trim-directive": "^1.1.0",
    "path": "^0.12.7",
    "popper.js": "^1.16.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "xlsx": "^0.17.4",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1002.0",
    "@angular/cli": "^10.1.6",
    "@angular/compiler-cli": "~10.1.2",
    "@types/datatables.net": "^1.10.19",
    "@types/datatables.net-fixedcolumns": "^3.2.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.5.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

**Comment by tniessen** [comment]
The official Node.js distributions do not auto-upgrade. If you installed Node.js through a third-party application, that third-party application may be responsible for the automatic upgrading.

**Comment by dsankarraj** [comment]
I have installed it by using node-v14.14.0-x64.msi which i have downloaded from Nodejs official website.

In windows10 weekly once it is happening
<img width="960" alt="nodejs_frequent_updation" src="https://user-images.githubusercontent.com/96570117/148014211-8a454e76-4824-446c-bb23-8b1edc2a096c.png">

**Comment by dsankarraj** [comment]
every time when it was auto upgraded i used to uninstall it and reinstall 14.14 version

**Comment by tniessen** [comment]
Maybe VS 2019 is updating it, assuming you enabled its Node.js components?

Node.js itself contains no logic for automatic upgrades and I have never heard of Windows 10 updating Node.js either.

**Comment by dsankarraj** [comment]
This same Vs2019 Nodejs work load concern was raised by my teammate also.

Today My IT support Team did some changes to stop auto updation of Node in windows 10. Let see whether it is working or not.

I will update you the same in the loop. 

 if the changes by local IT Team is not working then we will inspect further towards vs2019.

Thanks for the reply.

**Comment by dsankarraj** [comment]
What change have done by local IT Team was, Windows 10 should ask permission everytime to install if any update available for Node.

Let see whether it is working or not

**Comment by tniessen** [comment]
Thanks for reporting back @dsankarraj!

**Comment by dsankarraj** [comment]
it is still happening

![image](https://user-images.githubusercontent.com/96570117/148323451-0d7c46ac-dbd9-45b5-998b-3b65928294e2.png)

**Comment by tniessen** [comment]
It's interesting that, whatever is causing the update, is not using the most recent version of Node.js. I would expect the automatic update process to install the newest version, but 17.0.1 has been out for a while and there are newer 17.x releases. Maybe this tells us something about which distribution channel is being used?

**Comment by dsankarraj** [comment]
I too noticed it.

**Comment by aloksuman007** [comment]
I am also facing the same problem, I installed node 10.16.0 and its auto upgraded to higher version. Till now I uninstall and install several times and same issue happening. Can anybosy let me know what to do in this case

**Comment by thiennguyen007** [comment]
Is there any solutions for issue? NodeJs is bad!

**Comment by bcanterbury** [comment]
No one's got an answer for this?  I'm going through the same thing.

**Comment by tniessen** [comment]
@bcanterbury Node.js is not updating itself, so you need to figure out what software on your system is updating Node.js. As you'll see in the discussion above, we have no way of knowing.

**Comment by RedYetiDev** [comment]
As mentioned, Node.js itself is not auto-upgrading, but a manager that is controlling the program. Please contact that source instead.

Thanks!
