### ISSUE TITLE
I Can not install or delete node.js

### ISSUE THREAD

**Issue by unfazeds** [nodejs/help#3666]
### Details

![image](https://user-images.githubusercontent.com/84151633/147396441-f69b9bc7-6d15-466b-b8f5-a52ee1e43f3d.png)
 
 If I can Install or Delete node.js this problem always come my screen

### Node.js version

I am trying to download -v17.3.0

### Example code

.

### Operating system

.

### Scope

.

### Module and version

-v17.3.0

**Comment by tniessen** [comment]
This unfortunately seems like a Windows or system setup problem at first glance. There are various articles online about this problem regardless of the application (in this case, Node.js).
