### ISSUE TITLE
Node Js installation issue

### ISSUE THREAD

**Issue by Panchalsandip** [nodejs/help#3669]
### Details

I am not able setup node.js on my computer. I did install before one year but did not remember it which drive. Now, I am trying to run installer, it asking for G: drive and then installation will stopped immediately. But i do not have G: drive on laptop 

### Node.js version

Not applicable.

### Operating system

window 10

### Scope

Node Js installation issue

### Module and version

Not applicable.

**Comment by tniessen** [comment]
If you installed Node.js and added it to your `PATH` environment variable, you can find the location of the existing installation using the following command.

```bat
where node.exe
```

**Comment by gireeshpunathil** [comment]
ping @Panchalsandip
