### ISSUE TITLE
Getting file descriptor of current TTY

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#367]
Looks like you can retrieve the fd of the current TTY via:

$ tty

described here:

http://unix.stackexchange.com/questions/270272/how-to-get-the-tty-in-which-bash-is-running/270372

(not sure what the difference is between the path given by `$tty` and the fd integer given by `fs.openSync()`, but I am guessing there is a 1:1 correspondence).

however, I am wondering if we can capture that value programmatically in Node.js runtime, without having to spawn a child process to get that value (assuming that value is what I am looking for).

For example, if we start a node.js process with a shell/terminal window, I assume that we could have something like this available:

`process.tty` or `process.ttyfd` or something

if the process was not started with a shell, I guess that property would be null/undefined.

Please lmk, thanks for your help!

**Comment by ORESoftware** [comment]
However, if I do

`child_process.execSync('tty')`

I get 

```
 Error: Command failed: tty

    at checkExecSyncError (child_process.js:488:13)
    at Object.execSync (child_process.js:528:13)
    at Server (/Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/create-suman-server.js:52:13)
    at watch (/Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/watching/add-watcher.js:84:3)
    at module.exports (/Users/Olegzandr/WebstormProjects/oresoftware/suman/lib/helpers/watch-init.js:56:41)
    at Object.<anonymous> (/Users/Olegzandr/WebstormProjects/oresoftware/suman/index.js:557:38)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12) 
```

**Comment by ORESoftware** [comment]
Not sure why tty command doesn't work, but one idea I have to get this info is to inspect

`process.stdout` or `process.stderr` because those should generally point to the "current tty"

**Comment by addaleax** [comment]
`tty` on my Linux system does basically the equivalent of `fs.readlinkSync("/proc/self/fd/0")` and checks that the result is a TTY, so my guess would be that *stdin* is not a valid or a non-TTY fd in your scenario.

But anyway, you should get a proper fd referring to the TTY using Ben’s code from https://github.com/nodejs/help/issues/365#issuecomment-260574249 (which should also work when *all* of stdio is redirected).

**Comment by ORESoftware** [comment]
Thanks yeah,` fs.constants` is undefined, so I didn't know what to do with that

```
const { O_RDWR, O_NOCTTY } = fs.constants;  // fs.constants is undefined
var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);
var proc = child_process.spawn(cmd, args, { stdio: [fd, fd, fd] });
```

also, I am thinking that this line

`var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);`

should be this instead:

`var fd = fs.openSync('/dev/tty' + O_RDWR + O_NOCTTY);`

or no?

**Comment by addaleax** [comment]
> `const { O_RDWR, O_NOCTTY } = fs.constants;  // fs.constants is undefined`

If you’re on Node v4, I think you’re stuck with using
```js
const constants = require('constants');
fs.openSync('/dev/tty', constants.O_RDWR + constants.O_NOCTTY);
```

**Comment by ORESoftware** [comment]
yeah, thanks, I don't know why I got that constants undefined problem, using Node v7, I have:

```js
const fs = require('fs');
const util = require('util');

// console.log(util.inspect(fs));  // I verifed that constants is there, and it is

const O_RDWR = fs.constants.O_RDWR;
const O_NOCTTY = fs.constants.O_NOCTTY;

console.log('O_RDWR',O_RDWR);
console.log('O_NOCTTY',O_NOCTTY);

var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);

const fdTerm = fs.openSync('/dev/ttys003','a');  // this was from the `$ tty` command

console.log('fd:',fd);
console.log('fdTerm:',fdTerm);
```

basically, fd and fdTerm don't match, and I think they should

**Comment by ORESoftware** [comment]
in the script above, you should replace '/dev/ttys003' without ever the `tty` command gives you at the terminal

**Comment by addaleax** [comment]
> basically, fd and fdTerm don't match, and I think they should

The fds returned from two calls to `open()` won’t ever be the same if the first fd is not closed before the second one is opened. You can open a file again and again and again, and will always get different fds; they can still point to the same file.

> in the script above, you should replace '/dev/ttys003' without whatever the `tty` command gives you at the terminal

I don’t know what platform you are working on but opening `/dev/tty` should be functionally equivalent to what you are describing in virtually every situation. `/dev/tty` will work fine for you and will be more reliable than the `tty` command, because the `tty` command will always only check what TTY `stdin` refers to.

**Comment by ORESoftware** [comment]
Ok, that's useful info, last time I tried

`var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);`

it didn't work

but if I did

`var fd = fs.openSync(cp.execSync('tty'),'a');  // in an imaginary world where cp.execSync('tty') works :)`

then that fd did work. I will try the way you and @bnoordhuis suggest, do you think you could explain what this command is doing?

`var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);`

what exactly is happening there? I can only guess. The second arg is generally for the flag for opening the file.

**Comment by addaleax** [comment]
> it didn't work

It might be helpful to know why that didn’t work?

> what exactly is happening there? I can only guess. The second arg is generally for the flag for opening the file.

http://man7.org/linux/man-pages/man2/open.2.html and http://man7.org/linux/man-pages/man4/tty.4.html may be helpful? It’s really only opening `/dev/tty`, which will refer to the “controlling terminal of a process, if any”, in read/write mode.

**Comment by ORESoftware** [comment]
Ok got it re: read/write mode.

With regard to what didn't work, basically (try not to fall asleep as I write :)

I start a Node.js process A with the shell, which in turn programmatically starts a Node.js child_process B. Process B, in turn, starts a child process C.

I want the stdout/stderr from C to go to the terminal, but I do *not* want the stdout/stderr from B to go to the terminal.

So AFAICT, I have to pass the fd from the current TTY to B, so that it can be passed to C.

If I pass the wrong fd, it won't work. Currently the fd that works is the one given by $tty at the original (and only) terminal in question.

**Comment by addaleax** [comment]
> So AFAICT, I have to pass the fd from the current TTY to B, so that it can be passed to C.

The controlling terminal for processes is something that’s inherited in child processes; you shouldn’t manually *need* to pass anything, and I am not sure why just using `/dev/tty` wouldn’t work.

If you insist on passing fds, nothing is stopping you from passing extra file descriptors in `child_process.spawn` and reordering them as you like; pseudocode:

```js
A: spawn('B', { stdio: [ file, file, file, 0 ] }) // fd #0 is stdin, will become fd #3 in the child
B: spawn('C', { stdio: [ 3, 3, 3 ] }) // fd #3 is the TTY
```

**Comment by ORESoftware** [comment]
Oh nice, are you saying you can do:

cp.spawn('node',[],{
 stdio: [0,1,2,3,4,5,6,7]
});

and keep passing in file descriptors? I thought the order of those was important.

Currently, I am totally ok with using socketio or ipc to pass in the file descriptors that I need.

In fact, I probably need to use socketio/ipc to pass the fd's, because process B starts up only once, but process C are actually multiple different processes and will get launched by different terminals...kind of complicated to explain.

**Comment by addaleax** [comment]
> I thought the order of those was important.

Well… the order is whatever you say the order is? The first three FDs will be stdio, and I know that some ecosystem packages rely on the fact that a fourth FD is the IPC channel, if there is any. But other than that, yeah, you can pass in as many FDs as you’d like.

**Comment by ORESoftware** [comment]
Yeah, I see, got it!

When I use

`var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);`

I got 

```js
const tty = require('tty');
tty.isatty(fd)  // false, not a tty
```

at least in the child process, when I do that, any idea why that might happen?

**Comment by ORESoftware** [comment]
Yeah, I can confirm

```
tty.isatty(fd)  // in process A => true
tty.isatty(fd)  // in process B => false
```

same fd integer value.

**Comment by addaleax** [comment]
> same fd integer value.

Just to be clear, when you pass in `[0, 1, 2, 240]` to `spawn` in the parent process, the child process won’t have an fd `240`; it’s own fd `3` will refer to whatever `240` refers to in the parent process.

> at least in the child process, when I do that, any idea why that might happen?

Not really but at this point it might help to know your OS and/or have some reproducible test case that you’d like to share?

**Comment by ORESoftware** [comment]
yeah, if I ignore the fact that tty.isatty() is false, then I currently get

 `Error: EINVAL: invalid argument, write`

when I call

`fs.createWriteStream(null, {fd: fd});  // in process B`

**Comment by ORESoftware** [comment]
It looks like you're right, if I do

  var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);

or 

  var fd = fs.openSync('/dev/ttys001','a');

I get the same integer value. But if I pass the integer (fd) to the child process, then for some reason it is not recognized as a TTY and if I try to write to by create a write stream I get that EINVAL error, not idea what that is about.

**Comment by addaleax** [comment]
> I get the same integer value

Again; the value returned by `openSync` is completely meaningless. It’s just an identifier for the resource you opened, and you can’t expect FDs in different processes to refer to the same thing.

**Comment by ORESoftware** [comment]
Well, I meant that the two above calls were called in the same process

aka these two calls

var fd = fs.openSync('/dev/tty', O_RDWR + O_NOCTTY);

or

var fd = fs.openSync('/dev/ttys001','a');

**Comment by addaleax** [comment]
Right, but it doesn’t really matter whether they return the same integer value. Whatever these return, they will point to the same TTY (if `ttys001` is the controlling TTY for the process).

**Comment by ORESoftware** [comment]
Ok, but what I need to do - get a handle on the current TTY, and pass its identity to process B. Right now I can't seem to do that. The only way this whole thing works, is if I run $ tty in the terminal and pass that value to process B. And then in process B call fs.openSync($tty);

As we agreed on, if I pass an integer fd from A to B, B will not necessarily recognize that integer (news to me, but I believe you).

What I am doing is working, but it's only working because I manually run $tty.

**Comment by addaleax** [comment]
> get a handle on the current TTY, and pass its identity to process B.

There should be no reason why you can’t get the handle in process B itself?

> As we agreed on, if I pass an integer fd from A to B, B will not necessarily recognize that integer (news to me, but I believe you).

At the risk of repeating myself: When you pass FDs to child processes, they *will* receive them as their index in the `stdio` option for `spawn`, not as the original FD values in the parent process.

**Comment by ORESoftware** [comment]
Right, but I am passing fd's via socketio, not via spawn stdio option :)

**Comment by addaleax** [comment]
> Right, but I am passing fd's via socketio, not via spawn stdio option :)

Uh. That was an important missing bit of context… in that case, yeah, running the `tty` command + passing the name of the returned TTY might be your best bet.

**Comment by ORESoftware** [comment]
That's ok, thank you for helping me, it is a big help. 

But now the problem is, I cannot run the tty command from inside Node.js.

```js
const cp = require('child_process');
const tty = cp.execSync('tty');
```

this does not work. I need something like this to work :/

**Comment by addaleax** [comment]
`const tty = cp.execSync('tty', {stdio:'inherit'});`

**Comment by ORESoftware** [comment]
aha, let's try it

**Comment by ORESoftware** [comment]
That works, and this is a stupid question, I get two lines of stdout:

```js
const cp = require('child_process');
const util = require('util');

const tty = cp.execSync('tty', {stdio:'inherit'});

console.log(util.inspect(tty));
```

not sure how to capture that first line only, never had this problem before :)

**Comment by ORESoftware** [comment]
This doesn't work:

`const tty = String(cp.execSync('tty', {stdio:'inherit'})).split('\n')[0];`

:(

**Comment by addaleax** [comment]
Oh, right. You’ll need to pass `{stdio:['inherit', 'pipe', 'pipe']}`, that’s my bad.

So, `String(cp.execSync('tty', {stdio:['inherit','pipe','pipe']})).trim()` should do.

(But as a general tip: It’s really helpful if you try to say *why* you think that something doesn’t work rather than just saying “This doesn't work:”. :) )

**Comment by ORESoftware** [comment]
Sorry internet died for a second, yes will try to do as best a job explaining why something doesnt work, on the flipside do you mind explaining why using pipe works instead of inherit? I think i can guess why now that i think about it :)

Tested and seems to work, thanks a tonne for your help

**Comment by addaleax** [comment]
`inherit` would set *all* stdio streams to the parent process’es one, including stdout, which is where `tty` writes its output to. But of course, you want to capture exactly that, so `pipe` is the right thing to do there :)

(`stdin` needs to use `inherit` because `tty` uses the standard input FD for finding out to which TTY it is connected)

**Comment by ORESoftware** [comment]
thanks again

**Comment by ORESoftware** [comment]
@addaleax do you know if this info would be available synchronously in the Node runtime?

`const _tty = cp.execSync('tty', {stdio:['inherit','pipe','pipe']});`

seems like if Node.js process was started with a shell, that this info should/would be available without having to start a child process to get the info? (Also, imagining scenarios where the above call might not yield a valid/correct result.)

**Comment by addaleax** [comment]
@ORESoftware If you’re happy with code requiring native modules, here you go: https://github.com/addaleax/ttyname (which works exactly like the `tty` command)

Otherwise I think you’re pretty much stuck with using a child process.

**Comment by ORESoftware** [comment]
cool yeah I will check it out

**Comment by unphased** [comment]
I have a problem that is rather specific, I want to (on macOS and Linux) determine the `/dev/` tty path, because I want to figure out which terminal is currently running the command (so I can drive tmux, specifying the pane, and I can get these terminal handles from tmux in that format). 

That is to say, from a shell I can run `tty` and get back either `/dev/pts/27` on Linux or `/dev/ttys016` on macOS. That's what I want, but I'm doing it inside of a node script now, and spawning `tty` is fruitless.

**Comment by unphased** [comment]
Actually I think the solution i found is to sidestep spawning `tty` by spawning `ps`. Good enough for me...
