### ISSUE TITLE
Unable to run javascript files

### ISSUE THREAD

**Issue by RDjarbeng** [nodejs/help#3670]
### Details

When I try to run javascript files eg: clock.js in my project directory all I get is a node window that just shows a welcome message. I installed node.js months ago. This is the first time I'm trying to use it to run a file directly from terminal

![image](https://user-images.githubusercontent.com/57795443/147682987-fc66b817-ceb5-4e98-b7ab-5a6109dc2e14.png)

### Node.js version

 v12.18.3.

### Example code

`console.log('hello');`

### Operating system

Windows 10

### Scope

code

### Module and version

Not applicable.

**Comment by mhdtjk** [comment]
You should try `node clock.js` command in current directory.

**Comment by RDjarbeng** [comment]
That's what I did, both in the windows command line, powershell and in the
integrated terminal (git bash) in Visual studio code.

I've tried running the command line as administrator as well.
It just opens a new window as shown in the first (gnode.exe) that accepts
node commands on the terminal.
The original window seems to stop/wait until the gnode.exe is closed

**Comment by tniessen** [comment]
There is no `gnode.exe` in the official v12.18.3 distribution. How did you install Node.js?

(v12 is quite old at this point anyway.)

**Comment by RDjarbeng** [comment]
I installed it with the windows installer downloaded from the nodejs website.  I will install the cuurent LTS version to see if it resolves the issue, just wanted to make sure the issue was known.

**Comment by RDjarbeng** [comment]
> I installed it with the windows installer downloaded from the nodejs website. I will install the cuurent LTS version to see if it resolves the issue, just wanted to make sure the issue was known.

* Uninstalled my node js v12.18.3.
* Downloaded the current LTS version v16.13.1

This fixed the issue.

**Comment by tniessen** [comment]
Thanks for reporting back @RDjarbeng!
