### ISSUE TITLE
Bash startup files are not executed

### ISSUE THREAD

**Issue by RyanLeeLY** [nodejs/help#3672]
### Version

v14.17.6

### Platform

Darwin MacBook-Pro-2.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Subsystem

macOS

### What steps will reproduce the bug?

``` SHELL
$ node test.js
```
Bash startup files are not executed as expected. However, if i replace `shell: 'bash'` with `shell: 'zsh'`, startup environment is ok.

```javascript
//  test.js
var cp = require('child_process')
var os = require('os')

let cmd = cp.spawn("printenv", [], {
  shell: 'bash',
  argv0: '-l',
  cwd: os.homedir(),
  detached: false
});
cmd.stdout.setEncoding('utf8');
cmd.stderr.setEncoding('utf8');
cmd.stdout.on('data', (d) => {
  console.log(d);
});
```

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

Bash startup files should be loaded.

[Bash Documents](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html)
> with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists. After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.

**Comment by addaleax** [comment]
It seems very brittle to rely on `-l` being accepted as a valid flag if it is the first argument on the command line (i.e. where usually the executable name would be), and I would recommend not doing that. Maybe this just is a platform-specific behavior difference?
