### ISSUE TITLE
Does React no longer support windows 7 node.js????!?!? 

### ISSUE THREAD

**Issue by mattjaf** [nodejs/help#3677]
### Details

Windows 7
Node 12.13
npm 6.12

So, I created a front-end useDapp a few weeks ago with react ts and it said that I needed an even version of node.js 10^ || 12^ || 14^. I uninstalled 13.xx and downgraded to 12.13. Everything worked, cool! I went to create a new project today and now its saying "Create React App requires Node 14 or higher.", which doesn't make sense b.c I haven't been able to install node 14+ on windows 7?

Pretty much the only major install I did since then was install tuffle globally via yarn. //not sure if thats relevant, might of did something funky with my dependencies? 

  

### Node.js version

12.13

### Example code

npx: installed 67 in 36.823s
You are running Node 12.13.0.
Create React App requires Node 14 or higher.
Please update your version of Node.

### Operating system

Windows 7 64 bit

### Scope

Haven't been able to install node 14+ on windows 7 and react is saying I need node 14+ as of 2022??

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
The latest versions of React dopped support for Node.js v13 and lower versions.

And we no longer provide new Node.js build files for Windows 7 since [Microsoft dropped support for Windows 7](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962) as it reached it's EoL (End-of-Life) phase.

As our building policy states [here](https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
> Node.js does not support a platform version if a vendor has expired support for it. In other words, Node.js does not support running on End-of-Life (EoL) platforms.

**Comment by mattjaf** [comment]
Salam Aliekum,

Do you happen to know of any workarounds?

**Comment by HectorGitt** [comment]
So no way out??

**Comment by mattjaf** [comment]
I'm under the impression, the highest version of windows that my laptop
functionally supports in Windows 7.

**Comment by HectorGitt** [comment]
i thought so to but i eventually updated my windows to window 7 and it works fine

**Comment by Shark11Killer** [comment]
This works for me

npx create-react-app@3.4.0 my-app

the source of my comment:
https://stackoverflow.com/questions/70380801/how-to-use-create-react-app-with-windows-7

**Comment by RedYetiDev** [comment]
Hi! It seems that the question was answered, but if you have further questions about react, please visit its repo.
