### ISSUE TITLE
My NodeJS server stop working in Oracle Free Tier after sometimes.

### ISSUE THREAD

**Issue by githubgist123** [nodejs/help#3681]
### Details

I run my NodeJS server with forever start. But after sometimes it stops. When I run my NodeJS server on my local machine it works normal.
How I recognize after running my NodeJS server in Oracle Free Tier if I run for example htop my NodeJS server works normal until I close or console freeze and after sometime my NodeJS server stops working. I installed in my Oracle Free Tier Ubuntu OS 20.04. Also in my NodeJS code I use mysql. But I am not sure it is related to mysql because I tested every query and it was OK. Only I had crash in my local machine related mysql because after 8 hours wait_timeout occured crash. Also in top of the code I open connection to mysql and never close it. In log forever I don't see nothing related to error. There are only console logs which I added to check state of code.

### Node.js version

node v16.13.1

### Operating system

Ubuntu 20.04

### Scope

Server stops working after sometimes.

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
This version of Node.js is no longer supported, and this may be an issue with your VM instance.
