### ISSUE TITLE
Console halted output after update to 17.3

### ISSUE THREAD

**Issue by zdnk** [nodejs/help#3682]
### Version

17.3

### Platform

Darwin ZMac.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Dec  8 00:40:29 PST 2021; root:xnu-8019.80.11.111.1~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

upgrade to node 17.3
get nestjs started project for example
run `npm run build`

### How often does it reproduce? Is there a required condition?

dont know, seeing this mumbo jumbo in GitHub actions as well as on my machine

### What do you see instead?

whenever i run whatever nodejs app on my machine i see this:
<img width="1274" alt="Screenshot 2022-01-09 at 22 21 21" src="https://user-images.githubusercontent.com/2551911/148701495-9f405e99-4ee9-45ca-b5ea-122aec0148cc.png">

**Comment by Trott** [comment]
@nodejs/npm I'm guessing y'all are aware of this problem, but uh, hey, if you have anything else to add, please do.
