### ISSUE TITLE
http.require not sent directly after function get call, instead will wait for next tick

### ISSUE THREAD

**Issue by yuchihwang** [nodejs/help#3685]
### Details

When executing the below code with `strace -e network node test.js`
It show that the `socket()` `connect()` etc... will be triggered after the CPU bound `busy()` function.
What I expect is that the request will be sent physically first, and then continue on following code, then wait for response event trigger.
Does anyone know why node.js behalf like this?

```js
const http = require('http');

const busy = function(n = 6000) {
    for (let i = 0; i < n; i++) {
        for (let j = 0; j < n; j++) {
            i ** j;
        }
    }
};
const options = {
    hostname: 'www.google.com',
    port: 80,
    method: 'GET',
};

console.log('Request');
http.request(options, res => {
    res.on('end', () => {
        console.log('No more data in response.');
    });
}).end();

console.log('Start busy');
busy();
console.log('End busy');

```

Output
```
# strace -e network node test.js
Request
Start busy
End busy
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 19
connect(19, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("142.251.33.68")}, 16) = -1 EINPROGRESS (Operation now in progress)
getsockopt(19, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
+++ exited with 0 +++
```

I used to suspect maybe it is related to `stream.end()`, so i try this one and still got the same result
```js
const net = require('net');

const busy = function(n = 6000) {
    for (let i = 0; i < n; i++) {
        for (let j = 0; j < n; j++) {
            i ** j;
        }
    }
};

console.log('createConnection');
const client = net.createConnection(
    {
        host: 'www.google.com',
        port: 80,
    },
    () => {
        console.log('connected to server!');
        client.end();
    }
);
client.on('end', () => {
    console.log('disconnected from server');
});

console.log('Start busy');
busy();
console.log('End busy');
```

Output
```
# strace -e network node test.js
createConnection
Start busy
End busy
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 19
connect(19, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("142.250.69.196")}, 16) = -1 EINPROGRESS (Operation now in progress)
getsockopt(19, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
connected to server!
shutdown(19, SHUT_WR)                   = 0
disconnected from server
+++ exited with 0 +++
```

### Node.js version

```
# node -v
v14.17.6
```

### Operating system

```
# uname -a
Linux jukwaa-debug-release20220110172708b2ed23a730-8fdfdfb48-lbr9z 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Scope

runtime

### Module and version

http

**Comment by tniessen** [comment]
> It show that the `socket()` `connect()` etc... will be triggered after the CPU bound `busy()` function. What I expect is that the request will be sent physically first, and then continue on following code, then wait for response event trigger.

IO happens in the background. Anything else could lead to significant delays. For example, the DNS query that determines the IP address for a given host could potentially take seconds. Node.js does all that in the background and keeps running your code to avoid such delays.

**Comment by yuchihwang** [comment]
I also try to directly put up address there, but the results still the same.
Can think of another I/O operation and the full strace output also don’t
have any network related syscall before that too.

Tobias Nießen ***@***.***>於 2022年1月12日 週三，上午2:05寫道：

**Comment by yuchihwang** [comment]
I found why using ip will still have this situation, because nodejs will always handle the request on next tick here
https://github.com/nodejs/node/blob/4673ee11a377dcbc7228b6a3992467eca1b43654/lib/net.js#L1009

Even if we use http.Agent keepalive to keep the connection, this still happens because of onScoketNT here
https://github.com/nodejs/node/blob/4673ee11a377dcbc7228b6a3992467eca1b43654/lib/_http_client.js#L813

**Comment by yuchihwang** [comment]
@tniessen 
I found why using ip will still have this situation, because nodejs will always handle the request on next tick here
https://github.com/nodejs/node/blob/4673ee11a377dcbc7228b6a3992467eca1b43654/lib/net.js#L1009

Even if we use http.Agent keepalive to keep the connection, this still happens because of onScoketNT here
https://github.com/nodejs/node/blob/4673ee11a377dcbc7228b6a3992467eca1b43654/lib/_http_agent.js#L267
https://github.com/nodejs/node/blob/4673ee11a377dcbc7228b6a3992467eca1b43654/lib/_http_agent.js#L492
https://github.com/nodejs/node/blob/4673ee11a377dcbc7228b6a3992467eca1b43654/lib/_http_client.js#L813

There seems to be no I/O work here, why we need to have next tick here?

**Comment by tniessen** [comment]
> There seems to be no I/O work here, why we need to have next tick here?

For example, so you can set up event listeners, including an error listener, before any IO events can occur.

If Node.js performed any syscalls related to the network socket synchronously (i.e., before `nextTick`), they might fail or cause other events to be emitted before you have a chance to register any event/error listeners.

**Comment by yuchihwang** [comment]
@tniessen  Oh, that makes sense. But what if there are CPU-bound tasks there, then the HTTP request will be delayed a lot.
My ideal is that I can send the request first, and then proceed on some CPU-intensive task, then when the task is finished, the request might probably also be finished. So that I can save a lot of time there. Is there any workaround here?

**Comment by tniessen** [comment]
> But what if there are CPU-bound tasks there, then the HTTP request will be delayed a lot.
My ideal is that I can send the request first, and then proceed on some CPU-intensive task, then when the task is finished, the request might probably also be finished. So that I can save a lot of time there. Is there any workaround here?

Yes. If you do _any_ IO on the main thread (including HTTP requests), then you should _never_ do CPU-bound tasks on the main thread. Use [Worker threads](https://nodejs.org/api/worker_threads.html) instead. That way, your main thread will always remain responsive.

**Comment by yuchihwang** [comment]
@tniessen Oh actually I'm not trying to do CPU-bound tasks. Just because there will be many trivial tasks to do and many requests in the main thread, they are not very CPU intensive, but they are not optimized yet and will last around 100ms.
So if the request actually need 200ms, then there will be total 300ms latency. My ideal is to have 200ms latency e2e.

**Comment by tniessen** [comment]
> they are not very CPU intensive, but they are not optimized yet and probably not suitable for using worker threads and will last around 100ms.

100ms is an eternity for a computer.
- Let's say your CPU runs at about 3 GHz per core, then 100ms are about 300 million CPU cycles!
- In the same time, optical fiber would have transferred your data half way around the globe.
- A Fast-Ethernet connection (100 MBit/s) could have transferred more than a million bytes of data in that time.
- An SSD could deliver hundreds of millions of bytes in that amount of time.

The main strength of Node.js is its ability to provide excellent IO performance. But not if the main thread is blocked.

**Comment by tniessen** [comment]
Closing as answered. Please feel free to comment or reopen if you feel that this warrants more discussion :)
