### ISSUE TITLE
Node 0.12.7 application making https request to literal ipv6 address fills in servername wrong

### ISSUE THREAD

**Issue by decarbureted** [nodejs/help#369]
I'm working on an application on Node 0.12.7.  Yes, an upgrade is overdue, and I'm working that angle as well, but for now I need to deal with that revision, as I can't be certain that an upgrade will be possible in our target environment for technical and (mostly) non-technical reasons.

The issue that I have is this:  My Node application needs to communicate with an HTTPS server via an IPv6 literal address (example url = https://[2001:DB8::1]/api/things).  It also needs to do this via an IPv4 literal address, and that works fine.  In both cases, if I sniff the packets on the wire, I see the server_name extension header specified in the Client Hello.  For IPv4, it puts the IPv4 address as the servername.  For IPv6, the servername is "2001", and therefore Apache on the server rejects the connection because the SNI name doesn't match the hostname.

What I've learned is that, with a newer version of Node (4.something), I can specify "2001:DB8::1" as the servername, and that works around the issue.  But that option isn't available on the HTTPS agent in 0.12.7.

I then tried to backport that functionality, thinking that this was the commit that fixed it:
https://github.com/nodejs/node/pull/4389/commits/48864f08526e26dab7b2fcdb9e6704cd8291ffb1

Unfortunately, I don't know if that commit isn't a complete fix, or if I simply didn't build this correctly.

1.  Setting the obvious upgrade discussion aside, am I going down the right path to fix this issue?
2.  How can I figure out if the patch I did is in the code on my target?  I was hoping I could find lib/https.js somewhere on the target so that I could either see my changes or insert some log messages, but that apparently isn't an option.

The final complicating issue for me is that I hadn't touched JS at all before this year, so I suspect there could be some things I'm not yet understanding.

**Comment by decarbureted** [comment]
Example code to show the original problem:

// request
var axios = require('axios');

// allow self-signed certs for now
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

axios.get('https://[2001:DB8::1]/')
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })

And I've learned a little more... with Node 0.12.7, the SNI extension sends the server name as "2001", but with 6.9.1 it sends "[2001".

**Comment by decarbureted** [comment]
I've applied this fix to my 0.12.7 test environment, and that got me a little farther:
https://github.com/nodejs/node/commit/8453fbc8799cef98697f96be0e2f75f0fc021e41

Now something is looking up the address as though it's a hostname.  I suppose I got around the original problem I posted about, but I'll update as I figure out the rest of this process.

**Comment by TheAlphaNerd** [comment]
is there a reason you can't update to latest v0.12?

**Comment by decarbureted** [comment]
Yeah, our target environment requires FIPS and must remain RHEL-compatible (openssl 1.0.1).  v0.12.8 shifted to openssl 1.0.2, if I recall correctly.  That's what has us stuck on 0.12.7.  I think I see a way for us to get beyond that, but I'm not a team of one, so at best that's going to take time.

**Comment by bnoordhuis** [comment]
The v0.12 releases all use openssl 1.0.1, it's v4 and newer that switched to 1.0.2.

**Comment by decarbureted** [comment]
Thanks for the correction... I clearly misread or misremembered one of the many pages I looked at.  In which case, I don't have a clear answer as to why we haven't upgraded to 0.12.17, then, other than perhaps some confusion over our requirements.

In any case, I just did a quick test with 0.12.17, and that doesn't solve my problem, so my priorities are:
1: Pursue a workaround to getting this scenario to work while pursuing an upgrade to Node v6.
2: Upgrade to 0.12.17. (the "better than nothing" plan)

**Comment by decarbureted** [comment]
For anyone following along, this was the last change I needed to back port to ensure that the IPv6 address wasn't interpreted as a hostname to be looked up via DNS:

https://github.com/nodejs/node/commit/1bef71747678c19c7214048de5b9e3848889248d
