### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by hy721** [nodejs/help#3690]
### Details

unable to allow to access permission after downloaded  Node js for my react project, on the device of macOS Monterey, version 12.1. (updated). No access allow when changed as an admin. 

How can I fixed the issue and gain permission.  

Please advice. 

Thank you

HY

### Node.js version

node v16.13.2

### Example code

~$npm i -g create-react-app/usr/local/bin
zsh: permission denied: 

### Operating system

macOS Monterey 12.1

### Scope

my MacBook unable to get permission to access node js

### Module and version

Not applicable.

**Comment by marsonya** [comment]
How did you install node? Was it `.pkg` from the website or did you use `homebrew`?

**Comment by hy721** [comment]
Hi Akhil,

I installed it at home, device is MacBook Pro M1 latest updated.

Helen
________________________________

**Comment by marsonya** [comment]
It seems like a permissions issue with the npm's default directory.
You can try and fix it by following the instructions [here](https://stackoverflow.com/questions/47252451/permission-denied-when-installing-npm-modules-in-osx).

Alternatively, a good idea would be uninstalling the Node on your MacBook and then installing it again.
This time using `Homebrew`
To install using Homebrew use the command `brew install node`.
Homebrew sets things up out of the box with the correct permissions.

Hope it helps.

**Comment by AbdullahRumayah** [comment]
package.json | npm Docs

Don't put "js" or "node" in the name. It's assumed that it's js, since
you're writing a package.json file, ...


Pada Jum, 21 Jan 2022, 4:59 PTG akhil marsonya ***@***.***>
menulis:

**Comment by AbdullahRumayah** [comment]
Resolving EACCES permissions errors when installing packages ... If you see
an EACCES error when you try to install a package globally, you can either:
Reinstall npm with a node ...

Pada Jum, 21 Jan 2022, 8:46 PTG Abdullah Rumayah ***@***.***>
menulis:
