### ISSUE TITLE
facing less errror with unhandled promise exception in angular version 10 ( trying to upgrade from version 9 to version 12 )

### ISSUE THREAD

**Issue by bxdadwhal** [nodejs/help#3692]
### Details

Description:
error :- Compiling ngx-bootstrap/tooltip : es2015 as esm2015
Compiling ngx-bootstrap/dropdown : es2015 as esm2015
50% building 134/135 modules 1 active ...es\less-loader\dist\cjs.js??ref--14-3!C:\Users\bdadwhal-etc\angular-migration8.1\src\styles.less(node:1588) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:124:11)
at Object.normalize (path.js:300:5)
at new LessError (C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\LessError.js:15:169)
at C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\index.js:62:14
(Use node --trace-warnings ... to show where the warning was created)
(node:1588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Node.js version

v14.17.3

### Example code

i started from upgrading from angular version 4 to 12 , so far i have been able to compile the code in pipeline and build artifact on nexus and then deploy successfully the angular 9 version artifact with unit tests passing on vm but stuck on 10 version , my goal is to deploy angular version 12 , currently facing above error , my package.json looks like this :-

{
"name": "gd",
"version": "2.0.0",
"engines": {
"node": "6.11.0",
"npm": "3.10.10"
},
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build --prod",
"test": "ng test",
"lint": "ng lint --type-check",
"e2e": "ng e2e",
"serve": "ng serve --proxy-config proxy.conf.json",
"coverage": "ng test --code-coverage --reporters=coverage-istanbul"
},
"private": true,
"dependencies": {
"@angular/animations": "~10.2.4",
"@angular/common": "~10.2.4",
"@angular/compiler": "~10.2.4",
"@angular/core": "~10.2.4",
"@angular/forms": "~10.2.4",
"@angular/http": "7.2.16",
"@angular/material": "^13.1.2",
"@angular/platform-browser": "~10.2.4",
"@angular/platform-browser-dynamic": "~10.2.4",
"@angular/router": "~10.2.4",
"@ngrx/store": "4.1.0",
"core-js": "2.5.1",
"dexie": "2.0.1",
"tslib": "^2.0.0",
"immutable": "3.8.2",
"lodash": "4.17.4",
"ngx-bootstrap": "^6.2.0",
"pouchdb-browser": "6.3.4",
"rxjs": "~6.6.0",
"zone.js": "~0.10.2",
"rxjs-compat": "^6.0.0-rc.0"
},
"devDependencies": {
"@angular-devkit/build-angular": "~0.1002.3",
"@angular/cli": "~10.2.3",
"@angular/compiler-cli": "~10.2.4",
"@types/node": "^12.11.1",
"@types/jasmine": "~3.5.0",
"angular": "1.6.6",
"angular-in-memory-web-api": "0.4.6",
"angular-mocks": "1.6.6",
"angular-route": "1.6.6",
"angular-sanitize": "1.6.6",
"bootstrap": "3.3.7",
"codelyzer": "3.2.2",
"concurrently": "3.5.0",
"font-awesome": "4.7.0",
"grunt": "1.0.1",
"grunt-bower-task": "0.5.0",
"grunt-cli": "1.2.0",
"grunt-concurrent": "2.3.1",
"grunt-contrib-clean": "1.1.0",
"grunt-contrib-concat": "1.0.1",
"grunt-contrib-copy": "1.0.0",
"grunt-contrib-jshint": "1.1.0",
"grunt-contrib-less": "1.4.1",
"grunt-contrib-uglify": "3.1.0",
"grunt-contrib-watch": "1.0.0",
"grunt-exec": "3.0.0",
"grunt-open": "0.2.3",
"grunt-text-replace": "0.4.0",
"istanbul": "0.4.5",
"@types/jasminewd2": "~2.0.3",
"codelyzer": "^6.0.0",
"jasmine-core": "~3.6.0",
"jasmine-spec-reporter": "~5.0.0",
"jquery": "2.2.4",
"karma": "~5.0.0",
"karma-chrome-launcher": "~3.1.0",
"karma-cli": "1.0.1",
"karma-coverage": "1.1.1",
"karma-coverage-istanbul-reporter": "~3.0.2",
"karma-htmlfile-reporter": "0.3.5",
"karma-jasmine": "~4.0.0",
"karma-jasmine-html-reporter": "^1.5.0",
"karma-phantomjs-launcher": "1.0.4",
"karma-requirejs": "1.1.0",
"karma-sonarqube-unit-reporter": "0.0.13",
"load-grunt-tasks": "3.5.2",
"protractor": "~7.0.0",
"requirejs": "2.3.5",
"time-grunt": "1.4.0",
"ts-node": "~8.3.0",
"tslint": "~6.1.0",
"typescript": "~4.0.2"
}
}

### Operating system

windows 

### Scope

compilation error

### Module and version

angular 10 version

**Comment by marsonya** [comment]
Hi @bxdadwhal, the Angular [issues](https://github.com/angular/angular/issues) section would be the best place to get help for this one.
