### ISSUE TITLE
Copy *.node addon compiled file from compiling machine to another machine (client) same system 

### ISSUE THREAD

**Issue by mohammadmoth** [nodejs/help#3694]
### Details

Hallo all,

I would like to  (windows server 2019)  machine  compile the source file to a node file and run it on the same system as the Windows machine (windows server 2019, windows 10, windows 11).

For example after building an addon
It will create the following files:

addon.node
addon.pdb
addon.lib
addon.ilk
addon.exp

I will include it directly with my node project. 

my questions:
1. Is this safe?
2. Is this stable?

Thank you all

### Node.js version

V14

### Operating system

Windows 10 x64 or x86, 11 x64 or x86 and  Windows Server 2019 x64 or x86

### Scope

Runtime

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
yes and yes. Ideally we need `addon.node` for the production, but there is no known side effect of keeping the other items in the location.

**Comment by mohammadmoth** [comment]
Thank you very much for your quick reply

**Comment by mohammadmoth** [comment]
I would like to reopen issue. 
Because there is a new variable in this issue .

When compile the source file to a node file
We are using Node 14.16.1 32

at the party (client)
Node version 14.18.3 32  or 14.18.2 32 used

The same as the previous two questions, is there any change in your answer?

Thank you

**Comment by gireeshpunathil** [comment]
@mohammadmoth - still the answer remains same - yes and yes.

however, if the major version changes (the first token in the version string) then the source and target may become incompatible. here as that is not the cause, it would still work.

**Comment by mohammadmoth** [comment]
Thank you very much
