### ISSUE TITLE
Is it possible to reconfigure the global console so _all_ methods write to process.stderr?

### ISSUE THREAD

**Issue by zackw** [nodejs/help#3697]
### Details

I am writing a program that, in the traditional Unix fashion, sends its primary output to `process.stdout`.  I would like to be able to ensure that libraries I use do not accidentally corrupt this output by use of e.g. `console.log`.  The natural way to do this, it seems to me, would be to reconfigure the global console object so that _all_ of its methods write to `process.stderr`.

Is this possible?  I know I can create a new Console object myself that writes whereever I want it to, but I don't see any way to replace the original global console object with that.

### Node.js version

 ≥ 16

### Operating system

Linux is primary for this application, but I am interested in an answer that works on all platforms if possible.  If _all_ is not possible, then I am interested in an answer that works on everything except Windows.

### Scope

code / runtime library

### Module and version

Not applicable.

**Comment by zackw** [comment]
According to https://nodejs.org/docs/latest/api/console.html there is still no documented way to reconfigure the global console object, so this is still a live feature request and should remain open.

In general, auto-closing issues for inactivity is user hostile, please stop doing it.

**Comment by RedYetiDev** [comment]
> According to https://nodejs.org/docs/latest/api/console.html there is still no documented way to reconfigure the global console object, so this is still a live feature request and should remain open.

To achieve this result, you can make a new Console instance, and set the stdout property to stderr

> In general, auto-closing issues for inactivity is user hostile, please stop doing it.

I'm sorry you feel that way, but marking issues as stale is helpful for maintenance, as it keeps active issues open, and inactive ones closed.

**Comment by zackw** [comment]
>> there is still no documented way to reconfigure the global console object, so this is still a live feature request and should remain open.
>
> To achieve this result, you can make a new Console instance, and set the stdout property to stderr. 

Creating a new Console instance doesn't affect the *global console object*, right?  So I don't see how that would help?

> marking issues as stale is helpful for maintenance

It's still user hostile and you shouldn't do it.  The bug tracker is one of your most important public faces. Your internal convenience is less important than presenting a friendly face to people who have gone to the trouble of contacting you to report an issue, no matter how long ago that was.

The **only** non-user-hostile process for dealing with old bugs is manual. You have to actually check them, one by one, and find out for yourself whether they are still valid. For each one, you write a personalized note explaining what you found. You close only the bugs that have already been fixed or have been rendered moot by other changes. You note that unreproducible bugs are unreproducible, but you don't close them until the original reporter has been given *at least* three more months to come up with a repro recipe. And for what's still valid, you note that the issue has been confirmed as of [date] and any details you can add.

If you don't have the people power to do that, then you should leave old bugs open indefinitely. You can automatically tag them as "needs attention" or something based on elapsed time and/or releases, but that's the only automatic action you should ever take based on a bug's "age."

**Comment by RedYetiDev** [comment]
As of now, like I mentioned earlier, there is no way to achieve this (AFAIK). If you'd like to suggest a method, you can open a feature request against the main repo.

As for your concern with stale issues, please open a separate issue, as it is off topic to the current issue

**Comment by RedYetiDev** [comment]
*(help wanted from: @nodejs/console)*

**Comment by RedYetiDev** [comment]
After some source searching, I don't think this sort of feature will be added to Node.js, for both logistical reasons, and a lack of use-cases.

If you believe that you have valid use cases that would imply this feature is needed in the core, please open a feature request against the main repository.
