### ISSUE TITLE
NAPI segmentation fault on Arm

### ISSUE THREAD

**Issue by niyan-ly** [nodejs/help#3698]
### Version

v16.13.2

### Platform

Darwin YongLins-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

### Subsystem
macOS Monterey 12.1

### Background
I ran this test on the m1 macbook, got `segmentation fault` error. Then I pulled the `latest` official node docker image, still got same error. It seems more like an `arm-build` related issue, node-v14 on m1 still got the same error. But it works well on x64 linux(debian 9).

The key point is, if we switch the line `code-a` and `code-b`, which means create js_array before get_cb_info, then everything works well.

### Step to reproduce
copy these 3 files, `code.c` `test.js` `binding.gyp`.
1. run `node-gyp configure`
2. run `node-gyp rebuild`
3. run `node test`

### Result
<img width="475" alt="image" src="https://user-images.githubusercontent.com/28030655/150563320-ac46b4e8-dd14-45c4-a74a-369ff8451da1.png">

```gyp
{
  "targets":[
    {
      "target_name": "code",
      "sources": ["code.c"]
    }
  ]
}
```

```js
// test.js
const addon = require("./build/Debug/code.node");

console.log(addon.return_args('kl'));
```

```c
// code.c
#include <node_api.h>

napi_value return_args(napi_env env, napi_callback_info info)
{
  napi_value list, binding, new_list;
  size_t len = 4;

  napi_get_cb_info(env, info, &len, &list, &binding, NULL); // code-a
  napi_create_array(env, &new_list); // code-b

  return new_list;
}

napi_value Init(napi_env env, napi_value exports)
{
  napi_value s_return_args, f_return_args;

  napi_create_string_utf8(env, "return_args", NAPI_AUTO_LENGTH, &s_return_args);
  napi_create_function(env, "return_args", NAPI_AUTO_LENGTH, return_args, NULL, &f_return_args);

  napi_set_property(env, exports, s_return_args, f_return_args);
  return NULL;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
```

### How often does it reproduce? Is there a required condition?

stable reproducible.

### What is the expected behavior?

code should be compile and execute successfully.

### What do you see instead?

segmentation fault.
<img width="475" alt="image" src="https://user-images.githubusercontent.com/28030655/150564919-9965677b-3385-473a-b42f-dbda54cfc502.png">

**Comment by mhdawson** [comment]
Create PR to try to clarify - https://github.com/nodejs/node/pull/41635

**Comment by niyan-ly** [comment]
@addaleax thank you, I should have read the doc more carefully before open this issue. Anyway, thank you for your detailed explanation.
