### ISSUE TITLE
use npm XLSX module with stream

### ISSUE THREAD

**Issue by morfies** [nodejs/help#37]
my use case is supporting import&export for certain search page. As for export:

Currently I am able to retrieve query result, form the data into a workbook object and then use XLSX to writeFile to a xlsx file on server and then send this file back to browse for user to download.(This works, but I donot want to generate a file on server)

As for import: Browser upload the xlsx file through fileupload, and node server receive the file by busboy middleware, but again, how can I just pipe the file data to XLSX directly and then I can parse this data into json, eventually put the uploaded data to mysql?

Thanks very much if you can give me some advice on this.

**Comment by Trott** [comment]
Can you show the code you have (that doesn't use streams but otherwise works) and/or the code you've tried with streams that doesn't work?
