### ISSUE TITLE
Node.js does not detect the HTML files link in the href when a href containing html is served

### ISSUE THREAD

**Issue by nileshgiri34** [nodejs/help#370]
Node.js is always used to deliver the HTML files. But currently I am facing an issue where after serving the HTML with href links. The links do not work and we dont get to see the results. This called out a lot of research in web development.

`<a href="HTML1.html"><img src="D:\projectbase\maxresdefault.jpg" alt=""><span class="project-label">AC Legacy</span></a>`

What it should do is on clicking the image it should open the html1.html. It works properly when it is just loaded outside the node.js environment. But it does not work when we serve it thru Node.js.

I hope we can have discussions or answers for this.

**Comment by kahwee** [comment]
I don't think this is specifically a nodejs issue. 

Can you compare the HTML output of the nodejs server with your above HTML?

**Comment by lordKnighton** [comment]
Have you tried naming it `index.html` in lieu of `html1.html`  
 
--
![screen shot 2016-11-19 at 2 58 24 pm](https://cloud.githubusercontent.com/assets/1773260/20459018/d4d22af2-ae68-11e6-96d9-d3eacf182aae.png)

**Comment by nileshgiri34** [comment]
@kahwee @lordKnighton  it seemed like a problem of node.js. bcz in my IDE it behaved like it. Outside the node.js env it was working fine and links were working too.

I hv been using different server since then. But I would like to see it solved thru.
Let me know if anymore info is required. I m using vs2012, and its node.js tools

**Comment by lordKnighton** [comment]
I'd like you to change this

<a href="HTML1.html">   `to`  <a href="index.html">

Let me know the response of this.

**Comment by lordKnighton** [comment]
Change the backslash (\) to forward slashes (/) and add file:/ before the path, so:

**Comment by lordKnighton** [comment]
Gonna close for now, but let me know, if it didn't help, we will reopen & go from there 

👍  happy coding

**Comment by rajus0007** [comment]
Same problem here
Cannot get /howitworks.html

<li><a href="howitworks.html">How it works</a></li>

I'm using express and it can't open that html file which is in the same directory.

**Comment by rajus0007** [comment]
Oh just solved it....
Here is my static file directory notation in app.js in express
app.use(express.static(__dirname + '/public'));

all my html files are in /public/html/ directory. So in the link

//<li><a href="howitworks.html">How it works</a></li>
it should be
//<li><a href="html/howitworks.html">How it works</a></li>
just html/ should be added before howitworks.html to match the path.
