### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by fluentwind** [nodejs/help#3703]
### Version

12.22.0 32bit

### Platform

windows 10 20H2 x64

### What steps will reproduce the bug?

const test = async function (b1) {
  b1 = Buffer.concat([b1, Buffer.from('\n')])
  b1 = Buffer.concat([b1, Buffer.from('\n')])
  b1 = Buffer.concat([b1, Buffer.from('\n')])
  b1 = Buffer.concat([b1, Buffer.from('\n')])
  return b1
}
const test2 = async () => {
  let b1 = Buffer.alloc(1024 * 1024 * 300, '1')
  console.log(b1.length)
  b1 = await test(b1)
  console.log(b1.length)
}
test2()

### How often does it reproduce? Is there a required condition?

Most time

### What is the expected behavior?

Run successfully and print
314572800
314572804

### What do you see instead?

UnhandledPromiseRejectionWarning: RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at createUnsafeBuffer (buffer.js:152:12)
    at allocate (buffer.js:422:10)
    at Function.allocUnsafe (buffer.js:387:10)
    at Function.concat (buffer.js:567:25)
    at test (C:\Users\fluentwind\WebstormProjects\esign\test\testBuffer.js:3:15)
    at test2 (C:\Users\fluentwind\WebstormProjects\esign\test\testBuffer.js:11:14)
    at Object.<anonymous> (C:\Users\fluentwind\WebstormProjects\esign\test\testBuffer.js:14:1)

### Additional information

I want to concat a buffer and get a full buffer.

But memory usage never goes down. Is there anything wrong with gc?

**Comment by marsonya** [comment]
Have you tried allocating a smaller buffer than `1024 * 1024 * 300`?
Looks like you do not have enough memory to handle your buffer size.

**Comment by gireeshpunathil** [comment]
@fluentwind - is this resolved?

**Comment by darrylsepeda** [comment]
Hello, I'm using NextJS with webpack and got this issue when I run `npm run dev`.
![image](https://user-images.githubusercontent.com/5493333/188365349-329e9fe9-7d0d-4bbb-9861-b63e88259ac9.png)
![image](https://user-images.githubusercontent.com/5493333/188365225-a992b609-96b4-4018-83bf-30a34c82ead9.png)
Please let me know what is the issue and how to solve this. Thanks in advance!
