### ISSUE TITLE
Use async_hooks to access store in different module

### ISSUE THREAD

**Issue by akravets** [nodejs/help#3705]
### Details

When initializing store using AsyncLocalStorage, I'd like to access store stored in ALS in different module by executing `const store: any = storage.getStore();`, however as per async_hooks documentation this returns `undefined`. Store needs to be accessed in middleware and in individual modules as well. What is the correct way to achieve this?

### Node.js version

v 17.3

### Example code

**storage.js**
```js
import { AsyncLocalStorage } from 'async_hooks'
export const storage = new AsyncLocalStorage()
```

**express.js**
```js
import { storage } from './utils/storage'

App.use((req, res, next) => {
    const store = new Map();

    storage.run(store, () => {
       store.set("userName", "Bob");
       next();
    });
})
```
**module.js**
```js
  import { storage } from './utils/storage'

  const store: any = storage.getStore(); // undefined

  storage.run(store, () => {
     const userName = store.get("userName")
  });
```

### Operating system

Ubuntu 20.04

### Scope

Express server

### Module and version

Not applicable.

**Comment by Qard** [comment]
You need to use `storage.getStore()` from somewhere that is in some way called within the path of that request. So say `module.js` exported _another_ middleware like:

```js
module.exports = (req, res, next) => {
  const store = storage.getStore()
  const userName = store.get('userName')
}
```

If you attached that middleware after the other one, it will be able to retrieve that username.

Keep in mind that AsyncLocalStorage is _designed_ such that the store is only accessible from within the async call graph descending from where it is run, meaning it encapsulates that request and can be accessed anywhere within that request, but outside of the sequence of calls and events within that request there is no way to access it.

**Comment by akravets** [comment]
@Qard Thanks. Can you elaborate on **from somewhere that is in some way called within the path of that request**, so let's say I have router that calls a controller and that controller calls some service object, and at each point store needs to be access in these modules.
Taking in consideration your last paragraph, should I be looking at some other way to achieve my task?

**Comment by akravets** [comment]
>You should be able to just call `storage.getStore()` in your controller or service object code wherever it's getting called from the router. 

Do you mean this that if I set store in the router, and controller's method is called directly from the router, that method has access to the store? Is this tied with chaining middlewares together in your first comment?

>Which is to say, don't try to use `storage.getStore()` at the top-level, you already have a reference to the storage object. 
What you want is a reference to the store for that request so you have to get it (with `storage.getStore()`) _within_ that request somewhere.
Sorry I don't understand this part, can you elaborate on this?

**Comment by Qard** [comment]
Yes, that router method would have access to the store. All you would need to do is call storage.getStore() inside that method to access it. You just can't have that getStore call in an area outside of what was directly or indirectly _called_ by whatever code did the storage.run(...). So in this case, the next function is run inside that, so any following middleware would have that access as would any callbacks from async calls made in those middleware or descending from any of those callbacks.

**Comment by akravets** [comment]
Thank you for detailed explanation @Qard
