### ISSUE TITLE
Expired timer execution when scheduled during a timer

### ISSUE THREAD

**Issue by renatomariscal** [nodejs/help#3706]
### Details

If a timer is scheduled during a timer execution, is it possible it will get executed before the event loop move to other phases, or is it guaranteed that new timers will yield to other phases?

### Node.js version

v12.14.0

### Example code

```js
setTimeout(() => {
    // Here we are on the "timers" phase
    console.log('setTimeout-1');

    // A new timer is scheduled, set to be expired immediatelly
    setTimeout(() => {
        // Here we are on the timers phase.
        console.log('setTimeout-2');
    }, 0);
    
    // lock the thread for 1 ms to ensure that expiration evaluation doesn't get an off-by-one error
    lock(1);

    // This is executed 
    setImmediate(() => {
        // This is executed in check phase
        console.log('immediate');
    })
}, 0);


function lock(duration) {
    const start = Date.now();
    while (start + duration > Date.now()) { };
}
```

It produced for me consistently the log:
```
setTimeout-1
immediate
setTimeout-2
```

So, is that official, that I can rely on?

### Operating system

MacOS

### Scope

runtime

### Module and version

Not applicable.

**Comment by marsonya** [comment]
Your results are right.
Checkout this documentation: 
https://nodejs.dev/learn/understanding-setimmediate

For more details see:
https://nodejs.dev/learn/the-nodejs-event-loop

**Comment by renatomariscal** [comment]
Thanks for replying @marsonya! I have read the links you have posted, and also this one https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/ which I believe to explain a bit more in depth the event loop.

But I think none of them are clear about how a timer is handled from another timer execution, if they are required or not to wait until the next loop.
