### ISSUE TITLE
Uninstalled completly to install another version node version but it keep showing the previous version

### ISSUE THREAD

**Issue by theryantellem** [nodejs/help#3707]
### Details

I uninstall my node version 17.0.1 lastest features version to install the LTS version, but its keep showing the former version 17.0.1 even after i uninstalled it and installed new version...

### Node.js version

v 17.0.1

### Operating system

Last login: Wed Jan 26 12:26:16 on ttys000
➜  ~ node --version
v17.0.1
➜  ~ 

### Scope

Last login: Wed Jan 26 12:26:16 on ttys000
➜  ~ node --version
v17.0.1
➜  ~ 

### Module and version

node js version 17.0.1

**Comment by VoltrexMaster** [comment]
If the previous version keeps showing up after you've uninstalled the previous version and installed a newer version, I recommend closing your terminal shell and starting a new one and see if it resolves the newer version, if not, try restarting your machine/device/whatever and see if it resolves the newer version, or try uninstalling again and installing the newer version after restarting and see if it resolves the problem.

**Comment by gireeshpunathil** [comment]
@theryantellem - is this resolved?
