### ISSUE TITLE
Uncaught syntaxError: Token.deployed is not a function

### ISSUE THREAD

**Issue by royal3lau** [nodejs/help#3708]
### Details

Trying to put in function

truffle (development)>
```js
const token = await Token.deployed()
```

but I keep getting
```js
Uncaught TypeError: Token.deployed is not a function
    at evalmachine.<anonymous>:1:15
```

Below is a copy of my migration files.
1_initial_migration.js
```js
const Migrations = artifacts.require("Migrations");

module.exports = function (deployer) {   deployer.deploy(Migrations);
};
```

2_deploy_contracts.js
```js
const Token = artifacts.require("Token");

module.exports = function (deployer) {   deployer.deploy(Token); };
```

### Node.js version

Not applicable.

### Operating system

Windows 10

### Scope

Code

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Hi! These issues appear to be with a third party package. Please file an issue at their repo.
