### ISSUE TITLE
issue starting npm

### ISSUE THREAD

**Issue by dlipiz** [nodejs/help#371]
Im migrating a parse db and server. When in the Parse sever dir and attempting to run npm run start i get the following errors.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/DimasImac/Documents/Development/Parse/npm-debug.log
Dimas-Imac:Parse DimasImac$ 

Please help. Im fairly new to this and Im not too sure how to proceed. Thanks

**Comment by addaleax** [comment]
Can you run `node index.js` manually in that directory?

**Comment by lordKnighton** [comment]
Let's see your `scripts` then, you should fine them in your `package.json` file

--
Here is an example of one my `scripts`, located in package.json 
![screen shot 2016-11-19 at 3 06 44 pm](https://cloud.githubusercontent.com/assets/1773260/20459051/f99eabe8-ae69-11e6-8cb9-c0a1deade37a.png)

**Comment by lordKnighton** [comment]
@dlipiz You've solved this issue?
