### ISSUE TITLE
Problem when building an app.

### ISSUE THREAD

**Issue by thisiseesmaeel** [nodejs/help#3711]
### Details

I am trying to build an app but i keep getting the same error. I use Intellij IDEA as IDE and JDK 17. 

### Node.js version

v17.4.0

### Example code

<img width="1061" alt="Screenshot 2022-01-28 at 14 51 11" src="https://user-images.githubusercontent.com/76204917/151565261-019e0e10-8066-48d1-b588-181278011ff9.png">

### Operating system

MacOS 12.2

### Scope

Runtime. 

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Hi! It's hard to see exactly what went wrong here, and it looks like your trying to do something with Node.js and Java. We can't really provide support on the specifics between the two, as it may vary from system to system.
