### ISSUE TITLE
ERR! Cannot read properties of undefined (reading 'isServer')

### ISSUE THREAD

**Issue by Xenonar** [nodejs/help#3714]
### Details

I try to uninstall completely from other issues that has been open and solved such as [https://github.com/nodejs/help/issues/3660](url) and other solutions in google but still have the same issue. Even if I try to force install or `npm cache clean --force ` before install
![image](https://user-images.githubusercontent.com/3455784/151855978-43cd862b-8cff-4e52-a8d3-39ba4ff48178.png)

I need help.

### Node.js version

node version
v16.13.2

npm version
8.1.2

### Operating system

Windows 10 Pro
64-bit operating system, x64-based processor

### Scope

to run Next.js typescript project and even create-react-app also not working

### Module and version

v16.13.2

**Comment by udisun** [comment]
same happens for me

**Comment by RedYetiDev** [comment]
Hi! This seems like an issue with a dependency, and not Node.js itself
