### ISSUE TITLE
What is "option value 8.15.0"?

### ISSUE THREAD

**Issue by Masako-Maggie** [nodejs/help#3715]
### Details

I tried to create environment with AWS ElasticBeanstalk. The code is https://github.com/awsinAction/code2 from the book of "Amazon Web Services in Action, 2nd Edition," and I was trying to do Chapter 5 - create a Etherpad application with ElasticBeanstalk. After conducting the code accordingly based upon the book, I got the error from AWS. How could I fix it? What I tried to do is to reinstall the appropriate version of Node.js, but it didn't work. 
![error](https://user-images.githubusercontent.com/65614664/152154658-f2df854d-eb8c-4172-877e-9172d56aacc7.PNG)

### Node.js version

Node.js version 14.18.0

### Operating system

Window 10 pro

### Scope

not having

### Module and version

Not applicable.

**Comment by jeanbmar** [comment]
You are trying to use an outdated node version as per (https://github.com/AWSinAction/code2/blob/master/chapter05/Dev.md).
You must update your eb config script to reference a newer one supported by AWS.

**Comment by Masako-Maggie** [comment]
Thanks! I'll try to do that.

**Comment by Masako-Maggie** [comment]
Please close this case. Thank you!
