### ISSUE TITLE
Using process.stdin as a socket for IncomingMessage

### ISSUE THREAD

**Issue by jamesp** [nodejs/help#3716]
### Details

I am trying to make a very simple wrapper around node.js server handlers like `(req:IncomingMessage, res:ServerResponse) =>...` to use them in a cgi script context.

In a cgi script, the body of the request is given by stdin.  I thought this would work:

```js
#!/bin/node
// DOESN'T WORK
const {IncomingMessage} = require('http')

const req = new IncomingMessage(process.stdin)

var body = ""
req.on("data", function(chunk) { body+=chunk})
req.on("close", function() { console.log(body)})
```

But nothing is echoed from stdin.  However, attaching the event handlers to `req.socket` instead of just `req` does work:

```js
#!/bin/node
// DOES WORK
const {IncomingMessage} = require('http')

const req = new IncomingMessage(process.stdin)

var body = ""
req.socket.on("data", function(chunk) { body+=chunk})
req.socket.on("close", function() { console.log(body)})
```

What am I doing wrong? according to the docs `IncomingMessage` should work with a `net.Socket` as its parameter and stdin is a `net.Socket`. How do I get the event handlers on the parent `req` object to read from stdin, as would be the case for an `IncomingMessage` object created by a `http.server`? I want this cgi dispatcher to be compatible with handlers that expect to be able to call `req.on('data'...)`.

### Node.js version

v17.1.0

### Operating system

Linux 

### Scope

runtime

### Module and version

Not applicable.

**Comment by addaleax** [comment]
Hello @jamesp!

I’m not sure if you can really get all the way there with just `IncomingMessage`. Is it important that you do? For example, this also works:

```js
#!/bin/node
const { Server: HttpServer } = require('http');

const server = new HttpServer((req, res) => {
  let body = '';
  req.setEncoding('utf8');
  req.on('data', (chunk) => { body += chunk; });
  req.on('close', () => { console.log(body) });
});

server.emit('connection', process.stdin);
```

(You’ll notice that I added `.setEncoding('utf8')`. This is almost always what you want to do when you receive strings over a socket or other stream – otherwise, non-ASCII characters that are split across chunk boundaries will not end up being received properly.)

For a full stdin/stdout round trip, you could do this:

```js
#!/bin/node
const { Server: HttpServer } = require('http');
const { Duplex } = require('stream');

const server = new HttpServer((req, res) => {
  let body = '';
  req.setEncoding('utf8');
  req.on('data', (chunk) => { body += chunk; });
  req.on('close', () => {
    res.writeHead(200);
    res.end(`Request at ${req.url} said: ${body}\n`);
  });
});

server.emit('connection', Duplex.from({
  readable: process.stdin,
  writable: process.stdout
}));
```

**Comment by jamesp** [comment]
@addaleax that is amazing, thank you! Much more obvious how your code works. I'll give it a try. I hadn't considered using HttpServer in this way, I assumed I'd have to implement that myself.

Out of interest, why didn't my example work? My reading of the documentation suggested these two bits would interact.
