### ISSUE TITLE
How can we use custom TCP sockets?

### ISSUE THREAD

**Issue by jeanbmar** [nodejs/help#3717]
### Details

How can we properly use **custom** TCP sockets in Node.js?

This is a redundant question I've seen for years but I couldn't find a satisfying answer.
Most solutions I've seen wrap net.Socket inside a custom class. Which is horrible since you have to redefine tons of methods and rebind events for 0 added value.

My in-house solution is this:

```js
const { createServer, Socket } = require('net');

class CustomSocket extends Socket {
    constructor(options) {
    super(options);
    // now bind data event and do custom logic here
  }
}

const server = createServer();
server.on('connection', (netSocket) => {
    const socket = new CustomSocket({ handle: netSocket._handle }); // <-- this is the interesting part
    socket.on('close', (hadError) => console.log('closed, hadError:', hadError));
    socket.on('error', (error) => console.log('error received:', error));
    socket.destroy(new Error('kill me!'));
});
server.listen(3000);

const client = new Socket();
client.connect(3000);
```

It seems to work. But does it really?
The handle option on Socket is undocumented, I found it in Node source code. Docs mention an fd option, but there's no clear way to retrieve an existing socket fd.
Same for the _handle property. It's usable but private.

What's the way to go?

Thanks for your help.

### Node.js version

Not applicable.

### Operating system

Windows

### Scope

code

### Module and version

Not applicable.

**Comment by brian6932** [comment]
Should remain open, unsolved.
