### ISSUE TITLE
Will it be possible to implement the function of 'start', 'pause', 'resume', 'stop', just same as what multi-threads of JAVA do?

### ISSUE THREAD

**Issue by jasonsun001** [nodejs/help#3723]
### What is the problem this feature will solve?

To control the process of tasks which cost long time, for example, uploading and downloading files, data collecting, etc.

### What is the feature you are proposing to solve the problem?

To control the process of tasks which cost long time, for example, uploading and downloading files, data collecting, etc.

### What alternatives have you considered?

Promise

**Comment by gireeshpunathil** [comment]
`pause` , `resume` and `stop` methods are inherently buggy and can potentially cause inconsistencies to the entire app. For that matter, Java have either deprecated or removed those APIs.

You can use custom events to control the thread's life cycle. For example:

```js
worker.on('message', (message) =>
      // do what you need to do with the message
})
```

in the absence of this message and any other activities, the thread is waiting, and is practically free (in the underlying system), so will effectively give you the same result as `pause` and `resume`

Hope this helps!
