### ISSUE TITLE
Node installed but npm --version giving neither output nor error 

### ISSUE THREAD

**Issue by yashwadhwani08** [nodejs/help#3724]
### Details

I recently faced a problem in a react project for which I uninstalled node and reinstalled node a couple of times. node --version or node -v giving output (v16.13.2) but npm --version giving neither output nor error message.  
![image](https://user-images.githubusercontent.com/61770941/152681787-9a81d018-feaa-49bb-a3ca-052fdaf08b94.png)

### Node.js version

v16.13.2

### Operating system

Windows 11

### Scope

Not understood.

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
Where did you reinstall Node.js from? This can be caused by a corrupted installation, in which can cause NPM to not work properly if it's bundled with the Node.js installation.

**Comment by yashwadhwani08** [comment]
Downloaded it from the official website of Node.js https://nodejs.org/en/download/.

**Comment by yashwadhwani08** [comment]
@VoltrexMaster would you please look into this? I've been trying to uninstall & install nodejs so many times now but have got the same issue with every installation. Thanks in advance

**Comment by VoltrexMaster** [comment]
@yashwadhwani08 I'm unsure what could be causing that as you've downloaded and installed it from Node.js' official website.

Try the built-in [`which`](https://en.wikipedia.org/wiki/Which_(command)) command to see where the `npm` executable is located.
