### ISSUE TITLE
Scripts are loading in the frontend

### ISSUE THREAD

**Issue by Monisha94** [nodejs/help#3727]
### Details

Hi, 

We did a deployment 1 month before. after that some scripts are loading suddently in the frontend. We tried to check code and everything. Can you please help us to find the root cause of this?

Attached the screenshot for the same.

<img width="1536" alt="Scripterror" src="https://user-images.githubusercontent.com/32979807/152978647-89d992c3-17ed-4199-8f6d-3a0b6dae0fab.png">

### Node.js version

Not applicable.

### Operating system

Mac system

### Scope

Runtime

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Hi! Node.js is for backend JavaScript, and this looks like an issue with a Frontend page.
