### ISSUE TITLE
npm install uses system-wide node installation instead of local one

### ISSUE THREAD

**Issue by Osiris-Team** [nodejs/help#3731]
### Version

17.4.0

### Platform

Windows x64

### What steps will reproduce the bug?

1. Download node installation from here: https://nodejs.org/download/release/latest-v17.x/
2. Unpack the zip/tar somewhere
3. Create a new empty folder and open a terminal in that folder
4. Enter the following command in that terminal: `<npm-path> install puppeteer` (can be any module, puppeteer just a random example, also the npm-path must be pointing to the npm file from the unpacked node installation from before)
5. Voila.

### How often does it reproduce? Is there a required condition?

NodeJS must NOT be installed system-wide.

### What is the expected behavior?

It should check for an existing `node.exe` in its installation directory first, and only use the global `node` variable if there is no `node.exe` in its installation directory.

### What do you see instead?

```txt
...
npm ERR! path C:\WORK\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
...
```
As you can see npm tries to execute the command `node install.js`, the problem is, that node was not installed system-wide and thus there is no global `node` variable available.

**Comment by benjamingr** [comment]
Hey, node does not provide support for npm - please open an issue at the npm repo https://github.com/npm/cli

I suspect the workaround would be to execute npm's binary directly or add (the local) ndoe to the path.
