### ISSUE TITLE
Requiring same module from multiple modules causes same module to loaded more than once

### ISSUE THREAD

**Issue by aliemre1990** [nodejs/help#3736]
### Details

Hi.
I am facing an issue where i can't reproduce. Only happens on my source code so i will share the github repo of my code. The problem is when i reference same module from 2 different modules, that module is loaded twice. Because of this it causes it to be referenced as 2 different object. I will share an example code and my repo link. Don't worry only dependency you need is postgresql database service. And only command you need to run is `npm run start-dev-resetDb`. If you are using vs code i also have launch profile for this command so you can debug easily.

[Github repo link](https://github.com/aliemre1990/node-architecture-handlebars-postgresql)

### Node.js version

v17.5.0

### Example code

./backendModules/startup/data/frontend/languages.js

```js
const englishLanguage = {
    name:'English'
}

const turkishLanguage = {
    name:'Turkish'
}

const languagesData = {englishLanguage,turkishLanguage}

module.exports = {languagesData}
```
./backendModules/startup/data/frontend/languageCountryCodes.js

```js
const { languagesData } = require('./languages');

const languageCountryCodesData = {
    turkishTR: {
        language: languagesData.turkishLanguage,
        countryCode: 'TR'
    },
    englishEN: {
        language: languagesData.englishLanguage,
        countryCode: 'EN'
    },
    englishUS: {
        language: languagesData.englishLanguage,
        countryCode: 'US'
    }
};

module.exports = { languageCountryCodesData };
```

Below is the code i first reference this languagesData object.

./backendModules/startup/tableDescriptor/frontend/language

```js
const { languagesData } = require('../../data/frontend/languages');

const languagesTable = {
    tableName: 'languages',
    columns: [
        {
            name: 'id',
            type: 'SERIAL PRIMARY KEY',
            autoGenerated: true
        },
        {
            name: 'name',
            type: 'VARCHAR NOT NULL'
        }
    ],
    uniqueConstraints: [
        ['name']
    ],
    primaryKey: ['id'],
    prodData: languagesData
}

module.exports = { languagesTable };
```

./backendModules/startup/tableDescriptor/frontend/languageCountryCode

```js
const { languageCountryCodesData } = require('../../data/frontEnd/languageCountryCodes');
const { languagesTable } = require('./language');

const languageCountryCodesTable = {
    tableName: 'language_country_codes',
    columns: [
        {
            name: 'id',
            type: 'SERIAL PRIMARY KEY',
            autoGenerated: true
        },
        {
            name: 'languageId',
            type: 'INT NOT NULL'
        },
        {
            name: 'countryCode',
            type: 'VARCHAR NOT NULL'
        }
    ],
    primaryKey: ['id'],
    uniqueConstrarints: [
        ['countryCode']
    ],
    foreignKeys: [
        {
            key: 'languageId',
            table: languagesTable,
            reference: 'id',
            dataProperty: 'language'
        }
    ],
    prodData: languageCountryCodesData
};

module.exports = {  languageCountryCodesTable };
```

When i set a non-existing id property of one of languagesData value of languagesTable.prodData i expect it to be set on languageCountryCodesData.language of prodData property of languageCountryCodesTable object. languageCountryCodesData also references languagesData. And prodData property of languagesTable also references languagesData. But it seems they don't. They reference two different objects. But shouldn't theese be referencing same object?

### Operating system

Windows 10 Pro, Version:20H2, OS build:19042.1526

### Scope

runtime

### Module and version

Not applicable.

**Comment by aliemre1990** [comment]
It was a character casing problem. Fixed it by setting proper path with proper casing.

**Comment by VoltrexMaster** [comment]
Seems like you've fixed this, closing. Although feel free to reopen if needed.
