### ISSUE TITLE
Silently installing NodeJs but it fails each time

### ISSUE THREAD

**Issue by Zaserrr** [nodejs/help#3740]
### Details

Silently installing NodeJs but it fails each time
It says NodeJs v14 is installed but it is not. The nodejs file/directory is gone

### Node.js version

16.40.0

### Operating system

Windows

### Scope

Install

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Hi! Your question didn't supply enough information for us to understand how to best resolve it.
