### ISSUE TITLE
unable to verify signed binaries with gnupg

### ISSUE THREAD

**Issue by bahbarnett** [nodejs/help#3742]
### Details

https://github.com/nodejs/node#release-keys shows the following:

```shell
gpg --keyserver pool.sks-keyservers.net --recv-keys 4ED778F539E3634C779C87C6D7062848A1AB005C
... more key import lines here...
```

However:

```shell
$ host pool.sks-keyservers.net
Host pool.sks-keyservers.net not found: 2(SERVFAIL)
```

And:

https://lists.gnupg.org/pipermail/gnupg-users/2021-June/065258.html

It seems this keyserver has been shut down for close to a year?  Is there an alternate accepted keyserver, and if so, I would ask that the docs are updated.

Thanks

### Node.js version

Not applicable.

### Operating system

Linux (N/A)

### Scope

Release Veriication

### Module and version

Not applicable.

**Comment by bahbarnett** [comment]
Based upon this:

https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

And this:

https://web.archive.org/web/20211212202132/https://sks-keyservers.net/

And my recollection of this all happening a few year ago..

I'd suggest publishing these public keys, perhaps in a keyring, in your repo on github.

While not perfect, it does allow for verification of a release file from a secondary source.  That is, if nodejs.org was compromised in some way, a release file munged, said individual would have to also compromise github and commit an update to the sig file.

Again, not perfect, but far far better than nothing.  Which is where we're at currently.

**Comment by RedYetiDev** [comment]
Hi! This issue is not directly related to Node.js, so I'm closing it. If you disagree, please let me know :-)
