### ISSUE TITLE
node api doesnt work.

### ISSUE THREAD

**Issue by TrevorBlythe** [nodejs/help#3746]
### Version

16.7.0

### Platform

ubuntu

### What steps will reproduce the bug?

run the example hello world program for node_api.

### How often does it reproduce? Is there a required condition?

It says the same thing every time

### What is the expected behavior?

It to compile.

### What do you see instead?

Errors.

### Additional information

This is the code:

```cpp
#include <assert.h>
#include <node_api.h>

int main(){
  return 0;
}

static napi_value Method(napi_env env, napi_callback_info info) {
  napi_status status;
  napi_value world;
  status = napi_create_string_utf8(env, "world", 5, &world);
  assert(status == napi_ok);
  return world;
}

#define DECLARE_NAPI_METHOD(name, func)                          

static napi_value Init(napi_env env, napi_value exports) {
  napi_status status;
  napi_property_descriptor desc = DECLARE_NAPI_METHOD("hello", Method);
  status = napi_define_properties(env, exports, 1, &desc);
  assert(status == napi_ok);
  return exports;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
```

This is the error:

```text
main.c:20:71: error: expected expression before ‘;’ token
   20 | _property_descriptor desc = DECLARE_NAPI_METHOD("hello", Method);
      |                                                                 ^

make: *** [Makefile:2: all] Error 1
```

Keep in mind the only thing I wrote here was the main function because it said it needed it to compile. Everything else I just copied and pasted.

**Comment by mhdawson** [comment]
There has been no response from original poster for quite some time so closing. If that was not the right thing to do please let me know.
