### ISSUE TITLE
Issue using node.JS

### ISSUE THREAD

**Issue by aminotas** [nodejs/help#3751]
### Details

I was trying to install truffle and I was always receiving the same error, so I tried downgrading the nodejs and npm but I downgrade the npm in a version that is not compatible with node js version so I can't use these commands now :( 
Node js version 16.14.0
npm version 6.1.0

### Node.js version

Node js 16.14.0
npm 6.1.0

### Example code

```text
C:\Users\34628>npm install npm@latest
npm WARN npm npm does not support Node.js v16.14.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\34628\AppData\Roaming\npm-cache\_logs\2022-02-19T11_43_16_160Z-debug.log
```

### Operating system

windows 10

### Scope

installation

### Module and version

Not applicable.

**Comment by marsonya** [comment]
The node and npm versions are not compatible with each other. I would recommend either upgrading npm version to something compatible with the node version or downgrading node version to one supported by your nom version.

**Comment by gireeshpunathil** [comment]
@aminotas - is this resolved?

**Comment by gireeshpunathil** [comment]
closing as inactive
