### ISSUE TITLE
Is it possible to debug js internal/bootstrap/loaders.js

### ISSUE THREAD

**Issue by theGABS** [nodejs/help#3753]
### Details

I wanna understand how bootstrapping of nodeJS works, some details about is here https://stackoverflow.com/questions/71213900/how-require-work-under-the-hood-in-nodejs

So I try to run `node --inspect-brk`, but it's probably too late, and loaders.js is already executed.

### Node.js version

16.14.0 LTS
I can switch to another if its simplify 

### Operating system

windows 10
I can switch to another if its simplify 

### Scope

debug, internal, under the hood, bootstrapping 

### Module and version

internal module, require, nativeModuleRequire

**Comment by RedYetiDev** [comment]
AFAIK, you can't debug the bootstrap files, as they are executed before the script even runs
