### ISSUE TITLE
Find a way to use require with JavaScript run through stdin

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#376]
Ultimately, I just want to be able to do this on *nix:

`!#/usr/bin/env node --inspect`

but on *nix it won't work because you *cannot* pass any exec-args to node in that case. (It does work on MacOS, for whatever reason).

So as a workaround, I am trying to use 

https://en.wikipedia.org/wiki/Here_document#Unix_shells

to make something like this work on *nix, I have this:

```sh
#!/usr/bin/env bash

exec node --inspect --debug-brk <<EOF

console.log('dirname => ',__dirname);
process.env.SUMAN_EXTRANEOUS_EXECUTABLE = 'yes';
require('./cli.js');

EOF
```

like so:

![screenshot 2016-11-23 01 03 30](https://cloud.githubusercontent.com/assets/11139560/20556042/0bb29cc4-b11a-11e6-9035-92fb16f4b580.png)

However, I don't this will work correctly. Right off the bat, the require function is having trouble with path resolution.

The following:

```js
console.log('dirname => ',__dirname);  
```

Yields this:

![screenshot 2016-11-23 01 07 52](https://cloud.githubusercontent.com/assets/11139560/20556052/180d0dc4-b11a-11e6-95b4-a135ccf9d1d0.png)

and as you can see from the first image, even though cli.js is in the same directory, require cannot resolve it for some reason. 

Is there any hope in this methodology of passing stdin to Node or should I try something else? How do I solve the original problem of passing flags to node but also use whatever node executable is on the user $PATH (for example if the user is using NVM)?

thanks!

**Comment by targos** [comment]
I'm not able to reproduce your issue (with or without the inspector flag). This is what I get:

```bash
$ cat a.js
console.log('world');

$ cat run.sh
#!/usr/bin/env bash

exec node <<EOF

console.log('hello');
console.log('dirname => ',__dirname);
require('./a.js');

EOF

$ ./run.sh 
hello
dirname =>  .
world
```

**Comment by ORESoftware** [comment]
ahh, I think it has to do with the cwd being different

**Comment by ORESoftware** [comment]
try putting your files in a directory below the cwd

**Comment by ORESoftware** [comment]
however, I honestly think trying to get this to work with stdin seems like a bad idea, I am guessing/99% certain that node.js does not run files with stdin! And is not designed to do it

so this is my solution for this:

```sh
#!/usr/bin/env bash
SUMAN_EXTRANEOUS_EXECUTABLE=yes node --inspect --debug-brk `dirname $0`/cli.js "$@"
```

it seems to work for now, but I thought the EOF stuff was pretty neat and I have always wanted to do things like:

`blah -foo | node`

but it has been tough to figure out how to get it to work

**Comment by ORESoftware** [comment]
I am going to close this since I problem won't need this methodology, thanks though
