### ISSUE TITLE
Help me i can't update

### ISSUE THREAD

**Issue by Ander507** [nodejs/help#3762]
### Details

when i type `sudo apt-get install -y nodejs` it installs nodejs v8.10.0 and i need v14.x.x

### Node.js version

v9.11.2

### Example code

# Using Ubuntu

```shell
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
```

### Operating system

ubuntu server 18.04
32 bit

### Scope

No errors it downloads nodejs v8.10.0

### Module and version

Updating my nodejs

**Comment by marsonya** [comment]
Try using the current setup
`curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

**Comment by gireeshpunathil** [comment]
@Ander507 -  is this resolved?

**Comment by gireeshpunathil** [comment]
closing as inactive
