### ISSUE TITLE
Getting Unexpected token '.' in node 16.14.0

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [nodejs/help#3766]
### Version

16.14.0

### Platform

Windows

### What steps will reproduce the bug?

1) Install nvm
2) Install node 16.14.0 via `nvm install 16.14.0`
3) In window cmd type any node command such as `npx react-native init AwesomeProject`
4) Getting Unexpected token '.'

### How often does it reproduce? Is there a required condition?

When using windows cmd. On PowerShell works fine.
It can be due to installing node via NVM (Node Version Manager)

### What is the expected behaviour?

It should not give any error.

### What do you see instead?

It gives the following error 

Getting Unexpected token '.'

**Comment by ZeeshanAhmadKhalil** [comment]
Follow helped me, the issue was using the old version of NVM.

https://github.com/npm/cli/issues/4234#issuecomment-1040528646

**Comment by abhayashta12** [comment]
Hey I face the same problem with my mac. Is somebody facing the same error with a mac.
