### ISSUE TITLE
Hello im super new to coding and i need yor help

### ISSUE THREAD

**Issue by TDR122** [nodejs/help#3769]
### Details

So what happened was I was just watching a video tut over js. The next moment the guy in the video explained how I should have nodejs installed so I can create folders for vs code. I installed it and when I opened it a CDM file opened. Noth the app itself.so I need help with what I'm doing wrong here, Did I miss something. How can I create a folder if it opens the CDM file?
Please help

-TDR

### Node.js version

17.6.0

### Example code

-

### Operating system

Windows 10

### Scope

Other

### Module and version

-

**Comment by RedYetiDev** [comment]
Hi! It seems like your issue description is quite vague. To assist you better, could you please provide more details about the problem you're encountering? Any specific error messages, steps to reproduce, or expected behavior would be helpful. Thank you!
