### ISSUE TITLE
Question - How does NPM/Node.js do path resolution in the local node_modules/.bin directory

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#377]
This might be better asked over at NPM, but maybe someone knows 

Been confused about this for awhile

I have an executable file (cli/exec.js) in an NPM module called "foo" like so:

    /foo
    --/cli
       exec.js
    --/lib
    package.json

in package.json, we have:

      "name": "foo",
      "bin": {
        "exec-foo": "cli/exec.js"
      }

when this module gets installed, with npm install, node_modules looks like this:

    --/node_modules
    ---/.bin
        exec-foo
    ---/foo
    ---/lodash
    ---/async
    ---/whatev

...What confuses the crap out of me, is how does Node.js do module/dependency resolution with the require function, now that the exec-foo.js file is no longer where it once was in the project, but is now located in `node_modules/.bin`? Is there a simple explanation for this?

**Comment by ORESoftware** [comment]
Ok, I think I figured it out, these files in the node_modules/.bin directory are actually just symbolic links. So node_modules/.bin/x most likely points to a file in node_modules/x/index.js or whatever.

**Comment by lordKnighton** [comment]
Sorry for the late response @ORESoftware  do you still need help with this ❓

**Comment by ORESoftware** [comment]
I think I got it, symbolic links were the answer right?

**Comment by lordKnighton** [comment]
I think so `symbolic links`, but i'm sure this would be better asked @npm 

See if this link helps: https://docs.npmjs.com/cli/link
