### ISSUE TITLE
Get "home" directory if user is root

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#378]
From my quick experimentation, if the user is the root user, then` process.env.HOME` will be defined different than otherwise, looks like process.env.HOME = "/var/root".

My question is - can we count on `process.env.HOME` being defined properly, whether or not the user is root?

This mostly concerns using containers, when the default is to use the root user in the container.

**Comment by addaleax** [comment]
There’s also `os.userInfo().homedir`. Practically speaking, `process.env.HOME` will be what you want most of the time, but what can be tricky is that `sudo` doesn’t change it by default, so you need to be careful which files you create with which permissions.

**Comment by bnoordhuis** [comment]
> My question is - can we count on process.env.HOME being defined properly, whether or not the user is root?

No, neither when root nor when a normal user.  It's possible (if uncommon) to unset $HOME, to say nothing of setting a wrong value.

**Comment by ORESoftware** [comment]
Well I guess my question is, when Node.js engine starts up, `process.env.HOME `will be set even if you are root user, and I am wondering what the value will be? Will it be consistent or not and how is it determined?  is there docs somewhere showing what they value should be?

**Comment by bnoordhuis** [comment]
`process.env.HOME` is just $HOME, the shell variable.  It's set to whatever the value of $HOME was when node.js was started.  Node just inherits it, nothing more.

**Comment by ORESoftware** [comment]
yes that makes sense
