### ISSUE TITLE
Help running a build 

### ISSUE THREAD

**Issue by Naimas** [nodejs/help#3780]
### Details

Hello , I was trying to follow this tutorial , but I get stuck everytime I try to instal and run the app for the simulation of mock devices.. 

Here is the tutorial 

https://github.com/Azure-Samples/azure-digital-twins-unreal-integration

here the mockdevices ...

https://github.com/codetunez/mock-devices

And here are the erros log I get when I try to run the build as specified in the step by step guides, unfortunately I am not a programmer so I dunno what all that could be depending from but I need to progress on that tutorial as I am working on a project based on that ...

Thanks for any help .

[2022-03-10T17_38_48_431Z-debug-0.log](https://github.com/nodejs/help/files/8226034/2022-03-10T17_38_48_431Z-debug-0.log)
[2022-03-10T18_19_15_688Z-debug-0.log](https://github.com/nodejs/help/files/8226035/2022-03-10T18_19_15_688Z-debug-0.log)

### Node.js version

16.14.0 

### Operating system

windows 10

### Scope

tutorial based here  https://github.com/Azure-Samples/azure-digital-twins-unreal-integration

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
If your having an issue with a third party tutorial, please ask them for support.
