### ISSUE TITLE
How to properly set UTF-8 encoding in a child process?

### ISSUE THREAD

**Issue by user7230724** [nodejs/help#3781]
### Details

```console
> node -p `Д`
Д

> node -e "child_process.spawn('node',['-p','`Д`']).stdout.pipe(process.stdout)"
ðö
```

The expected output is `Д` instead of `ðö`. I guess I need to set UTF-8 encoding somewhere somehow. What should I change to get the expected output?

### Node.js version

v16.8.0

### Operating system

Windows 10 Pro

```console
> wmic os get Locale,Caption,CSDVersion,Version,BuildNumber,OSArchitecture
BuildNumber  Caption                   CSDVersion  Locale  OSArchitecture  Version
19043        Microsoft Windows 10 Pro              0809    64-bit          10.0.19043
```

**Comment by addaleax** [comment]
@user7230724 Which shell is this?

**Comment by user7230724** [comment]
Command Prompt.

**Comment by addaleax** [comment]
@user7230724 Unfortunately I couldn’t reproduce this locally, using your exact code … what does `chcp` report for you?

**Comment by user7230724** [comment]
Thanks. `chcp` was the right direction. This [answer](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window) helped me. I had to set the Windows locale in Control Panel to UTF-8.
