### ISSUE TITLE
Without support for windows 7 users

### ISSUE THREAD

**Issue by belsouza** [nodejs/help#3784]
### Details

I would like to make available a version of node 14 or 15 for Windows 7. This is just to create a react application. Thanks.

**Comment by ecalcutin** [comment]
Hello @belsouza!
Do I understand right, you want to install specific version of NodeJS on Windows machine?
If so, the best way to do it is: using `nvm` for Windows.

Go to the [NVM for Windows](https://github.com/coreybutler/nvm-windows) page, install it. Then from command line, you should be able to execute command
`nvm install 14` or `nvm install 15`

Let me know if it helps you.

**Comment by gireeshpunathil** [comment]
closing as inactive
