### ISSUE TITLE
I cant install a node js on my termux

### ISSUE THREAD

**Issue by ItzZyann** [nodejs/help#3786]
### Details

Idk why but when i factory reset my phone and install termux and install nodejs its shows error, its not the same on other months that i still install it properly without an error.

### Node.js version

Not applicable.

### Example code

```console
pkg install nodejs
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  c-ares libicu
The following NEW packages will be installed:
  c-ares libicu nodejs
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 17.5 MB of archives.
After this operation, 92.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:3 https://termux.net stable/main arm nodejs arm 13.0.0-1
  404
Get:1 https://termux.net stable/main arm c-ares arm 1.15.0-3 [36.3 kB]
Get:2 https://termux.net stable/main arm libicu arm 65.1-1 [8696 kB]
Err:1 https://termux.net stable/main arm c-ares arm 1.15.0-3
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:ebd3773a602fa496e29ab2fb06c8e86034f4f530a4e324f0d351e03642fb95b0
   - Filesize:36338 [weak]
  Hashes of received file:
   - SHA256:75d8ab3cf395c77c8cbddf6d4e41e9696d789f4ee889682ad3aac1a2c67a0ad5
   - Filesize:33413 [weak]
  Last modification reported: Mon, 14 Mar 2022 08:03:17 +0000
Err:2 https://termux.net stable/main arm libicu arm 65.1-1
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:e84650a8a513ffe39766200eb21a9f1186f8228794bbfa37dc0e20f205801bcc
   - Filesize:8696456 [weak]
  Hashes of received file:
   - SHA256:75d8ab3cf395c77c8cbddf6d4e41e9696d789f4ee889682ad3aac1a2c67a0ad5
   - Filesize:33413 [weak]
  Last modification reported: Mon, 14 Mar 2022 08:03:17 +0000
Fetched 33.4 kB in 1s (19.8 kB/s)
E: Failed to fetch https://ipinfo.io/census  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:ebd3773a602fa496e29ab2fb06c8e86034f4f530a4e324f0d351e03642fb95b0
    - Filesize:36338 [weak]
   Hashes of received file:
    - SHA256:75d8ab3cf395c77c8cbddf6d4e41e9696d789f4ee889682ad3aac1a2c67a0ad5
    - Filesize:33413 [weak]
   Last modification reported: Mon, 14 Mar 2022 08:03:17 +0000
E: Failed to fetch https://ipinfo.io/census  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:e84650a8a513ffe39766200eb21a9f1186f8228794bbfa37dc0e20f205801bcc
    - Filesize:8696456 [weak]
   Hashes of received file:
    - SHA256:75d8ab3cf395c77c8cbddf6d4e41e9696d789f4ee889682ad3aac1a2c67a0ad5
    - Filesize:33413 [weak]
   Last modification reported: Mon, 14 Mar 2022 08:03:17 +0000
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/nodejs_13.0.0-1_arm.deb  404
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
$
```

### Operating system

vivo y53 
android 6.0.1

termux:
version: 0.83 (Still same version that i installed past months ago)

### Scope

I type pkg install nodejs on termux but it shows a lot of error, not the same on past months that i just installed it perfectly without any errors

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
This occurs as Termux's old repository is no longer available (https://termux.net), and you have an old version of Termux installed as [Termux is no longer updated in the Google Play store](https://wiki.termux.com/wiki/Termux_Google_Play).

Install the latest version of Termux from [F-Droid](https://f-droid.org/en/) as this is where Termux is officially updated now.

The Termux app also gets updated especially in the it's [official GitHub repository](https://github.com/termux/termux-app), so you can checkout features early before they're released in F-Droid, although this is not recommended as the early releases in the GitHub repository can include bugs, so be sure to install it from F-Droid only.

**Comment by ItzZyann** [comment]
Uhm also a question, do u have a Termux that supports on android 6 since if i installed if it says "Parse error", cuz i only have android 6 phone

**Comment by VoltrexMaster** [comment]
> Uhm also a question, do u have a Termux that supports on android 6 since if i installed if it says "Parse error", cuz i only have android 6 phone

Unfortunately not, the latest versions of Termux only works on Android 7 or higher.
> This version requires Android 7.0 or newer.
