### ISSUE TITLE
I observe a missing library file libatomic.so.1.

### ISSUE THREAD

**Issue by oase473** [nodejs/help#3788]
### Details

Hello everyone, thanks for reading my help request.

Objective: I am a new programmer trying to install nodejs on my armv7l yocto linux single board computer. 

Observation: I observe a missing library file `libatomic.so.1`.

Log: During my installation according to [Installing node from binary archive for linux](https://github.com/nodejs/help/wiki/Installation), I receive this message 

```console
node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

I have seen `libatomic.so.1` issues on stackoverflow, but mostly related to other applications. If anyone can help out regarding this issue here, let me know.

Thanks!

### Node.js version

node-v16.14.1-linux-armv7l

### Example code

```console
root@am437x-empro:/usr/local/lib/nodejs/node-v16.14.1-linux-armv7l/bin# uname -m
armv7l
root@am437x-empro:/usr/local/lib/nodejs/node-v16.14.1-linux-armv7l/bin# node -v
node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

### Operating system

Yocto linux

### Scope

Installation

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
most probably your linux distribution is missing `libatomic` library. can you perform:
`dnf install libatomic` and retry?

**Comment by oase473** [comment]
Thanks, I think since this is an embedded device, so the linux does not come with a package manager. The following result was given:

`root@am437x-empro:~# dnf install libatomic

-sh: dnf: command not found`

**Comment by oase473** [comment]
`root@am437x-empro:~# ldd /usr/local/lib/nodejs/node-v16.14.1-linux-armv7l/bin/node`

`-sh: ldd: command not found`

**Comment by gireeshpunathil** [comment]
ha. so basically the system has a missing package and it has no tooling to figure out who depends on that package.

looks like the vanilla yocto linux do not have necessary runtime lib to support node.

@nodejs/build - any guidance?

**Comment by tomerpetel** [comment]
@oase473 any solution? I'm stuck at the same point

**Comment by gireeshpunathil** [comment]
@oase473 - is this still an issue?

**Comment by sxa** [comment]
This feels like a case where you need to get libatomic from /somewhere/ for yocto, and if it doesn't provide you with one then you will need to build it yourself. It's not something that is built and bundled with the Node.js runtime.

**Comment by RedYetiDev** [comment]
@sxa is correct, closing
