### ISSUE TITLE
Cannot run NPM on Windows

### ISSUE THREAD

**Issue by ignoreintuition** [nodejs/help#379]
I have installed Node on my Windows 7 laptop (v6.9.1) and it is working but Node Package Manager will not run when I execute the npm.cmd. I have verified the environment variables and both the nodejs and npm directories are in my PATH. The error I receive is

```
C:\Program Files\nodejs>npm
The syntax of the command is incorrect.
The syntax of the command is incorrect.
The syntax of the command is incorrect.
/F was unexpected at this time.

```
Any help would be appreciated.

**Comment by bnoordhuis** [comment]
I don't know but if you don't get an answer here, you might want to file an issue at https://github.com/npm/npm/issues.

**Comment by ignoreintuition** [comment]
Submitted.  Thank you 
[https://github.com/npm/npm/issues/14727](https://github.com/npm/npm/issues/14727)

**Comment by imxike** [comment]
Guys, if you are facing this problem. Try to head to regedit -> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor. Here you can see a key named EnableExtensions, try to change it to **1**, that may help

**Comment by RYO-commits** [comment]
@imxike Thank you so much friend, your suggestion worked!!! this issue was driving me crazy.
