### ISSUE TITLE
node-v16.14.2.pkg can't be installed because its digital signature is invalid.

### ISSUE THREAD

**Issue by Amgde22** [nodejs/help#3791]
### Details

I have a mac mac yosemite 10.10.5 and when even I open nodejs.pkg (from the official site ofc) I get the error in the title 
node-v16.14.2.pkg can't be installed because its digital signature is invalid.
The package may have been corrupted or tampered with. Get a new copy of the package and try again.
I tried reinstalling multiple times but nothing worked
I kindly ask for any help I can get

### Node.js version

node-v16.14.2.pkg

### Operating system

mac os 10.10.5 late 2011

### Scope

installation 

### Module and version

Not applicable.

**Comment by Valja-Banjo** [comment]
I have this problem too! Did you found the answer?

**Comment by Valja-Banjo** [comment]
try the previous vers
