### ISSUE TITLE
x86_64 being added to artifact so node cant be found in repo. 

### ISSUE THREAD

**Issue by nathanbrinqa** [nodejs/help#3798]
### Details

I am unable to build my app with node, I believe it has something to do with x86_64 being added to the artifact. 

### Node.js version

Not applicable.

### Example code

```
  > Task :my-app:nodeSetup FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':my-app:nodeSetup'.
> Could not resolve all files for configuration ':my-app:detachedConfiguration22'.
   > Could not find node-16.4.0-darwin-x86_64.tar.gz (org.nodejs:node:16.4.0).
     Searched in the following locations:
         https://nodejs.org/dist/v16.4.0/node-v16.4.0-darwin-x86_64.tar.gz
```

The error i am getting. 

### Operating system

macOS 
monterey
M1 chip

### Scope

runtime. 

### Module and version

16.14.0

**Comment by CrlsMrls** [comment]
this should be have been fixed in version 3.3.0, with the pull https://github.com/node-gradle/gradle-node-plugin/pull/204

After specifying the version 3.3.0, my problem was resolved.
```
buildscript {
    dependencies {
        classpath 'com.github.node-gradle:gradle-node-plugin:3.3.0'
    }
}
```
