### ISSUE TITLE
err_require_esm

### ISSUE THREAD

**Issue by Rialecla** [nodejs/help#3799]
### Details

```js
const fetch = require('node-fetch');
```
                      
when i run this show the error
`err_require_esm`

### Node.js version

Not applicable.

### Operating system

window 10

### Scope

help please

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
The latest versions of [node-fetch](https://npmjs.com/package/node-fetch) is now ESM only as stated [here](https://github.com/node-fetch/node-fetch#commonjs), so to use it; you must import it either by using `import` statements (which only works if you're inside an ES module):

```js
import fetch from 'node-fetch';
```

Or by using dynamic imports:

```js
const { default: fetch } = await import('node-fetch');
```

Although I recommend switching to ESM at this point which you can easily do so by setting the `type` entry in the `package.json` file to `module`.

**Comment by Rialecla** [comment]
closed
