### ISSUE TITLE
uncaughtException handler invoked more than once - no idea why

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#380]
I have a file, and it has a handler like so:

```js

process.on('uncaughtException', function(err){
     console.error(err.stack || err);
});
```

This call is at the top level in a module, so it will only get called once. (I am *not* doing anything too crazy like deleting require cache and re-requiring modules).

I am really confused why this uncaughtException handler is being fired more than once when I throw an error later in the program.

Any idea under what circumstances this type of handler may be invoked more than once for the same thrown error? I am 99.999% certain this same handler callback is being fired more than once for the same thrown error.

thanks!

**Comment by bnoordhuis** [comment]
Have you read the warnings in the documentation?  You keep going after an unhandled exception, anything could happen.  Your code is the JS equivalent of ON ERROR RESUME NEXT.

**Comment by ORESoftware** [comment]
ok let me think about that thanks
