### ISSUE TITLE
Won't the default way for generating sessionIdContext lead to security problem, which blab the possible cli information to client?

### ISSUE THREAD

**Issue by LongTengDao** [nodejs/help#3801]
### Details

What does `sessionIdContext` used for? I try to read the js lib source of node, but stopped when face c++ part.

(And, to resume session across server restarts or load banancers, need I to use the same sessionIdContext option?)

### Node.js version

16

### Example code

https://github.com/nodejs/node/blob/934a3aa28fdc8dd23701d642580b261f5f6c932b/lib/_tls_wrap.js#L1430

### Operating system

linux

### Scope

can't say

### Module and version

tls

**Comment by saeedjhn** [comment]
NOTES
Sessions are generated within a certain context. When exporting/importing sessions with i2d_SSL_SESSION/d2i_SSL_SESSION it would be possible, to re-import a session generated from another context (e.g. another application), which might lead to malfunctions. Therefore, each application must set its own session id context sid_ctx which is used to distinguish the contexts and is stored in exported sessions. The sid_ctx can be any kind of binary data with a given length, it is therefore possible to use e.g. the name of the application and/or the hostname and/or service name ...

The session id context becomes part of the session. The session id context is set by the SSL/TLS server. The SSL_CTX_set_session_id_context() and SSL_set_session_id_context() functions are therefore only useful on the server side.

OpenSSL clients will check the session id context returned by the server when reusing a session.

The maximum length of the sid_ctx is limited to SSL_MAX_SID_CTX_LENGTH.

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_session_id_context.html
