### ISSUE TITLE
can I log value in test?

### ISSUE THREAD

**Issue by zzz6519003** [nodejs/help#3802]
### Details

if I do `tools/test.py test/parallel/test-stream2-transform.js` to following code, I wanna see the value

```js
assert.strictEqual(tx.readableLength, 10);
console.log(transformed);
assert.strictEqual(transformed, 10);
```

### Node.js version

newest

### Operating system

OSX

### Scope

other

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
@zzz6519003 - can you add `-v` flag as `tools/test.py -v test/parallel/test-stream2-transform.js` and see if it prints the output?

**Comment by zzz6519003** [comment]
Thx man!

**Comment by zzz6519003** [comment]
```console
➜  node git:(master) ✗ tools/test.py -v test/parallel/test-stream2-transform.js
# out/Release/node -p process.arch
# out/Release/node -p process.versions.openssl
# out/Release/node -p process.features.inspector
# out/Release/node -p process.versions.openssl
[00:00|%   0|+   0|-   0]: release test-stream2-transform# out/Release/node /Users/zzz/Develop/node/test/parallel/test-stream2-transform.js
[00:00|% 100|+   1|-   0]: Done 
```

doesn't work T>T

**Comment by gireeshpunathil** [comment]
ok, forgot this - you can run the test directly, outside of the python harness. that way, the console output that you are printing will not be absorbed:

`node test/parallel/test-stream2-transform.js`

(make sure the `node` is properly qualified in terms of path)

**Comment by zzz6519003** [comment]
it worked! thx!

wonder the point of tools/test.py, where we have node

**Comment by gireeshpunathil** [comment]
the point of tools/test.py is to run large number of tests (3K+) in batches, and with finer level of controls (single, module wise, sequential, parallel, and many more). `tools/test.py --help` provides the available configuration options.

node exe is invoked inside the python script internally.

Hope this helps!
