### ISSUE TITLE
error: g++ was not found

### ISSUE THREAD

**Issue by zzz6519003** [nodejs/help#3803]
### Details

I switch to tag0.0.1 to learn code.

```console
➜  node git:(a3627c06f8) ✗ ./waf configure
Checking for program g++                 : ok /usr/bin/g++ 
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
/Users/zzz/Develop/node/wscript:29: error: g++ was not found, see the result of g++ --version
```

### Node.js version

Not applicable.

### Operating system

MAc

### Scope

other

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
@zzz6519003  - please install g++ by running `brew install g++` prior to the build and see if it resolves our issue.

**Comment by zzz6519003** [comment]
> @zzz6519003 - please install g++ by running `brew install g++` prior to the build and see if it resolves our issue.

I tried T.T

you can also see `Checking for program g++                 : ok`

**Comment by gireeshpunathil** [comment]
@zzz6519003 - cool - so it is resolved?

**Comment by zzz6519003** [comment]
Nope ~

**Comment by gireeshpunathil** [comment]
what does `which g++` show?

**Comment by gireeshpunathil** [comment]
and `g++ --version` ?

**Comment by zzz6519003** [comment]
> g++ --version

➜  ib-main-site git:(feature/1.0.88) which g++               
/usr/bin/g++
➜  ib-main-site git:(feature/1.0.88) g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by gireeshpunathil** [comment]
tricky indeed!
g++ is there in the path, yet the script complains!
what does `/Users/zzz/Develop/node/wscript` line 29 show?

**Comment by gireeshpunathil** [comment]
even better, show the full script here, if it is not too big!

**Comment by zzz6519003** [comment]
```python
# /usr/bin/env python
import Options
import sys
import os
from os.path import join, dirname, abspath
from logging import fatal


import js2c

VERSION='0.0.1'
APPNAME='node'

srcdir = '.'
blddir = 'build'

def set_options(opt):
  # the gcc module provides a --debug-level option
  opt.tool_options('compiler_cxx')
  opt.tool_options('compiler_cc')
  opt.add_option( '--debug'
                , action='store_true'
                , default=False
                , help='Build debug variant [Default: False]'
                , dest='debug'
                )

def configure(conf):
  conf.check_tool('compiler_cxx')
  conf.check_tool('compiler_cc')

  conf.env["USE_DEBUG"] = Options.options.debug


  if sys.platform.startswith("freebsd"):
    if not conf.check(lib="execinfo", libpath=['/usr/lib', '/usr/local/lib'], uselib_store="EXECINFO"):
      fatal("install the libexecinfo port. devel/libexecinfo")

  conf.sub_config('deps/libeio')
  conf.sub_config('deps/libev')

  # liboi config
  print "--- liboi ---"
  if conf.check_cfg(package='gnutls', args='--cflags --libs', uselib_store="GNUTLS"):
    conf.define("HAVE_GNUTLS", 1)

  conf.define("HAVE_CONFIG_H", 1)

  conf.env.append_value("CCFLAGS", "-DEIO_STACKSIZE=%d" % (4096*8))

  conf.check(lib='profiler', uselib_store='PROFILER')

  # Split off debug variant before adding variant specific defines
  debug_env = conf.env.copy()
  conf.set_env_name('debug', debug_env)

  # Configure debug variant
  conf.setenv('debug')
  debug_env.set_variant('debug')
  debug_env.append_value('CCFLAGS', ['-DDEBUG', '-g', '-O0', '-Wall', '-Wextra'])
  debug_env.append_value('CXXFLAGS', ['-DDEBUG', '-g', '-O0', '-Wall', '-Wextra'])
  conf.write_config_header("config.h")

  # Configure default variant
  conf.setenv('default')
  conf.env.append_value('CCFLAGS', ['-DNDEBUG', '-O3'])
  conf.env.append_value('CXXFLAGS', ['-DNDEBUG', '-O3'])
  conf.write_config_header("config.h")

def build(bld):
  bld.add_subdirs('deps/libeio deps/libev')

  ### v8
  deps_src = join(bld.path.abspath(),"deps")
  deps_tgt = join(bld.srcnode.abspath(bld.env_of_name("default")),"deps")
  v8dir_src = join(deps_src,"v8")
  v8dir_tgt = join(deps_tgt, "v8")

  v8rule = 'cp -rf %s %s && ' \
           'cd %s && ' \
           'python scons.py -Q mode=%s library=static snapshot=on'

  v8 = bld.new_task_gen(
    target = join("deps/v8", bld.env["staticlib_PATTERN"] % "v8"),
    rule=v8rule % ( v8dir_src , deps_tgt , v8dir_tgt, "release"),
    before="cxx",
    install_path = None
  )
  bld.env["CPPPATH_V8"] = "deps/v8/include"
  bld.env["LINKFLAGS_V8"] = "-pthread"
  bld.env_of_name('default')["STATICLIB_V8"] = "v8"
  bld.env_of_name('default')["LIBPATH_V8"] = v8dir_tgt

  ### v8 debug
  if bld.env["USE_DEBUG"]:
    deps_tgt = join(bld.srcnode.abspath(bld.env_of_name("debug")),"deps")
    v8dir_tgt = join(deps_tgt, "v8")

    v8_debug = v8.clone("debug")
    bld.env_of_name('debug')["STATICLIB_V8"] = "v8_g"
    bld.env_of_name('debug')["LIBPATH_V8"] = v8dir_tgt
    bld.env_of_name('debug')["LINKFLAGS_V8"] = "-pthread"
    v8_debug.rule = v8rule % ( v8dir_src , deps_tgt , v8dir_tgt, "debug")
    v8_debug.target = join("deps/v8", bld.env["staticlib_PATTERN"] % "v8_g")

  ### oi
  oi = bld.new_task_gen("cc", "staticlib")
  oi.source = "deps/liboi/oi_socket.c"
  oi.includes = "deps/liboi/ deps/libev/"
  oi.name = "oi"
  oi.target = "oi"
  oi.uselib = "GNUTLS"
  oi.install_path = None
  if bld.env["USE_DEBUG"]:
    oi.clone("debug")

  ### http_parser
  http_parser = bld.new_task_gen("cc", "staticlib")
  http_parser.source = "deps/http_parser/http_parser.c"
  http_parser.includes = "deps/http_parser/"
  http_parser.name = "http_parser"
  http_parser.target = "http_parser"
  http_parser.install_path = None
  if bld.env["USE_DEBUG"]:
    http_parser.clone("debug")

  ### src/native.cc
  def javascript_in_c(task):
    env = task.env
    source = map(lambda x: x.srcpath(env), task.inputs)
    targets = map(lambda x: x.srcpath(env), task.outputs)
    js2c.JS2C(source, targets)

  native_cc = bld.new_task_gen(
    source="src/http.js src/file.js src/node.js",
    target="src/natives.h",
    rule=javascript_in_c,
    before="cxx"
  )
  native_cc.install_path = None
  if bld.env["USE_DEBUG"]:
    native_cc.clone("debug")

  ### node
  node = bld.new_task_gen("cxx", "program")
  node.target = 'node'
  node.source = """
    src/node.cc
    src/http.cc
    src/net.cc
    src/file.cc
    src/timer.cc
    src/constants.cc
  """
  node.includes = """
    src/ 
    deps/v8/include
    deps/libev
    deps/libeio
    deps/liboi 
    deps/http_parser
  """
  node.uselib_local = "oi ev eio http_parser"
  node.uselib = "V8 EXECINFO PROFILER"
  node.install_path = '${PREFIX}/bin'
  node.chmod = 0755

  if bld.env["USE_DEBUG"]:
    node.clone("debug")


```

**Comment by zzz6519003** [comment]
line29:   conf.check_tool('compiler_cxx')

**Comment by gireeshpunathil** [comment]
I am not great at python, but can you do a `print opt` inside the `set_options` function soon before the failing line, say line 28 and see what it prints?

**Comment by zzz6519003** [comment]
def set_options(opt):
  print str(opt)
  # the gcc module provides a --debug-level option
  opt.tool_options('compiler_cxx')

Gives me

➜  node git:(a3627c06f8) ✗ ./waf configure
<Options.Handler object at 0x105786a88>
Checking for program g++                 : ok /usr/bin/g++ 
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
/Users/zzz/Develop/node/wscript:30: error: g++ was not found, see the result of g++ —version

T.T

**Comment by gireeshpunathil** [comment]
@nodejs/python - any help can be provided here? the g++ compiler is installed and is available in standard path, yet a script complains about missing compiler. I haven't debugged python scripts enough to make any meaning.

**Comment by cclauss** [comment]
```
python --version
python3 --version
```
Python 2  _should be avoided_ because it reached its end of life on 1/1/2020 which was 819 days ago.  On Python 3, `print()` is a function so the () are _required_.

**Comment by zzz6519003** [comment]
print(opt)
Doesn’t change the result T.T

**Comment by cclauss** [comment]
https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#installing-node-gyp-using-the-xcode-command-line-tools-via-xcode-select---install

**Comment by zzz6519003** [comment]
Why should I install that, sir?

**Comment by cclauss** [comment]
The output above says that you are on an M1 Mac but you still have Python 2 installed.  The current macOS removes Python 2.  Also, you are having trouble accessing Apple Command Line Tools binaries so it is best to ensure that you have the current tools and that the path to those tools is properly set.

**Comment by zzz6519003** [comment]
Thx man!

**Comment by zzz6519003** [comment]
def set_options(opt):
  print str(opt)
  # the gcc module provides a --debug-level option
  opt.tool_options('compiler_cxx')

Gives me

➜  node git:(a3627c06f8) ✗ ./waf configure
<Options.Handler object at 0x105786a88>
Checking for program g++                 : ok /usr/bin/g++ 
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
/Users/zzz/Develop/node/wscript:30: error: g++ was not found, see the result of g++ —version

T.T

**Comment by cclauss** [comment]
`print str(opt)` is Python 2!!  Try `print(opt)`

**Comment by zzz6519003** [comment]
i remember there's subtle differences of printing between 2 & 3 XD
