### ISSUE TITLE
Heap memory usage much higher for bundled server.js file versus separate node_modules

### ISSUE THREAD

**Issue by bwhitty** [nodejs/help#3805]
### Details

I'm working on a feature of our application server where I'm toying around with the idea of Webpack'ing everything on the server, and outputting it all to a single monlithic `server.js` file.

How this differs from before is that prior we would just be loading dependencies from `node_modules/**` like normal, but in this new setup Webpack will have bundled everything into the `server.js`, and resolves all `import`s/`require`s using the Webpack runtime.

What I observe is that:
1. Heap memory usage (base, upon server startup) is about 3-4x when using this single large file.
2. Inline source maps directly affect heap memory usage, and removing them removes 50MB off the heap.
3. Minifying the bundled server file has no affect on heap memory usage

![Screen Shot 2022-03-28 at 5 56 11 PM](https://user-images.githubusercontent.com/1571966/160512549-425fa6a7-fe40-49c7-806b-4b041a58ba7c.png)

So my question is about the cause of the heap memory increase. 

Is it because the file is so large (10MB) and Node's heap memory usage scales with file size?

Is it because the Webpack'ing of all the code into a single `server.js` file causes all app depencies to be parsed/executed upfront and at once? I'm not aware of how this is semantically different from normal `require()`s out to `node_modules/`, since those are all parsed and executed as well (since module imports in the app are identical between these two build setups).

Any thoughts on this?

### Node.js version

14

### Operating system

Alpine Linux

### Scope

Runtime

### Module and version

Not applicable.

**Comment by brunoargolo** [comment]
Hi @bwhitty did you get any further usable information on this?
I started using yarn workspaces so now I find myself having to bundle my express applications using esbuild.
Memory usage seems to have more than doubled. I wonder if this is more a nodejs thing than an issue of a specific bundler.
Did you try chunking the bundle into several small parts?

**Comment by bwhitty** [comment]
@brunoargolo no I've not gone further to try splitting modules, but if you're seeing similarly large increase in size when using `esbuild` then likely the bundler runtime can be ruled out. My observation on the inclusion of large inline source-maps causing linearly increasing heap memory usage continues to point to just raw filesize affecting overall heap memory usage.
