### ISSUE TITLE
Do I have to worry about Security for the *local* machine when using node.js ?

### ISSUE THREAD

**Issue by manne65-hd** [nodejs/help#3806]
### Details

Hello there at node.js.
as far as I understand it so far, I will only be using node.js to install modules via npm in order to develop intranet-websites with laravel available only inside our company-network. The websites will be served via Microsoft's IIS, so I am assuming that I only use node.js as an "engine" in order to install packages via npm and run other commands like `npm install && npm run dev` to generate code like CSS and JS, but I will not be using node.js to act as a webserver itself.
When searching the web for security best practices with node.js, all I can find seem to relate to scenarios, where node.js will act as a webserver _(which is not my use-case)_

So my question is not about security concerns or best practices for running node as a server but I am trying to find out, if the pure existance of a node.js-Installation raises any security-issues on the local machine _(and thus the rest of our company-network)_ 

I am looking forward to your answers,
Manfred

 

### Node.js version

16.14.2 LTS 

### Operating system

Windows 10 (pro) 21H2

### Scope

other

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
@manne65-hd - you are right, the usual suspects of web server security best practices do not apply to your node.js installation and usage, as those are not used to serve web pages and accessed through public internet.

However, if you are super concerned, the `nam install` and `rpm run` internally run JS code in Node.js that needs access to the registry across public internet, so security best practices that `npm` suggests apply:

https://docs.npmjs.com/policies/security
https://snyk.io/blog/ten-npm-security-best-practices/

Hope this helps!

**Comment by gireeshpunathil** [comment]
@manne65-hd - is this still an issue?
