### ISSUE TITLE
enoent error 

### ISSUE THREAD

**Issue by Rialecla** [nodejs/help#3807]
### Details

Enoent: no such file or directory, scandir '${basePath}/build/images'

### Node.js version

16.14.2 lts

### Operating system

window 10

### Scope

when run the node 

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
pls provide a minimal recreate or steps to reproduce the problem or the program that fails.

**Comment by Rialecla** [comment]
onst FormData = require('form-data');
const fetch = require('node-fetch');
const path = require("path")
const basePath = process.cwd();
const fs = require("fs");

fs.readdirSync('${basePath}/build/images').forEach((file) => {
  const formData = new FormData();
  const fileStream = fs.createReadStream('${basePath}/build/images/${files}');
  formData.append('file', fileStream); 

  let url = 'https://api.nftport.xyz/v0/files';

  let options = {
    method: 'POST',

**Comment by gireeshpunathil** [comment]
can you print the value of `${basePath}/build/images/${files}` prior to the `createReadStream` call, and see if it exists and the process has permission to access it?

console.log(`'${basePath}/build/images/${files}'`)

**Comment by Rialecla** [comment]
steps total:
const FormData = require('form-data');
const fetch = require('node-fetch');
const path = require("path")
const basePath = process.cwd();
const fs = require("fs");

fs.readdirSync('${basePath}/build/images').forEach((file) => {
  const formData = new FormData();
  const fileStream = fs.createReadStream('${basePath}/build/images/${files}');
  formData.append('file', fileStream); 

  let url = 'https://api.nftport.xyz/v0/files';

  let options = {
    method: 'POST',
    headers: {
      Authorization: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',  
    },
    body: formData
  };
  
  fetch(url, options)
    .then((res) => res.json())
    .then((json) => {
      const fileName = path.parse(json.file_name).name;
      let rawdata = fs.readFileSync('${basePath}/build/json/${fileName}.json');
      let metadata = JSON.parse(rawdata);

      metadata.file_url = json.ipfs_url;

      fs.writeFileSync('${basepath}/build/json/${fileName}.json',JSON.stringify(metadata, null, 2));
      
      console.log('${json.file_name} uploaded & ${fileName}.json updated!');
    })
    .catch((err) => console.error('error:' + err)); 
});

**Comment by gireeshpunathil** [comment]
@Rialecla - I am not sure I follow your update. I was asking you to check if the underlying file path was really existing or not. The error message indicates that the file is not existing; so that is what we want to assert. can you do that?

**Comment by Rialecla** [comment]
how?
i'm not a coding person, help me please

**Comment by gireeshpunathil** [comment]
In the code provided in this comment: https://github.com/nodejs/help/issues/3807#issuecomment-1083993751

change these sequence:

```
fs.readdirSync('${basePath}/build/images').forEach((file) => {
const formData = new FormData();
const fileStream = fs.createReadStream('${basePath}/build/images/${files}');
formData.append('file', fileStream);
```

to 

```
fs.readdirSync('${basePath}/build/images').forEach((file) => {
const formData = new FormData();
console.log('${basePath}/build/images/${files}');
const fileStream = fs.createReadStream('${basePath}/build/images/${files}');
formData.append('file', fileStream);
```

and then, for the line printed in the console prior to the error, do:
`$ ls -lrt line`

where line is the path text printed.

**Comment by Rialecla** [comment]
where?
and then, for the line printed in the console prior to the error, do:
$ ls -lrt line

where line is the path text printed.

**Comment by gireeshpunathil** [comment]
first, make the change to the code as explained: by adding the one line code
then, execute it. it may print one or more paths before it throw `ENOENT` error
then, in the command prompt, execute `ls -lrt <line>` where line is the last line from the previous step

**Comment by gireeshpunathil** [comment]
is this still an issue?

**Comment by RedYetiDev** [comment]
The issue you are facing is that template strings only occur when a backtick is used (\`), and not a quote (')
