### ISSUE TITLE
nmp' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by halasaedi** [nodejs/help#3808]
### Details

Hello! I have been having this problem with node js, i have tried every way possible to get rid of this error message "nmp' is not recognized as an internal or external command,
operable program or batch file" but nothing seems to work. I have tried going into the environmental settings and changing the path and i have tried using yarn as well. Any way that is available on the internet i have tried! I am fairly new to this so any help would be greatly appreciated!!!

### Node.js version

Not applicable. 17.8.0 current version

### Example code

nmp' is not recognized as an internal or external command,
operable program or batch file.

### Operating system

windows 10 pro
64-bit operating system

### Scope

how to get rid of error message 

### Module and version

Not applicable.

**Comment by manne65-hd** [comment]
Maybe because **nmp** is in fact what the error-message says ?
I guess you are trying to use the **NodePackageManager** and must call it by typing in `npm` ??

Hope this helps.

**Comment by RedYetiDev** [comment]
As @manne65-hd mentioned, the correct command is `npm`.

I'm also closing this as **invalid**, as the question did not provide enough context to debug the issue (but someone was kind enough to find the error)
