### ISSUE TITLE
I couldn't npm install ghost-cli@latest -g

### ISSUE THREAD

**Issue by legitwision** [nodejs/help#3809]
### Details

I am very new to npm and I am trying to install Ghost-CLI using this command(npm install ghost-cli@latest -g).
It said there is 1 moderate severity vulnerability so I ran npm audit fix --force as it said but It didn't solve my problem still. I've been looking for the solution to fix this for a while but I couldn't. Please help me see the spot that I might miss. Sorry if I did something wrong in this post, it is my first post.

### Node.js version

v16.14.2

### Example code

PS C:\Users\noree\Desktop\my_website> npm -v
8.5.0
PS C:\Users\noree\Desktop\my_website> node -v
v16.14.2
PS C:\Users\noree\Desktop\my_website> **npm install ghost-cli@latest -g**

changed 427 packages, and audited 428 packages in 17s

32 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\noree\Desktop\my_website> **npm audit fix --force**
npm WARN using --force Recommended protections disabled.

up to date, audited 1 package in 322ms

found 0 vulnerabilities
PS C:\Users\noree\Desktop\my_website> **npm install ghost-cli@latest -g**

changed 427 packages, and audited 428 packages in 9s

32 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

### Operating system

Windows 11

### Scope

Installation

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
you need to:
 - step into the folder of your package,
 - validate / create package lock
 - run the audit command

https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities provides the exact steps.

I suggest you run in this sequence:
 - npm install (as before)
 - get the error
 - step into the folder
 - create package lock
 - run npm audit
 - see the errors
 - run npm audit fix..
 - run npm audit again to see everything is clean
 - done

**Comment by legitwision** [comment]
Thank you. I followed all the steps you mentioned above and it worked. This made my day. Thank you so much, have a great day!
