### ISSUE TITLE
Get product id of nodejs v17

### ISSUE THREAD

**Issue by devopsdude12** [nodejs/help#3810]
### Details

Hello, 
is there a txt file or xml file where I can find the product id/code of the nodejs msi file?

### Node.js version

V17.6

### Operating system

Windows

### Scope

Installation and uninstallation

### Module and version

Not applicable.

**Comment by indy-singh** [comment]
Just had to do this myself, and this worked.

```powershell
Get-AppLockerFileInformation -Path "node-v20.12.1-x64.msi" | Select-Object -ExpandProperty Publisher | Select-Object BinaryName
```

outputs

```powershell
BinaryName
----------
{52F556F9-7BD0-464D-B350-4E89F1F2264F}
```

**Comment by RedYetiDev** [comment]
Hi! It looks like this is an issue with the Windows system running Node and not Node itself. If you disagree, please **ping** me.
