### ISSUE TITLE
You'll need to upgrade to a newer Node.js version in order to use this version of npm. But Node version is greater than v10

### ISSUE THREAD

**Issue by Boniqx** [nodejs/help#3818]
### Details

Here is my command line I already have node version higher than the specified 10.24.1 but still gives me this error. Not really sure what is the issue here.

I am using nvm.

I also have tried to uninstall and re install npm.

I am using ubuntu

![image](https://user-images.githubusercontent.com/56586865/162236818-b93d167f-d683-459d-8183-b73d51b1921c.png)

### Node.js version

16.14.2

### Operating system

Ubuntu

### Scope

npm is detecting lower version of node

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Hi! It seems like you're using an outdated version of Node.js. We recommend upgrading to the latest stable version as many issues may have been fixed since the version you're using. If the problem continues after upgrading, please let us know, and we'll be happy to help you more.
