### ISSUE TITLE
Unable to listen on port 80

### ISSUE THREAD

**Issue by ZehMatt** [nodejs/help#3821]
### Version

v16.14.2

### Platform

Microsoft Windows NT 10.0.20348.0 x64

### What steps will reproduce the bug?

Trying to listen on port 80 results in 
```
Error: listen EACCES: permission denied "80"
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

To be able to listen on port 80.

### What do you see instead?

Error: listen EACCES: permission denied "80"

### Additional information

I did a bit of researching and it seems port 80 falls under the "privileged" ports, why? The work-around would be to run it as administrator but I definitely don't want to go that route. Installing a reverse proxy is a waste of resources to get around an arbitrary limitation. What is the reason behind this?

**Comment by takipsizad** [comment]
there is nodejs can do about this- 
https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html
i advise you to read this

**Comment by ZehMatt** [comment]
> there is nodejs can do about this- https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html i advise you to read this

I already stated I was aware of those "privileged ports", calling that a security feature is a joke in my opinion.

As for the actual issue, it turns out when you accidentally pass the port as a string it will fall come to this error, I was quite sure that Windows does not require root/admin to be able to listen on those ports. Checking the port argument on the side of nodejs is probably a good idea, either convert the string to number or throw that it expects a number, this caused quite the confusion.

**Comment by takipsizad** [comment]
may i ask how?
" Checking the port argument on the side of nodejs is probably a good idea, either convert the string to number or throw that it expects a number, this caused quite the confusion."
>. Checking the port argument on the side of nodejs is probably a good idea, either convert the string to number or throw that it expects a number, this caused quite the confusion.

**Comment by ZehMatt** [comment]
By checking the type of the argument? If the API expects a number it should rejects anything that is not that, I'm not sure at this point what sort of value it passed to the OS apis that it would get a permission denied.

**Comment by nabtron** [comment]
You can fix it by running it as admin user, such as:

`
sudo npm start
// or
sudo node app.js
`

reference: https://socalledhacker.com/nodejs-cheatsheet/

**Comment by ZehMatt** [comment]
> You can fix it by running it as admin user, such as:
> 
> `sudo npm start` or `sudo node app.js`
> 
> reference: https://socalledhacker.com/nodejs-cheatsheet/

You should read the entire thread before making assumptions, the issue is that port was a string and not a number, passing it as a number solves the issue, Node should handle this as an error, running it as admin will not solve this.
