### ISSUE TITLE
Is Node.js server-side JavaScript?

### ISSUE THREAD

**Issue by SamHobbsOrg** [nodejs/help#3824]
### Details

I am posting here because I think the documentation should be clarified.

See [Static site generator without posts](https://www.sitepoint.com/community/t/static-site-generator-without-posts/384446/10); someone there says that the only difference between Node.js and JavaScript is that _one runs in a browser and other on server_. I am a beginner to Node.js but I have been doing computers for half a century. I really think that it is not accurate to say that Node.js is the same as JavaScript in a browser except Node.js is server-side. I have searched for answers and I cannot find anything relevant that is clear about this. [About \| Node\.js](https://nodejs.org/en/about) says that Node.js is a _JavaScript runtime_ and I think some people would interpret that as saying that Node.js is the same as JavaScript in a browser except Node.js is server-side. I think that [Introduction to Node\.js](https://nodejs.dev/learn) is correspondingly unclear on the subject; it emphasizes processes and threads. It does say _the new ECMAScript standards can be used without problems_ but I think that does not clarify the issue.

### Node.js version

Not applicable.

### Operating system

Windows, but that is not relevant.

### Scope

Documentation

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
- JS (JavaScript) and Node.js are 2 different things, though people sometimes use those interchangeably
 - JS is a language, Node.js is a JS runtime (a software that runs a non-native language)
 - Browsers are JS runtime too (apart from other things such as web page rendering)
 - Node.js runs JS applications. Part of it (APIs) is written in JS itself, part in C++ and C
 - ECMAScript standards define language specifications, runtimes implement and support those (though the timing can vary)

Ultimately to the user, it is a platform to run JS code, so it is right in saying "Node.js is a JavaScript runtime environment.". However, I agree that it can be confusing for people with different language / platform background. Feel free to propose amendments! PRs are defenitely welcome!

**Comment by SamHobbsOrg** [comment]
Unfortunately I do not know enough to know what changes to make to the documentation.

I do not think it is a matter of  language / platform background. I often see introductions that emphasize what the author wants to emphasize and ignores critical issues for understanding the topic.

So let me ask this. Is there any part of [Introduction to Node.js](https://nodejs.dev/learn) that does not apply to the JavaScript language? In other words, does any of it not apply to JavaScript in a browser? I assume that **most** of it does not apply to JavaScript in a browser but if so then the introduction does not make that clear. The introduction reads more like a sales pitch to convince people already familiar with something else (I do not know what) that Node.js is wonderful.

**Comment by gireeshpunathil** [comment]
thanks for sharing your views.

> Is there any part of Introduction to Node.js that does not apply to the JavaScript language?

Yes, the Node.js standard API library, and its underlying supporting infrastructure - most of those do not apply to JS in the browser, and are intended for server side applications (disk, db, other end points etc.)

So IIUC, is your point -  if Node.js is fundamentally different from JS in the browser, why don't that be mentioned in the doc, and make the differences more visible, than similarities?
