### ISSUE TITLE
Debugger attached?

### ISSUE THREAD

**Issue by s-a** [nodejs/help#383]
I am experimenting with ```node --inspect```. Does there exist a way to handle ```Debugger attached.``` event within my node app? It would also be very interesting to know how to get the dynamic debug url from JavaScript code. For example ```chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/75b9f5e3-c947-4dc5-aa81-1353225e2850``` So far I found this https://nodejs.org/api/debugger.html#debugger_v8_inspector_integration_for_node_js docs. And Google have A LOT of noise using ```nodejs debug```.

**Comment by bnoordhuis** [comment]
> Does there exist a way to handle Debugger attached. event within my node app?

Alas, no.

> It would also be very interesting to know how to get the dynamic debug url from JavaScript code.

You can scrape it from `http://127.0.0.1:9229/json/list`, it's the `devtoolsFrontendUrl` property.

**Comment by s-a** [comment]
Thank you for fast reponse. ```devtoolsFrontendUrl``` is realy helpfull. If there is ```devtoolsFrontendUrl``` maybe I could query some url to determine if devtools is ready? I mean it should indicate if debugger is attached in some way.

**Comment by bnoordhuis** [comment]
Maybe it you connect to `webSocketDebuggerUrl`.  Not sure though, you'd have to try it.
