### ISSUE TITLE
Error Downloading Node.JS

### ISSUE THREAD

**Issue by HossainE1006** [nodejs/help#3834]
### Details

Hello, having difficulty downloading node.JS on my laptop. I keep getting the following error when trying to install.

### Node.js version

64 bit version16.14.2

### Operating system

Windows

### Scope

n/a

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
> I keep getting the following error when trying to install.

Show us the error you're getting.

**Comment by HossainE1006** [comment]
Please see attached.

Best,

Enjam Hossain
Senior QA Test Engineer
Cell: 718.415.0619
kantar.com/disclaimer<https://www.kantar.com/disclaimer>

**Comment by KARTIK-RAINA5802** [comment]
I think you can try reinstalling node using the instructions given below:- 

Installation Steps:-

Download the Windows installer from the [Nodes.js® website](http://nodejs.org/). 

Choose the LTS version that’s shown on the left. 

Run the installer (the .msi file you downloaded in the previous step.)

Follow the prompts in the installer remember to Click the check box in tools for native module prompt to automatically install the necessary tools.

This will open a new terminal window and you just have to press enter twice and it will start and let it finish. It may take you to power shell and you need to press enter there and wait till the whole process is finished. 

Confirm that Node has been installed successfully on your computer by opening a Hyper terminal and typing in the commands node --version

You should see the version of node you just installed.

You can also refer to- https://youtu.be/__7eOCxJyow

I really hope this works for you.

**Comment by Socratesdev** [comment]
What happens if when downloading tools it gets an error
