### ISSUE TITLE
concurrency in node.js

### ISSUE THREAD

**Issue by marzelin** [nodejs/help#384]
Recently I attended node.js seminar where instructor stated that callbacks in node.js can be run in parallel, therefore there can be race conditions pertaining the global state and because of that there is no guarantee that the shared state won't change during the execution of the callback. I'm not sure about that, after all node.js is perceived as single-threaded runtime.

As I understand, node.js compared to an agency looks like this:

The Agency (node.js) has two employees:
- The receptionist (event loop) - schedules task for the developer
- The developer (main thread) - does some tasks himself, and can delegate specialized tasks to contractors

The contractors (database, filesystem, etc.) - execute tasks assigned by developer and when done, pass the results to the recepcionist.

The question is: can the Agency have more than one developer?
Or:
Can node.js have more than one thread that executes tasks given by event loop, so that they can work on different tasks in the same time?

**Comment by bnoordhuis** [comment]
There is only one JS thread.  Callbacks are never executed in parallel.

However, some behind-the-scenes work is handed off to a thread pool.  Writes to files, for example, and it is possible to introduce data races that way - but only to external resources like files.

This example has a race and may write either "one two" or "two one".
```js
const fs = require('fs');
const fd = fs.openSync('test.txt', 'w');
fs.write(fd, 'one', () => console.log('one'));
fs.write(fd, 'two', () => console.log('two'));
```

**Comment by marzelin** [comment]
@bnoordhuis Great answer, thank you.

As to your example, what is responsible for that unpredictable behavior: JS engine that schedules calls for external resources, or the external entity that handles the request (in this case filesystem)?

For the following code:

    setTimeout(() => console.log('one'), 100);
    setTimeout(() => console.log('two'), 100);

Is there possibility that "two" will be printed before "one"?

**Comment by bnoordhuis** [comment]
Timers maintain strict ordering.  You should never see "two one."

> what is responsible for that unpredictable behavior

File operations are done inside a thread pool and are not synchronized with respect to each other.  You get similar results if you write to the same file from two processes.

**Comment by marzelin** [comment]
To sum up the subject before closing:
```js    
let identifierInOuterScope;

//...//

const callback = () => {
    console.log(identifierInOuterScope);
        
    // some data processing code that takes some time to complete
    // identifierInOuterScope is not used here
    //...//
        
    // it is GUARANTEED that identifierInOuterScope
    // will have the same value as in the console.log() 
    // at the beginning of the callback because:
    // 1. There's only one execution thread.
    // 2. Each callback is processed completely
    //    before any other callback is processed.
    console.log(identifierInOuterScope);
} 

//...//
```
