### ISSUE TITLE
where is type of 'node:test'

### ISSUE THREAD

**Issue by skimhugo** [nodejs/help#3847]
### Details

Cannot find module 'node:test' or its corresponding type declarations.

I installed the latest "@types/node": "^17.0.30",

### Node.js version

18.0.0

### Operating system

macos

### Scope

types

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
The typings for the `node:test` module aren't added yet, which the TypeScript typings for Node.js are declared [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node).

Add them if you'd like or wait for it to be added.

**Comment by skimhugo** [comment]
thanks

**Comment by varunkamra** [comment]
@VoltrexKeyva would you happen to know when will the node:test types be available for node 20?

**Comment by VoltrexKeyva** [comment]
> @VoltrexKeyva would you happen to know when will the node:test types be available for node 20?

It's already available, simply install [`@types/node`](https://www.npmjs.com/packages/@types/node) v20.
