### ISSUE TITLE
im a noob cant install previos version

### ISSUE THREAD

**Issue by slutpuppet** [nodejs/help#3848]
### Details

i need to install a previous version and having trouble if anyone can help that would be awesome i have linux mint and i am also a new linux user so everything is pretty new to me
node js 14.8.2

### Node.js version

14.8.2

### Operating system

linux mint

### Scope

?

### Module and version

14.8.2?

**Comment by VoltrexMaster** [comment]
You can use a Node.js version manager to manage your Node.js versions installed and to of course install an older or newer Node.js version, such as [n](https://npmjs.com/package/n) or [nvm](https://nvm.sh).

**Comment by RedYetiDev** [comment]
*(This issue seems resolved, closing)*
