### ISSUE TITLE
UNABLE TO RUN NODE SCRIPTS

### ISSUE THREAD

**Issue by John-nath** [nodejs/help#3854]
### Details

Hello, I'm having an issue. I transferred my project folder from my old pc to a new pc and node scripts are not running. Except app.js
app.js only runs the last command that I ran on my old pc. Despite the fact that I cleared its content

### Node.js version

i am using v18.0.0

### Example code

![image](https://user-images.githubusercontent.com/64172453/167277323-4961617f-9faa-4067-8e64-584de4a8fbee.png)

### Operating system

Wimdows 10

### Scope

runtime

### Module and version

Not applicable.

**Comment by prettydiff** [comment]
This would require additional information before anybody can help.  The issue contains a graphical screenshot with no code visible, so anybody that want's to help is forced to guess at what is actually occurring in the application.
