### ISSUE TITLE
inability to reinstall

### ISSUE THREAD

**Issue by Adelakin-Adewumi** [nodejs/help#3856]
### Details

I wanted to install node 16 but I installed node 18 instead. So I uninstalled node 18 in other to install node 16. Unfortunately, node 16 refused to install. All I got was, window installer cannot be accessed, contact our help. Please help. 

### Node.js version

Nodejs 16

### Example code

Cannot access window installer

### Operating system

windows

### Scope

Nil

### Module and version

Node.js 16

**Comment by VoltrexMaster** [comment]
> windows installer cannot be accessed

This error can occur because of multiple reasons, for a fix I recommend checking this [post at Windows Report](https://windowsreport.com/windows-installer-service-could-not-be-accessed).
