### ISSUE TITLE
Node.js with Google Sheets. Only Display Recent Row

### ISSUE THREAD

**Issue by bigbossmaine** [nodejs/help#386]
I am setting up my Magicmirror/ Raspberry Pi for my office. I am an Aquatic Safety Coordinator and I usually check the chemical logs every 30 minutes. The Lifeguards on duty will log that information using google forms and the data gets store on a google spreadsheet [here](https://docs.google.com/spreadsheets/d/15Y5Syg-z63YGfsX7nPYOXRFZ-t_jB23QUKCLZAT4BYA/edit#gid=1833266067)

The code I have Displays the first three Columns of each row
```js
for (var i = 0; i < rows.length; i++) { 
    var row = rows[i];
    console.log('%s, %s', row[0], row[1], row[2]);
}
```
How would I make it only display the most recent row submitted ?

**Comment by danielkhan** [comment]
I am not sure if I got you right but basically you want to log out the last line?

If so, this would be your solution:
```js
var row = rows[rows.length-1];
console.log('%s, %s', row[0], row[1], row[2]);
```
