### ISSUE TITLE
npm wrong

### ISSUE THREAD

**Issue by bailanguy** [nodejs/help#3862]
### Details

i have upgraded my npm to match my node ,but it still still won't work.

### Node.js version

Not applicable.

### Example code

npm WARN npm npm does not support Node.js v18.1.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\node\node_cache\_logs\2022-05-15T05_21_00_456Z-debug.log

### Operating system

windows11

### Scope

npm run distribute

### Module and version

npm 8.8.0
node 18.1.0

**Comment by aduh95** [comment]
The error message let's me think you are in fact using a very old version of npm, what happens if yourun in your terminal `npm --version`? And `corepack npm --version`?

**Comment by bailanguy** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nodejs/help"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 凌晨1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nodejs/help] npm wrong (Issue #3862)





 
The error message let's me think you are in fact using a very old version of npm, what happens if yourun in your terminal npm --version? And corepack npm --version?
