### ISSUE TITLE
Make functionality to show folder files instead of 'file not found'

### ISSUE THREAD

**Issue by lucianahanan** [nodejs/help#3864]
### Details

**The problem**: I need to quickly switch between many files while here on my `localhost:8080/ `'live service' runned by Edge DevTools that uses node.js as its server, that will show the 'faux browser page' right inside visual studio code.

If you go to the same url using vscode Go Live, you can actually see the folder files normally, like Options +indexes enabled in apache used to have.

**Request**: Please, add a Directory listing fallback, an option in node.js service to let us do the same as Options +indexes, so we can see the folder files when not calling any specific file, at least for localhost ! 

### Node.js version

last stable.

### Operating system

doesnt matter

### Scope

http service

### Module and version

Not applicable.

**Comment by prettydiff** [comment]
That is a userland feature you can write yourself.  I wrote such a thing in a GUI presented in the browser for my personal application.  It requires the ability to walk the file system making use of fs.readdir method, packaging the output into a data object of your formulation, and an interactive interface to make use of that data.

**Comment by lucianahanan** [comment]
Hmm, I was wondering, because the plain Live Server comes with this functionality, I was expecting it to be ported to your code as well somehow :(
