### ISSUE TITLE
Buffer.concatenate only produces buffer of last buffer in the array

### ISSUE THREAD

**Issue by services4amit** [nodejs/help#3870]
### Details

I am trying to concatenate an array of buffers using the Buffer.concat() function. From the documentation it appears that the first input is an array of buffers, and the second input is the buffer total length. I then convert that to a string and pass it to another function to be emailed to the client... but when I get the email, it only contains a PDF of the last buffer in the stream. I was hoping it would put all the invoices (as separate pages) in the pdf attachment. I've googled a bunch and can't find anyone that has a solution to this issue... just people who are having the same issue

### Node.js version

16

### Example code

```js
let buffLength = 0;
for (let i = 0; i <= arrBuffers.length - 1; i++) {
  buffLength = buffLength + arrBuffers[i].length;
}
const buffers = Buffer.concat(arrBuffers, buffLength);

return resolve(buffers);
```

### Operating system

MAC

### Scope

runtime

### Module and version

Not applicable.

**Comment by tniessen** [comment]
First, if you need to compute the `buffLength` in a loop, there is likely no benefit to computing it at all. Just omit `buffLength`.

Second, I don't quite understand your expectation. If each `Buffer` is a PDF document, you likely cannot just concatenate them and expect the result to be a single PDF document whose pages are the concatenation of the pages of the smaller documents.
