### ISSUE TITLE
Saving a file via NodeJS FS API on macOS should perform proper filesystem operations which refresh that file in other apps

### ISSUE THREAD

**Issue by porg** [nodejs/help#3874]
### Details

At [Microsoft Visual Studio Code](https://github.com/microsoft/vscode) I reported [Saving a file in VS Code should perform proper filesystem operations which refresh that file in other apps](https://github.com/microsoft/vscode/issues/150571).

- My analysis of filesystem events on macOS 11.6.6 Big Sur by aid of [FileWatcher](https://www.whatroute.net/filewatcher.html) shows that [VS Code](https://github.com/microsoft/vscode) for Mac does it differently than other apps, but why it fails in particular, I do not know.
- Microsoft developer @bpasero [acknowledged the report](https://github.com/microsoft/vscode/issues/150571#issuecomment-1140168571) and laid out that VS Code uses the [NodeJS filesystem API](https://nodejs.org/api/fs.html) with a sequence of `open` , `write` , `close`.
- What remains is to find out what in particular is different in NodeJS's filesystem operations in comparison to the other Mac apps where their writing to the file reliably auto-refreshes the file in all the other apps which have the file open.

### Node.js version

The one which is included in / used by

VS Code version: Code 1.67.2 (https://github.com/microsoft/vscode/commit/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

### Operating system

MacOS

### Scope

Filesystem API

### Module and version

https://nodejs.org/api/fs.html

**Comment by porg** [comment]
I retested with a slightly newer macOS and the current app versions:
❌ The situation is still as reported in [Saving a file in VS Code should perform proper filesystem operations which refresh that file in other apps](https://github.com/microsoft/vscode/issues/150571):

| MacDown | TextEdit | BBEdit | VSCode |
|---------|----------|--------|--------|
| 💾      | ✅       | ✅    | ✅     |
| ✅      | 💾       | ✅    | ✅     |
| ✅      | ✅       | 💾    | ✅     |
| ❌      | ❌       | ✅    | 💾     |

- Meaning: 💾 Change file and save it,  ✅ File change reflected in app,  ❌  File change not reflected in app.

## Version changes
- MacDown: Unchanged version 0.7.3 (1008.4)
- TextEdit: Unchanged version 1.16 (365.2)
- BBEdit: Meanwhile version 15.0.1 (15A80, 64-bit Intel)
- VSCode: Meanwhile v1.87.0
- macOS: Meanwhile 11.7.10 (before 11.*)
- NodeJS: Meanwhile 18.17.1
- VSCode detailed version info
```
1.87.0 Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 20.6.0
```

## Will retest this when on a newer macOS
- Which will occur this year quite certainly.
- Still if the underlying NodeJS bug could be identified and backported it would be nice.

**Comment by RedYetiDev** [comment]
Node.ja uses the `libuv` library to perform fs operations. If you think this is an issue, please file it with them.

Thank you!
