### ISSUE TITLE
Install/Uninstall

### ISSUE THREAD

**Issue by jugandomiguel** [nodejs/help#3876]
### Details

I can't install or uninstall node, I try to reinstall but say " the windows installer service could not be accessed, this can occur if you are running windows in safe mode, or if the windows installer is not correctrly installed. contact you suport personnal assistance"

### Node.js version

16.15.0 lts

### Operating system

Windows 10

### Scope

Installadion Uninstallation

### Module and version

Not applicable.

**Comment by Jopchumba** [comment]
@jugandomiguel check to see if you are the administrator or go to the control panel then programs if you find node uninstall then install it. 
also check if your or safe mode and put back to normal mode
