### ISSUE TITLE
require.resolve() for executables 

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#388]
Hi all, I am looking for a quick way to find the path to an executable, let's take `istanbul` as an example.

Right now, assuming the installation was successful, we can get the istanbul executable like so:

for global installations:

```terminal
EXEC=$(which istanbul)
```

for local executable:

```js
const exec = path.resolve(require.resolve('istanbul'),'/../','.bin','istanbul');
```

what I am looking for is a good way in both the shell and in Node.js to resolve the path to either a local or global istanbul executable.

Is there a unified way to do this in both JS and the shell?

**Comment by addaleax** [comment]
There’s https://www.npmjs.com/package/which which does the same thing as the `which` CLI. Is that what you are looking for?

**Comment by ORESoftware** [comment]
Yes I think that will work, I already starting writing the below, so I will finish:

The problem I have in my original post:

(a) I have conditional logic based off of global or local (local is preferred), but I may want to fallback on global

(b) for resolving local executable, require.resolve will basically locate the package.json main value for istanbul, but it does not easily give you the executable istanbul value 

(c) furthermore, WRT (b), if the require.resolve gives me the global value, then this logic will likely fail:

```js
const exec = path.resolve(require.resolve('istanbul'),'/../','.bin','istanbul');
```

since the directory structure in the global space is different than the local space

**Comment by ORESoftware** [comment]
so yeah that package from isaacs should probably work, however, what I am confused about now is:

https://github.com/npm/node-which/blob/master/bin/which

does it this package place an executable at the command line, and is it just "which"?

In other words, in that project's package.json, what does this do:

` "bin": "./bin/which",` ?

normally we see:

```
"bin" :{
 "node-which": "./bin/which"
}

```
I know this is documented in the npm docs, but I think it's bad practice, it's very ambiguous using the shorthand that isaacs used in that project

**Comment by addaleax** [comment]
> does this package place an executable at the command line, and is it just "which"?

Yup, and that should behave pretty much like the UNIX `which`.

**Comment by ORESoftware** [comment]
ooo that's scary! replacement for unix which, maybe I will fork the project and replace that bin entry with "node-which"...thanks!

**Comment by ORESoftware** [comment]
Ughhh, actually this didn't give me what I want 

I filed this issue over there

https://github.com/npm/node-which/issues/43

basically I am looking for a way, in both JS and bash (but JS is priority) to find the "nearest" istanbul executable, based off require.resolve() type rules

let's call our fictitious utility "nodeFindExecPath"

so if istanbul is installed locally, we could do

`nodeFindExecPath('istanbul')   // ./node_modules/.bin/istanbul`

or if NODE_PATH is used, it would yield

`nodeFindExecPath('istanbul')   // /some-other-dir/node_modules/.bin/istanbul`

I guess it doesn't make sense to mix the local module executable paths with global module executable paths since you're not supposed to require global modules in projects.

hope it makes sense

**Comment by richardlau** [comment]
The `.bin` directory is an invention of npm -- Core Node.js knows nothing about it. Probably best looking at how npm deals with it, e.g. [npm bin](https://docs.npmjs.com/cli/bin).

**Comment by ORESoftware** [comment]
I guess you're right, but there still might be a userland module that can get at this

**Comment by benjamingr** [comment]
Hey @ORESoftware what did you end up doing here?

**Comment by trusktr** [comment]
The trick I use is to look inside the package in node modules, then construct the path.relative from the path.resolve.

For example for webpack, we see:

```
node_modules/webpack-cli/bin/cli.js
```

`require.resolve('webpack-cli')` results in

```
......../node_modules/webpack-cli/lib/index.js
```

Based on that, we can write this:

```js
const webpackBin = path.resolve(require.resolve('webpack-cli'), '..', '..', 'bin', 'cli.js')
```
