### ISSUE TITLE
Node.js is not Installing

### ISSUE THREAD

**Issue by DOKKUSAITEJA** [nodejs/help#3880]
### Details

Node.js is not installing on windows8 pro, with 32bit intel i3 of brand lenovo, it show a message that is This Application is only Support on windows8.1, Windows server 2012 R2, or higher. Could you please solve this problem

### Node.js version

Not applicable.

### Operating system

Windows 8 pro, intel(R) Core(TM) i3-2330M CPU @ 2.20GHz 2.20 GHz.
System type: 32-bit Operating System, x64-based processor

### Scope

It does'nt run on laptop directly the pop up message open

### Module and version

Not applicable.

**Comment by DOKKUSAITEJA** [comment]
![Uploading IMG_20220604_131542.jpg…]()

**Comment by F3n67u** [comment]
@DOKKUSAITEJA I cannot the image that you upload. Could you upload your image again?
