### ISSUE TITLE
/home/runner/same-spotify/node_modules/discord.js-selfbot-v11/src/client/actions/MessageCreate.js:31         const message = channel._cacheMessage(new Message(channel, data, client));

### ISSUE THREAD

**Issue by hdanqjz** [nodejs/help#3883]
### Details
i run this code and have a problem:
```js
const keepAlive = require("./server")
let discord = require('discord.js-selfbot-v11')
let rpcGenerator = require("discordrpcgenerator")
const dotenv = require('dotenv');
const TOKEN = (process.env.TOKEN);
var uuid = ()=>([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,a=>(a^Math.random()*16>>a/4).toString(16))
let client = new discord.Client()

keepAlive()
client.login(TOKEN)
 
client.on("ready", () => {
    rpcGenerator.getRpcImage("985009319558909962", "pic1")
    .then(image => {
        let presence = new rpcGenerator.Rpc()
        .setName("twitch")
        .setUrl("https://www.youtube.com/watch?v=Bmkx8QaM0dM")
        .setType("STREAMING")
        .setApplicationId("985009319558909962")
        .setAssetsLargeImage(image.id)
        .setAssetsLargeText("https://discord.gg/DTC")
        .setDetails("Join DTC to see my penis")
 client.user.setPresence(presence.toDiscord())
    }).catch(console.error)
console.log(`${client.user.username} Successfully Logged in!`)
})
```

console
```console
/home/runner/same-spotify/node_modules/discord.js-selfbot-v11/src/client/actions/MessageCreate.js:31
        const message = channel._cacheMessage(new Message(channel, data, client));
                                ^

TypeError: channel._cacheMessage is not a function
    at MessageCreateAction.handle (/home/runner/same-spotify/node_modules/discord.js-selfbot-v11/src/client/actions/MessageCreate.js:31:33)
    at MessageCreateHandler.handle (/home/runner/same-spotify/node_modules/discord.js-selfbot-v11/src/client/websocket/packets/handlers/MessageCreate.js:8:51)
    at WebSocketPacketManager.handle (/home/runner/same-spotify/node_modules/discord.js-selfbot-v11/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/runner/same-spotify/node_modules/discord.js-selfbot-v11/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/runner/same-spotify/node_modules/discord.js-selfbot-v11/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/runner/same-spotify/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/runner/same-spotify/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/runner/same-spotify/node_modules/ws/lib/receiver.js:422:14)
exit status 1
```

### Node.js version

v16.7.0

### Operating system

node v16.7

### Scope

node

### Module and version

Not applicable.

**Comment by hdanqjz** [comment]
i can't fix it :(

**Comment by F3n67u** [comment]
The problem is the `channel` object in `channel._cacheMessage` is not a channel that has the `_cacheMessage` function. but `discord.js-patched-v11` has not checked this situation. 

Could you report this problem to https://github.com/Carcraftz/discord.js-patched-v11 repo? I think this problem will be solved better at discord.js-patched-v11, because solving it will require a lot of knowledge about `discord.js-patched-v11` package.

**Comment by F3n67u** [comment]
I give another try to reproduce your problem but failed. The following problem blocks me:

1. I have no `process.env.TOKEN` to call `login(token)`
2. The `./server` file is missing

**Comment by VoltrexMaster** [comment]
[discord.js-selfbot-v11](https://npmjs.com/package/discord.js-selfbot-v11) no longer works as it uses [discord.js](https://npmjs.com/package/discord.js) v11, discord.js v11 no longer works as it's pretty old and haven't been patched to handle new requests properly and other things.

And self-botting is against [Discord's ToS (Terms of Service)](https://discord.com/terms), so I would advise not doing this.

**Comment by F3n67u** [comment]
> [discord.js-selfbot-v11](https://npmjs.com/package/discord.js-selfbot-v11) no longer works as it uses [discord.js](https://npmjs.com/package/discord.js) v11, discord.js v11 no longer works as it's pretty old and haven't been patched to handle new requests properly and other things.
> 
> And self-botting is against [Discord's ToS (Terms of Service)](https://discord.com/terms), so I would advise not doing this.

@VoltrexMaster Awesome! I forgot that you are Discord bot experts. 😜

**Comment by sirzento** [comment]
Quick fix if using discord.js v11:
Go to node_modules/discord.js/src/client/actions/MessageCreate.js at row 10 and replace

`if(channel) {`

with

`if (channel && typeof channel._cacheMessage === "function") {`

**Comment by Majordi** [comment]
> 

It's still not working

**Comment by Katilmami** [comment]
solution of this error
 npm uni discord.js
 npm i discord.js-v11-stable 
After that, Then 
const Discord = require("discord.js");
 delete this code and replace it with
 const Discord = require("discord.js-v11-stable");
 write your code And it's fixed, your problem is over
