### ISSUE TITLE
local vs global

### ISSUE THREAD

**Issue by Solodolofolobolo** [nodejs/help#3888]
### Details

I i type npm -v into my command prompt it keeps giving me this : npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

### Node.js version

Not applicable.

### Operating system

windows 10

### Scope

n/a

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
NPM's 8.11.x versions have deprecated the `--global` and `--local` flags from the CLI, but the deprecations have been lifted on the 8.12.x versions and higher, so I would recommend updating to the latest version of the NPM CLI by running:

```console
$ npm i -g npm
```

As for the difference, the global location refers to the NPM packages that are installed globally with the `--global` flag, and the local location refers to the NPM packages that are installed locally (for example in one of your projects).
