### ISSUE TITLE
ReferenceError: a is not defined
at Object.

### ISSUE THREAD

**Issue by shiva3222** [nodejs/help#3896]
### Details

```console
ReferenceError: a is not defined
at Object. (C:\Users\91895\Documents\demo.js\index.js:3:13)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
at node:internal/main/run_main_module:17:47
```

### Node.js version

16.15.1

### Operating system

HP laptop

### Scope

Code not run error found 

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
Self-explanatory error, the variable called `a` is not actually defined but is being used regardless, you can see a detailed explanation of the error [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined).

**Comment by shiva3222** [comment]
![IMG-20220618-WA0001.jpeg](https://user-images.githubusercontent.com/107740572/174436472-d85a7ddd-108d-4e96-9a5e-7e1b5a61495f.jpeg)

**Comment by F3n67u** [comment]
@shiva3222 could you please paste the `C:\Users\91895\Documents\demo.js\index.js` file?

**Comment by shiva3222** [comment]
![Uploading 16555576374004967935837634793529.jpg…]()

**Comment by shiva3222** [comment]
![Uploading 16555577226877542608098963746512.jpg…]()

**Comment by shiva3222** [comment]
![1655558065872251493490713360499](https://user-images.githubusercontent.com/107740572/174439366-29efbb6c-1678-4707-ac67-eea51d43fd63.jpg)

**Comment by shiva3222** [comment]
![16555581671498507585786858216499](https://user-images.githubusercontent.com/107740572/174439421-1f8e9fcb-2252-423e-be6c-d1b133e6313b.jpg)

**Comment by F3n67u** [comment]
Your code seems to have no problem. I could run your code on my side.

```console.
$ cat test.js    
var a=10
var b=20
console.log(a+b)
$ node test.js 
30
```

Do you save your code successfully? I saw vscode shows there is some code edit has not saved to disk.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/12343178/174439789-c8762798-a681-425a-9696-27d6e1e435a0.png">

Run command `type index.js` in your terminal, and let us see what the output is. You could see below as an example.
<img width="681" alt="image" src="https://user-images.githubusercontent.com/12343178/174439998-5b9371a7-a9b0-45dd-b3ff-1b340318d637.png">

**Comment by shiva3222** [comment]
Thanks my problem hai fix 🥰🥰

**Comment by F3n67u** [comment]
> Thanks my problem hai fix 🥰🥰

Great! What is the problem is?

**Comment by shiva3222** [comment]
My problem is I am note save tha code and run without save code

**Comment by F3n67u** [comment]
Got it. I usually turn on auto save in vscode and recommend you turn on it. See https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save on how to turn on auto save mode
