### ISSUE TITLE
Yarn error command failed with exit code 127

### ISSUE THREAD

**Issue by gianbuschor** [nodejs/help#3897]
### Details

My yarn wont load for some reason. I always get a error with command failed with exit code 127. I cant seem to find a solution on the yarn helpdesk tho....how can i fix this problem?

```console
gians-macbook-pro:web gianbuschor$ yarn deploy
yarn run v1.22.19
$ cross-env ASSET_PREFIX=/metaplex/ yarn build && yarn deploy:gh
/bin/sh: cross-env: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
gians-macbook-pro:web gianbuschor$ 
```

### Node.js version

v16.15.1

### Example code

yarn deploy

### Operating system

MacOS

### Scope

code

### Module and version

Not applicable.

**Comment by gabrielefigenio** [comment]
i had this problem with yarn and tried reinstalling on the same folder as my project and it worked, just make sure your installing with admin and if you are not sure you can try "sudo apt install yarn".

**Comment by AlexGeoDev** [comment]
Hello @gabrielefigenio, I had the same problem, I installed yarn like you said and not fixed, after that I read again my package.json and found my error, I wrote "netx", after chage for "next", I run again "yarn build " and all is ok. Thanks
