### ISSUE TITLE
using setimeout

### ISSUE THREAD

**Issue by law2004** [nodejs/help#390]
Hi I am trying to get the setTimeout function to work but it isnt
if you scroll down you'll see setTimeout(cb,20000);
but that doesnt seem to pause inbetween each crawls. any other way to do it?

`
var request = require('request'),
  cheerio = require('cheerio'),
  async = require('async');

var NUM_STATES_CRAWL = 51;
var REQUEST_DELAY_IN_SECONDS = 2;

module.exports = {
  crawl: function (crawlTask, crawlCities, next) {
    var nCities = crawlCities.length;

    var queue = async.queue(function (task, callback) {
      setTimeout(function () {
        console.log("Downloading contents from ", task.url);
        request(task.url, function (err, response, body) {
          if (!response) {
            console.log("Response wasn't received for task", task);
            callback({code: -1, task: task})
          }
          else if (response.statusCode != 200) {
            console.log("BLOCKED", task.url, response.statusCode);
            callback({code: -2, message: "BLOCKED"});
          }
          else {
            var newCars = [];
            var $ = cheerio.load(body);
            $('div').each(function (i, el) {
              if ($(el).attr('class') == 'content') {
                var content = cheerio.load($(el).html());
                content('li').each(function (j, elem) {
                  if (content(elem).attr('class') == 'result-row') {
                    var id = content(elem).attr('data-pid')
                      , row = cheerio.load(content(elem).html())
                      , title = row('.hdrlnk').text()
                      , price = row('span .result-price').text()
                      , owner = row('small').text()
                      , date = row('.result-date').text()
                      , link = row('a').attr('href');
			
                    if (link.indexOf("craigslist.org") === -1) {
                      link = "http://" + task.domain + link;
                    }
                    else {
                      if (!link.startsWith("http")) {
                        if (link.startsWith("//")) {
                          link = "http:" + link;
                        }
                        else {
                          link = "http://" + link
                        }
                      }
                    }

                    var newCar = {
                      taskId: task.taskId,
                      carId: id,
                      date: date,
                      owner: owner,
                      link: link,
                      price: price,
                      title: title
                    };
                    newCars.push(newCar)
                  }
                })
              } // END if
            })

            console.log("Found ", newCars.length, "cars.");
            callback(null, newCars, task.domain);
          }
        })
      }, REQUEST_DELAY_IN_SECONDS * 1000);
    }, NUM_STATES_CRAWL);

    var handler = function (err, newCars) {
      if (err) {
        if (err.code == -2) {
          nCities--;
          //console.log("Inside handler! BLOCKED...", nCities);
          if (nCities == 0)
            next(err);
        }
        else {
          //console.log(crawlTask.id, " failed for city", nCities, ". Re-queuing...");
          queue.push(err.task, handler);
        }
      }
      else {
        nCities--;
        console.log(crawlTask.id, " has ", nCities, " left to crawl.");

        if (nCities == 0)
          next();

        var cars = [];
        async.eachSeries(newCars, function (car, cb) {
          Car.create(car, function (err, c) {
            if (!err && c) {
              cars.push(c);
              Car.publishCreate(c);
            }
            cb();
          })
        }, function () {
          if (cars.length > 0) {
            NotifierService.sendEmail(cars, "bzeaiter@gmail.com");
          }
        })

      }
    }

    async.each(crawlCities, function (city, cb) {
      var temp = city + ".craigslist.org";

      queue.push({
        url: "http://" + temp + crawlTask.path,
        domain: temp,
        taskId: crawlTask.taskId
      }, handler);

      setTimeout(cb, 20000);
    }, function (err) {
      if (err) {
        console.log("Something went wrong");
      }
    });
  }
}
`

**Comment by addaleax** [comment]
Maybe use `async.eachSeries` instead of `async.each`?
