### ISSUE TITLE
Simple Answer (hopefully) for Newbie

### ISSUE THREAD

**Issue by digitaccel** [nodejs/help#3900]
### Details

I am just starting with node.js. I have my program working fine on localhost. The problem I am having is running it on the server since almost all the examples out there deal with localhost.

My code works fine when I post to the url on localhost: http://localhost:3000

When I post the same data to the node js on the server, it triggers the file but the app.post routine never gets fired.

The app.js file (node) is located in the app directory. I post to the following url:

https://mywebsite.com/app:3000

I have verified the code to post is working as I sent it to a php file that returns what I posted.

### Node.js version

Not applicable.

### Example code

```js
// convert a webm file to a mp4 file.
const fs = require("fs");
const express = require("express");
var bodyParser = require('body-parser');
const  { createFFmpeg, fetchFile } = require('@ffmpeg/ffmpeg');
const ffmpeg = createFFmpeg({ log:false });
const app = express();

var log_file = fs.createWriteStream(__dirname + "/debug.txt", {flags: 'w'});
log_file.write("getting started\r\n"); // this gets triggered

app.use(express.urlencoded({extended: false}));


app.post('/', function(req, res){
// never enters this function
    log_file.write('in post\r\n');
    log_file.write("file1: " + req.body.file1 + "\r\n" );
    console.log (req.body.file1);
    console.log (req.body.file2);
    console.log (req.body.folder);
    var folder = req.body.folder;
    var baseDir = req.body.baseDir;
    var firstFile = baseDir + folder + "/" + req.body.file1;
    var secondFile = baseDir + folder + "/" + req.body.file2;
 //   convertFile(firstFile, secondFile);
    res.status(201).send("ok");
    res.end();
});

app.listen(3000, function(err){
    if (err)
        log_file.write("Error in server setup");
    log_file.write("Server listening on Port 3000");
});
```

### Operating system

Windows

### Scope

runtime

### Module and version

Not applicable.

**Comment by ibkareem** [comment]
should be the route path. have you tried changing the 'post' route to '/app'. this might help [express docs](https://expressjs.com/en/guide/routing.html)

**Comment by gireeshpunathil** [comment]
ya - looks like an issue with the route. Is your client a browser? Either way, can you print the request header from the client side?

**Comment by digitaccel** [comment]
Yes. I had figured this one out. Took me a while but . . . bkareem you were correct. I was under the impression that the port number was required in both development (locally) and in production as well. When I changed the url to /api and accessed it through http://mywebsite.com/api it worked. So very few examples on the web talk about this. Thanks guys.

**Comment by gireeshpunathil** [comment]
closing then, cheers!
