### ISSUE TITLE
Issues enabling corepack 

### ISSUE THREAD

**Issue by jacobhay2626** [nodejs/help#3908]
### Details

Hi, I hope this is the right place for questions along these lines, if not I apologise: 

I have recently downloaded the LTS node.js from: https://nodejs.org/en/ . 
I have been trying to enable Corepack in Visual studio code however when I try the code: 

```
npm i -g corepack
```
i run into the error: 

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 1 package, and audited 2 packages in 495ms

found 0 vulnerabilities
```
From previous questions on other forums there are three common recommendations: 
1. Try to uninstall the .pkg file from my Mac and reinstall a previous version (I am currently on v16.15.1 for node and 8.11.0 for npm), however after having tried to access the file using: 

```
pkgutil --pkg-info <org.nodejs.npm.pkg>
```
it gives the error: 
```
zsh: parse error near `\n'
```
(To be honest I am very new to coding and diving into the hardrive of my mac is a little daunting to me as well). 

2. The next option seems to be to access the npm.cmd file and change the prefix -g in line 12 to –location=global. I tried to access this file using: 

```
C:\Program Files\nodejs\npm.cmd
```
however, when i put this into my terminal it gives: 

```
zsh: command not found: C:Program
```
my assumption is this command is windows based?
I have also seen recommendations to try and open my cmd as administrator but this again seems to only be suited to windows from what i have seen?

3. The third option i have found seems to be to update my npm to the latest version using: 

```
sudo npm install -g npm@latest
```

but this gives the error: 

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 14 packages, and audited 202 packages in 848ms

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

So I am now a bit stuck as all the possible options i have found seem to be inaccessible to me at this time. 

### Node.js version

Not applicable.

### Operating system

macOs Monterey Version 12.0.1

### Scope

installation issue

### Module and version

v16.15.1 = node.js
8.11.0 = npm

**Comment by VoltrexMaster** [comment]
```console
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
```

You're not running into an error, that's just a warning message telling you that both of the `--global` (`-g` for short) and `--local` CLI flags are deperacted.

These deprecations only exist in the v8.11.x releases of npm, but were soon lifted so you can try installing the latest versions of npm to get rid of the deprecation warning (no need to use the `@latest` tag as installing packages globally already looks for the latest version):

```shell
npm i -g npm
```

You might get that deprecation warning message again when trying to install the latest version of npm, but that's normal.

After it's installed, you can use both of the `--global` (`-g` for short) and `--local` CLI flags without getting that deprecation warning message. If the deprecation warning message still shows up after the installing the latest version, you should try closing the terminal and reopening it for it to use the latest version.
