### ISSUE TITLE
CAN'T TYPE PASSWORD IN NODE JS

### ISSUE THREAD

**Issue by krishanu45A** [nodejs/help#3910]
### Details

I CANT TYEPE PASSWORD TO ACCESS MY HOSTING

### Node.js version

Not applicable.

### Operating system

WINDOWS 10

### Scope

APP ISSUE

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
You aren't exactly typing your password into Node.js to access to your hosting service, you're likely trying to access the server using SSH or other connection methods.

You're probably inputting the password incorrectly but with the amount of given information, it's nothing enough to provide further help.
