### ISSUE TITLE
Can't launch node.js

### ISSUE THREAD

**Issue by Huterok228** [nodejs/help#3912]
### Details

Hello! I can't launch node.js on my PC.When i installed and opened node.js file,it said to me that "The Windows installer Service could not be accessed.This can occur if you are running Windows in a safe mode or if the Windows installer is not correctly your support personnel for assistance".Safe mode is turned off and everything is right with installer(but im not sure).I am  newfag in node.js and i cant really understand where the problem is.Hell me pls with this,i will be very grateful.

### Node.js version

16.15.1

### Operating system

Microsoft Windows [Version 10.0.19044.1766]

### Scope

Installation

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
For solutions to that error, you can have a look at this [post at WindowsReport](https://windowsreport.com/windows-installer-service-could-not-be-accessed/).
