### ISSUE TITLE
Unable to install Node JS on Macbook OS. 

### ISSUE THREAD

**Issue by JhaapKaur** [nodejs/help#3913]
### Details

I am on mac OS 10.11.6 when I am trying to install Node.JS LTS or latest version, I get the following error message: node-v16.15.1.pkg can't be installed because its digital signature is invalid. The package may have been corrupted or tampered with. Get a new copy of the package and try again.

I have tried to uninstall and install several times but cannot overcome this. I am then facing issues when running the npm create-react-app command in my terminal where the EACCESS error message is displayed.

Any help would be much appreciated. Thank you. 

### Node.js version

LTS and Latest Version 

### Operating system

I am on mac OS 10.11.6 

### Scope

Unable to install Node JS 

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
> I get the following error message: node-v16.15.1.pkg can't be installed because its digital signature is invalid. The package may have been corrupted or tampered with. Get a new copy of the package and try again.

Where did you download the Node.js installer from? You should be downloading them from the [official Node.js website](https://nodejs.org/) already, as all the digital signatures are valid.

> I am then facing issues when running the npm create-react-app command in my terminal where the EACCESS error message is displayed.

That happens when either npm or the installation process of packages tries to access something outside of their given privilege, you can escalate the privileges by running the command with the `sudo` command.

**Comment by JhaapKaur** [comment]
Hi thanks for your message.

I have tried to Sudo command as you’ve advised and I am still not having any luck creating a react app on VS code. Are there any other commands you can suggest to overcome this?

Thank you,
Jhaap

Sent from my iPhone

On 26 Jun 2022, at 21:55, Mohammed Keyvanzadeh ***@***.***> wrote:

﻿

I get the following error message: node-v16.15.1.pkg can't be installed because its digital signature is invalid. The package may have been corrupted or tampered with. Get a new copy of the package and try again.

Where did you download the Node.js installer from? You should be downloading them from the official Node.js website<https://nodejs.org/> already, as all the digital signatures are valid.

I am then facing issues when running the npm create-react-app command in my terminal where the EACCESS error message is displayed.

That happens when either npm or the installation process of packages tries to access something outside of their given privilege, you can escalate the privileges by running the command with the sudo command.

**Comment by JhaapKaur** [comment]
Hi there,

Thanks for your response. To summarise, when downloading NodeJs from NodeJs.org (either the current or LTS version) I am getting the below error:

[cid:d51bb47e-b17b-441b-bc11-0c22c7f358b7]

When opening VS Code and trying to create react app using the command 'npm i -g create-react-app' or npm i -g create-react-app' and then npm i -g create-react-app' I get this (EACCESS Error):
[cid:482e7920-fb2e-42c2-b4db-77650f69e91d]

I have tried to google and youtube various trouble shooting tips including 'mkdir' command and sudo commands. I have also tried to uninstall and re install but have not had any luck so far. Any assistance would be much appreciated. I am on mac OS 10.11.6.

Thank you in advance,

Jhaap
________________________________

**Comment by sjajagithub** [comment]
<img width="659" alt="Screenshot 2023-12-11 at 12 07 31" src="https://github.com/nodejs/help/assets/143281740/8a6a6f4b-4a7d-4b8a-be73-d02d508be0b5">
can you help me with this error im using a MacBook Air

**Comment by MuddassirAsh** [comment]
I just encountered this issue again. I was trying to upgrade my node version and I installed the latest node version on the home page 20.11.0 for my mac and encountered "The installation failed" error message identical to the image posted above. 

I am not sure how to get a stack-trace of a desktop installer application failure.

**Comment by yosvanyisel** [comment]
same problem, any recommendation please?

**Comment by RedYetiDev** [comment]
> <img alt="Screenshot 2023-12-11 at 12 07 31" width="659" src="https://private-user-images.githubusercontent.com/143281740/289975375-8a6a6f4b-4a7d-4b8a-be73-d02d508be0b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTU1ODksIm5iZiI6MTcxNTY5NTI4OSwicGF0aCI6Ii8xNDMyODE3NDAvMjg5OTc1Mzc1LThhNmE2ZjRiLTRhN2QtNGI4YS1iZTczLWQwMmQ1MDhiZTBiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxNDAxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTM4NWU0YjI4NzRlZjIwODlmMmUxZDBlOWVlZjUzZmM2ODllYjk3ZDkzYjkxYWVhNzBmYjBmZmZmMThkNWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xqpm60cVT95hcYFcNfjbhvIktqG9Wvoqi1o8kL77OfA"> can you help me with this error im using a MacBook Air


Please open a seperate issue for this.

**Comment by RedYetiDev** [comment]
Hi! If anyone is experiencing similar issues in the latest installer, please open a new issue

Thanks!
