### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by rajarajan1985** [nodejs/help#3919]
### Details

I'm trying to run CDK deploy on the GitHub runner (ubuntu build) and I'm getting this below exception. I have typescript and ts-node added to the package.json under devDependencies. The code is running fine locally but not on the runner.

```console
Cannot find module 'typescript'
Require stack:
- /root/.npm/_npx/13740/lib/node_modules/ts-node/dist/util.js
- /root/.npm/_npx/13740/lib/node_modules/ts-node/dist/bin.js
```

### Node.js version

Node version 14.

### Operating system

ubuntu

### Scope

NA

### Module and version

Not applicable.

**Comment by benjamingr** [comment]
ts-node needs a version of TypeScript near it - you need to `npm i typescript` - you can follow the ts-node installation instructions to learn more :)

**Comment by RedYetiDev** [comment]
*(This issue seems completed; closing)*
