### ISSUE TITLE
RegExpes in node.js 18.3.0 are non-deterministic

### ISSUE THREAD

**Issue by cookiengineer** [nodejs/help#3939]
### Version

v18.3.0

### Platform

Linux whatever 5.18.7-arch1-1 nodejs/node#1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000 x86_64 GNU/Linux

### Subsystem

RegExp / JIT Optimizer

### What steps will reproduce the bug?

RegExpes in this node.js version are non-deterministic.

See this gist as a demo that shows the problem (with an attached screenshot):

https://gist.github.com/cookiengineer/a3e69a078e55d912eef0062dbac37ace

### How often does it reproduce? Is there a required condition?

It works 60% of the time, every time. It's non-deterministic, but on my machine the RegExpes match around 2 out of 10 times only.

### What is the expected behavior?

It should work 100% of the time.

### What do you see instead?

In the demo file I've provided in the gist, you can see that it only works a bunch of times, whereas it should work all times.

**Comment by BridgeAR** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec
