### ISSUE TITLE
Bring Node.js Package Manger CLI and Registry Under Linux Foundation

### ISSUE THREAD

**Issue by majgis** [nodejs/help#394]
Today I get to add a monkey patch to our build to deal with this issue:
https://github.com/npm/npm/issues/14042

The patched version of npm exists, but it is not yet included in the latest Node.js v6 LTS release.

I feel that if the Node.js package manager was under the Node.js foundation and development was more tightly coupled with Node.js, we would see fewer of these issues and faster updates to the Node.js release.

The majority of our build issues are associated with npm, so I feel like the Node.js experience suffers because of a third party package manager.

We are also starting our migration to a different package manager from the one bundled with Node.js since the default leaves much to be desired.

I applaud node security being brought under the Node.js foundation but there is an elephant in the room and the elephant is npm.

+1 vote to replace npm cli with yarn
+1 vote to bring yarn under the Node.js foundation
+1 vote to get the registry under the Node.js foundation, also with the hope that other ecosystems can benefit from the same open infrastructure

**Comment by williamkapke** [comment]
<sup>** Uses of "linux foundation" above is probably intended to be "The Node.js Foundation" instead. More detail: [here](https://youtu.be/SV0p3ET1vpU?t=10m37s)</sup>

**Comment by majgis** [comment]
@williamkapke Thank you, you are right, fixing now

**Comment by mikeal** [comment]
1. yarn is not a drop-in replacement for npm. removing npm and replacing it with a different binary with a different API would be the largest breaking change Node.js has ever done.
2. the cost burden of the current registry infrastructure would be more than the foundation currently has budget for. we manage a good amount of donated compute resources for the build cluster right now but this would basically double that load even if it was donated and we'd still need someone to donate the CDN. also, the registry isn't open source, so we'd have to write one.

That said, if you want to reduce the ecosystem's dependence on npm there are some concrete steps y

**Comment by mikeal** [comment]
Concrete steps you can take:

1. Build an open source registry that supports the same API the npm registry has. Should work with npm or yarn OOTB.
2. Build additional libraries and projects that do some of the tasks npm does, like install. The more clients and tools that exist in the ecosystem the more people can iterate on alternatives.
3. Participate in npm's upcoming work to spec out their API. They've announced this but I'm not sure of where to link to for active participation. Documenting a working API and how it is used by clients is hard work but super important.

**Comment by isaacs** [comment]
The Node Foundation doesn't have the resources to run the primary npm registry, and without _dramatically_ increasing its fundraising goals, it's not ever going to.

It's not just compute and bandwidth resources, it's human beings to work full time to keep ahead of the most ridiculous scale of any OSS community in history without literally throwing millions of dollars at the problem.  No one is going to offer to donate that much bandwidth and infrastructure without wanting something in return, and I guarantee you that any strings it comes along with are going to feel much more restrictive than just forking over the cash for it, and you still need human beings to actually design the systems and keep them running smoothly.

There are currently about 5.6 million human beings downloading packages from npm.  That's a little more than half of all JavaScript developers, who make up a little more than half of all developers worldwide.  The number of developers is increasing, and the portion of them who use JavaScript is increasing, and the number of JavaScript users who use npm is increasing.

All of which is to say, the price tag is going to keep going up.  The only way to make it work is to build a business around it, and the only _ethical_ way to do that is to align our incentives with the interests of the community.  That's what we're doing at npm, Inc.

I am sorry that you encountered a bug in the free software tool we made for you.  You can of course use any other npm client you'd like.  But the Node Foundation doesn't have the resources or authority to annex the registry unilaterally, and attempting to do so would be perhaps the surest way to kill this golden goose.

**Comment by mikeal** [comment]
I'd like to point out that the Node.js Foundation is in a *supporting* role to the project and community. The foundation doesn't employ engineers for any development, system administration, build, etc.

Those resources are entirely from our community and will remain that way for the foreseeable future.

If you want something to happen it's most productive not to "other" the foundation or the people that do the work. If **you** want something to happen then **you** and others like you that believe in that change will need to step up and build things. We don't have a pool of engineers we can task with work other people happen to be passionate about ;)

If this thread goes too far down the path of "X should do this" it will get nasty quickly and we'll end up locking the thread.

The only productive way forward is to talk about things you can do, things you can build, things others can get excited about pitching in to do, in order to reach your goals.

**Comment by isaacs** [comment]
I'm sorry, my comment is already out of date.

5.7 million developers.  Not 5.6M.  It keeps rising, I can't keep up with it.

**Comment by TheAlphaNerd** [comment]
I'm going to go ahead and close this for now. @majgis please feel free to ask other questions you may have.

**Comment by majgis** [comment]
Thank you for your responses.  @mikeal I appreciate your constructive suggestions.
