### ISSUE TITLE
node -v failing with libstdc++ loading error in chromebook

### ISSUE THREAD

**Issue by dashjuthika** [nodejs/help#3941]
- **URL**:
- **Browser version**:
- **Operating system**:
ChromeOS 105 version

![image](https://user-images.githubusercontent.com/85892682/180893330-ecc39415-f880-4743-bb54-bcb7133c6bc5.png)

**Comment by VoltrexMaster** [comment]
Where did you install Node.js from? (You should install it from https://nodejs.org/).

I would also suggest uninstalling and reinstalling Node.js and see if that resolves the error.

**Comment by dashjuthika** [comment]
I downloaded nodev16.16 from nodejs.org in my chromebook and i see this issue and chromeOS has deprecated libstdc++ lib and node is using it.
![image](https://user-images.githubusercontent.com/85892682/181045408-31baab46-cf91-4b23-a592-3030b56bbff4.png)

**Comment by lemire** [comment]
@dashjuthika ChromeOS itself is not a supported platform, but many Chromebooks allow you to run Debian (i.e., currently Debian 12)... which I think is what you are doing, judging from the screenshots. Linux is definitively a supported platform.

There are many ways to install Node on Linux and details matter. Your issue did not provide nearly enough details to identify a bug in Node.

**Comment by grandpa1946** [comment]
> @dashjuthika ChromeOS itself is not a supported platform, but many Chromebooks allow you to run Debian (i.e., currently Debian 12)... which I think is what you are doing, judging from the screenshots. Linux is definitively a supported platform.
> 
> There are many ways to install Node on Linux and details matter. Your issue did not provide nearly enough details to identify a bug in Node.

this was a shell in devmode
os info:
`chronos@localhost / $ cat /etc/os-release
ID_LIKE=chromiumos
GOOGLE_CRASH_ID=ChromeOS
NAME=Chrome OS
ID=chromeos
HOME_URL=https://www.chromium.org/chromium-os
BUG_REPORT_URL=https://crbug.com/new
VERSION=107
VERSION_ID=107
BUILD_ID=15117.112.0`
(something like this)

**Comment by CerisWhite** [comment]
Apologies for necrobumping this issue, but I doubt anyone will see it regardless since it's already closed.
It's true; ChromiumOS no longer uses libstdc++, and hasn't for several years. Chromium as a whole has been using clang/llvm as the default for a long time. Is there any specific reason why a build linked against libc++ isn't available?

**Comment by lemire** [comment]
@CerisWhite 

ChromeOS supports running Debian software:

https://chromeos.dev/en/linux/setup#installing-linux-apps-and-packages

Once in a Debian shell, installing and running Node should be as simple as typing...

```bash
curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh

bash nodesource_setup.sh

apt-get install -y nodejs

node
```

(Assuming that curl is present.)

I realize that you may find it more convenient to run Node.js directly.

Node.js is released for a wide set of platforms. It takes enormous effort to support so many platforms. A few engineers are paid to work on Node.js, but it is mostly volunteer work. Importantly, adding new platforms without gaining additional ressources would stress the core team even more.

However, *you* can prepare,  distribute and support packages for ChromiumOS. Anyone can: it is open source.

Alternatively, if Google (or some other organization) wants to pay for support of ChromiumOS, it is quite doable.

I do not speak for the Node.js organization but it seems unlikely that the core Node.js would take on an additional platform without additional ressources.
