### ISSUE TITLE
Unsupported Node.js version 10.24.1, version 14.0.0 or later is required. Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by terlatogit** [nodejs/help#3942]
### Details

Run sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile ./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a dev
  sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile ./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a dev
  shell: /usr/bin/bash -e {0}
  env:
    CLIENT_ID: ***
    USERNAME: ***
    INSTANCE_URL: ***
Unsupported Node.js version 10.24.1, version 14.0.0 or later is required.
Error: Process completed with exit code 1.

### Node.js version

I am using nodejs version 16.16.0

### Operating system

Windows

### Scope

wile running Github pipelines.yml file, I got this error

### Module and version

Not applicable.

**Comment by vivganes** [comment]
Looks like you were missing a `with` clause to force the nodejs version like here: https://github.com/terlatogit/SFDevOps/commit/908bbb85156b99f6f173eb0f304f49fd863fc349

Now, I see the build is working. 

This issue can be closed.
