### ISSUE TITLE
Bin | Access is denied

### ISSUE THREAD

**Issue by SohamBorate** [nodejs/help#3943]
### Details

I am creating a simple CLI to download music from youtube and apply spotify metadata to it. But while trying to use the binary I am having issues which I don't really understand. I'm kinda new to NodeJS, I tried to find a solution but I couldn't. Any help is appreciated

`directory`
```console
 Directory of C:\Users\soham\Documents\spot-dl

27-07-2022  22:28    <DIR>          .
26-07-2022  20:50    <DIR>          ..
27-07-2022  17:43    <DIR>          node_modules
27-07-2022  17:50           165,129 package-lock.json
27-07-2022  22:28               536 package.json
27-07-2022  22:12             5,522 spot-dl.js
               3 File(s)        171,187 bytes
```

`package.json`
```json
{
  "name": "spot-dl",
  "version": "1.0.0",
  "description": "Download music from Spotify.",
  "main": "spot-dl.js",
  "scripts": {
    "test": "npm start",
    "start": "node spot-dl.js"
  },
  "keywords": [
    "spotify",
    "music"
  ],
  "author": "Soham Borate",
  "license": "MIT",
  "dependencies": {
    "fs": "^0.0.1-security",
    "https": "^1.0.0",
    "node-id3": "^0.2.3",
    "spotify-web-api-node": "^5.0.2",
    "stream": "^0.0.2",
    "youtube-sr": "^4.2.0",
    "yt-converter": "^1.3.1"
  },
  "bin": "spot-dl.js"
}
```

`terminal`
```
C:\Users\soham\Documents\spot-dl> npm install -g .

added 1 package, and audited 3 packages in 693ms

found 0 vulnerabilities

C:\Users\soham\Documents\spot-dl> spot-dl
Access is denied.
```

### Node.js version

v16.13.1

### Example code

Not applicable.

### Operating system

Windows 11

### Scope

`bin`

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
This is a basic permission error, Windows does not seem to allow you to execute your binary (`bin`) due to insufficient permissions, so I would recommend either running the command as administrator and see if it works, or debug to see what causes it to require administrator permissions than usual.

A guide to making a simple CLI with Node.js can be found [here](https://dev.to/rushankhan1/build-a-cli-with-node-js-4jbi) if you're having issues making it yourself.

**Comment by SohamBorate** [comment]
I got a solution on StackOverflow, https://stackoverflow.com/questions/73142094/nodejs-bin-access-is-denied/73142281#73142281
