### ISSUE TITLE
Calling napi_delete_reference from other thread

### ISSUE THREAD

**Issue by ronag** [nodejs/help#3951]
### Details

Often it is difficult to ensure that only the main Javascript thread has the last reference to an object. Hence, I wonder if it is safe to call `napi_delete_reference` from another thread? And if not, is it possible to check if you are not on the main thread and somehow dispatch back the unrefined to the main thread?

Tried to figure it out from the docs without much luck.

### Node.js version

Not applicable.

### Operating system

OSX

### Scope

node, napi

### Module and version

Not applicable.

**Comment by ronag** [comment]
@addaleax @jasnell @nodejs/addon-api

**Comment by addaleax** [comment]
This question sounds a bit like you’re doing odd things with Node-API, and your program structure is not what you want it to be. In particular, all Node-API calls should happen on the same thread, except for those APIs that are specifically made for usage with threads.

> Often it is difficult to ensure that only the main Javascript thread has the last reference to an object.

Generally speaking, only the main JS thread should ever work with Node-API objects, not just for the last reference to an object.

> Hence, I wonder if it is safe to call `napi_delete_reference` from another thread?

No.

> And if not, is it possible to check if you are not on the main thread and somehow dispatch back the unrefined to the main thread?

You can store the “main” thread id somewhere and compare it, if you want.
