### ISSUE TITLE
Inconsistent result with import()

### ISSUE THREAD

**Issue by simon300000** [nodejs/help#3957]
### Details

I am not sure why this is happening, is there a feature in JavaScript I don’t know causing this?

import(file) will produce different result on (semantically) similar/same code.

consider:
1.js
```javascript
module.exports['a'] = 1
```

2.js
```javascript
module.exports[String('a')] = 1
```

in node repl
```javascript
await import('./1.js')
// [Module: null prototype] { a: 1, default: { a: 1 } }
await import('./2.js')
// [Module: null prototype] { default: { a: 1 } }
```

more example:
behave like 1
```javascript
Object.defineProperty(module.exports, 'a', {
  enumerable: true,
  value: 2
})
```

behave like 2
```javascript
const __defProp = Object.defineProperty

__defProp(module.exports, 'a', {
  enumerable: true,
  value: 2
})
```

behave like 2
```javascript
const a = module.exports

Object.defineProperty(a, 'a', {
  enumerable: true,
  value: 2
})
```

3rd behaviour:
```javascript
Object.defineProperty(module.exports, 'a', {
  value: 2
})
```

```
[Module: null prototype] { a: 2, default: {} }
```

### Node.js version

12/14/16/18

### Example code

Please visit
https://github.com/simon300000/nodejs-module-export-string

### Operating system

Windows/Ubuntu/macOS

### Scope

code?

### Module and version

Not applicable.

**Comment by devsnek** [comment]
@guybedford

**Comment by guybedford** [comment]
Yes this is a very-specifically-constrained static analysis going on as you have pointed out. You can read more about the exact interop here -https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#interoperability-with-commonjs, and the static analysis is described in more detail in the readme at https://github.com/nodejs/cjs-module-lexer. Dynamic execution-based CJS analysis over heuristic static analysis was the original preference for the project, but was blocked by various spec hurdles and execution invariants both within the project and at TC39.

**Comment by simon300000** [comment]
Thank you for this information @guybedford
