### ISSUE TITLE
When and what drains the micro task queue?

### ISSUE THREAD

**Issue by sidwebworks** [nodejs/help#3959]
### Details

Can anyone please clear my doubt regarding scheduling in Node?

I've been researching a lot on this for past couple of days
my main question is that in the [talk](https://youtu.be/rUFUTdQALrk) that James Snell gave he clearly mentioned that 

> "the micro task queue will be drained immediately after the nextTick queue is empty"

Based on this point, the behaviour is a bit unexpected in the attached code

So here the SERVER LISTENING  is fired before the MICRO TASK  queue drains

But isn't the micro task queue drained immediately after the nextTick  queue is drained?

I thought it might be possible that the `net.Server.listen` internally does something to achieve this but digging in the source code https://github.com/nodejs/node/blob/main/lib/net.js#L1560 it seems "synchronous"

CC: @mcollina 

### Node.js version

v16.16

### Example code

```js
'use strict';

const fs = require('fs');
const crypto = require('crypto');
const http = require('http');

// Current timestamp
const start = Date.now();

// Simple Logging util
const log = (name, ...args) => {
  const diff = Date.now() - start;
  const msg = `[${name.toUpperCase()}]: TIME: ${diff}ms`;
  process.stdout.write([msg, ...args, '\n\n'].join(' '));
};

function work() {
  process.nextTick(() => log('process.nextTick', 'Draining nextTicks queue'));

  setImmediate(() =>
    log('setImmediate', 'reached the end of the current loop iteration')
  );

  setTimeout(() => log('Timers'), 1000);

  queueMicrotask(() => log('Micro task'));

  // Some file IO
  fs.readFile(__filename, () => {
    log('File IO');
  });

  // Expensive hash
  crypto.pbkdf2('password', 'saltyyy', 10000, 512, 'sha512', () => {
    log(`pbkdf2`);
  });

  let count = 1000000000;

  // Some blocking code
  while (count) {
    count--;
  }

  log('Blocking', `count is ${count}`);
}

const server = http.createServer((req, res) => {
  log('REQ INCOMING', req.url);

  if (req.url?.includes('kill')) {
    server.close();
  }

  req.on('readable', () => {
    log('REQ READABLE');
    work();
  });

  req.on('end', () => {
    res.end();
  });

  req.on('close', () => {
    log(`REQ CLOSE`);
  });
});

process.on('exit', () => {
  log('EXIT', 'Event loop is down. Gotta go now...');
});

server.on('close', () => {
  log(`Server CLOSE`);
});

server.on('listening', () => {
  log(`Server listening`);
});

work(); // Initial run

server.listen(3000);
```

Here is the stdout result

```
[BLOCKING]: TIME: 478ms count is 0 
[PROCESS.NEXTTICK]: TIME: 481ms Draining nextTicks queue 
[SERVER LISTENING]: TIME: 481ms 
[MICRO TASK]: TIME: 481ms 
[PBKDF2]: TIME: 481ms 
[SETIMMEDIATE]: TIME: 482ms reached the end of the current loop iteration 
[FILE IO]: TIME: 482ms 
[TIMERS]: TIME: 1002ms 
```

### Operating system

Mac M1, ARM

### Scope

runtime

### Module and version

Not applicable.

**Comment by mcollina** [comment]
Looks like listening to a socket is "fake" synchronous using `process.nextTick()`. What problem does this cause for you?

**Comment by sidwebworks** [comment]
@mcollina Oh I see, I tried to look for the call to `process.nextTick` inside the `net.Server.listen` method but it just did a `this.emit("listening", cb)` which I guess is synonymous.

Thanks for asking, it's not really a problem I am trying to understand Node at a more deeper level but this confused me a bit and I couldn't find any answers about this online.

You mentioned that listening to a socket "is a fake synchronous", is it possible for you to point me where this happens? Like a file or a class method?

Anyways thank you for your time Matteo 🙏❤️

**Comment by sidwebworks** [comment]
Oh I think I got it now, you were right! I tired enqueuing some more `nextTick` calls and it cleary does what was expected because the `micro task` queue can't be drained until the `nextTick` queue is empty! that's why the `Server listening` runs before. 

Sorry lol I feel dumb, don't know why I overthinked this 😓
