### ISSUE TITLE
Unsupported platform

### ISSUE THREAD

**Issue by elthombre** [nodejs/help#3960]
### Details

I am trying to install an updated version and seeing the following:

```console
44 verbose node v15.12.0
45 verbose npm  v7.7.5
46 error code EBADPLATFORM
47 error notsup Unsupported platform for n@9.0.0: wanted {"os":"!win32"} (current: {"os":"win32","arch":"x64"})
48 error notsup Valid OS:    !win32
48 error notsup Valid Arch:  undefined
48 error notsup Actual OS:   win32
48 error notsup Actual Arch: x64
49 verbose exit 1
```

### Node.js version

v15.12.0

### Operating system

Edition	Windows 10 Home
Version	21H2
OS build	19044.1889

### Scope

installation

### Module and version

Not applicable.

**Comment by vcano5** [comment]
Looks like you are trying to install [n package](https://www.npmjs.com/package/n)
But it is not supported on windows

"n is supported on macOS, Linux, including with Windows Subsystem for Linux, and various other unix-like systems."

**Comment by elthombre** [comment]
It states:

wanted {"os":"!win32"} (current: {"os":"win32","arch":"x64"})

What is "!win32" vs. "win32" ??

**Comment by elthombre** [comment]
ok

**Comment by OdDev26** [comment]
I am experiencing a similar issue. When I run npm install I get the error below:

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@9.1.0: wanted {"os":"!win32"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  !win32
npm ERR! notsup Actual os: win32

What can I do?

**Comment by Aminat00** [comment]
I am experiencing similar issue please can anyone help me how I can avoid such issue ?
