### ISSUE TITLE
Error certificate???

### ISSUE THREAD

**Issue by gkit1980** [nodejs/help#3962]
### Details

i'm writing **npm i** in my project and im taking this kind of error.

**> @impeo/ice-playground@0.0.1 preinstall C:\Users\pameydev03\Repos\Eurolife\customer-area-src\ice-playground
> rm -R node_modules/@impeo || rd /s /q "node_modules/@impeo" || exit 0

'rm' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.

> keytar@7.7.0 install C:\Users\pameydev03\Repos\Eurolife\customer-area-src\ice-playground\node_modules\keytar
> prebuild-install || npm run build

prebuild-install WARN install self signed certificate in certificate chain

> keytar@7.7.0 build C:\Users\pameydev03\Repos\Eurolife\customer-area-src\ice-playground\node_modules\keytar
> node-gyp rebuild

C:\Users\pameydev03\Repos\Eurolife\customer-area-src\ice-playground\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:643:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\pameydev03\Repos\Eurolife\customer-area-src\ice-playground\node_modules\keytar
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.7.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@7.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pameydev03\AppData\Roaming\npm-cache\_logs\2022-08-26T12_41_30_937Z-debug.log

> node-libcurl@1.3.3 install C:\Users\pameydev03\Repos\Eurolife\customer-area-src\ice-playground\node_modules\node-libcurl**
> node-pre-gyp install --fallback-to-build

i never faced any issue with  this command in any pc that i m making the installation(either Windows or Mac).
On this machine the os is Windows 10 pro and it is hosted in VM.(and Windows are not activated)
Im trying to understand if there is a needed certificate but i do not know where to find and what are the steps to install it(if this is the problem).

Please if anyone can help i would appreciate it

### Node.js version

Node 8.12.0

### Operating system

Windows 10 pro

### Scope

Installation

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
As it currently stands, your issue lacks sufficient details for us to reproduce it. Please provide more context.
