### ISSUE TITLE
Send IPC message with sh/bash to parent process (Node.js)

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#397]
I asked this question on SO, but realize an answer might be Node.js specific, because the 'ipc' system that Node.js uses might be Node.js specific.

http://stackoverflow.com/questions/41033716/send-ipc-message-with-sh-bash-to-parent-process-node-js

Any idea how to send the parent process (Node.js) an IPC message from bash? 

Looking here:
http://tldp.org/LDP/lpg/node7.html

I don't know what to do. Also looking to use Go and Python to send a Node.js parent process a message via IPC.

**Comment by bnoordhuis** [comment]
It's just JSON over a file descriptor that is passed to the child process.  If you don't have a reference to the file descriptor, you're out of luck - although on Linux you can probably obtain one by opening `/proc/<pid>/fd/<num>`.

Having two processes simultaneously send IPC messages is likely a recipe for disaster, though.

**Comment by ORESoftware** [comment]
Bnoordhouis - thanks for the heads, didn't follow what you mean. Certainly you dont mean two child processes sending messages to the same parent. How did you mean? My use case is just one parent multiple children, messages between children and parent, not between children.

**Comment by bnoordhuis** [comment]
What I mean is when you have a child process with an IPC file descriptor, then have another process copy (and use) that file descriptor.  That's unlikely to end well.

**Comment by ORESoftware** [comment]
Ok let me think about that. What do you think of Craig's answer to the SO
question? Link at the top of this thread.

**Comment by bnoordhuis** [comment]
That answer is not wrong but NODE_CHANNEL_FD is an undocumented property.  I don't expect it to change anytime soon but you should be aware that it could change or disappear when you upgrade node.

**Comment by ORESoftware** [comment]
alright thanks, I am going to go through some of the source

**Comment by ORESoftware** [comment]
FWIW it seems to be documented here

https://github.com/nodejs/node/blob/479822c45ef527386390227a1f8e086f6128d9e8/doc/api/child_process.md

**Comment by bnoordhuis** [comment]
Oh, then I take back my words.  I didn't intend for it to be an official thing when I added it but that's five or six years ago now.

**Comment by ORESoftware** [comment]
It's in the docs! ;)

**Comment by ORESoftware** [comment]
So, the bash thing was just an experiment. What I more likely looking to do, is set up communication between node.js and {python/go/java/web browser, etc}.

I figure with those requirements, that Websockets would probably be the best way to do IPC. I still don't really know how Node.js implements IPC between Node.js processes, and am still learning about this stuff :)

If you can think of something better than Websockets as a way to communicate between each of these programs, then let me know!

**Comment by bnoordhuis** [comment]
We use newline delimited JSON over a UNIX socketpair but if something like websockets is an option, I'd use that if I were you.  That way you are in control and you won't be subject to changes and limitations in node's IPC implementation.
