### ISSUE TITLE
How get to latest version of node:test

### ISSUE THREAD

**Issue by Andy-d-g** [nodejs/help#3978]
### Details

Hello,

I want to use node:test latest package version (18.8) to get `beforeEach` function.

When I change the node version to 18.9, node:test package return only `{ test as default, test, describe, it }`.

It seems to be the 18.0.0 version.

I was using nvm, so I was thinking that it can be the source of my issue.

I've uninstall node and nvm, reinstall node with the correct version, it doesn't change anything.

Do you know how to update node:test package ?

Thank you

### Node.js version

Not applicable.

### Example code

I use node 18.8
But the package (node:test) seems locked to 18.0

### Operating system

macOS Monterey
Version 12.3.1

### Scope

Installation / Upgrade

### Module and version

node:test

**Comment by MoLow** [comment]
how exactly do you install node and import the package?
results on my machine, using nvm:
```js
Welcome to Node.js v18.7.0.
Type ".help" for more information.
> require('node:test').beforeEach
undefined
```

```js
Welcome to Node.js v18.8.0.
Type ".help" for more information.
> require('node:test').beforeEach
[Function (anonymous)]
```

```js
Welcome to Node.js v18.9.0.
Type ".help" for more information.
> require('node:test').beforeEach
[Function (anonymous)]
```

**Comment by Andy-d-g** [comment]
I have forget to import `beforeEach` function into my project, my bad...
