### ISSUE TITLE
Net module replacement

### ISSUE THREAD

**Issue by 1vadios** [nodejs/help#398]
Hi, I’m trying to use the library mysql on a client in combination with Cordova.
It works until the program reaches the point where it has to connect to the database. The problem is that the function for the connect isn’t defined in the bundle.js.

Error:
Uncaught TypeError: Net.createConnection is not a function

I know that the core net module is transformed into an empty object. Now my question is there a workaround to use the module on client side, or is there a recomended library to solve my problem?

Thanks already for the help.

**Comment by lordKnighton** [comment]
Closing issue, let us know if you still could use help. Sorry we couldn't get to this sooner. Happy coding 💯
