### ISSUE TITLE
Order of nextTicks and microtasks

### ISSUE THREAD

**Issue by dSalieri** [nodejs/help#3984]
### Details

When I was writting some code I bump into incorrect as I think behaviour of nextTick queue and microtask queue.

Ok, example of the code will be the following:
```JavaScript
process.nextTick(() => console.log(1));
Promise.resolve().then(() => console.log(2));
Promise.resolve().then(() => console.log(3));
setImmediate(() => {
  Promise.resolve().then(() => console.log(4));
  process.nextTick(() => console.log(5));
});
```
it will output:
```
2
3
1
5
4
```

However, If I'll wrap that code into `setTimeout` you will see another order of outputs:
```
1
2
3
5
4
```
So why do I see that microtask will be first rather than nextTick without wrapping by `setTimeout`?

### Node.js version

v18.9.0

### Example code

All has been described in details section.

### Operating system

Windows 10

### Scope

Runtime

### Module and version

There are no modules in usage

**Comment by siddiq-rehman** [comment]
I am not able to replicate the code results when you are running without encapsulating the code in set Timeout. Please provide some more information!!

**Comment by dSalieri** [comment]
@siddiq-rehman first one was performed like `.mjs`, second one was performed like `.js`
