### ISSUE TITLE
Using child process to run kernel process to interpret hashbang

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#399]
I have this question on SO:

http://stackoverflow.com/questions/41067872/differentiate-between-bash-and-sh-via-child-process

I am wondering if there is a way to launch a process with Node.js that can execute a shell script and properly interpret the hashbang so that the right interpreter (bash or sh, or whatever) is invoked.

If I launch a child process with sh or bash like so:

```
const n = cp.spawn('sh', [file]);
// or
const n = cp.spawn('bash', [file]);
```

then either `bash` or `sh` will get used to interpret the file and the hashbang will get ignored.

Any idea if node.js can launch some process that can interpret the hashbang properly?

The reason this is a problem is that my program is launch shell scripts that I did not author, they are other developers shell scripts, so unless they use a convention of naming their files with the right extension (.sh and .bash) I will have no way of knowing what interpreter to use to run the script. The only way to know would be via hashbang.

**Comment by ORESoftware** [comment]
Doing some more research, I am thinking that the 'exec' command will invoke the kernel process that can do this (?)

**Comment by ORESoftware** [comment]
If I do this:

```js
 const n = cp.spawn('exec', ['file.sh']);
```

I get an error:

```
 Error: spawn exec ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) 

```

the error originates here:

```
    n.on('error', function (err) {
        console.error('\n',err.stack || err,'\n');   // here
      });

```

**Comment by bnoordhuis** [comment]
Looks like you figured out a solution?  I'll go ahead and close the issue.

**Comment by ORESoftware** [comment]
yep, thanks anyway
