### ISSUE TITLE
Node.js didn't install certain dependencies.

### ISSUE THREAD

**Issue by ayushiamazing** [nodejs/help#3998]
### Details

Last time when I installed Node.js (with dependencies) it installed Windows SDK and it's addon (with many others) but today after resetting my PC I tried to install Node.js (with dependencies option ticked [installation using chocolatey]) but it didn't install the Windows SDK neither it's addon. 
I tried to run the 'Install additional tools for node.js' Cmd file but it still didn't fix it. 
Neither running 'choco install visualstudio2019-workload-vctools' in powershell (admin) did something.

Is there a problem regarding my installation or its just removed?

### Node.js version

16.18.0 LTS

### Operating system

Windows 10 Pro for Workstations

### Scope

Missing Node.js dependencies 

### Module and version

Not applicable.

**Comment by ayushiamazing** [comment]
I have the other tools installed. (Vs.... c++ redistributable...)

**Comment by Martamk105** [comment]
> I have the other tools installed. (Vs.... c++ redistributable...)

**Comment by ayushiamazing** [comment]
> > I have the other tools installed. (Vs.... c++ redistributable...)

?

**Comment by ayushiamazing** [comment]
Closed!
