### ISSUE TITLE
Node module version 

### ISSUE THREAD

**Issue by jurajzecic** [nodejs/help#4000]
### Details

Hi, 
i can't run my code, it says:

was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module

### Node.js version

Node.js 19.0.0

### Example code

was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module

### Operating system

Windows 11 pro

### Scope

was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
You're using a dependency that is a [C++ addon](https://nodejs.org/api/addons.html) and needs to be compiled before use, however in your case it was compiled against a different version of Node.js than the current one.

To fix this you need to uninstall that dependency and reinstall it to recompile it and use it, if you're unsure which dependency causes that issue you can try removing your `node_modules` directory and your `package-lock.json` file, and run `npm install` to reinstall all dependencies and also recompile the C++ addons against your current Node.js version.

**Comment by DanBurkhardt** [comment]
for anyone else dealing with this, instead of going module-by-module, you can update all node packages globally with 

```shell
npm update -g
```

for me this was an error related to my version of node-pty and updating all global pkgs was the fix.
