### ISSUE TITLE
ReferenceError: URLPattern is not defined

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/help#4001]
### Details

```sh
const pattern = new URLPattern({pathname: `/${lang}/blog`,})
                ^
ReferenceError: URLPattern is not defined
```

### Node.js version

v18.9.1

### Example code

```JS
const lang = ["fr", "en"]

const pattern = new URLPattern({pathname: `/${lang}/blog`,})

console.log(pattern.test('http://example.com/en/blog'));
``` 

### Operating system

macOS 12.6

### Scope

Is URLPattern functional on Node?

### Module and version

//

**Comment by VoltrexMaster** [comment]
The [`URLPattern`](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern) API is still experimental and not yet implemented entirely, you can check the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern#browser_compatibility) for more information.

**Comment by AugustinMauroy** [comment]
There is no information for node 🥲

**Comment by AugustinMauroy** [comment]
@VoltrexMaster  Any ideas?

**Comment by VoltrexMaster** [comment]
> @VoltrexMaster  Any ideas?

It'll be shown when it's available in Node.js, so far it's unknown when it'll be fully implemented as it's still an experimental API.

**Comment by AugustinMauroy** [comment]
> > @VoltrexMaster  Any ideas?
> 
> It'll be shown when it's available in Node.js, so far it's unknown when it'll be fully implemented as it's still an experimental API.

How can I get this experimental feature?

**Comment by VoltrexMaster** [comment]
> How can I get this experimental feature?

You can't yet, it's available in some web browsers and you can check the compatibility tables I mentioned to see it's available for which ones exactly, but to use it in Node.js you'll have to wait until it's properly implemented.

**Comment by arjunyel** [comment]
@AugustinMauroy I'm getting the same issue, gonna use this polyfill https://github.com/kenchris/urlpattern-polyfill

**Comment by AugustinMauroy** [comment]
Thanks it's interesting

**Comment by AugustinMauroy** [comment]
It's just unimplemented. Thanks everyone!
