### ISSUE TITLE
how to open multiple files on macos with spawn 

### ISSUE THREAD

**Issue by Shivareddy-Aluri** [nodejs/help#4004]
### Details

i'm trying to open multiple file on an app on macos,
say my app is vsCode and i need multiple file to open . on macos i'm trying this
spawn('open', ['-a', vscode-path, 'filepath1 filepath2 filepath2'], opts)
its not working..
if i give a single path it works. is there any way to open multiple files?
in my terminal
open -a "vscode-path" filepath1 filepath2 filepath3 works

please help!

### Node.js version

 v16.13.0

### Operating system

Mac Os

### Scope

others

### Module and version

Not applicable.

**Comment by ErickWendel** [comment]
to run multiple commands you would use the flag `shell: true`

```js
spaw('open file1.js file2.mjs', {shell: true})
```
I'm not sure if you're running the `open` command correctly. Try running it out of your node.js application and make sure the `open` command is running as expected

**Comment by Shivareddy-Aluri** [comment]
@ErickWendel where should i give the app name on which i wanted the files to be open. in your command you just gave open. and also we might have files with spaces in them, in that case how the above command you mentioned will work?

**Comment by GabenGar** [comment]
You have to write it as `['-a', vscode-path, 'filepath1', 'filepath2', 'filepath2']`. Otherwise `spawn()` will surround it in quotes and pass as a single value, which is not a valid path for `open()`.
