### ISSUE TITLE
Linux Odd numbered Node.js versions will not enter LTS warning

### ISSUE THREAD

**Issue by QuentiumYT** [nodejs/help#4005]
Hello, I recently installed Node 19 from the nodejs repository (upgrading fro 18) and this is the first odd version I install in my Ubuntu machine.

Since then, every time I open the console, I have this warning message:
```
Node.js version v19.0.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
```

I am looking for a way to disable this info message because I know that it's a non LTS version and I am aware of that. I'm using it for early development purposes only. Is there something to do about it?

**Comment by richardlau** [comment]
This message isn't coming from anything in the official Node.js releases -- nothing we have does any kind of version checks, although such a feature is being discussed in https://github.com/nodejs/node/issues/44942.

Are you using angular?
- https://github.com/nodejs/help/issues/3602
- https://github.com/angular/angular-cli/issues/24104

**Comment by RaisinTen** [comment]
I agree with what Richard said. The message is coming from the angular-cli, which is a different project: https://github.com/angular/angular-cli/blob/1e4dbfdf4afb03a215db620fb0e0db6f86cdac63/packages/angular/cli/bin/ng.js#L39-L45.

**Comment by QuentiumYT** [comment]
Oh alright, thanks for the info. Had a look about the stackoverflow thread but haven't noticed angular/cli was causing that on my shell (at startup). Will remove angular probably

Thanks for the tips and the research about this issue :)
