### ISSUE TITLE
Does the Node.js site host pre-built versions of libnode?

### ISSUE THREAD

**Issue by Qix-** [nodejs/help#4006]
### Details

Is there a way to obtain pre-built shared libraries for the Node.js runtime (i.e. `./configure --shared && make` targets)? Or is the only way to get `libnode.{so,dylib}` to build from source?

It's not a problem to build from source, it just takes a lot of extra time.

Thanks for any info :)

### Node.js version

Not applicable.

### Operating system

N/A

### Scope

Installation

### Module and version

N/A

**Comment by richardlau** [comment]
No, we do not host pre-built binaries for Node.js as a shared library.
