### ISSUE TITLE
running dev has problem

### ISSUE THREAD

**Issue by MrPoP** [nodejs/help#4009]
### Details

Hello everyone
iam now facing simple problem and need your help in it
iam using ubunto wsl2
when iam trying to run this command
`sail up -d && npm run dev`
i got simple error
`CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
error when starting dev server:
Error: EPERM: operation not permitted, scandir 'C:\Windows\CSC'`
what can be done in this case

### Node.js version

v8.10.0

### Operating system

Windows 11

### Scope

Starting

### Module and version

Not applicable.

**Comment by bmuenzenmeyer** [comment]
- Does the behavior persist if you upgrade to a new version of Node.js? This reported version is [end of life](https://github.com/nodejs/release#release-schedule).
- Have you attempted to ask this question within other communities, such as [stackoverflow](https://stackoverflow.com/questions/tagged/node.js?tab=Newest) or laravel forums?
