### ISSUE TITLE
Incorrect Login Details were provided.

### ISSUE THREAD

**Issue by LamboCreeper** [nodejs/help#401]
Hey,

I keep getting the error `(node:11190) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Incorrect login details were provided.` when running a node program on my VPS and I don't know why. I've tried reinstalling Node, but this doesn't seem to fix it. If anyone knows why this happens and how to fix it I would appreciate it.

Thanks.

**Comment by bnoordhuis** [comment]
Your program is apparently using promises but not handling rejections properly.  Try starting node with `--trace-warnings --trace-deprecation`, that should give you a useful stack trace.
