### ISSUE TITLE
Run node from C++ with inspect option

### ISSUE THREAD

**Issue by vincent-herlemont** [nodejs/help#4015]
### Details

Is possible to run NodeJS 12 from C++ with inspect option?

I fail to do that, here the code:
```cpp
std::string binary = "node";
std::vector<std::string> argsVec;
argsVec.push_back(binary);
argsVec.push_back("--inspect=0.0.0.0:8010");
argsVec.push_back(scriptPath);
...
node::Start(argc, argv);
```

Logs:
```console
node: bad option: --inspect=0.0.0.0:8009
```

### Node.js version

NodeJS 12.x

### Operating system

Android

### Scope

Using as a library.

**Comment by preveen-stack** [comment]
can you share a more complete code to reproduce the issue
