### ISSUE TITLE
Too many connections cause node crash

### ISSUE THREAD

**Issue by ryohetoy** [nodejs/help#4017]
### Details

My node program is crashed without any log. I run the program below with node index.js.

I think it might be memory problem because of too many curl connections. But how to figure out it?

Thank you in advance!

### Node.js version

v16.13.1

### Example code

```node.js
const childProcess = require('child_process')
const util = require('util');
const exec = util.promisify(childProcess.exec);

console.time('total');
console.log("start");
const urlList = Array(500).fill("https://google.com");
const pList = urlList.map(function(url) {
    return exec('curl --max-time 20 --connect-timeout 10 -iSs "' + url + '"', function (error, stdout, stderr) { });
});
Promise.all(pList).then(() => {
    console.timeEnd('total');
}).catch((e) => {
    console.log('error: ' + e);
});
```

### Operating system

Mac OS Monterey 12.6

### Scope

runtime

### Module and version

Not applicable.

**Comment by ErickWendel** [comment]
it seems you're ignoring errors. The errors usually occurs on this section `function (error, stdout, stderr) { }`

```js
  return new Promise((resolve, reject) => {
    exec('curl --max-time 20 --connect-timeout 10 -iSs "' + url + '"', function (error, stdout, stderr) { 
    if(error) return reject(error)
    // just log results to check it out
    console.log('stdout', stdout)
    console.log('stderr', stderr)
    
    return resolve()
    });
  })
    
```

Please, if this answered your question, consider closing this issue
