### ISSUE TITLE
Warning: Gulp Version mismatch

### ISSUE THREAD

**Issue by bhupendra-chetu** [nodejs/help#402]
Hi,

I am getting the below issue when executing gulp command on Node command prompt.
Warning: gulp version mismatch:
Global gulp is 3.9.1
Local gulp is 3.9.0

Can anybody assist me how can i resolve this issue. I visit many articles and try to update gulp and all possible solution suggest by many person in the article but the issue still persist.

Please let me know if any additional information is required. Below is the screenshot.

![issue](https://cloud.githubusercontent.com/assets/16085795/21100030/bfa4b5c8-c097-11e6-9920-89c5b78d2618.png)

Thanks,
Vipin

**Comment by lordKnighton** [comment]
npm update gulp -g
Update the local: cd /your/folder/
npm update gulp
