### ISSUE TITLE
Create React App

### ISSUE THREAD

**Issue by SensSebastianSchlosser** [nodejs/help#4020]
### Version

18.12.0, 18.12.1

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### What steps will reproduce the bug?

npx create-react-app my-app

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

It should create an react-app

### What do you see instead?

npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in: (Blurred paths)

### Additional information

0 verbose cli C:\Program Files\nodejs\node.exe D:\Programme\nvm\v16.17.0\node_modules\npm\bin\npm-cli.js
1 info using npm@8.15.0
2 info using node@v16.17.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:[...]\v16.17.0\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 3ms
10 timing config:load:file:[...]\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:[...]\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 0ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 10ms
18 timing npm:load:configload Completed in 10ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm exec create-react-app smartsignal-status
22 verbose argv "exec" "--" "create-react-app" "smartsignal-status"
23 timing npm:load:setTitle Completed in 1ms
24 timing config:load:flatten Completed in 2ms
25 timing npm:load:display Completed in 4ms
26 verbose logfile logs-max:10 dir:[...]\AppData\Local\npm-cache\_logs
27 verbose logfile [...]AppData\Local\npm-cache\_logs\2022-11-07T07_53_33_729Z-debug-0.log
28 timing npm:load:logFile Completed in 5ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 22ms
32 silly logfile start cleaning logs, removing 65 files
33 timing arborist:ctor Completed in 1ms
34 silly logfile done cleaning log files
35 http fetch GET 200 https://registry.npmjs.org/create-react-app 72ms (cache miss)
36 timing arborist:ctor Completed in 0ms
37 timing arborist:ctor Completed in 0ms
38 http fetch GET 200 https://registry.npmjs.org/npm 213ms (cache updated)
39 timing command:exec Completed in 62134ms
40 notice
40 notice New [33mminor[39m version of npm available! [31m8.15.0[39m -> [32m8.19.3[39m
40 notice Changelog: [36mhttps://github.com/npm/cli/releases/tag/v8.19.3[39m
40 notice Run [32mnpm install -g npm@8.19.3[39m to update!
40 notice
41 verbose exit 0
42 timing npm Completed in 64705ms
43 info ok

**Comment by marsonya** [comment]
Hi @SensSebastianSchlosser, this is not a node.js issue.
Best place to file this issue and get it resolved would be https://github.com/facebook/create-react-app

**Comment by petronews** [comment]
good
