### ISSUE TITLE
TypeError: Cannot assign to read only property 'totalSocketCount' of object '#<Agent>' 

### ISSUE THREAD

**Issue by adriangiulianotucci** [nodejs/help#4022]
### Details

Hi i'm keep seeing this error in my API and it occurs randomly:

TypeError: Cannot assign to read only property 'totalSocketCount' of object '#<Agent>' 

Can someone give me a hint? I can't find anything helpful.

Thanks!

### Node.js version

v16.18.1

### Operating system

Linux (Heroku dyno)

### Scope

runtime

### Module and version

Not applicable.

**Comment by ErickWendel** [comment]
Hello, could you provide some code snippets so I can that a look at it?

**Comment by krrishdholakia** [comment]
You can try to debug the code by looking at the source and checking if the 'totalSocketCount' property is being set to a non-writable value. If it is, then you may need to adjust the code to make sure that the property is writable. Additionally, you can try to trace back the origin of the error to see if there is a specific action or input that triggers it. - [Clerkie](https://bit.ly/clerkie_ai_github)
