### ISSUE TITLE
[help] memory error  in pkg     nodejs   game server!

### ISSUE THREAD

**Issue by panpan2020** [nodejs/help#4023]
use pkg compile game server as one programe,   run at centos7.

pkg command:  
   pkg -t node12-linux-x64 package.json --options max_old_space_size=16384

After the Nodejs game server runs for a period of time, it is occasionally killed by the system. The system records the kill log as follows:

Nov  7 04:12:54  kernel:  miniGame [30231]: segfault at a0 ip 0000000000abca1b sp 00007ffd58090eb0 error 4 in  miniGame
[7a2000+120f000]

**Comment by ErickWendel** [comment]
How about you run it without packaging it? Does it still crash? Do you have any Application Performance Monitoring app running there? segfault usually happens in the C++ land when there's not enough memory or trying to access some resources that are not available
