### ISSUE TITLE
Node keeps updating on my system, then stops working altogether

### ISSUE THREAD

**Issue by LoreCrux** [nodejs/help#4024]
### Version

18.12.0

### Platform

Microsoft Windows NT 10.0.19042.0 x64

### What steps will reproduce the bug?

Unfortunately there aren't specific steps, it'll randomly happen when I am working in VS Code.

### How often does it reproduce? Is there a required condition?

It happens daily, there is no specific condition to trigger this.

### What is the expected behavior?

Node should not update on it's own and stop working altogether.

### What do you see instead?

I originally installed v18.12.0 and had not updated to a new version.  When Node updates on its own, I type in `node -v` and get the error: 
`& : The term 'node.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

I checked my PATH for both the User and System and it is still showing correctly.

When I go to Add or Remove programs in the System Settings and search for Node, the version now shows 19.0.1 instead of 18.12.0.

The only way to fix it is to completely reinstall Node.

### Additional information

VS Code version info

![image](https://user-images.githubusercontent.com/40617919/201213560-d7f583d5-416c-4701-8adc-331d12b522bb.png)

**Comment by LoreCrux** [comment]
Ya I figured so, but I can only report what I observed lol

Are there any logs I can send your way or someway of helping?

**Comment by Trott** [comment]
@nodejs/platform-windows

**Comment by LoreCrux** [comment]
404 Page Not Found

**Comment by LoreCrux** [comment]
> @nodejs/platform-windows

The page is returning a 404.

**Comment by tniessen** [comment]
This is likely caused by some software on your computer (that is not Node.js). Maybe VS Code or some extension of VS Code? There is probably a way to trace what program initiated installation with some Windows tools, but I don't know any specifics.

**Comment by LoreCrux** [comment]
I looked through the Windows Logs and found that this was installing Node:

`Beginning a Windows Installer transaction: C:\ProgramData\MspPlatform\PME\ThirdPartyPatch\Downloads\7c5cde88-b341-4bb7-ad10-abfb00a1f565\node-v19.0.1-x64.msi`

Not sure if this helps.

**Comment by lokesh-dev** [comment]
I facing the same issue some how node.js is getting upgraded from 16.14 (original) to 19.0.x then node.exe file is getting deleted. It happened twice this month.

**Comment by ShubhamKaushal001** [comment]
@LoreCrux,
Hi, Please try using nvm. It can solve your issue by preventing auto update and focusing on the version you installed
To start using it,
1. Download nvm and set path in environment variables.
2. Open terminal on the project location and install the version you want by command nvm install 16.14
3. Then use that version by command nvm use 16.14
