### ISSUE TITLE
Nodejs no longer working

### ISSUE THREAD

**Issue by Larry-Lars** [nodejs/help#4025]
### Details

Context: Using Nodejs and SublimeText 3. Using XLXS package (Sheetjs) to read and combine Excel documents. I was combining 10 docs at a time. When experimenting with my code and paired down to combining just 2, Nodejs crashed. I can no longer open NodeJS. the NodeJS command prompt states: 

```
<--- Last few GCs --->


<--- JS stacktrace --->


#
# Fatal javascript OOM in GC during deserialization
#

Your environment has been set up for using Node.js  and npm.
```

I've rebooted my computer, still does not work. I've uninstalled and reinstalled nodejs, still has the same problem. I would report this as a bug, but I don't know what caused it or how to reproduce it. Right now I just want any kind of fix.

### Node.js version

18.12.1

### Operating system

Windows 10
Processor: AMD Ryzen 5 2600X Six-Core Processor              3.60 GHz
64 bit

### Scope

nodejs not working, command prompt error, will not execute any javascript programs.

### Module and version

XLMS (Sheetjs)

**Comment by ErickWendel** [comment]
It seems to be a problem with the Windows OS. Try using the WSL or use Docker instead
