### ISSUE TITLE
Installer unfindable

### ISSUE THREAD

**Issue by StephanEggermont** [nodejs/help#4029]
### Details

The installer repo is archived without a link to where development now happens. 

### Node.js version

Not applicable.

### Operating system

Not applicable.

### Scope

Not applicable.

### Module and version

Not applicable.

**Comment by ErickWendel** [comment]
You should find the installer at [nodejs.org/](https://nodejs.org/en/download/)

**Comment by StephanEggermont** [comment]
That does not answer the question

**Comment by RedYetiDev** [comment]
Currently, your question lacks guidance, and it may hard for us to see the exact issue.

**Comment by richardlau** [comment]
Installer source for installers downloadable from https://nodejs.org/en/download/ is:
- Windows: https://github.com/nodejs/node/tree/main/tools/msvs
- macOS: https://github.com/nodejs/node/tree/main/tools/macos-installer

https://github.com/nodejs/installer (now archived) was an attempt to write a replacement(?) cross-platform installer for Node.js that stalled out.
