### ISSUE TITLE
Require and write a new module

### ISSUE THREAD

**Issue by ev1stensberg** [nodejs/help#403]
I've hit a cornerstone in my project whereas I need to add an item to an array that is a module. After adding it, I want to leave the module untouched. The expected behaviour is that it only adds a line of code to my project, but it doesn't. Instead it inlines the object using `serialize-javascript`. If I were to use template literals or `.toString()` it returns an file with `[Object object]`. 

To reproduce: 

[https://github.com/ev1stensberg/mink]()

1. Download the project
2. Run mink -r and click enter a bunch of times.
3. Go to `lib/refactor-configuration`
4. Issue is from `lib/write-loaders`

Thanks! 

![skjermbilde 2016-12-12 kl 08 40 47](https://cloud.githubusercontent.com/assets/16735925/21106558/d2d09878-c08e-11e6-838e-ce13befb8bb0.png)
![skjermbilde 2016-12-12 kl 16 39 39](https://cloud.githubusercontent.com/assets/16735925/21106563/d76b2614-c08e-11e6-9a26-a1f156091105.png)
![skjermbilde 2016-12-12 kl 08 40 25](https://cloud.githubusercontent.com/assets/16735925/21106568/dd098160-c08e-11e6-813f-1e4f422374e6.png)

**Comment by bnoordhuis** [comment]
I don't see a lib/write-loaders in your project.  What did I miss?

Aside: https://github.com/ev1stensberg/mink in your comment is a link to this issue, not your repo; you wrote `[https://github.com/ev1stensberg/mink]()`.

**Comment by ev1stensberg** [comment]
Oh, right! `lib/utils` **

**Comment by bnoordhuis** [comment]
Is your expection that calling `require('foo.js')`, updating foo.js, then calling `require('foo.js')` again reads the new foo.js?  It won't unless you delete it from `require.cache` first.  Note that `require.cache` is local to the calling script.

**Comment by ev1stensberg** [comment]
Yeah that was intended, but I need it to psychically write the new content. Possible, yes/no?

**Comment by bnoordhuis** [comment]
> psychically

You mean physically?  Yes, as long as you `delete require.cache[require.resolve('name')]` in the scripts that re-require the module.

**Comment by ev1stensberg** [comment]
Yeah, that's more like it. I'll try, thanks for helping out!
