### ISSUE TITLE
How to debug my own test code

### ISSUE THREAD

**Issue by WonJo-Jung** [nodejs/help#4031]
### Details

I'm trying to contribute to node.js for the first time, but I cannot debug my own test code(extension : mjs). I'm wondering how to debug test code without any debugging framework, not simply run it.

### Node.js version

v.20.0.0-pre

### Example code

```js
import assert from 'node:assert';
import { test } from "node:test";

const testName = 'anything with newline \nnot ok';

test(testName, () => {
    assert.equal(true, true);
});
```

### Operating system

Linux wonjo-VirtualBox 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Scope

maybe runtime

### Module and version

Not applicable.

**Comment by ErickWendel** [comment]
If you use VSCode, you can simply hit `F5`, select Node.js and then debug it:
![image](https://user-images.githubusercontent.com/8060102/202726766-d7c4c3f3-2e19-4341-bf1e-9b5ca4041486.png)



You can also use Chrome or any other Node.js inspector using the `--inspector-brk` flag do it by:

`node --inspect-brk test.mjs`

It'll generate an URL for you such as:
```sh
Debugger listening on ws://127.0.0.1:9229/4a28f153-a050-4420-a896-84407f867068
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

if You open the Chrome Browser, you'll notice a Node.js icon there
<img width="487" alt="image" src="https://user-images.githubusercontent.com/8060102/202726275-19238e44-db41-40de-a13c-a17af58df5f4.png">

So when you open it, you'll be able to debug it on Chrome.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/8060102/202725937-46e51a74-a9e6-43b3-8a40-c4da9368dc54.png">

**Comment by WonJo-Jung** [comment]
It helps me a lot! I appreciate it!
