### ISSUE TITLE
node:fs

### ISSUE THREAD

**Issue by Behzad970** [nodejs/help#4036]
### Details

I have tried using node file system (fs) functions such as readFile and writeFile functions using them with fs.promises and run into several problems. I am using node.js in my Mvc project in Visual Studio 2017 with module: es6. Even when I change to module: commonjs I still cannot use fs. Also, I was not able to install the new version of fs from npm. They have some how stopped that due to security issues. If there is an alternative for fs, please let me know. I would appreciate you help on this issue. 
Yours truly
B.Mona

### Node.js version

Version 19.1.0

### Example code

My typescript code:
import { promises } from 'fs';
import { resolve } from 'path';
Promise.all([
    promises.readFile(resolve(__dirname, 'file1.txt')),
    promises.readFile(resolve(__dirname, 'file2.txt')),
]).then((files) => {
    promises.writeFile(resolve(__dirname, 'output.txt'), files.
        join('\n'));
});
The error I am receiving from bundle.js (The bundles javascript file)
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'readFile'

 

### Operating system

Windows 8.1 64 bit with internet explorer 11

### Scope

I am using webpack, babel, and browserify respectively to bundle the javascript file transpired by typescript.

### Module and version

Not applicable.

**Comment by marco-ippolito** [comment]
the correct import 
`import { readFile, writeFile } from "fs/promises";`

**Comment by preveen-stack** [comment]
@Behzad970 Did the above solution fixed your issue?

**Comment by RedYetiDev** [comment]
*(No response, assuming resolved)*
