### ISSUE TITLE
Get the js stack trace of a running nodejs process

### ISSUE THREAD

**Issue by ericzhucode** [nodejs/help#4039]
### Details

Background: If there's an infinite loop in js script, it would be hard to find it. Currently if we found a nodejs process stucks, we would use nodejs debug feature to attach to that process and then pause it, in that way we can find the code of the infinite loop like
![image](https://user-images.githubusercontent.com/85340915/204082745-46f4e14d-31f6-4551-b59c-21cbe008343a.png)

I'm wondering if there's any params or tools of nodejs to help us output all stack trace of running nodejs process to a log file, so that we can find the infinite loop?

Or is there any other better ways to find the exact code of an infinite loop?
Thank you for your help!

### Node.js version

All versions

### Operating system

All systems

### Scope

code

### Module and version

Not applicable.

**Comment by MoLow** [comment]
@ericzhucode you can fire a `SIGUSR1` signal at the process, that will allow you connecting with a debugger

**Comment by MoLow** [comment]
See https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by ericzhucode** [comment]
> @ericzhucode you can fire a `SIGUSR1` signal at the process, that will allow you connecting with a debugger

Yes I know that and actually if you use vscode to debug nodejs via pid then vscode will automatially send `SIGUSR1` signal to that process so that we can attach via a debugger.
However, what we want is to output the stack trace to a log so that supporters can collect that info from user and send to our developers. Supporters may not be able to use IDE to debug so developers will have to join the meeting every time this kind of issue occured.
Is there any way to output the stack trace to a log?

**Comment by iloveitaly** [comment]
Same question on my end, would love to know if this is possible @MoLow! Thanks for all your help.

**Comment by artur-ma** [comment]
Maybe this one can help here

https://blog.apify.com/how-to-debug-an-infinite-loop-in-node-js-production-code/

**Comment by preveen-stack** [comment]
@ericzhucode Were you able to try out the suggestions above?

**Comment by molixiaoge** [comment]
So, what's the final plan? I need it too.
