### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by jbeja** [nodejs/help#404]
Windows 10 64bits
Node v7.2.1
```

C:\Users\Usuario\Code\ts\quickstart>npm install --unsafe-perm
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\browser-sync\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

After that, the package installation stops.

**Comment by addaleax** [comment]
That does not actually look like an error. It might be helpful to know more about what exactly you are doing, and what is not working?

**Comment by jbeja** [comment]
[Pretty much the Angular js "quickstart" setup](https://angular.io/docs/ts/latest/guide/setup.html)

**Comment by addaleax** [comment]
> I couldn't get further than `npm install` because it just breaks.

Can you go into more detail? How do you know that it didn’t work?

When `npm` writes output like `npm WARN …`, those are warnings, and in this case it should be safe to simply ignore them.

**Comment by jbeja** [comment]
Hmn, apparently trying gain made it work. Closing this, thanks for your time anyways.

**Comment by lordKnighton** [comment]
Try `npm install --no-optional`   from  https://github.com/webpack/webpack/issues/1435
