### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by KevinMorales30** [nodejs/help#4040]
### Details

Ni idea de que pasa con le programa 
![Screenshot 2022-11-09 114541](https://user-images.githubusercontent.com/108624472/204109408-303225a6-18a5-4b3c-ab51-68eddaa5de2e.png)

### Node.js version

Not applicable.

### Operating system

win 11

### Scope

ND

### Module and version

Not applicable.

**Comment by hassonor** [comment]
Try to:
1. Remove node_modules
2.  npm cache clean -force
3. npm install
4. And try to run it again

**Comment by ShubhamKaushal001** [comment]
Hola @KevinMorales30
Intente configurar la variable del sistema de entorno como nombre NVM_SYMLINK y proporcione la ruta de la carpeta del nodo que está instalada en su máquina local. Y si está utilizando nvm en su sistema, configure también su variable de entorno

**Comment by preveen-stack** [comment]
@KevinMorales30 ¿Pudiste probar la sugerencia anterior?

**Comment by RedYetiDev** [comment]
Hi! The Node.js maintainers mostly speak English. It may be difficult for them to read your issue in it's current state.
