### ISSUE TITLE
Override the JSON stringify method in process.send()

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#4041]
### Details

I am calling `process.send(val)` with an IPC message between parent and child. The object val has some arbitrary circular references that are hard to prune reliably. I have a custom JSON stringify function that can handle circular refs. Is there a way to override the JSON.stringify method within process.send()?

Something like:

```js
const serializableObj = {
  [process.send.stringify](){
      return myCustomStringify(this);
  }
}
```

I posted this question on SO too:
https://stackoverflow.com/questions/74593815/override-the-json-stringify-method-in-process-send

### Node.js version

18

### Example code

see above.

### Operating system

MacOS

### Scope

code/runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
could you try out the solution proposed in your SO Post @ORESoftware
