### ISSUE TITLE
adding multiple NODE_OPTIONS(--openssl-legacy-provider --max_old_space_size) is not working

### ISSUE THREAD

**Issue by arunvenkat1911** [nodejs/help#4047]
### Details

HI Team, 

I am trying to set these multiple options. 

"scripts":{
"build":"set NODE_OPTIONS='--openssl-legacy-provider --max_old_space_size=8192' && webpack serve --open --config ../webpack.config.js --progress"
}

it is not working as expected. Attached the error image. 
![2022-12-09_14-52-03](https://user-images.githubusercontent.com/101084873/206717832-31f8c38f-a19f-4618-8428-dfe5f9b7bfac.png)

NOTE: when we try the options individually, they are fine. 

Please help me with the solution. 

Arun.

### Node.js version

18.2.1

### Operating system

windows 11

### Scope

runtime

### Module and version

Not applicable.

**Comment by Arcadix** [comment]
Hi, 

These node commands do not seem to work in windows. Please check. 

Arun.

**Comment by preveen-stack** [comment]
> I'll try to test this on my Windows machine too, but for now it seems as if both NODE_OPTIONS flags are being respected

@bmuenzenmeyer  were you able to check this on your windows machine
