### ISSUE TITLE
nodejs worker_thread usecase

### ISSUE THREAD

**Issue by vijayalakshmi427** [nodejs/help#4049]
### Details

Hello,
I am building a nodejs/express server which handles requests and executes users code. I wanted each user code to run in isolation, for reasons like one shouldn't access/cause problems to others, i.e., one can be CPU intensive and others can be a normal one.

I am planning to implement in below way using worker threads
- Exposing a end point such as /register, on register creating a worker thread and caching the worker object for that user by maintaining a map. Since creating worker threads per request is not optimal. This also gives ability to add new users at runtime without restarting server
- When there is a request for the user, server picks that worker thread and runs the user code in that.

I cannot maintain a worker pool, since user can maintain some state like a DB connection so creating a dedicated worker per user.

In my scenario user code may or may not be CPU intensive. I was using worker_threads mainly to maintain isolation, gives ability to add new users without restarting server and obviously CPU intensive operations wouldn't effect other threads.

I was reading about worker_threads and most of the suggestions is to use it for CPU intensive tasks, not really about isolation or parallelism. Please advise if worker_threads best fits this usecase (or) any other alternatives

### Node.js version

v16 LTS

### Operating system

Linux

### Scope

worker threads

### Module and version

Not applicable.

**Comment by krrishdholakia** [comment]
You can use the Node.js Worker Threads API to create a dedicated thread for each user, thus ensuring isolation and allowing you to add new users without restarting the server. You can also use the cluster module to manage the threads and ensure optimal utilization of the CPU. Alternatively, you could also consider using a container-based solution such as Docker to provide isolation and scalability. - [Clerkie](https://bit.ly/clerkie_ai_github)
