### ISSUE TITLE
Node.js process API seems not to be sending proper signal to Elasticsearch

### ISSUE THREAD

**Issue by tberne** [nodejs/help#405]
Hi,
I'm developing a Node script that kills an Elasticsearch instance.
The script is very simple ([see Gist](https://gist.github.com/tberne/7e23f5fa69c09ba7388720db2818afba)).
It just read a `es.pid` file, created by the Elasticsearch itself (when running witth `elasticsearch/bin/elasticsearch.bat -p ../../es.pid`) and sends a signal to that process.
When entering a `Ctrl+C` directly in keyboard, Elasticsearch perform a "clean" close.
But when I run my script, Elasticsearch is behaving as it received a -9 signal. It just closes without a proper shutdown.
As I've never programmed in Node before, i don't know whether it is a Node issue, an Elasticsearch issue, my script issue or all of them.
I've just tested in Windows 10, latest v6 Node, Elasticsearch 5.1.1.
I would appreciate some help.

**Comment by vsemozhetbyt** [comment]
@tberne What signal argument do you call your script with? What is `argv.s` value?

[There are signals that are not supported on Windows.](https://nodejs.org/dist/latest-v7.x/docs/api/process.html#process_signal_events)

**Comment by tberne** [comment]
@vsemozhetbyt, I've tried with 'SIGINT' and 'SIGTERM'.

**Comment by vsemozhetbyt** [comment]
@tberne I can only point out these doc fragments, sorry:

> `SIGTERM` is not supported on Windows...

> Note: Windows does not support sending signals, but Node.js offers some emulation with `process.kill()`, and `ChildProcess.kill()`. Sending signal `0` can be used to test for the existence of a process. Sending `SIGINT`, `SIGTERM`, and `SIGKILL` cause the unconditional termination of the target process.

I hope somebody will explain you more or will suggest a workaround.

**Comment by tberne** [comment]
> Sending SIGINT, SIGTERM, and SIGKILL cause the unconditional termination of the target process.
This explains everything. 
I just would like to know if this is a Node or Windows drawback...

**Comment by bnoordhuis** [comment]
> I just would like to know if this is a Node or Windows drawback...

Windows for not having signals, node for emulating it in this particular way (but what would it do differently?)

I'll close this out.
