### ISSUE TITLE
Print to a local printer via a remote server

### ISSUE THREAD

**Issue by mhmatos** [nodejs/help#4052]
Hello, I'm developing an application with Node.js in the backend and React JS in the frontend to command a restaurant and I would like to know if it is possible after recording the data in the backend in a cloud server (example: Digital Ocean), is it possible that the backend send the printout of the recorded data to a local (thermal) printer on the client machine.

**Comment by preveen-stack** [comment]
please take a look at https://www.npmjs.com/package/react-to-print. It can give you some ideas

**Comment by NisargDeveloper** [comment]
@mhmatos You got the solution?. I'm also working on a similar project. I have to print locally using nodejs code hosted on heroku or any other hosting platform.

**Comment by ljharb** [comment]
You can’t print locally over the web unless the document is local, and you can’t ever print in a browser headlessly. What you can do is download/display the file in the browser, and then have the user print it.

**Comment by tamil752002** [comment]
i Would Like To Get All My Printer List , which Is Connected My Network  ?  I n Node Js

**Comment by RedYetiDev** [comment]
This issue appears to be stale, so I've closed it. If you need more help, please open a new issue.

**Comment by rahul-5503** [comment]
> > please take a look at https://www.npmjs.com/package/react-to-print. It can give you some ideas
> 
> This is more like Control+P using the code. This will not work with nodejs

hi, i also working on restaurant webpage . need to print without displaying preview print page and direct print to print what ever printer connected to it in usb or wifi mode printers . if use know any solution are any one know solution plz share
