### ISSUE TITLE
Node silently crashes

### ISSUE THREAD

**Issue by d3x0r** [nodejs/help#4055]
### Details

 node silently crashes when awaiting an import - see example code.

catching it with --inspect-brk and steping through, a lot of the work is done, but something happens that causes node to exit before even logging the first console.log in the first script run.

```
node tst.mjs
```

(I did try to attach the .mjs files themselves, but they aren't an allowed extension)

### Node.js version

17/18 at least

### Example code

//----------- File1 : tst.mjs ----------------

``` js
import {Table} from "./tst_table.mjs";
Table.loadSeed = false;
import {vendors} from "./tst_vendors.mjs"
```

//----------- File2 : tst_table.mjs ----------------

``` js
export class Table {
	static loadSeed = true;
}
```
//----------- File3 : tst_vendors.mjs ----------------

``` js
import {Table} from "./tst_table.mjs";
export class vendors extends Table {}

console.log( "test load", Table.loadSeed );
// this method, if uncommented does the same thing, and works.
//if( Table.loadSeed ) import( "./tst_vendors_rows.mjs" ).then( module=> vendors.seed = module.get_vendors_rows() );

// this method of importing fails...
if( Table.loadSeed ) vendors.seed = (await import( "./tst_vendors_rows.mjs" )).get_vendors_rows();
```

//----------- File4 : tst_vendors_rows.mjs ----------------
``` js
import {vendors} from "./tst_vendors.mjs";
export async function get_vendors_rows() { return [ new vendors() ]; }
```

### Operating system

Windows (latest 18 version)/Ubuntu Linux (nvm use 17)

### Scope

runtime modules

### Module and version

Not applicable.

**Comment by krrishdholakia** [comment]
Does the issue still occur if you modify the code to use the import() syntax instead of await import()? - [Clerkie](https://bit.ly/clerkie_ai_github)

**Comment by d3x0r** [comment]
the import().then() does work.

**Comment by preveen-stack** [comment]
@d3x0r does this issue still persist?

**Comment by d3x0r** [comment]
Yes with 19.4.0 and 20.5.1.  There is a logging done in the tst_vendors.mjs module, but it still fails to complete processing.

//----------- revised File1 : tst.mjs ----------------

``` js
console.log( "table import" );
import {Table} from "./tst_table.mjs";
Table.loadSeed = false;
console.log( "Set load seed" );
import {vendors} from "./tst_vendors.mjs"

console.log( "Seed worked?", vendors.seed );
```

revising the tst.mjs none of that logging happens (this is the root module)
