### ISSUE TITLE
Preserve stdio order on windows

### ISSUE THREAD

**Issue by user7230724** [nodejs/help#4056]
### Details

We have an executable file (program) that is given to us and we cannot modify it. The program prints messages to stdout and stderr. The problem is that if the program detects that the stderr is not piped to anything but rather directly connected to the console, then the program does not respect the console encoding of stderr and just literally outputs ASCII, breaking apart unicode characters. That is a limitation of the executable and we cannot fix it.

We decided to use Node.js as a mediator between the program and the console. We want to write a Node.js script to read the output (stdout and stderr) from the program and output it to the console. The problem is that we didn't find a way to preserve the order of stdout and stderr. If we simply pipe stdout and stderr to `process.stdout`, the order of messages is not respected (it changes randomly).

We created a simple exe file (program) and a [repository](https://github.com/user7230724/test) to demonstrate the issue. The program first prints unicode character `∃` to stderr, then `x`  to stdout, then `∃` to stderr again and finally `y` to stdout. The expected output is `∃x∃y`. That's what our goal is.

If we run the program directly from the command line (by calling `test.exe`), the output is `âˆƒxâˆƒy`. That's the limitation of the program that we want to overcome using Node.js.

Our first attempt (see `1.js`) is to write a Node.js script to pipe the stdout and stderr to `process.stdout`. However, the output is inconsistent. Sometimes we get `∃xy∃` and sometimes `∃∃xy`. At least the unicode is properly printed, but the order is wrong.

Our second attempt (see `2.js`) is to use `process.stdout.fd` as the stdout and stderr of the child process. But the output is again `âˆƒxâˆƒy`. The program somehow detects that the stderr is a console and does not respect unicode.

Can someone please help us to write a simple Node.js script to obtain the output `∃x∃y` consistently?

### Node.js version

v18.7.0

### Example code

```txt
git clone https://github.com/user7230724/test
cd test
node 1.js
node 2.js
```

### Operating system

Windows 10

### Scope

Stream

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
```
const { spawn } = require('child_process');

// Replace 'your-command' and ['arg1', 'arg2'] with the actual command and its arguments
const command = 'your-command';
const args = ['arg1', 'arg2'];

const childProcess = spawn(command, args);

const combineUnicodeStreams = (stream) => {
  const chunks = [];
  
  stream.on('data', (data) => {
    chunks.push(data);
  });
  
  stream.on('end', () => {
    const combinedData = Buffer.concat(chunks);
    process.stdout.write(combinedData);
  });
};

combineUnicodeStreams(childProcess.stdout);
combineUnicodeStreams(childProcess.stderr);

childProcess.on('error', (error) => {
  console.error(`Error executing the command: ${error.message}`);
});

childProcess.on('exit', (code, signal) => {
  console.log(`Child process exited with code ${code} and signal ${signal}`);
});

```

Can you check the above code and see if it works in your scenario.

**Comment by user7230724** [comment]
@preveen-stack No, it does not work. It prints `xy∃∃` (both in LTS v18.18.0 and latest v20.7.0). Have you tested the code using the provided executable? If not, please test it next time before posting.

**Comment by user7230724** [comment]
The issue should remain open until the answer is found.

**Comment by RedYetiDev** [comment]
> @preveen-stack No, it does not work. It prints `xy∃∃` (both in LTS v18.18.0 and latest v20.7.0). Have you tested the code using the provided executable? If not, please test it next time before posting.

Providing support for a custom executable isn't preferable for security reasons and ease of access reasons. Can you reproduce this using the standard Node.js installation?

**Comment by RedYetiDev** [comment]
I looked over the question again, and it seems you are asking for someone to complete a task for you or your team. These kind of asks usually find better answers over at StackOverflow, so I suggest you post your issue their instead.

Thank you!
