### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [nodejs/help#4061]
### Details

I want to split a string into two strings that are in an array but it gives me this error:
```console
TypeError: Cannot read properties of undefined (reading '0')
```

### Node.js version

v18.12.1

### Example code

```js
app.post('/', async (req, res) => {
  try {
    const prompt = req.body.prompt;

    const data = prompt.split(",", 2) ?? "Something went Wrong, Please try again"

    console.log(data)

    const response = await openai.createImage({
      prompt: data[0],
      n: 1,
      size: "1024x1024",
    });

    const response2 = await openai.createImage({
      prompt: data[1],
      n: 1,
      size: "1024x1024",
    });

    res.status(200).send({
      image: response.data.data[0].url,
      text: response2.data.choices[0].text
    });

  } catch (error) {
    console.error(error)
    res.status(500).send(error || 'Something went wrong');
  }
})
```

### Operating system

Windows 10

### Scope

ERROR

### Module and version

Not applicable.

**Comment by VoltrexKeyva** [comment]
The error isn't coming from splitting the string, you're accessing non-existent properties from the OpenAI library's `createImage()` function in the following lines of your code:

```js
    res.status(200).send({
      image: response.data.data[0].url,
      text: response2.data.choices[0].text
    });
```

The `<Response>.data` object only includes these properties: https://github.com/openai/openai-node/blob/master/api.ts#L1426-L1439

**Comment by Programming-School-Pro-Coding** [comment]
> The error isn't coming from splitting the string, you're accessing non-existent properties from the OpenAI library's `createImage()` function in the following lines of your code:
> 
> ```js
>     res.status(200).send({
>       image: response.data.data[0].url,
>       text: response2.data.choices[0].text
>     });
> ```
> 
> The `<Response>.data` object only includes these properties: https://github.com/openai/openai-node/blob/master/api.ts#L1426-L1439

Ok, What can i do ?

Can i remove `data[0]` or what ?

**Comment by VoltrexKeyva** [comment]
> Ok, What can i do ?
>
> Can i remove `data[0]` or what ?

Yes, for the URL: `response.data.url`, I'm not sure what the second property you're accessing is but there's a property called `b64_json`, it might be what you need.

**Comment by Programming-School-Pro-Coding** [comment]
> > Ok, What can i do ?
> > Can i remove `data[0]` or what ?
> 
> Yes, for the URL: `response.data.url`, I'm not sure what the second property you're accessing is but there's a property called `b64_json`, it might be what you need.

Ok, Thank you I will Try putting `response.data.url` and tell you

**Comment by Programming-School-Pro-Coding** [comment]
Solved
