### ISSUE TITLE
receive 'spawn EPERM' error when call child_process.execFile

### ISSUE THREAD

**Issue by wubeans** [nodejs/help#4062]
### Details

Hi, I'd like to ask:
there is already error handling like child_process.on('error',()) and child_process.stderr.on('data',()), but we still find this error was throw to console(didn't be catched), it's the whole codes
[the code img](https://user-images.githubusercontent.com/37647271/208329743-6df74021-b28e-4a8c-9e3b-f538a2081974.png)
Please take a look, thanks!

### Node.js version

16.17.0

### Example code

We can see the source code on line 184 at file index.js on wmic project https://github.com/tomas/wmic/blob/master/index.js, wmic version is 1.1.1.

### Operating system

Windows 10.0.18363

### Scope

runtime

### Module and version

child_process

**Comment by preveen-stack** [comment]
cc @nodejs/child_process PTAL
