### ISSUE TITLE
npm on Android

### ISSUE THREAD

**Issue by alikanarya** [nodejs/help#4063]
Hi, I am giving a try to develop a react app on my Android device.
I installed nodejs in termux. But when I try "npm start" I am getting

ENOSPC: System limit for number of file watchers reached, error.

I reached such a command to fixed it:

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

but it doesnt work on my Android device (mine is not rooted btw)

I also noticed another option in " https://webpack.js.org/configuration/watch/#watchoptionsignored "
but I dont know if it works or how to use it.
Do you have a suggestion to overcome this problem?
Thanks

**Comment by preveen-stack** [comment]
cc @nodejs/platform-arm PTAL
