### ISSUE TITLE
How to use Nodejs in html   How to use ducument.write in Nodejs to display information on a web page

### ISSUE THREAD

**Issue by cleversheep2011** [nodejs/help#4066]
My English is not good This article is from machine translation Forgive me if it is not accurate

How to use Nodejs in html
How to use `ducument.write` in Nodejs to display information on a web page

```html
<!DOCTYPE html>
<html>
    <head>
    	<title>sheep</title>
    </head>
    <body>
        <script>
           	const fs = require('fs');
		let data = fs.readFileSync('file.txt');
		ducument.write(data);
        </script>
    </body>
</html>
```

The script in this code does not work

**Comment by benjamingr** [comment]
Hey, Node.js is a server side technology and does not run code in browsers (client side). Consider a free course like freecodecamp to clarify this.

**Comment by cleversheep2011** [comment]
> Hey, Node.js is a server side technology and does not run code in browsers (client side). Consider a free course like freecodecamp to clarify this.

thanks

**Comment by cleversheep2011** [comment]
thank you for your help=>
________________________________
发件人: Benjamin Gruenbaum ***@***.***>
发送时间: 2023年1月6日 19:11
收件人: nodejs/help ***@***.***>
抄送: cleversheep2011 ***@***.***>; Author ***@***.***>
主题: Re: [nodejs/help] How to use Nodejs in html How to use ducument.write in Nodejs to display information on a web page (Issue #4066)


Hey, Node.js is a server side technology and does not run code in browsers (client side). Consider a free course like freecodecamp to clarify this.
