### ISSUE TITLE
Expect server.listen() to throw on ipv6Only

### ISSUE THREAD

**Issue by droid192** [nodejs/help#4067]
### Details

Host can be used to bind to local IPv4 or IPv6; 
```js
var server = http.createServer(app);
server.listen({ host: "localhost", port: 3001, ipv6Only: false });
```
With localhost the user did not specify any preference (up to the OS);  Vanilla Debian uses `::1`
When using `server.listen({ host: "127.0.0.1", port: 3001, ipv6Only: false });` it binds to ipv4; 

But setting `ipv6Only=true` will keep binding to IPv4, also the user clearly stated IPv6 only.  It should not give preference to host, but throw on incompatible config.
[Doc](https://nodejs.org/api/net.html#net_server_listen_options_callback)

### Node.js version

Welcome to Node.js v19.1.0.

### Operating system

debian11

### Scope

doc, api

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
from the doc
```
ipv6Only [<boolean>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type) For TCP servers, setting ipv6Only to true will disable dual-stack support, i.e., binding to host :: won't make 0.0.0.0 be bound. Default: false.
```
