### ISSUE TITLE
simple req.abort() does not ends the process immediately

### ISSUE THREAD

**Issue by vvo** [nodejs/help#407]
When using [request.abort()](https://nodejs.org/api/http.html#http_request_abort) I would expect the process to qui immediately if the only handler active was the current request.

But it take some good time before the process exits, how can I handle this? Is this behavior something we need to fix?

I was not able to easily understand what's going wrong here, I tried many "active handles" modules to see what's keeping the process up, it seems to be the fact that its still waiting for some data from the response while I asked to abort.

example.js
```js
var http = require('http');

// algolia.biz is a no-response DNS, a blackhole for integration testing
var req = http.get('http://www.algolia.biz', function(err, res) {
  console.log(err);
});

req.once('error', function(err) {
  console.log('Planned error', err);
});

setTimeout(function() {
  req.abort();
}, 2000);
```

```sh
> node -v
v7.2.1
> time node example.js
Planned error { Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12) code: 'ECONNRESET' }
node examples/node.js  0.07s user 0.00s system 0% cpu 52.805 total
```

BTW: Any good "Why does node.js does not exists?" modules to recommend? I saw "active-handles" and "wtf-node...".

Thanks.

**Comment by lordKnighton** [comment]
I apologize we didn't get to this in a timely manner, if you still need help reopen issue
