### ISSUE TITLE
Node 18.X is not able to connect to mongodb with localhost

### ISSUE THREAD

**Issue by KunalBurangi** [nodejs/help#4071]
### Version

18.12.1

### Platform

Windows

### What steps will reproduce the bug?

1. Update to Nodejs 18.x
2. connect to local mongoDb 
{
  name: "mongodb",
  connector: "mongodb",
  url: "",
  host: "localhost",
  port: 27017,
  user: "",
  password: "",
  database: "testdb",
};

### How often does it reproduce? Is there a required condition?

Every TIme

### What is the expected behavior?

MongoDb should connect.

### What do you see instead?

It gives the error Connection timed out.

### Additional information

MongoDb gets connect if we use 127.0.0.1 as host but not localhost as Host....

**Comment by KunalBurangi** [comment]
Node behavior has changed since node 17 
https://github.com/nodejs/node/issues/40537
https://github.com/nodejs/node/pull/39987

**Comment by treysis** [comment]
Start MongoDB with `--ipv6` option so it can listen on IPv6 address as well.
