### ISSUE TITLE
my hardhat project

### ISSUE THREAD

**Issue by obilovincent1234** [nodejs/help#4076]
I am trying to create my hardhat project but  my node.js version 19 said that it is not supported by hardhat and it may work incorrectly or not work at all

**Comment by obilovincent1234** [comment]
I had download a version 18.13.0 node and it tells me same thing

**Comment by RedYetiDev** [comment]
Hi! It looks like some crucial information is missing from your issue report. Could you please provide details such as your operating system, Node.js version, and any relevant dependencies? This will help us diagnose and resolve the issue more effectively. Thank you!
