### ISSUE TITLE
Hardhat 

### ISSUE THREAD

**Issue by obilovincent1234** [nodejs/help#4077]
### Details

Am trying to create my hardhat project and it said that the version is not supported and it will not work incorrect or it will not at all 

### Node.js version

19.0.0

### Example code

npx hardhat compile 

### Operating system

Window 10 64bite

### Scope

Other 

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
can you provide log of the messages you are seeing @obilovincent1234
