### ISSUE TITLE
Nodejs stuck on older version

### ISSUE THREAD

**Issue by Pyrole-2002** [nodejs/help#4079]
### Details

```
node -v
v14.15.4
```
```
n ls
node/18.13.0
```
Installed nodejs version 19.3.0-1 from pamac

OS: Manjaro

Need help in changing nodejs version to 18.13.0 which is installed but not getting used.

This causes problem in using npm as it demands a newer node version

### Node.js version

14.15.4

### Operating system

Manjaro

### Scope

installation

### Module and version

Not applicable.

**Comment by VoltrexKeyva** [comment]
Your current Node.js installations are conflicting with each other as they're installed from different sources on different locations. To resolve this, you should uninstall the older version using whatever package manager or tool you used to install it in the first place, once you've done that you can just run `n` (without any arguments) and it'll list all the Node.js binaries you've installed using `n`, so you can choose the one you want to use.

Additionally there's also [nvm](https://nvm.sh/) if `n` doesn't work properly for you.
