### ISSUE TITLE
DNS server list isn't updated in a running process on Windows

### ISSUE THREAD

**Issue by MichalBures** [nodejs/help#408]
In Windows the DNS server list obtained by `dns.getServers()` seems to be cached upon script start, therefore any change in the system DNS isn't reflected in the running script.

Consider this simple script:
```js
var dns = require('dns')

function getDns() {
	console.log(dns.getServers())
}

setInterval(getDns, 2000)
```

When you run this and then change the system DNS servers you'd expect it will at some point start showing the new servers, but that doesn't happen. It's not an issue that the `dns` package can't handle DNS change, because when you run another instance of this script after you've changed the servers it will show the updated list. And you'll get into a silly situation where the same code will be showing two different results.

The only thing I found that gets around this issue is to spawn another node process and get the server list from there.

I've tested this on Windows 10 with Node 7.2.0 and Electron 1.4.x and Windows 8.1 with node 7.2.1 and Node 6.2.0 and it's the same everywhere.

I've tried searching for this issue but I haven't found any mention of it anywhere. From a cursory look into the Node source code I didn't see any caching relevant to dns servers there. Is this an expected behavior? If so is there any way to refresh the server list?

**Comment by bnoordhuis** [comment]
Node.js uses the system DNS resolver for some things and the c-ares library for others. 

`dns.lookup()` uses the system resolver.  It should see DNS changes as soon as the system propagates them.  This is also the default lookup method in the net, tls, http and https modules.

`dns.resolve()` and friends wrap c-ares.  c-ares reads the list of DNS servers at start-up.  I think it's possible to refresh it by reinitializing or ares_dup'ing the control channel but that is not currently implemented.

**Comment by MichalBures** [comment]
Thanks for the info!

I need the actual DNS servers, so `dns.lookup()` doesn't help.

The function in `cares_wrap.cc` responsible is [`GetServers`](https://github.com/nodejs/node/blob/e432c2bfaab27c1917426257aa56269fe74bc893/src/cares_wrap.cc#L1199), specifically:

```c++
 int r = ares_get_servers(env->cares_channel(), &servers);
```
It sadly won't work if I simply `ares_dup()` it, since the servers get also transferred.

```c++
ares_channel ch;
ares_dup(&ch, env->cares_channel());
  
int r = ares_get_servers(ch, &servers);
```

From what I tested so far reinitializing the channel fixes it.

```c++
int r;
struct ares_options options;
memset(&options, 0, sizeof(options));
options.flags = ARES_FLAG_NOCHECKRESP;
options.sock_state_cb = ares_sockstate_cb;
options.sock_state_cb_data = env;

/* We do the call to ares_init_option for caller. */
r = ares_init_options(env->cares_channel_ptr(),
	&options,
	ARES_OPT_FLAGS | ARES_OPT_SOCK_STATE_CB);
if (r != ARES_SUCCESS) {
	ares_library_cleanup();
	return env->ThrowError(ToErrorCodeString(r));
}

r = ares_get_servers(env->cares_channel(), &servers);
```
Although it fixes it it's doing an unnecessary work by initializing the whole channel while only the DNS servers need to be refreshed.

[`init_by_resolv_conf`](https://github.com/nodejs/node/blob/b79e83e7f6458fe5bb180731a2fdb9341a22514e/deps/cares/src/ares_init.c#L1100) is responsible for reading the DNS servers in ares

Ideal solution would be to either to introduce new function something along the way of `ares_refresh_servers` that would reinitialize the DNS servers via `init_by_resolv_conf`.

Or update the [`ares_get_servers`](https://github.com/nodejs/node/blob/b79e83e7f6458fe5bb180731a2fdb9341a22514e/deps/cares/src/ares_options.c#L31) so that it would optionally or always the servers update via `init_by_resolv_conf`.

Both these options mean editing the ares dep, but it's a better solution then wastefully reinitializing the whole channel. So I'm guessing I should move this to `c-ares` repo.

**Comment by MichalBures** [comment]
Okay, you can see the proposed changes to ares [in my fork](https://github.com/MichalBures/c-ares/tree/refresh_dns_servers).

It simply introduces `int ares_refresh_servers(ares_channel channel)` function that will reload the DNS servers. I'll make the actual pull request tomorrow.

**Comment by camhart** [comment]
Was it decided not to fix this?  Because it's still behaves the way @MichalBures originally reported.  getServers() always returns the same servers as upon initialization and never updates/refreshes when the underlying system servers change.
