### ISSUE TITLE
Server.close not closing after given time

### ISSUE THREAD

**Issue by brijeshhroy** [nodejs/help#4080]
### Details

Below is a simple code which I wrote :-

```js
var http = require('http');
var server = http.createServer(function (req,res) {
  res.end("Hello World") 
})

server.listen(5000);



setTimeout(() => {server.close() } ,4000);   // put anytime duration here 
```

The behaviour which I expected was that server should stay on for 4 seconds and then closes. But rather what is happening is that server stays on indefinitely and we can do anything, however when we leave server idle for 4 seconds, after that if we reload or do anything  then the timer of 5 seconds starts and after that server closes.
Means from 0 to n seconds I kept on working, then left idle for 4 seconds, on 24th second I reloaded again and then on 29th second the server is closing.

Why is it happening like that.  Basically settimeout will move to call queue after 5 seconds and then it should be moved to call stack by event loop and close  the server as soon as it goes idle.We can put anytime duration in timeout we have to wait leave server idle for that duration for the settimeout to begin and after that 5 seconds it take to close it.
Why is it behaving so ?

I expected that the server shall close after 4 seconds but it is not happening so.

### Node.js version

v18.12.1

### Example code

Already provided in the details.

### Operating system

Windows 10

### Scope

I am tring it in VS code.

### Module and version

Module is "http"

**Comment by gireeshpunathil** [comment]
if I remember correctly, this is because the socket does not finalize immediately after close, instead it goes into a FIN_WAIT status from which it can be resurrected. the API does not destroy the socket while at this stage.

To confirm, can you test with two browsers (or clients) like this?
 - use the first client to access the server beyond 4 seconds, and keep it alive for say 5 or 10 seconds.
 - use the second client to access the server after say 4 seconds (after the timeout has hit)

and see if the second client is able to connect. I expect it to fail.

**Comment by brijeshhroy** [comment]
Thanks a lot for replying. In the second browser it indeed failed , but however in the first browser I am able to load once after it has benn left idle for the timeout duration and then it closes, why is it so ,any idea ?

**Comment by gireeshpunathil** [comment]
> but however in the first browser I am able to load once after it has benn left idle for the timeout duration and then it closes, why is it so ,any idea ?

this is expected, as the open socket is not immediately closed and can be resurrected within the timeout period. Whereas for other clients, a new socket needs to be opened, which will not be honoured as the server is already closed.

Hope this helps.

**Comment by preveen-stack** [comment]
@brijeshhroy did the above answer clarified your query? If so can you close the issue
