### ISSUE TITLE
req.headers becoming undefined

### ISSUE THREAD

**Issue by rehan78600** [nodejs/help#4081]
### Details

headers is becoming undefined after using spraed operator.

### Node.js version

v18.12.1

### Example code

For example->
req= {...req, id: 'abc'};
console.log(req.headers);
Expected result- it should print the headers value.
Actual result-> It is printing undefined

### Operating system

windows

### Scope

runtime

### Module and version

Not applicable.

**Comment by GabenGar** [comment]
Does the original `req` object have the headers?

**Comment by preveen-stack** [comment]
can you provide a test script for reproducing the issue @rehan78600
