### ISSUE TITLE
path: null in debug output for http.request even when explicitly specified in options.

### ISSUE THREAD

**Issue by Maverick099** [nodejs/help#4082]
### Details

Was getting 401 error for a http get request with `http` module from nodeJS.

To Debug this set `NODE_DEBUG=http,https` (context: because I was able to to a get call for the same in Postman wanted to know why 401 for same credentials). 

While going through the debug output found out that the path in the options is `null`.

can anyone let me know is this normal to see `null` in debug output.

Because if in actual the `path` was sent out as null I should have received a `404:NOT_FOUND` error from server and not `401:Unauthorized` error right!?

### Node.js version

v18.13.0

### Example code

debug output:

```
HTTP 22812: call onSocket 0 0
HTTP 22812: createConnection some.thing.com:8000: [Object: null prototype] {
  method: 'GET',
  host: 'some.thing.com',
  port: 8000,
  path: null,
  headers: {
    'Content-type': 'application/json',
    Authorization: 'Basic encoded_key:secret_;)_'
  },
  timeout: 60000,
  noDelay: true,
  servername: 'some.thing.com',
  _agentKey: 'some.thing.com:8000:'
}
```

passed options is as follows:

```
_config = {
           method: 'GET',
           host: "some.thing.com",
           port: 8000,
           path: `/I/do/have/a/path`,
           headers: _headers,
           timeout: timeOut
         };
```

### Operating system

Windows

### Scope

module

### Module and version

http

**Comment by Maverick099** [comment]
can anyone take a look into this!!!
thankyou.

**Comment by preveen-stack** [comment]
can you share example code for reproduction @Maverick099

**Comment by Maverick099** [comment]
@preveen-stack It's a simple HTTPCONFIG with prams defined as mentioned in above.

**Comment by jakec-github** [comment]
I've also seen this from the https module using `NODE_DEBUG=http`. Node version `v18.15.0`

**Comment by CakeShopIT** [comment]
same issue - tested on node 20 and 22
`function getFromURL(options, postData=null) {
    return new Promise((resolve)=>{
        if (postData) {
            if (!options.headers) {
                options.headers={}
            }
            options.headers['Content-Length']=Buffer.byteLength(postData, 'utf8')
        }
        console.log(JSON.stringify(options, null, 2))

        const req=https.request(options, (response)=>{
            let ret=""
            
            response.on('data', (chunk)=>{
                ret+=chunk
            })

            response.on('end', ()=>{
                resolve(ret)
            })

            response.on('error', (e)=>{
                resolve({'error': e, 'source': 'script - inside'})
            })
        })
        req.on('error', (e)=>{
            resolve({'error': e, 'source': 'script - outside'})
        })
        req.write(postData)
        req.end()
    })
}`

and calling it:
`    let ret=await getFromURL({
        hostname: 'something.com',
        path: '/testpath',
        method: 'POST'
    })
`

console output:
`NODE_DEBUG=https node test.js
{
  "hostname": "something.com",
  "path": "/testpath",
  "method": "POST"
}
HTTPS 1394986: createConnection [Object: null prototype] {
  hostname: 'something.com',
  path: null,
  method: 'POST',.....`

so the `options` showing correctly, but the `https.request` debug showing `path: null`

**Comment by Gared** [comment]
I can confirm this bug. This is still an issue in version 20.17.0
