### ISSUE TITLE
Current node.js does not work properly with IntelliJ CE on Windows

### ISSUE THREAD

**Issue by AndrewLazarus** [nodejs/help#4084]
A Java program running in the IntelliJ IDE trying to open a Connection to a node.js server on `http[s]://localhost:3000` gives Connection Refused. Connections are OK with Postman and any browser. Tested on multiple Windows installations. Windows Defender was off.

**Downgrading** to node.js 15.2 works fine.

There does not appear to be any problem running on Ubuntu or MacOS.

**Comment by preveen-stack** [comment]
@nodejs/platform-windows PTAL
