### ISSUE TITLE
Want to read YAML file from github location using nodejs

### ISSUE THREAD

**Issue by Debashriti** [nodejs/help#4087]
### Details

Want to read YAML file from GitHub location using Node.js. Used the following code
```js
const yaml = require('yaml');

const fs = require('fs')


 const file = fs.readFileSync('https://github.ibm.com/debashriti-bose/YAML_Locations/Test.yml', 'utf8')
let doc = yaml.parse(file)
console.log("YAML:::" ,doc);
```

But getting the following error
`no such file or directory`

Please help

### Node.js version

16

### Example code

```js
const fs = require('fs')


 const file = fs.readFileSync('https://github.ibm.com/debashriti-bose/YAML_Locations/Test.yml', 'utf8')
let doc = yaml.parse(file)
console.log("YAML:::" ,doc);
```

### Operating system

Windows

### Scope

Code

### Module and version

Not applicable.

**Comment by VoltrexKeyva** [comment]
The [`fs.readFileSync()`](https://nodejs.org/docs/latest-v18.x/api/fs.html#fsreadfilesyncpath-options) method you're using only reads files from your local storage, not remote ones.

To achieve what you want, you can make a `GET` request to that URL to fetch it and read it's contents, in Node.js v18 or higher you can use the [`fetch()`](https://nodejs.org/docs/latest-v18.x/api/globals.html#fetch) API that's globally available like so:

```js
const yaml = await fetch(/* Your URL goes here */)
  .then((response) => response.text());
```

Or with Node.js versions below 18 (such as v16, v14, etc etc), you can use third-party libraries like [Undici](https://undici.nodejs.org/) or [Node-Fetch](https://www.npmjs.com/package/node-fetch) to do that like so:

In CommonJS:

```js
// For Undici:
const { fetch } = require('undici');
// For Node-Fetch:
const fetch = require('node-fetch');

const yaml = await fetch(/* Your URL goes here */)
  .then((response) => response.text());
```

In ESM (ES Modules):

```js
// For Undici:
import { fetch } from 'undici';
// For Node-Fetch:
import fetch from 'node-fetch';

const yaml = await fetch(/* Your URL goes here */)
  .then((response) => response.text());
```

---

Of course, you can also use the built-in [`node:http`](https://nodejs.org/docs/latest-v18.x/api/http.html)/[`node:https`](https://nodejs.org/docs/latest-v18.x/api/https.html) modules, but I would recommend using the APIs I mentioned above, as working with the built-in `node:http`/`node:https` module can be tedious for this purpose.

**Comment by Debashriti** [comment]
Hi, when I tried to access the github locations using the node application, it is navigating to  authentication page of github url. How can I access the exact github location

**Comment by AugustinMauroy** [comment]
Have you try to use [raw content of GitHub](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file).

so here an example of what you can do
```js
const yaml = await fetch('https://raw.githubusercontent.com/nodejs/node/main/.yamllint.yaml')
  .then((response) => response.text());
  ```

**Comment by preveen-stack** [comment]
@Debashriti were any of the suggestions provided helped you
