### ISSUE TITLE
Looking for NodeJS Experts to help Audit Code/Performance of webpack core code

### ISSUE THREAD

**Issue by TheLarkInn** [nodejs/help#409]
Hi super awesome incredible NodeJS Folks!!!! We (the webpack organization), are interested in having someone look into identifying perf bottlenecks or audit our [core webpack code](http://github.com/webpack/webpack). Is there a group or team, (or single person) who specializes in this kind of process?

The code is pretty hefty so there could be lot's of opportunities. 

Additionally in 

github.com/webpack/webpack-sources
github.com/webpack/enhanced-resolve
github.com/webpack/loader-runner
github.com/webpack/watchpack
github.com/webpack/tapable
github.com/webpack/webpack

Feel free and reach out to me on twitter (@thelarkinn) or on here, we would love to have the help of experts who is willing to help contribute to our open source efforts or even general guidance.

**Comment by lordKnighton** [comment]
Hey @TheLarkInn Closing for now: My apologies no one responded to this post. If your still looking for help around the WEBPACK repo, I will volunteer some free time there(Specifically) handing user issues & DOCS. Not looking to contribute code at least for the moment. But if you already have enough help there, that's fine too.

**Comment by TheLarkInn** [comment]
Thank yo so much for following up. I know stuff is crazy over there in your neck of the woods but will probably re address this pretty soon.
