### ISSUE TITLE
AsyncLocalStorage loses store after await

### ISSUE THREAD

**Issue by dbryan0516** [nodejs/help#4090]
### Details

I'm having issues trying to work with async_hooks. I want to create a global request context so that I do not have to pass around the req/res objects from express through the entire app. I came across AsyncLocalStorage and have tried it out as an example but run into issues where it loses the store after 'await'. From what I can tell via the docs, this code should work as I'm running `next()` within the `run()` function but it does not. Can I get some help creating a store that will allow my app to access a global request context?

### Node.js version

18.7.0

### Example code

```node
const express = require('express');
const { AsyncLocalStorage } = require('async_hooks');
const Context = new AsyncLocalStorage();

const requestIdMiddleware = (req, res, next) => {
  Context.run(new Map(), () => {
    Context
      .getStore()
      .set('host', req.headers['host']);
    Context
      .getStore()
      .set('user-agent', req.headers['user-agent']);
    next();
  });
};

function getAsyncID() {
  return Context.getStore().get('host');
}

function getAsyncgent() {
  return Context.getStore().get('user-agent');
}

const app = express();

app.use(requestIdMiddleware);

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

app.get('/', async (req, res) => {

  console.log(getAsyncID()); // this works

  await sleep(1000);

  console.log(getAsyncID()); // store is undefined here

  res.json({
    host: getAsyncID(),
    agent: getAsyncgent(),
  });
});

app.listen(3000, () => {
  console.log(`Running on http://localhost:3000/`);
});
```

### Operating system

MacOS 10.15.7

### Scope

Runtime

### Module and version

async_hooks

**Comment by prettydiff** [comment]
The documentation for AsyncLocalStorage is at https://nodejs.org/api/async_context.html#class-asynclocalstorage

The code example provided in the documentation shows use of a callback.  Have you tried using a callback function instead?  Also you are using getters/setters, which are both slow and difficult to test.  I suspect if you attempt an alternative to the getters/setters this problem will go away.

**Comment by dbryan0516** [comment]
Changing the getters/setters calls to be inline instead has no effect.

And using a callback where? I have a callback in the `.run()` call
