### ISSUE TITLE
What should I do to get the process status by pid?

### ISSUE THREAD

**Issue by KID-joker** [nodejs/help#4091]
### Details

I created two separate processes, one of which exits depends on the state of the other, and it knows the pid of the other. What should I do?

### Node.js version

Not applicable.

### Operating system

all

### Scope

code

### Module and version

Not applicable.

**Comment by KID-joker** [comment]
I tried `process.kill(pid, 0)` to get the status, but got
```cmd
node:internal/process/per_thread:221
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at process.kill (node:internal/process/per_thread:221:13)
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\demo\web.js:7:43)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  errno: -4040,
  code: 'ESRCH',
  syscall: 'kill'
}
```

**Comment by prettydiff** [comment]
That will differ by OS.  My suggestion is to write a shell script for your particular OS that can check that status and that you can call as a child process in your Node application.

**Comment by KID-joker** [comment]
> This method will throw an error if the target pid does not exist. As a special case, a signal of 0 can be used to test for the existence of a process. Windows platforms will throw an error if the pid is used to kill a process group.

From the above, if the process does not exist, `process.kill(pid, 0)` should return false instead of an error. Or that `0` is not only a check, but also kill?
