### ISSUE TITLE
ENOTFOUND cannot connect to registry on npx create react app

### ISSUE THREAD

**Issue by deepbodo** [nodejs/help#4093]
### Version

19.6.0

### What steps will reproduce the bug?

Actually i uninstalled and reinstalled node again but now when i run npm install or npx create react app it gives enotfound error stating im connected to proxy or vpn but i don't have proxy or vpn connected. 

### How often does it reproduce? Is there a required condition?

I can't even create a project

### What do you see instead?

Npm/yarn whatever i use it gives enotfound error.i tried every available solutions but it says my network issues but on the same network in a different system everything is fine. 

### Additional information

npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to http://registry.npmjs.org/create-react-app failed, reason: getaddrinfo ENOTFOUND proxy.example.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Deepjyoti Bodo\AppData\Local\npm-cache\_logs\2023-02-10T04_12_18_901Z-debug-0.log

**Comment by Arif7067** [comment]
Same issue

**Comment by Arif7067** [comment]
type   npm config edit
Search for  https-proxy. If it is set to null then ok and also check for its duplicate if there is then delete than duplicate or else set https-proxy = null. It work for me.

**Comment by Stiagomon** [comment]
> type npm config edit Search for https-proxy. If it is set to null then ok and also check for its duplicate if there is then delete than duplicate or else set https-proxy = null. It work for me.

Thank you so much, Its working now! 
![image](https://github.com/nodejs/help/assets/131112405/abeebc94-9251-48da-a07d-6fb2e4d34a76)
![image](https://github.com/nodejs/help/assets/131112405/21e21d8d-197d-4827-b49a-049cd71e4a3c)

**Comment by HuzaifaChaudary** [comment]
@Arif7067 How dare you solved my problem? Thanks allooooot

**Comment by Sintay27** [comment]
I can't solve 
is there anyone who can help me?

**Comment by radhe098** [comment]
not worked, any other solution

**Comment by DorianBajorek** [comment]
Same in my case. I tried that in three different computer in different network and same reason
