### ISSUE TITLE
Windows 11 ENOENT -4058

### ISSUE THREAD

**Issue by jcs090218** [nodejs/help#4095]
### Version

16.x and 18.x

### Platform

Windows 11

### What steps will reproduce the bug?

```bash
# clone the project
$ git clone https://github.com/emacs-eask/cli

# navigate to project root
$ cd cli

# install all modules
$ npm install

# start program `eask.bat` and execute the command
$ cli/bin/eask.bat info
```

### How often does it reproduce? Is there a required condition?

consistent.

### What is the expected behavior?

Run without the error, -4058.

### What do you see instead?

```
Running Eask in the development environment
Press Ctrl+C to cancel.

Executing script inside Emacs...
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn emacs ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn emacs',
  path: 'emacs',
  spawnargs: [
    '-Q',
    '--script',
    'D:\\_workspace\\_eask\\cli\\lisp\\core\\info.el'
  ]
}
```

### Additional information

Related SO: https://stackoverflow.com/questions/73041590/windows-11-npm-err-errno-4058-code-enoent-bash

**Comment by prettydiff** [comment]
A translation of the error message means that you are attempting to run Emacs in a spawned child process but Emacs is not there.  I don't think this is a Node issue at all.  Emacs is not on Windows unless you put it on windows or execute an environment on Windows containing Emacs.  For example, the SO link you provided indicated the problem went away when that person executed their script in git-bash.  git-bash likely does provide Emacs even when running on Windows.

The solution then is to either provide Emacs as a dependency of your project that your project installs on Windows or tell your users to manually install it themselves.
