### ISSUE TITLE
Custom REPL, How to break out of infinite loop?

### ISSUE THREAD

**Issue by MoserMichael** [nodejs/help#4098]
### Details

I am using `node:repl` to create a custom REPL. Now the example accepts a single command `loop` that enters an infinite loop. There is no way to break out of the loop with Ctrl+C or by any other method. The process is stuck.

- `node:repl` has a option `breakEvalOnSigint` - but this is not available for a custom REPL. Setting this option gives the error `Cannot specify both "breakEvalOnSigint" and "eval" for REPL`
- `repl.Server.addListener('SIGINT'` - is being ignored while the REPL is stuck, so is `process.on()` - however the signals are processed when the REPL is not in an infinite loop.
- the Node.js code calls   `process.binding('util').startSigintWatchdog();` upon `breakEvalOnSigint` option, but I can't do that from Node.js v19.6.0 

What should I do?

I am making an educational programming language based on `node:repl` (here it is https://github.com/MoserMichael/jscriptparse ) and it's very awkward, that the kids can't stop a runaway script. I would be very thankful for your help.

### Node.js version

v19.6.0 

### Example code

```js
const repl=require("node:repl");

function runEvalLoop() {

        let doWrite = function(arg) { return arg };

        let evalIn = function(data, context, filename, callback) {

            console.log( "data: " + data.constructor.name);

            if (data.trim() == "loop") {

                console.log("entering infinite loop...");
                while(true) {
                }
            }             
            callback(null,"command ignored");
        }

        nodejsRepl = repl.start({
            prompt: "> ",
            eval: evalIn,
            writer: doWrite,
            //breakEvalOnSigint: true,
        });

        nodejsRepl.addListener('SIGINT', function() {
            console.log("on SIGINT");
            process.exit(1);
        });
        nodejsRepl.addListener('SIGTERM', function() {
            console.log("on SIGTERM");
            process.exit(1);
        });
}

runEvalLoop();
```

### Operating system

OSX - 21.6.0 Darwin Kernel Version 21.6.0: arm64
Also happens on Windows 11 and Linux (fedora)

### Scope

node:repl 

### Module and version

node --version
v19.6.0

**Comment by preveen-stack** [comment]
cc @nodejs/repl Can you advise
