### ISSUE TITLE
New auth string in npm v9/node.js v18 - Backwards compatible ?

### ISSUE THREAD

**Issue by melroyvandenberg** [nodejs/help#4099]
### Details

As stated here the `_auth` config in npmrc file is changed: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#auth

Now we need to include the full artifactory URL / scoped URL as part of the `auth` string. like so: `//registery.address/api/npm/npmjs/:_auth=...`

**Question:** If I fix this issue, will it still work on older NPM versions (below npm v9)?  
**So is this a backwards compatible change?**

I ask this for a production environment setup. Thanks!

### Node.js version

v18 (LTS)

### Example code

```npmrc
always-auth=true

registry=https://registery.address/api/npm/npmjs/

//registery.address/api/npm/npmjs/:_auth=<base_64_user:password>
```

### Operating system

Linux

### Scope

runtime

### Module and version

Not applicable.

**Comment by melroyvandenberg** [comment]
Anybody?

**Comment by richardlau** [comment]
cc @nodejs/npm

**Comment by lukekarrys** [comment]
Yes, this change is backwards compatible. I don't have specifics of how far back but it should be at least in all supported versions of npm (`>=6`).

**Comment by melroyvandenberg** [comment]
> Yes, this change is backwards compatible. I don't have specifics of how far back but it should be at least in all supported versions of npm (`>=6`).

Thank you so much for your reply!
