### ISSUE TITLE
How to install /node-v5.1.0-linux-x64$ 

### ISSUE THREAD

**Issue by dozeen** [nodejs/help#41]

**Comment by bnoordhuis** [comment]
Can you provide more details?  What did you download where and where are you trying to install it to?  If you ran into problems, please post what you've tried so far and the error messages you got.

**Comment by neophoenix123** [comment]
I am trying to install node for 64bit ubuntu OS. Simply put, I am not very good with file/archive management, understanding directory download/install behaviors and I just cannot seem to progress smoothly in navigating the terminal to launch programs or execute files. Every time I try, I keep getting errors and I am just burned out trying.  From what it looks like, node-v5.1.0-linux-x64 is right here in my /Home/Downloads directory. However, nothing seems to be executable within the contents of the folder in the given archive for me to actually get the program to either launch or be recognized. 

Also, I am sooooo desperate to get my first ember application started, but I get errors in the terminal such as "no such file" when clearly I am looking right at it. Also I get "WARN" errors stating I need the latest version of the program which I do. I also have downloaded Ember cli along with its respective supporting packages and I just cannot get things to update or download correctly (despite following instructions verbatim). Any assistance greatly appreciated!

**Comment by rvagg** [comment]
@neophoenix123 here's a one-liner that may be helpful for getting it installed: `curl https://nodejs.org/download/release/v5.1.0/node-v5.1.0-linux-x64.tar.xz | tar Jxv --strip=1 -C /usr/local/`

The important bits of this are the use of `J` for `tar` to understand `xz` compression, the `--strip=1` which will get rid of the `/node-v5.1.0-linux-x64` at the start of all of the paths and `-C /usr/local` to unpack it all under `/usr/local/` including the executable at `/usr/local/bin/node` and npm resources in `/usr/local/lib/node_modules/` and a link to the executable at `/usr/local/bin/npm`. It's also likely that you'll need `root` permissions to unpack in `/usr/local` so you can just change `| tar ...` to `| sudo tar ...`.

Alternatively, a much easier approach is to use the NodeSource Linux distributions at https://deb.nodesource.com/ to get v5.x and it'll be all be properly installed via the usual `apt` mechanisms, including updates as they come out.

**Comment by neophoenix123** [comment]
Wow I will be giving this a try right now and I will keep you informed. Thank you for this help I am crossing fingers as we speak!

**Comment by neophoenix123** [comment]
Wow nothing..this is the latest:

tar: Child died with signal 13
tar: Error is not recoverable: exiting now
curl: (23) Failed writing body (450 != 4096)

**Comment by rvagg** [comment]
@neophoenix123 did you try with `sudo tar` instead?

**Comment by Valentin-Seehausen** [comment]
Thanks @rvagg for https://deb.nodesource.com/

    # Using Ubuntu
    curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
    sudo apt-get install -y nodejs

**Comment by Valentin-Seehausen** [comment]
Oh, then I run into trouble because I had an old version of node installed. This helped me, but updated the existing installation to 5.0.0 (without LTS, but ok, lets go):

    sudo npm cache clean -f
    sudo npm install -g n
    sudo n stable

**Comment by supermonteiro** [comment]
thank you @rvagg

**Comment by neophoenix123** [comment]
If you are using it for Ember, I have a step by I can give you in order to
ensure node and other dependencies are installed using NVM. Its the best
method when using Ember!




On Wed, Feb 3, 2016 at 6:46 AM, Thiago Monteiro Barbosa <
notifications@github.com> wrote:

> thank you @rvagg <https://github.com/rvagg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/41#issuecomment-179242010>.
>



-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by neophoenix123** [comment]
Sudo install anything are just not good friends with ember as permissions
are temporary using sudo to install nodejs. You will probably run into
issues accessing files later so I would suggest

-curl -o-
https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
   (this will download node version manager)
-nvm install stable    (this will install the latest version of nodejs and
npm respectively)


On Wed, Feb 3, 2016 at 10:13 AM, George Awad <gawad@eptent.com> wrote:

> If you are using it for Ember, I have a step by I can give you in order to
> ensure node and other dependencies are installed using NVM. Its the best
> method when using Ember!
>
>
>
>
> On Wed, Feb 3, 2016 at 6:46 AM, Thiago Monteiro Barbosa <
> notifications@github.com> wrote:
>
>> thank you @rvagg <https://github.com/rvagg>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nodejs/help/issues/41#issuecomment-179242010>.
>>
>
>
>
> --
> *George Awad, BS.BA <http://BS.BA>*
> *Epic Proportions Software inc.*
> *gawad@eptent.com <gawad@eptent.com>*
> *http://epicproportionstour.com <http://epicproportionstour.com>*
>
>
>


-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by wellington1993** [comment]
Thanks @Valentin-Seehausen
