### ISSUE TITLE
WASI initialization in child thread

### ISSUE THREAD

**Issue by toyobayashi** [nodejs/help#4102]
### Details

`wasi` requires calling `initialize()` or `start()` after instantiating wasm and requires that memory is exported from wasm, but this doesn't work in multithreaded scenario (`wasm32-wasi-threads` target).

With wasi threads, we need to provide wasm memory created in JavaScript (`new WebAssembly.Memory({ shared: true })`) in main thread, and [send the memory to child thread to instantiate wasm again in child thread](https://github.com/WebAssembly/wasi-threads/blob/f203624c15fedbcc8b4f7f0589f867f0a63a92e3/README.md?plain=1#L141-L142), and it is unnecessary (and [will cause error](https://github.com/WebAssembly/wasi-libc/blob/8daaba387ce70a6088afe3916e9e16ed1c2bc630/libc-bottom-half/crt/crt1-reactor.c#L13)) to call `initialize()` or `start()` in child thread. So normal usage of `WASI` doesn't work in child thread. But we still need an "initialized" `WASI` instance in child thread.

Currently I'm using [cloned instance object and Proxy](https://github.com/toyobayashi/emnapi/blob/9bc69c52bc8d582c92acc754ea6a0050572d871b/packages/core/src/load.js#L84-L142)  to workaround this problem. Is there any possibility to handle this in future Node.js API change?

### Node.js version

18.14.0

### Example code

https://github.com/toyobayashi/emnapi/blob/9bc69c52bc8d582c92acc754ea6a0050572d871b/packages/core/src/load.js

`loadNapiModuleImpl`

### Operating system

macOS 13.2

### Scope

code? or runtime?

### Module and version

`require('node:wasi').WASI`

**Comment by preveen-stack** [comment]
cc @nodejs/wasi
