### ISSUE TITLE
Node.js not detected in the folder but i have already downloaded it in that folder[Windows10]

### ISSUE THREAD

**Issue by HaoHao-code** [nodejs/help#4105]
### Details

When I try to set node.js path in DevEco Studio, it always turns out Node.js not detected, Select another directory or download Node.js. However, I've already downloaded Node.js in that folder and add it into System Path. I cannot find the same question in Google. I am so confused.
![image](https://user-images.githubusercontent.com/76158231/220035034-c8b3dd1f-049a-4d09-b5ee-2a9316d200e7.png)

### Node.js version

Node.js v14.19.1

### Operating system

Windows 10

### Scope

Installation

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
can you give the listing of the directory C:\Users\85908\nodejsss

**Comment by HaoHao-code** [comment]
On that time, the environment path of my computer was too weird, and it was solved after I reset the operating system. Thanks for your reply.
