### ISSUE TITLE
Why does Node.js slow down during simple iterations?

### ISSUE THREAD

**Issue by jjuszkiewicz** [nodejs/help#4106]
### Details

I made simple program (code below) it make two loop. First loop makes 5,900,000,000 iterations without any complicated calculation. The second loop counts the time of this first. After 3 to 5 iteration outside loop, the time inner loop take much much larger than earlier (result also below). I tested it on two environment my local laptop MacBook Pro, and AWS EC2.

Do you have idea why it work that way, and what causing slow down?

```js
const calculate = () => {
  let a = 0;
  for (let i = 0; i < 5900000000; ++i) {
    a++
  }
};

for (let i = 0; i < 10; ++i) {
  console.time();
  calculate();
  console.timeEnd();
}
```

Result:

```console
default: 4.875s
default: 5.566s
default: 29.625s
default: 29.805s
default: 29.698s
default: 29.595s
default: 29.733s
default: 29.611s
default: 29.597s
default: 29.476s
```

### Node.js version

v18.13.0

### Operating system

macOS 13.1
AWS EC2

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
> default: 9.400s
default: 9.528s
default: 30.005s
default: 30.013s
default: 30.038s
default: 29.974s
default: 29.995s
default: 30.011s

wondering why!
