### ISSUE TITLE
Node v15.14.0 release SHASUMS256.txt file is empty

### ISSUE THREAD

**Issue by ttgrules** [nodejs/help#4108]
### Details

It looks like the contents of https://nodejs.org/download/release/v15.14.0/SHASUMS256.txt have disappeared since yesterday. This is breaking package installation.

### Node.js version

15.14.0

### Operating system

Multiple

### Scope

Installation

### Module and version

Not applicable.

**Comment by richardlau** [comment]
Looks like @rvagg took care of this in https://github.com/nodejs/nodejs.org/issues/5065#issuecomment-1441102067.
