### ISSUE TITLE
node -c

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#411]
For awhile I assumed  that

```console
node -c file1.js file2.js file3.js
```

would "compile"/check all the files passed as arguments, but I am starting to doubt that for several reasons. 

I just verified that this is not the case, and that's kind of dissapointing.

Should I make this a feature request? Or is it not worth it?

**Comment by gibfahn** [comment]
From `node --help`:

```
  -c, --check           syntax check script without executing
```

As javascript is an interpreted language, why/how would you compile `.js` files?

**Comment by targos** [comment]
> FWIW, I'm pretty sure node -c file1.js file2.js file3.js does check all three files.

It only checks the first file

**Comment by ORESoftware** [comment]
@gibfahn no, it doesn't, just try this `node -c real-file.js fake-file.js`, where fake-file.js is not an actual path, the command won't fail, hence node -c only reads the first argument, which is lame IMO

node -c apparently stands for compile, as in vm.runInThisContext

https://nodejs.org/api/vm.html

 because it "compiles" the file, in this case that seems to mean just check for syntax errors. Kind of a misnomer, double IMO

**Comment by gibfahn** [comment]
If you'd like to raise a PR, the idea sounds good to me.

Looking at https://developers.google.com/v8/, it does say
>V8 compiles and executes JavaScript source code

Which seems a bit odd as a description. `node -c` as `check` (which is what `node --help` says) seems like a better description of what actually happens.

**Comment by addaleax** [comment]
> If you'd like to raise a PR, the idea sounds good to me.

Yeah, this should be okay to do and I don’t see anything speaking against it. Let us know if you are interested and feel free to ask if there’s anything we can help you with! :)

**Comment by ORESoftware** [comment]
@gibfahn agreed, node -c, should stand for node --check, not node --compile

V8 does compile JS, just on the fly :)
