### ISSUE TITLE
Serverless compatitble version with node 18

### ISSUE THREAD

**Issue by Monisha94** [nodejs/help#4116]
### Details

I am trying to update my node version to 18. But i was getting an error for serverless. - 
    Error: Unknown object type "asyncfunction" 

So i upgraded my serverless to latest version, getting the below error now 
An error occurred: TransformerDashexportDashcsvLambdaFunction - Resource handler returned message: "Uploaded file must be a non-empty zip

Can someone help on this?

### Node.js version

18.14.1

### Operating system

Mac

### Scope

./node_modules/.bin/serverless deploy

### Module and version

serverless - Not working with any version

**Comment by preveen-stack** [comment]
please share relevant code
