### ISSUE TITLE
Sending a ZIP file as API call payload

### ISSUE THREAD

**Issue by yorickcleerbout** [nodejs/help#4118]
### Details

Hi guys, i was wondering if anyone could help me out. I'm currently working om some sort of tool that is using API calls, and i need to send a ZIP file as form params to the server. In curl it is using the tags ```-F "file=@filename.zip"``` but i was wondering how i can do this with nodejs. I currently have the following code but it gives me a 400 bad request: 

```js
let form = new FormData();
        form.append('file', fs.readFileSync(`./apigee/proxies/${file}`));

        let response = await fetch(`${to}/v1/organizations/${torg}/apis?action=import&name=${file.slice(0,-4)}`, {
            method: 'post',
            body: form,
            headers: {'Authorization': `Bearer ${ta}`, 'Content-Type': 'multipart/form-data'}
        });
```

### Node.js version

Not applicable.

### Operating system

Windows

### Scope

code

### Module and version

Not applicable.

**Comment by KevinSoulat** [comment]
Hi Yorick,

I had a similar issue and found this turnaround:

```js
// helpers
const createBlobFromFile = async path => new Blob([ await fs.promises.readFile(path) ]);

const body = new FormData();
//body.append('upload', fs.createReadStream(filePath)); // doesn't work
body.append('upload', await createBlobFromFile(filePath), 'myFile.wav' );

const response = await fetch(url, { method: 'POST', body })
const result = await response.json();
console.log( response.status, result )
```

Note this method is not optimal for large files, as they are fully loaded in memory.
For this case, modules like axios or node-fetch seem more efficient.
