### ISSUE TITLE
How to capture terminal output using exec nodejs

### ISSUE THREAD

**Issue by moezbenrebah** [nodejs/help#4119]
### Details

I'm trying to capture from the terminal `jest unittests` output using the `exec` method, in some cases it works, but in other cases it does not, I even try to log the stderr, and stdout when I have issues but didn't figure out how to do that properly:

### Node.js version

16

### Example code

my code:
```js
const subProcess = require('child_process');
const process = require('process')

subProcess.exec('jest your_filename_path', (err, stdout, stderr) =>  {
  if (err) {
    console.error(err);
    process.exit(1);
  } else {
    console.log(stderr.split('\n'))
    console.log(stdout.split('\n'))
    return stdout.split('\n').every(line => {
      if(!line.includes('FAIL')) process.stdout.write('OK');
      else process.stdout.write('NOK');
    });
  }
});
```

And I had this error message:
```console
Error: Command failed: jest src/actions/uiActionCreators.test.js
FAIL src/actions/uiActionCreators.test.js
  Test uiActionCreators.js
    ✓ test for LOGIN (1 ms)
    ✕ test for LOGOUT (1 ms)
    ✓ test for DISPLAY_NOTIFICATION_DRAWER
    ✓ test for HIDE_NOTIFICATION_DRAWER (1 ms)

  ● Test uiActionCreators.js › test for LOGOUT

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      true
    Received:
    ....
```

### Operating system

ubuntu 22.04

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
cc @nodejs/testing PTAL

**Comment by ljharb** [comment]
This has nothing to do with `node:test`.

**Comment by gireeshpunathil** [comment]
Your code logic is fine, just that you have test failure: `✕ test for LOGOUT (1 ms)` and that is why you don't get other log messages. Fix that and run, and you should start finding the console output.

If there are too much output you are expecting, consider increasing the console buffer using `maxBuffer` option for the exec call.

**Comment by moezbenrebah** [comment]
Hello everyone,
Below is a solution (I said a solution so without any improvement or looking for an external packages, just nodejs) that I developed, and glad to share here:
```js
const subProcess = require('child_process');
const process = require('process')

const cmd = `jest your_filename_path`;

subProcess.exec(cmd, (err, stdout, stderr) => {
  if (err) {
    // Handle any other error that might happen during running tests
    if (err.code === 1) {
      process.stdout.write('NOK')
    } else {
      // Access the stderr output, and analyze it line by line
      return stderr.split('\n').every(line => {
        if(!line.includes('FAIL')) process.stdout.write('OK');
        else process.stdout.write('NOK');
      });
    }
  } else {
    // Acess the stdout output, and analyze it line by line
    return stdout.split('\n').every(line => {
      if(!line.includes('FAIL')) process.stdout.write('OK');
      else process.stdout.write('NOK');
    });
  }
})
```

Finally, the above solution worked in my case, and I hope that will help anyone who comes across this post, or inspire him/her to implement an adequate solution.
