### ISSUE TITLE
Setting a request timeout for a specific endpoint

### ISSUE THREAD

**Issue by mateimarica** [nodejs/help#4120]
### Details

I have an `/upload` endpoint where I want the client to be able to continue sending data for hours, in a single request.

[`server.requestTimeout`](https://nodejs.org/api/http.html#serverrequesttimeout) defaults to 5 minutes and this will time out any request running longer than that. This is not good enough for uploading large files. I don't want to increase the `requestTimeout` for the whole server.

Setting the timeout on the `req` object is not what I'm looking for:
- `req.setTimeout(ms)` is an alias for `req.socket.setTimeout(ms)`
- `req.socket.setTimeout(ms)` sets the SOCKET timeout
   > A socket timeout is the timeout when waiting for individual packets. It's a common misconception that a socket timeout is the timeout to receive the full response.
- `req.connection.setTimeout(ms)` sets the max time for a connection to be SET UP
    > A connection timeout is the maximum amount of time that the program is willing to wait to setup a connection to another process. You aren't getting or posting any application data at this point, just establishing the connection, itself.

<br>

### What I tried

I tried setting the timeouts directly on the `req` object (and `res`, for some reason I saw this suggested)

Here's an example middleware function:
```js
const reqTimeoutSetter = (req, res, next) => {
	req.setTimeout(3600000); // one hour
	req.socket.setTimeout(3600000);
	req.connection.setTimeout(3600000);

	res.setTimeout(3600000);
	res.socket.setTimeout(3600000);
	res.connection.setTimeout(3600000);

	next();
};
```

and my endpoint:
```js
const app = express();

app.post('/upload', [reqTimeoutSetter, /* multer middleware */], (req, res) => {
	// ...
});

const server = http.createServer({
	requestTimeout: 10000 // 10 seconds
}, app);

server.listen(5000);
```
and the request still times out based on `server.requestTimeout`.

<br>

Is it possible to set a request timeout (like `server.requestTimeout`) but for a specific endpoint?

### Node.js version

v18.14.2

### Operating system

Windows 10, Ubuntu 20.04.3 LTS

### Scope

N/A

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
did you try adjusting keepalivetimeout ?

> > server
Server {
  maxHeaderSize: undefined,
  insecureHTTPParser: undefined,
  requestTimeout: 300000,
  headersTimeout: 60000,
  keepAliveTimeout: 5000,
  connectionsCheckingInterval: 30000,

**Comment by SystemParadox** [comment]
I don't think any of those timeouts are relevant, including `keepAliveTimeout` - they're all for timing out due to inactivity. As the OP described, what we want is a per-request version of `server.requestTimeout`, to allow file uploads to continue for a long time, but there does not appear to be any option for this.

**Comment by mateimarica** [comment]
@SystemParadox 

Correct, those properties are not relevant. Those are server-wide propreties. I'm looking for way to set the request timeout for an individual endpoint.

So far, I'm unable to find a good solution. I ended up increasing the `server.requestTimeout` to accommodate long-running uploads. I wouldn't recommend this though, it won't scale well and will increase server load.

**Comment by mateimarica** [comment]
@SystemParadox 

Correct, those properties are not relevant. Those are server-wide properties. I'm looking for way to set the request timeout for an individual endpoint.

So far, I'm unable to find a good solution. I ended up increasing the `server.requestTimeout` to accommodate long-running uploads. I wouldn't recommend this though, it won't scale well and will increase server load.

**Comment by marijazupunski** [comment]
Hi, I have the same issue. I need timeout to be increased only for few endpoints (to be seat to 24h) and I want to avoid increasing for all requests. Is there any solution for it? Thanks!

**Comment by mateimarica** [comment]
@marijazupunski Unfortunatly none that I have found.

**Comment by mateimarica** [comment]
@marijazupunski Unfortunately not that I have found.

**Comment by SystemParadox** [comment]
This is still relevant and should not have been closed.

**Comment by avivkeller** [comment]
This issue closed due to inactivity. If you should feel that this is still relevant, please open a new issue with relevant details and information.

**Do not** copy/paste the current issue, instead, create a new issue indicating all the required information.

Because this is a feature request, I suggest opening the issue in nodejs/node.
