### ISSUE TITLE
Getting: SentHandleNotReceivedWarning: Handle did not reach the receiving process correctly

### ISSUE THREAD

**Issue by leobgm** [nodejs/help#4121]
### Details

I'm getting this error while sending a net.socket object to a forked process:

(node:2101768) SentHandleNotReceivedWarning: Handle did not reach the receiving process correctly
    at ChildProcess.<anonymous> (node:internal/child_process:651:19)
    at ChildProcess.emit (node:events:532:35)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

Socket is created like this `const socket = new net.Socket({ fd, allowHalfOpen: true });`

And sending it to forked process: `worker.send(data, socket);`

### Node.js version

16.14.0

### Operating system

Ubuntu 20.04

### Scope

runtime

### Module and version

child_process

**Comment by preveen-stack** [comment]
https://github.com/nodejs/node/blob/36e4e3d86b31de7f38125aacad810e40295fd2ae/lib/internal/child_process.js#L651
```
      if (target._pendingMessage) {
        if (message.cmd === 'NODE_HANDLE_ACK') {
          closePendingHandle(target);
        } else if (target._pendingMessage.retransmissions++ ===
                   MAX_HANDLE_RETRANSMISSIONS) {
          closePendingHandle(target);
          process.emitWarning('Handle did not reach the receiving process ' +
                              'correctly', 'SentHandleNotReceivedWarning');
        }
      }
```
From the code it looks like it has exhausted retransmission attempts
