### ISSUE TITLE
Any Bug-Prevention Mechanism to better handle not existed NAPI

### ISSUE THREAD

**Issue by clipsheep6** [nodejs/help#4123]
### Details

I add some new NAPI for IOT devices that js app could access hardware,  since the API grows and the IOT devices various , some small devicess do not impl all the NAPI(only impl the API they use),  which means the Js app may call a NAPI,  that do not have a NAPI impl ( not even have a stub impl), which may need a Bug-Prevention Mechanism to avoid App error.

Any exist solution for this situation that may make a default "not impl error" for all those not impl NAPI call in run time ?

### Node.js version

Not applicable.

### Operating system

Linux

### Scope

Runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
guess we can use a try catch for this. 
```
cat test.js 
try {
	prints("hello")
} catch (error) {
	console.log(error)
}
console.log("continuing after calling unimplemented function");
```
```
$ node test.js
ReferenceError: prints is not defined
    at Object.<anonymous> (/Users/preveen/prevlabs/nodejs/nji-4123/test.js:2:2)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
continuing after calling unimplemented function 
```

**Comment by clipsheep6** [comment]
@preveen-stack  the question is that for IOT devices that may have different hardware e.g. sensor .  older device may do not have some sensor that they do not impl the NAPI, but share a  same js SDK for small apps to use . try catch is a way for apps to override ,but not sure all apps may do the protect , so I want to see if some way to add protect in the runtime that if a NAPI is not impl, that do not make the crash and just  return method not supported.

I found that opengl in android seem have same situation , vendors do not impl all the opengl api , and the system in runtime helps returns API not supported message. but I do not figure out where it add the same protect in Node

**Comment by preveen-stack** [comment]
cc @nodejs/node-api

**Comment by legendecas** [comment]
By default, Node.js loads the add-on with dlopen flag `RTLD_LAZY`. You can change this behavior by overriding the `require.extensions['.node']` to use the flag `RTLD_NOW` with `process.dlopen()` instead, for example:

```js
const { RTLD_NOW } = require('constants');
require.extensions['.node'] = function (module, filename) {
  return process.dlopen(module, filename, RTLD_NOW);
}
```

This would report an error when `require()` loads an add-on with missing symbols.

**Comment by preveen-stack** [comment]
@clipsheep6 does the above suggestion is useful for your scenario. let us know
