### ISSUE TITLE
Fetch - POST - use stream as body?

### ISSUE THREAD

**Issue by KevinSoulat** [nodejs/help#4126]
### Details

Hi guys,

Related to this post https://github.com/nodejs/help/issues/4118, is there a way to use a readable stream as body of POST (or PUT) request, to avoid memory issues with large files?

```js
// helpers
const createBlobFromFile = async path => new Blob([ await fs.promises.readFile(path) ]); // suboptimal

const body = new FormData();
//body.append('upload', fs.createReadStream(filePath)); // doesn't work
body.append('upload', await createBlobFromFile(filePath), 'myFile.wav' );

const response = await fetch(url, { method: 'POST', body })
const result = await response.json();
console.log( response.status, result )
```

Thanks

### Node.js version

v18

### Operating system

windows/mac

### Scope

code

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
please check https://nodejs.org/api/fs.html#filehandlecreatereadstreamoptions

**Comment by KevinSoulat** [comment]
@preveen-stack, not sure what you meant exactly. 
I tried different encoding, but it didn't work.

It's possible to use stream with http module as explained here: https://stackoverflow.com/a/64002066, but I wonder if it's possible with fetch().

**Comment by preveen-stack** [comment]
> const fs = require('fs');
const fetch = require('node-fetch');

const fileStream = fs.createReadStream('/path/to/large/file.wav);

fetch('https://example.com/api', {
  method: 'POST',
  body: fileStream
}).then(response => {
  // handle response
});


Can you check this code?

**Comment by KevinSoulat** [comment]
Hi @preveen-stack, this code doesn't work (for instance require('node-fetch') can't work since it's a pure ESM module), and my point is to use the native "fetch" module and not the tier-party module "node-fetch" to do that.

**Comment by preveen-stack** [comment]
Got it. Take a look at below code 

```
const https = require('https');
const fs = require('fs');

const fileStream = fs.createReadStream('path/to/file.wav');

const options = {
  method: 'POST',
  headers: {
    'Content-Type': 'application/octet-stream' // set the content type to octet-stream
  }
};

const req = https.request('https://example.com/upload', options, (res) => {
  console.log('Response:', res.statusCode);
});

fileStream.pipe(req);

req.on('error', (error) => {
  console.error('Error:', error);
});

req.end();

```

**Comment by mleister97** [comment]
Any updates on this one?

**Comment by purplesyringa** [comment]
I'm also interested in this feature. [Chromium supports something similar](https://developer.chrome.com/docs/capabilities/web-apis/fetch-streaming-requests), so this is not without a precedent.
