### ISSUE TITLE
Playstation 4

### ISSUE THREAD

**Issue by bernardo7007** [nodejs/help#4127]
### Description of the problem

Your environment has been set up for using Node.js 19.8.1 (x64) and npm.

C:\Users\cabbj>npm i ps4-waker -g
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

changed 10 packages in 22s

2 packages are looking for funding
  run `npm fund` for details

C:\Users\cabbj>

Please can someone help me with this problem?
I'm wanting to connect alexa on ps4 but this error always appears.
Thanks to anyone who can help.

**Comment by VoltrexKeyva** [comment]
That's not an error, those are simply deprecation warnings telling you that the package you're installing (`ps4-waker` in this case) uses deprecated packages or package versions.

That package you're installing hasn't been updated in [3 years](https://github.com/dhleong/ps4-waker/releases/tag/1.10.1), but you can still use it to see if it works, if it doesn't then try finding something else that works or try to fork it's [repository](https://github.com/dhleong/ps4-waker) and update it if you know how to do so.
