### ISSUE TITLE
How to convert a buffer to a readable file in NodeJS

### ISSUE THREAD

**Issue by vinaysruban** [nodejs/help#4128]
### Details

I receive a buffer through an input:
```js
const fileData = Buffer.concat(chunks);
```
I then send this input into OpenAI's Whisper which excepts a file
```js
const resp = await openai.createTranscription( //@ts-ignore
   fileData,
   "whisper-1",
);
```
This doesn't work so first I save the file to the disk
```js
fs.writeFileSync("input.wav", fileData);
```
Then I read it again in the response function
```js
const resp = await openai.createTranscription( //@ts-ignore
   createReadStream("input.wav"),
   "whisper-1",
);
```

This works but I don't want to save the file the disk every time I run the function.
Is there a way to convert a buffer into the same NodeJS stream or achieve something with the same final output without saving it to the disk?

### Node.js version

Not applicable.

### Operating system

Windows 10

### Scope

My problem is with the code itself, not the outcome.

### Module and version

Not applicable.

**Comment by rodgetech** [comment]
Did you find a way to do this?

**Comment by vinaysruban** [comment]
No, not yet

**Comment by preveen-stack** [comment]
Did you try 
`const fileDataStream = Readable.from(fileData);`

**Comment by EJKT** [comment]
Does someone know the solution to this post I made in the OpenAI forum: [https://community.openai.com/t/creating-readstream-from-audio-buffer-for-whisper-api/534380](url)

**Comment by patrr2** [comment]
You can convert Buffer to FileLike by calling 
`
import { toFile } from 'openai/uploads';

const file = await toFile(buffer)
`
