### ISSUE TITLE
Error: Failed at core-js, instructed to contact author

### ISSUE THREAD

**Issue by jasperdrinnon** [nodejs/help#4129]
![node-screenshot-windows-4](https://user-images.githubusercontent.com/109889213/227070964-f233daa7-1c7e-43e9-8261-686f56a15250.png)
![node-screenshot-windows-0](https://user-images.githubusercontent.com/109889213/227070966-fb4fbfac-8a46-4be8-a53e-3c57fecd9634.png)
![node-screenshot-windows-1](https://user-images.githubusercontent.com/109889213/227070969-4d941689-ee03-47f0-8fd3-a46814996864.png)
[npm-debug.log](https://github.com/nodejs/node/files/11045860/npm-debug.log)

![node-screenshot-windows-2](https://user-images.githubusercontent.com/109889213/227070970-4896bcfa-6539-4fa3-b8d1-5752cea5e48e.png)
![node-screenshot-windows-3](https://user-images.githubusercontent.com/109889213/227070971-20316fd9-e66f-47cd-aafe-915a1bdf8365.png)

**Comment by bmuenzenmeyer** [comment]
I wonder if this has to do with the npm@2.15.12 version - which is VERY old. 

As an aside, the core-js author is not here - that would be https://github.com/zloirock/core-js

**Comment by RedYetiDev** [comment]
Hi! This repo is for issues with Node.js itself. We are unable to provide support for third-party packages. Please get in touch with the maintainers of the specific package for assistance with your issue. Thank you for understanding!
