### ISSUE TITLE
SQlite Encryption Extension library

### ISSUE THREAD

**Issue by emilthomas1** [nodejs/help#413]
Do you know how to use SQlite Encryption Extension library with node js

**Comment by lordKnighton** [comment]
Here's one link of many - 

[link 🔗 ](http://jayralencar.com.br/create-database-sqlite-encrypted-with-node-js/)

Then go here, if that one doesn't do it for you. - 

[link 🔗 ](https://www.google.com/search?q=SQlite+Encryption&oq=SQlite+Encryption&aqs=chrome..69i57j0l5.317j0j7&sourceid=chrome&ie=UTF-8#q=SQlite+Encryption+node.js)

**Comment by emilthomas1** [comment]
Hi, The above link uses sql-cipher while I have to use the sqlite-see https://www.sqlite.org/see/doc/trunk/www/readme.wiki.

Is sqlite-see compatible with https://www.npmjs.com/package/sqlite3 ?

**Comment by lordKnighton** [comment]
NO i have zero experience with sqlite-see,  Your best bet is to go through the docs, & google 
But other than that, you can wait for one of the other team members to help you out, but there isn't alot
of post about node.js & sqlite-see so there is no telling when someone can help you with experience in the matter.
