### ISSUE TITLE
The package "@esbuild/darwin-arm64" could not be found, and is needed by esbuild.

### ISSUE THREAD

**Issue by usman1947** [nodejs/help#4130]
### Version

v18.15.0

### Platform

22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64

### What steps will reproduce the bug?

1. create a vite app with react verion  "react": "^18.2.0",
2. npm i and npm start
3. get the error
![Screenshot 2023-03-23 at 11 56 56 AM](https://user-images.githubusercontent.com/110887337/227099085-ee000abd-19f1-4e79-8231-8c38da7119fa.jpg)

### What do you see instead?

app running normally

### Additional information

i downgraded node version to v16.19.1 and it works fine on that

**Comment by curran** [comment]
This should probably be filed as an issue for Vite, not Node.

**Comment by michaelklopf** [comment]
In case you came here and use Docker in any way, you probably installed in your OS and try to build with your Docker container. Or in case you use Laravel Sail, you installed directly on the folder instead of in sail.
