### ISSUE TITLE
Understanding microtask queue execution

### ISSUE THREAD

**Issue by tayweekiam** [nodejs/help#4136]
### Details

Hi! I am new to the nodejs code base and want to understand more about how microtasks are executed.

From the source code, I understand that the tick queue and microtask queue will be cleared when:
- When at least one timer list is processed (code can be found [here](https://github.com/nodejs/node/blob/67200dca0fd22da14ba6e48a404ae2241d6cef81/lib/internal/timers.js#L519)).
- When at least one timer is processed. (code can be found [here](https://github.com/nodejs/node/blob/67200dca0fd22da14ba6e48a404ae2241d6cef81/lib/internal/timers.js#L499))
- When at least one immediate is processed. (code can be found [here](https://github.com/nodejs/node/blob/67200dca0fd22da14ba6e48a404ae2241d6cef81/lib/internal/timers.js#L433))

I also read that the microtask queue clears before the event loop tasks
So I ran the following code:
```js
console.log('1')

new Promise((resolve) => {
	console.log('2')
	resolve()
})

new Promise((resolve) => {
	console.log('3')
	resolve()
})

setTimeout(() => {console.log('4')}, 0)
setTimeout(() => {console.log('5')}, 0)

console.log('6')
```
And got the expected output:
```console
1
6
2
3
4
5
```
However, I can't seem to find the function call that runs the microtask queue before the tasks in the event loop.

So I need some advice on these:
- Where can I find the logic that clears the microtask queue before the event loop?
- For poll phase and close callback phase (e.g. file read), I can't find the function call that is similar to the `runNextTicks` function called in the timers phase and check phase. May I know where can I find it?

Thank you!!

### Node.js version

19.8.1

### Operating system

N/A

### Scope

Code related to the event loop, next tick queue and microtask queue

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
perhaps this article can help you out  https://medium.com/dkatalis/eventloop-in-nodejs-macrotasks-and-microtasks-164417e619b9

**Comment by theanarkh** [comment]
you can see the `env_->tick_callback_function()` in `void InternalCallbackScope::Close()`(src/api/callback.cc).

**Comment by tayweekiam** [comment]
Thank you guys for helping! I will look into it!
