### ISSUE TITLE
Please upgrade the OpenSSL to 3.1.0

### ISSUE THREAD

**Issue by SuperSnowYao** [nodejs/help#4139]
### Details

Please upgrade the OpenSSL to 3.1.0
![image](https://user-images.githubusercontent.com/36811234/229274008-9832b3ea-21e9-45d5-a3e9-771448ddcfed.png)

### Node.js version

19.8.1

### Operating system

windows10

### Scope

none

### Module and version

Not applicable.

**Comment by bmuenzenmeyer** [comment]
citing https://github.com/nodejs/node/issues/47360 - which you opened 3 minutes apart from this one, closing

**Comment by tniessen** [comment]
@SuperSnowYao OpenSSL 3.1.0 contains the same vulnerability. Upgrading would not help with this.
