### ISSUE TITLE
node.js reference error node not defined

### ISSUE THREAD

**Issue by techelpmike** [nodejs/help#414]
I just installed node.js on my Windows 10 computer.  I tried to see the version by typing 'node -v' at the command prompt  I received a Reference error message "Node not defined" with a list of where it is not defined.  Does this mean that I can't use node.js as there is no way to define it?  Or how do I correct this error in order to use node.js?

**Comment by vsemozhetbyt** [comment]
Are you trying to type `node -v` inside Node.js REPL (interactive session)?

You have two way to get Node.js version:
1. Type `node -v` in console outside Node session.
2. Type `process.version` inside Node interactive session (after you type `node` or click on the Node.js icon shortcut).

**Comment by bnoordhuis** [comment]
It sounds like you may have the Microsoft HPC Pack installed, it has a command named `node` too.  Either uninstall it or make sure "our" node comes first on the %PATH%.  I'll close this out.

**Comment by Kuolmarko24** [comment]
Heyy guys when I used app.se("view...","ejs"):
I do also get that error of referenceerror
