### ISSUE TITLE
nodejs and pooling.

### ISSUE THREAD

**Issue by nigelwright7558** [nodejs/help#4140]
### Details

I wrote a nodejs website program using MSSQL over a year ago and it worked great.
Came back to it recently and it now comes up with lots of "connection lost" errors.
After a lot of digging it appears it doesnt like pooling greater than 1.
If I make a loop putting records into a database the first item goes in ok but subsequent items come up with "connection error"

### Node.js version

latest

### Operating system

Windows 11

### Scope

Using pool > 1 causes the error

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
Please share relevant lines of code and specify the nodjs version number
