### ISSUE TITLE
How to investigate RSS memory leak?

### ISSUE THREAD

**Issue by mwilniewiec** [nodejs/help#4141]
### Details

I have a problem with one of my microservices that its RSS memory is rising and I don't know what should be a proper way of finding the real problem.
I already analyzed heapdumps and nothing can be found as I can see that heap is pretty stable.

`process.memoryUsage()` is currently showing:
```
external: 40866815,   (38.97 MB)
heapTotal: 135319552, (129.05 MB)
heapUsed: 114264216,  (108.97 MB)
rss: 1641189376,      (1565.16 MB)
```

It's a docker running inside of a k8s pod doing quite a lot of things. 
- it's a client of RabbitMQ (using `amqplib`) processing lots of messages
- using prostgres with `typeorm`
- using redis
- making GRPC calls to other services
- decompressing data using `zlib.inflateSync`
- lots of other stuff

Heap:
![image](https://user-images.githubusercontent.com/33090843/230053599-3a5cc3fd-cffb-4efa-8535-7ef6d1a9d66b.png)

RSS:
![image](https://user-images.githubusercontent.com/33090843/230053646-81807b56-4478-4a81-9ca7-d9003874fab6.png)

In the charts you can see that there are 2 instances of this microservice and both have exactly the same growth in RSS and exactly the same Heap.

Is there any way that I could analyse the other 1.3 GB of RSS memory which is not in the Heap ?

### Node.js version

12.14.1

### Operating system

Alpine Linux v3.11 (in a Docker)

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
Take a look at v8-profiler, may be it can help

**Comment by preveen-stack** [comment]
Also, pls check response to https://github.com/nodejs/help/issues/4148

**Comment by mhdawson** [comment]
This may also be helpfull - https://github.com/nodejs/node/blob/main/doc/contributing/investigating-native-memory-leaks.md

**Comment by gireeshpunathil** [comment]
it is worthwhile to see what is the system characteristics. summary of https://github.com/nodejs/node/issues/31641 in this context is: 

**rss stays high for ever, if there is no demand for memory in the system**

it is a known issue, and the current workaround is to ignore the observation, the growth will subside when there is a demand.

or in other words - the system will adapt to the need, don't measure too much! :)
