### ISSUE TITLE
fs module of node 

### ISSUE THREAD

**Issue by Aashish-Kaushik** [nodejs/help#4142]
### Details

```console
node:internal/validators:118
      throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
      TypeError [ERR_INVALID_ARG_TYPE]: The "fd" argument must be of type number. Received type string ('./content/text1')
←[90m    at Object.readSync (node:fs:707:8)←[39m
    at Object.<anonymous> ←[90m(D:\Code\Code\leraning_node\←[39mapp.js:5:18←[90m)←[39m
```

### Node.js version

18

### Example code

```js
const fs = require('fs');



const first = fs.readSync('./content/text1', 'utf8');
const second = fs.readSync('./content/text2', 'utf8');

console.log(first, second);

fs.writeSync('./content/result.txt', `test in this file from: ${first}, ${second}`);
```

### Operating system

windows

### Scope

when I try to read the file its shows this and I give a right file  path 

### Module and version

file system module

**Comment by preveen-stack** [comment]
> fs.writeSync('./content/result.txt', `test in this file from: ${first}, ${second}`);

Not sure if this file naming format valid on windows.

**Comment by KermanX** [comment]
use `readFileSync` instead of `readSync`, and `writeFileSync` instead of `writeSync`.

**Comment by Aashish-Kaushik** [comment]
> use `readFileSync` instead of `readSync`, and `writeFileSync` instead of `writeSync`.

yes I do this and  it works

**Comment by preveen-stack** [comment]
@Aashish-Kaushik If this issue is solved, can you please close the issue. Thanks
