### ISSUE TITLE
Package not installing in local directory 

### ISSUE THREAD

**Issue by Colin-Stark** [nodejs/help#4144]
### Details

I made a folder

I did npm init on it and it produced a package.json file which is fine

Now when I enter "npm install --save-dev hardhat"

It doesn't add a Devdependency called hardhat to my package.json 

And I can see that a node_modules is created in c:/user/user/AppData/roaming/npm

How do I fix this because I'm at the verge of formatting my laptop to cléan any configuration that is causing this 

### Node.js version

Node version 18. 15. 0

### Example code

Npm install --save-dev hardhat

### Operating system

WINDOWS

### Scope

Installation 

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
npm version? Also pls share what npm is showing on the console

refer the correct page for your npm for eg: https://docs.npmjs.com/cli/v8/commands/npm-install 
there is a foreground-scripts option which can give some clues on what is happening

**Comment by preveen-stack** [comment]
please check https://stackoverflow.com/questions/14032160/npm-install-module-in-current-directory

**Comment by preveen-stack** [comment]
I just tried this on my system. was not able to reproduce this 
```
cat package.json 
{
  "name": "local-install",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "hardhat": "^2.16.0"
  }
}
```

also node_modules was correctly created. I am on v18.7.0
