### ISSUE TITLE
Is there any requirement for the system kernel version when running node18?

### ISSUE THREAD

**Issue by laoboxie** [nodejs/help#4147]
### Details

I found that the node18 build has a requirement for the kernel version, but I am not sure if the runtime also has a requirement for the kernel version.
In the [node building doc](https://github.com/nodejs/node/blob/v18.15.0/BUILDING.md#platform-list), it says kernel version should >= 4.18.
But in [AWS Lambda runtimes doc](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), AWS  Lambda runtimes use kernel 4.14.
So what is the minimum version of kernel when running node18?

![image](https://user-images.githubusercontent.com/23701019/232960713-7de0a10a-6ce7-45af-8508-2f0ac7ed8b4f.png)
![image](https://user-images.githubusercontent.com/23701019/232961646-b4aa0683-974e-4e1e-8aca-d87082fe3362.png)

Can someone help answer this question?

### Node.js version

18.15.0

### Operating system

linux

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
Guess building requirements and runtime requirements are different
