### ISSUE TITLE
Should process.emit('SIGINT') from within readline SIGINT listener terminate the process?

### ISSUE THREAD

**Issue by ValYouW** [nodejs/help#415]
Hi,

When using `process.emit('SIGINT')` from within `readline` SIGINT event, the process won't exit.
Tried it both on win10 and Ubuntu 14.04.5 (windows subsystem for linux).

Here is a sample code, thx.

```js
var readline = require('readline');
var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.once('SIGINT', function() {
    console.log('GOT sigint');
    rl.close();
    // Should this terminate the process?
    process.emit('SIGINT');
});

// Just for keeping the process busy
require('http').createServer().listen(3000);
```

**Comment by bnoordhuis** [comment]
> // Should this terminate the process?

No.  You are emitting an event on the process object, not sending a signal.  Try `process.kill(process.pid, 'SIGINT')`.

**Comment by ValYouW** [comment]
Thanks, For some odd reason I thought that process.emit(SIGINT) would simulate Ctrl+C
