### ISSUE TITLE
Nodejs application scalability

### ISSUE THREAD

**Issue by alexmc1510** [nodejs/help#4150]
### Details

Hello, I am a newby in nodejs but really enjoying the way it works. I have developed a first application for converting one TCP protocol to MQTT based in a config file with IP/port for source and destination. I am also using NodeRed for having a GUI but it is not mandatory.

It works perfectly but now I would like to ask about scalability....replication of instances with different configuration files and/or maybe launching instances based on entries or number of configuration files.

I have read about docker, pm2.....would you be so kind as to give me some ideas and I will try to look for info in google and git. Maybe some examples...

Thanks in advance.

### Node.js version

Not applicable.

### Operating system

Windows 10

### Scope

other

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
you may need to consult your cloud provider recommendations for scaling nodejs application on their cloud platform 
eg: https://www.digitalocean.com/community/tutorials/how-to-scale-node-js-applications-with-clustering

**Comment by alexmc1510** [comment]
Hello. It is a local application that will run in a local server so I have the freedom to design the infra as I want.

**Comment by preveen-stack** [comment]
@alexmc1510 let us know if you need any further help on this othewise you can close the issue
