### ISSUE TITLE
How to replace toHaveBeenLastCalledWith with node:test

### ISSUE THREAD

**Issue by childrentime** [nodejs/help#4152]
### Details

in jest,we have
```tsx
 const mock0 = jest.fn();

expect(mock0).toHaveBeenLastCalledWith();
```
I know we have mock in nodejs, but can to check it?
```tsx
 const mock0 = mock.fn();
```

### Node.js version

20

### Operating system

macos

### Scope

test_runner

### Module and version

Not applicable.

**Comment by MoLow** [comment]
you can simply assert the arguments of the last call:
```js
assert.deepStrictEqual(mock.calls[mock.callCount() - 1].arguments, [/* some arguments */]);
```

**Comment by childrentime** [comment]
@MoLow  I am sorry, I use this mock in code before.
```tsx
import { mock } from "node:test";
```
It does not seems to have  `calls` and `callCount` export in nodeV20

**Comment by MoLow** [comment]
I did not refer to the top-level mock, the full example is more like:

```js
import { mock } from "node:test";
import assert from "node:assert";

const mock0 = mock.fn();
assert.deepStrictEqual(mock0.calls[mock0.callCount() - 1].arguments, [/* some arguments */]);
```

**Comment by childrentime** [comment]
![image](https://user-images.githubusercontent.com/58261676/235866276-15ce761e-53aa-4a2a-acdd-b9013882e0b7.png)
Actually, mock0 does not has method of callCount and property of calls either. Are you using a different version of node？ @MoLow

**Comment by MoLow** [comment]
sorry I was missing a `.mock`:

```js
import { mock } from "node:test";
import assert from "node:assert";

const mock0 = mock.fn();
assert.deepStrictEqual(mock0.mock.calls[mock0.mock.callCount() - 1].arguments, [/* some arguments */]);
```

**Comment by childrentime** [comment]
Well, thanks a lot🥰🥰🥰, missed this in nodejs document.
