### ISSUE TITLE
What are the benefits of using nodejs AsyncLocalStorage?

### ISSUE THREAD

**Issue by childrentime** [nodejs/help#4153]
### Details

 I don't understand the purpose of using AsyncLocalStorage。

For example:
```js
const store = { id: 1 };
// Replaces previous store with the given store object
asyncLocalStorage.enterWith(store);
asyncLocalStorage.getStore(); // Returns the store object
someAsyncOperation(() => {
  asyncLocalStorage.getStore(); // Returns the same object
}); 
```

why we just use plain javascript instead of it?
```js
let store;
export const getStore = () => store;

export const setStore = (value) => {
  store = value;
};
```

### Node.js version

Not applicable.

### Operating system

macos

### Scope

AsyncLocalStorage

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
https://medium.com/trabe/asynclocalstorage-for-easy-context-passing-in-node-js-e33c84679516 may be of help
