### ISSUE TITLE
How to get started reading the Nodejs source code 

### ISSUE THREAD

**Issue by NhatNguyen1810** [nodejs/help#4154]
### Details

I am new to nodejs, I am wondering if anyone can help me provide some instructions how to get started reading the source code. For example, when a node program runs, which file will get hit first (main function) ? And which repos are also associated to the most crucial parts of nodejs (event loop, v8 engine integration, thread pools, callback execution)

Any help is greatly appriciated, thanks! 

### Node.js version

Not applicable.

### Operating system

Not applicable 

### Scope

code 

### Module and version

Not applicable.

**Comment by Avinashbawage** [comment]
Here are some steps to help you get started:

Set up your development environment: Make sure you have Node.js and a code editor installed on your machine.

Choose a version: Determine which version of Node.js you want to read the source code for. You can find the source code for each version on the official Node.js GitHub repository (https://github.com/nodejs/node). Clone or download the repository for the specific version you are interested in.

Familiarize yourself with the project structure: Take some time to explore the directory structure of the Node.js repository. Understand the main folders and files, such as src, lib, test, doc, etc. This will give you an overview of where to find different components and modules within the codebase.

Identify a specific area of interest: Node.js is a large project, so it's helpful to narrow down your focus to a specific area or feature that you want to understand better. This could be an internal module, a core API, or a specific functionality.

Start with the entry point: Identify the entry point of the area you're interested in. For example, if you want to understand the HTTP module, look for the corresponding file or module within the codebase.

Read the code incrementally: Start reading the code from the entry point and follow the execution flow. Take your time to understand each function, module, or class as you encounter them. Pay attention to function signatures, comments, and variable names to grasp the purpose and behavior of the code.

Use development tools: Node.js has debugging and profiling tools that can be helpful when reading the source code. You can use the --inspect flag to start Node.js in debug mode and connect it to a debugger like Chrome DevTools. This allows you to step through the code, set breakpoints, and inspect variables during runtime.

Consult documentation and resources: As you read the code, consult the official Node.js documentation (https://nodejs.org/api/) and other relevant resources. The documentation will provide insights into the intended behavior and usage of different modules and APIs.

Engage with the community: Join Node.js discussion forums, mailing lists, or chat platforms to connect with other developers and ask questions. The Node.js community is active and supportive, and you can often find answers and insights from experienced contributors.

Remember that understanding a large codebase like Node.js takes time and persistence. Start small, gradually increase your understanding, and build upon your knowledge as you delve deeper into the source code.

**Comment by NhatNguyen1810** [comment]
Thanks for the answer! Currently I am particularly interested in reading about how nodejs uses v8 and create the Event Loop / Call stack. Do you have any pointers which dir is the best place to get started on those? 

I am still trying to find the main function of node js, I think from there I can trace how modules/functions are called, do you know in which file the main function of Nodejs is located at? Thanks.

**Comment by wide4head** [comment]
Eventloop is managed by libuv http://docs.libuv.org/en/v1.x/

**Comment by wide4head** [comment]
Check dep directory all dependecies including v8 and libuv

**Comment by NhatNguyen1810** [comment]
Thanks!
