### ISSUE TITLE
How eventloop is created 

### ISSUE THREAD

**Issue by NhatNguyen1810** [nodejs/help#4158]
### Details

From the source code of libuv, from this file, it seems like line the code is trying to init the eventloop when the nodejs program starts up. 

https://github.com/nodejs/node/blob/main/deps/uv/src/unix/loop.c#L50

And when I read the definition of uv_loop_s, I dont see any member field as wq, from this file 

https://github.com/nodejs/node/blob/main/deps/uv/include/uv.h#L213

instead, wq is a member field of uv_work, which has uv_loop_s as a member field 

https://github.com/nodejs/node/blob/main/deps/uv/include/uv/threadpool.h#L33

So can anyone help me explain how uv_loop_t from the first link can access wq? Thanks. 

### Node.js version

Not applicable.

### Operating system

N/A

### Scope

code

### Module and version

Not applicable.

**Comment by VoltrexKeyva** [comment]
> And when I read the definition of uv_loop_s, I dont see any member field as wq, from this file

The definition of the `uv_loop_s` struct:

https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L1847-L1862

uses the `UV_LOOP_PRIVATE_FIELDS` macro which expands to:

https://github.com/libuv/libuv/blob/v1.x/include/uv/unix.h#L220-L251

which is where the `wq` field is declared in.

**Comment by NhatNguyen1810** [comment]
This is mind-blowing, do you have any reference to further read about this macro expansion? Thanks. 

Also, since wq is an array of 2 entries? Does it mean there are 2 threads for the event loop or what?

**Comment by preveen-stack** [comment]
take a look at this thread https://stackoverflow.com/questions/61156557/what-does-queue-q0-mean-in-libuv-or-how-does-the-queue-work

**Comment by preveen-stack** [comment]
@NhatNguyen1810 Do you need any further help on this one. If not please close the issue
