### ISSUE TITLE
nodejs18 and openssl 3.0.8

### ISSUE THREAD

**Issue by coltonfreeman26** [nodejs/help#4159]
### Details

We are trying to build [node 18](https://hub.docker.com/layers/library/node/18.16.0-alpine3.17/images/sha256-44aaf1ccc80eaed6572a0f2ef7d6b5a2982d54481e4255480041ac92221e2f11?context=explore) off of your docker image. we are using a custom alpine:3.17 base image that installs openssl 3.0.8 and enables fips. We are running into an issue with the variable `NODE_EXTRA_CA_CERTS` that returns the error 
```
node[1]: ../src/node.cc:1040:std::unique_ptr<node::InitializationResult> node::InitializeOncePerProcess(const std::vector<std::__cxx11::basic_string<char> >&, node::ProcessFlags::Flags): Assertion `crypto::CSPRNG(nullptr, 0).is_ok()' failed.
```
I am having trouble finding any relevant information on the error nor that variable. My main question is "is node18 compatible with openssl 3.0.8? I see here that it is [compatible and fips capable with openssl 3.0.0](https://raw.githubusercontent.com/nodejs/node/main/BUILDING.md#:~:text=The%20current%20version%20of%20Node,openssl%2Dis%2Dfips%60.)

One other question if you know would be where that variable would store the cert in the container? NODE_EXTRA_CA_CERTS

### Node.js version

18.16.0

### Example code

I can paste the dockerfiles if you would like.
```
docker run -e NODE_EXTRA_CA_CERTS=cert.pem nodejs18-slim:test1
```
```
[[AWarning: Ignoring extra certs from `cert.pem`, load failed: error:80000002:system library::No such file or directory
```
```
node[1]: ../src/node.cc:1040:std::unique_ptr<node::InitializationResult> node::InitializeOncePerProcess(const std::vector<std::__cxx11::basic_string<char> >&, node::ProcessFlags::Flags): Assertion `crypto::CSPRNG(nullptr, 0).is_ok()' failed.
```

### Operating system

locally it is a mac intel 86x64x

### Scope

Runtime error that i think might be cause by our base image. Not a developer so am unfamiliar with node. I have googled this extensively but am lost at this point. Our image works fine thus far except for then trying to pass in new certs. 

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
https://github.com/nodejs/node/blob/c5f46293abe434b536f8caf24031692cba47e4f4/src/node.cc#L1039-L1040 
``` 
 // Ensure CSPRNG is properly seeded.
    CHECK(crypto::CSPRNG(nullptr, 0).is_ok())
```

Looks like CSPRNG init fails

can you try 
```
docker run -e NODE_EXTRA_CA_CERTS=cert.pem -it --memodry 2g --cpus 2  nodejs18-slim:test1
```

**Comment by richardlau** [comment]
As `NODE_EXTRA_CA_CERTS` is involved, this might be related to https://github.com/nodejs/node/issues/48143. https://github.com/nodejs/node/pull/48159 hasn't gone out in a release yet -- in needs to be released in Node.js 20 first before we consider it for Node.js 18.

**Comment by coltonfreeman26** [comment]
@tniessen We are using the system openssl with alpine. fips is being inherited. i messed around with this a little bit and i seem to have success with this when i install node via apk. i am guessing this has something to do with how we are enabling fips on the host. i am not familiar with CSPRING but will need to dive into that more. i will also take a look into enabling a random number generator. 

@preveen-stack i most certainly can. i will let you know if there is any luck there. 

@richardlau thank you for those links. i will read through those and update if this looks like our issue. 

thank you all for the feedback.

**Comment by ckcr4lyf** [comment]
> if you know would be where that variable would store the cert in the container? NODE_EXTRA_CA_CERTS

@coltonfreeman26 it should be the path to the certs _in_ the container. If `cert.pem` is a local file on the host system, you would need to copy it into the Dockerfile, and then provide the path relative to the container. 

Host dir structure:
```
$ ls
Dockerfile
my_extra_cert.pem
```

Dockerfile needs to copy the cert into the container:
```Dockerfile
FROM node:18

# Relative to the container, the cert will be in /my_extra_cert.pem!
COPY my_extra_cert.pem /my_extra_cert.pem 

# Other dockerfile stuff...
```

Then run as:

```
docker run -e NODE_EXTRA_CA_CERTS=/my_extra_cert.pem nodejs18-slim:test1
```

**NOTE THE VAR IS `/my_extra_cert.pem`!** (Absolute path)

**Comment by ckcr4lyf** [comment]
Btw, if you copy the cert into the container via the dockerfile, you can also specify the env variable in the dockerfile itself, e.g.:

```Dockerfile
FROM node:18

# Relative to the container, the cert will be in /my_extra_cert.pem!
COPY my_extra_cert.pem /my_extra_cert.pem 

# Other dockerfile stuff

# Set the extra ca certs var
ENV NODE_EXTRA_CA_CERTS=/my_extra_cert.pem 
```
