### ISSUE TITLE
SQlite Encryption Extension library [https://www.sqlite.org/see/doc/trunk/www/readme.wiki]

### ISSUE THREAD

**Issue by emilthomas1** [nodejs/help#416]
For using encrypted databases in node js, i have seen only sql-cipher being built against sqlite3 and used in node js. I am looking to use another encryption library known as sqlite encryption extension library  instead. Could you some one tell me if this is supported? If yes how do I use it?

**Comment by lordKnighton** [comment]
Closing for now: My apologies no one responded in time for your query - If you still need help, let us know.
