### ISSUE TITLE
NodeJs - Express - Pug - Got

### ISSUE THREAD

**Issue by oragain** [nodejs/help#4160]
### Details

So, installed a few modules like client-oauth2, azure cosmos and got.
Now, to be able to use got, I cannot use require() and have to use import from the error message I got. However, to use import, I need to add the type module in the package.json file
When I do that, I get the following error:
Unknown file extension "" for bin\www. Loading extension less files is not supported inside of "type":"module" package.json contexts.
No clue how to make all the modules play nice with one another. Any help would be appreciated

### Node.js version

Not applicable.20.1.0

### Example code

import httpClient  from 'got';

### Operating system

Windows

### Scope

runtime

### Module and version

GOT

**Comment by preveen-stack** [comment]
can you share your package.json

**Comment by oragain** [comment]
I think I got it working finally by updating all the references after
adding type module in the package file.
It seems like EJS works fine with module in package.json, but using --view
pug seems to not be compatible out of the box with ESM. So using the
express generator, you end up having to update everything.

I would point out that as a total noob at node and JS, I would have just
wished that the express-generator had an ESM option of some kind.
Cheers

**Comment by preveen-stack** [comment]
Good to hear that you got it working. Would you mind closing the issue @oragain

**Comment by oragain** [comment]
I would advise against using the express generator with PUG if you will be using ESM modules. Otherwise you will have to spend time revamping all the imports inside of the generated code when adding the ESM modules.
