### ISSUE TITLE
event loop and callback execution

### ISSUE THREAD

**Issue by NhatNguyen1810** [nodejs/help#4161]
### Details

What are the files I can read to bettern understand how the eventloop and callback of nodejs is executed? thanks. 

### Node.js version

Not applicable.

### Operating system

N/A

### Scope

code

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
https://github.com/nodejs/node/blob/main/src/README.md#event-loop

**Comment by tniessen** [comment]
Please refer to [the guides](https://nodejs.org/en/docs/guides) on the Node.js website.
