### ISSUE TITLE
Crowdin approval request

### ISSUE THREAD

**Issue by junstory** [nodejs/help#4162]
### Details

Hi! last week I did pull request translation in Korean and I heard that I can translate on Crowdin.
But until today, my request isn't approved. Can I join the team? Thank you :)

### Node.js version

Not applicable.

### Operating system

None

### Scope

Translating

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
https://github.com/nodejs/node/blob/main/doc/contributing/issues.md#triaging-a-bug-report may be of help
