### ISSUE TITLE
Different RssFile in two linux instance.

### ISSUE THREAD

**Issue by itachaaa** [nodejs/help#4166]
### Details

![image](https://github.com/nodejs/help/assets/31896600/0f207347-4605-483a-9f12-f2c65bf74408)
We run the node process in two Linux environments. At the beginning, the memory usage of the node process is pmap -x pid, as shown in the right figure. However, after a period of time, the file mapping corresponding to the node process in environment 1 is reduced to 10256 KB. The difference between the two environments lies in that the swap partition used by the current process is 10476 KB.
Run the cat /proc/pid/status command to check the status, as shown in the following figure.
![image](https://github.com/nodejs/help/assets/31896600/b1aec1d4-302e-43cd-acc5-8ba153ee674f)

It looks like the RssFile is reduced, and it looks like the code snippet in the node code + shared library mapping memory, and I want to know when the RssFile of the node process will reduced, and what is this part?

### Node.js version

v18.14.1

### Example code

Run the node to access the console.

### Operating system

Linux version 4.18.0-147.5.1.9.h499.eulerosv2r10.x86_64

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
Guess RSS is controlled by operating system rather than the process. Are your linux instances are completely identical? is there any difference in other processes running on the system?

**Comment by itachaaa** [comment]
> Guess RSS is controlled by operating system rather than the process. Are your linux instances are completely identical? is there any difference in other processes running on the system?

The Linux environment is the same, and the resource usage varies slightly. The swap partition in the low-occupation environment uses dozens of KB.
