### ISSUE TITLE
Error while debugging 

### ISSUE THREAD

**Issue by changkhothuychung** [nodejs/help#4169]
### Details

Hi everyone, while using lldb on mac to debug a program in the file test/node-api/1_hello_world/test.js, I ran into this issue 

`Process 72178 stopped

    frame #0: 0x00000001002fcbc6 node_g`node::NodeMainInstance::Run(this=0x000000030d0871f0, exit_code=0x000000030d087174, env=0x000000010a04a200) at node_main_instance.cc:98:23
   95  	    }
   96  	#endif
   97  	    if (!is_sea) {
-> 98  	      LoadEnvironment(env, StartExecutionCallback{});
   99  	    }
   100 	
   101 	    *exit_code =
Target 0: (node_g) stopped.
(lldb) n
nnode:internal/modules/cjs/loader:1073
  throw err;
  ^

Error: Cannot find module './build/Debug/binding'
Require stack:
`

Can anyone let me know what this error is and how to fix it? Thanks

### Node.js version

Not applicable.

### Operating system

N/A

### Scope

N/A

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
https://github.com/nodejs/node/blob/300f68e9d0fcee9f50dd124000b2027b24592c8a/lib/internal/modules/cjs/loader.js#L1055-L1074

**Comment by NhatNguyen1810** [comment]
Thanks! but how do I fix that error?
