### ISSUE TITLE
How to reuse a child process?

### ISSUE THREAD

**Issue by alexlarocca** [nodejs/help#4173]
### Details

Hello, I created a function that executes a command (Piper) to transform text into speech. It works but, each time I call it (on a Raspberry PI), the function takes more than 3 seconds to load the voice, and after that the creation of the wav file is very fast. Of course, this delay makes my function not usable since I call it a lot of time and I always I have to wait 3/4 seconds before to reproduce the speech. 

Is there any way I can "preload" the voice file and reuse the process in order to save the load time? This is my first project with Node, so I'm inexperienced. Thanks

### Node.js version

Not applicable.16.20.0

### Example code

```js
var voice = 'it-riccardo_fasol-x-low.onnx';
var filename = '/tmp/out.wav';
var cmd = 'echo "Ciao" | piper -m ' + voice + ' --output_file ' + fileName + ' && aplay ' + fileName;
			
exec(cmd, function(error) {
	if(error) {
	 	console.log('error while executing command ', cmd);
	}
});
```

### Operating system

linux/raspian

### Scope

code

### Module and version

Not applicable.

**Comment by marsonya** [comment]
There is no way (and is not recommended) to store the child_process spawned. Although in your case, you should try and separate the voice loading and process execution. Load the voice once separately and then have a second function to spawn your child_processes.
