### ISSUE TITLE
i can’t install node js on my mac 

### ISSUE THREAD

**Issue by SirOmar-8** [nodejs/help#4177]
### Details

When I download it it gives me many errors
I am writing this code in terminal (npx create-react-app app-001)
I just want to use react-js library

I'm still a beginner in programming

Note that the version I am downloading is: 18:16:00

And not the latest version

And thanks in advance

### Node.js version

18 : 16 : 00

### Example code

npx create-react-app app-001

### Operating system

MacOs

### Scope

installation

### Module and version

i can’t even install it

**Comment by tniessen** [comment]
How did you install Node.js? What error messages appear?

**Comment by SirOmar-8** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: app-001@0.1.0
npm ERR! Found: react@undefined
npm ERR! node_modules/react
npm ERR!   react@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/apple/.npm/_logs/2023-06-06T16_21_16_710Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/apple/.npm/_logs/2023-06-06T16_21_16_710Z-debug-0.log

**Comment by SirOmar-8** [comment]
> 

the same err

**Comment by tniessen** [comment]
Please show us your `package.json` file and the exact command that you used to produce this error message. It is impossible to help you if you don't provide relevant information.

**Comment by prettydiff** [comment]
Have you tried running `npm install` in the shell from your poject's directory?
