### ISSUE TITLE
Facing issue while connecting solr-client with Zookeeper for Solr-Cloud

### ISSUE THREAD

**Issue by satyendrahcl** [nodejs/help#4179]
### What is the problem this feature will solve?

I have solr-cloud setup with external Zookeeper. I am connecting solr-cloud to the node service. All are deployed in the same GKE cluster.
Solr does not have any officially supported library for nodejs. I am using  solr-client library in our node services.

 

With this library, I am able connect to solr cloud using solr-cluster I.P. and PORT but I want to connect it through zookeeper as its the ZooKeeper who is aware and keep track of the cluster state. While trying to connect it to zookeeper I passed the zookeeper service detail inside this client but I'm getting below error:

 

```
"message": "read ECONNRESET",
"stack": "Error: read ECONNRESET\n
```
<img width="1287" alt="image" src="[https://github.com/lbdremy/solr-node-client/assets/95628264/00df09ec-e542-4efd-8953-d6bcbeed96f4">](https://github.com/lbdremy/solr-node-client/assets/95628264/00df09ec-e542-4efd-8953-d6bcbeed96f4%22%3E)

 

I have tried to connect to zookeeper in many ways. First I provided zookeeper DNS service name but it didn't work. Then I provided public I.P. of zookeeper cluster with the port but stiil got the above error whereas ZKE is deployed in same GKE cluster and it is reachable to other services. 
We have java service as well we is successfully connected to zookeeper through its service DNS name.

 

Please guide me what should I do to run with ZooKeeper as I don't find any other node js library which can serve the purpose.

### What is the feature you are proposing to solve the problem?

I have solr-cloud setup with external Zookeeper. I am connecting solr-cloud to the node service. All are deployed in the same GKE cluster.
Solr does not have any officially supported library for nodejs. I am using  solr-client library in our node services.

 

With this library, I am able connect to solr cloud using solr-cluster I.P. and PORT but I want to connect it through zookeeper as its the ZooKeeper who is aware and keep track of the cluster state. While trying to connect it to zookeeper I passed the zookeeper service detail inside this client but I'm getting below error:

 

```
"message": "read ECONNRESET",
"stack": "Error: read ECONNRESET\n
```
<img width="1287" alt="image" src="[https://github.com/lbdremy/solr-node-client/assets/95628264/00df09ec-e542-4efd-8953-d6bcbeed96f4">](https://github.com/lbdremy/solr-node-client/assets/95628264/00df09ec-e542-4efd-8953-d6bcbeed96f4%22%3E)

 

I have tried to connect to zookeeper in many ways. First I provided zookeeper DNS service name but it didn't work. Then I provided public I.P. of zookeeper cluster with the port but stiil got the above error whereas ZKE is deployed in same GKE cluster and it is reachable to other services. 
We have java service as well we is successfully connected to zookeeper through its service DNS name.

 

Please guide me what should I do to run with ZooKeeper as I don't find any other node js library which can serve the purpose.

**Comment by preveen-stack** [comment]
> https://github.com/lbdremy/solr-node-client/assets/95628264/00df09ec-e542-4efd-8953-d6bcbeed96f4%22%3E
The link you provided is giving a 404 error

**Comment by gireeshpunathil** [comment]
are you able to ping the `zookeeper` endpoint? if no, fix that first. if yes, use NODE_DEBUG option for http and https (ref: https://stackoverflow.com/questions/38962957/how-to-enable-node-debug-without-environment-variables) and run the client to see additional debug messages that may give a clue to what is going on.
