### ISSUE TITLE
Enormous Node.js JavaScript Runtime consumption, despite heap information is OK

### ISSUE THREAD

**Issue by alexandis** [nodejs/help#4187]
I'm running **Angular** apps (here are 2 of them running on different ports):

> ng serve --configuration development --ssl --ssl-key ./localhost.key  --ssl-cert ./localhost.crt --port 4202

and trying to figure out what is going on lately. Please have a look at this memory consumption right from the start:
![image](https://github.com/nodejs/node/assets/6149843/94e23471-064e-47b1-9f64-0f9abf59b7b7)
Whereas heap information looks OK to me:
![image](https://github.com/nodejs/node/assets/6149843/6b055ded-84e2-4fe9-a98e-70c389aac2c2)
How to profile enormous memory consumption in my situation?
Node version is **18.14.1**

**Comment by preveen-stack** [comment]
cc @nodejs/performance

**Comment by tniessen** [comment]
If this is the RSS and not the amount of reserved virtual memory, you can see if [`--max-old-space-size`](https://nodejs.org/docs/latest-v20.x/api/cli.html#--max-old-space-sizesize-in-megabytes) helps. I believe Node.js 18 will use up to 2 GB by default, but you can restrict it to a smaller amount if the process doesn't need that much memory.

**Comment by mcollina** [comment]
My understanding is that `ng` also compiles typescript. In that case, the mentioned memory consumption is ok.
