### ISSUE TITLE
How do I update NodeJS by downloading a new .pkg from nodejs.org?

### ISSUE THREAD

**Issue by 00111000** [nodejs/help#419]
I have NodeJS v4.4.7 and I have downloaded NodeJS v7.3.0 from nodejs.org, but when I type in `node -v` is says that I still have v4.4.7. Why is that? What I am doing wrong?

I am able to run ES6 JS, does that mean I am running NodeJS v7.3.0!?
ps
I am on a Mac.
I don't want to use Homebrew.

**Comment by lordKnighton** [comment]
Try node use `v7.3.0` i think that should work.

**Comment by 00111000** [comment]
How do I make node use a specific version!?

**Comment by lordKnighton** [comment]
Again: in your command line `node use v7.3.0` or `node use 7.3.0` 

if this doesn't work for you let me know after, trying.

**Comment by 00111000** [comment]
It didn't work, in fact I don't think node does have a `use` command.

**Comment by SomeoneWeird** [comment]
@lordKnighton `node use` is not a thing. You may be thinking of `nvm`. 

@00111000 how did you originally install node? I recommend using [nvm.sh](nvm.sh) to manage your node installation as it allows seamless switching between versions. 

Let me know how you go.

**Comment by 00111000** [comment]
@SomeoneWeird I have originally installed node by downloading .pkg file from their official website. I have tried most reinstall guides, but I just can't delete node, I delete all its files, but it keeps coming back, I don't know how or why ...

**Comment by martinheidegger** [comment]
@00111000 "which node" in the terminal should usually point you to where node lies (on mac).

**Comment by 00111000** [comment]
@martinheidegger Mine lies in `/usr/local/bin/node`. I don't understand why when I download a new .pkg file from the node official website, it doesn't overwrite the old version or at least install a separate node folder.

**Comment by 00111000** [comment]
I have read about an NPM package `n`, which does install the latest version of node, but in a different path. How would I map node to read from that path?

**Comment by martinheidegger** [comment]
@00111000 it seems you also installed nvm once `nvm` Is a command line tool like `n` to manage different versions of node. If you run `nvm -h` you should get a list of options. More about nvm here:https://github.com/creationix/nvm

**Comment by lordKnighton** [comment]
My apologies @00111000 for closing issue with being solved.

I believe `nvm use` version of node should work for you. 

as you see here, I had `v6.4.0` & went to website & installed `v7.3.0` & then it was available to me. 


![screen shot 2016-12-26 at 1 16 04 pm](https://cloud.githubusercontent.com/assets/1773260/21486692/8d307948-cb6d-11e6-9515-e4324c3b8c90.png)


Link to another resource.  [link](https://davidwalsh.name/nvm)

**Comment by 00111000** [comment]
OMG, @lordKnighton , @martinheidegger For some reason I did have NVM installed, but I was not able to use it. I have deleted `.nvm` folder from `/Users/my-user-name/` and node automatically jumped to the correct directory `/usr/local/bin/node`. I now have v7.3.0. Thank so much!!

**Comment by 00111000** [comment]
You guys can close the issue now.
