### ISSUE TITLE
ESM loader v20.3.0 access parent path

### ISSUE THREAD

**Issue by kirrg001** [nodejs/help#4190]
### Details

Hi there!

In Node v18 the loader was able to easily access **all** cmd line args via`process.argv`.

> node --experimental-loader ./loader.mjs /opt/app/server.mjs

loader.mjs
```
console.log(process.argv)
```

> [
  '.../node/v18.16.0/bin/node',
  '/opt/app/server.mjs'
]

But with the [off-thread](https://github.com/nodejs/node/pull/44710) change, the `process.argv` are no longer complete.

> [ '.../node/v20.3.0/bin/node' ]

The second entry is missing. The path to the app is missing. 

I found a workaround, but I am not really happy with it. Wondering if there is an easier way.
When using the resolver hook, it is possible to get the parent path.

loader.mjs
```js
let appSpecifier;
export async function resolve(specifier, context, nextResolve) {
  if (!appSpecifier) {
    appSpecifier = specifier;
    process.argv[1] = appSpecifier.replace('file://', '');
    ...
  }

  return nextResolve(specifier, context, nextResolve);
}
```

This is important for APM tools, because we auto-load a tracer tool inside the loader to monitor an app. And we need access to the app path.

### Node.js version

v20.3.0

### Example code

See above.

### Operating system

darwin

### Scope

See above.

### Module and version

Not applicable.

**Comment by kirrg001** [comment]
> Are you perhaps looking for context.parentURL?

This would work too, but it is undefined for the first entry. 

> module/src/app.js, {
  conditions: [ 'node', 'import', 'node-addons' ],
  importAssertions: undefined,
  parentURL: undefined
}

In general I am looking for a solution without using the hooks.
If you have any idea, let me know :)

**Comment by giltayar** [comment]
Pass it to the loader via the `globalPreload` port mechanism (https://nodejs.org/api/esm.html#globalpreload). It's clunky, but it should work.
