### ISSUE TITLE
Which of setTimeout and setImmediate is executed first?

### ISSUE THREAD

**Issue by icoderMonkey** [nodejs/help#4198]
### Version

18.16.1

### Platform

Darwin xxxMacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Create a new index.js and write the following code, using npm init -y, to run it using commonJs (default) and esModule (type = "module") respectively

### What do you see instead?

In the current version of the environment, I created index.js and said, if it's in commonJs Modularity, that's what it says on the official website, but in the esmodule modularity specification, setImmediate is always done first, which is new feature, or bug, If instead of writing both in the I/O callback, can I determine that setImmediate under esModule has higher priority

<img width="546" alt="image" src="https://github.com/nodejs/node/assets/44015472/032ce25c-af5d-44c2-a658-06088f07981b">

**Comment by prettydiff** [comment]
You can test that yourself in any REPL.  A delay of 0 milliseconds just pushes the callback into the next call stack of the event loop without additional delay.  The setImmediate function does the same thing without any delay specified.

https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

If after testing one of those methods is always faster than the other there is some performance consideration happening in V8.  I would suggest testing these scenarios in a micro benchmark.  These methods are common to both the browser and Node as they come from the language run time, V8 so you can even test this in your browser.  I like https://jsbench.github.io/ for micro benchmarks.

**Comment by G0ngzheng** [comment]
> You can test that yourself in any REPL. A delay of 0 milliseconds just pushes the callback into the next call stack of the event loop without additional delay. The setImmediate function does the same thing without any delay specified.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate
> 
> If after testing one of those methods is always faster than the other there is some performance consideration happening in V8. I would suggest testing these scenarios in a micro benchmark. These methods are common to both the browser and Node as they come from the language run time, V8 so you can even test this in your browser. I like https://jsbench.github.io/ for micro benchmarks.

Without setting anything, as the website says, you can set the type in package.json to module after npm init -y and then execute the above code several times to see the specific print
