### ISSUE TITLE
Node V5 has issues with installing behind proxies (v0.12 works fine)

### ISSUE THREAD

**Issue by wyattbiker** [nodejs/help#42]
Why is V5 different from v0.12.  Putting the link here as well for steps to a solution. Thanks!

https://groups.google.com/forum/#!searchin/nodejs/wyattbiker/nodejs/_biylHUjedE/O6gQjuFoBwAJ

**Comment by Trott** [comment]
TLS is being handled more securely than in earlier versions. If your proxy is using an invalid/untrusted certificate, then it is rejected. This is a feature, not a bug. By refusing to work with a proxy's invalid/untrusted certificate, the user is being protected from man-in-the-middle and other attacks.

**Comment by lordKnighton** [comment]
Closing for now, feel free to reopen.
