### ISSUE TITLE
View: Root TypeError: undefined is not an object (evaluating 'P.replace')

### ISSUE THREAD

**Issue by mvallde** [nodejs/help#4205]
### Details

I can't access to my worker's profile of the App Amnesia. 

![BE335E36-C595-4D60-97AD-EFE3D534F8EF](https://github.com/nodejs/help/assets/139587657/38f00f70-b81a-4814-9ed8-0c2f0a4018f9)

### Node.js version

Not applicable.

### Operating system

IOS iPhone 

### Scope

Access to personal workers profile 

### Module and version

Not applicable.

**Comment by gireeshpunathil** [comment]
this is most likely an application problem, not a node.js issue - due to attempting to access uninitialised / unassigned variable. You should report this to `Amnesia` project.

**Comment by gireeshpunathil** [comment]
closing.
