### ISSUE TITLE
DNS resolution failure on extremely simple Express server.

### ISSUE THREAD

**Issue by JB0925** [nodejs/help#4206]
### Details

I have run into an issue lately where I am starting a very simple Express server and, upon doing so, am getting the DNS resolution error of ENOTFOUND.

The weird thing, though, is that the hostname is “base,” as in it seems to be trying to resolve the hostname of base. The code is very simple “app.listen(8080, () => console.log(“hello”))”

This happens even if I pass in a host to listen.

I know that a workaround would be to change the /etc/hosts file to include “127.0.0.1     base”, but I am curious if this has been brought up before and where “base” could be coming from. I spent a good bit of time debugging through source code but still cannot understand why it is trying to resolve “base.”

Any ideas would be appreciated. Thank you.

### Node.js version

19.7.0

### Example code

```
const express = require(“express”);

app = express();

app.listen(8080, () => console.log(“hello”));
```

### Operating system

Mac OS

### Scope

Runtime

### Module and version

dns

**Comment by preveen-stack** [comment]
can you share the log

**Comment by tanakatoo** [comment]
Hi, I'm getting the same "base" error. Did you find out why? Thanks.

**Comment by JB0925** [comment]
@preveen-stack , sure. Thank you.

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: getaddrinfo ENOTFOUND base
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'base'
}

Node.js v19.7.0
```

I used a debugger to follow a call all the way until it reached that point, but did not see anything that stuck out as to why it would be setting the hostname as `base`. Thanks for taking a look.

**Comment by JB0925** [comment]
@tanakatoo quick question: are you using `node-pg` client library for connecting and interacting with Postgres?

**Comment by tanakatoo** [comment]
Yes I am!

**Comment by JB0925** [comment]
I was talking to someone else and they determined that this is actually an issue with `node-pg` v8.11.0

Downgrading to anything lower seemed to solve it for them. On the other side, I checked out their Github issues and it seems like it was fixed in 8.11.1. So you can probably try that one, too. I haven’t tried it myself, as I was only looking into this to help someone else.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tanakatoo** [comment]
Thanks, I'll try different versions to see if it fixes the problem when I
have time. For now, I'm using your hack of adding base to the etc/hosts
file.

**Comment by JB0925** [comment]
Closing as I bel
