### ISSUE TITLE
Extend IncomingMessage and ServerResponse classes

### ISSUE THREAD

**Issue by chyzwar** [nodejs/help#421]
Hi, 
 
I am looking for clean way to extend IncomingMessage and ServerResponse classes. 
Currently it is only possible by:
- manipulation on __proto__ (express.js)
- wrapping in object/proxy (hapi.js)

Both these approaches are bad for multiple reasons. It would be nice if node can provide better way to customise these classes. 

For example:
```js
class MyRequest extends IncomingMessage{
   myMethod(){
    //Do my Stuff
   }
}
```
I would want get instances of this class in request event. The same thing for ServerResponse. 

@mscdex as requested I am opening issue in correct place, please take a look.

**Comment by lordKnighton** [comment]
@chyzwar Im gonna close this issue: I apologize no one got to your issue before. If you still need help, let us know.
