### ISSUE TITLE
Node.js installation in Kali

### ISSUE THREAD

**Issue by Johannes099** [nodejs/help#4213]
### Details

If i try to Install Mode.js in Kali Linux at the Second Last step of the internet Tutorials IT Takes 100% of useage of my PC or Laptop IT doesnt Matter which im using and i cant do anything anymore. My computer First Turns very very slow and that ITS on but ITS balck and unusable and i have to hardreset

### Node.js version

Doesnt matter

### Example code

```shell
sudo fakeroot checkinstall -y --install=no --pkgversion $(echo $(pwd) | sed -n -re's/.+node-v(.+)$/\1/p') make -j$(($(nproc)+1)) install
```

### Operating system

Kali linux

### Scope

Installation

### Module and version

Not applicable.

**Comment by prettydiff** [comment]
I recommend installing via NVM.  You can find NVM at https://github.com/nvm-sh/nvm

**Comment by preveen-stack** [comment]
is it possible to provide logs so that build team can take a look
