### ISSUE TITLE
Starting nodemon & eslint Error

### ISSUE THREAD

**Issue by CameronB-Git** [nodejs/help#4214]
### Details

I want to create a backend server that can store a list of values, that can be appended to etc. I have installed nodemon, node js, es lint etc. I have also created the package.json file for the backend server, as well as "app.js". To start the server, I run "npm start", and it throws an error when running the lint command: "The system cannot find the path specified". 
![Screenshot 2023-07-27 131339](https://github.com/nodejs/help/assets/114142256/08e66f32-a01a-4f6a-a5c1-eb1f9ff1586e) Screenshot of the error in cmd. 

![image](https://github.com/nodejs/help/assets/114142256/1ad6ec57-bd1b-49c3-81f4-046384bfa6e5)
Screenshot of the package.json file. 

![image](https://github.com/nodejs/help/assets/114142256/3eb78b81-5419-45ea-b39c-65a131eaf859)
Screenshot of the app.js file (console.log('hello) for testing purposes).

(I'm very new to JS as a whole, so it might just be a stupid mistake)

### Node.js version

![image](https://github.com/nodejs/help/assets/114142256/58d3674c-51f0-41e8-b705-0c3d715791a8)

node version - 20.5.0

### Operating system

Windows 11

### Scope

I need the server to run alongside the frontend server

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
Try changing to  "./node_modules/.bin/eslint app.js"

**Comment by CameronB-Git** [comment]
> 

Just tried this! Still returning the same error.

**Comment by CameronB-Git** [comment]
Didn't mean to close the issue :) Tried the above suggestion, didn't work.
