### ISSUE TITLE
mac m2 start react project error

### ISSUE THREAD

**Issue by sen-cs** [nodejs/help#4217]
### Version

v16.20.1

### Platform

Darwin MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64

### What steps will reproduce the bug?

npm start

> ruby-ui@1.0.0 start
> webpack-dev-server --open --config webpack.dev.js --mode development --hot

sh: webpack-dev-server: command not found

### What do you see instead?

<img width="756" alt="image" src="https://github.com/nodejs/node/assets/140896762/51a76edd-0519-4a62-a382-bf5b956f398b">

**Comment by prettydiff** [comment]
Have you tried running `npm install` in your project?
