### ISSUE TITLE
Nodejs instances runs for 2 seconds and pauses for 30 

### ISSUE THREAD

**Issue by jianshenglow** [nodejs/help#422]
In one NodeJS VM, I have 6 instances. When I hit all of the 6 instances separately and monitor all console logs together, it is observed that there is a flurry of activity on all console logs for 2 seconds, followed by a 30 second period of inactivity. This pattern repeats itself.

This cycle occurs at the exact same time for all 6 instances whether or not the start time of the Jmeter test is varied. The resulting tps is very low.

May I know if this behavior is normal to NodeJS or if some tuning needs to be done and if yes, what should be tuned?

**Comment by bnoordhuis** [comment]
It's not normal but I can't tell you what you should tune, you didn't provide enough information for that.  Have you tried profiling your application?
