### ISSUE TITLE
Native Test Runner: Mocking packages that are exported as classes

### ISSUE THREAD

**Issue by willdavies0** [nodejs/help#4220]
### Details

I'm trying to write mocks for a class that gets initialised in the file I am testing.

Please see the code example below for a detailed example of the problem. This problem often arises when trying to mock 3rd party packages (eg AWS-SDK) that export there APIs as a class that must be initialised.

Coming from Jest where mocking classes like this is very easy, I feel like I am missing something fundamental in how to use the node test runner.

Any help greatly appreciated!

### Node.js version

v20.5.0

### Example code

Below there are three 'files'. The Class I wish to mock, a file that creates an instance of the class, and the test file.

ClassToMock.js
```javascript
class ClassToMock {
  constructor() {
    this.foo = 'bar'
  }

  doSomething = () => {
    return this.foo;
  }
}

export { ClassToMock }
```

fileToTest.js
```javascript
import { ClassToMock } from './ClassToMock.js'

const functionToTest = () => {
  const instance = new ClassToMock();
  return instance.doSomething();
}

export { functionToTest }
```

fileToTest.test.js
```javascript
import { test, mock } from 'node:test'
import assert from 'node:assert'
import { ClassToMock } from './ClassToMock.js
import { functionToTest } from './fileToTest.js

// mocking a method of the class
mock.method(ClassToMock, 'doSomething', () => 'Hello World')

test('test method mock', () => {
  const result = functionToTest()
  assert.strictEqual(result, 'Hello World') // AssertionError Expected: 'Hello World' Actual: 'bar'
})

// mocking the entire class
mock.fn(ClassToMock, () => {
  return {
    doSomething: () => 'Bye world'
  }
})

test('test instance mock', () => {
    const result = functionToTest()
    assert.strictEqual(result, 'Bye World') // AssertionError. Expected: 'Bye World' Actual: 'bar'
})
```

### Operating system

macOS

### Scope

Native Test Runner

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
cc @nodejs/testing

**Comment by cjihrig** [comment]
Untested, but I think you want this:

```js
// mocking a method of the class
mock.method(ClassToMock, 'doSomething', () => 'Hello World')
```

to be this:

```js
// mocking a method of the class
mock.method(ClassToMock.prototype, 'doSomething', () => 'Hello World')
```

You can see more mocking examples in https://github.com/nodejs/node/blob/main/test/parallel/test-runner-mocking.js.

**Comment by willdavies0** [comment]
Thanks a lot for this @cjihrig 
Are there plans to add these examples to the docs [https://nodejs.org/api/test.html](https://nodejs.org/api/test.html)?

**Comment by cjihrig** [comment]
There are no plans that I'm aware of. Documentation PRs are always welcome, although I don't know if it makes sense to document every possibility.

**Comment by 0618** [comment]
I tried using `prototype` [mentioned above](https://github.com/nodejs/help/issues/4220#issuecomment-1691688789), but got the following error:

> TypeError [ERR_INVALID_ARG_VALUE]: The argument 'methodName' must be a method. Received undefined

any other suggestions? @cjihrig

**Comment by cjihrig** [comment]
@0618 I have no clue what your code looks like so it's difficult to provide suggestions.
