### ISSUE TITLE
src.once is not a function in pipeline

### ISSUE THREAD

**Issue by kevin-ye225** [nodejs/help#4221]
### Details

Hi,
I am currently doing pipeline(res.body, dest, err => err handling) after getting the response from node-fetch, after upgrading to node 18, it is throwing an error saying that src.once is not a function, I look at the response type from node-fetch, while the body is indeed a ReadableStream that implements EventEmitter, which has a once function, when I log it, it says undefined, which is why it is causing this to fail i think. 

I tried switching to the global fetch provided in node 18 with no luck. How should I address this? polyfill the once function somehow? 

### Node.js version

18.17.0

### Example code

 pipeline(res.body, dest, (err) => {
      if (err) {
          return rej(err);
      }
     return res();
   });

### Operating system

macOS

### Scope

runtime

### Module and version

Not applicable.

**Comment by prettydiff** [comment]
Please provide a sample of code so that any of us can experiment and attempt to reproduce your concerns.
