### ISSUE TITLE
Virus alert when installing node-v20.5.1-x64.msi

### ISSUE THREAD

**Issue by Faster22** [nodejs/help#4225]
### Details

Virus alert during install , leading to failed installation.

### Node.js version

[node-v20.5.1-x64.msi](https://nodejs.org/dist/v20.5.1/node-v20.5.1-x64.msi)

### Example code

![image](https://github.com/nodejs/help/assets/58865387/2e8b98d8-1de9-4708-9135-d414621a9860)

### Operating system

Edition	Windows 11 Pro
Version	22H2
Installed on	‎2022-‎10-‎06
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

### Scope

Installation failed

### Module and version

Not applicable.

**Comment by prettydiff** [comment]
I don't think that is a user issue requiring code guidance or help.  My recommendation is:

1) search the issues in https://github.com/nodejs/node repository to see if this is already reported
2) if not report this as a new issue of type security
3) contact the anti-virus vendor with the address of the new node issue

Either the anti-virus vendor is falsely identifying the memory footprint associated with that executable to a known malicious signature or there is a problem in Node that displays a memory pattern similar to a known malicious signature.

**Comment by preveen-stack** [comment]
submitted to avira https://www.avira.com/en/analysis/submit-url for analysis

**Comment by preveen-stack** [comment]
cc @nodejs/package-maintenance @nodejs/security

**Comment by mcollina** [comment]
cc @nodejs/releasers @nodejs/tsc PTAL

**Comment by targos** [comment]
Not sure what we can do. This online analysis gives 0 issues: https://www.virustotal.com/gui/file/9944eb363ac958a667d2c709fcd8bac8c93b9263c7ea50a2d381860ac6c7de85/detection

**Comment by preveen-stack** [comment]
`suspicious behavior blocked - Memory Buffer `
Guess only manifesting during install and not on a file or URL scan
