### ISSUE TITLE
createRequire - can't figure out or it's a bug

### ISSUE THREAD

**Issue by Mozzart88** [nodejs/help#4229]
### Details

Hello!
For a testing purposes I need to dynamically load and unload modules. My solution is looks like this
```JavaScript
import { test } from 'node:test';
import assert from 'node:assert';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);
function clearModule(id, src) {
    const module = require.cache[require.resolve(id)];
    const root = path.parse(path.resolve(src)).dir;
    if (module && 'children' in module && module.children.length > 0) {
        for (const child of module.children) {
            if (child.loaded && child.path.includes(root))
                clearModule(child.filename, src);
        }
    }
    console.log(module);
    delete require.cache[require.resolve(id)];
}

function requireModule(id) {
    return require(id);
}
```
This usage is documented [here](https://nodejs.org/api/module.html#modulecreaterequirefilename)

And it works fine with `tsx`, but not with `node`. With node it throws an exception `ERR_REQUIRE_ESM`  with this message:
```
require() of ES Module /app/build/src/app.js from /app/build/tests/unit/app.test.js not supported.
    Instead change the require of app.js in /app/build/tests/unit/app.test.js to a dynamic import() which is available in all CommonJS modules.
```

### Node.js version

v 18.15
v 20.15.0

### Operating system

MacOS Ventura 13.4.1 and on docker 

### Scope

code, runtime, meta
(don't really understand this question)

### Module and version

node:module

**Comment by preveen-stack** [comment]
cc @nodejs/loaders

**Comment by aduh95** [comment]
It's not a bug, `require`ing ES modules is not possible, you need to use `import()`.
Clearing loaded ES modules is also not possible because the ECMAScript spec does not define any way to clear modules.

You could load several instances of the same module by using query string, e.g. `import('./file.js')` and `import('./file.js?test=0')` would load two module instances of the same `file.js` file.

**Comment by Mozzart88** [comment]
Great, Thnx!
But I still don't understand the usage of the `createRequire` function - if `require` is not possible in ES, then why do we need this function and how should we use it?

**Comment by aduh95** [comment]
`createRequire` is provided as an escape mecanism for apps that relies upon a legacy feature of the CJS loader. It's not meant to be used unless you have no other choice.

**Comment by Mozzart88** [comment]
Okay, but it's not working properly.
Or did I use it incorrectly? In my case, it just throws an error.

**Comment by isocroft** [comment]
>require() of ES Module /app/build/src/app.js from /app/build/tests/unit/app.test.js not supported.
    Instead change the require of app.js in /app/build/tests/unit/app.test.js to a dynamic import() which is available in all CommonJS modules.

@Mozzart88 , as per the error details you pasted above, the main issue is that you are trying to `require()` an ES module which is impossible.

You can only `require()` a CommonJS module either in another CommonJS file or in an ES module file like you have above using `createRequire()`
