### ISSUE TITLE
Kernel TLS

### ISSUE THREAD

**Issue by grijjly** [nodejs/help#4230]
### Details

my kernel version is 5.12+ (ubuntu)
i execute sudo modprobe tls
i set secureOptions on https create server as 8 (8 is SSL_OP_ENABLE_KTLS)
i use version 20+ which use openssl 3.0.7
but when i trace node, only setsockopt is TCP_NODELAY
it does not activate ktls somehow,

### Node.js version

v18.17.0

### Example code

   const https=require('https')
    const handleHttp=require('./http')
    const server=https.createServer({
        key:fs.readFileSync('./suitable.live.key'),
        cert:fs.readFileSync('./suitable.live.pem'),
        ciphers: 'AES128-GCM-SHA256',
        secureOptions:984|536870912
    },handleHttp)
    server.listen(443)

### Operating system

linux ubuntu kernel version 5.12+

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
cc @nodejs/crypto

**Comment by tniessen** [comment]
@grijjly Are you using a custom build of OpenSSL with Node.js? The default compile-time configuration of OpenSSL disables KTLS, which means that it cannot be enabled at runtime.

**Comment by civilianatpoint** [comment]
> @grijjly Are you using a custom build of OpenSSL with Node.js? The default compile-time configuration of OpenSSL disables KTLS, which means that it cannot be enabled at runtime.

how can i do that ? how to compile with ktls enabled sir ?

**Comment by civilianatpoint** [comment]
> cc @nodejs/crypto
> 
> Can you try setting secureOptions as described in this doc https://www.codexpedia.com/node-js/nodejs-tls-configuration-server-and-client-example/
> 
> ```
> secureOptions: constants.SSL_OP_NO_SSLv2 | ....
> ```

i made right int value for that, only tls 1.2 working and i tested it with tls checker. i think problem is described by @tniessen

**Comment by tniessen** [comment]
> how can i do that ? how to compile with ktls enabled sir ?

OpenSSL needs to be configured with [`enable-ktls`](https://github.com/openssl/openssl/blob/e2972982c64f3f1ac10b3ebe1086d99ec67631bd/INSTALL.md?plain=1#L557-L565). Then you should be able to link against that custom build of OpenSSL as described [here](https://github.com/nodejs/node/blob/6117cc3bd1184d0cbd0cb0831d0fd82bc53ed1b0/BUILDING.md#building-to-use-shared-dependencies-at-runtime), i.e., using `--shared-openssl` etc.

That might not be sufficient though, see https://github.com/openssl/openssl/issues/14595#issuecomment-801822348. In particular, I am not sure if we use a compatible `BIO`. cc @bnoordhuis

**Comment by grijjly** [comment]
update: i tried build node with ./configure --openssl-conf-name=enable-ktls
i set secureOptions:984 also tried 8 but 984&8=8 
modprobe tls was already loaded because of recent nginx setup, but loaded anyway.
i tried to send after https parsed on my endpoint i sent fs.write(fd,buffer) but got ssl error on browser then i thought maybe nodejs handle it somehow then checked sudo nano /proc/net/tls_stat:
TlsCurrTxSw                             0
TlsCurrRxSw                             0
TlsCurrTxDevice                         0
TlsCurrRxDevice                         0
TlsTxSw                                 0
TlsRxSw                                 0

i think i made everything right but nodejs does not use something neccesary i think
