### ISSUE TITLE
Need documentation on NodeJS Minor Version Support Policy

### ISSUE THREAD

**Issue by uberDoward** [nodejs/help#4234]
### Details

Let me first preface this with an apology.  I, like every other developer on the planet, am well aware that when Node 20.3 is released, that very implicitly makes 20.2 deprecated.

I have been unsuccessful in communicating this to our internal End of Life team, and they require official documentation from the vendor before they will let me mark a minor version deprecated and no longer permitted for use.

If anyone on the Steering Committee could perhaps point me to a document that spells out the obvious, I would be grateful.

I am also not at all opposed to writing up this document myself and submitting a PR - just let me know how the Node TSC would like this to proceed.

### Node.js version

Not applicable.

### Operating system

Irrelevant 

### Scope

Documentation 

### Module and version

Not applicable.

**Comment by uberDoward** [comment]
I have to get approval before I may submit the PR.

To be clear, "no longer permitted for use" is not what I would like Node to state, lol.

I would be aiming for something like "A new minor release supersedes and deprecates the prior minor release for a given major version (eg, 20.5's release means 20.4 will no longer be supported)".

Would this be acceptable?

**Comment by richardlau** [comment]
I would not use the word "deprecates". Maybe something like "A new release within a release line supersedes previous releases on that line. Any fixes on the release line will be released as the next semver minor or semver patch release from the most recent release on that line."

cc @nodejs/releasers
