### ISSUE TITLE
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203.

### ISSUE THREAD

**Issue by TechBear72** [nodejs/help#4237]
### Details

While trying to install on Windows 10 64-bit (v18.17.1, though the same with others), after uninstalling an old version, get the error:

The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203.

I have found the same thing reported here:
https://github.com/nodejs/node/issues/29972
https://github.com/nodejs/help/issues/2231

However, the proposed solutions don't resolve the issue - you can't "right click the installer and run as administrator" as it's an MSI file, and as for the %temp% folder, I already have Full Control, and am logged in with an account which is an Administrator anyway.

### Node.js version

N/A

### Operating system

Microsoft Windows [Version 10.0.19045.3324]

### Scope

Installation

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
would you mind sharing the log of the error @TechBear72

**Comment by preveen-stack** [comment]
Please check [This](https://success.trendmicro.com/dcx/s/solution/1107889-error-code-2203-shows-when-installing-the-worry-free-business-security-wfbs-agent?language=en_US&sfdcIFrameOrigin=null#:~:text=The%20error%20code%20is%202203,missing%20permissions%20in%20temp%20folder.)
