### ISSUE TITLE
Error: ESPIPE: invalid seek, write

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#424]
hey all, looking for some help

I have this file, I am simply trying to find the first line that matches, and then blank it out, replacing the line with a blank line.

I invoke the script like so:

`node lib/blank.js /home/oleg/dogs.txt \\S+`

but when I do, I get this error:

`Error: ESPIPE: invalid seek, write`

the error is passed to the line indicated below in the comment

```js
#!/usr/bin/env node

const readline = require('readline');
const fs = require('fs');
const os = require('os');

const file = process.argv[2];
const rgx = new RegExp(process.argv[3]);

const fd = fs.openSync(file, 'r+');

const strm = fs.createReadStream(null, {fd: fd});
const rl = readline.createInterface({
    input: strm
});

const eolLength = String(os.EOL).length;
let position = 0;
let bytesRead = strm.bytesRead;

const onLine = line => {

    if (String(line).match(rgx)) {

        let len = line.length;

        rl.close();
        rl.removeListener('line', onLine);

        //overwrite the line with a blank line
        fs.write(fd, new Array(len + 1).join(' ') , position, 'utf8',

            (err, written, string) => {

            if (err) {   // <<<<<<<<<<<<         err is passed here
                process.stderr.write((err.stack || err) + '\n');
                return process.exit(1);
            }
            else {
                // output the line that will be replaced/removed
                process.stdout.write(line + '\n');
                process.exit(0);
            }

        });

    }
    else{

        position += (line.length + eolLength);
    }
};

rl.on('line', onLine);
```

I swear this was working before, but now I get this one line stderr message:

`Error: ESPIPE: invalid seek, write`

I can't figure out why the error is happening, any idea what it might be about?

**Comment by ORESoftware** [comment]
Strangely, I also get this error on occasion

`Error: EBADF: bad file descriptor, write`

**Comment by ORESoftware** [comment]
I added this line:

` fs.closeSync(fd);`

but then I get:

```
fs.js:526
  return binding.close(fd);
                 ^

Error: EBADF: bad file descriptor, close
    at Object.fs.closeSync (fs.js:526:18)
    at fs.write (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/lib/blank.js:37:16)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:671:5)

```

**Comment by ORESoftware** [comment]
the file exists, and this script runs successfully once, if I write to the text file manually and then save it and then re-run the script

**Comment by vsemozhetbyt** [comment]
5. If the error cause is `process.stderr.write`, not the `fs.write`, does anything change with `console.error` instead?

**Comment by ORESoftware** [comment]
@vsemozhetbyt let me try your ideas, I am on Ubuntu and node v7.2.1

well sure enough, if I change \\S+ to \S+, it works! 

that is so weird, why would I get a bad file descriptor error, for a "bad regex"?

**Comment by ORESoftware** [comment]
it works up until here:

![screenshot from 2017-01-01 14-02-40](https://cloud.githubusercontent.com/assets/11139560/21583204/035e9f84-d02b-11e6-805c-c5ec307916d4.png)

it has "blanked out" all the lines above fish, every time the command is run.
But then it fails when it tries to blank out "fish", and I don't know why

**Comment by vsemozhetbyt** [comment]
It seems I've found one possible oversight: try to use `autoClose: false` in the `fs.createReadStream()` [options object](https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options). Otherwise, it is closed by the end of the reading process before the last writing attempt.

**Comment by ORESoftware** [comment]
@vsemozhetbyt  that worked! thanks that makes sense!
