### ISSUE TITLE
Questions about GYP and Makefile in Node.js

### ISSUE THREAD

**Issue by jasonjiicloud** [nodejs/help#4242]
### Details

Hi, everyone,

I'm a Node.js researcher, I'm working on helping developers in my country to learn Node.js more easily.

When I read Node.js source code, I found Node.js uses GYP to build, but I also found that there’s a big Makefile, it has thousands of lines.

I have two questions:

1. We already have GYP, why do we need a Makefile? We can use GYP to do anything. Or why don't we remove GYP, only use Makefile to build Node.js(because V8 needs it?)?

2. If I want to add a build related feature, which one should I use, adding it to GYP config file or Makefile?

Thank you in advance!

### Node.js version

Not applicable.

### Operating system

Question about Node.js source code.

### Scope

GYP and Makefile

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
> The functionality of GYP is similar to the [CMake](https://en.wikipedia.org/wiki/CMake) build tool. GYP processes a file that contains a [JSON](https://en.wikipedia.org/wiki/JSON) dictionary[[2]](https://en.wikipedia.org/wiki/GYP_(software)#cite_note-2) in order to generate one or more target project make files. The single source .GYP file is generic while the target files are specific to each targeted build tool.

Ref https://en.wikipedia.org/wiki/GYP_(software)
perhaps the above can answer your question

**Comment by jasonjiicloud** [comment]
@preveen-stack, thank you for help!
Yes, you're right. Ah.. I know what GYP is used for, it can be used to generate Makefiles or xcodeproject file.
But why does Node.js use GYP and Makefile in parallel?
To my knowledge, we could remove that big Makefile, and move everything to GYP configure file.

**Comment by preveen-stack** [comment]
I guess it is probably evolved over time. One way to find out is to estimate the effort involved in going for a GYP only codebase

**Comment by jasonjiicloud** [comment]
Yeah, I guess so. Another reason maybe that GYP has already been deprecated, so new features will not be implemented by GYP anymore.
