### ISSUE TITLE
How do I achieve the same performance as a multi-threaded language with nodejs, which is single threaded?

### ISSUE THREAD

**Issue by ItaloCobains** [nodejs/help#4246]
### Details

I've already made some nodejs api's for some of my projects but I've been having some performance problems and I was recommended to use some multi thread frameworks like python's fastapi, I really like nodejs and I wanted to have the same performance for both rest apis and websocket etc. How can I achieve this? I'm no expert so I might be talking shit.

### Node.js version

nodejs=20.6.1

### Operating system

Windows 11

### Scope

Don't have code.

### Module and version

Not applicable.

**Comment by ljharb** [comment]
to be clear, node isn't a language; JS is. node also supports wasm and native modules, so you can author in C++, Rust, etc, if the performance of JS isn't to your liking.

**Comment by ItaloCobains** [comment]
Perdão por dizer que node é linguagem, entendi tem algum artigo para mim ler sobre a criação desses modulos em C++, rust...

thanks for the help.

**Comment by ItaloCobains** [comment]
Sorry for calling node a language, do you have any article or document explaining how to create and use these modules?

thanks for the help.

**Comment by ljharb** [comment]
I don't have anything off the top of my head; https://blog.risingstack.com/writing-native-node-js-modules/ is something i just found on google.

**Comment by ItaloCobains** [comment]
thank you.
