### ISSUE TITLE
Help with node.js

### ISSUE THREAD

**Issue by adviiik** [nodejs/help#4249]
### Details

I've been trying to make an app on react native with node and Visual Studio code, the initial phase was running smoothly but now suddenly when I try to open the app on the Android emulator it keeps on getting stuck on a certain percentage and I have no clue on how to tackle this! Ive been trying various different methods I don't know if the memory allocation to node is the reason, if it is can someone explain how to do that?

![image](https://github.com/nodejs/help/assets/145081171/d4c6ca1d-c8dc-48f2-bc7c-282cc1ae01c9)

like the percentage is just stuck like that

### Node.js version

Not applicable.

### Operating system

Windows 10

### Scope

No clue.

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
As far as I know, Node.js does not use any progress bar (or similar) internally; this is probably an issue with your IDE rather than with Node.
