### ISSUE TITLE
How to host nodejs application with sockect.io

### ISSUE THREAD

**Issue by ajithv11** [nodejs/help#425]
I have build an chat application using nodejs. I have developed on my windows system and it works fine.

Now I want to make it live on a server to check its real time performance, As a beginner I don't know which server hosting should I choose to develop nodejs application, so someone please suggest me a hosting for nodejs application?

**Comment by lordKnighton** [comment]
My  2 cents opinion, i would go with heroku. There are other good ones like docker & digitalocean 

But here you go - https://www.youtube.com/results?sp=EgIIBQ%253D%253D&q=deploy+node+app

just google or youtube it, & set your filter to recent, so you will know the content of the vid is still good.

**Comment by lordKnighton** [comment]
if you need more help, do let me know :) happy coding
