### ISSUE TITLE
How to host node api on macos using xampp apache web server and mysql?

### ISSUE THREAD

**Issue by fldvlpr** [nodejs/help#4250]
### Details

Hi There

I was working on a windows project and created some node apis and I have hosted them in local windows pc using iis server successfully.

After that I had one more requirement of hosting node api on mac os local server similar to iis server. I was able to run the same project using xampp and started services mysql database and apache web server and it was working fine.

But, I couldn't  find a way to host this node api on my local macbook server anyway.

Can anyone help me or suggest a possible workaround?

Thanks

### Node.js version

Not applicable.

### Example code

Not applicable.

### Operating system

MacOS

### Scope

Hosting

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
> But, I couldn't find a way to host this node api on my local macbook server anyway.

What is the issue / errors you are seeing

**Comment by matschik** [comment]
You are coming from PHP for sure. You don't need Apache or anything. Just run a http server to a port and you are good to go. Here is a minimal http server, created the file "server.js" with:

```js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello, World!\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});

```

And run it: `node server.js`
