### ISSUE TITLE
Regular errors downloading Node.js tarballs

### ISSUE THREAD

**Issue by shadowspawn** [nodejs/help#4254]
### Details

Users of `n` are [reporting](https://github.com/tj/n/issues/784) problems with around 5% of Node.js installs in CI failing while downloading the tarball with curl. Three different users, at least two using AWS CodeBuild.

Not got a lot of information, but I thought it was worth asking:
- Have there been any recent changes or problems with CDN that might explain increased errors? 
- Is there anything I can do to make the downloads more reliable? (Specify the http version to use?)

The reported errors are:
```console
       fetch : https://nodejs.org/dist/v14.21.3/node-v14.21.3-linux-x64.tar.xz
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

fetch : https://nodejs.org/dist/v18.14.2/node-v18.14.2-linux-x64.tar.xz
23 | curl: (18) transfer closed with 9476756 bytes remaining to read

       fetch : https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-x64.tar.xz
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

### Node.js version

Not applicable.

### Operating system

linux-x64 (based on logs supplied)

### Scope

All reports describe downloads for Node.js installation running in CI content.

### Module and version

Not applicable.

**Comment by mcollina** [comment]
You can read more at https://github.com/nodejs/TSC/issues/1416 and https://github.com/nodejs/build/issues/3410.

If you would like to help, there is likely plenty you can do to help fix this problem.

**Comment by shadowspawn** [comment]
Thanks for the links. I'll close this as a known issue.
