### ISSUE TITLE
How SIGURG works for node

### ISSUE THREAD

**Issue by vitalii-buchyn-exa** [nodejs/help#4257]
### Details

Hello community,

We have a case where we use a wrapper for istio (scuttle in our case) https://github.com/kvij/scuttle/issues/13, and i suspect that node may send signals to that wrapper, instead of child process.
I don't know C so i don't understand the code of node. 
Maybe our case is not a case at all.

Please let me know if any additional info is required.

Really appreciate any help/advise.

Thank you!

### Node.js version

{
  node: '16.20.1',
  v8: '9.4.146.26-node.26',
  uv: '1.43.0',
  zlib: '1.2.12',
  brotli: '1.0.9',
  ares: '1.19.1',
  modules: '93',
  nghttp2: '1.46.0',
  napi: '8',
  llhttp: '6.0.11',
  openssl: '1.1.1u',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022f',
  unicode: '14.0'
}

### Example code

scuttle /usr/bin/node --max-http-header-size=16384 dist/packages/scheduler/main.js

### Operating system

GKE, Linux

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
https://nodejs.org/api/os.html 

could not find any. reference to SIGURG related to nodejs apart from the above
