### ISSUE TITLE
Listener function is called when client.emit is called after http2 client is closed

### ISSUE THREAD

**Issue by kivancbilen** [nodejs/help#4259]
### Version

v21.0.0-pre

### Platform

Darwin Kivancs-MacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64

### Subsystem

http2

### What steps will reproduce the bug?

Not sure if it is intended way but when a listener is added to a http2 client, even after client.close is called client.emit() runs the function which was added as listener.

```
'use strict';
const common = require('../common');
if (!common.hasCrypto) common.skip('missing crypto');

const http2 = require('http2');
const tls = require('tls');
const fixtures = require('../common/fixtures');

const serverOptions = {
  key: fixtures.readKey('agent1-key.pem'),
  cert: fixtures.readKey('agent1-cert.pem'),
};

const server = http2.createSecureServer(serverOptions, (req, res) => {
  res.end();
});

server.listen(
  0,
  '127.0.0.1',
  common.mustCall(() => {
    const options = {
      ALPNProtocols: ['h2'],
      host: '127.0.0.1',
      servername: 'localhost',
      port: server.address().port,
      rejectUnauthorized: false,
    };

    const socket = tls.connect(options, async () => {
      socket.once('readable', () => {
        const client = http2.connect(
          'https://localhost:' + server.address().port,
          { ...options, createConnection: () => socket }
        );

        const func1 = function (...args) {
          console.log('Call function', ...args);
        };

        client.addListener('test', func1);

        client.emit('test');
        client.close()
        
        console.log('session is closed');

        client.emit('test');
        server.close()
      });
    });
  })
);
```
output is 
```
Call function
session is closed
Call function
```

### How often does it reproduce? Is there a required condition?

Everytime

### What is the expected behavior? Why is that the expected behavior?

client.emit() should throw error or not run anything

### What do you see instead?

client.emit() calls the listener function

**Comment by mcollina** [comment]
EventEmitter is a leaky abstraction, and everybody can call `emit()` without any knowledge of the internal state.
