### ISSUE TITLE
⨯ node:internal/modules/esm/module_job:124         this.module.instantiate();

### ISSUE THREAD

**Issue by DS-83** [nodejs/help#4265]
### Details

After running  _npm run dev_ get error:

$ npm run dev

> nextjs_app_@0.1.0 dev
> next dev

  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000
  - Environments: .env.local

 ✓ Ready in 5.9s
 ✓ Compiled / in 3s (1916 modules)
 ⨯ node:internal/modules/esm/module_job:124
        this.module.instantiate();
                    ^
Error: request for '@tanstack/query-sync-storage-persister' is not in cache
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5) {
  code: 'ERR_VM_MODULE_LINK_FAILURE',
  page: '/'
}

### Node.js version

v18.18.0

### Operating system

Linux localhost.localdomain 6.5.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep 24 15:52:44 UTC 2023 x86_64 GNU/Linux

### Scope

//package.json
{
  "name": "nextjs_app_",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@web3modal/wagmi": "^3.0.2",
    "axios": "^1.5.1",
    "ethers": "^6.6.1",
    "next": "^13.2.4",
    "node-cache": "^5.1.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "usehooks-ts": "^2.9.1",
    "viem": "^1.13.1",
    "wagmi": "^1.4.2"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build && next export -o build/",
    "start": "next start",
    "lint": "next lint"
  },
  "devDependencies": {
    "typescript": "^5.2.2"
  }
}

Next.js 13.5.4

### Module and version

Not applicable.

**Comment by DS-83** [comment]
Inappropriate repo

**Comment by psteinroe** [comment]
did you fix this?

**Comment by Geczy** [comment]
same issue, whats the fix?

**Comment by chiragmakkar** [comment]
Did anyone find a fix for this?
