### ISSUE TITLE
403 Error calling node.js webservice

### ISSUE THREAD

**Issue by novelist-jsmith** [nodejs/help#4267]
### Details

I have written a web service using node.js (in Javascript).  I have specified a route for my endpoint and have set the application up in IIS.  The URL works on the server where the application exists.  However, when I try to launch the URL from another server, I get a 403 error.

I know what the error means;  I need to know how to give access to the URL from a different resource/server.   I'm connecting via a VPN.
Thanks

### Node.js version

Not applicable.

### Operating system

Windows 11

### Scope

Runtime

### Module and version

Not applicable.

**Comment by Pyrolistical** [comment]
This does not sounds like a nodejs issue.

Also what would be more helpful is the output of a successful and failed call using an http client like [httpie](https://github.com/httpie/cli)
