### ISSUE TITLE
Node JS running on a web server

### ISSUE THREAD

**Issue by Stranner** [nodejs/help#4271]
### What is the problem this feature will solve?

I have no experience with Node js. For a single application I need Node JS functionality. 
I have a working application on a web server that works primarily in PHP. 
Questions: 
Is it possible to upload a copy of Node JS to a web server? 

Annotation: The application is designed to query short-lived access tokens for Firebase messaging

### What is the feature you are proposing to solve the problem?

Annotation: The application is designed to query short-lived access tokens for Firebase messaging
[Link to Firebase](https://firebase.google.com/docs/cloud-messaging/migrate-v1)

### What alternatives have you considered?

is there an application online where I can run Node JS?

_No response_

**Comment by preveen-stack** [comment]
> Is it possible to upload a copy of Node JS to a web server?
https://www.digitalocean.com/community/tutorials/how-to-create-a-web-server-in-node-js-with-the-http-module
google cloud / firebase seems to support nodejs runtime
[pls check https://firebase.google.com/docs/functions/get-started?gen=2nd](https://cloud.google.com/functions/docs/concepts/nodejs-runtime)

**Comment by Stranner** [comment]
Sorry,  preveen-stack there is a misunderstanding.
I don't want to create a web server. 
I want to upload NODE JS to a web server and run commands.

The background is: Firebase provides a short-term authentication key. This is only valid for 1 hour. To retrieve this key, Firebase provides instructions in NODE JS, Java, Python, Go, C#.

**Comment by kshitijsaksena** [comment]
Hi @Stranner
If I understand your question correctly then you want to run the Node.js code given by firebase to retrieve an auth key. If so then one way is to spin up your own node.js server and write this functionality in it. 
If you don't want to manage your own Node.js server then use cloud providers serverless products to just write your code and run it. eg: AWS Lamda or Firebase cloud functions.
I guess you are already using Firebase so it would be good to use cloud function in Firebase. Here's a link to know about cloud functions: [Firebase Cloud Functions](https://www.youtube.com/watch?v=vr0Gfvp5v1A)
