### ISSUE TITLE
node crashes on aix in uvlib when running from java

### ISSUE THREAD

**Issue by Galgc** [nodejs/help#4272]
### Details

First question/bug report:
We have a similar issue as in https://github.com/nodejs/help/issues/4083 but in different circumstances and we are not sure if we misuse node or if its a real bug.

We have a java (IBM Semeru JVM, 17.0.7) program that runs in AIX 7.3, 7300-01-01-2246. 
As part of the program it runs a cli that is written in node and collects the output from the node program
The CLI (node program) issues rest requests to our server using axios library (https requests if that matters)

When we run the CLI outside of the java process, nothing fails, however when running the node program in context of java we get the same exceptions as reported in the issue above.

We assumed its the same error and waited for 18.18, but now looks like the bug moved for us 3 lines down and we get:
Assertion failed: __EX, file  ../deps/uv/src/unix/aix.c, line 189
and a core dump from the node program.

Is there anything special in regards to the way java runs node that we need to be aware or should we just open a bug and someone can try and assist?
We have a running system where we can try things.

### Node.js version

./node -p process.versions
{
  node: '18.18.0',
  acorn: '8.10.0',
  ada: '2.6.0',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '6.0.11',
  modules: '108',
  napi: '9',
  nghttp2: '1.55.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.10+quic',
  simdutf: '3.2.14',
  tz: '2023c',
  undici: '5.22.1',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.18',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13.1-motley'
}

### Operating system

AIX ctxa-li1 3 7 00C734304B00

### Scope

Running code which uses SSL on AIX

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
cc @nodejs/platform-aix
