### ISSUE TITLE
ETIMEDOUT cannot connect to registry on npx create react app

### ISSUE THREAD

**Issue by vovantruong** [nodejs/help#4276]
### Details

I got an error while creating reactjs project, I tried uninstall -g create-react-app and reinstalling but it didn't install

### Node.js version

v18.14.2

### Example code

```console
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/create-react-app failed, reason: connect ETIMEDOUT 2606:4700::6810:1a22:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-10-25T04_11_47_030Z-debug-0.log
```

### Operating system

window 11

### Scope

no response

### Module and version

Not applicable.

**Comment by sayronoliveira** [comment]
I had the same problem! 
I tried to remove proxy config but still receive the same message again.
Also tried update node npm without success!

**Comment by NaseerUllahAwan** [comment]
I have the same issue with vuejs using Windows 11. I have used unpkg cdn for view.

**Comment by RedYetiDev** [comment]
Hi! This seems to be an issue with your network connection (timing out), and not a Node.js issue.
