### ISSUE TITLE
vcbuild ?

### ISSUE THREAD

**Issue by MarcWeber** [nodejs/help#4277]
### Details

I got choco, used the windows Box* install script on 3 machines.

But I cannot find vcbuild. I heard it's in VStudio 2015 or such but the download link on Microsoft was broken.

I want to test the quic implementation thus need to compile from source (?)

Is the problem me ?

### Node.js version

master

### Operating system

x

### Scope

x

### Module and version

Not applicable.

**Comment by MarcWeber** [comment]
lol vcbuild.bat is in the repo and works. My fault.

**Comment by VoltrexKeyva** [comment]
> lol vcbuild.bat is in the repo and works. My fault.

Nice, if this issue is resolved and you no longer need help then consider closing this issue.

**Comment by VoltrexKeyva** [comment]
Closing as resolved.
