### ISSUE TITLE
npm ERR! code E404 when running the "npx creat-react-app primeiro_app" command at the prompt. How to fix it?

### ISSUE THREAD

**Issue by gbsufscar** [nodejs/help#4289]
### Details

I'm using Node.js version v20.9.0, and when I try to run the command `npx creat-react-app primeiro_app` at the prompt, return the error:

```console
> npx crate-react-app primeiro_app
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/crate-react-app - Not found
npm ERR! 404
npm ERR! 404  'crate-react-app@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
[2023-11-08T09_27_12_240Z-debug-0.log](https://github.com/nodejs/help/files/13294845/2023-11-08T09_27_12_240Z-debug-0.log)
[2023-11-08T09_27_12_240Z-debug-0.log](https://github.com/nodejs/help/files/13294853/2023-11-08T09_27_12_240Z-debug-0.log)
npm ERR! A complete log of this run can be found in: C:\Users\gbsuf\AppData\Local\npm-cache\_logs\2023-11-08T09_27_12_240Z-debug-0.log
[2023-11-08T09_27_12_240Z-debug-0.log](https://github.com/nodejs/help/files/13294908/2023-11-08T09_27_12_240Z-debug-0.log)
[2023-11-08T09_27_12_240Z-debug-0.log](https://github.com/nodejs/help/files/13294910/2023-11-08T09_27_12_240Z-debug-0.log)
```

### Node.js version

Node.js version v20.9.0, 

### Example code

`npx creat-react-app primeiro_app`

### Operating system

Windows

### Scope

Other

### Module and version

Not applicable.

**Comment by VoltrexKeyva** [comment]
> `npx crate-react-app primeiro_app`

It's `create-react-app`, not `crate-react-app`.

**Comment by harshai07** [comment]
yah its' create-react app for npx

**Comment by harshai07** [comment]
> > `npx crate-react-app primeiro_app`
> 
> It's `create-react-app`, not `crate-react-app`.

npx create-react-app  appname 
this is correct one you need give the react app name

**Comment by udaybagda** [comment]
Use proper command for create project.
use npx create-react-app your application name

**Comment by MaheshBScCs** [comment]
Write command for create project.
npx create-react-app your project name

**Comment by ousey-ousey** [comment]
just type -error

**Comment by basma411** [comment]
C:\Users\asus>npx create-react-app your project name
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-react-app
npm ERR! 404
npm ERR! 404  'create-react-app@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: C:\Users\asus\AppData\Local\npm-cache\_logs\2024-03-18T01_18_48_574Z-debug-0.log

**Comment by ammoriddin** [comment]
I was installing million first of all i write the code in my git bash npm i million it installed but then i was installing this npm install --save-dev @million/babel-plugin but it didn't work so return me this:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@million%2fbabel-plugin - Not found
npm ERR! 404 
npm ERR! 404  '@million/babel-plugin@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CyberAcademy.uz\AppData\Local\npm-cache\_logs\2024-03-31T11_51_56_715Z-debug-0.log

what can i do

**Comment by VoltrexKeyva** [comment]
@ammoriddin `@million/babel-plugin` does not exist, if you go to the [registry page](https://registry.npmjs.org/@million%2fbabel-plugin) you'll see that it's not found, find the correct package you're trying to install.

**Comment by RedYetiDev** [comment]
The issues regarding typos (and such) appear to be resolved. If you have further issues, please open a new issue.

**Comment by Techgirlie-martinermars** [comment]
errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'C:\\Users\\MARS\\Downloads\\weather-search-engine',
  dest: 'C:\\Users\\MARS\\Downloads\\weather-search-engine\\weather-search-engine.'
}

Node.js v20.16.0
PS C:\Users\MARS\Downloads\weather-search-engine>

**Comment by myselfsandip** [comment]
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/axios - Not found
npm error 404
npm error 404  'axios@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: C:\Users\singh\AppData\Local\npm-cache\_logs\2024-12-08T18_42_10_135Z-debug-0.log

**Comment by Qurbonov** [comment]
same problem 
npm error 404 Not Found - GET https://registry.npmjs.org/create-next-app - Not found

**Comment by Qurbonov** [comment]
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/create-next-app - Not found
npm error 404
npm error 404  'create-next-app@latest' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: C:\Users\Asus\AppData\Local\npm-cache\_logs\2024-12-08T18_44_46_653Z-debug-0.log

**Comment by LOVE-GARG-19** [comment]
I got exact same error when I install react router dom 
Command : npm I react-router-dom

**Comment by BlezZy** [comment]
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/create-next-app - Not found
npm error 404
npm error 404  'create-next-app@latest' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: C:\Users\kubaf\AppData\Local\npm-cache\_logs\2024-12-08T18_44_12_346Z-debug-0.log

**Comment by willFreed1** [comment]
so basically it's a global issue

**Comment by EsleySaab** [comment]
same problem

**Comment by Feyedyassine** [comment]
same issue

**Comment by yx-elite** [comment]
I have same issues too

npx shadcn@latest init --legacy-peer-deps
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/shadcn - Not found
npm error 404
npm error 404  'shadcn@latest' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: C:\Users\user\AppData\Local\npm-cache\_logs\2024-12-08T18_48_42_415Z-debug-0.log

**Comment by not-ani** [comment]
https://x.com/npmstatus/status/1865098995296796973

I think npm is down for maintenance

**Comment by LOVE-GARG-19** [comment]
Hello guys may be npm down write now

**Comment by willFreed1** [comment]
ping registry.npmjs.org
the ping is working but it must be a maintenance or an error with the npm registry

**Comment by msobalvarro** [comment]
Same issue

<img width="1003" alt="Captura de Pantalla 2024-12-08 a la(s) 12 54 56" src="https://github.com/user-attachments/assets/efcdc1cd-431b-4246-8675-9761f0883524">

**Comment by Mochamad-Rizky** [comment]
Yaaa same issue

**Comment by Mochamad-Rizky** [comment]
<img width="1679" alt="image" src="https://github.com/user-attachments/assets/a2c45286-024b-437b-828f-506107d25a9d">

**Comment by AmirDavoodi** [comment]
Yaaa!!! 
Same here from Iran.

**Comment by msobalvarro** [comment]
Npm is down

**Comment by realHex** [comment]
guys i have angular project to submit in 2 days and I cant install npm.

**Comment by LOVE-GARG-19** [comment]
I am from India

**Comment by Acherbib** [comment]
Same
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/expo - Not found
npm ERR! 404

**Comment by dagm4020** [comment]
npm has a scheduled maintenance apparently: https://status.npmjs.org/

**Comment by yashvchavan** [comment]
same npm error 404
i am from INDIA

**Comment by mwheeler2244** [comment]
Same issues in USA

**Comment by curl-kawsar** [comment]
I was facing this problem also.
And after checking the npm site, its under maintainance

npm has a scheduled maintenance apparently: https://status.npmjs.org/

**Comment by h-chayma** [comment]
its working now haha ! 🎉

**Comment by yashvchavan** [comment]
its working now...

**Comment by francoisamisse** [comment]
works again!

**Comment by WazDevZm** [comment]
working here in Zambia!

**Comment by Domi83s** [comment]
> ### Details
> I'm using Node.js version v20.9.0, and when I try to run the command `npx creat-react-app primeiro_app` at the prompt, return the error:
> 
> ```
> > npx crate-react-app primeiro_app
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/crate-react-app - Not found
> npm ERR! 404
> npm ERR! 404  'crate-react-app@*' is not in this registry.
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> [2023-11-08T09_27_12_240Z-debug-0.log](https://github.com/nodejs/help/files/13294845/2023-11-08T09_27_12_240Z-debug-0.log)
> [2023-11-08T09_27_12_240Z-debug-0.log](https://github.com/nodejs/help/files/13294853/2023-11-08T09_27_12_240Z-debug-0.log)
> npm ERR! A complete log of this run can be found in: C:\Users\gbsuf\AppData\Local\npm-cache\_logs\2023-11-08T09_27_12_240Z-debug-0.log
> [2023-11-08T09_27_12_240Z-debug-0.log](https://github.com/nodejs/help/files/13294908/2023-11-08T09_27_12_240Z-debug-0.log)
> [2023-11-08T09_27_12_240Z-debug-0.log](https://github.com/nodejs/help/files/13294910/2023-11-08T09_27_12_240Z-debug-0.log)
> ```
> 
> ### Node.js version
> Node.js version v20.9.0,
> 
> ### Example code
> `npx creat-react-app primeiro_app`
> 
> ### Operating system
> Windows
> 
> ### Scope
> Other
> 
> ### Module and version
> Not applicable.

https://github.com/nodejs/help/issues/4289#issue-1983169911

**Comment by yx-elite** [comment]
Why is my npm not working again? Is it only my issue?

**Comment by Mykiechen88** [comment]
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/creat-react-app - Not found
npm error 404
npm error 404  'creat-react-app@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/mykiechen/.npm/_logs/2024-12-18T15_39_07_091Z-debug-0.log
How to resolve it
