### ISSUE TITLE
An Error while install Node.js in Termux

### ISSUE THREAD

**Issue by jfjstt** [nodejs/help#4294]
### Details

 I entered pkg install nodejs to install Node.js, but an error occurred.I tried apt upgrade,pkg upgrade as well.

### Node.js version

Not applicable.

### Example code

~ $ pkg install nodejs
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://packages.termux.org/apt/termux-main/: ok
Hit:1 https://packages.termux.dev/apt/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (20.2.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up nodejs (20.2.0) ...
CANNOT LINK EXECUTABLE "node": library "libicui18n.so.73" not found: needed by main executable
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

### Operating system

Termux

### Scope

Installation

### Module and version

Not applicable.

**Comment by ucdevinda123** [comment]
@jfjstt Do you mind sharing the fix?
