### ISSUE TITLE
Fatal Error V8 Array Buffer NewBackingStore Allocatation failed - process out of memory

### ISSUE THREAD

**Issue by SandeepReddyPinniti** [nodejs/help#4299]
### Details

We are encountering process out of memory error when running twilio flex:plugins:deploy command to deploy the plugin code. I have reached out to Twilio team and they have mentioned that is a node.js error. I have increased the memory size of node by configuring this in the windows environment variable. Node version on my machine is v16.20.0

node --max-old-space-size=1024

I have attached the error message too, Please let us know on how to resolve the issue?

Thanks in advance

![image](https://github.com/nodejs/help/assets/2034469/157d656f-f941-429a-bf51-88b39bc1aaa1)

> 

### Node.js version

v16.20.0

### Example code

twilio flex:plugins:deploy

### Operating system

Windows 10

### Scope

Deploying Twilio Flex Plugin

### Module and version

Not applicable.

**Comment by ljharb** [comment]
node 16 is EOL, and either way, if you're getting an out of memory error, either you need to fix your program so it doesn't leak memory, or, you need to increase the max-old-space-size even higher.

**Comment by SandeepReddyPinniti** [comment]
I'm encountering the same error with node 18 version too and increased the max-old-space-size to 4GB using an environment variable on a windows machine but no luck.

**Comment by fabiantorress** [comment]
@SandeepReddyPinniti hi, how did you solve your problem? I'm encountering the same error.
