### ISSUE TITLE
nodejs, expressjs, mongodb and angularjs

### ISSUE THREAD

**Issue by joanavives** [nodejs/help#430]
I want to use these tools in my company and i would like to know if they are free licensed and which limits of warrants to use in my company and if i can use with free or how much it costs.

i refer to use these tools in software to be sold.

thanks, joana

**Comment by lordKnighton** [comment]
node - https://raw.githubusercontent.com/nodejs/node/master/LICENSE
expressjs - https://creativecommons.org/licenses/by-sa/3.0/us/
mongodb - https://github.com/mongodb/mongo - bottom of readme 
angularjs  - https://github.com/angular/angular.js/blob/master/LICENSE  

These were very easy to find, just google or bing it. 
-----

if you need more help, let me know.

**Comment by joanavives** [comment]
i continue with the same doubts... if it is able to use these tools in my company with no problems????

Thanks a lot.... joana

**Comment by gibfahn** [comment]
@joanavives You can continue to comment on this issue even though it's closed, you don't need to raise a new issue. https://github.com/nodejs/help/issues/433

**Comment by vdeturckheim** [comment]
@joanavives it depends your company policies and I am no lawyer. 
However AFAIK, there is nothing that prevents you from using Node.js in your company. As for Express, I think it is alright too.

Regarding MongoDB and Angular, you better ask in their respective communities as these two projects are not linked to Node.js.

But anyway, if you explained what your doubts were, it would be easier to answer your question.

**Comment by lordKnighton** [comment]
if your still in doubt, playing it safe. I can try to ping a core developer from each of those communities here. but I'm sure there busy. if you want it's worth a shot. how do you wish to proceed?

**Comment by bnoordhuis** [comment]
The only right answer is that you should consult your company's legal department.  You know what licenses the software ships with.  Whether those are acceptable to your company is not for a public forum to answer.
