### ISSUE TITLE
When will Docker image for the latest LTS be available?

### ISSUE THREAD

**Issue by sharifsheraz** [nodejs/help#4300]
### Details

Currenlty, [node:lts-bullseye](https://hub.docker.com/layers/library/node/lts-bullseye/images/sha256-8056d2a3ec2c6f5a02e06c31d92745e52bf9be3b822e155e7c562c86588a6977?context=explore) Docker image is currently pointing to version 20.9. I'm eager to know when we can expect an update to version 20.10 for lts-bullseye.

### Node.js version

20.10.0

### Operating system

linux

### Scope

installation

### Module and version

Not applicable.

**Comment by bmuenzenmeyer** [comment]
it's a separate process across a couple other repos - it takes a day or two
