### ISSUE TITLE
[Question]: How to emulate a true .exit() command in browser?

### ISSUE THREAD

**Issue by MarketingPip** [nodejs/help#4301]
### Details

I am almost positive this in impossible unless using a web worker, but is there any way we can "stop" code including any / all awaiting promises. 

Similar to command line exit / terminated process? 

### Node.js version

Not applicable.

### Operating system

Any.

### Scope

Question.

### Module and version

Not applicable.

**Comment by ljharb** [comment]
This isn’t a node question, it’s a browser one - and no, in a browser there’s no way to do anything but throw an exception or navigate to another page, afaik.

**Comment by MarketingPip** [comment]
> This isn’t a node question, it’s a browser one - and no, in a browser there’s no way to do anything but throw an exception or navigate to another page, afaik.

My apologizies if wrong area. Just figured I might have some luck finding something that I do not know about. Not sure how to cancel ANY all awaiting processes.

**Comment by ljharb** [comment]
Again, in the browser, I'm pretty sure you can't unless you navigate the page elsewhere.

This should be closed, and if you have further questions you'd probably want to ask in WhatWG forums.

**Comment by MarketingPip** [comment]
@ljharb I know this is browser based but I do think this will be a Node.JS solution. 

Possibly web containers etc.... ie; Node.js solution for this possibly.

Hence hoping for some other input or maybe other alternatives.

**Comment by ljharb** [comment]
It would be impossible for node to provide browsers a capability like that they they do not have. I’m afraid you’re out of luck.

**Comment by MarketingPip** [comment]
Again @ljharb - I think you should look at web containers. I think I am barking up the right tree.

**Comment by ljharb** [comment]
That might let you exit the container, but wouldn’t ever affect the main thread, and again, wouldn’t involve node at all.
