### ISSUE TITLE
strapi cms keeps on crashing when developing on localhost with a node js internal error

### ISSUE THREAD

**Issue by AkshayVerma-Ipsator** [nodejs/help#4304]
### Details
```
node:internal/assert:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at new NodeError (node:internal/errors:405:5)
    at assert (node:internal/assert:14:11)
    at internalConnectMultiple (node:net:1118:3)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_INTERNAL_ASSERTION'
}
```
Node.js v20.6.1

### Node.js version

v20.6.1

### Operating system

Windows 

### Scope

runtime

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
@nodejs/core PTAL

**Comment by ronag** [comment]
@ShogunPanda

**Comment by GeoffreyBooth** [comment]
A stack trace isn't enough. Please provide steps too reproduce.

**Comment by AkshayVerma-Ipsator** [comment]
npx create-strapi-app@latest my-project
# 'npx' runs a command from an npm package
# 'create-strapi-app' is the Strapi package
# '@latest' indicates that the latest version of Strapi is used
# 'my-project' is the name of your Strapi project

install the strapi project then run 
npm run develop

I was doing migration of data from wordpress headless cms to strapi headless cms and for that I developed a code which fetches the data from wordpress and post the data to strapi.
it may run for a while smoothly if not fetching anything but after doing continous 50-60 crud operation like post from the scripts it crashes in between only.

**Comment by GeoffreyBooth** [comment]
```
docker run -it node:20 bash
npx create-strapi-app@latest my-project
Need to install the following packages:
create-strapi-app@4.15.5
Ok to proceed? (y)
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /my-project.
Creating files.
Dependencies installed successfully.
Initialized a git repository.


Your application was created at /my-project.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /my-project
  yarn develop

Running your Strapi application.

> my-project@0.1.0 develop
> strapi develop

⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (118ms)
⠸ Creating adminSegmentation fault
```

This could be a bug in Strapi. I suggest you open an issue with them. For Node to resolve this, we’ll need a minimal reproduction that can demonstrate the issue without dependencies.

**Comment by cclauss** [comment]
Let's open an issue on https://github.com/strapi/strapi/issues because they have already seen this issue twice https://github.com/nodejs/help/issues/4304#issuecomment-1831936744

**Comment by tniessen** [comment]
This is a known bug in the implementation of Happy Eyeballs. There are tons of issues about this in the main repository.

**Comment by icebearlabs** [comment]
Narrator Voice: "He didn't tackle it on Monday."
