### ISSUE TITLE
nodejs issue on mac El capitan

### ISSUE THREAD

**Issue by jariwbh** [nodejs/help#431]
Hi,

We have MEAN stack application running on linux and windows machine. We try to install app on new Mac El capitan machine today and got this error.

var treeAdapter = parse5.treeAdapters.htmlparser2;
                                     ^
TypeError: Cannot read property 'htmlparser2' of undefined

Its running on other Mac machine (not El capitan).

Regards,

**Comment by vsemozhetbyt** [comment]
If nobody can help you here, try also to post the issue in the [parse5 repository](https://github.com/inikulin/parse5).

**Comment by maasencioh** [comment]
Hi @jariwbh, are you allowed to show more of that code?

**Comment by SomeoneWeird** [comment]
If your `parse5` object is indeed them module that @vsemozhetbyt referred to, you probably have a different version of it installed between your installations.
