### ISSUE TITLE
Could not find the sentinel NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 in the binary

### ISSUE THREAD

**Issue by Drjacky** [nodejs/help#4313]
### Details

I followed these steps https://nodejs.org/api/single-executable-applications.html
When I run
```bash
npx postject hello NODE_SEA_BLOB sea-prep.blob \
    --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 \
    --macho-segment-name NODE_SEA 
```
I get:
```bash
Error: Could not find the sentinel NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 in the binary
```

### Node.js version

21.3.0

### Operating system

macOS

### Scope

Compile time

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
cc @RaisinTen can you advise

**Comment by YunusCorum** [comment]
why nobody doesn't care about the issue ?

**Comment by Drjacky** [comment]
@preveen-stack @YunusCorum I used this archived https://github.com/vercel/pkg and it worked.

**Comment by chengB12** [comment]
My issue is "Error: Multiple occurences of sentinel "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2" found in the binary"

for macos and node v20.10.0

**Comment by yisar** [comment]
node v21 still keep this error

**Comment by HxShard** [comment]
stuck with this running v20.11.0 on darwin, eventually switched to v20.0.0 (https://nodejs.org/dist/v20.0.0/node-v20.0.0-darwin-x64.tar.gz and https://nodejs.org/dist/v20.0.0/node-v20.0.0-darwin-arm64.tar.gz) and it seems to be working.

**Comment by HxShard** [comment]
probably it wasn't quite right because I obtained that node's binary from a ".pkg"-distributed version

**Comment by nokazn** [comment]
when I use [moonrepo/proto](https://github.com/moonrepo/proto) to install node, I needed to run

```sh
cp $(proto bin node) hello
```

instead of

```sh
cp $(command -v node) hello
```

in step 4 of [the guide](https://nodejs.org/api/single-executable-applications.html#single-executable-applications).

Related: https://github.com/volta-cli/volta/issues/1594

**Comment by ratatoeskr666** [comment]
> My issue is "Error: Multiple occurences of sentinel "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2" found in the binary"
> 
> for macos and node v20.10.0 (and v20.11.0 LTS too)

Same issue for me. It worked a couple of times but now I receive this issue. (Node 20.14.0)

**Comment by RedYetiDev** [comment]
The original author of this issue seems to have resolved their problem, if you are still experiencing an issue, I invite you to open a new issue.

Thank you!

**Comment by Drjacky** [comment]
> The original author of this issue seems to have resolved their problem, if you are still experiencing an issue, I invite you to open a new issue.
> 
> Thank you!

Yup, that error is gone but still, it doesn't work:
> Start injection of NODE_SEA_BLOB in hello...
Error: Can't read and write to target executable

**Comment by RedYetiDev** [comment]
If you are experiencing a different issue, please open a new issue, as that makes tracking easier.

Thank you!

**Comment by evaporei** [comment]
I'm experiencing this issue in Node 25.9.0

index.js
```js
console.log('test')
```

sea-config.json
```json
{
    "main": "index.js",
    "output": "sea"
}
```

Output:

```shell
$ node --build-sea sea-config.json
Error: sentinel NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 not found
```

I'm in MacOS 15.7.1 (Sequoia) M3 Pro, with Node.js installed directly via Homebrew.
