### ISSUE TITLE
Error while making httpsAgent call using pfx certificate and Axios

### ISSUE THREAD

**Issue by sidhartha31** [nodejs/help#4315]
### Details

I tried to use Axios with an https.Agent with pfx configuration but I get the below error message:

`Error: unsupported`

I checked https://github.com/axios/axios/issues/4778 and I applied the fix but it still didn't work. After that, I added a .npmrc file and by adding the node-options parameter there, it started working. The line that was added is:

`node-options="--openssl-legacy-provider"`

Can you please inform in which version of Node 18.x can I use my current setup without making use of .npmrc file? It won't be possible for me to downgrade the Node version. And if I have to use the .npmrc file, does it introduce any security threat?

### Node.js version

18.8.2

### Example code

```js
const configuredHttpsAgent = new https.Agent({
  pfx: KEYFILE_CONTENT,
  passphrase: PASSPHRASE
});

const config = {
    method: 'post',
    url,
    headers,
    data: body,
    httpsAgent: configuredHttpsAgent
  };
  axios(config)
    .then((response) => {
      // successfully sent notification
    })
    .catch((error) => {
      req.logger.error("${error}");
    });
```

### Operating system

Linux

### Scope

Runtime

### Module and version

Not applicable.

**Comment by camilo-pinheiro** [comment]
Try to use node 16

**Comment by RedYetiDev** [comment]
Hi! If you need support with a third-party library, like Axios, please refer to their issue trackers. If you are able to reproduce with only Node.js components. Please open a new issue.

Thank you!
