### ISSUE TITLE
Supporting OpenSSL custom provider

### ISSUE THREAD

**Issue by Seulhui** [nodejs/help#4318]
### Details

Hello,
Since after OpenSSL 3.x releases, it is recommended to use provider instead of engine because of the deprecation of engine API by OpenSSL.
node.js already moved to OpenSSL 3.x version, but it still doesn't have a feature supporting provider. 
There are some features for FIPS or legacy providers, but there is no way to set custom provider. (It could be an API such as "setProvider").
Is there anyone who knows about it?

Regards,
Seulhui Lee.

### Node.js version

Current

### Operating system

ubuntu 20.04

### Scope

code

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Hi! If you still see a future for this feature in Node.js, and you can provide detailled use cases, please open an issue in `nodejs/node`. Otherwise, feel-free to self-close.
