### ISSUE TITLE
Typo in node.js installation command

### ISSUE THREAD

**Issue by kebetsi** [nodejs/help#4319]
### Details

On the [How to install Node.js via binary archive on Linux?](https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux) wiki page, the path of the extracted Node.js runtime folder is missing a "v". 
I have provided a PR with the fix in "Example code"

### Node.js version

Not applicable.

### Example code

https://github.com/kebetsi/nodejs-help-wiki/pull/1/files

### Operating system

Linux

### Scope

Installation docs

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Thanks for the issue! I'd suggest that you open a PR against the affected repository instead of opening an issue with this one.
