### ISSUE TITLE
Node-crypto for the browser

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/help#432]
I am trying to get a client-side encryption :closed_lock_with_key:  library up and running that works both when Node is a client as well as when the browser is a client.

Unfortunately if I use `browserify` it will use [`crypto-browserify`](https://github.com/crypto-browserify/crypto-browserify) which quickly bloats my tiny library to render it cumbersome to load :steam_locomotive: _(like 250k or so minified for the crypto `require` statement)_. I would like this to be faster :bullettrain_side: .

I can imagine one of three solutions for this:

1. Extend the Node.js's crypto API _(send a PR)_ to be more modular in order to be able to decouple all the ciphers:
    ```javascript
    var createCipher = require('crypto/createCipher')(require('crypto/cipher/aes256'), ...)
    ```
    this way I would only need to bundle the ciphers that I need.
2. Have an "abstraction"-layer library that works pretty much like the API above except that its not in Node.js and that it falls back on the Node.js implementation. _(Does this exist? :thinking: )_
3. Use a crypto-subset library with a browser implementation. _(Have they been tested? :boom: )_

How do you approach crypto through npm on the browser?
What are good libraries?
Have there been approaches to make this better in the Node API?

**Comment by karlpokus** [comment]
What's the use case? If you don't mind me asking.

**Comment by martinheidegger** [comment]
@karlpokus My client would like to have a symmetrically encrypted _(where the key is not shared over the net; offline handshake)_ connection on top of https. It is for service accounts where they want to avoid man-in-the-middle attacks.

**Comment by karlpokus** [comment]
Makes sense. I'd go for #1 if that's an option.
