### ISSUE TITLE
Javascript import not working with npm installed package

### ISSUE THREAD

**Issue by Arno-62** [nodejs/help#4320]
### Details

I have installed 3 packages using npm and everything appears to be OK (node_modules directory, package.json, package-lock.json). However, when I use the "import" command in a javascript code given below, it does not work. If I un-comment any of the three "import" commands, the code does not work (I do not get the alert message).

### Node.js version

v20.5.1

### Example code

<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Test</title>

	</head>
	
	<body>
		
		<br>

		<p id="temp">This far. </p>
		
		
		

		
		
		<script>
			//import { Chart } from 'chart';
			//import 'chartjs-adapter-date-fns';
			import 'date-fns';
			alert('Got this far');

			
		</script>

		<br>
		<br>

	</body>
</html>

### Operating system

Ubuntu 22.04

### Scope

Runtime problem due to problem with package installation.

### Module and version

npm version10.2.5

**Comment by ljharb** [comment]
That’s because to run code in a browser, you need to use a bundler (or be using import maps and only native ESM that only uses universal features).

Webpack is a common one; you can google for tutorials.

**Comment by Arno-62** [comment]
Thanks for your rapid feedback. I will look into Webpack.
