### ISSUE TITLE
Node v21 build fails on Windows ARM64 Debug

### ISSUE THREAD

**Issue by lparam-max** [nodejs/help#4323]
### Details

Node v21 build fails on **Windows arm64 Debug** while the other build options, x64 Debug and Release as well as arm64 Release, are working fine.
I have tested the builds with VS2022 17.6.0 and 17.7.7 with all individual build tools, not only v143 but also v141 and v142, and Windows SDKs installed referring to https://github.com/nodejs/node/blob/main/BUILDING.md#windows
But, the builds resulted in failures with the following error:

**Command** in Git Bash with VS2022 17.7.7:
> $ ./vcbuild.bat
> Python 3.10.4
> Looking for Visual Studio 2022
> calling: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\\Auxiliary\Build\vcvarsall.bat" amd64_arm64
> **********************************************************************
> ** Visual Studio 2022 Developer Command Prompt v17.7.7
> ** Copyright (c) 2022 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x64_arm64'
> Found MSVS version 17.0
> configure  --debug --dest-cpu=arm64

**Result**
>    Creating library ..\..\out\Debug\mksnapshot_host.lib and object ..\..\out\Debug\mksnapshot_host.exp
>   mksnapshot_host.vcxproj -> ..\..\out\Debug\\mksnapshot_host.exe
>   generating: "..\..\out\Debug\obj\v8_snapshot\/snapshot.cc" "..\..\out\Debug\obj\v8_snapshot\/embedded.S"
>   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\vector(199) : Assertion failed: vector iterators incoible
> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: Custom build '..\..\out\Debug\\mksnapshot_host.exe' exited with code -1073740791. [C:\dev\node\tools\v8_gypfiles\v8_snapshot.vcxproj]

It seems the build failure occurred due to an error in v8, and I attempted to find the reason but couldn't find a suitable answer. 

I'm curious if there are such issues with building Node for Windows ARM64 debug using the v8 in Node v21.
If there's anything I might have missed or done wrong in the process of building Node v21, please, advise me.

Fyi, I have tried to build Node v21 with the latest VS2022, 17.8.3, but it failed at an earlier stage in ICU across all Windows builds.

### Node.js version

Node v21.0.0 and v21.5.0

### Operating system

Windows 10 Pro 22H2 19045.3803

### Scope

Build

**Comment by RedYetiDev** [comment]
Hi! Is this issue still occurring?
