### ISSUE TITLE
I want to Install CodeCompanionAI from Github but I get an error

### ISSUE THREAD

**Issue by PierrunoYT** [nodejs/help#4328]
### Details

C:\Users\pierr\Desktop\Github\code-companion-original>npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated classifier@0.1.0: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated electron-notarize@1.2.2: Please use @electron/notarize moving forward.  There is no API change, just a package name change
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

> CodeCompanion@5.20.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=23.6.0
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=canvas@2.11.2, node-pty@1.0.0 platform=win32 arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas
    npm ERR! command failed
    npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --update-binary
    npm ERR! Warning: Missing input files:
    npm ERR! C:\GTK\bin\libcairo-2.dll
    npm ERR! C:\GTK\bin\libglib-2.0-0.dll
    npm ERR! C:\GTK\bin\libfontconfig-1.dll
    npm ERR! C:\GTK\bin\libpng14-14.dll
    npm ERR! C:\GTK\bin\libpangowin32-1.0-0.dll
    npm ERR! C:\GTK\bin\libgobject-2.0-0.dll
    npm ERR! C:\GTK\bin\libfreetype-6.dll
    npm ERR! C:\GTK\bin\libexpat-1.dll
    npm ERR! C:\GTK\bin\zlib1.dll
    npm ERR! C:\GTK\bin\libpango-1.0-0.dll
    npm ERR! C:\GTK\bin\libintl-8.dll
    npm ERR! C:\GTK\bin\libgmodule-2.0-0.dll
    npm ERR! C:\GTK\bin\libpangocairo-1.0-0.dll
    npm ERR! C:\GTK\bin\libgthread-2.0-0.dll
    npm ERR! C:\GTK\bin\libpangoft2-1.0-0.dll
    npm ERR! Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm glichen, m ssen Sie den Schalter "/m" hinzuf gen.
    npm ERR!   Backend.cc
    npm ERR! c:\users\pierr\desktop\github\code-companion-original\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Datei (Include) kann nicht ge ffnet werden: "cairo.h": No such file or directory [C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\pierr\AppData\Roaming\nvm\v18.5.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --update-binary --module=C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v25.9' (1)
    npm ERR! node-pre-gyp info it worked if it ends with ok
    npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
    npm ERR! node-pre-gyp info using node@18.5.0 | win32 | x64
    npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v25.9-win32-unknown-x64.tar.gz
    npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v25.9-win32-unknown-x64.tar.gz
    npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and electron@25.9.8 (electron-v25.9 ABI, unknown) (falling back to source compile with node-gyp)
    npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v25.9-win32-unknown-x64.tar.gz
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@18.5.0 | win32 | x64
    npm ERR! gyp info ok
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@18.5.0 | win32 | x64
    npm ERR! gyp info find Python using Python version 3.11.7 found at "C:\Users\pierr\AppData\Local\Programs\Python\Python311\python.exe"
    npm ERR! gyp info find VS using VS2017 (15.9.34407.156) found at:
    npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
    npm ERR! gyp info find VS run with --verbose for detailed information
    npm ERR! gyp info spawn C:\Users\pierr\AppData\Local\Programs\Python\Python311\python.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'C:\\Users\\pierr\\AppData\\Roaming\\nvm\\v18.5.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'msvs',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\pierr\\Desktop\\Github\\code-companion-original\\node_modules\\canvas\\build\\config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\pierr\\AppData\\Roaming\\nvm\\v18.5.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\pierr\\.electron-gyp\\25.9.8\\include\\node\\common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\pierr\\.electron-gyp\\25.9.8',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\pierr\\AppData\\Roaming\\nvm\\v18.5.0\\node_modules\\npm\\node_modules\\node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\pierr\\\\.electron-gyp\\\\25.9.8\\\\<(target_arch)\\\\node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\pierr\\Desktop\\Github\\code-companion-original\\node_modules\\canvas',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'C:\\Users\\pierr\\Desktop\\Github\\code-companion-original\\node_modules\\canvas\\build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info ok
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@18.5.0 | win32 | x64
    npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'build/binding.sln',
    npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
    npm ERR! gyp info spawn args   '/nologo',
    npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp ERR! build error
    npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\pierr\AppData\Roaming\nvm\v18.5.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
    npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Windows_NT 10.0.22631
    npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pierr\\AppData\\Roaming\\nvm\\v18.5.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=C:\\Users\\pierr\\Desktop\\Github\\code-companion-original\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\pierr\\Desktop\\Github\\code-companion-original\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v25.9"
    npm ERR! gyp ERR! cwd C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas
    npm ERR! gyp ERR! node -v v18.5.0
    npm ERR! gyp ERR! node-gyp -v v9.0.0
    npm ERR! gyp ERR! not ok
    npm ERR! node-pre-gyp ERR! build error
    npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\pierr\AppData\Roaming\nvm\v18.5.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --update-binary --module=C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v25.9' (1)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
    npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22631
    npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pierr\\Desktop\\Github\\code-companion-original\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
    npm ERR! node-pre-gyp ERR! cwd C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas
    npm ERR! node-pre-gyp ERR! node -v v18.5.0
    npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
    npm ERR! node-pre-gyp ERR! not ok

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\pierr\AppData\Local\npm-cache\_logs\2024-01-16T13_16_02_839Z-debug-0.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\pierr\AppData\Roaming\nvm\v18.5.0\node_modules\npm\bin\npm-cli.js' rebuild canvas@2.11.2 node-pty@1.0.0
                    workingDir=
npm ERR! code 1
npm ERR! path C:\Users\pierr\Desktop\Github\code-companion-original
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c electron-builder install-app-deps

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pierr\AppData\Local\npm-cache\_logs\2024-01-16T13_14_50_446Z-debug-0.log

### Node.js version

I changed it to 18.5.0

### Operating system

Windows 11

### Scope

Im not sure

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
> npm ERR! Backend.cc
npm ERR! c:\users\pierr\desktop\github\code-companion-original\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Datei (Include) kann nicht ge ffnet werden: "cairo.h": No such file or directory [C:\Users\pierr\Desktop\Github\code-companion-original\node_modules\canvas\build\canvas.vcxproj]

Looks like some include files are missing or include path needs to be configured

**Comment by RedYetiDev** [comment]
As it currently stands, your issue may be poorly formatted, and difficult for members of the community to understand.
