### ISSUE TITLE
erroe installing react

### ISSUE THREAD

**Issue by noblez-90z** [nodejs/help#4331]
### Details

```console
> npx create-react-app first-project
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path C:\Users\dj waterside\AppData\Roaming\npm
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\dj waterside\AppData\Roaming\npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\dj waterside\AppData\Local\npm-cache\_logs\2024-01-20T06_09_40_398Z-deb0T06_09_40_398Z-debug-0.log
>
```

### Node.js version

version 20.5.1

### Operating system

windows

### Scope

installation

### Module and version

Not applicable.

**Comment by mwelwankuta** [comment]
Hello @noblez-90z, running the below command will create the npm directory which currently doesn't exist. 
```bash 
npm install npm -g
```
as an alternative you can manually create the folder.
```bash
mkdir 'C:\Users\dj waterside\AppData\Roaming\npm'
```

i hope this works for you

**Comment by RedYetiDev** [comment]
@noblez-90z did the suggested answer work?

Also, make sure that you are downloading the latest version of React/Node.js/NPM, etc

**Comment by noblez-90z** [comment]
Thank you for your reply it is working now
