### ISSUE TITLE
How to debug node.js

### ISSUE THREAD

**Issue by absolutebeg** [nodejs/help#4332]
### Details

I am trying to contribute to Node.js development.

I have picked up an issue in the tracker, but don't know how to investigate. And I could not add traces to the C++ module that has the issue.

Is there any place where I could find basic information about the way to debug Node.js (trace, log, debugger)?

The way I tried to add traces:

```cpp
#include <iostream>
//(...)
std::cout << value;
```

But the trace does not show. I have a Windows system and run Node.js from Git Bash with command: `winpty node`.

Is there something I miss to be able to use `iostream` in my configuration?

### Node.js version

v22.0.0-pre

### Operating system

Windows 11

### Scope

code

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
I'm not sure I follow the concern. Are you trying to use the Node.js `NODE-API`?
