### ISSUE TITLE
Node v18.19.0 - npm: command not found

### ISSUE THREAD

**Issue by HelpAroundUser** [nodejs/help#4334]
Hello, I have an issue with npm. 
I have used [this](https://deb.nodesource.com/) approach to install Node 18  inside the docker image. Image based on php:8.2-fpm. 
The image was successfully built and I see inside the Node version:
<img width="303" alt="image" src="https://github.com/nodejs/Release/assets/95231155/23ecd040-f249-4c02-972e-ee954272c7fa">

But when I tried to check the npm version I saw the message:
<img width="309" alt="image" src="https://github.com/nodejs/Release/assets/95231155/9c812ce3-65f5-4e55-9f1c-15eba3c9bc46">

If I used version 20 for installation with the same approach npm also works well and I had 
Node: v20.11.0
npm: v10.2.4

The issue appeared yesterday, before that we built a lot of images with node 18 and npm 10.2.3 for our needs. 
Could you help us to understand what is the issue? 
Thanks

**Comment by richardlau** [comment]
> Hello, I have an issue with npm. I have used [this](https://deb.nodesource.com/) approach to install Node 18 inside the docker image.

You'll need to ask over in https://github.com/nodesource/distributions/issues -- the Node.js project does not maintain the distributions from https://deb.nodesource.com/.

**Comment by HelpAroundUser** [comment]
Thanks I found the solution

**Comment by kpshiv** [comment]
@HelpAroundUser could you please comment the solution bcz I am also facing the same issue.thank you.

**Comment by HelpAroundUser** [comment]
```
NODE_MAJOR="18"

### workaround to install npm ##
RUN echo "Package: nodejs*" | tee -a /etc/apt/preferences.d/nodejs > /dev/null 
RUN echo "Pin: release *" | tee -a /etc/apt/preferences.d/nodejs > /dev/null 
RUN echo "Pin-Priority: -1" | tee -a /etc/apt/preferences.d/nodejs > /dev/null 
### end workaround to install npm ##

RUN mkdir -p /etc/apt/keyrings;
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt update \
    && apt install nodejs -y 

```
