### ISSUE TITLE
node installation

### ISSUE THREAD

**Issue by sk670994** [nodejs/help#4336]
### Details

I downloaded the Node.js MSI file many times and tried to install and uninstall Node.js. I tried everything manually adding path in environment variables but still it's showing:

```console
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

> node
'node' is not recognized as an internal or external command,
operable program or batch file.
```

and also in VSCode it's showing:

```console
> node --version
node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:1 char:1

node --version
  + CategoryInfo          : ObjectNotFound: (node:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException
````

kindly let me know what should I do and install Node.js and npm correctly and why isn't it installing on my laptop.

### Node.js version

v20 not showing in cmd 

### Operating system

Windows 

### Scope

installation

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
can you share you path?

**Comment by Aayan-Ali-Hashim** [comment]
Install it Again , if still not working , let me know I will explain you in live class.

**Comment by RedYetiDev** [comment]
Author didn't provide sufficient information to the comments from other contributors with 4 months, assuming stale
