### ISSUE TITLE
Error while running node in ARMv7 platform.

### ISSUE THREAD

**Issue by qq8512852** [nodejs/help#4338]
### Details

My platform is running Debian, and I installed Node,js using apt-get.
I can see the version output through command "node --version" , but it's not working I try to run it.
The same result with download from official web which version node-v20.11.0-linux-armv7l. 

![image](https://github.com/nodejs/help/assets/15918325/44910b2e-9522-4a2a-bfae-09426541f238)

### Node.js version

v12.22.12  and  node-v20.11.0-linux-armv7l

### Example code

no

### Operating system

Linux

### Scope

runtime

### Module and version

Not applicable.

**Comment by VoltrexKeyva** [comment]
> The same result with download from official web which version node-v20.11.0-linux-armv7l.

Did you uninstall Node.js that you installed from APT before running `node-v20.11.0-linux-armv7l`? If you didn't then it could still be running the one from APT which would result in the same error in this case.

On an additional note, I would recommend installing Node.js using a Node.js version manager like [nvm](https://nvm.sh/).

**Comment by qq8512852** [comment]
> > The same result with download from official web which version node-v20.11.0-linux-armv7l.
> 
> Did you uninstall Node.js that you installed from APT before running `node-v20.11.0-linux-armv7l`? If you didn't then it could still be running the one from APT which would result in the same error in this case.
> 
> On an additional note, I would recommend installing Node.js using a Node.js version manager like [nvm](https://nvm.sh/).

Hi sir. Even though Node.js has been uninstalled  by 'apt-get remove' , the following error is encountered.
![image](https://github.com/nodejs/help/assets/15918325/34558f25-e69e-41ae-8fa0-6404d8d6c3e0)

**Comment by RedYetiDev** [comment]
The nodejs apt-get package is not officially maintained. If you are able to reproduce with a version of Node.js from the website; please leave a comment. Otherwise, I'll assume this issue is resolved.
