### ISSUE TITLE
EADDRINUSE connect EADDRINUSE 127.0.0.1:<port number> error seen when executing protractor scripts

### ISSUE THREAD

**Issue by eymemathew** [nodejs/help#434]
Node version - 4.4.2
Jasmine version - 2.4.1
Protractor version - 3.1.1
OS - Windows Server 2012 R2, 64-bit

When we try to run our protractor tests that use Jasmine, we see an error - EADDRINUSE being thrown after a couple of it blocks are executed. This same test works fine on our laptops (Win7 64bit). Can you advise on why this error is thrown?

The error thrown: EADDRINUSE connect EADDRINUSE 127.0.0.1:<portnumber>

It throws a random port number each time and we have verified that this port is not being used by any other processes at that time.

**Comment by gibfahn** [comment]
Can you reproduce it when just running a single test?

**Comment by eymemathew** [comment]
Yes we can consistently reproduce it even with a single script. We tried rebooting the machine to ensure no ports are in use and then ran the test and the issue was seen. The same script doesn't produce that error when run on the laptop but does it when run on the Server or VM environment.

**Comment by eymemathew** [comment]
Yes we can consistently reproduce it even with a single script. We tried rebooting the machine to ensure no ports are in use and then ran the test and the issue was seen. The same script doesn't produce that error when run on the laptop but does it when run on the Server or VM environment.

**Comment by gibfahn** [comment]
Originally raised in https://github.com/nodejs/node/issues/10645

**Comment by gibfahn** [comment]
Can you post a link to the test script?

**Comment by eymemathew** [comment]
Here is a snippet of the code: It fails right after Test is entered in the last it block:

require( __dirname + '/../../PageObjects/all-page-objects.po.js' );

describe( 'Test Case: cols-create-edit', function() {
      // Variable(s)
    var countBeforeDeleteFromPersonal, countBeforeDeleteFromClient;

    describe( 'Test Step ID: 123, function() {

        it( 'Should launch the application with "default_doc_OLD" document', function() {
            MainPage.goToURL( '#/doc/Client:default_doc_OLD/report/report0' );

            // Check if application is launched
            browser.getTitle().then( function( title ) {
                expect( title === 'Weights [Client:default_doc_OLD]' )
                    .customError( 'Title of browser did not match. ' +
                        'Expected: "Weights [Client:default_doc_OLD]", Found: "' +title+ '"' );
                if ( title !== 'Weights [Client:default_doc_OLD]' ) {
                    CommonFunctions.takeScreenShot();
                }
            } );
        } );

        it( 'Should click on the "Wrench" button on the application toolbar', function() {
            MainPage.getWrenchIcon().click().then( function() {}, function( err ) {
                expect( false ).customError( err );
                CommonFunctions.takeScreenShot();
            } );

            // Verifying if drop down menu appear.
            MainPage.getWrenchIcon( true ).isPresent().then( function( option ) {
                if ( !option ) {
                    expect( false ).customError( 'Wrench icon dropdown is not present.' );
                    CommonFunctions.takeScreenShot();
                }
            } );
        } );

        it( 'Should select "Automatic Calculation" option', function() {
            // Verifying if "Automatic Calculation" option is selected.
            MainPage.setAutomaticCalculation( true ).then( function( option ) {
                if ( !option ) {
                    expect( false ).customError( '"Automatic Calculation" is not selected.' );
                }
            } );
        } );

        it( 'Enter "Test" in the "Portfolio" widget and select ' +
            '"CLIENT:/PA3/TEST.ACCT" from type ahead', function() {
            MainPage.setPortfolio( 'Test', 'Client:/TEST.ACCT', 'Client:/TEST.ACCT' ).then( function( option ) {
                if ( !option ) {
                    expect( false ).customError( '"CLIENT:/TEST.ACCT" is not selected from type ahead.' );
                    CommonFunctions.takeScreenShot();
                }
            } );
        } );
....
....
....

    } );

} );


The function SetPortfolio has:
MainPage.prototype.setPortfolio = function( portfolioTicker, optionToSelect, expectedPortfolioFullName,
                                              selectFromTypeAheadDirectly, selectFromTypeAheadUsingKeyboardArrows ) {
    var defer = protractor.promise.defer();
    var promise = defer.promise;
    var xpathPortfolioLookupWidget = '//id-widget[@id="portfolio-textbox"]';
    var xpathPortfolioInputBox = xpathPortfolioLookupWidget + '//input';
    var xpathTypeaheadContainer = '//filter-listbox-container';
    var portfolioInputBox = element( by.xpath( xpathPortfolioInputBox ) );

    // Initializing the optional variables
    if ( selectFromTypeAheadDirectly === undefined ) {
        selectFromTypeAheadDirectly = true;
    }

    if ( selectFromTypeAheadUsingKeyboardArrows === undefined ) {
        selectFromTypeAheadUsingKeyboardArrows = false;
    }

    // Click into "portfolio" widget
    portfolioInputBox.click();

    // Clear the default portfolio selected (if exists)
    portfolioInputBox.clear();

    // Enter the text into the Portfolio Input Box
    portfolioInputBox.sendKeys( portfolioTicker );

    // Wait for the type ahead box to appear
    var xpathTypeAhead = xpathPortfolioLookupWidget + xpathTypeaheadContainer;
    Utilities.waitUntilElementAppears( element( by.xpath( xpathTypeAhead ) ), 6000 );

    // Select the option from the type ahead list if selectFromTypeAheadDirectly == true
    if ( selectFromTypeAheadDirectly ) {
        // Check if type ahead appeared, if yes, select the required option
        var typeAhead = element( by.xpath( xpathTypeAhead ) );
        typeAhead.isPresent().then( function( listFound ) {
            if ( !listFound ) {
                defer.reject( 'Type ahead did not appear after typing into the Portfolio widget.' );
            } else {
                // Find the required option in the type ahead list
                var xpathOption = xpathTypeAhead + '//*[@data-qa-class="pa-typeahead-item" ' +
                    'and @data-value="'+optionToSelect+'"] | ' + xpathTypeAhead + '//*[@data-qa-class="pa-typeahead-item" ' +
                        'and descendant::*//*[normalize-space(.)="' +optionToSelect+ '"]]';
                var refOption = element( by.xpath( xpathOption ) );
                Utilities.scrollElementToVisibility( refOption );
                refOption.isPresent().then( function( optionFound ) {
                    // If required option is not found reject the promise
                    if ( !optionFound ) {
                        defer.reject( '"' +optionToSelect+ '" Portfolio is not found in the type ahead.' );
                    } else {
                        // Select the required option
                        refOption.click();

                        // Check if required portfolio is selected
                        portfolioInputBox.getAttribute( 'value' ).then( function( portfolioValue ) {
                            if ( portfolioValue.toLowerCase() !== expectedPortfolioFullName.toLowerCase() ) {
                                defer.reject( '"' +expectedPortfolioFullName+ '" portfolio is not found in the Portfolio widget ' +
                                    'on selecting "' +optionToSelect+ '" from type ahead.' );
                            } else {
                                defer.fulfill( true );
                            }
                        } );
                    }
                } );
            }
        } );
    } else if ( selectFromTypeAheadUsingKeyboardArrows ) {
        // Get the reference of all the Portfolios from Type Ahead
        var allPortfolios = element.all( by.xpath( xpathTypeAhead + '//*[@data-qa-class="pa-typeahead-item"]' ) );

        // Click on keyboard's DOWN arrow button
        portfolioInputBox.sendKeys( protractor.Key.DOWN );

        // Iterate through each element until required portfolio is found
        allPortfolios.map( function( eleRef ) {
            return {
                value: eleRef.getAttribute( 'data-value' )
            };
        } ).then( function( items ) {
            for ( var i = 0; i < items.length; i++ ) {
                if ( items[i].value === optionToSelect ) {
                    Utilities.scrollElementToVisibility( allPortfolios.get( i ) );
                    allPortfolios.get( i ).click();
                    defer.fulfill( true );
                } else {
                    if ( i === items.length - 1 ) {
                        defer.reject( '"' +optionToSelect+ '" portfolio is not found in the type ahead.' );
                    } else {
                        // Click on keyboard's DOWN arrow button
                        portfolioInputBox.sendKeys( protractor.Key.DOWN );
                    }
                }
            }
        } );
    } else {
        defer.fulfill( true );
    }

    return promise;
};

**Comment by bnoordhuis** [comment]
I fixed the formatting in your comment, the source code was getting mangled.  The EADDRINUSE error implies you are trying to bind to the same address twice.  Scan your code base and dependencies for `net.connect` or `net.createConnection` calls (or their `tls` counterparts) that pass in `localAddress` or `localPort` options.

**Comment by eymemathew** [comment]
I scanned through all the dependency files and I could find matches for both the calls mentioned in protractor related files. 
[Net.CreateConnection.xlsx](https://github.com/nodejs/help/files/689845/Net.CreateConnection.xlsx)
[Net.Connect.xlsx](https://github.com/nodejs/help/files/689846/Net.Connect.xlsx)

Can you suggest what could be done to get around it?

**Comment by eymemathew** [comment]
And is there a reason why this same test case would work on one environment(laptop) and not on the other(Win Server)

**Comment by bnoordhuis** [comment]
Did you check that there aren't already processes running that are bound to that port?

**Comment by eymemathew** [comment]
Yes we ensured nothing is using the port and also tried rebooting the machine and tracked the tcpview. The port was being used only by the process used by the script while it ran.

**Comment by eymemathew** [comment]
@bnoordhuis did you have a chance to check the attached files related to the calls for the methods you mentioned? Can you please help here.

**Comment by MylesBorins** [comment]
@eymemathew people are not very likely to open a `.xlsx` file. Could you put your output into a [gist](https://gist.github.com) or similar online service?

**Comment by eymemathew** [comment]
Hi please find the scan results for [Net.CreateConnect](https://gist.github.com/eymemathew/6903fca9ec03b6ab66b4d915941daf78#file-net-createconnection-txt) and [Net.Connect](https://gist.github.com/eymemathew/6903fca9ec03b6ab66b4d915941daf78#file-net-connect-txt) calls and they all seem to be from the protractor related files

**Comment by eymemathew** [comment]
@MylesBorins @bnoordhuis Do the links above work? Can you please help with this?

**Comment by eymemathew** [comment]
@MylesBorins just curious, have you had a chance to look into it as this is affecting all our team members. Sorry for the trouble..

**Comment by bnoordhuis** [comment]
It's possible you're exhausting the ephemeral ports on the system.  Googling for 'windows ephemeral ports' will tell you how to increase the range.

**Comment by eymemathew** [comment]
We have tried the same by increasing the port range and then rebooting the server to start fresh. And viewed the tcpview while the test ran. The ports were not getting exhausted

**Comment by eymemathew** [comment]
Were you able to get any helpful information on the cause from the scan results for Net.Create and Net.CreateConnect calls?

**Comment by bnoordhuis** [comment]
I'm afraid I don't have any suggestions.

**Comment by anand9540** [comment]
Hi Guys,
I also ran into same issue...i get it resolved by increasing dynamicports of machine.
netsh int ipv4 set dynamicport tcp start=10000 num=55535

**Comment by jgritten** [comment]
@anand9540 what with the who now? is there a dulled down version of 

> netsh int ipv4 set dynamicport tcp start=10000 num=55535
for us knuckle draggers?

**Comment by macedolfm** [comment]
[Read the Oracle advise (click here)](https://docs.oracle.com/cd/E26180_01/Search.94/ATGSearchAdmin/html/s1207adjustingtcpsettingsforheavyload01.html)

> 
Adjusting TCP Settings for Heavy Load on Windows

The underlying Search architecture that directs searches across multiple physical partitions uses TCP/IP ports and non-blocking NIO SocketChannels to connect to the Search engines. These connections remain open in the TIME_WAIT state until the operating system times them out. Consequently, under heavy load conditions, the available ports on the machine running the Routing module can be exhausted.
On Windows platforms, the default timeout is 120 seconds, and the maximum number of ports is approximately 4,000, resulting in a maximum rate of 33 connections per second. If your index has four partitions, each search requires four ports, which provides a maximum query rate of 8.3 queries per second.
(maximum ports/timeout period)/number of partitions = maximum query rate.

If this rate is exceeded, you may see failures as the supply of TCP/IP ports is exhausted. Symptoms include drops in throughput and errors indicating failed network connections. You can diagnose this problem by observing the system while it is under load, using the netstat utility provided on most operating systems.

To avoid port exhaustion and support high connection rates, reduce the TIME_WAIT value and increase the port range.

Note: This problem does not usually appear on UNIX systems due to the higher default connection rate in those operating systems.

To set TcpTimedWaitDelay (TIME_WAIT):

Use the regedit command to access the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\ Services\TCPIP\Parameters registry subkey.

Create a new REG_DWORD value named TcpTimedWaitDelay.

Set the value to 60.

Stop and restart the system.

To set MaxUserPort (ephemeral port range):

Use the regedit command to access the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\ Services\TCPIP\Parameters registry subkey.

Create a new REG_DWORD value named MaxUserPort.

Set this value to 32768.

Stop and restart the system.

**Comment by mjachowdhury** [comment]
@macedolfm I think we have to select set value decimal then set the value.
