### ISSUE TITLE
why use the event emitter instead of the asynchronous function

### ISSUE THREAD

**Issue by Sivaharish12** [nodejs/help#4342]
Why the event emitter is used instead of the asynchronous function because the asynchronous function is also capable of doing the emitter so why do we use the event emitter.

**Comment by preveen-stack** [comment]
https://stackoverflow.com/questions/27677692/performance-cost-of-pubsub-excessive-events-and-event-handlers-in-javascript

Perhaps the above can shed some light

**Comment by RedYetiDev** [comment]
@Sivaharish12 did @preveen-stack's solution help?
