### ISSUE TITLE
Centos7 uses the n command to install nodejs 18.19.1, but runs with the following error message.

### ISSUE THREAD

**Issue by bbhxwl** [nodejs/help#4346]
How should I upgrade?

```console
[root@VM-0-17-centos bin]# node -v
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by node)
node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by node)
[root@VM-0-17-centos bin]# 
```

**Comment by marco-ippolito** [comment]
Hi @bbhxwl, how did you install node? It seems you are missing some system libraries or have outdated version.

**Comment by RedYetiDev** [comment]
*No response to @marco-ippolito's query*

If you disagree, please re-open.

**Comment by HaitamDevOps** [comment]
Hello !
I have the same issue here when I followed steps of installing nodeJS from [nodeSource](https://rpm.nodesource.com/) for my Centos7 machine

> [centos@localhost code-server-npm]$ node --version
> node: /lib64/libstdc++.so.6: version \`CXXABI_1.3.8' not found (required by node)
> node: /lib64/libstdc++.so.6: version \`GLIBCXX_3.4.22' not found (required by node)
> node: /lib64/libstdc++.so.6: version \`GLIBCXX_3.4.20' not found (required by node)
> node: /lib64/libstdc++.so.6: version \`GLIBCXX_3.4.21' not found (required by node)
> node: /lib64/libstdc++.so.6: version \`CXXABI_1.3.9' not found (required by node)
> node: /lib64/libm.so.6: version \`GLIBC_2.27' not found (required by node)
> node: /lib64/libc.so.6: version \`GLIBC_2.28' not found (required by node)
> node: /lib64/libc.so.6: version \`GLIBC_2.25' not found (required by node)

**Comment by RedYetiDev** [comment]
Hi! If you are experiencing similar issue when **installing Node.js via https://nodejs.org**, please verify you have the required binaries.

If you *still* experience the issue, please file a new issue with all relavent information.
