### ISSUE TITLE
Problem with old node version

### ISSUE THREAD

**Issue by Jadiex** [nodejs/help#4347]
### Details

I have installed nvm version 1.1.12 and then i was installed node version 10.14.1 that work perfectly but when i installed version 6.2.0 and i try write differents node commands like (npm -v) and they didn't work. Don't appear any error mensage but doesnn´t do anything. I tried other command like npm install rollup o node and dont work any of them. 

I tried other version and I see that version 6.6.0 and earlier don´t work but I don't now why. I uninstall and install more then one times. Also when I am using that version and use nvm list don't appear de architecture of the version.

![image](https://github.com/nodejs/help/assets/101218889/494999ef-5f9a-4a4d-8c5a-f08627eb4d80)

### Node.js version

6.2.0

### Operating system

windows 10

### Scope

installations and use

### Module and version

Not applicable.

**Comment by Jadiex** [comment]
I have  this version for nvm
![image](https://github.com/nodejs/help/assets/101218889/54db6021-4a1f-4a67-a0f6-9c118756e052)

**Comment by RedYetiDev** [comment]
Node.js v6 has reached EoL. Unfortunately, issues within it aren't being actively worked on, but feel free to seek support from various alternative forums.
