### ISSUE TITLE
nodejs version 20.11.0，node:event:496

### ISSUE THREAD

**Issue by runningfan123** [nodejs/help#4348]
### Version

20.11.0

### What do you see instead?

![企业微信截图_17085659216487](https://github.com/nodejs/node/assets/65215605/6aca4169-67c6-4e5c-8743-43cd29d1bd6e)

**Comment by VoltrexKeyva** [comment]
See https://github.com/streamich/memfs/issues/828

**Comment by MariuzM** [comment]
Im having same issue node 20, installed dotenv_cli globally but getting this error

**Comment by RedYetiDev** [comment]
Hi! I believe @VoltrexKeyva's source may have resolved this issue. If you have read and understand the provided source, and this is still occurring in the latest / LTS version of Node.js, please open a new issue with a detailed reproduction.
