### ISSUE TITLE
 'node' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by viswasakthi3** [nodejs/help#4351]
### Version

v20.11.1

### Platform

Microsoft Windows NT 10.0.22631.0 x64

### What steps will reproduce the bug?

step 1 : run any nuxt 3 project 
step 2 : stop the system stop abruptly or shut down or close it 

### How often does it reproduce? Is there a required condition?

when the steps mentioned followed

### What is the expected behavior? Why is that the expected behavior?

normal working of the project 

### What do you see instead?

PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> npm install
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\viswa\\Desktop\\nuxt-proj\\theluvit\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\viswa\Desktop\nuxt-proj\theluvit\node_modules\@nuxt'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\viswa\\Desktop\\nuxt-proj\\theluvit\\node_modules\\@nuxt'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\viswa\Desktop\nuxt-proj\theluvit\node_modules\vue-demi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node -e "try{require('./scripts/postinstall.js')}catch(e){}"
npm ERR! 'node' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in: C:\Users\viswa\AppData\Local\npm-cache\_logs\2024-02-29T15_08_05_358Z-debug-0.log
PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> node -v
v20.11.1
PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> 

### Additional information

i tried every way possible i tried changing the nuxt 3 project  its kept happening i tried uninstalling the node js and install it , used the wise programmer unisntaller  done this process multiple times

PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> npm install
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\viswa\\Desktop\\nuxt-proj\\theluvit\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\viswa\Desktop\nuxt-proj\theluvit\node_modules\@nuxt'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\viswa\\Desktop\\nuxt-proj\\theluvit\\node_modules\\@nuxt'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\viswa\Desktop\nuxt-proj\theluvit\node_modules\vue-demi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node -e "try{require('./scripts/postinstall.js')}catch(e){}"
npm ERR! 'node' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in: C:\Users\viswa\AppData\Local\npm-cache\_logs\2024-02-29T15_08_05_358Z-debug-0.log
PS C:\Users\viswa\Desktop\nuxt-proj\theluvit> node -v
v20.11.1
PS C:\Users\viswa\Desktop\nuxt-proj\theluvit>

**Comment by RedYetiDev** [comment]
Hi! Is this still occurring?

**Comment by Simacoder** [comment]
Verify Node.js Installation
First, ensure that Node.js has been installed correctly. You can verify this by navigating to the directory where Node.js was installed (typically C:\Program Files\nodejs). Check for the presence of the node.exe file in this directory.

Reinstall Node.js
If the above steps don’t work, consider reinstalling Node.js:

Uninstall Node.js
Open Control Panel.
Go to Programs > Programs and Features.
Find and uninstall Node.js.
Reinstall Node.js
Download the latest Node.js installer from the [official Node.js website](https://nodejs.org/).
Run the installer and ensure that the option to add Node.js to the PATH is checked.
Add Node.js to System PATH
If Node.js is installed but the command is still not recognized, it means the system PATH variable is not set correctly. Follow these steps to add Node.js to your PATH. Step-by-Step Solution is as: , sometimes, your system has different version ..
