### ISSUE TITLE
Create an issue Template for this repo

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/help#436]
Hey,

Do we want an issue template for this repo ?

If so, what do we want inside ? ATM, I see:

* Node.js Version
* Scope (install, code, runtime)
* Package (and version) (if relevant)

Any ideas ?
cc @nodejs/evangelism

**Comment by vsemozhetbyt** [comment]
Maybe as well:
* OS
* request to provide a minimum code (if relevant)
