### ISSUE TITLE
digital envelope routines::unsupported with .mjs

### ISSUE THREAD

**Issue by HaoDong108** [nodejs/help#4365]
### Details

The first time I used the node .mjs script, I encountered this problem.

(See Example code)

This is just a simple single Demo script.  Its file suffix is'. mjs'

On this issue, I refer to [stackoverflow](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported/69672525),And tried to input `set NODE_OPTIONS=--openssl-legacy-provider` at the vscode terminal.  But it didn't work

I don't want to reduce the version of nodejs, and I don't want to attach other files. Who can tell me how to solve this problem gracefully? 😣

### Node.js version

v20.11.1

### Example code

```js
import crypto from 'node:crypto';

var obj = {
    code: "GM10001",
    stamp: (new Date()).getTime()
}
var json = JSON.stringify(obj);

var key = Buffer.from("pmQG0EzAXjV1UBCBw4hdDRRKgYnZErCb", "utf8");
var iv = Buffer.from("L434o3PH", "utf8");

//nodejs crypto
var cipher = crypto.createCipheriv('des-cbc', key, iv);   //throw error  0308010C:digital envelope routines::unsupported
var crypted = cipher.update(json, 'utf8', 'hex');
crypted += cipher.final('hex');

console.log(crypted);
```

### Operating system

windows 11  
Code edit in vscode

### Scope

None

### Module and version

Not applicable.

**Comment by Trott** [comment]
@nodejs/crypto

**Comment by tniessen** [comment]
@HaoDong108 Why are you using `des-cbc`?

**Comment by HaoDong108** [comment]
I can't understand why a code that only needs to be implemented purely by algorithm would encounter errors that seem completely unrelated to the calculation process.

**Comment by RedYetiDev** [comment]
> But it didn't work

Please provide information about what exactly went wrong

Thanks!

**Comment by Trott** [comment]
> > But it didn't work
> 
> Please provide information about what exactly went wrong
> 
> Thanks!

They provide a comment in the code indicating the error they receive on that particular line:

```js
var cipher = crypto.createCipheriv('des-cbc', key, iv);   //throw error  0308010C:digital envelope routines::unsupported
```

**Comment by RedYetiDev** [comment]
My bad! Sorry for the noise

**Comment by Trott** [comment]
> My bad! Sorry for the noise

Actually, I was wrong. They don't say what went wrong when they tried the legacy provider flag.  And I see now when I do it myself that the error is different:

```
RangeError: Invalid key length
```

Seems like the key is an incompatible length for the chosen algorithm. I'm not a cryptography expert by any means, but a web search indicates that DES keys are 56 bits long. Changing the key to that length fixes the error for me.

```js
const crypto = require('crypto')

var obj = {
    code: "GM10001",
    stamp: (new Date()).getTime()
}
var json = JSON.stringify(obj);

var key = "pmQG0EzA";
var iv = Buffer.from("L434o3PH", "utf8");

//nodejs crypto
var cipher = crypto.createCipheriv('DES-CBC', key, iv);   //throw error  0308010C:digital envelope routines::unsupported
var crypted = cipher.update(json, 'utf8', 'hex');
crypted += cipher.final('hex');

console.log(crypted);
```

I'm going to optimistically close this but not before saying: Please don't use legacy crypto algorithms.
