### ISSUE TITLE
setImmediate() ,process.nextTick() understanding

### ISSUE THREAD

**Issue by maccrin** [nodejs/help#4366]
### Enter your suggestions in details:

when I run the below code in ES module
```js
const start = () => {
    console.log('start');
    setImmediate(baz);
    setTimeout(() => console.log('timeout', 0))
    new Promise((resolve, reject) => {
        resolve('bar');
    }).then(resolve => {
        console.log(resolve);
        process.nextTick(zoo);
    });
    process.nextTick(foo);
};

start();
```

output
```console
start
bar
foo
zoo
baz
```

As per the documentation 
https://github.com/nodejs/nodejs.org/blob/main/pages/en/learn/asynchronous-work/understanding-setimmediate.md
It should be
```console
start
foo
bar
zoo
baz
```
I got the expected output as per documentation when run under CommonJS module.
so is the output is dependent on ES/CommonJS, it would be helpful if that is mentioned in the documentation.

**Comment by RedYetiDev** [comment]
(re)pinging @nodejs/timers

**Comment by benjamingr** [comment]
This was already fixed in the docs:

> The principle aforementioned holds true in CommonJS cases, but keep in mind in ES Modules, e.g. mjs files, the execution order will be different:

**Comment by maccrin** [comment]
> This was already fixed in the docs:
> 
> > The principle aforementioned holds true in CommonJS cases, but keep in mind in ES Modules, e.g. mjs files, the execution order will be different:

Thanks for the update.
