### ISSUE TITLE
I was installing the react typescript after installed i ran npm start ,this error i my facing

### ISSUE THREAD

**Issue by Manish-kumar-9601** [nodejs/help#4367]
### Details

'Typescript\my-app\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module 'C:\Users\manis\OneDrive\Documents\react-scripts\bin\react-scripts.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

### Node.js version

Not applicable.

### Operating system

window 11

### Scope

after the installation of react app

### Module and version

Not applicable.

**Comment by Trott** [comment]
You'll probably have better luck asking in a react and/or typescript forum. Even better might be StackOverflow. Sorry no one here has chimed in with any comments.
