### ISSUE TITLE
Error in JSON.parse() NodeJs

### ISSUE THREAD

**Issue by FranciscoCastle** [nodejs/help#4371]
### Version

21.7.1

### Platform

Microsoft Windows NT 10.0.22631.0 x64

### What steps will reproduce the bug?

![image](https://github.com/nodejs/node/assets/30781874/f799edca-0798-4727-81c6-bac7b1d407e8)
```
let data = JSON.stringify({string: "example text", object: {string: "text 2",object: {string: 3}}});
console.log(JSON.parse(data));
let _data = {data:JSON.parse(data)};
console.log(_data);
```

### How often does it reproduce? Is there a required condition?

All the time I run my app in nodejs

in my browser console it works correctly:

![image](https://github.com/nodejs/node/assets/30781874/3e7a9f21-c412-467a-90a8-30364796c93c)

### What is the expected behavior? Why is that the expected behavior?

```
{
  string: 'example text',
  object: { string: 'text 2', object: { string: 3 } }
}
{
  data: {
    string: 'example text',
    object: { string: 'text 2', object: { string: 3 } } // not [Object]
  }
}
```

### What do you see instead?

result in console:
![image](https://github.com/nodejs/node/assets/30781874/984a5604-e7a7-4961-9ee3-27f28f6ce3a5)
```
{
  string: 'example text',
  object: { string: 'text 2', object: { string: 3 } }
}
{
  data: {
    string: 'example text',
    object: { string: 'text 2', object: [Object] }
  }
}
```

### Additional information

I would like to send an object to my view in Pug but when reading it in Pug I only get this in the view:

![image](https://github.com/nodejs/node/assets/30781874/5490be1a-0c0b-40fb-b6a4-36ed3987e03e)

index.js:

```
res.render('index',_data);
```

index.pug:

```
p= data
```

**Comment by FranciscoCastle** [comment]
> It has nothing to do with `JSON.parse()`, as @climba03003 mentioned it's the documented behavior of `console.log()`. You should first convert the data to a string with e.g. `JSON.stringify()`, `util.format()`, or a third party library.

But if the problem is not with `JSON.parse()`, why does the first console show me all the JSON and the second show it with the result `[Object]`?

Likewise, as you say in your comment, before parsing it with `JSON.parse()`, a string must be created with `JSON.stringify()`, but I am doing it.

**Comment by aliakbar192** [comment]
In your code, you're correctly stringifying an object and then parsing it back into an object. However, when you pass _data to your Pug template, you're assigning the entire object to a variable called data. This is why you're seeing [object Object] in your view because data is an object, and Pug is displaying it as a string representation.

**Comment by RedYetiDev** [comment]
*(This issue seems resolved)*
