### ISSUE TITLE
Error: Cannot find module 'is-odd'

### ISSUE THREAD

**Issue by vfilatov** [nodejs/help#4372]
### Version

v20.12.1

### Platform

Linux dev 5.10.0-28-amd64 nodejs/node#1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux

### What steps will reproduce the bug?

The original issue https://github.com/sveltejs/kit/issues/11912

```shell
git clone https://github.com/gtm-nayan/node-socket-import-error.git
cd node-socket-import-error/
rm package-lock.json pnpm-lock.yaml
pnpm i
node index.mjs
```

### What is the expected behavior? Why is that the expected behavior?

If package installed with `npm i` it does not throw the error below

### What do you see instead?

```console
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'is-odd'
Require stack:
- /tmp/node-socket-import-error/node_modules/is-even/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/tmp/node-socket-import-error/node_modules/is-even/index.js:10:13)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/node-socket-import-error/node_modules/is-even/index.js' ]
}

Node.js v20.5.1
```

**Comment by vfilatov** [comment]
> Hi! This repo is issues with the NodeJS core, and this looks like an issue with a package installation.
> 
> But, to answer your question, modules are usually installed with `npm install <module>` (or similar, depending on your package manager). Installed packages typically appear in `./node_modules/<module>`, so if that folder doesn't exist, than the package is not installed.
> 
> If your experiencing an issue with `pnpm`, please file an issue in their repository.
> 
> Thank you!

They insist that is a `nodejs` bug.
https://github.com/pnpm/pnpm/issues/7931#issuecomment-2093152936

**Comment by ahaoboy** [comment]
```js
// index.js
// node ./index.js

const isEven = require('is-even')
console.log(isEven(1))
```


```
// index.js
// node ./index.js
import * as isEven from 'is-even'
console.log(isEven.default(1))

```

**Comment by ahaoboy** [comment]
I found an interesting thing. This line of code will affect the execution results. After commenting it out, it will only report an error the first time it is run. After that, it can run correctly every time. After removing the comment, it will report an error every time it is run.

```js
import fs from 'fs';
import { createServer } from 'net';
const mySocketFile = '/tmp/mysocketfile';

if (fs.statSync(mySocketFile, { throwIfNoEntry: false }))
  fs.unlinkSync(mySocketFile);

// magic line
createServer((socket) => { }).listen(mySocketFile);

setTimeout(async () => {
  const isEven = await import("is-even")
  console.log("isEven: ", isEven.default(1))
});
```

```
 node --version
v22.1.0
```

**Comment by ahaoboy** [comment]
@vfilatov  Can you test using node 18? On my machine node18 doesn't have this problem

**Comment by vfilatov** [comment]
> I found an interesting thing. This line of code will affect the execution results. After commenting it out, it will only report an error the first time it is run. After that, it can run correctly every time. After removing the comment, it will report an error every time it is run.
> 
> ```js
> import fs from 'fs';
> import { createServer } from 'net';
> const mySocketFile = '/tmp/mysocketfile';
> 
> if (fs.statSync(mySocketFile, { throwIfNoEntry: false }))
>   fs.unlinkSync(mySocketFile);
> 
> // magic line
> createServer((socket) => { }).listen(mySocketFile);
> 
> setTimeout(async () => {
>   const isEven = await import("is-even")
>   console.log("isEven: ", isEven.default(1))
> });
> ```
> 
> ```
>  node --version
> v22.1.0
> ```

Yes, that is the point!
Initially I though the problem is on the SvelteKit side, but this simplified code excludes all SvelteKit relations.
It is either pnpm or node.
As you found the (simplified) code working under node18 that makes me suspect the code might be on node core...

**Comment by RedYetiDev** [comment]
Hi! If you delete the package-lock and pnpm-lock files and run `npm i`, then test the code in the latest version (`v20.1.3` for LTS), will this issue still occur?

**Comment by vfilatov** [comment]
> Hi! If you delete the package-lock and pnpm-lock files and run `npm i`, then test the code in the latest version (`v20.1.3` for LTS), will this issue still occur?

Yes, it is working when I use `npm`

**Comment by RedYetiDev** [comment]
So this probably isn't an issue with `npm`. What happens when you follow the same instructions but use `pnpm` instead?

**Comment by vfilatov** [comment]
> So this probably isn't an issue with `npm`. What happens when you follow the same instructions but use `pnpm` instead?

when I use `pnpm` and node 20, I get the error above.
when I use `pnpm` and node 18, I do not get the error above.
when I use `npm` and any node, I do not get the error above.

**Comment by RedYetiDev** [comment]
So, despite what the `pnpm` team may have said, it really doesn't seem like an issue with Node.

**Comment by vfilatov** [comment]
> So, despite what the `pnpm` team may have said, it really doesn't seem like an issue with Node.

It might an issue on both sides... As something changed between node18 & node20...
Would be great if somebody could simply debug the code and find that "breaking point".
May guess that bug could be fixed by either team.

**Comment by RedYetiDev** [comment]
Well, the change from Node.js v18 to Node.js v20 was breaking, as with major release lines, so breakages are expected, maybe the pnpm team knows?

**Comment by ahaoboy** [comment]
> Well, the change from Node.js v18 to Node.js v20 was breaking, as with major release lines, so breakages are expected, maybe the pnpm team knows?

Someone more familiar with both libraries would need to investigate this in depth, and as a short-term solution, maybe try running it with bun for now?

**Comment by RedYetiDev** [comment]
Marking as NPM ad this regards it vs pnpm

**Comment by RedYetiDev** [comment]
As this is a still not reproducible via NPM, I'm gonna go ahead and close this issue. I know this isn't the answer you wanted, but It doesn't seem actionable. If you continue to experience errors, please open a new issue here or at `npm/cli`.

**Comment by vfilatov** [comment]
Here is the problem I see.
The issue involves nodejs & pnpm.
Each one of the core developers blame the other side.
Would it be possible for you guys to talk to each other and find a solution?

Thanks

**Comment by RedYetiDev** [comment]
> Each one of the core developers blame the other side.

Just want to point out a few things:
1. I'm not a Node.js core collaborator. While I'm a member of the organization, my role is as issue triage and support

2. I wouldn't say I'm "blaming" the PNPM team, I just don't think this is an issue with Node.js, as (AFAICT) it's not reproducible.

CC @nodejs/npm

**Comment by vfilatov** [comment]
Pnpm team insists this issue appears only in the nodejs v20, not in v18
(that is true).
Apparently (I don't aggree with that) issue on the node side.

The real issue is that nobody is willing to determine the breaking point.

Unfortunately my js experience doesn't let me dive that deep.

Thanks

**Comment by RedYetiDev** [comment]
I've CCd the NPM team to take a look

**Comment by ahaoboy** [comment]
I am not familiar with the underlying mechanisms of node and pnpm, but I found some very strange nodejs behaviors when reproducing this problem.


```
 node --version
v22.4.1

```

```
const fs = require('fs')
const { createServer } = require('net')
const mySocketFile = '/tmp/mysocketfile';

if (fs.statSync(mySocketFile, { throwIfNoEntry: false }))
  fs.unlinkSync(mySocketFile);

// magic line
createServer((socket) => { }).listen(mySocketFile);

setTimeout(async () => {
  try {
    console.log('resolve: ', require.resolve('is-even'))
    require('is-even')
  } catch (e) {
    console.log("err:", e)
  }
});
```

Run the above code multiple times. If an error occurs, the output should be a file path similar to the following:
```
resolve:  /root/code/npm-bug/node_modules/is-even/index.js
```

Comment out the magic line and run it multiple times. It should only report an error the first time. If there is no error, it should output a path similar to the following
```
resolve:  /root/code/npm-bug/node_modules/.pnpm/is-even@1.0.0/node_modules/is-even/index.js
```

This seems to indicate that the createServer function causes the behavior of nodejs resolve to change. I don't know what the specific mechanism is. If anyone wants to delve into this issue, I hope it will help.

**Comment by RedYetiDev** [comment]
Thanks for the info, @ahaoboy! That is indeed really strange. I suggest you open an issue against nodejs/node.

CC @nodejs/net

**Comment by RedYetiDev** [comment]
Sorry for the earlier close, @vfilatov. It's unclear how/why this issue occurs, but I've reopened the issue for tracking.

**Comment by vfilatov** [comment]
Please pay attention, this happens only on IPC, while TCP (the code below) working fine.
```javascript
import fs from 'fs';
import { createServer } from 'net';
const mySocketFile = '/tmp/mysocketfile';

if (fs.statSync(mySocketFile, { throwIfNoEntry: false }))
  fs.unlinkSync(mySocketFile);

// magic line
//createServer((socket) => { }).listen(mySocketFile);
createServer((socket) => { }).listen(8080);

setTimeout(async () => {
  const isEven = await import("is-even")
  console.log("isEven: ", isEven.default(1))
});
```

**Comment by RedYetiDev** [comment]
Hey everyone, I found the culprit: https://github.com/nodejs/node/issues/51142
