### ISSUE TITLE
build nodejs as a static library

### ISSUE THREAD

**Issue by bncdemo** [nodejs/help#4380]
### Details

Hi,

I still not found a clear way how to build nodejs as a static library on windows, can somebody give me an example?

### Node.js version

v18

### Operating system

windows10

### Scope

native dll

### Module and version

Not applicable.

**Comment by bncdemo** [comment]
Even ChatGPT answer with general terms, but nothing specific. 😑

**Comment by preveen-stack** [comment]
Perhaps single executable repo can give you some info https://github.com/nexe/nexe

**Comment by bncdemo** [comment]
> Perhaps single executable repo can give you some info https://github.com/nexe/nexe

That is some kind of packager, not relevant to the question.
