### ISSUE TITLE
Npm installation on versions under 21 not working.

### ISSUE THREAD

**Issue by marianaibarra** [nodejs/help#4388]
### Details

What steps will reproduce the bug?
Executing npm i with a package.json

How often does it reproduce? Is there a required condition?
When i try to install packages, it frozes.

What is the expected behavior? Why is that the expected behavior?
To install packages on all versions

What do you see instead?
It stays frozen with no output.

### Node.js version

18.19.1

### Operating system

Darwin MacBook-Air-de-Mariana.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103 arm64

### Scope

Installation

### Module and version

Not applicable.

**Comment by RedYetiDev** [comment]
Thanks for the issue! Could you provide us with some example code, such as a package.json or npm command?

**Comment by marianaibarra** [comment]
Hello, yes of course:

{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "engines": {
    "node": "18.x",
    "yarn": "1.x"
  },
  "scripts": {
    "start": "node .output/server/index.mjs",
    "build": "npx nuxi build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "format": "npx prettier --write '**/*.{js,vue,css,html}'"
  },
  "devDependencies": {
    "@nuxtjs/google-fonts": "^3.1.3",
    "@nuxtjs/tailwindcss": "^6.10.4",
    "@vueuse/core": "^10.7.2",
    "@vueuse/nuxt": "^10.7.2",
    "autoprefixer": "^10.4.16",
    "nuxt": "^3.9.0",
    "nuxt-icon": "^0.6.8",
    "nuxt-primevue": "^0.2.2",
    "postcss": "^8.4.33",
    "prettier": "^3.2.5",
    "vue": "^3.4.5",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.5.1",
    "axios": "^1.6.8",
    "chart.js": "^4.4.1",
    "chartjs-plugin-datalabels": "^2.2.0",
    "chroma-js": "^2.4.2",
    "fernet": "^0.3.2",
    "firebase": "^10.7.2",
    "firebase-admin": "^12.0.0",
    "fuse.js": "^7.0.0",
    "hookable": "^5.5.3",
    "html5-qrcode": "^2.3.8",
    "joi": "^17.12.1",
    "moment": "^2.30.1",
    "moment-duration-format": "^2.3.2",
    "nuxt-swiper": "^1.2.2",
    "pinia": "^2.1.7",
    "primevue": "^3.46.0",
    "sass": "^1.69.7",
    "xss": "^1.0.14",
    "zod": "^3.22.4"
  }
}

Im executing npm i, but the problem is i'm executing any command under nodejs v18 and it doesnt seem to work:

I executed npm i -g yarn, and it hangs without response, i changed my network connection, but it didnt resolve the issue

**Comment by RedYetiDev** [comment]
Is it only `npm i -g yarn`?
