### ISSUE TITLE
Why NodeJS fs module won't read or write to visible folder shared on the network?

### ISSUE THREAD

**Issue by worknotalent** [nodejs/help#4390]
### Details

I shared a folder on my network through the use of Windows UI.

I'm able to access this folder and edit its content through the File Explorer but problems arise when I try to do the same programmatically. Any fs functions will work on the hoster machine but on any secondary device it won't.

I had to pass the hoster session credentials when I first tried to access the folder from the secondary device so I'm guessing this folder is invisible to NodeJS for the same reason but I'm not sure, and if so I don't know how to pass credentials to NodeJS to make network folders accessible to it.

### Node.js version

20.12.0

### Example code

node:fs:2342
    return binding.writeFileUtf8(
                   ^

Error: UNKNOWN: unknown error, open '//DESKTOP-NAME/folder/test.txt'
    at Object.writeFileSync (node:fs:2342:20)
    at file:///C:/Users/me/some_folder/some_file.js:3:4
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'open',
  path: '\\\\DESKTOP-NAME\\folder\\test.txt'
}

Node.js v20.12.0

### Operating system

Microsoft Windows [Version 10.0.19045.4291]

### Scope

code

### Module and version

fs

**Comment by worknotalent** [comment]
Someone on StackOverflow suggested to use a package called node-cmd to update the credentials first and then use the fs function but it still fails for me :
import cmd from "node-cmd"
cmd.runSync(`net use \\DESKTOP-${device} /user:${username} ${password}`);

**Comment by preveen-stack** [comment]
Did you try escaping backslashes
\\\\DESKTOP-NAME\\folder\\test.txt

**Comment by mStirner** [comment]
You cant use a smb/cifs share as path in node.js.
Mount that network share as local resource like drive `X:` or what ever you want, and use then `x:/path/to/wher-ever-you-want-to-go`.

**Comment by mStirner** [comment]
> @nodejs/platform-windows does Node.js support network drives?

Does node support nfs/linux network shares? No.
You have to mount the network shared resources as local medium/device, and use that in node.js

**Comment by tniessen** [comment]
Does Node.js not support UNC paths on Windows? I was under the impression that any UNC path referring to a real file system (not an emulated file system or USB device or so) would work.

**Comment by RedYetiDev** [comment]
Thanks for the information!

It appears Node.js does not support the functionality you are attempting to use, so unfortunately it may not be possible to achieve the desired results.
