### ISSUE TITLE
Node.js Hosting

### ISSUE THREAD

**Issue by jasurhaydarovcode** [nodejs/help#4394]
### Node.js Version

v.20.11.1

### NPM Version

v.10.5.2

### Operating System

Windows

### Subsystem

domain

### Description

Hi, which hosting did you use for nodejs.org?

### Minimal Reproduction

Hi, which domen did you use for nodejs.org?

### Output

Hi, which hosting did you use for nodejs.org?

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
For information on the Node.js website, please visit https://github.com/nodejs/nodejs.org

**Comment by jasurhaydarovcode** [comment]
thanks
