### ISSUE TITLE
Linked bindings initialization

### ISSUE THREAD

**Issue by kaero** [nodejs/help#44]
Hi!

We've used linked bindings to compile single statically linked node binary for deployment, so i've a question about difference in the initialization process for built-in bindings, linked bindings and native extensions as dynamic libraries.

As far as i can see, linked binding initialization works more like built-in native modules init: module can be called using `process._linkedBinding()` and initialization function receive `v8::String` as second argument instead of `v8::Object` instance of `Module`.

My question is: is it good idea to hack linked binding initialization to make to behave more like `require + DLOpen` (create instance of `Module` and pass it to initialization function) or it's reserved for some internal needs? Maybe where is another, less "private" way to have native extensions as compiled-in modules?

**Comment by kaero** [comment]
@indutny Hi, Fedor! Can you help me to find anyone interested in this discussion? Is it right place for it?

**Comment by indutny** [comment]
@kaero I think it is a plain bug, and it should be receiving a `module` object instead of `String`.

**Comment by indutny** [comment]
Please feel free to file an issue for this.

**Comment by indutny** [comment]
And don't forget to cc me there ;) I'm going to take a look at it.

**Comment by kaero** [comment]
btw, it's only part my question. Second one is about usage of `process._linkedBinding()` which looks like private because of leading underscore in the name ;) Is it ok to use it?

**Comment by indutny** [comment]
I think the second question could be answered in a following way: please file an additional issue and cc me ;)

It probably just needs a documentation listing its signature and action, but it should be quite safe to use. Also, if it will get a doc - we will consider removing underscore.
