### ISSUE TITLE
Error with first launch 

### ISSUE THREAD

**Issue by TannicArcher** [nodejs/help#4405]
### Node.js Version

-

### NPM Version

-

### Operating System

Windows 10 Home 

### Subsystem

Other

### Description

[Новый текстовый документ (2).txt](https://github.com/nodejs/help/files/15416977/2.txt)

### Minimal Reproduction

i start prebuilt installer for first time node-v22.2.0-x64

### Output

[Новый текстовый документ (2).txt](https://github.com/nodejs/help/files/15416997/2.txt)

### Before You Submit

- [ ] I have looked for issues that already exist before submitting this
- [ ] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Hi! Your issue doesn't seem to involve Node.js at all, and it doesn't provide the needed information. Please revise your issue and resubmit
