### ISSUE TITLE
Porting nodejs module to run on v8

### ISSUE THREAD

**Issue by GauthamBanasandra** [nodejs/help#441]
* **Node.js Version**:7.4.0
* **OS**:mac os x sierra
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:Sweet.js version: 0.7.8

-

Hi all,

I'm trying to port a nodejs module - sweet.js to make it run on v8. I'm currently trying to resolve the dependencies by replacing all the "require()" calls with the actual module itself.

I got stuck when I came across cyclic dependencies, the "require()" method somehow takes care of resolving the cyclic dependencies. Could anyone please explain how nodejs resolves cyclic dependencies?

**Comment by bnoordhuis** [comment]
sweet.js can use AMD-style loading, can't it?  I'd use that if you are targeting V8 directly.
