### ISSUE TITLE
Stop cpu profiling without SIGINT from pod

### ISSUE THREAD

**Issue by tn-motorq** [nodejs/help#4415]
### Node.js Version

v18.17.1

### NPM Version

v9.6.7

### Operating System

Linux

### Subsystem

Other

### Description

I am running a cpu profiler on some pods in k8s and I want the cpu profiler to stop and give me the dump when the pod crashes without a SIGINT from the process. Is it possible?

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Hi! Could you provide a minimal reproducible example?
