### ISSUE TITLE
crypto.privateDecrypt throwing Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error

### ISSUE THREAD

**Issue by packcode** [nodejs/help#4419]
### Node.js Version

v16.17.0

### NPM Version

v8.15.0

### Operating System

Windows 10

### Subsystem

crypto

### Description

A client of us is sending encrypted response using javax.crypto.Cipher; with padding scheme **RSA/ECB/PKCS1Padding** and a public key when I an trying to decrypt the response using crypto.privateDecrypt using a private key it is throwing error 

**crypto.privateDecrypt throwing Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error**

### Minimal Reproduction

Java Code Snippet to encrypt the response:
```
private String getRequestkey(String randomNUmber) throws NoSuchAlgorithmException, NoSuchPaddingException,
InvalidKeyException, IllegalBlockSizeException, BadPaddingException, InvalidKeySpecException, IOException {
Cipher ci = Cipher.getInstance("RSA/ECB/PKCS1Padding");

X509Certificate cert = getCertificate(PUBLIC_CERTIFICATE);
ci.init(Cipher.ENCRYPT_MODE, cert.getPublicKey());

byte[] input = randomNUmber.getBytes("UTF-8");
String key = Base64.getEncoder().encodeToString(ci.doFinal(input));

logger.info("encrytpedKey " + key);
return key;
}
```
Crypto decryption:
```
function rsaDecryptNew(privateKey, encryptedData) {
  const decryptedData = crypto.privateDecrypt(
    {
      key: buildPrivateKey(privateKey),
      padding: crypto.constants.RSA_PKCS1_PADDING,
    },
    Buffer.from(encryptedData, 'base64'),
  );

  return decryptedData.toString('utf8');
}

function buildPrivateKey(privateKey) {
  const privateKeyBuffer = Buffer.from(privateKey, 'base64');
  return crypto.createPrivateKey({ key: privateKeyBuffer, format: 'der', type: 'pkcs8' });
}
```

### Output

```
node:internal/crypto/cipher:79
    return method(data, format, type, passphrase, buffer, padding, oaepHash,
           ^

Error: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error
```

### Before You Submit

- [x] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Hi! The version of node you are using is EoL, can you reproduce in a supported Node.js version?

**Comment by RedYetiDev** [comment]
@preveen-stack FWIW it seems like this isn't specific to windows, but instead the way crypto is used

**Comment by RedYetiDev** [comment]
I'm glad to fixed your problem!
