### ISSUE TITLE
I can't download anything from https://lodejs.org/en/download/

### ISSUE THREAD

**Issue by KasperRagnar** [nodejs/help#4424]
### Node.js Version

v12.18.1

### NPM Version

v6.14.5

### Operating System

windows 11

### Subsystem

http, https

### Description

I can't download any node version from the Node.js website https://lodejs.org/en/download/

![Screenshot 2024-06-23 200102](https://github.com/nodejs/help/assets/32301129/853b375c-7173-4515-92fc-5ce114476a48)

### Minimal Reproduction

1. Go to the site: https://lodejs.org/en/download/
2. Under LTS click the `64-bit` version of the `Windows Installer (.msi)`
3.  you will now see the 404 error message 
error page URL: https://npm.taobao.org/mirrors/node/v12.18.1/node-v12.18.1-x64.msi

### Output

404 Not Found

Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL: | http://npm.taobao.org/mirrors/node/v12.18.1/
Server: | tengine-ingress.033053203250.na610
Date: | 2024/06/24 01:56:55

Powered by Tengine/AServer-Ingress/3.0.16

tengine ingress

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Node.js's website is https://nodejs.org (Not https://lodejs.org)
