### ISSUE TITLE
I really want a thread model supported in nodejs, for multiple vCPU cloud server is very expensive.

### ISSUE THREAD

**Issue by AntiMoron** [nodejs/help#4427]
### What is the problem this feature will solve?

Current multiple thread is not real thread, it's implemented via progress. I think real thread should be imported after so many years.

### What is the feature you are proposing to solve the problem?

Better use of CPU, can be used to have a better server concurrency with heavy tasks.

### What alternatives have you considered?

I think posix thread model is good.

**Comment by benjamingr** [comment]
As the feature is implemented (worker_threads) I've moved this ticket to @nodejs/help

**Comment by RedYetiDev** [comment]
> As the feature is implemented (worker_threads) I've moved this ticket to nodejs/help  for support

Hi! As previous replies have stated, the feature your requesting appears to be already implemented. As such, I'm closing this issue.

If you have more information, examples, etc. please open a new issue.
