### ISSUE TITLE
PROTOCOL_CONNECTION_LOST

### ISSUE THREAD

**Issue by uds214125** [nodejs/help#443]
Hi,
I am new in nodejs with mysql. I have created one chat application where mysql server always after some minutes ( not exactly) sent the [Error: Connection lost: The server closed the connection.] fatal: true, code: 'PROTOCOL_CONNECTION_LOST'], so I want to know about the PROTOCOL_CONNECTION_LOST. What is the max idle time for connection lost ? and how to handle this?

**Comment by gibfahn** [comment]
See linked issue: https://github.com/nodejs/node/issues/10835

**Comment by dody87** [comment]
There is no solution for it yet? Is there a way to avoid connection lost ? It's not a critical issue but in my servers there are some catching error tools and these are reporting this error every time.

Thanks.

`{"line_number":975,"file_name":"_stream_readable.js"},{"line_number":80,"file_name":"internal/process/next_tick.js"},{"line_number":128,"file_name":"internal/process/next_tick.js"}],"code":"PROTOCOL_CONNECTION_LOST","fatal":true,"message":"Connection lost: The server closed the connection.","stack":"Error: Connection lost: The server closed the connection.\n    at Protocol.end (/home/gambar/domains/api-qa.gambar.com.ar/public_html/node_modules/mysql/lib/protocol/Protocol.js:113:13)\n    at Socket.<anonymous> (/home/gambar/domains/api-qa.gambar.com.ar/public_html/node_modules/mysql/lib/Connection.js:109:28)\n    at emitNone (events.js:91:20)\n    at Socket.emit (events.js:188:7)\n    at endReadableNT (_stream_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"}`
