### ISSUE TITLE
Handling "Unhandled 'error' event emitted"

### ISSUE THREAD

**Issue by AlexDiego123** [nodejs/help#4441]
### Node.js Version

v20.10.0

### NPM Version

v10.8.1

### Operating System

Linux alexraspi 6.8.0-1006-raspi #6-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 17 11:30:51 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Subsystem

Other

### Description

I'm having trouble handling this error and i can't figure this out. This error occurs when my discord bot created with the discord.js loses internet for a bit when my router restarts. The strange thing is that i have another bot on the same server with the same dependency version but this error is not happening there. I already tried to ask in discord.js's discord server but they told me it isn't related to discord.js. This seems to be something happening in the undici package but anyways the stack trace in the error isn't really helpful and i can't figure out i way to handle this error and make the process not exit. I already tried handling it from discord.js and handling it with process.on('error') because i thought that the event was called like that because in the error it says `Unhandled 'error' event emitted`. Is there a way to make it not throw this error or if not is there a way to handle this so that the process doesn't exit? This error was also documented in https://stackoverflow.com/questions/50531293/node-js-unhandled-error-event and someone said to handle it with client.on('error', (err) => { ... }) but i already tried and it doesn't work for me.

### Minimal Reproduction

Create a simple bot with discord.js (my discord.js version is v14.15.3) as documented in the discord.js guide (https://https://discordjs.guide/) and then remove internet connection for like 5 minutes and then reconnect internet. The normal outcome should be that no errors are thrown and the bot reconnects as soon as internet is available, instead my bot throws this error and crashes and i want to make it not throw this error or at least not crash.

### Output

https://pastebin.com/Vbu8pvg8

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Hi! It seems you are reporting an issue with a library, `discord.js`. This is the support issue tracker for the Node.js core. If you are having issues with a third-party dependency, please reach-out to it's maintainers for support.
