### ISSUE TITLE
TZ env variable is not working properly since Mexico remove DST

### ISSUE THREAD

**Issue by zurielbf** [nodejs/help#4443]
### Node.js Version

v16.17.1

### NPM Version

8.15.0

### Operating System

Windows 11 Home Single Language 23H2

### Subsystem

Other

### Description

Since Mexico goverment removes DST last year one of my app still in qa is presenting a lot of issues reported by multiple users because the timestamps are not correct. Mexico are supoused to be:

Current Offset: | UTC/GMT -6 hours

but when I log the current offset in my nodeJs backend I got the following offset

America/Mexico_City 300

and my .env file is configured like this.

TZ='America/Mexico_City'

### Minimal Reproduction

Set TZ env variable to 'America/Monterrey' or 'America/Mexico_City' and log the (new Date().getTimezoneOffset())

### Output

300 (5 hours equivalent)

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by zurielbf** [comment]
attached a tool for easy replication.

https://www.jdoodle.com/ia/16NS

**Comment by RedYetiDev** [comment]
Node.js v16 has reached EoL.

Also, ICU controls Date/Time data, so this isn't actionable on Node.js's side.

CC @nodejs/i18n-api for confirmation on that information.
