### ISSUE TITLE
Error while open exe file

### ISSUE THREAD

**Issue by Usamarajputrok** [nodejs/help#4445]
### Description of the problem

Microsoft Windows [Version 10.0.19045.4651]
(c) Microsoft Corporation. All rights reserved.

D:\New folder>my-bot.exe
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module 'C:\snapshot\dist\index.js'
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)←[39m
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
←[90m    at Module._load (node:internal/modules/cjs/loader:787:27)←[39m
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

Node.js v18.5.0

D:\New folder>

**Comment by Usamarajputrok** [comment]
> can a member transfer this to nodejs/help?
> 
> Can you provide information such as how you generated the exe, if you can reproduce in a js file, etc?

This is my project which is in ts then convert it into js then i convert it into exe

**Comment by RedYetiDev** [comment]
Can you provide a minimal reproducible example?

**Comment by Usamarajputrok** [comment]
> Can you provide a minimal reproducible example?
> 
> In JavaScript, not TypeScript.

https://drive.google.com/file/d/1xRjS9Gtymw46tmsoR25FVqsbfDWaiffa/view?usp=drive_link Here is complete project without modules

**Comment by RedYetiDev** [comment]
Can you provide a minimal reproducible example using Markdown code snippets, not the entire project.

If you can't reproduce minimally/without dependencies, it'll be hard to diagnose the issue.

**Comment by Usamarajputrok** [comment]
> Can you provide a minimal reproducible example using Markdown code snippets? not the entire project.
> 
> If you can't reproduce minimally/without dependencies, it'll be hard to diagnose the issue.

Sir you want to see mu dependencies or what ?

**Comment by RedYetiDev** [comment]
> Sir you want to see mu dependencies or what ?

In order to reproduce, it would be easiest if you provided a small snippet of code that clearly reproduces the error, preferably without dependencies.

**Comment by Usamarajputrok** [comment]
> > Sir you want to see mu dependencies or what ?
> 
> In order to reproduce, it would be easiest if you provided a small snippet of code that clearly reproduces the error, preferably without dependencies.

Can i show you at ultra viewer please

**Comment by RedYetiDev** [comment]
> Can i show you at ultra viewer please 

this is a help tracker, so if you need to use a third party method to communicate, other forums may be better.

Can you provide a minimal reproducible example? If not, there's no way to know what went wrong, so this issue isn't actionable.

**Comment by RedYetiDev** [comment]
Do you still require assistance?

**Comment by Usamarajputrok** [comment]
> Do you still require assistance?

Yes i need sir but how i can give you example. You want to see my package.json or what
I am using environment variables in my projects also to give path to opencv

**Comment by RedYetiDev** [comment]
Okay, if you having issues making a reproducible example, try breaking down the problem.

Does your code work if you don't compile it to an EXE, but just leave it as JS?

**Comment by Usamarajputrok** [comment]
> Do you still require assistance?

https://github.com/daniellwdb/rok-title-keeper.git  This that’s project github repository

**Comment by Usamarajputrok** [comment]
> Okay, if you having issues making a reproducible example, try breaking down the problem.
> 
> Does your code work if you don't compile it to an EXE, but just leave it as JS?

Yes my codes work fine . But when I convert it with pkg tool to exe then it’s show error

**Comment by RedYetiDev** [comment]
How are you converting the project to an exe?

**Comment by Usamarajputrok** [comment]
I am using pkg tool to convert it to the exe

wait let me give you modify package.json

**Comment by RedYetiDev** [comment]
> I am using pkg tool to convert it to the exe

I don't know what the is. Can you provide the exact steps you're taking?

**Comment by Usamarajputrok** [comment]
> > I am using pkg tool to convert it to the exe
> 
> Do you mean the NPM package `pkg`?

Yes

**Comment by RedYetiDev** [comment]
If your issue is with the `pkg` library, please file and issue with its maintainers. This repository is for help with the Node.js core functionality, not third-party dependencies.
