### ISSUE TITLE
Issue downloading yaml file

### ISSUE THREAD

**Issue by dadasaheb-acn** [nodejs/help#4446]
### Node.js Version

v20.15.0

### NPM Version

v10.7.0

### Operating System

Microsoft Windows NT 10.0.22621.0 x64

### Subsystem

https

### Description

Hi,
I am trying to download a yaml file from GitHub repository, however when the file is downloaded it always comes with the header as 'text/html', hence I cannot use this file for further processing. What I need is the yaml in as-is format so I can use it further. I also tried using axios.get(), fetch(yamlUrl), https.get()  but still same issue. Could you please guide me if I am missing something here. Below are the code snippets that I tried:

const express = require('express');
const bodyParser = require('body-parser');
const { exec } = require('child_process');
const path = require('path');
const fetch = require('node-fetch');
const fs = require('fs');

const app = express();
const port = 5000;

app.use(bodyParser.json());

// Endpoint to trigger code generation
app.post('/generate-code', async (req, res) => {
    const { yamlUrl } = req.body;

    try {
        // Fetch the YAML file from the provided URL
        const response = await fetch(yamlUrl);
        const yamlContent = await response.text();

        // Save the YAML file locally
        const yamlFilePath = path.join(__dirname, 'api-definition.yaml');
        fs.writeFileSync(yamlFilePath, yamlContent);

        // Run the OpenAPI Generator CLI command
        const outputDir = path.join(__dirname, 'generated-code');
}

Second approach:
const axios = require('axios');
const fs = require('fs');
const path = require('path');

const url = 'https://github.com/.../Test.yaml'; 
const outputPath = path.join(__dirname, 'downloaded.yaml');

async function downloadYamlFile(url, outputPath) {
  try {
    //const response = await axios.get(url, { responseType: 'arraybuffer' });
	//const response = await axios.get(url, { responseType: 'stream' });
	const response = await axios.get(url, { headers: {'Accept': 'text/yaml',} });
    if (response.headers['content-type'] === 'application/x-yaml' || response.headers['content-type'] === 'text/yaml') {
      fs.writeFileSync(outputPath, response.data);
      console.log('File downloaded and saved as', outputPath);
    } else {
      console.error('The fetched content is not a YAML file.');
    }
  } catch (error) {
    console.error('Error fetching the file:', error);
  }
}

downloadYamlFile(url, outputPath);

3rd approach:
const https = require('https');
const fs = require('fs');
const url = 'https://github.com/...../Test.yaml'

https.get(url, (response) => {
	const filePath = fs.createWriteStream('file.yaml');
	response.pipe(filePath);
	filePath.on('finish',() => {
		filePath.close();
		console.log('Download Completed');
	});
}).on('error', (error) => {
	console.log('Error ', error.message);
});

4th option:

const axios = require('axios');
const fs = require('fs');
const path = require('path');

async function downloadYamlFile(fileUrl, outputLocationPath) {
	const writer = fs.createWriteStream(outputLocationPath);
	
	return axios({
		method: 'get',
		url: fileUrl,
		responseType: 'stream',
	}).then(response => {
		response.data.pipe(writer);
		return new Promise((resolve, reject) => {
			writer.on('finish', resolve);
			writer.on('error', reject);
		})
	})
	
}

const fileUrl = 'https://github.com/bian-official/public/blob/main/release12.0.0/semantic-apis/oas3/yamls/Loan.yaml';
const outputLocationPath = path.resolve(__dirname, 'file.yaml');

downloadYamlFile(fileUrl, outputLocationPath).then(() => console.log('Download success')).catch(error => console.error('Error', error));

I also tried setting the headers:
return axios({
		method: 'get',
		url: fileUrl,
		headers: {
			'Accept': 'application/x-yaml'
		},
		responseType: 'stream',
	})

Downloaded file shows below content instead of yaml file:

``
"!DOCTYPE html>
html
  lang="en"
  
  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"
  data-a11y-animated-images="system" data-a11y-link-underlines="true"
  >

  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
  <link rel="preconnect" href="https://github.githubassets.com" crossorigin>
  <link rel="preconnect" href="https://avatars.githubusercontent.com">"

  
``

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
This issue is not with Node.js core, but with the way you are using it.

You are downloading `https://github.com/bian-official/public/blob/main/release12.0.0/semantic-apis/oas3/yamls/Loan.yaml`, when the file to download is hosted at `https://raw.githubusercontent.com/bian-official/public/main/release12.0.0/semantic-apis/oas3/yamls/Loan.yaml`

**Comment by dadasaheb-acn** [comment]
Ok Thanks for your response.
