### ISSUE TITLE
stream.pipeline adds many close listeners, which can easily lead to MaxListenersExceededWarning

### ISSUE THREAD

**Issue by selimb** [nodejs/help#4448]
### Node.js Version

v22.4.1

### NPM Version

10.8.1

### Operating System

Linux gw18976 6.6.6-76060606-generic #202312111032~1702306143~22.04~d28ffec SMP PREEMPT_DYNAMIC Mon D x86_64 x86_64 x86_64 GNU/Linux

### Subsystem

stream

### Description

When using `stream.pipeline` to pipe an `http(s).IncomingMessage` into an `http(s).ServerResponse`, a large number (7) of `close` event listeners are added to the `ServerResponse`. When other things are already listening on `close` -- such as the nextjs server, which seems to add 4 -- this can easily lead to the following warning:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners 
added to [ServerResponse]. Use emitter.setMaxListeners() to increase limit
```

I know I can simply increase the limit to `setMaxListeners`, but feel like 7 listeners is a lot. I feel like this is the perfect use-case for `stream.pipeline` (see minimal reproduction below), but maybe I'm wrong?

### Minimal Reproduction

Run this in one terminal:
```javascript
const http = require("http");
const { pipeline } = require("stream");
const { pipeline: pipelinePromise } = require("stream/promises");

const axios = require("axios");

const PROXY_URL = "http://httpbin.org/get";

const proxyHttps = (req, res) => {
  // Omitting a lot of error-handling here
  const reqProxy = http.request(PROXY_URL, {}, (resProxy) => {
    console.info(
      "listenerCount close BEFORE PIPELINE",
      res.listenerCount("close") // 0
    );

    pipeline(resProxy, res, (err) => {
      console.error("pipeline error", err);
    });

    console.info(
      "listenerCount close AFTER PIPELINE",
      res.listenerCount("close") // 7
    );
  });
  reqProxy.end();
};

const proxyFetch = async (req, res) => {
  const resProxy = await fetch(PROXY_URL);
  console.info(
    "listenerCount close BEFORE PIPELINE",
    res.listenerCount("close") // 0
  );
  const p = await pipelinePromise(resProxy.body, res);
  console.info(
    "listenerCount close AFTER PIPELINE",
    res.listenerCount("close") // 3
  );
  await p;
};

async function main() {
  const shutdown = () => process.exit(0);
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  const server = http.createServer(proxyHttps);
  // const server = http.createServer(proxyFetch);

  const port = 7777;
  server.listen(port);
  console.info(`Listening on http://localhost:${port}`);
}

if (require.main === module) {
  void main();
}
```
And call `curl localhost:7777` in another.

### Output

With `proxyHttps`:
```
$ node index.js
Listening on http://localhost:7777
listenerCount close BEFORE PIPELINE 0
listenerCount close AFTER PIPELINE 7
```
With `proxyFetch` instead:
```
$ node index.js
Listening on http://localhost:7777
listenerCount close BEFORE PIPELINE 0
listenerCount close AFTER PIPELINE 3
```

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
@nodejs/streams

**Comment by mcollina** [comment]
Those listeners are needed to handle all the various edge cases that are needed. I'm not sure this is fixable in any way for us.
