### ISSUE TITLE
npm run dev command is not working

### ISSUE THREAD

**Issue by rizwanshah1098** [nodejs/help#4453]
### Version

v22.5.1

### Platform

```text
Visual Studo terminal
```

### Subsystem

Visual Studio 

### What steps will reproduce the bug?

I try to install install tailwind css using post css
1-Install Tailwind CSS
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init

2-Add Tailwind to your PostCSS configuration
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  }
}
3-Configure your template paths
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
}

4-Add the Tailwind directives to your CSS
5-Start your build process
npm run dev

### How often does it reproduce? Is there a required condition?

When run this command showing only single time

### What is the expected behavior? Why is that the expected behavior?

<h1 class="text-3xl font-bold underline">
    Hello world!
  </h1>
Tailwind classes should be working

### What do you see instead?

Just simple text hello world

**Comment by rizwanshah1098** [comment]
You've not any solution?

**Comment by preveen-stack** [comment]
https://tailwindcss.com/docs/installation/using-postcss


> Are you stuck? Setting up Tailwind with PostCSS can be a bit different across different build tools. Check our framework guides to see if we have more specific instructions for your particular setup.
> [Explore our framework guides](https://tailwindcss.com/docs/installation/framework-guides)

Perhpas the framework guides mentioned in tailwind website can give you some pointers

**Comment by RedYetiDev** [comment]
If you're facing an issue with a specific library, in this case Tailwind, I suggest opening an issue with the project itself before opening one here. Thank you!
