### ISSUE TITLE
Cannot test locally committed code to Node.js in my PC.

### ISSUE THREAD

**Issue by ayan-de** [nodejs/help#4456]
### Node.js Version

v20.15.0

### NPM Version

10.8.2

### Operating System

Linux ayan-de 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Subsystem

buffer

### Description

I just cloned my node.js forked repo and I have built it using ninja following the [guideline](https://github.com/nodejs/node/blob/main/doc/contributing/building-node-with-ninja.md) resulting creation of a node binary file in my repo. I made some commits in the source code but how will I test if my code is running fine or not? I want to run my new committed source code. Can anyone help me with this? I have followed all the steps involved in [BUILDING Nodejs](https://github.com/nodejs/node/blob/main/BUILDING.md) and am not sure if my built was perfect or not (how would I know that?? )

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by preveen-stack** [comment]
After the build process completes, the Node.js binary will be located at out/Release/node.

**Comment by ayan-de** [comment]
yes it is present there! now how will i test my code??
Like i have made changes how will i run it to see if the function is working perfectly?
![Screenshot from 2024-07-27 13-04-38](https://github.com/user-attachments/assets/cc30ca75-bae2-470b-9599-84a131ad43ae)

**Comment by preveen-stack** [comment]
I guess you mean the command, right?
`./out/Release/node script.js`

**Comment by ayan-de** [comment]
after every time i change the code will it get reflected in this **`./out/Release/node`**  or i have to `make` it again ?

**Comment by preveen-stack** [comment]
You have to rebuild after every change

**Comment by ayan-de** [comment]
![Screenshot from 2024-07-27 15-53-25](https://github.com/user-attachments/assets/8f7ab0d3-8129-4387-96c3-fd7b5eca1e33)
btw this is how i am running it copy.js file is at another location

**Comment by ayan-de** [comment]
Thanks its working

**Comment by preveen-stack** [comment]
https://github.com/nodejs/node/blob/main/BUILDING.md#installing-nodejs

Check this if you want to replace the system binary with your custom version
