### ISSUE TITLE
"-sh: ./node: not found"  on ARM platform

### ISSUE THREAD

**Issue by dounsm** [nodejs/help#4457]
### Node.js Version

v20.15.1

### NPM Version

8.5.1

### Operating System

Linux JDCAX1800-3968 4.4.60 #1 SMP PREEMPT Thu Mar 21 07:18:39 CST 2024 armv7l ASUSWRT

### Subsystem

Other

### Description

I got `node-v20.15.1-linux-armv7l` from the official site
When I tried to run it on my ARM device I got this
```sh
-sh: ./node: not found
```
The program is indeed in this directory, but it does not run. 
I found out from the Internet that the system lacks the necessary runtime libraries. 
Again, this embedded device wouldn't allow me to change the files in the root directory, 
so I had to try re-static compilation.
And it also didn't work
(More information can be found at [Failed to cross-complie fully-static nodejs with arm-linux-gnueabihf complier #4449](https://github.com/nodejs/help/issues/4449) )

By the way, here is what's in the `/lib` 
```sh
administrator@JDCAX1800-3968:/jffs/myprogs/node-v20.15.1-linux-armv7l/bin# ls /lib -alh
drwxr-xr-x    7 administ root         294 Mar 21 07:43 .
drwxr-xr-x   20 administ root         356 Mar 21 07:43 ..
drwxr-xr-x    6 administ root         207 Mar 21 07:42 firmware
drwxr-xr-x    2 administ root          36 Mar 21 07:42 functions
lrwxrwxrwx    1 administ root           7 Mar 21 07:43 ld-musl-arm.so.1 -> libc.so
-r-xr-xr-x    1 administ root        9.1K Mar 21 07:42 libasuslog.so
-r-xr-xr-x    1 administ root      441.5K Mar 21 07:43 libc.so
-r-xr-xr-x    1 administ root      114.8K Mar 21 07:43 libdisk.so
-r-xr-xr-x    1 administ root       41.8K Mar 21 07:43 libgcc_s.so.1
lrwxrwxrwx    1 administ root          15 Mar 21 07:42 libi2c.so -> libi2c.so.0.1.0
lrwxrwxrwx    1 administ root          15 Mar 21 07:42 libi2c.so.0 -> libi2c.so.0.1.0
-r-xr-xr-x    1 administ root        5.2K Mar 21 07:42 libi2c.so.0.1.0
-r-xr-xr-x    1 administ root       24.4K Mar 21 07:42 libiw.so.29
-r-xr-xr-x    1 administ root       47.8K Mar 21 07:42 libws.so
drwxr-xr-x    3 administ root          29 Mar 21 07:43 modules
drwxr-xr-x    3 administ root          28 Mar 21 07:42 netifd
drwxr-xr-x    2 administ root          74 Mar 21 07:42 wifi
```

### Minimal Reproduction

Just use `./node`

### Output

-sh: ./node: not found

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Running a command beginning with `./` will execute a local file. If that file doesn't exist, the error is thrown.

Make sure Node.js is present at the path you are trying to execute it from
