### ISSUE TITLE
TENTANDO INSTALAR O YARN 

### ISSUE THREAD

**Issue by Halves12** [nodejs/help#4459]
### Node.js Version

v22.5.1

### NPM Version

10.8.2

### Operating System

windows 10

### Subsystem

dns, http, https

### Description

Estou tentando instalar o Yarn , mas esta ocorrendo erro 

### Minimal Reproduction

 utilizando:   npm install --global yarn

### Output

PS C:\WINDOWS\system32> npm install --global yarn
npm error code ENOTFOUND
npm error syscall getaddrinfo
npm error errno ENOTFOUND
npm error network request to https://registry.npmjs.org/yarn failed, reason: getaddrinfo ENOTFOUND proxy-host
npm error network This is a problem related to network connectivity.
npm error network In most cases you are behind a proxy or have bad network settings.
npm error network
npm error network If you are behind a proxy, please make sure that the
npm error network 'proxy' config is set properly.  See: 'npm help config'
npm error A complete log of this run can be found in: C:\Users\hugop\AppData\Local\npm-cache\_logs\2024-07-29T00_05_32_811Z-debug-0.log

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
This is a network issue, and not an issue with Node itself.

```
npm error network This is a problem related to network connectivity.
npm error network In most cases you are behind a proxy or have bad network settings.
npm error network
npm error network If you are behind a proxy, please make sure that the
npm error network 'proxy' config is set properly. See: 'npm help config'
