### ISSUE TITLE
Using official guide - Failed to install using 'fnm' CLI command on Win11 using PowerShell 7.4.4 

### ISSUE THREAD

**Issue by KfearO** [nodejs/help#4460]
### Node.js Version

v22.5.1

### NPM Version

10.8.2

### Operating System

Windows 11 Pro 23H2 OS Build 22631.3880

### Subsystem

path

### Description

Failed to install using CLI process found here:
https://nodejs.org/en/download/package-manager/current

### Minimal Reproduction

Follow instruction found here:
https://nodejs.org/en/download/package-manager/current

```
# installs fnm (Fast Node Manager)
winget install Schniz.fnm

# download and install Node.js
fnm use --install-if-missing 22

# verifies the right Node.js version is in the environment
node -v # should print `v22.5.1`

# verifies the right npm version is in the environment
npm -v # should print `10.8.2`
```

### Output

```
PowerShell 7.4.4
PS C:\Windows\System32> winget install Schniz.fnm
Found Fast Node Manager [Schniz.fnm] Version 1.37.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Path environment variable modified; restart your shell to use the new value.
Command line alias added: "fnm"
Successfully installed
PS C:\Windows\System32> fnm use --install-if-missing 22
fnm: The term 'fnm' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32>
```

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by htrahddis-hub** [comment]
Hey @KfearO,
I followed the instruction given [https://nodejs.org/en/download/package-manager/current](https://nodejs.org/en/download/package-manager/current),

in the output you provided it says to restart your PowerShell.
did you do that?? bcz I did that and it works.

**Comment by KfearO** [comment]
yes I did. I pasted the wrong output:

```
PowerShell 7.4.4
PS C:\Users\Kfear> fnm use --install-if-missing 22
error: We can't find the necessary environment variables to replace the Node version.
You should setup your shell profile to evaluate `fnm env`, see https://github.com/Schniz/fnm#shell-setup on how to do this
Check out our documentation for more information: https://fnm.vercel.app
```

**Comment by RedYetiDev** [comment]
Node.js does not official distribute fnm. If you need help with it, please contact its maintainers.
