### ISSUE TITLE
Asserting a range with descriptive error messages 

### ISSUE THREAD

**Issue by nicholaswmin** [nodejs/help#4461]
### Node.js Version

v22

### NPM Version

10.8.2

### Operating System

MacOS Sonoma

### Subsystem

assert

### Description

I work a lot with performance testing code which frequently leads in the unfortunate position where I need to assert *ranges* rather than *exact* values, i.e

is `value` between `1500` and `2000`?

Now, to do that I use a pair of `assert.ok` like so: 

```js
const value = 1700

assert.ok(value >= 1500)
assert.ok(value <= 2000)
```

so far so good, could be better but that's clean and concise enough for my taste.

The problem is that setting a descriptive error message quickly becomes rather repetitive and convoluted. 

I have to resort to something akin to this:

```js
assert.ok(value >= 1500, `expected value >= 1500 , got: ${value}`)
assert.ok(value <= 2000, `expected value <= 2000 , got: ${value}`)
``` 

Apart from cooking up my own assertion functions, is there a better way to do this out-the-box that I'm missing?

**Comment by RedYetiDev** [comment]
CC @nodejs/assert

**Comment by gireeshpunathil** [comment]
looks reasonable to me!

**Comment by gireeshpunathil** [comment]
@nicholaswmin - pls feel free to raise a PR if you are willing to!

**Comment by RedYetiDev** [comment]
Although, doesn't the assert message include the failed assertion line, so wouldn't it already show the failure?

**Comment by nicholaswmin** [comment]
@RedYetiDev here's the output:

```js
import test from 'node:test'

await test('is within range',  async t => {
  const value = 2700
  
  t.assert.ok(value >= 1500)
  t.assert.ok(value <= 2000)
})
```

```test
✖ is within range (1.220792ms)
  AssertionError [ERR_ASSERTION]: false == true
      at assert.<computed> [as ok] (node:internal/test_runner/test:261:18)
      at TestContext.<anonymous> (file:///Users/nicholaswmin/Projects/fsm/scratch.js:7:12)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:878:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:590:18)
      at node:internal/test_runner/harness:252:20
      at node:internal/process/task_queues:151:7
      at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:148:8) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  }
```

My "complaint" is that it doesn't print `value` being asserted against, unless I specifically code it to so with that string interpolation.

Now granted, the above is impossible to do with the code I'm providing because that's a Boolean expression. 
An ideal API might be something like:

```js
  t.assert.ok(value <= 2000, value)
  t.assert.ok(value <= 2000, value)
```

  AssertionError [ERR_ASSERTION]: Failed, value: 2700 was not ok


Hmm.. I'm a bit confused... Not sure why I opened this issue  as what I'm proposing sounds like a silly API

**Comment by RedYetiDev** [comment]
`assert.isGreaterThan` could work if you'd like to add it?

**Comment by nicholaswmin** [comment]
I'm personally against adding specific assertion checks to `assert` like that because it'll eventually snowball into a myriad utilities.

I don't remember what i had in mind when i opened this. Sorry.

**Comment by nicholaswmin** [comment]
The closest thing I can figure out that would help without adding specific assertion checks is printing the expression itself on `assert.ok()`. 

An example: 

```js
import test from 'node:test'

await test('foo', async t => {
  const value = 2700
  
  t.assert.ok(value >= 1500, { range: 1500, value })
  t.assert.ok(value <= 2000, { range: 2000, value })
})

```

logs:

```text
✖ is in range (1.220875ms)
  AssertionError [ERR_ASSERTION]: `value >= 1500`
      at assert.<computed> [as ok] (node:internal/test_runner/test:261:18)
      at TestContext.<anonymous> (file:///Users/nicholaswmin/Projects/fsm/scratch.js:7:12)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:878:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:590:18)
      at node:internal/test_runner/harness:252:20
      at node:internal/process/task_queues:151:7
      at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:148:8) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  }

```

Is that even doable?

**Comment by RedYetiDev** [comment]
For your specific case, a custom error (E.G. `throw new assert.AssertionError({actual: 1, expected:2, operator:">="})`) can be thrown.

> Not sure if that's doable without doing esprima-like parsing though?

In some cases, that is what happens:

```mjs
import assert from 'node:assert';

assert.ok(25 > 50);
```
```
node:internal/modules/run_main:123
    triggerUncaughtException(
    ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(25 > 50)

    at file:///Users/avivkeller/Documents/tmp/repro.mjs:3:8
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v22.8.0
```

**Comment by nicholaswmin** [comment]
> In some cases, that is what happens:


Yes. That works! I can repro it with `assert` but not with `t.assert`

**Comment by RedYetiDev** [comment]
I'm aware. I'm opening an issue for it as we speak.

**Comment by RedYetiDev** [comment]
If you'd like, see https://github.com/nodejs/node/issues/54760

**Comment by RedYetiDev** [comment]
Fixed in #54776

**Comment by nicholaswmin** [comment]
Amazing; sorry, life got in the way ...

**Comment by gireeshpunathil** [comment]
@nicholaswmin - is your proposal addressed? can this be closed now as resolved?
