### ISSUE TITLE
Test reporter spec has duplicate test titles

### ISSUE THREAD

**Issue by nicholaswmin** [nodejs/help#4468]
### Node.js Version

v22.6

### NPM Version

10.8.2

### Operating System

Mac OS Sonoma

### Subsystem

[Test Runner](https://nodejs.org/api/test.html)

### Description

The default [`spec` test reporter](https://nodejs.org/api/test.html#test-reporters) prints duplicate test titles for some reason.   
I guess that's expected but not clear why, nor documented. 

I write my tests in a way that resembles Cucumber BDD specs - reading it back is essential to making sure I've covered
my requirements. This duplication makes it awkward to read.

### Minimal Reproduction

Run this with `node --test`:

```js
import test from 'node:test'

test('test', async t => {
  await t.test('if its ok or fine', async t => {    
  
    await t.test('is ok',  t => {
      t.assert.ok(true)
    })
    
    await t.test('is fine', t => {
      t.assert.ok(true)
    })
    
  })
})
```

### Output

```logs
▶ test
  ▶ if its ok or fine   <-- printed title
    ✔ is ok (0.454084ms)
    ✔ is fine (0.051625ms)
  ▶ if its ok or fine (0.834375ms)   <-- same title printed 
▶ test (1.145416ms)
ℹ tests 4
ℹ suites 0
ℹ pass 4
ℹ fail 0
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 52.01175
```

**Comment by RedYetiDev** [comment]
Ill take a look at this later today,

I haven't attempted to reproduce yet, but my assumption is that more than one event being trigged is calling the log.

**Comment by RedYetiDev** [comment]
I've looked into it, and it seems like this was added as an intentional behavior. I'm not saying it's the intended behavior, but it's addition appears to be intentional (at the time it was added). I suggest opening an issue in `nodejs/node` with this.
