### ISSUE TITLE
Error On Download File With Http.Request

### ISSUE THREAD

**Issue by lfernando-silva** [nodejs/help#447]
* **Node.js Version**: 7.4.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: A external HTTP server
* **Module (and version) (if relevant)**: Native HTTP and relateds, such Download and Request.

I'm trying to download a .txt file hosted in a http server in my local network. Although I had used a lot of http request modules, they akways throw an "Parse Error" like this:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Parse Error
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```
The problem is: I can download this file through the browser and even through the Postman app, but even when I use the code provided by postman for native http request, it got Parse Error. In fact, the server response has a lot of problems as it's a legacy hardware (no headers in the response!) but I think it should not be a problem when using request module if can be downloaded in a browser, even in a node-based such Bravo it was possible.

Finally, I made a test http server and everything worked fine. So, initally, my request code are right (but maybe incomplete for this case). 

Can someone give some tip? Here is the code (autogenerated by Postman app)

```
var http = require("http");

var options = {
  "method": "GET",
  "hostname": "192.168.0.105",
  "port": null,
  "path": "/descriptor.txt",
  "headers": {
    "cache-control": "no-cache",
    "postman-token": "a token provided by postman"
  }
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function () {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.end();

```

**Comment by lfernando-silva** [comment]
Just for registry and help other people, the problem is NodeJS doesn't not support HTTP 0.9 requests, there is, HTTP requests with no headers in lower level. In this case, the parse error is similar to HPE_INVALID_CONSTANT and doesn't matter which http request module is used, as all uses http module requests in lower layers.

Otherwise, if this response cames from a embedded system that uses [lwip ](http://www.nongnu.org/lwip/2_0_0/group__httpd__opts.html#ga6f78487bc829f7f98274f1264020045e) library to help in tcp/http layer, maybe using the [makefsfile.exe](https://github.com/hrshygoodness/Luminary-Micro-Library/edit/master/tools/makefsfile/makefsfile.c) to generate the http server, it happens because[ the most commom command is the one that creates the server without the http headers](http://processors.wiki.ti.com/index.php/LAUNCHXL2_570LC43:_lwIP_Active_Webserver_Demo?keyMatch=makefsfile&tisearch=Search-EN). The command:

`$ makefsfile.exe -i fs -o io_fsdata.h -r -h -q`

generates this server with no headers. But seems taking out the -h (using headers), it has some other errors. 

I think the best solution in this cases is to make a raw http request using nodejs net module, writing the http commands by socket.end( ) method.

**Comment by bnoordhuis** [comment]
Node should support HTTP/0.9.  Are you sure the server sends back a valid response?

Quick sanity check:
```
$ node -e 'net.createServer(c => c.end("HTTP/0.9 200 OK\r\n\r\nBye")).listen(8000)'
```
In a second terminal:
```
$ node -e 'http.get("http://127.0.0.1:8000/", res => res.pipe(process.stdout))'
Bye
```

**Comment by lfernando-silva** [comment]
Are this a current HTTP 0.9 server? Because when I made a minimal (deleting the headers manually) http server, it also worked but it sent, at least, the response code (200 OK). But the response code should be in the response body, as serving the static file, because it does not have headers (I'm using [this](http://www.kafsemo.org/2015/01/03_talking-HTTP-0.9,1.0,1.1.html) reference as an example, maybe it's wrong). The [W3 docs](https://www.w3.org/Protocols/HTTP/AsImplemented.html) is not clear about what sould have and what not, but quite descriptive.

I'm saying it based on two points:

1. In [NodeJS docs](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_message_httpversion), it says explicitly about the 1.0 and 1.1 version ("probably") in server response or client request.
2. In [this issue](https://github.com/nodejs/node-v0.x-archive/issues/8514), it is pretty old but someone indicated that possibility (that's what you said was not the case). It is exactly my case for every request-like modules (http, download, got, request, request-promise, request2 and so on).

When I'm using the http client module do make requests, it uses the HTTP parser to do something that fails and then it throws HPE_INVALID_CONSTANTS just in this case (no headers). As said in the issue, it can be a not http request, but how would it work in postman app (just for test http requests), for example? 

So, in my case, nodejs is a client making a request (the minor possible request) to a legacy hardware such as the same case about modbus slave. But the hardware uses a very known C library called lwip, built with makefsfile to create an http server above the tcp layer, but not a REST server. So, I really doubt that the response is the problem, but it can be an unsupported by HTTP response, really. I contacted the legacy hardware developers and they tried to include the headers, but the response got worse. But my question is about where is the "magic" that can be done with postman and even browsers that can't be by nodejs? Just to understand the problem, as I solved this with the sugested net raw requests.

Anyway, I followed the tip in the issue (to use raw tcp requests) and it worked. This is just to understand the problem.

**Comment by bnoordhuis** [comment]
Are you saying the server omits the HTTP/0.9 status line?  If yes, it's no wonder it doesn't work with node; it's not a valid HTTP response.

**Comment by lfernando-silva** [comment]
When they build the server with -h command, it comes with no headers and no response code, just raw data. But is not this how it should be in 0.9? In [w3 docs](https://www.w3.org/Protocols/HTTP/AsImplemented.html), HTTP/0.9 response doesn't contains anything except the body; no error codes neither status line. Messages are sent in the response body as human readable text, but not in headers. Seems it was implemented [later](https://www.w3.org/Protocols/HTTP/HTTP2.html) in early versions of HTTP 1.0.

**Comment by bnoordhuis** [comment]
You have a point there.  Node accepts the "status line without headers" flavor of HTTP/0.9.  A response consisting of just a response body is rejected because in this day and age it's more likely that the response is malformed than that it's a HTTP/0.9 response.

The requirement to support such responses was dropped from the http-bis spec, I expect for that reason.

**Comment by lfernando-silva** [comment]
Really, the "true" 0.9 was abandoned and it remains just for historic purposes (legacy systems), that could be less than 1% of all http request cases (where my case was included). So, this is nodejs expected behavior in fact.

The big tip is to make the raw tcp requests.

Thanks for help and instructions!
