### ISSUE TITLE
Failure To Launch with Environment Value

### ISSUE THREAD

**Issue by rehatkathuria** [nodejs/help#4472]
### Node.js Version

v22.5.1

### NPM Version

10.8.2

### Operating System

Darwin Mac 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 21:29:10 PDT 2024; root:xnu-11215.1.10~5/RELEASE_ARM64_T6031 arm64

### Subsystem

http

### Description

I have the following starting point for a server: 

https://gist.github.com/rehatkathuria/d64904eb27240956f084ae8e93613d7f

The problem is the following:

```
await new Promise<void>((resolve) =>
  httpServer.listen({ port: process.env.PORT, hostname: "0.0.0.0" }, resolve),
);
```

When I have a `PORT` value defined in my environment, I get the following error:

```
$ bun run index.ts
44 | /// Websocket
45 | ws.start();
46 | 
47 | /// Server
48 | 
49 | await new Promise<void>((resolve) =>
               ^
EADDRINUSE: Failed to start server. Is port 4000 in use?
 syscall: "listen"

      at listen (node:http:443:9)
      at new Promise (1:11)
      at /Users/rehat/Developer/Repositories/hock-server/index.ts:49:7

Bun v1.1.22-canary.96+df33f2b2a (macOS arm64)
error: script "start" exited with code 1
```

However, if I manually give the port without the environment as such:

```
await new Promise<void>((resolve) =>
  httpServer.listen({ port: 4000, hostname: "0.0.0.0" }, resolve),
);
```

Everything runs as expected:
```
rehat@Mac 130 -> bun start                                                                                                   hock-server -> main ! $
$ bun run index.ts
Server listening on :::4000
```

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
This is the help repo for Node.js, **not** bun.
