### ISSUE TITLE
The “this wiki” link in this repo’s README is broken

### ISSUE THREAD

**Issue by Jayman2000** [nodejs/help#4476]
### Node.js Version

I don’t have Node.js installed yet.

### NPM Version

I don’t have npm installed yet.

### Operating System

Microsoft Windows 11 Home

### Subsystem

Other

### Description

I don’t actually need help with Node.js at the moment. I just wanted to report a bug with this repo.

This repo’s README has a broken link. Specifically, [the README says:](https://github.com/nodejs/help/blob/9664b94661f00245d245d967968c54413a4b4c0e/README.md#install)

> ## Install
> 
> To install Node.js, check out [this wiki](https://github.com/nodejs/help/wiki/Installation) to learn how to install Node.js via binary archive on Linux and AIX.

When I click the “this wiki” link, it redirects me to this repo’s main page. It does not take me to a wiki that explains how to install Node.js.

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Thanks! I'll fix that ASAP.

**Comment by RedYetiDev** [comment]
See https://github.com/nodejs/help/pull/4477
