### ISSUE TITLE
UDP dgram error on receive message - EINVAL - Azure Web App/Azure Functions

### ISSUE THREAD

**Issue by teresahoes-klf** [nodejs/help#4478]
### Node.js Version

18.20.4

### NPM Version

10.8.1

### Operating System

windows

### Subsystem

dgram

### Description

Hello we recently started having issues with a UDP lookup to a sql server to get named instances within Azure Function Apps and Web apps (after and update to Azure Service Environment v3). We have an open ticket with Microsoft, but I was hoping to get some more information as to what might cause this error to happen so we might be able to narrow the focus with Microsoft. 

This simple code as taken from the node documentation noted below produces the output shown below. 

We are wondering what types of things could cause the "recvmsg EINVALat UDP.onMessage [as onmessage] (node:dgram:938:31)" error noted.  We know via wireshark that the message reaches the sql server and returns the expected packet. But since we are unable to debug w/in the Azure environment, we cannot see what the returned message is (did it get modified somehow) or what is causing the error.  We do not have this issue with regular windows VM's running the same code in azure. 

thank you

### Minimal Reproduction

_const localClientPort = 0;
    const sqlServer = await dnsLookup(sqlServerHostname, { family: 4 });
    const sqlServerPort = 1434;

    const server = dgram.createSocket('udp4');

    server.on('error', (err) => {
        context.log(`Server error:\n${err.stack}`);
        server.close();
    });
    server.on('message', (msg, rinfo) => {
        context.log(`Message received: ${msg} from ${rinfo.address}:${rinfo.port}`);
    });
    server.on('listening', () => {
        const address = server.address();
        context.log(`Listening to: ${address.address}:${address.port}`);
    });
    server.on('connect', () => {
        const address = server.address();
        context.log(`Connected to: ${address.address}:${address.port}`);
    });
    //server.bind({port: localClientPort, exclusive: true});
     context.log('binding...');
    server.bind(localClientPort, function (err, bytes) {
        if (err) {
            context.log(`Bind error:\n${err.stack}`);
            throw err;
        }
        context.log('Socket bound to: ' + sqlServer.address + ':' + sqlServerPort);

    });

    const message = Buffer.from([0x02]);
    
    server.send(message, 0, message.length, sqlServerPort, sqlServer.address, function (err, bytes) {
        if (err) throw err;
        context.log('UDP message sent to ' + sqlServer.address + ':' + sqlServerPort);
    });_

### Output

2024-09-06T17:05:31.716 [Information] binding...
2024-09-06T17:05:31.716 [Information] Listening to: 0.0.0.0:0
2024-09-06T17:05:31.716 [Information] Socket bound to: 172.18.12.14:1434
2024-09-06T17:05:31.716 [Information] UDP message sent to 172.18.12.14:1434
2024-09-06T17:05:31.716 [Information] Server error:Error: recvmsg EINVALat UDP.onMessage [as onmessage] (node:dgram:938:31)

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Can you provide the Node.js debug output? (`NODE_DEBUG=<subsystem|*>` environment variable)

**Comment by teresahoes-klf** [comment]
Here is all the debug output around the call


NET 1876: onconnection
STREAM 1876: read 0
STREAM 1876: need readable false
STREAM 1876: length less than watermark true
STREAM 1876: do read
NET 1876: _read - n 16384 isConnecting? false hasHandle? true
NET 1876: Socket._handle.readStart
HTTP 1876: SERVER new http connection
STREAM 1876: resume
STREAM 1876: resume true
STREAM 1876: flow true
STREAM 1876: read undefined
STREAM 1876: need readable true
STREAM 1876: length less than watermark true
STREAM 1876: reading, ended or constructing false
STREAM 1876: readableAddChunk null
STREAM 1876: onEofChunk
STREAM 1876: emitReadable false false
STREAM 1876: emitReadable null
HTTP 1876: SERVER socketOnParserExecute 1578
STREAM 1876: emitReadable_ false 0 true
STREAM 1876: flow null
TIMER 1876: no 989 list was found in insert, creating a new one
HTTP 1876: write ret = true
HTTP 1876: outgoing message end.
STREAM 1876: onWriteComplete 0 undefined
STREAM 1876: resume
STREAM 1876: resume false
STREAM 1876: read 0
STREAM 1876: endReadable false
STREAM 1876: flow true
STREAM 1876: read undefined
STREAM 1876: endReadable false
STREAM 1876: read 0
STREAM 1876: endReadable false
STREAM 1876: endReadableNT false 0
STREAM 1876: endReadableNT true 0
STREAM 1876: endReadableNT true 0
binding...
Listening to: 0.0.0.0:0
Socket bound to: 172.18.12.14:1434
UDP message sent to 172.18.12.14:1434
Server error:Error: recvmsg EINVAL 
 Error: recvmsg EINVAL
    at UDP.onMessage [as onmessage] (node:dgram:938:31)
binding...
Listening to: 0.0.0.0:0
Socket bound to: 172.18.12.14:1434
UDP message sent to 172.18.12.14:1434
Server error:Error: recvmsg EINVAL 
 Error: recvmsg EINVAL
    at UDP.onMessage [as onmessage] (node:dgram:938:31)
binding...
Listening to: 0.0.0.0:0
Socket bound to: 172.18.12.14:1434
UDP message sent to 172.18.12.14:1434
Server error:Error: recvmsg EINVAL 
 Error: recvmsg EINVAL
    at UDP.onMessage [as onmessage] (node:dgram:938:31)
TIMER 1876: process timer lists 97714
TIMER 1876: timeout callback 989
TIMER 1876: 989 list empty
TIMER 1876: process timer lists 97927
TIMER 1876: timeout callback 5000
TIMER 1876: 5000 list wait because diff is 1144
TIMER 1876: process timer lists 101787
TIMER 1876: timeout callback 5000
NET 1876: _onTimeout
NET 1876: destroy
NET 1876: close
NET 1876: close handle
NET 1876: has server
NET 1876: SERVER _emitCloseIfDrained
NET 1876: SERVER handle? true   connections? 0
TIMER 1876: 5000 list wait because diff is 3623
NET 1876: emit close
HTTP 1876: server socket close
TIMER 1876: process timer lists 103170
TIMER 1876: timeout callback 5000
TIMER 1876: 5000 list empty
TIMER 1876: no 5000 list was found in insert, creating a new one
TIMER 1876: process timer lists 106502
TIMER 1876: timeout callback 30000
TIMER 1876: 30000 list wait because diff is -16
TIMER 1876: process timer lists 108211
TIMER 1876: timeout callback 5000
TIMER 1876: 5000 list empty
TIMER 1876: no 5000 list was found in insert, creating a new one
TIMER 1876: process timer lists 113330
TIMER 1876: timeout callback 5000
TIMER 1876: 5000 list empty
TIMER 1876: no 5000 list was found in insert, creating a new one
TIMER 1876: process timer lists 118371
TIMER 1876: timeout callback 5000
TIMER 1876: 5000 list empty
TIMER 1876: no 5000 list was found in insert, creating a new one

**Comment by teresahoes-klf** [comment]
We received an update from MS - they have determined that they need to make a change in their network code for VNets in Azure Web apps to handle how node processes UDP calls.
