### ISSUE TITLE
Upgrading the outdated node code for build dev machine 

### ISSUE THREAD

**Issue by Madavic51** [nodejs/help#4479]
Hi 
I am trying to upgrade from node 14.x to nodejs20.x
Am trying to run npm install after installation the latest nodej js but it's giving me ETIMEOUT  request to https:registry.npmjs.org failed
I tried seting that but still it didn't work 

And trying to run npm update command it's running since 2 hours in windows.
Need help  to update the outdated node code

**Comment by RedYetiDev** [comment]
Hi!
1. This is an issue with the `npm` client, not Node.js
2. `ETIMEOUT` errors typically are related to your local network configuration. Try connecting to a different network / see if other hosts are connectable.
