### ISSUE TITLE
Getting a segmentation fault with Node.js 6.9.2, Gulp, Socket.io and WebPack bundling

### ISSUE THREAD

**Issue by diasdavid** [nodejs/help#448]
I'm getting a 100% reproducible segmentation fault when using aegir over a module that uses socket.io and attach a `.once` to the client instead of `.on`. Completely lost on why this happens, you can find a repro case here: https://github.com/libp2p/js-libp2p-webrtc-star/pull/83

* **Node.js Version**:
6.9.2
* **OS**:
Mac OS X (but also seeing the same problem in CI that has Linux)
* **Scope (install, code, runtime, meta, other?)**:
runtime - Segfault
* **Module (and version) (if relevant)**:

When transpiling `socketioClient.once`, full context and repro case here:
https://github.com/libp2p/js-libp2p-webrtc-star/pull/83

**Comment by dignifiedquire** [comment]
I can reproduce the same behaviour with `node@7.4.0`

**Comment by stamster** [comment]
Have you tried to run your app on GNU/Linux?

**Comment by dignifiedquire** [comment]
This is my print out for the `find` above:

```bash
> find node_modules/ -name \*.node
node_modules//fsevents/lib/binding/Release/node-v11-darwin-x64/fse.node
node_modules//fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node
node_modules//fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node
node_modules//fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node
node_modules//fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node
node_modules//node-webcrypto-ossl/build/Release/nodessl.node
node_modules//segfault-handler/build/Release/segfault-handler.node
node_modules//wrtc/build/Release/wrtc.node
node_modules//wrtc/build/wrtc/v0.0.61/Release/node-v51-darwin-x64/wrtc.node
```

**Comment by dignifiedquire** [comment]
- segfault-handler is not the problem, as I installed it only after seeing the segfault
- not the problem, it's optional and it still segfaults after removing it:
  - fsevents
  - node-webcrypto-ossl

which leaves `wrtc` in question.

**Comment by bnoordhuis** [comment]
wrtc is a plausible suspect, it uses uv_async_t handles.

**Comment by bnoordhuis** [comment]
More specifically, I see that https://github.com/js-platform/node-webrtc/blob/develop/src/datachannel.cc initializes a uv_async_t handle and ties it to a JS object by means of nan::ObjectWrap, but it never seems to close the handle.  The handle's memory is going to get corrupted when the JS object is gc'd.

**Comment by bnoordhuis** [comment]
I'll close this out.  Left a comment here: https://github.com/js-platform/node-webrtc/issues/278#issuecomment-274277780

**Comment by diasdavid** [comment]
Thank you @bnoordhuis will follow up int the other issue :)
