### ISSUE TITLE
Getting a lot errors, idk why

### ISSUE THREAD

**Issue by C00LVansh** [nodejs/help#4480]
### Node.js Version

v20.17.0

### NPM Version

v10.8.3

### Operating System

Windows 11

### Subsystem

Other

### Description

I am facing this issue: https://pastebin.com/raw/yVe3zzUS
Kindly click here and tell me how to stop it. I have tried reinstalling but it's not working.
It is caused when i try to download any package.

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by C00LVansh** [comment]
New error now, https://pastebin.com/raw/neB8anzr

**Comment by RedYetiDev** [comment]
The errors you are experiencing are regarding npm. Please report issues in npmjs/npm, not nodejs/help.

However, the issues appear to be regarding system commands, so try to figure out what commands are failing, and if there is a reason for that before reporting bugs.
