### ISSUE TITLE
fetch is not defined ReferenceError: fetch is not defined for node 18, Only when hosted on azure static web app, but works in localhost:3000

### ISSUE THREAD

**Issue by daivagna** [nodejs/help#4489]
### Node.js Version

v18.20.3

### NPM Version

v10.2.4

### Operating System

windows

### Subsystem

Other

### Description

Hi Team,

We upgraded from node 16 to node 18, we also have integrated on third party UI kit, Initially we were getting "cannot read properties of undefined("fd") at useColours, but when we removed the reference of external UI kit from server.webpack.config.js and it was resolved

It always worked in our developer's machine, but our site is hosted locally on IIS in our backend developer's machine, so when we host our dist folder there it was not working before, but after removing above UIKit it worked, it also started working on machine with IIS hosting too

Now, issue we are running into is, currently it is working for all of us in localhost:3000 as well as in IIS hosted site too in local, but when we host it on azure static web app for node hosting, it is giving 

"fetch is not defined
ReferenceError: fetch is not defined"

We know that Node18 has native support of fetch we also tried uninstalling "node-fetch" but it gives same error when hosted 

One observation we did was, the server.bundle.js in our local and the build gets generated on upper environment has different server.bundle.js created

is it issue node not able to generate all JS needed to be run in a browser and hence failing or is it issue with node18 which needs to be fixed? Or is it some kind of bundle configuration which is missing?

Help much appreciated !!! As it is blocking our GO LIVE due to team not able to run it and test it

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
Your issue doesn't provide enough information. Fetch is provided as a builtin since v18. Any reason why it wouldn't be defined has to do with user code, or specific flags passed to the process / build.

**Comment by RedYetiDev** [comment]
I'm closing this until more info is provided
