### ISSUE TITLE
why does the order --experimental-sqlite in the CLI matter and how to enable --experimental-sqlite in SAE (Single Application Executable)?

### ISSUE THREAD

**Issue by levislicn** [nodejs/help#4491]
### Version

2.26.6

### What steps will reproduce the bug?

I was able to run with node --experimental-sqlite index.js but failed with node index.js --experimental-sqlite. 
However, I want to make an SAE(Single Application Executable) https://nodejs.org/api/single-executable-applications.html. The resultant exe doesn't support --experimental-sqlite. I don't know how to configure the experimental feature based on the link mentioned.

### How often does it reproduce? Is there a required condition?

issue always occurred.

### What is the expected behavior? Why is that the expected behavior?

The order of --experimental-sqlite in the CLI should not matter. and there should be a way to configure --experimental-sqlite to produce SAE.

### What do you see instead?

![image](https://github.com/user-attachments/assets/4f29c962-1644-4cfe-9cad-1622d4d2fb58)

**Comment by RedYetiDev** [comment]
That makes sense. Any arguments passed **after** the script are arguments to the script, not to Node.js

**Comment by levislicn** [comment]
the first question about the order of --experiment-sqlite is fine, but the main question is how to enable --experimental-sqlite in SAE (Single Application Executable), since node will be copy and embed with a single external js code.
for example，the generated SAE is myapp.exe, how can I use --experiment-sqlite? since myapp.exe is equivalent to node index.js

**Comment by RedYetiDev** [comment]
This is not currently possible. See https://github.com/nodejs/single-executable/issues/100 for the feature request
