### ISSUE TITLE
creating react app

### ISSUE THREAD

**Issue by elorm12345** [nodejs/help#4492]
### Node.js Version

v20.17.0.

### NPM Version

10.8.2

### Operating System

windows 11

### Subsystem

Other

### Description

PS C:\Users\HP\Desktop\my first react> npx create-react-app
npm error code ENOENT
npm error syscall lstat
npm error path C:\Users\HP\AppData\Roaming\npm
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat 'C:\Users\HP\AppData\Roaming\npm'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\HP\AppData\Local\npm-cache\_logs\2024-10-18T12_27_57_804Z-debug-0.log

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by elorm12345** [comment]
i need help asap

**Comment by RedYetiDev** [comment]
Duplicate of https://github.com/nodejs/node/issues/53538
