### ISSUE TITLE
Error in Clone Node 

### ISSUE THREAD

**Issue by sharafabacery** [nodejs/help#4498]
### Node.js Version

v22

### NPM Version

10

### Operating System

windows 10 (x64)

### Subsystem

Other

### Description

using git bash in windows to clone node js runtime by using
`git clone -c core.symlinks=true https://github.com/nodejs/node.git`
give me error

### Output

`Cloning into 'node'...
remote: Enumerating objects: 988910, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (96/96), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2628 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output`

### Before You Submit

- [x] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
This is an issue with the network connection to git, not node itself

**Comment by Domi83s** [comment]
> ### Node.js Version
> v22
> 
> ### NPM Version
> 10
> 
> ### Operating System
> windows 10 (x64)
> 
> ### Subsystem
> Other
> 
> ### Description
> using git bash in windows to clone node js runtime by using `git clone -c core.symlinks=true https://github.com/nodejs/node.git` give me error
> 
> ### Minimal Reproduction
> _No response_
> 
> ### Output
> `Cloning into 'node'... remote: Enumerating objects: 988910, done. remote: Counting objects: 100% (160/160), done. remote: Compressing objects: 100% (96/96), done. error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8) error: 2628 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output`
> 
> ### Before You Submit
> * [x]  I have looked for issues that already exist before submitting this
> * [x]  My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by Domi83s** [comment]
var data; 

  //accepting only JSON messages 
  try { 
     data = JSON.parse(message); 
  } catch (e) { 
     console.log("Invalid JSON"); 
     data = {}; 
  }

  //switching type of the user message 
  switch (data.type) { 
     //when a user tries to login
     case "login": 
        console.log("User logged", data.name); 

        //if anyone is logged in with this username then refuse 
        if(users[data.name]) { 
           sendTo(connection, { 
              type: "login", 
              success: false 
           }); 
        } else { 
           //save user connection on the server 
           users[data.name] = connection; 
           connection.name = data.name; 

           sendTo(connection, { 
              type: "login", 
              success: true 
           }); 
        } 

        break;

     case "offer": 
        //for ex. UserA wants to call UserB 
        console.log("Sending offer to: ", data.name);

        //if UserB exists then send him offer details 
        var conn = users[data.name]; 

        if(conn != null) { 
           //setting that UserA connected with UserB 
           connection.otherName = data.name; 

           sendTo(conn, { 
              type: "offer", 
              offer: data.offer, 
              name: connection.name 
           }); 
        }

        break;

     case "answer": 
        console.log("Sending answer to: ", data.name); 
        //for ex. UserB answers UserA 
        var conn = users[data.name]; 

        if(conn != null) { 
           connection.otherName = data.name; 
           sendTo(conn, { 
              type: "answer", 
              answer: data.answer 
           }); 
        } 

        break; 

     case "candidate": 
        console.log("Sending candidate to:",data.name); 
        var conn = users[data.name];

        if(conn != null) { 
           sendTo(conn, { 
              type: "candidate", 
              candidate: data.candidate 
           }); 
        } 

        break;

     case "leave": 
        console.log("Disconnecting from", data.name); 
        var conn = users[data.name]; 
        conn.otherName = null; 

        //notify the other user so he can disconnect his peer connection 
        if(conn != null) {
           sendTo(conn, { 
              type: "leave" 
          }); 
        }

        break;

     default: 
        sendTo(connection, { 
           type: "error", 
           message: "Command not found: " + data.type 
        }); 

        break; 
  }

**Comment by Domi83s** [comment]
var data; 

  //accepting only JSON messages 
  try { 
     data = JSON.parse(message); 
  } catch (e) { 
     console.log("Invalid JSON"); 
     data = {}; 
  }

  //switching type of the user message 
  switch (data.type) { 
     //when a user tries to login
     case "login": 
        console.log("User logged", data.name); 

        //if anyone is logged in with this username then refuse 
        if(users[data.name]) { 
           sendTo(connection, { 
              type: "login", 
              success: false 
           }); 
        } else { 
           //save user connection on the server 
           users[data.name] = connection; 
           connection.name = data.name; 

           sendTo(connection, { 
              type: "login", 
              success: true 
           }); 
        } 

        break;

     case "offer": 
        //for ex. UserA wants to call UserB 
        console.log("Sending offer to: ", data.name);

        //if UserB exists then send him offer details 
        var conn = users[data.name]; 

        if(conn != null) { 
           //setting that UserA connected with UserB 
           connection.otherName = data.name; 

           sendTo(conn, { 
              type: "offer", 
              offer: data.offer, 
              name: connection.name 
           }); 
        }

        break;

     case "answer": 
        console.log("Sending answer to: ", data.name); 
        //for ex. UserB answers UserA 
        var conn = users[data.name]; 

        if(conn != null) { 
           connection.otherName = data.name; 
           sendTo(conn, { 
              type: "answer", 
              answer: data.answer 
           }); 
        } 

        break; 

     case "candidate": 
        console.log("Sending candidate to:",data.name); 
        var conn = users[data.name];

        if(conn != null) { 
           sendTo(conn, { 
              type: "candidate", 
              candidate: data.candidate 
           }); 
        } 

        break;

     case "leave": 
        console.log("Disconnecting from", data.name); 
        var conn = users[data.name]; 
        conn.otherName = null; 

        //notify the other user so he can disconnect his peer connection 
        if(conn != null) {
           sendTo(conn, { 
              type: "leave" 
          }); 
        }

        break;

     default: 
        sendTo(connection, { 
           type: "error", 
           message: "Command not found: " + data.type 
        }); 

        break; 
  }
