### ISSUE TITLE
How i can Starting my NodeJS Application when linux starting

### ISSUE THREAD

**Issue by krzysiuszcze** [nodejs/help#45]
Hi,
I trying strating my app.js when the system starting. I need to have console becasue I use scanner to input datas.
this is the log error :
Tue Dec 8 09:34:43 2015: Starting ServerNode
Tue Dec 8 09:34:43 2015: /etc/init.d/ServerNode: line 22: node: command not found

To stating automatically my application i made a Sh Script (run when i launch)
and i copy this script in : /etc/init.d/
and give executable rights : chmod 755 /etc/init.d/ServerNode.sh
and : update-rc.d ServerNode.sh defaults 
Someone have a idea ?
Thanks for your help (Sorry for my poor english)
Christophe

**Comment by arvind-agarwal** [comment]
You could use https://www.npmjs.com/package/forever-service for this.

**Comment by bnoordhuis** [comment]
http://strong-pm.io/ ?  It's not well advertised on the site but it integrates with systemd and upstart, see `--help`.  It also does a ton more, like process management, log aggregation, profiling and debugging, and so on.  See http://strong-pm.io/compare/ for a feature matrix.

**Comment by krzysiuszcze** [comment]
Thank you for your responses, i trying this solutions. But my program need running in console. 
i solve my problem. I insert starting command in  /home/<user>/.bashrc . it run nicely
Thanks a lot for your help
best regards
