### ISSUE TITLE
Node.js binaries with v8 bleeding edge

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#450]
Is there a binaries store with something like https://github.com/v8/node/tree/vee-eight-lkgr similar to https://nodejs.org/download/nightly/ ?

**Comment by bnoordhuis** [comment]
@fhinkel might be able to answer that.  Integration testing is done [here](https://build.chromium.org/p/client.v8.fyi/builders/V8%20-%20node.js%20integration) but I don't know if you can download the build artifacts anywhere.

**Comment by vdeturckheim** [comment]
There is a page with the nightly builds. Dunno if it is what you need.
https://nodejs.org/download/nightly/

**Comment by vsemozhetbyt** [comment]
@vdeturckheim Now, Node.js nightly builds have almost the same v8 version as the current branch: v8 5.4.500.45 in Node.js 7.4.0 vs v8 5.4.500.46 in the Node.js 8.0.0-nightly20170118622b43997f. It would be helpful to have more edgy Node.js, something like Chrome Canary with the last v8.

For example, see [this thread](https://twitter.com/bmeurer/status/821802248770637826) and [this results](https://twitter.com/chicoxyzzy/status/821903659650977792): sometimes, it is interesting what goes on in the edge area, what optimizations we may wait and so on.

Unfortunately, I could not build from https://github.com/v8/node/tree/vee-eight-lkgr today on Windows 7, it fails. It would be handy to have a LKGR as a binary for quick tests.

**Comment by fhinkel** [comment]
You can download a zip file, e.g. [Build #3289](https://storage.cloud.google.com/chromium-v8/node-linux-rel/node-linux-rel-42550-4714bc15e850eec22e86f0b73c83178b78b4b4c2.zip). But I think only for Ubuntu :disappointed: . 

Build and test results are here: https://build.chromium.org/p/client.v8.fyi/builders/V8%20-%20node.js%20integration

They include a link to the zip file for every build. Click on a build number, then towards the bottom of the list of steps on `Archive link` - `download`. 

I'll discuss if we can setup a Windows trybot. Would be nice to easily be able to get the binaries as well. 

/cc @nodejs/v8

**Comment by targos** [comment]
I've been thinking lately about making a proposal to have nightly "canary" builds using our `master` branch and V8's `lkgr`. I'm working on scripts to automate this.

**Comment by ofrobots** [comment]
@targos that would awesome. Are you able to share the scripts you're working on. It would be good to be able to re-use the same integration scripts in both the node and the V8 build infrastructure.

**Comment by lordKnighton** [comment]
closing for now, definitely feel free to reopen.
