### ISSUE TITLE
v18.20.5 File not found

### ISSUE THREAD

**Issue by jjacobs-fundrise** [nodejs/help#4500]
### Node.js Version

v18.20.5

### NPM Version

I don't know

### Operating System

Darwin Kernel Version 23.6.0

### Subsystem

Other

### Description

We have a CI build that include the command `n 18`. It used to work downloading v18.20.4 but now that the latest version is v18.20.5 the response status is `404 File not found`.

I checked in https://nodejs.org/dist/v18.20.5/ and there are no files other than .txts.

Can someone add the files?

### Minimal Reproduction

Run `n 18` in terminal

### Output

Downloading https://nodejs.org/dist/v18.20.5/node-v18.20.5.tar.xz...
curl: (56) The requested URL returned error: 404

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
@nodejs/releasers PTAL

**Comment by noe-charmet** [comment]
Also reported here https://github.com/nodejs/node/issues/55829

**Comment by RedYetiDev** [comment]
This incident has been resolved
