### ISSUE TITLE
Cant install NodeJs

### ISSUE THREAD

**Issue by MHS5706** [nodejs/help#4502]
### Node.js Version

Installer

### NPM Version

none

### Operating System

Windows 11

### Subsystem

Other

### Description

I cant install node js the normal way, it gives me this error the moment i open the setup file, and yes i do have way above 10 gigs free
![image](https://github.com/user-attachments/assets/b0da528c-6111-4472-bc91-3250b196a704)
![image](https://github.com/user-attachments/assets/3739a95b-023b-46a5-ba2b-daa5e5e37951)

### Minimal Reproduction

literally just installed the 64x step up, and cant open it

### Output

![image](https://github.com/user-attachments/assets/56d77ed0-f557-4a11-a4d0-dbceb04214c3)

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by priyanand-shukla** [comment]
Are you running the installer as a admin?

**Comment by MHS5706** [comment]
No, cuz i literally don't have the option for whatever reason, i can't run
as administrator or go to compatibility and make it run as admin, it's
grayed out

**Comment by priyanand-shukla** [comment]
If it's your personal laptop figure out a way to run this as an Admin else connect with your org IT team.

**Comment by MHS5706** [comment]
> If it's your personal laptop figure out a way to run this as an Admin else connect with your org IT team.
it's my personal desktop, and i figured out how to run as admin through CMD, by using command (cd "filePath") then (start program") and it worked, so ig case closed, had to reinstall windows later, cuz something was off, but yea
