### ISSUE TITLE
Unable to access cookie at domain (client), when it is set at subdomain(server)

### ISSUE THREAD

**Issue by modaralgayal** [nodejs/help#4505]
### Node.js Version

Node.js v22.9.0

### NPM Version

10.9.0

### Operating System

22.04.1-Ubuntu

### Subsystem

domain

### Description

I am setting a cookie as a response to a signIn request from the subdomain ```api.talopakettiin.fi``` like so:
```
 res.cookie("Token", jwtToken, {
      domain: ".talopakettiin.fi",
      secure: true,
      httpOnly: true,
      path: "/",
      sameSite: "None",
    });
```
By specifying the domain you would think now talopakettiin.fi has access to the token that is set, but it doesn't. Im using elementor frontend on wordpress. In my function.php function i try to fetch the cookie like this: 
```
function handle_button_click() {

    error_log('Button clicked!'); // Example log for testing
	$api_url = 'https://api.talopakettiin.fi/forms/receive-form-data';
	$jwt_token = isset($_COOKIE['Token']) ? $_COOKIE['Token'] : 'Token not found';
	error_log("Extracted Token: " . $jwt_token);
    $response = wp_remote_post($api_url, [
            'method'    => 'POST',
            'body'      => "So much data",
            'headers'   => [
                'Content-Type' => 'application/json',
				$jwt_token
            ],
        ]);
    wp_send_json_success(array('message' => 'Button was clicked!'));
}
add_action('wp_ajax_handle_button_click', 'handle_button_click'); // For logged-in users
```
but jwtToken's value always results in Token not found. Even though, the cookie appears in the application storage tab: 
![image](https://github.com/user-attachments/assets/3ec6378d-3273-480f-8bd5-dfc2d1cea2e2)

Also, here is the url to my code: https://github.com/modaralgayal/TaloPakettiin

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by RedYetiDev** [comment]
It's unclear what code can be used to reproduce this issue. It seems like this is likely an issue with a dependency / how that dependency is being used.

**Comment by modaralgayal** [comment]
To whom it may concern,
Never fucking mind,
Sincerely

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RedYetiDev** [comment]
Hi @modaralgayal, I've edited your message to remove the profanity. I'm sorry you are upset. If you narrow down the reproduction, I'm sure we can find a way to help
