### ISSUE TITLE
Math.log changes in v7?

### ISSUE THREAD

**Issue by hughrawlinson** [nodejs/help#456]
* **Node.js Version**: 7.4.0
* **OS**: Debian (Travis CI)
* **Scope (install, code, runtime, meta, other?)**: Math
* **Module (and version) (if relevant)**: 

It looks like something has changed possibly in the Math module of node after v.7. Not sure exactly how to find out what's changed, but I'm seeing TINY changes in math computations that cause my tests to fail. I have an audio feature extraction module called [meyda](https://github.com/hughrawlinson/meyda) that calculates statistics about buffers of audio. There are two feature extractors that use `Math.log()`, and you can see in [this travis build](https://travis-ci.org/hughrawlinson/meyda/jobs/167888999) based on [this PR](https://github.com/hughrawlinson/meyda/pull/166) that builds meyda for node 7. Math.log is used only in the spectral flatness and mfcc (mel frequency cepstral coefficients) feature extractors, and now the values they output differ between v6 and v7 of node. Is it expected that Math.log will change between these two?

In case you do a repo search, the utilities part of Meyda also uses math.log, but it's not tested as part of utilities, only as part of mfcc (yes I realise this is bad testing practice and that I need to improve tests).

**Comment by MylesBorins** [comment]
if there was a change then it would likely have been on V8. are you testing
on browser as well? is it possible to make a reproducible minimal test
without using any dependencies?

**Comment by hughrawlinson** [comment]
@MylesBorins it should be possible, I will try this in a browser. I did have a look at the copy of the v8 in the Node repo, but I can't actually find the implementation of it, and searching for `log` just gives me lots of `console.log`. Do you know where it is?

**Comment by hughrawlinson** [comment]
I tried to reproduce the issue as minimally as possible [in this repo](https://github.com/hughrawlinson/node-log-test). What's currently in index.js is the original thing that produced the issue. It returns:

* **Node 7:** 0.43959081704043357
* **Node 6:** 0.4395908170404335

It looks like Node 7 added an additional digit of precision to the operation?

I reduced it down further in PRs on that repo which you can check out if you like, but the highlights were that: I wasn't able to reproduce the problem without Math.exp, so the problem may be there. It fairly clearly ended up being extra precision, which I imagine either causes floating point rounding errors, or corrected them. My understanding of floating point math is a bit hazy to be honest.

**Comment by MylesBorins** [comment]
@hughrawlinson I've gone ahead and confirmed that the sample code you provided is giving the result of `0.43959081704043357` in Google Chrome as well.

Node v7.x ships with V8 5.4, I believe that Chrome is currently shipping with V8 5.5.
Node v6.x shipped with V8 5.1.

It is worth mentioning that the result in Firefox is the same as Node 7 and latest chrome

While this is causing some weird edge cases I think it would be safe to assume that it is indeed the expected behavior

/cc @nodejs/v8 was there an expected increase in precision in between 5.1 and 5.4?

**Comment by ofrobots** [comment]
I can reproduce the difference with d8. `5.2-lkgr` seems to produce different output than `5.3-lkgr`.

**Comment by ofrobots** [comment]
A bisect reveals that the behaviour changed at the following commit:

```
Author: bmeurer <bmeurer@chromium.org>
Date:   Thu Jun 16 22:19:35 2016 -0700

    [builtins] Introduce proper Float64Exp operator.

    Import base::ieee754::exp() from FreeBSD msun and introduce a Float64Exp
    TurboFan operator based on that, similar to what we do for Float64Log.
    Rewrite Math.exp() as TurboFan builtin and use that operator to also
    inline Math.exp() into optimized TurboFan functions.

    CQ_INCLUDE_TRYBOTS=tryserver.chromium.linux:linux_chromium_rel_ng;tryserver.blink:linux_blink_rel
    BUG=v8:3266,v8:3468,v8:3493,v8:5086,v8:5108,chromium:620786
    R=mvstanton@chromium.org

    Committed: https://crrev.com/93e26314afc9da9b5b8bd998688262444ed73260
    Review-Url: https://codereview.chromium.org/2077533002
    Cr-Original-Commit-Position: refs/heads/master@{#37037}
    Cr-Commit-Position: refs/heads/master@{#37047}
```

/cc @bmeurer was a change in behaviour expected? The attached test case works with d8 with a minimal `s/console.log/print`. Let me know if I should open a V8 bug.

**Comment by bmeurer** [comment]
Yes this is an intentional change to make `Math.log` compatible with other JS engines, and to add more precision. We now follow the EcmaScript recommendation to use `fdlibm` (might even become a requirement in the future).
