### ISSUE TITLE
Should I use sync or async crypto.randomBytes in web server app

### ISSUE THREAD

**Issue by nwoltman** [nodejs/help#457]
* **Node.js Version**: >= 4
* **OS**: any
* **Scope**: meta
* **Module**: crypto

[`crypto.randomBytes()`](https://nodejs.org/dist/latest-v7.x/docs/api/crypto.html#crypto_crypto_randombytes_size_callback) has two signatures:

```js
// sync
const buf = crypto.randomBytes(256);

// async
crypto.randomBytes(256, (err, buf) => {
  if (err) throw err;
  // ...
});
```

My question is: Is it recommended to use the sync or the async version of `crypto.randomBytes()` in a web server application?

I'm guessing the answer will boil down to whether or not the sync version will block the process. I found [this comment](https://github.com/nodejs/node/pull/2170#issuecomment-122761940) which suggests that the sync version will probably be "instant" when generating small amounts of bytes. So if I always generate, let's say 512 bytes or less, would it be best to use the sync version? Or perhaps even with a small amount of generated bytes the sync version isn't "fast enough" so it would still be better for latency/throughput to use the async version?

**Comment by bnoordhuis** [comment]
The synchronous version can block to acquire entropy (in theory - it's complicated.)  If you want to play it safe, use the asynchronous version.

**Comment by nwoltman** [comment]
Okay, thank you!
