### ISSUE TITLE
Passing Data into a child process

### ISSUE THREAD

**Issue by moshie** [nodejs/help#458]
* **Node.js Version**: v6.9.2
* **OS**: Ubuntu 14.04.5 LTS
* **Scope (install, code, runtime, meta, other?)**: code

I have a method which loops through an array of arrays of file (image) paths. 

I need to pass each array into a child process, the child process is a casperjs file called (`processFiles.js`) which sends these file (image) paths through an online image compressor.

Initially I had it setup to stringify the array then send it through as a cli argument but that felt like a crude solution not to mention the array would be very long.

I looked at stdio, stout as a solution but I am kinda getting out of my depth and not really fully understanding what I am adding :$ 

Since the child process is async and in a loop I am not sure if I have managed it the right way with placing it in a promise chain?

Any help would be greatly appreciated! I have [added the repo](https://bitbucket.org/David-Hewitt/tiny-cli/src/1c8ceb6c24c610953539922690faa5e806ecbc62/src/compressor.js?at=async&fileviewer=file-view-default#compressor.js-16)  if you need a broader idea of what's going on.

My code is still very beta so please excuse the mass commenting 😄 

```js
var shellChain = [];

    // Loop through the chunks
    for (var d = chunks.length - 1; d >= 0; d--) {

          // Set chunk
	 var chunk = chunks[0];

          var promise = new Promise((resolve, reject) => {
               var child = shell('casperjs', [
                    `${__dirname}/processFiles.js`,
                    authUrl
               ]);

                child.stdin.write(JSON.stringify(chunk));

              child.stdout.on('data', function (data) {
                  log(data.toString());
              });

              child.on('error', (error) => {
                   reject(error);
              });

             child.on('close', (code) => {
                   resolve('ended?');
              });

         });

         shellChain.push(promise);

    }

return Promise.all(shellChain);
```

**Comment by bnoordhuis** [comment]
If you use `child_process.fork()`, you can `child.send(chunk)` and the child process will receive it as a `process.on('message', (chunk) => ...)` event.  How to integrate that with casperjs I can't tell you, though.

**Comment by moshie** [comment]
`fork()` is used specifically to spawn new Node.js processes and can't be used with phantomjs/casperjs 👎  which would explain why it can send data between parent and child processes that easily.

**Comment by moshie** [comment]
The write to file idea doesn't work I think it's something to do with async..
