### ISSUE TITLE
CRL validation issues

### ISSUE THREAD

**Issue by ruiquelhas** [nodejs/help#460]
* **Node.js Version**: `4.x` 
* **OS**: Any
* **Scope**: code
* **Module**: `tls`

I'm trying to validate a server certificate against a CRL on the client side, basically testing for the exceptional condition where I get the `CERT_REVOKED` error code.

I'm able to achieve this when I use a server certificate signed by a self-signed root CA, by referencing both that same CA file and the CRL (containing the server certificate id - which has been revoked with openssl).

```js
const fs = require('fs')
const tls = require('tls')

const server = tls.createServer({
  cert: fs.readFileSync('path/to/revoked/server/certificate.pem'),
  key: fs.readFileSync('path/to/revoked/server/key.pem')
})

server.listen(1337, () => {
  const client = tls.connect({
    port: 1337,
    ca: fs.readFileSync('path/to/root/ca.pem'),
    crl: fs.readFileSync('path/to/root/crl.pem')
  })

  client.on('error', err => {
    console.log(err.code) // CERT_REVOKED
  })
})
```

However, when using a server certificate which is signed by an intermediate CA (which in turn is signed by a self-signed root CA), there seem to be some issues validating the CRL (but not the CA).

Creating the full CA chain (required for it to work), and using openssl, I'm able to verify that the certificate is indeed revoked (by some CA in the chain - in this case, an intermediate CA):

```sh
$ cat path/to/intermediate/ca.pem path/to/root/ca.pem path/to/crl.pem > path/to/chain.pem
$ openssl verify -CAfile path/to/chain.pem -crl_check path/to/revoked/server/certificate.pem
path/to/revoked/server/certificate.pem: CN = <server_name>
error 23 at 0 depth lookup:certificate revoked
``` 

My question is, how can I achieve the same using `tls.connect()`?

With the same server configuration (this time pointing to a key pair revoked by the intermediate CA). I've tried all the following options:

### CRL bundled with CA chain

```js
server.listen(1337, () => {
  const client = tls.connect({
    port: 1337,
    ca: [
      fs.readFileSync('path/to/intermediate/ca.pem')  
      fs.readFileSync('path/to/root/ca.pem'),
      fs.readFileSync('path/to/intermediate/crl.pem')
    ]
  })

  client.on('error', err => {
    console.log(err.code) // no error
  })
}) 
```

### CRL not bundled with CA chain

```js
server.listen(1337, () => {
  const client = tls.connect({
    port: 1337,
    ca: [
      fs.readFileSync('path/to/intermediate/ca.pem')  
      fs.readFileSync('path/to/root/ca.pem'),
    ],
    crl: fs.readFileSync('path/to/intermediate/crl.pem')
  })

  client.on('error', err => {
    console.log(err.code) // UNABLE_TO_GET_CRL
  })
}) 
```

### CA chain bundled with CRL

```js
server.listen(1337, () => {
  const client = tls.connect({
    port: 1337,
    crl: [
      fs.readFileSync('path/to/intermediate/ca.pem')  
      fs.readFileSync('path/to/root/ca.pem'),
      fs.readFileSync('path/to/intermediate/crl.pem')
    ]
  })

  client.on('error', err => {
    console.log(err.code) // UNABLE_TO_VERIFY_LEAF_SIGNATURE
  })
}) 
```

### Providing both bundles

```js
server.listen(1337, () => {
  const client = tls.connect({
    port: 1337,
    ca: [
      fs.readFileSync('path/to/intermediate/ca.pem')  
      fs.readFileSync('path/to/root/ca.pem'),
      fs.readFileSync('path/to/intermediate/crl.pem')
    ],
    crl: [
      fs.readFileSync('path/to/intermediate/ca.pem')  
      fs.readFileSync('path/to/root/ca.pem'),
      fs.readFileSync('path/to/intermediate/crl.pem')
    ]
  })

  client.on('error', err => {
    console.log(err.code) // UNABLE_TO_GET_CRL
  })
}) 
```

I'm also really confused about the role of the "secure context" (the documentation is extremely vague), and why there are two different `ca` properties, one for the `options` object when creating that "secure context" - `tls.createSecureContext(options)` - and other for the `options` object used to create the connection itself - `tls.connect()`. My question in this case would also be why the same does not happen for the `crl` property? Cleary this property is also available as an option for `tls.connect()`, but it's not documented. Any reason why? 

I guess some of these issues might overlap with openssl concepts, but I was hoping somebody could make it a bit clear here since most of the available openssl documentation is extremely confusing.

I'm sorry for the long post, but maybe this could turn into a guide about how to do this kind of stuff using node, since I was not able to find anything that goes so deep.

**Comment by ruiquelhas** [comment]
Can someone from @nodejs/crypto engage here? I'm pretty sure this is something weird in the native bridge, but I'm not that comfortable with C++.

**Comment by Lackmann1994** [comment]
The problem is that you need to provide a CRL for each signing CA 
in your example the Root CA singes the intermediate CA (and possibly other certificates)
and the intermediate CA singes your client certificates (and possible other certificates)

If you provide CRL you need to provide a CRL for each signing CA since the intermediate CA could be revoked as well:


`server.listen(1337, () => {
  const client = tls.connect({
    port: 1337,
    ca: [
      fs.readFileSync('path/to/intermediate/ca.pem')  
      fs.readFileSync('path/to/root/ca.pem'),
    ],
    crl: [
      fs.readFileSync('path/to/intermediate/crl.pem'),
      fs.readFileSync('path/to/root/crl.pem'),
   ]
  })

  client.on('error', err => {
    console.log(err.code)
  })
}) `
