### ISSUE TITLE
node_natives.h generation

### ISSUE THREAD

**Issue by bigbadwofl** [nodejs/help#461]
I'm having some difficulty getting node_natives.h to reflect changes made to my node.gyp file (library_files section). I'm building with Visual Studio 2015 and even though I add extra js files to the array (like _third_party_main.js) it isn't being added to the resulting node_natives.h.

If someone has some info on where this file is generated and how I can debug the issue, I'd really appreciate it.

**Comment by bnoordhuis** [comment]
The node_js2c phase uses library_files as its inputs, any changes should automatically get picked up.  Maybe you need to run vcbuild.bat again?

**Comment by bigbadwofl** [comment]
Thanks @bnoordhuis, that seems to have done the trick.

Any idea why vcbuild rebuilds the natives and VS build (even if I do a full rebuild) doesn't?

**Comment by bnoordhuis** [comment]
vcbuild.bat runs the configure script and gyp.  It sounds like VS doesn't.

**Comment by bigbadwofl** [comment]
Thanks, that makes it more clear to me.

Appreciate the help!
