### ISSUE TITLE
Disable GC

### ISSUE THREAD

**Issue by dolftax** [nodejs/help#462]
I am looking for something similar to https://docs.python.org/2/library/gc.html#gc.disable (or) alternative flag combination to achieve the below mentioned.

'A node process to run until it reaches a defined RSS without GC interference.'

**Comment by bnoordhuis** [comment]
You can't disable it but you can try setting the `--max_*_space_size=...` flags (see `node --v8-options`) high enough that garbage collection never happens.  See also `--trace_gc`.

There is no equivalent to python's gc.disable().  Cpython mainly uses reference counting, with the garbage collector as a fallback mechanism for collecting cyclic object graphs.  Node/V8 always uses generational GC.

**Comment by dolftax** [comment]
@bnoordhuis Does this still hold true? - https://github.com/nodejs/node/wiki/Frequently-Asked-Questions

**Comment by bnoordhuis** [comment]
@dolftax Yes.

**Comment by dolftax** [comment]
``` javascript
➜ node --nouse_idle_notification --trace_gc --max-old-space-size=1000 --max-semi-space-size=64 example.js
[4465:0x3558ae0]      119 ms: Scavenge 3.2 (9.0) -> 2.9 (10.0) MB, 1.2 / 0.0 ms  allocation failure 
```

@bnoordhuis I have set the `max-old-space-size` and `max-semi-space-size` high enough and if you look below, the RSS is no-way near the constraints set. Why is the GC still trying to run?

``` javascript
➜ ps aux | grep node 
dolftax   4465  0.3  0.7 881664 29460 pts/0    Sl+  21:43   0:01 node --nouse_idle_notification --trace_gc --max-old-space-size=1000 --max-semi-space-size=64 example.js
```

.. where RSS is 29460 bytes

**Comment by bnoordhuis** [comment]
Perhaps you also need to pass `--noconcurrent_sweeping`.  If that doesn't help, I think the conclusion has to be that it can't be done.

**Comment by dolftax** [comment]
``` javascript
➜ node --nouse_idle_notification --trace_gc --max-old-space-size=1000 --max-semi-space-size=64 --noconcurrent_sweeping example.js
[10948:0x3712ae0]      119 ms: Scavenge 3.2 (9.0) -> 2.9 (10.0) MB, 1.2 / 0.0 ms  allocation failure 
[10948:0x3712ae0]      151 ms: Scavenge 3.5 (10.0) -> 3.5 (11.0) MB, 2.4 / 0.0 ms  allocation failure 
9 workers forked/spawned
[10967:0x2f4db20]      271 ms: Scavenge 3.1 (9.0) -> 2.8 (10.0) MB, 1.9 / 0.0 ms  allocation failure 
[10948:0x3712ae0]    15618 ms: Mark-sweep 10.0 (30.0) -> 4.4 (30.0) MB, 3.1 / 0.0 ms  (+ 26.3 ms in 70 steps since start of marking, biggest step 2.2 ms) GC interrupt GC in old space requested
```

Thus, concluded.

**Comment by dolftax** [comment]
@bnoordhuis I managed to get the GC running as required.

 `node --max-old-space-size=1000 --max-semi-space-size=512 --noconcurrent_sweeping example.js`

.. did wait for the max old space size to reach 1000 MB before running Mark Sweep. :smile_cat:

**Comment by Shahor** [comment]
Hello there, 

For a test I was trying to do exactly this and tried with your solution but somehow I see the GC always running even though I haven't reached the limits I imposed... so I suppose either:
- it has changed since, and can't be stopped that way on newer node versions
- I'm doing something wrong.

If you guys have any info on this I would be  super interested :)

**Comment by emersoncantalice** [comment]
Any success in disabling the GC in any way?
