### ISSUE TITLE
Compiling node_modules into binary

### ISSUE THREAD

**Issue by bigbadwofl** [nodejs/help#463]
If I need a bunch of node modules (for example 'express') as part of the node binary, do I need to add every single js file into the library_files array in node.gyp, or is there some other way I'm missing?

Worst case I can just distribute node_modules along with my executable but I'd prefer if I didn't need to.

**Comment by bnoordhuis** [comment]
> do I need to add every single js file into the library_files array in node.gyp

Yes, basically.  Note that baked-in script code executes in a slightly different environment than regular code loaded from disk.  For maximum compatibility, ship it along node, not baked into it.

**Comment by bigbadwofl** [comment]
Thanks, I think I'll just ship with the modules themselves.

Regarding compiled-in modules, if I were to add two files to the library_files with the same file name (but different folder paths) I'm assuming there's no way to distinguish them internally? Since I'd need to require the modules with their file names instead of the paths (as they've become 'native' modules).

Am I correct in assuming this?

**Comment by bnoordhuis** [comment]
I'm 95% sure you should be able to require them as 'foo/x' and 'bar/x' if you created them as lib/foo/x.js and lib/bar/x.js.

**Comment by bigbadwofl** [comment]
For posterity's sake, I just wanted to note that you were right on this, thanks!
