### ISSUE TITLE
Unsafe addon example?

### ISSUE THREAD

**Issue by bedeho** [nodejs/help#464]
* **Node.js Version**: 7.4.0
* **OS**: Ubuntu
* **Scope**: c++ addons

### Background

The c++ addon tutorial shows an example of how to pass wrapped objects around

https://nodejs.org/api/addons.html#addons_passing_wrapped_objects_around

which looks like this.

```c++
void Add(const FunctionCallbackInfo<Value>& args) {
  Isolate* isolate = args.GetIsolate();

  MyObject* obj1 = node::ObjectWrap::Unwrap<MyObject>(
      args[0]->ToObject());
  MyObject* obj2 = node::ObjectWrap::Unwrap<MyObject>(
      args[1]->ToObject());

  double sum = obj1->value() + obj2->value();
  args.GetReturnValue().Set(Number::New(isolate, sum));
}
```

However `node::ObjectWrap::Unwrap<T>` relies on `v8::Object::GetAlignedPointerFromInternalField`, as seen here
 
```c++
  template <class T>
  static inline T* Unwrap(v8::Local<v8::Object> handle) {
    assert(!handle.IsEmpty());
    assert(handle->InternalFieldCount() > 0);
    // Cast to ObjectWrap before casting to T.  A direct cast from void
    // to T won't work right when T has more than one base class.
    void* ptr = handle->GetAlignedPointerFromInternalField(0);
    ObjectWrap* wrap = static_cast<ObjectWrap*>(ptr);
    return static_cast<T*>(wrap);
  }
``` 

and the v8 documentation clearly states

**Gets a 2-byte-aligned native pointer from an internal field. This field must have been set by SetAlignedPointerInInternalField, everything else leads to undefined behavior.**

### Question

How can I modify this example so as to allow the addon to gracefully handle an object which does not wrap `MyObject`.

**Comment by bnoordhuis** [comment]
Your add-on is as safe or unsafe as you want to make it.  There are strategies for restricting (e.g. `v8::Signature`) or validating (e.g. `v8::Object::HasInstance()`) inputs from JS code.  If you can rephrase your question in closed form, I'll try to answer it.  :-)

**Comment by bedeho** [comment]
Thanks for the quick response, updated.

**Comment by bnoordhuis** [comment]
> How can I modify this example so as to allow the addon to gracefully handle an object which does not wrap MyObject.

Check with `function_template->HasInstance(args[0])` where the `v8::FunctionTemplate` is the same one you passed to `v8::ObjectTemplate::New()` (assuming you pass one - if you don't, you have a reason now. :-))

You will want to cache the FunctionTemplate in a `static v8::Persistent<v8::FunctionTemplate> persistent_function_template` somewhere so you can retrieve it with `auto function_template = v8::Local<v8::FunctionTemplate>::New(isolate, persistent_function_template)`.  HTH.
