### ISSUE TITLE
Public Key for verifying downloads 

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/help#465]
Hello everyone!

I am trying to create a secure 🔐 installer of node for my docker work that verifies that the correct version of node is installed: in short: a shasum check 🔍  .

Node.js _does_ provide the sha hashes for each release _(which I didn't notice before: but it is very awesome)_ 😃  in the [SHASUM256.txt.asc]( https://nodejs.org/dist/v6.9.4/SHASUMS256.txt.asc) 🔒  which is even [signed](https://nodejs.org/dist/v6.9.4/SHASUMS256.txt.sig) 🔏  _(awesome)_. But it seems that the signature _(public key?)_ is different per release?

If I want to provide a tool that downloads "any given version", then this tool would need to know the signature of every release, which means that with every release of node the tool would become bigger and I would have to setup a maintenance task. 😓 

Now: I wonder if it there is **one** common public key 🔑  that I could use to verify the release sha-sums against? And if not: would it be good to create one?

**Comment by bnoordhuis** [comment]
We don't use a shared key, releasers sign releases with their own individual keys, but they are listed in the README.

Our current release policy is intentional in case you're wondering, it came about after some discussion.  The main reason we sign with individual keys is that the logistics of a master key were deemed to much of a headache (who gets to own it, what if it's lost or stolen, etc.)

**Comment by martinheidegger** [comment]
It would be possible for me to write a "proxy" that has one singular public key that "i trust" that takes the data on deployment and encrypts it again. This sort of system seems to be easily "added on top" during a public process?!"

**Comment by bnoordhuis** [comment]
I'm sorry but I'm not quite sure what you mean.  (Unless it wasn't a question, in that case just ignore me.)

**Comment by martinheidegger** [comment]
In order to publish (and generate the files above) you use individual keys, and end up with following files: 

```
https://nodejs.org/dist/v6.9.4/SHASUMS256.txt
https://nodejs.org/dist/v6.9.4/SHASUMS256.txt.asc
https://nodejs.org/dist/v6.9.4/SHASUMS256.txt.asc.sig
```

This is and should stay the "single-source-of-truth" and is good that way. Now, based on this I can imagine a privateKey in the build process that has a published publicKey that based on those files adds a

````
https://nodejs.org/dist/v6.9.4/SHASUMS256.txt.common.asc
````

file that can be taken as verified. Unlike the keys used for signing though, if it should happen that the privateKey is lost at some point or revealed to someone it would be fairly easy, even though annoying to all involved, to replace it by "simply" adding a `...txt.common2.asc` file that again just sign's a new key. Naturally the installer would need to be updated to the new common2 key but that seems like a fair trade-off between usability and security.

I would think that it would be rather easy to develop a services that offers this functionality as an outsider but it seems like something better managed by the Node.js project?!

**Comment by martinheidegger** [comment]
Oh man, on my ride home it dawned on me that this - exactly is what **https** is for ... doh
