### ISSUE TITLE
Parse ics in node js

### ISSUE THREAD

**Issue by MKT123** [nodejs/help#466]

**Comment by vsemozhetbyt** [comment]
Sorry, I know nothing about ics, but there was [this issue](https://github.com/nodejs/help/issues/427) recently, maybe it will be somehow helpful. I hope somebody will give you more definite answer.

**Comment by mahakT** [comment]
Thanks for that...! I am able to parse the ics..... to be precise... I am looking to get this parameter from ics in output..there are 2 entried for BEGIN.. I want to get only records which has BEGIN:VALARM... how can i parse this parameter... any idea ? Thanks in Advance...

var calString = `BEGIN:VCALENDAR
VERSION:2.0
**BEGIN:VTODO**
DTSTAMP:20130609T150000Z
SUMMARY:my description
UID:john
**BEGIN:VALARM**
END:VALARM
END:VTODO
END:VCALENDAR`;

**Comment by mahakT** [comment]
Thanks for that..I am able to parse ics... in precise I am looking  how to get parameter BEGIN:VALARM in output to see if that helps ...in  below sample output there are  three BEGIN variables .... I am no sure how to get data  that has BEGIN:VALARM .... from sample output.. I need 1 and 2....not the third one.....
1.
**BEGIN:VEVENT**
VERSION:2.0
BEGIN:VTODO
DTSTAMP:20130609T150000Z
SUMMARY:my description1
**BEGIN:VALARM**
2.
**BEGIN:VEVENT**
DTSTAMP:20130609T150000Z
SUMMARY:my description2
**BEGIN:VALARM**

3.
**BEGIN:VEVENT**
BEGIN:VTODO
DTSTAMP:20130609T150000Z
SUMMARY:my description3
someone please help if you have any idea...
