### ISSUE TITLE
Where do I get node js 0.12 and how to install it on Linux debian 8?

### ISSUE THREAD

**Issue by Shaarp** [nodejs/help#47]
I think my title is explaining oneself.
Otherwise feel free to ask me.

Best Regards

**Comment by rvagg** [comment]
https://deb.nodesource.com/ should be the way to go for automated installs. For manual installs you can grab binaries from https://nodejs.org/download/release/latest-v0.12.x/, the x86 and x64 linux binaries will work fine.

**Comment by Fishrock123** [comment]
@Shaarp let us know if you have any more questions. :)
