### ISSUE TITLE
Referencing node_modules from native modules

### ISSUE THREAD

**Issue by bigbadwofl** [nodejs/help#472]
I'm busy compiling a project into node and I need access to external modules from within a native module but they all use NativeModule.require in bootstrap_node.js.

What is the correct way of dealing with this issue?

**Comment by bnoordhuis** [comment]
> I need access to external modules from within a native module but they all use NativeModule.require

What does 'they' refer to?  External modules or the baked-in ones?

If you want to access an on-disk module from a baked-in module, I don't think you can currently do that, you'd have to patch the bootstrap module loader.

**Comment by bigbadwofl** [comment]
Thanks, I figured that too.

Having some difficulty figuring out how to do that though. Where does node do the 'mapping' to figure out whether a module is an external module (like your index.js file) or whether it's a node_module which should be found in node_modules?

Basically what I'm trying to do now is to change the NativeModule.require to also call that method whenever a native module isn't found (implying that it's actually in node_modules.

**Comment by bnoordhuis** [comment]
That logic lives in lib/module.js, the normal (second-stage) module loader.

**Comment by bigbadwofl** [comment]
Something to do with Module._nodeModulePaths, I figure?

**Comment by bnoordhuis** [comment]
That's right.

**Comment by bigbadwofl** [comment]
Thanks so much! I'll keep this thread open for a bit, if that's ok. I might have more questions on this a bit later.

**Comment by bigbadwofl** [comment]
Ok, I've modified NativeModule.require to load the module from disk if a native module isn't found. Now I'm trying to use requirejs internally but when I load requirejs in _third_party_main (before loading my index.js), index.js can't require AMD modules. I get 'define is not defined'.

I guess this is because requirejs was loaded in some other scope? Got any ideas on how to rectify this?

**Comment by bnoordhuis** [comment]
Hard to say, I don't know how requirejs is implemented.  Are you using the vm module anywhere?

(FWIW, lib/module.js does but only `vm.runInThisContext()`.)

**Comment by bigbadwofl** [comment]
I'll have a look, thanks. So far, I'm thinking I'll just convert all my modules to CommonJS if I can't get it to work.
