### ISSUE TITLE
Compiling With Flags

### ISSUE THREAD

**Issue by bigbadwofl** [nodejs/help#477]
I need to compile node with the --expose-gc flag enabled. How would I go about this? Even if I need to modify code somewhere, that's fine.

(This is on Windows)

**Comment by bnoordhuis** [comment]
Run configure like this: `./configure --v8-options="--expose-gc"`

I don't know how (or if) vcbuild.bat lets you do that but you'll find out soon enough. :-)

**Comment by bigbadwofl** [comment]
Thanks! 

It would seem I can modify vcbuild.bat to achieve this (line 39).

`set configure_flags=--v8-options="--expose-gc"`
