### ISSUE TITLE
Access to native_module cache

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/help#478]
* **Node.js Version**: > 4.0
* **OS**: All
* **Scope (install, code, runtime, meta, other?)**: Core/internals
* **Module (and version) (if relevant)**: native_module

Hi,
Is there any way to access the [native_module cache](https://github.com/nodejs/node/blob/5de3cf099cd01c84d1809dab90c041b76aa58d8e/lib/internal/bootstrap_node.js#L441) from user-land or is it safe to assume that nobody can decache a native module after instanciation ?

Thanks alot

**Comment by addaleax** [comment]
> Is there any way to access the native_module cache from user-land

I’m pretty sure there isn’t. If you want to make sure it stays that way in the future, you could probably open a PR against Node that replaces `NativeModule._cache` with a simple variable in `node_boostrap.js`.

> is it safe to assume that nobody can decache a native module after instanciation ?

Even if that were possible, it would probably not be a very good idea – a lot of built-in modules run one-time setup code, so re-requiring would have problematic results.

**Comment by vdeturckheim** [comment]
@addaleax thanks a lot for this clarification. That is pretty much what I assumed :-)

I'll PR today as you suggested.
