### ISSUE TITLE
Need your help.

### ISSUE THREAD

**Issue by rahulmukherjeedurgapur** [nodejs/help#479]
Hi There,

Hope you are doing well !!!

We are developing a completely free online tutorial site (linkedlist.top) to set up a bridge between academics and industrial applications.
From real life experience it is often observed that fresher and professionals adopting a new technology often find it difficult to link up the same to assignments in industry.

The above mentioned site is for new comers with no prior knowledge of our technology.
As you have the best documentation to describe each feature, we like to use the same to create a topic wise tutorial as well.

We earnestly requesting you to permit us to use the same in our site where needed.

Thanks and Regards,
LinkedList Team.

**Comment by addaleax** [comment]
If you’re talking about the documentation that you can find at https://nodejs.org/api/: You can use that documentation under the terms of the MIT license as found at https://github.com/nodejs/node/blob/master/LICENSE#L4-L22. That basically you can use it as long as you include that license text along with it.

**Comment by rahulmukherjeedurgapur** [comment]
Hello Anna,
Many thanks for your quick response.  It will help us a lot.

Thanks and Regards,
Rahul
