### ISSUE TITLE
child_process.spawn() with 'ipc': has JSON built-in?

### ISSUE THREAD

**Issue by ibc** [nodejs/help#48]
Hi, the doc says:

> 'ipc' - Create an IPC channel for passing messages/file descriptors between parent and child. A ChildProcess may have at most one IPC stdio file descriptor. Setting this option enables the ChildProcess.send() method. If the child writes JSON messages to this file descriptor, then this will trigger ChildProcess.on('message'). If the child is an Node.js program, then the presence of an IPC channel will enable process.send() and process.on('message').

In my case I call `spawn()` with `stdio: ['pipe', 'pipe', 'pipe', 'pipe']`to launch a C+libuv subprocess in which I open the `fd` 3 to intercommunicate with the Node process and then pass JSON bodies in both directions.

According to the doc above, in Node I can do `process.send(JSON_BODY)` and `process.on('message', function(JSON_BODY)`, but:

* Does it mean that `process.on('message', function(JSON_BODY)` directly provides a JS object? or just a string I need to parse with `JSON.parse()`?  or a Buffer?
* Node's IPC are stream-based pipes, so being a stream I should be ready to receive "partial" JSON bodies... or does Node some magic and it guarantees me that any string given to `process.send()` is **totally** received in the child process and also that the data/string received in `process.on('message')` contains **all** the data written by the subprocess?

**Comment by ibc** [comment]
By checking the [code](https://github.com/nodejs/node/blob/master/lib/internal/child_process.js) it seems that ' ipc'  assumes JSON based messages with no line break (just one at the end that signals end of message).

This is **clearly** designed for spawning a Node subprocess. What about if my subprocess is not a Node program but a C program? What should I expect in the C side? Which kind of messages should I send from C side? Shouldn't this be documented?

**Comment by bnoordhuis** [comment]
It's really only intended for communication between node processes but if your C program speaks newline-delimited JSON, there's no reason it wouldn't work.

The 'ipc' part is tricky on Windows; the C program needs to know about the ad hoc protocol for sending over handles (unless you let libuv handle that, of course.)

**Comment by ibc** [comment]
Thanks a lot. Anyhow I'll feel more comfortable with a simple `pipe` :)

**Comment by ORESoftware** [comment]
@ibc did you find a good solution to this? I think IPC can be implemented with pipes. I just don't know how Node.js implements IPC, I think there is more than one way to do IPC of course, just not sure how Node.js does it.
