### ISSUE TITLE
What os-level dependencies are usually required?

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/help#483]
I wrote a tool to install node.js within another docker image: https://github.com/martinheidegger/install-node and as part of this I wrote:

Be sure that you have all dependencies (debian example):

> ```dockerfile
> RUN apt-get update \
>    && apt-get install -y \
>          build-essential \
>          git \
>          curl \
>    && rm -rf /var/cache/apk/*
> ```
>
> Note: build-essential is not necessarily required, but if any node build process requires a c, c++ > or other library, the yarn install process might fail.

But actually I would love to know what dependencies usually are needed when installing node.js packages. I imagine:

- `git` because npm/yarn can download from a git url
- `gcc` because some npm-packages want to be compiled
- `make` because some binary libraries will be compiled with it
- `man` for reading the manuals given in package.json's `man` section
- `python 2.7` Not sure where but I remember some python usage in build scripts?

It would be lovely if someone could help me figure that out _(and I think it might be good information for the node community)_

**Comment by bnoordhuis** [comment]
Your list looks correct to me.

> man for reading the manuals given in package.json's man section

Do people do that?  The community seems to have settled on markdown these days.  Outside of node and npm, I can't think of anything that ships with man pages.

> python 2.7 Not sure where but I remember some python usage in build scripts?

Correct.  Also node-gyp, which is based on GYP (which is python2 code.)

**Comment by gibfahn** [comment]
I think things that install globally sometimes have man pages, I know [citgm](https://github.com/nodejs/citgm/tree/master/man) does, not sure if any non-nodejs ones do.
