### ISSUE TITLE
for secure my code

### ISSUE THREAD

**Issue by aashishtyagi333** [nodejs/help#484]
I am going to give my Node-JS code to client. But, I want to secure it from client that the code not in the readable form but execute on browser easily.
So, what module can i use for securing my code. Please suggest me....

**Comment by vdeturckheim** [comment]
My understanding is that you are looking for Obfuscation of javascript code. This might do the trick but at the end of the day, I am very skeptical you will be able to prevent reversing JS code in browser. 

That seems to be more of a general JavaScript question than a Node.js one.

**Comment by aashishtyagi333** [comment]
But, I write my licensing code in JavaScript file. So, how can i protect it.
just like .Net we create DLL file for securing code. But if i am using NodeJS there is no way to secure it.

**Comment by vdeturckheim** [comment]
AFAIK .Net DLL can be decompiled to C# (https://www.jetbrains.com/decompiler/). JavaScript is an interpreted language. ususally, you can't have a JavaScript program without its sources.

**Comment by aashishtyagi333** [comment]
So, what can I do, Please give me a alternate solution.

**Comment by bnoordhuis** [comment]
nw.js has this: http://docs.nwjs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/

Note the caveats though.  Getting more reliable clients might be all around easier.
