### ISSUE TITLE
Documentation for v8 native functions

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#486]
* **Scope**: v8

Is there a documentation or any brief info about inner v8 functions used with `--allow-natives-syntax` and `%` prefix and listed in the [runtime.h](https://github.com/v8/v8/blob/master/src/runtime/runtime.h) (also mentioned in the v8 [wiki](https://github.com/v8/v8/wiki/Built-in-functions))?

cc @nodejs/v8

**Comment by bnoordhuis** [comment]
Short answer: no.

Longer answer: the natives are not stable in any way, they exist purely as a bridge for V8's baked-in JS code and its C++ runtime.

Upstream V8 seems to be moving more and more code to C++ land.  I don't know if their end goal is to remove all baked-in JS but it wouldn't surprise me.

**Comment by vsemozhetbyt** [comment]
@bnoordhuis Thank you. It is a pity that useful optimization functions like `%GetOptimizationStatus()`, `%HasFastProperties()` or `%HaveSameMap()` are mentioned only sparingly and by chance.
