### ISSUE TITLE
Debian Wheezy version of node

### ISSUE THREAD

**Issue by Soony37CZE** [nodejs/help#488]
* **Node.js Version**: That is problem
* **OS**:Debian 7
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Hi i want install NodeJS on Debian 7 Wheezy I need version 7.5.0 but every time installs version 0.10.48 and I don't  knows what is bad thanks for help and sorry for that problem.

**Comment by gibfahn** [comment]
If you want to use a package manager, see [this guide](https://nodejs.org/en/download/package-manager/). For older Linux distros you might need to see [these instructions](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md).

If you want to install node manually, there is no "installation" on Linux per se, you just need to extract the tarball, and make sure the `node` and `npm` binaries in the `./bin` subdirectory are somewhere in your path.

I find [nvm](https://github.com/creationix/nvm#install-script) is useful for managing node installations (it will download, extract, and add to path for you). If you want to do things manually, you can do something like:

```bash
wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz
tar -xf node-v6.9.2-linux-x64.tar.gz --directory /usr/local --strip-components 1
```

This will put the `./bin` directory in `/usr/local/bin`, which should be in your `$PATH` already. You can verify that it worked with:

```bash
node --version
npm --version
```
