### ISSUE TITLE
RESTful Services: Best Practices for GET URL

### ISSUE THREAD

**Issue by StephanusRex** [nodejs/help#489]
* **Node.js Version**: 6.9.5
* **OS**: Windows 7 64bit
* **Scope (install, code, runtime, meta, other?)**: Other
* **Module (and version) (if relevant)**: N/A

I want to build a RESTful service with Node such that the URL for the GET operation contains the item key in the URL. For example: `GET http://www.example.com/customers/12345`.

Right now I'm using a query string but that's not good form as I understand. So, if I use the method above, 

(a) how do I set up my route in Express ("/customers"?), and
(b) how do I pull the ID from the URL in my script?

Many thanks.

**Comment by evanlucas** [comment]
Hi @StephanusRex! The documentation for doing this can be found at http://expressjs.com/en/4x/api.html#req.

Here is an example:

```js
app.get('/customers/:id', function (req, res) {
  // To get the :id parameter, use req.params.id
  console.log('get customer', req.params.id)
  res.end()
})
```

If you were to navigate to `/customers/12345`, `get customer 12345` would be logged from this route. Thanks!

**Comment by StephanusRex** [comment]
Excellent! Thank you very much!
