### ISSUE TITLE
Node Post method not working

### ISSUE THREAD

**Issue by akhileshvaranasi** [nodejs/help#491]
HI When we are writing a put and post method Unresolved function or method .post in node js and
we are getting 404 error we tried using inteelij sublime also. The same error can any one solve it immediately

Version:
node js =4.3.2
Platform:
windows
Subsystem:
![screen shot 2017-02-09 at 6 50 48 pm](https://cloud.githubusercontent.com/assets/4920092/22785694/609905ce-eefb-11e6-8a33-1ff016f22e4d.png)

**Comment by evanlucas** [comment]
Can you paste in the entire contents of the file? Thanks!

**Comment by bnoordhuis** [comment]
No follow-up, closing.
