### ISSUE TITLE
Documentation for C++ layer debugging

### ISSUE THREAD

**Issue by kysnm** [nodejs/help#492]
Hi there!

I would like to try improvement for C++ layer test coverage.
I know `python tools/test.py --mode=debug` can use the debug build. (I read the Makefile)
Is there any documentation, knowledge, blog or so on for attach to the node process using gdb while the test running?

**Comment by addaleax** [comment]
Hi @kysnm! I don’t think so, but most of the time doing so is pretty easy. Did you see [this section](https://github.com/nodejs/node/blob/159749d5224d6a7906aa4e5a7aaa20f44500b3c8/CONTRIBUTING.md#step-5-test) in the contributing guide? You can run most tests as `node ./test/path/to/test.js`, so attaching `gdb` works the same as for most other programs. (`gdb node_g` and then `run ./test/path/to/test.js`).

(If the tests requires special flags to be passed to node, it’s listed at the top of the test file. That’s about the only tricky thing).

Let me know if this helps!

**Comment by kysnm** [comment]
Hi @addaleax 
Sorry for late reply. 🙇 
Thank you for useful information.

I got it!
I will try to improve test coverage.
