### ISSUE TITLE
file open event for fs.watch

### ISSUE THREAD

**Issue by ramandraju** [nodejs/help#493]
is it possible get event when a file is opened from a directory which is being watched.. if not is there any alernate to do so

**Comment by WsDwA1022** [comment]
@ramandraju As I know, there is no native way to achieve that. On Windows one possible solution would be
1. Create a v8 addon and require it in your Node.js script
2. From addon call **NtQuerySystemInformation** (from **windows.h**)
3. Filter returned array of **SYSTEM_HANDLE** structure to get all file handles in the system
4. Create a new thread which will search for handles to your file (when it finds file, close thread and call your callback function)
