### ISSUE TITLE
How to resolve "c:\\folDER\\fILE.tXT" to "C:\\Folder\\File.txt" using the fs API

### ISSUE THREAD

**Issue by doodadjs** [nodejs/help#497]
... taking into account that the canonical name is "C:\\Folder\\File.txt"

I've filled two separated issues :

[#11374](https://github.com/nodejs/node/issues/11374) **fs.stat should returns the actual file path**
[#11379](https://github.com/nodejs/node/issues/11379) **fs.realpath doesn't return the real path under Windows**

But none has finally resolved my problem. I've been proposed to use "fs.readdir" but that's really not efficient. Thanks.

**Comment by bnoordhuis** [comment]
Can you explain what it is you ultimately need to work, and why?

The canonical file name?  There isn't a portable way except fs.readdir() and even that may not be 100% fool-proof all the time.  (Also, what does 'canonical' even mean with file systems that support hard links?)

**Comment by doodadjs** [comment]
I just want the file name and path as it is stored in the file system. I don't know how I could be more precise, but...

Imagine the following URL : http://www.mydomain.com/app/static/FOLDER/FILE.TXT
And the following base on the FS : public\Folder\File.txt

I want it to return 404 when node runs under Windows just like it would do when it runs under Linux.

**Comment by bnoordhuis** [comment]
Right, you want the canonical path.  You either have to scan recursively with fs.readdir() or turn on NTFS case sensitivity (although that may break other programs - YMMV.)

**Comment by doodadjs** [comment]
I've browsed the Win32 APIs on MSDN and effectively there is no easy way to achieve that. Closing the issue... Thanks.

**Comment by WsDwA1022** [comment]
@doodadjs Well, it depends on what you consider as easy way. The function which does what you want is actually very simple. Just scan through all directories using native fs module and resolve each directory name.

```JavaScript
'use strict';

// Resolve function

const resolve = (rd => path =>
  path.toLowerCase().split('\\').reduce((parent, dir) =>
    parent ?
      (parent += '\\') + (dir && rd(parent).find(d => d.toLowerCase() == dir)) :
      dir.toUpperCase()
  , '')
)((fs => fs.readdirSync.bind(fs))(require('fs')));

// Test

var nonResolved = 'c:\\folDER\\fILE.tXT';
var resolved = resolve(nonResolved);

console.log(resolved); // C:\Folder\File.txt
```

**Comment by doodadjs** [comment]
I mean a C++ API. I also mean something that prevents a directory scan.
