### ISSUE TITLE
Arch: Is there a DOM (or the equivalent of a DOM)?

### ISSUE THREAD

**Issue by markfilipak** [nodejs/help#498]
* **Node.js Version**: none (yet, depending on...)
* **OS**: Linux Mint 17 & 18
* **Scope (install, code, runtime, meta, other?)**: architecture
* **Module (and version) (if relevant)**: all
Hello,

Could someone kindly give me a push in the right direction?
Is there a DOM (or the equivalent of a DOM)? Is it documented? Where can I find it?

That's probably all I need as I'm very experienced writing & using javascript.

Thanks & Regards,
Mark Filipak.

**Comment by addaleax** [comment]
If by “DOM” you mean what browsers expose to client-side Javascript, no, Node doesn’t have that. There are modules like https://github.com/tmpvar/jsdom that provide a virtual DOM for you if you really need it.

**Comment by vsemozhetbyt** [comment]
You can also try hybrid systems like [Electron](https://github.com/electron/electron), which connect Node.js and Web API and provide GUI besides.

**Comment by tniessen** [comment]
Closing as solved. There is no DOM in node.
