### ISSUE TITLE
Icalendar to HTML 

### ISSUE THREAD

**Issue by MKT123** [nodejs/help#500]
Hi, It would be helpful if expertise can provide a suggestion on how to implement below functionality.

I have an ics file ... as ics has whole information including unrequired evnts details....I need to get the ONLY exact events from the ics(means the events what i see when we open ics in calendar view) 

here is what i tried...
1. i tried with ical js package.. it doesnt fetch all parameters from ical( example: param like Byday)
2. so i have the ics data in plain file and stored in json format.
I did some analysis on how ics data works... not sure if i am right... I guess inspite of latest dstart /dend....it looks for Rrule parameter... so technically any advise how to get only required events ?Thanks

**Comment by vsemozhetbyt** [comment]
It seems there are not many Icalendar experts in the team. Sorry, all I can do is just to mention these issues:

https://github.com/nodejs/help/issues/427
https://github.com/nodejs/help/issues/466
