### ISSUE TITLE
Require absolute path

### ISSUE THREAD

**Issue by wipronaveen21** [nodejs/help#503]
My project structure.

common
--usageguide
--appserver
--thirdparty
--node_modules
--server.js

In server.js

var express = require('express');

error:
Error: Cannot find module 'express'.

Please let me know how to give the path

**Comment by SomeoneWeird** [comment]
Do you have express installed? `npm install express --save`

**Comment by wipronaveen21** [comment]
Yes its installed and it was working. As per the new project requirement, I have moved node_modules folder inside thirdparty folder directory. This is the current directory structure.

---common
       --- usageguide
            ---appserver
                ---thirdparty
                     ---node_modules
               --server.js

**Comment by SomeoneWeird** [comment]
You need to keep node_modules at the root of your application folder if you want to use just `require('express')`, although you can get your current folder structure working if you do something like `require('./thirdparty/node_modules/express')` it's not recommended.

**Comment by wipronaveen21** [comment]
Thanks a lot for the reply
