### ISSUE TITLE
Nodejs Chat with express, socket.io , mongodb and front end AngularJS

### ISSUE THREAD

**Issue by ajithv11** [nodejs/help#504]
I would like to build a chat application using nodejs and socket.io. Before stating I would like to know public opinion for the resourses which I am planning to use.
My plan is to use nodejs and socket.io to handle backend and front end angularjs 1.x version. For database I use mongodb.

The chat scenario should include the following.

1.  one to one user chat

2.  Create groups (may be from an admin section, backend option or whatever). User can join the group, so it will work exactly like a chat room

My Concerns

In different posts, forums and tutorials I found that, they keep track of differnt groups and online members socket in simple javascript variables( json or array).

	Eg:- 
	var onlineUsers = [];
	Socket.username = username;
	Socker.room= room1; // Current user socket joins room1
	onlineUsers["user1"] = Socket;// socket for user1
	onlineUsers["user2"] = Socket;// socket for user2
	onlineUsers["user2"] = Socket;// socket for user3
	...........

For single one to one user chat, the socket is directly read from the variable onlineUsers to emit chat messages.
It works fine on my testing purpose.

But I am not sure if the above mentioned method is the best way to handle one to one chat if the online users number is large as the variable onlineUsers goes large.
(Concerns : If there is a limit for a the variable size as the socket object itself is a big object I guess ;))

**Note: My ultimate concern is about the size of the variable to store all sockets of online users, Is it the best way ? please advice**

**Comment by ajithv11** [comment]
Any suggestion for my requirement. I can start once I get a feedback from experts :)

**Comment by gerardramosm89** [comment]
Have you googled?

**Comment by aqrln** [comment]
@gerardramosm89 please be helpful. Such comments are discouraged here.

@ajithv11 if the issue is still of interest to you, I don't think there's any limit beyond the heap size, but you'll definitely have some tough time trying to scale this.
