### ISSUE TITLE
How to know if a file is already open ?

### ISSUE THREAD

**Issue by popod** [nodejs/help#505]
In macOS Sierra, I open a file with an application (of the os like textedit for a text file) and edit it without saving my changes. Then if I open the same file with fs.open() or an other open function, how to know that this file is already opened and tell the user to save and close the file before node calling fs.open() on this file ?

Is there a simple way to test if a file is already open by an other application on macOS, Windows and Linux with node ?

**Comment by popod** [comment]
@lordKnighton no solutions for this ? Why are you closed it ?

Thanks for reply :)

**Comment by lordKnighton** [comment]
Because this issue is a bit dated: months old. So since me or my cohorts here couldn't get to this on time. I presumed you would have had a solution for this. You are still facing this issue?

**Comment by popod** [comment]
@lordKnighton yes, I'm still facing this issue. Thanks, I will check this links.

**Comment by popod** [comment]
Hi @lordKnighton, thanks for your help, but I've tried the two solutions you provide and none of them solve my problem..

I do not know if this is an OS issue (I use macOS High Sierra) or the code I've tried itself.

Juste to be clear, I want do this: Before delete or move a file, I want to be sure that it is not opened by an other process/application. To check the solution you provide, I just run the examples codes provided and open a file on the default text editor. But the result is always the same when the tested file is open or not..

You can see this issue I opened in ronomon/opened#2.

Could you help ?
