### ISSUE TITLE
Unable to understand something in event loop

### ISSUE THREAD

**Issue by metalshan** [nodejs/help#506]
* **Node.js Version**: 7.0.0
* **OS**: OSX El-capitan
* **Scope (install, code, runtime, meta, other?)**: Doc
* **Module (and version) (if relevant)**:

The [documentation](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/) says a little confusing things about the event loop. It says in [timer phase](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#timers) event loop executes callbacks set by setTimeout etc. But again says "Technically, the poll phase controls when timers are executed."

I'm unable to understand in which phase the setTimeout callbacks are actually executed?

**Comment by bnoordhuis** [comment]
The I/O poll phase sleeps until either an I/O event happens or a timer expires.  The comment is a bit redundant because the poll phase controls everything: until it wakes up the process doesn't do anything.

**Comment by metalshan** [comment]
@bnoordhuis 
Thanks for the quick reply.

By "The comment is a bit redundant because the poll phase controls everything"; did you mean all callback executions are done in poll? So what does the timer or i/o callback phase do? They just pushes the callbacks into the poll queue, is it like this?

**Comment by metalshan** [comment]
Ah.. I'm sorry I'm not being able to link the dots.  :( :(

You are saying, timer and poll executes the callbacks on their respective phases. So what is the role of poll in timer script execution; as said in the doc, "Poll has two main function and one of them is Executing scripts for timers whose threshold has elapsed".

**Comment by bnoordhuis** [comment]
When polling, libuv calls epoll_wait() or whatever the platform's equivalent is with a timeout (max sleep period) that is the expiry time of the next timer.  So, the actual waiting is done by the poll phase, but the timer callbacks are done in the timers phase.

**Comment by metalshan** [comment]
Okay.. got your point. Documentation needs more work I think.
One more question. When the event loops starts for the first time; does it start from any specific phase?

**Comment by bnoordhuis** [comment]
It starts from the start, from the timers phase.

**Comment by metalshan** [comment]
Thanks for the answers. Closing the issue now.
