### ISSUE TITLE
My program could run on Mac, but error on Window

### ISSUE THREAD

**Issue by zhangyy985** [nodejs/help#509]
* **Node.js Version**: v6.2.0
* **OS**: win7
* **Scope (install, code, runtime, meta, other?)**: 
* **Module (and version) (if relevant)**:

 My program could run on Mac.
![9831b61e-fcf9-11e6-9949-6ee70aaf818a](https://cloud.githubusercontent.com/assets/24477874/23350461/1b804db0-fcfe-11e6-8b63-1d6f71be18e6.png)
But there are errors on Window.
![b815a850-fcf9-11e6-9f5d-d25b9c6e286d](https://cloud.githubusercontent.com/assets/24477874/23356782/78ea3798-fd1e-11e6-9c07-5c7579af31f6.png)

There are different kind of errors after running.
![099a2ae8-fcfa-11e6-8045-211d799a9ff5](https://cloud.githubusercontent.com/assets/24477874/23350477/323b7688-fcfe-11e6-9230-126104189acc.png)
![0adaf9b4-fcfa-11e6-8022-16e2582fc124](https://cloud.githubusercontent.com/assets/24477874/23350481/36032c2a-fcfe-11e6-8075-95b8d8294a24.png)
![0cd99928-fcfa-11e6-8496-84cc898a6fcb](https://cloud.githubusercontent.com/assets/24477874/23350489/39304d38-fcfe-11e6-8af2-fe8ed180dbf0.jpg)

**Comment by jkantr** [comment]
it's hard to tell from the information given, but this is almost certainly to do with pathing. When you are creating paths dynamically, you generally want to use the stdlib ```path``` module to make sure your paths are environment agnostic, an example:

```js
const path = require('path')
path.join(__dirname, '..', '..', 'assets', 'stylesheets', 'somefile.css')
```
This will make sure the right slash direction is used and the '..'s are then also resolved, etc.
