### ISSUE TITLE
Make a nodejs app logged in at linkedin for example

### ISSUE THREAD

**Issue by DLDante** [nodejs/help#51]
Hi, i want to log in my nodejs app in "linked in" with my user and password, and then use the cookie to manage my account data directly in my personal nodejs app, but i can't log in, with a rest client in my browser i can log in but from a https request in nodejs i can't, help me please

**Comment by kelthenoble** [comment]
Hey @DLDante did you make any progress with this, If I'm honest, I have an idea of what your talking about, but I't seems like you were typing this at a hundred miles per hour & it isn't to clear on what you're outcome you want from your app. I'm here for ya man, so let me know if you need any further help with this. :+1:

**Comment by kelthenoble** [comment]
Closing for now, but if you want to continue this discussion, please do so.
