### ISSUE TITLE
Node.js bindings in C++ code

### ISSUE THREAD

**Issue by hamid2c** [nodejs/help#510]
Hi, I'm trying to figure out all places in node.js source through which node.js connects to JavaScript world. For example, the place where I can find the implementation of process.binding("fs").read in node.js.

I would very appreciate any comment or suggestion in this regard?

**Comment by bnoordhuis** [comment]
It's the function `void Read(const v8::FunctionCallbackInfo<v8::Value>&)` in src/node_file.cc.

**Comment by hamid2c** [comment]
Thanks, I like to instrument node such that it profiles all the native functions (not just the read function in node_file.cc). What is the best way to do that? Should I instrument the class FunctionCallbackInfo in v8.h?

**Comment by bnoordhuis** [comment]
If you're on Linux, you can use `perf record -g <flags> node --perf_basic_prof script.js`, that will profile both C++ and JS code.   (`-g` collects call graphs; you almost always want that.)

**Comment by hamid2c** [comment]
Thanks a lot, I'm going to try that

**Comment by hamid2c** [comment]
Thanks again, in the call-graph I got from the command you suggested, I can see functions like v8::internal::Scanner::Next but many functions (including all the functions of my interest) are represented as binary addresses. Should I compile node with specific flags to get more useful information?

**Comment by bnoordhuis** [comment]
The default build contains debug symbols.  How did you build your node binary or where did you get it from?  Are you trying to profile a native module?  Are you using a recent version of perf?

**Comment by hamid2c** [comment]
I downloaded node source version 7.7.1 and I configured it with --debug. I used the perf shipped with Ubuntu 16.04 (perf version 4.4.44) and I didn't get human readable function names for the functions I'm looking for).

**Comment by bnoordhuis** [comment]
Sounds like it should work.  Can you post the first 100 lines or so of `perf report --stdio`?  What flags did you pass to `perf record` and did it write a file to /tmp?

**Comment by hamid2c** [comment]
Thanks a lot for your reply.
I used this command to record the data: perf record --call-graph dwarf  ./node --perf_basic_prof script.js
Also, I can see perf-4253.map in my /tmp directory upon recording.

Below is the first 100 lines of perf report:
# To display the perf.data header info, please use --header/--header-only options.
#
#
# Total Lost Samples: 0
#
# Samples: 76  of event 'cycles:pp'
# Event count (approx.): 17722522963056
#
# Children      Self  Command          Shared Object        Symbol                                                                                         
# ........  ........  ...............  ...................  .......................................................................................................................................................................................................................................................................................................................................................................
#
    62.04%     0.00%  node             [unknown]            [k] 0xffffffff8106b4f7                                                                                                                                                                                                                                                                                                                                                 
                       |
                       ---0xffffffff8106b4f7
                          |          
                          |--62.04%-- 0xffffffff811c1e34
                          |          |          
                          |          |--62.04%-- 0xffffffff8118f50e
                          |          |          _dl_check_map_versions
                          |          |          
                          |          |--0.00%-- 0xffffffff8118f422
                          |          |          0xffffffff813fd26b
                          |          |          v8::internal::FlagList::SetFlagsFromCommandLine
                          |          |          
                          |          |--0.00%-- 0xffffffff8118f534
                          |          |          |          
                          |          |          |--0.00%-- 0xffffffff8118f266
                          |          |          |          v8::internal::Counters::Counters
                          |          |          |          
                          |          |           --0.00%-- 0xffffffff8118f25c
                          |          |                     ucln_common_registerCleanup_58
                          |          |                     udata_setCommonData_58
                          |          |          
                          |           --0.00%-- 0xffffffff8118f496
                          |                     do_lookup_x
                          |                     _dl_lookup_symbol_x
                          |                     _dl_relocate_object
                          |                     dl_main
                          |                     _dl_sysdep_start
                          |                     _dl_start
                          |                     _dl_start_user
                          |          
                          |--0.00%-- 0xffffffff811c1c8e
                          |          0xffffffff811be180
                          |          0xffffffff812a2c76
                          |          |          
                          |          |--0.00%-- 0xffffffff81191515
                          |          |          |          
                          |          |          |--0.00%-- 0xffffffff8119dc96
                          |          |          |          0xffffffff812998f6
                          |          |          |          |          
                          |          |          |          |--0.00%-- 0xffffffff812e735d
                          |          |          |          |          |          
                          |          |          |          |          |--0.00%-- 0xffffffff8118f987
                          |          |          |          |          |          0xffffffff811dccb6
                          |          |          |          |          |          v8::internal::Snapshot::Initialize
                          |          |          |          |          |          v8::Isolate::New
                          |          |          |          |          |          
                          |          |          |          |          |--0.00%-- 0xffffffff8118f9ac
                          |          |          |          |          |          0xffffffff8119fbee
                          |          |          |          |          |          0xffffffff8119f9c5
                          |          |          |          |          |          0xffffffff8119f8b0
                          |          |          |          |          |          0xffffffff8119e92b
                          |          |          |          |          |          v8::internal::CodePatcher::CodePatcher
                          |          |          |          |          |          v8::internal::CodeAgingHelper::CodeAgingHelper
                          |          |          |          |          |          
                          |          |          |          |           --0.00%-- 0xffffffff8118f9a0
                          |          |          |          |                     _dl_lookup_symbol_x
                          |          |          |          |          
                          |          |          |          |--0.00%-- 0xffffffff812e761b
                          |          |          |          |          0xffffffff813c86a6
                          |          |          |          |          0xffffffff813c8552
                          |          |          |          |          0xffffffff813ca269
                          |          |          |          |          0xffffffff813c96a4
                          |          |          |          |          v8::base::RandomNumberGenerator::SetEntropySource
                          |          |          |          |          node::Start
                          |          |          |          |          
                          |          |          |          |--0.00%-- 0xffffffff812e7558
                          |          |          |          |          0xffffffff8129bc5b
                          |          |          |          |          0xffffffff812e02b8
                          |          |          |          |          v8::internal::Isolate::InitializeOncePerProcess
                          |          |          |          |          v8::internal::V8::InitializeOncePerProcessImpl
                          |          |          |          |          
                          |          |          |          |--0.00%-- 0xffffffff812e76a6
                          |          |          |          |          v8::internal::Bootstrapper::InitializeOncePerProcess
                          |          |          |          |          v8::base::CallOnceImpl
                          |          |          |          |          
                          |          |          |           --0.00%-- 0xffffffff812e76eb
                          |          |          |                     0xffffffff813c004b
                          |          |          |                     0xffffffff813bfe2e
                          |          |          |                     0xffffffff811ed267
                          |          |          |                     v8::internal::Logger::Logger
                          |          |          |                     v8::internal::Isolate::Isolate
                          |          |          |          
                          |          |          |--0.00%-- 0xffffffff8119dcaa
                          |          |          |          0xffffffff813ca45c
                          |          |          |          0xffffffff813c9fe6
                          |          |          |          0xffffffff813c3f7a
                          |          |          |          0xffffffff813c3cb3
                          |          |          |          0xffffffff815c1a8c

**Comment by bnoordhuis** [comment]
Okay, thanks.  I speculate that you need to upgrade your copy of perf.  I don't remember exactly when it was introduced but JIT support is a fairly recent addition.

It's pretty easy: download a recent linux kernel sources tarball and run `make -C tools/perf` from the top-level directory.  See `tools/perf/Makefile.perf` for more build options.

**Comment by hamid2c** [comment]
Thanks, I will try that

**Comment by hamid2c** [comment]
Just compiled and tried perf 4.10.1 (in linux 4.10.1). There are still mostly function-addresses instead of names. I have attached the output
[out.txt](https://github.com/nodejs/help/files/819319/out.txt)

**Comment by bnoordhuis** [comment]
Ah, but at least the output helps make it clear they're kernel addresses.  I guess I could have inferred that from the first listing seeing how they're all in the uppermost 2 GB of the 64 bits address space, but oh well.

You can install debug symbols for your kernel or you can filter them out by passing `-e cycles:upp` to `perf record`.  Which option is best depends on what you want to measure.

**Comment by hamid2c** [comment]
Thanks, I'd like to see symbolic names (not their addresses) of node functions which has been invoked.

**Comment by bnoordhuis** [comment]
Right, then `-e cycles:upp` or just `-e cycles:u` is what you want, it tells perf to profile only user-mode code.  (`-e cycles:k` is its complement if you're wondering.)

**Comment by gireeshpunathil** [comment]
Closing as answered. @hamid2c  - please re-open if this is still outstanding.
