### ISSUE TITLE
Not able to Access the Clinet Secret Id in Node JS application

### ISSUE THREAD

**Issue by kiranbalivada** [nodejs/help#514]
Node.js Version : 5.0.0
OS: Windows 10
Scope :Token Generation Using Google 0auth 2

Hi All,

In my Node JS application, we are using Client Secret ID for Google 0Auth 2. When I directly assign the static Client Secret ID to the google authentication key it is working fine. But when I read the value of Client Secret ID from a text box in the UI by code and assigned to google authentication key, on submit it is displaying an error message "the key is probably invalid". 

Can you please advice.

Following is sample code:

**function Verify(){
  var options={
       email: Client Secret mail
        key:  Client Secret ID,
        scopes: ['https://www.googleapis.com/auth/content']
  }
googleAuth.authenticate(options)**

Thanks ,
Kiran Kumar.

**Comment by lordKnighton** [comment]
https://github.com/theoephraim/node-google-spreadsheet/issues/38

see if this helps you:

![screen shot 2017-02-28 at 11 45 51 pm](https://cloud.githubusercontent.com/assets/1773260/23450446/1ab0f87c-fe10-11e6-89d8-1b85fbe2ecbf.png)

**Comment by kiranbalivada** [comment]
In My requirement keeping the P12 file in the solution folder would require a code checkin every time  each different client.

**Comment by lordKnighton** [comment]
This doesn't look like a `node-js` problem specifically, and I don't have knowledge of this tech. It would probably be better posted on `stackoverflow`. How ever if you post a terminal photo or a package.json pic, of the package. And as well, your full error log, then maybe i can help point you in the right direction.
