### ISSUE TITLE
module.js:338 throw err; Error: Cannot find module 'are-we-there-yet'

### ISSUE THREAD

**Issue by ismael-rivera** [nodejs/help#515]
* **v0.12.17**:
* **Mac OS X "Snow Leopard" 10.6.8**:
* **Scope (install, code, runtime, meta, other?) - Runtime**:
* **Module (and version) (if relevant)**:

I realize my system is very old and so is the version of node that I am running. Recently, I successfully upgraded from nodejs v0.10 to v0.12 which is as far as this system would allow. But now, I keep getting the error output I placed below whenever I try to run ANYTHING that is node related. My guess is based on the following stack trace line:

 at Object.<anonymous>/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/npmlog/log.js:2:16

My guess is that some file is still running dependencies based on previous version as apparently it is still in my system. Is there anyway I can fix this. YES, I know my system is old. No, I cannot upgrade. This computer is on it's way out but I still use it for some crucial tasks. 

Thanks

Bare in mind. The following is not javascript. It's an error stack trace from the output I get when I try to run gruntjs or npm install from any dir in my system.

```js

module.js:338
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```
-->

**Comment by bnoordhuis** [comment]
> My guess is that some file is still running dependencies based on previous version as apparently it is still in my system.

That would be my working hypothesis too.

I think homebrew will simply let you `rm -rf /usr/local/Cellar/node/0.10.26` (or `brew unlink`) and be on your merry way.

**Comment by ismael-rivera** [comment]
Thanks. I will try that.

**Comment by lucamjj** [comment]
@ismael-rivera have you sorted it? Happening the same thing here.
