### ISSUE TITLE
How to halt nodejs from native addon?

### ISSUE THREAD

**Issue by bedeho** [nodejs/help#516]
* **Node.js Version**: v7.4.0
* **OS**: Ubuntu 16.04.1 LTS
* **Scope (install, code, runtime, meta, other?)**: code

How does one gracefully shutdown the node process from a native addon?

**Comment by bnoordhuis** [comment]
I assume `exit(0)` doesn't count?  If so, then the answer is "you don't."

Node exits when there is nothing left to do, i.e., when all connections, servers, timers, etc. are closed or expired.
