### ISSUE TITLE
node --inspect script to open chrome

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#517]
On Node version 6.9.1, on very new version of MacOS

Now that `node --inspect` is a built-in flag, I figure this question might be appropriate.

I am trying to write a script that will tell Chrome to open the `node --inspect ` chrome-devtools link in a browser window so I don't have to manually copy the link which can get old.

This is what I have:

```
#!/usr/bin/env bash

cd $(dirname "$0")

(kill -9 $(lsof -i:3050 -t) 2> /dev/null) || echo "server was not running"
(kill -9 $(lsof -i:9229 -t) 2> /dev/null) || echo "chrome-devtools was not running"

wait;

export PATH=$PATH:/Applications/Google\ Chrome.app/Contents/MacOS/

(node --inspect --debug-brk bin/www.js $@ &> debug-server.log) &
sleep 1;
LINE=$(grep -n "chrome-devtools" debug-server.log | awk '{print $2}')
echo " => Supposed chrome-devtools link => '$LINE'";
Google\ Chrome "${LINE}"
```

The script almost works except the last line: chrome doesn't open the right url, and I get the following if I run it manually at the command line:

```
ALEXAMIL-M-914U:cdt-now alexamil$ Google\ Chrome "chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/aed5c46f-0a4a-4fea-b28c-d74d71b87352"
ALEXAMIL-M-914U:cdt-now alexamil$ [38861:40963:0302/163711.577805:ERROR:upload_data_presenter.cc(77)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader &)
[38861:40963:0302/163711.627982:ERROR:upload_data_presenter.cc(77)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader &)
[38861:40963:0302/163711.781884:ERROR:upload_data_presenter.cc(77)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader &)
[38861:40963:0302/163711.870102:ERROR:upload_data_presenter.cc(77)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader &)
[38861:40963:0302/163712.047017:ERROR:upload_data_presenter.cc(77)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader &)


```

and ideas on how to get this to work?

I have an SO question open about this too:

http://stackoverflow.com/questions/42568029/open-url-given-by-stdout-from-node-inspect-command

I will update the answer on there if we arrive at anything!

thanks

**Comment by bnoordhuis** [comment]
The ERROR log messages make me think you've hit a bug in Chrome.  If your copy of Chrome is up-to-date, consider reporting it to that project.

**Comment by ORESoftware** [comment]
thanks, so weird that when you paste the url in the browser it works, but from command line it doesn't, yeah will do

**Comment by lordKnighton** [comment]
Closing for now, I apologize if you wanted to keep open, reopen if so.
