### ISSUE TITLE
Promise.all with Map

### ISSUE THREAD

**Issue by TarSzator** [nodejs/help#519]
Hello,

I tried today to run Promise.all with a Map (since it is an iterable) but the then is called before the promises are executed.
Node 6.9.2

Before I create an issue I would like to ask if this is a known thing and I just failed to see that this feature is not jet implemented in 6.9.2

**Comment by bnoordhuis** [comment]
Can you post a (standalone) example of code that you expect to work but doesn't?

**Comment by TarSzator** [comment]
`function delayPromise(id) {
	return new Promise((resolve, reject) => {
		try {
			setTimeout(() => {
				console.log('Promise executed', id);
				resolve(id);
			}, 1000);
		} catch (error) {
			reject(error);
		}
	});
}

let map = new Map();
for (let i = 1; i <= 5; i++) {
	map.set({id: i}, delayPromise(i));
}

Promise.all(map).then(resultMap => {
	resultMap.forEach((result, key) => {
		console.log('Key:', key, ', Result:', result);
	});
	console.log('Promises done');
}).catch(error => {
	console.error(error);
})

console.log('Sync process done');`

**Comment by bnoordhuis** [comment]
Thanks, I see what you mean.  Is that code supposed to work according to the spec though?

Yes, a map is an iterable but iterating over it in the `for (const entry of map)` sense yields key/value pairs, not values.  Your example works when you call `Promise.all(map.values()).then(...)`.

**Comment by TarSzator** [comment]
Thanks. Good thing than that I did not open an bug issue :-)

**Comment by stanislavzadiraev** [comment]
It is not a problem f a `Map`. It is a problem of `Promise.all`. 
For exaple:
```
Promise.all(new Map()
    .set('key', fs.promises.readFile('localhost-key.pem'))
    .set('sert', fs.promises.readFile('localhost-cert.pem'))
  )
  .then((files) =>
    http2.createSecureServer({
      key: files.get('key'),
      cert: files.get('sert')
    })
  //...
  )
```
It does not work.
How does `Promise.all` recognise and support `Map` if it does not?

**Comment by al-the-x** [comment]
Maybe of help: https://gitlab.com/snippets/1867177

`Object.entries` can be replaced with `Map.prototype.entries` if desired.
