### ISSUE TITLE
multi ajax call , TTFB too slow

### ISSUE THREAD

**Issue by serenahamilton-engineer01** [nodejs/help#52]
Client have a ajax call , just like:
      post_data = "keyword=" + keyword.value;
      $.ajax({
          type:"POST",
          url:"TooltipSearch",
          data:post_data,
          dataType:'json',
          success:function(data)
          {
              console.log(data)
          }
      });

Server /TooltipSearch like:
app.post('/TooltipSearch', function(req, res){
	var Tooltip_param = '{"Keyword": "'+ req.body.keyword +'"}';
	var search = require('./build/Release/florida');	
	var data = JSON.parse(search.v8access(16, Tooltip_param));
	
	if (data.length > 0) {
		console.log(data);
		result = {result:1,content:data};
	}
	else {
		result = {result:0, error_msg:'no data!'};
	}

        res.contentType('json');
        res.json(result);
});

the TooltipSearch get data is Average 1.3 seconds
but, when i try to call multi ajax call at the same time e.g. 5 times , 
ajax isn't async process , about 6.5 seconds after the last ajax call get response.
Can anyone tell me why this? And how to adjust node js to make ajax normal asynchronous processing. thank you very much~

**Comment by baslr** [comment]
try to require florida global?

```
var search = require('./build/Release/florida');

app.post( …
```

**Comment by serenahamilton-engineer01** [comment]
I tested it get as global, but still can not asynchronous processing ajax call..
===
I have tried using google query possible problems, has seen the release of the recording session may be a relationship, but I did not use session within this program, currently still do not know how to solve this problem ...

**Comment by lordKnighton** [comment]
@serenahamilton-engineer01 closing for now, feel free to reopen & will take it from there.
