### ISSUE TITLE
Lost/missing data on Unix Domain Socket

### ISSUE THREAD

**Issue by ForeverACE** [nodejs/help#521]
* **Node.js Version**: 4.4.3
* **OS**: Raspbian 8 (jessie)
* **Scope**: code

I've created a unix domain socket server (via node.js) so I can pass data from several bash scripts to my node.js program. The problem I'm having is that I occasionally miss entire messages on the node.js side. This seems to be a timing issue as if I add delays between messages, each arrives as expected. The problem seems to be with data arriving quickly (I think).

Below is code for the server side implementation which is actually called from other code. For debugging purposes, I'm only calling this code and allowing the server.on("data") to call a function shown here (i.e. UnixSocketData). This function does no processing; it just logs the data it receives. Occasionally, this function doesn't log the data sent to it.

What am I missing or doing wrong?

See bottom snippet for sample bash code that sends data to the unix domain socket.

```js
//======================================================
// require other modules
var fs = require('fs'),
    net = require('net');
//======================================================
// Global Variables
var gUnixServer = null;                             // Unix domain socket server
var gClients = new Array();                         // Currently connected clients
var gNextClientID = 0;                              // ID to be assigned to the next client
var gGotDataCB = null;                              // Function called when data received via unix port
var gServerReadyCB = null;                          // Function called when server is running/ready
//======================================================

exports.start = function(receivedDataCallBack, serverReadyCallBack)
{
  // Register callback functions
  gGotDataCB=receivedDataCallBack;
  gServerReadyCB=serverReadyCallBack
  openUnixSocket(); // Start listening for connections
}

exports.stop = function()
{

  gUnixServer.close(); // Stop the unix port server

  // Reinitialize for possible server restart
  gClients = new Array();
  gNextClientID = 0;
  gUnixServer = null;
  gGotDataCB = null;
}
/*
 * Start a UNIX socket server to allow OS/bash messages to be passed
 * to main program
 */
function openUnixSocket()
{
  gUnixServer = net.createServer(newUnixConnection);
  gUnixServer.listen('/var/run/customPortServer');
  console.log('Listening on /var/run/customPortServer');
  gServerReadyCB(cVersion);
}
/*
 * Received a connection request on the UNIX socket
 * Parameters:
 *  client - the client socket requesting connections
 */
function newUnixConnection(client)
{
  client['CHInfo'] = {ID: getNextClientID()};

  console.log('Got a connection on the UNIX port ID:'+client['CHInfo']['ID']);
  client.on('close', unixSocketClosed);
  client.on('data', unixSocketData); // TODO: added for debugging purposes
  //client.on('data', gGotDataCB); // TODO: This was removed for debugging purposes
  
  gClients.push(client);
}
/*
 * get the next available client connection ID
 * Returns:
 *  The ID to use for the new Client;
 */
function getNextClientID()
{
  var temp = gNextClientID;
  gNextClientID++;
  return temp;
}
/*
 * UNIX port connection has been closed - remove it from the list of clients
 */
function unixSocketClosed()
{
  console.log('UNIX Connection closed ID:'+this['CHInfo']['ID']);
  for(var z = 0; z < gClients.length; z++)
  {
    if(gClients[z]['CHInfo']['ID'] == this['CHInfo']['ID'])
      gClients.splice(z, 1);

  }
}
/*
 * Received data on the UNIX domain socket
 * Parameters:
 *  buff - byte buffer contain the data Received
 */
function unixSocketData(buff)
{
  console.log(buff.toString());
}
```

bash script
```bash
#!/bin/bash
mkfifo /tmp/socketServer.fifo

# open connection to node.js socket server (prevents constant opening & closing of socket for every message)
tail -f /tmp/socketServer.fifo | nc -U /var/run/customPortServer &
netcat_pid=$!

# EOL used to parse data (allows partial frames)
echo "{ \"msgCode\": \"log\", \"data\": \"some data here\"}EOL" > /tmp/socketServer.fifo
echo "{ \"msgCode\": \"log\", \"data\": \"some more data here\"}EOL" > /tmp/socketServer.fifo

# You get the idea, do some action, send more messages to the socket/port

kill $netcat_pid
rm /tmp/socketServer.fifo
```

**Comment by lordKnighton** [comment]
Hey did you ever fix this?

**Comment by ForeverACE** [comment]
No. Increasing the delay seems to help reduce the chance of lost data but I still lose data. Unfortunately, I haven't had time to come back to this to figure out a workaround or fix.

**Comment by lordKnighton** [comment]
well do you want to pursue this issue? Or are you ok?

**Comment by ForeverACE** [comment]
If there's a fix or workaround, that would be great! I haven't been actively working on it because my deadline is next week and I have a lot of work still to do on my program.

If you have suggestions, I can set aside some time to try them out. Any input is greatly appreciated.

**Comment by lordKnighton** [comment]
Look I don't have much experience with this tech, but i have just spent time on google searching for answers. And of the top, it looks like delaying the sockets is your best bet. Because they are extremely fast. 

And i don't see anything minus this post about unix sockets on Raspbian 8. The only thing i think we can do is scale down the problem. I'm on the net docs & if you want to continue top optimize your current code. We can try something from there. If you wish to give it a go. Let me know.

**Comment by ForeverACE** [comment]
I don't think the problem is on the unix socket OS implementation side because I haven't seen any lost data if I just dump data to the port and output it to the terminal or file via a bash listener script. I believe the issue is on the Node.js side. I would have expected the data to be buffered and processed as there were available cycles. If I take node out of the equation, it seems to buffer okay (even if there's a momentary delay because of a busy CPU).

I'd like to find a solution other than just adding delays (if possible) but I realize that it might not be possible.

I'm not sure I follow your second paragraph. How would you recommend optimizing my code?

**Comment by lordKnighton** [comment]
Optimize, fix the issue so you don't have to have work arounds in your code.

**Comment by ForeverACE** [comment]
Sounds good to me. I'm willing to spend some time to try to figure out what I'm doing wrong or how to do it better.

**Comment by lordKnighton** [comment]
Cool, so can you create another file & comment out the problematic one. I want you to scale down the problem.

**Comment by lordKnighton** [comment]
http://unix.stackexchange.com/questions/26715/how-can-i-communicate-with-a-unix-domain-socket-via-the-shell-on-debian-squeeze

Have you seen this post?

**Comment by ForeverACE** [comment]
I've seen that link and similar methods which was why I thought I might be able to do the same with node.js. In my case, my bash script pipes the output of a fifo to netcat (nc) to send data on the unix socket. I've done it that way because it keeps the connection to the open. If I send commands they rhey do it in the link youbprovided,

**Comment by ForeverACE** [comment]
Damn typing on a phone! Lol.

Anyways, If I send commands like they are doing in the link you provided, it repeatedly opens and closes the unix socket connection to the server. This results in unecessary avtivity on the node.js side where it's constantly opening and closing the connection.

**Comment by lordKnighton** [comment]
or you on your laptop or pc right now?

**Comment by ForeverACE** [comment]
I'm typing from my phone. I had a popup message and went to click it and accidentally clicked the close button that closed the thread.

Any code changes I make will have to happen tomorrow while I'm at work as I only have access to the hardware during business hours. Having said that, I can strategize about what to try.

I have stripped back the code quite a bit previously but didn't get very far. I will look over my notes tomorrow and see if I was getting all the data via the unixSocketData callback function or if it was lost when passed to the other main process.

I just noticed that I missed the code sample you provided. So based on what you show, that would actually be the bash script side and not written in node.js. Essentially, I have several bash scripts that are initiated via node and need to report their progress to the node app. So, I create a unix socket server with node.js, launch the bash script(s), they create a fifo that pipes data to netcat (to keep the server connection alive) which is connected/talking to the node.js unix socket server. The data the server receives then updates the GUI so the user knows whats2 currently happening with the bash scripts.

I hope this makes sense.

**Comment by lordKnighton** [comment]
Nope, it makes no sense at all. lol But tomorrow is a good idea, just cc me when your at work. we will keep going like  energizer bunny until we fix this though. So tomorrow it is. Bye for now.

**Comment by ForeverACE** [comment]
Thanks for the help. Cheers.

**Comment by ForeverACE** [comment]
I'm at work right now and have scaled back my program to essentially what was provided above. I basically have three components:
1) unixSocketServer.js - handles opening and closing of server and passing received data (see sample node.js code in original post)
2) mainPgm.js - basic program (represents my main program) that just calls unixSocketServer.start() & .stop() along with passing callbacks.
3) sendMsg.sh - basically the original bash script in my first post (with some minor modifications). This currently loops 100 times and outputs a message with the corresponding step of the loop (i.e. it counts from 1 to 100). This script creates a fifo, connects that fifo (via netcat) to the unix socket created by unixSocketServer.js

If I have the data written directly to the console using unixSocketServer.js (i.e. NOT pass it to mainPgm.js), it seems to get all the data (I cannot 100% guarantee that because data loss has been intermittent). If, however, I use the callback provided by mainPgm to log the data, I more reliably get data loss. If I add a delay when first setting up my connection between the bash fifo and unix domain socket, at this point, I seem to get all of my data. 

I'm going to run a bunch of load tests to see if I'm truly getting everything and then scale back up with my actual main program to see what happens.

**Comment by ForeverACE** [comment]
If I add processes to increase the CPU workload, I get lost data again. I believe the node.js event loop might just be missing the data. I had thought that it would be buffered but this doesn't seem to be the case. I might be stuck with what I have without a total overhaul of this method. I will keep investigating but I may have just run into a limitation with the way I'm doing it.

**Comment by sam-github** [comment]
I'm not clear, do you have an up-to-date reproduction? Is it in this thread somewhere?

**Comment by lordKnighton** [comment]
Hey where is `cVersion`  coming from? 

![screen shot 2017-03-31 at 11 48 01 am](https://cloud.githubusercontent.com/assets/1773260/24564758/ecc13070-1607-11e7-863b-19965df1b0ad.png)

**Comment by ForeverACE** [comment]
> I'm not clear, do you have an up-to-date reproduction? Is it in this thread somewhere?
Give me a few minutes and I'll post my current test version.

> Hey where is cVersion coming from?
It was an oversight in my original post. It should have been in the unixSocketServer.js file.

FYI, I'm leaving work in less than an hour but I think I've made progress. I will update you shortly.

**Comment by lordKnighton** [comment]
that's what i'm talking about #progress baby 👍

**Comment by ForeverACE** [comment]
Okay, so I've attached my test version of the files I'm using. I do the following to test the setup:

1. Start the unix socket server and output the console messages to a file by running:
`node mainPgm.js > output &`
1. Send 200 messages to the server and keep a log of the messages sent:
`./sendMsg.sh`

The bash script now creates a temporary file rather than a FIFO and pipes the output of the file to the unix domain socket. I noticed that if I connected several listeners to the FIFO and cranked up the CPU usage, I would get packets going to some listeners but not all. One scenario simply had two processes using tail and piping it to two separate files. In this case, I had some data going to one file and the rest going to the other. I'm not sure how valid a test that was but it made me re-evaluate the FIFO to begin with.

I believe node.js may not be reading the socket quickly enough which is causing the FIFO to pause or throw a SIGPIPE error. By changing to writing to a temporary file rather than a FIFO, I can change how the data is being buffered. At this point, I'm able to start four processes compressing random data (to busy up the CPU) and use the attached test files without losing any data. I believe this may be the fix but I need to do further testing. I will keep you guys posted and I appreciate the input. Also, if you have a better explanation of why one wasn't working and the other was, I'm open to it. My summary is based on my limited knowledge of the OS inter-processes.


[mainPgm.zip](https://github.com/nodejs/help/files/886647/mainPgm.zip)

**Comment by ForeverACE** [comment]
I've done several tests including running my test programs while using 'stress' to busy up the CPU and the I/O and haven't seen one missing message. I believe I've found a fix/workaround (see my last post).

I'm a little surprised and disappointed that I couldn't just use a FIFO but this seems to work fine and has minimal impact on my program (i.e. I only had to make a change to one line of code).

Thanks to @sam-github and, especially, @lordKnighton for your interest and input; collaboration makes things easier and I hope this thread will help others.

**Comment by kael-shipman** [comment]
Hey all,

I'm having the same issue here. @ForeverACE, just to confirm, your solution didn't actually _solve_ the problem, it just got around it, right? I'm in a situation where I need to make call to a service that returns a meaningful response (i.e., I can't just use a tmp file). Here's what I've done:

* I verified that the calls work as expected if you space them out with a `setInterval`.
* I then registered listeners that console log on EVERY POSSIBLE EVENT on the client socket connection.
* Then I added a "write buffer full handler," i.e., I pause writing if I get `false` back after `socket.write` and resume when I receive a "drain" event (though this mechanism is never triggered).

What ends up happening is that all of the calls are written (5 in this case), but only two of them ever make it to the server. No error events are ever fired, and nothing else out of the ordinary seems to be happening. The data is just simply lost.

This seems like a HUGE bug in node. I don't think this issue should be closed....

**Comment by ForeverACE** [comment]
@kael-shipman, it's been a while since I have worked on this issue but I can tell you, in general terms, what I found.

In my case, it appeared to me that the problem was with passing messages via multiple callbacks. I had created a library which created a Unix Domain Socket server which was instantiated via a main process. If the library directly processed the data, things seemed to work okay. However, if I had the library pass the data via a callback to the main process, I would occasionally lose data.

I ideally wanted to have my bash script directly send data to the main process via the unix domain socket but I couldn't get it to happen reliably. I added a temporary file to allow a quasi-buffer as I believed that Node.js wasn't queuing the messages/events properly. As I couldn't guarantee 100% that my suspicions were correct, I didn't feel it was fair to leave the ticket opened as I seemed to be the only one with the problem and I had a workaround.

Based on my experience, it seemed to me that if the Node.js event loop got too busy, it would sometimes result in messages being combined (either multiple messages or message fragments). I ended up adding custom start and end of message markers so I could make sure my callback could properly identify complete messages and buffer any others where they were either multiple messages and/or message fragments. Using this method (along with the intermediate file), I was able to 100% reliability.

I'm wondering if you implement your own SOF and EOF to your messages, you can use them to make sure you aren't getting multiple messages per event on your server. Given that you're only sending 5 messages and missing 3 of them, it sounds like there might be another issue. In my case, I was rapidly firing 20 - 30 large messages within a few seconds and missing, maybe, 2 or 3.

**Comment by kael-shipman** [comment]
Thanks for the info! After much more debugging, it actually looks like I haven't fully identified the problem. My original setup used a PHP server listening on the socket and a node client connecting to it. That was the setup in which I got the above described behavior. To try to narrow the problem area, I created a simple test node server and used the same client on it. With that setup, the messages seemed to arrive correctly, but the response were chunked significantly differently than with the PHP server.

Anyway, more debugging to do.... I'll try to update this thread if I discover anything else.

**Comment by sam-github** [comment]
> Based on my experience, it seemed to me that if the Node.js event loop got too busy, it would sometimes result in messages being combined (either multiple messages or message fragments).

Node only supports stream sockets in the Unix domain, so this is indeed what should happen. You can't rely on a single write of a packet at the sender be received as a single packet (this is the same as TCP). You can use datagram sockets in the unix domain, but you'll need an external module to do that (https://github.com/bnoordhuis/node-unix-dgram, the unix domain equivalent of UDP). Or you can add packet structure to your messages, probably a better approach.

**Comment by jessereitsma** [comment]
I might have the same issue, where we have a Go script and a Node.js script.
It seems that messages I'm trying to send from Node.js over the socket, not always make it to the Go application. It all worked fine untill I started sending some more messages at the same time.
Not exactly sure what caused it, but we figured out that Go never received the messages I tried to send from Node.js
I switched from unix sockets to TCP connections, and we didn't have the problem anymore.

The Node.js part:
```javascript
// Create connection
client = net.createConnection(process.env.SOCKET_ADDR);

// Write to client
// Payload is normal javascript object
client.write(JSON.stringify(payload) + '\n');
```

It's hard to debug if Node.js didn't send the message to the socket, or Go never received it, and which "fault" it actually is.

**Comment by sam-github** [comment]
@jessereitsma Use strace, you can see the network calls made by the process, should allow you to find where its dropped. https://gist.github.com/jhass/5896418 might help as well.

**Comment by ForeverACE** [comment]
> Node only supports stream sockets in the Unix domain, so this is indeed what should happen. You can't rely on a single write of a packet at the sender be received as a single packet (this is the same as TCP). You can use datagram sockets in the unix domain, but you'll need an external module to do that (https://github.com/bnoordhuis/node-unix-dgram, the unix domain equivalent of UDP). Or you can add packet structure to your messages, probably a better approach.

Something that I originally overlooked that @sam-github pointed out a few years ago was that Node didn't support Unix domain sockets as I had expected (see the quote above). If I were doing it again from scratch, I might change to a datagram socket as suggested but I've already written my own framing and buffer library around the Unix socket so I will continue using it that way. It's worked well but I suspect the datagram library probably would have saved me some time and headaches.

If you're using Unix Domain sockets like I did, you're probably running into the same thing where data isn't necessarily being dropped but requires some buffering (as you may be getting message fragments or messages mashed together).

Good luck!

**Comment by jessereitsma** [comment]
Thanks for your reply @ForeverACE
I currently swapped to TCP connection rather than unix sockets.
Is there any way why I should go with unix sockets instead?
My use-case is running Node.js and Go in different Docker containers on a Raspberry Pi, where Go handles (amongst others) the GPIO

**Comment by ForeverACE** [comment]
@jessereitsma probably not. On a modern system (both hardware and GNU/Linux), TCP via loopback address will be extremely fast. However, if you need faster throughput and/or lower CPU usage, you want to use Unix Domain sockets as it has much less overhead (even when piping through something like netcat). The entire purpose of Unix domain sockets is inter-process communications (IPC) so are probably the fastest method of communications between two processes. They're also easy to implement; in one of my applications, I have a bash script outputting to a unix socket on which Node is listening. Debugging can be done simply by attaching a netcat connection.

Having said all of this, the company that I work at is changing most IPC to TCP or websockets because of ease of maintenance. This allows IPC or external communication between modules/applications.
