### ISSUE TITLE
Error: connection timed out

### ISSUE THREAD

**Issue by FrenchMajesty** [nodejs/help#524]
* **Version**: 7.5
* **Platform**: Darwin VerdiKs-MacBook-Air-2.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
* **Subsystem**:

I have a problem with my node web application.

After some time my connection would timeout and my server would crash. This is the error message I am getting:

```
>  Error: connection timeout
>     at Db.<anonymous> (/Users/Verdi/Documents/Church2/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
>     at emitTwo (events.js:106:13)
>     at Db.emit (events.js:192:7)
>     at Server.listener (/Users/Verdi/Documents/Church2/node_modules/mongodb/lib/db.js:1798:14)
>     at emitOne (events.js:96:13)
>     at Server.emit (events.js:189:7)
>     at Server.<anonymous> (/Users/Verdi/Documents/Church2/node_modules/mongodb/lib/server.js:274:14)
>     at emitOne (events.js:96:13)
>     at Server.emit (events.js:189:7)
>     at Pool.<anonymous> (/Users/Verdi/Documents/Church2/node_modules/mongodb-core/lib/topologies/server.js:335:12)
>     at emitOne (events.js:96:13)
>     at Pool.emit (events.js:189:7)
>     at Connection.<anonymous> (/Users/Verdi/Documents/Church2/node_modules/mongodb-core/lib/connection/pool.js:270:12)
>     at Object.onceWrapper (events.js:291:19)
>     at emitTwo (events.js:106:13)
>     at Connection.emit (events.js:192:7)
>     at Socket.<anonymous> (/Users/Verdi/Documents/Church2/node_modules/mongodb-core/lib/connection/connection.js:185:10)
>     at Object.onceWrapper (events.js:291:19)
>     at emitNone (events.js:86:13)
>     at Socket.emit (events.js:186:7)
>     at Socket._onTimeout (net.js:342:8)
>     at ontimeout (timers.js:365:14)
```

Since I am fairly new to Node I don't know how to interpret this and Google hasn't been helpful in helping me figuring it out.

I think it has to do with my database and/or the way I am connecting to it. 

I have one ' mongoose.connect ' in my user model and I create multiple connections (' mongoose.createConnection ') throughout my application.

I thought that maybe the fact that I opened connection but never closed them was the problem so I tried adding db.close() in (what I think to be) the appropriate places but when I do that my application has a never-ending loading issue.

I appreciate any help.

**Comment by lordKnighton** [comment]
Hey @FrenchMajesty did you solve this, or you still need help with this issue?

**Comment by yongkylie** [comment]
I'm facing the same issue using mongoose in my small chatting app project. I need to restart my app daily to keep this error away. It seems like I need to set my session's timeout while connecting to mongoDB but I still don't know where to start. Any suggestion?

**Comment by FrenchMajesty** [comment]
@lordKnighton I still need help.

@yongkylie , What helped me lower the amount of timeouts is to pool my db connections. Before that I was creating connections to the db and I sometimes wouldn't even close them!

My amount of timeouts drastically lowered after doing this.

**Comment by lordKnighton** [comment]
Sorry for playing git tag @FrenchMajesty 

@FrenchMajesty & @yongkylie if you guys still haven't solve your issue email: keltheceo@gmail.com
& give me the deets as your terminal & browser javascript console.

But if you guys have fixed this problem, close issue.
I apologize for not responding on time #busy
