### ISSUE TITLE
How can I simply console.log on each event loop cycle ? 

### ISSUE THREAD

**Issue by Skahrz** [nodejs/help#526]
How can I simply console.log on each event loop cycle using nodejs ? I need some informations concerning micro/macro tasks, like knowing which one is executed first, if every microtasks are executed in the same cycle etc...

Thanks for your help

**Comment by targos** [comment]
you can schedule immediate callbacks like so:
```js
function scheduleImmediate() {
    setImmediate(function() {
        console.log('cycle');
        scheduleImmediate();
    }); 
}
scheduleImmediate();
```

**Comment by Skahrz** [comment]
Thanks for your answer, but I don't think it's what I m looking for.

I m having the following little code :

```javascript
let i = 0;

function scheduleImmediate() {
	if (i >= 3) return;
	setImmediate(function () {
		console.log('cycle');
		i++;
		scheduleImmediate();
	});
}
scheduleImmediate();

setTimeout(() => console.log('0'), 0);
setTimeout(() => console.log('1'), 1);

Promise.resolve('Promise').then(res => console.log(res));
Promise.resolve('Promise1').then(res => console.log(res));
```

And here's my output :

```
Promise
Promise1
0
1
cycle
cycle
cycle
```

The idea behind my question was to be able to *prove* that microtasks are executed in the *same* event loop cycle, while macro tasks needs 1 cycle by task. What I wanted to prove to myself is something like that :

```javascript
---- Start ----
Promise // microtask 0
Promise1 // microtask 1
End of Cycle

0 // macrotasks setTimeout 0
End of cycle

1 // macrotasks setTimeout 1
End of cycle
```

**Comment by addaleax** [comment]
Mh, just just to avoid confusion, it is not guaranteed that timers with different durations are not executed within the same event loop cycle…

**Comment by lordKnighton** [comment]
@Skahrz you good, you fixed the issue or still in more need of guidance?
