### ISSUE TITLE
Why does Node.js only contain English for Intl by default?

### ISSUE THREAD

**Issue by goloroden** [nodejs/help#527]
Basically, the title already says it all: In contrast to browsers, Node.js only contains English for `Intl`. Is there a special reason for this, i.e. why there is no support for other languages included by default?

**Comment by vsemozhetbyt** [comment]
This can help:

https://github.com/nodejs/node/blob/master/BUILDING.md#intl-ecma-402-support
https://github.com/nodejs/node/wiki/Intl

**Comment by goloroden** [comment]
Thanks for your quick reply, but my question was not how to achieve support for more languages, but why it is limited to English by default:

> Intl support is enabled by default, with English data only.

(Source: https://github.com/nodejs/node/blob/master/BUILDING.md#intl-ecma-402-support)

Why is that? Why English only?

**Comment by vsemozhetbyt** [comment]
It seems [this is the cause](https://github.com/nodejs/node/issues/8500#issuecomment-246432058):

> The reason node is built with a smaller ICU by default is file size.

**Comment by goloroden** [comment]
Great, thanks :-)
