### ISSUE TITLE
require vs ES6 import

### ISSUE THREAD

**Issue by yarax** [nodejs/help#53]
Are there any plans to move from CommonJs modules to ES6 modules and import syntax?

**Comment by bnoordhuis** [comment]
You can find some discussion about `require()` vs. `import` [here](https://github.com/nodejs/NG/issues/5) and there's more discussion scattered across various repositories.

In a nutshell, `require()` is not going anywhere - removing it would break too much for too little gain - but we'll almost certainly end up supporting ES6 import/export somehow, details TBD.

Support for ES6 modules first needs to land in V8.  The tracking bug is [here](https://bugs.chromium.org/p/v8/issues/detail?id=1569) but it's blocked by finalization of [the module loader spec](http://whatwg.github.io/loader/).

**Comment by yarax** [comment]
@bnoordhuis thanks!

**Comment by romu70** [comment]
Hi,
Newbie question, if I write a ES6 class, like this one:

```
'use strict';
  
class User {
  constructor(username, email) {
    this.email = email;
    this.username = username;
  }
}```

What's the correct syntax to export this class as a module? Tried many things ```export class...```, ```module.exports = class...```, ```export User as User```, nothing seems to work, so I guess I make a mistake somewhere.

Thanks.

**Comment by bnoordhuis** [comment]
@romu70 import/export isn't supported yet but `module.exports = ...` should work:
```javascript
// a.js
class A {
  // ...
}
module.exports = A;
```
Or:
```javascript
module.exports = class B {
  // ...
};
```

**Comment by StyMaar** [comment]
> Support for ES6 modules first needs to land in V8. 

Why ? The current module syntax doesn't rely on any V8 support to work and `import`/`export` can be transpilled to this model. Node's concerns about module loading and browsers' ones are quite different. 
I don't really understand how the whatwg module loader spec should affect Node, as long as the `import`/`export` semantic is already specified.

**Comment by bnoordhuis** [comment]
Is your question "why won't node.js support import/export until V8 does"?  Because node.js doesn't parse JS code, V8 does, and we're not a transpiler.

**Comment by StyMaar** [comment]
Fair enough, thanks.

**Comment by paulwalker** [comment]
Does v5+ of V8 (and consequently nodejs v6) support es6 modules yet?

**Comment by bnoordhuis** [comment]
@paulwalker No, not yet.  Maybe in node.js v7.

**Comment by styfle** [comment]
You can star [v8 Bug 1569](https://bugs.chromium.org/p/v8/issues/detail?id=1569).

**Comment by franciscop** [comment]
@lordKnighton why was this issue closed? I'd love to see this implemented as well

**Comment by getkey** [comment]
@lordKnighton 
> Support for ES6 modules first needs to land in V8. The tracking bug is [here](https://bugs.chromium.org/p/v8/issues/detail?id=1569) but it's blocked by finalization of [the module loader spec](http://whatwg.github.io/loader/).


> You can star [v8 Bug 1569](https://bugs.chromium.org/p/v8/issues/detail?id=1569).

**Comment by SamMorrowDrums** [comment]
Just came back here for an update. Currently there is blocking bug. https://bugs.chromium.org/p/v8/issues/detail?id=5685

Really looking forward to this finally dropping, it is so close, and the last thing that's preventing me dropping babel on some projects.

**Comment by xgqfrms-GitHub** [comment]
https://github.com/nodejs/node/wiki/ES6-Module-Detection-in-Node
http://stackoverflow.com/questions/37132031/nodejs-plans-to-support-import-export-es6-es2015-modules
http://stackoverflow.com/questions/31354559/using-node-js-require-vs-es6-import-export

**Comment by mrmayfield** [comment]
I've been reading up on ES Modules being supported in native node, it looks like there's two simultaneous discussions of how to implement it (ie, whether to use the .mjs file extension) and then also a consideration around a bug in V8.

Which is the true current blocker? Does anyone have an ETA on when the blocker should be smoothed out and V8 will support the ES Module syntax? I'm in the same boat as a few others here who are hoping to drop babel, thanks!

**Comment by mweels** [comment]
Why would they support it when you could use transcompilers?

**Comment by dandv** [comment]
Since 2017-Jan-10, [V8 supports modules](https://bugs.chromium.org/p/v8/issues/detail?id=1569).

**Comment by mrmayfield** [comment]
Awesome! And it looks like nightly node (and 7.4) uses v8 version: 5.4.500.46

Whereas the latest V8 version with es modules landed is around: 5.7.458

Wonder how long it will take to land in node 🤔 I don't actively develop node do any devs have a guesstimate?

**Comment by MylesBorins** [comment]
@mrmayfield it should eventually be on [this experimental branch](https://github.com/v8/node/commits/vee-eight-lkgr)

fwiw it landing in V8 will be only the first step towards proper support in node. I believe we are currently tracking V8 5.5 for inclusion in node 8... but other people will know better.

/cc @nodejs/v8

**Comment by mrmayfield** [comment]
Thanks @MylesBorins 
So there's still determinations to be made in regards to how to implement the actual feature even though it's now landed in V8? Sorry I'm a bit unfamiliar with the intricacies of how Node/V8 interact.

**Comment by targos** [comment]
@mrmayfield yes. It is happening here: https://github.com/nodejs/node-eps/pull/39

**Comment by dandv** [comment]
From James M Snell's [Update on ES6 Modules in Node.js](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c):

> Work is in progress but it is going to take some time — We’re currently looking at around a year *at least*.

**Comment by mk-pmb** [comment]
How's progress so far?

**Comment by caonUlisses** [comment]
You can use it with for `.mjs` files with the `--experimental-modules` flag, as had being pointed already, it's experimental, but it's already happening.

**Comment by cztomsik** [comment]
Currently, it's not possible to import the same file from chrome and node.js at the same time. Something should be done about this.

**Comment by devsnek** [comment]
> Currently, it's not possible to import the same file from chrome and node.js at the same time. Something should be done about this.

i'm not sure what exactly is lacking? obviously browsers won't implement node's loader algorithm or builtin modules. there is discussion around allowing node to import from urls but there's a lot of work to do behind that.

**Comment by cztomsik** [comment]
the problem is *.mjs file extension (which is not application/javascript
and so the chrome will reject it)

2018-03-14 0:42 GMT+01:00 Gus Caplan <notifications@github.com>:

**Comment by StyMaar** [comment]
`application/javascript` is a MIME type set by the web-server in the HTTP response header. 
Most http server automatically set the `application/javascript` MIME header when delivering files with a `.js` extension but you can configure your web server to do the same for `.mjs`.

**Comment by cztomsik** [comment]
there are cases when you can't

2018-03-14 12:38 GMT+01:00 StyMaar <notifications@github.com>:

**Comment by StyMaar** [comment]
What's your use-case ?

In general, if you can't configure the MIME type, and the `.mjs` extension is misbehaving on the server, then the bug is on the webserver's / hosting service side and should be filed there.

I'm still curious about your specific case though.

**Comment by devsnek** [comment]
for those of you following along at home: https://datatracker.ietf.org/submit/status/88872/

**Comment by styfle** [comment]
> Currently, it's not possible to import the same file from chrome and node.js at the same time. Something should be done about this.

@cztomsik There is something being done about it on the web side of things too.
See https://github.com/domenic/package-name-maps
