### ISSUE TITLE
Minimum requirements to use node.js on an embedded system with less RAM

### ISSUE THREAD

**Issue by EifelJoe** [nodejs/help#530]
Hi, I would like to use node.js on an embedded system server to administrate a sensor network. But I dont't know what the minimum requirements are, especially on the RAM.
Further it would be great if I could use the http module to build a web server. Apache for example cannot be used, because it's to big. My other option would be writing an own web server in C.
Unfortunately hardware is fix.

Can somebody help me giving me some numbers, please? Or is there a link to an official webpage perhaps where I can find this information (not found yet) ?

**Comment by bnoordhuis** [comment]
What specs does your target machine have?  `node -e undefined` (a one-liner that does nothing) needs about 10-20 MB.  You can probably run a simple web server in as little as 24 to 32 MB if you tweak `--max_old_space_size=...`; see `node --v8-options`.  `--optimize_for_size` might help too, although it has some known bugs.

You can strip down the memory requirements some more with a custom build.  See `./configure --help` for options you can disable, like `--without-ssl` and `--without-intl`.

**Comment by EifelJoe** [comment]
STM32F769I-DISCO.
- 128-Mbit SDRAM and 512-Mbit Quad-SPI Flash
- cortex-M7 core 

ever thank you

**Comment by bnoordhuis** [comment]
128 Mbit = 16 MB?  I don't think that's going to cut it.  As well, a Cortex-M7 probably isn't compatible.

**Comment by EifelJoe** [comment]
All right! So do you think we could use node.js without the http module? Or is it that what you mean and our hardware isn't compatible in general?

**Comment by bnoordhuis** [comment]
> our hardware isn't compatible in general?

This.  I don't think node will run on it.

**Comment by EifelJoe** [comment]
Pity! But thank you very much
