### ISSUE TITLE
OO inheritance and composition w/ modules, how to?

### ISSUE THREAD

**Issue by puppetmaster3** [nodejs/help#531]
If I have a class/module:
// a.js
class A {
  // ...
}
module.exports = A;

How do I create another module B that extends that class?

**Comment by vsemozhetbyt** [comment]
If I get it right, this way:
```js
// b.js
const A = require('./a.js');

class B extends A {}

module.exports = B;
```

**Comment by evanlucas** [comment]
@vsemozhetbyt is correct on this. We do try to keep this issue tracker for bugs in core only, so please try to ask questions like this at https://github.com/nodejs/help/issues in the future. I'm going to go ahead and close. Thanks!

**Comment by lordKnighton** [comment]
closing for now, if you still need help with this @vsemozhetbyt reopen and we will have a go again.
