### ISSUE TITLE
split the element value and add a array

### ISSUE THREAD

**Issue by MKT123** [nodejs/help#532]
Hi Team... I have a code in node js where I am looking to achieve the below result.. I did have a code in place.... can someone please take a look and let me know where am missing. line # 57 to 64 in the attached file.
[app (10).zip](https://github.com/nodejs/help/files/839266/app.10.zip)

array=["start":"07:00 pm","end":"07:45 pm",**"rule":
"MO,WE**","summary":"Gracie Jiu Jitsu"]
into 
array=[
{"start":"07:00 pm","end":"07:45 pm",**"rule":"MO,WE**","summary":"Gracie Jiu Jitsu","day":"**WE**"},
{"start":"07:00 pm","end":"07:45 pm","rule":"MO,WE","summary":"Gracie Jiu Jitsu","day":"**WE**"(instead it should be 'MO'}]

2.Also... when i run this app... I see the jsondata keep adding to the  output everytime (as duplicate output..)any idea how to avoid that? Thanks

**Comment by vsemozhetbyt** [comment]
@mahakT  I can be wrong (I am not sure I entirely understand the code), but this may be the cause:
```js
for(var j = 0; j < rulest.length; j++) {
  var day=rulest[j];
  entry.day=day; // entry is identical here, so you rewrite the same property
  jsondata.push(entry); // entry is identical here, so you push the same object by the reference
}
```
Consider this example:
```js
const obj = {};
const arr = [];

obj.prop = 1;
arr.push(obj);

obj.prop = 2;
arr.push(obj);

console.log(arr);
```
The output is:
```js
[ { prop: 2 }, { prop: 2 } ]
```
because the `obj` is pushed by reference with the same `obj.prop` rewritten.

You should at least push a copy of `entry`, something like this:
```js
jsondata.push(Object.assign({}, entry));
```
However, make sure that `Object.assign()` is what you need and that its limitations do not cause any mess with data:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

http://exploringjs.com/es6/ch_oop-besides-classes.html#Object_assign

**Comment by vsemozhetbyt** [comment]
As for `jsondata keep adding to the output everytime`, try to comment out this line:
```js
console.log("TTTTT rulest", rulest);
```

**Comment by mahakT** [comment]
Sorry... you mean to say commenting this log would help? as there is a loop inside another loo...am not sure how to achieve that.var day=rulest[j]; (logs gets the correct data for each loop (MO,WE) but when the day is added to json it adds identical data :( )

**Comment by vsemozhetbyt** [comment]
@mahakT 
By my second comment, I mean that if you replace this line:
```js
console.log("TTTTT rulest", rulest);
```
with this line:
```js
// console.log("TTTTT rulest", rulest);
```
this could partly prevent jsondata from adding to the output (your second problem).

To solve your first problem, you can try to replace this line:
```js
jsondata.push(entry);
```
with this one:
```js
jsondata.push(Object.assign({}, entry));
```

**Comment by vsemozhetbyt** [comment]
@mahakT Oh, [now I see](https://github.com/nodejs/help/issues/537) what you mean. I have misunderstood the  'jsondata keep adding to the output everytime', I thought `output` was the console output, not HTML output. Sorry for my wrong comments.
