### ISSUE TITLE
Node js read http url content

### ISSUE THREAD

**Issue by MKT123** [nodejs/help#533]
Hi...
I need to read external http url which has data (can be  of any extension xml,txt,ics). for eg: I downloaded the basic.xml to local . instead i need to read the file directly from url (https). can someone tel me how to read the content from external url?
fs.readFile('./public/basic.xml', 'utf8', function(err, data) {
		if (err) {
			console.log(err);
		} else {
console.log(data);

}

**Comment by zbjornson** [comment]
You can use `http.get`. There's a full example in the [docs](https://nodejs.org/api/http.html#http_http_get_options_callback).

The [request](https://www.npmjs.com/package/request) module wraps `http` and makes it a bit more convenient:

```js
request("your/url", function (err, response, body) {
  if (err) ...
  // do stuff with body
});
```

**Comment by hengsoheak** [comment]
> You can use `http.get`. There's a full example in the [docs](https://nodejs.org/api/http.html#http_http_get_options_callback).
> 
> The [request](https://www.npmjs.com/package/request) module wraps `http` and makes it a bit more convenient:
> 
> ```js
> request("your/url", function (err, response, body) {
>   if (err) ...
>   // do stuff with body
> });
> ```

@zbjornson  Does it support with csv? I want to react all content from remote url with file type csv
