### ISSUE TITLE
--debug-brk is very, very slow

### ISSUE THREAD

**Issue by maenthoven** [nodejs/help#534]
* **Node.js Version**: 6.10.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Runtime

I'm using node v6.10.0 and trying to figure out why my --debug-brk is so incredibly slow. Without this flag (with just --inspect or --debug), it's almost instantaneous, though the debugger still takes forever to attach (average 84 seconds after 5 trials).

Any ideas on how to start debugging this issue?

**Comment by bnoordhuis** [comment]
You will have to be more specific.  How and with what debugger are you seeing this?  Does it happen with a one-liner 'hello world' script or only with a full-fledged application?

**Comment by maenthoven** [comment]
This only happens on my application. Hello World is fine.

**Comment by bnoordhuis** [comment]
Right, that makes it more complicated.  What debugger are you trying to attach?  If it isn't the built-in one, you should probably report it to that project, maybe they can help.

**Comment by maenthoven** [comment]
It's the built-in​ one.

**Comment by bnoordhuis** [comment]
If it's the old debugger, it might be https://github.com/nodejs/node/issues/2875 (don't be fooled by the title, it's a red herring.)

If you are using the inspector, try putting a test case together and open an issue.  If that isn't an option, you probably have to resort to building from source and doing printf-style debugging.

**Comment by maenthoven** [comment]
That's not it. I used webstorm to log out what was going on and found that it was just taking forever to read all my modules? Perhaps that's what's going on?

Is there a way to speed this up? It's taking 34 seconds just to load all the require statements.

Running an es6 project
Skip to content
This repository
Search
Pull requests
Issues
Gist
 @maenthoven
 Sign out
 Watch 59
  Star 141
 Fork 41 nodejs/help
 Code  Issues 100  Pull requests 1  Projects 0  Wiki  Pulse  Graphs
Edit New issue
--debug-brk is very, very slow #534
 Open	maenthoven opened this issue 14 hours ago · 5 comments
Assignees

No one assigned
Labels

None yet
Projects

None yet
Milestone

No milestone
Notifications

  Unsubscribe
You’re receiving notifications because you authored the thread.
2 participants

@maenthoven @bnoordhuis
@maenthoven
   
maenthoven commented 14 hours ago
Node.js Version: 6.10.0
OS: Windows 10
Scope (install, code, runtime, meta, other?): Runtime
I'm using node v6.10.0 and trying to figure out why my --debug-brk is so incredibly slow. Without this flag (with just --inspect or --debug), it's almost instantaneous, though the debugger still takes forever to attach (average 84 seconds after 5 trials).

Any ideas on how to start debugging this issue?
 @bnoordhuis
 Member
bnoordhuis commented 11 hours ago
You will have to be more specific. How and with what debugger are you seeing this? Does it happen with a one-liner 'hello world' script or only with a full-fledged application?
@maenthoven
     
 maenthoven commented 8 hours ago
This only happens on my application. Hello World is fine.
…
 @bnoordhuis
 Member
bnoordhuis commented 8 hours ago
Right, that makes it more complicated. What debugger are you trying to attach? If it isn't the built-in one, you should probably report it to that project, maybe they can help.
@maenthoven
     
 maenthoven commented 8 hours ago
It's the built-in​ one.
…
 @bnoordhuis
 Member
bnoordhuis commented 8 hours ago
If it's the old debugger, it might be nodejs/node#2875 (don't be fooled by the title, it's a red herring.)

If you are using the inspector, try putting a test case together and open an issue. If that isn't an option, you probably have to resort to building from source and doing printf-style debugging.
@maenthoven
  
            
 
Write  Preview

That's not it. I used webstorm to log out what was going on and found that it was just taking forever to read all my modules? Perhaps that's what's going on?

Is there a way to speed this up? It's taking 34 seconds just to load all the require statements.

Running an es6 project

Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.
 Styling with Markdown is supported
Comment Close and comment
Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Terms Privacy Security Status Help

**Comment by Fishrock123** [comment]
My guess would be that running code in debug mode is just slower.

**Comment by maenthoven** [comment]
That doesn't make sense though. When I revert to node 4.x, it goes instantly.

**Comment by Fishrock123** [comment]
hmm, interesting. @nodejs/v8-inspector maybe?

**Comment by bnoordhuis** [comment]
Something doesn't add up.  There is no inspector in v4.x.

**Comment by maenthoven** [comment]
I'm just using what WebStorm uses for debug :-\ I'm not the most technical
person, so sorry if I'm not presenting correctly.

Node v.4.4.7 loads instantly on the debug there.

**Comment by bnoordhuis** [comment]
If you are using WebStorm, you should contact that project.  We can't help you with that.

**Comment by maenthoven** [comment]
It happens without Webstorm on v5+ though. Just using the command prompt, it's still taking 40+ seconds with --debug-brk

**Comment by bnoordhuis** [comment]
Right, then https://github.com/nodejs/help/issues/534#issuecomment-286400978 are your options.
