### ISSUE TITLE
node --inspect not working 

### ISSUE THREAD

**Issue by navinSing** [nodejs/help#538]
* **Node.js Version**:
v7.7.2
* **OS**:
Linux mh 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 10:21:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Using 

docker service create --name aserv  -p 9229:9229 -p 4848:4849 -p 18081:8080 node:7.7.2-alpine node  --inspect=127.0.0.1:4849  /src/start.js

// tried all combinations 
--inspect
--inspect=127.0.0.1:9229 
--inspect=127.0.0.1:4848 
--inspect=127.0.0.1:4849 

Chrome version : 55.0
// added the following in chrome
chrome://inspect/#devices

Target discovery settings (Remote Target)
192.168.1.100:9229
192.168.1.100:4848
192.168.1.100:4849
localhost:9229
localhost:4848

And Didn't worked. 

What is the best way to do this. 

1. If we are using docker swarm the remote IP may not be available
2. how does port tunneling work here
3. and new url hash like 
chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=**10.255.0.11**:9229/**c90e8346-11d6-47cf-aca4-d2360769bdd7** 

Both IP : 10.255.0.11
and hash : c90e8346-11d6-47cf-aca4-d2360769bdd7
are changing.. which means that i have to check the application logs to get this :S weird.  
Can't the hash be sent as a parameter to command line .. or some other way to avoid this hash

Earlier with --debug it was not.
how do i debug a service in a swarm

**Comment by navinSing** [comment]
fixed , my bad

**Comment by waqas64** [comment]
can you please share the fix.

**Comment by joshgav** [comment]
you need to use `--inspect=0.0.0.0:9229` because Docker doesn't route 127.0.0.1 through. Note [this (comment)](https://github.com/nodejs/node/pull/11755#issuecomment-289837657) though, since 7.7.4 there's a bug that makes this not work. Suggestions there would be welcome!
