### ISSUE TITLE
Trying to Link node using brew.

### ISSUE THREAD

**Issue by shaman-tech** [nodejs/help#541]
* **Node.js Version**:  7.7.3
* **OS**: macOS Sierra vrs. 10.12.3
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

I was trying to upgrade node and nvm, I followed some instructions which led to me uninstalling node and attempting to reinstall.
when I run 'brew install node' it returns a warning node 7.7.3 is already installed, it is just not linked.
I tried 'brew link node' it returns:
Error: Could not symlink lib/dtrace/node.d
/usr/local/lib/dtrace is not writable.

Any suggestions for me so I can get node and nvm up and running again?

**Comment by lordKnighton** [comment]
type `which node && which npm` & show me the output

**Comment by shaman-tech** [comment]
Output: 
/usr/local/bin/node
/usr/local/bin/npm

**Comment by lordKnighton** [comment]
Perfect, you've got node! 😃

**Comment by lordKnighton** [comment]
type `node -v && npm -v`

**Comment by shaman-tech** [comment]
Output: 
v7.7.3
4.1.2

Thanks so much for your response. I actually resolved it a while back. I think I deleted it and re-installed it directly from the website and it worked then. Using brew was still giving me an issue.

I have another issue if you could help me with that. when I use npm install in my project folder where grunt is stored locally. I try to use grunt. But I get a grunt command not found response. Gruntfile.js is there and my grunt-cli is installed globally, but still I get the issue.

Any suggestions?

**Comment by lordKnighton** [comment]
don't judge me, but i don't have much experience with grunt. But lucky for you Im proficient in google-Fu: so here are a few links that got you covered:

https://teamtreehouse.com/community/any-grunt-command-that-i-input-into-the-terminal-results-in-bash-gruntinit-command-not-found

if this page don't help then i don't know what will 😃  : http://stackoverflow.com/questions/16868924/grunt-command-not-found-when-running-from-terminal

Im gonna close this for now, but if neither one of those help much, then hit me up & we will take it from there. Best of luck. 👍

**Comment by shaman-tech** [comment]
thanks! :)
