### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SigurdSk** [nodejs/help#542]
* **Node.js newest**:
* **OS windows 10**:
* **Scope json script**:
* **Module (and version) (if relevant)**:

Hi. I have seen a .json script that you run with node or node package manager wich will install through code with dependencies that automatically using this script with npm installs newest versions of famous libraries like angular and jquery right in tge working directory. Could you provide me with a such script?

-->sigurd ikt spesialisten

**Comment by vdeturckheim** [comment]
JSON is a data format, this means you can't execute a json file.

**Comment by SigurdSk** [comment]
Maybe with bower?

Sendt fra min Huawei-mobiltelefon

-------- Original Message --------
Subject: Re: [nodejs/help] Help (#542)
From: Vladimir de Turckheim
To: nodejs/help
CC: Sigurd ,Author


JSON is a data format, this means you can't execute a json file.

**Comment by lordKnighton** [comment]
Maybe your looking for:  `npm init -y` 
> that will do the `npm init` & skip though the default packages

or you could be looking for, where you had already described the packs you wanted
in your package.json file then save it, then go to the term & type `npm i`
that will install all the packs you specified in your package.json file.

if not that then im not to sure what your looking for. Tell me more though.

**Comment by SigurdSk** [comment]
Exactly what i was looking for. I had dependencies in a json file i found just needed to rename it to package.json and then it worked!😁

30. mar. 2017 21:58 skrev "kelvin knighton" <notifications@github.com<mailto:notifications@github.com>>:

Maybe your looking for: npm init -y

that will do the npm init & skip though the default packages

or you could be looking for, where you had already described the packs you wanted
in your package.json file then save it, then go to the term & type npm i
that will install all the packs you specified in your package.json file.

if not that then im not to sure what your looking for. Tell me more though.

**Comment by lordKnighton** [comment]
glad to be of service @SigurdSk Happy coding 👍
