### ISSUE TITLE
socket.write callback delay called when using uv_async_send from another thread

### ISSUE THREAD

**Issue by linfang010** [nodejs/help#545]
* **Node.js Version**:  node-v6.9.5-x86
* **OS**: win7 64-bit
* **Module (and version) (if relevant)**:  socket.io@1.7.3

hello,
  I'm writing a nodejs middleware that use socket.io to interact with html5 clients through websocket and  C++ addon to interact with server side(another thread). In C++ thread, when received server side messages, i use **uv_async_send** to excecute the Persistent<Function> call back that early passed into c++ addon in nodejs main thread. The call back is socket.io emit function that send server message to clients. 
  Cilents  can receive message successfully. But the problem is when middleware received several messages at short period and emit them to client(i know **uv_async_send** will be combined by nodejs so i use a queue to emit them all in async callback). The client sometimes don't receive messages in time(**Ex**. middleware emit 5 messages, client may receive 4 messages immediately, but the fifth message wiil be delayed like 10-20s).
  So i looked into **socket.io** and **engine.io**, from the debug message i believe the delay is due to the callback that passed into **net.socket.write()** did not be called immediately when the data is written out but delayed for a long time. This only happend when socket.io emit function being called from c++ thread by **uv_async_send**. When i directly emit several messages in nodejs main thread, there is no delay. 
  I'm new to nodejs and have no idea what's going on. Anyone have some hints? 

**some code in C++ addon:**
```c++
std::queue<MessageString> Msg_Q;
uv_async_t async;
Persistent<Function> global_cb;

// register socket.io emit() from js
void RunCallback(const FunctionCallbackInfo<Value>& args) {
  Isolate* isolate = args.GetIsolate();

  uv_async_init(uv_default_loop(), &async, asyncmsg);

  global_cb.Reset(isolate, args[0].As<Function>());
}

// async callback
void asyncmsg(uv_async_t* handle) {

	WaitForSingleObject(global_mutex, INFINITE);
	Isolate* isolate = v8::Isolate::GetCurrent();
	HandleScope scope(isolate);

	while (!Msg_Q.empty())
	{
		MessageString ms = Msg_Q.front();

		const unsigned argc = 3;
		Local<Value> argv[argc] = { v8::String::NewFromUtf8(isolate, ms.socketid.c_str()),
									v8::String::NewFromUtf8(isolate, ms.typestring.c_str()),
									v8::String::NewFromUtf8(isolate, ms.jsonstring.c_str()) };
		// execute the socket.io emit()
		Local<Function>::New(isolate, global_cb)
			->Call(isolate->GetCurrentContext()->Global(), argc, argv);

		Msg_Q.pop();
	}
	ReleaseMutex(global_mutex);
}

// some callback in another thread
bool MessageHandler::onLoginOK(const void* data, uint32_t size) 
{ 
   ''' some code to process the data '''

   Msg_Q.push(ms);
   uv_async_send(&async);
   return true;
}
```

**Comment by addaleax** [comment]
How do you call the callback from the uv_async handler? Do you use `->Call` or node’s/nan’s `MakeCallback()`?

It might also be helpful to see a bit of code for answering this…

**Comment by linfang010** [comment]
I add some code, sorry about the format.

**Comment by bnoordhuis** [comment]
Seeing how in your example, you acquire `global_mutex` on entry in `asyncmsg` and don't release it again until exit, I'm going to guess that your critical sections are overly broad.  What does the producer look like?

Your consumer could (and arguably should) look like this:
```c++
for (;;) {
  WaitForSingleObject(global_mutex, INFINITE);
  if (Msg_Q.empty()) {
      ReleaseMutex(global_mutex);
      break;
  }
  MessageString ms = Msg_Q.front();
  Msg_Q.pop();
  ReleaseMutex(global_mutex);
  // Now call into JS land.
  // ...
}

**Comment by linfang010** [comment]
@bnoordhuis your code did make more sense. But the delay is still there. `global_mutex` is to synchronize between main thread and c++ thread for some global varialbles like `Msg_Q`, and there is no blocking work in that thread, the thread is a message loop that get nework messages(received in another thread) from a queue and excecute the relative callback like onLoginOK above .
I'm pretty sure the delay is due to the callback that socket.io(engine.io) passed into `net.Socket.write()` delayed being called. when i change the way it sends data in engine,.io(socket.js flush()), make the callback trivial, there is no delay.

**Comment by linfang010** [comment]
I removed the thread and mutex thing. when client sends a request to nodejs, i just emit some arbitary messages back in C++ addon. The delay only happend when i use `uv_async_send` to call the js callback. when i directly call the js callback, there is no delay.
did i use `uv_async_send` in a wrong way? @addaleax @bnoordhuis

**Comment by addaleax** [comment]
Try to replace `->Call` with `node::MakeCallback`, that might help. (`MakeCallback` makes sure that `process.nextTick()` callbacks are run, and I think that might be the problem here…)

**Comment by linfang010** [comment]
I use `node::MakeCallback` and the delay disappears, thanks for your help. Then i see this [https://github.com/nodejs/nan/issues/284](url), it says MakeCallback is dangerous. So should i be care of something else, or just replace `->Call` with `node::MakeCallback` . @addaleax

**Comment by addaleax** [comment]
I think it’s fine to use `MakeCallback`, I don’t think any of the problems there apply anymore

**Comment by linfang010** [comment]
@addaleax  ok, thanks a lot.

**Comment by addaleax** [comment]
I’m assuming this can be closed as answered now, but feel free to re-open if I’m wrong :)
