### ISSUE TITLE
Cross-platform run of an arbitrary script

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#548]
Is there a simple canonical way to run an arbitrary script with Node.js on different platforms? Something like CI, but just for one file.

Say, I want to know if [this benchmark](https://github.com/nodejs/node/issues/11972) is broken just for my OS and environment or it is broken in general. Can I do this?

**Comment by bnoordhuis** [comment]
https://ci.nodejs.org/job/node-stress-single-test/ ?

**Comment by gibfahn** [comment]
We should probably document this in the [COLLABORATOR_GUIDE.md](https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md).

**Comment by vsemozhetbyt** [comment]
@bnoordhuis @gibfahn Maybe I am doing something wrong, I've made 2 attempt, both have failed without needed output.

I was using `../benchmark/net/tcp-raw-pipe` path for the `RUN_TESTS` field and `1` for the `RUN_TIMES` field. Is it right?

For the first run, I've used already selected `RUN_LABEL`, for the second one I,ve selected something else.

https://ci.nodejs.org/job/node-stress-single-test/1137/

https://ci.nodejs.org/job/node-stress-single-test/1138/

**Comment by gibfahn** [comment]
@vsemozhetbyt oh right, that won't work for benchmarks. the `node-stress-single-test` job runs `tools/test.py` with the arguments you give it, as I understand it the benchmarks are run with `node benchmark/run.js`.

I guess the answer would be to add a new job to run benchmarks (assuming they don't take too long).

cc/ @nodejs/benchmarking @nodejs/build @mscdex as to whether this is a good idea.

**Comment by mscdex** [comment]
I believe there was some discussion some time ago by the benchmarking group about setting up dedicated hardware for running benchmarks and I was thinking it was about node's benchmarks and not the acme air benchmarks.

**Comment by vsemozhetbyt** [comment]
@gibfahn I am trying to do this [hard way](https://github.com/nodejs/node/pull/12030) :)

**Comment by gibfahn** [comment]
According to the [benchmarking WG README](https://github.com/nodejs/benchmarking/blob/master/benchmarks/README.md), there is currently [one dedicated benchmarking machine](https://ci.nodejs.org/computer/iojs-softlayer-benchmark/), which is used to generate the number for https://benchmarking.nodejs.org/.

However, this doesn't really help with the cross-platform testing @vsemozhetbyt is talking about. 

If it's just a single (short) script, and it can run from the tarballs on nodejs.org, then it should be pretty straighforward to set up a job that runs the script with a tarball from nodejs.org.

**Comment by mscdex** [comment]
@gibfahn Right, the keyword there is *currently*. I do not know what the status is for acquiring hardware for running node benchmarks or even if that is something the benchmarking group is looking into anymore.

Depending on the scope of this request, I think using the pre-compiled tarballs will only provide so much benefit, since I think in most cases we will want to be benchmarking changes made in a PR, which would require compilation.

**Comment by mscdex** [comment]
Additionally, I would think we would want actual dedicated hardware when it comes to running benchmarks, to avoid any interference/noise created by other processes running at the same and such.

**Comment by gibfahn** [comment]
I'd be interested to know how much variability Jenkins adds, given that the [current benchmarking jobs](https://github.com/nodejs/benchmarking/blob/master/benchmarks/README.md#capturing-benchmark-results) are run through [ci.nodejs.org](https://ci.nodejs.org/view/Node.js%20benchmark/).

@mscdex I think both are probably useful, you need to build from source to test a PR, but you often want to test an existing build, that's certainly the case with the `node-test-commit` jobs, CitGM, and the other `nodejs/` CI jobs.

Presumably if we were to have a complete suite of benchmarking machines that would double our hardware usage, I'm not sure whether that would be feasible.
