### ISSUE TITLE
Linux rhel 6.0 "install" robustness

### ISSUE THREAD

**Issue by nomad789** [nodejs/help#55]
When you download 64-bit Linux Binaries (.tar.gz), there are no .rpm packages.  I saw the curl/yum series of instructions, however we do not have a Red Hat subscription, so were hoping to use yum to install, but not possible w/out n .rpm package.

Did notice that expanding the packages, all components seem to be there. After setting PATH to the installed directories, I tried an npm install of an application and it worked fine.

-Is this "expand-and-set-PATH" installation valid - or is this a problem waiting to happen?  
We installed v4.2.3 on RHEL 6. 
-Any caveats?

Thanks and regards

**Comment by bnoordhuis** [comment]
> -Is this "expand-and-set-PATH" installation valid

Is it, that's (one of) the intended ways of installing it.

> We installed v4.2.3 on RHEL 6. -Any caveats?

`npm install` of native add-ons may be an issue due to the old compiler in the base install.  Node.js itself should work fine though, RHEL 6 is explicitly supported.

**Comment by nomad789** [comment]
Thank you bnoordhuis. 
Regarding the second item, did have some issues with an application requiring GLIBC 2.14 libraries

Error: /lib64/libc.so.6: version `GLIBC_2.14' not found ... Error(native) - but working through with application team on that issue.  We have: rpm -qa on glib:
glibc-2.12-1.7.el6.x86_64    - thanks again.

**Comment by bnoordhuis** [comment]
No problem.  I'll close out the issue.
