### ISSUE TITLE
Node js in HANA

### ISSUE THREAD

**Issue by MKT123** [nodejs/help#552]
Hi... Can someone guide me how to deploy and execute the node js code in SAP Hana cloud?

I did tried to explore and get some details...but stuck with SAP WEBIDE...not sure how to proceed from there...

any experts guidance please? Thanks.

**Comment by lordKnighton** [comment]
disclamer: I haven't even messed with SAP Hana cloud, no knowledge what so ever:

However I do know some ( google-Fu ) 

Have you read this post:  https://blogs.sap.com/2016/09/05/hcp-cloud-foundry-playing-around-with-node-mongodb-and-ui5/

this looks like the closet to what your asking. I've search, but could do more if need be.
So let me know what you think of it, helpful or nah?

**Comment by MKT123** [comment]
Thanks a lot for your time and helping to get the details...Appreciated !!

yes it does helps and its has related info... however i did see the issue with initial setup as per attached. I think its issue with service 
![sap_hcp](https://cloud.githubusercontent.com/assets/25396361/24591682/51226344-17d5-11e7-885a-fa8529ab57c6.png)

**Comment by lordKnighton** [comment]
@MKT123 you still having this issue?

**Comment by theakathir** [comment]
@lordKnighton  :  we are good, the issue was in service by itself.. which is fixed now.. Thanks!

**Comment by MKT123** [comment]
@lordKnighton  The issue has been resolved as it was occuring in service by itself...we are good now...and we can close the item Thanks again....
