### ISSUE TITLE
npm not installed along with nodejs

### ISSUE THREAD

**Issue by gagan0723** [nodejs/help#554]
Version: v4.2.6 of node -v
Platform: Linux 4.8.0-36-generic #36~16.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux.

Following the guidelines as per https://nodejs.org/en/download/package-manager/, installed nodejs versin-7.x on my machine several times.

But every time npm does not get installed. When typing in 'npm -v' it says, the program 'npm' is currently not installed. You can install it by typing: 'sudo apt install npm'.

What's even strange is, the system displays(node -v) that the installed nodejs version is v4.2.6.

**Comment by lordKnighton** [comment]
have you seen this post: older versions could be throwing it off. 
http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/

**Comment by shellberg** [comment]
The details documented at https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions include : 
"A Node.js package is also available in the official repo for Debian Sid (unstable), Jessie (testing) and Wheezy (wheezy-backports) as "nodejs". **It only installs a nodejs binary**."
You might want to check the repositories that are configured that apt-get consults and see if this last statement applied.

**Comment by gagan0723** [comment]
I've uninstalled both node and nodejs as per http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/ and again installed nodejs as per 
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions.

Here's the log:

userName@userName:~$ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libuv1
The following NEW packages will be installed:
  libuv1 nodejs
0 upgraded, 2 newly installed, 0 to remove and 12 not upgraded.
Need to get 0 B/3 218 kB of archives.
After this operation, 13,4 MB of additional disk space will be used.
Selecting previously unselected package libuv1:amd64.
(Reading database ... 246235 files and directories currently installed.)
Preparing to unpack .../libuv1_1.8.0-1_amd64.deb ...
Unpacking libuv1:amd64 (1.8.0-1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_4.2.6~dfsg-1ubuntu4.1_amd64.deb ...
Unpacking nodejs (4.2.6~dfsg-1ubuntu4.1) ...
Processing triggers for libc-bin (2.23-0ubuntu7) ...
Processing triggers for doc-base (0.10.7) ...
Processing 1 added doc-base file...
Processing triggers for man-db (2.7.5-1) ...
Setting up libuv1:amd64 (1.8.0-1) ...
Setting up nodejs (4.2.6~dfsg-1ubuntu4.1) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Processing triggers for libc-bin (2.23-0ubuntu7) ...

After installing this is what the terminal shows:
userName@userName:~$ which nodejs
/usr/bin/nodejs
userName@userName:~$ nodejs -v
v4.2.6
userName@userName:~$ npm -v
The program 'npm' is currently not installed. You can install it by typing:
sudo apt install npm

I'm sure that, curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -,  installs version 7.x, but it always shows v4.2.6

**Comment by gagan0723** [comment]
Sorry about the way the comment looks, I'm bad at markdown.

**Comment by vsemozhetbyt** [comment]
@gagan0723 You just need to escape `~`:

\\\~$

Or put three ticks before and after output:

\`\`\`
\~$...
\`\`\`

**Comment by lordKnighton** [comment]
have you tried, just typing in `sudo apt install npm` 

![screen shot 2017-03-29 at 9 26 36 am](https://cloud.githubusercontent.com/assets/1773260/24465466/f145a9b6-1461-11e7-8054-4b18dc7c4081.png)

**Comment by reallyroy** [comment]
I'm seeing the same issue on my Ubuntu VM. Running the instructions at https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions results in nodejs v4.2.6 getting installed without npm.

**Comment by johnson1979** [comment]
Try to update the nodejs version! It helped me!

**Comment by JeanCarlosChavarriaHughes** [comment]
After a hard time, I got npm installed with Carbon version. 
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -

The current version 10x did not work.
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -

I made sure to purge the nodejs-legacy package from my debian 9 strech 32 bit machine.

**Comment by yogi129** [comment]
> After a hard time, I got npm installed with Carbon version.
> curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
> 
> The current version 10x did not work.
> curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
> 
> I made sure to purge the nodejs-legacy package from my debian 9 strech 32 bit machine.

Worked for me! Thanks.

**Comment by TechiePriyaRanjan** [comment]
this is still not working 
```
techiepriyaranjan@techieace:~$ node -v
v8.10.0
techiepriyaranjan@techieace:~$ npm -v

Command 'npm' not found, but can be installed with:

sudo apt install npm
```
What to do? :disappointed:

**Comment by TechiePriyaRanjan** [comment]
> this is still not working
> 
> ```
> techiepriyaranjan@techieace:~$ node -v
> v8.10.0
> techiepriyaranjan@techieace:~$ npm -v
> 
> Command 'npm' not found, but can be installed with:
> 
> sudo apt install npm
> ```
> 
> What to do? disappointed

Even I runned this command `sudo apt install npm` nothing is working :cry:

**Comment by amedranogil** [comment]
I found a possible source for the problem: debian is giving more priority to the oficial debian package.
```
#apt-cache policy nodejs
nodejs:
  installed: 4.8.2~dfsg-1
  candidate:  4.8.2~dfsg-1
  table of versions:
     8.12.0-1nodesource1 500
        500 https://deb.nodesource.com/node_8.x stretch/main i386 Packages
 *** 4.8.2~dfsg-1 900
        900 http://deb.debian.org/debian stretch/main i386 Packages
        100 /var/lib/dpkg/status
```
version 4.8.2 has more priority than version 8.12.0. 
To solve this I added this file /etc/apt/preferences.d/nodejs
```
Package: nodejs
Pin: origin deb.nodesource.com
Pin-Priority: 1001
```
this forces apt to consider packages from the deb.nodesource.com origines as higher priority than the Debian origin packages. 
So it should select it as candidate after `apt update` and `apt upgrade`

**Comment by ClaudiaKlees** [comment]
amedranogil,
Your solution worked! Problem solved on my end, in case the OP hasn't seen this.

**Comment by sujananth** [comment]
These steps helped me to get npm version getting listed, I hope this will help someone,

`https://stackoverflow.com/a/36856279/4146319`

**Comment by jpink** [comment]
I have Debian Stretch on 32-bit (i386) PC.
- Official Debian nodejs package is version 4.8.2 and it works via `nodejs` or `js` commands, but not by `node` or `npm` command -> "bash: node: command not found."
- NodeSource 8.x or 6.x versions doesn't work. After install `node` or `npm` command says "Illegal instruction"

I also need NPM. How to install it on 32-bit Linux system?

**Comment by kazz54** [comment]
The following worked for me
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
and then 
apt install npm

**Comment by nirajdevpandey** [comment]
none of the above mentioned solutions worked for me. Any leads guys??

**Comment by CrownlessX** [comment]
@nirajdevpandey try to remove nodejs, remove old npm(if it is), 
apt --autoremove
apt update
apt install nodejs

I got conflicts of manual installed npm and which comes with nodejs.

**Comment by kazz54** [comment]
Hi,

I wounder if this has been resolved or not ?? what Os are you using to
install node??
try to take a look at this link of how to properly install node
https://cloudtails.blogspot.com/2019/05/how-to-install-latest-nodejs-npm-yarn.html
if you still can't get it to work let me know. I'll be more than happy to
assist you farther

Best Regards,

Jona.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MinerChAI** [comment]
```
root@ivan-Latitude-E6430:/home/ivan# apt install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by MinerChAI** [comment]
Oh I fixed it

**Comment by johndpope** [comment]
https://askubuntu.com/questions/1088662/npm-depends-node-gyp-0-10-9-but-it-is-not-going-to-be-installed
sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
sudo apt-get install npm

**Comment by itamarlev** [comment]
I had the same issue and changing the preferences.d didn't work.
the problem is that using "remove" doesn't remove the configuration files and any plugins and settings.
simply use the purge option to completely remove the current nodejs installation.

`sudo apt-get purge nodejs
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
`
works like a charm..

**Comment by fontenele** [comment]
Download the file https://deb.nodesource.com/setup_12.x
Edit the line 196 that says

`DISTRO=$(lsb_release)`

to 

`DISTRO=disco`

Set disco or other dist.

**Comment by mybatchcjc** [comment]
salkjdlj

**Comment by prahladyeri** [comment]
> After a hard time, I got npm installed with Carbon version.
> curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
> 
> The current version 10x did not work.
> curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
> 
> I made sure to purge the nodejs-legacy package from my debian 9 strech 32 bit machine.

Carbon (8.x) is the only version that works on 32 bit Linux machines! The rest silently fallback to the official repository's version, so we never know about why it failed. Instead, the script should prompt the user about not supporting the later versions on legacy systems and they should install the 8.x instead.

**Comment by suestring7** [comment]
If you installed nodejs package from the official website. The npm part is under folder node-YOURVERSION/deps/npm, so go to that folder and run `configure` then `make` to install it and look for the error message during the installation.

**Comment by baraa-jabeer** [comment]
write npm -v in the cmd

**Comment by YSternlicht** [comment]
In case this helps anyone, this was my solution.
I was using WSL 2 and on windows I had npm installed as well.
Check in /usr/bin and see if there is npm in there.
Note, when you type "type npm" it redirects you to the windows partition. Yet "type node" does not.
In order to fix this and not add windows path to wsl, add the following to /etc/wsl.config (or create it if its not there) with sudo.

[interop]
appendWindowsPath=false

Then, close the terminal and restart and see if npm now works.

**Comment by EdisonArango** [comment]
In case somebody comes in here and has the same issue in a Dockerfile while using a Debian slim docker image, just install curl before running `curl -fsSL https://deb.nodesource.com/setup_x.x | bash -`:
```
apt-get install curl
```
