### ISSUE TITLE
Require hooks - load patches before user code

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#556]
I am on Node.js v7 but this applies to all Node versions >= 4.0.0.

I have a library, and am looking to monkey patch a couple of things. 

In this case, to avoid any bugs, it would be fairly imperative to load the patches before any user code.

My question is - is there a way to use some sort of require hook in a local NPM project?

If the user issues:

`cd some-project && node foo.js`

is there a way to somehow hook in some code there? I think you can do it manually with

`cd some-project && node --require X foo.js`

as in https://nodejs.org/api/cli.html#cli_r_require_module

but is there a way to preload 'X' another way? Looking for something tricky/sneaky :)

thanks!

**Comment by sam-github** [comment]
soon https://github.com/nodejs/node/pull/12028 should help

**Comment by ORESoftware** [comment]
thanks @sam-github I caught a whiff of that recently, but I couldn't remember where I had seen it
