### ISSUE TITLE
Check to determine if global.Promise is native promise

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#557]
On Node.js versions 4.0.0 <--> latest

Is there a way to check to determine if `global.Promise` is the native promise implementation? As opposed to Bluebird promises, etc?

**Comment by addaleax** [comment]
The “official” way would be `value instanceof Promise`, the “correct” way that works across VM contexts would be `process.binding('util').isPromise(value)` (see https://github.com/nodejs/node-eps/pull/44 for a proposal turning the latter into a public Node API).

**Comment by ORESoftware** [comment]
hmmm
sorry, I should been more detailed

```
global.Promise  = require('bluebird')
value instanceof Promise // will pass, but not indicate we are using native promises
```

but the second methodology should work I think, right?

**Comment by addaleax** [comment]
Ah, right, should have read that you were asking for checking `global.Promise`, not *a* promise.

Yes, the second way should work.

**Comment by ORESoftware** [comment]
just checking

process.binding('util') is the same as require('util') or no?

**Comment by addaleax** [comment]
> process.binding('util') is the same as require('util') or no?

No, `process.binding()` gives you direct access to Node’s internal C++ APIs. It’s not part of our public API, so don’t rely on it being there forever. (Sorry – I fear that’s the best answer we have right now. If you want something more reliable, maybe engage in https://github.com/nodejs/node-eps/pull/44 …)

**Comment by ORESoftware** [comment]
sure will do thanks!
