### ISSUE TITLE
Extraction on Windows 7

### ISSUE THREAD

**Issue by chayankhoidream** [nodejs/help#558]
node-v6.10.1-win-x64.zip
node-v6.10.1-win-x86.zip

When extracting either of these 2 files I get a Windows 7 Error, 'Path too long'

I'm not sure how this can be published and work, since the limitations of Windows and it's file name issues are well known. And although I hold Microsoft fully responsible for their problem; I also know that others and I are going to have problems with this when leveraging Window RG. (Really Good ;)

Errors include:
"The filename or extension is too long"
"The file path is too long"

Supposedly, Microsoft released a hotfix but unsurprisingly it doesn't work (KB2891362)
The best advice people MS Techs give, believe it or not is to try to extract files into the root of C:\

Any other suggestions or mods that can be made?

**Comment by chayankhoidream** [comment]
Moving it to c:\njs\ worked. Not very enthusiastic about that though since I have to configure shares for this folder with other VM's. (Couldnt put in my VM Shares) Someone, please call a whaaambulance.

**Comment by gibfahn** [comment]
What path were you trying to use before? Windows can't handle more than 255 chars (if I recall correctly), and given the depth of some of npm's `node_module/` dependencies, I'm not sure how much path length you can have.

One trick that might help (maybe not for unzipping though IDK) is to run `subst Z: C:\path\to\dir` in CMD, and then run the commands from within `Z:`.

cc/ @nodejs/platform-windows

**Comment by seishun** [comment]
Extracting on Windows 10 by drag-and-dropping the node-v6.10.1-win-x86 folder from the zip file to `C:\Users\Nikolai` works just fine for me. Which path are you extracting to, and how?

**Comment by seishun** [comment]
The longest path in the zip is the following:

```
node-v6.10.1-win-x86\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan\package.json
```

It's 213 chars, which is 42 chars away from the limit. Why isn't it flattened though?

**Comment by gibfahn** [comment]
>Why isn't it flattened though?

Presumably something else depends on another version of each of those modules.

**Comment by WatsonWood** [comment]
I got issues as well before about path too long errors and it was a bit tricky to fix. I tried Long Path Tool and it fixed the error.

**Comment by russellblog** [comment]
If you are unable to deleting / renaming / copying the files due to their long path issue so i suggest to try "Long Path Tool" software.

**Comment by refack** [comment]
@chayankhoidream Apparently if you use [7zip](http://www.7-zip.org/) it works (since 7Zip uses the NTFS API and not WIN32 API)

Another alternative to follow up on @gibfahn's suggestion http://stackoverflow.com/a/25089206/27955
1. create a short path (less than 40 chars, like `c:\lpn_fix`) directory to keep short links to long paths
2. mklink /J `c:\lpn_fix\node` `c:\some\crazy\long\and\very\descriptive\path\that\makes\you\happy\node`
3. [optional] add `c:\lpn_fix\node` to your path instead of the long path

**Comment by refack** [comment]
The canonical bug for this is npm/npm#3697
I'm closing this, as there isn't much more we can do 🤷

**Comment by Naim28** [comment]
I would like to suggest you, try **LongPathTool** program to resolve this issue.
This tool is very helpful to resolve the issue.
