### ISSUE TITLE
SharePoint Online REST Endpoint doesn't work with mock-http-server

### ISSUE THREAD

**Issue by mrooths** [nodejs/help#559]
* **Node.js Version**: 6.9.5
* **OS**: MacOS Sierra
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: "mock-http-server": "^0.1.0",

I'm currently trying to build an app that interfaces with SharePoint online. The API endpoint I need to hit uses a single quote in the URL. I've tried double quotes and the behavior is the same. The HTTP request module I'm using is https://request.js.org/. When trying to post to the mocked endpoint, it doesn't decode the single or double quotes correctly. When the GUID used for list lookup doesn't have single quotes the endpoint is found. 

Code not working:

```js
var SM = require("mock-http-server");
import * as request from 'request';
import * as mocha from 'mocha';
import * as chai from 'chai';
import app from '../src/App';


const expect = chai.expect;
describe('Artemis mock server tests', () => {
    const host = "localhost";
    var resource = "/sites/dev/_api/web/lists('30a0d753-88a1-442b-a3b3-20d030db1494')/subscriptions"; 

    var server = new SM({ host: host, port:9000});

    beforeEach(function (done) {        
        server.start(done);
    });
    afterEach(function (done) {
        server.stop(done);
    });

    it('should hit the mock server successfully', (done) => {
        console.log('http://' + host + ':9000' + resource);
        server.on({
            method: 'GET',
            path: resource,
            reply: {
                status:  200,
                body:    'worked'
            }
        });
        request.get({url:'http://' + host + ':9000' + resource}, (err, res, body) => {
            if (err) {
                console.log(err);                
            }
            expect(body).to.equal('worked');
            done();
        }).end();
    });
});
```

Error:

  1) Artemis mock server tests should hit the mock server successfully:

      Uncaught AssertionError: expected 'Not Found' to equal 'worked'
      + expected - actual

      -Not Found
      +worked
      
      at Request.request.get [as _callback] (tests/nock.test.ts:39:29)
      at Request.self.callback (node_modules/request/request.js:188:22)
      at Request.<anonymous> (node_modules/request/request.js:1171:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1091:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by lordKnighton** [comment]
@mrooths Have you made any progress with this issue?

**Comment by joshgav** [comment]
cc @chakkaradeep
