### ISSUE TITLE
Looking for the nodejs repo owner/owners

### ISSUE THREAD

**Issue by gitsense** [nodejs/help#56]
Hi,

I'm currently indexing the most popular GitHub repos and nodejs owns a bunch of them.  The reason for the indexing, is to make it possible for GitHub users to search for commits, diffs among other things in the nodejs repos.

You can learn more about the technology here:

http://gitsense.github.io

And I took some screenshots of what the node repo looks like and what searching for commits and diffs looks like, and put them here:

http://imgur.com/a/EjYGD

Due to GitHub's API call limits and the fact that I'll be indexing 50,000+ repos, polling for new commits isn't the best use of my API limits.  To keep the indexes as up to date a possible, I would need the repo owner to use webhooks to notify my indexers of new pushes.

No permission or privileges needs to be granted.  The repo owner just needs to use a secret SHA that I would provide, which would be used by GitHub to sign the push events.

Sorry if this isn't the right place to ask this question, but I'm hoping this question will lead to the repo owner.

Thanks,
Terrence

**Comment by bnoordhuis** [comment]
I'm fairly sure we're unwilling to support or endorse third parties that are not core to our mission.  I'll close the issue on that assumption; if other collaborators disagree, please reopen.
