### ISSUE TITLE
Does NodeJS have any plans for shared memory?

### ISSUE THREAD

**Issue by hitsthings** [nodejs/help#560]
So [this API](https://github.com/tc39/ecmascript_sharedmem) is being added to JS that allows different execution contexts to share a chunk of memory safely with interleaved access.
Meanwhile the Web Worker spec already exists for creating these separate execution contexts.

I know there are pre-existing user space modules for web-worker implementations. But they either 1) use separate processes for each thread (and thus can't really share memory well), or 2) they literally expose all memory to all threads and thus accept all the chaos that other multithreaded languages often have.

Combined, the Web Worker and Shared Memory APIs seem like a solid infrastructure to build multithreading on. There would be no bad interaction with old code since the old code would have to opt in to using the shared buffer (or a bad dev would have to pass a shared buffer to the old code and then write to it). Is there any plan for making use of shared memory and web workers in Node?

**Comment by bnoordhuis** [comment]
> Is there any plan for making use of shared memory and web workers in Node?

Not at the moment.  It's not completely out of the question but:

1. Web workers are straightforward to implement through a native module.  If the existing modules aren't any good, that doesn't mean it's impossible, just that no one has done it yet.

2. Cross-platform shared memory and synchronization is a bit of a viper's nest.  Node would have to support it out of the box on all the platforms it supports, a native module can get away with supporting just the three major ones: Linux, Windows, TOSFKAOSX (The Operating System Formerly Known As OS X.)

**Comment by hitsthings** [comment]
Thanks for the info :) Wasn't expecting such a fast answer. Thanks for the alternative of a native module, too!

**Comment by addaleax** [comment]
Also, just fyi: https://github.com/audreyt/node-webworker-threads :)

**Comment by hitsthings** [comment]
Thanks @addaleax ! I was under the impression those threads still shared memory, but sounds like I'm wrong. Also I realized that I kinda completely forgot about https://nodejs.org/api/vm.html and this whole thing is probably just a derp. Thanks for setting me straight!

**Comment by sam-github** [comment]
I don't know what a derp is, but the VM API is  completely unrelated to threading or concurrency.

**Comment by hitsthings** [comment]
But it does allow executing code in a separate context. If a threading
library used it to isolate the memory that different threads have access
to, they could still pass sharedArrayBuffers between those threads'
contexts. At least I think they could - my understanding of all of this is
very high level and I'm sure there's a devil in the details.

**Comment by bnoordhuis** [comment]
@hitsthings Contexts are tied to their isolates, and those are not thread-safe.  That is, you can't have two contexts in the same isolate and access them from different threads.

(You can pass SharedArrayBuffers between contexts but there won't be any real concurrency, it'll be strictly sequential.)

**Comment by ORESoftware** [comment]
@hitsthings I would highly recommend just using different node.js processes instead of the node-webworker-threads lib; unfortunately the the node-webworker-threads lib is not very stable and has major API deficiencies last time I checked.

**Comment by hitsthings** [comment]
Thanks, I get that separate processes is the current standard. I posted this originally because shared memory seemed like a great opportunity for threads. Most cases are good with share-nothing concurrency which is what you get with processes (and anything you want to pass between them is slower over IPC afaik). I had a case a few years back where I was trying to implement real-time tracking and mapping for nodecopters (for fun, so meh on stability). One big performance hurdle was that I needed to pass large chunks of image data, edge detection data, etc between processes. That's where threads would help since I wouldn't have to pass anything around to access it in multiple threads.

To be clear - I'm not asking about doing anything in production code. Was just curious about whether there were any ideas/plans for threading with sharedArrayBuffers in node that might help me with problems like that.

Ben - thanks for the VM clarification.

**Comment by sam-github** [comment]
you can share memory between processes as well as between threads, bunch of stuff on npmjs, I vouch for the quality of none of it :-)  https://www.npmjs.com/search?q=shared+memory

**Comment by icodeforlove** [comment]
Would love to see some sort of equivalent for Workers, transferable objects and SharedArrayBuffer's.

`node-webworker-threads` is probably the closet you can get at the moment and from my experience its fairly unstable.

As it currently stands it is easier to take advantage of all cores and memory in the browser vs node. Which makes me sad :(.

**Comment by addaleax** [comment]
@icodeforlove Hey, just so you are aware: https://github.com/nodejs/node/issues/13143, https://github.com/nodejs/worker. :)

**Comment by refack** [comment]
> @icodeforlove Hey, just so you are aware: nodejs/node#13143, https://github.com/nodejs/worker. :)

@addaleax talk about "hitting the nail of the head" 😄 
@icodeforlove You are most welcome to participate in the discussion (esp. https://github.com/nodejs/worker/issues/1)

**Comment by Pacerier** [comment]
@ORESoftware, @addaleax, That's not shared memory. It's using message parsing which is slow.

**Comment by Pacerier** [comment]
I've been waiting for this for a loong time, when will they decide to implement this?

This is the **dealbreaker**, making me choose Java instead of Node for server apps.

**Comment by gireeshpunathil** [comment]
Linking this one with [14158](https://github.com/nodejs/node/issues/14158) which is potentially capable of covering this requirement.

**Comment by refack** [comment]
> Linking this one with 14158 which is potentially capable of covering this requirement.

Just to make that clearer $mdash; #14158 is a discussion about better supporting the embedding of node in-process into other apps. It covers the use case of single process memory sharing, and also allows the embedder to implement inter-process memory sharing.

**Comment by runvnc** [comment]
Isn't SharedArrayBuffer part of V8? Apparently not.
If Node won't add that stuff then once people are used to those features being available in the browser and they can't find it in Node then they will start just like running headless Chrome on the server in order to get those features.

**Comment by runvnc** [comment]
Which is obviously a pretty wonky hack to work around missing features.

**Comment by runvnc** [comment]
After people get used to taking advantage of it in the browser, the sentiment will go pretty quickly from 'who needs this they must not know how to Node' to "why the heck didn't they implement this already".

**Comment by Pacerier** [comment]
@p3x-robot Re "haha" Meaning?

**Comment by Pacerier** [comment]
@runvnc, re "running headless Chrome on the server"; but with Oracle and its billions of $$ on proper Java support for shared memory?

**Comment by allenluce** [comment]
While it's not a general solution, I ended up writing a [module (in C++) to handle shared memory](https://www.npmjs.com/package/mmap-object). It produces objects backed by a key-value store kept in shared memory.

**Comment by allenluce** [comment]
Direct access to (shared) memory is definitely faster than either Redis or `process.send` (which uses a Unix domain socket underneath, at least on my Mac). This is especially true in the case of random accesses and even more so when no synchronization is required (i.e. in the read-only case). I was led to [mmap-object](https://www.npmjs.com/package/mmap-object) after finding that Redis was far too slow for my application (even when configured to use Unix domain sockets).

**Comment by mogill** [comment]
It is telling people continue to comment on this issue more than 8 months after it was closed. Experimentation with parallelism and shared memory in Node has been ongoing for years, and there is a diverse set of implementations for curious programmers to evaluate and use.

I created a [List of Parallel JS Projects](https://github.com/SyntheticSemantics/List-of-Parallel-JS-Projects) that compares the various approaches.  Some of these tools may be useful until there is built-in support.

**Comment by Pacerier** [comment]
@p3x-robot, re "process.send is fast"; Done graphics and other baremetal code before?
Re "why"; because whatever that's fast today is slow tomorrow as demands can only go **up**.

**Comment by Pacerier** [comment]
@p3x-robot , NodeJS wants to replace Java/C++/PHP/C/ASM/etc (other "server-side" environments). But it simply can't until it can do proper multi-processing.

Re "how do you use shared memory with different servers"; It can be built the same way everything else is built as long as you first have shared memory on a single server.

**Comment by kyr0** [comment]
@allenluce Still people are suffering here :D My solution uses shared memory device shm (Linux, macOS / virtual shared memory page (Windows) based on my project [libsharedmemory] (https://github.com/kyr0/libsharedmemory) --> [node-libsharedmemory](https://github.com/kyr0/node-libsharedmemory)

If we'd merge our code bases, we could simply use my lib as the backend to your file-based impl. and get the holy grail of a real shared memory for Node.js. Do you or anyone else have time and energy to join? :)
