### ISSUE TITLE
Yikes, require.resolve('cluster') => 'cluster'

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#563]
I am looking for help on how to get the absolute path to a core module on the filesystem

the problem I am seeing is that require.resolve(), when called on a core module, literally just prints out the name of the core module, *not* the absolute path to the module code, e.g.

```js
console.log(require.resolve('cluster')) => 'cluster'
console.log(require.resolve('assert')) => 'assert'
```

how can I get the full/absolute path to the core module on my filesystem?

The reason I need this is because I am looking to bundle core modules for the browser.

**Comment by evanlucas** [comment]
Core modules are baked into the binary, so they don't have a full path, just a relative path from the lib directory of the source code.

**Comment by refack** [comment]
__not a solution__ but the closest thing you can do is download their source from https://github.com/nodejs/node/tree/master/lib

**Comment by ORESoftware** [comment]
If it's not clear, I need to get the path programmatically :)

It's _not even a relative path_, run my code, it's literally just the name of the core module.

I can't work with that at all. :(

**Comment by SomeoneWeird** [comment]
Are you using webpack or browserify?

**Comment by ORESoftware** [comment]
@SomeoneWeird I am willing to use anything, right now I am trying to work with SystemJS and the systemjs-builder

**Comment by SomeoneWeird** [comment]
If you use either of them, you should just be able to require stuff like `assert` and it will automatically polyfill it.

**Comment by ORESoftware** [comment]
Ahh that's cool, I might just use webpack then, if you have a link to a simple example, that would be awesome, although I can probably find something good.

**Comment by lordKnighton** [comment]
@ORESoftware have you made progress with this issue, let me know, if all good then close this issue.

**Comment by ORESoftware** [comment]
yeah, thx, closing
