### ISSUE TITLE
Server tool for Nodejs

### ISSUE THREAD

**Issue by TorinW** [nodejs/help#564]
Hi,
I'm new to nodejs app development and I would like to know whether there are any existing server tools (eg: XAMPP/ WAMP for apache) which can be used for nodejs. 
I specifically searching a tool for WebSocket app development with nodejs.

**Comment by ORESoftware** [comment]
@TorinW  Checkout socket.io on NPM. You can create a websocket server easily, something that Node.js is good at. Try this tutorial:

http://thejackalofjavascript.com/websockets-and-sockets-io/
