### ISSUE TITLE
Garbage collection upon process.nextTick()

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#568]
Been curious about this for awhile - does using` process.nextTick()` aid in garbage collection, or does it make memory consumption (generally / on average) worse?

I was hypothesizing that perhaps V8 did some GC when `process.nextTick() `was called (or Node told V8 to GC).

**Comment by Fishrock123** [comment]
`process.nextTick()` runs a function asynchronously after the end of the current async entry callstack.

That is, it runs *before* I/O poling is done next, but after the current synchronous callstack.

the same is roughly true even if you schedule nextTicks within nextTicks, which can result in an infinite loop, as I/O polling (libuv) is not hit inbetween.

tl;dr: the function is horribly misnamed. It works nothing like the function name suggests.

**Comment by Fishrock123** [comment]
More information may be available in [the docs](https://nodejs.org/dist/latest-v7.x/docs/api/process.html#process_process_nexttick_callback_args).

**Comment by Fishrock123** [comment]
It does not interact with GC in any special way, fwiw.

**Comment by ORESoftware** [comment]
ok thanks, was just curious
