### ISSUE TITLE
Implementing process.stdout.write and process.stderr.write in the browser

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#569]
This applies to Node.js versions 4.0.0-7.x

I have some Node.js code, and would like to get it running the browser. In many places in my Node.js code, I have made calls to `process.stdout.write` and `process.stderr.write`.

In the browser, we have console.log / console.error

I do not need high-performance here. If I implement these methods in the browser like so:
```js
    process.stdout.write = function(v){
       return console.log(v);
    };
    
    process.stdout.error = function(v){
       return console.error(v);
    };
```

that's obviously not going to really get us what we want.
Is there a way to hook into console.log / console.error in the browser to print to stdout/stderr without printing a newline char?

This is sort of about Node.js but more about browser internals, but thought someone might know around here, thanks

**Comment by bnoordhuis** [comment]
Something like this?
```js
var stdout = '';
process.stdout.write = function(s) {
  stdout += s;
  for (var i; -1 !== (i = stdout.indexOf('\n')); stdout = stdout.slice(i + 1))
    console.log(stdout.slice(0, i));
};
// Ditto for stderr.
```
But you'll need a way to flush the last slice.

**Comment by ORESoftware** [comment]
@bnoordhuis thanks that looks good, partly I asked the question to see if anyone know of some super secret browser magic that would get into the internals of console.log in the browser, but your code should work, I will try it
