### ISSUE TITLE
App design: getting the full & accurate stack trace on error

### ISSUE THREAD

**Issue by ivanakimov** [nodejs/help#572]
Before, with callbacks, we could design functions like this:

```javascript
doSomething(function(err, result) {
  if (err) { return done(err); }
  /* do something with result */
}
```

This `if (err) { return done(err); }` allowed to keep track of which functions were called when.

So, when an error happened 12 levels deep, you could see a complete stack trace of function calls and trace how that function order was called. Now, when we try the same with `async/await`:

```javascript
try {
  const result = await doSomething();
  /* do something with result */
} catch (err) {
  console.error(err);
}
```

You don't get the full stack trace, as all you get is a) the immediate error that happened and b) `process._tickDomainCallback`.

What's the proper way to design your app with `async/await` so that you can see a complete function stack trace?

P.S: I've tried `longjohn` and `stackup` with no useful help.

**Comment by ORESoftware** [comment]
@ivanakimov typically you would get short stack traces with true asynchronous callbacks. But I am not sure why you would get short stack traces with async/await, will wait to see what someone else says.

**Comment by ivanakimov** [comment]
@ORESoftware thanks for responding. Here's a concrete example:

Long trace, code:

```javascript
const getA = async () => await getB();
const getB = async () => await getC();
const getC = async () => {
  sdfg();
  const ret = await getD();
  return ret;
};
const getD = async () => true;

const start = async () => await getA();
start().then(r => console.log(r)).catch(e => console.error(e));
```

Output (which is great):

```bash
Desktop ❯ node --harmony test
ReferenceError: sdfg is not defined
    at getC (/folder/test.js:5:2)
    at getB (/folder/test.js:3:32)
    at getA (/folder/test.js:2:32)
    at start (/folder/test.js:11:33)
    at Object.<anonymous> (/folder/test.js:12:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

---

Now I change the position of `sdfg()` to be **after** `getD()`:

```javascript
const getA = async () => await getB();
const getB = async () => await getC();
const getC = async () => {
  const ret = await getD();
  sdfg();
  return ret;
};
const getD = async () => true;

const start = async () => await getA();
start().then(r => console.log(r)).catch(e => console.error(e));
```

Output (only `getC` is visible):

```bash
Desktop ❯ node --harmony test
ReferenceError: sdfg is not defined
    at getC (/folder/test.js:6:2)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

As you can see, `getA` and `getB` are no longer in the stack trace. I want to understand why that is, and how to get it to show actual stack trace (like in the first example) because this is really hard to debug for complex webapps...

**Comment by bnoordhuis** [comment]
You can't right now, if I understand you correctly.  The machinery for the async stack traces you have in Chrome hasn't been hooked up yet in Node.  It's on the roadmap but it probably won't happen before Node 9 (Q4 2017.)

**Comment by ORESoftware** [comment]
In the meantime, if you are really in need of the best possible stacktraces, you could try using Node.js domains, not sure if the stacktraces will be better though

**Comment by bnoordhuis** [comment]
Domains don't work with microtasks (what promises and async/await are under the hood.)

**Comment by ORESoftware** [comment]
yeah they do, if you add the following :)

```js
const then = Promise.prototype.then;
Promise.prototype.then = function (fn1, fn2) {

  if (process.domain) {
    fn1 = fn1 && process.domain.bind(fn1);
    fn2 = fn2 && process.domain.bind(fn2);
  }

  return then.call(this, fn1, fn2);
};
```

it is tried and true, it works

**Comment by ORESoftware** [comment]
You know that patch is sexy @bnoordhuis

**Comment by ivanakimov** [comment]
@bnoordhuis many thanks for explaining why that's happening and that it's on the todo list. Q4 2017 doesn't sound too bad... :)

@ORESoftware many thanks for the hint about domains and the `Promise` code. We're using `hapi.js`, but I guess it'd work the same way. I'll give that a shot.

I'll close the issue now. Thank you both for taking the time.

**Comment by ORESoftware** [comment]
@ivanakimov just fyi the test framework for HapiJS (Lab) uses domains - they are pretty domain friendly over there at HapiJS. Some people are for them, some are against, I personally like them, they might solve your problem in the short term.

**Comment by lll000111** [comment]
@ivanakimov It's a late reply, but the reason the stacktrace "disappeared" when you changed the ordered is that before you did that your function calls were not _really_ asynchronous - you got a normal (synchronous) stacktrace. By changing the order you made it _actually_ asynchronous.

Example for how I handle this problem: https://gist.github.com/lll000111/3d6a53da4d53beb909189793c7631ba6

Yes, it sucks - runtime code has to be burdened with something that should be internal, separation of concerns, etc.. I tried different methods, this is the only thing that works across JS runtimes (not just node) and that I can leave in production code (where random errors are much harder and much more important to track down compared to errors happening in my well thought-out test cases) and which gives me the best stack trace.

**Comment by ivanakimov** [comment]
@lll000111 thanks for following up. Helpful! 👍

**Comment by lll000111** [comment]
@bnoordhuis In [your reply above](https://github.com/nodejs/help/issues/572#issuecomment-293186024) you said 

> The machinery for the async stack traces you have in Chrome hasn't been hooked up yet in Node. It's on the roadmap but it probably won't happen before Node 9 (Q4 2017.)

But using node v9.4.0 &mdash; but it is the same situation in Firefox, IE Edge and Chrome (all latest versions) &mdash; shows that asynchronous stacktraces still don't work. A [V8 developer wrote "Asynchronous stack traces: why await beats .then()"](https://mathiasbynens.be/notes/async-stack-traces) in which he wrote about just this subject, but a sentence near the end sounds as if this wasn't (isn't?) implemented yet. I don't understand the discussion, because my tests show that asynchronous stacktraces don't work *anywhere* (keep in mind what I said above, with links, simplified examples that are not truly asynchronous don't work as demo, they seem to get an internal JS runtime optimization that indeed produces a true stacktrace, but not when the function is truly asynchronous, see my comment above).

**Comment by dusan-dragon** [comment]
@jd327 ping any news here?

**Comment by devsnek** [comment]
this is implemented now.

**Comment by justinmchase** [comment]
@devsnek In what version? Do we have to do anything special? I'm still getting the old callstacks and am wondering what needs to be done to enable it?
