### ISSUE TITLE
TypeError: response.sendfile is not a function

### ISSUE THREAD

**Issue by gkumarOB** [nodejs/help#573]
```js
var http = require('http');
var mysql = require('mysql');
var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password:'root',
    database: 'node_form'
});

console.log('MySQL Connection details  '+connection);

http.createServer(function (request, response) 
{ 
        console.log('Creating the http server');
        connection.query('SELECT * FROM manager ', function(err, rows, fields)
        {     
                response.writeHead(200, { 'Content-Type': 'text/html '});
                response.write(JSON.stringify(rows));
                response.sendfile( __dirname + "/index1.html",rows);
                response.end();
        }); 

}).listen(8087);

**Comment by gireeshpunathil** [comment]
It is true, and working as designed. Please refer [node.js API documentation for HTTP](https://nodejs.org/dist/latest-v7.x/docs/api/http.html) to see that sendfile is not a function of http.ServerResponse.

You could actually read from the file, append the content with the resultset, and then send it to the client something like: (untested code, please validate)

`response.write(require('fs').readFileSync( __dirname + "/index1.html").toString() + rows)`

Don't know whether you mean to append the resultset onto the content of the index file or not, but will need to do the integration manually.

Hoep this helps.

**Comment by gkumarOB** [comment]
@gireeshpunathil Thank you but i am trying to append into my html page in "table" tag.Its not able to generate "tr" tag in the table rather yours is actually appending it in the last .

```html
<!doctype html>
<html lang="en">
<head>
   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <meta charset="UTF-8">
  <title>Mysql Editor</title>
</head>
<body>
  <h1>Hello Manager</h1>
  <table id="tab">
  </table>

  
   <script>
   $(document).ready(function  () {
      for (var i = 0; i<=result.length; i++) {
        var id=result[i].id;
        var user=result[i].user;
        var pass=result[i].PASS;
      document.getElementById("tab").innerHTML= "<tr><td>" + id + " " + user + " " + pass + "</td></tr><br>";
      };


    
   });
  </script>
</body>
</html>
```
```js
var http = require('http');
var mysql = require('mysql');
var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password:'root',
    database: 'node_form'
});
 
console.log('MySQL Connection details  '+connection);

http.createServer(function (request, response) 
{ 
        console.log('Creating the http server');
        connection.query('SELECT * FROM manager ', function(err, rows, fields)
        {     
                response.writeHead(200, { 'Content-Type': 'text/html '});
                rows=JSON.stringify(rows) ;         
               response.write(require('fs').readFileSync( __dirname + "/index1.html").toString() + rows);
               response.end();


        }); 

}).listen(8087);
```
```output
software@OB116-33:~/Desktop$ node mysql.js
MySQL Connection details  [object Object]
Creating the http server
[ RowDataPacket { id: 1, user: '80001', PASS: '1234' },
  RowDataPacket { id: 2, user: '80002', PASS: '1234' } ]
Creating the http server
[ RowDataPacket { id: 1, user: '80001', PASS: '1234' },
  RowDataPacket { id: 2, user: '80002', PASS: '1234' } ]

```
P.S 
the main idea is to retrieve data from mysql database in server.js file and then forward the data to my predefined html structure and display the data there.

**Comment by gireeshpunathil** [comment]
right -  as I told you, if you want the resultset to be blended into the HTML, that is a manual composition of a dynamic page. 

I am not an expert in HTML rendition logic, so cannot comment further on this.

BTW, your this line:

`response.sendfile( __dirname + "/index1.html",rows);`

Seems to be an abstract code without any apparent bearing in any API or framework - rather justified by the intent alone - to send a composite HTML file, augmented with some dynamic content. Probably you would get a working sequence in the repository / API doc of the module from where you would have derived that sequence.

Hope this helps.

**Comment by gkumarOB** [comment]
@gireeshpunathil buddy i m stuck dont know what to do and how to do.
https://github.com/expressjs/express/issues/3281 

can u check this code too.
many thanks

**Comment by gireeshpunathil** [comment]
while the problem is well understood - sorry, your requirement looks abstract to me.

**Comment by sam-github** [comment]
You are trying to call an express API on node, it doesn't work and it isn't supported. You need to use node's API, as @gireeshpunathil pointed out, or more likely you should actually be using express, check out http://expressjs.com (note that express has a rsp.sendfile()).
