### ISSUE TITLE
Trouble with FileSystem

### ISSUE THREAD

**Issue by toruk0109** [nodejs/help#574]
* **Node.js Version**: 7.8.0
* **OS**: Windows 10 NT
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

Hello,
I need some help!

I tried to learn how to use Node.js inside my JS-files. I did the same as at the beginning here (https://nodejs.org/api/fs.html#fs_file_system).
`var fs = require('fs');`
But it failed with the error
`Uncaught ReferenceError: require is not defined at <filename> <line number>`
Why is this? Please help.

Thanks, Alex.

**Comment by bnoordhuis** [comment]
Guess you're not actually using node.  How and where exactly are you running those JS files?

**Comment by gireeshpunathil** [comment]
Probably in a Browser's console?

**Comment by toruk0109** [comment]
bnoordhuis, I've got local server (it's installed right on my PC), and I've got Node.js on my PC. From docs on Node.js website I can't understand what to do first, before using Node.js functionality via my web application. To store some data to files (like JSON file) is too important for my app. Do U have any ideas?

**Comment by gireeshpunathil** [comment]
> I've got local server (it's installed right on my PC), and I've got Node.js on my PC

Are they both different? Node.js is ideal to be used as a web server.

For basic sanity, you can follow the below sequence, and then build your logic around it.


```
#cat foo.js
const fs = require('fs')
let str = fs.readFileSync('./json.input');
var obj = JSON.parse(str.toString())
console.log(obj);
#which node
/usr/local/bin/node
#node -v
v7.8.0
#cat json.input
{"message":"hello world!"}
#node foo.js
{ message: 'hello world!' }
#

```

**Comment by toruk0109** [comment]
> Are they both different?
What do you mean? 

> `#cat foo.js
const fs = require('fs')
let str = fs.readFileSync('./json.input');
var obj = JSON.parse(str.toString())
console.log(obj);
#which node
/usr/local/bin/node
#node -v
v7.8.0
#cat json.input
{"message":"hello world!"}
#node foo.js
{ message: 'hello world!' }
#`
Is it JS code? Or not? :) I'm new in Node.js :)

**Comment by gireeshpunathil** [comment]
If you are too new to node.js to follow my previous sequences, I suggest you to go through [usage examples](https://nodejs.org/dist/latest-v7.x/docs/api/synopsis.html) and [command line options](https://nodejs.org/dist/latest-v7.x/docs/api/cli.html#cli_command_line_options) to start with, and then follow the internal links fitting to your purpose and progress thereon, but please revert when you have specific issues at hand.

**Comment by toruk0109** [comment]
> If you are too new to node.js to follow my previous sequences, I suggest you to go through usage examples and command line options to start with, and then follow the internal links fitting to your purpose and progress thereon, but please revert when you have specific issues at hand.

Thank you very much! I'll follow your advice! Thank you! ^)
