### ISSUE TITLE
Why HandleWrap is not managed by GC?

### ISSUE THREAD

**Issue by jiakai1000** [nodejs/help#58]
I think nodejs can make HandleWrap to be Persist weak object, so v8 can collect the inaccessible object and close the underlying file descriptor automatically, but why it isn't ?

var net = require('net');
var PORT = 8000;
var tcpServer = net.createServer(function(socket) {
    console.log('new client');
    // after run out of this callback, `socket' becomes inaccessible, so v8 can collect it
});
tcpServer.listen(PORT);

**Comment by kelthenoble** [comment]
Here are some resources. Let us know if you need further help.   
![screen shot 2015-12-24 at 7 08 26 pm](https://cloud.githubusercontent.com/assets/1773260/11999408/c3fed208-aa71-11e5-8642-31c9e632d719.png)   

https://developers.google.com/v8/embed#handles  & https://github.com/nodejs/nan

**Comment by jiakai1000** [comment]
In https://github.com/nodejs/nan/blob/master/doc/persistent.md#api_nan_persistent I saw a comment:
/**
   *  Install a finalization callback on this object.
   *  NOTE: There is no guarantee as to *when* or even *if* the callback is
   *  invoked. The invocation is performed solely on a best effort basis.
   *  As always, GC-based finalization should *not* be relied upon for any
   *  critical form of resource management! At the moment you can either
   *  specify a parameter for the callback or the location of two internal
   *  fields in the dying object.
   */
template<typename P>
  void SetWeak(P *parameter,
               typename WeakCallbackInfo<P>::Callback callback,
               WeakCallbackType type);

Is this the answer? anything else?

**Comment by bnoordhuis** [comment]
I replied to [your post on the node.js mailing list](https://groups.google.com/forum/#!topic/nodejs/PWFPPrJ1-DE) and I'll post it here as well:

> HandleWraps are strongly persistent precisely so they don't automatically close when the last reference to them goes away.
>
> In your example, the next major GC would collect `tcpServer` and close the server if handles were weak.

Hope that clears things up.
