### ISSUE TITLE
NodeJs Deployment

### ISSUE THREAD

**Issue by mdemarco1234** [nodejs/help#580]
I need to optimize NodeJs so that each server instance is a optimized as it can be. I did test. I spawned off 5000 threads simulating 5000 concurrent users. In the first test I inserted 60000 monotonically increasing integers into an array and then iterated through the array and wrote out each integer line by line to a file. Node failed out of the box with this load. I have read articles about tweaking kernal objects and file handles on a Linux box but we use Windows now. Not to say we won't go to Linux but have not yet. One reference spoke of tweaking /etc/security/limits.d and /etc/sysctl.conf. What is the equivalent in Windows? the second test was doing a simple search and returning 282 records and that was bad too. Certainly, we will load balance but I need to know how much we can squeeze out of an instance of NodeJs by tweaking the environment and when to route another request to a load balanced machine? This same test in .NET worked well for the first test but the second had issues. I did notice some degradation when using Postgre with to many concurrent requests.

**Comment by lordKnighton** [comment]
@mdemarco1234 you still need help with this?
