### ISSUE TITLE
Bash-style path interpretation directly from Node.js

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#581]
There might be an NPM module that already does this.

Say I have a JSON config file like so:

```json
{
  "searchRoots": [
    "$HOME/WebstormProjects"
  ],
  "ignorePaths": [
    "node_modules",
    ".git"
  ],
}
```

if I read this file in with Node.js, is there some utility I could use to interpret the "searchRoots" entries, to get the actual path?

**Comment by ORESoftware** [comment]
There is this, but I am looking for something even more generic.

https://github.com/jonschlinkert/expand-tilde

Maybe I will have to fork a 'bash' child process to actually get what I want.

Something like this:

```
const script = 'echo "$HOME/WebstormProjects";';
const k = cp.spawn('bash');
k.stdin.write('\n' + script + '\n');
k.stdin.end();

```

That might be the only way to make this generic enough.

**Comment by ORESoftware** [comment]
However, with that being said, it would be neat if there was Node.js utility that could take care of this, without the need to spawn a child process?

**Comment by addaleax** [comment]
I guess this might depend a lot on what you are looking for – do you want `~` expansion, environment variable expansion (`$HOME`, `$USER`), subprocess expansion (`$(ls)`), and probably many things I’m forgetting? :smile:

**Comment by ORESoftware** [comment]
yeah, I need to support not just ~ and $HOME, but any env variable, etc

**Comment by mk-pmb** [comment]
Spawning an actual bash is probably overkill unless you need all the features. Try [template2env](https://www.npmjs.com/package/template2env) in addition to `expand-tilde`. Seems like it doesn't have default value syntax though.
