### ISSUE TITLE
Problem in receiving output using stdout through application 

### ISSUE THREAD

**Issue by ayush191992** [nodejs/help#584]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I am trying to send input to child process through node.js application. I have spawn the child process using spawn method of node.js. The child process application is below behavior if we give any string using stdin along with $QUIT\n$ it will print some message in stdout and if we give some string along with keyword $END$ (child process will exit then ) as full application is in while loop and we need to give $END\n$ as terminating character to exit from application. I am trying to capture stdout after i give $QUIT$ to exit from inner while loop and second time I am trying to capture stdout after i give $END$ to exit from outer while loop. Child application is spawned during initialization of nodejs application,

But I am not able to capture the stdout after I am giving $QUIT\n$ to capture stdout from inner while loop.I am able to capture stdout from the application after my child process exit when I gave $END$ to exit the outer while loop.

Can you please help in this regard how we can capture the stdout when Outer loop is still in waiting condition to exit and inner loop is exited. How we can capture stdout from application which is still in running process.

**Comment by ORESoftware** [comment]
Probably need to show us your code.

**Comment by ayush191992** [comment]
@ORESoftware 
Here goes my code snippet for my child process
while(1)
{
while(1)
{
ch = getchar();
OutBuffer[i] = ch;
i++;
if(strstr(OutBuffer,"$QUIT$"))
{
char TempBuffer = (char)NULL;
printf("Quit Success");
break;
}
}
if(strstr(OutBuffer,"$END$"))
{
printf("End Success");
break;
}
}

I am trying to set variable var ChildWrapper in set environment variable function

var = ChildWrapper = spawn(currentDir + "\test.exe", ["1.json"], {shell:true});

In one function i am giving some string with
ChildWrapper .stdin.write("Test"+"$QUIT$\n");

and setting one global variable itest to send below output when function will execute second time

if(itest == 2)
{
wrapper.stdin.write("$END$\n");

}
but after send $END$ i am only able to receive stdout through application.

**Comment by ORESoftware** [comment]
Yeah...so you're coding this like it's a blocking language, like Java. JS is non-blocking and evented, totally different paradigm.

Here is how you write stdin of Node.js child process

```js

const k = cp.spawn('bash');

k.stdin.write('\n your bash command here \n');
k.stdin.end(); // call this when you are done writing to stdin of child

k.stdout.on('data, function(){
  // do something with stdout from child
});

k.stderr.on('data, function(){
  // do something with stderr from child
});

k.once('close' function(){
   // child process has ended
});
```

**Comment by ayush191992** [comment]
@ORESoftware 
I have tried this now when I am giving 
k.stdin("\n" + "$QUIT$\n");
k.stdin.end();

It is able to capture stdout.

but during second execution of that function  i.e

if(itest == 2)
{
  k.stdin.write("\n$END$\n");
  k.stdin.end();
}
It fails to capture stdout. Please note tht above condition ($QUIT$) was called once only and is inside if condition for the first execution of the function.

**Comment by mk-pmb** [comment]
> JS is non-blocking and evented, totally different paradigm.

Almost, but it's the other way around: Your JS code does, in fact, block.
Node.js does the I/O in separate threads, but unless you explicitly do thread stuff, your JS code always runs in one single thread.
As long as you keep that thread busy with your loop, it won't have time to communicate with its sibling thread, so it will never have a chance to learn that there's new data available.

What ORE probably meant is that you should always make your JS apps as non-blocking as possible. Work in tiny steps and have lots of gaps between them, so node.js can do the stuff you requested it to do.

When dealing with pipes, make sure you're either not using buffering or flusing them when appropriate. For 3rd-party programs, [stdbuf](https://linux.die.net/man/1/stdbuf) might help adjust their buffers.

**Comment by sam-github** [comment]
> Node.js does the I/O in separate threads

Fwiw, that's not true for sockets (TCP/UDP). It is only true for things like `fs` which have poor async support by the operating system. I tried to explain this in https://www.youtube.com/watch?v=P9csgxBgaZ8

**Comment by mk-pmb** [comment]
Fixed, thanks! :+1:
