### ISSUE TITLE
meta: access and policy for the help repository

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#587]
Should a collaborator ask for access to the help repository?

Say, every now and then I want to add backticks for code formatting in issues ([an example](https://github.com/nodejs/help/issues/584#issuecomment-294425189)) and find out I can't.

BTW, is it a good practice courtesy-wise? Should I explain the editing intervention for a poster? It increases a meta info a bit and bothers repo subscribers once more, but can be a necessary gesture demonstrating respect.

**Comment by addaleax** [comment]
See also https://github.com/nodejs/CTC/issues/58 – I think it’s safe to say that giving nodejs/collaborators access is consensus, this just needed a bump to get done. I’ll do it in a second. :)

> BTW, is it a good practice courtesy-wise? Should I explain the editing intervention for a poster? It increases a meta info a bit and bothers repo subscribers once more, but can be a necessary gesture demonstrating respect.

quoting https://github.com/nodejs/TSC/blob/master/Moderation-Policy.md:

> Minor edits to the formatting of a Post or to correct typographical errors are not considered to be "Moderation". Such edits and their intent should still be documented with a short note indicating who made the edit and why.

I think something that people have done is to add stuff like `(edited by @addaleax: added backticks for code blocks)` to the post itself, that way it’s still clear what happened and who did it, without adding noise.

**Comment by vsemozhetbyt** [comment]
@addaleax  Thank you!
