### ISSUE TITLE
IPC channel ignored if we spawn non-.js file?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#588]
This applies to node.js versions > 4.0.0

I am wondering if we have this:

```js
  let ext =   {
       cwd: process.env.SOME_PATH,
       stdio: [
       'ignore',
        (isStdoutSilent ? 'ignore' : 'pipe'),
        (isStderrSilent ? 'ignore' : 'pipe'),
       'ipc'  // <<<<<<< TODO: assume 'ipc' is ignored if not a .js file..
      ],
      execArgv: $execArgz
  };
```

we will always pass 'ipc' as an argument, I assume it's safe to use this even when spawning a non-nodejs process, and it will just be safely ignored?

**Comment by bnoordhuis** [comment]
It's not ignored, the process gets spawned with a fourth file descriptor besides the standard stdio file descriptors 0, 1 and 2.

**Comment by sam-github** [comment]
See docs: https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options

> Node.js processes launched with a custom execPath will communicate with the parent process using the file descriptor (fd) identified using the environment variable NODE_CHANNEL_FD on the child process. The input and output on this fd is expected to be line delimited JSON objects.

(Though the docs are in the wrong place, or at least, should also be in the spawn() doc entry).

**Comment by ORESoftware** [comment]
Thanks all, what I could really use is some official guide that tells Node.js users how to interact with Node.js parent process from a non-Node.js child process using IPC.

**Comment by sam-github** [comment]
> Node.js IPC is not really designed to play well with non-Node.js child processes.

Who told you that?

Node.js IPC is documented as to how to use with non-Node.js child processes, I included the the doc link above.

What info do you lack? I suggest asking more questions, because its not clear what is missing. The questions (and answers) then might be used to write a guide for https://github.com/nodejs/nodejs.org/tree/master/locale/en/docs/guides.

**Comment by ORESoftware** [comment]
@sam-github I don't think any of those docs explains how to communicate well with a node.js parent process via IPC. For example, is there a single doc that explains that when you send a message it has to be newline delimited JSON?

I asked this question on SO awhile ago (I guess I forgot the answer when I opened this question).

http://stackoverflow.com/questions/41033716/send-ipc-message-with-sh-bash-to-parent-process-node-js

an example like the answer given to the question in the Node.js docs would be a nice addition. I don't see anything like that in the Node docs?

**Comment by sam-github** [comment]
Still not seeing the question, sorry. The docs say:

> The input and output on this fd is expected to be line delimited JSON objects.

They don't explain how to get a fd number from an env var in any particular non-node language, or how to read/write JSON from the fd in a non-node language (of course). Your SO question is basically about bash programming, an arcane subject, admittedly.

It sounds like you are looking for a guide that shows examples in a number of languages of how to do this?

Its an interesting idea. You could open an issue for one (and describe what it should cover) on https://github.com/nodejs/docs/issues, but I'm not going to lie, the best way to get a guide is to contribute it yourself.
