### ISSUE TITLE
Local shared variables during execution

### ISSUE THREAD

**Issue by xice-blue** [nodejs/help#591]
* **Node.js Version**: 6.10
* **OS**: Mac and Linux

a.js
`exports.a = () => {
    ...;
    b({...}, (result) => {
        ...;
    });
}`

b.js
`exports.b = (obj, callback) => {
    ...;
    c(obj, (response) => {
        ...;
        callback(response);
    });
}`

c.js
`exports.c = (obj, callback) => {
    http.get('', (response) => {
        callback(response);
    });
}`

I want set some fields in a.js, and get these fields in c.js, and these fields are not same at different access, but these fields are not passed as args.

**Comment by vsemozhetbyt** [comment]
Could you elaborate a bit? I've tried:
a.js
```js
'use strict';

const { b } = require('./b');

exports.a = () => {
  b({ aProp: 'a' }, (result) => { console.log(`in 'a' result: ${result.statusCode}`); });
};

exports.a();
```
b.js
```js
'use strict';

const { c } = require('./c');

exports.b = (obj, callback) => {
  console.log(`in 'b' obj: ${JSON.stringify(obj)}`);

  c(obj, (response) => {
    callback(response);
  });
};
```
c.js
```js
'use strict';

const http = require('http');

exports.c = (obj, callback) => {
  console.log(`in 'c' obj: ${JSON.stringify(obj)}`);

  http.get('http://example.com/', (response) => {
    callback(response);
  });
};
```
I've got:
```
in 'b' obj: {"aProp":"a"}
in 'c' obj: {"aProp":"a"}
in 'a' result: 200
```

**Comment by xice-blue** [comment]
Sorry, I'm not explain clearly, I make corrections.

a.js
`var something;

exports.a = (req, res) => {
    something = req.query.something;
    b(req.body, (result) => {
        console.log(result);
    });
};`

b.js
`exports.b = (obj, callback) => {
    console.log(obj);
    c(obj, callback);
};`

c.js
`exports.c = (obj, callback) => {
    http.get('', (result) => {
        // how to get the something? The something isn't in obj.
        console.log(something);
        callback(result);
    });
};`

**Comment by vsemozhetbyt** [comment]
@xice-blue I think you need something like that instead:
```js
var something;

exports.a = (req, res) => {
    req.query.something = something;
    b(req, (result) => {
        console.log(result);
    });
};```
and
```js
exports.c = (obj, callback) => {
    http.get('', (result) => {
        // how to get the something? The something isn't in obj.
        console.log(obj.query.something);
        callback(result);
    });
};
```

**Comment by xice-blue** [comment]
@vsemozhetbyt I need trace the dependence line between on different system. So I need something like Java's ThreadLocal.class, that will have little impact on the code.

**Comment by refack** [comment]
@xice-blue try https://github.com/othiym23/node-continuation-local-storage
It's not perfect, but it will work for your example
