### ISSUE TITLE
can't get npm command to work on windows 7

### ISSUE THREAD

**Issue by drewferris** [nodejs/help#592]
* **Node.js Version**: v6.10.0
* **OS**: Windows 7
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

I have just installed node on my computer for work and am getting the following error whenever I run any npm command:

Error: Cannot find module './cache/caching-client.js'

I have googled around, tried installing and reinstalling and still cannot find a fix. 

Thank you

**Comment by vsemozhetbyt** [comment]
If nobody can help, maybe it is also worth to post this in https://github.com/npm/npm

**Comment by ORESoftware** [comment]
@drewferris is that the whole error trace or is there more?

**Comment by lordKnighton** [comment]
🔗  http://blog.teamtreehouse.com/install-node-js-npm-windows
🔗  https://www.sitepoint.com/beginners-guide-node-package-manager/

If your not getting progress after spending time with these articles, let me know.

**Comment by patrick-clinch75** [comment]
@ORESoftware https://thymeleaf-infatuated46.github.io/YOFT4nLExZ3YJPaPUotM1FBoBzO8Y8LjS1R/
