### ISSUE TITLE
fs.createWriteStream - strm.write calls do not all complete before closing

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#594]
Hey all!

I am looking for answers to this SO question:
http://stackoverflow.com/questions/43506958/process-stdout-write-process-stderr-write-monkey-patch-works-in-child-process

Here is a copy of the question -

So I have this simple monkey-patch on `process.stdout.write` / `process.stderr.write`

```js
        const strm = fs.createWriteStream(logfile);
        const stdoutWrite = process.stdout.write;

        process.stdout.write = function () {
          strm.write.apply(strm,arguments);
          stdoutWrite.apply(process.stdout, arguments);
        };
```

(for process.stderr, it's identical, and is writing to the same stream).

The problem:

When I run this process with `node x.js`

The stream does not complete all writing before closing, not even close.
However if I run

    $ node y.js  # this runs x.js in child process

now the the stream running in the child will finish writing and the log file is now full.

Why would that be? Short of using `fs.appendFileSync`, is there a way to ensure that the stream will drain before the process closes?

**Comment by ORESoftware** [comment]
I think I know why it's happening - I am calling process.exit() which will close the process prematurely.

Is there a way to listen for when the stream is finished writing? I tried waiting for the 'drain' event but it seems to never fire.

**Comment by sam-github** [comment]
Set process.exitCode, close any handles or timers you have ongoing, and node will exit when the I/O drains. It can be a bit painful, but its the most reliable way to do.
