### ISSUE TITLE
Node.js or framework at the begining 

### ISSUE THREAD

**Issue by duhamelstuff** [nodejs/help#595]
Is it a good idea to star learning Node (how to handler routers, form, such fundamental things) and, because I have a project to achieve, to jump to a﻿ framework like express, for example?

**Comment by ORESoftware** [comment]
You should start with Express to create servers. Trying to create a server, and especially doing the endpoint routing in Node.js without a framework, is a bit tricky.

**Comment by lordKnighton** [comment]
@duhamelstuff How is your decision coming along? If you need more help with this let us know.
