### ISSUE TITLE
[libuv][node-gyp] Segfault issues at GC sweep on low memory system

### ISSUE THREAD

**Issue by Neph0** [nodejs/help#596]
* **Node.js Version**: v6.10.0
* **OS**: Linux, 4.1.6 kernel
* **Scope**: Runtime

Hey,

I'm using some native C++ code to create a polling (poll(2)) interface in some Node.js software. The code itself works fine, however I'm getting a segfault **immediately** after each Garbage Collection sweep (like, starting Node.js with --expose-gc and calling `global.gc()` causes an instant SEGFAULT). Also, this behavior only happens on a low-memory (embedded) Linux. I can't reproduce it on my computer.

Here is the whole code: https://gist.github.com/Neph0/511fbd967300e231e91d5a9052c329b8

Any help woult be greatly appreciated. Thank you.

Also, if there is a Node.js native way of doing something similar, I'm completely open to straight up dropping the native C++ addon!

**Comment by Neph0** [comment]
Hello @bnoordhuis,

Running node from gdb causes a SIGILL, Illegal instruction. I'm using a v7.8.1 gdb. Any idea how to make it work? I'll look online...

**Comment by bnoordhuis** [comment]
Is it gdb or node that dies with a SIGILL?  If it's node, it's probably the CPU feature detection that happens at startup; just tap 'c' (for 'continue') a few times.

If all else fails, turn on core dumps with `ulimit -c unlimited` and inspect the core dump instead of a live process.

**Comment by Neph0** [comment]
Hey,

I managed to get a core dump of the segfault. Passed into gdb, I have a few symbols missing, but it still gives some information:

* [This is when I call global.gc() during C++ -> Node.js callbacks][1]
* I provoked the SEGFAULT when there should be no C++ -> Node.js callbacks being made, expecting a different stack trace, but it's actually the exact same.

Thanks in advance for any help.

[1]: http://i.imgur.com/aTqnJ2v.png

**Comment by bnoordhuis** [comment]
You are using the `Nan::NewBuffer()` overload that takes a pointer to a callback function but instead you are passing NULL.

**Comment by Neph0** [comment]
@bnoordhuis Oh... Well, that might indeed be the reason. I'll update the code and edit if that fixed it. No matter the outcome, thanks a lot for the help!

**Comment by Neph0** [comment]
Well... This is embarrassing. This was indeed the issue. And I thought the problem would be complex... Turns out I just needed to use the `Nan::NewBuffer(char* data, uint32_t size)` method instead of the other one with 4 parameters.

Thanks a lot @bnoordhuis, I owe you a beer. :smile:

**Comment by bnoordhuis** [comment]
Glad to hear it's working, I'll close this out.
