### ISSUE TITLE
module.exports = new A()

### ISSUE THREAD

**Issue by svipben** [nodejs/help#597]
Hello,

I'm wondering if I use for e.g. `module.exports = new A();` in the file `A.js` and that `A.js` will not be used by any other file with `require(...)` it will be cached to Node.js (if it's started with `node A.js`)? Because as I tested if I require that `A.js` in files like `B.js` and `C.js` it will be executed only 1 time (in the file who firstly required it), so it means after exporting it, it was executed and cached?

1. If `A.js` will be executed with `node A.js` and no one required it, it will be cached to Node.js?
2. If `A.js` will be used in `B.js` and `C.js` with `require(...)` it will be executed in the file who firstly required it and it will be cached? I mean no matter how much files require `A.js` it will be executed only 1 time in for e.g. `B.js` who was first?

**A.js**
```
const chalk = require('chalk');

class A {
  constructor() {
    console.log(chalk.red('Colored msg.'));
  }
}

module.exports = new A();
```

**Comment by bnoordhuis** [comment]
Yes to both/all three questions, with the caveat that B.js and C.js can programmatically delete it from their `require.cache` and then require it again.

**Comment by svipben** [comment]
@bnoordhuis Thank you very much for answer. Right now I discovered `require.cache` and `require.resolve`. Still new to Node.js :smile:

**Comment by refack** [comment]
Very roughly speaking modules implement the (per process) [singleton pattern](https://en.wikipedia.org/wiki/Singleton_pattern), with the caveat @bnoordhuis mentioned, and that if no one requires it, it will be run 0 times.

**Comment by refack** [comment]
> Still new to Node.js 😄

"Welcome to the dark side, we have cookies"

**Comment by svipben** [comment]
@bnoordhuis @refack What do you think guys, which is the best way to define private class which will not be executed and only will be used by node (it will be the main file which will be executed firstly). I like ES6 syntax (I'm from Java and C#) :smile: and code reads more easier if I use classes.

So I have these options:
1. 
```
new class A {
  ...
}
```
2.
```
class A {
  ...
}

new A();
```
3.
```
class A {
  ...
}

const a = new A();
```
4. Was with `module.exports` which I loved, but it Node.js caches it... :cry: 

P.S. I know this question is a little bit off topic :smile:.
P.S.S. Or it's better to avoid classes in such cases? When you use Node.js do you prefer classes?

**Comment by refack** [comment]
Personally I'd go with (3).
But know:
1) node caches modules only per process run. i.e. if you have `app.js` that requires `A.js` every time you run
    `node app.js` A __will__ be executed.
2) The flip side, unless you put `const a = new A();` in a method it will only run once, first time the module that contains it is required.

Think of all modules as closures wrapped with
```js
if (loader.cache[name] == null) {
  loader.cache[name] = (function (global, module, require) {
  ...
  }.bind(loader.module))(loader.global, loader.module, loader.require)
}
return loader.cache[name];
```
This is almost exactly what actually happens (was just too lazy to lookup the exact lines), even for the "main" `.js` file that is run.

**Comment by svipben** [comment]
@refack Very good code which explains a lot. Thank you very much!

**Comment by refack** [comment]
i.e.
## B.js
```js
class A {
  ...
}

export.theAwrapper = function ()
  const a = new A();
};
```

## app.js
```js
const B = require('B')

for (let i = 0; i < 500; ++i)
  B.theAwrapper()
```

**Comment by sam-github** [comment]
You want to be very careful assuming modules are singletons. It is true, but module in this case means "fully-resolved path on disk", it doesn't mean the "A" in `require('A')`. In particular, npm/yarn are free to lay modules out on disk any way they want as long as the end result is that module can require its direct dependencies. Their is absolutely no requirement for them to be de-duplicated, so no requirement that they be global singletons. In other words, when module A requires X, and module B requires X, they might get different instances of the X module. When various files in A require X, they will always get the same X, but that assumption breaks down quickly.

You might not notice this until your module tree gets more complicated, or until you include more modules in your app.

**Comment by svipben** [comment]
@refack @sam-github Thank you guys very much. :heart_eyes:

**Comment by slidenerd** [comment]
if a.js b.js and c.js are in the same folder and if you require("a") from b and c, I assume that is when the caching works, if C was in a different location and tried to require a , it would get a new instance, am I correct?
