### ISSUE TITLE
(C++, v8) Explicitly controlling when a JavaScript function returns

### ISSUE THREAD

**Issue by JoshuaWise** [nodejs/help#598]
* **Node.js Version**: 6.x.x-7.x.x
* **Scope (install, code, runtime, meta, other?)**: code/runtime

I'm writing a C++ native module for Node.js. I'm aware that I can execute C++ functions from JavaScript by wrapping them with `v8::FunctionTemplate` and then invoking `->GetFunction()` to return a JavaScript function. However, when that function is invoked from JavaScript code, it automatically returns when the C++ function returns. I need a way to explicitly return a JavaScript function invocation (long after the C++ function has already returned, for example).

```js
// example.js
myCppFunction(); // this shouldn't return until someOtherCppFunction() says so
doOtherStuff();
```

```c++
FunctionExecution execution; // global variable

NAN_METHOD(myCppFunction) {
  execution = info.functionExecution;
  return;
}

// ...later on, in some other function
void someOtherCppFunction() {
  execution.returnWith(Nan::New<v8::Number>(123.0));
}
```

**Comment by bnoordhuis** [comment]
I could go into detail but the short answer is "you can't."  What are you trying to do?  What would `myCppFunction` return to instead?

**Comment by JoshuaWise** [comment]
I realized I can accomplish what I need with [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*). Suffice it to say that I was trying to provided a particular API for registering custom [sqlite3 aggregate functions](https://sqlite.org/lang_aggfunc.html) using their [C API](https://www.sqlite.org/capi3ref.html), which is rather restrictive in how it is used.
