### ISSUE TITLE
En que consiste ser miembro de WG?

### ISSUE THREAD

**Issue by paulomcnally** [nodejs/help#60]
Hola  @julianduque me gustaría saber en que consiste ser miembro WG.

Quisiera estar revisando los issues en español donde pueda apoyar. Me parece genial este repo!

Saludos desde www.nodenica.com

**Comment by julianduque** [comment]
Salludos @paulomcnally, la idea del Grupo de Trabajo (WG) es tener un lugar centralizado donde se le pueda brindar ayuda o Community Support a usuarios de Node.js, que se necesita para participar? Pues exactamente eso que dices, participar de las discusiones en este repositorio y responder las preguntas que lleguen (bien sea en Inglés o Español).

PS: NodeNica, que bien, estaremos en contacto!
