### ISSUE TITLE
Request & cheer.io doesn't seem to scrape/work

### ISSUE THREAD

**Issue by siriate** [nodejs/help#601]
* **Node.js Version: 7.9.0**:
* **OS: Ubuntu 14.04**:

I've been playing around with cheerio and request and I wanted to try to learn to scrape websites. I tried reddit, and it worked, then I decided to try this on a bit more complex area Twitch.tv, I tried to scrape clips (video files) from twitch and I can't understand why it keeps giving me empty urls array.

```js
var request = require('request'),
	cheerio = require('cheerio'),
	fs = require('fs'),
	urls = [];

request('https://www.twitch.tv/directory/game/Counter-Strike:%20Global%20Offensive/clips', function(err,resp,body) {
	if(!err && resp.statusCode == 200) {
		var $ = cheerio.load(body);
		$('h3.cn-card__title a', 'ember2812').each(function() {
			var url = $(this).attr('href');
    		urls.push(url);
		});

  		console.log(urls);
 	}
});﻿
```
I've been trying to figure this out for HOURS, I'm not very experienced with node.js but it's the coolest language I have ever used.

My working reddit scraping version:

```js
var request = require('request'),
	cheerio = require('cheerio'),
	fs = require('fs'),
	urls = [],
	colors = require('colors');

request('http://www.reddit.com/', function(err,resp,body) {
	if(!err && resp.statusCode == 200) {
		var $ = cheerio.load(body);
		$('a.title', '#siteTable').each(function() {
			var url = $(this).attr('href');
			if(url.indexOf('imgur.com')!= -1) {
    			urls.push(url);
   			}
		});

  		console.log(colors.cyan(urls.join('\r\n')));
		fs.writeFile('links.txt', urls, function (err) {
		    if (err) 
		        return console.log(err);
		    console.log('Links were successfully saved into text file (links.txt)'.green);
		});
 	}
});﻿
```

It's really hard to find any help. I will thank you as much as I can!

**Comment by sam-github** [comment]
I think you should post your question in https://github.com/cheeriojs/cheerio/issues, along with the content of  the response body.

**Comment by ctl** [comment]
Try to replace request with something else. I had same issue while i tried to scrape one website. I changed request to axios and anything worked properly. Idk why
