### ISSUE TITLE
Is req.socket.bytesWritten safe to use for tracking bytes per request?

### ISSUE THREAD

**Issue by jotto** [nodejs/help#602]
How/when is `bytesWritten` incremented? Is it after a response is completely flushed? i.e. is it safe to use the `bytesWritten` getter as follows:

```js
app.use(function(req, res, next) {
  const bytesAtBeginningOfRequest = req.socket.bytesWritten || 0;
  res.on("finish", function() {
    console.log(
      "bytes for this request",
      req.socket.bytesWritten - bytesAtBeginningOfRequest
    );
  });
  next();
});
```

(because requests from slow clients reading long streaming requests won't increment `bytesWritten` until the data is completely flushed?)

**Comment by jotto** [comment]
cc @indutny

**Comment by refack** [comment]
No :(
https://nodejs.org/api/http.html#http_event_finish

**Comment by refack** [comment]
But but you can use this event https://nodejs.org/api/net.html#net_event_drain
something like:
```js
app.use(function(req, res, next) {
  const bytesAtBeginningOfRequest = req.socket.bytesWritten || 0;
  let bytesWritten = 0;
  req.socket.on("drain", function() {
   // I'm not sure about this line, but something of the sort
    bytesWritten += req.socket.bytesWritten;
  });
  res.on("finish", function() {
    console.log(
      "bytes for this request",
      bytesWritten - bytesAtBeginningOfRequest
    );
  });
  next();
});
```
I'm not sure about the the exact calculation inside the `.on("drain")` but it's guaranteed the buffer has been flushed.

**Comment by refack** [comment]
@jotto do you need any more information?

**Comment by jotto** [comment]
> do you need any more information?

Thanks for writing (and following up) @refack, sorry for the delay.

I don't understand the link you pasted to the finish event in the context of "No", I don't see anything there on why the finish event is not sufficient, if that's what you were alluding to.

**finish**

> this event is emitted when the last segment of the response headers and body have been handed off to the operating system

**drain**

> Emitted when the write buffer becomes empty. Can be used to throttle uploads.

Do you have reason to believe these are fired at different times?

**Comment by refack** [comment]
Yes:  
`finish` is fired by `node` when the data has been handed over to the OS
`drain` is fired by the OS when the buffer has been drained

**Comment by addaleax** [comment]
`finish` and `drain` are very different things. @refack’s description of the `finish` event seems accurate – `drain`, on the other hand, is called when there are no more pending writes on the Node side. That’s not really decided by the OS. You shouldn’t have any need to use it here.

@jotto Your original post seems like correct code to me.

**Comment by jotto** [comment]
@refack and @addaleax thank you both.

Now for a naive question (because I don't know how sockets work)

is `req.socket` unique per connection? That is, no other simultaneous connection can append to `req.socket.bytesWritten`?

**Comment by addaleax** [comment]
> is `req.socket` unique per connection? That is, no other simultaneous connection can append to `req.socket.bytesWritten`?

Yes – a single socket can be used for multiple requests/responses, but any request/response can only use a single socket. The `finish` event is when the socket is detached from the response object, so that should the right time to check things like the `bytesWritten` counter.

**Comment by jotto** [comment]
Thank you so much. I feel at ease using it now.

**Comment by refack** [comment]
@addaleax I stand corrected... That's the behaviour I've seen on Windows...

Is there a cross platform way to know that the data has been `ACK`ed?

**Comment by addaleax** [comment]
> Is there a cross platform way to know that the data has been `ACK`ed?

I’m pretty sure there isn’t, no. :/ (Googling shows solutions, but those have strong negative performance implications and wouldn’t be exposed through Node’s API anyway…)

**Comment by pps83** [comment]
In my case I try to track time that it takes to serve a request and surprisingly there is nothing in node's net/http code that can tell me when a request was sent out. The last 'finish' event is fired almost instantly in my case after I start handling requests. The only way to get time that remotely resembles real time that it took to serve a request is by handling 'drain' event on a response's socket. Which is kind of weird and messed up... what if I have a persistent connection that handles multiple requests: I may not get a single drain event until last request is completed.
I don't get: how is that something like this obvious is missing ?
