### ISSUE TITLE
https server with short lived ssl credentials

### ISSUE THREAD

**Issue by vsacheti** [nodejs/help#603]
We have ssl credentials which are short lived (age is few hours) and are keep getting refreshed on the box

If there anyway where a running server can reload the certificates without restarting.
In Java-Jetty world something like this can be done using [reload](http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/util/ssl/SslContextFactory.html#reload-java.util.function.Consumer-).

Is there anything similar in nodejs?

AFAIK, the only way to do this is to restart the server 
We figured we can do sort of dynamic reload if we are running in cluster mode. The master can watch the certificate files and `fork` a new worker and `kill` the existing workers gracefully on a cert update 

But I am not able to figure something on a standalone mode which can be graceful.

**Comment by bnoordhuis** [comment]
Node.js has no official support for that (yet) but see https://github.com/nodejs/node/issues/4464#issuecomment-296467506 for a workaround.

**Comment by vsacheti** [comment]
Thank You
