### ISSUE TITLE
node on LinuxPPC 32bit BE (Debian Jessie)

### ISSUE THREAD

**Issue by davigega** [nodejs/help#605]
Is there any binary file available for the above mentioned machine?

unfortunately I'm not able to build from source

**Comment by bnoordhuis** [comment]
I'm not aware of any.  Neither the project nor IBM or NodeSource provide ppc32 binaries.

**Comment by davigega** [comment]
Would it be possible to build it from source for/from my machine?

**Comment by gibfahn** [comment]
cc/ @nodejs/platform-ppc 

So you can't use a 64 bit build?

You can try building from source, but I suspect that it won't work (it certainly hasn't been tested by anyone to my knowledge).
