### ISSUE TITLE
Missing Internal Node.js libraries documentation

### ISSUE THREAD

**Issue by yagop** [nodejs/help#608]
I'm looking for Node "internal" documentation, mostly node.h (LoadEnvironment, FreeEnvironment, Start, etc.) but I wasn't able to found them.

Only references I found were in https://nodejs.org/api/addons.html but they are for Addons.

There isn't a Node.js Doxygen?

**Comment by bnoordhuis** [comment]
There is not.  The functions you mention are primarily intended for embedders (people embedding node.js in another application, like Electron.)  If you want to know more about them, just look up their definitions in src/node.cc and follow the code.

**Comment by yagop** [comment]
I know, that's my intention. I think documentation will be very welcome for embedders and people who want to understand Node.js.

**Comment by gireeshpunathil** [comment]
@yagop - feel free to come up with / get started with documentation on those interfaces

**Comment by gireeshpunathil** [comment]
inactive, closing. re-open if there is an outstanding action
