### ISSUE TITLE
Dapp init - Unhandled error event

### ISSUE THREAD

**Issue by dotnetspec** [nodejs/help#609]
Node.js Version: 6.10.2
    OS: Linux Mint 18
    Scope (install, code, runtime, meta, other?): initialization
    Module (and version) (if relevant): dapp init

on 'dapp init' I get:

```console
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Trying Test...
events.js:160
      throw er; // Unhandled 'error' event
```

**Comment by gibfahn** [comment]
Which module does `dapp init` come from? https://www.npmjs.com/package/dapp ?

**Comment by dotnetspec** [comment]
It came from https://github.com/dapphub/dapp
I did not npm install -g anything named 'dapp' that I can recall (only nodejs)
For nodejs I did the following:
https://www.npmjs.com/package/dapp/tutorial
Ubuntu
Run the following on your command line to install the source for nodejs
curl -sL https://deb.nodesource.com/setup | sudo -E bash -
Then, run this to get the latest nodejs package
sudo apt-get install -y nodejs
then going back to 

https://github.com/dapphub/dapp
I follow readme:
INSTALLATION
   make link                  install dapp(1) into /usr/local

I now run [sudo dapp init.txt](https://github.com/nodejs/help/files/966565/sudo.dapp.init.txt) and get a slightly different unhandled error:
xargs: shellcheck: No such file or directory
Makefile:13: recipe for target 'test' failed
make: *** [test] Error 127

**Comment by gibfahn** [comment]
Probably worth raising another issue in the dapp repo, as I'm not sure anyone here is likely to have much knowledge of how that works. I see you raised https://github.com/dapphub/dapp/issues/20 but it looks like that error is resolved, so maybe close that and open another one.

**Comment by dotnetspec** [comment]
Yes, I should head back to dapp now that I've got Node.js Version: 6.10.2
Thanks ...
