### ISSUE TITLE
node.js createWriteStream create empty file , and finish event (in stream.Writable) doesn't fire up

### ISSUE THREAD

**Issue by pooyamoha** [nodejs/help#61]
Hi ,

Plesae see this url in S.O for detail:
http://stackoverflow.com/questions/34516637/node-js-createwritestream-create-empty-file-and-finish-event-in-stream-writab

Thanks!

**Comment by kelthenoble** [comment]
Hey did you make progress with this issue?

**Comment by kelthenoble** [comment]
Closing for now, feel free to reopen.
