### ISSUE TITLE
USB IO Card recommendations?

### ISSUE THREAD

**Issue by humblewizard** [nodejs/help#610]
I'm looking for an IO module that plugs into my computer using a USB port that has drivers which make for smooth integration with node.js.

I need 8 lines of bidirectional IO with a couple of 10 bit A/D inputs and an D/A or pulse-width modulator output. 

Is there such a thing like that?

**Comment by lordKnighton** [comment]
Sorry for late response: Have you found a solution yet?

**Comment by humblewizard** [comment]
I haven't found an off the shelf solution. I've got a Arduino Nano and I'm going to use a software serial port on it to connect to my system and access the Nano's IO and A/D. I would have thought that something would be available off the shelf but I didn't find anything.

**Comment by lordKnighton** [comment]
Been pretty busy, sorry for not responding in a while😦  I wish i could be of more help. If you are still searching, maybe a thread or some sort. We should close this issue.  Or if you want to continue this conversation. Let me know to keep it open.

**Comment by humblewizard** [comment]
Thanks, you can close the issue.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: kelvin knighton <notifications@github.com> Date: 6/15/17  10:30 AM  (GMT-08:00) To: nodejs/help <help@noreply.github.com> Cc: Humblewizard <rbrunius@gmail.com>, Author <author@noreply.github.com> Subject: Re: [nodejs/help] USB IO Card recommendations? (#610) 
Been pretty busy, sorry for not responding in a while😦  I wish i could be of more help. If you are still searching, maybe a thread or some sort. We should close this issue.  Or if you want to continue this conversation. Let me know to keep it open.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nodejs/help","title":"nodejs/help","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nodejs/help"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lordKnighton in #610: Been pretty busy, sorry for not responding in a while😦  I wish i could be of more help. If you are still searching, maybe a thread or some sort. We should close this issue.  Or if you want to continue this conversation. Let me know to keep it open. "}],"action":{"name":"View Issue","url":"https://github.com/nodejs/help/issues/610#issuecomment-308813509"}}}
