### ISSUE TITLE
How to configure nodejs for Redis - One Master Two Slaves 

### ISSUE THREAD

**Issue by kumar163** [nodejs/help#615]
Node JS -- v0.10.36
NPM -- 2.7.6
OS : Linux --  2.6.32-642.3.1.el6.x86_64

We are trying to add another redis slave to the existing configuration of a master and a slave. We are using redis in a node app, where we are configuring redis master and slave like below in json file.

> 
> "redis" : {
> "master" : {
> "host" : "x.x.x.x."
> },
> "slave" :{
> "host" : "x.x.x.x."
> }}

As this is JSON, we can't add a new key as "slave". Could any one tell me how can I configure this?

Appreciate any help on this.

**Comment by gireeshpunathil** [comment]
please raise this up with https://github.com/antirez/redis .
