### ISSUE TITLE
Tab key operation for close button

### ISSUE THREAD

**Issue by ayush191992** [nodejs/help#617]
* **Node.js Version**6.10.3
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I am trying to close the Node.js compiled application using close button. On clicking close button the node,js compiled application got closed successfully.

But on clicking Tab or TAB+SHIFT key I am not able to get the focus on close button of node.js  compiled application.

Is it possible to to get focus on close button using TAB key and when we get focus hit enter to close the application? If Yes can you help me in the regard how can i fix in this using java script code

**Comment by vsemozhetbyt** [comment]
cc @nodejs/platform-windows

**Comment by bzoz** [comment]
Maybe `Alt + Space`? You can also terminate node app by pressing `Ctrl + C`

**Comment by ayush191992** [comment]
@bzoz  Thanks for your help ALT+space works
