### ISSUE TITLE
Reg: File Select Dialog Box

### ISSUE THREAD

**Issue by ayush191992** [nodejs/help#618]
* **Node.js Version**: 6.10.3 LTS
* **OS**: Windows 64 bit
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I am trying to use the accept file input for limit the file type that a user can choose when uploading a file. 

1. the problem is it would show "Custom Files" as file description in the file dialog which will confuse users about what type of file they should select.
  
<input id="file" type="file" name="file" class="upload" accept=".txt , .jpeg , .bmp">
 
Is there a way so that I can modify the text "Custom Files " to  any other names like " My Files"
 
2. Can i have a drop downlist for uploading different files for file select dialog box.
       like:   Text Files (.txt)
                Jpeg Files (.jpeg)
                All Files 

Below is the snap shot attached 

![prob](https://cloud.githubusercontent.com/assets/25947346/25897966/a9967aac-35a7-11e7-8d6d-5644d738db60.jpg)

Help me in this regard.

Thanks

**Comment by gireeshpunathil** [comment]
node.js core libraries do not cover GUI capabilities, however there are a number of open source libraries that do.
