### ISSUE TITLE
Meaningful install instructions

### ISSUE THREAD

**Issue by DavesBrain** [nodejs/help#619]
* **Node.js Version**: All
* **OS**: All
* **Scope (install, code, runtime, meta, other?)**: Site docs

Instructions for install are pretty much non-existent. New users to nodejs are stumped from the get-go.
At the very least, download/install instructions should advise that *system needs to be restarted* before nodejs is available. 

Remember: there is little point in writing documentation for those who already know the software; it is the uninitiated that are most in need of direction.

**Comment by gibfahn** [comment]
>Instructions for install are pretty much non-existent.

For Windows and Mac it should (hopefully) be pretty intuitive, double-click on the installer and follow the dialogs, if something doesn't just work that's probably a bug. If you want to use a different install method (or install on Linux) then there are [package manager docs](https://nodejs.org/en/download/package-manager/).

>New users to nodejs are stumped from the get-go.

That's a broad claim, we don't get many issues raised regarding the installer, do you know of other people who've run into problems?

>At the very least, download/install instructions should advise that *system needs to be restarted* before nodejs is available. 

I don't think that's true for any platform, which one did you use (you put `OS: all` so I can't tell)? I could be wrong regarding Windows (cc/ @nodejs/platform-windows).

If you have any more feedback regarding the installers let us know, we can always use more feedback on docs (or missing docs). It's often difficult to work out what "the uninitiated" need to know.

**Comment by seishun** [comment]
>system needs to be restarted before nodejs is available.

This is incorrect at least on Windows, Linux and macOS.

**Comment by refack** [comment]
>> system needs to be restarted before nodejs is available.
>
> This is incorrect at least on Windows, Linux and macOS.

For windows there's the %Path% issue... You need to know how to start a "parentless" cmd... or restart the shell... So you inherit the new ENV...
But a restart is not _necessary_ since no changes are done during a restart.

**Comment by refack** [comment]
Also I've never tried to run the installer while the `exe` is locked... Maybe WIX has some move on restart magic, or it asks you to kill the locking processes.

**Comment by jereupchurch** [comment]
https://nodejs.org/en/download/package-manager/
Just started. Wasting more time logging in and posting this than installing node. :/

**Comment by refack** [comment]
@DavesBrain do you need any more information?
