### ISSUE TITLE
Deprecation Warning and build struck

### ISSUE THREAD

**Issue by imharishsundar** [nodejs/help#620]
* **Node.js Version**: v7.10.0
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: install, run
* **Module (and version) (if relevant)**: 

sudo npm install

node-zopfli@2.0.2 install /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli
node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/.node-gyp"
make: Entering directory /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/build' make: *** No rule to make target../.node-gyp/7.10.0/include/node/common.gypi', needed by Makefile'. Stop. make: Leaving directory/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:194:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-229.el7.x86_64
gyp ERR! command "/usr/bin/node" "/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/lib/binding/node-v51-linux-x64"
gyp ERR! cwd /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node --module_name=zopfli --module_path=/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/lib/binding/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack at ChildProcess. (/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.10.0-229.el7.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node --module_name=zopfli --module_path=/var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare/node_modules/node-zopfli/lib/binding/node-v51-linux-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/core@2.4.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/http@2.4.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@3.3.0 requires a peer of @angular/core@2.3.0 but none was installed.
npm WARN @angular/router@3.3.0 requires a peer of @angular/common@2.3.0 but none was installed.
npm WARN @angular/router@3.3.0 requires a peer of @angular/platform-browser@2.3.0 but none was installed.
npm WARN @angular/router@3.3.0 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.25 requires a peer of @angular/core@^4.0.3 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.25 requires a peer of @angular/common@^4.0.3 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.25 requires a peer of @angular/forms@^4.0.3 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of rxjs@^5.0.0 but none was installed.
npm WARN angular2-schema-form@1.0.0-alpha.32 requires a peer of zone.js@^0.6.25 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/compiler@~2.2.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.
npm WARN sass-loader@6.0.5 requires a peer of node-sass@^4.0.0 but none was installed.
npm WARN @angular/common@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/forms@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN ng2-tag-input@0.8.4 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN CARE-UI@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 (node_modules/node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 install: node-pre-gyp install --fallback-to-build
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
[user@AMHI-DEV-WEBAPP UICare]$

sudo npm run build:dev

CARE-UI@1.0.0 prebuild:dev /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare
npm run clean:dev
CARE-UI@1.0.0 clean:dev /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare
npm run rimraf -- dev
CARE-UI@1.0.0 rimraf /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare
rimraf "dev"
CARE-UI@1.0.0 build:dev /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare
npm run webpack -- --config config/webpack.dev.js
CARE-UI@1.0.0 webpack /var/lib/jenkins/jobs/UIFrontEnd/workspace/UICare
webpack --progress --profile --bail "--config" "config/webpack.dev.js"
10% building modules 1/3 modules 2 active .../workspace/UICare/src/main.browser.ts(node:23738) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see webpack/loader-utils#56
parseQuery() will be replaced with getOptions() in th 55% building modules 847/1113 modules 266 active ...leonPicture/bsKameleonPicture.pipe.ts

**Comment by lordKnighton** [comment]
@imharishsundar did you solve this yet?

**Comment by robertpearce** [comment]
just ran into this myself on centos 7 and node 7.10.0 when installing adapt-cli package from npm

**Comment by lordKnighton** [comment]
@robertpearce is your build struck or stuck ? is that a typo.

**Comment by JamesBond** [comment]
I ran into this this morning after updating npm.  The fix, that I found from StackOverflow is described here:
[https://github.com/nodejs/node-gyp/issues/454](https://github.com/nodejs/node-gyp/issues/454) and basically boils down to adding "--unsafe-perm" when doing npm install:
`npm install --unsafe-perm --verbose -g @angular/cli`

**Comment by gireeshpunathil** [comment]
closing as answered and resolved, please re-open if that is not the case.
