### ISSUE TITLE
Node.js & npm no such file or directory error

### ISSUE THREAD

**Issue by erbanach** [nodejs/help#621]
I did a fresh install of Angular CLI, Node.js, and npm.

Output from: ng --version: No such file or directory
Output from: node --version: v7.10.0
Output from: npm --version: 4.2.0
macOS Sierra 10.12.4

After running `ng new app` on a fresh install of Node.js and npm I am getting the error message:

`bash: /Users/Liz/.npm-packages/lib/node_modules/@angular/cli/bin/ng: No such file or directory
`

I wanted to check and see if those directories existed:

```
$ cd /Users/Liz/.npm-packages/lib/node_modules/@angular/cli/bin
-bash: cd: /Users/Liz/.npm-packages/lib/node_modules/@angular/cli/bin: No such file or directory
$ cd /Users/Liz/.npm-packages
-bash: cd: /Users/Liz/.npm-packages: No such file or directory
```

It seems like npm & Node.js did not get installed correctly if those directories don't exist? How can I fix this?

**Comment by gibfahn** [comment]
@erbanach how did you install Node?

It sounds like your Angular CLI install didn't work properly. Did you install it with:

```bash
npm install -g @angular/cli
```

?

If so can you run it again and paste the output? When I run that (and then a `which ng`) I get this:

```bash
➜  ~ ❯ npm i -g @angular/cli                                                                                                                                                                                                                                               
/Users/gib/.local/share/nvm/versions/node/v7.10.0/bin/ng -> /Users/gib/.local/share/nvm/versions/node/v7.10.0/lib/node_modules/@angular/cli/bin/ng
/Users/gib/.local/share/nvm/versions/node/v7.10.0/lib
└── @angular/cli@1.0.3 

➜  ~ ❯ which ng                                                                                                                                                                                                                                                            
/Users/gib/.local/share/nvm/versions/node/v7.10.0/bin/ng
```

**Comment by lordKnighton** [comment]
@erbanach you found your solution yet?
