### ISSUE TITLE
node-gyp Unresolved External Symbol Error

### ISSUE THREAD

**Issue by Pecacheu** [nodejs/help#623]
Opened this on https://github.com/nodejs/node-gyp/issues/1194 originally, but moved here.
### Original Comment:
> I'm trying to make a native module that uses DirectX for some of it's functionality, but I get this error when I try to node-gyp build:
> 
> main.obj : error LNK2001: unresolved external symbol Direct3DCreate9
> I'm including d3d9.h in my c++ file. Is there something I'm doing wrong?

### Second comment:

Okay,
**a.** I don't know where D3D9.lib is, although I finally found D3D9.dll in Windows/System32, but more importantly...
**b.** How on earth do you include them in node-gyp. I can't find any documentation. Whenever I google for node-gyp help, I only get unofficial tutorials, and there doesn't seem to be any written on this topic.

I know how to include Windows dll's and lib's in Visual Studio. Basically just open the right menu (which is a bit hard to find, but whatever) and select the ones you want. Obviously it doesn't work like that with node-gyp, so I'm stuck.

EDIT: I just read through the node-gyp Wiki. I feel like this _almost_ explains it, but I still can't get it to work:
https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL

**Comment by refack** [comment]
1. IMHO if you're trying to develop something with DirectX install the [DirectX SDK](https://www.microsoft.com/en-us/download/details.aspx?id=6812) it has the static `d3d9.lib` file. If you feel comfortable with DirectX skip it.
2. `GYP` has a (not amazing but Ok) guide where it is explained how to [add library dependencies](https://gyp.gsrc.io/docs/InputFormatReference.md#Merging) (altough it's a section about merging, in the example they show how to set `link_settings`)
3. Look as examples like [`lzma_native`](https://github.com/addaleax/lzma-native/blob/master/binding.gyp#L22) or [`node-bigint`](https://github.com/substack/node-bigint/blob/master/binding.gyp)

**Comment by refack** [comment]
P.S. If you are only developing for your own use (not a distributable module), you can just run `node-gyp configure` that will create a `build` directory with regular Visual Studio files in it. You can open the `binding.sln`, edit the projects, add libraries and build. It should work (the end result is a file with `.none` extension in `build\Release`)

**Comment by Pecacheu** [comment]
I got it working after downloading the DirectX SDK, copying the .lib out of that, and using the node-bigint `binding.gyp` as an example. Thanks!

BTW, I'm making a library that captures the screen (that's what I just got working), captures system audio output (which should be working, but the audio data is corrupted somehow), and controls the mouse cursor.

I was using a combination of Electron and RobotJS before, but Electron doesn't work with a lot of other node modules that I need, and RobotJS is VERY broken on Windows with multiple monitors. Multiple monitor support is defiantly a necessity for the project.

**Comment by refack** [comment]
@Pecacheu If you have the possibility/opportunity, send a link, I'd enjoy checking that out...

**Comment by Pecacheu** [comment]
Sure, but I have to do the documentation for it first. I'm also waiting on an issue for libde265, 'cause I also need an H.265 or H.264 decompression library for my project. I can use the ffmpeg-stream module for compression on node side, but decompression happens on a device with an ARM processor.

**Comment by 3lwan** [comment]
Hi, can you send me a link to that because I am trying to link DirectX with electron but I am having problems with it and can not find examples of electron and DirectX.
