### ISSUE TITLE
Consume Node.js Debugger Protocol without Chrome

### ISSUE THREAD

**Issue by mtangoo** [nodejs/help#624]
I was taking a look at debugging Node.js and it seems the old protocol is deprecated in favor of the newer one. Unfortunately, all examples on new protocol uses Chrome/Chrome-Devtools and I don't want to use Chrome. I plan to develop my own debugger front end.

I will appreciate anyone point me to the right direction on this. Simple example will or documentation with example will be great!

NB this is my first issue here so may I be forgiven if I have not complied with any of the norms here.

**Comment by bnoordhuis** [comment]
Alternative open source implementations exist, such as node-inspect and the VS Code debugger.

The protocol is JSON-over-websockets, you can find its definition [here](https://github.com/nodejs/node/blob/master/deps/v8/src/inspector/js_protocol.json).  A bare-bones client exists in the test suite [here](https://github.com/nodejs/node/blob/master/test/inspector/inspector-helper.js).

**Comment by eugeneo** [comment]
@mtangoo connecting to inspector is trivial if you can import a WebSockets module from the NPM - you can use https://github.com/eugeneo/node-restarter/blob/master/restarter.js as an example.

**Comment by joshgav** [comment]
[node-inspect][] is a project to learn from if you're building your own tool. There's also a bit more background in [the Getting Started doc](https://nodejs.org/en/docs/guides/debugging-getting-started/).

[node-inspect]: https://github.com/nodejs/node-inspect

**Comment by mtangoo** [comment]
Thank you buddies for great advices. I will go thru links provided.
Can you also suggest if that will work fine with C++? I have editor already that I want to integrate debugging (reason for avoiding already working devtools)

Thanks for great help

**Comment by eugeneo** [comment]
All you need is an ability to send/receive messages over the WebSocket protocol. There should be C++ libraries for that.

**Comment by mtangoo** [comment]
Thanks a lot. 
I will close this ticket since I have got starting point
