### ISSUE TITLE
Want to run nodejs on dedicated server

### ISSUE THREAD

**Issue by bswscube** [nodejs/help#625]
Hello there,

I want to run nodejs on dedicated server. Can you please guide me for that.

**Comment by vdeturckheim** [comment]
Hey, without more details, it will be hard to give you a proper help.

Hopefully you might find what you need here: https://www.digitalocean.com/community/tags/node-js?type=tutorials

**Comment by gibfahn** [comment]
>I want to run nodejs on dedicated server. Can you please guide me for that.

Do you need help finding a server or installing Node on it?

**Comment by bswscube** [comment]
I have a dedicated server. Now i want to run nodejs on dedicated server.

**Comment by refack** [comment]
as @vdeturckheim said some background information would be helpful for us.
A good start is: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04
A few notes:
* `PM2` is just one option for process manager, on ubuntu-16-04 you could use `systemd`
* The same with setting `nginx` as reverse proxy, it's not mandatory, depends on what between your server and your clients, and who are your clients.

P.S. Unless you __must__ run on a dedicated server, I would warmly recommend a PaaS provider like Heroku / Azure / Google Cloud / AWS Lambda

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if you have unanswered part of your query.
