### ISSUE TITLE
NodeJS error message - UNABLE_TO_GET_ISSUER_CERT_LOCALLY - attempting LDAPS connection

### ISSUE THREAD

**Issue by achawla5000** [nodejs/help#626]
* **Node.js Version**:  7.3
* **OS**:  Windows 7 Enterprise
* **Scope (install, code, runtime, meta, other?)**:  code
* **Module (and version) (if relevant)**:  https://github.com/mcavage/node-ldapjs

Would someone be able to assist with this?
https://stackoverflow.com/questions/43849377/nodejs-error-message-unable-to-get-issuer-cert-locally-attempting-ldaps-conn

Thank you

**Comment by shellberg** [comment]
OK, you got me to bite!  Looks like a certificate - not code - issue to me.

**Comment by lordKnighton** [comment]
Gonna close issue, If you still in need of help, reopen & ping me.
