### ISSUE TITLE
i don't know how to install using node.js

### ISSUE THREAD

**Issue by KoolKidz112** [nodejs/help#627]
- Node.js Version: v7.10.0
- OS: Windows
- Scope (install, code, runtime, meta, other?):install

so im doing a github install thing i did it correctly but now i dont know what to do next and how to install the files.
`npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Truth Media Justin\package.json'
npm WARN Truth Media Justin No description
npm WARN Truth Media Justin No repository field.
npm WARN Truth Media Justin No README data
npm WARN Truth Media Justin No license field.`

**Comment by chungngoops** [comment]
There is no package.json at 'C:\Users\Truth Media Justin\
You should initialize package by running:
`npm init`

**Comment by gibfahn** [comment]
>so im doing a github install thing i did it correctly but now i dont know what to do next and how to install the files.

What package are you trying to install from github? 

I'm not entirely sure what process you're following, but in general the steps to install a module you've cloned from Github are:

```bash
git clone https://github.com/expressjs/express.git # Using express as an example
cd express # Or whatever the name of the module was
npm install # Only works if there's a file called package.json in the current directory
```

Alternatively if you just want to install a module directly from npm you can do:

```bash
npm install express # Or whatever the module name is
```

This usually installs the module into a `node_modules/` subdirectory.

For more info see the [`npm install` docs](https://docs.npmjs.com/cli/install) docs.

**Comment by lordKnighton** [comment]
Gonna close for now. If you guys wish to continue, reopen & take flight

**Comment by KoolKidz112** [comment]
> Gonna close for now. If you guys wish to continue, reopen & take flight

thanks for the help

**Comment by KoolKidz112** [comment]
```
Your environment has been set up for using Node.js 8.4.0 (x64) and npm.

C:\Users\Truth Media Justin>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "Truth Media Justin": Tags may not have any characters that encodeURIComponent encodes.
About to write to C:\Users\Truth Media Justin\package.json:

{
  "name": "",
  "version": ""
}


Is this ok? (yes) yes
npm ERR! Callback called more than once.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Truth Media Justin\AppData\Roaming\npm-cache\_logs\2017-08-19T21_34_13_642Z-debug.log
```

is that a good sign

**Comment by KoolKidz112** [comment]
this too?

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Truth Media Justin No description
npm WARN Truth Media Justin No repository field.
npm WARN Truth Media Justin No license field.

+ express@4.15.4
added 42 packages and removed 2 packages in 11.305s
```
sorry if u dont want me to post while this is closed

**Comment by KoolKidz112** [comment]
and by the way its version 8.4.0 now cus the cp had to reset

**Comment by gibfahn** [comment]
@KoolKidz112 commenting while closed is fine.

The reason you're getting this error is because you have a space in the directory you're running in.

See https://github.com/npm/validate-npm-package-name#naming-rules for more info.

Try creating a directory with the name of the npm package you want to initialise first, e.g.

```bat
mkdir my-first-package
cd my-first-package
npm init
```

and it should work

**Comment by KoolKidz112** [comment]
```
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
```

**Comment by KoolKidz112** [comment]
ok i created it and i was pretty lazy and confused:

```
package name: (my-first-package) testpackageorwhatever
version: (1.0.0) 0.0.1
description: simple package im using to download
entry point: (index.js) index.js
test command: test
git repository: test package/whatever
keywords: test, github, npm, node.js
author: KoolKidz112
license: (ISC) MIT
```

**Comment by gibfahn** [comment]
Don't worry too much about `npm init`, it just creates fields in the `package.json`, you can always edit it later.

I'll close, let us know if you have more issues.

**Comment by KoolKidz112** [comment]
fixed now you can close it
