### ISSUE TITLE
fs.createReadStream

### ISSUE THREAD

**Issue by joastonish** [nodejs/help#628]
mem leak when req is busy or be closed in traning stream

* **Node.js Version**:7.7.0
* **OS**:linux
* **Scope (install, code, runtime, meta, other?)**:code
* **Module (and version) (if relevant)**:

**Comment by addaleax** [comment]
Can you give any more information? How did you diagnose that there is a memory leak? Can you share any code to reproduce it? Does the problem occur with the latest v7.x version (v7.10.0)?

**Comment by joastonish** [comment]
html:
<!DOCTYPE html>
<html lang="en">
<head></head>
<body>
 <video id="video"
               width="600" height="360"
               preload="none" controls="controls"
                autoplay="autoplay"
src="192.168.1.6:1103/Play?filename=1.mp4"
        >
        </video>
    </body>
</html>


server:
var ipAddr = "192.168.1.6";
var serverPort = 1103;
var cmsUrl = "http://192.168.1.4:2223/getFile?";
var tempList = [];
var seq = 0;
var appFile = http.createServer(function (req, res) {

    var urlObj = url.parse(req.url);
    var pathIndex = urlObj.pathname.substring(1).split('/');
    try {
        switch (pathIndex[0]) {
            case 'Play':
                var range = '0-';
                if (req.headers.range.indexOf("=") != -1) {
                    var pos = req.headers.range.indexOf("=");
                    range = req.headers.range.substr(6, req.headers.range.length)
                }
                var queryData = queryString.parse(urlObj.query);
                var nvrPlayUrlGet = cmsUrl + filename=" + queryData.filename+ "&ip=" + ipAddr + "&port=" + serverPort + "&token=" + seq + "&range=" + range;
                tempList[seq] = res;
                seq++;

                var playurlreq = http.get(nvrPlayUrlGet, function (getPlayRes) {
                });
                break;
            case 'Doreq':
                var reqIndex = parseInt(pathIndex[1]);
                req.on('end', function () {
                    console.log("end",reqIndex);
                    res.end();
                });
                if (tempList[reqIndex]) {
                    tempList[reqIndex].setHeader("Content-Type", 'video/mp4');
                    tempList[reqIndex].setHeader("Content-Range", "bytes " + parseInt(pathIndex[2]) + "-" + parseInt(pathIndex[3]) + "/" + parseInt(pathIndex[4]));
                    tempList[reqIndex].writeHead('206', "Partial Content");
                    req.pipe(tempList[reqIndex]);
                }
                else{
                    console.log("error no res");
                }
                break;
        }
    }
    catch (e){
        console.log(e);
    }
}).on('error',function(e){
    console.log(e);
});
appFile.listen(serverPort);
console.log('Listening on localhost:1103');


LocalFile
var host = ip;//server 
var port = port;//server
 var stats = fs.statSync(filename);

        //this.dianboLock.PutExcFunc(function(putBackKey){
            var rdetails = parseRange(range, stats.size);//get file range
            if (rdetails) {
                var post_options = {
                    host: host,
                    port: port,
                    path: '/Doreq/' + token + "/" + rdetails.start + "/" + rdetails.end + "/" + stats.size,
                    method: 'POST'

                };
                post_options.header = { 'Content-Type': 'video/mp4',
                    Connection: 'keep-alive',
                    'transfer-encoding': 'chunked' }
                var req = http.request(post_options, function (res) {
                });
                var stream =  fs.createReadStream(fileInfo, {
                    "start": rdetails.start,
                    "end": rdetails.end,
                    autoClose: true
                });
                stream.pipe(req);
                stream.on('end',function(){
                    logger.debug('dianbo end');
                    if(stream) {
                        logger.debug('done dianbo end');
                        stream.unpipe(req);
                        stream.removeAllListeners();
                        stream = null;
                    }
              
                });
                stream.on('close',function(){
                    logger.debug('dianbo stream destroy');
                    stream = null;
                });
                req.on('error', function (err) {
                    logger.debug('dianbo end with err',err);
                    if(stream) {
                        logger.debug('dianbo end with err close stream');
                        stream.unpipe(req);
                        stream.destroy();
                    }
                    if(req) {
                        req.end();
                        req.destroy();
                        req = null;
                    }
                });
            }
            else
                logger.error("range error");


os:linux
mem:up up up up if i Play multiple files

**Comment by bnoordhuis** [comment]
Fixed formatting.  GitHub seems to get confused by the long lines, though.  Your memory leak is probably this:
```js
                var playurlreq = http.get(nvrPlayUrlGet, function (getPlayRes) {
                });
```
You create a request but you don't do anything with the response object.  The other file does the same thing:
```js
                var req = http.request(post_options, function (res) {
                });
```

**Comment by joastonish** [comment]
that means ,if i add res.end() ,it will work?

**Comment by joastonish** [comment]
no work，still mem leak

**Comment by bnoordhuis** [comment]
Next step: use the built-in inspector or a third-party module like heapdump to take heap snapshots and see where the memory goes.
