### ISSUE TITLE
node js arm 7 cross compile

### ISSUE THREAD

**Issue by rebecca-eujin** [nodejs/help#629]
* **Node.js Version**: node-v0.12.0-linux-arm-pi
* **OS**:windows 7
* **Scope (install, code, runtime, meta, other?)**:  install(?)/use
* **Module (and version) (if relevant)**: arm7

Im having issues using files that have been provided by Node js for arm7 (android).
Currently, Im trying to run node js files in arm7.
However, Im not sure how should I use the files that have been provided.
I have tried putting files in /system/bin and command node by running node file in node-v0.12.0-linux-arm-pi/bin.
However, it provides error by the node file does not exist.
How should I solve this problem?

**Comment by gibfahn** [comment]
>OS:windows 7

I assume you're running Raspbian not Windows 7 right?

Which file did you put in `/system/bin`?

Assuming you're using the terminal, you can navigate to `node-v0.12.0-linux-arm-pi/bin` and do:

```bash
ls                # Should show node npm
./node            # Runs node
```

**Comment by rebecca-eujin** [comment]
yes I did the same way however it provides error by file does not exist

**Comment by gibfahn** [comment]
What is the output of the `ls` command?

**Comment by rebecca-eujin** [comment]
node npm

**Comment by gibfahn** [comment]
What about `ls -l`?

**Comment by gibfahn** [comment]
# Short answer:

To install manually do:

```bash
wget https://nodejs.org/dist/v6.10.3/node-v6.10.3-linux-x64.tar.gz
tar -xf node-v6.10.3-linux-x64.tar.gz --directory /usr/local --strip-components 1
```

This will put the `./bin` directory in `/usr/local/bin`, which should be in your `$PATH` already. You can verify that it worked with:

```bash
node --version
npm --version
```

# Alternatives:

If you want to use a package manager, see [this guide](https://nodejs.org/en/download/package-manager/). For older Linux distros you might need to see [these instructions](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md).

If you want to install node manually, there is no "installation" on Linux per se, you just need to extract the tarball, and make sure the `node` and `npm` binaries in the `./bin` subdirectory are somewhere in your path.

I find [nvm](https://github.com/creationix/nvm#install-script) is useful for managing node installations (it will download, extract, and add to path for you). If you want to do things manually, you can do something like:

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if this is still outstanding.
