### ISSUE TITLE
安装 express 出现问题

### ISSUE THREAD

**Issue by vswen** [nodejs/help#63]
![6c4 kw6g4 9k x 95j5ieo](https://cloud.githubusercontent.com/assets/16498070/12062200/c2ea0e4e-afd2-11e5-9d91-59042a282f69.jpg)
![2l i n vh8b14h_q lk d](https://cloud.githubusercontent.com/assets/16498070/12062205/cc4e05e4-afd2-11e5-8867-86757a8f8066.jpg)

**Comment by kkc** [comment]
Did you try china mirror npm registry? 
http://npm.taobao.org/

**Comment by kelthenoble** [comment]
我同意 @kkc 考试 link.如不帮助, 请尝试以下 https://cnodejs.org/topic/5624d434ef99b0d40acb2c4b & https://cnodejs.org/topic/5346407fcb6fd9d06c029643 :+1:

**Comment by kelthenoble** [comment]
closing for now, Hope this helped. thanks @kkc :100:

**Comment by vswen** [comment]
Do not know how, I give up, ha ha!

**Comment by kelthenoble** [comment]
we'll were here if you need us. 
:+1:
