### ISSUE TITLE
Want to auto refresh nodejs api without page refreshing

### ISSUE THREAD

**Issue by bswscube** [nodejs/help#630]
Hello 

I want to create auto refresh nodejs api. If any changes occur in database's data then it will be shown in nodejs api without page refreshing.

**Comment by gibfahn** [comment]
Not completely sure what you're asking for, but AJAX might be the answer.

https://www.w3schools.com/xml/ajax_intro.asp

>AJAX is a developer's dream, because you can:
>- Update a web page without reloading the page
>- Request data from a server - after the page has loaded
>- Receive data from a server - after the page has loaded
>- Send data to a server - in the background

**Comment by bswscube** [comment]
there is an in build function nodejs for auto refresh. I don't want to use AJAX

**Comment by SomeoneWeird** [comment]
NodeJS doesn't have anything to do with your frontend or web browser. You still need to handle all of that using client-side javascript

**Comment by refack** [comment]
@bswscube a good place to start is https://socket.io/

But what @gibfahn & @SomeoneWeird said is true. `node` is only on the server side, what happens in the browser is up to you.

**Comment by ORESoftware** [comment]
I think you might need to use websockets - when db changes, send a message to the server to pull in the new data from the DB..this has nothing to do with the front-end

**Comment by bswscube** [comment]
Okay Thank you all.

1. Basically I am develop a API using nodejs. I am using pool connection method but server block my API for too many connections with MySql. Can you please help me out for that.

2. I want to run nodejs always on dedicated server so i am using pool connection concept but its fail on this API. 

3. How can use socket concept for connection when databases's data change. Please give me example.

**Comment by refack** [comment]
1. Cache your reads with something like `redis` with [`radis.js`](http://redis.js.org/)
2. If you use a connection pool correctly it should fail for the client.
3. Checkout the `socket.io` tutorial, it's really good https://socket.io/get-started/chat/

**Comment by bswscube** [comment]
Hello 
I am using simple below code for Socket.io.

// For App.js
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);
app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});
io.on('connection', function(socket){
  console.log('a user connected');
});
http.listen(3000, function(){
  console.log('listening on *:3000');
});

// index.html
<script src="/socket.io/socket.io.js"></script>
<script>
  var socket = io();
</script>

Every time when i reload the page then it give me "a user connected" in console.
I want to do it without page refreshing.

**Comment by refack** [comment]
> Every time when i reload the page then it give me "a user connected" in console.
> I want to do it without page refreshing.

Think about it... that is ok. _If_ the user refreshes, the browser clears the current state and reconnects, but you can _push_ new information to the user _without_ the user needing to refresh.
If you want to stop the user from refreshing you can use [`onbeforeunload`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload), to tell the user there is no need to refresh.

**Comment by bswscube** [comment]
Can you please give me example of this

**Comment by taruntadikonda** [comment]
how to live stream data from a mongodb which get updated frequently without refreshing the page.

`app.post('/databykey',function(req,res){
  var api=req.body.api;
  console.log(api);
  push.getdata(api,function(err,data){
    if(err)
    {
      console.log(err);
    }
    else
    {
      var sample=[];
      for(i=0;i<data.length;i++){
        sample[i]=data[i].id
      }
      console.log(sample);
      res.render('data',{'data':sample});
    }
  })
  
})`

this i my source code.I am fetching the data from the mongodb which get updated frequently.How do i render the updated data to the front end without refreshing the browser

**Comment by ORESoftware** [comment]
@taruntadikonda  you would use websockets to send the data from the server to the browser.

to listen to mongodb changes, you will want to use ChangeStreams, which are available from MongoDB version 3.6 on:

https://pusher.com/tutorials/mongodb-change-streams

https://docs.mongodb.com/manual/changeStreams/

https://medium.com/@thakkaryash94/mongodb-3-6-change-streams-example-with-node-js-2b9a85652c50
