### ISSUE TITLE
Code Protection?

### ISSUE THREAD

**Issue by harshalyeole-tudip** [nodejs/help#631]
Hi Everyone,
I need your help in protecting my code.
Actually, I need to deploy the code on a server but don't want anyone to read it but still, it should execute.

Is there any method to protect code like AngularJS makes deployable dist file.

Any help would be appreciated.
Thank you!

**Comment by refack** [comment]
At the moment this feature is still being debated nodejs/node#11903
But there are 3rd party modules that do this: https://github.com/nodejs/help/issues/576#issuecomment-294625826

**Comment by vsemozhetbyt** [comment]
You can also try https://github.com/zeit/pkg, but I don't know how easy this can be decompiled.

**Comment by harshalyeole-tudip** [comment]
@vsemozhetbyt 
Not able to configure with my app.

**Comment by harshalyeole-tudip** [comment]
@refack 
Didn't help out!
As I need to build the whole project and this is for only node modules I guess.

**Comment by refack** [comment]
@harshalyeole-tudip what about https://github.com/nexe/nexe

**Comment by refack** [comment]
@harshalyeole-tudip there is also [`docker`](https://www.docker.com/what-docker) and [`docker build`](https://docs.docker.com/engine/reference/commandline/build/)

**Comment by claudiorodriguez** [comment]
Be aware that any of these efforts will be based on eventual obfuscation of the source - you'll be making it harder to reverse-engineer, but not impossible. Someone dedicated enough will always be able to get a form of source-code; not a good one, but enough that you shouldn't put anything sensitive in it like secret tokens you don't want divulged and whatnot.
