### ISSUE TITLE
How the **** do I install it?

### ISSUE THREAD

**Issue by GazbonicAcid** [nodejs/help#632]
* **Node.js Version**:
v7.10.0
* **OS**:
Lubuntu 16.10 64 bit Yakkety
* **Scope (install, code, runtime, meta, other?)**:
Install

How the living _**swearing**_ do I **_more swearing_** install it from the .tar.xz archive?
There is no **_even more swearing_** info on how to install it.
And there are no intuitive files to run for installing it.

**Comment by GazbonicAcid** [comment]
Installing from the install script works.
Just absolutely no _**swearing**_ information on how to install from the archive.

**Comment by refack** [comment]
Well it just works...
The deb package referred to in https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions just extracts the archive

**Comment by gibfahn** [comment]
If you want to use a package manager, see [this guide](https://nodejs.org/en/download/package-manager/). For older Linux distros you might need to see [these instructions](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md).

If you want to install node manually, there is no "installation" on Linux per se, you just need to extract the tarball, and make sure the `node` and `npm` binaries in the `./bin` subdirectory are somewhere in your path.

I find [nvm](https://github.com/creationix/nvm#install-script) is useful for managing node installations (it will download, extract, and add to path for you). If you want to do things manually, you can do something like:

```bash
wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz
tar -xf node-v6.9.2-linux-x64.tar.gz --directory /usr/local --strip-components 1
```

This will put the `./bin` directory in `/usr/local/bin`, which should be in your `$PATH` already. You can verify that it worked with:

```bash
node --version
npm --version
```

**Comment by refack** [comment]
What @gibfahn said!

**Comment by lordKnighton** [comment]
Hey Gaz do you still need help with this, or do you have gist of it/ already got it working? 
@GazbonicAcid

**Comment by GazbonicAcid** [comment]
Already got it working. The issue stemmed from the big intuitive "click this to download and install it" gives just the base archive but without info on how to properly install it. Or at least without an intuitive path to get to said info.

**Comment by lordKnighton** [comment]
I'm gonna close this issue now, because we don't get this issue a lot, so it seems like an isolated issue. 
But if you wish to pursue and make sure it doesn't happen again. I ask you to post a photo along with a detailed paragraph explaining how you ran into this issue. 

Happy coding 👍
