### ISSUE TITLE
Mac Version in Index of /download/release/v6.9.1/ ?

### ISSUE THREAD

**Issue by andrewjholdun** [nodejs/help#635]
v6.9.1 Node.js Version
Mac OS

Hi I am trying to run Node.js but for google cloud need v6.9.1 and am on mac. 

(Andrews-MBP:apiai-facts-about-google-nodejs-master ajh$ functions start
Warning: You're using Node.js v6.10.3 but Google Cloud Functions only supports v6.9.1.
/bin/sh: gcloud: command not foundI looked at downloads )

I  looked here: 

https://nodejs.org/download/release/v6.9.1/

but am not clear which of these is the correct one to download.

Can someone help please?

Thanks so much!

Andrew

**Comment by bnoordhuis** [comment]
https://nodejs.org/download/release/v6.9.1/node-v6.9.1.pkg is probably the one you want, that's the installer.  That said, it seems like it's only warning you about the version number, the actual error is that the gcloud command is missing.  Not on your shell path, perhaps?

**Comment by andrewjholdun** [comment]
I totally missed that. Thank. I am trying to set up Google Assistant and following this:
https://developers.google.com/actions/get-started/deploy-fulfillment.
Nothing was mentioned about the version of Node.js needed so I assumed stable latest was ok.

**Comment by jdkasldjlasjljdkajklasjkdjaks** [comment]
ping @nodejs/automation @nodejs/members @nodejs/collabarators @joyeecheung @bnoordhuis @addaleax @snostorm @bnoordhuis @hashseed @jasnell @apapirovski @targos @mikeal @indexzero @sam-github @ChALkeR @cjihrig @Fishrock123

**Comment by jdkasldjlasjljdkajklasjkdjaks** [comment]
ping @nodejs/automation @nodejs/members @nodejs/collabarators @joyeecheung @bnoordhuis @addaleax @snostorm @bnoordhuis @hashseed @jasnell @apapirovski @targos @mikeal @indexzero @sam-github @ChALkeR @cjihrig @Fishrock123 @refack

**Comment by tniessen** [comment]
I am going to close this issue assuming it has been resolved, please add a comment or reopen this issue if the problem persists.
