### ISSUE TITLE
6.0.0-rc.0 release does not include source tarball

### ISSUE THREAD

**Issue by jasonkarns** [nodejs/help#636]
* **Node.js Version**: 6.0.0-rc.0
* **OS**: n/a
* **Scope (install, code, runtime, meta, other?)**: meta/download
* **Module (and version) (if relevant)**: n/a

The 6.0.0-rc.0 release includes binaries for some relevant platforms, but the source tarball itself is not included in that RC manifest: https://nodejs.org/download/rc/v6.0.0-rc.0/

Was that intentional? Is there a process for adding the source tarball to that "release"?

I'm one of the maintainers of nodenv and node-build. I've recently updated our scraper to create build-definitions for nodejs Release Candidates. It was during that process that I discovered this issue. I suspect this is an issue for other tools that pull from nodejs.org's dist/ and download/rc/ listings.

**Comment by refack** [comment]
Ref: nodejs/node#6155
ping @jasnell

**Comment by jasonkarns** [comment]
Is there a chance we can get the source tarball added for this release from the related git tag?

**Comment by gireeshpunathil** [comment]
@jasonkarns - is this still an issue for you? please let me know.

**Comment by jasonkarns** [comment]
It's not a _huge_ issue. But without the source tarball, nodenv and node-build are unable to add support for `6.0.0-rc.0` along with all the other node releases. I doubt many people are clamoring to install 6.0.0-rc.0 specifically. But yes, it's still an issue.

**Comment by gireeshpunathil** [comment]
/cc @nodejs/release again. I ran a script and found that there are at lest 3 releases for which source is missing:

```link
https://nodejs.org/download/rc/v6.0.0-rc.0/
https://nodejs.org/download/rc/v6.11.0-rc.0/
https://nodejs.org/download/rc/v6.12.1-rc.2/
```
and a couple for which the `.pkg` version of is not available. Is there anything we can do about it?

**Comment by jasonkarns** [comment]
https://nodejs.org/download/rc/v8.7.0-rc.1/ is also missing source.

**Comment by lordKnighton** [comment]
closing this issue, if you still need more help reopen it & we will pick it from there, thanks.

**Comment by jasonkarns** [comment]
@lordKnighton this is still an issue. All the versions listed in the comments here are still lacking source tarballs:

- https://nodejs.org/download/rc/v6.0.0-rc.0/
- https://nodejs.org/download/rc/v6.11.0-rc.0/
- https://nodejs.org/download/rc/v6.12.1-rc.2/
- https://nodejs.org/download/rc/v8.7.0-rc.1/

**Comment by lordKnighton** [comment]
@jasonkarns hey jason, I just notified the nodejs/release team to this issue. So hopefully soon they will take a look into this for you, until then you are more than welcome to make a PR for the issue, thanks.

**Comment by Trott** [comment]
I think the person that handled the rc releases was @jasnell so he might be able to explain why there's no source tarball for those releases or point you to where the source tarballs are.

**Comment by gireeshpunathil** [comment]
@jasonkarns  - it has been 2 years so I think it is not going to be resolved in this repo. Is this still an issue for you? v6 is out of support, but are recent versions also getting missed out? If so let me know, so that we can raise an issue in the release repo for their action / awareness and close it here.

**Comment by jasonkarns** [comment]
technically, yes it's still an issue. the scripts that nodenv uses to generate build definitions for nodenv/node-build don't have version exceptions, or care about the maintenance status of particular versions. they scrape the releases index and then either fail or generate an invalid build definition, due to the lack of source package.

**Comment by jasonkarns** [comment]
closing re: https://github.com/nodejs/build/issues/2053#issuecomment-556055738
