### ISSUE TITLE
Bower offline package in NPM?

### ISSUE THREAD

**Issue by acropolis22** [nodejs/help#637]
Is there a package similar to offline in bower within NPM? currently switching the dependencies from bower to npm, but the offline package doesn't exist.

**Comment by addaleax** [comment]
If you follow the link that bower provides for `offline`, you’ll see https://github.com/HubSpot/offline which has a `package.json` file; if you look at that, you’ll see that the npm package is called [offline-js](https://www.npmjs.com/package/offline-js), not offline, that’s all. :)

**Comment by acropolis22** [comment]
Thanks so much!
