### ISSUE TITLE
Cant Install Node Js

### ISSUE THREAD

**Issue by MEasSYNCHRO** [nodejs/help#638]
I Get the following error when i try to install node js to my windows

"""
Could not open the installation package .Verify with the vendor that its a valid installation package

"""

**Comment by vsemozhetbyt** [comment]
See https://github.com/nodejs/node/issues/10195. Maybe the cause is the same (the package is broken due to download issue).

**Comment by muyoucun557** [comment]
mdzz

**Comment by lordKnighton** [comment]
@MEasSYNCHRO you still need help with this issue? Or have you got it working?
