### ISSUE TITLE
Security using precompiled binary from nodejs.org

### ISSUE THREAD

**Issue by endemic** [nodejs/help#64]
I have a 0.10.x Node app running on CentOS 6, and I'd like to upgrade the runtime to 4.2.x. Unfortunately, NodeSource doesn't provide packages for 4.2 on CentOS 6, but I see that I can download a precompiled binary straight from nodejs.org. As per https://nodejs.org/en/security/, I see that those builds are updated whenever a security vulnerability is disclosed, which is awesome. My question is, would the precompiled binary dynamically link against any of the (older) CentOS 6 libraries? Or is it totally self-contained?

**Comment by kelthenoble** [comment]
check out these links to see if they help :+1:  https://github.com/nodesource/distributions/issues/128 
& https://github.com/nodesource/distributions 
![screen shot 2015-12-31 at 4 22 20 pm](https://cloud.githubusercontent.com/assets/1773260/12069262/aa649436-afda-11e5-8d7e-cb6403110b70.png)

**Comment by rvagg** [comment]
The binaries for Linux on nodejs.org should be good to use on CentOS 5 and above as they are. Just unpack and run.

**Comment by kelthenoble** [comment]
:smile: :+1: @rvagg

**Comment by endemic** [comment]
Thanks for the replies, I want to use the pre-compiled binary from nodejs.org, but my question is whether or not those binaries are self-contained, or depend on other system libraries. The 4.2 binary runs my app perfectly 👍

**Comment by kelthenoble** [comment]
Great to hear it. :100:
