### ISSUE TITLE
cannot find node or npm after install of nodejs

### ISSUE THREAD

**Issue by Bazmundi** [nodejs/help#641]
* **Node.js Version**: any
* **OS**: Armbian
* **Scope (install, code, runtime, meta, other?)**: installation
* **Module (and version) (if relevant)**: node, npm

The instructions on many web pages intimate that if I install nodejs I then get node and npm from the command line.  [For example](https://diyprojects.io/install-node-red-orange-pi-running-armbian/#.WSv5e2iGOUk).  

This same set of steps is replicated many places.  However, when I get to the step to check the node and npm versions the shell reports it cannot find either.  I note there are no errors reported during installation.

I poked around and found /user/bin/nodejs which appears to node??  That is if I run: nodejs -v from command line I get the version I installed.

I seem to have the same problem on either the ubuntu or the debian version of armbian and  I have tried version 4.x and 7.x of nodejs to get the same effect.

Any ideas please?
Cheers
B

**Comment by gibfahn** [comment]
From the [package manager docs](https://nodejs.org/en/download/package-manager/):

>A Node.js package is also available in the official repo for Debian Sid (unstable), Jessie (testing) and Wheezy (wheezy-backports) as "nodejs". It only installs a nodejs binary.
>
>The nodejs-legacy package installs a node symlink that is needed by many modules to build and run correctly. The Node.js modules available in the distribution official repositories do not need it.

I suggest you use the NodeSource ppa [section of those docs](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions). Let me know if that fixes it for you.

<details><summary>Manual install options:</summary>

If you want to install node manually, there is no "installation" on Linux per se, you just need to extract the tarball, and make sure the `node` and `npm` binaries in the `./bin` subdirectory are somewhere in your path.

I find [nvm](https://github.com/creationix/nvm#install-script) is useful for managing node installations (it will download, extract, and add to path for you). If you want to do things manually, you can do something like:

```bash
wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz
tar -xf node-v6.9.2-linux-x64.tar.gz --directory /usr/local --strip-components 1
```

This will put the `./bin` directory in `/usr/local/bin`, which should be in your `$PATH` already. You can verify that it worked with:

```bash
node --version
npm --version
```

</details>

**Comment by Bazmundi** [comment]
Gibson, thanks.  But, I have to note that the instructions from NodeSource
are likely the ones everyone is copying.  In fact while I used a link to an
example I have had the NodeSource page open in my browser.

I haven't taken the build from source route yet but that is always on the
cards.

I also notice you gave me a x64 link whilst I mentioned I was using Armbian
aka Debian on ARM.   I will substitute the pesky Arm version there if there
is one.

On Tue, May 30, 2017 at 1:13 AM, Gibson Fahnestock <notifications@github.com

**Comment by gibfahn** [comment]
I ran:

```bash
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

(on an xLinux box) and it created:

```bash
➜  ~ ❯ ls -l /usr/bin 
lrwxrwxrwx 1 root root          22 May 30 12:15 node -> /etc/alternatives/node
-rwxr-xr-x 1 root root    29766688 May  3 19:33 nodejs
lrwxrwxrwx 1 root root          38 May  3 19:33 npm -> ../lib/node_modules/npm/bin/npm-cli.js

➜  ~ ❯ ls -l /etc/alternatives/node                                                                                               ~
lrwxrwxrwx 1 root root 15 May 30 12:15 /etc/alternatives/node -> /usr/bin/nodejs
```

I'm not sure why that didn't work for you, might be an arm issue (in which case you should raise it on [nodesource/distributions](https://github.com/nodesource/distributions).

---

>I also notice you gave me a x64 link whilst I mentioned I was using Armbian
aka Debian on ARM.   I will substitute the pesky Arm version there if there
is one.

Whoops, my bad. Here's the corrected link for `armv7l` (if you're on a different arch use the [`armv6`](https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-armv6l.tar.gz) or [`armv8`](https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-ppc64.tar.gz) links instead):

```bash
wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-armv7l.tar.gz
tar -xf node-v6.9.2-linux-armv7l.tar.gz --directory /usr/local --strip-components 1
```

**Comment by Bazmundi** [comment]
Woo hoo!  so installing the arm binaries works, I was then able to install
node-red.

However, it always sickens me when something as straightforward as using
apt-get install does not work on a fresh stable distro of the OS.

Is this a problem with nodejs or armbian (or indeed orange pi)?

**Comment by gibfahn** [comment]
>Is this a problem with nodejs or armbian (or indeed orange pi)?

Not sure, I suggest raising an issue in [nodesource/distributions](https://github.com/nodesource/distributions) and linking to this one. Those guys are the experts on their packages.

**Comment by gireeshpunathil** [comment]
not an issue with nodejs itself, closing this. Please re-open if there is something outstanding with this.
