### ISSUE TITLE
can we create a complete dynamic website using nodejs and express?

### ISSUE THREAD

**Issue by bswscube** [nodejs/help#642]
can we create a complete dynamic website using nodejs and express? If yes then please share reference url for that

Thanks

**Comment by WebWeave** [comment]
Yes, this is very much possible.
However I do suggest you use a front end framework, like react or angular and let them communicate by ajax or websockets.

If you would like to spend some money there are some very good Udemy courses, or you could use this guide: [https://scotch.io/tutorials/react-on-the-server-for-beginners-build-a-universal-react-and-node-app](url)

**Comment by lordKnighton** [comment]
Closing issue for now, @bswscube if you still could use help let me know okay.
