### ISSUE TITLE
How to upgrade from Node.js version 7.10.0 to 8.0.0 on Ubuntu 16.10 ?

### ISSUE THREAD

**Issue by christalk** [nodejs/help#643]
Hello ,

How to upgrade from Node.js version 7.10.0 to 8.0.0 on Ubuntu 16.10 ?
Do we have to change the line in apt-repository ?
https://deb.nodesource.com/node_7.x  yakkety       ->  https://deb.nodesource.com/node_8**.x yakkety

Or uninstall and reinstall with 
curl -sL https://deb.nodesource.com/setup_8.x ?

Node v7.10.0
npm  v4.2.0
Ubuntu 16.10  64b
Upgrade from node 7.10.0 to node 8.0.0 ( and npm 4.2.0 to 5.0.0 )

**Comment by gibfahn** [comment]
Let's continue this in the nodesource/distribution issue you raised, https://github.com/nodesource/distributions/issues/465. If there's an issue with their apt repository, that's the place to get it fixed.

**Comment by christalk** [comment]
That's very kind of you, but are you sure it's the same issue ?
The link you are giving is only working on Debian or Ubuntu. 
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

I'm talking about  Centos
https://github.com/nodesource/distributions/issues/446
% curl -RLO https://rpm.nodesource.com/setup_8.x
% chmod 755 setup_8.x
% sudo ./setup_8.x -x


Thanks. 

Regards.

**Comment by christalk** [comment]
Hello, 

That's very kind of you, but I'm not sure it's the same issue :  Ubuntu vs Centos ?
The link you are giving is working on Debian or Ubuntu. 
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

There is another link with  Centos
https://github.com/nodesource/distributions/issues/446
% curl -RLO https://rpm.nodesource.com/setup_8.x
% chmod 755 setup_8.x
% sudo ./setup_8.x -x


Thanks. 

Regards.
Chris


      De : Gibson Fahnestock <notifications@github.com>
 À : nodejs/help <help@noreply.github.com> 
Cc : christalk <christalkto@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mercredi 31 mai 2017 11h20
 Objet : Re: [nodejs/help] How to upgrade from Node.js version 7.10.0 to 8.0.0 on Ubuntu 16.10 ? (#643)
   
Closed #643.—
