### ISSUE TITLE
How do I try the new async_hook debugging features in node 8?

### ISSUE THREAD

**Issue by Sequoia** [nodejs/help#645]
What digging environments/tools currently support it?
Also, where is it documented?

**Comment by vdeturckheim** [comment]
AFAIK, it is not really a debugging feature.

Doc is not merged yet https://github.com/nodejs/node/pull/13287/files

**Comment by Fishrock123** [comment]
1. `require('async_hooks')`. No flags needed.
2. Work in progress aimed for 8.1.0: https://github.com/nodejs/node/pull/13287

**Comment by Fishrock123** [comment]
If you would like to try it, https://github.com/AndreasMadsen/dprof is a great example that uses it to produce visualizations.

**Comment by Sequoia** [comment]
Thanks!
