### ISSUE TITLE
How can I detect to tcp client connection error or network changed?

### ISSUE THREAD

**Issue by mindori** [nodejs/help#646]
* **Node.js Version**: 6.10.3 LTS
* **OS**:RHEL 7.3
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: 'net' module

Hi, there!
I face the same problem as this issue. https://github.com/nodejs/node/issues/4560
TCP socket stay in ESTABLISHED status bug when socket's network changed. (Wi-Fi ON => OFF => ON)
(My client is android app)

So, I used the following methods. But, I can't solve it.
```
var net = require('net');
var server = net.createServer();
server.listen(3000);

server.on('connection', function (socket) {
    socket.setTimeout(1000 * 60 * 5); // 5 minutes

    // Wait for timeout event (socket will emit it when idle timeout elapses)
    socket.on('timeout', function () {
        // When I reconnect to server in 5 min, this method never called T_T
        socket.destroy(); 
    });
});
```
I think this problem will be solved if the server can detect the network error of the client.
But, I can't receive any event when client network changed. Code as follows.
```
var net = require('net');
var server = net.createServer();
server.listen(3000);

server.on('connection', (socket) => {
    socket.setKeepAlive(true, 100); // ping check

    server.on('error', () => {
        // this event never called when socket's network changed.
    });
    server.on('close', () => {
        // this event never called when socket's network changed. 
        // this event called when client terminated explicitly.
    });
});
```
How can I detect tcp client network change or network error?

**Comment by lfernando-silva** [comment]
@mindori Did you solve this problem?

**Comment by Ohen** [comment]
@mindori How did you solve this problem? could you explain to me?
