### ISSUE TITLE
Node8: Harmony object_rest_spread

### ISSUE THREAD

**Issue by peter-mouland** [nodejs/help#647]
* **Node.js Version**: 8
* **OS**: MacOS 10.12.5
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: 

Having played a _tiny_ amount with Node 8, the rest / spread implementation seems pretty complete.

I was wondering what the harmony flag `--harmony_object_rest_spread` does?

Is someone able to provide code examples of what doesn't work in Node 8 without the flag being enabled?

**Comment by vsemozhetbyt** [comment]
See for details and examples: http://2ality.com/2016/10/rest-spread-properties.html

**Comment by bnoordhuis** [comment]
It enables spread syntax in object literals:
```
var a = { x: 0, y: 1 };
var b = { ...a, z: 2 };  // { x: 0, y: 1, z: 2 }
```
