### ISSUE TITLE
Node8: Harmony dynamic_import

### ISSUE THREAD

**Issue by peter-mouland** [nodejs/help#648]
* **Node.js Version**: 8
* **OS**: MacOS 10.12.5
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: 

I see there is a harmony flag for `--harmony_dynamic_import`.  I was wondering what it does as `import` isn't support in node (i believe) and i'm sure you can already do the following `require('./file.${etx}')` ?

Is someone able to provide code examples of what doesn't work in Node 8 without the flag being enabled?

Any info appreciated, thanks!

**Comment by bnoordhuis** [comment]
It enables `import(var)` syntax but it's a no-op right now.  The static module loader hasn't been implemented yet, let alone the dynamic one.

**Comment by vsemozhetbyt** [comment]
See:
http://2ality.com/2017/01/import-operator.html
https://github.com/tc39/proposal-dynamic-import
https://bugs.chromium.org/p/v8/issues/detail?id=5785

**Comment by peter-mouland** [comment]
so would you say that this flag is more of a placeholder and enable you to write anything _usefull_ specifically with it yet?

**Comment by vkurchatkin** [comment]
It's a flag of V8. It _probably_ works form ES modules, but node.js doesn't expose module loader yet.
