### ISSUE TITLE
response does not end, res.on('end') event never occurs

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#650]
I have this POST request.
It looks the response never ends for a  HTTP POST to /coverage/client...
Is it my code, or is it perhaps that the response doesn't get ended on the part of the server?

I have this code:

```js
         let options = {
          port: 3050,
          host: cdtHost,
          path: '/coverage/client',
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          }
        };
        let req = http.request(options, function (res) {

          res.once('end', function () { 
            console.log('\nFinished sending coverage data.');   /// << res.once('end') never fires
            done();
          });

        });
```

Maybe it's my misuse, but it looks like 

```js
          res.once('end', function () { 
            console.log('\nFinished sending coverage data.');   /// << res.once('end') never fires
            done();
          });
```

will never fire, not sure why.

**Comment by gireeshpunathil** [comment]
can you also add a data listener (though dummy) :
```javascript
res.on('data', function () {
  });
```
and check?

Excerpts from [doc](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_class_http_clientrequest)
`If no 'response' handler is added, then the response will be entirely discarded. However, if a 'response' event handler is added, then the data from the response object must be consumed, either by calling response.read() whenever there is a 'readable' event, or by adding a 'data' handler, or by calling the .resume() method. Until the data is consumed, the 'end' event will not fire.`

**Comment by ORESoftware** [comment]
huh, thanks, that is so bizarre.

**Comment by gireeshpunathil** [comment]
I don't know the design decisions behind this, but please consider this example:

```javascript
var http = require('http');
let req = http.get('http://ww.google.com', function (res) {
  setTimeout(function() {
    res.on('data', function (d) {
      console.log(d.length);
    });
  },10000);
  res.on('end', function () { 
    console.log('done');
  });
});
```

A true event-driven system does not / cannot mandate the ordering of event registrations to follow the order of their occurrences. So the end handler invocation is preserved forever in expectation of a future data registration and event, lest invoking end handler when it 'ended' runs the risk of premature cleanup of data and its pertinent internal resources before a consumer arrives.

Given the premises and circumstances, do you think a better solution could have been possible?

/cc @bnoordhuis

**Comment by ORESoftware** [comment]
thanks!
