### ISSUE TITLE
Help with custom packaging of node.js 6.10.3 on Windows.

### ISSUE THREAD

**Issue by mingwandroid** [nodejs/help#654]
* **Node.js 6.10.3**:
* **Windows 10 x64**:
* **install/other?**:
* **npm/msi installer/self compilation**:

I work for Continuum Analytics and we provide `nodejs` packages. While updating to 6.10.3, I ran into a problem:

```
Can't build C:\Users\builder\conda\conda-recipes\nodejs\jquery_static due to environment creation error:
[WinError 206] The filename or extension is too long: 'C:\\Users\\builder\\mc-x64-3.6\\conda-bld\\jquery_static_1496308923299\\_b_env\\node_modules\\npm\\node_modules\\update-notifier\\node_modules\\boxen\\node_modules\\ansi-align\\node_modules\\string-width\\node_modules\\is-fullwidth-code-point\\node_modules\\number-is-nan'
```

It seems that my builds of node have a load of modules that the official releases do not have (`bluebird`, `cacache`, `call-limit`, `detect-indent`, `JSONStream`, `lazy-property`, `lru-cache`, `mississippi`, `move-concurrently`, `pacote`, `promise-inflight`, `safe-buffer`, `sorted-union-stream`, `ssri`, `update-notifier`, `uuid`) and misses a few that the official releases do have (`asap`, `normalize-git-url`, `realize-package-specifier`).

Here, my package having `update-notifier` causes it to have a very deep path length (193 characters) which `conda` (our package manager) cannot handle (when installed to a base folder containing >=67 characters) on `Windows` (we've been unable to change `conda` to make use of `UNC` paths for various reasons around `Windows` file locking semantics and `conda`'s use of hard-links).

I have three questions:

1. I believe that `npm` now flattens dependencies when it can, is this something I have to make a change to the source code to make work for `npm` itself?  (see also *)
2. Why do the official releases and my builds contain such different modules for npm? I looked through the source for MSI generation and couldn't find anything that would seem to cause exclusion of those modules (or addition of the other ones).
3. Where can I find the script / batch file that is used to make the official `.msi` releases?

My build batch file (https://github.com/ContinuumIO/anaconda/blob/nodejs/packages/nodejs/bld.bat) contains:
```
if "%ARCH%"=="32" (
   set PLATFORM=x86
) else (
  set PLATFORM=x64
)

call vcbuild.bat nosign release %PLATFORM%

COPY Release\node.exe %LIBRARY_BIN%\node.exe

%LIBRARY_BIN%\node.exe deps\npm\cli.js install npm -gf
```

(*) From reading https://docs.npmjs.com/cli/install, it seems there's a `--global-style` flag which AFAIUI, avoids flattening/deduping. I wonder if that's what is happening here since I pass `-g` when installing `npm`? Is there an opposite `--local-style` flag that would allow me to flatten global dependencies?

**Comment by gibfahn** [comment]
>1. I believe that npm now flattens dependencies when it can, is this something I have to make a change to the source code to make work for npm itself? (see also *)

The entire npm source tree is vendored into [`deps/npm`](https://github.com/nodejs/node/tree/master/deps/npm), there's no installation or compilation step required, you just need to put the right files in the right places. It will be already as flattened as it can be.

>2. Why do the official releases and my builds contain such different modules for npm? I looked through the source for MSI generation and couldn't find anything that would seem to cause exclusion of those modules (or addition of the other ones).

```bat
%LIBRARY_BIN%\node.exe deps\npm\cli.js install npm -gf
```

This installs npm@latest (i.e. npm5). That probably explains where your modules are coming from (I know [pacote is an npm5 module](https://github.com/npm/npm/blob/latest/package.json#L86)). 

You probably want to use the `package` argument instead, that bundles npm and node into a zip ([it's what our release builds do](https://github.com/nodejs/node/blob/master/vcbuild.bat#L114)).

```bat
call vcbuild.bat nosign package release %PLATFORM%
```


>3. Where can I find the script / batch file that is used to make the official .msi releases?

You can't (it's on a private Jenkins instance), but the important bit is:

```bat
vcbuild.bat build-release %ARCH% upload
```

---

I haven't seen a good solution for long file paths (other than using `UNC` paths), although using `subst` sometimes helps.

**Comment by mingwandroid** [comment]
Thank you very much for all of your help. I will try `call vcbuild.bat nosign package release %PLATFORM%` now.

**Comment by richardlau** [comment]
> Where can I find the script / batch file that is used to make the official `.msi` releases?

It's in `tools\msvs\msi`, started via [`vcbuild.bat`](https://github.com/nodejs/node/blob/v6.10.3/vcbuild.bat#L267-L269) (with the `msi` argument) and requires the [WiX Toolset](http://wixtoolset.org/). I'm not aware of any documentation on how it all works beyond that. If you're using another packager, it's probably easier to use the zip/.7z packages that are produced via the `package` argument as @gibfahn suggests. Note that you will need [7-zip](http://www.7-zip.org/) to build the zip/.7z packages.

**Comment by mingwandroid** [comment]
For now, I went for `%LIBRARY_BIN%\node.exe deps\npm\cli.js install npm@3.10.10 -gf`, seems to work well enough (though some `robocopy` would work even better I think!).

Thank you both for helping me out here.
