### ISSUE TITLE
v8: using a quantifier speeds up split()

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#656]
* **Node.js Version**: many
* **OS**: Windows 7 x64
* **Scope (install, code, runtime, meta, other?)**: v8

I am not sure if I should post this on v8 issue tracker, maybe I am missing some RegExp commonplace here.

Can anybody explain why the RegExp with a quantifier is faster here (except the weird case with the v8 5.6)?
```js
const str = 'ab'.repeat(1000);

console.time('/a/');
for (let i = 0; i < 1e4; i++) str.split(/a/);
console.timeEnd('/a/');

console.time('/a+/');
for (let i = 0; i < 1e4; i++) str.split(/a+/);
console.timeEnd('/a+/');
```

```console

  // Node.js 4.8.3 (v8 4.5.103.47) x64

/a/: 1246ms
/a+/: 799ms

  // Node.js 6.10.3 (v8 5.1.281.101) x64

/a/: 1373.404ms
/a+/: 756.321ms

  // Node.js 7.10.0 (v8 5.5.372.43) x64

/a/: 1314.573ms
/a+/: 758.805ms

  // Node.js 8.0.0-nightly201703249ff7ed23cd (v8 5.6.326.57) x64

/a/: 1215.599ms
/a+/: 1599.706ms

  // Node.js 8.0.0-nightly2017050673d9c0f903 (v8 5.7.492.69) x64

/a/: 1295.999ms
/a+/: 625.969ms

  // Node.js 8.0.0 (v8 5.8.283.41) x64

/a/: 1293.985ms
/a+/: 653.195ms

  // Node.js 8.0.0-test201704119b43f9c487 (v8 5.9.0 (candidate)) x64

/a/: 1266.587ms
/a+/: 652.215ms

  // Node.js 8.0.0-pre (v8 6.0.153) x64

/a/: 1313.029ms
/a+/: 583.952ms
```

cc @nodejs/v8

**Comment by refack** [comment]
I'm just guessing but I think that the `+` moves the virtual cursor one position forward for every match of `/a+/`
`/a/`
```
ababababababa
^
|- first match stops after `a` because `"a" == "a" == /a/` and that's the pattern. cursor = 1
```
`/a+/`
```
ababababababa
 ^
 |- first match stops after `b` because `'b' !== 'a'` and will never match RegEx no need to look back. cursor = 2
```

BTW: for your benchmark you should collect the outputs of `split` so that `V8` doesn't decide it's an operation it can skip (no side effects).

**Comment by refack** [comment]
also if you think of it `/a+/` <=> `/aa*/` so it's actually a 2 character pattern.

**Comment by bmeurer** [comment]
cc @schuay

**Comment by vsemozhetbyt** [comment]
@refack Yes, I have checked with not discarding the result, the time was the same, I've just simplified the code then. The order of checks is also insignificant (so any cycle optimizations are not the case).

`/aa*/` time is roughly the same as the `/a+/` time in all the versions.

**Comment by schuay** [comment]
Interesting, thanks for reporting.

The relevant difference between `/a/` and `/a+/` is that V8 recognizes the former as a simple string match (`JSRegExp::ATOM` type) while the latter generates irregexp matcher code (`JSRegExp::IRREGEXP` type).

The problem is that `RegExp.prototype.exec` has a fast path for `IRREGEXP` but bails to the slower runtime for `ATOM` - and `RegExp.p[@@split]` calls `exec` once for each split. That explains why `/a/` is slower than `/a+/`.

We should be able to avoid the runtime-call overhead by directly calling into string-matcher functions for `ATOM` regexps. I've opened an issue on the V8 tracker here: 

FYI: Results are different for V8 5.6 since we were in the middle of an internal refactoring, but `@@split` hadn't been optimized yet.

**Comment by schuay** [comment]
Clicked 'send' too soon. The V8 bug report is here: http://crbug.com/v8/6462

By the way, just to illustrate that `ATOM` regexps can be faster than `IRREGEXP` in other cases:

```
const str = 'aaaaaaaaaaaabaaaaaaaaaaaabaaaaaaaaaaaabaaaaaaaaaaaabc'.repeat(1000);

console.time('ATOM');
for (let i = 0; i < 1e4; i++) str.split(/aaaaaaaaaaaabaaaaaaaaaaaabaaaaaaaaaaaabaaaaaaaaaaaabc/);
console.timeEnd('ATOM');

console.time('IRREGEXP');
for (let i = 0; i < 1e4; i++) str.split(/(aaaaaaaaaaaabaaaaaaaaaaaabaaaaaaaaaaaabaaaaaaaaaaaabc)/);
console.timeEnd('IRREGEXP');
```

```
ATOM: 450.531005859375ms
IRREGEXP: 568.3740234375ms
```

**Comment by schuay** [comment]
And a final remark: timing results in the previous comment cannot be directly compared since adding a capture modifies the output - but the general point still stands.

**Comment by vsemozhetbyt** [comment]
@schuay Thank you!

It seems we can close this issue for now.

**Comment by schuay** [comment]
@vsemozhetbyt the situation should be much improved on V8 ToT as of https://crrev.com/b1ee17e588987f31d36658e733f67a9f7b971dae

Thanks again for the report, this will likely end up affecting quite a few RegExp uses in the wild.

**Comment by vsemozhetbyt** [comment]
@nodejs/v8 Can the above-mentioned patch be backported to versions that are used or will be used soon by Node.js?

**Comment by schuay** [comment]
Let's wait for Canary coverage before thinking about backmerging.

**Comment by schuay** [comment]
Seems like it's sticking, but V8 usually doesn't backmerge performance CLs.
Is there any way we could get this into Node LTS without a V8 backmerge?

cc @targos @MylesBorins @ofrobots

**Comment by ofrobots** [comment]
Indeed, V8 merge policy is to merge back bug fixes only. If this is important, we should to float it as a patch on the Node side.

**Comment by bmeurer** [comment]
I agree, this should be merged on the Node side.
