### ISSUE TITLE
var gets parameter obejct property name and not his value

### ISSUE THREAD

**Issue by catiamatos1991** [nodejs/help#659]
I have this function

```js
ServicesController.prototype.uci = function(device, config, path, section, opt, value, apply, commit){
    createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'begin');
    createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'option', opt);
    createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'value', value);
    createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'values', values);
```

Logs:

```
2|wscontro | [2017-06-07 09:40:08.353] - debug: /opt/wscontroller/wscontroller-api/routes/services ServicesController 63320169-611e-43f5-880e-9b1a13152cfd uci begin
2|wscontro | [2017-06-07 09:40:08.354] - debug: /opt/wscontroller/wscontroller-api/routes/services ServicesController 63320169-611e-43f5-880e-9b1a13152cfd uci option "disabled"
2|wscontro | [2017-06-07 09:40:08.354] - debug: /opt/wscontroller/wscontroller-api/routes/services ServicesController 63320169-611e-43f5-880e-9b1a13152cfd uci value "0"
2|wscontro | [2017-06-07 09:40:08.355] - debug: /opt/wscontroller/wscontroller-api/routes/services ServicesController 63320169-611e-43f5-880e-9b1a13152cfd uci values {"opt":"0"}
```

Where values={"opt":"1"} instead of {"disabled":"1"}

Why is this happening?

**Comment by gibfahn** [comment]
Where does the `values` variable come from? If you're logging a variable and getting the wrong result it's probably due to where the variable is assigned.

**Comment by catiamatos1991** [comment]
Here,

createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'inicio');
	
	createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'config', config);
	createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'path', path);
	createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'section', section);
	createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'option', opt);
	createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'value', value);
	createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'apply', apply);
	createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'commit', commit);
	
	
    var values={opt:value};
	createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), device.id, 'uci', 'values', values);

**Comment by gibfahn** [comment]
Try this:

```js
var values = {};
values[opt] = value;
```

instead of:

```js
var values={opt:value};
```

**Comment by gibfahn** [comment]
When you create an object like `var a = { prop: value}`, `prop` isn't a variable name, it's a literal value.

Have a look at the docs: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Object_initializer

**Comment by catiamatos1991** [comment]
Thanks! :)

**Comment by gibfahn** [comment]
I'll close this, feel free to comment again if you have any more issues.

**Comment by catiamatos1991** [comment]
Can you help me https://github.com/nodejs/help/issues/660 ? pls
