### ISSUE TITLE
how could write many functionality in asynchronous way?

### ISSUE THREAD

**Issue by vijayaraja** [nodejs/help#66]
I need to write a http post method to follow below steps.
1) insert into table1
2) insert into table2
3) create a file and write the data.
4) send a email to client.

can you please guide me. how can I achieve this. because each step depend on previous steps.

**Comment by thefourtheye** [comment]
Let's assume that all the APIs are asynchronous and respond with the Node.js style callbacks. Then you would simply write it like this

```js
const fs = require('fs');

db.insert('<sql>', function (insert1_err, result) {
  if (insert1_err) {
    // handler error here
    return;
  }

  db.insert('<sql>', function (insert2_err, result) {
    if (insert2_err) {
      // handler error here
      return;
    }

    fs.writeFile('filename', data, function (write_err) {
      if (write_err) {
        // handler error here
        return;
      }

      sendEmail(..., function (send_error, result) {
        if (send_err) {
          // handler error here
          return;
        }

        // respond with success messsage here
      });
    });
  });
});
```

**Comment by vijayaraja** [comment]
thank you for your response.
will the return statement in  insert2_err, write_err, send_err if block will stop the next asynchronous call? I mean if error occured in fs.writeFile (..) will stop running next async call and exit?

**Comment by vijayaraja** [comment]
thank you for your response.
