### ISSUE TITLE
Node is exposing internal IP address in cookie named saneID

### ISSUE THREAD

**Issue by ccarva** [nodejs/help#662]
* **Node.js Version**: v4.4.7
* **OS**: Linux Power PC 64 LE - Red Hat 7.3
* **Scope (install, code, runtime, meta, other?)**: other.
* **Module (and version) (if relevant)**:

Hi,

All nodes apps in all of our environments are displaying internal IP information on the cookie called saneID. I tried looking for information on the web but found none regarding this cookie for Node. As this is a security breach, can you please help or indicate where to to get help?

**Comment by MylesBorins** [comment]
/cc @nodejs/security 

For security concerns we request that you submit them to security@nodejs.org

**Comment by mscdex** [comment]
This isn't coming from node, but (according to google) it is instead a tracking cookie set by software previously called [Unica (now owned by IBM) NetTracker](https://www.owasp.org/index.php/Category:OWASP_Cookies_Database). My guess is that there is such intermediary software adding this between node and the client, unless there is some node module that is adding this.

**Comment by bnoordhuis** [comment]
Answered, closing.
