### ISSUE TITLE
Problems running crawler :*(

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#665]
Hi all... I am quite new to Node. I do have a good basic skillset of Javascript in general. I:
- downloaded and installed this node Crawler https://github.com/bda-research/node-crawler
- I then wrote a script in which I copied the example code: 
```js
var Crawler = require("crawler");

var c = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("title").text());
        }
        done();
    }
});

// Queue just one URL, with default callback
c.queue('http://www.amazon.com');

// Queue a list of URLs
c.queue(['http://www.google.com/','http://www.yahoo.com']);

// Queue URLs with custom callbacks & parameters
c.queue([{
    uri: 'http://parishackers.org/',
    jQuery: false,

    // The global callback won't be called
    callback: function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            console.log('Grabbed', res.body.length, 'bytes');
        }
        done();
    }
}]);

// Queue some HTML code directly without grabbing (mostly for tests)
c.queue([{
    html: '<p>This is a <strong>test</strong></p>'
}]);
```

- I saved this code into a filed called `crawl.js`
- I then ran this file by going to the specific parent folder in my terminal and typing in: crawl.js and hitting enter
- then nothing happens and Im lost :( 

Can anybody give me some handlebars on this?

Greets

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by gibfahn** [comment]
Try typing `node crawl.js`.

Let us know if you run into any problems.

**Comment by gibfahn** [comment]
You also need to make sure you've installed node (get it from https://nodejs.org/en/download/)

**Comment by WAINGOR** [comment]
Yes it did! Thank you :D

**Comment by lordKnighton** [comment]
Please close issue, if all is well. 

thank you 👍

**Comment by gibfahn** [comment]
Feel free to comment on here or raise another issue if you have  any more problems.
