### ISSUE TITLE
Problem crawling with Node...

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#667]
* **Node.js Version**: v6.9.5
* **Module**: crawler

Hi all, I have just gotten a cool Node crawler to work on my Macbook. I downloaded it at: 
https://github.com/bda-research/node-crawler
After writing this code: 

```js
var Crawler = require("crawler");

var c = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("body").text());
        }
        done();
    }
});

// Queue just one URL, with default callback
c.queue('http://www.amazon.com');


```
and run it I dont get back html tags... Does anybody know why this is?  Somehow this guy does get back pure html... https://www.youtube.com/watch?v=n-k_96h8M9g&t=38s My head is spinning a little because I tried all sorts of things so I hope somebody can help me out! 
-->

**Comment by gibfahn** [comment]
What exactly do you get? Can you show us the output you get?

Here's what I did to run your code snippet:

![image](https://user-images.githubusercontent.com/15943089/27002590-99ace2f4-4ddd-11e7-805f-998aa13c6837.png)

**Comment by gibfahn** [comment]
Breakdown:

```bash
mkdir waingor              # Create a new directory for this project
cd waingor                 # cd into it
npm init -y                # Create an empty package.json (every project you run should have one)
npm install --save crawler # Install crawler as a dependency and save it to the package.json
pst >index.js              # Paste your code into index.js (random file name)
node index.js              # Run that file with node
```

As you can see, I get the source of the page, which is a mixture of javascript and html. If you don't want it all to just spew to the terminal you can do `node index.js >myfile.txt`, which redirects the output to a file.

---

It's hard to gauge someone's experience level over the internet, but if you'd like to learn more about node check out https://nodeschool.io/#workshoppers, they have some really great interactive courses (`learnyounode` is the one to start with). If you want to learn more about the terminal the Codecademy course is pretty good: https://www.codecademy.com/en/learn/learn-the-command-line

**Comment by WAINGOR** [comment]
Hey Gibfahn, thank you so much for responding this fast! I am quite new to Node but I have about a year experience coding in JS. I have done some workshopper assignments and I go to Nodeschool amsterdam meetings sometimes. Apart from that I know some basic terminal skills. What are you running all these commands in? I cant really recognize it, it doesnt look like my mac terminal :) Thanks for proposing the terminal assignments on code academy I will make some assignments today! 
A few questions:
-  I already installed Crawler into another folder. If I create a new directory and save it again wont I get any conflicts?
- In your screenshot I dont see a single html tag... I think you are seeing the same output as I do. Did you manage so see where/in what setting all the html tags get filtered out? They talk about using the exact same settings as https://www.npmjs.com/package/htmlparser2 but I just cant find out how to stop these html tags from being removed...

Thanks for the useful tips!

Here are some pictures of my output: 

<img width="1280" alt="screen shot 2017-06-10 at 14 21 13" src="https://user-images.githubusercontent.com/19747468/27002766-da3422ae-4de9-11e7-9334-ce3351ba531f.png">
<img width="1280" alt="screen shot 2017-06-10 at 14 21 04" src="https://user-images.githubusercontent.com/19747468/27002774-e798fed8-4de9-11e7-892e-87efdb1b2d40.png">

In my output I can see the the text that is inside <p> and <div> tags when I view the source in my browser console...

Greets and thanks!

**Comment by gibfahn** [comment]
>I already installed Crawler into another folder. If I create a new directory and save it again wont I get any conflicts?

No, you can install something locally into lots of different folders, it doesn't make a difference. Basically when you do `require('crawler')` in node, npm looks for it in the `node_modules` subdirectory (and some other places, but ignore that for now).

>In your screenshot I dont see a single html tag... I think you are seeing the same output as I do. Did you manage so see where/in what setting all the html tags get filtered out? They talk about using the exact same settings as https://www.npmjs.com/package/htmlparser2 but I just cant find out how to stop these html tags from being removed...

Try replacing `console.log($("body").text());` with `console.log(res.body);`. That should give you the same output as looking at the source with your browser like this:

![image](https://user-images.githubusercontent.com/15943089/27002988-45452b46-4de6-11e7-84e2-9c26f4869b13.png)

**Comment by WAINGOR** [comment]
AWESOME!!!! you're the best thank you so much man. I was looking for this for hours... <3<3<3

**Comment by gibfahn** [comment]
>What are you running all these commands in? I cant really recognize it, it doesnt look like my mac terminal :) 

Using `Terminal.app` (the default terminal) with `oh-my-zsh` (http://ohmyz.sh/). It's a really good way to make your terminal more useful. I made a bunch of modifications (my dotfiles are [gibfahn/gcfg](https://github.com/gibfahn/gcfg), but I suggest you just start with the default `oh-my-zsh` if you're interested, it's really easy to get started with.

**Comment by WAINGOR** [comment]
Nice! I will check it out... By the way, I followed your steps and made a directory called nodecrawl etc. However when I reach this step---> pst >index.js  I get an error... It shows me this:
<img width="1097" alt="screen shot 2017-06-10 at 17 30 18" src="https://user-images.githubusercontent.com/19747468/27004045-b5fca186-4e02-11e7-8eba-333bff661101.png">
Do you know how this is possible?

**Comment by gibfahn** [comment]
That was just me pasting in the file. `pst` is a shell alias I set up. You could do `pbpaste >index.js` (works on macOS). Or just open index.js in an editor like [atom](https://atom.io/) and paste it in (with `⌘-v`).

Learning about shell aliases may be a little overkill for you at this point, but if you do here's a link: https://shapeshed.com/unix-alias/

I set `pst` [in my rc file](https://github.com/gibfahn/gcfg/blob/master/dotfiles/.config/gibrc#L91-L92).
