### ISSUE TITLE
I need Administrator

### ISSUE THREAD

**Issue by LOLMOMMY7** [nodejs/help#668]
It says: "You do not have suffcient privileges to complete this installation for all users of the machine. Log on as administrator and then retry this installation. "

So what the point is, i am Administrator. Someone please help?

**Comment by gibfahn** [comment]
Do you need to run the installer as an administrator (by right clicking and choosing `Run as administrator`?

**Comment by LOLMOMMY7** [comment]
@gibfahn It does not say i can run it as an Administrator for some reason

**Comment by refack** [comment]
It seems like the wording is a `wix` bug - https://github.com/wixtoolset/wix4/blob/develop/src/ext/UIExtension/wixlib/WixUI_en-us.wxl#L536

**Comment by LOLMOMMY7** [comment]
@refack Is it possible to fix it somehow?

**Comment by refack** [comment]
> @refack Is it possible to fix it somehow?

The wording or the behaviour?
For the wording you could file an issue at [the `wix` repo](https://github.com/wixtoolset/wix4)
For the behaviour, it's tricky...

**Comment by danielkhan** [comment]
Closing because of non activity
