### ISSUE TITLE
forEach is not a function

### ISSUE THREAD

**Issue by catiamatos1991** [nodejs/help#669]
HI everyone! I'm trying to read a json and parse it to search if a key exists.

For that I'm doing:
```js
var json = JSON.parse(response.body.replace(/\/g,''));
createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3),
          serial, 'makeRequest', 'response.body', json);

//var sn =  "DM-2M-1146668";

json.forEach(function(e) {
    Object.keys(e).forEach(function(key) {
        var value = e[key]
            console.log("key" + key);
            console.log("value "+value);
    });
});
```

My json have
```json
{
  "DM-2M-1146668":{
    "started":1497345519418,
    "renew":1497431118350,
    "token":"fab4330892d84475f5692a50bb048057",
    "expire":300,
    "timeout":300,
    "ipv6":"2016:900d:c0de::1001"
  }
}
```
and i want to check if for var sn (DM-2M-1146668) this exists in my json object.

If this exists as a key then json have a obejct for that sn.

How can i do this ? Im having the error TypeError: json.forEach is not a function

Anyone can help?

<sub>_(edited by @vsemozhetbyt: format code blocks)_</sub>

**Comment by vsemozhetbyt** [comment]
@catiamatos1991 Are you sure that `JSON.parse(response.body.replace(/\/g,''));` returns an Array, not an Object?

**Comment by catiamatos1991** [comment]
my logs

3|wscontro | [2017-06-14 10:52:29.849] - debug: /opt/wscontroller/wscontroller-service/scripts/integrator IntegratorController NA makeRequest response.body "{\"DM-2M-1146668\": {\"started\": 1497345519418, \"renew\": 1497434178530, \"token\": \"896f50586f104ac4e497855385905669\", \"expire\": 300, \"timeout\": 300, \"ipv6\": \"2016:900d:c0de::1001\"}}"
3|wscontro | [2017-06-14 10:52:29.850] - debug: /opt/wscontroller/wscontroller-service/scripts/integrator IntegratorController NA makeRequest response.body "string"
3|wscontro | [2017-06-14 10:52:29.850] - debug: /opt/wscontroller/wscontroller-service/scripts/integrator IntegratorController NA makeRequest response.body {"DM-2M-1146668":{"started":1497345519418,"renew":1497434178530,"token":"896f50586f104ac4e497855385905669","expire":300,"timeout":300,"ipv6":"2016:900d:c0de::1001"}}
3|wscontro | [2017-06-14 10:52:29.851] - debug: /opt/wscontroller/wscontroller-service/scripts/integrator IntegratorController NA makeRequest response.body "object"

I need to parse my string and split the "\" and then parse it into a json object.

In this json i have  {"DM-2M-1146668":{"started":1497345519418,"renew":1497434178530,"token":"896f50586f104ac4e497855385905669","expire":300,"timeout":300,"ipv6":"2016:900d:c0de::1001"}} and i need to verify if the key "DM-2M-1146668" exists understand?

**Comment by danielkhan** [comment]
Do a `console.log(json)` - is it something like [{some: 'thing'}, {some: 'otherthing'}] it's an array and you can use forEach on it. If there are no square brackets you have to use object.keys necause you can't iterate over an object.

**Comment by catiamatos1991** [comment]
Already fixed,

```
var json = JSON.parse(response.body.replace(/\\/g,''));
            createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), serial, 'makeRequest', 'response.body', json);                        

            var sn =  "DM-2M-1146668";
            var value, key;
            for (var key in json) {
                if( json.hasOwnProperty(sn) ) {                
                  value = json[key];
                  createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), serial, 'makeRequest', 'key', key); 
                  createLog('debug', __dirname, __filename.slice(__dirname.length + 1, -3), serial, 'makeRequest', 'valui', value); 
                } 
            } 
```

and logs:

```

3|wscontro | [2017-06-14 11:00:14.716] - debug: /opt/wscontroller/wscontroller-service/scripts/integrator IntegratorController NA makeRequest response.body {"DM-2M-1146668":{"started":1497345519418,"renew":1497434456946,"token":"7508153c5cae133574210bca47f34a01","expire":300,"timeout":300,"ipv6":"2016:900d:c0de::1001"}}
3|wscontro | [2017-06-14 11:00:14.717] - debug: /opt/wscontroller/wscontroller-service/scripts/integrator IntegratorController NA makeRequest key "DM-2M-1146668"
3|wscontro | [2017-06-14 11:00:14.718] - debug: /opt/wscontroller/wscontroller-service/scripts/integrator IntegratorController NA makeRequest value {"started":1497345519418,"renew":1497434456946,"token":"7508153c5cae133574210bca47f34a01","expire":300,"timeout":300,"ipv6":"2016:900d:c0de::1001"}
```

**Comment by danielkhan** [comment]
Closing

**Comment by vesrak** [comment]
by this i get to know, where to use ObjectKeys(data). thank you
