### ISSUE TITLE
How nodejs is more efficient if worker thread exceeds its limit?

### ISSUE THREAD

**Issue by vijayaraja** [nodejs/help#67]
I understand nodejs is single threaded to handle all request. I mean,
a Single thread receive the request and assign the request to worker thread and then start receiving the next request.
so what would happen if worker thread exceeds its limit?
it is again waiting for worker thread correct. Is it similar to Tomcat waiting for Thread to serves the request..please correct me.

**Comment by thefourtheye** [comment]
There are no worker threads as such. It uses event loop. This would be a good starting point https://nodesource.com/blog/understanding-the-nodejs-event-loop/

**Comment by vijayaraja** [comment]
Hi, thank you for the link. but take a look at below link, 
http://stackoverflow.com/questions/21485920/single-threaded-event-loop-vs-multi-threaded-non-blocking-worker-in-node-js
 
do you have any comments on the answer?

"node (via libuv) spawns many threads in the background to do work"

**Comment by bnoordhuis** [comment]
Libuv uses native multiplexing APIs when it can (for pipes, sockets, etc.) and threads when it must (e.g. for file I/O.)

As to your question what happens when the thread pool is saturated: work items queue up and are dispatched in FIFO order when a thread becomes available again.

**Comment by vijayaraja** [comment]
thank you. I believe "nodejs" is more efficient because of Event-Driven nature.
