### ISSUE TITLE
Possible Node.js bug in writable streams

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#671]
I see this error:

```
_stream_writable.js:243
  if (state.ended)
           ^

TypeError: Cannot read property 'ended' of undefined
    at process.Writable.write (_stream_writable.js:243:12)
    at process.Socket.write (net.js:661:40)
```

the code I am using is like so:

```js
const strm = fs.createWriteStream(path.resolve(__dirname + '/../logs/stderr.log'));

const stderr = process.stderr.write;
process.stderr.write = function () {
  strm.write.apply(strm, arguments);
  stderr.apply(process, arguments);
};
```

I assume it's operator error, but it also seems like there should not be a "null pointer" in the core codebase? The path to the .log file exists, and the log file gets written out/created.

**Comment by ORESoftware** [comment]
LOL I see it now, it should be:

```js
stderr.apply(process.stderr, arguments);
```

not

```js
stderr.apply(process, arguments);
```

but there's bug in core! lol

**Comment by gibfahn** [comment]
cc/ @nodejs/streams

**Comment by aqrln** [comment]
I don't think it can be qualified as a bug. If you call a method passing an object of a completely different class as `this`, it won't generally work.

**Comment by mcollina** [comment]
Closing, thanks everyone!

**Comment by ORESoftware** [comment]
It seems like it should fail early. We are trying to get "state" of undefined if I call recall. I think it should fail prior to that, and thus give the user (me) a better understanding of why the error happened. Luckily, I figured it out quickly - I should pass process.stderr instead of process LOL, but for other people they may not be so lucky.
