### ISSUE TITLE
Are circular dependencies with require statements different than those with include statements?

### ISSUE THREAD

**Issue by MaharishiCanada** [nodejs/help#674]
* **Node.js Version**: Any
* **OS**: Any
* **Scope (install, code, runtime, meta, other?)**: Any
* **Module (and version) (if relevant)**: Module

I am just checking my understanding. At first, when I learned that circular dependency was allowed in Node, I thought that it was an additional flexibility that we don't have when we include files in other languages. If file A includes file B, then file A cannot include file A.  I had the impression that it was the same level of flexibility that we have between classes: a class A can have an attribute of class B and class B can have an attribute of class A - no problem. Naively, at first, it would have made sense to have the same level of flexibility, because definitions in a module are akin to attributes in a class.    

However, after additional reading and personal experiments, my current understanding, which I am checking here,  is that the terminology "circular dependency" is misleading. There is no more circular dependency allowed with the Node `require` statement than there is with a typical include statement in other languages. In fact, I will argue that there is potentially less circular dependency.  

With a typical include statement, when you include file B at some point in file A, all the definitions prior to this point in file A are available to the execution of file B. Then the new definitions in file B are available to the remaining computation of file A.  So, there is some kind of circular dependency : file B depends on definitions in file A and file A depends on definitions in file B.  My understanding, which I am checking, is that the so called circular   dependencies with the `require`statement are of this kind - they are ordinary dependencies that we also have with ordinary include statements.  Nothing special. The only difference is that you will not see these circular dependencies if the required file B does not also require the original file A. So, you can have less circular dependencies, but not more. 

However, I have a doubt. because in the official documentation on the subject https://nodejs.org/api/modules.html#modules_cycles they say:

> Careful planning is required to allow cyclic module dependencies to work correctly within an application.

The dependencies that we have with include statements are very natural and they do not require much planning, because we have the simplicity of a tree structure:  `file A includes file B` corresponds to an arrow from node `A` to node `B` in a tree. The dependency of `B` on `A` is not seen as an arrow. So, there is no cycle.  The same easy tree structure is also there in the case of `file A requires file B`, because a subsequent `file B requires file A` will not trigger the execution of file A again - it only exhibits the dependency of  `B` on `A`. So, in the same way, it does not have to correspond to an arrow. 

I also have doubts because in one or two threads, I have seen people arguing that we should avoid these circular dependencies, as they are a sign of badly designed modules, and this contradicts the view that they are ordinary dependencies: we don't try to avoid dependencies when we include files.

So, if my understanding is incorrect, I would like to see examples of dependencies for which we  cannot find equivalents with ordinary file inclusion.

**Comment by bnoordhuis** [comment]
I'm not 100% sure what your question is.  If it's whether node supports circular dependencies, the answer is yes: A can import B and B can import A and that's not an error.  Whether it works the way you want it to is a separate question. :-)

> I have seen people arguing that we should avoid these circular dependencies, as they are a sign of badly designed modules, and this contradicts the view that they are ordinary dependencies

You need to do more work to make them work, that's why many people find them an anti-pattern.  B initially sees an empty module object when importing A (until A is done initializing), which it wouldn't see if it imported C.

That is, B normally needs to insert a delay before it can start using A:
```js
// A.js
const B = require('./B');
module.exports = { x: 42 };
```

```js
// B.js
const A = require('./A');
console.log(A.x);  // undefined
setImmediate(() => console.log(A.x));  // 42
```
Does that clear it up?

**Comment by MaharishiCanada** [comment]
My question was about how `import ('./b')` compares to `include('./b')` in other languages. The other language is not important - I refer to any include statement where the definitions before the include can be used in the execution of the included file and then the definitions in the included file can be used in the remainder of the execution of the including file. Do you see that there is a circular dependency even with these ordinary include statements?   We don't usually make a big deal about these circular dependencies - because we still have a tree structure.  My question is whether the circular dependencies with require statements in Node are of the same kind - that is, we still have a tree structure, despite these cycles. I know having a tree and cycles at the same time is contradictory, but if you don't see that we  do have both at the same time even with ordinary include statements, then you completely missed the question. However, perhaps by looking at your example more carefully, I will find the answer myself, even if you missed the question.

**Comment by MaharishiCanada** [comment]
Well, I have executed your example with Node V 7.4.0. When I execute `A.js`, I get `undefined` twice. When I execute `B.js`, I get `42` twice. This is consistent with my understanding of these so called circular dependencies. They look like the ordinary "circular dependencies" that we get with simple include statements. We usually do not make a big deal about them - we still have a tree structure. I know how to modify your example so that we get `42` in `B.js` only after we are sure that `A.js` has executed - you only need to reuse the original exports object, instead of replacing it entirely, but this would be also the behavior with an ordinary include statement.

**Comment by bnoordhuis** [comment]
Wups, I have a bug in A.js.  Replace:
```js
module.exports = { x: 42 };
```
With:
```js
exports.x = 42;
```
And it should work.  `module.exports` replaces the `exports` object, which doesn't quite work with circular dependencies.  A great example of why they are an anti-pattern, isn't it? :-)

**Comment by bnoordhuis** [comment]
I've read your other comments and it's still not clear to me what you are asking exactly.  Is the require tree a DAG?  No.  Is it different from other languages?  Yes, if you compare it to static languages like C.  No, if you compare it to dynamic languages like PHP.

**Comment by MaharishiCanada** [comment]
I know it can have cycles, so it is not always a DAG.  Also, of course, every language is different. You say that it is not different in PHP. In which way it is the same in PHP as in Node?   PHP is a good example for my question.  In PHP, if file A includes file B and file B includes file A, it will create an infinite cycle. So, we normally avoid these cycles and we have a tree structure where the root is the original file. This is why I say that we have a simple tree structure.  However, if we look carefully, even when we have such a tree, there are also a circular dependency.  
``` php
//A.php
$a = 10;
include('./B.php')
echo $b; // 20
```
``` php
// B.php
$b = $a + 10;
```
We have a tree here (with a single branch of length 1), because `A.php` includes `B.php` and that's it - there are no other inclusion.  Yet, we have a cycle because `A.php` depends on `B.php` (it needs `$b` at line 3) and also `B.php` depends on `A.php` (it needs `$a` at line 1) . Despite this circular dependency, we have the simplicity of a tree.  

My current understanding, which I am checking, is that it's the same thing with the so called circular dependencies in Node.js.  The difference is that we see the circular dependencies explicitly, because of the require statements, but they are of the same kind as in PHP and thus we also have a simple tree structure, just as we have in PHP.  It's not more complicated than in PHP, nothing special. Only, because we see the circular dependencies explicitly, people say things such as "they need special attention, plan them carefully, etc.", but in fact it's as simple as in PHP. 

If this is incorrect, which is certainly possible, then I want to see an example of a circular dependency without an equivalent with ordinary include statements.

**Comment by refack** [comment]
>``` php
>//A.php
>$a = 10;
>include('./B.php')
>echo $b; // 20
>```
>``` php
>// B.php
>$b = $a + 10;
>```
...

> My current understanding, which I am checking, is that it's the same thing with the so called circular dependencies in Node.js. The difference is that we see the circular dependencies explicitly, because of the require statements, but they are of the same kind as in PHP and thus we also have a simple tree structure, just as we have in PHP. It's not more complicated than in PHP, nothing special. Only, because we see the circular dependencies explicitly, people say things such as "they need special attention, plan them carefully, etc.", but in fact it's as simple as in PHP.
> 
> If this is incorrect, which is certainly possible, then I want to see an example of a circular dependency without an equivalent with ordinary include statements.

IMHO the main difference between `include` and `require` is more to do with scopes then with the dependency graph. `require`ed modules __do not share scope__ (except for `global` but that's a definite anti-pattern). So to elaborate on @bnoordhuis's example:
```js
// A.js
var foo = 'foo';
const B = require('./B');
console.log(typeof bar) // `undefined`

exports.x = 42;
```

```js
// B.js
var bar = 'bar';
const A = require('./A');
console.log(typeof foo) // `undefined`

console.log(A.x);  // `undefined`
setImmediate(() => console.log(A.x));  // 42
```

If we break the cycle by removing `const B = require('./B');` thing do get simpler, but just in terms of the `A` object, scope is never shared.
```js
// A.js
var foo = 'foo';
console.log(typeof bar) //still `undefined`

exports.x = 42;
```

```js
// B.js
var bar = 'bar';
const A = require('./A');
console.log(typeof foo) // `undefined`

console.log(A.x);  // now it resolved to `42`
setImmediate(() => console.log(A.x));  // 42
```

**Comment by MaharishiCanada** [comment]
Yes, the fact that scope are not shared, makes it different. In Node, we need exports statement and extra require statements to share variables, whereas in PHP it's automatic.   It was part of my understanding, which I should have emphasized.   However, whether it's more complicated or simpler, depends on whether you feel that less shared scope is more complicated or simpler.  The purpose of not sharing scope is to make it safer, not more complicated. Anyway, you seem to confirm that my understanding was correct: the difference is NOT in the circular dependencies.

**Comment by refack** [comment]
> In fact, because you do not share scopes, you might have less circular dependencies, not more.

I think the tl;dr is, you __can__ have circular dependencies, but you __should__ try to avoid them 🤷‍♂️

**Comment by MaharishiCanada** [comment]
What we should avoid is to share scope (and variables in them) when it is not necessary. Not creating circular dependencies is a consequence of that. Circular dependencies are not the issue in themselves.  

My tl;dr is: the documentation gives the impression that Node allows extra circular dependencies, when it is the opposite. By not sharing scope, which is a good thing, we have less circular dependencies.

**Comment by refack** [comment]
> My tl;dr is: the documentation gives the impression that Node allows extra circular dependencies, when it is the opposite. By not sharing scope, which is a good thing, we have less circular dependencies.

I'll try to think about a good update to the docs...
So for now we can close this issue?

**Comment by MaharishiCanada** [comment]
Sure !
