### ISSUE TITLE
node 8.1.1 and 8.1.2 armv6 builds are missing

### ISSUE THREAD

**Issue by Loghorn** [nodejs/help#676]
The https://nodejs.org/dist we site is missing the armv6 pre-built packages for the latest two versions.

**Comment by Loghorn** [comment]
Same problem for 8.2.1

**Comment by rvagg** [comment]
@jasnell there are armv6l and armv7l binaries sitting in 8.1.1 staging waiting to be promoted, could you run `./tools/release.sh` and push them up and update the blog post for it with hashes for these files please?

**Comment by Loghorn** [comment]
Same problem for 8.6.0

**Comment by jasnell** [comment]
The pi1 build bots were completely offline yesterday so the 8.6.0 images couldn't be built. I'll get those up once I'm able to. I did promote the older 8.1.1 binaries.

**Comment by gireeshpunathil** [comment]
I guess these are not problems anymore, but please re-open if that is not the case.
