### ISSUE TITLE
Installation help please

### ISSUE THREAD

**Issue by Occupy4Elephants** [nodejs/help#685]
* **Node.js Version**: v.6.11.0 LTS
* **OS**:  Debian Wheezy
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

I am installing node.js on my debian wheezy OS and have completed the following steps using the wiki:

```bash
sudo mkdir /usr/lib/nodejs
sudo tar -xJvf node-v6.5.0-linux-x64.tar.xz -C /usr/lib/nodejs 
sudo mv node-v6.5.0-linux-x64 node-v6.5.0
```

**I am stuck at this part:**
**Set the environment variable ~/.profile, add below to the end**

export NODEJS_HOME=/usr/lib/nodejs/node-v6.5.0
export PATH=$NODEJS_HOME/bin:$PATH

**I don't know how to set the environment variable ~/.profile.**

This is likely a dumb question but assistance is appreciated v much :)

Thank you!

**Comment by refack** [comment]
Hello @Occupy4Elephants IMHO your best option is [`nvm`](https://github.com/creationix/nvm#install-script).
Else you can follow the instructions in https://github.com/nodejs/help/issues/632#issuecomment-303023922

**Comment by gibfahn** [comment]
@Occupy4Elephants you can do this:

```bash
echo "export NODEJS_HOME=/usr/lib/nodejs/node-v6.5.0" >> ~/.profile
echo "export PATH=$NODEJS_HOME/bin:$PATH" >>~/.profile
```

**Comment by Occupy4Elephants** [comment]
thank you! xo Appreciate the help
