### ISSUE TITLE
Cannot listen to 'exit' or 'close' events on child process, when cp.kill() is called

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#686]
This has always struck me as strange. Something like this:

  ```js
 cp.once('exit', function(){
        // does not seem to fire
  });

 cp.once('close', function(){
        // does not seem to fire
  });

 cp.kill('SIGINT');  // or cp.kill('SIGTERM'), cp.kill('SIGINT'), etc
```

When I register both event handlers before calling cp.kill(), neither of the events fire!
How can I kill a process and only act after it's actually exitted?

**Comment by bnoordhuis** [comment]
A complete test case would be helpful.  Also, what platform is this on and with what node version?

**Comment by ORESoftware** [comment]
I have seen this same thing with multiple node.js versions, version 5-8. I have never seen this work as expected, finally I am asking a question about it. I am on MacOS Sierra, I cannot remember if I have seen the problem occur on Linux, but I have Ubuntu at home and can try it. Can you not reproduce the issue?

**Comment by Akamaozu** [comment]
@ORESoftware did you ever figure out a way to detect if `process.kill` was called?

I'm having the same issue ...

**Comment by ORESoftware** [comment]
@Akamaozu  to detect if node process has received a kill signal, use `process.on('SIGINT', fn)` or `process.on('SIGTERM,fn);`

**Comment by Akamaozu** [comment]
Sorry this was my mistake. Figured out what I was doing wrong.

**Comment by jedwards1211** [comment]
Did you guys ever figure this out?  I'm on macOS and don't get an `exit` or `close` event from the child process when I `SIGINT` it, but I do get the event when I `SIGTERM`.  The child process is a simple test script that doesn't install any `process.on('SIGINT')` hook.

**Comment by tx46** [comment]
this still does not seem to be working properly. test setup, procA->procB (detached)->some external app. if procA sends sigint to procB (negative pid), procA will never receive close/exit. works as expected with sigterm
