### ISSUE TITLE
How to run node js script on the browser 

### ISSUE THREAD

**Issue by anamika2910** [nodejs/help#69]
The browser doesn't recognise require() method and thus the script does not run on the browser

**Comment by kkc** [comment]
use script tag like following to load other module. 
```<script src="path of your module"></script>```

**Comment by gabrielsanterre** [comment]
Learn about browserify : http://browserify.org/
http://www.sitepoint.com/getting-started-browserify/
http://browserify.org/articles.html

**Comment by anamika2910** [comment]
I tried using browserify .But even after installing browserify ,the terminal always shows
browserify :  command not found.

**Comment by TheAlphaNerd** [comment]
@anamika2910 did you do ```npm i -g browserify```?

Keep in mind you won't be able to run ALL node modules in a browser, but you should be able to use a great many.

Here is an example seed project made with browserify + express -> https://github.com/thealphanerd/start-here

**Comment by TheAlphaNerd** [comment]
You may also find the browserify handbook useful --> https://github.com/substack/browserify-handbook

There is also a nodeschool class --> https://github.com/substack/browserify-adventure

**Comment by mh-cbon** [comment]
best it to check substack's videos on youtube, he uses browserify much like he takes a coffee : )

```
echo "alert('hello');"  > my_script.js
browserify my_script.js > bundle.js
echo "<script src=./bundle.js></script>" > index.html
xdg-open index.html
```

**Comment by nloveladyallen** [comment]
@mh-cbon Don't do echo blah > index.html. That replaces the entire file with "blah." Open it up in an editor and paste the `script` in the `head`.

**Comment by Boris-c** [comment]
You could give a try to https://github.com/salathegroup/nodular.js

We’re a research group and we needed to reuse Node.js code in a client front end. Our nodular.js code works great but we’d be glad to hear comments from the community 😉

It comes with a live example here: https://salathegroup.github.io/nodular.js/examples/
