### ISSUE TITLE
TypeError: Cannot assign to read only property 'timeout' of object '[object Object]'

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#690]
I created a read only object using this logic

```js
export default function freezeExistingProps(obj: any) {

    Object.keys(obj).forEach(function (key) {
      Object.defineProperty(obj, key, {
        writable: false
      });
    });
  
  return obj;
};
```

Later on, I try to reassign a value, and I get:

`TypeError: Cannot assign to read only property 'timeout' of object '[object Object]'`

Getting the error makes sense, but what does not make sense is '[object Object]'!

Any idea on how I can get a print out of the properties of the object?

**Comment by jweinsteincbt** [comment]
Have you tried `JSON.stringify(obj, null, 2)` ?

**Comment by tniessen** [comment]
What do you expect? `{ some: 'object' }.toString() === '[object Object]'`.

**Comment by ORESoftware** [comment]
omg guys

the error originates from internals not my code! jeez

I would expect the internals to do a better job logging the object, that's all

**Comment by tniessen** [comment]
I assume this can be closed.

**Comment by ORESoftware** [comment]
@tniessen yes

`{ some: 'object' }.toString() === '[object Object]'`

but what about

`util.inspect({some: 'object'})`

**Comment by tniessen** [comment]
@ORESoftware I believe that error is thrown from within v8, so there is not much we can do about it. On the other hand, v8 does not have access to `util.inspect`, so v8 would need to implement their own logic to display the object.

**Comment by ORESoftware** [comment]
yeah that's what I figured

**Comment by ORESoftware** [comment]
although I guess I am surprised that this is done implemented in C++ and not JS
