### ISSUE TITLE
xxx is not a function ?

### ISSUE THREAD

**Issue by alibaraneser** [nodejs/help#691]
I'm practising a shopping cart app. with node js. But I get this error

http://imgur.com/LQROqXG

http://imgur.com/DZNHggy

output : http://imgur.com/ZNd6VKf

**Comment by kahwee** [comment]
Can you upload your code in a repository so I can test it out? I'll help take a look.

**Comment by ORESoftware** [comment]
Yeah I am not seeing anything obviously wrong.

**Comment by thekemkid** [comment]
You seem to require the wrong file when initialising Cart in your index.js - Line 4.

```
vat Cart = require('../models/product');
```

**Comment by ORESoftware** [comment]
Dynamic typing for the win, LOL

**Comment by tniessen** [comment]
Closing as solved.
