### ISSUE TITLE
Wait for message from parent before closing

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#693]
I am on Node.js version 6-8

I have a child process file with this in it:

```js
process.on('message', function(){

});
```

this process seems to shut down as soon as I start it.

Now if I add a setTimeout to it:

```js
process.on('message', function(){

});

setTimeout(function(){

   console.log('timed out');

},3000);
```

then the process will close only after the timeout.

I swear it wasn't like this before. It was working with just process.on('message'). Did something with Node.js change with newer versions?

Anyway how can I wait for a message from the parent process before closing? One would think process.on('message') would keep the process open until the listener was removed -or- process.exit() is called, etc.

**Comment by ORESoftware** [comment]
LOL I know what's going on...I changed from 'fork' to 'spawn' and an IPC channel is not there by default.

I would recommend to the Node.js authors - please throw an error if process.on('message') is registered for a node.js process that does not have an IPC channel.

**Comment by thekemkid** [comment]
`process` is an `EventEmitter`, so it could be used in weird and funky ways to pass a 'message' event around. It would be unwise to throw when listening for a specific event on an EventEmitter when you don't know how users make use of them.

**Comment by refack** [comment]
I smell a deprecation of `message` in favor of an `IPCMessage` coming soon... 👃

**Comment by ORESoftware** [comment]
@refack thanks for the 🗣 heads up :)
