### ISSUE TITLE
[C++] Error/Exception overloading in embedded application

### ISSUE THREAD

**Issue by tamaroth** [nodejs/help#695]
* **Node.js Version**: 0.8.x 
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: 
* **Module (and version) (if relevant)**:

Hello,

I'm writing a simple application that is embedding node.js. So far everything is working great, I have managed to embed node into Visual Studio 2015 project. Node is launched as REPL and works great.

My question is, is there a way I could add my own exception /error handler in C++ code?

For instance, my current code that launches node.js is thus:

```c++
int main(int argc, char* argv[])
{
	node::Start(argc, argv);
	return 0;
}
```

Could I somehow overload the exception/error handlers so that I could process the error on my own? For instance to add logging it, or display errors somewhere else than stderr/stdout.

Simply adding try {} catch(...) {} does not work (obviously) and I'm wondering if it's at all possible or do I have to modify node.js source code for this?

Best regards,
tamaroth

**Comment by gireeshpunathil** [comment]
Standard way of defining custom exception handlers in Win32 system is SEH. (Structured Exception Handling). This involves enqueuing custom handlers ahead of the default Windows handlers. Hope these links will give you some guidance: [SEH](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680657(v=vs.85).aspx) and [SUEF](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680634(v=vs.85).aspx)

**Comment by bnoordhuis** [comment]
I suspect @tamaroth is asking how to catch JS exceptions, not C++ exceptions.

> Simply adding try {} catch(...) {} does not work (obviously) and I'm wondering if it's at all possible or do I have to modify node.js source code for this?

You may have to patch ReportException() in src/node.cc but, depending on your needs, `v8::Isolate::AddMessageListener()` might be sufficient.

**Comment by tamaroth** [comment]
Thank you @bnoordhuis! This is exactly what I needed. Modification of ReportException() was simple enough for my needs and did exactly what I needed.

Cheers!
