### ISSUE TITLE
Crypto required but not loaded

### ISSUE THREAD

**Issue by fusiodarts** [nodejs/help#696]
* **Node.js Version**: v7.10.0
* **OS**: Ubuntu 16.04
* **Module (and version) (if relevant)**: crypto

Hi,

I require crypto as 'var crypto = require("crypto")', but it doesn't find the crypto functions.
I have installed the crypto module, version 0.0.3, the latest.

So, I don't know where is the problem.
I am using a NodeJS project to implement a payment gateway, using crypto but it doesn't work.
The test in this module (in node_modules folder) works fine, but in an external controller instantiating the library not.

Thanks.

**Comment by vsemozhetbyt** [comment]
`crypto` is an internal Node.js module, you do not need to install it. You can uninstall the external one so it does not shadow the internal and then just use `var crypto = require("crypto")`.

**Comment by fusiodarts** [comment]
Yes yes it is ok, but the problem is that in the test in the payment gateway project inside node_modules, it works fine, but when we call the library from an external controller, it doesn't find crypto.

We have tried to install the crypto module because it didn't work as internal NodeJS, but we receive the same result.
We have already uninstalled the crypto external module.

**Comment by vsemozhetbyt** [comment]
cc @nodejs/crypto

**Comment by addaleax** [comment]
> I require crypto as 'var crypto = require("crypto")', but it doesn't find the crypto functions.

Is there any chance that you can be more specific? “it doesn't find the crypto functions” doesn’t tell so terribly much…

**Comment by fusiodarts** [comment]
I mean that this line don't require "crypto" if I call it from an external controller.
I need it because in the external controller where I am instantiating the library I need to use the createCipheriv function.

**Comment by addaleax** [comment]
Can you share any code to reproduce the problem?

**Comment by gibfahn** [comment]
Originally raised as https://github.com/nodejs/node/issues/13920

**Comment by fusiodarts** [comment]
In the external controller I am instantiating `var Sermepa = require('sermepa')`.
It instantiate the library, which requires "crypto"

**Comment by tniessen** [comment]
"In the external controller", are you referring to client-side code within a browser or is this within your node process?

**Comment by fusiodarts** [comment]
@gibfahn yes, it is mine. I have wrote in the incorrect platform, so the owner redirect me to this platform, sorry.

**Comment by fusiodarts** [comment]
@tniessen yes, a controller inside the client folder

**Comment by tniessen** [comment]
Well, `crypto` is a node-internal module... It is unrelated to all the stuff you do outside of the node process. Which dependency (injection) library do you use for clients? Something like require.js?

**Comment by fusiodarts** [comment]
We are implementing it in the client-side because we need that the client buy a product, so we have to generate the key for the payment gateway in the client-side.

We have webpack dependency installed, but nothing as require.js

**Comment by fusiodarts** [comment]
@tniessen sorry, the dependency (injection) library we are using babel

**Comment by tniessen** [comment]
You could probably use https://github.com/crypto-browserify/crypto-browserify (or alternatives, never used anything like that). That should work with webpack. However, modern browsers provide the `SubtleCrypto` API, which might be a better choice.

Ref https://github.com/nodejs/help/issues/432

**Comment by fusiodarts** [comment]
It is ok @tniessen a lot of thanks. We are going to try it.
We implemented crypto-browserify, but we need 3DES encryption, and with crypto-browserify we only can use AES encryption.
We are going to check the Ref that you have sent me.

**Comment by tniessen** [comment]
I am closing this as this problem is unrelated to node.
