### ISSUE TITLE
how to embed nodejs in win32 non-console application

### ISSUE THREAD

**Issue by kanbang** [nodejs/help#697]
how to embed nodejs in win32 non-console application (for example：mfc), without child process?
could someone kind show me a tiny demo
thanks

**Comment by lordKnighton** [comment]
Hey @kanbang you still need help with this? 😸

**Comment by kanbang** [comment]
yes

**Comment by gireeshpunathil** [comment]
@kanbang - Is it possible for you to explain your use case? What type of MFC application(s) you are building, and what are the features availed from node?

**Comment by kanbang** [comment]
@gireeshpunathil 
I had embed v8 in a draw toolbox,  since already using V8, why not embed node.js instead? This would allow developers to use any of the 100,000+ packages in npm without restriction.


![image](https://user-images.githubusercontent.com/4978439/28398139-62d59ecc-6d38-11e7-8dc3-457321e0bea9.png)

**Comment by gireeshpunathil** [comment]
ok, thanks. Linking this one with [14158](https://github.com/nodejs/node/issues/14158) which is potentially capable of covering this requirement.
