### ISSUE TITLE
Are environment variables loaded at launch time?

### ISSUE THREAD

**Issue by maxcbc** [nodejs/help#698]
* **Node.js Version**: All
* **OS**: All
* **Scope (install, code, runtime, meta, other?)**: runtime/code
* **Module (and version) (if relevant)**: process

Are environment variables loaded when the node process is launched? Or does calling them from `process.env` incur a system call? I'm curious at to the performance impact (if any) of directly (and repeatedly) accessing one in an express.js endpoint, rather than assigning it to a local `const` declared within the module.

**Comment by refack** [comment]
AFAICT every access to `process.env` incurs a system call &mdash; [node.cc#L2835](https://github.com/nodejs/node/blob/master/src/node.cc#L2835)
As for performance, it should be quite fast, but YMMV so you should benchmark your specific usage.
Ref: https://github.com/nodejs/node/blob/master/benchmark/process/bench-env.js

**Comment by bnoordhuis** [comment]
Not on UNIX, the environment is part of the program's address space.  It's a linear scan through possibly megabytes of memory though, so the fact that it's not a system call doesn't mean it's necessarily fast.
