### ISSUE TITLE
How to host a node.js application

### ISSUE THREAD

**Issue by IniongunIsaac** [nodejs/help#699]
I have developed a node js application using Express Js, EJS templating engine and MYSQL database. I am finding it a bit tough to host the website online (I did it the normal way I do host my PHP applications). Please advice me on how to go about hosting it.
Thanks
Best Regards

**Comment by danielkhan** [comment]
There are a few so called Plattform as a Service (PaaS) offerings but I'd recommend to simply rent a virtual machine or amazon EC2 instance and set up Node and nginx as reverse proxy there.

**Comment by lordKnighton** [comment]
@IniongunIsaac have you found anything yet? If not i can put together a small curated list. Gonna close this issue soon
