### ISSUE TITLE
Problems with the async reserved word

### ISSUE THREAD

**Issue by joingood** [nodejs/help#700]
* **Node.js Version: 6.11.0**:
* **OS: windows**:

#The reserved word async, does not work for me and I have no idea why.
![capture](https://user-images.githubusercontent.com/23662108/27639992-f16d567a-5be5-11e7-9b47-acad2d63a62d.PNG)

This appears in my console when I run the application:

(async function(){
 ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

**Comment by addaleax** [comment]
Native `async`/`await` is only available in Node >= 7.something, so this should work if you use Node 8. And conversely, if you need `async`/`await` before Node 7, you will need to transpile your code using tools like Babel.

**Comment by joingood** [comment]
How stable is node version 8?

**Comment by kahwee** [comment]
In my opinion, it's stable (and faster). However I did have to downgrade `npm` to 4.x as v5 wasn't installing packages right somehow (no time to investigate).

You can do so with `npm i -g npm@4`

**Comment by Kirmayrtomaz** [comment]
With you need use this version for node, use Promise.courutine() with generator is the same async await

``` javascript
const Promise = require('bluebird');
var example = () =>Promise.coroutine(function* (){
    const teste =yield waitThisFunction();
})();

```

**Comment by ORESoftware** [comment]
@kahwee  yeah I have seen the same problems with NPM v5...I frankly have no idea how they released something that clearly does not work.

**Comment by kahwee** [comment]
@ORESoftware Off the original topic, I do notice that the latest npm v5.2.0 is so much more reliable. I no longer have missing packages issues.

**Comment by ORESoftware** [comment]
@kahwee  good to hear

**Comment by joingood** [comment]
@addaleax I solved it with version 8 of node, thanks.

**Comment by gireeshpunathil** [comment]
closing as resolved, thanks!

**Comment by the8thbit** [comment]
I'm getting this error in Node v10.1.0
