### ISSUE TITLE
Create a small pool of bash processes, set cwd/env at a later time

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#701]
Say I want to have a small pool of bash workers, something this:

```js
const pool = [cp.spawn('bash'), cp.spawn('bash'), cp.spawn('bash')];
```

then later, I pop one of these processes off and use it

```js
const cp = pool.pop();
```

but then is there any way to change the `cwd` or `env` after the fact?

```
cp.setEnv()
cp.setCWD()
```

seems highly unlikely, just wondering. It probably will save me less than 50ms to start the processes beforehand, if that. so maybe it's not worth creating the child processes beforehand anyway? that's the only point of doing that.

**Comment by refack** [comment]
Not from the parent, but FWIW you can pipe commands to its `stdin`

**Comment by the1mills** [comment]
Yeah thx, it's probably not worth the trouble, only save a couple ms..user could always accidentally kill processes in the bash pool.

**Comment by tniessen** [comment]
POSIX does not define any mechanism to change the environment of another process, and that wouldn't be a good idea  anyway. As @refack correctly pointed out, you can change the environment of the process by passing suitable commands to the child process.

I am going to close this issue as it appears to be answered.
