### ISSUE TITLE
Write to stdin of daemon Node.js process

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#704]
I start a detached/daemon Node.js process X. How can I communicate with this process via another Node.js process? I don't have an IPC channel available, because the background process was started independently. How can I write to the stdin of process X? Is there another good way to communicate with process X besides stdin?

**Comment by refack** [comment]
Sockets? (On windows you can have a named pipe, on POSIX you can have unix sockets)

**Comment by ORESoftware** [comment]
Yeah, I am just looking for a solution that works on MacOS and other *nix flavors

**Comment by ORESoftware** [comment]
yeah I think what I did was simply start a tcp server in the recipient process and called it a day :)
