### ISSUE TITLE
How to catch ECONNRESET?

### ISSUE THREAD

**Issue by xl-yang** [nodejs/help#705]
* **Node.js Version**: 7.10
* **OS**: win32
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: https

I use https.request to read from server, and the response is fine. But after several minutes, ECONNRESET error crash the application. My question is, besides process.on('uncaughtException') (not recommended by Nodejs), **is there a proper way to catch and handle ECONNRESET for https.request?**

`{ Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`

Below is my code.
`    var options = {
      method: 'GET',
      hostname: hostname,
      path: url,
      auth: username + ':' + password,
      ca: [fs.readFileSync(path.resolve(__dirname, '../common/cer.cer'))],
    }

    const req = https.request(options, function (res) {

      res.on('data', (resdata) => {
        console.log('data');
      });

      res.on('end', () => {
        console.log('end');
      });
    })

    req.on('error', (e) => {
      console.log(e);
    });

    req.end();

**Comment by bnoordhuis** [comment]
`req.on('error', ...)` is the right way to do it.  Your example looks correct to me.

**Comment by 283084464** [comment]
@bnoordhuis 
Thanks for the reply. But sadly `req.on('error', ...)` doesn't get triggered. The request is fine and get correct resonse from server . The **ECONNRESET happened several minutes later**, so I guess by then the request is over and its event can't be triggered. Possibly I'm facing similar problems as [](https://github.com/nodejs/node/issues/3595).

 BTW, I tried using with or without keep-alive agent, and even listened socket event 'error'/'close' when `req.on('socket')` and did `socket.close()` and `socket.emit('agentRemove')`. But none of this helps, the error occured over and over again.

Please suggest.

**Comment by bnoordhuis** [comment]
Does it happen with the latest node.js 8?  What you describe sounds like a bug that was fixed some time ago.

**Comment by 283084464** [comment]
@bnoordhuis 
I see this issue in docker(Linux) with Node 6.x and my local Windows 7 with Node 7.10. 
I'll try Node 8 and let you know the result.

**Comment by 283084464** [comment]
Close by mistake

**Comment by 283084464** [comment]
@bnoordhuis I tried NodeJS 8, and got error again.
`current time: 22:51:2.750 http.request complete`
`current time: 23:6:1.770 Error: read ECONNRESET`
`C:\nodejs>node -v`
`v8.1.3`
`

**Comment by 283084464** [comment]
@bnoordhuis please suggest if I need to open an issue in nodejs/node.

**Comment by bnoordhuis** [comment]
Do you get 'error' and 'end' events?  If yes, which one comes first?  If no, file a bug but please include a ready-to-run test case.

**Comment by 283084464** [comment]
@bnoordhuis I added event for res.on('end') and req.on('error'). 'end' got triggered, but 'error' never get triggered as I mentioned above. I'll fire a bug but not sure if I can find a proper URL to reappear this issue as the current URL is in my Intranet.

**Comment by josephrocca** [comment]
I'm experiencing something similar (see my [comment](https://github.com/request/request/issues/2161#issuecomment-313375694) in #2161). This may also be related to #1946. I've posted code that reproduces the error (albeit, after a 5 or 10 minute wait) in the linked comment above.

**Comment by xl-yang** [comment]
nodejs/node#14102
I created issue under nodejs/node/issues, will use that to track this problem. Therefore close this. @josephrocca thanks for reproducing this error.

**Comment by ashtro-physicist** [comment]
I used this block of code and for now it seems to work,
```
process.on('uncaughtException', (err) => console.log('node js process error\n', err));
const server = require('http2').createSecureServer(options, (req, res) => {
    // my codes...
});
server.on('clientError', (err, socket) => {
    if (err.code === 'ECONNRESET' || !socket.writable) socket.end('HTTP/2 400 Bad Request\n');
    console.log('client error\n', err);
});
server.listen(PORT, (err) => (!err) ? console.log('listening on port', PORT) : console.log('something went wrong\n', err));
```

**Comment by sam-github-sam** [comment]
ashtro-0 you're a life saver.
I just used the server.on lump and it caught the exception which originated in the node process I was trying to talk to 
Cheers.
