### ISSUE TITLE
NODE_PATH on v7 and v8

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#706]
Just a quick question - does anyone know if the behavior of NODE_PATH changed with Node.js versions 7 or 8? Seeing something weird and trying to determine the cause. Essentially what I am seeing is modules that should be require'able because they are in the NODE_PATH, not being picked up. Works on 6, but if I switched to 7 or 8 with NVM, it stops working.

**Comment by lordKnighton** [comment]
@ORESoftware are you still having this issue?

**Comment by the1mills** [comment]
I think what's happening is that when I switch node.js versions with nvm, some weird stuff happens where I need to rebuild using node-gyp. I doubt it's an issue with NODE_PATH. Thanks.
