### ISSUE TITLE
nodejs mongo updateOne

### ISSUE THREAD

**Issue by karoul** [nodejs/help#708]
I'm facing an issue which I cannot understand:

I'm trying to execute from nodejs/model the following : 
```js
module.exports.addDet = function(username , accnbr, cycidx, det, callback) {

    let filter = {
        'username': username,
        'pf.acc.accnbr': accnbr
    }
    let pushdet = { $push: {}};
    pushdet.$push['pf.acc.$.cyc.' +cycidx+'.det'] = det;

    console.log(JSON.stringify(filter, null, 8), ",", JSON.stringify(pushdet, null, 8));

    Api.updateOne(filter, pushdet, {upsert: false},  callback);

};
```

and Result is:
```js
{
    "ok": 0,
    "n": 0,
    "nModified": 0
}
```
BUT when I ran the same command with the same parameters in Robomongo:

I got this:
```js
{
    "acknowledged" : true,
    "matchedCount" : 1.0,
    "modifiedCount" : 1.0
}
```
@angular/cli: 1.0.1
node: 7.8.0
os: linux x64

Any idea why it does NOT work from nodejs ?

<sub>_(edited by @vsemozhetbyt: added backticks for code blocks)_</sub>

**Comment by gireeshpunathil** [comment]
this is an issue that needs to be raised with probably mongodb project. Closing, please re-open if you think otherwise.
