### ISSUE TITLE
Issue with child_process "print" argument

### ISSUE THREAD

**Issue by lumenier1** [nodejs/help#709]
Hi, I have a problem with "print" argument in child_process.exec command.
This is my code:
```js
child_process.exec("print printme.txt", (err, stdout, stderr) => {
  console.log(err, stdout, stderr);
});
```
There is no error, but stdout log contains this string `�� 㤠���� ���樠����஢��� ���ன�⢮ PRN`
The problem is that this code worked a few times but now it does not. Exactly the same line of code!
It should send "printme.txt" file to the printing queue but now nothing happens.
All I understand is that you can not just take a file and print it with nodejs.

* **Node.js Version**: 7.0.0
* **OS**: Win7 x64
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

<sub>_(edited by @vsemozhetbyt: added backticks for the code block)_</sub>

**Comment by vsemozhetbyt** [comment]
Is this command (`print printme.txt`) works in the console?

Is it possible that you get something like `Unable to initialize device PRN` in some local code page?

**Comment by lumenier1** [comment]
No, it doesn't work in the console.
Despite all this "start" argument works well for for opening the file with associated application. But I  need to use "print" argument for printing.
By the way, it works well on the same PC using python with this line of code: `os.startfile("printme.txt", "print")`
Therefore, there is reason to believe that nodejs does not handle "print" argument well or there is some bug.
How horrible it would sound, but as for me there is only one working solution now - to execute python's script via nodejs just for file printing. Yay.

**Comment by vsemozhetbyt** [comment]
Node.js just delegates the command to shell here, If the command does not work in the shell, Node.js cannot fix this, if I understand the situation rightly.

**Comment by lumenier1** [comment]
Thank you for taking some time for the answer.
What's most surprising is that it only worked a couple of times.
I can not even imagine what might be wrong.

**Comment by vsemozhetbyt** [comment]
What message do you get when you run `print printme.txt` in the console?

**Comment by lumenier1** [comment]
`> null '?? ????? ???????????? ?????? PRN\r\n' ''`

**Comment by vsemozhetbyt** [comment]
I mean without Node.js. If you just open .cmd.exe` and type `print printme.txt`, what message do you get?

**Comment by lumenier1** [comment]
Yes, through windows console I get `Unable to initialize device PRN`

**Comment by vsemozhetbyt** [comment]
And in the same console, you can run a python script with `os.startfile("printme.txt", "print")` and get the file printed, right?

**Comment by lumenier1** [comment]
That's right.

**Comment by vsemozhetbyt** [comment]
That's strange...

cc @nodejs/platform-windows, @nodejs/python

**Comment by bzoz** [comment]
Pythons ([at least cpython](https://github.com/python/cpython/blob/f7eae0adfcd4c50034281b2c69f461b43b68db84/Modules/posixmodule.c#L10587))  `os.startfile` implementation uses [ShellExecuteW](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762153.aspx). This is something different from calling `print` from shell. In Python it would be something like `os.system(...)`.

I guess the `print` command stopped working for whatever reason. I also guess that you are using localized Windows 7, so this is why you get garbage - Node expects UTF8 and `print` return ANSI. You can get the original error message by redirecting the output to a file and then using `more` to display it. E.g.:
`node -p "require('child_process').execSync('print printme.txt').toString()" > errormsg && more errormsg`.

In any case, there is nothing wrong with Node here. If the command does not work in the command line shell there is nothing we can do in Node to help you out. I will close the issue, if you find a situation that running `print printme.txt` does work in command line and not in `child_process.exec` feel free to reopen the issue.

As a workaround, I guess there has to be a `npm` module for printing. If not, you can always create a Python script that uses `os.startfile` and call that from your Node app.
