### ISSUE TITLE
Icon of Node.js app is not visible in Windows X64

### ISSUE THREAD

**Issue by ayush191992** [nodejs/help#710]
* **Node.js Version : 6.11**:
* **OS: Windows 10 X64**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I have my package.json contents as below 

{
    "name": "TestApp",
    "main": "index.html",	
    "window": {
        "width": 1200,
        "height": 768,
        "icon" : "Favicon.png",
        "webkit": {
            "plugin": true
            
        }
    },
    "description": "My Test App ",
    "version": "1.0.0"	
}

icon I am using is of png type. I tested my App Icon is displaying in task bar in Windows 7/8 and Ubuntu 16.0 but When I launch my app in Windows 10 then I am not able to view the Icon in task bar for my node.js application.

Please share your comment on these

**Comment by vsemozhetbyt** [comment]
Are you using Electron or NW.js?

**Comment by ayush191992** [comment]
@vsemozhetbyt  I am using NW.js  Version of Node.js binaries used are (19.0.4)

**Comment by vsemozhetbyt** [comment]
It seems it would be better to post this issue in https://github.com/nwjs/nw.js

**Comment by ayush191992** [comment]
@vsemozhetbyt ok Thanks for your help.If you want to close it here you can close.
