### ISSUE TITLE
How do I ensure that the callback function finishes before the end of the process?

### ISSUE THREAD

**Issue by yhc-yhc** [nodejs/help#713]
test.js
```
var i = 0;
function watcher() {
    setInterval(_=>{
		i++
		console.log(i);
		checker(i, function (data) {
			builder(data, function (dd) {
				console.log(dd);
			})
		})
	}, 20);
}
function checker(i, cb) {
	setTimeout(_=>{
		cb(i+"checker");
	}, 50);
}
function builder(i, cb) {
	setTimeout(_=>{
		cb(i+"builder");
	}, 150);
}

watcher()
```
node test.js

and when the program is running, I press ctrl + c, and the terminal out is like this:

```
1
2
3
4
5
6
7
8
9
10
1checkerbuilder
11
2checkerbuilder
12
^C
```
but the 3 to 12 callback has no time to run, how resolve this problem?

**Comment by bnoordhuis** [comment]
Don't press ^C?  Or is your question how to intercept ^C?

**Comment by yhc-yhc** [comment]
@bnoordhuis , yes, how to intercept ^C in nodejs

**Comment by bnoordhuis** [comment]
`process.on('SIGINT', () => { /* ... */ })`

**Comment by yhc-yhc** [comment]
is three has any way to do something before close a process?
