### ISSUE TITLE
Need a file chooser

### ISSUE THREAD

**Issue by trump79** [nodejs/help#716]
Any suggestion on a module I can use to save and reading a text file. Looking for something like the java file chooser panel.

**Comment by Kirmayrtomaz** [comment]
See the documentation about [fs](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html). 

``` javascript
fs.readFile('/etc/passwd', (err, data) => {
  if (err) throw err;
  console.log(data);
});

```

``` javascript
fs.writeFile('message.txt', 'Hello Node.js', (err) => {
  if (err) throw err;
  console.log('The file has been saved!');
});
```

**Comment by ORESoftware** [comment]
LOL @Kirmayrtomaz I think you know that's not going to answer this person's question.

@trump79  -  node.js does not have a gui library like Java Swing TMK. The closest thing is probably Electron for Node.js, which allows you to build GUI apps for the desktop, just like Java Swing. I bet if you google for Electron + Filechooser + Node.js, you will find something.

**Comment by vsemozhetbyt** [comment]
@trump79 Do you use `const fs = require('fs');` before calling `fs` functions?

**Comment by trump79** [comment]
Yes. It is kind of strange. If I run my script like "node <script name>" from the command line it work but If I added my code to my application which is started with npm command it does not.

**Comment by vsemozhetbyt** [comment]
Maybe it is worth to add some details about the application which is started with npm command.

**Comment by trump79** [comment]
Well I can not really say much but it runs on the client machine and interacts with our java code on the server.

**Comment by tniessen** [comment]
Does "it runs on the client machine" mean that the code is effectively excuted by a browser, or is it executed within the node process?

As others have already said, node itself does not offer any GUI features or APIs, so you will probably need to look into existing libraries / frameworks (e.g. electron) or write native bindings.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if there is anything outstanding on this.
