### ISSUE TITLE
Running individual Tests on nodeJS code Repo

### ISSUE THREAD

**Issue by shivanth** [nodejs/help#718]
How do I run a single test case, say test/addons-napi/test_constructor/ , in the nodejs repo ?

**Comment by bnoordhuis** [comment]
`python tools/test.py addons-napi/test_constructor` - simple wildcards (e.g. `addons-napi/test_*`) are accepted.  Run `make build-addons-napi` if you haven't built them yet or you modified files.

**Comment by shivanth** [comment]
Bingo ! :thumbsup:
