### ISSUE TITLE
Write to named pipe, with fs.createWriteStream()

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#719]
I opened up a question about reading from a named pipe / fifo, but now I am trying to write to one.

In a bash script, I tail the named pipe:

```js
SUMANPIPEOUT="${HOME}/.suman/SUMANPIPEOUT";
tail -F ${SUMANPIPEOUT};

```
in JavaScript, I create a writable stream:

```js  
return fs.createWriteStream(path.resolve(process.env.HOME + '/.suman/SUMANPIPEOUT'));
```

it doesn't work not sure why. If I change the fifo to a regular log file, then it works. But I am hoping to get it to work with a fifo.

**Comment by gireeshpunathil** [comment]
Your code looks good to me, and I am able to get the data as expected: (node v9.0.0-pre on Linux):

```javascript
var fs = require('fs')
const wstream = fs.createWriteStream('./WPIPE')
setInterval( ()=> {
  wstream.write(`hello at ${process.hrtime()[0]}\n`)
}, 1000)
```
output:

```
$ tail -f WPIPE
hello at 2211261
hello at 2211262
hello at 2211263
hello at 2211265
hello at 2211266
hello at 2211267
hello at 2211268
hello at 2211269
```
There could be platform specific behavioral changes due the way the buffering happens in the pipes.

Also there is a subtle difference in this case compared to #717: There node stream is the reader, and your code has the ability to decide when to process the data, while bytes are flowing in. Here, tail is the reader, and it is up to the code logic of tail to decide how long to read and when and how much to output etc. An strace revealed that the tail is contineously reading until the writer has stopped writing.

**Comment by ORESoftware** [comment]
thanks I will investigate tomorrow...the problem with regular log files is that a little bit of the data is garbled with tail -f...I am hoping (fingers crossed) that using a fifo instead of a regular file will help solve that.
