### ISSUE TITLE
How to setup Node for Linux?

### ISSUE THREAD

**Issue by carlomilanesi** [nodejs/help#720]
* **Node.js Version**: 6.11.0
* **OS**: Linux sviluppo 4.8.0-58-generic #63-Ubuntu SMP Mon Jun 26 17:08:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

I downloaded the file "node-v6.11.0-linux-x64.tar.xz". Now what I should do to use node?
I found that it contains the file "node-v6.11.0-linux-x64/bin/node", and that it works if I run it. But I cannot find a "setup" program, or something similar. I presume that "node" should be copied to "/bin", but I am not sure.

**Comment by vdeturckheim** [comment]
I usually use [nvm](https://github.com/creationix/nvm) when installing node on Linux.

**Comment by gibfahn** [comment]
If you want to use a package manager, see [this guide](https://nodejs.org/en/download/package-manager/). For older Linux distros you might need to see [these instructions](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md).

If you want to install node manually, there is no "installation" on Linux per se, you just need to extract the tarball, and make sure the `node` and `npm` binaries in the `./bin` subdirectory are somewhere in your path.

I find [nvm](https://github.com/creationix/nvm#install-script) is useful for managing node installations (it will download, extract, and add to path for you). If you want to do things manually, you can do something like:

```bash
wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz
tar -xf node-v6.9.2-linux-x64.tar.gz --directory /usr/local --strip-components 1
```

This will put the `./bin` directory in `/usr/local/bin`, which should be in your `$PATH` already. You can verify that it worked with:

```bash
node --version
npm --version
```

**Comment by carlomilanesi** [comment]
The command

    sudo tar -xf node-v6.11.0-linux-x64.tar.xz --directory /usr/local --strip-components 1

has worked. I think it should be put in the download web page, or at least in the README.md file.
