### ISSUE TITLE
VM runInNewContext for ES6 classes?

### ISSUE THREAD

**Issue by NoelAbrahams** [nodejs/help#721]
* **Node.js Version**: 6.2.2
* **OS**: Windows 10
* **Scope**:  code
* **Module**: VM

**Sample Code**
```js
const vm = require('vm');
const sandbox = {};

vm.runInNewContext('class Foo{}', sandbox);
vm.runInNewContext('function Bar(){}', sandbox);

console.log(sandbox.Bar); // Prints "[Function: Bar]"
console.log(sandbox.Foo); // Prints "undefined"
```
**Expected result:**

```js
console.log(sandbox.Foo); // Prints "[Function: Foo]"
```

**Actual result**
```js
console.log(sandbox.Foo); // Prints "undefined"
```

Can someone please explain why I am unable to access the class `Foo` within the specified sandbox context?

Is my only option to use `function` instead of `class`? This really doesn't look right to me.

**Comment by addaleax** [comment]
I agree. Can you maybe open this as a bug report on https://github.com/nodejs/node?

**Comment by NoelAbrahams** [comment]
@addaleax, thanks. Ref: nodejs/node#14160.

**Comment by addaleax** [comment]
Thank you – I’m closing this, I assume there’s going to be some kind of answer or resolution in the issue in the “big” repo, we can always re-open if not. :)
