### ISSUE TITLE
How to use node js benchmark compare.R

### ISSUE THREAD

**Issue by billouboq** [nodejs/help#725]
I'm trying to use node js benchmark but I don't know how to use compare.R,

I used this for exemple : 

> ../node-changed compare.js --new ../node-changed --old ../node -runs 2 timers

with node being the old binary and node-changed the new binary

I want to display the % increase or decrease between the two, and I think that's what compare.R script is doing but can't figure out how to use it. Can you help me ?

**Comment by vsemozhetbyt** [comment]
Have you looked into https://github.com/nodejs/node/blob/master/doc/guides/writing-and-running-benchmarks.md ?

**Comment by billouboq** [comment]
oh... was just looking at the readme inside the benchmark folder and js file comments, but here it is. Thanks !
