### ISSUE TITLE
Launch a set Interval() call every client request in Node.js 

### ISSUE THREAD

**Issue by GhassenBHS** [nodejs/help#726]
I am developping a web service that will handle beacon registration. I am using set Interval in order to update an ephemeral ID every period of time with every successful request to register a new beacon.

Is that considered probelmatic for  the event loop especially when the number of registered beacons grows signicantly (Launching a thread that updates the database every x seconds, at every user request ) ?

**Comment by gireeshpunathil** [comment]
yes, that approach will mean the workload on the server will exponentially increase in proportion to the client requests.

I would suggest installing a single setInterval(), and push the work that comes from each connection into a data structure that the single timer callback can run through and process.

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is not working.
