### ISSUE TITLE
child_process.spawnSync() not return anything.

### ISSUE THREAD

**Issue by netcore-jroger** [nodejs/help#728]
* **Version**: 6.11.0 or 6.11.1
* **Platform**: Win10 Pro latest stable
* **Subsystem**:

**In my company's computer：**
```js
let result = childProcess.spawnSync('D:/Program Files/nodejs/node.exe', ['--version']);
``` 
work very well, can get return value.
 but 
```js
let result = childProcess.spawnSync('node', ['--version']);
``` 
not work and the code behind it will not execute.

**I use myself computer：**
```js
let result = childProcess.spawnSync('node', ['--version']);
``` 
was work very well.

I have added `D:\Program Files\nodejs\` to the environment variable.

This problem caused my vscode editor to not work properly. see[#45048199](https://stackoverflow.com/questions/45047450/in-the-child-process-module-in-node-js/45048199#)

**Comment by vsemozhetbyt** [comment]
Can you provide the output of the `childProcess.spawnSync('node', ['--version']);`?

**Comment by netcore-jroger** [comment]
@vsemozhetbyt 
```js
childProcess.spawnSync('node', ['--version']);
```
not return anything.
I just found that the `shell: true` can run properly.
```js
    let result = childProcess.spawnSync('node', ['--version'], {
        shell: true
    });

    console.log(result);
```
work very well. but `shell` default value is false.  Can I change the default value in global?

**Comment by gibfahn** [comment]
@netcore-jroger I suggest you use [execSync](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options), which actually spawns a shell to run the command in.

**Comment by gibfahn** [comment]
But `spawnSync` returns things for me:

![image](https://user-images.githubusercontent.com/15943089/28153326-7c5a588c-67ad-11e7-9960-491d58e0263c.png)

![image](https://user-images.githubusercontent.com/15943089/28153371-babf47a4-67ad-11e7-92e4-ccb0bf9ad7d6.png)

```
➜  ~ ❯ node                                                                                                                                                                                               ~
> require('child_process').spawnSync('node', ['--version']);
{ status: 0,
  signal: null,
  output: [ null, <Buffer 76 39 2e 30 2e 30 2d 70 72 65 0a>, <Buffer > ],
  pid: 10931,
  stdout: <Buffer 76 39 2e 30 2e 30 2d 70 72 65 0a>,
  stderr: <Buffer > }
```

**Comment by netcore-jroger** [comment]
![1](https://user-images.githubusercontent.com/3223890/28153434-eeff890a-67d7-11e7-9cc5-2605786690a7.png)

**Comment by netcore-jroger** [comment]
C:\Users\JRoger> node
> require('child_process').spawnSync('node', ['--version'], {shell: true});
{ status: 0,
  signal: null,
  output: [ null, <Buffer 76 36 2e 31 31 2e 31 0d 0a>, <Buffer > ],
  pid: 38208,
  stdout: <Buffer 76 36 2e 31 31 2e 31 0d 0a>,
  stderr: <Buffer >,
  envPairs:
   [ 'ALLUSERSPROFILE=C:\\ProgramData',
     'APPDATA=C:\\Users\\JRoger\\AppData\\Roaming',
     'ChocolateyInstall=C:\\ProgramData\\chocolatey',
     'ChocolateyLastPathUpdate=周四 5月 18 17:32:23 2017',
     'CLASSPATH=.;C:\\Program Files\\Java\\jdk1.8.0_131\\lib\\dt.jar;C:\\Program Files\\Java\\jdk1.8.0_131\\lib\\tools.j
ar;',
     'CommonProgramFiles=C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
     'CommonProgramW6432=C:\\Program Files\\Common Files',
     'COMPUTERNAME=JROGER-PC',
     'ComSpec=C:\\Windows\\system32\\cmd.exe',
     'FSHARPINSTALLDIR=C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.1\\Framework\\v4.0\\',
     'HOME=C:\\Users\\JRoger',
     'HOMEDRIVE=C:',
     'HOMEPATH=\\Users\\JRoger',
     'JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_131',
     'LOCALAPPDATA=C:\\Users\\JRoger\\AppData\\Local',
     'LOGONSERVER=\\\\JROGER-PC',
     'NUMBER_OF_PROCESSORS=8',
     'OneDrive=D:\\Users\\JRoger\\OneDrive',
     'OS=Windows_NT',
     'Path=C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Win
dows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\B
inn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\1
30\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\ManagementStudio\\;C:\\Program Files\\M
icrosoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\M
icrosoft\\Web Platform Installer\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\DTS\\Binn\\;C:\\Program Files (x8
6)\\Microsoft SQL Server\\120\\DTS\\Binn\\;D:\\Program Files\\Python27;C:\\Program Files\\dotnet\\;D:\\Program Files\\ap
ache-maven-3.5.0\\bin;"C:\\Program Files\\Java\\jdk1.8.0_131\\bin;";"C:\\Program Files\\Java\\jdk1.8.0_131\\jre\\bin;";C
:\\ProgramData\\chocolatey\\bin;D:\\Program Files (x86)\\LINQPad5;C:\\Program Files (x86)\\Microsoft Visual Studio\\2017
\\Enterprise\\MSBuild\\15.0\\Bin\\amd64;C:\\Users\\JRoger\\AppData\\Roaming\\npm;D:\\Program Files\\Git\\cmd;C:\\Program
 Files (x86)\\Microsoft VS Code\\bin;D:\\Program Files\\nodejs;D:\\Program Files\\nodejs\\;C:\\Users\\JRoger\\AppData\\L
ocal\\Microsoft\\WindowsApps;D:\\Program Files\\Python27;D:\\Program Files\\apache-maven-3.5.0\\bin;"C:\\Program Files\\
Java\\jdk1.8.0_131\\bin;";"C:\\Program Files\\Java\\jdk1.8.0_131\\jre\\bin;";C:\\Program Files (x86)\\Microsoft Visual S
tudio\\2017\\Enterprise\\MSBuild\\15.0\\Bin\\amd64;D:\\Program Files (x86)\\Microsoft VS Code\\bin;D:\\Program Files\\no
dejs;C:\\Users\\JRoger\\AppData\\Roaming\\npm',
     'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
     'PROCESSOR_ARCHITECTURE=AMD64',
     'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel',
     'PROCESSOR_LEVEL=6',
     'PROCESSOR_REVISION=5e03',
     'ProgramData=C:\\ProgramData',
     'ProgramFiles=C:\\Program Files',
     'ProgramFiles(x86)=C:\\Program Files (x86)',
     'ProgramW6432=C:\\Program Files',
     'PSModulePath=D:\\Users\\JRoger\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Module
s;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Pow
erShell\\Modules\\;C:\\Program Files\\WindowsPowerShell\\Modules\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Power
Shell\\ResourceManager\\AzureResourceManager\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\PowerShell\\ServiceManage
ment\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\PowerShell\\Storage\\',
     'PUBLIC=C:\\Users\\Public',
     'SESSIONNAME=Console',
     'SystemDrive=C:',
     'SystemRoot=C:\\Windows',
     'TEMP=C:\\Users\\JRoger\\AppData\\Local\\Temp',
     'TMP=C:\\Users\\JRoger\\AppData\\Local\\Temp',
     'USERDOMAIN=JROGER-PC',
     'USERDOMAIN_ROAMINGPROFILE=JROGER-PC',
     'USERNAME=JRoger',
     'USERPROFILE=C:\\Users\\JRoger',
     'VBOX_MSI_INSTALL_PATH=D:\\Program Files\\Oracle\\VirtualBox\\',
     'VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
     'VSSDK140Install=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\',
     'windir=C:\\Windows' ],
  options:
   { shell: true,
     windowsVerbatimArguments: true,
     file: 'C:\\Windows\\system32\\cmd.exe',
     args:
      [ 'C:\\Windows\\system32\\cmd.exe',
        '/s',
        '/c',
        '"node --version"' ],
     envPairs:
      [ 'ALLUSERSPROFILE=C:\\ProgramData',
        'APPDATA=C:\\Users\\JRoger\\AppData\\Roaming',
        'ChocolateyInstall=C:\\ProgramData\\chocolatey',
        'ChocolateyLastPathUpdate=周四 5月 18 17:32:23 2017',
        'CLASSPATH=.;C:\\Program Files\\Java\\jdk1.8.0_131\\lib\\dt.jar;C:\\Program Files\\Java\\jdk1.8.0_131\\lib\\tool
s.jar;',
        'CommonProgramFiles=C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
        'CommonProgramW6432=C:\\Program Files\\Common Files',
        'COMPUTERNAME=JROGER-PC',
        'ComSpec=C:\\Windows\\system32\\cmd.exe',
        'FSHARPINSTALLDIR=C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.1\\Framework\\v4.0\\',
        'HOME=C:\\Users\\JRoger',
        'HOMEDRIVE=C:',
        'HOMEPATH=\\Users\\JRoger',
        'JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_131',
        'LOCALAPPDATA=C:\\Users\\JRoger\\AppData\\Local',
        'LOGONSERVER=\\\\JROGER-PC',
        'NUMBER_OF_PROCESSORS=8',
        'OneDrive=D:\\Users\\JRoger\\OneDrive',
        'OS=Windows_NT',
        'Path=C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\
Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools
\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server
\\130\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\ManagementStudio\\;C:\\Program Files
\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files
\\Microsoft\\Web Platform Installer\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\DTS\\Binn\\;C:\\Program Files
(x86)\\Microsoft SQL Server\\120\\DTS\\Binn\\;D:\\Program Files\\Python27;C:\\Program Files\\dotnet\\;D:\\Program Files\
\apache-maven-3.5.0\\bin;"C:\\Program Files\\Java\\jdk1.8.0_131\\bin;";"C:\\Program Files\\Java\\jdk1.8.0_131\\jre\\bin;
";C:\\ProgramData\\chocolatey\\bin;D:\\Program Files (x86)\\LINQPad5;C:\\Program Files (x86)\\Microsoft Visual Studio\\2
017\\Enterprise\\MSBuild\\15.0\\Bin\\amd64;C:\\Users\\JRoger\\AppData\\Roaming\\npm;D:\\Program Files\\Git\\cmd;C:\\Prog
ram Files (x86)\\Microsoft VS Code\\bin;D:\\Program Files\\nodejs;D:\\Program Files\\nodejs\\;C:\\Users\\JRoger\\AppData
\\Local\\Microsoft\\WindowsApps;D:\\Program Files\\Python27;D:\\Program Files\\apache-maven-3.5.0\\bin;"C:\\Program File
s\\Java\\jdk1.8.0_131\\bin;";"C:\\Program Files\\Java\\jdk1.8.0_131\\jre\\bin;";C:\\Program Files (x86)\\Microsoft Visua
l Studio\\2017\\Enterprise\\MSBuild\\15.0\\Bin\\amd64;D:\\Program Files (x86)\\Microsoft VS Code\\bin;D:\\Program Files\
\nodejs;C:\\Users\\JRoger\\AppData\\Roaming\\npm',
        'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
        'PROCESSOR_ARCHITECTURE=AMD64',
        'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel',
        'PROCESSOR_LEVEL=6',
        'PROCESSOR_REVISION=5e03',
        'ProgramData=C:\\ProgramData',
        'ProgramFiles=C:\\Program Files',
        'ProgramFiles(x86)=C:\\Program Files (x86)',
        'ProgramW6432=C:\\Program Files',
        'PSModulePath=D:\\Users\\JRoger\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Mod
ules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\
PowerShell\\Modules\\;C:\\Program Files\\WindowsPowerShell\\Modules\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Po
werShell\\ResourceManager\\AzureResourceManager\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\PowerShell\\ServiceMan
agement\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\PowerShell\\Storage\\',
        'PUBLIC=C:\\Users\\Public',
        'SESSIONNAME=Console',
        'SystemDrive=C:',
        'SystemRoot=C:\\Windows',
        'TEMP=C:\\Users\\JRoger\\AppData\\Local\\Temp',
        'TMP=C:\\Users\\JRoger\\AppData\\Local\\Temp',
        'USERDOMAIN=JROGER-PC',
        'USERDOMAIN_ROAMINGPROFILE=JROGER-PC',
        'USERNAME=JRoger',
        'USERPROFILE=C:\\Users\\JRoger',
        'VBOX_MSI_INSTALL_PATH=D:\\Program Files\\Oracle\\VirtualBox\\',
        'VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
        'VSSDK140Install=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\',
        'windir=C:\\Windows' ],
     stdio: [ [Object], [Object], [Object] ] },
  args:
   [ 'C:\\Windows\\system32\\cmd.exe',
     '/s',
     '/c',
     '"node --version"' ],
  file: 'C:\\Windows\\system32\\cmd.exe' }

**Comment by vsemozhetbyt** [comment]
@netcore-jroger So if you run `require('child_process').spawnSync('node', ['--version']);` in the v6.11.1 RERL, it just exits without any outout?

**Comment by netcore-jroger** [comment]
yes !

**Comment by vsemozhetbyt** [comment]
cc @nodejs/platform-windows

**Comment by netcore-jroger** [comment]
in terminal also without any output.

**Comment by gibfahn** [comment]
@netcore-jroger what about:

```js
require('child_process').execSync('node', ['--version']);
```

**Comment by netcore-jroger** [comment]
@vsemozhetbyt 
```js
require('child_process').execSync('node', ['--version']);
```
work very well.

**Comment by netcore-jroger** [comment]
I found a similar question [link](http://techqa.info/programming/question/39231522/Node-crashing-when-creating-too-many-synchronous-child-processes)

**Comment by gibfahn** [comment]
In that case it's probably something to do with needing to spawn a batch shell on Windows. If you're running batch commands `execSync` is the better choice.

**Comment by netcore-jroger** [comment]
https://stackoverflow.com/questions/45047450/in-the-child-process-module-in-node-js

**Comment by netcore-jroger** [comment]
In fact, this is a problem with vscode editing. I have a little bit of debugging vscode code found this problem.

**Comment by netcore-jroger** [comment]
A lot of places in vscode use the `child_process.spawn ()` function.

**Comment by vsemozhetbyt** [comment]
Do you mean `node --version` in the `cmd.exe` terminal also outputs nothing?
What does `where node` output?

**Comment by netcore-jroger** [comment]
is there any way to update the shell in the global default value is true？

**Comment by netcore-jroger** [comment]
![2](https://user-images.githubusercontent.com/3223890/28154334-4c2bcb6c-67dc-11e7-8cf5-3cf0af01161d.png)

**Comment by netcore-jroger** [comment]
I manually modify all vscode editor code using the child_process.spawn () shell is true. The Vscode editor is working properly.

**Comment by bzoz** [comment]
@netcore-jroger, does this work for you, from a command shell:
`node -e "console.log(require('child_process').spawnSync('node', ['--version']))"`

**Comment by netcore-jroger** [comment]
@bzoz not work. But the following code works fine:
```
node -e "console.log(require('child_process').spawnSync('node', ['--version'], {shell: true}))"
```

**Comment by bzoz** [comment]
Is there anything printed out? Any error message?

**Comment by netcore-jroger** [comment]
nothing.

**Comment by bzoz** [comment]
@netcore-jroger  that is strange. You should get at least some error message.

Could you try couple more things? What does running `where node` returns? Does running `require('child_process').spawnSync('node', ['--version'])` from the REPL exits node? I mean, what you get when you do this:
![image](https://user-images.githubusercontent.com/17704638/28163107-0885520a-67ca-11e7-8bec-529ddbb5e014.png)

Also, is your D: drive unusual? A subst drive, ram drive, network share, etc>?

Can you also try running `require('child_process').spawnSync('not existing')` ?

Thanks for your answers!

**Comment by netcore-jroger** [comment]
@bzoz Look at the picture below:
![3](https://user-images.githubusercontent.com/3223890/28194384-81154f3e-6876-11e7-8700-8943c77a3196.png)

**Comment by vsemozhetbyt** [comment]
@netcore-jroger In the last case you should escape slashes: `require('child_process').spawnSync('D:\\Program Files\\nodejs\\node.exe');`.

**Comment by netcore-jroger** [comment]
Oh  sorry.
![4](https://user-images.githubusercontent.com/3223890/28194838-764b5eb0-6879-11e7-8986-6ec2a5c3598f.png)

The first parameter, if provided with a complete path, has always been normal.

**Comment by vsemozhetbyt** [comment]
Repeating @bzoz's question:
> Also, is your D: drive unusual? A subst drive, ram drive, network share, etc>?

**Comment by netcore-jroger** [comment]
@vsemozhetbyt normal drive.
![5](https://user-images.githubusercontent.com/3223890/28195198-76258c74-687b-11e7-9906-c8c4572b4996.png)

**Comment by netcore-jroger** [comment]
![6](https://user-images.githubusercontent.com/3223890/28195267-d1e6b15a-687b-11e7-813f-77132ab42212.png)

**Comment by vsemozhetbyt** [comment]
Does this happen only in REPL? Is there any output if you run a `file.js` with this code:
```js
console.log(require('child_process').spawnSync('node', ['--version']));
```

**Comment by netcore-jroger** [comment]
@vsemozhetbyt 
The same result is in the REPL and in the code file.

**Comment by vsemozhetbyt** [comment]
Does this happen with any other `.exe` files from `path` env in `C:` and `D:` drives? Is `require('child_process').spawnSync('notepad');` OK?

**Comment by netcore-jroger** [comment]
![invoke-notepad](https://user-images.githubusercontent.com/3223890/28195820-3a8c0df6-687f-11e7-9998-f41c8f1b2a25.gif)

invoke `notepad` is ok.

**Comment by vsemozhetbyt** [comment]
Is `require('child_process').spawnSync('python', ['-V'])` OK (`python` is on the `D:` drive, right)?

**Comment by netcore-jroger** [comment]
can also be.
![7](https://user-images.githubusercontent.com/3223890/28195931-eac6a17c-687f-11e7-9a5f-a3bf058297c7.png)

**Comment by netcore-jroger** [comment]
python install path:  `D:\Program Files\Python27\`

**Comment by vsemozhetbyt** [comment]
Strange.
cc @bnoordhuis, @cjihrig concerning `child_process`.

**Comment by netcore-jroger** [comment]
![8](https://user-images.githubusercontent.com/3223890/28196063-c5b218ca-6880-11e7-98e4-c54d85d7e216.png)
![9](https://user-images.githubusercontent.com/3223890/28196079-d76518ba-6880-11e7-81d2-3d8dc62cf37a.png)

**Comment by refack** [comment]
What's strage in this picture is that the REPL seems to exit
![3](https://user-images.githubusercontent.com/3223890/28194384-81154f3e-6876-11e7-8700-8943c77a3196.png)

**Comment by vsemozhetbyt** [comment]
And `node file.js` also exits without any output or error.

**Comment by netcore-jroger** [comment]
@refack yes. exited.

**Comment by refack** [comment]
So I want to say it's something is the system outside of node. @netcore-jroger could you take a look at the event log (run `eventvwr.msc`) if it says anything about `node.exe` crashing.

**Comment by netcore-jroger** [comment]
I found into the installation directory and execute the command `require ('child_process'). SpawnSync ('node', ['--version']);` can work properly.
But it will not work properly on the terminal.

![14](https://user-images.githubusercontent.com/3223890/28196254-085e91ac-6882-11e7-9b39-c6d7d3b2fd6c.png)
![10](https://user-images.githubusercontent.com/3223890/28196266-18c5a008-6882-11e7-8d39-73abd677671f.png)
![11](https://user-images.githubusercontent.com/3223890/28196268-18c8d912-6882-11e7-87cc-65f8a34ad4f0.png)
![12](https://user-images.githubusercontent.com/3223890/28196267-18c81d7e-6882-11e7-92c8-e1fab4d1f5a1.png)
![13](https://user-images.githubusercontent.com/3223890/28196269-18cc757c-6882-11e7-8146-5de31c9393b4.png)

**Comment by netcore-jroger** [comment]
@refack 
has nothing information in Windows Application events.

**Comment by refack** [comment]
@netcore-jroger Can you also post the output of `set` or `cmd /k set`

**Comment by netcore-jroger** [comment]
@refack `set` command.
![15](https://user-images.githubusercontent.com/3223890/28196412-158b6976-6883-11e7-8c9e-07ac55d12ee5.png)

**Comment by refack** [comment]
So there are two thing that are not common:
1. Your `%ProgramFiles% == `C:\Program Files`, but `nodejs` is in `D:\Program Files\nodejs`
2. There are directories with `"` in your `%Path% `which is unusual, maybe even the cause...
![image](https://user-images.githubusercontent.com/96947/28196502-12ae6abe-681f-11e7-9541-1ed466f85447.png)
For example my %Path% is:
```
d:\code\node-cur$ set Path
Path=D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64;D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.2;D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\MSBuild\15.0\bin\Roslyn;D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64;D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\Common7\IDE\;D:\bin\dev\VS\Microsoft Visual Studio 2017 Community\Common7\Tools\;C:\Tools\maint\conemu\ConEmu\Scripts;C:\Tools\maint\conemu;C:\Tools\maint\conemu\ConEmu;c:\Program Files\Microsoft MPI\Bin\;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32\Tools;C:\WINDOWS\system32\downlevel;C:\WINDOWS\system32\Java\jre\bin;C:\WINDOWS\system32;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\Wbem;C:\WINDOWS;C:\bin\dev\node;C:\bin\dev\python27;C:\bin\dev\python27\Scripts;C:\bin\git\usr\bin;C:\bin\git\cmd;C:\Tools\maint;C:\Tools\dev;C:\code\tools;C:\code\tools\scripts;.\node_modules\.bin\;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
PATHEXT=.JS;.;.CMD;.BAT;.EXE;.MSC;.COM
```
None of the entries has `"`

**Comment by netcore-jroger** [comment]
Oh sorry. my `set` command run in powershell.
when I run in `cmd.exe`
output result like this below picture:
![1](https://user-images.githubusercontent.com/3223890/28196658-92b97216-6884-11e7-8041-6e09062516cb.png)

**Comment by refack** [comment]
@netcore-jroger if you run this command in a console:
``` cmd
for %G in ("%path:;=" "%") do @echo %G
```
I'm assuming you'll get some strange results

**Comment by netcore-jroger** [comment]
Oh sorry . I did not look carefully, still has quotes.

**Comment by netcore-jroger** [comment]
![2](https://user-images.githubusercontent.com/3223890/28196694-de658894-6884-11e7-946c-390f75f880bd.png)

**Comment by netcore-jroger** [comment]
Let me modify the environment variables try.

**Comment by refack** [comment]
It's a bug in the way `libuv` searches the path - https://github.com/libuv/libuv/blob/v1.x/src/win/process.c#L409
If you either remove the `"` or the `;` that inside the quotes it should work.

**Comment by netcore-jroger** [comment]
@refack 
Thanks very much!!! it works.
![3](https://user-images.githubusercontent.com/3223890/28196888-fb156788-6885-11e7-953c-f8751902c3ad.png)
![4](https://user-images.githubusercontent.com/3223890/28196951-5b2902d8-6886-11e7-81f8-c42d69aeff25.png)

just one more one a `;`

**Comment by netcore-jroger** [comment]
@refack @vsemozhetbyt @bzoz @gibfahn 
Thanks very much !!!

**Comment by refack** [comment]
Great. Happy to be of help.
You can open an issue at libuv - windows: path search crashes when path contains `";";`. ( Or I'll open it tomorrow )

**Comment by netcore-jroger** [comment]
@refack 
I think you open this issue more appropriate.  I do not understand C .

**Comment by netcore-jroger** [comment]
@refack 
I think windows environment variable manager also has a problem, did not show more out of the `"`

**Comment by refack** [comment]
For posterity this is a minimal reproducing code (for Windows)
```js
d:\code\node-cur$ node
> process.env.Path = String.raw`";";C:\bin\dev\nodejs`
'";";C:\\bin\\dev\\nodejs'
> require('child_process').spawnSync('node.exe -i')

d:\code\node-cur$ echo %ERRORLEVEL%
-1073741819
```

**Comment by bzoz** [comment]
@refack great find. I've already started making a patch for that for libuv

**Comment by refack** [comment]
Fllowup https://github.com/libuv/libuv/issues/1422

**Comment by vsemozhetbyt** [comment]
@refack It seems it should be `require('child_process').spawnSync('node.exe'], ['-i'])` in your example (otherway we get ENOENT in any case).

**Comment by vsemozhetbyt** [comment]
@refack You may want to fix the example in the libuv issue too)

**Comment by refack** [comment]
> @refack great find. I've already started making a patch for that for libuv

Too many year doing 1st tier support 😖 

> @refack It seems it should be require('child_process').spawnSync('node.exe', ['-i']) in your example (otherway we get ENOENT in any case).

Minimized it even more.

and Re https://github.com/nodejs/node/pull/14149/files#r126477309
```js
d:\code\node-cur$ node
> process.env.Path = String.raw`"";`
'"";'
> require('child_process').spawnSync('cmd.exe') !== null
true
> process.env.Path = String.raw`";";`
'";";'
> require('child_process').spawnSync('cmd.exe') !== null

d:\code\node-cur$ echo %ERRORLEVEL%
-1073741819
```
