### ISSUE TITLE
Create resilient require mechanism

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#731]
This regards Node.js versions > v4.0.0

I am attempting to create a specialized resilient require mechanism, whereby missing dependencies can be installed in a fallback manner.

I asked this question on SO:
https://stackoverflow.com/questions/45091517/create-resilient-require-mechanism-in-node-js

The monkey-match on require looks like this:

```js
const cp = require('child_process');
const Mod = require('module');
const req = Mod.prototype.require;
Mod.prototype.require = function (d) {

  try {
    return req.apply(this, arguments);
  }
  catch (e) {
    if (/^[A-Za-z]/.test(String(d))) {
      console.error(`could not require dependency "${d}".`);
      try {
        var actualDep = String(d).split('/')[0];
        console.error(`but we are resilient and we are attempting to install "${actualDep}" now.`);
        cp.execSync(`cd ${_suman.projectRoot} && npm install ${actualDep}`);
        return req.apply(this, arguments);
      }
      catch (err) {
        console.error('\n', err.stack || err, '\n');
        throw e;
      }

    }
    else {
      throw e;
    }
  }

};
```

It mostly works, however I am seeing some somewhat strange behavior - for some reason the following two dependencies fail the first `try` statement

```
bufferutil
utf-8-validate

```
this doesn't make sense to me, because require() works without any errors normally, but when using the patch, require() suddenly fails for these two...so weird.

Anyone know what might be going on? Super weird.

(Note what it's doing is only attempting to re-install dependencies that start with a lowercase character, it won't attempt to install a dependency that starts with './' etc.)

**Comment by ORESoftware** [comment]
Ahh, as the guy on SO pointed out, it's probably some extraneous dependency, that's using

```js
try{
require(x);
}
catch(e){}
```

so what I am doing is probably a bad idea, because I can't be sure if the dependency is supposed to throw or now.

**Comment by bnoordhuis** [comment]
That's most likely it.  Both modules you mention are native modules and those usually have a try/catch block around their `require('./build/Release/binding.node')` calls.

**Comment by ORESoftware** [comment]
yeah, that makes sense, thanks, I will close.
