### ISSUE TITLE
How can I build or make a specific test 

### ISSUE THREAD

**Issue by shivanth** [nodejs/help#732]
I'm trying to write a few test cases for the NAPI tests, how can I add build a specific test after I make a change to it , especially the c/cpp files in it?

Say I am going to make changes to the c files in https://github.com/nodejs/node/tree/master/test/addons-napi/test_typedarray 
and I want to run only this test

**Comment by bnoordhuis** [comment]
`make build-addons-napi && python tools/test.py addons-napi/test_typedarray`

**Comment by shivanth** [comment]
Thanks @bnoordhuis
