### ISSUE TITLE
RSA SHA256 signature for JWT by nodeJs

### ISSUE THREAD

**Issue by bt10** [nodejs/help#736]
Hi,

I want to generate RSA SHA256 signature based on jwt.io by nodeJs. Is there any source code or anything or available.

Regards

**Comment by bnoordhuis** [comment]
What do "token" and "based on jwt.io" mean in this context?  Does jwt.io do something different from standard RSA-SHA256?  Does token mean signature?

**Comment by bt10** [comment]
Hi,
Actually, i have put reference only from jwt.io regarding JWT signature creation based on RSA-SHA256 by either JavaScript or NodeJS.

**Comment by bnoordhuis** [comment]
You create a signature with `crypto.createSign('RSA-SHA256')`.  Examples can be found in the crypto module documentation.

**Comment by bt10** [comment]
I have written already code but that is for SHA256, and apply same mthode for RSA but not working., Code has been sent to you your info@bnoordhuis.nl

**Comment by bnoordhuis** [comment]
Please post it here and include the error message you got.

**Comment by bt10** [comment]
function getSHA256Data(message,secret){
            var hash = CryptoJS.HmacSHA256(message, secret);
            return CryptoJS.enc.Base64.stringify(hash);
			}

**Comment by bnoordhuis** [comment]
When you post code, please make sure it's complete enough that it actually runs.  What was the error message you got?

**Comment by bt10** [comment]
Actuallu code is very long thats why i didnt post. It is generating SHA256 signature, but i need RSA-SHA256

**Comment by bnoordhuis** [comment]
Then post an abridged version or write a short test script.  The point is that it needs to be complete enough that you and I can have a conversation about it without either side having to guess what the other side means.

**Comment by bt10** [comment]
have you any related code to generate RSA SHA256 signature

**Comment by bnoordhuis** [comment]
Have you looked at the documentation?  Is anything unclear?

**Comment by bt10** [comment]
I am unable to create by NodeJS while i can in Javascript. But there is nothing available in Javascript

**Comment by bt10** [comment]
// Header
var oHeader = {alg: 'RS256', typ: 'JWT'};
// Payload
var oPayload = {};
var tNow = KJUR.jws.IntDate.get('now');
var tEnd = KJUR.jws.IntDate.get('now + 1day');
oPayload.iss = "http://foo.com";
oPayload.sub = "mailto:mike@foo.com";
oPayload.nbf = tNow;
oPayload.iat = tNow;
oPayload.exp = tEnd;
oPayload.jti = "id123456";
oPayload.aud = "http://foo.com/employee";

var sHeader = JSON.stringify(oHeader);
var sPayload = JSON.stringify(oPayload);

var pbKey = KEYUTIL.getKey("-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDdlatRjRjogo3WojgGHFHYLugdUWAY9iR3fy4arWNA1KoS8kVw33cJibXr8bvwUAUparCwlvdbH6dvEOfou0/gCFQsHUfQrSDv+MuSUMAe8jzKE4qW+jK+xQU9a03GUnKHkkle+Q0pX/g6jXZ7r1/xAK5Do2kQ+X5xK9cipRgEKwIDAQAB
-----END PUBLIC KEY-----");

var sJWT = KJUR.jws.JWS.sign("RS256", sHeader, sPayload, pbKey);
console.log(sJWT);

**Comment by bnoordhuis** [comment]
Have you read https://nodejs.org/api/crypto.html#crypto_class_sign?

**Comment by bt10** [comment]
I'm using Box.com for my application. For that I am creating JWT assertion by JavaScript and for that we need 3 parts:
<header>.<claims>.<signature>.
I have written JavaScript code for RSA-SHA256 to generate signature part in RSA-SHA256.
So my question here is, how to create SIGNATURE part with RS256 algorithms. Any help would be appreciated.

ReferenceError: "require" is not defined.

var jwt = require('jsonwebtoken');
var fs = require('fs');
var base64url = require("base64url");
var request = require('request');
var client_id = 123
var client_secret = 123
var key = fs.readFileSync('23er444'); 
var passphrase = 3444
var exp = Math.round((Date.now()/1000))+60;

var header = {
    "alg": "RS256",
    "typ": "JWT",
    "kid": keyID
};
var claims = {
    "iss": client_id,
    "sub": "sss",
    "box_sub_type": "user",
    "aud": "https://api.box.com/oauth2/token",
    "jti": "ddsss",
    "exp": exp
};

var encodedHeader = base64url(new Buffer(JSON.stringify(header)));
var payload = base64url(new Buffer(JSON.stringify(claims)));

var signature = jwt.sign(encodedHeader + '.' + payload, {key: key, passphrase: passphrase}, {algorithm: 'RS256'});
var encodedsignature = base64url(new Buffer(JSON.stringify(signature)));
var jwt = encodedHeader + "." + payload + "." + encodedsignature; //hier befindet sich wahrscheinlich Fehler
return jwt;

var options = {
    uri: 'https://api.box.com/oauth2/token',
    method: 'POST',
    json: true,
    headers: {'content-type': 'application/x-www-form-urlencoded'},
    body: 'grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&client_id=' + client_id + '&client_secret=' + client_secret + '&assertion=' + jwt
};

**Comment by tniessen** [comment]
See also https://github.com/nodejs/help/issues/730#issuecomment-317717963

**Comment by bnoordhuis** [comment]
For posterity, @bt10 deleted most of his or her comments, making it look like a rather one-sided conversation. :-/

**Comment by tniessen** [comment]
I am going to close this as the issue (as it is) is neither particularly helpful to others nor does @bt10 show interest in further communication leading to a solution.
