### ISSUE TITLE
Installing binary for Windows problem

### ISSUE THREAD

**Issue by nvasilev1** [nodejs/help#737]
* **Node.js **: Version : 8.1.4
* **OS**:windows 7 , 64 bit
* **Scope **: install

Hello,
Sorry if this topic is already discussed, but was not able to find it. 

I downloaded the binary version of Node.js for windows (.zip file) and unzip it. I am not sure what should be done next or that is all. I tried writing node -v and npm -v in the command prompt, but a message "node is not recognized as an internal or external command, operable program or batch file" appeared. Could you please advise me how I can proceed here?

Thanks in advance for helping me.

**Comment by vsemozhetbyt** [comment]
I think you should add the folder with node.exe to PATH environment variable or use the full path in commands.

cc @nodejs/platform-windows, @refack

**Comment by seishun** [comment]
That, or use the [installer](https://nodejs.org/dist/v8.1.4/node-v8.1.4-x64.msi) which adds node to `PATH` for you.

**Comment by nvasilev1** [comment]
Thanks, It worked :)

**Comment by refack** [comment]
For posterity: https://github.com/nodejs/node/issues/12311#issuecomment-293058120
