### ISSUE TITLE
Intstallation Verificaition Tests

### ISSUE THREAD

**Issue by bryont** [nodejs/help#74]
Hello, 
Is there a suite of tests that are already written that can be used to verify that a node JS installation is working correctly?  I was looking for something much more than a hello world.  

I test script that will use different features of Node JS

Thanks,
Bryon Trott

**Comment by kelthenoble** [comment]
Umm, no. Like every one else just do - node -v to make sure it's installed on your computer. But  something relative to this is in the works.   https://github.com/nodejs/evangelism/issues/200  
![screen shot 2016-01-16 at 11 38 10 pm](https://cloud.githubusercontent.com/assets/1773260/12376466/b6e8ad82-bcaa-11e5-8e05-7933c5edf0bc.png)

**Comment by kelthenoble** [comment]
nodejs/evangelism#200

**Comment by kelthenoble** [comment]
closing for now, but nodejs/evangelism#200 is the only thing i can think of that in the works. Feel free to reopen or comment in nodejs/evangelism#200
