### ISSUE TITLE
Prerequisites and Requirements for a Node server

### ISSUE THREAD

**Issue by rafael-trevisan** [nodejs/help#743]
* **Node.js Version**: 8.1.4
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**: N/A

Hey guys, I've done a nodejs app that I need to deploy into prod.

My IT department is asking for a "official" document (or manual, link, etc) to provide them all prerequisites and requirements. I know, the process is straightforward and I have myself done it thousand of times but, because they're going to install something and open a port in their firewall (I'm using Express) they're concerned about how to properly.

I've tried to find anything on the nodejs website but I couldn't... so if you guys have something to help, I'd be thankful.

Thanks in advance.

**Comment by styfle** [comment]
> "official" document (or manual, link, etc) to provide them all prerequisites and requirements

Is there another document we can use as reference? Perhaps .NET or Java has an "official" document somewhere we can take a look at?

**Comment by gireeshpunathil** [comment]
it depends on what the pre-requisites and requirements are for: the [building node.js from source](https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms) page has good amount of information about the platform support, toolchain requirement etc. , not all are relevant for running a production scale application, but a subset may apply.

Hope this helps, if there are more specific questions on pre-requisites, I can attempt to answer.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding.
