### ISSUE TITLE
Net API - Connect TCP socket via proxy

### ISSUE THREAD

**Issue by poojas2288** [nodejs/help#745]
I need to create a tcp socket connection to a server via internal proxy.
If I directly connect to the server, I get connection refused error. The only way to connect is via proxy, using tunneling.
Is there a way to accomplish this ?

I have gone through the documentation : https://nodejs.org/api/net.html
But did'nt find any options for proxy connections.

**Comment by tniessen** [comment]
This has not been implemented in node core as it can easily be implemented in userland. Please refer to npm packages for proxy support. I cannot suggest a specific one as this mainly depends on your requirements and the kind of proxy you are trying to use (I assume SOCKS as you are talking about TCP).

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding.
