### ISSUE TITLE
npx in the debian 8.2.1 package is not executable

### ISSUE THREAD

**Issue by gdamjan** [nodejs/help#746]
Installed the latest update from the `deb https://deb.nodesource.com/node_8.x stretch main` repo for Debian stretch.

`/usrb/bin/npx` is a symlink to `../lib/node_modules/npm/bin/npx-cli.js` (resolves to `/usr/lib/node_modules/npm/bin/npx-cli.js`) but the `npx-cli.js` file doesn't have the executable bit set, so `npx` is useless.

**Comment by chrislea** [comment]
Yup, that's an error on our part. Making new builds now to fix this. Thanks for the catch.

**Comment by chrislea** [comment]
We've pushed packages to the repository where this is fixed. Thanks again for the catch.

I can't close this as I'm not an admin on the nodejs repo, so please close it when you see this. Thanks.

/cc @evanlucas

**Comment by aqrln** [comment]
@chrislea thanks!
