### ISSUE TITLE
Warn if flag is in progress 

### ISSUE THREAD

**Issue by pannous** [nodejs/help#75]
(probably too many) users run into errors like 
https://github.com/nodejs/help/issues/31
https://github.com/nodejs/node/issues/2760
etc

Please output warnings when encountering those flags!

node --harmony_modules
> import { square, diag } from 'lib';
... \
SyntaxError: Unexpected token import

**Comment by kelthenoble** [comment]
Hey at @pannous, did you have any luck with this so far? If not let me know & we will tackle it together :8ball:

**Comment by evanlucas** [comment]
As a general statement, most of the harmony flags should be considered as "in progress". Unless they are enabled by default. A good way to see if something has been shipped would be to run `node --v8-options | grep -A1 harmony`. If the default shows `true`, then it should work properly.

**Comment by kelthenoble** [comment]
@pannous did you need anymore help going forward with this?

**Comment by subfuzion** [comment]
@pannous, in reference to the bug you mentioned, you could run this command `node --v8-options | grep "in progress"` to see that "harmony modules" is still in progress.

Please be aware that in progress features are [incomplete and possibly broken features of V8, so use them at your own risk](https://nodejs.org/en/docs/es6/#which-features-are-in-progress). By definition, you should **only** consider the features that are enabled by default (don't require a runtime flag) to be stable features.

Hope this helps clarify things.
