### ISSUE TITLE
code ELIFECYCLE Exit status 1 at EventEmitter.<anonymous>

### ISSUE THREAD

**Issue by sirsquall** [nodejs/help#750]
I'm opening this issue because:

I'm using the boilerplate : https://github.com/vuejs-templates/pwa/tree/master/template
and when I run e2e to fire the tests on my mac everything is working fine, but not on my Jenkins, and I don't konw why

How can the CLI team reproduce the problem?

 ```
0 info it worked if it ends with ok
1 verbose cli [ '/jenkins/workspace/Xxx/vue/node/node',
1 verbose cli   '/var/lib/jenkins/workspace/Xxx/vue/node/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e' ]
2 info using npm@4.6.1
3 info using node@v7.10.1
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle xxx@1.0.0~pree2e: xxx@1.0.0
6 silly lifecycle xxx@1.0.0~pree2e: no script for pree2e, continuing
7 info lifecycle xxx@1.0.0~e2e: xxx@1.0.0
8 verbose lifecycle xxx@1.0.0~e2e: unsafe-perm in lifecycle true
9 verbose lifecycle xxx@1.0.0~e2e: PATH: /jenkins/workspace/Xxx/vue/node/node_modules/npm/bin/node-gyp-bin:/jenkins/workspace/Xxx/vue/node_modules/.bin:/var/lib/jenkins/wo
rkspace/Xxx/vue/node:/var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/3.3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:
10 verbose lifecycle xxx@1.0.0~e2e: CWD: /jenkins/workspace/Xxx/vue
11 silly lifecycle xxx@1.0.0~e2e: Args: [ '-c', 'node test/e2e/runner.js' ]
12 silly lifecycle xxx@1.0.0~e2e: Returned: code: 1  signal: null
13 info lifecycle xxx@1.0.0~e2e: Failed to exec e2e script
14 verbose stack Error: xxx@1.0.0 e2e: `node test/e2e/runner.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/jenkins/workspace/Xxx/vue/node/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/jenkins/workspace/Xxx/vue/node/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid xxx@1.0.0
16 verbose cwd /jenkins/workspace/Xxx/vue
17 verbose Linux 3.13.0-105-generic
18 verbose argv "/jenkins/workspace/Xxx/vue/node/node" "/var/lib/jenkins/workspace/Xxx/vue/node/node_modules/npm/bin/npm-cli.js" "run" "e2e"
19 verbose node v7.10.1
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error xxx@1.0.0 e2e: `node test/e2e/runner.js`
23 error Exit status 1
24 error Failed at the xxx@1.0.0 e2e script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

## supporting information:

node -v prints: v7.10.1
npm -v prints: v4.6.1
npm config get registry prints:
Windows, OS X/macOS, or Linux?: Linux OS name: "linux", version: "3.13.0-105-generic", arch: "amd64", family: "unix"

**Comment by sirsquall** [comment]
fixed, was due to a missing package in the package.json

**Comment by crlang44** [comment]
What version is this fixed in?

**Comment by sirsquall** [comment]
This is not related to a version, is because you forgot to require a package in your package.json

**Comment by crlang44** [comment]
Do you recall which package you were missing? I'm having hard time interpreting the log.

Log for reference:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS\\node.exe',
1 verbose cli   'C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:android' ]
2 info using npm@5.5.1
3 info using node@v6.9.5
4 verbose run-script [ 'prebuild:android', 'build:android', 'postbuild:android' ]
5 info lifecycle gmapp@6.2.0~prebuild:android: gmapp@6.2.0
6 info lifecycle gmapp@6.2.0~build:android: gmapp@6.2.0
7 verbose lifecycle gmapp@6.2.0~build:android: unsafe-perm in lifecycle true
8 verbose lifecycle gmapp@6.2.0~build:android: PATH: C:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\npm\bin\node-gyp-bin;C:\Jenkins\workspace\gm-mobile-android-build\node_modules\.bin;C:\Program Files\Java\jdk1.8.0_144/bin;C:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs;C:\Program Files (x86)\CVSNT\;C:\Users\build\AppData\Roaming\npm;%JAVA_HOME%\bin;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools;C:\Users\build\AppData\Roaming\npm\;C:\Windows\System32;C:\Program Files\Git\cmd\
9 verbose lifecycle gmapp@6.2.0~build:android: CWD: C:\Jenkins\workspace\gm-mobile-android-build
10 silly lifecycle gmapp@6.2.0~build:android: Args: [ '/d /s /c', 'webpack && cordova build android --verbose' ]
11 silly lifecycle gmapp@6.2.0~build:android: Returned: code: 1  signal: null
12 info lifecycle gmapp@6.2.0~build:android: Failed to exec build:android script
13 verbose stack Error: gmapp@6.2.0 build:android: `webpack && cordova build android --verbose`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid gmapp@6.2.0
15 verbose cwd C:\Jenkins\workspace\gm-mobile-android-build
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS\\node.exe" "C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:android"
18 verbose node v6.9.5
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error gmapp@6.2.0 build:android: `webpack && cordova build android --verbose`
22 error Exit status 1
23 error Failed at the gmapp@6.2.0 build:android script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sirsquall** [comment]
I deleted the vendor in local, and I just run the same command as Jenkins, and I see the package missing

**Comment by jebaemanuel** [comment]
me too facing the same issue. Could you please check it and give idea.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS\\node.exe',
1 verbose cli   'C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:android' ]
2 info using npm@5.5.1
3 info using node@v6.9.5
4 verbose run-script [ 'prebuild:android', 'build:android', 'postbuild:android' ]
5 info lifecycle gmapp@6.2.0~prebuild:android: gmapp@6.2.0
6 info lifecycle gmapp@6.2.0~build:android: gmapp@6.2.0
7 verbose lifecycle gmapp@6.2.0~build:android: unsafe-perm in lifecycle true
8 verbose lifecycle gmapp@6.2.0~build:android: PATH: C:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\npm\bin\node-gyp-bin;C:\Jenkins\workspace\gm-mobile-android-build\node_modules\.bin;C:\Program Files\Java\jdk1.8.0_144/bin;C:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJs;C:\Program Files (x86)\CVSNT\;C:\Users\build\AppData\Roaming\npm;%JAVA_HOME%\bin;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools;C:\Users\build\AppData\Roaming\npm\;C:\Windows\System32;C:\Program Files\Git\cmd\
9 verbose lifecycle gmapp@6.2.0~build:android: CWD: C:\Jenkins\workspace\gm-mobile-android-build
10 silly lifecycle gmapp@6.2.0~build:android: Args: [ '/d /s /c', 'webpack && cordova build android --verbose' ]
11 silly lifecycle gmapp@6.2.0~build:android: Returned: code: 1  signal: null
12 info lifecycle gmapp@6.2.0~build:android: Failed to exec build:android script
13 verbose stack Error: gmapp@6.2.0 build:android: `webpack && cordova build android --verbose`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid gmapp@6.2.0
15 verbose cwd C:\Jenkins\workspace\gm-mobile-android-build
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS\\node.exe" "C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:android"
18 verbose node v6.9.5
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error gmapp@6.2.0 build:android: `webpack && cordova build android --verbose`
22 error Exit status 1
23 error Failed at the gmapp@6.2.0 build:android script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by PaymentsAutomationScriptRepository** [comment]
I am facing the same issue. can you please help me which package was missing here ?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'startDevPayMyBillTests' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'prestartDevPayMyBillTests',
4 verbose run-script   'startDevPayMyBillTests',
4 verbose run-script   'poststartDevPayMyBillTests' ]
5 info lifecycle uitests@1.0.0~prestartDevPayMyBillTests: uitests@1.0.0
6 info lifecycle uitests@1.0.0~startDevPayMyBillTests: uitests@1.0.0
7 verbose lifecycle uitests@1.0.0~startDevPayMyBillTests: unsafe-perm in lifecycle true
8 verbose lifecycle uitests@1.0.0~startDevPayMyBillTests: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\aravind.gunasekaran\Documents\Automation Repository\Access Optus\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Git\cmd;%JAVA_HOME%\bin;~\AppData\Roaming\npm;c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;c:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\NUnit.org\nunit-console;C:\Program Files (x86)\NUnit.org\nunit-console;C:\Program Files\apache-maven-3.8.2\bin;C:\Users\aravind.gunasekaran\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\aravind.gunasekaran\AppData\Local\Programs\Python\Python39\;C:\Users\aravind.gunasekaran\AppData\Local\Microsoft\WindowsApps;C:\Users\aravind.gunasekaran\AppData\Roaming\npm;C:\Users\aravind.gunasekaran\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\aravind.gunasekaran\.dotnet\tools;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1\bin;
9 verbose lifecycle uitests@1.0.0~startDevPayMyBillTests: CWD: C:\Users\aravind.gunasekaran\Documents\Automation Repository\Access Optus
10 silly lifecycle uitests@1.0.0~startDevPayMyBillTests: Args: [ '/d /s /c', 'gulp startPayMyBillTests --env Dev' ]
11 silly lifecycle uitests@1.0.0~startDevPayMyBillTests: Returned: code: 1  signal: null
12 info lifecycle uitests@1.0.0~startDevPayMyBillTests: Failed to exec startDevPayMyBillTests script
13 verbose stack Error: uitests@1.0.0 startDevPayMyBillTests: `gulp startPayMyBillTests --env Dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid uitests@1.0.0
15 verbose cwd C:\Users\aravind.gunasekaran\Documents\Automation Repository\Access Optus
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "startDevPayMyBillTests"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error uitests@1.0.0 startDevPayMyBillTests: `gulp startPayMyBillTests --env Dev`
22 error Exit status 1
23 error Failed at the uitests@1.0.0 startDevPayMyBillTests script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
