### ISSUE TITLE
node shebang question

### ISSUE THREAD

**Issue by keenwon** [nodejs/help#754]
* **Node.js Version**: v6.10.1
* **OS**: windows 7 and git bash 
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**: process

cli.js: 
```js
#!/usr/bin/env node

console.log(`columns: ${process.stdout.columns}`);
console.log(`rows: ${process.stdout.rows}`);
```

```shell
$ node cli.js
columns: 118
rows: 39

# but run cli.js directly
$ ./cli.js
columns: undefined
rows: undefined
```

Is there any way to get the term columns and rows when run with shebang? (eg. install the module global)

**Comment by vsemozhetbyt** [comment]
@keenwon It seems this is due to `mintty` known issue:

https://github.com/git-for-windows/git/wiki/FAQ#some-native-console-programs-dont-work-when-run-from-git-bash-how-to-fix-it

https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues

```js
#!/path/to/node

'use strict';

console.log(process.stdout.isTTY);

console.log(`columns: ${process.stdout.columns}`);
console.log(`rows: ${process.stdout.rows}`);
```

```console
$ node test.js
true
columns: 160
rows: 30

$ ./test.js
undefined
columns: undefined
rows: undefined

$ winpty bash

$ ./test.js
true
columns: 160
rows: 30
```

**Comment by keenwon** [comment]
Thanks a lot.
