### ISSUE TITLE
error lineNumber and filename

### ISSUE THREAD

**Issue by saurav2501** [nodejs/help#756]
* **Node.js Version**: 6.10.2
* **OS**: windows 10

I'm not able to track error lineNumber and fileName using error.lineName or error.fileName ??

**Comment by addaleax** [comment]
Can you give more context? An example of what you’re trying to do or what doesn’t work?

**Comment by saurav2501** [comment]
I'm trying to log error lineNumber and fileName in a file using
error.lineNumber and error.fileName but it is showing undefined for
linenumber and filename. But it is showing result for error name and code
using error.name and error.code. I want same for error lineNumber and
fileName. Kindly help me through this.

**Comment by bnoordhuis** [comment]
They're non-standard properties.  More specifically, they are Mozilla extensions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/lineNumber

**Comment by tniessen** [comment]
You can try to parse the error stack (`err.stack`) which usually contains file names and line numbers, but this is kind of hacky.

**Comment by addaleax** [comment]
https://github.com/v8/v8/wiki/Stack-Trace-API is a better alternative to parsing the stringified stack trace, fwiw. Maybe that helps.

**Comment by gireeshpunathil** [comment]
closing as answered, please let me know if that is not the case.
