### ISSUE TITLE
[C++ Addon] Unable to access isolate from native code.

### ISSUE THREAD

**Issue by tamaroth** [nodejs/help#759]
Hello,

I have embedded nodejs in my own application (with some difficulties, but managed) and at the same time that application is an addon in itself. 

I'm accessing nodejs/v8 with Nan.

The simplified structure is as follows:

MyAddon was injected into bootstrap_node.js as a global object:

`global.myaddon = process.binding('myaddon');`

My addon has two functions:

```
NAN_METHOD(SetValue)
{
	SetJsValue();
	uv_loop_t* loop{ uv_default_loop() };
	uv_timer_init(loop, &gc_init);
	uv_timer_start(&gc_init, init_main, 10, 0);
}
NAN_METHOD(GetValue)
{
	info.GetReturnValue().Set(Nan::New(GetJsValue()).ToLocalChecked());
}
```

And corresponding local (non-exported) functions:

```
void SetJsValue()
{
	Nan::TryCatch try_catch;
	auto ctx = Nan::GetCurrentContext();
	auto glb = ctx->Global();
	Set(glb, Nan::New("key").ToLocalChecked(), Nan::New("this is a secret key").ToLocalChecked());
}
char *GetJsValue()
{
	auto ctx = Nan::GetCurrentContext();
	auto glb = ctx->Global();
	auto val = Get(glb, Nan::New("key").ToLocalChecked());
	if (val.IsEmpty())
		return "Couldn't get the value!";
	return *Nan::Utf8String(val.ToLocalChecked()->ToString());
}
void init_main(uv_timer_t *handle)
{
	std::cout << GetJsValue() << std::endl;
}
```

When I execute REPL and then execute the command:

`myaddon.SetValue()`

my plugin will, as expected, retrieve current context, and sets the chosen ket to the chosen value.

However, when the timer function is executed, my program exits at retrieving current context.

I do realise that most likely my "external" code cannot reach already initialised instance of node, so my question is: how do I achieve this? How do I get access to node structures from outside?

Thank you in advance.

**Comment by tamaroth** [comment]
I have found the solution.

For this to work, I must create a handle scope each time I create or access a JavaScript object. In case of JavaScript-accessible functions and Nan, implicit HandleScope is created. But in case of external functions, i.e. functions that can, and often are, accessed from outside from JavaScript, you must create HandleScope explicitly.

To rectify it, the modified code looks like:

```
char *GetJsValue()
{
	Nan::HandleScope scope;
	auto glb = Nan::GetCurrentContext()->Global();
	auto val = Get(glb, Nan::New("key").ToLocalChecked());
	if (val.IsEmpty())
		return "Couldn't get the value!";
	return *Nan::Utf8String(val.ToLocalChecked()->ToString());
}
```

**Comment by bnoordhuis** [comment]
That's not exactly safe though.  The Nan::Utf8String goes out of the scope, the returned pointer points to just-freed memory.

**Comment by tamaroth** [comment]
Ahh, I did not realise! Thank you, I've fixed the problem (working on not my code so had to leave char* as a return value).
