### ISSUE TITLE
Uncaught Error: Cannot find module './reducers'.

### ISSUE THREAD

**Issue by Dindaleon** [nodejs/help#76]
I want to use `require` on the client side with a variable instead of a string, as follows:

    var somePath = '../reducers';
    var someFunc = require(somePath);

If I do that, I get the following error:

    Uncaught Error: Cannot find module './reducers'.

The following works:

    var someFunc = require('../reducers');

So, how can I use `require` with a variable?

**Comment by SomeoneWeird** [comment]
The error you got makes it seem like you only tried to require `./reducers` whereas your second attempt you required `../reducers`. Using a variable absolutely works, I think you may have just mixed up your paths :)

**Comment by Dindaleon** [comment]
Sorry @SomeoneWeird , I mistyped it.

Here is another example:

This works:

    var SomeContent = require('../extensions/myContent/containers')

This does not:

    var testpath = '../extensions/myContent/containers'
    var SomeContent = require(testpath)

the error: `Uncaught Error: Cannot find module '../extensions/myContent/containers'.`

**Comment by kelthenoble** [comment]
Have you saw this? http://stackoverflow.com/questions/9146980/how-can-i-pass-a-variable-while-using-require-in-node-js

**Comment by kelthenoble** [comment]
As well you should look over this, https://nodejs.org/api/modules.html#modules_module_require_id
Here in the docs, it's saying that you would only require a string. 

>module.require(id)
: id String
: Return: Object module.exports from the resolved module

so to my knowledge & perception of the documents, you can't pass in a variable. :+1: 

But i want to ask, why are you trying to do it that way?

**Comment by Dindaleon** [comment]
@kelthenoble thanks for the answer, I would have an array of paths that lead to different modules and I would like to loop through that array and storing/requiring each module into a variable. Do you know if there is any other way of doing this?

**Comment by kelthenoble** [comment]
That's sounds very clever, but to my knowledge their isn't.

**Comment by Dindaleon** [comment]
@kelthenoble well I managed to do it on the server side without an issue. I am now trying to do this on reactjs.

**Comment by kelthenoble** [comment]
glad to hear it bro. react.js is out of parameters of what i'm doing here, so good luck with it. And thanks @SomeoneWeird & @Dindaleon if you need further help, you know where to find us. :smile: :+1:

**Comment by SomeoneWeird** [comment]
Again, you can *absolutely* use variables with `require`, the path is relative to the file you're requiring from, are you sure it's correct?

**Comment by Dindaleon** [comment]
@SomeoneWeird yes I am sure because when I use the string, it works.

**Comment by blakeembrey** [comment]
@Dindaleon Are you using `webpack`, `browserify` or something else? You generally can't use variable requires with them because the client-side requires knowing what's included up-front.

**Comment by Dindaleon** [comment]
@blakeembrey yes, I am using webpack. Well, that would defeat the purpose of what I am trying to achieve. So I guess I am out of luck.

**Comment by SomeoneWeird** [comment]
Ahhhh right, that makes a lot more sense now. Have a look at [dynamic webpack requiring](https://webpack.github.io/docs/context.html) and let me know how you go.

**Comment by Dindaleon** [comment]
just WOW! That was awesome!! Thank you @SomeoneWeird Sorry for not specifying I was using webpack.

This is what I am using now:

```
var req = require.context('../extensions')
var testpath = './myContent/containers'
var SomeContent = req(testpath)
```

I would like to avoid having to use `require.context` by using `ContextReplacementPlugin`

I tried with the following inside my webpack's config but it did not work. I am not good at regular expressions, 

```
new webpack.ContextReplacementPlugin(
                /(..\/extensions)/
)
```

I know we already went off topic but I I would appreciate some help with it.

**Comment by kelthenoble** [comment]
Hey @Dindaleon I was reading this book & i came across a technique that you might could use. I think what you have in mind is larger, but if you could derive a way from the following, that would be cool. But if your over it then, oh well. Any way, I hope this some what helps. 

![screen shot 2016-01-19 at 8 49 28 pm](https://cloud.githubusercontent.com/assets/1773260/12440237/4ba719f0-beee-11e5-8cb3-121f9961ed5e.png)
 
and  
![screen shot 2016-01-19 at 8 50 17 pm](https://cloud.githubusercontent.com/assets/1773260/12440243/531afaa8-beee-11e5-8c97-fdbec63babd5.png)

**Comment by SomeoneWeird** [comment]
Yeah that's pretty simple, but also requires you maintaining an `index.js` file, and keeping that updated each time you add/remove another file.

**Comment by kelthenoble** [comment]
:+1: @SomeoneWeird

**Comment by Dindaleon** [comment]
@SomeoneWeird @kelthenoble thanks for sharing and for your support. Yes, I did solve it by using `require.context` and it is working nice enough. No need to maintain an index. Everything gets automated. Contributors to my project can develop an extension or a theme and drop it inside the extension's folder and it will just work. No need to export or import anything. The only requirement is an index file inside the extension specifying the name of the extension and whether it is active or not.

The extensions may be composed of redux reducers and react components.

I just published the new version, you can take a look at it:

https://github.com/Dindaleon/hapi-react-starter-kit

**Comment by kelthenoble** [comment]
Glad to hear it :100:
