### ISSUE TITLE
Proxy server question

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#760]
This pertains to Node.js versions greater than 4.0.0

re: https://stackoverflow.com/questions/45384853/proxy-request-with-node-js-neterr-empty-response/45385003#45385003

Why does this work:

```js
router.post('/image', function (req, res, next) {

  const filename = uuid.v4();

  const proxy = http.request({
    method: 'PUT',
    hostname: 'engci-maven.nabisco.com',
    path: `/artifactory/cdt-repo/folder/${filename}`,
    headers: {
      'Authorization': 'Basic ' + Buffer.from('foo:bar').toString('base64'),
    }
  }, function(resp){

    resp.pipe(res).once('error', next);

  });

  req.pipe(proxy).once('error', next);

});
```

but this does **not** work:

```js
router.post('/image', function (req, res, next) {

  const filename = uuid.v4();

  const proxy = http.request({
    method: 'PUT',
    hostname: 'engci-maven.nabisco.com',
    path: `/artifactory/cdt-repo/folder/${filename}`,
    headers: {
      'Authorization': 'Basic ' + Buffer.from('foo:bar').toString('base64'),
    }
  });

  req.pipe(proxy).pipe(res).once('error', next);

});
```

any info much appreciated.

**Comment by mcollina** [comment]
The object `http.request` returns is not a Duplex, so you can only write to it, not read from it. You are hitting https://github.com/nodejs/node/pull/14358, which will be fixed in Node 9.

I think the code you are writing would work using https://www.npmjs.com/package/request.

**Comment by ORESoftware** [comment]
@mcollina yeah I see, glad I wasn't totally off-base.
