### ISSUE TITLE
Determine if process is connected via pipes

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#764]
I have this question on Unix/Linux stackexchange:

https://unix.stackexchange.com/questions/382849/determine-if-process-is-connected-to-another-process-via-pipes

> If I do this:
> 
>     x | y
> 
> is there any way to check, during the runtime of x, to see if it's connected to y?
> 
> Specifically, I am talking about the Node.js runtime, so perhaps this is a Node.js specific question. But ultimately, I am wondering if it's possible to determine given any runtime. Is it possible and how?
> 
> 

Is it possible to determine if the stdout/stderr are hooked up to the stdin of another process? I guess that's what this question is about.

**Comment by bnoordhuis** [comment]
Short answer: no

Longer answer: file descriptors can be shared across processes, i.e., the remote end of the pipe may be present in more than one process.  There is no portable way to get that list of processes.

**Comment by ORESoftware** [comment]
yeah that makes sense
