### ISSUE TITLE
when to make ES Module harmony ?

### ISSUE THREAD

**Issue by SteveCruise** [nodejs/help#765]
I want to use **import / export** very much,  please tell me when will ES Module be harmony ?

**Comment by bnoordhuis** [comment]
Yes, eventually.  In the mean time you can transpile with Babel.

**Comment by tniessen** [comment]
We don't have an ETA yet as there are some problems in the interaction of node and ES6 modules. James has written [this article](https://hackernoon.com/node-js-tc-39-and-modules-a1118aecf95e) and [this follow-up](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c), explaining why implementing ES6 modules in node is not trivial. Be assured that we are working on a solution!

**Comment by SteveCruise** [comment]
Thank you, Thank you so much @bnoordhuis @tniessen 。
