### ISSUE TITLE
Node.js memory usage monitoring - is using the values from `process.memoryUsage()` sufficient?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#766]
I have a TCP server responsible for distributed locking

https://github.com/ORESoftware/live-mutex

I have a test that simply lets the process run for an ~hour, with 75 connected clients doing some bombardment and timeouts, etc. I want to monitor memory usage, to ensure there are no memory leaks.

My question is, are the 3 values on `process.memoryUsage()` sufficient to monitor memory usage and check for memory leaks? What is a good simple way to ensure there are no memory leaks? I am looking for a free and open source solution.

Right now, I am just graphing to the 3 values over time and doing a visual inspection.

**Comment by addaleax** [comment]
I think those values should be sufficient to give you the information of how much memory your process actually uses up, and if there is a memory leak, to tell you whether it’s coming from JS code (i.e. happening in the heap) or native code.

**Comment by ORESoftware** [comment]
@addaleax native code memory leak would only effect rss?

**Comment by addaleax** [comment]
@ORESoftware That’s what I would expect, yes.

By the way, if you would like more detailed memory records, there are also [`v8.getHeapStatistics()`](https://nodejs.org/api/v8.html#v8_v8_getheapstatistics) and [`v8.getHeapSpaceStatistics()`](https://nodejs.org/api/v8.html#v8_v8_getheapspacestatistics).

**Comment by ORESoftware** [comment]
ah, I didn't know about those other stats calls, will investigate

**Comment by kunalspathak** [comment]
Also, I think those APIs will give you v8's memory leak information and not something if node itself is leaking memory. For that you might want to collect heap allocation call-stack profiling.

**Comment by ORESoftware** [comment]
@kunalspathak thx do you have an example of that?

**Comment by kunalspathak** [comment]
Example of leak or heap allocation call stack?

**Comment by ORESoftware** [comment]
@kunalspathak I just meant an example of collecting heap or stack information

**Comment by addaleax** [comment]
Fwiw the RSS size is really independent from what V8 reports or sees, if there is a (relevant) memory leak it should show up in that information.

**Comment by kunalspathak** [comment]
@addaleax  is right. RSS size coming from `process.memoryUsage` should be sufficient enough to get a sense if leak is happening (also possible by just inspecting the task manager).

However to find out what is leaking, I would do some profiling. Chrome F12 memory analysis tools gives a good sense of memory leak and there are lot of blogs out there that walks through step by step usage.
