### ISSUE TITLE
Settimeout again sending response if response sent already.

### ISSUE THREAD

**Issue by saurav2501** [nodejs/help#768]
Version: 6.10.2
Platform: windows
My request timeout used to send socket timeout response to the browser. But I have one more settimeout function which used to send its response even after the response is sent already by request timeout. How can I block settimeout from sending response again.

**Comment by bnoordhuis** [comment]
Can you post some example code?

**Comment by lordKnighton** [comment]
Hey @saurav2501 Did you fix this yet?

**Comment by saurav2501** [comment]
No it's not fixed yet.

**Comment by bnoordhuis** [comment]
You never posted that example code I asked for.  I'll close this until you do.
