### ISSUE TITLE
Node.js throws error 'cannot find module' which is the folder its running from.

### ISSUE THREAD

**Issue by MrSpikeYT** [nodejs/help#771]
I'm using Node.js (latest version at my time) on Windows 7. Node used to work fine until now. Whenever I do node . to run node, I get the error ```
C:\ProjectStructure\Files>node .
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\ProjectStructure\Files'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
A blank file also will not solve. Any help is appreciated.

**Comment by MrSpikeYT** [comment]
If you must know,  \Files is the file in which it is running from.

**Comment by tniessen** [comment]
What files are inside `C:\ProjectStructure\Files`? Is there either an `index.js` file or a `package.json` with a correct `main` attribute?

**Comment by MrSpikeYT** [comment]
Ah thanks. I forgot the package.json.
