### ISSUE TITLE
rss / heapUsed / heapTotal figures

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#772]
I am on Node 8 here, I have a TCP server running, and I have plotted RSS, heapTotal and heapUsed, in red, blue and green respectively, the x axis is time in milliseconds starting at 0 when the data was first collected. The data was captured via ```process.memoryUsage()```.

Can anyone explain why we see heapUsed drop precipitously every 100,000ms or so?

I am just curious what this means and if this a normal looking plot.
The data was captured over 900,000 ms, which is 900 seconds or about 15 minutes.

<img width="1131" alt="screenshot 2017-08-03 21 39 29" src="https://user-images.githubusercontent.com/11139560/28954499-9e8397fa-7894-11e7-9880-d3a7ce917d83.png">

**Comment by bnoordhuis** [comment]
That's the garbage collector doing its work.  The Rocky Canyon-like profile is normal, yes.

**Comment by ORESoftware** [comment]
Yeah I would have thought the GC would do things more frequently - I would have guessed every 500ms, not every 100,000ms, but I guess not

**Comment by bnoordhuis** [comment]
The frequency is a function of the max heap size.  If you restrict it with `--max_old_space_size=128`, the intervals will be shorter but your application will spend proportionally more CPU time scanning for garbage - not a good trade-off if your system has plenty of memory.

**Comment by danielkhan** [comment]
If you want to learn more about Node's GC, I blogged about it some time ago https://www.dynatrace.com/blog/understanding-garbage-collection-and-hunting-memory-leaks-in-node-js/

**Comment by ORESoftware** [comment]
thanks all good info

**Comment by ORESoftware** [comment]
@danielkhan  "Unlike platforms like PHP, Node.js applications are long-running processes." I thought PHP has some centralized server that forks a process for each request, so the centralized server is still long running?

**Comment by tniessen** [comment]
> I thought PHP has some centralized server that forks a process for each request, so the centralized server is still long running?

Even though there have been a lot of changes to the infrastructure (especially when it comes to persistent memory and execution caches), the basic concept of PHP is to execute scripts independently of each other whenever an HTTP request is received. The simplest possible implementation would start one PHP process per HTTP request (luckily, there are far more advanced configurations available). In other words: Even though the webserver (and maybe some fancy fcgi server etc) are "long running", the program implementing the application logic (= PHP) is not. This is a fundamental difference to Node.js where the webserver process persists across requests without any special configuration, just as you would expect. Many concepts are completely different if you compare Node.js to PHP, e.g. when loading configuration files, computing something in the background or working with databases (most PHP applications will create new database connections for each request!).
