### ISSUE TITLE
Multiplexing of stdout given multiple grandchildren

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#773]
Say we fork a child like so:

```js
const k = cp.spawn('node',['./k.js']);
k.stdout.pipe(someParser());
```

if k in turn spawns children and so on and so forth, will the stdout from the grandchildren be guaranteed to reach the grandparent as complete lines, or will lines of stdout be mixed up, making parsing pretty much impossible? 

If the question is not clear, I can elaborate.

My guess, is that with multiple grandchildren, the stdout that reaches `someParser()` will be mixed up, and will not be able to piece together complete lines of stdout, but hopefully I am wrong about that.

I assume the answer to the question has to do with the technicalities of node.js streams...and I would expect/hope that node.js streams would mimic the behavior of a unix system and the unix shell?

**Comment by bnoordhuis** [comment]
> My guess, is that with multiple grandchildren, the stdout that reaches someParser() will be mixed up, and will not be able to piece together complete lines of stdout, but hopefully I am wrong about that.

Nope, you're right, output can be interspersed and that isn't particular to Node.js.

Small writes (up to a few hundred bytes, a few kilobytes on some operating systems) will be atomic but larger ones won't be.

**Comment by ORESoftware** [comment]
thanks that makes sense, useful info, will close
