### ISSUE TITLE
How to store data

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#774]
Hi all, I am writing my first app in Node which will crawl a website and respond to found information by sending e-mails, if that information meets specific requirements. 
Now the thing is:

I want it to send 1 e-mail for each identical post that meets the requirements mentioned above. My programme succesfully stores data that it scans into arrays that are assigned to variables.  I want it to store which posts it has already scanned so it wont notify me a second time with the same information (it crawls one and the same page every 2 minutes) . Obviously if I store this into an array that works fine. But I also want to turn the programme off every now and then and review the information stored. How do I do this? 
I want to save the state of vars/arrays into another (.js) file preferably.

Now the only way to solve this issue that comes to my mind is:
log my vars/arrays to a .txt file using 
```javascript
node index.js >myfile.txt
```

and then using  fs.readFileSync to read that file and checking for the presence of certain values. But this feels like a very bad solution.

Can anybody point me into the right direction for this issue?

Greets

**Comment by leesei** [comment]
Using plaintext is indeed a bad choice.
You could use "light weight database":
- [levelup](https://github.com/Level/levelup), backed by LevelDB
- [sqlite](https://github.com/kriasoft/node-sqlite)/[sqlite3] backed by sqlite

**Comment by WAINGOR** [comment]
Hi leesei and thank you so much for your effort in helping me. I will keep in mind this advice. I have also heard I can use 
```javascript
fs.writeFileSync('data.json', 'utf-8', JSON.stringify(data, null, 2))
```
which seems like a solid solution as well

**Comment by vsemozhetbyt** [comment]
@WAINGOR If you need your JSON only for machine-reading and not for human-reading, you can use just this:
```js
fs.writeFileSync('data.json', JSON.stringify(data));
```
which reduses the file size and reading/parsing time.

Note that encoding argument should be the last one and can be omitted ('utf-8' is default encoding). See https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options.

**Comment by WAINGOR** [comment]
Wow thats very useful (this is just for machines)! Just 1 more question: does this function say that the whole programme will output all data into the specified file? Or only that which is specified within the .writeFileSync function?

**Comment by vsemozhetbyt** [comment]
@WAINGOR This will dump only the content of the `data` variable. This will work fine if `data` contains only values appropriate for JSON (no functions, for example). While you store an array/object with strings/numbers/booleans, you will be OK.

**Comment by vsemozhetbyt** [comment]
To retrieve the data back you need this:
```js
const data = JSON.parse(fs.readFileSync('data.json', utf8'));
```

**Comment by WAINGOR** [comment]
Thanks this rlly helped me a lot

**Comment by tniessen** [comment]
The type of persistent storage you should choose really depends on your data. Small datasets which don't require a lot of concurrent modification can be stored as JSON, CSV, YAML or whichever format you like in regular files. Bigger datasets should usually be stored in databases (e.g. SQL-based relational databases, I personally tend to use SQLite / MySQL / PostgreSQL, even though some other non-relational DBMSs have become quite popular). Both file storage and databases allow object serialization with suitable libraries, but those are advanced concepts, so you might want to start with simple files :)

Closing as answered.
