### ISSUE TITLE
WHEN RUNNING DOCKER NODE Empty reply from server from node server

### ISSUE THREAD

**Issue by ravindra11** [nodejs/help#776]
root@docker:/dd/Golkonda# ### curl -v 0.0.0.0:8000

Rebuilt URL to: 0.0.0.0:8000/
Trying 0.0.0.0...
TCP_NODELAY set
Connected to 0.0.0.0 (127.0.0.1) port 8000 (#0)
GET / HTTP/1.1
Host: 0.0.0.0:8000
User-Agent: curl/7.52.1
Accept: /
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS, HEAD
< Access-Control-Expose-Headers: X-TOTAL-COUNT
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization,X-TOTAL-COUNT, X-access-token
< Content-Type: application/json; charset=utf-8
< Content-Length: 38
< ETag: W/"26-l3Z+0Y3Iw1AeZG4itDbyEtj3weg"
< Date: Tue, 08 Aug 2017 14:05:02 GMT
< Connection: keep-alive
<

Curl_http_done: called premature == 0
Connection #0 to host 0.0.0.0 left intact
{"message":"Welcome to talentscreen!"}
AND WHEN I'm SENDING REQ AS

root@docker:/dd/Golkonda# ### curl -v 0.0.0.0:8000/v1

Trying 0.0.0.0...
TCP_NODELAY set
Connected to 0.0.0.0 (127.0.0.1) port 8000 (#0)
GET /v1 HTTP/1.1
Host: 0.0.0.0:8000
User-Agent: curl/7.52.1
Accept: /
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS, HEAD
< Access-Control-Expose-Headers: X-TOTAL-COUNT
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< X-DNS-Prefetch-Control: off
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Content-Type: text/html; charset=utf-8
< Content-Length: 32
< ETag: W/"20-d8dubzYyMc8/DWaWgI+PPe5qydY"
< Vary: Accept-Encoding
< Date: Tue, 08 Aug 2017 14:06:50 GMT
< Connection: keep-alive
<

Curl_http_done: called premature == 0
Connection #0 to host 0.0.0.0 left intact
This is talentscreen version one
## BUT WHEN SENDING AS  ## curl -v 0.0.0.0:8000/v1/common/types

 GETTING Empty reply from server

Trying 0.0.0.0...
TCP_NODELAY set
Connected to 0.0.0.0 (127.0.0.1) port 8000 (#0)
GET /v1/common/types HTTP/1.1
Host: 0.0.0.0:8000
User-Agent: curl/7.52.1
Accept: /
Curl_http_done: called premature == 0
Empty reply from server
Connection #0 to host 0.0.0.0 left intact
curl: (52) Empty reply from server..

please any one help me. thanks

**Comment by lordKnighton** [comment]
Any luck with this yet?

**Comment by ravindra11** [comment]
Nothing, my request doesnt went to database in container,upto database
connection where i have written console requests are printing.

**Comment by jolson88** [comment]
Silly question. Are you actively on any network connection when this happens or recently made any network changes (like docker container started at work but now running at home after commute)? I've run into this in the past when developing on-the-go on my MBP and not connected to any active network, especially when the docker container is still running from when I was connected before. I've also had reboots work as a hokey fix for me in the past.

I had guessed at the time that it was something about the docker networking bridge that gets all cattywampus with network changes or across sleep/hibernate transitions on the machine.
