### ISSUE TITLE
Discord.js problems, please help!

### ISSUE THREAD

**Issue by ShoopDieDoo** [nodejs/help#779]
* **Node.js Version**: 8.3.0 (tried 6.11.2 LTS too)
* **OS**: Windows 10
* **Scope**: install
* **Module**: node-gyp

Hey everyone, I am trying to make a discord bot but am having some problems. I used the code `npm install --save discord.js` but then there was warnings of not having some files (`erlpack@hammerandchise1/er1pack`,
`node-opus@^0.2.5`, `opusscript@^0.0.3`, `sodium@^2.0.1`, `libsodium-wrappers@^0.5.1`, `uws@^0.14.1` and one of which I don't remember the name)
 but i installed a few of them with `npm install` and it worked with a few. now I have a few left that wont install (I tried starting with admin rights etc.), they are: `erlpack@hammerandchise1/er1pack`, `node-opus@^0.2.5` and `sodium@^2.0.1` 
![image](https://user-images.githubusercontent.com/30981341/29251077-2cd02336-804f-11e7-9ae3-a6591fd2c978.png)

I tried doing `npm install erlpack`, `npm install node-opus` and `npm install sodium` (Afterwards i tried installing the exact versions too) but they all gave me errors.
* `erlpack` gave me this:
![image](https://user-images.githubusercontent.com/30981341/29251046-72f3e8a8-804e-11e7-9db3-4bde79afaa69.png)

* `node-opus` gave me this: 
![image](https://user-images.githubusercontent.com/30981341/29251053-a3928276-804e-11e7-95ae-3a5563a2d9b6.png)

* `sodium` gave me this: 
![image](https://user-images.githubusercontent.com/30981341/29251059-cbd3932e-804e-11e7-9126-67c7dd911d12.png)
and if u scroll further: 
![image](https://user-images.githubusercontent.com/30981341/29251061-de298b5a-804e-11e7-9c37-d72be03d2201.png)

So I saw that it said that i had to add `--scripts-prepend-node-path` and tried it on all, and it still didn't work. I really don't know what to do!

<sub>refack: formatted</sub>

**Comment by refack** [comment]
@ShoopDieDoo hello, it seems like you are having trouble with the package that compiles native modules - `node-gyp`. It's use on Windows requires proper installation of several pre-requisites, in this case I think your Windows SDK is not properly configured.
There's an Ok guide at https://github.com/nodejs/node-gyp#on-windows
and some more details resolved issues like: https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

**Comment by ShoopDieDoo** [comment]
@refack This worked, But now I still have a problem. Im making the discord bot with visual studio, but it doesnt recognise the discord.js folder that was installed (thats what i think at least.), since I'm trying to make it say Discord.Client and Client should be recognised as Client.js in the discord.js folder but it doesnt. Do i have to place the discord.js folder anywhere else?

**Comment by ShoopDieDoo** [comment]
Nevermind
i made a mistake

**Comment by refack** [comment]
@ShoopDieDoo happy to have helped with the compilation errors.
When working when Visual Studio make sure you have `node.js` support installed:
<sub>VS2017 installer</sub>
![image](https://user-images.githubusercontent.com/96947/29272017-35acef20-80cc-11e7-8cfa-dd51111500d4.png)
But anyway it's probably not the best tool for the job. [VSCode](https://code.visualstudio.com/docs/nodejs/nodejs-tutorial) is very popular for working with node.js, and I personally like JetBrains' [Webstorm](https://www.jetbrains.com/webstorm/download/) (or even the free [Pycharm community edition](https://www.jetbrains.com/pycharm/download/#section=windows))

I'm closing this issue, but feel free to reopen if you have follow up questions.
