### ISSUE TITLE
how to deploy nodejs rest api with express framework on production server windows

### ISSUE THREAD

**Issue by nimishgoel56** [nodejs/help#780]
* **Latest node version**:
* **Windows**:
* **ScopeDeployement**:

I have created a node.js rest api created using express framework for routing. I have used [https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4 ](https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4)Now I want to deploy that rest api on actual production server. How to achieve that thing.   I have gone through below links.  

 [https://stackoverflow.com/questions/45600952/deploy-node-js-application-with-express-framework-on-production-mode](https://stackoverflow.com/questions/45600952/deploy-node-js-application-with-express-framework-on-production-mode) Only for linux. I need for windows. 

 [https://stackoverflow.com/questions/35064933/deploying-nodejs-express-rest-api-to-windows-10-iot](https://stackoverflow.com/questions/35064933/deploying-nodejs-express-rest-api-to-windows-10-iot) -- a little bit similar  problem but no solution  

[https://stackoverflow.com/a/38652869/2810015](https://stackoverflow.com/a/38652869/2810015)  -- this said to run npm start on production server after copying all of  the files on server. But this is not working fine either.   Any help will be highly useful.
-- | --

**Comment by refack** [comment]
Hello @nimishgoel56 
Your question is relatively vague... There are many different factors when copying a project from one computer to another, but the ___minimun___ steps are:
1. make sure you have a working version of `node` and `npm` on the target computer (preferably the same version you developed with).
2. copy your code to the target
3. if you used `npm` modules and have a `package.json` file run `npm i` (optionally with `--production`)
4. run node the same as you did in development (e.g. `node index.js`)

After that there are a multitude of thing to consider for a system in production (process longevity, logging, tracing, firewalls, etc.). Maybe a blog post like http://goldbergyoni.com/checklist-best-practice-of-node-js-in-production/ ccan help.

**Comment by refack** [comment]
Hi @nimishgoel56, any progress?

**Comment by nimishgoel56** [comment]
Refack, 
I was able to upload on the production server by following few steps, sorry for the late reply and thanks for the help.

**Comment by refack** [comment]
@nimishgoel56 so I'm closing this issue.
Feel free to reopen or add any new information you might have.

**Comment by theboman** [comment]
could you post your steps for running node on windows

**Comment by kiru86** [comment]
@nimishgoel56 could you share the steps for a running node on windows?
