### ISSUE TITLE
Re:Node JS installation steps and Usage in Visual studio 2015

### ISSUE THREAD

**Issue by rpremkumar10** [nodejs/help#782]
#Hi 
Im very new to .net development.
I need step by step installation of Node.js for visual studio.
Also I need how to use node.js in visual studio with step by step process and some sample coding.
please help me

**Comment by tniessen** [comment]
> Im very new to .net development.

Could you please elaborate how this is relevant to Node.js?

>  I need step by step installation of Node.js for visual studio.

Did you read through [this page](https://www.visualstudio.com/vs/node-js/)?

If that is not what you are looking for, what do you want to achieve? If you need a decent IDE for JavaScript, you might want to use [Visual Studio Code](https://code.visualstudio.com/docs/nodejs/nodejs-tutorial).

**Comment by lordKnighton** [comment]
@rpremkumar10 Are you asking about Nodejs & VScode or actual VisualStudio & Nodejs? 
Im gonna close this soon, if no response. I will assume you already solved your issue.

**Comment by tniessen** [comment]
Closing due to lack of follow-up information.
