### ISSUE TITLE
Set openssl context flags

### ISSUE THREAD

**Issue by chaen** [nodejs/help#788]
* **Node.js Version**: v6.11.2
* **OS**: Fedora 25
* **Scope **: code

Hi,

I am trying to make a very dummy https server that checks the client certificate. It was quite straight forward, using this as a source of information https://engineering.circle.com/https-authorized-certs-with-node-js-315e548354a2

Now, I want to push it slightly further and would like to allow proxy certificates (https://www.ietf.org/rfc/rfc3820.txt)

Openssl supports that, but requires a context flag to be set: https://github.com/openssl/openssl/blob/master/doc/HOWTO/proxy_certificates.txt

```
 - if the application directly calls X509_verify_cert(), it can first call:
   X509_STORE_CTX_set_flags(ctx, X509_V_FLAG_ALLOW_PROXY_CERTS);
```
I unfortunately did not see any way to pass these flags to node.js

However, as per https://github.com/nodejs/node/blob/master/deps/openssl/openssl/crypto/x509/x509_vfy.c#L620 I can just set an environment variable, and it works. 

But I'd rather propagate the flag from the node.js code.

Is there any way to do that ?

Thanks a lot

**Comment by bnoordhuis** [comment]
There is currently no way to set X509_STORE_CTX flags.

I don't know how easy it would be to add.  Node.js does not call `X509_verify_cert()` directly and it operates on X509_STORE instances, not X509_STORE_CTX.

Setting the flag on the X509_STORE effectively makes it a global setting.  It sounds like that might be good for your particular use case but it is frowned upon in general.

**Comment by chaen** [comment]
Oh, OK. I did not know it was considered a bad practice. Would you mind explaining why ?
In any case, I have the environment variable as a fallback solution, so I'm fine in any case.

**Comment by bnoordhuis** [comment]
It's not a bad practice per se for an application where you control all the code,  but global flags (or rather: the global change in behavior they effect) sometimes interact poorly with third-party libraries.  Libraries assume the world works a certain way but flipping the flag changes that under their feet.

**Comment by chaen** [comment]
I see. Well,  I suppose this issue can be closed. Thanks a lot !
