### ISSUE TITLE
Error.name vs Error.code

### ISSUE THREAD

**Issue by stouf** [nodejs/help#789]
* **Node.js Version**: >=8.3.0
* **OS**: Any
* **Scope (install, code, runtime, meta, other?)**: Best practice
* **Module (and version) (if relevant)**: Errors

There seem to be an ongoing effort in node.js for getting any error thrown by the code functions to have a `code` property (see [this pull request](https://github.com/nodejs/node/pull/14724) or [this issue](https://github.com/nodejs/node/issues/13937) for example).

As a node.js user, I'm used to use the `name` property to programmatically identify errors in the code I write. For example,

```js
// user.js
async function getByEmail(email) {
  const resultSet = await db.getBy('user', { email });
  if (resultSet.length === 0) {
    const error = new Error(`No user with the email ${email} could be found`);
    error.name = 'EMAIL_NOT_FOUND';
    throw error;
  }
  return resultSet;
}


// In some business logic code
user.getByEmail(inputEmail)
  .then((resultSet) => {
    return `Are you one of those? ${resultSet.map(x => x.name).join(',')}`;
  })
  .catch((error) => {
    if (error.name === 'EMAIL_NOT_FOUND') {
      return 'No user could be found for the input email';
    }
    throw error;
  });
```

Although the `name` property is not mentioned in [Node.js documentation about Errors](https://nodejs.org/dist/latest-v8.x/docs/api/errors.html), it is a [standard property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name) and [Node.js documentation about Errors](https://nodejs.org/dist/latest-v8.x/docs/api/errors.html) tells us the following:

> All JavaScript and System errors raised by Node.js inherit from, or are instances of, the standard JavaScript [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) class and are guaranteed to provide at least the properties available on that class.

Now that the [`code` is property is mentioned in Node.js documentation](https://nodejs.org/dist/latest-v8.x/docs/api/errors.html#errors_error_code), I am wondering which of `code` and `name` I should use *as a user* for programmatically identifying errors.

Is there anything one should be aware of? Does the node.js team encourage for the use of one over the other?

**Comment by jasnell** [comment]
For core, especially given that we are still in the process of migrating errors, use `code` first, but if code is not present, use `name`

**Comment by jasnell** [comment]
Answer part 2 .... unfortunately many errors cannot be determined just by their name and require looking into the error message to understand what happened... which is why we're introducing `code`

**Comment by stouf** [comment]
Thanks for responding :)

I see. What about it for people building their own applications in Node.js and aiming at programmatically identifying the errors their own code creates? Would the node.js team encourage using `code` or `name` for that? Or maybe it's just up to the developers and there is no such thing as good practice for that?

**Comment by tniessen** [comment]
Our goal is to make the `code` property the optimal way to distinguish and identify errors.

> aiming at programmatically identifying the errors their own code creates?

We are working on a good error handling strategy. There has already been a similar question at https://github.com/nodejs/node/issues/15057 and the discussion is being continued in https://github.com/nodejs/CTC/issues/173.

**Comment by stouf** [comment]
@tniessen Awesome, thanks for the reference 👍
