### ISSUE TITLE
Installing nodejs v4.x.x without using sudo command

### ISSUE THREAD

**Issue by neophoenix123** [nodejs/help#79]
I know this is rather basic, but is there a way to re configure permission settings so I stop getting the common error throws when developing in Ember-cli? Or better, is there simply a way to use other extraction methods from sources? Ex. use "curl" or "wget" in an instance to download on my ubuntu 15.10 machine?

**Comment by TheAlphaNerd** [comment]
hey @neophoenix123 what OS are you using?

How did you install node?

**Comment by kelthenoble** [comment]
have you tried the node.js org, it doesn't require  sudo command.

**Comment by neophoenix123** [comment]
Right I am just unclear on what to do with the package once it is
downloaded to my 'Downloads' folder. How to I actually get it installed on
the terminal?

On Tue, Jan 19, 2016 at 6:17 PM, kelvin knighton <notifications@github.com>
wrote:

> have you tried the node.js org, it doesn't require sudo command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/79#issuecomment-173044811>.
>



-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by kelthenoble** [comment]
So once you go & download node.js from the nodejs.org 
> you should then click on it & then it will open an interface: node.js installer
then continue with the installer, once it's finish

go to your terminal and type
> node -v 

to make sure node is on your system. And if it is there, then congrats you have a fresh installation of node.js. If it's not there let me know.

**Comment by neophoenix123** [comment]
Hmm no install er it only asks me where I want to extract the files/

On Tue, Jan 19, 2016 at 7:24 PM, kelvin knighton <notifications@github.com>
wrote:

> So once you go & download node.js from the nodejs.org
>
> you should then click on it & then it will open an interface: node.js
> installer
> then continue with the installer, once it's finish
>
> go to your terminal and type
>
> node -v
>
> to make sure node is on your system. And if it is there, then congrats you
> have a fresh installation of node.js. If it's not there let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/79#issuecomment-173063238>.
>



-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by kelthenoble** [comment]
show me a pic

**Comment by kelthenoble** [comment]
so this should be in your downloads. 
![screen shot 2016-01-19 at 6 39 59 pm](https://cloud.githubusercontent.com/assets/1773260/12438466/fa9c0154-bedb-11e5-8e26-c0a92cb91fcc.png)

and then click on it, it opens to this. 
![screen shot 2016-01-19 at 6 40 23 pm](https://cloud.githubusercontent.com/assets/1773260/12438472/01866798-bedc-11e5-92c4-03af14a7def5.png)

**Comment by neophoenix123** [comment]
​Well I just reinstalled Ubuntu so no good there..​

On Tue, Jan 19, 2016 at 7:33 PM, George Awad <gawad@eptent.com> wrote:

> Hmm no install er it only asks me where I want to extract the files/
>
> On Tue, Jan 19, 2016 at 7:24 PM, kelvin knighton <notifications@github.com
> > wrote:
>
>> So once you go & download node.js from the nodejs.org
>>
>> you should then click on it & then it will open an interface: node.js
>> installer
>> then continue with the installer, once it's finish
>>
>> go to your terminal and type
>>
>> node -v
>>
>> to make sure node is on your system. And if it is there, then congrats
>> you have a fresh installation of node.js. If it's not there let me know.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nodejs/help/issues/79#issuecomment-173063238>.
>>
>
>
>
> --
> *George Awad, BS.BA <http://BS.BA>*
> *Epic Proportions Software inc.*
> *gawad@eptent.com <gawad@eptent.com>*
> *http://epicproportionstour.com <http://epicproportionstour.com>*
>
>
>


-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by neophoenix123** [comment]
I do not have the option in ubuntu 15.10 to hit a button and install. I
need to use the terminal without sudo privileges to do so. That's my
dilemma!

On Tue, Jan 19, 2016 at 7:40 PM, kelvin knighton <notifications@github.com>
wrote:

> so this should be in your downloads.
> [image: screen shot 2016-01-19 at 6 39 59 pm]
> <https://cloud.githubusercontent.com/assets/1773260/12438466/fa9c0154-bedb-11e5-8e26-c0a92cb91fcc.png>
>
> and then click on it, it opens to this.
> [image: screen shot 2016-01-19 at 6 40 23 pm]
> <https://cloud.githubusercontent.com/assets/1773260/12438472/01866798-bedc-11e5-92c4-03af14a7def5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/79#issuecomment-173065263>.
>



-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by kelthenoble** [comment]
Ok to be clear, what OS are your running? And give me the version of it.

**Comment by neophoenix123** [comment]
Great thank you...Ubuntu 15.10

On Tue, Jan 19, 2016 at 8:24 PM, kelvin knighton <notifications@github.com>
wrote:

> Ok to be clear, what OS are your running? And give me the version of it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/79#issuecomment-173073983>.
>



-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by kelthenoble** [comment]
You're welcome man. Let me know if you need anymore help.

**Comment by neophoenix123** [comment]
Well yes I gave you my ubuntu and version. Can you help me install node
correctly?


On Tue, Jan 19, 2016 at 11:58 PM, kelvin knighton <notifications@github.com>
wrote:

> You're welcome man. Let me know if you need anymore help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/79#issuecomment-173111884>.
>



-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by kelthenoble** [comment]
alright here you go - there is a section about ubuntu -v 15.10 

http://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm-for-ubuntu-14-04-lts

**Comment by neophoenix123** [comment]
And last but not least if this doesn't seem to work since sudo is still
involved, any way to remove absolutely everything and start over? I thank
you greatly for the time you are taking to help me by the way!

On Wed, Jan 20, 2016 at 12:50 AM, kelvin knighton <notifications@github.com>
wrote:

> alright here you go - there is a section about ubuntu -v 15.10
>
>
> http://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm-for-ubuntu-14-04-lts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/79#issuecomment-173121322>.
>



-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by kelthenoble** [comment]
Of course man. And don't worry, it was no problem. For now i'm gonna close this issue, but don't hesitate to further comment, if you need more help.

**Comment by neophoenix123** [comment]
Alright I will give this a shot. Also looked at a site which seems relevant
to my version
http://eureka.ykyuen.info/2014/05/07/ubuntu-install-node-ver%C2%ADsion-man%C2%ADager-globally-for-all-users/

I will try both and thank you again. Happy coding!!

On Wed, Jan 20, 2016 at 12:55 AM, kelvin knighton <notifications@github.com>
wrote:

> Closed #79 <https://github.com/nodejs/help/issues/79>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodejs/help/issues/79#event-520062847>.
>



-- 
*George Awad, BS.BA <http://BS.BA>*
*Epic Proportions Software inc.*
*gawad@eptent.com <gawad@eptent.com>*
*http://epicproportionstour.com <http://epicproportionstour.com>*

**Comment by kelthenoble** [comment]
:+1: Happy coding :100:

**Comment by TheAlphaNerd** [comment]
You could try using nvm
