### ISSUE TITLE
A question about highWaterMark in readable stream module

### ISSUE THREAD

**Issue by linxiaowu66** [nodejs/help#794]
* **Node.js Version**: 8.4.0
* **OS**:ubuntu 17.04
* **Scope (install, code, runtime, meta, other?)**: source code
* **Module (and version) (if relevant)**:readable stream

In the official document: [Stream](https://nodejs.org/api/stream.html), this section has the description as follows:

    Once the total size of the internal read buffer reaches the threshold specified by highWaterMark, the 
    stream will temporarily stop reading data from the underlying resource until the data currently buffered 
    can be consumed (that is, the stream will stop calling the internal readable._read() method that is 
    used to fill the read buffer).

I just want to sure one thing: this action of `the stream will temporarily stop reading data` is automatically ?

As I read the fs.js source code, and I find the stop reading action maybe is manually. So if it is, we should be implement this temporarily stop action in our code ?

Anyone who can help me to solve this confusion.

Thanks.

**Comment by tniessen** [comment]
This behavior is internal and does not require users to implement any logic.

**Comment by linxiaowu66** [comment]
@tniessen 
  Thanks for your answer, But I can not find any code to implement this logic. Can you show me the code?  Thanks a lot.

**Comment by tniessen** [comment]
This behavior is implemented in [lib/_stream_readable.js](https://github.com/nodejs/node/blob/c3c045aea06a4d58b4af5c1bdc4f8aebbe5425e4/lib/_stream_readable.js).

**Comment by privateOmega** [comment]
@tniessen Would the reading stop on its own? Because I thought highWaterMark was just an indicator and not anything enforceable, so user would know to stop pushing to stream when it returns false. Correct me if I am wrong. I have just started reading upon the concept of streams and is in an attempt to build one.
