### ISSUE TITLE
IRC Channel Help

### ISSUE THREAD

**Issue by tkambler** [nodejs/help#795]
Who is in charge of moderating the #Node.js IRC channel. Is there an email address for related issues at which someone can be contacted?

**Comment by gibfahn** [comment]
Not sure who's in charge, but maybe some people from https://github.com/nodejs/community-committee/issues/33 or https://github.com/nodejs/community-committee/issues/20 would be able to help.

I guess maybe cc/ @rachelnicole @hackygolucky @Fishrock123

**Comment by rachelnicole** [comment]
I'm a moderator @tkambler, what do you need help with?

**Comment by tkambler** [comment]
@rachelnicole I rarely (if ever) get involved in Node discussions of a "political" flavor, but as you are well aware, some fervent discussions are going on right now. Nothing more needs to be said about that. Earlier this morning, I posted a link in the #Node.js IRC channel to a discussion regarding a recent CoC violation report that had some bearing on those discussions. Again - no need to get into that, either.

All that said, I have been banned from the channel without explanation. One is hardly necessary at this point, as I can gather it was likely due to topics of a not-strictly-technical nature not being allowed (please correct me if I'm wrong). I am aware of the following document regarding trolling in the channel, which I support and *thought* I was abiding by:

http://blog.izs.me/post/30036893703/policy-on-trolling

Long-story short: I can appreciate the fact that stuff of a non-technical nature can muddy the waters in an IRC channel. If that's the case, then I'm certainly happy to oblige. However, I have kindly reached out to AvianFlu who seems to be ignoring me.

I kindly request a re-instatement or a simple acknowledgement of "nope - you're perma-banned."

Thank you. :)

**Comment by rachelnicole** [comment]
@tkambler yes its because you just dropped in the topic unreleated to any technical discussion that was going on. I can unban you, as it should have just been a warning. Please keep that in mind for the future.

**Comment by tkambler** [comment]
@rachelnicole Fair enough. Am happy to abide by whatever rules are in play, so long as I'm aware of them. Thank you.
