### ISSUE TITLE
Object.defineProperty is not working in node.js 

### ISSUE THREAD

**Issue by muhammadfaizan** [nodejs/help#798]
* **Node.js Version**:  v8.1.4,
* **OS**:  Windows 10 x64
* **Scope**:  Command line

```js
let a = {};
Object.defineProperty(a, "name", { value: "Faizan" } ); 
```
This doesn't set _name_ property in my object a;

**Comment by vsemozhetbyt** [comment]
@muhammadfaizan I cannot reproduce with Node.js 8.4.0:
```js
> let a = {};
undefined
> Object.defineProperty(a, "name", { value: "Faizan" } );
{}
> a.name
'Faizan'
```
Can it be that you check the property in some loop or serialization that need `enumerable` key to be `true`? It is `false` [by default](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty).

**Comment by muhammadfaizan** [comment]
nope i checked by simply typing variable name

**Comment by muhammadfaizan** [comment]
Here is a screenshot

![alt text](https://ibb.co/d7hAnQ "Nodejs Define Property snapshot")

**Comment by muhammadfaizan** [comment]
ok it works by providing key, but its not enumerable. its default value is 
`enumerable: false `

**Comment by vsemozhetbyt** [comment]
@muhammadfaizan If you want it to be enumerable, you can set this key explicitly:
```js
Object.defineProperty(a, "name", { value: "Faizan", enumerable: true } );
```
