### ISSUE TITLE
DNS Settings

### ISSUE THREAD

**Issue by tahasiddiqui123** [nodejs/help#80]
Hello, I am new to node.js and i just want to get the DNS server address of both lan and wifi connected interfaces.
How can i get these two different DNS server addresses at the same time.

**Comment by subfuzion** [comment]
@tahasiddiqui123 Take a look at the docs on [os.networkInterfaces()](https://nodejs.org/api/os.html#os_os_networkinterfaces) if you want to enumerate the interfaces on your system (on my Mac `en0` is my wifi lan interface and `en1` is my wired lan interface).

If you just want to get the first network's local IPv4 address, you could use [dns.lookup()](https://nodejs.org/api/dns.html#dns_dns_lookup_hostname_options_callback) starting with this example and fine tune it for your needs:

```
var dns = require('dns');
var os = require('os');
var hostname = os.hostname();

dns.lookup(hostname, { family: 4 }, function(err, addr, fam) {
  console.log(addr);
});
```

Let me know if this helps so I can close the ticket.

**Comment by tahasiddiqui123** [comment]
Yes,Thanks so much for the help.
