### ISSUE TITLE
With node-cache module, not able to get the data after set.

### ISSUE THREAD

**Issue by ketans207** [nodejs/help#801]
* **Node.js Version**: v6.10.3
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: node-cache

I am trying to implement the caching with Node JS. using node-cache module.
I am using below code to set the data in to cache and get the data from cache.

```js
const NodeCache = require( "node-cache" );
const myCache = new NodeCache( { stdTTL: 3000, checkperiod: 3000} );

obj = { my: "Special", variable: 42 };
myCache.set( "myKey", obj ); // Calling DB, fetch the data and set in to cache for first time when client requests.

value = myCache.get( "myKey" );
console.log('value: ',value);

console.log(JSON.stringify(myCache)); 
```

But once I set the data, next time when I am trying to get the data (Without setting the data, as I already set it) then it gives me undefined value. When I print the cache I don't see the value(As per below example the value is { my: "Special", variable: 42 }).
So value is not persist in to cache. I have provided stdTTL as 3000 ms, so data should be available for 3000 ms but it is not available in to cache.

Do I need to set something with TTL or do we have other settings to fetch the saved value in cache?

**Comment by ORESoftware** [comment]
You may wish to file this issue with the `node-cache` author?

**Comment by gireeshpunathil** [comment]
#cat 801.js 
```js
const nc = require( "node-cache" )
const c = new nc ({stdTTL: 3,checkperiod:3})

console.log(c.getStats())

const o = {my:'Special',variable: 42}
c.set('key', o)

setTimeout(() => {
  const v = c.get('key')
  console.log(v)
  console.log(c.getStats())
}, 1000)

setTimeout(() => {
  const v = c.get('key')
  console.log(v)
  console.log(c.getStats())
}, 2000)

setTimeout(() => {
  const v = c.get('key')
  console.log(v)
  console.log(c.getStats())
}, 4000)
```
#node 801.js 
```trace
{ hits: 0, misses: 0, keys: 0, ksize: 0, vsize: 0 }
{ my: 'Special', variable: 42 }
{ hits: 1, misses: 0, keys: 1, ksize: 3, vsize: 160 }
{ my: 'Special', variable: 42 }
{ hits: 2, misses: 0, keys: 1, ksize: 3, vsize: 160 }
undefined
{ hits: 2, misses: 1, keys: 0, ksize: 0, vsize: 0 }
#
```

I don't see any issue with its documented functionality. However, please report any issues which you have outstanding on this with node-cache.

**Comment by aakhonbay** [comment]
You will lose your cache when you restart your server. It could be happening because you're running nodemon and making changes to your index.js or app.js files.
