### ISSUE TITLE
Array.prototype.concat.call is not a function

### ISSUE THREAD

**Issue by willin** [nodejs/help#802]
* **Node.js Version**: 8.4.0
* **OS**: OS X10.12.6

Test 1:

```js
const fn = Array.prototype.concat.call;

const test = (...args) => fn(...args);

console.log(test(1, 2, 3));
```

result:

```
const test = (...args) => fn(...args);
                          ^

TypeError: fn is not a function
```

---

Test 2:

```js
const fn = console.log; // Array.prototype.concat.call;

const test = (...args) => fn(...args);

console.log(test(1, 2, 3));
// 1,2,3
// undefined
```

why?

**Comment by vsemozhetbyt** [comment]
@willin Error message is rather misleading here, but there are some errors in your first fragment:

1. Unlike `console.log()` (which can work as a function without proper `this`), `.call` needs proper `this` that should be a function.
2. `.concat()` also needs proper `this` that should be an Array.

So we can fix both errors like this:

```js
const fn = Array.prototype.concat.call.bind(Array.prototype.concat);

const test = (...args) => fn(...args);

console.log(test([1], 2, 3));
```

See also: http://speakingjs.com/es5/ch17.html#_pitfall_losing_this_when_extracting_a_method

**Comment by willin** [comment]
oh, i see. but i still wonder if there is a way that can make `fn` flexable.

like:

```js
module.exports = (fn, ...args) => (_) => {
  if (typeof fn === 'function') {
    return fn(_, ...args);
  }
  return _;
};
```

**Comment by willin** [comment]
```js
const _ = require('./pipe');

const result = _([0].concat, [6, 7, 8, 9])([1, 2, 3, 4, 5]);

console.log(result);
// i want  [0,1,2,3,4,5,6,7,8,9] as result
```

```js
module.exports = function pipe(fn, ...args) {
  return function curry(_) {
    if (typeof fn === 'function') {
      return fn.apply(fn, [_, ...args]);
    }
    return _;
  };
};
```

current is 

```
[ [Function: concat], 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 ]
```

**Comment by lordKnighton** [comment]
I'm gonna close this, because @vsemozhetbyt responded & it appears he helped you. But if you still need help let us know.
