### ISSUE TITLE
Problem with loading .js, nothing happens.

### ISSUE THREAD

**Issue by Fastmancz** [nodejs/help#803]
* **Node.js Version - v8.4.0**:
* **OS - Windows 10 Pro**:
* **Scope (code, runtime)**:

Hello,

I'm new in Node.js. I do not know where is the problem, but It do not want to load it. 
![wr7l](https://user-images.githubusercontent.com/12295815/30006127-b6fc4a8c-90f1-11e7-85f7-856b5bf5be7a.png)
Nothing is happening, the cursor blinks. There is code:
https://pastebin.com/ZWU5mLZz

I'm waiting for the message:
console.log('succesfully logged on.');

I have the same problem on Linux. Can you somebody help me, where is the problem?
Thanks for answer.

**Comment by gibfahn** [comment]
Could you post the rest of the code? Your pastebin link contains `bot.js`, but you must also have a `package.json`, a `config.json`, and a `prices.json` (at least).

It sounds like your program is hanging, possibly waiting for a response from the server.

**Comment by Fastmancz** [comment]
Thanks for answer.

Here are the files:
config.json - https://pastebin.com/2Birp7Cn
prices.json - https://pastebin.com/nAYT98eQ
I can't find file (package.json) only (package-lock.json): https://pastebin.com/ZDgguXXh
When I try to install the package, I get an error message: https://pastebin.com/CdvPKpBa

I think I should get a correctly login message or a bad login message.

**Comment by gibfahn** [comment]
@Fastmancz where did you get this project from? It sounds like you don't have all the files you need?

**Comment by Fastmancz** [comment]
There is tutorial for this project - https://www.youtube.com/watch?v=CD5xCUxTobI and this is last part - https://www.youtube.com/watch?v=4V8oiyWkCio so I don't know what is missing.

**Comment by gibfahn** [comment]
Okay, so the description of the first video you linked to has a Github repo that contains the code for each step: https://github.com/andrewda/node-steam-guide

I suggest you find the right bit of code for the video you were doing, use that, and see if it works.

**Comment by Fastmancz** [comment]
Thanks, problem solved (poorly defined steam login - sharedSecret).
