### ISSUE TITLE
DLL Error

### ISSUE THREAD

**Issue by aabidkhan786** [nodejs/help#805]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by refack** [comment]
@aabidkhan786 Did you have any more information?

**Comment by vsemozhetbyt** [comment]
Refs: https://github.com/nodejs/node/issues/15227

**Comment by gireeshpunathil** [comment]
too few information to provide any help, closing. Please re-open if it is still outstanding, but with required data
