### ISSUE TITLE
How to make one request should process by all clusters in Node JS?

### ISSUE THREAD

**Issue by aniinprni** [nodejs/help#806]
* **Node.js Version**: v6.10.1
* **OS**:windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: cluster

Hi i am newbie to cluster mode in Node JS. I need to execute one particular request by all clusters in node js server without killing them. I searched online, but no where found any solution. You are my last hope. Kindly help me out.

Thanks & regards,
Anil.

**Comment by NickNaso** [comment]
Which is your specific use case? Why do you need to process a request from all the forks?

**Comment by aniinprni** [comment]
Hi Nick, 
   i need this for  internationalization. I am running my server on cluster mode. I  need to update the translations dynamically. When i update the language by url, it is updating to one instance only. Not for every instance. But when i run my server in normal mode , It is working fine. That's why i need to process this request by all clusters.  Pardon me for my english. Hope you understand my requirement. Please help me to resolve.

Thanks & Regards,
Anil.

**Comment by aniinprni** [comment]
Any update on this ? Please help me out.

**Comment by NickNaso** [comment]
@aniinprni Sorry I was busy.
Where do you store your translations?

**Comment by aniinprni** [comment]
Hi Nick,

   I am storing in a JSON file. When i fire a request , All clusters should read and re-initialize the translation function. Then only my translations will update.

Thanks & regards,
Anil.

**Comment by aniinprni** [comment]
Hi, any update on this ? Please help me out.

**Comment by aniinprni** [comment]
Hai Is there any update on this ? Please help me out. I stagnated by this issue

**Comment by bnoordhuis** [comment]
The logic should be this:

1. Worker that receives the request sends a message to the master with `process.send()`.
2. The master sends messages to all workers: `for (const w of cluster.workers) w.send(msg)`
3. The workers update on receiving that message: `process.on('message', msg => { ... })`

**Comment by aniinprni** [comment]
Thanks i really worked for me. I forgot to close this. pardon me
