### ISSUE TITLE
ES6 import for nodejs 8.4.0

### ISSUE THREAD

**Issue by isakovarseniy** [nodejs/help#808]
* **Node.js 8.4.0**:
* **MacOs**:

Hi 
I am trying  following code 
```
import '../common';
import assert from 'assert';
import ok from './test-esm-ok.mjs';
import okShebang from './test-esm-shebang.mjs';

assert(ok);
assert(okShebang);
```
using command
/usr/local/bin/node ~/Downloads/test-modules/typescript-test/qqq.js

and getting exception
```
(function (exports, require, module, __filename, __dirname) { import '../common';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

Process finished with exit code 1
```
Do I need to enable ES6 support?

Thanks
Arseniy Isakov

**Comment by ProfNandaa** [comment]
@isakovarseniy - For now, you will need a transpiler like Babel to use `import`. See [a detailed post here](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c)

**Comment by tniessen** [comment]
ES6 modules behave a little different from CommonJS modules and are not yet officially supported within node. As @ProfNandaa said, you can use a transpiler to use the ES6 module syntax. Be assured, we are working on a solution.
