### ISSUE TITLE
Question on error handling for implementing a stream.Writable

### ISSUE THREAD

**Issue by matianfu** [nodejs/help#810]
* **Node.js Version**: 8.x
* **OS**: all
* **Scope (install, code, runtime, meta, other?)**: document
* **Module (and version) (if relevant)**: stream

The document says:

> Throwing an Error from within writable._write() can result in unexpected and inconsistent behavior depending on how the stream is being used. Using the callback ensures consistent and predictable handling of errors.

Question:

1. Does `Throwing an Error` in document includes calling `this.emit('error')`? Or it just means `throw new Error('some error')`?

If the answer is yes, then the error happened internally must be preserved somewhere, say, `this.error`, and waiting for the next _write or _final call, where the error is returned by the callback. Is this the recommended way? 

The problem for this design is the error handling is delayed. If there are several streams or jobs executed in parallel, and the error handling policy is race and abort, then the abort action will be delayed. Also, if the stream is not a real busy byte-stream, instead, it is a logic stream processing jobs in pipeline mode, then the delayed error handling may waste a lot of computing resources.

2. Can I call `destroy` internally when error happens? Is it harmless as long as `_destroy` is properly guarded not to run more than once? Or should it only used by external component when they want to abort and stop any further action and should never be called from inside?

**Comment by gireeshpunathil** [comment]
closing as answered.
