### ISSUE TITLE
Addons vs Child Processes

### ISSUE THREAD

**Issue by JungleCatSW** [nodejs/help#811]
* **Versions 4->8**:
* **runtime**:

Hi, I have looked through the guides and docs, but couldnt find an answer to this question:
Which situation is best to use an Addon vs Using a Child process ?
- How much overhead does child process spawning have ?
- Do addons have the potential to block the main node thread ?
- How can I use threading in each ? I saw I can use libuv worker threads in addons ?
- How do they compare with long function processing times and high volumes of requests ?

Any help pointing me to this info would be great.
Thanks Sean

**Comment by tniessen** [comment]
> How much overhead does child process spawning have ?

Spawning child processes from within node has about the same overhead as any other way to create processes. I assume your child process is another node.js instance, so it will need to initialize v8 (which is fast thanks to snapshots) and parse your code, so it can become a significant overhead depending on how often you spawn processes and how long they stay alive.

> Do addons have the potential to block the main node thread ?

Yes, addons can block the main thread exactly as JavaScript code can, e.g. if you provide a native binding which is called synchronously.

> How can I use threading in each ? I saw I can use libuv worker threads in addons ?

Addons can use threading however they wish. Child processes use a different set of threads than the parent process.

> How do they compare with long function processing times and high volumes of requests ?

With child processes, you get the IPC overhead, but a native addon requires synchronization between threads (if you want to use threading).

The benefits of using either mostly depend on your application. What exactly are you trying to achieve?

**Comment by addaleax** [comment]
> How can I use threading in each ? I saw I can use libuv worker threads in addons ?

You can use [`uv_work_t`](http://docs.libuv.org/en/v1.x/threadpool.html) directly for this – the API can be worked with – or you could use e.g. [Nan’s `AsyncWorker` class](https://github.com/nodejs/nan/blob/master/doc/asyncworker.md). The only thing you need to make sure is that code that accesses JavaScript code may only run on Node’s main thread.

**Comment by NickNaso** [comment]
Hi @JungleCatSW 
I don't know your specific use case, but if you have the C / C++ source code, for me the best choice is to implement a new native  addon.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding.
