### ISSUE TITLE
Node.v6.11.3

### ISSUE THREAD

**Issue by goh1** [nodejs/help#813]
Hi. I installed the node. V6.11.3 yesterday. Now when I want to on my pc it try to launch but half way it goes blue blanck. What should I do? Thanks

**Comment by gibfahn** [comment]
Try downloading it and installing it again.

When you say it goes blue black, do you mean the Blue Screen Of Death (see picture)?

![image](https://user-images.githubusercontent.com/15943089/30254044-ec3fa084-9689-11e7-84a9-13657fc4678e.png)

**Comment by goh1** [comment]
Thank you for your reply. It took a longer than normal time to launch. But
its ok now. Maybe it was updating. It wasn't like the picture you sent. It
was all blank greyish blue. Supposing the problem emerge again ie the
screen becomes blank again, any path or key that can reach the file so i
can delete it.

Thanks again.

On Mon, Sep 11, 2017 at 7:41 AM, Gibson Fahnestock <notifications@github.com

**Comment by gibfahn** [comment]
>Supposing the problem emerge again ie the screen becomes blank again, any path or key that can reach the file so i can delete it.

If the computer is unresponsive (assuming you're on Windows) and <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Delete</kbd> doesn't work, then I'd recommend restarting it.

You can find the location of the Node binary by opening up `Command Prompt` and typing:

```bat
where node
```

which should give you the path.

I'll close this, as I think that answers your question, but if you have any more questions or issues just comment on here and I'll reopen.
