### ISSUE TITLE
Angular 2 client in a Node JS project with Visual Studio 2017

### ISSUE THREAD

**Issue by Opariti** [nodejs/help#814]
* **Node.js Version**: v6.11.2
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: configuration, build

Hi,

I have developed Node JS projects with Angular JS under VS 2015, deployed them and run on Azure; one Build did all of the project. Globally, it was without any fuss, except for some parameters to instruct IIS how to handle the node server, but eventually it was standard.

Now, I'm changing to Angular 2 and it's something else. It's not obvious how to bring Angular 2 into a MEAN application (not aside), do just one build and run client and server with one command. I've reached to do it from the command prompt, but I want to do it as Run of a Visual Studio Node JS-type project.

The requiremenst would be:
- transpile automatically Angular code at any file change, like with "gulp" + build the Node at any file change, like with "nodemon".
- when Build the project to automatically do TranScript compilation and Node build
- when Run the project to: build as above + open the browser at the server's URL.
As Microsoft gets involved in these type of projects via TypeScript I imagine that you would have the solutions for the above and I welcome any hints.

Thanks

**Comment by gireeshpunathil** [comment]
@Opariti - is this still outstanding?

**Comment by Opariti** [comment]
No

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
