### ISSUE TITLE
Problem with (ECONNREFUSED)

### ISSUE THREAD

**Issue by lukecorf** [nodejs/help#815]
Node.js Version: 8.2.1
Windows 10
IDE: Intellij
Frameworks: Spring Boot & Angular 4

Well... I need get data from my backend (Java). But Angular terminal show this message error:

[HPM] Error occurred while trying to proxy request /api/dados from localhost:4500 to http:/localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

This is my Angular code: 

![a](https://user-images.githubusercontent.com/22321349/30276975-dcafefa4-96dc-11e7-8b5c-69a2b81ab6f4.jpg)

And this is my Java Code: 

![as](https://user-images.githubusercontent.com/22321349/30277046-09e09d3e-96dd-11e7-96c3-c8ebb74c9341.jpg)

My Tomcat is configurated to 8080 port

![sem titulo](https://user-images.githubusercontent.com/22321349/30277080-1f12225e-96dd-11e7-8d58-932e7df7fa97.jpg)

And my proxy in angular is configurated like this image:

![asd](https://user-images.githubusercontent.com/22321349/30277140-4cec9ff6-96dd-11e7-8cad-22df6faa83f8.jpg)

Someone can help me please? This is important

**Comment by NickNaso** [comment]
Hi @lukecorf 
follow this guide https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md 
But to me seem that your **```target```** url is not valid. You set its value to http:/localhost:8080, but I think that the right one is **```http://localhost:8080```**
Hope to be helpful

**Comment by gireeshpunathil** [comment]
Closing as answered, please re-open if it is still outstanding.
