### ISSUE TITLE
WIN 10 - after update - permission issue

### ISSUE THREAD

**Issue by JaniSavolainen** [nodejs/help#817]
Using node with Windows 10

Updated to latest Node v8.4.0 and after that get the following error when trying to install packages as Administrator.

F:\Webpage\test>npm install --save react-swipeable-views
npm ERR! path F:\Webpage\test\node_modules\fsevents\node_modules\assert-plus\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'F:\Webpage\test\node_modules\fsevents\node_modules\assert-plus\pac
kage.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'F:\Webpage\test\node_modules\fsevents\node_modules\assert-plus\
package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'F:\\Webpage\\test\\node_modules\\fsevents\\node_modules
\\assert-plus\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'F:\\Webpage\\test\\node_modules\\fsevents\\node_modules\\assert-plus\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

How to FIX?

**Comment by JaniSavolainen** [comment]
Downgraded with [to](https://github.com/coreybutler/nvm-windows) 8.3.0 and works well

**Comment by gireeshpunathil** [comment]
OP resolved issue, I don't see any issue with node as such, and any outstanding issue either. Closing.
