### ISSUE TITLE
ANSI ASCII IDNA(s)...  ...bool, assambly, executable, comable... ...as some stupids who seem to own a time engine (digitally or physically).

### ISSUE THREAD

**Issue by MatthewBDot** [nodejs/help#819]
An very indice / circumstantial evidence:

[https://www.facebook.com/cryinscapesweapontechnologies/photos/a.1671489926449297.1073741827.1670979273167029/1917057868559167/?type=3](https://www.facebook.com/cryinscapesweapontechnologies/photos/a.1671489926449297.1073741827.1670979273167029/1917057868559167/?type=3)
Use this link for description of this worry with a prntscrn!
MB

* **Node.js Version**: Most recent...
* **OS**: Windows 10...
* **Scope (install, code, runtime, meta, other?)**: Command Line Interpreter usage...
* **Module (and version) (if relevant)**: NPM to create a package.json file...

<sub>_(edited by @vsemozhetbyt: fix link format)_</sub>

**Comment by addaleax** [comment]
This is a problem with `npm`, and is not related to ASCII characters (the space is enough to cause the problem here, the `ä` is not the main issue). I think https://github.com/npm/init-package-json/pull/71 seeks to fix this.

**Comment by gireeshpunathil** [comment]
Closing as answered.
