### ISSUE TITLE
Nodejs static function

### ISSUE THREAD

**Issue by dragonship** [nodejs/help#82]
Hi trying to run a server with node.js, with the following on the command line in a file:

var connect = require('connect'),
	serveStatic = require('serve-static');

connect.createServer(
       connect.static("../angular.js")

).listen(5000);

When I type:

node server.js

The respons is:

c:\node.js\server.js:5
             connect.static("../angular.js")
                                   ^

TypeError: connect.static is not a function

**Comment by kelthenoble** [comment]
connect()
  .use(connect.static(__dirname + '/public'))   Let me know if you need further help.

**Comment by dragonship** [comment]
Hi Kelvin Knighton

Thanks for the reply, and tried your answer with the same result.
Change the code to:

var connect = require('connect');
/* serveStatic = require('serve-static');*/

/*connect.createServer(
       connect.static("../angular.js")*/

connect()
.use(connect.static("../angular.js" + '/public')

).listen(5000);

My apoligise for not getting back to you sooner, very busy at present time
with my own work, and might not get back to you until late next week, as I
am attending a Oracle conference.

Yours Sincerely,
Peter Holder.

**Comment by kelthenoble** [comment]
Hi Pete, I want you to `try this`. 

var connect=require('connect'),
    serveStatic=require('serve-static');

var server=connect();

server.use(serveStatic('../angular.js'));

server.listen(5000);

and if this doesn't do the trick, respond back with your current `version of connect` and we continue from there. :+1: Best of luck mate.

**Comment by dragonship** [comment]
Hi Kelvin Knighton

Thanks. Success.

Peter Holder

**Comment by kelthenoble** [comment]
Glad to hear it Pete :+1:
