### ISSUE TITLE
(node:71470) DeprecationWarning: _writableState.buffer is deprecated. Use _writableState.getBuffer instead.

### ISSUE THREAD

**Issue by cryst10** [nodejs/help#821]
* **Version**: v7.8.0
* **Platform**: 'darwin' OSX Sierra
* **arch**: x64

I am currently writing test for a node module but keep getting this error.
```(node:71470) DeprecationWarning: _writableState.buffer is deprecated. Use _writableState.getBuffer instead.``` 

The process halts with this error and nothing happens the only remedy is killing the process. There is no further information or hints from where this error is from.

**Comment by gibfahn** [comment]
This is the deprecation message: [deprecations.md#dep0003-_writablestatebuffer](https://github.com/nodejs/node/blob/468110b3276007f445741b41c36beb0ef62d751c/doc/api/deprecations.md#dep0003-_writablestatebuffer)

Here is the deprecation in the source code:

https://github.com/nodejs/node/blob/7ce2555896536a6c9e96a8b9fd17b6563137a876/lib/_stream_writable.js#L166-L171

This deprecation warning shouldn't be crashing your process, as you can see it just logs the warning and then calls `_writableState.getBuffer()` instead. Have you tried using [the inspector](https://nodejs.org/en/docs/inspector/) to step through your code? That should show you what's going on.
