### ISSUE TITLE
When does a http request end?

### ISSUE THREAD

**Issue by ronag** [nodejs/help#824]
I would like to achieve the same thing `on-finished` does but in a less "hacky" (no extra allocations) way and I've come up with something like this:

```javascript
    req
      .on('close', onFinish)
      .on('aborted', onFinish)
      .on('error', onFinish)
    res
      .on('finish', onFinish)
      .on('close', onFinish)
      .on('error', onFinish)
```

Which works. But I'm not sure I need to listen to all of those events, i.e. what's the overlap between `close` on `req` vs `res`. Do I need to listen to both?

**Comment by gireeshpunathil** [comment]
is this still outstanding?

**Comment by ronag** [comment]
I think `close` on either `req` or `res` is enough. But it would be nice to have someone confirm it.

**Comment by gireeshpunathil** [comment]
In a variety of ways I tested, I see your point, `close` listener is always closed. So it makes sense to me!
