### ISSUE TITLE
issues reported in an article

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#826]
* **Node.js Version**: 6.11.3, 8.4.0
* **Scope (install, code, runtime, meta, other?)**: memory, performance, error messaging

[In this article](https://hackernoon.com/how-many-53-bit-integers-fit-in-your-languages-map-data-structure-41605402b7de), the author has reported some issues with Node.js (repository with the code is provided). I am not sure if we should address any of them, so this is just some overcautious alert. Feel free to close whenever it is appropriate.

**Comment by tniessen** [comment]
> node.js shows the worst memory performance characteristics. Of these, the current LTS release of node (v6) is slightly better than the latest release (v8). However, both are not only the slowest profiled here, but also show among the worst memory performance. Node 6 stores just 11.1 million integers in an object, and node 8 fares the worst with 8.3 million integers.

There is not a lot we can do about all of the performance-related "problems", this is mostly related to v8 as far as I know. Unsurprisingly, C++ exceeds the performance of v8 when working with a lot of in-memory data, and python is known to be efficient as well. The regression from 11.1 to 8.3 should probably be thought about.

> node 8.4.0 hung without crashing after consuming approximately 1.1 GB of memory. This is in spite of running with the — max-old-space-size=2048 command line flag. Without limiting process memory using ulimit, memory consumption appeared to increase without bound, in spite of producing no new output. Disabling TurboFan using — noturbo had no impact. Disabling garbage collection using — noconcurrent_sweeping also had no impact.

This sounds like something we should probably investigate.

**Comment by vsemozhetbyt** [comment]
It seems this can be closed now due to inactivity.
