### ISSUE TITLE
How to handle connection switch while there is a OnGoing Request?

### ISSUE THREAD

**Issue by bboysathish** [nodejs/help#827]
* **Node.js Version**: 6+
* **OS**: Mac
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: request, http

https://stackoverflow.com/questions/46265830/how-to-handle-connection-switch-while-there-is-a-ongoing-request

I have explained the issue in stackoverflow post.

**Comment by tniessen** [comment]
It seems like you are trying to do HTTP requests while physically switching networks. HTTP is based on TCP, and TCP connections cannot be held open if your network interface, your IP address or your physical network changes. It is up to your network interface or manager to mark existing connections as closed and to report corresponding errors to applications.

**Comment by bboysathish** [comment]
@tniessen Thanks for the answer. Can you also please clarify how to handle this ( not only on Node.js point / system level )

**Comment by tniessen** [comment]
The problem at hand might be that TCP connection timeouts can be quite long, so you might want to configure your own timeout (via `setTimeout()`), not on the connection but in your own application logic. This is not the cleanest, but probably the easiest way to do it.

**Comment by bboysathish** [comment]
interesting i thought the `requests` module would have default timeout value for some time, let me try setting that value. @tniessen

**Comment by gireeshpunathil** [comment]
ping @bboysathish - is this still outstanding?

**Comment by bboysathish** [comment]
@gireeshpunathil  NOPE. But if you solution for this, please post it may help someone in future & close this issue. Thanks

**Comment by gireeshpunathil** [comment]
Closing as answered .
