### ISSUE TITLE
child_process shell invocation doesn't honor PATH as specified in process.env per expectation

### ISSUE THREAD

**Issue by cdaringe** [nodejs/help#829]
* **Node.js Version**: 8.x
* **OS**: macOs
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: -

Hi all.  I actuall [fully described my issue on SO](https://stackoverflow.com/questions/46167958/why-is-which-not-resolving-the-binary-that-comes-first-in-my-path-from-nodejs), although it's been crickets.

in summary, if i set `PATH` on the `process.env` object and shell out via child process, the `which` binary does not return the first binary actually found on the PATH.  setting the path in a generic bash shell and `which`ing produces the expected binary.

runnable code?  so glad you asked! [here it is](https://github.com/cdaringe/squish-squash/blob/44c2ae4a249707ed6d23d980d4bfc633f111ade1/test/index.js#L70-L72)!

**Comment by richardlau** [comment]
Are you setting the `shell` option on the child process?

**Comment by vsemozhetbyt** [comment]
@cdaringe Maybe you can also ask in [execa repository](https://github.com/sindresorhus/execa) in case this is an `execa` issue.

**Comment by cdaringe** [comment]
thx guys. i'll do some more profiling then re-raise it, here or there
