### ISSUE TITLE
TLS socket with RC4 cipher

### ISSUE THREAD

**Issue by pierreliefauche** [nodejs/help#83]
I’m running into an issue while trying to open a TLS socket with a server using a RC4-SHA cipher.

As RC4 ciphers has been deprecated in node, the secure connection would not establish, that’s expected, but __there is no reporting about the secure connection not being established, let alone why__.

Question: __Is there any way to know that the secure connection is failing and why?__

---

The server is `smtp.orange.fr:465`.
`openssl s_client -connect smtp.orange.fr:465` indicates `TLSv1/SSLv3, Cipher is RC4-SHA`.

Here’s my test script (tested on 5.5.0 and 4.2.5):
```js
'use strict';

const tls = require('tls');

// Logging
const start = Date.now();
const log = function(str) {
  const args = Array.prototype.slice.apply(arguments);
  args[0] = `${Date.now() - start}ms - ${args[0]}`;
  console.log.apply(null, args);
};


const socketOptions = {
  host: 'smtp.orange.fr',
  port: 465,
};

const socket = tls.connect(socketOptions, log.bind(null, '[connect callback]'));

socket.setEncoding('utf8');

socket.on('connect', ()=> {
  log('[on connect] encrypted=%s authorized=%s authorizationError=%s cipher=%j', socket.encrypted, socket.authorized, socket.authorizationError, socket.getCipher());
});
socket.on('secureConnect', ()=> {
  log('[on secureConnect] encrypted=%s authorized=%s authorizationError=%s cipher=%j', socket.encrypted, socket.authorized, socket.authorizationError, socket.getCipher());
});
socket.on('error', log.bind(null, '[on error]'));
socket.on('data', log.bind(null, '[on data]'));
socket.on('timeout', log.bind(null, '[on timeout]'));
socket.on('end', log.bind(null, '[on end]'));
socket.on('close', log.bind(null, '[on close]'));
```

Running the above script outputs:
```
261ms - [on connect] encrypted=true authorized=false authorizationError=null cipher=undefined
60364ms - [on error] { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
60378ms - [on close] true
```

The socket connects (as expected, the server and port exist and are reachable), but then nothing, no indication that the server cert is "rejected" and the _secure_ connection never established, it just hangs until `ECONNRESET` fires.

Now, if I set `ciphers: 'RC4'` on `socketOptions` to override the list of allowed ciphers:
```
29ms - [on connect] encrypted=true authorized=false authorizationError=null cipher=undefined
68ms - [connect callback]
69ms - [on secureConnect] encrypted=true authorized=true authorizationError=null cipher={"name":"RC4-SHA","version":"TLSv1/SSLv3"}
122ms - [on data] 220 mwinf5d64 ME ESMTP server ready

300608ms - [on end]
300609ms - [on close] false
```

As expected:
- connection is established
- handshake succeeds and fires `secureConnect`
- server sends greeting

**Comment by bnoordhuis** [comment]
I had a quick look and I can confirm what you're describing.  It looks like the server simply doesn't send back anything if it doesn't like the TLS handshake.

I can't say for sure but it's possible we're dealing with a buggy TLS terminator.  I've seen this behavior before: if the handshake packet is too large, the server simply stops responding.

If you change the ciphers list to e.g. `ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384` (ciphers the server doesn't support but few enough not to trip the size limit), you get the expected handshake failure error:
```
$ NODE_DEBUG=net,tls,crypto out/Release/node -e \
  'require("tls").connect({host:"smtp.orange.fr",port:465,ciphers:"ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"}).on("error", console.error)'
NET 13581: pipe false undefined
NET 13581: connect: find host smtp.orange.fr
NET 13581: connect: dns options { family: undefined, hints: 40 }
NET 13581: _read
NET 13581: _read wait for connection
NET 13581: afterConnect
TLS 13581: start
NET 13581: _read
NET 13581: Socket._read readStart
NET 13581: destroy Error: 139981992400704:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:

    at Error (native)
NET 13581: destroy
NET 13581: close
NET 13581: close handle
Error: 139981992400704:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:

    at Error (native)
NET 13581: emit close
```

**Comment by pierreliefauche** [comment]
Thanks for looking into that so quickly!

Do you by any chance have an idea of how to get the cert details without running into that issue/establishing a connection at all?

**Comment by bnoordhuis** [comment]
If the issue is the handshake size, really the only workaround is to limit the number of ciphers.  The default cipher list in node.js is quite extensive and doesn't fit in the 64 bytes that I suspect is the limit for these faulty TLS terminators.

**Comment by pierreliefauche** [comment]
Thanks @bnoordhuis! Closing.
