### ISSUE TITLE
Problem with Intl API and toLocaleString in NodeJS

### ISSUE THREAD

**Issue by eddyw** [nodejs/help#832]
* **Node.js Version**: v8.4.0
* **OS**: MacOS
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: --

Running the following in Google Chrome, for example:
```js
(1314).toLocaleString('ar-EG') // Outputs:  "١٬٣١٤"
(1314).toLocaleString('zh-Hant-u-nu-hanidec') // Outputs:  "一,三一四"
(131400).toLocaleString('hi-IN') // Outputs: "1,31,400"
```
However, in NodeJS, running the same code:
```js
(1314).toLocaleString('ar-EG') // Outputs:  "1,314"
(1314).toLocaleString('zh-Hant-u-nu-hanidec') // Outputs:  "1,314"
(131400).toLocaleString('hi-IN') // Outputs: "131,400"
```
Why? Am I missing something?
Intl API (`new Intl.NumberFormat('[encoding]').format(1314)`) behaves the same way.

**Comment by bnoordhuis** [comment]
> Am I missing something?

Yes, https://www.npmjs.com/package/full-icu :-)

**Comment by vsemozhetbyt** [comment]
See also https://nodejs.org/api/intl.html

**Comment by eddyw** [comment]
@bnoordhuis cool, thanks!
Issue is solved

**Comment by eddyw** [comment]
@vsemozhetbyt thanks, I did wrong assuming NodeJS already includes all the Unicode data set. I haven't worked with Intl API on server-side before
