### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat 'index.html'

### ISSUE THREAD

**Issue by luck2011** [nodejs/help#838]
* **Version**:  v8.5.0
* **Platform**:  Darwin iMac.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
* **Subsystem**: fs.lstatSync

```fs.lstatSync``` throws an error when __reading infos of the sub-folders__ of the current folder, the subfolder means the child folder of the current folder in which my ```index.js``` locates.

Here is the ```index.js```:

```es
const myPath = __dirname + '/subfolder2/'
const { lstatSync, readdirSync } = require('fs')
const isDirectory = (source) => lstatSync(source).isDirectory()
const getDirectories = source => readdirSync(source).filter(isDirectory)
var folders = getDirectories(myPath)
console.log(folders)
```

When I change the ```/subfolder2/``` to ```/``` in the code above, it works well and prints: 
``` 
['subfolder1', 'subfolder2']
```

But with ```/subfolder2/``` it fails with:

```sh
fs.js:948
  binding.lstat(pathModule._makeLong(path));
          ^
Error: ENOENT: no such file or directory, lstat 'index.html'
    at fs.lstatSync (fs.js:948:11)
    at isDirectory (/Users/cc/Downloads/node-demo/index.js:6:33)
    at Array.filter (<anonymous>)
    at getDirectories (/Users/cc/Downloads/node-demo/index.js:8:54)
    at Object.<anonymous> (/Users/cc/Downloads/node-demo/index.js:10:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

The folder structure like this:

node-demo/
├── index.js
├── subfolder1/
├── subfolder2/
│   └── subfolder3/
│   └── index.html

**Comment by gireeshpunathil** [comment]
can you please try this:
```patch
#diff index.js.org index.js
3c3
< const isDirectory = (source) => lstatSync(source).isDirectory()
---
> const isDirectory = (source) => lstatSync(myPath + source).isDirectory()
#
```

**Comment by luck2011** [comment]
@gireeshpunathil it works and prints: ```[ 'subfolder3' ]```, but fails when without ```myPath```.
So is it a bug or ? 👍

**Comment by gireeshpunathil** [comment]
@luck2011 - it is not a bug. The `readsirSync()` returns the `relative` values of the resident files which needs to be augmented with the `vortex` from where they were referred, and hence the prepend. 

This also explains why it worked for you when you were in the root of the file system where the `absolute` === `relative`

Hope this helps.

**Comment by luck2011** [comment]
So things comes to be clear: ```lstatSync``` method checks for ```source``` forder from the current folder. 😄 
Thanks!
