### ISSUE TITLE
NodObjC Module

### ISSUE THREAD

**Issue by tahasiddiqui123** [nodejs/help#84]
Hello, I have a task for which I have to use the NodObjC module of node.js.I have search and find the hello world example which is working fine but I have to use systemConfiguration Framework.
I tried the code 

[var $ = require('nodobjc');
$.framework('systemConfiguration');
var pool = $.NSAutoreleasePool('alloc')('init');
var string = $.SCPreferencesRef('SCPreferencesCreate', 'NULL','NULL','NULL');
console.log(string);
pool('drain');](url)

This is not working please some one help me out.
Thanks very much.

**Comment by TooTallNate** [comment]
This probably belongs at https://github.com/TooTallNate/NodObjC/issues.

**Comment by tahasiddiqui123** [comment]
Thanks so much for your reply,

I have post there it as an issue sir but no one give response to it. So
please help me

Thanks

**Comment by kelthenoble** [comment]
Hey @TooTallNate when @tahasiddiqui123 opens it over at your repo, could you come back here and close this, Thanks Nate :100:

**Comment by TooTallNate** [comment]
https://github.com/TooTallNate/NodObjC/issues/80

@kelthenoble I don't appear to have permissions to close this issue.

**Comment by kelthenoble** [comment]
Ah. Sorry about nate, i got it man.
