### ISSUE TITLE
Node automation

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#843]
Dear all,

I have a very basic question on Node. I am looking for a way to automate parts of my work as a developer. A lot of the tasks (for setting up a project, and migrating to the live server) are repetitive and can be done inside the browser.
And so I would like to ask if there are any node Modules that allow you to have node visit a URL and:

fill in input fields
hit submit buttons
Thus automating these tasks?
Which Modules could I use for this purpose?

Greets

**Comment by vsemozhetbyt** [comment]
https://github.com/GoogleChrome/puppeteer

**Comment by kahwee** [comment]
You can also check out test automation tools such as Selenium and search for "macro recorders". It seems like what you want to achieve may not require node.js.

**Comment by lordKnighton** [comment]
I'd like to mention Protractor/ Selenium like @kahwee mentioned. Maybe your searching for End2End testing:

Happy Coding 💯 

Links: 
 https://medium.com/@adrian_lewis/top-5-most-rated-node-js-frameworks-for-end-to-end-web-testing-f8ebca4e5d44  

https://blog.risingstack.com/end-to-end-testing-with-nightwatch-js-node-js-at-scale/

https://dzone.com/articles/selenium-nodejs-and-mocha

**Comment by lordKnighton** [comment]
feel free to reopen
