### ISSUE TITLE
How to name make output?

### ISSUE THREAD

**Issue by hekike** [nodejs/help#858]
What's the easy way to name make outputs and handle multiple node versions while working with the core?

Like `./node-master` and `./node-pr-5134` in the benchmarking guide:
https://github.com/nodejs/node/blob/master/doc/guides/writing-and-running-benchmarks.md#comparing-nodejs-versions

Thanks,
Peter

**Comment by bnoordhuis** [comment]
I use separate checkouts + ccache.  Set `hash_dir = false` in `$HOME/.ccache/ccache.conf` to dedup build artifacts from different directories (but note it sometimes confuses debuggers.)

**Comment by hekike** [comment]
Okay thanks!

**Comment by gibfahn** [comment]
@bnoordhuis is `hash_dir = false` something we should consider for build machines? We don't normally use debuggers on them, and I guess it could save substantial build time.

cc/ @nodejs/build
