### ISSUE TITLE
Socket.IO - force remove specific user from room

### ISSUE THREAD

**Issue by LuciusAterna** [nodejs/help#859]
I search a lot of way to force remove specific user from a Socket.IO room by the server-side. like manager that force you to get out from the group in WhatsApp.
(not close the whole room - just the remove specific user).
Are you know how to do that ?

**Comment by lordKnighton** [comment]
I hope this helps: 

[link🔗 ](https://stackoverflow.com/questions/23092624/socket-io-removing-specific-listener)

This should be closer to a solution for you
[link🔗 ](https://github.com/socketio/socket.io-client-swift/issues/375)
------
if you still need more help, reopen & we will go from there
