### ISSUE TITLE
Notification of new releases

### ISSUE THREAD

**Issue by lostthetrail** [nodejs/help#86]
Has anyone found a particularly good way to be notified of new releases?

The best I have come up with is watching the atom feed:
https://github.com/nodejs/node/releases.atom

Is there a mailing list somewhere?

**Comment by rvagg** [comment]
http://nodejs.org/en/blog/ is where they are announced, I think that http://nodejs.org/en/feed/releases.xml should be reliable (if it's not then let us know!)

**Comment by lostthetrail** [comment]
Thanks @rvagg. Much appreciated.

**Comment by jsumners** [comment]
I just spent some time searching the website for a "releases" mailing list. I'd really rather be able to subscribe to a list that only announces new LTS releases. That releases.xml feed 1) is both LTS and non-LTS and 2) is an RSS feed which requires some sort of active checking. It's easier for us end users to get push notifications than pull.

It's disappointing that @github doesn't already provide this sort of feature. They do have our email addresses, and it should be fairly easy to say "on this repo, I want to know about new tags like `.*-lts-release`". But they don't. So it'd be very helpful if you guys would consider doing this.

**Comment by osher** [comment]
Still work in progress, kind'a waiting because of my limited free time - but core module works:
https://github.com/osher/node-lts-notifier

**Comment by osher** [comment]
Just published `+ node-lts-notifier@0.4.0`
would love to help if anybody does not succeed with it

**Comment by cluick** [comment]
I you use Windows, then you can use a small Powershell script which I have written to get informed about new patch releases of the currently installed Node.js version. See the following Github Repo for details:  https://github.com/cluick/CheckForNewNodeJS.ps1
