### ISSUE TITLE
Possible to use nodejs on client browser to print document to specific printer?

### ISSUE THREAD

**Issue by deepak-nawathe** [nodejs/help#860]
* **Node.js Version**: v8.x
* **OS**: Windows x64
* **Scope (install, code, runtime, meta, other?)**: Without installing full nodejs on client browser
* **Module (and version) (if relevant)**: node print

First of all, forgive me for asking such question if this is not relevant here.

We are trying to figure out if we can use Nodejs on client browser [any supported browser by nodejs] to print a document to a specific printer without opening print dialog box [with name or ip address]. However, the challenge is we can't install full Nodejs on each client machine. So is there any component/sub-set of nodejs applicable to client browsers only that can be included as part of a HTML page? Which executes the print job and sends a document to specific printer connected to client machine?

Please let me know if this can be achieved using Nodejs or it would be great if you can point me to any different approach to implement the required behavior?

Thanks in advance for your kind support.

**Comment by tniessen** [comment]
Short answer: No, you can't.

Node.js is a server runtime, so it's code cannot be included in webpages and it cannot access client devices such as printers. If you were able to install Node.js on the client machine, you could, but it sounds like this is not possible in your situation.

I am not aware of a possibility to print documents from any browser without requiring user interaction outside of the website, either by interacting with the built-in print dialog or by installing additional software.

**Comment by vsemozhetbyt** [comment]
You can possibly try [Electron](https://github.com/electron/electron/) with [`contents.print([options])`](https://electron.atom.io/docs/api/web-contents/#contentsprintoptions).

If you mean some virtual printer for PDF, you can try [Puppeteer](https://github.com/GoogleChrome/puppeteer/) with [`page.pdf(options)`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions).

**Comment by deepak-nawathe** [comment]
Thanks a lot for the clarification.

**Comment by deepak-nawathe** [comment]
Thank you very much for the suggestions.
