### ISSUE TITLE
Unable to remove node 5.0.0 or upgrade to latest

### ISSUE THREAD

**Issue by prasad456** [nodejs/help#861]
Hi,

Please look out image with is attached
![screenshot from 2017-10-04 13-10-38](https://user-images.githubusercontent.com/6705718/31164661-b389ce3e-a905-11e7-81fd-96398cd62caa.png)

Please help me, I want to install ionic framework

* **Node.js Version**: 8.6.0
* **OS**: Ubuntu 16.4
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by bnoordhuis** [comment]
Debian or Ubuntu?  `which node` will tell you where the node binary lives; you can probably just `rm` it.

The `nodejs` binary is from your distro's repo.  There is a nodejs-legacy package that installs a symlink from `/usr/bin/nodejs` to `/usr/bin/node`.

**Comment by prasad456** [comment]
@bnoordhuis 
Mine is Ubuntu OS,
I tried to remove, but warning repeats even I restarted my system after removing.
I'm a newbie for Ubuntu, please help me...

Can you explain how to remove and reinstall the node & node.js latest versions?
