### ISSUE TITLE
Installing nodejs in Opensuse 12.1

### ISSUE THREAD

**Issue by zlatanibra** [nodejs/help#862]
Hello, I would like to install nodejs in my opensuse 12.1. I haven't found it in the repositories. How could I install it? 

Thanks

**Comment by lordKnighton** [comment]
These shouldn't be to far from what your trying to accomplish ✅

Hi @zlatanibra check out these links: 
[Link1 🔗  ](http://blog.teamtreehouse.com/install-node-js-npm-linux)
[Link2 🔗  ](https://seravo.fi/2014/installing-node-js-suse-linux-enterprise)
[Link3 🔗  ](https://rpmfind.net/linux/RPM/opensuse/updates/leap/42.1/oss/x86_64/nodejs-4.3.1-24.1.x86_64.html)

If you need more help, do let me know 😸
