### ISSUE TITLE
System-wide package override?

### ISSUE THREAD

**Issue by mk-pmb** [nodejs/help#863]
* **Node.js Version**: Node.js v6.11.4, npm v5.5.0
* **OS**: Ubuntu 14.04.5 LTS trusty
* **Scope (install, code, runtime, meta, other?)**: install, runtime
* **Module (and version) (if relevant)**:

Is there any way to set a system-wide package override? Or maybe for selected users at least?
I'd like to configure node so that if any module `require()`s a file that would be provided by a package named `buggy-thingy` (version ranges are bonus), node shall provide the file from package `fixed-thingy` instead, or fail if the better package doesn't have the file.
Ideally I'd also like to set an expiration date after which it warns me to check whether I still need that workaround.
For npm I'd like a package blacklist with expiration date as well, so npm will rather fail than install any of the banned packages. For some of them I'd like to configure which replacement to use instead.

**Comment by tniessen** [comment]
Those buttons should really be further apart...

**Comment by bnoordhuis** [comment]
No, you can't do that.
