### ISSUE TITLE
Node inspector - killing the browser debugging environment - how to?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#867]
https://stackoverflow.com/questions/46628769/how-to-kill-node-inspector-once-you-have-started-debugging

anybody know how? thanks

**Comment by gibfahn** [comment]
Answered on SO as well:

I normally do <kbd>Ctrl</kbd>-<kbd>C</kbd> in the terminal, then click `Play` in the browser (so Node can handle the signal).

There's probably an easier way.

**Comment by ORESoftware** [comment]
@gibfahn how did you create those ctrl / c character icons? that's cool

**Comment by bnoordhuis** [comment]
@ORESoftware `<kbd>Ctrl</kbd>-<kbd>C</kbd>`
