### ISSUE TITLE
Create prototype function inline

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#868]
Ok say we have this:

```js
    class Car {
        constructor(name) {
            this.kind = 'Car';
            this.name = name;
        }
    
        printName() {
            console.log('this.name');
        }
    }
```

what I want to do is define printName, like so:

```js

   const {makePrintName} = require('./make-print-name');

    class Car {
        constructor(name) {
            this.kind = 'Car';
            this.name = name;
        }
    
        printName: makePrintName(foo, bar, baz)  // this syntax is not correct! 
    }
```

where makePrintName is a functor, something like:

```js
    exports.makePrintName = function(foo, bar, baz){
       return function(){ ... }
    };
```

is this possible with ES6? My editor and TypeScript is not liking this

**Comment by ORESoftware** [comment]
If I do this instead:

```js
   class Car {
        constructor(name) {
            this.kind = 'Car';
            this.name = name;
        }
    
        printName = makePrintName(foo, bar, baz); // with = instead of :
    }

```

printName will not be on the prototype, it will be a top-level property, wtf

**Comment by NickNaso** [comment]
Hi @ORESoftware 
You can try the following code:
```JavaScript
'use strict'

class Car {
    constructor(name) {
        this.kind = 'Car'
        this.name = 'NickNaso'
    }

    makePrintName() {
        console.log(`kind: ${this.kind} - name: ${this.name}`)
    }

    static makePrintName(kind, name) {
        console.log(`kind: ${kind} - name: ${name}`)
    }
}

let myCar = new Car()
myCar.makePrintName()
Car.makePrintName(myCar.kind, myCar.name)
```
The first method is a prototype method so you can call it on an instance of object Car, while the second is a static method and you can invoking by class Car.
I hope that this is what you need.
Nick

**Comment by ORESoftware** [comment]
@NickNaso thanks but that's not quite what I am looking for unfortunately, this is a syntax limitation of ES5 as far as I can tell, I added details here:

https://stackoverflow.com/questions/46639573/create-prototype-function-inline-with-different-scope

if you give a good answer I will upvote it
