### ISSUE TITLE
Detecting if a UDP port is open

### ISSUE THREAD

**Issue by umutm** [nodejs/help#87]
I am trying to check if a UDP port is open or not using Nodejs' dgram module.

Checking TCP is very easy, yet, as UDP is one way, I guess I have to:

- send a request
- create a UDP server
- listen to any responses

Anyone has success in checking if a UDP port is open or not? If yes, I'd appreciate if you can share any code samples. Thanks so much.

**Comment by sivatumma** [comment]
What I am doing right now is doing a telnet to that port. (or netstat -lntu)
We can log something on the 'listening' event of course through program
( My dgram server is not opening port now which prior to 3 days worked like charm, though. I am on it now)

**Comment by umutm** [comment]
@sivatumma Telnet is TCP-only as far as I know. And, with netstat, you can only view the ports of teh local computer.

I'm actually trying to detect if a remote UDP port is open.

**Comment by kelthenoble** [comment]
I don't have much experience with this module. But here is some resources, i hope they prove to be useful.   -> 

so you want to set up your problem like the docs suggests -> 

![screen shot 2016-02-13 at 1 48 18 pm](https://cloud.githubusercontent.com/assets/1773260/13030261/555abd34-d259-11e5-8cec-9f4fb19c90c2.png)

Be sure to check this out :100:  http://serverfault.com/questions/416205/testing-udp-port-connectivity

https://en.wikipedia.org/wiki/Netcat#Test_if_UDP_port_is_open:_simple_UDP_server_and_client
![screen shot 2016-02-13 at 1 53 59 pm](https://cloud.githubusercontent.com/assets/1773260/13030256/28cac9f8-d259-11e5-9722-ff2f307735d0.png)

Be sure to let me know if this works.

**Comment by bnoordhuis** [comment]
Easy solution: run nmap as root in a child process.  There is no 100% foolproof method if that is what you're hoping for: the host may not reply, the hops in between may not pass on the reply, etc.

**Comment by umutm** [comment]
@kelthenoble Thanks very much. I actually went that route but couldn't get the response from a given port (and the server responded). With a huge possibility I did some things wrong and will re-check.

@bnoordhuis Thanks very much and sounds great. Yet, I plan to test the availability of 1000s of UDP ports and running such many child processes will be a performance killer, right? Trying to make it work with dgram will be smarter performance-wise?

**Comment by bnoordhuis** [comment]
You can tell nmap to scan a range of ports, you don't need one process per port.  nmap can do a lot of things the dgram module can't.  I'd go for nmap.

**Comment by kelthenoble** [comment]
No problem, `Glad to be of help` & do let us know, if you've solve this issue.

**Comment by umutm** [comment]
@bnoordhuis Thanks very much for that and will be checking it (also https://github.com/jas-/node-libnmap).

**Comment by kelthenoble** [comment]
Closing for now, feel free to reopen.
