### ISSUE TITLE
"Since modules may resolve to a different filename based on the location of the calling module (loading from node_modules folders), it is not a guarantee that require('foo') will always return the exact same object"

### ISSUE THREAD

**Issue by pfftdammitchris** [nodejs/help#870]
* **Node.js Version**: any
* **OS**: Any
* **Scope (install, code, runtime, meta, other?)**: Semantics of Node.js
* **Module (and version) (if relevant)**: Any

On the [docs](https://nodejs.org/docs/latest/api/modules.html#modules_module_caching_caveats), it says that: 
**Modules are cached based on their resolved filename. Since modules may resolve to a different filename based on the location of the calling module (loading from node_modules folders), it is not a guarantee that require('foo') will always return the exact same object, if it would resolve to different files.**

Are my understanding of these semantics is correct?:  

If two modules are the same exact version but live in 2 separate paths, they will be loaded separately?
```
path1: home/node_modules/<lodash v.4.0.2>
path2: home/node_modules/cheerio/<lodash v.4.0.2>
```
The docs says that they are cached based on their resolved **filename**.  But since the next sentence says **"Since modules may resolve to a different filename based on the location of the calling module (loading from node_modules folders), it is not a guarantee that require('foo') will always return the exact same object, if it would resolve to different files."**, does that mean that the files will **not** be cached, because they have a different path? 

Some times people refer to a different file name together with the meaning of a path, so I am a little confused.

**Comment by addaleax** [comment]
If you have one `require('lodash')` call in `home/node_modules/foo/bar.js` and one `require('lodash')` call in `home/`, and both `home/lodash` and `home/node_modules/foo/node_modules/lodash` exist, that’s an example of when the `require()` call would return different results.

`require()` results *are* cached if the (absolute) filename that the call resolves to is the same, though.
