### ISSUE TITLE
basic question on Node errors

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#871]
Hi all, I have a question on the code below that I saw on Nodeschool. As we can see, the file solution_filter.js is a dependency of solution.js
It adds a single function to the module.exports object. The only thing I dont get is how errrors get handled. Do errors automatically get passed to callbacks within functions? I am wondering if the "err" in the callback is referring to the same "err" of its parent, and if acces to this error is always "inherited"... Many thanks in advance

─────────────────────────────────────────────────────────────────────────────
 _/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/soluti
 on/solution.js_ :

```js
    var filterFn = require('./solution_filter.js')
    var dir = process.argv[2]
    var filterStr = process.argv[3]
    
    filterFn(dir, filterStr, function (err, list) {
      if (err) {
        return console.error('There was an error:', err)
      }
    
      list.forEach(function (file) {
        console.log(file)
      })
    })
```
─────────────────────────────────────────────────────────────────────────────
 _/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/soluti
 on/solution_filter.js_ :

```js
    var fs = require('fs')
    var path = require('path')
    
    module.exports = function (dir, filterStr, callback) {
      fs.readdir(dir, function (err, list) {
        if (err) {
          return callback(err)
        }
    
        list = list.filter(function (file) {
          return path.extname(file) === '.' + filterStr
        })
    
        callback(null, list)
      })
    }
```

**Comment by banyudu** [comment]
There's not an "inherited" err. It's just a plain function call, with err as callback's first parameter
