### ISSUE TITLE
whether can i use "'Content-Length': postData.length"?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#873]
# [http.request(options[, callback])](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_http_request_options_callback)
![default](https://user-images.githubusercontent.com/8686739/31366977-bceaa836-ada6-11e7-927b-a9411d7ef746.PNG)

**Comment by anlexN** [comment]
![default](https://user-images.githubusercontent.com/8686739/31367271-b0d703c6-ada8-11e7-9a58-b38d8b201b92.PNG)


### if can i code this?

```javascript
res.on('data', (chunk) => {
    console.log(`BODY: ${chunk}`);
}).on('end', () => {
    console.log('No more data in response.');
});
```

**Comment by bnoordhuis** [comment]
When `postData.length === Buffer.byteLength(postData.length)`, if I understand your question.  The Content-Length header is always expressed in bytes.

Unicode characters can decode to multiple bytes so the the character length may be less than the byte length.
