### ISSUE TITLE
Where are the installers for versions of node other than LTS and Current?

### ISSUE THREAD

**Issue by willnwhite** [nodejs/help#876]
I want to use async/await in node. I read that v7 supports it. Rather than using Current, I'll use the latest v7 (more stable, right?).

**Comment by evanlucas** [comment]
Node 7 is not longer being maintained. I would recommend using the latest version of Node 8. I believe it is stable (we run it in production, in fact). Node 8 is also going to become the new LTS version in the near future.

**Comment by shellberg** [comment]
I'd concur!  Node v7 was the previous 'Current' release hosting developments effort then, but is by now 6 months out-of-date and unmaintained.    Node v8 is in its stability period prior to LTS, which is pretty imminent.

**Comment by NickNaso** [comment]
Hi @willnwhite,
I completely agree with @evanlucas and @shellberg Node.js v7.x is no longer mantained so if you can switch to the new Node v8.x. Anyway you can find the downloads for all Node.js versions here:
https://nodejs.org/en/download/releases/

**Comment by willnwhite** [comment]
@NickNaso I'd seen that link but not the .pkg installer at the bottom of each page. I'll install v8. Thanks everyone.
