### ISSUE TITLE
Document event arguments (http2, maybe more)

### ISSUE THREAD

**Issue by grantila** [nodejs/help#877]
* **Scope (install, code, runtime, meta, other?)**:
Documentation

* **Module (and version) (if relevant)**:
http2

When reading through parts of the `http2` documentation, I'm missing information about what arguments are passed in many events. It's like documenting that there's a function called `foo` but not what argument it takes.

If an event is emitted without any arguments, writing *"Emitted without any arguments"* in the documentation would be helpful. I tend to `console.log(arguments)` just to see what's there, and this forces me to try to cause events to actually be emitted... I'm probably not the only one.

[`session`:`close`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_close) 😟 I'm guessing none?
[`session`:`connect`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_connect) 😟 None? Also, what will I *typically* listen to?
[`session`:`error`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_error) 😧 An error argument perhaps? No?
[`session`:`frameError`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_frameerror) 😉 Well documented! But, the argument types have a different layout compared with:
[`session`:`goaway`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_goaway) 👍
[`session`:`localSettings`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_localsettings) 😕 What properties can I expect?
[`session`:`remoteSettings`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_remotesettings) 😕 What properties can I expect?
[`session`:`stream`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_stream) 😔 Flags? This is my flag: 🇸🇪
[`session`:`socketError`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_socketerror) 😰 What am I supposed to do?
[`session`:`timeout`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_timeout) 😒 Doesn't look like any arguments by the example snippet. And should I expect Node to close the socket?

The same goes for the *streams*...

[`stream`:`aborted`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_aborted) 😶 "Writable end". Is that my end, or the remote peers? Is abortion an error, i.e. should I expect an argument?
[`stream`:`error`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_error_1) 🤒 No argument in an `error` event. Or? Probably there is one...
[`stream`:`frameError`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_frameerror_1) 🤔 Interesting...
[`stream`:`streamClosed`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_streamclosed) 🤗 **Actually useful description**, since it describes **how this event relates to the flow of other events**.
[`stream`:`timeout`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_timeout_1) 🙁 What, am I supposed to do? I read the doc for `setTimeout` and it seems I should manually perform things in this event handler...
[`stream`:`trailers`](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_event_trailers) 😂 More flags! 🏳️‍🌈

I realize `http2` is in early stage. But for early adopters and testers, this kind of information is **very** useful if it is provided. I've seen this lack of information before in other modules, so probably the documentation needs an overhaul of the *events* specifically, with exactly *what* is being sent.

**Comment by gireeshpunathil** [comment]
@grantila - is this still outstanding? are you in a position to contribute to the improvement on the documentation?

**Comment by mcollina** [comment]
@gireeshpunathil it would be fantastic if someone went through that list and opened issues (maybe with good-first-contribution label) for all of the events that are missing.

**Comment by ryzokuken** [comment]
@mcollina I could try opening a few this weekend.

**Comment by mcollina** [comment]
awesome! Remember to tag @nodejs/http2 in all of them.

**Comment by ryzokuken** [comment]
Checklist for reference (close the issue once everything is checked off)

- [x] session:close
- [] session:connect
- [] session:error
- [] session:frameError
- [] session:goaway
- [] session:localSettings
- [] session:remoteSettings
- [] session:stream
- [] session:socketError
- [] session:timeout

- [] stream:aborted
- [] stream:error
- [] stream:frameError
- [] stream:streamClosed
- [] stream:timeout
- [] stream:trailers

**Comment by ryzokuken** [comment]
Umm, `socketError` doesn't exist? Perhaps it was removed somewhere down the line? Removing it from the list.

/cc @mcollina

**Comment by ryzokuken** [comment]
Umm, `socketError` doesn't exist? Perhaps it was removed somewhere down the line? Removing it from the list.

/cc @mcollina @nodejs/http2

**Comment by mcollina** [comment]
I think it has been routed to `sessionError` and `streamError`.

**Comment by apapirovski** [comment]
`streamError` also doesn't exist anymore. Whether by accident or intentionally. ping @jasnell

**Comment by mcollina** [comment]
Some part of the code still refer to it: https://github.com/nodejs/node/blob/master/lib/internal/http2/compat.js#L114-L122.

`'streamError'`  makes no sense for core, but it does for compat. That part needs to be refactored a bit, it's still in flux :/.

**Comment by apapirovski** [comment]
@mcollina I know but that error doesn't ever get emitted from core so the comment is somewhat outdated. As I said, it's possible the `emit` got taken out by accident but either way it's not around anymore.

**Comment by ryzokuken** [comment]
Was just wondering: what needs to be done here? I'd be happy to lend a hand.

**Comment by Trott** [comment]
@nodejs/documentation This can probably be closed if we can get a few more things documented per https://github.com/nodejs/help/issues/877#issuecomment-381253464.

**Comment by ryzokuken** [comment]
Thanks, @Trott. I'd love if someone else would like to pick this one up, it's fairly simple to crack. If nobody does, I'll just do it.

**Comment by Trott** [comment]
Maybe good for the NodeConf EU Code & Learn that's happening in a few weeks? /cc @BridgeAR 

I tend to avoid documentation fixes for Code & Learn, but I've been wrong about what types of issues are good for Code & Learn before, so why not assume I'm wrong about that too?  :-D

**Comment by BridgeAR** [comment]
@Trott thanks. I'll try to make a few tasks out of it. In the end each person can choose on their own what they feel comfortable about. I personally feel like it's actually not even that easy to properly document these things without a good understanding of the code, so it's not that trivial.

**Comment by Trott** [comment]
> I personally feel like it's actually not even that easy to properly document these things without a good understanding of the code, so it's not that trivial.

FWIW, the reason I avoid doc changes for Code & Learn is not because I believe doc changes are trivial. On the contrary, it's because even small doc changes are much harder to do well than most people realize.

**Comment by ryzokuken** [comment]
@BridgeAR totally agreed. All these would require the contributor to dive into the `lib` folder, find the appropriate function (sometimes they're not where you'd expect them to be) and figure out what the argument's types should be.

**Comment by gireeshpunathil** [comment]
@ryzokuken - just wanted to know where we stand on this. Are there pending tasks? If so, are these `good-first-issues` or candidates for `code-and-learn`?

**Comment by ryzokuken** [comment]
@gireeshpunathil there have to be! Someone will need to recheck the docs on what has been taken care of already though, since nobody else checked off stuff in my list and I compiled mine a long time ago. Want me to recompile?

**Comment by dev-313** [comment]
Can I take up this issue? Thanks!

**Comment by ryzokuken** [comment]
@dev-313 feel free to! If you need any help, please feel free to ask here or on #node-dev on Freenode IRC.

**Comment by dev-313** [comment]
Thanks @ryzokuken

**Comment by dev-313** [comment]
unable to find stream:streamClosed event. Above mentioned link open Node.js v8.16.2 Documentation page.

**Comment by gireeshpunathil** [comment]
Looks like this got closed because of the `Fixes` tag in https://github.com/nodejs/node/pull/30373

@dev-313 - can you pls confirm all the items that are listed in the checklist (https://github.com/nodejs/help/issues/877#issuecomment-381253464) are covered? If not, are you going to plan to work on those?

Keeping it open until then.

**Comment by dev-313** [comment]
> Looks like this got closed because of the `Fixes` tag in [nodejs/node#30373](https://github.com/nodejs/node/pull/30373)
> 
> @dev-313 - can you pls confirm all the items that are listed in the checklist ([#877 (comment)](https://github.com/nodejs/help/issues/877#issuecomment-381253464)) are covered? If not, are you going to plan to work on those?
> 
> Keeping it open until then.

ok @gireeshpunathil

**Comment by dev-313** [comment]
> Checklist for reference
> ### Http2Session
> 
>     * [x]  session:close
> 
>     * [x]  session:connect
> 
>     * [x]  session:error
> 
>     * [x]  session:frameError
> 
>     * [x]  session:goaway
> 
>     * [x]  session:localSettings
> 
>     * [x]  session:remoteSettings
> 
>     * [x]  session:stream
> 
>     * [ ]  ~session:socketError~
> 
>     * [ ]  session:timeout
> 
> 
> ### Http2Stream
> 
>     * [ ]  stream:aborted
> 
>     * [ ]  stream:error
> 
>     * [ ]  stream:frameError
> 
>     * [ ]  stream:streamClosed
> 
>     * [ ]  stream:timeout
> 
>     * [ ]  stream:trailers
> 
> 
> ### Final
> 
>     * [ ]  Final cleanup PR that cleans up the docs and makes all the argument listings consistent. Resolves this issue.

Checklist for remaining tasks
### Http2Session

- [x]  session:timeout


### Http2Stream

- [x]  stream:aborted

- [x]  ~stream:error~ (Https2Stream 'error' event same as Https2Session so i think no need to change.)

- [x] stream:frameError

- [x] ~stream:streamClosed~ (it might have been removed.)

- [x] stream:timeout

- [x] stream:trailers

**Comment by dev-313** [comment]
@gireeshpunathil All remaining tasks are completed.

**Comment by gireeshpunathil** [comment]
thanks @dev-313 (and others) for doing this!

`Final PR` as referred in https://github.com/nodejs/help/issues/877#issuecomment-381253464 would mean to go through the `http2.md` doc and making sure the doc text is consistent (wordings, construct, style etc.) and if not, make so. I don't think we need to hold up this issue for that; so will close this. If you find anything that needs change, please go ahead a raise a PR; or else, that is it!

thanks again!

**Comment by dev-313** [comment]
Thanks @gireeshpunathil. If i find anything that need change, I'll raise a PR.
