### ISSUE TITLE
Using Node for backup system

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#879]
Hi all,

I am trying to set up a server with Node and the FTP module https://www.npmjs.com/package/ftp  and tar module  https://www.npmjs.com/package/tar 
I want to do this to make backups of all websites I create for my clients. These are relatively straightforward websites, so no large databases with personal info/etc. 
I will start doing this for abou 20 different websites, but my program must potentially be able to backup hunderds or about max 1000 websites on a daily basis.
I was wondering if there would be any objections for using NodeJS to do this? 

Greets

**Comment by bnoordhuis** [comment]
No objections, but why wouldn't you use e.g. rsync or a dedicated backup tool like bacula?

(Not specifically endorsing bacula, it's just of many similar tools.)

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if there is something still outstanding.
