### ISSUE TITLE
Known issues in changelog.

### ISSUE THREAD

**Issue by stevemao** [nodejs/help#88]
Some known issues are listed in changelog https://github.com/nodejs/node/blob/master/CHANGELOG.md#known-issues. But most of the [confirmed bugs](https://github.com/nodejs/node/issues?q=is%3Aissue+is%3Aopen+label%3Aconfirmed-bug) are not. Why?

**Comment by rvagg** [comment]
to be honest, we don't have a solid policy on this, it's been mostly based on impact but the list has also been pretty static for a while with nobody paying attention to updating it

@nodejs/release my feeling on this is that if it's too hard to maintain the list from release to release then we should not even include it. I get the impression that cutting a release is hard enough without adding more tasks to the list so maybe we should trim it down to a simple link?

**Comment by cjihrig** [comment]
I'd be in favor of dropping that section and just linking into the issue tracker.

**Comment by stevemao** [comment]
Well it gives me a wrong impression. EG:

Are these recently introduced in the current release?
Does Node only has 4 or 5 bugs?
The bug "Surrogate pair in REPL can freeze terminal." is more important? or hard to fix so it appears in every new release?

**Comment by cjihrig** [comment]
I can definitely see how this can be confusing. For the record, the surrogate pair REPL bug was first reported in the [io.js 1.1.0 changelog](https://github.com/nodejs/node/blob/master/CHANGELOG.md#2015-02-03-version-110-chrisdickinson).

Also, this has been brought up before in https://github.com/nodejs/node/issues/1484.

**Comment by Fishrock123** [comment]
+1 to dropping it

**Comment by TheAlphaNerd** [comment]
+1 to dropping as well. Alternatively we could introduce a new label from BIG BUGS and generate the list from that

**Comment by Fishrock123** [comment]
@TheAlphaNerd the intention for "known issues" was to list issues effective a specific version. Issue labels can't really do that.

**Comment by TheAlphaNerd** [comment]
Well a label for fixes not yet landed in particular version could be... 

https://github.com/nodejs/node/pull/4819 for example We are likely to do the security release before this fix is landed

**Comment by rvagg** [comment]
Nobody left in favour of keeping "known issues" in its current form so it's being dropped from this week's releases, we can come up with a new approach in the future, perhaps linking to a dedicated label for "serious known issues". If we manage to actually properly use such a label we could even make `changelog-maker` spit out a list for our changelogs.

**Comment by stevemao** [comment]
Closing as we are not including the section in changelog
