### ISSUE TITLE
how many error types in the fs.readFile' callback?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#882]
* **Node.js Version**: 8.7.0
* **OS**: windows pro x64
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: File System
 ### [file system](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_readfile_path_options_callback)
![1](https://user-images.githubusercontent.com/8686739/31576262-a9e7e7f4-b129-11e7-8af5-20424b1b6237.PNG)
 ### [Node server without framework](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework)
![2](https://user-images.githubusercontent.com/8686739/31576332-585dc604-b12b-11e7-9066-a2ae81d19a6b.PNG)

I reviewed below there documents:
* [mdn docs' Error](https://developer.mozilla.org/enUS/docs/Web/JavaScript/Reference/Global_Objects/Error)
* [fs.js source code](https://github.com/nodejs/node/blob/master/lib/fs.js)
* [readFile.js source code](https://github.com/nodejs/node/blob/master/benchmark/fs/readfile.js)

I still don't understand how many errors. 
## Otherwise, nodejs team, whether can you showcase how to write a pure nodejs application without any framework?
# I love nodejs very much!!!!!! 🌹 🌹 🌹

**Comment by vsemozhetbyt** [comment]
As for system errors, see https://nodejs.org/api/errors.html#errors_common_system_errors

**Comment by anlexN** [comment]
@vsemozhetbyt , how much is --max_old_space_size the allowed biggest value?

**Comment by vsemozhetbyt** [comment]
I do not recall any limitations below an available memory, but maybe someone from @nodejs/v8 can tell.

**Comment by hashseed** [comment]
in newer V8 there is no longer a limit to max heap.

**Comment by anlexN** [comment]
where is the newer v8? nodejs v8.7.0?

**Comment by hashseed** [comment]
I don't remember when we lifted the limit, but it was quite a while ago. All Node 8 versions should be fine.

**Comment by vsemozhetbyt** [comment]
It seems to be the V8 5.8:
https://v8project.blogspot.com/2017/03/v8-release-58.html
https://v8project.blogspot.de/2017/02/one-small-step-for-chrome-one-giant.html
So Node.js 8.7.0 definitely has this fix.
