### ISSUE TITLE
N-API: embedding Node, access to environment

### ISSUE THREAD

**Issue by Let0s** [nodejs/help#884]
* **Node.js Version**: 8.x
* **OS**: Windows 7

Hello. I want to embed nodejs via n-api binding. I have an app, which calls node.dll and his function `Start(argc, argv)`. node.dll runs following script to include `sample.node` addon:

```js
var addon = require('./sample');
addon.setRunFunction((code)=>{
  vm.runInThisContext(code);
})
```

Here is a part of addon code in sample.cc
```cpp
napi_value SetRunFunction(napi_env env, napi_callback_info info) {
	napi_status status;
	size_t argc = 1;
	napi_value args[1];
	status = napi_get_cb_info(env, info, &argc, args, nullptr, nullptr);
	assert(status == napi_ok);
	embed::run_function = args[0];//I think, it's not right
	napi_value result;
	status = napi_get_undefined(env, &result);
	assert(status == napi_ok);
	return result;
}

napi_value Init(napi_env env, napi_value exports) {
	embed::env = env; // It's not right, now i know
	napi_property_descriptor descr[] = { "setRunFunction", 0, 
            SetRunFunction, 0, 0, 0, napi_default, 0 };
	napi_define_properties(env, exports, 1, descr);
	return exports;
}

NAPI_MODULE(sample, Init)

```

Also in addon i have file embed.cpp, which contains some interface to connect with app.  Here is some code of embed.h:
```cpp
namespace embed {
// function, used to run script
static napi_value run_function;
//global environment
static napi_env env;

extern "C" {
_declspec(dllexport) void __cdecl RunString(char * script)
}
}
```

And code of embed.cpp
```cpp
namespace embed {
_declspec(dllexport) void __cdecl RunString(char * script)
{
	napi_status status;
	napi_value args[1];
	std::string code = script + '\0';
	status = napi_create_string_utf8(env, code.c_str(), code.size(), &args[0]);
	assert(status == napi_ok); //here is first assertion
	//TODO: use result value
	napi_value result;
	status = napi_call_function(env, nullptr/*??*/, run_function, 1, args, &result);
	assert(status == napi_ok); //and here is second assertion
}
}
```
All runs good until I call `RunScript` from app.
In first assertion status have value `1`, I think it's `napi_invalid_arg`. If I understood right it is because env is empty and `embed::env = env;` is not good way to store environment (and documnetation says that environment must not be stored). 

So my question is: how can i store environment (or take it from some n-api function) to use it later (for example in `RunString`)?

And one more related question: is script, that was run by `Start` node function, still alive when I call `RunString`?

**Comment by Let0s** [comment]
I found simpler way, and I don't need answer anymore

**Comment by w3x731** [comment]
Same question. How to get current env? In example https://github.com/nodejs/abi-stable-node-addon-examples/blob/master/3_callbacks/node-addon-api/addon.cc#L6 callback called in the same function with the same env (instantly). But in my case i dont know what time the callback will called, and when its called i want to get current env.
