### ISSUE TITLE
Nodejs Team, can you write a repo about pure nodejs application without any framework?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#885]

**Comment by tniessen** [comment]
Hi @anlexN,

what exactly do you need? Are you looking for a tutorial on how to use Node.js? What do you want to use Node.js for?

**Comment by anlexN** [comment]
@tniessen , every section in the nodejs document, those' tutorial,  complete showcase on how to use nodejs, one by one!

**Comment by tniessen** [comment]
I believe there are countless examples of node.js applications which only use built-in modules, but I fear we don't have such a repository. What exactly is it you are looking for, how would that benefit you?

**Comment by anlexN** [comment]
I hope i can develope my pure and beautiful nodejs application without angularjs, emberjs, expressjs, and any more. So I hope nodejs team can write complete example on how to use nodejs one by one. nodejs natively is beautiful, pure nodejs can do anything. pure nodejs make any developer understand. Why must use framework? @tniessen , Don't you? I believe many else like me really want to know anything about nodejs! Pureness is the best. javascript is nodejs's heart, nodejs is my heart  ❤️

**Comment by tniessen** [comment]
Sounds like you are trying to reinvent the wheel. Sure, you can implement everything on top of Node.js without using any npm packages, but those packages (or frameworks) are there for a reason. In fact, you don't even need most of the built-in packages, e.g. `crypto`, `path`, `util` etc. can all be implemented in "pure" JavaScript.

We don't maintain any examples beyond our test cases in the nodejs/node repository and those included in the documentation, but the API docs should be a good place to start if you really want to implement everything yourself.

**Comment by anlexN** [comment]
1: I strongly recommand deer nodejs team can maintain these complete examples!
2: ```crypto, path, util etc. can all be implemented in "pure" javascript.``` what you said , to me, is very intersting!!!!!! 😃 😃 😃 @tniessen , can you work hard to document nodejs mudules and pure javascript comparisons? For example , below :

Tables | Nodejs |  javascript
------ |:-------:| ----------:
crypto|            |
 path  |            |
 util    |            |
...       |            |

**Comment by tniessen** [comment]
I still have no idea what you are trying to achieve. Are you actually trying to develop software or are you trying to learn the basics of JavaScript / Node.js? Node.js is just JavaScript with modules on top of that, so if you remove the modules, you are back to basic JavaScript.

**Comment by anlexN** [comment]
what i mean is that nodejs team whether can write actual, practical, complete, detailed showcases to explain every nodejs offcial module (dns, http, errors, zlib and so on)
Take a example: develope weather app, how to pefectly use http module (http.get).
All in a word, nodejs team offcial demonstration!

**Comment by tniessen** [comment]
So you are basically asking for self-contained examples which do not make use of external modules and are complex enough to showcase all features of our API?

I think the closest you will get right now is the API documentation which contains many self-contained examples, and I think this is more useful to most people than longer examples would be. Sometimes, the first sections of an API page contain at least one larger example snippet which shows how to use the core APIs of that module.
If you want to see how you can achieve things such as a "weather app" etc in node.js, look at existing implementations on GitHub / npm. Well, people probably won't just use "pure nodejs" but also npm modules, because that's how node.js works... If you want to learn to use node.js, you will need to learn how to use packages instead of reinventing the wheel each time.

I will keep this open as a suggested improvement.

**Comment by anlexN** [comment]
@tniessen  on your nodejs repo, make a folder to store actual, practical, complete, detailed showcases, ***Would it not be better ?

**Comment by tniessen** [comment]
Feel free to open an issue as a feature request in nodejs/node if you feel like there should be officially maintained examples beyond those in the API docs in node core, or in nodejs/nodejs.org if you feel like such examples should be on the website nodejs.org.

In my opinion the API docs are a very good start to understanding Node.js and how to properly use it, assuming users already know JavaScript.

**Comment by anlexN** [comment]
ok, you got right. @tniessen ,  you always stick to your own opinion. Thank you for hiting my enthusiasm.
