### ISSUE TITLE
Building Node...

### ISSUE THREAD

**Issue by chrisjakins** [nodejs/help#889]
Hello,

I downloaded the recent version from nodejs.org, but cannot find build instructions. How do I install node?

Thanks in advance

**Comment by tniessen** [comment]
Did you see https://github.com/nodejs/node/blob/master/BUILDING.md?

**Comment by chrisjakins** [comment]
Hmm no, thank you.. wonder why that wasn't in the download?

**Comment by chrisjakins** [comment]
So should I download that copy instead? There is a lot of stuff in there that is not in the website download..

**Comment by tniessen** [comment]
> but cannot find build instructions. How do I install node?

Are you trying to build node, to install it or both?

> wonder why that wasn't in the download?

It is included in source code downloads available on nodejs.org. It is not included in binary packages as those are already built, so no build instructions are required.

Installation instructions are available on nodejs.org.

**Comment by chrisjakins** [comment]
I'm not sure I understand the difference... 

Ok that makes sense, thank you. I was able to get it figured out. Thank you for pointing me in the right direction.
