### ISSUE TITLE
nodejs 5.5.0 on Raspberry

### ISSUE THREAD

**Issue by ggemmill** [nodejs/help#89]
Downloaded from nodejs.org/dist/latest, got 5.5.0. make failed for
....../v8_base/deps/v8/src/accessors.o
with 40-plus errors, mostly from handles.h
Have you any solution?
Regards
Graeme

**Comment by bnoordhuis** [comment]
Can you post the complete output from `./configure && make clean all`?  Your bug report amounts to "it doesn't work", not very helpful.

**Comment by ggemmill** [comment]
Thought you might say that - original post was not from the Raspy.
Here it is
Graeme

**Comment by bnoordhuis** [comment]
Did you mean to include a file?  I don't see anything.

**Comment by ggemmill** [comment]
file:///home/pi/Downloads/node-v5.5.0/nodejs.out
Hope this has worked - 
Graeme

**Comment by ggemmill** [comment]
Managed it (I think)
[nodejs.txt](https://github.com/nodejs/help/files/122952/nodejs.txt)

**Comment by bnoordhuis** [comment]
It's the first line of the log. :-)

> WARNING: C++ compiler too old, need g++ 4.8 or clang++ 3.4 (CXX=g++)

**Comment by ggemmill** [comment]
Ah! I tried to install g++ and was informed it was the latest version (4.6.3) available. The installed version of clang++ is 3.0-6.2. I'll have to get on to the package maintainers to ask them when updates will be available. Thanks.
Graeme
