### ISSUE TITLE
zlib problem

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#890]
* **Node.js Version**: 8.7.0
* **OS**: win pro x64
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:  zlib

[Compressing HTTP requests and responses](https://nodejs.org/dist/latest-v8.x/docs/api/zlib.html#zlib_compressing_http_requests_and_responses)

- client :
![default](https://user-images.githubusercontent.com/8686739/31601763-94f96880-b28d-11e7-932e-fc1e9e398e2c.PNG)

- server :
![2](https://user-images.githubusercontent.com/8686739/31601768-97566042-b28d-11e7-8bbe-fcfabbac6118.PNG)

I think server if and else if sentences don't run, always run else sentence. because client  'gzip,deflate' is a string. gzip have only one word boundary, deflate also.

**Comment by addaleax** [comment]
```js
> /\bgzip\b/.test('gzip,deflate')
true
```

There is a word boundary before and after the `gzip` in `gzip,deflate`, so I think this is fine?

**Comment by anlexN** [comment]
If so, test() method ignore any special charactors. @addaleax , do you think so？ ‘gzip,deflate" is just a string, do you think so?

**Comment by addaleax** [comment]
> If so, test() method ignore any special charactors.

@anlexN I don’t think I understand what you mean by this – why special characters? There is a word boundary before `gzip` (because it’s the start of the string itself) and between `gzip` and `,`, because one is an alphanumeric character and one is not… what are the special characters here?

> ‘gzip,deflate" is just a string, do you think so?

Yes :)

**Comment by anlexN** [comment]
@addaleax , thank you!

**Comment by addaleax** [comment]
@anlexN Did this answer your question? :smile:

**Comment by anlexN** [comment]
you are good
