### ISSUE TITLE
http.get and ecmascript Fetch api, what is the better? nodejs, why must write http.get api? why not use Fetch api?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#892]
* **Node.js Version**: 8.7.0
* **OS**: win pro x64
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http

**Comment by vsemozhetbyt** [comment]
If I get this right, `Fetch()` is not a part of ECMAScript, it is a part of Web API, like `XMLHttpRequest` or DOM. You can use [node-fetch](https://github.com/bitinn/node-fetch) though.

**Comment by anlexN** [comment]
@vsemozhetbyt , ok, you get right. 
But let me ask nodejs : why nodejs not to natively support ```Fetch()``` Web API ?

**Comment by vsemozhetbyt** [comment]
I think this links may be useful:
https://github.com/nodejs/node/wiki/node-core-vs-userland
https://medium.com/the-node-js-collection/keeping-the-node-js-core-small-137f83d18152

**Comment by anlexN** [comment]
After i finished those two article, I think they are old view, make no sense.  Did i not read, seriously read?

**Comment by vsemozhetbyt** [comment]
Well, I have no disagreement with the view that Node.js core should be as small as possible insofar as it allows to implement other things in userland modules without much pain. Modularity is a good part of JavaScript design and a strong side of the rich JavaScript ecosystem, why not to use it? :)

**Comment by tniessen** [comment]
Many parts of the Node.js API were designed before certain EcmaScript / Web APIs were implemented in other JS environments, often even before a specification for an alternative solution existed. By now, the ecosystem depends on node's APIs and we cannot simply replace them with new APIs just to get closer to the Web APIs. Some Web APIs are being implemented, e.g. the new [WhatWG URL API](https://nodejs.org/api/url.html#url_the_whatwg_url_api), but each implementation comes at a considerable cost, so we need to make careful decisions here.
