### ISSUE TITLE
how to cache the compressed buffer.

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#893]
* **Node.js Version**: 8.7.0
* **OS**: win pro x64
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: zlib

[Compressing HTTP requests and responses](https://nodejs.org/dist/latest-v8.x/docs/api/zlib.html#zlib_compressing_http_requests_and_responses)
![default](https://user-images.githubusercontent.com/8686739/31606096-be0292e4-b29a-11e7-937c-d292b640ff6f.PNG)

nodejs team, can you give me your prefect practice or recommandation?

**Comment by gireeshpunathil** [comment]
@anlexN - is this still outstanding? If so, please elaborate on the question.
If the question is how to use `compressed buffer`, the example is self-explanatory, but if you have specific doubts, please let me know, I can attempt explaining.

If the question is on what compression to use, it depends on the connection. As explained in the example, first parse the `acceptable encoding` that is coming from the remote endpoint, and then create a stream based on that, add the header appropriately, and pipe the stream into the server response.

Hope this helps!

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding, thanks!
