### ISSUE TITLE
Are nodejs document contradictory ?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#895]
* **Node.js Version**: 8.7.0
* **OS**: win pro x64
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: Erros

One say : 
[Nodejs style callbacks](https://nodejs.org/dist/latest-v8.x/docs/api/errors.html#errors_node_js_style_callbacks)
![default](https://user-images.githubusercontent.com/8686739/31616679-eb27e6fa-b2bf-11e7-83aa-5876a391dbf1.PNG)

But another say : 
[dns.resolve4](https://nodejs.org/dist/latest-v8.x/docs/api/dns.html#dns_dns)
![2](https://user-images.githubusercontent.com/8686739/31616687-f0bc935e-b2bf-11e7-8a6f-0e5db2324855.PNG)

**Comment by vsemozhetbyt** [comment]
I think the first fragment warns against the assumption that try/catch catches throwing inside a callback, while the second fragment does not use try/catch. I.e. you can throw inside a callback if you do not assume this can be caught by try/catch around outer code.

**Comment by anlexN** [comment]
@vsemozhetbyt , are these documents written by you ? How sure are you?

**Comment by vsemozhetbyt** [comment]
Not, not by me. It is just how I read them.

**Comment by anlexN** [comment]
@vsemozhetbyt , who is author?

**Comment by vsemozhetbyt** [comment]
@anlexN These fragments may have many authors in their history. You can try to discover by the blame mode:
https://github.com/nodejs/node/blame/master/doc/api/errors.md
https://github.com/nodejs/node/blame/master/doc/api/dns.md

**Comment by anlexN** [comment]
@addaleax, @jasnell , @apapirovski, @eljefedelrodeodeljefe, and others, can you speak something?

**Comment by apapirovski** [comment]
@vsemozhetbyt seems absolutely correct in his interpretation.

**Comment by jasnell** [comment]
Yes, @vsemozhetbyt is correct
