### ISSUE TITLE
Support for SharedArrayBuffers and Atomics?

### ISSUE THREAD

**Issue by hcphoenix** [nodejs/help#897]
Is there a native module out there providing support for Atomics and SharedArrayBuffers? [I can see they're not supported by default](http://node.green/#ES2017-features-shared-memory-and-atomics-SharedArrayBuffer) but I'm not sure why, and Googling has not been helpful--I'm guessing because this feature is too new, but maybe there are other reasons I don't know about.

Sorry if this isn't the place to ask... I'm new to this and doing my best.
-->

**Comment by addaleax** [comment]
They are behind a flag – `--harmony-sharedarraybuffer` should enable to you test them out.

I don’t think these features can really be implemented by native modules, or at least not comparable to what is implemented as part of the VM itself.

I do think this should show up as flagged on node.green, though … @williamkapke?

**Comment by vsemozhetbyt** [comment]
It seems to be un-flagged in V8 6.2, so it can be available in Node.js 9 (on in nightly builds when https://github.com/nodejs/node/pull/15362 is landed). For now, to test the feature, you can use the flag or one of the last v8-canary builds (currently they already have V8 6.4).

**Comment by krofpt** [comment]
That makes a lot more sense! Sorry, I poked around for a while to see if anyone was using these features in Node yet and got nothing. Refactoring this game engine is going to be interesting, let me tell you what.

Thanks so much~!

**Comment by williamkapke** [comment]
@addaleax yeah, our nightly is still 6.1 so it won't show up on the main node.green page.

If you go to http://node.green/nightly.html, which pulls from the v8 team's build- it's using 6.2 and shows it green.

**Comment by addaleax** [comment]
@williamkapke The question was more, like, why isn’t it showing up as under a flag for V8 6.1? Or am I misunderstanding something?

**Comment by vsemozhetbyt** [comment]
@addaleax Maybe 'under a flag' means only `--harmony` flag for http://node.green/, not the special flags?

**Comment by williamkapke** [comment]
yup- as @vsemozhetbyt just said. The tests only uses the `--harmony` flag (nothing more specific).

... although, I thought it included all `--harmony` _subflags_ (is that the correct term? lol)

**Comment by vsemozhetbyt** [comment]
As far as I understand, including a feature under a `--harmony` flag (V8 bug tracker uses the word 'stage' for this) means the feature is completed ('--harmony (enable all completed harmony features)' — from `node --v8-options` output), i.e. it is some pre-shipping step (where ship == unflag).

**Comment by vsemozhetbyt** [comment]
We can infer this from the comments above [these 3 parts](https://github.com/nodejs/node-v8/blob/16354cecef9ee2ecc62ea32714485106592454dd/deps/v8/src/flag-definitions.h#L194-L236).
