### ISSUE TITLE
Guid class in node.js

### ISSUE THREAD

**Issue by LuciusAterna** [nodejs/help#899]
I am using Node as backend and I was looking for a class that could generate Guid for me. I came across https://www.npmjs.com/package/guid
I installed it as npm install guid.
However, I am not sure how to import it in my class before I can actually use it.

**Comment by tniessen** [comment]
You can use this:

```js
// "Import" package
const Guid = require('guid');
// Create new GUID
const myGuid = Guid.create();
// Print GUID as string
console.log(myGuid.value);
```

You can find more information about the API in their [README](https://www.npmjs.com/package/guid).
