### ISSUE TITLE
About Node js

### ISSUE THREAD

**Issue by users23** [nodejs/help#90]
Hello,

Please tell me about node js and I am new in node js .
I have install node js in localhost and i don't know how to install node js digitalocean cloud server.

**Comment by kelthenoble** [comment]
So.. What's up? Can you be more specific about what you want to know about node.js & there is great `Digital-Ocean Docs` located here -> https://www.digitalocean.com/community/tags/node-js?type=tutorials Go there and they should be just what you're looking for :smile:

**Comment by kelthenoble** [comment]
Closing for now, feel free to reopen.
