### ISSUE TITLE
I recommend, net.isIP(input) returns -1 for invalid strings

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#900]
* **Node.js Version**:  8.7.0
* **OS**: windows pro x64
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: net

[net.isIP(input)](https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_net_isip_input)
many and many source code, -1 is always on behalf of the fault. also let most developers stick out a mile.

**Comment by bnoordhuis** [comment]
This is the wrong repo to post feature requests, nodejs/node is.  That said, your suggestion is unlikely to be implemented because it's backwards incompatible without commensurate benefits.
