### ISSUE TITLE
how to use pure nodejs to expose localhost to internet?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#903]
* **Node.js Version**:  8.7.0
* **OS**: windows pro x64
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: dns, https

***who can tell me there theory ?***

**Comment by tniessen** [comment]
I am not sure I understand your question. What do you mean by "expose localhost to internet"? Do you want a webserver running on your machine to be accessible from the internet? In that case, what's your network setup? Or do you need help with the actual code?

Having read your other questions, I assume "pure nodejs" means that you don't want to use any npm packages.

> who can tell me there theory ?

Okay, theory in short:
1. A process listens on an TCP/IP or UDP port on your machine, e.g. an HTTP server.
2. Your netwok setup allows other hosts to reach that port on your machine, e.g. via NAT and port forwarding if you are behind a router or directly if you are not. You might need to configure the firewall of some or all hosts.

**Comment by anlexN** [comment]
I found [localtunnel](https://localtunnel.github.io/www
) , but i want to achieve equivalent function like localtunnel using pure nodejs. As you said,
no other npm packages.

**Comment by tniessen** [comment]
I am not sure you understand how networking works here. localtunnel appears to use their internal API to expose your machine by tunnelling the traffic through their servers. (An alternative approach would by dynamic DNS and port forwarding if necessary.)

You can use `localtunnel` as a standalone tool and write your application in "pure nodejs", so your application does not need to care about localtunnel at all. localtunnel is not a dependency but rather used in addition to your own program.

If you don't want to use localtunnel and still want to achieve the same in "pure nodejs", it is possible and not even too difficult, assuming you got some public servers which are not behind a router and have a non-dynamic DNS setup. Are you familiar with networking basics?

If you don't have such servers, you can try to use theirs, but
- you could as well use their tool,
- I am not sure it would be legal and
- you are wasting a lot of time reinventing what others already did.

**Comment by lordKnighton** [comment]
I refer you to this page: [ 🔗  link](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework)

As well, You can find an example of that, right here on our website: [🔗  link](https://nodejs.org/en/about/)

---

Closing issue for now, if you need more help 
Let me or @tniessen know & reopen this issue.
