### ISSUE TITLE
console error (a bug known to break npm)

### ISSUE THREAD

**Issue by heyjohnboy** [nodejs/help#906]
* **Node.js Version**: 0.12.18
* **OS**: OS Name:  Windows 8.1 Pro
OS Version: 6.3.9600 N/A Build 9600
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

Installed node 0.12.18 using node-v0.12.18-x64.msi and install appeared to complete successfully, but npm is broken. 

```
C:\Users\myuser>node -v
v0.12.18

C:\Users\myuser>npm -v
C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\lib\utils\unsupported.js:27
        console.error(`a bug known to break npm. Please update to at least ${r
                      ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:19:2
1
    at Object.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm
\bin\npm-cli.js:92:3)
    at Module._compile (module.js:460:26)

C:\Users\myuser>
```

Anyone know how to fix this? I've uninstalled and reinstalled node, and tried to manually update npm, but get the same issue.

<sub>(edited by @addaleax: formatting)</sub>

**Comment by vdeturckheim** [comment]
Are you tied to this version of Node.js ? Can you try with the latest LTS version ?

**Comment by addaleax** [comment]
Just to give context, Node 0.10 and 0.12 are unmaintained and have known, severe security vulnerabilities. Even if it’s not about fixing this specific problem, you probably should still upgrade to at least Node 4.

**Comment by heyjohnboy** [comment]
ok, will give that a try and provide an update.

**Comment by heyjohnboy** [comment]
Uninstalled 0.12 and tried installing 8.7.0. Everything went smoothly and npm is now looking good at v5.5.1. I had tried node 6.x prior to trying 0.12, but had the same issue with 6.x. All looks good with 8.7.0.

Thanks for your help!

**Comment by vdeturckheim** [comment]
@addaleax should an action be taken on that issue?

Closing for the moment, feel free to reopen if I should not have ;-)
