### ISSUE TITLE
How I can save logs to file, using npm module “debug”

### ISSUE THREAD

**Issue by LuciusAterna** [nodejs/help#907]
I am using debug module https://www.npmjs.com/package/debug for logging in my app. How I can save logs to file, using this module??? (I can't change debug module to other, because project is big, and will should refactor much code)

**Comment by addaleax** [comment]
Did you mean to close this? Anyway, I think your options are:

- Inside the app, overriding `debug.log`: https://www.npmjs.com/package/debug#output-streams
- Redirecting all of stderr to some file, which will capture more than just than the `debug` output, but it might just be want you want anyway?
