### ISSUE TITLE
Ubuntu Server Help

### ISSUE THREAD

**Issue by itzpabz** [nodejs/help#909]
* **Node.js Version**: 8.7.0
* **OS**:Ubuntu Server     (BLACK SCREEN WITH WHITE TEXT)
* **Scope (install, code, runtime, meta, other?)**: ???
* **Module (and version) (if relevant)**:  ????

How in the hell do I get NodeJS 8.7.X on Ubuntu Server????

**Comment by tniessen** [comment]
This depends on your requirements. There are three common ways I to install node on Linux:

- via a package manager (presumably `apt` on your machine)
- via nvm
- from source

Personally, I would suggest to use nvm, you can find installation instructions [here](https://github.com/creationix/nvm). Note that nvm works on a per-user basis by default.

If you do not want to use nvm, you can find installation instructions for Debian-based systems [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

If you want to build and install from source, have a look at [this document](https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms).

**Comment by gibfahn** [comment]
@itzpabz let us know if you have any more questions.
