### ISSUE TITLE
Initiate node --inspect / --debug-brk with environment variable

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#910]
I have this question on SO if you want some points:
https://stackoverflow.com/questions/46861128/initiate-node-inspect-debug-brk-with-environment-variable

I have been debugging and inspecting with node-inspector with Node.js for a long time, but I have never seen any documentation that allows you to start the debugging environment with an environment variable.

Does anyone know if I can do this:

```bash
node --inspect-brk foo.js
node --debug-brk foo.js
```

using an env variable instead? something like:

```bash
NODE_INSPECT=yes node foo.js
NODE_DEBUG_BRK=yes node foo.js
```

**Comment by vsemozhetbyt** [comment]
With Node.js 8, you can use `NODE_OPTIONS='--inspect-brk' node foo.js`

https://nodejs.org/api/cli.html#cli_node_options_options

**Comment by ORESoftware** [comment]
ah yes, that will be cool, but yeah I need something to work with Node v6, v7, and v8+
