### ISSUE TITLE
How to include 3rd party node modules (website-scrapper) in electron app that uses electron-prebuilt

### ISSUE THREAD

**Issue by LuciusAterna** [nodejs/help#914]
I have created an electron (windows) app with electron-prebuilt, native node modules and python server. I want to include other node modules like serial-port and web-scrapper with my app. I have installed the modules with npm and the modules get bundled in "app.asar" file. But on using the module with require method in my javascript function throwing "cannot find the module" error. What to do?

**Comment by vsemozhetbyt** [comment]
Sorry, I am a bit confused why do you open and immediately close issues?
