### ISSUE TITLE
Garbage collection changes in 8.7.0

### ISSUE THREAD

**Issue by jeroenvollenbrock** [nodejs/help#917]
* **Node.js Version**: 8.7.0
* **OS**: debian jessie armhf
* **Scope (install, code, runtime, meta, other?)**: runtime

After updating from Node 8.4.0 to Node 8.7.0 (and thus V8 6.0 to 6.1), I noticed some significant changes in the memory profile of our application. There are a lot of spikes as if there is a periodic full garbage collect instead of smaller incremental sweeps. Is this intended behaviour?

<img width="1068" alt="schermafbeelding 2017-10-24 om 12 54 49" src="https://user-images.githubusercontent.com/4551130/31945346-39711c5e-b8cf-11e7-8df9-ee498ccc9d5b.png">
Left side is 8.4.0, right side is 8.7.0.

**Comment by hashseed** [comment]
@mlippautz

**Comment by jeroenvollenbrock** [comment]
@bnoordhuis The spikes themselves are only rarely problematic, but the change in footprint is. Instead of a clear baseline, there is now a huge deviation between the upper-bound and lower-bound of the used memory, with the upper-bound sometimes being as much as 3 times the baseline (see attached image), while the software runs on a device with only 512mb RAM. Before 8.7.0 this has never caused any problems, but now the system starts swapping a lot of memory back and forth to deal with these changes. The spikes themselves only cause problems when they occur simultaneously with a (non-nodejs) speech synthesis thread that plays generated speech over a speaker. The output starts to lag in this case, most likely due to a combination of swapping and higher cpu usage.

The measurements are of the RSS. and taken by `process.memoryUsage().rss / 1024 / 1024`.

![pasted image at 2017_10_24 04_18 pm](https://user-images.githubusercontent.com/4551130/31950918-034ebcae-b8dd-11e7-8ce8-7fcccc54fb17.png)

**Comment by jeroenvollenbrock** [comment]
As a sidenote, I've downgraded Node to 8.6.0, and can confirm the old memory footprint returned.

**Comment by mlippautz** [comment]
There are no incremental sweeps. Full GCs do incremental marking, parallel compaction and concurrent sweeping. Incremental marking is started when being close to some heap limit.

The spikes look like something is allocating a lot of garbage memory at a high rate.

Could you post the output when running with
  --trace-gc --trace-gc-verbose --trace-incremental-marking

**Comment by ofrobots** [comment]
Also, if you are running with any heap limits (e.g. `--max-old-space-size`) it would be good to provide that info too.

**Comment by jeroenvollenbrock** [comment]
I was running with `--max_old_space_size=256` as the only limit. I've now started a test device using `--max_old_space_size=256 --trace-gc --trace-gc-verbose --trace-incremental-marking`. How long would you like it to run?

**Comment by jeroenvollenbrock** [comment]
@mlippautz It's been running for 1 hour now, but it looks like the huge spikes do not show up when running with the trace flags.

![chart 1](https://user-images.githubusercontent.com/4551130/31955857-f9e496b8-b8e9-11e7-8271-81e9819bbad0.png)

[trace-gc.log](https://github.com/nodejs/help/files/1411620/trace-gc.log)

**Comment by mlippautz** [comment]
The flags only print and don't change behavior.

Also, unsurprisingly, the log doesn't show any odd behavior.

**Comment by jeroenvollenbrock** [comment]
I'll restart it and let it run over the night to see if anything changes, as the previous graphs all spanned multiple days.

**Comment by bnoordhuis** [comment]
The GC times are pretty high.  2024 ms average with a 760 ms stddev.
![histogram](https://user-images.githubusercontent.com/275871/31959033-e3fa09dc-b8f3-11e7-9cef-13664ea47c74.png)

**Comment by mlippautz** [comment]
I am looking at the trace-gc.log and cannot observe any pauses > 250ms (which are memory reducing GCs and bigger pause times are expected there).

Are you inspecting sums?

**Comment by bnoordhuis** [comment]
Ah, never mind.  I was looking at 'Total time spent in GC' but that's the sum of all cycles, not total time for an individual GC cycle.

**Comment by jeroenvollenbrock** [comment]
Maybe these logs are of more help, unfortunately the first part of the log got truncated due to the log size, but the captured time span covers multiple spikes.

![chart 2](https://user-images.githubusercontent.com/4551130/31993914-fdf797b0-b97e-11e7-8cdf-32a9bc444abb.png)
[trace-gc.log](https://github.com/nodejs/help/files/1414199/trace-gc.log)
[homey-manager-system.memusage (11).txt](https://github.com/nodejs/help/files/1414200/homey-manager-system.memusage.11.txt)

**Comment by mlippautz** [comment]
Thanks for providing the log. The symptoms are that used memory stays rather stable while committed increases due too scavenges (minor GCs).

@hashseed  @ofrobots Related bug is  https://bugs.chromium.org/p/chromium/issues/detail?id=771966 and even though it was not relevant for chrome it should definitely be backmerged to node.

**Comment by targos** [comment]
https://github.com/nodejs/node/pull/16490

**Comment by jeroenvollenbrock** [comment]
@targos I know it's hard and annoying to give ETA's, but this issue is currently blocking our ability to release software updates to our platform. Would you recommend reverting to Node 8.6.0 for now, or is the PR going to get included in an 8.x release within reasonable time?

**Comment by jeroenvollenbrock** [comment]
Problem seems to be resolved in 8.9.0
![chart 4](https://user-images.githubusercontent.com/4551130/32269789-ac8bcf2a-bef3-11e7-9746-e0c76a209480.png)
