### ISSUE TITLE
node-v6.11.5-x64.msi

### ISSUE THREAD

**Issue by Owned67** [nodejs/help#918]
* **Node.js Version**: node-v6.11.5-x64.msi
* **OS**: Windows 10 pro x64
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

npm is not added to path...
C:\Program Files\nodejs\ is set to path but:
npm install doesn't work, command unknow

**Comment by ProfNandaa** [comment]
What do you get when you type `node` on your command-line? I have a feeling that the issue is with how you've set your path...

**Comment by Owned67** [comment]
Solved with chocolatey install
