### ISSUE TITLE
Should/can I use NPM 3.x with Node 4.x

### ISSUE THREAD

**Issue by lostthetrail** [nodejs/help#92]
I am currently running the latest LTS (Node 4.x) but it comes packaged with NPM 2.x. There are major known improvement to NPM 3.x that might be nice to have.

What are the recommendations around using/not using NPM 3.x with Node 4.x?

**Comment by joshmanders** [comment]
AFAIK there are no recommendations around not using npm@3, usually what I do after installing new versions of Node is run `npm install -g npm@3` and use 3 over provided 2.x that comes with node.

**Comment by lostthetrail** [comment]
Thanks for the reply.
