### ISSUE TITLE
Force Google Chrome to pause at first `debugger;` statement

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#922]
I am launching a Google Chrome browser process using the "chrome-launcher" NPM package

https://github.com/GoogleChrome/chrome-launcher/issues/41

I am trying to figure out how to launch Google Chrome such that it will stop at the first breakpoint or `debugger;` statement so that I can debug the process. Does anyone know how to do that?

**Comment by eugeneo** [comment]
Can you clarify what you are trying to do? Are you trying to debug Node.js application or Chrome application.

Node.js has a `--inspect-brk` command line flag that pauses early and waits for the debugger client (e.g. Chrome DevTools) connection. This way you will not miss any `debugger` statements.

**Comment by ORESoftware** [comment]
yes, but I am not passing arguments to the Node.js executable, I am passing arguments to the Chrome executable..I just thought someone here might know about Chrome since Node.js is built on top of some of the same things

**Comment by eugeneo** [comment]
@ORESoftware it would be better to discuss Chrome-specific stuff on https://bugs.chromium.org/p/chromium/issues/list Feel free to open an issue there and CC eostroukhov@chromium.org.

I am closing the issue here as it does not seem to be relevant to Node.js.
