### ISSUE TITLE
Unable to upgrade to v8.8.0

### ISSUE THREAD

**Issue by xanlaeron** [nodejs/help#924]
### System
* **Version**: 
8.7.0

* **Platform**: 
Linux

* **Distro**:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Pop!_OS 17.10 (Artful Aardvark)"
```

* **Kernel**:

```
4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017
```

****
#### Steps Attempted to Resolve

- Reinstalling nodejs
- Removing nodejs and deleting `/usr/lib/node_modules`
- Running [these](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) commands

     ```
     curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
     sudo apt-get install -y nodejs
     ```

- Installing using `apt`/ `apt-get` followed by running `apt-get clean` and `apt-get -f install`.
- Installing the `nodejs_8.8.0-1nodesource1_amd64.deb` in `/var/cache/apt/archives` using both `dpkg -i` and `gdebi` followed by running `dpkg --configure -a`
- Installing via `nvm` as my last resort. The reason I use the method of installing `nodejs` via apt is because it's a hit or miss _(mostly miss)_ when it comes to installing it using nvm as I tend to get the following `StdErr` quite frequent.

    ```
    nvm needs curl or wget to proceed
    ```

****

#### Output

In spite of the workarounds that I have tried, this is the consistent output that I get.

- `apt` output:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 12.5 MB of archives.
After this operation, 57.8 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_8.x artful/main amd64 nodejs amd64 8.8.0-1nodesource1 [12.5 MB]
Fetched 12.5 MB in 0s (17.3 MB/s)
(Reading database ... 234340 files and directories currently installed.)
Preparing to unpack .../nodejs_8.8.0-1nodesource1_amd64.deb ...
Unpacking nodejs (8.8.0-1nodesource1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_8.8.0-1nodesource1_amd64.deb (--unpack):
 unable to open '/usr/bin/node.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_8.8.0-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

- `gdebi` output:

```
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Node.js event-based server-side javascript engine
 Node.js is similar in design to and influenced by systems like
 Ruby's Event Machine or Python's Twisted.
 .
 It takes the event model a bit further - it presents the event
 loop as a language construct instead of as a library.
 .
 Node.js is bundled with several useful libraries to handle server tasks :
 System, Events, Standard I/O, Modules, Timers, Child Processes, POSIX,
 HTTP, Multipart Parsing, TCP, DNS, Assert, Path, URL, Query Strings.
Do you want to install the software package? [y/N]:y
(Reading database ... 234340 files and directories currently installed.)
Preparing to unpack nodejs_8.8.0-1nodesource1_amd64.deb ...
Unpacking nodejs (8.8.0-1nodesource1) ...
dpkg: error processing archive nodejs_8.8.0-1nodesource1_amd64.deb (--install):
 unable to open '/usr/bin/node.dpkg-new': Operation not permitted
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 nodejs_8.8.0-1nodesource1_amd64.deb
```

**Comment by addaleax** [comment]
This sounds really weird – can you try removing `'/usr/bin/node.dpkg-new` and/or show which permissions the file has (`ls -l '/usr/bin/node.dpkg-new`)?

**Comment by xanlaeron** [comment]
Output for `ls -l /usr/bin/node.dpkg-new`:
```
ls: cannot access '/usr/bin/node.dpkg-new': No such file or directory
```

What makes it even more unusual is that I was already running as `su`.

**Comment by xanlaeron** [comment]
I was able to install the update by building from [source](https://nodejs.org/dist/v8.8.0/node-v8.8.0.tar.gz). It took a while to compile but it worked. :relieved:

I still don't understand why it wouldn't install using other means.

**Comment by addaleax** [comment]
@xanlaeron In any case, there are also tarballs with compiled binaries available for Linux.

I really don’t know why this would happen either.

**Comment by garaboncias** [comment]
I have the same issue on Debian Stretch with 8.9.0 and with 8.9.1 however i can install with this option:
sudo dpkg --force-unsafe-io -i /var/cache/apt/archives/nodejs_8.9.1-1nodesource1_amd64.deb
