### ISSUE TITLE
`node -pe` vs. `node -e`

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#925]
* **Node versions 6,7,8**:
* **OS Darwin**:

I am wondering what the difference is between 

`node -pe "require(x)"`

vs.

`node -e "require(x)"`

It was hard for me to google for the node arguments for the node executable itself

**Comment by addaleax** [comment]
There is none :)

> It was hard for me to google for the node arguments for the node executable itself

Does https://nodejs.org/api/cli.html help?

**Comment by ORESoftware** [comment]
you mean there is no `node -pe` option? Imma bookmark that link

**Comment by ORESoftware** [comment]
@addaleax while I have you on the line, I am wondering if you know if there is an env variable that can initiate a debug env, or if that's only a command line option, don't make me scan the list lol

**Comment by ORESoftware** [comment]
Looks like NODE_OPTIONS will do that, but that's only for version 8 and greater right

**Comment by addaleax** [comment]
@ORESoftware I mean, `node -pe` and `node -p` are the same thing.

> Looks like NODE_OPTIONS will do that, but that's only for version 8 and greater right

Yup, I think that’s what you want. It might get backported to v6.x at some point, I think?

**Comment by ORESoftware** [comment]
That would be cool. +1 for backporting to 7 and 6.

**Comment by addaleax** [comment]
@ORESoftware Node 7 has been unsupported since April. It’s already planned for Node 6 though: https://github.com/nodejs/node/pull/16263

**Comment by ORESoftware** [comment]
Oh that is awesome news thanks!

**Comment by andela-anandaa** [comment]
From checking help `node --help` (excerpt):
```
Options:
  -e, --eval script     evaluate script
  -p, --print           evaluate script and print result
```
So, you basically don't need to qualify `-p` with `-e` (hence `-pe`), `-p` does evaluation + printing. So, you either use `-e` (for only evaluation) or `-p` to print out the evaluation.

Hope this answers you.

**Comment by addaleax** [comment]
@ORESoftware Is there anything left here or should this be closed? :)

**Comment by ORESoftware** [comment]
that's good thx!
