### ISSUE TITLE
Error while installing Canvas

### ISSUE THREAD

**Issue by marcomorettim** [nodejs/help#927]
* **Node.js Version**: v6.11.5
* **OS**: 10.13
* **Scope (install, code, runtime, meta, other?)**: Install Canvas
* **Module (and version) (if relevant)**:

npm install canvas
npm ERR! Darwin 17.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! path /Users/marcomoretti/.npm/nan/2.7.0
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/nan/2.7.0'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/nan/2.7.0'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/marcomoretti/.npm/nan/2.7.0',
npm ERR!   parent: 'canvas' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marcomoretti/npm-debug.log
[npm-debug.log](https://github.com/nodejs/help/files/1422689/npm-debug.log)

**Comment by andela-anandaa** [comment]
Looks like this is n issue with `canvas` itself but not Node. Check filed issues e.g. - https://github.com/Automattic/node-canvas/issues/1023

**Comment by apapirovski** [comment]
Not a node core issue. Please report the issue with node-canvas or npm.

**Comment by marcomorettim** [comment]
Thanks @andela-anandaa & @apapirovski !
