### ISSUE TITLE
NPM dependency resolution - peer dependencies - resolving packages in node_modules that are not direct dependencies.

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#929]
I created this example project

https://github.com/ORESoftware/experimental-npm-project

To my pleasant surprise, peer dependencies seem to be able to require each other.

If you look at the project's source, a can `require('b')` and b can `require('a')`, even though neither declare each other as dependencies. So I am guessing the module resolution algorithm is to start at the top of node_modules and work your way down until you find a matching version of the dependency you are looking for. It looks like Node/NPM does not start from node_modules/a and walk down the tree looking for b, rather it starts at node_modules, and then finds node_modules/b.

My question is - do people know if this behavior has been standard since the first versions of Node and NPM?

I ask because I would like to install module b as a peer dependency of a, without having to declare b as a dependency of a (b is not mentioned in the package.json file at all, of a).

**Comment by ORESoftware** [comment]
I am going to close in favor of a newer issue thanks

**Comment by gibfahn** [comment]
Moved to: https://github.com/nodejs/help/issues/931
