### ISSUE TITLE
Does NodeJS run in Windows CE?

### ISSUE THREAD

**Issue by npurtschert** [nodejs/help#93]
Hi,

I am making some research about NodeJS and would be very interested to know if NodeJS can run in a Windows CE operating system.

I have read about the possibility to cross-compile the binary files in order to generate the installer for the required operating System. Would that be possible for Windows CE?

The embedded device I am trying to test has an ARM Cortex™-A8 processor.

**Comment by kelthenoble** [comment]
@nodejs/platform-windows

**Comment by npurtschert** [comment]
Hi,

sorry but the link shows error 404 o.O

**Comment by kelthenoble** [comment]
no, i was bringing the team to you. Available members from that link will comment & help you out. They have expertise with node in windows.

**Comment by npurtschert** [comment]
Oh ;) hehe. New here xD. Tanks!

**Comment by joaocgreis** [comment]
@npurtschert the current version of node does not support Windows on ARM. This is one of the advantages of supporting the ChakraCore engine. This is still very preliminary work, feel free to follow https://github.com/nodejs/node/pull/4765 and https://github.com/nodejs/node-chakracore . You can try the binaries at https://github.com/nodejs/node-chakracore/releases , but expect issues as there is still a lot of work to do.

**Comment by lordKnighton** [comment]
Closing for now, @npurtschert feel free to reopen and pursue further.
