### ISSUE TITLE
NPM dependency resolution - peer dependencies - resolving packages in node_modules that are not direct dependencies.

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#931]
* **Node.js Versions 6, 7, 8+**:
* **OS => MacOS and *nix **:

I created this example project as a dependency resolution experiment:
https://github.com/ORESoftware/experimental-npm-project

To my pleasant surprise, peer dependencies seem to be able to require each other.

If you look at the project's source, `a` can `require('b')` and `b` can `require('a')`, even though neither declare each other as dependencies. So I am guessing the module resolution algorithm is to start at the top of `node_modules` and work your way down until you find a matching version of the dependency you are looking for. It looks like Node/NPM does not start from node_modules/a and walk down the tree looking for b, rather it starts at node_modules, and then finds node_modules/b.

My question is - do people know if this behavior has been standard since the first versions of Node and NPM?

I ask because I would like to install module b as a peer dependency of a, without having to declare b as a dependency of a (b is not mentioned in the package.json file at all, of a).

**Comment by gibfahn** [comment]
nvm still supports v0.10 of Node, so easiest way to test would be to nvm install that and see if the install still works.

**Comment by richardlau** [comment]
You don't need to guess, the module resolution algorithm is [documented](https://nodejs.org/dist/latest-v6.x/docs/api/modules.html#modules_loading_from_node_modules_folders) and has barely changed since at least 0.10 (and probably earlier).

Note that Node.js only reads the `name` and `main` fields from `package.json`. Other fields such as `dependencies` are particular to package managers (such as npm).

**Comment by ORESoftware** [comment]
@richardlau actually this question has a different nature than the module resolution answer you linked to, I believe, you can look at the example project I linked to and see for yourself

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding, thanks!
