### ISSUE TITLE
How to get `child_process.execFile` to open 2 document windows not 2 applications instances

### ISSUE THREAD

**Issue by chrisvelevitch** [nodejs/help#932]
* **Node.js Version**: Electron 1.7.9
* **OS**: OS X 10.11.6
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: child_process.execFile
1. I'm launching `PhotoShop` twice with 2 different filenames and I'm getting 2 instances of `PhotoShop` running whereas I'm expecting for only one instance of `PhotoShop` to be running with 2 document windows open. How do I do this and is `child_process.execFile` the right function to use?

**Comment by gireeshpunathil** [comment]
Ability to re-use a running application window versus opening a new instance is a capability of the application launcher (in this case Photoshop), and has nothing to do with node.js. If the capability is in-built into `Photoshop` , `child_process.execFile` indeed will realize that. If not, you need to check with the user manual of `Photoshop` to see if it provides a custom launching facility (for example `--singleton` or something), that may also be displayed in the `--help` message when invoked from command line.

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered.
