### ISSUE TITLE
How do I install the security Binary

### ISSUE THREAD

**Issue by asrivastava2017** [nodejs/help#934]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by asrivastava2017** [comment]
This is regarding "https://nodejs.org/en/blog/vulnerability/oct-2017-dos/"
I have upgraded my nodejs version from 6.11.4 to latest LTS 6.11.5.

Do I need to do anything else to make sure the security fix is applied.
If yes , then how do I proceed further.
I found this binary https://nodejs.org/dist/v6.11.1/node-v6.11.1-linux-x64.tar.xz which is mentioned as the security fix. I am not sure what to do with it.

**Comment by shellberg** [comment]
@asrivastava2017 : In the recent past, there have been more than one CVE/security vulnerability.  So, if you have applied the maintenance to get you to the latest LTS 6.11.5 release, then you have addressed the [most recent Windows zlib vulnerability (CVE 14919)](https://nodejs.org/en/blog/release/v6.11.5/) and the last CVE 2017-1000381 (for the issue in the c-ares function) [addressed in 6.11.1](https://nodejs.org/en/blog/release/v6.11.1/), and the cumulative roll-up of all the relevant CVEs to-date.

Patching to maintain currency is the right preventative strategy.  If you're current, you're done!

**Comment by asrivastava2017** [comment]
@shellberg Thanks very much for the confirmation.

**Comment by gibfahn** [comment]
I think this is answered, @asrivastava2017 let us know if you have any more questions.

**Comment by asrivastava2017** [comment]
@gibfahn Yes it is. Thanks very much for the help.
Actually when I saw those binaries I was not sure whether to install or link them separately or to upgrade to existing latest LTS version. 

Stephen already answered that its about updating to latest LTS version. 

Thanks again for the prompt response.
