### ISSUE TITLE
Cannot find module when launch app through simlink

### ISSUE THREAD

**Issue by hebedombiu** [nodejs/help#935]
Version: v8.5.0
Platform: Linux 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I have dir structure:
app
 |- lib -> /other/path/lib
 |- node_modules

When I trying to launch: node lib/app.js
Console output:
module.js:529
    throw err;
    ^

Error: Cannot find module ...
...

But, if I would have dir structure:
app
 |- lib
 |- node_modules

App launch normally

How I could fix this?

**Comment by lordKnighton** [comment]
@hebedombiu Did you fix this issue? And can you show code in app.js

**Comment by ORESoftware** [comment]
yeah just share your project, instead of this unintelligible stuff.

**Comment by richardlau** [comment]
@hebedombiu have you tried the [`--preserve-symlinks` command line option](https://nodejs.org/dist/latest-v8.x/docs/api/cli.html#cli_preserve_symlinks)?
