### ISSUE TITLE
How can I update my nodejs on window OS?

### ISSUE THREAD

**Issue by yangkeou** [nodejs/help#936]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by bnoordhuis** [comment]
When asking questions, it helps to give some background information and an overview of what you tried (and what worked and what didn't.)

**Comment by gibfahn** [comment]
Download the latest installer (for example from here: https://nodejs.org/dist/v6.11.5/node-v6.11.5-x64.msi) and install it. It should overwrite the previous one.

**Comment by tniessen** [comment]
There are Windows installers available on nodejs.org. If you run into problems, try uninstalling the old version before installing the new version.

**Comment by yangkeou** [comment]
@gibfahn  Thank you I do what  you advise to,and this problem has benn solved! thank you!
