### ISSUE TITLE
How to uninstall NodeJS, then reinstall NodeJS on the latest version?

### ISSUE THREAD

**Issue by ItsPugle** [nodejs/help#938]
* **Node.js Version**: 5.5.1
* **OS**: macOS High Sierra 10.13
* **Scope (install, code, runtime, meta, other?)**: Update

I was just wondering how I can completely delete Node and NPM packages from my system?

**Comment by kgrz** [comment]
It would be helpful for if you can share the method of installation. Did you use `brew` to install node?

**Comment by ItsPugle** [comment]
I managed to get it all good :) Thanks, though.
