### ISSUE TITLE
use n latest to update node, Error: invalid version

### ISSUE THREAD

**Issue by msforest** [nodejs/help#939]
* **Node.js Version**: v6.10.3
* **OS**: ubuntu-16.04.3-desktop-amd64
* **Scope (install, code, runtime, meta, other?)**:  update nodejs
* **Module (and version) (if relevant)**:

![image](https://user-images.githubusercontent.com/16268045/32307551-f1b9b36e-bfbb-11e7-84d2-81abc3b9a067.png)

please help

**Comment by vsemozhetbyt** [comment]
It seems it is worth to post an issue in the https://github.com/tj/n, like this one for `lts`: https://github.com/tj/n/issues/469

**Comment by msforest** [comment]
thanks. although this is no valid to me. I try to the cmd to solve problem.
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by frankgo81** [comment]
you can just download the binary from nodejs.org and install the pkg file...
