### ISSUE TITLE
How to build bin for arm linux embedded environment?

### ISSUE THREAD

**Issue by tonyzdf** [nodejs/help#94]
1. Which source I should select? node-v5.3.0.tar.gz or node-v5.3.0-linux-arm64.tar.gz?
    What are the difference of the two source code?
2. Where could I find the operation steps for build nodejs for embedded arm linux environment?

thanks!

**Comment by bnoordhuis** [comment]
> Which source I should select? node-v5.3.0.tar.gz or node-v5.3.0-linux-arm64.tar.gz? What are the difference of the two source code?

The first one if you want to build from source.  The second one contains only binaries.

> Where could I find the operation steps for build nodejs for embedded arm linux environment?

I'm not sure what you're asking here.  `./configure && make`?

**Comment by caiowilson** [comment]
I guess that's exactly what he's asking for. just extract and configure, then make and make install.
Google for build node on linux it's the same as any linux.
Make sure you want the 64bit version which is the one you're referring to. Most cheap SoC are 32. @tonyzdf
