### ISSUE TITLE
Node module version issue with usb on Linux

### ISSUE THREAD

**Issue by lumenier1** [nodejs/help#940]
I've just tried to install usb module for node via npm on Ubuntu (`usb` and then `electron-usb`) but it doesn't work because of the version (look at screenshot https://ibb.co/g57noG).
Is there any way to fix it?

* **Node.js Version**: 7.9.0
* **OS**: Ubuntu 16.04
* **Module (and version) (if relevant)**: Electron 1.7.9, usb, electron-usb

**Comment by bnoordhuis** [comment]
Did you try the hint from the error message, `npm rebuild`?

**Comment by lumenier1** [comment]
Yep, it does not change anything :(
