### ISSUE TITLE
Upgrade Project 0.12.18 to 8.9.0 

### ISSUE THREAD

**Issue by mManishTrivedi** [nodejs/help#941]
Dear Team,

I know, I am already late.
Can I upgrade my project from Node 0.12.18 to latest LTS 8.9.0 ?? or I should upgrade first 4.0/6.0 then move to next ???

**Comment by bnoordhuis** [comment]
That depends on your application and its dependencies.  Without knowing what they are, it's impossible to say.

The best advice I can give you is to just try it.  If v8.9.0 doesn't work, downgrade to v6.x and only if that doesn't work either, try v4.x.

Keep in mind you may also need to upgrade your dependencies as well.

**Comment by mManishTrivedi** [comment]
You are definitely right. :+1: 
Thanks Mate
