### ISSUE TITLE
Multiply SSL-sertificates

### ISSUE THREAD

**Issue by mitroofann** [nodejs/help#943]
* **Node.js Version**: 9.0.0
* **OS**: Any
* **Scope (install, code, runtime, meta, other?)**: other
* **Module (and version) (if relevant)**:

HI there!
I'd like to run a node.js https server with different SSL-certificates for supporting multiple hostnames.
Why din't you realize this feature so far? and if you're going to, when?

**Comment by bnoordhuis** [comment]
You already can.  What exactly isn't working for you?

**Comment by mitroofann** [comment]
Can you give me any simple example of how can I do it?

An example of the v9.0.0 Documentation is this (which can only use one ssl as far as I understand):
```js
const options = {
  pfx: fs.readFileSync('test/fixtures/test_cert.pfx'),
  passphrase: 'sample'
};

https.createServer(options, (req, res) => {
  res.writeHead(200);
  res.end('hello world\n');
}).listen(8000);
```

**Comment by bnoordhuis** [comment]
Check the TLS documentation for SNI (Server Name Indication.)  If something doesn't work, please explain what you tried and what errors you got (if any.)

**Comment by mitroofann** [comment]
It works. Thank you!
