### ISSUE TITLE
npm cache not handling local files

### ISSUE THREAD

**Issue by mdavis777** [nodejs/help#944]
* **Node.js Version**:v8.9.0
* **OS**:Fedora 26 x86_64 and CentOS 7 
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: npm(5.5.1) cache / pacote

If I run npm cache add on a remote tarball such as  "npm cache add https://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz" everything works fine.
However if I wget the same tarball and do "npm cache add grunt-cli-1.2.0.tgz" nothing is added to the cache.  I have tried both relative and absolute paths.

**Comment by rzr** [comment]
Let me crosslink to related issue:
http://lists.openembedded.org/pipermail/openembedded-core/2017-November/143924.html

**Comment by mdavis777** [comment]
As an addition note "npm cache add <directory>" seems to have a similar issue.  Everything succeeds, but nothing is actually added to the cache.

**Comment by mdavis777** [comment]
Looks like it has already been resolved.
I will work on getting a patch put into our side until upstream releases a version with the fix.
https://github.com/npm/npm/issues/16723
https://github.com/npm/npm/pull/18726
