### ISSUE TITLE
Why the buffer requires to pass the offset, better buffer class?

### ISSUE THREAD

**Issue by enemyofthedawn** [nodejs/help#945]
For example `buf.readUInt8(offset[, noAssert])` I wonder why not simply `buf.readUInt8()`? It's just adding the offset. For example take a look at QDataStream of Qt framework.

Also, why int8 and not just boolean? How can I convert int8 to boolean? This is javascript not C++

IMO the official `Buffer` class is really bad and lacking simplicity. Or there should be another class like BinaryStream, BitStream.

I have a client in C++ and server in node and I'm sending binary data to node. I find it really uncomfortable to use `Buffer` class to deserialize my data. I wrote my own class but it would be awesome if we had it officially.

**Comment by gireeshpunathil** [comment]
@enemyofthedawn - there is subtle difference between `QDataStream` and `Buffer` - former is a stream of bytes and the later is a pool of bytes. So while reading from a stream, the most natural reading occurs sequentially, through the head of the stream, whereas from a pool of data, you have the choice of reading from the head (offset 0) or at some arbitrary byte offsets.


```trace
// allocate 4 bytes
> const b = Buffer.alloc(4)
undefined

// set 3rd byte
> b[3] = 1
1
> b
<Buffer 00 00 00 01>

// read 0th byte
> b.readInt8(0)
0
// read 3rd byte
> b.readInt8(3)
1

// read 4 bytes in big endian
> b.readInt32BE(0)
1

// read 4 bytes in little endian
> b.readInt32LE(0)
16777216

// read in BE and place it into a boolean
> const flag = b.readInt32BE(0) == 1 ? true : false
> flag
true
> 
```

> I wrote my own class but it would be awesome if we had it officially.

Please review the Buffer class [implementation](https://github.com/nodejs/node/blob/master/lib/buffer.js) and [documentation](https://nodejs.org/dist/latest-v9.x/docs/api/buffer.html) and if there are improvements possible, PRs welcome!

**Comment by gireeshpunathil** [comment]
ping @enemyofthedawn

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding.
