### ISSUE TITLE
New to node.js how to start using it

### ISSUE THREAD

**Issue by mittalyashu** [nodejs/help#946]
I have installed node.js on my local machine. I have used gulp before, but not familiar how node.js works?

So, how to get started? Do I need a create a `nodefile.js` file, just like in gulp.

**Comment by bloggervista** [comment]
Hello, 
You will only need gulp if you need to run tasks etc like that. For your question it would be better if you learn gulp from their docs.

**Comment by gibfahn** [comment]
@mittalyashu yep, just create a js file (people often go with `index.js` or `server.js`), and then run it with `node index.js`.

If you want to use npm modules, you probably want to do an `npm init` to get started.

After that I suggest you find the section of the node api docs that relates to what you want to do, and copy some examples from there (e.g. https://nodejs.org/api/http.html).

If you want to create a webserver, lots of apps have generators, that generate a "getting started" project, e.g. for express: https://github.com/expressjs/generator#installation

**Comment by bloggervista** [comment]
@gibfahn  this title is misleading. He want how gulp works like that...

**Comment by mittalyashu** [comment]
@gibfahn thanks you.

**Comment by bloggervista** [comment]
@mittalyashu  check out laravel elixir it was made for such thing. It uses gulp.

**Comment by mittalyashu** [comment]
No @bloggervista, you didn't get my point. I want to use node.js

**Comment by gibfahn** [comment]
Gulp is a library (npm module) written in node. If you want to compile sass or jade then the easiest way is to search for an existing library that does what you want.

e.g. if you google "compile sass npm", you get: https://www.npmjs.com/package/node-sass and https://github.com/hellobrian/sass-recipes/tree/master/node-sass.

If you want to implement your own jade or sass compiler then all you need is the node api: https://nodejs.org/api/all.html

**Comment by mittalyashu** [comment]
I have seen in some repository where the developer has written something like this in their `package.json` file.

```json
"scripts": {
    "test": "/*some coding stuff*/"
  }
```

**Comment by gibfahn** [comment]
>I have seen in some repository where the developer has written something like this in their package.json file.

What is your question? Documentation for that is https://docs.npmjs.com/misc/scripts and https://docs.npmjs.com/cli/run-script

**Comment by mittalyashu** [comment]
Thanks @gibfahn.

**Comment by ORESoftware** [comment]
@mittalyashu fyi

```json
"scripts": {
    "test": "/*some coding stuff*/"
  }
```
the above uses something like this:

```js
const cp = require('child_process');
const k = cp.spawn('bash');

k.stdin.write('some coding stuff \n');
k.stdin.end();

k.stdout.pipe(process.stdout);
k.stderr.pipe(process.stderr);
```

so in this way, you can run bash commands from node and act on the results. enjoy :)
