### ISSUE TITLE
Support request - modiffy core modules

### ISSUE THREAD

**Issue by henrix343** [nodejs/help#95]
Where to modiffy core modules ? For example I want to modiffy js - nodejs\node_modules\npm\lib\ there is no fs? How to modiffy it ? Thanks.

**Comment by kelthenoble** [comment]
Sure, if you have the already installed via npm in your `nodemodules folder` (for example)
![screen shot 2016-02-16 at 7 23 09 pm](https://cloud.githubusercontent.com/assets/1773260/13098968/a27d5c30-d4e2-11e5-8417-ecfb62dc0e12.png)

and you can modify the code to your liking or you can of course fork the specific module to your github 
and modify it like that  `for example ` -> 

![screen shot 2016-02-16 at 7 24 16 pm](https://cloud.githubusercontent.com/assets/1773260/13099005/e8fcc34e-d4e2-11e5-8dc7-493d48995ba9.png)

**Comment by SomeoneWeird** [comment]
I'm pretty sure @henrix343 is talking about core modules, like `fs` and `events` etc.

**Comment by kelthenoble** [comment]
Oh!! haha sorry :smiley: , I was enthusiastic about answering this question. Okay so like @SomeoneWeird suggests, you can go to github.com/nodejs/node and find said module and change it like that. We're working on the docs for modifying core modules. Either way, get back to me & we can go from there.

**Comment by henrix343** [comment]
Very nice ansver - but where to modiffy core modules physicaly on the drive? On git I can see https://github.com/nodejs/node/blob/master/lib/fs.js for example, but how can I edit it on my node.js serwer? I need to download it, modiffy and the require in node.js (cause I have heard that there are compiled binary)? Thanks!

**Comment by bnoordhuis** [comment]
@henrix343 You need to (re)build node from source when you edit files in lib/ or src/.

**Comment by kelthenoble** [comment]
+1 

> `@bnoordhuis` You need to (re)build node from source when you edit files in lib/ or src/.
