### ISSUE TITLE
Node v8.9.0 Error: Invalid key length crypto.createCipheriv

### ISSUE THREAD

**Issue by ronovar** [nodejs/help#953]
I have the following code that encrypt strings:

var crypto          = require('crypto'),
    algorithm       = 'aes-128-cbc',  
    key             = new Buffer('9vApxLk5G3PAsJrM', 'utf8'),
    iv              = new Buffer('FnJL7EDzjqWjcaY9', 'utf8');

function encrypt(text, key){
    /* GET - crypted */
    try {
        var cipher  = crypto.createCipheriv(algorithm, key, iv),
            crypted = cipher.update(text, 'utf8', 'hex');

        crypted += cipher.final('hex');
        return crypted;
    } catch(e) { return console.log(e)}
}

console.log(encrypt('blablabla', key))
And when i run this code in node v8.9.0 i get this error:

Error: Invalid key length
    at new Cipheriv (crypto.js:219:16)
    at Object.Cipheriv (crypto.js:217:12)
i try different key and iv lengths but i always get same error...so what it needs to be written key length?

I need to use crypto.createCipheriv because crypto.createCipher is depricied in new node version and new node version as describe developrs is 20% faster that previus version.

**Comment by bnoordhuis** [comment]
Your example works for me.  Check that the key and the IV are both 16 bytes (128 bits) long if you're using aes-128-cbc.

**Comment by ronovar** [comment]
What version of node are you using bnoordhuis? Try using v8.9.0..i now try on v9.0.0 same error...using above example with same key and lv i get same error...and i could not find where is the problem...maybe if you could try on node v8.9.0 to see if you get on your machine same error...

**Comment by bnoordhuis** [comment]
@ronovar I assume it's working for you now since you closed the issue?

**Comment by ronovar** [comment]
Yes it is working..propblem is that i read old value from MySQL database and this way i get correct error about length..i updated in MySQL database key as above posted in code and now it works...thanks
