### ISSUE TITLE
--inspect-brk vs. --inspect --debug-brk in newer Node.js versions

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#955]
Question -

Originally `--inspect` was introduced like so:

```bash
node --inspect --debug-brk   # a
```

then it became for short

```bash
node --inspect-brk           # b
```

my question is - will `a` be available for all foreseeable node versions? or will newer node versions only support `b`?

I am hoping that newer node versions will be backwards compatible such that `a` will always work in the same way that `--inspect-brk` works.

Please advise.

**Comment by bnoordhuis** [comment]
> will a be available for all foreseeable node versions?

I don't see it being removed anytime soon.  That's not quite the same thing as 'all foreseeable node versions', though - forever is a long time.

**Comment by ORESoftware** [comment]
but you can confirm that they are currently equivalent right?

**Comment by eugeneo** [comment]
`--inspect-brk` triggers the same codepath as `--inspect --debug-brk`.
`--debug-brk` alone used to imply `--debug` (legacy debug protocol)
