### ISSUE TITLE
How does nodejs start a jar packet service? how should I better connect to nodejs and restful API services?

### ISSUE THREAD

**Issue by cuiyueshuai** [nodejs/help#956]
I'm developing a desktop app with Electron, I tried to connect to MySQL by calling the Restful API service, so I built a jar packet service with spring boot and maven, and bound ports to form restful API services. but I should how to launch the jar packet service?

I'm trying to use the child_process module to run the Java -jar command to start the service:

```
var childProcess = require('child_process');
var options = {maxBuffer:1024*1024*100, encoding:'utf8', timeout:5000};
var child = childProcess.exec('java -jar *******.jar', options, function (error, stdout, stderr) {
    if (error) {
        console.log(error.stack);
        console.log('Error Code: '+error.code);
        console.log('Error Signal: '+error.signal);
    }
    console.log('Results: \n' + stdout);
    if (stderr.length){
        console.log('Errors: ' + stderr);
    }
});
```

But I think that's the wrong way, the starting effect is very unsatisfactory, so I should how to launch the jar packet service? or how should I better connect to electron and restful Api services?

Please forgive my poor English

**Comment by gireeshpunathil** [comment]
Please evaluate this:

```js
var childProcess = require('child_process');
var options = {maxBuffer:1024*1024*100, encoding:'utf8', timeout:5000};
var child = childProcess.spawn('java -jar *******.jar', options);
child.stdout.on('data', (d) => {
  console.log(d.toString())
})
child.stdout.on('data', (d) => {
  console.log(d.toString())
})
child.('error', (e) => {
  console.log(e.toString())
})
```

The main difference is the usage of spawn over exec and data listeneres associated with that. The advantage is that intermediary data that is produced by the jar service is made available to the parent instantaneously, as opposed to at the end, in the case of exec.


Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered.
