### ISSUE TITLE
cp.spawn

### ISSUE THREAD

**Issue by ariporad** [nodejs/help#96]
Hi All,

I'm really stumped with this issue, and was hoping you might be able to help (or at least confirm that it's impossible, so I can stop wasting my time):

I'm a maintainer of [`shelljs`](https://github.com/shelljs/shelljs), which aims to emulate bash scripting in node. Me and @nfischer have recently taken over the project, and I'm trying to re-work our old (and slightly scary) [`execSync` implementation](http://bit.ly/20E871O), which was written before node had `execSync`.

It has been determined that our `execSync` needs three things:
1. To be synchronous. - We try to emulate bash scripting, so we try to avoid async.
2. Print logs to the console in real time. - For long running commands, we want don't just want to dump out everything at the end.
3. It needs to return `stdout`, `stderr` and the exit code.

Our current implementation spawns a child process (asynchronously) which streams stdout/stderr to a temporary file, which the parent then reads. Once the command exits, the child creates a flag file, which indicates that the command is done. The problem is that our implementation is slow, CPU intensive, and rather complicated.

What I've tried to do to replace it is to use `spawnSync`, set `stdio` to `['ignore', process.stdout, process.stderr]`. Then, we tried to hijack those, somewhat like this:

```javascript
var stdout = '';
var stderr = '';
var out_writev = process.stdout._writev;
var out_write = process.stdout._write;
var err_writev = process.stderr._writev;
var err_write = process.stdout._write;

process.stdout._writev = null;
process.stdout._write = function(chunk, enc, done) {
  stdout += chunk;
  out_write.apply(this, arguments);
};

process.stdout._writev = null;
process.stderr._write = function(chunk, enc, done) {
  stderr += chunk;
  err_write.apply(this, arguments);
};
```

For some reason, this has absolutely no effect.

I guessed that the lack of effect was due to file descriptors bypassing the stream itself, so I tried creating streams on fd's 4 and 5, using `fs.createReadStream` (that didn't work either).

Does anyone have any idea why this is happening, and/or any idea how to accomplish it? (Or can someone at least tell me how much of this I've gotten right?).

Thanks so much!

**Comment by bnoordhuis** [comment]
`spawnSync()` is completely synchronous so monkey-patching process.stdout and process.stderr won't help - nothing in the event loop runs while the child process is executing.

I don't think what you want can be achieved without adding a tee-like child process in between.

**Comment by ariporad** [comment]
I was afraid of that.
Thanks anyway!
