### ISSUE TITLE
Explicitly stream stdio to /dev/null

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#961]
I am trying to pipe the stdout/stderr of a child process to `/dev/null`

I have this:

```js
    const k = cp.spawn('bash');
    ...
    k.stderr.pipe(fs.openSync('/dev/null', 'w'));
```

and I am getting this error:

```error
 TypeError: dest.on is not a function
```

anyone know how to explicitly send stdout/stderr to `/dev/null`

I tried this, which is pretty wrong too apparently:

`k.stdout.pipe({fd: fs.openSync('/dev/null', 'w')});`

and this:

`k.stdout.pipe(null, {fd: fs.openSync('/dev/null', 'w')});`

any help appreciated

**Comment by bnoordhuis** [comment]
You want `fs.createWriteStream()`.  `fs.openSync()` just returns a file descriptor.

**Comment by ORESoftware** [comment]
yeah I don't really know what I was thinking, I was thinking that maybe behind the scenes, `pipe()` would sent up a destination stream given a path to a file or `fd`, but yeah I guess not.
