### ISSUE TITLE
Remote debug node.js

### ISSUE THREAD

**Issue by benag** [nodejs/help#965]
* **Node.js Version**: 8.8.1
* **OS**: ubuntu 14
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I dont manage to remote debug nodejs. I am using chrome and run node on a remote server like this: node --inspect app.js. In chrome://inspect I configured the remote server with the correct address and port. But it doesn't show up (doesn't connect to remote server) . I am using chrome 60 on ubuntu 14. This is really annoying.

**Comment by bnoordhuis** [comment]
What did you do so far to debug the issue?  Can you `nc <address> 9229` from your local machine to the target machine?

**Comment by benag** [comment]
I used telnet
tried several ports:
always getting:
telnet: Unable to connect to remote host: Connection refused

Server is on digital ocean and all ports should be open by default.




2017-11-12 16:57 GMT+02:00 Ben Noordhuis <notifications@github.com>:

**Comment by benag** [comment]
Using telnet i tried several ports getting:
telnet: Unable to connect to remote host: Connection refused
server is on digital ocean and all ports are open by default.

**Comment by bnoordhuis** [comment]
If you haven't set up ssh port forwarding, you need to bind to a public address with `--inspect=0.0.0.0:9229`.

You should restrict access with an iptables rule though, otherwise _anyone_ can access it.

**Comment by benag** [comment]
Works, many thanks , I wish it was more documented.. (or I am the
problematic one..)

2017-11-16 14:38 GMT+02:00 Ben Noordhuis <notifications@github.com>:

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/nodejs.org/pull/1473 - it will be soon.

**Comment by bnoordhuis** [comment]
nodejs/nodejs.org#1473 landed.  I'll close this out.
