### ISSUE TITLE
node can run in iis width fastcgi module(named pipe)？

### ISSUE THREAD

**Issue by cx-emerge** [nodejs/help#966]
* **Node.js Version**: 8.9.0
* **OS**: Windows7 x64
* **Scope**: runtime

node can run in iis width fastcgi module(named pipe)？
same as php-cgi.exe

**Comment by bnoordhuis** [comment]
https://github.com/tjanczuk/iisnode ?

**Comment by cx-emerge** [comment]
fastcgi module(named pipe), not iisnode

**Comment by cx-emerge** [comment]
> [FastCGI](https://fastcgi-archives.github.io/)

* FastCGI is language-independent.
* FastCGI is not tied to the internal architecture of any Web server and is therefore stable even when server technology changes.

**Comment by bnoordhuis** [comment]
I know what fastcgi is, I've written several implementations in the last 15 years... my question, reformulated, is: why is iisnode not good enough?  It's pretty much the best solution for integrating with IIS.

Anyway, check npm for fastcgi libraries, there are several - although probably in various states of disrepair so YMMV.  Hope that helps, I'll close this out.
