### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Matthieu33** [nodejs/help#97]
Hello, I am trying to install nodejs on my Ubuntu x64 but I get errors.
When I run ./configure nothing happens and when I run make install I get an error : 

matthieu@LINUX-de-Matthieu:~/node-v0.12.10-linux-x64/lib/node_modules/npm$ gcc --version
gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1

matthieu@LINUX-de-Matthieu:~/node-v0.12.10-linux-x64/lib/node_modules/npm$ python --version
Python 2.7.8

matthieu@LINUX-de-Matthieu:~/node-v0.12.10-linux-x64/lib/node_modules/npm$ make --version
GNU Make 4.0

matthieu@LINUX-de-Matthieu:~/node-v0.12.10-linux-x64/lib/node_modules/npm$ ./configure
matthieu@LINUX-de-Matthieu:~/node-v0.12.10-linux-x64/lib/node_modules/npm$ make
make: Nothing to be done for 'all'.
matthieu@LINUX-de-Matthieu:~/node-v0.12.10-linux-x64/lib/node_modules/npm$ sudo make install
node cli.js install -g -f 
Makefile:67: recipe for target 'install' failed
make: *** [install] Error 1

Is there anaything I can do about that ?

Sincerely,

Matthieu

**Comment by rvagg** [comment]
Hi @Matthieu33, it looks like you've downloaded a binary version of Node.js, the path name has "linux-x64" in it so it doesn't have the source code and can't be compiled. If you want to compile you'll need to download the node-v0.12.10.tar.gz file and use that.
To use a binary distribution file on your computer you can unpack it like this:

```
tar -zxvf node-v0.12.10-linux-x64.tar.gz --strip=1
```

which will take out that first directory named `node-v0.12.10-linux-x64`. You can even unpack it directly to /usr/local with:

```
tar -zxvf node-v0.12.10-linux-x64.tar.gz --strip=1 -C /usr/local
```

(that may need `sudo`), the only drawback of that approach is that you'll end up with LICENSE.md and some other files in /usr/local.

Inside the tarball you'll have a `bin/` directory with `node` and `npm` in it and a `lib/` directory with npm's main files and some other things. Basically it's structured to live in /usr/local or even /usr, except for the .md files at the top.

**Comment by Matthieu33** [comment]
Ok, thank you very much !
