### ISSUE TITLE
Cross-compile for arm with libc-2.15.so

### ISSUE THREAD

**Issue by shawn-rigdon** [nodejs/help#973]
* **Version: 4.8.6 (and 6.11.3)**:
* **Linux**:
* **Compiling**:
* **N/A**:

BUILDING.md, for nodejs versions 4.8.6 and 6.11.3, claims compatibility with glibc >= 2.5, but the required gcc version for compiling is 4.8 or later.  I am able to successfully compile with the gcc-4.8-arm-linux-gnueabihf tool chain, but the binary then requires GLIBC_2.16.  My target system only supports up to GLIBC_2.15.

Is there a way I can resolve this dependency?  I have tried compiling with gcc-4.6-arm-linux, which links against libc-2.15.so, but I get the gcc version warning from ./configure and subsequent compiler errors.

Also, I tried running the pre-compiled binary from [here](https://nodejs.org/download/release/latest-argon/node-v4.8.6-linux-armv7l.tar.xz).  That will run on my system.  What compiler was used to create it?

**Comment by bnoordhuis** [comment]
The armv7l binary is built on a debian/wheezy box with gcc 4.8 from wheezy-backports.

**Comment by shawn-rigdon** [comment]
Can you provide some detailed instructions for setting up the wheezy box?  I installed the distro on a VM, but I don't see gcc-4.8 available in wheezy-backports main.

Sorry for the delayed reply.  I was assigned to another project just before Thanksgiving.

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/build/blob/0cf9e6a7a55344f33c35154a99b717851e67912b/setup/armv7-wheezy/ansible-playbook.yaml is the recipe we use.

**Comment by shawn-rigdon** [comment]
Is the host machine armv7, or is node being cross compiled?

**Comment by bnoordhuis** [comment]
I'm not 100% sure but I think we do both.
