### ISSUE TITLE
EADDRINUSE while port is not taken (multi-core, high traffic platform)

### ISSUE THREAD

**Issue by PatrickMevia** [nodejs/help#975]
node v8.1.2
OS: Debian GNU/Linux 8 (jessie)

I have a high traffic platform that can reach 2 mln users. To make it happen i need a router file that accepts all the connections and sends users to different server instances (operating on different ports). To accomplish that i am using child_process.fork method. This is the idea:

1. Router starts
2. Server instance#1 is created and accepts connections up to safe 50k users
3. ~50k router starts new server instance
4. repeat 2-3

The problem is that i am getting EADDRINUSE when router is about to create second or third server instance. Sometimes it crates it successfully and fails at third, sometimes it failes at second.

I observed in htop application that node.js has 10 different processes and each one has 12 threads. This most likely is causing the problem, it looks like every process of the same file (router.js) tries to start new server therefore resulting in error.

router.js

	var io = require('socket.io')(4000);

	var connections_current = 0,
		connections_made = 0,
		connections_dropped = 0,
		msg_sent = 0;
	var manager = require('./core/manager')({
		base_port: 3185,
		per_server: 50000
	});
	io.on('connection', function(socket) {
		connections_current++;
		connections_made++;
		socket.emit('redirect', manager.find_server());
		socket.on('disconnect', function() {
			connections_current--;
			connections_dropped++;
		});
	});

manager.js

	module.exports = function(config) {
		return (new function() {
			var cp = require('child_process'),
				servers = [],
				base_port = config.base_port,
				per_server = config.per_server,
				check_servers = function(callback) {
					for(var i = 0; i < servers.length; i++) {
						callback(i, servers[i]);
					}
				};
			this.add_server = function() {
				var port = base_port,
					server = {
						port: port,
						load: 0,
						process: cp.fork(__dirname + '/../server_instance.js', [], {
							env: {
								port: port
							}
						})
					};
				server.process.on('message', function(message) {
					server.load = message.load;
				});
				servers.push(server);
				base_port++;
			};
			this.find_server = function() {
				var min = Infinity,
					port = false;
				check_servers(function(index, details) {
					if(details.load < min) {
						min = details.load;
						port = details.port;
					}
				});
				if(min > per_server) {
					this.add_server();
				}
				return port;
			};
			this.add_server();
		}());
	};

server_instance.js

	var io = require('socket.io')(process.env.port);
	var odds = require('./shared/odds')();
	var connections_current = 0,
		connections_made = 0,
		connections_dropped = 0,
		msg_sent = 0;
	io.on('connection', function(socket) {
		connections_current++;
		connections_made++;
		socket.on('disconnect', function() {
			connections_current--;
			connections_dropped++;
		});
	});
	setInterval(function() {
		process.send({
			load: connections_current
		});
	}, 5000);

How to overcome that problem?

**Comment by danielkhan** [comment]
Before I start diving into your code - this setup does not make much sense for me so far.
Why don't you use the cluster module - or a process manager like PM2. It would distribute the load round robin and not 'start servers' after a number of users is reached. Also please note that you should not start more servers than numbers of cores available on a host. I don't see that your version takes this into account.

**Comment by gireeshpunathil** [comment]
@PatrickMevia - hope your issue is resolved? please let me know
