### ISSUE TITLE
Later version of Node.js is already installed. Setup will now exit.

### ISSUE THREAD

**Issue by akoper** [nodejs/help#976]
Node versions: 6.10 and 8.9
OS: Windows 10 64 bit
Scope: install

I am trying to install node on my PC.  I first went to Node's Web site, downloaded the Windows 8.9 msi, ran it, but that install died after several steps with a fatal error about not being able find something on a drive.  I then got node 6.10 msi, ran it, and that install died with "Later version of Node.js is already installed. Setup will now exit.”  Except the later version of node never got installed.  There is nothing at C:\Program Files\nodejs, and typing "node" and command line returns the error message "not recognized command." I closed and re-started shell and rebooted the PC.  How do I install node 6.10?  What is the solution to this problem?

**Comment by gireeshpunathil** [comment]
@nodejs/platform-windows - ideas?

**Comment by seishun** [comment]
Try installing node 8.9 or later maybe?

**Comment by benjamingr** [comment]
Hey, maybe try uninstalling Node from the "Add or remove programs" before installing the second version. It might appear there if it installed in a "sneaky" place by mistake the first time - or you installed another program that installed Node.

**Comment by tniessen** [comment]
If Node.js 8.9 does not appear in the list of installed programs, this is most likely a bug within WIndows / WiX. If nothing works, can you retry the installation of 8.9 and post the log here if it fails again?

**Comment by akoper** [comment]
Fortunately, this happened at work, and, five days after I filled out a help desk ticket, a PC-support guy came to my desk and fixed this problem.  It had to do with the registry - the installer wasn't there or it didn't point to right place or something.

**Comment by deepbag** [comment]
Change Your NPM Version to LTE
Check please `https://github.com/deepbag/nvs` it's the best solution for this problem.
Node Version Switcher - A cross-platform tool for switching between versions and forks of Node.js

Install NVS ---- Command Line Run Administration Mode
Windows: 

    choco install nvs

Mac|Linux : 

    export NVS_HOME="$HOME/.nvs"git clone https://github.com/jasongin/nvs "$NVS_HOME". "$NVS_HOME/nvs.sh" install

Add LTS Version NVS ---- Command Line Run Administration Mode

    $ nvs add lts

    $ nvs use lts (Output : PATH += ~/.nvs/node/6.9.1/x64)

    $ nvs link lts

    $ npm install -g npm

Successful Your NPM Version Changed and Updated

**Comment by OmarShezan** [comment]
go to `Control Panel>All Control Panel Items>Programs and Features`
uninstall Node JS
reinstall your preferred version from the Node JS website and good luck!
worked for me
