### ISSUE TITLE
Node js exec fails with Sighup signal

### ISSUE THREAD

**Issue by ishanbtr** [nodejs/help#977]
I am facing error while creating a child_process via exec in nodejs. It was working fine under 0.12.x node version, only change is nodejs upgrade to 6.11.3.This error occurs 2 out of 10 times not able to find the reason and solution. Thanks in advance

Code details:

var exec = require('child_process').exec;
cmd = 'sh /home/ec2-user/bin/lldn start';
exec(cmd,{ shell: '/bin/bash'},
function (error, stdout, stderr) {
if (error) {
deferred.reject({
stdout: stdout,
stderr: stderr,
error: error,
cmd: cmd
});
} else {
deferred.resolve({
stdout: stdout,
stderr: stderr,
error: error,
cmd: cmd
});
}
});
Error details:

msg="{ Error: Command failed: sh /home/ec2-
user/bin/lldn start

at ChildProcess.exithandler (child_process.js:198:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:920:16)
at Process.ChildProcess._handle.onexit
(internal/child_process.js:230:5)
killed: false,
code: null,
signal: 'SIGHUP',
cmd: 'sh /home/ec2-user/bin/lldn start' }"

**Comment by bnoordhuis** [comment]
It seems unlikely that it's related to the upgrade.  Something, not node, is sending the child a SIGHUP signal.

Aside: you're effectively running `/bin/bash -c 'sh home/ec2-user/bin/lldn start'` which is kind of superfluous.  Maybe start by fixing that and see what happens.

**Comment by ishanbtr** [comment]
The above command is just an example. I am facing this exception in multiple commands like 
'Command failed: /home/ec2-user/postgresql/bin/psql --port=5432 --username=abcd --host=localhost:9600 --dbname=testDb --set="currentPath=/home/ec2-user/logu/tools/lib" -f /home/ec2-user/logu/tools/lib/setup.sql'.

I am facing this exception in all kind of commands.I am not sure maybe in upper version we have changed something in Nodejs child_process

**Comment by bnoordhuis** [comment]
Do you have a small, isolated test case?  The code you posted is clearly an excerpt, it doesn't run.

**Comment by ishanbtr** [comment]
Agree . I don't have any test case . I am facing this error only on cloud machines not locally.

**Comment by gireeshpunathil** [comment]
> I am facing this exception in all kind of commands

So conversely, can you start with this simple test and see how it goes? If all is well, improve on exec call by adding shell etc. and different commands?

```js
var exec = require('child_process').exec;
exec('pwd', function (e, t, r) {
  console.log(e)
  console.log(t)
  console.log(r)
})
```

**Comment by ishanbtr** [comment]
Hi Gireesh,

I tried such kind of test. Its working fine on local but I am facing the SIGHUP signal on cloud machine. 

I am also trying to handle SIGHUP via

process.on( "SIGHUP", function() {
console.log('SIGHUP ignored and Running CMD =' +cmd );
runCmd(cmd);
});

But I am not successful in handling this issue yet.

**Comment by gireeshpunathil** [comment]
Please try these tests on Cloud itself, that way we can isolate the problem source. Does your Cloud provides a shell for easy testing of scripts such as these?

**Comment by ishanbtr** [comment]
Yup I can run this kind of scripts on my cloud machine.I am not facing this exception in test scripts but in main code scripts 2 out of 10 times. If I run that main code script again it works fine. It seems something related to time.

That's why I am looking for handling SIGHUP and yes if I downgrade nodejs from 6.11.3 to my older version. It works fine. I think that something is changed in EXEC internals.

**Comment by gireeshpunathil** [comment]
thanks for the quick info. If you can do either of:
 - reduce your program to a minimum level until the failure persists
 - improve my program to a level where the failure materializes

and pass it to me along with the OS details (`uname -a`) of your cloud , I can investigate this further.

**Comment by gireeshpunathil** [comment]
ping @ishanbtr

**Comment by ishanbtr** [comment]
Hi Gireesh,

I cannot offer you cloud details. its a company account. Right now this issue is put on hold. 
Please update me if you face such thing or i will update the same if i found the solution

**Comment by gireeshpunathil** [comment]
thanks, closing then. please re-open when you have a recreate / or data to work with. thanks!
