### ISSUE TITLE
child_process read command ran / stdin

### ISSUE THREAD

**Issue by ganna-shmatova** [nodejs/help#98]
Node.js version `4.2.4`
Windows 7 64-bit
child_process.spawn

---

For clarify purposes I want to see the exact command Node.js runs versus the shell/cli. Unfortunately I can't seem to find out how...

Referencing: https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

The returned object from this is an event emitter, but there's no way to sniff events from an event emitter in Nodejs at this time. I've tried `data` &, `pipe` events with no success.

The object returned with `child_process.spawn` has sub-objects: `stdout`, `stdin`, `stderr`. There's exmaples of `stderr` and `stdout` being used as event emitters & these work fine, but I can't find the events emitted by `stdin`...

I know I can just take my input and format it, but this feels prone to failure/inconsistency so I would much rather find a way to sniff what it is actually using.

**Comment by lordKnighton** [comment]
I closed this, because it's been up for a while and not one of me or my co workers got to it, and i assumed you would have solved it in that time. But if not, `reopen` and pursue your answer.
