### ISSUE TITLE
Cannot open Chrome to the right url for debugging Node.js script

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#980]
I run this at the command line:

```
$ node --inspect --debug-brk  test/src/dev/node/define/1.test.js
Debugger listening on ws://127.0.0.1:9229/93a5524a-ae0a-4aa2-a985-3cd6ac6a2b9f
For help see https://nodejs.org/en/docs/inspector
```

normally this commands spits out a url that I copy and paste to the browser. At some point it also auto-opened Chrome to the right url so I could start debugging immediately which was very nice. But now it doesn't log the url to open nor does it auto-open the url! Damn.

Note that the following url is not the right one to open via the address bar:
`ws://127.0.0.1:9229/93a5524a-ae0a-4aa2-a985-3cd6ac6a2b9f`

Anybody seen this with Node.js versions 6+?

**Comment by bnoordhuis** [comment]
Go to `chrome://inspect` first, then enter the `ws://...` URL (if Chrome didn't auto-detect node.js already.)

> At some point it also auto-opened Chrome to the right url

I don't think node.js ever did that.

**Comment by ORESoftware** [comment]
Yeah I was using a Chrome plugin that opened it to the right URL, nvm, thanks

**Comment by parthibansettu** [comment]
Hi I am using Javascript with cucumber and i am trying to add debug feature in the framework using VScode and i am facing "C:\Program Files\nodejs\npm.cmd run-script debug
Debugger listening on ws://127.0.0.1:1337/3a70b3dd-3378-4eae-8517-405e3ae9f3ba"
When i click on "debug" browser is not triggered

Here is my launch.json file

{
// Use IntelliSense to learn about possible Node.js debug attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "launch",
"name": "Debug",
"runtimeExecutable": "npm.cmd",
"cwd": "${workspaceRoot}/nodal/",
"env":{
"NODE_PATH": "${workspaceRoot}/nodal/node_modules"
},
"runtimeArgs": [
"run-script", "debug"
],
"port": 1337
}
]
}

Here is my package.json file
{
"name": "nodal",
"version": "1.1.5",
"description": "End to end UI test automation framework using node,es6,wdio and cucumber",
"main": "index.js",
"scripts": {
"test": "node node_modules/webdriverio/bin/wdio ./config/run_conf.js",
"suitetest": "node node_modules/webdriverio/bin/wdio ./config/run_conf.js --suite login",
"inspect-test": "node node_modules/webdriverio/bin/wdio ./config/run_conf.js --inspect",
"allure-report": "node_modules/.bin/allure generate ./reports/allure-results -c && allure open",
"test1": "npm run test && npm run allure-report",
"junit-report": "node_modules/.bin/junit-viewer --results=./reports/junit-results --save=junit-results.html && open junit-results.html",
"build": "babel feature_generator/server.js",
"start-feature": "nodemon feature_generator/server.js --exec babel-node",
"start-runner": "nodemon test_runner_and_report_generator/server.js --exec babel-node",
"debug": "node --inspect=1337 --debug-brk --nolazy node_modules/cucumber/bin/cucumber-js --tags @debug --format json:./reports/report.json"
},
"author": "TAA",
"license": "AthenaHealth",
"dependencies": {
"4": "0.0.0",
"@athena/app-fabric-logger": "^3.0.0",
"@athena/iam-service-token-manager": "^1.1.1",
"@sinonjs/formatio": "^3.2.1",
"allure-commandline": "^2.5.0",
"assert": "^1.5.0",
"axios": "^0.18.0",
"babel-cli": "^6.26.0",
"babel-polyfill": "^6.26.0",
"babel-preset-env": "^1.6.0",
"babel-preset-es2015": "^6.24.1",
"babel-register": "^6.26.0",
"body-parser": "^1.19.0",
"cookie-parser": "^1.4.3",
"cucumber": "^5.0.2",
"date-time": "^2.1.0",
"express": "^4.16.4",
"graceful-fs": "^4.1.11",
"hoek": "^6.1.3",
"js-yaml": "^3.13.1",
"json-to-pretty-yaml": "^1.2.2",
"json2yaml": "^1.1.0",
"multer": "^1.4.1",
"node-yaml": "^3.2.0",
"opn": "^5.5.0",
"qs": "^6.7.0",
"random-string-generator": "^0.2.0",
"regex": "^0.1.1",
"replace-ext": "1.0",
"rgb-hex": "^2.1.0",
"rgba-convert": "^0.3.0",
"selenium-grid": "^0.5.0",
"tar": "^4.4.6",
"wdio-allure-reporter": "^0.6.0",
"wdio-dot-reporter": "0.0.5",
"wdio-json-reporter": "^0.1.1",
"wdio-junit-reporter": "0.0.2",
"wdio-spec-reporter": "^0.1.2",
"yawn-yaml": "^1.4.0"
},
"devDependencies": {
"chromedriver": "^2.42.0",
"eslint": "^5.16.0",
"eslint-config-standard": "^10.2.1",
"eslint-plugin-import": "^2.17.2",
"eslint-plugin-node": "^5.1.1",
"eslint-plugin-promise": "^3.5.0",
"eslint-plugin-react": "^3.16.1",
"eslint-plugin-standard": "^3.0.1",
"inspect-brk": "^0.1.2",
"node-cmd": "^3.0.0",
"node-dir": "^0.1.17",
"node-uuid": "^1.4.7",
"nodemon": "^1.19.0",
"open": "^6.3.0",
"selenium-standalone": "^6.16.0",
"wdio-chromedriver-service": "~0.1",
"wdio-cucumber-framework": "^1.1.1",
"wdio-screenshot": "^0.5.0",
"wdio-selenium-standalone-service": "^0.0.10",
"webdriverio": "4.13.2"
},
"babel": {
"presets": [
[
"env",
{
"targets": {
"node": "current"
}
}
]
],
"plugins": [
"transform-object-rest-spread"
]
},
"nodemonConfig": {
"ignore": [
"./config",
"./reports",
"./allure-report",
"./page_objects",
"./step_definitions"
]
}
}

can you tell me how to fix this issue ?
