### ISSUE TITLE
How do I get the domain originating the request in express.js?

### ISSUE THREAD

**Issue by saurav2501** [nodejs/help#981]
* **Node.js Version**: v6.10.2
* **OS**: windows10

How do I get the domain originating the request in express.js? If I'm hitting from server2 to get server1 API data then I want to get details of server2 (i.e from which domain request is getting generated).

**Comment by gireeshpunathil** [comment]
http://expressjs.com/en/4x/api.html is where express APIs are explained. Please see if
[req.ip](http://expressjs.com/en/4x/api.html#req.ip) helps you.

**Comment by shellberg** [comment]
@gireeshpunathil has pointed you to the right place for current Express API docs, however, after a brief review of APIs there, you'll perhaps note the Express leverages the built-in 'http' module.  As such, I think what you're asking regarding the server name is really a call to the underlying 'http' module APIs, unless you want to process the IP address as Gireesh directed?  In that respect, perhaps what you want (servername) is found in the result of:

    req.get('host')

**Comment by gireeshpunathil** [comment]
ping @saurav2501

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still not working.

**Comment by alex700** [comment]
`req.get('host')` shows me `backend` instead of name of my virtual host.

**Comment by Elanza-48** [comment]
use `req.hostname` for getting client side `hostname`  if using `express.js`
