### ISSUE TITLE
Decryption of AES GCM 256 does not work (dicpher.end() or decipher.final() throws error)

### ISSUE THREAD

**Issue by kun-zhou** [nodejs/help#983]
Version: v8.9.1
Platform: Darwin
Subsystem: Crypto

```
    var enc_key = crypto.randomBytes(32)
    var iv = crypto.randomBytes(16)
    var data = crypto.randomBytes(32)
    console.log('data',data)
    var algorithm = 'aes-256-gcm'
    var cipher = crypto.createCipheriv(algorithm, enc_key, iv)
    cipher.write(data)
    cipher.end()
    var data_encrypted = cipher.read()
    var decipher = crypto.createDecipheriv(algorithm, enc_key, iv)
    decipher.write(data_encrypted)
    decipher.end() // Error: Unsupported state or unable to authenticate data
    decipher.read()
```
The error exists both with decipher.end() and decipher.final()

**Comment by bnoordhuis** [comment]
Look up the `.setAAD()` and `.setAuthTag()` methods in the crypto docs, they're missing in your code.

**Comment by kun-zhou** [comment]
@bnoordhuis  Thank you so much!

**Comment by joepagan** [comment]
@bnoordhuis can you suggest what `.setAAD()` needs? Cannot see any suggestion on the docs other than it should be a buffer, but of what? randomBytes?
Can we get an example of how we should use it?

**Comment by gireeshpunathil** [comment]
I assume the question is answered through this as well as #1034 . Please let me know if that is not the case.
