### ISSUE TITLE
String memory leaks? (help me understand why the retainers on strings go up)

### ISSUE THREAD

**Issue by Jayflux** [nodejs/help#984]
Version: v8.9.1
Platform: Linux hashweb 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I have an IRC bot who's memory usage goes up ever so slightly every few hours.
When taking snapshots and inspecting with dev tools the memory usage seems to be string objects, and they seem to be coming from the core.

I have a screenshot here:
<img width="1437" alt="screen shot 2017-11-22 at 13 10 19" src="https://user-images.githubusercontent.com/936006/33129193-0527c5d2-cf87-11e7-955a-b8d284378e91.png">

Why are strings like "[object Int8Array]" being stored and remaining there, i've yet to find good docs on the Memory profiler, so not sure how to better debug this, but most of these tree's fall into the core.

Thanks

**Comment by bnoordhuis** [comment]
> i've yet to find good docs on the Memory profiler

Is https://developer.chrome.com/devtools/docs/heap-profiling enough to get you started?  If not, please ask specific questions.

**Comment by Jayflux** [comment]
How can i find out whats storing  "[object Int8Array]"?
When i click on half the rows on the bottom, they look like node internals.

Also whats the order of the list at the bottom, that page you linked is outdated, and unfortunately doesn't really explain the relationship of the retains in the bottom section

**Comment by bnoordhuis** [comment]
Right, it's https://developers.google.com/web/tools/chrome-devtools/memory-problems/heap-snapshots now.

The screenshot you posted is the summary view but you probably want the dominators or comparison view.

Retainers lists the path from the retained object all the way to the GC root.  Ultimately everything can be traced back to a root - any object that isn't reachable from a root is garbage and doesn't show up in the heap snapshot.

**Comment by Jayflux** [comment]
@bnoordhuis  do you know how i could use the data at the bottom to work out whats storing all these strings? btw dominators view has gone now i think, and yes i have been using comparison view already, but the bottom section is the same.
![stringvalues](https://user-images.githubusercontent.com/936006/33154407-05440eb4-cfe0-11e7-850d-15dfd7c98ed2.png)

**Comment by bnoordhuis** [comment]
Those strings are script sources, both of built-in modules and modules loaded from disk.  They stay around, nothing to worry about.

The retainers tab in your screenshot doesn't show anything interesting. :-)

>  btw dominators view has gone now i think

You're right, looks like it's called 'Containment' now.

**Comment by Jayflux** [comment]
ok thanks @bnoordhuis

**Comment by gireeshpunathil** [comment]
closing as answered.
