### ISSUE TITLE
Please help me in understanding `--max_old_space_size`

### ISSUE THREAD

**Issue by ericpaulbasbas** [nodejs/help#985]
* **Node.js Version**: v8.9.1
* **OS**: macOS Sierra v10.12.6 ( 16GB RAM )
* **Scope (install, code, runtime, meta, other?)**: v8-options
* **Module (and version) (if relevant)**: N/A

I'm checking how `--max_old_space_size` behaves and as for my understanding, it should increase the memory that a nodejs instance uses. But I got confused with the results that I got. Please refer to the cases below:

This is the code that I use:
```js
// filename: memtest.js
var arr = [];
var start = 1;
var max = { maxValue };

while (start < max) {
    start = start + 1;
    arr.push(start);
}
console.log(arr.length);
```

### Results:
Case 1:
- maxValue: 75209228
- command: node memtest.js
- result: no errors

Case 2:
- maxValue: 75209229
- command: node memtest.js
- result: `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

Case 3:
- maxValue: 75209229
- command: node --max_old_space_size=2000 memtest.js
- result: no errors

Case 4:
- maxValue: 112813859
- command: node --max_old_space_size=2000 memtest.js 
- result: no errors

Case 5:
- maxValue: 112813860
- command: node --max_old_space_size=`>2000` memtest.js 
- result: `FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory`

From case 4 to 5, with just one addition of an element into the array, for any value more than 2000 for `--max_old_space_size` it's still throwing the FATAL ERROR.

Can anyone explain what's happening here? Thanks.

**Comment by bnoordhuis** [comment]
`--max_old_space_size=...` limits the total size of all objects on the heap.

That doesn't mean a single object can be that big. While not quite as simple as 'arrays can only have up to _n_ elements', individual objects have hard-coded limits.

**Comment by ericpaulbasbas** [comment]
@bnoordhuis Thanks for that quick response. So, it's not necessarily the memory that a nodejs instance uses? So for the test code above, how should I know that it's throwing an error because:
1: nodejs instance runs out of memory because the allotted memory is not enough
2: the system memory is not enough
3: because of the hard-coded limits of the object, as you have mentioned

For `1`, can I use `--max_old_space_size` to increase the allotted memory as what I'm doing in the test cases?

**Comment by bnoordhuis** [comment]
The `invalid array length` error indicates that you went over the per-object limit.

As to the other two, you can't really distinguish between them.  If node/V8 needs to allocate memory from the system but can't, it goes into emergency GC mode in order to reclaim as much heap space as possible.

If that doesn't free up enough space, you get that `CALL_AND_RETRY_LAST Allocation failed` error, same as when you hit the `--old_max_space_size=...` limit.

**Comment by vsemozhetbyt** [comment]
Can the [`os.totalmem()`](https://nodejs.org/api/os.html#os_os_totalmem) / [`os.freemem()`](https://nodejs.org/api/os.html#os_os_freemem) help with the distinction?

**Comment by ericpaulbasbas** [comment]
@bnoordhuis Thanks for that, seems to be clearer now. Just tested it with a new code where when the array hits the hardcoded limits it'll create a new array to continue.

**Comment by ericpaulbasbas** [comment]
@vsemozhetbyt How can I access `os`?

**Comment by gireeshpunathil** [comment]
closing as answered.

**Comment by plee-nm** [comment]
I am assuming setting ```max_old_space_size``` to a smaller number can limit memory usage but I haven't seen this officially documented anywhere.  Can I use ```max_old_space_size``` to limit memory usage or will it just cause the application to error when it reaches the ```max_old_space_size```.  For example if I set my ```max_old_space_size``` to 100 will it consume less overall memory (RSS) than not setting it or will it just cause the application to error if it goes over it.

**Comment by bnoordhuis** [comment]
Depends on your application.  If it can run in 100 MB, it'll be fine.  If its working set is larger, it will terminate when it exceeds the limit.

How do you find out?  By running it and monitoring memory usage.

**Comment by plee-nm** [comment]
@bnoordhuis Thanks for the quick response.  So theoretically setting `max_old_space_size` will make the GC run more aggressively on the old space and it will in turn free up more memory but it may crash the application if it needs more old space memory.  Is setting `max_old_space_size` the only way to reduce memory usage?

**Comment by bnoordhuis** [comment]
That or rewriting your application to use less. :-)

Some people run with `--expose_gc` and call `gc()` at intervals to trigger a major garbage collection.  It can help reduce peak memory usage but of course you're trading time for space.

**Comment by plee-nm** [comment]
@bnoordhuis Thanks for the help.  I actually have a 3rd party agent running monitoring and it causes the memory usage to go way up.  During a load test with it off it never goes above 100mb with it on gets as high as 250mb.  My thought it that during normal slow usage the gc never aggressively sweeps because it is never under stress and the old space slowly grows and grows.
