### ISSUE TITLE
Read in hashbang with node.js

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#988]
If I want to read a file with node.js, to see if the file has a hashbang/shebang, how can I read the first 2 bytes to see what they are?

https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback

I think I just need to read two bytes, to get the `#!` of the shebang

**Comment by vsemozhetbyt** [comment]
I think you need the [fs.read()](https://nodejs.org/api/fs.html#fs_fs_read_fd_buffer_offset_length_position_callback) for that. But beware this cases:
* file can contain BOM in its first bytes.
* `#!` may be 4 bytes if the file is UTF16 encoded.

**Comment by ORESoftware** [comment]
Thanks good thinking, I will read in the first 4 bytes, but maybe I can coerce into utf-8?

what is BOM?

**Comment by vsemozhetbyt** [comment]
[BOM](https://en.wikipedia.org/wiki/Byte_order_mark) can help you to find out the encoding.

**Comment by ORESoftware** [comment]
@vsemozhetbyt  seems like I can read the first 4 bytes, convert to a String, then just check to see if that string startsWith `#!` or will the BOM thing throw that off?

**Comment by vsemozhetbyt** [comment]
@ORESoftware Well, it seems you cannot convert bytes to string with confidence till you know file encoding. You can check if the first bytes are BOM: if so, you can read more and convert them to proper string or just check the bytes themselves; if those first bytes are not BOM, you can suppose them to be ASCII or UTF8 and convert + check for `#!`  or just check the bytes themselves.

**Comment by ORESoftware** [comment]
Ok so this works, but without checking for encoding / BOM:

```js
#!/usr/bin/env node

const fs = require('fs');
const assert = require('assert');
console.log(process.argv);

fs.open(__filename, 'r+', function (err, fd) {

  if (err) throw err;

  const b = Buffer.alloc(4);

  fs.read(fd, b, 0, 4, 0, function (err, bytesRead, buffer) {

    if (err) throw err;

    console.log('bytes read: ', bytesRead);
    console.log('buffer: ', String(buffer))

  });
});
```

this file just reads itself - safe - but how can I account for different file encoding and BOM? can you help?

**Comment by vsemozhetbyt** [comment]
@ORESoftware I can improvise something like this:
```js
'use strict';

const fs = require('fs');

function withShebang(path) {
  const NULL = 0x00;
  const BOM_UTF16LE = [0xFF, 0xFE];
  const BOM_UTF8 = [0xEF, 0xBB, 0xBF];
  const SHEBANG = [0x23, 0x21]; // #!

  const bf = Buffer.alloc(6);

  const fd = fs.openSync(path, 'r');
  fs.readSync(fd, bf, 0, 6, 0);
  fs.closeSync(fd);

  // UTF16LE with BOM: FF FE 23 00 21 00
  if (bf[0] === BOM_UTF16LE[0] && bf[1] === BOM_UTF16LE[1]) {
    return bf[2] === SHEBANG[0] && bf[3] === NULL &&
           bf[4] === SHEBANG[1] && bf[5] === NULL;
  }

  // UTF8 with BOM: EF BB BF 23 21
  if (bf[0] === BOM_UTF8[0] && bf[1] === BOM_UTF8[1] && bf[2] === BOM_UTF8[2]) {
    return bf[3] === SHEBANG[0] && bf[4] === SHEBANG[1];
  }

  // UTF8 without BOM or ASCII: 23 21
  return bf[0] === SHEBANG[0] && bf[1] === SHEBANG[1];
}
```

But you can outsource all the chore to some more reliable module, like [detect-character-encoding](https://www.npmjs.com/package/detect-character-encoding), for example.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still not working.
