### ISSUE TITLE
Open file for reading and executing (but not writing)

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#989]
I am looking at `fs.open()` here:

https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback

I want to open a file for both reading and executing.

it gives these flags:

> 'r' - Open file for reading. An exception occurs if the file does not
> exist.
> 
> 'r+' - Open file for reading and writing. An exception occurs if the
> file does not exist.
> 
> 'rs+' - Open file for reading and writing in synchronous mode.
> Instructs the operating system to bypass the local file system cache.
> 
> This is primarily useful for opening files on NFS mounts as it allows
> skipping the potentially stale local cache. It has a very real impact
> on I/O performance so using this flag is not recommended unless it is
> needed.
> 
> Note that this doesn't turn fs.open() into a synchronous blocking
> call. If synchronous operation is desired fs.openSync() should be
> used.
> 
> 'w' - Open file for writing. The file is created (if it does not
> exist) or truncated (if it exists).
> 
> 'wx' - Like 'w' but fails if path exists.
> 
> 'w+' - Open file for reading and writing. The file is created (if it
> does not exist) or truncated (if it exists).
> 
> 'wx+' - Like 'w+' but fails if path exists.
> 
> 'a' - Open file for appending. The file is created if it does not
> exist.
> 
> 'ax' - Like 'a' but fails if path exists.
> 
> 'a+' - Open file for reading and appending. The file is created if it
> does not exist.
> 
> 'ax+' - Like 'a+' but fails if path exists.

I am guessing opening for reading and executing would be `rx` but that's just a guess, anybody know for sure? There must be a reason it's not listed?

**Comment by ORESoftware** [comment]
Yeah as I suspected, my "guess" was wrong - if I use a made-up flag called "rx" - I get this error - `Error: Unknown file open flag: rx`

**Comment by bnoordhuis** [comment]
> I want to open a file for both reading and executing.

What do you mean by "executing"?

**Comment by ORESoftware** [comment]
I mean this:

`./foobar.js`

as opposed to

`node foobar.js`

**Comment by ORESoftware** [comment]
If you think this answer is good enough, we can leave it at that -
https://stackoverflow.com/questions/47481302/open-file-for-reading-and-executing-but-not-writing

**Comment by bnoordhuis** [comment]
Yes, the poster in the SO issue explained it well.  I'll close this out then.
