### ISSUE TITLE
Cannot compile Node.js 8.9.1 LTS

### ISSUE THREAD

**Issue by e14tech** [nodejs/help#992]
* **Node.js Version**: 8.9.1 LTS
* **OS**: OpenBSD 6.2
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I am attempting to build the Brave web browser and that requires the latest Node.js LTS.

Current system specs other than the ones already given:

clang(++) 4.0.0
libexecinfo-0.3p0v0
Python 2.7.14
GNU Make 4.2.1
CC=/usr/bin/clang
CXX=/usr/bin/clang++

As far as I can tell, I meet all the build dependencies.

I've ran the configure with "--without-intl" flag but it still fails with the next thing.

I've attached the error output from gmake.

[error.txt](https://github.com/nodejs/help/files/1503736/error.txt)

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node/issues/15784 - looks like the same issue.  If you manage to figure out why that particular commit breaks the openbsd build, do submit a pull request. :-)
