### ISSUE TITLE
Websocket buffering problem

### ISSUE THREAD

**Issue by 530140303** [nodejs/help#994]
* **Node.js Version**: v8.9.1
* **OS**: win7 x64
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: [ws](https://github.com/websockets/ws)3.3.2

The client sends a message to the server every 300 milliseconds, and the server sometimes receives several consecutive messages, rather than receiving a message every 300 milliseconds.
It's amazing. It appears on one computer, every time.Other computers don't have this problem. The computer system is win7.
I think it is the messages are buffered on that machine before being delivered until they reach a given size and after that they are sent as a single TCP packet. If that happens the server will receive them all at once.
Last,I'm using the websocket library of [ws](https://github.com/websockets/ws).

**Comment by gireeshpunathil** [comment]
It is working as designed, according to my theory. However, if you observe a consistent behavioral difference in one machine alone while all other systems show differently with the execution environment (network latency, load on the server, concurrent requests etc.) remain the same, can you please check the value of 

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSMQ\Parameters\TCPNoDelay`

being 0?

**Comment by 530140303** [comment]
No, I don't have any of these options, but when I install it, it's the same delay when I set it to 1

**Comment by gireeshpunathil** [comment]
apologies, this is the right registry path:

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{nic}`

where nic is the identifier associated with your IP address.

here is a reference [link](https://social.technet.microsoft.com/Forums/windows/en-US/9f476410-a7a6-4f5d-b9a9-0a63a2bab121/tcpackfrequency-and-nagle?forum=w7itpronetworking)

**Comment by 530140303** [comment]
OK,I try it with what you suggest,but it's not work!!

**Comment by gireeshpunathil** [comment]
I should have asked about the topology first - are client and server both on windows 7? or only server?

Also can you share your code?

**Comment by 530140303** [comment]
No,just client is on windows 7,server is on windows 10.
Code is too sample ,just client send message and server receive message.The client sends a message every 300 ms, and the server immediately returns a message to the client when the message is received.

**Comment by gireeshpunathil** [comment]
thank. My next diagnostic suggestions would be to employ low level TCP flow analyzer tool at client side to validate whether requests leave the system as and when they are made, and then address the server based on that.

But before going that route, pinging @bnoordhuis for an expert opinion.

**Comment by 530140303** [comment]
Yes, I grabbed the packet through the network grab tool and found that the client did send several messages to the server at once.Instead of sending it every 300 milliseconds.

**Comment by gireeshpunathil** [comment]
ok, the coalescence occurs at the client itself, so let us spare the server for now.

we have [request.noDelay](https://nodejs.org/dist/latest-v9.x/docs/api/http.html#http_request_setnodelay_nodelay) that disables nagle's algorithm , but as:

 - the same code works well in other platforms
 - nagle's algorithm only accumulates messages for a duration of 200ms,

I don't see any relevance of this API in the problem context.

**Comment by 530140303** [comment]
OK，I will try again,maybe is the abnormal network cause,anyway,thanks very much!

**Comment by lpinca** [comment]
Could it be the Auto-Tuning feature? Did you try to disable it?

**Comment by gireeshpunathil** [comment]
ping @530140303 - is your issue still outstanding?

**Comment by 530140303** [comment]
Yes, it still exists.

**Comment by gireeshpunathil** [comment]
while turning off the Nagle's algorithm helps in eliminating the delay in sending data, it does not help coalescence of packets - if multiple requests are pushed back to back from the application, before the TCP layer can start processing them.

Does setting a delimiter between data packages help you?
 - a unique character should be selected for delimiter.
- The server needs to parse the message and remove the delimiter to get the message

```js
const WebSocket = require('ws');
const DELIM= '*'
const ws = new WebSocket('ws://localhost:30000')

ws.on('open', function open() {
  setInterval(() => {
    for (var i=0; i< 100; i++) {
        const data = Buffer.alloc(10).fill((97 + Math.round((Math.random() * 26))))
        ws.send(data)
        ws.send(DELIM)
     }
  }, 100)
});
```

**Comment by gireeshpunathil** [comment]
@530140303 - does it help you?

**Comment by gireeshpunathil** [comment]
ping @530140303

**Comment by 530140303** [comment]
I'll try again later. I'm busy at this time.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding, thanks!
