### ISSUE TITLE
How to pass environment variable if it is an array

### ISSUE THREAD

**Issue by ddimitrioglo** [nodejs/help#995]
---
* **Version**: `v6.11.4`
* **Platform**: `Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`

---

Let's assume that we have `test.sh` with content:
```
for item in "${list_variable[@]}"; do echo ${item}; done
```

and we have `test.js`
```
'use strict';

const { exec } = require('child_process');

let env = {
  list_variable: ['one', 'two', 'three']
};

exec('bash test.sh', { env }, (error, stdout) => {
  console.log(stdout);
});
```

I expect to see 
```
one
two
three
```

but receiving: `one,two,three`

Please help me understand the root cause.. 

P.S. Guys from https://github.com/nodejs/node redirected me here.

**Comment by ORESoftware** [comment]
What you want to do:

```js
let env = {
  list_variable: JSON.stringify(['one', 'two', 'three']);
};
```

then parse that in the child process

**Comment by ddimitrioglo** [comment]
Thank you, @ORESoftware!
This is cool workaround if you have control in your bash script, but in my case I don't, I'm wondering if its possible to pass an array, not to transform coma-separated string into array.

Generally it looks like node transforms any data into string...

**Comment by ORESoftware** [comment]
Here's an answer:
https://stackoverflow.com/questions/47936076/log-every-item-in-json-array-in-newline/47936487#47936487

**Comment by ORESoftware** [comment]
Yeah, bash might have some string format for arrays, not sure. But easy to create a comma separated, or newline separate string with node.js, and write that string to the env variable.

**Comment by ddimitrioglo** [comment]
That's the salt...
I do not have access to the bash, and it needs that env variable to be an array.

**Comment by ORESoftware** [comment]
yeah dunno :)  I am not sure if you can construct a bash array with just a string format

http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_10_02.html

**Comment by bnoordhuis** [comment]
> Generally it looks like node transforms any data into string...

That's because environment variables are strings.  You can't make it work for the same reason why `env list_variable="..." bash test.sh` won't work.

I guess you could do something like this:
```js
const s = 'list_variable=(one two three)\n' + fs.readFileSync('test.sh', 'utf8');
child_process.spawn('bash', ['-c', s]);
```

**Comment by ORESoftware** [comment]
I asked this question just now - in general unix.stackexchange.com is your friend - nicer people on their than stackoverflow :)

https://unix.stackexchange.com/questions/412454/construct-bash-array-with-only-string-format

**Comment by ORESoftware** [comment]
@ddimitrioglo I think @bnoordhuis is onto something

**Comment by gireeshpunathil** [comment]
looks like this is answered and resolved, @ddimitrioglo please let me know if that is not the case.

**Comment by ddimitrioglo** [comment]
In this particular use-case - it's ok, but it still a workaround, and we will face the issue again by running not a bash file but an binary (for example `terrraform plan` command (https://www.terraform.io/docs/commands/plan.html), where I can pass vars like `TF_` prefixed environment variables)

**Comment by gireeshpunathil** [comment]
@ddimitrioglo - As I understand, this is not a node.js programming issue, rather a fundamental limitation on passing user defined types such as arrays into child processes, right? in other words, there is no evidence that this is feasible in any other language / framework etc. (The bash documentation refers this as a limitation)

I would suggest usage of arrays intrinsic to the program where they are created and used. In other scenarios, consider delimited environment variables (if the values are discrete) or configuration files if the list is big, and modify the consuming code accordingly. [ I read as you mentioning the consuming code cannot be modified, but I don;t see any other solution for this]

Hope this explanation helps.

**Comment by gireeshpunathil** [comment]
closing as answered.
