### ISSUE TITLE
[Question] Does Node.js use a fuzzer?

### ISSUE THREAD

**Issue by 6-8-axnw1bom81v5xa3nh48c** [nodejs/help#996]
I'm wondering does Node.js use any [fuzzer](https://en.wikipedia.org/wiki/Fuzzing)? I mean, the Node.js code is huge, so how can you be sure everything works properly? Do you use some random code generator to test Node.js, and if yes, which one?

Thanks. BTW, Node is aweome project, thanks for writing and sharing open source software.

**Comment by bnoordhuis** [comment]
No fuzzing is done.  It's been discussed in the past but the difficulty is in writing a fuzzer that doesn't generate a ton of false positives.  We have a pretty extensive test suite and support for ASAN/MSAN/etc., though

V8, the JS engine, does use a fuzzer (libfuzzer+clusterfuzz, IIRC) but sandboxed JS is a lot easier to fuzz than code that interacts with the outside world (i.e., deals with I/O.)

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
Thanks.
