### ISSUE TITLE
Multiple DB Connection issue at same time in nodejs

### ISSUE THREAD

**Issue by christopher-hirudayasamy** [nodejs/help#997]
* **Node.js Version**:v4.2.6
* **OS**:Linux
* **Sql server**:2012

We are using Jenkins and Gitlab for continuous integration. Using web hooks, jobs are triggered when merge requests and commits are done.

We are storing some required values into database from web hook post data.

The below code is used to store the values into the database

**Code:**

    var sql = require('mssql')
    var dbconfig = {
        server: 'xxxx',
        database: 'xxxx',
        user: 'xxx',
        password: 'xxx',
        port: 'xx'
    };
    try {
        console.log('db out '+mergeid);
        sql.close();
        console.log('db in '+mergeid);
        var connection = sql.connect(dbconfig, function (err) {
    
            if (err) console.log(err);
           console.log('DB connected');
              console.log('db after connected '+mergeid);
            var sqlquery = '';
            var request = new sql.Request();
            //query to the database and get the repo value
            sqlquery = 'select Repo from verylargetable';
            request.query(sqlquery, function (err, result) {
                if (err) console.log(err)
                var repo = result.recordset[0].Repo;
    
                //query to the database and get the commit value
                sqlquery = "select Commit from verylargetable where Repo='" + repo + "'";
                request.query(sqlquery, function (err, result) {
                    if (err) console.log(err)
                    var comm = result.recordset[0].Commit;
    
                    //query to the database and update the table
                    sqlquery = "UPDATE verylargetable set Repo='" + repo + "', WHERE Comm='" + comm + "'";
                    request.query(sqlquery, function (err, result) {
                        if (err) console.log(err)
                        console.log("record(s) updated");
                    });
                });
            });
        });
    }
    catch (e) {
        console.log("===========Exception Occurred==========");
        console.log(e);
        console.log(new Date().toString());
        console.log("==========================================================");
    } 

**Output:**
              
2017-11-20 18:10: db out 99

2017-11-20 18:10: db in 99

2017-11-20 18:10: db out 101

2017-11-20 18:10: db in 101

2017-11-20 18:10: db out 100

2017-11-20 18:10: db in 100

2017-11-20 18:10: DB connected

2017-11-20 18:10: db after connected 100

**Scenario:**

When two or more merge requests are given at the same time the last merge request values only inserted into the database.

Here I created three, merge request 99,100,101 respectively. All the three, merge requests are created at the same time.
              
sql.close() method is closed first two merge request (99,101) before the values are entered into database  since all merge requests came to access at same time.

The last one merge request(100) alone inserted into database.

Please look at the output for detailed information.
              
**Issue:**

1.How to handle multiple DB request at a time in node js with mssql?

2.We faced **global connection already exists issue** before when tried to establish the connection between node js and mssql since I have used sql.close() method at the beginning of connection. Whether this approach is correct?

Kindly provide a solution to this.

**Comment by ORESoftware** [comment]
If there is a database connection error, you need to return from the routine early

```js
 if (err) console.log(err);
```

should become

```js
 if (err) {
   return cb(err);
 }
```

if there is an error, your connection won't have been made. if there is an error, your resultset will not be available.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if it is still outstanding.
