### ISSUE TITLE
Can't install 8.9.1 LTS (x86) in Windows 10

### ISSUE THREAD

**Issue by vrunrun** [nodejs/help#998]
* **Node.js Version**: 8.9.1 LTS
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

I can't install node.js from the msi installer in Windows 10 and encountered a rollback problem during install. Pls help. Thx.

**Comment by bnoordhuis** [comment]
What error?

**Comment by vrunrun** [comment]
Helllo, the wizard just rollback during installation displayed "Node.js Setup Wizard ended prematurely because of an error ... (see attached).

![error](https://user-images.githubusercontent.com/34092207/33376060-2fff8400-d547-11e7-954c-c3d66363a680.JPG)


Windows Event Log
Log Name:      Application
Source:        MsiInstaller
Date:          11/29/2017 8:41:59 PM
Event ID:      1033
Task Category: None
Level:         Information
Keywords:      Classic
Description:
Windows Installer installed the product. Product Name: Node.js. Product Version: 8.9.1. Product Language: 1033. Manufacturer: Node.js Foundation. Installation success or error status: 1603.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MsiInstaller" />
    <EventID Qualifiers="0">1033</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-11-29T12:41:59.843834900Z" />
    <EventRecordID>14477</EventRecordID>
    <Channel>Application</Channel>
  </System>
  <EventData>
    <Data>Node.js</Data>
    <Data>8.9.1</Data>
    <Data>1033</Data>
    <Data>1603</Data>
    <Data>Node.js Foundation</Data>
    <Data>(NULL)</Data>
    <Data>
    </Data>
    <Binary>7B38383345434334362D334545442D343936302D423931322D3143464146344138424442377D3030303063363036663764643563623663616132323037346139303563393736376161373030303030393034</Binary>
  </EventData>
</Event>

**Comment by bnoordhuis** [comment]
Can you try unchecking the 'Event tracing (ETW)' option?

**Comment by vrunrun** [comment]
Great! Installation is completed. Thks.

**Comment by bnoordhuis** [comment]
Good to hear!  I'll close out the issue.

**Comment by chitgoks** [comment]
im experiencing the same issue iwth 8.9.3

disabling event tracing didnt work

**Comment by a-teammate** [comment]
Why is this closed if this is not fixed? O.o
providing a workaround is not a fix.

The bug is still there with 8.9.4.

**Comment by bnoordhuis** [comment]
Because it's a local permissions issue, not a bug in the installer.

**Comment by a-teammate** [comment]
ah okay.
No i haven't noticed, thx.

**Comment by GuruLahima** [comment]
I have Win 10 x64, installing node-v8.11.2-x64, I unticked both ETW and performance counters (because when I unticked only the performance counters it still didn't work), and it works now.
